### ISSUE TITLE
Feature request: crop apply button

### ISSUE THREAD

**Issue by byrning** [photopea/photopea#10]
This is a more of a feature request related to usability, than a bug.

When one uses the crop tool, it's not completely obvious that one must hit enter in order for the crop to apply - I've had clients with this issue. Having an "apply" button, similar to other apps, would sort that out.

Thanks!

**Comment by photopea** [comment]
I totally agree! Especially on mobile devices, where you don't have a keyboard to press Enter. It will add it in the next release.

**Comment by photopea** [comment]
We just added a Crop Apply and Crop Cancel buttons. They appear after creating a crop rectangle. Thank you very much for your help :)

**Comment by byrning** [comment]
Awesome, thanks!
