### ISSUE TITLE
Drop area [bug]

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#100]
Hi,

what about drop area for all window width, height?
If I try drag & drop picture to no-project photopea browser open just image. Same if I was try drop to photopea "header".

Screen record: https://www.youtube.com/watch?v=BWDc_uE9YBY&feature=youtu.be

**Comment by photopea** [comment]
Hi,

it was fixed. Thank you for your cooperation! :)

**Comment by landsman** [comment]
Nice! Thanks
