### ISSUE TITLE
Can't "copy merged" when layers group is selected on layers palette 

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1000]
As in the title.
It should copy merged layers to clipboard, even when I'm on folder with grouped layers in layers palette. Now it doesn't work in Photopea.

When I make that, it shows "copied area is empty"

**Comment by photopea** [comment]
Yeah, Copy Merged just copies the total image at the moment. But since we have partial rendering available now, it should be easy to implement.

**Comment by MichalSZZ** [comment]
The same thing with making "copy merged" when being on adjustment layer.

The same but different :) When I am on raster layer who are clipped to object (who makes a mask for her). It should "copy merged", what user see on the screen, but it copy layer without clipping mask effect.

**Comment by photopea** [comment]
Hi, I can do "Copy Merged" both when a group is selected, and when an adjustment layer is selected. I can do it with both Ctrl+Shift+C, and with Edit - Copy Merged.

What exactly did you do?

**Comment by photopea** [comment]
I am closing it because of lack of details :(
