### ISSUE TITLE
[Intersect, Unite, Subtract, Exclude] for Pen and shape

### ISSUE THREAD

**Issue by sonamdawa101** [photopea/photopea#1001]
Photopea is great that it support both vector and raster images to work with. Here I got one problem while working on a vector drawings.

**[Intersect, Unite, Subtract, Exclude] work perfectly between basic shapes by turning them as path. But can't work with pen tool set to path.**

I want to draw a shape with pen and use it to Intersect, Unite, Subtract, Exclude with other shapes/path.

**Is it possible to have  [Intersect, Unite, Subtract, Exclude] to the pen tool ( during set as path)**

![path](https://user-images.githubusercontent.com/36448436/47151836-859a3b80-d2f8-11e8-818b-0ea12ecbe3b1.png)

**Comment by photopea** [comment]
Hi, I fixed it! Thanks for suggesting it.

BTW. you can change this combination function for any existing path, or reorder paths, using a Path Select tool, see https://www.photopea.com/learn/vg-manipulation

**Comment by photopea** [comment]
Hi, I fixed it. You can change this boolean function later for any path using the Path Select tool https://www.photopea.com/learn/vg-manipulation
