### ISSUE TITLE
Croped layer thumbnail after switching from an external monitor or projector

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1002]
https://youtu.be/PaeL9flxRXc

I saw that yesterday after switched off from projector.
Today I have same issue after switching from external monitor to laptop display (retina).

Mac OS High Sierra 10.13.6 retina 13'
Chrome 69.0.3497.100

**Comment by photopea** [comment]
Hi, this look so strange. I have absolutely no idea, what could cause it. Could you try to play with the page zoom, and reproduce such behaviour?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
