### ISSUE TITLE
Strange result after making content-aware fill

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1003]
I try to make this tutorial in Photopea https://www.youtube.com/watch?v=azsfUXCxtO8 

When I try to remove woman from background (https://youtu.be/azsfUXCxtO8?t=297) using content aware fill, it makes very sharp content in some places

look
![37569513776_7fde6a4eef_o 1](https://user-images.githubusercontent.com/38118273/47188618-0ed16280-d339-11e8-9377-e308398c8d05.jpg)
![37569513776_7fde6a4eef_o 2](https://user-images.githubusercontent.com/38118273/47188701-61ab1a00-d339-11e8-896f-2d80a29b7940.jpg)

I can make final effect from this tutorial in Photopea, but content aware fill doesn't work how I expected...

BTW. In this tutorial https://youtu.be/azsfUXCxtO8?t=213 it shows how to use layer mask view, who was asked by @kevintey in this issue #980

**Comment by MichalSZZ** [comment]
It looks like it's from her hair, but why? selection was bigger than woman (like on tutorial)

Here is a link to the oryginal photo https://www.flickr.com/photos/psdesire/37569513776/ try do it yourself

**Comment by photopea** [comment]
I looked into it, but can not see any problem. Seems like the algorithm thinks, that it is an appropriate result.

Our current method of content-aware fill is too complicated and slow. I think we need to replace it by something simpler and faster.
