### ISSUE TITLE
Can't draw selection who are outside of image canvas by rectangle selection tool

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1004]
As in the title. Any others selections work good in that way. 
I want to subtract something from selection that I've made (but was bigger than project canvas size) and I couldn't by the rectangle selection tool

**Comment by photopea** [comment]
Hi, we made it work like in Adobe Photoshop some time ago: https://github.com/photopea/photopea/issues/529

**Comment by MichalSZZ** [comment]
Hi,
look at that https://youtu.be/YI1ykEKx4cI 

In Photopea I like that I can make selection from layer pixels (even from pixels outside the canvas), but I want to subtract sometimes unnecessary selection. Now I can't draw outside with rectangle selection tool.

**Comment by photopea** [comment]
Hi Michal, I implemented it, because users wanted it to work like in Photoshop. Could you find out, how to do this in Photoshop? 

My quick idea is: You can subtract the top part with an Ellipse selection or the Lasso.

**Comment by MichalSZZ** [comment]
OK it works with polygonal lasso tool :)

In my movie I compared Photopea with Photoshop. PP work different with making selection from layer (ctr + click on layer thumbnail). In my opinion - better. 
It calls all pixels, even that pixels who are outside of project canvas.
Photoshop make selection from layer but cut it to canvas size (when I fill selection with color and want to move e.g. layer up after fill, I have problem in Photoshop)

**Comment by MichalSZZ** [comment]
OK i checked that one more time in Photoshop.

Photoshop make selection from layer like Photopea but dont show it outside of canvas. When I make "transform selection" and move down, I see that all selected pixels.

Difference in both programs is in filling that selection with color
