### ISSUE TITLE
BUG in rendering effects using layer style on folder

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1008]
It's happens when trying to add bevel and emboss style to folder who have bevel and emboss + shadow effects on layers inside that folder.

<img width="1103" alt="obraz" src="https://user-images.githubusercontent.com/38118273/47394153-2b4b1180-d722-11e8-81c8-06c6e16744a1.png">
[bevel_and_emboss_bug.psd.zip](https://github.com/photopea/photopea/files/2508277/bevel_and_emboss_bug.psd.zip)

**Comment by photopea** [comment]
Hi, thanks, I fixed it!
