### ISSUE TITLE
Image to Vector

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1009]
Hello again!

I have been using the Image to vector feature a lot now, and i happen to run a lot into the same issue:
Some pictures really get weird when vectorizing.

I am working now with this picture of my dog's paw (i know is a complicated image to vectorize though)

But i got different results depending on the paws.

For example:

![b](https://user-images.githubusercontent.com/11801254/47401475-ede18680-d717-11e8-9f7f-409ea602d19e.png)
This png transforms into
![image](https://user-images.githubusercontent.com/11801254/47401724-e66ead00-d718-11e8-9393-19679f4e920f.png)

 But this:
![a](https://user-images.githubusercontent.com/11801254/47401443-cdb1c780-d717-11e8-9489-22b0876ab98b.png)
Turns to this inverse version:
![image](https://user-images.githubusercontent.com/11801254/47401466-e5894b80-d717-11e8-88b2-aa8e97bd373f.png)

I know it might have to do on how the algorithm is understanding the inside and outside of the picture.

But i might report it to you, i will be modifying the png until i get a desirable vector.

Cheers~!

**Comment by photopea** [comment]
Hi, your last bitmap has a very strange format. It contains semi-transparent pixels on the edge of the image. Also, it has bright  contours around black edges.

I recommend to pre-edit such bitmaps, to improve the the result. Reduce the number of colors, etc. E.g. I reduced your image from three colors (black, grey and transparent) to only two (black and grey): https://i.imgur.com/jqCB8qU.png . I also removed semi-transparent pixels on edges by cropping out the main object.
