### ISSUE TITLE
Canvas disappears on Epiphany browser

### ISSUE THREAD

**Issue by DanyGee** [photopea/photopea#1010]
Hi,
once launched in Epiphany Browser (default one that ships with elementary OS) the canvas of photopea disappers on every interaction with it.
On Opera, Google Chrome and Firefox didn't experience any issues, also when installed as desktop app with Google Chrome.
I would personally don't care about Epiphany, but on elementary OS there is an app (https://github.com/artemanufrij/webpin) that lets me pin any site as a desktop app - which is a good option to have photopea installed like that. You can additionally customize the name, icon and window color to match your taste. Photopea pinned in webpin app has the same issue like in Epiphany, so maybe both this apps use the same, somewhat incompatible yet render engine.
Could you take a look at the issue?
If more info is needed - just ask.

**Comment by photopea** [comment]
Hi, I don't have access to Elementary OS or Epiphany browser :( But it seems to me like a bug in Epiphany. Why don't you report it to creators of Epiphany?

**Comment by DanyGee** [comment]
Opened one:
https://gitlab.gnome.org/GNOME/epiphany/issues/564
Lets not close the issue here yet, untill we have some clue on which side the problem really lies...

**Comment by photopea** [comment]
I am sure it is not on our side, as we do everything according to web standards. Even if we could do anything to prevent your problem, we would never "crook" our code, just to overcome bugs in browsers. It should be fixed on a browser side. I wonder why don't you use some better browser instead :/

**Comment by DanyGee** [comment]
I'm using better browsers - sure. As stated, it works without problems in other major browsers :+1: 
I just wanted to pinpoint the problem why photopea has the same sort of problem in Epiphany and Webpin app.
