### ISSUE TITLE
Github login failure - Photopea didn't receive your email address

### ISSUE THREAD

**Issue by sysdrum** [photopea/photopea#1011]
I would prefer not to post the failure string that I get as it looks like it has the token in it.
Github shows access granted.

**Comment by photopea** [comment]
Hi, make sure you have your email address set in GitHub, and that it is available to third parties such as Photopea.

**Comment by sysdrum** [comment]
I have checked and both items are set.

**Comment by photopea** [comment]
I think you have to make it public somehow https://github.com/photopea/photopea/issues/837

**Comment by photopea** [comment]
https://github.com/photopea/photopea/issues/479

**Comment by sysdrum** [comment]
My email is set to public that is what does not make any sense on the failure.

**Comment by photopea** [comment]
So could you send us your error log to support@photopea.com ? Is there your email address anywhere in it?

**Comment by photopea** [comment]
I think we can not do much about it. This is a problem between users and GitHub :(
