### ISSUE TITLE
Title on New Project suggested sizes

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1014]
Hi! 

I would like to write you a recommendation:

Here, when you create a new project and select the size of the canvas. You have written titles that suggest the use of each size of canvas to a particular objetive: 
![screenshot 2018-10-24 at 21 48 45](https://user-images.githubusercontent.com/11801254/47469355-dfa66f80-d7d6-11e8-9a4a-d93b9b3a0f3d.png)

But when you go to Ads tab, we get nothing :(

![screenshot 2018-10-24 at 21 48 51](https://user-images.githubusercontent.com/11801254/47469584-02855380-d7d8-11e8-86af-7c9192d7851d.png)

Maybe Photopea should indicate for which platform and space is best suited for.

In the website Canva.com they do this, and recommend specific sizes according what you want to achieve.
You should check it.

**Comment by MichalSZZ** [comment]
Here https://github.com/photopea/photopea/issues/714 is ticket where we talked about those presets.

For ads there are official names, for example 120x600 has name scyscrapper and mostly is used in the sidebar of pages.
Here is well desribed that https://support.google.com/adsense/answer/6002621?hl=en and there are some visualisations, with places on the site.

**Comment by photopea** [comment]
Ok, I added names to these Advertisement Banner sizes. But I really doubt people use them in practice. For me, it has been always easier to tell someone the exact resolution, like 120x600.

**Comment by avagp** [comment]
I mean to keep sizes and add the titles.

Not replacing them :/

**Comment by photopea** [comment]
I kept sizes and added titles. I am jsut saying, that I think there is no purpose in displaying titles, because people don't know them anyway.

**Comment by avagp** [comment]
Is not mandatory to you to add them just because I suggested them. It is
your product after all :)

But thanks for considering it.

**Comment by photopea** [comment]
I am just a programmer, I am not a user of Photopea :) You are users and it is very important for me to know, what you need :) So thank you! :)
