### ISSUE TITLE
Photopea PWA icon

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1017]
I just Installed Photopea on Mac! WOW it's soooo great feature!
And cmd+t works for the free transform!

Don't you think that "p" in the icon, should to be fill not transparent?
Look at the movie https://youtu.be/H5XO8o_YsQo

Think about some of your users who have green wallpaper on the desktop :)
Once again many thanks for such a great thing!

**Comment by photopea** [comment]
Thanks! Yes, I also noticed, that Chrome lets us use these shortcuts in "isntalled" mode (You can also use Ctrl+O and Ctrl+N). 

I think we should have transparent background, we do so e.g. here on GitHub.

**Comment by MichalSZZ** [comment]
> I think we should have transparent background, we do so e.g. here on GitHub.

Yes but here (I think we talking about logo in header of this site) there is one background (black or some color, what frontend developers can predict)

Look how their logo looks on start page (with last viewed sites) in firefox

![github-logo](https://user-images.githubusercontent.com/38118273/47484211-7442b900-d83b-11e8-8517-733898f42f9c.jpg)

**Comment by photopea** [comment]
Ok, I made a version with a white background. You will probably have to "re-install" Photopea.
