### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by CrazyCorbeau** [photopea/photopea#1018]
it's not working for me,I keep getting a grey screen...

**Comment by xkovacikm** [comment]
I confirm. Same problem here. Google Chrome 69.0.3497.100

**Comment by photopea** [comment]
What about now?

**Comment by xkovacikm** [comment]
It's probably because of Adblock. When I turn it off, Photopea works :)

**Comment by photopea** [comment]
What browser and Ad Blocker extension are you using?

**Comment by oshriii7** [comment]
the same problem for me getting a grey screen even after i turn off adblock

**Comment by unckleg** [comment]
Not working.

**Comment by photopea** [comment]
Can you guys update a website a couple of times, and then, take a screenshot of errors in a web console (right-click - Inspect Element - Console) ?

**Comment by oshriii7** [comment]
work ok now thanks

**Comment by SmilerOnline** [comment]
I'm developing a desktop browser for Android desktop devices (such as Samsung DeX) and tablets, but I'm also experiencing this issue. I would like to ensure that my users can use your software so I just hope that you might understand where the problem lies and if it requires any code changes to the browser I'd be happy to do so. I'd also like to add your page to the default bookmarks bar list in my browser to encourage more users to try it. Please note the browser is still a WiP https://play.google.com/store/apps/details?id=com.touchtech.dexbrowser

**Comment by photopea** [comment]
Hi @SmilerOnline . The reports in this issue are related to our hosting problem, when Photopea was not available for 15 minutes (all the reports were written on 25th of October, between 16:35 and 16:50). But it never happened since then.

What problem exactly are you experiencing?

**Comment by SmilerOnline** [comment]
> Hi @SmilerOnline . The reports in this issue are related to our hosting problem, when Photopea was not available for 15 minutes (all the reports were written on 25th of October, between 16:35 and 16:50). But it never happened since then.
> 
> What problem exactly are you experiencing?

Oh ok sorry... 

At the moment when navigating to the page, I see the intro screen, those when I click the X button I just see grey...

**Comment by photopea** [comment]
What browser are you using? Could you try to update it? Do you see any errors in a web console?

**Comment by SmilerOnline** [comment]
I am using a webview in a browser which I am the developer of called Desktop Browser for Samsung DeX https://play.google.com/store/apps/details?id=com.touchtech.dexbrowser

**Comment by SmilerOnline** [comment]
WebView is pretty much the backend to near all Android browser. Webview is built upon Chromium engine

**Comment by photopea** [comment]
Are you sure your Android is not 10 years old? Can you update this WebView?

**Comment by SmilerOnline** [comment]
I'm using the Samsung Galaxy Note 9 (2018 device) with Android Pie and the Webview version I'm running was updated December 19 2018 by Google

**Comment by elviss116** [comment]
in 2022 confirm, not work in webview android.
https://scontent.flim23-1.fna.fbcdn.net/v/t1.15752-9/269805329_1743081432852751_6537923265989154040_n.png?_nc_cat=101&ccb=1-5&_nc_sid=ae9488&_nc_ohc=Hh5BuNqKZZcAX954MML&_nc_ht=scontent.flim23-1.fna&oh=03_AVK9InlIowswJMDPGa4PmdQjY2Jf4MEDukjfSO2gc7LpUQ&oe=61FC3568

**Comment by photopea** [comment]
@elviss116 Interesting. But isn't it a bug in Android Webview?
