### ISSUE TITLE
UI ideas [feature, ux]

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#102]
Hi, 
some ideas to improve UI, design:
- [x] add layer styles to main menu
- [x] implement scrollbar plugin for better design (for example: https://noraesae.github.io/perfect-scrollbar/) sure must supports touch devices. If I have black theme scrollbars looking ugly.
- [x] all important buttons as submit in green color for example same as here on github. It must be most visible!
- [ ] login via "modal window" like in bootstrap without new window for photopea. New window only for oAuth service with auto-close function & request to parent window for refresh snippets in site (login => logged, load user settings etc....)
- [x] If I have enabled czech language title in hover are in english (tools, right sidebar).
- [x] If I was click to navbar menu item (file, edit ,...) and some drop down are visible why hover opening for next items not working?  
- [x] Add titles for icons: new layer, new mask, .. (bottom on page) 
- [ ] change order of this icon to: 1. New layer, 2. new folder, 3. mask (by most freq. using)
- [ ] Implement nice tooltips for better UX like: https://jsfiddle.net/greypants/zgCb7/ (for example)
- [x] paint bucket tool not working for new transparent layer or bad UX? Change cursor to bucket => this is for all tools.
- [ ] zoom ratio by percentage / select
- [x] zoom by CTRL + mouse wheel
- [x] brush tool cursor is "invisible" if I have size <= 5 ...
- [ ] If I have "active" text layer and try draw by brush tool photopea show alert message, why can't auto create new layer?

Others:
- [ ] Try implement https://www.getsmartlook.com/cs/ for thinking about next things from user feedback.
- [ ] enable IPv6 http://ipv6prepared.com/?url=https://www.photopea.com/
- [ ] add meta tags for: facebook, twitter, apple, microsoft
- [ ] add meta tab background color: <meta name="theme-color" content="#559900" />
- [x] switch to less / sass and give this files as open source for comunity contributors
- [x] Show sizes - width, height for selection

**Comment by photopea** [comment]
--- If I was click to navbar menu item (file, edit ,...) and some drop down are visible why hover opening for next items not working?

You want it to work exactly as in Photoshop. I think we don't need every detail of UI to work the same.

**Comment by photopea** [comment]
IPv6 : I need my hosting provider to implement IPv6 first.

LESS / SASS: I think it will make the process of style development even more complex and time-consuming. Is there any particular problem with styles?

**Comment by landsman** [comment]
> LESS / SASS: I think it will make the process of style development even more complex and time-consuming. Is there any particular problem with styles?

Only for first step. After them is it faster. For future is it very important thing.

**Comment by landsman** [comment]
Look: http://css2less.co/

**Comment by photopea** [comment]
We don't have too much CSS, current CSS has quite clear structure. I don't see a reason for rewriting content to other formats (like CSS to LESS, Javascript to Coffeescript or other languages). I think it will only make the development harder.

**Comment by landsman** [comment]
>  lot of CSS styles area added to each element from a code.
Inline styles? Why?

**Comment by photopea** [comment]
E. g. each window can have differend width (Save For Web, Color Picker, Layer styles, New Project ...). It is easier to set  style:"width: 20 em"  than creating a CSS class for each window and specify the width for each class. What do you think?

**Comment by landsman** [comment]
I think that theese windows can have max-width / max-height by % or by content + padding. 
Key is the most united UI.

**Comment by landsman** [comment]
I was add new thing "Show sizes - width, height for selection".
Very often I need check size of some "free space" or something.

**Comment by photopea** [comment]
I think it should be solved by the Information panel: https://github.com/photopea/photopea/issues/116

**Comment by landsman** [comment]
Hey @photopea look on this: http://grsmto.github.io/simplebar/

**Comment by photopea** [comment]
Most of these are fixed. 
- I think, that login in a new big window is more comfortable, than a new flowing window, especially on small screens
- order of icons corresponds to Photoshop and I think that is what users are used to
- large tooltips - I think they would be too big and unnecessary
- zoom by percentage - do you really need it?
- I don't think so many users try to draw into the Type layer

**Comment by landsman** [comment]
Thank you
