### ISSUE TITLE
Measurement tool & rectangular selection  manual setup

### ISSUE THREAD

**Issue by egiraudy** [photopea/photopea#1022]
Hi, 
I just discovered photopea is this looks like a very promising tool!
I would love to move some of my workflow off Gimp to Photopea... but there are 2 things I am missing (let me know if I missed them in my exploration):
- a measurement tool (https://en.wikibooks.org/wiki/GIMP/Measure_Tool)
- the ability to set the position & size of a rectangular selection

Thanks!

**Comment by photopea** [comment]
Hi, Photopea has a Ruler tool, which lets you measure distances. You can also enable "Show Distances" in  the top bar for the Move tool

For the Rectangle selection tool, you can set the Fixed size in the top panel. You can also see some properties in the Info panel on the right side.

**Comment by photopea** [comment]
So I think that these tools are "covered" by our alternative tools, so I will close it.

**Comment by egiraudy** [comment]
Thanks for the pointers.
The crop tool is also easier and probably more in line with what i need.
Measurement will be more difficult to not have as I need to be able to precisely measure objects in the image as I need to resize the image based on a reference object size... I may survive with trials and error with resizing...

**Comment by photopea** [comment]
What exactly are you missing? I believe everything you need is already in Photopea, but probably in a slightly different form, than you are used to from GIMP.

**Comment by egiraudy** [comment]
I looked at the rulers but it is not helping.  
I have a reference image with the size of an object.  I need to measure the same object in different picture and resize this picture accordingly (simple cross-multiplication).  I then crop the picture to a specific size and stitch the generated "vignettes" together (if you want to look at really bad code & design it's here: https://github.com/egiraudy/Collagr ;-).
The ruler is really not accurate enough to measure distances, granting I want to measure the horizontal or vertical distance between 2 points (which is not always the case).

Thanks!

**Comment by photopea** [comment]
It is hard to understand what you mean. What is "image with the size of an object"? Is the size written as text? It would require some text recognition feature, to detect the numbers out of pixels of your image.

Do you know how to use selections in Photopea? For any selection, you can see its Width and Height in the Info panel.
