### ISSUE TITLE
Fade Brush Tool

### ISSUE THREAD

**Issue by kevintey** [photopea/photopea#1025]
Hey there!

As per the title, is it possible to have the Fade Brush tool developed?

It's actually a tool to quickly apply an opacity and blending mode adjustment after a **process** have been executed. Processes such as Stamp Tool, Spot/Patch/Healing Brush Tool, Paint Brush Tool, applying various filters... (almost all raster pixel editing) can be 'Faded'. It can be parked under Edit > Fade Brush

Check out the series of images for explanation on what it does:

Fading a Patch Tool (opacity):
![fadetool-1](https://user-images.githubusercontent.com/41601071/47842402-7edeee80-ddf7-11e8-930d-97d6a3231568.jpg)

![fadetool-2](https://user-images.githubusercontent.com/41601071/47842688-67543580-ddf8-11e8-94c1-5fc9fb30bf71.jpg)

Fading a Paint Brush Tool (blendmode):
![fadetool-3](https://user-images.githubusercontent.com/41601071/47842729-88b52180-ddf8-11e8-9bee-ab7ec0d4b19f.jpg)

![fadetool-4](https://user-images.githubusercontent.com/41601071/47842739-8e126c00-ddf8-11e8-9188-9ca682b8430e.jpg)

It's a really interesting feature to have and a great addition to the editor. Do let me know your thoughts. 
Thanks!

**Comment by wingsofovnia** [comment]
+1
At least opacity would be great to have!

**Comment by photopea** [comment]
I believe we implemented it several months ago. It is under Edit - Fade.

It works for fading Brushes, Adjustments, filters or any other pixel editing tools.
