### ISSUE TITLE
Load Font button

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#1026]
Many people don't know, that they can load custom fonts with File - Open (or drag-and-drop). We can add "Load TTF" button at the top of the font list, which would just open the Open dialog (the same as File - Open).

**Comment by flaneurette** [comment]
Nice. I also didn't know I could paste from the clipboard... Would be nice to have a button in the file menu: "Paste from clipboard". Almost opened it as a feature request until I discovered it by doing Ctrl+V ! :)

Thank you for this amazing piece of software. Really useful. Going premium next month.

**Comment by flaneurette** [comment]
How silly from me :) of course, forgot about the same origin policy i.e. user security for a moment. Is it possible in the chrome app? or is that just the same program.

**Comment by Shinhan** [comment]
Maybe a paste icon could open a small popup with this explanation?

**Comment by photopea** [comment]
I added the Load Font button.
