### ISSUE TITLE
creating a shape and duplicating the layer leaves shape oddly linked to previous shape

### ISSUE THREAD

**Issue by phazei** [photopea/photopea#1027]
I created one shape, set the properties to width: 300, height: 200, x: 0, y:0.
Duplicated layer, set new properties to x:300.
The new rectangle has an artifact of the duplicates layer shape in it.

**Comment by photopea** [comment]
Did you create a Live Shape (rectangle, rounded rectangle, ellipse) and changed the properties in Properties panel? I tried to do that and everything works fine.

What exactly is the artifact? Can you send us a screenshot?

**Comment by photopea** [comment]
There were some errors in the past, I think it is solved now.

**Comment by phazei** [comment]
Tested, it works, but now if you try to use the up/down arrows to change the width/height/x/y it doesn't work, it jumps to 0 and can only use arrows to go negative.

**Comment by phazei** [comment]
You're awesome!  Thanks for such a great tool, it's really amazing 🥇
