### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by flaneurette** [photopea/photopea#1028]
Would be nice if you could make the language file editable on Github. Noticed some small spelling mistakes in the dutch language section:

https://www.photopea.com/code/LNG2.js

`"Tint / Verzadeging",`
Should be:
`"Tint / Verzadiging",`

`"Nieuw folder",`
Should be:
`"Nieuwe folder",`

`"Serspreiding",`
Should be:
`"Verspreiding",`

```
"Kleur",
	[
	"Neen",
```

Should be:

```
"Kleur",
	[
	"Geen",
```

`"Minimale Rondinge",`
Should be:
`"Minimale Rondingen",`

`"Cuidige Laag",`
Should be:
`"Huidige Laag",`

`"Weerspiegd",`
Should be:
`"Weerspiegeld",`

`"Bewegins vervagen",`
Should be: 
`"Beweging vervagen",`

**Comment by photopea** [comment]
Hi, actually, it is editable here: https://www.photopea.com/translate/ . Could you please take a look at it and improve it?

Translations are made by our fans, and I think many of them would not be eager to learn GIT / JSON just to be able to translate.

**Comment by flaneurette** [comment]
Sure, no problem.

**Comment by photopea** [comment]
Please, fill in the missing phrases, if you can :) then, I will send it manually to a live Photopea.

**Comment by flaneurette** [comment]
That is a nice way of editing language files. However, it would be good to have some context as to where a word is used. In dutch language we have many words that are used in a different context. For example: "Rate", in Dutch could be: Snelheid, Prijs, Aanduiding, etc. etc. which mean totally different things...

**Comment by photopea** [comment]
Great, thanks! I just updated it at Photopea.com . I am aware, that translating is hard without knowing a context :(  But I am not sure how to improve it. Would it be enough, if we added a little comment to each phrase?

**Comment by flaneurette** [comment]
Looking at the source it's easy to see the context... how about printing the first array description? 
For example: 
```
file=>
file=>export
edit=>
edit=>transform
image=>adjustment
image=>transform
filter=>
filter=>blur
filter=>distort.
```
etc. etc.

It's that I know from memory what the descriptions are, otherwise it would be more difficult indeed. :)

**Comment by flaneurette** [comment]
Made another 5 edits a moment ago.
