### ISSUE TITLE
Feature request: information on rectangle tool.

### ISSUE THREAD

**Issue by flaneurette** [photopea/photopea#1029]
When drawing with the rectangle tool, it would be nice to have the information about the width and height placed next to the rectangle or the cursor the moment I draw with it. Indeed, I can find it in the info box right now, but it would be a nice feature to have it next to the rectangle or the cursor when drawing it and have it stick to the rectangle.

Often I use this rectangle tool to measure something, and right now I have to write down my measurements. It would be useful to have this information next to each rectangle.

**Comment by MichalSZZ** [comment]
@photopea I think, that function is done. Am I right?

**Comment by photopea** [comment]
Yup :D
