### ISSUE TITLE
Choose the object under the cursor does not work

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#103]
It behaves glichy.

Sometimes i get it right and other times i cannot change the current selection.

**Comment by photopea** [comment]
Hi, can you give me an example? Maybe send a PSD and tell me where to click.

Note, that layer effects do not work as an active area. So if you are clicking on a "stroke" of a text, it will not work.

**Comment by avagp** [comment]
Here is a video: https://drive.google.com/file/d/0BxACIQ9JCuosbzRIZlppeUJGVDQ/view?usp=sharing

I am trying to use the feature, but as you can see on the right, the layers selects glitchy, and sometimes respond properly and sometimes not.

I am moving my mouse, doing one click on the doodle, then 2 or 3, but sometimes changes and sometimes dont.

**Comment by photopea** [comment]
That is really strange. I have no idea what is going on.

What if you save your file as PSD, reload Photopea and open it again? Can you send me that PSD?

**Comment by avagp** [comment]
I did what you say. It still works strange. 

I leave you a link of the PSD: https://www.photopea.com/?state=%7B%22ids%22:%5B%220BxACIQ9JCuosaXFqQUl5OEQxdE0%22%5D,%22action%22:%22open%22,%22userId%22:%22103573920370075112038%22%7D

BTW, there is a way to share a Photopea project from inside the app like you do on the blog? (Like a sharable link like this: https://www.photopea.com/?p=%7B%22files%22:%5B%22https://www.photopea.com/api/img2/woman.jpg%22%5D%7D)

**Comment by landsman** [comment]
2) photopea have api: https://www.photopea.com/api/

**Comment by photopea** [comment]
Hi, I do not have access to your PSD file. Can you send it to support@photopea.com ?

You can give PP instructions, what files to open, through Photopea API.  There is API playground: https://www.photopea.com/api/#playground  , just insert the URL of your file into JSON configuration and it will be encoded into the URL of Photopea.

**Comment by photopea** [comment]
Thanks for the PSD. I was not able to reproduce your bug with it. Can you?

Do you see any errors in the web console, when it happens? Does it happen in all browser? Are you using a mouse or a touchpad?

**Comment by avagp** [comment]
I can reproduce the bug every time. I am using chromebook with touchpad. 

No errors so far on the web console. But if you want i can copy paste something from it

**Comment by photopea** [comment]
Can you try it with a mouse?

**Comment by avagp** [comment]
Of course, but when i arrive home :P

**Comment by photopea** [comment]
So does it work or not? :)

**Comment by avagp** [comment]
Yes, still happends. Even when playing with the default project you have
(the protopea logo)




2016-11-04 7:03 GMT-03:00 Photopea <notifications@github.com>:

**Comment by photopea** [comment]
Hi, I would like to take a closer look at it now, but your video is not available and I can not reproduce the bug. I have your project "New Project.psd", what are the steps to reproduce it?

**Comment by avagp** [comment]
Let me retry it again and record it.




2017-01-17 14:30 GMT-03:00 Photopea <notifications@github.com>:

**Comment by photopea** [comment]
I have noticed, that it happens only when you have zoomed in, am I right?

**Comment by photopea** [comment]
There was a really stupid bug, I fixed it. Thank you very much for your cooperation!

**Comment by avagp** [comment]
I was just about to tell you that is not there anymore.  :D

Great to know i can use it.




2017-01-20 8:48 GMT-03:00 Photopea <notifications@github.com>:
