### ISSUE TITLE
Warp not available

### ISSUE THREAD

**Issue by fdiniro** [photopea/photopea#1030]
Hi all,
when going for free transform via menu or via Crtl+Alt+T shortcut the "Warp" button does not appear. In a previous session I had the button but after reloading the browser I don't have it anymore.
I tried many combination of open / close the free transform without success.
I'm running Firefox 63.0 (64 bit) on a Mac with iOS 10.14 (Mojave).

Thanks
Fabio

**Comment by photopea** [comment]
Hi, the Warp is available only when you transform One layer, and it is not a Type layer. You probably wanted to warp mutliple layers, or a Type layer.

**Comment by fdiniro** [comment]
Hi, thanks for your quick reply.
I confirm Warp is not available when editing a single, raster (not type) layer, you can verify in the attached screenshot:
[cid:image001.png@01D4749E.C1A7EE50]

Thanks,
Fabio

**Comment by photopea** [comment]
Hi, sorry, but I can not see any image :( Please, reply at github, not via email.

**Comment by fdiniro** [comment]
here you go
![image](https://user-images.githubusercontent.com/17047280/47971938-1a41bf00-e097-11e8-8a5c-b926f858edd6.png)
