### ISSUE TITLE
Feature request: yearly price.

### ISSUE THREAD

**Issue by flaneurette** [photopea/photopea#1032]
Would be useful to also have a yearly price model to Photopea.

**Comment by photopea** [comment]
Currently, we offer 90-days Premium for 20 USD (6.67 USD per month). We can not go below this cost.

The Team Premium is even cheaper.

**Comment by photopea** [comment]
If you don't renew it, it is probably because you don't use it (and don't notice that the ads are back). We don't want people to pay, if they don't use it.
