### ISSUE TITLE
Same paths, different results

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1033]
When i download this file as PDF, the Hexagons on the top look different from the one on the right.

![image](https://user-images.githubusercontent.com/11801254/48040321-2725e780-e157-11e8-979d-aaf4954359cd.png)

But are the same paths  :/

Can you explain me why this happens?

[Caja (2) (1) (1).zip](https://github.com/photopea/photopea/files/2551440/Caja.2.1.1.zip)

**Comment by photopea** [comment]
Hi Alvaro, could you send me the original file? I think it was converted into PSD in a wrong way.

**Comment by avagp** [comment]
Here is. It is an AI
[Caja.zip](https://github.com/photopea/photopea/files/2555643/Caja.zip)

**Comment by avagp** [comment]
BTW, i have also had a lot of trouble opening the SVG on AdobeIlustrator or CorelDraw.

I exported it on PDF, SVG, with and without rasterized text and layers and i cannot open and modify it.

Because i work a lot with China, the company i work with has coreldraw and ilustrator, and cannot open my files.

Before Photopea i used inkscape, and the only way to transfer my work to those 2 platforms was exporting to [EPS](https://en.wikipedia.org/wiki/Encapsulated_PostScript). It is a kind of a common file extension between a lot of platforms:
3D Turbo
Adobe Acrobat
Adobe Flash (in later versions, it is a hidden feature)
Adobe Illustrator
Adobe InDesign
Adobe Photoshop (later versions)
Affinity Designer
Autodesk AutoCAD
CorelDRAW
Cytoscape
FlexiSign
Ghostscript
GIMP (requires Ghostscript)
GNU Octave
IDL
ImageMagick (requires Ghostscript)
Inkscape (requires Ghostscript)
InPage
Ipe
LaTeX
LibreOffice Draw
Macromedia Freehand
Maple
Mathematica
MathType
Matlab
OmniGraffle
OpenOffice.org Draw
PhotoImpact X3
Python (programming language)
QuarkXPress
R (programming language)
Scribus
Sketch
Stata
Xara
Xfig

So, i am just asking, it should be possible to Photopea to export on EPS? That will solve my problems?
That could be the solution for communicate and transfer works between the most used platforms?

Tell me what you think.

Cheers!

**Comment by photopea** [comment]
@avagp  I downloaded your file Caja.ai , but it contains just one Octagon (your PSD contains three octagons). Did you make them manually, or they are from other AIs?  I don't know, if I should fix the PDF loader, or the style editor.

**Comment by avagp** [comment]
The other 2 octagons I made it on Photopea.

But, independly from this possibility of exporting as EPS, I managed to
open it on Adobe illustrator after you made the change on my other issue.

So, maybe, just maybe, should not be as necessary as I thought, because now
the Photopea's PSD can be opened on AI.

**Comment by avagp** [comment]
The issue I was talking about is the 1097

**Comment by photopea** [comment]
Hi, I fixed your problem, the PDF from your PSD should look much better now. 

Note, that current PDF export of Text supports only single-line left-aligned text layers (other text layers may be aligned incorrectly). We plan to improve it in the future.

**Comment by avagp** [comment]
Great!

Yes i noticed that words are not aligned, but you told me before, and i can live with it at the moment.

Now the PDF looks way better and can be properly exported to PDF and opened on AI, which was my first real problem.

Cheers!
