### ISSUE TITLE
EPS export

### ISSUE THREAD

**Issue by Shinhan** [photopea/photopea#1037]
Encapsulated PostScript format is a common file extension between a lot of platforms.

https://www.loc.gov/preservation/digital/formats/fdd/fdd000246.shtml

**Comment by MichalSZZ** [comment]
EPS file format is very popular. Many big brands gives their logos in EPS as a substitution for the AI file.
Maybe it sound silly, but for me EPS looks more "professional" than SVG in designers world ;)
If that is not a problem for you - make that format as a option to export.

**Comment by avagp** [comment]
PDF and SVG is not a reliable replacement for every industry.
First, you have a lot of people that have NEVER EVER used nothing but AI, so dont know how to open them, neither correct the differences.

And second, i have tried giving them SVG and PDF, but always they tell me that some goes bad.
For example i sent this PDF:
![image](https://user-images.githubusercontent.com/11801254/48168208-2911b700-e2cd-11e8-8f65-ddd4483fb135.png)

And when they tried to open in AI, they got this:
![image](https://user-images.githubusercontent.com/11801254/48168187-1ac39b00-e2cd-11e8-9b84-23c920c1af67.png)

Here is the PSD file, please try to export it so in AI looks exactly the same. I you can, PLEASE TELL ME HOW :O
[Cajita Mala Leche.zip](https://github.com/photopea/photopea/files/2559703/Cajita.Mala.Leche.zip)

Hope this can be solved!


Thanks for all the hard work

**Comment by chrisdrumz** [comment]
Would also like EPS support

**Comment by avagp** [comment]
I am going to play a little as the devil's advocate here.

After the fixes on the PSD exports (#1097) i can export as PSD and then open it on Photoshop and Adobe Ilustrator without any issues.

Nevertheless i have not tried on Corel Draw nor Ink Scape. But i might say i am pretty confident that it might.

So, i am turning my side a little but maybe Ivan was right, and the PDF, SVG and PSD are file formats that may cover 90% of the use cases. But it needed the #1097 fix

**Comment by avagp** [comment]
Still waiting for the text alignment though  :P

**Comment by chrisdrumz** [comment]
I should clarify, I'd just like to open an eps file.. I can export to
something else

**Comment by photopea** [comment]
I was thinking about it again, and I still think that files should not be exported as EPS today.

The PDF format can store everything that EPS can store. You can not do anything in EPS, what can not be done in PDF. When some person or software accepts EPS files, they surely accept PDF as well.

While we do care about Photopea opening EPS files, we want people to export in PDF instead of EPS. What do you think?

**Comment by photopea** [comment]
Guys, I am closing it. PDF is a more advanced "analogy" to EPS. If any program does not support PDFs from Photopea, it would not support EPSs from Photopea, too. Let's improve PDF export, instead of thinking that EPS would save us.
