### ISSUE TITLE
Suggestion: Image Size by %

### ISSUE THREAD

**Issue by benmcmaster1** [photopea/photopea#1038]
Is it possible to have a Image -> Image Size, change by percent?

Sometimes I only use Image Editing software to expand an image out by double (200%) or shrink it to half (50%) etc.

**Comment by MichalSZZ** [comment]
Yes, it is possible.
Use from top menu Image->Image Size
And in popup window, next to "width", change units (from default px) to %

Remember to have "kepp aspect ratio" checket.

**Comment by photopea** [comment]
@MichalSZZ , thank you again for helping me! :)
