### ISSUE TITLE
different dimensions when viewed on sketch and photopea

### ISSUE THREAD

**Issue by vilkazz** [photopea/photopea#1039]
When looking at element dimensions and distances (using Dimension checkbox) the given values are different in sketch and photopea:
sketch: http://prntscr.com/lfbcdw
photopea: http://prntscr.com/lfbao6

**Comment by photopea** [comment]
In Sketch, the red rectangle around text has a gap at the top and the bottom of the text. In Photopea, there is no gap. I could add a gap too, but I don't know how large should it be. Is it the same for all fonts?

I think it is a bug in Sketch.
