### ISSUE TITLE
Add the key shortcut to the tool tips

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#104]
It should be easy for new users to know that if they press certain keys it will change to a specific tool. Like pressing Z for zoom, or W for the magic wand.

So the tool tip should display the name of the tool next to the corresponding key, for example:

Zoom Toll (Z)
Magic Wand (W)
Brush Tool (B)
and so on...

Btw,

**Comment by photopea** [comment]
You mean when user keeps the mouse cursor above the icon, the button "title" appears? Yes, that would be useful.

**Comment by avagp** [comment]
Exactly

**Comment by landsman** [comment]
Right, some quick legend of shortcuts missing. Titles / tooltips can be good too.

**Comment by photopea** [comment]
Ok, it is done. Also, a key is attached to a group of tools, which are located at the same position in a toolbar. E.g. when you press L multiple times, you can choose between multiple Lasso tools.

**Comment by avagp** [comment]
Great addition.

**Comment by avagp** [comment]
Just a little idea, also related with my other issue: Alt+click problems on chrome

Maybe in certain tools, where exist the Alt click problem, pressing the key, after selecting, switches between states of the tool.

At least zoom and clone tool.  

Sorry to post it here and not on the proper thread, but it related with this last feature you just add

**Comment by photopea** [comment]
I have reported a bug to Chrome developers. Please, sign in and tell them how much you need this feature. https://bugs.chromium.org/p/chromium/issues/detail?id=650436

**Comment by photopea** [comment]
Thanks for supporting my bug report! :)

By the way, I have heard, that you can install Android apps in Chrome OS. Can you try to install Chrome or Firefox for Android?

**Comment by avagp** [comment]
No problem. I really like Chrome OS and i think is really bad for developers not having this keyboard input :/

Right now just 3 chromebooks have the possibility to install play store, not mine still. But mine is on the list for early 2017.

What about the little idea i left before?

**Comment by photopea** [comment]
I think that users are used to not holding Alt - zoom in,  holding Alt - zoom out, releasing alt - zoom in again (or vice versa). You suggest, that if there is zoom in and user press and release Alt, there will be zoom out. Many users can complain about it.

**Comment by avagp** [comment]
No at the end.

Maybe pressing for a second time the key of the corresponding tool, for
example Z for zoom or C for clone, will.switch its function.

For.example;

Press Z - select zoom.tool
Press Z again - zoom.tool with zoom out
Press Z again - back to zoom tool with zoom.in.
And so on.

For me should be the only way of using the cloning tool  :(

**Comment by photopea** [comment]
I will add some manual switch between choosing source /drawing for the clone stamp, until Chrome fixes it. I am thinking about making Photopea usable completely without a keyboard, for touch-screen devices. What do you think about it?

BTW. that is a paradox of webapps. You can replace any native app with a webapp, except of the web browser. Or you can make a web browser webapp, but its capabilities are limited by a browser in which you run it. 

I was always a fan of Chromebooks, but now I see that having a device with just a single possible web browser is quite a bad idea.

**Comment by avagp** [comment]
Sorry for the bad writing. I meant it wasn't the idea after you told me
about that problem with users. I think you are right.

I was thinking in this second possibility using the just modified hover
text of the tools

**Comment by avagp** [comment]
I like the idea for touch controls, specially now with the project
andromeda (merge of chrome OS and Android). There you could install more
browsers if you want.

To have a manual switch for the clone tool is also a good solution ;p I am
a keyboard guy, that is why I didn't think nothing similar.
