### ISSUE TITLE
"cmd +" and "cmd -" keeps zooming out

### ISSUE THREAD

**Issue by vegardnx** [photopea/photopea#1041]
Same with "ctrl +" and "ctrl -". 
Love the project! cheers

**Comment by photopea** [comment]
Hi. Could you go here: http://jsfiddle.net/p45f44zb/14/ , click into the white area at the bottom right, and press those key combinations? It should say, what keys are pressed. If you release all keys, but it still says, that buttons are pressed, there is a bug in your browser / OS, and we will try to report it to your OS maker.

**Comment by ieatfood** [comment]
Possibly same issue:

Holding down `Command` and pressing `-` and not letting go of `Command` and then pressing `=` keeps zooming out. Pressing `Command` `=` first works normally.

Fiddle outputs `["MetaLeft","Minus","Equal"]`
MacOS 10.11.6
Chrome 69

Awesome app!

**Comment by vegardnx** [comment]
For 'Control +' it shows [ControlLeft, Minus].
For 'Control -' it shows [ControlLeft, Slash].
Both zooms out, I'm on Chrome 72.

**Comment by mblandfo** [comment]
@photopea testing this on your fiddle on MacOS 10.14.5 it has the same behavior in Chrome and FF - when cmd is held down, the keyup event of any key is not fired. Also the keydown event is not fired in cases where the key is used by the OS. For example, Cmd+N opens a new browser window and does not record even the keydown in your fiddle.

As a workaround for some keys, I think you can check e.metaKey on mac or e.ctrlKey on windows along with e.code.

**Comment by photopea** [comment]
Hi, I think it should be fixed by Apple. Until then, the only thing I can recommend is to use a better OS :(

Because of this, Photopea contains a special feature: when you release Command, all keys are set to an "unpressed" state.
