### ISSUE TITLE
UX problem: "New project / Open from computer / Demo" buttons are not visibly clickable

### ISSUE THREAD

**Issue by d33tah** [photopea/photopea#1042]
Hi! I just found out about photopea from Hacker News. I opened the website and saw that, first thinking it's just a screenshot on the landing page:

![image](https://user-images.githubusercontent.com/295322/48120728-41ed7e80-e273-11e8-95ef-8a2f7614b837.png)

There's something about the view that made me think it's static, but that's a separate issue.

The actual issue I'd like to report is that since those are buttons, I believe that they should somehow be highlighted so that the clickable area is obvious to the user without hovering over the "buttons" and seeing the mouse cursor change.

**Comment by MichalSZZ** [comment]
You are right from UX point of view :) I agree.
And you can hover and click "Demo:" that do nothing :)

**Comment by photopea** [comment]
I am aware of this, but giving a custom background or underline to these buttons makes them ugly.

You can still do everything in Photopea without using these buttons. So you can think of them as an "easter egg" :)
