### ISSUE TITLE
CSS viewer has a few glitches

### ISSUE THREAD

**Issue by yunruse** [photopea/photopea#1043]
Hey hi howdy,

As an on-off web dev I love the CSS viewer, and though I know it'd be a bit of a Herculean effort to parse and sync properties I still interpreted the fact that the textbox was editable as a sign that it would be automatically parsed. It's a bit of a UX feature, but I would recommend some text or a read-only box to indicate that this is not the case.

My programmer's instinct tells me this is a formatted string, and I often get a line of the format `border: {width} solid {hexcolor};` even after having edited the pattern of the line to be not solid. Additionally, gradients seem to turn around as a blank string.

Not to pry too much into your methodology (advanced patterns could be many different `<canvas>` elements, parsing CSS to change the UI might be annoying, etc), but would it not be a little easier in the long run to directly shadow-and-edit the `<canvas>` object's CSS?

Great program otherwise, and it's only from not wasting your time that I won't spend a whole paragraph telling you how much of a life-saver it is :)

**Comment by photopea** [comment]
I have to close it because of lack of details :(
