### ISSUE TITLE
HTTPS misconfig

### ISSUE THREAD

**Issue by yunruse** [photopea/photopea#1045]
Hey hi howdy,

Back again with an _extreme_ nitpick: your HTTPS certs are only for subdomains, not `www.`, so attempting to go to `https://photopea.com` comes up with a cert error, which might end up confusing a rare few users such as myself. I know how much of a pain Let's Encrypt is, so this might not be fixable for redirects, I'm not entirely sure.

Thanks again :)

**Comment by photopea** [comment]
Hi, you should not be able to go to https://photopea.com , it should always redirect to the "www" version. Does it not redirect in your case? What browser do you have?

**Comment by yunruse** [comment]
Hi,

This is identical behaviour for all browsers, because the HTTPS certificate is only issued for the www subdomain. This means that only the http version redirects.

**Comment by photopea** [comment]
I tried to access photopea.com (without www) on many browsers on many devices, and it always redirects to www. How can you say it is identical for all browsers?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
