### ISSUE TITLE
Zoom stuck

### ISSUE THREAD

**Issue by jenskanis** [photopea/photopea#1046]
**System**
- MacOS 10.14
- Firefox 63.0

**Steps to reproduce**
- Open an image
- Hold `cmd` key and press the plus (`+`) key two times.
- Keep holding `cmd` key and press the minus (`-`) key two times.
- Keep holding `cmd` key and press the plus (`+`) key two times. It will keep on zooming out, but expect it to zoom in. 

This is only a problem when **holding** the `cmd` key, using `ctrl` works fine.

**Comment by photopea** [comment]
Hi, we made some changes in the way the keyboard shortcuts work. Does it still happen?

**Comment by jenskanis** [comment]
@photopea unfortunately this behavior is still present.

**Comment by photopea** [comment]
I tried to reproduce it in MacOS on a virtual machine, but sadly, I don't have a command key there.

This page shows, which keys are pressed at the moment: http://jsfiddle.net/p45f44zb/14/ . Click into the white area and try pressing the same shortcuts. At the end, according to your report, it should say, that you are pressing Minus, even after you release Minus. If that is the case, I will report this bug to Firefox developers.

**Comment by jenskanis** [comment]
I tried the jsfiddle and indeed in continues to show the minus key after
releasing it.

**Comment by photopea** [comment]
Ok, I filed a bug to Firefox here: https://bugzilla.mozilla.org/show_bug.cgi?id=1510209  . There is nothing I can do at Photopea at this point :(  You can monitor the bug, or discuss it with them.

**Comment by jenskanis** [comment]
Cool, thanks!

Op di 27 nov. 2018 om 12:08 schreef Photopea <notifications@github.com>
