### ISSUE TITLE
Suggestion: Layer Fill Opacity

### ISSUE THREAD

**Issue by NilsKrause** [photopea/photopea#1047]
I'd suggest adding the feature to change the opacity of only the layer fill, so everything drawn on the layer not the masks and other options or effects. ([See this post for a better definition](https://graphicdesign.stackexchange.com/questions/1878/what-is-the-difference-between-opacity-and-fill-on-a-photoshop-layer/1882#1882))

I image it in a similar position as the general layer opacity, but it may also be hidden behind some menues. Just the option to change that value would be pretty handy. - In photoshop it is placed directly under the opacity slider, just for reference.

**Comment by mrillusi0n** [comment]
But since it's claimed that the UI is similiar to Adobe Ps, I'd like that to be placed under the Opacity Slider. Also, do you know how to filter layers based on color, text, ...?

**Comment by MichalSZZ** [comment]
> **You can find it in the layer style menu under blending options.**

Yes, exactly over here

![obraz](https://user-images.githubusercontent.com/38118273/70689624-0ebac180-1cb5-11ea-9b04-3277d63b9ec9.png)

**Comment by MichalSZZ** [comment]
> Also, do you know how to filter layers based on color, text, ...?
@mrillusi0n it was suggested over there #1802
