### ISSUE TITLE
Dutch translation spelling correction.

### ISSUE THREAD

**Issue by Hansyperman** [photopea/photopea#1048]
Thanks for your great application and the respect you show for my language.  Some of the dutch (Nederlands)  translations are a bit strange.

Here are some suggestions for the first 3 menus.  I'll see if I have time for the other menus.

Bestand/
    Publiseer online -> Publiceer online (typo)

Bewerk/
    Snij -> Knip
    Kopie -> Kopier
Afbeelding/
    Toevoegingen -> Aanpassen
        Rondingen -> Curves (Rondingen is technically correct but insinuates the round female shape)
        Kleur balans -> Kleurbalans (no space)
        Kanaal mixer -> Kanaalmixer(no space)
    Automatisch Contranst -> Automatisch contrast (Second upper case is wrong)
    Bitmap Vectoriseren -> Bitmap vectoriseren (Second upper case is wrong)
    Vervorm -> Transformeer (Vervorm is more destructive, like deform or disfigure.  BTW,t the menu Edit=Bewerk also has this.  Is there a difference that should be noted in the menus? )

**Comment by photopea** [comment]
Hi, we just change it a while ago: https://github.com/photopea/photopea/issues/1028

Translations are made here: https://www.photopea.com/translate/  Could you translate it there?

BTW. could we keep the second word starting with a capital? I think it looks better.

**Comment by Hansyperman** [comment]
Most corrections were already there, except Vervorm.  And some of them were better than mine. So I'm going to close this issue.

Thanks!
