### ISSUE TITLE
Ctrl + + on german keyboard does not zoom in

### ISSUE THREAD

**Issue by smoli** [photopea/photopea#1050]
Works on Num-Pad but not on the regular +-Key

**Comment by smoli** [comment]
["ControlLeft", "BracketRight"]
["ControlRight", "BracketRight"]

**Comment by tiger62** [comment]
Same Problem here on Chromebook, no Num-Pad there. 
Must use the ` key where the + is on the US keyboard.

**Comment by avagp** [comment]
I have a chromebook set to international english, and this keys i use for the zoom combo
![image](https://user-images.githubusercontent.com/11801254/49710468-5927df00-fc18-11e8-9ba7-ea649030084d.png)

Also you can use Alt+Scroll (or swipe up)
Or hit Z and then drag to the right or left

**Comment by avagp** [comment]
I did it, and it perfectly responsive.

I mean, is perfect.

**Comment by photopea** [comment]
I think I fixed it. Now, if a keypress produces a "+" character, it is considered as if the plus is pressed.

I am a little afraid, that it could break other shortcuts, but lets see.
