### ISSUE TITLE
OSS photopea

### ISSUE THREAD

**Issue by josephjacks** [photopea/photopea#1051]
Are there plans to open source the core source code / most of the core at some stage? If so, love to chat with you, Ivan! Drop me a line: j@oss.capital 

Thanks.

**Comment by photopea** [comment]
Hi, we discussed it here: https://github.com/photopea/photopea/issues/45  . We don't have any plans for open-sourcing.

**Comment by quantuminformation** [comment]
lol some of the issues in here must drive you nuts.
