### ISSUE TITLE
Transaprent text effect not working

### ISSUE THREAD

**Issue by Que88** [photopea/photopea#1052]
I'm a photoshop noob but I am able to achieve this effect in photoshop.
Unfortunately not in Photopea.
https://www.youtube.com/watch?v=bG5r5TM5e2o

The text is black as well, while it should be transparent.
https://www.dropbox.com/s/sg5urjmjayep6zh/Screenshot_13.jpg?dl=0

**Comment by photopea** [comment]
Hi, I think you should select a layer mask before filling it. Or could you be more precise, at what step it did not work?

**Comment by Que88** [comment]
The steps I follow are:
- select text
- inverse
- soft light
- solid fill

Here the endresult on PS: https://www.useloom.com/share/46d34e0bd426470ea6800adecbd2b69b

Photopea does not give me that result with those steps: https://www.useloom.com/share/606450959f5d4fff9c1f628b7f35d878

**Comment by MichalSZZ** [comment]
I think that I know where is the problem.
In photoshop, when you have a selection and you create a new adjustment layer. This layer have mask from selection.
In Photopea, mask to new adjustment layer is alwayes empty (white).

**Comment by Que88** [comment]
Can you advise which additional step I need to take, as I don't understand the terminology?

**Comment by photopea** [comment]
Hey, I fixed it: when you make a new fill layer, it gets a mask according to a selection! You should be able to follow your tutorial now.

@MichalSZZ man, thanks you a lot for helping me out!
