### ISSUE TITLE
Texttool prevents the user from creating guides

### ISSUE THREAD

**Issue by smoli** [photopea/photopea#1054]
When the text tool is active I cannot create a guide from the ruler.

**Comment by photopea** [comment]
Guides can be added only with a Move tool. You can switch to a Move tool by pressing Ctrl.

**Comment by MichalSZZ** [comment]
@photopea I have other habits from working in photoshop. For example, today I wanted to show something in Photopea, and when I was in creating new shape mode, I could't made a guides (horizontal and vertical) in the middle point of that shape (showing by the center point of transformation).

In photoshop I think that no matter what tool you are using, it is possible to start dragging guide from ruler (now I am on mobile phone and can't check that)
