### ISSUE TITLE
Brush Icon Size

### ISSUE THREAD

**Issue by antonbe** [photopea/photopea#1056]
Brush Size Icon size doesn't change with brush size.

**Comment by photopea** [comment]
Hi, what do you mean by a brush Size icon?

**Comment by antonbe** [comment]
![image](https://user-images.githubusercontent.com/3018990/48566558-b8682d00-e8c0-11e8-918a-fbb0a7936923.png)

**Comment by antonbe** [comment]
![image](https://user-images.githubusercontent.com/3018990/48566589-ccac2a00-e8c0-11e8-9651-600b8faa18d6.png)

**Comment by photopea** [comment]
I still don't know what you mean by the picture. The Brush button has a Circle, which obviously can not be 473 pixels large, because it would be outside the button.
