### ISSUE TITLE
Free Transform doesn't conform to layer size

### ISSUE THREAD

**Issue by antonbe** [photopea/photopea#1057]
Free Transform doesn't conform to layer size

**Comment by photopea** [comment]
Hi, what does it mean?

**Comment by antonbe** [comment]
![image](https://user-images.githubusercontent.com/3018990/48566087-9621df80-e8bf-11e8-8e76-c98a040a28aa.png)

**Comment by photopea** [comment]
Do you have a selection in your document? When you do, the Transformation rectangle corresponds to the selection.
