### ISSUE TITLE
Exposure panel improvements (+- adjustments, shortcuts...)

### ISSUE THREAD

**Issue by wladehr** [photopea/photopea#1058]
Hi! I discovered your project throught Reddit AMA. Well done!

What I am writing here aren't issues (bugs) but feature requests (I guess).

I would appreciate as an improvement some tweaks on the way edit panels work. For example, Exposure.
Right now, you have a click-and-move slider for three options (Exposure, Offset and Gamma). [TBH I don't know what Offset even does and how it works in this context, but I am an amateur user and I can see stuff happening in the background so I can see some use for it.]

What I suggest is that you add + and - icons (or up-down arrows) on one side of the sliders, so that minor adjustments can be made without painstaking precision with the mouse or touchscreen while moving the slider. The step size for each click can be by 0.1 points for example. Also, a window to insert a specific value could sometimes come in handy, but that is less required for my own needs.

This approach to slider manipulation can probably be replicated to sliders elsewhere in the interface. 

What I would also appreciate is an option to cancel the recent changes from within the Exposure panel, without closing the panel (X does revert without saving, but then I need to reopen to start over). I know I can reach the same effect by hunting down the changes in the history panel. This option (click to revert changes since opening the particular panel, while the panel stays open) would just make it more fluid and accessible.

One more thing - a shortcut system to reach every option without needing to move over with the mouse pointer would also help the workflow. For comparison, when using basic menus in windows/office, you may not have some global shortcuts available to instantly access every possible option in the dropdown menus. But you do have available a shortcut combination to open each dropdown, then usually just a single-letter-shortcut to reach any option in the opened menu, and so on. Similar functionality would be a nice touch to have in this interface as well. I don't need global shortcuts for every little thing, but once I have a dropdown open, help me save time by just clicking specific letter for a particular item in the list.

Thank you for reading and I'm looking forward to using your program more! Thank you for the AMA :-)

Cheers, 
Wlade

**Comment by photopea** [comment]
Hi Wlade,

Sliders: Each slider always have an text box with a value on top of it. You can enter the value manually.

Once you click any slider, you can change it by small steps using the arrows on your keyboard: Left and Right.

You can also reset each slider to the original value by double-clicking it.

You should be able to switch from one input element to another simply by clicking Tab on your keyboard. You can set all values without using mouse.

Is there anything else that I missed?

**Comment by photopea** [comment]
To move a value by small steps:
- click on a slider and move arrows left / right
- or: click into a text field with a value and use arrows up / down

Every adjsutment has a "Reset" button now, which sets default values to all parameters.

You should be able to go through form elements by pressing Tab, arrow keys, etc.
