### ISSUE TITLE
Making canvas bigger makes the entire project black.

### ISSUE THREAD

**Issue by minespatch** [photopea/photopea#106]
Since Firealpaca isn't loading my psd files, I'm, using Photopea to finish my psd files. Unfortunately when I widen the canvas to move the layer around, the entire file goes black.

**Comment by photopea** [comment]
Hi, what do you mean by widening the canvas? What browser do you use? Have you tried another browser?

**Comment by minespatch** [comment]
When I spread the canvas to 1000x1000 or 3000x3000, the layers become useless. I use firefox but haven't tried chrome yet.

**Comment by photopea** [comment]
How do you spread the canvas? Do you mean Zoom In (View - Zoom In) ?  Or you mean Image - Canvas Size?

**Comment by photopea** [comment]
I have to close it because of the lack of details.
