### ISSUE TITLE
Program freezes when trying to do magnetic lasso for large picture

### ISSUE THREAD

**Issue by Jaklynn** [photopea/photopea#1060]
Hello,

I have a picture with a large resolution that I am trying to use the magnetic lasso for. Every time I go to click on it, the entire browser freezes. Can you help? Unfortunately this is a wedding photo that came right off the camera, so I can't reduce the size because I would like to eventually blow the finished project up to a portrait size.

**Comment by aliceell** [comment]
I am also having this problem.
Switching to a new tab seems to help. I also shrank my picture down by 50% and that fixed it, but as OP said, that's not something that everyone can do.

**Comment by photopea** [comment]
Hi, I made the Magic Wand work about 3x faster. Rendering selections at high resolution is quite slow, so we will improve it, too.
