### ISSUE TITLE
Doesn't support GIMP 2.10.X XCF files

### ISSUE THREAD

**Issue by bitshifter52** [photopea/photopea#1061]
The app doesn't support the newest version of GIMP 2.10.x file format. I tried to attach an example XCF file but even when compressed to a zip file it's too large so I emailed an example to you.

Thanks for what you do.

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by xanthoxyl** [comment]
Hi, here's an example of a simple XCF which causes a crash.

[test.zip](https://github.com/photopea/photopea/files/2780933/test.zip)

**Comment by photopea** [comment]
@xanthoxyl It was fixed, thank you!  :)
