### ISSUE TITLE
Feature request: Import PhotoShop Custom Action Keys (.atn)

### ISSUE THREAD

**Issue by Sliicy** [photopea/photopea#1062]
First of all, saw your program via Reddit, and this is **AMAZING**!!! I would switch to this tool, however I already am used to my custom shortcuts. Can you please consider adding the ability to import custom action keys (which are .atn files)? This way, one could migrate with all their custom shortcuts and not relearn everything? I basically want to import custom keyboard shortcuts.

**Comment by photopea** [comment]
Hi, as far as I know, Photoshop lets you save keyboard sortcuts as .KYS files.  .ATN are used to save actions (which are not shortcuts). Are you confusing two things?

**Comment by Sliicy** [comment]
Sorry, how do we save keyboard shortcuts again? I couldn't find the docs for .KYS files.
Also, yes. Could we then add actions? So I could use my existing .ATN actions?

**Comment by photopea** [comment]
Follow this coorresponding issue about actions: https://github.com/photopea/photopea/issues/376
