### ISSUE TITLE
Feature request: More History

### ISSUE THREAD

**Issue by Sliicy** [photopea/photopea#1063]
Can you add more History undos to make this product much better? Right now, the maximum undo history is only 30. Can we at least have an option for more if we have more RAM?

**Comment by CrazyCorbeau** [comment]
I agree on adding more history

**Comment by photopea** [comment]
I always wonder, what style of workflow it is, when you have to step back more than 30 steps in history. BTW. what kind of steps do you have? Maybe we could "merge" them into one step.

**Comment by Sliicy** [comment]
I understand. Perhaps there's a way (if you're up for the challenge) to include an option to fully undo each step? It would be very useful for merging steps as well, but if someone is designing a logo for instance, and they move the picture multiple times, they may desire each step to get to a particular point...
Maybe you could turn this into an optional checkbox?
<sarcasm>And see how many more users complain as a result?</s>

**Comment by photopea** [comment]
Hi, so now, everybody has 30 history steps by default, and 60 history steps, if they have a Premium account.
