### ISSUE TITLE
Transforming a Layer

### ISSUE THREAD

**Issue by kevintey** [photopea/photopea#1064]
Hi,

There's no option to flip horizontal just 1 layer. Only way to flip is to drag manually (an object) when in free transform mode.

The transform option under Image > Transform actually transforms the whole canvas. 

Suggestion to enable single layer (or single object/selection) transform? Menu > Layer > Transform
or if we can enable a right click to pull out the transform option on selected objects.

Thank you!

**Comment by MichalSZZ** [comment]
There is a option to transform only one layer. 
Use Edit->transform->flip...
It works good (like in othergraphic programs) 

Image transform works on whole Image (all layers on canvas) :)

**Comment by kevintey** [comment]
Ah, totally missed out that one.
Thanks! What if we do a right click and select transform option from there? Will it be more convenient?

**Comment by photopea** [comment]
Also, in Free Transform, you can enter the Width / Height of -100% in the top menu.
