### ISSUE TITLE
Can not load file from Google  Drive

### ISSUE THREAD

**Issue by copyhold** [photopea/photopea#1065]
![Screenshot](https://user-images.githubusercontent.com/42069/48181156-1334de00-e32f-11e8-9f62-e9640a9e886f.png)
Open file from computer woorks.

**Comment by photopea** [comment]
Hi, did you see a pop-up window, which asked you to give Photopea access to your Google Drive? Did you confirm it?

Could you try it in anonymous mode, when all your extensions are disabled?

**Comment by copyhold** [comment]
I just tried on Chome using the same file, and it did opened without an error.

**Comment by photopea** [comment]
Ok, I will close it now then. Maybe Firefox is blocking your popup windows or something.
