### ISSUE TITLE
Important Photoshop feature isn't available: Alt + RMB up/down left/right to adjust brush size/hardness

### ISSUE THREAD

**Issue by Shadetail** [photopea/photopea#1069]
In Photoshop, while holding alt + RMB, moving mouse up/down changes hardness of the brush, and moving it left/right changes the size.
And in addition to that, alt + space + LMB left/right zoom as well.

As an industry professional with many thousands of hours of Photoshop experience, these are the first immediate issues I noticed when trying to use photopea.

**Comment by eddy386** [comment]
I agree. Would be a superb addition. At least, add a quicker way to change the brush size.

**Comment by JASHIKO** [comment]
One of the most used tools on PS so this is a must have shortcut!

**Comment by photopea** [comment]
Hi, I implemented it. I am sorry that it took so long. 

Thanks for suggesting it. I think it is a great feature!
