### ISSUE TITLE
Cannot save as PSD

### ISSUE THREAD

**Issue by murdz** [photopea/photopea#107]
I've successfully been able to edit a PSD (great work by the way) but I cannot save as PSD.

Everytime I click "Save as PSD" it throws a Javascript error. The error is "Uncaught TypeError: Cannot read property '0' of undefined" and Chrome debug reports it as file/line pp.js:324 

Saving as PNG (Save for web) works.

**Comment by photopea** [comment]
Hi, you have probably discovered a bug in Photopea.

Can you send us your PSD to support@photopea.com , so we can check what is going on?
