### ISSUE TITLE
Pinch to zoom

### ISSUE THREAD

**Issue by j-rieck** [photopea/photopea#1070]
I'm using this on a MacBook Pro, and intuitively tried to pinch to zoom in, but that does nothing. Is it possible to implement this?

**Comment by bgobler** [comment]
This would be SUPER helpful!

**Comment by bgobler** [comment]
Maybe a continuous zoom instead of discrete jumps. Thanks!

**Comment by photopea** [comment]
Hi, I implemented Pinch-to-zoom on Trackpoints. 

The continuous zoom is quite difficult. Photopea is raster-based, and when the zoom is e.g. 120%, you have to draw one pixel on an image to 1.2x1.2 hardware pixels of a screen (it is not clear how should it be drawn).

However, when we allow only 100% or 200% zoom, we draw a pixel as 1x1  or 2x2 hardware pixels.

**Comment by bgobler** [comment]
This makes so much sense, thank you for taking the time to respond! I am
grateful for the software and for everyone working behind the scenes!
