### ISSUE TITLE
AZERTY keyboard support

### ISSUE THREAD

**Issue by Grafikart** [photopea/photopea#1071]
**Note**: My keyboard layout is AZERTY
If i press "Z" I expect the zoom tool to be selected. It only works if I press W. And I have the same problem with keys that change places between layout.

**Comment by lcswillems** [comment]
There is the same problem also to undo. People with AZERTY keyboards currently have to press "ctrl+w" to undo but this closes the tab...

**Comment by vocamen** [comment]
Yep, I have the same issue.

**Comment by phiresky** [comment]
Same issue with [Neo](https://neo-layout.org/) except it's much worse because Ctrl+C becomes Ctrl+Ä, Ctrl-V becomes Ctrl-P and doesn't even work because the browser catches Ctrl+P to open the print dialog.

**Comment by ggrelet** [comment]
This issue is still what's blocking me from using Photopea at full power.
I can use it as a quick editing tool but not from that since `Undo` is really important.

**Comment by priem19** [comment]
Came here to mention the same problem.

**Comment by photopea** [comment]
I think I fixed it. Now, Photopea should detect the "local" keyboard layout. Please, let me know if it works now.

**Comment by ggrelet** [comment]
Yes, it's fixed. Thank you very much.
