### ISSUE TITLE
Feature Request: Quick Mask

### ISSUE THREAD

**Issue by seanboothm** [photopea/photopea#1072]
Photoshop has a super useful feature for editing the selection area by entering "quick mask" mode. This mode allows you to edit the selection area with any of the brushes, including different hardness levels and different shapes. Made it really quick and easy to select around an object.

More details can be found here:
https://helpx.adobe.com/photoshop/using/create-temporary-quick-mask.html

**Comment by AxDSan** [comment]
+1

**Comment by photopea** [comment]
Quick Mask mode in PS is really strange. It removes the selection and "creates a new hidden layer" at the top. In that mode, you can make new selections, which are lost, after you escape quick mask mode.

**Comment by photopea** [comment]
I implemented it :)
