### ISSUE TITLE
Blur tool is blending in black when blurring with a transparent background

### ISSUE THREAD

**Issue by kokuda** [photopea/photopea#1073]
Blurring a shape on a transparent background causes it to blend with transparent black which causes dark edges.

1. Create a new rectangle on a new layer
1. Rasterize that layer
1. Blur the edges of the rectangle
1. The edges get dark because they are blending with the transparent black background.

The blur calculations could scale the color contribution of the pixel by the alpha, so an alpha of 0 will contribute no color to the result.

There may be other places where the blending is done like this, this was just my first attempt at using your cool tool.

![image](https://user-images.githubusercontent.com/11729648/48217898-7cbbe900-e33d-11e8-80be-c2f614540256.png)

**Comment by photopea** [comment]
Hi, it was fixed, thank you! :)
