### ISSUE TITLE
快捷键放大缩小问题

### ISSUE THREAD

**Issue by OrangePeel73** [photopea/photopea#1077]
当按住‘command’ + ’-‘ 缩小视图大小，想放大时，按住’command‘不放，按住’+‘，视图没有放大，而是缩小；反之，没有问题。

**Comment by photopea** [comment]
Hi, could you please write in English?

**Comment by TerryBryant** [comment]
@photopea The question is, when you press 'command' and '+' button, the picture is supposed to be zoomed in, and the 'command' and '-' button is suppose to be zoomed out. There maybe some bug within it.

**Comment by photopea** [comment]
What exactly is the bug?

**Comment by TerryBryant** [comment]
when you press 'command' and '+' button, the picture is zoomed out

**Comment by photopea** [comment]
What "+" button do you press? There are many different keyboards in various parts of the world.

Could you go here, click into the white area and press "+"? What key name do you see? http://jsfiddle.net/p45f44zb/14/

**Comment by TerryBryant** [comment]
@photopea I'm not the original questioner, just here to help with the translation. I'll let @OrangePeel73 to respond to you...
@OrangePeel73 能看懂作者说什么吧，去那个网站跟他反馈下。。。

**Comment by photopea** [comment]
@OrangePeel73 it is so nice of you :) I am very glad, that so many people join forces to help us :)

**Comment by qinfenjiqu** [comment]
一股清流。所以什么时候开发中文翻译呢

**Comment by photopea** [comment]
Guys, I am going to close this and wait, until the same issue is reported by somebody else in English.
