### ISSUE TITLE
ctrl+Z switches to Zoom Tool?

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#1078]
Z is the hotkey for Zoom Tool
but for me ctrl+Z, in addition to undo, also changes to Zoom Tool
it happens not always, but more than half of the times
it's as if it reacts to Z even if Ctrl is pressed
I am  not sure when it started
May be it's only for me? Because it seem to be something too bad to go unnoticed for even a short time.
Sorry if it's something on my system that is messing with photopea hotkeys, I tried disabling the only thing that I think could interfer with the keys (Tampermonkey extension) but it didn't help

**Comment by photopea** [comment]
Hi, sorry, there really was a bug. When you pressed the Ctrl, then Z, Undo was done. But then, you released Ctrl, and only Z was pressed, so it switched to the Zoom tool (i.e. only when you released Ctrl earlier than Z).

I fixed it. Now, these actions can be executed only after pressing a key, not after releasing a key (so if you release Ctrl, but keep Z pressed, nothing will happen).

**Comment by ewnjtgouierg** [comment]
thank you

**Comment by deltasucko** [comment]
This still happens to me, and was kind of annoying. It is okay if you cannot fix it completely.

**Comment by photopea** [comment]
@deltasucko I can not reproduce it :( Could you describe how to make it happen? Are you sure you don't press Z without pressing Ctrl?

**Comment by deltasucko** [comment]
Yes, I sometimes double check. It may just be the fact that I do it so often.
