### ISSUE TITLE
Layer not editable

### ISSUE THREAD

**Issue by Que88** [photopea/photopea#1079]
I'm sure I am doing something wrong but can figure it out.
I am trying to move a shape but am getting: 'Layer not editable'
https://www.useloom.com/share/ef15a3dfe12947f4a399a597da31290e

**Comment by MichalSZZ** [comment]
try to use deselect before (ctr + D). I think that is problem with rectangle selection of the left of arboard.

**Comment by photopea** [comment]
Ok guys, I changed the behaviour, so if the layer is not a regular pixel layer, the selection is ignored and the whole layer is moved.

**Comment by f7n** [comment]
FIX THIS DAMN ISSUE!
