### ISSUE TITLE
Missing features from Photoshop: Open dialog with previous settings

### ISSUE THREAD

**Issue by andybak** [photopea/photopea#108]
Hidden but very useful feature: open any dialog (eg 'Levels') with a modifier key held down and it remembers it's previous settings. 

(there also a modifier key whilst inside the dialog to reset settings to defaults)

**Comment by photopea** [comment]
Hi, what do you mean by a modifier key? I have Windows.

What if it always remembers previous settings, after each opening, and there will always be a Reset button?

**Comment by andybak** [comment]
It's Alt (Option on the Mac).

> What if it always remembers previous settings, after each opening, and there will always be a Reset button?

Main downsides with that - it's different from Photoshop - better? worse? Hard to say as it depends on a user's workflow - but being different is bad by itself. I've got 23 years of muscle memory to unlearn ;-)

I think this feature should be more discoverable and less hidden than in Photoshop - but not sure about anything as radical as reversing the default behaviour.

**Comment by photopea** [comment]
By the way, does Option key work in Photopea on Mac correctly (e.g. for Clone stamp, as Alt on Windows)? I have never tried to run PP on Mac, so I have no idea how does it work.

**Comment by andybak** [comment]
> By the way, does Option key work in Photopea on Mac correctly (e.g. for Clone stamp, as Alt on Windows)? 

Yep. Just tried it.

Are you aiming to duplicate most PS keyboard shortcuts where possible? I just tried some of my usual workflows and there's quite a few missing.

**Comment by andybak** [comment]
(BTW I'm not complaining! I'm astonished how much you've achieved. I've never seen any other non-Adobe app, be it desktop or web, load a PSD with smart objects, layer styles, adjustment layers, vector masks etc. all intact.

**Comment by photopea** [comment]
Thanks :)  You are helping me improve PP, so thank you very much for that. I just added this feature - when you hold Alt, the Adjustment window is open with the previously applied parameters.

Keyboard shortcuts are useful and when users are used to some specific shortcuts from other editors, it would probably be the best to implement them in the same way. Let me know what other shortcuts are missing :)
