### ISSUE TITLE
1. Layered TIFF 2. CMYK display

### ISSUE THREAD

**Issue by m5g** [photopea/photopea#1082]
1. Layered TIFF, saved in PS CC 2019, opens as single flatten layer.
2. CMYK images displayed wrong, like inside any other programs that doesnt support CMYK view, only sRGB

**Comment by photopea** [comment]
Hi, could you send us your TIFF file, which is displayed wrong in Photopea?

**Comment by photopea** [comment]
I think it was fixed.
