### ISSUE TITLE
Illustrator CC 2019 files

### ISSUE THREAD

**Issue by JBinAussie** [photopea/photopea#1083]
Hi there,

Just test Photopea to see how it handled .AI files and I was happy to see that it opens them well. I was able to make edits and then save the file back to my desktop. But that's when the problems started.

The file gets saved as a .PSD.PDF file and photoshop refuses to open it saying it could not complete the request due to a progamme error?? I tried renaming the file to just .PSD and then to just .PDF but nothing worked. Photoshop won't even look at it. However if try reopening the file in Illustrator it see's it as a PSD file and imports it without a hitch??

Just thought you'd want to know. 

James

**Comment by photopea** [comment]
Hi, Photopea can not work with AI files at the moment, it can only work with PDF (many AI files are PDF at the same time, but not all of them).

To be able to work with your document in Photoshop, you should save it as PSD. Please, save your file as PSD (File - Save as PSD) instead of PDF.
