### ISSUE TITLE
字体编辑不支持中文

### ISSUE THREAD

**Issue by Wanmeibox** [photopea/photopea#1084]
创建或者编辑字体的时候，输入中文会变成乱码

**Comment by photopea** [comment]
Hi, sorry, could you write it in English?

**Comment by PabloRomanH** [comment]
It says that the font editing doesn't support Chinese.

**Comment by photopea** [comment]
You need a font, which contains Chinese characters. In the font menu, enable the Chi-Jap-Kor filter.

**Comment by zxdawn** [comment]
@photopea , is it possible to add fonts by ourselves without affecting others?

**Comment by Wanmeibox** [comment]
@photopea,  My browser support many Chinese fonts, why not automatically add these fonts?

**Comment by photopea** [comment]
Current technologies do not allow us to use internal fonts of your computer :( We would love to use them, if it was possible.

You have to load your fonts manually using File - Open (or the Load Font button).

**Comment by Wanmeibox** [comment]
You can make a huge font library, stored most of the font.  Not read from the computer, it is possible:)

**Comment by zxdawn** [comment]
@photopea Maybe you can try [google font](https://github.com/neverpanic/google-font-download)

**Comment by photopea** [comment]
@zxdawn All "Goog fonts" are already in Photopea.

**Comment by zxdawn** [comment]
@photopea Oh, that's good! Maybe you can check [this website](https://www.freechinesefont.com/).
But, it's difficult to download all of them. It seems better to upload fonts by ourselves.
Thank you!
