### ISSUE TITLE
Can't open pdf-files

### ISSUE THREAD

**Issue by linusinfomagine** [photopea/photopea#1085]
Attempting to open a pdf-file from the computer results in infinite loading. The loading message at the top stays there endlessly.

**Comment by photopea** [comment]
Hi, can you show us your file here?

**Comment by linusinfomagine** [comment]
I can't show you the file I used originally, but I found a sample file which I can link you which has the same problem.

https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf

I saved that file to my downloads folder and then tried to open it in Photopea by clicking File->Open.

**Comment by photopea** [comment]
That PDF file has a strange structure. I asked about it here: https://github.com/mozilla/pdf.js/issues/10248  , hope somebody will help me.

**Comment by photopea** [comment]
So it seems like your PDF is encrypted (even though anybody can decrypt it without knowing any password). The encryption is quite complex, and we don't have resources to implement it now.

I added a message, which says, that the PDF is encrypted, when you open such PDF in Photopea.
