### ISSUE TITLE
Thanks for Photopea!

### ISSUE THREAD

**Issue by enzyme69** [photopea/photopea#1088]
I am using Photopea to generate "Depth Map" for Facebook 3D Photo. Works perfectly without any hickup! Ok maybe when I am using iPad and Duet Display when painting and clicking on tools, it create this weird LINE, but anyhow~ Great Tool!!

<img width="1070" alt="screen shot 2018-11-13 at 11 42 23 am" src="https://user-images.githubusercontent.com/3952687/48383277-38fc2180-e739-11e8-9fe9-2da93b4819bf.png">

**Comment by photopea** [comment]
Hi, which line do you mean? the line around your hand looks like a selection. You should press Select - Deselect (or Ctrl+D) to remove it (but it does not get into a final photo anyway).
