### ISSUE TITLE
I can't use thai font

### ISSUE THREAD

**Issue by Awa1t** [photopea/photopea#1090]
Can you make it ?

**Comment by wutkaru** [comment]
@photopea Could you add this font list to project?

Thai Font List
- [Prompt ](https://fonts.google.com/specimen/Prompt)
- [Kanit](https://fonts.google.com/specimen/Kanit) 
- [Sarabun New](https://www.f0nt.com/release/th-sarabun-new/) 

Thanks :wave:

**Comment by photopea** [comment]
@wutkaru But these fonts are already in Photopea.

I just added a selector for "Thai" fonts into the list of selectors.

**Comment by photopea** [comment]
There is still a problem with rendering wovels

![46800553_1028677803971434_8246280987198095360_n](https://user-images.githubusercontent.com/15955558/49005783-dc046080-f167-11e8-984c-a3b5f6acb20b.jpg)

**Comment by photopea** [comment]
It was fixed.
