### ISSUE TITLE
PNG export

### ISSUE THREAD

**Issue by cardosojoao** [photopea/photopea#1091]
Simple set of rules to allow to easily export different layers into PNG files.

As a user I need to be able to export multiple layers into a single PNG, following the order of layers.

using a predefined separator in this example "_" (underscore) I want the  3 layers ( in the example bellow) to be exported into a single png file called "boat.png".
boat
boat_color
boat_shadow

**Comment by photopea** [comment]
Hi, do you want layers to be placed one next to another horizontally? Or one over another (the rest of layers hidden) ?

When you have the Move tool, you can select multiple layers (in Layers panel) and click Get PNG / Get SVG in the top menu (to export only selected layers).

**Comment by photopea** [comment]
I have to close it because of lack of details :(
