### ISSUE TITLE
Can't Open Photoshop Made PSD

### ISSUE THREAD

**Issue by moonie68** [photopea/photopea#1092]
Hello. I made a PSD file in Adobe Photoshop CC 2018, and when I open it on photopea,

1. A white box appears that is titled 'loading'.
2. it stays that way for a long time
3. I close it because I'm worried that the computer will crash.

**Comment by photopea** [comment]
Hi, can you send us your PSD to support@photopea.com ?

**Comment by moonie68** [comment]
I wouldn't like to email, can I upload a psd on here?

**Comment by moonie68** [comment]
I will have taken out a personal item. Just note that the personal item is a rounded text in the [Federation Wide](http://www.st-minutiae.com/resources/fonts/Federation_Wide.zip) font. The link is a direct download.

**Comment by photopea** [comment]
Hi, I fixed the problem. I am very sorry for such delay :(

**Comment by moonie68** [comment]
Oh, you're fine!
