### ISSUE TITLE
Clipping masks not always working as expected

### ISSUE THREAD

**Issue by textoo** [photopea/photopea#1095]
Hello,
first i have to say i am very impressed by the work already done on Photopea.
Thank you for this great piece of code.

I have found that sometimes clipping mask are not working as expected : 
in my case in a PSD with two folders each containing clipping masks, only the clipping masks in the second folder are working.

Steps to reproduce :

- download and extract https://cdn.qwertee.com/images/qwertee-mockup-kit.zip
- open PSD in Photopea
- delete the 2 first layers called "delete this" and "delete also..."
- open layer folder "Artwork" and draw something on the "Paste Artwork Here" layer
- you may notice that your drawing is not visible at all

Configuration :
Linux Mint 18.3  64bit
Chromium 70.0.3538.77

**Comment by photopea** [comment]
Hi, the layer below, named "Clipping Mask", has a Fill set to zero (see Blending Options). You should change the Fill to 100% to make the layer above visible.

In fact, the "Clipping Mask" layer has the "Blend Clipped Layers As Group" disabled, which makes the top layer still visible, even thought the Fill is Zero. Sadly, Photopea does not support these advanced blending options (they are rarely used).
