### ISSUE TITLE
Cannot open Photopea's PSD in Photoshop

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1097]
Hi. 
Today i have a problem trying to open a PSD file on photoshop.

Here is the PSD i made on Photopea: 
[Cajita Condensada.zip](https://github.com/photopea/photopea/files/2591471/Cajita.Condensada.zip)

When trying to open in Photoshop 2018, 2017 and 2016  it says an error has occurred and cannot be opened. :(

There is something i can do to help?

**Comment by photopea** [comment]
Hi, does it come from a PDF? Can you send us your PDF file?

**Comment by avagp** [comment]
No, I created on Photopea.

But here is the PDF output:

But I did use elements from other PDFs in this

**Comment by photopea** [comment]
Can you open any of your PDFs in Photopea, save it to PSD, and open it in Photoshop (without any editing)? Maybe you will find such problematic PSD.

**Comment by avagp** [comment]
These are the original files.

I redone all the graphic on Photopea, but I copied some elements from this files by opening them in photopea and cop
[Archive.zip](https://github.com/photopea/photopea/files/2591871/Archive.zip)
ying into the new project

If i have to take a guess i will say that the Logo of the box has the problem.

**Comment by photopea** [comment]
Do you have a PDF with this part? https://i.imgur.com/T6Qui6W.png

**Comment by avagp** [comment]
Yes. Here is the PSD.

And here is the original AI:
https://drive.google.com/open?id=1GdKSwEmLqOwulx2OpAj_NHXoUYTz41fD

[Pasalo chancho.zip](https://github.com/photopea/photopea/files/2591913/Pasalo.chancho.zip)

**Comment by photopea** [comment]
Ok. So it looks like your PSD (or some part of it) was produced with an old Photopea, which did have a bug. If you do the same work in a new Photopea, your PSD will work correctly in all versions of Photoshop.

So the new Photopea works well and there is nothing to fix. But I did make one change: if you open your current PSD (damaged by the old Photopea) in a new Photopea and save it as PSD, the new PSD will be fixed :)

**Comment by avagp** [comment]
It worked!!!!!!!!!
I kept my promise:
![screenshot 2018-11-19 at 20 52 37](https://user-images.githubusercontent.com/11801254/48742371-7121c980-ec3d-11e8-9d25-ece40b37e800.png)
![screenshot 2018-11-19 at 20 53 55](https://user-images.githubusercontent.com/11801254/48742378-72eb8d00-ec3d-11e8-8e70-4f1c8622e07c.png)


Thank you for such great support!

**Comment by photopea** [comment]
Thanks Alvaro! Thank you for reporting all these bugs! You really helped us make Photopea better :)

BTW. you can join my team: ivan.kuckir@gmail.com , so that you have Premium forever.

**Comment by avagp** [comment]
![image](https://user-images.githubusercontent.com/11801254/48743680-d9bf7500-ec42-11e8-9804-3ef8e09ec2f5.png)
