### ISSUE TITLE
right-to-left text direction

### ISSUE THREAD

**Issue by knizer** [photopea/photopea#11]
text area doesn't type arabic letters

**Comment by photopea** [comment]
Hi,
the font face, that you are using, may not contain shapes for the arabic letters. I discovered, that 
DejaVu Sans, Free Serif  have such shapes. Would it help, if I add "Arabic" checkbox as a next Font Filter? Just like there is Greek, Cyrillic now.

But if you mean typing from right to left, it is not implemented now, but it would be definitely added in the future.

**Comment by knizer** [comment]
i tried DejaVu Sans , still not working , and i tried another iam sure that it contains "Arabic" letters.

**Comment by photopea** [comment]
I think, that the letters are drawn correctly, but in the opposite order. We will add right-to-left text rendering in the future.
![pea](https://cloud.githubusercontent.com/assets/15955558/13724634/6cacab98-e88c-11e5-92b3-67b43ee11ac3.png)

**Comment by photopea** [comment]
We also need to support Farsi - Persian language.

**Comment by knizer** [comment]
use this
https://github.com/knizer/ar-php

**Comment by photopea** [comment]
@knizer  I dont think it can be any useful for me. I need to render arabic letters in Javascript, Ar-PHP is not about rendering letters at all.

**Comment by knizer** [comment]
ok

**Comment by photopea** [comment]
The support for Arabic and other right-to-left languages was added. I am sorry that it took so lonk. Can you check, if everything works correctly?
