### ISSUE TITLE
Working with vector shapes

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#110]
I am drawing a lot in Photopea, and i am really missing the shape tool, for squares, lines and elipsis.

Can i suggest that feature?

Keep the great work!  :D

**Comment by photopea** [comment]
Yes ... working with vector shapes is one of the missing features in PP.  I am planning to add it in the future :)  Now you can only duplicate shapes from other projects, or use Free Transform on them.

**Comment by avagp** [comment]
thank you!

**Comment by landsman** [comment]
PDF open, editing should be cool too!

**Comment by photopea** [comment]
PDF files are usually used as a "final destination" for documents. They don't have a nice structure as PSD, SVG or HTML. So it is almost impossible to make a general-purpose PDF editor.

**Comment by wernight** [comment]
For some things I found using the [Web Symbol](https://www.fontsquirrel.com/fonts/web-symbols) font to be useful.

**Comment by photopea** [comment]
@wernight  This font is already available in Photopea.

**Comment by wernight** [comment]
Yes that's what I'm saying.

**Comment by photopea** [comment]
Added, see https://www.photopea.com/learn/vector-graphics
