### ISSUE TITLE
Suggestions (Channels Panel)

### ISSUE THREAD

**Issue by kevintey** [photopea/photopea#1102]
Heya,

Is it possible for Photopea to have channels panel? In Photoshop, these channels (Red, Green, Blue) represents the whole image when combined (as viewed in viewport). Take the Green channel for example, if that area have alot of Green color, it will be represented with White within the Green channel. 

![sugg-channels 01](https://user-images.githubusercontent.com/41601071/48686046-d9988880-ebf4-11e8-8f2d-c31b4bb6fdcf.jpg)

We can easily extract the channel's selection by Ctrl + Click on the channel thumbnails. And we can further manipulate this black and white map using adjustments (e.g. Levels, Curves, etc)
![sugg-channels 02](https://user-images.githubusercontent.com/41601071/48686047-da311f00-ebf4-11e8-961c-b42c88bb35f6.jpg)

It's a rather complex process/request I reckon. 
What are your thoughts? 

Ps. This feature is vital for some, in their photo editing process.

**Comment by photopea** [comment]
Hi, it is already in our plan, see here: https://github.com/photopea/photopea/issues/285
