### ISSUE TITLE
Translations, English - Finnis

### ISSUE THREAD

**Issue by Ollder** [photopea/photopea#1103]
https://www.photopea.com/  English "Export As" is translated in Finnish: "Tuo" (That means "Import"!) 
Should be "Vie..."
There is no suitable word for the term "As" (because of the structure of the language) but quite usually there is three dots used to tell that more options will open.

**Comment by photopea** [comment]
Hi, I fixed that prhase. You can check and fix our translations at https://www.photopea.com/translate/ 

All our translations are made by users, we can not check if tey are correct :(
