### ISSUE TITLE
Viewing PNG has weird result.

### ISSUE THREAD

**Issue by jwoertink** [photopea/photopea#1104]
I uploaded [this logo](https://www.dropbox.com/s/6ltxwcri7g5hiau/1%261%20IONOS_1125x1125.png?dl=0) just using File > Open. This is how it looks:

<img width="719" alt="screen shot 2018-11-19 at 8 51 57 am" src="https://user-images.githubusercontent.com/2391/48722311-8f091300-ebd8-11e8-9d4b-42feebb0e0e3.png">

I'm not sure what settings I'd need to check to make this display correctly, but this was straight from my first load of the site (ever).

**Comment by photopea** [comment]
Hi, I am very sorry, I just fixed it. Thank you!

**Comment by jwoertink** [comment]
nice! Looks good. Thanks!
