### ISSUE TITLE
Request Feature: Support .EPS file

### ISSUE THREAD

**Issue by wutkaru** [photopea/photopea#1105]
I can't open .eps file. that I download from shuttershock.
Weekly free file from shuttershock: [file](https://ak.picdn.net/assets/cms/c65ebdc8a6521e999ceec6728f49646446d26bb4-shutterstock_782787022.eps)
Unknown file format: 
![untitled](https://user-images.githubusercontent.com/43336971/48747669-9565c080-eca6-11e8-9e16-ea7d49d5df10.png)

**Comment by photopea** [comment]
Hi, I improved the EPS support a bit, now it can handle much more EPS files, that it could before.

However, your file is EPS file generated by Adobe Illustrator. There is a section, where binary data start right after PostScript commands. I am not sure how to parse it and I don't know anybody who could help me :(

I have to mark it as unfixable for now :(

**Comment by wutkaru** [comment]
It was fixed. 
Thank you. 
:heart:
