### ISSUE TITLE
Quality of Life Feature Request : Have the Crop bounding box start around the image automatically.

### ISSUE THREAD

**Issue by BrenanWright** [photopea/photopea#1107]
In Photoshop Creative Cloud the crop box starts around the bounds of the image automatically. It also grays out the parts of the image that aren't being used in the crop before you choose to apply to help you be more precise. I think these would be useful features.

**Comment by photopea** [comment]
In Photopea, you can make a Crop of the whole document using buttons in the top Menu:  Total Content, Selection, etc.
