### ISSUE TITLE
Lensflare filter

### ISSUE THREAD

**Issue by rcoenen** [photopea/photopea#1109]
Please add a lensflare filter! w000t!

**Comment by icexuick** [comment]
really?

**Comment by rcoenen** [comment]
Yeah! For full Photoshop compatibility!

**Comment by CrazyCorbeau** [comment]
that'd be nice

**Comment by photopea** [comment]
It was implemented :)

**Comment by rcoenen** [comment]
Amazing! Well done! Just 1 bug

"Lens 3" and "Lens 4" produce identital results... bug?

LENS 1:
![image](https://user-images.githubusercontent.com/753704/62174660-b936d700-b308-11e9-9e32-517442c6795a.png)

LENS 2:
![image](https://user-images.githubusercontent.com/753704/62174685-ceac0100-b308-11e9-9aa0-926ba7cc0fc9.png)

LENS 3:
![image](https://user-images.githubusercontent.com/753704/62174571-75dc6880-b308-11e9-929f-2ea2e62abf88.png)

LENS 4
![image](https://user-images.githubusercontent.com/753704/62174627-a2908000-b308-11e9-9e55-9cfd7249fa74.png)

**Comment by photopea** [comment]
Hey, I know, I did not have enough time to implement the fourth version. I think three should be enough.

**Comment by AcademyOfF** [comment]
Is it possible to create a lens flare with a transparent background, or is there a way of extracting only the lens flare as its own image? I'm happy to create a new issue for this if there isn't a way to do it

**Comment by photopea** [comment]
When you use filters, you need at least one pixel to apply the filter on.

I recommend applying Lensflare to a fully black layer. Then, you can place that layer over other content with blendmode = Screen.

**Comment by rcoenen** [comment]
Agreed
