### ISSUE TITLE
can't open most psds.

### ISSUE THREAD

**Issue by wndigos** [photopea/photopea#111]
i currently am bound to a chromebook, meaning i don't have ready access to photoshop. photopea is a _lifesaver_, but i've recently ran into a snag that limits the things i do: i'm unable to open most of my psds. the psds are simply for coloring, icons and edits and the like, but as i said before, i'm unable to use the majority of them. i've disabled the webgl and it didn't help, and i've tried probably two dozen psds, and only five of them will open in photopea. am i doing something wrong?

**Comment by photopea** [comment]
Hi,
did these PSDs work before in Photopea? Can you send at least one PSD to support@photopea.com ? Thansk!

**Comment by photopea** [comment]
It was fixed.
