### ISSUE TITLE
Photopea didn't receive your email address.

### ISSUE THREAD

**Issue by bphd** [photopea/photopea#1114]
https://www.photopea.com/papi/login.php?provider=2&code=🤔

array(3) { ["result"]=> array(31) { ["login"]=> string(4) "🤔" ["id"]=> int(🤔) ["node_id"]=> string(20) "🤔" ["avatar_url"]=> string(53) "https://avatars1.githubusercontent.com/u/🤔?v=4" ["gravatar_id"]=> string(0) "" ["url"]=> string(33) "https://api.github.com/users/🤔" ["html_url"]=> string(23) "https://github.com/🤔" ["followers_url"]=> string(43) "https://api.github.com/users/🤔/followers" ["following_url"]=> string(56) "https://api.github.com/users/🤔/following{/other_user}" ["gists_url"]=> string(49) "https://api.github.com/users/🤔/gists{/gist_id}" ["starred_url"]=> string(56) "https://api.github.com/users/🤔/starred{/owner}{/repo}" ["subscriptions_url"]=> string(47) "https://api.github.com/users/🤔/subscriptions" ["organizations_url"]=> string(38) "https://api.github.com/users/🤔/orgs" ["repos_url"]=> string(39) "https://api.github.com/users/🤔/repos" ["events_url"]=> string(50) "https://api.github.com/users/🤔/events{/privacy}" ["received_events_url"]=> string(49) "https://api.github.com/users/🤔/received_events" ["type"]=> string(4) "User" ["site_admin"]=> bool(false) ["name"]=> string(4) "🤔" ["company"]=> NULL ["blog"]=> string(0) "" ["location"]=> NULL ["email"]=> NULL ["hireable"]=> NULL ["bio"]=> NULL ["public_repos"]=> int(2) ["public_gists"]=> int(0) ["followers"]=> int(0) ["following"]=> int(3) ["created_at"]=> string(20) "2014-12-20T10:48:40Z" ["updated_at"]=> string(20) "2018-11-22T08:47:31Z" } ["code"]=> int(200) ["content_type"]=> string(31) "application/json; charset=utf-8" } Photopea didn't receive your email address.

**Comment by photopea** [comment]
Hi, you have to enter your email address into your GitHub account, and make sure third parties will get access to your email address. We already dealed with this problem at this forum (do a search).

I agree, that GitHub settings may be too complex and misleading, so if it is too hard for you to figure it out, use a Google or Facebook to log in instead.
