### ISSUE TITLE
Shows wrong color

### ISSUE THREAD

**Issue by quantumpotato** [photopea/photopea#1115]
I select 7dbfe7

I use paint bucket, I get 

72b7e3

![screen shot 2018-11-22 at 19 58 54](https://user-images.githubusercontent.com/433852/48925420-5d6ea100-ee91-11e8-81c5-dfc52d24e89d.png)
![screen shot 2018-11-22 at 20 00 01](https://user-images.githubusercontent.com/433852/48925423-5f386480-ee91-11e8-9244-f9254fbd6361.png)

**Comment by photopea** [comment]
Hi, what is that second program, that says "72b7e3"? Are you sure it works correctly? Where does it pick the color from?

**Comment by quantumpotato** [comment]
Hey, it's using color picker. Whe nI exported the color (7dbfe7), it does look visually different to me than the color I had selecetd

**Comment by photopea** [comment]
I see, that it says "color picker" in the top bar of your tool. But I have no experience with it. Are you sure it works correctly?

"When I exported the color" - what do you mean? Did you save your document as JPG / PNG? Can you show us the file?

**Comment by quantumpotato** [comment]
https://youtu.be/HknKXPIf6Lo
![download](https://user-images.githubusercontent.com/433852/49186626-2ab22600-f333-11e8-9d6a-178c05c11ef2.png)

**Comment by photopea** [comment]
I still think it is a bug in your color picker program. It probably interprets the input image as some other color space, and not sRGB.

Have you ever tried to pic colors from other websites? E.g. from https://www.color-hex.com/color/77d4d4 ?

**Comment by quantumpotato** [comment]
You're right! Sorry to bug you about this. Thanks for your quick responses.
