### ISSUE TITLE
Feature request: Copy current canvas as an image

### ISSUE THREAD

**Issue by avi12** [photopea/photopea#1116]
Please add to the Export menu an option to copy the canvas as an image, in case, for example, that I'm using the service only to later share this image on WhatsApp, which allows sharing images by pasting them.
Also, I would suggest to let the user export the image (as a file / copy to clipboard) in a custom format specified by a text box.

**Comment by photopea** [comment]
Sadly, web apps can not copy images into a system clipboard yet :(  There is an experimental solution, which only works in Firefox. Hope the situation will improve soon :(
