### ISSUE TITLE
Add IFF support

### ISSUE THREAD

**Issue by rcoenen** [photopea/photopea#1117]
Please add support to at least read (and preferably export) Amiga IFF files (formally known as ILBM IFF Interleaved Bitmap) 
For sample files: https://www.fileformat.info/format/iff/sample/index.htm
Parser here: https://github.com/svanderburg/libilbm
Fileformat here: http://wiki.amigaos.net/wiki/ILBM_IFF_Interleaved_Bitmap

**Comment by rcoenen** [comment]
another possible better ILBM IFF library https://github.com/wiesmann/ilbm.js

**Comment by photopea** [comment]
Is it really used in practice? Maybe people should just convert all ILBM files into PNGs, and then use only PNGs.

**Comment by rcoenen** [comment]
It's a fileformat that was supported by default until Photoshop CS3 if I am not mistaken. The most recents versions still support it but you'll have to add the filter yourself (by moving it into the plugins directory). It's an esoteric format these days but it was a great standard format used in many games and demoes. Occasionally it still pops up, and it would be great to support it for completeness sake. The demo and 8 biut gaming and emulator scene is still using it too. 
From my perspective if anything, IFF is a more common and useful format than the CorelDraw.

**Comment by photopea** [comment]
I implemented it! :)

**Comment by rcoenen** [comment]
so when can we use it? Do you need to deploy the changes still?

**Comment by photopea** [comment]
I deployed it yesterday. It works well with all 15 IFF files that I found on the internet. But if you have an IFF file, which does not work, please, send it  to me
