### ISSUE TITLE
Feature request: set file name in save / export

### ISSUE THREAD

**Issue by hallworth** [photopea/photopea#1118]
I would like to be able to set the file name when saving / exporting

**Comment by photopea** [comment]
Hi, the saving is completely in hands of your browser. You must set your browser to let you change the file name when saving files.

E.g. for Chrome, here is how to do it: https://support.google.com/chrome/answer/95759?co=GENIE.Platform%3DDesktop&hl=en-GB . You should enable "Ask where to save each file before downloading"

**Comment by hallworth** [comment]
brilliant! thank you for your quick response.
