### ISSUE TITLE
Is it possible to remove tourists from the travel photos?

### ISSUE THREAD

**Issue by lipis** [photopea/photopea#1119]
Reference: https://www.reddit.com/r/interestingasfuck/comments/a12y2u/how_to_delete_tourists_from_your_travel_photos/

**Comment by lipis** [comment]
Tripod! That's a well known technique..

**Comment by photopea** [comment]
You can do it in Photopea now. These steps work in Photoshop, too:

1) load all photos as layers into one document.
2) select all layers (in Layers panel), right-click, "Convert to Smart Object"
3) Press "Layer" - "Smart Object" - "Stack Mode" - "Median"

**Comment by MichalSZZ** [comment]
OMG I should test it if I find some photos in my library. I even didn't know that Photoshop has that feature :) 

I have heard about 'stack' technique for adding more depth. Now I know one more thing for Photoshop from Photopea GitHub site :D
