### ISSUE TITLE
program locks up and stops working if the image is over 1000 px and u

### ISSUE THREAD

**Issue by Centurion2016** [photopea/photopea#112]
if the image is over 1000 px and usually stops working and crashes. it is aggravating

**Comment by photopea** [comment]
Hi, I just tried to create a new 2000x2000 px image and everything went well.

Are you having problems with a specific PSD? How large is it (in Megabytes)? Can you share it with us (you can send it to support@photopea.com) .

**Comment by photopea** [comment]
I have to close it because of the lack of details :(
