### ISSUE TITLE
Start open sourcing more things!

### ISSUE THREAD

**Issue by lipis** [photopea/photopea#1120]
First of all this project is just awesome!

Now that this project is well established, I think it would be a great idea to start open sourcing more things so you can offload your work, and people can improve things for _free_.

For example: There is no need to maintain your own custom blog in a closed source, open source it (maybe even use Gatsby) and have it in the open. Somebody will come and improve it one day.. no need for you to spend time on it.

Extensions, Filters, Various Components, etc, if your app is modular you have nothing to lose to start open sourcing some of them, and besides the obvious that people could improve, maybe they will start contributing with new features/filters and stuff.

WDYT?

**Comment by photopea** [comment]
Hi, thanks!

We already discussed it here: https://github.com/photopea/photopea/issues/45 . We can continue the discussion there.

We are not planning to open the source of more features at the moment. Our current free libraries are used by some people, but nobody is contributing to them. I think, that open-sourcing other components would not encourage people to help us, but to implement those features into their own software (those features are exclusive to Photopea now).

What do you mean by maintaining a custom blog, and by improving it? Do you mean the content of a blog? We use WordPress for our blog.
