### ISSUE TITLE
Artifacts in PDF import

### ISSUE THREAD

**Issue by eddy386** [photopea/photopea#1124]
Artifacts and huge pixels appear in several places. Image attached (those pixels shouldn't exist, that part is mostly white).

![captura2](https://user-images.githubusercontent.com/45461435/49237743-294e2f80-f3ff-11e8-8890-64a88ea171ef.JPG)

**Comment by photopea** [comment]
Hey, can you send us your PDF file?

**Comment by eddy386** [comment]
Here you have!

**Comment by eddy386** [comment]
[03 scan.pdf](https://github.com/photopea/photopea/files/2630133/03.scan.pdf)

Here you have!

**Comment by photopea** [comment]
Hi, I fixed it. Thanks for pointing it out! :)
