### ISSUE TITLE
I cannot open sketch file 

### ISSUE THREAD

**Issue by Yivivi** [photopea/photopea#1126]
Hey guys,

I am trying to open a sketch file form my Desktop,but I can not open it, Loading is all time.
=> File Size 3.6 MB
I hope you can help solve the problem, thank you very much.

![snip20181203_3](https://user-images.githubusercontent.com/45549559/49354124-323f4980-f6fc-11e8-8b30-02e3784f90f9.png)

**Comment by photopea** [comment]
Hi, can you send us your Sketch file? Either here on GitHub, or to support@photopea.com .

**Comment by Yivivi** [comment]
OK.I have sent the file to the mailbox.

**Comment by photopea** [comment]
Thanks! It was fixed.
