### ISSUE TITLE
(For fly out menus) click the menu item again to fold it up

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#1127]
Click once on the menu items wil expand them, and click it again should fold them up, for both the top menu flyouts and the effects/adj layer shortcut flyouts in layers panel

This is especially needed on mobile devices that have limited blank space for "click out"

**Comment by photopea** [comment]
Hi, I fixed it, thanks!

**Comment by hgs54371** [comment]
On desktop worked, but not on mobile browsers like iphone and ipad, both latest version

Also the two flyouts in layers panel (layer style and adj layer list) are missed

**Comment by hgs54371** [comment]
On desktop : top menu and side panel ok, two flyouts in layers panel not

On iphone and ipad : Side Panel Ok, top menu and two flyouts in layers panel not

The side panel is working as usual on ios in all browsers, the other two just need to be implemented as the way for side panel, all are latest

**Comment by photopea** [comment]
Hi, I think I fixed it. Regarding iOS, are you sure you are using the latest iOS? As it is probably a bug in iOS, we can do nothing about it.
