### ISSUE TITLE
Losing opened Projects from auto page reloads

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#1128]
One problem of working with projects in a browser is that it will be unexpectedly auto reloaded when switch back from other tabs or apps/tasks, especially on mobile devices where available ram is limited for multitasking. 

Apart from the memory management that is done by the OS and the browser, is there something that can be done on the webpage itself to prevent these auto page reloading from happening

For example on an iphone 6 with 1g ram, the photopea tab opened in safari will almost always be auto reloaded(project lost) when switching back from other tabs or apps/tasks

**Comment by photopea** [comment]
Hi, I was not aware of this, this is really bad :( When you have unsaved work in Photopea, the browser should let you close it, before you save it. Have you tried to close it directly, to see if it works?

Can you try to report it to creators of your browser?

**Comment by hgs54371** [comment]
The pop up dialog to confirm stay/leave when close/refresh tab is not present on safari iOS
But this is not the main point of this issue, the thing here is to retain opened page contents After switching back from multitasking, either by not dumping them to make room for multitasking, or they can be reloaded invisibly after dumping

I have encountered some sites that can retain contents after a page refresh, for example http://pasted.co/ , the texts are retained after page refreshes, on desktop browser but not mobile

I have reported this at https://www.apple.com/feedback/safari.html , but not yet at https://webkit.org/reporting-bugs/ , cause I haven't had enough understanding of those terms

**Comment by photopea** [comment]
Are you sure you are using the latest iOS with the latest Safari?

I really don't see how I could help you. If it was a text editor, it is very easy to save the text into Cookies or something. But it is quite hard to do the same for an image editing work, the whole document and the history of editing. It seems stupid to do so just because of a bug in a minority browser.

I really think the authors of your browser should fix it. Or buy a better device to run Photopea (e.g. Android Phone or something).

**Comment by hgs54371** [comment]
They are latest and this is not a bug, other apps will also reload under heavy multitasking, it’s just hardware limitation combined with how it is designed right now
Maybe the way you mentioned is worth a try, at least it’s better than nothing

**Comment by photopea** [comment]
If you know, that your browser may "kill" and reload some webpages, and you think it is OK, you should save your work gradually to a permanent memory (e.g. as a PSD file).
