### ISSUE TITLE
Trimming image

### ISSUE THREAD

**Issue by martin11591** [photopea/photopea#1130]
Photopea stops refreshing actions on image after unsuccessful trimming.

How to reproduce:

Create empty image, create new layer, clear it to be empty (transparent), so we have only one empty transparent layer. Click **Image** -> **Trim**.

Photopea tries to trim layer and after this, if you try to select something then it'll not show selection until you change opened image tab to other and come back. Same with other actions like moving part of image.

Sorry for my english.

![problem](https://user-images.githubusercontent.com/21086183/49503276-55dacf00-f877-11e8-8956-1456ab89bbce.png)
[exception.txt](https://github.com/photopea/photopea/files/2648068/exception.txt)

**Comment by photopea** [comment]
Wow, thanks for finding this bug! I just fixed it :)
