### ISSUE TITLE
Leading Character not working

### ISSUE THREAD

**Issue by sonamdawa101** [photopea/photopea#1131]
Leading in Character option is not working. Can't use arrow up or down. Entered value does't make any changes to the paragraph

![capture](https://user-images.githubusercontent.com/36448436/49504463-b7169880-f89f-11e8-842a-e44c437eac02.JPG)

**Comment by photopea** [comment]
Hi, the Leading should change the space between lines of text. I just tried it  with Mina Regular font and it works well for me. Can you tell us, what did you do and what happened?

**Comment by sonamdawa101** [comment]
I checked again and found that **if the value in the LEADIND is smaller that FONT SIZE than LEADING doesn't affect.** 
If LEADING value is bigger than font size than LEADING works? !!!

**Comment by photopea** [comment]
You can set a different value of Leading to each character. Then, the leading of a line is the maximum of leadings of all characters. Maybe you did not select some character when selecting text (its leading remained Auto), so the leading of the whole line is Auto (= Font size).
