### ISSUE TITLE
Mirror Mode Painting

### ISSUE THREAD

**Issue by enzyme69** [photopea/photopea#1132]
I wonder if this is something that be added in near future? A mirror symmetry mode for painting. Maybe mirror in X Y or kaleidoscope way...

**Comment by photopea** [comment]
Personally, I think such feature is more of a toy than a useful thing. When you draw anything, you can duplicate it and rotate it with a Free Transform, and merge layers, to get the same result. You can also write a script for this (check out File - Script, there is already such script!).

I think it is better to focus at more important features at the moment.
