### ISSUE TITLE
Duplicating into a new project crashes the website

### ISSUE THREAD

**Issue by steven4547466** [photopea/photopea#1133]
Whenever I use "Duplicate Into" > "New Project" the entire website crashes. I can still switch projects, but I can't do anything in them or save them. I've tried waiting, restarting my computer, reloading the tab and closing the tab. The screenshot shows what the layers look like after using the duplicate button in the new project.
![screenshot 2018-12-07 at 7 02 24 am](https://user-images.githubusercontent.com/23726534/49646752-1682be80-f9ee-11e8-961d-c7871242f5fa.png)

**Comment by photopea** [comment]
Hi. When you open Demo: pea.psd (from the intro menu) and duplicate any layer into a new project, does it crash, too? (it does not crash for me).

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by valerianb** [comment]
Hi, I have this issue too.

```

**Comment by photopea** [comment]
I fixed it! Thanks for reporting it! :)
