### ISSUE TITLE
Feature request: mouse wheel zoom in/out

### ISSUE THREAD

**Issue by eugenebbb** [photopea/photopea#1134]
Is it possible to zoom in and zoom out using wheel only? 
When moving mouse to the edge of the screen the photo moves that way automatically, same way as in Photoshop CS5?

When I clean photos I have to zoom in and out a lot,  letting the mouse go to press CLRL + - takes way too much time.

Thank you for your work the tool is awesome!

**Comment by MichalSZZ** [comment]
Try to use alt + mouse wheel. In that way it's work in Photoshop.

**Comment by photopea** [comment]
Yes, the wheel scrolls up and down by default, but it can zoom after you press Alt.

**Comment by MichalSZZ** [comment]
But one thing from Photoshop doesn't work currently in Photopea.
When you have for example polygonal lasso tool and want to move working view on big zoom, in photoshop, when you are on the edge of working space, image slowly go in direction of your mouse

**Comment by eugenebbb** [comment]
> But one thing from Photoshop doesn't work currently in Photopea.
> When you have for example polygonal lasso tool and want to move working view on big zoom, in photoshop, when you are on the edge of working space, image slowly go in direction of your mouse

Exactly this is what I wanted to say.

**Comment by MichalSZZ** [comment]
That works for tools:
Rectangle and eliptical selection
Polygonal and magnetic lasso
Crop tool (when drawing crop view)
Rooler tool
Gradient tool (when drawing line)
Text tool (when drawing paragraph size)
All shape tools.

**Comment by photopea** [comment]
In other words, now, it works only when mouse is pressed.

**Comment by photopea** [comment]
Hi, I made it work for Polygonal and Magnetic lasso, too.

**Comment by eugenebbb** [comment]
Thank you!
