### ISSUE TITLE
Photopea's paths looks weird on AI or Photoshop 

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1135]
One more issue about paths ;)

But the best side is it keeps getting better on being a reliable alternative to classic alternatives.

Well, here is the issue:

I have a created a logo only with paths, and in photopea looks great:
![image](https://user-images.githubusercontent.com/11801254/49688850-099dc200-faf7-11e8-8573-9693f4d69c79.png)
Here is the PSD
[Logo.zip](https://github.com/photopea/photopea/files/2659910/Logo.zip)

But when opening on Photoshop or Adobe Ilustrator i get this (picture taken from the screen):
![image](https://user-images.githubusercontent.com/11801254/49688878-8af55480-faf7-11e8-93a1-06c7aa212ed0.png)

The eye, the side, the left fingers, the mouth, the little cap on top, gets weird lines on them.

Maybe i should resave them to PSD again, because you already did some correction? Or is something different this time?

(I cannot test it myself inmediatly, but i will send it to the company who uses the logo)

Cheers!

**Comment by photopea** [comment]
Hi, Photopea works a little different, than Photoshop.

In Photoshop, you can not create two open paths in one layer, and stroke them "openly". Look at this PSD. Open it in Photopea and then in Photoshop. 
[curves.zip](https://github.com/photopea/photopea/files/2665045/curves.zip)

Do you think we should make the paths work the same as in Photoshop, or keep them the way they work in most of vector editing programs?

**Comment by avagp** [comment]
I am just thinking out loud here:

I believe it should behave like photoshop, because photopea is a tool that should replace the functions of what photoshops do, and also behave as an bridge that can send or receive files from Photoshop.

Similar to what google drive did in the past, because MS office was the rule, drive had to be able to open and export properly to MS office (and MS office changed little things on every iterations so google cannot catch up), because both knew that the ability of compatibility was the key to reduce the cost of change of the users. Thus changing to google drive was an easy.

Like two different personas that talk the same language, photoshop and photopea are different work spaces that should communicate flawlessly, specially if you what more people to change or try photopea,  their work should transfer perfectly to their main platform.  

If that is not the case, why making PSD the main file format in the first place?

What do you think?


Even though, the mouth and the eye deconfiguration seems not to be related to the topic (from my ignorant point of view), but rather to a extension of the actual path. Different from what happens to the side of the milk box, the little cap on the top and the left finger, where the paths closes.

**Comment by photopea** [comment]
Have you tried to open my little PSD in Photoshop? The thing is, that this shape (as well as shapes in your PSD) can not be drawn in Photoshop at all. The only thing I can do is to remove these layers completely during the PSD export.

**Comment by avagp** [comment]
I have not opened your file yet, because most of the time i have no access to photoshop, but my clients and providers has. As soon as i can i can check. But i assume those curves will come closed, more like an O than a U.

On the other hand, if you delete them during the exporting process, is not a real solution, because i will lose some piece of the work. :/

You should not let those paths be drawn in the first place, right?  (which sounds really difficult)

**Comment by photopea** [comment]
I wrote an email to Adobe about it, will see what they reply.

**Comment by avagp** [comment]
Today i opened the curves file.

As i though they came closed.

BUT, when exported to SVG and opened on AI, they kept their U shape.

Tomorrow i will export the Mala Leche logo on svg and open on AI and analyse the result.

Maybe you were right. With SVG and PDF you should be able to handle all platforms.

**Comment by photopea** [comment]
Hi, I did not get any response from Adobe.

The problem is, that SVG does not support Inner - Outer stroke. To simulate outer stroke in SVG, Photopea draws 2x thicker line, and the layer is filled after stroking (so the inner stroke is not visible). If you open the SVG from Photopea in a browser, it should look right. So I think it is a bug in Illustrator, for not loading SVGs correctly.

BTW. can you export your graphics from Illustrator to SVG and show me how it looks like? Does it preserve outer stroke?

**Comment by avagp** [comment]
I will try.

**Comment by avagp** [comment]
By the way, mean while i should change all the paths to center in order to see them correctly on AI?

**Comment by photopea** [comment]
Hi @avagp , I think I got lost in what we are trying to solve, and what AI / PSD / SVG file is related to it.

Could you maybe report it again, and attach the one file, that it is related to?

**Comment by avagp** [comment]
XD

Ok

**Comment by photopea** [comment]
So I fixed the problem with "closed curves". When you save a document as PSD, and there is an open curve in a layer with multiple curves, that curve will be separated into a new layer. So the resulting PSD looks correctly in Photoshop.

**Comment by avagp** [comment]
![image](https://user-images.githubusercontent.com/11801254/51440648-286fa680-1ca8-11e9-95ef-6742d36b6c7e.png)
This little triangles on top of the shapes comes from the same problem of trying to close the vector?

**Comment by photopea** [comment]
Yes, our current vector drawing tool only supports "central" stroke. So we simulate outer stroke by drawing a 2x thicker stroke first, and filling it afterwards.  People usually "close" filled paths in practice, so your example almost never happens (I guess you know, that you can connect the end point with a beginnign point with a straight line).

**Comment by avagp** [comment]
Ok. here is what i test.
Photopea -> Ilustrator
Ilustrator -> Photopea

This picture was made on Photopea:
![image](https://user-images.githubusercontent.com/11801254/51508699-3b33c980-1dd5-11e9-8b59-3841a0d675f6.png)
A) a bag shape non-closed vector
B) a line with outer stroke
C) a line with center stroke
D) a line with inner stroke 

And exported it as PSD, SVG and PDF and opened them on Ilustrator, which afterwards i exported them to SVG.

In every step i took pictures of the screen, here they are:

PSD open on Ilustrator:
![image](https://user-images.githubusercontent.com/11801254/51508882-f0ff1800-1dd5-11e9-95c2-15535120a78b.png)

SVG open in Ilustrator:
![image](https://user-images.githubusercontent.com/11801254/51508876-e8a6dd00-1dd5-11e9-8887-c205b769706d.png)

PDF open in Ilustrator:
![image](https://user-images.githubusercontent.com/11801254/51508877-ecd2fa80-1dd5-11e9-8063-f6645cf3fe30.png)

PSD exported to SVG in Ilustrator:
![image](https://user-images.githubusercontent.com/11801254/51508905-0b38f600-1dd6-11e9-8e3a-96835a73d74c.png)

SVG exported to SVG in Ilustrator:
![image](https://user-images.githubusercontent.com/11801254/51508922-1429c780-1dd6-11e9-9e61-4a669d133ffe.png)

PDF exported to SVG in Ilustrator:
![image](https://user-images.githubusercontent.com/11801254/51508897-03795180-1dd6-11e9-87e0-59c2adcb9828.png)




==Conclutions==
