### ISSUE TITLE
Open with Google Drive - Feature request

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1136]
Since ever i have used Photopea as a webapp, which means that i don't use it on a browser tab, but on its own window instead. So most of the time i launch Photopea on itself, and then select a file to open.
![image](https://user-images.githubusercontent.com/11801254/49688967-b593dd00-faf8-11e8-9c87-8f95e3c2359e.png)

I have everything on Google Drive, and i really like the feature to be able to open a Google drive file FROM GOOGLE DRIVE into Photopea.

But i really miss the option to open from Photopea a Google Drive file and have the possibility to save the modifications.

I will be very comfortable to have, and will push further more the use as a standalone webapp rather than a Google Drive addon.

Cheers!!

**Comment by avagp** [comment]
Is there anything i can clarify about this request?

**Comment by avagp** [comment]
Good news Ivan!

No pressure on my issues, just wondered if you missed it.

Cheers man!

**Comment by OfficialNoob** [comment]
This would be also be useful for collaboration. even better if it had the "Place Linked" feature

**Comment by s5706820** [comment]
Now, it's already able to save to google drive. this is so great!
 still waiting to browse through GGdrive via Photopea, this will make it's freaking awesome!!

**Comment by photopea** [comment]
There are many online storages (google drive, Dropbox, One Drive ....). I was hoping that they will make the same API to access. It would be much easier for us to implement then.

**Comment by s5706820** [comment]
No mean to rush you.
Thx you for your hardwork all along. Love you Ivan😘

**Comment by avagp** [comment]
With the new photopea update where we can save directly to the file without creating a new PSD i can work perfectly on my chromebook.

I can open a PSD from the Files App and save the modifications.

So for me at least, i have no more issues.

**Comment by jspence2018** [comment]
Hi, teacher here. My school just added the Photopea add-on to Google Drive. However when I go to open a photo with Photopea, it won't open the photo, it will just open Photopea. HELP?  I have kids on Chromebooks that will only be able to use Photopea from their Google Drives. They need this for editing their AP Art portfolio pics. Thanks!

**Comment by avagp** [comment]
Hello jspence.

I have using Photopea on my chromebook since 3 years I think.

You can totally set to use Photopea as the default option to open psd and
image files on google drive.

Try to look on open with.

I can give you a little tutorial when I reach my computer later.

:)

**Comment by jspence2018** [comment]
Alvaro, thank you so much!
Photopea contacted me... with me it was my Chrome setting for the pop up
blocker and I had to allow the website. I am not sure what will happen with
the Dept of Ed chromebooks.... I may hit you up if there is a challenge
with that, but it will most likely be a permissions problem, and as
students they won't be able to change it...

best,
Jen

Jen Spence, Art
Brooklyn Preparatory High School
257 N 6th Street
Brooklyn, NY 11211
718-486-2550

"Every child is an artist. The problem is how to remain an artist when he
grows up."
---Pablo Picasso

"Perhaps the mission of an artist is to interpret beauty to people - the
beauty within themselves." - Langston  Hughes

**Comment by avagp** [comment]
I have to add this here.

The open in Google Drive works.

But what doesn't work is to open the webapp when it is open.

So, i filled an issue on the chromium issue tracker to ask for this. 

I have Photopea as a webapp, and it would be great to open google drive files ON the webapp, instead of a tab. Because on the webapp i have more control over the app itself. Like key combos and other things:

https://bugs.chromium.org/p/chromium/issues/detail?id=1214687&q=&can=4

**Comment by avagp** [comment]
Maybe another way around will be Open From Google Drive.

What do you think @photopea ?

Using the Google Drive API to check the user files and open them in Photopea

**Comment by photopea** [comment]
I have been working on it for weeks and I am planning to release it soon.

**Comment by jspence2018** [comment]
Hi, it's been a long time since I sent this lol.  It's all good. We figured
it out.

**Comment by photopea** [comment]
Hi guys. After you go to https://www.photopea.com/ , there are "storages" on the left side. Basically, it is a file explorer for different "storages", one of them is Google Drive. You must give Photopea permissions to access your Google Drive. What do you think about it? :)

**Comment by avagp** [comment]
Woohoo!

I'll check and report back!
