### ISSUE TITLE
Stuck on loading

### ISSUE THREAD

**Issue by JordanFai** [photopea/photopea#1138]
I am working on a project using a template and it permanently says "loading" across the top. I have tried in both Chrome and Brave.. restarted many times etc. I am also not able to add text; I can open a text box but when I type, nothing shows up

**Comment by photopea** [comment]
Hi, can you try it now again?

**Comment by JordanFai** [comment]
No change. I'm loading a PSD from my computer. It loads but the "loading" banner doesn't go away.

**Comment by photopea** [comment]
Can you send me your PSD to support@photopea.com ?

**Comment by JordanFai** [comment]
Sent

**Comment by photopea** [comment]
Hi, can you try now, if it works? It works fine for me.

**Comment by JordanFai** [comment]
Yes, works now. Thanks

**Comment by photopea** [comment]
Great!
