### ISSUE TITLE
Some fonts crashes photopea

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1139]
I wanted to use font Bungee Shade and it crashes with this error:

ext.js:13245 Uncaught e
Typr._lctf.readCoverage @ ext.js:13245
Typr.GPOS.subt @ ext.js:13994
Typr._lctf.readLookupTable @ ext.js:13185
Typr._lctf.readLookupList @ ext.js:13164
Typr._lctf.parse @ ext.js:13150
Typr.GPOS.parse @ ext.js:13981
Typr._readFont @ ext.js:12989
Typr.parse @ ext.js:12914
RX.Mx @ pp.js:7581
RX.jH @ pp.js:7565
load (async)
RX.jk @ pp.js:7539
RX.If @ pp.js:7536
Rd.jQ @ pp.js:7759
Oi.u @ pp.js:9
Rs.Ah @ pp.js:20
so.GG @ pp.js:5068
m.aM.aO @ pp.js:3301
m.aM.nk @ pp.js:3292
Rd.bp @ pp.js:7809
Rd.jQ @ pp.js:7789
Oi.u @ pp.js:9
dT.u @ pp.js:5421
dT.u @ pp.js:5421
dT.u @ pp.js:5421
dT.u @ pp.js:5421
kU.It @ pp.js:5710
kU.skV @ pp.js:5719
Oi.u @ pp.js:9
dT.u @ pp.js:5421
Rj.yE @ pp.js:5743
Rj.sVU @ pp.js:5741

Some other Bungee fonts crash too (Bungee Hairline, Bungee Inline, Bungee Outline)

**Comment by photopea** [comment]
Hi, I fixed it, thanks!
