### ISSUE TITLE
iframe and chrome error

### ISSUE THREAD

**Issue by byrning** [photopea/photopea#114]
Hi,

So there appears to be an issue with running photopea in an iframe with the chrome browser. Photopea fails to load. If works fine in Firefox, Safari and IE though.

The chrome errors are:

Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.(…) @ VM746 pp.js:116

and

Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.(…)  @ VM746 pp.js:120

Possibly you can try/catch that for chrome users, or just in general?

**Comment by photopea** [comment]
I tried it here and it works for me in Chrome: https://jsfiddle.net/pk88jdt1/  ... does this demo work in your chrome?

**Comment by byrning** [comment]
I tried another mac with chrome and works fine. It looks like "block third party cookies and data" was enabled in my chrome. I'm sure that setting was enabled by default in the past, whereas now for new chrome installs, it is unchecked by default. Maybe google heard people's screams. :)

Thanks anyways.
