### ISSUE TITLE
Problem with opening SVG icon

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1141]
I tried to open SVG icon/emoji from here in photopea:
https://github.com/twitter/twemoji/blob/gh-pages/svg/1f332.svg
But image was hidden initially and I needed to disable or delete some incorrect Vector Mask.
I think it incorrectly reads or interprets "clip-path" property there.

**Comment by photopea** [comment]
There is an SVG path  "M 0,38 38,38 38,0 0,0 0,38 Z" . I thought it means "moveTo" five times, but other coordinates are probably for "lineTo". I just can not confirm it anywhere :(

**Comment by photopea** [comment]
Ok I just found it here: https://www.w3.org/TR/SVG/paths.html  : "If a moveto is followed by multiple pairs of coordinates, the subsequent pairs are treated as implicit lineto commands."

**Comment by photopea** [comment]
It was fixed, thank you!
