### ISSUE TITLE
Please add power of 2 size for new files (Feature request)

### ISSUE THREAD

**Issue by samafshar** [photopea/photopea#1143]
Hi.
Many game artists need to use power of 2 image size (32x32, 64x64, ... , 4096x4096) for their texture assets. 
Please add a section in "New File" menu for it.
Thank you.

**Comment by photopea** [comment]
Ok I added it. But I am not sure if people would use it :(  we should not have too many buttons, it can be confusing.

**Comment by samafshar** [comment]
Thank you. It's extremely useful for game artists. :)
