### ISSUE TITLE
Can see the file i'm working on 

### ISSUE THREAD

**Issue by zainaba194** [photopea/photopea#1147]
I am opening a file i was working on (PSD) but it wont show up on the screen.. Its opened and the layers are there but my page is blank, there isn't even a page its just blank. I tried reopening the website, even turned my laptop on and off and the same thing happens.
Please help

**Comment by photopea** [comment]
Hi, can you send me your PSD to support@photopea.com ?

**Comment by photopea** [comment]
It was fixed. Thanks!
