### ISSUE TITLE
Feature request : Select and mask

### ISSUE THREAD

**Issue by TomVivant** [photopea/photopea#1148]
Hi,

May be tricky to add, but could be good in some time to have the a "Select and mask" feature like in photoshop.

Example : https://helpx.adobe.com/photoshop/how-to/remove-replace-background.html

Thanks, Photopea is awesome !

**Comment by photopea** [comment]
Hi, this feature is called "Refine Edge" in Photopea: https://www.photopea.com/learn/refine-edge
