### ISSUE TITLE
Feature request: fast 2x click on thumbnail to change shape fill color

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1149]
I often use this function in Photoshop (where works with 2x click).
In Photopea when I double click on layer thumbnail, it's opening properties panel and I must make too much steps...

I wrote about it some time ago here https://github.com/photopea/photopea/issues/744#issuecomment-395682658

**Comment by MichalSZZ** [comment]
Double click on layer with shape should show "Color Picker" directly.
For me it is the fastest way to recolor the shapes on layer.
I can use there full color spectrum or type hexidecimal value of color.
Now in Photopea i must make more steps to do that.

https://youtu.be/wWoSQ-OAdQQ

**Comment by MichalSZZ** [comment]
Knock, knock
Hi! :)
I just want to ask how's going with that case? Is it possible to make photopea work in that way?
2x click in shape thumbnail (when use any tool) to get easy access to color edit window of that shape.

**Comment by photopea** [comment]
Hey, I am aware of this issue :) But sadly, I solve issues "from the top" - from the newest, so I can not promise when will we get to it :)

**Comment by MichalSZZ** [comment]
I understand it. Thanks for your fast reply!

**Comment by photopea** [comment]
When you make a color fill layer, it will ask you about the color before creating a layer. I hope it will decrease the need of changing the color in many cases.

**Comment by MichalSZZ** [comment]
@photopea  
This doesn't solve the problem of changing the existing shape color...
I like work with shapes, and many times I change colors of them (because i try many variant of colors). 

In Photoshop it can be done at any moment when user use any tool (e.g. when typing something by te text tool, can double click on shape layer thumbnail in layers pallete).
It temporary switch to color picker tool and show up window with Color Picker. When user acept new color, it change color of shape and switch to earlier tool. 

In Photopea to do that I must (in this example it will be simple rectangle shape):

1. click on layer thumbnail with shape
2. change tab from "live shape" to "layer" in Properties Window
3. click on "Color Fill"
4. set new color

Photoshop have better UX to do that - 2 steps less

**Comment by photopea** [comment]
You can double-click the thumbnail with a shape, and the Properties panel will show up.
