### ISSUE TITLE
Export multiple PNGs to zip

### ISSUE THREAD

**Issue by randalfien** [photopea/photopea#1152]
With a template PSD I want to be able to export multiple PNGs based on some data. Ideally the script would run and then spit out a zip file with the pngs files to be downloaded locally.

Here's my specific usecase (PSD and JSX):
[Downloads.zip](https://github.com/photopea/photopea/files/2696232/Downloads.zip)]

I have one template with different layers and textfields for a card game.
Based on JSON data, I show/hide layers and replace text in textfields and finally export the resulting image to disk.

**Comment by photopea** [comment]
We should make this script work in PP, and use a ZIP archive as a replacement for a filesystem.

**Comment by photopea** [comment]
It has been implemented! :)  After you open a PSD, you can simply drag-and-drop your JSX file into Photopea.

Note, that converting 1 MPx into PNG takes about 1 second, and your script takes about 30 seconds, but it is still much faster than Photoshop.

**Comment by randalfien** [comment]
You are literal god!
