### ISSUE TITLE
Missing CJK Font Fallback

### ISSUE THREAD

**Issue by doodlewind** [photopea/photopea#1154]
In #873 we found that although Photopea supports CJK fonts, with its embed fonts, it's not able to:

* Use CJK font to render non-CJK letters.
* Use non-CJK font to render CJK letters.

That means I can't render `你好 Photopea` with same font unless I upload a "complete font set" like Microsoft Yahei by myself, which can be confusing.

Guess this can also related to https://github.com/photopea/Typr.js/issues/26

Any idea or plan for font fallback? Thanks.

**Comment by photopea** [comment]
Currently, we have a "fallback" for missing fonts (e.g. if a character requires a Helvetica font, and it is not available, all Helvetica characters will be rendered with DejaVu Sans font).

But we do not have any Fallback for missing glyphs at the moment. I am not even sure, if it is a good idea. Let's say the user wants to write "Příští", but his current font does not have characters "řší", so those are rendered with a different font. It may look very confusing (with squares, it is clear, that characters are missing, and you should choose another font). Or he may not notice, that "řší" are a different font, and his work would look ugly.

There is a font filter in Photopea. If you enable "Latin 1" and "Chi-Jap-Kor", you should see only fonts, that support both sets of characters at the same time.

**Comment by photopea** [comment]
I will close it now.
