### ISSUE TITLE
Feature Request:Skew using mouse

### ISSUE THREAD

**Issue by shavyg2** [photopea/photopea#1155]
If when i click on the transform if i can skew using the mouse as well that would be awesome. 
Unless i can already and i just can't figure it out.

**Comment by photopea** [comment]
Hi, you can skew the image (in the Free Transform) by holding Ctrl and dragging a control points on edges (i.e. not those on the corners). It is described here: https://www.photopea.com/learn/free-transform

**Comment by shavyg2** [comment]
ok it seemed to work fine on windows, but not on my mac, is it cmd on the mac?

**Comment by photopea** [comment]
It should work for a Command key on the Mac, too.

Could you please go here: http://jsfiddle.net/p45f44zb/14/ , click into the white area and press the Command key? What do you see? You should see one of these: "MetaLeft","MetaRight","OSLeft","OSRight"
