### ISSUE TITLE
Exporting JPGs

### ISSUE THREAD

**Issue by crazykooke** [photopea/photopea#1157]

**Comment by crazykooke** [comment]
When I select a folder with 2 layers in it and then go to export as a JPG, the entire workspace gets saved in the same file including all artboards. I've done this succesfully as a .png, but those files can get very big or have problems processing depending on the platform.

Is there a trick that I'm not seeing?

**Comment by photopea** [comment]
Hi, when you press File - Export As - ... , the whole document will be exported (i.e. what you see in Photopea, except that for JPG, transparent pixels would be replaced with white). 

If you want to export just one element (a layer or a folder of layers), select it in the layers panel, switch to the Move tool (the first tool in the toolbar) and press the JPG / PNG button in the top menu.

It is all described here: https://www.photopea.com/learn/opening-saving
