### ISSUE TITLE
Dialog panel with textfield

### ISSUE THREAD

**Issue by mikelchris** [photopea/photopea#1158]
Hi, I am trying to create a dialog window but the javascript is not working

var dlg = new Window('dialog', 'Alert Box Builder', [100, 100, 400, 300]); 
dlg.show();

http://www.joshwright.com/tips/photoshop-scripting-user-interface

Is the function "new Window" possible in photopea?

Thanks!

Best,
Michael

**Comment by photopea** [comment]
Hi, Photopea does not support the full scripting standard of Adobe Photoshop yet, but I will look into it and see how hard it is :)

**Comment by photopea** [comment]
Hi, I implemented this simple function for showing a new window. However, I can not find the official manual about creating the UI with Photoshop scripts. If you find any manual and have a more advanced UI-related script, let us know! :)
