### ISSUE TITLE
Information panel

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#116]
We need information panel, which can help measuring stuff - it can show the size of the current selection, as in Adobe Photoshop.

**Comment by ArtemsWay** [comment]
Subscribe, a very necessary thing.

**Comment by landsman** [comment]
Good idea!

**Comment by photopea** [comment]
Info panel was added.
It shows the X Y coordinates of the cursor and the RGB color under the cursor.  
When there is a selection, it shows the width and the height of the selection. 
When you are editing the cropping rectangle of the Crop tool, it shows the width and the height of the cropping rectangle.
