### ISSUE TITLE
filename within autosave function

### ISSUE THREAD

**Issue by mikelchris** [photopea/photopea#1160]
Hi, after loading an image I rename the document name through script. The HTTP POST request contains the source path and the versions. Is there a way to get the actual filename during the autosave function to save it properly?
Thanks!
Best,
Michael

**Comment by photopea** [comment]
Hi, did you try to change the Document.source through the script, too? That string is used as the identifier, since file names can be the same for several opened documents.

**Comment by mikelchris** [comment]
Hi, Thanks for pointing that out. I haven't changed the Document.source. 
Now it is working.

Thanks!

------ Originalnachricht ------
Von: "Photopea" <notifications@github.com>
An: "photopea/photopea" <photopea@noreply.github.com>
Cc: "mikelchris" <m.huethig@t-online.de>; "Author" 
<author@noreply.github.com>
Gesendet: 25.12.2018 11:05:46
Betreff: Re: [photopea/photopea] filename within autosave function 
(#1160)
