### ISSUE TITLE
Memory issues and crash

### ISSUE THREAD

**Issue by flaneurette** [photopea/photopea#1161]
Happy Holidays.

When creating large file, let's say 5000 x 3000 px (like editing a scanned JPG of just about 2 MB) Photopea often crashes. Today it even took Windows down, saying that my graphic drivers crashed and got a blue screen. Only happens in Photopea, Pixlr works fine

I run Windows 7 on this machine with 4GB.

**Comment by photopea** [comment]
I will close it now.
