### ISSUE TITLE
Feature request: desktop application

### ISSUE THREAD

**Issue by Pong420** [photopea/photopea#1162]
This is really a great product.
I think it would be greater if it looks like a desktop application.

Here is some suggestion:

- Desktop PWAs
  https://developers.google.com/web/progressive-web-apps/desktop

- ElectronJS
  - [nativefier](https://github.com/jiahaog/nativefier) which is a command-line tool to easily create a desktop application for any web site

**Comment by photopea** [comment]
But I think Photopea already is a PWA. You can click More - Install Photopea. Or are you asking for anything specific?
