### ISSUE TITLE
Hundreds of "Project will be converted from CMYK to RGB mode"

### ISSUE THREAD

**Issue by guiherzog** [photopea/photopea#1163]
When I export the document to .PDF, I receive hundreds of notifications saying that the "Project will be converted from CMYK to RGB mode". 

It looks like the image below, and it keeps coming for a minute or two.
<img width="804" alt="screen shot 2018-12-26 at 18 24 03" src="https://user-images.githubusercontent.com/3836025/50452691-e159f400-093b-11e9-960e-35214b59c938.png">

Thanks for support and let me know if I can do anything else to help on solving this issue.

**Comment by photopea** [comment]
Hi, so you opened a PSD file and are exporting it as PDF? Can you send us your PSD to support@photopea.com ?

**Comment by photopea** [comment]
Hi, I fixed this error with too many messages.

Note, that Photopea can not export fonts yet. We plan to fix it. Until then, you can try enabling "rasterize fonts" or "rasterize all" in the PDF export window.
