### ISSUE TITLE
Roboto Medium font is not depicted in CSS window

### ISSUE THREAD

**Issue by yerzhant** [photopea/photopea#1167]
Hi, Medium font isn't depicted in CSS window as font-weight=500 or like.
http://joxi.ru/KAgdbv0U4L8VJr

Regards,
Y.

**Comment by photopea** [comment]
Have you tried to use this CSS in a website? I think that without any font-weight information, it should use the "default" Medium version.

**Comment by yerzhant** [comment]
Sometimes I do copy styles from the CSS window when I'm doing markup, but usually I copy-paste hex color values. As for the other information I just "visually transfer" it to style sheets. I.e. if I see font-weight=300/bold and other styles I just do (enter) the same in VS Code.

So the project I'm marking up now has missed medium font weights in a number of places, as I didn't see font-weight=500 in the CSS window. One must say, that by my eyes I felt that there's some difference between what is on the site and what is on the Photopea. And only today, I guess (or, maybe, yesterday), I have noticed that in the tool bar Protopea depicts the right font weight.

**Comment by photopea** [comment]
The PSD file only says, which TTF / OTF file has to be used to render each character (there is no information about a font weight). Photopea has a database of free fonts, so it can download the TTF file and extract the font-weight from that font file.

But if Photopea does not have a necessary TTF file, it will not be able to determine a font-weight.

**Comment by yerzhant** [comment]
Thanks for valuable information.
Do you have a Roboto Medium in your database?

пн, 31 дек. 2018 г., 0:58 Photopea notifications@github.com:

**Comment by photopea** [comment]
Hi, it was fixed. Now, Photopea shows a "font-weight: Number", according to the font weight value in a TTF / OTF file (it is 500 for Roboto Medium).

**Comment by yerzhant** [comment]
Hi, thanks a lot.
