### ISSUE TITLE
Chrome Error - Save as "psd"

### ISSUE THREAD

**Issue by mikelchris** [photopea/photopea#1169]
Hi,

I wish you a Happy New Year! :-)

I need to save the file as "psd" but in Chrome I receive the "Aw Snap!" message. Save the file to "psd:true" is working. 

Test URL's:
Save to psd
https://www.photopea.com/#{"files":["//www.photopea.com/api/img/new-1546302845.jpg"],"server":{"url":"//www.photopea.com/api/saveImage.php","formats":["psd"]}}

Save to psd:true
https://www.photopea.com/#{"files":["//www.photopea.com/api/img/new-1546302845.jpg"],"server":{"url":"//www.photopea.com/api/saveImage.php","formats":["psd:true"]}} 

Best,
Michael

**Comment by photopea** [comment]
I fixed it by doing it in a little different way.
