### ISSUE TITLE
Cannot open large psd file or pull from URL

### ISSUE THREAD

**Issue by ethernutza** [photopea/photopea#117]
I have an 88meg PSD file that I want to try edit as a sample. After selecting upload or URL the app does nothing and eventually hangs.

**Comment by photopea** [comment]
I think I know what is the problem. Photopea tries to get all the layers into the graphic memory, but in some cases, there is not enough memory available, so Photopea fails. 

I am very sorry for that. We will fix this behavior in the future.

**Comment by photopea** [comment]
By the way, can you send us your file to support@photopea.com, so we can check, if the graphic memory is the real problem? There could be some other bug.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
