### ISSUE TITLE
Eyedropper Tool Not Working

### ISSUE THREAD

**Issue by GoMifune** [photopea/photopea#1170]
I attempted to use the eyedropper tool and when I clicked on it, it was not selected.

**Comment by photopea** [comment]
Hi, I just tried to click on Eyedropper tool in the toolbar and it was selected (highlighted). Could you be more precise, how did you do it?

**Comment by GoMifune** [comment]
> Hi, I just tried to click on Eyedropper tool in the toolbar and it was selected (highlighted). Could you be more precise, how did you do it?

Sorry about that, looks like it works fine. I'm not sure what I was doing wrong previously.

**Comment by photopea** [comment]
ok no problem :) We always need to reproduce the bug ourselves, to be able to fix it.
