### ISSUE TITLE
brightness layer

### ISSUE THREAD

**Issue by sarahbeth710** [photopea/photopea#1172]
happy new year!

when I go to change the brightness, it adds a white layer on top and then that's the only thing that changes, not the actual picture itself. hope that makes sense!

**Comment by sarahbeth710** [comment]
so if this is the original picture
![image](https://user-images.githubusercontent.com/45085646/50621139-f9002200-0ed1-11e9-9414-11bdad4b756d.png)

with the brightness up it looks like this
![screenshot 2019-01-02 at 9 05 01 pm](https://user-images.githubusercontent.com/45085646/50621159-17feb400-0ed2-11e9-8145-cb6ea21f9b6d.png)

maybe it's always been like that, but it just seems like it's doing something different now

**Comment by photopea** [comment]
Do you have an example of how do you want it to look like? Note, that there is the "Old Way" checkbox at the bottom, which will give a different result.

**Comment by sarahbeth710** [comment]
i think it's adjusting the contrast at the same time, since when i make them both the same number it looks closer to what it used to

**Comment by sarahbeth710** [comment]
so i end up with this which is what i'm looking for
![screenshot 2019-01-02 at 9 15 29 pm](https://user-images.githubusercontent.com/45085646/50621386-927c0380-0ed3-11e9-9286-9e8188ec09f6.png)

**Comment by photopea** [comment]
I don't see how can I help you :( Photopea always worked this way. In your last photo, dark colors became even darker, which is impossible to do only by increasing Brightness.
