### ISSUE TITLE
Long-touch as a right button

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#1174]
The right mouse button is not possible on touchscreen-only devices. If the touch is long (without moving), we could interpret it as a right-click. It could be used in:

- Move tool (to select layers beneath)
- Layers panel (to show a context panel)

**Comment by bgobler** [comment]
Or in the layers panel, long touch could be used to move a layer around in the order. As of now, I don't think the layers can be rearranged on touchscreen.

**Comment by photopea** [comment]
It has been implemented. Also, you can zoom with two fingers.
