### ISSUE TITLE
Buggy text tool in mobile browsers

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#1176]
On safari iphone/ipad with latest ios, after a new font loaded, the text typed out are invisible, sometimes even the first font loaded produce invisible text.

In firefox ios, it seems only the default font is ok, and only the first several character for a given layer is ok, an additional character can toggle the visibility of that text layer.

On androids 8: (the latest supported)

Change font size with dragging not working in samsung internet browser, chrome, edge, only firefox ok

Font size will set to 1 after put down text cursor   in samsung internet browser, chrome, edge, only firefox ok

Invisible text, here I found this is somewhat font specific, samsung internet browser cannot display noto, pt sans, chrome cannot display noto, lato and pt sans, edge cannot display pt sans, only firefox displayed the fonts I tried properly

**Comment by photopea** [comment]
Hi, I tested Photopea on Android 6 in Chrome. Everything works correct.

Sadly, I don't have Android 8 to test it :( Could you maybe make a video of it and report it as a bug to Chrome developers?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
