### ISSUE TITLE
Bicubic Interpolation

### ISSUE THREAD

**Issue by spooknik** [photopea/photopea#1177]
Hello, just a suggestion to add bicubic interpolation when resizing images. It can yield better results in some cases with upscaling.

**Comment by spooknik** [comment]
It does take more time to compute, but personally I don't mind waiting. In my experience even upscaling (1.5 times) photos with Bicubic produces sharper and crisper results. I'm not saying it should be the default, but for those who want the improved quality, it would be nice. 

In images with small details (like the plastic grain), Bicubic does a better job.  

Upscaled 150%:
Bilinear 
![bilinear](https://user-images.githubusercontent.com/40317809/51026108-1302ca00-158e-11e9-970f-bc155cd1330f.jpg)

Bicubic
![bicubic](https://user-images.githubusercontent.com/40317809/51026113-15fdba80-158e-11e9-8404-55a136774afa.jpg)

Source
![source](https://user-images.githubusercontent.com/40317809/51025881-76402c80-158d-11e9-9c9f-3f4194e814eb.jpg)

The same is also true with downscaling. Bicubic produces better result. 

Downscaled 25%
Bilinear
![bilinear_25](https://user-images.githubusercontent.com/40317809/51026433-cb307280-158e-11e9-9d6f-1dc469e67fd2.jpg)

Bicubic
![bicubic_25](https://user-images.githubusercontent.com/40317809/51026444-d1beea00-158e-11e9-9127-62b6429f97b7.jpg)

**Comment by photopea** [comment]
Interesting, Bicubic version does look a lot sharper. BTW. do you understand the interpolation mechanism? Do you know, what downscaling with bilinear / bicubic means? I always thought, that interpolation only make sense for upscaling.

**Comment by spooknik** [comment]
I must admit my knowledge is only surface level. But I do understand that some interpolation can take place when downscaling that can make better results. For example Photoshop has [Resampling options ](https://helpx.adobe.com/photoshop/using/resizing-image.html#Resampling%20options%20|%20Photoshop%20CC) like Bicubic Sharper (for reduction) and Bicubic Smoother (for enlargements). [This article](http://entropymine.com/resamplescope/notes/photoshop/) might give some insight into how they work. I used Krita to downscale the examples above and it only has 'Bicubic'. Sorry I can't be of more help :/

**Comment by rocifier** [comment]
This is slightly surprising to me. Usually bicubic interpolation is smoother (less sharp), and traditionally that's what it has been used for. @spooknik are your example pictures created using the newer "bicubic sharper" in photoshop?

**Comment by spooknik** [comment]
I did not use Photoshop for the examples posted above. I used Krita and it only has one option called, 'bicubic' (weather or not you upscale or downscale). It could it's just doing something similar to bicubic sharper then in Photoshop.

**Comment by photopea** [comment]
I think the possible difference between PS and PP is not because of Bicubic interpolation. You should be able to get the same result, if you apply a Sharpen filter after resizing.
