### ISSUE TITLE
Some ideas for Photopea Brackets plugin to be realese in future.

### ISSUE THREAD

**Issue by LipaGre** [photopea/photopea#118]
![photopea](https://cloud.githubusercontent.com/assets/23517531/21236273/719c743a-c30b-11e6-92b8-ec8cfe162f1d.png)

**Comment by photopea** [comment]
Hi, do you mean copying the name of the layer as a text and copying the image as an image file? That is a nice idea! I think that I should examine a clipboard API for web. Then, it will be possible to copy-paste a text or an image not only inside a browser, but between any two apps, e.g. Photopea and Gimp, or Photopea and Notepad. I will take a look at it in the future.

By the way, I am really surprised, that PP works in Brackets. I was complaining about it here: https://github.com/adobe/brackets/issues/12902  , it looks like they have fixed it without letting me know. But your greenish look is still incorrect, so they have to fix it better.

**Comment by photopea** [comment]
1. The layer name can be copied by double-clicking it and pressing Ctrl + C, then pasting it wherever you want.
2. Layer can be quickly exported to a PNG file by the "Get PNG" button (of the Move tool).
