### ISSUE TITLE
Unable to open .eps

### ISSUE THREAD

**Issue by luidjivampa** [photopea/photopea#1183]
Unable to open 2,9 mb file in EPS format.

**Comment by photopea** [comment]
Hi, can you send it to support@photopea.com ?

**Comment by photopea** [comment]
Hi, your EPS seems to be quite complex, for us to be able to track down an error. It could take us weeks :(

EPS format should not be used nowadays. Please, use an online tool like this: https://convertio.co/eps-pdf/  to convert your EPS to PDF. If Photopea crashes while opening your PDF, try to disable WebGL before opening (More - Use WebGL).
