### ISSUE TITLE
Enhanced Grid? - Feature Request

### ISSUE THREAD

**Issue by GregoryTheGamer** [photopea/photopea#1184]
Would you guys be able to enhance the grid by allowing specific height and length values? (for example: 128 px by 64 px) That would make doing certain things much easier. Thanks!

**Comment by photopea** [comment]
Hi!  We just added new feature: You can use Percent as grid units (e.g. grid gap 25% will create four equal "vertical slices" and four equal "horizontal slices".

I think that having two different grid gaps (vertical and horizontal) would look too complex. Have you tried using guides? Try View - Add Guide.

Also note, that the grid is displayed the same for all documents, while you can have different guides in each document.
