### ISSUE TITLE
Shape Tools mirroring and fixed ratio/size

### ISSUE THREAD

**Issue by enjamb-ment** [photopea/photopea#1185]
When using the shape tools, the point of origination acts odd for line and parametric shapes. It seems like the drawn shape is not mirrored over the axis correctly for quadrants I and III.  

![new project](https://user-images.githubusercontent.com/46714924/51184765-e0f9ac80-189a-11e9-8028-71f764a1a088.jpg)

Also, when setting shape tools from free to fixed ratio/size for rectangle, ellipse, and custom shape, the shape doesn't allow movement on the +y or -x axes, where this used to be place anywhere and drag. Also, scaling a fixed ratio shape produces a similar mirroring effect above.

edit- clarified fixed ratio/size issues.

**Comment by photopea** [comment]
I am very sorry for this. I just fixed it.
