### ISSUE TITLE
Critical BUG> Photopea is not rendering properly

### ISSUE THREAD

**Issue by francescortiz** [photopea/photopea#1187]
After a few seconds of operation the image and the layers stop getting updated. It happens both in firefox and chrome. If I click any tool on the toolbox or if I hit the shortcut key the canvas gets repainted, but not does the layers panel. If I resize the window the layers panel gets rendering glitches (a piece of the bitmap associated with the panel gets repeated all along the panel height.

The only option is to restart it every minute.

**Comment by photopea** [comment]
Hi, I can not reproduce it :(  Could you please tell me exactly, how to make this bug happen?

**Comment by francescortiz** [comment]
I just have to let a few seconds pass, nothing else. On opera is not happening for now. If it only happens to me then don't worry and I will come back if I cannot find a solution, or if I do find a way to fix it. But as long as it looks random and I am the only one affected there doesn't seem to be much to do.

**Comment by photopea** [comment]
Are you using a Beta release of a browser? Try to update your browser, or OS, or GPU drivers (we used to have simiar glitches with Photopea on old versions of Mac OS on some macbooks).
