### ISSUE TITLE
Support limited palette (non-24bit) images

### ISSUE THREAD

**Issue by rcoenen** [photopea/photopea#1188]
I'd love to see support for non-24 bit images. Quite often I work with limited palette images. unlike Photoshop, Photopea can only deal with full 8-bit-per-channel (24 bits) images.

**Comment by photopea** [comment]
Hi! Are you talking about opening a paletted PSD images in Photopea? What is the purpose of a palette in your case?

Currently, if you export images to PNG or GIF and decrease the quality, Photopea will save it as a paletted image, which can be 4x smaller than a regular version, while looking almost exactly the same.

**Comment by rcoenen** [comment]
I use Photoshop for pixel art, where I can control the palette and modify pixel by pixel. This is quite different from generating a palette image based on 24 bit input.

**Comment by rcoenen** [comment]
Basically a "mode" menu is missing to choose between
bitmap/gray-scale/duo-tone/indexed color/RGB Color. Currently Photopea
basically only supports RGB Color mode if I'm not mistaken? See screenshot

**Comment by photopea** [comment]
Yes, there is only "RGB mode" in Photopea. (btw. we can not see your attachment, when you reply through an email)

In Photoshop, when you have an Indexed mode, you can have only one layer. Also, the Brush tools can not have hardness, and if you pick a color in a color picker, it usually draws with a different color.

I don't think it is useful to offer more modes the way they work in Photoshop. But maybe we could add other features, which will help you do what you need (in a different way, than in Photoshop).

**Comment by photopea** [comment]
I am closing it. I don't think it is a useful feature, and it can be achieved otherwise.
