### ISSUE TITLE
How do I move a path anchor?

### ISSUE THREAD

**Issue by QuantumInformation** [photopea/photopea#1189]
How do I move a path anchor on the mac on chrome, like this one:

![image](https://user-images.githubusercontent.com/216566/51432746-0d1b8180-1c3d-11e9-820a-a6d1031a269d.png)

**Comment by photopea** [comment]
Hi, you should be able to move it with a Direct Select tool (press A to switch between Path Select and Direct Select tools).

**Comment by QuantumInformation** [comment]
Great thanks

**Comment by photopea** [comment]
I recommend you to read https://www.photopea.com/learn/vg-manipulation
