### ISSUE TITLE
Cannot vectorize this little picture

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1190]
I cannot vectorize this picture. Is because is so tiny?
![layer 41](https://user-images.githubusercontent.com/11801254/51434798-9e8ff100-1c47-11e9-8eaf-a6ca38265983.png)

![image](https://user-images.githubusercontent.com/11801254/51434801-b6677500-1c47-11e9-9512-4577c8f11556.png)

Neither could with the bigger one :/
![image](https://user-images.githubusercontent.com/11801254/51434810-08a89600-1c48-11e9-9635-ec112374dbf9.png)

**Comment by photopea** [comment]
Hi, the Vectorize tool works well only with images with solid-color surfaces. Your image contains too much noise and gradients. Photopea throws away every vector shape, if its area is smaller than 4 square pixels.

Try to do Filter-Blur-Surface Blur with values 5, 90 and then vectorize: https://imgur.com/n1zJc64  Otherwise, I doubt any tool would be able to do better :(

**Comment by photopea** [comment]
Would you like this result: https://i.imgur.com/y5ughp1.png ?

**Comment by avagp** [comment]
Yes, but i don't like the white between the yellow and pink.
![image](https://user-images.githubusercontent.com/11801254/51439555-10455a80-1c9b-11e9-8c79-4c12b8a2af4a.png)

**Comment by avagp** [comment]
Have you tried this tool?
https://www.vectorizer.io

Similar quality results as Vector Magic
![image](https://user-images.githubusercontent.com/11801254/51439665-4800d200-1c9c-11e9-8dd6-cbbbcaf6e00b.png)

**Comment by photopea** [comment]
Do you really like that vectorizer.io output? It has over 5000 paths and probably about 100 000 control points. The SVG is 10x larger, than the original PNG. Isn't it better to keep it in PNG?

**Comment by photopea** [comment]
I thought, you want the "center of the flower" and petal leaves to have a solid color (remove stripes).

**Comment by avagp** [comment]
You are right Ivan. I wanted exactly what you thought.

The file from vectorizer is unusable.
