### ISSUE TITLE
Function "App.open(url, as, asSmart)" - Place image into active document

### ISSUE THREAD

**Issue by mikelchris** [photopea/photopea#1191]
Hi,
is it possible to place an image through script into the active document?

In your documentation I found the function "App.open(url, as, asSmart)". But this function always creates a new document - wnd.postMessage('app.open("test.jpg",false)', "*").

In addition I would like to place the image as rasterized. I am setting "asSmart" to false but it is still get placed as smart object.

Thanks!

Best,
Michael

**Comment by photopea** [comment]
Hi. asSmart==false will open your document separately, and asSmart==true will put it into a current document as a smart object.

I just implemented the Layer.rasterize() function, which will rasterize any layer. Note, that you have to call it in a next script, after the image is loaded and placed.
