### ISSUE TITLE
Feature request: Allow us to move the page by holding the mouse wheel 

### ISSUE THREAD

**Issue by dvx17** [photopea/photopea#1192]

**Comment by photopea** [comment]
Hi, I have never seen this feature in any other program. I am not sure, if anybody will discover it.

Note, that now, you can "move vertically" by turning a mouse wheel, or horizontally by holding Ctrl + wheel.

You can also move the page when you hold spacebar (it quickly switches to a Hand tool, and then to the previous tool, after you release the Spacebar).

I think such options should be sufficient.

**Comment by dvx17** [comment]
it has been discovered in gimp and i think it's an amazing tool, also the hand tool does not work for me, neither making a selection with the pen tool. i have attached an image of me trying to fill the path that i made with the bucket tool and this message keeps happening. i try rasterizing it but it removes my nodes plzzz fix this glitch or whatever it is!

![](https://cdn.discordapp.com/attachments/502021446718193684/537388398705639425/unknown.png)

**Comment by photopea** [comment]
Hi, at your screenshot, you are zoomed out, so moving the page is not possible (Moving is possible only when the document does not fit into the workspace).

Only Selections can be filled, not Paths. Photopea works differently than GIMP. Please, keep using Gimp, or learn Photopea at www.Photopea.com/learn

**Comment by dvx17** [comment]
yup i am going to stick to gimp, much better and needs less work
