### ISSUE TITLE
Feature Request: Layer Selection

### ISSUE THREAD

**Issue by dvx17** [photopea/photopea#1193]
Sorry but i am using other Photopea competitors, such as GIMP due to the fact i can't make a selection out of an layer. unlike in gimp they have a feature that is is called "Alpha to Selection" and what this feature let's us do is, make a layer  selection, unlike Photopea all you can do is select everything that's on the Canvas. Which i really hate, and other Photopea users might also dislike it.

@photopea

**Comment by photopea** [comment]
Hi, this feature has been available in Photopea for many years. You have to hold Ctrl and click on the thumbnail of the layer (in Layers panel). It is described in the second paragraph here: https://www.photopea.com/learn/creating-selections
