### ISSUE TITLE
Lasso Tool and Losing Progress

### ISSUE THREAD

**Issue by Morgan2905** [photopea/photopea#1194]
I have been having trouble with the lasso tool. When I use it for the first time on an art piece I can not use any of my tools unless the area is selected. It gets super annoying. 

My second problem is losing progress. My internet at home is strong too. I work on an art piece for multiple hours, I go to a different tab then return back to photopea and all my work is gone! This has happened to me many times. Please fix this.

**Comment by photopea** [comment]
Hi. What exactly is the problem with a Lasso tool? What other tools you can not use? I can switch from a Lasso tool to any other tool, without making a selection.

Your browser "deletes" Photopea for some reason. I think you don't have enough RAM memory, and your computer tries to free memory by "killing" unused programs.

Please, buy more RAM memory, or try another web browser. If it does not help, you have to save your work as PSD from time to time.
