### ISSUE TITLE
Swatches palette - show as list with names

### ISSUE THREAD

**Issue by mikelchris** [photopea/photopea#1195]
Hi,
Is it possible to show the swatches as list with names. This function would be very helpful. Currently it is "only" possible to show the swatches as thumbnails.
Is it possible to load swatches through the resources parameter of the api - similar to fonts?

Thanks!

Best,
Michael

**Comment by photopea** [comment]
Hi, you can see color name in a bubble, if you hover over the thumbnail with your mouse. Isn't it sufficient?

You can load ".ACO" swatches into Photopea through the API, similar to fonts.

**Comment by mikelchris** [comment]
Hi, Your program is getting used for the creation of social media images. Depending on the promoted product it is necessary to colorize elements in a secondary and a primary color. The names of the swatches starts with the product name to make the selection easier. 
Within a list it is much easier to select specific colors. 
The mouse over tool tips are useful but it takes too long to find the right color when I am having a palette with many colors.

**Comment by photopea** [comment]
It has been implemented! :)
