### ISSUE TITLE
Possible Chrome 72 Problem

### ISSUE THREAD

**Issue by ratickle** [photopea/photopea#1197]
When using Chrome 72 on a Samsung Chromebook Pro, the Erase Tool cursor is not visible on white backgrounds.  When I tried it on a Windows machine running Chrome 71, the Erase Tool cursor displays as a black circle on white backgrounds.

**Comment by photopea** [comment]
Hi, could you tell us your Device Pixel Ratio? You can see it here: https://johankj.github.io/devicePixelRatio/

Do you see the brush cursor on other than white background? Could you take a short video of what you see?

**Comment by photopea** [comment]
This is a bug in a web browser, which I can not "fix" at Photopea side. Usually, I try to get as much information from the user as possible, before I report it to browser makers.

I just noticed, that Chrome OS 72 is Beta. I am 99% sure, that it will work fine in a stable release. But if you still want to learn what is happening, discuss it with authors of Chrome.

**Comment by ratickle** [comment]
My Pixel Ratio is 1.60000...      Screen is 2400 x 1600

I do NOT see the brush cursor on ANY background.

**Comment by ratickle** [comment]
Just switch my Chromebook back to Stable Chrome 71.

Same non-visible cursor problem still occuring.

**Comment by ratickle** [comment]
Correction:   On Chrome 72, I do NOT see the brush cursor on ANY background.
                     On Chrome 71, I do NOT see the brush cursor on WHITE
backgrounds.

**Comment by photopea** [comment]
Do you have a page zoom? Can you try to reset it to 100%?
