### ISSUE TITLE
Slider (like in Blur Filter) broken visually in Edge

### ISSUE THREAD

**Issue by cthedot** [photopea/photopea#12]
Slider control (seen in Filter/Blur) looks empy with no slider control knob visible but on click actually does work. Simply removing CSS height: 0.1em does make it workable. Guess best would be to style input type range (as most inputs) not at all but simply use browsers default rendering?

**Comment by photopea** [comment]
Hi, it is really sad to hear, that the same CSS is rendered differently in some browsers, in 2016.

I tried to install Edge, but it requires Win 10 OS. It seems like Microsoft is limiting support on purpose, which is really strange, while the other browsers try to reach as much environments as possible.

I disabled the height: 0.1em. Does it work now?

**Comment by cthedot** [comment]
Only checked on phone yet, looks okayish ( did not check that out before on phone though so don't know if actually better;). Will test tomorrow, thanks for quick answer ☺ 

You should be able to test on remote azure https://dev.windows.com/en-us/microsoft-edge/tools/remote (or search for test edge on osx or linux).

**Comment by cthedot** [comment]
I think esp input type range is so different on every browser and platform it is best not to style that at all. And as edge is the newest browser and win10 only all tutorials to try do style it anyway are out of date. I think the shadow looked really strange too. 

What os are you working on btw?

And yes, would be better if edge be on more platforms but at least currently seems more like what safari is for mac or ios

**Comment by cthedot** [comment]
Following are 2 screenshots of Edge with -webkit-appearance: none set or not (Edge uses most webkit-prefixes(!)):

![appearance-none](https://cloud.githubusercontent.com/assets/964436/14059577/a6904626-f345-11e5-89a4-ce844841274f.PNG)
![appearance-normal](https://cloud.githubusercontent.com/assets/964436/14059576/a68e7486-f345-11e5-9739-0d0f5b255e34.PNG)

Guess if you really like to style the range input try something like http://brennaobrien.com/blog/2014/05/style-input-type-range-in-every-browser.html
, seems one of the better articles on styling a range input.

**Comment by photopea** [comment]
I am using latest Chrome and Windows 7.

I would like to avoid -webkit and -moz prefixes completely, but these features are not yet supported in browsers without prefix. I would like to disable all styling of range input, but Chrome has gray background of range, so it merges with a gray background.

**Comment by cthedot** [comment]
Yes, as all inputs range seems even more complex with what is stylable. IE/Edge can even style the left hand side of selected value different (above blue) so guess will take ages if ever that this will be resolved. 

For the Chrome gray issue: TBH I find the UI of (the btw great webapp!) a bit dull and gray anyway. Looks more like Photoshop 3.0 than the current ones. Maybe make it a bit more "modern" (sorry, hope no offense) and maybe background could be white or even use a dark mode (latest Photoshop actually uses that too) so the gray slider on Chrome would not be an issue? Just a thought.

Also I noticed you tried hard to align range (position and margin) ;)
Would `vertical-align: middle` not work?

**Comment by photopea** [comment]
Thanks for vertical-align :) I somehow forgot, that it exists :)  I have removed all CSS of range input, so the default look should be displayed. I inserted the input into auxiliary <span> with a gray background.

**Comment by cthedot** [comment]
looks good, thanks!
