### ISSUE TITLE
No JPG download button when Move Tool active

### ISSUE THREAD

**Issue by yerzhant** [photopea/photopea#1202]
Hi,

there's no JPG button. Only PNG and SVG:
http://joxi.ru/EA4jJ71UwWpYWm

Though here https://github.com/photopea/photopea/issues/1157#issuecomment-449060684 it is said:
"...press the JPG / PNG button in the top menu".

Regards,
Y.

**Comment by photopea** [comment]
I am sorry for that. I thought, that there wer too many buttons, so I deleted the JPG.

Why exactly you need JPG  and don't use PNG? JPG does not support transparency. If you want to export a large photo, use File - Export As - JPG.

**Comment by yerzhant** [comment]
Sorry for late response.

I need it when there's no need for a transparency. And, as we know, JPG is more compact (when compression is applied, as it usually is), from size perspective compared to the PNG, resulting in faster site download (opening).

**Comment by yerzhant** [comment]
Ok, thanks a lot for the info.
