### ISSUE TITLE
I used the magic wand to remove some text and now I can't remove the selection

### ISSUE THREAD

**Issue by SMills64** [photopea/photopea#1203]
I'm having a really frustrating problem with trying to replace old text on a newspaper. 
I used the magic wand to select the text, then cleared it before "fill - content specific" which all works fine, but the pixels from the wand selection remain. 
I can't do anything to get rid of them, I've tried selecting/deselecting, using the wand with Alt to deselect and restarting the project. 
When I export I get the pixels on the .jpeg. 

Can anyone help?

![untitled](https://user-images.githubusercontent.com/47001256/51685119-ee770b00-1fed-11e9-8757-725f921d4207.jpg)

**Comment by photopea** [comment]
press Ctrl+D

**Comment by SMills64** [comment]
Thanks, I tried that and it didn't work, I have been able to remove it through the spot healing tool though.
