### ISSUE TITLE
Ability to edit color name in swatches panel

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1205]
Now I can only add the new color without a name of it.
It will be great to have ability to add new color name (2x click on a color row) when "list view" is on.
Or maybe by default adding new color to swatches panel with his default hex name? E.g. #E20000 and after that I can double click on name to change, or not, if I dont want to do this.

In my corporation we have many brands who have diferent company colors.

**Comment by photopea** [comment]
Hi, I added such option. It is possible by right-clicking any item and pressing Name Change. 

Note, that all this (renaming, deleting, Thumbnail/List view) is available not only for Swatches, but also for Brushes, Gradients, Contours, Layer styles, Patterns and Custom shapes.
