### ISSUE TITLE
Deleting some part of shape with backspace button

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1206]
Now when I try to select some paths on shape layer and delete it with backspace, layer is deleted.
It should clear only selected paths and leave layer with shapes not selected before.

<img width="504" alt="obraz" src="https://user-images.githubusercontent.com/38118273/51793592-153a6a80-21c3-11e9-8f4c-7bda239ce5b4.png">

**Comment by photopea** [comment]
I fixed it! Originally, only the Delete key worked like this, so I added the same functionality to the Backspace.

**Comment by MichalSZZ** [comment]
Hehe - currently I work on my laptop and dont have Delete button :D

Thank you so much!

Can I add more issues about shapes in Photopea? Or that (working with paths/shapes) is not your priority at that moment?

**Comment by photopea** [comment]
Sure, add more!
