### ISSUE TITLE
Merge shape components

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1207]
Now I can make very complicated shape in Photopea (by using unite, subtract etc.), but when I finally get what I want on that layer, I have many path and unnecessery knots.

In Photoshop I have option "Marge shape components" to simplify the shape.

Before
<img width="355" alt="obraz" src="https://user-images.githubusercontent.com/38118273/51793803-c098ee80-21c6-11e9-8b19-a39514b7383a.png">
After
<img width="355" alt="obraz" src="https://user-images.githubusercontent.com/38118273/51793811-e625f800-21c6-11e9-8fb6-5420e849b20d.png">

**Comment by photopea** [comment]
It was implemented!  Actually, this feature has been present in Photopea for a long time (to be used when saving as SVG, since SVG does not have any Subtract / Intersect modes). So I added it into the top menu (in a drop-down for Fill rules).

**Comment by MichalSZZ** [comment]
Wow. You implemented that faster than time what I spended to wrote the Issue :D
