### ISSUE TITLE
Deleting knots with Backspace button

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1208]
Same thing like in #1206 but with knots of path

Now I read https://www.photopea.com/learn/vg-manipulation to know what is implemented now and all issues on Github with paths/shapes to make sure I dont make duplicate :)

**Comment by photopea** [comment]
Hi, I made Backspace key equivalent to the Delete key for Direct Select tool, Magnetic Lasso tool (for deleting endpoints) and Gradient Editor (for deleting a selected color stop).
