### ISSUE TITLE
"Error in photoshop file: Wrong Signature" when editing smart objects

### ISSUE THREAD

**Issue by geraldlnj** [photopea/photopea#1209]
I tried opening a PSD file that I created, and it opens, but when I try to edit smart objects it gives me "Error in photoshop file: Wrong Signature".
Creating a new smart object in Photopea works, and I can edit them.

Using Adobe Photoshop CC 20.0.2 20181219.r.30.

[I've attached a test PSD for you.](https://github.com/photopea/photopea/files/2800203/test.zip)

**Comment by photopea** [comment]
Hi, I fixed it, thanks for reporting it! :)  Send more such files, if you find any other problem.

BTW. it is cute, how 1 MB PSD converts into a 7 kB ZIP fille :)
