### ISSUE TITLE
Selection width and height

### ISSUE THREAD

**Issue by ianldgs** [photopea/photopea#121]
https://pixlr.com/editor/ has this "navigator" panel, that has the width and height of the current selection.

![image](https://cloud.githubusercontent.com/assets/6526498/21693310/9506b1c6-d367-11e6-94ed-2401795dfd4d.png)

this is often usefull to discover dimensions of elements

**Comment by photopea** [comment]
Hi, we are going to add Information panel, which will have this information. So I will close this issue and keep the original issue open https://github.com/photopea/photopea/issues/116
