### ISSUE TITLE
Please add a Facebook Group Header Image Size in the Template

### ISSUE THREAD

**Issue by sonamdawa101** [photopea/photopea#1211]
Kindly add a **facebook group header image size** in the template section when creating a new file in Photopea.

**Comment by photopea** [comment]
Hi, what is "Facebook Group Header Image Size"? I tried to search it, but I found many different sizes in articles from different years. Do you have any official manual from Facebook about image sizes?

**Comment by MichalSZZ** [comment]
Hi, I'm trying to help in this topic...
I have found this size: 1640x856 (or ratio 1,91:1) 
via https://www.facebook.com/help/212144952271305

**Comment by sonamdawa101** [comment]
I tried various sources with valid info through the net. And here I made a illustration of the Facebook Group Cover Image Size with Visible Area. Please correct I am wrong
![facebook group cover image size](https://user-images.githubusercontent.com/36448436/52107906-3addce80-261e-11e9-97e7-74b2a16f8c27.png)

**Comment by sonamdawa101** [comment]
MichalSZZ you are right !

**Comment by photopea** [comment]
Ok I added it. Hope they will not change it next week :)

**Comment by sonamdawa101** [comment]
hhhhh 🥇
