### ISSUE TITLE
25MB+ Sketch files never import

### ISSUE THREAD

**Issue by FlamboyantN** [photopea/photopea#1214]
When importing Sketch files that are 25MB+, the program shows 'Loading' but it never completes - even after hours elapsed. 
Would really appreciated a quick fix!

**Comment by photopea** [comment]
Hi, could you send us your Sketch file to support@photopea.com , so we take a look at what is happening?

**Comment by photopea** [comment]
Hi, I am sorry for the delay, I was fixing another issue. 

In your Sketch file, there is a Shape Group, which contains a text layer. I don't know what would be an analogy of it in PSD :( So Photopea just skips such layer for now. You can open your Sketch file in Photopea now.

**Comment by photopea** [comment]
It occurs multiple times in your file. E.g. it is the shape group with ID AF1FFA4B-0776-418D-A4B1-ED8EAFF5D1A3.

All such shape groups have a name "Combined Shape" and contain one Oval and one Text.

**Comment by FlamboyantN** [comment]
Lovely - thank you very much!
