### ISSUE TITLE
Brush cursor

### ISSUE THREAD

**Issue by JeSuisJe** [photopea/photopea#1216]
There isn't any brush cursor. There is just the normal cursor, but not the circel that shows the size of the brush. I do remember it being in Photopea, but it just dissapeared.

**Comment by photopea** [comment]
Hi, can you update your web browser?

**Comment by emiel877** [comment]
I'm on the newest version of Chrome OS
(71.0.3578.127)

**Comment by photopea** [comment]
Can you see cursors in this demo? http://www.ivank.net/veci/cursors.html . Can you try Photopea in anonymous window?

**Comment by JeSuisJe** [comment]
The first 3 are working, but the last two (256x256px and 512x512px) are not.

**Comment by JeSuisJe** [comment]
Also not working in incognito

**Comment by photopea** [comment]
So brushes work in Photopea in Incognito?

**Comment by JeSuisJe** [comment]
No

**Comment by photopea** [comment]
Do you have your page zoom at 100 % ?

**Comment by JeSuisJe** [comment]
i had it on 80% but i changed it and nothing happened

**Comment by photopea** [comment]
Can you reload Photopea after you switch to 100%?

**Comment by JeSuisJe** [comment]
still doesn't work

**Comment by photopea** [comment]
And what number you see here? https://johankj.github.io/devicePixelRatio/

**Comment by JeSuisJe** [comment]
0.8999999761581421

**Comment by photopea** [comment]
Could you go here and move your mouse over the text in the white area? Do you see a cursor? https://jsfiddle.net/da5q3nj1/

**Comment by JeSuisJe** [comment]
Yes i see a cursor

**Comment by MichalSZZ** [comment]
I have the same (I think) problem. Cursor is dissapear after e.g. size changing (sometimes it's blinking)

> And do you see cursors here? http://www.ivank.net/veci/cursors_dpr.html

Only for a while appear

Look here https://www.youtube.com/watch?v=BdBCJopXAfY

Mac OS (High Sierra), newest FF and Chrome
My friend from work with macbook like mine (only newest OS) have no problem.

**Comment by photopea** [comment]
@JeSuisJe Can you try the cursor here: https://jsfiddle.net/gftL58u9/ ? Do you see any cursor?

@MichalSZZ I think your problem is not related to this. Could you try to update your Mac OS?

**Comment by JeSuisJe** [comment]
For me its diffrent than the video, The websites work perfectly but in Photopea it doesn't show at all.

**Comment by photopea** [comment]
I would like to fix all cursor-related issues by hiding the mouse cursor completely, and moving a PNG image along the mouse movement. Mainly because current browsers don't let us use cursors larger than 128x128 pixels.

**Comment by photopea** [comment]
It should be fixed now. Custom cursors (mainly for Brushes) should work well in all browsers. There is no limit to a cursor size (it can be huge).

**Comment by MichalSZZ** [comment]
WOW. Thank you @photopea 
Is there any cons in that method of cursor showing?

I asking becouse in my #735 issue, that can be a solution of problem.

**Comment by photopea** [comment]
These new cursors usually have a 0.02 second delay in comparison with where your real mouse is (and the delay can be even bigger, it is hard to predict). Also, when Photopea is stuck at computing, these cursors don't move, until the computing finishes.

**Comment by Valeria011345** [comment]
Hello, When I use the brush it paints above the cursor and I don't know what I have to do to fix it.
Greetings and thank you.
[Uploading Screen recording 2023-12-13 16.23.00.webm…]()

**Comment by Valeria011345** [comment]
Tell me in the settings what to put

**Comment by photopea** [comment]
Press Edit - Preferences, set Mouse Offset to zero.

**Comment by Valeria011345** [comment]
thank you very much, it was for a project from my institute

**Comment by burnsboyamazing** [comment]
Stuck on uploading attachment for .webm, fixing the stuck upload for .webm in Github. See screenshot, to fix the stuck upload for .webm later.
![Screenshot 2024-02-10 3 34 33 PM](https://github.com/photopea/photopea/assets/154830140/3911427d-9eda-42f7-bc33-7791b3a213df)

**Comment by photopea** [comment]
Hi, I am confused, do you have any problem with www.photopea.com?
