### ISSUE TITLE
Do not see "Accept" button in Terms of Service

### ISSUE THREAD

**Issue by matthewwayneconnors** [photopea/photopea#1217]
Hello,

I'm trying to pay for a single user license, but when I open the Terms of Service, I cannot see an "Accept" or "Submit" button anywhere. I have tried scrolling to the bottom. Tried several times.

I am using Chrome OS on a Chromebook.

m@

**Comment by photopea** [comment]
Hi, the Checkbox is right under the table with Buy buttons :)
