### ISSUE TITLE
Converting a smooth point to a corner point in path

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1218]
Now I can't see this functionality in Photopea...

Photoshop have one more tool to do that - "Convert Point Tool".
When I have smooth knot, I can change it to corner point by clicking it with this tool.

In Photoshop I can modify one part of knot separatly with Alt button (when dragging end of existing direction lines with Alt ). Or I can draw path with custom direction line when use Alt button.

Now I think it is immpossible in Photopea.

See more about converting here https://helpx.adobe.com/photoshop/using/editing-paths.html#convert_between_smooth_points_and_corner_points

**Comment by photopea** [comment]
Hi, you can convert the knot between linked and unlinked (smooth and corner) by double-clicking the anchor, see here: https://www.photopea.com/learn/vg-manipulation
