### ISSUE TITLE
Feature Request: Make selections with the pen tool

### ISSUE THREAD

**Issue by dvx17** [photopea/photopea#1222]
plzz let us make selections with the pen tool. I can't remove an object from an image because the pen tool only accepts fill color. It's not only for that reason, i can't make logos because i Can't make selections with the pen tool. 

so pls allow us to make selections with the pen tool
it will be easier to use photopea and much more fun

**Comment by photopea** [comment]
Hi, it is already in our todo list: https://github.com/photopea/photopea/issues/1068

**Comment by dvx17** [comment]
about how long is it going to take?

**Comment by MichalSZZ** [comment]
@dvx17 What is your main problem?
I think it can be done without work paths (like in Photoshop) 
Just set fill color to 0 (in eff -> blending options) of your shape (layer). 
There will be nothing on artboard but You can still click with Ctrl button to make selection from layer (path)

https://youtu.be/iJZLo-Puh6s

**Comment by photopea** [comment]
@MichalSZZ In Photoshop, the "path" is a specific object, not related to any layer (it is similar to a pixel selection). There are too many people, who are used to use the Pen tool in a "Photoshop way", so we should implement it in a similar way.

**Comment by MichalSZZ** [comment]
@photopea Yes of course, I understand it :) but I see that the Author of this Issue have a big problem,  I just wanted help and give him quick fix (hack) to make selections from paths :)

BTW. Ivan - do you know that JPG file format can store paths and guides? :)
https://graphicdesign.stackexchange.com/questions/109814/how-was-this-path-embedded-in-a-jpg-image

**Comment by dvx17** [comment]
i need to make a eSports logo for my costumer

**Comment by dvx17** [comment]
i need to make an eSports logo for my client
