### ISSUE TITLE
Remove possibility to click with path/direct select tool on locked shape bellow

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1226]
Everything is in the title :)
It should be no possibility to select locked layer (and switching to that layer automaticaly) with path/direct select tool.

Worst of that - even if I have "lock all" turned on on shapes, I can move and edit knots of locked shapes...

**Comment by photopea** [comment]
Hi, I think I fixed it, both for Path Select and Direct Select. Moving with Keyboard Arrows also does not work.
