### ISSUE TITLE
Snap to 45 deg in pen tool

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1227]
When making path with a pen tool, it is great when you can snap to 45 degree before add next knot (with Shift button).

Look here https://youtu.be/IILuFwlL0II?t=48
In my movie, it is a combination with Alt button to make curves, but with Shift button only pressed, it is the best way to easy draw part of shape, who is e.g rectangle, triangle etc.

**Comment by photopea** [comment]
What a coincidence! Another user asked about it two hours ago, and I implemented it an hour ago. Can you check, if it works well?  :)

**Comment by MichalSZZ** [comment]
LOL. Yes! 
Another thing is just outdated :D #1228
