### ISSUE TITLE
Possibility to changing the direction handle for the next curve in pen tool

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1228]
Now it is hard to draw something with pen tool, without that possibility. 
In Photoshop when you press Alt button before make next knot, you can change direction of one handle separately.
Sometimes I use pen tool to draw vector mask of object or create some fancy shape with pen tool.
When you add that functionality, that tool will be much better and usefull.
look here https://youtu.be/IILuFwlL0II

**Comment by photopea** [comment]
It has been added an hour ago.

**Comment by MichalSZZ** [comment]
THX!
U R awesome!
What channels of requests/bugs I should monitoring to see all issues you are just working on? 
Facebook/blog/reddit or something else? :)

**Comment by photopea** [comment]
It is our 15-year-old user from Brasil, he writes me private messages on Facebook from time to time. He translates his and my messages with Google Translator.

BTW. I just added another feature: when you are dragging a handle with a Pen tool, press Spacebar to move the whole knot.

**Comment by MichalSZZ** [comment]
NO WAY!
I just added that request now! You are reading in my mind!
LOL

**Comment by MichalSZZ** [comment]
@photopea OK i don't want to be silly again with creating new issue 🗡 

One request. After you are ending the path, it should to be possibility to make last curve on anchor point. Click and drag when closing the path.
