### ISSUE TITLE
Moving anchor point with spacebar when drawing with pen tool

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1229]
Maybe at this time that will be not a duplicate request (asking about feature who was added 1 hour ago) :D (not like in my 1227 and 1228 issues) ;)

When you draw a path with pen tool, after create a new anchor point and start dragging direction handle, it should be a possibility to move that point with spacebar and continuing drawing after releasing the spacebar.

**Comment by photopea** [comment]
OMG I added it 10 minutes ago :D

**Comment by MichalSZZ** [comment]
I have a lesson...
Before click "add new issue" button. Turn off and on or reload Photopea to see that feature is not added by the Author (who is reading in my minde or see everything what I do on my computer) :D

**Comment by MichalSZZ** [comment]
I go sleep... I feel useless :D

**Comment by photopea** [comment]
It was just a coincidence now :D You are very useful Michal! Good night! :)
