### ISSUE TITLE
Drop down menu with right click

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#123]
It is the cloning tool again in chrome.

But before you go nuts, i just want to ask if using a specific tool, can you show different options on the dropdown menu that appears when you right-click?

So, for chrome users, pressing Alt-click will give them the menu to select an alternative tool. And in the case of the cloning tool, the anchor (which for the moment we cannot use at all).

Keep the great work  :)

**Comment by photopea** [comment]
Hi.  You can hold K key instead of Alt to choose the source of cloning. So just hold K (as Klone) and click to choose it. It is only temporary, until Google fixes that problem :)

**Comment by avagp** [comment]
Oh!  That should totally be written somewhere.  :/

**Comment by photopea** [comment]
I just added this feature now.  I wrote about it into the English version of the message, that shows when cloning source was not selected.

**Comment by avagp** [comment]
Sorry, but it does not work  :/

**Comment by photopea** [comment]
Are you sure? Just hold K and click somewhere ... reload the Photopea several times, if your browser has an old version in cache.

**Comment by avagp** [comment]
Yes. this is what happends.

When i press any letter key on the keyboard, the cursor disappears. Then i
click the spot where i would like to set the anchor. Finally i move to
another spot and try to draw with the tool. Nothing happends.

But, the feature is there.

I tried holding K and clicking multiple times and in different ways, and
the only way i can get the tool properly working is by holding K and
clicking rapiddly many times. I suppose it is related to the disappearing
of the cursor when pressing K. Somehow i skip that bug when i hold K and
click many times getting the proper key combo.



2017-01-20 22:03 GMT-03:00 Photopea <notifications@github.com>:

**Comment by photopea** [comment]
Ok, I have reported it here https://bugs.chromium.org/p/chromium/issues/detail?id=683524  . This is a problem with Chrome OS, your cursor should not disappear.

**Comment by photopea** [comment]
Hi, so there was a bug in Clone tool and it did not work correctly. I fixed it. Maybe it solved your problem. Ivan.

**Comment by avagp** [comment]
Yes it got solved!  :D  So glad you cold fix it. Now i have a new tool.

Even though, you have to know that it only works with "Alt Gr" button, the
one on the right side of the keyboard, maybe you should try in other
chromes and rename the help message to tell you that  :/

(it took me me a couple of minutes to figuring out, knowing that something
was changed from the last time)

Regardless, thank you!



2017-02-23 11:30 GMT-03:00 Photopea <notifications@github.com>:

**Comment by photopea** [comment]
I am very sorry for not analyzing the problem deeper. Actually, it had problems only when you zoom in. I was testing it with a zoom 1x, so I had no problems, but with larger zoom, the problem occured.

AFAIK  Alt+Click is the right click on Chromebooks, there is no way I can chane it :(  But you can also use K + Click.

**Comment by avagp** [comment]
Yes, Alt+click is the right click, and it wont be changed, because i know
many people who use it instead the double finger tap.


Well, right now works either Atr Gr+Click and K+Click

:)





2017-02-24 18:29 GMT-03:00 Photopea <notifications@github.com>:

**Comment by photopea** [comment]
Thanks for letting me know :) And also, you have to be much harder on me, when you see that something does not work and I claim that it works. I am sorry for that.

**Comment by avagp** [comment]
😉




2017-02-24 18:55 GMT-03:00 Photopea <notifications@github.com>:
