### ISSUE TITLE
Possibility to make guides from ruler not only with Move Tool

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1232]
Now Photopea have small part of functionality of guides (making and snapping to) in comparision to PS

part one https://youtu.be/RxK4MgJbjVE making guides when transforming and using ruler tool
part two https://youtu.be/6_sbac1BuTc snapping to selection and text

**Comment by photopea** [comment]
I added following properties:

- guides can be dragged from the ruler with any tool active
- guides always snap to usual snapping objects (document boundaries, grid ...)
- if there is a selection, guides snap to its borders
- if there is no selection, guides snap to the borders of the current layer(s)

**Comment by MichalSZZ** [comment]
Great! Thank you!
