### ISSUE TITLE
Feature request: Isometric Grid

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1235]
![isometric-grid](https://user-images.githubusercontent.com/38118273/52753283-4a81ed80-2ff6-11e9-8c3e-36085f30f93b.png)

Is it possible to do at all? With all benefits like snapping to that type od grid?
Who can be beneficient of that feature:

- ppl who make graphics to isometric games
- graphic designers who makes charts for data presentations
- icon makers
- anyone who want to create graphic in isometric style

on the web there is many articles about that (how to make isometric like look and what kinde of type you can use) - https://medium.com/gravitdesigner/designers-guide-to-isometric-projection-6bfd66934fc7 here is how that is made in Gravit

**Comment by photopea** [comment]
Hi, I implemented such grid together with snapping. I am still not sure if it is useful :(  Lines intersect at not whole-pixel coordinates. The Move tool always moves by whole pixels, so it will snap (e.g. the top left corner) vertically not exactly on the intersection of lines of the isometric grid.

But it is quite useful for vector drawing.

**Comment by MichalSZZ** [comment]
Great news! Thank you.
Now I will try to make some actions to rotate objects (to the left and right to isometric grid) and make some depth to simulate 3D look (like in this plugin https://graphicriver.net/item/smarticon-generator-2-isometric-3d-icons/19592649 )
