### ISSUE TITLE
Feature Request: Create new document via URL API 

### ISSUE THREAD

**Issue by manticorp** [photopea/photopea#1236]
I would love to see a way to create a new document via the Photopea URL API.

At the moment you have the ability to load files, as either data URIs or from URLs.

However, it would be great to be able to just create a new document at a specified size.

It could either by a documents key or via an app script

For example:

```
{
    "documents": [
        {
            "width":            2000,
            "height":           2000,
            "resolution":       200,
            "resolution_units": "DPI",
            "name":             "10 x 10 inch square"
        }
    ]
}
```

or via an app script as per the Adobe CC scripting reference:

```
{
    "script" : "app.documents.add(1920,1080,192,'My Screen Size', NewDocumentMode.RGB)"
}
```

**Comment by photopea** [comment]
Hi! I implemented this feature over a script. You should convert your JSON object into an appropriate script "on your end".

**Comment by manticorp** [comment]
Hey, thanks!

This works great on the site itself when running from File > Script, but I can't seem to get it to work from the URL?

For example:

https://www.photopea.com#%7B%22script%22:%22app.documents.add(1920,1080,192);%22%7D

**Comment by photopea** [comment]
Oh, you are right :/  In the past, people used scripts to edit the current document. So currently, such scripts (in the URL) are executed after the first document is opened.

I can make the script execute immediatelly, when no documents are passed in the URL. Or you can send a script to Photopea using Web Messaging https://www.photopea.com/api/live

**Comment by manticorp** [comment]
Hmm...the former would be better for my purposes.

My use case is that I would like to be able to send people perfectly sized documents as templates, e.g. a 20 x 20cm file at 180DPI.

At the moment, the only way I can do that is to create a blank PNG file and put it as a document - however, the generated URLs are MASSIVE, even for the smallest PNG.

It would be great to be able to send them just the small link above.

The alternative would be to host a file myself on a CORS enabled server, and inject as a document, but this is something I would prefer to avoid.

**Comment by photopea** [comment]
Ok, I fixed it. Now, if you send only the script without files, it will be executed: https://www.photopea.com#%7B%22script%22:%22app.documents.add(1920,1080,192,'My%20Screen%20Size',%20NewDocumentMode.RGB)%22%7D

**Comment by manticorp** [comment]
Aha that is awesome, thank you so much!
