### ISSUE TITLE
Auto Correction Not Working?

### ISSUE THREAD

**Issue by WMDesign** [photopea/photopea#1237]
I tried the auto tone, auto color, and auto contrast and saw no difference in the image I was editing.  The same image had a dramatic improvement when auto color was used in Photoshop.

Great concept, hope to see it continue to improve!

**Comment by photopea** [comment]
Hi, Auto Tone and Auto Contrast should work in Photopea exactly as in Photoshop. But I could not figure out what Auto Color does :(
