### ISSUE TITLE
Cant save

### ISSUE THREAD

**Issue by terohero** [photopea/photopea#1238]
I tried to save an image/lair as PNG or JPG but nothing happened at all. Maybe its because I have to many tabs open (I am translating a comics, thats why) and something bugged out. But this never happened to me. I just want to know if something can be done or if I have to close it and start from scratch. Ask  if you need more info. 
-Thomas

**Comment by photopea** [comment]
Hi Thomas, can you download any files from the internet at the moment? Are you saving using File - Export As - JPG / PNG? Can you save it as a PSD and open it again?

**Comment by terohero** [comment]
Yes, I can download files form the internet. Yes i tried save it via file - export JPG/PNG when - when I press save the only thing that happens is a small lag and increased numbers in task mannager (I have space to download dont worry). I dont exactly know what happend but I think it might be that I have opened too many tabs. 
![tabs](https://user-images.githubusercontent.com/47677948/52888474-0e789500-317c-11e9-9518-841d790a67a2.JPG)

**Comment by terohero** [comment]
I guess there is not much what you can do from your end, right? I can send you a video if you need to see the process step by step. its pobably not even a problem in photopea, it just may be ma RAMs or something, If you can atleast somehow figure out what caused it, that would be great. sorry for my English its not my first language.

**Comment by terohero** [comment]
Good news, I can upload it to igmur a then save it from there. Still can save normally tho .

**Comment by photopea** [comment]
It is really strange. Can you check, if you see any errors in the web console?

**Comment by terohero** [comment]
It was already late and I went to bed, I solved it via imgur and closed photopea. I tried Ph today and everything is fine. Idk what happend but thanks for responding and to anyone else - be careful not to open too many tabs, I guess.

**Comment by photopea** [comment]
I am really sorry for the bug, it probably had to do something with RAM, but I can't tell if I could fix it. Maybe you could fix it just by updating your browser.
