### ISSUE TITLE
Not able to paste images onto page

### ISSUE THREAD

**Issue by zainaba194** [photopea/photopea#1239]
I cant seem to paste images (from word) onto my page, i have tried images from google and that too doesn't work.. Weirdly if i screen shot and paste that works.

**Comment by photopea** [comment]
Hi, do you mean copying by Ctrl+C and pasting by Ctrl+V? We did not change this feature in a long time. It seems to work fine for me in a latest Chrome on Windows.

What browser do you use? Did it work before? Can you update your browser?

**Comment by zainaba194** [comment]
Yeah both Ctrl C&P and going to edit, paste 
I'm using google chrome. It was working 4 days ago it when I was working

**Comment by photopea** [comment]
Edit - Paste will paste only stuff copied within Photopea, not outside Photopea. You should use Ctrl+V to Paste.

**Comment by zainaba194** [comment]
i'm sure that's what i was doing (ctrl v).. I just copy, pasted an image off google and it worked.
Thanks for your assistance

**Comment by photopea** [comment]
I right-click any image on any website, choose Copy, then I go to Photopea and press Ctrl+V. It always works for me.

Can you record a video of what you do and what happens?

**Comment by zainaba194** [comment]
It's working now
Before nothing happened.. From Microsoft word I even copy and pasted onto the document and it pasted but when I came to photopea it wouldn't paste I don't know why

**Comment by photopea** [comment]
I am not sure if you can copy images in Microsoft Word and paste them outside Word. You should probably report this as a bug to Microsoft.

**Comment by zainaba194** [comment]
I was doing it a couple of days ago, but maybe its just something on my end.
Thank you again
