### ISSUE TITLE
i can't select or edit layers

### ISSUE THREAD

**Issue by bruhve** [photopea/photopea#1240]
so i'm using an acer google chromebook obviously using google chrome and for some reason i can't select psd layers, edit layers, and half of the time it just looks like this with layers loaded on the side but no picture in the window
![screenshot 2019-02-19 at 8 11 28 pm](https://user-images.githubusercontent.com/47802142/53061173-944d5680-3482-11e9-9a78-8768f79ffc71.png)

**Comment by photopea** [comment]
Hi, does it happen for every file you open in Photopea, or just for some files? How large is your PSD file?

Can you try to disable WebGL (More - Use WebGL) and try it again?

**Comment by bruhve** [comment]
it happens to every psd file that i load no matter the size and yes i did just try it with the disabled webgl.

**Comment by photopea** [comment]
Can you send me one of your PSDs to support@photopea.com ?

**Comment by photopea** [comment]
I have to close it because of lack of details.
