### ISSUE TITLE
Gif Looping problem

### ISSUE THREAD

**Issue by BabyDrifter** [photopea/photopea#1244]
I had a problem with the following project, when the second loops is abou to start the background gif lags  and takes a second to start the second animation instead of looping while trying to export into a gif.
i cannot place the PSD file but i will place an example of the gif.

![tumblr_static_tumblr_static_2h8k2xyts4o488w8wo0kg8o4g_640 2](https://user-images.githubusercontent.com/47900104/53263907-f632d980-3697-11e9-910e-5352dd500c44.gif)

**Comment by photopea** [comment]
Hi, maybe the structure of your PSD corresponds exactly to this GIF result. Can you send me your PSD file to support@photopea.com?

**Comment by BabyDrifter** [comment]
I fixed it thanks,i just had to redo the frame speeds


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by photopea** [comment]
Yeah, that is what I thought too, when I saw it :)
