### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [photopea/photopea#1245]
It is possible to migrate the personal account to organization?
https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by photopea** [comment]
Hi, I think this is question about GitHub and it is not related to Photopea, right?

**Comment by Neustradamus** [comment]
Linked to this personal account: https://github.com/photopea

**Comment by photopea** [comment]
Do you want us to help you move your personal account on GitHub to organization? Or you want Photopea to make its account an "organization account"? I don't know GitHub very well. What would be the purpose of it?

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by Neustradamus** [comment]
"Or you want Photopea to make its account an "organization account"" yes

**Comment by photopea** [comment]
I can't see any reason to do so.

**Comment by Neustradamus** [comment]
@photopea: I think that the best solution is (in few minutes):
- Change your username to photopeaaccount (or other): https://github.com/settings/admin
- Create photopea organization: https://github.com/organizations/new

And:
- Transfer photopea into photopea org: https://github.com/NEWACCOUNTUSERNAME/photopea/settings
- Other repos too (if linked to photopea)

No lost, you can see, for examples:
- https://github.com/nerzhul/ocsms
- https://github.com/tigaseinc/tigase-server

Some links:
- https://help.github.com/en/github/getting-started-with-github/types-of-github-accounts
- https://github.community/t/best-practices-for-organizations/10205
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams

**Comment by photopea** [comment]
I can not see any benefits of what you are suggesting.

**Comment by Neustradamus** [comment]
Dear @photopea team, dear Ivan Kutskir,

Have you progressed on this ticket?

I propose you to rename your account to IvanKutskir or Ivan-Kutskir or other.
And to create the good organization for the project.

No lost, GitHub adds redirections, all details are in description and it takes 2mn to do it :)

Links about Photopea:
- https://news.ycombinator.com/item?id=26769141
- https://getlatka.com/companies/photopea
- https://www.producthunt.com/products/photopea
- https://www.zoominfo.com/c/photopea/448108399
- https://www.crunchbase.com/organization/photopea
- https://tracxn.com/d/companies/photopea/__5nMoLNXUMYvpSsCVwWiHAkD7YEE2povzCauIWgx_ojg
- ...

**Comment by photopea** [comment]
How exactly can I help you? How does it help you if I "migrate to organization"?

**Comment by Neustradamus** [comment]
Dear Ivan Kutskir,

It is me who try to help you to respect GitHub rules, below, the recall details and steps.
It takes 2mn to do it.

You must to respect GitHub TOS:
- https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#3-account-requirements

Of course, there is a better project management, more pro, etc. (of course, it is free = zero = 0).

For example, the first user of Microsoft organization at top right:
- https://github.com/radical
- You can see one Microsoft organization member, Microsoft in "Organizations", and you see organization between table of contributions. It is same for all organization members.

For example, verified status in the GitHub organization:
- https://github.com/GitHub

---------------------------------

RECALL again all details from main description:

Dear @photopea team, dear Ivan Kutskir,

It is possible to migrate the personal account to organization?

Your project can not have a personal account but an organization and it is free.

You must to respect GitHub TOS:
- https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#3-account-requirements

You have two possibilities:
- Converting
- Rename / Create an organization / Transfer repositories (no lost, redirections are here)

Important to know, there is no lost, and GitHub adds redirections after a transfer, for example:
- https://github.com/libreswan has been converted
- https://github.com/exiftool has been converted
- https://github.com/redorescue has been converted
- https://github.com/nerzhul/ocsms -> https://github.com/nextcloud/ocsms
- https://github.com/tigaseinc/tigase-server -> https://github.com/tigase/tigase-server
- https://github.com/boothj5/profanity -> https://github.com/profanity-im/profanity
- https://github.com/asciimoo/searx -> https://github.com/searx/searx

Thanks in advance.

----------------------

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://docs.github.com/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by photopea** [comment]
Are you an employee of Github? Are you a machine?

**Comment by Neustradamus** [comment]
I am not a GitHub employee and I am not a machine.

But I try to help projects/organizations to respect rules.

A lot of projects/organizations have already been changed with success.

It is a pleasure to help Photopea to be perfect on GitHub :)

Our common folder has started 7 years ago in some weeks.

Do you need help to do few steps?

It is not clear in main description?

Recall, it takes 2mn.

**Comment by Neustradamus** [comment]
Dear @photopea team, dear Ivan Kutskir,

Have you progressed with this ticket?

To respect GitHub TOS, etc.?

**Comment by photopea** [comment]
I am not doing it. If Github wants me to do it, they should let me know.
