### ISSUE TITLE
Max the error messages

### ISSUE THREAD

**Issue by SyazAmirin** [photopea/photopea#1248]
Hi.

Can you max the error messages? For example, I, for fun, clicked multiple times and the error message "Layer is not editable" came out. And... well, there are too many of them now. Need to wait for one by one to close, is really a pain in the butt.

That's it, really.

![the 92](https://user-images.githubusercontent.com/21003809/53390622-ad985a80-39ce-11e9-8a80-ae387a58966d.PNG)

**Comment by photopea** [comment]
Hi, I added a new condition, such that if a message with a specific text is currently displayed, a new message with the same text will not be displayed.
