### ISSUE TITLE
Lasso tool options are reversed

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#125]
Except for Replace, Union and Difference are switched. And XOR and Intersection are also switched between them.

**Comment by avagp** [comment]
Or i am unsertanding wrong the option?

**Comment by photopea** [comment]
Why do you think they are? I just tried them and they look nice.
Union will contain pixels, which were in the previous OR in the new selection.
Intersection will contain pixels, which were in previous AND in the new selection.
Difference will contain pixels, that were in previous, but are not in the new selection.
XOR contains pixels, that were in previous OR in new selection, but not in both.

**Comment by avagp** [comment]
I just figured out that i had inverted selection before.

Sorry, my mistake.

**Comment by photopea** [comment]
You are welcome :) I am very glad that you examin Photopea so thoroughly.
