### ISSUE TITLE
File menu bar missing when logged in

### ISSUE THREAD

**Issue by kcheyne** [photopea/photopea#1251]
I have noticed that if I am logged in to Photopea (via Github), close the window, then try to re-open PhotoPea, the File Menu bar is missing.  

If I log out, the menu re-appears. The menu remains when logging in again.   However, if I close the window and reopen, the menu bar is gone again.   Only the red Account button remains.

I am using Chrome latest on Windows 10.

![image](https://user-images.githubusercontent.com/32852338/53448970-5a2e0880-39de-11e9-965a-9e972c96a055.png)

**Comment by photopea** [comment]
Hi, I can not reproduce it :(  Can you reload Photopea several times and try it again?

**Comment by kcheyne** [comment]
Yes, I can reproduce it each time.  If I am logged in and close/reopen the window, the file menu does not appear.     As soon as I log out it appears.  Logging in will keep the menu intact until I close the window.

I turned off all extensions and restarted my computer but no change.

**Comment by photopea** [comment]
Do you see any errors in a web console? Could you try to clear your cookies?

**Comment by kcheyne** [comment]
I think it I have fixed it.  Appears to be related to Github token/cached credentials.   I tried logging in using Google and had no issue when reloading it.   Opened up Github, logged out, then tried to login to Github via Photopea.  After doing that it seems to be working correctly.
