### ISSUE TITLE
Can't open psd + only can open certain ones.

### ISSUE THREAD

**Issue by Hiikaaa** [photopea/photopea#1253]
I cannot open post of my psd coloring's, I can how ever open some. Whenever i try to open a coloring from a certain person, it just has the loading bar up there and it never loads or comes off. It just stays there forever. Please help with this issue.

**Comment by photopea** [comment]
Hi, please, send your psd to support@photopea.com

**Comment by Hiikaaa** [comment]
Hi,I do not know if I send the link to the original post or to the one I’ve uploaded on drive. So I will leave two links.

[ORIGNAL LINK]
https://www.deviantart.com/chillinmoon/art/PSD-COLORING-01-689780636

[DRIVE LINK]
https://drive.google.com/open?id=13Ey8Vsqb0vBlJXsTBFiCg-2hQrXomt-2

Thanks, hika.

**Comment by Hiikaaa** [comment]
I sent the psd.

**Comment by photopea** [comment]
Hi, it was fixed, thanks!
