### ISSUE TITLE
Photopea Crashes Chromebook

### ISSUE THREAD

**Issue by blotchjbmr** [photopea/photopea#1254]
whenever I click on certain tool (magic wand, clone stamp, etc.) my whole chromebook just crashes to my desktop, and won't let me open another chrome tab, nor anything else

**Comment by photopea** [comment]
Hi, can you try to update your Chrome OS?

How large images are you opening, in terms of resolution?

**Comment by WTFdedler** [comment]
After loading Photopea and opening a PSD invariably it crashes Chrome browser with 'Ah snap'...I can't get anything done....what do I do? CHrome browser is updated

**Comment by blotchjbmr** [comment]
> Hi, can you try to update your Chrome OS?
> How large images are you opening, in terms of resolution?
My chromebook is updated to the latest version and it happens on images of any size.

**Comment by WTFdedler** [comment]
9000x13023 but this is the size WCfullfilment says to use

**Comment by photopea** [comment]
9000x13023 is quite a lot for raster editing. You need 8 - 16 GB of RAM to work well with such large files.

Try to disable WebGL (More - Use WebGL) or just make smaller files.
