### ISSUE TITLE
Filter Gallery

### ISSUE THREAD

**Issue by l4leeorr** [photopea/photopea#1255]
Hi,

the filter gallery is buggy. as soon as I click on it it opens up a filter but nothing can be changed
I couldnt change the setting even when trying to move the handlebar

Also,
can you please add more filer option please

**Comment by photopea** [comment]
Hi, these filters are very hard to compute. Once you change the value, you should wait a second or more for the result.

You should click on the new position of a slider, instead of dragging it.

We would love to add more PSD filters into it, but we don't know how they work :(
