### ISSUE TITLE
Problem when painting while filter dialog is open

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1257]
When you open some filter with dialog (for example Mosaic) you can paint on temporary image with filter applied with Brush Tool or select parts of image and move them with Move Tool or similar things. After you cancel your filter your in between actions are recorded in History and if you go back and forward in History your image happens to be broken with filter partially applied on parts of layer where you painted. See screenshot:
https://imgur.com/7TyAknH

**Comment by photopea** [comment]
I fixed it. Such tool can not be used, when a document-editing window is open :)

**Comment by hxim** [comment]
Much better but you can still use and apply Free Transform or Transform-Perspective to break your image/history. You can also use Refine Edge function to new layer but it seems to cause no problems but partial Filter effect is still applied in new layer even if you cancel it so i am not sure...

**Comment by photopea** [comment]
I fixed those, too. Thanks! :)

**Comment by hxim** [comment]
Great! I found another functions you can still use when a document-editing window is open and I think you shouldn't be able to:
- Image/Image Size...
- Image/Canvas Size...
- Layer/Duplicate Into...

**Comment by photopea** [comment]
Ok, I fixed those too, thanks! :)
