### ISSUE TITLE
Malfunction

### ISSUE THREAD

**Issue by Kas99** [photopea/photopea#1258]
The program isn't working like usual, everything is inverted or off. I've tried restarting the  program and using the website version but come to the same problem. Can someone help?

**Comment by photopea** [comment]
Hi, could you be more precise, what is not working? Everything works fine for me.

**Comment by Kas99** [comment]
Normally when I insert a picture the transform box is centered but when I
do it now this happens

**Comment by photopea** [comment]
I can not see any screenshot :( could you please reply at the github page?

You should select "Transform controls" in the top bar, to see transform controls (transform box).

**Comment by Kas99** [comment]
![screenshot 2019-03-01 at 11 18 42](https://user-images.githubusercontent.com/48120637/53655096-f0e40a80-3c14-11e9-8d58-fa9242cb3be8.png)


Are you able to see the screenshot now?

**Comment by photopea** [comment]
Hi, yes, I do see it now, it looks like a serious bug.

I tried to create a new empty document, take a screenshot and paste it into a new document with Ctrl+V. It worked well. I also tried to create a new document and paste a photo into it: File - Open and Place. it also worked well.

Could you please tell us, what exactly did you do to make this happen? Does it work the same in an incognito mode?

**Comment by Kas99** [comment]
I didn't do anything. My computer died and I rebooted it up and restarted the program and it was like that

**Comment by Kas99** [comment]
Are you still there?

**Comment by photopea** [comment]
I am here. A webpage should not be able to shut down your computer. Did you try to do the same thing in the Incognito mode?

**Comment by Kas99** [comment]
yes, i got the same result
![screenshot 2019-03-02 at 04 33 37](https://user-images.githubusercontent.com/48120637/53680678-6519bf00-3ca4-11e9-89b4-5717bd5af742.png)

**Comment by photopea** [comment]
Can you try to press More - Use WebGL (uncheck it), to disable WebGL?  Let me know if it helped.

**Comment by Kas99** [comment]
IT WORKED!! What does that do and why does it do that?

**Comment by photopea** [comment]
Your device has a WebGL bug (it can be a browser, OS, gpu drivers ...). Can you update your browser or Operating System? Photopea will be quite slow, when WebGL is disabled.

**Comment by Kas99** [comment]
How do I update my browser?

**Comment by photopea** [comment]
Can you go into chrome://settings/help and see if it is up to date?

Or just find out, what operating system do you have, and search the internet on how to update it.
