### ISSUE TITLE
rectangle shape corner radius does nothing

### ISSUE THREAD

**Issue by joshmorel** [photopea/photopea#1259]
Tried on both Firefox and Chrome. See pics below. Shape to 12px Corner Radius and nothing happens.

**Before**
![photopea-rectangel-corner-radius-before](https://user-images.githubusercontent.com/10546720/53685529-d760c280-3ce9-11e9-869c-62dd3515940e.png)

**After**
![photopea-rectangel-corner-radius-after](https://user-images.githubusercontent.com/10546720/53685530-ddef3a00-3ce9-11e9-873b-bb89538a5a57.png)

**Comment by photopea** [comment]
Hi, that field is for setting the corner radius of a shape, that you are going to create.

To change the corner radius of an existing shape, go to Properties - Live Shape.
