### ISSUE TITLE
no pen pressure

### ISSUE THREAD

**Issue by gamchawizzy** [photopea/photopea#1261]
I'm using a Wacom Intuos 2015 and pen pressure doesn't seem to work. I've tried using a cintiq at school, different browsers, using a smaller canvas size (at 72 dpi) getting better wifi connection, using different PCs...nothing yet. Are there any specific specs this program needs for pressure to work? 

![image](https://user-images.githubusercontent.com/48221436/53759022-53c9f000-3efa-11e9-8388-958dedd8a2c1.png)

**Comment by photopea** [comment]
Hi, have you tried different browsers? Are your browsers updated? Can you try to update the Wacom drivers or the operating system? This is the issue between a browser and the OS / drivers. If nothing helps, I will report it to developers of your browser (or to the Wacom company).

The paradox is, that when I use Photopea on my 80 dollar android phone, it can detect the pressure of the finger and draws a thicker line :/

**Comment by gamchawizzy** [comment]
Updated browsers and drivers, nothing yet unfortunately. I used Chrome and Mozilla Firefox. (Picture A and B)

In fact, using Photopea on Firefox gives you very wonky brushstrokes apparently (see Picture A.) Asked a friend of mine to try using Photopea on his own PC (Intuos CTH-680 on Chrome), no pen pressure on his side either. (See Picture C)


(Picture A) ![image](https://user-images.githubusercontent.com/48221436/53962683-a8ea4980-4126-11e9-9b84-45fcc69e03c3.png)

(Picture B) ![image](https://user-images.githubusercontent.com/48221436/53962714-bef80a00-4126-11e9-9c18-751bf2fb19c6.png)

(Picture C) ![image](https://user-images.githubusercontent.com/48221436/53962767-df27c900-4126-11e9-9b3c-4426a7734891.png)

**Comment by reillyeon** [comment]
What OS and version are you running?

**Comment by gamchawizzy** [comment]
Win10 Home, Version 1803.

**Comment by photopea** [comment]
Hi, I reported it to developers of Chrome, which should get in touch with Wacom (hopefully). There is nothing else I could do at this point :( Let's hope they will fix it soon.

**Comment by Megalomaniak** [comment]
Windows 7 SP1, Wacom Cintiq 12WX, waterfox 56.2.7.1 (64-bit). No pressure what so ever here either.

**Comment by Megalomaniak** [comment]
On closer inspection, the pressure is there, but the pressure curve is totally off. I guess the browsers can't handle pressure levels above 1024. The cintiq I use has 2048.

**Comment by photopea** [comment]
@Megalomaniak Hi! Could you please try it in modern browsers like Chrome and Firefox, too?  

Waterfox is usually based on a 2-year-old Firefox. So you will always be two years backwards in terms of browser advancements https://twitter.com/photopeacom/status/1102224427788500993

**Comment by Megalomaniak** [comment]
Well, I'm couple of releases of waterfox behind myself so I'll try updating that first, but I do have opera to test with too. Alas firefox(quantum) and chrome(/ium) will never get installed on this system. That's just how much I dislike them.

**Comment by Megalomaniak** [comment]
Yeah, just updated both to latest and opera doesn't work either. I wonder if it might have more to do with windows, I have ink turned off in 7 and it makes sense that windows 8 on-wards probably had quite a lot of development on touch and pen support. Oh well. I can always deal with digital painting in Krita, I'm mostly interested in using photopea for webdesign purposes, so as a replacement for photoshop and gimp anyways.

**Comment by photopea** [comment]
It is hard to say what is the reason of it :( Can you get all most recent updates to Windows 7? And maybe get the latest drivers for your tablet?

**Comment by Megalomaniak** [comment]
Already done and done. The cintiq tablet is one of the first cintiq's though so definitely old one itself now.

**Comment by Megalomaniak** [comment]
hmm, looking at https://caniuse.com/#feat=pointer

it's no wonder it doesn't work in waterfox yet(though ff 68 based alpha for waterfox exists) but interestingly opera should work so I do think it's something probably todo with the wacom driver or windows, might just have to do a clean install of the driver perhaps.

**Comment by photopea** [comment]
I think this is the problem between the creators of your tablet, and the creators of your browser. We can not do anything about it :( The only thing we can do is to report it somewhere.

Once the OS + the browser + the tablet driver work well, you should be able to see the pen pressure e.g. in this demo: https://codepen.io/janroudaut/pen/VprRqj

Do you know where could we report it? Or could you report it yourself? It is not related to Photopea at all, they just have to make it work in that web demo above.

fun fact: When I use Photopea on my $150 Android phone, it detects the finger pressure and draws thicker lines.

**Comment by Megalomaniak** [comment]
ok, in waterfox about:config the `dom.w3c_pointer_events.enabled` was set to false. Not sure whats up with opera though. About to restart waterfox and try again.

**Comment by Megalomaniak** [comment]
Ok, restarted the browser, in the codepen demo it shows 0.5 no matter how much pressure I put on the pen though.

**Comment by Megalomaniak** [comment]
Hmm, yeah I think it's just wacom doesn't want to support a tablet this old with the new features like this one, thats probably all it is. It's a shame though I bought this thing for 800€ back in 2013 just as it was EOLed and was on clearance sale from their own german warehouse. Pre EOL it was an even more insanely expensive stylus display. Oh well.

**Comment by Megalomaniak** [comment]
interesting! on https://pressurejs.com/index.html#examples

my pressure works just fine!

**Comment by Megalomaniak** [comment]
Interesting, two days ago I downloaded the latest driver from wacom.com and checking it again today it seems they have rolled a version back... going to try uninstalling and then installing the older version.

**Comment by Megalomaniak** [comment]
Nope, older driver seems to be the same too, Made a post on wacom forums, will see if I can find out more from there.

**Comment by photopea** [comment]
So I guess the pressure.js demo works for your Wacom tablet the same way, as if you did it with a mouse.

**Comment by Megalomaniak** [comment]
Guess so.

**Comment by photopea** [comment]
I asked Wacom on Twitter

**Comment by photopea** [comment]
https://twitter.com/wacom/status/1122907364716363777

**Comment by Megalomaniak** [comment]
Yeah, thanks but I'm not really expecting the marketing people to even know what a pointer event is. :)

**Comment by photopea** [comment]
So I am a marketing person, because I respond on Photopea's Twitter? :D

Could you respond to them, please? https://twitter.com/wacom/status/1122996985911554048 :)

**Comment by Megalomaniak** [comment]
Don't use twitter(don't have an account) but as I said, I made a post on the wacom forums, its sitting in moderation with the info asked.

**Comment by bomborant** [comment]
I apologize for Necro-ing this thread. But thought I'd add to this in case anyone else finds themselves in the same boat as the users above.

I had the same issue before because I had Windows Ink disabled (which I disabled on purpose as I didn't need the extra features) but it seems certain apps (such as browsers) rely on it. So making sure Windows Ink is active (and communicating with your device - I had to activate it both in the Windows Settings and the Driver Settings of my tablet) allowed Pen Pressure in Photopea 👌

**Comment by Megalomaniak** [comment]
Yes, windows ink is needed for the pen to work with web-browsers at all, that wasn't my issue. Sadly waterfox doesn't support pointer events properly. On the pressurejs.com the site tells me it's falling back to a polyfill that uses time as 'pressure'.

I'll just have to report it as a bug to https://github.com/WaterfoxCo/Waterfox

**Comment by GorgonFreeman** [comment]
Just to add to this, my Wacom Pro L from about 8 years ago works with the [PressureJS demo](https://pressurejs.com/index.html#examples) - All and Pointer Events - but no dice with Photopea tip dynamics, Chrome or Safari on a Macbook. Will update if I find a solution.

**Comment by photopea** [comment]
Yes, you need to enable "Stylus Pressure Controls Size", if you want the stylus pressure to control size.

**Comment by aliciarubleart** [comment]
> Yes, you need to enable "Stylus Pressure Controls Size", if you want the stylus pressure to control size.

It doesn't seem to work for me either. 
I have 'TIp Dynamics' enabled in the Brush window. And under Tip Dynamics I have size control set to Pen Pressure with the minimal diameter turned up. 
I'm also using a Wacom tablet, Cintiq 22HD, on a MacBook Pro.

**Comment by Megalomaniak** [comment]
> **@aliciarubleart said:** I'm also using a Wacom tablet, Cintiq 22HD, on a MacBook Pro.

First thing to check is if you have functioning pointer events for touch/pressure in your browser.
