### ISSUE TITLE
Can't resize rubber on chromebooks

### ISSUE THREAD

**Issue by TomPotter8** [photopea/photopea#1262]
Hello,

When selecting the rubber icon and trying to resize it in the drop down box in the top left corner the box never drops down and doesn't do anything.

We have tested this on a normal PC and it seems to work find but it doesnt seem to work on chromebooks which is strange.

![capture](https://user-images.githubusercontent.com/48241826/53796189-82ac8a00-3f2b-11e9-843c-164ed7335091.PNG)

**Comment by photopea** [comment]
Hi Tom, can you try to update your Chromebook? Does this button show up e.g. for a Brush tool? Do you see any errors in a web console?

**Comment by photopea** [comment]
I have to close it, because I really don't know how to help you :(
