### ISSUE TITLE
PhotPea loops adblocker message for a premium account.

### ISSUE THREAD

**Issue by bhoyestl01** [photopea/photopea#1264]
Please correct the issue immediately or refund my payment for premium service.
If I don't hear back shortly, I will contact PayPal and cancel the authorization.
Bill Hoye

**Comment by photopea** [comment]
Hi Bill,
can you try to reload Photopea.com ? Does the message still appear?

**Comment by bhoyestl01** [comment]
Yes.
It doesn't even allow time to click the account button to login.

Clicking the account button and login shows I am premium but the ad-blocker
message continues.

Makes the product useless for doing anything. Frustrating.

Bill Hoye

**Comment by photopea** [comment]
I am very sorry for these problems :(

I changed the code. Can you please reload Photopea.com and try it again?

**Comment by bhoyestl01** [comment]
1. If I enter while logged out of account, the ad-blocker message
   appears until I can get logged in.
   2. If I enter already logged in the ad-blocker doesn't appear.

That gets me past the problem.
Thanks
Bill Hoye

**Comment by photopea** [comment]
I am very sorry again for the inconvenience.

Now, this message should be shown only to people without Premium, who use Ad-blocking tools.
