### ISSUE TITLE
Quick Selection tool works non-intuitively

### ISSUE THREAD

**Issue by hmira** [photopea/photopea#1266]
When using the quick selection, odd behavior can be spotted:

![ezgif-pp](https://user-images.githubusercontent.com/540283/53839895-f933a100-3f98-11e9-8a75-a89c9fa12718.gif)

1.  It easily jumps out of red region
2.  When trying to spread the square region, when coming close to borders, the region does not spread

**Comment by photopea** [comment]
You already have black spots inside your selection, so it "thinks", that the black areas outside the sweater should be selected, too.

You should remove the incorrectly selected spots by switching to Subtract mode in the top menu, or holding Alt. It is all described here: https://www.photopea.com/learn/advanced-selecting

I am not really sure this can be improved :( Do you have any example, where a similar tool works better?

**Comment by photopea** [comment]
This is a hard problem, I think our algorithm should be re-implemented form scratch. 

You can still select your object by using a subtract mode. I will close it for now.
