### ISSUE TITLE
Gradient tool does not complete the action- selection line stays/follows mouse

### ISSUE THREAD

**Issue by editorman** [photopea/photopea#1267]
It seems that at the moment, on Mac at least, when I attempt to use the gradient tool (clicking, dragging the tool/selection line, and releasing) Photopea does not complete the action, instead leaving the selection line attached to the cursor as if I had not released the mouse button. It continues even after I've closed/reopened the window, deleted cookies, etc. This issue has happened before but was usually resolved by creating a new layer, but that doesn't seem to work anymore. I would very much appreciate advice or a fix for this.

Lastly, I want to say thank you for this website, it is very helpful at my job.

**Comment by MichalSZZ** [comment]
Gradient tool don't work without selection.
Me and my students had that problem now.
On Mac and Windows (Chrome and Firefox).

**Comment by photopea** [comment]
OMG, I am very sorry :(  it should be fixed now.

**Comment by MichalSZZ** [comment]
Now works great. Thank you.
