### ISSUE TITLE
Size of smart object don't update after changing canvas size proportion inside of Smart Object

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1268]
1. Make circle on new layer.
2. Create smart obcject from that layer.
3. Double click to edit that smart object.
4. Change canvas size in that smart object (f.g. 200% of height) and save to update.
5. Switch to oryginal file with smart layer.
6. It has steel 1:1 proportion and should be 1:2 after update.

**Comment by photopea** [comment]
This is a great feature! I just implemented it! :)
