### ISSUE TITLE
Auto-blend Button?

### ISSUE THREAD

**Issue by Spearbinnieb** [photopea/photopea#1269]
So while I was trying to follow a tutorial of how to photoshop peoples faces to other peoples faces (don't question it 😆) the main thing they used was the button in the edit drop down menu called "Auto-Blend Layers" and honestly I think that would be super useful to have! Or is there just a way to have the same effect as that button without having to actual HAVE that button (I'm sorry if that doesn't make sense, I was trying to work on attempting to find out how to use the tools on your site to make it into an auto-blend myself but obviously that failed)? [https://www.youtube.com/watch?v=h7bDCFlSeGg](url) (The video I attached is the tutorial that I was following)

**Comment by photopea** [comment]
Hi, I added this feature. Select the layers, that you want to blend, and press Edit - Auto-Blend.

It is not necessary to make a "hole" behind a face, as in Photoshop.

**Comment by idow09** [comment]
Are there plans to make this feature more configurable? In photoshop I think you can control the blending (even though it's Auto-Blending :laughing: )

**Comment by photopea** [comment]
Would you like to choose between Panorama and Stack Images? Or what exactly would you like to do?

Panorama creation is not available in Photopea at the moment, so we can provide just one option at the moment (i.e. all you could do would be to press OK or close it).

**Comment by idow09** [comment]
Yeah OK now I understand the issue. Indeed I wanted to use Panorama.

And the options "Seamless Tones and Colors" and "Content Aware Fill Transparent Areas" in Photoshop are only available in Panorama mode?
