### ISSUE TITLE
Cannot paste from Windows 10 clipboard history

### ISSUE THREAD

**Issue by ovidiupruteanu** [photopea/photopea#1270]
Pasting from clipboard with Ctrl + V works fine, but pasting from the new Windows 10 clipboard history with Win + V doesn't do anything.

**Comment by photopea** [comment]
Hi, I don't have access to Windows 10 and I am not sure what it means. If it does the same thing, can't you just use Ctrl + V instead of Win + V?

**Comment by ovidiupruteanu** [comment]
Hi. It's not the same thing. Clipboard history is a feature introduced in the October 2018 update. It lets you paste from the last 25 things copied to clipboard.
It looks like this:
![image](https://user-images.githubusercontent.com/2089342/54022167-8eea4e80-419a-11e9-960f-8036627abac5.png)

**Comment by ovidiupruteanu** [comment]
I just tested [this example](https://codepen.io/tmrDevelops/pen/YxGQaW) and it works correctly with Win + V

**Comment by photopea** [comment]
In Photopea, we can paste only images, which a browser allows us to paste (the browser notifies the web app, that the user is trying to paste something, and we can accept it or ignore it).

So this issue is entirely between Windows 10 and the browser. What browser do you use? The only thing I can do is to report it to browser makers and hope, that they will implement it eventually. I will close it for now, but we can keep discussing it.

**Comment by ovidiupruteanu** [comment]
The browser shouldn't be the issue since I tested with the example above and it works correctly. I'm using the latest version of Chrome.

**Comment by photopea** [comment]
What do you mean by "I tested with the example above"? Is there any website, which accepts pasting with Windows 10 clipboard?

**Comment by ovidiupruteanu** [comment]
Yep, this one: https://codepen.io/tmrDevelops/pen/YxGQaW

**Comment by photopea** [comment]
So are your pasting text or images?

**Comment by ovidiupruteanu** [comment]
Images

**Comment by photopea** [comment]
This is strange. Photopea should accept images in the same way, as your Codepen example.

So what exactly happens, when you paste an image to Photopea? Nothing happens?

**Comment by ovidiupruteanu** [comment]
Yes, nothing happens. Not even the "doPaste" and "systemPaste" are logged to the console.

**Comment by photopea** [comment]
There should be at least "systemPaste", if your Codepen really works. Are you trying them both in the same browser?

**Comment by ovidiupruteanu** [comment]
Yes, the codepan example works and I'm trying them in the same browser. Somehow, in Photopea, the "paste" event is not triggered by the new clipboard. I even tried adding another listener on the "paste" event and that's not getting triggered either. 
It's like something else in the code is blocking that event. I'll investigate further.

**Comment by ovidiupruteanu** [comment]
From what I could gather, the new clipboard works like this:
1. You press Win + V
2. You select an image from your clipboard with your mouse
3. Browser receives "fake" `keydown` events for Ctrl and Ctrl + V
4. Browser also receives `paste` event

I tracked it down to the `preventDefault()` you have in your `keydown` event listener. If I remove that the paste starts working.

**Comment by ovidiupruteanu** [comment]
It looks like a Chrome issue, it works fine in Firefox.

The "fake" `keydown` event that is received for the new clipboard paste doesn't have a value for the `code` property. It looks like this:

```
{
    altKey: false
    bubbles: true
    cancelBubble: false
    cancelable: true
    charCode: 0
    code: ""
    composed: true
    ctrlKey: true
    currentTarget: null
    defaultPrevented: true
    detail: 0
    eventPhase: 0
    isComposing: false
    isTrusted: true
    key: "v"
    keyCode: 86
    location: 0
    metaKey: false
    path: (4) [body, html, document, Window]
    repeat: false
    returnValue: false
    shiftKey: false
    sourceCapabilities: InputDeviceCapabilities {firesTouchEvents: false}
    srcElement: body
    target: body
    timeStamp: 4258.994999996503
    type: "keydown"
    view: Window {postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, parent: Window, …}
    which: 86
    __proto__: KeyboardEvent
}
```

It's missing the "KeyV" value, so your code isn't catching it:
```js
l.gIQ = "ZoomToggle BrightnessDown BrightnessUp AudioVolumeMute AudioVolumeDown AudioVolumeUp LaunchApplication1 F1 F2 F3 F4 F5 F6 F7 F8 F9 F10 F11 F12 Enter Shift Escape KeyV".split(" ");
...
return l.gIQ.indexOf(_) == -1 || s.shiftKey && _ == "F5"
```

**Comment by photopea** [comment]
Wow, I really admire, that you got so deep into my code :) would you like to help us develop Photopea?

I stopped preventing Default on keydown, when e.code is not defined. Does it work now?

**Comment by ovidiupruteanu** [comment]
I tested and the fix didn't work because the value of `code` in this case is empty string, rather than `null`.
Also, my recommendation would be to check specifically for the "v" key, rather than making an exception for all events with empty codes. I think it might be the safer approach in this case.

Something like: 
```js
s.jd = function (Q) {
    var g = Q.code;
    return Q.keyCode != 86 && (s.yFE.indexOf(g) == -1 || Q.shiftKey && g == "F5")
};
```

Looks like `code` is a working draft: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code#Specification
I'm guessing this is why we're seeing the inconsistency between Chrome and Firefox.

**Comment by photopea** [comment]
If you look at https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent , only the "key" and "code" value are recommended to usage. "key" is the text, that is supposed to be typed by the event (can depend on various shortcuts and OS), while "code" is the identifier of the hardware key (should be the same for all devices and OSs).

I changed the comparison to an empty string, does it work now?

**Comment by ovidiupruteanu** [comment]
Yes, it's working now.
Thanks!

**Comment by photopea** [comment]
Great, thank you too! :)

**Comment by quinnaissance** [comment]
I just wanted to note that this issue persists for me on Windows 11 in Edge and Chrome (but weirdly, not Firefox) as well as in the desktop app.

**Comment by photopea** [comment]
What issue do you have? Comments in this thread have been written five years ago.

**Comment by quinnaissance** [comment]
I am aware this is old but this is the only reference I found to this issue.

I suppose whether or not there is an issue depends on what is desired from a UX perspective. Usually when pasting from Clipboard History, clicking on an item will immediately paste that item into the desired location. When I wrote the first comment, my observation was that on Firefox this worked as expected, but on Chrome/Edge it did not do anything at all.

However, I have since discovered that on Chrome/Edge it does actually work if you add an extra CTRL+V after clicking on the Clipboard History item you want to paste. This is still in contrast to most websites that allow this, though. For example, if I go to imgur.com, I can paste the third item off the clipboard and it immediately picks it up, with no further CTRL+V necessary.

**Comment by photopea** [comment]
In Photopea, we need a direct access to your clipboard using the Clipboard API: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API 

- pressing a button inside Photopea should open an image from your clipboard
- pressing a button inside Photopea should store an image to your clipboard

i.e. working with clipboard should not depend on you wanting to paste something or pressing Ctrl+V.

The clipboard API works fine in Chromium browsers, but is buggy in Firefox, so we do it the "regular way" - we wait until you paste it through your OS.

**Comment by ovidiupruteanu** [comment]
I understand. 

I think this issue is similar to the one from 5 years ago. When you paste from the clipboard history, Windows simulates a paste action. This simulation triggers a KeyboardEvent that represents a Ctrl + V keypress. However, since this event is generated programmatically by the operating system, the code property ("KeyV") is missing (it's set to ""). Since Photopea relies on the `code` property in the keyboard event, the paste command doesn't trigger.


```js
{
    isTrusted: true,
    altKey: false,
    bubbles: true,
    cancelBubble: false,
    cancelable: true,
    charCode: 0,
    code: "",
    composed: true,
    ctrlKey: true,
    currentTarget: null,
    defaultPrevented: false,
    detail: 0,
    eventPhase: 0,
    isComposing: false,
    key: "v",
    keyCode: 86,
    location: 0,
    metaKey: false,
    repeat: false,
    returnValue: true,
    shiftKey: false,
    timeStamp: 1671185.0999999046,
    type: "keydown",
    which: 86,
}
```
