### ISSUE TITLE
change input type text to number for units of size and with 

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#1271]
```
Image -> Canvas Size
Image -> Image Size
```

I can write letters to this field. Can you change it please?

**Comment by photopea** [comment]
Hi, if you type a letter into this field and confirm, the value will be converted into a number.

Sometimes, this field conatins letters like "px" or "%". When we allow to type anything, and convert it to a number ourselves, it allows us to have the same experience on many devices.

If we used <input type="number">, it would look differently on each device. E.g. Chrome adds little arrows into the field, so the area for the number is smaller.

**Comment by photopea** [comment]
Note, that you can always click-and-drag the label (such as "Width" and "Height") horizontally, to change the value.

**Comment by landsman** [comment]
What? changing letters to random number (š to 3) not making any sense :-1: D
Standard way is type=number. Do not developing wheel.

**Comment by photopea** [comment]
input type number adds arrows in Chrome, which are ugly in my oppinion :(
![image (6)](https://user-images.githubusercontent.com/15955558/54051495-46ef1a00-41e2-11e9-9995-df80d315f286.png)

**Comment by landsman** [comment]
Yeah, it has easy fix in CSS:

```

  input[type=number]::-webkit-inner-spin-button,
  input[type=number]::-webkit-outer-spin-button {
    -webkit-appearance: none;
    margin: 0;
  }

  input[type=number] {
    -moz-appearance:textfield;
  }
```

**Comment by landsman** [comment]
Input field type number is great for virtual keyboards btw.
