### ISSUE TITLE
Problem with warp

### ISSUE THREAD

**Issue by jjholt42** [photopea/photopea#1272]
Warp does not work sometimes.
To reproduce:
Open a file (.jpg or .psd)
Place a rectangular selection
Edit -> Free transform
Select warp button (for some reason I have to do Select -> Transform Selection first to get the button)
Move a handle (little square)
 - nothing happens, image does not warp.

On Windows 10, latest version of Firefox.

![image](https://user-images.githubusercontent.com/27014127/54030329-38a2fd00-41e6-11e9-869e-866378ad5a8c.png)

**Comment by photopea** [comment]
Hey, I fixed it, thanks for reporting it!
