### ISSUE TITLE
GIFS Crashing 

### ISSUE THREAD

**Issue by boba-tea** [photopea/photopea#1273]
Just recently, photopea has been crashing whenever I am trying to save any gif. After I apply the PSD, then export it to gif, but when I try to save it, the whole website reloads to a white screen before redirecting me back to photopea. Please help :(

**Comment by photopea** [comment]
Hi, exporting GIF requires a lot of RAM, especially if you have many frames with large resolution. So my guess is, that you don't have enough memory for it, or your browser does not let Photopea to use that memory.

Can you update your OS or your browser? If it does not help, try to decrease the resolution of your GIF (Image - Image Size - enter a smaller size - OK), then export GIF.
