### ISSUE TITLE
PDF dont open properly

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1275]
I was trying to open this PDFs, but when opening them i only get a black square shape, not he codes.

[EAN-13-0653981824631.pdf](https://github.com/photopea/photopea/files/2955149/EAN-13-0653981824631.pdf)
![image](https://user-images.githubusercontent.com/11801254/54174264-52ea0e80-4464-11e9-980b-f798f246c66e.png)

BTW, the moving tool is missing some icons on the top menu
![image](https://user-images.githubusercontent.com/11801254/54174280-6eedb000-4464-11e9-8fcf-150a51c48250.png)

**Comment by photopea** [comment]
Hi, I fixed it! If the PSD seems too small (pixellized) for you, use Image - Image Size - enter a larger size. But it has no effect on the exported SVG / PDF (which will be vector graphics).

Your top menu is the menu of the Free Transform. You should escape it, to use the Move tool.

**Comment by avagp** [comment]
About the free transform tool, I meant it's missing icons.

Watch closely on the X and Y and the 0.0°

It has squares

**Comment by avagp** [comment]
I cannot open this PDf as well :/
[PVC Sticker.pdf](https://github.com/photopea/photopea/files/2969340/PVC.Sticker.pdf)

**Comment by photopea** [comment]
In the Free Transform, the X and Y icons are correct, it is this character: https://www.fileformat.info/info/unicode/char/25b1/index.htm

The Angle icon is incorrect. There should be this character: http://www.fileformat.info/info/unicode/char/2221/index.htm . Have you tried other borwsers / devicces? Can you update your OS? 

I can not open your PDF in Adobe Acrobat Reader. It says there is a mistake. How did you create it?

**Comment by avagp** [comment]
I have chrome 73 Beta.

On my phone the icon is correctly displayed, so maybe is my browser :/

About the PDF i created in photopea and exported to PDF, but i can open
properly to see it, but not in photopea.
[image: image.png]

I am attaching the PSD

**Comment by photopea** [comment]
Hi, I can not see your PSD :( could you please attach it in the web interface?
