### ISSUE TITLE
issue: Moving panels from one group to another fails

### ISSUE THREAD

**Issue by UInIQ** [photopea/photopea#1278]
### Issue
When attempting to drag a panel from one panel group to another, the destination panel group tab bar indicates the action should be allowed, but there is no result in the UI, nor is there an informative message to the user suggesting the move is not allowed. See screen shots, below.

### Steps to Reproduce

![Panel Drag Failure](https://user-images.githubusercontent.com/17788145/54214649-9e2c0d80-44b4-11e9-8faa-d6f82830dbf5.jpg)

#### UI Updated to Reflect Action (the Photoshop Behavior)
As a long-time Photoshop user, I would expect the action to result in the source panel being relocated to the target panel group. The panel (presumably a free-standing control with its own, compartmentalized styles and behaviors) would size itself to fit the available panel space, behave in concordance with the other panels in the same group on collapse/resize events, and retain its position (cookie, local/session store, react store, etc) on the next load of the software.

#### Error/Informative Message Displayed (and UI/UX Prohibits Action)
If this is a pending feature, or an elective decision to omit, then:
1. The user should be informed of the preclusion, to prevent their assuming it's an error. This can be accomplished via your standard white information notification bar ("This action is currently not supported. Panels must remain within their own panel groups.").
2. The UI should not suggest to the user that the action IS valid. That is to say: the "not-allowed" cursor should be maintained everywhere but within the panel group's own tab bar, the tab bars of other panel groups should not highlight blue, and the I-bar allowing for the horizontal targeting of the drop point (where in relation to the other, extant tabs it is to be dropped) should be omitted.

... Ideally BOTH, _especially_ if this _is_ a known issue/future milestone. There's a 100% chance that you have `ondragend` logic in those drop zones that are resulting in either A) the logic determining it's not a valid move (whereupon you can trigger your standard white information notification feedback message), and/or B) `ondrag` logic that can rip the 'valid drag target' off of any other drop points than the one from whence the drag originated (thereby dropping the `not-allowed` handling back onto the client).

### Final Note
I am presupposing this is a bug due to the fact that reordering tabs within their OWN panel group works just fine. If the inability to transplant panels from one group to another is off the table, then it's a bug because it's simply not clear it's an issue.

### System Details: 
Windows 10 Enterprise, x64 (Quad i7 2.9, 16GB RAM)
Browser: Chrome Version 72.0.3626.121 (Official Build) (64-bit)
Confirmed on browser- and app-modes
_(I'll verify on OS-X High Sierra and Mojave tonight and update)_

**Comment by photopea** [comment]
Hi, you can open panels (Window - Layers, etc.) and close panels (right-click - Close). Opened panels are preserved when you close Photopea and open it again.

One of users asked us to let him reorder panels of documents (in the main workspace area, which have document names as labels). And since all panels use the same model, reordering panels in the right sidebar is also possible. But the order is not preserved after closing Photopea.

Moving panels between different panel blocks is not possible now. I disabled the "light up effect" when you drag a panel from one block to another.

**Comment by UInIQ** [comment]
Hey, thanks for the prompt response! FWIW: color me thoroughly impressed by the software; I'm a paying member (who signed up mainly to see how well it held up to PS). 

I've been working, heavily, in Photoshop since version 2. Not CC2. Not even CS2. _VERSION_ 2. Like, when they added COLOR, 25+ years ago. Couple that with the fact that I've been a front end JS developer for the last 23 years, and I flatter myself in a unique position to appreciate the labor of love you've undertaken here. 

Seriously: I'm genuinely, honestly impressed. Great, great job guys. 

You may assume I'll be as thorough in any bug reports I file, and that I'm using the software enough (I'm currently a senior dev at a major US telecom company... who doesn't have the "business justification" for a copy of Photoshop on this work box, lol) that I WILL ferret out more for y'all. You're doing God's work here; let me know if I can be of any help.

**Comment by kuckir** [comment]
Thanks a bunch! Actually i am just one guy :) https://www.reddit.com/r/IAmA/comments/9urjmg/i_made_a_free_alternative_to_photoshop_that_is

**Comment by UInIQ** [comment]
Are… you… fucking… KIDDING ME?!

No, I just read the entirety of your AMA; I see that you are not!

Let me just say, then, you’re a roaring badass. For real bro… Roaring. Badass. I consider myself a pretty hardcore front-end dev. I’ve been using JS full time since the year it came out. I’ve been a senior or lead engineer for Warner Bros, Toyota, Apple, Cerner, Sprint, Virgin, and a half dozen more… I been around, and I done some shit, and lemme tell you: You’re a BADASS.

I’m prepared to keep my pro membership going henceforth just to make sure I have a way of sending you 80 bucks a year. If you ever find yourself Stateside in the Kansas City area, you hit me up: you may treat this email as a voucher good for a fine steak dinner and a pitcher of the best beer we can find, on me.

It’s devs like you that give programmers a good name. Indeed, I’m routing around your AMA and a link to photopea.com to the dozen devs I manage right now as an example of… well… being a fuckin’ badass!

Mad props dude. Major, MAJOR kudos!

Jason Jurusz

**Comment by xan2622** [comment]
> Moving panels between different panel blocks is not possible now. 

Just like @UInIQ, I wish it was possible to move panels from a *panel block* to another one.

Here are examples of CSS/Javascript snippets (that allow to move DIVs into other DIVs), that, I hope can help you (or inspire you to) implement this "possibility (this customization of the UI): https://speckyboy.com/drag-and-drop-ui/

**Comment by KnIfER** [comment]
I actually modified the "source code"( very old version though ) to achieve this:

<img width="172" height="129" alt="Image" src="https://github.com/user-attachments/assets/798574f9-4502-4c39-8271-fa1644cb1c10" />

I'm planning to add a more convenient way to switch panels using **TamperMonkey** : use mouse wheel to switch between different panels of the same dock!
