### ISSUE TITLE
Filter dialog box with "preview" checkbox to view before and after

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1280]
Everything is in the title :)
By default it should have "checked" state.
When somebody want to look how image looks without filter, it should to be possibility to uncheck preview.

**Comment by photopea** [comment]
Hi, I added such Checkbox to both Filters and Adjustments (Levels, Curves  ...). I also added the Reset button, which resets the configuration of that Filter (or Adjustment).

**Comment by MichalSZZ** [comment]
Great news. Thank you!

**Comment by MichalSZZ** [comment]
@photopea I thinking about one solution about preview and speed of making it.

Now when you have big resolution photo and filter that is hard to calculate (like High Pass) it take a moment to render preview.

When I switch off preview and toggle it again, I think that, program calculate it again? Am I right?

How about one little trick?
When somebody switch off the preview, it should have  all the time the state of filter added (with all settings), but over it show only image with are a base to add filter. When preview will be turn on again, that temporary image will be hidden and program dont must to calculate again...

**Comment by photopea** [comment]
I was too lazy to implement it in a "proper way" :D  But since you wrote about it, I fixed it!

**Comment by MichalSZZ** [comment]
:D thank you
