### ISSUE TITLE
Smart Objects are pixelated

### ISSUE THREAD

**Issue by mikelchris** [photopea/photopea#1281]
Hi,

I am loading vector files as eps into an existing document with the function "Open & Place". After scaling this layer the loaded vector graphic is getting blurry/pixelated. This layer itself is an smart object layer.

Do you have an solution how to scale imported graphics without pixelating?

Thanks!

Best,
Michael

![image](https://user-images.githubusercontent.com/5864130/54266694-2e7f5680-4578-11e9-979b-136b2189d711.png)

**Comment by photopea** [comment]
Hi, sadly, this is an usual ways how PSD files work (unlike AI and other vector formats).

You should enter the smart object and change its resolution (Image - Imag Size - enter a higher resolution) and save it.

**Comment by MichalSZZ** [comment]
Try to double click in layer thumbnail. 
Should open new tab with ability to edit that vector image inside Photopea. 
Change image size (e.g. 500%). It should now resize without pixel (operation on vectors).
Save (ctrl + s) to update main image.
Resize icon. Now it should be e.g. 5x larger then before.

I think it should work like in Photoshop generaly.
When scale smartobject, it should recalculate vector data.

**Comment by photopea** [comment]
But it seems like Photoshop can resize SVG smart objects while re-rasterizing them. So maybe we could do that too. But as soon as you edit a smart object in Photopea, it is always converted to a PSD smart object.

**Comment by MichalSZZ** [comment]
https://youtu.be/1BBZpq2jVu0
I used "place embeded" (finder window with selecting file was on other monitor :) )

**Comment by MichalSZZ** [comment]
Now I see (testing PS ability) that my method don't work with vector smart objects who was made form shape in photoshop.
Strange thing... Both should be a vectors... (SVG and photoshop shape)

**Comment by photopea** [comment]
@MichalSZZ it is not how it works.

In a PSD, every Smart Object is the actual file (JPG, PNG, PSD, SVG, PDF ...). When you create a new Smart Object from layers (in Photoshop or Photopea), it is always a PSD Smart Object. When you scale PSD smart objects, they are pixelated.

When you resize an SVG or PDF smart object in Photoshop, it remains sharp. But you can not double-click and edit such smart object.

When you Open & Place an SVG, PDF or EPS file in Photopea, it is converted into a PSD smart object, which is always pixelated (in Photoshop and Photopea).

**Comment by QuantumInformation** [comment]
So no way to work with svg nicely then in photopea yet (

**Comment by QuantumInformation** [comment]
Ah entering the smart object fixes it thx
