### ISSUE TITLE
Smart layer + Warp + perspective

### ISSUE THREAD

**Issue by HendrixString** [photopea/photopea#1282]
hi @photopea , 

i have a very technical question as it seems your system
reproduces a bug of Photoshop.

if I have a smart layer, and I apply perspective and then a small amount 
of warp then the projection interpolation is changing, it becomes more
stretched. this happens in Photoshop as well.

so, my question is, how do you do it ?
I assumed you first render warp into a texture and then render that texture into the quadrilateral
defined by the free transform.
but your solution seems to create a distortion in projection.

can you please elaborate on that ?

for comparison, you can use two layers with a rectangle image,
one is smart and the other is not.
Both layers will contain an image that spans the entire canvas.
one layer you make smart the other will be normal

*for Smart layer*
- create perspective transform with 50% top edge
- create warp with very minimal change (select one control point and move it only a pixel)

*for Non Smart layer*
- create warp with very minimal change (select one control point and move it only a pixel)
- then create perspective transform with 50% top edge

notice that the smart layer texture jumps and is interpolated differently from the non-smart layer. 
what kind of texture mapping is this ? this is not the regular projection texture mapping

**Comment by photopea** [comment]
Hi, the Perspective transform (dragging each corner separately) corresponds to viewing the layer from a certain angle in a 3D space (with a correct geometrical rendering).

In the warp tool, there is a rectangular image and 16 2D points. The current engine takes an image and the 16 2D points and produces a new image (there is no extra Transform at the input).

When there is both a (nontrivial) Transform and (nontrivial) Warp, we transform the positions of 16 2D Warp points with a Transform, and then use Warp only. It is geometrically correct for Linear transforms, but not correct for Perspective transforms.

I guess Photoshop works in the same way.
