### ISSUE TITLE
A handful of feature requests

### ISSUE THREAD

**Issue by jknason** [photopea/photopea#1285]
I'm not sure if any of these have been requested or already exist and I simply cannot find them, but I scanned the issues page and have been toying with photopea to find them and didn't spot them, so I thought I would just submit a handful of requests in one thread. None of these are deal breakers for me, but they would allow for greater ease of access and would vastly improve how this program handles for me.

1. When moving a guide line from the ruler, it would be handy to have it show the measured placement of where it is lining up. For instance, I do a lot of for print design, and want to have things centered. When I drag a guide line away from the ruler, it would be nice for it to have an indicator of where the line is actually lining up without having to zoom in.

2. Removable/repositionable/movable side bars/menus - I'd like to be able to move the layers bar. I cannot see all of the options available when I right click on layers, because there are too many to fit my screen properly, and I cannot seem to scroll through them. Even a scroll bar would be handy.

3. Zoom menu - When using zoom, right clicking to display zoom options would be great; zoom in, zoom out, fit to screen, and actual size.

4. Quick selection improvements - When using quick selection in art with more than one color, it often just makes a selected square. It would improve the functionality immensely if it would select all things of the same color, with an option for continguous or non continguous.

5. A magic erasure function - It is very handy to erase all of a particular thing, such as the white or black in a monochrome logo, with continguous and non continguous options, as well as tollerance, if possible.

6. A create your own brush tool.

**Comment by MichalSZZ** [comment]
Hi. I'm only Photopea user but I will try to help. (BTW one Issue for one problem is better) 

1. Try to turn on "info panel", there are informations about x and y position.

2. What screen resolution do you use. On what kinde of device? 

3. Do you use keyboard? I thinkt that keyboard shortcuts are very helpfull in that case. But if you use zoom tool, there are options to fit to screen and actual size (but for me shortcuts or e.g. Ctr + miuse wheel is better than mouse clicking) 

4 and 5. 
Why you dont try to use "magic wand" for that?

**Comment by photopea** [comment]
Hi! 
1. I implemented it.
3. I implemented it.

2. Every context menu should be scrollable. Could you send us a screenshot of what you actually see?

4. Quick selection needs a massive ground-up remaking. We are aware of it.

5. You are describing a paint bucket, that would fill with "transparent color". You can do the same already with a Magic Wand + pressing Delete on your keyboard. 

6. You can do it already. Look into the Brush panel. You can define a new brush with current settings. You can press Edit - Define New - Brush to make a brush from the current image.

**Comment by MichalSZZ** [comment]
@photopea big THX for the 1st feature! 
Is it a big deal, to copy that solution (with Width and Height in real time next to cursor) when user create:

1. selection
2. new shape
3. Paragraph Text rectangle?

**Comment by photopea** [comment]
@MichalSZZ sure, I added it to a Crop Tool and a Free Transform tool, too! :)

**Comment by MichalSZZ** [comment]
WOW. Thank you so much!
