### ISSUE TITLE
Font Loading From PSD

### ISSUE THREAD

**Issue by Abystus** [photopea/photopea#1287]
If you open a PSD with a custom font, it will show the message that it loaded the project and the name of the font, but when you click into the text, it will revert to another font (even though it has your font selected, but it is nowhere to be found in the list). To correct the issue, you have to reload the font in question via the load font button. This was tested using a CS2 psd, but I assume any version would work.

**Comment by photopea** [comment]
Hi, Photopea has a huge database of free fonts, that you can use in your work.

People often use commercial fonts such as Arial or Helvetica. We don't have a licence to offer such fonts to you, and you have to load them manually into Photopea (if you own them).

When your text layer requires Helvetica, there will be "- Helvetica" in the font name field (the Minus sign means, that the font is not available). When you try to edit such text layer, Photopea would use the most similar font from available fonts.

Do you have any ideas, how to handle this in a better way? In general, Photopea can not draw letters with  any specific font, if it does not have access to such font (and currently, webpages can not load fonts from your computer automatically).

**Comment by Abystus** [comment]
> Hi, Photopea has a huge database of free fonts, that you can use in your work.
> 
> People often use commercial fonts such as Arial or Helvetica. We don't have a licence to offer such fonts to you, and you have to load them manually into Photopea (if you own them).
> 
> When your text layer requires Helvetica, there will be "- Helvetica" in the font name field (the Minus sign means, that the font is not available). When you try to edit such text layer, Photopea would use the most similar font from available fonts.
> 
> Do you have any ideas, how to handle this in a better way? In general, Photopea can not draw letters with any specific font, if it does not have access to such font (and currently, webpages can not load fonts from your computer automatically).

Well you could host fonts the person owns tied to their account via upload while logged in. Say I wanted Arial available on my account, I could login and upload that font to my account. Now if I ever wanted to use that font, I would just have to login to my account. Fonts are relatively small files, so hosting them per account would be a minimum hit oh the host for storage.

**Comment by photopea** [comment]
Yes, I have been planning it for a long time. There doesn't have to be any hosting, webpages can use a small local storage called "localData". It would be still stored in your computer, but available only to that webpage.

When you open a PSD (or Sketch, SVG, PDF, etc.), Photopea tells you, that the font is not available, and that it will use an alternative font.

**Comment by Abystus** [comment]
> Yes, I have been planning it for a long time. There doesn't have to be any hosting, webpages can use a small local storage called "localData". It would be still stored in your computer, but available only to that webpage.
> 
> When you open a PSD (or Sketch, SVG, PDF, etc.), Photopea tells you, that the font is not available, and that it will use an alternative font.

It does tell you that the font is missing, but goes away almost instantly after it is displayed. Maybe it could be turned into a modal display to attract more attention and also give a button to load font on that modal display? Just trying to provide an easy way for the user to know about it, and a forward driven process to having them load them after being made aware they was missing.
