### ISSUE TITLE
Ctr + ' doesn't work. 

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1289]
Shortcut for show/hide grid doeasn't work.
Tested on Chrome and FF on MacOS

**Comment by photopea** [comment]
I implemented it. I also added Ctrl + ;  to show/hide Guides.

**Comment by MichalSZZ** [comment]
Thanks! 
But... I think that worked good before...
Even in your keyboard shortcuts (in menu "more") that was discribed 
![obraz](https://user-images.githubusercontent.com/38118273/54533004-7f80b780-4989-11e9-820d-957e7b888b51.png)

**Comment by MichalSZZ** [comment]
Another thing:

1. Use cmd + '
2. Don't release cmd
3. Hit ;

grid is switch off (not guides)

Chrome and FF on MacOS

**Comment by photopea** [comment]
It is a well-known bug in MacOS and I think there is nothing we can do about it.

Try to press the same keys here: http://jsfiddle.net/p45f44zb/14/  You probably still see "Quote" after releasing it.
