### ISSUE TITLE
BUG in moving set of layers just after making copy

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1291]
1. Create shape
2. Make copy (ctrl + j)
3. Move right (shift + right arrow)
4. Make copy (ctrl + j)
5. Move right (shift + right arrow)
6. Select 3 layers on layers panel (click first one and last with Shift)
7. Make copy (ctrl + j)
8. Hit V on keyboard
9. Move down this layers (shift + down arrow)

Only first one is moving down (all layers should move, becouse all of them are selected on layer panel)
https://youtu.be/je0w6VXvl5Q

**Comment by photopea** [comment]
Hi! In your video, you are not doing the step 8 - switching to the Move tool.

Using arrow keyboards with a Rectangle tool works the same, as with a Path Select tool. It moves selected paths in an active layer. 

You should use the Move tool (press V on the keyboard) to move all selected layers.

**Comment by MichalSZZ** [comment]
I'm very sorry. I was quite sure that I'm doing that with the steps like above...
