### ISSUE TITLE
Eraser Bug After Magic Wand

### ISSUE THREAD

**Issue by Lobalobo** [photopea/photopea#1292]
Eraser deactivated after using Magic Wand. Makes the layer tool essentially worthless. Hope you can fix this.

**Comment by photopea** [comment]
Hi, what exactly do you mean? I just tried to use Magic Wand, I can use Eraser tool after that.

**Comment by Lobalobo** [comment]
Thanks for getting back to me to quickly. I'll be more specific. I tried
the following on two different images, and on both background and
higher-level layers:

   1. Use eraser tool on a portion of the image: Eraser works as expected.
   2. Use magic wand to select another portion of the image, then delete
   that portion.
   3. Attempt to User eraser on any of the remaining image: Eraser does not
   function.

Hope this helps and can be fixed.

**Comment by photopea** [comment]
Hi, do you still have a selection in your image between steps 2 and 3? When there is a selection (e.g. created by the Magic Wand), pixel-editing tools (Eraser, Brush, Adjustments etc.) work only inside the selected area. You should deselect pixels (Select - Deselect, or Ctrl+D) to be able to draw everywhere again.

**Comment by Lobalobo** [comment]
Thanks, de-selecting does indeed solve the problem. I was unaware that once the content of a selection is deleted from the layer that there is still an active selection. Would have thought that deletion ended the selection, but I suppose I can see why it wouldn't. Thanks.
