### ISSUE TITLE
Cannot set Google Drive to open by default on Photopea

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1293]
I don't know if this should be said in here or in the chromium bug tracker, but here i go.

![Screenshot 2019-03-17 at 20 56 09](https://user-images.githubusercontent.com/11801254/54500024-4dbf1080-48f7-11e9-9e91-6734eb6cd52b.png)

When opening a PSD file from Google Drive (now that i have set photopea as a webapp) it suggest me to open it with the app, which i think is great, because i get the full screen and the focused key combos (like Ctrl+T).

But it happens to be that i cannot check the option "Recordar mi selección" (Remember this option) so the next time it opens those files by default with Photopea.

Ivan, tell me if i have to report this on chromium or you can solve it.

Cheers!

**Comment by photopea** [comment]
Hi, I am afraid this is out of my scope :(  I reported it to a Chrome developer, you can report it as Chromium bug, too.

**Comment by photopea** [comment]
I was told, that they are actively working on it :)

**Comment by avagp** [comment]
:D
Better than Adobe at least
