### ISSUE TITLE
Information about actual % of zoom

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1298]
Hi, 
I don't find any place in Photopea with that info.

In Photoshop there are minimum 3 places (in tab name, left bottom corner in project window, and in navigator panel - but I don't use it).

**Comment by photopea** [comment]
Hi, I know it is missing, but I never really needed such information :/ What are the cases, when it is useful to know?

**Comment by MichalSZZ** [comment]
For me now it is only one case:
When I work on Retina display. I must be on 200% zoom to get real size of image (as it will be view on the web browser). 
Yes, I know - it's funny but sometimes when I make zoom in and out many times, I don't remember to switch to 200% :)

I can work without that. I just only asking about possibility to add that feature with minimum of work.

Second (not so important) thing, it is tommorow lesson with my students. I have next group (on my free graphic design course) and tommorow they will be learn about basic things in Photopea (e.g. how to change color, how to use brush tool, and how to zoom in and out with keyboard shortcuts). I think that, not every one will be know that is on 50%, 100% or 200% zoom.

But I understand that it is hard to finde space for that information, and nothing bad happend if you dont add that.

**Comment by photopea** [comment]
Hey, I added the zoom value to the bottom left corner. It is shown only when Rulers are shown. 

You can check the value any time by enabling rulers with Ctrl+R and Ctrl+R to disable.
