### ISSUE TITLE
Can't record steps when making a new Action

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1299]
1. "convert to smart object" (right click on layer in layers palette)
2. "duplicate layer" (ctrl + j)
3. "move current layer" (when hit V and arrow on keyboard)
4. "merge layers" (ctrl + e)
5. "set layer styles of current layer" (fx icon and e.g. drop shadow)
and maybe much more...

**Comment by photopea** [comment]
Actions is quite a new tool and not all actions are recordable at the moment. Do you really need it for your work, or you are just trying to find missing parts?

**Comment by MichalSZZ** [comment]
No, I don't need it :)
In my job I use Photoshop most of my work time.

I want to have actions in Photopea for isometric transform (rotate left and right and making of 3D depht)

I only testing that new feature.
BTW. When I make this action in PS and load to PP it will work?

**Comment by photopea** [comment]
.ATN files from Photoshop should work in Photopea, and .ATN files from Photopea should work in Photoshop, as both support the same format of actions.

Currently, the idea is, that you use .ATN files which you need to execute in Photopea. If any step is not executed properly, you should send us the .ATN file, possibly with a PSD file.

When we make any ATN step executable in Photopea, we also make such step recordable in Photopea. We need the .ATN file to learn, how exactly this kind of step should be recorded.

**Comment by photopea** [comment]
I will close it for now. I would like you to present ATN files, which you really need to run in Photopea, and start a new issue for each such ATN.
