### ISSUE TITLE
Cursors do not work in Edge

### ISSUE THREAD

**Issue by cthedot** [photopea/photopea#13]
Seems cursors (like in Eyedropper tool) do not work in Edge which uses default cursor. Maybe use a keyword cursor (cursor: crosshair) as fallback to PNG file cursor? IMHO PNG cursors should work in Edge but have not researched that.

**Comment by cthedot** [comment]
please see http://caniuse.com/#search=cursor

**Comment by photopea** [comment]
PNG cursors are standardized for a long time. I think (or I hope), that Edge will implement them very soon ... Can you report it as a bug (or feature request) to Edge developers?

**Comment by cthedot** [comment]
.icon cursor seems to work, just a different format after all. And crosshair as fallback would be great anyway. 

I'll need to check if such an issue is already there. But even if guess will take at least a few month as imho they have other priorities currently ( I'd like serviceworker or full filter and masks but at least edge fev seems much faster than ies ever was and in parts also faster than safaris ;)

**Comment by cthedot** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

Says fallback must be added after url so should be simple fix. Crosshair would be fine I guess.

Also seems a few other browsers do not support png (ie also no data uri) if can use info is current.

Sorry for being such a stickler 😏

**Comment by photopea** [comment]
I am very glad for your reports, you are helping thousands of users :)

PP uses fallback "auto" in CSS filter. I have a suspicion, that Edge does not have a problem with PNG format, but with a cursor size (PP uses 128x128, Chrome and FF currently support up to 128x128).

I reported it as a bug to Chrome and FF
https://bugs.chromium.org/p/chromium/issues/detail?id=591980
https://bugzilla.mozilla.org/show_bug.cgi?id=1253573

Can you go to this URL and see, if any of cursors works?
http://www.ivank.net/veci/cursors.html

**Comment by cthedot** [comment]
just submitted a bug to Edge with this demo:
http://jsbin.com/jujacu/edit?html,css,output

Seems Edge does not yet know the extended URL Version with defined hotspot yet at all. 
So none of the URLs at http://www.ivank.net/veci/cursors.html work.
Guess it still knows the CSS 2.1 version of cursors only https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_User_Interface/Using_URL_values_for_the_cursor_property

Options for workaround for now (as e.g. described at http://www.useragentman.com/blog/2011/12/21/cross-browser-css-cursor-images-in-depth/):

- add a `cursor: crosshair` (or whatever fits best of the predefined cursors) before the data-URI version that will work for Edge. Also replacing auto with crosshair  would be future proof (I hope ;)
- convert PNG cursors to .cur files (which have the addition relative path issue) and remove the hotspot. 
- Keep the current version of the cursor as the last defined property for browsers that can handle the latest cursor spec but change auto to a cursor like crosshair (or text or whatever https://developer.mozilla.org/en/docs/Web/CSS/cursor) so even if cursor fails fallback makes sense.

**Comment by cthedot** [comment]
BTW, both in Firefox and Chrome only 32, 64, and 128 sized cursors work (Win10).

**Comment by photopea** [comment]
I don't like adapting an app to the bugs in the environment (or to an old environment). What if we just wait, until Edge fixes it? There are not that much users from Edge.

I am aware, that Firefox and Chrome have the size limit 128px. That is why I filed bug reports. When you use a huge brush in PP, or you zoom in with a small brush, large cursors are really important.

**Comment by cthedot** [comment]
Waiting could take months if not longer as there are still quite a few areas where Edge has to improve. I am not even sure FF/Chrome will support larger cursors in the near future, guess they are an "edge" ;) case not many websites or webapps need or use.

Adapting to an environment is sadly how any work on the web works at least in my experience. In my work as a webdev I work around browser bugs, inconsistencies and problems all the time and in EVERY browser (IE, Edge, Firefox, Chrome, Safari, iOS, Android, ...). 

For this specific problem it seems an easy back and forwards compatible fix which is just nice to browsers that might not support it.
If you just add `cursor: crosshair` (or whatever makes sense) before your current cursor definition it would be already much better for Edge users like myself.

**Comment by photopea** [comment]
I have reported many bugs to Chrome and FF during the last 3 years, most of them were fixed.

Why don't you use firefox or chrome (or something else) instead? :) People using broken tools are the reason why tool makers don't care too much about an improvement. If you move to competitor tool, they will care more, I think.

I am aware of the fact, that many web developers adapt to bugs (especially in the past). But e.g. in the past, Adobe Flash dominated the "smart web", and Apple released iOS without Flash support. I think, that such decision helped the web ecosystem.

You mean adding cursor:crosshair only if the browser is Edge? And remove it once it is fixed? I really don't want to add browser-specific code and make the system even more complicated.

**Comment by cthedot** [comment]
no, simply add both:

    cursor: crosshair; /* all browsers */
    cursor: url(data:...) 64 64; crosshair; /* browsers that know CSS 3 cursors

Firefox and Chrome have other issues, there simply is no perfect browser and there never will be. I'd simply not use a service which does not work in my browser before switching. And I am a developer who knows how browsers work and their problems. A normal user never changes his browser and sometimes (most businesses) is not allowed even if she wanted to. 
BTW, esp mobile Safari can be the most problematic to develop for so not a good example ;)
And sorry to disagree, but Flash always sucked ;)
iOS not supporting Flash was helping, I agree but at the same time Safari and nowadays Chrome are adding proprietary stuff so fast they can be the main offender these days.

The solution above is progressive enhancement, works on all browsers and experience is even better on browsers that support it.

**Comment by cthedot** [comment]
And I have to disagree, Edge is not "a broken tool". If you define a tiny part of a specification breaks a browser all browsers are broken and the web should be closed ;)

**Comment by cthedot** [comment]
You can vote for better cursor support at https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/6517137-support-png-gif-svg-cursors-and-other-cursor-en (no registration needed). Thanks!

**Comment by photopea** [comment]
Thanks, I just voted for it :)

BTW. I wanted to make PP work in IE 11 some time ago. It has implemented an old version of Typed Arrays, which does not support Uint8ClampedArray. There was a bug report 3 years ago:
https://connect.microsoft.com/IE/feedback/details/781386/typed-array-support-is-incomplete-missing-uint8clampedarray-important-for-canvas And after reading the MS response I gave it up. It seems like MS does not care about the quality of their software at all.

BTW. I would like to add PNG cursors as a new requirement of PP and make it part of http://www.photopea.com/willitwork/ . Do you have an idea, if the support of PNG cursors can be somehow tested through JS?

**Comment by cthedot** [comment]
IE is in maintenance mode so no new features. And no, no idea

**Comment by cthedot** [comment]
What is webcl btw? I know webgl but cl?

**Comment by photopea** [comment]
WebCL is a JS interface to OpenCL. OpenCL is an interface to perform hi-performance parallel computing. I think, that if browsers implemented WebCL. But sadly, it is not available by default in any browser, even few years after the release.

**Comment by photopea** [comment]
Hi, I have replaced all .PNG cursors with .CUR cursors (for all browsers). Does it work in Edge now?

**Comment by cthedot** [comment]
hi,
DataURi cursors and hotspot info break the cursors too so not really ;)

More details:
Crop Tool: IE11/Edge/Firefox/Chrome all use crosshair

Brush/Clone/Eraser Tool: FF/C use small dataURI cursor, IE11/Edge the default as defined inline as cursor:url(data:image/x-icon;base64,AAACAAEAgIAAAEAAQAD4AAAAFgAAAIlQTkcNChoKAAAADUlIRFIAAACAAAAAgAgGAAAAwz5hywAAAAFzUkdCAK7OHOkAAAAEZ0FNQQAAsY8L/GEFAAAAoklEQVR4Xu3d0QlDIQwFUHWOdpBO2SHbObQRfDwH8Ks5B8KF/BrRv5QxRi0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAckXJxdO/9EfGstc6cC7S/EZ/W2kz+XQzAK2LstXrptJWpXDc/Dv09a+9lk3IASM4TcPMJDD6BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHFDKD73yMRnOxgWXAAAAAElFTkSuQmCC) 64 64, auto;
so Edge does not yet know 64 64 hotspot and I think no data-URI support.

Text tool: All use default, maybe you could use the cursor "text" or "vertical-text" instead which should work everywhere?

I think the CSS cursor implementation in Edge is practically the same as in IE11 so if it works in IE11 on your machine it will probably work in Edge too (Edge did improve a lot of stuff like e.g. Flexbox etc etc but some things are just the same).

**Comment by photopea** [comment]
Thanks for info,

I am creating cursors dynamically for each brush, since there can be lots of combinations of brushes (shape, size, rotation, x/y-scale ...). User can even upload his own brushes.

I have removed " 64 64" part. The hotspot is already present in the CUR file. Does it work in Edge now?

**Comment by cthedot** [comment]
Sorry, data-uri is not supported in Edge as said before. Guess only thing you can do is put cursors that are not changable in external files and leave dynamic cursors as they are. And use fallback of crosshair

**Comment by photopea** [comment]
Ok, I am giving it up. 

So please wait, until Microsoft fixes it, or use another browser without this problem.
