### ISSUE TITLE
Unable to use mouse

### ISSUE THREAD

**Issue by tzs5178** [photopea/photopea#130]
For whatever reason, regardless of browser, photopea will not recognize and left or right cursor clicks. Can load images and PSD filed, can move them using left, right, up and down arrows. However, Photopeo will not recognize any cursor clicks whatsoever, whether it be to transform an object or simply close the account tab pop up.

**Comment by photopea** [comment]
Hi, thank you for letting me know.

Four hours ago, I made an update, where I replaced "mouse events" with "pointer events", which should be a more modern way of programming. But now I see, that it is supported only in Chrome, Opera and IE / Edge: http://caniuse.com/#feat=pointer

I replaced it with a previous version, so it should work now. You say, that it did not work in any browser, so not even in Chrome or Opera?

**Comment by tzs5178** [comment]
I hadn't tried Chrome at the time. I realized that shortly after I posted the bug. It works for Safari and Firefox now as well; thank you very much
