### ISSUE TITLE
Free Transform

### ISSUE THREAD

**Issue by slowmoed** [photopea/photopea#1301]
Heyy, big bug with the free transform feature. When I'm dragging, the options at the bar where the "X" and check mark are disappear and don't show up again unless I go to free transform through the edit tab. And when I press the checkmark when they do show back up, free transform doesn't finish and it shows up as many times as I click on the check in the history bar. It reverses other functions like sharpening when I press the check mark, as well. Sorry if that's not a good explanation!

**Comment by photopea** [comment]
Hey, I am very sorry for this bug :(  It should be fixed now.
