### ISSUE TITLE
Crop - Fixed Ratio - broken

### ISSUE THREAD

**Issue by mygumtreect** [photopea/photopea#1302]
Used to work fine. No longer does. I've attached a screenshot where a 6:4 ratio is selected but dragging the crop area is not constrained. I had to use a combination of image resize and image crop to get to my 6:4 ratio.

![Photopea   Online Image Editor](https://user-images.githubusercontent.com/48825168/54813889-3dac8580-4c97-11e9-9177-2f0492687047.png)

**Comment by photopea** [comment]
Hey, i am very sorry for this. I just fixed it. Thanks!

**Comment by mygumtreect** [comment]
Awesome, so quick! Thank you.
