### ISSUE TITLE
Color Range Selection - more options

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1306]
Hi,
Now, I see that Color Range have only one option - "Sampled Colors", who get color samples from image with Eyedropper (or something like that).

This tool is powerfull for making selections but only when have more options.

1. First of all, making color range from selection. Now it takes to analyze all pixels on artboard. In Photoshop, you can fast select something, and then make Color Range only from part of image. E.g. I have photo from London (with red bus and red telephone booth). On that image there are many other red colors (people in red clothes, other red cars, red elevation on houses, and many more red looking things). I can do fast select only bus and telephone cabine with e.g. lasso tool and then use Color Range to make selection of reds from these two things only.

2. Second thing is adding and substracting to/from color range. E.g. I have T-shirt. It is only one colour but have hard highlights and shadows. Fuzziness don't work and it is hard to select all of colour. It works like magic wand but with more precise real time preview.

3. Other predefinied options to use. Now it is only "Sampled Colors". In PS there are e.g. skin tones, hightlights, shadows, basic colors.

How I can work with these 3 methods from above?
I make very fast selection of face (with polygonal lasso tool), then I use Color Range with skin tones option. Accept values and make again color range and then use shadows. Finaly i have selected shadows on face and can play with color corrrections in Adjustments Layers.

https://helpx.adobe.com/photoshop/using/selecting-color-range-image.html

**Comment by photopea** [comment]
Hi, I implemented 1. and 2.
