### ISSUE TITLE
Keyboard shortcuts in any selection tool switch icons in navbar

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1307]
I know that, cursors in PP can't have little "+", "-" and "x".
In #735 we have discused about it.

But I think that, is no any cons to add visual suggestion, of what kind of option is now used in selection (when user use keyboard shortcuts).
I prefere to have "add" as my default option in any selection tool. But most of time I switch from one option to another before start of making next selection. I use for that only shortcuts (alt, alt+shift).
E.g. I made Circle Selection. After that I want to do "moon" by using a substract from other selection. I have Circle selection tool, press alt and now it should switch Icon
from 
<img width="158" alt="obraz" src="https://user-images.githubusercontent.com/38118273/54958809-5b0f7700-4f57-11e9-9402-b04045237d45.png"> to 
<img width="157" alt="obraz" src="https://user-images.githubusercontent.com/38118273/54958830-6ebadd80-4f57-11e9-9604-cbcce6d430fd.png">

If there is no possibility to have little +, -, * next to crosshair cursor, that modification would be a nice feature.
My students have problems when they makes selection with Shift button (to get 1:1 proportions). When they hit to fast Shift button, they have "add" option and dont know why :)

**Comment by photopea** [comment]
Fixed, thanks! :)

**Comment by MichalSZZ** [comment]
Thanks! You are awesome!
