### ISSUE TITLE
Create new layer with keyboard shortcut

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1308]
Shift + Cmd (Ctrl) + N

**Comment by photopea** [comment]
Hi, I implemented it, but the support will depend a lot on your browser. Many browsers still open a new window on Ctrl+N.

It seems like in Chrome, you can press Shift+Ctrl+N +Alt to do the same (althouth Photopea does not require pressing Alt, holding it prevents Chrome from opening a new tab).
