### ISSUE TITLE
Toggling the Lasso Tools with Alt 

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1310]
When you start making lasso with polygonal lasso tool it should to be a possibility to temporary switch to a freehand (normal) lasso with holding Alt button and vice versa 

http://blogs.adobe.com/jkost/2009/08/toggling_the_lasso_tools.html

**Comment by photopea** [comment]
I implemented this feature for a Lasso and Polygonal Lasso tools.  I hope I did not add new bugs :(
