### ISSUE TITLE
Unable to change tabs

### ISSUE THREAD

**Issue by BlinkdGraphics** [photopea/photopea#1312]

**Comment by photopea** [comment]
Hi, what do you mean by changing tabs?

**Comment by BlinkdGraphics** [comment]
Posted this without leaving a description

Just made a new project but have now experienced an issue that I cannot change to the other prject tabs I had been working on (and stupidly didn't save)

**Comment by BlinkdGraphics** [comment]
![image](https://user-images.githubusercontent.com/49042522/55188804-16bcea80-5194-11e9-9618-2848fd6c1e96.png)
Active tab is the new project I loaded

**Comment by photopea** [comment]
I am afraid I can not reproduce it :( I just opened several files in Photopea and I can switch between them without any problems.

Could you try it again? If it happens again, could you describe what exactly did you do?

**Comment by BlinkdGraphics** [comment]
I can tell you what happened when I tried to do this the first time:

I first opened a new project
Then I attempted to use the Gradient Editor in the Gradient Tool.
Then I exited out of that menu to find that I could no longer switch between project tabs.
This has only happened around twice, now and a couple of weeks ago, but the last time was for a minor project so I didnt really worry.

**Comment by BlinkdGraphics** [comment]
Just opened a new tab and tried the same steps again and it works okay on that tab

**Comment by photopea** [comment]
I can not make it happen either :( Maybe there was a certain little detail, which you did when it failed? Could you remember it?

**Comment by BlinkdGraphics** [comment]
Not that I know of... The other two projects I had loaded this time were pretty big (I was making a large graphics pack) so maybe it was too much to handle? I dunno. I do have all of the images and stuff I used for the project so not everything is lost :p

**Comment by BlinkdGraphics** [comment]
Aprox 62 photos/layers (without the folders) in one of the projects

**Comment by photopea** [comment]
I think Photopea crashed in your case because of using too much memory. We are cooperating with browser vendors to let us use more than 4 GB of memory.
