### ISSUE TITLE
Gradient Editor errors

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1313]
1. Open pea.psd - Gradient Tool - Gradient Editor (edit red to black gradient)
2. Add point in between red and black color
3. Move it completele to the right so it overlaps black point
4. Click on it again
5. Try to delete this point (with delete button in dialog or with keyboard delete key)
->
Uncaught TypeError: Cannot read property 'v' of undefined
    at yQ.ZE (pp.js:7007)
    at yQ.og (pp.js:6990)
    at lC.KY.m (pp.js:9)
    at lC.lE.m (pp.js:5850)
    at lC.En (pp.js:5986)
yQ.ZE @ pp.js:7007
yQ.og @ pp.js:6990
KY.m @ pp.js:9
lE.m @ pp.js:5850
lC.En @ pp.js:5986

----

1. Open pea.psd - Gradient Tool - Gradient Editor (edit red to black gradient)
2. Add point in between red and black color
3. Move one small black square (right one) to the left (so it has 5% position)
4. Now move added point slightly to the right so it overlaps with small black square
5. Click and hold mouse left button  on this small black square and move mouse down while still holding left mouse button
->
Uncaught TypeError: Cannot read property 'v' of undefined
    at yQ.gm (pp.js:7022)

**Comment by photopea** [comment]
I think I fixed it. Thank you! :)
