### ISSUE TITLE
Transform - Warp error

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1314]
1. Select something and use "Free Transform" or "Transform Selection"
2. Click "Warp" button
3. In "Nearest/Bilinear" dropdown select other item
->
Uncaught TypeError: Cannot read property 'Z$' of undefined
    at ll.KH.cD (pp.js:8040)
    at Sm.KY.m (pp.js:9)
    at Sm.lE.m (pp.js:5850)
    at Sm.sF (pp.js:6120)

**Comment by photopea** [comment]
I think I fixed it, thanks!
