### ISSUE TITLE
Cant close dialog after selecting other layer

### ISSUE THREAD

**Issue by joshmorel** [photopea/photopea#1315]
If I open a dialog (e.g. color picker) then click on another layer, I can't close the dialog even if clicking back on the original layer. Basically I need to refresh the page to get it workable again.

![Photopea-cant-close-dialog](https://user-images.githubusercontent.com/10546720/55292039-e18ee300-53b3-11e9-8ddf-424fe153ef09.gif)

**Comment by photopea** [comment]
Hey, I think I fixed it. Thanks for pointing it out!
