### ISSUE TITLE
How did you implement the brush tool with variable opacity?

### ISSUE THREAD

**Issue by kamild706** [photopea/photopea#1316]
Hi, this is not a bug nor suggestion. I just wanted to ask for help on how to make a brush tool which opacity can be set to different than 100%. I see that you have only one canvas element, while all solutions to this problem required two separate canvas elements to make brush tool with custom opacity work in real time. 
I would appreciate if you could share a code fragment, textual description or some other resource that explains how to implement this feature.

**Comment by photopea** [comment]
Hi Kamil, this is a very basic thing to implement in every image editor. Even if I explain it to you or share a piece of code, and you make it all work, you will run into many other similar programming problems in the future.

I recommend you to study programming from the beginning. Basic Math and Algorithms. Do not try to implement any your own ideas, if you never implemented things like heap sort or Dijkstras graph search.

Regarding the brush tool, the idea is, that one bitmap (a circle of the brush) is placed "on top" of another (background layer), and the new colors are colors from both bitmaps, combined, depending on the opacity of each bitmap. I would like to tell you more, but I don't know what knowledge you have, so on what level should I explain it to you.

**Comment by kamild706** [comment]
The problem I encountered is identical to this one: https://stackoverflow.com/questions/28105192/html5-javascript-paint-brush
Brush strokes overlap each other and the final image is full of small circles instead of one continuous line.
It seems that there is no trivial way to make this thing work in html canvas. That's the reason I posted this thread. I noticed that you use only one canvas (instead of two as suggested in SO answer) which is probably more interesting solution.

**Comment by photopea** [comment]
So you are drawing a line by drawing many circles?

What I think you need is, that you should draw everything into a separate bitmap with 100% opacity (fully opaque), and then, redraw that bitmap into the main bitmap with partial opacity. So in the old bitmap, everything will be either 0 or 100% opacity, and in the new bitmap, everything will be 0 or e.g. 16 % opacity.

**Comment by kamild706** [comment]
I draw a line using `ctx.lineTo()` and `ctx.stroke()`. Since `stroke()` causes all points in the path to render again (unless you call `beginPath()` to clear points array) the final line doesn't have requested opacity. I don't see any other way than calling `stroke()` on every mouse move if I want to have a real time painting effect.
There is a demo https://codepen.io/matt23/pen/VRqEvN

The solution you gave seems to work, but it requires at least two canvas elements. Unless I'm mistaken, in Photopea you have only one canvas (even when multiple layers are present, what surprises me) so I suppose there is some better solution.

**Comment by photopea** [comment]
In Photopea, we only use two methods of Canvas: createImageData and putImageData. We dont work with vector drawing (lineTo, stroke, beginPath), we process arrays of bytes, which represent pixels, with our own code.

**Comment by photopea** [comment]
Also, I dont know why are you so much considered with the number of canvases. E.g. in Photopea, each thumbnail of a layer is a HTML Canvas element. Photopea often shows hundreds or thousands of canvas elements simultaneously.

**Comment by kamild706** [comment]
Well, all is clear now. Thank you for your time.
