### ISSUE TITLE
Inverted numbers

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1318]
It is only me?

But i am having this weird behaviour, where numbers on the ruler and zoom are upsidedown.

Please check this video:

[Apr 2, 2019 12_55 AM.zip](https://github.com/photopea/photopea/files/3032310/Apr.2.2019.12_55.AM.zip)
![image](https://user-images.githubusercontent.com/11801254/55376902-ef925000-54e8-11e9-9664-62610b09bd3f.png)

**Comment by photopea** [comment]
Hey Alvaro, I think I saw this bug once in the past. It is a bug in a WebGL of your browser :( Did you update it recently? Can you update it again?

**Comment by photopea** [comment]
So it seems like it is a bug in Chrome Beta and I can not do anything about it :( Please, report only bugs in stable versions of browsers.

**Comment by avagp** [comment]
I updated the channel yesterday to have stable.

Today I will try and see. Then report to you

**Comment by avagp** [comment]
In the stable channel it works.

So probably was the WebGL or something realted.

:)

**Comment by photopea** [comment]
I have often seen a bug, that is always in Beta channel, but never gets to a stable channel :/
