### ISSUE TITLE
Can't open EPS file

### ISSUE THREAD

**Issue by aokocax** [photopea/photopea#1320]
I have tried open this file http://videouret.com/images/75290.eps but nothing happened.
Thank you.

**Comment by photopea** [comment]
Hi, Photopea can not open this file as AI file, and it seems to be too complex for our EPS parser :(

Please, use some online service to convert it into a PDF, and open that PDF in Photopea.

**Comment by aokocax** [comment]
Thank you for replying fast, I will try it :)
