### ISSUE TITLE
Polygonal lasoo tool - shortcuts work when creating a selection

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1322]
Now in Photopea many shortcuts (ctrl + z, ctrl + a, ctrl + t) work when user makes  selection with polygonal lasso tool.

I don't know how that worked before, but hope, that is not a bug after solve that issue #1310  :)

**Comment by photopea** [comment]
Hi, I think it always worked that way, but nobody tried it before yet :)

I fixed it, if you do such step, the current tool is "cleared".
