### ISSUE TITLE
Backspace in Polygonal Lasso Tool when user use alt to togle to normal lasso

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1323]
It is funny but I don't know... it is bug... or new great Feature :D

Now it is possible to use backspace to undo last steps (many little ones), when user switch to free hand lasso tool (with Alt in Polygonal Lasso Tool). In Photoshop that's not work in that way (even more - when you switch - you cant undo with backspace any of steps).

I'm confused, because it is a first time when I don't know which option is better for the user :) 
So many steps stored in memory isn't a problem for Photopea?

Maybe, in case like this one (maybe not now but in the future), you should ask users in Facebook poll, which method they prefer? ;)

**Comment by photopea** [comment]
Well, each step in lasso has like 4 bytes :) so if you have 4 GB of RAM, you can store 4 billions of steps :) 

In Photoshop, Delete (Backspace) removes even tiny points drawn with Alt. So I think it works the same as PS.

You should decide what you really want, before you write an issue :D
