### ISSUE TITLE
Replace the content of a Smart Object with a script

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#1324]
It should work in Photoshop using this code

https://gist.github.com/laryn/0a1f6bf0dab5b713395a835f9bfa805c

Would be nice to make it possible in Photopea, too.

**Comment by kratosvn** [comment]
Hi @photopea did you support it for your app?

**Comment by photopea** [comment]
Hi, I think there is not enough demand for such feature, so I decided to ignore it for now.

**Comment by photopea** [comment]
It should be doable now. Here is a tutorial: https://www.photopea.com/tuts/edit-smart-objects-with-a-script/
