### ISSUE TITLE
Problem with layer ordering by dragging

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1325]
https://youtu.be/Re-TPVhxVV8

I saw that problem on 2 Macbooks (Pro and Air) and (for me) it is only on PWA version.
In Firefox work good, and in Chrome Browser (strange) it is correct too.

Newest version of Chrome.

**Comment by photopea** [comment]
Hey, can you somehow open this website as "pwa" (install it to your desktop) and try to drag-and-drop the image into the box? https://www.w3schools.com/htmL/tryit.asp?filename=tryhtml5_draganddrop

My guess is, that drag-and-drop does not work in chrome on Mac in an installed version.

**Comment by MichalSZZ** [comment]
Hi, I would like to test and help, but I don't know how to install it, without that option on W3C website... Any sugestions?

**Comment by photopea** [comment]
I think every website should have an option under Three dots - More tools - Create a shortcut? It should make a desktop shortcut.

**Comment by MichalSZZ** [comment]
Ok. I just instaled W3C drag and drop page as a PWA and problem exist there too.
That is a BUG of Chrome on mac?

**Comment by photopea** [comment]
Ok I think it is a bug in Chrome on Mac in Installed version. I will report it to Google (I have a direct email to a leader of Chrome development) and will hope it will be fixed ASAP :)

**Comment by MichalSZZ** [comment]
@photopea I only come back here, to say that something was fixed (it works now again on PWA)

**Comment by photopea** [comment]
Great, I think they did their work :)
