### ISSUE TITLE
Feature Request: RMB show context menu when using selection tools

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1327]
With Right Mouse Button in Photoshop (when you have something selected) there is easy access to many functions like:

- Deselect
- Select Inverse
- Layer via Copy
- Layer via Cut
- Transform
- Transfrom Selection
- Fill
- ...

I preffer keyboard shortcuts (not all of them from above have it - like transform selection) but one of my students has show me this option in PS and it looks interesting for newbees.

**Comment by photopea** [comment]
Hi, when you right-click the document with the Selection tools, I added the same menu, as after pressing Select at the top.
