### ISSUE TITLE
Cannot use scroll bar. It would work great if you could get that to work, otherwise its unusable.  Its probably something your aware of and I couldnt get it to work

### ISSUE THREAD

**Issue by questcns** [photopea/photopea#133]
Cannot use scroll bar. It would work great if you could get that to work, otherwise its unusable.  Its probably something your aware of and I couldnt get it to work

**Comment by photopea** [comment]
Hi, what do you mean by that? Layers and History panels have their scrollbars. In the main image area, you can scroll with a mouse wheel (Vertically, or Horizontally while holding Ctrl). You can also use Hand tool (press spacebar to switch to Hand tool at any moment). 

Do you mean scroll bar for the main image area?

**Comment by questcns** [comment]
Nope didnt work but its ok I found one of your competitors :-)  Thanks though.  Might want to look into fixin' that. 

    On Thursday, February 23, 2017 12:43 AM, Photopea <notifications@github.com> wrote:
 

 Hi, what do you mean by that? Layers and History panels have their scrollbars. In the main image area, you can scroll with a mouse wheel (Vertically, or Horizontally while holding Ctrl). You can also use Hand tool (press spacebar to switch to Hand tool at any moment).Do you mean scroll bar for the main image area?—

**Comment by photopea** [comment]
Can you let us know, what scrollbar do you miss?  Where should it be?

**Comment by questcns** [comment]
link me to the website again Ill ScreenShot it for you 

    On Thursday, February 23, 2017 2:55 AM, Photopea <notifications@github.com> wrote:
 

 Can you let us know, what scrollbar do you miss? Where should it be?—

**Comment by photopea** [comment]
you can use Photopea at www.Photopea.com

**Comment by questcns** [comment]
got it to work thanks 

    On Thursday, February 23, 2017 4:23 AM, Photopea <notifications@github.com> wrote:
 

 you can use Photopea at www.Photopea.com—

**Comment by photopea** [comment]
that is strange. By the way, what competition software do you use?
