### ISSUE TITLE
Feature request: Export as in-page canvas

### ISSUE THREAD

**Issue by mumbleskates** [photopea/photopea#1330]
In lieu of an API that would enable #1116, there could be a feature to export to a canvas element in a dialog that can be right-clicked (for "Copy image" or "Save image as..." in the context menu, dragged to another application to save or share, etc. the same way that normal web page images can.

While there is one extra step to take, this would be far faster and more convenient for quick sharing of images than the current workflow that requires first saving to a file, and could cuts several laborious steps out of the workflow for getting an image into the system clipboard.

**Comment by photopea** [comment]
I think there should be a web API for copying images into a clipboard within months.

BTW. have you tried File - Publish online (imgur)? It gives you the URL of your current file, that you can share. It is almost impossible to find such image without having the URL.

**Comment by mumbleskates** [comment]
Yeah, I know that all these things may happen... but the ability to quickly right click -> Copy image and paste in a private chat somewhere would be invaluable. Posting to imgur is rarely what I actually want to do with an image I'm making, as common as it surely is among the general user base.

**Comment by mumbleskates** [comment]
(There also exist occasional applications that understand drag & drop image from browser better than they understand paste-from-clipboard!)

**Comment by photopea** [comment]
So currently, we woulld have to do something like this: You press File - Prepare for copying. A new window appears with the actual <img> element with your image. You right-click it and choose Copy Image (that is done by a browser), and you close that image.

So you would have to do a click on File, click on Prepare for copying, third click to right-click, fourth click on Copy Image, and the fifth click to close that window.

Now, you can do File - Export As - PNG - Save, which is only four clicks. Also, I really doubt many people would use "Prepare for copying", as it is quite complex and I see no easy way to explain it to average users.

**Comment by mumbleskates** [comment]
I understand it is fast and easy to export as PNG. This is necessary and good! However, here's an example workflow, click by click, to copy to clipboard right now:

1. click on File
2. click on Export as...
3. click on PNG
4. choose location to save file and click Save
5. DRAG the downloaded file from the download panel to a new tab
6. right click on the image in that tab
7. click Copy image
8. close the new tab

...and now I have a file lying around somewhere I will likely eventually want to get rid of.

I understand there may be an apparent low incidence of this use case, but I'm not convinced about the timelines of upcoming alternatives either. People have been expecting the image-to-clipboard API to show up soonish for [at least seven years](https://content.pivotal.io/blog/you-cant-yet-programmatically-copy-an-image-to-the-clipboard-from-a-javascript-web-app) now :(

I wouldn't request a feature like this if it did not seem very viable to implement, and I hope you will consider. Thanks for your time and for making such an excellent product.

**Comment by photopea** [comment]
I fully understand what you mean. I just contacted a leader of Chrome development and I received an answer, that they work on it and it should be available in M75 (so like in a month or two). 

It is tracked [here](https://bugs.chromium.org/p/chromium/issues/detail?id=150835&q=proj-fugu%20-proj-fugu-efforts&sort=pri&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified).

So I will close it for now and then implement it ASAP. Actually, we will unify a local Photopea clipboard with a system clipboard, so you can copy anywhere and paste anywhere :)

**Comment by mumbleskates** [comment]
Hey, super cool to hear! If it's that soon this sounds good to me :+1:
