### ISSUE TITLE
Need image to be 300 DPI. Won't export as such.

### ISSUE THREAD

**Issue by marinamaee** [photopea/photopea#1331]
I'm needing to export an image with 300 DPI at the very least for printing purposes. I'm trying to send them over to a printing company that will be using the image as table runners after converting the image to an EPS file. However, they are needing the image to be 300 DPI at the very least to begin with and I haven't been able to change the photos DPI in the slightest (as it will only export as 1 DPI or 72 DPI at the highest). Please get back to me regarding this in a timely manner! I'd really appreciate it, thank you.

**Comment by photopea** [comment]
Hi Marina, in what format are you exporting your image?

If you save it as PSD, PNG or JPG, the DPI should correspond to the DPI you see in Photopea (Image - Image Size).

**Comment by marinamaee** [comment]
I'm exporting my image as a PNG. I've even tried saving it as a JPG and TIFF but every time the DPI wouldn't stay the same.

**Comment by photopea** [comment]
How do you check the DPI of a PNG image, that you saved from Photopea?

**Comment by marinamaee** [comment]
After right clicking the photo in my saved files, I inspect the properties
and details.

**Comment by photopea** [comment]
I think there is a bug in your image inspector program. It shows the DPI of 72 to all PNG images. Or have you found a PNG, for which your program show a different value than 72 DPI?

**Comment by marinamaee** [comment]
The problem with that conclusion, however, is that I've had three different
people inspect the image as well using different computers. All 3 never saw
the DPI change from a low resolution nor did they see the image change to
300 DPI after I set it to be such. Would you mind expanding on your last
question?

**Comment by photopea** [comment]
Can you send me your PNG to support@photopea.com ? 

I just tried to export a PNG from Photopea at 300 DPI. Then, I opened it in Photoshop, and then, in Photopea. Both show, that the PNG is 300 DPI.

PNG files rarely contain DPI information , and I think 99% of software can not read DPI from PNG files. But Photopea and Photoshop can read and store DPI in PNG.

**Comment by marinamaee** [comment]
I can absolutely do that!

**Comment by photopea** [comment]
I just replied to your email. It seems like you did not change the DPI at all. It should be cahnged manually in the Image Size window, as described here: https://www.photopea.com/learn/image-size
