### ISSUE TITLE
Feature Request: Sharpen Layers

### ISSUE THREAD

**Issue by slowmoed** [photopea/photopea#1332]
So, just a feature request! I work with gifs a lot and have to resize them, making them lose some sharpness. I was wondering if there would be any way to add an "add adjustment layer" feature where you can add a sharpening layer that adds the sharpening effect to the layers beneath it? Or the ability to sharpen folders? Thank you!

**Comment by photopea** [comment]
If you select multiple layers (e.g. click on the top one, hold Shift and click on the bottom one), you can apply some filters, and all these filters will be applied to all selected layers.

In general, Filters are much harder to compute than Adjustments, that is why there are no "filter adjustments layers".
