### ISSUE TITLE
text?

### ISSUE THREAD

**Issue by littlemisspond** [photopea/photopea#1333]
the text feature isn't working anymore?
like, I try to type in text and it just stops at the loading bar and doesn't even show the text I type in?

**Comment by photopea** [comment]
Hey, we updated our text rendering engine yesterday, so that is probably a reason of the bug :(

I think I just fixed it. Could you please try it again? But it seems like this bug happened only sometimes, and I don't know what exactly caused it.

**Comment by littlemisspond** [comment]
I just tried again and it wouldn't work. Text worked on mobile, but refuses to show up on laptop?

**Comment by photopea** [comment]
Can you update your browser somehow? Do you see any errors in Web Console?

**Comment by littlemisspond** [comment]
No. I am using Microsoft edge and I don't think I have Web Console??

**Comment by photopea** [comment]
You can right-click the page, choose Inspect Element, and then, switch to a Console. Are there any messages?

Can you also try another browser? Are you sure you are using the latest Edge?

**Comment by littlemisspond** [comment]
HTML1300: Navigation occurred.
www.photopea.com (1,1)

Service worker active

supp ValueImpression

Extra parameter Spcn

Powered by AMP ⚡ HTML – Version 1903281741200 https://www.photopea.com/
amp4ads-v0.js (555,34)

SEC7111: HTTPS security is compromised by http://ads.betweendigital.com/sspmatch-iframe
www.photopea.com (1,1)

SEC7111: [Mixed-Content] The origin 'https://www.photopea.com' was loaded in a secure context but tried to load an insecure document resource at 'http://ads.betweendigital.com/sspmatch-iframe'.

Emily: failed checking if already ran: SecurityError

**Comment by littlemisspond** [comment]
this is what i got?

**Comment by littlemisspond** [comment]
also, i am using the latest edge, i just checked. unfortunately, i cannot use another browser.

**Comment by photopea** [comment]
Do you have any browser extensions? Can you try to disable them? Or try Photopea in Incognito mode?

**Comment by photopea** [comment]
Also, try to reload Photopea multiple times, like F5, Shift + F5 ... there is a chance, that your browser has an old version in cache memory.

**Comment by photopea** [comment]
So I just realized there really was a problem even in the modern Edge browser. I fixed it and it should work well now.

I am sorry for not noticing it earlier. Too bad Edge is not available for Windows 7, which I use :(
