### ISSUE TITLE
Feature Request: Magic eraser

### ISSUE THREAD

**Issue by tyronx** [photopea/photopea#1334]
The one from photoshop is extremely helpful to cut out images from a background

**Comment by photopea** [comment]
Looks like it is just a Magic Wand, that immediatelly clears what you select. Isn't it simpler to combine the Magic Wand + the Delete key on the keyboard?

**Comment by tyronx** [comment]
It also had antialias which made the edges smooth

**Comment by photopea** [comment]
Magic wand should also create smooth edges, as if Antialias was always on. I really prefer combining existing tools instead of creating tons of new tools, so I will close it now.
