### ISSUE TITLE
Feature Request: Layer mask

### ISSUE THREAD

**Issue by tyronx** [photopea/photopea#1335]
The ability to edit the alpha mask would be super useful.

**Comment by tyronx** [comment]
Ow, is that the raster mask?

**Comment by photopea** [comment]
The transparency is stored both in a layer, and in its mask (it is combined when displaying). You can edit the layer transparency e.g. with an Eraser, or with Edit - Clear. You can edit a mask as a simple grayscale image, see here: https://www.photopea.com/learn/masks
