### ISSUE TITLE
Can't open psd

### ISSUE THREAD

**Issue by sweetkikky** [photopea/photopea#1336]
I like making these coloring PSD files (kinda like color filters) and Photopea allows me to put these in animated GIF's 
And this works fine with the PSD files i downloaded from Deviantart, but when i want to put my own PSD in the program glitched out. 

At first it would open but the file was invisible (i couldn't see any images) And if i tried to copy the filter layer on my image or GIF it would freeze the program and i had to refresh it. 

Now when i try to open my PSD file it gets stuck on the loading screen.
I use Affinity Photo to create my PSD files, but it has the same exporting as Photoshop.

I tried to make the file very small (60 kb) but it still won't open. Is there anything i can do?

**Comment by photopea** [comment]
Hi, can you send us your PSD file to support@photopea.com ?

**Comment by sweetkikky** [comment]
Okay, i've send it.

**Comment by photopea** [comment]
Hi, I fixed it, you can work with your PSD in Photopea now. Thanks for the cooperation! :)

**Comment by sahilfarouq** [comment]
Hello, I can’t seem to open my psd file in a Photopea , can I get some assistance please, thanks.

**Comment by photopea** [comment]
@sahilfarouq Can you try steps mentioned here: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/ ?

**Comment by pepereal** [comment]
Hello, im having probles with my psd file.
When i open the file in photopea it takes longer to load and when it loads it gets frozen.
i have a file i was working on for a long time and now i cant zoom in or color it in.
May i please get some assistance with my problem, thanks.

**Comment by photopea** [comment]
Hi, please, send me your PSD file to support@photopea.com

**Comment by pepereal** [comment]
ok the psd file is sent

**Comment by photopea** [comment]
I can not open your PSD file in Adobe Photoshop or any other program. Did you make it in Photopea? If yes, please, tell us how can we produce such a damaged file ourselves.

**Comment by pepereal** [comment]
yes o dod make it in photopea.
i dont know how iz happend but it might be couse i put a gradient in 32 by 32 pixels.
i realy gope you find a way to fix the isusu, thanks

**Comment by photopea** [comment]
The file could be damaged by your browser extensions. It would really help if you can produce such PSD again, and tell us how you did it.

**Comment by pepereal** [comment]
i dont have any browser extesions that could damage the psd but i culd try making another one that will frezze

**Comment by pepereal** [comment]
i have managed to get my photo back by pasting it into a new document but if it will frezze it wull probably frezze tomorow

**Comment by stingeroff1** [comment]
Hi, I have just created a PSD file with photopea and I want to know if it is possible to open it with Adobe Photoshop cc because I don't have the software, thanks.

**Comment by photopea** [comment]
There is no difference between PSD files made by Photopea and PSD files made by Photoshop. The same goes for JPG files. If a program can open JPG or PSD file, it does not matter what software created this JPG or PSD file.
