### ISSUE TITLE
Cannot Save PSD Smartobjects

### ISSUE THREAD

**Issue by Shawnee06** [photopea/photopea#1338]
Hello there so I am trying to save Smartobjects and cannot. Can you please check into this for me. Thanks so much!

**Comment by photopea** [comment]
Hey, I just made a Smart Object in Photopea, edited it, and was able to save it back.

Could you please tell us more on what did you do? Could you share some files with us, where it happened?

**Comment by Shawnee06** [comment]
Yep so ill send u a video link of whats happening...

**Comment by Shawnee06** [comment]
Please check out this video... >>> 
https://youtu.be/YnwzxX8nLEM

**Comment by photopea** [comment]
I think I know what you mean. You used a Free Transform on a Smart Object and you could not Confirm it with a Checkmark at the top.

I think I fixed this problem. Is there any other problem?

**Comment by Shawnee06** [comment]
Nope no other problems... will try it again (and umm kudos to you all for the fast support) for realz :-)

**Comment by photopea** [comment]
Yeah, I made a big update of Photopea today (to make it start faster), and I made this mistake. I am very sorry for that. It is fixed now.

**Comment by Shawnee06** [comment]
No worries! Thanks again for the quick response..and I appreciate this app a lot
