### ISSUE TITLE
Enable PWA support for macOS

### ISSUE THREAD

**Issue by julianxhokaxhiu** [photopea/photopea#1339]
Hi,

first of all let me thank you for this awesome software you're doing in your spare time, or either full time, but for sure for free. I've been a user since a lot of months now on Windows and Linux, and I use this app as PWA.

Although I noticed that on macOS the install menu is grayed out. Could you please enable the support for it?

Google states that since Chrome 73 now PWA is enabled on all the platforms ( source https://developers.google.com/web/progressive-web-apps/desktop ), and right now I'm using version `73.0.3683.103 (Official Build) (64-bit)` on macOS Mojave version `10.14.4 (18E226)`.

Thank you in advance,
Julian

**Comment by photopea** [comment]
Hi Julian, I think we implemented PWA installation in a way it was supposed to be implemented. I can not try it out, as I don't have access to Mac OS.

Can you install any other PWAs in your environment?

**Comment by julianxhokaxhiu** [comment]
I'll try and let you know. Indeed I didn't as I personally use only your app in PWA :)

**Comment by MichalSZZ** [comment]
@julianxhokaxhiu
Copy and paste that:
chrome://flags#enable-desktop-pwas
Into your adressbar in Chrome.
Then switch "Desktop PWAs" to "enabled". Restart your browser and check it out again. "instal photopea"  should to be enabled at this time. ![Screen](https://i.imgur.com/IkTYlKq.jpg)

**Comment by julianxhokaxhiu** [comment]
Enabled the flag, works as expected. So after all, Google is not saying the total truth. Although it's available, is NOT enabled everywhere yet.

Thanks and sorry for this issue. I didn't thought to check for the flag first :)
