### ISSUE TITLE
Gradient not working in MAC

### ISSUE THREAD

**Issue by anupkum100** [photopea/photopea#1340]
Getting this console error when clicking the gradian and than selecting the gradient type from the top arrow
pp.js:6252 Uncaught TypeError: Cannot read property 'length' of null
    at fp.Cn (pp.js:6252)
    at fp.Zl.yz (pp.js:5967)

**Comment by photopea** [comment]
Hey, I am very sorry for that, I just fixed it.

It did not work anywhere, not just on Mac :)
