### ISSUE TITLE
PSD issue

### ISSUE THREAD

**Issue by ghost** [photopea/photopea#1341]
So, I was working on editing a collection of PSDs complied into a single PSD file I downloaded from a resource blog. It was fine yesterday, but whenever I open it up now, I get something like this:
<img width="1440" alt="Screen Shot 2019-04-12 at 2 55 32 PM" src="https://user-images.githubusercontent.com/49573092/56068276-15162980-5d33-11e9-8882-555d2be0edfe.png">
On top of that, any file I open up on a new tab after this PSD makes the tabs end up being all buggy such as not being able to edit the images on previous tabs. I don't think it's too big of a file since it's 1.2 MB. It could be because I have too many layers or something? Or maybe my file got corrupted?

**Comment by photopea** [comment]
Hi, could you send me your PSD file to support@photopea.com ?

**Comment by photopea** [comment]
Hi, I fixed it, you can work with your PSD in Photopea now. Thanks for the cooperation! :)
