### ISSUE TITLE
My PSD opens but doesn't show up

### ISSUE THREAD

**Issue by iSoraa** [photopea/photopea#1342]
Hey, I'm making a little PSD icon for some people and the PSD opens but it's laggy, won't show up in the editor and you can't actually open or edit any layers. It works for my friend using proper PS so I don't think it's the file's issue? 

Thank you. 

![image](https://user-images.githubusercontent.com/49614214/56093848-4b83ae00-5ec5-11e9-9a12-5820e9fa81be.png)

**Comment by photopea** [comment]
Hi could you please send us your psd file to support@photopea.com ?

**Comment by iSoraa** [comment]
Yeah of course. I'll send it now.

**Comment by photopea** [comment]
Hi, I fixed it, you can work with your PSD in Photopea now. Thanks for the cooperation! :)
