### ISSUE TITLE
Image denoise

### ISSUE THREAD

**Issue by wangyanhui152626** [photopea/photopea#1343]
**I need make image denoise,but photooea have no this function**

**Comment by photopea** [comment]
Hi, there is a Surface Blur and the Median filter. Have you tried them?

**Comment by wangyanhui152626** [comment]
> Hi, there is a Surface Blur and the Median filter. Have you tried them?

I can't find it [cry]

**Comment by wangyanhui152626** [comment]
> Hi, there is a Surface Blur and the Median filter. Have you tried them?

Thank you ,I can find it

**Comment by photopea** [comment]
I think those work quite well, if you find right parameters. I will close it for now.
