### ISSUE TITLE
Free Transform issues

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1346]
1. When doing Free Tranform I write in top toolbar in X and Y fields some number to change position. It changes position correctly but after I change also W and/or H fields to change width and height it suddenly jumps and resets position of my previously set X and Y offset.

2. When I accidently write zero in W or H fileds I cannot change it back by writing another number there. It just stays zero size and I need to cancel it and start Free Transform again.

**Comment by photopea** [comment]
Hi, I fixed it, thanks!
