### ISSUE TITLE
Impossible to insert guides by dragging in Firefox

### ISSUE THREAD

**Issue by blaberus** [photopea/photopea#1347]
Unfortunately nothing happens when dragging with Move tool from the ruler to the working area — in Firefox on macOS. But it works good e. g. in Opera. Thanks :)

**Comment by photopea** [comment]
Hey, are guides enabled in your case? Look at View - Guides .

**Comment by blaberus** [comment]
I'm so sorry. Trouble was not in View - Guides, but in View - Extras. This menu doesn't seem very intuitive. Are guides part of extras? Perhaps it would be better to move a bit all the points under Extras to the right? Or make Extras point bolder? Anyway your service is great, thank you.

**Comment by photopea** [comment]
If you uncheck View - Extras, the View - Guides, View - Grid and others become unclickable.

Extras is for showing / hiding all these four items at once.
