### ISSUE TITLE
Canvas is diferrent from the displayed canvas

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1349]
I have a file. If i resize the canvas, the visible canvas does not adjusts, so, when moving layers, they dissapear to the actual canvas limits.

Here a video showing:

[Apr 19, 2019 10_00 AM.zip](https://github.com/photopea/photopea/files/3098325/Apr.19.2019.10_00.AM.zip)

**Comment by photopea** [comment]
Hi, this is related to the problem with artboards, which can not be edited at the moment: https://github.com/photopea/photopea/issues/964 . In the future, the canvas size will adapt to the boundaries of all present artboards.
