### ISSUE TITLE
Site Down?

### ISSUE THREAD

**Issue by GregoryTheGamer** [photopea/photopea#1355]
Hello, when ever I try to access the site it says "The site can't be reached" could you guys look into this to see if the site is offline right now? I've tired several things to no avail.

**Comment by photopea** [comment]
Hi, there is some DDOS attack going on at our hosting provider. We are trying to analyze it.

**Comment by GregoryTheGamer** [comment]
Alright thanks for letting me know hope you can get it sorted out soon!

**Comment by photopea** [comment]
There are hundreds of people using Photopea right now. So I think it does not work for like 5 minutes in each hour (but hard to say when :/ )

**Comment by photopea** [comment]
Hi, it should work now.
