### ISSUE TITLE
Keeps filling a shape when I have it on don't fill

### ISSUE THREAD

**Issue by CrazyCorbeau** [photopea/photopea#1356]
the title kinda explains it
it keeps filling my shape when I don't want it filled

**Comment by photopea** [comment]
Hi, what keeps filling your shape? When?

**Comment by CrazyCorbeau** [comment]
few moments ago,I'd have it so the shape couldn't be filled and then once I made the shape it was filled,I'd turn it off again then make the shape and it'd be filled again

**Comment by photopea** [comment]
I see. When there is no shape, and you set that you want an empty shape, the new shape is still drawn Red.

**Comment by photopea** [comment]
I think I fixed it. Thanks for reporting it!

**Comment by CrazyCorbeau** [comment]
thank you!!
