### ISSUE TITLE
Converting shape to smart objet fill it and if undo, it makes other disappear!

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1357]
Open this file:
[Logo Mala Leche.zip](https://github.com/photopea/photopea/files/3110584/Logo.Mala.Leche.zip)

Convert all to smart object.

The eye of the character should turn black.
![image](https://user-images.githubusercontent.com/11801254/56632990-4db6dc80-662a-11e9-846c-3f0f9feb16be.png)

Undo the action

Now the lines will dissapear
![image](https://user-images.githubusercontent.com/11801254/56632982-4394de00-662a-11e9-854e-e982b19a423f.png)

**Comment by photopea** [comment]
Hi, I fixed it! Note, that now, a special action may be added to a history, about splitting the open paths in one layer into multiple layers with a single open path in each of them.
