### ISSUE TITLE
Font wont keep on Photopea after loading it on my account

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1358]
I am assuming a lot here, but i have loaded a lot of fonts, and they are kept on my photopea's account after closing it.

But this font: Poplar Std i have uploaded a thousand times, but everytime i need to upload it.

Is that font in particular or something i am doing wrong?

Or is a bug?
[poplar-std (1).zip](https://github.com/photopea/photopea/files/3110593/poplar-std.1.zip)

**Comment by photopea** [comment]
Hi Álvaro, Photopea does not store any files after you close it. It only stores basic settings, such as foreground/background color, enabled panels, grid size, current language ... these data are small (100-200 bytes) and fit inside Cookies.

So my guess is, that all your fonts are already present in Photopea, except Poplar, which is not free for commercial usage. 

I thought about making Photopea store your own presets (fonts, brushes, patterns, gradients, shapes ...) in your computer (you would have to give it a permission). But such storage would be available only on a certain device, and will not be available elsewhere, even if you log in to Photopea. What do you think?

**Comment by avagp** [comment]
About the font, you may be right, probably they where there even before
uploading them.

And about the addition, Good idea.

Of course is great to use photopea anywhere, but in practice I have one
device where I tend to do all the hard work, I will probably store it in
there.

Or maybe, you can use Google drive to store that kind of data as well?

**Comment by photopea** [comment]
Hi, I added an option to store your fonts (and other files) in Photopea even after closing. https://blog.photopea.com/photopea-4-2-with-local-storage.html

**Comment by avagp** [comment]
You are wonderful you know :D
