### ISSUE TITLE
Text align is working weird.

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#136]
How to trigger it:
Type a word.
Then select some alignment setting, not the left one.
The text goes to the left if you selected center, and far left if you selected right.

Left alignment:
![screenshot 2017-02-25 at 23 10 35](https://cloud.githubusercontent.com/assets/11801254/23336449/aa58d4ee-fbaf-11e6-8b37-db46bfdbd982.png)
Center alignment:
![screenshot 2017-02-25 at 23 10 42](https://cloud.githubusercontent.com/assets/11801254/23336448/aa58710c-fbaf-11e6-9031-bb2a06e9633a.png)
Rigth alignment:
![screenshot 2017-02-25 at 23 10 48](https://cloud.githubusercontent.com/assets/11801254/23336450/aa595cd4-fbaf-11e6-854f-d7c823613c6b.png)

**Comment by photopea** [comment]
Hi. This is the correct behavior of type layers in a PSD format. There are two kinds of type layers: type 0 (with the single origin point, no boundaries, you create it by clicking somewhere) and type 1 (with a rectangle, that defines a boundary, you create it by pressing the mouse and dragging). 

In type 0, if you put the origin to some place and align the text to the right, all text should be on the left side of the origin (aligned to the right).  Create multiple lines to see how it works.

**Comment by avagp** [comment]
I didn't know that. Sorry for bothering you with my ignorance issues  :/
