### ISSUE TITLE
Making selection from layer thumbnails - subtract and intersect

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1360]
Now it is possible to load selection from layer by clicking with ctrl on thumbnail.
Next step: ctrl + shift on other layer make combination (unite) from that two selections.
That works good.

I miss two other methods:

- Ctrl + Alt: make subtract from selection that was made before
- Ctrl + Alt + Shift: make intersect with selection that was made before

**Comment by photopea** [comment]
It was implemented! Not only for layer thumbnails, but for masks, too.

Also, you can record these operations as Actions, and play them later.
