### ISSUE TITLE
BUG in transforming width of rounded rectangle

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1361]
Make rectangle with 2 rounded corners.
Try to make small width like in that movie:
https://youtu.be/gqSgCwKpcwI
Position of 2 rounded corners are fliped 90 deg

**Comment by photopea** [comment]
Hey, this is a very interesting bug! :D I just fixed it.

I don't think it is right to rewrite corner radii during the free transform. Photopea dos not change actual values, but they are decreased in the rendered shape (if needed).
