### ISSUE TITLE
Rasterize Layer Style Bevel and Emboss - Texture

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1364]
When doing Rasterize Layer Style on layer with texture set in Layer Style section - Bevel and Emboss - Texture -> texture disappears (is not rasterized)

**Comment by photopea** [comment]
Hi, I fixed it! Thansk for pointing it out :)

**Comment by hxim** [comment]
Hello I just tried it and offset of such texture is slightly wrong after you do Rasterize Layer Style.

**Comment by photopea** [comment]
Hi, I was aware of this problem, but I was too lazy to fix it, I thought nobody would mind.

I am very sorry. I think I fixed it properly now.
