### ISSUE TITLE
Mac OS, Safari - selection and guidelines remain on the screen

### ISSUE THREAD

**Issue by leaptrotaj** [photopea/photopea#1365]
Marks like guidelines and selections are persistent in Safari until a new step is taken that affects the canvas or layers (such as creating a new layer). The marks are ghosts only, but can be confusing for new users.

**Comment by photopea** [comment]
Hi, are you using the latest Safari? If not, can you please update it? Is it in other browsers, too?

**Comment by leaptrotaj** [comment]
I am on the latest version. This occurs on all Mac computers I’ve tried if using Safari, though other browsers did not have the issue.

**Comment by photopea** [comment]
Can you please show us a screenshot? Or make a short video?

What exactly version of Safari are you using?

**Comment by leaptrotaj** [comment]
Here is a short video. Using Safari 12.1 on a MacBook Air. This problem is duplicated across all MacBook's I've used (my students have them), but I did try my iMac last night (Safari 12.1) and the problem was not present.
[Photopea Glitch.zip](https://github.com/photopea/photopea/files/3122091/Photopea.Glitch.zip)

**Comment by photopea** [comment]
Can you try to do More - Use WebGL (uncheck that option), does the problem still persist?

**Comment by leaptrotaj** [comment]
That did the trick. Thanks!

**Comment by photopea** [comment]
We need to make it work with WebGL on. Photopea will be very slow without WebGL. 

@MichalSZZ can you try it yourself? Does it happen to you too?

**Comment by MichalSZZ** [comment]
@photopea 
Yes, for me too. (Without WebGL is OK)
Safari 12.1. Mac Book Pro with Retina.
But I'm still on High Sierra OS (FYI)

**Comment by MichalSZZ** [comment]
@leaptrotaj  on your iMac what kind of graphic card do you have?

**Comment by leaptrotaj** [comment]
Radeon Pro 560 4 GB

**Comment by photopea** [comment]
@MichalSZZ do you know any WebGL programming? Could you crate a small case, where this bug happens, so that I could report it to WebKit developers?

**Comment by MichalSZZ** [comment]
@photopea no, I'm "only" frontend developer (without JS skills) and graphic designer. Unfortunatly - no programing skills :(

I asked about graphic card, because in macbooks (pro, air etc.) there are "on board" cards like Intel Iris. iMac have dedicate card like Radeon and if there work on same OS and browser, I guessed that there might be a problem

**Comment by photopea** [comment]
I reported it to WebKit authors: https://bugs.webkit.org/show_bug.cgi?id=198039

In the meantime, I would suggest you to use a different browser.
