### ISSUE TITLE
Selection is in wrong place when selecting on Pixelbook

### ISSUE THREAD

**Issue by shawntabai** [photopea/photopea#1366]
When drawing a selection on my Pixelbook, the selection is drawn in the wrong place, making it difficult to use correctly. This appears to apply to all selection tools (rectangular, ellipse, lasso). When I'm done selecting, the selection is made in the correct place; but while trying to draw it, the dotted lines showing me what's happening are in the wrong place.

Screen capture video showing this:
https://drive.google.com/file/d/1JXb01xJXyNOyq5ideKZ2QGkK5k5M0NT3/view

**Comment by photopea** [comment]
Hi, this is a bug in Chrome OS Beta. https://github.com/photopea/photopea/issues/1359  . We reported it to Google and hope it will be fixed soon.

If you want Photopea to work, use a standard modern browser.

**Comment by photopea** [comment]
https://www.reddit.com/r/chromeos/comments/bh1a4h/is_photopea_broken_on_chrome_os/
