### ISSUE TITLE
DPI

### ISSUE THREAD

**Issue by Owwie** [photopea/photopea#1368]
I export the image at 300dpi, but when I open it, it's a 72dpi image.
I need it to be 300dpi for printing and such.

**Comment by photopea** [comment]
Hi, you say "when I open it, it's a 72dpi image" - how do you open it? Maybe the program you use to open it can not detect the DPI properly.

Photopea should store correct DPI inside PNG and JPG, but not in TIFF at the moment. What format do you use?

**Comment by Owwie** [comment]
I used photopea to open it. The resolution is bad as well, it's clearly not
300dpi.

**Comment by Owwie** [comment]
Hi,
I used photopea to open it. The resolution is bad, it's clearly not 300dpi.
I saved it in TIFF, but then I tried PNG as well, and it's the same issue.

**Comment by Owwie** [comment]
Hi again,
Just wanted to let you know that the issue has been fixed.
Thanks!

**Comment by photopea** [comment]
Hi, I fixed the problem with TIFFs. Now, the DPI information is preserved when you both open and save TIFFs.
