### ISSUE TITLE
File > Export As... only allows 1 export, then I have to reload app

### ISSUE THREAD

**Issue by FitSpur** [photopea/photopea#1369]
After exporting 1 image (e.g. png), then I can't export anymore.  And I can't close the PSD file to load it again, I have to close the app, relaunch it, reload the PSD file again, and I can export 1 image again.  I was using the program 5-7 days ago and it wasn't doing this.

**Comment by photopea** [comment]
I am very sorry, there was a tiny bug added 8 hours ago :( I fixed it.
