### ISSUE TITLE
Suggestion: Canvas and image size should have ratios

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#137]
When resizing canvas (for facebook again) sometimes i want to change the ratios of the canvas.

Right now i have to calculate myself the fraction between height and width which contains one of my measures to get the other.

For example, i have a work width 1355 pixels wide, and i have to get a 1.91:1 ratio.
I want to crop the height of the picture, but keeping the width.
So... i do the math to get the result i need.

**Comment by photopea** [comment]
I see, what you mean. But how should the interface look like? 

There may be three items: Width, Height and Ratio. When you change Width or Height, the Ratio will be recomputed. But if you change the Ratio, which of the values should be recomputed?

Maybe when you change the Ratio, the Width should be preserved, but the height will be changed. But some people may need it to work the other way. It may be very confusing.

**Comment by avagp** [comment]
Maybe it should display the actual ratio of the pixels on width and height. So we could just play a little to get the number we need.
![screenshot 2017-02-26 at 21 1](https://cloud.githubusercontent.com/assets/11801254/23345248/c67fe760-fc69-11e6-8531-76ea57020d07.png)

I belive the second number of the ratio should ever be 1 digit interger wide, and the first one should have decimals and all. (only my mere opinion)

**Comment by photopea** [comment]
Wow, that is a brilliant idea!

**Comment by photopea** [comment]
ok, there is a label showing the current aspect ratio. Thanks for such a great idea! :)

**Comment by avagp** [comment]
Looks cool  :D




2017-03-04 7:46 GMT-03:00 Photopea <notifications@github.com>:
