### ISSUE TITLE
Uploaded font from computer not loading correctly.

### ISSUE THREAD

**Issue by nenochis-1** [photopea/photopea#1371]
Hello, I added Gill sans.ttc to photopea and it worked perfectly until a few days. Some styles are not loading correctly...
As you see below, light and regular look fine but semibold, bold and ultrabold won't load correctly.
I use this font a lot, so I would appreciate the help.
Thank you!

<img width="972" alt="Screen Shot 2019-05-06 at 7 06 34 PM" src="https://user-images.githubusercontent.com/46464895/57263196-89dc3b00-7035-11e9-8778-4cf97bfec5d6.png">
<img width="966" alt="Screen Shot 2019-05-06 at 7 08 49 PM" src="https://user-images.githubusercontent.com/46464895/57263197-89dc3b00-7035-11e9-8f88-c0c9cbaac7ab.png">
<img width="946" alt="Screen Shot 2019-05-06 at 7 06 16 PM" src="https://user-images.githubusercontent.com/46464895/57263198-89dc3b00-7035-11e9-99d9-c11598bf1fd4.png">
<img width="931" alt="Screen Shot 2019-05-06 at 7 06 08 PM" src="https://user-images.githubusercontent.com/46464895/57263199-8a74d180-7035-11e9-9f69-0d2b9a5be13f.png">
<img width="936" alt="Screen Shot 2019-05-06 at 7 06 01 PM" src="https://user-images.githubusercontent.com/46464895/57263200-8a74d180-7035-11e9-9cef-e91a211880d1.png">

**Comment by photopea** [comment]
Hi, could you send us this font to support@photopea.com ?

**Comment by nenochis-1** [comment]
Sure, just sent it.

**Comment by photopea** [comment]
Hi, it should be fixed now, thanks for reporting it!
