### ISSUE TITLE
Add preview for the Clone Tool

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#1372]
https://www.reddit.com/r/photopea/comments/blow6j/questions_regarding_the_clone_tool/

**Comment by MichalSZZ** [comment]
I asked about that (visual presentation of cloning source) in July 2018, but then that was inpossible (FF cursors) https://github.com/photopea/photopea/issues/784

Cloning angle is something new for me (i didn't know that before) but sounds great! I must turn on PS and try it!

**Comment by photopea** [comment]
It has been implemented :)
