### ISSUE TITLE
JPG is exporting as a text file called "jpg.txt".

### ISSUE THREAD

**Issue by fareskalaboud** [photopea/photopea#1373]
Using Chrome 73.0.3683.103

When trying to export an image into JPG, it's downloading a file called jpg.txt.

When actually changing the extension to jpg, the file works just fine.

**Comment by photopea** [comment]
Hi, this is really strange. Can you update your Chrome? Chrome 74 should be available today.

**Comment by fareskalaboud** [comment]
Updating to Chrome 74 seems to have fixed the issue. Thank you :)

**Comment by photopea** [comment]
That is really strange. I expected the problem to be in the OS somehow.

**Comment by gabal007** [comment]
I'm getting the same issue and my Chrome version is up to date. Version 83.0.4103.116

**Comment by photopea** [comment]
Have you tried to disable all browser extensions?

**Comment by gabal007** [comment]
Just did that. One of them was obviously causing this issue. It works now. Thanks.

**Comment by photopea** [comment]
Could you tell us the name of the extension, that was causing it?

**Comment by gabal007** [comment]
Free download manager.

**Comment by photopea** [comment]
Does that extension do anything else than renaming files to .TXT?

**Comment by gabal007** [comment]
Haven't noticed anything else. It does the same thing when I try to save a psd as well.

**Comment by photopea** [comment]
I mean, did you install it for any other reason than renaming downloaded files to .TXT?

**Comment by gabal007** [comment]
I didn't install it for this purpose. For some reason it does that, but this tool is for managing my downloads.

**Comment by aidinjk** [comment]
look guys i can still comment on this
