### ISSUE TITLE
Parameters of new shape in pop up window when user click on artboard

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1375]
https://github.com/photopea/photopea/issues/1311 
Now its work good only for rectangle and ellipse (maybe for line too, but... I will write about line below).

When you are making e.g. Parametric Shape, it should have more parameters then width and height only.

And I see some kind of bug there. Now when I choose star and click on artboard to create new one, and I set width and height to e.g. 200x600... it create star with fixed proportions but I don't know where is that 200 or 600. I don't understand how it's calculate the size of new shape.

In rectangle, corner radius (by default set to 0, but with option to set each manually - like in Live Shapes Properties) will be a "nice to have" option.

Line tool - (that is my Idea - not copied from PS) - Width, Lenght, and Angle! 
Now Photopea create new rectangle shape :D (I know that line is just a rectangle, but my properties add new value to that tool)

Custom Shape - should have "preserve proportion" checkbox. And when it is checked, it should recalculate second dimension from first one (set proportional Width of icon when I type height manually and vice versa)

**Comment by photopea** [comment]
I am afraid it is not possible. We want Photopea to work with Photoshop actions, and Photopea actions to work in Photoshop. Creating of a shape generates a new action, which should be the same as the one in Photoshop, with the same parameters.
