### ISSUE TITLE
Defined proportion in Custom Shape as a option to choose

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1377]
In Photoshop there is a 4th option to choose (defined proportion) when user create new Custom Shape (by clicking and dragging to draw new one) .

It should work like there https://github.com/photopea/photopea/issues/1362  but without shift button :) For users who can't use Shift or don't know that method.
Now Photopea have 3 options in select - "free", "fixed size" and "Fixed Ratio" but with this option you can't draw Custom shape with its oryginal proportions (e.g. fa-ellipsis-h).

**Comment by photopea** [comment]
Could you please be more specific, what are you proposing?

I think people who want to draw in original proportion, will learn to use Shift, or will be very accurate when drawing, to hit the required aspect ratio.

**Comment by MichalSZZ** [comment]
Propably you have right. Shift is the first thing that I teach my students on my lessons :)
Not everything should to be 1:1 like in PS.
