### ISSUE TITLE
Sliders of the right windows are off-placed

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#138]
If you open the right windows
![screenshot 2017-02-26 at 01 39 50](https://cloud.githubusercontent.com/assets/11801254/23337224/8020b98e-fbc4-11e6-8305-c306f0fa2a0d.png)

And if you go to the character tab at the bottom, when you select any setting that has a slider it will be displayed far off, at the top, like inside the brush demo setting. (here i was selecting tracking)

![screenshot 2017-02-26 at 01 37 00](https://cloud.githubusercontent.com/assets/11801254/23337216/54821e6c-fbc4-11e6-91fe-27b7746413dd.png)

I think is related to the limits of the canvas and the windows. The slider is displayed inside the canvas, but the window with the setting title is outside the workspace

**Comment by photopea** [comment]
Did you close the bar with the information, that apears at the top of Photopea?

**Comment by avagp** [comment]
No. I did not close it.
I got opened: info + brush + character.

Maybe is somehow related to my screen resolution?  :/

**Comment by avagp** [comment]
In this video i show you what i did.
https://drive.google.com/file/d/0BxACIQ9JCuosaVN2NFkyOVpZZHM/view

At first, i show you that the program is a little off my screen so i get a scroll bar which scrolls 2 pixels :/
then i get to the right windows to show you their behavior.

**Comment by photopea** [comment]
That looks quite bad. I expected, that nobody will open that second vertical bar. Users can open just specific panels as "bubbles".

How should be that second panel displayed when it is "expanded", when the content does not fit onto a screen?

**Comment by avagp** [comment]
Maybe something like i suggested on this issue: https://github.com/photopea/photopea/issues/139

Why no having all the tabs on the same position and be aligned as they populate the space? Like you do on the canvas side?
![screenshot 2017-02-26 at 21 46 27](https://cloud.githubusercontent.com/assets/11801254/23346128/4bd2e8de-fc76-11e6-8eef-8950c3318357.png)

For me will be more intuitive to have all the options on the same place, and no to scroll down lo certain ones. And you wont tabs on top of another, because every tab should have the proper height. Personally dont really need 2 "bubbles' at the same same time, just having one and another easilly switched.

**Comment by photopea** [comment]
I think it is pretty much the copy of #139
