### ISSUE TITLE
Transform Again and Transform Again with copy of object (keyboard shortcuts)

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1381]
Now Photopea have shortcut Shift + Alt + Ctrl + T.
In Photoshop that shortcut makes transform again with copy of a object.
Look at the second part of the movie https://youtu.be/SAboeGNgRLM
Shift + Ctrl + T is for transform again withou copy

BTW. In Photoshop when you are holding Alt and use edit -> transform -> roatate or flip, that makes transformation with copy of that object.

**Comment by photopea** [comment]
Hi, when Ctrl + T is pressed in current browsers, without Alt, it always performs a browser shortcut (so we can not use these shortcuts).

**Comment by MichalSZZ** [comment]
@photopea OK I understand that... But...

I use PWA version of Photopea, Alt there will be a problem too? Maybe only for PWA? Like ctrl+t work? 

I want to show this method to my students this week. 
What do you think to add this in menu edit - transform? If method for PWA will be not possible?

**Comment by photopea** [comment]
So Ctrl+Alt+T will start a Free Transform in a browser, but it should start a Free Transform of a copy in a PWA? I don't really like this idea, to make Photopea check, in what environment it is running, and change the behaviour. There should be only one environment - the Web environment.

I am ready to make these shortcuts correspond to Photoshop, once this Ctrl+T bug in browsers is fixed. Until then, you will have to use Ctrl+J in between :/
