### ISSUE TITLE
Add fonts support: source-han-sans & source-han-serif

### ISSUE THREAD

**Issue by Victorkangsh** [photopea/photopea#1382]
source-han-sans & source-han-serif fonts are developed by Adobe and Google for three years. It was announced in July 2014 as an open source font. This is a new open source Pan-CJK font family for desktop use. There are seven font weights ( ExtraLight, Light, Normal, Regular, Medium, Bold, and Heavy), fully supports Traditional Chinese, Simplified Chinese, Japanese, and Korean, all of which are contained in one font. It also includes Latin, Greek and Cyrillic characters from our popular Source Sans font family.

[adobe-fonts:source-han-sans](https://github.com/adobe-fonts/source-han-sans)

[adobe-fonts:source-han-serif](https://github.com/adobe-fonts/source-han-serif)

**Comment by photopea** [comment]
Hi, I added Source Han Sans and Serif. They created 14 new items in the font menu.

**Comment by Victorkangsh** [comment]
Great! Chinese characters are now displayed correctly and beautifully! 
The Noto is google fonts name for Source han, but it can't display well on photopea. So removing it is ok.
