### ISSUE TITLE
Exporting Layers but keeping the size?

### ISSUE THREAD

**Issue by enzyme69** [photopea/photopea#1383]
I tried the -e- and export layers trick. Seems to work, I can see each elements of the layers as a single file. However if I want to stack them again in another package, I have issue because they are no longer in the same dimension with each other and I cannot align them / taking sometime to do it.

Is there a trick so that the export actually save PNG and respecting the image size / dimension? So the output should be the same size?

Thanks!

**Comment by photopea** [comment]
Hi, what you mean by "stack them again in another package"? Each time you export layers, the new package is generated according to your PSD document and export options. All previous exports are forgotten.

**Comment by photopea** [comment]
I will close it because of lack of details.
