### ISSUE TITLE
.xd files aren't loaded at all

### ISSUE THREAD

**Issue by suwermave** [photopea/photopea#1384]
Whenever I try to upload .xd file in photopea, page freezing. Tested in Google Chrome and Microsoft Edge.

**Comment by photopea** [comment]
Hi, can you send us your XD file to support@photopea.com ?

**Comment by suwermave** [comment]
All XD files don't work.
[Sansung s10 concept.zip](https://github.com/photopea/photopea/files/3163513/Sansung.s10.concept.zip)

**Comment by photopea** [comment]
Hi, are you sure about that? I was able to open your XD file without any problems. What exactly happens in your case?
![image (1)](https://user-images.githubusercontent.com/15955558/57478286-d5435300-729a-11e9-8e25-d9fe07565168.png)

**Comment by photopea** [comment]
Can you please update your browser?

**Comment by photopea** [comment]
So I guess it was fixed.

**Comment by suwermave** [comment]
How Microsoft Edge can be older than 2 years. I'm using the last versions of browsers and I have this issue.

**Comment by photopea** [comment]
Microsoft Edge was released 4 years ago, so it can be older than 2 years.

When the page freezes, can you look into a Web Console and send us a screenshot of what you see in there?

**Comment by suwermave** [comment]
![image](https://user-images.githubusercontent.com/50447661/57778637-289b2280-772d-11e9-9d03-f66837ba8a14.png)

**Comment by suwermave** [comment]
![image](https://user-images.githubusercontent.com/50447661/57778989-ee7e5080-772d-11e9-82ad-ca5a246b447e.png)

**Comment by photopea** [comment]
Hi, that error message does not correspond to a current Photopea. How old is the screenshot?

Can you take a screenshot of a console from the current Photopea? Can you reaload it a few times, to make sure your browser is not caching anything?

**Comment by suwermave** [comment]
This screenshot is 3-hours old. The one that I am going to upload now is 2-minutes old. I cleared cache and refresh the page 4 times - it can't allow me to open .xd files
![image](https://user-images.githubusercontent.com/50447661/57791839-580a5900-7746-11e9-90a6-d37dd1909966.png)

**Comment by suwermave** [comment]
UPD. I am not the only person having this issue

**Comment by photopea** [comment]
This error means, that an index of a selected layer is incorrect. Is it really happening when you open "Sansung s10 concept .xd", or some other file? 

Can you try to disable browser extensions or try it in the Incognito mode?

**Comment by suwermave** [comment]
Well, it somehow works now. thanks for the useful editor, I guess?..

**Comment by photopea** [comment]
It started working just like that, or you disabled extensions?

Let us know what you don't like, we can fix it :)
