### ISSUE TITLE
Error when opening specifc sketch file

### ISSUE THREAD

**Issue by andrevabo** [photopea/photopea#1385]
If you try to open this file the editor gets stuck with a "Loading" message and this error shows up in the console:

```
pp.js:2982 Uncaught TypeError: Cannot read property 'sha1' of undefined
    at Object.ZF.Gh (pp.js:2982)
    at Object.ZF.parse (pp.js:2969)
    at Function.wY.Vz (pp.js:2551)
    at Object.ZB.SKETCH.Ht (pp.js:268)
    at Function.cM.iR (pp.js:8260)
    at cM.wNu (pp.js:8248)
ZF.Gh @ pp.js:2982
ZF.parse @ pp.js:2969
wY.Vz @ pp.js:2551
ZB.SKETCH.Ht @ pp.js:268
cM.iR @ pp.js:8260
cM.wNu @ pp.js:8248
load (async)
cM.Cn @ pp.js:8218
(anonymous) @ pp.js:8206
```

I'm not sure if the file is broken/corrupted because I don't have sketch to test it.

[file.zip](https://github.com/photopea/photopea/files/3163976/file.zip)

**Comment by photopea** [comment]
Hi, your Sketch file seems to be quite old. I fixed it and it should work now.
