### ISSUE TITLE
Spot healing tool gives black edges

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1387]
I am attaching a  PSD.

Please go to the transparent "conejo" layer.

Use the spot healing tool anywhere and see how the bunny goes with a black edge all over it, that cannot be undone.

Before
![image](https://user-images.githubusercontent.com/11801254/57595677-87398400-7514-11e9-9987-c560d854718c.png)

After
![image](https://user-images.githubusercontent.com/11801254/57595684-94567300-7514-11e9-88ba-734d9d43e9d3.png)

PSD:
[IMG_20190507_204503523.zip](https://github.com/photopea/photopea/files/3171120/IMG_20190507_204503523.zip)

**Comment by photopea** [comment]
Fixed, thanks! :)
