### ISSUE TITLE
Eraser Adjustments

### ISSUE THREAD

**Issue by BOBBYERTLY** [photopea/photopea#1389]
It would be helpful if the eraser tool made smoother marks (my smooth (option in the top bar) is 0% because the smooth thing just lags the part that gets erased behind the circle cursor) and the smooth option (the same thing mentioned before) doesn't help.

(Those bumps)

![screencapture-photopea-2019-05-13-21_22_52](https://user-images.githubusercontent.com/50558641/57664277-857bc900-75c5-11e9-9050-a910eaa0d275.png)

Thanks
(Hope this explanation makes sense)

**Comment by photopea** [comment]
Hi, I think you need to decrease the Spacing of a brush: https://www.photopea.com/learn/brush-tools

**Comment by BOBBYERTLY** [comment]
Ok, thanks
