### ISSUE TITLE
When you close the right window with the history, is closes weird.

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#139]
![screenshot 2017-02-26 at 01 44 49](https://cloud.githubusercontent.com/assets/11801254/23337243/3bb4e4ae-fbc5-11e6-99f2-70f24bab6626.png)

As you can see, the History and Layer title tabs are cut by the scrolling bar

**Comment by photopea** [comment]
You are right, it is all because of that Info bar at the top, which requires Photopea to be scrollable. I added it in a hurry, without a proper testing.

**Comment by avagp** [comment]
Why no having all the tabs on the same position? Like you do on the canvas side?
![screenshot 2017-02-26 at 21 46 27](https://cloud.githubusercontent.com/assets/11801254/23345444/17b320b8-fc6d-11e6-8b42-b5b75f3f9577.png)

**Comment by avagp** [comment]
Btw i found something while tacking the screenshot:

https://drive.google.com/file/d/0BxACIQ9JCuoseEVsUmdINmU1Tnc/view

As you can see, if you open the right windows, and then close them, the ruler on the top of the canvas will get a distosion (diagonal effect)

**Comment by photopea** [comment]
Tabs: When they don't fit into a single line, they start to appear on the next line. What other behavior would you suggest? Should they become "narrower" (hide the part of the file name)?

Ruler: I could not reproduce this bug, but I think I can fix it.

**Comment by avagp** [comment]
When i meant tabs, i meant "bubbles" (the right windows) to have the same behavoir as the project tabs: When they don't fit into a single line, they start to appear on the next line.

![screenshot 2017-02-26 at 23](https://cloud.githubusercontent.com/assets/11801254/23346401/b04f7c80-fc78-11e6-8250-fc2e405b0ad4.png)

**Comment by photopea** [comment]
These panels (Brush, Character, Tab) should be separated into subgroups. It would look confusing to put them all into a single group.

Regarding the scrollbar, that appears after unfolding the column with Info / Properties ... I think that nobody unfolds that, you can open floating panels separately by clicking their buttons.
