### ISSUE TITLE
Actions do not save with PSD

### ISSUE THREAD

**Issue by leaptrotaj** [photopea/photopea#1390]

**Comment by photopea** [comment]
Hi, actions are not supposed to be stored with PSD files. You should store them separately in ATN files.

See here: https://www.photopea.com/learn/actions

**Comment by leaptrotaj** [comment]
Am I not seeing the option to import ATN files?

Thanks

**Comment by photopea** [comment]
It is at the end of that article :D

"Press File - Open, to load the ATN file into Photopea."

**Comment by leaptrotaj** [comment]
Thank you!
