### ISSUE TITLE
Language Slovenščina isn't shown even if its translated

### ISSUE THREAD

**Issue by klemcijada** [photopea/photopea#1391]
Language Slovenščina (Slovenian) is not shown in the menu More/Language/... even if its very much translated. I have finished the translation today, please add it.

**Comment by photopea** [comment]
Hey, thanks a lot!

We update languages manually, just in case there is any vandalism (otherwise, anybody would be able to "destroy" the usage experience for everybody at any time).

I just updated the translations. Thanks again!
