### ISSUE TITLE
Suggestion: Change name before Exporting As

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1392]
I will be very comfortable to be able to change the name of the output file just before hitting save.

On the preview window

![image](https://user-images.githubusercontent.com/11801254/57824771-36bb6400-776a-11e9-8073-5f1e7a9d98ef.png)

Many times i download diferent versions of the same proyect, to only find myself opening them again to see what they are.

Also happends that the name of the project sticks to the first picture i used.

Obviously i know i can change the name of the file double clicking on the project tab, but most of the time i am already on the preview window when i remember that.  :)

**Comment by photopea** [comment]
Hi, you should be able to configure your browser, so that after pressing Save, it offers you a Save dialog (of the operating system), where you can also change the file name.

**Comment by avagp** [comment]
Yes, but by default on chrome is not ask where to save.

No savvy people like me and my coworkers tend to stick with the default
options.

Just saying...

**Comment by photopea** [comment]
I am really afraid of adding a feature, which will not be used by people, but will only make the UI more complicated :(

Really, just look into your browser settings. You can set it to ask you about the file name during each saving.
