### ISSUE TITLE
Vector mask problems

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1393]
1.) Layer-Vector Mask-Add(Show All) and Add(Hide All) seems to be swapped (Show All hides all and Hide All shows all)
2.) After I added Vector mask, unlinked it and moved layer contents it did not refresh empty space and keeps some lines from layer (see screenshot and attachment)

Open pea.psd
Merge all layers
Layer-Vector Mask-Add(Show All) --> this hides all
Add path with Free Pen
Unlink Vector Mask by clicking on chain icon
Move layer contents with Move Tool

[pea (3).zip](https://github.com/photopea/photopea/files/3185625/pea.3.zip)
![sc](https://user-images.githubusercontent.com/6370548/57830480-c6303980-77a1-11e9-819a-0c022e5ca902.png)

**Comment by photopea** [comment]
Fixed, thank you!
