### ISSUE TITLE
Color Picker issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1394]
Color Picker area has greater height in Firefox because of button in right part (button for standard color pick dialog is bigger) is wrapped on new line. Because of it white circle and line is lower than mouse cursor - see screenshots
firefox:
![s](https://user-images.githubusercontent.com/6370548/57999059-51783a80-7ad4-11e9-9659-dc0e7a1321f3.png)
chrome:
![s2](https://user-images.githubusercontent.com/6370548/57999058-50dfa400-7ad4-11e9-85b6-e2c2eb8cd059.png)

**Comment by photopea** [comment]
Ok, fixed, thanks! :)
