### ISSUE TITLE
Rasterize Layer Style with Opacity or Fill

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1395]
When doing Rasterize Layer Style on layer with Opacity or Fill (in Bledning Options) set to lower values than 100%. It does rasterize according to percentage set to Opacity or Fill but it does not reset to 100% after it. So after "Rasterize Layer Style" it is applied two times (for example if I set 50% opacity in Layer Style dialog and then apply Rasterize Layer Style it is 25% opacity as a result). I think it should reset these values to 100% or not apply Opacity or Fill during Rasterize Layer Style command at all.

**Comment by photopea** [comment]
ok, fixed, thanks!
