### ISSUE TITLE
3 dimention/ 3d

### ISSUE THREAD

**Issue by Hoodgail** [photopea/photopea#1398]
hey i would be a good idea too talk too mrdoob and making a 3d editor live mean every thing you do on the texture goes too the model using the threejs JavaScript engine . for more info about threejs visit https://threejs.org/

**Comment by photopea** [comment]
Three.js is just an engine, not a 3D editor. If any 3D editor is interested, they can integrate their editor with Photopea very easily.

I just tweeted to Clara.io : https://twitter.com/photopeacom/status/1131114003617472512
