### ISSUE TITLE
Buttons should use <button> element

### ISSUE THREAD

**Issue by cthedot** [photopea/photopea#14]
Noticed Buttons like "OK" in Blur filter use `<span class="fitem button spread">OK</span>` and not a button element. So not tabable in addition to not being accessible. Should be easy to fix?

**Comment by photopea** [comment]
It should be fixed now :) thank you for reporting it.

**Comment by cthedot** [comment]
great, thanks!

There are quite a few other elements which should be changed too though. div class="form" => form, span class="label" => label etc.

**Comment by photopea** [comment]
Is there any functionality reason to do it? :)

**Comment by cthedot** [comment]
Yes, for accessibility which depending on user is functionality 😏

**Comment by photopea** [comment]
I thought that <label> would behave (look) completely the same, am I right?

**Comment by cthedot** [comment]
Look yes, but not behave 😏

**Comment by photopea** [comment]
Can you be more specific? I always thought, that label tag does not have any extra purpose, than span element, at least in my case.

**Comment by cthedot** [comment]
There are lots of good articles about semantic html and specifically sematic html for forms on the web. They are a much better read than me trying to explain this in a few sentences. Guess buttons are the most important but labels too can be read out by e.g. A screen reader. But also most browsers focus the related (via for) input by click on a label so even for "regular" users they have advantages. Esp for smaller inputs like radios or checkboxes.

Photopea looks very advanced but you are not a frond end (html+css) type of guy really? No offense and my stuff is certainly not perfect either but there are a few things I think I learned in the last years

**Comment by photopea** [comment]
No, I am certainly not a "designer" kind of guy.

You are right, clicking on the label to highlight an input element is really a good feature. So I replaced all the spans with labels and used for - id attributes (it is updated now).

I appreciate your help very much. Do you have any other suggestions? :)
