### ISSUE TITLE
Can't open .dng

### ISSUE THREAD

**Issue by Foorie** [photopea/photopea#1400]
I've just tried to open a .dng file (approx. 25 MB) and it didn't wen through. "Loading" for minutes and minutes without any result.
<img width="1263" alt="Screen Shot 2019-05-22 at 14 43 56" src="https://user-images.githubusercontent.com/50914758/58175265-0f9bef80-7ca0-11e9-8a42-f6b0efe4ebf0.png">

**Comment by photopea** [comment]
Hi, can you please send us your DNG file to support@photopea.com ?

**Comment by Foorie** [comment]
sent now. Thanks.

**Comment by photopea** [comment]
Hi, it is because your DNG does not use a standard Bayer pattern, but an advanced 6x6 pattern, which is not supported by Photopea now.  https://en.wikipedia.org/wiki/Fujifilm_X-Trans_sensor

I will try to implement some quick solution for this.

**Comment by photopea** [comment]
Hi, I made a simple naive demosaic method for all non-Bayer patterns. Your DNG should work well in Photopea now.

**Comment by photopea** [comment]
Není zač, já děkuji za spolupráci :)

**Comment by Foorie** [comment]
FUNGUJE!
A ještě se unaveně večerně zeptám, jestli RAW editor má pouze tyhle hejblátka, co vidím (a jsou přiloženy na printscreenu).

Děkuju, Jitka

______________________________________________________________

**Comment by photopea** [comment]
Bohužel žádný screenshot nevidím :( Github to neumí přes email, musíte přímo přes stránku.

Photopea zatím nemá tolik RAW funkcí, jako jiné editory. Jaké funkce konkrétně vám chybí?

**Comment by Foorie** [comment]
No, pět veličin se tam dá ovládat, je to tak? 
Chybí mi "highlights", "shadows", "clarity" - coby základní. 
Ale jestli on mi nechybí jeden dlouhý kvalitní spánek nejvíc:-)

Doporučila jsem Photopea svým studentkám a to i na editaci RAWu (NIKON a CANON formáty), tak přemýšlím, jestli jim to bude stačit.

Jitka

______________________________________________________________

**Comment by photopea** [comment]
Spousta věcí jde upravovat až kliknete na OK, pak tam máte např. Image - Adjustments - ....

**Comment by Foorie** [comment]
Koukám na to. Tyhle úpravy kopírují tytéž v Photoshopu, když se "opustí" raw editor a nebo když se prostě otevře JPG soubor rovnou. 
Pro vykreslení světel a nebo vytažení informace z tmavých míst to ale není úplně ono.
Ale děkuju, budu si s tím hrát.

Vy jste dobrej blázínek, naprogramovat Photoshop do browseru:-)

______________________________________________________________
