### ISSUE TITLE
Only one color in stroke blending mode

### ISSUE THREAD

**Issue by joshmorel** [photopea/photopea#1401]
I even added a color to swatch but there is only red

![Photopea-only-one-stroke-color](https://user-images.githubusercontent.com/10546720/58181678-3810f300-7c7a-11e9-86a9-ec03299198df.png)

**Comment by photopea** [comment]
Hi, you should press on the label "Stroke" to see more options of this layer style. https://www.photopea.com/learn/layer-styles

**Comment by joshmorel** [comment]
Oops I see now. I thought it had accessed Stroke menu when I toggled it on.
