### ISSUE TITLE
Fonts not displaying properly

### ISSUE THREAD

**Issue by ymmat423** [photopea/photopea#1402]
Through the Chrome browser on Windows 10, fonts are not displaying properly. The other day I used one font: Tsay Mono, and today couldn't find it. So, tried some other similar ones and fonts do not look like the 'Preview' from the drop-down menu?

**Comment by photopea** [comment]
Hi, I think there is some old version of Photopea cached in your computer. Try to reload Photopea webpage several times.

If it continues, could you please tell us, which font does not look as the Preview? I think we never had Tsay Mono font :/

**Comment by ymmat423** [comment]
Okay - that was the name I had written down for the font used the other day.
I reloaded the webpage about 10 times. And as for which fonts don't look like Preview: any that I've been trying to use as a test font!

**Comment by ymmat423** [comment]
I reset Chrome's cache. Problem solved!

**Comment by photopea** [comment]
Great! :)
