### ISSUE TITLE
Brush / Pencil cursor size not updated

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1404]
Brush / Pencil cursor size is not updated after I zoom in/out with ALT+mouse wheel.
It is only updated after I start painting with it.

**Comment by photopea** [comment]
Fixed :)

**Comment by hxim** [comment]
Hello I noticed same problem (cursor size is not updated after I zoom in/out with ALT+mouse wheel)  happened to me also with Eraser and Spot Healing Brush.
It happens also with other tools like Blur Tool, Sharpen Tool and similar. Can you fix that too?

**Comment by photopea** [comment]
fixed, thanks!

**Comment by hxim** [comment]
Hello. I found one more situation when cursor size is not updated - when I zoom in/out by moving slider (or writing number) in Navigator window.
