### ISSUE TITLE
Duplicate layer not working

### ISSUE THREAD

**Issue by BrofistKittycat** [photopea/photopea#1408]
When selecting "Duplicate layer" from the menu, it does not duplicate only the selection, it does the whole layer. The hotkey Control + J still works, but would not be possible on mobile.

**Comment by photopea** [comment]
Duplicate Layer should duplicate a layer, not the selection.

To copy a selected content into a new layer, try Edit-Copy, Edit-Paste (or Ctrl+C, Ctrl+V).

There are many things impossible to do on touchscreens :(
