### ISSUE TITLE
Paid for Premium, but not showing in my account

### ISSUE THREAD

**Issue by diorist** [photopea/photopea#1409]
I submitted a Paypal Payment yesterday. The service response was a name-not-found error (similar to login with GitHub). Paypal verifies the payment was sent, but I still don't have Premium account features. What's my next step?

**Comment by photopea** [comment]
Hi, are you able to log in? You should not be able to pay for anything, if you did not log in.

**Comment by diorist** [comment]
Yes, I can log in. 

If you need it, I can share identifying info for all involved accounts (photopea, gmail, PP) -- of course, not on a public issue board.

**Comment by photopea** [comment]
So where did you see "name-not-found", if you can log in? If you send us your email address and your name to support@photopea.com , I will look into it.

**Comment by diorist** [comment]
The payment process (not login process) seems to have thrown the error. It was, at the hand-off from Paypal back to Photopea. I was logged in. 

When I reloaded Photopea (still logged in), my account registered as Premium. Today I logged in from a different browser and I'm back to seeing ads.

**Comment by photopea** [comment]
If you tell me your PayPal email or name, I will try to find, what is the reason of your problems.

**Comment by photopea** [comment]
So does it work now? If not, can you tell us anything about yourself (like name, email, paypal email ...) ?
