### ISSUE TITLE
program is locking up

### ISSUE THREAD

**Issue by Centurion2016** [photopea/photopea#141]
i am trying to use the new heal function but each time i try to the program locks and i cant even close it i have to use task manager to close it... the pic i am using is 1024 x 1024

**Comment by photopea** [comment]
Hi, we are aware, that these tools are quite slow. Did you try to wait for 5 - 10 seconds? 

Can you send us your image and steps to reproduce the problem?

**Comment by photopea** [comment]
I have to close it because of the lack of details :(
