### ISSUE TITLE
Layer Style dialog styles issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1410]
1. open pea.psd
2. open Layer Style dialog for layer "Welcome"
3. click on "Define New" button
4. click on "Satin" label
5. open list of saved styles (under Define New button) and select style you just added
-> Now you have Satin options visible but checkbox is now unchecked and all values are empty
6. click to "empty" Contour
-> Error

**Comment by photopea** [comment]
I fixed it. When a newly applied style does not contain a currently active effect, it is switched to Blending Options (top item).
