### ISSUE TITLE
Errors when no layer is selected

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1412]
1. Open pea.psd
2. Deselect all layers (Move Tool, turn on Auto-Select, click outside of image)
3. 
- Press any number on keyboard (for example "1") -> error
or
- click PNG SVG buttons on toolbar -> error
or
- Menu - Layer - Duplicate Layer -> error
or
- Menu - Layer - New - Layer via Copy-> error
or
- Menu - Edit -Cut -> error

**Comment by photopea** [comment]
Fixed, thanks! :)
