### ISSUE TITLE
Color Range Not Detecting Green Screen 

### ISSUE THREAD

**Issue by Blessyourself** [photopea/photopea#1414]
I've been using Photopea for awhile now, and just recently the Color Range tool hasn't been detecting the green screen background. It's always worked in the past. Usually when i increase the fuzziness to 100% it clears out any unwanted green background color, but it isn't doing so anymore. Am I now doing something incorrectly, or is it just a bug? 
![New Project](https://user-images.githubusercontent.com/51026988/58371384-7c98ca80-7ed6-11e9-905c-5bd40e0cc070.png)

**Comment by photopea** [comment]
Hi, I changed the default settings to the old settings.

Note, that during the Color Range, you can click into image to select the main color, that should be selected.  https://www.photopea.com/learn/advanced-selecting

**Comment by photopea** [comment]
BTW. after you select the background with a Color Range, press Select - Inverse, Select - Refine Edge, confirm with OK. You can remove the green completely from around the o
![image (1)](https://user-images.githubusercontent.com/15955558/58372044-29476c00-7f18-11e9-86f6-4189f302118d.png)
bject :)

**Comment by Blessyourself** [comment]
thank you so much!
