### ISSUE TITLE
Font issue? 

### ISSUE THREAD

**Issue by vonbreek** [photopea/photopea#1415]
Recently I have found that when I use fonts on Photopea the font that I have chosen isn't translating to what I am typing. Virtually none of the fonts work for me and I don't know whether it's an issue on my end or not. 
I have attached a screenshot from something I was working on to better showcase the issue. 
![2019-05-26](https://user-images.githubusercontent.com/51055719/58384394-2e202480-7fd9-11e9-8b34-1ae9816c6655.png)
I have never had this issue before and I absolutely love using Photopea, but this is really making it difficult to love editing with this service.

**Comment by photopea** [comment]
Hi, we store a database of Font Previews in this huge PNG image: https://www.photopea.com/rsrc/fonts/fonts.png

It seems like your browser is caching some old previews. Try to reload Photopea website several times.
