### ISSUE TITLE
Font switched during typing text

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1418]
When typing text with diacritic in some fonts it now swich to other font (and never comes back to original font). It does it also when glyph for that character is available in that font.
For example in this screenshot using font Diplomata:
![image](https://user-images.githubusercontent.com/6370548/58401166-6a956400-805d-11e9-9624-6275790d2faa.png)

**Comment by photopea** [comment]
Hi, we made it work this way on purpose. E.g. when people want to start typing in Chinese (default fonts dont support Chinese).

You can take it as "warning", that you are using a wrong font, and choose another one.

If you really just want to draw only "š" with another font, you should do it after typing.

**Comment by hxim** [comment]
OK I understand.
But in situation where it switches font and after I delete wrong/unsupported character with Backspace key can you make it go back to original font?. Now I need to move cursor left and right or find original font again in font list to continue without diacritics.

**Comment by photopea** [comment]
No, deleting characters should not switch fonts, it would cause many other problems. But moving cursor left-right will switch the font.

To avoid it all, when choosing fonts, enable Latin 1 and Latin Extended A filters.
