### ISSUE TITLE
Zoom tool with sub menu.

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#142]
For the sake of us, chrome users, PLEASE give the zoom tool a submenu on the tool bar, just like lasso or dodge. So we can doulbe tap the Z key and change from zoom in to zoom out.

**Comment by photopea** [comment]
You can hold alt to switch between Zoom In / Zoom Out.

Actually, I quick-switch to Zoom tool from any tool by pressing Ctrl + Spacebar (or Ctrl + Spacebar + Alt).

**Comment by avagp** [comment]
I have a chromebook. Alt+whatever doesn't work properly.

It does work, but at the same time I get the dropdown menu from the right
click.

And the combos you gave me does not work  :/







2017-03-03 20:55 GMT-03:00 Photopea <notifications@github.com>:

**Comment by photopea** [comment]
I know, that there is a problem in Chrome OS with using Alt :( But I don't want to change the whole interface just because of a bug in devices of a small fraction of users.

When you have a zoom tool, you can also press the mouse and drag it left / right to zoom in / out.

**Comment by avagp** [comment]
And how i am supposed to know that pressing the mouse and drag it left /
right to zoom in / out???

It is a good workaround for chrome os users!

But as a new user, how i am supposed to know that key combo?




2017-03-04 6:36 GMT-03:00 Photopea <notifications@github.com>:

**Comment by photopea** [comment]
sorry ... there are many features, that almost nobody knows about.

Since the beginning, I was waiting if somebody, who knows Photoshop, makes some tutorials about Photopea (UI is very similar). But I will probably do it myslef, once.

**Comment by avagp** [comment]
:c

So sad.

I will try to make some my own. I did tutorials on the past.




2017-03-05 17:48 GMT-03:00 Photopea <notifications@github.com>:

**Comment by avagp** [comment]
You know what.

Why don't you make as part as the social content a post every week or so
where you highlight a tip under the hood?

At the end of the year you can compile them and make a mini compendium or a
FAQ.

Also gives more interest to the users to visit Facebook or Twitter.   :)

**Comment by photopea** [comment]
That is a great idea! But I don't enjoy social networks that much. Would you like to post something to our fans? :)

**Comment by avagp** [comment]
I would, but you will have to give me all the secrets  😉




2017-03-06 7:07 GMT-03:00 Photopea <notifications@github.com>:
