### ISSUE TITLE
[Firefox] Deleting the layer asks if you want to leave the page

### ISSUE THREAD

**Issue by divillysausages** [photopea/photopea#1421]
- Create a project with more than one layer
- Drag one of the layers down to the layers bin icon
- You get a popup asking if you want to leave or stay on the page

I've been stung more than once clicking on the wrong option :D

Thanks for the great tool btw

**Comment by photopea** [comment]
Hi, I just tried it and I don't see any such popup :( What browser do you use? Can you update it or disable some extensions?

**Comment by divillysausages** [comment]
Hi,

Thanks for getting back so quickly. I'm on the latest Firefox (Quantum 67.0, updated this morning, though it's been an issue for a while). No extensions

Screens:

Create new layer
![createNewLayer](https://user-images.githubusercontent.com/179882/58468771-786ee600-813e-11e9-9626-a92b8af34389.PNG)

Drag to bin
![dragToBin](https://user-images.githubusercontent.com/179882/58468798-8ae91f80-813e-11e9-892b-83a4d37dd4b2.png)

Popup that shows up
![popup](https://user-images.githubusercontent.com/179882/58468820-90466a00-813e-11e9-9ace-440be0adf585.png)

**Comment by divillysausages** [comment]
Can confirm that it's not present in Chrome, Edge, or Brave though

**Comment by photopea** [comment]
I managed to change the code, so that it overcomes the problem in Firefox.

But I still don't understand, why browsers behave differently, and which behavior is the correct one. One would expect, that browsers will work the same way in 2019.

**Comment by divillysausages** [comment]
I'm with you on that one :D

Thank you!
