### ISSUE TITLE
BUG when transforming live shape with Alt

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1425]
Draw rectangle e.g. 300x300px
Use free tranform (ctrl+t)
Change reference point of transforming layer to left bottom corner
Rotate object (with Shift) to 45deg 
Hold right transforming point and move left with Alt button (to change width from center)

BUG - not enough RAM! and strange loop :)
<img width="1280" alt="Zrzut ekranu 2019-05-29 o 23 42 19" src="https://user-images.githubusercontent.com/38118273/58594080-034dfe80-826d-11e9-82cb-faf7f7a7003b.png">

`Uncaught RangeError: Invalid typed array length: 6.630486816174822e+30
    at new Uint8Array (<anonymous>)
    at Function.L.T (pp.js:361)
    at O.Xn.VJ (pp.js:5111)
    at O.Yi (pp.js:5004)
    at Function.J.H.fn (pp.js:4157)
    at J._Q.J.H.ZB (pp.js:4173)
    at J._Q.J.H.LM (pp.js:4097)
    at rk.rgY (pp.js:8593)
    at rk.N_.j (pp.js:9)
    at rk.fV.j (pp.js:5979)
L.T @ pp.js:361
O.Xn.VJ @ pp.js:5111
O.Yi @ pp.js:5004
J.H.fn @ pp.js:4157
J.H.ZB @ pp.js:4173
J.H.LM @ pp.js:4097
rk.rgY @ pp.js:8593
N_.j @ pp.js:9
fV.j @ pp.js:5979
fV.j @ pp.js:5979
fV.j @ pp.js:5979
GC.tH @ pp.js:7955
`

**Comment by photopea** [comment]
Hi, I fixed it!

BTW. holding Alt does not change width "from the object center", but "from the rotation center".

**Comment by MichalSZZ** [comment]
Thank you :)

Yes, yes - I know it (about rotation center) :)
I will try to show You how does it work in Photoshop becouse now in PP it doesn't work how I want (and should).

https://youtu.be/dX8gfbW_1uY
first part with Alt, last without.

**Comment by photopea** [comment]
I think I made it work as you expect.
