### ISSUE TITLE
Wrong interpretation of merged shapes

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1426]
https://youtu.be/39OvompqYSs

When I use "subtract" one shape from another (one is inside the other one) and after that I merge the result of that operation, I have all the time two separate shapes.
That makes problems in another combinations in the future (look at the movie above)

**Comment by photopea** [comment]
I believe I fixed it :) thanks!

**Comment by MichalSZZ** [comment]
@photopea thanks, but now at the end I finaly have something like this
![obraz](https://user-images.githubusercontent.com/38118273/58638399-0391dc80-82f5-11e9-975f-fc7188ac63eb.png)

**Comment by photopea** [comment]
it was not your goal? How did you make it?

**Comment by MichalSZZ** [comment]
> it was not your goal? How did you make it?

No, that wasn't my goal :)
Here is short movie how I did that
https://youtu.be/zhN6f8_ETtk

and here is https://youtu.be/39OvompqYSs?t=99 , how it should to work correct

**Comment by MichalSZZ** [comment]
Hi @photopea 
There is still that BUG in merging shapes
https://youtu.be/W9xzAHHzKLU

![2shapes-merge-bug](https://user-images.githubusercontent.com/38118273/58836069-edb74b00-8657-11e9-8c10-96bcddccda81.png)
