### ISSUE TITLE
i'm stuck on loading !

### ISSUE THREAD

**Issue by go-paulistic** [photopea/photopea#1427]
hello photopea ! i am having a big problem with your website and application ,, the same as many before me. when i try to upload a psd i get a large white sign that says "loading" this sign does not go away and my file never uploads. please help me fix this i am on a time crunch to create an image for someone.

**Comment by photopea** [comment]
Hi, can you please send us your PSD file to support@photopea.com ?

**Comment by go-paulistic** [comment]
yes i can give me a moment

**Comment by go-paulistic** [comment]
email sent ,, i apologize for the two emails ,, my computer glitched it is rather old.

**Comment by photopea** [comment]
Did you send me the right files? I can open your PSD files in Photopea without any problems.

**Comment by go-paulistic** [comment]
ah yes i did ,, on my phone they wont load in the app or on the website

**Comment by go-paulistic** [comment]
i will show you a screenshot of what happens when i try to open my psd file
![Screenshot_2019-05-30-14-32-38](https://user-images.githubusercontent.com/51185534/58655621-7d6f9900-82e8-11e9-9bb3-3b97a8ae3472.png)

**Comment by photopea** [comment]
Can really dont know how to help you :( I can not make Photopea do this with your PSD files neither on my desktop, neither on my Android phone :(

**Comment by mdyeamin** [comment]
one solution to this loading problem!
first of all, save your existing photopea file to .PSD 
open photopea on the new tab then upload your .psd file 
that's it
