### ISSUE TITLE
Changing height/width of live shape by moving 2 knots, disables Live Shape possibilities

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1428]
All is in the title :)
Sometime I use Direct Select Tool to change width/height of shape.
In Photoshop when I do that (only up/down or right/left - without distortion of object), I can still change e.g. radius of corner.
In PP it doesn't work

**Comment by photopea** [comment]
We would have to check, if you are dragging exactly two knots, which can not be on the opposite sides, and can be dragged only in a certain direction (e.g. top-right and bottom-right only dragged to left or right). And it gets more complex with rounded corners (you have to drag 4 knots).

Just use a Free Transform, or the Properties panel instead :)

**Comment by MichalSZZ** [comment]
@photopea how about checking only width and height after transform? If only that was changed (without any skew, rotation etc.) it should be a Live Shape still.
Live Shapes are only rectangles which are predictible in some of way... :)

**Comment by photopea** [comment]
Free Transform works well on Live Shapes. You can not only change width / height, but also rotate it by multiples of 90 degrees.
