### ISSUE TITLE
Feature request: Save for Web as PDF - possibility to select pages to export

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1429]
When I have PDF file or AI file with artboards and want to edit it and save only few selected pages, it should to be possibility to set which of pages export (e.g input to type numbers like in print settings 1-8, 10, 12 or checkboxes near thumbnails).

And yes - I know that I Can delete folder with page/artboard in layers panel but that is not the comfortable solution

**Comment by photopea** [comment]
Hi, I implemented it :) Both for PDF and EMF formats.
