### ISSUE TITLE
Healing tool get stuck and paints the picture!

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#143]
I have been using the new healing tool and it is great!

Even though, sometimes the tool freezes and do not hide the content, instead leaves the trail as a color, painting the picture, which cannot be undone.
![gondola 3 3](https://cloud.githubusercontent.com/assets/11801254/23708790/f5fa3b10-03f5-11e7-8ccd-359639ef4454.png)

Here you can see 2 spots (in yellowish) where the tool got stucked.

Also, why sometimes the tool paints in grey, other red and another yelllow?

**Comment by avagp** [comment]
![screenshot 2017-03-12 at 15 40 33](https://cloud.githubusercontent.com/assets/11801254/23834743/484c954c-073a-11e7-8934-85cc0a45008e.png)

**Comment by photopea** [comment]
Hi, I have tried to heal black spots in your picture and it works fine. What exactly was the problem?

Are you talking about the Spot healing brush or the Healing brush?
![f5fa3b10-03f5-11e7-8ccd-359639ef4454](https://cloud.githubusercontent.com/assets/15955558/24267737/985076ec-100b-11e7-8488-3bed41e75f6b.jpg)

**Comment by avagp** [comment]
Healing spot.

Do you see those yollowish strokes?  Those are because of the healing spot
tool not working properly. Sometimes it just paints on the picture

**Comment by photopea** [comment]
Can you find a specific image and a specific place, where it always happens? I would need to reproduce it (make it happen by myself), to be able to fix it.

**Comment by avagp** [comment]
I know I have to do that in order to get it fixed.

I'll try, but happens every now and then.

I will record myself working.

**Comment by photopea** [comment]
When it happens, can you see if your CPU is still working? maybe it gets into an infinite loop.

**Comment by avagp** [comment]
Emmm
I will, but is a Chromebook. Don't think it will get a bottle neck on the
cpu side. :)

**Comment by photopea** [comment]
I enforced the computation time limit to about 15 seconds. So at most after 15 seconds, healing with terminate (with the best possible heal it could make in 15 seconds). I hope it fixes the problem. If not, feel free to open it again.

**Comment by avagp** [comment]
I'll try it. If it still happens, take in account that I will reopen :P

Hope this is not an April's fool joke  😏

Le 1 avr. 2017 8:24 PM, "Photopea" <notifications@github.com> a écrit :

I enforced the computation time limit to about 15 seconds. So at most after
15 seconds, healing with terminate (with the best possible heal it could
make in 15 seconds). I hope it fixes the problem. If not, feel free to open
it again.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/photopea/photopea/issues/143#issuecomment-290953845>,
or mute the thread

**Comment by avagp** [comment]
It happened again  :/

I was using the spot healing with size 5, correcting the lip, and it got painted.

![screenshot 2017-04-13 at 12 58 57](https://cloud.githubusercontent.com/assets/11801254/25013184/14f3af64-2049-11e7-9fd7-45380bfd50a0.png)

**Comment by avagp** [comment]
Also, would like to ask, why some times the healing is red and other white? On what it depends?
