### ISSUE TITLE
EPS or AI not open correctly

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1430]
Graphic from here
https://www.freepik.com/free-vector/travel-flyer-template_4001884.htm
1.) when I tried open EPS format it said:
ext.js:1258 Uncaught e
2.) when I tried open AI format it opens but some shapes are not filled (for example instagram icon) or have wrong fill color (circle in top right). Same thing happens if I convert it to pdf via Acrobat Reader and then try to open it in photopea

**Comment by photopea** [comment]
Hi, Photopea supports only simple EPS files. We recommend to convert EPS into PDF, and open the PDF with Photopea.

Your AI file is actually a PDF file. You can replace the .AI extension with .PDF and open it in any PDF viewer. I fixed some bugs with vector shapes. However, Photopea does not support Tiled Patterns from PDF (as there is no way to store them inside PSD).

**Comment by aralroca** [comment]
What means "basic" EPS? We want to support only basic EPS and we found photopea a good tool to verify this. We are generating the EPS file with `pdftops` tool, and we want to know the correct config to support basic EPS. Currently this is not basic, and is not opened with photopea:

```sh
pdftops -eps -level3 -processcolorformat CMYK8 file.pdf file.eps
```

However removing `-level3` and `-level3 -processcolorformat CMYK8` we also have the same problem.

Thanks.

**Comment by photopea** [comment]
Could you send me an EPS file, which you can not open in Photopea, to support@photopea.com ?

BTW. EPS is an outdated pformat, you should use PDF nowadays. Every EPS can be converted into a PDF without any loss of data.
