### ISSUE TITLE
Adding Fonts

### ISSUE THREAD

**Issue by littlemisspond** [photopea/photopea#1431]
Hello! I was wondering if there was a limit to how many fonts can be downloaded from my personal files? I have a lot, and I've been able to keep a lot of them in photopea, given that I don't use most of the fonts generated by photopea itself. However, I tried to download some more today and they weren't there?

**Comment by photopea** [comment]
Hi, if you let Photopea save fonts in its "Local Storage", there should not be any limit for it. But it probably depends a lot on the browser and its settings. Some browsers may ask you, if you really want to allow Photopea save so much data.

So what exactly is the problem? What you mean by "download"? Do you mean storing fonts, that you import to Photopea, in the Local Storage?

**Comment by littlemisspond** [comment]
Storing fonts that I import to photopea! Usually what I do, is I take the font and just drop it into photopea by dragging it to the screen and something pops up that asks if I want to always save etc and I say yes. then it imports the font. however, I tried doing that yesterday and I couldn't find the font down at the bottom where it usually is??

**Comment by photopea** [comment]
Look into Photopea under Edit - Local Storage. Do you see any TTF / OTF files there? These are your private files, which will be loaded every time you start Photopea.

Local Storage could be cleared e.g. when you clear browser data, or reinstall the browser. Note, that if you saved your fonts in Chrome, and then use Photopea in Firefox, your Local Storage will not be there. It is different for each environment (browser, computer, phone ...) where you use Photopea.
