### ISSUE TITLE
Paint bucket tool does not consider pixels to be connected when only touching by corner

### ISSUE THREAD

**Issue by OfficialNoob** [photopea/photopea#1432]
I made a border using a 1px pencil but when trying to fill it in with a tolerance of 1.
The borders where not detected.

This might be useful for Pixel Art.
Update: Only happens when the boarder goes diagonally,
Works fine with a 2px pencil

**Comment by photopea** [comment]
I just tried to do the same and it worked well.  Can you send us your image as PNG and tell, where exactly did you click?

Note, that Paint Bucket only fills the pixel and other pixels, which are "connected" to that pixel (Contiguous). Do you want to fill all pixels in the whole image, which may not be connected to each other?

**Comment by hxim** [comment]
I think what he means is if you want to fill inside area like this with paint bucket in "contiguous" setting it will not work in photopea see screenshots (it will consider pixels are connected when only touching by corner):
![s1](https://user-images.githubusercontent.com/6370548/58744562-026fc500-8445-11e9-8e2d-7fb47d766438.png)
![s2](https://user-images.githubusercontent.com/6370548/58744561-026fc500-8445-11e9-8f32-4e1709ecca82.png)

**Comment by OfficialNoob** [comment]
That is what I meant I tried in Photoshop with the Paint Bucket tool (with Anti-alias unchecked)
And it filled in the area "correctly"

**Comment by photopea** [comment]
I made it work exactly as in PS :)
