### ISSUE TITLE
Snap to grid/guides stopped working!

### ISSUE THREAD

**Issue by bgobler** [photopea/photopea#1433]
I just bought a new laptop, and snap to grid/guides no longer works! Snap to document bounds is functioning, but not the other two. I hope there's a quick fix for this! I don't know if it's just the new laptop, or if others are experiencing this as well.

**Comment by photopea** [comment]
Hi, there really was a bug, I just fixed it. Thanks!

**Comment by bgobler** [comment]
Thank you SO much!!

**Comment by hmesker** [comment]
I still seem to have this problem as well - my objects don't snap to anything. I defined a rough grid of 1 inch to make positioning easier but the objects don't snap to it.

**Comment by photopea** [comment]
@hmesker Hi, have you enabled View - Snap, and options in View - Snap To - ...  ?

**Comment by hmesker** [comment]
> @hmesker Hi, have you enabled View - Snap, and options in View - Snap To - ... ?

Yes. View-snap is on and all three options (guides, grid & document bounds) are turned on. 
I first thought it might be a browser issue (I use Opera) but in Edge it also doesn't work.
If you want I can make a screen recording so I can show you what I am trying to do etc.

**Comment by photopea** [comment]
Yes, please, a recording would help us.

**Comment by hmesker** [comment]
https://www.youtube.com/watch?v=73ABIZIBqDE

I opened the sample project and tried to snap the title to the 1x1 inch raster - did not succeed.

**Comment by photopea** [comment]
Hi, there was a bug, that when snapping to grid, grid units were ignored, and pixels were expected. So in your video, it is snapping to 1x1 px grid.

I fixed it and it should work well now. Thank you! :)

**Comment by hmesker** [comment]
> Hi, there was a bug, that when snapping to grid, grid units were ignored, and pixels were expected. So in your video, it is snapping to 1x1 px grid.
> 
> I fixed it and it should work well now.

And so it does and it does it with flair and brilliancy. Thank you! You just made my day.
