### ISSUE TITLE
Feature request: Support .TGA file extension

### ISSUE THREAD

**Issue by KyoGrou** [photopea/photopea#1434]
It would be awesome if the app supports reading and exporting .TGA files, since this extension is widely used in game making industry.

**Comment by photopea** [comment]
Hi, I know Targa was "big" in the past, but I am not aware of it being used today. Can't you replace it with JPG / PNG?

**Comment by photopea** [comment]
It was implemented (only for opening). The source of Photopea grew by about 300 Bytes :)

TGA is very simple format, that creates huge files. PNG can fully replace it. That is why I think you should always save in PNG instead of TGA today.

**Comment by KyoGrou** [comment]
Hi there, thanks for your work. 
Because of some difference in how the photographic softwares treat the Alpha channel of each extension:

- The alpha channel of TGA is separated when opened, so we can take control of it easily. When you open the .PNG, the software will automatically treats the alpha channel as transparency, which is hard to deal with.
- Some software (even photoshop, I don't know if they fixed it or not) will fill in random color for RGB channels where the alpha value is 0 (fully transparent). It can be absolute white, black or just some color from the other area. (this is why there is a plug in for photoshop called superpng existed). This problem caused the unwanted artifact when using in game engines.
- JPG is a no-go since it is a compressed format and can't store the alpha channel.
- The compression won't make huge difference, since the game engines will compress the image to it own format.
- TGA is loaded faster than compressed PNG.

You can read about it on some game making community:
https://forums.unrealengine.com/development-discussion/content-creation/33788-tga-vs-png-for-textures/page2
https://forum.unity.com/threads/tgas-or-pngs-which-does-unity-prefer-alpha-wise-which-is-more-efficient.149617/
https://forum.unity.com/threads/colleagues-for-tga-i-for-png.456764/
https://polycount.com/discussion/112149/png-or-tga-i-dont-get-it

**Comment by photopea** [comment]
You are showing liks to discussions, where some people say TGA is better than PNG. It does not prove anything.

You can have a PNG with DEFLATE with only copy-recodrds, which means "no compression" and could be decompressed equally fast as TGA. 

When pixels are transparent, their RGB information should not be important. So it is ok to rewrite such RGB values.

I really think you should not use TGA nowadays, use PNG or JPG instead. JPG is lossy, but GPU-related compression (BC3, BC7...) is even more lossy. You can store alpha in separate files.

**Comment by KyoGrou** [comment]
It's not just about a RGB image with a transparency information: 

- If we use the PNG files for the transparency, due to the compression method of the game engine, you can see the seam when using transparency just like in this article: https://answers.unity.com/questions/10302/messy-alpha-problem-white-around-edges.html

- We used the the TGA to create a special material texture in realistic game nowadays, we use each R.G.B.A channel to store grayscale values to express information like smoothness, reflection, ambient occlusion, glowness, etc ... and with the png method it may mess the other channels up.
And because of how the Photoshop treats the tga alpha information as separate layer, not as 3 RGB channels with transparency, we're still using this file extension in game making.

Me and my team has tried png before, and had to switched to tga because of this problem.
TGA
![image](https://user-images.githubusercontent.com/30156458/58941845-cae77c80-87a6-11e9-95e3-5c7c0a0bab42.png)

PNG
![image](https://user-images.githubusercontent.com/30156458/58942072-3df0f300-87a7-11e9-9966-f6a7d9b2d4ed.png)

- We can't separate the alpha to another files, since it will take another whole RGB image just to store one grayscale information, which will affect the game's build size a lot. 
- JPG isn't good, we use it sometime, but because this extension will cause artifact due to it's compression method. so we doesn't use it that much, for example if you want to make some pixel game and maybe you don't want Mario's mustache go up to his nose.

**Comment by KyoGrou** [comment]
Here is an example:
![image](https://user-images.githubusercontent.com/30156458/58944753-a68e9e80-87ac-11e9-879c-109d3e7ce539.png)

I imported both PNG and TGA to Unity engine

The PNG exported by Photoshop have weird white bars, which cut through the other channel:
![image](https://user-images.githubusercontent.com/30156458/58945188-93300300-87ad-11e9-8ac0-65845583d9e6.png)

The PNG exported from the TGA by Photopea has lost the information of the RGB channel where alpha value is 0:
![image](https://user-images.githubusercontent.com/30156458/58945205-9b883e00-87ad-11e9-8bb8-7000ecd7aaf5.png)

And the RGB information of TGA is still the same:
![image](https://user-images.githubusercontent.com/30156458/58945227-a3e07900-87ad-11e9-92ef-1a1916489deb.png)

Here is a graph showing how the channels work in game engine:
![image](https://user-images.githubusercontent.com/30156458/58945468-1c473a00-87ae-11e9-9e00-abddee2e855f.png)

We took data from each channel to provide the information for the specific settings of the game's material, so the object will display it's correct material depending on where the channel data applies

**Comment by photopea** [comment]
I see, that you just need a fourth channel, which will not store transparency, but other data. Currently, photopea is rgb-based, and it can treat the fourth channel only as transparency.

Are four channels in TGA always enough for you? Dont you need like five or even 10 channels sometimes?

If i were you, i would store those in separate png files. You can make a png with just one channel (i.e. not rgb), the files are very small. Or you can have green and blue channel with a constant 0 value, files will be equally small as with only one channel.

**Comment by KyoGrou** [comment]
- 4 channel is fine, and that's the limit of a TGA file can hold. 
- I prefer multiple alpha channel, since I can quickly store and load selection just by Ctrl + L Click the Alpha channel, I have never tried exporting a TGA with multiple Alpha channel before to see what it's like, but the selection thing is something I really wished for.
- I think that because of each file extension purpose and handling method, so as you mentioned above, the png is made for web viewing and is lightweight, so it won't preserve the RGB channel when the Alpha value = 0, unlike the TGA format.
- The game engines just doesn't care what file format and size you import, once you imported the images to the engine, they will be converted to the engine's own format, even if you make a RGB with one channel, the other 2 channel is still there, and when the engine converted, they have the same size, so the input file size is not a problem, what we have to deal with is use RGB or RGBA, and the number of image files

**Comment by photopea** [comment]
Png can be grayscale.

**Comment by KyoGrou** [comment]
Oh, I don't know about that, thanks for the information :D 
But because of the engine's nature and the client's requirement, so we can't really do anything about this.

I think we will use the grayscale PNG in some specific case though, thank you once again.

**Comment by KyoGrou** [comment]
I have tried importing the Grayscale and Unity automatically convert it to RGB image.
The file size is the same with the RGB png after converting, such bad luck.

**Comment by photopea** [comment]
So we are not talking about a PNG or TGA, but about Photopea capable of working with more than 3 color channels (and 4th not being Alpha). All Photopea tools (brushes, Eraser, Adjustments, filters ...) currently expect the image to be RGB. Remaking all tools would take a huge amount of time, and I think it is not worth it, as there are not many people needing it.

If you really want to be less dependent on Photoshop, try to get used to separating your work into multiple layers / images, instead of one layer with many channels. Every tool can handle a RGB image, but not many tools can handle an image with so many channels.

Anyway, storing non-transparency data into a transparency channel is a cheap trick from 80s, when there was only one image format, and advanced compression did not exist. There is no reason to do it nowadays.

If you are loading a grayscale image, which (obviously) should be representable by a single channel, and Unity creates RGB (3x more memory), it is a bug in Unity and you should report it to them.

**Comment by KyoGrou** [comment]
- Personally, I think that the 4th channel of the RGB color space is always the Alpha channel, it's just because of the special method Photoshop treats multiple channels for the .PSD extension. 
About the tools behavior, I think that the Advanced Blending option is made to handle this. You choose the specific channels for the layer, it will display the layer in the chosen color channels. You can still paint / erase / edit on all RGB channels of the layer, it just that the layer will only displayed in the channels you choose, and you can switch back whenever you want.
- And yes, we separate each channel by layers, and just have them used Advanced Blending. 
- I don't think this is the case, when opening a PNG and TGA in Krita and GIMP. They still treat the alpha channel as Transparency, but Krita can separate the alpha channel and keep the RGB channel as is, so I think this is about the softwares preferences, not the file format itself.
- Using it in game engine is just an example, I think that there are a lot of case since you would like to access to edit each channel information, since I have seen some request to enable the channels editing support.

With this feature, say, everyone can retouch their photo, by selecting the color by each channel and adjust them. They can even edit the transparency of some buttons for their website, if they want the transparency is exactly 50%, which we can't be sure if we don't have the information extracted from the alpha channel.

I know that with each feature added, there will be a lot of work to do, and a lot of bugs to take care of. So it's up to you if you want to do it or not, but we're talking about images and photos editing here, and I think that the accuracy and high quality of each work is a must, and this feature will help the users a lot, so please take your time to consider about it.

**Comment by photopea** [comment]
When you interpret the fourth channel as Alpha, it means, that RGB values are not important at such pixel. Tools are usually free to rewrite RGB values, e.g. to improve the compression.

So you need to work with a fourth channel the same way as you work with RGB channels (meaning that it should not influence other channels). Which is not possible with usual image editing tools.

**Comment by KyoGrou** [comment]
So you mean that we can only have 4 channels at max or it's hard to edit the tools' behavior ?

**Comment by photopea** [comment]
The regular image model (the Photopea model) are three channels plus Alpha. You should not think about it as four channels, because it is a little different. When Alpha is zero, the RGB value of such pixels is not defined. And all tools (and even APIs like OpenGL or DirectX) work this way. 

E.g. it is often needed to convert between "premultiplied alpha" and regular alpha. And once you multiply a Red value by Alpha=0, there is no way to get back the original value.

Implementing CMYK into Photopea would be equally hard. Restricting ourselves to a specific color model simplifies many things.

**Comment by KyoGrou** [comment]
So this means if I import a Grayscale or CMYK image into Photopea, it will automatically convert to RGBA ? I guess this is fine since we use RGBA for most of the time.
 
About the channels editing, I think that if you made it, it will be 3 RGB channels with alpha information implemented, not RGB and a separate 4th channel ? 

Isn't there any way that Photopea can keep the RGB information if the alpha = 0 ?

**Comment by KyoGrou** [comment]
The only method I can think of for this situation right now that I have to group the layers, and create an alpha mask for that group. But this means that if only I keep the file as .PSD extension, then the data of all channels is kept, but if I export to another format, it will lose the RGB information, am I right ?

**Comment by MichalSZZ** [comment]
@KyoGrou TIFF file should have a option to store layers folders etc.

**Comment by KyoGrou** [comment]
@MichalSZZ this is a feature request, not finding a work around method, since there are a lot of game studios still using TGA because of how the graphic software handles the alpha channel of the format.

For the TIF / TIFF, I agree that this extension is great, it's lossless and can handle alpha, 
But the softwares (I will say photoshop for example) treat the alpha channel is either, it can be separated to RGBA channels, or RGB with transparency, and the other channel lost it's information where the alpha is 0, so the graphic software / game engine will automatically fill in black or white (0% or 100%) information.
