### ISSUE TITLE
Feature request: Channels editing support

### ISSUE THREAD

**Issue by KyoGrou** [photopea/photopea#1435]
As mentioned in #1434 , some extensions store the alpha as separated channel, not as transparency.
When you open the TGA format, you can only see the RGB channel, and the Alpha channel is hidden because of it's nature, so it's impossible to edit the alpha.

**Comment by KyoGrou** [comment]
Also there is the "Advanced Blending", a sub menu of the layer's Blending Options, which is directly related to the channels editing feature

**Comment by photopea** [comment]
I dont mean what you mean by "alpha as separated channel". Can you share such TGA image with me?

**Comment by KyoGrou** [comment]
Here is an example:
[Test.zip](https://github.com/photopea/photopea/files/3256009/Test.zip)

If you open with photopea or photoshop, it will display like this:
![image](https://user-images.githubusercontent.com/30156458/58938377-e6e72000-879e-11e9-8373-52e92243c316.png)

Channels viewer in photoshop:
![image](https://user-images.githubusercontent.com/30156458/58938429-fc5c4a00-879e-11e9-8139-412fe58647d4.png)

Another image viewer:
![image](https://user-images.githubusercontent.com/30156458/58938454-0da55680-879f-11e9-9bd9-e736fc6b7375.png)

**Comment by photopea** [comment]
We are planning to add the support for channel editing. It is described here: https://github.com/photopea/photopea/issues/285

**Comment by photopea** [comment]
I also fixed the TGA import, so that it loads the alpha channel now, too.
