### ISSUE TITLE
Bug: Shapes created with "fixed size" option have wrong size.

### ISSUE THREAD

**Issue by KyoGrou** [photopea/photopea#1436]
The shape created with the fixed size is 1 pixel larger than the defined size, unless the shape is snapped to the border / grid.
![image](https://user-images.githubusercontent.com/30156458/58926639-1897c100-8776-11e9-8ef5-970f22f13e63.png)
![image](https://user-images.githubusercontent.com/30156458/58926656-28afa080-8776-11e9-855f-860673c3231b.png)
![image](https://user-images.githubusercontent.com/30156458/58926677-3402cc00-8776-11e9-9fb8-2e998673fd00.png)

**Comment by photopea** [comment]
Hi, I fixed it, thank you :)

**Comment by KyoGrou** [comment]
Thank you :D
