### ISSUE TITLE
Bug: Wrong "Path Select" & "Direct Select" icons

### ISSUE THREAD

**Issue by KyoGrou** [photopea/photopea#1437]
The icons displayed on toolbar is swapped, unlike the icons displayed when you hover the mouse over the tool itself

**Comment by photopea** [comment]
Hi, it is not swapped, icons are just "inverted" (a black icon on a white background vs. a white icon on a black background).

**Comment by KyoGrou** [comment]
Sorry for the bad explanation.
What I meant is when you use the "Path select" tool, the toolbar will display the "Direct select" icon instead.

**Comment by photopea** [comment]
Are you sure? I cant reproduce it. Can you show me a screenshot?

**Comment by KyoGrou** [comment]
Path Select tool:
![image](https://user-images.githubusercontent.com/30156458/58947180-9c22d380-87b1-11e9-97f4-896fd1bec152.png)

Direct Select tool:
![image](https://user-images.githubusercontent.com/30156458/58947225-b361c100-87b1-11e9-8f63-c70bc2fc4163.png)

Compared to how it shown when hovering over the tool icon:
![image](https://user-images.githubusercontent.com/30156458/58947338-e73ce680-87b1-11e9-8acc-dea03712a03f.png)

**Comment by photopea** [comment]
The colors are inverted :D looks correct to me

**Comment by KyoGrou** [comment]
It's note about the inverted color, this is what I meant:
When I choose the Pen

In photoshop, when I choose the the Path Select tool, the toolbar show the black pointer of the Path Select tool for me, and the same applied to the Direct Select tool:
![image](https://user-images.githubusercontent.com/30156458/58949449-aeebd700-87b6-11e9-9822-1eaa39a1997d.png)
![image](https://user-images.githubusercontent.com/30156458/58949627-1b66d600-87b7-11e9-8788-06aecf552cf4.png)

But in Photopea, when I choose the Path Select tool, I'm expecting to see the Black pointer icon of the tool, instead the toolbar just display the White pointer of the Direct Select tool.

Take the Pen tool in Photopea for example, when I choose the Pen tool, and the toolbar is showing correctly the icon of the Pen tool, not the Free Pen tool.

**Comment by photopea** [comment]
You should not think of it as white cursor and black cursor. 

You should think of it as an "empty cursor" with a contour and empty inside (for Direct Select), and a "filled cursor", whose inside is filled with color, and there is no contour (for Path Select).

**Comment by KyoGrou** [comment]
Okay, it make more senses now, guess i will just have to get use to it.
Thanks a lot for the explanation.
