### ISSUE TITLE
Periods are behaving weirdly in text boxes.

### ISSUE THREAD

**Issue by putering** [photopea/photopea#1438]
I've tried to type a period multiple times but it keeps going to the wrong spot, no matter what text alignment I'm in.
The gif below shows it. The moment where the period sort of disappears I hit enter.
![Peteproblemvid](https://user-images.githubusercontent.com/51424391/58994350-d2625200-87b5-11e9-82eb-ae713037aa35.gif)

**Comment by photopea** [comment]
Can you save the document as a PSD and send it to support@photopea.com ?

**Comment by putering** [comment]
If you're saying by email, absolutely!

**Comment by photopea** [comment]
Hi, I tried to open your PSD in Adobe Photoshop and it works the same way.

The reason of this is, that your text layer has set the Right-To-Left direction. You can change it in Paragraph panel: Window - Paragraph, Direction: Abc ...
