### ISSUE TITLE
Menu-View-Zoom In/Out cursor size not updated

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1439]
When using Menu-View-Zoom In/Out cursor size of Brush,Eraser and other tools is not updated.
Same happens when using Menu-Window-Navigator window as I mentioned in https://github.com/photopea/photopea/issues/1404
![image](https://user-images.githubusercontent.com/6370548/59017683-ad142900-8833-11e9-889a-26c8027e5402.png)

**Comment by photopea** [comment]
Hi, I fixed it. But the cursor will not be updated immediatelly, but only after moving the mouse over a canvas.
