### ISSUE TITLE
Keeping all the secrets: Layer Style

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#144]
Maybe you wrote about Layer Style window on a blog post, but for any new user it will bee difficult to find those options.

Double click on a layer gets you to this massive amount of options that i have not seen (most of them i translated myself, but was not aware where were them).

Maybe keep that double-click to enter, but i should suggest to add it to the right-click menu on the layer.
![screenshot 2017-03-12 at 15 05 26](https://cloud.githubusercontent.com/assets/11801254/23834435/5a576ec4-0735-11e7-81f5-7d301bea7d76.png)

Keep the great work. I posted Photopea on a Chrome OS subreddit, for someone who was asking for the best editing tools for chromenbooks, for me photopea is the best one. ;)

**Comment by photopea** [comment]
Thank you Alvaro :)  Actually, it was already requested earlier :) https://github.com/photopea/photopea/issues/131

**Comment by photopea** [comment]
It was added. There are Blending Options as the first item in the context menu.

**Comment by avagp** [comment]
Yey!

Le 27 mars 2017 8:45 AM, "Photopea" <notifications@github.com> a écrit :

It was added. There are Blending Options as the first item in the context
menu.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/photopea/photopea/issues/144#issuecomment-289429725>,
or mute the thread
