### ISSUE TITLE
Feature: Edit point tool

### ISSUE THREAD

**Issue by KyoGrou** [photopea/photopea#1440]
There is no way to break the point's handles into 2 separate lines, or completely set the handles length to 0. 
It would be nice to have a tool just like in Photoshop, the Convert Point tool / or the Edit Shapes tool in Krita, which can edit the point handles, moving, insert and remove point, etc.. by using the right click sub menu.

**Comment by photopea** [comment]
Hi, you can do it by double-clicking the handle or the anchor point, see https://www.photopea.com/learn/vg-manipulation

**Comment by photopea** [comment]
You can also make sharp angles with a Pen tool in every program by holding Alt.
