### ISSUE TITLE
Requesting addition of new Tibetan fonts

### ISSUE THREAD

**Issue by sonamdawa101** [photopea/photopea#1448]
It is such a joy to see that photopea has supported Tibetan Language and we are able to use it for any design and projects. This act of yours help preserve our unique Tibetan language. Therefore, I am truly honored.
     Since Tibetan language is supported in Photopea many people from Tibet and Tibetan in exile asking if more Tibetan fonts could be added in the font section. 
     For a while I have collected 12 Special Tibetan Font and 17 newest and most commonly used Tibetan Font in the link below: 
    https://drive.google.com/drive/folders/1-5naZ_oKRFOTMeMN-uw249CL--_TFzyG

I am a big fan of Photopea and I sincerely support the advancement of Photopea, 

Lastly, I would like to requst you to add the fonts given in the link above.

Thank you once again.
sonamdawa

**Comment by photopea** [comment]
Hi, are you sure these fonts re free to use for any purpose, and we don't need any special licence?

**Comment by sonamdawa101** [comment]
Yes all these fonts are free to use and don't need any licence. No worry :-)

**Comment by photopea** [comment]
Hi, I added them, thank you! :)

**Comment by sonamdawa101** [comment]
Thank you for all the new Tibetan Fonts included in Photopea. 

**I found one font is not add "TCRC Youtso Uni.ttf" in the special font set.** Other than that all working perfectly. 

Thank you once again for making this possible !

![Tibetan New Fonts in Photopea](https://user-images.githubusercontent.com/36448436/59324822-32994c80-8cfe-11e9-9ce8-66f404c5b13e.jpg)

**Comment by photopea** [comment]
Hi, that font does not have as many Tibetan characters, as other tibetan fonts do, so it was not classified as Tibetan. I lowered the limit (for tibetan characters, to consider the font as Tibetan), and it is in the Tibetan category now.

**Comment by sonamdawa101** [comment]
TCRC Youtso Uni is working !
Thank You :-)

![Tibetan New Fonts in Photopea -3](https://user-images.githubusercontent.com/36448436/59328852-1223bf00-8d0b-11e9-8b22-23028ccd23ad.jpg)
