### ISSUE TITLE
I am typing into a box on a photo that I created with the text tool but I cannot see any of the text on the photo. It does appear on the side where it shows the layers.

### ISSUE THREAD

**Issue by Youngmarc73** [photopea/photopea#1451]

**Comment by photopea** [comment]
Hi, maybe you are typing with a black text on a black background?

If not, what font are you using, and what text are you typing? I will try to do it myself.

It is also possible, that your browser is too old. Text tool requires WebAssembly technology, which is not present in old browsers (older than 2 years).

**Comment by photopea** [comment]
I have to close it because of lack of details :/
