### ISSUE TITLE
Type tool stops working

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1455]
1.) Open new project 400x400 px
2.) Select Type Tool and create box about 150x150 px
3.) Write text "abcdefghijklmno" so it overflows box (mno is outside of box)
4.) Confirm
5.) Now click on letter "o"
6.) Press some letter on keyboard (for example "a")
-> Type tool stops working and console show errors:
pp.js:5653 Uncaught TypeError: Cannot read property 'Xc' of undefined
    at Function.WH.Wje (pp.js:5653)
    at new WH._I (pp.js:5667)
    at new WH (pp.js:5633)
    at f.iI.gF (pp.js:3679)
    at f.iI.WFD (pp.js:3688)
![image](https://user-images.githubusercontent.com/6370548/59326738-cf9cbb00-8ce7-11e9-9eb9-0fd2368c50b1.png)

**Comment by photopea** [comment]
It should be fixed now, thanks! :)
