### ISSUE TITLE
Transparency lock

### ISSUE THREAD

**Issue by kelfoxx** [photopea/photopea#1456]
Hi, just wondering if it's possible to lock the transparent pixels in a layer? I used to use it all the time drawing in photoshop and really miss it. Brilliant job on Photopea, thank you :)

**Comment by photopea** [comment]
Hi, it is not possible at the moment. I think it is related to Channels feature (e.g. when you choose a Red channel, it is like applying a "lock" on a green and blue channel). So we will fix this together with Channels: https://github.com/photopea/photopea/issues/285

**Comment by kelfoxx** [comment]
Ah all good, was just wondering if I'd missed something. Will keep an eye out for the update. Thanks for the quick reply and have a great day.
