### ISSUE TITLE
Bug: Gradients in layer style keep changing

### ISSUE THREAD

**Issue by KyoGrou** [photopea/photopea#1457]
For example, when I clicked on the gradient box in the Stroke options, the Gradient Overlay value changed. and when I clicked on the Gradient Overlay color, the gradient in the Stroke changed.
![image](https://user-images.githubusercontent.com/30156458/59371882-5f864780-8d70-11e9-85c5-6306541f9320.png) (Original)
![image](https://user-images.githubusercontent.com/30156458/59372037-c7d52900-8d70-11e9-80f1-02cd07bfeab4.png) (Edit Stroke, Gradient Overlay changed)
![image](https://user-images.githubusercontent.com/30156458/59371904-6d3bcd00-8d70-11e9-839a-9a1cc4d9086e.png) (and the other way)

**Comment by photopea** [comment]
Hi, this is a really interesting bug! I wonder that nobody reported it before.

I fixed it. Thank you very much!
