### ISSUE TITLE
Rectangle Select - Fixed Ratio problem

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1458]
When I set Fixed Ratio W:1, H:1 in Rectangle Select tool it allows me select rectangle so width is one pixel higher than height sometimes - see screenshot.
![image](https://user-images.githubusercontent.com/6370548/59405265-29fe5000-8daa-11e9-9ee6-4e5beb52410c.png)

**Comment by photopea** [comment]
I fixed it, thank you! :)
