### ISSUE TITLE
Fade error

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1459]
1.) Use Brush
2.) Use Menu - Edit - Fade...
3.) Undo last step by clicking in History window (undo Fade)
4.) Now Menu - Edit - Fade... is disabled (why?)
5.) But I Press Shift+Ctrl+F and Fade dialog still opens
6.) Move slider and confirm with OK
->
![image](https://user-images.githubusercontent.com/6370548/59487373-c1cc6e80-8e7c-11e9-95c5-fa8a8d7bbf6f.png)

**Comment by photopea** [comment]
I fixed it. 

Fade can be applied only after a pixel-editing step. It uses the history, to make a combination between the last state and the previous state.

Fade is the pixel-editing step itself, so you can use Fade for the second time to decrease the intensity of a previous Fade :)

**Comment by hxim** [comment]
Great!
But I found another error:
1.) open pea.psd
2.) go to "background" layer
3.) paint with brush
4.) go to "Welcome" layer
5.) now apply Menu - Edit - Fade... function
->
![image](https://user-images.githubusercontent.com/6370548/59504719-d40dd300-8ea3-11e9-8b34-32a65dcfa50e.png)

**Comment by photopea** [comment]
Fixed, thanks! :)

**Comment by hxim** [comment]
And one more
1.) open pea.psd
2.) go to "background" layer
3.) paint with brush
4.) Menu - Edit - Free Transform
5.) now apply Menu - Edit - Fade... function
->
![image](https://user-images.githubusercontent.com/6370548/59505486-d83af000-8ea5-11e9-92af-18c22f47ce8a.png)

**Comment by hxim** [comment]
More errors with Fade:

1.) open pea.psd
2.) go to "background" layer
3.) paint with brush
4.) select all layers
5.) now apply Menu - Edit - Fade... function
->error
---

1.) open pea.psd
2.) go to "top bar" layer
3.) add raster mask
4.) paint with brush into mask
5.) switch from mask pixel data to layer pixel data
6.) now apply Menu - Edit - Fade... function
-> fade applied on wrong pixel data (from layer instead of mask)

**Comment by photopea** [comment]
Hi, I fixed the last two, but still don't know how to fix the Free Transform issue within the current environment :(
