### ISSUE TITLE
A T Shirt mockup hangs up the UI.

### ISSUE THREAD

**Issue by mrillusi0n** [photopea/photopea#1461]
I'm unable to work with the PSD linked below.
[https://www.pixeden.com/psd-mock-up-templates/classic-psd-t-shirt-mockup-vol1](url)

**Comment by photopea** [comment]
Hi, I was able to open your PSD in Photopea, view the layers, etc.

Your PSD is quite large (330 megapixels). If your browser crashes while editing, try to disable WebGL (More - Use WebGL).
