### ISSUE TITLE
Stop working bug detected! Solve this issue: Error: WebGL warning: copyTexSubImage2D: Texture has not been initialized prior to a partial upload, forcing the browser to clear it. This may be slow.

### ISSUE THREAD

**Issue by tamjidsatt** [photopea/photopea#1462]
this error trigger while any image or project open. Error: WebGL warning: copyTexSubImage2D: Texture has not been initialized prior to a partial upload, forcing the browser to clear it. This may be slow.

nothing comes up on screen, i am using mozile dev version

**Comment by photopea** [comment]
Hi, we don't recommend to browse the web with experimental versions of browsers. 

Please, test Photopea in a standard release of a browser. Otherwise, it is almost surely the bug in your browser.
