### ISSUE TITLE
Tamaño de Interfaz

### ISSUE THREAD

**Issue by jorgeincreare** [photopea/photopea#1463]
La interfaz del programa se muestra demasiado pequeña y no se puede leer. El área de trabajo esta bien pero la barra de menús y barra de herramientas se encuentran completamente reducidas de tamaño.

**Comment by photopea** [comment]
Hi, what is the zoom of your webpage? Maybe you zoomed out too much. Click into the menu and set the zoom to 100%.

**Comment by jorgeincreare** [comment]
Es correcto, era el zoom de Google!! Gracias!!!

**Comment by photopea** [comment]
You are welcome :)
