### ISSUE TITLE
Can't start cropping in direction other then upper left to lower right

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1464]
'But I will add the option of drawing a rectangle in "any direction". '

_Originally posted by @photopea in https://github.com/photopea/photopea/issues/486#issuecomment-368890724_

I still have this problem. On February you wrote that this functionality will be added. Is something hard to implement that?

**Comment by photopea** [comment]
Hi, I realised it is quite hard to add into a current structre. Is it really so important for you? I think people can get used to always draw from the top left corner. You can always press Esc to start again.

**Comment by MichalSZZ** [comment]
@photopea No. That isn't so important for me. I just wondered, if that was an oversight or something very hard to do. 
Thank you for the answear!

**Comment by photopea** [comment]
It has been fixed - you can draw a cropping rectangle in any direction.

**Comment by MichalSZZ** [comment]
Thx!
