### ISSUE TITLE
Paste from clipboard - sometime work strange

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1465]
Sometimes after use ctrl/cmd + v Photopea is paste other things from clipboard (something that was copy earlier - not only images). It looks like OS have two diferent clipboards? :/

Or it pasts some other image and very fast changes it to proper one. Its happens not all the time. Hard to reproduce that.

I have this situation on my Macbook and PWA verrsion of Photopea, but saw this issue also on Windows.

**Comment by MichalSZZ** [comment]
I made this video some time ago (when tried to reproduce 'copy merged' bug), but there is same bug as in the title -> I copied from artboard but pasted layer was made 10 minuts before all other copy-paste tries.
In OS clipboard are stored one or maybe more things?

**Comment by photopea** [comment]
Current technology does not allow us to put an image into a OS clipboard. So when you do Copy in Photopea, it is stored in our "local clipboard".

When you do Ctrl+V, we see, that there is an image in a system clibpoard, and in a local clipboard, but it is hard to tell, which one you want to paste.

But soon, the technology should improve, and we will work only with one system clipboard.
