### ISSUE TITLE
能不能做个psd或者xd格式的文件转为axure格式的需求呢

### ISSUE THREAD

**Issue by yll18279150734** [photopea/photopea#1466]
能不能做个psd或者xd格式的文件转为axure格式的需求呢

**Comment by photopea** [comment]
Hi, I am not familiar with Axure. I think it should load PSD and XD files, right?

**Comment by MiYogurt** [comment]
这个需求很奇怪 ，adobe 和 axure 是两个公司，他们存储的文件格式是不一样的，不存在这种转换。

his mean transfer the psd file to axure file type

It's not possible.

**Comment by photopea** [comment]
Ok, I will close it for now.
