### ISSUE TITLE
polygonal lasso select tool

### ISSUE THREAD

**Issue by jokiez88** [photopea/photopea#1467]
When using polygonal lasso select tool and you do not complete the path and select the zoom 
 tool with your mouse; you lose the whole gray selection path.

**Comment by photopea** [comment]
I know that. Switching to a new tool will cancel the work of the previous tool.

There are many other ways to zoom in. Hold Spacebar and Ctrl to switch temporarily to a zoom tool (adding Alt will change the mode: + or -). You can also use View - Zoom in, or the Navigator panel (Windows - Navigator).
