### ISSUE TITLE
Fonts keeping changing back

### ISSUE THREAD

**Issue by hihichan** [photopea/photopea#1468]
Whenever I use other fonts (uploaded from my computer), it keeps changing back to DejaVu Sans.

**Comment by photopea** [comment]
Hi, could you please describe, what you mean by that? When does it change back to DejaVu Sans?

**Comment by hihichan** [comment]
It happened whenever I wrote in Vietnamese
![38 (1)](https://user-images.githubusercontent.com/52148037/60002984-f4077880-9693-11e9-9f88-64823781b5b5.jpg)

**Comment by photopea** [comment]
Hi, can you send us your Augie font to support@photopea.com ? Are you sure it supports Vietnamese?

**Comment by hihichan** [comment]
Yeah, I have used these fonts to write in Vietnamese for a long time (since
last year if my memory serves correctly). However, it turned out like this
about 2 months ago

**Comment by photopea** [comment]
Could you send us your the Augie font, please?

**Comment by hihichan** [comment]
Can I have your gmail?

**Comment by photopea** [comment]
It is support@photopea.com

**Comment by hihichan** [comment]
Have you received Augie and Astro city font?

**Comment by photopea** [comment]
Hi, I received your files, and I think I fixed your problem.

Can you please check, if it all works well?

**Comment by hihichan** [comment]
It works, thanks a lot. I'm really appreciative of your help <3

**Comment by photopea** [comment]
Thank you for helping us fix it. I did not realize in the past, that there could be such serious problem. 

Thousands of our users from Vietnam are thankful to you :)
