### ISSUE TITLE
Possible typos in Photopea

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1469]
You probably meant "width:34px" not "widt:34px" and "DejaVuSans" not "DeajVuSans" :-)
![typ1](https://user-images.githubusercontent.com/6370548/59995383-808b4a00-9646-11e9-8afc-b4cf788f61d0.png)

![typ2](https://user-images.githubusercontent.com/6370548/59995382-808b4a00-9646-11e9-8dac-af2ec0dda7a1.png)

**Comment by photopea** [comment]
wow, fixed, thank you! :)
