### ISSUE TITLE
Brush / Esraser tools invisible and issue with their settings

### ISSUE THREAD

**Issue by Niroc** [photopea/photopea#1470]
Hi, 
The cursor for the brush and eraser tool have become invisible so, I can't see the circular outline of their tips.

Also, when I try to adjust the brush size, the usual preset brush option are invisible too.

Please see image showing the right-click drop down menu for the brush tool
![Screenshot_2019-06-24_08-45-12](https://user-images.githubusercontent.com/12100786/60000879-04e8c780-965d-11e9-9e3b-a36058c4331b.png)

My OS is Manjaro Linux and I have tried Photopea in Chromium, Firefox and Waterfox and all of them have this issue.

I can say for certain this was 100% working as expect on the 19th of June (last Wednesday)

Let me know if you need more info!

**Comment by photopea** [comment]
Hi, It was fixed, thank you! :)
