### ISSUE TITLE
Layer Effects cannot be accessed after text is too long.

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1479]
To normally access the layer effects, you should double click on the specific layer on the layers tab.

But if your text layer is too long, then the effects cannot be accessed, because the double click will prompt the rename function.

Is uncomfortable to edit your layer's name only to be able to access the layer effects window.

It will be ok to keep it to that way, but adding the layer effects on the drop-down menu when right clicking the layer.

Here is a video showing it:
[video.zip](https://github.com/photopea/photopea/files/3342271/video.zip)

**Comment by photopea** [comment]
How exactly would you like me to fix it? Should I always show only the first 10 cahracters of the layer name?

Actually, Layer Style window opens when you click anywhere except of the layer name, "T" thumbnail, and the eye icon. There is about 3px space around the "T" icon, where you can click. 

Right-click - Blending Options, or Layer - Layer Style, or the "eff" icon at the bottom of the Layers panel also start the Layer Style window.

**Comment by avagp** [comment]
So maybe, it will be better to all have the same name...

For me was misleading all the time.

Blending options = Layer Style = Effects

And yes, having the text truncated after 20 characters will also help the work flow.

**Comment by photopea** [comment]
Now, if the layer name is wider than 140 px, it will be cropped to only 140 px.

**Comment by avagp** [comment]
yuhu!  Great!

**Comment by avagp** [comment]
I kinda found a problem with that approach, when the layer is inside folders.
![Screenshot 2019-08-10 at 22 28 36](https://user-images.githubusercontent.com/11801254/62828861-7d302b80-bbbe-11e9-8256-c39f18784b8c.png)

**Comment by photopea** [comment]
You can double-click the area between the "eye" and the thumbnail.

You can also do Layer - Layer Style - blending options.

**Comment by avagp** [comment]
Sorry to bother you with this issue.

Photoshop does not let the layer title go over the fx button:
[image: image.png]
Does not matter how long the text is, or how inside folders it is.

Could it have a similar approach?
