### ISSUE TITLE
Cannot save file as PSD

### ISSUE THREAD

**Issue by stepanov** [photopea/photopea#148]
I modified existing PSD file and saved results as jpeg. But when I tried to save it as PSD I got JavaScript error:
```

10:57:52.560 TypeError: k.add.lfx2.patternFill.v.Ptrn is undefined 1 pp.js:417:381
	fa.Yg https://www.photopea.com/code/pp.js:417:381
	pa.Tq https://www.photopea.com/code/pp.js:1050:205
	pa.prototype.BH https://www.photopea.com/code/pp.js:1050:322
	na.prototype.cD https://www.photopea.com/code/pp.js:1071:451
	lb.prototype.B https://www.photopea.com/code/pp.js:115:421
	E.prototype.B https://www.photopea.com/code/pp.js:848:463
	E.prototype.B https://www.photopea.com/code/pp.js:849:20
	Ca.prototype.vO https://www.photopea.com/code/pp.js:1099:268
	lb.prototype.B https://www.photopea.com/code/pp.js:115:421
	E.prototype.B https://www.photopea.com/code/pp.js:848:463
	Ha.prototype.Af https://www.photopea.com/code/pp.js:1047:269
	bound  self-hosted:915:17
```
You develop amazing tool! Let's make it even better :)

**Comment by photopea** [comment]
Hey! :) can you please share your PSD with us? You can delete some layers etc ... Or send that file to support@photopea.com

**Comment by stepanov** [comment]
Hi, I sent PSD via email.

**Comment by photopea** [comment]
Fixed :)  Your file was made with a recent version of Photoshop. It contains an unexpected format of pattern fill. Now it can be saved as PSD, but I still can't guarantee the full 100% compatibility with these latest Photoshops.

**Comment by Henning29** [comment]
Here is an old psd file saved as jpg, it cannot be saved as psd after changes
![logo-khj-3-gra-cr 50](https://user-images.githubusercontent.com/47607523/52734053-869c5a80-2fc4-11e9-8c8c-1a66e84d909a.jpg)

I have ste same file saved as psd in an old photoshop, but cannot attach it here?

**Comment by photopea** [comment]
Hi, what exactly is the problem? Your JPG seems to work fine in Photopea. You can send us PSD files to support@photopea.com, or you can attach it here as ZIP.

**Comment by Henning29** [comment]
Thanks, here the PDS-file as Zip file, which I only can store as JPG etc., but not as PSD:
[LOGO-KHJ-3-grå-kontur (1)-liten.zip](https://github.com/photopea/photopea/files/2872305/LOGO-KHJ-3-gra-kontur.1.-liten.zip)

Second problem: Some times Photopea open this way, see Hardcopy:
![photopea-hardcopy](https://user-images.githubusercontent.com/47607523/52904374-bf8a3880-322b-11e9-8ff5-378a820d5478.jpg)

Thanks Henning

**Comment by photopea** [comment]
Hi, I opened your PSD in Photopea and was able to save it back as PSD (without any editing).

How exactly did you edit your PSD? Did you add any pattern? I need to be able to reproduce the bug somehow :(
