### ISSUE TITLE
Text and colour layer

### ISSUE THREAD

**Issue by PPA2019** [photopea/photopea#1481]
I have being using photopea for several months, in the most recent use a text layer when moved over a coloured shape or background layer shows partial transparency. This can be temporarily rectified by rastering the text layer but the issue reapears when the text item is moved. Any thoughts?
![text issue a](https://user-images.githubusercontent.com/52412766/60437972-6b468a80-9c07-11e9-827a-8d1d61654392.jpg)

**Comment by photopea** [comment]
Hi, can you save it as a PSD and open it again, does it still happen? If yes, can you send us your PSD file to support@photopea.com ?

**Comment by PPA2019** [comment]
When I save it as a pad and reopen it the could problem has gone; until I try to rearage the text / change properties.

**Comment by photopea** [comment]
So if you open that PSD and move a text layer, it happens again? Can you send it to me, so that I can try it myself?

**Comment by PPA2019** [comment]
See attached
[COLOUR CLICK.zip](https://github.com/photopea/photopea/files/3345779/COLOUR.CLICK.zip)

I have recreated this at 2000px by 2000px and cant recreate the issue.

**Comment by PPA2019** [comment]
Anything under 500*500 on my sample has the issue - above that does not show the problem.

**Comment by photopea** [comment]
Can you update your browser or try another one?

pondělí 1. července 2019 PPA2019 <notifications@github.com> napsal(a):

**Comment by photopea** [comment]
I think updating a browser fixed it.
