### ISSUE TITLE
Shadows / Highlights adjustment

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#1482]
It would be cool to have such adjustment.

**Comment by HolanJan** [comment]
A very good feature that often saves a lot of broken photos, or photos from the strong sun with great contrasts. It can also achieve HDR effect, but more sensitive than the HDR function. I would very much welcome the post in Photopea 

Velmi dobrá funkce, která často zachrání i hodně pokažené fotky, nebo fotky ze silného slunce s velkými kontrasty. Dá se s ní docílit i efektu HDR, ale citlivěji, než přímo funkce HDR. Velice bych funkci přivítal i v Photopea.

**Comment by photopea** [comment]
implemented ... after a year :D

https://blog.photopea.com/photopea-4-8-shadowshighlights.html

**Comment by HolanJan** [comment]
Děkuji!!!

Tak a nyní ten RAW :-)

Jan Holan
tel.: 732 521 835
www.ZvicinaTV.cz
www.Kralovedvorsko.cz
www.Jaromersko.cz


čt 11. 6. 2020 v 18:57 odesílatel Photopea <notifications@github.com>
napsal:
