### ISSUE TITLE
problem with raster mask

### ISSUE THREAD

**Issue by 77misza77** [photopea/photopea#1484]
hi!
i want to cut object from picture. i open picture in photopea. i make a selection. invert and add raster mask show all. mask is clipped but it does not covers only the background - it covers all photo. on every tutorial i watch, mask should cover background without object.  i cant put mask on layer properly. i am not experienced maybe i do sth wrong, maybe you can help please! kind regards

**Comment by MichalSZZ** [comment]
Hi,
try to use mask icon on layer pallet (4th icon from the left) at the bottom of panel.
In photoshop there is 2 other options in menu layer-> layer mask -> Reveal Selection (is one of it). Photopea doesn't have that option.

**Comment by photopea** [comment]
Hi, I added new options: Layer - Raster Mask - Reveal Selection / Hide Selection / From Transparency.
