### ISSUE TITLE
Colour buttons cover menu items

### ISSUE THREAD

**Issue by olafbond** [photopea/photopea#1485]
![image](https://user-images.githubusercontent.com/52509158/60620200-3ee76580-9de3-11e9-933e-d7542f476441.png)

**Comment by photopea** [comment]
Hi, can you update your browser? Colored buttons should have different colors.

The problem happens because of very long phrases in Russian. It would look better in English. Do you know how to translate some items with shorter words?

**Comment by olafbond** [comment]
Hi. Different buttons' colors are due to a Dark Theme mode. It doesn't change the layout.
The current translation looks like standard. The only thing I would suggest to cut words in case of lack of space:
Редактирование = Редакт.
Изображение = Изобр.
Выделение = Выдел.
Просмотр = Просм.
I couldn't see the other menu items.
Here is a screenshot of all my screen with a taskbar hidden: https://www.dropbox.com/s/bd15lg6bk2h3y3s/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA.PNG?dl=1

**Comment by olafbond** [comment]
Another suggestion is to move the ad block down to free more space for the buttons.

**Comment by photopea** [comment]
Hi, I fixed it. When the main top menu is too wide, this list of buttons is hidden.

I also changed the look. It is not so colorful, and Twitter and Facebook labels were replaced with much shorter icons.
