### ISSUE TITLE
Auto-select sometimes doesn't work

### ISSUE THREAD

**Issue by idunnololz** [photopea/photopea#1486]
Repro steps:
1) Open https://www.photopea.com/
2) Select Pointer tool.
3) Check Auto select. Note that it will work.
4) Refresh https://www.photopea.com/
5) Select Pointer tool.
6) Verify that Auto select is already selected.
7) Auto select will not work.

**Comment by photopea** [comment]
Hi, I just tried it and Auto-Select still works for me, even after the refresh :/

Maybe you clicked into a text layer, in a transparent part (like the middle of O). A text layer is selected every time you click into its "rectangle", no matter if the pixel under the mouse is transparent or not.
