### ISSUE TITLE
Brush presets gives incorrect brush size

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1489]
1.) open pea.psd, go to background layer, select Brush Tool, paint with it
2.) now Brush is 15px/100% open Window - Tool Presets - Define New 
3.) right click on image and change brush to 200px/50%
4.) paint with it and in Window - Tool Presets - Define New
5.) right click on image and change brush to 30px/50%
6.) paint with it and in Window - Tool Presets - Define New
7.) now click on second Preset in Tool Presets window
-> brush is changed to 10px/50% ... it should be  200px/50%
(first preset also changes wrongly to 200px/100% brush instead of 15px/100%)

![image](https://user-images.githubusercontent.com/6370548/60645121-2c4b4b80-9e38-11e9-8a51-7f4c53bfb257.png)

**Comment by photopea** [comment]
Fixed, thank you!
