### ISSUE TITLE
Photopea Editor is not opening pictures correctly

### ISSUE THREAD

**Issue by Shawnee06** [photopea/photopea#149]
Photopea Editor is not opening pictures and allowing edits of smartobjects correctly.  I am trying to edit PSD files but the images are not showing up correctly in the tool.

Can you please check this out....here is a screenshot of the issue....

![photopea editor issues](https://cloud.githubusercontent.com/assets/13091599/24455493/631db28e-1455-11e7-9edc-45700a6d5260.png)

**Comment by photopea** [comment]
Hi, thank you for reporting it. I checked several PSD files with smart objects and they seem to work fine. Can you share your PSD with us?  You can send it to support@photopea.com

**Comment by Shawnee06** [comment]
Hey there!

Here is one of my images that I downloaded from Canva and tried uploading
to the tool....

Regards,


[image: photo]
*Kim George*
Founder, YourChicGeek
(972) 696-9309 | kim@yourchicgeek.com | http://yourchicgeek.com
<http://facebook.com/yourchicgeek>  <http://twitter.com/yourchicgeek81>
<http://pinterest.com/yourchicgeek>
Your Chic Geek How to Do a Website Audit
<http://feeds.feedblitz.com/~/285393800/0/yourchicgeek~How-to-Do-a-Website-Audit/>
Get a signature like this: Click here!
<http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MDA4JnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MzI1Njg1NDg3Njk3OTIiLCAiZSI6ICI1NzMyNTY4NTQ4NzY5NzkyIn0=&u=203406367697005>

**Comment by photopea** [comment]
I am sorry, but I can't see your file. Can you send a new email to support@photopea.com ?

**Comment by photopea** [comment]
Thank you very much for reporting it, you are amazing!  :) it was fixed and it should work well now.

**Comment by Shawnee06** [comment]
Sure! Here is the screenshot of what I am getting...
![screenshot of loading error message from photopea](https://user-images.githubusercontent.com/13091599/27226225-8c4ad6d6-5263-11e7-91d3-541a8616dc83.png)

**Comment by photopea** [comment]
Hi, can you send us your PSD file to support@photopea.com ?
