### ISSUE TITLE
PDF including accentuated character import

### ISSUE THREAD

**Issue by koimeria** [photopea/photopea#1491]
Hello,

When the PDF includes accentued characters, strings are not loaded.

In photopea :
![image](https://user-images.githubusercontent.com/52525447/60648301-f742f700-9e3f-11e9-9c5b-12da49db6172.png)

In the original PDF:
![image](https://user-images.githubusercontent.com/52525447/60648437-3bce9280-9e40-11e9-8d53-5002ea377f7e.png)

I'll send the original PDF to support@photopea.com but please don't make it public.

**Comment by photopea** [comment]
Hi, I fixed the problem, thanks for reporting it! :)
