### ISSUE TITLE
Sony a7riii raw files tint bug

### ISSUE THREAD

**Issue by explirer** [photopea/photopea#1493]
Some color tint issues when opening sony raw files.
Tried a few different ones, same result.
![image](https://user-images.githubusercontent.com/52527916/60652234-22314900-9e48-11e9-952c-dc2b29ca7cd8.png)

**Comment by Hello1024** [comment]
Looks like a 8 bit vs 10 bit overflow issue...

**Comment by photopea** [comment]
I was not able to reproduce it with ARW files that I have. Can you send us your file to support@photopea.com ?

**Comment by photopea** [comment]
I just fixed it.

**Comment by photopea** [comment]
I am sorry, it was not fixed properly. Now, it should be properly fixed.
