### ISSUE TITLE
BioFormats

### ISSUE THREAD

**Issue by Javlington** [photopea/photopea#1494]
Dear Ivan,

I am from here: 

https://www.reddit.com/r/IAmA/comments/c8ru2y/i_made_a_free_alternative_to_photoshop_that_is/esq95g5/ 

Following is the home of BioFormats, which is the importer that scientists use for opening their imaging documents: 

https://www.openmicroscopy.org/bio-formats/ 

They often use that importer to get the data into Java applications:

a) FIJI and ImageJ: 

https://fiji.sc/

b) OMERO.insight and OMERO.web: 

https://www.openmicroscopy.org/omero/

They have always been complaining about scientific file format incompatibility with Adobe applications (PS, Illustrator)!

Hope this is informative,

Javlington

**Comment by photopea** [comment]
Hi, thanks for getting in touch! Do you have any examples of such files? Is there one or several formats for such images?

**Comment by photopea** [comment]
I see that BioFormats supports many formats https://docs.openmicroscopy.org/bio-formats/6.1.1/supported-formats.html

Many of these formats are supported by Photopea already. Sadly, we can not use their code directly in Photopea. But we can add new formats. Do you know which ones are the most popular?

**Comment by Javlington** [comment]
Dear Ivan,

Good to hear a lot of formats are compatible! 

From experience, the most popular formats would be LIF (from Leica), CZI (from Zeiss) and OIF/OIR (from Olympus). Those are the big companies dominating the field, and make most commonly used scientific microscopes. 

You already followed up your first reply, but let me know if you'd still like some example images. 

On a related note, Charles University has a central scientific imaging facility, with some absolutely awesome and friendly people staffing it who I have had the pleasure of meeting. I dunno, they could be a useful local connection for anything scientific imaging.

All the best, 

Javlington

**Comment by photopea** [comment]
I just added the support for Leica LIF format. I don't know how reliable it is, since I had only 3 files to test with :/ 

It seems like these files contain many photos of the same thing. Photos are taken at a different time, or a different focal length, or a different shutter speed, etc. I think that the structure of a PSD file is not good for viewing such data. Now, you have to show / hide layers to browse through images. It would be better to have a slider, etc.

Are you talking about the Charles University in Prague? Where are you from? :)

**Comment by photopea** [comment]
I am afraid I have to close this. There are too many formats out there, and they are not publicly documented. 

@openmicroscopy only provide the code. I wish they wrote public descriptions of these formats, too, for others to implement them (as it looks like companies share documentations with them, but not with "mortal" people).

I also wish somebody starts a movement for an open standard for such data, and encourage everybody to use that format (similar to using DNG for RAW). Now, everybody creates their own format, or even several own formats.
