### ISSUE TITLE
Sliders max and min are not at the edges of the slider

### ISSUE THREAD

**Issue by nielsswinkels** [photopea/photopea#1497]
It bugs me that the minimum and maximum values of sliders are not placed where the arrow would touch the beginning or end of the slider line. Is there a reason for this? It gives a wrong sense of scale in my opinion.

![New Project](https://user-images.githubusercontent.com/5718354/60688530-15e3d500-9eb6-11e9-87e8-3f814f8ff05e.jpg)

**Comment by photopea** [comment]
Fixed, thank you! :)

**Comment by nielsswinkels** [comment]
I refreshed and it looks closer, but still there are some pixels xD (Tested on firefox)

![image](https://user-images.githubusercontent.com/5718354/60689012-7a546380-9eb9-11e9-9e32-d7f1b6b9d310.png)

**Comment by photopea** [comment]
We did not design this slider. We just use the Slider HTML element, and your browser decides how it looks like. If you don't like the look, you should report it to Firefox :/
