### ISSUE TITLE
double click to start new file

### ISSUE THREAD

**Issue by nielsswinkels** [photopea/photopea#1498]
Feature request: double click in the empty space next to the filename tab would open the dialog to create a new file.

I'm not sure if it is from photoshop, but I noticed myself doing this.

**Comment by nielsswinkels** [comment]
![New Project2](https://user-images.githubusercontent.com/5718354/60688634-b639f980-9eb6-11e9-9696-40aa68e947a8.jpg)

**Comment by photopea** [comment]
Hi, I implemented it :)
