### ISSUE TITLE
make shape selection popup resizable

### ISSUE THREAD

**Issue by nielsswinkels** [photopea/photopea#1500]
Feature request: I like to be able to resize the popup where you choose the shape, in order to get a quick overview of as many as possible at the same time.

![shape](https://user-images.githubusercontent.com/5718354/60688874-49276380-9eb8-11e9-8961-d5252db9dbda.jpg)

Slightly related side thought: maybe http://thenounproject.com/ could be an interesting partner to implement in here, that you can easily search and buy their icons.

**Comment by photopea** [comment]
Sorry, it would be too hard to implement :(
