### ISSUE TITLE
New file takes dimensions from clipboard

### ISSUE THREAD

**Issue by nielsswinkels** [photopea/photopea#1503]
Feature request: I love it in photoshop that when you copy something/screenshot and then open a new file, it defaults to having the same size as what you have on your clipboard. So that when you paste it fits perfectly. Is that possible?

**Comment by photopea** [comment]
Sadly, it is not possible to read clipboard content until the user pastes it. Imagine you copied a banking password into a clipboard. Then, every website that you open in between, reads your password, without you actually pasting it.

**Comment by nielsswinkels** [comment]
How about having a way when creating a new file to easily select "take the same dimensions as my screen"? That should be possible and might be nice. (Not sure how to handle multiple monitors though)

**Comment by photopea** [comment]
I don't think it will be that useful for people. I don't want to make the UI unnecessarily complex.

BTW. you can paste an image from the clipboard (e.g. a screenshot) into Photopea any time, even with no documents opened.

**Comment by nielsswinkels** [comment]
Good that you defend against feature creep, not an easy thing. 

That pasting function is good to know about though!
