### ISSUE TITLE
SVG parsing fails with whitespace characters before svg tag

### ISSUE THREAD

**Issue by colinsanford** [photopea/photopea#1504]
Hi, I found an svg parsing issue when clicking `open` or `open & place` under the file menu.

SVG files with any kind of line breaks or white space fail with a parsing error

eg:
```svg
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="512" height="512" viewBox="0 0 100 100">
</svg>
```

This screenshot shows the error when there's a line break and a tab character before the opening svg tag (different from my snippet).

<img width="1772" alt="Screen Shot 2019-07-04 at 11 35 13 PM" src="https://user-images.githubusercontent.com/4040290/60696795-45dea880-9eb5-11e9-9740-b3d3effca56d.png">

Amazing app by the way, thanks for all your hard work

**Comment by photopea** [comment]
I fixed it, thank you! :)
