### ISSUE TITLE
Crop tool issue when no layer selected

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1507]
Crop tool not working correctly when no layer is selected. It will always crop from top left corner.

1.) Open pea.psd
2.) Deselect layers (Move Tool-Auto-Select-click outside of image)
3.) select Crop Tool
4.) select some area in the middle of image
5.) confirm
->
wrong part of image is cropped (as if area was selected from top left corner)

**Comment by photopea** [comment]
Fixed, thank you! :)
