### ISSUE TITLE
Slices and canvas size change

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1508]
When I create some slices and then change canvas size (Image - Canvas Size) or image size (Image - Image Size) or use Crop Tool I would expect positions and sizes of slices will adjust accordingly so they are above same part of image - now you need to delete them all and recreate them by hand i guess...

**Comment by photopea** [comment]
Hi, I make Canvas Size, Image Size and the Crop tool modify slices.

Of course, if you crop with rotation, or do a Perspective crop, you will get nonsense.
