### ISSUE TITLE
Reordering layers

### ISSUE THREAD

**Issue by randomd00d** [photopea/photopea#151]
Is it possible to reorder layers? I've tried moving one layer under another one, by click-and-dragging it within the layer window, and that did nothing. I also tried using keyboard shortcuts for layer reordering (CTRL + ] for PC, CMD + ] for Mac), and that also did nothing (though I didn't really expect it to :) ).

I did get around the issue, by doing this:

0.  original setup: PSD file with multiple layers. Wanted to put layer_0 (at the very bottom) above layer_1 (which was right above it).
1.  duplicating layer_0 into another file (let's call it FILE_2)
2.  returning back to the original file, and selecting layer_1
3.  going to FILE_2, and duplicating the layer_0 back into the original file
4.  now I have layer_0 at the bottom, layer_1 right above it, and the copied layer_0 right above layer_1
5.  after deleting the bottom layer_0, I am left with layer_1 (which is now at the bottom), and layer_0 (duplicated from FILE_2)

**Comment by photopea** [comment]
You should be able to reorder layers by clicking, dragging and releasing them. Look at this video at the time 5:20 https://www.youtube.com/watch?v=4FNCA5kdq5A  During the dragging, there will appear a thick line, which marks the place, where the layer will be inserted.

Let me know if it works.

**Comment by randomd00d** [comment]
I see what you mean, and I did try exactly that. However, unlike in the video, the layer I select doesn't even begin to move, nor do I get the little green circle with the white plus. All layers stay in place. I'm using Firefox 52.0.2.

Will give it a go in Chrome (like the person in the video was doing), and get back to you.

**Comment by photopea** [comment]
I just tried it in Firefox and it does not work either :( I am very sorry for that. I will try to fix it as soon as possible.

**Comment by randomd00d** [comment]
No need to apologize, really. I'll test it out in other browsers (Chrome, Opera, Edge, Safari) and let you know how things work out.

**Comment by photopea** [comment]
I think that I found a bug in Firefox and I reported it to Firefox developers 
https://bugzilla.mozilla.org/show_bug.cgi?id=1352852 . I am 99% sure, that dragging layers worked in previous versions of Firefox.

Until they fix it, I made a work-around, so now, dragging layers works in Firefox, too.
