### ISSUE TITLE
It is impossible to save the PSD file as a one jpeg file.

### ISSUE THREAD

**Issue by unaluna8** [photopea/photopea#1511]
My psd file is prepared in Photoshop. There he was already divided into equal parts (slices). When  I open it in Photopea the order of the pieces(slices) is numbered incorrectly. When  I try to save this psd as 1 jpg Photopea automatically cuts it into pieces. I can not save this psd as a separate jpg file.

**Comment by photopea** [comment]
When you save a document with slices as JPG, I added an option "As Slices". Uncheck it, to save the document as a single JPG.
