### ISSUE TITLE
"Replace Color" tool eliminates transparency

### ISSUE THREAD

**Issue by nkizz** [photopea/photopea#1512]
I loaded a PNG with transparency into Photopea, and then selected "Replace Color". Both in the preview and the final product, the transparency was converted to a white background.
Before:
<img width="545" alt="Before" src="https://user-images.githubusercontent.com/12008806/60760528-c4962b80-a004-11e9-8063-305b6d526ec2.png">
After:
<img width="560" alt="After" src="https://user-images.githubusercontent.com/12008806/60760532-ceb82a00-a004-11e9-90ef-8f1119733f6b.png">

**Comment by photopea** [comment]
Hi, do you mean Image - Adjustments - Replace Color?  This adjustment should not change the transparency of pixels. Can you record a short video of what you did?

Are you sure you did not save as JPG in between?

**Comment by nkizz** [comment]
This shows what's happening: https://imgur.com/a/kJesFXX
You can see the checkerboard behind it, then not.
Thanks for the quick response!

**Comment by photopea** [comment]
There really was a bug. I fixed it. Thank you for reporting it! :)
