### ISSUE TITLE
Feature request: Flatten Image (/layers)

### ISSUE THREAD

**Issue by rcoenen** [photopea/photopea#1513]
As far as I can tell Photopea has no option to simply flatten all layers into.. well.. a flattened image right? please add, should be simple and such a useful feature

https://www.dummies.com/software/adobe/photoshop/how-to-flatten-an-image-in-adobe-photoshop-cs6/

**Comment by photopea** [comment]
I was always scared about adding too many items into the Layer menu. Also, I never needed to flatten all layers while editing photos :/

In layers panel, you can select all layers (click on the top one, hold Shift, click on the bottom one) and do right-click - Merge Layers. Isn't it sufficient?

**Comment by rcoenen** [comment]
I use it all the time. Especially when I have transparent parts in my layer composition: flatten image basically puts a "Background" layer back (defaulting to the active background colour) and then flattens all layers. Also Photopea is my fave tool when doing quick and dirty image manipulation, on laptop sometimes Ipad. There is no easy way to right-click here.

**Comment by photopea** [comment]
Ok, I added an option Layer - Flatten Image :)

**Comment by hxim** [comment]
I just tried and it only merges layers. You need to remove transparency (replace all transparent pixels with background color) to implement Flatten image as in other editors.

**Comment by photopea** [comment]
I know, that in Photoshop, the Background is a special kind of layer, which can not have Transparency.

But I thought that maybe we can allow people have Backgorund with transparency. Isn't it better?

**Comment by hxim** [comment]
I am not sure it may be confusing when it behaves differently.

**Comment by rcoenen** [comment]
Cheers!

**Comment by photopea** [comment]
So the transparency should be replaced always with a white color? That is how it works in Photoshop (foreground/background colors are ignored).

**Comment by rcoenen** [comment]
Ok I was't sure but yes I believe it's always white indeed

**Comment by photopea** [comment]
Ok, I added a white background when flattening.

**Comment by hutber** [comment]
Ha... 7 years later almost, but how do we flatten single layers? I can only see "flatten image"

Would it make more sense for "Flatten image" to be in the image menu and then have a flatten layer in the layer menu?

**Comment by photopea** [comment]
What is flattening a layer?

**Comment by hutber** [comment]
It would work the same way as flatten image, but with an individual layer. So maybe I want to take a vector image and make it "flat" aka not a vector anymore. Just an example, but that was how I used to work with fireworks when I needed to. :)

**Comment by rcoenen** [comment]
> It would work the same way as flatten image, but with an individual layer. So maybe I want to take a vector image and make it "flat" aka not a vector anymore. Just an example, but that was how I used to work with fireworks when I needed to. :)

I believe that what you mean here is "rasterizing" the layer - a different thing.

**Comment by hutber** [comment]
Interesting, I thought this was just telling the layer to "allow me to edit" I did no realise this actually changed anything on the layer. Thats good to know then, thank you

**Comment by photopea** [comment]
A document can have many layers (the list of Layers is "deep"), or it can be just one layer ("flat"). Flattening a document means putting all layers into one layer.

Rasterizing a layer means converting a "specail" type of layer (e.g. a text layer) into a simple pixel layer (you will not be able to edit it with the text tool anymore).
