### ISSUE TITLE
Oswald font is displayed as an italic on regular and some other variations  

### ISSUE THREAD

**Issue by elkarina** [photopea/photopea#1514]
Can't make it work properly. Some variations of Oswald font are displayed as if they were italic. I tried to load the font I need from my computer previously downloaded from google font. But it s still overrides by the italic variation from Photopea ((

**Comment by photopea** [comment]
Hi, I fixed it, you should see both Italic and non-Italic versions of the Oswald in Photopea. There is no need to load your own Oswald now :)
