### ISSUE TITLE
Flashing is an annoyance but it is also a danger to those with epilepsy

### ISSUE THREAD

**Issue by modbotmaker** [photopea/photopea#1515]
This is quite an annoyance when using Photopea but if someone using it is epileptic, this stuff can cause seizures. This needs to be fixed.

![81LPYFvXoG](https://user-images.githubusercontent.com/17211100/60762676-9c192c00-a01a-11e9-9c26-edb3769dd09f.gif)

**Comment by photopea** [comment]
Hi, this never happened to me :/ Does it happen with any image, when you draw and move a Selection?

What browser do you use?

**Comment by modbotmaker** [comment]
> 
> 
> Hi, this never happened to me :/ Does it happen with any image, when you draw and move a Selection?
> 
> What browser do you use?

It happens with any image, I was redoing a logo that one of my friends had for a Discord server because I wanted to and I had this stuff happen. Plus it is also happening in that gif of a new image i just threw together to get proof of the flashing.

I'm using Mozilla Firefox.

**Comment by photopea** [comment]
I can not make it happen in my latest Firefox on Windows 7 :(

Are you using the latest Firefox 67.0.4 ? What is your OS?

Is it happening with a grid off, or only when it is on? Do you see any errors in a Web Console?

**Comment by modbotmaker** [comment]
> 
> 
> I can not make it happen in my latest Firefox on Windows 7 :(
> 
> Are you using the latest Firefox 67.0.4 ? What is your OS?
> 
> Is it happening with a grid off, or only when it is on? Do you see any errors in a Web Console?

It happens without the grid.

I'm using Windows 10 Pro build #17134 and Mozilla Firefox v67.0.4 64bit

**Comment by modbotmaker** [comment]
Plus this is what the F12 console was showing on photopea:
![image](https://user-images.githubusercontent.com/17211100/60765923-b40ea100-a056-11e9-82a6-388a097558c3.png)

**Comment by photopea** [comment]
This looks normal. Does it still happen when you disable WebGL (More - Use WebGL) ?

**Comment by modbotmaker** [comment]
> 
> 
> This looks normal. Does it still happen when you disable WebGL (More - Use WebGL) ?

I tried looking around in the More section and found no "Use WebGL" option.
![image](https://user-images.githubusercontent.com/17211100/60776435-00062800-a0e1-11e9-95c7-317271ee8fdb.png)

**Comment by photopea** [comment]
I mean the More section in Photopea: https://imgur.com/rTwgMIK

**Comment by modbotmaker** [comment]
Well, it seems that WebGL is causing the issue. (I just turned it off a few minutes ago)

**Comment by photopea** [comment]
WebGL makes Photopea faster. There should not be any flashing even with WebGL on.

What is your OS? Can you update it? Or can you update GPU drivers separately?

**Comment by modbotmaker** [comment]
DirectX stuff I have is DX12 and windows did update last night.

**Comment by photopea** [comment]
Did you experience the flashing elsewhere on the web, or in games? Can you try it in Chrome, if the flashing happens, too?

**Comment by modbotmaker** [comment]
The flashing only happens in photopea. It doesn't happen in Final Fantasy XII, Skyrim albeit with a decent amount of mods, Sid Meiers Civilization V and VI and other games. It also doesn't happen anywhere else other than photopea.

**Comment by photopea** [comment]
I think it is a browser-related issue. Can you try it in Chrome, Opera or any other Chromium-based browser?

**Comment by modbotmaker** [comment]
The flashing isn't an issue in the Brave browser. (Its a chromium-based browser)

**Comment by photopea** [comment]
Do you think you could report this to Firefox developers and discuss it with them (as I can not reproduce it on my computer)? https://bugzilla.mozilla.org/enter_bug.cgi

I think it is curcial to report bugs to Firefox. Otherwise, it will be very buggy, and people will switch to other browsers, and only Chromium browsers will remain at the end.
