### ISSUE TITLE
Open SVG file

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1517]
This SVG file cannot be opened in Photopea.
It says "Unexpected file structure. Please, send your file to support@photopea.com and we will solve it" and "Not enough RAM! (need 4398046511104 MB)"

It is because of irrelevant (and empty) clippath with very large coodinates (outside of bounds of image i think). When edited to small values or removed it will open no problems.

```
<clipPath clipPathUnits="userSpaceOnUse" id="clipPath1"
      ><path d="M-1073741824 -1073741824 L1073741824 -1073741824 L1073741824 1073741824 L-1073741824 1073741824 L-1073741824 -1073741824 Z"
      /></clipPath
      >
```

[473.zip](https://github.com/photopea/photopea/files/3365750/473.zip)

**Comment by photopea** [comment]
Hi, I made an exception. If a vector shape needs more than 400 megapixels, it will be rasterized into a 100x100 rectangle. 

Note, that your SVG still takes a long time to render, because of the clipping masks.
