### ISSUE TITLE
Add Apple Touch Icon

### ISSUE THREAD

**Issue by MuffinMedic** [photopea/photopea#1518]
Adding Photopea.com to the home screen of an iOS currently uses a screenshot of the page as the icon. An Apple touch icon would allow iOS to show the Photopea logo in place of the screenshot as the home screen icon.

**Comment by photopea** [comment]
I added such HTML tag. It should work now.

I believe Safari will understand a standard "icon" tag in the future, just like other browsers do, so we will be able to remove it.
