### ISSUE TITLE
Scripting not able to link layers

### ISSUE THREAD

**Issue by JorVLP** [photopea/photopea#1519]
It does not seem to be possible to link layers in scripts

````
var layer1 = app.activeDocument.layers.add();
var layer2 = app.activeDocument.layers.add();

layer1.link(layer2);
````

Expected Result:
creates 2 layers and they are linked (have the chain link when selected in layers panel)

Actual Result:
creates 2 layers which are not linked

**Comment by photopea** [comment]
Hi, I am sorry, Layer.link was not implemented in Photopea. I just implemented it :)
