### ISSUE TITLE
Create a layer out of a selection

### ISSUE THREAD

**Issue by randomd00d** [photopea/photopea#152]
In Photoshop, there's an option to create a layer out of what's selected from another layer, like in the images below. Is it possible to do the same in Photopea?
![01](https://cloud.githubusercontent.com/assets/26855143/24598401/7b66cdb8-184b-11e7-86d3-41219d518f72.png)
![02](https://cloud.githubusercontent.com/assets/26855143/24598403/7e1f9076-184b-11e7-96af-c816cd749c1e.png)
![03](https://cloud.githubusercontent.com/assets/26855143/24598405/801e9e8a-184b-11e7-895c-27af7e7253de.png)
![04](https://cloud.githubusercontent.com/assets/26855143/24598406/825bd2ee-184b-11e7-822d-6762801fcee8.png)

**Comment by photopea** [comment]
I believe you can do the same thing by pressing Ctrl+C, Ctrl+V (or Edit-Copy, Edit-Paste).  Do we really need a menu item for it?

**Comment by randomd00d** [comment]
Not at all, I was just unsure how to go about it. CTRL + C, CTRL + V is fine.

**Comment by photopea** [comment]
Let's keep it open, I would like to add this feature to Photopea too.

**Comment by photopea** [comment]
We have added Layer - New - Layer via Copy. It also works using Ctrl + J.
