### ISSUE TITLE
Type Tool - Buttons not working second time

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1520]
When using buttons in bottom of Character window or in toolbar of Type Tool (align text buttons) they sometimes not work when clicked second time.
for example:
1.) open pea.psd (you are in Welcome layer)
2.) select Type Tool
3.) go to Character window
4.) click first button in bottom (fake italic button) - now works OK
5.) click first button in bottom (fake italic button) again - now not button is deactivated but no action happens (text is still in italic)

---

or 
1.) open pea.psd (you are in Welcome layer)
2.) select Type Tool
3.) click left button in toolbar (align from left) - now works OK
4.) click middle button in toolbar (align from center) - nothing happens but style of button changes so it looks like it was activated

**Comment by photopea** [comment]
I fixed it. I hope I did not introduce new bugs by my fix :/
