### ISSUE TITLE
Issue with long menu on small touchscreen

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1521]
On phone with small screen when I press Edit (in menu) it opens pop-up over my finger (height is too big to fit on screen) and automatically executes Undo/Redo as I remove my finger making it very hard to access other items in this menu. I think pop-up should open just below main menu element as for items where height is small enough to fit on screen.
![image](https://user-images.githubusercontent.com/6370548/60798344-7dbd4880-a160-11e9-9ac0-d580b020a743.png)

**Comment by photopea** [comment]
I think I fixed it. Thanks!
