### ISSUE TITLE
Umlaut issues with ChunkFive

### ISSUE THREAD

**Issue by Lehmax** [photopea/photopea#1522]
How to reproduce the issue:
- Choose the Type Tool
- Use ChunkFive Roman
- Type a special character like äöü or ß

Result: Font switches back to the default, because these characters are not supported.

Possible fix: Updating ChunkFive to the latest version found [here](https://github.com/theleagueof/chunk). When I use the latest version locally or when I load the font into photopea and choose ChunkFive Regular instead of Roman, the special characters work.

**Comment by photopea** [comment]
We get our fonts from public databases like FontSquirrel, Google Fonts and many others.

I asked FontSquirrel to update ChunkFive, and once they do, we will update Photopea, too :)

**Comment by photopea** [comment]
Hi, FontSquirrel updated their database, and we updated ours :) it should work well now.
