### ISSUE TITLE
Slow speed + frequent crashing

### ISSUE THREAD

**Issue by JHJ467** [photopea/photopea#1523]
The program is quite slow and crashes frequently in the middle of projects. I've tried both Chrome and Firefox, and I'm working on a PC. I've seen the posts about possible RAM restrictions/limited RAM, but are there ways around that? Thanks!

**Comment by photopea** [comment]
Hi, how large are your doucments, e.g. when you save them as PSD? How much RAM do you have on your PC?

**Comment by JHJ467** [comment]
My file size is 13.7MB and I have 7.88GB RAM on my PC...!

**Comment by photopea** [comment]
That is really strange. What is the resolution of your file? You can see it in Image - Image Size. 

Also, is WebGL supported on your computer? Check it in More - Use WebGL.

**Comment by JHJ467** [comment]
Oof, yeah, the resolution is 19489 x 13780 pixels - trying to make a
poster-size image :'D

And yes, WebGL is supported 👌

**Comment by photopea** [comment]
19489 x 13780 is quite a log. I guess every program would be a bit slow with so large images. It is actually 266 Megaipxels, much more than regular cameras have. I think you should be fine with decreasing the dimension (or the DPI).

Regarding Crashing: a full-size layer in so llarge document requires 1 GB of RAM. You would not be able to create that many layers. Also, Chrome kills (crashes) every website, which tries to use more than 4 GB of RAM. Try to use Firefox instead, which does not have such problem.

**Comment by JHJ467** [comment]
Yeah, thanks for the info...!

I did use firefox before I tried chrome, and both crashed frequently. Guess
I should just stick to normal pics from now on >.<

Thanks!

**Comment by photopea** [comment]
I recommend to use smaller images (e.g. 10 000 x 7 000 pixels), or buy more RAM. 8 GB is not enough for such work.

**Comment by Willz7** [comment]
I am also experiencing slowness when creating a flyer on Photopea.com

**Comment by photopea** [comment]
@Willz7 you should tell us more details.

Slowness is normal, when your document has tens of millions of pixels. What is the size of your document? What exactly is slow?

**Comment by Willz7** [comment]
How can I check how big is the document?

**Comment by photopea** [comment]
Image - Image size.

**Comment by Willz7** [comment]
Picture size width 2551, height 3579, DPI 300. The reason I said it was slow is because it wasn't moving as quickly as I anticipated on Vividi when I moved an picture from side to side into photopea, Chrome and I tested it on Firefox and the slowness managed to go away on Firefox.

**Comment by photopea** [comment]
Is WebGL enabled in Chrome? See More - Use WebGL.

**Comment by Willz7** [comment]
WebGL is disabled on Chrome, should I enable it?

**Comment by photopea** [comment]
Yes, WebGL can make redrawing the document 20x faster.

**Comment by Willz7** [comment]
I have enabled it and I will report back.
