### ISSUE TITLE
Fuji .RAF Raw file not recognized

### ISSUE THREAD

**Issue by wtfmate1337** [photopea/photopea#1524]
If this thing doesn't recognize Raw files from a major camera manufacturer, I'm really not sure what the point of it is...

**Comment by photopea** [comment]
Hi, we support uncompressed RAF files now. Are your RAF files compressed or uncompressed?

**Comment by wtfmate1337** [comment]
Compressed.

**Comment by dwbmb** [comment]
This was surprise to me too. I wanted to try Photopea with my pictures but compressed .RAF are half in size so I am using them.

**Comment by photopea** [comment]
Fujifilm is doing the best they can to prevent you from opening their photos in something other than their software (or the software of those who paid them). I guess you were aware of that when getting their cameras :/

**Comment by dwbmb** [comment]
Well, this was not exactly written on the box, actually after years of using it I found out couple seconds ago after you wrote it.

Not a crucial function though, I can export pictures to TIFF from Lightroom and work with TIFF in Photopea. Tested and working.

**Comment by photopea** [comment]
Maybe Lightroom will let you convert your photo to .DNG raw format. Photopea works very well with DNG. Some cameras can save photos directly in DNG format.

**Comment by wtfmate1337** [comment]
Well, I sold the thing so I'm over it!

Thanks for your help, though!

**Comment by IamFlea** [comment]
I think we should be able to open the most of compressed RAF files now. However, we still need some files that are loosely compressed. :) As soon as we encounter loosely RAF compression, I will implement it asap. I think we can close this thread right meow. :)

**Comment by dwbmb** [comment]
Yes and thank you, it works. Meow.

**Comment by photopea** [comment]
It took almost two years, but we finally did it! Thanks @IamFlea  :)
