### ISSUE TITLE
[BUG?] Background behaviour sees broken

### ISSUE THREAD

**Issue by rcoenen** [photopea/photopea#1525]
See video https://www.youtube.com/watch?v=Lc9McgpV0eY

This behaviour is different from Photoshop IIRC:
1) I have created 2 layers (background + 1 layer on top.. yes I am counting the background as a layer here b/c that is how Photoshop seems to do it too... simply the "background" layer)
2) the background layer is by default position locked. But in Photoshop the minute you cut away anything in the background layer it unlocks (again: I a doing this from memory but I am pretty sure) so that you can use it like any normal layer
3) OK You could argue that I could manually unlock first (by clicking on "position" which is weird, in Photoshop you click on the actual lock icon). In Photopea clicking the lock icon does.... nothing. It took me a while to understand this because again this behaviour is different from how it remember it from Photoshop. (See from 1m26s how I am trying to click the lock icon.. nothing.. right-click.. mm, yes layer popup menu, but no unlock layer nothing.. ok weird. Confused)
4) I then carried on cutting away parts of the background layer so it has translucent "holes" in it and ended up with a straaaange situation where an empty area remains selected (around 2m03s) and auto-select too enabled clicking anywhere else does not work properly
Altogether a bit of a buggy mess combined with behaviour quite different from Photoshop.

**Comment by photopea** [comment]
Background layer in Photoshop can not have transparent pixels.

2. When you cut away from the Background layer in Photoshop, the area is filled with a background color. I think making it empty better.
3. I changed the behaviour of the lock icon. When you click it, it removes all locks.
4. I changed the behaviour too. Now, it should correspond to the PS. I am sorry I did not notice it earlier. I neve use Photopea with Auto-Select or Transform controls.

**Comment by rcoenen** [comment]
Don't be sorry! You are doing an amazing job. I just figure to report usability issues that I run into while actually trying to use it as someone who used Photoshop for years. Your quick response to it makes it all better & easier for us! Brilliant work!

**Comment by rcoenen** [comment]
BUT! when cutting in the background layer, it should fill with the background layer. As long as the layer in "Background" modus that is. Why is introducing any inconsistency with the way how it worked in Photoshop for many may years any better? It's just more... confusing?

**Comment by rcoenen** [comment]
(.. I actually used the Photoshop selection-cut-in-background-fill-with-solid-background-color technique a lot!)

**Comment by rcoenen** [comment]
also watch the video from 2m00s to 2m03s ...  at 2m00s I am left with a selection of 'nothing', then click on the transform tool and at 2m03 I am left with a transform selection of a piece of.. nothing?
Then in order to try and get rid of the 'nothing' transform I try to click on the geen pixels in Layer 1 (at 2m11s, with the 'auto select' tool enabled) which does not work. a "This layer is locked" popup shows up. This is not correct, Layer 1 is unlocked. It seems auto-select fails to detect I clicked on the green pixels in Layer 1.

![image](https://user-images.githubusercontent.com/753704/60850030-5fd10180-a1bb-11e9-9224-898f13e2e42b.png)

**Comment by rcoenen** [comment]
See here I click on the green pixels in Layer 1 with Auto Select enabled. Expected behaviour: it should unselect the Background layer, cancel the transform of the empty rectangle in the background layer, select layer 1, and show a transform box around the green pixels.



![image](https://user-images.githubusercontent.com/753704/60850232-51cfb080-a1bc-11e9-91ac-3fb0f4e5f12a.png)

**Comment by photopea** [comment]
@rcoenen  Regarding your last message, as I said, it was fixed. If you click on the green pixels of Layer 1, you can drag it. However, the "transform rectangle" always stays around the selection. That is the behaviour of Photoshop.

**Comment by rcoenen** [comment]
@photopea I understood you fixed it and that is awesome. However, I think we have a slight miscommunication. Let e illustrate what I meant with the image below as an example:

Imagine that currently the Background layer is active.
I have drawn a bounding box (purple box around the green pixels) to illustrate where Layer 1 starts and ends. Everything inside the box is Layer 1, everything outside the box is not Layer one (and in this example thus Background layer)

**Behaviour in Photoshop** when clicking with Auto Select turned on.
point A: Background layer remains selected
point B: Layer 1 gets selected
point C: Layer 1 gets selected 

**Behaviour in Photopea** when clicking with Auto Select turned on.
point A: Background layer remains selected
point B: Background layer remains selected
point C: Layer 1 gets selected 

See the difference? In Photopea I *really* need to target and click a filled pixel in Layer 1 to get Layer 1 selected. If you accidentally click on an "empty" pixel, Layer 1 does not get selected. However, In Photoshop, I can kinda click roughly in the correct area and Layer 1 gets selected.

Hopefully, this illustration clears up what I was trying to report on. Thanks!

![image](https://user-images.githubusercontent.com/753704/60858151-31fbb500-a1db-11e9-9bc2-febb65ccd990.png)

**Comment by photopea** [comment]
Hi, this is not how Photoshop works. Your "Behaviour in Photopea" is how Photoshop works.

Imagine you have 100 layers, but the layer on top has a brush stroke from the top left corner to the bottom right corner. You wold not be able to auto-select any layer below, as every click would be inside the bounding box of the top layer.
