### ISSUE TITLE
Feature Request: Exposed Channels

### ISSUE THREAD

**Issue by theironpaw** [photopea/photopea#1526]
Hello,

My recommended request is to add [Channels](https://i.imgur.com/ga1Kz57.png) to Photopea

For the Games and VFX Industry, we store Black and white images within the RGB+A Channels to save space. Here are some examples from photoshop of two examples: https://imgur.com/a/xQ1BakI
Showcasing how it works. 

Most game engines like, [Unity](https://unity.com/) and [Unreal 4](https://www.unrealengine.com/en-US/what-is-unreal-engine-4) read RGBA channels and we use it to optimize our work. 

The Format we export into game engines is usually [TGA](https://en.wikipedia.org/wiki/Truevision_TGA)

Here is some more information on why in the games and vfx industry we do this (http://wiki.polycount.com/wiki/ChannelPacking)

I am a teacher from a CG school in Australia. We have been looking at photoshop alternatives. And reviewed Photopea as a potential replacement. The only thing missing from the pipeline that we use every day in photoshop, is the ability to edit and change channels within an image. (as described above). 
I saw the IAmA and decided to reach out if it was a feature you were looking into the future.

**Comment by photopea** [comment]
Hey, thanks for getting back! 

Does Photoshop allow you to store data into the Alpha channel, too? I always thought, if any pixel is transparent (Alpha is Zero), RGB values of this pixel are lost (as they are usually not important).

In Photoshop, I can Erase with an Eraser tool, to set Alpha to Zero. But is there a way to set alpha back to 100% and see the original pixels?

**Comment by theironpaw** [comment]
Hey, thank you also for getting back and responding. 

I have recorded a video, showcasing how the Games/VFX use the channels in photoshop. 
https://youtu.be/XIkYvQpjWsE 

Essentially we typically don't use the eraser, as its a destructive workflow we usually use the Alpha Channel as a Black and white image to depict what is visible and what is not. Without losing the pixels within the RGB. 

We also use all, Red, Green, Blue And alpha Channels to store Black and white masks that we utilize within the 3d engine. (as per the previous post, and the video linked) 

The other key element is the format [.TGA](https://en.wikipedia.org/wiki/Truevision_TGA). which is the standard Image format we use for games and film for textures for 3d models. (which I think Photopea, doesn't support yet). Saving the image off as a 32bit.TGA guarantees the extra additional alpha channel is carried across in the file. 

Let me know if you have any additional questions happy to help out.

**Comment by theironpaw** [comment]
Hey, thank you also for getting back and responding. 

I have recorded a video, showcasing how the Games/VFX use the channels in photoshop. 
https://youtu.be/XIkYvQpjWsE 

Essentially we typically don't use the eraser, as its a destructive workflow we usually use the Alpha Channel as a Black and white image to depict what is visible and what is not. Without losing the pixels within the RGB. 

We also use all, Red, Green, Blue And alpha Channels to store Black and white masks that we utilize within the 3d engine. (as per the previous post, and the video linked) 

The other key element is the format [.TGA](https://en.wikipedia.org/wiki/Truevision_TGA). which is the standard Image format we use for games and film for textures for 3d models. (which I think Photopea, doesn't support yet). Saving the image off as a 32bit.TGA guarantees the extra additional alpha channel is carried across in the file. 

Let me know if you have any additional questions happy to help out.

**Comment by photopea** [comment]
Ok I understand it now. BTW. have you thought about switching from TGA into grayscale PNG images? I am 100% sure, that four grayscale PNG images will be smaller, than one 32bit TGA image. You would be able to edit PNGs anywhere, compared to TGA, wich is not always supported.

I know, that TGA was popular in 80s and many games keep using it until today. But after the invention of PNG in the end of 90s, you can fully replace TGA with corresponding PNG files. 

BTW. Photopea can load TGA images, but it can not save them, as I thought such format is obsolete and should not be used nowadays.

**Comment by theironpaw** [comment]
Hey, 
Yeah, 100% right that PNG overall would be smaller in size and is also the other preferred option for a lot of developers. It's definitely older habit's kicking into why I pick TGA. Probably due to Unreal Engine strictly supporting that format and not (JPG's and PNG's until later in its life). 

It has got me thinking, so I've asked a few people in various industries and will post back once I've got a response. Regarding TGA usage within the industry and its relevance.  The stock standard formats are usually, (JPG, EXR, PNG, TGA, TIFF) it does come down to the personal preference of what you choose in the end. 

All n all, though, being able to pack/edit the RBGA channels is something we use a lot in our pipeline. So as a potential feature to Photopea, you will win over the game devs and other VFX related industries. Thanks again for taking your time responding, and making a wonderful web app Photopea. 

I'll keep spreading the good word of what you are doing with this app, and look forward to future updates :) keep up the great work.

**Comment by theironpaw** [comment]
Asked some peeps in various studios. The format doesn't matter. TGA, is just one of many options. Most studios that have proprietary pipelines have scripts that convert it to .dds or it's converted into the correct format during manual import into the engine. Some pipelines straight-up import PSD and the game engine will detect the black and white Alpha Channel (Unreal engine does this). 
Overall its personal preference which to choose, that which doesn't impact the quality of the final texture.

**Comment by photopea** [comment]
Regarding TIFF: it can use many compressions inside. It can use JPEG inside, which makes it equivalent to JPG. It can use raw sensor data, which makes it equivalent to EXR. It can use DEFLATE compression, which makes it like PNG. It can use PackBits RLE encoding, which makes it equivalent to TGA :D

I will add the support for Channels into Photopea: https://github.com/photopea/photopea/issues/285
