### ISSUE TITLE
Crop tool not working as expected

### ISSUE THREAD

**Issue by pjen66** [photopea/photopea#1527]
Use case: The image area I select needs to be cropped and resized to 600x300px.

As is: Having chosen the crop tool, I can the choose "Fixed Size" and type in 600 by 300. After that, I can still choose an image area of any aspect area. 

To be: I would expect the aspect area selector to be fixed to 2:1 as this is the aspect ratio of the cropped image. 

Hope this helps - keep up your incredible work :)

**Comment by photopea** [comment]
Hi, thanks!

After you choose Fixed Size and enter 600 by 300 (and confirm with Enter or by escaping the text box), you should see a 600x300 rectangle in the middle of a document. You can move it around, to choose where you want to crop.

But you are right, if you delete that rectangle and draw a new one, it should keep the aspect ratio. I just made it work that way :)

**Comment by pjen66** [comment]
Thanks - the selection tool works as I expected now :)

Next problem: Having typed in 600 x 300 and completed the cropping, the image does not end up being 600 x 300 pixels. The size will depend on the size of the selection.

**Comment by photopea** [comment]
When you start a Crop Tool with a selection, the default rectangle is placed around it. 

But if you really enter 600x300 and confirm it, it should create a new rectangle 600x300, and crop according to it.

**Comment by photopea** [comment]
I made an update: When you start a Crop tool with a selection, and the crop rectangle is around the selection, the Constraints will switch back to Free (as Fixed Ratio or Fixed Size would not be applied at this moment).

**Comment by pjen66** [comment]
You are awesome - so quick!

But perhaps I am not making myself clear: In Photoshop, the cropping tool can crop AND resize to the desired size in one operation. So no matter how much or how little of the image you select, the resulting image will always end up having exactly the specified size. This is literally the single feature I use most of all in Photoshop. So I can't see myself relying on Photopea if this feature is not available.

**Comment by photopea** [comment]
I am afraid I do not understand what you mean.

Can you describe step-by-step, what you do in Photoshop, and what happens?

**Comment by photopea** [comment]
I think I understand now. If you enter a Fixed Size of 600 x 300, and draw a rectangle of 900 x 450, Photoshop will crop and scale down the image, to make the size 600 x 300. But that is not what the crop means :( If there is a circle 50x50 px in your image, it should not become bigger or smaller after **cropping**.

**Comment by pjen66** [comment]
I understand your philosophy :) 

I don't know if your strategy is to offer "Photoshop-as-a-web-app". But if so, I think you should be aware that what I described *is* one of the ways Photoshops cropping tool can work (W x H x Resolution). I for one find this combined crop-and-resize feature incredibly useful.

**Comment by photopea** [comment]
Ok, I made Photopea work this way :)

**Comment by pjen66** [comment]
Awesome!!
