### ISSUE TITLE
Tool resets after selecting with hotkey

### ISSUE THREAD

**Issue by DillanV** [photopea/photopea#1528]
I've been using Photopea for a while, and it's great. However, if, lets say, I selected the Pencil tool instead of the Brush tool, and I pressed B for the pencil hotkey, it would reset back to Brush, when I would like to keep it to Pencil. If I select it by the toolbar on the left, it works fine, but not for hotkeys. Is it possible to fox this?

**Comment by photopea** [comment]
Ok, I made it work like that.

But what if you have a Brush tool, and you keep pressing B? Should it switch to the next tool in a brush group (as it works now), or should it always stay on the last tool, that was chosen manually from the group?
