### ISSUE TITLE
new user to photoea - need help with PSD  resume 

### ISSUE THREAD

**Issue by jsigler17** [photopea/photopea#153]
I have a PSD resume template I cannot figure out how to change the original text and edit to update with my personal text for resume purposes. Any pointers would be greatly appreciated! Also, I need to insert a photo as well, and I cannot seem to do that either

**Comment by jsigler17** [comment]
If someone from photopea has an email address, I'm happy to send over my template to help elaborate on my questions/issues. Thank you again!  Jared

**Comment by photopea** [comment]
Hi, you should choose a Type tool, click on text and type. If it does not work, send us your PSD to support@photopea.com

**Comment by photopea** [comment]
I have to close it because of lack of details :(
