### ISSUE TITLE
Iframe does not work in safari browsers

### ISSUE THREAD

**Issue by Nekozzz** [photopea/photopea#1530]
To display Photopea on my site, I use the link from your demo page and install it in the iframe. In Safari browsers, a JS error occurs. Here is what the console displays:

SecurityError: IDBFactory.open() called in an invalid security context pp.js:77252
TypeError: undefined is not an object (evaluating 'this.mM.length') pp.js:77238

Is that a problem on your side?

**Comment by photopea** [comment]
It looks like yoour browser is not allowing Photopea to access IndexedDB. Can you try to change browser settings? Maybe you enabled "too high security" somehow. This is not a regular setting, other browsers don't have it this way.

**Comment by photopea** [comment]
I expect this was fixed.
