### ISSUE TITLE
Use web workers for CPU intensive tasks

### ISSUE THREAD

**Issue by fl4p** [photopea/photopea#1531]
Yesterday I exported WEBP and the coding task freezed the tab for about 1 minute. 
If the user gets nervous they might close the frozen tab with data loss.
I think it would be cool to have this CPU intensive code run in a web worker.

**Comment by photopea** [comment]
Hi, the saving to WEBP should be extremely fast, as it is done through a "native" interface of the browser. But after saving, we have to decode it back, to show you the preview (which may have different quality, than the original image). We use a custom decoder, and maybe that is what lagged. But in total, the process should not take more than 1 second even for large images.

If you try to export the same image again, does it take 1 minute again? If yes, could you send us your doucment to support@photopea.com ?

**Comment by fl4p** [comment]
Yes its still the same, even on my desktop the export GUI is pretty much unusable, especially the quality slider. I'll send you the image.

**Comment by photopea** [comment]
Hi, I just tried to export your image into WebP. It takes about 8 seconds before it shows the result (definitely not a minute). 60% of this time is decoding the new WebP file, to show the user a preview of how the result actually looks like.

I asked a friend to prepare a better (faster) WebP decoder for us. If it is possible, we will update it.

**Comment by fl4p** [comment]
Did you try to drag the quality slider?

**Comment by photopea** [comment]
The slider works in a same way. If you give it a new value, it should be updated in 8 seconds. You can type the quality as a number, or click on a new position of a slider (to avoid dragging by small steps).
