### ISSUE TITLE
Layer - Layer Style - Stroke issues

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1532]
1.) Open pea.psd - go to menu Layer - Layer Style - Stroke. Layer Style dialog open but Stroke is not selected as it should

2.) Error if you open pea.psd - deselect all layers (with Auto-Select and click outside) - go to menu Layer - Layer Style - Stroke
  Now empty Layer Style dialog open (for first Layer it seems) and error is shown in console->

Uncaught TypeError: Cannot read property 'frameFXMulti' of undefined
    at EF.mj (pp.js:7467)
    at AP.hCV (pp.js:9049)
    at Oa.hFS (pp.js:8789)
    at Oa.EH.F (pp.js:9)
    at Oa.dN.F (pp.js:6127)
    at Ev.dN.F (pp.js:6127)
    at Em.dN.F (pp.js:6127)
    at Em.dN.F (pp.js:6127)
    at Em.nW (pp.js:6148)

**Comment by photopea** [comment]
Hi, fixed, thanks! :)

**Comment by hxim** [comment]
There is still error if I do this:
1.) Open photpea, open pea.psd
2.) go to "background" layer
3.) go to menu Layer - Layer Style - Stroke

![image](https://user-images.githubusercontent.com/6370548/61187772-ec753700-a675-11e9-8552-66825b3ea09b.png)
