### ISSUE TITLE
Feature request: adjustments pane

### ISSUE THREAD

**Issue by JohannesBe** [photopea/photopea#1533]
In photoshop some basic adjustments (e.g. change brightness, color balancing...) can be done from a panel, that is oft located above the `layers` pane. I figure this is possible in photopea through `images > adjustments`, but this has two major disadvantages from a UX standpoint:

1) it requires a lot of clicks to get there
2) it is currently implemented through dialog boxes, meaning that it is more difficult to change to another tool whilst performing adjustments (the sidebar is unavailable).

Could a similar [adjustments pane](https://www.wikihow.com/images/thumb/9/90/Use-the-Adjustment-Panel-on-Photoshop-Step-2-Version-2.jpg/aid6991735-v4-728px-Use-the-Adjustment-Panel-on-Photoshop-Step-2-Version-2.jpg) be implemented in photopea?

Thanks.

**Comment by photopea** [comment]
Hi! In Photoshop, that panel adds Adjustment Layers. You can do it in Photopea (and in Photoshop) using Layer - New Adjustment Layer - ....

**Comment by JohannesBe** [comment]
Could you give the different options a easily distinguishable icon then? It makes skimming through the list much more easy. Thanks!

**Comment by photopea** [comment]
I am not good at making icons :( but if you could make icons, I would be
happy to use them!

pátek 12. července 2019 JohannesBe <notifications@github.com> napsal(a):
