### ISSUE TITLE
Bug: Blank space below workspace, scale ratio display gone missing

### ISSUE THREAD

**Issue by KyoGrou** [photopea/photopea#1536]
There is a blank space right below the picture, seem like the space to display the horizonal ads, and the number which display the canvas scale ratio is gone.

![image](https://user-images.githubusercontent.com/30156458/61134793-958f2680-a4ea-11e9-846e-3731e4de0978.png)

**Comment by photopea** [comment]
Yes, there should be advertisement. We will try to solve why it is not displayed.

The document zoom is displayed only when Rulers are enabled (View - rulers).

**Comment by KyoGrou** [comment]
You mean there will be 2 ads display at the same time ?

**Comment by photopea** [comment]
It is hard to say, we are trying to find the optimal amount of ads. We will also make the Premium account cheaper.
