### ISSUE TITLE
Feature: Support importing .abr (photoshop brush files)

### ISSUE THREAD

**Issue by KyoGrou** [photopea/photopea#1539]
Maybe this will turned out that you will have to implement all attribute in photoshop brushes settings. For now I think that if we take some information like alpha, scatter, angle, etc ... from the set will be good, since it will be much faster than creating all the brushes you need one by one.

**Comment by photopea** [comment]
Hi, importing ABR should work well. You can do File - Open, or use the tiny arrow next to a brush gallery.
