### ISSUE TITLE
Bug: Some brushes didn't show the pointer outline

### ISSUE THREAD

**Issue by KyoGrou** [photopea/photopea#1541]
When I tried using these brushes, I can't see the pointer anywhere so it's really hard to paint. maybe it's related to the brushes' transparency or something ?
![image](https://user-images.githubusercontent.com/30156458/61185863-2bac8380-a688-11e9-9717-fa2fe16f0174.png)

**Comment by photopea** [comment]
Hi, I made Photopea use a tiny cross as a cursor for these brushes.
