### ISSUE TITLE
Svg graphic error

### ISSUE THREAD

**Issue by GregoryTheGamer** [photopea/photopea#1543]
Hello, for some reason this svg graphic does not display correctly, I want to fix it. Any help? (The inside of the D is not there on the image but the mask shows it properly.)
![help](https://user-images.githubusercontent.com/24637139/61190496-9fd43080-a662-11e9-9719-528389920269.png)

**Comment by photopea** [comment]
Hi, could you share your SVG with us?

**Comment by GregoryTheGamer** [comment]
Sure thing, It one of the Super Smash Bros. Symbols. (despite there being much more complex symbols related to smash this one is the only one that is giving me issues)
[DonkeyKongSymbol.zip](https://github.com/photopea/photopea/files/3393775/DonkeyKongSymbol.zip)

**Comment by photopea** [comment]
I fixed it. Thanks for reporting it!
