### ISSUE TITLE
Error when trying to select a path: Cannot read property 'setAttribute' of undefined

### ISSUE THREAD

**Issue by kaffeskogen** [photopea/photopea#1546]
I get the following error when trying to select a shape. I can click on the menus but the image I'm editing is frozen.

```
Uncaught TypeError: Cannot read property 'setAttribute' of undefined
    at new ts (pp.js:8040)
    at new ts (pp.js:8024)
    at new ts (pp.js:8024)
    at new ts (pp.js:8024)
    at ti.pS (pp.js:7987)
    at mn.pS (pp.js:8964)
    at tu.update (pp.js:8875)
    at tu.Px (pp.js:8873)
```

How to recreate:
1. Create a shape
2. Warp it a bit
3. Select it via `Path select`
4. Error appears and the list over layers is emptied.

![Anteckning 2019-07-15 135514](https://user-images.githubusercontent.com/7135301/61214746-04e26180-a709-11e9-8d4c-47482d108d74.png)

**Comment by kaffeskogen** [comment]
Here is the PSD:

[Ribbon.zip](https://github.com/photopea/photopea/files/3392170/Ribbon.zip)

**Comment by photopea** [comment]
Hi, I am very sorry for this serious bug. I just fixed it. Thanks for reporting it!
