### ISSUE TITLE
keyboard short cuts wont work

### ISSUE THREAD

**Issue by nixeen** [photopea/photopea#1547]
cannot drag and drop, deselect ,ctrl z, use the [ and ] to resize the eraser or paint brush. No keyboard short cuts are being aloud I am using a bing internet search

**Comment by photopea** [comment]
Hi, I guess you are using the Microsoft Edge browser. Sadly, it does not support keyboard events in a form we need it: https://caniuse.com/#feat=keyboardevent-code

Please, use a different web browser, or wait until Chromium-based Edge.
