### ISSUE TITLE
Chosen font loads as something completely different

### ISSUE THREAD

**Issue by geelouisey** [photopea/photopea#1549]
When I pick a font, it says that that particular font has been loaded but what appears on the screen is a totally random font that is not what I chose. I have switched across browsers and closed and re-loaded the program several times but this issue still won't budge.

**Comment by photopea** [comment]
Hi, I played with fonts and it seems to wokr well in my case. Could you tell me what font did you choose? Or send a screenshot or something?

**Comment by photopea** [comment]
I have to close it because of lack of details :/
