### ISSUE TITLE
Feature: Free Transform UX

### ISSUE THREAD

**Issue by mblandfo** [photopea/photopea#1550]
I use this all the time to edit images in MS Paint. Select a region, and then stretch that region. In Photopea, I think I need to do this:

1. select region
2. ctrl+alt+T (kind of awkward to press on Mac)
3. stretch region 

whereas in Paint, it's just this:

1. select region (automatically in free transform mode)
2. stretch region

So, it'd be really nice if you could select a region, and just hold Cmd or Ctrl to go into free transform mode, or even if the keyboard shortcut was easier or if keyboard shortcuts were editable
Or maybe a setting that changes you into Free Transform mode when you select a region?

**Comment by photopea** [comment]
Hi, I am afraid this would ruin many other usual workflows. There are many things you could do with a selection. People often create selecitons with multiple steps.

Some browsers may allow you to use Ctrl+T for free transform. You can also do Edit - Free Transform. If you have a Move tool, you can enable Transform controls.

**Comment by mblandfo** [comment]
Move tool transform controls do help since they stay on.

Ctrl + T does work on mac, which is nice. Maybe it doesn't work on Windows? Maybe it should be listed as Ctrl + T on mac?

Well, it doesn't matter. Transform controls also allow you to move the thing, so that's pretty much exactly what I wanted.
