### ISSUE TITLE
Cropp tool (false cropping)

### ISSUE THREAD

**Issue by Aquarius1702** [photopea/photopea#1555]
Cropping tool not working. It cuts strange area.

**Comment by photopea** [comment]
Hi, could you tell us more? We just tried it with pea.psd and it worked well.

**Comment by Aquarius1702** [comment]
Yes. You are right. 
It is probably buggy with layers. 
Works fine on flat image. 

Best regards, 
Tomislav.

**Comment by photopea** [comment]
What do you mean "buggy with layers"? Can you send us your PSD image and tell what you did? Crop tool should always work correctly in all cases.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
