### ISSUE TITLE
Warp on partial path issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1556]
In Free Transform on part of points of shape as you implemented #1502 when you hit Warp button and do some "warping" shape is "broken".
for example
1.) open pea.psd
2.) convert Welcome layer to shape
3.) with Direct Select tool select only points of letter W
4.) Do Free Transform - button Warp or (Menu -Edit -Transform -Warp)
5.) Move with some point
->entire shape seems to be transformed into letter W (into selected area)

**Comment by photopea** [comment]
Hi, it is fixed :)

I am sorry I did not make it work properly from the beginning. I thought nobody would use such special feature.
