### ISSUE TITLE
Editing a Layer Style opens box that renders PhotoPea unresponsive

### ISSUE THREAD

**Issue by zonV** [photopea/photopea#1557]
I have tried to edit layer styles and upon opening the Layer Style box found it doesn't display any information and cannot be closed. Attached below is a screenshot of how it appears. Tested on a Windows 10 machine using both Chrome and Edge. Hope this helps, extremely grateful for the work you do!

![layer-style](https://user-images.githubusercontent.com/31111586/61547691-e71f4000-aa19-11e9-9025-c99d709605eb.JPG)

**Comment by photopea** [comment]
Hi, I am very sorry :( it is fixed now.

**Comment by zonV** [comment]
No apology necessary, thank you very much!
