### ISSUE TITLE
Unresponsive Menus

### ISSUE THREAD

**Issue by Farwl** [photopea/photopea#1558]
I'e been using this for about a week now and it worked fine. For some reason I opened it today and I couldn't click on anything. I thought I was losing my mind but all my other websites worked fine and I even tried it in two browsers. Its kind of annoying. I've restarted my PC and web browsers and it still is unresponsive.

https://gyazo.com/87d6048a1984a214e2050ea4ae29ae4c

**Comment by MatthewToo** [comment]
Yup - can confirm. I'm seeing these issues too. I assume there was some sort of update that broke something.

**Comment by photopea** [comment]
Hi, I am very sorry :( it is fixed now.
