### ISSUE TITLE
Can't save and Can't create new file

### ISSUE THREAD

**Issue by dickywijayaa** [photopea/photopea#1559]
Hey , I've used this apps for few weeks and it works fine.
But today , just now , I use it and try to make a new file and press the create button its give no response and not making a new file. And when I want to export the file , it give no response too. Here I attached the file.

<img width="1059" alt="Screen Shot 2019-07-19 at 22 59 56" src="https://user-images.githubusercontent.com/34730861/61548893-f71a3c80-aa78-11e9-93a8-9d1005e2d8e9.png">

Hope this will resolved soon , because I use this app on daily basis, thanks!

**Comment by dickywijayaa** [comment]
just realized that height and width become 12,41 and 12,42. Is that supposed to be that ? Check the picture

**Comment by dickywijayaa** [comment]
ohh its fixed now , thanks!

**Comment by photopea** [comment]
Hi, I am very sorry :( it is fixed now.
