### ISSUE TITLE
Crop tool press Enter error

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1560]
When you select Crop Tool (and no area is selected to crop) and press Enter on keyboard it shows this error in console:
pp.js:3591 Uncaught TypeError: Cannot read property 'Nr' of null
    at F.PR.F.LR.my (pp.js:3591)
    at F.PR.F.LR.xe (pp.js:3562)
    at mk.xe (pp.js:8375)
    at mk.IK (pp.js:8346)

**Comment by photopea** [comment]
fixed, thank you!
