### ISSUE TITLE
can't export to gif

### ISSUE THREAD

**Issue by moonimuy** [photopea/photopea#1561]
hello! So i have used this app for a long time and it always works fine. But today, i can't export my work to gif, i've tried many times. i even tried to re-do it on my laptop because i thought there's something wrong with my phone but it just cant work. 
![Screenshot_20190720-001326_Chrome](https://user-images.githubusercontent.com/53094447/61553405-8ed15800-aa84-11e9-8de6-a98b5b4a5635.jpg) 
![Screenshot_20190720-001437_Chrome](https://user-images.githubusercontent.com/53094447/61553411-93960c00-aa84-11e9-9d4f-033d941e6c0b.jpg) 
![Screenshot_20190720-001633_Chrome](https://user-images.githubusercontent.com/53094447/61553414-97299300-aa84-11e9-8ad6-4c4c5d1125df.jpg)

**Comment by photopea** [comment]
Hi, can you save your file as PSD and send it to us to support@photopea.com ?

**Comment by photopea** [comment]
Hi, your document is quite huge (2289 x 1946 pixels). It requires a lot of RAM and time to convert it to GIF, which I guess you don't have.

I was able to export your PSD as GIF, the GIF is 10.5 MB and the export took about 30 seconds. I will send it to you in an email.

Do you really need so large resolution? Press Image - Image Size, and enter a smaller resolution (e.g. 500 x 500 pixels, which is 20x smaller). Then, the export should work even with small RAM.
