### ISSUE TITLE
actions cause photopea to freeze/layers uneditible

### ISSUE THREAD

**Issue by jemichael1997** [photopea/photopea#1562]
whenever I use actions from photoshop to edit, more often than not the whole program ceases to allow me to do anything else (no new layers, no editing, etc.) and the action doesn't seem to load. I'm not super familiar with editing software but I've spoken with friends who do and they say this seems abnormal.

**Comment by photopea** [comment]
Hey, are you talking about loading actions or playing them? If Photopea feezes while loading ATN files, send us your actions to support@photopea.com

**Comment by photopea** [comment]
I have to close it because of lack of details.
