### ISSUE TITLE
Feature: Free Transform on Masks (raster and vector), Editing on vector mask

### ISSUE THREAD

**Issue by KyoGrou** [photopea/photopea#1563]
- The free transform only works when the raster mask is unlinked from the layer. If I make a selection when selecting the raster mask layer and free transform, a "Selected area is empty" dialog appears.

- The vector masks just doesn't support editing well. I can only add new path, move the paths. It's lacking the abilities to preview, edit path, free transform.

**Comment by KyoGrou** [comment]
Okay, this is a random bug. After I tried Uninstall and clear the data, and then install Photopea again, the free transform works like expected. 
However, I can't use the free transform on the paths of vector mask, or even the mask itself alone. The only option is I have to keep the links between layer and both masks, but this will also transform the raster mask and layer. If I unlink the vector mask, only layer or raster mask is transformed. Weird.

PS: Side question, is there anyway I can reset the data of Photopea without having to uninstall and install again (and without losing the imported assets in Local Storage ?).
![image](https://user-images.githubusercontent.com/30156458/61573183-607b6900-aad4-11e9-952d-f32f54fa4932.png)

**Comment by photopea** [comment]
So raster masks work well now, only vector masks don't?

I made Vector Masks work the same as in Adobe Photoshop. If a vector mask is active, and you enter Free Transform from a vector-editing tool, only the vector mask will be transformed. If you enter Free Transform from any other tool, the main content will be transformed + vector mask only if it is linked.

**Comment by photopea** [comment]
Local Storage, Foreground Color, Background Color and UI Theme are the only things Photopea stores in your computer after you close it. You can clear it all in your browser settings, depending on what browser you use.

Every time you open Photopea, your browser should load the latest version of the website = program from our server.

**Comment by KyoGrou** [comment]
> I made Vector Masks work the same as in Adobe Photoshop. If a vector mask is active, and you enter Free Transform from a vector-editing tool, only the vector mask will be transformed. If you enter Free Transform from any other tool, the main content will be transformed + vector mask only if it is linked."

Well this is strange though. Since there is no way I can select only the Vector Mask, so if I free transform, the content / raster mask also get transformed, even the preview box of the Free Transform tool is equal to the combination of both the layer + vector mask. ( I can select only layer / only raster mask).
![image](https://user-images.githubusercontent.com/30156458/61579517-335ca400-ab30-11e9-9fa0-cd52533e2fa6.png)
![image](https://user-images.githubusercontent.com/30156458/61579522-42dbed00-ab30-11e9-8dee-32f52201a66d.png)

> Every time you open Photopea, your browser should load the latest version of the website = program from our server.

I'm not sure about this. I have many cases make me wonder if I'm encountering a bug, but everything was working normally just a moment ago. I tried close and open photopea, refresh the webpage but no luck. So I uninstalled and delete data, then open the photopea website again, everything work normally like expected now. Do you know what may have caused this ?

**Comment by KyoGrou** [comment]
Okay the masks is behaving more strangely now. I can Transform the vector layer only now. But when I link the layer and masks, still only the vector mask get transformation. Still can't select only the vector mask.
![image](https://user-images.githubusercontent.com/30156458/61579650-3eb0cf00-ab32-11e9-9930-a440ee8c32c3.png)
![image](https://user-images.githubusercontent.com/30156458/61579653-45d7dd00-ab32-11e9-9c33-672438b342c3.png)
![image](https://user-images.githubusercontent.com/30156458/61579657-4ec8ae80-ab32-11e9-97a6-f2a725b8f78a.png)

**Comment by KyoGrou** [comment]
So I will try clearing the data and do this again to see if it will happen again or not

**Comment by KyoGrou** [comment]
Still happening
![image](https://user-images.githubusercontent.com/30156458/61579724-27261600-ab33-11e9-9883-c0268f7cf8d8.png)
![image](https://user-images.githubusercontent.com/30156458/61579729-3a38e600-ab33-11e9-9111-6016412a5190.png)

**Comment by KyoGrou** [comment]
Seem like it's depend on which kind of layer is having the masks.
- If it's the raster layer, then only the vector mask is transformed, even when linked
- If it's special layer (shape, text, I haven't test the others so i'm not sure), then it's a combination of layer + vector / raster + vector.

**Comment by photopea** [comment]
I decided to make it work as Adobe Photoshop, because that is what people are used to.

Search the internet to find out how exactly these things work in Photoshop (and Photopea). 

*** The behaviour of Free Transform also depends on what tool was active before it.

Let me know if there are any problems.

**Comment by KyoGrou** [comment]
I remember that in Photoshop, when the masked is unlinked, so it will depend on which mask is selected so the tools only affected that mask. Yes, this is what we expecting to happen, not what's happening with Photopea right now.

I guess I will have to go to my company to test out this case, since I don't have Photoshop at home.

**Comment by photopea** [comment]
In Photoshop, you can only select between the main image and the raster mask, or the Smart Filter mask (exactly one of these can be selected at any time). The Vector mask can be "active" or "not active", which can be changed by clicking on it.  The "activeness" of the vector mask has nothing to do with whenter the main image or the raster mask or the vector mask is selected.

Maybe the behaviour you describe was in older, 10 - 15 year old versions of Photoshop.

**Comment by KyoGrou** [comment]
You are right, the way photopea's behaving is just like in Photoshop.

By the way, in photoshop, I can edit it directly, just like a normal shape layer.

In Photopea, I can't see the path's outline + points, neither can I use Direct Select + Path Select tool. So it's really confusing when I use the free transform tool, unlike in photoshop, I can use free transform based on which path I selected.
The only thing I can do with the Vector masks in Photopea is using Pen tool and shape tools to add more paths, that's all. Should I create another ticket for this ?

**Comment by KyoGrou** [comment]
Okay now I can't even see the preview outline of the paths in shape layers. Bet I will have to uninstall Photopea again. 
![image](https://user-images.githubusercontent.com/30156458/61605991-4ecfc800-ac72-11e9-9e70-43f296fdeb93.png)
![image](https://user-images.githubusercontent.com/30156458/61606016-6c9d2d00-ac72-11e9-9383-e7acbedad56a.png)

**Comment by photopea** [comment]
Hi, you probably disabled View - Paths or View - Extras. This is also the same as in Adobe Photoshop.

**Comment by KyoGrou** [comment]
You're right. Guessed I hit the shortcut keys without knowing. 
Sorry for taking your time.
