### ISSUE TITLE
How can I install photoshopea on my server

### ISSUE THREAD

**Issue by mini536** [photopea/photopea#1565]
I am a Chinese user and I found that your website is too slow to visit,So I hope to install it on my server,How to do that?

**Comment by photopea** [comment]
Hi, I guess you are talking about Photopea.

You can get a licence for self-hosted Photopea, but it usually costs 1000 USD per month, or even more. See more details here: https://www.photopea.com/api/accounts

If you need it only for yourself, I recommend you to get a better internet connection. Photopea is only 1.4 MB, and if it takes too long to load, your internet is really slow :(
