### ISSUE TITLE
Bug: Shift + Drag in Direct Select tool

### ISSUE THREAD

**Issue by KyoGrou** [photopea/photopea#1566]
- When I Drag + Shift, sometime the points is slightly shifted from where it should be:
![image](https://user-images.githubusercontent.com/30156458/61576730-ad2c6780-ab07-11e9-95f3-35705333078a.png)

- When I Shift + Drag, the point I clicked on stayed behind, and the other points is slightly shifted:
![image](https://user-images.githubusercontent.com/30156458/61576744-d4833480-ab07-11e9-8062-49bc6f037918.png)

**Comment by photopea** [comment]
First problem: I fixed it, the position will not slightly shift.

Second problem: when you click the point with Shift, it will add / remove that point from selection. So you should press Shift after pressing the mouse over a point, to do what you need.

**Comment by KyoGrou** [comment]
> when you click the point with Shift, it will add / remove that point from selection. So you should press Shift after pressing the mouse over a point, to do what you need.

I think it should be depended on if the event is Shift click - Release / or Shift click - Drag. Guess I will also have to try this in photoshop.

**Comment by photopea** [comment]
When you shift+drag a selected point with a Direct Select (in Photoshop or Photopea), it will deselect it and will do nothing while moving the mouse.

**Comment by KyoGrou** [comment]
In photoshop, when you selected the points, you can shift + drag when you click near one point, not directly on points ( and the clickable area is quite large).

**Comment by photopea** [comment]
Are you talking about a Direct Select tool? When you shift+drag in Photoshop far a way from any point, you start to draw a selecting rectangle. The clickable area of each point is the same in PS and PP.

I feel like this whole issue is about me teaching you how to use Adobe Photoshop.

**Comment by KyoGrou** [comment]
Sorry, my bad. What I clicked on is the path itself, not the blank space.
You can try it for yourself.
