### ISSUE TITLE
The action does not appear / does not work

### ISSUE THREAD

**Issue by Akemi145** [photopea/photopea#1567]
Hi, I'm Brazilian and I use photopea. The actions are not working, whenever I use and apply, the action does not appear / does not work and always appears this message "unknown action rasterize layer".

**Comment by photopea** [comment]
Hi, ATN files may contain a lot of steps of many types. We have to make Photopea convert every type of step into an internal command of Photopea.  We do not support all possible steps of ATN (there are thousands of them), but we gradually add the support for new steps.

Please, send us your ATN to support@photopea.com , and if it is only the rasterization step missing, we can add it very quickly.
