### ISSUE TITLE
PSD files Not Opening (Crashing)

### ISSUE THREAD

**Issue by ankursiddha** [photopea/photopea#1568]
![Screenshot 2019-07-22 at 12 13 26 PM](https://user-images.githubusercontent.com/33720309/61611723-2ba91680-ac7a-11e9-8b24-287244f3670d.png)

PSD Files are not opening properly in Photopea. This is not with one file I have faced this will all the PSD files recently. None of them is working properly.

**Comment by photopea** [comment]
I am confused. You say crashing, but you have a file opened in front of you.

I just tried about 500 different PSDs in Photopea and they work well. Could you send us your PSD file to support@photopea.com , or attach it here?

**Comment by ankursiddha** [comment]
![cut   salon 21 july ](https://user-images.githubusercontent.com/33720309/61614530-96118500-ac81-11e9-9d77-665c45c6fe30.jpg)

I guess a PSD File Should Look Like this after Opening. I am Also e-Mailing you the Files on the above Email ID.

**Comment by photopea** [comment]
I did not receive any PSD on my email yet :(

**Comment by ankursiddha** [comment]
Please Check Once. I Have mailed. You a Wechat link to download the Files.

**Comment by ankursiddha** [comment]
Any Update? I have mailed you the PSD File Needed? Why I am facing this issue with every file ??

**Comment by photopea** [comment]
Hi, I received your file. It is 16bit file, which are not supported by Photopea. It will take me a day or two to add a support.  I will not close this issue until it is fixed.

**Comment by s5706820** [comment]
So, I am not the only one facing this, i see.
Hope there is any update soon

**Comment by photopea** [comment]
It was fixed, 16bit PSDs are supported now :)
