### ISSUE TITLE
How to do the trademark R in photospea text 

### ISSUE THREAD

**Issue by Matty12347890** [photopea/photopea#1570]
How to do the trademark R in photospea text  r in the circle

**Comment by MichalSZZ** [comment]
Just copy ® (from any place of the internet) and paste into the text field ;)

**Comment by photopea** [comment]
This is not related to Photopea. You should search the internet to find how to type the ® sign on your computer. It could be in a manual for your computer, if you received any. It can be different for every OS or keyboard language.

If nothing works, you should always be able to copy-paste that character from elsewhere.
