### ISSUE TITLE
SVG colors not loading correctly

### ISSUE THREAD

**Issue by Kerooker** [photopea/photopea#1571]
Hey!

I'm having troubles with a svg file. I want to open it in photopea to export it as png. However, photopea can't load it's colors properly

SVG when I open in my computer with Ubuntu's image viewer:
![image](https://user-images.githubusercontent.com/1577251/61668281-9ece7f00-acb2-11e9-8348-f4c4bb2ddf19.png)

When I open it in photopea:
![image](https://user-images.githubusercontent.com/1577251/61668323-bdcd1100-acb2-11e9-9b0c-d94cce7608f7.png)

Am I doing something wrong?

[logo_vector.zip](https://github.com/photopea/photopea/files/3419297/logo_vector.zip)

**Comment by photopea** [comment]
Hi, there was a bug with processing CSS, it is fixed now :)

Sorry for the delay.

**Comment by Kerooker** [comment]
Great! Thanks!
