### ISSUE TITLE
Crop to zero width and height image

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1572]
It is possible to use Crop Tool to width=0px and height=0px image and produce invalid psd/png file of zero width and height.
1.) Open pea.psd
2.) Select Crop Tool
3.) Use Crop Tool in top left direction but do not release mouse button
4.) While still holding mouse button press Enter on keyboard

**Comment by photopea** [comment]
Fixed! :)

**Comment by hxim** [comment]
Hello now If I do Crop Tool and while still holding mouse button press Enter on keyboard it crops with no problem but black rectangle with width and height stays on screen and I need to switch to Move Tool to make it disappear.

**Comment by photopea** [comment]
You are right, I was too lazy to fix it. Now I did!

**Comment by hxim** [comment]
@photopea 
Hello it is now possible to crop to produce invalid width=0px and height=0px image using Fixed Ratio or Fixed Size options and writing 0 in W and H inputs.

**Comment by photopea** [comment]
You could also enter negative values into these fields. I made "1" the minimum value.

**Comment by hxim** [comment]
@photopea
Try writing "x" there it does not change to 0 or 1 and resulting size image is 0px x 0px

**Comment by photopea** [comment]
Now, it should be fixed.
