### ISSUE TITLE
Photopea with many files open issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1573]
When I open large number of files in photopea. Workplace does not fit in the window and outside scrollbar appears. You need to scroll down to reach bottom part of image and then menu and tools in top are not accessible. See screenshot (I just clicked Fit The Area but bottom part of image is under current viewable area and I need to scroll down to reach it):
![image](https://user-images.githubusercontent.com/6370548/61689775-5eedb300-ad17-11e9-9417-b99fea8479de.png)

**Comment by photopea** [comment]
Hey, I fixed it! :)

**Comment by hxim** [comment]
Hello now if I put photopea on half of my screen it does this - see screenshot - only half of layers panels is visible and panel with tabs of open files is not filling entire area (also advertisement is out of view)
![image](https://user-images.githubusercontent.com/6370548/62303844-2a979680-b47d-11e9-8184-c722f28cd8d2.png)

**Comment by photopea** [comment]
That is strange. What if you resize the the edge of a browser manually at that point?

**Comment by hxim** [comment]
@photopea 
Hello I recorded video what happens if I resize browser window:
https://youtu.be/ur9-nyDd8Dk
Also when I resize browser window to smaller size and then reload photopea with F5 it is OK after reload but when resize browser to full screen reload photopea with F5 and then make browser window smaller as in video it is not working properly.

**Comment by photopea** [comment]
I see, it is caused by the ad at the bottom, which is displayed only on screens taller than 900 pixels (so it is not there in my case).

Do you really start Photopea at one size and then resize it? If you reload Photopea when you want to have a smaller window, it should be fine.

**Comment by hxim** [comment]
> Do you really start Photopea at one size and then resize it? If you reload Photopea when you want to have a smaller window, it should be fine.
Yes I always start it in maximized window (full screen) and sometimes when I watch some videos I put one browser window with videos/youtube on half of screen and photopea on another half and watch videos and work with photopea at the same time.
