### ISSUE TITLE
my photopea always crash

### ISSUE THREAD

**Issue by cattodesu** [photopea/photopea#1575]
i want to edit my gif for my important work, but why did photopea always crash? please fix it asap, i really need this.
![Screenshot_20190724-063020_Chrome](https://user-images.githubusercontent.com/53241030/61754922-86a84e00-addf-11e9-9315-ed1e3b8a14a7.jpg)

**Comment by photopea** [comment]
Hi, you probably don't have enough RAM. Try to use smaller images (Image - Image Size - decrease it e.g. to 500x500 pixels).
