### ISSUE TITLE
Possibility to get DOF data from photo taken with dual camera phone

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1576]
All the new smartphones (MID and HI-end) has more than one camera to simulate the Field Of Depth.

This data are stored (somehow) in a JPG file. 
This is grayscale bitmap.

e.g. it can be used to make a 3D photo in facebook https://blog.picjumbo.com/create-facebook-3d-photo-from-normal-photo/

but there are many more usefull examples:

- easy selecting areas (persons or other things)
- "fake" field of blur with blur filters (in PS there are an option named 'lens blur' which simulate camera lens, from mask or one of the channels)
- making corrections to those of taken pictures, which have fail in AI algorithm 

here  https://photo.stackexchange.com/questions/86286/how-to-extract-depth-information-from-jpeg-files/100479 someone wrote that can be stored as a Base 64 in a EXIF

and here https://forum.xda-developers.com/p9/help/extracting-images-p9-dual-camera-t3465877/page2 someone made a program to extract this data, but it is too complicate for me to use it :)

maybe it will be helpfull for you

I would like to have this information (when open such of file), in a channel tab (when that feature will be in Photopea) as a new channel. Or in any other place.

**Comment by MichalSZZ** [comment]
For now (when there is no channels pallete) it can be attached as a new layer.
E.g.: 
user open JPG file
Photopea is checking the file for such a data in EXIF
If data of DOF is in the file, pop up window is showing and program ask user, that he would like to attach information of Field Of Depth as a new layer. (for better expirience to begginer user, it can be the lower one layer under the main photo)

**Comment by MichalSZZ** [comment]
I just finded a great webapp that allow to extract depth of field from photos  (or draw new one if it doesn't exist) ad play with it  :)

http://depthy.me/#/

but...
I think it is outdated https://github.com/panrafal/depthy
and have problems with new cameras


and here is http://stereo.jpn.org/kitkat/indexe.html a program that allow to extract field map as a file but... it is .exe file and I cant run it becouse I have macOS :(

**Comment by photopea** [comment]
Hi, I implemented it. Depth map should appear in a separate layer.

I am not sure if it is the only format of such images. If you find an image, for which Photopea does not open a depth map, share it with us! :)

**Comment by MichalSZZ** [comment]
WOW. You are amazing!

I had hope to get DOF data from photos taken with my wife phone - Huawei P20 PRO
[IMG_20190714_154805.jpg.zip](https://github.com/photopea/photopea/files/3458553/IMG_20190714_154805.jpg.zip)

Is there any information about DOF?

E.g. Older Huawei P9 have DOF informations inside this image:
https://img.photographyblog.com/reviews/huawei_p9/sample_images/huawei_p9_16.jpg
https://fdn.gsmarena.com/imgroot/news/16/04/huawei-p9-camera-samples/gsmarena_004.jpg

those 2 above was tested in https://www.omnivirt.com/3d-photo/ and have DOF

**Comment by MichalSZZ** [comment]
iPhone XS:
https://img.photographyblog.com/reviews/apple_iphone_xs/sample_images/apple_iphone_xs_06.jpg
https://img.photographyblog.com/reviews/apple_iphone_xs/sample_images/apple_iphone_xs_07.jpg
https://img.photographyblog.com/reviews/apple_iphone_xs/sample_images/apple_iphone_xs_01.jpg

**Comment by photopea** [comment]
Hey, I made it work with Huawei P9 and iPhone images.

However, I can not see a depth map in a photo from your wife. Are you sure it is in there?

**Comment by MichalSZZ** [comment]
@photopea I can't tell you about DOF informations in P20 PRO (didn't found any informations about it). I affraid, that there isn't possibility to get those data from smartphones, which doesn't have functionality, to rearrange blur effect after shot a photo. And P20 PRO is one of those smartphones.
But sometimes, there are a hidden options and I was wondering if it is one of them :)

Should I send to you other tested images like P9 and iPhone X, to implement extracting DOF in Photopea?
If yes:
Here or on via email is better for you?

**Comment by photopea** [comment]
Now, Photopea should load DOF from every image, which contains such
information.

If you have an image with DOF information, which is not opened in Photopea,
send it to me :)

pátek 2. srpna 2019 MichalSZZ <notifications@github.com> napsal(a):

**Comment by MichalSZZ** [comment]
I have few informations about DOF.
Huawei P20 PRO have DOF but only when user make a photo with specific mode.
Photos taken in that mode (on any cameras with 2 or more cameras - samsung, iPhone etc.) can change DOF in phone gallery. 

BTW. I made that 3D post with DOF last friday (not in Photopea - becouse that was a lot of layers and drawings, which is slow in PP in high resolutions)
https://www.facebook.com/375809290670/posts/10156357153355671/

**Comment by photopea** [comment]
That is useful to know! I also made a 3D post on Facebook in Photopea some time ago https://www.facebook.com/photopea/posts/2222894937971582 :)

Again, if you ever find a photo with DOF, which is not recognized by Photopea, just send it to us!

Photopea should not be slowwith many layers and large resolution. At least not slower than other programs.

**Comment by 4nric** [comment]
The depth map layer isn't loaded when importing portrait photos from Samsung Galaxy S10+. The phone doesn't utilize a ToF sensor as it doesn't have one but calculates depth from a stereo pair of images. Photopea does import those images alongside the main one with effects applied, only three layers currently.

http://www.hasaranga.com/dmap/ can extract the depth map and does it locally, only JS stuff.

Please let me know where to send a photo if you need one, thanks!

**Comment by photopea** [comment]
Hi, you can attach your photo here, or send it to support@photopea.com ! :)

**Comment by 4nric** [comment]
I sent the photo via email. The file is over 10MB, so I can't attach it here. It was an older image taken around a year ago. Thank you!

**Comment by photopea** [comment]
It should be fixed now.
