### ISSUE TITLE
Panels missing when menus property included in environment

### ISSUE THREAD

**Issue by jason-engage** [photopea/photopea#1579]
When I load photopea in my iframe with menus property in environment object the panels on the right are missing. But the menus are showing as specified, for example:

...
menus: [[0,0,0,0,0,0,1,0,1,0,0],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0],1,1,1,1,1,1,[1,1,0,1,1]],
...

When I remove the menus property entirely, and the full menu is shown, the panels reappear on the right side as expected.

I also tried including the 'panels' property such as panels:[0,1,2], but this does not solve the issue.

What I am missing?

**Comment by jason-engage** [comment]
I think I got it to work now... playing around with the settings. It seems to be a bit buggy, not sure why.

**Comment by photopea** [comment]
Hi, I just tried your parameter, it seems to work well: 

https://www.photopea.com#%7B%22environment%22:%7B%22menus%22:%5B%5B0,0,0,0,0,0,1,0,1,0,0%5D,%5B1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0%5D,1,1,1,1,1,1,%5B1,1,0,1,1%5D%5D%7D%7D
