### ISSUE TITLE
Improve touch screen support

### ISSUE THREAD

**Issue by wernight** [photopea/photopea#158]
The most important is supporting [pinch to zoom and move](https://stackoverflow.com/questions/11183174/simplest-way-to-detect-a-pinch)

The touch isn't to fully support touch only, but mostly to support standard pinch/zoom which works on almost all websites including Google Maps.

**Comment by photopea** [comment]
I guess it would look ugly, because we still support only fixed values of zoom ... so from 1x it would jump right to 2x.  What if we made WebGL the necessary requirement for running Photopea?

**Comment by wernight** [comment]
I would be fine but may be it could be a optional improvement. Maps has it optional but I agree it's hard.

**Comment by photopea** [comment]
Do you think we should create a brand-new UI for small-screen touch-only devices? 
... maybe something like this? https://play.google.com/store/apps/details?id=com.adobe.psmobile

Or we should have always the same UI, but adapt it to the current screen size (it works already to some degree)? E.g. for the Clone Stamp, you need to click with the Alt key down to pick the source of cloning. Should we have a non-keyboard alternative for each such thing?

**Comment by twitchplayskh** [comment]
Things you can look at to make better 

- It's to hard to resize a photo 
- save for the web looks like this on my phone http://imgur.com/ji5JfzJ  

What if you have a button for touch screen on or off and have set layouts for big or not so big screens

**Comment by photopea** [comment]
Hey! 
- What do you mean by resizing a photo? Do you mean Image - Image Size, or Free Transform? You can also enter the new size in Save for web
- It seems that your browser does not support CSS variables. Can you update it? What browser do you use?
- Sorry for that, it is fixed now.
You mean like when a user can choose from multiple layouts, what he or she prefers?

**Comment by twitchplayskh** [comment]
I am on Google google chrome  And I am on about free transform 
Yes multiple layouts one for big scrren one for small screens

**Comment by photopea** [comment]
Photopea looks completely different in my Chrome  on Android (58.0.3029.83).  Have you tried to update it? 

But how should the layout for small screens look like? We can not fit in all the tools, panels etc. We probably need larger buttons. Should it be just a several filters?

Free Transform ... I believe I have fixed it a little. It should be easier to grab the corner.

**Comment by twitchplayskh** [comment]
Can we not have pinch in and out for free transform ? 
I had a update and it's working my b 
It's hard to think of a good layout what about a ui scale slider as a quick fix till you all work out a better plan

**Comment by photopea** [comment]
What do you mean by "pinch in" for free transform?

Slider? So we should show the Desktop UI on the phone, just scale it down? But buttond would be too small.

**Comment by twitchplayskh** [comment]
On a phone you pinch in and out to zoom in and out. In transform can we not do that for resizing ?
In  video games you have a bar that lets you scale the ui to what works bets for you so with the layout the phone one has just need a bar we can slide to scale it a bit

**Comment by photopea** [comment]
I see. On a touchscreen, you have multitouch. So by grabbing the image with two fingers at two different places, the layer could be moved / rotated / scaled, to follow two fingers.

I still don't understand what do you mean by scaling, but I have a feeling that even you have no idea what should it be :D

**Comment by twitchplayskh** [comment]
Ui like this may work 
https://play.google.com/store/apps/details?id=com.adsk.sketchbookcom.adsk.sketchbook or like this https://play.google.com/store/apps/details?id=com.bytestorm.artflow
 yes it's a app ui but it looks like a good fit for the web phone ui

**Comment by photopea** [comment]
Should it still be Photopea, or a completely different app? I mean ... should there be available all features of PP, or just some of them?

If it should be Photopea (with PSD support), we must have things like Layer Styles, Gradient Editor, Save for Web, panels: Layers, History, Brushes, Character, Paragraph, Properties. I really can't see how the layout should look like to contain all this.

**Comment by twitchplayskh** [comment]
Can the layers panel not look like this but with text http://imgur.com/ljOW5io  as a popout and you can hit a button to minimize it let's us move it to a place we like

**Comment by photopea** [comment]
But I am still skeptical about it. Having a professional photo editor in your phone and using it is like having a Spoon in your swiss knife and using it. 
I think that even if Photopea works completely on the tiny screen, working with it would be 3x slower, than working on a large screen (with a mouse and a keyboard).
Keep in mind, that each layer should also have its name, which should be editable, there should be layer groups, raster and vector masks, their locks, transparency locks, layer effect sign etc., in order to be a PSD editor. Since it would be a completely different interface than a large-screen version, users would have to spend weeks to learn how to use it.

**Comment by twitchplayskh** [comment]
We make this for big screens not tiny no one has a s8 phone to do art they have a big tablet for that or a pc

**Comment by twitchplayskh** [comment]
There is no app on android  that can do what photopea can and photopea a Web app if we can work out a ui for big tablets like the galaxy tab s or more it will be amazing

**Comment by twitchplayskh** [comment]
Yes it's a lot of work but it will be amazing

**Comment by twitchplayskh** [comment]
The updates you did are amazing I can do photoshop type thing on my phone

**Comment by photopea** [comment]
So I think, that multi-touch controls are not needed now. There are not many people using Photopea with a touchscreen. Current tools should be sufficient for it (Zoom tool, Hand tool).

**Comment by wernight** [comment]
I agree that zoom and hand cover most of the desired usage on a touch screen.
