### ISSUE TITLE
deleting part of a layer

### ISSUE THREAD

**Issue by KaoticVibez** [photopea/photopea#1582]
I'm trying to create a streaming overlay. When I try to delete part of a layer using the magic wand, it just deletes the whole layer, whether using the delete layer button or right clicking and hitting delete. Also my delete button key doesn't work for anything, nor does trying backspace. Then when I try to delete part of a rectangle (because I need two, one for gameplay and one for webcam which overlap) by using the magic wand, it will just delete the whole rectangle.

**Comment by photopea** [comment]
Hi, I think you need to Clear the selected area - Edit-Clear, or Delete or Backspace on a keyboard.

**Comment by KaoticVibez** [comment]
yes I was trying to use delete and backspace. Neither of them would work.

**Comment by photopea** [comment]
What about Edit-Clear?

**Comment by KaoticVibez** [comment]
Could you tell me how to do that?
