### ISSUE TITLE
Image-Trim or Crop Tool Trim weird behavior

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1583]
1.) I open pea.psd and clear two rectangles in background layer (select and delete key).
2.) Menu-Image-Trim or  Crop Tool - Trim button
it does this -> see screenshot
![image](https://user-images.githubusercontent.com/6370548/61933361-ff490f00-af85-11e9-831b-a69b7fdb0817.png)
note : if I use Ctrl + . keyboard shortcut (for Image-Trim) it seems to behaves normally

**Comment by photopea** [comment]
It used to trim according to a current layer. I made it trim according to a total image content.

**Comment by hxim** [comment]
Hello, when I create new file with white/transparent background and do Menu-Image-Trim it gives this error now.
Uncaught TypeError: Cannot read property 'clone' of undefined
    at j.yE.j.Xu.Tq (pp.js:3560)
    at ny.Tq (pp.js:8843)
    at ny.gb.Q (pp.js:9)
    at ny.Sj.Q (pp.js:6179)
    at ny.wC (pp.js:8983)
    at ny.vp (pp.js:8967)

**Comment by photopea** [comment]
You are right, I fixed it.
