### ISSUE TITLE
clone tool problem

### ISSUE THREAD

**Issue by rezaafz** [photopea/photopea#1585]
Hello
sometimes after a little working Clone tool doesn't work at all!
i have to save the image , open it again and then continue the work! that's very annoying ...!

**Comment by rezaafz** [comment]
Here's a recorded video of what really happens :
https://drive.google.com/open?id=1s2-OaDErlKp7q650Fa5IhZn5P8dt8yfo

**Comment by photopea** [comment]
Hi, I was playing around for several minutes, but I could not make it happen :( Could you find any specific instructions how to reproduce it?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
