### ISSUE TITLE
Color lookup

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1587]
I wanted to try new Color Lookup adjustment but I don't know how is it supposed to work
1.) I selected some raster layer and clicked on Menu-Adjustments-Color Lookup...
2.) There is some dropdown so I opened it but no items there
3.) So I clicked on "Define new" there but it gives this error
Uncaught TypeError: Cannot read property 'v' of undefined
    at hJ.rY (pp.js:6717)
    at hJ.Db.jb (pp.js:6245)
    at J.clrL.RC (pp.js:7125)
    at Yi.RC (pp.js:7234)
    at lc.RC (pp.js:9102)
    at cV.PA (pp.js:8876)
    at cV.cll (pp.js:8859)
    at cV.Lk.h (pp.js:9)
    at cV.Dt.h (pp.js:6156)
    at lc.Dt.h (pp.js:6156)

**Comment by photopea** [comment]
Hey, I fixed it!

For this adjustment, you need a lookup table. You can find those as .look, .cube or .3dl files (and some ICC files). Load them into Photopea (just like fonts) and then, use them.

If you know about any nice and free Lookup table collection, let me know, I would like to add it into Photopea.
