### ISSUE TITLE
Ctrl + T shortcut support could be improved

### ISSUE THREAD

**Issue by wernight** [photopea/photopea#159]
Currently on most browsers, Ctrl + T will open a new tab instead of starting the free transform.

There are two workarounds:

 - "Open as window" for Chrome users
 - Ctrl + Alt + T (Alt is ignored by PP)

It seems that it's possible to capture [Ctrl + T](https://stackoverflow.com/questions/7295508/javascript-capture-browser-shortcuts-ctrlt-n-w) and avoid these workarounds.

**Comment by photopea** [comment]
I just tried it in the latest Chrome and Firefox and it really is not possible now. Check this: https://jsfiddle.net/89hks1xm/

I don't want to make my app behave differently depending on a browser. This is simply againts the main idea of the web.

So I changed the description of the shortcut to Ctrl + Alt + T (even though Ctrl+T is enough for Photopea). I tried to do the same thing for Ctrl + N (for a New Project), but once Ctrl and Alt is pressed, Chrome does not detect pressing of N.

**Comment by wernight** [comment]
I remember trying on some website where it worked, but I get your point.

Could mark it has `Ctrl + [Alt] + N` to hint users (shortcuts are for power users anyway).

**Comment by photopea** [comment]
Ctrl + Alt + N does not work in Chrome either.

**Comment by wernight** [comment]
Ctrl + N works in "Open as window"! :+1:

**Comment by sozipp** [comment]
i think "https://sozipp.github.io/Input-Remapper-for-Photopea/" will solve your problem bcz it is made for it you can change key bindings in photopea freely without os or web shortcut conflict
