### ISSUE TITLE
New Guides From Layer

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1590]
In Photoshop it's calls "New Guide From Shape" but works for any layers (raster, shape, text)

https://www.youtube.com/watch?v=bLfOLlysz4s

Last month I have used that feature in Photoshop to make my custom Bootstrap grid with Material Design gaps. 
From today I can do that propably with Guide Guy ;), but there is many more usefull ocasions to use it (making logos etc.)

**Comment by photopea** [comment]
Hi, I implemented it! View - Guides from Layer.
