### ISSUE TITLE
Tool presets "Define New" not working

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1591]
When I go to Tool Presets and click "Define New" it does not work and shows this error in console
->
pp.js:6256 Uncaught TypeError: Cannot read property '0' of null
    at XP.fe.bv (pp.js:6256)
    at fi.BI.J (pp.js:9)
    at fi.Uj.J (pp.js:6165)
    at fi.VW (pp.js:6187)

**Comment by photopea** [comment]
That was a really stupid bug :( I fixed it!
