### ISSUE TITLE
Request: Skip click to fold out items in top menu after initial first click 

### ISSUE THREAD

**Issue by kappische** [photopea/photopea#1592]
It feels a bit off that you need to click on each item in the top bar to fold them out after the initial first click.

I made videos how it works on mac for me in PhotoPea (rings indicate left click):
https://www.youtube.com/watch?v=b7m7cCDQx68

How I would like it to work, it would make it feel more native:
https://www.youtube.com/watch?v=-MNH316_o6U

**Comment by photopea** [comment]
I Implemented it, thanks for suggesting! :)

**Comment by kappische** [comment]
That's amazing! Thank you very much :)
