### ISSUE TITLE
Lower time for folding out menus

### ISSUE THREAD

**Issue by kappische** [photopea/photopea#1593]
It would be great if the time that it takes to fold out sub menus from top menu is shorter. Right now it makes photoPea to feel slow in comparison to native apps.

On mac it seems to be something like 15ms but photopea seems to be 30ms, which make photopea feel less snappy since it feels like I'm waiting to see the various options.

**Comment by photopea** [comment]
Hi, that time is 300 ms right now (0.3 seconds). I don't think it is good to make menus open sooner. Sometimes, the user moves from the top to the bottom of the menu, and it would be confusing, to open and close ("blink") all sub-menus along the way.

In all programs that I know, this time is even longer. You can also click on them, if you want it to be opened faster.
