### ISSUE TITLE
Serious tint problem with AWR-files

### ISSUE THREAD

**Issue by frida1234** [photopea/photopea#1595]
Hi! 

Yes, I also got this problems with all of my raw-files.. how is this problem solved? Also the hue of a png-file lookes messed up (much more green than it actually is).. 

![photo2](https://user-images.githubusercontent.com/53612565/62369734-42cceb80-b539-11e9-9790-963f9166f4a5.jpg)

**Comment by photopea** [comment]
It was already reported here: https://github.com/photopea/photopea/issues/1493
