### ISSUE TITLE
Live preview of gradient?

### ISSUE THREAD

**Issue by kappische** [photopea/photopea#1596]
Not sure if this would be good or not in a workflow (or too resource heavy?), but it's pretty nice in gimp to see a live preview of the gradient before releasing the mouse button. In gimp you can even edit a gradient after you do it but maybe that is just annoying?

**Comment by photopea** [comment]
Hi, I just tried to do that and it is not very smooth. Note, that the Gradient tool may have a custom opacity and a blend mode. Even some stops of the gradient can be semi-transparent. So it is necessary to re-blend the gradient with the original content of the layer.
