### ISSUE TITLE
Undo did not remove all changes

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1597]
I did some steps and when I did undo it did not remove all my changes...
1.)  I added new Adjustment Layer - Invert
2.) I went to mask of that layer, selected rectangle and cleared it with Menu - Edit - Clear
3.) I moved selected rectangle little bit and cleared it again with Menu - Edit - Clear
4.) In history I wanted to undo steps 2 and 3 but when I hit "New Adjustment Layer" item in History window it did not undo everything and black bar stayed in mask of adjustment layer

See screenshots:
![screen1](https://user-images.githubusercontent.com/6370548/62425251-53b46300-b6d9-11e9-8d83-e46764adec7e.jpg)
![screen2](https://user-images.githubusercontent.com/6370548/62425250-53b46300-b6d9-11e9-8047-63f6c0c7367a.jpg)
![screen3](https://user-images.githubusercontent.com/6370548/62425249-53b46300-b6d9-11e9-9d1f-01cf1b0cf1e6.jpg)
![screen4](https://user-images.githubusercontent.com/6370548/62425248-53b46300-b6d9-11e9-955a-7184763c32eb.jpg)
![screen5](https://user-images.githubusercontent.com/6370548/62425247-531bcc80-b6d9-11e9-83cb-cbe83d2c3522.jpg)
![screen6](https://user-images.githubusercontent.com/6370548/62425246-531bcc80-b6d9-11e9-8d24-7bf92d2002d9.jpg)

**Comment by photopea** [comment]
Fixed, thank you :)
