### ISSUE TITLE
Pen Tablet Pressure Not Working With Firefox

### ISSUE THREAD

**Issue by RoboticMind** [photopea/photopea#1598]
On Firefox 68.0.1, with a Huion H420, pen pressure does not appear to be working. I was able to get this to work without changing anything on Chrome. I've already tried restarting Firefox, and the driver for the Tablet, but that didn't seem to fix it. 

Image from Firefox:
![image](https://user-images.githubusercontent.com/30132912/62485420-a8fc7d00-b78a-11e9-8cb5-f3f1ab5ab9d9.png)

Image from Chrome:
![image](https://user-images.githubusercontent.com/30132912/62485568-08f32380-b78b-11e9-926b-73db0e5a278e.png)

**Comment by photopea** [comment]
Hi, it seems like a bug in Firefox. You can report it to Firefox to fix it. But maybe you can change the behaviour by changing the settings of Firefox. Or try to search the internet about how to make your pen work with Firefox.

**Comment by RoboticMind** [comment]
Ah it looks like doing some deeper digging, you need to set a flag in the about:config 

https://paintberri.com/posts/FirefoxWindows-pen-pressure-by-etherpendant-By13Xixmf?page=1#5a43cfc1c4a1b5940de3c5e2

````
For the past year or so, Firefox has supported pen pressure on Windows if the flag "dom.w3c_pointer_events.enabled" was turned on in "about:config".

However, a recent update to Firefox introduced a new requirement - "dom.w3c_pointer_events.dispatch_by_pointer_messages" needs to be turned on as well now.

So if Firefox pen pressure suddenly died on you in the last few months, please give this a shot!

1. Go to "about:config" in Firefox
2. Ensure "dom.w3c_pointer_events.enabled" and "dom.w3c_pointer_events.dispatch_by_pointer_messages" are turned on```

maybe you could show a warning about this and or create a help page article about this?

**Comment by RoboticMind** [comment]
It's worth noting that website I found was fairly buried and found with fairly specific search terms, so if other users run into this issue, they aren't likely to find that super easily

**Comment by photopea** [comment]
I am afraid that efforts of "fixing each browser" are out of the scope of our work. There are too many browsers, which may behave differently on every OS or hardware.

I am very sad to hear, that your browser requires such complex configuration. But I have heard, that the popularity of Firefox is dropping, so luckily, it will be replaced by better browsers in the future.

If you really want to help people with Firefox, discuss it with Firefox developers.
