### ISSUE TITLE
Color Lookup Tutorial?

### ISSUE THREAD

**Issue by hoshihosh** [photopea/photopea#1599]
Hello! I have wanted to try out the new color lookup feature but every time i upload and use the LUT thing its just makes my picture black? I was wondering how soon we could get presets already in there and maybe give me a tutorial? I have a large group of people wanting to know. Thank you!

**Comment by photopea** [comment]
Hi, can you share your LUTs with me? Once you open your LUT in Photopea and select it in adjustment parameters, it should work well.

**Comment by hoshihosh** [comment]
...I'm really sorry for taking time out of your day, but I did it! Thanks for the fast reply though!

**Comment by photopea** [comment]
So your LUTs work?
