### ISSUE TITLE
tip to new stuffs

### ISSUE THREAD

**Issue by Studioartcz** [photopea/photopea#16]
Hi,

what about implement this shortcuts?

1. CTRL + Z         => back last action
2. CTRL + +/-       => zoom in / zoom out
3. CTRL + H         => show guide lines
4. SHIFT + draw   => make horizontal / vertical line (line, brush, ...)
5. SHIFT / CTRL + rotate => rotate by 15 degress
6. CTRL+G           => New group

--- 
Close alert:
When i have opened my file alert after click to close tab / browser will be best!

**Comment by photopea** [comment]
Hi, thanks for suggestions.
Guidelines are not implemented yet, they will be added in the future, when rulers are added.

**Comment by Studioartcz** [comment]
Good, what about some public "to do list" with this things? Maybe with voting :)

**Comment by photopea** [comment]
Open issues here is my "to do list" :) I will not close them until they are done.

**Comment by photopea** [comment]
All the features were implemented. Except Ctrl+Z, it is a very misleading shortcut, there already exists Alt+Ctrl+Z for step backward.  http://blog.photopea.com/photopea-1-7.html
