### ISSUE TITLE
Moving layer with Move Tool to other file issues

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1600]
A. When moving layer with Move Tool to another file (keeping mouse cursor on other file tab) it does this (see screenshot):
- in layers window something (broken line?) appears and mouse cursor is in wrong place (before releasing mouse) but it seems to duplicate that layer after I release mouse button
![screen1](https://user-images.githubusercontent.com/6370548/62523439-10bad280-b834-11e9-832f-d8d936c54604.jpg)

B. I can move layer without any mouse button pressed with this steps and if I switch to other file after that it show this error (see screenshot) 
steps:
1. Hold left mouse button and start moving
2. Hold  also right mouse button while still holidng left button
3. Now release left mouse button
4. Now release right mouse button
5. Layer is still moving but no button is currently pressed
6. Switch to other file and it will show this error
![screen2](https://user-images.githubusercontent.com/6370548/62523438-10bad280-b834-11e9-8f10-bc68e093726f.jpg)

**Comment by photopea** [comment]
Hi, I fixed both problems.
