### ISSUE TITLE
copy/cut + paste

### ISSUE THREAD

**Issue by alexg-22** [photopea/photopea#1601]
Hello,

Suddenly i can not cut or copy and paste in a new image. 

It is a bug or am i doing suddenly something wrong?

Thanks

**Comment by photopea** [comment]
Hi, what is your OS? Can you update it?

**Comment by alexg-22** [comment]
hi again,

I have windows 10 enterprise 2016. I use the software until now without any problem, but this happened suddenly.

I can not update because i am not the administrator of this laptop.

So there is not yet any solution, and i have to wait till my laptop will be updated?

Thank you for your immediate response.

**Comment by photopea** [comment]
and what web browser do you use?

**Comment by alexg-22** [comment]
Well i tried with Firefox and it works, the problem is with my google chrome. So I have to use firefox browser.

**Comment by photopea** [comment]
I would like to make it work for old Chrome, but my Chrome already updated to 76, so I have nowhere to test it :/

Could you update your Chrome? It will work in the latest version.
