### ISSUE TITLE
Feature Request: Create a Steem-Engine.com token to allow for Photopea Pro Payment and Scotbot tribe for users to earn money and charge Photopea Tokens for the PSD files

### ISSUE THREAD

**Issue by ackza** [photopea/photopea#1602]
This is a feature Request: If you use https://steem-engine.com and the steem blockchain you can for around $20 create a token that lets you represent photopea in an open source community on the blockchain , let people pay for their photopea pro subscription in it AND when you pay around $700 for a scotbot community you can have a custom site where photopea creations can be posted,m by a phopea steem account, then charge photopea tokens or credits whatever you want to name them, for the fresh steem accounts oir let someone use steem connect or keychain extension for brave/chrome/firefox to login to steem and post the creations from Photopea to the social media blockchain visible on the steemit,com and the tribe sites like i would guess, photopea.network or whatever you wanted the custom site to be. 

We could even let people post through the photopea account until they earn phopea enough steem rewards from the blockchain to give them a new account, (Or they can wait a few days to weeks for a free one in the fsteemit inc faucet) I myself have a few hundred accounts ic an give if people from photopea really needed them and it is $700  to get a steem engine protocal scotbot tribe but only $20 to create a steem engine token . Im over on the steemspeak dot com discord if anyone from this project wants to get to me, im really interested in getting something like this off the ground!

**Comment by photopea** [comment]
Your message is very confusing and it looks like a spam to me. What problem  exactly is it going to solve?

**Comment by ackza** [comment]
I assure you it is not "spam" just because you dont understand it... I guess I should have added "Feature request" to the title but the "problem" this solves is creating a token for photopea users to earn by posting their creations, so they can actually make the $20 you are asking users to pay for the pro feature, which I am explaining, could be improved and allow for a great expansion of photopea, using the decentralized steem blockchain to improve your product.

If you don't know what the steem blockchain is maybe you could look it up before just deciding that things look like spam? I would even be willing to pay for your token creation fee and pay for instant free steem accounts for as many users as you need , and Id upvote them if they posted their Photopea creations on the open source decentralized steem blockchain, think of it like reddit but where youre in control of the data and instead of earning worthless karma your users can post their photopea images, (like during photoshop contests etc) and get upvoted, earning photopea tokens, creating value for photopea, giving users a reason to use it, its just a feature request, and i have thought a lot about it, you could at least ask about it if you think its confusing. It makes perfect sense to everyone I have told this to who uses steem. 

Please tell me what you consider to be "spam" about any of this? I am trying to help you expand photopea... if you dont apreciate that i will go take the idea to Aviary or someone else but photopea is a great tool, that i use a lot, and which id love to be able to earn tokens by refering enw users, so i could use THAT to pay for the $20 subscription you ask for in the ads

maybe i will pay for some ads to run on Photopea, if those ads spaces are for sale, , so you can see i am serious . 

You really should be more welcoming to people willing to take time to contribute to your github. II spent a lot of time helping your product with a lot of excitement and am posting this to my 9000+ followers on the steem blockchain, and its social media site steemit which, being open source and community run, is a perfect match for photopea. 

Sorry i did not title this as a "feature Request" Not every "issue" has to be negative. 

Thank you for the great product and have a great day.

**Comment by photopea** [comment]
Thanks for your comment :)

I do not want users to pay for Photopea with cryptocurrency, or encourage them to use cryptocurrencies without a stable value, when selling their work. But maybe we could use it in other ways.

Do you think there would be enough users interested in such feature? I am worried, that it may sound too complex for many people. What exactly do you propose? What should I do next?

**Comment by photopea** [comment]
I will close it now. I don't think there is enough interest in such features, and it is probably not worth to invest time into it.
