### ISSUE TITLE
Where is the source code of this open source project ?

### ISSUE THREAD

**Issue by cancerberoSgx** [photopea/photopea#1604]

**Comment by photopea** [comment]
Hi, Photopea is not open-source.

**Comment by cancerberoSgx** [comment]
ouch my bad . Nevertheless excellent job! on that UI (are you using ext ? - could you share the library name or if'ts opensource?) I would like to build something similar based on ImageMagick 100% in the browser. I'm working on emscripten port that behaves acceptably and has almost all the libraries and features - with no hacks and latest versions from git projects. Just in case you might find it useful: 

https://github.com/cancerberoSgx/magica
playground WIP: https://cancerberosgx.github.io/demos/magica/playground

 : [an example url](https://cancerberosgx.github.io/demos/magica/playground/#state=eyJleGFtcGxlIjp7Im5hbWUiOiJGbHV4IGFuaW0iLCJkZXNjcmlwdGlvbiI6IjxhIGhyZWY9XCJodHRwczovL2ltYWdlbWFnaWNrLm9yZy9Vc2FnZS9jYW52YXMvI3JhbmRvbV9mbHV4XCI+U2VlIEltYWdlTWFnaWNrIGV4YW1wbGVzIHBhZ2UgY2FudmFzLyNyYW5kb21fZmx1eDwvYT4iLCJ0YWdzIjpbImFuaW1hdGlvbiJdLCJpbnB1dEZpbGVzIjpbImJsdWViZWxscy5wbmciXSwic2NyaXB0IjoiPCUgXG5mdW5jdGlvbiBzZXF1ZW5jZShzdGFydCwgc3RlcCwgZW5kKXtcbiAgdmFyIGEgPSBbXVxuICBmb3IodmFyIGkgPSBzdGFydDsgaTw9ZW5kOyBpKz1zdGVwKXtcbiAgICBhLnB1c2goaSlcbiAgfVxuICByZXR1cm4gYVxufSBcbnZhciBzaXplID0gJzEwMHgxMDAnXG52YXIgZGVsYXkgPSAxMlxudmFyIGxpc3QgPSBzZXF1ZW5jZSgwLCAyMCwgMzU5KVxuJT5cbiMgZmlyc3QgZ2VuZXJhdGUgYSByYW5kb20gbm9pc2UgaW1hZ2UuIFdlIHVzZSBtaWZmIGZvcm1hdCB3aGljaCBpcyBmYXN0ZXJcbmNvbnZlcnQgLXNpemUgPCU9IHNpemUgJT4geGM6ICtub2lzZSBSYW5kb20gcmFuZG9tLm1pZmZcbiMgY29weSBpdCBqdXN0IHRvIHNlZSBpdCBpbiB0aGUgYnJvd3NlclxuY29udmVydCByYW5kb20ubWlmZiByYW5kb20uZ2lmIFxuXG4jIE5vdyBnZW5lcmF0ZSBzZXF1ZW5jZSBvZiB2YXJpYXRpb25zIG9mIGl0IHdpdGggZnVuY3Rpb24gU2ludXNvaWRcbjwlIGxpc3QuZm9yRWFjaChpPT57ICU+XG4gIGNvbnZlcnQgcmFuZG9tLm1pZmYgLWNoYW5uZWwgRyAtZnVuY3Rpb24gU2ludXNvaWQgMSw8JT1pJT4gXFxcbiAgICAtdmlydHVhbC1waXhlbCB0aWxlIC1ibHVyIDB4OCAtYXV0by1sZXZlbCBcXFxuICAgIC1zZXBhcmF0ZSBmbHV4XzwlPWklPi5taWZmXG48JX0pJT5cbiMgQW5kIGFwcGVuZCB0aGVtIGFsbCBpbiBhbiBhbmltIGdpZjpcbmNvbnZlcnQgLXNldCBkZWxheSA8JT0gZGVsYXkgJT4gPCU9IGxpc3QubWFwKGk9PmBmbHV4XyR7aX0ubWlmZmApLmpvaW4oJyAnKSAlPiBmbHV4X2FuaW0uZ2lmXG5cbiMgYSB0aHJlc2hvbGQgdmFyaWF0aW9uIG9mIHByZXZpb3VzOlxuY29udmVydCBmbHV4X2FuaW0uZ2lmIC10aHJlc2hvbGQgNzAlIGZsdXhfdGhyZXNfYW5pbS5naWZcblxuIyBBbm90aGVyIFwiZmlsYW1lbnRzXCIgdmFyaWF0aW9uOlxuY29udmVydCBmbHV4X2FuaW0uZ2lmICBcXFxuICAtc2lnbW9pZGFsLWNvbnRyYXN0IDMweDUwJSAtc29sYXJpemUgNTAlIC1hdXRvLWxldmVsIFxcXG4gIC1zZXQgZGVsYXkgPCU9IGRlbGF5ICU+IGZpbGFtZW50c19hbmltLmdpZlxuXG4jIGdlbmVyYXRlIGFub3RoZXIgbGlzdCB0aGlzIHRpbWUgXCJyaXBwbGVzXCJcbjwlIGxpc3QuZm9yRWFjaChpPT57ICU+XG4gIGNvbnZlcnQgcmFuZG9tLm1pZmYgLWNoYW5uZWwgRyBcXFxuICAgIC1mdW5jdGlvbiBTaW51c29pZCAxLDwlPWklPiBcXFxuICAgIC12aXJ0dWFsLXBpeGVsIHRpbGUgLWJsdXIgMHg4IC1hdXRvLWxldmVsIFxcXG4gICAgLWZ1bmN0aW9uIFNpbnVzb2lkIDIuNSw8JT1pKjUlPiBcXFxuICAgIC1zZXBhcmF0ZSArY2hhbm5lbCBmbHV4X3JpcHBsZXNfPCU9aSU+Lm1pZmZcbjwlfSklPlxuY29udmVydCAtc2V0IGRlbGF5IDwlPSBkZWxheSAlPiA8JT0gbGlzdC5tYXAoaT0+YGZsdXhfcmlwcGxlc18ke2l9Lm1pZmZgKS5qb2luKCcgJykgJT4gZmx1eF9yaXBwbGVzX2FuaW0uZ2lmIn0sImZpZWxkcyI6W3siaWQiOiJzcGVlZCIsInZhbHVlIjoiMiJ9LHsiaWQiOiJpbnRlbnNpdHkiLCJ2YWx1ZSI6IjkifSx7ImlkIjoid2lkdGgiLCJ2YWx1ZSI6IjE0In0seyJpZCI6ImhlaWdodCIsInZhbHVlIjoiMjEifV0sImlucHV0RmlsZU5hbWVzIjpbImJsdWViZWxscy5wbmciXSwic2NyaXB0IjoiPCUgXG5mdW5jdGlvbiBzZXF1ZW5jZShzdGFydCwgc3RlcCwgZW5kKXtcbiAgdmFyIGEgPSBbXVxuICBmb3IodmFyIGkgPSBzdGFydDsgaTw9ZW5kOyBpKz1zdGVwKXtcbiAgICBhLnB1c2goaSlcbiAgfVxuICByZXR1cm4gYVxufSBcbnZhciBzaXplID0gJzEwMHgxMDAnXG52YXIgZGVsYXkgPSAxMlxudmFyIGxpc3QgPSBzZXF1ZW5jZSgwLCAyMCwgMzU5KVxuJT5cbiMgZmlyc3QgZ2VuZXJhdGUgYSByYW5kb20gbm9pc2UgaW1hZ2UuIFdlIHVzZSBtaWZmIGZvcm1hdCB3aGljaCBpcyBmYXN0ZXJcbmNvbnZlcnQgLXNpemUgPCU9IHNpemUgJT4geGM6ICtub2lzZSBSYW5kb20gcmFuZG9tLm1pZmZcbiMgY29weSBpdCBqdXN0IHRvIHNlZSBpdCBpbiB0aGUgYnJvd3NlclxuY29udmVydCByYW5kb20ubWlmZiByYW5kb20uZ2lmIFxuXG4jIE5vdyBnZW5lcmF0ZSBzZXF1ZW5jZSBvZiB2YXJpYXRpb25zIG9mIGl0IHdpdGggZnVuY3Rpb24gU2ludXNvaWRcbjwlIGxpc3QuZm9yRWFjaChpPT57ICU+XG4gIGNvbnZlcnQgcmFuZG9tLm1pZmYgLWNoYW5uZWwgRyAtZnVuY3Rpb24gU2ludXNvaWQgMSw8JT1pJT4gXFxcbiAgICAtdmlydHVhbC1waXhlbCB0aWxlIC1ibHVyIDB4OCAtYXV0by1sZXZlbCBcXFxuICAgIC1zZXBhcmF0ZSBmbHV4XzwlPWklPi5taWZmXG48JX0pJT5cbiMgQW5kIGFwcGVuZCB0aGVtIGFsbCBpbiBhbiBhbmltIGdpZjpcbmNvbnZlcnQgLXNldCBkZWxheSA8JT0gZGVsYXkgJT4gPCU9IGxpc3QubWFwKGk9PmBmbHV4XyR7aX0ubWlmZmApLmpvaW4oJyAnKSAlPiBmbHV4X2FuaW0uZ2lmXG5cbiMgYSB0aHJlc2hvbGQgdmFyaWF0aW9uIG9mIHByZXZpb3VzOlxuY29udmVydCBmbHV4X2FuaW0uZ2lmIC10aHJlc2hvbGQgNzAlIGZsdXhfdGhyZXNfYW5pbS5naWZcblxuIyBBbm90aGVyIFwiZmlsYW1lbnRzXCIgdmFyaWF0aW9uOlxuY29udmVydCBmbHV4X2FuaW0uZ2lmICBcXFxuICAtc2lnbW9pZGFsLWNvbnRyYXN0IDMweDUwJSAtc29sYXJpemUgNTAlIC1hdXRvLWxldmVsIFxcXG4gIC1zZXQgZGVsYXkgPCU9IGRlbGF5ICU+IGZpbGFtZW50c19hbmltLmdpZlxuXG4jIGdlbmVyYXRlIGFub3RoZXIgbGlzdCB0aGlzIHRpbWUgXCJyaXBwbGVzXCJcbjwlIGxpc3QuZm9yRWFjaChpPT57ICU+XG4gIGNvbnZlcnQgcmFuZG9tLm1pZmYgLWNoYW5uZWwgRyBcXFxuICAgIC1mdW5jdGlvbiBTaW51c29pZCAxLDwlPWklPiBcXFxuICAgIC12aXJ0dWFsLXBpeGVsIHRpbGUgLWJsdXIgMHg4IC1hdXRvLWxldmVsIFxcXG4gICAgLWZ1bmN0aW9uIFNpbnVzb2lkIDIuNSw8JT1pKjUlPiBcXFxuICAgIC1zZXBhcmF0ZSArY2hhbm5lbCBmbHV4X3JpcHBsZXNfPCU9aSU+Lm1pZmZcbjwlfSklPlxuY29udmVydCAtc2V0IGRlbGF5IDwlPSBkZWxheSAlPiA8JT0gbGlzdC5tYXAoaT0+YGZsdXhfcmlwcGxlc18ke2l9Lm1pZmZgKS5qb2luKCcgJykgJT4gZmx1eF9yaXBwbGVzX2FuaW0uZ2lmIn0=)

I wander if you did you had any trouble for hosting this in github . I think you use ImageMagick (you announced there) I would like to share experience regarding close source products using imagemagick (and its delegate libraries) since I also want to release a close source utility  based on it. I think some libraries are GPL but I really don't have clear the consequences of that ...

Thanks

**Comment by photopea** [comment]
I made the UI using CSS and Javascript, I did not use any UI libraries. You can watch my presentation here: https://www.youtube.com/watch?v=IZmaeC_Ma5A

I have no experience with ImageMagick, I do not use it in Photopea.

**Comment by quantuminformation** [comment]
Too many people likely grew up in communism, or aspire to.

**Comment by aslamanver** [comment]
if you ever consider open-sourcing even a portion of Photopea, I believe there's a large community of developers who would be eager to contribute to such an incredible project and make it powerful ever.

**Comment by photopea** [comment]
Around 30% of the code that I wrote for Photopea is open-sourced here on this GitHub account (UPNG.js, UTIF.js, etc.).
