### ISSUE TITLE
Photopea crashes in Chrome on Mac quite often

### ISSUE THREAD

**Issue by gentle-media** [photopea/photopea#1605]
As the title implies, but I have to say it only happens when the tab with photopea.com is idle and it seems like it happens since there is this ad banner at the bottom of the UI.

**Comment by photopea** [comment]
Hi, sorry, I dont have any device with Mac :/ How exactly does it crash? You switch to another tab, and when you switch back, there is nothing?

**Comment by gentle-media** [comment]
Yeah, something like that. Or when I'm working in another app and come back to Chrome whit Photopea open in the active tab. I see then the Chrome 'Awe snap' page.
I have Photopea now open for quite a while, but there's no flashing banner ad at the bottom this time and thus far no crashing. So perhaps it has something to do with that banner ad location.

**Comment by photopea** [comment]
Can you confirm, that it crashes every time there is a banner at the bottom? Is it always the same banner? Can you take a screenshot of what banner it is?

**Comment by gentle-media** [comment]
For now there's no banner at the bottom, but next time there is, I will keep an eye on it.

**Comment by photopea** [comment]
The bottom banner is shown only if the window is at least 1000 px tall at the beginning

**Comment by gentle-media** [comment]
Ah ok... mine is 1080px and I never saw a banner at the bottom before. Only at the right that vertical banner. I've noticed the banner at the bottom only since yesterday a few times. And when it was there I had this crashing issues and when it's not there (like now) everything is fine.
Anyway... I will see what happens when the banner is there again.

**Comment by photopea** [comment]
I will close it for now.

**Comment by gentle-media** [comment]
Yeah, I had no crashing Photopea tab anymore, so perhaps it was something locally that was causing it.
