### ISSUE TITLE
https://www.photopea.com/ is down

### ISSUE THREAD

**Issue by nino-moreton** [photopea/photopea#1606]
Can't access the web app.

**Comment by yutakatsuchida** [comment]
Same. I hope it will be fixed ASAP

**Comment by Farwl** [comment]
Same here.

**Comment by nino-moreton** [comment]
I guess this highlights the problem with being a non open sourced, web app only product.

**Comment by Farwl** [comment]
Pretty much

**Comment by mmcrae37** [comment]
Has anyone heard if Photopea will be back up soon?

**Comment by nino-moreton** [comment]
It's now back up.
