### ISSUE TITLE
rasterized background (solid color) when exporting as svg

### ISSUE THREAD

**Issue by denkquer** [photopea/photopea#1607]
when exporting an otherwise fully vectorized image, but with a solid color backdrop. The SVG size expands x20 because it defines the solid color backdrop as png. Now I know this is because I just fill the background layer with a color but it should propably be optimized for user convenience. To prevent this I usually export with white (no) background and change color in XML. This is annoying, please fix :D

**Comment by photopea** [comment]
Hi, I am afraid I don't understand the problem.

You have a pixel layer in your document, what do you want it to be in the SVG? If you don't want it in the SVG, just hide it in the Layers panel.

**Comment by denkquer** [comment]
I want my SVG to have a background color.
There are 3 solutions to this problem:

1.  Add a png as a background layer. This blows up the file size so much that you could just use a png for most usecases.

2. Use the new SVG standard "viewport-fill" described here: https://www.w3.org/TR/SVGTiny12/painting.html#viewport-fill-property

3. Use a viewBox filling `<rect>` like so: `<rect width="100%" height="100%" fill="red"/>`and render it first.

It would be nice if a solid color background (example 1) could be optimized like solutions 2 and 3 suggest. Note: that viewport-fill is newer and might not be well supported.

**Comment by denkquer** [comment]
I believe a lot of people add a background color using the first method. Thereby wasting the filesize advantages of svg completly. Since this is just one color this does scale like normal svgs aswell. I bet you could also stretch a 1px*1px solid color png to get the same result but less costly on the filesize.

**Comment by photopea** [comment]
What do you mean by "blow up" the file size? A PNG with a solid color should not be bigger than 200 - 300 Bytes (even if it is 1000 x 1000 pixels).

Photopea has a fixed mechanism of SVG exporting. It exports pixels to pixels, and vectors as vectors. If you want to get a vector rectangle, why don't you draw a vector rectangle instead of a raster layer? You can do it with a Rectangle tool.

**Comment by denkquer** [comment]
I made this gist showing the difference in filesize. 
https://gist.github.com/denkquer/65c3eb5eb077eb72a7dd8c07a3a2af0f
Version 1 is 21,3 KB while Version 3 is 1.9KB

**Comment by photopea** [comment]
You are right, there was a bug, which made Photopea produce unnecessarily large PNGs.

I fixed it. The PNG in your case adds about 300 Bytes. Here is how it looks like: https://gist.github.com/photopea/bfdda3f075659059620403f480d01cd7

If you want a vector rectangle, create it in Photopea. You can also add a solid-fill layer: Layer - New Fill Layer - Color Fill.

**Comment by denkquer** [comment]
Cool, that seems like a much more reasonable size.
