### ISSUE TITLE
Simplify pasting from web

### ISSUE THREAD

**Issue by wernight** [photopea/photopea#161]
A common flow is:

 1. Take a screenshot
 2. Open PP
 3. Create new
 4. Ctrl + V

This avoids saving, finding the file, dragging to PP.

PS detects the clipboard and offers default image size matching it when creating a new image. This is probably not possible on the web due to security. I often then have to guess a larger image size and adjust after. No ideal for rapid operations (the most common ones).

One idea may be to auto-resize upon pasting on a new project. So it could add a resize canvas operation by default if user does this on PP at step 4, allowing to undo the last step if desired.

Another idea is to have a common paste/drop area like on most web tools, may be as default (instead of the sample even though the sample is cool it gets in the work of my daily tasks):

![image](https://cloud.githubusercontent.com/assets/145667/24794328/7c9e6fbe-1b85-11e7-99c5-40d7f1536d44.png)

This would reduce the steps and remove steps 3

**Comment by photopea** [comment]
Pasting images from clipboard and Drag-and-Dropping images from your computer already works for many years. Are you having problems with these?

**Comment by wernight** [comment]
Not with D&D. D&D is cool but most of the time I see and image on the web or I want to start from a screenshot (let's say that a bit more than half of my initial images and most of my "rapid" touch up).

For screenshot, the clipboard is fastest. It avoids steps like: Open file explorer, search for file, delete file after. This is what this issue is avoid at it's core.

The other use case is an image on the web. Actually even on Android since PP should work on tablets. I see an image, right click to copy to clipboard, and want to paste in PP.

**Comment by photopea** [comment]
I repeat it again. Pasting into Photopea (with Ctrl+V) already works :)

**Comment by wernight** [comment]
Yes it works. What I mean it that it could at step 4 resize the image to match the clipboard.

**Comment by photopea** [comment]
But users don't always want to resize the image after pasting new content. How should we solve it? What about showing a dialog window, where the user chooses "insert into current" or "open separately"?

**Comment by wernight** [comment]
So I think the best is to change the opening and show a Past or D&D area instead of the PP image. This reduces steps for all cases (avoids like 3 clicks at least).

The alternative I suggested is that it only resize when pasting in a new default image, and create a undoable step. The confirmation dialog is also an option.

**Comment by NatashaDK** [comment]
Photopea, a very good solution could be a google chrome extension like the one offered by Polarr.  https://chrome.google.com/webstore/detail/polarr-plugin-edit-any-ph/fhggacdeldojnpbgknpipalghlkbcimk)
Rightclick on any picture on the web, and "open with Photopea".

**Comment by wernight** [comment]
That could be an additional help but it wouldn't help with screenshots.

**Comment by photopea** [comment]
Hi, I have replaced the initial pea.psd file with a little menu.  You can do Ctrl+V right after opening Photopea.com, a new project will be created with dimensions corresponding to the pasted data.

**Comment by NatashaDK** [comment]
GREAT!!! - I love you guys ❤❤❤ - I'm using Photopea every day.
