### ISSUE TITLE
When disabling all layer effects, the effect mark keeps on the layer

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1610]
If you enable some effect on a layer, like drop shadow for example.

If you then deselect it, it will keep being marked on the layer.

![Screenshot 2019-08-10 at 20 22 53](https://user-images.githubusercontent.com/11801254/62828290-671b6e80-bbb0-11e9-91dd-4b578368d0de.png)

**Comment by photopea** [comment]
The "eff" mark means, that there are some layer effects. They can even be disabled.

It can be useful to have effects on the layer, all disabled, if you want to enable them again in the future.

**Comment by avagp** [comment]
Maybe I am missing something, but if I uncheck all the effects on the
effect window (not disabling them by the eye icon on the layer section) the
"eff" tag should remain?

If that is the case, why is not visible on all layers by default.

My issue with keeping the "eff" tag is that after a while, or after a
couple of days, when I reopen the file, i always get confused and have to
check of the layer that has the "eff" tag, that is supposed to not have an
effect, has an effect.

Personally, I believe is counterintuitive to keep the "eff" tag even after
unchecking all the effects on a layer.

😕

**Comment by photopea** [comment]
Yes, effects can still be there, but they are hidden. Checking the checkbox enables the effect (if it was disabled), or creates a new one (if such effect did not exist). But unchecking it only disables the effect, it does not delete it.

If you want to delete effects (and parameters of each effect), you can drag-and-drop them into a Garbage Bin in Layers Panel.

You can also right-click the layer (in Layers panel) - Layer Style - Clear, that will delete all effects (and "eff" symbol).

**Comment by avagp** [comment]
Perfect
