### ISSUE TITLE
Waiting for app.open(url, as, asSmart) to finish

### ISSUE THREAD

**Issue by gabiap** [photopea/photopea#1611]
Hello again!

I am using Photopea and the scripting window to generate a lot of graphics at once. I am basically looping trough a JSON array and placing elements based on their type (text or image).
Whenever I am placing an image, I use the app.open(...,..., asSmart) command. The problem is that the script keeps on going and reaches the activeDocument.save() and activeDocument.close() commands before finishing the placing of the images. I read in one of your answers here that you can't wait for the command to finish except when using the Messages API. From what I've seen, Photopea returns a "done" message, regardless of the asset type that is loaded. Since I'm also loading things like fonts, it would be difficult to keep track of what was loaded and what is still pending. I've tried using while loops inside the scripting panel, but they don't seem to work :(. 

Is there any chance you could build an app.open that runs in sync and returns a reference to the newly added layer?

Anyway, awesome work and keep it up!!

**Comment by photopea** [comment]
Hi, I am afraid I will not be able to implement it any time soon.

Are you running scripts through File - Script, or from external website through web messages?

**Comment by gabiap** [comment]
No problem:)
I'm testing out both at the moment

**Comment by photopea** [comment]
ok, so I will close it for now.
