### ISSUE TITLE
Safari iframe does not work

### ISSUE THREAD

**Issue by bendada3** [photopea/photopea#1612]
Hello,
from last update, Photopea does't work in iframe in Safari. Chrome, FF etc are fine.

Console error:
`SecurityError: IDBFactory.open() called in an invalid security context`

Browser:
`Safari 12.1.1`

Example:
[https://www.w3schools.com/code/tryit.asp?filename=G6YJZR8G2V2H](https://www.w3schools.com/code/tryit.asp?filename=G6YJZR8G2V2H)

**Comment by photopea** [comment]
Hi, sadly, I don't have Mac to try it, and Safari is not availabe for Windows :(

Do you mean the last update of Photopea or the update of Safari? 

Do you know what part of code causes the problem? There is no IDBFactory.open() in Photopea code :(

**Comment by bendada3** [comment]
I dont know if problems is in latest version of photopea or safari. I only know that worked in safari 1-2 months ago.

There is detail of error:
[https://www.dropbox.com/s/9xcuiso6o6g188w/Sn%C3%ADmek%20obrazovky%202019-08-14%20v%25C2%25A011.11.17.png?dl=0](https://www.dropbox.com/s/9xcuiso6o6g188w/Sn%C3%ADmek%20obrazovky%202019-08-14%20v%25C2%25A011.11.17.png?dl=0)

**Comment by photopea** [comment]
This was reported before: https://github.com/photopea/photopea/issues/1530

You should change the Safari settings: allow iframes (third parties) use IndexedDB.

**Comment by bendada3** [comment]
I am sorry I somehow missed that thread.

It looks like this settings is under global safari's setting "Prevent cross-site tracking" (which is default enabled I think). So normal user can't use photopea in iframe and other people have to choose between using photopea or allow this tracking globaly. 

https://support.apple.com/guide/safari/prevent-cross-site-tracking-sfri40732/12.0/mac/10.14

Never mind thank you for info :) 

BTW: your work on this project is increadible, keep it up :)

**Comment by photopea** [comment]
This decision of Safari makes no sense.

You have a website A, which contains a website B in an iframe. You allow website A to "track" you as much as it wants, but you forbid it to the B.

But it was the decision of A to display B in an iframe, i.e. A "trusts" B to some degree. Also, A has full control on displaying / not displaying B.

**Comment by bendada3** [comment]
I don't know, I am not safari/mac user. I was just trying find setting which will help with this problem and I found only "Prevent cross-site tracking" make some effect.
