### ISSUE TITLE
Count how many pixels in selection

### ISSUE THREAD

**Issue by Rtutorials** [photopea/photopea#1614]
If I select something is there a way to see how many pixels are in the selection?

**Comment by Rtutorials** [comment]
Nevermind, found it in Histogram

**Comment by photopea** [comment]
Yes, it is in a Histogram panel :) 

E.g. when I make a document 200x200 px, and make an ellipse selection from the top left corner to the bottom right, it shows 31418 pixels. The area of a circle should be 100 x 100 x PI = 10000 x 3.1416, so it seems to work.
