### ISSUE TITLE
can't import MS UIGothic Font file 

### ISSUE THREAD

**Issue by s5706820** [photopea/photopea#1615]
I don't really know why but this 
"Unexpected file structure. Please, send your file to support@photopea.com and we will solve it."
It the font pre-install in windows, if i did not misunderstand. 
![Screenshot (14-1)](https://user-images.githubusercontent.com/15662227/63102117-b1339400-bfa4-11e9-8862-5f3d41e7f6b0.png)

[msgothic.zip](https://github.com/photopea/photopea/files/3505897/msgothic.zip)

**Comment by photopea** [comment]
I fixed it, thanks for reporting! :)
