### ISSUE TITLE
can't put a curtain Value on paragraph setting below minus 20

### ISSUE THREAD

**Issue by s5706820** [photopea/photopea#1616]
I don't even know what this value is called. sorry about that
That value is the one pink arrow is pointing.
the slider is only -20 to 20 . for greater value, i can manually put the number, but when it come to lower it always change back to -20 .
Well, it's no need to rush, I can work around somehow with different text box.
Appreciate
![Screenshot (15)](https://user-images.githubusercontent.com/15662227/63182207-3a69ca00-c07c-11e9-8d76-f87443e8ed8f.jpg)

**Comment by photopea** [comment]
Fixed :)
