### ISSUE TITLE
Allow Vector shapes (created by Shape Tool or Pen) to use Blending Options when not given a predetermined fill or stroke.

### ISSUE THREAD

**Issue by CheeseManFuu** [photopea/photopea#1618]
On Photoshop whenever I would create GFX, I would typically use the shape tool and use layer properties on said shapes (for strokes, drop shadows, pattern fill, etc) in cases where I wanted only the frame to show up (example shown below). However, on Photopea, none of the styling shows up on *new* vector shapes when no predetermined fill or stroke is given, and only certain ones show up when either is filled (inner glow and inner shadow depend on having a fill, for example, both instances shown below). I can go into older PSDs with them functioning just fine, even staying fine when I edit them, but even copying styles to new shapes doesn't work.

The bottom line here is just to allow Blending options when a vector shape doesn't have either a predetermined fill nor stroke. The CSS is also slightly different between the two:

New shapes (with fill and stroke):
```
width: 580px;
height: 397px;
box-shadow: 0 0 30px rgba(0,0,0,0.85);
background-color: #808080;
border: 0.1px solid #808080; //0.1px is a workaround to have an essentially invisible pre-determined stroke
```

Old shapes that work:
```
width: 407px;
height: 476px;
box-shadow: 0 0 30px rgba(0,0,0,0.85);
background-color: rgba(255,255,255,0);
border: 12px solid ;
```
---

Example of what I do for boxes in GFX:
![Screenshot_2019-08-18_21-06-20](https://user-images.githubusercontent.com/7471405/63235168-10401580-c1fe-11e9-9cfe-fba6cef056ff.png)

Shape without fill:
![Screenshot_2019-08-18_21-11-18](https://user-images.githubusercontent.com/7471405/63235112-db33c300-c1fd-11e9-8a15-792313fa3c55.png)

Shape without stroke and fill:
![Screenshot_2019-08-18_21-10-37](https://user-images.githubusercontent.com/7471405/63235242-4d0c0c80-c1fe-11e9-8ea9-cf2c416b4fdf.png)

**Comment by photopea** [comment]
Hi, I think I made it work the same way as Photoshop works.

Although, I still find it very confusing, that when you increase the stroke from 0.0 to 0.01, "the whole layer disappears".
