### ISSUE TITLE
Channels issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1620]
I opened pea.psd and go to background layer. Select blue channel. Paint one line with brush (red color). Then select green channel and paint second line with brush. And result is this:
![image](https://user-images.githubusercontent.com/6370548/63281547-3a044580-c2ad-11e9-9bc7-bedf18107238.png)
I guess it should paint into selected channel only but it seems not to do that,..

**Comment by photopea** [comment]
fixed, thank you!
