### ISSUE TITLE
Quick Mask issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1621]
I select circle and turn on Quick Mask mode.
Then I select circle as is seen on screenshot and press delete key on keyboard.
But it did not remove entire circle from quick mask only part of it as seen on second screenshot.
![screen1](https://user-images.githubusercontent.com/6370548/63282123-6c627280-c2ae-11e9-8bb8-69edba12a2ed.jpg)
![screen2](https://user-images.githubusercontent.com/6370548/63282122-6c627280-c2ae-11e9-85ab-e6f670653838.jpg)

**Comment by photopea** [comment]
Hi, I fixed it.

Also, when you Clear or Erase (with Eraser tool) from a raster mask, quick mask, or a single channel, it just fills the area with a backgorund color.
