### ISSUE TITLE
Drop shadow changes color when doing Swap Colors

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1623]
1. I open new project with transparent background.
2. Paint with brush
3. Add Drop Shadow to layer - keep all setting except I change color from black to white.
4. Now when I swap current foreground and background colors several times with Swap Colors (X) - up/down button or with "X" on keyboard -> color of Drop Shadow effect changes!

**Comment by photopea** [comment]
Fixed! I would never expect such bug to exist :D
