### ISSUE TITLE
Request Pseu-bold font for the font that bold is not available

### ISSUE THREAD

**Issue by s5706820** [photopea/photopea#1624]
i found that Photopea can make the character italic with out an actual italic font.
So, i wonder if bold thing is also possible to implement. 
if it's possible, I want one. LOL 
if not, well, i guess i need to work around with 1px stroke. (that make it look kinda weird tho LOL)

**Comment by photopea** [comment]
Sure, I just added it :)


![fauxbold](https://user-images.githubusercontent.com/15955558/63777056-c4b6f700-c8e2-11e9-9973-1256dc64aa0e.gif)
