### ISSUE TITLE
Preview of some font overflows to other font preview

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1625]
for example Linux Libertine O
see screenshot
![image](https://user-images.githubusercontent.com/6370548/63493836-bd47b600-c4bc-11e9-9670-e77de21ce365.png)

**Comment by photopea** [comment]
Hi, I knew about it, but I was too lazy to fix it :(  Now I fixed it! The image with previews also became 5 kB smaller: https://www.photopea.com/rsrc/fonts/fonts.png
