### ISSUE TITLE
Move Tool - Transform controls issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1627]
When you have some selection -> Transform controls checkbox on Move Tool now shows transform controls on selection instead of layer - i think they were on layer before - and they do not work.
Also when you turn on Quick Mask Mode and Transform controls checkbox is checked it shows transform controls on layer now but they also do not work in this case.

**Comment by photopea** [comment]
Hi, when you have a selection, Transform controls are always around that selection (because if you enable Free Transform, it will transform only the selected area). It does work for me.

Free Transform does not work on quick masks at the moment.
