### ISSUE TITLE
Image stuck

### ISSUE THREAD

**Issue by Keishahhhh** [photopea/photopea#1628]
When I open an existing image it does not let me move it around. I have to exit the website numerous times before I can finally grab it and begin adjusting.

**Comment by photopea** [comment]
Hi, does it happen with any file, or with a specific file? How large is that file?

**Comment by Keishahhhh** [comment]
I take photos on my camera and edit numerous so it's hard to tell which exact ones it does it with but all the photos are generally around 4MB - 7MB

**Comment by photopea** [comment]
I think it is related to a previous problem, so I will close this one and we can discuss it in the previous topic.
