### ISSUE TITLE
Mouse won't let go of image

### ISSUE THREAD

**Issue by Keishahhhh** [photopea/photopea#1629]
When dragging a new photo onto an existing already opened template. It often, when I grab the new photo to move around, doesn't get "unclicked". The mouse just doesn't let go no matter what other buttons I click etc. I usually have to exit out of the website, open it up and then exit out of it again before it works. But eventually occurs again a few photos later.

**Comment by photopea** [comment]
Hi, does it happen with any file, or with a specific file? How large is that file?

**Comment by Keishahhhh** [comment]
I take photos on my camera and edit numerous so it's hard to tell which exact ones it does it with but all the photos are generally around 4MB - 7MB

**Comment by photopea** [comment]
Does it happen on a desktop computer, or on a phone? Is there a specific image, for which it happens every time? Can you send that image to support@photopea.com?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
