### ISSUE TITLE
Can't Paste

### ISSUE THREAD

**Issue by J4s0nW4lkr** [photopea/photopea#1630]
When I go to cut part of an image to paste it nothing happens when I click Cntrl+X or when I manually press paste on the edit dropdown.

Thank you, I need this fixed because I use photopea almost daily

**Comment by photopea** [comment]
Hi, can you update your browser? Also, make sure you gave Photopea access to your clipboard.

Many users deny the access to the clipboard, when they are asked, and then, they wonder, why copying and pasting does not work.

**Comment by J4s0nW4lkr** [comment]
Thanks! worked

**Comment by photopea** [comment]
No problem, it is reported quite often :) https://github.com/photopea/photopea/issues/1622
