### ISSUE TITLE
Freezes when I add a layer!

### ISSUE THREAD

**Issue by zoellaz** [photopea/photopea#1631]
Hi, I'm new to using Photopea (basically a beginner) and was just wondering if it's just a glitch that the website completely freezes when I'm duplicating a layer onto another image?

**Comment by photopea** [comment]
Hi, does it happen for all files you try? Or just for a specific file and a specific layer?

**Comment by photopea** [comment]
Are you doing it on a phone or on a desktop? Are there adjustment layers in your PSD? Is WebGL enabled? You can see it in More - Use WebGL.

**Comment by photopea** [comment]
I would like to try it myself, to see what is going on. Can you send me your PSD and the other image to support@photopea.com ?

**Comment by photopea** [comment]
So I opened both of your files in Photopea simultaneously. I switched to a JPG one, right-click the layer, Duplicate Into, I chose "PSD 1.psd", then, I pressed OK.

It was duplicated immediatelly. I switch to a "PSD 1.psd", the new layer is there.

Is that what you do? Or did you do something differently?

**Comment by photopea** [comment]
I am doing it in Chrome as well, and it gets copied immediatelly. Are you using the latest Chrome?

**Comment by photopea** [comment]
I dont have Mac, to try it in Chrome on Mac (I did it in Chrome on Windows).

I will close it for now.
