### ISSUE TITLE
Can i move picture under mask separately form mask?

### ISSUE THREAD

**Issue by s5706820** [photopea/photopea#1633]
Not really an issue but i Don't know how to do it. 😅😅😅
Can i move or even transform the (imported) picture under the layer mask separately? If yes, how?
It kind of that the size and position of the mask is good. But the (imported) image  is a bit off so i try to transform it, but it tell me that it become smartobject and need to rasterized, but i dont want to rasterized it.
So for now i need to imported a duplicate pic, adjust it and move the layer mask to it as a final step.

**Comment by photopea** [comment]
Hi, you can "link" or "unlink" the mask from the main image (with a chain icon), to be able to work with it separately.

Read here about masks: https://www.photopea.com/learn/masks
