### ISSUE TITLE
is it possible to modify text box?

### ISSUE THREAD

**Issue by s5706820** [photopea/photopea#1635]
like to be trapezium or diamond or polygonal ?
not like warp which will distort the text and already function perfectly , i want just align the text in modify shape. is it possible?
Thx you, Ivan

**Comment by photopea** [comment]
Hi, I think it should be possible once we implement this feature: https://github.com/photopea/photopea/issues/833

**Comment by MichalSZZ** [comment]
@photopea are you thinking about custom text box with any shape like here https://www.youtube.com/watch?v=NL0Z-AQconQ ?
or about writing on a path of any shape?

**Comment by photopea** [comment]
Seems like both are possible to store in PSD files. So we could add both.
