### ISSUE TITLE
Dotted rectangle remains on screen after Deselect is performed

### ISSUE THREAD

**Issue by max8938** [photopea/photopea#1636]
After making a rectangular or ellipse select and then clicking outside to deselect it, the dotted selection rectangle/ellipse is still displayed even though Deselect action was correctly performed (it is visible in History, and Copy action does not copy that previously selected image part). An example is in the attached screenshot, where the selection rectangle is still visible even though Deselect is the last action performed.

This was observed on MacOS Mojave, in Firefox and Safari. On the other hand, in Chrome it works correctly, the selection rectangle disappears when expected.

![deselect bug example](https://user-images.githubusercontent.com/38248011/63857407-ef1cb900-c9a3-11e9-848e-6813aab54a96.jpg)

**Comment by photopea** [comment]
Hi, I tried it in Chrome and Firefox on Windows, and it never happens. I guess there is some problem with GPU drivers. Could you update your MacOS?

Can you try to disable WebGL: More - Use WebGL? I guess it will disappear (but it is not a fix).

**Comment by max8938** [comment]
Hi, thank you for the fast reply. Disabling WebGL indeed solves this issue, the rectangle now disappears correctly.

I will try updating the OS to the latest version and get back to you (there are a couple of minor updates).

**Comment by max8938** [comment]
Just updated my Macbook to the latest MacOS, but the problem still persists (unless WebGL is disabled).

**Comment by photopea** [comment]
It is a bug in OS / Browser. Try to report it to these browsers, or use Chrome :/
