### ISSUE TITLE
CMD + - zoom out bug

### ISSUE THREAD

**Issue by RewindFest** [photopea/photopea#1637]
If you zoom out using CMD + - and then without releasing CMD, press any key, regardless of what you try to do, it keeps zooming out.

**Comment by photopea** [comment]
Hi, I believe we already discussed it. Mac OS does not let any website know, that a key has been released, while CMD is pressed. There is nothing we can do about it at our end :(

Also, we did not find any way to contact Apple. Our messages were rarely answered. You can try to contact Apple yourself.
