### ISSUE TITLE
Fonts seem to be only using bold

### ISSUE THREAD

**Issue by Poison-Pancakes** [photopea/photopea#1638]
I upload a file with the Air America font and as soon as I click on it with the text tool, it switches to bold. In the text type there is only regular so I cannot change it there. It seems that most if not all of the fonts are also stuck on bold.

**Comment by photopea** [comment]
Hi, did you open a PSD file in Photopea, which has a text layer, which is supposed to use "Air America" font? Could you send us your PSD file to support@photopea.com ?

**Comment by Poison-Pancakes** [comment]
Yes, correct. No problem, I'll send it over now.

**Comment by photopea** [comment]
So it seems like there is Faux Bold applied to your text layer. Choose a Type Tool (e.g. by pressing T), open a Character panel (Window - Character), and disable the Faux Bold (as shown in the GIF below).
![63777056-c4b6f700-c8e2-11e9-9973-1256dc64aa0e](https://user-images.githubusercontent.com/15955558/64001033-41c2b600-cb07-11e9-9412-3bba1b881e48.gif)
