### ISSUE TITLE
Script: Open a smart object in a new tab and edit it

### ISSUE THREAD

**Issue by 0x15f** [photopea/photopea#1639]
I have a smart object/layer group that I can double click to open in a new tab and edit it. 
![image](https://user-images.githubusercontent.com/17521434/63986354-8b78b580-caa1-11e9-9f27-2889f9097e5d.png)

I need to use a script to open this and load a new layer into it from an image.

**My current script:**
```js
app.activeDocument.layers[0].visible = false;

let layer = app.activeDocument.getLayerByName('Sticker');
//todo open layer in new tab
app.open('https://my.site/images/image.jpg', as, true);
app.activeDocument.close(SaveOptions.SAVECHANGES);

app.activeDocument = app.documents[0];

//export document as jpg
```

**Comment by 0x15f** [comment]
This works if doing it manually, just can't script it. I'm using a headless chromium instance but even when double clicking the layer it doesn't open.

**Comment by 0x15f** [comment]
Current solution I've come up with:

Use headless chrome and open the url with the pre-script (load the image).. Delay chrome 2s then open the script model and paste the code to move the image then click the button. It isn't ideal but it should get the job done.

**Comment by 0x15f** [comment]
Nevermind that doesn't work. The script box is dynamically inserted and removed..

**Comment by photopea** [comment]
Hi, could you try to make a Photoshop script, which does this (and make sure it works in Photoshop)?

We would like to provide a scripting API similar to Photoshop, without adding many "extra" features, unless they are necessary.

**Comment by 0x15f** [comment]
Can I run actions in Photopea? It can't be done with a script but I just did it with an action in PS.

**Comment by photopea** [comment]
Hi, all scripts in Photopea are synchronous now, so you would have to split it into two scripts.

Photopea can run actions, but not all of them.

**Comment by 0x15f** [comment]
How do I split scripts with the API?

**Comment by photopea** [comment]
just call a first script, wait until it finishes (e.g. until a file is loaded), then call a second script.

**Comment by 0x15f** [comment]
I'm attempting to do this with headless chrome, no real interaction with the page. I just replicated what I needed to in a Photoshop Script / Action. 

**API JSON:**
```json
{
	"files": [
		"https://lynndigitalllc.s3.us-east-2.amazonaws.com/366-1+Laptop+Sticker+01.psd"
	]
}
```

**Photoshop Script 1:**
```js
app.activeDocument.layers[0].visible = false;
app.activeDocument.activeLayer = app.activeDocument.layers.getByName('Smart Objects').layers[1];
app.open('https://i.imgur.com/HKgVxo9.png', as, true);
```
**Photoshop Script 2:**
```js
MoveLayerTo(app.activeDocument.activeLayer, 900, 1350);

function MoveLayerTo(fLayer,fX,fY) {

  var Position = fLayer.bounds;
  Position[0] = fX - Position[0];
  Position[1] = fY - Position[1];

  fLayer.translate(-Position[0],-Position[1]);
}
```

Then I need to trigger a save to jpg and download it to the browser.

**Comment by 0x15f** [comment]
**Questions:**

1. Are "files" passed in the JSON loaded in order? E.g If I pass my PSD then my action file will the PSD load then the action?
2. Are scripts ran after the files are loaded?
3. Can you implement the `$.sleep(ms)` function like PS?
4. Is there an API method to trigger a save to browser? Or CSS/JS/X selectors I can replicate in headless Chromium?

Amazing service by the way, if you have a Patreon I'd love to support it.

**Comment by 0x15f** [comment]
My Ideal Workflow:

I'd like to load the page in headless chrome with the assets/files/actions/etc loaded in the json then use headless chrome to trigger a script then click some of the buttons.

**Comment by photopea** [comment]
Hi, 

1) Photopea does load all files in order. This allows using app.documents[i] to access the file you need in a Script.
2) If you are talking about a "script" parameter, it is described here: https://www.photopea.com/api/
3) Our current implementation does not allow "waiting" :/
4) There is a regular "Document.save()" - see Adobe docs, and "Document.saveToOE()" - see here https://www.photopea.com/learn/scripts

I wrote a tutorial about how to work with Smart Objects from a script:  https://www.photopea.com/tuts/edit-smart-objects-with-a-script/

Note, that if you want to load data in the middle of the script, you should split it into two scripts (the first part will initiate the download, and when it is done, call a second part of the script).

**Comment by jmverges** [comment]
👋 Hi there, 

I know this is a closed old issue but I'm in the same situation here. The tutorial about Smart Objects doen't handle the replacement of a content inside the Smart Object. When doing it programatically via onMessage and I need to do a setTimeout and send 2 messages instead of 1 message. 
First message will open the smart object and do app.open to place a new image inside. Second message with timeout is the one that .clear the layer, save and close. 
Is there any other way to handle this scenario or just old good setTimeout (which is just gambling about connection bandwith and so... )
Many thanks!

**Comment by photopea** [comment]
You can send Photopea your image as an ArrayBuffer using the postMessage(). Then, it will be processed immediately.
