### ISSUE TITLE
Cropping weird behavior

### ISSUE THREAD

**Issue by wernight** [photopea/photopea#164]
I found that the crop tool has a few weird behaviors:

 - If I select the crop region from bottom right to top left, then the cropped image is mirrored (up-side down).
 - If I select an area that is out of the image, it appends some transparent pixels (I don't remember having this issue in PS). It makes cropping only some corners (e.g. only bottom and right) pretty tricky. If the current behavior is really desired, may be magnetic selection would work.
 - In PS I could double click inside the crop rectangle to perform the operation (I think Ctrl + Enter or Enter also does it but I used to double click as it's the fastest)

**Comment by photopea** [comment]
Hi,
- You are right, we should fix that.
- I think that tis is correct. Cropping should allow you to make the canvas larger. Regarding corners, you can press Ctrl+A to select all and then press the button "Selection" to adjust the cropping area according to the selection. Or we can make corners "magnetic" somehow.
- in Photopea, you can confirm the cropping with Enter. But adding doubleclick should not mind anything.

**Comment by photopea** [comment]
I decided to forbid dragging the corner Left or Up (towards the original point) to prevent this weird behavior. It works the same for Type tool, too.

Also, doubleclick will confirm the cropping.

**Comment by photopea** [comment]
It has been fixed - you can draw a cropping rectangle in any direction.
