### ISSUE TITLE
How can I implement the refine-edge

### ISSUE THREAD

**Issue by maybepossible** [photopea/photopea#1640]
The refine-edge is really really amazing! As a student in Image Processing, I am quite curious that which algorithm is used behind this. I am wondering if it is possible to give me some hints or which direction should I work on to implement this? Thank you in advance.

**Comment by photopea** [comment]
Hi, there are many algorithms to do this. This area is often called "Foreground extraction", "Image Matting", "Alpha Matte", etc.  Some use "trimap", some use stereo images (to reconstruct depth map), some use video sequences.

I even found a video about it: https://www.youtube.com/watch?v=Zn1TtXKI9-I

https://neurohive.io/en/state-of-the-art/alphagan-natural-image-matting/
