### ISSUE TITLE
Feature request: sample black point, grey point, white point on Levels adjustment

### ISSUE THREAD

**Issue by erikw1234** [photopea/photopea#1642]
Hi - the Levels adjustment is great. 

Can you implement the feature where you can set the black point, white point, and grey point? I find that very helpful for using the Levels adjustment in PS and it would be great to see it in PhotoPea.

**Comment by photopea** [comment]
Hi, it was implemented.
For Levels and Curves, you can choose the White, Grey and Black point by clicking into the image.

For Hue/Sat, you click-and-dragging into the image will change the saturation of the specific channel.
