### ISSUE TITLE
Spot Healing problem

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1645]
I was using Spot Healing Brush Tool and in the middle of painting with it I realized I did mistake and wanted to cancel action and start over (still left mouse button down) - so I pressed Backspace - but it did not cancel action and after I released mouse button it deleted my layer and applied Spot Healing after that. So I undid both steps in History but gray markings from Spot Healing Brush Tool stayed in layer. See screenshot...
![obrazek](https://user-images.githubusercontent.com/6370548/64062474-f7186b00-cbe6-11e9-9991-2df07e9de54f.png)

**Comment by photopea** [comment]
Hi, I fixed it. Now, Delete / Backspace keys delete a layer only if the mouse is not pressed.

BTW. I have been seeing the same ad for Vitamin C in Photopea for the last couple of days :D
