### ISSUE TITLE
Feature Request: Add More Features to Ctrl+S Dialogue, Better Smudge Tool

### ISSUE THREAD

**Issue by calclover2514** [photopea/photopea#1646]
Photopea would be better if there were a more Photoshop-like save menu for Ctrl+S (e.g. Quick export instead of Save for Web).
The Smudge tool would be much better if it used a more efficient algorithm, because as it is right now, it is so slow it is unusable.

**Comment by photopea** [comment]
Quick Export? Do you mean exporting without opening a Save For Web? But you can press Save in Save for Web, there is just one extra click.
The Smudge tool should work smoothly, when the brush size is under 70px. How large is your brush? Do you know any better algorithm?

**Comment by calclover2514** [comment]
Yes. In Photoshop, the exporting without Save for Web has some features that I don't see in the save for web dialogue, such as "Interlace".
I don't have a better algorithm in mind, and my brush was WAY bigger than that, so that is the problem there.

**Comment by photopea** [comment]
"Interlace" was useful in 90s, when internet speed was very slow. I believe that now, there is no point in using it (it only makes files bigger). I think all useful settings are present in Save for Web.

I made Smudge about 40% faster, when Hardness is 0. Sadly, I don't know any better algorithm for Smudge :(  From my experience, smudge with a large diameter in Photoshop is also slow. You should buy a better computer, to make programs work faster.

**Comment by calclover2514** [comment]
The smudge tool is WAY better. Thanks!
