### ISSUE TITLE
Feature Request: Image Mode

### ISSUE THREAD

**Issue by calclover2514** [photopea/photopea#1647]
It would be extremely helpful if you could add a "Image Mode" menu as seen in Photoshop here:
![Pic1](https://user-images.githubusercontent.com/43104632/64070749-de37a600-cc36-11e9-8467-5c0da2fff320.png)
It would also be great to be able to have custom indexed palettes (.act) as seen here:
![Pic2](https://user-images.githubusercontent.com/43104632/64070754-01faec00-cc37-11e9-971d-56ec79fb45da.png)

**Comment by photopea** [comment]
Hi, it is very easy for me to add these menus. But you probably mean adding the same features, as you know from Adobe Photoshop.

Adding custom color models and bit depths would be quite hard, and I don't think it is such a crucial feature. I think there are many much more important features.

**Comment by calclover2514** [comment]
I do graphic design for 8-bit games that I write, and I ALWAYS use this feature to make sure it will look correct on the platform I am developing for. If this could be implemented, that would be great, as I can't use Photopea for the aspect of graphic design that I do the most.

**Comment by photopea** [comment]
What feature exactly do you need? Do you mean representing an image as indexed color with a palette? I don't understand, what problem are you trying to solve.

**Comment by calclover2514** [comment]
Let's say I wanted to make an image look good on the `Microsoft Windows (System)` color palette (8-bit, 256 indexed colors) or a simplified color palette (4-bit, 16 colors). In Photoshop, I would go to Image > Mode > Indexed Color and choose the `Microsoft Windows (System)` color palette from the dropdown, load my `simplified.act` file for the simplified color palette, or define a new color palette and save it as a new `.act` file. I could then choose if I wanted to use dithering to make the image look better after the conversion.
It would also allow for switching between RGB and CMYK color, as well as 8, 16, and 24 bit color modes.

**Comment by photopea** [comment]
Today, almost all devices can display 16 million colors. But if you want your images to be limited to smaller amount of colors, you can define your colors in Swatches (or load the .aco file with necessary colors) and then, use only these colors when painting.

Or do you have photos (with thousands of colors), which you want to convert into a smaller number of colors? There is Image - Adjustment - Posterize. But we could add a new filter, that would convert images to specific palettes, or even find the best palette for a specific image.

When you export an image as PNG, the quality slider actually defines the number of allowed colors. It finds small palettes, in order to decrease the file size.

**Comment by calclover2514** [comment]
I have photos with lots of colors that I would like to convert. I have set up custom palettes for devices that I program for in Photoshop and I would like to be able to load them in Photopea.

P.S. The `Indexed Color` option in `Image > Mode` is pretty much nothing more than a filter anyway, as is RGB and CMYK. The only difference is that it limits your color palette to those colors once you set the color mode.

**Comment by c-sanchez** [comment]
I think color mode option is very important, at least in game development is really useful, many game uses color indexed images.

**Comment by photopea** [comment]
@c-sanchez I think modern hardware is capable of displaying at least millions of different colors.

You can still use only e.g. 10 colors when you create your image in Photopea. You can also do Image - Reduce Colors, to find a good palette (which is preserved when you save your image as PNG etc.)

**Comment by JebGrep** [comment]
This is actually a surprisingly important feature for modern art and design that draws on any kind of pixel art aesthetic. Generating palette constrained dithering for existing raster images seems to be impossible with photopea currently. Might have to check out Affinity Suite sadly :s

**Comment by photopea** [comment]
You can generate a restricted palette with dithering in Photopea when you export a GIF.

Or press Image - Reduce Colors.

**Comment by JebGrep** [comment]
I just had a go at this and this solution doesnt work. Without an indexed palette there is no useful way to control the outcome, there is just a reduced color slider and a choice of two algorithms. Users that work with pixel art require tight control over the available color selection without automation. I also have an additional more niche application using indexed colour for industrial design where CAD software requires images restricted to specific defined hues representing particular data layers within other software. This sort if work is usually done with vector rather than raster data but it would be good to have the option (Separate issue: No choice of dithering algorithm on GIF export)

**Comment by photopea** [comment]
That looks like an error. could you share your image with us?

**Comment by FlarosOverfield** [comment]
![Pmd With Pmd256 Palette Black Fix](https://user-images.githubusercontent.com/24918282/234617413-42f480b4-6409-4fd0-a7df-eced9e1f935f.png)
Don't bother, i used a **real** program instead.

**Comment by FlarosOverfield** [comment]
![image](https://user-images.githubusercontent.com/24918282/234621790-61f5fc8e-c063-41ec-af62-87f007869c23.png)
Suuuure it does.

**Comment by camoody1** [comment]
Typing "Sigh" doesn't really tell us anything. What exactly is your issue if not the icons appearing black?

**Comment by camoody1** [comment]
> Tfw you open an issue 4 years ago and wake up to people arguing on it lol

LOL. I don't even know the whole issue. I'm just reacting to a rude post made by an apparently spoiled child. Drives me crazy when someone starts bitching about a free to use application as if they paid good money for it. I understand requesting help or new functionality, just don't be an ass about it.

**Comment by programmer2514** [comment]
> > Tfw you open an issue 4 years ago and wake up to people arguing on it lol
> 
> LOL. I don't even know the whole issue. I'm just reacting to a rude post made by an apparently spoiled child. Drives me crazy when someone starts bitching about a free to use application as if they paid good money for it. I understand requesting help or new functionality, just don't be an ass about it.

Yeah, as a FOSS developer, I 100% agree with you there. I was just very confused by my GitHub notifications for a bit XD

**Comment by FlarosOverfield** [comment]
The enormous issue here is that the developer is telling us to use a feature that is limited to 50 colors to replace a feature designed for 256 color palettes.

And even if it *wasn't* limited to 50 colors, and even if i *was* extra careful to not accidentally use colors that aren't in my palette, it would be useless, because Photopea cannot save Indexed PNG's.

![image](https://user-images.githubusercontent.com/24918282/234624295-b649c088-2110-4e48-a3f3-f672901c6fac.png)

And i already tried "not being an ass about it", and this is what happened. https://www.youtube.com/watch?v=SQDa9kwlJYc

**Comment by programmer2514** [comment]
@FlarosOverfield I'm not even sure what that video is showcasing, but it doesn't really matter. The software is provided to you for free. It takes devs hundreds of hours of their time to maintain and improve software like this and this guy is doing it for free. He is under no obligation to implement anything he doesn't want to, and being rude won't change that. If your use case is so important, there are plenty of alternative applications you can use, as I have been doing for the past 4 years when it comes to indexed color.

**Comment by FlarosOverfield** [comment]
I dunno i guess i'm just tired of "just use a paid program instead bro" being an excuse to close github issues as "completed" when they clearly aren't, especially for a program with so much potential like Photopea.

At **least** add a `wontfix` tag so people don't spend two hours banging their head on their desk

**Comment by programmer2514** [comment]
Nobody is saying to use a paid program. Use GIMP, it has the functionality you want for free.

And yeah, you may not agree with the dev's decisions but that isn't an excuse to be rude.

**Comment by FlarosOverfield** [comment]
> Try GIMP
> Try to import .ACT file
> Not supported
> Import sprite sheet with preapplied .ACT file
> Export palette as .TXT file from gimp
> Import .TXT file
> Not supported
> Search on the internet what palette file types GIMP supports
> ONLY AND EXCLUSIVELY .GPL files
> Try to export palette as .GPL file from gimp
> Exporting palette as .GPL is not supported

wow

**Comment by photopea** [comment]
"Reduce Colors" has two modes: "Cartoon" and "Photo". "Cartoon" is supposed to create large areas of the same color (by joining pixels of a similar color together). You should use the "Photo" mode for your image (as you have many tiny pixels with differend colors).

When you export a PNG, and you have 256 colors or less, it is always saved as an indexed color. 

Actually, the "Quality" slider in exporting PNG finds the best palette (0% = 2 colors, 50% = 256 colors).

**Comment by FlarosOverfield** [comment]
> "Reduce Colors" has two modes: "Cartoon" and "Photo". "Cartoon" is supposed to create large areas of the same color (by joining pixels of a similar color together). You should use the "Photo" mode for your image (as you have many tiny pixels with differend colors).
> 
> When you export a PNG, and you have 256 colors or less, it is always saved as an indexed color PNG.
> 
> Actually, the "Quality" slider in exporting PNG finds the best palette (0% = 2 colors, 50% = 256 colors).

![image](https://user-images.githubusercontent.com/24918282/234669194-71bf41f2-528a-44f5-af89-78397b1dd23b.png)

Then why does the export window not display the number of colors? And why is there no option to force a certain set of colors such as [Pmd256B.txt](https://github.com/photopea/photopea/files/11336228/Pmd256B.txt)?

**Comment by photopea** [comment]
We expect that modern displays can display any color, so there is no need to ask for a certain palette.

So it is all done only for a purpose of compression. You tell Photopea how large PNG you want, and Photopea does all it can to make the file smaller, while keeping it as similar to the original as possible (users usually dont care what exactly was done - creating a smaller palette in this case).

But if you want to export a palette, or import your own palette, it is probably more suitable for the "Reduce colors" tool.

**Comment by FlarosOverfield** [comment]
The reason we use palettes is not for display compatibility, but to ensure that all sprite sheets use consistent colors with one another. It's the same reason lo-fi music reduces sample quality on purpose. 

I also couldn't help but notice that the Reduce Colors tool **DOES** support 255 colors, but only by enabling Edge's developer mode to set numbers higher than the slider allows.
![image](https://user-images.githubusercontent.com/24918282/234678676-2cc7971c-4950-4921-a3dd-6de3a50d3c11.png)

Should I create a new issue for adding Custom Palettes in the Reduce Colors tool? This feature alone paired with PNG export set to 50% would be enough for most 8 bit color stylized workflows.

**Comment by photopea** [comment]
You can just type any number into the window, there is no need for a "developer mode".

So do you want to load your own palette from your computer, or to save a palette? Is there any standard format for palettes? Currently, we use .ACO to save color swatches.

What exactly is your goal? Do you want to convert many different images into a specific palette (the same for one images), and you have that palette in advance?

**Comment by photopea** [comment]
BTW. do you think we should allow reducing colors to more than 256, e.g. to reduce a photo with 50,000 colors to 1,000 colors? there is a bug now (it makes black pixels), but it would be easy to do.

**Comment by FlarosOverfield** [comment]
> So do you want to load your own palette from your computer, or to save a palette? Is there any standard format for palettes? Currently, we use .ACO to save color swatches.

There are several. ACO is a Photoshop swatch file format, while ACT is a Photoshop palette file format. Swatches are just easily accessible colors for brushes, while palettes have many more functions, such as replacing all colors of one sprite with another set of colors, by simply swapping the palette.

Here are open source palette formats, all supported by Aseprite: 

[Pmd256B.txt](https://github.com/photopea/photopea/files/11341134/Pmd256B.txt)
![Pmd256B](https://user-images.githubusercontent.com/24918282/234800686-28abe30a-a552-4f1a-9dde-3238c1c7183a.png)
![PMD256B](https://user-images.githubusercontent.com/24918282/234801118-ec8ec158-ea5d-4cdb-8954-4dd36caca8a6.gif)

Other open source formats are PAL, HEX, GPL, and CSS, but Github doesn't let me upload them for some reason. All of them are easily human editable and readable with any text processor. ACT is proprietary, but being able to import it would be best case scenario.

1024 colors would be a good limit for Reduce Colors before diminishing returns I think.

**Comment by FlarosOverfield** [comment]
> What exactly is your goal? Do you want to convert many different images into a specific palette (the same for all images), and you have that palette in advance?

Precisely. Currently the only program that can do that with one Alpha matte is Photoshop.

**Comment by photopea** [comment]
But what about the transparency? Do any palettes contain the transparency value, or you want to modify only colors while keeping transparency identical? Or is your transparency always binary: 0/255?

Currently, if you have a an image with all pixels black and 30 different levels of transparency, photopea exports a PNG with a palette of 30 colors (all black, different transparency).

But if your transparency is binary, the palette is X colors with transparency 255 and 1 black color with transparency 0.

So I guess you want to work only with colors for now, and you are aware, that when you use 256 colors, but there exist a transparent pixel, palletted PNG is impossible (as it would require 257 items in a palette). Paletted PNG requires at most 256 unique cobinations of RGB+A.

**Comment by FlarosOverfield** [comment]
![image](https://user-images.githubusercontent.com/24918282/234863458-19346502-ba06-4b79-850d-71c227aefccd.png)
As explained above, Indexed PNG's do not have an alpha channel. This is why this picture will still display as RGB instead of indexed as photoshop, even when using 5% quality in Photopea.
![image](https://user-images.githubusercontent.com/24918282/234863666-ce249a95-e723-4ff2-ac42-b0f41768c13f.png)
![image](https://user-images.githubusercontent.com/24918282/234863777-9832fd3b-ae11-488e-bcee-dea6812f549f.png)
Alpha works a bit differently in indexed PNG's with a palette. **Instead of using an Alpha channel, one of the 256 colors becomes the Alpha, in this case, the last one, `#ffffff`.**
![image](https://user-images.githubusercontent.com/24918282/234864786-edb09924-66d6-4fc8-80d8-a61955a5ed02.png)
![image](https://user-images.githubusercontent.com/24918282/234864432-2dbf7ec0-fbb2-44ad-9ce5-4c78c21a4aa5.png)
Let me know if you need me to insert all this info in a new issue.

**Comment by photopea** [comment]
You are wrong, indexed PNGs can have an additional alpha value for each palette color: https://www.w3.org/TR/2003/REC-PNG-20031110/#11tRNS

Here is an indexed PNG with variable transparency.
![New Project](https://user-images.githubusercontent.com/15955558/234882003-7cd02900-264a-477d-8c44-c0a9dbde471d.png)

**Comment by FlarosOverfield** [comment]
![image](https://user-images.githubusercontent.com/24918282/234891784-cc30801e-e578-4227-9c8e-7e65d113c52b.png)
![image](https://user-images.githubusercontent.com/24918282/234892041-fd526963-d406-4448-b756-4f2cb34c1717.png)
Weird... the only program that seems to recognize this as an indexed PNG is gimp, and while the image imports correctly, the palette doesn't have any alpha values.

**Comment by FlarosOverfield** [comment]
![image](https://user-images.githubusercontent.com/24918282/234895803-ba5b2681-461d-4d87-9435-f37fe2b11065.png)
huh

**Comment by y4my4my4m** [comment]
Would love that feature implemented as well for pixel art and more (I'm making ANSI art).

**Comment by kuzyn1** [comment]
The Color Table would be awesome...
There are situations when you want to check what colours are present on the image, especially with large images where its hard to check if there are some leftovers anywhere.

**Comment by camoody1** [comment]
> The Color Table would be awesome... There are situations when you want to check what colours are present on the image, especially with large images where its hard to check if there are some leftovers anywhere.

Go More -> Plugins and search for a plugin named "Adaptive Palette". I think this will give you what you want. 😊
