### ISSUE TITLE
Feature Request: 3D Rendering via WebGL

### ISSUE THREAD

**Issue by calclover2514** [photopea/photopea#1648]
I'm not sure if this is possible or feasible, but I thought that since WebGL is mostly a 3D web engine, it would be amazing if you could implement at least some of the features in Photoshop's 3D menu (e.g. 3D text, shapes, conversions).

**Comment by photopea** [comment]
Hi, I looked at what 3D does in Photoshop, and it is quite neat :D

I created this web-based photorealistic renderer six years ago: http://3dtool.ivank.net/

The hardest part would be adding the necessary UI. There are like millions of panels, buttons, options.

I wonder how many people actually uses such feature in Photoshop.

**Comment by MichalSZZ** [comment]
@photopea I have used Photoshop renderer few times. Results are good but the UI is hard for novice.
For simple things (3D elements from text or shapes) I like to use Illustrator and his easy creator https://helpx.adobe.com/pl/illustrator/using/creating-3d-objects.html
Results are not photorealistic but in flat isometric graphics or 3D texts looks quite good.

**Comment by photopea** [comment]
I am afraid this feature would be quite complex and there is not enough people interested in it :( So I will close it for now. Maybe in the future, once Photopea has more users, it will be worth doing it.
