### ISSUE TITLE
Add a square brush to default brushes.

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#1649]

**Comment by photopea** [comment]
added!

**Comment by wgordon17** [comment]
Where? How? I don't have any square options

<img width="274" alt="image" src="https://user-images.githubusercontent.com/22222756/162632813-6341ac3f-4833-4e3f-b745-3eb909a6a8d3.png">

**Comment by photopea** [comment]
The one with a number "20" is a square brush. But it is a tiny square in the preview.
