### ISSUE TITLE
Maybe simplify the texts areas?

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#165]
Is just a minor detail.
Every time I would like to change a name of a layer, paste a URL to open a file, resize a brush, opacity, hardness (you get the point) not by dragging the sliders (because I know the exact number or name i want), the text should be completly selected, so you can immediatly change it, and not having to select it before hand.
If in some case you would like to change a single character, if it is completly selected before hand, THEN you can click on the certain spot of the string to change it. But most of the time you would like to change the entire text or digit.

Here are the issues I face when changing the name of the layers:
https://drive.google.com/file/d/0BxACIQ9JCuosM3ljLWNjNE1ZV0k/view

Here issues changing the Open URL:
https://drive.google.com/file/d/0BxACIQ9JCuosUXJKWmJUNUNxVm8/view

Here maybe the "px" and  "%" should be outside the text area? (just an idea):
https://drive.google.com/file/d/0BxACIQ9JCuosOE1LNlJFa3pLcDQ/view

**Comment by photopea** [comment]
Ok, I did it. When you doubleclick the layer name, the whole name will be selected. Also, you can select specific parts of the layer name with mouse (previously, it started to drag the layer. Sorry for not fixing it eariler).

When you open the Open From URL window, the original URL will be selected.  I decided to keep Numeric inputs as they are. "px" or a percent inside the text is ok. BTW. when you doubleclick some text, it selects the whole word in most of browsers.

**Comment by avagp** [comment]
Great!

I know if you double click you select the whole text, but is now much
faster, and flawless.

:D

PP keeps improving!
