### ISSUE TITLE
Paint bucket spreads color

### ISSUE THREAD

**Issue by Laurennial** [photopea/photopea#1651]
I don't know if I'm missing a setting or something, but every time I use the paint bucket, it spreads a lighter version of the color onto the outside of the color I'm trying to fill, like it's trying to make a gradient. I'm just trying to fill one single color (as in, identical hex code) with another single color. 

Thanks!

**Comment by photopea** [comment]
That depends on the value of Tolerance (in the top menu). When it is not zero, the tool will tolerate small differences in color, and consider those to be the same color (and will fill them).
