### ISSUE TITLE
Cut/Copy/Copy Merged/Paste Not Working

### ISSUE THREAD

**Issue by donaldgraphic** [photopea/photopea#1652]
I have constantly tried time after time to cut a layer & paste it onto another one, and it never pastes. This is a fairly new issue I have been having & it kinds of upsets me because before this I've never had a bug/issue that hasn't been resolved already!

**Comment by photopea** [comment]
Hi, I believe we solved in the past: https://github.com/photopea/photopea/issues/1622

At some point, Photopea asked you for the permission to access the clipboard, and you refused it. You should chceck the settings again and allow it (see the end of the issue that I mentioned).

**Comment by donaldgraphic** [comment]
Oh ok, I understand now !

**Comment by photopea** [comment]
In the past, the permission was not necessary, because you could only copy and paste within Photopea.

But now, with a permission, you can copy in Photopea and paste elsewhere (e.g. in Photoshop, Gimp, etc.).

**Comment by donaldgraphic** [comment]
Ok, thanks so much ! But, I would like to say I use this app for everything
... you guys did so well !

**Comment by photopea** [comment]
thanks :)
