### ISSUE TITLE
"paste" not working

### ISSUE THREAD

**Issue by bozenka123** [photopea/photopea#1656]
Hi,
I am having problems with the paste function - it does not work neither while using Ctrl C - Ctrl V nor with choosing "copy" and "paste" in the menu. 
Can you help me please?

**Comment by photopea** [comment]
Hi, I believe we solved in the past: https://github.com/photopea/photopea/issues/1622

At some point, Photopea asked you for the permission to access the clipboard, and you denied it. You should chceck the settings again and allow it (see the end of the issue that I mentioned).

**Comment by bozenka123** [comment]
got it, great, many thanks!
