### ISSUE TITLE
Buttons on small screen

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1657]
D and switch colors buttons are displayed over content from right panel on small screen/mobile as you can see on this screenshot
![Screenshot_20190904-220104_Chrome](https://user-images.githubusercontent.com/6370548/64287588-6207d000-cf60-11e9-9839-b1b820fb59e6.jpg)

**Comment by photopea** [comment]
I knew about it, but I was too lazy to fix it :(

Now I did! Thanks! :)
