### ISSUE TITLE
Custom Shape loading

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1658]
When is dropdown with custom shapes opened first time it loads default set of shapes. But I once defined new shape with Menu-Define New-Custom Shape before I opened that dropdown and it did not load default shapes and only triangle and my new defined shaped appeared.
![image](https://user-images.githubusercontent.com/6370548/64316760-0ff19980-cfb6-11e9-88e8-0813adfd923b.png)

**Comment by photopea** [comment]
fixed, thanks!
