### ISSUE TITLE
Clone Tool not working properly 

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#166]
As i recall from using Photoshop, the Clone tool move relative to the cursor taking on account the origin of the anchor. So it moves accordingly when you click. 

But in PP when you move your cursor after setting the anchor, but before clicking, the anchor moves relative to your cursor! 

So, let's say i want to copy a rock of a landscape to another place in the picture, I set the anchor on the center of that rock then I move my cursor to the new point and use the tool. But the cursor begins to move as soon as i set the anchor, so when I actually use the Clone tool, I cannot clone the rock.

**Comment by photopea** [comment]
So I have found, that Photoshop has the checkbox "Aligned". When it is on, it behaves like Photopea right now. When it is off, it behaves as you describe :)  So I will put the same checkbox into Photopea.

**Comment by photopea** [comment]
I have added this "Aligned" checkbox, which is off by default, so it will work as you described.

The Healing Brush works the same way.
