### ISSUE TITLE
Cursor Not Aligning With Pixel

### ISSUE THREAD

**Issue by Laurennial** [photopea/photopea#1660]
This doesn't happen all the time, but often enough that it's really frustrating and I'm afraid my Ctrl and Z keys are going to wear out. 

Basically, when I click in one pixel, the color will be placed in a pixel next to it instead, often to the left but it's ended up in other ones too. I do pixel work, so this is blatantly obvious and really frustrating. It wasn't doing this when I began using it regularly about a week ago. Reloading the page used to help until yesterday. 

Thanks for the amazing site though! I get a lot out of it.

**Comment by photopea** [comment]
Hi, what tool are you talking about? Is it about a Brush tool? Have you zoomed in a lot?

**Comment by calclover2514** [comment]
The pencil tool does this for me when I use it very zoomed in.

**Comment by hxim** [comment]
I remember it happened to me too.
For example as you can see in this screenshot when I click it paints wrong pixel placed one to the right:
![image](https://user-images.githubusercontent.com/6370548/64405343-54d90700-d06e-11e9-910e-25f101e9723f.png)

**Comment by photopea** [comment]
Guys, you are right, and it was really awful.

I just fixed it. I wonder that nobody reported it earlier :/
