### ISSUE TITLE
Feature Request: Arrow Key Support for Color Picker

### ISSUE THREAD

**Issue by Laurennial** [photopea/photopea#1661]
I would enjoy being able to use the arrow keys in the color picker instead of having to click and drag to change colors. It would be super helpful for making better color gradients. Thanks!

**Comment by photopea** [comment]
Colors consist of three values (R,G,B, or Hue/Saturation/Brightness), while arrow keys can move only in two directions :(  

You can click into any specific value (e.g. Saturation) and use arrow up / down to change it.
