### ISSUE TITLE
Clone Tool cursor

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1662]
When I used Clone Tool in some zoom level preview cursor was broken and was not circle but some broken ellipse as seen on screenshot.
Also when I have selected Source for Clone Tool as Current Layer it shows as preview/cursor pixels from all layers which is very confusing because then it applies pixels from current layer (different from preview).

![image](https://user-images.githubusercontent.com/6370548/64377370-8cbe5b00-d02a-11e9-948f-17b95e77791e.png)

**Comment by photopea** [comment]
Hi, I fixed both problems.
