### ISSUE TITLE
Move History Tab to Small Dock

### ISSUE THREAD

**Issue by calclover2514** [photopea/photopea#1663]
Photopea would be easier to use on tablet/phone and even Chromebook screens if the history panel were moved to the small dock so that you could see the layers panel.
Before:
![Before](https://user-images.githubusercontent.com/43104632/64379791-aa290000-cffd-11e9-92a6-9a4f2aeaad83.png)

After:
![After](https://user-images.githubusercontent.com/43104632/64379803-b0b77780-cffd-11e9-8899-21cbd9d346bc.png)

And yes, I did modify these images with Photopea 😛

**Comment by photopea** [comment]
Adding so much flexibility to panels would be quite hard to implement :(

You can right-click the History label and choose Close, to hide it permanently (then, Layers will be stretched to the top).

**Comment by calclover2514** [comment]
I was simply saying to make it open that way instead of opening above the Layers panel.
