### ISSUE TITLE
Feature Request: Allow Setting Bend of Path Point After Creation

### ISSUE THREAD

**Issue by calclover2514** [photopea/photopea#1664]
Right now, with the pen tool, if I just click, it creates a point that is unable to be curved or bent with control points. Every time I want to add a curve, I have to click and drag. This doesn't work if I want to edit pre-defined shapes, and gets really annoying sometimes. Also, why does the bend sometimes only affect one side of the point?

**Comment by photopea** [comment]
Hi, you can edit an existing path with a Direct Select tool (switch by pressing A).  https://www.photopea.com/learn/vg-manipulation

**Comment by calclover2514** [comment]
Sorry. I somehow managed to miss that.

**Comment by photopea** [comment]
But everything can be drawn with a pen tool on a first try. There is a game, where you can learn how to use it: https://bezier.method.ac/
