### ISSUE TITLE
Is it possibillity to use tabulator when typing with text tool?

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1666]
Now it doesn't work like in PS or Word or any software to coding (should make bigger space - now it's jumping to other section on site). 
I think that can be a browser limitation, but want only to ask :)

**Comment by photopea** [comment]
So I made a simple implementation of Tabulators.

It creates a space of a fixed width. I.e. it does not "jump" to fixed positions in different lines, as it usually does in other editors.
