### ISSUE TITLE
Creates random static file for no reason

### ISSUE THREAD

**Issue by calclover2514** [photopea/photopea#1668]
Photopea keeps randomly creating a new file named `AE3Au5_g7yGHHYNkjvRaEqVIIr6fQPuMAhmnoMwiDt0rOATa2Q.psd` that looks like this:
![AE3Au5_g7yGHHYNkjvRaEqVIIr6fQPuMAhmnoMwiDt0rOATa2Q](https://user-images.githubusercontent.com/43104632/64481773-64ad3400-d1b1-11e9-8116-e11f69dd8353.png)
for no reason at all and I can't seem to figure out why it's doing it.

**Comment by photopea** [comment]
Hi, nobody reported such problem before. When does it happen? When you open Photopea?

Try to restart your computer. Maybe there is this image in your clipboard and some virus keeps pasting it into every program you use.

**Comment by calclover2514** [comment]
This happened to me twice one day and only when I was copy/pasting layers between files.
It hasn't happened since.

P.S. I know it's not a virus, as I'm using a school-monitored chromebook.

**Comment by photopea** [comment]
Such behaviour was common in an old version of Photopea (a month ago), but it should not happen now.

**Comment by calclover2514** [comment]
OK
