### ISSUE TITLE
Searching functions by keywords

### ISSUE THREAD

**Issue by JinHengyu** [photopea/photopea#1671]
A search input can be very useful, sometimes when we forget the position of a button, but remember the name of the function(like rotate) , we can search for it. Could u plz made one ?

**Comment by photopea** [comment]
How exactly would you like it to work? In Photoshop, you can press Ctrl+F and a special window opens, where you can type the name of what you are looking for.

I don't know if many people would discover this feature (Ctrl+F). Currently, you can put "photopea something..." into Google and you should find an answer.

**Comment by photopea** [comment]
Hi, it has been implemented, see here: https://github.com/photopea/photopea/issues/1727
