### ISSUE TITLE
Action Set not working in Photopea

### ISSUE THREAD

**Issue by IgneoWarrior** [photopea/photopea#1673]
Attachment: [SeamlessTextures_2_Actions_Set.zip](https://github.com/photopea/photopea/files/3593294/SeamlessTextures_2_Actions_Set.zip)

The attached SeamlessTexture Action Set is for CS3+ and is courtesy of [The Orange Box](https://www.the-orange-box.com/portfolio_page/free-seamless-texture/). After going to File > Open > .ATN, only some of the actions seem to run and the the result is not a seamless texture.

Note: I do not have Photoshop, so the action set might actually be broken and not work in Photoshop too, but I thought I'd submit an issue request anyways.

P.S. Thanks for Photopea, am coming from Paint.net and am really loving all of Photopea's automation features.

**Comment by photopea** [comment]
Hi, I implemented the missing features. All actions in your Action Set should work well in Photopea now.
