### ISSUE TITLE
app.doAction("X","Y") doesn't execute the whole action?

### ISSUE THREAD

**Issue by RookVanguard** [photopea/photopea#1674]
`app.doAction("Action Set 0", "Action 0");`

Hello, I am trying to run an action set from the above script. When I run this script, it seems to only execute one step. It does not proceed to execute the second step of the action set.

Attached is a .zip containing a .psd & .atn to help replicate this issue:

[PhotoP.zip](https://github.com/photopea/photopea/files/3594223/PhotoP.zip)

*Also, I've tried and have had the same or similar issues in Chrome, Firefox, and the Chrome App. I was also looking at the [Photoshop CS6 JS Reference manual](https://www.adobe.com/content/dam/acom/en/devnet/photoshop/scripting/Photoshop-CS6-JavaScript-Ref.pdf) and noticed that _actionset_ and _action_ seem to be reversed?

Page 47:

> _doAction(action, from)_
Plays an action from the Actions palette. The _action_ parameter is the name of the action, the _from_ parameter is the name of the action set.

Also, thanks for this wonderful piece of software, keep up the good work and _happy photopeaing!_

**Comment by photopea** [comment]
I fixed it :) and you are right, the first parameter is the action name, the second one is the action set name.
