### ISSUE TITLE
Select > Inverse not working

### ISSUE THREAD

**Issue by Lunacamanda** [photopea/photopea#1676]
The Select inverse option is unable to be clicked either from the Select menu, from right clicking and then choosing Select inverse, or by using the ctrl shift I command. The menu just stays open and nothing happens when clicking that option. Started today, I use this regularly and it was working yesterday. 
I'm using windows 10 and chrome, and I've tried restarting my browser first and then computer with no change.
Thanks!

**Comment by photopea** [comment]
Hi, I am very sorry :( it is fixed now.

**Comment by Lunacamanda** [comment]
Wow, that was so fast!! Thank you!
