### ISSUE TITLE
Live Messaging event duplicated once per plugin  trigger

### ISSUE THREAD

**Issue by dbnuxeo** [photopea/photopea#1677]
## Setup:
 
1. Define a plugin within the environment (the default Wikipedia example will be sufficient)
2. Add a Live Messaging API callback listener

## Problem

Message Events are re-sent once per click.  The first click on the plugin will send 1 message with `{request: "postUri", uri: ...}` as expected.  The second click will send 2 identical messages, the 3rd click 3 messages, and so on.

**Comment by photopea** [comment]
Hi, i am afraid I don't understand. 

2. Add a Live Messaging API callback listener  - did you add a listener to Photopea.com or to Wikipedia? I ama fraid you could not do any

"click on the plugin" - what do you mean by that? Do you mean the area of the iframe of the plugin?

**Comment by dbnuxeo** [comment]
I am using Photopea with an outer environment (OE), so I am adding a Live Messaging listener to www.photopea.com to receive events.  When I add a plugin, such as Wikipedia, it appears in the plugins list under "Inf", "Pro", "CSS".  When I click on the Wikipedia plugin and the page loads, the OE receives a Live Message API event containing the object `{request: ..., uri...}` in the data field.  The second time I click on the Wikipedia plugin, the OE receives 2 events, and so on.  The OE should only receive one event per load from the Wikipedia plugin.

**Comment by photopea** [comment]
What do you mean by "adding messaging listener to www.photopea.com" ? I think a message listener can be added only to the main window - a global variable "window".

I tried to run the Wikipedia plugin in our Playground. It shows all messages at the bottom. I do not see any messages after opening and closing Wikipedia plugin.

https://www.photopea.com/api/playground

**Comment by dbnuxeo** [comment]
This is curious - I am able to reproduce in Google Chrome (76.0.3809.132 and 77.0.3865.75) on https://www.photopea.com/api/playground - I see the duplicated message events in the web console, but I do *not* see them in the "Messages from Photopea".  The origin of these events in Chrome is "https://www.photopea.com", example here:
```
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: Window {postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, parent: Window, …}
data: {request: "postUri", uri: "https://en.wikipedia.org/wiki/Main_Page"}
defaultPrevented: false
eventPhase: 0
isTrusted: true
lastEventId: ""
origin: "https://www.photopea.com"
path: [Window]
ports: []
returnValue: true
source: Window {postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, parent: Window, …}
srcElement: Window {postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, parent: Window, …}
target: Window {postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, parent: Window, …}
timeStamp: 256688.80000000354
type: "message"
userActivation: null
__proto__: MessageEvent
```

I am unable to reproduce with the latest versions of Firefox, Safari, or Opera.
- I see no messages in the console for Firefox or Safari
- I see 1 message per load in Opera

Appears to be a Chrome specific behavior.  Sorry for the noise.

**Comment by photopea** [comment]
I see the same behaviour in both latest Chrome and Firefox.

The playground prints only the messages with an origin of "photopea.com" under the iframe (while it prints all messages in the console).

Do you have any Chrome extensions? Try to disable them.
