### ISSUE TITLE
Gradient of opacity does not work properly for stroke of the shape

### ISSUE THREAD

**Issue by s5706820** [photopea/photopea#1678]
as i set opacity to 0 as in the pic.
the corner of the stroke suppose to be transparent, but it is not.

![image](https://user-images.githubusercontent.com/15662227/64777984-5c744080-d585-11e9-97c8-04e3e1da84f1.png)

**Comment by photopea** [comment]
Adobe Photoshop is currently the most popular PSD editor.

When you have a Gradient Stroke around a shape in Photoshop, and the gradient contains transparency, the transparency is ignored.

We would probably have to discuss it with Adobe, to agree on the new rendering mechanism. But until then, I think it is better to keep PSDs looking the same as in Adobe Photoshop.

**Comment by s5706820** [comment]
Oh i see, it has been a long time since i last use PS. So i dont know how thing work there.
And i agree to keep it the same way as in PS.
Thank you
