### ISSUE TITLE
Error when opening saved PSD in various versions of photoshop

### ISSUE THREAD

**Issue by i18n-1974** [photopea/photopea#168]
Hi,

I can upload my PSD and edit online but when saving it as PSD again from photopea and opening in various versions of photoshop, I get an error:

 "Could not complete your request because the file is not compatible with this version of Photoshop"

This happens with the following versions of photoshop:

CS6
CC v14.2.1
CC 2014
CC 2015

This error occurs with the CC 2015.5:

"Could not complete your request because of a program error"

Can you please let me know which version it does work with?

Cheers,
Warren

**Comment by photopea** [comment]
Hi,
I think it may be related to this issue: https://github.com/photopea/photopea/issues/128 .

Can you try to open your PSD and then save it back (without editing). Does it work? Can you send us your file to support@photopea.com (or attach it here) ?

**Comment by photopea** [comment]
I have to close it because of the lack of details :(

**Comment by basovdesign** [comment]
I have the same mistake. How to solve it?

**Comment by photopea** [comment]
Hi, can you send us your original PSD file to support@photopea.com ?

**Comment by basovdesign** [comment]
I sent


On November 10, 2017 at 12:48:55 PM, Photopea (notifications@github.com) wrote:

Hi, can you send us your original PSD file to support@photopea.com ?

**Comment by photopea** [comment]
Hi, we haven't received your email :(

**Comment by Ennllel** [comment]
Hi!

Same error "Could not complete your request because the file is not compatible with this version of Photoshop" in CC 2017

"Can you try to open your PSD and then save it back (without editing). Does it work?"
-I tried and it doesn't work.

Can you send us your file to support@photopea.com (or attach it here) ?
-Attached here 👍 

[News-Channel.psd.zip](https://github.com/photopea/photopea/files/1480066/News-Channel.psd.zip)

**Comment by photopea** [comment]
Hi, I downloaded your PSD file "News-Channel.psd".

1) I tried to open it in PS CS6 and it works.
2) I opened it in Photopea and saved as PSD, the new PSD also works in PS (CS6 on Windows).

What exactly is the problem?

**Comment by Ennllel** [comment]
Ok I use PS CC 2017 for Mac, 

I've done further testing and I think the smart object layers may be causing the issue:

I save this PSD which contains a Smart Object Layer:
<img width="1440" alt="fullscreen_18_11_2017__09_56" src="https://user-images.githubusercontent.com/7062453/32978745-924109a2-cc48-11e7-9feb-629adbd032a9.png">

Open in Photopea and Save as PSD.
<img width="1439" alt="photopea___edit_photoshop_files_online" src="https://user-images.githubusercontent.com/7062453/32978756-d9392d9e-cc48-11e7-9be5-91bd6a04a310.png">

When I try to open it Photoshop cc 2017 I get: 
<img width="1440" alt="fullscreen_18_11_2017__10_02" src="https://user-images.githubusercontent.com/7062453/32978762-02621f14-cc49-11e7-9542-9dc8efc3cb9e.png">

If I rasterize the Smart Object layer before downloading as PSD everything is OK though :)
<img width="1440" alt="fullscreen_18_11_2017__10_04" src="https://user-images.githubusercontent.com/7062453/32978827-00d8020c-cc4a-11e7-9246-72fe92e533e6.png">

**Comment by photopea** [comment]
Thanks a lot for so many details! I also noticed, that your smart Object has Smart filters. Can you delete them (right click on Smart filters - Clear smart filters) while keeping the smart object, and try, if the new PSD works in Photoshop?

**Comment by photopea** [comment]
So even PSDs without smart filters get "corrupted" by Photopea?

**Comment by Ennllel** [comment]
That's right, at least with CC2017...

-PSD **with smart object created in Photoshop**, uploaded to Photopea and saved back: Gets corrupted.
-No smart objects: No problem.
-PSD with Smart object created  in Photopea: No problem.

Here's another "corrupted" PSD
[Adventure-Thumbnail_3.psd.zip](https://github.com/photopea/photopea/files/1500093/Adventure-Thumbnail_3.psd.zip)

Let me know if you want me to do some more testings :)

**Comment by photopea** [comment]
Thank you very much!

Could you please make some smaller PSD file (as small as possible), that still gets corrupted? I would have to take a look at actual bytes.

**Comment by Ennllel** [comment]
Sure!
Here's 2 files (10px & 1px) 2 versions each (original PSD from PS-CC2017 & corrupted PSD saved from PP).
Hope it helps!

[PP-Tests.zip](https://github.com/photopea/photopea/files/1513174/PP-Tests.zip)

**Comment by photopea** [comment]
Hi, I believe I have fixed it now. All output PSDs should work well with Photosohp CC.

**Comment by IamSohaggazi** [comment]
hi, i have same problem can u fix?

**Comment by photopea** [comment]
@IamSohaggazi Hi, can you tell us, how did you create such corrupted PSD? 

All PSD from Photopea, that we tried so far, work well in Adobe Photoshop.
