### ISSUE TITLE
Feature Request: Record Export Action

### ISSUE THREAD

**Issue by RookVanguard** [photopea/photopea#1682]
Hello again! I'm now attempting to automate exporting as .png (_since I plan on processing images in bulk._) Thus, I'm requesting an Export As recordable action.

*Also, if you have time, how would one script exporting the document as a .png? (I tried and failed miserably, and could only get it to export .png files through .zip)

Thanks for photopea! :)

**Comment by photopea** [comment]
Today, websites can not write files into your computer, without showing a Save As dialog, and without you confirming it with OK (some browsers save automatically to a Download folder, depending on browser settings).

Photopea supports scripting, whenever a script calls Document.exportDocument(), Photopea puts all such documents into a ZIP, which is offered for download after the script finishes.

Here is a tutorial about it: https://fishtrone.wordpress.com/2019/02/25/generating-images-from-code-with-photopea/
