### ISSUE TITLE
Images Wont Save

### ISSUE THREAD

**Issue by Cybermouse63** [photopea/photopea#1684]
Photopea is not saving my images. The platform has suddenly stopped saving image despite advising that it is currently saving but nothing else happens. Its connected to my Dropified platform. Any advise please?
![image](https://user-images.githubusercontent.com/55302739/64901218-344a2600-d6da-11e9-9282-f71099aa23f9.png)

**Comment by photopea** [comment]
Hi. Saving files from Photopea to the server works elsewhere. I just reported this issue to Dropified. Hope they will fix it soon.

Until then, save your image from Dropified to your computer, open it in www.Photopea.com, save it back to your computer and upload to Dropified manually (if it is possible. I never used Dropified).
