### ISSUE TITLE
Zoom to "100%"

### ISSUE THREAD

**Issue by extremepayne** [photopea/photopea#1687]
Zoom in photoshop provides the option to make one pixel of the photo equal to one pixel on the monitor. This can be done by double-clicking the zoom tool or right-clicking with the zoom tool and selecting "100%". This option gives you a sense of the size of your image at your current screen resolution and allows you to view exactly what the finished photo will look like.

**Comment by extremepayne** [comment]
Oh, just realized that "pixel to pixel" in the top bar does this. Maybe make the feature more discoverable?

**Comment by photopea** [comment]
Hi, I think double-clicking for 100% would be quite misleading. Somebody may want to zoom in quickly twice, and it would put him back to 100%.

There is a context menu after the right click. I changed the name from "Pixel to Pixel" to "Pixel to Pixel: 100%".

**Comment by extremepayne** [comment]
No, double-clicking the zoom tool itself!
"Double-click the Zoom tool in the toolbox."
https://helpx.adobe.com/photoshop/using/viewing-images.html#display_images_at_100

**Comment by photopea** [comment]
Why didn't you say it right away? :D  I just implemented it!
