### ISSUE TITLE
When coping a layer from psd file to another layer does not show correctly.

### ISSUE THREAD

**Issue by stimpyaw** [photopea/photopea#1688]
Today and last week Photopea has been working without a problem but everyone in a while when I copy a layer from one PSD tab to another tab the layer copied is showing in the correct position but not displaying correctly. I have had this issue on just about every layer I copy between to different tabs. please see screenshot.
![Photopea-layer issue_9-16-2019](https://user-images.githubusercontent.com/55409394/64984924-a5274480-d878-11e9-8421-392919b5ad23.jpg)

**Comment by photopea** [comment]
Hi, I am not able to reproduce it :/

What browser are you using? Can you try to update it? Can you try a different one? Can you try to disable extensions?

**Comment by hxim** [comment]
@stimpyaw Looking at screenshot you may have some "unwanted" blending options on that layer can you check Right click on layer - Blending options

**Comment by stimpyaw** [comment]
The current version of Chrome I have is:

• Version 76.0.3809.132 (Official Build) (64-bit)

I checked Chrome again and it updated to:

• Version 77.0.3865.75 (Official Build) (64-bit)

I will try Safari and Firefox and will have to get back to you. I will also try to disable my extensions one by one to see what happens.

~ Anthony
stimpyaw@gmail.com

**Comment by stimpyaw** [comment]
I checked that before posting and in the screenshot provide there is no blending options turned on for any of the layers.

~ Anthony
stimpyaw@gmail.com

**Comment by photopea** [comment]
So can you open two JPGs in Photopea, switch to the first one and do Select - All, Edit - Copy. Then, go to a second one and press Edit - Paste. Does it work as expected?

**Comment by stimpyaw** [comment]
Sorry If I didn’t clearly state how I copied layers between tabs. I selected the layers I wanted and then dragged them to the tab I wanted.

~ Anthony
stimpyaw@gmail.com

**Comment by photopea** [comment]
Can you do the same for two simple JPGs? Just drag the layer to the tab of another document.

Or send us your PSDs (to support@photopea.com ) and tell us, which layers are you copying, so that we can try it ourselves.

**Comment by photopea** [comment]
This bug happened with Rulers enabled. Sometimes, after the layer is copied, the Move tool drags a new guide from the ruler, instead of dragging a copied layer (so the copied layer remained out of the view).

I fixed it.

**Comment by stimpyaw** [comment]
I apologize for not notifying you of that, but yes I had used rulers in most of the psd files that I opened in Photopea. I didn’t think the two where related to each other.

Thank you for a great piece of software!

~ Anthony
stimpyaw@gmail.com
