### ISSUE TITLE
Could you please support Ctrl+MouseScroll to zoom in and zoom out.

### ISSUE THREAD

**Issue by chanuei** [photopea/photopea#1689]
# Could you please support Ctrl+MouseScroll to zoom in and zoom out.

Dear,

zoom in and out is a very important feature.

Please think about it

**Comment by balQu** [comment]
You already can zoom in and out with Alt + MouseScroll.

**Comment by photopea** [comment]
Photopea works differently. 
Mouse wheel scrolls the document vertically. 
Ctrl + wheel scrolls the document horizontally.
Alt + wheel zooms in and out.
