### ISSUE TITLE
Chrome not opening PSD's at all w/ console error

### ISSUE THREAD

**Issue by alexcavender** [photopea/photopea#169]
Uncaught TypeError: Cannot read property 'v' of undefined
    at Function.na.ZB (pp.js:1050)
    at na.yK (pp.js:1049)
    at na.aD (pp.js:1048)
    at na.update (pp.js:1047)
    at Xa.Ha.update (pp.js:1146)
    at la.update (pp.js:1169)
    at la.XP (pp.js:1169)

**Comment by alexcavender** [comment]
also not working in Firefox Developer Edition on Mac OS X 10.11.6

**Comment by photopea** [comment]
Hello, opening (or not opening) PSD files does not depend on the browser or the operating system.

Can you please attach your PSD file? You can also send it to support@photopea.com

**Comment by alexcavender** [comment]
Yes, I included that just to help with some specifics of my situation and how to replicate. I sent a copy of the PSD to your Support email. Thanks!

**Comment by photopea** [comment]
I am sorry, I still haven't received it. How large is the file? can you send it maybe to ivan.kuckir@gmail.com ?

**Comment by alexcavender** [comment]
I'll try sending it via Google Drive, its quite large (~50mb)

**Comment by photopea** [comment]
ok, I am looking forward to it :)

**Comment by photopea** [comment]
are you here? Can you show me your PSD file?

**Comment by photopea** [comment]
I had some problems with mymailbox. Can you send it again to support@photopea.com ?

**Comment by alexcavender** [comment]
Sending again, thanks!

**Comment by photopea** [comment]
The problem was artboard-related. It seems, that some PSDs don't have the background color defined, that was the problem. I fixed it.  BTW. your PSD was made by the new Photoshop, many properties are still not available to edit in Photopea. We will work on it, too.

**Comment by alexcavender** [comment]
Thank you!
