### ISSUE TITLE
Sampling black, gray and whites in Levels and Curves on Adjustments Layers

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1690]
#1642 that feature works great only when using menu -> Image -> Adjustments

I tryied it right now with Adjustments Layers and there, that doesn't work for me.
When I click on image to set point of white it close the Adjustments panel, switch to that layer and doesn't do enything.

**Comment by photopea** [comment]
Are you sure? Can you reload Photopea? Can you try it on a single-layer JPG?

**Comment by MichalSZZ** [comment]
Yes.
I just tested twice on Mac and PC. Chrome and Firefox.
Single layer JPG too.

**Comment by photopea** [comment]
Oh, you are right, this does not work with adjustment layers, only with Image - Adjustments.

I will think if there is an easy way to fix it.

**Comment by photopea** [comment]
Currently, when you work with a mouse, only a tool can process it (a tool from a toolbar), or a window, which is opened. We would have to remake our whole mechanism, to allow panels handle mouse events. So I would rather omit this feature for now.

**Comment by avagp** [comment]
I really need this to work.

Thanks for pointing out that on Image>Adjustments it works.

I was about to submit a bug for not working.

Besides, it will be more intuitive to have a eyedropper icon on the samples, rather than squares.
