### ISSUE TITLE
Autoupdate (redraw) histogram in Levels after automatic set of whites, greys and black point

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1691]
It should work in that way as in the title.
When user set new point of white by sampling from photo, it should redraw and update histogram in Levels palete. Same for other points. That's how Photoshop do that.

**Comment by photopea** [comment]
Here is what happens in Photoshop: when you change levels for Red, Green or Blue, the histogram for RGB is updated (but histograms for Red, Green and Blue never change during editing).

Setting White / Grey / Black point only updates the levels for Red, Green and Blue.

**Comment by photopea** [comment]
Ok so I made it work this way.
