### ISSUE TITLE
Colour lookup Issue

### ISSUE THREAD

**Issue by doyoungg** [photopea/photopea#1694]
Hello! I was trying to use the colour lookup feature today but every time i click it everything in my layer's panel freezes as well as everything on the canvas. It appears to break everything, even if I try to go back it doesn't work and when I open a new project the same picture from the last canvas will show up instead. I'm not sure what's wrong.

**Comment by photopea** [comment]
Hi, did you load your own LUT into Photopea? What format is it? Can you send us your LUT to support@photopea.com ?

**Comment by doyoungg** [comment]
I didn't load anything in (as far as i'm aware?) nothing but fonts have ever been added into my photopea... if i'm understanding the question correctly at least

**Comment by photopea** [comment]
Oh, you probably tried the Color Lookup Adjustment Layer, right?. I see it does not work. I will look into it.

**Comment by doyoungg** [comment]
sorry, i should have been more specific ! yes i am using the adjustment layer, thank you for looking into it

**Comment by photopea** [comment]
Hi, I fixed the problem.  Now, when there is no Lookup Table (LUT) specified, it just covers the image with black, not causing any errors.

You can load your own LUTs into Photopea manually. I also added some free LUTs (open a dropdown with LUTs, press a tiny triangle in the right part, choose e.g. "Cubicle 99.CUBE" .
