### ISSUE TITLE
"Color picker" window - sampling from foreground and background miniatures in tollbar

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1695]
In Photoshop I can sample color in Color Picker window from foreground and background color in left tollbar. Photopea doesn't let me to do that.
This is my strong habit from Photoshop and today I saw that my friend tried to do that in same way in Photopea too.

**Comment by photopea** [comment]
What an interesting feature :D

I implemented it. When a Color Picker window is opened, you can "sample" from any color sample.

**Comment by MichalSZZ** [comment]
Thanks :) It may look as funny/stupid feature but...
Sometimes Color Picker is a part of other functionality and show up as a 3th window (e.g. layer styles -> gradient editor -> color picker) and there, you want to make gradient from your own Swatches :D

**Comment by photopea** [comment]
Actually, if the Color Picker is opened, and a foreground color is changed, the current color of a Color Picker is set to the foreground color.

So clicking on swatches or Color panel will change the color in Color Picker.
