### ISSUE TITLE
New Color Fill layer - start with foreground color

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1696]
Now it's start with red colour all the time and I must make one step more to set my own.
In PS it's fill with foreground color.

**Comment by photopea** [comment]
Hi, I made Photopea ask you about a color when making a Color Fill layer.

**Comment by MichalSZZ** [comment]
@photopea sorry for asking, but I had no time to check when you made fix for this issue. 
Is there everything OK? I don't see any "in-program question" about new color, when making new color fill layer...
And why it sould work differently like in Photoshop? In PS it set automaticaly new color fill from foreground color (with color picker).

**Comment by MichalSZZ** [comment]
@photopea I don't want to make a new issue, but I think that it doesn't work for me.
Maybe it wasn't Color Fill Layer created by New Adjustments Layer?

Photopea don't show Color Picker after creating New Fill Layer as you wrote above...
And in Photoshop it works like that:
1. User create a New Adjustments Layer (Color Fill...).
2. Color Picker window is showing
3. New color in that window is set from foreground color. User can quick click OK if it is OK, or change it.

**Comment by photopea** [comment]
Hi, there is no adjustment layer Color Fill in Photoshop or Photopea.

In Photoshop (or Photopea) you should press Layer - New Fill Layer - Color Fill.

**Comment by photopea** [comment]
You probably mean using the button at the bottom of the Layer panel. I made it work there, too.

**Comment by MichalSZZ** [comment]
Yes, you have 100% right! I mean that icon with contrast symbol on the botton of layers pallete.
Thank you! Works great!
