### ISSUE TITLE
Tools not shaped as circles resizing on their own in the midst of using them.

### ISSUE THREAD

**Issue by DaAquaholic** [photopea/photopea#1697]
In my project, I am taking an image and beginning to put a raster mask over the top of it to erase out said image's background. When I am doing this, I would normally place a raster mask over top of the image and paint with the brush tool over all I wish to disappear, but that has since changed and does not allow me to progress at all. Whenever I begin to do this, I zoom in very far to view individual pixels and I use the square brush head at the size 1px, but when this tool is used, it automatically switches from 1px to a range of numbers **with each click** to make things impossible for me. I wish to know if this can be fixed and when as I need this tool soon.

**Comment by photopea** [comment]
Hi, I am sooooo sorry :(  I made a mistake today.

It is fixed now.
