### ISSUE TITLE
Can't save gif

### ISSUE THREAD

**Issue by cscyjh0804** [photopea/photopea#1698]
So I tried to make GIF several time and couldn't save it anymore. It worked perfectly fine before I don't know why...

**Comment by photopea** [comment]
Hi, I just tried to open a GIF and save it back as GIF, and it works well.

What exactly do you mean by "couldn't save"? What exactly happens? Can you save the document as a PSD and send it to support@photopea.com ?

**Comment by photopea** [comment]
I have to close it because of lack of details.
