### ISSUE TITLE
doesn't let me save or export

### ISSUE THREAD

**Issue by kristinapa** [photopea/photopea#1699]
Hello.
I tried saving again and again and it saves into gibberish txt file.

**Comment by photopea** [comment]
Hi, did it work before? Can you update the browser or disable browser extensions?

Can you open the demo "pea.psd" and save it as PSD or PNG?

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by aidinjk** [comment]
Are you sure about that?
