### ISSUE TITLE
Dropbox

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#17]
Hi,

what about Dropbox storage connection?
My people working with dropbox very often.

**Comment by photopea** [comment]
Hi,
Dropbox requires all parties, that use their API, to use SSL connection. I will try to get SSL connection first.

**Comment by Studioartcz** [comment]
It´s good idea! HTTPS will be great.

**Comment by photopea** [comment]
Lets discuss it here now: https://github.com/photopea/photopea/issues/1136

**Comment by photopea** [comment]
After opening https://www.photopea.com/ , there are "storages" on the left side. Basically, it is a file explorer for different "storages", one of them is Dropbox. You must give Photopea permissions to access your Dropbox. What do you think about it? :)
