### ISSUE TITLE
Can't open Sketch 43.2 file - "unknown file format RK"

### ISSUE THREAD

**Issue by dorian-grey** [photopea/photopea#170]
File in question:

[photopea.sketch.zip](https://github.com/photopea/photopea/files/960989/photopea.sketch.zip)

**Comment by photopea** [comment]
That is very interesting. Sketch is using completely new "container" for their files.

This new .sketch file is just a ZIP file. If you change the .sketch extension to .zip, you can unzip it, you will get a bunch of folders, which contain JSON files and PNG images.

I will try to analyze it and make it work with Photopea.

**Comment by dorian-grey** [comment]
Sketch completely changed their file format with 42 -> 43 two or three weeks ago. They wanted it to be more open and accessible, so that it's easier for devs to interact with it. There should be a whole lot of documentation available ...

**Comment by photopea** [comment]
BTW. can you send me some more complex Sketch file (in this new format) for testing? :) thanks!

**Comment by photopea** [comment]
I have added the support for version 43 and higher. You can open your files now :) Let me know, if there are any other problems.
