### ISSUE TITLE
Cannot move handle independently with Direct Select tool.

### ISSUE THREAD

**Issue by Limbukushal** [photopea/photopea#1700]
I created a closed shape by using Pen tool, but while editing the anchor point using Direct Select tool (holding the Alt Key and dragging one of the handles ), I am unable to rotate the handle independently(one handle at a time). But if handles angle not equal to 180 degree then works fine.

**Comment by photopea** [comment]
Hi, you should double-click the middle point, to change it to change the "smooth knot" to "corner knot". See here: https://www.photopea.com/learn/vg-manipulation
