### ISSUE TITLE
Firefox: New project doesn't ask to use image from clipboard

### ISSUE THREAD

**Issue by Harrison-Mitchell** [photopea/photopea#1701]
It's a feature I wish existed everytime I opened PhotoPea, so to see it implemented the one time I used it in Chrome was bittersweet. Specifically the feature where it detects the clipboard image's dimensions and sets the new project's parameters accordingly.

Repro steps: Copy image, open photopea, select new project.

I've confirmed that I haven't explicitly blocked the clipboard permission for the site, nor have I ever been asked for it.

My UA: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0

Lovely program mate, love from Australia. :australia:

**Comment by photopea** [comment]
Hi, there is no way in Firefox to read the content of a clipboard, without the user pasting it first (with Ctrl+V).

Also, Chrome is really slow when reading large images from clipboard (30 megapixels and more), so we disabled it for Chrome, until they improve it.

https://bugs.chromium.org/p/chromium/issues/detail?id=1004867

**Comment by Harrison-Mitchell** [comment]
No chance then that we can paste the image on app start which creates a project to dimensions with the clipboard image? Firefox could have a string under the dimension fields "or paste it in directly" or similar.

**Comment by photopea** [comment]
Yes, after you open Photopea.com , you can paste the image from a clipboard (Ctrl+V) - it should work in all browsers.
