### ISSUE TITLE
Edit -> Copy does not copy to OS clipboard

### ISSUE THREAD

**Issue by vramdal** [photopea/photopea#1705]
Hi, not sure if this is supposed to work, or if its a bug: When I click Edit -> Copy (or Edit -> Copy merged) the image is not copied to my (local) clipboard, so that if I try to paste the copied image into another application, it's not available.

Reproduced on platforms:
- Chrome 76 on RHEL 
- Safari 12 on macOS 10.14

To reproduce:
1. In a text editor, or the browser's address bar, type som text, e.g. "foo bar"
2. Select the text and click Ctrl+C to copy it to the clipboard
3. In Photopea, open any image from your computer
4. Using the Rectangle Select tool, select an area of the image
5. Click Edit -> Copy Merged
6. Switch to another application e.g. Slack, and Command-V to paste

Expected result:
- The rectangle copied in step 5 is pasted into Slack

Actual result:
- The text copied in step 2 is pasted into Slack

**Comment by photopea** [comment]
Hi, we did use the system clipboard for several weeks, but then, we noticed, that copying large images into a system clipboard takes too much time in Chrome, so we returned to a local clipboard for Photopea.

https://bugs.chromium.org/p/chromium/issues/detail?id=1004867#c23

We will use a system clipboard again, once they make it work fast.

**Comment by vramdal** [comment]
Thank you, that's interesting. If the `navigator.clipboard` functions are too intensive to use for every copy/paste, I'd suggest using a Photopea-internal clipboard, and add and _Export to / Import from system clipboard_ feature.

**Comment by photopea** [comment]
Yes, currently, we do have an "internal clipboard" (it has been there for years). It is controlled by Edit - Copy / Cut (Ctrl+C, Ctrl+X) and Edit - Paste. When you press  Ctrl+V, a system clipboard is pasted. If you press Ctrl+V again and the image content is the same, system clipboard is ignored and an internal clipboard content is pasted.

**Comment by vramdal** [comment]
Good to know. But there's no obvious way to export _from_ Photopea _to_ the system clipboard (except going through File -> Export as -> PNG , opening the exported file in the browser, right-click and Copy image).

**Comment by photopea** [comment]
You are right. Putting an image into a system clipboard was never possible in the past (in any browser).

Now, it is possible only in Google Chrome, but the implementation is quite bad. It is still not possible in Firefox and other borwsers, and it is not clear if it will be possible in them at all.
