### ISSUE TITLE
Problem with fonts

### ISSUE THREAD

**Issue by s-ardenedits** [photopea/photopea#1706]
I edit a lot on Photopea, however recently it has not been saving the fonts I add. I click "Yes" when it asks if I would like it (the fonts) to appear again next time I access Photopea, though each time I come back the fonts disappear again.

**Comment by photopea** [comment]
Hi, I just tried to open some TTF fonts in Photopea, clicked Yes , and fonts are there even after closing and reopening Photopea.

Are you using Photopea in an incognito window? Did you install any new extensions? What browser do you use?

Many browsers (@mozilla Firefox) and extensions consider it to be a bad thing, when a webpage stores any data in your computer.

**Comment by photopea** [comment]
I will close it because of no comments from the creator.
