### ISSUE TITLE
Is it possible to export all layers but leave one as the background to each image

### ISSUE THREAD

**Issue by M33rkat5** [photopea/photopea#1707]
I have several images I am trying to export at once and I want them to all have the same decorative background, which is it's own layer beneath the folder containing my main images

But when I export layers, they all export without including the background in any of them

Is there a way to export all layers while leaving one as a global background image?

**Comment by photopea** [comment]
So you want export multiple images, and in every image, different layers should be visible?

You can change the visibility of the layer with the eye icon in the Layers panel. So you can do it manually. "Export layers" feature exports every layer separately - that is not what you need (as you want multiple layers to be visible in every image).

Also, if you know programming, you can write a script, that will export what you need. Here is a tutorial: https://fishtrone.wordpress.com/2019/02/25/generating-images-from-code-with-photopea/
