### ISSUE TITLE
The action sketch

### ISSUE THREAD

**Issue by Akemi145** [photopea/photopea#1708]
Hey, uh, so... Does the sketch action not work? I downloaded it but wasn't sure if it would work, it's a photoshop action. When I apply, "unknown action, rasterize layer" appears and renames the 'background'.

I don't know if you have this action on Photopea, but if not, could you add it?

**Comment by photopea** [comment]
Are you trying to run an ATN file in Photopea? Can you send us these actions to support@photopea.com ?

**Comment by Akemi145** [comment]
yes, of course!

**Comment by Akemi145** [comment]
is this: https://drive.google.com/file/d/15tix_A_mxHPDo-ZrkAUH5JEmkGTW2Hh1/view

**Comment by Akemi145** [comment]
Yes, of course! is this: https://drive.google.com/file/d/15tix_A_mxHPDo-ZrkAUH5JEmkGTW2Hh1/view

**Comment by Akemi145** [comment]
I use "Sketch Color Fill" when I select the action

**Comment by photopea** [comment]
Hi, I think this action requires having several layers with special names. Do you know that? The creator of actions should have supplied some instructions about how to use them (how should the document look like, before you run actions).  Also, it seems like it requires a special set of brushes (.ABR), too.

I think these actions are quite complex and it would take weeks to implement all needed features :( I would rather focus on other things at this point.
