### ISSUE TITLE
F shortcut for fullscreen preview

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1709]
It is possible to have this feature like in Photoshop?
By hitting "F" It's toggling step by step 3 times to full screen view

**Comment by photopea** [comment]
BTW. do you know about pressing Tab in Photopea to change the view?

If we implemented this F shortcut, do you just need the "fullscreen preview", or you need also the preview "in between"?

**Comment by MichalSZZ** [comment]
Yes, I know about Tab :) But sometimes I want to show something (when I editing) in full screen view, without any other things on monitor. Only my artwork.
In photoshop in that case I turn off rulers, hit few times Tab and F.

And @photopea I just ask for "fullscreen preview" - nothing else between :)

**Comment by photopea** [comment]
I implemented it :)  In a fullscreen mode, you can still paint, switch between tools, and do everything you usually do in the main image area.
