### ISSUE TITLE
Zoom info

### ISSUE THREAD

**Issue by danielstrelec** [photopea/photopea#1712]
There is one big thing I am missing in Photopea - actual zoom info in GUI.

I want to know how actual zoom is used - you can see this information in a lot of programs and it is  very important (for me).

Is any chance to put zoom info (like 100%/150%...) somewhere in GUI?

**Comment by photopea** [comment]
Hi, Photopea supports only specific values of zoom, it is not possible to set any zoom you want. E.g. yo u can have zoom 100% or 200%, but nothing in between.

To see the current zoom, enable Rulers (View - Rulers). The zoom value will be shown in the bottom left corner.

**Comment by danielstrelec** [comment]
This is great - thank you! Good enough for me.
