### ISSUE TITLE
Cannot erase the Black and White layer

### ISSUE THREAD

**Issue by fportelos** [photopea/photopea#1714]
We add a new Black and White adjustment layer over another layer. When we go to erase part of the Black and White layer, it won't do anything.

**Comment by photopea** [comment]
Hi, you can not erase part of the adjustment layer. You can only delete the whole layer, or edit its mask. Learn how to use adjustment layers: https://www.photopea.com/learn/other-layers

**Comment by fportelos** [comment]
But I did before. https://vimeo.com/363785059

-Francesco A. Portelos,

IS 27 STEM Teacher
mrportelos.com

"The foundation of every state is the education of its youth." - Greek Philosopher Diogenes

________________________________

**Comment by photopea** [comment]
They are not erasing the adjustment layer, but its mask. Learn about masks here: https://www.photopea.com/learn/masks
