### ISSUE TITLE
Open Sans font text issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1719]
When using Open Sans font size 57px with smaller width at about 61% I noticed it shows strange white thing inside top part of letter "h". See screenshot. When using normal 100% width it looks ok. Is this bug in photopea or inside that font?
![image](https://user-images.githubusercontent.com/6370548/66254650-5edb4c00-e779-11e9-95d3-797278bf7e2b.png)

**Comment by photopea** [comment]
Hi, I tried to do the same, but it works fine. 
![image (1)](https://user-images.githubusercontent.com/15955558/66254743-0907a380-e77b-11e9-95d3-16876dc3ae51.png)

It seems like your browser has a bug when rendering vector graphics. Can you try to update your browser?

**Comment by hxim** [comment]
My browser is updated:
Google Chrome je aktuální
Verze 77.0.3865.90 (Oficiální sestavení) (64bitový)
OS: Windows 10

In firefox it looks ok:
![image](https://user-images.githubusercontent.com/6370548/66254845-56384500-e77c-11e9-82f0-971398824f6b.png)

But in chrome it shows this:
![image](https://user-images.githubusercontent.com/6370548/66254851-62bc9d80-e77c-11e9-9090-778d27ce7ceb.png)

**Comment by hxim** [comment]
I checked my browser settings and if I turn off "Use hardware acceleration when available" it starts to work correctly.
![image](https://user-images.githubusercontent.com/6370548/66254966-f6429e00-e77d-11e9-8210-30d4bd2e30d6.png)

**Comment by photopea** [comment]
@hxim wow, thanks a lot! I have the switch On in my Chrome, but I guess my hardware does not support it.

Could you convert the text layer into a shape and export as SVG? Does Chrome render the SVG the same way?  

If not, could you make a little demo with HTML5 canvas, where you would draw the shape of "h" (e.g. using commands from the SVG)? I need something simple to show to Chrome developers.

**Comment by hxim** [comment]
Yes. Opened SVG is rendered ok. When drawing on canvas it is rendered wrong see link and screenshot:
http://jsfiddle.net/7ceud3j6/
![obrazek](https://user-images.githubusercontent.com/6370548/66255381-09a43800-e783-11e9-9833-24b5380ad11a.png)

**Comment by photopea** [comment]
Thanks  a lot! I reported it to Chrome developers: https://bugs.chromium.org/p/chromium/issues/detail?id=1011615

**Comment by photopea** [comment]
After the Chrome update, it happens on my computer, too.

**Comment by photopea** [comment]
So I will close it now. I hope Chrome will fix it very soon.
