### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Sonleeforever5** [photopea/photopea#172]
I think it would be nice if you made to hue/saturation layer in the filters option try to take some things from pixlr though the wand tool is great. Maybe add a line tool,  and if you could add some things like star brushes and sparkles too! I love sparkles to death, also it's difficult to import images onto a project. Could you please add something for that under layers? That'd be awesome!! As an artist I know these things...though i'm no expert just the below that. Also I don't quite understand how to change colors with the gradient tool.

**Comment by photopea** [comment]
Hi, I believe all this is available in PP already, but it is done differently.

Photopea has Filters and Adjustments. If you click Image - Adjustments, you can change Hue/Saturation there. 

What is a Line tool? When you use Brush, you can hold Shift and click, it will draw straight lines from the previous point.

To add images into the project, just Drag-and-Drop them from your computer into Photopea window (into the current project). You can also copy the image from elsewhere and insert it (Ctrl+V) into a current project.

Search the internet for .ABR brushes (for Photoshop). You can load them into Photopea ... there are millions of brushes on the internet.

When you click on the gradient thumbnail, the Gradient editor will show up. This tutorial may help you: https://helpx.adobe.com/photoshop/using/gradients.html

**Comment by Sonleeforever5** [comment]
I'm glad to hear this, but then the only issue would be with how the hue & satiation tool works. I've tried to change the color of a fill, and it affected every layer below it. Which isn't what I wanted.

**Comment by photopea** [comment]
What exactly are you trying to do?  If you do Image - Adjustments - Hue/Saturation, it will change only the Hue and Saturation of the current layer (that is selected in the Layers panel). If you add an Adjustment layer (Layer - New Adjustment Layer - ...), the adj. layer will affect all layers under it.

**Comment by Sonleeforever5** [comment]
Well thanks for the help! Didn't know that was there.

**Comment by photopea** [comment]
You are welcome! Is there any other way I can help you? :)

**Comment by photopea** [comment]
I guess I can consider it as fixed.
