### ISSUE TITLE
Replacing an Image layer with Script 

### ISSUE THREAD

**Issue by drupalshift** [photopea/photopea#1720]
Hi there 
I just found PhotoPea and I'm in love, I didn't know about photoshop scripting until my license expired and I searched for alternatives and I found PhotoPea and Scripting possibilities 

Sorry if it's newbie question and script related ( I know I have to read and find a solution in adobe docs ), But if you could help me that would be awesome 

I'm trying to open an Image from URL with: 
`app.open("https://i.imgur.com/MgzvrB5.jpg",null,true)`

then replace the layer named lion with new opened layer inside my PSD

Here is my PSD for test 
https://www.dropbox.com/s/lw8s062k7npzh6p/photopea_lion_learn_script.psd?dl=0

There is a layer named "lion" 
Is it possible to replace it with the new layer which is added using `app.open`, and keep the mask and effects intact?

Thanks in advance

**Comment by photopea** [comment]
Hi, Photopea can not run asynchronous scripts at the moment (i.e. it can not pause the script to wait, until a file from URL is downloaded). Are you familiar with Live Messaging? You could probably do it by running two scripts.

**Comment by drupalshift** [comment]
That's so interesting :heart_eyes: 
But my main problem is I don't know how to replace layer even if it's loaded :disappointed:,
I know I have to look it up in adobe documentation but I can't figure out, Every sample I saw failed to do what I'm trying to do 

Could you help me, At least which method I have to look into so I can replace the layer with all mask and effects intact !?

**Comment by photopea** [comment]
I don't think you can "replace the layer". You should remove the old one and add a new one. 

If you try scripts for photoshop and some of them fails, try to find which step exactly fails. We can look at it.

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by DOEHOONLEE** [comment]
Hi! Is it possible to create a smart object, warp it around the puppy's ears, put image in the smart object so that I can customize the ears' colors/pattern?

Can this be done on the [PlayGround](https://www.photopea.com/api/playground)?

Also, assuming it is possible, I don't need to open the photopea to edit images, right? I can just do it by HTTP request. Is this correct?

Thank you! 

![Screen Shot 2021-08-23 at 4 47 44 PM](https://user-images.githubusercontent.com/20305442/130410353-69ae472f-afe8-4ac0-94ab-f6c24b9c6a06.png)

**Comment by photopea** [comment]
Make a Photoshop script or a Photoshop aciton, which can do it in Adobe Photoshop. Try to run it in Photopea. If it does not work, report it here as a bug :)

Photopea runs only in a web browser. You will need to run it on your computer e.g. in an iframe. There is no HTTP API.

**Comment by DOEHOONLEE** [comment]
Alright! Thanks for the explanation! It's all clear now :)
