### ISSUE TITLE
HSL Color Inaccuracies

### ISSUE THREAD

**Issue by jacobScripts** [photopea/photopea#1721]
While RBG and HEX color formats are consistent, specifying a color using HSL values results in a different color than expected. For example, the color specified below is `hsl(210, 90%, 30%)`. However, the corresponding HEX value should be `#084c91` (not `#082a4d`); similarly the RGB value should be `rgb(8, 76, 145)` (not `rgb(8, 42, 77)`).

Also noticed that the lightness values range from 0-100 along the right edge of the color picker, instead of 50-100 like normal.

![Color Picker](https://user-images.githubusercontent.com/52473011/66259865-d0ac9900-e76b-11e9-85b3-6f854270435c.png)

**Comment by jacobScripts** [comment]
Didn't notice it's actually a HSB value, not HSL. I forgot this was the Photoshop standard, and I was having issues with importing web colors because of this discrepancy. Thanks.

**Comment by photopea** [comment]
Yes, HSB and HSL are different color spaces.
