### ISSUE TITLE
unable to download 

### ISSUE THREAD

**Issue by sriramyashwanth** [photopea/photopea#1723]
hello photopea team, I was unable to any type of file while clicking on it. Click on the link below. I have tried so many times clicking on it. please resolve this issue ASAP. because I was totally depended on photopea for designing any banner or youtube thumbnail. Thank you
![photopea issue](https://user-images.githubusercontent.com/38062182/66272266-0a24f780-e885-11e9-9e27-9f9feb64ddf8.png)

**Comment by photopea** [comment]
Hi, this button is for downloading a layer. You should select a layer first (by clicking on it with a mouse, or in the Layers panel).

**Comment by sriramyashwanth** [comment]
> Hi, this button is for downloading a layer. You should select a layer first (by clicking on it with a mouse, or in the Layers panel).
> 
> If you want to export everything (not just one layer), use File - Export As - JPG...

I have tried it the png button does not respond to anything. It doesn't do any downloads options.

**Comment by photopea** [comment]
You should select a layer first by clicking on a layer. It should be highlighted in the layers panel.

Learn how layers work here: https://www.photopea.com/learn/layers
