### ISSUE TITLE
GIF issues

### ISSUE THREAD

**Issue by ifo0511** [photopea/photopea#1725]
When moving a gif, I am unable to move all of its layers. One may think you should move the layers separately, but this is inefficient and there have been several instances in which I can move all the gif layers simultaneously; the conditions just seem to change with every visit to the website.

What can be done about this?

**Comment by photopea** [comment]
You probably enabled "Auto-select" at the top menu. In that case, you will move only one layer at most.

To move multiple leayers, disable "Auto-select" and select layers in the Layers panel instead. See https://www.photopea.com/learn/layers
