### ISSUE TITLE
Zoom function has error when switching between zoom out and zoom in.

### ISSUE THREAD

**Issue by philippeollivier** [photopea/photopea#1726]
If you do command - (on mac) and then do command + right after, then it will zoom out twice rather than expected behavior of zoom out and then zoom in.

**Comment by photopea** [comment]
Hi, I think it is a bug in all Macs. We reported it to Apple, but they did not fix it yet. Try tweeting to them and showing a link to this issue: https://twitter.com/webkit

**Comment by photopea** [comment]
You can also try another browser, but I think this bug is at the OS level.

**Comment by JanRowland11** [comment]
Mine will not zoom back out. I'm not on an Apple computer.

**Comment by photopea** [comment]
@JanRowland11 So what exactly are you pressing? What OS and browser do you use?
