### ISSUE TITLE
Feature request: command search

### ISSUE THREAD

**Issue by vvo** [photopea/photopea#1727]
Hi there,

I frequently wander around the various menus searching for a particular command, for example right now I am searching for the "trim" or "crop" feature I use a lot in other photo editing software.

Here's my process:
![2019-10-08 13 26 11](https://user-images.githubusercontent.com/123822/66392120-44021500-e9cf-11e9-998d-583e54efdf46.gif)

What about we offer a shortcut to search for feature, just like in code editors? See:
![2019-10-08 13 28 29](https://user-images.githubusercontent.com/123822/66392250-8deafb00-e9cf-11e9-9ba5-4d4b4d703ad5.gif)

This is vscode using the shortcut to search for commands.

Let me know what you think!

**Comment by JanRowland11** [comment]
I need any help I can get?!!

**Comment by photopea** [comment]
Hi, I implemented it. Use an icon next to the Account button (or Ctrl+F) to start the search :)

![search](https://user-images.githubusercontent.com/15955558/66868513-bc537200-ef9d-11e9-9e13-c9cf83e072c6.png)
