### ISSUE TITLE
More filters & filter gallery

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#173]
It would be nice to have more filters: glowing edges, plastic wrap, and chrome.

**Comment by manticorp** [comment]
See here for a canvas implementation of glowing edges (if it helps):

https://codepen.io/manticorp/pen/omwJqP

It consists of the following steps:

* blur
* copy + (dilate morphology for ```size in px``` steps using square kernel)
* copy + (erode morphology for ```size in px``` steps using square kernel)
* subtract erosion from dilation
* brighten + contrast

**Comment by photopea** [comment]
Hi, so I implemented Glowing edges a long time ago. 

I have been working on Plastic Wrap for two days, but did not come up with any good result :( So I give it up for now.

**Comment by photopea** [comment]
Plastic Wrap is really hard.

**Comment by photopea** [comment]
We implemented Chrome and Plastic Wrap :)
