### ISSUE TITLE
Differences in radial blur in PS and Photopea

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1731]
![difference-pp-ps-radial-blur](https://user-images.githubusercontent.com/38118273/66499923-0087d380-eac1-11e9-8455-b7e8ed4ee828.png)

It was made from gray raster layer with monochromatic noise filter.
Then I used radial blur with 100 amount

One thing is better for me in Photopea (there is no noise at the edges).
But one thing is strange in Photopea. Middle point when blur starts and end.

[difference-pp-ps-radial-blur.psd.zip](https://github.com/photopea/photopea/files/3708392/difference-pp-ps-radial-blur.psd.zip)

**Comment by photopea** [comment]
Hi, I fixed the problem, thanks for reporting it! :)
