### ISSUE TITLE
I can't save my project

### ISSUE THREAD

**Issue by HarmJanvHolst** [photopea/photopea#1733]
I opened a picture from my computer and editted it in photopea. But now I can't save my project. When I try to save it as PSD it doesn't download or save anyting. If I try to export as .PNG or any other file-type I have the same problem. Nothing saves or downloads to my computer. Can anyone please help me?

**Comment by photopea** [comment]
Hi. Can you open Photopea in a new panel, open any JPG o PNG image in it and save it back as a file?

**Comment by ponera** [comment]
Hi, today I run into similar issue. I uploaded .png and added some text and shape. I could save my project to png, but when I tried to save it as psd nothing happened. (Win 10, Chrome 77)

**Comment by photopea** [comment]
I need some steps how to reproduce it.

Maybe your internet was slow, and the font could not be downloaded. Is it possible?

**Comment by ponera** [comment]
So, apparently problem was with Chrome, it suddenly started to block downloads from this website. Anyway thank you for you help :) 
![image](https://user-images.githubusercontent.com/51154350/66744300-633fed00-ee7c-11e9-8780-c23e4ebe755a.png)
