### ISSUE TITLE
Open / Open & Place actions are mixed up if upload dialog is canceled

### ISSUE THREAD

**Issue by clayware-shard** [photopea/photopea#1736]
Hello.

Found a bit strange behavior.

Prerequisite: No documents are opened.
Actions:
- Select Open & place command from menu.
- Cancel file upload dialog.
- Select Open command from menu.
- Choose some local file in file upload dialog. Ok.

Result: Error "Open a document first." Doesn't open as new document.

Or

Prerequisite: Any document is opened.
Actions:
- Select Open & place command from menu.
- Cancel file upload dialog.
- Select Open command from menu.
- Choose some local file in file upload dialog. Ok.

Result: Inserts selected image into existing file, doesn't open as new document.

And vice versa if you start with Open, cancel the dialog and Open & place.

Tested on Windows 7 in Chrome (77.0.3865.90 Official Build 64-bit) and Firefox (69.0.3 64-bit).

**Comment by photopea** [comment]
Hi, I fixed it, thanks for reporting! I also made "Open & Place" inactive, when no document is opened.
