### ISSUE TITLE
Blur Tool is very strange

### ISSUE THREAD

**Issue by tyronx** [photopea/photopea#1738]
It creates all kinds of colored streaks in my image instead of blurring it. Whats up with that?

Attached a before picture and then one after I wiggled around with the blur tool in the non black area
![before](https://user-images.githubusercontent.com/762006/66750560-73b09180-ee95-11e9-88d9-5595d94514b2.png)
![after](https://user-images.githubusercontent.com/762006/66750564-7612eb80-ee95-11e9-80a1-6dcd6d743c65.png)

**Comment by photopea** [comment]
Hi, we are aware of this. It happens always, when you have semi-transparent pixels, and you "draw" many strokes (20 or more) at the same place.  We do not have a simple fix for it.

Use at most 5 - 10 strokes of a blur tool for a specific place. More strokes would not add more blur anyway. To add more blur, select the area with a lasso and use Filter - Blur - Gausssian blur.

You can try a Smudge tool, too.

**Comment by tyronx** [comment]
O_O

Getting an answer in the likes of "Yes it's broken. Don't use it. Here's some alternatives that do something remotely similar. Issue closed." is not exactly what I expected from a valid bug report. Also, the streaks already appear after 5 strokes of the blur tool, not after 20. 

Pity. I Guess I'll have to fall back to Photoshop after all.
So much for your goal of creating the most advanced and affordable photo editor.

**Comment by photopea** [comment]
I am very sorry, you are right. I received quite a lot reports this morning, and I felt quite overwhelmed.

Turns out the problem was not in what I thought it was, and was quite easy to fix. So it is fixed now.

**Comment by tyronx** [comment]
Thank you. As a fellow programmer who tries to make a living from his own software (or rather game) I know the feeling of being overwhelmed by bug reports all to well. 

I got the 90 day premium account now.

**Comment by photopea** [comment]
Really? I also made games :D  http://games.ivank.net/  There are even reviews of "Dino Hunt 2" on Youtube :)

BTW. feel free to discuss the old issues, that I closed.

**Comment by tyronx** [comment]
Oh, nice! Tried Dino Hunt 2 for a few minutes. I make Vintage Story (https://www.vintagestory.at/) for which I occasionally use Photopea :-)

Thanks for the offer on the other issue.
