### ISSUE TITLE
Change space between lines

### ISSUE THREAD

**Issue by stepanov** [photopea/photopea#174]
Hi,

Is there a way to change the space between lines as per attached Photoshop setting screenshot?

Thank in advance
Michael
![chracter-and-paragraph-panel](https://cloud.githubusercontent.com/assets/166552/25738968/750fcad6-3188-11e7-9598-74fc5c516c6f.jpg)

**Comment by photopea** [comment]
Hi, there is the Character window in Photopea too. Press Window - Character to open it (or click on "Cha" button in the "narrow column"). You can change the Leading value in it.

**Comment by stepanov** [comment]
Great! Thank you! Didn't realize it.
