### ISSUE TITLE
Text on curve shape with two parts error

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1741]
I created new shape with Ellipse tool (with Shape setting) and then added another ellipse to same shape/layer with Ellipse tool (now with Path setting). After that I added Text on curve on second ellipse. Then selected Path Select tool and tried to move second ellipse.
It will crash with error and nothing is working:
pp.js:8898 Uncaught TypeError: Cannot read property 'Cr' of undefined
    at UL.CY (pp.js:8898)
    at po.RQG (pp.js:9281)
    at po.UU.i (pp.js:9)
    at po.pI.i (pp.js:6432)
    at c.gC.$U (pp.js:4255)
    at po.update (pp.js:9359)
    at po.Ww (pp.js:9358)

**Comment by photopea** [comment]
Fixed, thank you! :)
