### ISSUE TITLE
Quick Select and Wand Select Lag

### ISSUE THREAD

**Issue by blofstedt** [photopea/photopea#1743]
Both the Quick Select and the Wand Select tools are extremely laggy. You cannot see the selection in real-time and there is about a 1-second lag until you see what you've selected. Also, the selection for the Quick select is giant blocks instead of smooth areas like in Photoshop. Is there a way to fix this?

**Comment by photopea** [comment]
Hi, I know about the Quick Select lag, but I don't know how to make it faster :(

However, Magic Wand should be quite fast. When I tried it on 2MPx image, it is selected right after releasing the mouse. On a 15MPx image, there is about 1 second lag. Is that what you experience?

**Comment by photopea** [comment]
I will close it because of lack of details.
