### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MysticDesigns** [photopea/photopea#1746]
When I right click on the plane, this window does not come where I can make a cut mask

**Comment by photopea** [comment]
Hi, do you mean right-clicking on the working area? The result depends on the tool that is active at that moment.  What would you like to happen when you right-click? 

I have never heard of "cut masks" :(

**Comment by gcostelha** [comment]
I have right-click issue as well. Today I cannot right-click on layers. The window does not come as well.

**Comment by photopea** [comment]
Guys, I am very sorry, I fixed it.

**Comment by MysticDesigns** [comment]
Yes Right click issue
