### ISSUE TITLE
Euro sign - € - is displayed as a square

### ISSUE THREAD

**Issue by stepanov** [photopea/photopea#175]
I tried to add € sign to the text on my PSD but it's displayed as square in all fonts. Dollar and pound signs are displayed correctly. Any suggestion how to fix that?

Thank in advance.

**Comment by photopea** [comment]
Hi, I just tried to type "€" in the Liberation Sans font and it worked. Also in fonts Alegreya, Amble, Arcon ... What font are you using? I guess this character is missing in your font.

We could add a function, that will show only the fonts, which contain specific characters.

**Comment by stepanov** [comment]
Thank you! It looks like my fond doesn't have such symbol. I used vag-rounded-bt.
 The function with special symbols will be very helpful!
