### ISSUE TITLE
Character width/height for text on a curve

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1751]
I made text on circle - I increased text character height to 300% and it did this - see screenshot. Is this intended behauviour or bug? Can photopea first scale those letters and rotate them afterwards because I want to have higher letters on circle.
![image](https://user-images.githubusercontent.com/6370548/67093279-87b80400-f1b1-11e9-8b1a-2aad3ea834b5.png)

**Comment by photopea** [comment]
Hi, I fixed it :)
