### ISSUE TITLE
Large file size after saving psd

### ISSUE THREAD

**Issue by QuantumInformation** [photopea/photopea#1752]
I uploaded 2 x 4mb file from unsplash, but my psd export is ≈200mb
I have a few blending options and effects.

Is this normal?

**Comment by photopea** [comment]
Hi, I think it is normal. PSD is a lossless format. If you have smart objects, each image is stored twice or three times with smart filters.

Complex PSD files with many layers and high resolution often have 5 - 10 GB.

**Comment by QuantumInformation** [comment]
Ok thanks, I reduced my canvas size from 4k to 1.2k and it was better

**Comment by photopea** [comment]
With no smart objects, it should be at most 4 MB per one megapixel (or 3 MB, if there are no transparent pixels).

E.g. if a layer si 4000 x 5000 pixels, the layer will take 20x4 = 80 MB.

With three such layers, you will get 3x80 + 80 = 320 MB (as there is extra 20 megapixels for the preview of the whole document).
