### ISSUE TITLE
 There are strong problems with the "Free Transformation" tool.

### ISSUE THREAD

**Issue by zethboccelli06** [photopea/photopea#1754]
I do not understand the problem with everything covered by the "Free Transformation" tool. It can be used with images already placed on a template, but you cannot transform a photo by the tool, it is a rather annoying problem when you need to do a graphic design job , please take care of this case, solve it as soon as possible, I am a user of this page two years ago, thanks in advance.

**Comment by photopea** [comment]
Hi, I can not see such problem :( What exactly should I do to make the problem visible? 

Free Transform seems to work well for me :/

**Comment by photopea** [comment]
Ok I found it. You should select a part of an image, Copy-paste it (with Copy and Paste, not Duplicate layer) and apply Free Transform after that.

I fixed it. I am very sorry for the problem :(

**Comment by zethboccelli06** [comment]
Good morning, I hope everything goes well for you. I am here to make a
small complaint, I have been a loyal user of your platform for a long time,
and I have problems with the option "upload file" and the option "new" or
"create new project" It does not upload any photos that I upload or no file
that I want to create, please, I want you to fix this soon because I have
important work to do. Thank you very much for your attention.
