### ISSUE TITLE
Problem with Layer adjustment tools

### ISSUE THREAD

**Issue by izzysediting** [photopea/photopea#1755]
Hi, there's a problem with the gradient tool and the color replace tool, I click on them and nothing happens.

**Comment by photopea** [comment]
Hi, sorry, I can not see any strange behaviour of these tools :(

Do you know how to use them? You should click into image to apply it.

**Comment by KittyBeaver** [comment]
I've had the same issue. Haven't tried Color Replace, but the Gradient adjustment layer isn't working. I was using it before, so it's not a matter of not knowing how to use it. I can still use Chanel Mixer, Color Balance, Hue/Saturation
![Gradient Adjustment Layer Doesn't Work](https://user-images.githubusercontent.com/56851679/67251078-d24cb100-f43b-11e9-8e94-d961e0ba6879.jpg)

**Comment by photopea** [comment]
You are right, creating certain types of Adjustment Layers is not possible. I will try to fix it as soon as possible.

**Comment by photopea** [comment]
Hi, I fixed these.

Note, that Replace Color Adjustment Layer is not available in Adobe Photoshop. If you open a PSD with such layer in Photoshop, Photoshop will ignore it.

**Comment by KittyBeaver** [comment]
Thank you so much!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
