### ISSUE TITLE
Brush/erasing appear red

### ISSUE THREAD

**Issue by mavila20** [photopea/photopea#1756]
doesn't matter what color i decide to use, it's red same goes for the eraser tool

**Comment by photopea** [comment]
Hi, I can not reproduce it :(

Can you show me a screenshot of the whole screen?

**Comment by MichalSZZ** [comment]
@mavila20  can you check, that you have enabled "quick mask" option? 
![obraz](https://user-images.githubusercontent.com/38118273/67268022-c997c180-f4b3-11e9-948d-770ee59a0d6c.png)
I think that might be that in your case (that is circle icon under foreground and background color)

**Comment by photopea** [comment]
I have to close it bacause of lack of details :(
