### ISSUE TITLE
DeNoiser

### ISSUE THREAD

**Issue by Sii-22** [photopea/photopea#1757]
it would be nice if there's a Photoshop's Camera Raw filter like in Photopea

**Comment by manticorp** [comment]
If it helps, a typical noise reduction algorithm for photographs separates chroma and luminance noise.

The chroma noise can be easily reduced by taking a 'Median' layer and compositing atop the original image in 'Color' mode (this would be fairly easy to implement in a noise reduction filter).

Luminance noise is much more difficult, but a good start would be a gaussian blur to the luminance channel which is then sharpened with a complimentary unsharp mask.

Use this in combination with the colour noise filter above and combine the two as luminance/chroma channels. This would create a nice, simple de-noise function.

Removing noise from an image, though, is quite highly specialised and there are whole software suites out there to de-noise images, which might be out of the remit of Photopea.

**Comment by photopea** [comment]
Hi, I implemented the Reduce Noise filter in Filter - Noise - Reduce Noise :)
![126625872-96687ad9-29b2-4873-8604-78d53c268792](https://user-images.githubusercontent.com/15955558/128425591-2a18db82-0bee-4e6a-94b4-7e3c6abe7f12.jpg)
