### ISSUE TITLE
Allow to manage text styles

### ISSUE THREAD

**Issue by strogonoff** [photopea/photopea#1758]
Somewhat related to https://github.com/photopea/photopea/issues/52.

IMO, the ability to manage text styles would be super useful.

It would be useful for object styles too, but that can somewhat be addressed by creating multiple instances of the same smart object. This doesn’t work with text content, hence an ability to manage paragraph/character styles would be a killer feature. (Actually, I’m not aware of said feature in PS, but InDesign does it well.)

**Comment by strogonoff** [comment]
As a side note, I got very excited when I discovered the CSS pane, thinking I could set any text or object styling directly from code… Was somewhat disappointed on that front, but am still very impressed by this piece of software.

**Comment by Photopeafan2** [comment]
I have an issue that my txt is on a leading of 22 px, when i copy it in a new txt frame it becomes a leading of 1 px, yet is 22 px on the txt character panel.

**Comment by photopea** [comment]
We depend on PSD files, and you can not have such styles in PSD files.

But if you copy-paste a part of a text layer into another text layer, the style is copied, too.
