### ISSUE TITLE
CSS panel show only first of effect with ability to have multiple box-shadows

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1759]
"Drop shadow" in Google Material Design have 2 shadows on object. I have preset for that type of shadows and want to copy CSS style of it, but CSS panel shows only the first one.

CSS3 (2.1 formally?) gave ability to have many shadows separated by comma e.g. 
box-shadow: shadow-one, shadow-two;

Same thing with gradients.

**Comment by photopea** [comment]
Hi, I implemented  multiple shadows in CSS.
However, in the "filter" mechanism, each filter is applied to the results of all previous filters. See this:

https://jsfiddle.net/m7jyksnh/
