### ISSUE TITLE
CSS drop shadow style for text layer and filter: drop-shadow for non rectangle objects

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1760]
When I add shadow to text layer, in CSS panel should to be text-shadow instead box-shadow.

There is one more thing with shadows in CSS but it is complex.
Box-shadow work good with regular <div> boxes or images with no transparency (when you coping CSS - it will look probably the same in browser as in Photopea)

For objects with no regular shape, better solution is to use filter: drop-shadow
https://css-tricks.com/breaking-css-box-shadow-vs-drop-shadow/

**Comment by photopea** [comment]
Ok I made it always produce filter: drop-shadow(...);   I think it is an expected behaviour almost always.
