### ISSUE TITLE
Cmd + Shift + N on Mac OS makes new layer and new project same time

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1763]
like in the title
Ctrl + Shift + N works good but Mac OS users use Cmd not Ctrl

**Comment by photopea** [comment]
At this moment, Photopea is configured to consider Ctrl equivalent to Cmd.

Can you go here http://jsfiddle.net/p45f44zb/14/ , click into the white area and try your shortcuts? Does it awlays show only pressed keys? If not, I guess it is a bug in Mac OS.

**Comment by MichalSZZ** [comment]
@photopea 
On jsfiddle when I release all the keys, it stays ["KeyN"] always visible. Another hit in that key make it invisible.

I just tested, when the new project window is showing in Photopea and (in the order of pressing and releasing the keys - slowly):

![obraz](https://user-images.githubusercontent.com/38118273/67836247-6aa5fe00-faec-11e9-9c55-8d7f33eb9ecf.png)

- +Left Shift +Cmd +N -> -N -Cmd -Left Shift = new layer 
- +Left Shift +Cmd +N -> -N -Left Shift -Cmd = new layer + new project

When I hold this shortcut a little longer, Photopea creates many new layers until I unrelase keys (it is strange behavior).

With this combination of keys (when I hold longer and release only Shift and still hold Cmd + N) Photopea open new instances of program (a lot - until I will release keys) 

with Ctrl key works good all the time (nomatter how fast and in which order I release the keys)

IMPORTANT!

also now I see that (in Mac OS):
cmd + N = create new project window (should to be Alt + Cmd + N)

**Comment by photopea** [comment]
If you release all keys, but the JSFiddle still shows you, that some key is presed, it means, that there is no reliable way for Photopea to know, which keys are pressed :(

That is why I think there is no point in trying to fix it. It should be fixed on the OS level.

**Comment by MichalSZZ** [comment]
And what with the other problem that I found? 
cmd + N = create new project window (should to be Alt + Cmd + N)
