### ISSUE TITLE
Ctrl + Tab for switching tabs with projects (only in PWA)

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1764]
I know there is a problem with that shortcut in browsers (like with Ctrl + T for transform), but can it work in PWA version?

**Comment by photopea** [comment]
I implemented it, thanks!

**Comment by MichalSZZ** [comment]
Thanks. Works great!(on Mac it should be used with Ctrl because Cmd + T has own functionality in this system)
