### ISSUE TITLE
Linked text boxes like in Illustrator or InDesign

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1765]
In Illustrator or InDesign there is a possibility to link two or more text boxes. 
When in first text box there is more word then can be, rest of paragraph is continued in secound one that is linked.
https://youtu.be/99e0cXW_DaM

I know - that functionality can't be stored in PSD file becouse Photoshop don't have this option...
In PS, peoples use addons like UberColumns (there was a free version before I think) but it work in different style.
https://www.youtube.com/watch?v=oAplQyrcP_Y

**Comment by photopea** [comment]
I dont like the idea of linked text boxes, as they can not be saved in a PSD.

But maybe we could make a plugin, that will split a rectangular text into columns. What do you think?

**Comment by MichalSZZ** [comment]
@photopea do you mean functionality like in UberColumns? 
That would be great.

**Comment by photopea** [comment]
As we have Text in Shape now, I think it can replace this feature.
