### ISSUE TITLE
Selection issues

### ISSUE THREAD

**Issue by Vivivane** [photopea/photopea#1767]
Hi,
I can't select nor create a new layer. Plus, resizing a layer is impossible, a box appears, it looks like a selection of something invisible. I have the same issue while adding text, it does not work...

**Comment by photopea** [comment]
Hi, could you describe how can we reproduce such behaviour?

I just tried to create a new document and I can do everythin, what you said you can not do.

**Comment by Vivivane** [comment]
Hi, 
The selection issue appears to be fxed for the images. But not for the text.
If I try to add/edit a text, nothing happens. The text is not selected. Plus, I can't resize it.

**Comment by photopea** [comment]
We did not fix anything.

How do you select and resize a text? Could you maybe record a video of what you do?

**Comment by Vivivane** [comment]
Hi, I'm really sorry, but that is also fixed. I don't understand how it is possible. I've been using Photopea for about a year now so it is not due to a misuse of it.
I had to postpone my work friday because it was not working and i didn't think of taking screenshots of all issues. As you can see on the attached file, the first layer is a text in white. It did not appeared on my screen. I was not able to edit it nor select it. But it is now working.
Thanks for the help anyway.
![Capture](https://user-images.githubusercontent.com/54576383/67663192-394ef600-f965-11e9-9fa2-dadfd232f4df.JPG)

**Comment by photopea** [comment]
Ok i will close it now.
