### ISSUE TITLE
Selection problems

### ISSUE THREAD

**Issue by takochi** [photopea/photopea#1768]
Whenever i try to resize or rotate an image/layer 
a small box appears on the upper left corner and it deselects the move tool
![Captura](https://user-images.githubusercontent.com/57111365/67708133-437eed80-f981-11e9-8f4b-0cd24b9c310c.PNG)
![issue2](https://user-images.githubusercontent.com/57111365/67708134-437eed80-f981-11e9-992c-ec908806f3fd.PNG)

**Comment by photopea** [comment]
Hi, could you please describe steps, what should I do, to make it happen?

**Comment by photopea** [comment]
In your screenshot, the Width and Height are set to 0%. In that case, all 9 points of a transformation rectangle are at one point, so it all looks like a tiny square.

If you want to remove a layer, you can simply press the trash icon, instead of setting the size to 0 pixels.

**Comment by takochi** [comment]
Sure, i just select the move tool pick any image try to rotate it or resize it and the box will appear immediately in the top left corner like in the images above

**Comment by photopea** [comment]
I opened a JPG image from my computer, I pressed Edit - Free Transform. I can rotate my image without any problems.

**Comment by takochi** [comment]
perhaps it's an issue with the file im working on i'll try to move it to another new file and see if that fixes it

**Comment by takochi** [comment]
yeah that did it, it works now, thank you

**Comment by photopea** [comment]
If it is a bug, it should be fixed. Can you save your old file as PSD and open it again? Does it still happen?

**Comment by takochi** [comment]
yeah it still happens on the old psd file if i try to open it again but not on the new one

**Comment by photopea** [comment]
Can you send that PSD to support@photopea.com ?
