### ISSUE TITLE
Magic Wand selected wrong pixels

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1769]
I wanted to select white area with Magic Wand and clicked on pixel where is mouse cursor on screenshot but it selected gray area one pixel below instead of white:
![image](https://user-images.githubusercontent.com/6370548/67747068-3963fa00-fa28-11e9-987f-766e5a05ed47.png)

**Comment by photopea** [comment]
Hi, I am very sorry, it is fixed now, thanks!
