### ISSUE TITLE
Cannot open the "File Open" window

### ISSUE THREAD

**Issue by Speedtwins** [photopea/photopea#177]
I've use Photopea in the past with no issue, however tonight after the site pulled up in my browswer, I selected File>Open and nothing happened. I have no way to open my saved PSD files. Any suggestions as to what may be going on?

Thanks,
Sam

**Comment by photopea** [comment]
Hi, I am very sorry, it works now.

I was testing a new version of code minifier. I thought that I have fixed all the issues, but it seems I have not.  BTW. you can also drag-and-drop files into Photopea window, it may be more comfortable sometimes :)

**Comment by Speedtwins** [comment]
Thanks for the quick response. Really appreciate the quick fix. 
Thanks, Sam


Sent via mobile device. 
-------- Original message --------From: Photopea <notifications@github.com> Date: 5/6/17  18:57  (GMT-05:00) To: photopea/photopea <photopea@noreply.github.com> Cc: Speedtwins <motor_ninja@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [photopea/photopea] Cannot open the "File Open" window (#177) 
Hi, I am very sorry, it works now.
I was testing a new version of code minifier. I thought that I have fixed all the issues, but it seems I have not.  BTW. you can also drag-and-drop files into Photopea window, it may be more comfortable sometimes :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/photopea/photopea","title":"photopea/photopea","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/photopea/photopea"}},"updates":{"snippets":[{"icon":"PERSON","message":"@photopea in #177: Hi, I am very sorry, it works now.\r\n\r\nI was testing a new version of code minifier. I thought that I have fixed all the issues, but it seems I have not.  BTW. you can also drag-and-drop files into Photopea window, it may be more comfortable sometimes :)"}],"action":{"name":"View Issue","url":"https://github.com/photopea/photopea/issues/177#issuecomment-299670971"}}}
