### ISSUE TITLE
Possibility to change text atributes in multiple text layers in one time

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1771]
In Photoshop, I can select two or more layers in layer pallete and then in Character Panel, change e.g. color, font-size etc. for all of them.

It is great time saving feature for me.

In Photopea, even if I have one layer selected, I can not change anything until i use text tool on that text layer. Character panel do nothing when only layer (with other active tool) is selected.

**Comment by photopea** [comment]
I see that now, if you select multiple text layers, and change the text style, it will be changed for all selected layers. But it only works when a Type tool is chosen.

So we just need to make it work from Characters panel, even when another tool is chosen.

**Comment by photopea** [comment]
I implemented it. You can change the text style e.g. from a Character / Paragraph panel, no matter what tool is chosen.
