### ISSUE TITLE
Magic Wand with Tolerance

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1772]
I wanted to select only darker (non-white) pixels of my shape with Magic Wand with high Tolerance setting but it keeps partially selecting all neighbouring pixels. My Anti-alias and Contiguous are turned off and Feather settings is 0px.
![image](https://user-images.githubusercontent.com/6370548/67937443-e9269c80-fbcd-11e9-9199-afffdaeed6d8.png)

**Comment by photopea** [comment]
Can you show me a PNG of this?

**Comment by photopea** [comment]
It is ok, I can reproduce it.

**Comment by photopea** [comment]
It is fixed now :)
