### ISSUE TITLE
it is crashin when i am tryin to do drop shadow, please help

### ISSUE THREAD

**Issue by DonnaWxnter** [photopea/photopea#1774]

**Comment by photopea** [comment]
Hi, I just tried to add a Drop Shadow layer style, and it worked well.

How large is your image in pixels? Does it happen for every image you ever tried?

**Comment by DonnaWxnter** [comment]
Yikes the image size seems off too. It’s not the accurate aspect ratio.
It’s 6680 x 7095.
That’s the size I did on vectornator.

**Comment by photopea** [comment]
That is quite a lot. Each layer requires 200 MB of RAM in such case. Several temporary layers are created during the generation of a layer style. You probably don't have enough RAM.

Do you really need such resolution? Can you make it smaller using Image - Image Size?

**Comment by DonnaWxnter** [comment]
Ram? Do u mean on my computer?

**Comment by photopea** [comment]
I guess it crashes because of not having enough graphics memory. Try to disable WebGL (More - Use WebGL), it should work then.  Or just use smaller images.
