### ISSUE TITLE
Feature request TGA file support.

### ISSUE THREAD

**Issue by CarnageMarkus** [photopea/photopea#1775]
Hello there, this is great editor, thanks for developing it. As I work with TGA format daily, would it be possible to export into TGA ? 
It is cumbersome for me to export into PNG, and then use different tool to convert into TGA.

**Comment by photopea** [comment]
Hi, PNG format can actually fully replace TGA.  But TGA format is much simpler (and files are bigger) than PNG.

Cant you use PNG in your case? There should exist PNG format decoders in every platform.

**Comment by Castigavi** [comment]
TGA is extensively used in gaming and modding communities while PNG is not supported. Saving in PNG format would be as practical as drawing on paper, putting it inside PC case and then being surprised it doesn't show on your computer.

**Comment by photopea** [comment]
Hi, so now, Photopea can open and save TGA files. When exporting, Photopea performs lossless RLE compression to make files smaller.

It is sad, that your software does not accept PNG files. PNG files are often 3x smaller than TGA with RLE compression (containing the same image).
