### ISSUE TITLE
When resizing selected text, please retain custom colours if text has mutiple.

### ISSUE THREAD

**Issue by QuantumInformation** [photopea/photopea#1776]

**Comment by QuantumInformation** [comment]
using transform retains colours

**Comment by photopea** [comment]
Hi, what do you mean? Free Transform transforms the whole layer, not the selected text.

When I have multiple colors in one text layer, changing the size does not change the colors.

**Comment by hxim** [comment]
@photopea I just tried and if you select text like this with left mouse button triple click and then change size it will destroy individual colors
![obrazek](https://user-images.githubusercontent.com/6370548/68084831-38253980-fe3b-11e9-9bb0-0a2218488697.png)
![obrazek](https://user-images.githubusercontent.com/6370548/68084892-699e0500-fe3b-11e9-8dc8-86418d63f501.png)
![obrazek](https://user-images.githubusercontent.com/6370548/68084914-79b5e480-fe3b-11e9-8e09-67dc817d9e27.png)
![obrazek](https://user-images.githubusercontent.com/6370548/68084920-86d2d380-fe3b-11e9-806d-8da92b682c42.png)

**Comment by photopea** [comment]
I fixed it, thanks!
