### ISSUE TITLE
lagging on quick select

### ISSUE THREAD

**Issue by suhflower** [photopea/photopea#1777]
I am trying to work on a project however, whenever i begin using the quick select tool the website begins to lag eventually causing it to crash.

**Comment by photopea** [comment]
Hi, we are preparing a brand new version of Quick Select, which will work much faster than the current one. It should be ready in a couple of days.

**Comment by photopea** [comment]
We will present a new Quick Select in 10 hours from now. You can follow our Facebook or Twitter to be informed about new updates.
