### ISSUE TITLE
copy paste from external text does not work

### ISSUE THREAD

**Issue by MartinBechber** [photopea/photopea#1778]
copy paste from external text does not work

The text is not pasted into the image.

**Comment by photopea** [comment]
Hi, how exactly are you copy-pasting a text?

You should enter a text layer (or create a new one) and then, press Ctrl+V. It is described here: https://www.photopea.com/learn/text

**Comment by MartinBechber** [comment]
Hello

Did exactly what you said. Existing textlayer with already text in it. Then
had text in a regular txt file, copied and then strg + v into the existing
layer. It was only put a black box into the layer. Tried marking and
changing of font color. But no change hapened.

Photopea <notifications@github.com> schrieb am So., 3. Nov. 2019, 18:13:

**Comment by photopea** [comment]
Black box? Is your text chinese or arabic? If the font does not support your characters, it will draw black boxes for such characters.

**Comment by MartinBechber** [comment]
No but i use an uploaded font. Segoe print.

Photopea <notifications@github.com> schrieb am So., 3. Nov. 2019, 18:56:

**Comment by photopea** [comment]
And what if you type a text on a keyboard? is it displayed correctly?

**Comment by MartinBechber** [comment]
Yes

Photopea <notifications@github.com> schrieb am So., 3. Nov. 2019, 19:09:

**Comment by photopea** [comment]
Can you send me the PSD file, the TXT file, and a font to support@photopea.com ?

**Comment by MartinBechber** [comment]
Hello

Your mail account does not accept a file this large. The file is about 11
MB, because it is a A2 poster. I try to shrink the size of the image and
then save it.



Am So., 3. Nov. 2019 um 19:23 Uhr schrieb Photopea <notifications@github.com

**Comment by MartinBechber** [comment]
Hello

When using the smaller image size the copy and paste works.

So is there a way i can send you the large file`? Maybe the size of the
file has something to do with it?


Regards Martin

Am So., 3. Nov. 2019 um 19:23 Uhr schrieb Photopea <notifications@github.com

**Comment by photopea** [comment]
Can you remove some layers from your large PSD? It should become smaller.

What if you create an empty PSD in Photopea with the same dimensions? Can you copy-paste the same text into it?

**Comment by MartinBechber** [comment]
Hello

When creating a file of for example 4000 py width and 8000 height and 300
dpi the black box occurs everytime

I tried to send you a file with reduced layer but even a 5 mb file is to
huge for your inbox.



Am So., 3. Nov. 2019 um 18:13 Uhr schrieb Photopea <notifications@github.com

**Comment by photopea** [comment]
Hi, what exactly do you mean by a "black box"? Could you show us a screenshot?

I have people sending me 50 MB files without any problems. How do you know, that "it is too huge for my inbox"?

**Comment by MartinBechber** [comment]
Hello

Or is this a gmail limitation?

[image: image.png]



Am Mo., 4. Nov. 2019 um 10:23 Uhr schrieb Photopea <notifications@github.com

**Comment by photopea** [comment]
You are sending all these messages as emails to  @GitHub.com  . I think GitHub can not show the images that you send it.

You should go to https://github.com/photopea/photopea/issues/1778  and reply there, or send us an email to support@photopea.com

**Comment by photopea** [comment]
The problem is caused by WebGL acceleration. With WebGL, the width and height of each layer can not be bigger than 8192 pixels.

However, when you paste your text into a text layer, it becomes 28 000 pixels wide. 

So there are multiple solutions: disable WebGL (more - use WebGL), or break your text into multiple paragraphs before pasting (so that each line is not wider than 8192 pixels after pasting). Or use Paragraph text instead of Point text (then, lines will be broken automatically, see https://www.photopea.com/learn/text )
