### ISSUE TITLE
Image->Trim does not work in Chrome OS

### ISSUE THREAD

**Issue by TheRiflesSpiral** [photopea/photopea#1779]
Making a selection then choosing "Trim" from the "Image" menu has no effect.
Chrome OS Version 77.0.3865.105 (Official Build) (64-bit)

**Comment by photopea** [comment]
Hi, what exactly would you like to happen after you press "Trim"?

**Comment by TheRiflesSpiral** [comment]
Trim the image boundaries to the selection.
What's the intended function of "Trim"?

**Comment by photopea** [comment]
The "Trim" feature in Photopea or Photoshop removes the regions from top, left, bottom and right sides of the image, which have the same color (e.g. if you have a yellow star on a blue backgroun, it will crop the image to smallest rectangle, which still contains the whole star). It ignores the selection completely.

To crop the image to a custom rectangle, use a Crop tool. It is described here: https://www.photopea.com/learn/image-size

There is also a button at the top, to crop the image according to a current selection.

**Comment by AhmedRadwan76** [comment]
Hi there , lasso tool , in chrome , the movement of cruiser doesn't math the line of lasso tool, there is a wide distance between them

**Comment by photopea** [comment]
Press Edit - Preferences, and set the cursor offset to zero. You probably changed it without knowing what it means.

**Comment by AhmedRadwan76** [comment]
Thank you so much , It works mow
________________________________
