### ISSUE TITLE
Pen Tool

### ISSUE THREAD

**Issue by ToonzBoom** [photopea/photopea#178]
You do not have the Pen Tool tool. Adobe blurted out openly one of his photoshop with open source.

https://github.com/adobe-photoshop/spaces-design

![untitled-3](https://cloud.githubusercontent.com/assets/28530944/25810767/d12f7120-3419-11e7-8da9-0a0e7698a798.jpg)

**Comment by photopea** [comment]
Hi, 
we are planning to add vector-drawing capabilities, it is already in this issue: https://github.com/photopea/photopea/issues/110

The software at your link is not Adobe Photoshop. It seems like it is just a theme to Photoshop, which changes the user interface. Only people who already own Photoshop can use it.  You can change the code of this theme, but you need Photoshop software to use it.

**Comment by ToonzBoom** [comment]
Thank you so much. I am very pleased that you answered me.

**Comment by photopea** [comment]
Ok, so I will close this issue, we can keep the discussion in #110
