### ISSUE TITLE
Saving a file (gif with 53 frames) it keeps crashing

### ISSUE THREAD

**Issue by DonnaWxnter** [photopea/photopea#1783]
Hi i've merged the layers so there is only one image and a gif that has 53 frames; but everytime i try to save this as a gif, photopea is crashing on me; please help; i've worked so hard on this and i need it asap, lol thank youj; the main image or the background image size is 1775 x 1880

**Comment by DonnaWxnter** [comment]
ps: im not sure if the aspect ratio was set;

**Comment by DonnaWxnter** [comment]
its doing it again; please help

**Comment by DonnaWxnter** [comment]
my file size says 31.6 mb lol; that is for the gif

**Comment by photopea** [comment]
Hi, try to decrease the size of your file. Image - Image Size - set 500 x 500 pixels.

Now, it sounds like you are trying to save a 4K two-hour movie as a gif. Rendering movies often takes hours.

**Comment by DonnaWxnter** [comment]
Ah I see thank u! I shall try this method instead. Thanks! I compressed the
file instead and managed to
Get it saved as a gif

**Comment by photopea** [comment]
I will close it now.
