### ISSUE TITLE
Object Selection crash

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1785]
Object Selection crash when applied on small region (like 5x5 pixels)
1.) Create new project (white background)
2.) Zoom in to maximal zoom level
3.) Select Object Selection Tool
4.) Use Object Selection Tool on 5x5 pixels region
5.) Object Selection Tool stops working
and it shows error in console
pp.js:1856 Uncaught e

**Comment by photopea** [comment]
I fixed it, so that it always does something, without trhowing errors.
