### ISSUE TITLE
Loading psd crash

### ISSUE THREAD

**Issue by MaximMatrosov** [photopea/photopea#1786]
Infinite loading and message in console:
Access to XMLHttpRequest at 'https://dmx.districtm.io/b/v1' from origin 'https://www.photopea.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by photopea** [comment]
Hi, I think that error message is not related to the problem with PSD. Could you send us your PSD to support@photopea.com ? How large is it?

**Comment by photopea** [comment]
I will have to close it because of lack of details :(
