### ISSUE TITLE
very small suggestion: inconsistent space in Layer > Raster Mask; ラスター マスク and Vector Mask; ベクターマスク

### ISSUE THREAD

**Issue by xilehence** [photopea/photopea#1789]
We use English and Japanese at my international university.  I wonder why Layer > Raster Mask is translated ラスター マスク (with a space between the two words) whereas Vector Mask lacks that space: ベクターマスク. Shouldn't the translations be consistent?  (Generally, Japanese people don't use spaces of loan words well, but i personally prefer the interpolated space since it helps to parse the katakana transliteration.)

**Comment by photopea** [comment]
Hi, the translations were made by our users. Can you please fix it at https://www.photopea.com/translate/ ?

**Comment by photopea** [comment]
I will close it now.
