### ISSUE TITLE
.adr brushes

### ISSUE THREAD

**Issue by ToonzBoom** [photopea/photopea#179]
Will there be support for the (.adr) brushes?
![image](https://cloud.githubusercontent.com/assets/28530944/25811852/381006ea-341d-11e7-8043-ed7dc4fef722.png)

**Comment by photopea** [comment]
Hi, do you mean .ABR brushes? You can load them already.  If you really mean .ADR brushes, please send them to us, so we can have a look at what it is.

**Comment by ToonzBoom** [comment]
You're right (.Abr). I just now learned that it's possible. Thank you.
