### ISSUE TITLE
Resizing of a picture/text impossible

### ISSUE THREAD

**Issue by Vivivane** [photopea/photopea#1792]
Hi,
Resizing a layer is impossible, a box appears, it looks like a selection of something invisible. I have the same issue with texts, it does not work...
Here are some screens  
1. I'm selecting an image or a text, I'm willing to resize it with the arrows that I represented in red
2. The moment I'm clicking on an arrow, it is a mysterious box that is selected, not the layer I wanted. This box is not part of my layers, it appears at the exact same place on all my files, and it is the only thing that I can resize. 
![2  selectioon of a random box automatically](https://user-images.githubusercontent.com/54576383/68653680-879af200-052c-11ea-807f-05ad55ba2f29.JPG)
![1  Selection](https://user-images.githubusercontent.com/54576383/68653681-879af200-052c-11ea-891c-7c46176ab4cb.png)
I really need help, it already happened 2 weeks ago, I reported it on isuue #1767 but I did not took screenshots and the issue was fixed a few hours later by itself. Maybe this will help.

**Comment by Vivivane** [comment]
on the screenshots : 
picture 2 : step 1 described, resizing
picture 1 : step 2 described : the random selection

**Comment by photopea** [comment]
Hi Viviane, do you know what that object in the middle is (on the left side of a womans face), around which the transform box appears?

Was it always there or you created it?

**Comment by Vivivane** [comment]
No, I don't. It is not something that I created nor a layer, that is why I cannot remove it.

**Comment by photopea** [comment]
So somebody sent you a PSD and it was already there?

**Comment by Vivivane** [comment]
Hi, not at all, it is a PSD file I created and that I edit every week.
That box is something that is not part of my file.

**Comment by Vivivane** [comment]
As we speak, the issue is no longer existing. But it keeps coming back, causng some delays in my schedule which is problematic...

**Comment by photopea** [comment]
It looks to me as a Path. Can you look into Paths panel (Window - Paths) and tell me, if it is there? You can delete it there, or with a Path select.

**Comment by Vivivane** [comment]
Thanks, that worked but it is only part of the problem. That path does not come from me and appears randomly at the exact same position and shape on different files (from me or clleagues at the opening of them) and disappear later to reappear a few days later.

**Comment by photopea** [comment]
It is not possible. Can you open those files and see, if it is in Paths?

Paths can be hidden, if you disable View - Extras, or View - Show - Paths.

**Comment by photopea** [comment]
I guess the problem was in Paths. I will close it now.
