### ISSUE TITLE
Imported font (Data 70) get's swapped for standard DejaVu font when I type Norwegian Latin characters (ÆæØøÅå)

### ISSUE THREAD

**Issue by SondreVaa** [photopea/photopea#1793]
https://imgur.com/H2yrUgP 

Just noticed this odd bug, not sure if it's just this font, but only one I noticed so far. When I type it works fine, but when I get outside the standard 26 Latin characters it changes to the standard font automatically. I checked another imported font, Futura Bold, and it wasn't present there. 

Then I thought the font lacked those characters, but I loaded it into FontForge and sure enough it was present there. Then Ioaded it into Word and it worked there as well. I eventually just tried changing the text after done writing in PhotoPea, and finally the characters displayed. So it can display, but it just changes on command for some reason. Just thought I'd let you know!

**Comment by photopea** [comment]
Hi, this is a feature of Photopea, when you insert a character, which is not supported by the font, it switches the font to another one (instead of rendering rectangles).

If you think your character is supported by the font, tell us a name of the font, and the character, which causes the font to change, and I will look at it.

**Comment by SondreVaa** [comment]
The font is called "Data 70", and the characters I've tested are, Æ, æ, Ø, ø, Å, å. I've also made sure the characters are present in the library at first, can enclose a photo in the bottom here. Maybe it will happen with these other "irregular" chracters as well, but it's not something I've tested. 

<img width="777" alt="Skjermbilde 2019-11-13 kl  14 20 46" src="https://user-images.githubusercontent.com/46457220/68767463-007b7600-0621-11ea-850c-b96f09f29cea.png">

**Comment by photopea** [comment]
So it is a bit more complex.

For each font, we check, if it supports Latin 1 characters: https://en.wikipedia.org/wiki/Latin-1_Supplement_(Unicode_block) . It has to support at least 70%  of characters.

Then, for each character you type, we check, if it is in Latin 1, and if the current font supports Latin 1. If not, we switch the font.

"Data 70" supports only 65% of Latin 1, so we classified it as unsupporting Latin 1.

**Comment by photopea** [comment]
So I made some Latin-1 characters not mandatory. So, your font now supports Latin 1 by 78%.

I also reclassified all fonts in our database. If you enable Latin 1 font filter, you should see more fonts available.
