### ISSUE TITLE
A similar website, almost exactly the same 

### ISSUE THREAD

**Issue by suruoxi** [photopea/photopea#1794]
https://ps.gaoding.com

Does this website use your APIs? 

![截屏2019-11-1310 54 13](https://user-images.githubusercontent.com/7591860/68729084-ff881b80-0603-11ea-9a1a-4e32d4364929.png)

**Comment by photopea** [comment]
Hi, yes, we are licencing Photopea to this company. Our main site www.Photopea.com is blocked in Chinese internet.
