### ISSUE TITLE
paste not working, clipboard permission granted and computer updated

### ISSUE THREAD

**Issue by lb219** [photopea/photopea#1796]
Hi, I've had a few problems using the paste to paste in images, sometimes when it doesn't work I use another image and it allows me to, but now I can't paste any of the images I want. Neither Ctrl + 
 V works or the manual paste button, and the action does not show up in the history tab. My Chromebook is completely updated and Photopea is allowed to access my clipboard, so I'm not sure what's up!

**Comment by photopea** [comment]
Hi, I just tried Ctrl+V to paste a content from the clipboard and it worked.

So you are saying that whenever you open Photopea and press Ctrl+V, nothing is pasted?

**Comment by lb219** [comment]
Yes, neither the shortcut or manual button is working on Photopea.

**Comment by photopea** [comment]
Photopea does not put images into the OS clipboard. So you need to copy it elsewhere and paste in Photopea. Are you sure it does not work? Can you update your browser?

**Comment by lb219** [comment]
I copy images in a separate document or source and have no problems pasting
there, but I can't paste in Photopea. My browser is up to date.

**Comment by photopea** [comment]
Can you copy an image on some website using right-click - Copy, and paste in Photopea using Ctrl+V ?

What browser do you use?

**Comment by lb219** [comment]
Yes I can copy and paste on other websites but not on photopea. It let me
earlier but now not at all. I use chrome.

**Comment by photopea** [comment]
It really can not believe, that pasting works on other websites, but does not work in Photopea. In that case, I have no idea how to help you.

Can you record a video, where you copy an image somewhere and paste it in Photopea.com ?

**Comment by lb219** [comment]
I have a screen recording where I try to copy and paste both ways, it works
on separate documents, but not on photopea.

https://drive.google.com/file/d/12RtU_oPJ9vVf0KV9IkcpUdLGJfbZ4607/view

**Comment by photopea** [comment]
So you are trying to copy from Google Docs :D You never mentioned it in any of your five messages.

If you copy a regular image (e.g. [here](https://imgur.com/gallery/jGGziXo), right-click the Image, Copy), it should be pasted into Photopea correctly.

Otherwise, I think it is a bug in Google Docs and you should report it to them. There is nothing we can do, as Google Docs are not under our control.

**Comment by lb219** [comment]
Okay, thank you very much.

**Comment by adi3355** [comment]
She,
The same thing happened to me,
I copy a file directly from the computer ..
there is a solution?

**Comment by photopea** [comment]
I think it is a bug in Chrome. I am discussing it with Chrome developers. Have yo tried to drag-and-drop a file into Photopea instead?

**Comment by inletfetch** [comment]
I can't even get copy/paste to work in a single document.  I drag a selection, do COPY, create a new layer, turn off background so I just see empty layer, and do PASTE.  Nothing happens.  Layer isn't locked.  Nothing shows up in history.  I'm sure I'm doing something stupid or making some stupid assumption, but expect simple select, copy, paste to work.

**Comment by photopea** [comment]
Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

In general, we accept only bug reports which happened in a web browser with no extensions. Otherwise, it could be your extension that is causing your problems.

**Comment by Wilbercorvid** [comment]
There's an issue I just kept having recently, and that is that the copy and paste won't work, and even when I have the clipboard read access allowed, it still won't let me copy and paste anything, especially if I have a rectangle select tool. I don't even know what is going on, despite the fact that I always have the clipboard read access allowed.

**Comment by photopea** [comment]
It should be fixed now, just clear your cache.

**Comment by mcmanusslim** [comment]
I'm not able to copy paste when creating a action. When recording yhe action doesn't save the copy or paste in the action during or after recording.

**Comment by CheerfulStormtrooper** [comment]
Hi, everyone. I see this thread has been going on for some time. I too have this problem. I can not copy/paste into Photopea. I can copy/paste everywhere else, just not photopea. Yes, I am copying from Google docs, and I am also using Chrome. I have cleared my cache. It's been mentioned that there are some clipboard permissions, but I haven't found them, however I have observed that copy/paste from other documents and in Chrome does work. Understood that some extensions can cause trouble.  However every browser has extensions of some kind, so to create software that won't work with *any* extensions running is not very practical.  It's also been mentioned that the copy/paste function from Google docs has been fixed. Clearly it hasn't - has any progress been made, or is Photopea looking into this issue? Thank you.

**Comment by photopea** [comment]
@CheerfulStormtrooper could you please make a bug report and fill in all the necessary information? I have no idea what you mean by "copying from Google docs", to try it out myself.

**Comment by CheerfulStormtrooper** [comment]
I'd love to, but I don't know how. There is a lot of discussion in this
thread about "copying from google docs" - what I mean is that the picture I
am copying is in a google doc or google slide. That is something that a
user or Photopea representative asked in the earlier conversation, and so I
included it as possibly relevant.

Sunshine Cowgill [image: linkedin]
<https://www.linkedin.com/company/connectder/>

National Interconnection Manager

805-225-3004 <+1++8057439343>

connectder.com
[image: logo] <https://connectder.com/>

**Comment by photopea** [comment]
Go to www.photopea.com and press "Report a bug" at the top right corner.
