### ISSUE TITLE
Feature Request: Resize without resample

### ISSUE THREAD

**Issue by manticorp** [photopea/photopea#1797]
This should be a fairly easy one to implement.

Currently, it is very difficult using Photopea to change the physical dimensions of an image without resampling.

Photoshop achieves this with a 'Resample Image' checkbox in their image sizing dialog.

When checked off, the Width, Height and Resolution adjustments all affect eachother, so you can change the physical dimensions by changing the DPI easily, or vice versa.

At the moment, if you change any of these settings in Photopea, it will always resample the image unless you very carefully calculate the ratios beforehand (and even then, due to rounding errors it will more often than not resample a tiny amount anyway).

I would love to use Photopea for more graphics work, and I find this to be one big missing feature.

**Comment by photopea** [comment]
Hi, so you want to change the DPI without changing actual pixels? You can go to Image - Image Size, and set a new DPI value.

If you enter a new size in Inches or pixels, but keep the DPI same, it will be resampled (there is no other way).

**Comment by manticorp** [comment]
Yes, I suppose that's one way of doing it.

But let's say I import a photograph, which is currently 72DPI, and it measures some random physical size (e.g. 19.5 x 29.25cm).

I would like to resize the image to 10 by 15cm (a 6x4inch photo print) - at the moment I would have to get out the calculator and do (19.5/10)*72 and enter that in the DPI box, instead of just being able to put 10cm and 15cm in the size boxes.

One thing our customers ask a lot is for image sizing, and being able to point them to Photopea to easily set the print size of their images would be great.

**Comment by photopea** [comment]
Ok, I see and I agree, that we should add a "Resample" checkbox.

But keep in mind, that you still might not be able to make the image have a specific physical size. That's because the DPI should be an integer, and the size in pixels should be an integer. And the physical size is "what's left".

**Comment by manticorp** [comment]
The DPI does not have to be an integer.

In exif data (tags 282 and 283), the DPI is saved as a rational/fraction, e.g:

    exif:XResolution: 721230/10000
    exif:YResolution: 721230/10000

which equals a DPI of 72.123

The numerator and denominator are both unsigned long types, and so a great deal of precision is possible. Although the pixel sizes must be integers, the resolution does not.

I don't know if this is a limitation in Photopea, however?

**Comment by photopea** [comment]
It is true, that in TIFF, the DPI is stored as a rational number. But it also depends on the ResolutionUnit 296 (so maybe it is CM, and will become integer in Inches).

But in a PSD format (the main format for Photopea), the DPI has to be an integer.

**Comment by manticorp** [comment]
Hmm, are you certain? For example, I can save a PSD file with non-integer resolution, and re-open and it will have saved the non-integer resolution, even for numbers like 3141.593DPI (which is 1236.848 pixels per centimetre).

Looking at a few docs online, it's saved as a fixed point number.

E.g.:

https://www.fileformat.info/format/psd/egff.htm

The photoshop API guide confirms it's a Fixed:

https://usermanual.wiki/Document/Photoshop20API20Guide.1445764450/view

Its a LONG type fixed point number of precision 16.

In addition, looking at:

https://github.com/layervault/psd.rb/blob/master/lib/psd/resources/resolution_info.rb

would seem to confirm this.

**Comment by photopea** [comment]
@manticorp Maybe you are right. But Adobe Photoshop does not allow entering DPI values, which are not integers.

**Comment by photopea** [comment]
I implemented the "Resample" checkbox, it should work in an expected way :) the DPI value can be decimal, too.

**Comment by manticorp** [comment]
That's awesome, thank you! Makes this much more usable for me for print files.
