### ISSUE TITLE
OTF font cannot read latin characters

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1798]
Hi!

I was using the font Matiz from photopea library.

I needed to use the áéíóúñ characters, so i made a modification of the font myself.

Here is the file for you to see:
[MatizLatin-Regular.zip](https://github.com/photopea/photopea/files/3848392/MatizLatin-Regular.zip)

Now the characters are on the new font, as i can see on: https://fontdrop.info/
![image](https://user-images.githubusercontent.com/11801254/68891176-1bbcb300-06ff-11ea-99bf-fdaed67ea296.png)

But when trying to tyoe those characters on a text layer on photopea, i get my font changed to DejaVu Sans  :(

![image](https://user-images.githubusercontent.com/11801254/68891055-e2844300-06fe-11ea-9810-3d63527f7bb6.png)

It should read the proper character.

Maybe i am doing somethign wrong?

Cheers!

**Comment by photopea** [comment]
Hi, in Photopea, there can be only one font with a PostScript name. And the default fonts in Photopea database can not be redefined.

Can you maybe change the PostScript name of your font and try it again? Your font editor should be able to do it.

**Comment by avagp** [comment]
I tried again, but now i have a different result.

Here is a video i recorded explaining:


[font photopea.zip](https://github.com/photopea/photopea/files/3852475/font.photopea.zip)

**Comment by photopea** [comment]
Hi Álvaro, I fixed it. 

BTW. if the author of the font has a new version of it, ask him to put it online, and we will update it in our database.

**Comment by avagp** [comment]
You rock Ivan!

BTW, i cannot use space with my modified font  :/

**Comment by photopea** [comment]
Your font seems to have a very small width of the space character :( It looks the same way when I use your font elsewhere (it is not relate to Photopea).

**Comment by avagp** [comment]
True!
