### ISSUE TITLE
Issue with AD

### ISSUE THREAD

**Issue by tsarevs** [photopea/photopea#1799]
advertising crawls beyond its calling and expands to half the work area:
![image](https://user-images.githubusercontent.com/44121511/68928968-79133b80-07b5-11ea-828e-3674bb9eab53.png)

**Comment by photopea** [comment]
Wow, thats awful. How many times did it happen? Was there any way to make it "go back"?

**Comment by tsarevs** [comment]
Hello,

No. This problem showed after +-5 minutes of work in Photopea. To hide the banner I had to refresh the page.

**Comment by photopea** [comment]
You are the only one reporting it, nobody else had this problem before.

Does it happen always, when you use PP for 5 minutes? Does it happen on any other sites? What web browser do you use?

**Comment by tsarevs** [comment]
Issue got when Firefox is updated ( maybe I'm wrong ). Before this PP is working fine.

I used: Windows 10 PRO and Firefox 68.2.0.

PS: I tested PP on my second Computer, where installed Windows 7 and Firefox 68.2.0esr (32-bit). Result: I don't sees Advertising, and PP working fine.

**Comment by photopea** [comment]
So it happens every time you use Photopea, after 5 minutes?

**Comment by tsarevs** [comment]
Yes. In about five minutes. At first I thought that this one of the three banners spreads over the entire page, but no. This is a completely different banner, it seems it was Swarovski

**Comment by photopea** [comment]
Can you open any other website (e.g. Google.com ) and stay on it for 5 minutes? 

Do you have any browser extensions? Can you disable them? Can you scan your OS for viruses and malware? I think many viruses may include ads into webpages.

**Comment by tsarevs** [comment]
Hi,

Now is PP working fine.

BR,
Sergey

**Comment by photopea** [comment]
Ok, let me know if it happens again. And always check, that your problem happens in Incognito mode, too (i.e. it is not caused by browser extensions).
