### ISSUE TITLE
Touch devices suport

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#18]
Hi,

what about support touch gestures  for mobiles, tablets?

**Comment by photopea** [comment]
Hi,
what gestures do you mean? It is possible to do basic things with Photopea on a touchscreen device, but user interface of Photopea requires mouse or some other precise input.

**Comment by Studioartcz** [comment]
Some basic as: zoom, rotation, ...
For bigger screens (tablets) can be photopea usefull with these gestures support.

**Comment by tomasnosek** [comment]
I have the same opinion as photopea. There is no reason to support this on cellphones. Photopea is a pro tool, not aiming on mobile device. But yes, on tablets it may be useful.

To Photopea: Studioartcz probably means he want to do some operations by fingers. For example: You select some layer in panel and you could able to move that selected object by 1 finger or hit some anchor-pont and by moving finger rotate it. Zoom gesture means probably pinch-to-zoom.

**Comment by photopea** [comment]
So I think, that multi-touch controls are not needed now. There are not many people using Photopea with a touchscreen. Current tools (single-touch) should be sufficient for it (Zoom tool, Hand tool).
