### ISSUE TITLE
Mypaint Brush

### ISSUE THREAD

**Issue by ToonzBoom** [photopea/photopea#180]
I would like to see brushes from MyPaint. It will be amazing.
![image](https://cloud.githubusercontent.com/assets/28530944/25812069/d7715c0c-341d-11e7-8578-1374133dbaca.png)

**Comment by JunLao** [comment]
Very good!

**Comment by photopea** [comment]
Are these brushes really popular?  Could the same brushes be stored in the ABR format?

**Comment by JunLao** [comment]
These brushes are very popular. They are used in the program of Krita. And many consider these brushes to be the main competitor of photoshop brushes.
![image](https://cloud.githubusercontent.com/assets/28540251/25819940/3b578808-3438-11e7-8369-651f5b7d6c44.png) 
![image](https://cloud.githubusercontent.com/assets/28540251/25819949/40d689e6-3438-11e7-8373-7373b904890c.png) 
![image](https://cloud.githubusercontent.com/assets/28540251/25819985/60dc0022-3438-11e7-8d3d-aa7d3382b0b7.png)

**Comment by JunLao** [comment]
libmypaint, a.k.a. "brushlib", is a library for making brushstrokes which is used by MyPaint and other projects. http://mypaint.org
https://github.com/mypaint/libmypaint

**Comment by JunLao** [comment]
Format (.myb)

**Comment by ToonzBoom** [comment]
But this will require a separate brush tool. Mypaint Brush. Then you can appreciate all the features of the Software.
![12](https://cloud.githubusercontent.com/assets/28530944/25820942/c5f4d40e-343b-11e7-9b97-165ad5a09c62.jpg)

**Comment by ToonzBoom** [comment]
These brushes are so popular that they are installed in many programs. : Krita, Synfig, 2DPencil, OpenToonz
![image](https://cloud.githubusercontent.com/assets/28530944/25821090/6784fde4-343c-11e7-830d-97fb2b025e3b.png)
![image](https://cloud.githubusercontent.com/assets/28530944/25821297/331c083a-343d-11e7-9725-04c6b7d97a33.png)
![image](https://cloud.githubusercontent.com/assets/28530944/25821393/93c98a22-343d-11e7-8115-15637c327f0b.png)
![image](https://cloud.githubusercontent.com/assets/28530944/25821426/b0ff6418-343d-11e7-8f5d-275197456545.png)

**Comment by Number0001** [comment]
MyPaint Brushes will add? @photopea

**Comment by photopea** [comment]
Are you just one person writing from multiple accounts?

I am not sure about MyPaint brushes. Maybe you could have the same brushes in ABR format. Did you try to find the same brushes in ABR?

**Comment by Number0001** [comment]
There is not one person.

**Comment by photopea** [comment]
It seems like MyPaint uses MYB brush format, Gimp uses GBR, I think that ABR brushes are more general and should be sufficient.
