### ISSUE TITLE
double image paste

### ISSUE THREAD

**Issue by hongsoo-kim** [photopea/photopea#1800]
hi~ there is a problem with the image paste function
1. capture image ( copy image to system clipboard )
2. load image in photopea
3. select area and copy in loaded image
4. create new project
5. paste image(Ctrl + V) in new project

The image from the system clipboard is pasted, not the image copied from Photopia.

ps.
can i size the canvas based on the system clipboard image size when creating a new project?

**Comment by photopea** [comment]
Did you press Ctrl+V in a New Project window? Or you created a new project first?

**Comment by hongsoo-kim** [comment]
I pasted in New Project

**Comment by photopea** [comment]
You can paste only when no window is opened. It will either paste into a current document, or Photopea will create a new document.

**Comment by hongsoo-kim** [comment]
ok i see, thanks your response
However, I'm attached a document for detail explain 
please one more review
[capture image problem.docx](https://github.com/photopea/photopea/files/3856567/capture.image.problem.docx)

**Comment by photopea** [comment]
We are aware of this problem. This will be fixed in a month, when Google releases a new version of Chrome which can handle clipboard images better. https://bugs.chromium.org/p/chromium/issues/detail?id=1004867
