### ISSUE TITLE
Cool editor but needs scrollbars (vertical and horizontal) for zoomed in images

### ISSUE THREAD

**Issue by manake** [photopea/photopea#1801]
Cool editor but needs scrollbars (vertical and horizontal) for zoomed in images like in Photoshop.

**Comment by manake** [comment]
I just discovered "Hand Tool (H)" which I didn't ever use in Photoshop.

So, this issue has low priority then because I can perform this operation.

**Comment by photopea** [comment]
It has been suggested many times, but I still think scrollbars would take too much space from the working area.

You can quickly switch to a hand tool by pressing Spacebar (and releasing it). You can also scroll with a mouse wheel (hold Ctrl to scroll horizontally).

**Comment by manake** [comment]
Yes, please close this, it's all good the way it is.
