### ISSUE TITLE
I was not able to filter layers based on color, type, etc...

### ISSUE THREAD

**Issue by mrillusi0n** [photopea/photopea#1802]
Could you please add a tab to filter layers based on their color, type, etc...?

**Comment by photopea** [comment]
Hi, what do you mean by filtering layers? What exactly is your goal?

**Comment by MichalSZZ** [comment]
It is my project that I worked on today (not exacly that one but quite similar):
![layer-filter](https://user-images.githubusercontent.com/38118273/68980300-62de9d00-0800-11ea-880b-eb8451ea2017.gif)
I have 5309 layers on ca. 80 artbords.
And yes, in Photoshop I MUST use filtering for better workflow.
From time to time I must show eg. only one language variant, that I mark as Orange colour in Layers pallete.  When I create new Layer Comp for easy switching between views I'm filtering by folder name for example. There are many more examples.

**Comment by photopea** [comment]
I understand. I guess this will continue, until Photopea looks exactly as Photoshop :/

**Comment by MichalSZZ** [comment]
In that issue #1771 with that feature I will have a possibility to filter all layers which are text layer, and select all of them and change font family or  color by one click.

Or in big website project I can select all buttons (by the specyfic name - better solution or layer type - shape layer) and which one click change them colour.

**Comment by MichalSZZ** [comment]
> I understand. I guess this will continue, until Photopea looks exactly as Photoshop :/

For me, that isn't nessesary in Photopea to do that. I only try to answear for your question and show how hard projects can be in PS (in that project I discovered how many layers can be max in PSD file :D)

In my proffesionall career I will work on Photoshop all the time probably. But I'm a big fan of Photopea and your very hard work!

**Comment by photopea** [comment]
We have these filter now. Press the "burger menu button" and enable "Filters".
