### ISSUE TITLE
App for Nextcloud and Owncloud

### ISSUE THREAD

**Issue by blackcrack** [photopea/photopea#1804]
Hi,

would be nice if this Webapp works in Nextcloud,Owncloud too :)

best regards
Blacky

**Comment by photopea** [comment]
Hi, I never heard of these :/ Is there a web browser on these platforms? All Photopea needs is a web browser.

**Comment by blackcrack** [comment]
OwnCloud/NextCloud is a Cloud solution for the peoples on a basement, a Webcloud with Mariadb or something and it is free for the peoples : 
https://nextcloud.com/
https://github.com/nextcloud
https://nextcloud.com/install/#more
https://nextcloud.com/install/#instructions-server (Details and Download)

Nextcloud is a branch behind a trouble , the programmer and Founder of Owncloud
was going back to Germany and  have start Nextcloud again because the commercial things in the States was not so free like it should and there was becomes trubles and Nextcloud is started.. that's in Short .. Photopea in the Public is not bad, but behind a Login of an own server it is more save, because no no provider is coming on the datas and the pictures be real safe.

this why it should exist Photopea as a app for Nextcloud too :)
https://apps.nextcloud.com/

so, it is need Photopea only a webserver, so i guess it can run also as a app behind a Nextcloud Login.
Could also become a also mean a breakthrough, as a enhanced Application with a "Plugin for Own/Nextcloud" to make it able to run behind a Next/Own -cloud as safety/security Webapp wheres the data/pictures really more save and saving directly into nextcloud. (and not on a provider space where can take away the pictures for own...) 
There exist a small and more MS-Paint app, but not mature Painting apps like your Photopea, what makes Photopea super as a enhanced Graphic Program for Nextcloud in one Window Gimp style :)

nest regards
Blacky

**Comment by photopea** [comment]
Hi, Photopea does not send any data anywhere. When you use it, all your data stays inside your computer. So "no provider is coming on the datas".

If you understand Nextcloud, coulld you create a Photopea "app" for it? I guess you can just make an iframe, which contains www.Photopea.com inside it.

**Comment by blackcrack** [comment]
no, i can't, this is why i have make a issue..

it send not, if download in the ram and have therewith
the informations on Servers local store, for edit.. 
your program can really easy changed to save a copy of it on local Servers diskspace, automatically.. think about, and this is the reason, why i want have some possible on my private space
behind a loginwall ..

you can close this issue if this not for you relevant.. 
or, you can search or ask by Nextcloud community directly if anyone want help with that ..
to have a app from your program..
best
Blacky

**Comment by photopea** [comment]
I will close it now, as you are the only one who asks for it, so it is probably not that important. All Nextcloud and Owncloud users can use Photopea at Photopea.com

**Comment by iPwnWolf** [comment]
Maybe a little late but I would be really interested as well 😅
I also posted a request in the Nextcloud forum but I think they are really busy right now :/
I think it would only be interesting if it was possible to edit the files on the server directly tho. Otherwise you'd be right that I cloud just use the photopea website.

I just got to know this Project and it is awesome! My guess is that nobody is asking for this right now because nobody knows it would be possible.

**Comment by iPwnWolf** [comment]
I think developing wouldn't be that hard really!
Here is a quick guide on how to set up an app, it's really simple and fast: (first installing nextcloud is required)
https://docs.nextcloud.com/server/latest/developer_manual//app_development/intro.html

The only thing I am not sure about would be the data Access because the app would only make sense if it was possible to open PSD files directly in the browser from the Nextcloud files app. Similar to their onlyoffice or pdf apps.I don't know how Nextcloud or Photopea manage that.

**Comment by photopea** [comment]
I have never heard of the nextcloud and I don't know what it is.

Any person with basic developer skills can integrate Photopea into another product, as described at www.Photopea.com/api

**Comment by gloomytree** [comment]
Nextcloud is an open-source WebDAV based server. You can compare the functionality to Dropbox, Sharepoint and Google Drive. It would be really nice to add my nextcloud server as a datasource, to edit my files directly. 

In the meantime, a user can always select "This Device" and choose a local folder that is being syncronized by the nextcloud client.

**Comment by photopea** [comment]
I have implemented a really "neat" interface for the storages, which you see on the left side. It is really simple to add new storages now, without changing anything in Photopea.

Are you a programmer? Do you know the WebDAV API? Would you be interested into implementing it for us?

**Comment by gloomytree** [comment]
Unfortunately, I am not. I code a few bits here and there, but nothing that requires product-grade skill. I can, however, supply a link to a javascript implementation of WebDAV: [](https://www.webdavsystem.com/ajax/programming/start/)

And I could test, if that helps.

**Comment by photopea** [comment]
I don't think there are that many users interested in this feature. But if someone implements it according to our interface, I can add it.

**Comment by blackcrack** [comment]
Nextcloud is a Webapplication for Apache in Webserver/Linux or an other XAMP 
who be in able to communicate over an application like 
DAVx⁵_4.2.0.2gplay_402000008_at.bitfire.davdroid_24.03.22 162809.apk
or an other exchange Informations over Webdav/carddav and Caldav 
and Interacting with your Phone/Handy, other Side is Nextcloud a Possibility to have a Storage on a Webserver over Webdav, connectable over TotalCommander Plugin (webdav), Over Carrot http://rei.to/carotdav_en.html or https://cyberduck.io/webdav/ 
and the Possibility of Design of your Program, Supports to be in the Net, working on a Picture in the own account and sve it secure in the own Account wothout need to save anywhere, but in the own space .. and if the Spae over a DynDNS at the Own Computer in the basement, and you be in the German States or Frace or Canada or what ever and so on.. connected with your Notebook to you own Computer is this the Savest way to hold your Informations at your own Space.. and this.. this is this is very interesting for a lot of people and make a really pretty huge advertising for your program, if this not alone interesting for you, then i don't know... really ..

Because if this WebProgram as app behind a Login to an own Webspace to be in able to have a Editing tool for grafics behind a Login, it is also in able to creating or editing Pictures anywhere in the World in the own account, pictures where must be in hidden because be ideas, saved ideas or mindemaps where must be changed and so on.. so be your program in the first Possibility to do that if it is a Nextcloudapp behind a login as Save Space for important Pictures.


then adding a couples variables to save in the Users account or edit vom useraccount/ root or open file-search/open Dialog
for the file.. or upload to open and save to "Standart-folder" in the Users space or save/overwrite a file in the User-space

and by side, many big fad Factorys in the Wold (Like german Bosch, Festo also the Big City Stuttgart ) is using Nextcloud from Germany and Opencloud from the States..
And Nextcloud Community updating OpenCloud because under GPL (and therewith lookinable in the code ) and must be in this direction compatible and could be in this possible very be a more startup as only speaks for it self.. ;) Photopea is a really Cool Webapp, but if this be also to have as addon for Nextcloud.. wow.. miammy... would i implement this directly also for my own Cloud in the Server at my basement ... but extra a subdonmain for it.. do i am not need.. there for take i am Gimp and load it up.. to be honest to you...
but if i can work over a Webbrowser, at my own Space... do i no more need my Notebook at the hands, only a Webbrowser at any place, log me in in my account and can do what ever i need to do.. in really saved space , on my own server...
And have only my Handy with me for all Meetings, Datas and Adresses..

To reaffirm it again how important it would be to have for many people.

i guess must not many changed, need only a subdirectory by side of the nextcloud app-informations in an own subfolder
nextcloud/apps/photopea/appinfo
nextcloud/apps/photopea/photopea
nextcloud/apps/photopea/css
nextcloud/apps/photopea/data
nextcloud/apps/photopea/js
nextcloud/apps/photopea/lib
nextcloud/apps/photopea/themplates

@gloomytree , could you maybe ask a couple peoples to help for make a app into nextcloud ?
it could be important to make known this issue-tread...

best regards
Blacky
