### ISSUE TITLE
Why are ads running smoother than the program itself?

### ISSUE THREAD

**Issue by clangamer42** [photopea/photopea#1807]
I was trying to use the lasso tool to crop a image out and it took 10 minutes to load while a runescape ad was running smoothly right next to it, i get your revenue comes from ads but this is getting dumb. is anyone else having a problem or is just me? cause im about to enable my adblocker for this

**Comment by photopea** [comment]
Hi, what exactly was slow? Do you mean a Magnetic Lasso? What is your resolution?

Feel free to enable your adblocker.

**Comment by lumlune** [comment]
My cursor stutters more than once per minute whenever the ads reload.

>Feel free to enable your adblocker.

Feel free to make a serviceable program for non-subscribers.

**Comment by photopea** [comment]
@lumlune I know, that the cursor gets stuck for half a second whenever the ads reload :( But 90% of our income comes from ads, and we would not be able to keep working on Photopea without that money :( Do you have any recommendations about what should we do?

**Comment by photopea** [comment]
I will close it now. I know, that ads may take a fraction of performance (if they reload every 30 seconds, and it takes 1 second, it is 3.3% of performance).

I would recommend buying a Premium account. It costs only 3.33 USD per month (if you buy a 365 day version for 40 USD).
