### ISSUE TITLE
double image paste

### ISSUE THREAD

**Issue by hongsoo-kim** [photopea/photopea#1808]
thanks your response about double image paste issue
However, I'm attached a document for detail explain
please one more review
[capture.image.problem.docx](https://github.com/photopea/photopea/files/3856744/capture.image.problem.docx)

**Comment by photopea** [comment]
We know this, it will be fixed. Now, if you paste for a second time, the image from Photopea will be pasted.

**Comment by hongsoo-kim** [comment]
good~!!,  thank you~
