### ISSUE TITLE
1 px white space at bottom

### ISSUE THREAD

**Issue by anupkum100** [photopea/photopea#1813]
i usually edit 6000*4000 px image but when i upload that for edition it takes 1px white space at bottom and makes it 6000*4001. I have to crop that 1px every-time which is not an easy task

**Comment by photopea** [comment]
Hi, I just tried to open 6000 x 4000 image in Photopea and I do not see any white space. Can you please send us your file to support@photopea.com ?

**Comment by photopea** [comment]
I have to close it because of lack of details.
