### ISSUE TITLE
Compliments, small issue and suggestions

### ISSUE THREAD

**Issue by nlackey** [photopea/photopea#1814]
Hello,

First off, let me start by complimenting and thanking you for this. I use Photopea daily and can't really fault it at all. I do have 2 things to mention, however, and I even feel bad doing so because the product is already awesome and free so who am I to complain?

One thing I miss from using actual Photoshop is scroll bars when I zoom in on something rather than having to zoom back out to move to a different area or use keyboard commands to do same. That may just be me being old-school but I'm used to using scrollbars. Niggly issue.

Secondly, I regularly save my work as I go in case of a power outage or something that may cause me to lose work. I do this with all programs. I find Photopea saves a new PSD each time. Would it be possible to save as the same file? Again, a niggly issue.

None of these issues really take away from my experience and I really appreciate this awesome product.
Have a good day.

**Comment by photopea** [comment]
Hi, thanks!

Scrollbars havebeen suggested many times, but I still think scrollbars would take too much space from the working area.

You can quickly switch to a hand tool by pressing Spacebar (and releasing it). You can also scroll with a mouse wheel (hold Ctrl to scroll horizontally).

In your browser settings, you should be able to change them, to make the browser always ask you, where you want to save a downloaded file, and under what name. In such dialog, you can select the old file to be replaced.

**Comment by nlackey** [comment]
Good suggestions and thanks for the fast reply.

**Comment by photopea** [comment]
You are welcome!
