### ISSUE TITLE
Rotate custom missing

### ISSUE THREAD

**Issue by smartm0use** [photopea/photopea#1815]
Hello, today I discovered this amazing tool, congratulations! It is very useful!

Anyway, I need to rotate a photo by some degree, and I can't see a custom rotate feature.
Can you add it?

**Comment by photopea** [comment]
Hi, you can use a Free Transform (Edit - Free Transform) and enter the angle into the menu at the top.

**Comment by photopea** [comment]
BTW. congratulations to you for discovering Photopea! :)
