### ISSUE TITLE
can i change image save url (server.url) in photopea ?

### ISSUE THREAD

**Issue by hongsoo-kim** [photopea/photopea#1817]
hi~ can i change image save url (server.url) in photopea dynamically ?

**Comment by photopea** [comment]
Hi, are you talking about our API? Why don't you change it in JSON parameters, when you load Photopea.com ? You can make that server URL different for each file that you open (to let the server identify your file).

**Comment by hongsoo-kim** [comment]
Yes, I was talking about the API.
I want to change the save URL or JSON parameter according to the action of the webpage developed by my Plugin so that it can be distinguished  at the Server. How do I change it after load photopea?

**Comment by photopea** [comment]
It is not possible. But Photopea sends the URL of the original file to your server, too, so you can distinguish files by this URL.

You can also execute a script "saveToOE()" after pressing "Save". Then, your webpage will receive a file from the iframe, and you can save that file wherever you want: https://www.photopea.com/api/live

**Comment by hongsoo-kim** [comment]
Thanks. I'll try it

**Comment by photopea** [comment]
I will close it now.
