### ISSUE TITLE
New layer hotkey

### ISSUE THREAD

**Issue by manake** [photopea/photopea#1819]
"Ctrl + Shift + N" and "Ctrl + N" are reserved in Chrome for "New Incognito tab" and "New tab".

Alternative "New layer" hotkey possibilities:

1. Add checkbox in hotkeys window to allow enabling "Ctrl + Shift + N"?
2. Or maybe "Shift + N"? It doesn't do anything in my browser (Chrome).

"New layer" is one of the most popular actions for me so lack of any possibility to have a hotkey is somewhat frustrating.

**Comment by photopea** [comment]
While creating Photopea, we thought these "unusable shortcuts" are just temporary, and browsers will allow us to use them, as they evolve. But now, even after many years of development, the shortcuts are still not available :(

Have you tried to "install" Photopea in More - Install? In that mode, Ctrl + Shift + N works for creating a new layer. Maybe in some other browsers, too.

**Comment by photopea** [comment]
It also seems to work in a fullscreen mode (F11)

**Comment by manake** [comment]
I haven't tried installing it but I will.

1. How about "Shift + N"?
2. Or just making this particular shortcut customizable would be perfectly fine too (perhaps better).

**Comment by GavHern** [comment]
I've also noticed that there are some shortcuts broken on Chromebooks. (For example Ctrl + Shift + Z enables Text to Speech, Ctrl + Alt + T opens the terminal, etc). Virtually nothing you can do about it but I thought I'd mention it since there is a real minuscule amount of people with access to a Chromebook.

**Comment by photopea** [comment]
@GavHern have you tried to install Photopea: More - Install Photopea? do these shortcuts work in installed mode?

**Comment by photopea** [comment]
I will close it for now. I would rather wait until it is possible to implement usual shortcuts, instead of inventing alternative shortcuts.
