### ISSUE TITLE
Error: user_logged_out

### ISSUE THREAD

**Issue by hallworth** [photopea/photopea#1822]
This started to happen today Nov 25, I have been using this software daily for some time with no issues on this front.

I am logged into google with the account that I purchased the 3 month license. It has not run out.
When I 'open with photopea' on drive.

- Photopea window opens
- log into google pop up shows and the disappears
- photopea notification appears showing "Error: user_logged_out"
- file not loaded

I have tried logging out of all accounts, clearing all cookies but still get error.

Is this a software regression?

**Comment by photopea** [comment]
Hi, there is no need to log in to Photopea. If you are logged in in Photopea, can you log out and try it again? I think it is not related to your Photopea account at all.

Did you install Photopea to your Google Drive using these instructions: https://www.youtube.com/watch?v=p7kjmwhlNrA ? Can you remove it from Google Drive and add it back?

**Comment by hallworth** [comment]
Logged out of photopea 
Removed chrome extension
Removed app.

Followed video above
Still happening

![Screenshot from 2019-11-25 15-50-15](https://user-images.githubusercontent.com/10153155/69555711-87264080-0f9b-11ea-80a4-185358ae4323.png)


Files load fine from local so can still work

**Comment by photopea** [comment]
That is so strange :( When I open files from Google Drive, they open in Photopea without any problems.

Do you think any browser extension could cause this? Could you disable extensions and try it again?

**Comment by hallworth** [comment]
Found it - Privacy badger extension stopped it working.
Sorry for wasting your time looking into this.

**Comment by photopea** [comment]
Nowadays, about 90% of problems reported are because of the extensions :D
