### ISSUE TITLE
Downloads as .txt file.

### ISSUE THREAD

**Issue by ratz159** [photopea/photopea#1823]
All methods of download are currently downloading as .txt onto my computer. Is there a way to fix this?

**Comment by photopea** [comment]
Hi, can you update your browser? Can you also try Photopea in Incognito mode?

**Comment by hostlerb** [comment]
I had the same problem and it worked while in incognito mode.  Will I have to be in this mode every time I use the program?

**Comment by photopea** [comment]
@hostlerb there is some browser extension, which renames all files you donwload from the internet.

You can disable that extension, or ask the authors to fix it.

I am shocked, that people use such extensions, without even being aware of what these extensions do :(

**Comment by photopea** [comment]
I will close it now.

**Comment by aidinjk** [comment]
u sure bout that cheif

**Comment by photopea** [comment]
@aidinjk Do you have any problem with using Photopea? What should I be sure about?
