### ISSUE TITLE
Can only crop from top-left corner to bottom-right corner

### ISSUE THREAD

**Issue by GavHern** [photopea/photopea#1824]
I can only use the crop tool going in this direction: ↘

Going in this direction: ↖ causes it to be a 0x0 pixel crop.

**Comment by photopea** [comment]
It is a bit hard to allow this in the current structure. I think it is simpler to learn to use the current crop.

**Comment by photopea** [comment]
It has been fixed - you can draw a cropping rectangle in any direction.
