### ISSUE TITLE
crashes on tablet - MIPAD

### ISSUE THREAD

**Issue by jackiebpunzi** [photopea/photopea#1825]
Tried opening a PSD on my tablet and Chrome crashes... I opened on internal storage and google drive.

**Comment by photopea** [comment]
Hi, does it happen for all PSDs you try to open? Can you open "pea.psd", that is in the middle of a screen?  How large is the PSD, which makes Chrome crash?

**Comment by jackiebpunzi** [comment]
Its okay i already sent a psd file to IVAN. Thanks.

**Comment by photopea** [comment]
Hi, your PSD is 287 MB. You need at least 1.2 GB of free RAM to work with such large file. Do you have so much RAM?

Also, you can try to disable WebGL (More - Use WebGL).

**Comment by jackiebpunzi** [comment]
thank you!

**Comment by photopea** [comment]
I will close it now.
