### ISSUE TITLE
Not receiving api content from photopea to laravel project

### ISSUE THREAD

**Issue by richardgoslingAOS** [photopea/photopea#1826]
When submitting images from photopea to a laravel project we are not receiving any content within the request.

When we attempt to send a call separately using postman the request is received.

Has anyone come across this previously and can recommend any solutions

**Comment by photopea** [comment]
Hi, I am not familiar with Laravel project. Are you talking about "save to server" feature, when you press File - Save in Photopea, and it makes a request to your server with files in a "POST" data?

**Comment by richardgoslingAOS** [comment]
It turns out that a reboot of the server resolved this issue. Closing
