### ISSUE TITLE
Text layers not working

### ISSUE THREAD

**Issue by jelostinthesauce** [photopea/photopea#1827]
Hi - I've been using Photopea for a while now, but lately the text layers don't seem to be working. I can't create visible text - the text boxes are created but when I insert text nothing seems to happen. I've tried using different browsers too. The size and colour of font doesn't seem to be an issue either. I would previously be met with a message 'Font Loaded' when using fonts - but this no longer appears. Any tips?

**Comment by photopea** [comment]
Hi, did you install any browser extensions? Can you try it in Incognito mode?

**Comment by jelostinthesauce** [comment]
Nope no browser extensions - and yes I've tried in both normal and incognito

**Comment by photopea** [comment]
Maybe fonts can not be downloaded for some reason. Do you see any errors in a web console?

**Comment by photopea** [comment]
I have to close it because of lack of details :/
