### ISSUE TITLE
Issues with resizing smart objects with Free Transform Feature

### ISSUE THREAD

**Issue by Shawnee06** [photopea/photopea#1828]
Hello...

For some reason I am having issues with resizing smart objects in PSD files.  For example, here is a graphic that I am trying to replace and use the "Free Transform Feature"...

When I try to select the graphic that I want to replace in the "smart object" area, it wont let me resize the graphic for some reason...

Thanks in advance for your assistance with this issue..

**Comment by photopea** [comment]
Hi, what do you mean by "smart object" area? Smart objects are separate documents, and you can not change their parts from the main document. It is described here: https://www.photopea.com/learn/smart-objects

"here is a graphic" - I can not see any graphic :(

**Comment by Shawnee06** [comment]
Hello there...

Yeppers I totally understand. I've attached a GIF showing you what I am
experiencing with trying to use the Free transform tool in Photopea.com
 Issues with Smartobjects in Photopea.gif
<https://click.api.drift.com/click/3bd56c6b-b67b-4ee1-942a-368bebe6ad9e?u=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F1pEHpuZ4SmJMJggszyl8D_MSZPpjTqEgF%2Fview%3Fusp%3Ddrive_web&h=9740ac3bb39d8cfe663685613b16cf9d>

Regards,


[image: photo]
*Kim George*
Founder, YourChicGeek

kim@yourchicgeek.com

https://yourchicgeek.com
<https://click.api.drift.com/click/617fb73f-6af1-4187-b610-9730f65ec45d?u=https%3A%2F%2Fyourchicgeek.com%2F%3Fd_utk%3D1f2349af-914c-4b54-969e-c388fe43374a&h=44cbf83db9ad09179dd8a6765ce5c002>
| Skype: shawnee0681 <#>
<https://click.api.drift.com/click/8a50c79f-55dc-491b-b2d7-7effaa508643?u=http%3A%2F%2Ffacebook.com%2Fyourchicgeek&h=4be21d865e6b6e66db467518dc8875a9>
<https://click.api.drift.com/click/dd79a150-250e-4061-887c-c439007d0ba5?u=http%3A%2F%2Flinkedin.com%2Fin%2Fyourchicgeek&h=197ea54a325e381ee12880111cb73c7d>
<https://click.api.drift.com/click/8012a916-c3a7-4902-9b6e-e8e40de9b166?u=http%3A%2F%2Ftwitter.com%2Fyourchicgeek81&h=050bed80284708b81fbaf1d612c0289b>
<https://click.api.drift.com/click/af7810b4-eab6-499c-b535-5130b0a4199d?u=http%3A%2F%2Fpinterest.com%2Fyourchicgeek&h=52517edff21dc96c68f6b4959b110c88>
Your Chic Geek How to Design Beautiful eBooks with Canva
<https://click.api.drift.com/click/60460185-3c91-4de2-94b8-efdc7ee3f933?u=https%3A%2F%2Ffeeds.feedblitz.com%2F~%2F587722842%2F0%2Fyourchicgeek~How-to-Design-Beautiful-eBooks-with-Canva%2F&h=94c099f4f0101052ba6ba1d0194ef41c>
Get your own email signature
<https://click.api.drift.com/click/67585302-7d4b-49bc-bfdc-952db4f673b8?u=https%3A%2F%2Fwww.wisestamp.com%2Fsignature-in-email%3Futm_source%3Dpromotion%26utm_medium%3Dsignature%26utm_campaign%3Dget_your_own&h=655d2c9cdb8fcf3ae155c17b938ba459>

**Comment by photopea** [comment]
Wow, that is so weird,

could you send us your PSD file to support@photopea.com ?

**Comment by Shawnee06** [comment]
desktop_workspace_mockup.psd
<https://click.api.drift.com/click/9800fbba-32bb-4c55-9abc-9dcd7b2ffb30?u=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F1OVHXD-WJeIA_xxQpxQ5hDOtyJsJ69r3b%2Fview%3Fusp%3Ddrive_web&h=8e8f540ce997b96f074c8cc91ca65c4c>
Sure thing... heres the PSD file...

Thanks for your help with this...

Regards,

[image: photo]
*Kim George*
Founder, YourChicGeek

kim@yourchicgeek.com

https://yourchicgeek.com
<https://click.api.drift.com/click/5bfdf7cc-643c-444e-983d-cf0b9d17b61f?u=https%3A%2F%2Fyourchicgeek.com%2F%3Fd_utk%3Dafdea3a5-fb03-46db-b977-9cfe1058cac3&h=f4064125ae4c6c9268c82324ad1f18a4>
| Skype: shawnee0681 <#>
<https://click.api.drift.com/click/ad502127-b0f3-441f-8421-d0e66649dbce?u=http%3A%2F%2Ffacebook.com%2Fyourchicgeek&h=4be21d865e6b6e66db467518dc8875a9>
<https://click.api.drift.com/click/979443fc-96c2-4f54-a43f-e37323f15a71?u=http%3A%2F%2Flinkedin.com%2Fin%2Fyourchicgeek&h=197ea54a325e381ee12880111cb73c7d>
<https://click.api.drift.com/click/3ec2c68e-3f07-451d-a51b-5713f018348f?u=http%3A%2F%2Ftwitter.com%2Fyourchicgeek81&h=050bed80284708b81fbaf1d612c0289b>
<https://click.api.drift.com/click/9d5f0567-e846-45fe-83a2-a4f05da89d45?u=http%3A%2F%2Fpinterest.com%2Fyourchicgeek&h=52517edff21dc96c68f6b4959b110c88>
Your Chic Geek How to Design Beautiful eBooks with Canva
<https://click.api.drift.com/click/7341bb99-df6b-45d2-a5a9-a9f052c265dd?u=https%3A%2F%2Ffeeds.feedblitz.com%2F~%2F587722842%2F0%2Fyourchicgeek~How-to-Design-Beautiful-eBooks-with-Canva%2F&h=94c099f4f0101052ba6ba1d0194ef41c>
Get your own email signature
<https://click.api.drift.com/click/1ceb0e95-921d-4ead-a589-57e7d7bbd801?u=https%3A%2F%2Fwww.wisestamp.com%2Fsignature-in-email%3Futm_source%3Dpromotion%26utm_medium%3Dsignature%26utm_campaign%3Dget_your_own&h=655d2c9cdb8fcf3ae155c17b938ba459>

**Comment by photopea** [comment]
I fixed the problem. It should work well now. Thanks for reporting it!

The problem was in a Working Path (press Window - Paths, to see paths in your document). Pasting an image activated a working path, and then, free transform was applied to that path instead of a layer.

**Comment by Shawnee06** [comment]
Yayyy thanks so much for your help on this. You guys are amazingggg 😎
