### ISSUE TITLE
Free Transform issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1829]
Created Work Path with Pen (with Path setting) and then selected rectangle with Rectangle Select tool. Now Menu - Edit - Free Transform not working and showing error see screenshot.
![image](https://user-images.githubusercontent.com/6370548/70046290-016f4a00-15c6-11ea-9ed7-ba1fe42f0583.png)

**Comment by photopea** [comment]
I fixed it. Thanks for reporting it!
