### ISSUE TITLE
Levels - adjusters missing

### ISSUE THREAD

**Issue by NatashaDK** [photopea/photopea#183]
The LEVELS editor have gone mad. 
Please see attached picture file. Missing adjusters... nothing works as it should?

Love from N,
Denmark

![screenshot 2017-05-14 at 20 08 06](https://cloud.githubusercontent.com/assets/27579710/26036632/61310fd8-38e1-11e7-9e9b-b38e7cd5678d.png)

**Comment by photopea** [comment]
Hi Natasha, I am very sorry for not testing it properly :(  I made a quick fix so it works now (without a histogram), I will make a proper fix tomorrow.

**Comment by NatashaDK** [comment]
Thanx, that was quick :-)

Love N

**Comment by photopea** [comment]
I have fixed it completely, with a histogram. Thank you very much for reporting it :)

Btw. it may seem like the number of problems in Photopea is increasing, but actually, it is decreasing :) We become better and better thanks to people like you :)

**Comment by NatashaDK** [comment]
You're welcome ♡
