### ISSUE TITLE
Text Not Showing Up

### ISSUE THREAD

**Issue by alxndrtg** [photopea/photopea#1831]
None of the stock fonts are loading (not showing the Preview), and when I upload custom fonts, they don't show up either. It's been like this all day. Please resolve, I have a deadline to meet.

**Comment by alxndrtg** [comment]
![image](https://user-images.githubusercontent.com/58492721/70098838-3e096880-15fb-11ea-9b2a-4a0410e26fd8.png)
![Screenshot 2019-12-03 at 6 31 01 PM](https://user-images.githubusercontent.com/58492721/70098851-4a8dc100-15fb-11ea-8f75-b087f06df6b7.png)

**Comment by photopea** [comment]
Hi, could you try steps described here? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by alxndrtg** [comment]
None of those work. Same issues in Incognito Mode.

**Comment by photopea** [comment]
What browser do you use? Can you try a different one? Can you try it e.g. on your phone?

**Comment by alxndrtg** [comment]
I tried using a different computer as well. I use Chrome and am unable to try other browsers due to school computer restrictions.

**Comment by photopea** [comment]
What version of Chrome are you using?

**Comment by alxndrtg** [comment]
The latest. I'm on Chromebook. Just updated yesterday.

**Comment by photopea** [comment]
Do you see any errors in a web console? Open a font list, right-click a page, Inspect Element, switch to Console, send me a screenshot of what you see.

**Comment by photopea** [comment]
And does the typing work? Or you can not type the text too?

**Comment by alxndrtg** [comment]
Typing doesn't show up at all. The only error I see is "Unexpected character: '#'"

**Comment by alxndrtg** [comment]
![image](https://user-images.githubusercontent.com/58492721/70101571-55e4ea80-1603-11ea-9741-25269f8fea81.png)

**Comment by photopea** [comment]
It will sound weird, but could you scroll up the Console window? I would like to see that yellow message

**Comment by photopea** [comment]
Are you sure typing does not work in incognito mode?

**Comment by alxndrtg** [comment]
![image](https://user-images.githubusercontent.com/58492721/70145984-3daab500-166f-11ea-8fc9-ca996503ecbc.png)
Yes, I'm sure typing doesn't work in incognito mode. I will try again now to see if things are working again.

**Comment by alxndrtg** [comment]
Things are working now. Thank you.

**Comment by photopea** [comment]
so what was the problem? Was it a browser extension?

**Comment by alxndrtg** [comment]
I'm actually not sure, but the whole website was slow to access yesterday. It may have been an internet issue, though other websites were working perfectly fine.

**Comment by jelostinthesauce** [comment]
I’m still having the same issue but it doesn’t change even with different browser / incognito mode. I can’t open the error console due to administrative restrictions.

**Comment by photopea** [comment]
@jelostinthesauce What browser do you use? Can you update it? Text layers do not work in browsers older than two years.

**Comment by jelostinthesauce** [comment]
I use Chrome, but I’ve tried on Edge and IE too and it doesn’t work either. I wasn’t having issues two weeks ago, so I’m not sure what’s changed. Afaik the browser is up to date.

**Comment by photopea** [comment]
What is the version of your Chrome browser and Edge browser?

Photopea does not work in browsers, that are older than two years. There is no point in testing PP in IE, as it is six years old.

**Comment by jelostinthesauce** [comment]
Ok so this is strange - I opened Photopea up in the same browser at work and the fonts all loaded, no issues. I’ve brought my laptop home and no fonts work, except for the one saves in my .psd file.

**Comment by photopea** [comment]
Hi, what do you mean by "fonts dont work"? Do you mean rendering of the text?

No fonts are saved in PSD files. There are only names of fonts, that are used in text layers.

**Comment by jelostinthesauce** [comment]
The fonts do not load - I’m met with the error ‘Unknown file error: <!--‘

**Comment by photopea** [comment]
That could be caused by some extensions. Can you try it in Incognito mode?

Do you have an antivirus or any other program, that could restrict or censor your internet traffic?

**Comment by dragonism** [comment]
The same thing is happening to me.. it worked yesterday night but then now I can't use the text tool.
![Screenshot 2020-04-23 at 12 27 52 PM](https://user-images.githubusercontent.com/63560008/80130275-f2ca0500-855d-11ea-8b89-1a1dcd40b7d4.png)

**Comment by photopea** [comment]
@dragonism Can you disable all your browser extensions and try it again?

Many people use extensions which break Photopea and other websites. People usually don't know why they use them.

**Comment by dragonism** [comment]
Unfortunately, I am on a school laptop and can not disable my ad blocker and other extensions. But, I cleared my data in [chrome://settings/content/siteDetails?site=https%3A%2F%2Fwww.photopea.com](url) and it worked just fine now.
![image](https://user-images.githubusercontent.com/63560008/80133631-2196aa00-8563-11ea-9b1c-a6d318018466.png)

**Comment by photopea** [comment]
That is very strange. The behaviour of Photopea should not depend on clearing site data.

**Comment by dragonism** [comment]
Maybe it was my internet connection.. I was in my room where the internet connection is the worst and I am currently very close to the router.

**Comment by photopea** [comment]
maybe. when you change a font, photopea needs to download it.

**Comment by MTyson** [comment]
Sometimes it seems that loading the font takes a very long time and displays no message, so it appears that text is not showing.

**Comment by photopea** [comment]
@MTyson have you tried to disable all browser extensions? Some of them could be blocking the download of TTF files (fonts) from our servers to your computer.

**Comment by ddevries1164** [comment]
i am having thee problem where i click the type tool and no prompt appears.  when i type it does nothing but the X and check appears at the top.  i click the check and a type layer appears in my layers palette but no text is indicated in the layer name.  only when i create a text box will it run properly.  this is problematic as i am showing my students how to type on a curved path and i can't use the text box for that.

**Comment by jamo62** [comment]
Please find an actual solution, I'm trying to work on something and text is an important requirement

**Comment by photopea** [comment]
If you disable all your browser extensions, I am 100% sure that everything will work perfectly.
