### ISSUE TITLE
Alternative to ClippingMagic.com

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#1832]
There are many people using www.ClippingMagic.com. It works very similar to Quick Selection in Photopea.

Maybe we could provide a tool with a similar interface (painting with red and green), as we already have the necessary technology.

**Comment by GavHern** [comment]
I've always used [remove.bg](https://www.remove.bg/). They do have an API so it may be interesting to see integration in photopea (but I suppose if you are already in photopea you could just remove the background yourself. Though, that does take a considerable amount of time if you want to do it well...)

**Comment by photopea** [comment]
@GavHern by the way, how much do you pay for remove.bg in a month?

**Comment by photopea** [comment]
We have a Magic Cut tool, it works quite well https://www.photopea.com/tuts/magic-cut-remove-image-background-online/
