### ISSUE TITLE
Smart object editing

### ISSUE THREAD

**Issue by isametry** [photopea/photopea#1834]
Hello,
so Photoshop has the functionality of linked/connected Smart Objects. It has its menu in Layer > Smart Objects, and it’s very useful because you can duplicate Smart Objects many times, and if you edit one, every other instance is edited as well. You can select "Edit Contents" to open the Smart Object layer in another tab, and when you edit it and click Save, all instances in the original file get updated.

So is this on the future roadmap? Currently Photopea _does_ support Smart Objects, but only in terms of lossless transformation and nothing else.

**Comment by photopea** [comment]
Hi, Photopea supports smart objects to the same degree as Adobe Photoshop, for the last four years.

Please, specify, what kind of smart object manipulation you can not achieve in Photopea?

**Comment by photopea** [comment]
You can edit the main file behind the smart object by double-clicking the icon of the layer in Layers panel (in Photoshop and Photopea).

**Comment by isametry** [comment]
Oh, you’re right! Sorry, I was just looking for a section in the Layer menu, didn’t realise there was also a "double click the icon" method.

Do you think you could add one then? For extra clarity? It doesn’t have to be completely like Photoshop’s but just a simple "Edit Smart Object" button shouldn’t be that hard to implement.

**Comment by photopea** [comment]
I added a new option: Layer - Smart Object - Open.

**Comment by isametry** [comment]
Great, thank you!
