### ISSUE TITLE
Second time save is not working

### ISSUE THREAD

**Issue by anupkum100** [photopea/photopea#1838]
When i edit any image and save it, it works fine ... after saving if i keep on editing and save again it does not save

**Comment by photopea** [comment]
Hi, can you try it in Incognito mode (without any extensions)? 

So you press File - Save as PSD, but nothing happens?

**Comment by msollicito** [comment]
Yes  I try to Save as PSD and get nothing - no response

**Comment by photopea** [comment]
Have you tried it in Incognito mode?

**Comment by photopea** [comment]
@msollicito  I see you just ordered Premium, but it still did not work (as Premium only hides ads), and you are asking for a refund on PayPal.

I would like to give you a refund, but PayPal makes us pay a 20 USD fine for each refund. So I am afraid I can not refund you.

**Comment by photopea** [comment]
The user was refunded. I will close it now.
