### ISSUE TITLE
New shape is not snapping to pixel grid

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1840]
1. Zoom in to max limit of the zoom (to see better the problem at the end)
2. Use shape tool (rectangle)
3. Click on the stage (inside of pixel grid)
4. Type new width and height

New shape have semi transparent pixels on the edges (antialiasing)

I think that is a bug becouse, when you are drawing a shape in 100% view, you never know if it has proper (pixel perfect - without comma) X and Y coordinates.

I think, I saw that bug too, when I drawed new rectangle shape manually...

**Comment by MichalSZZ** [comment]
![snaping-to-pixel-grid](https://user-images.githubusercontent.com/38118273/70690810-bfc25b80-1cb7-11ea-8752-a028212fb2a6.gif)

**Comment by photopea** [comment]
I fixed it. Thanks for reporting!
