### ISSUE TITLE
Linked layers duplicating bug (on layers pallete)

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1841]
4 types of duplicating methodes (in layers pallete) - results are different then in Photoshop.

1. Create 2 or more layers
2. Link it togehter by the chain icon
3. Select only one layer 

1st method: ctrl + J = all of linked layers was duplicated
2nd method: drag layer with Alt on the layers pallete = as above
3rd method: drag layer to new layer icon = same result
4th method: RMB on layer and then "Duplicate Layer" = again all layers was duplicated

Photoshop creates duplicates of layers that are only selected (not all of linked).
In photoshop it is only one situation when duplicated are all of linked layers - when I move layers on stage with alt button

**Comment by photopea** [comment]
Fixed! thanks for reporting it.
