### ISSUE TITLE
Thumbnails of Layers with black rectangles

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1842]
![thumbnails-bug](https://user-images.githubusercontent.com/38118273/70666465-fc1d9980-1c6e-11ea-8d4f-ecc983210c28.png)

I saw that few times (not on my computer). Do you know what is the reason?

**Comment by photopea** [comment]
Hi, it is just a black border around the image, that is how we designed our UI design. It should be always there.

**Comment by MichalSZZ** [comment]
@MichalSZZ hmm I think that we are talking about 2 different things :)
 see image below
![obraz](https://user-images.githubusercontent.com/38118273/70716713-23b34700-1ced-11ea-9ee4-55a396203075.png)

**Comment by photopea** [comment]
Oh, I thought these are a part of your layer pixels :D

Can you send me the PSD to support@photopea.com ?

**Comment by MichalSZZ** [comment]
Hi,
I asked person who had that problem, but when she open file next day, the problem wasn't visible any more. 
I saw that few times. On that layers thumbnails there is no shape icon. The black/gray rectangle show up instead.
Could it be a memory issue?

**Comment by photopea** [comment]
It is hard to tell. It never happened to me. Maybe it is related to MacOS and graphic drivers.

I wish you could reproduce it.

**Comment by MichalSZZ** [comment]
That was on PC (last time)

**Comment by photopea** [comment]
I will close it for now.
