### ISSUE TITLE
History brush

### ISSUE THREAD

**Issue by Maxthunderman** [photopea/photopea#1843]
Can you add the History brush tool?

**Comment by photopea** [comment]
Hi, I don't think it is a good idea. It would require remembering the original data of each layer, which would use 2x more RAM. There are not many people who need this feature.

I recommend you to duplicate a layer, before you start working on it (and hide the original, in case you ever need to use it).

**Comment by Maxthunderman** [comment]
Thanks for commenting!

**Comment by DanMarshall909** [comment]
Why not have a toggle in settings? I used to use History Brush all the time in Photoshop.

**Comment by photopea** [comment]
I think nobody uses the History Brush in Photoshop nowadys. It is much more practical to have a copy of your original image in a separate layer.
