### ISSUE TITLE
Android App?

### ISSUE THREAD

**Issue by calclover2514** [photopea/photopea#1844]
I'm surprised this hasn't been asked before, but would it be possible to implement Photopea as an Android app? The latest Chrome mobile makes Photopea unusable on anything but a large tablet, and making it an app would make it much more convenient to use than something like Pixlr.

**Comment by DjovDev** [comment]
Maybe create a smartwatch version too while you're at it?

I wonder how your productivity is on Android.

**Comment by photopea** [comment]
Hi, 15% of our users use Android, 5% use iOS.

What exactly is the problem with Photopea in Chrome for Android? You can press More - Install Photopea, and get an icon to your homescreen, which will start Photopea without a browser UI.

What advantages exactly do you expect from a native Android version, which are not available in this version?

**Comment by calclover2514** [comment]
Chrome seems to be slightly scaling it up by default, though your "Install Photopea" method appears to have gotten it working correctly again. Was this method in the docs? I must have completely missed it.

**Comment by photopea** [comment]
The "Install Photopea" shouls work the same as in a browser. Try to disable your browser zoom. Or maybe you enabled "Desktop view" in your android browser.
