### ISSUE TITLE
Crop Tool Only Works From Top Left Corner

### ISSUE THREAD

**Issue by anonyco** [photopea/photopea#1845]
The crop tool only works when starting from top left corner--similarly to the origin of the HTMLCanvasElement. You should be able to extend the cropped area starting from any corner. This should be a simple fix in the Javascript code.

**Comment by photopea** [comment]
Actually, it is quite hard to implement in our current code. I think it is easy to get used to drawing a rectangle in a specific direction.

**Comment by photopea** [comment]
It has been fixed - you can draw a cropping rectangle in any direction.
