### ISSUE TITLE
Convert to Smart Object and Work Path issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1846]
1. Open pea.psd
2. Create some Work Path
3. Convert layer "background" to Smart Object
4. Undo both steps 2 and 3
5. Convert layer "Welcome" to Smart Object
6. Open Welcome.psd smart object with double click
7. Go to Paths -> There is unwanted Working Path created in step 2!

**Comment by photopea** [comment]
This bug is so creepy :D you delete a path, but it recovers from the dead and refuses to die :D

**Comment by photopea** [comment]
I fixed it.
