### ISSUE TITLE
Empty Text Layer Convert to Shape error

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1848]
Create new project. Create empty text layer - with Type Tool but write nothing there and confirm.
Right click on text layer and select Convert to Shape.
Photopea not working and errors appears in console
->
Uncaught TypeError: Cannot read property 'add' of undefined
    at i.sE.No (pp.js:3807)
    at i.sE.lS (pp.js:3803)
    at Gz.update (pp.js:9470)
    at Gz.Gv (pp.js:9469)
pp.js:9499 Uncaught TypeError: Cannot read property 'uU' of undefined
    at Gz.Zh (pp.js:9499)
    at Gz.Uq (pp.js:9475)

**Comment by photopea** [comment]
I can not reproduce it, so I guess it has been fixed by fixing some other bug.

**Comment by hxim** [comment]
@photopea 
I can reproduce it:
Steps:
1) Open/reload photopea
2) click New Project
3) click Create
4) click Type Tool
5) use Type Tool to make Paragraph Text (make rectangle)
6) confirm with button in top
7) right-click on new text layer in Layers window
8) click on Convert to Shape
9) error appears as seen on screenshot and photopea is frozen

note: If in step 5 you make Pont Text (only click) it will not work either but will show different error

![image](https://user-images.githubusercontent.com/6370548/76498806-e7070100-643d-11ea-8cbf-a0c1e25500a4.png)

**Comment by photopea** [comment]
It should be fixed now, thanks!
