### ISSUE TITLE
I wish PP had an eyedropper tool inside the Color Picker dialog

### ISSUE THREAD

**Issue by NatashaDK** [photopea/photopea#185]
Before PP I used photo$hop on my PC. And I used the eyedropper tool all the time to sample colors from inside dialog boxes.
I gave my PC away... couldn't stand all the constant updates! And now I'm using a Chromebase 24 which have NO updates at all, because the system is run by Google in the cloud :-)
So I switched to PP. And I love your app. It's a godsend, and I use it all the time. Thanx!

Sorry for that long intro... here's my question: would it be possible to implement an eyedropper tool tht works from INSIDE color picker boxes?

Here's a screenshot 
![an eyedropper tool here please](https://cloud.githubusercontent.com/assets/27579710/26072508/055bf152-39ac-11e7-810b-727d27a5ee99.png)

**Comment by photopea** [comment]
I wanted to add this feature a long time ago, but it requires to change the inner structure of Photopea, and I was too lazy ... but you are right, it really should be present in PP :)

**Comment by photopea** [comment]
Let's close it when I add it to PP.

**Comment by avagp** [comment]
Totally. I was about to suggest the same.

**Comment by photopea** [comment]
Dear Natasha and Alvaro, I just added this feature. I am sorry for such a long delay. 

Additonally, standard tools (Move, Brush or any other active tool) do nothing, when some window is open. I hope there is no case, where it could cause problems.

**Comment by NatashaDK** [comment]
This is absolutely great!!! And it works perfectly from inside dialog boxes.
Just what I wanted... it makes my work much, much easier!

**Comment by avagp** [comment]
Great addition! . In fact it probably fixes some issues like when using the
brush tool and I change the tab sometimes it draws on the image and cannot
be undone.

If I trigger it again I will report you back
