### ISSUE TITLE
Photopea doesn't work AT ALL!

### ISSUE THREAD

**Issue by rosealeeloves** [photopea/photopea#1850]
Trying for hours to complete the simplest of commands to achieve the desired effect and to no avail. I have a psd file that's been converted to an xcf. It's a text texture, to be exact. I wish to simply open, edit and move on with my life, but I can get no further than my first layer image. Each time I choose OPEN, then my  '      psd/xcf' file, of choice, the program loads until it glitches and freezes or it loads up the entire pds file, including the help file and such. I AM new to this and may be overlooking something painfully simple, but there seems to be no in depth tutorials out there on exactly how to utilize these files in Photopea, lest it really is as easy as Open, load and edit! Any advice would be very welcome and thank you!

**Comment by photopea** [comment]
Hi, so you are not able to open a specific file in Photopea? Can you try steps mentioned here? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

If it still does not work, can you send us your file to support@photopea.com ?

**Comment by musikBear** [comment]
I tried to open  .RAW files, and the operation fails casting this error:
![image](https://user-images.githubusercontent.com/6662066/70912213-c59ba200-2013-11ea-9e80-8e6b8dcee9ad.png)
This is the File:  
[HeightmapPrimaryOLD.zip](https://github.com/photopea/photopea/files/3968338/HeightmapPrimaryOLD.zip)

**Comment by photopea** [comment]
@musikBear Do you know of any program in the world, which can open your RAW files? If yes, can you send me a screenshot of what they are supposed to contain?

**Comment by musikBear** [comment]
No sorry, i am struggling to find a program, and found yours :p 
That is also why i requested a RAW export option 
The RAW files are heightmap-data for terrain in game-engine, and made from scanned png, then converted on this page :
https://onlineconvertfree.com/convert-format/png-to-raw/
However these RAW-files fails to create any terrain in game engine, that was why i wanted to inspect the content. They are supposed to be rgb grey-scales from 0-255, where 0 is sealevel and 255 is a height controlled in game-editor. The grey scale gradients then results in a perfect realistic landscape. This is the png file that was converted. The RAW file version would be similar, but with higher contrast
![aebleoe](https://user-images.githubusercontent.com/6662066/70914272-ef56c800-2017-11ea-972f-4225baf65dac.png)

**Comment by photopea** [comment]
Your RAW files do not contain the information what is the widht / hight, if it is RGB or Grayscale, how many bits per pixel are there ... Photopea would need to ask you to enter these properties manually.

Why don't you use PNG image in your game directly, instead of converting to this RAW format?

**Comment by musikBear** [comment]
> Your RAW files do not contain the information about the widht / height, if it is RGB or Grayscale, 
Woo.. it does not? Yes then a diolog would be needed it the method should be generalized for any RAW purpose
> how many bits per pixel are there ... 

Sorry should had said 16 bit greyscale. Again a dialog for legal values would be needed
> Why don't you use PNG image in your game directly, instead of converting to this RAW format?

yesss... why not.. Unfortunately that question needs to be aimed at the &///))** publisher (EA) of the engine. Its the *only* option! It must be *exactly* that image-format, and they are the same way all through everything in the process *sigh*

**Comment by photopea** [comment]
The problem is, that internally, Photopea works only with 8bit colors. So you would lose precission when importing 16-bit image. When exporting 16-bit, we can set the remaining 8 bits to zeros. Are you OK with that? 

Can you try to set every odd Byte in your file to zero and see how it works?

**Comment by musikBear** [comment]
> The problem is, that internally, Photopea works only with 8bit colors. 

Oh..
Then no go, we need to find another app. in the end photoshop may be only option
any and all discrepancy from *exact* prerequest, will crash the EA engine. 8 bit to zero wont work either, im afraid.
Thank you for your time and assistance!

**Comment by photopea** [comment]
I think this discussion is not related to the original report, so lets discuss it in another thread.
