### ISSUE TITLE
[Request] Add export-option for RAW-format

### ISSUE THREAD

**Issue by musikBear** [photopea/photopea#1851]
One of the image formats that are most often needed in game-development, is the image-format RAW. This format is used for heightmaps (terrain-data) in most game engines.
It would be a tremendous help for indie-game-developers,  if an online option to various commercial image-editing programs, was available. t.y.i.a.

**Comment by photopea** [comment]
Hi, your raw images from a previous post do not contain even a width or height of the image. Are you sure there are programs for working with these files (except of the game, which uses them, and knows the width and height of each image)?

Why don't you switch to JPG, PNG or BMP, which are more universal?

**Comment by musikBear** [comment]
>Hi, your raw images from a previous post do not contain even a width or height of the image. 

Arhh.. That could be why the RAW-image is rejected by the engine. The one that i would like your App to produce should then have this information. Again it shows that the current options for building RAW files with a free App, is insufficient. Remember that the RAW i showed is made online..
The bit depth expected by EAs engine is 16 bit-greyscale, but a export for RAW in your App, would ofcause need to ne versatile, and cover all legal export formats, through dialogs
> Why don't you switch to JPG, PNG or BMP, which are more universal?

yesss... why not.. Unfortunately that question needs to be aimed at the &///))** publisher (EA) of the engine. Its the only option! It must be exactly that image-format, and they are the same way all through everything in the process sigh

**Comment by photopea** [comment]
I can make Photopea process and export RAW files the same way as Photoshop does. Just give me a moment.

**Comment by photopea** [comment]
I added RAW import and export. It should work the same way as Adobe Photoshop.

Please, let me know if it works as you expect.

**Comment by musikBear** [comment]
! Thank you. That is so kind of you! I think your RAW export is correct, because it does not crash the engine, and everything that is just 'a bit off' causes a crash immediately. 
The RAW imports, and  a surface is indeed created, however -It is with no contours at all. 100% flat at 0 elevation. 
![image](https://user-images.githubusercontent.com/6662066/71108477-77c59c00-21c3-11ea-9cfb-f55251d756ac.png)

I simply cant understand why, but it must be a engine issue
Your RAW looked SO promising:
I was sure that it would be a super landscape
![image](https://user-images.githubusercontent.com/6662066/71108571-a774a400-21c3-11ea-85f7-7a9bc72ed63b.png)

I have NO idea why this fails (yet :)
Again i must say that your swift reply and implementing this export, is one of the best services i have ever had !
Fantastic job! <3
Now i just need to understand this odd behaviour 
If i manage, i will let you know :)
Thanks a LOT for your afford & Mery Christmas !

**Comment by photopea** [comment]
Have you tried to change the Byte Order during then RAW import? There is Big Endian / Little Endian.

Please, send me your RAW file. All RAW files you sent me so far have a constant color (same elevation everywhere).

**Comment by musikBear** [comment]
I have figured it out -sort off, at least ..
For some reason the only area that was inside the map, was sea-surface. The island was outside. That i have to understand why happened, because base-map and heightmap has exactly same dimentiones, but something is wrong. Using a geo-map without sea-surface, gives very different results indeed!
![image](https://user-images.githubusercontent.com/6662066/71116495-8e282380-21d4-11ea-8a77-479f13cd1ce2.png)
That is way to dramatic, but here i think adding a noise-profile to the imagedata, would 'smooth' the edges, and male a better result. Have to experiment with that!
But!
Your RAW-image format is perfect!
It is engines settings that now is needed to be optimized. 
THANK YOU!!
This is the RAW-file that created the landscape above
[HeightmapPrimary.zip](https://github.com/photopea/photopea/files/3980184/HeightmapPrimary.zip)

**Comment by photopea** [comment]
Hi, I fixed several bugs, it should work better now.

Please, let me know if there still is any problem.

**Comment by musikBear** [comment]
Hi! *That* simply fixed the ragged folding of the terrain! Everything look way better!
Great job!
The RAW picture is identical to the geo-data. You have done a marvellous good job!
The *engine* does skew the terrain, in a diagonal'ish way, towards right and down, but that must be possible to solve some way. 
![årøInBFEditor](https://user-images.githubusercontent.com/6662066/71202890-4e793e80-229d-11ea-89e9-7ff7001ed1fd.JPG)
The correct shape from your RAW image : 

![AaroeSatdataMerged](https://user-images.githubusercontent.com/6662066/71203125-b9c31080-229d-11ea-8352-6f621c8994ed.png)

Thank You so much! Mery Christmas!

**Comment by photopea** [comment]
Hi, I don't think any .raw file, that you sent me, corresponds to the PNG images above.

Could you send me the .raw again, together with the parameters (widht, height, etc) or a PNG version?

**Comment by musikBear** [comment]
Ohh I should have thought of that! I have never looked at the exported RAW, as a re-import, I only looked at the resulting height-map. But when i reopen the RAW-file exported from photopea, in photopea, there is serious distortion. I have inserted the two images next to eachother. 
Right : the PNG with the world-data (Aaroe Height Map (Merged).png)
Left : the reimported RAW (HeightmapPrimary.raw)
![image](https://user-images.githubusercontent.com/6662066/71284700-9f536a80-2363-11ea-8524-5349098afed5.png)
As you can see the RAW is mirrored version of the PNG and there is that skew in diagonal towards right bottom (witch because of the mirrored display would be *up left* (?)
I also include a zipfile with poth the geo.data-png, and the RAW-file in the zipfile
[HeightmapPrimary.zip](https://github.com/photopea/photopea/files/3989814/HeightmapPrimary.zip)

**Comment by photopea** [comment]
Hi, when I open your PNG in Photopea and export it as a 16-bit grayscale RAW, I get a different (bigger) file, than the one that you sent me. And that new RAW, when imported to Photopea, looks exactly like the PNG version.

Can you create your RAW with the latest version of Photopea? I think they should work fine.

**Comment by musikBear** [comment]
>  Your PNG is 1081x1081 pixels

Yes i should have told you. I scale the RAW to 1024, because the engine uses heightmaps in 512/ 1024/ 2048  Eg -n^2, so i downscale the RAW at export. That may be a wrong thing to do. I will instead scale the PNG, *before* i open it in photopea, and see it that works better.
I will try that later today, and keep you updated Thanks!

**Comment by photopea** [comment]
You are welcome, Merry Christmas to you too!

At the moment:
- if you open any .raw in Photopea, and save it back as .raw (with same parameters), you should get the identical file
- if you can edit a .raw in Photoshop in a certain way, you should be able to perform the same thing in Photopea, too

Rescaling the image should not have any impact on the quality etc.
I will close this thread for now. Please, let me know if you find any more bugs or missing features.
