### ISSUE TITLE
Not an Issue, Just a suggestion or Request

### ISSUE THREAD

**Issue by DonnaWxnter** [photopea/photopea#1852]
Hello; I just want to say that I am beyond thankful to learn about Photopea, and I've been using it for several months now to make my creations.  I'm beyond thankful that this is available to someone like me. I wanted to make a suggestion.  Can the file size for gifs and pngs or animations be increased please? ^_^

**Comment by photopea** [comment]
Hi, thank you very much! What exactly do you mean by "size for gifs and pngs"? What exactly is a problem?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
