### ISSUE TITLE
Error after saving a color for the 7th time

### ISSUE THREAD

**Issue by VDarvill** [photopea/photopea#1853]
Hello,

English is not my first language so I will try my best to explain the issue I have had. 

I needed to save some Pantone colors for a project at a large format (14000*10000px) so I created the color, I saved a first time at a .png format, everything was fine, I did the same 7 times and I encountered no issue but when I created the 8th color, Photopea stopped working. I have tried several times and always have an issue at the 8th time when I put the color on the 'paper'.

Thank you for your attention and sorry for my English.
Best regards

**Comment by photopea** [comment]
Hi, a layer of 14000 x 10000 pixels requires 560 MB of RAM (4 Bytes per pixel)

Seven such layers require 3920 MB of RAM.

There is a bug in Google Chrome, which does not let websites use more than 4 GB of RAM. I think your browser kills Photopea, when you try to add the 8th layer.

Try to use Firefox instead. Or make the document a little smaller (e.g. 7000 x 5000 pixels).
