### ISSUE TITLE
Text tool don't get center when writing on a shape

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1855]
Here is a video:
[Untitled_ Dec 17, 2019 4_58 PM.zip](https://github.com/photopea/photopea/files/3975208/Untitled_.Dec.17.2019.4_58.PM.zip)

I try to write just in the middle, but the text tool begins a little to the side.

Maybe is a configuration that i am missing?

**Comment by photopea** [comment]
Hi, I tried it with my own path, but I can not reproduce it.

Could you send me the PSD with your path?

**Comment by avagp** [comment]
[Pizza TOP Box (2).zip](https://github.com/photopea/photopea/files/4008806/Pizza.TOP.Box.2.zip)
here

**Comment by photopea** [comment]
I am very sorry, I did not realize, that it happens only when text alignemnt is to the center.

I believe I fixed it, it should work much better now.

**Comment by avagp** [comment]
:D
