### ISSUE TITLE
Stroke of the shape - wrong corners rendering 

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1856]
Stroke of the shape (outside and center)  is bad rendered in Photopea.
Look at this movie below. File genereted in PS and opened in Photopea. 
![shape-stroke](https://user-images.githubusercontent.com/38118273/71035883-c66c2b00-211c-11ea-98d9-e91a8f4ba41c.gif)
[outside-stroke.psd.zip](https://github.com/photopea/photopea/files/3975575/outside-stroke.psd.zip)

**Comment by avagp** [comment]
That also has occured to me. Even if you export it to PDF, for example, it keeps the wrong corners

**Comment by avagp** [comment]
This still happens

**Comment by photopea** [comment]
Fixed! Thanks! :)
