### ISSUE TITLE
path fill color does not wor properly

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1859]
Here i attach a video explaining, and the file i am using.

Cheers!

[Untitled_ Dec 17, 2019 9_19 PM.zip](https://github.com/photopea/photopea/files/3976049/Untitled_.Dec.17.2019.9_19.PM.zip)

[Pizza TOP Caja.zip](https://github.com/photopea/photopea/files/3976056/Pizza.TOP.Caja.zip)

**Comment by avagp** [comment]
I know it is realted to the folder.

If you take the layers from the EAN13 folder, the color will  fill the paths.

**Comment by photopea** [comment]
The folder of layers "EAN13" is actually an artboard (it has two thick lines at the top and at the bottom in the Layers panel). Artboards should not be placed into anothr folders in a PSD file.

Please, make a regular folder in your PSD file, copy layers into it, and remove the current artboard. I fixed it in Photopea: now, you should not be able to put artboards into folders.
