### ISSUE TITLE
Quick Mask Mode issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1861]
During painting with brush in Quick Mask Mode I pressed "Q" to turn off Quick Mask Mode whithout releasing left mouse button. It destroyed/erased part of image where was cursor + when I continued moving cursor it painted with normal brush but around brush cursor it keeps erasing some pixels see on screenshot.
![image](https://user-images.githubusercontent.com/6370548/71179587-c5e4a900-2270-11ea-9895-8d05a1ed7101.png)

**Comment by photopea** [comment]
Hi, I fixed it. It should not switch between the Quick Mask Mode, if the mouse is down.

Thanks for reporting it!
