### ISSUE TITLE
SVG opening problem

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1862]
When I open this svg and place it into current project (as smart object)
https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/410.svg
white "410" text is missing. Works if I open as new project.

![image](https://user-images.githubusercontent.com/6370548/71247311-c5075200-2318-11ea-90cf-9811ea735051.png)

**Comment by photopea** [comment]
It is quite hard to fix it in the current structure. You can double-click the smart object, wait for a re-rendering of the text, and save it back.

**Comment by photopea** [comment]
We should fix it now, as SVG smart objects are becoming more and more popular.

**Comment by photopea** [comment]
I have implemented this feature :) the smart object is rendered with no fonts, but the font download is initiated, and when fonts are loaded, the smart object image is re-rendered with all needed fonts :)
