### ISSUE TITLE
SVG opening problem 2

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1863]
When I open this svg image is not visible at first and I need to increase canvas size or crop to all layers because image canvas is too small initially.
https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/tiger.svg

**Comment by photopea** [comment]
Hi, do you understand the SVG format? Do you know how the dimension should be deduced form this SVG file?

It only contains the attribute height="800" (no width="..."). I changed photopea. If there is only one of width/height available, I set another one to be the same. But I am not sure if it is correct.
