### ISSUE TITLE
I was working on a drawing and site crashed, I lost all my progress D:

### ISSUE THREAD

**Issue by CrazyCorbeau2** [photopea/photopea#1864]
well the title explains it all,

**Comment by photopea** [comment]
Hi, I am very sorry for that. How much RAM do you have? If you have less than 6 GB, try to get more. You can also use a smaller resolution (if you use 4000 x 4000 or higher) or a smaller number of layers.

**Comment by CrazyCorbeau2** [comment]
> Hi, I am very sorry for that. How much RAM do you have? If you have less than 6 GB, try to get more. You can also use a smaller resolution (if you use 4000 x 4000 or higher) or a smaller number of layers.

I'm using a Lenovo Chromebook, can't really find the amount of RAM it has..
