### ISSUE TITLE
After using the navigation panel view can jump completely

### ISSUE THREAD

**Issue by ladal1** [photopea/photopea#1865]
While using the nav view with touchscreen, if you pull your current selection and then try to touch the workspace to work with the image, the whole screen jumps as if you pulled you selection. (or in other words, if you pull the view with touch screen it is not released and then when you try to work it's release way out of the image boundaries)

I couldn't describe the issue correctly so I recorded the issue
https://youtu.be/d-z5nB0uZbI

**Comment by photopea** [comment]
Hi, I fixed it, thanks for reporting!
