### ISSUE TITLE
Can't load ABR File - Unknown file format

### ISSUE THREAD

**Issue by erikw1234** [photopea/photopea#1866]
Hi - I created a really simple brush in Photoshop with the idea to import it into Photopea. 

When I import it under the brush tool (load .abr), I get a message saying unknown file format. I tried different sizes and other variations but I always get the same message.

**Comment by photopea** [comment]
Hi, can you send me the ABR file to support@photopea.com ?

**Comment by photopea** [comment]
I fixed it, thank you for reporting!
