### ISSUE TITLE
Photoshop twin in js - accomplished. What's next? 

### ISSUE THREAD

**Issue by mocomatics** [photopea/photopea#1868]
Hey Ivan, 

big big props for this incredible achievement. I also love that you refrain from monetizing people's data but focus on democratising the access to your creative tool. Really cool.

TLDR;
PhotoPea (or -shop) is a mighty tool the way it's designed. 
But it's not the end. I have some ideas.

- - -

Two thoughts: 
I was always very disappointed that Adobe never went for creating one big tool that incorporates Illustrator, Indesign, Photoshop etc. similar to what's the standard way in 3D programmes like Blender, Maya, Cinema4D or 3DS Max: one core but different views ("workspaces", "layouts"). This lead to slightly similar concepts  behaving differently in each environment "smart object" vs. "masterpage" vs "symbol" etc. and a huge mess of double code and different shortcuts. I assume that there was, and still is, mainly a economical reason behind for splitting the packages. Now, that you're reworking it from scratch, I'd suggest to not repeat the same mistakes :)

The second thought is less defined: 
PhotoPs UI hasn't changed much since the 90ies. If you look around, at "new" software, there's a multitude of interesting concepts already there. From small but powerful pro-user features (eg. hotkeys that trigger pie menus) to more substantial ideas (nodes!). Following your assumed intention of democratising the access to creative tools, one could think of educational versions with UIs of adaptive levels of complexity, depending on the level of experience of the user.

I would love to help building on this:
![EDFvNwJXkAUmhza](https://user-images.githubusercontent.com/1568783/71579535-5a66cb00-2afd-11ea-968c-1ea53a7b7ede.png)

Cheers and keep up the great work,

Moco

**Comment by photopea** [comment]
Hi, thanks for getting in touch! I don't fully understand what you are proposing.

1) Different views / workspaces / layouts: do you mean the user interface, where the buttons would be rearranged, and with different keyboard shortcuts? In Adobe Photoshop, you can rebuild the UI (move menus, buttons, etc) and save each UI, so that you can switch between them.

2) Hotkeys that trigger pie menus - I have no idea what that means. Nodes - I also don't know what it means in terms of a photo editor :/ Could you be more specific?

**Comment by mocomatics** [comment]
Hey Ivan,

1. I meant both UI and UX concepts.
I assumed that you would continue with your work in replacing Adobe products. In that case I wanted to make the point, that Illustrator, Indesign etc. should all live in the same program, so all the metaphors and UI principles continue throughout the different fields.

2.1 "Blender 2.8 now includes pie menus enabled by default for some key features. Pressing the Z-key opens a pie menu with viewport shading options. We also use pie menus now with the tilde key to set the viewpoint.

Because 2.8 makes pie menus a default UI paradigm, it's a good time to review other areas where we might want to use them."

![0yGpH](https://user-images.githubusercontent.com/1568783/71583228-cbae7a00-2b0d-11ea-9071-a7ba36de1105.png)

https://developer.blender.org/T56881

2.2
Node Interface for graphic processing are used in
- many shader programming environments (eg Substance)
- Touchdesigner
- Unity Visual Effect Graph
- vvvv
- in old times: Apple Shake

For example layer adjustments, layer style functionalities and layer merging modes could be presented very intuitively as a chain of effects. This way each step can be visualised separately as a little thumb, items can be easily reused in various occasions (analogous to a "smart object mask") without having to duplicate the item. 

![a5c7995ebd55cf290224c240f9a67656](https://user-images.githubusercontent.com/1568783/71583490-f64d0280-2b0e-11ea-8d2b-ce1a15cf8a74.png)

2.3
My baseline is that PS is UI from a long time ago. Many of the things we take for granted could be quite different and probably optimised for each target audience, be it kids, teachers, professionals.
Since you have a giant userbase already, this could be tested and verified quickly, and that is very exciting.

Cheers,
Moco

**Comment by photopea** [comment]
1) I really don't think that if Adobe put Photoshop, Indesign and Illustrator into one program, it would be a good thing. It is like making a spoon, which is a fork and a knife at the same time.

2) Pie menu: as I understand, it is just placing the items in a cricle, instead of having them in a list (one under another). I don't think it makes that much difference. Also, text description is often better than just an icon.

Nodes - I understand, that many workflows require this kind of the interface, but at I dont think it can be useful or intuitive for a photo editor. It feels like you saw an airplane with nice wings, and you want me to put the same wings on a submarine :/

You have to be more precise with your suggestions. Right now, you are only saying "Photopea must look more like Blender than Photoshop".

**Comment by mocomatics** [comment]
1. I think it's important to specify who we have in mind, when speaking about interfaces. I jumped into writing you a post with the teacher in mind, that commented on twitter. I assume what she does is show teenagers how to get creative with software. Let me try to explain what I mean with the example of vectors:
Since the bezier vector tool got extended into basically a shape tool, with outline properties and fill, Illustrator started to creep into PS. Why not offer all the tools for vector editing right at that moment in the same program, simply offering a few different UI elements? This would be equivalent to hopping from animating objects in a 3D program to modelling or UV editing. Why can I edit vectors within photoshop, but only to some random extent? If you're new to the world of "editing graphics", eg. a kid, this rather random separation of tools probably feels unnecessary. 

2. What I wanted to say is that it's always a good idea to offer different ways of interacting. I didn't mean that you have to replace the UI of PS – what I meant is that there is a lot of space to innovate. 
Regarding the pie menu: The pie menu can become quite intuitive and reduce the distance of mouse movements. Similar to professional PS users that do not even use the mouse at all, when working in Photoshop, only shortcuts. I am suggesting things here, completely from the top of my mind. I am not saying this is the way to go.

3. Regarding nodes: 
I agree, they would only make sense in some parts of photoshop, for example the layer manager.
If you look at a setup like this:
<img width="261" alt="Screenshot 2019-12-30 at 15 15 40" src="https://user-images.githubusercontent.com/1568783/71585547-416b1380-2b17-11ea-9c48-221de8e21aa5.png">

For s.o. who has worked with PS for years, this is all fine. For someone that is new, this is very complex to grasp. My intuition is that with a node interface, this could be arranged way cleaner and intuitive.

Again, I am not providing solutions here. I wanted to know, if you're interested in challenging the PS UI to make it more suitable for new users in the context of teaching.

**Comment by photopea** [comment]
I do not think your suggestions (that you mentioned so far) would make the UI more intuitive, neither for long-time users, neither for new users. I am not a fan of doing something differently just for the sake of being different. I would love to make things more intuitive.

**Comment by photopea** [comment]
I understand, that the UI of Photopea is very complex. But I think you should be aware of all the capabilities and features (i.e. know how to use it), before you try to propose an UI improvement.

It seems like you want to "know how to fly a plane right after you sit into a pilots seat". But many things are really hard to make more intuitive.
