### ISSUE TITLE
Edit and modify skills bar on resume

### ISSUE THREAD

**Issue by whoomp69** [photopea/photopea#187]
Hello,

Totally new to photopea, i really need some help to modify the level of skill on skills bar for my resume.
I'm working on a template which has several of them but i can't manage to find how to modify them.

Thank you.

**Comment by photopea** [comment]
Hi, do you need to modify the text? You should use Type tool, or double-click the layer with the text.

**Comment by whoomp69** [comment]
Hi, 

No I just want to modify the skills levels.
It is a bar 
Like this: 
http://codepen.io/thomasjwicker/pen/vHyui/image/large.png

Thanks for your help.

**Comment by photopea** [comment]
So find the layer with a blue rectangle, click on the layer to select it. Then choose Edit - Free Transform and make it shorter / longer.

**Comment by whoomp69** [comment]
I´ve just tried but it only allows me to set the length and position of the bars on the resume. I can't change the level of skills.

**Comment by whoomp69** [comment]
For example I have a skill bar callled "Wordpress" , and i need to adjust the color of the skill bar to fit my level of competency. Sorry if I am not that clear English is not my best skill. ;-)

**Comment by photopea** [comment]
Maybe there is some program, where you can insert the values of each skill and it will generate the chart image for you.  In Photopea, you will have to do everything manually, which may be complicated.

**Comment by whoomp69** [comment]
Guess i will have to spend more time on it.

Merci.

**Comment by photopea** [comment]
btw, when you have a layer with a blue bar, you can double-click it and change the color in Properties.

**Comment by whoomp69** [comment]
i don't know how to proceed...
