### ISSUE TITLE
Adding new presets

### ISSUE THREAD

**Issue by JoaoPauloAlexandre** [photopea/photopea#1870]
Photopea allows you to create a new document from a set of presets, which is awesome, like Photoshop. 

Is there a way to add presets?

For eg, there isn't a preset for Facebook/Instagram Stories, which have a size of 1080x1920.

![Screenshot_2019-12-31 Photopea Online Photo Editor](https://user-images.githubusercontent.com/6052776/71630305-1dccc980-2bfa-11ea-9835-c20aa219ce90.png)

**Comment by photopea** [comment]
It is quite hard to decide, what should be in these presets, and what should not be there. We do not want to have 500 presets, as it will be very hard to find what you need.

To get 1080x1920, choose FB Event Page (or Screen - FullHD, or Mobile - Samsung S5, or Mobile - Google Pixel). You can swap Width and Height by clicking the button with two arrows (next to the Height field).

**Comment by JoaoPauloAlexandre** [comment]
Your workaround is pretty clever.

Choose New > FB Event Image (1920x1080) and click on the double arrow icon ⇅. This changes it from 1920x1080 to 1080x1920. Done.

Thank you.

![1](https://user-images.githubusercontent.com/6052776/71632912-f7625a80-2c08-11ea-8c0b-a5c52ca98748.gif)

**Comment by photopea** [comment]
FullHD resolution is very popular, and it is used in many cases.

Even in our current presets, some presets are present multiple times under different names.
