### ISSUE TITLE
vectorize dialogue takes very long

### ISSUE THREAD

**Issue by mocomatics** [photopea/photopea#1872]
When selecting "Vectorize Bitmap" the vectorize dialogue appears once a first pass of vectorizing has finished. Depending on the file dimensions this can appear as the app freezing, as nothing happens visually for quite some time (for 6MP on 2019 1,4ghz i5 more than 30s)

I suggest to display the vectorize dialogue first, then start the vectorization progress, including a progress bar, to help the user understand what happens

**Comment by photopea** [comment]
I made it work this way. Also, I added a new checkbox "segmentize", which can be useful when vectorizing photographs.
