### ISSUE TITLE
feature request: keyboard command to fill shape layers and text layers with ALT+RETURN

### ISSUE THREAD

**Issue by mocomatics** [photopea/photopea#1873]
In PS one can fill shape layers and text layers with ALT + RETURN.

At the moment on text layers this triggers a "text layer must be rasterized first"
on shape layers "layer is not editable".

I think it's a nice shortcut, even though it technically is doing different things on each layer.

**Comment by photopea** [comment]
I have implemented it! Sorry that you had to wait for so long.
