### ISSUE TITLE
editing of effects on multiple layers simultaneously not implemented

### ISSUE THREAD

**Issue by mocomatics** [photopea/photopea#1874]
select 2 layers
add Layer Style by clicking on "eff"
select eg. Drop Shadow
only the lowest in hierarchy gets the effect

Should be added to all selected layers.

**Comment by photopea** [comment]
It does not make sense to me. The Blending Options / Layer Style window shows properties of a current layer (e.g. if Drop Shadow is enabled, its size, etc).

If you select two layers, and only one of them has Drop Shadow, should the Layer Style window show the Drop Shadow enabled or disabled? Or what if they both have Drop Shadow, but with different sizes. What size should be displayed in Layer Style window?

You can right-click a layer and choose Layer Style - Copy, right-click another layer, Layer Style - Paste. Or you can define a new layer style in a gallery, and then, choose styles from a gallery, or export a gallery as .ASL file. See here: https://www.photopea.com/learn/layer-styles
