### ISSUE TITLE
feature request: Generate Normal Map

### ISSUE THREAD

**Issue by mocomatics** [photopea/photopea#1875]
I think that would be a very useful one for all the 3D crowds around.

**Comment by photopea** [comment]
Hi, I am not aware of such feature in any image editor.

Could you please elaborate, what is your input, and what you want to get as an output? Maybe add some examples?

**Comment by mocomatics** [comment]
It's been implented in PS since a few years.
Before that, I have used CrazyBump, or Substance.

Here's a simple example implementation without the level of detail adjustments like in PS.
You'll get the idea.
https://stackoverflow.com/questions/10652797/whats-the-logic-behind-creating-a-normal-map-from-a-texture


<img width="767" alt="Screenshot 2020-01-04 at 15 52 29" src="https://user-images.githubusercontent.com/1568783/71767235-50ccd100-2f0a-11ea-9a95-9673c8e0e33b.png">
<img width="1069" alt="Screenshot 2020-01-04 at 15 52 47" src="https://user-images.githubusercontent.com/1568783/71767238-57f3df00-2f0a-11ea-8b58-a1c60a3acb0a.png">

**Comment by mocomatics** [comment]
Another one:

https://www.shadertoy.com/view/Xtd3DS

**Comment by photopea** [comment]
I added the Normal Map filter under Filter - 3D - Normal Map. It has the same parameters as in Adobe Photoshop, producing a similar result.
