### ISSUE TITLE
Can't copy pixels of channel into RGB

### ISSUE THREAD

**Issue by mocomatics** [photopea/photopea#1876]
using a single layer rgb image.

go to channels
select single color channel only (eg R) in channel window
create selection on canvas
copy
select all channels again by clicking on RGB channel
paste

behaviour in PS: 
single channel black and white pixels get pasted
(in multi layer cases: the channel colors of the selected layer)

behaviour in PP: 
rgb pixels get pasted

I guess it's disputable of what's more logical.

**Comment by photopea** [comment]
I see, I made it work this way.
