### ISSUE TITLE
Keyboard Focus is taken by checkboxes

### ISSUE THREAD

**Issue by mocomatics** [photopea/photopea#1877]
Chrome 79.0.3945.88 (Official Build) (64-bit) 
Mac OS 10.15

After having selected a checkbox in the layer window (probably in other occasions, too), keyboard commands are not possible.

<img width="239" alt="Screenshot 2020-01-01 at 23 30 08" src="https://user-images.githubusercontent.com/1568783/71646923-a9278700-2cee-11ea-80bf-15ce70e94185.png">

**Comment by photopea** [comment]
Hi, I fixed it. Keyboard input is still processed, even when a checkbox has focus.
