### ISSUE TITLE
Figma Support

### ISSUE THREAD

**Issue by agazade** [photopea/photopea#1879]
Is it possible to add figma file support as a new feature?
that would be amazing!

**Comment by photopea** [comment]
Hi, why don't you edit Figma files in Figma instead? Figma is on the web and is free to use. I guess it will always handle Figma files better than Photopea.

Does Figma have Sketch or XD export? Photopea already supports Sketch and XD files.

**Comment by agazade** [comment]
> Hi, why don't you edit Figma files in Figma instead? Figma is on the web and is free to use. I guess it will always handle Figma files better than Photopea.
> 
> Does Figma have Sketch or XD export? Photopea already supports Sketch and XD files.

**Comment by agazade** [comment]
Yes, figma is one of the best design tool, but when it comes to export it is limited with PDS and SVG which is not works fine with other tools.
My main purpose of using Photopea is converting other design files to PSD, which works great!

You should definitely check Figma, has API's and support plugins. Maybe you want to add Photopea plugin there :) or Figma file (.fig or online URL) support to your website.

**Comment by rcoenen** [comment]
@agazade are you referring to Figma web or Figma desktop app?

**Comment by agazade** [comment]
@rcoenen i think both are same. Figma is web based tool.

**Comment by photopea** [comment]
I implemented the support for Figma files: https://blog.photopea.com/photopea-4-6-open-figma-files.html

**Comment by rcoenen** [comment]
Beautiful! Amazingly I could verify the correct working from my phone
thanks to the fact that Photopea runs in a mobile browser too!

**Comment by agazade** [comment]
Perfect! Thanks a lot.
