### ISSUE TITLE
When I save it, it saves it as a ".txt" file. It does not save as other file types (PNG, JPG ...).  Why?

### ISSUE THREAD

**Issue by VictoRy977** [photopea/photopea#1880]
When I save it, it saves it as a ".txt" file. It does not save as other file types (PNG, JPG ...).  Why?
![gönderi](https://user-images.githubusercontent.com/59456989/71699035-cdf32b80-2dce-11ea-842b-f87cd62f954f.jpg)

**Comment by photopea** [comment]
Hi, can you try to save a file, while using Photopea in Incognito mode?  Some of your browser extensions may be doing this.

**Comment by VictoRy977** [comment]
The problem fixed when I used it on the Hidden tab. This problem was caused by an extension in the browser. Also I thank you for offering such a program for free.

**Comment by photopea** [comment]
You can report the bug to the creators of your extension. Actually, there are quite many people with this problem.

https://github.com/photopea/photopea/issues/1823
