### ISSUE TITLE
"Image" item on toolbar missing.

### ISSUE THREAD

**Issue by IncognitusX** [photopea/photopea#1881]
see screenshot:
![Screenshot 2020-01-04 at 11 12 19 AM](https://user-images.githubusercontent.com/36338746/71770653-f15bca80-2ee3-11ea-9f10-94f825b3472a.png)

**Comment by photopea** [comment]
Hi, I just checked and it is there in my case :/

Are you using any browser extensions? Today, many people use extensions without knowing what exactly these extensions do.

**Comment by IncognitusX** [comment]
Rechecked and it is back? Sorry for false bug report.


 *Michael Barrett* (m32b64@gmail.com)
