### ISSUE TITLE
Is "auto tone" work proper?

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1882]
I just checked automatic color correction and I think that something works wrong with that functionality.
Can you check that? I even tried with your files showed on Facebook when that options was added to Photopea and it doesn't work for me... (like in 3 images before and after).

Windows 10, PWA Chrome app

**Comment by photopea** [comment]
Hi, yes, it works for me. What exactly happens in your case?

Note, that these features analyze the whole image, before applying the adjustment. If you apply it on "Facebook image" with six images, it will show a different result, than if you apply it on one of these six images separately.

**Comment by photopea** [comment]
![image](https://user-images.githubusercontent.com/15955558/71773667-1d696100-2f61-11ea-892b-ca1b4ab14230.png)

**Comment by MichalSZZ** [comment]
Thanks for the suggestion.
Now i know what was wrong.
I used crop tool before...
In Photoshop there is a checkbox "Delete Cropped Pixels". And after cropping with that option it can analize only that pixels that are visible on the artboard (without using selection Ctrl + A).
Without that it analize whole image (even that pixels that aren't visible right now).

Thanks.

**Comment by photopea** [comment]
Do you think we should have "Delete Cropped Pixels" in Photopea?

**Comment by photopea** [comment]
I will close it for now.
