### ISSUE TITLE
TGA format

### ISSUE THREAD

**Issue by xerxesza** [photopea/photopea#1883]
Hi,

I have a problem, however unsure if it is a Photopea issue.

I play iRacing (car simulator). You can paint the cars. For this you need to prepare TGA files. If I generate a TGA file with Photopea, it does not work (there is no error message or so, simply the paint is not rendered). If I open the same file with GIMP and re-export, it is fine. I add 2 TGA-s. The Gimp one is "good" while the Photopea one is "wrong". 
I cannot see the difference :(

thanks,
aron

[car_289904_gimp.zip](https://github.com/photopea/photopea/files/4023369/car_289904_gimp.zip)

**Comment by photopea** [comment]
Hi, It seems like TGA files should end with a text "TRUEVISION-XFILE.". I just updated Photopea to attach these extra bytes to the end of the file.

Can you export a the RAW file again and try it your game?

**Comment by xerxesza** [comment]
Hi,

thanks a lot for the quick response :)

Unfortunately this seems not to be the issue. I exported the file, the "TRUEVISION-XFILE" is there, but the app still does not recognise. 

I attach 2 files for the same car:

car_289904.tga: This is the file, which is already "accepted" by the app, and is downloaded during initialization.
car_289904_photopea.tga: This is the file I just created.

In the "accepted" tga the TRUEVISION part is missing as well, still it is treated to be a valid file :(

I will open a ticket at iRacing as well. Maybe they can tell me what is missing.... However big companes are usually not that responsive.

thanks,

aron
[car_289904.zip](https://github.com/photopea/photopea/files/4023532/car_289904.zip)

**Comment by photopea** [comment]
I see, the problem is in RLE compression. Photopea may produce runs, which start at one line of the image, and end on another line. I think it is perfectly valid (as all other programs can open TGA files from Photopea).

I noticed, that in your "working" TGA, a run never goes over two lines.

**Comment by photopea** [comment]
I updated the RLE compiler, so that runs do not cross lines.

The resulting TGA files may be 1 - 2 % larger than before, but I think it should fix your problem.

**Comment by xerxesza** [comment]
Wow. Amazing. Thanks a lot! This is working now :)

**Comment by avi8tor61** [comment]
I have an issue I'm trying to help a friend with. I sent him a custom paint .tga a file and he tried to open it with internet explorer.  Now all .tga files try to open with internet explorer by default and as a result he can not see his custom paints in iracing 3D viewer.  Is there some way to set how the .tga files are handled by default in iracing?

**Comment by camoody1** [comment]
This isn't a Photopea question. This is a Windows default file type question. You should ask this question on Reddit in one of the Windows subreddits.
