### ISSUE TITLE
Zeplin Support 

### ISSUE THREAD

**Issue by TIIGRUS** [photopea/photopea#1884]
Is it possible to add Zeplin file and exporting?
For example, how it's done in Photoshop - https://support.zeplin.io/en/articles/1067453-exporting-designs-from-photoshop

**Comment by photopea** [comment]
Hi, what do you mean by a Zeplin file? Do you have any such file to show us?

As far as I understand, you are supposed to make PSD in some editor (Photoshop, Photopea), and then, transfer them to Zeplin. But you are talking about making something in Zeplin and opening it later in Photoshop / Photopea?

**Comment by TIIGRUS** [comment]
> Hi, what do you mean by a Zeplin file? Do you have any such file to show us?
> 
> As far as I understand, you are supposed to make PSD in some editor (Photoshop, Photopea), and then, transfer them to Zeplin. But you are talking about making something in Zeplin and opening it later in Photoshop / Photopea?

Sorry for my English. 
I would like to open psd in Photopea and then export it to Zeplin, as it was done in Photoshop.

**Comment by TIIGRUS** [comment]
The principle as in the link above.

**Comment by photopea** [comment]
Zeplin made a plugin for Photoshop. I don't know if they will make a plugin for Photopea.

You can open PSD from Photopea in Zeplin manually, without plugin, right?

**Comment by photopea** [comment]
Also, you can press Window - CSS, to see a CSS code in Photopea. Is there any Zeplin feature that you miss in Photopea?

**Comment by TIIGRUS** [comment]
> Zeplin made a plugin for Photoshop. I don't know if they will make a plugin for Photopea.
> 
> You can open PSD from Photopea in Zeplin manually, without plugin, right?

yes, you're right, i need a plugin. I can not open psd in zeplin.

**Comment by photopea** [comment]
I am afraid we can not make such plugin for Photopea. Zeplin does not offer any interface to do it.

But if you want, we can add Zeplin features to Photopea.

**Comment by TIIGRUS** [comment]
> But if you want, we can add Zeplin features to Photopea.
It would be great! Thanks for the quick answers!)

**Comment by photopea** [comment]
What feature exactly do you miss?

**Comment by TIIGRUS** [comment]
> What feature exactly do you miss?

**When hovering over the mouse, it shows the sizes and indents**
![image](https://user-images.githubusercontent.com/11195373/72064964-bf80a480-32e5-11ea-8739-cf0a2d2fe841.png)

**Comment by photopea** [comment]
When you have a Move tool, enable "Distances" at the top menu.
![20031753_1876760662585013_803679735303928482_n](https://user-images.githubusercontent.com/15955558/72065329-45005680-32de-11ea-800d-436f77c9c455.png)

**Comment by TIIGRUS** [comment]
> What feature exactly do you miss?

**Quickly select text and copy, click on the field and copy to clipboard**
![image](https://user-images.githubusercontent.com/11195373/72065316-a0364700-32e6-11ea-85c0-5f668d2e76e1.png)

**Comment by TIIGRUS** [comment]
> When you have a Move tool, enable "Distances" at the top menu.
Nice! Thank you!

**Comment by photopea** [comment]
Quickly select text: Press T for a Type tool. Tripple-click the text and press Ctrl+C.

**Comment by TIIGRUS** [comment]
I understand that these are two different programs, but if it is impossible to export from Photopea in Zeplin. It would be great to be able to create a style guide.

![image](https://user-images.githubusercontent.com/11195373/72066577-a4179880-32e9-11ea-9994-6d7d40006eb5.png)

![image](https://user-images.githubusercontent.com/11195373/72066630-c6111b00-32e9-11ea-86b4-78335e4e569b.png)

![image](https://user-images.githubusercontent.com/11195373/72066682-e5a84380-32e9-11ea-91a4-5e82993d9d31.png)

**Comment by photopea** [comment]
Ask Zeplin to create a plugin for Photopea, or allow you to upload a PSD file to Zeplin directly.

**Comment by TIIGRUS** [comment]
> Ask Zeplin to create a plugin for Photopea, or allow you to upload a PSD file to Zeplin directly.

Ok, thank you so much!

**Comment by mubeenfayyaz20** [comment]
Hi Photopea

**Comment by mubeenfayyaz20** [comment]
i need some help can you tell me how I can export Photopea PSD and upload into zepline
