### ISSUE TITLE
Login using github error

### ISSUE THREAD

**Issue by dwbmb** [photopea/photopea#1886]
After I complete login procedure using github account, I get this error message:

> array(3) { ["result"]=> array(31) { ["login"]=> string(5) "dwbmb" ["id"]=> int(59622256) ["node_id"]=> string(20) "MDQ6VXNlcjU5NjIyMjU2" ["avatar_url"]=> string(53) "https://avatars3.githubusercontent.com/u/59622256?v=4" ["gravatar_id"]=> string(0) "" ["url"]=> string(34) "https://api.github.com/users/dwbmb" ["html_url"]=> string(24) "https://github.com/dwbmb" ["followers_url"]=> string(44) "https://api.github.com/users/dwbmb/followers" ["following_url"]=> string(57) "https://api.github.com/users/dwbmb/following{/other_user}" ["gists_url"]=> string(50) "https://api.github.com/users/dwbmb/gists{/gist_id}" ["starred_url"]=> string(57) "https://api.github.com/users/dwbmb/starred{/owner}{/repo}" ["subscriptions_url"]=> string(48) "https://api.github.com/users/dwbmb/subscriptions" ["organizations_url"]=> string(39) "https://api.github.com/users/dwbmb/orgs" ["repos_url"]=> string(40) "https://api.github.com/users/dwbmb/repos" ["events_url"]=> string(51) "https://api.github.com/users/dwbmb/events{/privacy}" ["received_events_url"]=> string(50) "https://api.github.com/users/dwbmb/received_events" ["type"]=> string(4) "User" ["site_admin"]=> bool(false) ["name"]=> NULL ["company"]=> NULL ["blog"]=> string(0) "" ["location"]=> NULL ["email"]=> NULL ["hireable"]=> NULL ["bio"]=> NULL ["public_repos"]=> int(0) ["public_gists"]=> int(0) ["followers"]=> int(0) ["following"]=> int(0) ["created_at"]=> string(20) "2020-01-07T19:11:39Z" ["updated_at"]=> string(20) "2020-01-08T14:12:49Z" } ["code"]=> int(200) ["content_type"]=> string(31) "application/json; charset=utf-8" } Photopea didn't receive your name.

**Comment by photopea** [comment]
It means you have to enter a name in your GitHub settings. As you see, we received ["name"]=> NULL

**Comment by dwbmb** [comment]
Yeah, sure, but the blank page with this content is not the best way how to tell users, is it?

**Comment by photopea** [comment]
What should we show instead?  There is a message at the end "Photopea didn't receive your name.".

**Comment by dwbmb** [comment]
I did not even read to the end, when it starts with "array(3) { ["result"]=> array(31) { ["login"]=> string(5) ". I wanted to try edit some pictures, I am not a developer, text like this is too scary for me.

**Comment by photopea** [comment]
You are right, I changed the message, it should be clearer now :)
