### ISSUE TITLE
Suggestion: Add Letter size to the print menu

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1887]
It is just that.

If you can please add Letter size (279x216mm) and double Letter (432x279mm) to the print options  :)

![image](https://user-images.githubusercontent.com/11801254/71997195-3fdad300-321c-11ea-8988-3766d90f9c0d.png)

**Comment by photopea** [comment]
Hi, I added these new two sizes. I found, that their names are "Letter" and "Ledger", and their sizes are in Inches, as they are used mostly in americas.
