### ISSUE TITLE
Brush tool problem

### ISSUE THREAD

**Issue by NatashaDK** [photopea/photopea#189]
Please try this: 

Open a new document...
Choose the Brush tool and choose a color, and paint something...

Open the Brush Palette and change the size of the brush...
Paint something...

now pres Ctrl + z to undo your last paint strokes...

NOW the circle-round cursor changes to a magnifying glass, and pressing the mouse zooms the page ???

**Comment by photopea** [comment]
Hi Natasha,  I can not reproduce it by following your steps :(

Ctrl + Spacebar  switches to Zoom tool from any other tool. But after you release the Ctrl and Spacebar, the previous tool must return.

Are you using a Chromebook? There are some issues with the keyboard on Chromebooks.

**Comment by NatashaDK** [comment]
Yes, I'm using a Chromebook. Ctrl + Spacebar doesn't seem to zoom on a Chromebook. I zoom by pressing the Alt key and scroll with the mouse.

**Comment by photopea** [comment]
Maybe it has nothing to do with Chromebooks ... pressing Z (without Ctrl) always switches you to the Zoom tool from any other tool. So maybe you just pressed Z without Ctrl (or you pressed Ctrl after pressing Z)? 

Each tool has its key (e.g. B for Brush, E for Eraser, C for Crop ...) so you can switch tools directly from the keyboard. Leave the mouse cursor over the tool icon for a short time, there will be a bubble showing you the name of the tool + its key.

**Comment by NatashaDK** [comment]
Yes, I know the shortcuts, adapted from photoshop, very good. 
I just discovered something  :-)
If I keep pressing the Ctrl key while I press the z key, and then let go of the Ctrl key, while stille pressing the Ctrl... it is working :-)

So, maybe I'm a little too fast with my fingers. I just did what I used to do in Photoshop when I had a PC.

**Comment by photopea** [comment]
So try this:  choose the Brush tool and draw something.  Now press Ctrl, press Z, release Z and release Ctrl. It should take you one step back. Does it work?

In Photoshop, if you press Z before pressing Ctrl, it will also switch to the Zoom tool.

**Comment by NatashaDK** [comment]
That was jast what I tried to explain in my posting above :-) But you are describing it more simple, thanx. And it works perfectly that way !!

**Comment by photopea** [comment]
ok, I am glad that it works :)

**Comment by NatashaDK** [comment]
ok, I am glad that it works :)
Thank you very much for your excellent support. And please excuse me for taking up your valuable time with this. I should have fixed it myself.
Have a really nice evening,
Love from Natasha
... 

    Den 18:34 mandag den 22. maj 2017 skrev Photopea <notifications@github.com>:
 

 ok, I am glad that it works :)—
