### ISSUE TITLE
Rasterize Layer Error

### ISSUE THREAD

**Issue by felipeballesteros** [photopea/photopea#1892]
When doing File > Export As > PDF
there is a dialog window that provides some options to save the file, when I selected 'Rasterize text', the text layers sometimes will not display properly, in my case some text field was being overwritten with another

**Comment by photopea** [comment]
Hi, I have never seen such issue, and I can not reproduce it with any files that I have.

Could you send us your document, for which it happens, to support@photopea.com ?

**Comment by felipeballesteros** [comment]
I will try to replicate and send something soon. Thanks!!

**Comment by photopea** [comment]
I have to close it because of lack of details :/
