### ISSUE TITLE
Images from Gallery (pixabay.com) not loading

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1895]
When clicked on Gallery icon and some image it stays on Loading forever. Seems to be blocked by CORS policy. In console it says this:
`Access to XMLHttpRequest at 'https://pixabay.com/get/52e7d44…_1280.jpg' from origin 'https://www.photopea.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by photopea** [comment]
I think I fixed it. Thanks for reporting!

**Comment by Benoit1980** [comment]
> I think I fixed it. Thanks for reporting!

How did you fix it please? I have the  exact same issue when trying to download the images from a get request. Thanks

**Comment by photopea** [comment]
@Benoit1980 Do you mean you can not open a template in the "New Document" window? Is https://pixabay.com/ blocked by your internet provider?

**Comment by Benoit1980** [comment]
Thanks for the reply.

No I meant that when I pass a request(API call), I get the response ok, but as soon as I try to download the file via vue(front end), I get the warning you mention above. I cracked it tonight but not the way I wanted..... I had to pass the file path from pixabay back to Laravel, copy a copy of the file to the system file and then serve the file back to the front end.....I could only get it to work this way. But this means that each time I will have to make a copy of the file request. From what I understand, it is what Pixabay wants(24 hours cached requests).

**Comment by photopea** [comment]
So your problem is not related to Photopea?

I don't remember how I fixed it, it was over a year ago :( Maybe use a different URL of the image, which has CORS set?

**Comment by Benoit1980** [comment]
> So your problem is not related to Photopea?
> 
> I don't remember how I fixed it, it was over a year ago :( Maybe use a different URL of the image, which has CORS set?

Oh sorry I thought this was a Pixabay API, my apology :-) I fixed it by getting the images from the PHP side rather than the front side, all good. Thanks again!
