### ISSUE TITLE
"GPS" Parameters metadata problem

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1896]
After I added all "GPS" Parameters to metadata with File - File Info ... dialog photopea behaves weirdly and when I attempt to save image to PSD it does not work and shows error "Uncaught e" in console see screenshot...
![image](https://user-images.githubusercontent.com/6370548/72372169-277c2400-3706-11ea-960b-a362f57d0ea0.png)

**Comment by photopea** [comment]
I am very sorry, it is fixed now. Thanks!
