### ISSUE TITLE
File Info dialog problem

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1897]
In File Info when I press Add Parameter too many times until there is no more parameters to add it shows this error and stops working photopea properly...
Uncaught TypeError: Cannot read property '0' of undefined
    at Da.$k (pp.js:7848)
    at sM.LS.H (pp.js:9)
    at sM.PR.H (pp.js:6578)
    at sM.Kr (pp.js:6733)

**Comment by rcoenen** [comment]
Confirmed. Low priority issue I guess, more a warning type message. it does not seem stop any functionality of Photopea from working correctly.
![image](https://user-images.githubusercontent.com/753704/72689735-92e93b80-3ae2-11ea-89a5-38649b5f1ea4.png)

**Comment by photopea** [comment]
I fixed it, thanks for reporting!
