### ISSUE TITLE
Open and placing a pdf does not bring the text with it

### ISSUE THREAD

**Issue by stingray4540** [photopea/photopea#1898]
I have a map with images and text in PDF format. When I try to insert the map into photopea, only the image parts of the map open, all of the text is missing
[MAP5_2017.pdf](https://github.com/photopea/photopea/files/4062696/MAP5_2017.pdf)

**Comment by photopea** [comment]
Hi, this is a shortcoming of our current PDF import feature. Please, double-click the thumbnail of your PDF layer (smart object layer) to open it separately, wait for the fonts to load, and save it back.
