### ISSUE TITLE
Can't Login With GitHub Account

### ISSUE THREAD

**Issue by BackYardChickens** [photopea/photopea#1899]
Tried to login with GitHub and got an error:

"Photopea didn't receive your name. Please, enter the missing parameters at your GitHub account."

... and below that a TON of code like:

array(3) { ["result"]=> array(31) { ["login"]=> string(16) "username" ["id"]=> int(35995333) ["node_id"]=> string(20) "MDQ6VSDXNlcjUTUwODMz" ["avatar_url"]=> string(53) "https://avatars1.githubusercontent.com/u/59944833?v=4" ["gravatar_id"]=> string(0) "" ["url"]=> string(45)....

etc. etc. etc.

**Comment by photopea** [comment]
Hi, you should set your name in your GitHub profile. Just go to Settings, the Name field will be in front of you. Also, it has been reported here about 10 times :D 

![image](https://user-images.githubusercontent.com/15955558/72510849-7206b900-384a-11ea-9186-28b16c65a533.png)
