### ISSUE TITLE
save doesn't work in safari

### ISSUE THREAD

**Issue by vmikhaylova** [photopea/photopea#19]
safari save file after editing is completely f*cked.

**Comment by photopea** [comment]
Hi, I don't have a Mac computer and Safari does not exist for other OS. I will try to get to some Safari to see what's going on.

**Comment by photopea** [comment]
Hi, Photopea should work now, but you have to enter the name of the file manually. We must wait, until Apple implements "donwload" attribute in Safari for more convenient download:  http://caniuse.com/#feat=download

**Comment by DevBadger10** [comment]
Safari appears to support it now.
