### ISSUE TITLE
Can't work with a PSD file loaded from my computer. Chrome, FF.

### ISSUE THREAD

**Issue by DaggLo** [photopea/photopea#190]
Everything was fine a few days ago. But now when I'm trying to open a PSD file from my pc nothing happens. Only the default menu is avaliable and some pop-ups about the fonts loadings apear but nothing else.

I've tried in Firefox and Chrome Canary.

**Comment by photopea** [comment]
Hi, can you attach some of your files, that can not be open?  Were you able to open them before?

**Comment by DaggLo** [comment]
Hello,
yes everything was excellent earlier.

http://file.sampo.ru/kws8g4/

**Comment by photopea** [comment]
Hi, I am very sorry, it was fixed and it works now.  Thank you very much for reporting it. Let us know if you have any other problems in the future.

**Comment by DaggLo** [comment]
Yep, everything works fine now. Thank you for your work.
