### ISSUE TITLE
UX issue: Click to dismiss paints into the image

### ISSUE THREAD

**Issue by rcoenen** [photopea/photopea#1900]
Please fix this issue with the current UI menu system: Clicking to dismiss a menu paints into the image.

**How to reproduce**
1) Select a paint brush, colour red, size somewhat big for clear visibility so that 1 click will leave a clear red dot
2) Open a menu
3) Click outside the menu to dismiss. Make sure you click outside the menu but somewhere into the image
4) Expected result: menu gets dismissed (closes) and image is not altered / affected.
Actual result: menu gets dismissed but there is now a big red dot in the image 

**Screen-recording to illustrate above case:**
https://www.youtube.com/watch?v=eJMbAX2GpZo

**Comment by photopea** [comment]
I am not sure if it is really an issue.

Some people may want to start painting right while a menu is opened, i.e. click just once instead of twice.

If you open a context menu (right-click) in any program (e.g. in a web browser), and click into the program (outside the context menu), the action is performed, as if there was no context menu.

**Comment by rcoenen** [comment]
The way how it's implemented currently in Photopea goes against standard UX
conventions. No other editor works this way. I find myself constantly
closing a menu by clicking outside of it (as is the custom on virtually
every other desktop app with a menu system ever) on both Mac, PC and Linux.
And this is also how it works in Photoshop for example. It's an annoyance
having to remember that Photopea works different, for no clear reason.
The use case you mentioned about wanting to directly paint is not a legit
one. Nobody wants to paint just a dot even browsing menus. If you can't
find what you're looking for in the menu, you want to dismiss the menu
first and foremost- not dismiss the menu AND paint a red dot.

**Comment by photopea** [comment]
I see the latest version of Photoshop really works this way. However, e.g. the web browser lets you click the link even when a context menu is opened.

I made Photopea hide the context menu before performing a mouse action in a document, as you asked.

**Comment by rcoenen** [comment]
Awesome thank you! 💪

**Comment by rcoenen** [comment]
I just tested it, works great. Amazing how this change is already available only a couple of hours after I requested the change. This surely shows the power of cloud based apps!
