### ISSUE TITLE
PWA enhancement: Add open recently used files to "File" menu

### ISSUE THREAD

**Issue by rcoenen** [photopea/photopea#1902]
Workflow enhancement request: Add open recently used files (last 5 used) to the "File" menu
![image](https://user-images.githubusercontent.com/753704/72671123-995cb200-3a13-11ea-8261-eb275b256d19.png)

**Comment by photopea** [comment]
Websites can no do it at the moment.

Many browsers / extensions try to prevent websites from even detecting, that you ever used it in the past (to prevent "tracking" etc). So I think the whole industry is moving in a completely opposite direction.

**Comment by rcoenen** [comment]
This was not a request for the web version but a PWA specific optimisation.
I suppose this might be related to the availability of the native
filesystem API

**Comment by photopea** [comment]
The PWA is still a website, it only tells the browser to start it without the browser UI, but everything else is 100% identical.

**Comment by rcoenen** [comment]
I know this is true from a pure technical perspective. But another way to
look at it is to compare the Photopea website with Adobe Flash (the
in-browser plug-in) and the PWA Photopea with Adobe Air (essentially Flash
running in a desktop/smartphone container) giving Flash access to operating
system features like the filesystem, clipboard and other OS native
elements. It appears to me that PWA is moving in that direction too,
allowing for a PWA Photopea version which is optimised for desktop use and
less of an in-browser/web version.
