### ISSUE TITLE
PWA enhancement: Save file instead of download

### ISSUE THREAD

**Issue by rcoenen** [photopea/photopea#1903]
**Workflow improvement request:**

Please enable the PWA version with direct file system access, so that you can open a .PSD in Photopea, work on it and then simply hit "Save" to write the changes back to disk into the same file.

Currently I cannot do this and Photopea downloads a new .psd file every time. This is rather annoying when making changes, having to rename the file and replace the original one.

**Comment by photopea** [comment]
Hi, I am afraid it is not possible at the moment. Websites can not rewrite files in your computer just like that.

But it seems a solution will be available soon, at least in Chromium-based browsers: https://web.dev/native-file-system/

**Comment by rcoenen** [comment]
Yeah this would do the trick. In general, are you interested in adding
features specifically for the PWA version to make it act more like a
regular desktop app and less like a web app?
From a workflow perspective it could be very beneficial to add some
functionality to integrate PWA Photopea closer with the operating system.
Drag n drop files. Shared clipboard. File system access for opening/saving.
Use Photopea as default app. Etc.

**Comment by photopea** [comment]
PWA is still just a regular website, which is opened without a browser UI.

We can do only things, which web standards and web browsers allow us to do. The idea of the web (the "W" in PWA) is to have a unified environment and don't care about operating systems at all.

**Comment by photopea** [comment]
E.g. when developing Photopea, we test it only in two browsers and one OS. However, it is used in many more browsers and operating systems (in which we never tested it). That is the beauty of the web.

**Comment by rcoenen** [comment]
See previous comment on Flash Vs Air. Adobe Air essentially added
abstracted OS APi access to Flash (Flash bring a pure browser based
experience). But from a Dev perspective you wouldn't need to worry about
which exact operating system the Air version was running on: if you'd
implement filesystem access to your app you'd do so through the Air API. It
would then always work no matter where the app was being used: Window, Mac,
Linux or even iOS or Android

**Comment by photopea** [comment]
I understand, what you mean. It is all possible.

If we went the Flash way: it would require users to install "Photopea Player" (like a Flash Player) extension to their browser, which would give Photopea possibilities, which are not available through a browser. But this would require installing extensions, which can be an obstacle for many users.

If we went the Air way: it would basically convert Photopea into installable app, which has to be downloaded and installed through some app store. But I think it can be an obstacle for many users. Also, maintaining such separate version is also time consuming.

**Comment by rcoenen** [comment]
Yes indeed. Just to be clear: I wasn't suggesting to build some specific
player (or god forbid using actual outdated Flash/Aur technology). I was
curious to see if you'd be up for employing certain PWA and/or Chrome
specific features in order to create a more native like desktop experience.

So the web version would be the exact same as per today, but if you'd
"install" the PWA version on the right version of Chrome, it'd give you the
features discussed (ie file system stuff) which might or might not be
available in the browser agnostic web version

**Comment by photopea** [comment]
As I said, what you call PWA is still in under a full control of a web browser.

And no current browser supports such features at the moment (i.e. there does not exist any PWA today, which offers such features, as it is technically impossible).

**Comment by rcoenen** [comment]
I know and appreciate that PWA is onder full control of a web browser.  Yet PWA's are conceptually *not* intended to be just a web app in a chromeless container. From Google's [own developer resources](https://developers.google.com/web/ilt/pwa/introduction-to-progressive-web-app-architectures#instant_loading_with_service_workers_and_application_shells), introduction to PWA: _"Progressive Web Apps combine many of the advantages of native apps and the Web. PWAs evolve from pages in browser tabs to immersive apps by taking ordinary HTML and JavaScript and enhancing it to provide a first class native-like experience for the user."_

With this in mind (and the exact analogy to how Adobe positioned Adobe Air=native desktop/phone vs Adobe Flash=web) we might want to embrace this development under the moniker of "PWA".

Going back to the original topic of this threat: My current standard Chrome browser (Version 79.0.3945.117 Official Build 64-bit) supports the required flags to enable the [Text Editor demo](https://googlechromelabs.github.io/text-editor/). Sure, for now, I need to manually enable the #native-file-system-api flag once but with that I have a simple Text Editor that can open, edit and save any standard .txt file on my computer.

Would it be an idea to have a specific "experimental" branch of Photopea (let's call it PhotoPWA or PhotopeaX or something) which allows us to experiment and do what PWA is supposed to be designed for and _provide a first class native-like experience for the user._ ?

As things stand, we could already have a PWA that opens and saves PSD files directly to disk. It would seriously enhance the workflow a lot, I believe. At leats you could tease the feature out and test it and get feedback before you merge it in the main stable project.

I'll be happy to assist!

**Comment by photopea** [comment]
I can not make a special release Photopea for 0.001% of users with beta versions of a browser, or with special flags enabled :/

But I think I can implement it once the browsers support it, I can have it ready on the same day the browser is released.

**Comment by rcoenen** [comment]
OK - I was thinking maybe use it as laboratory / testing ground. There is a
risk that Photopea gets too many disjointed features or features that are
poorly integrated. The real value of this approach would obviously not be
to satisfy the 0.001% of users but have a small group of users interested
in testing features. A bit like how there is Chrome (main branch) but also
Chromium and Canary for testing bleeding edge features. Only stuff that has
been testing in Chromium successfully, and matured in Chromium ends up in
Chrome ultimately. Quite a few ideas might have been tested in Canary but
users did not like it, or it was poorly done or maybe just a bad idea to
start with and it got killed.

If a similar approach would be deployed to get Photopea ready as true
turn-key, drop-in solution to replace Photoshop this would be an amazing
feat to accomplish.

**Comment by photopea** [comment]
The problem is, that there thousands of people developing Chrome, while I am alone :(

**Comment by rcoenen** [comment]
True - and you are doing an amazing job seriously. OK I will leave it at
this. If you decide to have a go at adding native file system functionality
(and only that for now I guess) to an experimental PhotoPeaWA version -
feel free to reach out and I'll be happy to assist where I can.

**Comment by photopea** [comment]
I think I will add only features, that are supported in current standard releases of web browsers.
