### ISSUE TITLE
error with "app.activeDocument.saveToOE("tiff");" or "pdf"

### ISSUE THREAD

**Issue by nao-pon** [photopea/photopea#1905]
I got an error "Uncaught TypeError: Cannot read property '0' of null" when call "app.activeDocument.saveToOE("tiff");".

Error message:
```
pp.js:formatted:2680 Uncaught TypeError: Cannot read property '0' of null
    at Object.xx.TIFF.Rg (pp.js:formatted:2680)
    at Function.xx.Dq (pp.js:formatted:1383)
    at Function.xg.ob (pp.js:formatted:86871)
    at xg.In_ (pp.js:formatted:86847)
    at Fc.Ieo (pp.js:formatted:89246)
    at Fc.FM.J (pp.js:formatted:71)
    at Fc.xS.J (pp.js:formatted:66540)
    at Object.xp.cc.CV (pp.js:formatted:65622)
    at Function.xp.eval (pp.js:formatted:64505)
    at Function.xp.eval (pp.js:formatted:64452)
```

pp.js:formatted:2680 :
```javascript
    xx.TIFF.Rg = function(R, t, J, d) {
        var f = {}
          , y = R[0];
        if (y[3] != null && d[0]) // <-- pp.js:formatted:2680 d is null
            f = Fb.aD(y[3]);
```

**Comment by nao-pon** [comment]
And "pdf" cannot be saved either.

Probably because the option `y` is not set properly at the next point.

**Function.xg.ob (pp.js:formatted:86861)**
```javascript
xg.ob = function(R, t, J) {
    var d = t.split(":")
      , f = d[0]
      , y = null;
    if (d.length == 2) {
        if (f == "jpg" || f == "webp")
            y = [Math.round(100 * parseFloat(d[1]))];
        if (f == "psd")
            y = [!0, !0]
    }
    var F = xx.Dq(R, f.toUpperCase(), null, null, y, J);
    return F
}
```

**Comment by nao-pon** [comment]
The following file types I tried could not be saved.

- 'image/svg+xml', 'image/tiff', 'image/x-adobe-dng', 'image/x-xcf', 'application/pdf' and 'application/x-msmetafile'

**Comment by photopea** [comment]
Hi, I am very sorry for this bug.

I just fixed it for Tiff, PDF and SVG. Other formats are not possible for Photopea to export at the moment.

**Comment by nao-pon** [comment]
@photopea Thanks for a very quick fix! I have confirmed that saving Tiff, PDF and SVG works fine. Other types are saved as psd for now.

Thank you for developing such a great tool!
