### ISSUE TITLE
Lines from Select Tool stay on screen

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1906]
Using Rectangle Select Tool, Gradient Tool, Crop Tool or some others, when I go with mouse cursor over left toolbar and it opens context menu after I select some other tool here or click outside of context menu helper lines from tool stay on screen.

Screenshot 1 - selecting rectangle and I go over Pencil Tool icon:
![image](https://user-images.githubusercontent.com/6370548/72974916-cddfbd80-3dc7-11ea-8d7c-27ced1107e9e.png)
Screenshot 2 - I swap to Brush Tool and start using Brush (but Rectangle Select lines stay on screen):
![image](https://user-images.githubusercontent.com/6370548/72975038-01bae300-3dc8-11ea-8dcf-4c3910011f99.png)

**Comment by photopea** [comment]
I fixed it, the "sub-tools" menus will not appear after moving a mouse over them. You need to click them.
