### ISSUE TITLE
Error when using Free Pen with subtract mode

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1907]
I was using Free Pen tool in "Path" setting and "Subtract" mode. Tolerance was 3.
When I made small closed shape it disappeared like it closed to itself and when I released mouse in that moment it showed this error and it kept painting with free pen tool even after I released mouse left button.

Uncaught TypeError: Cannot set property 'Zj' of undefined
    at E.DN.E.O_.Zx (pp.js:4295)
    at vU.xDB (pp.js:9642)
    at vU.Kn.$ (pp.js:9)
    at vU.vu.$ (pp.js:6619)
    at KM.vu.$ (pp.js:6619)
    at Kt.vu.$ (pp.js:6619)
    at Kt.rv (pp.js:8894)

In this screenshot I am in pea.psd in pea layer - I started this shape in top then I go left then down then right then up then when I was close to starting point entire shape disappeared and I released mouse button and it keeps doing shape and error in console appeared in that moment:
![image](https://user-images.githubusercontent.com/6370548/72986182-882eef00-3ddf-11ea-98c1-c2825f48842a.png)

**Comment by photopea** [comment]
I fixed it, thanks for reporting!
