### ISSUE TITLE
Path merge and photopea crash

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1909]
Photopea stopped working when i did some paths manipulations and merging.
To reproduce this error:
1. Go to pea.psd.
2. Select "pea layer"
3. Select shape/path in that layer with Path Select tool
4. Copy and paste that shape with Ctrl+C and Ctrl+V
5. Now in top bar after Path 2: select "Subtract"
6. Now in top bar after Path 2: select "Merge"
7. Photopea crash and nothing is working:

pp.js:9174 Uncaught TypeError: Cannot read property 'mK' of undefined
    at Fg.YB (pp.js:9174)
    at _S._fy (pp.js:9566)
    at _S._U.L (pp.js:9)
    at _S.rA.L (pp.js:6615)
    at w.Rj.Lv (pp.js:4350)
    at _S.update (pp.js:9647)
    at _S.tz (pp.js:9646)

**Comment by photopea** [comment]
I fixed it, thanks for reporting!
