### ISSUE TITLE
Problem with Arabic text

### ISSUE THREAD

**Issue by Abdo578** [photopea/photopea#191]
Hi, 
I have used Photopea and it's great – it almost makes me feel like using Photoshop. But I have run into a problem that I haven't experienced before — whenever I try to edit a text on a .PSD file writing in Arabic, I get empty boxes instead of the Arabic characters (like they are unidentified), I do not know why. That .PSD file is not mine, I downloaded it for translation purposes.

**Comment by photopea** [comment]
Hi,  we are aware of that ... it is currently the oldest unfixed issue: https://github.com/photopea/photopea/issues/11

Thank you. We will try to fix it asap.
