### ISSUE TITLE
Guides negative position issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1911]
I set guides on position Horizontal : -3 Vertical : -3. But after I saved document and reopen it changed to Horizontal : 134217725 Vertical: 134217725
![image](https://user-images.githubusercontent.com/6370548/73053254-90426980-3e87-11ea-9eb2-4321fbfaea49.png)
![image](https://user-images.githubusercontent.com/6370548/73053261-96384a80-3e87-11ea-8723-27ffe02bee95.png)

**Comment by photopea** [comment]
Fixed! Thanks for reporting it :)
