### ISSUE TITLE
copy and paste not working

### ISSUE THREAD

**Issue by billyspeaks** [photopea/photopea#1912]
I'm using Photopea the same as always and it with not let me copy/paste. It will let me cut, but not paste.

**Comment by photopea** [comment]
Hi, I believe it is because you refused to give Photopea permissions to the clipboard, when you were asked.

Press on the lock icon on the left side of the URL address in your browser, and set the Clipboard to Allow.

**Comment by angebt** [comment]
In my computer, there is no padlock next to the address ("not secure"). 

I tried in the page settings and I didn't find it either

**Comment by photopea** [comment]
Are you using Photopea at www.Photopea.com ? Are you copying with Edit - Copy or Ctrl+C?

**Comment by angebt** [comment]
I got it! Thank you!!
