### ISSUE TITLE
photopea crashe after 5 hours of working

### ISSUE THREAD

**Issue by ziadg4mer** [photopea/photopea#1913]
i worked for about 5 hours on photo editor and then the website froozed and then it said to me that a problem happened and it told me to restart the page and all work i have done have gone

**Comment by photopea** [comment]
I am sad to hear that :/ sometimes, a browser decides to "kill" Photopea without a clear reason.

What browser do you use? Do you have at least 5 GB of RAM? Would it help, if we show a message "Don't forget to save your work" every hour?

**Comment by photopea** [comment]
I have to close it because of lack of details. If it happens in Safari, try using another browser.
