### ISSUE TITLE
Feature request: improve .raw file format support

### ISSUE THREAD

**Issue by victimized0** [photopea/photopea#1914]
Sometimes .raw files contain more than 4 channels and in fact the number can be arbitrary.
So the request would be to replace channels number button with text field so user can choose how many channels he wants.
Another feature request is to add file header into consideration. .raw files can contain headers and so it will be useful to be able to tell the tool how many bytes I want to skip before image data.

**Comment by photopea** [comment]
Hi, can you provide us an example of such files?

BTW. do you know why creators use such raw files? Isn't it better to use JPG or PNG, and make multiple files with 3 channels in each?

**Comment by victimized0** [comment]
Thats because raw files are basically an array of bytes. Thats why its called raw: raw bytes.
It's useful for between software exchange. For example you can put a lot of images inside such files (as long as they arent rgb: greyscale, indexed etc).
Sometimes you can interpret binary data as images (coz bin data is nothing else but raw bytes).
And it's the simplest (and fastest) file format to write/read. No need to bother about compressions or anything like it. Also since it stores greyscale colours, file uses 1 byte of colour info per pixel, instead of 3 (or 4) for rgb/argb.

**Comment by photopea** [comment]
But formats like .BMP also contain a raw data, which you can easily read and write. They have a header starting with a string "BM", which lets you detect that it is a BMP image, tells you the width, the height and the number of channels.

The raw files you are describing don't even have the info about width and height. A possible header, that is not standardized, does not help either.

People could just attach .BMP header to their raw files and make them openable everywhere, for the cost of extra 14 Bytes.

**Comment by victimized0** [comment]
Yeah you might be right

**Comment by photopea** [comment]
I will close it now, as I have never seen a .raw file with a number of channels different from 1, 3 or 4.

Also, I think it is not a good thing to invent your own file formats (with arbitrary headers, number of channels and possibly other properties) and asking software creators to add support for them. Many image formats are already invented and I recommend to make use of them.
