### ISSUE TITLE
Lens Blur Filter

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1916]
I use that functionality a lot! :)

I use it for example to make a realistic blur of the shadow. Sharp near the object and more blurred at the end of shadow.

There is a many more examples how to use it.

And... it isn't a Smart Blur! :)
That is good news for you @photopea because you can do it better than Adobe ;)

Here is nice simulator (reference for beginners in photographing) https://dofsimulator.net/en/
You can simulate many bokeh effects for the backgrounds and many more.

And now... just try imagine something.
You have photo taken from smartphone with DOF. Open it in Photopea. Photopea can show you oryginal file as a layer, DOF as a grayscale layer and Portrait photo as you can see in your phone.
With DOF changed to layer mask, you can reedit bokeh effect in Photopea to oryginal layer with many more possibilities (smartphone editors have small number of options). 

I post it again because author of the first Github Issue close it.

**Comment by photopea** [comment]
BTW. do you need all parameters similar to Lens Blur in Photoshop? E.g. Iris, Specular Highlights, Noise?

**Comment by 7Wdev** [comment]
> BTW. do you need all parameters similar to Lens Blur in Photoshop? E.g. Iris, Specular Highlights, Noise?

Yes plz with the depth map selection !!!

**Comment by manticorp** [comment]
> > BTW. do you need all parameters similar to Lens Blur in Photoshop? E.g. Iris, Specular Highlights, Noise?
> 
> Yes plz with the depth map selection !!!

The depth map is really the awesome feature about lens blur in Photoshop.

Specular highlights also help to make lens blur look quite realistic.

**Comment by MichalSZZ** [comment]
Ohh. I forgot to answer...
All parameters add more realistic look to the blur. If photo has got a noise, blurred effect should have noise too.

**Comment by photopea** [comment]
I was able to implement a square shape of a shutter. Other shapes would probably require a GPU implementation (otherwise, they take like 40 seconds to render).
![flowers](https://user-images.githubusercontent.com/15955558/76125262-b158b700-5ffc-11ea-9510-30a766c922a1.gif)

**Comment by MichalSZZ** [comment]
Good job! Something like that is better than nothing :)

40 seconds is not too much, when user know how much it can take.
Can you calculate how long it can be? That information can help take the decision to user. When it will have preloader or any other information about progress, user can decide to wait or hit esc and cancel operation.
BTW. in big images Content Aware Fill take long time too :)

Here http://bethecamera.com/ I see that square shape is implemented too. It is in JS.
This http://www.andersenimages.com/tutorials/exposure-simulator/# simulator works great but it doesn't generate images, but show only photos taken before.

**Comment by photopea** [comment]
Hi, I implemented the Lens Blur filter (Filter - Blur - Lens Blur). 

It runs on the GPU, but it can still be quite slow (over 1 second), as it requires for each pixel to compute the average color of neighbouring pixels (for a radius 100, there 200x200=40,000 pixels). And for 10 megapixel image, we need 400 billion operations. That would take about 20 seconds on my GPU, and probably an hour on the CPU :)

![image](https://user-images.githubusercontent.com/15955558/76239053-27456400-6231-11ea-8230-e86f9f8ab9b0.jpg)

**Comment by manticorp** [comment]
Wow, awesome job! That preview looks great. -------- Original message --------From: Photopea <notifications@github.com>Date: Mon, 9 Mar 2020, 17:11To: photopea/photopea <photopea@noreply.github.com>Cc: Harry Mustoe-Playfair <manticorp1234@gmail.com>, Comment <comment@noreply.github.com>Subject: Re: [photopea/photopea] Lens Blur Filter (#1916)Closed #1916.

**Comment by MichalSZZ** [comment]
AMAZING!
Thank you. I just bought premium account for next 3 months :)

My test with bokeh effect:
![bokeh](https://user-images.githubusercontent.com/38118273/76294390-0f162900-62b3-11ea-8d9b-392f52eac7a4.jpg)

**Comment by photopea** [comment]
Actually, this filter could be 100x faster, if we used a shutter of a circular shape with soft edges. But since it is a polygon with hard edges, that is why it is so slow :D

**Comment by MichalSZZ** [comment]
Slow? :D I can't tell that. It's Ok on our test image.

How about heart bokeh for womans? ;)
![obraz](https://user-images.githubusercontent.com/38118273/76295457-f0189680-62b4-11ea-9797-aac2a0310009.png)

One more time I must thank you very much for all your hard work!

**Comment by photopea** [comment]
You probably have a good GPU (I have only a laptop with integrated graphics). How did you make the heart shape? :)

**Comment by MichalSZZ** [comment]
hehe not me :)
<img width="572" alt="obraz" src="https://user-images.githubusercontent.com/38118273/76296110-ff4c1400-62b5-11ea-9c86-a8ff24202e6d.png">
screen from https://youtu.be/Sn-EpqJCLXk?t=20

last screen from https://www.diyphotography.net/diy_create_your_own_bokeh/ it is trick in photography - custom (any) shape bokeh

**Comment by MichalSZZ** [comment]
and I have Intel Iris integrated GPU in my 6 years old i5 processor (macbook pro)

**Comment by photopea** [comment]
yeah, that trick makes sense :D a real bokeh with a real shutter, not faking it with Photopea :D 

I could add the option to give Photopea any bitmap as a shutter shape. It is related to Shape Blur in Photoshop.
