### ISSUE TITLE
Feature Request : channels duplicatation and editing !! 

### ISSUE THREAD

**Issue by 7Wdev** [photopea/photopea#1919]

**Comment by photopea** [comment]
Hi, how can we help you?

**Comment by 7Wdev** [comment]
> Hi, how can we help you?

I am trying to duplicate the blue channel , because I want to edit it without damaging the original one.
I tried alot, idk how can I duplicate the channel and edit it in photopea or maybe this feature is not implementated yet??

**Comment by photopea** [comment]
In a Channels panel, you can select a specific channel, that you wish to edit.

You can duplicate a layer in advance, to preserve the original channels.

**Comment by 7Wdev** [comment]
> In a Channels panel, you can select a specific channel, that you wish to edit.
> 
> You can duplicate a layer in advance, to preserve the original channels.

Can you tell me how

**Comment by photopea** [comment]
Press Window - Channels and select a specific channel.

Or look for a tutorial about how to do it in Photoshop (it should work similarly in Photopea).

**Comment by 7Wdev** [comment]
> Press Window - Channels and select a specific channel.
> 
> Or look for a tutorial about how to do it in Photoshop (it should work similarly in Photopea).

That's why I am asking, in Photoshop I was able to duplicate a channel and edit it directly .
My PC is broken that's and I saw that photopea is a great project(good job) that can help me continue my work....

**Comment by photopea** [comment]
In Photoshop, you can hold Ctrl and click the channel (in Channels panel) to convert it to a selection. Then, you can press a button at the bottom, to make a new channel from a selection. It works the same way in Photopea.

**Comment by 7Wdev** [comment]
> In Photoshop, you can hold Ctrl and click the channel (in Channels panel) to convert it to a selection. Then, you can press a button at the bottom, to make a new channel from a selection. It works the same way in Photopea.

https://youtu.be/6JVFxnWH-pM
Look at 4:13
That's what I mean

**Comment by photopea** [comment]
You can duplicate channels now by dragging them to a New Channel icon.

**Comment by 7Wdev** [comment]
> You can duplicate channels now by dragging them to a New Channel icon.

Hmmm, it doesn't work

**Comment by photopea** [comment]
could you be more specific?

**Comment by 7Wdev** [comment]
> could you be more specific?

I can drag layers, I can't drag channels in photopea (the new feature)

**Comment by photopea** [comment]
You need to switch to a Channels panel. Press Window - Channels. 

Or could you record a video how do you do it?

**Comment by 7Wdev** [comment]
> You need to switch to a Channels panel. Press Window - Channels.
> 
> Or could you record a video how do you do it?


Look

**Comment by 7Wdev** [comment]
> You need to switch to a Channels panel. Press Window - Channels.
> 
> Or could you record a video how do you do it?

Idk why I can't send the video, but I am sure that I am doing it correctly !!!
When I try to drag a layer and duplicate it it works but with channels it doesn't work , I can't drag them....

**Comment by photopea** [comment]
Try to reload Photopea website.

**Comment by 7Wdev** [comment]
> Try to reload Photopea website.

I will try
