### ISSUE TITLE
Feature Request: Bind Escape to canceling stuff

### ISSUE THREAD

**Issue by dimitriadisg** [photopea/photopea#192]
Hello,

thank you for this great project, I hope it will remain free and useful forever.

Now. on topic : It would be really nice if you could bind hitting ESC to canceling current selection. The general logic is up to you, but specifically I find this feature really needed when I am selecting Text.

Example use case workflow :
1. Select the "Text (T)" tool from the left bar
2. Click on a text in the psd document
3. Do some (or none) changes
4. Hit Escape button
5. Click on another text and go repeat from step 3

So, ESC would actually trigger clicking on the "X" button from the topbar while text editing is active. Taking this one step further, maybe it would be a good idea to unfocus current text and focus on new text upon clicking outside the text area, but that would be more complicated, I think implementing an escape usage would be better and more generic (maybe you'll find it cool to have some functionality for other tools as well)

**Comment by photopea** [comment]
Hi Dimitri,

Escape key always escaped the text editing (equivalent to clicking "X"), since the introduction of the Type tool. Do you have to click "X" manually, because Escape does not work? What OS and a browser do you use?

Clicking outside the text area during the editing is used for moving the text layer (for a constrained text layer), so you have to confirm / cancel current editing and then click on another layer.

**Comment by dimitriadisg** [comment]
Hello,

Oh I see. Well, my OS is Mac OS 10 and I have that problem on Safari. I will test again on Chrome tomorrow and let you know on updates.

**Comment by photopea** [comment]
We want Photopea to work in every browser, including Safari.

Can you go to this page http://jsfiddle.net/p45f44zb/ , click into the bottom-right rectangle area (to give it focus) and press different keys (Shift, Spacebar, Escape) ... what do you see when you press Escape?

**Comment by dimitriadisg** [comment]
Update:
OS: Mac OS Sierra 10.12.3
Chrome: 58.0.3029.110
Safari: 10.0.3

On Chrome, Escape works as expected. Also the loaded content is not grainy (unlike Safari) when zoomed out (But this has to do with Chrome rendering).
On Safari, Escape doesn't work.

Update on jsfiddle testing :
Chrome: Works fine, I am seeing the name of the key pressed (beware with Tab, Tab's functionality will make the iframe lose focus).
Safari: Nothing, e.key is written inside the span normally, but its content is empty.

Suggestion: You can try e.keyCode instead and receive the ASCII representation of the pressed key, works normally on Safari and Chrome, here's the [fiddle](http://jsfiddle.net/p45f44zb/1/)

Thanks for your support !

**Comment by photopea** [comment]
So in Safari, Keyboard event is dispatched, but the .key property is an empty string? That is very weird. Can you report it to Safari developers as a bug? We don't want to make separate versions of code just to overcome bugs in browsers.

BTW. "grainy content" is probably related to WebGL ... When WebGL is on, we use a simplified version of zooming out. We plan to fix it in the future. You can switch WebGL in More - Enable WebGL.

**Comment by dimitriadisg** [comment]
e.key is actually undefined.
Well, I could report it as a Safari bug, but I doubt they'll bother fixing it, so I'd be wasting my effort towards improving a browser that I don't like. They didn't bother to fix a thousand webkit-specific issues all these decades. I think they like feeling special.

**Comment by photopea** [comment]
According to this: http://caniuse.com/#feat=keyboardevent-key  , the "key" property should work in Safari 10.1. Can you try to update it?

Otherwise, I recommend to use some different browser, until Safari developers fix it.

**Comment by dimitriadisg** [comment]
Yeap, it works, thanks.

**Comment by photopea** [comment]
You mean it works in Safari after an update?

I have updated the Will-It-Work page: https://www.photopea.com/willitwork/ . It should say, if Photopea will work in your browser (Yes / No).

**Comment by dimitriadisg** [comment]
Yeap, worked perfectly mate, thanks for your support !
