### ISSUE TITLE
Undo Glitch

### ISSUE THREAD

**Issue by deltasucko** [photopea/photopea#1922]
When I use this for art, as I sometimes do, I use the undo feature alot. When its used alot, sometimes it glitches and deletes the last few strokes I have made. Please fix.

**Comment by photopea** [comment]
Hi, could you show us an example of what you mean? What should we do in Photopea to see it happen for ourselves?

**Comment by deltasucko** [comment]
I cannot have it happen by choice, as it seems to happen randomly, but an example is, I undo something, but it then undo's the action before the last one. I cannot redo it, however.

**Comment by photopea** [comment]
I really need an example, how to make it happen. I am sure it is not completely random.

If you go back multiple steps, and create a new step (e.g. moving a layer), you can not go back to the steps you undid, because a new step replaces them.

**Comment by photopea** [comment]
I have to close it because of lack of details. I think the user did not press the shortcut correctly, when the problem happened.
