### ISSUE TITLE
Lag.

### ISSUE THREAD

**Issue by deltasucko** [photopea/photopea#1923]
The main problem I have with this that makes me not use it so often: Lag. It happens whenever you use it for over 10 minutes. Then it starts to lag. The only way out of the lag is to close and reopen Photopea. But I'm working on a project, and it's a pain to have to save it and use up more storage on my computer. If there is ANY way to fix this.. Please do.

**Comment by photopea** [comment]
That is really strange. How much RAM do you have on your computer? How large are your documents, in terms of resolution and PSD file size?

**Comment by deltasucko** [comment]
I keep the files at around 50% resolution. The last .PSD I saved was 64.4 MB. I have around 8G RAM on my device.

**Comment by deltasucko** [comment]
The lag mostly happens while scrolling, but also happens when I use tools.

**Comment by photopea** [comment]
And what is the resolution of your PSD in pixels?  Do you paint a lot with a brush? Or what actions do you do the most?

**Comment by photopea** [comment]
I will close it now because of lack of comments. My guess is, that your device is not powerful enough for working with such large  documents as yours.
