### ISSUE TITLE
Feature Request: Consider to add zoom/preview area while using select/crop tools 

### ISSUE THREAD

**Issue by rosolko** [photopea/photopea#1924]
Hi, can you please think about this feature.

From my point of view it will be very helpful.
For example, by default this feature will be disabled, but can be enabled in settings.

Maybe it can looks like build in zoom/preview area from Firefox color picker tool.

<img width="326" alt="Screen Shot 2020-02-06 at 10 50 36" src="https://user-images.githubusercontent.com/11458319/73916769-1e2e4380-48cf-11ea-9d62-d6749d5962fa.png">

Thanks!

**Comment by photopea** [comment]
I don't really know if people would use this. They might turn it on accidentally and then, they don't know how to turn it off.

Have you tried holding Ctrl+Spacebar, clicking and dragging to the left - right?

**Comment by rosolko** [comment]
Yes, it works, but, for this you have to zoom in/out image many many times.
And yes, feel free to close this issue, if no really case imagine.

Anyway, many thanks for awesome tool!

**Comment by photopea** [comment]
I will close it, as I don't know how to add it to our current tools, so that it is easy to find for people who need it. I am not aware of such feature in other photo editors, to be able to implement it in a same way, already familiar to users.
