### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by ktdid518** [photopea/photopea#1927]
Bullets and indentation set in Sketch do not convert to Photoshop

**Comment by photopea** [comment]
Hi, do you have an example of such Sketch file? Are you sure such text properties are possible in a PSD format?

**Comment by ktdid518** [comment]
There are auto bullet indentation settings in Sketch, and in Photoshop you must set indentations via the "Paragraph" window

This is what my styling looks like in Sketch:
<img width="879" alt="Screenshot 2020-02-06 12 17 23" src="https://user-images.githubusercontent.com/57205847/73961584-e4fbd080-48da-11ea-8a97-d7ffa310ccc8.png">

And, this is what the conversion to PS looks like:
<img width="1011" alt="Screenshot 2020-02-06 12 18 45" src="https://user-images.githubusercontent.com/57205847/73961629-f47b1980-48da-11ea-84a3-2b773208459d.png">

**Comment by photopea** [comment]
Could you recreate such paragraphs in Photoshop?

I know you can set the left indentation in Paragraph window, but how do you add bullets that are not indented?

**Comment by photopea** [comment]
I will close it, as I am afraid there is no way to do it in PSD format.
