### ISSUE TITLE
Type vertical alignment setting lost in conversion

### ISSUE THREAD

**Issue by ktdid518** [photopea/photopea#1928]
The vertical alignment of type set in Sketch is lost in conversion to Photoshop

**Comment by photopea** [comment]
Can you provide us a sample Sketch file, where it happens?

**Comment by ktdid518** [comment]
Screenshot of sketch to photoshop conversion where centered vertical type alignment is lost: <img width="961" alt="Screenshot 2020-02-06 12 10 34" src="https://user-images.githubusercontent.com/57205847/73961146-0ad4a580-48da-11ea-8857-c015f02ad023.png">

**Comment by photopea** [comment]
Could you send me the Sketch file to support@photopea.com ? I don't have Sketch App to create such file myself.

**Comment by ktdid518** [comment]
Will do! Thanks!

**Comment by photopea** [comment]
I fixed it, Photopea should handle the vertical alignment better now.

**Comment by ktdid518** [comment]
You are a magician! Thank you for all of your help today and in creating this product. It's so helpful!
