### ISSUE TITLE
Pop-up Issue 

### ISSUE THREAD

**Issue by EliTaylor17** [photopea/photopea#1930]
Whenever I try to use this program to edit files for my schoolwork, it has a pop-up that appears stating the following:

![image](https://user-images.githubusercontent.com/60794038/74057915-e4366d80-49b2-11ea-981e-b01df5e09e40.png)

This pop-up continues to appear despite the fact that I have clicked the OK button multiple times. The device I use to edit images on Photopea doesn't even have an ad blocker, as it is school issued and we are unable to install such programs. I am not the only person in my class having this issue, so I would assume that it is not a problem with my device in particular. Is there a specific reason as to why this is happening? Is it intentional?

**Comment by photopea** [comment]
Something is blocking photopea from loading an internal file. Are you sure you are not blocking ads? Do you see normal ads on other websites?

**Comment by EliTaylor17** [comment]
Most websites that would have ads are blocked, so I am unable to check, but I know that of the programs installed, there are no ad blockers. I am unable to check the settings on the device either, so I am unable to check that way. Thank you however for trying to help resolve the problem.

**Comment by photopea** [comment]
I disabled the message about blocking ads. But it will be enabled again in the future, so your problems will return.

So what exactly do you see on the right side of Photopea? If you see a banner for Photopea Premium, it means that standard ads are blocked. Do you have any antivirus that could do that?

**Comment by EliTaylor17** [comment]
There is a banner for premium, yes. It is possible that there is an antivirus, but I am not sure. Thank you for your time as well as your help fixing this issue.

**Comment by photopea** [comment]
You should know, that there is some program in your devices, which monitors all your web data. If it can change the code of Photopea, it can read your emails, facebook messages and other chats as well, and send them to the authors.

It is probably your antivirus or the browser itself. What browser do you use?

**Comment by EliTaylor17** [comment]
I use Google Chrome. The school has installed some extensions to it, so they may be the cause.

**Comment by photopea** [comment]
I will close it now. If you have such issues, use Photopea in Incognito mode.
