### ISSUE TITLE
Ctrl+C and Ctrl+V don't work

### ISSUE THREAD

**Issue by littlemissblitz** [photopea/photopea#1932]
When I try to use the command ctrl+c to copy an object it does not work, same goes for ctrl+v. Also when I try to copy the object from the Edit section it doens not work either.

**Comment by photopea** [comment]
You probably denied Photopea access to your clipboard, see here: https://github.com/photopea/photopea/issues/1912

This problem seems to be so common that people even make videos about it https://github.com/photopea/photopea/issues/1912
