### ISSUE TITLE
Update Request !!! 

### ISSUE THREAD

**Issue by 7Wdev** [photopea/photopea#1933]
Try to search features in Adobe Photoshop that photopea doesn't have and add them as a new huge update , it will be awesome !!!
for example the noise and solid gradient, missing filters, color grading ....

**Comment by photopea** [comment]
Your request is too general. It takes years to add new features. You should specify only one feature which you miss, and we will add those features, which are requested by the biggest number of people.

**Comment by 7Wdev** [comment]
> Your request is too general. It takes years to add new features. You should specify only one feature in your request. We will add those features, which are requested by the biggest number of people.

Oh ok, currently I miss the gradient fill ui that exist in Adobe Photoshop, there is presets + selection between noise gradient or solid ...

**Comment by photopea** [comment]
There is a Gradient UI in Photopea, too. 

Do you really need Noise Gradients? Nobody ever asked for them in the last seven years. What do you use them for?

**Comment by 7Wdev** [comment]
> There is a Gradient UI in Photopea, too.
> 
> Do you really need Noise Gradients? Nobody ever asked for them in the last seven years. What do you use them for?

Yes, I need them to edit sunlight , moonlight...

**Comment by photopea** [comment]
Can you show us how it should look like?

**Comment by 7Wdev** [comment]
> Can you show us how it should look like?

I can't upload videos on GitHub idk why, but this video may explain all :
https://youtu.be/-01kLB8JnH8
