### ISSUE TITLE
Work path from selection

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1934]
Is it hard to implement that functionality in a paths tab?

I know how to change something into a path/shape in Photopea (and Photoshop don't have that ability ;) and that is great feature), but sometimes it's take me more time and few steps more to do vs one click option in PS.

For example I have transparent PNG and want to make text that flows around the picture.
![obraz](https://user-images.githubusercontent.com/38118273/74289536-9497cf00-4d2f-11ea-861a-c0c7f4aa13c7.png)

In Photoshop:
1. Click on layer thumbnail with Ctrl button
2. Select -> modify -> expand selection
3. Go to paths and click on "make new path from selection"
4. Copy path and paste to the rectangle shape with "subtract front shape" option
5. Fill shape with text

In Photopea I must make a little trick with filling selection with one color and vectorizing a bitmap.

**Comment by photopea** [comment]
I implemented it :)

But if you convert path to a selection, and then selection to path, don't expect to get the same path. You will usually get more anchors.

**Comment by MichalSZZ** [comment]
Thank you! That works as I expected :) Great!

**Comment by sktzofrenic** [comment]
On this topic, I noticed that if you create a path from a selection like this:

![image](https://user-images.githubusercontent.com/11902047/120068132-24f54280-c04d-11eb-901c-ac2597a6a249.png)

But then try to convert the path back to selection, you only get the exterior selection. 

![image](https://user-images.githubusercontent.com/11902047/120068147-38081280-c04d-11eb-9b6b-6c87860bc3a4.png)

Even trying to select a portion of the path and make a selection just from that yields the exterior selection. 

![image](https://user-images.githubusercontent.com/11902047/120068172-540bb400-c04d-11eb-945d-84d883305702.png)

Result

![image](https://user-images.githubusercontent.com/11902047/120068179-5e2db280-c04d-11eb-975f-9fa501d41c8c.png)


[tiger.zip](https://github.com/photopea/photopea/files/6564569/tiger.zip)

I must say this app is extremely fun to use and as helped me transfer my photoshop productivity to something compatible with linux. This is a huge win and thank you for the effort.

**Comment by photopea** [comment]
I think our selection-to-path converter can not process holes right now :( In general, I recommend not converting selections to paths, but draw the paths manually.

**Comment by DesertBanana** [comment]
> I implemented it :)
> 
> But if you convert path to a selection, and then selection to a path, don't expect to get the same path. You will usually get more anchors.

How do you convert a path to a selection?

**Comment by photopea** [comment]
You can right-click it with any vector tool (e.g. Pen tool) and choose "Make Selection".

Or go to Window - Paths, and click "Selection" at the bottom (the middle button).

**Comment by DesertBanana** [comment]
> You can right-click it with any vector tool (e.g. Pen tool) and choose "Make Selection".
> 
> Or go to Window - Paths, and click "Selection" at the bottom (the middle button).

Thanks!!!
