### ISSUE TITLE
Text hyphenation

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1935]
It is a not a "must have" feature for me :) 
I just only asking about possibility to add something like this http://hunspell.github.io/ if it don't take so much time for you to implement it.

It looks good when we have many text in a column with big font size and/or long words and paragraph justified.

Maybe it can be helpfull in cases like this one https://github.com/photopea/photopea/issues/667 when text box is narrow and long text is hidden

**Comment by photopea** [comment]
It would be quite hard to make it, and it would require a large database to be downloaded from our server every time.

Maybe we should wait until web browsers offer some interface for doing this.

**Comment by MichalSZZ** [comment]
Ok I understand. But I have one more thing with text functionality that I use alot and I think it is quite easy to add. I will make a new Issue for that ;)
