### ISSUE TITLE
Opening file from Google Drive is stuck

### ISSUE THREAD

**Issue by grandyop** [photopea/photopea#1936]
Hello,
Whatever the device is (chromebook, Win 10 with Chrome 79,  Android phone with Chrome 80) my file import from Google Drive is stuck in Photopea : "Loading" appears and that's it

**Comment by photopea** [comment]
We are aware of this problem, we are trying to solve it with Google. Until then, you can put your files into your computer and open them from your computer.

**Comment by photopea** [comment]
Hi, it is fixed now.

**Comment by grandyop** [comment]
Thx for your reactivity
