### ISSUE TITLE
Filter>Render>Clouds and Difference Clouds does not work 

### ISSUE THREAD

**Issue by TOMYver666** [photopea/photopea#1937]
Hello everybody I have little problem on photopea.com . If I want to use Filter>Render>Clouds or Difference clouds than the photopea.com does not make anything. Do you know to help me with this problem please ? .

**Comment by photopea** [comment]
you are right, it does not work when the layer is empty. it should work for the empty layers, too.

**Comment by TOMYver666** [comment]
yeah you're right too than i must fill this layer with coloring bucket .... thank you for your help :)

**Comment by photopea** [comment]
No, I mean Photopea should make clouds even if the layer is empty.

I fixed it, it will make clouds also in empty layers now.

**Comment by TOMYver666** [comment]
Oh ... Oukey thank you than 👍
