### ISSUE TITLE
Path/Pen tool  (2 issues)

### ISSUE THREAD

**Issue by teeInc** [photopea/photopea#1938]
Just want to say AMAZING program!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  No one has the features you have for a web based application. Thank you. 

Is it possible to add a cursor/icon change or highlight when you edit the handles on the anchors/nodes. Hard to see the square/circle modes of the anchors too. 
![image](https://user-images.githubusercontent.com/54411028/74670450-30ce3580-5177-11ea-9496-e17a98737f30.png)

When trying to convert an anchor with no handles (into one that has them, it is not consistent). This happens using both modes of the Path Select tool. Also happens in both Chrome and FireFox.

**Comment by teeInc** [comment]
It looks like you made some changes? Easier to see now, thank you. Maye too much to ask about the hover/highlight of the nodes/anchor points.

**Comment by photopea** [comment]
Hi, the vector anchor will highlight, when you move over it with a Direct Select tool.

Also, I made the path contours blue instead of "inverted colors".
![image](https://user-images.githubusercontent.com/15955558/75985626-ec6bc500-5eec-11ea-9069-d6fe64db7556.png)
