### ISSUE TITLE
Poiret One

### ISSUE THREAD

**Issue by NatashaDK** [photopea/photopea#194]
Would it be possible to add this free and beautiful art deco font :
https://fonts.google.com/specimen/Poiret+One

Love from Natasha / Denmark

![screenshot 2017-06-02 at 02 19 21](https://cloud.githubusercontent.com/assets/27579710/26705959/eda6fb24-4739-11e7-9a23-e95999037b36.png)

**Comment by photopea** [comment]
Hi Natasha, I am sorry for such a long delay. I had to solve several other problems with our font database.

Poiret One was added, also about 300 other new fonts.

Also, I have added a little text field, where you can type the name of the font. The font list will be updated in real time as you type. So when you know which font you need, you don't have to scroll through hundreds of fonts.

**Comment by NatashaDK** [comment]
Wow! this is great news! I love the search fileld, thanx a lot.
Photopea is really improving... almost day by day :-)
