### ISSUE TITLE
Cannot View Project

### ISSUE THREAD

**Issue by jules1398** [photopea/photopea#1940]
Every time I try to open a picture to begin a project, it does not show up. Neither does the background when I create a new project. If I place a picture on a new project it will show briefly but as soon as I click anything it disappears. It works in incognito, but I don't have any extensions that would impede on its functionality (I have adblock but it's turned off on photopea and then i have grammarly but that's about it). I do marketing for my organization at school and this is my primary photo editing tool so any assistance would be appreciated. I'm using it on Chrome using a PC with Windows 10..
![image](https://user-images.githubusercontent.com/44196186/74902080-2f149580-5362-11ea-864f-abe072e021b5.png)

**Comment by photopea** [comment]
Hi, if it works in Incognito, it has to be some extension. Try to disable them all, then, enable them back one by one, until you find the one which will brea Photopea. 

It could be the adblock or grammarly. You never know what extensions really do (they all are allowed to see the content of all websites and modify it).

**Comment by photopea** [comment]
I will close it because of lack of details.
