### ISSUE TITLE
Lasso Select

### ISSUE THREAD

**Issue by coolcraftnet18** [photopea/photopea#1941]
It would be nice to have a Lasso Select more like Gimp's Lasso Select because Gimp's Lasso Select lets you make multiple connected lines.
![image](https://user-images.githubusercontent.com/18317131/74932739-880b1a80-53b0-11ea-81e6-95b62287c52d.png)

**Comment by photopea** [comment]
When you are drawing with a Lasso tool, press Alt and release the mosue. Now, you can click into the image, it works like a polygonal lasso. Hold the mouse and release Alt, to use it as a regular lasso again.
