### ISSUE TITLE
XD File - Unknown format

### ISSUE THREAD

**Issue by RoryDep** [photopea/photopea#1943]
Hi,

I am trying to convert an XD file to .psd and it says file not working. I have tried on a different .xd file and it works. Is there anything I can do to fix this?

Kind regards,

Rory

**Comment by photopea** [comment]
Can you send us your XD file, which does not work, to support@photopea.com ?

**Comment by RoryDep** [comment]
Hi, 

I was able to fix it. Thank you for the help!

Regards,

Rory

**Comment by photopea** [comment]
ok great :)
