### ISSUE TITLE
3d | threejs

### ISSUE THREAD

**Issue by Hoodgail** [photopea/photopea#1944]
# threejs or any other webgl 3d renderers

- ok i was suggesting for a 3d editor for example... if a person loads in an obj file
- you could edit the texture on photopea and it displays the texture on the 3d model **(live)**

for this it would be easier to use three JS it would not be hard to implement this feature... i could do it but i don't have that much time

**Comment by photopea** [comment]
Hi, even if Photopea had 3D features, I think nobody would use it, because nobody would expect 3D features in an image editor. What do you think?

You can make a 3D editor and use Photopea in it as a plug-in tool.

**Comment by Hoodgail** [comment]
OK ill work on one... there is a lot of devs/users that uses photopea for texturing and would like to prev 
the tex live on the 3d model

**Comment by Hoodgail** [comment]
oh and i cant find the way to get the current image in the editor... for ex when you click the png button
i cant find how it gets the image data 
could u help me get it in base64 or blob? **JS**

**Comment by photopea** [comment]
Now, Photopea allows saving file only saving raw bytes. Also, if you select part of the image and press Ctrl+C, it will be copied into a clipboard (you can paste it outside Photopea).

**Comment by xan2622** [comment]
>  - ok i was suggesting for a 3d editor for example... if a person loads in an obj file
 >   - you could edit the texture on photopea and it displays the texture on the 3d model (live)
>
> for this it would be easier to use three JS it would not be hard to implement this feature... i could do it but i don't have that much time

> there is a lot of devs/users that uses photopea for texturing and would like to prev the tex live on the 3d model

---

This is literally my exact wish. It would be awesome if 3D artists could texturize their objects/meshes directly in Photopea.
Photopea alerady features a plugin to create [Normal Maps](https://github.com/photopea/photopea/issues/1875) but it would be great to see Photopea moving forward (just a bit) to Substance Painter.

Here are some javascript-based projects that I found: 

 - paint on a 3D model: https://discourse.threejs.org/t/paint-color-and-images-on-3d-model/13891 | <img src="https://user-images.githubusercontent.com/1732773/138133511-b6239458-bb3a-43fa-840d-c8540525340d.png" width="14px" height="14px"> [demo](https://rawcdn.githack.com/sciecode/three.js/f4e363a8e0cf6c496f4191192d7eb15110442a7c/examples/webgl_paint_texture.html)
- a project to load FBX, glTF and Collada files: https://github.com/looeee/multiformat-model-viewer | <img src="https://user-images.githubusercontent.com/1732773/138133511-b6239458-bb3a-43fa-840d-c8540525340d.png" width="14px" height="14px"> [demo](https://loader.lewy.blue/) 
- fillRect vs ImageData: https://stackoverflow.com/questions/39733553/using-fillrect-to-paint-onto-a-3d-model-is-too-slow
- Three.js Examples: https://stemkoski.github.io/Three.js/
- informations about webgl: https://www.toptal.com/javascript/3d-graphics-a-webgl-tutorial

**Comment by Hoodgail** [comment]
> Hi, even if Photopea had 3D features, I think nobody would use it, because nobody would expect 3D features in an image editor. What do you think?
> 
> You can make a 3D editor and use Photopea in it as a plug-in tool.

There is a whole community with 10k members looking for 3d tools with image editors for material creations... I will work on it...

> > * ok i was suggesting for a 3d editor for example... if a person loads in an obj file
> > * you could edit the texture on photopea and it displays the texture on the 3d model (live)
> > 
> > for this it would be easier to use three JS it would not be hard to implement this feature... i could do it but i don't have that much time
> 
> > there is a lot of devs/users that uses photopea for texturing and would like to prev the tex live on the 3d model
> 
> This is literally my exact wish. It would be awesome if 3D artists could texturize their objects/meshes directly in Photopea. Photopea alerady features a plugin to create [Normal Maps](https://github.com/photopea/photopea/issues/1875) but it would be great to see Photopea moving forward (just a bit) to Substance Painter.
> 
> Here are some javascript-based projects that I found:
> 
> * paint on a 3D model: https://discourse.threejs.org/t/paint-color-and-images-on-3d-model/13891 | <img alt="" width="14px" height="14px" src="https://user-images.githubusercontent.com/1732773/138133511-b6239458-bb3a-43fa-840d-c8540525340d.png"> [demo](https://rawcdn.githack.com/sciecode/three.js/f4e363a8e0cf6c496f4191192d7eb15110442a7c/examples/webgl_paint_texture.html)
> * a project to load FBX, glTF and Collada files: https://github.com/looeee/multiformat-model-viewer | <img alt="" width="14px" height="14px" src="https://user-images.githubusercontent.com/1732773/138133511-b6239458-bb3a-43fa-840d-c8540525340d.png"> [demo](https://loader.lewy.blue/)
> * fillRect vs ImageData: https://stackoverflow.com/questions/39733553/using-fillrect-to-paint-onto-a-3d-model-is-too-slow
> * Three.js Examples: https://stemkoski.github.io/Three.js/
> * informations about webgl: https://www.toptal.com/javascript/3d-graphics-a-webgl-tutorial

I shall work on it.

**Comment by photopea** [comment]
There already is Window - More - 3D Depth Viewer.  If you press "Load Color", it will apply the current image as a texture to a 3D model (which you can rotate etc).

We could have a similar plugin, where you can load your 3D model and preview the current document as a texture on that model. Would it be useful for anyone?
