### ISSUE TITLE
Better to have an offline editor.

### ISSUE THREAD

**Issue by Tairraos** [photopea/photopea#1947]
is this requirement possible?

**Comment by photopea** [comment]
Hi, we already have an issue for this, lets discuss it there: https://github.com/photopea/photopea/issues/1867

**Comment by aidinjk** [comment]
Lol its not closed

**Comment by vehosah** [comment]
> Hi, we already have an issue for this, lets discuss it there: #1867

Pity it's closed :p

**Comment by photopea** [comment]
Photopea works fully offline now. If you open www.Photopea.com at least once on a computer, it will be stored on it forever, and your browser will show you www.Photopea.com even offline.
