### ISSUE TITLE
In "Levels", the middle level box is lost

### ISSUE THREAD

**Issue by mathemaudio** [photopea/photopea#1948]
Steps:
* open/create a file in Photopea
* in "Layers", click the little half black circle at the bottom
* choose "Levels"
* Right at the bottom of the Histogram, you can see three boxes: black at the left, gray in the middle and white at the right
* drag the middle box either to the left (min) or to the right (max), so that it gets hidden by either white or black box

Actual result:

* the grey box disappears and is never accessible anymore

Expected result:

* the gray box should be visible and draggable

**Comment by photopea** [comment]
fixed, thank you!

I wonder why nobody reported it until before.
