### ISSUE TITLE
Objects lost if free transform is used to expand it too much

### ISSUE THREAD

**Issue by stingray4540** [photopea/photopea#1950]
I'm working on a 24000x19200 300 DPI project and when I try to expand something, at a certain point it disappears. This happens with the rectangle tool, all of a sudden the fill color is gone. Also happens with an image, expand past a certain point and the image is gone. It's not specific to this project, I've tried other larger sized projects and this keeps happening. I can't make anything large enough inside the project to do what I want to do.

**Comment by photopea** [comment]
There were two restrictions in Photopea:
- if the area of a rendered vector shape is bigger than 200 megapixels, the content is empty
- if the area of a transformed bitmap is bigger than 200 megapixels, the content is empty

I increased the limits to 900 megapixels, and these bugs should not occur now. However, when a document size (widht or height) is larger than 16000, WebGL is disabled, and Photopea is very slow without WebGL. Also, in your case, a full-size layer takes 1.8 GB of RAM memory (so there is a very limited number of layers you can create). 

I would recommend using smaller pixel resolution (or if you need an exact size in inches, use smaller DPI). Photopea will be a lot faster. If you use only vector shapes, text layers and smart objects, the resolution is not important at all (you can increase it in the future).
