### ISSUE TITLE
Eraser tool doesnt work

### ISSUE THREAD

**Issue by AzibK** [photopea/photopea#1951]
Eraser tool doesnt work when I use it. Fix it thanks

**Comment by photopea** [comment]
Hi, I just tried and it works for me. Are you sure you selected the right layer, when erasing?

**Comment by AeonCaptain** [comment]
Reload the page, or if you don't want to lose your work, save the file as a .psd and open again after reloading. Always works for me.

**Comment by photopea** [comment]
@AeonCaptain if you wound any bugs, which make you reload the page, please, try to find a way to reproduce these bugs, and report them to us :)

**Comment by photopea** [comment]
I have to close it because of lack of details.
