### ISSUE TITLE
When opening .ico files, it uses the smallest size

### ISSUE THREAD

**Issue by AeonCaptain** [photopea/photopea#1952]
I am editing some icons. In file explorer they look like this:
![2020-02-27 (2)](https://user-images.githubusercontent.com/56273352/75505805-7d94e600-5999-11ea-85cf-3511b8a4fc5d.png)

In photopea, it looks like this:
![2020-02-27 (3)](https://user-images.githubusercontent.com/56273352/75505862-a321ef80-5999-11ea-8100-c91427aae25d.png)
These are both cropped screenshots.

**Comment by photopea** [comment]
Hi, could you share such ICO file with us?

**Comment by AeonCaptain** [comment]
Sure thing, I'm pretty sure it uses multiple sizes: https://drive.google.com/file/d/1fZUkl0FfttXI9psu11_d6Lwj_zwo--3H/view?usp=sharing

**Comment by photopea** [comment]
It is fixed now :)
