### ISSUE TITLE
Add export to XCF

### ISSUE THREAD

**Issue by tkzv** [photopea/photopea#1954]
It would be nice to be able to export images to GIMP XCF format too.

**Comment by photopea** [comment]
Sadly, XCF format can not represent many features of Photopea, such as Layer Styles, Adjustment Layers, Smart Objects, etc.  If you saved your document as XCF from Photopea, and then opened it back, it can look very different.

Can you suggest Gimp developers to improve their support for PSD (which is the main format for Photopea)?

**Comment by photopea** [comment]
I will close it, as I think it is not a good idea.

**Comment by tkzv** [comment]
> Sadly, XCF format can not represent many features of Photopea, such as Layer Styles, Adjustment Layers, Smart Objects, etc. If you saved your document as XCF from Photopea, and then opened it back, it can look very different.

At least the former two are currently in the works and are likely to be presented this May.

But what I suggested was an export with partial feature loss. The supported features (e.g. text objects) are exported as they are, the unsupported ones are somehow approximated with irreversible changes (e.g. layer effects are applied to bitmaps).

> Can you suggest Gimp developers to improve their support for PSD (which is the main format for Photopea)?

That's likely to happen after May.

**Comment by photopea** [comment]
What exactly your goal is? If you need a PSD to XCF converter, I think GIMP should just improve the PSD support.

If you need just to edit images, use Photopea and store your work in PSD. If you miss any GIMP features in Photopea, let us know and we will add them.

**Comment by tkzv** [comment]
I need an offline took for collaborative editing of comics, when some team members use Photoshop. Going online once in a few days to convert is OK. Staying online for hours is too long.

**Comment by photopea** [comment]
Photopea works offline, but you should open it when you are online. Many people have it opened in a browser all the time, even if they are offline for weeks.
