### ISSUE TITLE
Save as JPG doesn't work

### ISSUE THREAD

**Issue by Dida83** [photopea/photopea#1955]
Hi guys, 
When I first saved in JPG the "save as ..." window was opened to choose position and name.
Today it is saved in a "Downloads" folder and opens the Win Photo viewer.

It is not comfortable :-( I would like to choose the folder and the name to save

**Comment by photopea** [comment]
How do you save JPGs? Do you press File - Export As - JPG?

**Comment by Dida83** [comment]
> How do you save JPGs? Do you press File - Export As - JPG?

Yes exactly :-)

**Comment by photopea** [comment]
The mechanism of saving depends on the settings of your browser. You probably changed it, or reinstalled a browser.

Go into your browser settings and set it to ask you about the location of saved files each time you save files.

**Comment by Dida83** [comment]
The browser setting are correct...but "Automatically open this file types" (I presume the image file types) option was selected.
Now everything works perfectly again
Thank you so much

**Comment by photopea** [comment]
Great :) It is important to know about the settings of your browser, as it is usually the program you use the most.

**Comment by Dida83** [comment]
Right, this option had eluded me, I've never changed it in the past
👍 )
Thanx :))
