### ISSUE TITLE
psd files won't open & files freeze when editing

### ISSUE THREAD

**Issue by coachju** [photopea/photopea#1958]
When I am making edits the file freezes and won't allow me to edit it. The saved version of the file that is froze will not allow me to open it

**Comment by photopea** [comment]
Can you send a PSD, which makes Photopea freeze, to support@photopea.com ?

**Comment by coachju** [comment]
Jalisa Mitchell

Assistant Women’s Basketball Coach

Moberly Area Community College

101 College Avenue

Moberly, MO 65270

Office: (660) 263-4100 Ext. 11553

Fax: (660) 263-32408

Cell: (314) 456- 7730

**Comment by photopea** [comment]
Hi Jalisa,

I was able to open your PSD file in Photopea without any problems. Please, try to do it in Incognito mode. If it works in Incognito mode, then, some of your browser extensions are breaking Photopea. Try to disable them.
