### ISSUE TITLE
Can't zoom in/out with Ctrl + Spacebar + (L/R)MB when Adjustment Curves/Levels window is opened

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1959]
Everything is in the title + can't use spacebar to move zoomed in photo view.
Photopea is sampling tones (black/white/mid). Shortcuts should work with window for Curves/Levels is opened.

**Comment by photopea** [comment]
Some adjustments require clicking into the image to select a black / gray / white point.

I made the "fast tool shortcuts" override the need of mouse of an adjustment.

I hope there is no window, which performs a custom task, when you click into the image with Ctrl+Spacebar.

**Comment by MichalSZZ** [comment]
Thank you very much!
I use Zoom In for sampling perfect black or white places.
Trick with treshold help me for seeking them. https://photoblogstop.com/photoshop/accurate-white-balance-adjustments-in-photoshop
