### ISSUE TITLE
Inverted reaction for Ctrl + Spacebar + Mouse Button shortcut when Zoom Toll is set to "minus" 

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1960]
1. hit Z and mark "minus" icon to zoom out when clicking LMB on the stage
2. change tool to any other
3. Try to zoom in with Ctrl + Spacebar + Left Mouse button

Shortcut for Zoom In work incorrect (has inverted functionality)

**Comment by photopea** [comment]
Fixed, thanks!
