### ISSUE TITLE
Changing color from swatches pallete

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1961]
When I create my own color swatches to speed up my work (e.g. primary, secondary color for webdesigns) it should work on active layer.
For example - I have text layer and want to change it color to something from my previusly defined in swatches. In photoshop I can click on color in swatches and text is changing. Same thing with shapes, gradients (clicking with Alt changes second gradient color).

**Comment by photopea** [comment]
Hi, when I select a Text layer in Photoshop, and click on swatches, the text color does not change. Photopea works the same. So what exactly do you mean?

**Comment by MichalSZZ** [comment]
Maybe it is a new feature in CC 2020? At work I have CC from 2016. Tommorow I will look in older version. That what I was wrote I have in newest PS

**Comment by photopea** [comment]
What if you want to put a Swatch color to a foreground color, instead of re-coloring the text layer? You would have to select a non-text layer? It does not make any sense to me.

**Comment by photopea** [comment]
I will close it because of lack of details.
