### ISSUE TITLE
Text Tool crashes site.

### ISSUE THREAD

**Issue by mavila20** [photopea/photopea#1962]
Every time I try to type in the type tool, the whole site just crashes and I can't do anything to fix it. I tried deleting cache but no luck.

**Comment by photopea** [comment]
Try to use Photopea in Incognito mode. Many browser extensions can break Photopea.

**Comment by photopea** [comment]
I am quite confident, that it was because of a browser extension. 90 % of issues that users report to us are because of extensions.
