### ISSUE TITLE
Feature Request: Interpolation options for "Move" tool or "Edit > Preferences"

### ISSUE THREAD

**Issue by daniel-christianson** [photopea/photopea#1963]
Note: Interpolation options already exists in Photopea when using "Image > Image Size" from the main menu, but the options can't be specified when transforming a layer or selection.

This request is to add the ability for interpolation options when transforming a layer or selection. This could be implemented to the "Move" tool specifically, or as an entire document option in the "Edit > Preferences" menu.

**Comment by photopea** [comment]
Hi, I guess you have "Transformation controls" enabled in your move tool, and when you start "resizing" an object, it switches to a Free Transform tool.

Note, that there is an interpolation dropdown menu in the top menu, after you start resizing (after switching to Free Transform tool). Can you see it?

**Comment by daniel-christianson** [comment]
Hi, thanks for the speedy response! Yes, I was using the "transform controls" check box with the Move tool (what I'm used to from a certain other program). I forgot to check "Free Transform" to see if there were additional options. :)

I guess It would be niiice if it could be added to the Move tool or Edit > Preferences? But it would just be a 'quality of life' change at this point for more clarity. I'm glad the option exists.

Thanks for showing me that! Feel free to close this request if you don't plan to make any changes.

**Comment by photopea** [comment]
Since it is already available in the top menu, I think there is no need to have it twice.
