### ISSUE TITLE
Duplicating smart objects saves changes to both of them

### ISSUE THREAD

**Issue by QuantumInformation** [photopea/photopea#1966]
When I make a change to one of them it makes it to the other one exactly the same

![image](https://user-images.githubusercontent.com/216566/75965482-c9c3b700-5ec0-11ea-9cf5-95247a70915a.png)

![image](https://user-images.githubusercontent.com/216566/75965569-e2cc6800-5ec0-11ea-9380-8f46e0b24f61.png)

**Comment by photopea** [comment]
Yes, that is exactly the point of Smart Objects - to change multiple instances just by modifying one image source. See https://www.photopea.com/learn/smart-objects

**Comment by QuantumInformation** [comment]
Ah I see, is there any way to clone them then?

**Comment by MichalSZZ** [comment]
> Ah I see, is there any way to clone them then?

@QuantumInformation that should works for you 
https://github.com/photopea/photopea/issues/923
"duplicate smart object via copy"

**Comment by photopea** [comment]
Yes, you can right-click a layer and choose "New Smart Obj. via Copy", to make an independent copy of the source of the smart object.

But the simplest solution is not to create a smart object at all, and have it as regular pixels (or rasterize an existing smart object).
