### ISSUE TITLE
photopea issue

### ISSUE THREAD

**Issue by asdxghj** [photopea/photopea#1967]
everytime i click for a text layer, It keeps zooming into a grid that i can't zoom out or get rid of .

**Comment by photopea** [comment]
Hi, can you send us your PSD file to support@photopea.com ?

**Comment by photopea** [comment]
I think I maybe fixed it. Can you try it again? It was probably related to some non-latin text with ligatures.

**Comment by asdxghj** [comment]
[image: Annotation 2020-03-05 191656.png]

**Comment by asdxghj** [comment]
thank you so much, It's fixed now.

**Comment by photopea** [comment]
Ok, I am glad it works now. Thank you very much for reporting it! 

I was fixing this issue today https://github.com/photopea/photopea/issues/1942  but made a mistake.
