### ISSUE TITLE
Changing work path to normal path by dragging work path on file icon in path window

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1969]
By dragging by the first time it should create new (normal) path (in the place of the work path).
Now it's create empty path.

2nd time and more. It should duplicate path in that window.

And I can't drag and copy when holding on path name in FF on Windows 10. In Chrome PWA works good.

**Comment by MichalSZZ** [comment]
@photopea Can you look at this issue?

I need to copy a path in the path palette (it is related with this old issue)

1. make some shape
2. go to path palette
3. try to drag and drop path from that shape layer by dragging it to the bottom (on the new file icon in a path palette)

the result should be as a same path (copy)
I have now empty path

**Comment by photopea** [comment]
Both should work well now :)
