### ISSUE TITLE
Fullscreen not working on Photopea on Chromebook

### ISSUE THREAD

**Issue by wernight** [photopea/photopea#197]
Photopea running as a standalone app window in Chromebook seems to intercept the fullscreen button (Chromebook fullscreen button). It's the first app that I've seen that seems to disallow fullscreen mode. This means that I've always an extra bar on top visible taking space.

It's also blocking all other standard Chrome OS shortcuts like:
 - Ctrl + Alt + ? to show help
 - Alt + 1..9 to start app
 - Alt + [/] to split screen
 - ...

**Comment by photopea** [comment]
Right now, Photopea tries to prevent the default behavior for all keys except of "F1","F2","F3","F4", "F5","F6","F7","F8",   "F9","F10","F11","F12", "Enter", "Shift", "Escape", "V" .

Could you go here: http://jsfiddle.net/p45f44zb/  and tell us the "key" values of other keys, that we should not prevent?

**Comment by wernight** [comment]
It cannot be captured by a normal browser window. Only the Photopea Chrome App has this issue.

**Comment by photopea** [comment]
So can you run that JSFiddle link as a Chrome App to see the key name of the Fullscreen button?

**Comment by wernight** [comment]
Not possible as per my comment on #196

**Comment by wernight** [comment]
Correct. I know no easy way to start JSFiddle as standalone app on Chromebooks. 

However I can debug and found the obfuscated function in pp.js preventing event for `ZoomToggle`.

It seems that `return d.TS.indexOf(C) == -1` only returns false if it's a function key or escape and else just preventsdefault.

**Comment by photopea** [comment]
Yes, you can see it in the code:
    
    d.TS="F1 F2 F3 F4 F5 F6 F7 F8 F9 F10 F11 F12 Enter Shift Escape V".split(" ");
    function(C){  C=d.Ta(C);  return d.TS.indexOf(C)==-1  };

Photopea does not prevent the keys from d.TS . So if I knew the key property of that fullscreen key, I can add it to the list. BTW. what is ZoomToggle?

**Comment by wernight** [comment]
`ZoomToggle` is that key on Chromebooks.

What is does is: 

        if (d.Tu(C.key)) {
            C.preventDefault()
        }

        d.TS = "F1 F2 F3 F4 F5 F6 F7 F8 F9 F10 F11 F12 Enter Shift Escape V".split(" ");
        function d.Tu(C){  C=d.Ta(C);  return d.TS.indexOf(C)==-1  };

So `d.Tu(C.key)` will return true iff it's **not** F1, F2... So in all those cases it'll `preventDefault()` in that function:

    qV.prototype.oU = function(C) {
        var K = C.target.tagName.toLowerCase();
        if ((K == "input" || K == "textarea") && C.key != d.yQ)
            return;
        if (d.Tu(C.key)) {
            C.preventDefault()
        }
        this.fy.Te(C.key);
        this.oM("down")
    }

**Comment by photopea** [comment]
Yes. I just need you to somehow find the Javascript name of that Fullscreen Key. I.e. the value of a "key" property of the KeyboardEvent.

**Comment by wernight** [comment]
It's `C.key == ZoomToggle`. However instead of preventing almost all key downs (white listing) shouldn't it prevent only those known to cause trouble (black listing).

**Comment by photopea** [comment]
Do you mean `C.key == "ZoomToggle"` ? I am not aware of any standard variable ZoomToggle. BTW. how did you find it out?

Blacklisting is also possible. But the blacklist would be much larger than the whitelist.

**Comment by wernight** [comment]
I think it's fine to have a larger blacklist.

I found that key by debugging the JS when pressing the Chromebook zoom key: 
![image](https://user-images.githubusercontent.com/145667/27078007-59d6fcee-5032-11e7-8985-d349b20a89ab.png)

**Comment by photopea** [comment]
Hi, I have added the ZoomToggle into the whitelist. Does it work now?

**Comment by photopea** [comment]
I hope it works.

**Comment by wernight** [comment]
Fullscreen works, but PP still blocks a lot of system keys like:
 - Brightness up/down
 - Volume up/down/mute
 - Switch applications
 - Reload / backward / forward (those may be blocked on purpose and outside PP already)

I'd expect also advance

**Comment by photopea** [comment]
Ok, I added these new Chromebook key codes too.

**Comment by photopea** [comment]
BTW Werner, can you please upvote / write a review about Photopea here: http://alternativeto.net/software/photopea/ ? :)

**Comment by wernight** [comment]
I did already, and on Slant. :)

PP really got now to a level where I use it as my main image editor (partially because that way I don't need to learn yet another app depending on the machine I use).

**Comment by photopea** [comment]
Thanks! :) Let me know if there is any other problem.

**Comment by photopea** [comment]
BTW. If you log in, I can give you a premium account :)

**Comment by wernight** [comment]
Logged in 😄

**Comment by photopea** [comment]
Ok, you should have it  now :)
