### ISSUE TITLE
Can't copy and paste work path to the shape layer

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1971]
Copying or cutting normal path from one shape layer to onother works fine.

**Comment by photopea** [comment]
Hi, it should work, but make sure the Work Path is not selected in Paths panel. If both a Work Path and a Shape layer are selected in Paths, it it will paste into a Work Path.

**Comment by photopea** [comment]
So I believe that now, it works the same as in Photoshop.

**Comment by photopea** [comment]
I think it was because the work path was still selected.
