### ISSUE TITLE
Your Annoying Ad to Allow Ads (March-2020)

### ISSUE THREAD

**Issue by AppleAipei** [photopea/photopea#1972]
The first time (last week) I used your app there was no such annoying issue. I was thinking about how I could donate to the developer for the wonderful app. The second time (now) I use your app with my same pc, same browser (Chrome) of the same version, the ad asking to allow ads, pops up every 5 seconds, leaving your app totally unusable.

I read your comments at https://github.com/photopea/photopea/issues/1263. You were not sorry at all for the bug (by purpose or not) and you thought that your behavior (forcing users to watch ads, or forcing users to deal with your annoying ad to allow ads) has always been right.

When you force people in such a disgusting way to either watch your ad, watch other ads or straight away give you 10 USD or 20 USD, you are pissing off volunteers who use to make a one-time donation at any amount. I normally donate 5 Euro each time to the apps I feel grateful to use (twilight, split pdf, merge pdf, derivative calculators, Wikipedia, etc) and I hate being forced to pay.

I must warn you that, if you do not correct your backward fundraising method, you are just gonna be replaced anytime by anyone coming out with a similar good app (but free with options to donate any amount, most importantly users do not need to come to GitHub to learn that the developer has an unreasonable manner).

With your current behavior or mindset, you do not need to mention "for the future of Photopea", you are indeed making you and your app really vulnerable to any forthcoming competition.

**Comment by photopea** [comment]
Hi, thank you for your feedback. The amount of people who block ads is really quite high. I think that it is not fair, that some people watch ads and contribute to our efforts, while others get away with hiding ads, while receiving the same service.

Do you have an issue, when you are not blocking ads, but you still see that message? It is not quite clear from your report.

**Comment by rarkins** [comment]
I've turned off ad blocking for photopoea.com and not experienced any problems. What a wonderful site!

**Comment by photopea** [comment]
I will close it now.
