### ISSUE TITLE
Shift Key for uniform transform control isn't working

### ISSUE THREAD

**Issue by Jay-Dabo** [photopea/photopea#1973]
When resizing, the SHIFT key on the keyboard is used to initiate uniform transformation. However this doe not work anymore as the application does not recognize the key input command.

**Comment by Jay-Dabo** [comment]
Also the CTRL key for unique section of layers for a unified transformation edit cannot be recognized

**Comment by Jay-Dabo** [comment]
Basically, both keys (SHIFT & CTRL) do not work anymore

**Comment by photopea** [comment]
Hi, it works for me :/  Can you try it in Incognito mode, i.e. without any browser extensions?

**Comment by photopea** [comment]
I have to close it because of lack of details.
