### ISSUE TITLE
Magnetic Lasso selection lines now showing

### ISSUE THREAD

**Issue by beepboopbleep** [photopea/photopea#1975]
Points of selection and lines not showing
<img width="946" alt="Screen Shot 2020-03-08 at 9 35 42 PM" src="https://user-images.githubusercontent.com/61953600/76175844-cfe9ba00-6184-11ea-9fb7-25cf8aef1842.png">

**Comment by photopea** [comment]
Hi, can you try it in Incognito mode, i.e. without browser extensions?

**Comment by photopea** [comment]
I will close it because of lack of details.

**Comment by beepboopbleep** [comment]
Hi, I've tried this on incognito and different browsers, still the same issue.

**Comment by photopea** [comment]
What is the resolution of your photo? Can you waitt 3 - 5 seconds after the first click, if the lines appear?

Can you try to disable WebGL, if it helps? More- Use WebGL.
