### ISSUE TITLE
Type Tool Feature doesn't work properly

### ISSUE THREAD

**Issue by MatanyaP** [photopea/photopea#1976]
This is somewhat new, yesterday worked fine. 
When adding a text layer via Type Tool, if clicking the mouse afterward it enlarges the screen and filling it with a grid for some reason.

I tried it with Chrome, Edge Legacy and Firefox. The same issue for all

![image](https://user-images.githubusercontent.com/11622812/76192696-1e31a400-61eb-11ea-930a-a5d566f06386.png)

**Comment by photopea** [comment]
Hi, does it happen for a specific PSD file? Could you send your PSD file to support@photopea.com ?

**Comment by MatanyaP** [comment]
It happens with any new or existing file.  I've tried it a few times more, sometimes it works and at other times it presents the issue I described. Seems random.

**Comment by photopea** [comment]
When you open Photopea.com , there is "pea.psd" in the middle. After I click it, I enter the text layer, and I can edit text without any problem.

Can you try to do the same? If yes, then, it happens only for specific files.

**Comment by photopea** [comment]
can you try Photopea in Incognito Mode? I think some extension is doing this. Extensions can do anything they want with websites that you visit.

**Comment by photopea** [comment]
I will close it, as I think it was because of an extension. Feel free to add your comments!

**Comment by MatanyaP** [comment]
I have tried it without any extensions, but I guess it might be some local bug I'm experiencing because no one else has raised this issue. Anyway, I'm attaching this recording of it occurring, just in case...
![20200310_074832](https://user-images.githubusercontent.com/11622812/76283727-0e29cb00-62a4-11ea-9bf9-cf67966e9bbb.gif)

**Comment by photopea** [comment]
Actually, many people reported it, but then, they stopped responding.

Can you actually try it in Incognito mode? Not just with extensions disabled?

**Comment by MatanyaP** [comment]
I've tried it in incognito via all three browsers, the same effect. It feels to me as if it's somehow related to the loading of fonts. If you wait for the font to load and then a few moments more, then it usually keeps working correctly.

**Comment by photopea** [comment]
Thats correct, if the font is not loaded when you start typing, it will crash.

But fonts are small (often under 100 kB) and they should be loaded in under 0.1 second. That is why we dont even check if the font is loaded when you type, as it usually has to be.

**Comment by MatanyaP** [comment]
So maybe a solution would be to delay typing for a small amount of time, or rather to store the typed characters until the font is loaded and then input it to the place it should originally be. That might be overkill though...

**Comment by photopea** [comment]
In what country are you located? What is your internet speed? Does it take long to load Photopea.com for the first time?

**Comment by MatanyaP** [comment]
My actual speed test while testing it is ~70Mbps.
It takes quite a long time to fully load Photopea .com. According to a speed test, it's 7.7 sec.
But even if it would work correctly for higher speeds, it would be better to have some kind of "safety mechanism" for slower connections (if implemented easily, of course)

**Comment by photopea** [comment]
Ok, I will implement such procedure.

By the way, can you look into DevTools? Can you see, what makes loading Photopea so slow? Is it the DNS lookup, or time to first byte, etc?

In my case, Photopea fully loads in less than 2 seconds.

**Comment by MatanyaP** [comment]
I just realized... perhaps it's not optimized for mobile networks, and so even if you have are going to the website on a desktop and your home internet is mobile-based (like a sim card in a router that some providers sell as a home-internet), the loading time will be high because it's interpreted as a simulated-desktop or something weird like that. This was the case where I was experiencing the problem mostly. 

Here is a report of the audits using this internet:
[Untitled Document.pdf](https://github.com/photopea/photopea/files/4311809/Untitled.Document.pdf)

**Comment by photopea** [comment]
There are no "mobile netowrks" or "desktop networks", and you can not optimize for them. There are only mobile browsers, which are often slower than desktop browsers (execute code longer).

Your internet provider is probably slowing down Photopea to save money for traffic from distant locations. The speed 70Mbps is probably only for sites who have servers in your country. Maybe you could ask your internet provider about it.

**Comment by photopea** [comment]
@MatanyaP Could you tell me, in what country you are located?

When you open Photopea.com and do File - New, there are templates. They should contain text, rendered with our custom fonts, looking like this: https://i.imgur.com/vxEEQBh.png

Can you tell me, how long does it take you to see the templates with text, after opening a New Document window? If you never see text, do you see any errors in a browser console?

**Comment by photopea** [comment]
Now, this error should not happen anymore. Instead, Photopea will show you a message, that fonts are not loaded yet.
