### ISSUE TITLE
Cannot import Voga font

### ISSUE THREAD

**Issue by jolanca24** [photopea/photopea#1977]
Hello, 
I'm trying to import the attached font but keeps returning an error
[voga-cufonfonts.zip](https://github.com/photopea/photopea/files/4308163/voga-cufonfonts.zip)

**Comment by photopea** [comment]
Hi, I am able to use your font in Photopea without any problems. Do you use any browser extensions? Can you try it in Incognito Mode?

**Comment by jolanca24** [comment]
It's working now.
Thanks,
Joana
    On Monday, March 9, 2020, 07:46:07 PM GMT, Photopea <notifications@github.com> wrote:  
 
 
Closed #1977.
