### ISSUE TITLE
Publish URL issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1979]
If I open URL like this
`https://www.photopea.com/#`
or with some random number after "#"
`https://www.photopea.com/#123456`
 it will open slightly broken photopea (without ads!) and and after some clicking I am still able to use it to open and edit files.
See screenshot:
`https://www.photopea.com/#`
![image](https://user-images.githubusercontent.com/6370548/76390726-37169280-636e-11ea-9c3c-18e78b363aae.png)
Note:
After opening this URL I clicked twitce on "><" in top left then went to other browser tab and back. Menu appeared and I opened some template with File-New. Then clicked Window-Action and Layers window appeared...

**Comment by photopea** [comment]
Hi, I think I fixed it. Thanks for reporting!

**Comment by hxim** [comment]
Hi I just tried and
https://www.photopea.com/#
works
but this
https://www.photopea.com/#123456
has still same behaviour and shows this error:
Uncaught TypeError: Cannot read property 'plugins' of undefined
    at Bh.lrO (pp.js:9919)
    at Bh.lsq (pp.js:9901)

**Comment by photopea** [comment]
Currently, a valid URL ends either with
#i.... - then, we look for a published PSD document
otherwise, # should be followed by a JSON configuration

If somebody creates an invalid URL, I think it is not necessary to provide them an editor, as if there was no parameters at the end of the URL.

**Comment by hxim** [comment]
> Currently, a valid URL ends either with
> #i.... - then, we look for a published PSD document
> otherwise, # should be followed by a JSON configuration
> 
> If somebody creates an invalid URL, I think it is not necessary to provide them an editor, as if there was no parameters at the end of the URL.

Sure but I mean you maybe shouldn't provide almost working (slightly glitched) editor without ads I guess, and it should refuse to work at all in this case i think..

**Comment by photopea** [comment]
If people are willing to do all this just to avoid ads, I think they deserve to see Photopea without ads. We can not guarantee anything in this case.

**Comment by hxim** [comment]
@photopea 
One more thing I noticed when I put photopea in iframe it also opens with no ads. Is this also intended behavoiur because it seems people can put full photopea without ads (and without paying) on their site while photopea.com will have ads.
I tried it on this page https://www.iframe-generator.com/
![image](https://user-images.githubusercontent.com/6370548/76516204-48899880-645b-11ea-8e56-ff69d1a92227.png)
and clicked Preview there...

**Comment by photopea** [comment]
Hi, when in Iframe, Photopea shows an ad randomly in 50% of cases.

That is because people tried to cover our ad with their own ad (on top of the iframe). Now, when the ad is not certain, they risk covering the UI of the editor.

Also, ad companies do not allow having ads inside an iframe (it can only be in the most-top window), so we only show an ad for Photopea Premium.
