### ISSUE TITLE
Photopea.com keeps crashing when adding SmartObjects

### ISSUE THREAD

**Issue by Shawnee06** [photopea/photopea#198]
Hello...for some reason the Photopea.com app keeps crashing when I try to add smartobjects to my graphics.  Can you please check it...

I have rebooted my pc and restarted the program twice. Thanks!

**Comment by photopea** [comment]
Hi, I am very sorry. It is related to an update, that was made yesterday.

I have fixed it and it works now. Thank you very much for reporting it! :)

**Comment by Shawnee06** [comment]
Thanks sooo much! You guys are the BEST!!
