### ISSUE TITLE
Exported Layers allows to download assets.zip  with 0 images and throws exception when opening it

### ISSUE THREAD

**Issue by lemongrasslabs** [photopea/photopea#1981]
You can reproduce the issue by creating a new project with multiple layers, open "Export Layers", keep all settings default and export to assets.zip. When opening the zip, the alert below is shown and the zip cannot be opened.

The exportable layers were shown as 0. If the default 'Only laters / folders, whose name starts with "-e-"' is unchecked the zip file can be opened

System: macOS 10.14.06

<img width="411" alt="Screen Shot 2020-03-12 at 09 59 28" src="https://user-images.githubusercontent.com/57791404/76483217-022b3e00-6449-11ea-9304-cf1ff61a769f.png">

**Comment by photopea** [comment]
Thanks! I fixed it by not exporting any ZIP, when there are no layers to export (you will see a message instead).
