### ISSUE TITLE
Rasterized layer style issues after closing webgl

### ISSUE THREAD

**Issue by z411500976** [photopea/photopea#1982]
After closing webgl, when the layer style has a stroke, there is a problem with the rasterized layer style and it will become the fill color.

**Comment by z411500976** [comment]
![QQ截图20200312123420](https://user-images.githubusercontent.com/24216715/76487602-e0888180-645d-11ea-9ff2-bf7a34065148.png)
![QQ截图20200312123445](https://user-images.githubusercontent.com/24216715/76487604-e2eadb80-645d-11ea-898f-ea06dc44bbc4.png)

**Comment by photopea** [comment]
I fixed it, thanks for reporting!
