### ISSUE TITLE
Script saving offers text "[object ArrayBuffer]" as name

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1983]
First time it offered "script" as name for my script but after I saved and loaded some scripts it now offers 
`[object ArrayBuffer]`
as name of my script for some reason. see screenshot
![image](https://user-images.githubusercontent.com/6370548/76498096-81664500-643c-11ea-9f61-947ab93e6bfb.png)

**Comment by photopea** [comment]
Fixed, thank you! :)
