### ISSUE TITLE
PWA version - can't open shared link via "Open from URL"

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#1984]
When somebody send mi a link, when I click on it, new tab in browser is onening (my default system browser is FF but I work in PWA Chrome version in Photopea).
I wan to work with that link in PWA version. Can't do that because "Open from URL" with that link don't work for me.

BTW. Where that files are stored? How long that link will be work?

**Comment by photopea** [comment]
I am afraid the web technology does not allow to do this now. You want multiple links to open in the same window, but also in a different browser. That means breaking basic web rules, which did not change in 30 years.

I made Photopea detect special URLs like  http://photopea.com/#iVjChu0Vl  and you can open them with File - Open From URL now.

We store our files at https://www.backblaze.com/ . I would like to store the PSDs for as long as possible, but I can not guarantee anything at the moment. I will see how much this feature is used. Ideally, I would like to delete a file, if it has not been opened for more than a year (so it is stored for at least a year).

**Comment by MichalSZZ** [comment]
Thx.
Now I can open link when paste it in "Open from URL". Before that didn't work.
I dont want anything more :)
Thank you

**Comment by photopea** [comment]
People uploaded about 150 files, around 140 MB, in the last 30 hours :) I am quite excted. Although, now, I dont track how many times files were opened :D

**Comment by MichalSZZ** [comment]
Probably many of them, only trying possibilities.
Don't you think that option (creating links, not opening) should be only for premium users if transfer/space will be to big?

**Comment by photopea** [comment]
There are services for sharing images with a link: Imgur.com , or sharing text with a link: https://pastebin.com/  . They all are free. So I thought we could offer PSD sharing for free.

Currently, Photopea remembers your foreground/background colors after closing (several characters like #ff00ff). If we make it remember the IDs of your uploaded files (e.g. 100 more characters), we get a cloud storage (you can open, edit, save all your files in the cloud).
