### ISSUE TITLE
Leading in Character window

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1986]
It seems this value can't be changed without keyboard by just using sliders - you need to write your number on keyboard here to change this value (and this looks to be only place in entire application behaving like this). Also if you want to reset this value to "Auto" you need to know that you need to type text "auto" here. This is very uncomfortable and would be great if
a) sliders were available as everywhere else
b) you could reset to Auto be different more simple mechanism (for example deleting number would reset to Auto or small button next to it, double click or something else i don't know)
![image](https://user-images.githubusercontent.com/6370548/76501949-76fb7980-6443-11ea-9c32-a30b5a57f98b.png)

**Comment by photopea** [comment]
Actually, this field changes two values: Leading value (number) and Auto-Leading (boolean). When Auto-leading is true, the Leading value is ignored and the Leading is used from the font parameters.

Do you think we should add a checkbox for Leading?

**Comment by hxim** [comment]
Ideally i would keep one field with sliders and when you delete value it would change to auto. If it is not possible or too hard checkbox and value would be also good imho

**Comment by photopea** [comment]
I added a checkbox for Auto value.
