### ISSUE TITLE
heic format

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#1987]
Hi,

some of our customers send me photos in HEIC format. 
Do you know about it? It would be great to have support for convert.

https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format

Thanks

**Comment by photopea** [comment]
Hi, HEIC is a proprietary format and everybody, who wants to create HEIC files, hast to pay a licence fees. There is almost no sofware that can view HEIC files. Also, it is about 50x more complex than JPG. I think it will never become as popular as JPG, and that it is a "dead end".

Your HEIC images are probably photos from iOS cameras. Just tell the people to switch the settings to JPG instead. We should really avoid every phone manufacturer inventing their own image format.

**Comment by landsman** [comment]
I did this for convert: https://fitzcarraldoblog.wordpress.com/2019/01/15/heic-image-files-in-linux/

**Comment by jaredlt** [comment]
For future iOS users viewing this thread.

To switch from HEIC to JPEG (for all future photos - doesn't affect already taken):

`Settings > Camera > Formats > Most Compatible`

NB. This will also change the settings for future video files (from HEVC to H.264)

**Comment by photopea** [comment]
You can open HEIC now! It is available in a plugin by @hxim . Press Window - Plugins, and choose "JPEG XL, AVIF" plugin. An icon will appear in the right bar, which lets you load HEIC images.

**Comment by Kevogich** [comment]
> 

Anyone still getting an unknown format error with lots of zeros ?

**Comment by photopea** [comment]
You should use the heic plugin to opeh heic files.

**Comment by TomasHubelbauer** [comment]
@photopea Is there any chance Photopea could recognize the extension or the magic bytes of HEIC and tell you to use the plugin to load it? Right now you only get an error and if you don't search around to see there is the plugin, you'll never know Photopea can work HEIC files.

That being said, even with the plugin install, I couldn't open my particular HEIC file. I got this error:

> Unknown file format: "\u0000\u0000\u0000("

@hxim does this mean your plugin didn't kick in or is my file not compatible with it?

**Comment by photopea** [comment]
I recommend to start taking photos as JPG as soon as possible, and convert all HEIC you have to JPG, as soon as possible, too. There are many online tools.

**Comment by TomasHubelbauer** [comment]
That's awesome! Tested it and it works great. One thing I noticed is when I open the HEIC image, the tab name is the file's name but the extension is shown as PDF. No biggie, just an observation in case that's not intentional.
