### ISSUE TITLE
I can't open any psd files, jpgs, pngs or create new

### ISSUE THREAD

**Issue by masterjune70** [photopea/photopea#1989]
I was working on some stuff and it was working fine. I've been working in the incognito window. I've tried restarting my computer, using the usual Chrome browser etc. but I can't get Photopea to work. It opens the main screen, allows me to create new - then when I choose the paper/screen size nothing. If I try to open up a recent file (PSD or Png or Jpg) nothing opens.
I hope you can help me with this issue.

Cheers.

**Comment by photopea** [comment]
Hi, I am very sorry, it is fixed now.
