### ISSUE TITLE
Layer previews are blank on chromebook

### ISSUE THREAD

**Issue by userword** [photopea/photopea#199]
When i go to the layer window no matter what is in the windows the preview is blank

**Comment by photopea** [comment]
Hi, can you show us the screenshot? Are previews of text layers / masks also blank?

**Comment by userword** [comment]
![screenshot 2017-06-04 at 10 07 28 am](https://cloud.githubusercontent.com/assets/29177923/26764356/2f800d72-492b-11e7-8ede-29b5d00c58d4.png)

**Comment by photopea** [comment]
Thanks. Can you tell me, what is your device pixel ratio? you can see it here: http://devicepixelratio.com/  Is it 1.25?

**Comment by userword** [comment]
my ratio is 1

**Comment by photopea** [comment]
The same thing with thumbnails happens to me, when I set the page zoom to 90% and reload the page. I will try to fix it for this case and I think it will fix your case, too.

**Comment by userword** [comment]
Ok thank you I will try to resize my page and see if that works

**Comment by userword** [comment]
It worked! I just had to zoom in a little.

**Comment by photopea** [comment]
Fixed. Now, thumbnails are correct even if you don't zoom in.
