### ISSUE TITLE
not opening a new project/picture

### ISSUE THREAD

**Issue by outropastel** [photopea/photopea#1992]
I wanted to use photopea to make a transparent emoji but it wouldn't let me open up a new project. Is this a bug?

**Comment by lilsolis** [comment]
i'm pretty sure it is! i'm rather irritated by it.

**Comment by GreenPuke** [comment]
Me too! I even paid for this crap

**Comment by obiwanbrenobi** [comment]
Happened to me too!

**Comment by photopea** [comment]
Hi, I am very sorry, it is fixed now.
