### ISSUE TITLE
Anti-aliasing

### ISSUE THREAD

**Issue by Moonie68** [photopea/photopea#1995]
Hi, I noticed that when trying to follow [this tutorial](https://www.youtube.com/watch?v=nN8Vf6c3tko) there was no anti aliasing, as shown by the result. Is it possible to fix? Thanks!
![New Project](https://user-images.githubusercontent.com/58180094/76709218-a79d1680-66c2-11ea-9319-b20129d49938.jpg)

**Comment by photopea** [comment]
Hi, could you save it as a PSD and send it to us to support@photopea.com ?

**Comment by Moonie68** [comment]
I sent it.

**Comment by photopea** [comment]
Hi, I changed the mechanism of Bevel and Emboss, I think it looks better now.

![image](https://user-images.githubusercontent.com/15955558/76745353-07a0c500-6776-11ea-8aac-65a2392eb120.png)
