### ISSUE TITLE
Arabic language

### ISSUE THREAD

**Issue by Snoker87** [photopea/photopea#1996]
Hello, there's a problem in your program when you write in the Arabic language it's a simple issue. the space between the letter should be removed, http://prntscr.com/rgvxy9
the spaces should've between the words, not letters as you see in the link.

**Comment by photopea** [comment]
Hi, is it like this with all fonts? Have you tried to use a different font?

**Comment by Snoker87** [comment]
Yup the issue on all fonts.

**Comment by photopea** [comment]
Can you please write me your text in Arabic, so that I try it myself?

**Comment by Snoker87** [comment]
"اهلا بكم"

**Comment by Snoker87** [comment]
"مرحبا بكم"

**Comment by photopea** [comment]
It seems like you increased Tracking (spacing between letters). Set it back to 0 in Characters panel and it should look well.

https://www.photopea.com/learn/text-style
