### ISSUE TITLE
Store layer styles into a PDF

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1998]
Aside for changing a little the color when exporting to pdf (that may be the chrome pdf viewer) the layer effects, in this case glow (the shadow) is missing after exporting.
![image](https://user-images.githubusercontent.com/11801254/76823226-55f3a980-67f2-11ea-9841-a8b9906bd623.png)

I am attching the PSD on wetransfer
https://wetransfer.com/downloads/e3a9cfe14878695b81f2eddef066e5e520200317045824/581bae0381923786414608da9e496e0b20200317045824/b25908

**Comment by photopea** [comment]
Hi, the PDF format does not support "shadows", like SVG does.

Editors store shadows into a PDF as semi-transparent bitmaps. Would you like Photopea to store them also as bitmaps?

Then, if you open such PDF in Photopea, the shadow will be just a bitmap layer, and it will not be linked to the "main object".

**Comment by avagp** [comment]
Yes!

**Comment by photopea** [comment]
I was thinking about it, and I think there are tons of features, that can not be reasonably stored in a PDF: layer styles (bevel and emboss, glows and shadows - they all would need to be rasterized), adjustment layers, some blend modes, smart filters, text stye (text warp) etc.

If you want to export a complex document, and make it pixel-perfect, enable "rasterize all" during the export.

**Comment by avagp** [comment]
I will check with my provider if when I send it rasterized I lost quality.

I used Gravit yesterday to see how it handles layer effects, and when a
layer has an effect it gets rasterized (the main and the effect merge) only
that layer. The rest keeps vectorised.

But it totally loose quality.

I will keep you informed :)

**Comment by photopea** [comment]
There is no other way to put a shadow into a PDF, you can only rasterize it.

**Comment by avagp** [comment]
Hi Ivan.

i would like to reopen this issue.

I have talked with my providors and i need to be able to export as much as possible as vectors. Shadows and other effects can be rasterized.

The thing is. Most of the time they have to rearrange my design in order to print it, separate it by parts or change shape strokes for the cutting.

And when i raterize all the design they loose the ability to edit some elements.

This should happen to anyone who works on printing.

Maybe there should be a 4th option when exporting on PDF to check if the effects are rasterized.
![image](https://user-images.githubusercontent.com/11801254/78709489-bd78b280-78e1-11ea-8de7-0732ed875ba8.png)
 
How difficult is to implement this?

**Comment by photopea** [comment]
In Photopea, you can right-click the layer and choose "Rasterize Layer Style". It is hard to convert a PSD to a PDF. Some Blend Modes of PSD do not exist in PDF. The "rasterize all" is the only reliable option to make sure everything looks the same.

Have you thought about delivering a PSD to your providers? The PDF files were not meant to be edited.

**Comment by avagp** [comment]
Well, thanks for the advice. I will be rasterizing the effects before sending.

I have tried before to send the PSD, but they they use a vector program and i have tried opening my PSD on AI, and sometimes it gets it all wrong. :/

The point for me is: Even if i try to correct everything before sending (like vectorize text and rasterize effects) it is not only a lot of work, but i have to change it back to be editable after sending.

Or open the final version, convert everthing, and then not save. But when i have to change something to send it again, i will have to convert everything all over again.

I know it can be achievable, but is not comfortarble. 

Maybe i should try Gravit    :/

**Comment by photopea** [comment]
I have never tried Gravit, but you should definitely try it.

Photopea is not as capable as Adobe Illustrator. I don't know if it is a good idea to add all those PDF-related features, while other editors (like Photoshop) just rasterize everything into a PDF.

**Comment by avagp** [comment]
Ok, i have used Premiun Gravit the last 3 hours.

Photopea is better hands down.

Besides it is way sluggish, i encountered various bug while playing around and one crashed my browser.

Ok, enough trash talk.  :)

I am asking you for help.

In Grvit they have this option. Similar to the one i proposed
![image](https://user-images.githubusercontent.com/11801254/78725914-bca24980-78fe-11ea-8b11-c929139dfe81.png)

When including the effects, you get them rasterized on the layer or path.

I was trying to do the same on photopea, one by one, but i encountered a problem with the way i work.
![Screenshot 2020-04-07 at 18 26 09](https://user-images.githubusercontent.com/11801254/78726022-f8d5aa00-78fe-11ea-9801-7fe60b2e7ceb.png)

I set the effects on the folder  :/

So, in order to rasterize the effect on the image i have to copy and paste the effect on each layer.

In synthesis, if it is hard to create an option when exporting to rasterize each effect on the layer, maybe i could ask for an option to be able to apply/transfer the layer effect from the folder to the layers it contains?  😋

**Comment by photopea** [comment]
By the way, could you try to use Figma? It is a more vector-ish editor. I think it could be much more appropriate for editing vector graphics.

Premium Gravit? Why don't you simply pay for Adobe Illustrator? :D

**Comment by avagp** [comment]
One word: Chromebook

**Comment by avagp** [comment]
And Figma does not have text on path :(

**Comment by photopea** [comment]
Ok, I will add an option to store rasterized layer styles into a PDF.

**Comment by avagp** [comment]
Yuhu!

ლ(^o^ლ)

**Comment by photopea** [comment]
Hi, rasterized layer styles should now be added into a PDF :)

**Comment by avagp** [comment]
I love you! !!!

**Comment by photopea** [comment]
I love you for not giving up when trying to convince me, that it is an important feature! :)

**Comment by avagp** [comment]
How i achieve it?

**Comment by photopea** [comment]
It should automatically export most of layer styles. For text layers, styles are exported only if you check Rasterize or Vectorize text layers (to make sure they correspond to how you see them in Photopea).
