### ISSUE TITLE
Pen Tools.

### ISSUE THREAD

**Issue by ShoriFlare** [photopea/photopea#200]
As I was trying to edit something with the pen tools they would simply not work out for me and they would instantly fill in as a shape no matter what I tried with them. I sat here for a good few minutes and I just could not sit here and use it, so I wonder if you are going to try and make it similar to PhotoShops pen tool because that'll be a lot easier for me to use [https://www.photopea.com/](url), that is all I wanted to ask and needed to know as for that tool.

**Comment by photopea** [comment]
Hi,
the Pen tool in Photopea should work similarly to the Pen tool in Photoshop. What exactly is different?

Each vector drawing tool (in Photopea and in Photoshop) has a mode: Path / Shape / Pixels. Maybe you need a different mode?

You can find the complete explanation of Vector Graphics in Photopea here: https://www.photopea.com/learn/vector-graphics .

**Comment by ShoriFlare** [comment]
I have attempted to use the other modes for the pen tool and I simply cannot work with them as well as I could with Photoshop, I'll give an example to show what my problem is with it to hopefully make it a bit easier to understand rather than explaining.
![screenshot 2017-06-05 at 12 41 46 pm](https://cloud.githubusercontent.com/assets/29206469/26793564/6bae35d2-49ec-11e7-86f0-cad7f0435c88.png)

I am simply trying to make a line to change the color as a highlight to show where the outlines would be but either way I cannot change the color nor will it just make a simple line so that when I do go back to fill it all in I can add detail lines to it but it will simply no cooperate with me.

**Comment by photopea** [comment]
So you have made an open path. Now you can choose the Path Select tool and change the Fill (color, gradient, pattern or no fill)  and change the Stroke.

In Photoshop, each tool has Fill / Stroke options, but in Photopea, only Path Select has these options.

**Comment by ShoriFlare** [comment]
Okay so I have it how I want it but the only thing that is left is me needing to figure out how the line will only show where I put the path. If I do color it makes a shape but I don't want that; I just want a line so that I may fill it either to change the color tone to make it more detailed.

![screenshot 2017-06-05 at 12 55 51 pm](https://cloud.githubusercontent.com/assets/29206469/26794088/5ca8f87c-49ee-11e7-9810-e35290a29491.png)

**Comment by photopea** [comment]
Each shape has two properties: Fill and Stroke. You disabled the fill, so now you need to add a Stroke. It is next to the Fill (in the top menu of the Path tool).

Read the full tutorial at the link, which I sent earlier. It will take you 30 minutes to read, but it will save you hours of asking and struggle in the future.

**Comment by ShoriFlare** [comment]
I will read it then, if I have anymore questions I will just come back to here rather than just making a new one. Thank you for your assistance.
