### ISSUE TITLE
I can't take a photo

### ISSUE THREAD

**Issue by nick497** [photopea/photopea#2001]
just please fix it

**Comment by photopea** [comment]
Hi, do you mean taking photos with File - Take a picture? Did you give Photopea permissions to use the camera?

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by nick497** [comment]
yeah when I pressed the allow camera button and reloaded the site it still
said "access to camera denied."

**Comment by photopea** [comment]
Are you using Photopea on a desktop or on a phone? Can you try it in Incognito mode?
