### ISSUE TITLE
Interface of menu error

### ISSUE THREAD

**Issue by icypyh** [photopea/photopea#2003]
![圖片](https://user-images.githubusercontent.com/31072546/77144478-f848b100-6ac0-11ea-9dd9-71c5e63342e6.png)
The menu in Traditional Chinese is now presenting as the picture. The first button (file button) should be displayed as "檔案" and cannot be adjust.

**Comment by photopea** [comment]
Hi, it seems like some vandalism in our translations.

But somebody already fixed it at www.Photopea.com/translate, so I updated a new version from there.
