### ISSUE TITLE
Error when delete and Free Pen

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2007]
1.) Open New project
2.) Select Free Pen tool
3.) Create path with Free Pen tool
4.) Select Type Tool
5.) Click on created path and write some Text on Path
6.) Select Path Select tool and select the path in text layer
7.) Move that path
8.) Select Free Pen tool
9.) Press Delete key on keyboard
10.) Error as seen on screenshot

![image](https://user-images.githubusercontent.com/6370548/77289835-0bcf6400-6cdb-11ea-819c-10ec88063d0a.png)

**Comment by photopea** [comment]
Fixed, thank you! :)
