### ISSUE TITLE
Empty path for text selection errror

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2008]
1.) Open New project
2.) Select Free Pen tool
3.) Create path with Free Pen tool
4.) Select Type Tool
5.) Click on created path and write some Text on Path
6.) Select Path Select tool and select the path in text layer
7.) Press Delete key on keyboard
8.) Right click with mouse and select Make Selection
9.) Error as seen on screenshot
![image](https://user-images.githubusercontent.com/6370548/77290553-b5fbbb80-6cdc-11ea-91b8-865adde4a62c.png)

**Comment by photopea** [comment]
fixed, thank you :)  I wish everybody described bugs as nicely as you do!
