### ISSUE TITLE
Exports not saving unless restarting Photopea

### ISSUE THREAD

**Issue by McLeanUser** [photopea/photopea#2009]
I frequently work on projects with multiple images that I need to export as JPGs or PNGs for web use.

Photopea works great for me, except that exporting an image only works the first time I use the export function.

If I try to export another image, I get the dialog box checking my settings (e.g. resolution, size, etc.), but then never get to the Windows folder function where I can designate the location for the new export unless I completely shut down Photopea and restart it.

I can escape from the settings dialog and continue working, and I've tried closing the current image, opening a different one and exporting that one.  But the same outcome: I basically can't get to designating the location and I have to shut down the program and start it up again to export my next image.

Kind of inconvenient.  

NOTE: I'm on Windows 10 Personal Edition, use Chrome as my default browser.  The situation above is exactly the same whether I start Photopea by logging in on the browser, or starting from the downloaded version.

**Comment by photopea** [comment]
Hi, I think a similar problem has been reported before. I think it is a part of the effort of browsers trying to "protect you from evil websites".

Somewhere in the Chrome UI, there should be a message saying, that a website is trying to save multiple files. Try to open it and allow the saving of files.

Let me know if it helped.

**Comment by McLeanUser** [comment]
Thank you for putting me on the right path!  I seem to encounter new automatic protections that slow me down in software everyday. But I guess on-balance, I'll take them over the alternative.

On to the solution (for me, at least): 

Step 1: in Chrome click the lock icon to the left of the URL in the address bar.  On the drop-down menu that appears select allow, next to "Automatic Downloads".  Escape or "x" out of the drop-down.

Step 2: Chrome presents a message with a button in that upper-left section of the screen telling you to reload the page to apply the change.  Do that, and the problem of saving and exporting multiple files from Photopea should go away.

Screen shots below.


![automatic-downloads-selection](https://user-images.githubusercontent.com/62556688/77754762-58c87880-7002-11ea-89e3-a3d83bd99a77.png)
![reload-to-apply-msg](https://user-images.githubusercontent.com/62556688/77754784-62ea7700-7002-11ea-8e8e-952858088aef.PNG)

**Comment by photopea** [comment]
I am glad it is solved. Strangley, in my case, Chrome always saved the files form Photopea for me, I never had to do a configuration such as yours.
