### ISSUE TITLE
Error in photoshop file:  wrong signature

### ISSUE THREAD

**Issue by izbarboza** [photopea/photopea#201]
I saved a .psd file created in photopea, containing layers with images and folders. When I tried opening this file today, I got the message "error in photoshop file: wrong signature".
What might have happened and what can I do to solve it and recover my file?

**Comment by photopea** [comment]
Hi, did you create a brand new file, or opened an existing PSD from your computer?

**Comment by izbarboza** [comment]
I created a brand new PSD file using a JPG as a model to copy the size of the image.

**Comment by photopea** [comment]
can you send us your corrupted PSD? Or at least describe the steps, how to create such "corrupted" PSD?

**Comment by photopea** [comment]
Hi, are there any news?

**Comment by photopea** [comment]
I will have to close it because of lack of details :(
