### ISSUE TITLE
Canvas did not update with raster mask

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2010]
1.) New project
2.) Add stroke effect to Background Layer with Size:20px, Position:Inside
3.) Ctrl+A to select all
4.) Click "Add Raster Mask" button in bottom of Layers window
5.) Select Brush tool and paint into mask
6.) Canvas did not update properly as seen on screenshot
![image](https://user-images.githubusercontent.com/6370548/77353623-977bdb80-6d41-11ea-8151-065f5c786665.png)

**Comment by photopea** [comment]
Hi, I fixed it. It seems like this bug was here for a long time and nobody reported it :(
