### ISSUE TITLE
Photopea unable to use move tool

### ISSUE THREAD

**Issue by mommy2mckenzye** [photopea/photopea#2013]
When I try to make an overlay; I am using the boxes to make sections for the various things. Webcam, Chat-box, VM Capture and such. I cannot get the boxes bigger or smaller no matter what I do. I have tried the incognito window; I have cleared the cache and cookie - I have checked for system updates. I still am unable to resize a box - please help.

**Comment by photopea** [comment]
Hi, what do you mean by the box? Do you mean a rectangular selection? You should use a Free Transform tool to transform layers: https://www.photopea.com/learn/free-transform

Or when you use a Move tool, enable "Transform Controls" at the top.
