### ISSUE TITLE
I see that you closed my ticket

### ISSUE THREAD

**Issue by mommy2mckenzye** [photopea/photopea#2014]
I see that you closed my ticket; maybe instead of closing it after you THINK you solved it - when it wasn't even listened too I wouldn't have to open a new one and clutter all this mess. 

SADLY that will not be able to happen since in my ORIGINAL statement I am claiming that I need an overlay for a VM which needs a 1600 x 1200 layout ; and it needs to be able to fit 3/4 of my scree - which is where the broken move tool isn't working. I HAVE been able to use this on the fixed ratio before so the "quick fix" that you gave me for closed ticket #2013 isn't going to help. Can you please tell me what I am doing wrong or at least try to look at thing in my perceptive
 since I was just looking into paying for this service now I am not so sure. 

![Capture](https://user-images.githubusercontent.com/62652099/77543531-d4e18580-6e75-11ea-8289-2402f747afc8.PNG)

**Comment by mommy2mckenzye** [comment]
LOL, sorry that really all came out super rude - I apologize; please don't take it that way. Much love for the service that is why I really want to buy it, but the problem happens often, and after a few days fixes itself.... which is why I was wondering if I was doing something wrong.

**Comment by photopea** [comment]
It is possible to continue the discussion in closed tickets, too.

I am afraid I don't understand your issue. What is "overlay" and "VM"?

Have you tried the Free Transform : Edit - Free Transform? Are you sure it is not what you need?

**Comment by mommy2mckenzye** [comment]
Even with Free; I can't resize the box. 
![Capture](https://user-images.githubusercontent.com/62652099/77555935-d31fbe00-6e85-11ea-869e-96a5ff03cb4b.PNG)

**Comment by photopea** [comment]
To use a Free Transform, press "Edit" at the top. You will see a menu. Then, press "Free Transform" in that menu.

**Comment by MichalSZZ** [comment]
...and if you want to keep ratio 4:3 (or any other from oryginal shape) just hold shift button when resizing by holding the shape corner

...or try to edit->"free transform" and at the bar with W and H input boxem write 75% when you want to have 3/4 of the oryginal size of the layer

"free", "fixed size", fixed ratio" are only for creating shapes - not editing it

**Comment by photopea** [comment]
So did it help?

**Comment by photopea** [comment]
I have to close it because of lack of details.
