### ISSUE TITLE
[Suggestion] Improve snap (+rounded rectangles)

### ISSUE THREAD

**Issue by Dangelman** [photopea/photopea#2016]
I put Photopea as recommendation for my community of vector artists.
However, I noticed that the snap doesn't work for aligning or centring layers (to other layers or the frame), which is a pretty bad downside.

Another note: my community base its designs on rounded rectangles. However, I see that the shape is not available. Would it be possible to add it?

**Comment by photopea** [comment]
Hi Dangelman,

Photopea supports snapping. Enable it in View - Snap. Then, you can specify to snap to specific objects (View - Snap To - ....)

To make rounded rectangles, use a Rectangle tool and set the corner radius bigger than zero (in the top menu).

**Comment by Dangelman** [comment]
Thanks for the reply.
1. Is it possible to change radius after creating the shape?
2. You can't snap to shape and layers, even with all the options selected

**Comment by MichalSZZ** [comment]
1.
Yes. In properties panel
<img width="747" alt="obraz" src="https://user-images.githubusercontent.com/38118273/77771691-4c1a4380-7047-11ea-9b55-1273979deaed.png">
<img width="757" alt="obraz" src="https://user-images.githubusercontent.com/38118273/77771732-5e947d00-7047-11ea-9664-4f3ce16c49f6.png">

**Comment by MichalSZZ** [comment]
>     2. You can't snap to shape and layers, even with all the options selected

Yes. For me it doesn't work too. But I think that worked before (?)

Here is my record from Photoshop, how does it work there

![snapping](https://user-images.githubusercontent.com/38118273/77775723-3b6ccc00-704d-11ea-8bd7-dddc5268057a.gif)

**Comment by photopea** [comment]
Are you sure this is a good idea? Every object has six "snapping lines" - top, middle and bottom horizontal, and left, middle and right vertical. When we have only two objects A B, they can be snapped in 9 ways horizontally (A left and B right, A left and B middle ...) and 9 ways vertically (18 in total). But if you have five layers, each layer can be snapped with four others in 18 ways, 72 ways in total.

When I use photoshop, I feel like I can not move objects freely anymore. They only "jump" between snapping positions.

**Comment by photopea** [comment]
So I imlemented that snapping to layers. It is always disabled, unless you enable it in View - Snap To - Layers.
