### ISSUE TITLE
Text is always a little bit blurry/fuzzy

### ISSUE THREAD

**Issue by DanielLaberge** [photopea/photopea#2017]
Hi,

I love this app and I have a lot of respect for its author and his dedication.

I have only one issue: **any text I use, no matter which font, always appears a little bit blurry**, unlike in Photoshop, or even normal web pages, where the text is very crisp. The smaller the text is, the worst it gets.

This could be because Photopea doesn't use anti-aliasing for its text rendering.

Would you consider implementing it? It would really improve the visual fidelity level of Photopea for UX mock-ups, for instance.

See the following two images for an example using Roboto Regular at 13px, in Photopea, then in JSFiddle. Make sure to view them at their original resolution.

**Photopea**:
![image](https://user-images.githubusercontent.com/3459916/77783282-f33eb100-702e-11ea-818f-013aa4a9afa1.png)

**JSFiddle**: https://jsfiddle.net/cabu0xk9/
![image](https://user-images.githubusercontent.com/3459916/77783720-bcb56600-702f-11ea-98cb-3b7374259310.png)

**Comment by photopea** [comment]
Hi, I zoomed in at your photos and this is what I got (JSFiddle at the top, Photopea below):

![image (1)](https://user-images.githubusercontent.com/15955558/77785529-9ce86700-705c-11ea-98bb-cd40839a6912.png)

I see two differences:
1) JSfiddle makes "sub-pixel antialiasing" - When the text is black, pixels can be non-black
2) JSfiddle puts the baseline on a whole pixel (like 100), while Photopea can have it at any location (e.g. 100.23)

**Comment by photopea** [comment]
You can read more about sub-pixel antialiasing here: https://en.wikipedia.org/wiki/Subpixel_rendering

It is quite common everywhere today, but in Photopea, we use only the main color of a text.

**Comment by DanielLaberge** [comment]
Here's a real example from a UX mockup I'm working on. I first tried creating buttons in Photopea, but quickly gave up because the text doesn't look clear. So I ended up creating buttons in a webpage , then I screenshot them and paste as image in Photopea.

As can clearly be seen here, for the same text settings, the Photopea rendered text is less clear and almost looks blurry.

![image](https://user-images.githubusercontent.com/3459916/77788732-26d20900-7038-11ea-9361-a8723c97dd4f.png)

By the way, this is not a Photopea vs JSFiddle issue. All moderns browsers I know of render text clearly. Photoshop as well when the anti-alias option is enabled.

Would you consider updating your text-rendering to match what modern browsers do?

Thank you again for all your work.

**Comment by photopea** [comment]
The text has different sizes in your last screenshot. As i said, I think the only difference is in sub-pixel antialiasing. Otherwise, they look equally clear to me.

**Comment by photopea** [comment]
I dont know if it is a good idea to put sub-pixel antialiasing into a photo editor. People can be shocked, that when they make a black text on a white background, they get red and blue pixels.

Have you tried any actual image editors? Do they produce text, that you would call "sharp"?

**Comment by DanielLaberge** [comment]
I tried selecting the same font-size (13px) in all cases, but due to the rendering engine being different, the actual final size does indeed vary.

I do not have Photoshop on hand right now, but here's Paint.net, a pretty basic editor:

![image](https://user-images.githubusercontent.com/3459916/77799818-f4caa200-704b-11ea-8122-2b9eeef29784.png)

I do find it helpful to have a say in how the text is rendered.

Thank you for the consideration.

**Comment by photopea** [comment]
I think Paint.NET looks the same as Photopea. But it is also rounding the baseline to the whole pixel.

**Comment by photopea** [comment]
I implemented the rounding of the baseline. The text should look sharper now, just like in Paint.NET.
