### ISSUE TITLE
Corner tool - ability to round any corner in a shape

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2018]
Hi,
we talked about that few months ago by email :)

I come back with that subject again after that #2016 issue.

I like to make simple vector artworks in Photoshop. Photopea have all important things from PS. But when I must make round corner in shape that isn't rectangle - Photoshop hasn't  ability to do that. Then I must open Illustrator and have to round the corners there, copy shape and paste it into the Photoshop. I hate to do that! And I think that Adobe (for some reasons) doesn't want to give this functionality to their users.

I know that Photopea is raster program. But that will be great feature for many designers.
Adobe Illustrator, Affinity Designer, Inkscape have that function with their own GUI for it. 
I like how Affinity Designer showing that (with circles showing radius). In illustrator it works great too. I didn't use Inkscape for many years but I saw tool for that in this software too.

https://www.youtube.com/watch?v=xTHdK5kG99w here all of the features are showed (Affinity). 

I looked before how that can be done (some links with math solutions etc.). If that can help you I will be very happy. 

https://stackoverflow.com/questions/24771828/algorithm-for-creating-rounded-corners-in-a-polygon

https://www.stkent.com/2018/04/06/really-rounded-polygons.html

https://stackoverflow.com/questions/10177985/svg-rounded-corner

https://helpx.adobe.com/lu_en/illustrator/using/reshape-with-live-corners.html

https://wiki.inkscape.org/wiki/index.php/SpecFilletChamfer

https://medium.com/@nikolskayaolia/an-easy-way-to-implement-smooth-shapes-such-as-superellipse-and-squircle-into-a-user-interface-a5ba4e1139ed

It will be great to change radius of all corners at the same time and ability to change one or few selected only.
I didn't need options for corner types (Straight, Concave, Cutout).

If you make that tool I promise I will make 10 tutorials on YT how to draw vectors easly in Photopea :) like this ones (that was fast test - 3-5 minutes) 
https://www.photopea.com/#iybjXdN_4 puppet warp test
https://www.photopea.com/#isr53PF4Q filters test (on aurora borealis)

**Comment by photopea** [comment]
Hi, it is already implemented in Photopea. When we load Sketch files, they can contain a polygon + a radius of corners (or a specific radius for each corner). We need to convert it to a standard shape in PSD.

So we just need to expose it in the UI. You can play with various radiuses when you apply it for the first time, but it will not be possible to change radiuses later, is it ok for you? Also, radiuses might not remain circular, if you apply a free transform to the shape. The problem is, that a PSD does not support storing radiuses separately, so all we can do is to turn them into a standard vector path.

**Comment by MichalSZZ** [comment]
1. If you have some time, you can first add UI for Live Shapes corner radius. That will be very good for users (properties tool is not so "user friendly" for rounding the corners).
2. Later you can add tool for rounding all corners in any shape/path (not only for polygonal).
3. I belive that later you will discover a magic trick to keep data od radius in file for possibility to change radiuses all the time  ;) 

But now I will be very happy having only point nr1 :)

Here is my suggestion how to show UI for live shapes (and later fo any shape). Dashed circles isn't required :)

![corner-raiuds-tool-UI](https://user-images.githubusercontent.com/38118273/77822390-7543de00-70f2-11ea-8e7c-5122b3f00a5c.png)

**Comment by photopea** [comment]
It is not clear, if you want it only for rectangles, or for any polygon, or for any path (with smooth corners).

**Comment by MichalSZZ** [comment]
> It is not clear, if you want it only for rectangles, or for any polygon, or for any path (with smooth corners).

For any path - that would be fantastic.

But if it will be hard to implement fast - rectangles/polygon for the start will great too.

**Comment by photopea** [comment]
Hi, I implemented the Corner feature. Switch to Direct Select and select some corners. Then, click the Corner Radius button at the top panel.

**Comment by MichalSZZ** [comment]
Big, big thanks!
Photopea has got yet another functionality that Photoshop hasn't :)

There is no GUI for corners yet but it is milestone for me :) I Will buy another 3 months when my premium account will be end.

**Comment by photopea** [comment]
@MichalSZZ Thanks! Actually, I would like to make the corner radius modifiable many times, but I am limited by what PSD format can store. I can add new features to PSD files, but they will not work in Photoshop.

**Comment by MichalSZZ** [comment]
@photopea That shouldn't be your problem :) 
I told you that some time ago via email :)
Your program is more dynamic in development. Adobe should watch what are you adding and do same thing in Photoshop :)

I think that most peaople open PSD files in Photopea that was made in Photoshop. In reverse direction I think that doesn't work. Nobody (exept some freaks like me) use Photopea to make PSD files when have Adobe CC licence.
If your new data stored in PSD file don't kill Photoshop (file will be opened and extra data will be ignored), you should think about that.
