### ISSUE TITLE
Some PSDs from a Sketch file can't be opened by PS on MacOS

### ISSUE THREAD

**Issue by Bonero** [photopea/photopea#202]
I have converted a sketch file to a PSD but I can't open up the PSD-file in Photoshop!? Photoshop is working but nothing happens. Only the colorful nice little beach ball :-) Why?

**Comment by photopea** [comment]
Hi Bonero, can you share your Sketch file with us? Or send it to support@photopea.com ? What version of Photoshop do you use?

**Comment by photopea** [comment]
I believe I have fixed it. Can you try it again?

**Comment by photopea** [comment]
- it happens only on MacOS (never happened on Windows)
- when there are no text layers, everything works fine

**Comment by photopea** [comment]
I believe I have fixed it for good now.
