### ISSUE TITLE
Magic Cut on icon

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2020]
I wanted to use Magic Cut function on 16x16 pixels icon and it did not work with "Uncaught e" error.
Also I noticed everytime I open photopea there is some "Uncaught ReferenceError: addSmartReactAdUnits is not defined" error now. See screenshot
![image](https://user-images.githubusercontent.com/6370548/77903657-807a4380-7283-11ea-8a09-514c76e47a64.png)

**Comment by photopea** [comment]
I fixed it, thanks for reporting! :)
