### ISSUE TITLE
where is the source code?

### ISSUE THREAD

**Issue by mobop** [photopea/photopea#2021]

**Comment by photopea** [comment]
Hi, what source code?

**Comment by mobop** [comment]
your web app's

**Comment by photopea** [comment]
It is in my computer. Photopea is not open-source.

**Comment by mobop** [comment]
@photopea , why you have this github account?

**Comment by photopea** [comment]
Some parts of Photopea are open-source. They are in other repositories: https://github.com/photopea?tab=repositories

This repository is only for reporting bugs in www.Photopea.com , I recommend to read our README: https://github.com/photopea/photopea

**Comment by quantuminformation** [comment]
You have the right to make a living!
