### ISSUE TITLE
text not selectable when exporting as a PDF

### ISSUE THREAD

**Issue by jes76155** [photopea/photopea#2022]
When I export my file as a PDF the text layers are not selectable (i.e you can't ctrl + f to find a word).

**Comment by photopea** [comment]
We have a very limited support for exporting text into a PDF.
Was the text selectable in a PSD? Or is it e.g. a photo of a newspaper?

**Comment by jes76155** [comment]
Yes, it is selectable in a PSD.

**Comment by photopea** [comment]
To keep the text selectable, do not rasterize or vectorize it (these are the options in the PDF export). The text will be written with a default font and supports only english characters, but it will be selectable and "findable".

**Comment by jes76155** [comment]
I didn't select either option and I'm still experiencing the same issue.

**Comment by photopea** [comment]
That is very strange. Could you send me a screenshot of your Save For Web window, while you export the PDF? Could you also attach a resulting PDF file here?

**Comment by jes76155** [comment]
[Whitepaper (8).pdf](https://github.com/photopea/photopea/files/4421981/Whitepaper.8.pdf)
<img width="556" alt="WhitepaperSaveSS" src="https://user-images.githubusercontent.com/63060032/78267801-5ddf6900-74d5-11ea-80a4-52c3e9230df4.PNG">

**Comment by photopea** [comment]
Thank you very much! It really looks like a bug. Could you send me the PSD version of your document, so that I try it myself?

**Comment by jes76155** [comment]
https://www.photopea.com/#iKccjYEhe

**Comment by photopea** [comment]
Hi, there was a bug, I fixed it. Please, try it again.

To make sure your PDF looks exactly as the PSD, use "rasterize all". It will simply export a PNG image wrapped in a PSD (with no selectable text).

Otherwise, the text may look different and some layer styles are omitted (like bevel and emboss).

**Comment by jes76155** [comment]
Thank you! It seems to be working now.

**Comment by photopea** [comment]
Great! Thanks for reporting it.
