### ISSUE TITLE
Unsubscribe ??

### ISSUE THREAD

**Issue by DonnaWxnter** [photopea/photopea#2023]
Hi everyone how do I u subscribe from getting so many notifications about the issues here? I tried it once, but it didn’t work. Can someone help or guide me please?

**Comment by photopea** [comment]
I thought only I receive emails about new issues  :/

When you go to https://github.com/photopea/photopea/, is there an "Unwatch" button at the top? Can you click it?

**Comment by DonnaWxnter** [comment]
Thank you!!

**Comment by photopea** [comment]
I think it is solved, so I will close it :)
