### ISSUE TITLE
Able to brush outside of the selecion

### ISSUE THREAD

**Issue by ColdTuna** [photopea/photopea#2025]
Hi, this might be a bug, I don't know... I was painting a selection red and the red seems to be leaking outside of the selection. I'm posting a photo of it.

Thanks for this great tool!

![Screenshot](https://user-images.githubusercontent.com/42479948/78359431-74e09280-758b-11ea-91ce-73c9231e8e71.jpg)

**Comment by photopea** [comment]
Hi, the selection is not like a selected / unselected pixels, but a pixel can have various degrees of selection. E.g. you can apply Feather on the selection, to blur it. You can read more here: https://www.photopea.com/learn/selections

The contour, that you see, is drawn between pixels with a selection >50% and pixels with a selection <50%. The pixels outside the contour probably have the selection around 30%. Use the Rectangular selection with a Subtract mode to remove these pixels form a selection (set their selection value to 0  %).
