### ISSUE TITLE
Get Photopea listed in cloud apps

### ISSUE THREAD

**Issue by RasheedAZ** [photopea/photopea#2026]
Hi. In order to increase discoverability, you should get Photopea listed among web apps and cloud apps:

[(https://www.getapp.com)](url)

[(https://www.gartner.com/en/digital-markets/basic-listing)](url)

Also, you can try to talk to Elementary OS's AppCenter for Everyone team and Flathub to have web apps like this that run on multiple platforms included. This way Linux users have a greater chance of knowing about Photopea and other useful web based software instead of fumbling about with Wine, etc.

**Comment by photopea** [comment]
I looked at https://www.getapp.com/ . I could not find popular webapps such as Figma or Gravit. I also could not find regular apps like VLC player. I think it is just a website for bad apps, where authors have to pay to make their app published, as they can not get users in any other way.

I do not know much about Linux. Could you maybe ask them to add Photopea? I would be very grateful.

**Comment by RasheedAZ** [comment]
Well I think if they list for free it's still better than not being listed. Not sure, but the impression I got was that it's the same company behind Capterra. 

Thanks for considering anyway.

For Linux, I just asked Flathub and Elementary's App Center to open up to web based apps and games... let's see of they accept. 

To get included in the app store of Ubuntu, one of the most widespread Linux based OSs, please submit Photopea here:
[https://snapcraft.io/first-snap]
Sorry I don't know the first thing about programming or what Photopea is written in or I'd do that for you.

However, it's annoying that so many users are fumbling about trying to get mediocre apps to run when much better cross-platform web apps like Photopea exist.

**Comment by photopea** [comment]
I think it is better if someone else tries to promote an app. When the author does that, it always feels like self-promotion. I tried to create a page about Photopea on Wikipedia, and it was deleted immediately.

BTW. Snapcraft does not have a category for Photopea :(

**Comment by RasheedAZ** [comment]
OK no worries but if you need me to do this anywhere, just say. You'll just need to provide those details that I don't know.

I submitted Photopea to Softpedia just now. They'll contact you on the support email address if any questions. Hope that's ok.

**Comment by RasheedAZ** [comment]
Hey bro the Flatpack guys are welcoming of Photopea being included. They said:

"If somebody wanted to make it into a flatpak the easiest path is to simply make a thin wrapper with either WebKitGTK or QtWebEngine that simply opens the website."

**Comment by photopea** [comment]
I have no experience with WebKitGTK or QtWebEngine. If Flatpak guys really want to have a catalogue of good-quality software, they should make the process simpler.
