### ISSUE TITLE
Feature Request: Resize Layer

### ISSUE THREAD

**Issue by clutchwave** [photopea/photopea#2027]
Hi, I often use GIMP and like the way I can resize a layer and keep the scale. Doesn't seem to be a way to do this from the Layer menu in Photopea. Would be great to have it added!

That's for such incredible software!

**Comment by photopea** [comment]
Hi, what exactly do you mean by that? Could you show us an example?

**Comment by clutchwave** [comment]
I mean to say *scale layer*. Is this possible in Photopea?

![image](https://user-images.githubusercontent.com/2278974/78458343-2e1b9700-7676-11ea-9780-67d46cb6fd43.png)

![image](https://user-images.githubusercontent.com/2278974/78458351-3e337680-7676-11ea-995d-5f8d8492851f.png)

Thanks!

**Comment by photopea** [comment]
Yes, you can use a Free Transform: https://www.photopea.com/learn/free-transform . You can enter a new size in the top panel.

**Comment by clutchwave** [comment]
Thanks!
