### ISSUE TITLE
Fonts aren't showing when uploaded

### ISSUE THREAD

**Issue by kohenro** [photopea/photopea#2029]
I've been trying to add a font to photopea. It says it has successfully loaded but when I go to chose the font it isn't there. It is showing it is saved to the local storage.
![fontissue](https://user-images.githubusercontent.com/63278961/78633777-c075a200-78e5-11ea-8de1-4bf2f3a05512.PNG)

**Comment by photopea** [comment]
Hi, so is it one specific font, that was not loaded, or all your loaded fonts don't show up?

If it is a specific font, can you send it to us to support@photopea.com ?

**Comment by avagp** [comment]
i can add something up? 

Montserrat font is already in the fonts library.

Maybe it is related to that.

**Comment by photopea** [comment]
@avagp that is true, but other fonts should load correctly. We need the author to give us more details.
