### ISSUE TITLE
Photopea Playground Infinite Loop

### ISSUE THREAD

**Issue by AxDSan** [photopea/photopea#2032]
function `onMSG()` @ https://www.photopea.com/api/playground causes an Infinite Loop on the page.

**Comment by photopea** [comment]
Hi, where exactly is an infinite loop?

You don't have to use any code from our Playground.

**Comment by AxDSan** [comment]
> Hi, where exactly is an infinite loop?
> 
> You don't have to use any code from our Playground.

This better showcases it...
https://streamable.com/35nyvy

However I have noticed that, it only happens in Edge Browser, I don't know if it's caused by my extensions, but I have almost all of the same extensions across all my multiple browsers and it only acts up in Edge (Beta).

I will try using Edge in Safe Mode without any extensions loaded and will report back.

**Comment by AxDSan** [comment]
I apologize, I have launched the browser with the `--disable-extensions` commandline flag, and the issue does not appears. So it's indeed one of my extensions that is breaking your website.

**Comment by photopea** [comment]
Your extension acts almost like a virus :D

**Comment by AxDSan** [comment]
I know! and that's quite scary! 🤣

------ Original Message ------
