### ISSUE TITLE
Using CSS width trick to hide ads, permissible?

### ISSUE THREAD

**Issue by abrari** [photopea/photopea#2033]
Hi, great product.

I saw a site using Photopea API that is hiding the right side ads with following CSS:

```
#container iframe {
    width: calc(100vw + 300px);
    ...
}
```

The ads is effectively hidden. Is this permissible?

**Comment by photopea** [comment]
We don't want people to do this, but many of them do this anyway.

Photopea in iframe shows anad only in 50 % of cases. So they will hide the ad sometimes, but other times, the Photopea UI will be "cut off". But they probably did not notice it :(

**Comment by photopea** [comment]
I am closing it.
