### ISSUE TITLE
eraser tool appling red color as if it's a paint brush - Firefox/Waterfox - Linux

### ISSUE THREAD

**Issue by Niroc** [photopea/photopea#2035]
Hi, 
The eraser tool seems to be acting like the paint brush tool, I made a very short video clip (attached) showing the behaviour but, I had to compress the vid into a .zip file as Github doesn't support mkv files
[2020-04-12 20-27-57.zip](https://github.com/photopea/photopea/files/4466920/2020-04-12.20-27-57.zip)

please can you take a look?

**Comment by photopea** [comment]
Hi Niroc, you accidentally enabled the Quick Mask mode. It is described at the end of this article: https://www.photopea.com/learn/selections
