### ISSUE TITLE
App Interface Layout is broken on Firefox 76

### ISSUE THREAD

**Issue by ktryndchrs** [photopea/photopea#2037]
The screenshot to show what I mean

<img width="1710" alt="image" src="https://user-images.githubusercontent.com/416462/79149322-349bc400-7d84-11ea-988f-4d5ddc68bed5.png">

**Comment by photopea** [comment]
Hi, what exactly is broken? I can not see it.

There should be ads on the right side, but you are probably blocking them. Please, watch our ads. Otherwise, we would go bankrupt :(

**Comment by photopea** [comment]
I have to close it because of lack of details.
