### ISSUE TITLE
Ads??

### ISSUE THREAD

**Issue by dfsmith001** [photopea/photopea#2039]
All blockers turned of message keeps coming up annoying as all heck. i'm just trying photopea to see if its worth it. I'm an amateur computer guy

**Comment by photopea** [comment]
Hi, so you are not aware of any ad-blockers, you reloaded www.Photopea.com and you still see the message?

What number do you see at the end of the message? There should be e.g. "1" or "2", etc. Are the ads displayed normally? What kind of ads do you see?

**Comment by dfsmith001** [comment]
I'm not very tech savy ads are displayed on the right side but the message
keeps popping up that my blocker is on and its not.

--
Denny Smith
Service Dept.
Industrial Truck Repair, Inc.
637 Perkins Dr.
Mukwonago, WI 53149

O: (262) 363-2919
C: (414) 333-3164
F: (262) 363-2939
E: denny@industrialtruckrepair.com
http://www.industrialtruckrepair.com


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by photopea** [comment]
Can you tell me, what number do you see at the end of that message? There has to be a number like 1, 2, etc.

**Comment by photopea** [comment]
Can you send me a screenshot of Photopea, as it is displayed in your computer?

**Comment by tkzv** [comment]
I experienced a similar problem about a month ago. Several times. The ad banner was clearly visible.  The message disappeared after I deleted cache and cookies and restarted the browser. Can't reproduce it this week. I'll copy the message, if I see it again.

**Comment by photopea** [comment]
We enable this adblock-check only from time to time.

@tkzv What banner did you see? Photopea shows a banner for "Photopea Premium", when adblock is detected. Otherwise, you should see an ad for other things.

**Comment by alekexe** [comment]
Maybe @tkzv has some ad malware?

**Comment by photopea** [comment]
Photopea checks for AdBlock just once when it starts. Disabling AdBlock while using Photopea will not help. You should disable ad blocking before even opening Photopea.
