### ISSUE TITLE
New PP logo

### ISSUE THREAD

**Issue by NatashaDK** [photopea/photopea#204]
Hi guys...

I don't have a twitter/facebook account so I'm posting my idea of a new PP logo here on Github.
(See attach. png).

Love from NatashaDK
![pp logo](https://user-images.githubusercontent.com/27579710/27155302-bc494658-5158-11e7-9e5f-933bca8e3797.png)

**Comment by photopea** [comment]
Hi Natasha, thanks for your design :)  But it reminds me Adobe products a lot (two letters in a colorful square).

**Comment by photopea** [comment]
I am sorry, this place is visited just by me and sometimes by some user having a problem. But I shared your logo on Facebook :)

**Comment by NatashaDK** [comment]
That's sweet... thanx :-)
