### ISSUE TITLE
Help! Whenevery I save as PNG it saves it as a txt file!! Please tell me how to fix

### ISSUE THREAD

**Issue by chrisscnm** [photopea/photopea#2040]

**Comment by photopea** [comment]
Hi, I think it is because of your browser extensions. Try to find the one which does that and disable it (or ask the authors of an extension to fix it).

You can also use Photopea in Incognito mode, where browser extensions are disabled.

**Comment by chrisscnm** [comment]
> Hi, I think it is because of your browser extensions. Try to find the one which does that and disable it (or ask the authors of an extension to fix it).
> 
> You can also use Photopea in Incognito mode, where browser extensions are disabled.

**Comment by photopea** [comment]
By the way, could you tell us, what extension it was?

I am afraid, that there are hundreds of people with this extension, who are trying to use Photopea and give it up because of TXT files. If I know what extension it is, I could report it to the authors of that extension, so that they fix it.

**Comment by aidinjk** [comment]
Firefox can allow private extensions 😏
