### ISSUE TITLE
Chromebook and Photopea

### ISSUE THREAD

**Issue by jco561** [photopea/photopea#2042]
Any project I am on for more than five minutes it resets my screen and deletes my progress. I have saved it but it shows a blank screen and it will not let me edit at certain times.

**Comment by photopea** [comment]
Hi, can you try Photopea in Incognito mode? Maybe your browser extensions are doing it.

**Comment by jco561** [comment]
Ok thank you. I will try that.

**Comment by photopea** [comment]
I have to close it because of lack of details.
