### ISSUE TITLE
Type Tool's Not Working

### ISSUE THREAD

**Issue by bernardoklock** [photopea/photopea#2046]
Third day in a roll I have to reset browser (updated Chrome, updated Windows) due to this error.

Create New Document > Select Type Tool > It writes, creates a layer, but text's invisible.

**Comment by bernardoklock** [comment]
Annoying.

**Comment by photopea** [comment]
Hi, it is probably because of your browser extensions, which prevent Photopea from working properly. Browser extensions can do anything they want with websites  you visit.

Try Photopea in Incognito mode to see, if it still happens.

**Comment by photopea** [comment]
I have to close it because of lack of details.
