### ISSUE TITLE
This Layer Style tool option is not working.

### ISSUE THREAD

**Issue by bboyguil** [photopea/photopea#2047]
I've been trying to use this feature for a few days, but it's not working.

![screenshot_30](https://user-images.githubusercontent.com/3357743/79591270-a2126200-80ae-11ea-90f8-10663fc57925.jpg)

**Comment by photopea** [comment]
Hi, this menu shows a gallery of styles. You should press Define New, to add a current style to the gallery, or open an ASL file from your computer.
