### ISSUE TITLE
Psd file won’t open

### ISSUE THREAD

**Issue by sahilfarouq** [photopea/photopea#2049]
Hello, I can’t seem to open my psd file in Photopea, can I get some assistance please

**Comment by photopea** [comment]
@sahilfarouq Can you try steps mentioned here: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/ ?

**Comment by photopea** [comment]
I have to close it because of the lack of details. There are hundreds of thousands of people opening their PSDs in Photopea every day, so we need to know a little more.

**Comment by sahilfarouq** [comment]
Hey! The file was a fifa 20 card creator file from google drive. All other files are fine

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by photopea** [comment]
Can you send me that PSD file to support@photopea.com ?
