### ISSUE TITLE
PSD Projects Won't Load

### ISSUE THREAD

**Issue by DeckerGaming** [photopea/photopea#205]
So I download PSD files and try to open them in Photopea, but all of a sudden now, it will not show up. I cannot see it when I open it here.

**Comment by photopea** [comment]
Hi, can you send us your file to support@photopea.com ?

**Comment by DeckerGaming** [comment]
But it is anything, nothing will show up at all!

**Comment by DeckerGaming** [comment]
Oh, now it is working after a while.

**Comment by photopea** [comment]
There was an issue, which prevented  opening some PSDs with layer comps. But it was fixed several hours ago. Maybe that was your case and you didn't reload Photopea for a long time.  Let us know if you find any other problems.
