### ISSUE TITLE
Time Lag

### ISSUE THREAD

**Issue by kween30** [photopea/photopea#2050]
The time lag for Photopea is unbelieveable.  I am unable to complete ANY project due to the awful lag.  It took literally 10 MINUTES to change my background from white to black, due to the time lag.  It really a shame that people are mislead to believe that this is an "efficient" free software used for designing, and you cant even get to the design portion!!  Once I finally got the background color changes, the whole project reverted BACK to the original home page.  THEN in order to report a bug you must CREATE an account on HERE!!! Total waste of time!! You frustrate your customers to the point where they will pay ANY amount of money to NOT use your software.  I am HIGHLY dissapointed.  Definitely misleading advertisements!!!!!

**Comment by photopea** [comment]
Hi, there are hundreds of thousands of people using Photopea every day. Nobody reported such problem in the past.

Is your web browser more than ten years old? Could you update it? If it still does not work, could you please describe the steps to reproduce the lag? I just tired to change the color in several ways, and it was changed instantly every time.

**Comment by kween30** [comment]
That's interesting because even a YouTube tutorial on your product shows
that there are terrible time lags. No need to investigate further, I
already purchased my Adobe Software and it works like a dream.  You can
close the ticket

**Comment by photopea** [comment]
I am very sorry for your trouble. There are thousands of tutorials about Photopea and I did not see the lag in any of them. But I have not seen them all.

We solve problems right after users report them, and we solved thousands of problems in the past. Saying "you have a problem and I will not tell you what it is" does not really help anybody :(

**Comment by photopea** [comment]
@kween30 Unless you can provide a description of how to make the lag happen, or share a video with me, which demonstrates the lag, the only explanation I see is, that you are just making it all up.
