### ISSUE TITLE
Downloadable version

### ISSUE THREAD

**Issue by aidan012** [photopea/photopea#2051]
You should make a downloadable version so that people without powerful computers can run it outside there browser.

**Comment by photopea** [comment]
Hi, we do not plan a downloadable versio :(

Have you tried pressing More - Install Photopea?

**Comment by aidan012** [comment]
yes, its still lagging

**Comment by photopea** [comment]
What exactly is lagging? Do you mean opening photopea or some specific operation, which you do in Photopea?

**Comment by photopea** [comment]
I will close it now, as I doubt this issue has a chance to move any further.
