### ISSUE TITLE
Paste not working

### ISSUE THREAD

**Issue by UnderMineBlox** [photopea/photopea#2052]
Every time i try to do [Ctrl] + V it wont work.

**Comment by photopea** [comment]
Hi, I think we sloved this problem here: https://github.com/photopea/photopea/issues/1912

**Comment by UnderMineBlox** [comment]
I have it on, but it still is not working.

**Comment by photopea** [comment]
What do you have on? What browser are you using?

**Comment by UnderMineBlox** [comment]
I am using Google Chrome, are you asking what extensions I have on?

**Comment by photopea** [comment]
Yes, can you try Photopea in Incognito mode?

**Comment by UnderMineBlox** [comment]
I have just tried using it in incognito, same issue

**Comment by photopea** [comment]
Are you sure you gave Photopea permissions for the Clipboard? Can you show me how the permissions look like in your case? Also, is your Chrome updated?

**Comment by UnderMineBlox** [comment]
![image](https://user-images.githubusercontent.com/62233505/79691331-56abaf80-8278-11ea-9938-cd167ab5ee4e.png)
I will check if chrome is up to date

**Comment by UnderMineBlox** [comment]
Chrome seems to be up to date

**Comment by photopea** [comment]
Are you sure you have an image in your clipboard? Can you select, copy and paste within Photopea?

**Comment by UnderMineBlox** [comment]
Ive tried in multiple ways. I used Ctrl + v, photopea's paste button, chromes paste button, an onscreen keyboard, none of it is working. Each time I made sure my clipboard had something and tested on other sites

**Comment by photopea** [comment]
I see you are using FreePhotoTool.com . Use Photopea directly at www.Photopea.com , it should work there.

**Comment by UnderMineBlox** [comment]
Thank you! It is working now :)

**Comment by UnderMineBlox** [comment]
Is this your main site now?

**Comment by photopea** [comment]
Photopea.com has always been our main site since 2013. FreePhotoTool is a guy, who puts Photopea on his website (anybody can put Photopea on their website).

**Comment by UnderMineBlox** [comment]
Oh, I see. Thank you again!
