### ISSUE TITLE
Fuck your ads

### ISSUE THREAD

**Issue by ShyteSite** [photopea/photopea#2053]
Photopea was like"UwU pls diable your adblock we wont interrrupt you with annoying ads *snuffles your cock*", so I did - since I really liked the site so far. 20 minutes in after photoshopping an image I was redirected to a phishing site and ALL my progress was gone. Sincerely, fuck you. I'm turning my adblocker on and will NEVER turn it off again...

**Comment by photopea** [comment]
We do not respond to reports containing vulgar words. Also, we think it is not fair to allow people to hide ads, while others watch them. So I enabled a message, which asks you to stop blocking ads.

**Comment by ShyteSite** [comment]
That's it... I'm not going to use your service at all then. How can you
support ads promoting scams and downright harmful content? I never had any
issues with your service before, up until now that is. Also, it is for the
record illegal to directly redirect from your page to fake mirror sites
(phishing sites)

Den sön 19 apr. 2020 kl 18:52 skrev Photopea <notifications@github.com>:

**Comment by photopea** [comment]
Our ads are only on the side of screen, they never cover the editor and never redirect anywhere. I think it is some virus in your computer. Browser extensions can also redirect any website at any moment. Use Photopea in a regular browser without any extensions, and let us know if it still happens.
