### ISSUE TITLE
Ads are still running for premium user (Purchased an account recently)

### ISSUE THREAD

**Issue by TaWumpas** [photopea/photopea#2054]
Hello,

I started my report but see that there may be a solution already found. I want to report the issue still so you were aware of it but I am trying the solutions others have been recommended. 1. Clear Photopea Cookies (Completed). 
I saw this forum post and my issue matches their issue. So I may have the same problem. 
 https://github.com/photopea/photopea/issues/428

**MY ISSUE:**
I am a premium member brand new to Photopea. Despite my purchase, I still see ads despite my purchase. Note, I didn't see ads after my initial purchase, but today 4/19/2020 they returned. I don't think it's been a month since my purchase and can't seem to find a "# of days until premium ends" but perhaps that does exist? 

(Slight rant, but information may assist) Until I hear back I am going to re-enabled my AdBlock, which had been disabled since before I purchased a Premium account. This prompted the 'please disable adblockers or purchase premium' message. I've disabled my AdBlock and check if my premium account is logged in and it is.

**Comment by photopea** [comment]
Hi, when you have Premium, you should see a green Account button. Can you see it?

If you do not have Premium, but you think you should have, tell us, under which email you are logged in, and we will check your orders.

If you buy premium when logged in under one email address, and then log in with a completely different email address, there is no way for us to tell, that it is the same person. That is why we can not share a single-user Premium between multiple email adrresses.

**Comment by TaWumpas** [comment]
The button is Yellow. Is this an indication that my accounts premium as timed out? I only use this email. Should I simply state it here or is there a private route to list it?

**Comment by photopea** [comment]
Could you tell me your email address, so that I can look into it? You can say it here or send it to support@photopea.com .

**Comment by photopea** [comment]
Are there any news? If you still have problems, please, let us know. I will close the issue now.
