### ISSUE TITLE
Ad redirecting me automatically!!!

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2055]
Whenever this ad appears (The japanesse skincare icon Sephora) it tries to redirect me from photopea automatically. Is this virus or what? Antivirus claims to be some phising site see screenshots

![screen3](https://user-images.githubusercontent.com/6370548/79698619-67fdb780-828a-11ea-9210-e9256e2b746d.png)
![screen4](https://user-images.githubusercontent.com/6370548/79698618-67652100-828a-11ea-8eaa-7de954fccc85.png)
![screen5](https://user-images.githubusercontent.com/6370548/79698616-659b5d80-828a-11ea-8645-e2f528156ce9.png)

**Comment by photopea** [comment]
Wow, that is really awful. I guess the managers responsible for ads did not notice it.

I reported it and I hope they will fix it soon. Please, let me know if it still happens in an hour or two.

**Comment by hxim** [comment]
It looks it does not happen now and seems to be fixed.
