### ISSUE TITLE
text is not showing up for me no matter what I do

### ISSUE THREAD

**Issue by mikejaret** [photopea/photopea#2056]
I try laying text over a picture i upload and I cant see it, I try laying it on a new image i create i cant see it.  I have turned off the opacity on that layer and it is still not doing anything....

thanks

**Comment by photopea** [comment]
Hi, the problem is probably in your browser extensions. Try to disable them and let me know if it works.

**Comment by mikejaret** [comment]
it did, but i have had the same extensions on for years....

**Comment by photopea** [comment]
Can you try Photopea in Incognito mode, if it works? We have to figure out, if an extenxion causes a problem, or not. The fact that you use them for years does not prove anything :D

**Comment by photopea** [comment]
I guess it has been fixed.
