### ISSUE TITLE
Problem with brush settings

### ISSUE THREAD

**Issue by Rosejustrose** [photopea/photopea#2057]
Hello, I was on photopea today and have encountered a problem with the brush settings. It just wont load or let me change the settings please get back to me about this thank you 

https://i.postimg.cc/MTbfyJWG/Annotation-2020-04-20-012155.png
https://i.postimg.cc/G21s8mnN/Annotation-2020-04-20-012246.png
check these out to see my problem

**Comment by photopea** [comment]
Hi, can you reload Photopea with F5? Is it still happening?

**Comment by Alexanderaaaa** [comment]
> Hello, I was on photopea today and have encountered a problem with the brush settings. It just wont load or let me change the settings please get back to me about this thank you
> https://i.postimg.cc/MTbfyJWG/Annotation-2020-04-20-012155.png
> https://i.postimg.cc/G21s8mnN/Annotation-2020-04-20-012246.png
> check these out to see my problem

i got the same bug

**Comment by photopea** [comment]
I opened Photopea and I see brushes in the Brushes panel. Can you update Photopea with F5 and tell me, if it still happens?

**Comment by Rosejustrose** [comment]
It still doesn't work

**Comment by photopea** [comment]
Can you reload Photopea with Shift+F5? Also, do you have any ABR files in Local Storage (Edit - Local Storage)?

**Comment by Rosejustrose** [comment]
i think i do yes, however my computer isn't letting me reload with shift+f5

**Comment by photopea** [comment]
Can you delete ABR files from a local storage and reload Photopea again? You should click in the URL bar when reloading with Shift+F5.

**Comment by photopea** [comment]
I think it is related to the ABR file in your Local Storage. Can you send me that ABR file to support@photopea.com , so that I can fix it?

**Comment by Rosejustrose** [comment]
I looked at my local storage and there was actually nothing in there :( so I have no idea what else it could be

**Comment by Rosejustrose** [comment]
I also put something in there deleted everything out & reloaded with f5 and still nothing

**Comment by photopea** [comment]
That is very strange. Could you switch to a Gradient tool and check, if Gradients are loaded properly? There should be 16 gradients.

Also, try to open Photopea in Incognito mode, in case your browser extensions are blocking Photopea from loading a ZIP file.

**Comment by Rosejustrose** [comment]
Where would i find the different gradients>

**Comment by Rosejustrose** [comment]
?

**Comment by Rosejustrose** [comment]
nvm all 16 are there

**Comment by Rosejustrose** [comment]
also on my computer it wouldn't load photopea on a private browser however all 16 gradients were there

**Comment by photopea** [comment]
Could you try one more test? When you open Photopea and open the Brush panel, and the brushes are not there, can you right-click the panel, choose "Inspect Element", switch to "Console" at the top and do a printscreen of what you see in that console.

**Comment by Rosejustrose** [comment]
here is everything I saw
https://i.postimg.cc/5N7rywC1/Annotation-2020-04-22-101216.png

**Comment by photopea** [comment]
There is "Console" at the top. Can you click it and share a screenshot of that? https://i.imgur.com/gm34kMf.png

**Comment by Rosejustrose** [comment]
https://i.postimg.cc/ydDgt7Y4/Annotation-2020-04-22-101216.png
https://i.postimg.cc/3xZvDLb6/Annotation-2020-04-22-1012166.png

**Comment by photopea** [comment]
Oh, I see it now. It means that your web browser is a bit too old. Could you update it?

**Comment by Rosejustrose** [comment]
If i can figure out how

**Comment by photopea** [comment]
So I think all these problems happen because Photopea is using a command, which is not supported in web browsers older than two years.

Please, update your web browsers.

**Comment by Rosejustrose** [comment]
Hey so i have not had my computer for a few days and have not checked to see if what you said worked

**Comment by photopea** [comment]
Updating a browser should take about 15 seconds, maybe 20 at most. It should be in the menu somewhere. Try too Google how to udpate your browser, if you can not find it.

**Comment by Rosejustrose** [comment]
I have updated i just have not gone to my computer in a day or two so i have to wait until i get on it to see if the brushes work
