### ISSUE TITLE
Layers window not updating

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2058]
After I change Layer Style or Blending Options of layer via Layer Style/Blending Options dialog or by Layer Style-Copy Layer Style-Paste or by removing Effect by drag and drop to delete button in the bottom it does not update Layers window contents with new Effects and/or Blending mode and Opacity. It will update only after I click on that window.

**Comment by photopea** [comment]
Hi, I think I fixed it. Thanks for reporting.

The Layers panel used to be redrawn e.g. while panning with a mouse wheel. With thousands of layers, it caused a huge lag - panning was not smooth. So I changed the mechanism. Now, every action should say explicitly, that it modified a layer list. But I forgot to add it to all actions. Maybe there are more such actions.

**Comment by hxim** [comment]
> Maybe there are more such actions.

Hi, I found one more:
When you have Smart Object and try to add Filter to it (as Smart Filter) it does not update.

**Comment by photopea** [comment]
Fixed, thanks! :)

**Comment by hxim** [comment]
@photopea 
I found one more again:
1. Open New Project
2. Add text with Type Tool
3. Try to undo by clicking on "Open" in History window
4. Layers window is not updated

**Comment by photopea** [comment]
Fixed, thanks! :)
