### ISSUE TITLE
My adblock is disabled but

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2059]
My adblock is disabled - see the gray icon of Adblock Plus extension but
it showed me this pop-up and no ads are ever showing in Mozilla Firefox.
Screenshots:

![obrazek](https://user-images.githubusercontent.com/6370548/79725401-75965a00-82e9-11ea-963f-731f92a0bb9f.png)

![obrazek](https://user-images.githubusercontent.com/6370548/79725568-aececa00-82e9-11ea-9f24-c65d19dab0a1.png)

**Comment by photopea** [comment]
Is it the Incognito mode in Firefox?

Incognito mode in Firefox always blocks ads for some reason, it can not be changed. Try any other website, if you see ads there.

**Comment by hxim** [comment]
I use this setting
![obrazek](https://user-images.githubusercontent.com/6370548/79727558-dc694280-82ec-11ea-9e53-a2b5adbe8056.png)
which means it is always behaving like incognito mode i guess??
I see some ads on other sites if I disable Adblock there but I am not sure if it is all of them.

**Comment by photopea** [comment]
I do not really know much about Firefox. The fact is, that in your case, Firefox blocked loading some Javascript files, which we consider to be blocking ads.

Also, in your screenshot, no ads are visible, which means, that you are blocking them.

**Comment by photopea** [comment]
@hxim did you find a way how to solve it? Several users are complaining about it, too, I would like to help them.

**Comment by photopea** [comment]
I just noticed, that in Firefox, you can have an extension installed and working, while its icon is not present in the top right corner of a browser.

**Comment by hxim** [comment]
> 
> 
> @hxim did you find a way how to solve it? Several users are complaining about it, too, I would like to help them.

@photopea 
No I stopped using Firefox long time ago for Photopea back in 2017 I think because of the ALT issue #338
