### ISSUE TITLE
Handling huge vector shapes

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#206]
Some Sketch files may contain shapes, that are 5000 x 7000 px (or larger). Rasterizing such shapes would consume a lot of computer memory.  E.g. 12 MB Sketch file may need 10 GB of RAM.

We need to change the way we handle vector graphics.

**Comment by anasred** [comment]
I have 1.2GB psd file and even after installing your chrome app extension. Chrome crashed

**Comment by photopea** [comment]
The Chrome app  is just a bookmark for Photopea.com , it just redirects to photopea.com . There is no extension.

Photopea can not work with so big files yet :(

**Comment by photopea** [comment]
This bug was inspired by some Sketch files, which contained huge vector shapes (30000 x 30000 px). But that case, it was incorrect parsing of Sketch files, actual shapes were much smaller. I think we don't have to care about such big shapes at this point.

**Comment by photopea** [comment]
@anasred  I improved the handling of big PSD files. It may take a lot of time and RAM, but if you have both, you should be able to open it. You should see an alert, when there is not enough RAM.
