### ISSUE TITLE
Layer visibility is broken

### ISSUE THREAD

**Issue by LarryAP** [photopea/photopea#2060]
Hi
When I click the 'eye' symbol to make a layer visible or invisible, the other other layers also become randomly visible or invisible too.

**Comment by photopea** [comment]
Hi, does it also happen in Incognito mode (without browser extensions)?

**Comment by LarryAP** [comment]
I'm using it as an installed Chrome app

**Comment by photopea** [comment]
Please, try it in Incognito mode in a web browser, to see if it still happens.

**Comment by LarryAP** [comment]
Will do. It's happening intermittently - only when I'm really busy :) so I'll report back.

**Comment by photopea** [comment]
I am closing it because of lack of details.
