### ISSUE TITLE
photopea has no ads with or without Ad Blocker

### ISSUE THREAD

**Issue by 253488655422** [photopea/photopea#2061]
I used this website in multiple browsers, removed all extensions, cleared cookies, and cache but still it thinks I'm using Ad Blocker and keeps giving me an annoying pop-up when I'm editing my image so help me please fix this silly issue because I really want to get back to editing I really don't care if there ads just fix this!!

**Comment by photopea** [comment]
Hi, can you check your antiviruses or VPNs? Maybe they are blocking ads.

**Comment by 253488655422** [comment]
um I don't use vpn or antivirus because I wanted to port forward a while ago but I don't understand there aren't ads even when I reload. What should I do?

**Comment by 253488655422** [comment]
My friend just tested it and he says he has the same problem 😟

**Comment by FreakinCoolUsername** [comment]
Same issue here.

**Comment by FreakinCoolUsername** [comment]
No VPN or ad blocker but i do have malwarebytes but it isn't flagging anything, if i had to guess you ads server isn't connecting.

**Comment by photopea** [comment]
What web browsers do you use? Does it happen in two different browsers, e.g. Firefox and Chrome?

**Comment by sefradomes** [comment]
Same issue. Using chrome.

**Comment by photopea** [comment]
@sefradomes Have you disabled all your browser extensions?

**Comment by photopea** [comment]
Can you guys open this link in your browser? https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js

If not, it means something is blocking websites for you.

**Comment by 253488655422** [comment]
I can't open that. That link is broken have you checked the link? It says the site can't be reached the server IP can't be found.

**Comment by photopea** [comment]
can you try to open that link on some other computer or a phone (while on wifi)? If not, then, your internet provider is blocking websites. You should ask him about it.

**Comment by 253488655422** [comment]
Excuse Me but I have never had an issue with this website until now I didn't change or added any programs lately like a vpn and my friend had the same issue. Have you checked that if the link worked for you.

**Comment by photopea** [comment]
@253488655422 We started to ask people to watch ads on Monday, because too many people were hiding them (before that, we tolerated people hiding ads). The link at the top works for me and for millions of people who use Photopea.

Do you see ads in Photopea on the right side? Can you open Photopea on some other network, e.g. a mobile network instead of WiFi?

**Comment by Bobrow** [comment]
I'm having the same issue, going to the link you provided downloaded "f.txt" which contains large amounts of javascript as it should. One intresting thing is that google chrome has a setting to "block ads that show intrusive or misleading content" and I believe that having to watch a video ad would fall under that, I realise that you require ads to be able to maintain this platform but maybe a video ad is a little too far, an alternative that might work is to make people who block ads to not be able to use the site at all, like an insite pop up (not provided by the browser) that dosen't allow users to get past unless there adblock is turned off, also with something like this you would have to make a small piece of code that checks if that is still there when it is ment to be as many adblocks have 'element zapper' features which would remove it all and allow them to get past.

Hope this helps :)

**Comment by photopea** [comment]
@Bobrow  Are you still having the issue, after disabling all browser extensions?

Photopea never shows video ads or ads which cover the user interface.

**Comment by Bobrow** [comment]
the only browser extension is google docs offline but i'll try disabling that

**Comment by Bobrow** [comment]
I am so confused, after disabling google docs offline, it now works. thanks, btw i got the impression that there were video ads by your reply to 253488655422 but i must of misunderstood

**Comment by photopea** [comment]
"Google Docs Offline" :D Do you know that anybody can make an extension, name it "Google Docs Offline" and put it on the chrome store?

**Comment by photopea** [comment]
BTW. which Google Docs Offline were you using? I tried installing this: https://chrome.google.com/webstore/detail/google-docs-offline/ghbmnnjooekpmoecnnnilnnbdlolhkhi   But Photopea still works :/

**Comment by photopea** [comment]
I am closing it now.
