### ISSUE TITLE
Showing Ads but asking me to unblock Ads

### ISSUE THREAD

**Issue by nasirkhan** [photopea/photopea#2062]
I am using Photopea for a long time and usinng the same browser (Firefox) and same os (Ubuntu 18.04). 

From yesterday i am getting a notice to unblock the Adblock. 

![Screenshot from 2020-04-21 16-49-21](https://user-images.githubusercontent.com/396987/79857981-75cd4d00-83f0-11ea-8547-d3794cc4f6b7.png)

**Comment by photopea** [comment]
In your case, Photopea can not successfuly load the file https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js . Can you open that file in your browser? Do you have any extensions, that could be blocking it?

**Comment by nasirkhan** [comment]
I could not open the link directly either. I tried in private browsing mode as well but failed to open.

**Comment by photopea** [comment]
Do you have any antivirus programs in your computer or VPNs? Maybe your Internet provider is blocking these.

**Comment by nasirkhan** [comment]
I use Ubuntu and there is no additional service or vps is running. is there any other way to fix this issue?

**Comment by photopea** [comment]
You should find out, why you can not open https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js  . It is a regular link, which can be opened from any part of the world.

Can you try it in your phone? If it still does not work, it is probably your Internet provider doing it.

**Comment by photopea** [comment]
I am closing it because of lack of details. If your internet provider is blocking websites, which Photopea works with, you should report it to them.
