### ISSUE TITLE
(feature request) Support for .psb files?

### ISSUE THREAD

**Issue by redbrain1014** [photopea/photopea#2063]
.PSB (photoshop big) is a format I'd love to see supported in the webapp (if it isn't already, i tried uploading a psb and nothing happened)

**Comment by photopea** [comment]
Hi, Photopea supports PSB since 2014. What exactly happens when you open your PSB? How large is it?

**Comment by redbrain1014** [comment]
hm, its very large, 4gb. an error message may have appeared briefly but i was not looking at the window at that moment. maybe i did not wait long enough

**Comment by photopea** [comment]
Currently, Photopea works completely in RAM memory. You need to have a free RAM of 5x the size of the file you want to open. So in your case, you need 20 GB of free RAM space.

**Comment by redbrain1014** [comment]
yeah, i dont have that much memory. thank you!

**Comment by photopea** [comment]
I am very sorry. We thought such huge files will be quite rare, so we decided to invest our efforts into other features. But files under 1 GB usually work well in Photopea.

**Comment by redbrain1014** [comment]
honestly it is quite rare for a filesize like this, i think the app is
great for just light photoshopping when you dont actually have photoshop.
im going to edit it on my actual copy of photoshop now, i just had my
laptop (without photoshop) at that point in time. thanks a lot for your
help. this is likely the best support ill ever receive for a small webapp
like this.

**Comment by photopea** [comment]
Photopea can save files in the PSB format now: https://twitter.com/photopeacom/status/1349770822211268613
