### ISSUE TITLE
Don't have any adblockers, vpns, or virus protection services but still will not let me go 3 seconds without asking me to unblock ads.

### ISSUE THREAD

**Issue by snaccerpaccerz** [photopea/photopea#2064]
I've tried the link, testing it in different browsers, but will not stop bugging me about ads.
![Screenshot 2020-04-22 at 1 11 18 AM](https://user-images.githubusercontent.com/57503014/79946746-3295cd00-8436-11ea-95e3-2f103b170b71.png)

**Comment by nefretiart** [comment]
the same problem

**Comment by photopea** [comment]
Hi, the ad is not visible on the right side of your browser. Something is blocking it.

Can you look into chrome://extensions/ and disable extensions that block ads? It can also be your antivirus or other software, which monitors your web traffic.

**Comment by snaccerpaccerz** [comment]
Back whenever this issue wasn't happening, there weren't ads there to begin with. Also, I went into extensions, and nothing is blocking ads, and my antivirus software isn't blocking anything either.

**Comment by photopea** [comment]
@snaccerpaccerz How do you know if your extensions are blocking ads or not? Every extension is capable of blocking ads. Please, try Photopea in Incognito mode. Do you see ads there or not? BTW. Firefox is always blocking ads in Incognito just by itself.

**Comment by ilkerkaran** [comment]
@photopea, I have added https://www.photopea.com/ to white-list. it still blocks me. I am not sure what kind of ad you are trying to show and firefox blocks it all along. It is not usable as it is.

**Comment by photopea** [comment]
@ilkerkaran  Try to find a browser which does not delete ads in Photopea. I can use Photopea in Chrome and Firefox without any problems.

**Comment by ilkerkaran** [comment]
I can confirm it works in chrome without any problem. However, does not work in Firefox Developer Edition even if I stop ad block.

**Comment by photopea** [comment]
Maybe Firefox is blocking some domains by itself? Can you change Firefox settings?

**Comment by snaccerpaccerz** [comment]
@photopea I tried it in incognito mode and with a VPN and I did not work. It is still saying I am blocking ads. I don't know what's going on, but nothing I do will fix it.

**Comment by photopea** [comment]
@snaccerpaccerz I think your internet provider is blocking it then. Could you get in touch with him and tell him about your problem? Even the fact, that your internet provider knows which websites you are visiting, is already disturbing.

**Comment by photopea** [comment]
I am closing it now. It is always either a browser extension, or the internet provider.

You should either pay 10 USD for a Premium version, or find an internet provider which does not break your websites.
