### ISSUE TITLE
photopea crashing when im making or trying to save psd colourings

### ISSUE THREAD

**Issue by hdkiix** [photopea/photopea#2065]
i am using my ipad and working on safari.

i often try to make psd colourings using photopea since i know some others do the same using the site, but when i try to save the psd, the site often crashes. how can i fix this? its very frustrating as a lot of time and effort goes to waste since photopea keeps crashing

**Comment by photopea** [comment]
Hi, does it crash every time or just sometimes? iOS Safari is known for killing websites when they use a lot of RAM. What is the resolution of your document (in pixels) and how many layers do you have?

**Comment by photopea** [comment]
I have to close it because of lack of details.
