### ISSUE TITLE
No se puede copiar ni pegar

### ISSUE THREAD

**Issue by Alexjr999** [photopea/photopea#2066]
Hoy quería editar una imagen y necesitaba copiar y pegar partes seleccionadas de otra imagen y no podía hacerlo. Tanto si pulsaba las teclas ctrl + c  y ctrl + v  o manualmente copiar y pegar. No pasa nada al hacer estos comandos, por lo que no se puede realizar dichas acciones.

**Comment by photopea** [comment]
Hi, it should be possible to solve it with these steps: https://github.com/photopea/photopea/issues/1912

**Comment by Alexjr999** [comment]
> Hola, debería ser posible resolverlo con estos pasos: [# 1912](https://github.com/photopea/photopea/issues/1912)

No, el acceso al portapapeles está permitido, tiene que ser otro tipo de error.

**Comment by photopea** [comment]
Are you using Photopea at www.Photopea.com ? Please, use it at www.Photopea.com

**Comment by InesRachel** [comment]
Im having he same fliping issue, Its annoying. Im using Potopea.com and its the same problem. The issue is in the app, you need to fix this.

**Comment by photopea** [comment]
@InesRachel Did you give Photopea permissions to access the clipboard? It is described here: https://github.com/photopea/photopea/issues/1912 . Also, what website are you using for Photopea?
