### ISSUE TITLE
Photopea not loading

### ISSUE THREAD

**Issue by davidmathew** [photopea/photopea#2067]
The page just wont load

**Comment by davidmathew** [comment]
![Screen Shot 2020-04-22 at 5 43 25 PM](https://user-images.githubusercontent.com/3677816/79980789-43d7eb80-84c1-11ea-9274-8561d21692f5.png)

**Comment by photopea** [comment]
Hi, what browser are you using? Photopea will not work in browsers more than 10 years old.

**Comment by davidmathew** [comment]
I'm using google chrome

**Comment by photopea** [comment]
Can you try it without any browser extensions? You can try it e.g. in Incognito mode (extensions are disabled in it).

**Comment by davidmathew** [comment]
yeah i did. tried safari private mode and google incognito. same screen appears.

**Comment by photopea** [comment]
Something is blocking Javascript and other files to be loaded. Can you right-click the webpage, press Inspect Element, are there any messages? Do you have an antivirus which could be blocking your web traffic?

**Comment by davidmathew** [comment]
[Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://fonts.gstatic.com/s/opensans/v17/mem5YaGs126MiZpBA-UN7rgOUuhpKKSTjw.woff2
(index):1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://fonts.gstatic.com/s/opensans/v17/mem8YaGs126MiZpBA-UFVZ0bf8pkAg.woff2

**Comment by davidmathew** [comment]
I dont have any antivirus installed. is it an issue with mac os?

**Comment by photopea** [comment]
I think it means that your computer can not properly load files from our server.

Btw. can you open Photopea.com on your phone? Is the page also empty?

**Comment by davidmathew** [comment]
Page is empty

**Comment by photopea** [comment]
I think your internet provider is blocking the access to Photopea. Can you report it to him, that you have such problem?

**Comment by davidmathew** [comment]
okay will do it

**Comment by photopea** [comment]
Did it help? If not, we can keep looking for a solution. But since millions of People are using Photopea without any problems, I think the problem is on your side.
