### ISSUE TITLE
Copy and paste

### ISSUE THREAD

**Issue by InesRachel** [photopea/photopea#2068]
Photopea wont let me copy and paste. And  not, its not a problem from my laptop or browers. I have tried it on 3 browers. Google, Microsoft Edge, Internet Explorer, it wont copy paste. I even tried it on my phone and it doesnt work. Can you fix this please.

**Comment by photopea** [comment]
Hi, are you using Photopea at www.Photopea.com ?

**Comment by photopea** [comment]
Also, did you give Photopea permissions to use a Clipboard, when you were asked?

**Comment by InesRachel** [comment]
It was working 2 days ago tho and I have used it for a month now, it stopped working yesterday so I think the error is with the app or site.

**Comment by photopea** [comment]
Could you try steps mentioned here: https://github.com/photopea/photopea/issues/1912 ?

We did not change the copy-paste functions recently, and they work well in my case.

**Comment by InesRachel** [comment]
Permission is allowed and it still wont work. I see a few people have this issue.

**Comment by photopea** [comment]
Are you using Ctrl+C and Ctrl+V on your keyboard? Can you try Edit - Copy or Edit - Paste in the top menu? Also, do it in Chrome. Photopea never worked in Internet Explorer.

**Comment by photopea** [comment]
Also, can you try the Incognito mode in Chrome? Maybe your browser extensions are blocking it.

**Comment by InesRachel** [comment]
I have tried ctrl not working. I am using Google and its still not working, incognito mode not working either. This is frustrating.

**Comment by InesRachel** [comment]
Its working now.

**Comment by photopea** [comment]
What was the problem?
