### ISSUE TITLE
How to scale down to xx.xx%

### ISSUE THREAD

**Issue by rjian001** [photopea/photopea#2069]
Hi! Guys,
I tried several times. It seems that an image can only be scale down to a whole number percent, ie, xx%.
I am wondering if we can scale down to xx.xx%.
Thanks
Richard

**Comment by photopea** [comment]
Hi, do you mean Image - Image Size?  The current input for percent allows only integers. Should I allow decimal values there?

By the way, it might be impossible to scale the image to the exact percent value you want. Let's say your image is 2x2 pixels. You want to scale it to 60%, but the size can be either 1x1 (50%) or 2x2 (100%), there is nothing in between.

**Comment by rjian001** [comment]
Thanks for replying.

Yes, I think it is the image size. When I perform the "free transform - scale", it seems that only image size (not the canvas size) will be changed.

If the image is 3000x3000 pixels, there will be a huge difference between 20% and 20.4%. It will be 600x600 vs 612x612. 

Thanks again.

**Comment by photopea** [comment]
Ok, I implemented it. Note, that the percent value is always rounded to correspond to the integer pixel size. Even if you enter e.g. 50% and the document width is not an even number, it will be changed e.g. to 49.75

**Comment by rjian001** [comment]
thanks. let me try.

**Comment by rjian001** [comment]
I tried several times. The scale still takes whole number only (ie. xx% only, not xx.x%). Please check out the scale parameter in red square on the attached image.
![photopea_whole_number_scale](https://user-images.githubusercontent.com/17462846/80124910-f4e09380-855e-11ea-8cb1-a46a8bcdc519.jpg)

**Comment by photopea** [comment]
Ok, I allowed decimal values for the Free Transform, too.

**Comment by rjian001** [comment]
Thanks, let me try.
