### ISSUE TITLE
.PSD file won't load

### ISSUE THREAD

**Issue by GabrielBrangers** [photopea/photopea#207]
I have loaded your example .psd and it works fine. My .psd file just sits there and says "loading"

**Comment by photopea** [comment]
Hi Gabriel, can you send your file to support@photopea.com ?

**Comment by GabrielBrangers** [comment]
Sure can.

**Comment by photopea** [comment]
Thanks. The problem was in the unexpected format of the pattern used for Alaska.

I implemented that new format and it works now :) Thank you very much for reporting it!
