### ISSUE TITLE
Popup showing a message to remove ads

### ISSUE THREAD

**Issue by SvenWritesCode** [photopea/photopea#2070]
There is an alert that says

> We use advertisement to get money for our development. Your device seems to be blocking ads. Please, let us show you ads, or buy a Premium account (Account - Log In - Buy).  0

![image](https://user-images.githubusercontent.com/7458951/80135451-3f1d4100-856e-11ea-8838-427c8abc0370.png)

This does not allow the user to click anywhere until the alert is dismissed.

**Comment by SvenWritesCode** [comment]
A temporary fix would be to enter `window.confirm = ()=>{}` in the dev console.

**Comment by photopea** [comment]
Hi Sven, we would like users to watch our ads, because ads are the main source of our income, and there would not be any Photopea without ads.

**Comment by metwomey** [comment]
I have checked the settings to make sure the ad blocker was off and it still happens. I was going to try and record a tutorial for my students but I can't get rid of that pop up!

**Comment by photopea** [comment]
@metwomey Can you try Photopea in Incognito mode? Incognito mode is a browser without any extensions.

**Comment by metwomey** [comment]
I did as you suggested and the ads are showing on the side now. This not the first tutorial I've done, I don't know why it started happening. The only thing that changed was I added Emoji Keyboard to chrome. I could try uninstalling it and see if that makes a difference too.
Thanks!

**Comment by photopea** [comment]
Try to disable all browser extensions and Photopea will work well. Then, you can enable them back, one by one, until you find the extension which breaks Photopea.

**Comment by photopea** [comment]
In 90% of cases, you are using a browser extension, which blocks Photopea. Photopea (and other websites) can not disable your extensions. I am really sad about it. If you allow an extension to break websites for you, you should not wonder that websites do not work.
