### ISSUE TITLE
Font not showing up

### ISSUE THREAD

**Issue by the-elleb** [photopea/photopea#2072]
I am new to Photopea. I attempted to use the font and it wont show up. When I type I have the color set to where it is different than the background (black text on white background). I have attempted to change the size in hopes that maybe it was either too small or too large, nothing changes. When I select the check mark to finish it, it shows me on the right side where the layers are, what I typed. You just cant see it when youre typing it or after you finish. It doesnt allow you to selct the text with your mouse either. Its as is there is nothing there at all but it shows up in the layer.

**Comment by the-elleb** [comment]
NVM, i had to close the program and open it again and it worked.

**Comment by photopea** [comment]
If you find steps how to reproduce this issue, let us know!
