### ISSUE TITLE
Can't close or accept corner radius after few steps

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2073]
<img width="1280" alt="obraz" src="https://user-images.githubusercontent.com/38118273/80157195-e7122900-85c5-11ea-8563-f64aa0c4ceb1.png">

`pp.js:4710 Uncaught TypeError: Cannot read property 'clone' of null
    at m.dA.SpF (pp.js:4710)
    at SG.VT (pp.js:8652)
    at SG.dk.Y (pp.js:9)
    at SG.gM.Y (pp.js:7077)
    at SG.gt.SsD (pp.js:8144)
m.dA.SpF @ pp.js:4710
SG.VT @ pp.js:8652
dk.Y @ pp.js:9
gM.Y @ pp.js:7077
gt.SsD @ pp.js:8144
pp.js:4709 Uncaught TypeError: Cannot read property 'add' of null
    at m.dA.SpF (pp.js:4709)
    at SG.xs (pp.js:8652)
    at gi.dk.Y (pp.js:9)
    at gi.gM.Y (pp.js:7077)
    at gi.tq (pp.js:7233)
m.dA.SpF @ pp.js:4709
SG.xs @ pp.js:8652
dk.Y @ pp.js:9
gM.Y @ pp.js:7077
gi.tq @ pp.js:7233`

**Comment by MichalSZZ** [comment]
1. Make Square
2. Duplicate and rotate 45deg
3. Ctr+e for merge
4. Select all with Direct Select tool
5. Set corners roundnes to 30px
6. Merge 2 shape paths
7. Select one new sharp corner and set corner radius,
8. Make it again with next corner and again and next time pop up window doesn't work.

**Comment by photopea** [comment]
I am afraid I can not reproduce it. After step 6, I get a shape below. I can modify its corners.
[New Project.zip](https://github.com/photopea/photopea/files/4525743/New.Project.zip)

**Comment by photopea** [comment]
BTW. you can press File - Publish Online - PSD, and shere the link of that PSD with me.

**Comment by MichalSZZ** [comment]
I can't do that again too :/ But I had that situations twice.
You can see errors on my pasted screen above too.

BTW. I found little bug -> try to type letters in corner radius input :)

**Comment by hxim** [comment]
1. Make Square
2. Select one corner with with Direct Select tool
3. Click Corner Radius button
4. Click on image (outside of dialog)
5. Click OK in dialog

Uncaught TypeError: Cannot read property 'add' of null
    at m.dA.SpF (pp.js:4709)
    at SG.xs (pp.js:8652)
    at gi.dk.Y (pp.js:9)
    at gi.gM.Y (pp.js:7077)
    at gi.tq (pp.js:7233)

**Comment by photopea** [comment]
I see, I fixed it, thanks! :)

**Comment by MichalSZZ** [comment]
@hxim thanx! 
BTW. Whenever I read your Issues here I'm very impressed about your testing skills!

**Comment by photopea** [comment]
@MichalSZZ @hxim  Me too! He finds issues which I think other users would not find in 1000 years. He also describes them very well :) We met in person with @hxim more than a year ago and he is really an impressive guy! :)
