### ISSUE TITLE
adblocker error

### ISSUE THREAD

**Issue by LJF206** [photopea/photopea#2074]
i have my ad blocker off and is still sends a notification saying its on and wont let me work until i get rid of it

**Comment by photopea** [comment]
Hi, can you try Photopea again with absolutely all browser extensions deactivated? You don't have to remove them, you can activate them later.

**Comment by LJF206** [comment]
it still comes ups

**Comment by LJF206** [comment]
never mind i found out

**Comment by photopea** [comment]
Can you open this link: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js ?

**Comment by LJF206** [comment]
no

**Comment by photopea** [comment]
Then, your internet provider is blocking the website. Try to tell him about it, so that he unblocks it.

**Comment by tyronx** [comment]
I have the same issue and I'm pretty sure my provider does not block any ads. More looks like a same-origin-policy error. In the Network tab, I don't see any blocked or failed http requests
![photopea](https://user-images.githubusercontent.com/762006/80298667-512df800-8797-11ea-8504-744df14fabe6.jpg)

**Comment by tyronx** [comment]
Ohwait, its firefox itself blocking the stuff

**Comment by LJF206** [comment]
I’m using chrome and opera gx

**Comment by photopea** [comment]
@LJF206  You should ask your internet provider to unblock https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js and other websites for you. What is the point of such internet connection, when you can not access any website you want?

**Comment by TheMClaeys** [comment]
I think it's indeed Firefox itself that's blocking it. I got annoyed by the pop-up, opened in Chrome and didn't see the popup anymore. Both browsers without Adblock on Photopea.

**Comment by photopea** [comment]
I will close it now.
