### ISSUE TITLE
Type Tool issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2075]
1. New Project
2. Select Type Tool
3. Add text "Hello" as Point Text (click and write Hello)
4. Now you want to add second text as Point Text by clicking but your hand is shaking little bit and you accidently move your mouse while clicking slightly creating instead Paragraph text but with 0px height or very small height. You start typing text "xxx" but
a) Nothing appears as you writing (because this is Paragraph text with 0 height box)
b) Very strangely word "Hello" from previous layer appears appended after the "xxx" word making it "xxxHello" instead (as you can see in name of layer after you confirm or if you convert to Point Text afterwards)

**Comment by photopea** [comment]
Hi, I "improved" the criteria of when a Paragraph text layer is created. You should click and move the mouse at least 4px to the right and at least 4 px down.

I can not reproduce this "xxxHello" issue, how exactly can I make it appear?

**Comment by hxim** [comment]
Now I can not reproduce the "xxxHello" issue too. It seems to be fixed with your changes....
