### ISSUE TITLE
Writing text in numerical inputs -> NaN

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2078]
As was metioned in #2073 you can write text into numerical inputs and it changes to NaN value.
It causes errors in various places in photopea - For example:
1.) In layers window Opacity NaN%
-> All content behind that layer becomes transparent and if you save and load as psd it becomes 0%.
2.) Brush size NaNpx
-> Uncaught TypeError: Failed to execute 'createRadialGradient' on 'CanvasRenderingContext2D': The provided double value is non-finite.
3.) Properites - Live shape corner radius NaN
-> Uncaught TypeError: Cannot read property 'toFixed' of null
4.) In Free Transform - NaN°
-> Uncaught RangeError: Maximum call stack size exceeded

**Comment by photopea** [comment]
Hi, I fixed it. If the typed value is not a number, it will be changed to zero.

**Comment by hxim** [comment]
Hello if you clear the value or write text and then immediately use arrow keys UP and DOWN on keyboard or try to change value with slider on field label it still goes to NaN and causing same errors.

**Comment by photopea** [comment]
I fixed that too, thanks!

**Comment by hxim** [comment]
Well, this kind of slider still changes it to NaN
![obrazek](https://user-images.githubusercontent.com/6370548/80202167-84507a00-8625-11ea-8038-3ba0749f45de.png)

![obrazek](https://user-images.githubusercontent.com/6370548/80202081-6125ca80-8625-11ea-82d1-9075b9b6d95b.png)

**Comment by photopea** [comment]
Fixed, thanks! :)
