### ISSUE TITLE
Google chrome autocomplete issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2079]
When I clear input value (for example Opacity in Layers window) there are sometimes autosuggestions or autocomple items from Google Chrome browser. After I click on one of the items it shows error in console see screenshots:

![obrazek](https://user-images.githubusercontent.com/6370548/80192078-f1104800-8616-11ea-872c-f1e651a11f90.png)

![obrazek](https://user-images.githubusercontent.com/6370548/80192240-2d43a880-8617-11ea-9e7e-6973841411af.png)

**Comment by photopea** [comment]
How do I enable such autocomplete feature? I tried right-clicking, but there is nothing there.

**Comment by hxim** [comment]
I don't know how I added items there. It was probably long time ago. It seems I am not able to add items there now again. I cleared all saved autofill data in my browser now and there are no items now.
FYI the menu appeared when I cleared value and left-clicked... (now it is not doing anyyhing as I cleared all saved autofill data in browser)

**Comment by photopea** [comment]
I will close it now, I don't think it is a frequent scenario.
