### ISSUE TITLE
Long time loading

### ISSUE THREAD

**Issue by neise** [photopea/photopea#208]
Is there a problem with the system right now? I am having a hard time loading my design to edit. Same file as always but it just says "Loading" and never loads or goes away.

**Comment by photopea** [comment]
Hi, so your file worked before? Can you send it to support@photopea.com ?

**Comment by neise** [comment]
My mistake, I was trying to load a zipped file instead of the unzipped item. It is working perfect now, so sorry about that. But I do appreciate your quick response! Thank you!!

**Comment by photopea** [comment]
No problem, I fixed it anyway. Now, if open a ZIP file, you will see the message "Unexpected ZIP file".
