### ISSUE TITLE
Corner Radius issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2080]
1.) New Project
2.) Create Rectangle
3.) Select Direct Select Tool
4.) Select all 4 corners
5.) Click Corner Radius button
6.) Cancel with X
7.) Using Edit-Free Transform make rectangle much smaller
8.) Click Corner Radius button
9.) Rectangle changes to its original size for no reason...

**Comment by photopea** [comment]
fixed, thanks!
