### ISSUE TITLE
Free transform box on Work Path

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2081]
1.) New Project and unlock Background layer
2.) Select Free Pen tool and set Path setting in top toolbar
3.) Make two shapes like on screenshot 1 (as one work path)
4.) Select Direct Select tool
5.) Select part of the points in left shape and part of the point in right shape
6.) Edit-Free Transform
7.) Transform box appears in wrong place over second shape instead of selected points and
    if you for example rotate it rotates selected points not contents of the box (as seen on screenshot 2)

![obrazek](https://user-images.githubusercontent.com/6370548/80204360-01312300-8629-11ea-86b7-09e9a50ef135.png)
![obrazek](https://user-images.githubusercontent.com/6370548/80204379-0b532180-8629-11ea-9f81-42131b3e43d2.png)

**Comment by photopea** [comment]
Hi, I just tried it in Photoshop. The bounding box is around the whole path, but only the selected points are transformed.

You say you select points in different shapes, but the box is just around one shape. I could not reproduce it. Can you share your PSD with me? Just press File - Publish Online - Photopea.

**Comment by hxim** [comment]
https://www.photopea.com/#ip6RcQbPG
But if I open this existing file it behaves differently and box is around both shapes:
![obrazek](https://user-images.githubusercontent.com/6370548/80207608-bc0fef80-862e-11ea-839e-795457ba4f23.png)
If I reload photopea and try steps from first message it has box around second shape only like this:
![obrazek](https://user-images.githubusercontent.com/6370548/80207698-ed88bb00-862e-11ea-92f4-ec1da5ee9c0d.png)
In both case if I rotate/change size it applies transform only on selected points.

**Comment by photopea** [comment]
Hi, transforming only the selected points is the correct behavoiur.

I tried to select points just like in your screenshot, but the transformation rectangle is always around both paths.

**Comment by hxim** [comment]
> I tried to select points just like in your screenshot, but the transformation rectangle is always around both paths.

Here is video of what I am doing:
https://youtu.be/ZEgNpOsu-aQ

> Hi, transforming only the selected points is the correct behavoiur.

But if I do exactly the same but not with Work Path but regular Shape Path (I keep Shape setting for first shape and switch to Path setting only for second shape) it does box like this what I think is more logical:
![obrazek](https://user-images.githubusercontent.com/6370548/80225504-757cbe00-864b-11ea-8f47-36c7e9e952ae.png)

**Comment by photopea** [comment]
So I guess it is a feature of Photopea and Photoshop, not a bug.
