### ISSUE TITLE
Copy/Paste not pasting

### ISSUE THREAD

**Issue by oakridgelights** [photopea/photopea#2082]
I've been trying to do a simple copy/paste function, but can not get the paste part to work.

**Comment by photopea** [comment]
Hi, try to allow the access to a clipboard: https://github.com/photopea/photopea/issues/1912

Also, use Photopea at www.Photopea.com

**Comment by oakridgelights** [comment]
Access to clipboard was allowed.  Still having the same issue.

**Comment by photopea** [comment]
Are you using Photopea at www.Photopea.com ?
