### ISSUE TITLE
Unable to load styles

### ISSUE THREAD

**Issue by dashaken** [photopea/photopea#2085]
Hello,

since yesterday i can't load any styles. It worked for weeks with my uploaded .asl styles now i can't get to that window.

**Comment by dashaken** [comment]
![image](https://user-images.githubusercontent.com/64353519/80303237-3798aa80-87af-11ea-9de6-cea72227cceb.png)
Nothing opens

**Comment by photopea** [comment]
Hi, it should be fixed now :)  Thanks for reporting it!

**Comment by dashaken** [comment]
Yeah it works. Thank you!
