### ISSUE TITLE
ISSUES: TOOLS ARE NOT WORKING.

### ISSUE THREAD

**Issue by BreezeMadelynn** [photopea/photopea#2087]
Hi, some of the working tools are not working? Was it a bug or something? I'm not really sure. I was working on my graphics yesterday and suddenly the tools were not working.  I can't use my brush and eraser tool. I clicked on them many times but it doesn't show me the sizes and brushes. And also, I can't use the Spot healing brush tool. 

I downloaded Photopea as well.

**Comment by BreezeMadelynn** [comment]
I'm using my laptop btw.

**Comment by BreezeMadelynn** [comment]
and oh, it works perfectly fine in incognito mode, but i have all my brushes and styles in chrome/laptop so I think it would be a little troublesome because incognito won't save my brushes and styles ><

**Comment by BreezeMadelynn** [comment]
and one more thing, when i added my brushes in photopea (in incognito mode), i clicked on the brushes tool but it didn't show any sizes or patterns of my brush, i assumed that some of my brushes were not compatible with the whole format? but it works completely fine yesterday.

**Comment by photopea** [comment]
Hi, If there is a problem with using Photopea in a regular mode, try to disable all your browser extensions. Also, try to update your browser.

If you have an ABR file, which is problematic, please, send it to me to support@photopea.com

**Comment by BreezeMadelynn** [comment]
I've updated my browser and try to disable my browser extensions, but it still doesn't work for me ><

**Comment by photopea** [comment]
So it works in Incognito mode, but not in a regular mode?

**Comment by BreezeMadelynn** [comment]
yeah, but when I added my brushes in incognito, i can't click on the brush tools. so i think my brush tools have something to do with it? let me send me all the ABR files. 

ketchy_drawings__26_by_lilithdemoness_dbha28l.abr
_paper_brushes__5_by_itsvenue_dcg4csg.abr
_brushes_paint__23_by_itsvenue_dcysy6s.abr
Day 2.abr
manga_speech_bubbles_by_faeth_design_d183f4o.abr
shoujo_wonderland_brushes_by_kabocha_d4blcxj.abr
moons_and_stars___17_brushes_by_ashqtara_d2r57i8.abr
01_brush_by_chen_ye_by_chen_ye_daz5k8k.abr
dashed_and_dotted_line_brushes_by_blacknovart_d2fvhh4.abr
brushes_set_001_by_itsvenue_dcb166w.abr
gic___brush_pack_by_nextviewdesigns_d2a6wmx.abr
_new_brush_by_natieditions00_d73p6ie.abr
@imsxphie (1).abr
Brush_by_TokisakiDesigner.3.abr
Brush_by_TokisakiDesigner.2.abr
Brush_by_TokisakiDesigner.abr
BrushByTokisaki.abr
randomlines by btchdirectioner deviantart com.abr
fireworks brushes ( by allscallie ).abr
seashells brushes ( by allscallie ).abr
crystals brushes ( by allscallie ).abr
plants brushes ( by allscallie ).abr
flowers brushes ( by allscallie ).abr
polaroids brushes ( by allscallie ).abr
BokehBrushes.abr
+StarBrushes;AsianWorld.abr
._SS-arcane-circlesII.abr
SS-arcane-circlesII.abr
decorative circles..abr
Kichibrushes.abr
SS-frost.abr
SS-artistic.abr

**Comment by photopea** [comment]
Could you send me the brushes in a ZIP file to support@photopea.com ?

**Comment by BreezeMadelynn** [comment]
[ABR FILES.zip](https://github.com/photopea/photopea/files/4538711/ABR.FILES.zip)


[ABR FILES 2.zip](https://github.com/photopea/photopea/files/4538689/ABR.FILES.2.zip)

[ABR FILES 3.zip](https://github.com/photopea/photopea/files/4538697/ABR.FILES.3.zip)


I still have other brushes that are over 10MB, should i send this straight to support@photopea.com?

**Comment by photopea** [comment]
I think I fixed it. Could you try it again?

**Comment by BreezeMadelynn** [comment]
yes! it works ! thank you so much <3

**Comment by photopea** [comment]
Thank you very much for helping me fix it :)
