### ISSUE TITLE
Distort->Displace filter doesn't do anything

### ISSUE THREAD

**Issue by samlimster** [photopea/photopea#2088]
Hi folks.

I was trying the Distort-> displace filter on a rasterized layer but when I click the "ok" button, instead of presenting me with a dialog to select the displacement map, nothing happens.

Am I missing something?

Thanks!

Sam.

**Comment by samlimster** [comment]
Hi folks.  I realized that it only works on smart objects so I converted my rasterized image to a smart object. Thank you!

**Comment by photopea** [comment]
Hi, the Distort filter works on any layer, but the distortion map can be only a Smart object.
