### ISSUE TITLE
Site will not stop bothering be about disabling adblocker even though adblocker is disabled

### ISSUE THREAD

**Issue by flleeppyy** [photopea/photopea#2089]
Hi, so this is getting really annoying.
I've disabled all my chrome extensions, but it still pops up saying to turn off my ad blocker.
Now the reason why its probably saying that is because our network admin has Pi-hole installed on our server and it doesn't matter what DNS server we set our computer to go to, it will still go through Pi-Hole. and if i try to ask him to disable Pi-Hole he will say no.

And I have no money to afford premium.

**Comment by photopea** [comment]
Hi, so I guess you can not open this address: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js ?

We really need ads to be able to exist, since almost nobody pays for Premium. It would not be fair to allow certain users get away with blocking ads. Could you explain it to your admin, that this is really important?

**Comment by flleeppyy** [comment]
No I cannot. And if I asked him to remove that from the blocklist he would say no, " its a crucial part of google ads and we need to block it" he would say.

Have you guys considered Patreon as a way to be funded? I'm pretty sure much more people would support you guys, Including me. In my opinon, I don't find premium very eye-catching/noticeable, and it doesn't bother me to go and purchase premium. I really do enjoy your editor, and it really help's me a lot when I can't use Photoshop. I'm pretty sure if you guy's setup a patreon, and setup a patreon button or notice on the home page, many more people would support it.

I do want to support you guys and I do want to allow ads, but I don't think its possible for me to look at ads, that is unless I pay for a VPN or go through a proxy so I can see the ads.

**Comment by photopea** [comment]
Premium costs only 10 USD per 90 days. That is like 3 dollars per month.

**Comment by photopea** [comment]
I don't know what else can I offer you. You would have to do a fight with your admin, and probably get more people on your side. What is the purpose of the admin, if he does the opposite of what users want.

**Comment by flleeppyy** [comment]
I just got done talking with him and he said he'd implement something that would allow ads on photopea.

I will see if I can afford premium either way, cause I do want to support you guys.
