### ISSUE TITLE
Exporting folder with clipping mask layer still renders the empty space where the original image is

### ISSUE THREAD

**Issue by flleeppyy** [photopea/photopea#2090]
Sorry for my rough title.

So I tried to export a folder which has 3 layers, one with a clipping mask, and it rendered the empty space where the rest of the image is, but isint shown because of the clipping mask. I believe that the exporting layer function should just export what can be seen on that layer.

Note the transform on the image layer
![image](https://user-images.githubusercontent.com/18307183/80369347-fa7df800-8842-11ea-82ab-74b5fb7fcff3.png)

Then highlight the layer folder, then I click the download png at the top (next to download svg)

When viewed, the image border is the same size as the original image that is clipped, thus showing empty space where it thinks the actual image is.
![image](https://user-images.githubusercontent.com/18307183/80370005-0e762980-8844-11ea-88f9-8bd59eabf8b5.png)
It should simply render what it can see on that layer.

**Comment by photopea** [comment]
What exactly should your layer look like? Can you disable the clipping mask and show us what it looks like? Photopea should e

**Comment by flleeppyy** [comment]
![image](https://user-images.githubusercontent.com/18307183/80382587-4d61aa80-8857-11ea-8c0e-856576e87f3f.png)

**Comment by flleeppyy** [comment]
this should be what the result image of exporting the folder looks like
![image](https://user-images.githubusercontent.com/18307183/80383870-02e12d80-8859-11ea-87df-c047da2e5990.png)

My workaround for this was to create a new top layer, rasterize it, magic wand the outside, click on the image layer and rasterise it, then delete everything that was outside of the circle. 
but I dont want to have to delete the rest of the image, cause was if i want to come back and change its position or scale later?

**Comment by photopea** [comment]
Sorry, our current export feature exports the whole layer, even if it is a clipping mask.

Try to use a Crop tool to crop it and save with File - Export As - PNG.

**Comment by MichalSZZ** [comment]
All of my 3 tries for workarounds (that works in Photoshop) doesn't work in Photopea:

1. Create smart object from folder and then export [Fail]
2. Click on circle thumbnail in layers pallete for circle selection and make raster mask on folder - then export folder [Fail]
3. Create vector mask on folder with circle shape [Fail, and I will create new Issue with vector mask suggestion]

**Comment by photopea** [comment]
@MichalSZZ  Could you please explain, how do you do steps 1, 2, 3, in Photoshop?

How do you export a smart object or export a folder? How do you export a version with a vector mask on a folder?

**Comment by MichalSZZ** [comment]
Right click on layer or folder and "quick export as PNG".

**Comment by photopea** [comment]
Hi, I fixed it. Now, when you "quick export" any layer or folder, the transparent areas in the output image are "trimmed".
