### ISSUE TITLE
Adjustment layer name : text edition loses focus because shortcuts are not disabled

### ISSUE THREAD

**Issue by jeancallisti** [photopea/photopea#2091]
OS: Windows
Browser : Chrome

**Scenario** : 
1) Create an adjustment layer
2) double click on the name to edit it.
3) Double-click on a word in the name or highlight it by holding the cursor mouse
4) Try to type letter "p" or any letter that acts like a shortcut

Please note : I didn't try to reproduce it just now, so I don'r remember exactly if it is that you have to select a word in the name or by double-clicking or something. But it definitely happens when you select part of the layer's name in a certain way.

**Expected result :** the letter "p" is entered into the layer's name
**Observed result (incorrect) :** the key "p" acts as a shortcut, the layer's name is saved and the layer comes out of edit mode (loses focus).

**Comment by photopea** [comment]
Hi, I am not able to reproduce it. At step 4, I type "p" and it replaces the selected part in the layer name with "p".

Try to update your browser and disable all browser extensions. Let me know if it still happens.

**Comment by jeancallisti** [comment]
The very exact steps are as follow : 
- Double click on the adjustment layer's name to enter edit mode
- Select the text by holding the left mouse button. Do it from right to left. Release the mouse button while you've gone past the left side of the text and are now hovering the layer options (alpha mask or whatnot)
- you will see that the behaviour is not as expected : 
Sometimes the text _exits_ edit mode as soon as you release the mouse (instead of just highlighting the text as it should), as if you had actually _clicked_ instead of just releasing the highlight.
 Sometimes the text _seems_ to be highlighted but it's really not, and while you _believe_ you're typing into the textbox you're really entering application shortcuts.

**Comment by photopea** [comment]
This happens when renaming any layer, not just the adjustment layer.

When you are editing a layer name, and the mouse is released somewhere outside the layer name box, the editing is confirmed and you "escape" the box.

In the current model, we do not track where the click began. So just be more careful when selecting the text.
