### ISSUE TITLE
PHP Warning after payment

### ISSUE THREAD

**Issue by tyronx** [photopea/photopea#2094]
Might want to fix this one: 

```
Notice: Only variables should be passed by reference in /var/www/vhosts/photopea.com/httpdocs/papi/order.php on line 154
Payment complete. You can close this window now.

If you are having any problems, write me an email to support@photopea.com.
```

**Comment by photopea** [comment]
Hi, I think I fixed it. Also, this window should have been closed automatically.

Is your Premium working well? Is there anything else I can help you with?

**Comment by tyronx** [comment]
Seems fine so far 👌

**Comment by tyronx** [comment]
But since you are asking, being able to see the center position when using the background eraser tool at a big radius would be really helpful, otherwise its hard to know where to click :D

**Comment by photopea** [comment]
Sure thing, it is done :)
