### ISSUE TITLE
No document - Merge Channels

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2095]
With no document open you can go to Channels window and select Merge Channels... option in hamburger menu. After OK you get this error:

Uncaught TypeError: Cannot read property 't' of undefined
    at yX.uD (pp.js:8591)
    at tu.aU.G (pp.js:9)
    at tu.tR.G (pp.js:7079)
    at tu.nd (pp.js:7235)

**Comment by photopea** [comment]
I fixed it. The Merge Channels window is not opened, if there is no document opened.
