### ISSUE TITLE
AdBlock Alert Bypass

### ISSUE THREAD

**Issue by Nanoo-web** [photopea/photopea#2098]
I have found a way of bypassing the window.confirm() dialog which pops up every 5 seconds, if Photopea thinks you have an AdBlocker.

This can be done by running this simple script in the Console...
`window.confirm = function() { return false; };`

It basically returns false every time the window.confirm() function is called.

This should be fixed, otherwise people may take advantage.

**Comment by photopea** [comment]
Hi, thanks. We fixed it. This method should not prevent the message now.

**Comment by Nanoo-web** [comment]
That was fast. If I find any more issues, I will report them.
