### ISSUE TITLE
Some settings not appearing

### ISSUE THREAD

**Issue by TheAvGe** [photopea/photopea#2099]
The Lay, Cha, and Pat settings , on the right side, of the rightmost settings column are not appearing. I get this:
![image](https://user-images.githubusercontent.com/64568824/80665860-d6dfcb00-8a57-11ea-95aa-1fd175492b83.png)
When I should get this.
![image](https://user-images.githubusercontent.com/64568824/80665869-df380600-8a57-11ea-809e-906ca5d0797c.png)

PLEASE HELP!

**Comment by photopea** [comment]
Hi, you just closed these windows. You can open them back by clicking Window - Layers, etc.
