### ISSUE TITLE
drag & drop without project

### ISSUE THREAD

**Issue by Studioartcz** [photopea/photopea#21]
Hi,

i try drag & drop some jpeg and all projects all are closed. Browser open just image, without photopea. I was expected that photopea create new project with width, height from this image as photoshop :)

**Comment by photopea** [comment]
Hi, what browser do you use? When you drop a new image, it should be added to the current project as a new layer. I have tested it in Chrome and Firefox.

**Comment by photopea** [comment]
Oh I see, you have closed all the projects and you Drag and Drop a new image. It should be fixed now :)

**Comment by Studioartcz** [comment]
Nice, thanks! And what about some information mesage as in wordpress?
![screenshot from 2016-05-04 14-11-02](https://cloud.githubusercontent.com/assets/3184228/15013831/3cf4ed3a-1202-11e6-8a97-acd34ad7e44e.png)

**Comment by photopea** [comment]
I think we should focus on more important features now.
