### ISSUE TITLE
A couple of ideas for your new logo...

### ISSUE THREAD

**Issue by NatashaDK** [photopea/photopea#210]
Feel free to use any of these 6 logos. They won't cost you anything :-)

![6 new logos](https://user-images.githubusercontent.com/27579710/27253222-c42cd1d6-5370-11e7-9040-15a5c360d1e2.png)

**Comment by photopea** [comment]
Wow, thanks :)  I want to find the right shape first, and we can choose colors / gradients later. I really like the letter P from your first three logos :)

BTW. what do you think about my own logos? http://i.imgur.com/c1FuJhQ.png

**Comment by NatashaDK** [comment]
I'm glad you liked the logos. They are all created in 400x400px size, and I'll send the original Photopea layer files if you want to experiment with different colors etc. Just say the word.

_>>>>>BTW. what do you think about my own logos?<<<<<_
A1 - looks like a moon
A2+A3 - is this an alien?
A4 - this IS the moon  :-)
B1 + B2 + B3 - good
B4 - reminds me about a seawave or a musical node.

-----

But these icons don't have any wow-effect. I believe that most people like gradients, or at least some color. I also know that logos should be reproduceable in both large and very small sizes. That's what makes it difficult to create a goodlooking, and well-functioning logo.

I'm not very good with vector tools, but I might get better now you have implemented it in PP.
Do you have any plans about importing .svg vector files?

Have a nice weekend !

**Comment by photopea** [comment]
Dear Natasha, 

you can import shapes in a CSH format into Photopea, like these: https://www.smashingmagazine.com/2008/12/the-ultimate-collection-of-photoshop-custom-shapes/

SVG files are quite complex, they can have text / bitmaps / CSS styles. But some degree of SVG support is definitely possible! Have a nice weekend too :)

**Comment by NatashaDK** [comment]
Thanx for the info!
