### ISSUE TITLE
Cant set clipboard permission

### ISSUE THREAD

**Issue by Fabian35566666** [photopea/photopea#2100]
![Screenshot_20200430-021718_Chrome](https://user-images.githubusercontent.com/63743282/80674656-e1ff1f00-8a88-11ea-9c63-edb331067251.jpg)
I cant copy and paste. When I try to change permission settings on the site I dont see clipboard permission, only sound

**Comment by photopea** [comment]
Can you update your web browser? Are you using Photopea at www.Photopea.com ?

**Comment by Fabian35566666** [comment]
Its updated, and yes I am. Should I re install it? Im on an android tablet

**Comment by photopea** [comment]
I just tried Photopea in Chrome on my Android phone. When I make a selection and press Edit - Copy, Edit - Paste, it pastes the selected data as a new layer.  Is that what you are doing?

**Comment by Fabian35566666** [comment]
No. When I copy, it doesnt do anything. When i cut, it  "clears"

**Comment by photopea** [comment]
It should not do anything when you copy. It should paste the image when you press Paste.

**Comment by Fabian35566666** [comment]
I know, but it doesnt even register the action in the history, and when i paste, nothing happens. A while ago, i had the same problem, but i could change the permission. I saw the option to do it, now i dont

**Comment by Fabian35566666** [comment]
Ok, now its working. I tried to paste again, and for some reason, it asked me if i give prrmission to use clipboard. I said yes. Im glad, but its weird, it makes me nervous the random of it all. Still , this software is awesome!

**Comment by photopea** [comment]
are you using Photopea at www.Photopea.com ?

**Comment by Fabian35566666** [comment]
Yes im using it there

**Comment by photopea** [comment]
That is weird, I used Photopea for a long time and it always worked exactly as it should.

**Comment by art-doc** [comment]
When I used the photopea.com, I think it asked for permission and I guess I didn't give it then... now I cannot paste after cut.. and also can't give permission again after restarting the chrome. Can you please let me know what to do in this case.

**Comment by photopea** [comment]
@art-doc I guess you are using Google Chrome. Press the padlock icon on the left side of "photopea.com" in your browser, and change the clipboard permissions there.
