### ISSUE TITLE
Oil Paint issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2103]
Reload photopea and open this file.
https://www.photopea.com/#ixQZYwEfp
After you try apply Filter-Stylize-Oil Paint it is not working correctly and does this:
![image](https://user-images.githubusercontent.com/6370548/80837295-d29de400-8bf6-11ea-8f79-8ea268e43f9f.png)

**Comment by photopea** [comment]
Fixed, thanks! :)
