### ISSUE TITLE
ISSUE: photopea can't save my brush and gradient files. 

### ISSUE THREAD

**Issue by BreezeMadelynn** [photopea/photopea#2107]
It says "your browser doesn't allow us to store the files." I cleared all my cookies today and all of my brushes are styles are gone, I tried to add back in and they can't store some of my brushes? The gradient style as well.  It normally works perfectly for me though.

**Comment by photopea** [comment]
Do you mean storing in a Local Storage, so that they are already in Photopea the next time you open Photopea?

It is hard to say what is the problem. Could you disable all your browser extensions?

**Comment by BreezeMadelynn** [comment]
Yeah, but they can't store some of my brushes. I tried to disable all my browser extensions but it doesn't work for me ><

**Comment by photopea** [comment]
Do you already have other resources in your Local Storage? How many MB? You can check it in Edit - Local Storage.

**Comment by BreezeMadelynn** [comment]
i have around 281 mb in my local storage

**Comment by BreezeMadelynn** [comment]
Yeah I did, I just need to open my brushes everytime when I go to Photopea

**Comment by photopea** [comment]
Photopea needs to ask your browser, to allow it to store files in your computer permanently (ABR and others). It is up to your browser to decide, how much can be stored. It seems like in your case, the browser does not allow storing more than 281 MB.

Are you using Google Chrome? I am communicating with people from Google to fix this problem. Until it is fixed, the only thing I can recommend is to delete some files that area already in your local storage.

**Comment by BreezeMadelynn** [comment]
yeah, i'm using google chrome! and i'll try that out later :)

**Comment by photopea** [comment]
We can not do anything about it. The limit for the Local Storage has to be fixed from a browser side.
