### ISSUE TITLE
A dialog box with the list of shortcuts

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#211]
It would be nice to have some window, which would show the list of keyboard shortcuts.

**Comment by wernight** [comment]
Most common shortcut is `?` (i.e. Shift + ? on QWERTY).

Draft of possible content:

 - Ctrl + Space + Drag↔ (or Ctrl + Alt + Wheel) (or Ctrl + [Alt] + Space + Click) ‒ Zoom in/out.
 - Space + Drag ‒ Move around.
 - Ctrl + Drag ‒ Move element.
 - X ‒ Swap foreground/background colors.
 - [ / ] ‒ Changes brush size.
 - { / } ‒ Changes brush softness.
 - Ctrl + E ‒ Merge down current layer.

Note: Most common Photoshop shortcuts should work.

Note: Usually mouse middle = mouse left.

Note: Usually adding Shift to a shortcut is ignored: Shortcut will still work and it allows to bypass some browser shortcuts. For example Ctrl + Alt + [Shift] + T.

**Comment by photopea** [comment]
Hi, I have added the list of shortcuts. It is available after pressing "?". What do you think about it?

**Comment by wernight** [comment]
- Style is good.

 - Ctrl + -/+ for zoom doesn't work generally (they trigger browser zoom). I'd not list them.
 - Quick tools:
    - Space for Hand is missing +Drag
    - Ctrl + Space for zoom is missing Drag↔
    - Consider showing Ctrl+Alt+MouseScroll as alternative zoom
    - Same for Move
 - Consider grouping the increase/decrease brush size shortcuts on one line.

Looking at it, I remember also using frequently the export shortcut (which PP doesn't have). It was something like Ctrl + Alt + Shift + S on PS.

**Comment by photopea** [comment]
I have added details about the zooming and panning, also new shortcuts for Save for Web and Save as PSD.

I think that +Drag is not worth mentioning. It is clear, that once you switch e.g. to the Move tool with Ctrl, you can use it in a regular way (dragging). 

Different shortcuts are allowed in different browsers. Ctrl + -/+ works in my browser. I hope that all that will be fixed in browsers soon, I don't want to mention any browser-specific shortcuts.

**Comment by wernight** [comment]
I tried on Chromebook:

 - Ctrl + Alt + Wheel doesn't work (so may be don't list it).
 - Ctrl + Space + Drag doesn't work, but Space + Ctrl + Drag does, so I'd use that order, even though it's not common order.

**Comment by photopea** [comment]
Chromebook users are a minority of PP users. All these are bugs in Chrome OS. 

I guess we will have to make Photopea OS for Chromebooks, which would have all these problems fixed.

**Comment by wernight** [comment]
Ctrl + Alt has also sometimes weird behaviors on Linux as well (due to Alt). Yes another minor platform. My point is that when/if deciding which shortcuts to recommend and two perform the same action, it's better to recommend the one that will always work. Simply because a user trying a new product and finding stuff not working will simply drop it without looking twice at it.
