### ISSUE TITLE
Getting "you're using adblocker" message when I'm not

### ISSUE THREAD

**Issue by barnu5** [photopea/photopea#2110]
Love this tool, it's become essential. 

I've previously installed the web app locally. Now getting msg saying I need to unblock ads, but I'm not running any adblocker.

**Comment by photopea** [comment]
Hi, can you see ads in Photopea without any problems?

Do you still see a message, if you disable all browser extensions?

**Comment by barnu5** [comment]
Hi @photopea 

Used to be able to see ads OK, now there's just a blank panel.

No browser extensions are running.

**Comment by photopea** [comment]
Do you have any antivirus installed, or other program, which can see and edit your web traffic?

**Comment by barnu5** [comment]
Yep, I’ve got bitdefender. I tried disabling all features except the single
core antivirus protection feature, unfortunately still didn’t work.

**Comment by photopea** [comment]
Can you access this file? https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js

**Comment by barnu5** [comment]
It downloads f.txt file

**Comment by photopea** [comment]
What browser are you using? Are you absolutely sure you have no browser extensions? You can check at chrome://extensions for Chrome.

**Comment by Irazzeval** [comment]
Same problem.
No antivirus (I'm on Linux ;-)
No browser extension active.
I checked the configuration in Chrome and I don't see anything abnormal.
It has been like this for at least a week.

Debian 10 - 64 bit
Chrome 81.0.4044.92 (Official Build) (64-bit)

**Comment by photopea** [comment]
@Irazzeval do you see ads? Can you access https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js ?

**Comment by Irazzeval** [comment]
@photopea
I don't see ads in Photopea and I can't access: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
I'm getting this error message: ERR_CONNECTION_REFUSED

P.S .: Javascript is activated

**Comment by photopea** [comment]
@Irazzeval Can you check, if some program in your computer is blocking some websites for you? The URL above is a regular public URL and it should be accessible from any device connected to the internet.

If nothing helps, then, your internet provider is blocking the websites. You should report it to him or her.

**Comment by Irazzeval** [comment]
@photopea
Recently I have not installed new programs and I know that there are no programs that block ads ... before it worked, now not.
I tried to change the DNS server (from Google to OpenDNS) but nothing.
I tried to change the web browser but nothing.
From the mobile phone the URL: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
is reachable.

**Comment by photopea** [comment]
@Irazzeval is your phone on the same wifi as your computer? Try to connect your phone to the same wifi, to make sure if it is your internet provider.

Also, try Photopea in Incognito mode.

**Comment by Irazzeval** [comment]
In incognito mode:
- https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js is not reachable;
- in photopea no alert, about adblocker, appears but there isn't ads.

In addition, it's no longer able to load files from Google Drive (in local it works).

I have tried all of this, both using a normal gmail account and using a gsuite account.

**Comment by Irazzeval** [comment]
my phone is on the same wifi as computer

**Comment by photopea** [comment]
If the same URL opens on your phone, but not in your computer, while both are on the same WiFi, I think it is a problem in your computer. Some program is monitoring what you do on the web, and blocks some URLs.

**Comment by barnu5** [comment]
For me, the programs I’m using haven’t changed and it was working before.

**Comment by photopea** [comment]
If Photopea works in Incognito, then the problem should be in your browser extensions. 

I think it is very important to know about your browser extensions and what they do (because they correspond to how many companies / creators actually know about everything you do online).

**Comment by barnu5** [comment]
Hi @photopea thanks for being so responsive in this.

Let me confirm the issue happening:

[As per example here, I installed photopea as a PWA](https://cdn.guidingtech.com/imager/assets/2019/12/249109/Install-Uninstall-Pwa-in-Chrome-2_4d470f76dc99e18ad75087b1b8410ea9.png?1576590492)

In Chrome itself I'm not using extensions. However I am installing as a PWA as well. 

You can see in the next screenshot, the blank ad area and the browser popup, which is appearing every 30 to 60 seconds.

![Annotation 2020-05-06 180202](https://user-images.githubusercontent.com/3778403/81150835-ba95de00-8fc3-11ea-89f3-2046ba0288cd.jpg)

**Comment by photopea** [comment]
There are no ads in Photopea on a right side.

Can you try Photopea in Incognito window? Is the message still there?

**Comment by photopea** [comment]
Please, go to chrome://extensions and disable all extensions. Let me know if it helped.

**Comment by barnu5** [comment]
Very strange, I have just restarted the PWA and things are working again! (Never been so pleased to see ads haha :-))

Thanks for all your help and advice working through this one!

I believe the issue can be closed. Thanks for an awesome project.
