### ISSUE TITLE
Color Picker OK button

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2112]
This happened to me several times.
I open Blending Options dialog and from there Color Picker (for example for Stroke color). Color Picker window appears and it is positioned as seen as in screenshot. I select my color and click OK but I choose wrong OK button and it picks color from image underneath and I need to select my color again and click the correct OK button. See screenshot positioning of the dialog window is so confusing that even when I now know about this as it happended to me few times already I still keep clicking sometimes wrong OK button accidentaly.
![image](https://user-images.githubusercontent.com/6370548/81059399-a45b2580-8ed0-11ea-9cf6-2acff071ad8f.png)

**Comment by photopea** [comment]
Do you have any ideas how should we fix it?

I was thinking about blurring all windows behind, like this: https://imgur.com/ZCGiTHx

Or we could put each new window on a different spot. Do you know how should we find a new spot depending e.g. on a previous window? Or should we place windows on random coordinates?

**Comment by hxim** [comment]
> Do you have any ideas how should we fix it?

I am not sure. Easiest way seems to me just change position of window so that only one OK is visible. I mean something like IF (PARENT WINDOW) == "Blending Options" THEN position = top right ELSE position top left.

**Comment by photopea** [comment]
So at the beginning, the first window will be placed at 150,150, the second at 300,300, and so on ...

But most importantly, any window can be dragged, and after closing and opening it again, it will remain at the previous position.
