### ISSUE TITLE
Convert to smart object behaves differently when one layer is visible

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2113]
When converting a buch of layers to a smart object all is fine, but if i set to invisible one layer of the set and then convert to smart object i get the eye color to red.

WHy is this happening?
[Untitled_ May 5 2020 5_02 PM.zip](https://github.com/photopea/photopea/files/4583600/Untitled_.May.5.2020.5_02.PM.zip)
[Logo Marihuana.zip](https://github.com/photopea/photopea/files/4583601/Logo.Marihuana.zip)

**Comment by photopea** [comment]
Hi, I just tried it in Adobe Photoshop and it works absolutely the same. It happens, when such shape is placed into a document with a different size (converting to a Smart Object, cropping a document, etc).

Your eye has a red-white radial gradient, which is aligned to the document, not to a layer (so resizing a document changes the look).

Did you convert it from a PDF file? Can you share the file with me for testing? I will make Photopea create the aligned gradient, which does not change like that.

**Comment by avagp** [comment]
I made the logo all in photopea.
I have shared the PSD with you, it is the Logo_marihuana.zip file

**Comment by photopea** [comment]
Oh, I see. So the eye is a shape with a gradient fill. Could you enable "Align with layer" on that gradient fill? You will also need to change the parameters.

Align all gradients with a layer, when you make them.

**Comment by avagp** [comment]
Yes, that made the trick.

Yesterday i found that option and worked :)

Even though i thought that the behaviour was weird

**Comment by photopea** [comment]
I can easily change that, but it is the way Photoshop handles such layers, so I think it is better to have the same behaviour. So I will close it now :)
