### ISSUE TITLE
Project not saving as PSD

### ISSUE THREAD

**Issue by RasheedAZ** [photopea/photopea#2115]
For some reason, project is not saving as PSD. Saving it for the first time.

Exports fine. Tried as jpg and tiff. 

Tried another project with same steps and that one saves.

The only thing different about the first one (that's not saving) that I remember is that I did not save it as PSD every couple of minutes as I normally do. Instead, I finished the whole thing taking maybe 15 minutes and then tried saving at PSD...

Using Chrome 81.0.4044.129 on Windows 10.

**Comment by photopea** [comment]
Hi, that is really strange. Do you see any error message? Can you disable all browser extensions?

**Comment by RasheedAZ** [comment]
Thanks for replying. No error message - just nothing happens when I press Ctrl + S or select Saves or Save as PSD from menu.

There was only one extension enabled, uBlock Origin, but it is disabled on the Photopea website of course :)

Now I'm going to  uninstall it altogether since I use Chrome for Photopea only anyway.

Will let you know how it goes...

**Comment by photopea** [comment]
So you still have that document opened, and you are trying to save?

If you could describe steps, what to do to produce unsavable document, it would really help us :)

**Comment by RasheedAZ** [comment]
OK I completely uninstalled uBlock extension but it still happens.

No I don't have the original document open but I opened earlier saved psd copies of it and was able to save them in the beginning a few times but not after making a number of changes.

Also, tried to make new documents from scratch and was able to save a few times as psd in the beginning of the work but later on, save as psd stopped working.

**Comment by photopea** [comment]
So you can save all documents now? Let us know when you are not able to save again.

**Comment by RasheedAZ** [comment]
I think it happens when I try to to open and edit saved psds rather than when creating new psds from scratch.

These saved psds were created in Photopea.

**Comment by RasheedAZ** [comment]
Chrome updated to 81.0.4044.138 since my first post but it doesn't seem to have impacted this.

**Comment by photopea** [comment]
Can you try to open a saved PSD?

**Comment by RasheedAZ** [comment]
Yes that happens.

OK this is preliminary but it's looking like the point at which saving at PSD stops is when I add Invert to Smart Filter to a layer that has Drop Shadow effect applied.

![Annotation 2020-05-06 233131](https://user-images.githubusercontent.com/16827461/81172187-e29c3600-8ff1-11ea-9298-889258ccb824.png)

**Comment by RasheedAZ** [comment]
Okay what I said above looks correct. If I undo the Invert, it saves. 

Also instead of applying Invert as smart filter, if I open the smart object and apply invert on it and update it, return to document and save, it saves as PSD :)

**Comment by photopea** [comment]
Wow, that is quite a serious bug! I fixed it. Thank you very much for reporting it :) I think many users had the same problem with saving a PSD, but could not find what caused it. I am really happy that it is solved now.

**Comment by RasheedAZ** [comment]
You're welcome. That's the least we end users should be doing.
