### ISSUE TITLE
Pressure Sensitivity

### ISSUE THREAD

**Issue by rishirajiv** [photopea/photopea#2116]
I am using an XP-Pen Star G640 on Windows 10 on an Inspiron 13 7000. I've tried using the pressure sensitivity so many times. Neither fading out/fading in nor bigger/smaller styles work. The tablet I use supports pressure sensitivity. Please help me.

**Comment by photopea** [comment]
Can you update your tablet drivers? Can you try Photopea in different browsers (Chrome, Firefox ...)? What browser are you using?

**Comment by rishirajiv** [comment]
I updated the tablet drivers. Tried Photopea in Chrome and Edge. Nothing worked. Originally using Chrome.

**Comment by photopea** [comment]
I am afraid we can not do anything about it. The tablet manufacturer should fix it.

I wrote them a tweet. Maybe you could retweet it or something https://twitter.com/photopeacom/status/1258286944372613121 . Maybe they will notice it, when there are enough people complaining.

**Comment by rishirajiv** [comment]
Thank you!
