### ISSUE TITLE
Nelze otevřít .sketch soubory.

### ISSUE THREAD

**Issue by kom1n** [photopea/photopea#212]
Ahoj, dva dny se snažím otevřít .sketch soubory, z verze 43 i 44 a nejde to. Vždy se objeví "načítání" a na tom to stojí klidně i 20minut.

Soubor má jedno plátno, žádné složité efekty.
![snimek obrazovky 2017-06-23 v 14 23 58](https://user-images.githubusercontent.com/25580850/27481969-b4f63ba4-581f-11e7-9b45-982ddd3d258f.png)

**Comment by photopea** [comment]
Ahoj, stačí to hlásit na jednom místě :) Můžete mi to poslat na support@photopea.com ?

**Comment by photopea** [comment]
Fixed.
