### ISSUE TITLE
Advertisement popup interruption 

### ISSUE THREAD

**Issue by StealthRT** [photopea/photopea#2120]
Seems it keeps popping up an OK/Cancel box saying i have ads blocked but you see by the picture the ad is there on the right side. This pops up every 15-20 seconds....
![popup](https://user-images.githubusercontent.com/1037844/81215501-74328600-8fa7-11ea-9d3b-c9d27b467e29.png)

**Comment by photopea** [comment]
Hi, can you open this URL https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js ?

**Comment by StealthRT** [comment]
Seems not to load. However, I am on a work computer.
![errphotopea](https://user-images.githubusercontent.com/1037844/81225829-e3b07180-8fb7-11ea-910e-55fad1d8e4d5.png)
