### ISSUE TITLE
Text Edit

### ISSUE THREAD

**Issue by Romeoabhishek786** [photopea/photopea#2122]
If write any text on pic than we unble to re-edit text and other text layer are not available for that project.

**Comment by photopea** [comment]
Hi, I do not understand. After you make a text layer, you can not edit it? It is hard to believe. Could you record a short video of what you are doing?

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by photopea** [comment]
Hi, I did not receive any explanation of your problem, could you describe it again?

**Comment by Romeoabhishek786** [comment]
Open PHOTOPEA in chrome than add a text layer now you see you wrote wrong
name than try to correct in but you see keyboard not open for thay text

Other thing is your text size is very small (150) please increase it (500)

**Comment by photopea** [comment]
Hi, when I add a text layer, the text layer is empty. Who wrote a wrong name? What name do you mean?

At the top menu, you can change the text size. You can type any number you want.
