### ISSUE TITLE
Working path and vector mask

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2124]
Hi,

1. I can't copy ad paste path from working path to vector layer mask.

- create new layer (with photo e.g.)
- layer -> vector mask -> add (reveal all)
- create shape with "path" mode
- go to path palette
- select path and copy it
- click on vector mask on photo layer
- should to be mask from pasted path

2. Vector mask from path. There is no such functionality in [layer -> vector mask -> new vector mask from current path]

**Comment by photopea** [comment]
Hi Michal, I believe I fixed it. When you add an empty vector mask, drawing with a Path mode will draw into that new vector mask.

I added an option Layer - Vector Mask - Current Path, to create a mask from a current path.

**Comment by MichalSZZ** [comment]
@photopea THX!
Now works great!
