### ISSUE TITLE
Add support for Vector Smart Objects

### ISSUE THREAD

**Issue by bduffany** [photopea/photopea#2125]
When opening & placing an SVG file, it seems to rasterize immediately, preventing lossless resizing.

Example SVG you can use for testing: https://drive.google.com/open?id=1Ql7HOeC24i8VXNm9GfbTBOLZ-_AFNlWh

**Comment by photopea** [comment]
Hi, when you do Open and place, the file is placed as a smart object (one layer). Smart objects are rasterized at their main resolution .

To avoid it, open it as a separate document and duplicate the layers into the main document. You will have multiple vector layers (representing multiple shapes), which will be transformed smoothly.

**Comment by bduffany** [comment]
Excellent, thanks.

I do think it would be a better user experience to allow importing the SVG and rescaling freely, and only rasterize once the user clicks the "Check" mark or something.

**Comment by photopea** [comment]
It would still be very confusing. Imagine you have a SVG of 20x20 pixels with a circle. A circle has a 1 px stroke. You place it into Photopea and resize it to 10x20 pixels. Should the stroke be 1 px on the sides and 2 px at the top and the bottom?

**Comment by bduffany** [comment]
That's an interesting point.

What happens today when you import an SVG by opening it as a new document? When you resize paths that have 1px stroke, is the 1px stroke preserved?

If that's the case, why can't that same resizing behavior be used when using open & place?

I think that when you open & place an SVG, it should behave as though you imported all the SVG layers into one "multi-layered object," which resizes all the layers internally as you scale it.

**Comment by bduffany** [comment]
Or better yet, just import all the SVG elements as layers into a "folder" and automatically select all the items in the folder, so that they can be resized together.

**Comment by bduffany** [comment]
I guess what I am proposing may be difficult to implement, because the current behavior is to import as a smart object, and now we would want SVG-specific behavior (import as folder). Might be worth collecting some metrics to see how many people actually import SVGs using "open and place," because I imagine those people would be very surprised by the current rasterizing behavior.

**Comment by photopea** [comment]
So when you place an SVG Smart Object into Photoshop, it is transformed while re-rendering vector graphics. We should make it work the same way.

**Comment by photopea** [comment]
But Adobe Photoshop can not edit the SVG smart object. 

So once a person edits the SVG smart object in Photopea, we will have to convert it to a PSD (a raster format), and then, it will be scaled in a usual way like any other PSD smart object..

**Comment by photopea** [comment]
Hi, I added the support for vector smart objects. SVG and PDF files will be scaled sharply, when placed into a document.
