### ISSUE TITLE
Publishing to imgur via script

### ISSUE THREAD

**Issue by Mapsama** [photopea/photopea#2126]
Hi,

i could not find any information about publishing a file to imgur by scripts.
Is it possible?

Regards
Mampsama

**Comment by photopea** [comment]
Hi, we do not have such script now. But you can make a script,  that will send you a PNG to the outer environment (saveToOE) and save it to Imgur yourself.

**Comment by Mapsama** [comment]
That would be awesome

**Comment by photopea** [comment]
You can do it right now. See our api at www.Photopea.com/api
