### ISSUE TITLE
Text tool not working properly

### ISSUE THREAD

**Issue by Creepium** [photopea/photopea#2127]
It has been a while it began happenning to me.

a few weeks ago I tried getting some simple text on a simple proyect I was working on, only 3 layers for background, pasted image and the text I was about to insert.

The text tool just got stuck on loading font pop-up on top of the screen and stood there all time the site was open, I tried to use a layer from other proyect and duplicate it on the proyect I was working on but couldn't edit it so I used another image editor to just add text.

Now that I tried to use it a bit ago it was working as supossed but when I want to write the text doesn't appear even if its the top layer, I dont want to waste more time using extra apps or else...

Hope you can fix it, greetings

**Comment by photopea** [comment]
Hi, can you disable all browser extensions and try it again?

**Comment by Creepium** [comment]
Oh yes it actually gets fixed!

Thanks you, now hopefully I remember to turn off and on all my extensions after editing
