### ISSUE TITLE
Disabling anti-aliasing

### ISSUE THREAD

**Issue by Dujma** [photopea/photopea#2129]
Hi, could it be possible for you to add an option to disable anti-aliasing for a specific layer? This is quite useful when working with really small resolutions and small texts for example. Thanks.

EDIT: example attached

![New Project (2)](https://user-images.githubusercontent.com/13941756/81473678-6592db80-9200-11ea-97a7-c6fce41ed9be.png)

**Comment by photopea** [comment]
Hi, in general, a layer is a pixel layer, where each pixel has a specific color (there is no place for antialiasing).

But text layers are rendered automatically from text parameters. So we could allow rendering the text without antialiasing. Is that what you want?

**Comment by Dujma** [comment]
Yes! That’s exactly what I want :) I just generalised the request thinking that it could be beneficial for all types of layers.

Thank you a lot!

**Comment by photopea** [comment]
Hi, I implemented it. When you have a Type tool, and a type layer is selected, you can change the AntiAliasing in the top menu to "None".

**Comment by Dujma** [comment]
Thank you very much! It's even more than I expected. Works great.
