### ISSUE TITLE
Can't export the photos

### ISSUE THREAD

**Issue by catalingraur** [photopea/photopea#2130]
Hello, 
I have an issue with using Photopea. I can't export the edited photos, neither JPG or PSD.
What is causing the issue?

Thanks

**Comment by photopea** [comment]
Hi, can you disable all browser extensions and try it again?

**Comment by catalingraur** [comment]
Yes

**Comment by catalingraur** [comment]
So, I disabled all the browser extensions and I reloaded Photopea, imported a pic, and tried to export it, but nothing.

**Comment by photopea** [comment]
What browser are you using? can you update it?

If you are in Chrome, sometimes, it shows a message somewhere at the top, that multiple files are trying to be downloaded, and it wants your confirmation.

**Comment by catalingraur** [comment]
I'm using Brave, with brave shields off, and I have the latest version, v.1.8.95.

**Comment by catalingraur** [comment]
I don't know how and why, but it started working again. Thanks

**Comment by photopea** [comment]
ok
