### ISSUE TITLE
Interface is too small

### ISSUE THREAD

**Issue by RealJekyll** [photopea/photopea#2131]
All of a sudden, for no apparent reasons, my interface is now very small.  I can hardly see the menu items and the tools. It's like if the screen resolution of my computer had been changed, which it hasn't. Also, around the same time, I can no longer us the text tool. It is there, and when I click the image, the Test Layer appear, but when I type, although the text size and colour should make it visible, nothing shows up on the screen, but in the layers, next to the Text icon I can see the text that should be on the image.  These two problems seem unrelated but they occurred at the same time.

**Comment by photopea** [comment]
Hi, try to reset a browser zoom to 100%. Click the three dots at the top right corner and choose 100%.

If the text tool is not working, try to disable all your browser extensions.

**Comment by photopea** [comment]
I think it should be solved now.
