### ISSUE TITLE
Can't use custom .ttf font

### ISSUE THREAD

**Issue by barnu5** [photopea/photopea#2132]
Hi Photopea!

I can't upload a custom font. Font works OK locally.

Have tried incognito. Font loading process works fine, no errors. However no font available in the list. See attached.

Thanks!

[font.zip](https://github.com/photopea/photopea/files/4613157/font.zip)

**Comment by photopea** [comment]
Hi, I tried your font in Photopea and it works well for me. It will appear at the end of the font list, i.e. not sorted by alphabet like other fonts.

If Photopea works differently in Incognito mode than in normal mode, disable your browser extensions.

**Comment by photopea** [comment]
I think it should be fixed now. But feel free to keep discussing it here.

**Comment by barnu5** [comment]
You rock @photopea
