### ISSUE TITLE
Suggestion: Change Brush Size Dynamically

### ISSUE THREAD

**Issue by isametry** [photopea/photopea#2134]
In Photoshop and Affinity Photo there’s a shortcut to quickly change the brush size visually, with a live preview.

On Mac, you have to hold ctrl + alt + left-click
On PC, it’s alt + right-click 

When you hold these three, a real-size preview of the brush appears, then you can drag horizontally to change brush size, or vertically to change brush hardness.

Photoshop:
![Image-3](https://user-images.githubusercontent.com/46103746/81665154-a9742380-9440-11ea-917d-76ce5d13f89c.gif)

Affinity:
![Image](https://user-images.githubusercontent.com/46103746/81665040-7d58a280-9440-11ea-89c7-4d1ce55e7a45.gif)

This is a very handy feature I’d love to have in Photopea as well. Sorry if it’s already in and I missed it somehow.

**Comment by isametry** [comment]
I figured it out, I was doing the Mac shortcut but didn’t try the Windows one. I’m sorry.

**Comment by photopea** [comment]
Yes, we have this shortcut, too :)
