### ISSUE TITLE
The screen freeze up

### ISSUE THREAD

**Issue by ead0331** [photopea/photopea#2135]
Some times the screen freeze up I can move my mouse and I can't click on anything besides the close, full screen, and hide screen those are the only button I can press. I have been using this software for the whole school year and I had no problems at all. This freezing up is happening on the app because my sister uses it on the website. Please fix it I have a project due Friday.

**Comment by photopea** [comment]
Hi, I do not observe any freezing in Photopea. Can you describe how can we make it freeze?

Please, try these steps: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
