### ISSUE TITLE
the magnetic lasso tool

### ISSUE THREAD

**Issue by ead0331** [photopea/photopea#2136]
Whenever I use the lasso tool and I am about to finish it freeze-up

**Comment by photopea** [comment]
Hi, I just tried to use a magnetic lasso and it does not freeze. Could you record a short video of what exactly you are doing?

The first click of the magnetic lasso usually takes a second or two, or even longer, when you work with large resolution.

**Comment by photopea** [comment]
I will close it because of lack of details.
