### ISSUE TITLE
gif

### ISSUE THREAD

**Issue by soniasoon** [photopea/photopea#2139]
I can't rename layers...

Sonia

**Comment by photopea** [comment]
Can you tell us more? I just tried and it works well for me.

**Comment by soniasoon** [comment]
do we have an account? I double click but everything is stuck

**Comment by photopea** [comment]
Can you disable all browser extensions and try it again?

**Comment by soniasoon** [comment]
Nothing. I was working with Safari 11.1. Now I have open the page with Firefox and now it works

**Comment by photopea** [comment]
Try to update Safari.

**Comment by soniasoon** [comment]
I don't think I can do it. It is a somewhat dated computer. Mac El capitan 10.11.6 ...

**Comment by soniasoon** [comment]
but now in Firefox I can't see your projects well
