### ISSUE TITLE
Escape or Confirm the current action error

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#214]
How to trigger:
1.- Open a project 
2.- Go to Free Transform toll (Ctrl+T)
3.- Scroll up or down with the mouse or mouse pad

What i was expecting to happend:
Nothing, just nothing.

What actually happended:
Photopea display hundreds of warning signs with the following text: "Escape or Confirm the current action error"

After that, it takes a lot of time to wait until every sign disappears, and at the end it stops my working flow.
![screenshot 2017-06-25 at 17 18 49](https://user-images.githubusercontent.com/11801254/27519824-5f090b2a-59ca-11e7-837b-7e8f07a2562c.png)

BTW, change the pea.psd so reflects the new logo :P

**Comment by photopea** [comment]
Hi, 
it was fixed :)  Thanks for reporting it!  BTW. I think nobody ever opens pea.psd :D
