### ISSUE TITLE
Layer Order Detecting Incorrectly  

### ISSUE THREAD

**Issue by Blessyourself** [photopea/photopea#2140]
Whenever I go to move or change the size of an image, it will sometimes suddenly change the current layer I was editing on and abruptly move the image on another separate layer that I didn't want to move or resize.

**Comment by photopea** [comment]
Hi, are you using the Move tool? Did you enable the "Auto-select" option at the top menu?

Also, the layers can be reordered by pressing Ctrl + [  or  ] . Maybe that is what you did?

**Comment by Blessyourself** [comment]
Oh gosh, I did have the "Auto-select" option turned on, and yes that was it. Thank you again!

**Comment by photopea** [comment]
The Auto-select can be very useful, as long as you know that it is or is not enabled :)
