### ISSUE TITLE
Eraser

### ISSUE THREAD

**Issue by TasEz** [photopea/photopea#2142]
Hello
Please fix the eraser .. The eraser line is transparent. can you make it a bit darker?
Because the eraser always hiding and can't use it.
This is photo for example
https://i.top4top.io/p_15954myrg1.png 
_______________________________________________
Also we wish to add magical eraser so can delete the background easily... Hope to get any respond from you 👍

**Comment by photopea** [comment]
Hi, what exactly is wrong with the eraser? You can see the circle of the brush.

There is a background eraser right below the eraser tool.

**Comment by photopea** [comment]
I have to close it because of lack of details.
