### ISSUE TITLE
Color Fonts Glyph color is inverted

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2143]
Color of glyphs for color fonts in Glyphs window is inverted:
https://blog.photopea.com/color-fonts-in-photopea.html
![image](https://user-images.githubusercontent.com/6370548/82017068-98b2f000-9682-11ea-80f5-fe0581a1e920.png)

**Comment by photopea** [comment]
Hi, the glyphs image was displayed the same way as other icons are displayed - black color on a transparent background. Then, it is up to the current theme and the CSS to invert it or not.

I changed it, so now, it is always a black color on a white background, and the theme does not modify it.
