### ISSUE TITLE
Png files not working

### ISSUE THREAD

**Issue by Hander04** [photopea/photopea#2144]
Whenever I try to add a png file I can see the grid backround.

**Comment by photopea** [comment]
Hi, your PNG is probably semi-transparent. What background would you like to see instead?

**Comment by MichalSZZ** [comment]
I think there is a different problem here. In google images, when you are looking for transparent img of something I see many web services who give thumbnails in google with transparency grid. User thing "wow that si exacly what I was searching for" and copy image directly from google. The file extension is PNG byt there isn't any transprency. Just fake visualisation of transparency grid.

**Comment by photopea** [comment]
@MichalSZZ I agree, I once spent an hour explaining a lady on Facebook, why she can not replace the backgorund in her JPG, even though it had a "transparency grid". It was not even a PNG, it was a JPG.
