### ISSUE TITLE
Using brushes make the app really slow

### ISSUE THREAD

**Issue by fusionPT** [photopea/photopea#2145]
Using brushes makes the app go slow. The more time you use them the slower it gets.
Tested on chrome with WebGL enabled.

**Comment by photopea** [comment]
Hi, could you tell us more? I just tried to use brushes and they work well.

Do you have any specific settings of brushes? Could you describe any instructions, which lead to brushes being slow?

**Comment by fusionPT** [comment]
Hi, I believe it's when you start tweaking the parameters like Tip Dynamics, Scatter, etc
![image](https://user-images.githubusercontent.com/393198/82113956-ffefa380-9759-11ea-8d85-cff27bdd72cc.png)

I'm on a 2019 Macbook Pro.

I'm attaching a small recording.
https://www.dropbox.com/s/1nbgbhowd0qslxo/photopea-brushes.mp4?dl=0

**Comment by photopea** [comment]
Hi, I think I improved the performance. Could you try it again?

**Comment by photopea** [comment]
I will close it for now, but feel free to keep discussing it :) But I think the new speedup should fix your issues.

**Comment by fusionPT** [comment]
It does look faster. Thanks for the quick turnaround. Keep up the good work!
