### ISSUE TITLE
Text tool for Chinese/Japanese/Korea user

### ISSUE THREAD

**Issue by eszerfrm** [photopea/photopea#2146]
Dear developers,
this is really a nice tool,
I like this very much,
but I found that I can't change text directions from parallel to vertical...

**Comment by photopea** [comment]
Hi, we have only a Horizontal text tool at the moment. It is hard to tell, how many people would use such vertical text tool. But is it a big problem, if you write it horizontally?

**Comment by photopea** [comment]
I will close it, as I think this is too hard to make, and there are not that many people who need it.
