### ISSUE TITLE
A red box appeared oddly and doesn't allow me to move stuff and when exported to png it doesn't appear

### ISSUE THREAD

**Issue by wolf653** [photopea/photopea#2147]
![Screenshot 2020-05-17 at 9 32 54 PM](https://user-images.githubusercontent.com/29867428/82166296-04b17600-9886-11ea-9df8-9bdbf15041c9.png)

**Comment by photopea** [comment]
Hi, you entered a quick mask mode. Press Q to escape it. Look here to learn more: https://www.photopea.com/learn/selections
