### ISSUE TITLE
Delete new line in Firefox

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2148]
Use Mozilla Firefox browser.
Select Type Tool and start editing some multi line text.
When you go with cursor to end of line and press Delete key on keyboard it does not delete "line break" and does nothing. It is working fine in Google Chrome browser.

**Comment by photopea** [comment]
Hi, this is a bug in Firefox, I reported it to them here: https://jsfiddle.net/k3osx980/1/ . It should be fixed once Firefox is fixed.

**Comment by photopea** [comment]
I managed to fix it! It should work now.
