### ISSUE TITLE
hey this isnt an "Issue" so much as a "Suggestion" for photopea...

### ISSUE THREAD

**Issue by EDDYDUELS** [photopea/photopea#2149]
what i would like to say as my humble "Suggestion" is that i know you have themes already. but what about custom themes? let me elaborate. Custom themes would open up a world of possibilities for the whole "Look" of photopea. just simply put a file prompt and a (hopefully cuz idk coding that much) little bit of coding later and you got custom themes! (if you accept my "Suggestion")
Thanks!
-EDDYDUELS

**Comment by photopea** [comment]
Hi, we have five themes under More - Theme - ...  , or do you mean allowing the user create his own theme?

**Comment by photopea** [comment]
I will close it because of lack of details.

**Comment by EDDYDUELS** [comment]
create own theme, sorry i'm so late.
