### ISSUE TITLE
Clicking and dragging support on XP-Pen StarG640 drawing tablet

### ISSUE THREAD

**Issue by TylerDKnight** [photopea/photopea#2150]
When using a drawing tablet in photopea, layers in the layer panel can't be clicked and dragged around using the pen. Not sure where else this problem extends to.

**Comment by photopea** [comment]
Hi, and when you have many layers, does it scroll the Layers panel, when you drag layers in it?

**Comment by TylerDKnight** [comment]
Yeah, it does!

**Comment by photopea** [comment]
and what if you click the layer with a pen and hold it for a while, can you drag the layer then?

**Comment by photopea** [comment]
This is quite a complex task. When the user drags inside a Layers panel on a touchscreen, it is hard to tell, if he wants to scroll, or to reorder layers. I don't know how should we fix it.
