### ISSUE TITLE
Script Error editing Smart-Object

### ISSUE THREAD

**Issue by Mapsama** [photopea/photopea#2151]
Hi,

i have a problem. i wrote a script editing a text-layer in a smart object.
I'm testing it on api-playground.
it stucks and throws an error the first time i execute it.
if i close the smart object-tab and execute the same script again, it works like a charm

my code:
`function changeText(sobj, val){
  var l = app.activeDocument.layers.getByName(sobj);
  app.activeDocument.activeLayer = l;
  executeAction(stringIDToTypeID('placedLayerEditContents'));
  var l1 = app.activeDocument.layers.getByName(sobj);
  alert(l1.textItem.contents); //working
  l1.textItem.contents = val; //not working
  app.activeDocument.save(); //not working
  app.activeDocument.close(); //not working
}

changeText('Name', 'Examplevalue');`

any sugestions why? i think because it executes the 'l1.textItem.contents'-part before loading the fonts. possible?

Best regards

**Comment by photopea** [comment]
Hi, could you share also a PSD, on which you run it? BTW have you tried to run your script in Adobe Photoshop?

**Comment by Mapsama** [comment]
Hi, thanks for the fast reply.
No, i have not tested it on photoshop because i dont own it.

My json-config on playground:

{
    "files": [ 
        "https://botify.store/tests/test.psd"
    ],
    "resources": [ 
        "https://botify.store/tests/KALINGA.TTF"
    ],
    "environment": {
        
    }
}


my script:
function changeText(sobj, val){
var l = app.activeDocument.layers.getByName(sobj);
app.activeDocument.activeLayer = l;
executeAction(stringIDToTypeID('placedLayerEditContents'));
var l1 = app.activeDocument.layers.getByName(sobj);
alert(l1.textItem.contents);
l1.textItem.contents = val;
app.activeDocument.save();
app.activeDocument.close();
}

changeText('Adresse', 'ausstellungsdtm');

**Comment by hxim** [comment]
@Mapsama 
I think you are using ArialMT font inside Smart Object and Photopea tries to replace this unknown font with LiberationSans font during executing script and it causes error. Add ArialMT font to resources or change font to some font which is already loaded and it will work also first time.
![obrazek](https://user-images.githubusercontent.com/6370548/82346134-6264d000-99f6-11ea-84a9-cc2b7be590ad.png)

**Comment by Mapsama** [comment]
@hxim thanks for you reply, i changed the font now to KALINGA and updated the psd file on the server, but it's still not working. Any other suggestions?

Regards

**Comment by hxim** [comment]
@Mapsama 
Hmm you are right it still show this error:
```
Uncaught TypeError: sP.DqU is not a function
    at new sP.jl (pp.js:6733)
    at new sP (pp.js:6688)
    at Z.R$.Mw (pp.js:4225)
    at sL.Mw (pp.js:10155)
    at sL.cZ.i (pp.js:9)
    at sL.ta.i (pp.js:7129)
    at Object.ty.ac.DpE (pp.js:7023)
    at Function.ty.eval (pp.js:6942)
    at Function.ty.eval (pp.js:6932)
    at Function.ty.eval (pp.js:6927)
```

it seems to work only after you open and close Smart Object so as a workaround you can maybe call script to do that in the beggining like this:
```
{
"files": [
"https://botify.store/tests/test.psd"
],
"resources": [
"https://botify.store/tests/KALINGA.TTF"
],
"environment": {

},
"script": "app.activeDocument.activeLayer=app.activeDocument.layers.getByName('Adresse1');executeAction(stringIDToTypeID('placedLayerEditContents'));app.activeDocument.close();"
}
```

**Comment by Mapsama** [comment]
Thanks again, the problem is, that i wanted to open the script by visiting only the URL. if i add my code to your code you've posted, it doesnt work anymore :(

**Comment by photopea** [comment]
Hi, I fixed it, it should work well now :)

**Comment by Mapsama** [comment]
Awesome, thanks a lot :)

**Comment by Mapsama** [comment]
Now the save-request doesnt work anymore.
i get the error message:
pp.js:9978 Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.zS.JHE (pp.js:9978)

by visiting:
https://www.photopea.com/#{"files":["https://botify.store/tests/test.psd"],"resources":["https://botify.store/tests/KALINGA.TTF"],"server":[1,"//botify.store/img/index.php?id=testid",["jpg"]],"script":"function changeText(sobj, val){var l = app.activeDocument.layers.getByName(sobj);app.activeDocument.activeLayer = l;executeAction(stringIDToTypeID('placedLayerEditContents'));var l1 = app.activeDocument.layers.getByName(sobj);l1.textItem.contents = val;app.activeDocument.save();app.activeDocument.close();}changeText('Adresse1', 'HerrASD'); app.activeDocument.save('jpg');"}

:(

**Comment by photopea** [comment]
You should write your scripts according to a documentation. If you look at the scripting documentation: https://www.adobe.com/content/dam/acom/en/devnet/photoshop/pdfs/photoshop-cc-javascript-ref-2019.pdf , the Document.save() does not have any parameters (while you use app.activeDocument.save('jpg'); ).

If you want Photopea to send the document as JPG to your server, you should specify the "server" property according to our API: www.Photopea.com/api . The "server" value should be an object, but in your example, it is an array, which is wrong. 

    "server":[1,"//botify.store/img/index.php?id=testid",["jpg"]]

**Comment by matiq83** [comment]
I get the error message: 
pp.js:15995 
 Uncaught TypeError: Cannot read properties of undefined (reading 'Idnt')
 
 let sobj = 'samplelayer';
 let val = 'sampletext';
 let l = app.activeDocument.layerSets[0].layers.getByName(sobj);
 app.activeDocument.activeLayer = l;
 executeAction(stringIDToTypeID('placedLayerEditContents'));
 let l1 = app.activeDocument.layers.getByName(sobj);
 l1.textItem.contents = val;
 app.activeDocument.save();
 app.activeDocument.close();
