### ISSUE TITLE
Brushes delay

### ISSUE THREAD

**Issue by fusionPT** [photopea/photopea#2153]
Brushes have some delay when you are drawing (specially noticeable using a Wacom) that makes it complicated to use.

**Comment by photopea** [comment]
Hi, we updated our Brush engine recently, which was supposed to speed it up.

Could you specify, what is the size of your brush, and whether it changes with a pen pressure?

**Comment by fusionPT** [comment]
I think it is just sometimes that there a slight stagger and delay, but it's probably due to the ads displaying on the browser.

**Comment by photopea** [comment]
The ads should not slow down Photopea. Is it only when the ads are changing maybe? Also, does the brush size change according to a pen pressure?

**Comment by fusionPT** [comment]
I think it's when they are loading, yes. It's not something really very noticeable but when you are drawing the slightest delay influences. Not a huge deal though.

**Comment by photopea** [comment]
Ok I will close it now.
