### ISSUE TITLE
Will not let me copy and paste area with lasso tool

### ISSUE THREAD

**Issue by snaccerpaccerz** [photopea/photopea#2154]
It won't let me copy and paste an area in photopea using the lasso tool. Maybe I'm doing it wrong and you guys could show me how to do it but I don't know. Here is video of me doing it: https://drive.google.com/file/d/13yyC5AQCPou2yP0GUTUQk5-vil8WJ_Gf/view

**Comment by photopea** [comment]
Hi, from the video, it is not clear, when do you press the Copy. But during the whole time, the active layer seems to be empty, so yo are copying (and then pasting) an empty area.

You probably want to copy from the bottom-most layer, so you should click it in the layers panel. You can learn how to use layers here: https://www.photopea.com/learn/layers

**Comment by photopea** [comment]
I think it is solved now.
