### ISSUE TITLE
Font scale not functioning properly

### ISSUE THREAD

**Issue by bdbossmovemaker** [photopea/photopea#2155]
When I try to scale the font it is not working properly at all and not moving when I scale it. I move the scale over and it doesn't do anything

**Comment by photopea** [comment]
Hi, how do you scale the font? What do you mean by "moving the scale over"?

You can increase the size of text by changing the Size parameter at the top, or by using the Free Transform.

**Comment by photopea** [comment]
I will close it because of lack of details.
