### ISSUE TITLE
Layer Effects scaling

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2156]
Sometime I need to scale object that have Layer Styles (Effects) on it. 
For example:
I have Circle 400x400px, with stroke 16px, and drop shadow with size 20px.
When I use Free Transform on that layer to scale to 50x50px I will have huge stroke and shadow.

In photoshop I can use Scale Effects feature only for layer effects that I need. 
I can change that when I click with right mouse button on "effect" in layers pallete. Then I need to calculate or remember %  of transform that I made on layer ;)

BTW. In Image -> Image Size in Photoshop there is an option for scaling effects with Image.
I don't see that feature in Photopea - but I see that styles are scales automaticaly (and that is correct for 99,99% of users)

**Comment by photopea** [comment]
Yes, we already have the mechanism for scaling the Effects (it is used in Image - Image Size). So the hard part is to figure out, when the user wants to use it, and when not.

We can add the same option (right-click layer effects - Scale Effects) to scale all effects of a layer. Would it be enough? Do you also need a way to scale just one of effects?

**Comment by MichalSZZ** [comment]
Scaling all effects will be be enough fo me :)
Now I Can try it only in PS CC2015 and there it works with all efects.

Thank you!

**Comment by photopea** [comment]
I added this option. Right-click a layer, Layer Style - Scale Effects, or right-click the "eff" icon on the right side of the layer.

**Comment by MichalSZZ** [comment]
thx!
