### ISSUE TITLE
Support for anamorphic 2:1 pixels

### ISSUE THREAD

**Issue by og2t** [photopea/photopea#2157]
I'd like to propose supporting 2:1 pixel ratio in order to create pixel art for retro computers (such as Commodore 64).

This can be quickly "hacked" by adding CSS `transform: scale(2, 1)` to the canvas but I'd love to have this option (as Photoshop does it).

<img width="1680" alt="Screenshot 2020-05-20 at 17 14 22" src="https://user-images.githubusercontent.com/28712/82463654-614aa600-9abd-11ea-966d-78c449e094ae.png">

**Comment by photopea** [comment]
Hi, that is interesting. What if you worked with "normal" images instead, and we made a filter, which would replace every two horizontal pixels with the average of their colors?

**Comment by og2t** [comment]
Thanks for considering! The point would be NOT to average the pixel color values actually, i.e. each pixel has to be stretched to have 2:1 (instead of 1:1 ratio) without averaging (check the screenshot in full res).

Perhaps a 2:1/1:1 toggle would be enough?

**Comment by photopea** [comment]
We would also need rulers (View - Rulers), where one measure is 2x larger than another one. We would need custom rendering of selections and masks.

When someone draws a square 100 x 100 pixels, do we have to draw it as 50x100 pixels, or the rectangle 100x100 is not a square in this case?

What if Photopea just converted each such pixel into 2x1 pixels, and you kept working with it as witn an image with square pixels?

Do you want to create such images, edit them, or just view them?

**Comment by photopea** [comment]
I think this would be too complex to make, and there are not that many people who need it.

I recommend the following: after opening such image, press Image - Image Size, and scale the image with a Nearest Neighbour interpolation.

Once you are done editing, scale it back the same way to the original size, with a Bilinear interpolation.

**Comment by tomek29k** [comment]
Makes sense. Thanks.
