### ISSUE TITLE
Missing Psds

### ISSUE THREAD

**Issue by go-paulistic** [photopea/photopea#2158]
when i go to open a psd file from my phone to apply to a photo it doesn't appear at all. i have dowloaded the psd and it shows in my files but when i open my files on photopea the psd isnt there. ive tried searching for it and even downloading multiple other psds but none of them show up in my files on photopea.
![Screenshot_20200520-191824_My Files](https://user-images.githubusercontent.com/51185534/82507092-5bf65700-9acf-11ea-9a03-4f722af72463.jpg)
![Screenshot_20200520-191837_Files](https://user-images.githubusercontent.com/51185534/82507093-5bf65700-9acf-11ea-903c-214d99ea3d54.jpg)
![Screenshot_20200520-191842_Files](https://user-images.githubusercontent.com/51185534/82507095-5c8eed80-9acf-11ea-97b8-462b7129a7c9.jpg)
the first screenshot shows the files on my phone of the psd i had downloaded. the two other photos is my files from photopea and the psd are not there.

**Comment by photopea** [comment]
I think the files in your first screenshot could be PSDs. But it is hard to tell, because the extension is not visible. 

If you really downloaded a file into a phone, and it is not there, I think it is a defect of a phone, and you should complain to the person who sold that phone to you.

**Comment by photopea** [comment]
Do you have a manual for your phone? Is there something about PSD files? Photopea works well in my phone, but I think I have a different phone.

**Comment by go-paulistic** [comment]
the files are psds. i have used the same psds from the same person that makes for a long time. and i have used the psds on this phone before. this is a fairly new phone (ive only had it for a few months) its nothing wrong with the phone. the files show up everywhere else. and ALL of my other files show up but the psds do not. 

i dont know what you mean by a manual but there is nothing wrong with the psds because i have used a couple of them by the person just a week ago. photopea was at one point picking and choosing which psds showed up and now none of them are showing up.

**Comment by photopea** [comment]
So what exactly is a problem? You can not find a PSD in your phone, or you select a PSD in your phone and Photopea does not open it?

**Comment by go-paulistic** [comment]
the issue is that the psd doesnt even show up when i try to find it through
photopea. when i click "open from my computer" or "open" the files dont
show up at all. even though i know i have them downloaded and i have
checked to make sure they are correct. it started doing this to a few of my
psd files a couple of weeks ago but now its doing it to all of them. all my
other files work but my psds dont show up at all when i try to find them on
photopea. i can access them through anywhere else but photopea

**Comment by photopea** [comment]
Interesting. Can you send me one of these PSDs to support@photopea.com ?

**Comment by go-paulistic** [comment]
apparently i cant. my bad for the misunderstanding my files are not working
properly at all now? i apoloize for the inconvenience it was not photopea.

**Comment by photopea** [comment]
Maybe you have a virus in your phone or something. Or some "cleaner" program, which deletes files in Downloads folder, as it thinks you will not need these files.
