### ISSUE TITLE
Allow aspect ratio restriction when cropping

### ISSUE THREAD

**Issue by wernight** [photopea/photopea#216]
Like Google Photos has an aspect restriction, and Photoshop, when cropping. Please include that.

Note: When the current image is of the same aspect ratio as the desired ratio, one can:

 1. Crop tool
 2. Total content
 3. Shift + Drag corner

Google Photos has a drop down like:
![image](https://user-images.githubusercontent.com/145667/27627601-b6dd670a-5bec-11e7-929c-d56e6fb38598.png)

Photoshop has similar:
![image](https://user-images.githubusercontent.com/145667/27627660-df12f91a-5bec-11e7-894f-85fb2590cf18.png)

**Comment by photopea** [comment]
I think it is not intuitive in Photoshop. Once you choose a specific aspect ratio, you can not enter exact dimension.

Notice, that it is almost impossible to crop images by a specific ratio. E.g. if you set the ratio 3:2 and resize the rectangle to be e.g. 100 px wide, the height should be 66.666.. px, so it is rounded to 67 px and the ratio is 100:67, not 3:2.  

Image - Canvas size allows you to set a specific canvas size and preserve some ratio.

**Comment by wernight** [comment]
Yes Canvas Size can, using basic math, but it's quite hard to work with when you want to zoom in some area with a specific ratio and decide what to include of your image. Say for example that you've a picture and want to create a 16:9 YouTube thumbnail out of the most interesting area of it.

**Comment by photopea** [comment]
I guess you are right. So it relates to the Crop tool, or any other tool?

**Comment by wernight** [comment]
I'd say only the crop tool.

**Comment by photopea** [comment]
Ok, I added the menu of predefined ratios, which are preserved while resizing the cropping rectangle.
