### ISSUE TITLE
Right-click on a layer does not work on a MacOS touchpad

### ISSUE THREAD

**Issue by melkamar** [photopea/photopea#2162]
When using Photopea on a Macbook (in Chrome) I noticed that it does not handle right-clicks. Using an external mouse works fine. But I couldn't figure out a way to do a right-click with the touchpad. The usual macos way is either control-click or clicking with two fingers. Neither work to bring up the right-click menu.

**Comment by photopea** [comment]
Hi, are you using the latest Mac OS? If not, could you please update it? Do you know, if right-clicking worked for you in Photopea before?

**Comment by MichalSZZ** [comment]
I have Macbook Pro and for me, clicking with two fingers on touchpad works fine in FF and Chrome. I have same menu as when I click with right mouse button.

**Comment by photopea** [comment]
I think updating your OS should fix it.
