### ISSUE TITLE
Canvas resizing 

### ISSUE THREAD

**Issue by narcolepticinsomniac** [photopea/photopea#2163]
Do you make the canvas teeny tiny because it's completely unresponsive? Even with how unnecessarily small it is, you can't open the extra left side bar column with cutting off the sides of the canvas with no way to access them.

The canvas needs to resize dynamically. If there's lots of room, it should fill it. If it's crowded, it should shrink dynamically while maintaining its aspect ratio

**Comment by photopea** [comment]
Hi, I am afraid I dont know what you mean. Photopea looks well and is comfortable to use in my case. Could you maybe show us a screenshot?

**Comment by narcolepticinsomniac** [comment]
I mean the canvas is unresponsive, and does not resize dynamically. Why is it so small by default, when there's still plenty of room on either side. Why, when both side bar columns are closed, does it not get bigger? Why, when both are open, does it cut off the sides of the image, instead of shrinking down to the largest width available, while maintaining its aspect ratio?

Red dots in corners to [demo](https://streamable.com/szf49i).

**Comment by MichalSZZ** [comment]
In Photoshop it works exacly in same way as in Photopea. Zoom size don't change with or without hiding panels.

**Comment by photopea** [comment]
The area on the right side: There should be ads, and you are probably hiding them. To use Photopea without ads, you can get a Premium account for 10 USD for 3 months.

The behaviour of the document area is correct. The document is always displayed at a certain zoom (e.g. 200%) and the zoom should not change, when you resize the editor.

You can change the zoom with a Zoom tool, or by using Alt + mousewheel. When zoomed in, you can move to other parts of the image with a Hand tool. It is all described here: https://www.photopea.com/learn/navigation

Also, press View - Fit the area, to switch to a largest zoom, at which the document is still fully visible.

**Comment by photopea** [comment]
You can have an image 10,000x10,000 pixels, and you zoomed in, to change only 3 specific pixels. But then, you just expand a panel on the right, and the document "shrinks", and you have no idea where are those pixels that you just changed :D that would be really stupid.

**Comment by narcolepticinsomniac** [comment]
>you are probably hiding them

The wasted space is there regardless, so that's kinda irrelevant.

>you have no idea where are these 3 pixels that you just changed :D that would be really stupid

Hopefully you're not looking for any pixels on the sides of the image, because not only are they cut off, you can't even scroll to them. 

I would think if the canvas was not zoomed, it would resize properly, but maybe cutting off parts of the canvas with no way to access them, or leaving it super tiny when there's plenty of room is the way to go.

**Comment by photopea** [comment]
Again, the document is always at a certain zoom. The zoom is chosen automatically when you open a document (to fit the area), but then, it can be changed only manually. 

If some parts of the document are not visible, you can move them with a Hand tool, or just scroll the document with a mousewheel (Ctrl+wheel to scroll horizontally). You cal also scroll on most of touchpads by using two fingers.

**Comment by narcolepticinsomniac** [comment]
>to fit the area

Exactly. So why wouldn't it continue to adjust like that to fit the area unless the user resizes it? It's not like I'm getting the impression that I'm gonna change your mind here, but you're not gonna convince me that if it's a good idea to fit the area by default, that doesn't continue being a good idea until the user resizes it themselves.

**Comment by photopea** [comment]
You are right. When the user resizes the editor, we dont know, if he wants to change the zoom of the document, or not (to make it fit the working area).

But in other editors, the zoom never changes automatically like that. And I think that is what 90% of users expect, as they are used to it this way.

**Comment by narcolepticinsomniac** [comment]
>I think that is what 90% of users expect

You would know. I'm no graphics designer, just basic stuff in GIMP. IME, these types of programs are kinda clunky and scrollbar heavy by design. I suppose I expected a more responsive design in a web app, but if you're shooting for emulating a familiar environment, then no, they are not that, so I guess you're nailing it.

**Comment by photopea** [comment]
I think that Gimp works the same.

**Comment by narcolepticinsomniac** [comment]
I wouldn't argue with that. Though there's way more room, and I've never seen any scenario where I couldn't at least scroll to any area. I expected a more responsive design inside a browser, that's all. If 90% of your users expect otherwise, then it doesn't matter much what I expected. =)

**Comment by photopea** [comment]
What do you mean by responsive? I think Photopea is responsive as it is now.

**Comment by narcolepticinsomniac** [comment]
>What do you mean by responsive?

>you're not gonna convince me that if it's a good idea to fit the area by default, that doesn't continue being a good idea until the user resizes it themselves.

>When the user resizes the editor, we dont know,

You'd set a cookie, or local storage, or any other way you currently store user prefs. This seems pointless, but if you keep asking what I mean, I'll keep telling you.

**Comment by photopea** [comment]
I think this way it is more responsive than what you suggest.

**Comment by narcolepticinsomniac** [comment]
Right on, man. Agree to disagree. I lost this argument an hour ago. I'll get over it. =)

**Comment by photopea** [comment]
I am sure, that if you use Photopea for a while, you will understand, that it is more practical the way it works now. We can not make it work in 150 ways simultaneously. We have to make it work in one specific way. That is why I recommend to read our manual at www.Photopea.com/learn

**Comment by narcolepticinsomniac** [comment]
> you will understand, that it is more practical the way it works now

>you're not gonna convince me that if it's a good idea to fit the area by default, that doesn't continue being a good idea until the user resizes it themselves.

I could do this all day.

Not really though. I gotta take off. I do appreciate you taking the time though, so thanks.

**Comment by christianbearslyclark** [comment]
I do understand this question / comment / opinion.  

The right side empty panel should be for layers, history, paths, etc as the canvas space should be more, as Adobe Photoshop, Affinity, GIMP and Krita. 

That space should be filled up with Photopea. 

I mean...the BEST app that could take over the spot of Adobe Photoshop !  I do really LOVE Photopea. I have WAITED a long time for this. I have Photoshop, Affinity Photo for Windows 10....... and ... , GIMP and Krita for Linux ...but .. nothing as close as Photopea for Ubuntu Users. Totally Awesome !

![Screenshot from 2020-05-22 22-23-00](https://user-images.githubusercontent.com/11014645/82722543-a49f4300-9c7c-11ea-94dc-5d9df445b2f1.png)

**Comment by MichalSZZ** [comment]
@christianbearslyclark but on the right side should be the ads (120x600 banner e.g.). It is the main source of income for the authors of Photopea.
I think that you even couldn't know that you adblocker (addon in browser, browser functionality or some software on your internet acces point) blocked the ads. And then empty space is strange for user.
You have ability to use free program and watch the advertisment or pay for premium account to hide it.
I dont need this extra space on the right, but I have already bought 3-4 times  3 month premium account as a thanks for the author.

**Comment by christianbearslyclark** [comment]
> @christianbearslyclark but on the right side should be the ads (120x600 banner e.g.). It is the main source of income for the authors of Photopea.
> I think that you even couldn't know that your adblocker (addon in browser, browser functionality or some software on your internet acces point) blocked the ads. And then empty space is strange for user.
> You have ability to use free program and watch the advertisment or pay for premium account to hide it.
> I dont need this extra space on the right, but I have already bought 3-4 times 3 month premium account as a thanks for the author.

..so ....the premium version will take away that right side panel then ?
