### ISSUE TITLE
How to save ? 

### ISSUE THREAD

**Issue by christianbearslyclark** [photopea/photopea#2164]
How to save after doing changes to PSD ? Photopea keeps on to replace the PSD file when I want to save. 

The save feature does not work.

**Comment by photopea** [comment]
Hi, it depends on browser settings. Are you using Chrome? Try this: https://support.google.com/chrome/answer/95759?co=GENIE.Platform%3DDesktop&hl=en

**Comment by christianbearslyclark** [comment]
> Hi, it depends on browser settings. Are you using Chrome? Try this: https://support.google.com/chrome/answer/95759?co=GENIE.Platform%3DDesktop&hl=en

I know how to save LOL

..... the save feature of Photopea is disabled. Photopea will only "save as".

**Comment by christianbearslyclark** [comment]
> Hi, it depends on browser settings. Are you using Chrome? Try this: https://support.google.com/chrome/answer/95759?co=GENIE.Platform%3DDesktop&hl=en

No ....... Photopea does not save changes the Photoshop does.

When I do make changes to a PSD file, it will save as another file, instead of the original PSD file. That's the issue.

**Comment by photopea** [comment]
You can change your browser settings to make the browser ask you, if you want to replace the original file.

**Comment by christianbearslyclark** [comment]
> You can change your browser settings to make the browser ask you, if you want to replace the original file.

Yeah. I do know about this tho.

**Comment by photopea** [comment]
I will close it now.
