### ISSUE TITLE
right side panel with ads /  premium version ?

### ISSUE THREAD

**Issue by christianbearslyclark** [photopea/photopea#2165]
... IF I go for the premium, will the Empty right side space may be filled by the tools and the canvas will be space out then ?  As with the premium version ?

![Screenshot from 2020-05-23 00-46-56](https://user-images.githubusercontent.com/11014645/82725024-f9e45000-9c8e-11ea-92a9-8ae81ed72af1.png)

**Comment by photopea** [comment]
Hi, these two photos show a difference between a free and a Premium version: https://twitter.com/photopeacom/status/1157159576204013568

**Comment by christianbearslyclark** [comment]
> Hi, these two photos show a difference between a free and a Premium version: https://twitter.com/photopeacom/status/1157159576204013568

YES !  That's what I wanted to know !

What does it means 60 steps in history with Premium version ?

The Save feature does not work. I think it's disabled or something.  It will just "Save As", instead of Save. You know what I mean ?

**Comment by photopea** [comment]
The 60 steps in history means, that you can do a step back 60 times.

Please, see here how to save files: https://www.photopea.com/learn/opening-saving

**Comment by christianbearslyclark** [comment]
> The 60 steps in history means, that you can do a step back 60 times.
> 
> Please, see here how to save files: https://www.photopea.com/learn/opening-saving
--------------------------------------------------------------------------------------------------------------------

I don now, Understand the Save part.

As you have on your website, stating that "When a document was opened from your device, the File - Save option will not work (Photopea is just a website, and it can not rewrite files in your device). You have to use File - Save as PSD instead. But if you opened your file from Google Drive, or as a Smart Object, or from a server (using the API), File - Save will save your file to a correct destination".

I was Very Hoping that "Save After Changes" would work.

I gonna wait for the Premium version until you may have "Save After Changes". I do a lot of changes and a lot of savings on one original PSD. 

You have one truly Awesome thing that you have. I have waited a long time for something as Photopea, for Windows and Linux.  Very Good start :)

Keep on Updating for me to totally like it  !

Thanks !
