### ISSUE TITLE
Please troubleshoot the Lasso Selection tool

### ISSUE THREAD

**Issue by EditorialUser** [photopea/photopea#2166]
The Lasso Selection tool is once again having issues and not working; this is the second time I am contacting about this.  If someone could please look into it, I would highly appreciate it; thank you.

**Comment by photopea** [comment]
Hi, I can not observe any issues with the Lasso tool. Could you be more specific? Or record a short video of what is happening?

**Comment by EditorialUser** [comment]
The Lasso Select and the Polygonal Select work fine; yesterday, the Magnetic Lasso Select was freezing up and stalling the program, but it is now working normally.  Thank you for your promptness!

**Comment by photopea** [comment]
What is the size of your document? Magnetic lasso can be slow on large photos (many millions of pixels).
