### ISSUE TITLE
Opacity slider doesn't handle mouseup correctly

### ISSUE THREAD

**Issue by bduffany** [photopea/photopea#2168]
If I drag the opacity slider from left to right, and mouseup inside an Ad, the mouseup event is not handled properly and the opacity keeps changing as I move my mouse, even though I'm not holding down the left mouse button.

**Comment by photopea** [comment]
Sadly, we can not detect releasing the mouse on an ad, since the ad is technically a different website :(

You need to be careful where you release your mouse. You can also hide ads by getting a Premium account.

**Comment by bduffany** [comment]
I was bored, so I tried seeing if there is a way to work around this problem. You are right; it is not easy to detect mouseup on ads.

Here is the solution I came up with: https://codepen.io/bduffs/pen/MWaxRqo

**Comment by photopea** [comment]
That is interesting. However, I am afraid it is against the rules to manipulate the ad in this way.

**Comment by bduffany** [comment]
Good point... Google probably doesn't want people touching the iframe elements and might even have some code in place that checks whether they are manipulated.

I updated the code so that it doesn't manipulate the ads at all. Instead it applies a full page scrim whose only purpose is to capture the mouseup event. It hides itself when it receives the mouseup.
