### ISSUE TITLE
Make it work offline using service workers

### ISSUE THREAD

**Issue by wernight** [photopea/photopea#217]
Using some JS one can create a progressive web app which means that PP could work offline. I wrote a tutorial at https://beroux.com/english/articles/progressive-web-apps/ which hopefully explains how to do that simply.

That would means that stuff like "export to drive" would be disabled while offline, but one could go to photopea.com (if he/she went there before) even without internet.

Another benefit is that PP would load significantly faster, and once the mobile version works, it can automatically offer people to add an "app-like" icon on their home screen.

I didn't look if that would also allow to mark the PP Chrome App as working offline.

**Comment by photopea** [comment]
I think that trying to make offline Photopea is a bad idea.

When Photopea is online, you always use the latest version. If it was offline, there would have to be some system for updates, which would interrupt the user.
Photopea has a database of 250 MB of fonts, which are loaded when they are needed. Copying this database into each users drive is a waste of space.
Since PP has properly set the caching parameters, it should load very fast. Do you have problems with a loading time?
In general, I am afraid that managing the offline version would require quite a lot of effort, and we don't have resources for it.

**Comment by wernight** [comment]
Let me address some concerns here:

- **Updates** can be done transparently: i.e. when connected you always get the latest version if so desired. It's literally a choice when using service-workers. This affects load time of course but again it's completely optional.
- You may choose to disable whatever features while offline, but for **fonts** it'd may be best to cache used fonts when using them online (that's simple), and pre-cache some popular fonts (also simple)

I suggest you check it out and ask me if you've any question. I think it's a lot simpler than you think, especially using **sw-toolbox**.

**Comment by photopea** [comment]
But I think, that out of all the people, who are by the computer right now, only about 2% of these people don't have the internet. And that number will drop in the future.

We may add it in the feature , but I think there are more important things we should focus at right now.

**Comment by wernight** [comment]
Desktop or more likely a laptop. I agree that it may be secondary right now, unless a large portion of users considering PP prefer an alternative because they are scared of the offline scenario (I know some people like that). The difficulty with that is that's hard to even show a survey to *new users* to validate. In any case, why not leave it open with a lower priority if you feel there is something more urgent.

**Comment by photopea** [comment]
To me, making PP work offline sounds like making PP work in Internet Explorer 6. It is a waste of time from a long-time perspective.

And another thing, Photopea makes money through ads, which don't work offline. Also, it will not be possible to verify, if a person has Premium or not. The offline version interferes with the current way things work.
