### ISSUE TITLE
text not working at all

### ISSUE THREAD

**Issue by murphy271096** [photopea/photopea#2170]
when I try to use the text it gives me the option to place and scale but when I go to type it wont show in the photo im working on, it shows on the right hand side with the layers that it is but not on the picture plz help as im new to this.

note...I used it a few days ago and it was working fine.

**Comment by photopea** [comment]
Hi, try to disable all your browser extensions. Let me know if it helped.

**Comment by murphy271096** [comment]
> Hi, try to disable all your browser extensions. Let me know if it helped.

its still not working unfortunately

**Comment by photopea** [comment]
Can you update your web browser? What browser and version do you use?

**Comment by murphy271096** [comment]
ive went and downloaded chrome and it seems to be working now, thanks

**Comment by Ziyaf** [comment]
text not working, not in chrome too. I am using firefox, but tried on chrome

**Comment by photopea** [comment]
@Ziyaf have you tried to disable all browser extensions? If yes, what version of a browser are you using?

**Comment by photopea** [comment]
I will close it because of lack of details.
