### ISSUE TITLE
Export brush?

### ISSUE THREAD

**Issue by nathgit** [photopea/photopea#2172]
I know you can import brushes in .abr format, but is it possible to export a brush created in photopea as an abr?

**Comment by photopea** [comment]
Hi, sure, it is described at the end of this article: https://www.photopea.com/learn/brush-tools

**Comment by photopea** [comment]
You can right-click any brush in a gallery and delete it.

**Comment by nathgit** [comment]
I know you can It's just time-consuming if you have a lot of brushes.

**Comment by photopea** [comment]
We don't have any simpler solution at the moment :(

**Comment by nathgit** [comment]
I didn't figure there was. I appreciate the quick response.
