### ISSUE TITLE
Cannot save as a PSD or export as a PNG

### ISSUE THREAD

**Issue by Squig99** [photopea/photopea#2173]
Tested on 2 different laptops, one with a registered account and one without one. Both were unable to save or export any of the work done. We appreciate any help or assistance you can give us

**Comment by photopea** [comment]
Hi, is it still a problem? Why did you close the issue?

Logging in does not have any influence on the functionality. Have you looked into the Downloads folder? Can you try to disable all browser extensions and try it again?

**Comment by Squig99** [comment]
Hey! Sorry about the previous email. The problem was solved. Apparently the
problem was only on “Freephototool.com” And not on “Photopia.com” so I used
“Photopia.com” instead. I think they’re both on your domain anyways. But
thank you for getting back to me! Your website is amazing and has helped me
with various projects countless times <3

Regardless, thank you for the speedy response!

**Comment by photopea** [comment]
Wow, that is quite a serious problem. I think it is broken since the latest Chrome update from two days ago. It still works well in Firefox.
