### ISSUE TITLE
COMMAND PANEL DISAPPEARED

### ISSUE THREAD

**Issue by catalingraur** [photopea/photopea#2175]
Hello,
I was  doing some editing with Photopea, and after I pressed some buttons (idk which) my command panel (left) and right panel disappeared. What should I do?

**Comment by catalingraur** [comment]
I closed the browser and started Photopea again. Somehow it worked. Thanks, anymway!

**Comment by photopea** [comment]
Hi, you probably switched to a different view using Tab. You can switch back by pressing Tab again. Try it in Photopea to see what it does :)
