### ISSUE TITLE
Allow rotating the view

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#2176]
Now, the document can be moved (Hand tool) and zoomed (zoom tool) but it would be nice to allow rotating it (only the view, not the image data).

**Comment by spartacruz** [comment]
I am very exited with this feature!

It makes me more easy to do some task rather than rotating my monitor......

**Comment by photopea** [comment]
Implemented! :)

**Comment by spartacruz** [comment]
> Implemented! :)

How to do that? Could you please direct me to the documentation? @photopea

**Comment by photopea** [comment]
It is possible with a Rotate View tool :) I just wrote a description here: https://www.photopea.com/learn/navigation
