### ISSUE TITLE
Copy Paste not working

### ISSUE THREAD

**Issue by yanbaha** [photopea/photopea#2179]
When using "selection tools" to select an area and copy it. Nothing is copied nor pasted.
Hope you are going to fix it.

**Comment by photopea** [comment]
Hi, did it work for you before? Can you disable all browser extensions, allow the clipboard and try it again?

**Comment by dentistformyeye** [comment]
Yanbaha, check to make sure you have the correct layer active when you copy. You might accidentally be copying the transparent portion of a layer even though you see the opaque pixels of another layer.

**Comment by yanbaha** [comment]
the problem is in my browser. Thanks for your answer.
