### ISSUE TITLE
Unable to save transparent image

### ISSUE THREAD

**Issue by nitvik** [photopea/photopea#218]
Unable to save transparent image.

If you have a layer in PSD which is image and a transparent one, when you save the image, the white and black squares in the background also come and hence transparency is not maintained.

**Comment by photopea** [comment]
Hi, the white and black squares are just in the preview, they will not be present in a final image.

Can you save your transparent image and then send that file to support@photopea.com , so we can have a proof?

**Comment by photopea** [comment]
Since there is no response, I am going to assume, that it is solved.
