### ISSUE TITLE
See-through pixels when merging text and shapes

### ISSUE THREAD

**Issue by Cauyote** [photopea/photopea#2181]
So I was making some things, experimenting with what I can do with  the online application when the pixels started to become transparent. Is there anyway to solve this? All I did was put the letter "C" in with in a circle then put a line through it with the line tool and it started to glitch out.

**Comment by photopea** [comment]
Hi, did you type any numbers? If you start typing numbers, it will modify the opacity of the current layer.

You can set the opacity back to 100% in the Layers panel. See here: https://www.photopea.com/learn/layers

**Comment by photopea** [comment]
I have to close it because of lack of details.
