### ISSUE TITLE
Keyboard Shortcuts window with Mac alternatives

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2182]
Hi, 
Is there an option, to automaticaly show Mac OS alternatives for Keyboard Shortcuts window?
When user use Windows, he will be see Ctrl and Alt. After Photopea recognize Mac OS - it can be change to:

Alt - ⌥ (option)
Ctrl - ⌘ (command)

(I know how to read shortcuts becouse I'm win-mac user, but I have one student who don't know it)

![keyboard-shortcuts-macOS](https://user-images.githubusercontent.com/38118273/83388241-675e5200-a3ee-11ea-9b78-524d0daa14bc.png)

**Comment by MichalSZZ** [comment]
I see that I forgot about Shift as ⇧

**Comment by photopea** [comment]
Since the Mac users are in the minority, dont they know right away, that Ctrl corresponds to Command? Do you think Apple could switch to normal keyboards, if programs like Photopea and thers don't mention their keys?

**Comment by MichalSZZ** [comment]
That was only a sugestion for you :) if it will be easly to implement.
You know... Apple users think they aren't in the minority ;)

Apple make it own standards and I think that they don't think about switching to other keys naming ;)

If automatical changes will be trouble - maybe some radio button in Shortucts window:
PC (default selected) Apple (to switch)

**Comment by MichalSZZ** [comment]
I see now, that OS automaticaly (?) changes all shortcuts hints in any (?) application on my system.

<img width="361" alt="obraz" src="https://user-images.githubusercontent.com/38118273/83402127-78b35880-a406-11ea-8bf6-f10b7a7e4627.png">

I haven't thought about it before but now I think that sould work in same way in photopea - becouse that might to be the first place where (not advanced) mac users could see PC shortcuts

**Comment by photopea** [comment]
Ok, I implemented it :)

**Comment by MichalSZZ** [comment]
thx! very fast as always!
