### ISSUE TITLE
Error saving Smart-Object with Smartfilters

### ISSUE THREAD

**Issue by Mapsama** [photopea/photopea#2183]
Hi,

i found a bug where you cant edit a Smart-Object and save it if there is applied a filter.
Steps to reproduce:
1) Open Photopea, load by URL: https://botify.store/tests/Sample.psd
2) Open the smart-object named "SAMPLE", edit the text-layer value
3) Save the smart-object

in console you can see the following log:
TypeError: a.LghD is undefinedpp.js:6007:59
    Ui https://www.photopea.com/code/pp.js:6007
    Jy https://www.photopea.com/code/pp.js:6165
    Cx https://www.photopea.com/code/pp.js:6160
    P$ https://www.photopea.com/code/pp.js:5467
    kc https://www.photopea.com/code/pp.js:5493
    i2 https://www.photopea.com/code/pp.js:5347
    i2 https://www.photopea.com/code/pp.js:10220
    k https://www.photopea.com/code/pp.js:9
    k https://www.photopea.com/code/pp.js:7216
    VK https://www.photopea.com/code/pp.js:10249
    k https://www.photopea.com/code/pp.js:9
    k https://www.photopea.com/code/pp.js:7216
    k https://www.photopea.com/code/pp.js:7216
    k https://www.photopea.com/code/pp.js:7216
    l0 https://www.photopea.com/code/pp.js:7237
    <anonym> self-hosted:875

is there any solution? anyone got the same problem?

Regards
Mapsama

**Comment by photopea** [comment]
Hi, the problem was, that Photopea thought the Box Blur filter is an Oil Paint filter, and when it tried to re-apply it, it crashed.

I fixed the problem. Thanks for reporting it :)
