### ISSUE TITLE
Can't Open Saved PSD in Photoshop

### ISSUE THREAD

**Issue by Oldcat9** [photopea/photopea#2185]
Hi, I have used Photopea to convert sketch and xd files to psd.
I've had no issue loading the files inside Photopea and saving them, but most of the psd files I got would not open in Photoshop. Here is the error message I keep getting :

" File is not compatible with this version of photoshop " 

Do you have a solution?

Thanks

**Comment by photopea** [comment]
Hi, I just tried to convert several XD and Sketch files to PSD, but they all worked in Photoshop :(

Could you send me some of your problematic files to support@photopea.com ? By the way, do you try them in Photoshop on Windows or on Mac?

**Comment by Oldcat9** [comment]
Hi, I first tried on my Mac at work and then on my own Windows PC. The result was the same sadly.

**Comment by Oldcat9** [comment]
But I found a solution, the size of my canvas was over 30 000px and PSD files only support 30 000 x 30 000 anything over that is saved as a PSB file when using Photoshop. So I had to reduce the size of my canvas to 30 000px using Photopea before being able to open them in photoshop, where they were then saved correctly as PSBs after resizing the canvas.

**Comment by Oldcat9** [comment]
It would be cool if Photopea could directly save those huge files as PSBs. I exhausted every option before thinking about that fix.

**Comment by photopea** [comment]
Wow, I did not realize, that somebody could work with Sketch or XD files, which result into a PSD larger than 30 000 pixels. Now, if it happens, Photopea will offer you to scale down the document.

We could store documents as PSB, too, but I think it is a very rarely needed feature.

**Comment by photopea** [comment]
Photopea can save files in the PSB format now: https://twitter.com/photopeacom/status/1349770822211268613
