### ISSUE TITLE
Missing keyboard shortcuts

### ISSUE THREAD

**Issue by basaric** [photopea/photopea#2186]
No keyboard shortcut for 'New Project'. Preferably I'd also like to have a shortcut for creating a new project with the size of the photo I have in clipboard, if not creating a new project already containing that image. 

With the current state of thing, I need to click 'new project' button on the splash screen and then 'create' button on the new project screen and then paste. I want to eliminate extra clicks and have ctrl + n to create a new project, or something similar.

**Comment by photopea** [comment]
Actually, there is Ctrl+N to start a new project. 

Currently, many browsers open a new window at Ctrl+N, and don't even tell the website, that Ctrl+N was pressed. But maybe the browsers will allow us to detect Ctrl+N in the future. Developing Photopea is a constant fight with browser developers.

If you "install" Photopea (More - Install Photopea) in a "PWA mode", Ctrl+N works.
