### ISSUE TITLE
Fullscreen not scaling

### ISSUE THREAD

**Issue by TurnipianFlux** [photopea/photopea#2187]
So I recently got photopea on Chrome OS, but for some reason which I have been unable to find a response, the scaling of the fullscreen on both the website and the app which is broken and highly annoying.

**Comment by photopea** [comment]
Hi, what do you mean by "scaling of the fullscreen"? Do you have a screenshot or something?

**Comment by TurnipianFlux** [comment]
![Screenshot 2020-06-05 at 10 32 35](https://user-images.githubusercontent.com/66398311/83823730-f97c9800-a717-11ea-8d06-b6344f27eb62.png)
here is a screenshot, not entirely sure if it works...

**Comment by photopea** [comment]
Hi, I see your screenshot. What exactly is wrong?

There should be ads on the right side. You are probably blocking them with ad blocker. Is that what you mean?

**Comment by TurnipianFlux** [comment]
> 
> 
> Hi, I see your screenshot. What exactly is wrong?
> 
> There should be ads on the right side. You are probably blocking them with ad blocker. Is that what you mean?
yes that is what i meant, i didn't know and it just kinda gave me bad vibes.

**Comment by photopea** [comment]
You can pay for a Premium account to hide the ads (or the empty space in your case). It costs 10 USD for 3 months.
