### ISSUE TITLE
opening image from google drive 

### ISSUE THREAD

**Issue by BahneGork** [photopea/photopea#2188]
i have connected the app to my google drive, i have logged into the app with google. 
opening the file from drive "open with.." results in "Error: user_logget_out" ??

**Comment by photopea** [comment]
That is very stragne. Did you allow Photopea to access your Google Drive? There should be a popup window when you open a file in Photopea this way for the first time.

**Comment by piamedea** [comment]
I'm also getting an error message, though i get a different message and it was working at first I was open one image and edit it but then when i tried to open other images I got the error that youy see in the screenshot I've attached. 
![photopea-not-opening-from-drive](https://user-images.githubusercontent.com/66444411/83811979-99321b80-a66f-11ea-9cd9-81164cd683b8.JPG)

**Comment by photopea** [comment]
Can you try it with all browser extensions disabled?

**Comment by photopea** [comment]
I think it was because of browser extensions.

**Comment by BahneGork** [comment]
> i have connected the app to my google drive, i have logged into the app with google.
> opening the file from drive "open with.." results in "Error: user_logget_out" ??
I think i fixed it with "who has this link" rights

**Comment by seethahere** [comment]
Came here looking for a solution to the exact same issue as the OP. Thanks guy for the tips - it was indeed a browser extension issue - Privacy Badger was causing this. Disabled it on Photopea site and its all good now. Thought i should let others know.
