### ISSUE TITLE
Keyboard shortcuts carry over when holding command key on Mac

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2191]
This bug involves layer duplication on Mac.

Steps to reproduce:
1. Open an image in Photopea.
2. Hold down the command key.
3. Tap J, but don't let go of the command key.
4. Tap I, but don't let go of the command key.
5. Tap S.

Expected result:
Step 3 duplicates the layer. Step 4 inverts the colors of the new layer. Step 5 opens the save dialog.

Actual result:
Step 3 duplicates the layer (as normal). Step 4 duplicates the new layer. Step 5 duplicates the newest layer, then opens the Save dialog.

Additional notes:
Letting go of the command key in between steps is a workaround.
I've tested this with and without Chrome browser extensions on. I've only tested step 3 with the J key, but steps 4 and 5 can use virtually any letter keys (step 5 can change behavior depending on step 4).
Example of what I mean by change behavior:
4a. Tap the K key instead of the I key. The layer duplicates (incorrect behavior) and the Photopea Preferences dialog pops up. Keep holding the command key.
5a. Tap the O key. The layer duplicates (incorrect behavior) and the Open dialog opens up. Keep holding the command key.
6a. Close the Open dialog and tap the I key. Because the Open dialog in 5a (and the Save dialog in 5) is a system dialog rather than a Photopea dialog, Photopea forgets about the command key and switches to the eyedropper tool. This is correct behavior.

If I try steps 1-4 on Windows (holding the control key, since there's no command key), I get different results: If I wait a bit after step 3, step 4 inverts the new layer from step 3 instead of duplicating. If I perform steps 3 and 4 in very quick succession, step 4 duplicates the new layer from step 3 and inverts that newest layer.

**Comment by dentistformyeye** [comment]
Separate bug involving the Desaturate shortcut on Mac:
1. Open an image in Photopea.
2. Press command-shift-U and let go of U key, but keep holding shift and command.
3. After a second passes, let go of the shift key. Letting go of the command key is optional.

Expected result:
Image becomes desaturated.

Actual result: Image becomes desaturated. The Photopea Hue/Saturation dialog pops up and affects the desaturated image (pressing cancel doesn't cancel the desaturation).

Workarounds:
A. In step 2, after pressing command-shift-U, let go of all three keys immediately instead of waiting.
B. In step 2, use the Image > Adjustments > Desaturate option in the menu instead of the keyboard short cut.

Additional notes:
The keyboard shortcut for Hue/Saturation is command-U.
I've tested this bug with and without Chrome extensions on.
This bug doesn't happen on Windows (using the control key instead of the command key).

**Comment by photopea** [comment]
Hi, this is a known bug in Mac OS  https://stackoverflow.com/questions/27380018/when-cmd-key-is-kept-pressed-keyup-is-not-triggered-for-any-other-key

I have reported it to Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1510209

I think only Apple can fix it. You can ask Apple to fix it, or switch to a different OS :/

**Comment by dentistformyeye** [comment]
Thank you for the quick response and the links to information. I also greatly appreciate that Photopea allows Mac users to use the control key to perform command key functions.
