### ISSUE TITLE
Desaturate image adjustment doesn't work properly on smart objects

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2192]
This bug involves the Desaturation image adjustment. I've tested this on Mac (command key) and Windows (control key).

Steps to reproduce:
1. Open a color image in Photopea.
2. Convert the image to a Smart Object.
3. Desaturate the image using either Image > Adjustments > Desaturate or the command-shift-U keyboard shortcut.
4. Invert the image using Image > Adjustments > Invert or the command-I keyboard shortcut.
5. Press command-Z or use the History panel to return to the Desaturate state.

Expected result:
Step 3 desaturates the image, Desaturate shows up in the History panel, and Desaturate shows up as a Smart Filter under the Smart object.
Step 4 inverts the desaturated image, Invert shows up in the History panel, and Invert shows up as a Smart Filter under the Smart object.
Step 5 returns to the desaturated image state from before the color inversion.

Actual result:
Step 3 desaturates the image and Desaturate shows up in the History panel, but the Smart Object doesn't show any Smart Filters.
Step 4 overrides the desaturation (because there's no Smart Filter for Desaturate) and inverts the color version of the image (incorrect behavior) as if the desaturation had never happened. Invert shows up under Desaturate (correct behavior) in the History panel.
Step 5 now shows the color version of the image instead of the desaturated image (incorrect behavior) as if the desaturation had never happened.

Alternate expected result (undesirable, but mimics Photoshop behavior if I recall correctly):
Disallow using Image Adjustments on Smart Objects.

Additional notes:
I have tested this with and without Chrome extensions on.
Photoshop doesn't allow Image Adjustments to be used on Smart Objects, but Photopea does. In addition, Desaturate is an instant adjustment with no options, unlike other Image Adjustments, which have dialog boxes.

**Comment by photopea** [comment]
Hi, I fixed it in a "photoshop way". Desaturation is not applicable to Smart Objects now.
