### ISSUE TITLE
Error with File Info

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2197]
1. Open this psd file: https://www.photopea.com/#i6VvxQOTH
2. Go to File-File Info...
3. Press "===SAVE===" button in that dialog
4. In main menu press File - Save as PSD
5. Error appears in console and nothing is saved
->
Uncaught e

**Comment by photopea** [comment]
That is really strange. The problem is probably with some default file info parameters.

Could you describe simple steps about how to produce such unsavable PSD?

**Comment by hxim** [comment]
> Could you describe simple steps about how to produce such unsavable PSD?

Yes, I produced this PSD exactly like this:
1.) Reload photopea and open New Project (New Project - Create)
2.) In menu go to File-File Info...
3.) Press "Add Parameter" button many times so it adds all possible parameters
4.) Press "===SAVE===" button
5.) Close File Info dialog
6.) In menu go to File-Save as PSD

**Comment by photopea** [comment]
I think I fixed it. Thanks! :)
