### ISSUE TITLE
Advanced Blending

### ISSUE THREAD

**Issue by inv1sium** [photopea/photopea#2198]
Hi, I am aware that this issue had been opened and closed 2 years ago, but I thought that maybe you could get over it now. What I request is advanced blending options, which is already in Photoshop. I have come across situations where I needed advanced blending several times, it would be very useful for me -and probably for the community- if you added this.

**Comment by photopea** [comment]
We already have a Blend If option :)

**Comment by inv1sium** [comment]
Yes, there is a Blend If option, I am asking if the option to select RGB channels (to do glitch effects) is possible or not.

**Comment by photopea** [comment]
Are you following any specific tutorial? Maybe it could be done without the advanced blending.

**Comment by inv1sium** [comment]
I have looked at dozens of tutorials trying to find one without using channels, unfortunately every one of them were using it. If there was a way to do it as effectively without channels, I would take it.

**Comment by photopea** [comment]
Can you show me one of such tutorials?

**Comment by inv1sium** [comment]
youtu.be/TIz3dOI3gh0 My point starts at 2:00.

**Comment by MichalSZZ** [comment]
On black background, try to make one layer with text in Red color, duplicate this layer and change color of the text to Green, one more copy of text layer and change again color of new text layer to Blue. For all of these layers change layer blending mode (it is from the left of opacity) to screen (it will simulate RGB color space on channels).
Move RED layer 10px to the left. 
Baaaang! You got it
Ctrl + A, 
Edit->copy merged
Ctrl + V
and make next steps from tutorial.
https://www.photopea.com/#it1wrmVoL

**Comment by inv1sium** [comment]
This works finely with grayscale photos when you change the color balance as well! Thank you so much, this solution is the one. I will not close this issue, if, the developer wants to add something.

**Comment by photopea** [comment]
Hi, I added the option to enable / disable the Red, Green and Blue channels of the layer.

![image (1)](https://user-images.githubusercontent.com/15955558/83978380-61450580-a907-11ea-85f9-cd7b761655ea.png)

I think it looks nicer when you move the blue channel, too: https://www.photopea.com/#iIVCzlNQp

**Comment by photopea** [comment]
The same "technique" can be applied not only to the text, but to any image data :)

![New Project](https://user-images.githubusercontent.com/15955558/83978741-d3b6e500-a909-11ea-8c6f-5f3f7537506e.gif)

**Comment by MichalSZZ** [comment]
> The same "technique" can be applied not only to the text, but to any image data :)
 
@photopea Earlier I did it using a little trick by clicking with ctrl on channel Red for channel red selection -> then new empty layer and filled with #ff0000, and same things with two others channels. Then blending mode to screen. 
Now it is easier. Thank You.

I used it to say something about CMYK to my students (how colors are blending when something is printed) https://youtu.be/Q16MJKJpiPg?t=204
White background and layers in multiply blend mode.

**Comment by rome4ya2** [comment]
@photopea  Is there an alternative for the 'Advanced Blending' option of 'Blend Interior Effects as Group'?
![PS-ADVANCED BLENDING](https://user-images.githubusercontent.com/94921412/213949813-9f6f397d-1ff1-4b7a-a633-1453911ec5a8.png)

**Comment by grimAgent** [comment]
> The same "technique" can be applied not only to the text, but to any image data :)
> 
> ![New Project](https://user-images.githubusercontent.com/15955558/83978741-d3b6e500-a909-11ea-8c6f-5f3f7537506e.gif)

Hey! I know this is a long shot, but is there any way you could explain (at least high level) how does the advanced blending by channel works in code? I'm trying to replicate the same effect with a library called [sharp](https://github.com/lovell/sharp) and can't really get to this. (I need to automate this on a server, otherwise I'd use Photopea :D )

**Comment by photopea** [comment]
@grimAgent you just set the red/green/blue values to zero.
