### ISSUE TITLE
Font in SVG replaced with DejaVuSans

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2199]
I used font "Actor" and saved as SVG. When I reopened the SVG it was replaced with DejaVuSans font for no reason (this font is available in photopea).
Showing
`Alert: "Actor" ➡ DejaVuSans`
in console
See screenshots:
before:
![image](https://user-images.githubusercontent.com/6370548/83964745-4e9ee200-a8af-11ea-892a-452f8ea2d3f7.png)
after saving as SVG and reopening:
![image](https://user-images.githubusercontent.com/6370548/83964752-5f4f5800-a8af-11ea-9130-4964d09d0bd8.png)

**Comment by photopea** [comment]
Hi, we use a "postscript name" to identify the font in a PSD file. However, the CSS in SVG does not have any method for specifying the font exactly.

Now, Photopea saves the SVG text with a postscript name as a font-family value. You should be albe to save and open the SVG without losing the font information.

The postscript name of your font is "Actor-Regular" and it is not clear, if other SVG viewers will render it correctly, even if such font is installed on a device.

**Comment by hxim** [comment]
Hello I have one more issue with this.
When I export as SVG with for example "Open Sans" font it will write in SVG
`font-family: "OpenSans-Regular"`
and is recognized as Open Sans font in Photopea but not in a browser / other software.
When it is the opposite - I have SVG from other software or generate it in my plugin with
`font-family: "Open Sans"`
it will be displayed as Open Sans in browser but it will not be recognized as Open Sans in Photopea.
Is it possible to change this function in some way so it can show same Open Sans font in both Photopea and in browser?
I tried to specify both like this
`font-family: "OpenSans-Regular", "Open Sans"`
but it is not recognized in Photopea either :(
`Alert: OpenSans-Regular", "Open Sans ➡ DejaVuSans`
![image](https://user-images.githubusercontent.com/6370548/85363403-62358400-b510-11ea-9be9-4a1475e4ad81.png)

**Comment by photopea** [comment]
Hi, the current web technology does not contain mechanisms to specify a font precisely (without including an actual font to a website).

Parameters like "font-family", "font-weight" and "font-style" are only guides for a renderer.

I propose to use a following syntax: font-family: "PostscriptName", "Family Name". Photopea will use a PostscriptName while a browser will probably use a Family Name.

It is implemented in Photopea now.  The following style works both in Photopea and in a browser.

    font-family: "OpenSans-Regular", "Open Sans";

**Comment by hxim** [comment]
Great, thanks!
