### ISSUE TITLE
Scroll

### ISSUE THREAD

**Issue by Studioartcz** [photopea/photopea#22]
If i have some zoom and will try scroll down it not work.

**Comment by photopea** [comment]
Do you mean scrolling with a mouse wheel? There is no support for mouse wheel at all (yet).

**Comment by Studioartcz** [comment]
Yes mouse wheel, it can be easy by invisible scrollbars or not?

**Comment by photopea** [comment]
Yes, it can be definitely added in the future, the behavior can mimic the Photoshop or other programs. I will keep this issue open until it's done.

**Comment by photopea** [comment]
Scroll implementation was moved to this issue https://github.com/photopea/photopea/issues/43
