### ISSUE TITLE
Photopea website not loading

### ISSUE THREAD

**Issue by jabgro** [photopea/photopea#220]
Hey. I would like to know if there are any problems with the Photopea website? It's not currently loading up. It has been like this since last Friday and I already cleared my cache. Let me know, please. Thanks.

![photopea](https://user-images.githubusercontent.com/29846221/27774308-96b3cfbc-5fc2-11e7-95f9-17c67b8ea462.JPG)

**Comment by jabgro** [comment]
Tried it with Firefox browser and it worked. However, I hope you can fix it and make it work in Google Chrome. 😄

**Comment by photopea** [comment]
Hi, Photopea works in Chrome for me.  

Can you try to disable some extensions?  Browser extensions have permissions to read and rewrite the content of every website that you visit. Their authors know about every mouse click you do in a browser. That is why I don't use any extensions.

**Comment by jabgro** [comment]
I see. Well, I kinda need these extensions so maybe I'll just use Firefox then. Thanks a lot!

**Comment by photopea** [comment]
So did it work without extensions? Maybe it is just one specific extension, that causes problems. If that is true, you can report it as a bug to the authors of your extension.

You can also use Anonymous mode, where all extensions are disabled.

**Comment by jabgro** [comment]
I tried it when I signed in as 'Guest' in Google Chrome and yes, it worked. 👍

**Comment by photopea** [comment]
And are there any errors in the Web Console?
