### ISSUE TITLE
Plugin idea

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2200]
I was thinking about making simple bar graph generator plugin where you could input information like this (with some nice user interface)
```
[Data]=
Mar;57
Apr;49
May;45
Jun;61
Jul;68
Aug;62
Sept;66
Oct;69

[MinValue]=0
[MaxValue]=70
[StepValue]=14
[DecimalPlaces]=0
[ThousandSeparator]=,
[Unit]=

[BarColor]=#444444-#2f2f2f
[BackgroundColor]=#fffcf7
[LineColor]=#c8c4be
[FontColor]=#403e38
[FontSize]=11
[FontWeight]=400

[GraphWidth]=700
[GraphHeight]=350
[GraphSpacing]=1
[BarWidth]=1
[BarSpacing]=1
[BarCornerRadius]=3
```
and get something like this inserted in photopea
![image](https://user-images.githubusercontent.com/6370548/83965715-0636f280-a8b6-11ea-9a9b-879d55d32b07.png)
I thought I could generate svg including all the labels as text and then insert it to photopea on clicking button but there is issue #1862 where text in SVG disappear when you place it into current project (as smart object). Is it possible to fix it? Or do you think there is other/better way to do it?

**Comment by photopea** [comment]
Hi, that is very interesting. 

The input format: have you considered using JSON instead? Maybe there already exists some standard to describe the data for such graphs, D3.js maybe?

Generating SVG is a great idea. You could offer SVGs directly for download. The issue with missing text in SVG smart objects can be fixed.

**Comment by hxim** [comment]
Thanks, I mean there will be user interface like input boxes for each of setting value and data will be entered in one textarea where on each line one data point and category and value semicolon separated.
This is how it might look like (it is not working version)
![obrazek](https://user-images.githubusercontent.com/6370548/83978498-255e7000-a908-11ea-9e62-425a7f30257e.png)
And after clicking Custom... there will be setting for size, colors, fontsize, spacing, label format and other stuff i imagine...
Line graph, Pie chart or some others under "Mode" are possible in the future i think

**Comment by photopea** [comment]
I really think it is a nice idea, but it is hard to tell, how many people would use it. There already exists specialized software for creating charts like this (people can just copy-paste them or take a screenshot to place them into Photopea). 

Also, many people could get angry, that if they want to modify a value, they would have to re-enter all data (unless you store the used data in cookies or something).

**Comment by MichalSZZ** [comment]
In Adobe Illustrator there is a special tool for that.
https://helpx.adobe.com/illustrator/using/graphs.html
you can even paste data from excel but... I used that only a few time in my live

**Comment by photopea** [comment]
I would be happy, if you create a plugin like this. I will add it to Window - More - ... :)

But it is hard to tell how many people would use it. If you know that at least you will be using it, that is already worth it :)

**Comment by hxim** [comment]
Hi, I just published experimental version of this plugin
See here in action:
https://hxim.github.io/ChartMakerPlugin
Repository:
https://github.com/hxim/ChartMakerPlugin

**Comment by photopea** [comment]
That is great! Do you have any data about the usage of your Emoji plugin?

**Comment by hxim** [comment]
> That is great! Do you have any data about the usage of your Emoji plugin?

No, I don't have any data about usage.

**Comment by photopea** [comment]
You can try to put Google Analytics into your plugin :) It always feels rewarding to see the statistics.

**Comment by hxim** [comment]
> The issue with missing text in SVG smart objects can be fixed.

Hi I made it now so that chart is inserted into photopea as Smart Object into exisitng project. In this case there is still issue #1862 as I wrote in the first message under this issue. I hope you can fix this because now it will show graph without any labels :(
![obrazek](https://user-images.githubusercontent.com/6370548/87708094-7cc2ec00-c7a2-11ea-9e25-853a44f1cd33.png)

**Comment by hxim** [comment]
> You can try to put Google Analytics into your plugin :) It always feels rewarding to see the statistics.

@photopea 
Hi I added Google Analytics into Emoji plugin week ago. And it shows 430 users and 512 visits for last week or 7 days.

**Comment by photopea** [comment]
Hey, regarding your Chart plugin. You are not adding a smart object, because Photopea does not render the text in it. Can your plugin open your SVG separately, and run a script to copy-paste all layers to the previous document, and close the new document? 

If an opened document contains a text layer, it will initiate loading of fonts and re-rendering (unlike Smart Objects, which are not waiting for fonts, and are rendered immediately).

**Comment by hxim** [comment]
@photopea 
1. If working with several documents after I open new document and then close it I am not returned to original document, but I go the last document.
2. I don't know how to identify uniquely previously open/original document or get its index in app.documents[] array, because several document can have same "name" ("id" property is not implemented in photopea). I would need this if I want use "app.activeDocument.activeLayer.duplicate" function to duplicate layer to original document.
3. I did something similar with this script in past - it groups and extracts all layers from Smart Object and put it to original document to the same position. It does not have issues 1 and 2 because I get reference to orignial document before opening smart object here (this is not possible with case of new document - I need to wait for loading and continue later with different script i think)

```
var doc = app.activeDocument;
var oldlayer = app.activeDocument.activeLayer;
if (oldlayer.kind == 1) {
executeAction(stringIDToTypeID("placedLayerEditContents"));
app.activeDocument.activeLayer = app.activeDocument.layers[0];
if (app.activeDocument.layers.length > 1) {
newGroup = app.activeDocument.layerSets.add();
newGroup.name = oldlayer.name;
for (var i = app.activeDocument.layers.length - 1, min = 0; min < i; i -= 1) {
  app.activeDocument.layers[i].move(newGroup, ElementPlacement.INSIDE);
}
app.activeDocument.activeLayer = app.activeDocument.layers[0];
}
var w2 = app.activeDocument.width;
var h2 = app.activeDocument.height;
app.activeDocument.activeLayer.duplicate(doc,ElementPlacement.PLACEAFTER);
app.activeDocument.close();
app.activeDocument = doc;
var newlayer = app.activeDocument.activeLayer;
newlayer.name = oldlayer.name;
var x = oldlayer.bounds[0].value, y = oldlayer.bounds[1].value;
var w = oldlayer.bounds[2].value-x, h = oldlayer.bounds[3].value-y;
oldlayer.remove();
app.activeDocument.activeLayer = newlayer;
app.activeDocument.activeLayer.translate(x, y);
app.activeDocument.activeLayer.resize(100.0*w/w2, 100.0*h/h2,AnchorPosition.TOPLEFT);
}

```

**Comment by photopea** [comment]
Yes, you need to run two scripts. If you close your current document (SVG), the activeDocument should be the last document. Or you can do app.documents.indexOf(...)  and save that index to your plugin using echoToOE().

**Comment by hxim** [comment]
I need to go back and insert layers to original document where I was in the start not to the last document in order of all documents. I just tried and no, unfortunately `app.documents.indexOf(app.activeDocument);` is not working :(

**Comment by photopea** [comment]
I tired app.documents.indexOf() in Photoshop and it does not work either.

I found this solution, which works in Photoshop and Photopea:

    var docs = app.documents, index = -1;
    for(var i=0; i<docs.length; i++) if(docs[i]==app.activeDocument) index=i;
    alert(index);

**Comment by hxim** [comment]
Hi, I attempted using your solution with following javascript function:
```
function openSvg(target, content) {
    function sendScript(script, func) {
        var data = [];
        var onMessage = function(e) {
            if (e.source != target) return;
            data.push(e.data);
            if (e.data == "done") {
                window.removeEventListener("message", onMessage);
                if (func) func(data[0]);
            }
        };
        window.addEventListener("message", onMessage);
        target.postMessage(script, "*");
    }
    sendScript("var r=-1;for(var i=0;i<app.documents.length;i++)if(app.documents[i]==app.activeDocument)r=i;app.echoToOE(r);",
        function(curDocIndex) {
            sendScript("app.open(\""+content+"\", null, false)", function() {
                if (curDocIndex != -1) {
                    var loadDone = function(e) {
                        if (e.data == "done") {
                            window.removeEventListener("message", loadDone);
                            var script = 'var doc=app.documents[@DOCINDEX];app.activeDocument.activeLayer=app.activeDocument.layers[0];if (app.activeDocument.layers.length>1){newGroup=app.activeDocument.layerSets.add();for (var i=app.activeDocument.layers.length-1,min=0;min<i;i-=1) {app.activeDocument.layers[i].move(newGroup, ElementPlacement.INSIDE);}app.activeDocument.activeLayer=app.activeDocument.layers[0];}app.activeDocument.activeLayer.duplicate(doc,ElementPlacement.PLACEAFTER);app.activeDocument.close();app.activeDocument=doc;';
                            script = script.replace("@DOCINDEX", curDocIndex);
                            sendScript(script);
                        }
                    }
                    window.addEventListener("message", loadDone);
                }
            });
            
        });
}
```
and when svg is inserted to existing document it looks like this (folder and all layers inside are selected and folder is expanded):
![screen1](https://user-images.githubusercontent.com/6370548/124349123-eb849980-dbed-11eb-9daf-bbba6ea99f6b.png)
but i want it to look like this (only folder layer is selected and folder is collapsed):
![screen2](https://user-images.githubusercontent.com/6370548/124349154-1c64ce80-dbee-11eb-9bbb-36c7cd72ab05.png)
Is it possible to do it with script?
Also I would like to rename the resulting layers so it does not have " copy" in the end. But I cannot access it with "app.activeDocument.activeLayer" because it does not return just duplicated current layer (is it bug?) See this screenshot what it returns when I call `alert(app.activeDocument.activeLayer.name);`
![obrazek](https://user-images.githubusercontent.com/6370548/124349322-bd538980-dbee-11eb-9454-ed1502a88b6b.png)
When I tried `app.activeDocument.activeLayer.name="x"` it added "Name change" action to history but nothing changed for any layer.

**Comment by photopea** [comment]
I think you should be able to set the activeLayer to another layer. 

Could you maybe provide a script, which works in Photoshop, but does not work in Photopea?

**Comment by photopea** [comment]
It has been fixed! You can insert even smart objects, which need additional fonts for correct rendering :)
