### ISSUE TITLE
Photopea not opening certain PSD files in Mobile browser

### ISSUE THREAD

**Issue by kidnip** [photopea/photopea#2201]
I have no problem opening PSD files on my PC, but it's a different story when trying to open certain files on my phone on the Photopea website. I am only able to open certain PSD files, while others just crash the website. I thought it had to do something with the image size, but after scaling it down to sizes similar to other PSD files I can open, it keeps crashing. It also doesn't matter what browser I use or where I pull the file from; it crashes the site regardless. Any advice? Thank you.

**Comment by photopea** [comment]
So you say you can open all PSDs on a PC, but it some of them crash on a phone, even when the image size is small? Could you send me such "small PSD" to support@photopea.com , so that I try it on my phone?

**Comment by kidnip** [comment]
I think I figured out what the problem was. I believe it’s because the file I was trying to open, and others like it, have too many layers. After I merged some layers, it started opening up with no problems. Maybe this has something to do with mobile browsers and their memory limitations, where it can’t handle too many layers.

**Comment by photopea** [comment]
How much RAM do you have in your phone? What browser (and version) are you using?

**Comment by kidnip** [comment]
My iPhone has 3 GB of RAM and I used Safari, the Google app, and the Google Chrome app (all latest version). It works best on Safari I found out.

**Comment by photopea** [comment]
I see. Are you using the latest iOS? The Safari in the newer iOS could handle the websites like Photopea much better.

**Comment by kidnip** [comment]
I am not using the latest iOS. Maybe this is what’s causing the problem. I will update it now and see if there’s a difference.

**Comment by photopea** [comment]
I think updating the iOS helped.
