### ISSUE TITLE
Convert to Point Text moves text

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2202]
Convert to Point Text moves my text few pixels vertically. Smaller sized font is moved less pixels then large font but it is slightly annoying to always realign the text in your design after using this function. Would be great if it keeped exact position if possible.
Before Convert to Point Text: (position is X:61,Y:94)
![image](https://user-images.githubusercontent.com/6370548/84008517-4b205f00-a972-11ea-8f2f-54b1f7f6b29d.png)
After Convert to Point Text: (position is X:61,Y:99)
![image](https://user-images.githubusercontent.com/6370548/84008574-570c2100-a972-11ea-9006-9f07045092dd.png)

**Comment by photopea** [comment]
Fixed, thanks! :)
