### ISSUE TITLE
Highlighting and creating Text box

### ISSUE THREAD

**Issue by Bella565** [photopea/photopea#2203]
I'm not sure if it's just me but all of a sudden when highlighting text instead of being transparent so you can see what you are selecting, it's now highlighting in black, so I can't see the wording selected. Particularly annoying on a black background! 

Also, when trying to make a new text box it won't actually start creating the box until I un-click and it's so small there isn't much I can do with it.

All very frustrating!
Thanks.

**Comment by photopea** [comment]
Hi, is your WebGL on? Check it in More - Use WebGL.

**Comment by Bella565** [comment]
Ah, perfect. Thanks for that.
