### ISSUE TITLE
Request: Color -> To Alpha

### ISSUE THREAD

**Issue by coolcraftnet18** [photopea/photopea#2205]
It would be useful if Photopea had color to alpha like gimp does, I use this tool a lot when putting cars in different backgrounds.

**Comment by photopea** [comment]
I don't know what exactly do you mean. If you want to remove all parts, which are e.g. not blue, you can use a magic wand to select it, invert the selection and clear the selected area.

**Comment by coolcraftnet18** [comment]
https://docs.gimp.org/2.8/en/plug-in-colortoalpha.html
I mean like translucent colors?

**Comment by photopea** [comment]
I see. It is not clear what it does, and what would anybody use it for.

To remove the sky, use Select - Color Range in Photopea. Once you have a selection, you can clear it with Edit - Clear. You will get this: https://imgur.com/3GKK1oC

In addition, you can remove the selected area from the blue channel: https://imgur.com/Bkpvnt5

**Comment by coolcraftnet18** [comment]
![Untitled drawing (12)](https://user-images.githubusercontent.com/18317131/84258341-c9047780-aae4-11ea-9753-f826d2b7f91a.png)
![Untitled drawing (13)](https://user-images.githubusercontent.com/18317131/84258350-cace3b00-aae4-11ea-95ec-20a8c787bd66.png)
Look at these images to compare opaque with transparent and translucent. The alpha color tool is used with a selection that is already made. The alpha color tool is not used to make a selection. The alpha color is used for lets say, a car window that you want to be translucent.

**Comment by photopea** [comment]
I implemented it under Filter - Other - Color to Alpha. It gives 100% identical results as GIMP.
