### ISSUE TITLE
Reordering layers - placing in bottom is hard

### ISSUE THREAD

**Issue by danielhaan** [photopea/photopea#2207]
Hello,

First of all, thanks for doing what you do. It is such an awesome tool, that I just started using instead of Photoshop after my license ran out.

When you click-and-hold a layer and drag it up/down, it is possible to move the ordering of that layer.

However, if you drag it all the way past the bottom layer, it is only possible to place it there if you let go in a small sweet spot.

**Bug behavior:**
clicking a layer, dragging it past the bottom layer, and into the empty space below all layers, then releasing the mouse does nothing.

**Expected behavior:**
I would expect the layer to be placed in the bottom, regardless of where I let go, as long as it's inside the layer container.

I hope this could be fixed, as I imagine it isn't such a difficult thing to add.

**Comment by photopea** [comment]
I fixed both issues. Thanks for reporting it! :)
