### ISSUE TITLE
Cannot upload the same font type

### ISSUE THREAD

**Issue by Vdapeach** [photopea/photopea#2209]
They have the same name but different font type, but i can't upload them

**Comment by photopea** [comment]
Hi, if Photopea contains a font with such name, you can not replace it with your own font.

What font is it? Can you share it with us?

**Comment by Vdapeach** [comment]
No, I mean, I can't upload the same type of font although it's different
Vào Th 6, 12 thg 6, 2020 vào lúc 00:16 Photopea <notifications@github.com>
đã viết:

**Comment by photopea** [comment]
There can be only one font in Photopea with a specific name. If there already is one, you can not replace it with another.
