### ISSUE TITLE
Photopea cut and paste

### ISSUE THREAD

**Issue by Jooles96** [photopea/photopea#2211]
Need help with cut and paste. I select part of an image, go to edit - copy - then open an Instagram doc via file - new but when I try to paste from my into the new instagram doc nothing happens and no new layer is created.  I've gone through this with my tutor and he is unable to figure out what the problem is. Can anyone help please?

**Comment by photopea** [comment]
Hi, are you using Photopea at www.photopea.com ? Make sure you are using it there.

Did you allow Photopea to access your clipboard? See here: https://github.com/photopea/photopea/issues/1912

**Comment by photopea** [comment]
Now, Photopea should tell you, if you refuse to give it permissions to paste.
