### ISSUE TITLE
Keyboard Shortcuts window

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2214]
![obrazek](https://user-images.githubusercontent.com/6370548/84418434-83949700-ac17-11ea-9634-51dc8cfc939c.png)
1.) What is the "abc" in the end of "Tools" list?
2.) Move Tool in Quick Tools why is there "+ Ctrl" a not just "Ctrl" like in other quick tools
3.) Blur, Sharpen Smudge seems to have no shortcut why are they listed in list of keyboard shortcuts then

**Comment by photopea** [comment]
fixed, thanks :)
