### ISSUE TITLE
Drop down menu moves after overview in chrome os

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2215]
Hi!

I am here with another chrome related bug i belive.

Here is the video explaining it:
https://video.drift.com/v/abdc63D2dkG/
 
In short: the drop down menus move to the down-left after changing windows.

If this is a chrome bug, i can report it, if not, well, here you go :)

**Comment by photopea** [comment]
Hi,  I believe it is a bug of your environment. Photopea uses "native drop-down" - it lets the browser decide, how the dropdown menu should be displayed. W3Schools has a custom dropdown - they show a floating DIV with options.

Can you update your OS and a browser? Make sure you are not using beta / experimental browser, which always have a lot of bugs like this.

**Comment by avagp** [comment]
Yes, i am in the stable channel.

And i have updated a couple of times the OS since i have this issue.

:/

**Comment by photopea** [comment]
Can you try to reproduce it at other places, which have such dropdown menu? E.g. here: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

**Comment by photopea** [comment]
Can you reproduce it in Photopea in a browser, i.e. not in "pwa version"?

**Comment by avagp** [comment]
It does not happens on w3schools (the page you gave me)

It still happens on non-pwa (in a browser tab)

**Comment by photopea** [comment]
I think the menu in Photopea works in a regular way, and it is probably a bug in a browser. 

As I can not reproduce it, it is hard for me to report it. You can report it to Chrome developers, or just ignore it and hope that it will be fixed in a next release.

**Comment by avagp** [comment]
I can reproduce it out of photopea.

I will report it as a bug.

I just created a select tag in html, and it triggers the bug
[image: image.png]

:)

**Comment by photopea** [comment]
ok, great! :)
