### ISSUE TITLE
Layer functions on touch screen

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2216]
When on tablet withhout mouse I cannot access right click menu on layer and some of the functions are not available in main menu or somewhere else (like via Quick search button in top). Can you add those functions under Quick search or to main menu or make it possible to open context menu without mouse right click.
I am talking about those functions:
- Select pixels
- Convert to Shape
- Convert to Point Text/Paragraph Text
- Layer Style - Copy / Layer Style - Paste / Layer Style - Clear

**Comment by photopea** [comment]
Hi, the context menu in the layers panel should be openable on touchscreens using a long-tap. Can you try it?

**Comment by hxim** [comment]
Hi, when I long press on layer it will initiate layers reordering. When I short press it will just select layer. I am not able to open context menu there :(

**Comment by photopea** [comment]
layer reordering - do you mean drag-and-drop of the layer?

What OS and browser (versions) are you using?

**Comment by hxim** [comment]
Yes it does drag-and-drop of the layer.
Using
Android 8.0.0
Google Chrome 83.0.4103.101

**Comment by photopea** [comment]
That is so strange. I use the same browser in Android 6.0 and it works differently.

We will have to wait until I get a new phone.  BTW. there is a "keyboard button" at the bottom of the toolbar, where you can enable virtual keys - Alt, Shift ... e.g. to select multiple layers on a touchscreen. Maybe we could add a virtual right mouse switch there?

**Comment by hxim** [comment]
> Maybe we could add a virtual right mouse switch there?

I do not know what is best solution but i would like to have ability to use these functions on my tablet
- Select pixels
- Convert to Shape
 - Convert to Point Text/Paragraph Text
 - Layer Style - Copy / Layer Style - Paste / Layer Style - Clear

**Comment by photopea** [comment]
by the way, does the layer reordering work well in your case? does it drop and reorder everything correctly?

Do you have any other Android device, where you can try it, to check if it works the same?

**Comment by hxim** [comment]
> by the way, does the layer reordering work well in your case? does it drop and reorder everything correctly?
> 
> Do you have any other Android device, where you can try it, to check if it works the same?

I have samsung phone and tablet with android 8 and 9 and in both reordering work well with drag and drop using google chrome browser

**Comment by photopea** [comment]
And what if you tap the layer with two fingers? Does it open a context menu?

**Comment by hxim** [comment]
No, tap with two fingers is not doing anything.
But I found a way how to open it. I can double tap on layer name and when keyboard show up I can long press on layer and in that case it will open context menu.

**Comment by photopea** [comment]
Are you sure a long-press with a keyboard opened does a different thing than with a keyboard closed? That is very strange.

**Comment by hxim** [comment]
Yes it does different thing when I am editing layer name. It opens context menu with long press only when cursor is inside layer name input field (keyboard can be closed/minimized without leaving edit mode of input field for layer name). After I confirm or cancel layer name change it goes back to standard behaviour of long press causing drag and drop reordering of layers.

**Comment by photopea** [comment]
I will close it for now. We can reopen it once I have a device on which I can test it.

**Comment by sobaee** [comment]
It works normally when you gently long click, you also needs to avoid moving finger during long click.l, so is hard a little bit. Could you please add a virtual right mouse switch beside keyboard button?

I am using samsung phone, android 12, on Firefox and Google Chrome browsers.

**Comment by sobaee** [comment]
> @sobaee did you try the burger menu at the corner of the layers panel? There is "long tap as right click"

Yes

It has no effect, it's the same
