### ISSUE TITLE
Color to Alpha with Selection

### ISSUE THREAD

**Issue by coolcraftnet18** [photopea/photopea#2217]
I see that color to alpha works by choosing a color you want, but I want to use color to alpha with a selection, like a car window. 
![image](https://user-images.githubusercontent.com/18317131/84508421-3dc7e500-ac90-11ea-8a66-a3024c25ccf4.png)

**Comment by coolcraftnet18** [comment]
Nevermind, I was in the wrong layer

**Comment by coolcraftnet18** [comment]
Actually, reopened, changing the layer I was on didn't fix the issue. 
Color to alpha needs a few fixes such as:
Adjustability (Adjust how alpha the color will be)
Ability to be used with a selection instead of choosing a color
Ability to use translucent alpha colors

**Comment by coolcraftnet18** [comment]
![image](https://user-images.githubusercontent.com/18317131/84509433-af546300-ac91-11ea-952c-62c955731aee.png)
It needs to look like this

**Comment by photopea** [comment]
Hi, I added the two missing parameters form GIMP: Transparency Threshold and Opacity Threshold. Now, it should work like GIMP. Let me know if you need anything else.
