### ISSUE TITLE
Copy and Paste Issue

### ISSUE THREAD

**Issue by warloc204** [photopea/photopea#2218]
It says that I didn't give access to Photopea to use the clipboard, I've already tried that lock thing next to the link and it says allow yet it still doesn't work

**Comment by warloc204** [comment]
This hasn't been a problem before today either, I had no problem cop and pasting before

**Comment by photopea** [comment]
Are you using Photopea at www.Photopea.com ? Try to use it there.

**Comment by 253488655422** [comment]
Same Problem with me, I hope this gets fixed :)

**Comment by photopea** [comment]
@253488655422 Are you using Photopea at www.Photopea.com ? Are you allowed Photopea to access your clipboard, when you were asked?
