### ISSUE TITLE
how to control the handle of path 

### ISSUE THREAD

**Issue by chandeshwarkumar** [photopea/photopea#2219]
while creating any shape or path with the pen tool. if i want to control the handles of the path, there is no option to do that. how can someone control the single handle of the path. both the handles moves simultaneously. i even checked the the help, nothing is mentioned over there regarding this issue.

**Comment by photopea** [comment]
The Pen tool is described in this article: https://www.photopea.com/learn/vg-creating

It works the same as in any other program. There is a link to a game, where you can learn how ot use it. To move handles independently, you should press Alt while drawing.

**Comment by photopea** [comment]
You can also use a Direct Select tool to edit paths you created before. Look here: https://www.photopea.com/learn/vg-manipulation

**Comment by chandeshwarkumar** [comment]
in photoshop to control the handle we need to press ALT key, but here that is not working, both the handles are working together. 
i want to control one part of the handle not both of then at a time. Either there is different key combination here or the feature is not provided.

I am using microsoft edge, ALT key is not working, just recheck

**Comment by photopea** [comment]
You are probably using an old Microsoft Edge from 2015 - 2016. Photopea can not detect any keyboard shortcuts in this Edge at all.

Please, switch to a newer Edge, or some other newer browser. https://www.microsoft.com/en-us/edge
