### ISSUE TITLE
PlayfairDisplay font problem

### ISSUE THREAD

**Issue by NatashaDK** [photopea/photopea#222]
Whenever I type with your font, Playfair Display and use the Return key to type on a new line, I get the letter "A" added ?!?! 

I tried downloading Playfair Display from this site:  http://www.1001freefonts.com/playfair_display.font
- and then uploaded the Playfair Display Regular to Photopea... That fixed the problem :-)

Am I missing something here?

NatashaDK
![bug](https://user-images.githubusercontent.com/27579710/27978526-3322bd6c-6370-11e7-865f-8fc0bf900e63.png)

[Bug_psd_file.zip](https://github.com/photopea/photopea/files/1132451/Bug_psd_file.zip)

**Comment by photopea** [comment]
Hi Natasha, thank you very much for reporting it.  I think it is the most curious bug of the year.  I fixed it :)

**Comment by NatashaDK** [comment]
Thanx!
