### ISSUE TITLE
Figma plugin

### ISSUE THREAD

**Issue by mikefats** [photopea/photopea#2220]
Photopea would be an ideal “heavy-duty” editor for raster elements within Figma (their native one is [a little bit light](https://www.figma.com/best-practices/working-with-images-in-figma/manipulating-images/). How useful would a Figma Plugin to allow embedding of a Photopea image be? 
Maybe a workflow like this? 
Figma > click to edit a raster element > opens in photopea > manipulate and save changes > jpg/png auto exported (and optimized???) and element refreshed in figma

**Comment by photopea** [comment]
Hi, have you made a Figma plugin before? I think anyone can make a plugin of Photopea for Figma, as both tools have open APIs.

Even if we made such plugin, it is hard to tell, how many people would discover it.

**Comment by mikefats** [comment]
Sorry, didn’t realize Photopea had an open API - that’s great. I don’t have the skills to make a plugin, but will ask around!

**Comment by photopea** [comment]
It would be great if someone makes it :)  I will close it for now.
