### ISSUE TITLE
Problem with copying and pasting

### ISSUE THREAD

**Issue by ladowofs** [photopea/photopea#2221]
Hi, i have a problem when copying something from the original image and pasting on to another layer.  It says that the site doesn't have clipboard permission, but in fact, it actually has! It's on Android and the browser is Chrome, i tried several things and looked at inumeral google articles but had found nothing about it, look at the image i'm annexing for reference, if you need anything more tell me.

![image](https://user-images.githubusercontent.com/66926816/84607664-e8085e00-ae84-11ea-8f2d-fe04194bdd87.png)

That's the problem above ^!

**Comment by photopea** [comment]
Hi, what version of Android are you using? Is it Android 6 or is it higher?

**Comment by ladowofs** [comment]
So it's higher, look at the image.
![WhatsApp Image 2020-06-14 at 21 59 06](https://user-images.githubusercontent.com/66926816/84608955-27d24400-ae8b-11ea-8812-58f855294314.jpeg)

**Comment by hxim** [comment]
Hi I have the same problem.
Copy and paste is not working on both my android devices one has Android 8 and one has Android 9 version with Google Chrome browser.
See what it does in this video I recorded in morning:
https://youtu.be/SjGZeatmrrw

**Comment by photopea** [comment]
It does not work on my Android phone either. I am not sure if it worked before or not. I asked a developer from Google to tell us more: https://github.com/photopea/photopea/issues/2118

**Comment by tomayac** [comment]
Sorry for that. I have filed https://bugs.chromium.org/p/chromium/issues/detail?id=1094798 and can reproduce the issue on Android Chrome 83. It works on Android Chrome 84 and 85, so maybe temporarily try running Photopea in the Beta, Dev, or, if you dare, Canary channel.

**Comment by cahmarion** [comment]
Here the same issue. I'm using a Chrome for Mac. The paste function isn't working, I can cut but not paste. Could you please help me? Thank you!

**Comment by photopea** [comment]
@cahmarion Are you using Photopea at www.photopea.com , or at another site in a frame?

**Comment by photopea** [comment]
I disabled the native clipboard when Photopea runs in frames and in Android OS. Let's hope it will be fixed soon, so that we can enable it again.

**Comment by demironmanx** [comment]
Dear @photopea Ivan, Please enable the native clipboard when Photopea runs in frames. I need to use the vanishing point filter, which only accepts pasting content with CTRL+V.

**Comment by photopea** [comment]
But it should work in iframes. What should I do to see it not working?

**Comment by tomayac** [comment]
For the iframe to be able to use the API, you need to set the proper `allow` attribute. See the [documentation](https://web.dev/articles/async-clipboard#permissions_policy_integration) for details.

**Comment by tomayac** [comment]
If you try copying the Photopea image via Photopea's **Edit** > **Copy** menu and then try pasting it, for example, into the macOS Preview app, you will notice that there's nothing on the clipboard. 

<img width="637" alt="Screenshot 2024-04-05 at 10 23 49" src="https://github.com/photopea/photopea/assets/145676/a51f7594-8117-490d-a71a-6780a19c0894">

**Comment by photopea** [comment]
So Chrome allways blocks the clipboard API for iframes from other domains? But why?

**Comment by tomayac** [comment]
Security. As the embedder, you can grant cross-origin iframes access to the API via the `allow` attribute.

**Comment by demironmanx** [comment]
> I disabled the native clipboard when Photopea runs in frames and in Android OS. Let's hope it will be fixed soon, so that we can enable it again.

Hi guys, thank you for still working out the issue.

@photopea As you reported 4 years earlier, if so you had disabled the native clipboard deliberately, is this can tell us why CTRL + C is causing "doCopy false undefined"? Could you please check the clipboard access features implemented on pp.js:16094?

@tomayac I tried to implement what you have mentioned last week. Do you please try here https://jsfiddle.net/ngxrbm74/ as well? But I couldn't use CTRL + C in this iframe. If the clipboard has something already clipped by from some other tab etc. I can use CTRL + V in the frame.

**Comment by tomayac** [comment]
The code needs to be as follows:

```html
<iframe allow="clipboard-read; clipboard-write" src="https://example.com"></iframe>
```

This enables the API. See, for example, the embedded [demo](https://web.dev/articles/async-clipboard#demos) in the article.
