### ISSUE TITLE
Photopea Local File Access Through API

### ISSUE THREAD

**Issue by coolcraftnet18** [photopea/photopea#2223]
For Chrome, if I enable --allow-local-file-access, will that let the Photopea API work with local files?
Example:
`https://www.photopea.com/#{"files":["c:\users\user\pictures\image.jpg"],"environment":{}}`

**Comment by photopea** [comment]
Hi, I think it is not related to Photopea, but to the web in general.

I just tried it in [our playground](https://www.photopea.com/api/playground) and in the console, I see "Not allowed to load local resource: file:///C:/...."

But maybe it will work in some other browser. But the easiest solution is to run a local HTTP server, I wrote a tutorial at the end of this article: https://github.com/photopea/JS-guide
