### ISSUE TITLE
Popup window in Photopea with link to a file after "publishing online"

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2224]
Is there a possibility to have a Photopea popup (with link to copy) when someone make "publish online PSD"? Many cloud apps have that functionality after file uploading.

I know there is new window with link in address bar, but maybe that one more thing will be cool for that persons who have problem with blocked popups in their browsers?

I like to check homeworks in that method - without saving many files on my computer. But students have problems with that :/

**Comment by photopea** [comment]
I see. I don't understand why it is blocked in some browsers.

The problem is, that we don't know, if a newly opened window will be blocked or not. If we knew it will be blocked, we would show the URL inside Photopea instead. But it is probably stupid to both show the URL in Photopea and open a new window. What do you think?

BTW. is the process of unblocking opening a new window so hard? I really don't know, as it never happened to me.

**Comment by MichalSZZ** [comment]
I think that giving both method isn't stupid for that moment.
Google Chrome have they own site with tips for that problem ;) I think that it is something really hard for some users...
https://support.google.com/chrome/answer/95472?co=GENIE.Platform%3DDesktop&hl=pl

But maybe if you want to have only one method... Popup window with link and two buttons will be the answer:

--------------------------------------- X
Your file was published online
-----------------------------------------
https://www.photopea.com/#i_bUR_-Yf

**[show me the file]** **[copy link]**

-----------------------------------------

but it should look like a Photopea window - not browser window (people dont read messages and they are closing everything very fast - that is the problem with clipboard copy paste problem and so on)

**Comment by photopea** [comment]
I was thinking about it for a while, and I think it is better to keep it as it is.

Opening a website is an essential task in a web browser. Everybody knows (or definitely should learn) how to open or close a website, and how to copy its URL (steps could be different for every device). Seeing a published result is also a proof, that the work is truly published.

I also think it is important to fight against browsers / extensions, which don't allow websites to open new windows.
