### ISSUE TITLE
Temporary "auto select" checked (visualy) in Move Tool when holding Ctrl 

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2225]
I always use "auto select" on. But I know that many people have that function unchecked. 
In photoshop when "auto select" is unchecked, when user hold Ctrl key, it is visualy show on Move Tool bar - checked status. When user will stop pressing, it is back to the normal state with uncheck.

**Comment by photopea** [comment]
fixed, thanks! :)

**Comment by MichalSZZ** [comment]
Thanks!
