### ISSUE TITLE
Different colors after publishing to Imgur

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2227]
https://www.photopea.com/#iklUJjOmQ
red should to be as in the project: #BA122B and the blue #00205B

in Imgur it changes to:
red #b8172f and blue #022259
https://imgur.com/YSYlNFI

it is a problem with Imgur? Or something in exporting? 
Normal save as PNG is OK.

**Comment by photopea** [comment]
Hi, in my case, the colors at Imgur are displayed identical as in Photopea. After saving a PNG and opening it in Photopea, the colors are still identical.

What did you do to get the values red #b8172f and blue #022259 ?

**Comment by MichalSZZ** [comment]
I'm inspecting it with color picker in web developer tool in FF. Maybe there is a bug... I know that browsers may have something like they own color profiles. Sometimes i look on image in Windows preview and colours there can be different than in browser.

**Comment by photopea** [comment]
I could not reproduce such issue in Firefox on Windows (colors are identical).

The PNG from Photopea, and the PNG on Imgur have the "sRGB" tag set to 1, meaning, that the color space is sRGB (you can open the PNG in a notepad and see the text "sRGB"). So if a browser renders the image at Imgur differently, than the preview in Photopea, it is a bug in a browser.

Can you tell me, if you see the same colors here: https://jsfiddle.net/9csj34x1/ ?

**Comment by MichalSZZ** [comment]
Yes, on jsfiddle both colors are same when I teste it. But Different then a # hex colour.

<img width="1052" alt="obraz" src="https://user-images.githubusercontent.com/38118273/84916600-8e8b7380-b0be-11ea-8d20-b95c8583e1c7.png">


I think that can be a problem with some of my "color profile" settings on my laptop :/

**Comment by photopea** [comment]
It is hard to tell. But we see, that it is not related to Photopea.

The code in your screenshot fills a rectangle with a color #ba122B,  Firefox renders it and tells you it is a color #b8172f. You can report it to them, if you want, or just use a different browser.
