### ISSUE TITLE
,,smart object must be rasterized first"( it's not leting me free transform my object)-Photopea

### ISSUE THREAD

**Issue by anwayne** [photopea/photopea#2228]
HELP ME!!

**Comment by photopea** [comment]
Hi, you should always be able to free-transform a smart object.

What exactly did you do? I can not make Photopea show such error.

**Comment by photopea** [comment]
I havee to close it because of lack of details.

**Comment by quantuminformation** [comment]
I added an image and I got message

Smart Object must be rasterized first

So I then rasterised it and I still cannot transform it:

![image](https://user-images.githubusercontent.com/216566/93896082-cc68eb00-fcf0-11ea-819d-fb7583bcb08f.png)

**Comment by photopea** [comment]
What do you mean by "transform it"? You should be able to apply a Free Transform on smart objects without any problems.

**Comment by quantuminformation** [comment]
i downloaded the psd then re uploaded, and it worked, so no worries
