### ISSUE TITLE
Feature Request: Measurement Guide

### ISSUE THREAD

**Issue by shahmoeen** [photopea/photopea#223]
First of all thank you so much for such a nice tool. This small tool have capabilities to do most of Photoshop and sketch tasks.
I want to request/suggest two features which will make this handy tool more professional and useful.

**1. Vertical and Horizontal Alignments**
first feature I want to request is vertical and horizontal alignments of shapes and other elements. so we can align any two or more elements left, right, center, top and bottom.

**2. Measurement guides**
second feature I want to request is measurement guides. Measurements guides that can display distance between two elements. so while designing something we can check distance between elements. this will make alignments so easy.

**Comment by photopea** [comment]
Hi, thank you!  

Are these features already present in Photoshop or some other program? I never used them, so I am not completely sure how should it work. Do you know, that Photopea has snapping? Is it something, what cannot be done with snapping?

**Comment by shahmoeen** [comment]
snapping is very helpful tool and it become more helpful if we can snap to layers. (which currently we can't do in photopea)

above both feature which i suggested in my thread are available in photoshop and also in another tool which I use Gravity Designer. I am attaching a screenshot which explain a little bit better what I am saying.
http://i.prntscr.com/bKQQ-J81TIq1Hj-LAQVd7g.png

**Comment by photopea** [comment]
Hi, I have added Vertical and Horizontal Alignment buttons.

I still don't know how Measurement guides should work. Can you explain it?

Snapping to layers: I think it is quite confusing feature. There are usually too many layers, so the object gets snapped "everywhere".  Isn't it better to add a guide, and then snap both layers to that guide? Or with these new Alignment buttons?

**Comment by shahmoeen** [comment]
thank you so much for adding another nice feature in your really great tool.

I found a video on youtube that is showing how Measurement Guides Work.
Have a look at this:
https://www.youtube.com/watch?v=8W4uCuxJcIA

Actually I really don't like Snapping feature and these new alignments
button will solve lot of problem, so forget snapping.

Thank you once again for adding this new feature.

**Comment by photopea** [comment]
Hi, I have added the Distances checkbox. It works similar to the video. What do you think about that?

![image 4](https://user-images.githubusercontent.com/15955558/28278112-3cdc1d7c-6b1c-11e7-8a08-0f4b3b8273ab.png)

**Comment by shahmoeen** [comment]
Working Perfectly, thank you so much!

**Comment by photopea** [comment]
Thanks for suggesting it :)
