### ISSUE TITLE
Distances tooltip very small

### ISSUE THREAD

**Issue by joaopereiraspic** [photopea/photopea#2231]
Hello,
the sizes and distances between elements when using the Move Tool the distances is very small, barely readable. Restarting chrome doesn't correct this.

I'm using Chrome 83.0.4103.61 in a MacOS 10.15.5. 

![image](https://user-images.githubusercontent.com/64983510/84811504-dd74d280-b004-11ea-9033-913f28741b67.png)

**Comment by photopea** [comment]
Hi, I fixed it, it should look better now. Thanks!
