### ISSUE TITLE
nothing special tho

### ISSUE THREAD

**Issue by lucythedumbbie** [photopea/photopea#2232]
so, i am just so fucking dumb. i do know heck about this photopea shit and i am like freaking out!!!!!!!!!! cuz my teacher just thinks that i am super clever,,,,,,,but,,,,,,,I AM NOT. THAT IS THE FUCKING PROBLEM!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! help plzzzzzzz, i wil die ;)))))))))

**Comment by photopea** [comment]
Hi, sorry, we do not reply to requests, which contain offensive language.
