### ISSUE TITLE
Sidebar is missing

### ISSUE THREAD

**Issue by kbridge89** [photopea/photopea#2233]
I can't find the sidebar, so there are a lot of windows I cannot use because it's missing. When I try to open windows like the layers window through the menu on top it doesn't do anything. It is not a problem if I am logged out but it disappears when I log in.

**Comment by photopea** [comment]
Hi, that is very strange. Could you tell us your email address? We will look into it.

**Comment by photopea** [comment]
Once you tell me your email address, I will delete your account, so that you can start a new one.

You can also try to delete cookies for Photopea, it also could help.

**Comment by kbridge89** [comment]
kbridge1996@gmail.com

**Comment by photopea** [comment]
Hi, I deleted your account. You can log in again, if you want.
