### ISSUE TITLE
Issue resizing pictures

### ISSUE THREAD

**Issue by farrellsc9** [photopea/photopea#2235]
I'm having an issue when I'm resizing a picture on photopea. I can move the picture up, down, left, and right, but cannot zoom in or out to make the picture bigger or smaller.

**Comment by photopea** [comment]
Do you want just to "look closer" at the picture (zoom in the preview), or you want to change the size of the document (e.g. from 2x3 inches to 4x6 inches)? 

You should read these articles:
https://www.photopea.com/learn/navigation
https://www.photopea.com/learn/image-size

**Comment by farrellsc9** [comment]
no i mean changing the size of the image using free transform. I cannot make an image bigger or smaller. I also cannot rotate an image. Same goes with applying text.

**Comment by photopea** [comment]
Free transform is only for resizing layers. To change the "rectangular window", through which you see the layers, you should use the Crop tool. I really recommend reading those articles, I am sure you will find an answer there.
