### ISSUE TITLE
Custom fonts are not loaded

### ISSUE THREAD

**Issue by xsouto** [photopea/photopea#224]
Hi i try to load a custom font but it doesn't, help pls!!!

**Comment by photopea** [comment]
Hi, can you send us your font to support@photopea.com ?

**Comment by photopea** [comment]
Ok, I see the problem, give me a minute.

**Comment by photopea** [comment]
It should be fixed now. Thank you very much for letting us know!

**Comment by xsouto** [comment]
YES IT WORKS! THANKS!!!! BEST PHOTO EDITOR ONLINE

**Comment by morpheus4721** [comment]
when i use custom fonts it just showed a line instead of text and when i chose a font made by Photopea is just said loading and doesnt let me type anything
