### ISSUE TITLE
Unable to zoom in on my project

### ISSUE THREAD

**Issue by TheAvGe** [photopea/photopea#2240]
I am unable to zoom in to my project to get a closer look at the small details. Even if I do ctrl (+) +, I can't move around in the new zoom setting. I have tried messing with View, and nothing has happened. Please help

**Comment by TheAvGe** [comment]
Update: I can now zoom in and out, but only if I click the + and - buttons on the home screen, which are unavailable after I use a tool.

**Comment by photopea** [comment]
Hi, what do you mean by the homescreen? You should be able to zoom with a Zoom tool (in a toolbar). Does it work?

**Comment by TheAvGe** [comment]
Sorry, not homescreen. Regular screen. 
I can zoom in and out, but I cannot move around. I can only go in and out to a set location

**Comment by photopea** [comment]
You can "pan" with a Hand tool. It is at the bottom of a toolbar.

**Comment by photopea** [comment]
I wrote an article about the navigation here: https://www.photopea.com/learn/navigation . I really recommend reading it.
