### ISSUE TITLE
Cannot zoom any further!

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2241]
Today i was zooming in i could not zoom as far as 3 times (from Fit the area)

The only way to kee p zooming in is to clic Pixel to pixel and then keep zooming.  :O

https://video.drift.com/v/abszSwvp5FG/

**Comment by photopea** [comment]
Hi, I edited the zooming feature today.

Does it still happen? I can not reproduce it.

**Comment by photopea** [comment]
I can reproduce it now.

**Comment by avagp** [comment]
I am working right now.

It still happens

**Comment by photopea** [comment]
I t is fixed now. I am very sorry again, it was a stupid mistake on my side.

**Comment by avagp** [comment]
:P

It is not stupid Ivan. It is part of the process and i am glad you respond
so quick to my reports!!

Have a great day
