### ISSUE TITLE
The text area is small and text input cannot be transformed

### ISSUE THREAD

**Issue by a573367014** [photopea/photopea#2243]
<img width="225" alt="A459F5FB-C916-49AE-ABDF-15FBD8FC727E" src="https://user-images.githubusercontent.com/14799720/85088268-4c734680-b212-11ea-90e0-3e5780e7a467.png">

**Comment by photopea** [comment]
Hi, you can change the text size to make the text bigger. See here: https://www.photopea.com/learn/text-style

To transform a layer (rotate, etc.) use a Free Transform: https://www.photopea.com/learn/free-transform
