### ISSUE TITLE
Free Transform box corner squares

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2244]
Free Transform box squares in the corners and on sides becomes broken and too small after zoom in.
See screenshots

Normal zoom:
![image](https://user-images.githubusercontent.com/6370548/85161817-a0a51780-b260-11ea-8129-d7cda55475af.png)

Higher zoom:
![image](https://user-images.githubusercontent.com/6370548/85161596-499f4280-b260-11ea-8f16-77f5d0a89931.png)

Edit:
Same thing happens with points of vector shapes

**Comment by photopea** [comment]
fixed, thanks!
