### ISSUE TITLE
Clipboard access is allowed, but photopea says it isn't?

### ISSUE THREAD

**Issue by SampledText** [photopea/photopea#2245]
![Annotation 2020-06-19 173235](https://user-images.githubusercontent.com/67172392/85183846-e22ec600-b252-11ea-8feb-b089d7d32f6f.png)
![image](https://user-images.githubusercontent.com/67172392/85183875-0ab6c000-b253-11ea-8993-1a3faaedaa61.png)

?????

**Comment by photopea** [comment]
Hi, that is very strange. Can you disable browser extensions, or try it in Incognito mode?

**Comment by SampledText** [comment]
Sure, I'll try it right now and get back to you in a minute!

**Comment by SampledText** [comment]
Ahh, actually, I should have mentioned, this is totally my bad, this is the "app" version of photopea.

**Comment by SampledText** [comment]
I tried both in incognito mode and without extensions individually, then both at once. Same issue :( 
Strangely enough, this only happens with images I try to copy from a file on my computer, files copied from the internet are perfectly fine

**Comment by photopea** [comment]
That is really strange. I modified it, so that now, it prints an actual error message in brackets: (...). 

Can you try it again and tell us, what error message you see?

**Comment by SampledText** [comment]
"No valid data on the clipboard"
I'm trying to copy this file specifically at the moment, but it seems all others that are stored on the drive are "invalid". 
![image](https://user-images.githubusercontent.com/67172392/85184633-0b048a80-b256-11ea-9098-a691b617a204.png)

**Comment by photopea** [comment]
Oh, you copied a file from a File Explorer in Windows.

Can you paste a copied file into any other program? It does not have to be a web program.

I think files copied in a File Explorer can be pasted only in File Explorer.

**Comment by SampledText** [comment]
I tried with paint.net and it worked fine, same with regular Paint

**Comment by SampledText** [comment]
Well, actually that isn't entirely true. with Paint I had to use "paste from"
![image](https://user-images.githubusercontent.com/67172392/85184807-cc230480-b256-11ea-956f-5f1a8f6ccd1d.png)

**Comment by photopea** [comment]
I tried to paste a PNG file into Paint with Ctrl+V, it did not work.

I think File - Paste in Paint corresponds to File - Open in Photopea.

You can open files in Photopea quickly by dragging them down to the taskbar onto Photopea, until it is opened, and then, release the file inside Photopea.

**Comment by SampledText** [comment]
Hmm, well alright, that'll work for me. Thanks for your time then, sorry it wasn't something that could be remedied!
That's strange though, I wonder why that is?

**Comment by photopea** [comment]
I think only Microsoft can solve it by changing the way copying in File Explorer works.

Copied files can not be pasted not only in Photopea but you can not paste them even into MS Paint.
