### ISSUE TITLE
My SVG graphs issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2246]
I was able to generate those SVG graphs with via developlment version of my plugin but they do not open correctly in Photopea. It is possible there is some issue on my side but browsers open them without problems.

graph(1).svg - text labels on x-axis are vertically aligned in the middle - they should be in the bottom because I set there dominant-baseline="hanging".

graph.svg - does not open at all with Error. Please, send your file to support@photopea.com and we will solve it. I guess it has some problem with stroke color specified as rgba value. (there is message unknown fill rgba(191,29,46,0.15) in console)

[svgs.zip](https://github.com/photopea/photopea/files/4807839/svgs.zip)

**Comment by photopea** [comment]
Hi, I fixed it, it should work well now.

BTW. there are thousands of SVG files opened in Photopea, but nobody reported the rgba() issue before. That is because rgba() colors never occur in SVG in practice. fill-opacity and stroke-opacity are used instead.

Photopea accepts rgba() now, but you might have issues when opening your SVGs in other editors.

**Comment by hxim** [comment]
While testing my graph plugin I found some issue with opacity on text layers.
Photopea will not apply opacity for <text> element if it has only one <tspan> subelement, when it has multiple children <tspan> it will work as exected. See how "United Kingdom" has opacity applied and not the other labels. 
Even if I open this SVG change opacity manually and save and reopen in Photopea opacity disappears/is not loaded.

See my SVG file and screenshots:
Photopea:
![obrazek](https://user-images.githubusercontent.com/6370548/87145679-f7bf6a80-c2a9-11ea-84db-54fa2760e2ad.png)
Chrome and Firefox:
![obrazek](https://user-images.githubusercontent.com/6370548/87145944-7b795700-c2aa-11ea-990b-b03a828b676d.png)

SVG:
[graph(17).zip](https://github.com/photopea/photopea/files/4902591/graph.17.zip)

**Comment by photopea** [comment]
Hi, I fixed the issue.

Note, that when <text> contains just one <tspan>, it is converted to one text layer, but when there are more <tspan>s, <text> is converted into a folder with several text layers inside. I think it helps to keep a nice structure.

**Comment by hxim** [comment]
Yes, nice thanks.
