### ISSUE TITLE
Image Resizing and rotation

### ISSUE THREAD

**Issue by Micky661** [photopea/photopea#2247]
Hi, I am not able to edit anything in the photopea. I can't resize any image or text and I can't even rotate it. Plz see to it

**Comment by photopea** [comment]
Hi, you should do these things according to our manual at www.Photopea.com. I just tried it and it works for me. If it really does not work, you should be more precise about what exactly did you do.

**Comment by photopea** [comment]
You probably meant zooming with "pinch to zoom". It should be fixed now.

**Comment by Micky661** [comment]
Thanks
