### ISSUE TITLE
Feature request: blending options for smart filters

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2248]
### Description
In Photoshop, each Smart Filter has an icon representing Blending Options. Double clicking the icon (instead of somewhere else on the Smart Filter) brings up a pop-up window that allows the user to change the filter's blending mode and opacity with respect to the Smart Object that the filter is applied to.

### Example of desired result
![Button for blending options](https://pe-images.s3.amazonaws.com/photo-editing/cc/sharpen-high-pass/new/smart-filter-blending-options-icon.png)
![Example](https://pe-images.s3.amazonaws.com/photo-editing/cc/sharpen-high-pass/new/blend-modes-high-pass-photoshop.png)
(I don't own these images. The Images are by Steve Patterson from https://www.photoshopessentials.com/photo-editing/sharpen-high-pass/)

**Comment by photopea** [comment]
Hi, I implemented it, it works in a similar way as in Adobe Photoshop.

**Comment by hxim** [comment]
Hello I tried this function but it did not work and completely crashed Photopea.
![image](https://user-images.githubusercontent.com/6370548/85664285-96907800-b6a9-11ea-875a-78ef69d71b42.png)
1. I opened pea.psd.
2. Selected all layers and converted to Smart Object
3. Added Filter-Pixelate-Mosaic
4. Double clicked the new icon next to text "Mosaic"
5. Pressed OK in dialog.
6. Error appears and nothing works in Photopea

**Comment by photopea** [comment]
Oh, sorry for that. It is fixed now. Thanks for reporting it :)

**Comment by dentistformyeye** [comment]
Thank you!
Would you also be willing to add a Fill slider for Smart Filters? I don't think Photoshop has one, though.

**Comment by photopea** [comment]
You are welcome :)  What should a Fill slider do? Do you know, that there is an Opacity slider in Blending Options of a smart filter?

**Comment by dentistformyeye** [comment]
Fill acts differently from Opacity for eight blend modes: Color Burn, Linear Burn, Color Dodge, Linear Dodge (Add), Vivid Light, Linear Light, Hard Mix, and Difference.

For example, I am using a Color Fill set to Hard Mix. This Color Fill layer has Opacity 100% and Fill 30% on the left (bottom folder) but Opacity 30% and Fill 100% on the right (top folder).
![image](https://user-images.githubusercontent.com/51429646/85800266-a3938280-b70e-11ea-8173-58b54ba3c756.png)

**Comment by photopea** [comment]
Yes, I know, that Opacity and Fill of the layer act differently on some blend modes. As you can see, I even managed to implement it into Photopea the right way :D

I think we could add a Fill parameter, but it is hard to tell how many users actually need it. Also, Adobe Photoshop would not be able to process such parameter in PSD files from Photopea.

But I think you could duplicate a smart object, apply right filters on each copy, and then, configure the blending options of a layer (not a smart filter)

**Comment by dentistformyeye** [comment]
> Also, Adobe Photoshop would not be able to process such parameter in PSD files from Photopea.

Ah, that's a very good point. Thank you for the workaround. And I'm very impressed that you'd managed to recreate the Fill for layers! All of the other photo/art programs I've found don't have Fill at all.
