### ISSUE TITLE
Feature request: precision to a tenth of a pixel for filters

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2249]
### Description
Some filters in Photoshop have a parameter (such as Blur, Radius, or Distance) measured in pixels that can be controlled by a slider and a textbox. The parameter can measure to a tenth of a pixel.  However, some Photopea filters round the value to a whole number. High Pass is one example of a filter that doesn't accept decimal values in Photopea, but does in Photoshop.

### Example that already has desired result
![Photopea Gaussian Blur box](https://user-images.githubusercontent.com/51429646/85208757-f16c4d00-b300-11ea-9e46-22d2469bbbab.png)
This screenshot is of Photopea's Gaussian Blur filter. The Radius parameter allows decimals in both Photopea and Photoshop.

### Example that doesn't have desired result
![Photopea High Pass box](https://user-images.githubusercontent.com/51429646/85208788-1b257400-b301-11ea-9216-5691dbbfe407.png)
This screenshot is of Photopea's High Pass filter. The Radius parameter only accepts whole number pixel values. Decimal values get rounded (e.g. 3.5 gets rounded to 4).

![Photoshop High Pass box](https://pe-images.s3.amazonaws.com/photo-editing/cc/sharpen-high-pass/new/lowest-radius-value.png)
(I don't own this image. This image is by Steve Patterson from https://www.photoshopessentials.com/photo-editing/sharpen-high-pass/.) In Photoshop, the Radius parameter for High Pass allows decimal values to a tenth of a pixel.

**Comment by photopea** [comment]
Hi, I fixed these parameters for High Pass. Do you know any other place, where a decimal radius is appropriate?

**Comment by dentistformyeye** [comment]
Thank you!
Normal Map (Blur) and Unsharp Mask (Radius) also use decimal values.

![image](https://user-images.githubusercontent.com/51429646/85439892-7f437480-b55b-11ea-9426-373e01f223c4.png)
[Source](https://photoshoptrainingchannel.com/photoshop-3d-depth-maps-bump-normals/) for normal map pic

![](https://pe-images.s3.amazonaws.com/photo-editing/cc/sharpen-unsharp-mask/unsharp-mask-radius-default-value.png)
[Source](https://www.photoshopessentials.com/photo-editing/how-to-sharpen-images-in-photoshop-with-unsharp-mask/)  for unsharp mask pic

**Comment by photopea** [comment]
fixed, thanks! :)
