### ISSUE TITLE
Communicate with a script from a plugin

### ISSUE THREAD

**Issue by mprinc** [photopea/photopea#2252]
Considering [Plugins](https://www.photopea.com/api/plugins) and having [Scripts](https://www.photopea.com/learn/scripts)

I am wondering is it possible and is there any demo of them two communicating: so I can create a plugin that will talk to the particular script (or a function from the script

This is my script:

```js
function ArrayUnitValueToArray(arrayUV){
  let array = []
  for(let i=0; i<arrayUV.length; i++){
    array.push(arrayUV[i].value);
  }
  return array;
}

function getSelectionBounds(){
  let selection = app.activeDocument.selection;
  let bounds = ArrayUnitValueToArray(selection.bounds);
  alert("bounds: " + JSON.stringify(bounds));
  console.warn("page bounds: ", JSON.stringify(bounds));
  return bounds;
}
```

Can I create a plugin with a button that when I click it I get script or even better the method `getSelectionBounds()` called and I can get its result and use it further on?

Thanks

**Comment by photopea** [comment]
Hi, the plugin is a website, which runs in an iframe opened by Photopea. A script is just a string of characters, which can be executed by Photopea.

The plugin as a website can send scripts to Photopea, and Photopea will execute these scripts. You can look at the Live messaging api: https://www.photopea.com/api/live

**Comment by mprinc** [comment]
Thanks, yes I am aware of the live messaging support, but didn't get completely how it can work all together. Will try it again and close the issue when I manage it. thanks

**Comment by photopea** [comment]
It is very simple. A plugin (or any other window) sends Photopea a script to execute.

Your script can contain a command app.echoToOE(...);  which sends a string back to the window.

**Comment by hxim** [comment]
@photopea 
But last time I tried I could send scripts from plugin to photopea but plugin never received anything back. When testing I was able to receive messages only in OE never inside plugin.
I tried it here:
https://www.photopea.com/#%7B%22environment%22:%7B%22plugins%22:%5B%7B%22name%22:%22plugin_debug%22,%22url%22:%22https://hxim.github.io/TwemojiPlugin/plugin_debug.html%22,%22width%22:400,%22height%22:400%7D%5D%7D%7D

**Comment by photopea** [comment]
@hxim oh, you are right. I never noticed it, as I never made plugins myself.

Now, when a script performs app.echoToOE(...);  or saveToOE(); , or "done" by Photopea, these message are sent to the parent frame (when in iframe) and to iframes of all plugins, that are currently opened.

**Comment by photopea** [comment]
I think after this fix, all things mentioned above should be doable.

I will close it for now. But we can still keep discussing it.

**Comment by mprinc** [comment]
Thank you, it works fine now
