### ISSUE TITLE
Unlinked (Corner) knot

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2254]
Unlinked (Corner) knot of vector shape on higher zoom level is wrongly positioned on nearest pixel instead of actual position. On maximum zoom level it becomes invisible or very small.
![image](https://user-images.githubusercontent.com/6370548/85253136-cfd4a800-b45d-11ea-95ab-4a1e3727477a.png)
![image](https://user-images.githubusercontent.com/6370548/85253207-f0046700-b45d-11ea-87d1-fc53e1b8f54d.png)

**Comment by photopea** [comment]
fixed, thanks! :)
