### ISSUE TITLE
Clone Tool Fixed Mode

### ISSUE THREAD

**Issue by coolcraftnet18** [photopea/photopea#2256]
Can you add a mode for clone tool where the clone source will not move with the brush?

**Comment by photopea** [comment]
Hi, i dont know what you mean. There is the "Aligned" checkbox at the top, is that what you need?

**Comment by coolcraftnet18** [comment]
https://docs.gimp.org/2.10/en/gimp-tool-clone.html
Scroll down to "Fixed" alignment

**Comment by photopea** [comment]
That is a very weird option. It clones the cirular area from one spot, and pastes the same circular area along the mouse strokes (with 1 pixel gap in between). 

Do you really need it in practice? Do you "paint" with it, or you just need to copy a piece of image from one spot to another?

**Comment by photopea** [comment]
I think a "Fixed" mode for a clone stamp is not useful in practice. If you want to copy some area to other places, use a Patch Tool.
