### ISSUE TITLE
Transform and Free Transform Tools not working

### ISSUE THREAD

**Issue by Niki8836** [photopea/photopea#2257]
The title of the issue is almost says what the problem is. Transform and Free Transform Tool are not working. Neither through the file bar, nor through Right Click on the image. I tried restarizing and doing all it needs to scale an image, but all of it didn't work.

**Comment by photopea** [comment]
Hi, they do work for me. Can you reload the website? Or you can close it and open it again.

**Comment by photopea** [comment]
I think it was fixed by reloading a website.
