### ISSUE TITLE
Photopea API demo page broken

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2258]
I am sorry I have broken Photopea API demo page here
https://www.photopea.com/api/demo
I opened edit of some file with edit link - this URL https://www.photopea.com/#%7B%22files%22:%5B%22//www.photopea.com/api/img/1590783694.jpg%22%5D,%22server%22:%7B%22version%22:1,%22url%22:%22//www.photopea.com/api/saveImage.php%22,%22formats%22:%5B%22jpg%22%5D%7D%7D
Then I changed app.activeDocument.source with script
and pressed File - Save

**Comment by photopea** [comment]
Hi, I removed the Demo page completely, as people uploaded their images and it became very messy. I think such page is not needed anymore.
