### ISSUE TITLE
PNG download button not working

### ISSUE THREAD

**Issue by br2234** [photopea/photopea#2259]
The PNG download button below the red account button does not work. It downloads a small .png file with nothing inside it. You have to go file>export as>PNG to make it work

**Comment by photopea** [comment]
Hi, that button will download only a currently selected layer as PNG. You probably selected an empty layer.

**Comment by br2234** [comment]
Hi,

Thanks for the update. I did not realise the function was to only download
1 layer.

I would vote to change the function to download the project as a .png.

Thank you for your amazing app. It is super useful. It looks like you have
put a lot of work into it.

Best,
Ben

  Ben Rycroft
Publisher Success
<https://t.sidekickopen77.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPfhMynW7fcJ5d1qgd6vW56dJ8l1vYZ6C102?te=W3R5hFj4cm2zwW4mKLS-4cMPmfW3K6c9D43T4N9W4hMnzc4cNcV-W3F6d8p3_R592W1Grjjh41PGFyW49KnK14fKWwwW3K2-zD3_y2XLW3zbV9S2PQW1kW1pVFVG3vcgmQW45LLHw41wC8yW41NNPD3P4cDl4Pc_c1&si=8000000003270457&pi=797aab52-1929-4211-f9ee-b87c4fde0351>
ben@snigelweb.com <ben@snigel.com>
+353 85 162 9785 <+353851629785>
Schedule a Meeting 📆
<https://t.sidekickopen77.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPfhMynW7fcJ5d1qgd6vW56dJ8l1vYZ6C102?te=W3R5hFj4cm2zwW3zfPSj3R5HxGW45SBgq3Fbt5SW3_SMKM3T1k87F1LvF4gn3bh1&si=8000000003270457&pi=797aab52-1929-4211-f9ee-b87c4fde0351>
[image: LinkedIn]
<https://t.sidekickopen77.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPfhMynW7fcJ5d1qgd6vW56dJ8l1vYZ6C102?te=W3R5hFj4cm2zwW4mKLS-3ZWVWBW3K2-zv1JxwY5W1Lyz993C7MZ3W49TQyM43QhvB0&si=8000000003270457&pi=797aab52-1929-4211-f9ee-b87c4fde0351>
[image:
WhatsApp]
<https://t.sidekickopen77.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPfhMynW7fcJ5d1qgd6vW56dJ8l1vYZ6C102?te=W3R5hFj4cm2zwW4myt1c3JFRG3W1V3fXV1-YpYLW22WLvL4fGCX6W2dXt651S1ttmW4f8W1R1mrCrmW24X2Tk1S1sHMW3zhl8l1NsMSDW4hMgd21NFNntW49cNml3K6K772203&si=8000000003270457&pi=797aab52-1929-4211-f9ee-b87c4fde0351>
[image:
Skype]

Snigel Web Services Ltd, The Black Church, St. Mary's Place, Dublin,
Ireland, VAT: IE9839158S

**Comment by photopea** [comment]
Thanks. The total content can be downloaded with File - Export As - PNG. There are also many options (Quality, etc.).

**Comment by br2234** [comment]
Hi,

Yes, thank you. I use the File - Export As - PNG often. It just takes a bit
longer when you are running many downloads.

P.S. There is room to increase your ad revenue. I work for an ad tech
company that helps big sites like w3schools.com. We can give you special
treatment. Drop me a line if you're interested and I can connect you with
our best ad ops manager.

Best,
Ben

  Ben Rycroft
Publisher Success
<https://t.sidekickopen77.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPfhMynW7fcJ5d1qgd6vW56dJ8l1vYZ6C102?te=W3R5hFj4cm2zwW4mKLS-4cMPmfW3K6c9D43T4N9W4hMnzc4cNcV-W3F6d8p3_R592W1Grjjh41PGFyW49KnK14fKWwwW3K2-zD3_y2XLW3zbV9S2PQW1kW1pVFVG3vcgmQW45LLHw41wC8yW41NNPD3P4cDl4Pc_c1&si=8000000003270457&pi=204a8721-5674-416c-eddf-ab2da6fa984a>
ben@snigelweb.com <ben@snigel.com>
+353 85 162 9785 <+353851629785>
Schedule a Meeting 📆
<https://t.sidekickopen77.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPfhMynW7fcJ5d1qgd6vW56dJ8l1vYZ6C102?te=W3R5hFj4cm2zwW3zfPSj3R5HxGW45SBgq3Fbt5SW3_SMKM3T1k87F1LvF4gn3bh1&si=8000000003270457&pi=204a8721-5674-416c-eddf-ab2da6fa984a>
[image: LinkedIn]
<https://t.sidekickopen77.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPfhMynW7fcJ5d1qgd6vW56dJ8l1vYZ6C102?te=W3R5hFj4cm2zwW4mKLS-3ZWVWBW3K2-zv1JxwY5W1Lyz993C7MZ3W49TQyM43QhvB0&si=8000000003270457&pi=204a8721-5674-416c-eddf-ab2da6fa984a>
[image:
WhatsApp]
<https://t.sidekickopen77.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5XWPfhMynW7fcJ5d1qgd6vW56dJ8l1vYZ6C102?te=W3R5hFj4cm2zwW4myt1c3JFRG3W1V3fXV1-YpYLW22WLvL4fGCX6W2dXt651S1ttmW4f8W1R1mrCrmW24X2Tk1S1sHMW3zhl8l1NsMSDW4hMgd21NFNntW49cNml3K6K772203&si=8000000003270457&pi=204a8721-5674-416c-eddf-ab2da6fa984a>
[image:
Skype]

Snigel Web Services Ltd, The Black Church, St. Mary's Place, Dublin,
Ireland, VAT: IE9839158S
