### ISSUE TITLE
Layers get distorded and disorganized when export to PDF

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2261]
I was working on a LUDO gameboard on Google Slides, then transfer it to photopea to keep working there.

But when i am about to export it to PDF, i get super weird, please take a look:
![Screenshot 2020-06-24 at 14 22 35](https://user-images.githubusercontent.com/11801254/85611893-5805a980-b626-11ea-914f-174ce4ebeb64.png)
[Lud8.zip](https://github.com/photopea/photopea/files/4827222/Lud8.zip)

I am attaching the PSD as well for you to see

**Comment by photopea** [comment]
Hi, there was a bug in our PDF encoder, it is fixed now :)
