### ISSUE TITLE
Crop Tool - difference between "trim" and "current layer"

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2266]
I'm wondering what is the difference in Crop Tool between "trim" and "current layer".
Is Trim working correct? In menu "Edit" -> "Trim", that function cuts all empty pixels around all layers, and make canvas size to fit perfect to the layers. Shouldn't work the same in crop tool?

**Comment by photopea** [comment]
The Trim feature tries to "trim out" a specific color from the image. It finds a smallest rectangle, such that only a specific color is outside that rectangle.

Currently, Image - Trim  trims by a color in a top left corner of a total image.

I made the "Trim" button in a Crop Tool settings do the same thing as Image - Trim.

**Comment by MichalSZZ** [comment]
Ok, thanks!
Now "Trim" crop the area as I expect (now there is a difference)

**Comment by photopea** [comment]
what difference do you mean?

**Comment by MichalSZZ** [comment]
When I checked it yesterday, both buttons worked same in crop tool. I had many layers, and both buttons created crop box from only one layer
