### ISSUE TITLE
Paint Bucket Tool doesn't work on raster mask of a folder

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2267]
### Description:
Attempting to use the Paint Bucket Tool on the raster mask of a folder triggers the "No layer selected" alert.

### Steps to reproduce:
1. Open any image in Photopea
2. Press ctrl-G or select Layer > Group Layers to create a folder.
3. Add a white raster mask to the folder. Verify that the raster mask is selected and that the image in the workspace doesn't seem to have changed.
![image](https://user-images.githubusercontent.com/51429646/85856647-5d7a0580-b786-11ea-9ba1-e61d407e8cb5.png)
4. Choose black as the foreground color.
5. Select the Paint Bucket Tool (under the Gradient Tool).
6. Click on the image in the workspace.

### Expected result:
The image in the workspace should become a checkerboard pattern indicating transparency.

### Actual result:
The "No layer selected" alert appears and nothing happens to the raster mask.

### Additional info:
Other tools, such as the Gradient Tool and Brush Tool work correctly on the mask.

**Comment by photopea** [comment]
I am very sorry for the delay, it is fixed now, thanks for reporting :)
