### ISSUE TITLE
【BUG】Shortcut keys conflict between reverse selection and invert adjustment

### ISSUE THREAD

**Issue by vabaly** [photopea/photopea#2268]
Reverse selection's shortcut keys is `command + shift + I`，invert adjustment's shortcut keys is `command + I`，when I press `command + shift + I`, reverse and invert will exec at the same time.

**Comment by MichalSZZ** [comment]
I have same bug. Are you using Mac OS too?

**Comment by vabaly** [comment]
> I have same bug. Are you using Mac OS too?

Yes

**Comment by photopea** [comment]
If you press Ctrl + I, the "Inverse" will perform. You should press Shift before pressing I.

If you release Shift before releasing I, that problem should be solved now.
