### ISSUE TITLE
Bad interaction on mobile device

### ISSUE THREAD

**Issue by splincode** [photopea/photopea#227]
When I open a new project on a mobile device, in principle everything is convenient, except that I can not swap layers, because there is no Drag-and-Drop function for icons or the LayerUp / LayerDown button. Also, I can not select the tools that are grouped together, for example: Pen / FreePen, Gradien Tool / Paint Bucket Tool.

**Comment by photopea** [comment]
You are right. Let's fix it.

Layers Panel: Most of users would swipe over layers to scroll the list up and down. I think it can be disabled, so swiping would cause reordering. But what would be a good way to scroll then?

Toolbar:  the menu with tools is displayed "on mouse over" (which is not possible on a touchscreen). Maybe we can show it on click-and-hold ... ?

**Comment by photopea** [comment]
I implemented tap-and-hold for tools in a toolbar, so you can switch them on a touchscreen now.

I don't know what to do with swapping layers. There are much more features, that are impossible to do witout a mouse or a keyboard.
