### ISSUE TITLE
How do I get a save dialog?

### ISSUE THREAD

**Issue by jambalayadog** [photopea/photopea#2270]
Seems like the Save Dialog no longer appears and it just outputs a file without giving a me a choice of location or filename.

This behavior seems to have changed a few weeks ago, and is consistent along different browsers.  Save as PSD.  Export as PNG.

I can't use it without a Save Dialog.  The save action should not require additional manual user process.

**Comment by coolcraftnet18** [comment]
I think the developer should add a tick box option and an API option for the SaveAs prompt

**Comment by photopea** [comment]
Hi, the saving mechanisms depends fully on your web browser. You probably have "Save without asking" option enabled in your browser. You should enable "Show a save dialog" in your browser settings.

I really recommend everyone to learn about the settings of their browsers, as you usually spend thousands of hours in your browser over a year.

If you can not find the settings in your browser, tell us the name of your browser, and I will Google it, to find where these settings are located.

**Comment by lanadeldel** [comment]
> Hi, the saving mechanisms depends fully on your web browser. You probably have "Save without asking" option enabled in your browser. You should enable "Show a save dialog" in your browser settings.
> 
> I really recommend everyone to learn about the settings of their browsers, as you usually spend thousands of hours in your browser over a year.
> 
> If you can not find the settings in your browser, tell us the name of your browser, and I will Google it, to find where these settings are located (as every browser is a bit different).

When I use app.avtivedocument.save(), a save as psd dialog  will pop up, is there an api for the same to pop up a save as png dialog :)?

**Comment by photopea** [comment]
Are you using Photopea over the API? There is Web Messaging and the "saveToOE()" command for scripts.
