### ISSUE TITLE
Lag in Quality Percentage Adjustment

### ISSUE THREAD

**Issue by KallynDe** [photopea/photopea#2272]
When a project is created in photopea and exported, you have the option to adjust the quality from 0%-100%.  If the quality is left at default of 100%, it triples the size of the document (which is understandable).  However, adjusting the size via the slider bar takes for EVER.  I have a brand new Acer computer with fast internet, and yet trying to drag the slider bar to the appropriate quality sizing  I wanted took 15 minutes and stalled my computer and the browser (chrome) multiple times, and kept resetting to 50% when I wanted 90%.  I'm also not able to type in the percentage via the percentage window.  This CAN'T be normal!

**Comment by photopea** [comment]
Hi, could you tell us, what is the Width, the Height and to what format are you exporting?

If you export PNG, it takes about 0.5 seconds per million pixels. So if you have 4000 x 6000 pixels (24 million pixels), it will take 12 seconds. Exporting PNG is slow in all programs, not just Photopea. Exporting JPG is about 20x faster.

Also, update your web browser and disable all browser extensions, it could help.

**Comment by KallynDe** [comment]
The width is 4500 by 5400 pixels. If I export as ping, which I need to do for a project, and leave it at 100% quality, it exports at a maximum of 4 seconds(for a 34 MB pic). That part is crazy fast and not what is causing me the issue. Let's say I want the pic to be fewer MB. I would adjust the slider next to quality percentage when exporting the pic. Adjusting the SLIDER is what is taking forever. I have to repeatedly attempt to drag the slider, it stalls, I repeat the dragging, til finally the slider lands on approximately the right quality percentage. I thought it would be faster to type the percentage into the percentage text box, but it won't let me. This is with everything updated on my pc and nothing open but the photopea tab. I would expect the lag to be after I have the desired quality percentage and have hit the export button, not before when I'm still adjusting percentages, etc.

**Comment by photopea** [comment]
To be honest, I really think JPG would be more appropriate for a file like yours (the file will be smaller and with a better quality). The person who told you to use PNG is probably wrong.

The Quality slider looks and works a bit different in every web browser. But usually, you should be able to click at a new place and wait for the update (instead of dragging the slider). If you type in a percentage and press Enter, it should also update. But keep in mind, that each update will take over 10 seconds in your case.

**Comment by KallynDe** [comment]
Well...I wish Amazon Merch allowed jpeg, as you are definitely right...easier and smaller files. I should have added that I've also tried clicking on the bar, but that takes even longer, and sometimes the slider indicator bounces back from where I've clicked to 50%. If 50% were ok quality, I could live with it, lol, but it's not. I hear what you're saying, though. I will give each adjustment 10-30 seconds before getting annoyed with it ;-) . 

The reason I'm using photopea is that I need those exact dimensions in a png, and pixlr doesn't allow a creation bigger than 4095x4095. Their png format is not an export and does not give pics with huge file size, so except for the dimensions issue it would be perfect. 

I have a couple crop/resize tools on my computer, but the custom size selection has a default I can't override, where whatever size I enter ends up like 11 pixels off. Even one off and Amazon won't accept it. Makes me want to scream! Lol. Th for your help and suggestions! I will do my best to be patient and deal.

**Comment by photopea** [comment]
You can save a PNG at 100% quality and then, minify it here: https://tinypng.com/

**Comment by photopea** [comment]
By the way, what exactly are the requirements of Amazon Merch? Do they need PNG at 4500 by 5400 and do they have a size limit?

**Comment by KallynDe** [comment]
Thank you so much for the minify link!  The requirements of Amazon Merch for most of their items (front of zipped hoodie and front of pull over hoodie vary) is 4500x5400 exactly, png only, and a size no greater than 25 MB.

**Comment by photopea** [comment]
I made the PNG export 2x faster. Now, a photo of 5000x3000 pixels takes only 5 seconds instead of 10 seconds.

The PNGs can also be a little smaller after this update.
