### ISSUE TITLE
Export as... PDF - parameters in Save for Web window 

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2273]
1. If there is only one page (no any other artboards), the "Pages:" input fiels should be inactive (maybe with title in html element with information about why it is disabled). 
2. When I save print project as PDF (for example Bussines Card) I want to have info about size (width and height) in mm or inch in select field (now it is only % and px).

**Comment by photopea** [comment]
1. The "Pages" is hidden, when there is just one page.

2. You can switch to "in" and "mm" now. Note, that it shows the size of a whole document (it is a size of the page only if there is just one page). Note, that each page in a PDF can have a different size.
