### ISSUE TITLE
Photopea Hangs When Loading This Image

### ISSUE THREAD

**Issue by Abystus** [photopea/photopea#2274]
The website hangs and eventually locks up the browser attempting to load this image:

Dropbox Link:

https://www.dropbox.com/s/rkeqm5nr33ghqya/Test.jpg?dl=0

I tried on multiple browsers (Chrome, Firefox, Edge) and the outcome is always the same. I linked to my Dropbox as I didn't want to risk GitHub converting the image or doing something odd to it that would prevent the issue from happening.

**Comment by photopea** [comment]
Hi, I tried to open your JPG image in Adobe Photoshop and it crashed. Your JPG is damaged.

I also made Photopea recover, when the error such as yours occurs. It should work well now. But still, you should re-encode your JPG and use a correct version of it.
