### ISSUE TITLE
Can't See Or Edit Uploaded File

### ISSUE THREAD

**Issue by MuttonCutter** [photopea/photopea#2275]
![photopea_error](https://user-images.githubusercontent.com/67770058/86425297-5a978b80-bd17-11ea-8d66-da61b4c975db.png)

This is what I see when I upload a file. Can't zoom in or out. Can't edit the file at all. All I see is the black box. I uploaded a jpeg file, but somehow the file name reads "xxxx.psd" upon upload. Please advise. Thanks!

**Comment by photopea** [comment]
Hi, can you disable all browser extensions and try it again? Or try it in Incognito mode?

**Comment by MuttonCutter** [comment]
It works, thanks!
