### ISSUE TITLE
Why intro image not working?

### ISSUE THREAD

**Issue by ayaanahad** [photopea/photopea#2276]
Hi,
I properly used[ Environment](https://www.photopea.com/api/) JSON.

My site - [Photoshop Online](https://www.freeonlinephotoshop.com/) load with Photopea iframe. But not showing the intro screen. What has happened?

**Comment by photopea** [comment]
Hi, we allow only Distributors to hide the label "Photopea". I.e. you would have to pay for a distributor account.

You should not use a name "Photoshop" for your website, as it is a trademark of the Adobe company.
