### ISSUE TITLE
Coda caption o is the same as q

### ISSUE THREAD

**Issue by quantuminformation** [photopea/photopea#2277]
![image](https://user-images.githubusercontent.com/216566/86518698-94f64b00-be33-11ea-86ce-4a40438660fb.png)

**Comment by photopea** [comment]
Hi, I looked at the font Coda Caption. It is a pupular free font, which you can find on many places on the internet, e.g. here: https://www.1001freefonts.com/coda-caption.font . And indeed, the "picture" of a capital Q is the same as a picture for a capital O.

The font was made by Vernon Adams: @vernnobile . Maybe he can tell us more about it?

There is nothing we can do in Photopea about it. Photopea only renders fonts the way the author wanted them to be rendered.
