### ISSUE TITLE
(feature request) Save as PSB

### ISSUE THREAD

**Issue by thiscris** [photopea/photopea#2278]
Great application! I love it!
I am using it to generate some sprites for a Unity project. There is a plugin that allows to import PSB files preserving layers structure. Unfortunately, even though the plugin is called "PSD importer", importing PSD files is not as easy as PSB ones.

If your app had an additional option to export to PSB files, it would make my life easier.

**Comment by photopea** [comment]
Hi, that is very strange. Can you show us a PSB file, which works well in your plugin? If you open it in Photopea and resave as a PSD, are you sure the new PSD does not work in your plugin?

**Comment by thiscris** [comment]
Hi.
What I am asking for is to be able to export to PSB (the same way currently PSD, PDF, PNG, RAW and other formats are supported).
The plugin in question doesn't really work with PSD so I need to save in PSB something that is only 75 KB...

**Comment by photopea** [comment]
But can you show us any PSB file, which works well with your plugin?

Also, if you open that PSB in Photopea, export as PSD and rename it to something.PSB, does it work in your plugin?

**Comment by thiscris** [comment]
Alright. 
This is the example file I am testing with:
https://oc.unity3d.com/index.php/s/jwUEs5Z5HWQEe9l
1) I did as you suggested. Open in Photopea -> Save as PSD -> Rename to PSB (original file 385 kB, new file 336 kB )
it works ✅

Additionally I did the following experiments:
2) I opened the example file in Photopea, I added a new layer and used the paintbrush to draw something. Export->Rename to PSB
doesn't work ❌
3) Same as test 2, but instead of drawing in a new layer I used the paintbrush in an existing layer. Export->Rename to PSB
it works ✅
4) Same as test 2, but after drawing I merged that layer with the one above.  Export->Rename to PSB
doesn't work ❌

Honestly, at this point it could be as much fault of the plugin as Photopea.
The difference in the file size makes me think that PSD and PSB aren't 100% interchangeable.
Tests 2 and 4 make me think that layers might be saved differently.
Let me know if you can think of additional tests I can do.

**Comment by photopea** [comment]
Do you have access to Adobe Photoshop? Could you try to do the same things (2 and 4) in Photoshop and see if the file works in your plugin?

There is just a minor difference between PSD and PSB formats. PSD files produced by Photopea should be the same as those produced by Photoshop.

**Comment by thiscris** [comment]
Hi, apologies for the delay.
I got a photoshop generated PSB and test 2 works with it (I didn't bother with 4)
Here you can find the files used in the tests:
https://drive.google.com/drive/folders/1yNJg3FFVC7vlEjKrZeeo73XxuUouqGY7?usp=sharing
*Cop-newlayer.psb*
This is made with **Photoshop**, add a new layer, paintbrush (test 2 in Photoshop) - it works ✔️
*Cop-newlayer-Photopea.psb*
This is taking the file above in **Photopea**, save it as PSD and rename to PSB (same as test 1) - it works ✔️
*Cop-2-newlayers-Photopea.psb*
Open Cop-newlayer.psb in **Photopea**, add a new layer,  save as PSD, rename to PSB (test 2 in Photopea) - doesn't work ❌

**Comment by photopea** [comment]
The PSD which you made in Photopea and did not work in your plugin, could you do the same thing in Photoshop?

In your first test, you added a new layear and used a brush tool, while in case of Photopea test, you added a new layer and kept it empty. Maybe your plugin does not support empty layers.

Anyway, I will close it. I think PSD is much more "mainstream" than PSB, and you should ask the creator of your plugin to fix the PSD support in their plugin.

**Comment by thiscris** [comment]
My description earlier today was imperfect. I have edited my post.
 _Cop-2-newlayers-Photopea.psb_ does have some paint brush action, so the layer is not empty.
I had used white paintbrush, which is not very visible, but it still works for the test.

Since Photopea already allows for exporting to some more obscure formats like ppm and dds, and since you said that Photopea supports PSB (https://github.com/photopea/photopea/issues/2063#issuecomment-617366989) , I thought that adding another option to the export menu would not be a big deal.

I have shown with files _Cop-newlayer.psb_ and _Cop-2-newlayers-Photopea.psb_ that there are differences between saving a PSB file with Photoshop and saving a PSD file with Photopea and changing the extension. I can do nothing more about this.

**Comment by photopea** [comment]
Photopea supports PSB by opening PSB files.

Your plugin is the only software in the world, which supports PSB, while not supporting PSD. I think it is not right to make another export option just because of your plugin, even though others will not need it.

**Comment by photopea** [comment]
Hi, you can export PSB files from Photopea now: https://www.facebook.com/photopea/posts/2717607221833682
