### ISSUE TITLE
Circle select

### ISSUE THREAD

**Issue by rkeene** [photopea/photopea#228]
There appears to be no way to create a circular selection with Photopea

**Comment by photopea** [comment]
Hi, if you hold your mouse above the Rectangle select, the menu with appear with an Ellipse select. Hold Shift while drawing an Ellipse to draw a Circle.

**Comment by rkeene** [comment]
Holding down shift changes the mode to select addition as well

**Comment by photopea** [comment]
So I guess I can close it now.
