### ISSUE TITLE
FIG: rotated and cropped background images are rendered without rotate

### ISSUE THREAD

**Issue by sibbngheid** [photopea/photopea#2282]
example file: https://www.figma.com/file/hYsjgBALDIqp6cohqWLeIb/Untitled?node-id=0%3A1

result in photopea:
![image](https://user-images.githubusercontent.com/19991745/86951759-a18fe180-c15a-11ea-8fec-dc4ccacee06a.png)

without cropping, rotated images are fine. but when you also crop them, photopea ignoring rotation then crops on 0 rotation.

**Comment by photopea** [comment]
Hi, Photopea converts all images into PSD before opening them. These shapes of Figma are converted to vector shapes with a pattern fill, and pattern fills can not be rotated in PSD files.

Can you make a PSD file (in Photoshop or Photopea), which corresponds to this FIG file? I think it is impossible.

**Comment by hxim** [comment]
@photopea 
There is this new Rotatable Pattern feature in new Photoshop see here:
https://community.adobe.com/t5/photoshop/rotate-patterns-in-photoshop/td-p/11241977?page=1

**Comment by MichalSZZ** [comment]
@hxim nice info! Thanks for tip. I will update my PS on other computer and I will check this out.

**Comment by photopea** [comment]
I think your FIG file can not be converted into a corresponding PSD, because the standard PSD does not support rotated patterns. At the moment, I think it is not right to create PSDs which work only in Photoshop from June 2020.
