### ISSUE TITLE
Selection Channel

### ISSUE THREAD

**Issue by geyonk** [photopea/photopea#2284]
i make action then try open at photopea, but can't run.... after I checked, it turned out that no function for selection channel. Can u make that possible? thank's a lot
![Clip_56](https://user-images.githubusercontent.com/35011593/87109617-59261000-c28f-11ea-97fe-aec67f8d7e42.jpg)

**Comment by photopea** [comment]
Hi, can you share your .ATN file with us?

**Comment by geyonk** [comment]
[lumi mask.zip](https://github.com/photopea/photopea/files/4901414/lumi.mask.zip)
here the .atn
thank's for the response

**Comment by photopea** [comment]
Hi, I improved the support for this kind of actions. Your .ATN file should work well now.
