### ISSUE TITLE
what is a recommended way to export a single layer/object as PNG / SVG?

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#2285]
Hi.
It's a usual work scenario, when you need to extract various small icons from designer's PSD
To achieve this now for each item I do:

1. right-click item in the canvas to find the layer
2. if I'm saving a transparent PNG (or a GIF), I find all background layers that are behind this icon and hide them
3. crop canvas to this item (because save/export works with the size of the canvas): right-click the layer with the item, choose select pixels, then crop to the selection
4. if I'm saving to SVG, I delete all other layers (otherwise SVG will contain the info from all other layers and will be huge).

I suspect other people do it in some easier way, b/c I didn't find any posts about this here. There doesn't seem to be any "export layer / smart object as SVG/PNG" in right-click menu, but may be there's a way to do something similar that I'm just missing?

**Comment by photopea** [comment]
What you do is correct and it works.

When you have a Move tool, there are PNG / SVG buttons at the top, which will save currently selected layers as one PNG / SVG file. I usually select one or multiple layers, or a folder of layers, and click this button.

The smartest way: add "-e-" to the beginning of the name of layers, which you want to export. You can add it to folders of layers (if an exported element consists of multiple layers).  Then, press File - Export layers. It will export all such "-e-" layers in a ZIP archive.

Keep "-e-" layers in your PSD. If you modify something in the future, you can re-export all layers with one click (File - Export Layers).

**Comment by ewnjtgouierg** [comment]
ok sorry, finally checked the menu carefully and realized there's an "Export layers..." option
