### ISSUE TITLE
when panning with the hand tool mode sometimes a spinning mode is activated

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#2286]
it started relatively recently, I am not sure if it's some new feature and how do I manage to trigger it
I think I don't touch any keys, only using mouse to pan the canvas, but sometimes it starts rotating the canvas instead
it seems like it's a mode to view canvas rotated by arbitrary angle, because it is not an operation that you can undo
so I have to reload the PSD when this happens
what is this thing and how not to trigger it? thanks
sorry, I feel dumb :D

**Comment by photopea** [comment]
Hi, the Rotate View tool is just under the Hand tool. Did you click it? Or did you press the H button twice?

You can rotate back to 0 degrees by pressing the Reset button at the top (when the Rotate View is active).

**Comment by ewnjtgouierg** [comment]
yes, I hit H twice
I should have checked the top panel first to find out what's going on sorry

**Comment by photopea** [comment]
Hit H just once for a Hand tool, or hold a Spacebar as I do.
