### ISSUE TITLE
Export layers: problem with unicode characters in layers names?

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#2287]
my PSDs have lots of layers with non-English names, and the corresponding files in assets.zip get the mojibake names.
Same when using zip and 7z
Not sure if still may be I'm doing something wrong on my end, or it's a known thing that it's not supported? Thanks

**Comment by photopea** [comment]
It should be fixed now. Thanks for reporting!

**Comment by photopea** [comment]
I.e. text encoding should work well in new ZIP files made by Photopea.
