### ISSUE TITLE
Photopea Font change while exporting to pdf

### ISSUE THREAD

**Issue by yassine7999** [photopea/photopea#2288]
Hello,

I like photopea however there is one major problem. Some fonts change when i want to export my psd file to pdf. 
It is my Resume so I don't want to rasterize the text, because nowadays the resumes are going through kind of robots that analyze text on your resume and then decide if it goes to the human ressources or not. 

Is there someway to surmount this issue?

Thanks in advance,
Yassine

**Comment by photopea** [comment]
Hi, Photopea does not support a propper font export for PDFs at the moment.

All you can do is to rasterize or to vectorize the text. Maybe you could make your CV in programs like Word instead, and use graphics in it, which you made in Photopea.
