### ISSUE TITLE
What is the recommended way to export a vector object, that comprises multiple layers, as an svg?

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#2289]
When I want to export some vector icon, which is a combination of two or three layers, how should I do this?

If I merge them, the resulting figure is vector, but it is different from the original combination.

If I create a smart object from all the layers of the icon, it remains the same and has vector layers inside. But when I export the smart object's layer into an SVG, this SVG contains raster image, a rendering of the original vector layers. I couldn't find any settings in the export dialogue that one would expect to affect it. (Tried turning off "add raster graphics" thought, but that didn't help).

So I ended up exporting the layers individually and then editing svg to combine them in a way similar to how they were combined in the PSD. This is, of course, a difficult way.

I wonder if there's an easier one?

**Comment by photopea** [comment]
Hi, you can copy your layers into a separate empty document, and export with File - Export As - SVG.

You can also select multiple layers in the Layers panel, and press the SVG export button in the top menu (when a Move tool is chosen).

**Comment by ewnjtgouierg** [comment]
the second way is ideal, thank you!
