### ISSUE TITLE
I can't load sketch files

### ISSUE THREAD

**Issue by lowpiou** [photopea/photopea#229]
I've heard recently of your app and how it could help me convert sketch files.
However, none of the files i have tried have successfully loaded.
i chose the file from my computer, and then the "loading" bubble is there and that's it.

Can you help in any way ?
Thanks

**Comment by photopea** [comment]
Hi. Can you please send one of your files to support@photopea.com ?

**Comment by lowpiou** [comment]
Just sent it.
Thanks for your reactivity.

**Comment by photopea** [comment]
Hi, thank you very much for sending us your file.

It should be fixed now. Please check, if other files work too. If some of them does not work, send it to us again :)

**Comment by lowpiou** [comment]
Hi,

It worked with the file I sent you. I could export the psd. But had a weird bug then : Clicking in a text area made the text invisible. It’s still possible to highlight it, and change the color to make it reappear, but there’s no way to know for sure the original colors.
And there’s another fil I could not open at all :
https://we.tl/D29QCAKZYR

Thanks for time and your app, it’s really useful !


Laurent IGNACIO
Responsable Artistique

Pour un meilleur traitement de vos demandes, merci d'utiliser l'adresse support@aims-interactive.com<mailto:support@aims-interactive.com>
[cid:A48B4E1C-A6D3-4E38-A038-A80DFD4665AE]

Tél : 05 31 61 58 22
Standard : 05 31 61 58 20
[cid:CA1C13B9-17B1-424A-8B46-E21370126EFC]<http://www.aims-interactive.com/blog> [cid:1D4774AB-12C6-4173-AA8A-DDEC9E66B682] <https://www.facebook.com/AIMS-Interactive-Sp%C3%A9cialiste-e-commerce-Magento-144954825554887/>  [cid:9FBD36F2-39FA-43AA-9C92-14E762A0197F] <https://twitter.com/AIMSinteractive>



De : Photopea [mailto:notifications@github.com]
Envoyé : vendredi 21 juillet 2017 14:49
À : photopea/photopea
Cc : Laurent IGNACIO - aims-interactive.com; Author
Objet : Re: [photopea/photopea] I can't load sketch files (#229)


Hi, thank you very much for sending us your file.

It should be fixed now. Please check, if other files work too. If some of them does not work, send it to us again :)

**Comment by lowpiou** [comment]
Hi,

I could open the file today, thank you.
The text did not become transparent, but changed colors drastically (fluorescent green) in the case of unavailable fonts substituted by photoshop.
Your previous fix is fine for me but I thought I’d warn you about this new bug.

Thanks very much for your work, it’s a great tool !


Laurent IGNACIO
Responsable Artistique

Pour un meilleur traitement de vos demandes, merci d'utiliser l'adresse support@aims-interactive.com<mailto:support@aims-interactive.com>
[cid:A48B4E1C-A6D3-4E38-A038-A80DFD4665AE]

Tél : 05 31 61 58 22
Standard : 05 31 61 58 20
[cid:CA1C13B9-17B1-424A-8B46-E21370126EFC]<http://www.aims-interactive.com/blog> [cid:1D4774AB-12C6-4173-AA8A-DDEC9E66B682] <https://www.facebook.com/AIMS-Interactive-Sp%C3%A9cialiste-e-commerce-Magento-144954825554887/>  [cid:9FBD36F2-39FA-43AA-9C92-14E762A0197F] <https://twitter.com/AIMSinteractive>



De : Photopea [mailto:notifications@github.com]
Envoyé : vendredi 21 juillet 2017 20:10
À : photopea/photopea
Cc : Laurent IGNACIO - aims-interactive.com; Author
Objet : Re: [photopea/photopea] I can't load sketch files (#229)


Hi,
I could open your file (Cata_perso.sketch), but it took almost 40 seconds (there are many large bitmaps, that must be resized several times). I agree, that the speed should be improved.

I fixed the problem with transparent text, it sould work now. Thanks for reporting it :)

**Comment by photopea** [comment]
Hi, you are welcome?

Fluorescent green: are you talking about "Menu version finale V2.sketch", or another file ? Which text layer became green? 

Can you please give us a like at http://alternativeto.net/software/photopea/ ? thanks! :)

**Comment by lowpiou** [comment]
It was on « Cata_perso.sketch”
The layers for which I didn’t have the original font turned green. It’s the title layers, those that appear blue on the file. Layers for which I had the original font did not change colors.

Laurent IGNACIO
Responsable Artistique

Pour un meilleur traitement de vos demandes, merci d'utiliser l'adresse support@aims-interactive.com<mailto:support@aims-interactive.com>
[cid:A48B4E1C-A6D3-4E38-A038-A80DFD4665AE]

Tél : 05 31 61 58 22
Standard : 05 31 61 58 20
[cid:CA1C13B9-17B1-424A-8B46-E21370126EFC]<http://www.aims-interactive.com/blog> [cid:1D4774AB-12C6-4173-AA8A-DDEC9E66B682] <https://www.facebook.com/AIMS-Interactive-Sp%C3%A9cialiste-e-commerce-Magento-144954825554887/>  [cid:9FBD36F2-39FA-43AA-9C92-14E762A0197F] <https://twitter.com/AIMSinteractive>



De : Photopea [mailto:notifications@github.com]
Envoyé : lundi 24 juillet 2017 11:03
À : photopea/photopea
Cc : Laurent IGNACIO - aims-interactive.com; Author
Objet : Re: [photopea/photopea] I can't load sketch files (#229)


Hi, you are welcome?

Fluorescent green: are you talking about "Menu version finale V2.sketch", or another file ? Which text layer became green?

Can you please give us a like at http://alternativeto.net/software/photopea/ ? thanks! :)

**Comment by photopea** [comment]
Hi, I fixed the incorrect colors. Thank you very much for it! I would probably never notice it otherwise.

Let me know if you ever have any other problems.
