### ISSUE TITLE
Please don't exclusively offer a WASM version

### ISSUE THREAD

**Issue by wolfbeast** [photopea/photopea#2291]
There are numerous good reasons to keep WASM in browsers disabled, at which point photopea complains that the browser is "too old". Please consider offering a normal `asm.js` version of the application if WASM is found disabled in the browser, for maximum web compatibility.

**Comment by photopea** [comment]
I don't think there are any reasons to keep WASM or Javascript disabled in your browser. These technologies allow websites to become "interactive" and provide the actual software over the web.

Disabling Wasm while keeping Javascript enabled is really strange, as both technologies are equally "dangerous". I do not see any logic behind it. 

You could as well say, that we should make a version of Photopea for a browser from 2006. We can not make and maintain so many versions. We use the latest web standards for the best performance.

**Comment by wolfbeast** [comment]
I'm not talking about disabling javascript because that's nonsense if you want to have a web application.
I'm asking to have a WASM fallback to regular js, as in do not exclusively offer a precompiled WASM blob. This allows browsers to remain both more secure and to use a natively-compiled version of the web application which will simply be optimal, even if compiling it may take a few seconds on load (which is the only real advantage for using WASM over plain js from a browser perspective). Once compiled, performance will be exactly the same, and probably even better for the non-WASM version.
Ultimately it won't make a difference for your side; it will just be delivered in a different format but will be the same code.

> Disabling Wasm while keeping Javascript enabled is really strange, as both technologies are equally "dangerous". I do not see any logic behind it.

Please take some time to read up on the public criticism WASM has received, by which malware it is normally used, and why it has been, in fact put on ice as far as further development is concerned.

Ultimately it's your choice, of course, but I do really beg you to reconsider this.

**Comment by photopea** [comment]
The Wasm offers us many advantages. It is not only compiled faster, but it is also smaller than a corresponding JS version of the program (so Photopea loads faster over the network).

I have never seen any criticism of WASM and I think the articles that you read are misinformation. All you can do with WASM, you can also do with Javascript, so it is not any more "dangerous" than Javascript. We could even write a WASM interpreter in Javascript, which would run 100% the same as now, and you would not even know we are using WASM. But it would be quite slow.

**Comment by wolfbeast** [comment]
Misinformation? :D 
Well you can draw your own conclusions about how dangerous WASM is, I guess, and why it's a good idea to actually disable it in a browser even if a browser environment offers _some_ protection. Especially if you're dealing with jit-compiled interpreted WASM (as is the case in all major browsers) then a simple cast can already cause a vulnerability that punches right through any sandboxing that might be happening naturally -- because WASM simply doesn't offer the same kind of memory protection you'd expect from higher level languages. In-browser interpreters of WASM can only deal with the limited scope of WASM's linear (shared!) memory model, and as such it's risky to run WASM code in the browser from sources you don't trust.

Then there is the well-known problem of WASM-based cryptominers which by itself is already a good reason to not enable WASM in the browser.

But, don't take my word for it:
nVision/OWASP https://youtu.be/8DEw0CeQIZE?t=933

However, I understand that the problem is effort and money here. It's not my place to try and convince you otherwise if you are not concerned with browser security. I'm sure instructing people to temporarily enable WASM if they want to use your website is a decent compromise.

**Comment by photopea** [comment]
Your first video - Security Issues - by that, they mean the security of your program "not harming itself" - not rewriting your own memory.

Your second video - they only mention two bugs in Firefox, related to a WebAssembly execution, which has been fixed. The rest is a "scary talk", which should persuade you to buy their product - "browser in the cloud".

The fact, that there exist WASM cryptominers, does not mean anything. You can make a crypto miner in Javascript and it will run just as well.

I recommend you to read the specification to learn "what WASM is", instead of reading these pseudo-scientific articles about "how evil WASM is".
