### ISSUE TITLE
Editing template

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2293]
When editing template from Free Templates.
Save as PSD is disabled but Publish online > PSD is still enabled. I think it should be disabled too.

**Comment by photopea** [comment]
I disabled publishing a PSD for templates, too. Thanks for reporting it!

**Comment by MichalSZZ** [comment]
@photopea I can select all layers from template and make "duplicate into" and then Save without any problems. I think will be very hard to protect that files.
Dragging to other Tab etc.
