### ISSUE TITLE
Export to PNG is saving as a .txt file

### ISSUE THREAD

**Issue by leadhouse-kevin** [photopea/photopea#2294]
Unable to export an image as .PNG - Upon doing so, the downloaded file is a .txt

**Comment by photopea** [comment]
You are using a browser extension, which renames all files downloaded from websites. It is probably "Free download manager".

Do not use extensions, which rename downloaded files to .TXT, if you don't want the downloaded files to be renamed to .TXT

**Comment by leadhouse-kevin** [comment]
I use Photopea on a daily and I've never had this issue. Google Chrome, no browser extension.

**Comment by photopea** [comment]
Can you open chrome://extensions/  in your browser and send us a screenshot of what you see there?

**Comment by leadhouse-kevin** [comment]
![image](https://user-images.githubusercontent.com/64483333/87312511-a8b64700-c4ee-11ea-8ea1-42d5844c0cc6.png)

**Comment by photopea** [comment]
You are using eight browser extensions. Any of them can be renaming files.

Try Photopea in Incognito mode (where extensions are disabled) and see, if files are still renamed to .TXT

It is quite shocking, that people are using so many extensions and don't even know what they do.

**Comment by leadhouse-kevin** [comment]
Hey Ivan,

Been a big fan for a couple of years now.
I know I'm using these extensions, my point is none of them impact file downloads considering it's the same 8 extensions that have been there from me using Photopea hundreds of times!

In all cases, seems like me reporting an honest bug is annoying you more than anything else.

Have a good day

**Comment by photopea** [comment]
Please, try Photopea in Incognito window. I am 99% sure it is because of browser extensions.

**Comment by photopea** [comment]
In this issue: https://github.com/photopea/photopea/issues/2061 , the extension "Google docs offline" was renaming files form Photopea to .TXT. You are using the same extension.

Please, be aware, that anyone can make an extension that records a video of your screen, name it "Google Docs Offline", and millions of people will download it.

**Comment by aidinjk** [comment]
> Hey Ivan,
@leadhouse-kevin who is IVAN?
