### ISSUE TITLE
Paste doesn't works with PNG's 

### ISSUE THREAD

**Issue by naxxaxdev** [photopea/photopea#2295]
When i enter the page, and I try to paste some image, the page only generate an new layer, but not an image.
Also, the page doesn't give me some type of warn.
I think that only doesn't work with PNG.

By the way, excuse my poor English, im from Colombia.

I tried pasting a PNG Pac-Man and a JPG Pac-Man, and it crashes only with the PNG one.
I think there is also an issue that is really similar (#2294).
[Image](https://user-images.githubusercontent.com/67982073/87313859-1e6ae480-c4e8-11ea-984f-105bf6aa9c2f.png)

**Comment by photopea** [comment]
Hi, can you try the same thing in Incognito window? I think some of your browser extensions could be doing it.

**Comment by naxxaxdev** [comment]
Oh, it works in Incognito (In my case, InPrivate). I will try to delete all my extensions and see if it works!

**Comment by naxxaxdev** [comment]
No, it didn't work without the extensions.

**Comment by naxxaxdev** [comment]
Nevermind, it was the image! Thank you.

**Comment by photopea** [comment]
what do you mean it was an image? Let me know if there is anything else I can do for you.

**Comment by naxxaxdev** [comment]
Like, when I pasted the image, it didn't work. But when I pasted another image (Also as a PNG) it worked.

**Comment by photopea** [comment]
Can you open that wrong PNG image using File - Open? Does it work correctly?

**Comment by naxxaxdev** [comment]
Yes, it does. But when I only copy it and paste it doesn't work.

**Comment by photopea** [comment]
How do you copy it and where? If you select all in Photopea and press Ctrl+C, you should be able to paste it with Ctrl+V.

**Comment by naxxaxdev** [comment]
I enter in an image of google, i click the right button and I press "Copy Image". Then, I enter Photopea and I paste the image.

**Comment by photopea** [comment]
That should work, too. Unless you use some browser extensions which can break it.

**Comment by naxxaxdev** [comment]
Yeah, I uninstalled all the extensions.
