### ISSUE TITLE
when changing size of brush i get stuck + brush covers new size when using ALT

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2296]
Hi!

Here is the video explaining both glitches:
https://video.drift.com/v/abObkVTx2sG/

**Comment by photopea** [comment]
Hi, I fixed the issue with a red cursor covering the labels with numbers.

I can not reproduce the issue, when the brush preview stays after releasing Alt and a mouse button

**Comment by avagp** [comment]
the fix you did is a really good one. It really bothered me a lot.

And about the second one, don't know if it was related but, i still could
reproduce it, however now i can correct it if i press Alt again

SO everything is fixed by now.

Thanks!

**Comment by avagp** [comment]
I have to reopen this.

It is happening again.

How to repro:
0- Select brush tool
1- Hold Alt, now drag the cursor to change the size of the brush
2- Release Alt (and keep holding the cursor)
3- You'll get stuck on the size change animation

**Comment by photopea** [comment]
@avagp I think your issue is similar to this: https://github.com/photopea/photopea/issues/2551  and this : https://github.com/photopea/photopea/issues/2556 . 

What you say happens on Chromebooks (or on any device, which interprets Alt+click as a right click). Photopea will not work correctly in such evnironment.

Try to change the Chrome settings according to this: https://support.google.com/chromebook/thread/14888778?hl=en

**Comment by avagp** [comment]
Uhm...

Before changing anything, the tool worked perfectly for many months. This began happening a couple of  week ago.

I did change it, and now i don't get the size change animation.

So, i will turn it back.

:(

**Comment by photopea** [comment]
For the size change animation, you should hold Alt and right-click-and-drag the mouse, as in Adobe Photoshop.

Alt + left click with a brush is for picking the color (like an eyedropper tool).

**Comment by avagp** [comment]
Yes, i have always used it.
And worked like a charm.

But a couple weeks ago it changed its behaviour.
If you release the click before releasing the Alt button, the animation
will get stuck.

**Comment by avagp** [comment]
HJere is a video showing the bug:
https://video.drift.com/v/abcynf7A5rh/

**Comment by photopea** [comment]
I have watched your video. When you hold Alt and do a left-click with a brush tool, the red brush size modifier should not appear. It should appear only when you hold Alt and do a right-click.

As I said, I can not guarantee the correct functionality of Photopea on devices, where Alt+left click is not possible (in your case, Alt+left click performs a right click).

**Comment by photopea** [comment]
I recommend you to disable that "Alt+left click as a right click" feature, so that your Photopea works the same as Photopea of the rest of the world :)

**Comment by avagp** [comment]
Well, i changed it.

I cannot use the feature.

I believe because it is in beta it cannot take the Search+Left-click+Alt
Combo

Being Search+Left-click = Right-click

I hope you can change it back as it worked before, when i released either
the click or the Alt the size animation disappeared.

It worked before.

**Comment by photopea** [comment]
You should be able to do a right click with a mouse or a trackpad, without holding any additional keys on a keyboard.

**Comment by avagp** [comment]
No. Do you have the chromium issue to report this malfunction?

**Comment by photopea** [comment]
What do you mean No? You should be able to do a right-click with a two-finger tap on a trackpad.

The Chromium issue is here: https://bugs.chromium.org/p/chromium/issues/detail?id=248762

**Comment by avagp** [comment]
Ok, i couldn't do it.

I have to press and hold the 2 fingers on the trackpad to get it.

So i think it is solved by now.

Hope the right-click will be the default option in the near future, but for
me i will be sticking with this new configuration.

Thanks for your help, :D

I really appreciate it.

**Comment by photopea** [comment]
I can modify Photopea, so that instead of the right click, the brush size modifier will appear after holding some key on a keyboard and doing a left-click.

But the most important thing is, that all these features should work the same for everyone, for both you and me. Otherwise, it is almost impossible to discuss problems.

**Comment by avagp** [comment]
I totally understand that.

I didn't know that the brush size was modified by Right click + Alt. I
always thought it was left click + Alt.

The setting I have now is much better, I can use the other tools second
functions, like zoom out, or deselect.

So thanks for pointing out the chrome flag

Cheers!
:)

**Comment by photopea** [comment]
@avagp Did you ever use the Clone Stamp? It requires Alt + left click to choose a cloning source.

But I think I also allowed K + left click because of some Chrome user.

**Comment by avagp** [comment]
Yes, now i can use Alt.

:D

**Comment by avagp** [comment]
Chrome os has removed that flag i am afraid  :(

**Comment by avagp** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1129141

Let's fight for it
