### ISSUE TITLE
APNG support

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2297]
Will be great to have APNG support.

:)

That's all

**Comment by photopea** [comment]
Photopea has been supporting APNG for many years :) do you have any specific problem?

**Comment by avagp** [comment]
i suspected it, but the format is not shown on the export as... menu

can you set it there?

**Comment by photopea** [comment]
APNG is just an extension of PNG. Just like an animated GIF is an extension of a one-frame GIF, or animated WEBP is an extension of a one-frame WEBP.

You can open APNG in Photopea and export as GIF, or the other way. The mechanism of animations is described here: https://www.photopea.com/learn/animations

**Comment by photopea** [comment]
So export as a regular PNG (or GIF, or WEBP) even if you want an animation.

**Comment by avagp** [comment]
You are right. I didn't know

Thanks!
