### ISSUE TITLE
Relation to freeonlinephotoshop.com (and license in general)

### ISSUE THREAD

**Issue by myfonj** [photopea/photopea#2298]
Stumbled upon https://www.freeonlinephotoshop.com/ ([snapshot](http://archive.is/Wb2yB), [FB](https://www.facebook.com/pg/freeonlinephotoshop/about/)) what at this moment **embeds Photopea** [1] even with original branding with added info on the bottom of the page. It links photopea.com It's ["about" page](https://www.freeonlinephotoshop.com/about/) ([shot](http://archive.is/A0jNh)) reads

> [..] "It uses the API from Photopea, developed by Ivan. [..]

- I wonder if "Ivan" has any knowledge about that and if so whether there was any agreement with author of that page?
- I haven't found clear stance about license or more precisely if this kind of 'leach' is considered legal without author knowledge for this product?

[1] `<iframe src="https://www.photopea.com/#%7B%22environment%22:%7B%22menus%22:%5b1,1,1,1,1,1,1,1,1%5d,%22theme%22:1,%22vmode%22:1,%22icons%22:%7B%22intro%22:%22https://www.freeonlinephotoshop.com/assets/images/photoshop-intro.svg%22%7D%7D%7D" />`

**Comment by photopea** [comment]
Hi, this is a basic feature of the web - any webpage can embed any other webpage using <iframe>. You don't need an agreement to do it. It is similar to having a link to a website: [Youtube.com](https://www.Youtube.com) - I just made a link to Youtube without any agreement with Youtube.

Actually, 16% of our users use Photopea through sites like this. I don't think there is anything bad about it. Do you think there is?

**Comment by photopea** [comment]
That website freeonlinephotoshop.com has only 555 pageviews a month. There is also //photoshoponline.net.br, which has 267 000 pageviews a month (500x more).

**Comment by myfonj** [comment]
> I don't think there is anything bad about it. Do you think there is?

Well, not quite, and I applaud your open mind and generosity.  Thanks for claryfication.

**Comment by photopea** [comment]
No problem :) You can make a similar "mirror" of Photopea yourself, too :)

The main idea was, that people use Photopea as a plugin, and build many additional services around it.
