### ISSUE TITLE
error with layers

### ISSUE THREAD

**Issue by xsouto** [photopea/photopea#230]
hi, when i click on a layer to copy it, it delates it, please solve it

**Comment by photopea** [comment]
Hi, what do you mean? Are you talking about the right-click?

**Comment by xsouto** [comment]
yeah. thats it is

**Comment by xsouto** [comment]
yeah
only with the click it deletes it, i cant use it, sometimes creates a smart
object

2017-07-30 12:01 GMT+02:00 Photopea <notifications@github.com>:

**Comment by photopea** [comment]
Do you have Chrome OS?

**Comment by xsouto** [comment]
yes


2017-07-30 12:05 GMT+02:00 Photopea <notifications@github.com>:

**Comment by xsouto** [comment]
hey?


2017-07-30 12:06 GMT+02:00 Xsouto <elxabisouto@gmail.com>:

**Comment by photopea** [comment]
I think I fixed it. Can you try it now?

**Comment by xsouto** [comment]
no, is fixed

2017-07-30 13:09 GMT+02:00 Photopea <notifications@github.com>:

**Comment by photopea** [comment]
Another user with Chrome OS also confirmed, that it is fixed.
