### ISSUE TITLE
Ctrl+S not only saves the PSD, but also applies Splitting Open Paths

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2300]
Open a the file
[Logo Altiro (3).zip](https://github.com/photopea/photopea/files/4922335/Logo.Altiro.3.zip)

then pres CTRL+S, see what happens

**Comment by photopea** [comment]
Hi, that is an expected behaviour. Adobe Photoshop can not handle layers with many open paths, so we do it to make sure the PSD looks the same in Photoshop as in Photopea.

**Comment by avagp** [comment]
:o

Did not know
