### ISSUE TITLE
Allow for duplicating single layers using alt-drag and drop

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2301]
This is a minor feature request. (I would like this feature, but it's not of high priority for me.)

Using alt-drag and drop to duplicate layers doesn't work on a single layer because trying to duplicate a layer by alt-drag and dropping immediately below or above a layer fails.
____
_above Layer A_
#### Layer A
_below Layer A_
_above Layer B_
#### Layer B
_below Layer B_
____
When I alt-drag **Layer A** and try to drop in the area _above Layer A_ or _below Layer A_, nothing happens. However, when I try to alt-drag **Layer A** and drop in the area _above Layer B_ or _below Layer B_ instead, **Layer A copy** appears above or below **Layer A**, respectively, as is expected.

____
_above Layer A_
#### Layer A
_below Layer A_
____
This means that when I only have one layer, as shown directly above, I cannot duplicate it using the alt-drag and drop method. I can use ctrl-J to create a **Layer A copy** above **Layer A** and then drag the duplicate layer below the original layer if I need to, but alt-drag and drop would take only one step whether I want the duplicate layer above or below.

**Comment by photopea** [comment]
I think I have fixed it. Can you check it?

**Comment by dentistformyeye** [comment]
It works. Thank you!
