### ISSUE TITLE
Layer reordering issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2302]
When reordering layers I put my layer in the top (see screenshot)
![image](https://user-images.githubusercontent.com/6370548/87645767-3e034680-c74e-11ea-9933-ebb8666a122d.png)
->
![image](https://user-images.githubusercontent.com/6370548/87646137-b0742680-c74e-11ea-8ca3-055bf2b617e1.png)
but after I released mouse it appeared in the bottom (in this case below background layer)
It seems there is 1px area in the top of layers window where if I put it there it will reorder layer to the bottom.

**Comment by photopea** [comment]
Hi, I fixed it just by changing CSS :)
