### ISSUE TITLE
When using Quick Select it isn't working like a brush and just selecting the whole image

### ISSUE THREAD

**Issue by stephensixthsense** [photopea/photopea#2303]
When I am trying to use Quick Select I drag it a tiny bit and then it will select the whole image.

**Comment by photopea** [comment]
Hi, what will select the whole image? Could you describe what you mean or maybe record a short video?

**Comment by stephensixthsense** [comment]
When I use the quick selection tool using the W key. I have watched a tutorial on how to use it and they seem to be able to brush over which part of the image they would like to select. When I try to do the same thing it will select the whole image. 

![image](https://user-images.githubusercontent.com/63402073/87668641-59794c00-c764-11ea-8a7d-23901702b1d8.png)

**Comment by photopea** [comment]
You should use both Add and Subtract modes of Quick Select. It is nomal, that sometimes, it selects more than you want.

See our tutorial about Quick Select  https://www.photopea.com/learn/advanced-selecting  , or see the Adobes description of Quick Select.

**Comment by stephensixthsense** [comment]
I understand that it selects more than what I want but the issue I am having is that it is selecting sections of my image that are nowhere near where I am brushing. It either selects parts of the image from an opposite side or selects the whole image.

**Comment by photopea** [comment]
It selects them, because they are similar to what you are selecting at the moment. I know, that it does not work as well as in Photoshop, but I don't know how to make it better :(

**Comment by stephensixthsense** [comment]
Ah that;'s alright, I was just reporting it in case it was a bug! Still works well :)

**Comment by photopea** [comment]
If you use a subtract mode a couple of times, you should be able to select what you wanted to select.
