### ISSUE TITLE
UI has blank panel

### ISSUE THREAD

**Issue by tiltos** [photopea/photopea#2305]
Currently I have a large panel on the right handside that is blocked out. This happens no matter the width of the viewport, as well when its a standalone app.

![image](https://user-images.githubusercontent.com/259111/87735253-5b044c00-c818-11ea-8234-746aa690e91e.png)

Browser is Brave Version 1.11.97  (Chromium: 84.0.4147.89 (Official Build) (64-bit))

**Comment by photopea** [comment]
Hi, there should be an advertisement on the right side. Your device is probably trying to remove the advertisement from our website.

Since there are too many people blocking ads, and almost nobody pays for a Premium account, now, Photopea will ask you to stop blocking ads.
