### ISSUE TITLE
Adblock issue?

### ISSUE THREAD

**Issue by tiefbard** [photopea/photopea#2306]
I use an adblock and despite turning it off on Photopea I still get no ads and a pop-up stating that I'm still using an ad-block.
I love using Photopea so I don't mind getting some ads, is there anything I can do to fix this?

**Comment by photopea** [comment]
That is strange. But are you seeing ads on the right side? Can you try Photopea in Incognito mode?

**Comment by tiefbard** [comment]
![image](https://user-images.githubusercontent.com/68423938/87776473-ba198f00-c81f-11ea-9d2e-9f85f938cbfd.png)
this is with an incognito mode, no visable ads but no pop-up
![image](https://user-images.githubusercontent.com/68423938/87776533-d7e6f400-c81f-11ea-85f6-a31c2382f1fd.png)
this is a normal new tab, no ads and i get this popup

sorry i shouldve added more info :+1:

**Comment by photopea** [comment]
If you do not see any message in Incognito mode, that means, that some of your browser extensions is rewriting Photopea code.

Try to disable all browser extensions and let me know if you still see the message. You should know about all your extensions, which are allowed to rewrite websites.

**Comment by tiefbard** [comment]
i disabled all of my extensions one by one to see which one of them it was, but i'm still getting the issue
i use firefox, if that helps?

**Comment by photopea** [comment]
So there is no message in Incognito mode, but you see it in a normal mode
with no extensions? Can you try the incognito mode again?

pátek 17. července 2020 tiefbard <notifications@github.com> napsal(a):

**Comment by tiefbard** [comment]
![image](https://user-images.githubusercontent.com/68423938/87782539-9a3b9880-c82a-11ea-8d25-07943bbdf5fb.png)
here's another screenshot of a new incognito window, no popup or ads

**Comment by photopea** [comment]
Look into your Firefox settings, Privacy & Security. I think you enabled blocking some domains, which are used by our ads.

**Comment by tiefbard** [comment]
that fixed it thank you for your help!

**Comment by photopea** [comment]
no problem :)
