### ISSUE TITLE
Mask Alt Shift combination Bug

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2308]
1. Make some mask on layer
2. Click on layer mask thumbnail with Alt
3. Click on layer mask thumbnail with Shift

Canvas preview switch to hmm... something like quick mask mode (semi-transparent red) but it isn't a quick mask.

**Comment by MichalSZZ** [comment]
Or it isn't a bug - just hidden feature? ;)

**Comment by photopea** [comment]
This is a feature, that is also in Adobe Photoshop. See here: https://helpx.adobe.com/photoshop/using/masking-layers.html  - "Select and display the layer mask channel"

You can view any channel this way (in Window- Channels). The Quick Mask mode is just making a channel from a selection and setting its view to a "rubylith".
