### ISSUE TITLE
Incorrect Adblocker detection + bug with tools in combination with adblocker pop-up

### ISSUE THREAD

**Issue by JamesAnnoyed** [photopea/photopea#2311]
I do not run an adblocker of any kind, yet I get this very annoying pop-up all the time, I even installed an ad blocker and disabled it, but did not help.

The issue is when you are using a tool while holding the left mouse button the action goes through the whole artwork and is not registered in the history, which meant hours of work lost. yes, i forgot to save every min....

I really hope that is not on purpose

**Comment by photopea** [comment]
Hi, any browser extension can rewrite any website in any way it wants.

Try to run Photopea in Incognito mode (i.e. with all extensions disabled). Let me know if you still see that message about blocking ads.

**Comment by photopea** [comment]
As the author of the issue does not respond, I think it has been fixed by removing a problematic extension.
