### ISSUE TITLE
Content-Aware Scale issue 2

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2313]
Go to pea.psd
Select "top bar" layer
Edit Content-Aware Scale
Resize to about 800 x 400 pixels size
Transparent (or white) stripe appeared in the middle of image as seen on screenshot:
![image](https://user-images.githubusercontent.com/6370548/88017279-a58e0d00-cb25-11ea-8338-42f955c0e3dc.png)

**Comment by photopea** [comment]
fixed, thanks! :)
