### ISSUE TITLE
fail to open PSD archives from Google Drive

### ISSUE THREAD

**Issue by producao21ieq** [photopea/photopea#2314]
when i started photopea to edit a PSD archive in the Google Drive, doesn't open the file, show a message "unknow JSON file opened. see the content in the console. and i can't work, because all my work is collaborative and we need keep de files in google Drive for all team.

**Comment by photopea** [comment]
Hi, can you try to disable all browser extensions, or try it in Incognito mode?

Also, when Photopea starts, did you see a popup window about allowing Photopea to access your Google Drive? Did you confirm it?

**Comment by photopea** [comment]
I have to close it because of lack of details.
