### ISSUE TITLE
GIF is generating a line on the top

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2315]
Hi, here is the animation i am working on, and when i export it to GIF it makes a like on the top on the tail.
![C - medel](https://user-images.githubusercontent.com/11801254/88127297-4d94ec00-cba1-11ea-9572-fb1b0ed853f5.png)
[C - medel.zip](https://github.com/photopea/photopea/files/4957498/C.-.medel.zip)

**Comment by photopea** [comment]
Hi, btw. you exported a PNG (APNG), this bug is related to a PNG format, not GIF.

I fixed the bug, the APNG animation should be correct now.

**Comment by avagp** [comment]
Yes, it is apng.

I just used it as synonym

**Comment by photopea** [comment]
APNG is a lot different than GIF :)  GIF can use only 256 different colors in it (a palette of 256 colors), while APNG can have up to 16 million colors (like PNG).

GIF can have only fully transparent or fully opaque pixels, while APNG can have 256 levels of transparency (like PNG).

When exporting APNG, try to set the quality to 30 - 50%. It usually makes the file 2x maller, and often, you don't even notice the slightly worse quality.
