### ISSUE TITLE
WebGL in iOS 14 Safari

### ISSUE THREAD

**Issue by amonforstmann** [photopea/photopea#2316]
WebGL Mode in iOS (14) Safari just gives me am empty canvas.
I enabled WebGL 2.0 for Safari.

The non-WebGL mode works fine but slowly.

<img width="683" alt="PNG-Bild" src="https://user-images.githubusercontent.com/1593803/88158231-11e33c00-cc0c-11ea-8553-a161706741ac.png">

**Comment by photopea** [comment]
Hi, that is very strange, as there are hundreds of thousands of people using Photopea in iOS. Does it happen for any file you open in Photopea, even for small files 100 x 100 pixels?

Photopea uses WebGL 1.0, your browser does not need to support WebGL 2.0.

**Comment by amonforstmann** [comment]
Hi, I tried disabling WebGL 2.0 - still no luck.
But this is on the iOS 14 Beta. I will try a regular (iOS 13) device later.

**Comment by photopea** [comment]
Photopea usually does not work well in beta browsers or beta operating systems.

if you are using Beta, you probably expect some things not to work :) so you have to choose, whether you want everything to work, or you want to use Beta.

I am sure that everything will work well in a normal environment, so I will cose it now.
