### ISSUE TITLE
Shift + Enter doesn't break a text line

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2317]
It should only break a line. In Photopea (or in text maked in Photoshop and opened in Photopea), it's make a new paragraph.

**Comment by photopea** [comment]
I was not aware of this functionality of Photoshop. I thought the number of paragraphs corresponds to the number of newline characters.

This goes much deeper into our text engine. If you have a PSD with five newlines (made with Shift+Enter), but just one Paragraph, Photopea will render it as five paragraphs (i.e. differently than Photoshop).

It is quite hard to fix, so I will close it for now, until more people report it.

**Comment by MichalSZZ** [comment]
@photopea  OK. I understand. Thanks for the answer. 

Shift + Enter works in many aplication in that way. That is a main feature for people who working with text (Word or any other text editor). Even for designers :) 
It is a simplest way to manualy break the line if you don't want to leave conjunctions at the end of the line.
In Polish spelling rules (I don't know about other languages), you shouldn't leave conjunctions at the end of the line. The simplest method is to simply break the line manually with Shift + Enter. An unbreakable space should be the most correct. In HTML I use <br> to break the line or &nbsp; for replacing space if I need to correct it manualy and text should to look good even in RWD.

Sometimes at the end of work with designs with text people want's to correct Widows, Orphans and Conjunctions ath the end of the line.

**Comment by MichalSZZ** [comment]
In Photopea I use "Paragraph Text" for long text or lists and use distances between paragraphs (I set it in paragraph pallete - distance in px in begining or at the end of next paragraph)
