### ISSUE TITLE
Save to google drive isn't working.

### ISSUE THREAD

**Issue by BMG309** [photopea/photopea#2318]
After clicking save to google drive, it shows aww snap and are forced to reload the page.

**Comment by photopea** [comment]
What format is your image? Is it PSD? Does saving a PSD locally to your computer work?

**Comment by BMG309** [comment]
Yes it is a psd. It works to save locally no problem, the only issue is to
save to google drive.

**Comment by photopea** [comment]
It is very strange. How large is your PSD when you save it to your computer? Can you disable all browser extensions and try again?

**Comment by photopea** [comment]
I have to close it because of lack of details.
