### ISSUE TITLE
Keyboards

### ISSUE THREAD

**Issue by realrish15** [photopea/photopea#2319]
My backspace and controls isn't working in Photopea. Can it be fixed?

**Comment by photopea** [comment]
Hi, can you try this demo: http://jsfiddle.net/p45f44zb/14/ ? Click into the white area and press various keys. Does it show the keys which are pressed at each moment?

**Comment by realrish15** [comment]
No. It wasn't. What showing was null.

**Comment by photopea** [comment]
There is something wrong with your browser. What browser are you using? What version?

**Comment by realrish15** [comment]
Ohh. I got it. I was using the microsoft edge earlier. And I just
downloaded the google chrome and it's working now. Thank you. You're a big
help!

**Comment by photopea** [comment]
I think you were using the Edge, which is three years old (a default part of windows 10). You should update it here: https://www.microsoft.com/en-us/edge

Photopea works in all browsers. They just need to be updated.
