### ISSUE TITLE
Translate user modal

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#232]
It still in english for all languages.
![snimek obrazovky 2017-08-06 v 23 55 28](https://user-images.githubusercontent.com/3184228/29007401-d2118a58-7b02-11e7-9fbb-75c419dc792d.png)

**Comment by photopea** [comment]
Most of our users know English, I think we can keep it in English at this point.

**Comment by landsman** [comment]
GA said same information?

**Comment by photopea** [comment]
Yes, seems like 67 % of users speak English: http://i.imgur.com/4UhDTK5.png

**Comment by landsman** [comment]
What about Spanish or Russian?

**Comment by photopea** [comment]
It is the number of pageviews, not visitors. So it can be 1000 views from 10 visitors :)  I would wait, until it is at least 50 000 visits / month form that country.
