### ISSUE TITLE
color palette

### ISSUE THREAD

**Issue by erst1** [photopea/photopea#2320]
the screen shows the place where the color palette should be, why is it not there?

https://ibb.co/PcbXfwg

**Comment by photopea** [comment]
Hi, I guess you mean why our menu is not identical to Adobe Photoshop. We just thought it is not important. You see the preview of the image in front of you, that is all you need, or not?

**Comment by erst1** [comment]
I need this in order to select the desired color, this is how the
"properties" window should look like
[image: 3423d9e27f5c041c5d45916fd3a6f5fe.jpg]

чт, 23 июл. 2020 г. в 17:25, Photopea <notifications@github.com>:

**Comment by photopea** [comment]
I dont think it is important to have the menus 100% identical to Adobe Photoshop. That "rainbow" only shows how the Cyan color would change.
