### ISSUE TITLE
Transform Outlines and Guides Disappear in Safari

### ISSUE THREAD

**Issue by dandixon16** [photopea/photopea#2321]
I’ve used photopea for months with Chrome, no major problems. I use hotkeys H and V to toggle between “Rotate View” and “Move Tool” regularly. In Safari, when switching back to V (from H), the layer’s transform outlines no longer appear, so I can’t click/transform/rotate the layer at all. I can still click on the layer and drag it to reposition it, but all the trasnform options no longer show up.

Oddly, they only show up at the very beginning of working on something. The moment I toggle out of “Move Tool” and then back into it, the transform outlines are gone for good.

Thank you!

**Comment by dandixon16** [comment]
smh i had “Transform Controls” deselected… so dumb of me. Still - strange that they show up at first, but then never again unless you have “Transform Controls” selected.

**Comment by photopea** [comment]
Hi, the "Transform Controls" are disabled, when you open www.Photopea.com for the first time.

So maybe you cleared the memory of your browser. Or you use some browser extension, which clears it (to prevent "tracking").

**Comment by dandixon16** [comment]
> Hi, the "Transform Controls" are disabled, when you open [www.Photopea.com](http://www.Photopea.com) for the first time.
> 
> So maybe you cleared the memory of your browser. Or you use some browser extension, which clears it (to prevent "tracking").

you’re exactly right — i realized that JUST after I posted this thread, my bad! I’d been messing around with photopea for a whiiiile before I saw that tick box. right before my eyes, smh…

thanks for you that prompt help tho!
