### ISSUE TITLE
"Your browser is modifying our code"

### ISSUE THREAD

**Issue by JCVogelsberg** [photopea/photopea#2322]
Whenever I try to open a file to edit (jpg, png, pdf), i get an error "your browser is modifying our code."

Browser: Google Chrome, Version 84.0.4147.89 (Official Build) (64-bit)
![Screen Shot 2020-07-23 at 2 14 15 PM](https://user-images.githubusercontent.com/4934923/88339404-d66d6e00-ccee-11ea-98f0-ae37c32fc9cc.png)

**Comment by photopea** [comment]
Hi, I would recommend using a browser, which does not modify the code of Photopea.

But it is also possible, that some of your extensions are modifying the code of Photopea. Can you try to disable them?

**Comment by olegivashko** [comment]
I have the same issue. No new extension has been added. Your application gives the same result.
The previous week it worked ok. Today I see this response for the first time.

**Comment by photopea** [comment]
@olegivashko have you tried to disable all extensions, or the Incognito mode?

**Comment by olegivashko** [comment]
It seems I found the reason. 
https://chrome.google.com/webstore/detail/selenium-ide/mooikfkahbdckldjjndioackbalphokd
I removed this extension.
Now both site and Photopea application are ok.

**Comment by photopea** [comment]
You should at least write them a negative review, that they break Photopea by dredefining window.confirm .

**Comment by olegivashko** [comment]
related issue - https://github.com/SeleniumHQ/selenium-ide/issues/1100

**Comment by photopea** [comment]
I will close it now.

**Comment by JCVogelsberg** [comment]
Why did you close this thread? The issue is not fixed. I do not have The Selenium extension. This issue persists in incognito mode where NO extensions are enabled.

**Comment by photopea** [comment]
@JCVogelsberg  Are you 100% sure, that it happens in Incognito mode? Could you check it several times?

Are you sure all extensions are disabled in your Incognito mode? I think Chrome allows using some extensions in Incognito.

Could you at least disable all extensions and reload Photopea?

**Comment by photopea** [comment]
@olegivashko I managed to fix it. If we do not detect, that you are blocking ads, your browser or extensions are allowed to redefine window.confirm() . So the Selenium extension works well in Photopea now.
