### ISSUE TITLE
Text layer must be rasterized in order to delete it?

### ISSUE THREAD

**Issue by flleeppyy** [photopea/photopea#2323]
I'm trying to delete a text layer, but it keeps telling me to rasterize it before I delete it, which is really dumb...

![image](https://user-images.githubusercontent.com/18307183/88350570-57852f00-cd08-11ea-8051-30ab9d3b1de3.png)

Browser: Firefox 78.0.2 (64-bit)
OS: Kubuntu 20.04 LTS

**Comment by photopea** [comment]
Hi, how do you try to delete a text layer? 

You are probably pressing the Delete key on your keyboard. But you probably have a selection. It that case, the Delete key is used to clear (erase) the selected pixels, wich can not be done in a text layer (until you rasterize it).

To delete layers, use a garbage bin at the bottom of the Layers, or use Layer - Delete.
