### ISSUE TITLE
Customizable Keyboard Shortcuts

### ISSUE THREAD

**Issue by flleeppyy** [photopea/photopea#2324]
I'm a Linux user (Kubuntu fan), and some of the keyboard shortcuts that are predefined by Photopea, conflict with KDE.
For example, Alt + Ctrl + T, which is supposed to be Free Transform, opens up Konsole.

Being able to change shortcuts so they don't conflict with our OS would be great!

**Comment by photopea** [comment]
Hi, it is not possible to customize keyboard shortcuts at the moment. I dont think it would be useful. Our shortcuts are those used in many other image editors. It can be useful, when you switch to another editor, and don't have to re-learn or re-configure shortcuts.

I think it can be considered as bug in your browser / KDE. The keyboard input should be "consumed" by a website, and not propagated outside the browser. The same happens with mouse input: when you click at the top left corner, the click should be consumed by the active program (web browser) and not e.g. open a file, which is at the same coordinate on your desktop.
