### ISSUE TITLE
Font does not appear

### ISSUE THREAD

**Issue by Hollowfox97** [photopea/photopea#2326]
Hello, ever since Photopea is based on Photoshop, I was excited, but two flaws has kept me from using the website. Fonts are invisible and the text wasn't shown. This was supposed to be important for some graphic design stuff and I want the people behind the website to fix it.

Or is there any way to fix the problem?

**Comment by photopea** [comment]
Hi, Photopea is not based on Photoshop. What does it even mean?

Try to disable all browser extensions and try it again. Or try Photopea in Incognito mode, where all extensions are disabled.

**Comment by Hollowfox97** [comment]
If that wasn't based on Photoshop, why does it look like it?

**Comment by Hollowfox97** [comment]
Also, even in incognito mode, the text still doesn't show

**Comment by photopea** [comment]
What browser and the version do you use? Can you update it?

**Comment by Hollowfox97** [comment]
I use Google Chrome. Version 84.0.4147.89 (Official Build) (64-bit).

**Comment by photopea** [comment]
Can you try to open a Demo: "pea.psd", that is in the middle of Photopea, and edit the text in it with a Type tool? Can you record a short video of what happens?

**Comment by photopea** [comment]
I have to close it because of lack of details.
