### ISSUE TITLE
List of all cursor issues

### ISSUE THREAD

**Issue by Romarain** [photopea/photopea#2327]
I noticed that the _Paint Bucket Tool_ cursor was the same one that my normal mouse. It disturbed me.

So I tested all the tools and **here's the list, with comments about each of every one from the top to the bottom of the actual toolbar**. I don't know how cursors are managed, and if they are based on Windows' ones (so it may be limited), but if this is possible, those marked as "NOT OK" should be revised to improve ergonomics.

- **Selecting/Moving (V)** : REGULAR mouse cursor => _OK, but should be a black cursor with a cross sub-icon_
- **Rectangle Select (M)** : CROSS cursor => _PERFECT_
  - **Ellipse Select (M)** : CROSS cursor => _PERFECT_
- **Lasso (L)** : CROSS cursor => _OK even if not Photoshop original one's._
  - **Polygonal Lasso (L)** : CROSS cursor => _OK even if not Photoshop original one's._
  - **Magnetic Lasso (L)** : CROSS cursor => _OK even if not Photoshop original one's._
- **Magic Wand (W)** : REGULAR cursor => _**NOT OK**. Confusing with "**not having a tool selected**"._
  - **Object Selection (W)** : REGULAR cursor => _**NOT OK**. Confusing (same)._
  - **Quick Selection (W)** : CIRCLE cursor => _OK._
- **Crop Tool (C)** : CROSS cursor => _**NOT OK**. Original one should be prefered._
  - **Perspective Crop (C)** : CROSS cursor => _**NOT OK**. Original one should be prefered._
  - **Slice Tool (C)** : REGULAR cursor => _**NOT OK**. Confusing._
  - **Slice Select Tool (C)** : REGULAR cursor => _**NOT OK**. Confusing._
- **Eyedropper (I)** : REGULAR cursor => _**NOT OK**. Confusing._
  - **Ruler (I)** : REGULAR cursor => _**NOT OK**. Confusing._
- **Spot Healing Brush Tool (J)** : CIRCLE cursor => _OK._
  - **Healing Brush Tool (J)** : CIRCLE cursor => _OK._
  - **Patch Tool (J)** : REGULAR cursor => _**NOT OK**. Confusing._
  - **Red Eye Tool (J)** : CIRCLE cursor =>_OK._
- **Brush Tool (B)** : CIRCLE cursor =>_PERFECT._
  - **Pencil Tool (B)** : CIRCLE cursor =>_PERFECT._
  - **Color Replacement  (B)** : CIRCLE-LIKE cursor =>_PERFECT._
- **Clone Tool (S)** : CIRCLE cursor => _PERFECT._
- **Eraser Tool (E)** : CIRCLE cursor => _PERFECT._
  - **Background Eraser (E)** : CIRCLE cursor => _PERFECT._
- **Gradient Tool (G)** : REGULAR cursor => _**NOT OK**. Confusing._
  - **Paint Bucket Tool (G)** : REGULAR cursor => _**NOT OK**. Confusing._
- **Blur (??)** : CIRCLE cursor => _OK._
  - **Sharpen (??)** : CIRCLE cursor => _OK._
  - **Smudge Tool (??)** : CIRCLE cursor => _OK._
- **Dodge (O)** : CIRCLE cursor => _PERFECT._
  - **Burn (O)** : CIRCLE cursor => _PERFECT._
  - **Sponge Tool (O)** : CIRCLE cursor => _PERFECT._
- **Type Tool (T)** : REGULAR cursor => _**NOT OK**. Confusing._
- **Pen (P)** : REGULAR cursor => _**NOT OK**. Confusing. Original one should be prefered._
  - **Free Pen (P)** : CROSS cursor => _**NOT OK**. Confusing. Original one should be prefered._
- **Path Select (A)** : REGULAR cursor => _**NOT OK**. Confusing because it should be **black**._
  - **Direct Select (A)** : REGULAR cursor => _**NOT OK**. Confusing because it should be **alternative**._
- **Rectangle (U)** : CROSS cursor => _PERFECT._
  - **Ellipse (U)** : CROSS cursor => _PERFECT._
  - **Line (U)** : CROSS cursor => _PERFECT._
  - **Parametric (U)** : CROSS cursor => _PERFECT._
  - **Custom (U)** : CROSS cursor => _PERFECT._
- **Hand Tool (H)** : HAND cursor => _PERFECT._
  - **Rotate View (H)** : HAND cursor => _OK, but should be a hand with rotation arrows sub-icons._
- **Zoom Tool (Z)** : MAGNIFYING GLASS cursor => _PERFECT._

As you can see, the main problem (to me) is when the REGULAR cursor is used in place of a tool that should have its own cursor : because it induces confusion with a bug **as if we hadn't selected a tool**.

**Comment by photopea** [comment]
Hi, do you know someone who could draw these new cursor for us? Could you draw them?

**Comment by MichalSZZ** [comment]
@photopea  What file format do you use? SVG? Do you have any of cursor used in Photopea to show us the structure and style?

**Comment by photopea** [comment]
We don't have any images for custom cursors at the moment. What if we a tiny arrow plus the icon of the tool (that you see in a toolbar) next to it?

**Comment by MichalSZZ** [comment]
> What if we add a tiny arrow plus the icon of the tool (that you see in a toolbar) next to it?
For me that isn't a problem if some of tools (like paint bucket tool) have not the same icon as in Photoshop. 
The biggest problem are + - * for tools like all the Selection Tools, Shape tools (but for now adding two shapes in drawing mode isn't possible yet in Photopea), Pen tool (adding and removing points) etc. That is UX problem when I use keyboard shortcuts with tool (ctr, shift, or combinations) and I don't see it on cursor.

I remember that for you, the problem of custom cursors is in lags in Photopea, when you change for own icon - not default of browser ones?

**Comment by egnucledge** [comment]
Would it be possible to make the Lasso Select cursor something with a point, like an arrow? The crosshairs work great for square and round selections, but I primarily use the Lasso Selection tool to cut out freeform shapes, usually by tracing around the edge of objects. The crosshairs make it hard to see exactly where I am on an image. With a pointed cursor, I can be more precise.

**Comment by photopea** [comment]
I will close it, as I think it is not necessary to have a different cursor for each tool, and the original person, who posted it, never joined our discussion.

**Comment by Romarain** [comment]
Sorry for not joining the discussion, I don't read my mails since years.

> Could you draw them?
Depends : if you propose me a **free subscription account for life** on Photopea, I could give it a try.

> We don't have any images for custom cursors at the moment.
It's strange, given that you already have some Photoshop icons (or similar to) in your product.

> as I think it is not necessary to have a different cursor for each tool
At the contrary, it's very, very, VERY, important. Especially if the actual icon of a tool can be totally confused with the arrow we have in MS Windows.
