### ISSUE TITLE
Photopea glitch 

### ISSUE THREAD

**Issue by StealthProoo** [photopea/photopea#2328]
I am trying to make a thumbnail for my yt videos and everything was going well until a glitch where I could not move my layers and   im trying to move the objects that I had (layers) then it causes the objects to turn red
![Screenshot (36)](https://user-images.githubusercontent.com/68824304/88487205-a4574880-cf48-11ea-9f07-b4f9eb3afd0a.png)

**Comment by StealthProoo** [comment]
Does anyone know how to fix this????

**Comment by photopea** [comment]
Hi, you entered a quick mask mode (probably by pressing Q), see here: https://www.photopea.com/learn/selections

Just press the Q again.
