### ISSUE TITLE
'graphic pen' filter

### ISSUE THREAD

**Issue by mnherm** [photopea/photopea#2329]
Would it be possible to implement a filter akin to the 'graphic pen' filter from Photoshop. So far one can use Mezzotint with short-lines to roughly the same effect, but it doesn't have the line length variables and contrast variables of 'graphic pen'. 

See examples of graphic pen: https://lh3.googleusercontent.com/proxy/FRIfXmjCWG9LZVL7eEaFwOyysfYbxLc1cnWx99MD7-NCu_SQCqRM202FuRK-V51FXHrH9n20rBAaMbDhM2Sgm07O6KQKScgmFfMTjvQX0vGFBbM

https://permadi.com/tutorial/photoToSketch/images/stroke10.gif

**Comment by IamFlea** [comment]
We have done an approximation of this filter.

**Comment by photopea** [comment]
Yes, this filter is complete :)

**Comment by mnherm** [comment]
I never replied to this, thank you SO much, Photopea has now replaced Photoshop for me. And made me able to fully move to Linux etc.

Best,
James

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
