### ISSUE TITLE
Improve login/register modal

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#233]
I think that missing informations like:
1) Why I would want be logged, what benefits I will got?
2) Improve UX of login area (green button, more bigger area for it with 1. ... some call-to-action item)
3) Need be logged before I register as a premium member? It not making sense.
4) How works teams? I think that this is should be advanced function ... same with Distributor account. Form is too long and not clear for beginners. I think that some intersection for example by accordion menu can be good, hm?
5) "I accept Terms of Services" too not making sense. There should be a link to the terms. I don't want scroll to the top of page for it, ...
6) Some better UX can bring by split "login/register" and premium membership to the next step / window.

Do you making sense these my ideas?

**Comment by photopea** [comment]
Hi,
1. There is a message about it: settings will be synchronized
2. What do you mean? Which button should be bigger?
3. You must log in before buying premium. So we know who is buying it.
4. There is a link under the table, where teams are explained.
5. You are right.
6. I thought that scrolling is easier than clicking.

**Comment by photopea** [comment]
I think it is pretty much fixed now.

**Comment by landsman** [comment]
Do you have a plan redesign for this?
It can be AJAX call from photopea window, or modal window.
It looks weird compared to whole great design of program.

![Screenshot from 2019-04-16 11-01-26](https://user-images.githubusercontent.com/3184228/56196437-1e570d00-6037-11e9-9cb5-54332dbf0988.png)

**Comment by photopea** [comment]
Many browsers have blocked popup windows. Also, Google and Facebook dont let us have this in an iframe. And we can not reload the Photopea webpage itself (the work would be lost).
