### ISSUE TITLE
Inserting symbols and punctuation marks in Arabic at the end of a sentence (right to left) puts them at the start of the line

### ISSUE THREAD

**Issue by SnaccHBG** [photopea/photopea#2331]
To give an example in English (to demonstrate):

This is a sentence.

You'd type the letters then add a period - however, this is what it shows up as:

.This is a sentence

Refer to this screenshot as an example.
![image](https://user-images.githubusercontent.com/65660396/88581027-9cd59380-d05d-11ea-954e-150aaae2aef8.png)

The only punctuation mark that works correctly is the Arabic question mark. In fact, this is a temporary workaround to fix it; in the above example, if I type "sentence.?" then reduce the size of ? to 1 px (making it disappear), it'll display correctly.
![image](https://user-images.githubusercontent.com/65660396/88580829-49fbdc00-d05d-11ea-8f58-f992cb5acbfa.png)
![image](https://user-images.githubusercontent.com/65660396/88580845-5122ea00-d05d-11ea-8a2b-ea2da8e2e5f7.png)

**Comment by photopea** [comment]
Hi, did you set the main direction of the paragraph as left-to-right? Press Window - Paragraph, it is at the bottom of the menu.

**Comment by SnaccHBG** [comment]
> Hi, did you set the main direction of the paragraph as left-to-right? Press Window - Paragraph, it is at the bottom of the menu.

Oh! That seems to be a fix. Sorry for not trying it; in other programs, aligning the text to the right usually takes care of that automatically. Thank you for the quick response!
