### ISSUE TITLE
Glitch were using move tool switches layers..

### ISSUE THREAD

**Issue by GavHern** [photopea/photopea#2332]
Ive recently encountered an issue where using the move tool will cause the layer to switch... It persists after I refresh the page and load the psd back... Not sure how to fix it, seems to just happen miraculously... Seems to happen sometimes when i duplicate a layer, but not too sure what's causing it. This is really annoying as I have to move that layer with only arrow keys (and just found out, i can move it with free transform which makes it a little less annoying).

**Comment by photopea** [comment]
Do you have "Auto-select" enabled at the top menu of the Move tool?

Are you using Firefox? Photopea duplicates a layer, if you move it while holding Alt. Firefox has a bug, that it tells Photopea the Alt is pressed, even when it is not.

**Comment by GavHern** [comment]
> Do you have "Auto-select" enabled at the top menu of the Move tool?
> 
> Are you using Firefox? Photopea duplicates a layer, if you move it while holding Alt. Firefox has a bug, that it tells Photopea the Alt is pressed, even when it is not.

Im on chrome, but I have software running that might force my alt key to be pressed... The issue was not about duplicates being created, but rather the app acting up after duplicating a layer. After I duplicated layers, the app didnt let me move layers, as it would always move me to a different layer.

Here's a video so you can see what's going on [https://youtu.be/b96Jzpj1-8g](https://youtu.be/b96Jzpj1-8g)

I'm not 100% sure that duplicating layers caused this but it was the action i did right before it happened. Again, refresh doesn't fix it.

**Comment by photopea** [comment]
And what about the auto-select?

středa 29. července 2020 Gav Hern <notifications@github.com> napsal(a):

**Comment by photopea** [comment]
According to your video, you have Auto-select enabled. Disable it, so that layers are not auto-selected when you click on them.
