### ISSUE TITLE
Feature request: Open smart object on layer window

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2333]
Hi!

It would be awesome if i can open a Smart Object from the layer window.
Now the only way to open it is by top menu > Layer > Smart Object > Open.
![Screenshot 2020-07-29 at 19 57 48](https://user-images.githubusercontent.com/11801254/88865518-1db79b00-d1d6-11ea-8816-5d77ea99891d.png)

Cheers!

**Comment by dentistformyeye** [comment]
Double-click/tap the thumbnail of the smart object in the layer panel.

**Comment by avagp** [comment]
[image: What does Mind Blown mean & Why Mind=Blown is a viral meme?]

**Comment by dentistformyeye** [comment]
If that's all you need feel free to close the issue.

**Comment by avagp** [comment]
Thanks!!!

**Comment by photopea** [comment]
I am very heppy to see, that you guys are helping each other :)
