### ISSUE TITLE
Liquify filter doesn't work properly on bottom of a short image

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2334]
### Description
The liquify filter doesn't work on the bottom of an image unless I move my mouse very quickly. In addition, the filter effect is on the top of the brush circle rather than the center. It might be because the image I'm using is very short.

### How to reproduce
1. Open the following image in Photopea. I added the red brush strokes to make the Liquify effect easier to see.
![image](https://user-images.githubusercontent.com/51429646/88878187-59ae2880-d1f5-11ea-95da-54ac0ed5cc36.png)

2. Go to Filter > Liquify.
3. Change size, density, rate, and opacity to 100.
4. Choose the swirl option (4th one).
5. Start with the brush completely above the image. Click and drag the brush very slowly along the left red line until the brush is completely below the image.
6. Start with the brush in place such that the circle surrounds the entire right line. Click and hold in place for a second or two.

### Expected result
The entire left line should be distorted with chaotic swirls. The entire right line should be distorted into a single large swirl.

### Actual result
The bottom of the left line doesn't get distorted. Only the top of the right line gets distorted.

### Additional notes
I reproduced this bug with my extensions disabled.

**Comment by photopea** [comment]
Hi, that was a serious bug, which happened only for small images. I fixed it :)
