### ISSUE TITLE
Feature request: destructive crop checkbox

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2335]
### Description
The crop tool always crops pixels non-destructively. When an image gets cropped, the pixels not in the box get hidden but don't go away. Filter Gallery and Liquify use the whole image even when the image is cropped, but that's not always desirable, so a checkbox which would toggle the crop tool between destructive and non-destructive would be useful.

**Comment by photopea** [comment]
Hi, I implemented that checkbox :)
