### ISSUE TITLE
BUg for photopea

### ISSUE THREAD

**Issue by neodaboi** [photopea/photopea#2337]
When I try to move a layer it goes to the rectangle selection tool and it moves a different layer and this bug makes this website unusable for me.

**Comment by photopea** [comment]
Hi, I think you have Auto-select enabled, but you don't know how it works.

When you have a Move tool, look at the top menu. There is "Auto-select" checkbox. Disable it. Let me know if it helped.

**Comment by SebiTimeWaster** [comment]
this can probably be closed

**Comment by photopea** [comment]
ok :)
