### ISSUE TITLE
Malicious Ad Fraud

### ISSUE THREAD

**Issue by Nanoo-web** [photopea/photopea#2338]
Hello,

In short: You have an ad which redirects users to a fraudulent website (steals credit card info, email, etc...)

I have been trying to use your website, and I keep getting a pop-up which says: "Would you like to leave the page?". I am not trying to leave the page, so I close it (which, unfortunately, wasn't enough) - a few seconds later, it appears again. So I press "ok", since I was curious to what was going on, and it redirects to me to this phishing website, claiming to give "Free iPhones" from the user's internet provider. Knowing it was a scam, I played along and ended up on a page which asks you to enter your **credit card** information.

Page screenshot:

![image](https://user-images.githubusercontent.com/62435867/89100775-ed4c4880-d3f1-11ea-96c0-5ba58faf656b.png)

Please remove this ad, before anyone has their information stolen.

Thanks.

**Comment by photopea** [comment]
Hi, I think this ad is inserted into Photopea by one of your browser extensions. Photopea never shows ads which have to be closed.

Can you please confirm, that this ad also appears in Incognito mode? Or it appears when you disable all your browser extensions?

**Comment by Nanoo-web** [comment]
I tested this on a completely different browser (Firefox), and still receive the alert message:

![image](https://user-images.githubusercontent.com/62435867/89101250-2090d680-d3f6-11ea-9f48-15850611e048.png)

This is the page it redirects to:
![image (73)](https://user-images.githubusercontent.com/62435867/89101279-5b930a00-d3f6-11ea-9d0d-986d988a2e5f.png)

**Comment by photopea** [comment]
Can you open a private window in Firefox and try it there?

**Comment by Nanoo-web** [comment]
I do not receive ads in the private window.

Here's the ad service URL which I found in the Network DevTools:
`https://www.lijits.com/track/a62a8b52-adbb-4965-be80-9ff951efdab6?siteid=YjY0MTU4Mjc1OTYwMTQ4ODQ4NTE2IzE1OTYyODMwOTZANTcwOEBfMzM1ZDA2MzM2MGM1MzgwMjY4ZDljMDA0YTMzZjUyNTA&var1={sitedomain}&var6=YjY0MTU4Mjc1OTYwMTQ4ODQ4NTE2IzE1OTYyODMwOTZANTcwOEBfMzM1ZDA2MzM2MGM1MzgwMjY4ZDljMDA0YTMzZjUyNTA&var5=2`
(redirects to phishing page, as shown in screenshot above)

![image](https://user-images.githubusercontent.com/62435867/89101454-e4f70c00-d3f7-11ea-9d00-32e0482712f6.png)

**Comment by photopea** [comment]
So you always see an ad in a regular window, but never in Private? Do you have any add-ons in Firefox? Open about:addons

**Comment by Nanoo-web** [comment]
I have no add-ons on Firefox (including Private).

![image](https://user-images.githubusercontent.com/62435867/89101544-ae6dc100-d3f8-11ea-9c34-b7dc362a1db1.png)

**Comment by Nanoo-web** [comment]
I found the reason to why ads don't appear in Private:

Ads, which are perceived as Tracking Content, are allowed in normal windows. However, in a Private window, Tracking Content is blocked, so ads are not shown.

Anyway, the point is that your website is infected with adware which could potentially mislead users and leave negative reputation.

**Comment by MichalSZZ** [comment]
It is a problem only on Photopea? Can you try to open any other website with ads and wait for a moment?
Sometime it is problem on a router that give acces to internet. Somehow software on it is changed in that way, that adresses to normal ads are changed. I had that problem few years ago but then I even didn't know about Photopea.

Try to disable wifi and connect internet in laptop from internet from mobile phone (internet data connection from your operator). If dake ads didnt show, you have the answear.

**Comment by Nanoo-web** [comment]
I am **absolutely certain** that it's **only** Photopea. I have been using Google Chrome for the past 2 hours, visited multiple 
 unique websites, and have not come across this issue before.

Have you tried opening Photopea yourself?

**Comment by photopea** [comment]
There are about 200 000 people using Photopea every day and nobody reported such behaviour. That is why I think that your computer is "infected" with something.

I will report the screenshot and the ad to my ad provider.

**Comment by Nanoo-web** [comment]
That's fine. I guess i'll just use Firefox Private in the future, since I don't receive any dodgy popups and ads from your website. I only reported this to make you guys aware.

**Comment by photopea** [comment]
Soon, we will show a pupup in Firefox Private too. We are looking into it and will let you know.

**Comment by photopea** [comment]
Let's discuss it in the another thread, as I think it is related.
