### ISSUE TITLE
Feature Request: GIF frames boomerang

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2342]
Hi!
I have been doing a lot of GIFs lately, and i encountered that in many cases it will be a lot of time saved if i had the option to boomerang my frames.

When i mean boomerang, it is like instagram videos, when after all frames have passed, they go backwards.

Here is a little example: 
![N - cholito](https://user-images.githubusercontent.com/11801254/89106662-a2ceca00-d3f9-11ea-8343-b879ef6890a6.gif)
This GIF is a loop animation. After the wings have streched, the wings should turn back.

Right now i have to create the frames of the strech, and then duplicate them and reorder them backwards.

But if Photopea has a "boomerang/reversed-loop" feature when exporting, it will save a lot of time.

Hope i explained it correctly  :)

**Comment by photopea** [comment]
Hi, I was thinking about this feature before, too! :)  There is one sad fact - even though it will show the same frames, as were shown before, it will double the size of the GIF file :(

I think there are two ways to do it: either we add a feature "Reverse selected layers" (so you can duplicate all layers and reverse the new copies to make the effect), or we add a checkbox when exporting the GIF.

**Comment by avagp** [comment]
add the checkbox an make it be double in size, it is pretty much the same thing.

I prefer th latter, so i can handle less layers, and the modifications i made apply to the final file, instead of delete and reduplicate the layers.

👍

**Comment by dentistformyeye** [comment]
Would the last frame be doubled? I.e. would the boomerang version of 1 2 3 be 1 2 3 3 2 1 or would they be 1 2 3 2 1?

**Comment by avagp** [comment]
To be honest, the boomerang should be the following: 1-2-3-2-1-2-3-2-1-2-3...

Neither the last or the first shoulb be repeated

**Comment by dentistformyeye** [comment]
Yep, my mistake.
And to clarify what I meant by flexibility, I prefer a "Reverse selected layers" option because it would allow for turning 1-2-3 into 1-2-3-3-2-1-2-... . (Unless another checkbox were made, a boomerang checkbox in the GIF export menu would only allow for turning 1-2-3 into 1-2-3-2-1-2-... or turning 1-2-3-3 into 1-2-3-3-3-2-1-2-... .) In addition, a "Reverse selected layers" option would be useful for non-GIF purposes.

**Comment by avagp** [comment]
Honestly I am fine with the method I told you. But if there is more
flexibility I won't get mad :)

Le ven. 16 oct. 2020 à 01:41, dentistformyeye <notifications@github.com> a
écrit :

**Comment by photopea** [comment]
Hi, I implemented the Boomerang feature :)

**Comment by avagp** [comment]
![image](https://user-images.githubusercontent.com/11801254/99820815-08bd9980-2b30-11eb-89d5-a84e3078cab8.png)

Niceeee addition

So, at the end was: 1-2-3-2-1-2-3-2-1...
