### ISSUE TITLE
Image not trimming

### ISSUE THREAD

**Issue by rap0so** [photopea/photopea#2343]
Hello guys,

This occurs when you left some empty pixel anywhere around layers
and click this option:

![image](https://user-images.githubusercontent.com/18194524/89125053-0e746e00-d4b2-11ea-8b3a-0ee5a1988fbe.png)

even with `Ctrl + .`

there's no error on screen nor console:

![image](https://user-images.githubusercontent.com/18194524/89125119-7fb42100-d4b2-11ea-9746-f1c446d48563.png)

**Comment by photopea** [comment]
Hi, the Trim option looks at the pixel in the top left corner and trims edges of the image, as long as they have the same color as that pixel.

Does Trim do anything else in your case? Or do you want it to do something else?

**Comment by rap0so** [comment]
> Hi, the Trim option looks at the pixel in the top left corner and trims edges of the image, as long as they have the same color as that pixel.
> 
> Does Trim do anything else in your case? Or do you want it to do something else?

Aaah got it, i was expecting it to trim any corner, is it possible in the future?

**Comment by photopea** [comment]
What do you mean by trimming a corner? The image is always rectangular.

**Comment by photopea** [comment]
You can use the Eraser tool to erase pixels (make them transparent).

**Comment by rap0so** [comment]
Ops, sorry, i mean this "empty area" here
![image](https://user-images.githubusercontent.com/18194524/89137830-d6037d00-d50f-11ea-8146-ad2f3006bbd6.png)

instead of `top left`, `top left right bottom`

**Comment by photopea** [comment]
In your case, the top left pixel is transparent, so it should trim all transparent areas from the sides. Here is how it works in my case:

![image](https://user-images.githubusercontent.com/15955558/89150282-85ffd700-d55e-11ea-9c31-edd3f39781f1.gif)

**Comment by rap0so** [comment]
OMG, I swear it wasn't trimming like this kkkkk!
anyway, ty and congratulations for the project

u guys r awsome

**Comment by rap0so** [comment]
OMG, I swear it wasn't trimming like this kkkkk!
anyway, ty and congratulations for the project

u guys r awsome

**Comment by photopea** [comment]
Maybe you had a non-transparent pixel in the first line of pixels.

Lines  (and columns) of pixels are trimmed away from the edges of the image, as long as they have the same color in all pixels.

**Comment by shethhiral** [comment]
the image issn't trimming for me too.

**Comment by photopea** [comment]
Could you send me your document as a PSD file to support@photopea.com ?
