### ISSUE TITLE
Login via GitHub error

### ISSUE THREAD

**Issue by kallaon** [photopea/photopea#2346]
I've tried to log in via GitHub and I this get error with output of JSON object that I'm not pasting here cause it contains some of my  account info.

> Photopea didn't receive your name.
Please, enter the missing parameters at your GitHub account.

Thank you and keep doing good work

**Comment by photopea** [comment]
Can you fill in some name in your Github profile?

**Comment by kallaon** [comment]
I can but I do not have it there on purpose, but I have never had problem with authorizing via github in other web apps. Maybe you could implement such function that fills that input if empty.

**Comment by photopea** [comment]
We just want to call you somehow in the Account window, that is why we ask for two values - a name and an emial.

You can enter a single character like "a" or "x" or "_".

**Comment by kallaon** [comment]
I see, no problem :) I've already signed in with FB account. I've just wanted to let you know what I've encountered

**Comment by photopea** [comment]
I see, no problem. But the message is correct - you did not enter any name on Github. But you have it on Facebook so it is fine :)
