### ISSUE TITLE
files appear in txt for me not in png

### ISSUE THREAD

**Issue by starkin1** [photopea/photopea#2347]

**Comment by photopea** [comment]
Hi, you are using a browser extension, which renames your files to TXT. We discussed it before.

https://github.com/photopea/photopea/issues/1699
https://github.com/photopea/photopea/issues/1880
https://github.com/photopea/photopea/issues/1823
https://github.com/photopea/photopea/issues/2040
https://github.com/photopea/photopea/issues/1373
https://github.com/photopea/photopea/issues/2294
