### ISSUE TITLE
Line Form arrows - end and start missing

### ISSUE THREAD

**Issue by gitty8** [photopea/photopea#2350]
Is the option for end and start for Line, Form arrows missing?
![image](https://user-images.githubusercontent.com/19901796/89412823-0291e180-d728-11ea-80a2-2186baee3131.png)

**Comment by photopea** [comment]
Hi, I am not familiar with Adobe Photoshop 2020.

Do you want a similar Feature in Photopea? What exactly should it do? My German is quite bad :(

**Comment by gitty8** [comment]
Path options
Arrowheads
beginning and end

The other forms, own forms etc. are already working and work great! Only the arrowheads beginning and end are missing :)

**Comment by photopea** [comment]
I implemented it :) Sorry that it took me a year. There is a live preview of the arrow in the configuration window.
![image (2)](https://user-images.githubusercontent.com/15955558/128625994-a130c62d-4cff-4c13-89cb-1333f92249b2.png)
