### ISSUE TITLE
Feature Request: Hue Editor as in PhotoLine

### ISSUE THREAD

**Issue by IPv6** [photopea/photopea#2351]
Please, add color filter with abilities as in "Hue Editor" in PhotoLine editor. Unfortunately there is no good docs for it, but its the best way to recolor images without too much hassle. I tryed a lot of usual variants.

Basically it allows to remap color to another color in each logical channel (hue, brightness, saturation) with soft fallofs

**Comment by photopea** [comment]
Hi, that sounds like a nice feature. But the problem is, we can not have it in our normal adjustments (e.g. as an adjustment layer), because such type of adjustment layer does not exist in a PSD format.

BTW. in our Hue/Saturation adjustment, you can pick a specific color (e.g. Reds) and apply the change only to that color.

I can add a custom selector, where you can choose an "interval of Hue with soft edges", to which the change should be applied, like it is in Photoshop: https://i.imgur.com/RjOzXHx.png What do you think?

**Comment by IPv6** [comment]
I see... Thanks for explanation, i understand that your are limited with PSD compatibility. May be as a modal tool?

Soft edges is a nice feature too, but Full-fledged Hue Editor really makes a difference // It`s hard to catch "sweet spots" with that kind of controls comparing to just picking hues from the image itself (as it is done in PhotoLine)

**Comment by photopea** [comment]
Is it this Hue editor? https://www.pl32.com/pages/images/rnote/ver18_9.jpg

As I understand, it modifies one hue to another, without changing the saturation or the lightness, am I right?

**Comment by IPv6** [comment]
Yes generally, but there is some more: you can switch to Brightness and change brightness based on hue (top button switching to editing this curve). Additionally you can switch to saturation and change saturation curve based on hue.
All 3 curves take effect in the same time, altering separately hue/brightness/saturation from hue values (initial, unaltered)

With this only effect you can totally "remap" image to another pallete - changing hues there, brightness of another zones here, and adjusting saturation of other parts. Especially useful for colorful art, since hues are defining "zones of interest" very well

There is also dropdown to select "definitions" of hue/brightness/saturation - in LAB terms, HSV terms, etc. This may be overkill, but sometimes usefull since curve in different modes gives different color interpolation

**Comment by rocifier** [comment]
@photopea this is almost the same use case as I had with #3649 and I believe would serve a similar purpose. The ultimate problem is not having a perceptual color space to work in
