### ISSUE TITLE
REMOVE THE POP UP THAT WANTS YOU TO BUY PREMIUM.

### ISSUE THREAD

**Issue by aidinjk** [photopea/photopea#2353]
It's so annoying!!! >:((((((

**Comment by photopea** [comment]
Hi, you are probably blocking ads in Photopea. Please, allow us to show you ads. Photopea depends on ads and it would not exist, if everybody was blocking ads.

Do you have any other idas how can we get money for our development? :/

**Comment by aidinjk** [comment]
IDC ABOUT ADS, THEY ARE PIECES OF CRAP. I DO NOT WANT TO SEE THEM AT ALL.

**Comment by aidinjk** [comment]
also you mispelled ideas
