### ISSUE TITLE
Curves white balance correction issue

### ISSUE THREAD

**Issue by aiakovlev** [photopea/photopea#2358]
I noticed that white balance correction doesn't work in Curves adjustment layer, but it works fine from the menu "Image" - "Adjustments" - "Curves".  If you try to do the same procedure via adjustemtn layer, it shows a pop-up error "Layer is not editable" (depending on the tool selected) or simply doesn't do anything.
White point tool has no effect in the adjustment layer, Curves:
![Annotation 2020-08-07 134229](https://user-images.githubusercontent.com/57973835/89673269-0f434080-d8b4-11ea-80c9-255f8f776a76.png)

This feature works via "Adjustments" menu:
![Annotation 2020-08-07 134339](https://user-images.githubusercontent.com/57973835/89673270-0fdbd700-d8b4-11ea-9827-2cf2ee401e9e.png)
The area on the wall was selected as a white point sample and effect has been applied:
![Annotation 2020-08-07 134343](https://user-images.githubusercontent.com/57973835/89673273-10746d80-d8b4-11ea-8380-fd9bf5f8c05c.png)

**Comment by photopea** [comment]
We will fix it in this issue: https://github.com/photopea/photopea/issues/2969
