### ISSUE TITLE
Continuing an existing vector path doesn't work

### ISSUE THREAD

**Issue by mira-fraiyo** [photopea/photopea#2359]
I'm working on an illustration made entirely out of vector paths. Very recently I tried to add to the paths I already made, but it won't allow me to continue adding points; when I try to add points outside the path, it adds them to the nearest path line. I know that to continue a path, I select the end of the path first and then use the pen tool as a path to add to the existing one. When I did this before, it would add on to the path. The only thing that seems to work is creating a new path; I cleared the cache and refreshed the page but nothing changes. But at this rate, I'll have to recreate all the paths I want to add to.

EDIT/CLOSED: It looks like I was editing the start of the path and not the end... It would be nice to be able to edit either side, or to at least have an indicator of where the start is.

**Comment by mira-fraiyo** [comment]
Unfortunately it looks like it doesn't matter which way the path is edited, I was working on a brand new path at the end of it and it is still not allowing me to append points...

**Comment by photopea** [comment]
The pen tool adds a new point at the end of a selected point. If no point is selected, it starts a new shape.

You can select points e.g. with a Direct Select tool: https://www.photopea.com/learn/vg-manipulation  . When you add a new point with the Pen tool, that new point becomes selected.

**Comment by mira-fraiyo** [comment]
Yes, I select the end anchor, switch the pen to path, and try to continue the path. This is what happens:
![penexample](https://user-images.githubusercontent.com/49675891/89724452-ea37f600-d9b7-11ea-96dd-ffa19fe2d0ba.gif)

**Comment by photopea** [comment]
Hi, I think I fixed it, thanks for reporting :) let me know if you have any other problems.
