### ISSUE TITLE
Text not working

### ISSUE THREAD

**Issue by ShinyRain** [photopea/photopea#2361]
When I write text, the text layer in on top of a black picture, it is the top layer and the text is white and its not showing up.

**Comment by photopea** [comment]
Hi, try to update your browser and disable all browser extensions (or try Photopea in Incognito mode). Does it work differently?

**Comment by ShinyRain** [comment]
Yes, I restarted my browser and my pc and it started working fine. Thanks for reaching out to me.

**Comment by photopea** [comment]
Great :)
