### ISSUE TITLE
Copying alpha channel not working

### ISSUE THREAD

**Issue by JirkaVasica** [photopea/photopea#2362]
Hi,

copying image with alpha channel (RGBA) to another RGBA picture doesn't copy the alpha channel. Only the RGB data are copied. There is no difference whether you are copying from image/psd to another image/psd or if you are just copying within the .psd. Editing alpha channel with brushes etc. works, but copy/paste does nothing.

**Comment by photopea** [comment]
Hi, if you use a Chromium-based browser, the clipboard is integrated with the OS clipboard (so that you copy the image in Photopea and paste it e.g. into Photoshop or Gimp).

I think your OS or your browser might have a bug. What version of OS and a browser do you use? Are you using a beta / experimental version?

**Comment by JirkaVasica** [comment]
Hi,

OS: Windows 10 Pro (1909)
Browser: Vivaldi (3.1.1929.45 Stable)

I have also tried edge (same results) and internet explorer (photopea not loading at all)

**Comment by photopea** [comment]
I see that thre is Vivaldi 3.2 available for download. Why don't you update it?

I tried it in the latest MS Edge 84 and everything works. What Edge do you use? Could you maybe show us a screenshot of what you mean by alpha channel not working? What is pasted instead of the transparent areas?

**Comment by JirkaVasica** [comment]
I tried the update of vivaldi and the result is the same. However I have also MS Edge 84, so the problem is somewhere else. Maybe I am doing the copy/paste wrong, but I would assume that selecting all the layers, ctrl+c and ctrl+v inserts all the data. Instead only the RGB is pasted and the alpha is lost. 

Also I have discovered, that using "Open and Insert" option from the dropdown menu has the same issue, because it inserts only the RGB data without alpha channels.

Here is video showcasing the usecase (In this video I am using two .tga files, both in RGBA format and I am trying to insert one image to another): https://www.youtube.com/watch?v=FdLknl27-NY&feature=youtu.be

**Comment by photopea** [comment]
I think I have fixed it. If at least one channel is selected, the content is copied from and pasted into that selected channel.

**Comment by JirkaVasica** [comment]
Copy/paste now works, but not only partial. Here are the issues:

1. Selecting all the channels (R,G,B + Alpha) copies only the alpha part and not the whole picture
2. Pasted data are inserted directly in to the base layer instead of a new layer (as with the regular copy/paste)
(Next issue is not linked with copy/paste, but it is crucial after copy/paste so I am including it as well)
3. Moving selection does not work in alpha channels. Instead the whole content is moved
4. Open and insert option in the menu still only inserts RGB channels and not the alpha channels

Result I am trying to achieve is to copy small RGBA picture into bigger RGBA picture, but with the current setup I am unable to achieve this. Ideal solution would be to select all the channels in the smaller picture, copy the data, paste it in to the bigger picture (as a new layer) and then just offset/translate the picture. However currently I have to select RGB channels, copy them to the bigger picture, move the layer, go back to the smaller picture, select only alpha, copy the alpha and I have reached dead end since I can't move only the inserted part, because translation moves the whole image.

**Comment by photopea** [comment]
Hi, I recommend you to learn how Channels work in Adobe Photoshop. They work similarly in Photopea, as Photopea also works with the PSD format.

You should learn to distinguish between basic channels (R G B and transparency) and additional channels (you can have millions of them). You are calling the additional channel Alpha, but it is very confusing, as the transparency is usually called Alpha. Just call it an additional (fifth, sixth, seventh) channel.

In Photoshop, you can not select RGBA and additional channels simultaneously. You should do it separately.

**Comment by photopea** [comment]
The work with additional channels is similar to working with raster masks. You can not select two raster masks together and copy their content into two different masks.

**Comment by JirkaVasica** [comment]
True, with the naming I was just trying to stay within the context of this use case. Nevertheless in Photoshop you can edit the alpha channels almost the same way as the basic channels (translation, selection etc.). Also if I am not mistaken photoshop can have multiple layers contributing to all channels not just to the base RGB, but I would have to verify that on my second computer. 

Copying the image twice is not a big problem (first RGB channels and then additional channels), but the problem is that you can't copy the additional channels in to a specific layer and that you can't translate pasted content of the additional channel. So unless you are copying image with the exact dimensions as the target image, you are unable to transfer RGBA data to another RGBA file.

**Comment by photopea** [comment]
Maybe let's do it this way: Find steps, which work in Photoshop, but don't work in Photopea, and describe these steps to us.

**Comment by JirkaVasica** [comment]
Here is video showcasing the differences compared to photoshop when copy/pasting additional channels and editing them:

https://www.youtube.com/watch?v=yW3iSti8yYo&feature=youtu.be

**Comment by indigane** [comment]
I can confirm that pasting into a color channel does not seem to work. It pastes the image data as a layer instead, even if a single channel is selected and visible.

**Comment by photopea** [comment]
I think it should be fixed now.
