### ISSUE TITLE
Exporting Bug

### ISSUE THREAD

**Issue by Ametheus** [photopea/photopea#2363]
After exporting an image once, I can't export it again. I have tried exporting in different file types, but nothing works. This problem occurs every time I use Photopea and it's incredibly frustrating. I use Opera on the latest version.

**Comment by photopea** [comment]
Hi, this is because Opera is "protecting" you from "evil" files of Photopea.

Somewhere at the navigation bar there should be a notification, that the website is trying to save multiple files. Try to open it and confirm it, that you really want to allow Photopea save files into your computer.

**Comment by photopea** [comment]
I guess it was fixed. If not, let us know.
