### ISSUE TITLE
Feature request: content aware move tool

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2366]
I've found the patch tool very useful for filling something in (source mode) and duplicating something (target mode), but sometimes I also want to move an object without leaving the old object or a transparent area behind. Using the Target mode of the patch tool to duplicate and the spot-healing brush to remove the old object can serve most purposes but doesn't work well if the moved object would overlap with the old one.
Adobe implemented a content aware move tool in CS6. I would appreciate a similar tool in Photopea. (However, I'm not familiar with Adobe's "structure" or "color" parameters for ca patch and ca move. I like the simple patch tool parameters that Photopea uses.)
https://helpx.adobe.com/photoshop/using/content-aware-patch-move.html

**Comment by photopea** [comment]
Done! :)
![image](https://user-images.githubusercontent.com/15955558/91037781-e63be300-e609-11ea-814a-27029dbca0b6.gif)

**Comment by dentistformyeye** [comment]
Thank you!
