### ISSUE TITLE
This specific WebP image won't load

### ISSUE THREAD

**Issue by Defourthkitten** [photopea/photopea#2367]
![HandsomeTemplate](https://user-images.githubusercontent.com/69603749/90063651-8d318e00-dc9e-11ea-86ff-49aef528d2ea.png)

Whenever I try to open this image into Photopea, it gets stuck on loading, even though it's less than 1 Mb. If I open another image first, then open the attached image, it will still get stuck on loading. I tried opening a whole folder of images, most of which are larger than this one (and one even the same size), and it opened all of the images fine until it got the "glitched" image. My theory is that somehow the image has a pixel that Photopea can't load for some reason, but I wouldn't really know.
In case Github compresses/changes the attached images, [here's the link](https://vignette.wikia.nocookie.net/wingsoffire/images/4/46/HandsomeTemplate.png/revision/latest?cb=20200704114933) that the image is from.

EDIT:
I have found [another image](https://vignette.wikia.nocookie.net/wingsoffire/images/2/25/BromeliadTemplate.png/revision/latest?cb=20200704114909) that does the same, and both of them have something in common that none of the other images have:

![Screenshot 2020-08-12 at 17 47 52](https://user-images.githubusercontent.com/69603749/90082167-fb3c7c00-dcc3-11ea-882c-26b9c3b14bf0.png)

This screenshot shows six PNG files on my Chromebook. The two that don't load on Photopea are HandsomeTemplate.png and BromeliadTemplate.png.
When I saved those two files to my device, it appears my Chromebook put .png at the end of the file name. When I viewed the metadata of the file, and they were WebP files. I fixed the file extension, and it still didn't load.

So this bug report has changed to: WebP images get stuck on loading.

**Comment by photopea** [comment]
Hi, we are using a WebP Decoder from Dominik Homberg, who is extremely hard to reach and get in touch with. Sadly, there is no better WebP decoder than his at the moment.

I tweeted to him, but it is hard to tell if he will reply this year or never at all :D https://twitter.com/photopeacom/status/1294303093576937472

**Comment by photopea** [comment]
I replaced our old javascript WebP decoder with a new WASM decoder. It does not have bugs (i.e. it opens your image) and it is also 5x faster than our old decoder :)
