### ISSUE TITLE
[Suggestion] Read and write DXF CAD files

### ISSUE THREAD

**Issue by dalep** [photopea/photopea#2369]
For possibly expanding usefulness into CAD (Computer aided design) and CAM (computer aided manufacturing) and CNC (computer numerical control)
Many hobby CNC's use DXF files directly for engraving and laser cutting.  Others that use G-Code probably have ways to convert from DXF.
There are probably opensource libraries in inkscape that could reduce the workload in implementing this feature.
Related expanded feature request would be creating 2D g-code output and raster b/w images to laser grey-scale or 3D topographic type g-code.
Again probably features in inkscape or plugins that could be copied or just left as a separate workflow in inkscape if not features you feel fit with photopea.

**Comment by infinityiowastaken** [comment]
there may be some constraints to this in that photopea is mainly designed around raster imagery, so vector-based GCode may be difficult to implement correctly (although lines do seem to be handled similar to vectors, so who knows)

**Comment by snoopen** [comment]
I could see this as more of a convert grayscale image to 3d height map. Though consideration to keeping polygon count low would be needed. You'd only need export in that case.

Useful for CNC routing/milling and 3D printing.

**Comment by dalep** [comment]
Handling many test files great.  I imagine the line art and laser/router path type of files are the most relevant for photopea users.
I did still find some issues.  
Dashed lines showing as solid.  No idea how many line types are supported by dxf.  I see other files are showing dashed lines ok though.
This file didn't render well. (1.9M large file sorry) [https://www.parlec.com/Parlec/media/DrawingDownloads/dxf/H63-32ERC337.dxf](https://www.parlec.com/Parlec/media/DrawingDownloads/dxf/H63-32ERC337.dxf) but several others from there did well.  Possibly something to do with filtering dimensions?  There isn't any convention on layer names or useage.  It seems like curve points go to 0,0 perhaps like the wrong data got filtered out?  If the Dimensions are working, your probably better off leaving them in unless it is unrelated to this issue.
Text parsing on the Parlec drawings still has some issues.  The weights have an extra variable or formula overlaid. One note is missing a closing ')' on a '(AT3)' Last char missing on a similar note for other drawings.  The part number at the bottom also has extra 'PART NUMBER' text overlaid (another variable or label?).
3axis.co seemd to have a large collection of dxf for laser cutters.  
[https://cncriver.com/downloads/](https://cncriver.com/downloads/) has quite a few that seem under 200k in size.  four samples from there did not work, [4x.dxf](https://cncriver.com/wp-content/uploads/edd/2017/07/4x.dxf) is missing most elements.  
[https://grabcad.com/jesus.chavez-20](https://grabcad.com/jesus.chavez-20/models?page=4)  This guy did several drawings in the 300-500k size.  Renders well except text issues.  I noticed no hash fill on [gears-autocad-dxf-2](https://grabcad.com/library/gears-autocad-dxf-2)
Some samples that are not fully rendering [https://www.bluesea.com/support/documents/Engineering_Drawings](https://www.bluesea.com/support/documents/Engineering_Drawings) http://assets.bluesea.com/files/resources/product_documents/engineering_drawings/2002.dxf is a good small sample.
One final sample (300k) of lines to 0,0 and also text issues.  [https://grabcad.com/library/2d-3d-modelling-sample-1](https://grabcad.com/library/2d-3d-modelling-sample-1)

**Comment by photopea** [comment]
I have fixed most of the issues with text and lines going to Zero.

I downloaded some of your DXFs and converted them to PDFs here: https://anyconv.com/dxf-to-pdf-converter/ , but the PDF looks very weird sometimes. Also, some links require me to make an account before I can download the DXF file.

Could you attach DXF files, which still don't work, here, together with a PNG or PDF preview of what should they look like?

**Comment by dalep** [comment]
[Google Drive share](https://drive.google.com/drive/folders/11lGVJ2m7kBgSfz8BYEnIK9TbkHkTPbQe?usp=sharing)
Nice work, all the line art files I tried look great.  And this is probably the primary use case for most Photopea users.
For better full dxf compatability, fonts/text are the largest issue.  On  BRAZO DE ENGRANAJE.dxf I see the degree symbol '°' listing a Unicode string instead.  A case of missing logo on 2104.dxf, google drive preview is not displaying it either.  On the Parlec stuff, dropped last char from some labels, diameter symbol 'Ø' is 'n'.  Previously mentioned missing fill hatch and some dashed lines rendering as solid.

**Comment by photopea** [comment]
I fixed probably all what you have mentioned :)

**Comment by dalep** [comment]
Looks nice now.  That was fast getting that implemented.

**Comment by photopea** [comment]
@dalep Would you like to have a DXF export, too?

**Comment by dalep** [comment]
While I do not need it, I imagine it could be useful to someone.  I'm
guessing you will have to put restrictions on what type of file can be
output as DXF, or at least how the source is interpreted before output.
That may create a lot of complications.  If you want to give it a try, I'll
give some feedback.
Actually a specific use case is scanned drawings back into cad files.  But
that seems like all the text OCR programming problems on steroids.

*Regards,*
*Dale Puch*

**Comment by photopea** [comment]
By the way, do you think DXF format can store Cubic Bézier Curves? That is what Photopea works with.

I have seen only only polygons and B-splines in DXF. Maybe a bézier curve is just a case of a B-spline.

Could you find any DXF file which contains bézier curves?

**Comment by dalep** [comment]
Yes from what I understand the spline is a b-spline or Cubic Bézier Curve.
If you haven't found it yet, take a look at
https://images.autodesk.com/adsk/files/autocad_2012_pdf_dxf-reference_enu.pdf
https://documentation.help/AutoCAD-DXF/WS1a9193826455f5ff18cb41610ec0a2e719-79e1.htm
looks to be the web version of it, possibly newer standard as well but I
didn't see the autocad/dxf version it was for.

*Regards,*
*Dale Puch*

**Comment by photopea** [comment]
Hi, I made a basic DXF export : File - Export As - More - DXF.

My exporter creates cubic splines for bézier curves, however, I was not able to open such DXF in any online DXF to PDF converter. I wish I could find some "minimum" DXF file containing a spline (I found the one which is 16 kB and it is not clear what can be removed).

However, you should be able to open DXF files from Photopea in Photopea.

**Comment by dalep** [comment]
Try looking at some of these file samples, but none of these used splines.
I added 2106.dxf back as it does seem to use spline but is 131k
https://drive.google.com/drive/folders/1HZWDiFLTRq0Onh343mOZ-UHF_f1WCJ4k?usp=sharing

Found this python lib doc if it helps
https://dxfwrite.readthedocs.io/en/latest/index.html
Also this reference for DXF files seems like the
practical samples/structures might be a help.
https://ezdxf.readthedocs.io/en/stable/dxfinternals/index.html


*Regards,*
*Dale Puch*
