### ISSUE TITLE
 Problem while saving

### ISSUE THREAD

**Issue by glaucorlima** [photopea/photopea#237]
I'm trying to save a project to PSD and I'm not getting it. It is only allowed to save on the web. How can I fix this problem?

**Comment by photopea** [comment]
Hi. Did you open PSD, or Sketch, or created a brand new PSD?  If you opened an existing file, can you open it separately in Photopea and save as PSD (without editing) ?

**Comment by glaucorlima** [comment]
I opened an existing PSD and made several changes. If I open the same PSD, even not doing any editing I can't save it.

**Comment by photopea** [comment]
Thank you very much for detals! Please, send your PSD to support@photopea.com and we will fix it as soon as possible.

**Comment by glaucorlima** [comment]
Excuse me for my ignorance, but how can I send it if I can not save it?

**Comment by photopea** [comment]
Please send us an original PSD file. I am sorry for not being clear :)

**Comment by photopea** [comment]
I was able to save that specific PSD file. The person stopped responding to my emails. I think it can be closed now.
