### ISSUE TITLE
[Suggestion] Add support for 16-bit and 32-bit per channel

### ISSUE THREAD

**Issue by maximecosseau** [photopea/photopea#2370]
Would you consider adding support for images with a color depth above 8-bit per channel ?

16-bit integer images are often used by photographers to keep colors more accurate during editing. 16- and 32-bit float images are widely used in post-production and visual effects to store high dynamic range images with values above one.

**Comment by photopea** [comment]
Hi, how would you preview the 16-bit images, to know it looks as you want it to look during the editing? Can your monitor display 65536 levels of red, green and blue?

**Comment by infinityiowastaken** [comment]
Under CSS Colour Level 4: https://drafts.csswg.org/css-color/#changes-from-3
>rgb() and rgba() functions now accept \<number\> rather than \<integer\>

In monitors that support higher bit depth colour, they will be rounded to the nearest unit of colour depth available

**Comment by photopea** [comment]
I am afraid such change would require too many changes in Photopea, as Photopea depends heavily on 8-bit colors at the moment. I think there are features which need my attention much more, and that spending time on it is not worth it. So I will close it.
