### ISSUE TITLE
Anti-aliasing for Pen Tool

### ISSUE THREAD

**Issue by sarrahyasay** [photopea/photopea#2373]
i Photopea Team,

I am Sarrah from Microwork.io. We are looking into using Photopea as a main tool in doing masking Annotation in our company. We are currently using Photoshop but we needed a tool that can be integrated into our site. I am asking if you could fix to disable anti-aliasing, I have talked to Ivan and he told me your team can fix it with a week or two and go hear to post my concern. Thank you!

attached below is the video for your reference

https://drive.google.com/file/d/16thefidYOfHQzuLs_pUkozlLdT5rvTRA/view?usp=sharing - Video of Photoshop setting to unclick anti-aliasing.

Hoping to hear a positive response from you soonest. Thank you!

with kind regards,

Sarrah Yasay
HR Assistant
Microwork.io

**Comment by photopea** [comment]
Hi, I implemented it :) You can either use the Make Selection button at the top menu of a Pen tool, or right-click the path and choose Make Selection.

**Comment by sarrahyasay** [comment]
Hi Photopea Team,

Make Selection is already there but when I unclick the anti-alias there are
still transparent pixels edges (see attached photo for your reference).

[image: image.png]

Regards,

Sarrah

**Comment by sarrahyasay** [comment]
Hi Photopea Team,

Make Selection is already there but when I unclick the anti-alias there are still transparent pixels edges (see attached photo for your reference).

Regards,

Sarrah
<img width="680" alt="Capture" src="https://user-images.githubusercontent.com/69631287/90337049-6d89c500-e012-11ea-8096-4b95c249a0ae.PNG">

**Comment by photopea** [comment]
Hi, are you sure you disabled anti-alias? When I disable it, there are no semi-transparent pixels.

![image](https://user-images.githubusercontent.com/15955558/90337224-639b9e00-dfe1-11ea-832a-579941b5c02e.png)

**Comment by sarrahyasay** [comment]
Hi

I clicked, Alt Enter and Alt Backspace after making a pattern using pen
tool and unclick the anti alias and still edges have transparent.

**Comment by sarrahyasay** [comment]
Ill send a video if you asked :)

**Comment by photopea** [comment]
Why do you click Alt+Enter? What is it supposed to do?

Can you send me a video? :)

**Comment by sarrahyasay** [comment]
Oh sorry, ctrl + enter and not alt enter. Ill sen you a video

**Comment by photopea** [comment]
Ctrl+Enter will convert a path to a anti-aliased selection. That is how it works in Photoshop. You should not do it, if you don't want anti-aliasing.

**Comment by sarrahyasay** [comment]
Hi,

I'm using CTRL+Enter all the time on Photoshop when my Anti-Alias is
unclicked already so that I can make a selection even if I don't go to Make
Selection Area again..

Please see attached Video. It works now but let me explain the first and
second try.
First try works, when I unclick the anti-alias and click okay the pattern
will automatically be selected and ALT+Backspace then it filled without
transparent pixels.
Second Try, I didn't click make selection because I thought Anti-Alias is
automatically unclicked as it was previously unclicked already so I  only
typed CTRL+Enter (to select the pattern) and ALT+Backspace and there are
still transparent pixels.

Video -
https://drive.google.com/file/d/1nEspMft-pdQTMSpifEqCgk8EMv4UQy0Q/view?usp=sharing

**Comment by photopea** [comment]
Oh, I see. The tool should remember the settings from Make Selection window, and use them when Ctrl+Enter is pressed.

It should be fixed now :)

**Comment by sarrahyasay** [comment]
Hi,

Thank you, your Response time is very fast!Wow! . it works now!

Regards,

Sarrah
