### ISSUE TITLE
It should be easier to make gradient with paint brush (Default color blending is mathematically incorrect)

### ISSUE THREAD

**Issue by TiraO** [photopea/photopea#2374]
This is also a bug in Photoshop, Gimp, and many other graphics applications. The source of the bug is that computer colors are stored as their square roots, and the average of the square roots is not the same as the square root of the average. The result is that bright colors blend together into duller colors than they should.

Blending (255, 0, 0) with (0, 255, 0) should do `(sqrt((255*255 + 0)/2), sqrt((0 + 255*255)/2), 0)`
giving (180, 180, 0), but instead you're doing `((255*255 + 0)/2, (0 + 255*255)/2, 0)` and getting (125, 125, 0) which is a significantly darker, more olive color. This problem in blending results in significantly extra work and subpar results for artists. This is not just an issue in Normal blend mode. All your blend modes suffer from this issue.

I encourage you to try it out and experience how much easier it is to create a smooth gradient e.g. when drawing a sphere.

**Comment by photopea** [comment]
Hi, I think GitHub mangled your formulas and it is not clear what yo mean. 

I don't know how did you come up with a square root. Are you talking about the gamma correction? Do you know what the gamma correction is?

**Comment by TiraO** [comment]
Whoops, my multiplication turned into italics.

Yes, I'm talking about gamma encoding / correction. The exponential nature of human color perception + storage is the cause of the problem.  https://en.wikipedia.org/wiki/Gamma_correction#Scaling_and_blending

My math may not be correct. I got the square root formula from this video, which does a reasonably good job of showcasing the problem even if its math is wrong:
https://www.youtube.com/watch?v=LKnqECcg6Gw

Here is a resource which mentions the square root formula but suggests another one that is faster and may be better. http://alienryderflex.com/hsp.html

**Comment by TiraO** [comment]
This is apparently the color space setting that is recommended for drawing/blending in photoshop: https://en.wikipedia.org/wiki/CIELAB_color_space

**Comment by photopea** [comment]
Our color blending works in a sRGB color space and we would like to keep it that way.

Yes, you can say that computing in another color space looks better, more natural etc. But it is just like arguing which Instagram filter is better and more natural. We would not get anywhere with it.

**Comment by photopea** [comment]
Also, I am sure most of people prefer the color blending as it works now, and would not like it, if we make it work according to your formula (in another color space).

**Comment by TiraO** [comment]
I think one thing that is terrible about moving to the color-space in photoshop is that they also shift all the pallets around. People are used to working with an rgb-style pallet. But saying that most people prefer having the blending itself work this way is a bit like saying everyone prefers magic markers--the ones that change colors via chemical reaction when they overlap. They might be fun for some purposes, but they don't behave intuitively, and if you're trying to create something realistic, it' a lot of extra work. When you blend bright red and green light together, you get yellow. When you blend bright red and green paint together you a kind of mid-tone brown. When you blend bright red and green using rgb shortcut math, you get a dark brown. It's off the end of the behaves-like-something-physical spectrum. So I guess in a sense it is like arguing about Instagram filters, but my point is that it would be nice to be able to have something that vaguely resembles "no filter" available, maybe even as the default.

**Comment by photopea** [comment]
There is not just a square root. There is an infinite number of mathematical functions, and each one would result into a different image

These color blending mechanisms are not just in Photopea. They are the same in a PDF, SVG and many other open formats. Saying that the user would prefer his PDF to be rendered differently, than it was renered in the past 20 years, makes no sense. The author of a PDF could see, how his PDF is rendered, and if he wanted it to look different, he was able to achieve it even with the current color blending mechanisms (without a square root).

I recommend you not to fully believe these blog posts and youtube videos, which claim that "everybody is doing it wrong".

**Comment by TiraO** [comment]
You're right, it is a very widespread problem. There is certainly some value in following conventions. It would be a complicated change to implement seamlessly for users. I understand if you don't want to do it. 

However, it is an issue that I was aware of before reading any blog post about it. It frustrated me as an artist long before I understood the technical reasons behind the implementation. It's difficult to achieve a smooth gradient that resembles the way colors blend together in a physical space when using the fast-rgb method and drawing with a brush. 

As far as I know there are no longer any free drawing tools which implement a more intuitive blending style. There used to be a tool on https://ratemydrawings.com/ which was very good, but they dropped support for that tool since it was a java applet and the developer was no longer supporting it. I'm not sure the site is even around anymore. Paint Tool SAI does a good job of blending, but it is not free. In other words, I am hunting for programs with this feature, since I personally find it very unpleasant to do drawing without it.

**Comment by Nekkowe** [comment]
> In other words, I am hunting for programs with this feature, since I personally find it very unpleasant to do drawing without it.
I'm seeing this pretty late, but if it helps, Krita lets you pick gamma-corrected colour profiles (and then export in standard sRGB later) while also being free.

**Comment by Nekkowe** [comment]
To drive the point home visually, here's a before/after with the incorrect blending mechanism:
![image](https://user-images.githubusercontent.com/28980049/221966318-9ce65734-aed6-40fc-9295-04dee4528c4b.png)
and the one that handles gamma correctly:
![image](https://user-images.githubusercontent.com/28980049/221966367-816d612e-f08c-4f83-b24f-8e356ba6f905.png)
In the first one, the unfortunate standard of sRGB blending without any correction for the format's gamma compression, the boundaries look atrocious - washed-out and much darker than the colours on either side. 

It's a mathematical oversight, common only because these tools were developed by people who mess with sRGB colour representation without fundamentally understanding how it actually works.
