### ISSUE TITLE
Bicubic sharper handles transparency wrong

### ISSUE THREAD

**Issue by SebiTimeWaster** [photopea/photopea#2375]
i have an image with alpha: 
![image](https://user-images.githubusercontent.com/3726309/90146921-ede5c700-dd81-11ea-8d38-029849cae28d.png)
i added a white background: 
![image](https://user-images.githubusercontent.com/3726309/90147008-02c25a80-dd82-11ea-93e0-d05b3adcfb89.png)
when i reduce the image size with "Bicubic Sharper", this happens: 
![image](https://user-images.githubusercontent.com/3726309/90147113-208fbf80-dd82-11ea-9c4c-ef0477495506.png)

**Comment by photopea** [comment]
Hi, the bug happens even if you apply Filter - Sharpen - Sharpen more on a layer with trapsparent areas.

**Comment by SebiTimeWaster** [comment]
nice additional find!

**Comment by photopea** [comment]
I fixed it, thanks for reporting! :)

**Comment by SebiTimeWaster** [comment]
awesome!! :)
