### ISSUE TITLE
Histogram - RGB Mean Values Don't Change by Channel

### ISSUE THREAD

**Issue by torinmcq** [photopea/photopea#2376]
Hello, I'm new to the software and greatly appreciate it, but have one suggestion. When making a selection, the histogram visibly shows a different color profile by channel (RGB), but the mean value doesn't change by channel. Could it be revised so that when switching color channels (red to blue, red to green.. etc.) the mean value will reflect the change? I've attached two screengrabs with the same selection but changing the channel. You can see the color profile move, but the mean stays put.

Thanks!
![Red](https://user-images.githubusercontent.com/69642073/90158252-c3cdde00-dd5c-11ea-9bf3-0d3d55f6b783.PNG)
![Blue](https://user-images.githubusercontent.com/69642073/90158262-c6c8ce80-dd5c-11ea-8a02-edbae1ab6a9c.PNG)

**Comment by photopea** [comment]
Hi, I fixed it, thanks for reporting it :)
