### ISSUE TITLE
PNG's not working

### ISSUE THREAD

**Issue by AtharvJ** [photopea/photopea#2377]
I opened and placed a png image but the background for it was still showing.

**Comment by MichalSZZ** [comment]
Did you find that PNG on google graphics? Why I'm asking... Many users have problem with PNG files from sites that showing PNG with special background (white gray chessboard) which pretend to be transparent, only for get the traffic for they sites (withs many many ads).

**Comment by AtharvJ** [comment]
Yeah, I searched up images on google which were in PNG format.

**Comment by photopea** [comment]
Hi, can you show us your image? 

What do you mean by the background? PNGs consist of pixels. A pixel can be transparent or it can have some color.

**Comment by AtharvJ** [comment]
![511-5116077_transparent-fortnite-dark-bomber-png-png-download](https://user-images.githubusercontent.com/66854597/90274167-f5a27b80-de14-11ea-82e1-dda75799ff6a.png)
This is my image. I did open and place. Does that not work?

**Comment by photopea** [comment]
Hi, your image does not have any transparent pixels. It is fully white with a black person in the middle.

I wrote an article about how to remove background form the image: https://www.photopea.com/tuts/remove-background-from-photo/
