### ISSUE TITLE
loading text remained on the screen

### ISSUE THREAD

**Issue by ademhatay** [photopea/photopea#2378]
I loaded the font and loading remained on the screen.
![Ekran Görüntüsü - 2020-08-14 00-20-34](https://user-images.githubusercontent.com/66277966/90188395-10003900-ddc4-11ea-80b9-edde27d96dba.png)

**Comment by photopea** [comment]
Hi, what exactly did you do before that? Does it happen for all files you try to open? Is your web browser updated? Can you try to run Photopea without any browser extensions?

**Comment by ademhatay** [comment]
I have installed the Text Font. The text "Downloading font" remained fixed
on the screen. I uninstalled add-ons and the problem was resolved. But it
can happen at any moment. because the same problem happened before. Then
repaired. If it happens again, I will forward it to you with the screenshot

Photopea <notifications@github.com>, 14 Ağu 2020 Cum, 17:57 tarihinde şunu
yazdı:

**Comment by photopea** [comment]
If you have a font, which can not be opened in Photopea, share it with us. I will close the issue for now.
