### ISSUE TITLE
Translations. Add New Language?

### ISSUE THREAD

**Issue by madranet** [photopea/photopea#2380]
Is there a way to add a new language to the translation page at https://www.photopea.com/translate/  or are you only interested in the languages already listed there?

I wouldn't mind kick-starting the Irish Gaelic translation.

**Comment by photopea** [comment]
Hi, I add the "slots" for the new languages manually :) You should just tell me which language you want.

There already is the Gaelic language and it is 51% translated. Or do you mean some other language?

**Comment by madranet** [comment]
> There already is the Gaelic language and it is 51% translated.

Whoops! --so there is. I don't know how I didn't see that. Sorry.

**Comment by Yazu321** [comment]
> Hi, I add the "slots" for the new languages manually :) You should just tell me which language you want.
> 
> There already is the Gaelic language and it is 51% translated. Or do you mean some other language?

I want to add a new language which is geez or amharic but i tried my best and not yet got it need you help

**Comment by photopea** [comment]
@Yazu321 ok, I have added the Geez language.
