### ISSUE TITLE
Magic Wand

### ISSUE THREAD

**Issue by Omegasuchti** [photopea/photopea#2381]
Every time when i want to use the wand there is the "Small Objects must be rasterised first" message coming. I can't use the wand. Why?

**Comment by photopea** [comment]
Hi, you should never see such message when using the magic wand tool. Can you show us a screenshot of what your document looks like?

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by Omegasuchti** [comment]
I‘m sorry that I had no Internet for a while. I went to a spot where was no signal

Here is a photo of the screeN

Bye,
Antonio

Von meinem iPhone gesendet

**Comment by photopea** [comment]
Hi, I can not see any screenshot. Please, go to a GitHub and write your comment there.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
Well... I'm not able to put a picture in this message. I don't know why, but I tried to sent one more Email with the picture.

**Comment by Omegasuchti** [comment]
I sent one more picture. Hopefully you can see it now. Actually I’m not able to comment anything in Github. Maybe because the issue is closed

Von meinem iPhone gesendet

> Am 19.08.2020 um 11:25 schrieb Antonio Zoder <antoniozoder@icloud.com>:
> 
> ﻿
> <image0.jpeg>
>

**Comment by photopea** [comment]
Hi, I still don't see any picture.

Hi, please, open https://github.com/photopea/photopea/issues/2381 in your web browser and comment there. You should be able to comment even the closed issue.

**Comment by Omegasuchti** [comment]
I tried several times, but it didn’t work

Von meinem iPhone gesendet

**Comment by photopea** [comment]
Do you have a GitHub account? Can you start a new issue and attach a screenshot in it?

**Comment by Omegasuchti** [comment]
I don’t know why, but I can’t attach images to the Github Website.

**Comment by photopea** [comment]
You can upload images to Imgur.com and share a link with us.

**Comment by Omegasuchti** [comment]
I sent one more pic. I downloaded it from the website and shared it with you on email. Maybe it’s a problem with your email?

**Comment by Omegasuchti** [comment]
Here's an Imgur post I made for you https://imgur.com/a/2n2OEZK

**Comment by Omegasuchti** [comment]
Have you got Instagram? If yes you could follow me and I’m going to post the picture

**Comment by photopea** [comment]
Can you take a screenshot of your computer, instead of taking a photo of your screen whit a camera? I wanted to see the layer structure.

**Comment by photopea** [comment]
You can share a link to your instargram post here, too.
