### ISSUE TITLE
Custom Fonts Do Not Kern Properly

### ISSUE THREAD

**Issue by EnderSmith** [photopea/photopea#2383]
1. Load custom .OTF font with kerning data
2. Type text involved with kerning pairs

expected: the font displays properly kerned.
actual: the font displays without any kerning.

**Comment by photopea** [comment]
Hi, could you share your font with us? So far, I thought all fonts are rendered correctly in Photopea.

**Comment by EnderSmith** [comment]
Font is here: https://aurekfonts.github.io/VeersNumeric/VeersNumeric.otf

The kerning should be tight between 3 and 8 (as seen here in word):
![image](https://user-images.githubusercontent.com/29317895/90416294-24b02b80-e067-11ea-8141-91ad00a76313.png)

But in photopea, I'm getting:
![image](https://user-images.githubusercontent.com/29317895/90416694-a86a1800-e067-11ea-9755-2f58e73d6e7c.png)

Though, I guess it's possible that I'm just dealing with an older version of the font still being installed, though I thought I had overwritten it. Is there a clean way to remove just one font, so that I can reinstall and check?

**Comment by photopea** [comment]
Could you also tell me the text which you are typing?

**Comment by EnderSmith** [comment]
Yes, the text is "38"

**Comment by photopea** [comment]
I will look into it and will let you know.

By the way, when I use the font in a website (through CSS), the kerning is the same as in Photopea.

**Comment by photopea** [comment]
It is fixed now :)

**Comment by EnderSmith** [comment]
Thank you!
