### ISSUE TITLE
Photopea not using entire browser

### ISSUE THREAD

**Issue by Gandolph101** [photopea/photopea#2385]
![image](https://user-images.githubusercontent.com/69954876/90723482-19eed400-e2bd-11ea-80ec-5ccc8e34a267.png)

**Comment by photopea** [comment]
Hi, there should be advertisement in that area. You are probably hiding it through some browser extension.

Please, watch our ads. If everyone did what you do (hiding ads and not Paying for Premium), Photopea would not exist at all :(

With Premium, Photopea will use the full screen of your device.
