### ISSUE TITLE
pencil brush does not work on ipad

### ISSUE THREAD

**Issue by enzyme69** [photopea/photopea#2388]
i just tested now, on iPad running iOS 14 beta 5, the pencil brush does not update the canvas while stroking, it just flickers. only updated if I did something else.

**Comment by photopea** [comment]
Hi, I think it is a bug in iOS 14 Beta. You can convince Apple to fix it, or use a stable iOS release.

**Comment by photopea** [comment]
I will close it, as I think it is a bug in the iOS.
