### ISSUE TITLE
PDF transparency not shown in preview window

### ISSUE THREAD

**Issue by cimm** [photopea/photopea#2390]
1. Create a new project with a transparent background
2. Choose File → Export as → PDF

![screengrab](https://user-images.githubusercontent.com/68112/91227290-90a92880-e726-11ea-8d70-8cfc1b38308d.png)

Notice the white background in the preview window (titled "Save for web"). The white background isn't really there. I saved the PDF and merged it with another one (using `pdftk`) and the PDF is really transparent.

To be fair to Photopea, most PDF viewers (like Evince) show a white background for transparent PDFs.

Also, I can't tell you all the things I tried to create a transparent PDF in Inkscape. To see it “just works” in Photopea is... awesome. Thank you!

**Comment by photopea** [comment]
The PDF is transparent, but the preview in Save for web has a white background. That preview is made with a PDF viewer integrated in your browser and I am afraid we can not change the way it renders the PDF :/

**Comment by photopea** [comment]
I need to close it, as I don't see any solution. It is up to a PDF viewer what background they use.

**Comment by cimm** [comment]
Sure, it's not something Photopea can fix without a ton of work. The browser’s built-in PDF viewers should be improved. Thank you for this awesome webapp! :heart: Photopea.
