### ISSUE TITLE
Ridiculous Editing Software

### ISSUE THREAD

**Issue by gmajor78** [photopea/photopea#2391]
This is just stupid. I cannot understand how the hell I can only edit everything backwards. Its frustrating as hell and no tutorials show you how to fix this issue

**Comment by photopea** [comment]
Hi, what do you mean by editing everything backwards?

**Comment by gmajor78** [comment]
Hey, I couldn't do a screenshot that could explain it so I recorded a video
to show you exactly what Im trying to do and what issues Im having trying
to accomplish it. Here is the video here https://youtu.be/yQJ5XKS5H4g

**Comment by photopea** [comment]
Hi Gmajor78. Can you send me your PSD file to support@photopea.com ?

**Comment by photopea** [comment]
Can you send me your PSD file to support@photopea.com ?

**Comment by photopea** [comment]
I have to close it because of lack of details.

Your PSD seems to have a strange structure, and I think it would work absolutely the same way in any other image editor. But I can not test it (as you did not send it to me).  You should ask the creator of your PSD why did they make it the way it is.
