### ISSUE TITLE
Export problems causing files to export as .txt files

### ISSUE THREAD

**Issue by LamentTheLime** [photopea/photopea#2392]
I'm on a windows 10 computer if that helps any.

**Comment by photopea** [comment]
Hi, you have a browser extension, which renames downloaded files to a TXT.

Try to disable that extension, or all extensions (e.g. in Google Chrome, go to chrome://extensions). You can also use Photopea in Incognito mode, where all extensions are disabled (so none of them can rename files like that anymore).
