### ISSUE TITLE
page keeps refreshing on its own and i lose all of my work

### ISSUE THREAD

**Issue by iishaa04** [photopea/photopea#2394]

**Comment by photopea** [comment]
Hi, are you using an old Safari on an iPhone? Or what are you using Photopea on?

**Comment by Yabla1** [comment]
Same on Google Chrome Latest version (Version 85.0.4183.83 (Official Build) (64-bit)) but for me it does not keep refreshing -- In fact it does prevent/ask when I try to refresh the page -- But..
The page got refreshed -while I was on another browser tab- automatically once internet connection (WiFi) is back. And lost my document.

**Comment by photopea** [comment]
@Yabla1  what operating system are you using?

**Comment by Yabla1** [comment]
It happened on a Windows 10 Pro.

**Comment by photopea** [comment]
I think Chrome should not reload webpages by itself, without you reloading them manually.

Did you change any Chrome settings / flags? I found this discussion: https://superuser.com/questions/1091425/how-to-auto-reload-tabs-in-chrome-if-there-was-no-internet-connection

**Comment by Yabla1** [comment]
@photopea 
> I think Chrome should not reload webpages by itself, without you reloading them manually.
Yes this, to reword my comment, the tab actually reloaded once I get back to it and open it.

I didn't change any of these settings.
[This comment](https://superuser.com/questions/1091425/how-to-auto-reload-tabs-in-chrome-if-there-was-no-internet-connection#comment1546125_1091438) describes exactly my case.
I didn't find any of the flags, but found this instead: (chrome://flags/#enable-new-download-backend), and it's set as "Default".
I think I'll just let it unchanged -Don't know actually what to change, I'm afraid I mess up these settings!-, unless there are some clear/to-the-point instruction.

Thanks for the resource, that's very helpful.

**Comment by photopea** [comment]
This is a question about a web browser and I do not know much about it :( All I can say is, that the browser is more "powerful" than a webpage, and Photopea as a webpage can not "dictate" the browser what to do.

Try asking about it here:  https://superuser.com/
