### ISSUE TITLE
Drawing on layer while invisible.

### ISSUE THREAD

**Issue by Yabla1** [photopea/photopea#2395]
It keeps drawing on a layer even when it is invisible.

How to reproduce this issue:
1. Create a document (project)
2. Add a layer
3. Make this layer invisible (hide it by clicking on the eye icon)
4. Select one of these tools: [Brush, Pen, Gradient, Paint bucket, (anything actually)]
5. Select a color (to make sure you see any changes you make)
6. Select the invisible layer (in case you missed it)
7. Draw something on the invisible layer
8. You can see the changes right in the Layer thumbnail
9. Make the layer visible. et voilà! you just made a drawing you actually didn't see, or have the intention to.

**Comment by photopea** [comment]
Hi, I think that is a correct behaviour. User is allowed to draw into any layer, no matter if it is visible or invisible, or if the opacity is only 50%. The user can draw into a layer even if it is visible, but fully covered by another layer on top (so the user does not see anything).

I just noticed, that drawing into invisible layers is not possible in Adobe Photoshop. But we allow it in Photopea, so I think it is an advantage.

**Comment by Yabla1** [comment]
Oh Hi! excuse me!
It can actually cause serious damages, especially if you use a graphic tablet -which is my case (Wacom intuos)- and make a lot of _unnecessary_ moves.
Speaking of which, tablet use is quiet off the grid in this. Thank you man for building this gem.

**Comment by photopea** [comment]
I still think it can be very useful to be able to draw into a layer, without having to enable its visibility.

If you decided to work with more than one layer, you probably know how layers work, how to switch between them, and you are aware what layer is active when you draw. So I would like to keep it as it is now.
