### ISSUE TITLE
Server Lag? Or any other possible problems?

### ISSUE THREAD

**Issue by zmrxdz** [photopea/photopea#2396]

**Comment by zmrxdz** [comment]
After i change the fonts, the top of the website showed "loading" for a very long time, if i refresh, i can't reach to this website again at least for a day.

**Comment by photopea** [comment]
Hi, are you using any browser extensions? Can you disable it? If nothing helps, I recommend to ask your internet provider about it.

**Comment by photopea** [comment]
I will close it now because of lack of details.
