### ISSUE TITLE
Crop tool seems lacking, could use some love

### ISSUE THREAD

**Issue by danielhaan** [photopea/photopea#2397]
Hi!

I love your tool a LOT, and really am trying to use it instead of photoshop. However, one of the tools I use often is Crop, and it seems a bit lacking in Photopea compared to Photoshop.

I'm mostly missing the snapping/guide behavior that is in the Photoshop variant of the Crop tool, and I would imagine it isn't such a huge development effort to implement. If anything, just that cropping is more a "box with corners you can drag" than a "square drawn with a cursor" feel.

If this is not a priority, then no problem :)

Cheers!!!

**Comment by photopea** [comment]
Hi, I just tried to use a Crop tool and while you drag it, it is snapped to guides.

Is that what you mean? Or what exactly is the problem?

**Comment by danielhaan** [comment]
Hi, I just realised that what I'm looking for already exists 🤦 just need to press the "Trim" option.

Sorry, for the wasted time!

**Comment by dentistformyeye** [comment]
Be careful not to confuse Current Layer and Trim. Trim will sometimes predictively cut  out some non-transparent pixels while Current Layer will surround the entire layer, including parts of the layer that have been cropped out nondestructively.
