### ISSUE TITLE
local storage

### ISSUE THREAD

**Issue by Studioartcz** [photopea/photopea#24]
Hi,

what about work with local storage in browser? 
I mean "save" opened project to this storage and after reload brower get this back.

**Comment by photopea** [comment]
local storage in modern browsers usually lets websites save about 5 MB of data. It is not enough for a casual PSD (or multiple PSDs). And if there is any history of editing, saving such history would make it even larger :(

**Comment by Studioartcz** [comment]
Really? I was think, that you can save just paths to files and some history.

**Comment by photopea** [comment]
Yes, you can save "paths to files". But the file must be located somewhere. Website cannot write on users harddrive and I don't have enough storage to store it online.

**Comment by Studioartcz** [comment]
I understand. What about "close alert"?
