### ISSUE TITLE
Text not showing

### ISSUE THREAD

**Issue by mikeivog** [photopea/photopea#2400]
![Capture](https://user-images.githubusercontent.com/70498145/91678051-125de380-eb77-11ea-88b8-4b8ba0fdcfb0.JPG)

**Comment by photopea** [comment]
Hi, you are probably using a browser extension, which clears all text in Photopea. Try to disable that extension, or try Photopea in Incognito mode (where all extensions are disabled). Let me know if it helped.

**Comment by photopea** [comment]
I think it has been solved, so I will close it now.
