### ISSUE TITLE
API: how to select magic wand, set its tolerance, and exit Photopea after saving

### ISSUE THREAD

**Issue by nibicas** [photopea/photopea#2401]
After I congratulate you on your excellent project, I would like your help in streamlining my App to Photopea connection, through your API. Specifically, I would like to 

1. Select magic wand
   The first step I ask my users to do, after (automatically) opening Photopea with the image at hand, is to select magic wand. It would be useful to do it via the url string.
1. Setup magic wand tolerance to **16**
  This is the second thing I ask them to do. After extensive testing (on quickly removing background in product images), I have found that the default value of **10** leaves a lot of noise around the object, especially when displayed in a dark background. A value of **16** is just about right for nearly all cases with a solid background (usually white). The problem is that Photopea cannot remember this (PS, does), so my users will have to repeatedly change 10 to 16. 
1. Exit Photopea
  After hitting File -> Save, and successfully communicating back an "OK!" message, I would like to close the Photopea tab, and be ready for the next image. As it is, right now, my users have to hit [X] (or press Ctrl+W) AND dismiss the (rather annoying) "Leave page" dialog. 

Before bothering you, I did my homework: read your docs (including the comments), PS docs, played with the script dialog (and the environment setting, of course), and googled a lot. I cannot make it work!

Thank you in advance for your time and your contribution to the community!

**Comment by photopea** [comment]
Hi, thanks! I made following changes:

- I set the default Tolerance of the Magic Wand to 16
- Now, Photopea remembers the options of Magic Wand even after you close it and open it again
- Magic Wand options can be changed in our API: https://www.photopea.com/api/environment
- to change the tool, you can run a script. I found the answer here: https://stackoverflow.com/questions/29109677/photoshop-javascript-how-to-get-set-current-tool

The following script will change the tool to a Magic Wand in Photoshop and Photopea:

```
setTool("magicWandTool");

function setTool(tool) {
    var desc9 = new ActionDescriptor();
    var ref7 = new ActionReference();
    ref7.putClass( app.stringIDToTypeID(tool) );
    desc9.putReference( app.charIDToTypeID('null'), ref7 );
    executeAction( app.charIDToTypeID('slct'), desc9, DialogModes.NO );
}
```

**Comment by nibicas** [comment]
Wow - you are a treasure!

I've tested all and they work as indented.

Any idea for my 3rd wish? Is there anything I can enter into the "script" key of my server response, to close all documents and the Photopea tab, as well?

Nevertheless, I sincerely wish you the best and I will do my best to persuade my clients to go premium!

**Comment by photopea** [comment]
According to the current web standards, a webpage can not close itself :(

But if you opened Photopea tab from your script, you can close it from your script, too, see here: https://stackoverflow.com/questions/2076299/how-to-close-current-tab-in-a-browser-window

**Comment by nibicas** [comment]
Yes, this is the first thing I did... 

But Photopea (obviously) uses the `onbeforeunload` event and thus the browser prompts the user, so the window is not closed!

I understand Photopea uses some kind of "dirty" flag, to control this behavior. If I open an image and do absolutely nothing, then there will be no prompt. But if I make a selection and copy that to the clipboard - not doing any editing on the image itself - then the prompt is there! Photopea is very eager to think that something has changed...

Anyway, could a server response indicate that "everything is saved" and "all changes can be discarded" and so "please, allow me  to close the window gracefully"!

**Comment by photopea** [comment]
How exactly do you save your file? After the file is saved, the "unsaved" flag should be removed and the message about unsaved work should not appear. Unless you do some editing after the saving.

**Comment by nibicas** [comment]
I think we are getting somewhere... because I sense that you puzzled and I can understand why.

My procedure (simplified) is as following:

1) I open Photopea (in a new tab) and load the image, via the url
2) I select the background, reverse the selection, copy it *(via the menu option only - there is a bug here if you are interested)*, make a new document (which **rightfully** and as in PS has the selection's dimensions), and paste it.
3) I hide the background layer and hit `File -> Save`

So, there are 2 documents: the *initial* (staff we want and staff we do not want) and the *new* one (staff we only want).

As I understand, the `File -> Save` command clears the "unsaved" flag *only* for the second image. The first image - although there was no editing done (only select and copy) - is considered "unsaved" and that is the one who triggers the dialog!

I've just tested and it is indeed so...

**Comment by photopea** [comment]
It is not clear to me, what you are doing manually and what you are doing by code.

I guess by "reverse" selection you mean "inverse", and by "staff" you mean "stuff" :)

If you want to close the first, unsaved document, with code, you can e.g. save it to outer environment. Or I could add a capability to go back to the original state in History.

**Comment by nibicas** [comment]
I am sorry for my grammatical errors :-(  Of course, "inverse" and "stuff" are the indented words...

I am not doing anything by code (yet). I will certainly implement the magic wand pre-select snippet, but after that - and up to the point of `File -> Save`, everything will be manual.

I am not using an `iframe` - I use `window.open()`. Anyway, I tried your suggestion. Specifically, I sent the following response:

`{"script":"for(var i=0;i<app.documents.length;i++){app.documents[i].saveToOE('jpg');console.log(app.documents[i].source)}close();","message":"OK!"}`

It doesn't work. I tried also interactively, via the `File -> Script`, to no avail. What works, **partially**, is this:

`app.activeDocument.saveToOE('jpg'); close()`

...and I say "partially" because although the asterisk indicator (of unsaved work) is removed from the document name, the browser still prompts me! Event if it worked, however, it wouldn't suit my case because I will always have (at least) 2 documents open.

I still think that the easiest solution would be to implement a function to clear the "unsaved" flag from all open documents, or unhook from the `onbeforeunload` event, or anything that can allow your `window.open()` API consumer to just close Photopea programmatically, without the browser's prompt.

**Comment by photopea** [comment]
In your script, you are calling a global function close() which does not exist. It would fail in Photoshop, too.

    for(var i=0;i<app.documents.length;i++){app.documents[i].saveToOE('jpg');console.log(app.documents[i].source)}close();

I tried this and it works.

    app.documents[0].saveToOE('jpg');   app.documents[0].close();

**Comment by nibicas** [comment]
YES!!! 

The `app.documents[0].close();` did the trick!

I cannot thank you enough for your patience!


PS 1: The `close()` thing is about closing the window. which certainly works - at least in Firefox which I just tested. No errors in console, either. I will try in Chrome later. I am too excited for that, right now.
PS 2: You can close (no pun indented) this issue. I do not close it myself, to give someone else the chance to gain something out of it.

**Comment by photopea** [comment]
You don't need to call  app.documents[0].close(); .  If you call saveToOE() on every document, all documents will be "ready for closing", so you can close the browser tab from your code.
