### ISSUE TITLE
Error that selected area is blank for both images and text and cannot resize

### ISSUE THREAD

**Issue by SesCarny** [photopea/photopea#2402]
Hey everyone. I'm trying to resize (transform) text and images in Photopea, but suddenly it won't let me. I keep getting an error message that says the text layer must be rasterized first, which is odd since I've had no issues with it before now. When I resterize the text, it then tells me the "Selected Area Is Empty" and won't let me resize it. Plus I'm trying to resize (transform) an image in the same file, but I keep getting an error message that is the same 'empty area' popup, which it is definitely not. Photopea has been working just fine on my PC until a few minutes ago, while working on the same file that I have been all morning. Any ideas as to what is happening?

**Comment by photopea** [comment]
Hi, do you have a selection in your document? To transform a whole text layer, you should not have any selection.

You can remove the selection with Select - Deselect.

If you want to resize just a part of a layer (e.g. the top half of the first letter), you should rasterize the layer (it will not be a text layer anymore).

**Comment by photopea** [comment]
I have to close it because of lack of details.
