### ISSUE TITLE
Pressing "Esc" to exit full screen mode doesn't bring back UI controls

### ISSUE THREAD

**Issue by bduffany** [photopea/photopea#2403]
I accidentally pressed "F" never having used the shortcut before. It went into full screen mode, and I pressed "Esc" to exit full screen mode. However, the UI controls were still invisible.

I panicked for a second, thinking that I wouldn't be able to save my work, since the UI was gone. Needless to say, this was a horrible experience!

I eventually figured out that pressing "F" would restore the UI controls. But it would have been a much better experience if pressing "Esc" restored the UI controls for me.

**Comment by photopea** [comment]
I understand. Now, you can escape the fullscreen mode even with the Escape key :)
