### ISSUE TITLE
"Open and Place" does not respect PDF size and rescales PDFs arbitrarily

### ISSUE THREAD

**Issue by positron96** [photopea/photopea#2410]
I am putting a small PDF into an A4 page and expect the imported image to be same real size (in mm) as the PDF itself. I use "Open and Place" command for this. However, the inserted image is small, its real (mm) size is not equal to PDF's size. Imported size probably depends on DPI of the document (when my A4 document is 600 DPI, the imported image is twice as small as when document is 300 DPI, both have imported image of incorrect size). Is this expected? How do I place a PDF respecting its size?

**Comment by photopea** [comment]
Hi, PDF files consist of pages. Each page as a certain physical size (inches). It contains vector graphics, so it makes no sense to talk about any DPI. Once you decide print it, it can be printed at any DPI you want.

If you open a PDF in Photopea, you should see the true size of the document (in centimeters or inches).

If your inserted PDF is smaller than the first PDF, it is probably because it is actually smaller (e.g. you insert A5 into A4).

You can enlarge your inserted object (or any other layer in a document) using the Free Transform tool.

**Comment by positron96** [comment]
Hi, thank you for response!
My PDF is one page, example can be seen here: 
[PCB_PCB_small_2020-09-03_18-58-21.pdf](https://github.com/photopea/photopea/files/5173089/PCB_PCB_small_2020-09-03_18-58-21.pdf) (it's a PCB). When I open it with "Open" command, the document DPI is 144 (seems arbitrary as PDF itself does not have any DPI, as you noted). The size does match PDF size.

But I did a different workflow. Let me describe it in more detail:
1. Created an empty A4 document with 300 DPI.
2. "Open and place" a PDF document into it. PDF size is around 8x6 cm, but inserted layer is around 4x3 cm (the soft _probably_ assumed same 144 DPI as with "Open" command and scaled the image by 144/300). I would like it to be inserted with original size (8x6cm). As it's a PCB and its printed size must be exactly as specified in PDF, I cannot just "Free transform" it with mouse, since I won't be able to set its exact size manualy.

**Comment by photopea** [comment]
As Photopea is a raster editor, we render every document by rasterizing it into pixels. We render all opened PDFs at DPI 144, but it is completely arbitrary and can be changed in Image - Image Size (by resampling).

I fixed your problem. When you Open and Place a PDF file, its size is adapted to match the physical size of the main document.

**Comment by positron96** [comment]
Amazing! Thank you for increadible work! Photopea is actually the closest thing to Photoshop that I've enountered.

**Comment by photopea** [comment]
Thanks! Except that in Photoshop, you can not edit the content of your PDF :)
