### ISSUE TITLE
Importing SVG colors get darker

### ISSUE THREAD

**Issue by titusfx** [photopea/photopea#2412]
Upload a svg the colors get darker.
Link to the svg that looks fine on the Desktop but not on photopea.

[SVG Link](https://api1.iloveimg.com/v1/download/szfy3dj9yz5fbc1g4482m7qAhpd0rwtyvj3hzf845lp2f3g3zlw0v3sAz0vAnhj82wt3wqjt9qw53qlbk9fdssA9pjhd2y3867dv0Am2fbh028rrhtdm15mg0tA5sgv4vx3v6ppmvtpvbxhqh6y3j03vlvn4wk4t7jAxqyq0b89g0kdw9db1)

This is how it [looks on photopea and how it looks on the OS.](https://ibb.co/v4d44Pt)

**Comment by titusfx** [comment]
This issue is related with [this](https://github.com/photopea/photopea/issues/2413)

**Comment by photopea** [comment]
Hi, could you please share the SVG file with us? Your link does not show any SVG for me.

**Comment by titusfx** [comment]
I [upload it here](https://svgshare.com/s/PH0) and it seems that the problems is still happening with this link.

**Comment by photopea** [comment]
I fixed the problem with colors of your SVG. You should see the correct colors now.

Is there any other problem?

**Comment by photopea** [comment]
I have to close it because of lack of details.
