### ISSUE TITLE
Actions not working

### ISSUE THREAD

**Issue by tanzderphotopea** [photopea/photopea#2415]
Action files take a long time to load, if they even load at all. Hard to open other files after I attempt to put one on another. Very glitchy :(

**Comment by photopea** [comment]
Hi, do your actions contain any special filters, that are not present in Photopea? Photopea can not run all Photoshop actions at the moment (because of missing filters, etc).

**Comment by tanzderphotopea** [comment]
They don't last time I checked, and have worked before! I'll make sure to look them over again.

**Comment by photopea** [comment]
Send your actions to support@photopea.com and I will take a look at them.
