### ISSUE TITLE
Script problem: save / wait until saved...

### ISSUE THREAD

**Issue by Mapsama** [photopea/photopea#2416]
Hi,

i have a problem:
i do some changes on a psd-file and want to save it to my webspace using the script out of the tutorial.
After changing the layers i save it by document.save. This works fine.

But: if i want to close the current window by "window.close();" this works to, but it does not wait until saving is finished (or does not wait for the response from my server) so that the window closes before its saved to my webspace.
Is there any solution for this?

Best Regards

**Comment by photopea** [comment]
Yes, I guess that is correct. If you close a website, the website does not run anymore and can not send anything to your server.

You should not close the website, if you want the saving process to finish. You can make your server send a script, which will be executed by Photopea after the saving finishes, see: https://www.photopea.com/api/

**Comment by Mapsama** [comment]
Thanks for the fast answer, but if my server responds with "window.close();" i get this result:
http://prntscr.com/uc0q2y

its just alerted and does not execute it as a script...

**Comment by photopea** [comment]
Ok I am glad it works :)
