### ISSUE TITLE
Periodically the Site is Unusable

### ISSUE THREAD

**Issue by EricPonvelle** [photopea/photopea#2417]
I cannot reliably trigger it, but periodically if I am doing a lot of work in Photopea, it collapses completely. For example, I was trying to use the move tool, but every single click just duplicated my object to move. It was like I was holding a button but nothing was held. It would also not hide the layer I selected but instead hide all layers OTHER than the one I clicked. Other times, if I am trying to use a selection box to clean up an image it will grow in every direction rather than how I drag.

This happens to me on Linux and Windows, both in Chrome and Firefox.

**Comment by photopea** [comment]
All that behaviour, which you describe, happens, when the Alt key is pressed.

There is a bug in Firefox, such that when you press and release Alt, Firefox does not tell Photopea that the Alt has been released, so Photopea thinks it is still pressed. See here: https://bugzilla.mozilla.org/show_bug.cgi?id=1568130

However, it should not happen in other browsers (just in Firefox).

**Comment by photopea** [comment]
I think it has been fixed.
