### ISSUE TITLE
Can’t "save as psd"

### ISSUE THREAD

**Issue by Ouigy** [photopea/photopea#2418]
Hi,

It doesn’t work when I try to save as psd. I receive an error message and it only propose me to close the app...
![Screenshot_20200906-135732_Photoshop](https://user-images.githubusercontent.com/70845029/92325208-024b7580-f049-11ea-8657-7d08651eae6c.jpg)
Thank’s !

**Comment by photopea** [comment]
Hi, that is very strange. What web browser are you using? Could you try to update it?

**Comment by Ouigy** [comment]
Hi, i’m using the application which i downloaded on the play store, in Android.  I can’t update it...

**Comment by photopea** [comment]
I downloaded the application from the Play Store to my Android phone, I can save files as PSD.

What is this DeX? Could you try it directly on your phone instead?

**Comment by photopea** [comment]
As I have no experience with DeX, I have to close it.

You can try to report it to the developers of DeX, or just try to use Photopea in a normal web browser instead at www.Photopea.com
