### ISSUE TITLE
Can't load specular or normal dds map files

### ISSUE THREAD

**Issue by ReeceBar** [photopea/photopea#2420]
It will literally forever load whenever I import a n.dds or s.dds file. Use this as an example, it won't ever load like all other normal and specular map files. 

[sock_n.zip](https://github.com/photopea/photopea/files/5181396/sock_n.zip)

**Comment by photopea** [comment]
Hi, I found these online DDS to PNG converters: https://convertio.co/dds-png/ , https://anyconv.com/dds-to-png-converter/ . I was able to convert any of my DDS files to a PNG.

I was not able to convert your DDS file to a PNG. Your file says, that it uses zero bits per pixel, which does not make any sense.

Do you know how your DDS file was created? Are you sure it can be opened in any program other than the one which created it?

**Comment by ReeceBar** [comment]
This is an issue with all normal and specular map dds files, I can open
them in GIMP with a DDS plugin, but can't save it as a DDS so no point in
that. Photopea can't even load them. I don't think Photopea has support for
normal and specular maps and was hoping you can add it. These types of
files are used in Bethesda games, I don't know how they differ from regular
dds files.

**Comment by photopea** [comment]
Hi, I fixed the problem, it should work perfectly now.

Thanks for reporting about this issue! :)
