### ISSUE TITLE
LayerComps does not save fill percentage

### ISSUE THREAD

**Issue by brintuss** [photopea/photopea#2421]
When creating a new LayerComp, or updating an existing LayerComp, the fill percentage of layers is not saved. In compasrison, the opacity percentage of layers is saved in a LayerComp.

**Comment by photopea** [comment]
Hi, I just tried and the Fill value is saved in a layer comp. Could you describe what to do to make the Fill value not saved?

**Comment by brintuss** [comment]
I did the following on a pc with:
- Windows 10 (10.0.19041)
- Firefox (80.0.1)
- Chrome (85.0.4183.83 (Official Build))

I first tested it with my own psd, but I get the same result with the demo file pea.psd.

In Firefox and Chrome the result is the same with these steps :
- open the demo file pea.psd
- create a LayerComp
- select layer 'Welcome' in group 'texts' (it actually does not matter which layer is changed)
- change the fill  (not opacity) of the layer to any other value
- create a second LayerComp
- switch between one of the created LayerComps: 
the fill value of layer 'Welcome' will stay unchanged to the value last set, no matter what LayerComp is active.

In comparison to the fill value: the opacity value of a layer does get saved in a LayerComp and will change when another LayerComp is active.

**Comment by photopea** [comment]
Hi, it turns out the Fill value was not implemented in Layer Comps in Photopea at all. I implemented it, it should work well now :) Thanks!
