### ISSUE TITLE
Unable to import .eps file

### ISSUE THREAD

**Issue by SomeshThakur** [photopea/photopea#2423]
I am trying to import the eps file but I see there are some errors thrown in console.
```

pp.js:10409 Uncaught TypeError: Illegal invocation
    at Function.fv.J$ (pp.js:10409)
    at di.LB (pp.js:10359)
fv.J$ @ pp.js:10409
di.LB @ pp.js:10359

```

I have downloaded eps from the freepik website. Here is the link : https://www.freepik.com/free-vector/colors-curl-logo-template_835044.htm

**Comment by photopea** [comment]
Hi, the support for EPS in Photopea is quite limited. We recommend users to convert EPS files to PDF and open PDF in Photopea instead (especially when it is a large file such as yours).

BTW. the archive from Freepik also contains the .AI file, which seems to work quite well in Photopea.
