### ISSUE TITLE
When cropping a file, saving it as SVG & then trying to use it it gives me ERROR!

### ISSUE THREAD

**Issue by ALEXIAVH** [photopea/photopea#2424]
I love Photopea, but for some reason when I crop a file, then save as SVG, when I then try to use the file it says my files are broken, that they are either not compatible or they are corrupted. It says please make sure all files you upload have the correct file extension and are not broken.

**Comment by photopea** [comment]
What do you mean by "using SVG file"? Who exactly tells you the file is corrupted? Could you share your SVG with us?

**Comment by ALEXIAVH** [comment]
The file is EPS file or .eps or .ai  ,  I crop certain parts of the file and then save as SVG file, it lets me do that but when I upload to canva or other programs it gives me the error.

**Comment by photopea** [comment]
Can you open an SVG file in Photopea, save it as SVG and open it in Canva?

**Comment by ALEXIAVH** [comment]
[tiktok.zip](https://github.com/photopea/photopea/files/5191485/tiktok.zip)

[](url)

**Comment by ALEXIAVH** [comment]
What I have done is , I go to : FILE, EXPORT AS, then I choose SVG .svg

**Comment by photopea** [comment]
Your EPS file contains raster graphics. I think there is a bug in Canva - Canva can not load SVGs which contain raster graphics.

You can ask Canva to fix it, or you can disable the "raster graphics" checkbox when exporting the SVG.

![image (1)](https://user-images.githubusercontent.com/15955558/92575182-52644b00-f288-11ea-9234-c1872d49d6ba.png)

You can also export as PNG instead SVG. Canva should not have such problems with PNG.

Also, you can open the .AI version of your file in Photopea, it looks even nicer than the .EPS

**Comment by ALEXIAVH** [comment]
THANK YOU SOOO MUCH!!!! I really appreciate your help and response. :)
