### ISSUE TITLE
Ad changes slow down the browser

### ISSUE THREAD

**Issue by LegendFinder** [photopea/photopea#2425]
I've been using Photopea for a while, and I noticed that the ads off to the side change pretty frequently. When they do, my browser slows down pretty significantly. Actions in Photopea (and even moving the cursor itself) essentially freeze for several seconds while these ads are getting ready to change. If you could look into what manages to slow down the browser so much, that'd help a lot!
(For reference, I use Photopea in Chrome on a Mac.)

**Comment by photopea** [comment]
Hi, what computer (CPU) do you have? 

Changing of the ads should not take more than half a second, and it happens at most every 30 seconds.

**Comment by LegendFinder** [comment]
It's a late 2013 Mac with quad-core Intel i5's.

**Comment by photopea** [comment]
Do ads refresh for longer than half a second?

**Comment by LegendFinder** [comment]
Well the actual ad changes themselves happen for half a second I believe, but it's in the 10 or so seconds before that where Photopea slows down.

**Comment by photopea** [comment]
Like the whole Photopea slows down? I dont think it is because of ads. What exactly do you do in Photopea, that is being slow?

**Comment by LegendFinder** [comment]
Only drawing, really. I've noticed that the problem worsens the more layers I have, though, so that might be one of the reasons why it slows down.

**Comment by photopea** [comment]
Is your WebGL on? Look into More - Use WebGL. Photopea is really slow without WebGL.

**Comment by photopea** [comment]
I have to close it because of lack of details.
