### ISSUE TITLE
Photopea on macbook not using full screen

### ISSUE THREAD

**Issue by TurtleneckTechYT** [photopea/photopea#2426]
Photopea isn't using the full screen for some reason there is a grey empty spot on the right. I am using Brave Browser on the latest version of macbook catalina

<img width="1280" alt="Screen Shot 2020-09-07 at 10 02 52 PM" src="https://user-images.githubusercontent.com/70902629/92395978-d3232a00-f156-11ea-9bf2-6b33e835fc96.png">

**Comment by MichalSZZ** [comment]
The Brave browser have auto enabled adblock for all sites (as I remember).
In that place there should be an ads, which is the the main source of income for author of such great program (Photopea of course ;) ) If You want to have more space there you can buy premium account.
I suggest to turn off adblock - I think you even donkt know that you are blocking ads from Photopea

**Comment by photopea** [comment]
That area should contain an ad. You are probably blocking it.

As there are too many visitors blocking ads in Photopea, I added a message, which will ask the visitor to watch our ads.
