### ISSUE TITLE
Disable ad-blocker popup when no ad-blocker is active

### ISSUE THREAD

**Issue by barnu5** [photopea/photopea#2427]
Admittedly could be my antivirus, but I've got the ad issue again.

This happened a few months ago but was solved.

Basically I get a popup every 30 secs to disable ad-blocker. I don't have any kind of ad-blocking installed, only standard AV.

Tried three different browsers. 

Just wanted to give heads up in case others have the issue!

**Comment by photopea** [comment]
Hi, what number do you see at the end of the message? Like 2 or 5, etc ?

Is the ad displayed correctly in Photopea?

**Comment by barnu5** [comment]
Number 5

And no, the ads are not displaying at all. They were until recently.

**Comment by photopea** [comment]
That means that Photopea can not access the URL https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js .

This URL should be accessable with a standard browser and a standard internet connection. Try to find out what is blocking that URL. Maybe it is an antivirus software or something. Also, try Photopea in Incognito mode (in case it is a browser extension). Most of people do not know they have browser extensions installed.

**Comment by ropo100** [comment]
I am having the same issue. I disabled my ad blocker and the message keeps popping up with the number 6 at the end.
I have tried to disable all extensions, still pops up. I went into Incognito mode and the message stopped popping up. However, I still couldn't see ads on the right side even then. I am using Microsoft Edge Beta version.

**Comment by photopea** [comment]
@ropo100 I do not know much about MS Edge. Maybe it has some ad blocker built in. Have you tried a stable version of MS Edge?

I really dont know what is blocking ads in Photopea in your case :(

**Comment by ropo100** [comment]
Stable Edge doesn't display ads either, without ad blocker and in incognito. The only difference is the ad blocker message doesn't pop up on Stable Edge but does on Beta Edge. Regardless, new Edge is based on chromium so it should work very similarly to Google Chrome.

**Comment by photopea** [comment]
It should work similarly, but your Edge is hiding ads for some reason :( Maybe try to ask here: https://www.reddit.com/r/edge/

**Comment by photopea** [comment]
I will close it now.

**Comment by barnu5** [comment]
Hi @photopea, this issue is happening again. It started happening a couple days ago and has not stopped since.

Message: Ends in `5`
Browser: Chrome PWA (installed)

Same issue seems to happen in browser.

Could it be bitdefender blocking? Although, I have no visible way to confirm or change that. 

Thanks

**Comment by photopea** [comment]
@barnu5  Photopea can not access the domain of our ad partner: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js . Your environment is blocking that domain.

Have you tried to disable all browser extensions?

**Comment by barnu5** [comment]
Thanks, yes, I can’t work out why!

No extensions running

**Comment by photopea** [comment]
Can you access that domain of our partner?

**Comment by barnu5** [comment]
Dull moment, apologies. VPN causes google ads to fail

**Comment by photopea** [comment]
You should ask your VPN provider to unblock all domains for you. Usually, people use VPN to avoid censorship, but your VPN is adding censorship :/

**Comment by barnu5** [comment]
It’s Nord VPN’s security feature,
https://nordvpn.com/features/cybersec/

That said I totally get why you don’t want this.

I will disable VPN to use this app.

Sorry to bother and Thanks for your help :-)
