### ISSUE TITLE
Initial overlay pops up over work.

### ISSUE THREAD

**Issue by Kerobus** [photopea/photopea#2429]
The initial overlay with New project, open project, etc... pops up when I try to open other images to add to my project and I have to refresh the page and lose my progress to get rid of it.
![bug Photopea](https://user-images.githubusercontent.com/71038850/92643721-1a183900-f297-11ea-879d-14ce90cfc18e.jpg)

**Comment by photopea** [comment]
Hi, what browser are you using? Is it a stable browser? If not, could you switch to some regular stable browser?

**Comment by Kerobus** [comment]
I'm using google chrome. It is a stable browser.

**Comment by photopea** [comment]
Could you try to do the same thing in the Incognito mode? Does it work?

**Comment by Kerobus** [comment]
I'll try that when I work on my poster project today. I'll fill you in
then.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by photopea** [comment]
I have to close it because of lack of details.
