### ISSUE TITLE
Error while trying to save a picture

### ISSUE THREAD

**Issue by oleander** [photopea/photopea#2431]
I'm seeing the following error in Chrome `85.0.4183.83` on both Windows and Mac OS when trying to save an image. The error occurs for fresh, unedited images as well as altered.

```
pp.js:207 Uncaught TypeError: Cannot read property 'wg' of undefined
    at Function.ih.Hy (pp.js:207)
    at Object.aa.yW (pp.js:10395)
    at Object.aa.a0b (pp.js:10397)
ih.Hy @ pp.js:207
aa.yW @ pp.js:10395
aa.a0b @ pp.js:10397
setTimeout (async)
cv.aet @ pp.js:10358
cD.sI @ pp.js:10661
hU.A @ pp.js:9
cb.A @ pp.js:7531
cb.A @ pp.js:7531
cb.A @ pp.js:7531
c1.Ml @ pp.js:7552
```

![image](https://user-images.githubusercontent.com/220827/92747150-347c1080-f384-11ea-9fbe-8da190126db3.png)

``` json
{
   "files":[
      "https://domain.com/editor/7cd5fad54ee6dd8368611538d6c4712d/images/362927"
   ],
   "server":{
      "version":"1",
      "url":"https://domain.com/editor/7cd5fad54ee6dd8368611538d6c4712d/images/362927",
      "formats":[
         "jpeg"
      ]
   }
}
```

Any idea what the problem could be?

**Comment by photopea** [comment]
Hi, it is hard to tell what is the problem. Could you tell me the real URL, so that I can reproduce it somehow myself?

**Comment by photopea** [comment]
Also - try basic things first, such as updating your web browser and disabling all browser extensions.

**Comment by oleander** [comment]
Disabling uBlock solved the problem. Thanks!

**Comment by photopea** [comment]
You also use "jpeg" in the "formats" array, and it will not work. Use the "jpg" string to refer to the JPEG format, as described in our specification: https://www.photopea.com/api/

**Comment by oleander** [comment]
Thanks, that solved the second problem I had.
