### ISSUE TITLE
Cage Warp

### ISSUE THREAD

**Issue by LegendFinder** [photopea/photopea#2432]
Hi, I was wondering if you could add a cage warp feature to Photopea, where you can surround an area with anchor points and use those to deform the object.

You can check the documentation in Gimp (https://docs.gimp.org/2.10/en/gimp-tool-cage.html) or this video (https://www.youtube.com/watch?v=jL8TepHX0qE) to see how it works, if you want.

Optionally, instead of having a separate tool options window for switching between editing and deforming the cage like what's used there, you could hold shift or ctrl instead (though Gimp uses shift to select and move multiple anchor points at once).

Thanks!
-LegendFinder

**Comment by photopea** [comment]
Hi, I think we already have such feature, it is called the Puppet Warp: https://blog.photopea.com/photopea-4-7-puppet-warp.html

**Comment by LegendFinder** [comment]
I've used Puppet Warp in the past, and while it is similar in some ways to Cage Warp, there's a few differences. 

For one, with Puppet Warp you can't place anchor points outside the object you want to deform, only inside. Also, if you delete an anchor point, the object snaps back to where it would be without it, whereas with Cage you have the option to edit the anchor points after placing them down. 

If you have, say, a curved structure, and you want to straighten it out a bit, I think using Cage Warp would be easier than using Puppet Warp. 

Let me know what you think!
-LegendFinder

**Comment by photopea** [comment]
I know that Puppet warp works differently. But at the moment, we dont have resources to create a Cage warp :(

I think all you can achieve with the Cage warp, can be achieved with the Puppet warp, too.
