### ISSUE TITLE
Payment not possible error

### ISSUE THREAD

**Issue by Woosoo** [photopea/photopea#2434]
Payment not possible error

Message : 

Notice: Undefined property: stdClass::$state in /var/www/vhosts/photopea.com/httpdocs/papi/order.php on line 122
string(255) "{"name":"INSTRUMENT_DECLINED","message":"The instrument presented was either declined by the processor or bank, or it can't be used for this payment.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"c831ec126e149"}" Payment was already accepted

I tried to pay several times, but an error occurred.

Please check.
Thanks.

**Comment by photopea** [comment]
Hi, that is really strange. I think nobody reported such problem before.

Could you check your bank if there is enough money? If the money was taken from your account, could you tell me your name, so that I return it back to you?

**Comment by photopea** [comment]
I have to close it because of lack of details.
