### ISSUE TITLE
Open from URL cropping images from google drive

### ISSUE THREAD

**Issue by castlemanj** [photopea/photopea#2435]
I'm a new user and I need my students to be able to open images in Photopea from their google drive accounts. When I use the open URL feature for images found in a general image search they import fine. But when I use it for images from google drive only a cropped version imports. This is happening from both my district and personal google drive accounts. In both cases I set the permissions so anyone with the link could edit the files but still only got cropped versions. 
![Opened from public URL in general image search](https://user-images.githubusercontent.com/71194971/93005401-784a5380-f505-11ea-925d-27524aed3458.jpeg)
![Opened from google drive URL](https://user-images.githubusercontent.com/71194971/93005407-88fac980-f505-11ea-95a1-b84a121082b1.jpg)

**Comment by castlemanj** [comment]
The first image is opened from a public URL in a general image search. The cropped image is what happens when I open the URL from google drive

**Comment by photopea** [comment]
Hi, can you open your image URL in Incognito window? What image do you see?

**Comment by castlemanj** [comment]
Same issue when using an incognito window. The image imports cropped like
this.

**Comment by photopea** [comment]
As you see, your problem is not related to Photopea at all. Your URL just links to a image which you call "cropped".

You should probably ask Google about how to achieve the URL of the "uncropped" image.

**Comment by castlemanj** [comment]
Thank you. Yes, I have already reported the issue to Google

**Comment by photopea** [comment]
You can also right-click any image and choose "Copy Image" and go to Photopea.com and press Ctrl+V.

Or  right-click an image and choose "Save image as", and then, open it in Photopea from your computer.
