### ISSUE TITLE
image viewer

### ISSUE THREAD

**Issue by SaiGaneshReddy3648** [photopea/photopea#2437]
it does not make me 1100*490 px

**Comment by photopea** [comment]
Hi, what do you mean?

**Comment by SaiGaneshReddy3648** [comment]
I mean the, I cann't make the size pic into 1100*490 px

**Comment by SaiGaneshReddy3648** [comment]
but it makes it self in 871*490px help me

**Comment by photopea** [comment]
Do you mean using Image - Image Size window?

You probably locked the aspect ratio. There is a chain button, which lets you unlock it.

**Comment by SaiGaneshReddy3648** [comment]
yeah

**Comment by SaiGaneshReddy3648** [comment]
thank you

**Comment by photopea** [comment]
Ok I am glad you figured it out.

**Comment by SaiGaneshReddy3648** [comment]
thank you
