### ISSUE TITLE
Actions feature not working at all

### ISSUE THREAD

**Issue by baddiebgk** [photopea/photopea#2438]
For the past week, I have been trying to use the actions feature and whenever I add the action layer onto my photo, the site glitches. Please, I really want to use actions to edit my photos. It would be great to see if this can be fixed! Thank youu!! :)

**Comment by photopea** [comment]
Hi, what do you mean by the "action layer"? You can learn how to use actions here: https://www.photopea.com/learn/actions

**Comment by baddiebgk** [comment]
[](url)
<img width="1197" alt="Screen Shot 2020-09-13 at 6 11 17 PM" src="https://user-images.githubusercontent.com/71234699/93029886-abb3dd80-f5ec-11ea-8a15-b3ea739973f9.png"> I apply the action to the photo, but it doesn't work, and then the screen begins to glitch when I want to edit my photo even further using other features.

**Comment by photopea** [comment]
Hi, Photopea does not have a full support for Photoshop actions at the moment.

Please, send me your .ATN file to support@photopea.com and I will take a look at it.

**Comment by baddiebgk** [comment]
Hi,

Here are the files. They used to work before last week. I am unsure of what
happened.

**Comment by photopea** [comment]
Hi, I do not see any files. Could you send them to support@photopea.com ?

**Comment by baddiebgk** [comment]
I sent them over!

Thank you!

**Comment by photopea** [comment]
I am very sorry for the problem. It is fixed now.
