### ISSUE TITLE
Text Tool not working

### ISSUE THREAD

**Issue by Rushftw** [photopea/photopea#2440]
Hey I really need help so basically I was making a skin for a game and when I wanted to add my name the text won't show up everything is good but just the text won't show up I don't know what I did wrong but please help me

**Comment by photopea** [comment]
Hi, I think some of your browser extensions is preventing Photopea from drawing text.

Try to disable all browser extensions. You can also try Photopea in Incognito mode, where all extensions are disabled.

**Comment by Rushftw** [comment]
I did try
but didn't work in incognito mode either

**Comment by Rushftw** [comment]
OMG thank you so much

**Comment by photopea** [comment]
so did it work?
