### ISSUE TITLE
Filter - Filter Gallery - Error when delete

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2445]
When I go to Filter - Filter Gallery and click delete button in the bottom photopea shows this error in console and stops working properly
Uncaught TypeError: Cannot read property 'v' of undefined
    at g.GEfc.CU (pp.js:8449)
    at g.GEfc.gk (pp.js:8443)

**Comment by photopea** [comment]
I fixed it, thanks!

BTW. thank you for your PSD templates. You can add more keywords into the description, e.g. when someone searches for "sea", they would not find your template.
