### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by filipedeschamps** [photopea/photopea#2446]
![image](https://user-images.githubusercontent.com/4248081/93479680-712e9700-f8b1-11ea-8910-b04a6715306a.png)

I've already refreshed and it's ok, but in the past couple days the performance of the editor is very different from before.

**Comment by photopea** [comment]
Hi, what do you mean by "it is ok"? You can not access www.photopea.com? Can you access other websites, e.g. www.google.com ?

**Comment by filipedeschamps** [comment]
I mean, I refreshed and Photopea opened, everything looks ok, just wanted to give you a heads up about this 500 👍

**Comment by photopea** [comment]
Since neither you neither me can reproduce it, there is no way to "fix" it. It is hard to tell what caused it :(

**Comment by filipedeschamps** [comment]
Sure no problem 🤝
