### ISSUE TITLE
can't paste images after allowing clipboard permission

### ISSUE THREAD

**Issue by glm27** [photopea/photopea#2448]
Hi there, does someone know why I would not be able to paste images? I've tried CTRL + V and 'edit' 'paste' and I get the same message each time about allowing Photopea access to clipboard. I have done that. I am using Chrome (up to date).

**Comment by photopea** [comment]
Hi, can you try to disable all browser extensions? Does it help?

**Comment by glm27** [comment]
I just realized the file I was trying to paste is a PNG...resolved. Thanks!
