### ISSUE TITLE
I can't change layers in photopea 

### ISSUE THREAD

**Issue by Gemstealer12321321** [photopea/photopea#2449]
![Photopea1](https://user-images.githubusercontent.com/71464570/93518777-26794300-f8e2-11ea-91e4-be0878a6e35c.jpg)

**Comment by photopea** [comment]
Hi, what if you use Photopea in a web browser? Does it work there?

**Comment by Gemstealer12321321** [comment]
yeah but sometimes its the same thing in browser

**Comment by photopea** [comment]
Can you disable all browser extensions? Will it still happen?

**Comment by Gemstealer12321321** [comment]
yes

**Comment by Gemstealer12321321** [comment]
i dont think so but i prefer to use the app

**Comment by photopea** [comment]
Did it help to disable browser extensions?

**Comment by photopea** [comment]
I have to close it because of lack of details.
