### ISSUE TITLE
Layer style bug

### ISSUE THREAD

**Issue by imms93** [photopea/photopea#245]
Whenever I click on any layer style, happens this:
![gif](https://user-images.githubusercontent.com/30982542/29328269-49705cd2-81f2-11e7-9753-700b3a5afbee.gif)

**Comment by photopea** [comment]
Hi, you are in a "text-entering mode" and you can not only type text in this mode. You should escape it before doing other things. Please, see https://www.photopea.com/learn/text-layers 

Or do you think it should work differently?
