### ISSUE TITLE
When lowest path has "Subtract" mode, compositing uses bounding box instead of curved form

### ISSUE THREAD

**Issue by xilehence** [photopea/photopea#2450]
When composing a shape with multiple subpaths, if the first (lowest) subpath is "Subtract," and the subpaths are not rectangular, the compositing seems to use the bounding box rather than the actual subpath.

![image](https://user-images.githubusercontent.com/30189507/93550823-41fa5180-f9a7-11ea-9ba2-55004250946a.png)

**Comment by photopea** [comment]
Hi, could you share a PSD with us? You can publish it with File - Publish Online - PSD.

**Comment by xilehence** [comment]
https://www.photopea.com/#iXkmGEkNR

(Problem confirmed on macOS in Firefox and Safari.)

**Comment by photopea** [comment]
Hi, I fixed it.

Surprisingly, Photopea became 50 Bytes smaller after this fix (I removed more code than I added).
