### ISSUE TITLE
Unable to Choose Custom Color for Shapes

### ISSUE THREAD

**Issue by reverseflash010** [photopea/photopea#2451]
For some reason I cannot choose a custom hex color when adding a shape (i.e. rectangle/circle).

Am I missing something?

See attached pictures...

Thanks!
![2020-09-19_11-36-14](https://user-images.githubusercontent.com/71566393/93686693-c9f65f00-fa6c-11ea-8130-aa49a4d0b780.png)
![2020-09-19_11-37-23](https://user-images.githubusercontent.com/71566393/93686694-ca8ef580-fa6c-11ea-8be6-542607f549a7.png)

**Comment by photopea** [comment]
Hi, the Fill of the shape can be edited only in the Fill drop-down menu. The foreground color (in a toolbar) is not used for shapes.

Click the color in the Fill menu.

![Background](https://user-images.githubusercontent.com/15955558/93686888-a3124a00-fab9-11ea-97a0-db5b4d497aad.png)
