### ISSUE TITLE
cannot select multiple layers with ctrl and clicking

### ISSUE THREAD

**Issue by laineybird** [photopea/photopea#2452]

**Comment by photopea** [comment]
Hi, I just tried and it works fine for me.

Did it work in the past? What browser do you use? Can you try to disable all browser extensions?

**Comment by laineybird** [comment]
No it hasn’t worked for me, I am currently using internet explorer, and I
do not have any extensions applied.

**Comment by photopea** [comment]
Photopea does not work in IE or the old Edge browser. Try to get a browser
that is not older than 3 years

neděle 20. září 2020 laineybird <notifications@github.com> napsal(a):

> No it hasn’t worked for me, I am currently using internet explorer, and I
> do not have any extensions applied.
>
