### ISSUE TITLE
Not enough RAM

### ISSUE THREAD

**Issue by Ab00d1982** [photopea/photopea#2453]
![1600602811337](https://user-images.githubusercontent.com/71592543/93710661-17e49300-fb51-11ea-9e4e-af42cc21e487.jpg)
Hi there I faced a problem with the Psd editing files on my Huawei MatePad Pro. when I want to save as smart object it says that not enough ram. By the way the MatePad pro has 6gb ram
![1600602774191](https://user-images.githubusercontent.com/71592543/93710653-07ccb380-fb51-11ea-8308-f035b7375784.jpg)

**Comment by photopea** [comment]
Hi, can you update your web browser? Also, how many documents did you open and how large are they? At some point, even 3 GB might not be enough.

**Comment by Ab00d1982** [comment]
Hi
The browser i used has the latest update. 
And I tried firefox and google chrome as well. but same problem one gave me not enough ram and the other crush. 
Regarding the files it’s an ipad psd mock up around 250 mb with many layers as you know. when i open the back smart objet and put any pictures and save it as smart it gave me the same error not enough ram
Note: only the ipad and laptop mock up gave me this error 
The phone and credit card and headset mock ups didn’t give me that error

**Comment by photopea** [comment]
I think it is what Photopea says it is: Your computer does not have enough RAM to open such large PSD file. Try to work with smaller files, or get more RAM memory into your computer. We can not do any magic - we can not put 1 GB of data into 0.5 GB of memory.

**Comment by Ab00d1982** [comment]
The maximum size of file was 226 MB who talked about 1 gb

**Comment by photopea** [comment]
A PSD file is compressed. After you open it, it is decompressed and needs between 4x and 15x more memory than the PSD size.

**Comment by LorincJuraj** [comment]
Sorry for reopening this issue, but I have similar problem. I am trying to open large .xd file and I get an error `Not enough RAM. Need 3344MB). The thing is, my PC has 32GB ram of which is currently 70% (over 20GB) free. I guessed it has something to do with browser limiting ram usage, but I tried Chrome, Firefox and Brave with the very same result. And AFAIK chrome has 4GB RAM limit per single tab. Solution for me would be ability open only some groups/artboards.

**Comment by photopea** [comment]
I think modern browsers do not have a limit of 4 GB per tab.

I just opened a 18 megapixel JPG in Photopea (a layer takes 72 MB = 4x18). I duplicated the layer 100 times, and Chrome is using 7.2 GB of RAM. This code allocates 16 GB of RAM and it also works well: https://jsfiddle.net/pao17u9x/1/

Photopea rasterizes everything. 32 GB of RAM might not enough. Try to separate your XD file into several smaller files.

**Comment by LorincJuraj** [comment]
So why does it say "Needed 3344MB" ? And the fiddle doesn't work for me. When I run it the console just says: 
`"<a class='gotoLine' href='#42:34'>42:34</a> Uncaught RangeError: Array buffer allocation failed"`

I have found a workaround for my problem by modifying manifest of the .xd file to make Photopea think there are just 2 artboards, but would love to work with it without the hack. Possibly with ability to just pick some of the artboards. If I can be of any assistance let me know.

**Comment by photopea** [comment]
I do not know much about Chrome on Ubuntu :(  Maybe you can open your Sketch file in Photopea opened in Firefox.

**Comment by LorincJuraj** [comment]
Your fiddle works on Firefox, but my XD file shows the same error on all tested browsers including Firefox. But don't worry about it. I've fixed that by modifying the manifest file. But ability to import/open only certain artwork in Photopea would be very helpful. But I can imagine there are more important things to implement and your time is limited. Thanks for your help and for great product anyway.

**Comment by MichalSZZ** [comment]
Maybe when user want to open some file with artboards (other than PSD) this should be work like opening PDF file in Photoshop?
When i open PDF i have window with preview of each page in that PDF and I can chose which one I want to open. There are also some other options.
Look:
![obraz](https://user-images.githubusercontent.com/38118273/117947005-151cf500-b310-11eb-8eb3-ec4ad1ca0a50.png)

**Comment by LorincJuraj** [comment]
This looks amazing. If the thumbnails would be too complicated even the multi select dropdown with artboards names would probably be sufficient. But of course image is worth 1000 words :-) And if some lazy designer names the artboards `artboard 01` to `artboard 99` then the thumbs would be really appreciated.

**Comment by dentistformyeye** [comment]
>In photoshop when I chose more than one page, it each one as a separate project (not as an artboards - like in Adobe Illustartor).
>I think that is good solution for all PDF and XD, Sketch, Figma files

Unless there's another easy way to edit and re-export PDFs, I'd still want an option to open PDFs the way Photopea currently does

**Comment by SIAviationYT** [comment]
I was trying to open a fjs732 PSD file but it says´Not Enough RAM (need 16MB) pls help I using a Chromebook with 1.10Ghz CPU

**Comment by photopea** [comment]
How large is your PSD file and how much RAM do you have in your computer?

**Comment by RazorSpark** [comment]
How do you get more RAM on photopea

**Comment by ELFIDOmob** [comment]
I have the same issue and actually  have 64 GB RAM and the issue appears in all browsers

**Comment by photopea** [comment]
Google Chrome refuses to give a website more than 8 GB of RAM. If you work with too large or too many documents in Photopea, try to do it in Firefox.

**Comment by camoody1** [comment]
> Google Chrome refuses to give a website more than 8 GB of RAM. If you work with too large or too many documents in Photopea, try to do it in Firefox.

So are you saying that if I'm working with several large open documents at once, I will get better performance from Photopea if I use Firefox instead of Google Chrome or Microsoft Edge? My PC has 32GB of RAM. I would hate for my web browser to be the limiting factor in my application performance. That's just awful.

**Comment by photopea** [comment]
It is not related to the performance at all. Simply, if you open a 10 GB PSD file in Photopea in Chrome, it will crash, but it might not crash in Firefox. And 99.999% of Photopea users never open that large documents in Photopea.

**Comment by camoody1** [comment]
> It is not related to the performance at all. Simply, if you open a 10 GB PSD file in Photopea in Chrome, it will crash, but it might not crash in Firefox. And 99.999% of Photopea users never open that large documents in Photopea.

Ahhh... gotcha. That would be one helluva big file! 😆

**Comment by jackloomen** [comment]
sadly i constantly get "blended areas are too large" when trying to auto blend. it's disappointing. machine is 128gb...

**Comment by camoody1** [comment]
> I have 128 GB of physical RAM. My project file is 170 MB. Still having this issue "Not enough RAM" when saving.

What browser are you using?

**Comment by photopea** [comment]
Do you really have 128 GB? Could you show us a screenshot?

Many users have a phone with a 128 GB of storage and they think it is RAM.

**Comment by fidlip** [comment]
@photopea I am also facing this issue. I have 48GB RAM on my desktop station. When I open one 112MB PSD file, everything is OK and still 50% of memory is available (many other apps open). Then I need to open another PSD (300MB) to compare content with the first one and it shows for example something like: "Not enough RAM! (needs 211MB)"
This is memory consumption after first file open:
![image](https://github.com/user-attachments/assets/f765234c-ac5b-420c-b6f1-65d258d71461)

**Comment by photopea** [comment]
Photopea uses a GPU acceleration by default. Is your GPU RAM limited in any way? You could try to disable WebGL (more - Use WebGL) before opening files.

**Comment by builder-main** [comment]
Hi there, on a 64GB machine and Opera when saving I still get a 2gb ram limit error (tried disable WebGL as well). PSD is large, like 1.6gb

**Comment by photopea** [comment]
Right now, all Chromium-based browsers have the same bug - they do not allow allocating a single piece of memory bigger than 2 GB. 

I have reported it to google over four years ago: https://issues.chromium.org/issues/40055619

So a layer of 500 million pixels is not possible (4 bytes per pixel), but two layers of 400 million pixels should be fine.

**Comment by builder-main** [comment]
Thanks! It works in Firefox indeed. perfect answer

**Comment by ataberkw** [comment]
Chrome saying 3000mb needed. Firefox opens it easily. And no lag while operating.
