### ISSUE TITLE
"transform Selection" transforms picture content, not selection

### ISSUE THREAD

**Issue by SebiTimeWaster** [photopea/photopea#2454]
As is: i have selection, choose "transform Selection" and expect to transform the selection (flipping horizontally for instance), but it transforms the picture content laying under the selection and removes the selection.

Expected: the selection is transformed and can still be used afterwards.

**Comment by photopea** [comment]
Hi, I just tried it, and I can not reproduce it :( The selection is transformed correctly in my case.

Are you sure you are transforming a selection, and not e.g a path?

**Comment by SebiTimeWaster** [comment]
yes, 99% sure, but let me retry...

**Comment by SebiTimeWaster** [comment]
ok, after reloading the page it transforms the selection and does not delete it, but it still transforms the underlying picture which is not correct imho...
i presume i produced an illegal state somehow before...

**Comment by photopea** [comment]
Can you describe some steps, how can I make the Select-Transform Selection transform a layer? Maybe in pea.psd in the middle?

**Comment by SebiTimeWaster** [comment]
i created a screencast for you: https://files.timewaster.de/photopea-select.mp4

**Comment by dentistformyeye** [comment]
This is expected behavior. The "marching ants" outline is just there as a visual guide; "selection" refers to the pixels that are selected. (For example, pixels that are not "fully" selected might not be included in the outline.)

For a crude workaround:
1. Prepare a transparent layer.
2. Make your selection on any layer.
3. Click the transparent layer and transform the selection however you need to.
4. Click back to whichever layer you need to use the selection shape on.

**Comment by dentistformyeye** [comment]
"Selection" refers to the pixels that are selected; the outline is just a visual guide. (In fact, pixels that aren't "fully" selected might not be included in the outline.) Whatever you do to the selection is supposed to affect the content. If you want to transform just a selection outline, make your selection, switch to a transparent layer, transform the selection, and click back to whichever layer you need to use the selection on.

However, moving the selection should move the content, yet only the selection outline moves after the flip in your video, which is unusual.

**Comment by SebiTimeWaster** [comment]
@dentistformyeye that is not true, you have two options "Free Transform" which is for transforming the selected pixels and "Transform Selection" which is to transform only the selection.

**Comment by photopea** [comment]
@SebiTimeWaster you are right, this is a bug in Photopea. Too bad you never mentioned the right-click, I would know it right away :D

**Comment by SebiTimeWaster** [comment]
404 correct keyword not found ^^

**Comment by photopea** [comment]
Fixed, thanks for reporting! :)

**Comment by dentistformyeye** [comment]
The right-click menu is still performing "Free Transform" actions on the selected content when "Transform Selection" is active.
1. Make a non-symmetrical selection on an image.
2. Right-click and click "Transform Selection". Drag a corner of the transform box. (Only the selection outline changes.)
3. Right-click and click "Scale". Drag a corner of the transform box. (The selected content changes.)

**Comment by photopea** [comment]
@dentistformyeye I can not reproduce it now. Can you reproduce it now?

**Comment by dentistformyeye** [comment]
I can't reproduce that anymore. Transform Selection works as expected, but Free Transform is acting weird now. When Free Transform is active, everything in Edit > Transform works properly. However, choosing something from the right-click menu causes Free Transform to act like Transform Selection.
1. Make a non-symmetrical selection on an image.
2. Right-click and click "Free Transform". Drag a corner of the transform box. (As expected, the selection outline and selected content change size.)
3. Right-click and click "Scale". Drag a corner of the transform box. (Only the selection outline changes.)
4. Click Edit > Transform > Scale. Drag a corner of the transform box. (This reverts to expected behavior as described in step 2.)

**Comment by photopea** [comment]
@dentistformyeye  I can not reproduce your step 3. In my case, both the selection and the selected content are changing.

**Comment by dentistformyeye** [comment]
I'm very confused now. Free Transform is back to working as expected for me too.
> The right-click menu is still performing "Free Transform" actions on the selected content when "Transform Selection" is active.
> 
> 1. Make a non-symmetrical selection on an image.
> 2. Right-click and click "Transform Selection". Drag a corner of the transform box. (Only the selection outline changes.)
> 3. Right-click and click "Scale". Drag a corner of the transform box. (The selected content changes.)

This is happening to Transform Selection for me again.

> i created a screencast for you: https://files.timewaster.de/photopea-select.mp4 and reproduced it in two different browsers

What @SebiTimeWaster recorded is also happening again.

**Comment by photopea** [comment]
@dentistformyeye The video that you mentioned does not correspond to the three steps that you mentioned.

I can not reproduce the video or the three steps anymore. Could you record your own video so that I can see what actually happens?

**Comment by dentistformyeye** [comment]
https://youtube.com/watch?v=zaz3dYvDDwA

**Comment by SebiTimeWaster** [comment]
have you cleared your cache and/or tried another browser?

**Comment by SebiTimeWaster** [comment]
it works in my browser

**Comment by photopea** [comment]
@dentistformyeye You make a selection with a Lasso tool, right-click: Transform selection, right-click: Rotate 90, and the selected part rotates.

I can not reproduce it, I tried multiple times. Only the selection is rotated in my case.

Can you reload Photopea multiple times? To make sure you are not using a two weeks old version.

**Comment by dentistformyeye** [comment]
Reloading and disabling extensions doesn't resolve the issue. Free Transform and Transform Selection interfere with each other depending on which one you use first.

1. Reload Photopea. Make a non-symmetrical lasso selection.
2. Right-click and click Free Transform.
3. Right-click and click Rotate 90. Click the checkmark.
4. Deselecting is optional.
5. Make a new non-symmetrical lasso selection. Alternatively, continue to use the current selection.
6. Right-click and click Transform Selection.
7. Right-click and click Rotate 90.

Result: Transform Selection acts like Free Transform.
To get the converse, perform the same steps, but exchange Free Transform and Transform Selection in steps 2 and 6.

**Comment by photopea** [comment]
You are right, there really was a bug. It happened only if you used both Free Transform and Transform Selection, one after another (which I did not do in my tests).

It should be fixed now.

**Comment by dentistformyeye** [comment]
Thanks for the fix.
On a different note, did you intend for the Edit > Transform actions to always behave like Free Transform regardless of whether Transform Selection is active?

**Comment by photopea** [comment]
Yes. Originally, they were supposed to transform layers / selected areas without activating the Free Transform.
