### ISSUE TITLE
Feature request: Layer Mask editing mode

### ISSUE THREAD

**Issue by SebiTimeWaster** [photopea/photopea#2455]
One of the biggest downsides compared to PS is that i cannot see the layer mask directly, it makes it a lot harder to manipulate it.

awesome would be alt + click to activate that view, but i presume alt would work in browsers, so maybe a right click menu option?

**Comment by photopea** [comment]
Hi, you can alt-click the raster mask in Photopea and see the mask-only view (black and white). We added that feature about five years ago.

**Comment by SebiTimeWaster** [comment]
That does not work in any of my browsers, tested with Vivaldi (Chromium), Chrome and Firefox, all under Linux.

**Comment by photopea** [comment]
Maybe there is an issue in your linux? In some operating systems, Alt+click acts as a right-click, so there is no way to actually do an alt+click.

Alt+click is used a lot in Photopea.

**Comment by SebiTimeWaster** [comment]
yes, you are right, i found the setting interfering with it. 

for documentation if someone else has this problem in Mate Desktop, set this to "Super" and restart your browser: 
![image](https://user-images.githubusercontent.com/3726309/93712712-cdb2e000-fb57-11ea-90bc-0bd55c6103cb.png)
