### ISSUE TITLE
I Cant See Letters as I type them 

### ISSUE THREAD

**Issue by dontwannamakeaccountbutihaveto** [photopea/photopea#2458]
When im trying to add text, I can't see the text that im putting in. For this the website is unusable and I hope it'll be fixed soon.

**Comment by photopea** [comment]
Hi, try to disable all your browser extensions. You are probably using an extension which clears the text in Photopea.

**Comment by dontwannamakeaccountbutihaveto** [comment]
The only extension i have is Honey and i got that after the glitch

**Comment by photopea** [comment]
You probably have more extensions which you do not know about.

Try to open Photopea in the Incognito mode, where all extensions are disabled. Can you see the text in that case?

**Comment by dontwannamakeaccountbutihaveto** [comment]
I've tried this now and it doesn't help the situation.

**Comment by dontwannamakeaccountbutihaveto** [comment]
i went into incognito

**Comment by dontwannamakeaccountbutihaveto** [comment]
This same issue arises when I'm using the paint tool as well which is very
unfortunate.

**Comment by photopea** [comment]
All it happens in Incognito?

What browser and version do you have?

sobota 26. září 2020 dontwannamakeaccountbutihaveto <
notifications@github.com> napsal(a):

**Comment by photopea** [comment]
I have to close it because of lack of details.
