### ISSUE TITLE
Open from URL is cropping images

### ISSUE THREAD

**Issue by mrshaney** [photopea/photopea#2459]
When I try to open an image from my Google Drive using Open from URL, it crops the image.  I have never encountered this before, but both my students and I have been having this problem this week.  The links I'm using will open the images at full size in a new window, so the problem does not seem to be with the links.

The screenshots show it as it opened in Photopea and as it opened in a new window.

Thank you!
![Screen Shot 2020-09-20 at 2 59 20 PM](https://user-images.githubusercontent.com/71610501/93722174-149dd700-fb52-11ea-9bdb-37cd62980639.png)
![Screen Shot 2020-09-20 at 2 59 43 PM](https://user-images.githubusercontent.com/71610501/93722177-1a93b800-fb52-11ea-9f49-a4b822ea59fd.png)

**Comment by photopea** [comment]
Hi, can you send us the URL of your image? Did you try to open it and in a browser and save it to your computer (not related to Photopea)? how does it look like?

**Comment by mrshaney** [comment]
Yes, I can save it to my computer and it looks normal.  Here's the link I was using: https://drive.google.com/file/d/1iIW-u2atCr5xvWmQBEcJzPQk06hmd2y0/view?usp=sharing

**Comment by photopea** [comment]
That URL is not a URL of the image. It is the URL of a webpage with multiple images. 

In that case, Photopea scans the HTML code of the webpage and opens the first image URL it finds in it.

Try to get a real URL of the image, or save the image from the Google Drive to your computer, and open it from your computer.

**Comment by photopea** [comment]
You can also try our extension for Google Drive: https://www.youtube.com/watch?v=p7kjmwhlNrA

**Comment by mrshaney** [comment]
Can you show me what you mean by multiple images?  It is only showing one when I open it.

**Comment by photopea** [comment]
So your link is not a link to an image, but to a website.

Photopea scans that website and finds this URL of an image in it: https://lh4.googleusercontent.com/5kZlOaLYYz8bIZEyU_i8dZWLWC6qrSz2Ckm5SFlg_D-Yqv_FxjPCQG4YT-m3OP4=w1200-h630-p . It loads this URL.

You should ask Google about the way to obtain the URLs of your images in their Google Drive.
