### ISSUE TITLE
Cannot create shapes

### ISSUE THREAD

**Issue by imms93** [photopea/photopea#246]
When I click on rectangle, ellipse, line, parametric shape or custom shape, happens this:
![gif](https://user-images.githubusercontent.com/30982542/29328783-fd82ce52-81f3-11e7-879c-81e2ac98ef11.gif)

**Comment by imms93** [comment]
whoops, my bad, i didn't choose shape in the little menu, so it's not really a bug, just me being stupid!

**Comment by photopea** [comment]
Yes, you must choose the mode for these tools, see https://www.photopea.com/learn/vg-creating
