### ISSUE TITLE
Layer styles are not recorded when recording an action

### ISSUE THREAD

**Issue by Emperorlou** [photopea/photopea#2460]
While I have an active recording going on I do the following: 

1. Double click on a layer to bring up the layer style dialog
2. Enable the Stroke style, change some settings, then press OK

The action is not updated with the new layer style and rerunning the action does not style the layer.

Thanks for an otherwise amazing software! Worth buying!

**Comment by photopea** [comment]
It should be fixed now, thanks :)

**Comment by Emperorlou** [comment]
Nice!
