### ISSUE TITLE
Auto-Align feature says "no similarity found" when there is definitely overlap between my images

### ISSUE THREAD

**Issue by MoonDancerLu13** [photopea/photopea#2461]
Auto-Align feature says "no similarity found" when there is definitely overlap between my images. I've manually stitched them now, but wanted to report that the auto-align feature didn't work even though I followed the tutorial exactly. The 1st 3 files are the photos I was attempting to stitch, and the last 2 are the before and after of attempting to auto-align them.

![Screenshot (1359)](https://user-images.githubusercontent.com/71679225/93836913-40a08180-fc52-11ea-8ea2-b12bda3d7f0f.png)
![Screenshot (1362)](https://user-images.githubusercontent.com/71679225/93836917-44cc9f00-fc52-11ea-9c2b-55e0c1931fbf.png)
![Screenshot (1363)](https://user-images.githubusercontent.com/71679225/93836928-4b5b1680-fc52-11ea-873c-9b47afc35d5b.png)
![Screenshot (1366)](https://user-images.githubusercontent.com/71679225/93841773-a6950500-fc62-11ea-8c09-0335af1919d1.png)
![Screenshot (1367)](https://user-images.githubusercontent.com/71679225/93841782-ac8ae600-fc62-11ea-9d8d-0aaeb5da51ec.png)

**Comment by photopea** [comment]
Hi, Photopea is probably not as smart as you would expect. The images should "overlap" by at least 30% of their area.

**Comment by MoonDancerLu13** [comment]
Good to know, thank you so much for your response! 😃
