### ISSUE TITLE
Text jumps to new line

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2462]
I created text `"CREATED BY PHOTOPEA.COM"` with Type Tool (written in capital letters).
Later I wanted to add more space just before letter "P" so it has more space between Y and P
but when press space on keyboard "PHOTOPEA.COM" part of text jumps to new line.
before I press spacebar:
![image](https://user-images.githubusercontent.com/6370548/93859433-e937fb00-fcbd-11ea-9331-fe3dce8b67a6.png)
after I press spacebar:
![image](https://user-images.githubusercontent.com/6370548/93859475-f3f29000-fcbd-11ea-8d00-8f2af50f1861.png)

**Comment by photopea** [comment]
Hi, I can not reproduce it, could you share your PSD?

**Comment by hxim** [comment]
Yes,
PSD before I pressed spacebar:
https://www.photopea.com/#i1sVFCoXP
PSD after I pressed spacebar:
https://www.photopea.com/#iRTduGu0M

**Comment by photopea** [comment]
It seems like a bug in Chrome, it works well in Firefox.

**Comment by photopea** [comment]
I reported it to Google: https://bugs.chromium.org/p/chromium/issues/detail?id=1132679

I also partially fixed it by making the hidden textarea bigger.
