### ISSUE TITLE
Unable to see text

### ISSUE THREAD

**Issue by KariNewman** [photopea/photopea#2463]
I've never had a problem seeing text before, but now suddenly I'm unable to see it. I've tried using "incognito" mode and that didn't help. It appears that several users have been experiencing this lately, so I assume that this is an actual bug.

**Comment by IamFlea** [comment]
It looks like the same issue as https://github.com/photopea/photopea/issues/2467 

Select text layer.
Window > Character > Leading > Auto. 
Is the checkbox checked?

**Comment by photopea** [comment]
I changed some settings, does it work now?

**Comment by KariNewman** [comment]
Yes, it does. Thank you!
By the way, I am in Chrome.
