### ISSUE TITLE
Can't see text

### ISSUE THREAD

**Issue by BryanMcCallum** [photopea/photopea#2464]
When trying to use the text box you can't see any text. This happens on firefox, chrome, and brave browsers. Not sure why it won't display anymore.

**Comment by IamFlea** [comment]
It looks like the same issue as https://github.com/photopea/photopea/issues/2467 

Select text layer.
Window > Character > Leading > Auto. 
Is the checkbox checked?

**Comment by rferreira98** [comment]
> When trying to use the text box you can't see any text. This happens on firefox, chrome, and brave browsers. Not sure why it won't display anymore.

I've experienced this, although the Leading solution did not solve the problem.
For whoever is having this problem, I suggest checking the fonts. I had to wait a bit for the font loading (it's quite slow these days).

**Comment by photopea** [comment]
We changed the font loading options. Does it work better now?

**Comment by rferreira98** [comment]
> We changed the font loading options. Does it work better now?

It does look a little bit faster. Loading a template (Insta Story) it took some seconds loading but it began right away after selecting the template. 
Before it took a while to just start loading fonts.

**Comment by BryanMcCallum** [comment]
Yes it is working, took about 30 seconds to load, I understand this issue slightly, I would suggest if you are unable to make the load time faster, an alert could be triggered if font is typed in a text box within the first 10-20 seconds of the site being loaded. Otherwise all good! Thanks for your hard work on photopea it has been a great tool when at work.
