### ISSUE TITLE
Errors being seen launching photopea

### ISSUE THREAD

**Issue by OwenMorganAOS** [photopea/photopea#2465]
We are getting the following error on some occasions from multiple machines

A refresh resolves the issue however it seems to be happening a few times a day

Could not Parse content for https://content.quantcount.com/adchoices/v2/css/300x250.css.map

We have a paid for team to remove ad's

**Comment by photopea** [comment]
Hi, is there an error when Photopea can not load your PNG image? Are you sure your HTTP server works well? Can you send me a screenshot of how the error in Photopea loosk like?

**Comment by OwenMorganAOS** [comment]
Yes I sure can it does not happen on every load but yesterday a few users had this happen on different machines and internet connections


[cid:image001.jpg@01D691C3.DFA26360]


Then the debug console shows

[cid:image002.jpg@01D691C3.DFA26360]

Thanks

Owen
Owen Morgan

Head of IT Operations
Tel: 03300 538 505
Email: owen.morgan.aos@bca.com
2 Alexandra Gate, Ffordd Pengam, Cardiff, CF24 2SA
To find out more about our products please click here<http://uk.autosonshow.tv/Autos-On-Show-Information-Page.asp>
[cid:image003.png@01D691C3.DFA26360]
[cid:image004.png@01D691C3.DFA26360]
This email and any attachments to it may contain confidential information intended for the addressee only. If you are not the intended addressee, you are strictly prohibited from disclosing, copying, distributing or using this email in any way. Unauthorised use of the information contained in this email is unlawful. If you have received this email in error please notify us on info@autosonshow.tv<mailto:info@autosonshow.tv> and delete the email from your system. Information contained in this email cannot be disclosed, copied, distributed or used in any way without the prior consent of the sender. Any opinions, advice or facts given in this email are given without warranty or the intention to enter into an agreement unless specifically stated and confirmed by agreement, letter or such other documentation signed by an authorised signatory of Life on Show Limited. Any personal information contained in this email is strictly the view of the sender and is in no way authorised or attributable to Life on Show Limited (Company number 06763696) or any of its subsidiary or group companies in any way. All emails through the company gateway are subject to monitoring. The company cannot be held liable for any errors or viruses contained in this message. Registered office Headway House, Crosby Way, Farnham, Surrey GU9 7XG, England VAT registration number: GB 972 2351 22

**Comment by photopea** [comment]
I did not receive any image from you. Please, open the issue at Github.com and write a response there.

**Comment by OwenMorganAOS** [comment]
Yes I sure can it does not happen on every load but yesterday a few users had this happen on different machines and internet connections

Please see the screenshot attached
![screenshot PNG](https://user-images.githubusercontent.com/71714307/94036307-136fe280-fdbc-11ea-8f97-6ec0ad0e7e3b.jpg)
![error](https://user-images.githubusercontent.com/71714307/94036325-1965c380-fdbc-11ea-8ef1-b63acf805c6a.jpg)

**Comment by OwenMorganAOS** [comment]
The browser in use was google chrome

**Comment by photopea** [comment]
I think their Google Chrome is at least 12 years old.

You need a browser not older than 3 years to use Photopea correctly.

**Comment by OwenMorganAOS** [comment]
The version of google chrome is very recent from the machine that these screenshots showed up on
Version 85.0.4183.102 (Official Build) (64-bit)
Its working correctly today but yesterday this was happening intermittently for multiple people on different machines and internet connections

**Comment by photopea** [comment]
Make sure the people who use Photopea have a modern browser, not older than 3 years.
