### ISSUE TITLE
Type Tool not working

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2467]
When I open this PSD. Text in text layer is not visible.
When I try to create another new text layer text does not appear.
https://www.photopea.com/#iRqp1aVQv

**Comment by hxim** [comment]
I figured out it is because of Leading setting in character window on 0.00px and Auto not checked but I don't know how this can happen.

**Comment by photopea** [comment]
Hi, I fixed it.  But if you select the text, the selection rectangle height will be 0 (invisible).
