### ISSUE TITLE
i have a permanent loading bar on the website and no matter what i try it stays

### ISSUE THREAD

**Issue by Squaregalaxy9** [photopea/photopea#2468]
![Screenshot 2020-09-22 at 5 41 38 PM](https://user-images.githubusercontent.com/71735978/93944704-09d27600-fcfb-11ea-8e03-61a1a5cb69f0.png)

**Comment by Squaregalaxy9** [comment]
also i somehow got rid off the layers tab

**Comment by photopea** [comment]
Are you using Photopea at www.Photopea.com? Could you disable all browser extensions?

**Comment by Squaregalaxy9** [comment]
yes and i did and now i have the same thing just with ads 
![image](https://user-images.githubusercontent.com/71735978/94162320-34801400-fe4c-11ea-8f88-a40048dc5702.png)

**Comment by photopea** [comment]
That is so strange. Is the "Loading" there right after opening, or you pressed something?

**Comment by Squaregalaxy9** [comment]
always there when i open it

**Comment by photopea** [comment]
Does it work better now? If not, do you see any errors in the web console?

**Comment by photopea** [comment]
I have to close it because of lack of details.
