### ISSUE TITLE
Photopea keeps crashing when adding Smartobjects

### ISSUE THREAD

**Issue by Shawnee06** [photopea/photopea#247]
Hello...the photopea apps keeps crashing as I try to add smartobjects to a PSD file.  I get to the end of the file..and the entire screen just goes blank.

Can you please take a look at this....thanks!

**Comment by photopea** [comment]
Hi, this is very strange. How large is your PSD file? Do you add smart objects by right-click - Convert to Smart Object?

**Comment by photopea** [comment]
I guess we fixed this one too.
