### ISSUE TITLE
Too many ads, lagging my fucking work

### ISSUE THREAD

**Issue by annoyeduser9991** [photopea/photopea#2471]
You have way too many fucking ads.
And you're refreshing them way too fucking often.

I have a good pc, Ryzen 2700x, GTX 1080ti, 16GB Ram, 960 EVO ssd.
And you have made your site annoying as fuck to use, because every fucking 15 seconds, when you cycle 4 new fucking ads, photopea lags for like 2 seconds and causes me to fuck up what ever I was doing.

Chill the fuck out with the ads, getting to where I might as well just pirate real photoshop.
I'd buy it if I used it more than 2-3 times a year on average..,

Edit: I understand you're providing a service, and it costs you money, and you need to run ads, but the ads are impeding the usefulness of the service now.

**Comment by photopea** [comment]
Sorry, we do not reply to posts containing offensive language.
