### ISSUE TITLE
Some fonts only showing regular but in MacOs Font Book shows all subfamilies

### ISSUE THREAD

**Issue by nospam2k** [photopea/photopea#2473]
I tried to load Bahnschrift.ttf into Photopea and is only showing regular for subfamily, yet in MacOs Font Book shows all the subfamilies once installed.

Font is available here for test: https://fontsnetwork.com/bahnschrift-font-family/

I tried installing all of the ttf's and just the main ttf with the same results. I also tried refreshing the page in my browser.

**Comment by photopea** [comment]
Hi, that is a variable font and Photopea does not support variable fonts yet :(
