### ISSUE TITLE
Cant do anything

### ISSUE THREAD

**Issue by Hellorhigh** [photopea/photopea#2474]
Layers are no longer showing and I am unable to make any edits (none of the tools work)

**Comment by photopea** [comment]
Are you using Safari 14? Photopea does not work in it.

**Comment by Aidanp1913** [comment]
I am using Crome on my Mac Book Pro and nothing is working.

**Comment by photopea** [comment]
Can you disable all browser extensions or try Photopea in Incognito mode?

**Comment by photopea** [comment]
I have to close it because of lack of details.
