### ISSUE TITLE
GIF exporting with extra layer between _a_ layers

### ISSUE THREAD

**Issue by nenochis-1** [photopea/photopea#2475]
Hello. I created a gif using the _a_ command in each layer but when I export it, it adds the background layer in between. I'm confused since I've done this multiple times with Photopea but it exported correctly. I don't know if it is my file or something else...
Below I add the gif. What can I do?
Thank you!
![program 26](https://user-images.githubusercontent.com/46464895/94290044-4979a780-ff1f-11ea-836e-b9a795d9de72.gif)

**Comment by photopea** [comment]
Hi, do you have empty layers or folders named with "_a_"?   They will be converted to frames, too (the layer with "_a_" is enabled, all others are disabled). I.e. for a folder, all _a_ layers in a _a_ folder will be disabled to make a frame out of it.
