### ISSUE TITLE
DO NOT RELY ON THIS PROGRAM! I lost an hour of work!

### ISSUE THREAD

**Issue by techy64** [photopea/photopea#2476]
Photopea froze. I could still click on the "X", but it would not close. I tried to save, but I could not save my work. I could not do anything. I tried to do everything I could, but it said I needed to close that window first. I could not close the window, and thus, had to refresh. I lost an hour of progress because of this. My PC and internet connection were fine. I was using the latest version of google chrome, and had no extensions that would mess with Photopea. DO NOT USE THIS PROGRAM INSTEAD OF PHOTOSHOP. It is very similar, but beware, as huge bugs like these can and will happen.

**Comment by photopea** [comment]
Hi, Photopea never tells you to close any window. It is hard to tell what happened in your case.

If you ever find a problem which you can reproduce, let us know!
