### ISSUE TITLE
Suggestion: make it possible to paste into a layer if it has a mask.

### ISSUE THREAD

**Issue by restinrip** [photopea/photopea#2477]
When I try to paste into a blank layer that has a mask on it, the image pasted appears above the mask unaffected by it. Please allow it to be possible to paste into the blank layer if it has a mask.

**Comment by restinrip** [comment]
Nevermind I did a folder

**Comment by restinrip** [comment]
nevermind

**Comment by photopea** [comment]
I would probably go into Channels, convert a channel into a Selection, then select a mask and fill the selection with black / white.
