### ISSUE TITLE
I want to change the default location where my photopea files are saved. No option.

### ISSUE THREAD

**Issue by sleeper1995** [photopea/photopea#2478]
I want to change the default location where my photopea files are saved but there is no option to do so. Please add this feature because I have a dedicated photopea folder in my downloads but I keep having to manually drag the files into that folder.

**Comment by MichalSZZ** [comment]
As I know, that is impossible to do. Photopea is a web based program. Even if you "install" Photopea, it is stil a browser, with browser limitation. Save as doesn't save file as in native OS programs. It only make command to dowload generated file. You can change that destination in your browser, but all files that you will download in the future, will be downloaded in that place.

**Comment by dentistformyeye** [comment]
@sleeper1995 If you'd be okay with clicking a few times rather than dragging, turn on "Ask where to save each file before downloading" or the equivalent in your browser settings.

**Comment by photopea** [comment]
Change the settings of your browser to modify the mechanism of saving files. The saving is under the control of a browser, not a website.
