### ISSUE TITLE
a button to turn on and off rotation in free transfrom 

### ISSUE THREAD

**Issue by twitchplayskh** [photopea/photopea#248]
yes i use photopea on a tablet xd but the one thing that would make it a lot better is a button to turn on and off rotation in free transfrom. as when i go to re size a thing it just keeps going to rotation and it makes editing hard .

**Comment by photopea** [comment]
Hi, I made the active area of corner points larger. It should be easier to hit them.

Anyway, there are many other buttons in Photopea, that are quite small. I recommend getting a mouse or some stylus.
