### ISSUE TITLE
my suggestions to photope

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#2480]
![photopea update (1) (1) (1) (1) (1) (1)](https://user-images.githubusercontent.com/70863817/94348891-41fdef80-0040-11eb-8fd5-96de215532f5.png)
![photopea update (1) (1) (1) (1) (1) (2)](https://user-images.githubusercontent.com/70863817/94348932-8e492f80-0040-11eb-8fc1-4078b08624db.png)
![photopea update (1) (1) (1) (1) (1) (3)](https://user-images.githubusercontent.com/70863817/94348951-c486af00-0040-11eb-9b97-87ccbaa0c519.png)
![photopea update part2 (1) (1) (3)](https://user-images.githubusercontent.com/70863817/94348997-07e11d80-0041-11eb-93c0-93df8e17ad9d.png)

**Comment by MichalSZZ** [comment]
Wonderful work. Put that redesign on Behance, Dribble etc. That will be a good promotion for Photopea in proffesional designers world.

**Comment by mustafaGFX** [comment]
> Wonderful work. Put that redesign on Behance, Dribble etc. That will be a good promotion for You and Photopea in proffesional designers world.

nice idea... But I am hesitant because of my bad English And because I did not put much effort in designing the presentation ((The main purpose of making a presentation is to convey a sense of a new visual identity))

my Behance: https://www.behance.net/MustafaWorks

**Comment by MichalSZZ** [comment]
I have poor english, but I understand everything that you want to say. Just belive in yourself. You can cut some of UI/UX parts and "personal sugestions" and everything will be great :). That part with logo, idea and splash screen are great. You have you have the knowledge and skills to freelance design for large agencies.

**Comment by mustafaGFX** [comment]
> I have poor english, but I understand everything that you want to say. Just belive in yourself. You can cut some of UI/UX parts and "personal sugestions" and everything will be great :). That part with logo, idea and splash screen are great. You have you have the knowledge and skills to freelance design for large agencies.

I will ..... thank you very much for your kind support

**Comment by mustafaGFX** [comment]
![photopea dark theme test (1) (2)](https://user-images.githubusercontent.com/70863817/94349981-1253e500-004a-11eb-97be-6a37b956ea29.gif)

**Comment by mustafaGFX** [comment]
![photopea dark theme test (2)](https://user-images.githubusercontent.com/70863817/94349987-27307880-004a-11eb-9744-161d3e7fd4a2.gif)

**Comment by mustafaGFX** [comment]
![new-document](https://user-images.githubusercontent.com/70863817/94349998-429b8380-004a-11eb-9565-ceb405533c5c.gif)

**Comment by mustafaGFX** [comment]
![Uploading home_screen.gif…]()

**Comment by mustafaGFX** [comment]
![home_screen](https://user-images.githubusercontent.com/70863817/94350013-64950600-004a-11eb-841c-bd64dad56968.gif)

**Comment by IamFlea** [comment]
That is really good job. :+1:

**Comment by mustafaGFX** [comment]
> That is really good job. 👍

thanks, man.
it will be great if photopea responds to my suggestions

**Comment by MichalSZZ** [comment]
@mustafaGFX if I could give to you one or two suggestions about your presentation, that will be great.
1st one: try to not use justified textes in paragraph. It hard to read sometimes and look bad in narrow columns. That looks good only when you can use hyphenation. If not, from time to time there are huge spaces betwen words.
2nd suggestion. In long text, paragraphs with "all caps" letters, are harder to read.

**Comment by mustafaGFX** [comment]
> @mustafaGFX if I could give to you one or two suggestions about your presentation, that will be great.
> 1st one: try to not use justified textes in paragraph. It is hard to read sometimes and look bad in narrow columns. That looks good only when you can use hyphenation. If not, from time to time there are huge spaces betwen words.
> 2nd suggestion. In long text, paragraphs with "all caps" letters, are harder to read.

thank you for your suggestions...... I already agree with you and I think that you didn't read my previous comment, I said  (( nice idea... But I am hesitant because I did not put much effort in the presentation ((The main purpose of making a presentation is to convey a sense of a new visual identity ))

**Comment by photopea** [comment]
Hi, thanks a lot! You mentioned several nice ideas, and I am very grateful for it!

Regarding the new logo, I feel like I have seen it somewhere. It reminds me a logo of MS Edge and Google Maps, but I think I have seen a more similar one. Did you use any logos as an inspiration?
![microsoftedgenewlogo](https://user-images.githubusercontent.com/15955558/94436227-7981ae80-019c-11eb-8050-e8531ae70e23.png)

Most of your proposals are copy-pasted froms from Adobe Photoshop, e.g. for a new document. I hope you dont expect us to fully copy the UI of another program.
![image](https://user-images.githubusercontent.com/15955558/94436924-5a375100-019d-11eb-9da9-3a016ae8457c.png)

**Comment by mustafaGFX** [comment]
Regarding the new logo, I didn't use any logos as an inspiration... I think you I have seen it somewhere Because this type of logos is very common : 
![مشروع جديد (2)](https://user-images.githubusercontent.com/70863817/94440416-f9f6de00-01a1-11eb-9bbf-d958159d836a.png)


about the new document settings, I actually copied the Photoshop interface with some touches added ... if you think this is wrong just ignore it and I am sorry, But you can add the features that I mentioned and ignore the UI point

by the way, you didn't say anything about the rest of the features : 

- splash screen
- black theme
- templates page
- color wheel
- brush settings
- hide ads button

**Comment by photopea** [comment]
Half of your suggestions are misleading. There is a "DPI" property when you make a document. There is no Hide Ads button - you are not supposed to hide ads. 

It is hard for me to refer to specific parts of your text, as all your text is inside an image. E.g. I have no idea what you mean by "brush settings" - where exactly are they, in what image?

The text in your splash screen is too small and impossible to read. Is such text even needed?

The color wheel is just an option of a color picker. In Photoshop, it is located in the Color panel, and you can choose between multiple options. I can add it, but I don't know if anyone would find it, when it is hidden under a drop-down menu.

**Comment by photopea** [comment]
BTW. I remade the Templates into a dark theme, as you suggested.

**Comment by mustafaGFX** [comment]
thanks for responding
actually, I don't know what is misleading in my suggestions and why do you say that and I am very disappointed 

I don’t have to waste my time and effort thinking of suggestions that will make  a program better or design a logo for it or design splash screen image or ...etc ) ..... I volunteered to do this and I was very happy and was waiting for a welcome or a thank you and I never expected this reaction

all my suggestions were: 

- [ ] - logo update ( that is not misleading )
- [ ] - splash screen ( that is not misleading )
- [ ] - darker theme ( that is not misleading )
- [ ] - orientation ( i didn't know that it's already existed )
- [ ] - resolution ( i said resolution, not DPI )
- [ ] - color mode (it's important, not misleading )
- [ ] - BG content ( custom color option and other new options)
- [ ] - templates ( upload button and dark theme and thanks for making it dark )
- [ ] - color wheel ( it is more important than you think, it isn't just an option of a color picker, it's a Color coordinating tool )
- [ ] - adjustment panel ( that is not misleading )
- [ ] - brush angle and folder ( that is not misleading )
- [ ] - go premium or hide ads or subscribe button ( that is not misleading )

my suggestions are not misleading, And I will not gain anything if I did this

**I know you will not answer this, But I know you will read it**

**Comment by photopea** [comment]
@mustafaGFX I am very happy for your work and for your wish to contribute. But I can not just blindly add everything what "looks cool", I need to think about the practical side, too. Also, half of your work are just screenshots of Adobe Photoshop with almost no edits, I think that is not the way how to do design.

What do you mean by "resolution" and "brush angle and folder"?

**Comment by photopea** [comment]
Regarding your logo, I think it is too complicated (many gradients using about 10 colors). If we make it black and white, I think it is not that interesting anymore.

**Comment by mustafaGFX** [comment]
I wrote in a previous comment the following:

> about the new document settings, I actually copied the Photoshop interface with some touches added ... if you think this is wrong just ignore it and I am sorry, But you can add the features that I mentioned and ignore the UI point

I think you didn't read it because of work pressure and I really appreciate your effort ❤️

What I mean by "resolution" is "PPI"
and What I mean by "brush angle and folder" is this :
![Capture](https://user-images.githubusercontent.com/70863817/96632933-bd3d8300-1318-11eb-96a5-520c3918fcc6.png)

**Comment by photopea** [comment]
The resolution, PPI and DPI are usually the same thing. The PPI is used mostly for the printed documents. Photopea already has the DPI parameter, which corresponds to resolution.

Regarding to the Brush angle, it can already be set in the Brush window, and people don't use it very often. I think the drop-down menu looks simpler and cleaner without it.

Additional brush sets - I would love to add more brush sets, but I don't know where to find them. Do you know about any ABR files, which are free to use for any purpose? I found very specific ones (like 150 brushes of various stains).

**Comment by mustafaGFX** [comment]
Regarding the Brush angle, I know that it can be set in the Brush window but it's very tiring and stressful, especially when painting or adjusting the lighting and colors, not just me who says that, almost all the users need that future. **_You can vote on this matter on Facebook or Reddit_** 

BTW, This site offers you free ABR files and they are more than wonderful
https://www.brusheezy.com/free/abr

**Comment by photopea** [comment]
@mustafaGFX  You are the first person who asked for the Angle control in a right-click menu, and there are millions of people using Photopea.

Thanks for the link for brushes. Do you think you can choose specific 5 - 10 ABR files, which will be most appropriate for Photopea? I am afraid people will be like "why there are fifty seven brushes with roses? I need burshes with dogs".

**Comment by mustafaGFX** [comment]
okay I think I can Diverse ABR files

if you want to make sure that photopea users don't need the Angle control in a right-click menu I advise you to make a vote on social media, e.g 
**_what do you think about putting Angle control in a right-click menu_** 
Opinions : 

[ ] I hardly need it
[ ] it will be nice if you do
[ ] I don't think that it's necessary
[ ] don't do that

**Comment by photopea** [comment]
Honestly, I think 60% of Photopea users never used a Brush tool. From those who do, 90% don't know that you can right-click and see such menu. And from those who know about the menu, 90% use only the Size and Hardness, and have never heard about the angle.

If I make such voting, I think 99% of votes would be from people who have no idea what we are talking about. They would vote "Yes", because they think "more is better".

**Comment by mustafaGFX** [comment]
Very logical words 👍

**Comment by mustafaGFX** [comment]
BTW, how can choose the ABR files for photopea , will I send you the links privately or send the files to your e-mail or...... etc

**Comment by photopea** [comment]
You can send me the ABR files to support@photopea.com

**Comment by mustafaGFX** [comment]
I have sent the ABR files to support@photopea.com a long time ago, check it out and let me know what do you think about it, I hope you like them

**Comment by photopea** [comment]
@mustafaGFX I replied to your email two days ago, and asked some questions.

**Comment by mustafaGFX** [comment]
oooh
I'm so sorry, I have 3 emails and I thought that I sent you the files by my work email which is more professional, but it looks like I have sent them by my social email, I checked it out and I will answer you now

**Comment by mustafaGFX** [comment]
I answered you 😇👍

**Comment by mustafaGFX** [comment]
are you sure you don't want this logo, think about it, it's not that bad and still better than the current one, answer me because if you don't want it I will use it in different porous but please think about it

![New Project (4) (2)](https://user-images.githubusercontent.com/70863817/98733438-2f016d80-23a9-11eb-9f28-14ed6082f6f6.png)

**Comment by mustafaGFX** [comment]
without colors and Still not bad

![Swapp Dribbble (1)](https://user-images.githubusercontent.com/70863817/98733770-b818a480-23a9-11eb-806b-887a5702b6bc.png)

**Comment by photopea** [comment]
Hi, thanks, but I am afraid I got too much used to our current logo. You can use it however you wish, it is your logo.

Also, your font is too weird. I think we should use simple fonts like Microsoft, Lenovo or Google logos use.

**Comment by mustafaGFX** [comment]
so the prolem is the font or you refuse the hole changement ..?

if you refuse the changement stuff, watch this

https://www.boredpanda.com/famous-logo-evolution-history-old-new/?utm_source=google&utm_medium=organic&utm_campaign=organic

after watching this If you were still refusing the improvment you can close the issue

thanks ivan :)

**Comment by photopea** [comment]
@mustafaGFX your link is too old and outdated. Many companies changed their logos since then, like e.g. Facebook or Microsoft.

I will close it now.

**Comment by photopea** [comment]
@mustafaGFX BTW. your work is amazing, you are doing everything right. Just keep doing what you are doing and don't pay much attention to "conservative" guys like me :)

**Comment by mustafaGFX** [comment]
This sentence confirms that I am right: 😂😂
> your link is too old and outdated. Many companies changed their logos since then, like e.g. Facebook or Microsoft.

you have just admitted that Many companies  have changed their logos many times, so the improvement is not a bad thing then 😂😂
.
.
.
.

> BTW. your work is amazing, you are doing everything right. Just keep doing what you are doing and don't pay much attention to "conservative" guys like me :)

these beautiful words mean a lot to me ❤️, thanks ivan

**Comment by JoshuaRifareal** [comment]
man @mustafaGFX amazing stuff!

**Comment by TheRadicalDreamer** [comment]
i love all of this new style.

I feel it fits perfectly with Photopea, and it gives the professional look it deserves and will put in the looks of professional suits like it, and hopefully, old designers will recommend it to their younger pals.
