### ISSUE TITLE
Using the gradient tool in layer masks ignores transparency.

### ISSUE THREAD

**Issue by CJxD** [photopea/photopea#2481]
To reproduce:
- Create two layers of different solid colours.
- Create a layer mask on the top colour.
- Select the layer mask for editing.
- Select the gradient tool, and make a gradient from black to transparent or white to transparent.
- Draw the gradient, and note that the transparency is ignored.

**Comment by MichalSZZ** [comment]
@photopea that is very useful feature. For example - you can have separated object from the background (with mask help) and then on that same layer mask make a gradient (white to transparent) from bottom to have really nice effect.

And another thing - the blending mode of a gradient doesn't work when you create black to white gradient on mask that have some masked area on the layer.

**Comment by mrpanderson** [comment]
The blending modes on the gradient tool are also ignored when working on a layer mask. 

To reproduce, 

1. Follow @CJxD's steps above. 
2. Set your colors to the default black and white
3. Drag out a gradient from the left edge of the canvas to the center. 
4. Switch to Multiply mode on the gradient tool. 
5. Drag from the right edge of the canvas to the center. 

You should see the upper layer appearing on both the left and the right, but you will only see it on the right.

**Comment by photopea** [comment]
I have implemented it! Sorry that it took me two years :/

**Comment by CJxD** [comment]
Yay! Great news! Thank you @photopea
