### ISSUE TITLE
Edit > Transform buttons do nothing

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2482]
When a transformation is not active, the options in the Edit > Transform menu do nothing whether or not a selection is active. When "Free Transform" or "Transform Selection" is in progress, the manual scale, rotate, etc options do nothing. The 90/180 rotation/reflection buttons stop the "transform" state but don't actually transform the layer/selection.

**Comment by photopea** [comment]
fixed, thanks! :) I made this bug yesterday, sorry.
