### ISSUE TITLE
Error with Path Select tool

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2484]
After I deleted all points of shape with Direct Select Tool I selected Path Select Tool and then Merge feature in dropdown it crashed with error and Photopea not working properly (can't switch layers)

To reproduce:
1.) Open pea.psd
2.) Go to "pea" layer
3.) Select Path Select Tool and select shape/circle in that layer
4.) Select Direct Select Tool and select all four points of that shape
5.) Press delete on keyboard to delete them all
6.) Select Path Select Tool again and select Merge in dropdown in top bar
7.) Error is shown in console and photopea not working properly

pp.js:10273 Uncaught TypeError: Cannot read property 'IN' of undefined
    at gk.vB (pp.js:10273)
    at cG.Lv (pp.js:10711)
    at cG.aZ.I (pp.js:9)
    at cG.hp.I (pp.js:7547)
    at O.j8.ft (pp.js:5107)
    at cG.update (pp.js:10800)
    at cG.jz (pp.js:10799)
    at cG.dt.alM (pp.js:10557)

**Comment by dentistformyeye** [comment]
For me, the error appeared immediately after selecting the Path Select tool in step 7. The History panel and Layers panel stopped updating visually completely, but still worked. Tools worked, but the workspace and the Channels panel wouldn't update visually unless I were to switch from Layers to Channels or Channels to Layers.

**Comment by photopea** [comment]
Fixed, thanks for reporting! :)
