### ISSUE TITLE
Layer Style window won't close.

### ISSUE THREAD

**Issue by JoshuaWyszynski** [photopea/photopea#2485]
I can interact with the window its self with moving it and clicking the setting in it, but I'm unable to close it or interact with anything out side that window. Closing the tab isn't an option for cause I need to save work. Is there a way to close that window with out losing work or a way to save files with right click inspect (ctrl+shift+I)

**Comment by photopea** [comment]
Hi, could you describe how to reproduce it? I just tried and the Layer Style window works well for me.

**Comment by JoshuaWyszynski** [comment]
I don't fully remember how it happened, all i do remember is that i was trying to figure out a certain shape that I wanted and must have clicked too many things too quickly.

**Comment by photopea** [comment]
Please, if it happens again, try to repeat it, and then, describe how did you do it.
