### ISSUE TITLE
The image is pink

### ISSUE THREAD

**Issue by nicktoia** [photopea/photopea#2487]
maybe the colors are inverted; i didnt even put some edit on it.

**Comment by photopea** [comment]
Hi, can you share your image with us?

**Comment by nicktoia** [comment]
Hi! I dont remember pressing anything, but if I did, I dont know how to
undo this. heeelp 😬

**Comment by photopea** [comment]
Can you share your image with us?

**Comment by MichalSZZ** [comment]
@nicktoia Maybe you are in Quick Mask mode? Try to turn off this icon under colors
<img width="347" alt="obraz" src="https://user-images.githubusercontent.com/38118273/94800454-e1c2d100-03e4-11eb-86b5-0b1b1e56c4d2.png">

**Comment by nicktoia** [comment]
Thanks, but, no, it didn't work... It happens with every pic. I even tried
to shut down my computer, but nothing seems to work

**Comment by photopea** [comment]
Hi, can you try to disable WebGL in More - Use WebGL?

If it does not help, send me your image to support@photopea.com

**Comment by nicktoia** [comment]
it also didn't work

**Comment by photopea** [comment]
can you send me your image?

**Comment by photopea** [comment]
I have to close it because the person stopped responding.
