### ISSUE TITLE
Uncaught incorrect run 1030, undefined pp.js:1661

### ISSUE THREAD

**Issue by tejas239** [photopea/photopea#249]
Facing this issue & unable to open sketch file

**Comment by photopea** [comment]
Hi, can you send us your Sketch file to support@photopea.com ?

**Comment by tejas239** [comment]
Sent

**Comment by tejas239** [comment]
Any update?

**Comment by photopea** [comment]
Hi, it was fixed. BTW. your file has large dimensions. If Photopea crashes, try disabling WebGL (More - Disable WebGL) and open it again.
