### ISSUE TITLE
Text Screen Glitch 

### ISSUE THREAD

**Issue by Wolfnwarriors** [photopea/photopea#2491]
Whenever I try and type in a text box the screen slides over to the left with all of its contents and hinder me from righting the screen, saving the project, or doing anything besides closing out because its a huge screen glitch whenever I try and type of resize some text in the text box. Please Help, what it looks like [https://drive.google.com/file/d/1-cQXE07ZDlHfpvgI43wJglyaJM1-Km9L/view?usp=sharing](url)

**Comment by IamFlea** [comment]
Working link: https://drive.google.com/file/d/1-cQXE07ZDlHfpvgI43wJglyaJM1-Km9L/view?usp=sharing

Did you try to disable your browser extensions?

**Comment by Wolfnwarriors** [comment]
I will try that tomorrow

**Comment by photopea** [comment]
I believe it has been fixed.

**Comment by Wolfnwarriors** [comment]
Thank you
