### ISSUE TITLE
Slider problems with Firefox

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2492]
When I try to change value with mouse (press left button down and then moving left or right and then releasing left mouse button) in case of label in form of image (not text) it instead initiates drag and drop as seen on screenshot.
For example in settings for Guide Guy or Paragraph.
Problem appears only in Mozilla Firefox and works correctly in Google Chrome browser for me.
![image](https://user-images.githubusercontent.com/6370548/94784233-6568c780-03bd-11eb-9d8f-4b37f1923498.png)
![image](https://user-images.githubusercontent.com/6370548/94784124-394d4680-03bd-11eb-976d-342487e0e9ac.png)

**Comment by IamFlea** [comment]
Firefox behaviour is indeed different. After releasing the left button, user needs to perform an additional left click in order to save the value. At least, this action worked to me on Firefox.

**Comment by photopea** [comment]
As I was a bit lazy to report it to Firefox, I modified the code and it does not happen anymore.
