### ISSUE TITLE
Anti-Aliasing of Wand does not work

### ISSUE THREAD

**Issue by SebiTimeWaster** [photopea/photopea#2494]
having "Anti-Alias" option on or off makes no difference.
![image](https://user-images.githubusercontent.com/3726309/94880460-4886cf80-0463-11eb-94be-29873c92e0b7.png)
![image](https://user-images.githubusercontent.com/3726309/94880485-576d8200-0463-11eb-9f23-5f25bda16b61.png)

**Comment by photopea** [comment]
I think it should work the same as in Adobe Photoshop.

**Comment by SebiTimeWaster** [comment]
i am not sure. i closed it because i noticed there is a *slight difference, but the last time i used photoshop was just too long ago to compare it. 

i would not expect so much hard white stops on horizontal and vertical lines, but there is a good chance i just dont understand how the algorythm works. hence the close.
