### ISSUE TITLE
Feature request: option to convert a work path to a saved path

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2495]
When using the Pen tool on Path setting, the Pen tool creates a new work path unless a saved path in the Paths panel is selected beforehand. The work path is temporary, so I would like to able to save a work path by simply renaming it.
https://helpx.adobe.com/photoshop/using/paths.html#save_a_work_path

**Comment by photopea** [comment]
I implemented it. If you rename a work path, it will be converted into a regular saved path (and the work path becomes empty = hidden in the Paths panel).

**Comment by dentistformyeye** [comment]
Thank you!
