### ISSUE TITLE
Glyphs 

### ISSUE THREAD

**Issue by Cakellamc** [photopea/photopea#2497]
I am trying to use glyphs for a certain font, and only some of them work. When I click on other ones there is no error message, they just don't pop up or show up. I highlighted a letter and clicked on one of the non working glyphs and it deleted my letter, but still no glyphs.

**Comment by Cakellamc** [comment]
Bump.

**Comment by photopea** [comment]
Hi, can you find out, which characters produce these glyphs? What if you type (or copy-paste) these characters into a text layer?

**Comment by Cakellamc** [comment]
I'm sorry I don't understand. I am unable to access them through the glyphs panel, and I don't have a list where I can copy/paste the characters into the text layer.

These are some of the glyphs I cannot use:
![image](https://user-images.githubusercontent.com/66096314/94998281-ab20be00-057e-11eb-8e42-1abe80a6230f.png)

**Comment by photopea** [comment]
We do not support this feature (inserting a glyph, which does not correspond to a character) in Photopea.

What if we added a glyph as a new layer - vector shape? Would you like such solution?

**Comment by Cakellamc** [comment]
That would be great and much appreciated!

I believe that these glyphs shown in the photo are part of a style set for the font, do you know how to use style sets for fonts in Photopea?

**Comment by Cakellamc** [comment]
Bump

**Comment by photopea** [comment]
I think adding a shape for a certain glyph would be counter-intuitive. Could you send me your font file, e.g. to support@photopea.com ? Maybe I will figure out how to add these glyphs into the actual text layer.

**Comment by photopea** [comment]
So I think adding glyphs as separate layers is not appropriate, so I will keep it as it is.

**Comment by photopea** [comment]
It is fixed, you can add any glyph as a character into a text layer now: https://github.com/photopea/photopea/issues/3082
