### ISSUE TITLE
Gradient mishap

### ISSUE THREAD

**Issue by websview** [photopea/photopea#2499]
Greeting fellow Photopea enthusiast, staff and the creator of Photopea.

I loaded a gradient pack on Photpea and now the gradient bar shows black when it's ticked and when I click to try and change gradient nothing happens. If I click on the view area of the gradient tool I can edit gradient and use the gradient to fine that way but I have a lot of gradients and I would like to save time.

Thank you, for your attention, and response, ahead of time.

**Comment by photopea** [comment]
Hi, can you share your gradient pack with us?

**Comment by websview** [comment]
Not legally. But I would be happy to share a great number of gradients I make and some other stuff. And I am interesting in furthering Photopea, it is just that I am disabled, on ssdi, not particularly well of monetarily and I do not have photoshop. I Invite you to correspond
![pp](https://user-images.githubusercontent.com/40432802/95016302-0f876000-0607-11eb-9674-5b6d5f812b87.gif)
 with me more directly but keep in mind, I am unable to talk so it will have to be through texting of some form.

**Comment by photopea** [comment]
So you have a GRD file, which does not work in Photopea? I am afraid i can not fix it without having that GRD file :(

**Comment by websview** [comment]
It isn't the gradient file, that is not working, it is the gradient tool, which will not function properly after loading a gradient pack by dropping it over the Photopea interface. If I knew perhaps how to clear the added file from Photopea maybe it would again function, but, I do not know how.

________________________________

**Comment by photopea** [comment]
I need to reproduce the problem somehow (make the problem happen on my computer), to be able to fix it. How can I reproduce the problem?

If your .GRD file is stored in a Local Storage, you can remove it by going to Edit - Local Storag.

**Comment by websview** [comment]
That fixed it, only now I can't use the gradients. Catch 22. But I will figure it out. And I will send some stuff later.
[Animated GIF]
________________________________

**Comment by photopea** [comment]
What do you mean you can not use gradients? Please, be more specific :)

I really need a description of how to make it happen on my computer.

**Comment by websview** [comment]
I hate like hell to have wasted every one's time,  any one's time. But I went to document
how the gradient pack would make the GRD interface glitch and it worked perfectly this time!
No idea what could have caused the problem and I am not interested in trying intentionally to reproduce it.
But anyway, here is a link to the gradient pack I loaded, I hope you have a Deviant art account. I am certain you do.
https://www.deviantart.com/elvensword/art/Heritage-Platinum-Ps-Gradients-78899865
There are lots of free goods there.
[https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/i/95b707f8-c8bb-458c-a710-49f18c0fc5b5/d1az3ix-56f2d642-53a7-48f7-a9b5-fdc2a92b4a0c.jpg/v1/fill/w_600,h_682,q_75,strp/heritage_platinum_ps_gradients_by_elvensword_d1az3ix-fullview.jpg]<https://www.deviantart.com/elvensword/art/Heritage-Platinum-Ps-Gradients-78899865>
Heritage Platinum Ps Gradients by ElvenSword on DeviantArt<https://www.deviantart.com/elvensword/art/Heritage-Platinum-Ps-Gradients-78899865>
Greys this time.. 45 grey based gradients with companions. First one, transparent. 35., especially for swords. ES Platinum.grd and preview in zip.
www.deviantart.com

________________________________

**Comment by photopea** [comment]
Hi, I am glad everything works now.

I have not used my DeviantArt account for the last 15 years :D
