### ISSUE TITLE
resizable right sidebar

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#25]
Hi,

what about own width of right sidebar by resize function? If i have more nested layers with long names i need look on their title.

**Comment by photopea** [comment]
Yes, it is possible to implement :) There are two sidebars on the right, one is collapsed using the button on the top.

**Comment by Studioartcz** [comment]
Yea, button i try and works but i need sometime set custom width :)

**Comment by photopea** [comment]
Done. Sorry that it took me a year.

**Comment by landsman** [comment]
Thanks!
