### ISSUE TITLE
Unable to remove white background layer from AI file

### ISSUE THREAD

**Issue by RudeySH** [photopea/photopea#2500]
Hi there, I have an AI file with many layers, including a layer that represents a white background layer. The white background does not disappear after removing this layer, though. I opened the same file in Adobe Illustrator and was able to remove the background without any issues. Am I missing something or does Photopea not support removing background layers in AI files?

Here's the file. I zipped it because GitHub does not accept AI files: [221475-P155XO-208.zip](https://github.com/photopea/photopea/files/5323811/221475-P155XO-208.zip)

I downloaded the file from here, credits for the artwork itself go to freepik: https://www.freepik.com/free-vector/cartoon-owl-set-four_1586787.htm

**Comment by photopea** [comment]
Hi, Photopea does not support AI files. It supports only these formats:

PSD, XCF, Sketch, XD, FIG, PXD, CDR, SVG, EPS, PDF, WMF, EMF.
PNG (APNG), JPG, GIF, WebP, ICO, BMP, PPM/PGM/PBM, TIFF, DDS, IFF, TGA.
DNG, NEF, CR2, ARW.
