### ISSUE TITLE
copy and paste

### ISSUE THREAD

**Issue by gabbers11** [photopea/photopea#2502]
While I was trying to create a poster for an assignment, I was trying to copy and paste photos but it said that I didn't give photopea permission to access my clipboard. The problem is that I have copy and pasted things on there many times and it never said that.

**Comment by photopea** [comment]
Hi, can you click the lock icon on the left of to www.Photopea.com in your browser? Is the clipboard permission enabled?

**Comment by gabbers11** [comment]
yes, it was allowed.

**Comment by photopea** [comment]
Can you try Photopea in the Incognito mode? Also, are you using Photopea at www.Photopea.com ?

**Comment by Merety91** [comment]
That doesnt work either. Is there another way.

**Comment by photopea** [comment]
@Merety91 Are you the same person as the one who created this issue? What web browser do you use and have you tried it in the incognito mode?

**Comment by Merety91** [comment]
no im a different person with the same problem. And yes i have tried incognito mode.

**Comment by photopea** [comment]
And what web browser do you use? The name and the version?

**Comment by photopea** [comment]
Do you see any error message when you try to paste?

**Comment by gabbers11** [comment]
i use chrome and yes

**Comment by photopea** [comment]
I am confused, if we are talking about the case of @gabbers11  or @Merety91 .

If you have a problem with a clipboard, could you record a short video of opening the incognito mode, opening www.Photopea.com in it, and pasting something into Photopea?

**Comment by photopea** [comment]
I am closing it, because of lack of details.
