### ISSUE TITLE
Lagging

### ISSUE THREAD

**Issue by invisiblevampire** [photopea/photopea#2503]
Photopea is lagging which makes it very frustrating to do anything. If I switch to another tab then go back to photopea the edit I made will show up, but I can't see it happen in real time. I can't accurately position stuff like this. I've restarted my computer and updated it but nothing has changed.

**Comment by photopea** [comment]
Hi, are you using Safari 14? There is a bug in it, try another web browser.

**Comment by photopea** [comment]
I am closing it because of lack of details.
