### ISSUE TITLE
Pages of uploaded PDF 

### ISSUE THREAD

**Issue by outland1995** [photopea/photopea#2504]
Pages of uploaded PDF automatically get rotated 90° right, I tried with multiple PDF files. 
Here is a [screenshot](https://imgur.com/a/EgPmqrw).

**Comment by photopea** [comment]
Hi, how does the PDF look like when you open it in a regular PDF viewer? Are pages not rotated?

If the rotation is wrong, could you send me your PDF to support@photopea.com ?

**Comment by photopea** [comment]
I am closing it because of lack of details.
