### ISSUE TITLE
Layer box on the right of the screen MISSING PLS HELP

### ISSUE THREAD

**Issue by 30FpsGamingYT** [photopea/photopea#2506]
I'm on pc and a very big problem. The layers that are supposed to on the bottom right of your screen are missing. You know your layers and how you press double-tap them to go into the layer settings, like to add a stroke or to add a glow to your item, its not there. My layers won't show up :( The box is there, but it's empty, I really need a fix, otherwise, I can't create thumbnails for my youtube channel!

**Comment by photopea** [comment]
Hi, if you close any window in the sidebar (such as Layers, Channels, History ...) you can open it again by pressing Window - Layers, Window - Channels, Window - History.
