### ISSUE TITLE
I cannot use spot healing brush on new layer

### ISSUE THREAD

**Issue by lissaqueen** [photopea/photopea#2507]
When I want to use the spot healing brush on my new layer that I created, nothing happens at all. I can only use it on the background (original layer). See photo attached. Can someone help please? 
![photopea2](https://user-images.githubusercontent.com/72490911/95301432-e540d700-0880-11eb-9955-04daffd1490b.JPG)
![photopea](https://user-images.githubusercontent.com/72490911/95301437-e6720400-0880-11eb-81d5-2d56b021c851.JPG)

**Comment by MichalSZZ** [comment]
Spot Healing Brush in Photopea doesn't have [Sample all layers] option (like in Photoshop). It's make changes only on that layer (not on new empty layer picking sample from current and bellow).

**Comment by lissaqueen** [comment]
@MichalSZZ Thank you very much!

**Comment by photopea** [comment]
I think we could add an option for sampling all layers. @lissaqueen Is that what you want to happen when painting in an empty layer? 

Or do you expect some result even if you delete a background layer and paint into a new empty layer?

**Comment by lissaqueen** [comment]
This option would be nice! That you can just hide the new layer and the brushing in it instead of making a direct copy of the background first. Like photoshop does it. Thanks for your quick respond and the engagement :) @photopea

**Comment by MichalSZZ** [comment]
@photopea https://youtu.be/-dbgmwQP6Ws?t=22 here is nice trick with that. New layer for Blemishes (B&W adjustments layer is only for help) and then Spot Healing Brush.

**Comment by photopea** [comment]
Lets discuss it here: https://github.com/photopea/photopea/issues/2508
