### ISSUE TITLE
Healing Brush Tool - no blend effect on new empty layer (with sampling from layer bellow)

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2508]
When I make a new empty layer, and want to have nice "healing" effect on separate layer (for example to change opacity of that effect etc.) - Photopea make spots like a clone tool (without tone and color blending).

**Comment by photopea** [comment]
I added the option to choose a source of healing, you can switch it to "All Layers" :)

**Comment by dentistformyeye** [comment]
Feature request: I would like to have sampling options (All Layers, etc.) for Content Aware Fill. It would be useful for non-destructive filling of transparent areas in smart objects.
