### ISSUE TITLE
Selecting things with Color Range

### ISSUE THREAD

**Issue by lissaqueen** [photopea/photopea#2509]
I wanted to select the tree in the picture below, but the only thing I can do is selecting the sky in it. How does the Color Range select the other part of the image or things I want in general? Is this possible?

![Tree](https://user-images.githubusercontent.com/72490911/95317384-6609ce00-0895-11eb-958e-475881c0c9f6.JPG)

**Comment by photopea** [comment]
Hi, you should click on the tree in the workspace, to define a color which should be selected.

Or you can select the sky and then, invert the selection (Select - Inverse).
