### ISSUE TITLE
Doesn't reflect changes until you log out and log back in

### ISSUE THREAD

**Issue by dsunday5** [photopea/photopea#2510]
Hi, I can't paint, change colors.  It doesn't show my changes when I am doing them.  It only shows them when I log out and back in

**Comment by photopea** [comment]
Are you using Safari 14? Photopea does not work in Safari 14.

**Comment by definitelynotaditya** [comment]
When are you planning to fix that?

**Comment by photopea** [comment]
There is a bug in Safari, only Apple can fix it.
