### ISSUE TITLE
Layer not editable

### ISSUE THREAD

**Issue by penm1** [photopea/photopea#2512]
i cant erase or draw on a layer

**Comment by MichalSZZ** [comment]
What type of layer is that?
Is that a normal raster layer or some special layer like a Smart Object, Shape, Text Layer etc.? 
Isn't that layer locked with the padlock icon?

**Comment by penm1** [comment]
Shape layer and has no padlock icon. But i found to way to resolve it

**Comment by MichalSZZ** [comment]
Ok I understand :) All those layers types above - are special layers and it can't b modified by the brush tool ory any other tool (eraser, smudge, healing brusch, stamp etc). If you have shape layer (and want to do with ith with brush) try to click on layer name and change it to raster ("Rasterize").

**Comment by jaimet** [comment]
If anyone else arrives here (google's top search result for "photopea Layer not editable" is this bug report!) and does not understand [MichalSZZ's last comment](https://github.com/photopea/photopea/issues/2512#issuecomment-705414438), read on...

Some of the tools in photopea (such as the "Brush tool", the "Pencil tool", the "Eraser tool", the "Gradient tool", the "Paint bucket tool", the "Blur tool", the "Sharpen tool" and the "Smudge tool") work by directly modifying the pixels in your image. These tools can **_only_** work on 1 **_type_** of layer, and that is a "**_raster_** layer".

The tools listed above cannot work on "shape layers", "smart object layers", "text layers" and "fill layers", as these types of layers do not directly contain pixels - instead, these types of layers contain information about the things that they contain (shapes, smart objects, text, fills etc). If you want to use one of the tools listed above on one of these types of layers, you first need to [convert the layer to a raster layer](https://www.photopea.com/learn/other-layers) - this is called rasterization.

Be aware that when you rasterize a layer, Photopea will "throw away" the information about your shapes, smart objects, text or fill. If you rasterize a "shape layer" that contains a 5cm-diameter blue circle centered at co-ordinate (1000,1000), you will end up with a "grid" of pixels that will correctly show that 5cm-diameter blue circle centered at co-ordinate (1000,1000), but Photopea will no longer know that the "grid" contains a blue circle.
