### ISSUE TITLE
Page doesn't Load when Editing a Layer

### ISSUE THREAD

**Issue by ctfes** [photopea/photopea#2515]
I'm trying to complete a school photoshop project and the layers showing anything when I edit on it. I don't know if you guys have this problem, but I need photo pea to work or I can risk my grade. If the developers can fix this during the weekend, that would be well appreciated. Also, if anyone know a solution to this bug, can you please tell me a solution for photo pea to begin working again.

**Comment by photopea** [comment]
Hi, what exactly is the problem?

"the layers showing anything when I edit on it" - what does it mean? The layers is plural, but "it" is singular. What are you talking about?

**Comment by 30FpsGamingYT** [comment]
Yeah for me too, I have the layers box at the bottom right corner, but none of my layers show up there. Its just blank, is there a fix!

**Comment by photopea** [comment]
Are you guys using Safari 14? It has a bug and Photopea does not work in it.

**Comment by photopea** [comment]
Also, it could be nice if you provided a screenshot, as nobody else reported such behaviour.

**Comment by 30FpsGamingYT** [comment]
no I'm using my pc.

**Comment by 30FpsGamingYT** [comment]
![image](https://user-images.githubusercontent.com/72482544/95510054-31b41180-096a-11eb-835b-14d90a84d0a7.png)
See im missing my layers, This is 1980x1080

**Comment by photopea** [comment]
What web browser is this? Can you disable all browser extensions?

**Comment by 30FpsGamingYT** [comment]
OMG it worked

**Comment by 30FpsGamingYT** [comment]
Thank you so much!

**Comment by photopea** [comment]
So your browser extensions were deleting the Layers panel? What extension was it?

**Comment by 30FpsGamingYT** [comment]
It was working last last week and last week it just broke, i was just using grammerly, Honey ,tubebuddy and adblocker which I have off on the site.

**Comment by 30FpsGamingYT** [comment]
Let me see which one specifly broke it for me, so other know.

**Comment by 30FpsGamingYT** [comment]
Ok, I found out why I was having this problem, you have to have adblocker off, in your google extensions, I've seen notifications about it on photopea.com  and I turned off adblocker and its worked and others times I've had adblocker on and the site would still work. Anyways thanks a lot!

**Comment by photopea** [comment]
What adblocker do you use? Photopea should work fine with an adblocker. Adblocker should not remove the Layers panel in Photopea (but it seems like it does). Maybe you can ask the creators of your adblocker to fix it.

**Comment by 30FpsGamingYT** [comment]
"AdBlock — best ad blocker "
its the generic one, that most people use

**Comment by photopea** [comment]
I tried to install it from here: https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom  but my Layers are not hidden as in your screenshot.

Did you disable all extensions? Can you put the rest of extensions back on? Does Photopea work correctly?

**Comment by 30FpsGamingYT** [comment]
ok then, yes i disabled all the extentions and photopea worked correctly, When I enabled all the extentions expect adblocker photopea worked perfectly. The other extemnt

**Comment by 30FpsGamingYT** [comment]
the other extensions I have is Grammarly, Tubebuddy , and Honey.
