### ISSUE TITLE
New Figma projects cannot be opened

### ISSUE THREAD

**Issue by rommashka** [photopea/photopea#2516]
Today I noticed, that .FIG files cannot be loaded into Photopea. I faced endless loading.
I tried to load some other Figma projects to Photopea, but nothing worked.

**Comment by rommashka** [comment]
upd: it happens with using new Figma projects. I successfully managed to upload a Figma project that I downloaded a month ago. But the same project downloaded today cannot be uploaded to the Photopea.

**Comment by photopea** [comment]
It is fixed now :)
