### ISSUE TITLE
Fonts not loaded yet

### ISSUE THREAD

**Issue by cyclops365** [photopea/photopea#2517]
On loading a saved project, I get the error "Fonts Not loaded yet" at the top. 

My fonts have loaded, but can't edit text in the project.

**Comment by photopea** [comment]
Hi, does it happen every time you try to edit text? Did it happen before? Can you try it in Incognito mode?

**Comment by cyclops365** [comment]
Seems to have resolved now. Thanks 👍

**Comment by photopea** [comment]
What was the problem? So that we can recommend the solution to others with a similar problem.

**Comment by cyclops365** [comment]
So when I loaded a saved project, it came up with Fonts Not loaded yet when I tried to add text to the text already in the document. I closed the window, left it an hour and come back and works fine.
