### ISSUE TITLE
Type tool not working.

### ISSUE THREAD

**Issue by Gameboy3118** [photopea/photopea#2518]
It doesn't show anything when I type. EDIT:its fixed

**Comment by Gameboy3118** [comment]
Ok now it is fixed, the font was not loading

**Comment by mustafaGFX** [comment]
maybe you have a poor internet

**Comment by Gameboy3118** [comment]
> maybe you have a poor internet

Thanks, I had switched to a proxy network so it was not loading

**Comment by photopea** [comment]
Ok I am glad it is fixed.
