### ISSUE TITLE
overtime I go on photepea it always has a problem like today I was trying to make someone a thumbnail and I wouldn't move my layer when I tried then the next time I opened it it was moving when I didn't even touch the layer it would move when my mouse move

### ISSUE THREAD

**Issue by Sintly** [photopea/photopea#2520]
everytime I go on photepea it always has a problem like today I was trying to make someone a thumbnail and It wouldn't move my layer when I tried then the next time I opened it it was moving when I didn't even touch the layer it would move when my mouse move

**Comment by photopea** [comment]
Hi, could you describe how can I make this happen on my computer?

**Comment by photopea** [comment]
I have to close it because of lack of details.
