### ISSUE TITLE
Ctrl+Shift+E crashed photopea

### ISSUE THREAD

**Issue by Scryus** [photopea/photopea#2521]
Used to Photoshop, using some shortcuts here and there. Done with my project, tried to flatten all layers using my muscle-memory shortcut, Ctrl+Shift+E -- everything crashed, unusable, unsavable.

**Comment by photopea** [comment]
Hi, I just tried Ctrl+Shift+E and the document was flattened into a signle layer. What exactly happened? Did the whole screen turned black or white or something else? How much RAM memory do you have in your computer? Is your web browser updated?

**Comment by Scryus** [comment]
Hi there,

Everything updated, 16gb RAM. The screen doesn't change at all really,
everything looks "normal", just nothing functions anymore. Buttons are
still clickable although do nothing.

I've attached a screenshot but don't know if it works through this github
email reply.

[image: image.png]

**Comment by photopea** [comment]
So you still have a problem even after closing Photopea and opening it again? Can you go to GitHub and attach a screenshot there?

**Comment by Scryus** [comment]
I can replicate on my laptop, but I'm sure on other systems it's worked
fine.

I'll attach a screenshot when possible.

JAck

**Comment by photopea** [comment]
I have to close it because of lack of details. If you want, we can keep discussing the closed issue.
