### ISSUE TITLE
Unable to paste even though clipboard permission granted

### ISSUE THREAD

**Issue by baezanat** [photopea/photopea#2522]
Hello, the very first time I used Photopea and was asked about clipboard access permission I accidentally clicked "no". Then I trie to backtrack. I enabled access on the browser (Chrome). I even reset all browser permissions and set the clipboard permission to "allow, always ask". Next time around I answered "yes" but STILL I can't paste any content. I even updated Chrome but I can't seem to get past this impasse.  Alas! Can I get some help please? My operating system is ubuntu 18.04.

**Comment by photopea** [comment]
Press the padlock icon on the left side of "photopea.com" in your browser, and change the clipboard permissions there.

If it is allowed, and you still can not paste, you are probably using a browser extension, which blocks the clipboard. If you don't know which extension it is, try to disable them all.

**Comment by photopea** [comment]
also, use Photopea at www.Photopea.com

**Comment by photopea** [comment]
I guess it has been fixed.
