### ISSUE TITLE
Error with Depth Map in JPEG

### ISSUE THREAD

**Issue by vicnip** [photopea/photopea#2523]
If a jpeg with depth map is rotated 90 degrees as indicated in EXIF, the depth map's shape is rotated by the same 90 degrees but the image of the depth map is not rotated.

**Comment by photopea** [comment]
Hi, can you provide a file which has such problem?

**Comment by vicnip** [comment]
Github does not allow me to send the 4MB photo to you.

Sample image here:
https://drive.google.com/file/d/1sTOE544xQS4bBpcVp1n9SetYYIMFAyNu/view?usp=sharing

**Comment by photopea** [comment]
Hi, I fixed it.
