### ISSUE TITLE
Vectorize Bitmap not working

### ISSUE THREAD

**Issue by doctormarty** [photopea/photopea#2524]
Hello,

Image > Vectorize Bitmap does no longer work, left canvas shows source bitmap, but right canvas with vectorized bitmap is blank. Pushing OK does not do anything either.

Checking console while opening the Vectorize Bitmap yields:

Uncaught TypeError: Cannot read property ‘0’ of undefined at .....

**Comment by photopea** [comment]
I am very sorry, it is fixed now.
