### ISSUE TITLE
Apply same filter to multiple images at the same time (?)

### ISSUE THREAD

**Issue by 100330706** [photopea/photopea#2525]
Is there a way to apply a filter (like sharpening or any other operation) to multiple images at once? I was thinking of automating this via Selenium and Python, but maybe there is just an easier way I do not know.

**Comment by photopea** [comment]
Hi, you can select multiple layers in the Layers panel. The adjustments and filters are always applied to all selected layers.

There is an option Filter - Last Filter, which will apply the last used filter (with its parameters) again.
