### ISSUE TITLE
PSD file wont open

### ISSUE THREAD

**Issue by DonaldDuck46** [photopea/photopea#2526]
Cant open up the downloaded .psd file from Photopea.com. (.fig to .psd)
Receiving message "Could not complete your request because of a program error"

![unnamed](https://user-images.githubusercontent.com/72826156/95915053-9a3d2d00-0d74-11eb-84e9-41788955197c.png)

**Comment by photopea** [comment]
Hi, could you send me your FIG file to support@photopea.com ?

**Comment by DonaldDuck46** [comment]
Sure thing.
ty

**Comment by photopea** [comment]
It should be fixed now. Thanks for your help! :)

**Comment by DonaldDuck46** [comment]
Yes, its fixed. Thank you!
