### ISSUE TITLE
Unable to open eps files

### ISSUE THREAD

**Issue by anandphotopeauser** [photopea/photopea#2528]
Hi,
I was able to open couple of eps files. After a while eps files stopped uploading from my computer.

Please help.

**Comment by photopea** [comment]
Hi, I recommend converting your EPS to PDF, as described here: https://www.photopea.com/tuts/convert-eps-to-layered-psd/

EPS is an archaic format and it should be replaced by a PDF.

**Comment by anandphotopeauser** [comment]
Okay, thanks.
