### ISSUE TITLE
Missing interface elements

### ISSUE THREAD

**Issue by NatashaDK** [photopea/photopea#253]
Lately I keep seeing this, several places in PP :
![screenshot 2017-08-22 at 23 36 48](https://user-images.githubusercontent.com/27579710/29588862-59d4fd52-8793-11e7-8d67-b05757f3098b.png)

**Comment by photopea** [comment]
Hi Natasha, I am aware of this. It is because sliders are gray and the background is also gray. But you can still use them - drag them with mouse, the same way as before.

If you really mind this, please switch to some other color theme, e.g. More - Theme - Black.
