### ISSUE TITLE
the text tool is not typing

### ISSUE THREAD

**Issue by leonardzzz13** [photopea/photopea#2530]
i would like to report that the text tool in photopea is not working because once i tried to type on the text box nothing shows up no matter what i do so i would like to ask that you would fix this problem as soon as possible because i am a student and i need this for one of my projects

**Comment by photopea** [comment]
Hi, you are probably using a browser extension, which blocks the text rendering to all websites. Try to disable that extension.

Let me know if it helped.

**Comment by leonardzzz13** [comment]
yes this really helped thank you
