### ISSUE TITLE
Brush tool has slight darker outline around it and won't go away

### ISSUE THREAD

**Issue by ravinecrusader** [photopea/photopea#2531]
Tried painting with the brush tool, and every time I start a new stroke, there's a darker line around the brush stroke so it's not blending with other strokes.
![Screenshot (37)](https://user-images.githubusercontent.com/72900216/96068807-d783e680-0e6a-11eb-8e6e-745ce6080891.png)

**Comment by photopea** [comment]
Hi, I am 99% sure that you are using a Pencil tool, and not a Brush tool. Switch to a Brush tool :)
