### ISSUE TITLE
Charcoal Filter

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2532]
Can this particular filter be added to the filter gallery?

i use it to modify draw to look like a scketch

:)

**Comment by IamFlea** [comment]
I will try to look on that filter in one or two weeks. We will notify you here as soon as the filter will be available on Photopea.

**Comment by avagp** [comment]
:D

Thanks Flea, are you new to the Photopea's team?

**Comment by photopea** [comment]
@avagp Yes, @IamFlea is a MIRACLE! :)  He got in touch with me and he is helping me add more filters. Actually, the last filters (Solarize, Wind, Sharpen Edges, ... ) were made completely by him, and a few more are coming :)

**Comment by mustafaGFX** [comment]
do you guys create these filters by coding or using specific programs...?

**Comment by IamFlea** [comment]
@avagp It should be there. 

@mustafaGFX We code it. In my case, I code it with blood, sweat, and tea :)

@photopea I guess we can close it :)

**Comment by photopea** [comment]
Yes, it is implemented :)

**Comment by avagp** [comment]
Thanks guys for the filter.
Here is a portrait of my brother using the filter.

Thanks!
![seba](https://user-images.githubusercontent.com/11801254/102526437-66cf9500-407a-11eb-8552-1a15502a2e81.png)

**Comment by IamFlea** [comment]
Wow, that is a good job! :+1: 

If you need any other filters from the Filter gallery just write it here. :)
