### ISSUE TITLE
macOS Safari issue - nothing you do/draw is visible until you click next tool/brush etc

### ISSUE THREAD

**Issue by cudapetr** [photopea/photopea#2534]
Hello there, just 3 days I have a problem in my macOS X Safari browser, when joined to Photopea. Anything I do, draw etc. is not visible until I click another tool in left icon menu. 

I tried basics like restart macOS, restart Safari etc. and nothing works. Only way is to use Chrome, which is not preffered for me, I am using Safari for many years and satisfied.

**Comment by photopea** [comment]
Hi, it is a bug in Safari 14. We are trying to modify Photopea to overcome that bug. See here: https://github.com/photopea/photopea/issues/2447
