### ISSUE TITLE
Rasterizing Layer Styles - Photopea Freezes

### ISSUE THREAD

**Issue by shellysteele** [photopea/photopea#2535]
When I try to rasterize the layer styles on a layer Photopea Freezes.

**Comment by photopea** [comment]
Hi, I just tried it and it worked well.

Can you describe what should I do to make it happen on my computer? Does it freeze every time you try it?

**Comment by photopea** [comment]
I have to close it because of lack of details. You can still reply if you want.

**Comment by shellysteele** [comment]
I'm sorry.  It happens everytime.  I even tried on a different computer
using the same image.  I'm beginning to wonder if it has something to do
with the image itself.

Shelly Steele
Ponder High School
Career & Technology Education
Graphic Design, Money Matters
UT OnRamps Computer Science
Video Game Design, Yearbook, UIL

**Comment by photopea** [comment]
Hi, could you send me your PSD to support@photopea.com ?

**Comment by shellysteele** [comment]
I'm teaching class right now, I will try to send it later this afternoon if
that is ok?

Shelly Steele
Ponder High School
Career & Technology Education
Graphic Design, Money Matters
UT OnRamps Computer Science
Video Game Design, Yearbook, UIL

**Comment by photopea** [comment]
Of course, you can send it anytime.
