### ISSUE TITLE
Photopea not working on Macbook Pro

### ISSUE THREAD

**Issue by scrabini33** [photopea/photopea#2536]
I have created some .psd templates on Photopea and can open them and edit them on all PC's and macbook air computers.  However I cannot edit them on Macbook Pros.  Has anyone else had this issue? When I open the .psd template on a macbook pro i am not able to edit any layers or even hide layers or anything at all.

**Comment by photopea** [comment]
Hi, Photopea should work the same way on all devices and all web browsers.

Can you create a new PSD document in Photopea on your MacBook Pro? Can you work with it?

**Comment by scrabini33** [comment]
Yes it looks like I can create a new one.  But when I import the template I made on a different device I am unable to edit it on a Macbook pro (have tried 8 different MacBook pros) where I can on MacBook airs and Pcs

**Comment by photopea** [comment]
That is really strange. Can you send us a screenshot of what you see? What web browser (name and a version) are you using?

Please, reply at Github.com and not over an email.

**Comment by MichalSZZ** [comment]
@scrabini33 can u share that file? I have Macbook Pro and Windows too and I can test it.

**Comment by scrabini33** [comment]
[Template.zip](https://github.com/photopea/photopea/files/5393553/Template.zip)
Here it is in this zipped folder

**Comment by MichalSZZ** [comment]
On my Macbook Pro (mid 2014) everything is OK. File is opening normally od Chrome, FF and Safari. I can transform, edit and move layers.
But I have older OS version (High Sierra)...

**Comment by photopea** [comment]
@scrabini33 Can you tell us in what browser it does not work?

**Comment by scrabini33** [comment]
It is Safari that I have been having issues with.  I will try it on Chrome later today.

**Comment by scrabini33** [comment]
HMM so weird.  I think it is something to do with the Macbook pros not recognizing them as .psd files when downloading them.

**Comment by photopea** [comment]
What do you mean by "Macbook pros not recognizing them as .psd files"? You should open files in Photopea using File - Open, and save them using File - Save as PSD. The computer does not work with your files, it does not need to recognize anything.

**Comment by scrabini33** [comment]
Yes I do that. And when I File-Open them on a PC or a Macbook Air everything works as it should but when I File-Open them on a Macbook Pro they are completely unusable.

**Comment by photopea** [comment]
What do you mean by "unusable"? Can you describe with words what happens, or share a screenshot?

**Comment by scrabini33** [comment]
I will try to take a screenshot later today.  But what happens is the .psd opens, and I can see all of my layers.  But then nothing that I do edits the psd, so basically it acts like it is a .png or .jpeg instead of a .psd.  Photopea wont let me delete, modify, or add any layers.  If I click he eyeball to hide a layer it just greys out and the layer remains on the screen.

**Comment by photopea** [comment]
I think you are using Photopea from a week ago on your macbook. Try to reload the webpage several times, to make sure Safari is showing you the latest website, not the old one.

**Comment by photopea** [comment]
I will close it because of lack of details.
