### ISSUE TITLE
An option to disable finger touch for drawing on canvas

### ISSUE THREAD

**Issue by kuanyui** [photopea/photopea#2537]
I tried to draw with Samsung Galaxy Tab S6's stylus, and found it's quite easy to mistakenly touch the drawable area (canvas. I'm not mean the canvas of JavaScript) .

I found it's possible to get if a PointerEvent is emitted from touch or a stylus pen:
https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/pointerType

I think it's necessary to make an option in preference to let user disable all touch events for drawing on canvas. Fingers touching should be only for navigation on canvas.

**Comment by photopea** [comment]
I don't understand what you mean. Would you like to "lock" the workspace area, and then unlock it? You can try to switch to a Hand tool for a while, and then, switch back to your previous tool.

**Comment by kuanyui** [comment]
I mean I frequently mistakenly draw some wrong lines or points when trying drawing with pencil or brush, on an android tablet which can accept hand touch or pen as input.

(But the area outside of canvas should be able to be triggered by touching. In fact, lots of app has such design, ex: OneNote, touch for navigation, and only stylus for drawing)

And Photopea has some wrong behaviours when touching and stylus triggering events on canvas, this issue also can be seen in this video:

https://youtu.be/1FgWiF1BBJ8

**Comment by photopea** [comment]
I see. I think that currentlz, a website does not know, whether the current pointer is a finger, or a pen, or a mouse, etc. Even if we know it, we would have to add many additional settings, which could be confusing for many users.

I recommend using Photopea with one kind of pointer only (e.g. only with a pen). You can use the Zoom tool to zoom (click it in the toolbar and then press and move left - right).

**Comment by kuanyui** [comment]
Closed...?!

> I see. I think that currently, a website does not know, whether the current pointer is a finger, or a pen, or a mouse, etc.

Is this API unable to know this? 
![Screenshot_20201017-184111_Firefox Nightly](https://user-images.githubusercontent.com/1370070/96335114-9842d900-10a8-11eb-8ff8-c386812c9c82.jpg)


 Even if we know it, we would have to add many additional settings, which could be confusing for many users.

I don't think this would confuse user... Just a boolean.
I guess the users of some popular laptops with active stylus touchscreen such as Microsoft Surface Pro would encounter such issue, but I have not hardware no confirm it.

> 
> I recommend using Photopea with one kind of pointer only (e.g. only with a pen). You can use the Zoom tool to zoom (click it in the toolbar and then press and move left - right).

In Android, it's impossible to disable touch screen even if stylus is in my hand.
When trying to draw with stylus, palm almost definitely will trigger `touch` event before stylus triggering `pen` event, then Photopea goes chaos.

**Comment by kuanyui** [comment]
Photopea has done lots of hard work and become an astonishing smoothly-worked and rich-featured PWA, I think it's very regreted if it decide not to implpement (should not required too much efforts) supports for tablet.

Photopea has more functions and user-friendly than all of native drawing / picture editor app I've ever tried in Google Play Store and just fits my requirements (I even feel this is more easy to use than GIMP and startup time much faster than it... What a black magic...), I'm verily looking forward to Photopea can add supports for distinguish `pen` and `touch` event.

**Comment by photopea** [comment]
Ok, I will reopen it, but it is hard to tell when I will be able to focus on this :/

**Comment by photopea** [comment]
I implemented the "No Touch" feature.

At the end of a toolbar, there is a virtual keyboard with "No Touch" option. If you enable it, finger touches on the workspace will be ignored (so only mouse and pen events will work).

https://i.imgur.com/TofF3wP.png

**Comment by photopea** [comment]
As there is no response, I think we can consider it to be fixed by our new No Touch feature.

**Comment by kuanyui** [comment]
Not exactly fit what I mean, but much better than before!
