### ISSUE TITLE
filter render clouds doesn't tile

### ISSUE THREAD

**Issue by Unreal-Dan** [photopea/photopea#2538]
photoshop makes perfectly tile-able clouds, these clouds don't tile :(

For example if you fill a 256x256 canvas with clouds, then stretch the canvas and tile the 256x256 cloud it will have a seam.

Not sure how you would go about generating tile-able clouds, I'm sure there is some sort of algorithm for it.

**Comment by IamFlea** [comment]
Confirmed. 

I guess the algorithm might be similar to this algorithm I've just found: https://gamedev.stackexchange.com/questions/23625/how-do-you-generate-tileable-perlin-noise

**Comment by Unreal-Dan** [comment]
For the record, these cloud maps are used in texture/material creation quite often so making them able to tile will make them significantly more useful.

**Comment by IamFlea** [comment]
We will notify you here as soon as we will fix it :)

**Comment by photopea** [comment]
@IamFlea I will fix it right now, it should not take more than five minutes.

**Comment by photopea** [comment]
A little discovery: Photoshop Clouds filter is tileable in the width or height only when the width or height is the power of two (16, 32, 64, 128, ...).

**Comment by photopea** [comment]
Now, the filter should work similar to Photoshop.
