### ISSUE TITLE
Screen resolution problem

### ISSUE THREAD

**Issue by CrysoK** [photopea/photopea#2539]
Is it supposed to look like this? (empty space on the right side)
Google Chrome.
Resolution 1360 x 768.

![image](https://user-images.githubusercontent.com/57516378/96324531-a0dbd680-0ff8-11eb-9ea7-cab5e91780be.png)

**Comment by photopea** [comment]
Hi, there should be advertisement on the right side.

Please, do not block ads in Photopea. Nobody wants to pay for Photopea Premium, so we would not exist if everybody hides ads like you do.
