### ISSUE TITLE
[FEATURE REQUEST] Add the current document name to "Save to Server" 

### ISSUE THREAD

**Issue by Fluxflashor** [photopea/photopea#2540]
Photopea is an excellent web app, thanks for creating it! I have a request for some additional support when it comes to saving documents to an external server.

---

**An Example Scenario**

- The `server` parameter was specified in the original Photopea request.
- A PSD file has been loaded into Photopea from a URL.
- I have double-clicked the document's filename in Photopea and changed it.
- The save button has been hit which sends the JSON request to the server.

This currently provides us with a `source` key in the JSON with the PSD file's URL that it was loaded from. We can get the original filename (and full URL) of the PSD.

--- 

**Problem**

- We don't know the new name of the document.
- Knowing the name of this file would be useful to the server to save the JPEG as the new file name.

---

**Solution**

- Add an additional key to the save to server JSON (perhaps "psdName")
- Set the value of this key to the current name of the PSD.

(If the name of the PSD didn't change from the loaded PSD, maybe the new key,value isn't included)

----

I understand you can create custom saving functionality to perform actions like these already, I just think this would be some great additional value to the embedded version of Photopea.

**Comment by photopea** [comment]
Hi Robert,

the names of files are a bit tricky. Even if you open a JPG or a PNG in Photopea, the name is converted to a .PSD.

You can make File - Save button run a custom script. That custom script can run XYZ, and then, do Document.save();

The XYZ can be any script. E.g. it can modify the "source" of a document to correspond to a document name in Photopea:

    app.activeDocument.source = app.activeDocument.name;

**Comment by photopea** [comment]
I guess we figured it out.
