### ISSUE TITLE
fill tool (shift + F5) is not working

### ISSUE THREAD

**Issue by zorkotA3** [photopea/photopea#2543]
I work with 360 ° photos and use Photopea to remove the tripod from the camera. To do this, I use the fill tool in the "content sensitive" option and with the mixing mode in "normal". This was working perfectly until the other day, now, when I give the command, nothing just happens.

(Sorry for my English, I'm not fluent)

**Comment by photopea** [comment]
Hi, I am very sorry, it is fixed now.
