### ISSUE TITLE
Number displayed as square when used with chinese character

### ISSUE THREAD

**Issue by jenglamlow** [photopea/photopea#2544]
Hi, when I try to insert text with the combination of chinese character and number, the number part will be displayed as square box.

For example, when I insert 大家好1234 into Text Layer, it is converted to 大家好 ▯▯▯▯. 

Could you take a look? Thanks

**Comment by photopea** [comment]
Hi, I think that your chinese font does not support digits. Can you select your digits and set them to a different font, e.g. Deja Vu Sans?

**Comment by jenglamlow** [comment]
Hi, I have tested with other fonts, by filtering the font with Chi-Jap-Kor. It is displaying correctly now. Thanks for the help

**Comment by photopea** [comment]
Ok, great!
