### ISSUE TITLE
I can't change the name'layers

### ISSUE THREAD

**Issue by moraymanazari** [photopea/photopea#2547]
Hello, I can't change the name'layer why?

**Comment by photopea** [comment]
Hi, I just tried it and it works well. How exactly do you change the name of the layer?

**Comment by moraymanazari** [comment]
I do double click in the layer

**Comment by photopea** [comment]
and what happens next?

**Comment by moraymanazari** [comment]
Nothing, No, just now

**Comment by photopea** [comment]
So it worked in the past? Are you writing us on Facebook or it is someone else?

**Comment by photopea** [comment]
I think you are doing something wrong. You can learn how layers work at www.Photopea.com/learn/layers
