### ISSUE TITLE
No Permission to Clipboard

### ISSUE THREAD

**Issue by WRDSBart** [photopea/photopea#2550]
Last week, I encountered an issue with copying and pasting in Photopea on my PC.  I could copy/paste in every other program (Word, Photoshop, etc.) from multiple sources, but could not paste the same photos in Photopea.  It said I hadn't given permission to use the clipboard.  With my IT guy, we checked and reset the permissions and granted them... and it still said the same thing.  Now that I've cleared the data on my Chromebook, it's saying the same thing on this device.  And again, I've been copying and pasting in multiple programs so I know the function is working.  It appears to only be an issue with Photopea.

**Comment by photopea** [comment]
Hi, can you disable all browser extensions? Extensions can modify the behaviour of your browser and the behaviour of all websites.

**Comment by photopea** [comment]
I have to close it because of lack of details. But you can still reply if you want.

**Comment by WRDSBart** [comment]
i wasn't sure how to reply.  I have extensions because of teaching,.so
closing them down isn't an option.  I also haven't put any new ones on my
Chromebook to warrant the change from your site.
I need to figure this out or I can't use Photopea for my classes.

~V~
"Playing small does not serve the world.
There is nothing enlightened about shrinking so that others won't feel
insecure."
M.W.

**Comment by photopea** [comment]
Can you press the "PrintScreen" on your keyboard and paste it into Photopea with Ctrl+V?
