### ISSUE TITLE
Clone stamp wont turn off red circle

### ISSUE THREAD

**Issue by Brianaflory** [photopea/photopea#2551]
![image](https://user-images.githubusercontent.com/73257673/96788687-bf4f2280-13a8-11eb-86de-8e79d22ea61c.png)
it will just get bigger and reset itself

**Comment by photopea** [comment]
Hi, can you close Photopea, open it, and make it happen again?

I need some instructions how to make the problem happen on my computer, to be able to fix it.

**Comment by photopea** [comment]
I have to close it because of lack of details. But you can still reply if you want.
