### ISSUE TITLE
I cant write anything by using Type Tool. The text invisible.Even I try to create from template.

### ISSUE THREAD

**Issue by emred111** [photopea/photopea#2553]
I changed the everything but text is invisible
![screenshoot](https://user-images.githubusercontent.com/17517256/96871039-6354ce80-147a-11eb-8d08-bc6d6efb242e.png)

**Comment by photopea** [comment]
Hi, try to disable all browser extensions. You are probably using extensions which prevent websites from drawing vector shapes.

**Comment by emred111** [comment]
Problems is solved I don't know how but...

**Comment by photopea** [comment]
Did you disable any extensions? Which extensions?

**Comment by emred111** [comment]
> Did you disable any extensions? Which extensions?

I just restart chrome and it worrks
