### ISSUE TITLE
ads doesn't work

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#2555]
when I opened photopea today I surprised that I don't have ads even though I didn't go premium yet !!! 
I don't use an ad blocker and I have never used it, I didn't update my browser or switch my account. I reload photopea many times and restart my computer But the ads are still not shown
![Screenshot (3)](https://user-images.githubusercontent.com/70863817/96997253-b76eba00-1531-11eb-992f-729069bcde42.png)

**Comment by photopea** [comment]
You are the third person reporting it. I did not know there are so many people visiting Photopea to watch ads.

We thought that ads are not an essetnial part of photo editing. You can find ads on other websites, e.g. https://www.nytimes.com/   https://www.businessinsider.com/  https://www.bbc.com/

**Comment by mustafaGFX** [comment]
I don't visit photopea to watch ads ..!!!
But Photopia relies mainly on ads for its income and It is unethical to discover a problem and not report it.. actually is amazing for me to hide ads for free but it isn't even a good thing fo photopea

**Comment by mustafaGFX** [comment]
I'm not just the third person who get a premium account for free, I'm the third person who reports the problem
