### ISSUE TITLE
Not saved project crashed when editing font

### ISSUE THREAD

**Issue by itskarldesigns** [photopea/photopea#2557]
I was working on a thumbnail for Youtube, finishing up with font and layerstyles, had multiple text layers selected and tried to change tracking/size in character window. Seemed to load a bit and then crashed to an "oopsie" screen. Most likely error was on my side, since I did have multiple tabs open as well and the project was quite a few layers deep. Tried to back quickly, but the work was gone, so I just figured I post it here. Not a big issue, but if its somehow avoidable/fixable thing, im sure it would save others some time and nerves in the future.

**Comment by photopea** [comment]
Hi, I think your computer ran out of memory :( Try to save your work regularly, especially if you work with large files (large resolution or many layers).

**Comment by photopea** [comment]
I will close it now.
