### ISSUE TITLE
Spot Healing Brush Tool

### ISSUE THREAD

**Issue by oshkalo89** [photopea/photopea#2558]
Hi Photopea,

My name is Peter Oshkalo. I am a small entrepreneur who is selling photo books to children graduating from school in Moscow.
Briefly the process looks like this:
1. My photographer goes to school and take snaps with professional camera
2. My photographer retouchs photo. It takes 2-7 days to do this depending on photographer.
3. My designer creates PDF look of the photobook. 
4. Customer approves, pay the bill.
5. I print and deliver the books.

I am trying to speed up my service and make as quick and smooth as possible. The plan is to use Machine Learing for autoretouching of my photos (step 2).
The autoretouching specifically for photo books service contains:
- Colour balance. No problems with it. Use neirual network trained on my own dataset.
- Photo crop. No problems with it. Use neirual network trained on my own dataset.
- Spot Healing Brush Tool. Here is a problem. Neiural work is traned and have more or less fine results. But it takes 12 seconds to remove 1 spot.

Photopea service has the "Spot Healing Brush Tool" which provide a good result in a very quick way. How did you do that? 
Can you share some recommendations on what is the direction should I go to make this happen?

Here is my school photo book service (purely in Russian ) https://prinday.ru/
Just in case you want to have a look.

Peter Oshkalo 
+7 910 466 68 38  peter.oshkalo@prinday.ru

**Comment by photopea** [comment]
Hi Peter, so you are a programmer, too? Did you made these neural networks yourself?

I don't know what you mean by "spot healing brush with neural network". What algorithm exactly takes 12 seconds? There is no human input at all?

**Comment by oshkalo89** [comment]
Hi,

I am IT oriented person, but not programmer. :)  I work with a programmer who made nerural network using Python libriries: tensorflow, numpy, pillow, cv2 .
We use SNGAN and 9-12 hidden layouts

My photographer should find the scin deffect and click with «spot healing brush» tool.  He is doing this in my desktop application written with Node.js, Electron, JavaScript.  

Like it’s done in Photopea
![2020-10-26_10-11-14](https://user-images.githubusercontent.com/17721740/97163435-b2a84100-1791-11eb-89ca-995abd6b40c3.png)

**Comment by photopea** [comment]
You can use the Spot Healing Brush in Photopea for free. Note, that if the spot is large (e.g. 200 x 200 pixels), it can also take 12 seconds in Photopea.

I can not disclose our method to you, but you can try looking for "inpainting" algorithms :)

**Comment by photopea** [comment]
I will close it now, but we can keep chatting under a closed issue, if you want :)

**Comment by oshkalo89** [comment]
Hi Photopea,

I use this repo as a reference for our model: https://github.com/JiahuiYu/generative_inpainting We use tensorflow 1.7.0 and pretrainded weights based on CelebA-HQ dataset. 
I haven't tried tensorflow-gpu with this model yet. It might increasse the performance. 

Result is good enough. But still I have no idea how to make this working quickly (within 1 second) on almost any laptop. 12 seconds for the area 15/15 is so bad. :(

Did you have similar problems with performance of Spot Healing Brush Tool?

**Comment by photopea** [comment]
I do not use any trained neural networks for inpainting. There are plenty of regular algorithms.

**Comment by oshkalo89** [comment]
oh. Didn't expect this. )
