### ISSUE TITLE
Can’t get to layers

### ISSUE THREAD

**Issue by duo203** [photopea/photopea#2559]
Whenever I open a new file all it shows is channels and paths. I don’t know why it is doing this I’ve tried to open different photos but that doesn’t work can someone please help I have work to do

**Comment by photopea** [comment]
You can open the Layers panel in Window - Layers.

**Comment by duo203** [comment]
Can you Elaborate

**Comment by photopea** [comment]
There is a Window button at the top of Photopea. If you press it, there will be a drop-down menu, where you should click "Layers".

**Comment by photopea** [comment]
I just put "photoshop layers gone" and the solution is right there: https://www.howtogeek.com/336523/what-to-do-if-you-can%E2%80%99t-find-the-layers-panel-or-any-other-panel-in-photoshop
