### ISSUE TITLE
No URL after trying to publish on Imgur (nor photopea)

### ISSUE THREAD

**Issue by francojoint** [photopea/photopea#2560]
I access photo pea.com from an iPad and I can’t save locally an edited file. When I try to save it locally I get another browser tab with lots of chars. To avoid this I tried to publish on imgur. It seems it successfully publish but there is no clue to what URL  is chosen to access the picture.

**Comment by photopea** [comment]
Hi, what iOS do you have? Can you update it?

**Comment by photopea** [comment]
I have to close it because of lack of details.
