### ISSUE TITLE
Youtube Banner

### ISSUE THREAD

**Issue by KamiKamu** [photopea/photopea#2561]
Can there be a youtube banner?

**Comment by photopea** [comment]
Hi, where should be a youtube banner?

**Comment by MichalSZZ** [comment]
Maybe he want to add predefinied format like FB cover photo... Don't know. I dont like people who write something  and doesn't follow they own questions.

**Comment by photopea** [comment]
There is a Youtube Cover predefined in Photopea, I think that is it.
