### ISSUE TITLE
Where is the Background Eraser tool?

### ISSUE THREAD

**Issue by SM-Fahim** [photopea/photopea#2562]
I think a few months back, when I hovered over any of the tool listed on the left, a sub-list of tools were shown. Now, I can't see them. Only the main tools are shown.
On the other hand, I was looking for the background eraser tool. Seems like it's not there. 
I'm not a regular photoshop user so it might be my mistake. But why there are no longer the sub list of tools on the lest bar?

**Comment by photopea** [comment]
Hi, you need to click and hold the icon of a tool, to see the dropdown menu with more tools. It is in the same "group" with the Eraser tool.
