### ISSUE TITLE
Panels disappear and Photopea stops working

### ISSUE THREAD

**Issue by dmassaragolden** [photopea/photopea#2563]
Today, whenever I open a file in Photopea after a couple of seconds my panels disappear and my Photopea stops working all together. This has never happened before today. I am using Chrome when it happens. I used Firefox after on the same computer and I had no issues. It seems to be happening only on Chrome.

**Comment by dmassaragolden** [comment]
![image](https://user-images.githubusercontent.com/73542873/97338727-172dd380-1858-11eb-8bcd-1f11b9a70281.png)

**Comment by photopea** [comment]
Hi, can you try it in Chrome in Incognito mode? Does it work?

**Comment by dmassaragolden** [comment]
Notice all the panels are gone....I can't do anything, then I have to go to a different browser.

**Comment by photopea** [comment]
I think one of your extensions is removing stuff from Photopea. Are you aware of using such extensions? Or did someone else install extensions into your computer?

**Comment by dmassaragolden** [comment]
No I am not aware of any extensions. I don't think anyone else did

**Comment by photopea** [comment]
Can you try to open Photopea in Chrome in Incognito mode? Does it work there?

**Comment by dmassaragolden** [comment]
Can you tell me how I try Chrome in incognito mode.  I don't really know what that is

**Comment by photopea** [comment]
Look here: https://support.google.com/chrome/answer/95464?co=GENIE.Platform%3DDesktop&hl=en

**Comment by dmassaragolden** [comment]
Since I am at work, I don't see the incognito option when I click the 3 dots.....maybe my school does not allow that

**Comment by dmassaragolden** [comment]
Why do you suppose Firefox works and Chrome doesnt

**Comment by photopea** [comment]
I think you have many browser extensions in Chrome, which modify websites (they remove elements from Photopea). While in Firefox, you have no extensions.

**Comment by photopea** [comment]
Open chrome:// extensions in Chrome and disable all extensions. Let me know if it helped.

**Comment by dmassaragolden** [comment]
Ok...I think that worked....why all of a sudden did that start to happen? May I ask you one more question....or do I need to start a new thread?

**Comment by photopea** [comment]
Hi, sure, ask any questions you want! You should always ask instead of asking if you can ask :)

What did start to happen all of a sudden?

**Comment by photopea** [comment]
I will close it now, as I think it is fixed and the person is not answering.
