### ISSUE TITLE
Loading... banner up forever, not opening pictures from URL

### ISSUE THREAD

**Issue by kelseymoultonths** [photopea/photopea#2564]
I am a teacher, and I have an assignment out right now for my students to open a picture from a URL and use certain tools to edit it. Many of students had no problems last week opening pictures from URL. But this week, there have been many where they are not able to open a picture from URL...the "loading..." banner at the top of the page just stays there forever and ever. I also tried it and it was the same problem. I tried with several different picture sizes and the same message pops up and nothing ever loads. Is there a fix out for this?

**Comment by photopea** [comment]
Hi, could you tell us the URL which you can not load?

When a computer opens the URL, it makes the request to the web server, and the web server returns some data. But the same URL can return different data to each person. E.g. if you open www.facebook.com , every person sees a different timeline, but they are all at the same URL.

You must make sure, that you use a regular image URL. E.g. if you have a private Facebook album and you copy URL of the image in it, that URL may not be openable to your friend.

Can you open an Incognito window in your browser and open your image URL in it?

**Comment by photopea** [comment]
I have to close it because of lack of details.
