### ISSUE TITLE
Brushes stop recognising pressure when switching tabs

### ISSUE THREAD

**Issue by fusionPT** [photopea/photopea#2565]
I set up a brush with dynamic pressure (I'm using a wacom) and when I switch between tabs on the browser and come back to Photopea again the pressure dynamics don't work.
![image](https://user-images.githubusercontent.com/393198/97450675-4402e900-1933-11eb-819f-6effcc31eef5.png)

**Comment by photopea** [comment]
Hi, the tip dynamics is not related to the pen pressure. Do not enable that option if you don't know what is it for

When you open Photopea for the first time and press your pen harder, does it draw a thicker line?

**Comment by fusionPT** [comment]
What do you mean? Yes, if I press harder it does draw a thicker line... it looses that ability after I switch tabs and come back to photopea.

What do you mean don't touch if I don't know what is it for?

**Comment by photopea** [comment]
The "Point Dynamics" is not related to the pen pressure recognition.

It is really weird that it loses the ability to detect pen pressure. Can you try Photopea in incognito window and do the same (switch to other tab and back) ?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
