### ISSUE TITLE
Is WebGL acceleration necessary for displaying transparency?

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2566]
When WebGL is disabled, transparency, which should be represented as a checker pattern, is instead represented as white in the workspace. (The export preview for a format that supports transparency, such as PNG or SVG, still displays the expected checker pattern.) I don't think this has always been the case; the transparency would display correctly a few months ago even though I've always had WebGL turned off.

**Comment by photopea** [comment]
Hi, it happens only when you have artboards (when loading PDF or EPS or Sketch, Figma, XD).

When you open a PDF in Photopea, I think it makes sense to use a white background, while during the export (e.g. to SVG) we should make the background transparent. What do you think?

**Comment by dentistformyeye** [comment]
Oops, I should clarify that I mean regular images (JPG, PNG, SVG). The export preview works as expected for every format (transparent when supported, white when JPG or PDF). Making the background of an opened PDF white is also working as expected.

For regular images in the workspace, toggling WebGL switches the transparent parts from white to checkered or vice versa in real time. Blend modes work correctly, so Linear Dodge black on transparency that looks white is still black.

1. Open a new project.
2. Use the eraser to drawn lines across the layer.
3. Create a new empty layer above and use the brush tool to draw across the eraser lines.
4. Set the blend mode of the top layer to Linear Dodge.

WebGL off:
![image](https://user-images.githubusercontent.com/51429646/97526465-9538ca00-197f-11eb-9793-ad0b74bbc4ae.png)
Top layer only:
![image](https://user-images.githubusercontent.com/51429646/97527002-af26dc80-1980-11eb-8754-040de89868c6.png)
(Bottom layer just looks like white.)

WebGL on:
![image](https://user-images.githubusercontent.com/51429646/97526480-9e299b80-197f-11eb-8254-bed08ab7b774.png)
Bottom layer only:
![image](https://user-images.githubusercontent.com/51429646/97526926-8999d300-1980-11eb-924f-7a07546ef662.png)
Top layer only:
![image](https://user-images.githubusercontent.com/51429646/97526941-91597780-1980-11eb-9dd7-4f647a8d3a2c.png)

**Comment by photopea** [comment]
Oh, I am very sorry, there was a bug, it should be fixed now.

**Comment by dentistformyeye** [comment]
Thank you! It works perfectly now.
