### ISSUE TITLE
No valid data on clipboard

### ISSUE THREAD

**Issue by FrostEdits** [photopea/photopea#2569]
I have been struggling to copy and paste, every time I try to paste an image from a different tab it gives a notification of "no valid data on clipboard." I have toggled between allowed and blocked and ask for permission on settings and it hasn't been working.

**Comment by photopea** [comment]
Are you using Photopea at www.Photopea.com ? Could you try to disable all browser extensions?

**Comment by photopea** [comment]
I think only the person who can remove extensions from your Chromebook can help you. You should ask that person for help.

**Comment by FrostEdits** [comment]
I figured it out, I could only use other devices on this website, thanks! I'll continue working now!
