### ISSUE TITLE
Filter - Render - Lighting effects

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#2570]
It would be nice to have this filter.

**Comment by mustafaGFX** [comment]
it would be amazing if you make a camera raw filter like adobe photoshop, I don't know if it is difficult to do that or not, but I think that you already have all tools like hue & saturation and brightness & contrast... etc, All you have to do is assemble these tools in one filter and you did it,  I hope it is that simple

**Comment by photopea** [comment]
I give up, this filter has too many 3D parameters and is related to other 3D features.
