### ISSUE TITLE
photopea stops working / " freezes " when using the text tool

### ISSUE THREAD

**Issue by svlringen** [photopea/photopea#2572]
i've run into this problem several times in the past and i'm not sure why. i was editing something for a friend and only had a few layers in the project. when i  tried to add another text layer, photopea _bugs_ out and i can't do anything. i can click on other tools and projects opened, however i can't do anything else. 

i've tried closing the app and restarting it, but the problem still occurs. i would have to not use photopea for a day or so in order for the problem to go away for some time before it comes back again.

it mainly happens when i use a font i load into photopea and try to move it within the project. the issue doesn't pop up if i were to use any fonts that the app already has.

**Comment by photopea** [comment]
Hi, could you share your font with us? Could you try to find some specific steps, how can we make the bug happen?

**Comment by photopea** [comment]
I have to close it because of lack of details.
