### ISSUE TITLE
account login is always redirected to google after choosing google accidentally

### ISSUE THREAD

**Issue by SebiTimeWaster** [photopea/photopea#2573]
steps to reproduce:
- you are not logged in
- click "log in"
- accidentally select google
- close window
- click "log in" again
- one is automatically redirected to the google oauth window, no chance to select another provider

the only way to get to the selection page again and select github for instance is to delete the cookies set by photopea and reload the page.

**Comment by photopea** [comment]
Hi, it should be fixed now :)
