### ISSUE TITLE
Artifacts when using paintbrush

### ISSUE THREAD

**Issue by wgabel** [photopea/photopea#2575]
When using paintbrush there are artifacts on brush with softness set to a low value. There is no soft gradient but a hard, pixelated line. 
Steps to reproduce:
1. New document.
2. Pick paintbrush. Round, soft.
3. Pick color, anything but white.
4. Start painting.

After some continous strokes artifacts should start to appear. The artifacts are hard, pixelated edges on the gradient part of the brush stroke.

example:
https://imgur.com/dFQGLPA

**Comment by photopea** [comment]
Hi, we switched to this method about a month ago, because it is much faster.

I switched it back to the old, slower method, which does not make these artifacts.
