### ISSUE TITLE
Cannot save the edited file

### ISSUE THREAD

**Issue by Andromedanita** [photopea/photopea#2576]
After doing all the editing, the option to save works but then nothing happens and it does not ask where to save it!

**Comment by photopea** [comment]
Hi, are you using File - Save as PSD? Or something else?

Can you open Photopea in a separate tab, make an empty document and save it? does it work?

**Comment by Andromedanita** [comment]
Yes, it used to work before as well, its just that if I refresh it, I will loose my edited file that I spent so much time on it and I am not sure if there is any way to save it without loosing it.

**Comment by photopea** [comment]
But can you open Photopea in a separate tab, make an empty document and save it? does it work?

You will not lose anything if you open "new Photopea" in a separate tab.

**Comment by photopea** [comment]
What browser and operating system do you use?

**Comment by photopea** [comment]
Can you send us a screenshot of how everything looks like, including the browser interface?

**Comment by Andromedanita** [comment]
Yes, I can open a new tab and create a project and save it but it just got frozen on my finished project so I assumed it could be a bug maybe?! I am using Chrome on Mac with Catalina OS

**Comment by photopea** [comment]
It is really strange. Can you right-click Photopea, choose "Inspect Element" and switch to "Console"? Can you send me a screenshot of what you see there?

**Comment by Andromedanita** [comment]
I refreshed the page (my bad) and now its all gone so I can't do the inspect mode unfortunately.

**Comment by photopea** [comment]
Can you make the problem happen again? E.g. with a new empty document?

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by Benleisorek** [comment]
I got the same problem. I press save as PNG and it just does nothing
It does the same on other projects i tried opening
maybe it is because I saved the project before and did some changes since
(I use Ubuntu software)

**Comment by photopea** [comment]
@Benleisorek Try to disable all browser extensions. Does it help?
