### ISSUE TITLE
Inaccurate eraser tool 

### ISSUE THREAD

**Issue by peko46** [photopea/photopea#2578]
![New Project(1)](https://user-images.githubusercontent.com/73909293/98032729-ba608900-1e14-11eb-8494-04d6cab441de.png)

Hi Photopea! 

I use Photopea a lot to make quick actions if I need some details to be done. Today I've found pretty frustrating thing about the area which is being erased when using the tool (basic, not background). Never interfered with tool settings, everything is set to default except the size of the circle. The circle always were erasing full area and I could have been as much precise as I wanted. For example with the line like above. Tried Photopea on two devices, so I assume it's not related to laptop. I'm also sure that yesterday everything was ok. 

Cheers!

**Comment by dentistformyeye** [comment]
With extensions disabled, I've confirmed that this happens to every tool with a brush behavior (circle indicator), including background eraser, healing brush, dodge, etc. Toggling WebGL doesn't seem to change anything.

**Comment by dentistformyeye** [comment]
Maybe switching back to the old brush method as described in #2575 has to do with it?

**Comment by MichalSZZ** [comment]
I have same Issue (and my students) with size of brush tool. It is half the size as it should to be.
<img width="725" alt="obraz" src="https://user-images.githubusercontent.com/38118273/98041216-dd456a00-1e21-11eb-9607-a5039a395eb6.png">

**Comment by photopea** [comment]
Guys, I am very sorry. I created this error when trying to fix this issue: https://github.com/photopea/photopea/issues/2574

Now, both issues should be fixed. Thank you for pointing it out!
