### ISSUE TITLE
Gray screen

### ISSUE THREAD

**Issue by CrystallicCoder** [photopea/photopea#258]
If I have something selected everything turns gray.

**Comment by photopea** [comment]
Hi, what exactly turns gray? Did you try to disable the grid (View - Grid) ?

**Comment by CrystallicCoder** [comment]
Whatever I'm drawing or making turns gray, I'll try turning grid off

**Comment by photopea** [comment]
Can you send us a screenshot of what exactly is gray?  Does the whole page become gray?

**Comment by photopea** [comment]
I can't see a screenshot. 

BTW. go to Edit - Preferences, try to enable the Grid and change Grid Gap. When your grid gap is small and you zoom out, grid lines are drawn very close to each other, making the image gray.
