### ISSUE TITLE
No blend mode option for smart filters without dialogue boxes

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2580]
Some filters, such as Gaussian Blur and Wind, have dialogue boxes that allow the user to adjust parameters before applying the filter. A few filters, such as Average and Clouds, take effect immediately. When applied to a smart object, a blend mode option doesn't appear for immediate filters when the user clicks the symbol on the right side of the smart filter in the Layers panel.
![image](https://user-images.githubusercontent.com/51429646/98073075-85186300-1e35-11eb-9161-1b5fad86ee5b.png)

### Steps to reproduce
1. Open any image. Convert it to a Smart Object.
2. Apply Filter > Blur > Average.
3. Double-click the double circle symbol to the right of the smart filter in the Layers panel.

### Actual result
No dialogue box appears.

### Expected result
A dialogue box for changing the blend mode of the smart filter appears.
![image](https://user-images.githubusercontent.com/51429646/98073466-65356f00-1e36-11eb-96df-ff7d426eb352.png)

### Additional notes
Extensions were disabled.

**Comment by photopea** [comment]
Fixed, thanks! :)
