### ISSUE TITLE
API - Crop image doesn't work 

### ISSUE THREAD

**Issue by taime** [photopea/photopea#2581]
I'm trying to crop image by coordinates. What is the correct way to do it?
I've tried these:

`app.activeDocument.crop(400,400,500,500)`

and 

`app.activeDocument.crop([400,400], [500,500])`

Doesn't work...

**Comment by photopea** [comment]
Hi, there was a bug in Photopea. I fixed it. The following code should work now:

    app.activeDocument.crop([400,400,500,500]);
