### ISSUE TITLE
Place a new image to a new layer in current document with API

### ISSUE THREAD

**Issue by taime** [photopea/photopea#2582]
How to place (load) a new image to a new layer in current document with API
Examples show only how to open image in a new tab... is it possible to place image to the current tab with API?

Normally I would use app.open and copy image to buffer and paste it, but this doesn't work in photopea...
or.. Another way is  pasting by using Action Descriptor, but it's also not supported in photopea

Are there any docs with methods, that works in photopea?

**Comment by photopea** [comment]
Hi, if you can open a document in a new tab in Photopea, you can run a script, which will copy-paste the layer to another document, and will close the old document.
