### ISSUE TITLE
Photopea have Photoshop ads

### ISSUE THREAD

**Issue by minecraft2048** [photopea/photopea#2583]
I'm using photopea because I can't run photoshop but photopea have creative cloud ads 
(Adobe rant: you can give me 100% student discount but if photoshop can't run on linux then its no go for me)

![image](https://user-images.githubusercontent.com/2445636/98181842-62cb3600-1f58-11eb-8247-1c7888770455.png)

**Comment by photopea** [comment]
Hey! If you don't like a specific ad, there is a tiny "X" sign at the top right corner.

If you click it, you can choose "Stop Seeing This Ad" :)
