### ISSUE TITLE
Spot healing glitch deletes a square

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2584]
here is the video:
https://video.drift.com/v/ab4RsZ4kEFh/
 

It have happened very often during this work session.

Only with the spot healing tool

**Comment by avagp** [comment]
here is the PSd
[Uploading tofu-kiltros-mirada1 (2).zip…]()

**Comment by photopea** [comment]
Hi, I never thought about using a Spot Healing brush on a layer, which contains transparency. It is probably related to the fact, that there are not enough non-transparent places around the spot, which could be used for patching.

What exactly would you like to happen in that case?

**Comment by MichalSZZ** [comment]
> What exactly would you like to happen in that case?

Maybe sampling only from non transparent pixels? I tried that in Photoshop and there it works in that way...

**Comment by avagp** [comment]
Yes. Exactly that :)

**Comment by photopea** [comment]
I fixed it. If the healing is not possible for any reason, Photopea will keep the original content unchanged.

**Comment by avagp** [comment]
Good!
Thanks! :D
