### ISSUE TITLE
Ctrl + click on layers group arrow - opens / closes folders with the same hierarchy level

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2585]
There is 2 more combination about that feature, but that one is mostly used by me.

For example. Ctrl + Alt + Click collaps all groups in document (on any hierarchy level)

With Ctrl + Alt + LMB clicking It works also for collapse all layer styles and filters in smart objects when user click on arrow for layer effects

**Comment by photopea** [comment]
Done, thanks! :)
