### ISSUE TITLE
app.documents[3] doesn't work (so can do nothing with non active documents) (it's in API)

### ISSUE THREAD

**Issue by taime** [photopea/photopea#2587]
app.documents[I] property from adobe script language docs doesn't work

For example, this code will make changes in acitveDocument, but not in 4th opened document...
```
var lays = app.documents[3].layers;

for(var i=0; i<lays.length; i++)
{
	//lays[i].visible = false;
	//lays[i].opacity = 50;
	lays[i].name = "My Layer "+i;
}
```

So can do nothing with not active document. For example, after opening a few images I can not use it, because activeDocument is always the first one have been opened...

**Comment by photopea** [comment]
Hi, I tried your script in Adobe Photoshop and I see a following error:

![image](https://user-images.githubusercontent.com/15955558/98408565-a1a0df00-2071-11eb-8371-e22cc59d923f.png)

I added "app.activeDocument = app.documents[3];" to the beginning of your script, and it works both in Photoshop and Photopea.
