### ISSUE TITLE
API - app.activeDocument.selection.select() doesn't work

### ISSUE THREAD

**Issue by taime** [photopea/photopea#2588]
The **select()** method doesn't work

For example:
`app.activeDocument.selection.select(11,22,100,100)`

**Comment by photopea** [comment]
Hi, you are using the method select in a wrong way. See https://www.adobe.com/content/dam/acom/en/devnet/photoshop/pdfs/photoshop-cc-javascript-ref-2019.pdf

The correct usage is this:

    var x=11, y=22, sw=100, sh=100;
    app.activeDocument.selection.select([ [x,y], [x,y+sh], [x+sw,y+sh], [x+sw,y] ]);
