### ISSUE TITLE
Create new text layer with text in API

### ISSUE THREAD

**Issue by taime** [photopea/photopea#2589]
Impossible to create text as described in adobe scripts language documentation:

This code create new text layer without any contents.
It's also impossible to add text to this later with `textItem.contents = "HELLO WORLD";`

```
var addText = `
                        var layers = app.activeDocument.artLayers;
                        var layer = layers.add();
                        layer.kind = LayerKind.TEXT;
                        var textItem = layer.textItem;
                        textItem.kind = TextType.PARAGRAPHTEXT;
                        textItem.size = 30;
                        textItem.position = [10, 10];
                        textItem.contents = "HELLO WORLD";
                        textItem.width = new UnitValue("300 pixels");
                        textItem.height = new UnitValue("30 pixels");
                    `
wnd.postMessage(addText, "*");
```

**Comment by photopea** [comment]
Hi, I fixed the issue, your script should work well now.

Note, that this is a bit tricky in Photopea. A single script can create a text layer, rasterize it and apply the blur on it. But to do so, Photopea or Photoshop must have access to a font before starting a script.

Make sure a necessary font is loaded into Photopea before calling such script. You can do it by typing with such font before, or by loading a PSD with text layers containing that script. Or in our API, send a font to Photopea from the Outer Environment :)
