### ISSUE TITLE
Feature Request: File System Access APIs

### ISSUE THREAD

**Issue by jamesorlakin** [photopea/photopea#2590]
The new [File System Access APIs](https://web.dev/file-system-access) are launching in Chrome (and I assume others over time). These have the potential to remove one of my pet peeves with Photopea - the fact you can't just save a file locally without hopping through the downloads folder. Having a native open/save experience will be incredibly beneficial and the old behaviour can be retained for incompatible browsers.

This is just a little nod in case you weren't aware. Photopea is an amazing webapp!

**Comment by photopea** [comment]
Hi James, I am working on it right now, it should be available in several hours. It was reported before (https://github.com/photopea/photopea/issues/2118), so I will close your issue.

Your downloads don't have to go into a Downloads folder. You can configure your browser to ask you before each download, where it should be saved and under what name (e.g. you can choose to replace the original file).

See here - https://support.google.com/chrome/answer/95759 "Ask where to save each file before downloading."  This option has been in Chrome and other borwsers for at least 10 years.

**Comment by jamesorlakin** [comment]
Aah I didn't see that issue, oops! Thanks

**Comment by photopea** [comment]
It is implemented now :) If you open a PSD file from a computer, File - Save will be available and will rewrite the original file.
