### ISSUE TITLE
Clone Tool

### ISSUE THREAD

**Issue by Adryanaaaaaaaaaa** [photopea/photopea#2591]
the Clone Tool has become too large for the part to be copied. A few days ago it was normal, now it is impossible to use. If I copy a small part, it becomes huge in the moment I paste. Sorry for my English, I'm Italian.

**Comment by photopea** [comment]
Hi, I can not reproduce shuch behaviour. Could you show us a screenshot of what you mean? And how do you make it happen?

**Comment by photopea** [comment]
I have to close it because of lack of details.
