### ISSUE TITLE
I can't open a template while working on another project

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#2592]
I can't open a template while working on another project, because I can only open the templates page when I start opening the program,  is it possible to add a shortcut for the templates page on the File menu ..?
![Screenshot (22)](https://user-images.githubusercontent.com/70863817/98471570-ee152780-21f5-11eb-9b42-d7bd86aa444c.png)

**Comment by photopea** [comment]
You are right. But I am afraid there would be too many items in the File menu. Maybe we should remove some, or put some in a sub-menu? What do you think?

**Comment by photopea** [comment]
I decided to have it in a following way :) 

![image](https://user-images.githubusercontent.com/15955558/98584103-b70e4700-22c5-11eb-84b3-99920716285a.png)

**Comment by mustafaGFX** [comment]
it,s great
but in my personal opinion, I think that its good to have many items in the File menu because this shows all the options of the program in a clear way and reflects the ability of the program too

My opinion is not necessarily correct but I have a little experience in UX design

**Comment by mustafaGFX** [comment]
if you think that it will be better if you put some in a sub-menu go on and hope you are right

**Comment by photopea** [comment]
It is like making layers in a PSD. You do not have 100 layers one under another, you put them into folders. Related layers are in one folder. When you look for a specific thing, you don't have to go through 1000 items, but you have a hierarchy :)

It is the same with making UI and menus.

**Comment by mustafaGFX** [comment]
great
