### ISSUE TITLE
Open option not working (Ctrl+O)

### ISSUE THREAD

**Issue by raghavranebiz** [photopea/photopea#2593]
Unable to ope local file as the option not working, Hence not able to add any image or reference images or any file format.

**Comment by photopea** [comment]
Hi, could you try Photopea in Incognito mode? I think your browser extensions could be blocking Photopea. I do not use any browser extensions, as they are basically viruses.

**Comment by vinhchiase** [comment]
> Hi, could you try Photopea in Incognito mode? I think your browser extensions could be blocking Photopea. I do not use any browser extensions, as they are basically viruses.

I also can't open the image file on my computer, but that's when using Photopea from my embedded website, and accessing Photopea.com is normal, I hope you don't disable this feature.

**Comment by vinhchiase** [comment]
I use Coc Coc browser to use normally, this browser is like Chrome but why is there this difference

**Comment by photopea** [comment]
I fixed the problem with File - Open in an embedded website.
