### ISSUE TITLE
Photopea no longer works with Chrome!

### ISSUE THREAD

**Issue by andrewtuttle** [photopea/photopea#2594]
As of today, whatever changes have been made to Chrome and/or the program itself cause it Photopea to no longer be able to open files.

Any file attempted to be opened gets "error: cannot open system files"

**Comment by IamFlea** [comment]
Everything works fine for me. I have Chrome on the latest version. 
- Make sure you have user rights to open the files. You might logged in into the system as a guest.
- Check if you are running Chrome on the latest version
- If you want to open single image. You can also try copying the image into the clipboard (ctrl-c) and then pasting it on the website (ctrl-v). 
- If none of these helps, you can try running the browser with administrator rights (in Windows right click - Run as Administrator).

**Comment by photopea** [comment]
Hi, I think it should be fixed now. if not, try to disable all browser extensions.

Let me know if it helped.
