### ISSUE TITLE
No working "Open File" today in iframe!

### ISSUE THREAD

**Issue by AlexanderKapaceb** [photopea/photopea#2596]
Today I ran into a problem, the editor stopped opening files through the "Open file" menu item. 
See screenshot for console output.

![1](https://user-images.githubusercontent.com/45259214/98568744-7e20a300-22c2-11eb-8af9-d393df9b3d33.JPG)

**Comment by photopea** [comment]
Hi, I am very sorry, it is fixed now.

**Comment by tomayac** [comment]
This limitation is covered in the [specification](https://wicg.github.io/file-system-access/#privacy-third-party). I'm curious, how did you solve the issue?

**Comment by photopea** [comment]
@tomayac  I just dont use the API when in iframe.

**Comment by tomayac** [comment]
> @tomayac I just dont use the API when in iframe.

I have filed https://github.com/WICG/file-system-access/issues/245 to track this feature request.
