### ISSUE TITLE
shape roundness

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#2598]
I apologize for the many suggestions, but I think that they should be presented, can you add a scroll bar to the shape roundness like this

![Screenshot (23) (1)](https://user-images.githubusercontent.com/70863817/98706516-973f5780-2387-11eb-85eb-91ad7d58ffc4.gif)

this look is not perfect and looks untidy but you can make it looks better

**Comment by mustafaGFX** [comment]
closer view
![Screenshot (23) (2) (1)](https://user-images.githubusercontent.com/70863817/98706894-12a10900-2388-11eb-861d-9abf8d3f0b6e.png)

**Comment by mustafaGFX** [comment]
and this a different idea which will be so much better but I am not sure if you would like it

![Screenshot (28)](https://user-images.githubusercontent.com/70863817/98708796-3cf3c600-238a-11eb-885b-7a369e270382.gif)

**Comment by mustafaGFX** [comment]
when you press shift you control all the corners  like this 

![img_1_033](https://user-images.githubusercontent.com/70863817/98709495-1b470e80-238b-11eb-82e4-bb60eef2a2e7.gif)

**Comment by photopea** [comment]
Hi, you can click and drag the symbol before the input box.

![image (1)](https://user-images.githubusercontent.com/15955558/98709685-01093280-2383-11eb-99e4-900b21f1f3de.png)

**Comment by mustafaGFX** [comment]
yea I know, but do you think that it would be better if you add a scroll bar ...?
and what do you think about the second idea

**Comment by photopea** [comment]
It already works as a scrollbar. I think there is no need for an extra scrollbar.

The draggable corners would be nice, too.

**Comment by mustafaGFX** [comment]
wow
I tried it right now and it already works as a scroll bar, sorry for your time :)

**Comment by mustafaGFX** [comment]
The draggable corners are hard to Implement, I mane would it take a lot of time?

**Comment by photopea** [comment]
yes, draggable corners are hard and it is not clear which tool should manage them.

**Comment by MichalSZZ** [comment]
> The draggable corners are hard to Implement, I mean would it take a lot of time?

Hi - I posted about that some time ago. Look #2018 

There was a major update for that (withoun draggable corners but - with that tool you can round any selected hard corner) 
<img width="584" alt="obraz" src="https://user-images.githubusercontent.com/38118273/99384880-62278d80-28d0-11eb-8f2e-6e20f2077143.png">

Arc Icon (button) on Direct Select Tool - top toolbar. Try it yourself. That is some kinde that you can finde in Illustrator but without GUI (circles) on corners.

**Comment by MichalSZZ** [comment]
<img width="565" alt="obraz" src="https://user-images.githubusercontent.com/38118273/99385348-26d98e80-28d1-11eb-8e90-2d418648a383.png">
any Shape that have hard corners. Photoshop still doasn't have that.
