### ISSUE TITLE
Pop up Ads

### ISSUE THREAD

**Issue by REVMA** [photopea/photopea#2599]
I've notice an increase in frequency in pop up ads on photopea. The ads are formatted so that there is no way to close the window, forcing me to reload the page and losing all the work I just did. 

Can you please advise?

I don't mind the ads, but I need help.

**Comment by photopea** [comment]
Hi, Photopea should never show any popup ads. At all.

My guess is, that you are using a browser extension, which inserts ads into websites which you visit (extensions can modify websites in any way they want, so inserting or replacing ads is not a problem for an extension).

If you disable all extensions, or try Photopea in Incognito mode, you will not see popup ads in Photopea. Let me know if I am right.

**Comment by REVMA** [comment]
Yes, incognito mode resolved the problem!! Thank you so much for the
suggestion!

**Comment by photopea** [comment]
You do not have to use Incognito mode. Just delete an extension, which inserts popup ads into websites.

Why do you use an extension, that inserts popup ads, when you say you dont want popup ads to be inserted?
