### ISSUE TITLE
Show Font Preview in Dropdown

### ISSUE THREAD

**Issue by amberream** [photopea/photopea#260]
It would be nice to see the font name rendered in the actual font in the drop down.

**Comment by amberream** [comment]
I guess I didn't wait long enough, looks like it just took some time and it's displaying now...

**Comment by photopea** [comment]
No problem Amber :)  Previews of all 3500 fonts are stored in this huge file: https://www.photopea.com/rsrc/fonts/fonts.png  , which has 670 kB, so it may take a while until it is loaded.
