### ISSUE TITLE
Filter modal window - zoom problem with keyboard shortcuts

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2601]
In most of filters doesn't work keyboards shortcuts to zoom the document when their modal window is apear. 
Only works Ctrl + Spacebar + Click.
It should to work also:

- Ctrl + +/-
- Alt + mouse scroll
- or only mouse scroll like in Liqufy or Filter Galery

**Comment by photopea** [comment]
That is a bit tricky.

- with a filter, you want to be able to press Ctrl + + (to zoom in)
- with a filter, you should not be able to press Ctrl + Z (to do a step back)

At the moment, if there is a window, keyboard shortcuts are ignored and the window can process them (e.g. Enter to confirm the filter, or Esc to escape the filter).

**Comment by photopea** [comment]
I have implemented it somehow.
