### ISSUE TITLE
Double click on shape layer thumbnail (in layers pallete) to show immediately Color Picker window

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2603]
It is my favorite function for shape color changing. It is very fast and easy in PS.
In Photopea after clicking, first apear properties window, then (sometimes) I must switch to "Layer" tab and then click on layer colour. 
Please... can you add double click for fast and user friendly color changing? It is very important for me.

**Comment by photopea** [comment]
Implemented, thanks! :)

**Comment by MichalSZZ** [comment]
Thank you very much!
It is a huge time saver for me.
