### ISSUE TITLE
depth map for FB post

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#2605]
**Sometimes I design a 3D facebook post like this:**

![Facebook-3D-Photos](https://user-images.githubusercontent.com/70863817/98953390-4e151200-2505-11eb-85eb-919874213e79.gif)
.
.
.
.
**First I put the image itself as a layer, then draw a depth map like this:**

![Facebook-3D-Photos (1)](https://user-images.githubusercontent.com/70863817/98954922-ff687780-2506-11eb-8970-c2aecb791c21.png)
.
.
.

**then I put the 2 images on Facebook and Facebook do it like this:** 

![3d-post-upload](https://user-images.githubusercontent.com/70863817/98955223-51110200-2507-11eb-883d-e66940622772.gif)
.
.
.
The problem is that it does not work the first time, there is always something wrong with the depth map, so I return to photopea to fix this wrong, then save the image, then delete the old depth map, and then upload the image again to see if the image is perfect or not and Then I do this many times

so I ask you if you can make photopea do it, here is my idea: 

![Screenshot (34)](https://user-images.githubusercontent.com/70863817/98964885-0648b780-2512-11eb-94b7-5f0a5c146342.gif)

![Screenshot (35) (2)](https://user-images.githubusercontent.com/70863817/98965136-5a539c00-2512-11eb-92b1-49788438f43c.png)

.
.
.
.
.
the user can use the depth map from layers, the depth map layer should have the same name as the main layer which ends by _depth
 example :
 main layer: dog
depth layer: dog_depth
-or the user can use the raster mask as a depth map : 

![Screenshot (35) (2)](https://user-images.githubusercontent.com/70863817/98968215-0f3b8800-2516-11eb-9f4e-a06aff9b3123.gif)
.
.
.
.
.
.
the filter has 3 controllers : 

**1. camera position/ zooming
2. spacing
3. expanding**

these gifs will make you understand what do these options do : 

**1. camera position/ zooming** : Camera distance to the image

![Screenshot (35) (3)](https://user-images.githubusercontent.com/70863817/98971533-f3d27c00-2519-11eb-8754-c2062b3cd8a7.gif)
.
.
.
**2. spacing**: The spacing of objects from each other

![Screenshot (35) (3) (1)](https://user-images.githubusercontent.com/70863817/98974541-af48df80-251d-11eb-9d49-141704ca2c3a.gif)
.
.
.
**3. expanding**: expand the white color in the depth map

_video could help you_: https://www.youtube.com/watch?v=DInWVvfPQm8
_FB 3d photos_: https://www.facebook.com/groups/1005731289499173/permalink/4618336061571993/

**Comment by mustafaGFX** [comment]
**the best place for this effect**

![Screenshot (34)](https://user-images.githubusercontent.com/70863817/98978340-7fe8a180-2522-11eb-94fe-20693e8e2285.png)

**Comment by mustafaGFX** [comment]
this tool should solve  these problems and save time and effort
>The problem is that it does not work the first time, there is always something wrong with the depth map, so I return to photopea to fix this wrong, then save the image, then delete the old depth map, and then upload the image again to see if the image is perfect or not and Then I do this many times

**Comment by photopea** [comment]
" there is always something wrong with the depth map, so I return to photopea to fix this wrong,"

Do you mean there is an error in a PNG file and Facebook can not process the PNG from Photopea? Or do you mean that you painted the depth map the wrong way, and the part of image is too far / too near (too dark or too bright)?

I agree, a built-in depth map viewer is a neat idea.

**Comment by MichalSZZ** [comment]
It can to be a nice new feature. I like 3D photos on FB.
I think that the biggest problem can be to create 1:1 script that render 3D like Facebook. I saw few sites with they own preview of 3D and, all was a little bit different than FB in app rendering.

@mustafaGFX did You saw that issue? #1576

**Comment by mustafaGFX** [comment]
@photopea I mean that I  painted the depth map in the wrong way, it can't be perfect from the first time, every time I have to return to photopea to adjust the brightness of white or the darkness of black (**The spacing of objects from each other**)

**Comment by MichalSZZ** [comment]
@photopea 
_Or do you mean that you painted the depth map the wrong way, and the part of image is too far / too near (too dark or too bright)?_

I have same problem. It wolud be great to test in app without sending it to Facebook

**Comment by mustafaGFX** [comment]
@MichalSZZ I fully agree with you, but at least we will be able to adjust the depth map in realtime, I will be a little bit different than FB app rendering but it will save the time and effort

**Comment by mustafaGFX** [comment]
@MichalSZZ 
>did You saw that issue? #1576

no, I didn't but I will

**Comment by mustafaGFX** [comment]
extra options but aren't as important as the previous ones :

- **custom depth map**
- **create a depth map**

![Screenshot (35) (2) (1)](https://user-images.githubusercontent.com/70863817/98986728-f5a63a80-252d-11eb-903c-426d06115f29.gif)
.
.
.
.

**custom depth map**: means to upload a png depth map from the device
**create a depth** map means this :

![Screenshot (37)](https://user-images.githubusercontent.com/70863817/98986938-3a31d600-252e-11eb-8d85-832c9e0b3988.png)

depth map creator tool is a little bit similar to the [magic cut](https://www.photopea.com/tuts/magic-cut-remove-image-background-online/) tool
you draw with black color on the far parts of the camera and draw with white on the near part of the camera and you know where you should draw with gray color : )

**Comment by photopea** [comment]
Hi guys, I made a 3D viewer similar to a Facebook 3D viewer. Press Window - More - 3D Viewer. Then, you can load your current document state as a Depth Map, or a Color Image.

It is a very simple implementation at the moment, but it should correspond geometrically to what you see on Facebook.

**Comment by mustafaGFX** [comment]
wow
that is soooooo wonderful
it was very fast, I didn't expect that it would be that fast
thanks, Ivan :)

**Comment by mustafaGFX** [comment]
hi Ivan
I took a very very long time to understand how to view the 3d image, some photos work well but some others look like this : 

![Screenshot (38)](https://user-images.githubusercontent.com/70863817/99158822-c20b1200-26df-11eb-90f4-31019788c235.png)

**Comment by photopea** [comment]
@mustafaGFX Could you send me that image to support@photopea.com ?

**Comment by mustafaGFX** [comment]
I did
BTW I answered you a long time ago about ABR files but you didn't answer me back, open photopea inbox  :)

**Comment by photopea** [comment]
@mustafaGFX You just sent me a screenshot of Photopea. Could you send me the colored image with its depth map?

**Comment by mustafaGFX** [comment]
I did
take a look here: https://www.photopea.com/#ipzK7Poar

**Comment by mustafaGFX** [comment]
hi
I have just noticed that when I resize the image to high resolution the problem be solved,
also, the size makes different changes in the 3d image 

this is a (311x390) image

![Screenshot (38) (1)](https://user-images.githubusercontent.com/70863817/99192559-211e6480-277c-11eb-920d-281a6c8c7dfd.png)

this is a (350x439) image and it uncolored

![Screenshot (39)](https://user-images.githubusercontent.com/70863817/99192566-2c719000-277c-11eb-9c32-9ef722b3c0b2.png)

and this is a(400x502) image in which the problem is resolved 

![Screenshot (40)](https://user-images.githubusercontent.com/70863817/99192576-31ceda80-277c-11eb-9d30-3000428a5587.png)

**Comment by MichalSZZ** [comment]
That files works good on Facebook https://youtu.be/4O74H_aVCaY

![bitdeffender45_depth](https://user-images.githubusercontent.com/38118273/99193083-e5cd6700-2776-11eb-9e89-44d59c1ea029.jpg)
![bitdeffender45](https://user-images.githubusercontent.com/38118273/99193084-e8c85780-2776-11eb-9b0b-3fd1e19e37f9.jpg)
[fb-bit-3dpost.zip](https://github.com/photopea/photopea/files/5542875/fb-bit-3dpost.zip)

But in Photopea I see that:
<img width="1000" alt="obraz" src="https://user-images.githubusercontent.com/38118273/99193110-1f9e6d80-2777-11eb-9322-1a9e5a2dc76f.png">

**Comment by mustafaGFX** [comment]
@MichalSZZ its because you didn't run the depth map in the right way, follow these tips

- put the colored image up and the depth map down
- press the 3d button
- press load color
- hide the colored layer
- press load depth

you load your current document state as a Depth Map, or a Color Image, I hope you got it :)

**Comment by MichalSZZ** [comment]
@mustafaGFX Can you download my ZIP file with source? 
I did your steps and got that:
<img width="868" alt="obraz" src="https://user-images.githubusercontent.com/38118273/99193684-cf290f00-277a-11eb-9c13-585ff5dabaa1.png">

**Comment by mustafaGFX** [comment]
also, image size makes some bugs.

this is your original image (widhth= 1619)

![Screenshot (44) (1)](https://user-images.githubusercontent.com/70863817/99193670-2632e200-2783-11eb-9677-a9af466f8744.png)
.
.
.
.

width= 1600 (its perfect)

![Screenshot (44)](https://user-images.githubusercontent.com/70863817/99193696-48c4fb00-2783-11eb-8652-2b5e43ec86ed.png)
.
.
.
.

width = 1601 ( We only increased one pixel and it has been unsaturated)

![Screenshot (44) (2)](https://user-images.githubusercontent.com/70863817/99193735-95103b00-2783-11eb-86f9-9ae217642c14.png)
.
.
.
.
when you increase the size up to 1601 pixel it becomes like this 
![Screenshot (44) (1)](https://user-images.githubusercontent.com/70863817/99193807-051ec100-2784-11eb-9732-889cfb881741.png)

**Comment by mustafaGFX** [comment]
@MichalSZZ put the size of your image (1600x1999)

**Comment by photopea** [comment]
Guys, there is a bug and I need to fix it. It will take me 10 minutes to fix it, but I am busy now, I will do it tomorrow :)

**Comment by mustafaGFX** [comment]
@photopea take your time :)

**Comment by MichalSZZ** [comment]
> Guys, there is a bug and I need to fix it. It will take me 10 minutes to fix it, but I am busy now, I will do it tomorrow :)

No problem :) 
With bigger resolution (as Mustafa said) it works.

**Comment by photopea** [comment]
These problems should be fixed now. It should work with any resolution :)

**Comment by mustafaGFX** [comment]
great
it works well, thanks  :)

**Comment by photopea** [comment]
So I think we can close it for now.
