### ISSUE TITLE
Mouse support not with iPad Pro 

### ISSUE THREAD

**Issue by Jerommmeke** [photopea/photopea#2606]
If I use a mouse with my iPad Pro, it doesn’t work. I can’t move objects, can’t turn it. Then I take my pen and I can move an object in a layer. I can’t even use the app menu on the top, it doesn’t even open. Use mu pen and the menu opens. What is wrong. This is just one of the problems.

**Comment by photopea** [comment]
Hi, does your mouse work  on other websites? Can you click on stuff e.g on Facebook.com?

**Comment by Jerommmeke** [comment]
With the mouse I can hit, drag, second mouse button. If the mouse works sometimes and after a minute no more, I can still use the pen. I minimize the app and I can use the mouse with All other apps. 0% Problems with the mouse on my ipad.
If you like I can send you a movie with the problem.

**Comment by photopea** [comment]
Sure, it would be great if you could make a video.

BTW. make sure you have updated to the latest iOS and the latest Safari. But not a Beta version of a OS.

**Comment by Jerommmeke** [comment]
I can't send a video. Just images. How can I send a video to you?

**Comment by Jerommmeke** [comment]
All my devices are up2date. Latent software, I bought a lot of software, nothing iligal. So that can't BE the thing.

**Comment by photopea** [comment]
You can put a video on youtube and share a link, or send it to support@photopea.com

**Comment by Jerommmeke** [comment]
Here is my video with troubles inside PhotoPea with mous. https://youtu.be/UuDorhlH1PU

**Comment by photopea** [comment]
Can you confirm, that the same happens even if you open Photopea in a web browser at www.Photopea.com ?

**Comment by Jerommmeke** [comment]
I opened  safari @ http://www and @ https://. Then I saved the browser as an app on my front screen (icon).

I also tested it in just in a browser without saving it as an app, just visiting. Tested it in safari and Google Chrome.
I thing I tested all possible ways.

When the mouse actions didn't work anymore I just refreshed the browser, but that also didn't work.

**Comment by photopea** [comment]
You should not be able to open http://www.Photopea.com , it should always redirect you to https://

What if you use only fingers and a pen, wiht no mouse, does everything work?

**Comment by Jerommmeke** [comment]
With vingers and pen I can do everything.

I must say I often have a problem that the app crashes, but that's when I use a large file (200MB) and 3500x2500px (144dpi).

**Comment by photopea** [comment]
Could you somehow open a web console on your iPad? Maybe you would have to do it through your computer. Are there any errors in the console?

I think Safari "kills" a website if it uses more than 1 GB of RAM, even when there are 4 GB of free RAM. Since Apple does not allow other borwsers to run in iOS, your only solution is to "pray" to apple to make Safari allow websites use more RAM (instead of killing them).

**Comment by photopea** [comment]
I will close it for now. maybe, in the future, someone can report it with more details from a web console.

**Comment by Jerommmeke** [comment]
I stil have problems. But when I discovered that the mouse did not work in the upper menu, it stil worked in de left Side menu.
I disagree that it has something to do with browser limitations. When I go over the upper menu, the mouse stil shows an over effect and the mouse still moves all over the screen.

**Comment by photopea** [comment]
We had a bug such that Photopea did not work in Safari 12. What Safari are you using?

**Comment by Jerommmeke** [comment]
Check thuis video please https://youtu.be/YLMAmGoY4nY.

**Comment by photopea** [comment]
I still wish to know what version of Safari do you have.

**Comment by Jerommmeke** [comment]
![image](https://user-images.githubusercontent.com/74272093/100154740-5dea0a00-2ea6-11eb-9499-f8878515da15.jpeg)

**Comment by Jerommmeke** [comment]
Of i use Photopea.Com on my MacBook Pro (2013 version) with Safari 14 (15610.1.28.1.9) Theo I get the message that the website is using a lot of memory and that the macbook could react slow.

**Comment by Jerommmeke** [comment]
But then my next question, where is the app in the appstore? I had an app before, but it's gone.

**Comment by photopea** [comment]
I wish you have told me that earlier, that you are using Safari 14.2

Safari 14.2 is an experimental Beta release of a Safari browser. It is not a "Stable" version and it is not expected to work correctly.

If you want, you can ask Apple to fix it. But in general, I think it is a bug in your browser, and we can not do anything about it.

Photopea will not work, if it can not allocate enough RAM memory. Every pixel takes 4 Bytes, so if you have 1 billion pixels, you need 4 GB of RAM.

We never put Photopea into any app store.

**Comment by Jerommmeke** [comment]
Safari 14.2 expreimental browser? I never put BETA updates on my iPad Pro, I am not a developer. I am an end user, so when Apple gives an update, I download that version.

I Tought I had an app before. It didn't work correct, so I uninstalled it en when I went to the AppStore I could not fine it Andy more. Strange ... then I made a misstake.

**Comment by photopea** [comment]
According to Wikipedia, Safari 14.0 is the latest Safari for iOS: https://en.wikipedia.org/wiki/Safari_(web_browser)

What iOS do you have? Maybe you have Beta iOS, which always downloads Beta Safari.

**Comment by Jerommmeke** [comment]
How can i check the version of safari on iOS? The software is iPad os 14.2. It's not a beta, it's a stable release.![image](https://user-images.githubusercontent.com/74272093/100167044-6c442000-2ebe-11eb-929d-fe25fd3706a4.jpeg)

**Comment by Jerommmeke** [comment]
![image](https://user-images.githubusercontent.com/74272093/100167609-bed20c00-2ebf-11eb-9dde-5bafc935cf36.jpeg)
I am using iPad OS 14.2. According to the image below I am using Safari 14, not 14.2.
![image](https://user-images.githubusercontent.com/74272093/100167771-13758700-2ec0-11eb-83c8-beb799ca796c.jpeg)

**Comment by photopea** [comment]
I see, you are right, the latest iPadOS is 14.2.

But I still think there is a bug in Safari. It would really help, if you could somehow see the messages in the web console and tell me, if there are any errors.
