### ISSUE TITLE
Drag and drop a layer style effect to change it position on artboard

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2607]
Like in #2602 layer style effect should to have possibility to change it position by dragging. 

I don't know any other method to change center of radial gradient in Photoshop (in Photopea there are X and Y coordinates).
In shadow effect by this method user can easly change the distance and angle in same time.

**Comment by photopea** [comment]
I implemented it! :)

For a gradient fill and a pattern fill, it moves the origin of the fill.

For a Drop Shadow, Inner Shadow, Satin, it moves the Distance and the Angle, as you would expect.
