### ISSUE TITLE
Photopea Crashes followed by unresponsive page

### ISSUE THREAD

**Issue by Bombsquad2K** [photopea/photopea#2609]
I recently got into using Photopea because I simply like doing digital art with it. Mostly because I cannot afford Adobe Photoshop.

I found 2 big issues with photopea and I am not sure whether it is PC issue, photopea just simply crashing, and maybe browser settings

1. I get occasional crashes when simply loading in a font I want to use. outdated fonts a problem.....
2. The other one is, photopea seems to crash when the memory is overloaded and when it does the page crashes. Is there a active memory limit while having browser open? 

Is photopea only newer photoshop files and fonts? If so, could it be specified?

Used a CS3 PSD and Photopea crashed followed by unresponsive page when I tried to edit a smart object that was text.

**Comment by photopea** [comment]
Hi, what web browser do you use? Could you update your web browser and disable all browser extensions? Does the problem still happen?

**Comment by photopea** [comment]
i have to close it because of lack of details
