### ISSUE TITLE
photopea drop down menus not working

### ISSUE THREAD

**Issue by nctdreams** [photopea/photopea#2610]
i cannot click anything on the top menu bar (aka files, edit, image, layer… etc) except for the magnifying glass. usually, when i press those buttons, drop down menus show up. now it doesn't, for some reason. this started happening today and i've never had this problem before. my browser (safari) is up to date and i don't understand why it's happening. are there any tips to get photopea working again?

**Comment by photopea** [comment]
Hi, could you try to disable all browser extensions and try it again?

**Comment by nctdreams** [comment]
i don't actually have any extensions installed on my browser so unfortunately no i cannot disable them

**Comment by photopea** [comment]
Can you see any errors in a browser console?

BTW. I tested Photopea in Safari on Catalina and Big Sur, and it works well. So I really don't know how to reproduce it.

**Comment by nctdreams** [comment]
sorry, i'm not too sure how to do that. could you possibly tell me how?
and would photopea work on a macbook air that was made in 2015/2016? i was looking around for updates on my browser but there were no available updates so that's why i believed my browser was up to date but i could be wrong.

**Comment by 7ROSES1** [comment]
I am having the same problem, any idea how to resolve it ? using safari

**Comment by dentistformyeye** [comment]
To open the console, select Develop > Show Javascript Console in the browser menu bar. To store a screenshot in your clipboard, use Command-Shift-4.
![image](https://user-images.githubusercontent.com/51429646/99210861-ea087d00-2794-11eb-8fed-0737043431f3.png)

**Comment by nctdreams** [comment]
![Screen Shot 2020-11-15 at 7 59 53 PM](https://user-images.githubusercontent.com/74484696/99211480-3f389480-277d-11eb-8359-042dd569ec82.png)
that's what it says and also there is a lot of errors that say:
"blocked a frame with origin "[link]" from accessing a frame with origin "[link]." protocols, domains, and ports must match.

**Comment by 7ROSES1** [comment]
This is not working out for me...any other ideas ?

**Comment by photopea** [comment]
@7ROSES1 Do you guys have iOS 12? Someone else is reporting problems with iOS 12.

**Comment by 7ROSES1** [comment]
I never got this problem before it was working fine. did you guys changed something ..I di not change anythig in my system

**Comment by photopea** [comment]
we change photopea several times a day. What iOS do you have?

**Comment by deadfandoms** [comment]
I also have been having the same problem but on mobile. It was working just fine a few days ago, I don’t know what you guy did in the new updates but something was messed with. 
You’re able to select the things on the hot bar like ‘file’ and such but as people have said nothing drops down so you aren’t able to open more files

**Comment by photopea** [comment]
@deadfandoms Do you have iOS 12?

**Comment by 7ROSES1** [comment]
I have a Mac sierra ...this has never happened before

**Comment by deadfandoms** [comment]
@photopea Yes I do, I’m not able to update my phone for some reason

**Comment by deadfandoms** [comment]
If it comes down to just needing to update from iOS 12 I can see what I can do

**Comment by nctdreams** [comment]
are there others who have reported issues with photopea on macbooks? because that's the one i'm having trouble with. or is it just with ios 12 devices?

**Comment by 7ROSES1** [comment]
@nctdreams I am having problems with my mac ..no one is able to fix it yet ....please???

**Comment by nctdreams** [comment]
@7ROSES1 no i know! but i unfortunately can't help you with that because i'm having the same issue :/ i'm hoping the problem will be fixed soon so we can go back to using photopea normally :)

**Comment by photopea** [comment]
Guys, we can not fix anything, if we can not reproduce the problem ourselves (make the problem happen ourselves).

I have tested Photopea on a Macbook Air with Big Sur in Safari. Sadly, everything works well and no problem happens.

We need you to tell us more, what should we do to make the problem happen. Otherwise, we can not fix it.

**Comment by nctdreams** [comment]
i have no idea how to recreate the problem but i've noticed that if i open the javascript console, there are many errors popping up. however, if i disable cross-origin restrictions and refresh photopea, the errors in the console disappear. it does not fix the issue of the drop-down menus not working because there's now "syntax error: unexpected character '#' (1:6)" though. if i refresh the page again, an error shows up saying "failed to load resource: the server responded with a status of 404 ()"

**Comment by nctdreams** [comment]
i've also just noticed that if i use a different browser — aka google chrome in my case — photopea works again. its just a matter of my safari browser not working for some reason

**Comment by photopea** [comment]
I found a problem and fixed it. Photopea should work again in an old Safari 12 from 2018.

But I still recommend you to upgrade to a newer Safari for the best experience. There is even Safari 14 available now.

Apple is very slow with browser progress. Even Chrome from 2016 is more capable than Safari from 2018.

**Comment by camoody1** [comment]
First off, why would you resurrect a 2.5 year old ticket instead of opening a new one?

And second, of course Photopea works with Chrome and all other Chromium based browsers. I've been working in it all morning. Try running Photopea in In Cognito Mode to see if there is a browser extension causing you problems. If it works in that mode, you'll need to uninstall your extensions until you find out which one is breaking Photopea.
