### ISSUE TITLE
Cannot save my work

### ISSUE THREAD

**Issue by ghost** [photopea/photopea#2611]
Buttons are now unresponsive and I cannot save my work nor download it.

![image](https://user-images.githubusercontent.com/74524232/99214071-393cc500-280a-11eb-9884-f3f16057ac9e.png)

**Comment by IamFlea** [comment]
Try to disable browser extensions.

**Comment by photopea** [comment]
@RC1990xy did you disable your browser extensions? Did it help?

**Comment by RC1990xy** [comment]
Your response is too late. I cannot possibly wait 3hours for the solution. Thanks anyway.

**Comment by photopea** [comment]
We need you to describe, how to reproduce a problem. We can not fix it otherwise.
