### ISSUE TITLE
Export as ... no longer has the point for extension

### ISSUE THREAD

**Issue by Dida83** [photopea/photopea#2612]
Hi, When I try to export a file in .jpg (or others), it no longer gives me the point and saves everything as TXT

![Cattura](https://user-images.githubusercontent.com/61692188/99245426-d811f300-2803-11eb-9bcc-b92029ae4c50.PNG)

**Comment by photopea** [comment]
Hi, I am 99.9% sure that some of your browser extensions is modifying the files which you download.

If you don't know which extension it is, try disabling all of them. Let me know if it helped.

**Comment by Dida83** [comment]
thank you!
I tried restarting the Photopea app and everything seems ok :-)
