### ISSUE TITLE
Distance is one pixel off

### ISSUE THREAD

**Issue by RoryIsAwesome6116** [photopea/photopea#2613]
Hello. I was using the distance tool when I noticed that there was one extra pixel to the left. Please fix this bug as it will help save time in making pictures.

Thanks, Rory

**Comment by photopea** [comment]
Hi Rory, do you mean the Distances checkbox of the Move tool? Can you show us a screenshot of that tool showing an incorrect distance?

Note, that the distance is always rounded upwards, so 21.1 pixels will be rounded to 22 pixels.

**Comment by hxim** [comment]
I tried on my tablet and horizontal distance is wrong shows 3 pixels but distance is 4 pixels see screenshot:
https://www.photopea.com/#i-qEkXi6s

**Comment by photopea** [comment]
Hi, the issue should be fixed now. Thanks for reporting! :)
