### ISSUE TITLE
images with clipping masks export as gifs 

### ISSUE THREAD

**Issue by marvelseoks** [photopea/photopea#2614]
i've been trying to download a few edits i've made, but every time i go to export the file as a png.. it turns into a gif. and when i try exporting it as a jpg, the image comes out glitchy with parts missing. please fix this.

**Comment by photopea** [comment]
Hi, it is not a GIF, it is an animated PNG.

Do you have any layers, whose name starts with "_a_"? That is the animation mechanism in Photopea. Try to rename these layers into something without "_a_" at the beginning.
