### ISSUE TITLE
3D Viewer not working

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2616]
1.) I opened new project (white background)
When I go to 3D Viewer and click "Load Color" or "Load Depth" it does nothing and shows exception 
`(index):51 Uncaught 1`
on this line
`if(bpp!=24 && bpp!=8) throw bpp;`
(bpp variable is set to 1)
2.) When I convert any layer to smart object then open that smart object (double click)
   and then after I click "Load Color" or "Load Depth" it always says "Smart Object updated" instead of doing anything

**Comment by photopea** [comment]
Hi, I fixed it, thanks! :)
