### ISSUE TITLE
Paste not working properly after copying a path

### ISSUE THREAD

**Issue by brhndursun** [photopea/photopea#2617]
Hello,

This issue happens when you copy-paste a path and then copy paste an image.

To reproduce this issue please follow these steps:
1. New Project
2. Draw a shape or draw with pen
3. Reshape your drawing with Direct Select (A) tool
3. Select your drawing with Path Select (A) tool
4. Copy and paste selected path (It should be 1 layer with two seperate paths)
5. Copy and paste an image to canvas and fail

or you can watch this gif
![issue_photopea](https://user-images.githubusercontent.com/8144522/99522822-3b885600-29a7-11eb-9173-cd28f9484e77.gif)

When I try to paste an image to a new canvas, it still pasting previously coppied path.
Somehow I managed to fix this issue by selecting a raster layer with Rectangle Select (M) and copy-paste to canvas. 

Does this supposed to be happen like this way? Am I missing something? 

Thanks in advance.

**Comment by photopea** [comment]
Hi, I fixed the problem.

Now, vector paths are copied as text into the main clipboard of the device. They will overwrite the image in the clipboard. Similarly, the copying an image will overwrite the vector paths in the clipboard.

It also means, that you can copy paths, close Photopea, open it later and paste the paths. Or paste paths as text into an email and send it to a friend, who can copy the text from an email and paste it into Photopea as paths :)
