### ISSUE TITLE
"Canvas size" not working

### ISSUE THREAD

**Issue by PanCap** [photopea/photopea#2618]
By using "Canvas size" change in "mm" it made whole canvas black and my picture disapeard. After exporting in .jpg picture was empty(white). Thank you and sorry for my english

**Comment by photopea** [comment]
Hi, I think your size was too big, and your computer ran out of memory.

If you want to have a large size in MM, you should decrease the DPI. Make sure your document is not more than 1 billion pixels.

E.g. 30 000 pixels x 40 000 pixels is 1.2 billion pixels. Convert MM to Inches and multiply by the DPI to get the value in pixels

For DPI=70:  50 mm = 2 inches ;  2x70 = 140 pixels.
