### ISSUE TITLE
Couldn't open 42Mb sketch file!

### ISSUE THREAD

**Issue by Beastme** [photopea/photopea#262]
I can't open 42Mb sketch file on this page.
Show this message "Not enough Memory (need 1669Mb)"
Please let me know how to fix it

Thanks

**Comment by photopea** [comment]
Hi, could you please send us your Sketch file to support@photopea.com ?

**Comment by Beastme** [comment]
Hello. Thanks for your quick message!

https://www.dropbox.com/s/v2d1d2fpkkogn2a/125.sketch?dl=0

Please check my sketch file.

Regards.

**Comment by photopea** [comment]
I am sorry, I didn't have time to look into it until now. And the link is expired now :(

**Comment by photopea** [comment]
I have to close it because of lack of details :(  Please cooperate with us on solving such problems.
