### ISSUE TITLE
Ctrl + Shift + G shortcut for ungrouping the group

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2620]
As in the title. There insn't  such of shortcut in Photopea. 
Also right click on the group in layers pallete should to have that option.

**Comment by photopea** [comment]
Hi, I implemented the keyboard shortcut.

But I think this option is used quite rarely. You rarely want to move layers outside the folder. Also, I think the menu on the right click is too long now, so I did not add "Ungroup" into it.

**Comment by MichalSZZ** [comment]
Shortcut only is OK. Thank you.
One of my student asked for it.
