### ISSUE TITLE
Photopea Art - Brush Settings, Pen Pressure Simulation and More!

### ISSUE THREAD

**Issue by frostedddev** [photopea/photopea#2621]
Hey Photopea! Love your webapp! I use it everyday! But I do wish for more inprovements regarding brush settings! I do reference photopea with Photoshop, and just to be honest Photoshop has way more customization features & settings! For example you cannot simulate pen pressure with the pen tool! I will provide specific settings I hope to get added below! If the feature is already added, please correct me!

Shape Dynamics (I think this is already added with a rename of Tip Dynamics, but I may be wrong)
Scattering
Texture
Dual Brush
Transfer
Control Setting, Pen Pressure Simulation!

I like to do digital art/doodling, but I just really hope to simulate Pen Pressure with a pen tool! ( I am using a mouse )

If I posted this in the wrong place, please tell me and I will repost or remember it in the future!

Thanks, FrosteddDev

**Comment by Kristopian** [comment]
I Know Scatter And Shape Dynamics Are Both Here And You Can Change The Texture Of The Brush (I Think You Mean Define New Brush And Import Adobe Brush File) And That Is About All The Features You Mentioned That I Know Are In Photopea Right Now, I Know I'm A Bit Late And  These May Have Been Added After This Post But I Hope This Helps A Little

**Comment by xan2622** [comment]
I hope Photopea (in the future) features more **Brush Shape Dynamics** (like "fade").
https://www.photoshopessentials.com/basics/photoshop-brushes/brush-dynamics/shape-dynamics/

To be able to do things like that: 

[<img src="https://user-images.githubusercontent.com/1732773/147693859-46cfd775-1292-4d99-83a1-b45b8832ca11.png" width="30%" height="30%">](https://youtu.be/7Akao6t2vd4?t=714)
<img src="https://user-images.githubusercontent.com/1732773/147693070-ff005eb8-5624-499a-9b79-c6cc7fadeabd.jpg" width="30%" height="30%">

**Comment by photopea** [comment]
Photopea can already do it - see "pressure detection" - https://www.photopea.com/learn/brush-tools

**Comment by xan2622** [comment]
I know, but the **Brush Shape Dynamics** allow everyone to achieve these effects, not only pen displays/graphics tablets owners.

**Comment by photopea** [comment]
What do you mean? I dont really know much about advanced brush settings in Adobe Photoshop. Can you show me e.g. a video of that feature?

**Comment by photopea** [comment]
I have to close it because of lack of details. Also, we have added some new parameters to our brushes since then.
