### ISSUE TITLE
Cutout Filter

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#2623]
It would be nice to have a filter similar to Photoshop Cutout.

**Comment by IamFlea** [comment]
I can check it right after I finish the stamp filter I've been working on. And I would like to do charcoal after. The first parameter seems to be obvious. Two others looks trickier.

**Comment by mustafaGFX** [comment]
it would be nice to have a filter similar to the camera raw filter in photoshop  :)

**Comment by photopea** [comment]
We don't know how to make this filter, so I give it up.
