### ISSUE TITLE
Color replacement tool and background eraser leave gaps when moved too quickly

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2629]
The color replacement tool and background eraser aren't working smoothly. If the mouse/pen gets moved too quickly, some spots get skipped and square edges appear. This doesn't affect the brush tool, pencil tool, or normal eraser tool.
1. Open a new empty project in Photopea in an incognito window (extensions disabled).
2. Set the foreground color to black.
4. Select the color replacement tool and set the mode to Luminosity. Make the brush size somewhat big (30 px or more).
![image](https://user-images.githubusercontent.com/51429646/99889433-20297f00-2c23-11eb-96de-14ea3f3d59b6.png)

3. Scribble quickly across the layer.
![image](https://user-images.githubusercontent.com/51429646/99889464-929a5f00-2c23-11eb-8900-17befaaf4743.png)

It might have to do with the way the tools decide what to change and what not to change. However, the issue happens with all sampling options: Brush Center, Start of Stroke, and Background Color.

**Comment by photopea** [comment]
I improved it a little. Improving it even more would require a lot of work, so I will keep it as it is.

**Comment by dentistformyeye** [comment]
Thank you! It's much more usable now.
