### ISSUE TITLE
Gradient in Outer Glow or Inner Glow not working

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2630]
1. Open photopea and pea.psd
2. Open Layer Styles on "Welcome" layer
3. Go to Outer Glow settings
4. Click on Gradient to open Gradient Editor
5. Error appears and Gradient Editor opens but is not working (cannot move sliders)
Note: Same error also happens when I try to change gradient with dropdown button.
![image](https://user-images.githubusercontent.com/6370548/99898835-e8631b80-2ca4-11eb-9328-159a4dc48b00.png)

**Comment by photopea** [comment]
I think I fixed it, thanks! :)
