### ISSUE TITLE
Errors in Filter Gallery

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2631]
I double clicked on selected filter name in right side in Filter Gallery and it opens text editor (changing name?) and after I click somewhere else errors start to appear in console. See screenshot:
![image](https://user-images.githubusercontent.com/6370548/99899774-34fe2500-2cac-11eb-9ea1-0fbc7bf6923a.png)

**Comment by photopea** [comment]
It is fixed, thanks!

BTW. how do you find these bugs? How many hours a week do you use Photopea? :)
