### ISSUE TITLE
Плохой интерфейс

### ISSUE THREAD

**Issue by redmin22882** [photopea/photopea#2632]
Ээмм а что делать если у меня столь ужасный тут интерфейс? Так и реклама на пол экрана 
![Screenshot_20201122-004210](https://user-images.githubusercontent.com/74855608/99899924-89b29780-2cce-11eb-85e6-b45ad1f72217.png)

**Comment by mustafaGFX** [comment]
try to rotate your phone ( i am a user not from photopea team )

**Comment by redmin22882** [comment]
> попробуйте повернуть свой телефон ( я пользователь не из команды photopea).
> Русский: попробуйте повернуть телефон (я пользователь, я не из команды photopea)

Пытался но всё тщетно и не помогает

**Comment by photopea** [comment]
It should be fixed now. We decided not to show any ad on such small screen.
