### ISSUE TITLE
Quick mask + tools errors

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2633]
1. I selected Quick Mask Mode with button in the bottom left
2. When I try to use Spot Healing Brush, Patch Tool or Content-Aware Move Tool errors like this appear
![image](https://user-images.githubusercontent.com/6370548/99900411-a095c180-2caf-11eb-97b1-838e7de88d70.png)

Edit: Also happens when editing regular Raster Mask

**Comment by photopea** [comment]
Fixed, thanks! :)
