### ISSUE TITLE
Small problem

### ISSUE THREAD

**Issue by nofearifat** [photopea/photopea#2634]
Hello . I had a small problem that I could not solve. I also get good performance on my mobile phone. But how can we make the electoral lines thicker. The place I choose is very uncertain and does not appear. Have a nice day

**Comment by photopea** [comment]
Hi, what are the electoral lines? You can modify the stroke of vector graphics this way:  https://www.photopea.com/learn/vg-structure

**Comment by photopea** [comment]
I have to close it because of lack of details.
