### ISSUE TITLE
Problem with exporting Figma -> Photopea -> Photoshop

### ISSUE THREAD

**Issue by rommashka** [photopea/photopea#2636]
I have .FIG file. It contains 2 different fonts - and I uploaded them into Photopea. Everything is excellent.
Then I save this project as .PSD and cannot open it with Photoshop.

It shows me this font error
![Снимок экрана (4)](https://user-images.githubusercontent.com/72567669/99956967-fa71b680-2d97-11eb-80ab-ed30b7227e0f.png)

I had this problem before, but it happened only with After Effects, when i tried to open PSD file. But Photoshop worked.
Now even PS cannot open this file.

These problems happen when I use my home PC on Windows.
But my office Macbook has not these font problems at all.

Photoshop on both devices is 2020.

p.s.: Sorry for my English. Let me know if you need more details.

**Comment by photopea** [comment]
Hi, can you send me your FIG files to support@photopea.com ?

**Comment by rommashka** [comment]
ofc, but I solved this problem by installing the newest versions of Photoshop and After Effects. Not it works, but this summer versions of AE and PS had those font errors.

I don't suppose it is actual now, that's why I closed the issue, but I'll send you this .FIG file.

**Comment by photopea** [comment]
I was able to convert your FIG into PSD with Photopea. I was able to open that PSD file in Adobe Photoshop 2019.

Maybe you used some old Photoshop, which does not support artboards or live shapes.
