### ISSUE TITLE
Why is it every time I attempt to save a document in Photopea, it tries to open the file in my browser and crashes my browser

### ISSUE THREAD

**Issue by stevenclark1397** [photopea/photopea#2638]
Hey Folks,

It's my first time using Photopea as a school application, as a part of our first lesson we're required to take different screenshots within Photopea to demonstrate it's the programs different capabilities. Anyways, essentially the first task is to show how you you would go about saving your photo as a .PSD file. When saving file as a .PSD in Photopea, the file automatically tries to open the file in Chrome without permission and crashes the browse each time I try. I tried changing my windows preferences for opening .PSD files but, it doesn't show Photopea as an option. I even tried downloading other programs that are capable of opening .PSD's and that had no effect.

Any idea on how to fix this problem? I'd like to not have to deal with this

**Comment by photopea** [comment]
Hi, I think you configured your browser in a way, to make it open every downloaded file. 

I found this on the internet: https://services.dartmouth.edu/TDClient/1806/Portal/KB/ArticleDet?ID=75023 . Try to change the browser settings, so that it only saves a file, without opening it.

**Comment by photopea** [comment]
I have to close it because of lack of details.
