### ISSUE TITLE
Any text typed or edited is very small and unreadable

### ISSUE THREAD

**Issue by dandray** [photopea/photopea#2640]
When I upload a psd file and try to add text, or edit, it gives me very small text. 
And nothing changes if I change the font or size.

**Comment by dandray** [comment]
![Capture d’écran 2020-11-24 à 12 06 24](https://user-images.githubusercontent.com/14936606/100086277-7d087d80-2e4d-11eb-968f-88c314aaec14.png)

**Comment by MichalSZZ** [comment]
What size have the oryginal uploaded PSD. In px. You can check it in menu image-> image size

**Comment by photopea** [comment]
Hi, can you send us your PSD to support@photopea.com ?

**Comment by dandray** [comment]
> Hi, can you send us your PSD to [support@photopea.com](mailto:support@photopea.com) ?

I send it to you, thanks for the answer

**Comment by photopea** [comment]
Hi, I fixed the problem. But I still don't fully understand this feature of PSD format, so I am not sure if I fixed it correctly. But it works for your file :)

Note, that your PSD uses a commercial font Myriad Pro. Load it into Photopea to be able to modify text layers. Otherwise, it will be rendered with a substitute font and may look different.

**Comment by dandray** [comment]
Hi,
Thank you very much. It works perfectly.
Congratulations for having done such a wonderful online tool. It's even easier/quicker to use than photoshop.

Have a good end of week,
Dan

________________________________
De : Photopea <notifications@github.com>
Envoyé : jeudi 26 novembre 2020 20:42
À : photopea/photopea <photopea@noreply.github.com>
Cc : dandray <draydan@hotmail.fr>; Author <author@noreply.github.com>
Objet : Re: [photopea/photopea] Any text typed or edited is very small and unreadable (#2640)


Hi, I fixed the problem. But I still don't fully understand this feature of PSD format, so I am not sure if I fixed it correctly. But it works for your file :)

Note, that your PSD uses a commercial font Myriad Pro. Load it into Photopea to be able to modify text layers. Otherwise, it will be rendered with a substitute font and may look different.

**Comment by photopea** [comment]
You are welcome :)

For some reason, opening a new browser tab and loading Photopea.com (from a server thousands miles away) is faster than starting Photoshop from your own hard drive.
