### ISSUE TITLE
Ошибка при загрузке файла

### ISSUE THREAD

**Issue by Vlad1604** [photopea/photopea#2642]
При создании нового проекта, после появления белого окна, не загружается файл: при нажатии открыть, пишет "Из-за ошибки на странице она была перезагружена"
![2020-11-25_10-32-37](https://user-images.githubusercontent.com/75010798/100201994-c5896f00-2f11-11eb-8bb3-615e83a9606e.png)
![2020-11-25_11-22-26](https://user-images.githubusercontent.com/75010798/100201999-c6ba9c00-2f11-11eb-804f-834d945bf4e8.png)

**Comment by IamFlea** [comment]
[Google Translate] When creating a new project, after a white window appears, the file does not load: when you click open, it says "Due to an error on the page, it was reloaded"

**Comment by photopea** [comment]
What version of a browser are you using? Can you update your browser?

Is it when opening a file or when creating a new file?

**Comment by Vlad1604** [comment]
1. Использую Yandex Browser
2. Я использую актуальную версию Яндекс.Браузера
3. Это происходит при открытии файла с компьютера, ранее при этих действиях подобного не возникало
(создаю новый файл, появляется белое окно, далее хочу загрузить фото кнопкой "открыть"с компьютера, но оно не загружается - на сканах видно)

**Comment by photopea** [comment]
Can you try Photopea in Incognito Mode?

**Comment by Vlad1604** [comment]
Вышел из аккаунта, происходить тоже самое, и по ссылке тоже фото не загружается (висит окошко "загрузка" без действий)

**Comment by photopea** [comment]
About a month ago, we implemented a new Native File System API. This should let Photopea rewrite files in your computer, without the "Download" window in between.

Yandex browser seems to support Native File System API. But when we call window.showOpenFilePicker(), it reloads the webpage.

I think it is a bug in Yandex browser. I recommend you to use some different browser. Also, I wrote to Yandex on Twitter and asked them to fix it.

**Comment by photopea** [comment]
![image](https://user-images.githubusercontent.com/15955558/100234238-122d7400-2f2b-11eb-9939-72b50d64136a.png)

**Comment by photopea** [comment]
You should enable the flag: browser://flags/#native-file-system-api
