### ISSUE TITLE
Imported PDF is not shown correctly

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2645]
I have this PDF
[Lud8.pdf](https://github.com/photopea/photopea/files/5600042/Lud8.pdf)

The first "page" is a gameboard.
![image](https://user-images.githubusercontent.com/11801254/100299641-ecc45880-2f72-11eb-99d4-bd2d674dd543.png)

But when opened on Photopea, one of the grey lines are disappeared.
![image](https://user-images.githubusercontent.com/11801254/100299682-01a0ec00-2f73-11eb-96a6-49e8535de9bb.png)

**Comment by avagp** [comment]
I have taken a look into it.

And i found that 2 grey lines got merged, and somehow not completely fill.  👍 
![image](https://user-images.githubusercontent.com/11801254/100300139-1c279500-2f74-11eb-9e94-4544fce188fd.png)

PSD:
[Page 1.zip](https://github.com/photopea/photopea/files/5600070/Page.1.zip)

**Comment by avagp** [comment]
When i save it get the splitting open paths history step

**Comment by avagp** [comment]
This issue is not a problem, but i am here asking if you could solve it. :)

**Comment by photopea** [comment]
I am very sorry for such delay, it is fixed now :)

**Comment by avagp** [comment]
:)
Thanks anyways
