### ISSUE TITLE
Feature Request: GIF fram as an option

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2646]
Hi, i have been making a lot of GIFs lately, and i was wondering if something could change about the frame designation.

As now, you have to add "_a_" to every layer that should be part of the frames of the GIFs.

I would like to have the option to right-click the layer and select something like "Set as frame", and the frame gets a little icon somewhere (like the smart object) so i can know which layers are frames and which ones not.

:)

**Comment by photopea** [comment]
Hi, our documents still need to be compatible with other PSD editors, such as Adobe Photoshop. If we add additional properties to a layer, Photoshop could remove them from a PSD file. While a layer name can be anything, and PSD editors do not have a reason to change layer names.

I can add an option Layer - Animation - Make Frames, which would add \_a\_ to the names of selected layers. What do you think?

**Comment by avagp** [comment]
It is a good solution.

You can also add "change frame duration" and append the milliseconds to the
name.

Last week I was teaching a friend to do gifs and she never remembered what
to preappend to the name to do a frame.

With this changes it will be also very intuitive to discover yourself how
to do gifs

:)

**Comment by photopea** [comment]
The prefix is "\_a\_" as the "Animation", I thought it will be obvious :D

I added the Make Frames button. Rgarding the duration: if you want all frames to have an equal duration, do not write any numbers at the end. The frames will be given a default duration, and you can modify the d durplaying speeing the export.

**Comment by avagp** [comment]
Thanks! I was speaking about the _a_layer, *3000*

I know at the export dialogue you can modify the duration of the whole gif.

But i meant to be able (in the same way as to append _a_) to append the
modified duration of a particular frame.

**Comment by photopea** [comment]
You would have to select a layer, press Layer - Animation - Modify Duration, type a new duration, click OK. It is 6 clicks.

I think it is faster to double-click a layer name and type the duration directly.

**Comment by avagp** [comment]
Totally, but now seems like a built-in feature, rather than a trick.

So i can teach it properly :D

**Comment by dentistformyeye** [comment]
> I think it is faster to double-click a layer name and type the duration directly.

A menu option for changing duration might be slower for a few frames, but it would be much faster for changing the duration of many frames at a time, especially when all except one of the frames have the same duration.

Separate feature request: menu option to convert selected _a_ layers back to regular layers. (It could have a separate button, or you could instead make the existing Make Frames button a toggle.)
Analogous menu options for making layers exportable and non-exportable, i.e. by adding and removing -e-, respectively, might also be helpful.

**Comment by avagp** [comment]
I have to say that the menu to turn layers into GIFs has been a good improvement on my work making animations.

Now i can create folders with the elements inside, and then convert each folder into a layer, and finally change every layer to a frame in a couple of clicks.

So, in that line, i believe what dentistformyeye is asking may improve the work as well.

Of course adding to a layer's name **_a_**  or **,1500** is easy when doing one or two, but when you are working with animations with more than 20 frames, it is kinda slow.

**Comment by avagp** [comment]
Ok, now i have just noticed that you can name a folder _a_ and works as a frame.

Cool :)

**Comment by photopea** [comment]
Yes, if you think about it, you can set the name to \_a\_ to adjustment layers, etc. So many "tricks" are possible. I am sure I am not even aware of all tricks which could be done with this mechanism :D

And it is really that simple. Imagine you hide all layers starting with \_a\_ , and then, enable the first one, export a static image, disable it, enable a second one, export a static image, and so on.

**Comment by avagp** [comment]
![image](https://user-images.githubusercontent.com/11801254/107800636-c6c27f00-6d3d-11eb-8f47-3ae6e3ea1927.png)


BTW, there is a key combo to hide/display selected layers?

**Comment by photopea** [comment]
I think you can Alt+click a specific "eye" to see only that layer / folder

**Comment by dentistformyeye** [comment]
> Separate feature request: menu option to convert selected _a_ layers back to regular layers. (It could have a separate button, or you could instead include the functionality in the existing Layer > Animation > Make Frames button.)

I would still find it convenient to have this feature because trying out different combinations of frames would be quick. Duplicate Into can act as a substitute, but is inconvenient on devices with little RAM.

**Comment by photopea** [comment]
@dentistformyeye Now, there is an option Layer - Animation - Unmake Frames, which removes "_a_" from layer names.

**Comment by dentistformyeye** [comment]
Thank you!
