### ISSUE TITLE
How do i get smart objects to be vectorized on PDF?

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2647]
The title is a little missleading, so let me explain:

I have a smart object layer that only has vectors inside (texts and shapes).

But when i download the project as PDF the smart object does not get vectorized.

Is this an intended behaviour or not?

(i need to know because i have sent to print a lot of boxes and i have noticed this after sending the final printable file 😳 )

**Comment by photopea** [comment]
Every smart object is actually a file (JPG, PNG, PSD, PDF, SVG).  Photopea and Photoshop can scale PDF and SVG smart objects smoothly in a target document. But once you modify a smart object, it turns into a PSD smart object (which is blurry when you scale it up).

It is hard to decide, if a PSD smart object can be turned into a vector graphics, which looks the same.

What about rasterizing your document when you save as a PDF? You can set the right DPI in Image - Image Size, and be sure, that layer styles, adjustment layers, etc. will not be lost.

**Comment by avagp** [comment]
I have increased the size of the image on the smart object and showed fine on the main project when exported. So it was a matter of resolution.
