### ISSUE TITLE
Noticeable freezing / slow down when using a text element

### ISSUE THREAD

**Issue by bonebagmel** [photopea/photopea#2648]
I made a little PNG to use as a twitch panel (640 x 136 px)

In it I use a text element with the font "Major Mono Display". Whenever I try to modify the text (via text itself, text size, etc.) photopea pretty much stops and then very slowly start dishing out the changes I may have typed. This doesn't happen if I use the move / resize tool.

**Comment by photopea** [comment]
I just tried to make a text layer with "Major Mono Display"  and it works smoothly as usual.

Can you save that slow document as a PSD and send it to support@photopea.com ?

**Comment by photopea** [comment]
I fixed the error. BTW. you will not be able to see the selection of text, because the height of the selection always corresponds to the line height (leading), which you set to Zero.
