### ISSUE TITLE
uninstalled everything for adblock and has text saying turn off adblock

### ISSUE THREAD

**Issue by LETMESAYMYISSUE1128726821** [photopea/photopea#2649]
fix this now please it's thanksgiving

**Comment by photopea** [comment]
Can you disable all browser extensions and try it again?

**Comment by LETMESAYMYISSUE1128726821** [comment]
ok

**Comment by LETMESAYMYISSUE1128726821** [comment]
um how

**Comment by photopea** [comment]
Go to chrome://extensions and disable your extensions

Or try Photopea in Incognito mode.

**Comment by LETMESAYMYISSUE1128726821** [comment]
Thanks for the tip!

**Comment by LETMESAYMYISSUE1128726821** [comment]
It works!

**Comment by photopea** [comment]
Ok, I am glad it helped. Your computer might be faster now, too.

**Comment by LETMESAYMYISSUE1128726821** [comment]
Thanks a LOT!
