### ISSUE TITLE
Filter like Topaz Clean

### ISSUE THREAD

**Issue by imms93** [photopea/photopea#265]
It would be nice to have a filter like Topaz Clean or in alternative something similar to Photoshop's Smart Sharpen

**Comment by photopea** [comment]
Topaz Clean: I think it looks quite the same as Surface Blur filter.

Smart Sharpen: I think it is quite similar to Unsharp Mask.

What do you think?

**Comment by imms93** [comment]
Smart sharpen is quite different from unsharp mask, I think. I never used Surface Blur so I don't know what does exactly, but you could be right!

**Comment by imms93** [comment]
Sorry, I wrongly clicked on "close and comment". Yes, Surface Blur seems quite similar to Topaz as far as I know, but Smart Sharpen seems different from Unsharp Mask, I think gives more of a subtle effect to images.

**Comment by manticorp** [comment]
Smart Sharpen is the exact same as an Unsharp Mask, except:

* You can choose the inverse blur kernel (e.g. Gaussian, Motion Blur, Lens Blur)
* It is applied selectively to dark / light / mid tones by means of overlaying the sharpened image on top of the original and masking dark/light areas in a smooth way (tonal width / amount)

In many ways, smart sharpen is an improvement over unsharp mask as quite often applying an unsharp mask to shadowy areas in photographs just highlights noise, and in light areas will put rings around blown own highlights.

At the moment, it looks like the Photopea implementation of Smart Sharpen is just an unsharp mask, but it would be good to see the choice of blur kernel and selective high / low / midtone sharpening, especially for photos.

**Comment by manticorp** [comment]
In addition, Surface Blur looks the exact same as Topaz Clean.

I would close issue.

**Comment by photopea** [comment]
Yes, we are trying to make everyone happy by adding the features they ask for.

But in fact, we are just faking it by copy-pasting the same feature (unsharp mask) under different names, as we have absolutely no idea how these tools in other programs actually work :(

**Comment by photopea** [comment]
I will close it, as we don't know how exactly Topaz Clean works :(
