### ISSUE TITLE
Blending options

### ISSUE THREAD

**Issue by fastasfrick** [photopea/photopea#2650]
Blending options isn't working. Layer style panel doesn't pop up when I click on it.

**Comment by photopea** [comment]
Hi, everything works fine for me. Can you disable all browser extensions and try it again?

**Comment by fastasfrick** [comment]
Hi, I tried disable all extensions and it worked! Thanks!
Not sure what caused it tho

**Comment by photopea** [comment]
You dont have to disable all extensions. Just find one which is breaking Photopea and keep it disabled.

Users of extensions rarely know what exactly these extensions do. They can modify websites in any way they want.
