### ISSUE TITLE
CTRL - Z shuts down application (installed as app in chrome)

### ISSUE THREAD

**Issue by Javerages** [photopea/photopea#2653]
I have my project saved as a file on disk and when I press CTRL - Z chrome asks me if I want to save changes.
every time I press another button it asks me again. (Using qwerty keyboard)
It still allows me to save but enevitably shuts down (check out twitch.tv/javerageGames for details)

**Comment by photopea** [comment]
Hi, there is a Ctrl + W shortcut to close a current project. Are you usint AZERTY keyboard? In that case, Z is located at the W key.

Is your Chrome updated?

**Comment by hxim** [comment]
I can reproduce this issue in updated Chrome incognito window with following steps:
1.) Open photopea
2.) Open pea.psd
3.) Click on background layer (to select it)
4.) Press Delete on keyboard (to delete background layer)
5.) Press CTRL+W on keyboard.
6.) Pop up appears and I Press "Cancel" button there
7.) Press W on keyboard.
8.) Pop up appears (? but I did not press CTRL -> bug)
9.) I press "Cancel" again
10.) Now if I press almost any key on keyboard pop up always appears again (for example key "X" or key "5" )

**Comment by photopea** [comment]
That is because when a "popup messsage" appears, the browser does not tell a website, which keys were pressed or released while the popup was displayed.

I don't think we can fix it. The browser needs to tell a website, that Ctrl was released. We do not know about it otherwise.
