### ISSUE TITLE
Depth Map is not depth map issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2654]
Images from my camera open as "Depth Map" and "Main" but "Depth Map" is not really depth map it is lower resolution version of image or thumbnail it seems which is confusing. 

Screenshot:
![image](https://user-images.githubusercontent.com/6370548/100524764-0ce65880-31bb-11eb-8c88-968657dc1f43.png)

Image:
![DSC00066](https://user-images.githubusercontent.com/6370548/100524739-dc062380-31ba-11eb-8fab-005e15add85f.JPG)

**Comment by photopea** [comment]
Photopea just detects several images in one JPG file. It is hard to tell what is the actual meaning of the extra images. 

I fixed it. The layer will be named "Depth Map" only if it is grayscale.
