### ISSUE TITLE
Sito photopea

### ISSUE THREAD

**Issue by diocane12345** [photopea/photopea#2655]
Dio cane il vostro sito fa cagare ho perso un lavoro che ho fatto con duro lavoro per colpa del vostro pop-up del cazzo che mi diceva di disattivare l'ad block quando era già disattivato quindi cambiate lavoro

Cordiali saluti

**Comment by photopea** [comment]
Hi, I do not understand. Also, I think there are some offensive words. We do not reply to such messages.
