### ISSUE TITLE
Website slow/Completely breaks

### ISSUE THREAD

**Issue by rfhruigrhbtrhbtynty** [photopea/photopea#2656]
Everything is so slow and the thing you're editing just disappears sometimes, I spent thirty minutes on a homework assigment and it just broke

The ads might be causing this. I have to watch literal animated adverts while editing and it's really slowing it down

**Comment by rfhruigrhbtrhbtynty** [comment]
update: its slow when you're editing big canvases like 18x24in (i was making a poster), i started again on A4 and it works much better

**Comment by photopea** [comment]
Hi, Photopea is a raster editor and "at the bottom", graphics are rasterized as pixels.

How many pixels do you have in your documents? Is it a million, 10 millions, 100 millions?

You can compute pixels by mutliplying inches by DPI. So at DPI 100, you have 1800x2400 pixels = 4.3 million pixels.

You need a powerful computer to work with more than 20 million pixels smoothly. Keep the number of pixels (DPI) low.
