### ISSUE TITLE
Suggestion: arrow shape

### ISSUE THREAD

**Issue by plohoj** [photopea/photopea#2657]
I often have to insert screenshots and focus on certain areas with an arrow. But for this I have to use the line tool and draw 3 lines. It would be convenient if there was a tool that allows you to draw an arrow like a regular line with a tip.

An example of how I use arrows
![Example](https://user-images.githubusercontent.com/10156573/100620279-4b048900-332f-11eb-8ab9-2069ef2f6f0b.png)

**Comment by photopea** [comment]
Hi, switch to a Parametric Shape tool, and choose "Arrow" at the top.

**Comment by plohoj** [comment]
I would like not to insert the shape, and rotate it. I would like to indicate the beginning and end of the arrow in one click. Also, I need a line of arrows of different lengths with the same tip size.

**Comment by photopea** [comment]
Yes, that is exactly what you describe.

**Comment by photopea** [comment]
You are probably confusing it with a Custom Shape tool. That is not it, I was talking about a Parametric Shape tool.

**Comment by plohoj** [comment]
I found, thanks, this is what I needed. I really messed up with another tool
