### ISSUE TITLE
JPG capitalization seems to matter on google drive

### ISSUE THREAD

**Issue by nomorecs** [photopea/photopea#2658]
If I have a jpg on google drive and use "open with" command, PhotoPea does not appear as an available option if file extension JPG are capitalized.
Changing the file name so that jpg is lower case, Photopea appears as an option.
See images.
May be frustrating new users who don't understand why it doesn't work.

![lower case](https://user-images.githubusercontent.com/50219589/100642792-3c09e080-3307-11eb-9790-c4cb401e299b.jpg)
![upper case](https://user-images.githubusercontent.com/50219589/100642793-3ca27700-3307-11eb-8958-0fec445e7125.jpg)

**Comment by photopea** [comment]
@tomayac Do you know anything about Google Drive apps?

Photopea is associated with "image/jpg" MIME type and "jpg" extension. However, Google Drive does not show an option to open a JPG file in Photopea, when "JPG" is capitalized.

I tried to add "JPG" into a list of extensions, but it does not allow me to submit such list.

![image](https://user-images.githubusercontent.com/15955558/100677179-c33c7000-336a-11eb-85a7-85c4c1768c3a.png)

**Comment by photopea** [comment]
I added "image/jpeg" into the list of MIME types and it is fixed now.

**Comment by nomorecs** [comment]
Nice. Thanks for the quick action.

**Comment by tomayac** [comment]
Happy this got resolved before I even had a chance to look at it ;-) So yeah, since not all OSs work the same, you always have to specify the MIME types as well as the extensions for maximum compatibility. Glad it's working now!
