### ISSUE TITLE
Pen Tool not creating paths

### ISSUE THREAD

**Issue by imms93** [photopea/photopea#266]
Whenever I click on the pen tool and I chose "Path" mode, it doesn't let me create a path around an image, it shows the message: "Paths can be added to existing shapes only". Here's a gif:

![](https://i.imgur.com/4s4ZhPV.gif)

**Comment by photopea** [comment]
I guess you are refering to some behavior of Adobe Photoshop. PS has "working paths", which don't belong to any specific layer. They are shown in the Paths window instead.
I never understood the purpose of such paths. What exactly do you want to do? What about creating a vector mask for your layer?

**Comment by imms93** [comment]
I want to transform a path into a selection because when selecting with the lasso tool selections sometimes come out "wonky", I don't really know how to explain it but with the pen tool the selection is smoother. How do vector masks work?

**Comment by photopea** [comment]
I would recommend drawing a shape (e.g. red shape) with the pen tool, and give it a small opacity (so you can see what is under it). Then, you can click on the layer (in the Layers panel) while holding Ctrl - that would create a selection based on the layers transparency.

**Comment by imms93** [comment]
Thank you! I'll try doing that and see how it works.

**Comment by photopea** [comment]
I hope it worked. Maybe we will add Paths in the future for "text on path".
