### ISSUE TITLE
No ads, buy premium messing with my work

### ISSUE THREAD

**Issue by Draven370674** [photopea/photopea#2660]
Every 30 seconds or so a pop up appears at the top of my screen, telling me to stop blocking ads (no ads are blocked) and buy premium. every time i press cancel or ok, my cursor flings itself across the screen, with the pencil tool equipped, messing up my hard work, and i cant get rid of it unless if i erase the whole thing. And before anyone says "turn on incognito" or anything, im on a school computer and i cant. Please help

**Comment by photopea** [comment]
Hi, I am afraid there is no solution for your case. You must ask someone to disable adblockers on your computer.

**Comment by Draven370674** [comment]
There isnt any adblockers, and ive already tried disabling extensions too

**Comment by photopea** [comment]
So do you see ads in Photopea or not?

**Comment by Draven370674** [comment]
I dont see ads, there is just a piece of paper with a sad face and a folded corner instead of the ad, i already checked my computer and there is no ad blockers, i might just have to buy premium

**Comment by photopea** [comment]
Are you using Google Chrome? Have you tried disabling all browser extensions? Can you show me a screenshot of chrome://extensions ?

**Comment by Draven370674** [comment]
my teacher was going to im pretty sure anyway, so i guess problem solved, i just have to wait until they buy it

**Comment by Draven370674** [comment]
im gonna close it now, because i think my teacher is going to buy premium for everyone, is what they said im pretty sure
