### ISSUE TITLE
Brush area larger than brush border.

### ISSUE THREAD

**Issue by MichaelCodeleone** [photopea/photopea#2662]
Very annoying when going for precision!
It used to be such that when you used the brush, it would only fill in the area encapsulated by the border of the brush cursor. Now it goes way outside the border.

**Comment by photopea** [comment]
Hi, can you share a screenshot of what you mean? I think it does not work that way in my case.

**Comment by MichaelCodeleone** [comment]
I cannot screenshot the brush but I just realized the issue is exclusive to Safari. Just measured: A 100px brush leaves a 200px mark. Same issue on two different devices running macOS Catalina but I don't think the OS should make a difference.

**Comment by photopea** [comment]
You are right, Safari works differently than other browsers. It should be fixed now.

**Comment by MichaelCodeleone** [comment]
Works now. Thank you.
