### ISSUE TITLE
Filter - Render - Fibers

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#2664]
It could be nice to have a filter similar to the one in Adobe Photoshop.

**Comment by photopea** [comment]
@IamFlea Do you know how this filter could work? Is it similar to Clouds?

My only idea is to simulate hair with raycasting.

**Comment by IamFlea** [comment]
I wouldn't be surprised if it was something similar to perlin noise.

**Comment by photopea** [comment]
I was able to generate this without using Perlin noise. My observations:

- the average color in each line of pixels is almost identical
- the histogram of the image has a gaussian distribution

![pea](https://user-images.githubusercontent.com/15955558/101189882-ec554d00-3657-11eb-9086-c648067b968a.png)

**Comment by photopea** [comment]
Implemented! :)

**Comment by photopea** [comment]
@IamFlea hey how are you doing? Are you ok?

**Comment by IamFlea** [comment]
> @IamFlea hey how are you doing? Are you ok?

Heya, all good, how about you?

**Comment by photopea** [comment]
@IamFlea I am great, can I get in touch with you? What email address do you use?
