### ISSUE TITLE
Defringing & Removing edge halos

### ISSUE THREAD

**Issue by Jakemup** [photopea/photopea#2665]
There currently isn't really a easy or convenient way to remove edge halos left behind after using magic wand, magnetic lasso, etc. On Photoshop, there is a layer setting called "defringe", which automatically removes edge halos by matching the color of the halo's pixels with other surrounding pixels. The addition of this feature, or some form of it, would greatly benefit Photopea, solving many struggles people have had trying to remove edge halos manually.

**Comment by MichalSZZ** [comment]
Hi. Try to use mask after making selection (mask from selection). Click on mask thumbnail and go to filter -> other -> maximum/minimum.

See how does it works https://youtu.be/60GysIWun2s

**Comment by Jakemup** [comment]
> Hi. Try to use mask after making selection (mask from selection). Click on mask thumbnail and go to filter -> other -> maximum/minimum.
> 
> See how does it works https://youtu.be/60GysIWun2s

That works, but I would like a more convenient way of removing edge halos, and also one that is friendly to people who are new to photoshopping.

**Comment by miw-nik** [comment]
+1 We need a defringe tool!

**Comment by photopea** [comment]
Could you show me a PNG, where Defringe works well? Whenever I try it in Photoshop, it looks like it does not do anything.

**Comment by photopea** [comment]
I could not find a photo, that is used in your video. Could any of you provide a photo, where this feature performs something useful in Photoshop?

**Comment by HiroakiLion** [comment]
https://gyazo.com/ba5e82305fedb17f5baf24ec9b0ab6ab
from my article
https://blog.gridrooms.online/entry/2020/04/08/035336

This defringe plugin on GIMP is different process from photoshop.
Photoshop defringe produce much smoother better result, but it is not opensource.
There is no way to know how they do this.
At least on GIMP side, we have the plugin that shows the step-by-step process in the code.

**Comment by photopea** [comment]
@HiroakiLion Sorry, I am afraid I sitll don't understand :( Could you attach two images here, one of what you have, and another of what you want to get?

Your article contains screenshots of Photoshop and Gimp, but I need actual images to test it myself.

**Comment by HiroakiLion** [comment]
pre_defringe, when zoomed in
https://gyazo.com/6e872927ee675199d8d9a6d388705520

post_defringe, same position same zoom
https://gyazo.com/2569ab61e23b7004717f5ce373304d7b

![heart_pre_defringe](https://user-images.githubusercontent.com/9125397/128628410-95ed7820-a44a-4fc1-bafd-78036224fd55.png)
![heart_post_defringe](https://user-images.githubusercontent.com/9125397/128628411-d9aed8ab-98e1-4550-9519-cb7a3116efcc.png)

**Comment by HiroakiLion** [comment]
pre_defringe loses the color data of edge pixels which has partial alpha

defringing in photoshop adds the color bleeding to the pixels, it recreates the lost color data by comparing 8 surrounding pixels
but depending on your system, the grey edges are not visible, due to the reading of data or rendering process different from some other viewer, in Unity, where I use the byte[] data to load this pre_defringe image file, it shows the grey edge line when loaded as texture, but post_defringe has color information embedded properly in each pixel (RGBA), so latter shows fine without grey edges, making smooth gradient transition to the background.

**Comment by photopea** [comment]
We have added a new feature: Layer - Defringe (at the end of a list of options).

Does it work as you expect?

**Comment by yaustar** [comment]
@photopea Late to this, I'm trying it now with an image and it doesn't seem to be doing anything unless I'm using it wrong?

**Comment by photopea** [comment]
Could you try the same thing in Photoshop? It should work similarly.

**Comment by yaustar** [comment]
Ah, I'm afraid I don't use Photoshop 😅 Just GIMP or Photopea

**Comment by photopea** [comment]
We have Layer - Defringe. I still dont know  understand what it does, but it should work the same as in Adobe Photoshop.

If you think it works differently than in Photoshop, please, provide a proof.
