### ISSUE TITLE
Ad not displaying triggering dialogue popup

### ISSUE THREAD

**Issue by aborriello** [photopea/photopea#2668]
Ad not displaying triggering dialogue popup the prevents students from using Photopea. Happing for 2 of my students currently. Did restarts and checked for extensions that could be blocking ad and had no success. Not sure what else to try.

**Comment by photopea** [comment]
Can you try to disable all the extensions?

**Comment by aborriello** [comment]
Tried that. One student had no extensions anyway.

**Comment by photopea** [comment]
That is really strange. Do they have an antivirus program, which could be blocking some web domains?

**Comment by aborriello** [comment]
I will check with them but I'm not sure. I didn't realize this
initially but the students are siblings, meaning they are on the same
internet connection. Could it be that the ISP is blocking the ad? If so how
would they even go about fixing that?

**Comment by photopea** [comment]
I think the internet provider should not decide what you can or can not visit (censor internet for you). Try the antivirus, or their router at home could be blocking websites, too.

**Comment by photopea** [comment]
BTW. are they in China or Iran?

**Comment by aborriello** [comment]
No, USA. Ok I will ask them to reset their router. Maybe that will help.

**Comment by photopea** [comment]
We allowed our users to use Photopea with adblockers for now. But we will ban it again in the future, so please, try to figure out how you are blocking ads. 

Also, do not let other people get to your computer and install software, which could be blocking ads, without you knowing about it.
