### ISSUE TITLE
Popup is asking for adblock to be turned off, despite adblock being turned off, making using Photopea difficult.

### ISSUE THREAD

**Issue by toolazytothinkofausername** [photopea/photopea#2669]
Using uBlock Origin and Google Chrome.

**Comment by photopea** [comment]
Try to disable all browser extensions.

**Comment by pebblecray999** [comment]
this is not working. all extensions are removed, and the pop up claims i have ads turned off. this is a bug.

**Comment by photopea** [comment]
We allowed our users to use adblockers for now. But we will enable it again in the future, so please, try to figure out how you are blocking ads. 

Also, do not let other people get to your computer and install software, which could be blocking ads, without you knowing about it.
