### ISSUE TITLE
Photopea Layer Not Editable

### ISSUE THREAD

**Issue by arandomo** [photopea/photopea#2671]
**Photopea Layer Not Editable Error**

Whenever I try to crop a part of an image it says "Layer not editable." How do I fix it?

**Comment by MichalSZZ** [comment]
Do you use a crop tool?
Or want to delete a part of the image by selecting it?
Is your layer a "smart object"? Look on bottom right corner of layer thumbnail. If there is a little rectangle, you can't delete part of that layer.

**Comment by photopea** [comment]
I have to close it because of lack of details.
