### ISSUE TITLE
Cannot open THIS PDF

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2672]
I cannot open this pdf :/
[cannot open.pdf](https://github.com/photopea/photopea/files/5649200/cannot.open.pdf)

**Comment by photopea** [comment]
Hi, your PDF seems to be corrupted somehow.

There is a reference to an object 3562, which should be at Byte 18356169, but there is no such object at that byte.

What was the last program you modified your PDF with?

**Comment by avagp** [comment]
It was sent to me by my provider.

I can guess it is corel draw or AI.

Those are the only ones that they use.

**Comment by photopea** [comment]
Adobe Illustrator can open any PDF file (even those not made with Illustrator). Adobe Illustrator crashed, when I tried to open your PDF in it.

Most of PDF viewers "evolved" over the years, to accept lots of incorrect or damaged PDF files. However, editors like Illustrator or Photopea require the file to be undamaged.

Ask your provider to "fix" the file - make it openable at least in Adobe Illustrator.
