### ISSUE TITLE
show vector as "vector"

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#2673]
hi  :)
when I open a vector file photope open it as a raster image,  when I zoom in on it it goes Pixley.

the shape : 
![Screenshot (55) (1)](https://user-images.githubusercontent.com/70863817/101291453-81e80c80-3811-11eb-9459-1665b341608f.png)

when I zoom in : 
![Screenshot (55)](https://user-images.githubusercontent.com/70863817/101291449-7ac0fe80-3811-11eb-84e5-f200cb0c5375.png)
.
.
.
some times it goes difficult to design a vector when it's actually not a vector, so can you make photopea show the vector shapes like this : 

zoomed in : 
![Screenshot (55) (2)](https://user-images.githubusercontent.com/70863817/101291508-fe7aeb00-3811-11eb-8fc8-7e0dde84cf45.png)

**Comment by mustafaGFX** [comment]
is it possible ....?

**Comment by photopea** [comment]
We could make a custom renderer, which would render the document in such way.

But, the raster images (e.g. photos) would still be pixelated after zooming.

Also, we would not render Layer Styles, as they are pixel-based. You would need to add a vector stroke to the shape, rather than a Stroke Layer Style.

This feature would make Photopea different than e.g. Adobe Photoshop, and it would confuse many people.

**Comment by MichalSZZ** [comment]
In Illustrator user can view how his design will looks like as an artwork made from pixels.
It is an option hided in menu "View" -> "pixel preview". 
Maybe in Photopea by default should to be pixel preview, but when user want to work only on vectors (I like it very much), he can switch to "vector preview" in menu "view"?
What are you think about that?

Here how does it work in Illustrator https://m.youtube.com/watch?v=yjZLdUkzT-4

**Comment by photopea** [comment]
Layer Styles, Adjustment layers and many other things are impossible to render at "vector preview". On the other hand, smooth vector shapes are impossible to preview at "pixel preview".

Would it be confusing, if after switching to Vector preview, layer styles disappear, and the document would look completely different? When making vector graphics, users would be confused, that layer styles "do nothing".

Also, how should we render vector shapes with raster masks, after you zoom in?

**Comment by mustafaGFX** [comment]
@photopea 
I understand all that you say, all I need is to render **shapes** as a vector, 
you can give the users the choice between ( shapes vector preview - shapes pixel preview )

you also can let the other types of layers on its current status, you will just edit the shapes preview not all layers.
what do you think about that, is my words make any sense or it can't be real?

**Comment by mustafaGFX** [comment]
> Also, how should we render vector shapes with raster masks, after you zoom in

that is a good point
I think vector shapes can't be rendered with a raster mask, but I have a solution which can solve this problem : 
if the user turns on the '**shapes vector preview**' he just can't use the raster mask with shapes, if he tries to do, photopea will say that shapes cant be with the raster mask in shapes vector preview

if the user makes a raster mask to the shapes before turns on the '**shapes vector preview**', photoopea will say that all raster mask will be disabled until you return to the default preview ( raster preview )

does it make any sense ??

**Comment by mustafaGFX** [comment]
what do you think ..?

**Comment by mustafaGFX** [comment]
can you answer me, please!

**Comment by photopea** [comment]
I am really very skeptical about it. I think it would be better to make a separate, independent program.

Also, when you zoom in, there is a blue contour of vector shapes, even though the fill is pixellized.

**Comment by mustafaGFX** [comment]
okay thank you
