### ISSUE TITLE
error on script - ActionList()

### ISSUE THREAD

**Issue by alex-gross** [photopea/photopea#2675]
var list1 = new ActionList();

Uncaught new ActionList
dj.eval @ pp.js:7572
dj.hr @ pp.js:7601
dj.eval @ pp.js:7567
dj.eval @ pp.js:7567
dj.eval @ pp.js:7565
dj.e2 @ pp.js:7562
hC.oF @ pp.js:10987
hA.B @ pp.js:9
hF.B @ pp.js:7783
hF.B @ pp.js:7783
hF.B @ pp.js:7783
cM.yL @ pp.js:9376
hA.B @ pp.js:9
hF.B @ pp.js:7783
gm.Aw @ pp.js:7941

**Comment by photopea** [comment]
Hi, could you write a short script for Adobe Photoshop, which uses ActionList and performs some simple task, so that I can use it for testing?

**Comment by alex-gross** [comment]
For adjust Layer

```
var HUE_SAT_ADJUSTMENT_V2_SYM  = 'Hst2';
var COLORIZE_SYM               = 'Clrz';
var ADJUSTMENT_SYM             = 'Adjs';
var HUE_SYM                    = 'H   ';
var SATURATION_SYM             = 'Strt';
var LIGHTNESS_SYM              = 'Lght';
var HUE_SATURATION_SYM         = 'HStr';
var colorizeDescriptor = new ActionDescriptor();
var hueSatDescriptor = new ActionDescriptor();
var hueSatAdjustmentList = new ActionList();
colorizeDescriptor.putBoolean( charIDToTypeID( COLORIZE_SYM ), true );
hueSatDescriptor.putInteger( charIDToTypeID( HUE_SYM ), 100 );
hueSatDescriptor.putInteger( charIDToTypeID( SATURATION_SYM ), 42 );
hueSatDescriptor.putInteger( charIDToTypeID( LIGHTNESS_SYM ), -51 );
hueSatAdjustmentList.putObject( charIDToTypeID( HUE_SAT_ADJUSTMENT_V2_SYM ), hueSatDescriptor );
colorizeDescriptor.putList( charIDToTypeID( ADJUSTMENT_SYM ), hueSatAdjustmentList );
executeAction(charIDToTypeID( HUE_SATURATION_SYM ), colorizeDescriptor, DialogModes.NO);

```

**Comment by photopea** [comment]
I fixed the problem, it should work well now.

**Comment by alex-gross** [comment]
No error more, but alert "layer is not editable"

`activeLayer = activeDocument.layers.getByName('hue');
activeLayer.visible = true;
var HUE_SAT_ADJUSTMENT_V2_SYM  = 'Hst2';
var COLORIZE_SYM               = 'Clrz';
var ADJUSTMENT_SYM             = 'Adjs';
var HUE_SYM                    = 'H   ';
var SATURATION_SYM             = 'Strt';
var LIGHTNESS_SYM              = 'Lght';
var HUE_SATURATION_SYM         = 'HStr';
var colorizeDescriptor = new ActionDescriptor();
var hueSatDescriptor = new ActionDescriptor();
var hueSatAdjustmentList = new ActionList();
colorizeDescriptor.putBoolean( charIDToTypeID( COLORIZE_SYM ), true );
hueSatDescriptor.putInteger( charIDToTypeID( HUE_SYM ), 56 );
hueSatDescriptor.putInteger( charIDToTypeID( SATURATION_SYM ), 81 );
hueSatDescriptor.putInteger( charIDToTypeID( LIGHTNESS_SYM ), 15 );
hueSatAdjustmentList.putObject( charIDToTypeID( HUE_SAT_ADJUSTMENT_V2_SYM ), hueSatDescriptor );
colorizeDescriptor.putList( charIDToTypeID( ADJUSTMENT_SYM ), hueSatAdjustmentList );
executeAction(
    charIDToTypeID( HUE_SATURATION_SYM ),
    colorizeDescriptor,
    DialogModes.NO
);

[test_hue.zip](https://github.com/photopea/photopea/files/5657302/test_hue.zip)
`
