### ISSUE TITLE
pop up interrupting work 

### ISSUE THREAD

**Issue by pebblecray999** [photopea/photopea#2678]
i've turned off all extensiosn and removed ad blocker entirely, and the pop up claims i am blocking ads. please fix now.

**Comment by photopea** [comment]
Hi, can you try Photopea in Incognito window? Does it work there?

**Comment by baggachipz** [comment]
I have the same issue. Running it in a Private Window (Firefox) does indeed stop the nag message. Still don't see any ads though, which I won't complain about.

**Comment by photopea** [comment]
I think your browser (Firefox) blocks ads in Private mode, too. Try to disable it in Firefox settings somehow.

Or try another browser, which does not do anything to websites.

**Comment by baggachipz** [comment]
I definitely disable my ad blocker (uBlock Origin) for the entire site: https://ibb.co/w6P6G8L

**Comment by baggachipz** [comment]
Ah, it's the "enhanced tracking protection" feature. Guess Google Ads errors out with that protection on, which as you state is a core feature of Firefox.

**Comment by photopea** [comment]
I guess it has been fixed.
