### ISSUE TITLE
Missing metadata?

### ISSUE THREAD

**Issue by zemko85** [photopea/photopea#2681]
Hi all,

This is a recent development, which I can't trace to anything I have changed in my set-up, so filing it as a bug. It may well be an issue on my end, in which case I apologise. I should preface this by saying Photopea is amazing and thank you for making it.

As of a few days ago, Photopea can't seem to read metadata out of my OOC jpg files. I shoot with a Nikon D750 and edit photos on a Chromebook (hence the use of Photopea). When saving, I always click on save metadata, but when I was done editing a few days ago, I noticed no metadata was saved in the final pictures. So I went back and discovered that any jpg straight out of the camera only has pixel Y and pixel X dimensions visible under File Info, nothing else. This is the same for older files I edited over the last few months (when it worked flawlessly). Bizarrely, if I open a Photopea-edited jpg file from a few weeks ago, File Info shows all metadata no problem, since Photopea saved it nicely back then, so the issue is only with jpg files straight out of the camera regardless of when I shot it.  

I have tried incognito mode, different devices and browsers with the same result.

Any help and suggestions appreciated.

M.

**Comment by photopea** [comment]
Hi, we update Photopea several times a day.

Could you show me a file, which is supposed to have metadata, but you can not see them? Or describe steps, how can I make Photopea remove metadata?

**Comment by zemko85** [comment]
Thanks for the speedy response. Never used GitHub before, so hopefully this works. Here's a picture which, if I open it in Photopea and click on File Info, has nothing there (apart from the pixel dimensions). A few weeks ago it would have a full slate of metadata there.

![_DSC9332](https://user-images.githubusercontent.com/75725283/101613411-a3a8e580-3a03-11eb-8625-129d2ef980e7.JPG)

**Comment by photopea** [comment]
I fixed the problem.

Note, that your file contains three images (there are three layers, when you open it in Photopea). Photopea will always display the metadata of the first image.

**Comment by zemko85** [comment]
That is speedy work, I'm very impressed. Thank you very much.
