### ISSUE TITLE
Saving files end up as .txt extension  

### ISSUE THREAD

**Issue by Roxgame95** [photopea/photopea#2685]
Saving files end up as .txt extension  i  have to rename the files every time i save

**Comment by photopea** [comment]
Hi, you have a browser extension, which renames files. Try to find and disable that extension, or disable all extensions.

If you don't know how extensions work, use Photopea in Incognito mode. I am sure your files will be saved correctly in it.

**Comment by Roxgame95** [comment]
it works thank you <3
