### ISSUE TITLE
Exporting as txt instead of jpg,pdf etc

### ISSUE THREAD

**Issue by gitSambhal** [photopea/photopea#2686]
When I do export from File -> Export as -> JPG (or any other), the exported file extension is coming as txt instead of JPG or PDF.

**Comment by photopea** [comment]
Hi, we solved it many times.

https://github.com/photopea/photopea/issues/2685

https://github.com/photopea/photopea/issues/2679

https://github.com/photopea/photopea/issues/2667

https://github.com/photopea/photopea/issues/2663
