### ISSUE TITLE
Customize Keyboard Shortcuts?

### ISSUE THREAD

**Issue by ScottSummers9** [photopea/photopea#2687]
This is essential for my workflow when I used Photoshop.  Thx!

**Comment by photopea** [comment]
Hi, our keyboard shortcuts correspond to default shortcuts in Adobe Photoshop and other prorams. We do not have an option to change them.

Also, web browsers prevent us from using certain shortcuts (e.g. when you press Ctrl+T, the browser does not tell a website, that Ctrl+T was pressed, and just opens a new browser tab).

**Comment by ScottSummers9** [comment]
1. Many users use a few functions far more than others, so assigning those to hotkeys near each other:
---Speeds up workflow.
---Reduces the need to hunt for a distant key.
---Reduces repetitive stress injury.

2. Users can discover on their own that hotkeys like Ctrl+T are already in use.
---I'm mostly talking about the basic keys: asd, qwe, zxc.

**Comment by photopea** [comment]
Isn't it better, if everyone uses the same keyboard shortcuts? Which shortcuts exactly would you like to change and to what?

**Comment by ScottSummers9** [comment]
**Like a video game:**
For years in Photoshop, I've been leaving my left hand centered on ASD. 
  1. That allows the user to reach up to QWE and 123, or down to ZXC.
  2. I set these to the functions I use the most.
  3. I periodically modify them to fine-tune my workflow --**which can change over time**!
------------------------------------------------------------------------
**My setup:** 
> A: Pencil/brush
> S: Eraser
> D: Default: White & Black
> 
> Q: Move 
> W: Select,
> 
> Z: Swap Colors
> X: Pen
> Alt: Eyedropper, 
> Spacebar: Hand tool 

It seems far less efficient to move my left hand to the other side of the keyboard and start pressing keys to try to find the I or P.
