### ISSUE TITLE
Layer Style not showing up

### ISSUE THREAD

**Issue by MeiliTT** [photopea/photopea#2688]
I'm trying to add a drop shadow to my text but it's not showing up at all. It always has in the past and I'm not sure why it would suddenly not work.

Photopea also opened in its own window, which it hasn't done in a while which makes me wonder if there was an update or something. Anyway, I really need the Layer Style to work so I hope you can get this fixed.

Thank you for this fantastic program.

**Comment by photopea** [comment]
Hi, I just tried to add a drop shadow and it works.

Can you update your web browser and disable all browser extensions?

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by MeiliTT** [comment]
Sorry, forgot to update. I discovered that for some reason the white wasn't
working on the drop shadow but the black was.

**Comment by photopea** [comment]
I think that is because you use a "Multiply" blend mode for your drop shadow. Switch to another blend mode.

The white color is number 1, and if you multiply any number by 1, it will not change that number.

**Comment by MeiliTT** [comment]
Oh, gotcha. Thanks so much.
