### ISSUE TITLE
Color Overlay

### ISSUE THREAD

**Issue by ceodaryl** [photopea/photopea#2689]
When i go and try to change the color of my boarder. The drop box for colors are empty.

**Comment by photopea** [comment]
Hi, could you describe, what should I do, to see the problem myself? What boarder and the drop box are you talking about?

**Comment by primemb** [comment]
same here
![image](https://user-images.githubusercontent.com/3611284/102048903-2d3a2800-3df5-11eb-8160-a46e4567d76a.png)

**Comment by photopea** [comment]
@primemb That is a drop box for layer styles, you do not have any saved layer styles.

To change the color of the Color Overlay, click on the "Color Overlay" and all the options will be in the middle.

Read this: https://www.photopea.com/learn/layer-styles  Or buy a book about Adobe Photoshop to learn it.
