### ISSUE TITLE
move tool does not move selected layer

### ISSUE THREAD

**Issue by SebiTimeWaster** [photopea/photopea#2693]
steps to reproduce:
- create layers with varying image data
- select a specific layer
- move it with the move tool
another layer is moved that had a non-transparent pixel on the mouse position

**Comment by photopea** [comment]
Hi, I think you have "Auto-select" enabled at the top bar. Disable it and it should not auto-select layers.

**Comment by SebiTimeWaster** [comment]
hm... is that the standard setting?

**Comment by photopea** [comment]
Yes, it is enabled, if you start Photopea for the first time.
