### ISSUE TITLE
Cant upload file from computer

### ISSUE THREAD

**Issue by rahulsain** [photopea/photopea#2694]
![image](https://user-images.githubusercontent.com/50570677/102094823-c8102200-3e48-11eb-8185-c36cf2c5300b.png)

**Comment by rahulsain** [comment]
It was .pdf file which I combined pages from 3 pdf's from online

**Comment by photopea** [comment]
Can you please send your file to support@photopea.com ?

**Comment by rahulsain** [comment]
@photopea Sure, but I used another software to do the work which I was planning to do in Photo pea

**Comment by rahulsain** [comment]
It was 40MB file, maybe thats a problem

**Comment by photopea** [comment]
Photopea converts every file into a PSD before opening it. And the PDF can become 20x larger when converted to PSD. It is hard to tell, until I see the PDF myself.

**Comment by rahulsain** [comment]
Ok, Sending the file

**Comment by rahulsain** [comment]
@photopea If you could help me, only that file is not opening. Need to do some work on it

**Comment by rahulsain** [comment]
This is the link of the file: https://drive.google.com/file/d/1K057MIABflfNQcmuiIkLy4d1sbJtGdbX/view?usp=sharing

**Comment by photopea** [comment]
Hi, thanks for sharing, I fixed the problem.

However, you still need plenty of RAM to open your PDF in Photopea. But it worked in my case.
