### ISSUE TITLE
Alt key doesn't work when using Pen

### ISSUE THREAD

**Issue by tlsmj** [photopea/photopea#2695]
Alt key doesn't work when using Pen to cut image line

**Comment by photopea** [comment]
Hi, could you tell us more? What is "image line" and how do you cut it?

Are you using Firefox or a Chromebook, or MS Edge from 2015? The Alt key does not work there at all.

**Comment by tlsmj** [comment]
> Hi, could you tell us more? What is "image line" and how do you cut it?
> 
> Are you using Firefox or a Chromebook, or MS Edge from 2015? The Alt key does not work there at all.

First, sorry about my bad grammar.

I meant this.

When I make curve with using pen tool, 2 white dot appear with 1 blue line.

I hold "Alt key" and press blue dot in the middle
then 1 white dot disappear.

But from today "Alt Key" doesn't work.

I use pen tool so many time and this system always worked great.

So, I can't cut image with curve.

Thank you for read.

**Comment by photopea** [comment]
I think I fixed the problem. Does it work better now?

**Comment by tlsmj** [comment]
Problem solved.

Thank you so much!
