### ISSUE TITLE
Добавление, и исправление

### ISSUE THREAD

**Issue by redmin22882** [photopea/photopea#2696]
Мне крайне не хватает такой функции как деформация она мне необходима для моих проектов. 

Но а также мне крайне необходима функция быстрое выделение. Она не работает и это крайне удручает. 

Когда хочешь воспользоваться ею то весь Фотошоп становится нерабочем. 

Крайне прошу вас добавить и исправить

**Comment by photopea** [comment]
Hi, what deformation do you have in mind? Could you show us the link of how such feature loogs in any other program?

Also, what is wrong with the quick selection? What device are you using it on? is it powerful enough?

Our software is called Photopea, not Photoshop.

**Comment by redmin22882** [comment]
> Привет, какую деформацию ты имеешь в виду? Не могли бы вы показать нам ссылку на то, как такая функция работает в любой другой программе?
> 
> Кроме того, что плохого в быстром выборе? На каком устройстве вы его используете? достаточно ли он силен?
> 
> Наше программное обеспечение называется Photopea, а не Photoshop.

Про деформацию... https://m.youtube.com/watch?v=ScfU1CtwZ8w&t=479s


А про быстрое выделение : когда его используешь то ничего не выделяется так и после остальные функции не работают. "Не одна из функций" приближении. Кисть. Ласо. ( Да и всё остальное после этого быстрого выделения) 

А про моё устройство : Хуавей. 32 гига памяти. ОЗУ 3. 

И да я понимаю что это другое приложении но никто не станет отрицать что вы хотите сделать подобие версии ПК. Я просто хочу исправление и добавление как и все мы тут надеюсь

**Comment by redmin22882** [comment]
Эм я крайне извиняюсь но почему мой ответ удалился?

**Comment by spooknik** [comment]
Hello, maybe you can try puppet warp? (Looks like this in Russian)

![image](https://user-images.githubusercontent.com/40317809/102330613-0eb96580-3f8a-11eb-8449-09fc1277afcb.png)

It's not exactly the same as photoshop, but it will do what you want 👍

**Comment by photopea** [comment]
I believe we have the Warp tool, similar to Adobe Photoshop. Look here: https://www.photopea.com/learn/free-transform - there is an example with a cup.

I just tried the Quick Select tool and it works well.  Are you using it on a phone? How much RAM do you have and what is the resolution of your image?

**Comment by redmin22882** [comment]
> Здравствуйте, может быть, вы можете попробовать кукольный варп? (Выглядит так по-русски)
> 
> ![изображение](https://user-images.githubusercontent.com/40317809/102330613-0eb96580-3f8a-11eb-8449-09fc1277afcb.png)
> 
> Это не совсем то же самое, что видео, но оно будет делать то, что вы хотите 👍

Я всё понимаю но эта функция у меня не совсем стабильно работает

**Comment by redmin22882** [comment]
> Я думаю, что у нас есть инструмент Warp, похожий на Adobe Photoshop. Посмотрите сюда: https://www.photopea.com/learn/free-transform - есть пример с чашкой.
> 
> Я только что попробовал инструмент быстрого выбора, и он хорошо работает. Вы используете его на телефоне? Сколько у вас оперативной памяти и каково разрешение вашего изображения?

Оперативной 32 гигабайта. И у меня планшет Хуавей

**Comment by spooknik** [comment]
Sorry, I told you the wrong tool. You want the 'warp' tool like @photopea said. This one is what they use in the vidoe. 

![image](https://user-images.githubusercontent.com/40317809/102335219-e7659700-3f8f-11eb-94f5-4173910fcbe6.png)

**Comment by redmin22882** [comment]
> Извини, я сказал тебе не тот инструмент. Вам нужен инструмент "деформация", как сказал @photopea. Это то, что они используют в видое.
> 
> ![изображение](https://user-images.githubusercontent.com/40317809/102335219-e7659700-3f8f-11eb-94f5-4173910fcbe6.png)

Ну а сейчас я хочу извиниться. Это у вас есть

**Comment by redmin22882** [comment]
> Я думаю, что у нас есть инструмент Warp, похожий на Adobe Photoshop. Посмотрите сюда: https://www.photopea.com/learn/free-transform - есть пример с чашкой.
> 
> Я только что попробовал инструмент быстрого выбора, и он хорошо работает. Вы используете его на телефоне? Сколько у вас оперативной памяти и каково разрешение вашего изображения?

![Uploading Screenshot_20201216-152704.png…]()

**Comment by redmin22882** [comment]
![Screenshot_20201216-152704](https://user-images.githubusercontent.com/74855608/102336763-6ddfa000-3fb3-11eb-9242-930ad7183d57.png)

**Comment by photopea** [comment]
I changed the russian translation, I changed Warp from "Перекос"  to "Деформация".

**Comment by redmin22882** [comment]
> Я изменил русский перевод, Я изменил варп с "Перекос" на "деформация".

Благодарю. 

Но почему-то у меня эта функция крайне лагает и просто не могу это использовать. 

И я уже показал скрин моего устройства. Может она слишком слабое

**Comment by photopea** [comment]
I think your device is slow, while your photo is large.

Try to make your image smaller (Image - Image Size). E.g. 2 millions pixels (2 megapixels) instead of 20 megapixels. It will be faster then.

**Comment by redmin22882** [comment]
> Я думаю, что ваше устройство работает медленно, в то время как Ваша фотография большая.
> 
> Попробуйте сделать свое изображение меньше (Image-Image Size), например, 2 миллиона пикселей (2 мегапикселя) вместо 20 мегапикселей. Тогда это будет быстрее.

Ну хорошо я завтра попытаюсь и надеюсь поможет всё-таки

**Comment by redmin22882** [comment]
> Я думаю, что ваше устройство работает медленно, в то время как Ваша фотография большая.
> 
> Попробуйте сделать свое изображение меньше (Image-Image Size), например, 2 миллиона пикселей (2 мегапикселя) вместо 20 мегапикселей. Тогда это будет быстрее.

Простите но а как это сделать? Я просто смотрел и не могу понять как это сделать

**Comment by photopea** [comment]
It is described here: https://www.photopea.com/learn/image-size

Or find some tutorials for Adobe Photoshop in Russian (Photopea works the same).

**Comment by redmin22882** [comment]
> Это описано здесь: https://www.photopea.com/learn/image-size
> 
> Или найдите несколько учебников для Adobe Photoshop на русском языке (Photopea работает так же).

Благодарю
