### ISSUE TITLE
Copy not working

### ISSUE THREAD

**Issue by WeedEater1** [photopea/photopea#2697]
The copy function does not work even though I have allowed clipboard access the paste function did work for a while but that stopped working too

**Comment by photopea** [comment]
Hi, can you disable all browser extensions? Does it work then?

**Comment by WeedEater1** [comment]
No

**Comment by WeedEater1** [comment]
It doesn't work on any browser, everything is on the latest version

**Comment by photopea** [comment]
I just tried and it works for me.

Can you tell me, what operating system and what browser are you using? And how do you copy? Can you send me a screenshot of your extensions list, as a  proof that they are disabled?

**Comment by dentistformyeye** [comment]
@WeedEater1 Are you making selections before you copy? You can press ctrl-A ctrl-C to copy an entire raster layer.

**Comment by WeedEater1** [comment]
I didn't select the images properly
