### ISSUE TITLE
Won't allow to upload a photo to edit 

### ISSUE THREAD

**Issue by nataliasaenz01** [photopea/photopea#2699]
I have tried several times to upload photos to edit for my film class, and every time it says file "Unknown" with a series of numbers after. I have tried everything to change this and nothing has helped

**Comment by photopea** [comment]
Can you try to update your browser and disable all browser extensions? Your extensions could be modifying the files, before Photopea receives them.

**Comment by photopea** [comment]
I have to close it because of the lack of details.
