### ISSUE TITLE
Ability to change Text of a layer via Script

### ISSUE THREAD

**Issue by puddinman94** [photopea/photopea#270]
It would be great if you could expose the ability to change a Text layers content via scripting. Doesn't seem to be supported right now.

From the docs(http://wwwimages.adobe.com/www.adobe.com/content/dam/Adobe/en/products/photoshop/pdfs/cs6/Photoshop-CS6-JavaScript-Ref.pdf), you should be able to set the text via:

`myLayers[i].textItem.contents = "Layer in " + textArray[i] + " Set Inside "+ textArray[i] ;`

**Comment by photopea** [comment]
It was implemented. Thanks for pointing it out!
