### ISSUE TITLE
Support for 16 bit/32 bit HDR image editing

### ISSUE THREAD

**Issue by superluffa-kei** [photopea/photopea#2700]
Hi,

Photoopea largely replaces my Photoshop workflow—thanks for that.
In my case, the only area that it cannot compete with Photoshop is editing floating point precision image AKA 16/32 bit images. Is it under development or do I have a chance to see this feature in the future(within months, etc)?

Thank you.

**Comment by photopea** [comment]
Hi, we do not have such plans at the moment. Have you tried to work with regular 8 bit images in your case? Are you sure the quality is not sufficient?

Also, where will you display your images? Most of computers, phones and TVs have 8 bit colors.

**Comment by superluffa-kei** [comment]
Hi, 

Thank you for the response. Unfortunately, only the 16/32 bit image works in my case, as this image is directly used as a HDR lighting source in the 3d software. In this case, the captured image is also already in the HDR range (like those from "HDRI Haven"), so the 8 bit image is not a feasible option. I believe the Photopea is a strong alternative to the Photoshop, but currently I cannot find an alternative to the Photoshop when handling HDR images.  

I've heard that some artists also prefer the 32 bit image to modify the photo in a specific way effectively. For example, [this video](https://www.youtube.com/watch?v=Fnua6gM7bUk&ab_channel=PiXimperfect) illustrates the benefit of using 32 bit images. I see supporting the floating point image would not be a trivial task. Right now, I might need to subscribe the Photoshop again.

Thank you again for your teams' great effort.

**Comment by photopea** [comment]
Hi, I see. I believe that all effects, that you achieve with 32-bit images in Photoshop, could be achieved in 8-bit images, but in a different way. But I understand, that it can be comfortable to many people to do it this way.

I will close it now, as we do not have enough resources to work on such feature.

**Comment by dentistformyeye** [comment]
[Krita](https://krita.org/) has 32-bit support. It has some image editing features even though it's designed for digital artists. I don't know if it supports your workflow, but it's free and open source, so you could test it out.

**Comment by superluffa-kei** [comment]
> [Krita](https://krita.org/) has 16/32-bit image support. It has some image editing features even though it's designed for digital artists. I don't know if it supports your workflow, but it's free and open source, so you could test it out.

Hi, thank you for the suggestion. I quickly tested the program that you have mentioned.

Unfortunately, when I checked if the program supports HDR format(.hdr extension), it seems that it cannot open the HDR files properly. I'm not sure what other options might be available. Please let me know if anyone has any other alternatives.

**Comment by superluffa-kei** [comment]
> Hi, I see. I believe that all effects, that you achieve with 32-bit images in Photoshop, could be achieved in 8-bit images, but in a different way. But I understand, that it can be comfortable to many people to do it this way.
> 

Thank you for spending some time to think about this feature. You are right — the same HDR effect can be achieved if we have the full control over the shader, engine, etc. For example, by using the alpha channel as the exposure component of the image. In my case, the 3d program/engine is the PlayCanvas/editor and it only supports 32 bit HDR input image to extend the range of lighting—which means I don't have the control over to modify the image. 

> I will close it now, as we do not have enough resources to work on such feature.
>

As an alternative, I'm suggesting a new feature which could be done in the 8 bit image workflow. For example, in the PlayCanvas editor, actually the 32bit image is converted to the RGBE format. And then in the realtime lighting part, although each component of the image is just 8 bit, the HDR effect is possible with the help of the alpha channel which is [exponent](https://en.wikipedia.org/wiki/RGBE_image_format). 

I don't know if it is possible to support this workflow in the Photopea—for example, by providing a way to import 32 bit image and **convert the 16/32 bit image to RGBE format when importing it**. Can we have this feature? In this case, it would be useful to have the ability to see the tone-mapped image in the editor, by using the E channel as the exposure and then applying the tone mapping to convert the output into the 8 bit image again.

**Comment by Romarain** [comment]
> Also, where will you display your images? Most of computers, phones and TVs have 8 bit colors.

I think 16 bits would be more than appreciable, given that is has nothing to do with the final 8-bit image we can save : it has the solely purpose to avoid ugly glitches in color gradients. Fo instance, if you take the BRUSH and put the hardness to 0%, the gradient it will make at the edge of the circular brush will be absolutely infamous. This is because 8-bits is too limited.

It is know since 15 years at least that using 16-bits for workspace is NECESSARY in order to avoid those visual glitches. There's ton of videos on Youtube about it.
