### ISSUE TITLE
Advertisement code slowing down/freezing the interface

### ISSUE THREAD

**Issue by Kuragi-Kriada** [photopea/photopea#2701]
So all you really need to do in order to get this to happen is to attempt any project that takes 5 minutes or longer and the problem will show itself. Not only is this irritating, but it also stacks the longer that you use the software.

**Comment by photopea** [comment]
Hi, can you disable all browser extensions and try it again? You may have a browser extension, which replaces our ads with their own ads, and these ads (which are not ours) slow down your computer.

**Comment by photopea** [comment]
I need to close it because of lack of details.
