### ISSUE TITLE
[Request kind of] Any way to disable those huge font-loaidng popups or put them somewhere else?

### ISSUE THREAD

**Issue by foxnoodles** [photopea/photopea#2703]
I mean those resource loading messages (rounded rectangles) that pop up everytime I open a document. I can't see how are they so important. Is there a way to disable those? 
Maybe put a setting in preference pane or something.
Thanks in advance, keep up the good work

**Comment by photopea** [comment]
Hi, these messages should go away after two seconds. Or they do not go away?

**Comment by foxnoodles** [comment]
They do, but sometimes it's 20-30 of them and I have to wait until they disappear. Plus they are huge. 
what is the main purpose of those messages anyway? why not have them as small notifications at the bottom left of the screen or something.

**Comment by photopea** [comment]
Hi, I fixed the problem. When several fonts are loaded at the similar time, there is just one message about them. Also, the message stays for only 1.5 seconds instead of 2.
