### ISSUE TITLE
Добавление

### ISSUE THREAD

**Issue by redmin22882** [photopea/photopea#2704]
А не планируете ли вы добавить виртуальную мышь? Просто есть подобие клавиатуры для клавишь но и хотелось бы и мышь. Это поможет во многих ситуациях. 

И прошу добавьте режим наложения как: мягкий свет. И экран

**Comment by photopea** [comment]
Hi, what do you mean by a virtual mouse? Do you mean making a right-click on a touchscreen?

We have all blend modes of Adobe Photoshop. See here: https://helpx.adobe.com/ru/photoshop/using/blending-modes.html

**Comment by redmin22882** [comment]
> Привет, что вы подразумеваете под виртуальной мышью? Вы имеете в виду щелчок правой кнопкой мыши на сенсорном экране?
> 
> У нас есть все режимы смешивания Adobe Photoshop. Смотрите здесь: https://helpx.adobe.com/ru/photoshop/using/blending-modes.html

Нет я имею ввиду именно курсор. Так и кистью удобнее работать так и трансформацией лучше можно заниматься

**Comment by photopea** [comment]
What exactly is a virtual cursor? What kind of device do you have?

**Comment by redmin22882** [comment]
Хм вот вам пример того чего хотелось бы 
![IMG_20201220_085355](https://user-images.githubusercontent.com/74855608/102704773-5d744180-42a1-11eb-816d-bdc05ff68d48.png)
![IMG_20201220_085419](https://user-images.githubusercontent.com/74855608/102704774-5ea56e80-42a1-11eb-9641-1d846b3a39b1.png)

**Comment by redmin22882** [comment]
Примерно такой аналог мне пригодится да и всем другим я уверен он не помешал бы. 

И вновь прошу режимы наложения: мягкий свет. И экран

**Comment by photopea** [comment]
So you want a virtual trackpad? How exactly does it work? I have a Windows and Android device, but I do not have Virtual Trackpad. Do you have a video of what should it do?

What is мягкий свет. И экран? How do they look like?

**Comment by redmin22882** [comment]
Вот вам режимы наложения и как работают
![IMG_20201220_175505](https://user-images.githubusercontent.com/74855608/102713975-abaf3200-42ed-11eb-8e87-f6ff57fdd93a.png)
![IMG_20201220_175536](https://user-images.githubusercontent.com/74855608/102713976-ae118c00-42ed-11eb-9f6d-3fbd4a2d4aa2.png)
![IMG_20201220_175558](https://user-images.githubusercontent.com/74855608/102713977-aeaa2280-42ed-11eb-951b-76a952f4d92d.png)

**Comment by redmin22882** [comment]
Ну а вот про курсор который мне да р многим нужен 

Uploading SVID_20201220_180003_1.mp4…

**Comment by photopea** [comment]
I think the blend modes in your Photoshop are translated incorrectly. Here is how they should be translated to Russian:

![6](https://user-images.githubusercontent.com/15955558/102714764-26b61f80-42d1-11eb-92d6-cfe61f85c000.png)

**Comment by redmin22882** [comment]
> Я думаю, что режимы наложения в вашем Photoshop переведены неправильно. Вот как они должны быть переведены на русский язык:
> 
> ![6](https://user-images.githubusercontent.com/15955558/102714764-26b61f80-42d1-11eb-92d6-cfe61f85c000.png)

Это не у меня а просто версия ПК то как должно быть по аналогии и у вас. 

Но и тем не менее вы не ответили про эти режимы

**Comment by redmin22882** [comment]
> Я думаю, что режимы наложения в вашем Photoshop переведены неправильно. Вот как они должны быть переведены на русский язык:
> 
> ![6](https://user-images.githubusercontent.com/15955558/102714764-26b61f80-42d1-11eb-92d6-cfe61f85c000.png)

Это не у меня а просто версия ПК то что по аналогии должно быть и у вас если вы повторяете. 

И я конечно извиняюсь но то что вы сейчас показываете этого у вас нет я только что вновь посмотрел в надежде что увижу то что нужно. 

Так что просто прошу вас это добавить ведь этого пока что нету

**Comment by photopea** [comment]
As I said, we have all blend modes of Adobe Photoshop. I think they are translated incorrectly into Russian in your Photoshop.

I do not see how a virtual trackpad could be useful to anybody, so I am closing it.

**Comment by redmin22882** [comment]
> Как я уже сказал, У нас есть все режимы смешивания Adobe Photoshop. Я думаю, что они неправильно переведены на русский язык в вашем фотошопе.
> 
> Я не вижу, как виртуальный трекпад может быть кому-то полезен, поэтому закрываю его.
> 
> Кроме того, я думаю, тебе следует выучить английский. Я думаю, что многие важные вещи, которые вы сказали Или я сказал, могут быть потеряны при переводе.

Ладно допустим проверю смешивания. 

Но а про курсор... Нет ну серьезно когда нужно вырезать или работать с маской то обязательно нужно видеть куда двигается кисть ведь палец всё будет закрывать. Вы лишь отвечаете ведь и времени у вас не так много но в само дело вы не хотите погружаться ведь думаете что курсор никому не нужен и не подумали для чего это и даже не спросили. 

А про английский... Ну хорошо когда-нибудь

**Comment by photopea** [comment]
Can you connect a mouse to your device? I think there should be Bluetooth Mice for any tablet or phone. I think you can not do a serious work only with a finger.

**Comment by redmin22882** [comment]
> Можете ли вы подключить мышь к своему устройству? Я думаю, что для любого планшета или телефона должны быть Bluetooth-мыши. Я думаю, что нельзя делать серьезную работу только пальцем.

Простите за грубость но если была то вам я не писал бы
