### ISSUE TITLE
Support crypto payments

### ISSUE THREAD

**Issue by pakokrew** [photopea/photopea#2705]
Hey there,
Loving what you do, would really like to buy your product to support, but don't want to go through Paypal. 

Would you guys allow us to pay with cryptocurrencies ?
You can super easily setup it with stuff like  https://www.coinpayments.net/ or https://commerce.coinbase.com/

Cheers

**Comment by photopea** [comment]
Hi, there is a small number of people paying for Photopea, and I think maybe one in a thousand would be willing to pay with cryptocurrency. I think it is not worth it to implement such feature for 1 - 2 crypto payments a year.

You should be able to pay through Paypal with a card, without making a PayPal account.

**Comment by pakokrew** [comment]
> Hi, there is a small number of people paying for Photopea, and I think maybe one in a thousand would be willing to pay with cryptocurrency. I think it is not worth it to implement such feature for 1 - 2 crypto payments a year.
> 
> You should be able to pay through Paypal with a card, without making a PayPal account.

You'd be surprised that people which own cryptocurrencies are more keen to donate :)

Anyway, I understand it may not worth to implement such a system, but at least you can drop a donation address somewhere, I'd send some coins !

**Comment by photopea** [comment]
Thanks :) I feel a bit uncomfortable owning cryptocurrencies, as their value can become 2x bigger, but also 2x lower in a couple of weeks. You can donate by buying yourself a Premium account with regular money :)
