### ISSUE TITLE
Support for RGBE workflow

### ISSUE THREAD

**Issue by superluffa-kei** [photopea/photopea#2706]
Hi,

This feature is related to the previous ticket https://github.com/photopea/photopea/issues/2700

Can we add the support for [RGBE](https://en.wikipedia.org/wiki/RGBE_image_format) import workflow? 
For example, when importing/opening the 16/32 bit image, the Photopea might ask users to open the image as RGBE, making it possible to convert the image to the RGBE channels.

Along with the RGBE importing, it would be also nice if we can have a way to see the 8 bit image by applying the tone-mapping as well. 
For example, the user can mark the 8 bit channel as exponent then this channel work with a possible new adjustment layer called "tone mapping". In this way, we can tweak the RGBE channels and see the HDR effect without actually needing the heavy floating point image format. This can open the door for HDR editing.

Thank you for your team's amazing effort and happy new year soon!

**Comment by photopea** [comment]
Sorry, it feels like it would be too much work, and there is not that many people requesting this feature :(
