### ISSUE TITLE
clipart

### ISSUE THREAD

**Issue by patrickggg** [photopea/photopea#2708]
how do i make clipart in photopea?

**Comment by photopea** [comment]
Hi, I think it should be similar to making any other graphics. Have you learned how to use Photopea? If not, read www.Photopea.com/learn

**Comment by patrickggg** [comment]
yes i have i have and learned how to use photopea before but there is nothing about how to make clipart

**Comment by photopea** [comment]
what is clipart? can you give us an example of what do you want to make? Is it a JPG file?

**Comment by patrickggg** [comment]
[https://drive.google.com/file/d/1J2fBuxcdWmOSy_gvWiwUSFERJuIDwlTO/view?usp=sharing](url)

**Comment by photopea** [comment]
I think that is a photo of a car. You need to use a camera to take a photo, or you can paint it yourself.

**Comment by patrickggg** [comment]
no shit its a car and i want to make it look like this [https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pinclipart.com%2Fmaxpin%2FoxwmRR%2F&psig=AOvVaw2YpyX5KH8ELUaa1i8Zmu0W&ust=1608663706858000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCOiLhsLh3-0CFQAAAAAdAAAAABAE](url)

**Comment by photopea** [comment]
It can not be done automatically with "one click". I think it was drawn by an artist. It can take hours. Can you draw?

I found a video about clipart, you can do the same thing in Photopea: https://www.youtube.com/watch?v=YuVCXn2u8Hk

**Comment by photopea** [comment]
I will close it now.
