### ISSUE TITLE
Sketch: Symbols and instances should be converted to smart objects

### ISSUE THREAD

**Issue by NoRabbit** [photopea/photopea#271]
It's a 18mb sketch file.
I tried Chrome, Firefox and Edge (edge doesn't work at all, the interface is going crazy but it seems to be opening it...)

**Comment by photopea** [comment]
Hi, can you please send us your file to support@photopea.com ?

**Comment by DrKlanes** [comment]
I have exactly the same problem with a 300 KB .sketch, Chrome, Firefox and Edge working with Windows 10.

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by NoRabbit** [comment]
Hi sorry about the lack of news, I just sent you the file that still causes the issue today to support@photopea.com
thx !

**Comment by photopea** [comment]
Your file contains many symbol masters and symbol instances. Photopea puts the whole object multiple times for each symbol instance, so the final PSD has 30 000 layers and requires 6 GB of RAM to load. 

We must use smart objects instead. I will try to fix it soon.

**Comment by photopea** [comment]
Using smart objects is not possible in this case. In Sketch, there can be symbols A and B in the main document, and A can also be placed (nested) inside B. In PSD files, each smart object represents a separate PSD file with its own smart objects, so the A inside B can not be related to A inside the main document.

Working with vector graphics inside PSD simply requires much more RAM, than working with it in a pure vector editor (like Sketch or Illustrator). Please, ask somebody to split your Sketch file into several smaller files.
