### ISSUE TITLE
Remapped Caps Lock to CTRL not working

### ISSUE THREAD

**Issue by firmgently** [photopea/photopea#2712]
Hi I have Caps Lock remapped to CTRL on my keyboard (using X11 on Linux). In Photopea the key doesn't work and I have to use the normal CTRL key for shortcuts (which is awkward as muscle memory makes me use Caps Lock).

I see this problem in one other place on my system (happens when inside a Windows VM). All other software works with the remapped key, it works correctly inside the same browser where I use Photopea.

This problem occurs for me in Firefox and Chromium on Void Linux.

(great software btw, thanks very much)

**Comment by photopea** [comment]
Hi, if Photopea still knows, that you pressed  Caps Lock and not Ctrl, I think you did not really remap it. Could you remap it so that it is actually remapped for all apps? Maybe in BIOS somehow?

**Comment by firmgently** [comment]
Hi I am using a config file in `/etc/X11/xorg.d`, it remaps it for the entire X session (so all GUI apps). This is a standard/common remapping method for Linux.

Eg `xev` gives the following output when I press my remapped key:

```
KeyPress event, serial 34, synthetic NO, window 0x3e00001,
    root 0x1a1, subw 0x0, time 120663315, (38,807), root:(679,809),
    state 0x0, keycode 66 (keysym 0xffe3, Control_L), same_screen YES,
    XKeysymToKeycode returns keycode: 37
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

**Comment by photopea** [comment]
Sorry, I am not familiar with Linux, so I dont understand your tools.

I think I have fixed it. Could you try it again?

**Comment by firmgently** [comment]
You have fixed it :)

Fantastic response, thanks so much.

**Comment by photopea** [comment]
you are welcome :) I just hope I did not break it for someone else.

**Comment by firmgently** [comment]
I hope so too. Well if you have to reverse the change I understand, I'm probably in a very tiny minority so not reasonable to break it for other people.
