### ISSUE TITLE
zooming

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#2713]
I cant zoom in or zoom out in photopea, hope you solve this problem as soon as possible because I can't do anything with this problem

thanks

**Comment by photopea** [comment]
hi, how exactly do you zoom in or out?

**Comment by mustafaGFX** [comment]
with touchpad like I always do

**Comment by mustafaGFX** [comment]
almost all zooming ways don't work

**Comment by mustafaGFX** [comment]
when I try to zoom photopea turn the out select on instead of zooming :


![Screenshot (59) (4)](https://user-images.githubusercontent.com/70863817/102925245-b14a7a80-449b-11eb-83ac-071c0ae07927.gif)

**Comment by photopea** [comment]
I modified the behaviour of the Control key today. Do you think your touchpad could perform the Control key down?

What about using Alt+mouse wheel? Or the Zoom tool?

**Comment by mustafaGFX** [comment]
> What about using Alt+mouse wheel? Or the Zoom tool?

they do work but I am not used to using them, I don't use the mouse at all, all I use is the touchpad

**Comment by mustafaGFX** [comment]
> Do you think your touchpad could perform the Control key down?

I have no idea

**Comment by photopea** [comment]
You said "almost all zooming ways don't work", but it turns out only the touchpad does not work.

I just tried to zoom with a touchpad in Windows and on a Macbook, and they both work. Can you update your web browser and disable all browser extensions? What OS and a browser do you use?

**Comment by mustafaGFX** [comment]
I use google chrome
and I haven't added any new browser extensions or use different browsers, This problem occurred without any introductions

BTW, I have just discovered that when I add a new text the problem becomes resolved, but when I save this text and select any other tool the problem comes back :(

**Comment by photopea** [comment]
Could you try Photopea in Incognito mode?

**Comment by photopea** [comment]
Also, what operating system do you use?

**Comment by mustafaGFX** [comment]
> Could you try Photopea in Incognito mode?

I have just tried and it still not working
.
.
.
.

> Also, what operating system do you use?

window 10

**Comment by photopea** [comment]
I have the latest Chrome on Windows 10 and my trackpad works well. That is really strange.

Let's wait if anyone else reports the same problem.

**Comment by mustafaGFX** [comment]
the same problem is in the Microsoft Edge browser

**Comment by mustafaGFX** [comment]
> BTW, I have just discovered that when I add a new text the problem becomes resolved, but when I save this text and select any other tool the problem comes back :(

can you Conclude anything from that..?

**Comment by photopea** [comment]
Can you go to http://jsfiddle.net/p45f44zb/14/ , click into the white area and try to zoom in with a trackpad? Does it print anything?

**Comment by mustafaGFX** [comment]
here I can zoom ( **while editing some text** )

![screenshot](https://i.imgur.com/Zxvbawt.png)
.
.
.
.
but here I can't ( **when I'm not using the keyboard anymore** )

![Screenshot (62) (1)](https://user-images.githubusercontent.com/70863817/102933243-99c6be00-44aa-11eb-82b4-5882330538dc.png)

**Comment by photopea** [comment]
Can you go to http://jsfiddle.net/p45f44zb/14/ , click into the white area and try to zoom in with a trackpad? Does it print anything?

**Comment by mustafaGFX** [comment]
I record a video but I can't send it, it says that's a big file

**Comment by mustafaGFX** [comment]
zooming with the trackpad
https://user-images.githubusercontent.com/70863817/102935375-b107aa80-44ae-11eb-8612-6f9273172d53.mp4

**Comment by photopea** [comment]
I think I fixed it, does it work now?

**Comment by mustafaGFX** [comment]
you are the smartest man I have ever know Ivan :)
It works now and that is so amazing

thank you very much :)

**Comment by photopea** [comment]
It is still wrong, that our computers behave differently, even though we have the same OS and the same browser.

**Comment by mustafaGFX** [comment]
maybe the model or the Gear of the computers are the reason
