### ISSUE TITLE
Copying doesn't work

### ISSUE THREAD

**Issue by shenchan** [photopea/photopea#2714]
I've tried using ctrl+c and going to edit>copy but neither work. I know it isn't my computer's problem since copying works fine on other things (i.e. google docs, discord, file explorer, etc.).

**Comment by photopea** [comment]
Have you made a selection before copying? Or what are you trying to copy?

**Comment by shenchan** [comment]
Yes, I've made a selection beforehand. I'm trying to copy a shape onto a different layer.

**Comment by photopea** [comment]
Are you using a Chrome browser? Did you allow a clipboard access? Could you try it in the Incognito mode?

**Comment by shenchan** [comment]
Yes, I'm using a chrome browser. I allowed clipboard access and tried it in incognito mode yet it still doesn't work.

**Comment by photopea** [comment]
Could you maybe record a short video of how you copy a part of a layer in Incognito mode?

**Comment by mustafaGFX** [comment]
>  I'm trying to copy a shape onto a different layer.

I think vector shapes cannot be cut

**Comment by photopea** [comment]
You can not copy paths with a selection. Copy-pasting paths pastes paths into the same vector shape (or vector mask). Read this: https://www.photopea.com/learn/vg-structure  . It works the same as in Photoshop, so you can look for resources about Photoshop.
