### ISSUE TITLE
Add PSD template?

### ISSUE THREAD

**Issue by nathgit** [photopea/photopea#2715]
How do I add a PSD template? I did the publish online as PSD option, but how do I find the url to add it as a template?

**Comment by photopea** [comment]
When you publish a PSD in Photopea, it should open the file in a new browser window, under a URL such as this one: https://www.photopea.com/#i_Rc7hdfx

**Comment by nathgit** [comment]
Thanks. It opened in a browser window before, but I closed it not realizing I had to copy & paste the link. I thought maybe it would show up for me to select when adding it as a template, as most services would do.
