### ISSUE TITLE
Add "preserve transparency" when in the filling option

### ISSUE THREAD

**Issue by superluffa-kei** [photopea/photopea#2716]
Hi,

When filling the image, sometimes we want to only fill the area where there is a pixel—in other words without changing the opacity of an image. This "preserve transparency" option is available in the Photoshop. Can we have this feature?

**Comment by dentistformyeye** [comment]
Workarounds you could use for now:

If each pixel in your image is either transparent or opaque (or if you don't mind applying the fill to partially opaque pixels):
1. Make a new layer above the image you want to fill.
2. Apply the fill to the new layer.
3. Create a clipping mask (Layer > Clipping Mask or press ctrl-alt-G).
![image](https://user-images.githubusercontent.com/51429646/103160333-a6e0f700-47a1-11eb-9bad-579d58ad6883.png)


If you want to make sure only the completely opaque pixels are affected:
1. Make a new layer above the image you want to fill.
2. Apply the fill to the new layer.
3. Click back to the image you want to affect and choose Layer > Raster Mask > From Transparency.
4. Apply a threshold adjustment to the raster mask (Image > Adjustments > Threshold). Set the value to 255.
5. Alt-click_and_hold the raster mask and drag it to the fill layer to copy. Delete the original raster mask.
![image](https://user-images.githubusercontent.com/51429646/103160362-18b94080-47a2-11eb-94eb-be338f44ae24.png)

**Comment by dentistformyeye** [comment]
Oh, actually, there is a way that only requires your original image. If you don't mind affecting partially opaque pixels, this is probably all you need.
1. Make sure the layer you want to change is in focus. Click this symbol in the Layers panel to lock transparency
![image](https://user-images.githubusercontent.com/51429646/103160427-ee1bb780-47a2-11eb-9cee-725033842b33.png)
2. Apply the fill to the layer.
![image](https://user-images.githubusercontent.com/51429646/103160437-228f7380-47a3-11eb-86b4-5a0a87c0b014.png)

**Comment by photopea** [comment]
Hi, I added the "preserve transparency" option into the Fill window.
