### ISSUE TITLE
Edited photos and went to log in to create an account before exporting them

### ISSUE THREAD

**Issue by Jaydeburgos** [photopea/photopea#2718]
Go back to original page and it crashed. Hit F5 and all of it was gone. I spent 2 hours on my photos.

**Comment by photopea** [comment]
Hi, you should not close Photopea if you have not saved your work. Is that what you did?

**Comment by photopea** [comment]
Photopea always shows you message, when you are trying to close (or reload) it, with unsaved work.

Should I disable F5 in Photopea? Even if you press it now, you should still see a message about the unsaved work. If you cancel it, the browser should not reload a website (and your work will still be in front of you).

**Comment by Jaydeburgos** [comment]
No. I opened a new tab to create an account and it crashed.

**Comment by photopea** [comment]
I think your browser could be closing Photopea, because there is not enough RAM memory. How much RAM do you have? Also, could you update your web browser? It could be more stable in a new browser.
