### ISSUE TITLE
Fonts should be loaded every single time.

### ISSUE THREAD

**Issue by lethalgrace** [photopea/photopea#2719]
All the fonts that i want to use should be loaded every single time i want to use it. if i close photopea, i should reload the whole fonts again to use it. it gets quite annoying to wait for the fonts to load up. my friends dont have this issue. please fix it.

**Comment by photopea** [comment]
Hi, I think you use a browser extension, which clears the website data after you close a website. Or maybe your browser is clearing the website data.

Browsers never clear website data by default. So you either installed an extension, or changed the browser settings, to prevent Photopea from storing fonts in your computer.

Could you find that extension and disable it? If not, try to disable all your browser extensions. Let me know if it helped.

**Comment by photopea** [comment]
I hope it has been fixed by disabling certain extensions, so I will close it.

**Comment by lethalgrace** [comment]
i disabled all the browser extensions but still the problem persists.

**Comment by photopea** [comment]
Are you asked about storing a font into a local storage, so that you do not have to load it next time? Do you confirm it or you press "cancel"?

**Comment by lethalgrace** [comment]
i want to store the font into photopea so i dont have to load it every single time. no option comes asking me to store into the local storage or something. but when i load my text styles there comes an option to store it in the local storage and i confirm it. but no option comes when i load the fonts.

**Comment by lethalgrace** [comment]
My text styles load up perfectly when i want to use them but the fonts dont.

**Comment by photopea** [comment]
I just tried to load a TTF font into Photopea and I see this message:
![image](https://user-images.githubusercontent.com/15955558/103270528-6ad3af00-49b8-11eb-918b-a94222f016c6.png)

Do your fonts appear in Photopea at all?

**Comment by lethalgrace** [comment]
i dont get that message.

**Comment by lethalgrace** [comment]
but my font do appear in photopea after i load them.

**Comment by lethalgrace** [comment]
![image](https://user-images.githubusercontent.com/76647938/103271235-1984e900-49d3-11eb-80b9-35e2de579df5.png)
this is what comes

**Comment by photopea** [comment]
Could you open Photopea in incognito mode and load a font into it? Do you see the message?

**Comment by lethalgrace** [comment]
no i dont

**Comment by photopea** [comment]
That is strange. Could you record a short video of how you open an incognito mode window, open Photopea, and load a font into it?

**Comment by lethalgrace** [comment]
https://user-images.githubusercontent.com/76647938/103278830-df711280-49e5-11eb-86c7-7b34923ae489.mp4

**Comment by photopea** [comment]
Oh, I see it now. You did not load a font file, but you loaded a ZIP file with fonts inside it.

You should load font files directly (TTF or OTF files), so that Photopea offers you to store the fonts.

**Comment by lethalgrace** [comment]
I loaded it this time directly as a TTF file. it asked me the message and i confirmed. but when i closed the tab and tried again the font was gone. it wasnt there anymore.

**Comment by lethalgrace** [comment]
it worked well in the incognito mode only. in the normal browser the message also didnt appear.

**Comment by photopea** [comment]
Can you disable all browser extensions and load a TTF file into Photopea in a normal mode? Do you see the message?

**Comment by lethalgrace** [comment]
no the message doesn't come

**Comment by photopea** [comment]
Are you sure you are loading TTF and not ZIP? Could you maybe record a video of opening Photopea and loading a font?

**Comment by lethalgrace** [comment]
https://user-images.githubusercontent.com/76647938/103287379-d25f1e00-49fb-11eb-8056-20c50c189c25.mp4

**Comment by photopea** [comment]
Did you load anything into Photopea before loading your font? Photopea asks about storing to a Local Storage just once (and then, it uses your previous answer).

**Comment by lethalgrace** [comment]
when i used the incognito mode photopea asked me. but when i tried in the normal browser it didnt come.

**Comment by photopea** [comment]
Can you record a video, where you demonstrate, that you disabled all extensions (chrome://extensions) ? Then, open www.Photopea.com and load a font into it.

In your last video, Photopea was already opened. Maybe you did something before loading a font.

**Comment by lethalgrace** [comment]
https://user-images.githubusercontent.com/76647938/103297955-cb8fd580-4a12-11eb-9d53-00c6e5dd1e3a.mp4

**Comment by photopea** [comment]
I believe you now, but I still can not explain why it does not show a message :( When I do the same steps in the latest Chrome or Firefox, it shows me a message.

**Comment by lethalgrace** [comment]
is there anything i can do to fix this?

**Comment by photopea** [comment]
I have no idea. Is it Google Chrome? Can you update it or reinstall it? Or reset the settings to default?

**Comment by lethalgrace** [comment]
i tried using microsoft edge and it worked partly. some fonts loaded the next time but the others didnt.

**Comment by photopea** [comment]
You can see your stored fonts in Edit - Local Storage. There should remain the same items even after you close and open Photopea.

**Comment by lethalgrace** [comment]
tysm. it works now. i changed the settings to default and now all the fonts get loaded. thank you.
