### ISSUE TITLE
I can't see the layer thumbnail

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#2720]
when the canvas is quite wide or tall, it becomes difficult to see the layer thumbnail, specially when the layers aren't named or colored, some times it goes annoying to get a very long time to just select a layer !!

![Screenshot (65)](https://user-images.githubusercontent.com/70863817/103178005-dc601000-4887-11eb-99bb-ea1216b7519a.png)

can you please put a fixed ratio to the thumbnail like the other programs like adobe photoshop?
I think that can solve this issue.

**Comment by mustafaGFX** [comment]
also, when the thumbnail of a smart object is too wide, I can't open it at all, because I cant double click on it !!!

**Comment by mustafaGFX** [comment]
and I can't open the blending options by double click..... and many problems happen because of this issue

**Comment by photopea** [comment]
Hi, how would you like the thumbnail to look like in this case?

**Comment by mustafaGFX** [comment]
I think if you put a fixed ratio to the thumbnail will be better, at least to be able to double click it

**Comment by photopea** [comment]
So we should stretch the thumbnail into a square? But it would look weird I think.  https://i.imgur.com/hno7bIG.png

**Comment by mustafaGFX** [comment]
![Screenshot (67)](https://user-images.githubusercontent.com/70863817/103179458-0c61e000-4895-11eb-99e0-4d3b6bec112f.png)

what do think about this ...?

**Comment by mustafaGFX** [comment]
I think we should do this only with the wide of tall layers, which means that we should put a maximum length and maximum width to the layer, if the layer gets taller or wider than this average photopea will make it like the previous image

**Comment by photopea** [comment]
I looked at Photoshop and the thumbnails are also "thin", as in Photopea. I think the aspect ratio of a thumbnail should correspond to the aspect ratio of the document.

**Comment by mustafaGFX** [comment]
yeah
so can you make the thumbnail a little bit bigger, to be easier to double-click on it, like opening the smart objects?

**Comment by mustafaGFX** [comment]
or add "**open smart object**" to the right-click menu

**Comment by photopea** [comment]
I have added a condition, such that thumbnails are at least 6 pixels tall. So if your image is 100x1 pixel, thumbnails will still be 6 pixels tall.

You can open smart objects with Layer - Smart Object - Open.
