### ISSUE TITLE
Export layer sketch file with 2x/3x/4x selected null pointer

### ISSUE THREAD

**Issue by ymebrugts** [photopea/photopea#2721]
Hi,

I'd like to start with saying this web-app is amazing. It saved me a bunch of times over the past few years. 

I've encountered a bug. Exporting a layer of a sketch file with anything other than 1x selected does not work. 

![image](https://user-images.githubusercontent.com/36673314/103203424-2cc18700-48f5-11eb-89a2-67d8e62ee780.png)
![image](https://user-images.githubusercontent.com/36673314/103203484-4f53a000-48f5-11eb-860d-ff4124089506.png)

Greetings,
Yme

**Comment by photopea** [comment]
Hi, I opened "milk.sketch" (in the main menu of Photopea) and renamed two layers to make them start with "-e-". Exporting at 1x, 2x, 3x, 4x worked well.

Could you give us more details? Maybe send us your Sketch file to support@photopea.com and tell us, which layers should we export.

**Comment by ymebrugts** [comment]
Hi,

I send an email with the sketch file for you to debug. I already got the files in another way. 

Greetings,
Yme

**Comment by photopea** [comment]
Hi, I fixed the problem, it should work well now. Thanks for reporting it!
