### ISSUE TITLE
Tools disappearing/not visible

### ISSUE THREAD

**Issue by Just-Another-Black-Sheep** [photopea/photopea#2722]
So, I think around 4-5 days ago Photopea started looking like this for me (special attention to the tools)

![IMG_20201228_202422_779](https://user-images.githubusercontent.com/73115403/103239267-4b536c80-494d-11eb-8566-ca74c3df1b16.jpg)

And this is how it used to look before (the image is an older screenshot I have)

![IMG_20201228_202442_327](https://user-images.githubusercontent.com/73115403/103239286-59a18880-494d-11eb-8700-541cef882dac.jpg)

At first I didn't think too much about this but then I noticed that some tools were missing, like the eraser tool and the keyboard

![PicsArt_12-28-08 32 07](https://user-images.githubusercontent.com/73115403/103239300-645c1d80-494d-11eb-8ff6-7f26580f114d.jpg)

Here's another catch; I took a screenrecord and found that while Photopea is still loading, just for a second, the other tools are visible but once it loads the tools disappear.
(I'd suggest either slowing down the video or pressing play/pause in order to see the exact moment of change, it's on 0:03 - 0:04)

https://user-images.githubusercontent.com/73115403/103239322-72aa3980-494d-11eb-903d-9ee1465b5722.mp4

All of this is happening on mobile Photopea.

However when I open Photopea in the web browser (Chrome), some tools are visible, like the keyboard (again, tools are visible until Photopea completely loads)

![IMG_20201228_203504_920](https://user-images.githubusercontent.com/73115403/103239344-835aaf80-494d-11eb-9e15-554680a69782.jpg)

And if I choose "deskop site" then all tools are visible.

![Screenshot_20201228-203430](https://user-images.githubusercontent.com/73115403/103239354-8a81bd80-494d-11eb-83f2-94641845ff55.png)

I'm wondering why this is happening and is there a way for me to get Photopea to the old look where I can see and use all tools (like in the second image)?

So far I've tried removing the "app" from my phone and installing it back, updating Chrome, deleting cookies and scanning for viruses but those actions didn't do anything.

Unfortunately, besides my phone, I have no other devices that I can currently use to access Photopea.

**Comment by photopea** [comment]
Hi, in Photopea, there are about 50 tools in Photopea, and we can not display them all in the toolbar.

That is why tools are "grouped" into groups. When a tool button has a tiny arrow at the bottom right corner, there are more tools hidden under that button. Press and hold the button, to see a menu with more tools.

Photopea will show you as many tool buttons it can fit into one column. So you will see more buttons on taller screens (and the buttons will appear and disappear when you resize Photopea window).

If you feel like a tool is missing, it is just "merged" with another button. E.g. in your case, the Eraser tool is probably in a group with the Brush tool.

We did that (showing just one column of tools) to provide more space for the work area with a document. What do you think about it?

**Comment by Just-Another-Black-Sheep** [comment]
Got it, it is indeed merged, I just wasn't aware of this change.

I can definitely see the benefits of this decision regarding a bit of extra space :)

Thank you for the help :))
