### ISSUE TITLE
Free Transform SkewX - SkewY

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2724]
I think that on toolbar for object transformation, there is wrong interpretation for X and Y.

https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/skewX() 

Places are OK (it corresponds to Photoshop H and V) but in Photopea it should to be Y and X.

**Comment by photopea** [comment]
Hi, thanks, I changed it to H and V as in Photoshop.

**Comment by MichalSZZ** [comment]
Ok, thank you.

X and Y wasn't any problem for me (if it will be named as in CSS transform - not switched as it was), but changing it to H and V is good too.
