### ISSUE TITLE
Create new layers from layer styles

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2726]
https://helpx.adobe.com/photoshop/using/layer-effects-styles.html?#convert_a_layer_style_to_image_layers

Sometimes I use this method for example when I have object with shadow. I create 2 shadows as a effect, first shadow is quite sharp and strong, second have less of opacity and is more blurred. When I have one object behind my first (main) object - I clip strong shadow to this object. That more blurred shadow I move as a last layer. It looks more realistic when using this method.

I know that creating all of layer style as a separate layer is hard (even Adobe write information about possibility to strange results of this action), but I think it would be nice to have it in Photopea.

**Comment by photopea** [comment]
I believe we already have it at the same place as Photoshop:  Layer > Layer Style > Create Layers.

**Comment by MichalSZZ** [comment]
Ohh. I always doing that by clicking right mouse button on layer effect in layers palette. 

Can you add it in that place? It can be for example near the "scale style effect".

**Comment by photopea** [comment]
Hi, I understand, I added it to the context menu. It should look similar as in Photoshop.
