### ISSUE TITLE
Toolbar on left won't expand

### ISSUE THREAD

**Issue by drillab** [photopea/photopea#2727]
The toolbar on the left won't expand when I press the expand button. It works on the 2 right bars. I now can't click on AI background remover :(

**Comment by photopea** [comment]
Hi, the toolbar adapts to the size of your screen. Tools are "grouped" together, one button contains multiple tools, you should click and hold a tool button to see tools under it. 

the "expand" button at the top of a toolbar does not do anything

**Comment by photopea** [comment]
I guess we figured it out.

**Comment by drillab** [comment]
Oh ok thank you but I'm sure that the first time I used it I clicked on I
think background remover and then I had the option to use AI background
remover by watching an ad. I can't find this anymore

**Comment by photopea** [comment]
The usage of photopea has never been conditioned by watching ads. Are you sure you were using Photopea?

**Comment by drillab** [comment]
Hmmm maybe not but I thought I was. Does photopea have an AI background
remover?
