### ISSUE TITLE
Menu bar not working untill select a layer

### ISSUE THREAD

**Issue by brhndursun** [photopea/photopea#2728]
Hello,

I can't click menu bar when there is no layer selected. Tried on incognito mode and other browsers, still happening.

Watch gif to reproduce this issue.

![select_issue](https://user-images.githubusercontent.com/8144522/103398180-9091bd00-4b4c-11eb-8d4e-ccd15e6d3531.gif)

**Comment by photopea** [comment]
I am very sorry, it is fixed now.
