### ISSUE TITLE
Perspective Crop closes when corners align in an axis

### ISSUE THREAD

**Issue by KingBarnaby** [photopea/photopea#2729]
I am so sorry if this has already been an issue but I have not found anything similar so I might as well open an issue.

I have tried to use perspective crop but if the corners of the crop thing align up in the x/y axis it just closes immediately as in the square just dissapears and it has been a problem for me at least. Can you fix this issue?

**Comment by photopea** [comment]
Hi, what do you mean by "corners align in an axis"?

**Comment by dentistformyeye** [comment]
### Steps to reproduce (set 1)
1. Draw a rectangle with the perspective crop tool. Optionally, rotate the perspective crop grid exactly 180 degrees in any direction.
2. Drag the upper-left corner until it overlaps the upper-right corner or the lower-left corner. Alternatively, drag the lower-right corner until it overlaps the upper-right corner or the lower-left corner.

### Steps to reproduce (set 2)
1. Draw a rectangle with the perspective crop tool.
2. Rotate the perspective crop grid exactly 90 degrees in any direction.
3. Drag the new upper-right corner until it overlaps the new upper-left corner or the new lower-right corner. Alternatively, drag the new lower-left corner until it overlaps the new upper-left corner or the new lower-right corner.

### Expected result
The perspective crop grid remains usable.

### Actual result
The perspective crop grid disappears.

### Additional notes
For set 1, dragging the upper-right corner or lower-left corner to overlap another corner doesn't make the grid disappear. The same applies with the new upper-left corner or new lower-right corner for set 2.
Rotating or dragging the corners of the perspective grid in ways not specified in the steps listed may prevent the grid from disappearing.

**Comment by photopea** [comment]
Hi, I fixed the issue. The rectangle should not disappear now.

However, keep in mind, that such thing (two corners at the same spot) does not occur in the real world, so it will not produce any meaningful results.
