### ISSUE TITLE
Cannot change size of rotated crop tool rectangle with zero width or height

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2730]
### Steps to reproduce
1. (Make sure that extensions are disabled.) Draw a rectangle with the crop tool. Rotate the crop tool by some angle that is NOT a multiple of 90 degrees.
2. Drag a corner to an adjacent corner so that the crop rectangle becomes a line, not a dot.
![image](https://user-images.githubusercontent.com/51429646/103420037-7911fe80-4b63-11eb-9cf5-bcab34d713ca.png)

3. Attempt to drag any corner or border node.

### Expected result
The crop rectangle changes changes size after step 3. Alternatively, the crop rectangle disappears after step 2.

### Actual result
After step 2, the crop rectangle remains on-screen, but step 3 doesn't change the area, width, or height of the rectangle. The crop rectangle cannot be rotated but can be dragged.

### Additional notes
Regardless of rotation, dragging a corner to another corner when possible makes the crop rectangle disappear, which is an expected result.

**Comment by photopea** [comment]
I would recommend pressing Escape and drawing the rectangle again.

I am afraid if we make Photopea so "stupid-proof", it will become so much bigger. There will be more code related to stupid-proofness, than the code related to more important things.
