### ISSUE TITLE
Question: How does the new ad consent button work?

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2731]
A version of Photopea from a month ago had a green button that, when clicked, showed a menu for changing ad personalization and data selling settings.

The new, grey "Change Ad Consent" button doesn't seem to do anything when I click it. (I've made sure that my extensions have been disabled; ads have been showing up for me.) Is there supposed to be some sort of menu or indication that something has changed after clicking the button?

**Comment by photopea** [comment]
In my case, the button opens a window "Preference Privacy" in the middle of Photopea.

Could you try it in Incognito mode?

**Comment by dentistformyeye** [comment]
I've made sure that my extensions were disabled and tried Incognito mode without success :(

**Comment by photopea** [comment]
That is very strange. Do you see any errors in a web console when you click the button? What web browsers have you tried?

**Comment by dentistformyeye** [comment]
I've been using Brave, but Brave is virtually identical to Chrome when I disable my extensions and Brave's ad blocking settings.
Different things show up depending on what number appears after "Extra parameter Spcn". They appear before I open a project and before I click the "Change Ad Consent" button. Clicking the button doesn't make anything new appear in the console whether or not I have a project open.
![image](https://user-images.githubusercontent.com/51429646/103446599-77256980-4c4f-11eb-970f-4a2f028aa4d2.png)

![image](https://user-images.githubusercontent.com/51429646/103446617-a8059e80-4c4f-11eb-8f3b-9c68bd662f41.png)

![image](https://user-images.githubusercontent.com/51429646/103446630-dd11f100-4c4f-11eb-87a2-3928a9ecdcc5.png)

When I try with extensions and tracking protections disabled in a Firefox private window, Photopea doesn't work. I don't understand what this "Content Security Policy" is, so I don't use Photopea in Firefox.
![image](https://user-images.githubusercontent.com/51429646/103446820-d97f6980-4c51-11eb-856a-c7a4fa6f3ad5.png)

![image](https://user-images.githubusercontent.com/51429646/103446802-ab018e80-4c51-11eb-89f1-bd3244d888ed.png)

![image](https://user-images.githubusercontent.com/51429646/103446811-ba80d780-4c51-11eb-888c-9d55fe6382c0.png)

When I try with extensions and tracking protections disabled in a Safari private window, the "Change Ad Consent" button still doesn't work. Whether or not I click the button, some things pop up if 0 and 2 show up in the console, but no errors appear for 1.
![image](https://user-images.githubusercontent.com/51429646/103446901-bf925680-4c52-11eb-8a2b-bbe116b8d0dc.png)

![image](https://user-images.githubusercontent.com/51429646/103446922-dd5fbb80-4c52-11eb-8740-544efa2fd15f.png)

**Comment by dentistformyeye** [comment]
I just tried with all cookies enabled and Incognito mode in the latest Google Chrome on a Windows device. The "Change Ad Consent" button still does nothing. The "Cross-Origin Read Blocking" yellow error, multiple yellow "Resource interpreted as Document but transferred with MIME type image" errors, and multiple "ERR_NAME_NOT_RESOLVED" (magnetic.t.domdex.com) red errors pop up depending on the number printed in the console regardless of whether I click the "Change Ad Consent" button.

**Comment by photopea** [comment]
Hi, I am not sure Brave with extensions disabled is identical to Chrome. I do not consider Brave to be a correct web browser, as from my experience, you can never be sure if it displays a webpage exactly as the author wanted it to be displayed.

Firefox in Incognito mode blocks many domains by default. You should not expect Firefox to display websites the way authors wanted them to be displayed in Firefox Incognito mode.

I tried Photopea on Windows: The "Change Ad Consent" button works both in Chrome and Firefox.

I tried Photopea on Mac OS: the button works both in Chrome and Safari.

Maybe your internet provider or firewall is blocking some domains. Can you try Photopea on your phone?

**Comment by dentistformyeye** [comment]
I doubt Comcast blocks domains, and I don't have a firewall set up; I'd expect to get unresolved domain name errors if that were the case. Brave and Firefox each have a convenient switch for turning off tracking protections at once.
I'm using an Android 6.0.1 device. I cannot update it any further. Even when I have landscape mode on in a private window in the Brave mobile app, the sidebar that's supposed to contain the ads and the "Change Ad Consent" button is completely cut off, or perhaps not even loaded, because the screen isn't wide enough.

**Comment by photopea** [comment]
Actually, we do not show ads at all at small screens. Can you enable "desktop view" on a phone?

**Comment by dentistformyeye** [comment]
The sidebar doesn't show up for the desktop view either.

**Comment by photopea** [comment]
So when you click the button in Chrome Incognito, does anything new appear in the console, what was not there before?

**Comment by dentistformyeye** [comment]
I don't know how to check the console in mobile. On all of the desktop devices and the browsers I've tried, clicking the button hasn't made anything new appear in the console. Anything that does appear beforehand doesn't seem to have anything to do with the button itself.

**Comment by photopea** [comment]
What part of the world are you located at? Maybe there is no need for consent.

This button is managed by a script from uniconsent.com and we can not change it, but I can report a bug (if I manage to reproduce it).

**Comment by dentistformyeye** [comment]
I'm in the US. Maybe the button only applies for people in the EU?

**Comment by photopea** [comment]
Are you in California? I think that the consent is not required in the US outside California.

**Comment by dentistformyeye** [comment]
I'm not in California. I'm fine with the setting's not showing up for me, but I would appreciate an alert such as "This option only applies to European Union and California residents."

**Comment by mustafaGFX** [comment]
hi

> The new, grey "Change Ad Consent" button doesn't seem to do anything when I click it

me too, the grey button doesn't do anything, and also my friends, we thought that this button might be a coming one, I mean it will work in the future

**Comment by photopea** [comment]
I think I fixed it. You should not see any consent button outside the EU and California.

**Comment by crispybegs** [comment]
i have this same issue out of nowhere after years of using photopea.
I try and open a file and get this..

<img width="626" alt="Screenshot 2023-07-03 at 22 00 06" src="https://github.com/photopea/photopea/assets/129169122/03203939-db7d-4dc8-8d9c-60d74314e264">

But clicking the 'change consent' button does nothing whatsoever..

<img width="122" alt="Screenshot 2023-07-03 at 22 00 44" src="https://github.com/photopea/photopea/assets/129169122/f58a4242-993b-4772-a406-7587ba188bb6">

Also on Mac.. Macbook Pro 10.15.6
My iMac which is also on 10.15.6 lets photopea work just fine.

**Comment by photopea** [comment]
I think Photopea is being modified by some of your browser extensions.

Are you using Google Chrome? Could you click the puzzle piece button at the top right corner of Chrome and send us a screenshot of how many extensions have your permission to modify Photopea?

**Comment by Curioso521** [comment]
https://i.pinimg.com/564x/48/ed/6d/48ed6d732001d8185a2c1124b1aaacf0.jpg

**Comment by photopea** [comment]
@Curioso521 what does it mean?
