### ISSUE TITLE
Path Select tool drop down menu's icon are inversed

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2735]
The icons on this tools are reversed. The white arrow belongs to path select, and the black arrow to the direct select.

**Comment by photopea** [comment]
You say "The white arrow belongs to path select, and the black arrow to the direct select."

But in Adobe Photoshop, it is the other way.

![image (1)](https://user-images.githubusercontent.com/15955558/103834153-f917f700-5082-11eb-965c-85a20dcf8d8b.png)

**Comment by avagp** [comment]
Click one and see the color of the tool

**Comment by photopea** [comment]
Our icons can have only two colors: a transparent color and a non-transparent color. the non-transparent color depends on a current theme. It is white for dark themes and black for the white themes. So I don't really know how to fix it in our case.

**Comment by avagp** [comment]
Yes, it has something to do with themes.

But those icons are not changed when you change the theme, so you get
inconsistent icons on the tool.

Here is a little video:
https://video.drift.com/v/abQeTbErYTl/
<https://video.drift.com/v/abQeTbErYTl/>

**Comment by mustafaGFX** [comment]
I think the photopea team want to present the tool by its shape, not by its color, the reason for this is that the color is variable and the shape is not

**Comment by mustafaGFX** [comment]
I think the icons are inversed, they just take there appropriate for every situation

**Comment by photopea** [comment]
I recommend you to think about it this way: Path Select icon is always "filled", Direct Select icon is "empty inside" - just a contour.

**Comment by avagp** [comment]
I get that about the icons:
Filled one is select
And empty is direct

But it does not correspond after selection.
https://video.drift.com/v/abU7JeHKfZl/

**Comment by photopea** [comment]
@avagp No, "Path select" is "filled", "Direct Select" is "a contour", always.

The color of the icon depends on the background. It is black on the white background and white on the black background.

**Comment by avagp** [comment]
Sorry, but my point is, if the background changes the icon "color"

Why does the icon on the dropdown menu doesn't change with the background
color?

**Comment by avagp** [comment]
![Screenshot 2021-01-18 at 11 54 54](https://user-images.githubusercontent.com/11801254/104930539-09ce4400-5984-11eb-8ce4-f3b217cb775d.png)
![Screenshot 2021-01-18 at 11 54 48](https://user-images.githubusercontent.com/11801254/104930542-0aff7100-5984-11eb-87df-0c627f3cc7a7.png)

**Comment by photopea** [comment]
The context menu is always white, so the icon (and the text on it) is always black, no matter what theme you use.

**Comment by photopea** [comment]
Are't you confused by the Hand tool? It is sometimes black, sometimes white. But it works the same as the Path Select / Direct Select.

**Comment by avagp** [comment]
Yes and no.

The hand tool has the same problem, but because it has different icons i can tell them apart.

**Comment by avagp** [comment]
> The context menu is always white, so the icon (and the text on it) is always black, no matter what theme you use.

That is why it does not change with the theme.

I don't know, but in photoshop is the menu always white as well?
