### ISSUE TITLE
corner radius

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#2737]
I have just discovered this and I am so grateful for you, this was the most needed tool for me
![Capture (1)](https://user-images.githubusercontent.com/70863817/103947687-2e831a00-5141-11eb-9dad-8ec2374c7bd4.png)

but why don't we add The draggable corners like this
![98709495-1b470e80-238b-11eb-82e4-bb60eef2a2e7](https://user-images.githubusercontent.com/70863817/103947963-a05b6380-5141-11eb-8d32-b9d545745b66.gif)

**Comment by photopea** [comment]
It is because such corner properties are not possible to save in a PSD file. So if you save a new PSD with new corners, and open it later, you would not be able to change the corner radius.

**Comment by mustafaGFX** [comment]
so is it possible to add it as a tool, it doesn't matter to save these properties into the PSD, it all about having the ability to edit the corner radius quickly

also, the current way to change the corner radius is not be saved to the PSD too, so it's the same.
do you think it will be better?

**Comment by photopea** [comment]
And which tool should be capable of this? The Move tool or the Path Select tool? Or we need a new Corner tool?

**Comment by MichalSZZ** [comment]
@mustafaGFX  I wrote a post here #2598 to you, about that was implemented yet.

But yes - as I described here #2018 it will be very easy to manipulate corner radius like as in other apliactions (newest Photoshop 2021 have this circle handles for shapes in his live shapes, but Illustrator and Affinity have it for all corners)

Photopea have ability to round all "sharp" corners (Photoshop have not). 
@photopea For all corners you can do this like in illustrator:

- after drawing a shape the circle handlers are showing in the corners (and with the shape tool you can modify it - even by selecting only a part of it with Shift button)
- by using a direct selection tool
- by using a selection tool

In Photoshop 2021 **you can't round (using circle GUI) with "move tool" and with "direct select tool"**. Only that is possible:
- after drawing a shape the circle handlers are showing in the corners (and with the shape tool you can modify it - even by selecting only a part of it with Shift button)
- path selection tool (black arrow)

can that be done like in newest Photoshop 2021?
you can read about that here https://www.photoshopessentials.com/basics/using-the-shape-tools-in-photoshop-cc-2021/  in the middle of that long page

**Comment by MichalSZZ** [comment]
And yes - like @mustafaGFX  i dont want to change corner radius all the time. One change with the handlers will be great too. And then I see that isnt a sharp one point corner and know I can't modify. Illustrator have that ability but I understand you Ivan - PSD format is a problem in this case.

**Comment by mustafaGFX** [comment]
> @photopea And which tool should be capable of this? The Move tool or the Path Select tool? Or we need a new Corner tool?

a new tool will be better because the users usually don't notice the tool improvement as good as adding anew tool, also the will be easier for you **I guess**

My perception of this tool:
![Screenshot (70)](https://user-images.githubusercontent.com/70863817/104061629-a0bb3380-5201-11eb-92fc-33fc783378d2.png)
