### ISSUE TITLE
Program Froze

### ISSUE THREAD

**Issue by Noelynn** [photopea/photopea#2738]
I was doing homework for photo editing, and halfway through the homework,  I clicked filter, then stylize, then oil paint, and it just froze. now I can't do my homework

**Comment by photopea** [comment]
Your computer probably ran out of memory. Save your work regularly as PSD (File - Save as PSD), if you work with large files (tens of millions of pixels) and there is a risk of running out of memory.

You can also buy more RAM memory for your computer, or work with smaller images (Image - Image Size - enter a smaller size).
