### ISSUE TITLE
Dropdown menu not responding

### ISSUE THREAD

**Issue by werohero** [photopea/photopea#2739]
I've been having this problem for a month now. I'm using Google Chrome. The dropdown menu works for me to open a new file, but as soon as I have a file open, none of the dropdown options (File, Edit, Image, Layer, etc).

**Comment by photopea** [comment]
Hi, can you update your web browser? Does it work in Incognito mode?

**Comment by werohero** [comment]
My browser is updated. And no, it doesn't work in incognito mode. Now, when I open the file, it works but as soon as I edit anything or use an action, the dropdown menu stops working.

**Comment by photopea** [comment]
Could you send me your file to support@photopea.com and describe what should I do? I would like to reproduce it on my computer.

**Comment by werohero** [comment]
Sent, with instruction and action used

**Comment by werohero** [comment]
There was an issue with my action which listed a layer that did not exist in this particular gif. So it crashed.
Problem is fixed so now, it will print that a corresponding layer does not exist, and the top menu will still work.
