### ISSUE TITLE
Add the ability to open pdn files

### ISSUE THREAD

**Issue by AirGEL** [photopea/photopea#2740]
It would be nice to be able to open pdn files that friends have sent me.

**Comment by photopea** [comment]
Hi, I added the basic support for .PDN files. Could you try to open your files, and if any filed oes not work, could you send it to support@photopea.com , or share it here? :)

**Comment by photopea** [comment]
I fixed several bugs with PDN import and I am quite confident to say, that 99% of PDN files should work well in Photopea now.
