### ISSUE TITLE
Ctrl (and other modifier keys?) not registered

### ISSUE THREAD

**Issue by Nightfirecat** [photopea/photopea#2744]
I seem to be unable to use any keyboard shortcuts requiring Ctrl, and based on the behavior when pressing any of the standard modifier keys (Ctrl, Shift, Alt) with the selection tool, none of them appear to be working as expected. That said, the modifier keys did seem to be consumed as I couldn't open developer tools via the usual keyboard shortcut (Ctrl + Shift + I) or use other browser functions involving them.

I'm running Firefox 84.0.2 from the snap installation on Debian, and didn't see any console errors clearly indicating an issue. I tested this via Tor Browser as well and experienced the same issue.

**Comment by photopea** [comment]
Hi, that is really strange. I do not have Debian to test it myself.

Open this: http://jsfiddle.net/p45f44zb/14/ and click into the white area, and press some keys. It should display the codes of keys pressed at each moment.

What codes do you see for Ctrl, Shift and Alt?

**Comment by Nightfirecat** [comment]
None of the modifier keys are displayed for that fiddle. If I change it slightly to consider `KeyboardEvent.(ctrl|shift|alt)Key`, it does report Ctrl and Shift working, though not Alt: https://jsfiddle.net/prjex6n8/

**Comment by photopea** [comment]
I recommend you to report it to Firefox, as it looks like a bug in your browser. Do you have any browser extensions? Can you disable them?

**Comment by photopea** [comment]
I think one should never try to "overcome" bugs in web browsers. There is one standard, our job is to make websites that follow the standard, and their job is to make browsers that follow the standard.

**Comment by Nightfirecat** [comment]
Based on [numerous entries](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=ctrl), seems like it's a common bug on many Linux platforms for Firefox

**Comment by photopea** [comment]
Try to install some drivers, or try another borwser :/

**Comment by arovlad** [comment]
@Nightfirecat I know this issue is closed, but keep in mind keyboard shortcuts won't work in Firefox and Tor while `privacy.resistFingerprinting` is set to `true`.

**Comment by photopea** [comment]
@arovlad Photopea can be used without a keyboard, a mouse, or even without a monitor or display, but it can be quite uncomfrotable.
