### ISSUE TITLE
Photopea won't let me type

### ISSUE THREAD

**Issue by galati-34** [photopea/photopea#2745]
I was trying to add text to my project but nothing would appear. The title of the layer would change to whatever I was typing, except it didn't actually show up on the project.

**Comment by photopea** [comment]
I think you are using a browser extension, which prevents websites from rendering vector graphics.

Try to disable your extension. If you do not know which one it is, try to disable all extensions. If you do not know what are extensions, try to install some new web browser (browsers are installed without any extensions).

Let me know if it helped.

**Comment by photopea** [comment]
Hi, I am very sorry, it is fixed now.
