### ISSUE TITLE
after New release ... text field .. double clicking T layer 

### ISSUE THREAD

**Issue by pburel** [photopea/photopea#2748]
Uncaught TypeError: o.a1K is not a function
    dp https://www.photopea.com/code/pp.js:7480
    O4 https://www.photopea.com/code/pp.js:5000
    Cv https://www.photopea.com/code/pp.js:4946
    Qt https://www.photopea.com/code/pp.js:4922
    Qt https://www.photopea.com/code/pp.js:11148
    $ https://www.photopea.com/code/pp.js:9
    $ https://www.photopea.com/code/pp.js:7983
    $ https://www.photopea.com/code/pp.js:7983
    $ https://www.photopea.com/code/pp.js:7983
    $ https://www.photopea.com/code/pp.js:7983
    $ https://www.photopea.com/code/pp.js:7983
    $ https://www.photopea.com/code/pp.js:7983
    anA https://www.photopea.com/code/pp.js:10332
pp.js:7480:3

**Comment by pburel** [comment]
Editing text field ... same error

**Comment by photopea** [comment]
Hi, I am very sorry, it is fixed now.
