### ISSUE TITLE
Text tool not working - still.

### ISSUE THREAD

**Issue by evanstektchr** [photopea/photopea#2749]
Got an email saying the issue with the text tool not working was resolved. It is not.

**Comment by macgavin** [comment]
I also received that issue and email and confirm it is still not working for me. I am hoping it will take some time to update and resolve.

**Comment by foxinthebox10** [comment]
I've got the same problem. Shows what you've typed in the layers section but doesn't display on the document.

**Comment by lonestarsun** [comment]
Same, this is very much not resolved.

**Comment by photopea** [comment]
Try to reload Photopea multiple times. Your browser is probably still showing you the old Photopea from 30 minutes ago. Load a current version of a website.

**Comment by lonestarsun** [comment]
Can confirm that I just refreshed the page a few times and the text tool seems to be working fine now!

**Comment by photopea** [comment]
i am glad it works for you.
