### ISSUE TITLE
It is necessary to move layers between tabs

### ISSUE THREAD

**Issue by splincode** [photopea/photopea#275]
![image](https://user-images.githubusercontent.com/12021443/31320941-e4f7b5de-ac85-11e7-9629-660afc54376b.png)

I wanted to somehow move one picture (layer) to another psd file, but I could not add an additional image (layer) to another tab.

**Comment by photopea** [comment]
Hi Maxim, you are not the first one asking about this :)  It is already here: https://github.com/photopea/photopea/issues/234  so I will close this one. 

BTW. right now, you can right-click selected layers and choose Duplicate Into.

**Comment by splincode** [comment]
So, maybe can also make it functional to drag layers to another tab of another project by using the tool while dragging "Move (V)"?

**Comment by splincode** [comment]
Yes, I see you got the task, thanks

**Comment by photopea** [comment]
It was implemented, you can duplicate now simply by dragging layers to another tab.

**Comment by splincode** [comment]
You are best
