### ISSUE TITLE
Not sure if this is a bug, but you can remove ads without a license

### ISSUE THREAD

**Issue by MooseFlip** [photopea/photopea#2752]
So, you can LITERALLY just remove the ads on Photopea by just changing your 'ad consent'!
Like, why pay for a license when you can do that?
Seriously, Photopea, if you want to make money, don't let us get rid of ads without paying!

**Comment by photopea** [comment]
From what I have heard, it seems like nobody is willing to pay for showing ads to people you know nothing about. There are new mechanisms coming into place soon, so let's hope it will change.

The Premium account not only hides ads, but also, it spreads the workspace.
