### ISSUE TITLE
Puppet Warp tool BUGs

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2754]
There are a few BUGs with Puppet Warp tool that doesn't exist in Photoshop. I don't wanna make lots of issues on Github for that - I will write it here.

1. Try to open this file https://www.photopea.com/#ihNf6R0HC it does not load a layer with curved banana (opened in Photoshop show that layer but with some preview bug - cut a part of it).
2. I can't duplicate and transform a layer with smart object and puppet warp filter add on it - after transformation on layer, it show only a part of it or disapear
3. After changing the image size (image->image size) - layer with puppet warp disappear
4. After duplicate smart layer with puppet warp, try to edit puppet warp. The mesh is in different place than a object on layer

![obraz](https://user-images.githubusercontent.com/38118273/104625380-004b9000-5695-11eb-95bd-727cc80dee76.png)

here is oryginal PSD file [moritz-kindler-j-v3GVQ9lC8-unsplash (1).zip](https://github.com/photopea/photopea/files/5815967/moritz-kindler-j-v3GVQ9lC8-unsplash.1.zip)

**Comment by photopea** [comment]
Hi, I think have fixed some bugs. Could you try to produce a PSD, that is not editable in Photoshop or Photopea again? Your old PSD is somehow strange, could you describe how to create such PSD (if it is still possible now)?

**Comment by MichalSZZ** [comment]
Nothing help to me. I made that file in Photopea only. That is what I made today after your fixes
[banana.zip](https://github.com/photopea/photopea/files/5826640/banana.zip)
https://www.photopea.com/#ixPshmqIV

Steps to reproduce (all what I made to get this - and remember) - in PWA version on Chrome and Win 10.
1. Download this file in a oryginal size: https://unsplash.com/photos/j-v3GVQ9lC8
2. Open from computer in Photopea (don't resize that huge file)
3. Duplicate layer by Ctrl+J
4. Use Object Selection tool to select banana
5. Use polygonal lasso tool to select more precisely (in 3  or 4 places with "add to selection" option)
6. Use Ctrl+Shift+I to invert selection
7. Use backspace key to remove white background
8. Change layer into smart object
9. Duplicate that layer
10. Move one layer
11. Transform second layer with Ctrl+T and rotate a little (photopea will inform about transformation on smart object with filter added)
12. BUGs are on my project.

When I enter into smart object and get the separated from background layer, copy to new project and make same steps on smaller file 1080x1080 - bugs are too on project.

**Comment by photopea** [comment]
I tried your steps and it seems to work well. Did you forget mentioning the Puppet Warp? Where exactly should it be?

**Comment by MichalSZZ** [comment]
Before 8 step there is Ctrl+D (I forgot that)
After 8 step I use Edit and Puppet Wap. Add 7 points and then curve banana moving that points.

**Comment by photopea** [comment]
I think I have fixed the issue. Moving and free transforming a smart object should not break the Puppet Warp transform (smart filter).

Your old PSDs from Photopea will still look wrong, but you should not be able to create such PSDs again.

**Comment by MichalSZZ** [comment]
Yes - now everything works good!
Thank you.

**Comment by photopea** [comment]
Thank you for reporting it all and for your patience, you are awesome :) you are helping thousands of people! :)

**Comment by MichalSZZ** [comment]
@photopea  You're welcome :)
You are helping thousands of people everyday by developing this great software.
And Photopea helps me to teach my students "Photoshop"  :)
Lessons are free for ppl from my company (and other free learning projects for other groups) and I think that without free of charge software that wouldn't be possible.
