### ISSUE TITLE
Layer Styles not loading

### ISSUE THREAD

**Issue by Spinnerlude** [photopea/photopea#2755]
Trying to add a stroke in layer styles. The only layer style loaded is grey with a red outline. No other colour options there. I have rebooted, reset history cookies.

**Comment by photopea** [comment]
Hi, you should click the name of the layer style to see the options. You probably just clicked the checkbox.

It is described here: https://www.photopea.com/learn/layer-styles

**Comment by Spinnerlude** [comment]
No, I have no layer styles available.
![Screenshot 2021-01-14 133720](https://user-images.githubusercontent.com/77458531/104633812-b56a5200-566d-11eb-8137-c8808ef3812b.jpg)

**Comment by photopea** [comment]
You need to load the .ASL file to see styles available in the style gallery. It is described here at the end: https://www.photopea.com/learn/layer-styles
