### ISSUE TITLE
No Layer styles loading

### ISSUE THREAD

**Issue by Spinnerlude** [photopea/photopea#2756]
No layer styles are loading

![Screenshot 2021-01-14 133720](https://user-images.githubusercontent.com/77458531/104636095-d2545480-5670-11eb-9536-6acab7bd37e6.jpg)

**Comment by photopea** [comment]
Hi, have you loaded the .ASL files into Photopea?

**Comment by Spinnerlude** [comment]
where do I get asl files? ive used some that were preloaded on previous projects but they are not there anymore.

**Comment by Spinnerlude** [comment]
I just want simple things, nothing fancy. doesn't photopea have some basic ones in there already?

**Comment by photopea** [comment]
There are plenty of ASL files on the internet. Some of them are 10 - 20 years old. 

e.g. this: https://www.brusheezy.com/brushes/9210-400-photoshop-style-pack

https://psfiles.com/free-photoshop-party-text-styles-asl-psd/

**Comment by Spinnerlude** [comment]
Thank you! This can be closed now.
