### ISSUE TITLE
Stuck on Loading!

### ISSUE THREAD

**Issue by JMPf916** [photopea/photopea#276]
Hi!

I've been trying to upload a picture as a template to edit, but it's stuck and has said "Loading" at the top for a while now. I've reloaded it several times, and it works with other pictures, just not this one. Please help!

Thanks!

Here's the picture if you need it:
![bannerbase](https://user-images.githubusercontent.com/32689491/31414557-83c2df7e-adec-11e7-8c4a-8774db2300ed.png)

**Comment by photopea** [comment]
Hi, this was a really curious bug! It happened for any image (PNG, JPG, PSD ...), where width is more than 30 times bigger than height.

It is fixed now. Thanks for reporting it :)
