### ISSUE TITLE
Multiple Canvas / Pages

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2760]
When i open a PDF normally it creates folders named "page x" corresponding to each page of the document.

I was wondering if there is already a solution for multi canvas or may I ask for one :)

Many of my works correspond to a printable document like a diptych and i have been creating 2 PSD files for each face of the paper.

Would be fenomenal to have multiple pages within one PSD.

So my work lives in one file.

Cheers!

**Comment by photopea** [comment]
That corresponds to a tool for making new artboards, reported here :) https://github.com/photopea/photopea/issues/964
