### ISSUE TITLE
Delius Unicase Font types above the textbox

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2761]
This seems super particular, but this font begins typing above the textbox.

So when i am trying to align vertically, it goes above the limits.

![Screenshot 2021-01-15 at 01 13 23](https://user-images.githubusercontent.com/11801254/104680787-77057f00-56cf-11eb-9716-7e28e7847b1d.png)

As you can see the textbox begins just to the left of the S, on the little square.

**Comment by photopea** [comment]
Hi, I fixed it, thanks for reporting :)
