### ISSUE TITLE
Ultrawide monitors and anything other than 16:9 has blank space

### ISSUE THREAD

**Issue by itsLazR** [photopea/photopea#2762]
Any other ratio/resolution that is not 16:9 has blank space as filler. Should fill up the entire screen horizontally 

![image](https://user-images.githubusercontent.com/31200591/104698292-bf746b00-56d6-11eb-9d21-c5bd2b4cb41a.png)

**Comment by MichalSZZ** [comment]
You probably have something like adblock added to your browser (or firewall/antivirus on your computer). 
It block banners on the right side that should to be in the empty space. That is the only income for the Photopea creator - don't block banners (you should turn off adblock for this specific domain) or buy premium account if you don't like advertisements.

**Comment by photopea** [comment]
There should be advertisement located at that spot. Please, do not block our ads, as it is the only way we make money.
