### ISSUE TITLE
Invert layer mask button (raster)

### ISSUE THREAD

**Issue by infinityiowastaken** [photopea/photopea#2764]
Not sure how difficult it would be to implement but it is a useful feature to have available

**Comment by photopea** [comment]
Hi, how do you invert a raster mask in other programs? How do you want it to work?

In Photopea or Photoshop, you can press Image - Adjustments - Invert, to invert a mask.

**Comment by MichalSZZ** [comment]
1. Ctrl + I on qick mask mode - OK for me
2. Ctrl + I on raster mast added to layer - OK
3. Menu Image - adjustments - invert - OK
4. Properties panel - tab mask - there isn't Invert button (like in Photoshop). Maybe that is what he searching in Photopea?

**Comment by infinityiowastaken** [comment]
You are correct, 4 is what I was searching for, although I ended up using Ctrl+I it threw me for a second

**Comment by photopea** [comment]
Hi, I added the Invert button into that panel :)
