### ISSUE TITLE
Angle modyfication for pattern fill

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2765]
In new Photoshop CC we have possibility to change angle on pattern (finally).
Is it possible to have that parameter in Photopea too?

![obraz](https://user-images.githubusercontent.com/38118273/104734852-2595d800-5741-11eb-85f2-d6902fa82d58.png)

**Comment by photopea** [comment]
Hi, could you please share a PSD with us, which contains a rotated pattern?

**Comment by MichalSZZ** [comment]
Hi, it is more complicated as I was thinking it would to be. I added a ZIP file with old and new one with angle rotated for the pattern.
[2-types-of-patterns-in-ps-cc-2020.zip](https://github.com/photopea/photopea/files/5849249/2-types-of-patterns-in-ps-cc-2020.zip)

Photoshop CC 2020 haven't old patterns in his pattern window. They changed working method or patterns somehow and old one are not working well with angle transform.
https://community.adobe.com/t5/photoshop/default-patterns-that-install-with-photoshop-2020/td-p/10722822?page=1 here is where user should to search for old patterns.

**Comment by photopea** [comment]
I have implemented it.

**Comment by MichalSZZ** [comment]
Wow. Thank you. I have to test it.

BTW. Now i should to create task for a new features in shapes that we have talking about on reddit and via mail.

**Comment by nothingshiru** [comment]
It does not seem to work. Nothing changed while changing the angle.

**Comment by photopea** [comment]
@nothingshiru what exactly do you do? The angle of the pattern should change. It works when I try it.

**Comment by photopea** [comment]
Oh, there is a bug, it does not work for pattern fill layers, only for pattern fill layer stlye :/ i will fix it.

**Comment by MichalSZZ** [comment]
> 
> 
> Oh, there is a bug, it does not work for pattern fill layers, only for pattern fill layer stlye :/ i will fix it.

I saw that too.

Next thing that is miss: angle in pattern fill in shape layer.

**Comment by photopea** [comment]
It should all be fixed now, thanks for reporting! :)
