### ISSUE TITLE
Photopea produced corrupt PSD file

### ISSUE THREAD

**Issue by ExplosiveKrypton** [photopea/photopea#2766]
I believe the trigger for this has something to do with attempting to access a smart object. I went to edit a smart object that was in my PSD file and everything starting bugging out. More specifically...

- The canvas and sidebars display the last tab you clicked.
- Trying to click on history and any layers does nothing.
- Folders (and the layers inside of them) will stop displaying on the canvas properly.
- Produces a corrupt PSD when attempting to save (Not sure about images since I can't recreate the bug)

Fortunately, I happened to have a backup of the files I was working on, so I didn't lose very much progress on my work. I also still have the corrupt PSD file in case you want to take a look at it.

**Comment by photopea** [comment]
Hi, can you send us the corrupted PSD to support@photopea.com ?

**Comment by photopea** [comment]
Hi, thanks for sharing your file.

I was afraid, that it was related to the changes which I made today. But your file does not work in Photopea from four days ago, either.

When I open your PSD in Adobe Photoshop, I see an error, something about corrupted groups. Do you think you could reproduce it? I.e. describe, how to create a PSD in Photopea, which causes an error in Photoshop?

**Comment by ExplosiveKrypton** [comment]
I tried again to reproduce it again, but couldn't. I was playing around with clipping masks, the darken filter, and smart objects when I first ran into the bug. The glitch started when I attempted to edit the bottom-most smart object. (Inside of the folder.)

**Comment by photopea** [comment]
I will close it for now. Please, let us know, if you find a way to reproduce it.
