### ISSUE TITLE
Text Sizing bug (?)

### ISSUE THREAD

**Issue by zezinho1718** [photopea/photopea#2767]
Yesterday, I was using photopea and the text was working fine. Today, the text is too small, and it's on the default setting (25 px i think). It doesn't even show for me.

**Comment by photopea** [comment]
Hi, what do you mean? Could you attach a screenshot? Can you make the text size larger?

**Comment by mustafaGFX** [comment]
me too
the text is shown at some sizes and isn't shown at some other sizes

so I have to convert the text to a shape when it's shown to be able to resize it, I have been suffering from this problem for about 7 days now

**Comment by photopea** [comment]
Hi, could you describe how can I make it happen in Photopea?

**Comment by mustafaGFX** [comment]
@photopea 

> could you describe how can I make it happen in Photopea?

- open any PSD file with a large size (let's say 2000*2000 px )
- try to type anything with any font and then try to resize this text
- when you try to resize the text you will notice that the text is shown in some sizes and isn't shown in some other

the same problem happens in the vector shape stroke and this problem has been around for about 2 weeks now and a lot of people have reported it

please find the problem and fix it

**Comment by mustafaGFX** [comment]
@photopea 

> could you describe how can I make it happen in Photopea?

- open any PSD file with a large size (let's say 2000*2000 px )
- try to type anything with any font and then try to resize this text
- when you try to resize the text you will notice that the text is shown in some sizes and isn't shown in some other

the same problem happens in the vector shape stroke and this problem has been around for about 2 weeks now and a lot of people have reported it

please find the problem and fix it

**Comment by photopea** [comment]
Hi, I went to www.Photopea.com and created a new document 2000x2000 pixels. I created a new text layer and typed "Hello World". Then, I highlighted the text and increased the size. But everything worked well :(

Can you maybe record a video of what exactly you do?

**Comment by photopea** [comment]
@mustafaGFX Do you have any news?

I modified the text rendering about 2 weeks ago, so there could really be an issue. However, I still can not reproduce it, no matter what I do :(

**Comment by photopea** [comment]
I will close it now.
