### ISSUE TITLE
Error in Save PSD/PSB

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2768]
1. Open photopea
2. Open pea.psd
3. Click File - Save PSD/PSB...
4. Click Save "pea.psd" button
5. Click PSB button
6. Error appears (see screenshot) and I am unable to save as PSB
![image](https://user-images.githubusercontent.com/6370548/104808976-0dc65e80-57ea-11eb-8e01-461a7449307a.png)

**Comment by photopea** [comment]
Fixed, thanks! :)
