### ISSUE TITLE
Error in Smart Filters

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2769]
1. Open photopea
2. Open pea.psd
3. Go to "background" layer
4. Convert it to smart object with right click and "Convert to Smart Object"
5. Apply some filter with for example Filter - Blur - Blur More
6. Doble click the small gear icon next to Filter in Layers window
7. Error appears as seen on screenshot
![image](https://user-images.githubusercontent.com/6370548/104809403-4a478980-57ed-11eb-9f61-001edb99ac13.png)

**Comment by photopea** [comment]
I fixed it, thanks! :)
