### ISSUE TITLE
Saving & Exporting work only results in a .txt file 

### ISSUE THREAD

**Issue by GitGudEliot** [photopea/photopea#2770]
Whether I save or export my work through the browser version and the app client, any work will be saved as TITLE.txt.

Starting a new project, exporting in a existing .psd or even opening a regular image file to work on i have found no way to properly save anything will become a TITLE.txt then TITLE (1).txt and so forth.

**_Note that "TITLE" is just a stand-in for the actual filename, everything is properly named_**

**Comment by photopea** [comment]
Hi, you have a browser extension, which renames the files into TXT. Try to find that extension and disable it, or ask the creators of that extension not to rename files to TXT.

You can try Photopea in Incognito mode (i.e. without extensions) to see, that the files will be saved correctly.
