### ISSUE TITLE
I can't download the app

### ISSUE THREAD

**Issue by AngyCake** [photopea/photopea#2771]
I don't know why i can't download this app,I have never used it or downloaded it again.The download ''button" is not bold.By the way I am from Greece (I beacause I don't know if it's not supported in my region).

**Comment by photopea** [comment]
Hi, what Download button are you talking about?  The More - Install button works only in Chrome at the moment.

**Comment by photopea** [comment]
Check here to see if it is already installed in your Chrome browser: chrome://apps/

**Comment by photopea** [comment]
I will close it for now.
