### ISSUE TITLE
Screen goes blank after Save Smart Object

### ISSUE THREAD

**Issue by rw1234** [photopea/photopea#2772]
This issue has been going on for several weeks now.  I use Photopea primarily for creating mockups using PSD templates with smart layers.  Recently, there is a bug where, after I select "Save Smart Object", the screen will flicker for a second (go completely black) and then when the screen reappears, Photopea's working areas are completely blank, even though the file is still open. I have to close the file and open it again.  It will work fine for 3-4 times, then the flickering happens again and I have to restart. This happens regardless of which file I am using.  I don't see a way to submit a screenshot here, but I am happy to provide one if needed.
I am using a laptop with Windows 10 home edition, and using Chrome 87.0.4280.141 as the web browser, no plugins.

**Comment by photopea** [comment]
Hi, no matter what I try, I can not reproduce such behaviour :(

Could you maybe record a short video of what exactly do you do?

**Comment by rw1234** [comment]
I have recorded a video of the event. How do I share it here so you can see it?

**Comment by photopea** [comment]
You can put it on Youtube (or somewhere else) and share a link. Or you can send it to support@photopea.com , or attach here on Github somehow.

**Comment by rw1234** [comment]
I have sent a dropbox link to support@photopea.com

**Comment by photopea** [comment]
After watching the video, the main PSD document is over 100 MB. The user adds multiple images (as smart objects) into another smart object, and the history of both documents is tracked. It seems like the browser runs out of RAM.

Try not to have too many steps in History, when working with large documents (100-500 MB), if you do not have plenty of RAM.
