### ISSUE TITLE
On IPad the photopea.com font doesn’t show for most fonts 

### ISSUE THREAD

**Issue by ipad-cuz-cant-afford-pc** [photopea/photopea#2775]
![736C1836-59BC-4A4D-92BB-7F179112E141](https://user-images.githubusercontent.com/77628782/104931181-80d4fe00-59bf-11eb-87ff-67ea0590cb9a.png)

**Comment by ipad-cuz-cant-afford-pc** [comment]
@photopea

**Comment by ipad-cuz-cant-afford-pc** [comment]
@photopea pls reply for a fix

**Comment by photopea** [comment]
Hi, I do not see a font "Etnocentric" in Photopea. Did you load this font manually from your iPad?

What if you type with other fonts, like Open Sans?

**Comment by mustafaGFX** [comment]
this problem has been in photopea for a while in all devices not just on iPad

**Comment by photopea** [comment]
I have to close it because of lack of details.
