### ISSUE TITLE
Quick  selection tool doesn't work  properly

### ISSUE THREAD

**Issue by Peter-Mfitumukiza** [photopea/photopea#2776]
When I try to select a small part it selects the whole image

**Comment by photopea** [comment]
Hi, you have to combine both Add and Subtract options of the Quick Select.  Watch this to learn how to use Quick Selection: https://www.youtube.com/watch?v=zuHwDGlrWSs

I know, that our tool does not work as well as in Photoshop, but I do not know how to make it better :(

**Comment by jeancallisti** [comment]
Same problem; I've been using the same tool in Photoshop for years, but in Photopea it always only selects the entire image, or almost all of it. As if there was a selection threshold setting set way too high.

See video:


https://user-images.githubusercontent.com/1881493/194819301-500e1fc5-e5f2-4c0a-8a1c-919bcbdd175a.mp4
