### ISSUE TITLE
Export Layers with the size of canvas

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2779]
This is a feature request.

I would like to have an option where i can export all layers with the size of the canvas.

![Screenshot 2021-01-20 at 21 33 37](https://user-images.githubusercontent.com/11801254/105257747-2f677300-5b67-11eb-8def-ecf8933d500b.png)

**Comment by photopea** [comment]
Hi, you willl get it if you disable "Trim transparent parts" :)

**Comment by avagp** [comment]
Thanks!!

:P
