### ISSUE TITLE
Premium account

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#278]
I recommend these steps:

- [x] add `remove ads` link to top of sidebar with ad => which open modal window about login, premium membership
- [ ] add recurrent payment option (by default checked)

**Comment by photopea** [comment]
* Remove Ads link is already at the bottom, under the banner
* Most of our users buy 90-days account. Paying by PayPal takes usually about 3 seconds, there are no emails or confirmations (you actually have premium after 3 seconds). Is it really so hard to spend 3 seconds four times a year? :)

**Comment by landsman** [comment]
- But I don't see this link. I expecting link on top of page.
![snimek obrazovky 2017-10-19 v 13 50 29](https://user-images.githubusercontent.com/3184228/31769571-8b5ccb0c-b4d4-11e7-8556-2be8ecc79a77.png)
-  It does not having sense buy apps every 1 or 3 months. This what I said is really usually in other softwares. You're undermine efforts...

**Comment by photopea** [comment]
I think your screen is too small for image editing (700px height). Tools on the left don't fit into a single column.  Could you try to zoom out the page in your browser?

**Comment by landsman** [comment]
This is 1280x800 px screen. Most used in older Macs.
It good for you - I want remove ads because screen => payment ;-)

**Comment by photopea** [comment]
Ok, I put the "Hide Ads" link to the top. Regarding the automatic payments: I am really afraid that people will feel too "pressured" in that case. It will look much more complicated then.

I need to ask more people about that, what they think about it.

**Comment by landsman** [comment]
Just try subscription on Netflix, Adobe, Avocode, etc ... :)

**Comment by photopea** [comment]
ok you are right. But now, we don't have many paying users, so lets leave it for the future.

**Comment by landsman** [comment]
Good can be send information about expired account by email. 
Users are accustomed for this.

**Comment by photopea** [comment]
I decided to avoid recurring payments. I don't want people to pay for it, if they don't use it e.g. for 2 months. The payment process should still be simple enough to pay when you need it.
