### ISSUE TITLE
Ctrl + click on raster (and vector) mask doesn't create selection from mask

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2780]
Everything is in the title. It should work like clicking on layer thumbnail

**Comment by photopea** [comment]
also, you can not right-click a mask. It seems like it is caused by the Alt+Shift+Drag functionality, which I added yesterday.

**Comment by photopea** [comment]
I fixed it, while Alt+Shift+Drag still works.

**Comment by MichalSZZ** [comment]
Thanks. I didn't noticed that bug what you found.
