### ISSUE TITLE
Smart object is not working

### ISSUE THREAD

**Issue by smalldead** [photopea/photopea#2784]
When I click on the smart object the window of "layers effect" pop ups :c 
I can't edit any smarts objects on my work

**Comment by swadeshpadhi** [comment]
Not working for me too

**Comment by singgihafra** [comment]
yes, it doesn't work for me

**Comment by photopea** [comment]
Hi, I am very sorry, it should be fixed now.

Reload Photopea multiple times, as browsers can store the old version of a website for up to one hour.
