### ISSUE TITLE
Photopea not retaining new custom brush, or Tool presets upon exiting

### ISSUE THREAD

**Issue by gse123** [photopea/photopea#2785]
Firstly, can I just say that I love this software...absolutely incredible, and I think you have done an amazing job. 

I have an issue where if I define a new tool preset, or create a custom brush, they show up perfectly until I exit out of Photopea and then they get lost (I am logged in to a paid account actually).  Is this supposed to happen or is it a bug? A little bit frustrating having to re-import them from a separate file or re-create them every time I use the software. 

Thank you

**Comment by Offroaders123** [comment]
I have noticed this as well and haven't gotten around to mentioning it, thanks for making a report for it. 🙂

**Comment by photopea** [comment]
At the moment, you can export brushes in an .ABR file (or tool presets as .TPL file), and then, load that file into Photopea.

When you load .ABR or .TPL into Photopea, you will be asked to store that file in the Local Storage. If you confirm, your resources will be loaded every time you open Photopea.

I will try to come out with a simpler way to do it.

**Comment by Rotstift9** [comment]
Bei mir tritt das gleiche Problem auf. Das war bisher nicht so. Der gesamte Lokale Speicher geht verloren. Muster, Formen, Konturen usw.

Gleich noch ein anderer Hinweis: Es waren neue Filter in der Filtergalerie angekündigt. Bei mir sind keine erschienen, was da ist, ist schon länger vorhanden.

**Comment by photopea** [comment]
If your Local Storage (Edit - Local Storage) is lost, you probably have a browser extension, which clears website data. You have to decide, if you want webiste data to be cleared, or if you want the Local Storage remain.

Do not use any browser extensions, if you do not know what they do. Web browsers can work well without any extensions.

**Comment by gse123** [comment]
Many thanks for your quick reply!  I don't remember it asking me for the local storage option when I imported my .ABR / .TPL but I shall try again ensuring all my extensions are definitely disabled. 

Thanks again for the great software!

**Comment by photopea** [comment]
So I guess it has been sloved and we can close it.
