### ISSUE TITLE
Partially locked up with error messages in the debug console

### ISSUE THREAD

**Issue by torndar** [photopea/photopea#2786]
Chrome 87.0.4280.141

This error is in the console wherever I click on the image
pp.js:7197 Uncaught TypeError: Cannot read property 'add' of undefined
    at ik.Nw (pp.js:7197)
    at _.ln.jP (pp.js:4994)
    at _.ln.Tf (pp.js:5005)
    at cZ.a23 (pp.js:11347)
    at cZ.hq.f (pp.js:9)
    at cZ.b$.f (pp.js:8022)
    at d5.b$.f (pp.js:8022)
    at dT.b$.f (pp.js:8022)
    at dT.RF (pp.js:10521)

This one appears when I try to click a menu
pp.js:7149 Uncaught TypeError: Cannot read property 'y5' of undefined
    at ik.B5 (pp.js:7149)
    at ik.zo (pp.js:7148)
    at Object.Q (pp.js:11538)
    at eL.update (pp.js:8039)
    at fJ.Ro (pp.js:11528)

I'll try to keep the tab open for a couple days to help troubleshooting.

**Comment by photopea** [comment]
Hi, what should I do to make it happen on my computer?

**Comment by torndar** [comment]
I wish I knew. I was trying a bunch of things and getting a little frustrated. I was playing with text layers and layer attributes trying to get a black on white label (really wish I could just give the text layer a background) and it quit working. I don't remember exactly what I clicked before it froze though. I can set a breakpoint or two and inspect some values if that would help.

**Comment by photopea** [comment]
I fixed an error related to the Leading parameter of the text. Maybe it fixes your issue, too.

Anyway, I can not fix bugs which I can not reproduce myself :( So I have to close it.
