### ISSUE TITLE
SVG Appears Incorrect in Editor and After Export

### ISSUE THREAD

**Issue by Offroaders123** [photopea/photopea#2787]
### Description
I'm not sure if something wrong with the SVG image I am trying to work with, but every time I open it with the editor or try to save it again as an SVG file, it will appear different than the original image in the editor, and it will create lines that don't exist on the original SVG when exported from the app.

Also, since it may look familiar, this is the logo for the [Electron.js](https://www.electronjs.org/) framework.

### Image Downloads
I attached screenshots of the issue to this post below, and I made a .zip file of them to download that also includes the original vector image that caused the issue, and the vector image that is downloaded after exporting from the editor.

[icon - Vector and Raster Images.zip](https://github.com/photopea/photopea/files/5854906/icon.-.Vector.and.Raster.Images.zip)

#### Original image:

![icon - Original Raster](https://user-images.githubusercontent.com/65947371/105474533-29e75700-5c53-11eb-918d-ba6a7522bc3c.jpg)

#### Image appearance within the editor:

![icon - Editor Appearance](https://user-images.githubusercontent.com/65947371/105474534-2a7fed80-5c53-11eb-9f48-3df1bb01d749.jpg)

#### Image appearance on export screen:

![icon - Export Appearance](https://user-images.githubusercontent.com/65947371/105474536-2a7fed80-5c53-11eb-9731-3676d41dfcf1.jpg)

#### Exported image:

![icon - Exported Raster](https://user-images.githubusercontent.com/65947371/105474537-2b188400-5c53-11eb-826a-b1c7626fdb1d.jpg)

**Comment by photopea** [comment]
Hi, I fixed all issues that you have mentioned.

**Comment by Offroaders123** [comment]
Awesome, thanks!
I opened the image with the editor and exported it, and all of the problems were fixed on my end as well.

How did you know what was causing it, if you don't mind me asking?

**Comment by photopea** [comment]
The PSD format does not support fill rules (like in SVG), while the SVG does not support combining operations of PSD (subtract, intersect, etc). 

Photopea has a mechanism to convert between them, but it was not perfect (as you saw in your issue), but I improved it (at least for cases such as yours).

**Comment by MEneedhelp101** [comment]
i also need help with the same problem. every time i try to save my clothing mockup to .svg the backgrounds of the images i uploaded appear but do not appear when I am editing the file on the website. i tried turning it into a smart object but then when i try to save it it just moves the image out of place when i try to save it but again works while im editing

**Comment by photopea** [comment]
@MEneedhelp101 I am a bit confused. What should I do to see the problem myself?

**Comment by MEneedhelp101** [comment]
> @MEneedhelp101 I am a bit confused. What should I do to see the problem myself?





![Screenshot (5)](https://github.com/photopea/photopea/assets/165345094/5a466310-9b25-4918-986a-56a1a7a272b0)
 
the background of the images i added to my mockup are shown when save it as an svg but not a png this screenshot will provide the info i am talking about

**Comment by MEneedhelp101** [comment]
> > @MEneedhelp101 I am a bit confused. What should I do to see the problem myself?
> 
> ![Screenshot (5)](https://private-user-images.githubusercontent.com/165345094/318108157-5a466310-9b25-4918-986a-56a1a7a272b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MzQ3MDUsIm5iZiI6MTcxMTczNDQwNSwicGF0aCI6Ii8xNjUzNDUwOTQvMzE4MTA4MTU3LTVhNDY2MzEwLTliMjUtNDkxOC05ODZhLTU2YTFhN2EyNzJiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQxNzQ2NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTA2OTcxOTg5YjA5NGMwMjBiZjViYjZhOTg4MGY4OTZlZjI4MGZjMjhmMTUzNjBkZmMyMTQxYTIyZTgzZjk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z1wfoPyCJZsdl4CJWm4o-GeUW4QFEt099MGyk_TcQm4)
> 
> the background of the images i added to my mockup are shown when save it as an svg but not a png this screenshot will provide the info i am talking about

i tried switching one of the layers to turn into a smart object but then it moves the image out of place

![Screenshot (6)](https://github.com/photopea/photopea/assets/165345094/576a333b-75bf-41fd-bdda-f320dcea7c2b)

**Comment by photopea** [comment]
Could you start a new issue and answer the required questions?

**Comment by MEneedhelp101** [comment]
> Could you start a new issue and answer the required questions?

its fine im working around the issue ,but i ran into a new one pertaining the free transform tool. I usually go to the edit section then press free transform and it gives me the option to do what i like with the image , now that i try to do that it doesn't even let me select the image.Just want to say im a fan of Photopea!

**Comment by MEneedhelp101** [comment]
> > Could you start a new issue and answer the required questions?
> 
> its fine im working around the issue ,but i ran into a new one pertaining the free transform tool. I usually go to the edit section then press free transform and it gives me the option to do what i like with the image , now that i try to do that it doesn't even let me select the image.Just want to say im a fan of Photopea!

issue fixed, I think it was a glitch. closing and reopening the project solved it
