### ISSUE TITLE
Leading non auto issues

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2789]
When I unchecked Leading Auto checkbox in Character window text cursor doing weird things and selection of text is invisible.
![image](https://user-images.githubusercontent.com/6370548/105518887-1979bf80-5cd9-11eb-9fbd-ac3059acb5d7.png)

Also when I uncheck Leading Auto on pea.psd file  "welcome" layer it does this:
![image](https://user-images.githubusercontent.com/6370548/105518809-fea74b00-5cd8-11eb-99ac-62b9de8dbfef.png)

**Comment by photopea** [comment]
Hi, I fixed this.
