### ISSUE TITLE
Support for More File Extensions | File Handling API

### ISSUE THREAD

**Issue by Offroaders123** [photopea/photopea#2790]
*About [File Handling API](https://web.dev/file-handling/) (Article on web.dev)*

I noticed in the [Web App Manifest](https://www.photopea.com/manifest.json) that the File Handling API section currently supports Photopea file associations with `.jpg` images, and I was wondering if you have plans to add more file associations in the future? A few that came to mind include:

`.psd` `.png` `.svg`  `.tga`  `.jpeg` `.gif`

**Comment by photopea** [comment]
Is this part of manifest actually useful? Does any browser provide any feature based on these formats?

**Comment by Offroaders123** [comment]
Currently the API is not supported by default in public browser releases, but I have the flag enabled on Google Chrome on my desktop devices, and it works for [my site](https://offroaders123.github.io/Smart-Text-Editor/) and a few others like [Excalidraw](https://excalidraw.com/), as of now. The flag can be enabled on any newer releases of Chrome or Edge in the feature flags page (chrome://flags/#file-handling-api), and it is supported on Windows, macOS, and Chrome OS.

If you want to see the behavior in action on other sites, the app to test has to be in the installed state, and the feature flag enabled in the feature flags page.

Exalidraw has a custom file extension that is associated with their app, `.excalidraw`, and right-clicking on the file will show Excalidraw as a program to open the file with.

_Image from web.dev:_
![File Handling API in action](https://webdev.imgix.net/file-handling/finder.png)

**Comment by photopea** [comment]
Hi, I added more image formats into the manifest and implemented the basic support, according to the current implementation in Google Chrome. When opening PSDs, File - Save works for rewriting the original file.

When you open multiple files from your computer, it opens a separate Photopea window for each one of them. I guess browser developers have to fix it.

**Comment by Offroaders123** [comment]
Awesome, thanks! I'll try out the new file associations after this.

I noticed the window opening issue a few months ago as well, and I submitted an [issue/feature request](https://github.com/WICG/file-handling/issues/45) on the [File Handling API proposal repository](https://github.com/WICG/file-handling) created by WICG. Two of the members of WICG said that this was an issue that they knew about, and that it would likely have a solution in the future. These are their comments [here](https://github.com/WICG/file-handling/issues/45#issuecomment-729435742) and [here](https://github.com/WICG/file-handling/issues/45#issuecomment-728497420) on my issue/feature request.

**Comment by Offroaders123** [comment]
Works on my end after reinstalling the app 👍

![Successful issue fix screenshot](https://user-images.githubusercontent.com/65947371/105562293-7623ad00-5cce-11eb-8771-2b55953bd2d3.png)

**Comment by photopea** [comment]
The standard Chrome release already supports File Handling API, so you can double-click files in your computer to open them in Photopea.com .

https://twitter.com/photopeacom/status/1531325944501354497
