### ISSUE TITLE
Exporting files 

### ISSUE THREAD

**Issue by redbayoub** [photopea/photopea#2791]
Hi, 
I love using the web app version but when I try to export or save as psd the window of save file shows sql extension instead of the real extension JPG, PNG 
![image](https://user-images.githubusercontent.com/40964509/105573974-994b6c80-5d61-11eb-8396-be76df45feb8.png)
so I have to manually write the extension before clicking on save
![image](https://user-images.githubusercontent.com/40964509/105573995-c9930b00-5d61-11eb-9439-8d32d519db98.png)

**Comment by photopea** [comment]
Hi, these things can be redefined only by a browser or browser extensions. Can you disable all browser extensions and try it again? Or find the one which causes it?

**Comment by photopea** [comment]
I think this error has been fixed by disabling the problematic browser extension.
