### ISSUE TITLE
Advanced Blur: Field Blur, Iris Blur, Tilt-Shift blur

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#2792]
- field blur
- iris blur
- tilt-shift blur

why you don't add these filters to photopea, however, they are not hard or difficult to make....?

![filtermenu](https://user-images.githubusercontent.com/70863817/105577808-78484300-5d84-11eb-871d-e28824e29ff3.png)

**Comment by MichalSZZ** [comment]
Yes that would be great. I'm using they very oft.

**Comment by mustafaGFX** [comment]
@MichalSZZ 
yes, and there are important for a lot of people, and they are not very complex to embed as the other filters in the filter gallery

**Comment by mustafaGFX** [comment]
you changed the title but you didn't answer me :(

**Comment by IamFlea** [comment]
@mustafaGFX @MichalSZZ  do you also use distortion in the TiltShift blur?

**Comment by MichalSZZ** [comment]
@IamFlea no, I have never use it.

But adding noise or bokeh - yes.

Look that in Photoshop that are a filters that can combine more than one point of blur center.

**Comment by MichalSZZ** [comment]
Hi @photopea 

is there something new in this topic? Maybe for the start only one of them... tilt-shift with basic functionality for example (start, stop, angle and blur strength)? 

Today i make a PSD template in Photoshop for my Social Media Specialist and I forgot that in Photopea there isn't implemented yet Tilt-Shift Blur... (my coworker will make only modifications in template by adding new photos and text in Photopea but blur effect will be invisible when he update smart object with image)

**Comment by photopea** [comment]
These filters have their own user interface, with too many parameters.

Do you think all these filters could be simulated by the Lens Blur method, while all the parameters serve for generating a specific depth map? E.g. a depth map of a gradient between black and white for the Tilt Shift.

**Comment by mustafaGFX** [comment]
technically they can be simulated by the Lens Blur method, but it will be so difficult to get the perfect result, cuz I have to make the depth map before putting the filter and edit it many times to rich the needed result, I have just tried this way and it was too hard especially with the filed blur...... the iris blur and tilt-shist blur filters were not too hard to simulate but the filed blur filter was tiring

**Comment by yikuansun** [comment]
@mustafaGFX 

> I have to make the depth map before putting the filter and edit it many times to rich the needed result

I usually use the filter mask with Lens Blur, you can adjust it a lot faster than with depth map. I'm not sure about quality differences, but my method usually looks pretty fine.

**Comment by yikuansun** [comment]
> I usually use the filter mask with Lens Blur

<img width="1280" alt="Capture" src="https://user-images.githubusercontent.com/38194363/127055272-be978988-0ef4-473e-a8a0-cb635fe574b9.PNG">

**Comment by mustafaGFX** [comment]
> I usually use the filter mask with Lens Blur, you can adjust it a lot faster than with a depth map. I'm not sure about quality differences, but my method usually looks pretty fine.

it for sure doesn't look professional and looks unrealistic, especially with high-detailed images, it just makes the blur effect fade away, and this feeling can be noticed very clearly when you increase the blur

![g9aaf8114c6b5ce57b1868c39078da5be10d0f59c1b9cc9af8 (1)](https://user-images.githubusercontent.com/70863817/127210779-3993684e-81b3-4fe9-af34-033ac9c9c564.png)

when we talk about realism, we need a technically mathematically right blur effect, with a start and endpoint of blur
were the same example but with the lens blur (almost the same depth)
![g9aaf8114c6b5ce57b1868c39078da5be10d0f59c1b9cc9af8](https://user-images.githubusercontent.com/70863817/127211097-91757478-0f2f-4695-ad99-4d923b5275f5.png)

**Comment by mustafaGFX** [comment]
the difference is huge, there's no compare
![g9aaf8114c6b5ce57b1868c39078da5be10d0f59c1b9cc9af8 (2)](https://user-images.githubusercontent.com/70863817/127211647-19e3beb4-fa5c-4ac5-8395-22122dda2116.png)

**Comment by mustafaGFX** [comment]
can you feel that there is any depth in this image ?
any far point and close point of the lens ?
![ge632021b4005743f4d7375e6802c66d6e87a7e1be8566c381](https://user-images.githubusercontent.com/70863817/127211989-fa254b36-a43b-41a6-baae-d2920e23e44f.png)

**Comment by mustafaGFX** [comment]
can you feel any depth in this?

![g469260daaad1bdb30de9df706c7eb592ab71bf111680811e3 (1)](https://user-images.githubusercontent.com/70863817/127213102-0cfafe62-5ae8-4879-9043-51640476fe91.png)

.
.
.
lent try the same image but with lens blur:

![g469260daaad1bdb30de9df706c7eb592ab71bf111680811e3](https://user-images.githubusercontent.com/70863817/127213327-c4ec3e48-3361-4b3b-8be4-59b48dc2524a.png)


I increased the blur to make the deference noticeable

**Comment by yikuansun** [comment]
@mustafaGFX Are you using lens blur for both?

**Comment by mustafaGFX** [comment]
yes

**Comment by mustafaGFX** [comment]
lens blur is good for some cases bur for sure it can't replace the other advanced blur effects

**Comment by yikuansun** [comment]
@mustafaGFX Oh yeah, I do see your point. My bad. I generally work with more subtle depth of field, so the filter mask is okay for me but I see that it wouldn't work for deeper depth of field.
I think you could use the filter mask to preview the effect, then create a new black color fill, convert to smart object, use hue/saturation and colorize and increase the lightness so it is completely white, then move the filter mask to the new white layer, then convert to smart object, creating a depth map for the lens blur. This way, you can have a fast preview and a quality final.

> lens blur is good for some cases bur for sure it can't replace the other advanced blur effects

You can try making the light pop more using the Maximum filter

**Comment by yikuansun** [comment]
Path blur would also be nice

**Comment by mustafaGFX** [comment]
it is a good way but it would be better if we just have these advanced filters, I don't know why they are so late :(
however, there aren't as complex as other filters in the filter gallery that need study and time

@photopea can you give us any good news if you have one of these filters or more?

**Comment by mustafaGFX** [comment]
> These filters have their own user interface, with too many parameters.

if you need any help with the user interface please tell me, I would be happy to see my interface design used by hundreds of users around the world, also I know how do you think and I understand your version about the UI of photopea and can make it perfect

if you don't want people to participate in the development of photopea I understand it, but for sure steve jobs didn't create apple brand alone, and Bill Gates didn't make the huge name of Microsoft alone, as I said before we need to help each other to make the things perfect

**Comment by mustafaGFX** [comment]
I don't tell you to make it open source (and I don't want to), and I don't want to be a Contributor to photopea in Github, I just love the perfect things

**Comment by yikuansun** [comment]
@photopea The bokeh controls in Photoshop would also be nice. Lens Blur is pretty good, but it can't create the dramatic bokeh with hard edges.

**Comment by itb-devs-de** [comment]
The depth map could be a replacement for tilt-shift, but when it is activated for Lens Blur, it doesn't allow a radius larger than 5, which makes it unusable. I need a radius of about 50, which is no problem without depth map. Is this a fixed limitation or based on resources, image size, oder other factors?

**Comment by yikuansun** [comment]
> The depth map could be a replacement for tilt-shift, but when it is activated for Lens Blur, it doesn't allow a radius larger than 5, which makes it unusable. I need a radius of about 50, which is no problem without depth map. Is this a fixed limitation or based on resources, image size, oder other factors?

I agree, lens blur is a very nice filter but performance keeps it from perfection. I [raised this issue previously](https://github.com/photopea/photopea/issues/5348). My recommended solution would be switching to a lower-quality, performance-optimized algorithm, at least while the user is experimenting with the sliders, and if possible, switch to a quality-optimized algorithm once the user presses `OK`.

**Comment by photopea** [comment]
Hi, I have added the Blur Gallery filter: https://www.photopea.com/learn/blur-gallery

**Comment by yikuansun** [comment]
Thanks so much, Ivan!! You're the best!

**Comment by photopea** [comment]
you are welcome :) I had fun working on these filters!
