### ISSUE TITLE
Add alternative glyphs menu to Photopea

### ISSUE THREAD

**Issue by JeremixxGithub** [photopea/photopea#2795]
I would like to access alternative glyphs and stylistice sets in Photopea. Here's my example on how would it look like.
![image](https://user-images.githubusercontent.com/77931550/105637070-bc624300-5e6b-11eb-932f-5f80aafe8b07.png)

**Comment by photopea** [comment]
Actually, all glyphs available in a font should be listed in a Glyph menu (i.e. a font does not contain any other glyphs than those which you see).

**Comment by JeremixxGithub** [comment]
But what if a font has alternative glyphs and you want to access them?

**Comment by JeremixxGithub** [comment]
https://www.youtube.com/watch?v=YclhHYvf_bo here's an example

**Comment by photopea** [comment]
We can not add this feature from Adobe illustrator, because I think the PSD format does not support it.

But now, you can add any glyph from a font into a text layer, so it should be doable now. https://github.com/photopea/photopea/issues/3082
