### ISSUE TITLE
Crashes frequently

### ISSUE THREAD

**Issue by luisckc** [photopea/photopea#2796]
![Premium](https://user-images.githubusercontent.com/67866380/105700689-f40ed080-5ee7-11eb-99fa-32af0cc4b7e2.png)
Hi! I have a premium account, but I have noticed that internet addresses appear in the lower left corner. As if trying to load advertisements. Slowness and crashes were very common in the free account and I noticed that it had a direct relationship with the loadings of advertisements. Today the situation is the same, if not worse. I just can't work! I click on a tool, or to expand the styles of a layer, and nothing happens, or it takes a long time. Some windows, like the style windows, sometimes open incomplete ... Until yesterday this did not happen.

**Comment by photopea** [comment]
Hi, can you try to use Photopea in Incognito mode? Does it still crash so much?

I think you may have browser extensions, which ruin your experience (by recording what you do on every website, or slowing down your computer in other ways, etc). Browser extensions are disabled in incognito mode.

**Comment by luisckc** [comment]
Hello. I used Photopea in the Slimjet browser, based on Chromium. It is 32
bits, lightweight and only has two extensions installed. I am now using the
installed version of Photopea. I know it also runs in the browser, in
hidden mode.
However, what was most problematic, as I mentioned, was the constant
loading of advertisements. After logging off and logging on to Photopea, it
no longer gave the problem of crashing and slowing down (at least
yesterday). I'll watch today. If it happens again, I will try in incognito
mode. By the way, when I use Photopea installed, does it run on the browser
in incognito mode?

Em seg., 25 de jan. de 2021 às 11:39, Photopea <notifications@github.com>
escreveu:

**Comment by photopea** [comment]
I think if you "install" Photopea, it still runs with your extensions enabled.

Can you figure out, if it crashed because the RAM ran out, or the GPU memory ran out? Look into a browser console to see, if there are any warnings after the crash.

**Comment by luisckc** [comment]
My PC is a little old, but the configuration is reasonable: i5-2500K CPU
3.30 GHz; 8 GB RAM, NVIDIA GeForce GTX 1060 6GB, Windows 10 64 bit
installed on SSD.
Observe in the attached files 1 and 2 the main memory and the video card
memory, before and after opening the installed Photopea and uploading a 21
MB, 600 DPI file...
The open browser consumes 241 MB. On the other hand, when I open Photopea
and the file above, it increases the main memory by 15% and the video card
memory by 50%! To work with a 21 MB file, Photopea is using 4096 MB (4 GB).
If I need to open a second file to copy layers, it is very slow.
Is it normal for Photopea to consume so much memory?
There are 100 Mb psd files that I couldn't even open, let alone work on it.
I need to know from you the limitations of Photopea and I will test the
Gimp to see if it is the same. I signed up for a Premium account to see if
I could work. It has improved, but not enough. Currently, I cannot change
PCs because the dollar price is very high and everything comes from other
countries.

Em ter., 26 de jan. de 2021 às 10:07, Photopea <notifications@github.com>
escreveu:

**Comment by photopea** [comment]
Hi, how many pixels are there in your file? Photopea needs 4 Bytes for every pixel. If you have 10 layers of 10,000x10,000 pixels, that is one billion pixels = 4 GB of RAM.

When all billion pixels have the same color (e.g. red), it can be compressed into very small files (a PSD of 21 MB), but to work with that file, we still need to keep the billion pixels in memory.

**Comment by luisckc** [comment]
I understand. The way will be to buy more memory ...
Thanks.

Em ter., 26 de jan. de 2021 às 19:36, Photopea <notifications@github.com>
escreveu:

**Comment by photopea** [comment]
I added the new feature, which can help you find the problem.

Press Window - More - Memory. It will show you the RAM and the GPU memory, that is currently used by each document. If the values are close to the limits of your device, then, it crashes because of insufficient memory.

The Memory panel ignores the steps in the history. If you create 10 layers and delete 9, the Memory panel knows about only one layer (the only one in your document), even though more layers are stored in RAM (so that you can go back to them if you want).

Also, your Slimjet browser could be simply killing every website that uses over 1 GB of RAM. Do you know how Slimjet works? Have you tried another browser?

**Comment by photopea** [comment]
Actually, Photopea could be crashing because of you having Premium :( Can you try to log out? Does it still crash?

With Premium, Photopea keeps 60 steps in history instead of 30. And by remembering more steps, the memory runs out faster.
