### ISSUE TITLE
Slices from guides enhacement

### ISSUE THREAD

**Issue by JoeRaig** [photopea/photopea#2797]
Hi, I don't know if this particular functionality is included. I was looking in the user guide and on the web, but I didn't see any exact reference to what I'm looking for.

Both, Gimp and Photoshop include a functionality to "Slices from guides". Like here:

![image](https://user-images.githubusercontent.com/48797109/105706358-baeb5600-5f11-11eb-861a-a36853f2c0d0.png)

In Photopea there is also something similar. Once you have set the guides, you can select the slices and the will adapt to the guides. Then when exporting you can get a zip file with each of the selections "as slices".

This works well, but it would be great if it could be done automatically like in the programs mentioned above. Because if, for example, you want to cut an image in 9 parts and you have 10 images, right now you have to make 90 slice selections.

If someone knows how to do it in a faster and more productive way, I would appreciate the help. 

This is a suggestion for an enhancement in case this functionality does not exist. I hope the app continues improving and thank you very much for the effort put into it. Great job!

**Comment by photopea** [comment]
I have added this feature to the Slice tool :)

**Comment by JoeRaig** [comment]
Perfect, thank you! Great work!
