### ISSUE TITLE
Feature Request: Layer mask refining options (smooth, feather, contrast etc)

### ISSUE THREAD

**Issue by gse123** [photopea/photopea#2798]
Hi there,

I hope it would be possible in some future version of Photopea to have at least basic options for adjusting a layer mask outside of the main refine edge feature that currently exists. i,e, to be able to simply and quickly feather, smooth, expand, contract the mask etc. I know there are options to do this to a selection, but not currently for a mask unless i'm mistaken.  (apart from in a layer mask's properties box, where I know there is a real time feather slider). 

Don't get me wrong, refine edge is great, but often i'd need to make more basic 'linear' refinements to a mask as above. 

Thank you for taking the time to read all these - it is very much appreciated!

**Comment by avagp** [comment]
When selecting a layer's mask, go to properties:
![image](https://user-images.githubusercontent.com/11801254/108734510-4e627780-750e-11eb-88fc-b63048e6dd53.png)

Is that what you are looking for? (at least, basically)

**Comment by photopea** [comment]
You can Ctrl+click the mask to turn it into a selection, modify your selection, and then, turn the selection into a mask.

Also, you can apply filters on a mask (gaussian blur filter, etc).

Have you seen the features you describe in some other program? Where it is located? For now, I do not know where should I put these features.

**Comment by gse123** [comment]
> You can Ctrl+click the mask to turn it into a selection, modify your selection, and then, turn the selection back into a mask.
> 
> Also, you can apply filters on a mask (gaussian blur filter, etc).
> 
> Have you seen the features you describe in some other program? Where it is located? For now, I do not know where should I put these features.

Hi, It's in the Photoshop Select and Mask function... and was also in the refine edge function before that. 4 Sliders that you can use on a mask - Smooth, Feather, Contrast, and Shift Edge.  I use them all the time in my Retouching day job, and while I do appreciate there is a  workaround of doing adjustments to a selection via the 'Selection>Modify' menu and then turn that back into a mask... it's really cumbersome to work that way and not be able to apply these modifications directly onto a mask (although like avagp said, I am aware that you can adjust the Feather real time in the properties panel. 

Thank you - just a thought for the future... I think you are doing an amazing job with Photopea!

**Comment by photopea** [comment]
Photoshop has Select and Mask for this, but I think a brand new window would be an overkill. You can convert a mask to a selection, modify a selection, and put it back into a mask.

**Comment by nothingshiru** [comment]
What about implementing those 4 options like a "Adjustments"?
Like this
![Screenshot_20210702_181405_com android chrome](https://user-images.githubusercontent.com/79258245/124263823-55596080-db66-11eb-9f00-4404c53e970f.jpg)

It would be very helpful that having realtime preview.
