### ISSUE TITLE
Error when dragging JSX file

### ISSUE THREAD

**Issue by Nanoo-web** [photopea/photopea#2800]
You stated [here](https://github.com/photopea/photopea/issues/1152#issuecomment-455267746) that a JSX file can simply be dragged & dropped, to run a script, within Photopea.

However, I am getting this error:
![image](https://user-images.githubusercontent.com/62435867/105873293-3c66e500-5ff3-11eb-8b1d-ecb058a5a870.png)
![image](https://user-images.githubusercontent.com/62435867/105873597-8fd93300-5ff3-11eb-9017-b9cfb0ca0cea.png)

My file has the JSX extension, as shown here:
![image](https://user-images.githubusercontent.com/62435867/105873404-5a344a00-5ff3-11eb-924d-1b085d76a395.png)

Am I doing something wrong? Or is this a feature that you no longer support?
(I am using Chrome 87.0.4280.141)

**Comment by photopea** [comment]
Hi, it should be fixed now.

**Comment by Nanoo-web** [comment]
I confirm that it's now working again - thanks!
