### ISSUE TITLE
text not showing in art

### ISSUE THREAD

**Issue by vinodpanchal** [photopea/photopea#2803]
![image](https://user-images.githubusercontent.com/78083174/105985434-74d4f480-60c1-11eb-9065-a7ce767ecbd2.png)

no text showing after creating text layer

**Comment by photopea** [comment]
Maybe your browser or some antivirus is blocking the download of OTF files. Are you using such programs to monitor and block internet traffic? Could you change the settings your programs?

Can you access e.g. this font? http://photopea.com/rsrc/fonts/fs/DejaVuSans.otf

**Comment by photopea** [comment]
Also, try to update your browser and disable all extensions.

**Comment by photopea** [comment]
I guess it has been fixed.
