### ISSUE TITLE
Convert to Point/Paragraph Text issues

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2804]
Convert to Point Text or Paragraph Text moves the text. It was working perfectly after fixing #2202 in June but after recent changes it seems much worse then before. It not only moves the text by large amount but sometimes when I convert to Paragraph Text part of text disappears because photopea makes the bounding box smaller then text so it doesn't fit.

1. I have Paragraph Text
![image](https://user-images.githubusercontent.com/6370548/106006184-39ccc400-60b5-11eb-95c1-9df02eb83192.png)
2. After I click Convert to Point Text (It jumps to comletely different position)
![image](https://user-images.githubusercontent.com/6370548/106006278-57019280-60b5-11eb-8be6-3d0a062fcf92.png)
3. After I click Convert to Paragraph Text (Part of text disappears because it does not fit into created paragraph box)
![image](https://user-images.githubusercontent.com/6370548/106006508-992ad400-60b5-11eb-966c-365c1d618994.png)

**Comment by photopea** [comment]
I am very sorry, I fixed it.
