### ISSUE TITLE
Feature request: import-only uploading of MP4 files

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2805]
Please allow for uploading of MP4 files by breaking them down into frames. MP4 files would be treated similarly as GIFs are treated, except MP4 files would be import-only. It would enable making GIFs of small sections. (This is also part of the reason why I requested an option to remove \_a\_ from selected animation frames in [#2646](https://github.com/photopea/photopea/issues/2646#issuecomment-768450445).)

There are already third party websites for converting video files to GIFs. I would like to cut out the third party by uploading MP4 files to Photopea, but I'm okay going without this feature if you feel that it would make Photopea too large.

**Comment by photopea** [comment]
I implemented it. It is done through the internal video decoder of a browser (so it might work a bit differently in each browser).

A video is converted into frames at 10 FPS.

**Comment by dentistformyeye** [comment]
Thank you so much! Using the browser's decoder was a great idea.

**Comment by MichalSZZ** [comment]
@photopea  how can I open a mp4 file in Photopea? It does not working for me. 
here you have a mp4 file
[iga-mac.zip](https://github.com/photopea/photopea/files/6426225/iga-mac.zip)
when I tried to open it show only an error
![obraz](https://user-images.githubusercontent.com/38118273/117124031-18583400-ad98-11eb-97ce-28e7363bb142.png)
