### ISSUE TITLE
Feature request: Add user-defined channels count support for .raw import

### ISSUE THREAD

**Issue by victimized0** [photopea/photopea#2806]
.RAW files can store an arbitrary amount of channels while photopea only allows to use 1/3/4 channels.
Would be awesome to have support to define myself how many channels my .RAW files has.

**Comment by photopea** [comment]
Hi, do you really have RAW files with a different number of channels? How many channels do you have?

**Comment by victimized0** [comment]
Hey, yes indeed we have .raw files with an arbitrary number of channels.
I've used to work with 5 channels, 7 channels, and even 16 channels!

**Comment by photopea** [comment]
Is there any program (other than your own) which can edit these files? Have you thought using regular PNGs with one channel in each file? PNG decoder can be very small, under 15 kB.

**Comment by victimized0** [comment]
Well, the only software with such support is Photoshop but I simply cannot afford it...
I can't use it in any other form because I'm using .raw file format for debugging reasons; I dump a lot of debug data in a .raw file, that data is visual representation of multiple arrays

**Comment by victimized0** [comment]
Is this a big issue to replace RadioButton with a TextBox? Just curious why wouldn't this be easy?

**Comment by photopea** [comment]
Right now, Photopea can have four channels in a layer. How should we interpret the fifth and other channels?

Can you send me your RAW file to support@photopea.com, so that I can see what happens with extra channels in Photoshop?

**Comment by victimized0** [comment]
Sent. IIRC Photoshop recognises first 3 channels as rgb channels and rest are just alpha channels. Or if image mode is set to cmyk then it recognises first 4 channels as cmyk and rest as alpha channels. In fact each individual channel is just a greyscale file so if you could interpret channels > 4 as just a batch of greyscale channels that would do it.
Or alternatively you could add a checkbox to interepret channels as layers; This way you would have a single greyscale channel but arbitrary number of layers.

**Comment by photopea** [comment]
I implemented it :)  Now, Photopea can handle raw files the same way as Adobe Photoshop.

Photopea always expects the channel values to be interleaved, as I have not seen a raw file with non-interleaved values.
