### ISSUE TITLE
Past history states locked after Convert to Paragraph Text while editing new text

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2807]
If I use Convert to Paragraph Text on a newly created text layer that hasn't been confirmed for the first time and is currently being edited, previous history states become locked in the history panel and cannot be accessed with control-Z.

## Steps to reproduce
1. (Confirm that all extensions are disabled.) Open a new document in Photopea.
2. Switch to the text tool. Click on the editable area. Type something visible in the textbox. Click the checkmark to confirm the text layer.
3. Click on the editable area. Type something visible in the textbox. DON'T click the checkmark.
4. Right-click the text layer from step 3 and choose Convert to Paragraph Text.
5. Either click the topmost "Type Tool" state in the History panel or press control-Z twice.

## Expected result
Between steps 4 and 5, the current text layer being edited should be automatically confirmed and written into a new history state. Then, still before step 5, the text layer should be converted to paragraph text, producing another new history state. Previous history states should remain accesible.
Convert to Shape and Convert to Smart Object both produce the expected behavior:
1-3. Perform steps 1-3 as described in the previous section.
4A. Right-click the text layer from step 3 and choose Convert to Shape.
![image](https://user-images.githubusercontent.com/51429646/106043015-cf635600-60ab-11eb-92d6-83b937a38587.png)

5A. Either click the topmost "Type Tool" state in the History panel or press control-Z twice.
![image](https://user-images.githubusercontent.com/51429646/106043062-df7b3580-60ab-11eb-8ae5-4bae86ad8845.png)

## Actual result
Right before completing step 4, there are two history states and the second text layer shows up as "Text layer 2" rather than as whatever the user types. This is normal behavior.
![image](https://user-images.githubusercontent.com/51429646/106040934-24ea3380-60a9-11eb-8e81-0d7fb831e341.png)
 
Right after completing step 4, the confirmation buttons remain in the top bar and the text layer is still in edit mode. A new "Type Tool" history state still appears, but this new state is actually equivalent to the first "Type Tool" state; it contains only the first text layer. [Note: ignore the textbox outline in my screenshot. My keyboard shortcut for screenshots uses the control button, which makes Photopea outline temporarily highlight textboxes.]
![image](https://user-images.githubusercontent.com/51429646/106043632-b3ac7f80-60ac-11eb-8c5b-3dd8c20e9059.png)

After completing step 5, yet another Type Tool state appears. (If using the control-Z method, the new state appears after the first control-Z.) The first "Type Tool" state and the "Open" state cannot be accessed. The newest state has the second text layer, which is paragraph text. In other words, part of this newest state is actually what should have been in the second "Type Tool" state!
![image](https://user-images.githubusercontent.com/51429646/106043862-f9694800-60ac-11eb-8166-25fda23efacc.png)
This appears in the console after step 5. (If using the control-Z method, the first control-Z makes the "disabling 47" appear. The second control-Z makes the red error appear.) Further attempts to access the inaccessible history states make the red error appear again.
![image](https://user-images.githubusercontent.com/51429646/106046860-d04ab680-60b0-11eb-98d8-f4e50d676bfd.png)

**Comment by dentistformyeye** [comment]
At the moment, Convert to Paragraph Text and Convert to Point Text both produce history states called "Type Tool". To make the history panel easier to understand, I'd recommend that the history states say "Convert to Paragraph Text" and "Convert to Point Text", respectively

**Comment by dentistformyeye** [comment]
Using Convert to Paragraph/Point Text on a previously existing text layer that is currently being edited produces broken history states but doesn't lock older history states.

## Steps to reproduce
1. (Confirm that all extensions are disabled.) Open a new document in Photopea.
2. Switch to the text tool. Click on the editable area. Type something visible in the textbox. Click the checkmark to confirm the text layer.
3. Click on the existing textbox to reenter edit mode. Change the text to something else visible. DON'T click the checkmark.
4. Right-click the text layer from step 3 and choose Convert to Paragraph Text.
5. Either click the top "Type Tool" state in the History panel or press control-Z exactly once.
6. Click the bottom "Type Tool" state in the History panel. (Keyboard shortcuts don't work because the textbox is in focus.) Click on the existing textbox to reenter edit mode.
7. Click back to the top Type Tool state. Reenter textbox edit mode.
8. Click back to the bottom Type Tool state. Reenter textbox edit mode.

## Expected result
Between steps 4 and 5, the current text layer being edited should be automatically confirmed and written into a new history state. Then, still before step 5, the text layer should be converted to paragraph text, producing another new history state. There should be four history states total, including "Open".

## Actual result
After completing step 2, the layer name matches the text in the textbox. This is normal behavior.
![image](https://user-images.githubusercontent.com/51429646/106062167-6d631a80-60c4-11eb-86db-6213525f819d.png)

After completing step 3, there is one history state and the text layer's name is whatever the user had typed in step 2. This is normal behavior.
After completing step 4, a new "Type Tool" history state appears, the confirmation buttons remain in the top bar, and the text layer is still in edit mode. The text layer still has the old name.This text is paragraph text (which can't be confirmed until step 6) even though the editor still thinks it's point text.
![image](https://user-images.githubusercontent.com/51429646/106062228-7e139080-60c4-11eb-8831-01224fceb9d7.png)

After completing step 5, "disabling 47" appears in the console. The text layer still has the old name, but contains the new text. (This is point text, but that can't be confirmed until step 7.) This means that the top "Type Tool" history state was overwritten by step 4 and the bottom "Type Tool" state is for the Convert to Paragraph Text.
![image](https://user-images.githubusercontent.com/51429646/106062391-b4e9a680-60c4-11eb-92a0-790cfb82d248.png)

After completing step 6, the text layer name and textbox contents finally match. The text in the newer state seems to be paragraph text. It is still paragraph text because we did not try to edit the older state in step 5.
![image](https://user-images.githubusercontent.com/51429646/106062430-c3d05900-60c4-11eb-9df5-05bdf628dc8c.png)

After completing step 7, the text in the older state seems to be point text.
![image](https://user-images.githubusercontent.com/51429646/106062539-e82c3580-60c4-11eb-8f07-f6bb8939bdee.png)

Step 8 reveals that step 7 has overwritten the text in the newer state into point text. From this point on, all history states are stable.
![image](https://user-images.githubusercontent.com/51429646/106062853-5b35ac00-60c5-11eb-8e9d-89725456be88.png)

**Comment by photopea** [comment]
Hi, I fixed this problem.

When you are editing text, converting it to Point / Paragraph will not do anything.

These actions get a more specific names in history now.
