### ISSUE TITLE
Eraser Tool not working

### ISSUE THREAD

**Issue by 22tolmjam** [photopea/photopea#2808]
The eraser tool quits working for some strange reason. I tried to erase after using the Lasso tools, but the eraser won't work.

**Comment by photopea** [comment]
Hi, can you describe what should I do to make it happen? It does erase in my case.

**Comment by 22tolmjam** [comment]
I'm not entirely sure why it isn't erasing. It just stopped erasing after I used the Lasso tool. I don't know if it is my computer or if it is the site. It might be my computer, though. It's old and doesn't run the very best.

**Comment by photopea** [comment]
Can you save your work as a PSD, close photopea and open it again?

**Comment by MichalSZZ** [comment]
Maybe that is strange question but... Do you erase inside your selection or outside?
Did you change opacity of the tool or the flow (to 0% for example) in the top tool menu bar?

**Comment by photopea** [comment]
I have to close it because of lack of details.
