### ISSUE TITLE
Photopea not displaying correctly

### ISSUE THREAD

**Issue by AirGEL** [photopea/photopea#2809]
Photopea had crashed, and when I reloaded it, all the showed up was a blank gray screen like this:
![image](https://user-images.githubusercontent.com/73725883/106231351-5a287b80-61a6-11eb-9580-f183954151a3.png)

I tried closing it and opening it again and it still does the same thing.

**Comment by photopea** [comment]
Can you open it in the incognito mode? Can you clear website data (cookies etc)?

**Comment by AirGEL** [comment]
I closed my browser and reopened it and it works fine, but it still
sometimes just goes blank like that while in the middle of doing stuff.

**Comment by photopea** [comment]
What web browser do you use? is it updated? Do you think you could run out of RAM memory?

**Comment by photopea** [comment]
I will close it now.

**Comment by AirGEL** [comment]
Firefox, it says it can't update, and idk about RAM
