### ISSUE TITLE
Here is a screen shot of Photopea on my computer. You see only 7 tools, if your scren is small.

### ISSUE THREAD

**Issue by jarocho2** [photopea/photopea#2810]
Here is a screen shot of Photopea on my computer. You see only 7 tools, if your scren is small.

![image (1)](https://user-images.githubusercontent.com/15955558/104247214-9ac68c00-5467-11eb-9fa2-bb03e607f562.png)

_Originally posted by @photopea in https://github.com/photopea/photopea/issues/2742#issuecomment-758274236_

**Comment by jarocho2** [comment]
My computer does not appear the cloning and loop tools, which may be because both do not appear online and the clone tool appears in the application

**Comment by jarocho2** [comment]
![Captura de pantalla de 2021-01-28 22-42-54](https://user-images.githubusercontent.com/78192201/106232711-4424b600-61ba-11eb-975b-1436e33b66b0.png)
See this.

**Comment by photopea** [comment]
That is a correct bahviour. We have about 50 tools in Photopea and we can not show them all at once. You should click and hold a tool button to see more tools under that button. 

The Magic Wand or the Paint Bucket hidden even on large screens.

**Comment by jarocho2** [comment]
You're right, what you say is correct, I just found out. Thank you
very much for your prompt reply. Greetings.
