### ISSUE TITLE
Images not viewable when inserted into new document

### ISSUE THREAD

**Issue by lhalford00** [photopea/photopea#2811]
I've tried dragging them in and placing them on the canvas, and I've tried open and place. 

Just get this screen 
![image](https://user-images.githubusercontent.com/78206412/106261625-b4165900-6219-11eb-9b65-2ee19183f2ee.png)

You can see them in the layers panel but not on the clipboard?

**Comment by photopea** [comment]
Hi, as you see in the Layers panel, the selected layer is covered by a layer "Background" on top of it. Hide or remove the "Background" layer, to see layers below.
