### ISSUE TITLE
Could you please improve Replace Color?

### ISSUE THREAD

**Issue by steekingdom** [photopea/photopea#2812]
I have noticed that the replace color feature is not at the same quality as on photoshop. The new colors a lot of the times look not realistic at all. I think it mostly depends on the pictures and what color you need, but having used the photoshop one for many years, I have completely abandoned the photopea one even though I use it almost daily, and just change colors manually which takes a lot more work.

For example this picture. On photoshop it would be a super easy and basic change, but here it looks too.. pixelated and not natural, with weird glows. And this is a very good quality picture, so in lower quality ones things are a lot worse. I have tried all kinds of adjustments but some things can never look normal.

![Markiplier-Net-Worth](https://user-images.githubusercontent.com/39697792/106266898-a5d43700-6231-11eb-9db6-496cc745d17a.png)
![latest cb=20161010163949](https://user-images.githubusercontent.com/39697792/106266911-a79dfa80-6231-11eb-8966-ccb3bcab1537.png)

**Comment by photopea** [comment]
You are right, my method for replacing color was crazy. I fixed it. Here is the result Photopea (left) vs. Photoshop (right).

![red_hair](https://user-images.githubusercontent.com/15955558/109396498-2c179200-7932-11eb-98f2-3b17532e80f6.jpg)
