### ISSUE TITLE
Sudden non acceptance of files 

### ISSUE THREAD

**Issue by jhkjhlkhNM** [photopea/photopea#2813]
From one day to the next Photopea stopped opening image files I have on my computer, the same image files that it opened yesterday, it stopped opening today. The files were not altered. A pop-up tells me they contain system files - please see screenshot attached. Is this a bug or is there something that can be done? Thanks.

<img width="1139" alt="Screenshot 2021-01-29 at 19 03 47" src="https://user-images.githubusercontent.com/78231098/106318056-26615a80-6267-11eb-9474-5ca890b9e75f.png">

**Comment by photopea** [comment]
Hi, Photopea never shows such message. Such words do not exist in our code at all.

I believe this message comes from your browser, or some browser extensions. Could you try Photopea in Incognito mode? If it works, then, some of your browser extensions are causing this issue.

**Comment by photopea** [comment]
I think my last message should solve it, so I will close it now.

**Comment by jhkjhlkhNM** [comment]
Thank you for the input. Will look into the browser and browser extensions.
