### ISSUE TITLE
System busy error downloading the file when a layer that is erased

### ISSUE THREAD

**Issue by sidkpp** [photopea/photopea#2814]
Summary: System busy error downloading the file when we have a layer that is erased

Steps:
-  Create a duplicate of a background layer (layer1)
-  Do some stuff on the duplicate layer (like some filter effects)
- Create another duplicate of background layer (layer2)
-  Now erase some parts of layer 2. 
- Try to download the PSD or export to png. It will give System busy error.

**Comment by photopea** [comment]
Hi, I am not able to reproduce it with your steps :(  Saving always works.

Could you maybe record a short video of what you do?

**Comment by sidkpp** [comment]
It happens when u have multiple files open...say 5 to 10 files ...with the
steps I mentioned. Then u cant save any of the files.

**Comment by photopea** [comment]
I tried opening 10 files and it still works well :(

Can you maybe record a short video of what exactly you are doing? Can you make this problem happen with all browser extensions disabled (extensions could cause such problems).

**Comment by photopea** [comment]
I have to close it because of lack of details.
