### ISSUE TITLE
pt, cm, mm etc.

### ISSUE THREAD

**Issue by AlekseyCheCity** [photopea/photopea#2816]
Hello, Photopea!
First of all want to tell that you made a great tool. Thank you. I have already bought license for 90 days and I am going to renew it in the future and I will definitelly reccomend it to others.

I have created this issue just for add one more vote for adding pt, cm, mm etc. as units, because it's the last reason why I still hold Photoshop on my mac.

Thanks!

**Comment by photopea** [comment]
Hi Aleksey,

you can change the main unit in Edit - Preferences - Ruler Units. Also, whenever you have to enter a size of something (e.g. a new document), you can also choose a unit. Is that what you need?

**Comment by AlekseyCheCity** [comment]
Thank you so much! Yes, this is what I needed.

Do you have some settings for fonts sizing, pt instead of px?

**Comment by photopea** [comment]
a "pt" is 1/72 of an inch, about 0.352778 millimeters.  Is this unit really important? What if I added millimeters for the font size instead?

**Comment by photopea** [comment]
If you set your DPI to 72, 1 px would be 1 millimeter, and you can change the DPI later (resample it).

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by AlekseyCheCity** [comment]
I'm sorry for the delay.
Thank you, this way which you proposed (set DPI to 72) is works good, I see font size in pt units.

> Is this unit really important?
Yes, for me it's really important, because I create pages which will be converted to PDFs and printed, so it's better to work with pt, cm etc. instead of px.

> What if I added millimeters for the font size instead?
It doesn't look as the best solution for me, because, for example, if I need to set font size 12pt it means that I should calculate 12 * 0.352778 and the final code `font-size: 4,233336 mm;` is look as a bad code.
