### ISSUE TITLE
le sigle euro €

### ISSUE THREAD

**Issue by marchande5457** [photopea/photopea#2817]
bonjour

je ne peux plus utiliser le sigle euro, ça fait tout planter avec les polices de caractères. j'ai testé avec Kavavinar ou une autre Hack.
ça marque "fonts not loaded yet". et je ne peux plus modifier le texte.
le signe euro fait tout planter.
je vous donne une copie d'écran avec 1 Cuisine 100€%, ça ne s'affiche plus bien et on ne peut plus travailler
[plantagePhotoshop.pdf](https://github.com/photopea/photopea/files/5911658/plantagePhotoshop.pdf)

**Comment by photopea** [comment]
Hi, I tried to create a text layer with the Heck font and pasted "1 Cuisine 100€%" into it and it worked well. How can I reproduce the error which you describe?

**Comment by marchande5457** [comment]
it hasn't work.i will try tomorrow something else

    Le mardi 2 février 2021, 21:44:36 UTC+1, Estelle Mercier <emercier57@yahoo.fr> a écrit :  
 
  Hello !
thank you to write so soon.I don't know apart to give you my .psd
Estelle in France !!
    Le mardi 2 février 2021, 21:22:36 UTC+1, Photopea <notifications@github.com> a écrit :  
 
 


Hi, I tried to create a text layer with the Heck font and pasted "1 Cuisine 100€%" into it and it worked well. How can I reproduce the error which you describe?

**Comment by photopea** [comment]
How do you type "€" on your keyboard? How many keys do you click and how many times? Is there any other temporary character on the screen while you type "€"?

**Comment by marchande5457** [comment]
hello !I am engineer in computing.so I tried different things.
when i use Kavivanar font it doesn't work .before, i used Kavivanar font and it has work very well to enter €.now it is a bug / impossible.and after i used kavivanar, i can't write anything on any font after. i have the same message. 
i must say also that my .psd was KO once time. after i tried to open documents photopea open always the same with error. so i remove all the cookies and after i can open all the documents. it was linked with the problem of euro that made a big problem at the same time.
so i press on "alt gr" and the e on a keybord azerty, at the same time.there is no other temporary character
Estelle
    Le mercredi 3 février 2021, 08:33:34 UTC+1, Photopea <notifications@github.com> a écrit :  
 
 


How do you type "€" on your keyboard? How many keys do you click and how many times? Is there any other temporary character on the screen while you type "€"?

**Comment by photopea** [comment]
Hi, I created  a text layer with the Kavivanar font, and pressed AltGr + E, and everything seems to work.

Could you maybe describe the steps what I should do, to make the bug happen? Or record a video of what exactly you do.

![image](https://user-images.githubusercontent.com/15955558/106793268-88e79b80-6657-11eb-8fd8-9fc0360173c7.png)

**Comment by photopea** [comment]
Also, make sure you updated your browser and disable all extensions, as described here: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by marchande5457** [comment]
voici ce que j'ai quand ça plante après :
normalement dns ce fichier il y a une image mais non :



    Le mercredi 3 février 2021, 20:06:11 UTC+1, Estelle Mercier <emercier57@yahoo.fr> a écrit :  
 
  i has the same problem with another font. and all is ko.when i open a psd it opens always the same, because of euro.how can I make a video ? after it is too big for sending into a mail
    Le mercredi 3 février 2021, 19:57:57 UTC+1, Photopea <notifications@github.com> a écrit :  
 
 


Hi, I created a text layer with the Kavivanar font, and pressed AltGr + E, and everything seems to work.

Could you maybe describe the steps what I should do, to make the bug happen? Or record a video of what exactly you do.

**Comment by marchande5457** [comment]
i has the same problem with another font. and all is ko.when i open a psd it opens always the same, because of euro.how can I make a video ? after it is too big for sending into a mail
    Le mercredi 3 février 2021, 19:57:57 UTC+1, Photopea <notifications@github.com> a écrit :  
 
 


Hi, I created a text layer with the Kavivanar font, and pressed AltGr + E, and everything seems to work.

Could you maybe describe the steps what I should do, to make the bug happen? Or record a video of what exactly you do.

**Comment by marchande5457** [comment]
yes i test it on another project, a new, and it is ok. i have the problem only on one document. but how can i give you the psd ? 9 MB
Estelle
    Le mercredi 3 février 2021, 20:13:56 UTC+1, Estelle Mercier <emercier57@yahoo.fr> a écrit :  
 
  voici ce que j'ai quand ça plante après :
normalement dns ce fichier il y a une image mais non :



    Le mercredi 3 février 2021, 20:06:11 UTC+1, Estelle Mercier <emercier57@yahoo.fr> a écrit :  
 
  i has the same problem with another font. and all is ko.when i open a psd it opens always the same, because of euro.how can I make a video ? after it is too big for sending into a mail
    Le mercredi 3 février 2021, 19:57:57 UTC+1, Photopea <notifications@github.com> a écrit :  
 
 


Hi, I created a text layer with the Kavivanar font, and pressed AltGr + E, and everything seems to work.

Could you maybe describe the steps what I should do, to make the bug happen? Or record a video of what exactly you do.

**Comment by marchande5457** [comment]
i have copied all the photos in a new document. i use another font to write a new text.but the problem is arrived with the key space or " , " i don't remember.and i have two problems now at least
when i double click on the text, i have the same message "fonts not loaded"i can't click or do anything 

    Le mercredi 3 février 2021, 20:31:47 UTC+1, Estelle Mercier <emercier57@yahoo.fr> a écrit :  
 
  yes i test it on another project, a new, and it is ok. i have the problem only on one document. but how can i give you the psd ? 9 MB
Estelle
    Le mercredi 3 février 2021, 20:13:56 UTC+1, Estelle Mercier <emercier57@yahoo.fr> a écrit :  
 
  voici ce que j'ai quand ça plante après :
normalement dns ce fichier il y a une image mais non :



    Le mercredi 3 février 2021, 20:06:11 UTC+1, Estelle Mercier <emercier57@yahoo.fr> a écrit :  
 
  i has the same problem with another font. and all is ko.when i open a psd it opens always the same, because of euro.how can I make a video ? after it is too big for sending into a mail
    Le mercredi 3 février 2021, 19:57:57 UTC+1, Photopea <notifications@github.com> a écrit :  
 
 


Hi, I created a text layer with the Kavivanar font, and pressed AltGr + E, and everything seems to work.

Could you maybe describe the steps what I should do, to make the bug happen? Or record a video of what exactly you do.

**Comment by marchande5457** [comment]
texte too long ? 
    Le mercredi 3 février 2021, 20:56:51 UTC+1, Estelle Mercier <emercier57@yahoo.fr> a écrit :  
 
  i have copied all the photos in a new document. i use another font to write a new text.but the problem is arrived with the key space or " , " i don't remember.and i have two problems now at least
when i double click on the text, i have the same message "fonts not loaded"i can't click or do anything 

    Le mercredi 3 février 2021, 20:31:47 UTC+1, Estelle Mercier <emercier57@yahoo.fr> a écrit :  
 
  yes i test it on another project, a new, and it is ok. i have the problem only on one document. but how can i give you the psd ? 9 MB
Estelle
    Le mercredi 3 février 2021, 20:13:56 UTC+1, Estelle Mercier <emercier57@yahoo.fr> a écrit :  
 
  voici ce que j'ai quand ça plante après :
normalement dns ce fichier il y a une image mais non :



    Le mercredi 3 février 2021, 20:06:11 UTC+1, Estelle Mercier <emercier57@yahoo.fr> a écrit :  
 
  i has the same problem with another font. and all is ko.when i open a psd it opens always the same, because of euro.how can I make a video ? after it is too big for sending into a mail
    Le mercredi 3 février 2021, 19:57:57 UTC+1, Photopea <notifications@github.com> a écrit :  
 
 


Hi, I created a text layer with the Kavivanar font, and pressed AltGr + E, and everything seems to work.

Could you maybe describe the steps what I should do, to make the bug happen? Or record a video of what exactly you do.

**Comment by photopea** [comment]
I still need to be able to make the problem happen myself. Otherwise, I can not help you, if I can not see the problem myself.

You can send me your PSD to support@photopea.com and describe, what should I do to see the problem.

**Comment by photopea** [comment]
There really was a bug, which happened only for long text, which contained non-english characters.

I fixed the bug and it should work well now.

**Comment by marchande5457** [comment]
hello !
thank you so much. i have not seen .I have made with an other option, two texts instead one.
Estelle
    Le mercredi 3 février 2021, 21:32:56 UTC+1, Photopea <notifications@github.com> a écrit :  
 
 


Closed #2817.
