### ISSUE TITLE
published to psd struck at loading

### ISSUE THREAD

**Issue by helixtech** [photopea/photopea#2818]
I had a student share a published to psd link with me and when I click on link it hangs at loading... I then sent him one I created and it opened fine. I then sent the students link to another teacher and they opened it with out a problem. The crazy thing is, it was working fine for me yesterday. Was looking for any kind of help with this

**Comment by photopea** [comment]
Can you tell me that link, so that I can try it myself? The PSD link should either open for everybody, or for nobody.

Note, that your PSDs could be deleted after six months. Do not use this feature as a reliable storage for your work.

**Comment by helixtech** [comment]
https://www.photopea.com/#iorwMEVN4

**Comment by photopea** [comment]
I can load your document without any problems. What happens when you load it? Can you open it in the Incognito mode?

**Comment by helixtech** [comment]
It just says loading, on all my browsers

**Comment by photopea** [comment]
Have you tried the Incognito mode?

**Comment by helixtech** [comment]
Yes, I did. And theee different browsers.the crazy thing is it worked two
days ago when I was showing my class

**Comment by photopea** [comment]
Do you see any errors in the web console? Maybe your internet provider is blocking the website of our storage partner.

Can you open it on your phone (so that it is through a different internet provider)?

**Comment by helixtech** [comment]
view-source:https://www.photopea.com/#iorwMEVN4

**Comment by helixtech** [comment]
So I tried my phone with my house wifi off and it opened

**Comment by photopea** [comment]
Are both your phone and computer on the same wifi, and it works on one, but not on another?

**Comment by helixtech** [comment]
When I use WiFi on phone it won’t open. Cellular service it works fine

**Comment by photopea** [comment]
Can you open https://www.backblaze.com/ ? If not, ask your internet provider to fix it.

**Comment by helixtech** [comment]
Are you sure you want me to open that link? cause that worked

**Comment by photopea** [comment]
Can you also open https://f000.backblazeb2.com/file/psdshared/orwMEVN4 ?

**Comment by helixtech** [comment]
nope, says site cant provide a secure connection

**Comment by photopea** [comment]
Maybe ask your internet provider what is the problem. It works for me and should work for every person with an internet connection.

**Comment by helixtech** [comment]
thanks for helping, strange it worked Monday

**Comment by photopea** [comment]
I have to close it because of lack of details.
