### ISSUE TITLE
Zoomed out workspace, now everything is small

### ISSUE THREAD

**Issue by HeavyScout** [photopea/photopea#2819]
I accidentally hit a stray key (or some combination of keys,) and the workspace, icons and all, shrunk to a level I can barely see, leaving way too much canvas room. I was wondering if anyone knew how to fix this situation, because I've tried everything, and it's not reverting back to the normal size.

Edit: Figured out what was wrong, if it happens to you randomly, you probably changed the website zoom setting. I apologize for my stupidity.

**Comment by photopea** [comment]
I think you changed the zoom of a webpage in your browser. Go into the browser menu and set it back to 100%.

If you use Google Chrome, see here: https://support.google.com/chrome/answer/96810
