### ISSUE TITLE
Photo Filter using always red

### ISSUE THREAD

**Issue by imms93** [photopea/photopea#282]
There's a problem with Photo Filter adjustment layer: no matter what color I choose as foreground and background, the layer it creates is always red. There's no possibility to choose the color of the filter and I can't regulate the density of the filter. Here's a gif of what happens:
![gif](https://user-images.githubusercontent.com/30982542/31718933-f09f3ba8-b411-11e7-893b-e8696b013c1e.gif)

**Comment by photopea** [comment]
Hi, it was fixed, thanks for pointing it out! :)
