### ISSUE TITLE
Bug when opening images from Device

### ISSUE THREAD

**Issue by moraisgs** [photopea/photopea#2820]
Every time I try to open an image or archive from my Device the app crashes. There's no way to dragging or copy/paste these images as well. It is a crucial feature for the means I use Photopea and this problem makes the usage inviable.

**Comment by photopea** [comment]
Hi, how large files are you opening? Can you open e.g. a JPG image in Photopea, which is smaller than 1 MB?

**Comment by photopea** [comment]
I have to close it because of lack of details.
