### ISSUE TITLE
Background colour dropdown is mis-labeled

### ISSUE THREAD

**Issue by dex-k** [photopea/photopea#2821]
In the New Project window, the "Background" dropdown menu has options "White", "Transparent" and "Background" instead of, presumably, "Black".

![image](https://user-images.githubusercontent.com/15846679/106744926-834c7e80-6674-11eb-8a20-3853ffbf585b.png)

**Comment by photopea** [comment]
Hi, the value "Background" corresponds to the color you have set as the Background color.

You can find two colors at the bottom of a toolbar (on the left side). The one in front is called the Foreground color, and the one at the back is called the Background color.
