### ISSUE TITLE
Can't open saved files

### ISSUE THREAD

**Issue by castlemanj** [photopea/photopea#2822]
Recently I can no longer open saved files using the unique URLs given when published as PSDs online. I've tried on two different devices, tried using different browsers, tried in incognito mode, tried clearing the cache for the website, and still have the same issue. Please advise.

Thank you.

**Comment by photopea** [comment]
Hi, can you access this URL and download a file?  https://f000.backblazeb2.com/file/psdshared/orwMEVN4 

That is a domain of our storage partner and maybe your internet provider is blocking it.

**Comment by castlemanj** [comment]
No can't access. My browser says it's blocked. Is there any way around that?

**Comment by castlemanj** [comment]
It says "cant provide secure connection" ERR_SSL_PROTOCOL_ERROR

**Comment by photopea** [comment]
What browser are you using? Can you ask the creators of your browser to fix it, or try another browser?

**Comment by castlemanj** [comment]
I'm using Chrome. I tried on Safari and it didn't work there either. I can try Firefox and see if that works, and I'll try asking Chrome if it can be resolved.

**Comment by photopea** [comment]
What country are you in? Do you use any antivirus or other software, that could be blocking websites?

Ask your internet provider, why they don't let you access this URL: https://f000.backblazeb2.com/file/psdshared/orwMEVN4

**Comment by photopea** [comment]
I have to close it because of lack of details.
