### ISSUE TITLE
Cannot save the edited image

### ISSUE THREAD

**Issue by nicksourav** [photopea/photopea#2823]
Hi,

I cannot save the image after editing on photopea platform.
When I trying to save the image the browser going to not responding and it's hanged.
I have cleared all my cache memories of my browser but still, it's happening the same issue.

Sharing the screenshot for your reference
The issue is happening from the last 7days Please help me to solve the issue. 
![1](https://user-images.githubusercontent.com/78540468/106888619-d6721000-670c-11eb-85e4-fc3cda457285.jpg)

**Comment by photopea** [comment]
What exactly happens when you press Save?

I downloaded the latest Firefox, it saves files into my Downloads folder, without any message in between (so it seems like nothing happens).

**Comment by photopea** [comment]
I have to close it because of lack of details.
