### ISSUE TITLE
Double click on locked layer freezes photopea

### ISSUE THREAD

**Issue by LPW00** [photopea/photopea#2824]
So what the issue is, is that when an imported psd has locked layers and you equip the move-tool with auto-select enabled, and you repeatedly click on an object in a locked layer, after telling you the layer is locked, photopea becomes unusable. You can still equip different tools, but everything else is not working until you reload the site, meaning you lose all progress.

I hope this doesn't read like gibberish, it's hard to explain.

I'm on a windows 10 machine with firefox 85.0.

**Comment by hxim** [comment]
I have similar(same?) problem when I double clicked on locked text layer with Move Tool
![image](https://user-images.githubusercontent.com/6370548/107021308-42ec1e00-67a4-11eb-823f-65074357c88e.png)

**Comment by photopea** [comment]
Hi, I have fixed it, thanks for reporting it! :)
