### ISSUE TITLE
I cannot save my GIF, please help.

### ISSUE THREAD

**Issue by Drew-art-droid** [photopea/photopea#2825]
I am currently unable to export a GIF, each time I try to, it opens a window telling me I have to reduce it by 50%, then it crashes, it is only 800 by 800. Can you please explain the issue further to me, thank you for reading.

**Comment by photopea** [comment]
Hi, how many layers do you have? Is it over 100? Maybe it crashes, because your device does not have enough memory. Are you doing it on an old phone?

Try to update your browser or your operating system.

**Comment by photopea** [comment]
I have to close it because of lack of details.
