### ISSUE TITLE
the transform controls and distances option are broken

### ISSUE THREAD

**Issue by doogadooga** [photopea/photopea#2826]
![image](https://user-images.githubusercontent.com/78573464/106973848-81cc9600-6708-11eb-8445-0d881cefb8d9.png)
![image](https://user-images.githubusercontent.com/78573464/106973937-ae80ad80-6708-11eb-9c5d-885bdea3de34.png)
unsure as to if this is a known issue or not, but it's been affecting my workflow.

**Comment by photopea** [comment]
Hi, can you update your web browser and disable all browser extensions? Does this still happen?

**Comment by doogadooga** [comment]
> Hi, can you update your web browser and disable all browser extensions? Does this still happen?

i did, i actually updated chrome earlier today and it worked fine without a problem. dunno why it started doing that but i updated it again and it works fine now. as for extensions, i doubt that's a problem considering the only extention that i have is a youtube adblocker. next time it happens i'll try that as well.

**Comment by photopea** [comment]
Ok let me know if it happens again. I will close it for now.

**Comment by doogadooga** [comment]
sd
