### ISSUE TITLE
Outline on a vector mask

### ISSUE THREAD

**Issue by cvmh** [photopea/photopea#2827]
Hello,
I have an issue when I apply an outline on a vector mask. 
For example, if the mask is circular on a square layer, the outline effect is square and not circular.

**Comment by photopea** [comment]
Hi, what is an outline and how do you apply it?

**Comment by cvmh** [comment]
Hi,
Sorry for my english (I'm french). An outline is a contour.
Here is a screen shot. The mask is circular. On Photoshop, the contour is circular as it should be. On Photopea the contour follows the original layer (square)
![contour](https://user-images.githubusercontent.com/11349320/107011512-07e3ed80-6798-11eb-9e3c-f6b5dc7a24d0.jpg)

**Comment by photopea** [comment]
It should be fixed now, thanks for reporting!
