### ISSUE TITLE
ZigZag Distortion filter

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2829]
Hi,
I have some PSD template for sketch text.
It use ZigZag filter for better hand draw effect.
Is it possible to have that filter in Photopea?

Here is a file to test https://graphicburger.com/sketch-text-effect-psd/
PS. (surface blur in Photopea look a little bit different than in Photoshop, but I don't know is it not a ZigZag problem)

**Comment by photopea** [comment]
Hi, I added this filter.  Also, I switched to another algorithm for Stroke layer effect, which produces smoother strokes than Photoshop.
![image](https://user-images.githubusercontent.com/15955558/107122277-12d17780-6897-11eb-9037-09f91dd8f42c.png)

**Comment by MichalSZZ** [comment]
Thank you! Looks great.
