### ISSUE TITLE
Cannot edit raster mask for smart filters

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2830]
The raster mask that is available for controlling the transparency of smart filters on smart objects doesn't respond to simple clicks and cannot be edited.

## Steps to reproduce
1. After confirming that extensions are disabled, open a new document with a white background in Photopea.
2. Switch the foreground color to black and draw something with the freehand brush tool.
3. Convert the layer to a smart object.
4. Apply a Gaussian Blur with a radius of 7.2 px. (The kind of filter and the parameters don't actually make a difference.)
5. Click the raster mask icon for the smart filter. With the freehand brush tool, attempt to unblur a part of the scribble from step 2 by drawing over it.
6. While holding down the alt key, click the mask icon.

## Expected result
The outline indicating which layer/mask is in focus switches to the raster mask. A part of the scribble from step 2 becomes sharp again after step 5. After step 6, the raster mask's contents appear, showing another black mark.

## Actual result
The outline stays on the layer and the layer continues to stay active in the workspace. Nothing happens to the scribble from step 2. (The "Smart Object must be rasterized first" warning appears.) Step 6 fails to make the mask active.
![image](https://user-images.githubusercontent.com/51429646/107067925-f279be00-67ad-11eb-9349-70ff2227952d.png)

## Additional notes
Turning off the visibility of the smart filters using the eye icon works normally. Shift-clicking the mask icon (or right-clicking the icon and choosing "Disable Filter Mask") makes the red X appear, so it seems to work normally.

**Comment by photopea** [comment]
Wow, that is quite a serious bug! I fixed it.

**Comment by dentistformyeye** [comment]
Thanks for fixing it. I'm not sure if this is related to it or whether this was an issue before, but I found a smaller bug with alt-click on raster masks on layers. Alt-click makes the mask active, and alt-clicking again makes the layer active again. However, if I replace the second alt-click with a normal click instead, alt-clicking afterward fails to display the mask.
1. Add a new raster mask to a layer. Alt-click the raster mask icon in the Layers panel.
2. Click the mask icon without holding any keys.
3. Alt-click the mask icon again. (Fails to display the raster mask in the workspace.)
If the mask is a layer's raster mask rather than a smart object's filter mask, clicking the mask again (regardless of whether alt is held down) will make alt-click work properly afterward.

If the mask is a smart object's filter mask, there's a simpler way to make alt-click fail.
1. Add a filter to a new smart object to create a filter mask. Click the mask icon in the Layers panel to make the outline switch to the filter mask icon.
![image](https://user-images.githubusercontent.com/51429646/107103755-c3367180-67ec-11eb-860b-0a8b17c87736.png)

2. Alt-click the filter mask icon.
To make alt-click work again, click the filter mask icon without holding any keys twice to make the outline switch from and back to the layer icon.

**Comment by photopea** [comment]
I fixed that too :)

**Comment by dentistformyeye** [comment]
Thank you!
There is one more thing, an interaction between filter masks and layer masks. I'm not sure what is considered normal behavior in this case, so I'll see what you decide:
1. Make a new smart object. Add a filter to create a filter mask. Add a layer mask.
2. Draw something different on each mask so they will be easy to tell apart. For example, I drew a vertical line on the filter mask and a horizontal line on the layer mask.
![image](https://user-images.githubusercontent.com/51429646/107128687-b584f880-688d-11eb-9ff3-76626e310eb2.png)

3. Alt-click one of the masks. Then click the other mask without holding any keys.

Regardless of which mask you start with, the visibility of all channels turns off.
(If I alt-click the filter mask and click the layer mask, the layer mask appears in the Channels panel.)
![image](https://user-images.githubusercontent.com/51429646/107128876-3abcdd00-688f-11eb-8d19-2b6903aad77a.png)
(If I alt-click the layer mask instead, the filter mask appears in the Channels panel.)
![image](https://user-images.githubusercontent.com/51429646/107128910-7c4d8800-688f-11eb-8120-251c2033a478.png)

Alternative behavior could be that the normal click automatically cancels the alt-click's effect, so that whichever mask is clicked last displays in the workspace, i.e. its channel visibility is turned on.

**Comment by photopea** [comment]
I am very sorry, it should be fixed now.

**Comment by dentistformyeye** [comment]
No need to apologize. Thank you for your hard work and responsiveness.
