### ISSUE TITLE
Feature request: Remember folder location in Chrome OS

### ISSUE THREAD

**Issue by gfalken** [photopea/photopea#2833]
Hi. It would be a huge time saver if file opens and saves returned to the last used folder in My Drive (Chrome OS) . As it is now, it defaults to the download folder every time. Thanks.

**Comment by photopea** [comment]
Hi, the saving mechanism can be modified in the settings of your web browser. For Chrome, see here: https://support.google.com/chrome/answer/95759?co=GENIE.Platform%3DDesktop&hl=en

I recommend enabling "Ask where to save each file before downloading".

There is nothing a website can do about file opening and saving mechanism. The only thing you can do is to change the settings of your web browser.

**Comment by gfalken** [comment]
I kind of figured that. It just feels like I'm endlessly clicking through folders while editing images. I'll try changing the default to somewhere a little closer to where I need to go. Thanks for answering.

**Comment by photopea** [comment]
I think the browser should always take you to the last folder, that you used before.
