### ISSUE TITLE
text not showing up

### ISSUE THREAD

**Issue by carmencusiter** [photopea/photopea#2835]
my font is black, the background is plain white, and it won't show up. this has been happening for about three weeks now. please help me fix asap
<img width="1440" alt="Screen Shot 2021-02-05 at 6 49 42 PM" src="https://user-images.githubusercontent.com/78629898/107106899-ef4cf500-67e2-11eb-9217-ede4d37206b0.png">

**Comment by photopea** [comment]
Hi, could you try to delete all your browser extensions, if you have any?

**Comment by carmencusiter** [comment]
i don’t think i have any

**Comment by photopea** [comment]
Is your Safari updated? Photopea may not work well in browsers, that are more than four years old.

**Comment by carmencusiter** [comment]
yes it is, this is a new computer i just got for christmas

**Comment by photopea** [comment]
That is weird. Can you use the Ellipse tool to draw Ellipses?

**Comment by carmencusiter** [comment]
yes, both work fine

**Comment by dentistformyeye** [comment]
Is that h logo to the left of the address bar an extension?

**Comment by carmencusiter** [comment]
it is! i didn't know that. i just removed it, let me try now

**Comment by carmencusiter** [comment]
still not working :( that was my only extension

**Comment by photopea** [comment]
After you type a text, can you right-click Photopea somewhere and choose "Inspect Element"? Then, switch to "Console". Can you see any error messages in that console?

**Comment by carmencusiter** [comment]
i don’t see inspect element

**Comment by dentistformyeye** [comment]
Right-click in the empty space below the ad so that the browser's menu, not the Photopea menu, appears.

**Comment by photopea** [comment]
I have to close it because of lack of details.
