### ISSUE TITLE
Content aware fill on rotated image with unusual dimensions may fail

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2836]
Content aware fill on rotated images that have unusual dimensions and that are cropped to include all non-transparent pixels can fail with an error printed in the console.
![image](https://user-images.githubusercontent.com/51429646/107108921-da378c80-6809-11eb-9ad8-363bcede8a40.png)

## Steps to reproduce
1. After confirming that extensions are disabled, open this image in Photopea. The image is 1535 x 1023.
https://user-images.githubusercontent.com/51429646/107108895-a9efee00-6809-11eb-83a1-06b493397155.png
2. Use Edit > Free Transform. Set the angle of the transformation to 16.0 degrees. Confirm the transformation.
![image](https://user-images.githubusercontent.com/51429646/107109688-5fbe3b00-6810-11eb-870f-c71d0f4b4045.png)

3. Switch to the crop tool. Click Current Layer. Confirm the crop.
![image](https://user-images.githubusercontent.com/51429646/107109174-d86ec880-680b-11eb-93d9-4166d9a7e246.png)

4. Control-click the layer icon in the layers panel to select non-transparent pixels. Press control-shift-i to invert the selection.
5. Choose Edit > Fill. Set the fill mode to Content Aware. Click Ok.
![image](https://user-images.githubusercontent.com/51429646/107109216-3d2a2300-680c-11eb-8ffd-de7ff757a60e.png)

## Additional notes
Skipping step 3 prevents the error from triggering and produces a successful result. 

Making the crop in step 3 just outside of the corners of the image also seems to prevent the error from triggering.
![image](https://user-images.githubusercontent.com/51429646/107109335-98104a00-680d-11eb-8d74-770441ffadd5.png)

This image below doesn't trigger the error and produces a successful result. The image is 1536 x 1024.
https://user-images.githubusercontent.com/51429646/107108926-e7547b80-6809-11eb-9ab6-7cddfbe7f0da.png

**Comment by photopea** [comment]
I fixed it, thanks for reporting!  BTW. it is always good if you select also a contour of an object a bit (so that the unselected part has no semi-transparent pixels).

**Comment by dentistformyeye** [comment]
Thanks for the fix!
