### ISSUE TITLE
Content-Aware Scale not working

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2838]
I clicked on Content-Aware Scale and nothing happend. Error is shown in console:

Uncaught TypeError: Cannot read property '0' of null
    at Z.jp.Z.t.Lw (pp.js:5599)
    at Z.jp.Z.t.enable (pp.js:5588)
    at gY.yo (pp.js:11370)
    at gY.cV (pp.js:11304)
    at gY.g3.f (pp.js:9)
    at gY.dI.f (pp.js:8031)
    at gi.dI.f (pp.js:8031)
    at ip.dI.f (pp.js:8031)
    at ip.ZO (pp.js:8052)

To reproduce:
1. Open photopea
2. Open New project - Create
3. Unlock "Background" layer
4. Select all with CTRL+A
5. In menu select Edit - Content-Aware Scale
6. Content-Aware Scale not working and error appears

**Comment by dentistformyeye** [comment]
The error also happens with different selection tools and sizes.
Workaround: skip step 4. From then on, Content-Aware Scale will work with selections until you refresh Photopea, even if you open another project or return to an earlier history state.

**Comment by photopea** [comment]
Hi, I made the content-aware scale work with selections.
