### ISSUE TITLE
Photopea Select Tool Bug

### ISSUE THREAD

**Issue by coolcraftnet18** [photopea/photopea#2839]
[Video](https://drive.google.com/file/d/1Iu7URtWxcf5Iy8nFpP8QGo4cD4HguQW4/view?usp=sharing) 
![image](https://user-images.githubusercontent.com/18317131/107133771-b6cc1a80-68b9-11eb-8a51-4db8319a0478.png)
I try to color or clear a selection and nothing happens, or I'll just get a red overlay
Edit: Copy and paste is not working either

**Comment by photopea** [comment]
Hi, I think that is a correct behaviour in your video. What else do you want to happen when you do this?

I recommend you to learn about selections: https://www.photopea.com/learn/selections

**Comment by photopea** [comment]
I have to close it because of lack of details.
