### ISSUE TITLE
exported psd wont load in gimp

### ISSUE THREAD

**Issue by TricoCosmic** [photopea/photopea#284]
Opening 'C:\Users\p\Documents\Computing & Networking, Year 2\Work Based Project\Moon wireframe kit-sketch.psd' failed: Error loading PSD file: Unsupported compression mode: 8320

![photpea gimp psd load error](https://user-images.githubusercontent.com/32955560/31815919-253ccf04-b586-11e7-9f6a-9ab97a97bc30.png)

[convert sketch to psd to gimp.zip](https://github.com/photopea/photopea/files/1401530/convert.sketch.to.psd.to.gimp.zip)

**Comment by photopea** [comment]
Hi, did you try to open that PSD in Photopea or in Photoshop?  Did it work?

Can you open all PSDs made with Photoshop in GIMP?

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by Natetronn** [comment]
I'm running into this issue and similar ones where saving PSD from Photopea won't open in GIMP. It's able to open in Photoshop, however. I'd like to help troubleshoot this issue if you still willing.

**Comment by photopea** [comment]
@Natetronn have you tried to report it to Gimp? I believe our PSDs are correct and it is a bug in Gimp.

**Comment by Natetronn** [comment]
Thanks for the reply. Now that I've done a bit more research, it would appear you are correct. Sounds like it's less of a bug and more like a lack of implementation for anything other than basic layers and text.
