### ISSUE TITLE
Pressure sens on linux

### ISSUE THREAD

**Issue by Robiimadot** [photopea/photopea#2841]
My XPPen G430S's driver works because in GIMP it alows me to draw light lines, but when i try it in Photopea i can't use pressure sensitivity. my linux distro is pop os.

**Comment by photopea** [comment]
Photopea asks a browser about the pen pressure, and it is up to a browser to communicate with the hardware and detect these values.

What browser do you use? Can you update it or try another one?

**Comment by photopea** [comment]
I have to close it because of lack of details.
