### ISSUE TITLE
Some layers (and groups) cannot be selected (console errors)

### ISSUE THREAD

**Issue by powerslave** [photopea/photopea#2842]
repro: 
* open template `Simple YouTube Thumbnail`
* try to select layer `Border`, or text layer `Tutorial` or `THUMBNAIL` via Layers panel

-> ❌ cannot be selected.  
Console error: `pp.js:6960 Uncaught TypeError: Cannot read property 'placed' of undefined`

* Same error when trying to select any group.
* Not all layers are affected: Certain layers (e.g. layer `8` in Particles) are selectable
* Found in Chrome Version 88.0.4324.104 (Official Build) (64-bit) on Windows 10.
* Same behavior also on Firefox (console errors are different).

**Comment by photopea** [comment]
Hi, i am very sorry, it should be fixed now. Try to reload Photopea multiple times (to be sure your browser is not caching an old version).

**Comment by powerslave** [comment]
Wow, what a fast fix! 🚀

✔ Can confirm problem is fixed for me. Thanks a ton!
