### ISSUE TITLE
Cannot select layers in PSD file.

### ISSUE THREAD

**Issue by kacieisokay** [photopea/photopea#2843]
Whenever I open up a PSD file, I cannot change which layer I have selected. I can change the visibility, but that is it.

**Comment by photopea** [comment]
Can you reload Photopea several times and try it again?

**Comment by kacieisokay** [comment]
I have reloaded multiple times, and tried with multiple files. It is still not working.

**Comment by photopea** [comment]
Could you send me your PSD to support@photopea.com and describe what should I click?

**Comment by kacieisokay** [comment]
I have sent it. For me, it will not allow me to select other layers, or move them to other files.

**Comment by photopea** [comment]
Hi, I can select all layers in your file. Can you reload Photopea with Shift+F5? I mean reloading a website, not opening your file again.

**Comment by kacieisokay** [comment]
I have tried reloading multiple times, but it will not work in chrome. It does work in firefox, though.

**Comment by photopea** [comment]
I still think that Chrome is showing you the old version of Photopea. Click into the address bar (where www.Photopea.com is written) and press Shift+F5. That should fix it.
