### ISSUE TITLE
Image only green channel in photopea

### ISSUE THREAD

**Issue by mrklondon** [photopea/photopea#2845]
I am loading an image into Photopea and when I do this, only the green channel is loading. I have tried the file in other photo editing software and it works fine, but my students are using Photopea to do their edits so don't have access to any other software. The image also loads properly in preview on safari. The issue occurs in chome and safari. 

I have attached an image to illustrate the issue. 
<img width="1121" alt="Screenshot 2021-02-08 at 09 57 12" src="https://user-images.githubusercontent.com/78728949/107204063-26debb80-69f4-11eb-983c-311283ee0cf4.png">

**Comment by photopea** [comment]
Hi, could you send me your file to support@photopea.com ?

**Comment by mrklondon** [comment]
Have just sent the original cr2 file as requested,

**Comment by photopea** [comment]
Hi, it should be fixed now.

If possible, try to take your photos in DNG format, which is open and widely supported, instead of CR2, which is proprietary and only Canon knows (and refuses to tell others) what exactly is inside a CR2 file.
