### ISSUE TITLE
new PDF viewer on chrome looks weird

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2847]
Chrome have updated its PDF viewer, and therefore the preview of the PDF export looks weird.
![Screenshot 2021-02-08 at 14 33 54](https://user-images.githubusercontent.com/11801254/107258672-daf33d00-6a1a-11eb-8800-378f4c3e23e1.png)

Maybe there is a parameter on the URL which can only show the page without the page index :/

**Comment by photopea** [comment]
Hi, you can click this button and it will look better.

Otherwise, the only thing we can do is to remove the preview completely, like we do for EMF, DXF and other formats.

![Background](https://user-images.githubusercontent.com/15955558/107268091-fc1e5280-6a47-11eb-8a7d-a8853763aae9.png)

**Comment by avagp** [comment]
Yes, i know i can click the hamburger icon, but i thought it could be a way to set the preview without it.

**Comment by photopea** [comment]
If you click it once, the side menu will never appear.

However, the PDF viewer can only by changed by Chrome developers, so you should report it to Chrome. In Firefox, the PDF preview looks completely different.
