### ISSUE TITLE
Save feature can keep the compressed version?

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2848]
I have been using a lot the new Save as PSD/PSB to compress my files and use less storage space on Google Drive.

But, when i open the file, edit it and then save it, it saves the uncompressed version to the cloud.

There is a way to keep saving the compressed version?

**Comment by photopea** [comment]
Hi, the saving PSD to Google Drive is the same as File - Save as PSD, i.e. no compression.

I tried to omit a preview in all PSD files in the past (to make them smaller), but many people complained, that they can not see a preview of a file in the Google Drive. 

Do you think we should show the compression window dialog every time you press Ctrl+S?

**Comment by avagp** [comment]
No.
But maybe it should be a another key combo to display the save dialog
before saving.

**Comment by photopea** [comment]
Now, if the PSD file has been opened from the Google Drive, the Save PSD/PSB window contains a button "Save to Google Drive".

![image (1)](https://user-images.githubusercontent.com/15955558/110534338-3c442400-811f-11eb-963f-a69c503ac91d.png)

**Comment by photopea** [comment]
For Photopea, PSD and PSB is the same "psd" format. Saving a PSB just adds some "extra sugar" during the PSD export. I would recommend you to avoid using PSB, as you would not need it in practice.

We added the PSB export because of people using PSD plugin for Unity3D. The authors of the plugin decided to handle PSD differently than PSB for some reason.

**Comment by avagp** [comment]
Ok.

But, just to get sure.

When opening a compressed PSD, and then saving it, will keep its
compression??

**Comment by photopea** [comment]
The compression options which you see in "Save PSD/PSB" are available only through that window.

Once Photopea opens a PSD, it does not forgets if it was compressed or not. So opening a compressed PSD is the same as opening a less compressed PSD.

**Comment by avagp** [comment]
So. If you open a compressed psd, and them save it.

It will be saved compressed. Right?

**Comment by photopea** [comment]
Every PSD is always compressed with the RLE compression and contains a preview of a final image.

ZIP compression is better. A PSD with ZIP compression and without a final preview can be generated only through File - Save PSD/PSB.
