### ISSUE TITLE
Stamp Filter (again)

### ISSUE THREAD

**Issue by gerrmalcolm** [photopea/photopea#2849]
Thank you for bringing back the Stamp Filter along with many more filters in the Filter Gallery. I change my image to monochromatic using the Channel Mixer and then I change my foreground and background colors to the default by pressing D. I then go to the Stamp Filter. Prior to the February 7, my image would turn to a black outline with a white background (and this is what it does in Photoshop). Now when I use the Stamp Filter, the color are reversed.  My image has a white outline and the background is black.  It this a bug or is it how the Stamp Filter will work from now on? I attached my images. The first 2 images are done in Photopea and the next 2 images are Photoshop doing the same steps.
![Photopea Stamp Filter](https://user-images.githubusercontent.com/78708814/107267923-5bef0c00-69fc-11eb-9641-b0c188a969dc.png)
![Photopea Stamp Filter 2](https://user-images.githubusercontent.com/78708814/107267924-5c87a280-69fc-11eb-8dde-0bd5964868b0.png)
![Photoshop Stamp Filter](https://user-images.githubusercontent.com/78708814/107267929-5d203900-69fc-11eb-93ff-8bd501915a19.png)
![Photoshop Stamp Filter 2](https://user-images.githubusercontent.com/78708814/107267931-5d203900-69fc-11eb-9c2e-e9f66649a79e.png)

**Comment by photopea** [comment]
Hi, I fixed it, thanks for reporting :)
