### ISSUE TITLE
Channels

### ISSUE THREAD

**Issue by imms93** [photopea/photopea#285]
Here I come asking for more features :D I'd like to recreate in Photopea this tutorial: http://powzie.livejournal.com/3492.html and this tutorial which is a variation of the first but the method is the same: http://elli.livejournal.com/281012.html
The feature I'm asking for is Channels, in Photoshop they're in the Layers panel, and divide the image in three channels: Red, Green and Blue. As usual I suck at explaining things, but I think the tutorials are well-written and explain well how channels work.

**Comment by photopea** [comment]
I think I understand how Channels work. But almost always you can do it without them.

Duplicate your layer. Then, do Image - Adjustments - Black and White. Turn down Red, Cyan, Green to darken the skin. Fix it with Levels. You will get this:  

![](https://i.imgur.com/AYE8nvh.png)

Convert the black color into a selection with Select - Color Range.

**Comment by imms93** [comment]
I'm trying right now with an image with a complex background to see how it works, thanks for the tip! There's another tutorial I'd like to replicate, it's this: https://icon-tutorial.livejournal.com/9445095.html#cutid1 it has features like "convert to shape", "fill path" and "stroke path", it's a tutorial that I really love and I'd like to replicate it in Photopea because my computer is a low-end pc and grinds to a halt whenever I open Photoshop, I can't wait to abandon PS and use Photopea as my go-to editor!

**Comment by photopea** [comment]
We do have "convert to shape", but we don't have "stroke path" yet. But I think that in latest Photoshop, there is a new effect for vector shapes, that strokes the shape. So you would do the same thing differently.

**Comment by photopea** [comment]
What about reading  www.Photopea.com/learn ? I think once you know how it works, it would be easier for you to understand Photopea and Photoshop.

**Comment by photopea** [comment]
Channels are related to Transparency lock, we should add them at once.

**Comment by KyoGrou** [comment]
Hi there,
I'm just wondering how is this feature processing.

**Comment by photopea** [comment]
I did not know how much priority should I give to this, so I focused on other issues.

**Comment by martybrenson** [comment]
Just throwing in a little "me too" in here as well.
I was trying to figure out a way to do 3D Anaglyphs in Photopea, and the only way I knew how was isolating red and blue channels.
Do you think it's possible another way?

**Comment by photopea** [comment]
Channels have been implemented :)

**Comment by KyoGrou** [comment]
Congratulations :)
Thank you for your hard work.

**Comment by theironpaw** [comment]
Legendary!!! Thank you so much for your hard hard work! 
I only just checked back today! so stoked. Works great!
