### ISSUE TITLE
Problems pasting across 2 projects

### ISSUE THREAD

**Issue by ArtLabHydro** [photopea/photopea#2850]
For some reason when I copy a layer from one of my projects and paste it to another project the layer pastes in red and is no longer editable, any attempts to move it instead move a large red background shape. I cant find a solution for this anywhere, what am I doing wrong?

![Photopea Issue 2](https://user-images.githubusercontent.com/78783786/107324294-b029d880-6a5c-11eb-8180-07f3919808ed.PNG)
![Photopea Issue](https://user-images.githubusercontent.com/78783786/107324296-b0c26f00-6a5c-11eb-99b7-196315e8f85c.PNG)

**Comment by MichalSZZ** [comment]
It looks like that in your second project (that with a car) you have a Quick Mask enabled.

You can't see that before you didn't paste something. And you probably doesn't have that pasted layer in layers palette too (it is in separate channel only as a selection)
You can turn off that function by clicking a circle in the left bottom corner (under a foreground and background layer)

![obraz](https://user-images.githubusercontent.com/38118273/107329841-058fd500-6ab1-11eb-9467-2bfa58352db3.png)

**Comment by photopea** [comment]
Exactly, you have a Quick Mask. Learn how the Quick Mask works here: https://www.photopea.com/learn/selections

**Comment by ArtLabHydro** [comment]
Thanks so much for the help!
