### ISSUE TITLE
Shadow/Highlights missing in Adjustment Layers!

### ISSUE THREAD

**Issue by zcraber** [photopea/photopea#2852]
May I know why **Shadow/Highlights** is missing in **Adjustment Layers**?

![image](https://user-images.githubusercontent.com/61133303/107473826-49f5a080-6b97-11eb-95e1-3b5b871a598f.png)

**Comment by dentistformyeye** [comment]
Since Photopea allows you to apply adjustments to smart objects, you could try that in the meantime.

**Comment by zcraber** [comment]
> 
> 
> Since Photopea allows you to apply adjustments to smart objects, you could try that in the meantime.

Yeah, I know that. But wondering why it is the only one missing there!

**Comment by photopea** [comment]
Shadows / Highlights is more like a filter than an adjustment. It takes a lot of time to compute (unlike other adjustments), e.g. one second for a 2000x2000 image. So if there was such adjustment layer, and you were e.g. painting something, it would run at one frame per second. That is there is no Shadows/Highlights adjustment layer in Adobe Photoshop, too.
