### ISSUE TITLE
Grammar corrector within Photopea

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2853]
Chrome has its own corrector which can be used in different web app, but in Photopea is not possible.

Maybe it is completely impossible, but if not, i would like to request it.

Because i work with many many texts, many times i get a wrong spelling and i don't notice it.

BTW, when are going to be the artboards enabled??

I would really like that feature.

**Comment by photopea** [comment]
Hi Alvaro, I am afraid I can not provide the spell check of a web browser in Photopea. I would probably have to make my own grammar correction mechanism. You can type text in another window (with a spell-check) and then, copy-paste it into Photopea.

I started to work on the artboard tool yesterday.

**Comment by avagp** [comment]
Thanks!

I do that occasionally, but I still get mistakes because I edit a lot in
the file.

Hope the artboards are ready! For printing and prototyping is a great
addition to photopea!
