### ISSUE TITLE
Shape not centered and smart object names don't update

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2854]
I am trying to center a shape, but the red guides does not fit properly.

And beside, how i can change the names of smart objects??

https://video.drift.com/v/abMePy2O4Il/

**Comment by avagp** [comment]
[Shape 5 copy.zip](https://github.com/photopea/photopea/files/5961817/Shape.5.copy.zip)
 here is the PSD

**Comment by photopea** [comment]
Hi Alvaro, I fixed the issue with centering. Also, you can rename smart objects now :)
