### ISSUE TITLE
GIF's frame time is not accelerated on export?

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2855]
I made a new GIF and i noticed that the frames that indicated a particular time frame (_a_ name, 1000   =  for example) are not accelerated when i export it to 300%  

This is just a perception. But in past times it did not go so stuttered
[Archive.zip](https://github.com/photopea/photopea/files/5962662/Archive.zip)

Am i doing something wrong?

**Comment by photopea** [comment]
Hi, I opened your PSD in Photopea. The last layer has ",1000" at the end of its name. I exported it as a GIF with Speed = 300%.

When I load that GIF into Photopea, the last layer has ",330" at the end of its name. So I think everything works correctly.

**Comment by avagp** [comment]
It is fine, but something did change.

The default delay for a frame was 50ms and now is 100ms

It is fine as is, but you should change it on the learn section
![image](https://user-images.githubusercontent.com/11801254/107712690-9da3df00-6ca8-11eb-8e63-c21cf41ddb4d.png)

Also, maybe you are rounding, but the 1000ms at 300% should be 333ms, not 300ms.

**Comment by photopea** [comment]
I changed the docs, the default delay is 100 ms.

Photopea supports three animation formats: GIF, APNG and WEBP. Each format supports a different precission for the delay. It is not possible to store a delay of 333 ms in a GIF file, so it is rounded to 330 ms (not 300 ms).
