### ISSUE TITLE
Black background not deleting from gfx's (psd packs) 

### ISSUE THREAD

**Issue by Gotiq** [photopea/photopea#2857]
yesterday, when i adding something from gfx to my project it remove the black background, today i want to make some graphics and black background dosen't gone, help

**Comment by photopea** [comment]
Hi, can you describe, how can I reproduce this problem?

**Comment by Gotiq** [comment]
i dont know but  shortcuts wtih ctrl dosen't work too idk what to do

**Comment by Gotiq** [comment]
look at this video



https://user-images.githubusercontent.com/78923053/107673053-e30ae100-6c95-11eb-9e89-bf8ba1fa3194.mp4

 That black background shouldn't be in my file! yesterday it was not there when I added such effects and today it appeared

**Comment by MichalSZZ** [comment]
You must read first about blending modes.
That layers have "screen" or "linear doge" blending mode and when you have transparent layer under your effects it's gave no effect for your project

**Comment by photopea** [comment]
It works this way in Photopea, Photoshop, Gimp and other programs. Read our article about layers and their properties: https://www.photopea.com/learn/layers

**Comment by e3bqarinu** [comment]
You can use this method on this site: https://www.e3bqarinu.com/2021/05/photopea.html
