### ISSUE TITLE
Exported PDFs have doubled dimensions and DPI

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2858]
PDFs exported from Photopea have twice the height, width, and DPI that are shown in the image size and export menus.

1. Make sure that extensions are disabled. Open pea.psd from the Photopea welcome screen.
2. Check Image > Image Size. (Should say 512 px width, 512 px height, and 72.000 DPI.)
3. Choose File > Export as > PDF. Observe the dimensions in the export menu. (Should say 512 px width and 512 px height.)
4. Click Save. Then open the new PDF in Photopea. Check Image Size.

Width becomes 1024 px, height becomes 1024 px, and DPI becomes 144.000.

I tried this with extensions disabled on the latest Chrome version (88.0.4324.150).

**Comment by photopea** [comment]
Hi, there are no pixels in PDF format. There are only inches. All dimensions in a PDF files are described in Inches.

When a program like Photopea loads a PDF, it sees all values in inches, and it can choose, how many pixels it will use to rasterize a PDF page. In this sense, Photopea uses a DPI of 144 for all PDFs.

The important feature is, that the physical size of a document (in inches) is preserved when saving / loading PSD, PDF, JPG, PNG ... 

Your PSD was 512 x 512 at 72 DPI, so it is 7.1 x 7.1 inches.

When you load such PDF into Photopea, Photopea only knows a size of 7.1 x 7.1 inches. There is no 512 or any other pixel size. So no matter what DPI is chosen, the size in inches is always preserved.

**Comment by dentistformyeye** [comment]
Got it. Thanks for the info.
I think it would be good to put a warning about the DPI for PDF exports. I once exported a PDF from Photopea and couldn't import the result back in because the computer ran out of memory. Other online PDF viewers also couldn't view the file; only the browser itself could display the file safely. (I didn't test any other locally installed PDF viewers.) I found out that the original file from before exporting was 5 DPI afterward, but didn't understand what was happening until I read your explanation; it turns out that the exported PDF had effective dimensions of tens of thousands of pixels, even though the exported file's width and height were each below four thousand pixels.
