### ISSUE TITLE
Exporting PNGs for layers in Acrobat

### ISSUE THREAD

**Issue by ellawhite** [photopea/photopea#286]
Hello,

I am trying to create layered PDF documents. For this I am using multiple translucent PNGs with different information to layer on top of one another and then putting them together in Adobe Acrobat pro.  

When I export a translucent layer as a PNG it looks fine, however when I import as layer in adobe acrobat pro the layer is completely black. 

Furthermore, I have found that imported JPEGS with features extracted work fine, however text layers for example created in Photopea are all black when imported as a layer in Acrobat. 

What can I do to fix this?

**Comment by photopea** [comment]
Hi. When you open the PNGs in an image viewer, or in some other program, are they black too?

What do you mean by "features exctracted"?  Do you mean exporting text layers as PNGs (the previous problem) ?

**Comment by ellawhite** [comment]
The PNGs look fine in Windows Photo Viewer - the only program I have for opening images in this computer. 

By 'features extracted' I mean if I create some text in paint and save as a JPEG, I can then remove the background manually on Photopea and save as a PNG and that will import into Acrobat fine.
If I create a text layer in Photopea and export as a translucent PNG it looks black when imported into Acrobat.

**Comment by photopea** [comment]
Can you please send us two PNGs, the one that works fine in Acrobat, and the one that is black in Acrobat? You can attach them to the message right here under your comment.

**Comment by ellawhite** [comment]
![png created in photopea](https://user-images.githubusercontent.com/33066297/31964957-bd13c7ce-b8d3-11e7-884c-895e498344b3.png)
![png created elsewhere](https://user-images.githubusercontent.com/33066297/31964958-bfca592e-b8d3-11e7-876d-9630b06176f6.png)

**Comment by photopea** [comment]
So the PNG from Photopea is so-called "palette" PNG, while another one is "direct color" PNG. You can see, that the paletted PNG has only 20 kB, while another one has 111 kB (5x larger).

It seems like there is a bug in Acrobat Pro, so it does not support "palette" PNGs. I would recommend you to report this bug to Adobe, but I am not sure if they can fix it quickly. 

Is it completely black only in Acrobat Pro, or also in a final PDF file?

**Comment by ellawhite** [comment]
It is completely black in the final PDF file. 

How can I save PNGs created in Photopea as a direct color PNG?

**Comment by photopea** [comment]
I can make Photopea always produce direct color PNGs, but they are unnecessarily large, which can be a problem for other users. I can add an option "produce direct-color PNG" into Save for Web window. Will it be sufficient?

**Comment by ellawhite** [comment]
Yes that would be perfect, thank you so much!

**Comment by photopea** [comment]
Ok, so there is a new option "don't use palette" when you export as a PNG. It is just for you! :D  It has no effect on actual colors, but it usually produces slightly larger files. Let me know if these new PNGs work well with Acrobat Pro.

**Comment by ellawhite** [comment]
It works great! Thank you so much and I love this application :)
