### ISSUE TITLE
EMF import bugs

### ISSUE THREAD

**Issue by avonwyss** [photopea/photopea#2860]
I wanted to post this to the UDOC.js repo, but since that has been removed I do it here. I observed some issues importing a EMF:
- When ModifyWorldTransform is used with MWT_IDENTITY, MWT_RIGHTMULTIPLY or MWT_SET, an exception occurs.
- When RestoreDC with -2 or more is used, the import hangs (infinite loop)
- Not tested, but I believe that your code will fail on big-endian machines. EMF is always little-endian, but your code copies the bytes 1:1 into the Uint8Array with the shared buffer and reads the other data types with TypedArrays. The TypedArrays however always use the endianness of the host system, therefore on a big-endian machine all data which is not read byte-by-byte will end up wrong.

**Comment by photopea** [comment]
Hi, please, show us a file, which you can not open in Photopea.

**Comment by avonwyss** [comment]
I sent a file to support@photopea.com.

**Comment by photopea** [comment]
Hi, thanks! I fixed the error, it should work well now.
