### ISSUE TITLE
photopea doesn't respond

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#2862]
I was working on a **small** project, 2000x2000pxl, and about 25 layers, and immediately photopea didn't respond to anything, have been working on this project for 2hours now and I will not reload the site

![Screenshot (82)](https://user-images.githubusercontent.com/70863817/107851994-81be4b80-6e16-11eb-8364-5ed78a31db8c.png)

**Comment by photopea** [comment]
Hi, how can I reproduce this problem?

**Comment by mustafaGFX** [comment]
I noticed that this problem happens when working on vector graphics and when the whole project layers are just vector shapes or at least most of them this problem happens

**Comment by photopea** [comment]
Can you record a video of you reproducing this bug?

**Comment by mustafaGFX** [comment]
I will try to, but I don't think so that it's possible, cus this bug happens suddenly

**Comment by photopea** [comment]
I modified Photopea. The vector-editing steps take much less memory in History. So the memory should not run out that fast.
