### ISSUE TITLE
Something is dreadfully wrong with the site-

### ISSUE THREAD

**Issue by BasicBroom** [photopea/photopea#2864]
I've already restarted my computer and tried using the browser version but every time I use the Hue and saturation tool, it's not giving me a live preview of what I'm doing. I have to keep clicking the preview button just for it to show me something. Not to mention that when I DONT click the preview button to see what I'm changing the color to before sliding the color picker and clicking "OK" it does absolutely nothing to the image. Also It's seeeeeriously lagging for some reason and I just- What is going on. I impute the name of my image onto the thing, I titled it "Garret V. Benson" and saved it to my computer. But when I look at the file it saved it's just titled "Garret V"

Whats going on, I really don't want to have to switch photoshopping sites again.

**Comment by photopea** [comment]
Hi, I am very sorry, it is fixed now.
