### ISSUE TITLE
Sharpness and Blurs Aren't Working Like Normal

### ISSUE THREAD

**Issue by DuckyMacfly** [photopea/photopea#2866]
Hiya, I have noticed that most of the sharpness/blur filters aren't working anymore, the ones that do work are the ones that bring up a window. i.e smart sharpen or blur box. Even then, they are extremely weak compared to what they were before, needing me to put the percentage slide in the thousands to even see a noticeable change. 

I thought maybe it's because I'm using chrome, but this issue also affects microsoft edge. I've tried deleting cookies, refreshing the page, etc. It's not working, unfortunately. Can you please fix it? Thank you. Photopea is a great site and this is the only issue I have faced so far, so hopefully it's resolved. 

Edit: It worked on the 13th of this month, I know this because I used it on a project I was working on. When I try to use the filters now, it doesn't even show up in history and the tab doesn't get clicked away like it normally does. It's as if I haven't clicked on it or something.

**Comment by photopea** [comment]
Hi, I am very sorry, it all should work well now.
