### ISSUE TITLE
Unable to save project as PDG

### ISSUE THREAD

**Issue by wasiasia** [photopea/photopea#2868]
Im not able to save the project as PNG - if im trying, it only save it as .txt.
I checked with other projects - saved as psd, than changing something (like adding a dot) and photopea is trying to save the grafic in .txt 
Please help

**Comment by photopea** [comment]
Hi, you are using a browser extension, which renames your files to .TXT. You should disable that extension, or ask the authors of your extension to fix this problem.

I think most of people do not know what browser extensions they are using and what these extensions do. That is why recommend everyone to remove all browser extensions, as I do.

**Comment by wasiasia** [comment]
Hi, thank you for the answer. What extention are you refering to?
 I have only gmail, google translate and adblock - and I added it before even I started using photopea - since 1 week I have problems with saving projects, and im using photopea over a year. So I dont think that any of my extentions are the problem

**Comment by photopea** [comment]
It is hard to tell which extension does it. But the same problem has been reported here many times, and every time, it was because of a browser extension.

Try to open Photopea in Incognito mode (i.e. without any extensions) and you will see that everything works fine.

**Comment by wasiasia** [comment]
Thanks a lot! Will try.
Have a nice day!
