### ISSUE TITLE
Text spacing changing incorrectly when editing

### ISSUE THREAD

**Issue by Ch0yc3z** [photopea/photopea#2869]
HI there, 

I'm having an issue with a text template originally created in Photoshop. 

There is tabbed spacing in the template between areas of text. When the template is loaded into Photopea it retains the same spacing until I click into the text box to edit it - at this point all of the tabbed spacing areas widen by a great deal. 

I've attached two pictures, before clicking in to edit, and after clicking in to edit:

<img width="412" alt="Screenshot 2021-02-14 at 22 11 40" src="https://user-images.githubusercontent.com/79063457/107890787-a3046200-6f12-11eb-8e60-6eedfa85b45c.png">
<img width="400" alt="Screenshot 2021-02-14 at 22 11 46" src="https://user-images.githubusercontent.com/79063457/107890791-a5ff5280-6f12-11eb-8943-04194d0358e7.png">

**Comment by photopea** [comment]
Hi, could you share your PSD file with us? You can send it to support@photopea.com

**Comment by Ch0yc3z** [comment]
Yes will do now. I've just made a completely new template just to test this issue, results are as follows: 

![Uploading Photopea Testing [PHOTOSHOP CORRECT].png…]()
![Photopea Testing  PHOTOPEA ERROR](https://user-images.githubusercontent.com/79063457/108130742-0e336d00-70a8-11eb-9938-6a5f15c4f891.png)

**Comment by Ch0yc3z** [comment]
![Photopea Testing  PHOTOSHOP CORRECT](https://user-images.githubusercontent.com/79063457/108130809-2905e180-70a8-11eb-83a6-2c7f99f99a94.png)

**Comment by photopea** [comment]
Hi, I implemented it. Be aware of some properties of this formatting (same in Photopea and Photoshop):

- If you increase the text size, the text might become misaligned (because the Tab size is always the same)
- If you change the font, the text might become misaligned
