### ISSUE TITLE
Pasting into a single channel not supported

### ISSUE THREAD

**Issue by Wolfos** [photopea/photopea#2870]
**Steps:**
- Copy a greyscale image
- Select G channel and hide others
- Paste image

**Expected:**
- Greyscale image is copied into the G channel

**Actual:**
- Greyscale image is copied into R, G and B channels

This is required for texture packing.

**Comment by photopea** [comment]
I fixed the problem. If just one channel is selected, the pasted content is pasted only into a selected channel.
