### ISSUE TITLE
Layer effect on folder text does not apply on text when exporting to PDF (with vectorized text) 

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2871]
Pretty much what the title says.

When i export a text with a layer style and i vectorize the text, it gets the effect.

But if the same effect is applied to the folder which contains the text layer, using the same export method does not apply the effect.

**Comment by avagp** [comment]
![Screenshot 2021-02-15 at 15 42 30](https://user-images.githubusercontent.com/11801254/107983385-71d47200-6fa4-11eb-894e-717f522a19d2.png)
![Screenshot 2021-02-15 at 15 41 55](https://user-images.githubusercontent.com/11801254/107983393-7436cc00-6fa4-11eb-9a2a-d78eb3fac940.png)

**Comment by photopea** [comment]
I Implemented it :)
