### ISSUE TITLE
Curves adjustment layer sample droppers not working

### ISSUE THREAD

**Issue by paultsip** [photopea/photopea#2873]
I am trying to white balance an image but the color dropper do not work.

![image](https://user-images.githubusercontent.com/79159869/108094091-4b114c80-7033-11eb-9277-0cdbab013003.png)

**Comment by MichalSZZ** [comment]
In Photopea it works only for adjustments from Image -> Adjustments -> Levels. For a raster graphics or smart objects.
Probably you are using Adjustments Layers. Sadly it doesn't work there.

**Comment by photopea** [comment]
Yes, try using the Adjustment (Image - Adjustment - Levels)  instead of the Adjustment lalyer.
