### ISSUE TITLE
Artboards - can't select with auto selection objects in other artboards when in upper Artboard - object on layer is big

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2877]
https://www.photopea.com/#iXGh7oVK7

In this file try to select (V-move tool) with Auto Select mode a Cyan color rectangle.

It works in that (bad) way with Color Fill layers or Layers with size that are so big, that move to another artboards.

**Comment by photopea** [comment]
fixed, thanks for reporting it :)  Now, if the cursor is above a specific artboard, only layers inside that artboard can be selected.
