### ISSUE TITLE
Artboards - Moving a layer with move tool from one artboard to another

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2878]
https://www.photopea.com/#iXGh7oVK7

1. Use move tool
2. Try to move White rectangle to another artboard

It moves but doesn't show in new artboard

Should jump in to another artboard folder where it actualy is (as a top layer). And should show up on project. (like moving them by dragging in layers pallete - that wors good)

**Comment by Erelynn** [comment]
I tried to do the same thing and it didn't work for me either. I would appreciate this feature too because sometimes I like to take elements from one project and move them to another. It's convenient to get this done by simply dragging them to the other project that I have opened in Photopea.

**Comment by avagp** [comment]
as now, you have to manually move the layer to the artboard folder.

BUT, it would be great to have this feature as default. It will be a breeze to work on Photopea

**Comment by photopea** [comment]
I implemented it! I hope I did not introduce too many new bugs.

**Comment by avagp** [comment]
Hoorray!!

Let's cross the fingers for not having any bugs related :D
![image](https://user-images.githubusercontent.com/11801254/120377488-30659980-c2eb-11eb-8476-d5b1ace9656d.png)

**Comment by avagp** [comment]
Ok, first bug:

On michal's example:
https://www.photopea.com/#iXGh7oVK7

You can successfully move the teal rectangle to the red artboard.

but you cannot move the white one to the blue artboard.

You can neither move back the teal rectangle after moving to the red artboard.

**Comment by photopea** [comment]
fixed :)

**Comment by avagp** [comment]
YESSSSS
