### ISSUE TITLE
Gap between text and last line.

### ISSUE THREAD

**Issue by rossnyvia** [photopea/photopea#288]
![photopea](https://user-images.githubusercontent.com/33109792/32032672-5024a756-b9d6-11e7-80b0-60bfaccc0347.png)

No adjustment of the tracking fixes this. Anybody else experiencing similar issues?

**Comment by rossnyvia** [comment]
Fixed by making a new text box. Weird, but it worked.

**Comment by photopea** [comment]
Could you send us your PSD file to support@photopea.com ?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
