### ISSUE TITLE
Artboards - possibility to move artboards by dragging artboard name or/and with arrows on keyboard

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2880]
That is really useful function. It works in PS with Move tool and Artboard Tool. 

With Alt button I can duplicate artboard (with all content) and move it to another place. But if that is too difficult to You I can make it by duplicating Artboard Folder and then move it With move tool. That is only nice to have feature to primary move artboard tool.

**Comment by photopea** [comment]
I think it is all possible in Photopea now.

In Photopea with the Move tool, you can click anywhere and move selected layers. Also, you can Alt+click anywhere and move a copy of selected layers. An artboard is just a layer, so it works for them, too.
