### ISSUE TITLE
Artboards - "duplicate into" artboard name in project

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2881]
It works by duplicating one layer form Arboard1, to Artboard2 (or any other - user can select it from select input with all artboards name in project). Duplicated layer should copy in that same X and Y place as it was in Artboard1.

It can work also by selecting another project tab and artboards list that are in taht other project.

**Comment by photopea** [comment]
I implemented it!

Also, if there is an artboard among the duplicated layers, the Artboard field is disabled (you can not insert an artboard into another artboard).
