### ISSUE TITLE
Artboards - Alt and click on Plus in circle icon makes new artboards with all layers from old one

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2882]
It is the simple way to make duplicate of one artboard but in the new place (up, down, right, left).

Then user can change dimensions and make for example new banner with other canvas size.
I have 300x600 banner with layers, texts and all in right places. I can Click and duplicate, change to 160x600 px and change places for logo, CTA button and size for paragraph text.

I make duplicate by using Alt with move tool too (by dragging artboard name).

**Comment by photopea** [comment]
I implemented this feature (Alt+ click on Plus to duplicate an artboard).
