### ISSUE TITLE
How can we paste unicode emojis in?

### ISSUE THREAD

**Issue by quantuminformation** [photopea/photopea#2883]
I want to use all my emojis in the psd's. Is there a font we can use?

✉️🔴👥👤🗑️

🇩🇰🇳🇬

🏴󠁧󠁢󠁥󠁮󠁧󠁿 🇨🇳 🇳🇿
🇷🇺🇦🇺
🇳🇱 🇺🇸

🎙🎹
🎼🎵
🎤📽️
🎞️
🍿
🎦🚍🦚💺 
🎥
🎬

🤡

**Comment by photopea** [comment]
Hi, it is the same as with any other characters. You need a font, which contains glyphs for these characters.

E.g. "Source Code Pro" and "Deja Vu Sans" contain some emojis: https://www.photopea.com/#iRCYrQnbJ

In the font menu, enable "Emoji" filter to see only fonts with emojis. Open Window - Glyph, and switch to Emoji, to see all emojis in a current font.

You can load your own TTF / OTF fonts into Photopea, which contain emojis.

![image](https://user-images.githubusercontent.com/15955558/108287456-1a442b00-718b-11eb-933a-68ed9571e5f5.png)

**Comment by photopea** [comment]
There is also an Emoji plugin (Window - More - Emoji), which inserts emojis as SVG smart objects into a current document.

**Comment by eugeniweb** [comment]
@photopea Hi! How to do this in 2025? :)

**Comment by photopea** [comment]
You can use Ctrl+C and Ctrl+V to copy paste text from one place to another.

**Comment by quantuminformation** [comment]
wow 4 years ago was a while back
