### ISSUE TITLE
crashing frequently

### ISSUE THREAD

**Issue by AirGEL** [photopea/photopea#2884]
When ever I try to save a psd after working on something, photopea crashes.
I tried restarting my computer, but that didn't help.

**Comment by photopea** [comment]
Hi, how much RAM memory do you have? Can you look into Window - More - Memory and tell us, how much RAM your document uses?

**Comment by AirGEL** [comment]
idk how much ram my computer has, it says the file uses 167.8 MB

**Comment by photopea** [comment]
Can you update your web browser and disable some browser extensions? Does it still crash?

What browser and version are you using?

**Comment by photopea** [comment]
Also, it would help, if you could describe specific steps, which crash Photopea every time in your case. Then, I could do these steps myself and see, why it is happening.

**Comment by AirGEL** [comment]
I use Firefox and it says it can't update and I don't think I have any extensions.
It only crashes when I try to save as a psd or png, doesn't seem to matter what I do before.

**Comment by photopea** [comment]
So you were never able to save a PSD in Photopea?

Could you at least record a video of what you do in Photopea and how it crashes?

**Comment by AirGEL** [comment]
I was able to save it once, but that was it.
and idk how to record a video of it

**Comment by photopea** [comment]
I will close it now. I really need some clue to make the problem happen on my computer.
