### ISSUE TITLE
Export layers fails after editing artboards

### ISSUE THREAD

**Issue by gabiap** [photopea/photopea#2885]
Hello!

The export layers feature (with the "only export layers that start with "-e-" checkbox enabled) fails for edited artboards (it works if the artboards haven't been touched in the tool at all). 

Console output
`pp.js:430 Uncaught TypeError: Cannot read property 't' of undefined
    at Function.iH.fA (pp.js:430)
    at Function.iH.yz (pp.js:410)
    at Function.hN.nO (pp.js:519)
    at Function.cX.acj (pp.js:729)
    at Function.cX.Eu (pp.js:711)
    at Object.dm.m1.aiF (pp.js:2284)
    at Object.dm.m1.Wu (pp.js:2285)
    at bE.Y6 (pp.js:7412)
    at Function.C.fe.Tf (pp.js:5304)
    at ik.Hc (pp.js:9691)
iH.fA @ pp.js:430
iH.yz @ pp.js:410
hN.nO @ pp.js:519
cX.acj @ pp.js:729
cX.Eu @ pp.js:711
dm.m1.aiF @ pp.js:2284
dm.m1.Wu @ pp.js:2285
bE.Y6 @ pp.js:7412
C.fe.Tf @ pp.js:5304
ik.Hc @ pp.js:9691
hc.f @ pp.js:9
ev.f @ pp.js:8316
fo.s5 @ pp.js:8474`

To replicate:
Open a PSD with artboards created in Photoshop. Delete a folder. Rename the artboard to start with "-e-". Run the export feature.

**Comment by photopea** [comment]
I can not replicate it now. Can you still replicate?

By the way, when you export with File - Export As - PNG, JPG, or GIF, there is an option "Artboards", which will export a file for each artboard.
