### ISSUE TITLE
Photopea Publishing

### ISSUE THREAD

**Issue by MrsSalv** [photopea/photopea#2887]
My students are trying to publish their assignments (File--Publish as PSD) and it just sits at "loading."

**Comment by MichalSZZ** [comment]
Hi. How big is the file? Online publishing have some limits in Mb. Don't know at 100% but it can be 10 or 20 Mb.

**Comment by photopea** [comment]
Uploading a file can take a while, but it should be done in a couple of seconds. Do you have any browser extensions, which could be blocking Photopea? Do you see any errors in the web console?

**Comment by photopea** [comment]
I have to close it because of lack of details.
