### ISSUE TITLE
overlapping windows

### ISSUE THREAD

**Issue by jongottshall** [photopea/photopea#2888]
On Safari, the image window overlaps the tool controls at the top of my screen and makes them unable to be accessed. I've quit Photopea 2x and reopened, with the same issue. I don't see how to reduce the size of the image window (I can enlarge/reduce the image itself, but not the window it's in).
[Overlapping windows.pdf](https://github.com/photopea/photopea/files/5998534/Overlapping.windows.pdf)

**Comment by photopea** [comment]
Hi, what version of Safari is it? Could you maybe update it?

**Comment by photopea** [comment]
I have to close it because of lack of details.
