### ISSUE TITLE
Artboards - new artboard icon (circle with plus) should have always the same size

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2889]
Now that icon have very big size at the start and change the size when user make zoom in and out

**Comment by avagp** [comment]
Like this
![Screenshot 2021-02-18 at 13 24 27](https://user-images.githubusercontent.com/11801254/108387780-ae92aa00-71ec-11eb-917e-b25beaf4d4b8.png)
And this
![image](https://user-images.githubusercontent.com/11801254/108387767-aaff2300-71ec-11eb-93e0-8aada4a99ccc.png)

**Comment by photopea** [comment]
Fixed, thanks! :)
