### ISSUE TITLE
Import frames to layers

### ISSUE THREAD

**Issue by imms93** [photopea/photopea#289]
It would be nice to have an option in "File" like "Import frames to layers" and the frames imported will be on the same document, each frame on its own layer, and then you can edit and save everything as an animated gif.

**Comment by photopea** [comment]
Do you mean opening multiple JPGs / PNGs and placing them all in a single PSD as separate layers?

**Comment by imms93** [comment]
Exactly that! And then save the output as an animated gif (after adding adjustment layers or text, for example).

**Comment by photopea** [comment]
How many frames do you want to import? You can drag and drop new images into a current document, they will be added as new layers. Then, just give them right names to export an animation, see https://www.photopea.com/learn/animations

**Comment by imms93** [comment]
I didn't really understand that part, to be honest, but it's probably because my English is limited.

**Comment by photopea** [comment]
Do you really need it, or you just think it would be cool?  Now, you can load and save GIF and PNG animations, just try it (File - Open,  choose GIF, File - Export - GIF).  If you put all layers into one PSD, you can export it as a GIF animation.
