### ISSUE TITLE
Artboards - checkbox for creating new projects

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2891]
It will be perfect to have a little checbox "[  ] create Artoboad" in "New Project" windows, when a user set it own dimension or use predefined. Sometime at the start I know that I must make artboard with all elements (for example desktop view for a website) and then I only copy that artboard and change to another (tablet or/and mobile phone view).

**Comment by photopea** [comment]
I added the checkbox "Artboards" when creating a new document :)
