### ISSUE TITLE
Artboards - layers in artboard folder after drawing new artboard over project without artboards

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2892]
When: the project has layers, groups etc and there isn't any artbord. 
What should do user: Draw new artboard with document size over canvas
What should to be: all layers and groups should to jump in to the artboard folder
What is now: blank artboard with background and the layers are invisible behind

**Comment by photopea** [comment]
I implemented it! If there are no artboards, and your new artboard intersects the area of a current document, all current layers are placed into the new artboard.
