### ISSUE TITLE
Artboards - different color for document window background

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2895]
When artboards are created in Photopea - the background is light gray.
When I open file with artboards from Photoshop - the background is very Dark Gray (as default for any project in Photopea when there is no artboards)

**Comment by avagp** [comment]
The only difference i can get when creating artboards is that the artboards lose their shadow
![image](https://user-images.githubusercontent.com/11801254/108390278-442f3900-71ef-11eb-888c-ee440dfc4ae1.png)

![image](https://user-images.githubusercontent.com/11801254/108390323-514c2800-71ef-11eb-8b31-65b470a16619.png)

**Comment by photopea** [comment]
I fixed it. It works as in Photoshop now - the background is identical for all documents. In Photopea, it depends on a current theme.

**Comment by avagp** [comment]
But the canvas loses its shadow when creating art boards.

Use the silver theme to notice

**Comment by photopea** [comment]
yes, the shadow is present only when there are no artboards, just like in Photoshop.
