### ISSUE TITLE
does not detect pressure

### ISSUE THREAD

**Issue by evaneth** [photopea/photopea#2896]
on the graphics tablet HUION KAMVAS GT-191 V2 HD IPS 8192 does not detect pressure, but in other programs it works. help

**Comment by photopea** [comment]
Hi, what web browser do you use? Can you update your browser or try another one?

**Comment by photopea** [comment]
I will close it, as it is up to a device manufacturer and the browser makers to fix it, websites can not fix "the stuff behind".
