### ISSUE TITLE
quick selection doesn't work properly

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2897]
I chose quick selection and clicked once on image,  then no matter what i did on canvas,  there is no reaction. All I can do is close the document and open it again.

**Comment by photopea** [comment]
That is weird. Can you send us your file to support@photopea.com , so that I can try it myself? I just tried it on my own files and it always works.

**Comment by nothingshiru** [comment]
it doesn't happen in a particular file.I have sent you a video to show you how it happened

**Comment by nothingshiru** [comment]
sometimes it can work properly, but most of time it can't. once it can't work properly, I have to close the document, so I dare not use it.

**Comment by photopea** [comment]
I need to be able to reproduce the problem somehow, in order to fix it. Can you record a video, so that I can try it myself according to your video?

**Comment by nothingshiru** [comment]
yeah I have sent a video to support@photopea.com, my email is 775657710@qq.com

**Comment by nothingshiru** [comment]
I mean it doesn't only happen in a specific file. I'm not good at English, I don't know which word is correct. sorry about that

**Comment by nothingshiru** [comment]
I have sent a video to support@photopea.com again. This time my email is nothingshiru@gmail.com

**Comment by photopea** [comment]
Your browser does not tell Photopea that the mouse has been released. I think it is a bug in your device. Try to update it, or ask the manufacturer of your device to fix it.

**Comment by nothingshiru** [comment]
Thank for all of your patient replies. 
I think I really need to buy a new device, in future.
