### ISSUE TITLE
PSD Export: Problem loading file in PS

### ISSUE THREAD

**Issue by voidnothings** [photopea/photopea#290]
Exporting a sketch file to psd works but no matter how I export it PS CS6, CC2017 keeps on saying there's something wrong with the file and suggests to "Read Composite Data" instead. Doing this will open everything flattened.

See: https://i.imgur.com/2mQZLGT.png

Versions: PS CS6, CC2017, Sketch 47.1

**Comment by photopea** [comment]
Hi, can you please send your Sketch file to support@photopea.com ?

**Comment by photopea** [comment]
I have been trying to solve it for two days now, and I found a solution. It seems like Photoshop can work with at most 8000 layers ( https://forums.adobe.com/thread/960119 ), while your Sketch file probably has more than 8000 layers. 

Now, Photopea will notify you, when you save a PSD with more than 8000 layers. I recommend deleting half of layers (in Sketch or in Photopea), saving a PSD, then going back and deleting another half and saving another PSD (so your artboards will be separated into two PSD files).

**Comment by voidnothings** [comment]
Cool. I’ll try you suggestion. Thanks!
