### ISSUE TITLE
Artboard - Copy guides to another artboard

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2900]
Frequently the artboards share a lot of common elements and common composition. So it is important to being able to copy the guides from one artboard to another.

As far as i know, Photoshop does not handle this problem (and i have looks on the web and there is a lot of people complaining about it). Illustrator have 2 types of guides, Global giudes and local guides.

Maybe an easy way could be, if the rulers are separated from each artboard (like #2893 suggests) we could have something like this when doing View > Add guides...
![image](https://user-images.githubusercontent.com/11801254/108389141-23b2af00-71ee-11eb-89c1-0efabcb5d2a1.png)

Or have it here:
![image](https://user-images.githubusercontent.com/11801254/108389265-447b0480-71ee-11eb-90b8-c482549896cd.png)

**Comment by photopea** [comment]
We could probably add a "private" list of guides to each artboard, which would be displayed only when the artboard is selected, and move when the artboard is moved.

But the problem is, that Photoshop would not detect such guides in PSD files form Photopea. I think Photoshop should add it first.

**Comment by MichalSZZ** [comment]
@photopea but Photoshop have it indyvidual guidea for each Artboard (they are activates as you describe - thay are only showed when artboard is acrive and move whwn arboard is moved). I think (dont remember now) thar the color for the global guides are different than for separate artboards.

**Comment by photopea** [comment]
Wow, you are right :) I will make it, too.

**Comment by photopea** [comment]
I implemented it. Now, when you are inside an artboard, new guides "belong" to that artboard. 

When you are inside an artboard, only guides belonging to that artboard are displayed.

When you move an artboard, its guides move with the artboard.

View - Guides from layer adds guides to the artboard, in which the layer is located.

Global guides are still possible to create and work with.
