### ISSUE TITLE
Artboard - sizes

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2901]
There should be a way to change artboards width and height on different unit measurement.

![image](https://user-images.githubusercontent.com/11801254/108389474-78562a00-71ee-11eb-9d86-6240ef250725.png)

Now i can only chage it on pixels, but i work a lot on mm/cm/inches

**Comment by photopea** [comment]
I changed it. Now, the values are displayed in ruler units. Also, for Live Shapes, the values are also in ruler units.

**Comment by avagp** [comment]
So quick, so fast
![image](https://user-images.githubusercontent.com/11801254/108583644-a1bfa480-7319-11eb-8a05-a1d02eef4daf.png)
