### ISSUE TITLE
Reposition Object selection Tool

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2902]
I use the magic Wand a lot, and i don't know if you have the statistics of usage of the W tools, but i bet that is the one.

So i have to always cycle through the W tools to get to the Magic Wand (which is the third one) 

But the real problem is that Object Selection tool is the default one on W, so when i press the W key while i have a project opened, Photopea gets stuck momentarily on "Image Analysis..." (depending on the size of the layer it could take up to 5 seconds) and the it cycles through to the next tool.

So, I would prefer to have Magic Wand as the default W tool.

Or at least Quick Selection, as in Photoshop.

But Object Selection is driving me nuts.  :)

**Comment by photopea** [comment]
Sure, I made the Magic Wand the first tool in the group :)

**Comment by avagp** [comment]
[image: image.png]
