### ISSUE TITLE
Keyboard Shortcuts are not working

### ISSUE THREAD

**Issue by TheAvGe** [photopea/photopea#2903]
The browser interface of photopea will not let me use more than one keyboard shortcut. For example, if I press G, I can only get to the gradient select. I cannot get to the fill tool, no matter how many times I press g. another example is when you press M, you can get the rectangle select, press M again and nothing happens. However, if you press L, you will get the free select tool in the same tool selector.

**Comment by photopea** [comment]
This is a new feature we added today, see https://github.com/photopea/photopea/issues/2898

You should hold Shift and press G or M, to "cycle" inside the tools of a specific group (specific key, like "G" or "M").

**Comment by avagp** [comment]
Now is like photoshop:
![image](https://user-images.githubusercontent.com/11801254/108457239-f519f000-7250-11eb-9bb9-cc2ac7a5e108.png)

**Comment by TheAvGe** [comment]
Thanks!
