### ISSUE TITLE
the key alt in toolbar doesn't work for getting the button apart under blend if

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2905]
I'm using a Android device. The button I said is under "blend if" in layer style. 
When I connect keyboard/mouse to my device, I can hold the key alt on my keyboard and drag one half of the button to get the button apart. 
When I connected only mouse to my device, I activated the key "alt" in toolbar and went to drag one half of the button I said. The whole button would be moved instead of half of it. 
 
there is another problem, that button is too small to drag it by finger when I didn't connect a mouse to my device.

**Comment by nothingshiru** [comment]
Not just the key alt. I found that the key ctrl doesn't work in some places neither. For example, I activat the key ctrl in toolbar and click on thumbnail on layer. The pixel of the layer clicked can't be selected. 
 
these things can be done with a real keyboard but not with the keys in toolbar

**Comment by photopea** [comment]
Sorry, but we do not have resources to improve the experience on touchscreens. How much would you be able to pay for Photopea e.g. per month? Maybe if we could gather money from our users somehow, we could invest into these improvements.
