### ISSUE TITLE
Problems in panels of layer/channel/path

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2906]
- dragging a layer/layer style/filter in smart object to the icons at bottom can't be copied/delete
 
- channel/path can't even be dragged
 
- path can't be renamed

because the channels can't be dragged, I have no way to copy them. 
because path can't be renamed, I can't turn a work path into normal path. If I didn't create a new path in panel before starting to use pen tool, I won't be able to save the path later. 
 
I'm using Android 10, chrome. I don't know if it only happen in my device.

**Comment by photopea** [comment]
Many people want to use their finger to scroll the layers panel, while others want to drag-and-drop layers. We can not have both. It is hard to tell what is more important.

I am afraid it is impossible to make 100% of Photopea work on a touchscreen, so I am giving it up. I recommend you to buy a bluetooth mouse and work with a mouse.

**Comment by nothingshiru** [comment]
I have keyboard/mouse and I have tried them.It is almost the same.
The only different point is rename the normal path.
When I double click the normal path by finger, virtual keyboard would show up and disappeared quickly.Using a real keyboard/mouse can solve it.
But even if I use mouse to double click a work path,it still won't let me rename it.
