### ISSUE TITLE
circular cursor can't move with mouse

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2908]
I'm using mouse on Android device. 
 
When I use a tool that its cursor is a circle like in brush tool, the circle won't move with mouse. The true cursor moved but I can't see it. So when I moved mouse and I'm going to paint, I don't know from where brush tool will start painting. If I hold left button and move mouse, the circle would move with mouse. But holding left button while I'm not going to paint something, it doesn't make sense. 
 
If it's a cross cursor like lasso, it can work properly. 
 
In Photoshop, I can press Cap lock to switch cursor between circle and cross. Could there be a same option in photopea? If circular cursor can work properly, it will be much better.

**Comment by photopea** [comment]
Are you using the Google Chrome borwser? Is it updated?

**Comment by nothingshiru** [comment]
yeah I'm using chrome. I have just updated it to newest version. Nothing is changed.

**Comment by photopea** [comment]
Do you have any settings in your mouse? Maybe it can be changed in settings, to make your mouse behave like it would on a computer.

**Comment by nothingshiru** [comment]
There are only 2 settings for mouse in Android. Moving speed and cursor size. 
Left button and mouse wheel is as same as on computer, the functionality of right button is "back" and there is no way to change it. Does it matter?

**Comment by photopea** [comment]
Can you open this webpage on your device and move the mouse in the white area? Does the text move along with the mouse cursor?

https://jsfiddle.net/nb6r824e/

**Comment by nothingshiru** [comment]
If I click, the text would comes to the place where my cursor is. 
If I click and hold and move, I can drag the text. 
If I just move cursor, text didn't move and there is nothing happened.

**Comment by nothingshiru** [comment]
It is same as the circular cursor in photopea

**Comment by photopea** [comment]
So in short, Photopea is just one webpage, there is no "photopea for Android" or "photopea for Mac". 

If a website has problems on one device, while it runs fine on the other device, it means, that the problem is in the device itself, and there is nothing a website can do about it (e.g. if you device does no speakers, and you hear no sound on Youtube.com , it is not a bug in Youtube, Youtube can not fix it).

I reported this bug to Chrome developers. I hope they can fix it: https://bugs.chromium.org/p/chromium/issues/detail?id=1180224

Meanwhile, you can try Firefox for Android, or some other browser.

**Comment by nothingshiru** [comment]
Thank for your suggestion. 
I have just found that it can work properly in the default browser of my device. I thought running photopea by chrome would be better than other browser, but I was wrong. 
So this is a bug of Chrome, right?

**Comment by photopea** [comment]
What is the default browser in your device? Yes, I think it is  a bug in Chrome. What version of Chrome do you have?

**Comment by nothingshiru** [comment]
The version of Chrome is 88.0.4324.181
 
The name of the default browser in my device on screen is "browser", I don't know what the name exactly is. 
 
My device is HUAWEI matepad10.4. 
The OS is called EMUI.

**Comment by nothingshiru** [comment]
Almost every Chinese phone brand have their own browser. I think you might not be able  find it in app store like Google play. If you need it, I can sent you the apk file.

**Comment by nothingshiru** [comment]
You won't need it. 
Just after I wrote the last reply, I went to try again. It doesn't work properly now. It's so weird. I don't know what is going on.

**Comment by photopea** [comment]
I think your "device browser" is just a modified version of Chrome. So it behaves similarly.

**Comment by nothingshiru** [comment]
yeah I have heard of it before in some Chinese network platform. They said most of browser are using the core of chrome. I don't know much about that and I don't know if the word "core" I used is correct.

**Comment by nothingshiru** [comment]
The cursor in lasso tool always work properly, could we use the same cursor in brush tool? 
 
I had watched a video in a YouTube channel called piximperfect and found that we can set the cross cursor as default. If photopea have a same option, it make sense. 
 
Is it possible that we use the cursor as same as lasso tool when we using brush tool? 
If it is possible, we can avoid using the circular cursor that bug now.

**Comment by photopea** [comment]
Another user tried it on Android with a mouse connected, but it works well.

Maybe the problem is in your Huawei device. Can you ask Huawei to fix it?

**Comment by photopea** [comment]
See a video here: https://bugs.chromium.org/p/chromium/issues/detail?id=1180224#c2

**Comment by nothingshiru** [comment]
I have tried some other browser. Firefox, Via, quark.And I found a browser can work properly so far. 

- Firefox
It always shows me the default cursor of Android, no matter what tool I was using. When I am using brush tool, I can see circular cursor and default cursor of Android at same time. When I use lasso tool or hand tool, it won't show me the cross cursor or hand cursor. There is only default cursor. 

- Via
It worked properly when I had just installed it, after I click the option "open and place" to open image in gallery and came back to photopea, it doesn't work properly anymore, just like chrome. 

- quark
So far circular cursor can always work properly in this browser.

**Comment by nothingshiru** [comment]
The problem happens in my 2 different devices. They are both Android 10/emui10.Maybe Android 10 is the problem. If I had any other devices, I would test it.

**Comment by nothingshiru** [comment]
@photopea 

Could you ask them to open a image from local on a Android 10 device, and observe whether the cursor of brush is moving along with mouse?

**Comment by photopea** [comment]
My brush also does not move if I connect an external mouse to my phone in Chrome for Android.

I reported it here: https://bugs.chromium.org/p/chromium/issues/detail?id=1213940

**Comment by nothingshiru** [comment]
Hi. 
I had left two comments on that page. And then there was just this one comment and no other comment. 
![screenshot_20210528_192642](https://user-images.githubusercontent.com/79258245/119977737-5dfccb00-bfeb-11eb-8206-0f036291263d.jpg)

Do you know what it means? And what is the M90?
