### ISSUE TITLE
clipping mask question

### ISSUE THREAD

**Issue by sooyoung410** [photopea/photopea#2909]
I have a question about clipping mask.
Is there any way I can get all the stroke line of bottom layer left while the overlapped part of top layer being cropped into the bottom layer?

For example, Let say there are 2 pen-drawn shape layers(top layer is a square one and bottom layer is a circle one), both colored and stroked. I want to get all the stroke of circle one with the all overlapped square part cropped into the circle.
For now, if I use clipping mask on the top layer, the cropped part on top layer covers the both stroke and color of bottom layer underneath it.

**Comment by photopea** [comment]
I am afraid I do not understand you quite well. Photopea has no clipping paths, there are vector masks.

Photopea can do everything Photoshop can do. So look for a solution how to do it in Photoshop. Or ask here: https://www.reddit.com/r/photopea

**Comment by MichalSZZ** [comment]
@sooyoung410 can you share psd with us and flat png with effect (you can even draw it by hand) of what do you want to have. I think that is can be solution but we must know more details.

**Comment by sooyoung410** [comment]
Here's my psd and png with effect as I wanted.
(It is the stroke on face layer on beard that I want. it disappears after clipping mask effect.)

I know I'm the problem here but I just don't know how to do it😂 (cuz I'm learning photoshop as a beginner) 
Thanks for helping me tho.

> @sooyoung410 can you share psd with us and flat png with effect (you can even draw it by hand) of what do you want to have. I think that is can be solution but we must know more details.

[아카이브.zip](https://github.com/photopea/photopea/files/6012248/default.zip)

**Comment by MichalSZZ** [comment]
https://www.photopea.com/#iTH2psvac

is it good for you?
You should use boolean operation on 2 (or more) shapes. In your case:
Duplicate layer "face"
Select 2 layers: "beard" and "face" and than marge it to one shape (ctrl + E)
With "Path select" tool select one path in that new layer
On top tool toolbar there is "path1" and some boolean operation to manage
Change it to have result as common part of two shapes (if nothing is correct - use arrow that is on the right to set one shape over another
If you have what you want, change the fill and when you don't want to modify it you can joint two path with  merge function (last in boolean select box for Path).

**Comment by sooyoung410** [comment]
Thank you so much! it helped me a lot.

**Comment by MichalSZZ** [comment]
No problem. Next with question like this, try to write on reddit. I look there frome time to time. Github is more for Bugs and feature request I think.
