### ISSUE TITLE
I don't know if this counts as an "issue"?

### ISSUE THREAD

**Issue by rowan010101** [photopea/photopea#291]
I don't know if this counts as an "issue" or not, but it's been bugging me. Instead of being able to upload things directly to a project from my computer, I have to open them in new tabs and then duplicate each thing into the project I want them in.

**Comment by photopea** [comment]
Hi Rowan, do you know about the option of Drag-and-Drop ? You can drag the images with a mouse from your computer right into the project inside Photopea, they will be added as new layers.

See https://www.photopea.com/learn/opening-saving

**Comment by photopea** [comment]
You can also duplicate layers simply by dragging them to another tab.
![duplicate](https://user-images.githubusercontent.com/15955558/32139074-2a9e88dc-bc40-11e7-8c4e-bc67de8d91d7.png)
