### ISSUE TITLE
Font for text layer is not set in script

### ISSUE THREAD

**Issue by Ekimik** [photopea/photopea#2910]
Hi,
I have following script
```js
var names = [
    'John Doe',
    'Jane Doe',
];

var currentUnits = app.preferences.rulerUnits;
app.preferences.rulerUnits = Units.MM;

for (var i = 0; i < app.documents.length; i++) {
    var doc = app.documents[i];
    app.activeDocument = doc;
    var content = names[i];

    var textLayer = doc.artLayers.add();
    textLayer.kind = LayerKind.TEXT;
    textLayer.name = content;

    var text = textLayer.textItem;
    text.size = 55;
    text.font = 'Sedgwick Ave'; // <------ not working
    text.justification = Justification.LEFT;
    text.position = [470, 310]; // x, y
    text.contents = content;

    var color = new SolidColor();
    color.rgb.red = 0;
    color.rgb.green = 0;
    color.rgb.blue = 0;
    text.color = color;
}

app.preferences.rulerUnits = currentUnits;
```
I have also two documents open, where I want to add text. The only thing, that doesn't work is the font. Font `DejaVuSans` is loaded and used instead of `Sedgwick Ave`. I tried also other fonts, for example `Courgette` (as it is one word), but same problem appeared. I noticed that font showed in Photopea UI after script is finished is `- Sedgwick Ave` not `Sedgwick Ave` (same for `Courgette`) - see screen below. When I select font manually after script is finished, everything works as expected.

![font](https://user-images.githubusercontent.com/3527794/108598632-fea97200-738e-11eb-922d-d5e6f0199ce5.png)

**Comment by photopea** [comment]
Hi, the "font" property should be the postscript name of a font: https://www.adobe.com/content/dam/acom/en/devnet/photoshop/pdfs/photoshop-cc-javascript-ref-2019.pdf

If you move the cursor above the font name, and hold it there for a while, you will see a "bubble" with the postscript name of the font in quotation marks.

**Comment by Ekimik** [comment]
Thanks for your help. I noticed scripting manual tell something about postscript name, but I was unable to get the actual value. It's working now
