### ISSUE TITLE
Circular cursor only work properly at first.

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2911]
The thing is little different. 
I found that in Chrome the circular cursor only work properly before i Iopen a image. After I opened a image, it can't work well anymore unless I clear all the data of Chrome or uninstall it and reinstall it. 
 
https://jsfiddle.net/nb6r824e/ 
In this web you sent me, the text would always move along with mouse now in Chrome. 
 
I have recorded 2 videos. The long one is showing how it is going on in Chrome, another one is showing the circular cursor can always work properly in a browser called Quark(夸克). 
I'll send it to support@photopea.com

**Comment by nothingshiru** [comment]
I have sent the videos to support@photopea.com.My email is nothingshiru@gmail.com

**Comment by photopea** [comment]
Hi, your videos have almost five minutes with no comment. I looked at them and everything seems to work fine.

As I said before, we are just a website and we can not fix it. You have to report it to Huawei, or to the creators of your mouse.

**Comment by nothingshiru** [comment]
Ok, I get it.
