### ISSUE TITLE
Artboard background is initially transparent if WebGL is off

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2912]
If WebGL is turned off, the background of a new artboard appears invisible until I interact with it, e.g. by drawing on a new layer with the freehand brush tool. When drawing for the first time, parts of the background show up as rectangles. After releasing the mouse button, the entire background appears.

## Steps to reproduce >> results
1. After ensuring that extensions are disabled, make sure that WebGL is enabled (More > Use WebGL).
2. Open a new artboard project with a white background.
![image](https://user-images.githubusercontent.com/51429646/108606732-c81d2880-7389-11eb-937b-0906ed67deb3.png)

3. Turn off WebGL. >> The background becomes invisible.
4. Create a new layer in the artboard folder. Switch to the freehand brush tool and draw a short line. >> White rectangles appear during drawing. The entire background appears after the mouse button is released.
5. Switch to the freehand eraser. Erase the entire brush stroke from before. >> A rectangle just big enough to contain the brush stroke becomes invisible.
![image](https://user-images.githubusercontent.com/51429646/108606830-7cb74a00-738a-11eb-82ad-afa55965021e.png) >> ![image](https://user-images.githubusercontent.com/51429646/108606837-93f63780-738a-11eb-84d1-e63e26d0d0df.png)

**Comment by photopea** [comment]
fixed! :)
