### ISSUE TITLE
Artboard background is white until the user interacts with it

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2913]
If WebGL is turned on, the background of a new artboard will always appear as white regardless of the background color setting in the new project menu and the properties panel until I interact with it, e.g. by drawing on a new layer with the freehand brush tool.

## Steps to reproduce >> results
1. After ensuring that extensions are disabled, make sure that WebGL is enabled (More > Use WebGL).
2. Use File > New to create a new artboard. Be sure to set the background color to black. >> After clicking Create, the background shows up as white.
![image](https://user-images.githubusercontent.com/51429646/108606473-3eb92680-7388-11eb-98de-78fc386436d2.png)
![image](https://user-images.githubusercontent.com/51429646/108606892-fe0edc80-738a-11eb-9260-9fa0a8dfd012.png)

3. Create a new layer in the artboard folder. Switch to the freehand brush tool and draw a short line. >> Black rectangles appear during drawing. The entire background becomes black after the mouse button is released.
4. Switch to the freehand eraser. Erase the entire brush stroke from step 3. >> A white rectangle just big enough to contain the brush stroke appears.
![image](https://user-images.githubusercontent.com/51429646/108606942-5c3bbf80-738b-11eb-968a-f7ca5d2e165b.png) >> ![image](https://user-images.githubusercontent.com/51429646/108606952-6a89db80-738b-11eb-881e-744ba18d6ebc.png)

## Additional notes
This could be related to #2912. I made this a separate issue because fixing #2912 might not fix this. I also don't know whether the always-white background is expected behavior, so I'll defer to someone who regularly works with artboards.

**Comment by photopea** [comment]
fixed, thanks for reporting it :)

**Comment by dentistformyeye** [comment]
The artboard background colors now behave normally when changing them or creating a new artboard. However, erasing a brush stroke still creates a rectangular artifact for any artboard background color other than "transparent". The artifact is white if WebGL is on and is the color of the workspace background if WebGL is off.

## Steps to reproduce >> results
1. After ensuring that extensions are disabled, start with a new artboard project with a black background. Create a new layer in the artboard folder.
2. With the foreground color set to red, draw a short line with the freehand brush tool. Then erase the entire brush stroke with the freehand eraser. >> A rectangle just big enough to contain the brush stroke appears. The color depends on whether WebGL is on.
3. Toggle WebGL in the More menu. >> The rectangular artifact disappears, which is good.
4. Perform step 2 again. >> Same result as in step 2.

**Comment by photopea** [comment]
I believe I fixed it. I modified a blending pipeline, so I hope I did not break anything else.
