### ISSUE TITLE
Artboard - button to create a juxtaposed artboard are kinda blurry

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2914]
Look at this:
![Screenshot 2021-02-20 at 23 54 08](https://user-images.githubusercontent.com/11801254/108614135-f2490780-73d6-11eb-9368-a983ebb85dfe.png)
![image](https://user-images.githubusercontent.com/11801254/108614153-11e03000-73d7-11eb-9f4e-7f3ae830a038.png)

:/

they were not like this at the beginning of the artboard implementation

**Comment by photopea** [comment]
I made these buttons blue and they should look better.

**Comment by avagp** [comment]
WAAAY BETTER

It was because of the background color right?
