### ISSUE TITLE
Feature request - Guide Layout, Smart Guides and Cross guides 

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2915]
I can explain the features one by one if you tell me, but for now i will leave this link, with all the features from Photoshop that i would be glad to have over Photopea:

https://jkost.com/blog/2017/05/grid-guides-and-ruler-shortcuts-in-photoshop-cc.html

Cross guide:
![image](https://user-images.githubusercontent.com/11801254/108614380-d2b2de80-73d8-11eb-9911-3eeca5d62d46.png)

Guide Layout:
![image](https://user-images.githubusercontent.com/11801254/108614384-dcd4dd00-73d8-11eb-8c50-e70cc43fece4.png)

Smart guides:
![image](https://user-images.githubusercontent.com/11801254/108614392-ea8a6280-73d8-11eb-8b39-8652bfa8fe62.png)
![image](https://user-images.githubusercontent.com/11801254/108614395-eeb68000-73d8-11eb-8d81-e063a73ad7f2.png)
![image](https://user-images.githubusercontent.com/11801254/108614397-f1b17080-73d8-11eb-9bd4-95bd286e52e6.png)
![image](https://user-images.githubusercontent.com/11801254/108614398-f37b3400-73d8-11eb-8b99-bb774a661fd5.png)
![image](https://user-images.githubusercontent.com/11801254/108614400-f8d87e80-73d8-11eb-84f6-b849d6afdcfb.png)

**Comment by MichalSZZ** [comment]
Cross guide: I used a few times ib Photoshop in spexific moments. It was very helpfull there.

Guide Layout: I think there is now in Photopea. Look for Guide Guy. Maybe it is not 1:1 as un Photoshop but work good for me (sometimes even better)

Smart guides: you are thinking about mesurments? Becouse  lines are in Photopea I think...

**Comment by avagp** [comment]
I will never ever ever thought about looking into Window > Guide Guy.

It is what i was looking for (i had being making mines by hand (or typing them on the Add Guides)!!)

As i read on Facebook post about GuG, it is like a "plugin", it is really good, but maybe it is time to absorb it and make it "official".

For example, it should display the name of each option (ass now it has a tooltip). Or have the units set to the one on the rulers (as now there are only pixels). And finally the bottom part should have a subtitle like: Guides to the canvas. Maybe here it can have a copy/paste feature for guides on Artboards #2900.

And for the smart guides, here is a video:
https://youtu.be/btPWT_nqmZU

It gives you the units between layers/shapes and also help you align them in groups

**Comment by avagp** [comment]
Btw, this:
![Screenshot 2021-02-21 at 11 37 09](https://user-images.githubusercontent.com/11801254/108628351-32d96d00-7439-11eb-8061-5e25ce45361d.png)

Is simpler than this:
![image](https://user-images.githubusercontent.com/11801254/108628361-3d940200-7439-11eb-96e7-db724778769b.png)

Although the latter is more compact

**Comment by MichalSZZ** [comment]
Not everything should be copied from PS...
BTW as I remember guides can be maked from selection if you have rectangle selection and than use GuG by clicking icons for border from the bottom of window.

GuG can be better. As you wrote - units in mm in cm is a good feature. But for somebody the grid for bootstrap or samething else for webdesign will be more helpfull. Photoshop have presets for that.

**Comment by avagp** [comment]
Totally agree Michal, not everything should be like Photoshop.
As now GuG is great (the units is a must, at least for me that i work printing).

I still believe Photoshop guide creation is more easy to understand.

Thanks for the trick with the rectangle selection.
![Screenshot 2021-02-21 at 12 32 16](https://user-images.githubusercontent.com/11801254/108629946-12151580-7441-11eb-87be-9972f44c4323.png)

**Comment by MichalSZZ** [comment]
3th thing are in Photopea too.

![obraz](https://user-images.githubusercontent.com/38118273/108636021-05191600-7483-11eb-8acc-25c3aeca8017.png)

I dont have access to computer yesterday but now i see that distances are in Phtotopea (even if you change units - I have mm changed in rulers on my print screen)

**Comment by MichalSZZ** [comment]
> 
> 

> Thanks for the trick with the rectangle selection.

It works for any selection. You can for example click with Ctrl in text layer thumbnail (or everything else) and it make selection and after that you can use GuG

**Comment by avagp** [comment]
How do you trigger/activate the distances?

**Comment by MichalSZZ** [comment]
> 
> How do you trigger/activate the distances? 

You have it on the screen. When you have Move Tool, at the top in toolbar you have checkbox "[  ]  Distances". Check it out :)

**Comment by avagp** [comment]
Thanks.

It does show the distances, but there is a way to enable this snapping
feature of equal distances?

**Comment by photopea** [comment]
Guys, you can keep discussing it, but I will close it for now, to be able to focus on other problems. Feel free to make new specific feature requests :)
