### ISSUE TITLE
Update the translation of Simplified Chinese

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2916]
There are some word that is incorrect or not same as Photoshop, so I have changed a lot of word in photopea.com/translate.
 
Can you update it? 
 
I haven't changed all the word I want to changed yet, because I'm mixed up. I can't remember which one I have changed, which one I haven't changed. I'll keep changing after you update it.

**Comment by photopea** [comment]
Hi, I have updated the translations :)

**Comment by nothingshiru** [comment]
Thanks

**Comment by nothingshiru** [comment]
Hey, I wanted to translate some English words to Chinese words, but I can't find the words in photopea.com/translate. What should I do? 
 
For example, these words in top menu I can't find. 
 
1.图层(Layer) - Smart Object
The "Smart Object" should be "智能对象".
 
2.选择(Select) - Save selection
The "Save Selection" should be "存储选区". 
 
3.视图(View) - Extras
The "Extras" should be "显示额外内容". 
 
Some filters in Filter menu and all the filters in filter gallery can't be found neither.

**Comment by nothingshiru** [comment]
Hi. 
There are some English texts in 简化字 中文 that I want to translate into Simplified Chinese. But I can't find any of them in photopea.com/translate.
 
What can I do for that?

**Comment by photopea** [comment]
Hi, many phrases in Photopea are not translatable at the moment, they are fixed in English.

I was afraid, that if I make everything translatable, there would be 2x more words to translate, but only one in 10000 people would see these words.

**Comment by nothingshiru** [comment]
I'm just wondering, is it make photopea much larger or laggy that people add translation?
