### ISSUE TITLE
Switching foreground/background color is difficult without mouse

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2917]
The button is too small to touch by finger, even clicking on it with stylus isn't much easier. The button of resetting colors to default is same. 
 
They are easier to be touched in old version. 
 
![screenshot_20210222_032449](https://user-images.githubusercontent.com/79258245/108636417-0fa5d080-74c0-11eb-9d60-47733578c83c.jpg)
 
Could you make them bigger?

**Comment by photopea** [comment]
Hi, the buttons should actually be about the same as before. It was hard to click with a finger before, too.

Can you increase the page zoom in your device? Then, everything should become larger.

**Comment by nothingshiru** [comment]
No, they are not same. I use photopea sometimes in photopea.com  , sometimes in ps.gaoding.com . They are quite different.
 
I can zoom in page by two fingers normally, but the same action would just zoom in canvas in photopea.

**Comment by photopea** [comment]
I made the top right / bottom left buttons a bit bigger, while the main color buttons are a bit smaller.

If we switch to the old colors, we would have to show a smaller number of tools in the toolbar, because the color picker would use more space.
