### ISSUE TITLE
Disable raster mask cross is a little off

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2918]
![image](https://user-images.githubusercontent.com/11801254/108638474-2faca400-746e-11eb-8d16-d790bebebe1c.png)

**Comment by nothingshiru** [comment]
Is it a cross??? 😳
![screenshot_20210222_051208](https://user-images.githubusercontent.com/79258245/108638919-a4163000-74cc-11eb-8cd4-86c62f0fad9d.jpg)

**Comment by MichalSZZ** [comment]
Yes. It should to be a red cross. Sometimes I have cross sometimes line. I must see on my mac with retina. Maybe it is depend on resolution.

**Comment by photopea** [comment]
fixed, thanks for reporting it :)
