### ISSUE TITLE
"Save to Web" problem

### ISSUE THREAD

**Issue by Actfirst** [photopea/photopea#292]
From the file option I cannot "save to web" why?

I want to change some wording and I cannot save to web to upload

**Comment by photopea** [comment]
Hi, "Save for Web" was replaced by "File - Export - PNG / JPG / SVG ..."

We think it is better, because you can choose the format just with one extra click (in the Save For Web window, it needs two clicks).

**Comment by photopea** [comment]
I am going to consider it solved.
