### ISSUE TITLE
Fixed ratio as a default when transform image

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2920]
Photoshop did it. Does it means that people won't change the ratio of image most of time when transform it? 
 
I do keep the ratio fixed most of the time. So I think it would be more convenient that fixed ratio is default setting.

**Comment by photopea** [comment]
Hi, I think there are still more people who are used to holding Shift to keep the ratio, than the other way.

Maybe it will change in a couple of years, but I will leave it as it is for now.
