### ISSUE TITLE
Keys button disappeared in portrait mode

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2921]
When the page haven't been loaded completely, I can see it. Once the page been loaded,  it's gone. 
![Screenshot_20210222_205612_com android chrome](https://user-images.githubusercontent.com/79258245/108723945-c3aa6880-755f-11eb-8d67-f4d27de47bee.jpg)
![Screenshot_20210222_205618_com android chrome](https://user-images.githubusercontent.com/79258245/108725025-e9843d00-7560-11eb-9aec-279248216635.jpg)

 
If I go to landscape mode, it's there where it should be in Chrome. But in the photopea that I installed to home page from Chrome, it is still can't be seen no matter what mode I am. 
 
In this version (ps.gaoding.com), I'll see it all the time, no matter what mode I am, what browser I'm using.

**Comment by photopea** [comment]
I fixed the problem. Now, the keyboard button should always be displayed.
