### ISSUE TITLE
Artboard - When moving artboards, layers disappear

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2922]
https://video.drift.com/v/abW6eWjr5Ll/

Another way to see it is that the layers don't move witht the artboard

**Comment by photopea** [comment]
Hi, that is a way Photopea works and I can not fix it now :( after you release the mouse, it should come back again.

Internally, there is sitll a rectangular document for all artboards, and when you finish moving an artboard, it performs a Cropping with the crop tool, to make sure all artboards are visible.

**Comment by avagp** [comment]
Maybe showing a square where it is moving in staff of moving the whole
showed in real time can be a trick?

**Comment by photopea** [comment]
It shows an artboard rectangle while you move it.

**Comment by avagp** [comment]
but only that.
meanwhile the artboard waits in its place

**Comment by avagp** [comment]
But it is just a mere suggestion.

Of course it could be better
