### ISSUE TITLE
Open multiple images in one document

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2923]
The way we put images into one document now is that open one of them first, and open others in the option File - Open & Place. 
 
There's a bad thing that the size of others would be limited by the first image. 
![新建项目 (3) (1)](https://user-images.githubusercontent.com/79258245/108747155-18f27400-7578-11eb-8d2f-2234f8c9c33f.jpg)
 
We need a new option to put images into one document at once, and the size of canvas is as big as it can to include all images without changing the size of any of them.

**Comment by photopea** [comment]
Hi, I don't know where to add such option, without making it too complicated.

After you place all your images, you can use the Crop tool - crop by "All Layers" button.

**Comment by MichalSZZ** [comment]
@photopea I think there is a bug. If we put an Image to the project using function "open and place" the image is added as a new layer (as a smart object). And that is OK. It is work like "place embeded" in Photoshop.

But in Photoshop when layer is added and it fits to the canvas - and... in the toolbar there is for example 15% in width and height for smart object (when that layer is bigger than canvas size). 
In Photopea we have layer that fits but the size is 100% for the smart object... That is incorrect

And when user will get the proper % of size after importing - he can change to 100% and have original dimensions fo each layer added to the project

**Comment by photopea** [comment]
@MichalSZZ you are right, it is fixed now.
