### ISSUE TITLE
Need a delete button in slice select tool

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2924]
We can't delete slices without mouse/keyboard now. It would convenient having a delete button in Slice Select Tool.

**Comment by photopea** [comment]
Hi, sure, I added the Delete button.

**Comment by nothingshiru** [comment]
Nice!

**Comment by nothingshiru** [comment]
Is it in the page now? I can't find it.

**Comment by photopea** [comment]
It is in the Slice Select tool at the top.

**Comment by nothingshiru** [comment]
Ok, I see it.
