### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by CrazyCorbeau** [photopea/photopea#2925]
So my keyboard shortcuts aren't working, I tried changing the brush tool to pencil tool which the shortcut is 'b' and i have to press it twice, but it doesn't change. I did the same for all shortcuts and the same thing happened.

**Comment by nothingshiru** [comment]
You now need to hold shift key before press b. It have been changed a few days ago.

**Comment by photopea** [comment]
yes, hold Shift to "cycle" through the group of tools. Otherwise, the letter like B will always take you to the last used tool form the group, no matter how many times you press it.

**Comment by CrazyCorbeau** [comment]
> yes, hold Shift to "cycle" through the group of tools. Otherwise, the letter like B will always take you to the last used tool form the group, no matter how many times you press it.

thank you, really wish I was notified about any changes

**Comment by photopea** [comment]
@CrazyCorbeau do you follow our twitter or facebook? The links are on the top right corner in Photopea.com

**Comment by CrazyCorbeau** [comment]
> @CrazyCorbeau do you follow our twitter or facebook? The links are on the top right corner in Photopea.com

No I do not, but I will now
