### ISSUE TITLE
Overscroll

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2927]
See a video in this link. 
https://youtu.be/eNQMsF9hgdM
 
In photopea, we can do that by two fingers but not mouse/keyboard. But Not all devices can be controlled by fingers.

**Comment by dentistformyeye** [comment]
Summary of the feature: if the entire image fits in the visible workspace, then the pan tool doesn't do anything if overscroll is turned off.

I've always found it a bit jarring when I pan a little, zoom out, then try to pan again but can't. In addition, the Rotate View tool can make the image go outside of the visible workspace, but the pan tool still doesn't do anything if the unrotated image fits, so I'd have to zoom in to edit the clipped corners/edges.
If you do implement it in Photopea, I think overscroll should be on by default. I don't think there's an advantage in having overscroll off.

**Comment by photopea** [comment]
So I would make it as if it is always on, instead of making it an option. Do you agree?

In general, I was afraid, that when zoomed out, the user would move the image too much off the screen, and then, would not be able to find it back. 

I will keep the functionality, that if you perform a zoom, it would be re-centered, ok?

**Comment by nothingshiru** [comment]
We may wanna zoom out/in a little bit but don't want it go back sometimes. 
To find it back, we can do it by top menu View - Fit The Area.

**Comment by dentistformyeye** [comment]
> So I would make it as if it is always on, instead of making it an option. Do you agree?
> In general, I was afraid, that when zoomed out, the user would move the image too much off the screen, and then, would not be able to find it back.

Yep, having overscroll permanently on is fine. I appreciate that you considered that the user might pan too far.

> To find it back, we already have a option can do it. Top menu View - Fit The Area.

Ivan's idea with keeping the zoom -> recenter was a good compromise, but I can't believe I forgot about one of the features I use the most 😅 .

**Comment by photopea** [comment]
I fixed it :) You can pan a document freely at any zoom. Also, there is a restriction, such that at least a small strip of a document should be always visible (so that you can not pan too far away from your document).

**Comment by dentistformyeye** [comment]
Thank you!
