### ISSUE TITLE
The Layer Style window wont close

### ISSUE THREAD

**Issue by me0wri3e** [photopea/photopea#2929]
![image](https://user-images.githubusercontent.com/79513426/108832605-b7c5b180-7606-11eb-961a-295a4b56b4a5.png)
i keep on repeating on my work due to this issure T^T

**Comment by photopea** [comment]
Hi, what should I do to make it happen on my computer? When I try to open the Style window, i am alawys able to close it.

**Comment by me0wri3e** [comment]
> Hi, what should I do to make it happen on my computer? When I try to open the Style window, i am alawys able to close it.

i was editing the layer then it doesn't close idk what to do

**Comment by photopea** [comment]
I really need some steps how to reproduce it to be able to fix it. If you can not make it happen again, I can not fix it.

**Comment by photopea** [comment]
I have to close it, as there is no way to reproduce it :(
