### ISSUE TITLE
Occasional smart object issue

### ISSUE THREAD

**Issue by jplibby** [photopea/photopea#293]
There seems to be an occasional issue with smart objects that has developed. When editing psd files from Adazing.com, the saved smart objects are out of alignment in the image. But smart objects in other psd files don't seem to have this problem. They look correct when saved.

I have edited files from Adazing before with no problem. I have just noticed this in the past couple of days. I hope I'm explaining this properly. Thank you!!
Joe L.

**Comment by kuckir** [comment]
Hi, you are right, we changed the redrawing mechanism of smart objects recently (to make it faster). Could you send us one of those PSDs to support@photopea.com?

**Comment by jplibby** [comment]
Thanks for following up. I will e-mail it to you in a few minutes.
Joe

**Comment by photopea** [comment]
Hi, it was fixed. It happened only for smart objects, that had Warp on them. Thank you very much for your cooperation!
