### ISSUE TITLE
No more reaction atfer setting two options in brush panel

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2930]
Once I set 100% roundness jitter and 0% minimal roundness in brush panel, the page would be freezing. 
![screenshot_20210223_191114](https://user-images.githubusercontent.com/79258245/108836956-79cb8c00-760c-11eb-9468-9d1b230926fc.jpg)
 
99% Roundness Jitter and 0% Minimal Roundness/ 100% Roundness Jitter and 1% Minimal Roundness was fine.

**Comment by photopea** [comment]
It does not happen for every brush. It does happen for the third brush from the end.

**Comment by photopea** [comment]
I fixed it - the Minimal Roundness should always be at least 1%.
