### ISSUE TITLE
Merge Layers broken. What is this box?

### ISSUE THREAD

**Issue by SpiritHeroKaleb** [photopea/photopea#2933]
I have come across this problem where I am unable to merge my two layers even though it has worked last week. I also noticed there's a box with four boxes on its corners, and I don't know what that means. I would like to remove it, thinking it's the primary issue, but I don't know how. Can I get help with this, please?
![image](https://user-images.githubusercontent.com/79526957/108862900-a9ec3e00-75be-11eb-91f2-df74a90b1b4f.png)

**Comment by photopea** [comment]
Hi, could you try it again? Reload Photopea with Shift+F5.

**Comment by SpiritHeroKaleb** [comment]
I thought that would be the trick too, but reloading it four times and doing the entire thing still gave me this same box inside that layer I'm still trying to get rid of.

**Comment by nothingshiru** [comment]
> I thought that would be the trick too, but reloading it four times and doing the entire thing still gave me this same box inside that layer I'm still trying to get rid of.

You can do that in top menu Layer - Rasterize

**Comment by photopea** [comment]
Hi, I am able to merge any layer I try. Can you send me your PSD to support@photopea.com , so that I try to merge it myself?

**Comment by dentistformyeye** [comment]
![image](https://user-images.githubusercontent.com/51429646/108937928-2ca3e600-761d-11eb-9c65-e7e8ea33965a.png)
The box with 4 smaller boxes is just an indicator that the layer is a shape layer.

**Comment by photopea** [comment]
Merging did not work yesterday for several minutes, and it should be fixed now.
