### ISSUE TITLE
photopea frozen & i can't save the files

### ISSUE THREAD

**Issue by kaguraaaaa** [photopea/photopea#2936]
i was using photopea because i dunno how to make gifs with photoshop and i had about 10 files completed before it randomly bricked on me. i'm gonna be damn pissed if i lose all of my progress. is there a way to save my files or something?

**Comment by photopea** [comment]
Hi, you probably don't have enough RAM memory. In that case, try to save your work often using File - Save as PSD.

**Comment by kaguraaaaa** [comment]
so thats it? its just all gone now? what a pain.

**Comment by photopea** [comment]
If a website is closed, there is no way to restore it. Otherwise, you can try to do some steps back in History and save it.
