### ISSUE TITLE
Adblocker Removed yet prompts still appear

### ISSUE THREAD

**Issue by LarryTLlama** [photopea/photopea#2938]
I have recently tried to access the photopea website with an adblocker installed but disabled during the time using the web app. Prompts still appeared so thought the best thing to do is to just remove the adblocker altogether. After refreshing the page multiple times, the prompts on photopea still kept popping up.

I can't exactly use photopea now as the same message keeps appearing

**Comment by photopea** [comment]
Hi, is the advertisement displayed properly at the right side of the editor?

**Comment by LarryTLlama** [comment]
Yes it was strangely.

It appears that it now works though, after many refreshes! Thanks for your help

**Comment by photopea** [comment]
Ok I am glad it works.
