### ISSUE TITLE
Will there be a publicly available developer API?

### ISSUE THREAD

**Issue by splincode** [photopea/photopea#294]
Can you provide REST API for interaction with various graphic tasks, for example, getting a picture by psd, reducing, compressing various images like TinyPNG, in general, something for developers?

**Comment by photopea** [comment]
Hi, there is an API here: https://www.photopea.com/api/ .
You can use it to convert any file to PNG (and save it back to the server), process PSDs with scripts etc.
For a simplified PNG minification, use http://upng.Photopea.com

**Comment by splincode** [comment]
Add this to the description to the readme.md.
https://github.com/photopea/photopea/blob/master/README.md

After all, the project is directly related to this. And I would also like links to all products. And also the roadmap of the API development. Then it will be clear what to expect.

**Comment by photopea** [comment]
Ok, I just did, thanks.  UPNG minifier has its own page here: https://github.com/photopea/upng.js
