### ISSUE TITLE
Photopea isn't opening Google Drive photos from my School's Google Drive account

### ISSUE THREAD

**Issue by jspence2018** [photopea/photopea#2940]
Hi
My admin added Photopea to the "Open With" options so my Chromebook students would be able to edit photos from their Google Drive accounts. I was excited because I tried it with my personal Google Drive and it worked yesterday. But then when I tried it with the school account today it wasn't working - Photopea will open but the photo won't open in it and there are no File options for it to open a photo from Google Drive. Help! Is there any way to resolve this?

**Comment by photopea** [comment]
That is very strange. Did you see a popup window for allowing Photopea access your file? Maybe popups are blocked in your browser, you should unblock them.

**Comment by jspence2018** [comment]
Hi, thanks for getting back to me!  no, no pop up nor a sign that a file is
blocked. I will try again.... I can also do a screencast vid if you want so
you can see what's happening.



Jen Spence, Art
Brooklyn Preparatory High School
257 N 6th Street
Brooklyn, NY 11211
718-486-2550

"Every child is an artist. The problem is how to remain an artist when he
grows up."
---Pablo Picasso

"Perhaps the mission of an artist is to interpret beauty to people - the
beauty within themselves." - Langston  Hughes

**Comment by jspence2018** [comment]
https://drive.google.com/file/d/11sQXhal_eGA-GEe3BCNypVr2N5k6CatR/view


Jen Spence, Art
Brooklyn Preparatory High School
257 N 6th Street
Brooklyn, NY 11211
718-486-2550

"Every child is an artist. The problem is how to remain an artist when he
grows up."
---Pablo Picasso

"Perhaps the mission of an artist is to interpret beauty to people - the
beauty within themselves." - Langston  Hughes

**Comment by photopea** [comment]
I see you are using many browser extensions. Maybe one of your extensions is blocking Photopea from accessing Google Drive. Could you try to disable all extensions and try it again? Or at least do not give any extension a permission to read and modify the content of websites.

**Comment by jspence2018** [comment]
THANK YOU. It was the pop up blocker on Chrome. Hopefully my students using
the Ed dept computers can access and change that setting....


Jen Spence, Art
Brooklyn Preparatory High School
257 N 6th Street
Brooklyn, NY 11211
718-486-2550

"Every child is an artist. The problem is how to remain an artist when he
grows up."
---Pablo Picasso

"Perhaps the mission of an artist is to interpret beauty to people - the
beauty within themselves." - Langston  Hughes

**Comment by photopea** [comment]
I recommend people not to use any browser extensions. You can never know precisely what an extension does. In 99% of cases, it does something you do not want, which will cause you pain in the future.

It is the same as if before reading a letter, you passed it through ten random people, and allow each person to read and rewrite it as they wish. That is what browser extensions do to a website before it is displayed to you.
