### ISSUE TITLE
Slider buttons in levels seem to be incorrect

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2941]
I felt hard to drag the button by finger before, and today I discovered that maybe the touch area is incorrect. (If using mouse, everything is right.) 
![Screenshot_20210225_013033_com](https://user-images.githubusercontent.com/79258245/109042933-b7630e80-770b-11eb-88c0-017fcb7983a0.png)

The red line is track of my finger. 
As you can see in this picture, the real area that can be touched is little bit upper. 
 
Dragging button at that position, parts of histogram would be covered by finger.

**Comment by photopea** [comment]
I just tried to drag the slider as you show on the left, and it works well :/

Is the red line a real recorded track of your finger, or is it where you think you have clicked?

**Comment by photopea** [comment]
Hi, I made the whole graph area clickable, you can click absolutely anywhere and drag the slider.
