### ISSUE TITLE
Pixel grid is green if zooming by scroll left/right

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2943]
![screenshot_20210225_190356](https://user-images.githubusercontent.com/79258245/109144843-ae6e4d80-779c-11eb-9030-8a6fed76ac2e.jpg)
Zooming by click, grid is black. Zooming by scroll, it will be green,  but it comes back to black when zooming in to the limit. 
Clicking on canvas by  zoom tool can change it back to black and don't need to zoom in to the limit.

**Comment by photopea** [comment]
I am afraid we can not fix it, that is the way it has to work for WebGL.
