### ISSUE TITLE
display on page domain, files from sub.domain

### ISSUE THREAD

**Issue by youtube666** [photopea/photopea#2944]
can i use photopea frame in my domain, if files will upload from the subdomain ?

**Comment by photopea** [comment]
Hi, what do you mean by "files will upload"? The <iframe> can be placed on any domain. The URL of opened files (via the API) can also be any domain. These things are not related.

**Comment by youtube666** [comment]
will this work?

on page DOMAIN.tk
but file png load from sub.domanin

`<iframe src="https://www.photopea.com?rnd=1680422140#%7B%22files%22:%5B%22https://SUB.DOMAIN.tk/img2/pug.png%22%5D,%22environment%22:%7B%7D%7D" id="pp" style="border:none; width:100%; height:500px;"></iframe>`

**Comment by photopea** [comment]
Yes, it should work. You just have to set the right CORS for your file pug.png.

**Comment by youtube666** [comment]
```
SetEnvIf Origin ^(https?://(?:.+\.)?domain\.com(?::\d{1,5})?)$ CORS_ALLOW_ORIGIN=$1
Header append Access-Control-Allow-Origin  %{CORS_ALLOW_ORIGIN}e   env=CORS_ALLOW_ORIGIN
Header merge  Vary "Origin"
```
it worked for me. thanx
