### ISSUE TITLE
It says I'm using an ad blocker, but I'm not

### ISSUE THREAD

**Issue by TheColdCeltic** [photopea/photopea#2945]
I've been using this art program with DuckDuckGo for a YEAR now, and I've never had this problem before. I love this program and use it all the time. Today I used it, only to get a notification that I am using an ad blocker and that this site depends on them. Here's the problem: I'm not using an ad blocker

**Comment by photopea** [comment]
You should answer another question: do you have any browser extension? If yes, you probably have no idea what they do.

Read our article and let me know if it helped: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by dentistformyeye** [comment]
The DuckDuckGo extension blocks trackers. Since most ad services are trackers, DuckDuckGo's extension often behaves like an ad blocker. Try turning off the "Site Privacy Protection" option on Photopea's site.

**Comment by photopea** [comment]
I think it has been fixed by disabling the ad blocker.
