### ISSUE TITLE
Can not save or export image on photopea

### ISSUE THREAD

**Issue by Sophie951** [photopea/photopea#2946]
I select File - Export As - PNG, JPG etc. No matter what format, it doesn't work at all. I'm using phoropea on Google chrome, Mac 10.13.6.
Please help!

**Comment by photopea** [comment]
Hi, did it ever work before in the past? Maybe all files are saved into the Downloads folder, with no notification in between. Also, is your Chrome updated?

**Comment by photopea** [comment]
I have to close it because of lack of details.
