### ISSUE TITLE
Which font library is used 

### ISSUE THREAD

**Issue by Nils-1st-retail** [photopea/photopea#2947]
Hi, 
I'm using Photopea to create graphics for a website where they will be displayed  as svg to allow crawlers to detect the contained text. 
My problem is that when displaying the SVG on my website I need to include the referenced fonts used in the SVG to load them on the site. 

Which list of fonts is it that's included as default on the font selector? Such that I can load them on my server to be able to load each one.
And is there any better way of locating which fonts is used in a specific svg then to parse the style part for the specific fonts?
Some event, or such that I can catch when a new font, is added to my creative.

**Comment by photopea** [comment]
We have over 5000 fonts in our database. Many of them are often installed on the computer of the visitor (no need to link them from elsewhere).

I was thinking, maybe we could attach the font to the SVG as a Base64 string? That is how we attach raster graphics into SVG at the moment (all  in one file).

**Comment by Nils-1st-retail** [comment]
If it's possible to embed the fonts in the svg that would be a nice solution for our setup yes. :)

**Comment by MichalSZZ** [comment]
@photopea Base64 string will be detected by the crawlers as the text that they can "understand"?

Maybe in SVG there is a tag or attribute to input text as text that can be readed by robots? As that was made in Flash for site accesibility and google robots to index the page?

Something like Alt in HTML etc.

**Comment by Nils-1st-retail** [comment]
I would think that the crawlers are smart enough to detect the base64 encoding, ignoring that as text to be indexed for the page. 

But otherwise an alternative solution if something like the "alt" tag exists for SVG would be to rasterize the text and then add the original text in an alt tag. That would make the SVG larger, but so would embedding the font as base64.

**Comment by photopea** [comment]
When exporting an SVG, there is an option to Rasterize or Vectorize text layers.

Now, when you enable these, the element will get the "aria-label" attribute with the original text, which should help search engines understand what it is. Is such solution ok for you?

**Comment by Nils-1st-retail** [comment]
Let's try it and then see if Google and other crawlers accept the texts. As long as they do, that would be a good solution for me :)

And thanks for a very quick response and solution

**Comment by photopea** [comment]
I hope it helped, I will close it now.
