### ISSUE TITLE
text keeps breaking upon save ( transparency begins to show once you get to " save as: " and choose one of the options )

### ISSUE THREAD

**Issue by sighsindisappointment** [photopea/photopea#2948]
i dont know what else to do about this, every time i go to save a gif file that has text on it, the transparency behind the text immediately breaks and shows through after im at the save page. several friends have suggested that i clear the cookies, as photopea should not be doing that and even after clearing the cookies, it still does it. what do i do ?

**Comment by photopea** [comment]
Are you making an animation? GIFs can have one frame ("static image"), too. Are you sure you understand the animation mechanisms in Photopea?

Can you send us your PSD file to support@photopea.com ?

**Comment by sighsindisappointment** [comment]
no, im not making an animation. i already have what i need, its just that when i put the desired text over my project, the transparency immediately appears when i go to save it as a gif file. i have all the frames required, but it only ever does this with my gif projects, never with my jpg and png files.

**Comment by photopea** [comment]
What do you mean by "transparency immediately appears"? Can you show us a screenshot of what you get and what you want to get?

**Comment by sighsindisappointment** [comment]
https://imgur.com/8YMTJPN.png / https://imgur.com/BAV4QsL.png

theres the before and after screenshots.

**Comment by photopea** [comment]
Could you save your work as a PSD and send it to support@photopea.com ?

**Comment by sighsindisappointment** [comment]
uh, sure, i guess, but i dont know what all you guys can do for it

**Comment by photopea** [comment]
I opened your PSD in Photopea and pressed File - Export As - GIF. The resulting GIF does not have any transparent parts.

![test](https://user-images.githubusercontent.com/15955558/109281766-00ef4e80-781d-11eb-8c2a-7312f6e12e3f.gif)

Do you have any browser extensions? Some of them could be doing it (modifying GIFs in Photopea). Could you disable some extensions and try it again?

**Comment by sighsindisappointment** [comment]
... i dont know what extensions could be interfering with the site when im trying to put text on the gif. all i have is google translate, google dictionary and screencastify as my extensions.
could it be something within the site settings other than the cookies ?

**Comment by photopea** [comment]
Try to disable all extensions and see if it helps. In Chrome, you can see your extensions at chrome://extensions

**Comment by sighsindisappointment** [comment]
i dont think translate, dictionary and screencastify are doing anything though...

**Comment by photopea** [comment]
If you refuse to disable your extensions, which break Photopea, use Photopea in Incognito browser mode (extensions are disabled in it). I am sure everything will work well in Incognito.

**Comment by sighsindisappointment** [comment]
my problem is, it still does it in incognito mode

**Comment by photopea** [comment]
Are you using Google Chrome? Is it updated?

**Comment by sighsindisappointment** [comment]
yes, it has all of its updates

**Comment by photopea** [comment]
Can you maybe record a short video of how you open your PSD in Photopea in Incognito mode and export it as GIF?

**Comment by sighsindisappointment** [comment]
i can try if screencastify doesnt crash on me in the process
but all i really do is just open the file i want edited in photopea, edit it accordingly and save it as either a .png, .jpg or .gif file. sometimes it works as the gif file and sometimes it doesnt.
