### ISSUE TITLE
Duplicate into - wrong new document dimensions after duplicating from artboard

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2949]
It is problem for layers/groups that are in the project that have an artboards.

When I want to duplicate only a layer or group (functionality that was in Photopea before artboards) to new project without any artboards. The dimensions of new project are as summary of artboards width or/and height from source.

**Comment by photopea** [comment]
I fixed it. When you copy from artboard, the new document has a size of the current artboard.
