### ISSUE TITLE
Replace mask if dragging the other mask in

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2950]
If we want to drag a mask into a layer which already have a old mask, we have to delete the old mask first. 
Would it be better that the old mask would be replaced if we drag a mask to the layer directly? In Photoshop we can do it. 
![Screenshot_20210226_211944](https://user-images.githubusercontent.com/79258245/109306964-e946b300-787a-11eb-90cd-6ffed17436d5.jpg)

**Comment by photopea** [comment]
I implemented it, it should work now.
