### ISSUE TITLE
Photopea blocked by public school network due to link to Pixabay.com

### ISSUE THREAD

**Issue by StalkinatSDHT** [photopea/photopea#2951]
Hello - I am a high school art teacher working for a public school. We have been successfully using Photopea for about a year as a replacement for Adobe Photoshop students who are learning from home on Chromebooks. This week Photpea abruptly started giving popups saying that we were blocking the ads, and the app is disabled for my students as a result. Working with my tech department, it turns out that the link in the templates feature to Pixabay.com is triggering our nannyware because Pixabay hosts pornographic content. We will NEVER be able to use Photopea.com again on the school issued Chromebooks because to do so would place us in violation of COPPA. This is a shame, and excludes Photpea.com from a big market [every student using a school Chromebook in the USA]. 

I am by necessity porting all of my assignments to Pixlr which I feel is inferior but does not have the porn link liability.

**Comment by photopea** [comment]
It makes no sense to me. Even if Pixabay.com contain any adult images, they should not be accessible to children.

Have you blocked Wikipdia too? It also contains many adult photos, e.g.  https://en.wikipedia.org/wiki/Vulva , without any age checking. Wikipedia is much more dangerous to children than Pixabay.

**Comment by dentistformyeye** [comment]
@photopea Does the safe-search setting for image searching (#2604) apply to template images?

@StalkinatSDHT If your school doesn't think the safe-search restriction is enough to satisfy COPPA, would it be possible for the tech department to block only third-party resources from loading on the www.photopea.com domain? Wholesale blocking seems a bit heavy-handed.

**Comment by StalkinatSDHT** [comment]
Thanks for your quick reply. I will forward this to my tech department! I
will follow up to let you know what the outcome is.

**Comment by photopea** [comment]
If there are any adult images at Pixabay, they are never displayed by Photopea, and can not be accessed through Photopea.

**Comment by photopea** [comment]
I will close it now.
