### ISSUE TITLE
The lower edge of menu of adjustment layer is too low in small screen

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2953]
![Screenshot_20210227_044510_com android chrome](https://user-images.githubusercontent.com/79258245/109354990-8c1e2200-78b9-11eb-8542-c2caf9d225f9.jpg)
In my device, sometimes clicking on the button of adjustment layer would create a "invert" direct but I don't want. I think the edge is too low. 
 
Could you make the lower edge never cover on the buttons? 
like this image I made
![Screenshot_20210227_044510_com](https://user-images.githubusercontent.com/79258245/109355757-aa385200-78ba-11eb-8ff6-31d647e50613.jpg)

**Comment by photopea** [comment]
I fixed it. The menu will still be tall, but it should appear on the left side of the button.

**Comment by nothingshiru** [comment]
If I open photopea in portrait mode and switch to landscape mode later, the menu wouldn't be moved to left and still cover on button. 
Can it be fixed?

**Comment by photopea** [comment]
If you hide the menu and open it again, it should be displayed correctly.

**Comment by nothingshiru** [comment]
I was wrong. The problem is not about switching mode, but about language chosen. 
I'll sent a video to support@photopea.com to show you what is happening.

**Comment by photopea** [comment]
I think I have fixed it. The panel can be displayed incorrectly when you open it for the first time. But then, it should never cover a button.

**Comment by nothingshiru** [comment]
I have just tried again. The button is still being covered when choosing Chinese. 
![Screenshot_20210228_012023_com android chrome](https://user-images.githubusercontent.com/79258245/109394790-c5ab6780-7963-11eb-9e67-f332709da341.jpg)

**Comment by photopea** [comment]
I think I have fixed it. This menu should always appear above the button.
