### ISSUE TITLE
There can't be only one color left in gradient editor

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2954]
We can't delete one of them if there are only two colors. So we can't make a perfect gradient which is color to transparent, because even if setting the opacity of one side to 0%, the color of that side will still effect the gradient. 
For example
![screenshot_20210228_041445](https://user-images.githubusercontent.com/79258245/109399448-d537aa00-797d-11eb-8880-810928cf19e5.jpg)
In Photoshop we can make it only one color left.

**Comment by MichalSZZ** [comment]
I think in Photopea it work exacly  as in Photoshop. Opaxity and position can be in different place but effect is the same.

In gradient it mus be 2 or more color (even if start and end is the same color). If you want, you can set first and last color the same and on the right set opacity to 0%. Then it will be perfect gradient to transparency

**Comment by nothingshiru** [comment]
> I think in Photopea it work exacly as in Photoshop. Opaxity and position can be in different place but effect is the same.
> 
> In gradient it mus be 2 or more color (even if start and end is the same color). If you want, you can set first and last color the same and on the right set opacity to 0%. Then it will be perfect gradient to transparency

have a look at this screenshot
![Screenshot_20210228_052330_com huawei browser](https://user-images.githubusercontent.com/79258245/109400722-30b96600-7985-11eb-803d-183db19ffe87.jpg)

**Comment by photopea** [comment]
I fixed it :) now, you can have just one color stop and one transparency stop.

**Comment by nothingshiru** [comment]
The slider of opacity would be deleted if my mouse over this line while dragging it. 
![screenshot_20210302_162037](https://user-images.githubusercontent.com/79258245/109619227-7cc9fd80-7b73-11eb-8785-f2ef3eefb543.jpg)

https://user-images.githubusercontent.com/79258245/109619257-85223880-7b73-11eb-93fa-ad9964b7dffd.mp4

**Comment by photopea** [comment]
I think I have fixed it. Does it work better now?

**Comment by nothingshiru** [comment]
OK now
