### ISSUE TITLE
A name of step in history is incorrect

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2955]
Hold Alt key and drag one handle of a anchor point when using pen tool, the step is called add anchor point. It is incorrect.
And I have found another problem. We can't drag one handle by holding Alt key when using direct select tool.

**Comment by photopea** [comment]
I renamed the step, when you just move the anchor with the Pen tool.

In Direct Select, you should double-click the middle point to switch between linked (circle) / unlinked (square) point. But I added your feature - you can hold Alt to turn linked into unlinked now.

**Comment by nothingshiru** [comment]
When I'm using pen tool to click on anchor to delete it, the step appeared is Add Anchor Point. It's incorrect.

**Comment by photopea** [comment]
It should be fixed now.
