### ISSUE TITLE
"Again" in edit - transform is not working correctly

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2956]
It should duplicate layer and transform again, like the shortcut Shift+Alt+Ctrl+T do in Photoshop.In Photopea it just transform again but didn't duplicate.
There was "Shift+Alt+Ctrl" written beside the option, but in fact it is like Shift+Ctrl+T do in photoshop.

**Comment by photopea** [comment]
Actually, current web browsers do not allow us use the Ctrl+T shortcut (a browser always opens a new browser tab, it never tell the website that the user pressed Ctrl+T). Shift+Ctrl+T opens a new browser tab, too.

We found, that Alt+Ctrl+T does not open a new browser tab. So Alt+Ctrl+T and Shift+Alt+Ctrl+T  are the only shortcuts we can use. So we can not support as many shortcuts as native apps (e.g. omitting Alt).
