### ISSUE TITLE
Features requests

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2957]
1. Setting center point by holding Alt and click
The center point I'm saying is the point that the image would rotate around when transforming. 
In Photoshop you can hold Alt key and click the place where you want it to be to set its place

2. Measuring angle by ruler tool
When already created a ruler, hold Alt and drag to create second ruler from the end point of the first ruler. And we can see the degree between two rulers and the lengths of two rulers.You can do it in Photoshop too.

**Comment by photopea** [comment]
I implemented both :)
