### ISSUE TITLE
Amount of slices is not right when use "Slices from Guides"

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2958]
Slices have been created more than expected. 
![New Project](https://user-images.githubusercontent.com/79258245/109420516-ea5c1980-7a0d-11eb-8712-773da8186583.jpg)
  
Besides, I think we need a option to be able to delete all slices by one click. A clear option, you can put it below the option which is called Guides from Layer in top menu View, as same as Photoshop.

**Comment by photopea** [comment]
I think I have fixed the problem. BTW. you can keep commenting a closed issue, there is no need to open a new one.

**Comment by nothingshiru** [comment]
OK, I get it.
