### ISSUE TITLE
Issues and feature requests about ruler tool

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2959]
Issue
1. The first ruler became invisible once drew second ruler to measure angle. 
![IMG_20210228_221358](https://user-images.githubusercontent.com/79258245/109421757-9f450500-7a13-11eb-8eae-70ffb4d2b321.jpg)
2. The whole ruler became invisible once switch to other tools and switch back. 
 
Feature request
1. Displaying lengths of both rulers when measuring angle. 
2. Add a clear button in ruler tool so that we can clear ruler manually during using ruler tool. 
![@MOXC22U0NW@BY8S6}AT9}W](https://user-images.githubusercontent.com/79258245/109442280-b404b580-7a72-11eb-9bbb-421a6c8bb42a.png)

**Comment by photopea** [comment]
I think I have fixed everything that you asked for :)

**Comment by nothingshiru** [comment]
There is a circular cursor on the point of ruler that I click recently, If I have just used brush tool. 
![screenshot_20210302_003858](https://user-images.githubusercontent.com/79258245/109528789-00420b00-7af0-11eb-9d6b-9f62c199407c.jpg)

**Comment by photopea** [comment]
Sorry, it is fixed now, too.
