### ISSUE TITLE
again, vector bug

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#2960]
when I move any shape, its whole style doesn't move,
![Screenshot (83)](https://user-images.githubusercontent.com/70863817/109428141-5767b300-79fe-11eb-8b18-fa1f999296b7.gif)

**Comment by photopea** [comment]
Could you try the same PSD in Photoshop? I think it works the same.

**Comment by mustafaGFX** [comment]
I did, it doesn't work like that in photoshop, and it never has been working like this in photopea too and I shouldn't, I use photopae to design vectors every single day,

**Comment by photopea** [comment]
Could you send me the PSD to support@photopea.com ?

**Comment by mustafaGFX** [comment]
oh, the problem has been fixed :)
thank you :)

**Comment by photopea** [comment]
There was no problem, you just do not know Adobe Photoshop very well :P

**Comment by mustafaGFX** [comment]
nop :)
I know adobe photoshop very well cuz it's my main design program, I just use photopea to get some specific Tasks done.
I think my pc was a little bit tired
