### ISSUE TITLE
photopea has fcking problems

### ISSUE THREAD

**Issue by vemperior** [photopea/photopea#2961]
I AM TRYING TO MAKE STUFF, AND IF F-ING ALWAYS SAYS "We use an advertisement to earn money," BLAH BLAH BLA NOBODY CARES, I FREACKING TURNED OF MY AD BLOCKER AND STILL, IT FREAKING DOESNT WORK!!! FUCK YOU

**Comment by mustafaGFX** [comment]
don't cry

**Comment by photopea** [comment]
Hi, I am very sorry for the inconvenience. Please, try our tutorial to learn how to make your computer stop blocking ads in Photopea: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/
