### ISSUE TITLE
Can't create a anchor without handles easily sometimes

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2962]
Because of a little imperceptible distance that my mouse moved after click. 
![screenshot_20210301_112657](https://user-images.githubusercontent.com/79258245/109481116-5b0b4080-7ab7-11eb-92e3-3226d4ed968d.jpg)

Zoom in to the limit. You can see how short the distance is. Nobody would create a anchor with handle like this. 
![screenshot_20210301_180001](https://user-images.githubusercontent.com/79258245/109481860-44191e00-7ab8-11eb-8ec5-b7ef649e7326.jpg)
 
In my opinion, if the point of the handle have covered the anchor in users' view when create a new anchor, the handle should not be created.

**Comment by photopea** [comment]
Maybe it is a bug in a hardware. If your mouse moves by 0.1 mm, the computer should not consider it as a movement.

Does it really happen with a mouse? Or you are using a finger?

**Comment by nothingshiru** [comment]
yes, I'm using mouse on tablet. I have also found that somgtimes the anchor didn't appear in the place I click on exactly. 

https://user-images.githubusercontent.com/79258245/109512373-ffed4400-7ade-11eb-9579-95b6472cda9a.mp4

**Comment by MichalSZZ** [comment]
I have similar feeling... when i make shape with pen tool and I make only clicks by mouse. It looks like all corners are sharp - but when I try to round it I have info about that "only sharp corners can be rounded". And when I'm zoom in I see that not all of them are sharp and they have handlers.

**Comment by nothingshiru** [comment]
> I have similar feeling... when i make shape with pen tool and I make only clicks by mouse. It looks like all corners are sharp - but when I try to round it I have info about that "only sharp corners can be rounded". And when I'm zoom in I see that not all of them are sharp and they have handlers.

Yeah, if we want the handle we gotta zoom in to drag it. It's annoying.

**Comment by photopea** [comment]
It looks like your device performs "mousemove" to the same point right after click (so I would say it is a bug in your browser).

I changed it a bit. Now you need to move a mouse at least 2 pixels, to make Photopea interpret it as moving handles. Does it work better now?

**Comment by nothingshiru** [comment]
It's much better with finger, need to move 1 pixel to create handle now. But mouse seems to be not limited. 

In this video, the upper path is created with mouse, the lower path is created with finger. 

https://user-images.githubusercontent.com/79258245/109523190-0a610b00-7aea-11eb-948a-86a59c8c9709.mp4

**Comment by photopea** [comment]
I think I improved it, does it work better?

**Comment by nothingshiru** [comment]
It's great now.

**Comment by photopea** [comment]
Yes, the Pen tool puts points on a pixel grid in Adobe Photoshop, too.
