### ISSUE TITLE
Feature request, export options in server api

### ISSUE THREAD

**Issue by Nils-1st-retail** [photopea/photopea#2963]
Hi, 
In extension to the closed issue #2947 
It would be useful for the server -> formats -> SVG, to include an option to turn on vectorize text (and possible other options for the export) in the script definition in the same way as it is possible to specify the quality for a JPG or to product a minified PSD

**Comment by photopea** [comment]
I don't want to make the API over-complicated.  BTW. have you tried to vectorzie text layers in a PSD document with a script? Or maybe create an action for it with a script?

**Comment by Nils-1st-retail** [comment]
Currently I'm using the API to make a custom save function saving a png + psd + svg, using the following code 
`"formats":["png","svg","psd:true"]}`
As I understand your answer, you suggest I either vectorize all text in the psd, making it more difficult to change the text later if needed since it's not 'text' anymore. 
Or create a secondary script to export the svg to my server, that I can trigger in the return value from the custom save opperation?

**Comment by photopea** [comment]
These options of SVG export are not present in any other program, and I think they could change in the future, so I am afraid of offering a specific interface for SVG export parameters, which could be changed very soon.

Yes, use scripts and actions to modify your PSD, so that the export to SVG does not require any additional parameters.

I will close it, but we can keep discussing it.

**Comment by Nils-1st-retail** [comment]
Just for clarification, theres no way for me with the api to make an export to svg having all text being vectorized, while still keeping the PSD with non vectorized text like I can do via the menues when exporting to svg?

I guess I could make the script to vectorize the text in the PSD then export, and then reverte the history to undo the changes. If I can undo via scripting too.

**Comment by photopea** [comment]
I thought you are not saving a PSD back to server. It will be vectorized only in RAM, without saving your PSD anywhere.

Yes, you should be able to undo via script, too.

**Comment by Nils-1st-retail** [comment]
I'm saving SVG to the server for serving on the website allowing crawlers to index etc.
Then I'm saving the PSD to the server too, to allow edits to the canvas in the future. That's why I would like the PSD to remain text for those further edits, instead of becoming vectors in the PSD

**Comment by Nils-1st-retail** [comment]
I have tried to make a script that vectorizes or rasterizes all text elements, and that works. My problem is that when doing it like this, I don't get a added benefit of having the new "arial-label" attribute on the svg export of the text that was added in #2947 

I can see that there's an exportDocument option in the scripting, but I can only set the first export option for svg in that one, not all 5.

**Comment by photopea** [comment]
Ok, you can specify SVG export parameters now after the colon: "svg:true,true,true...", as described here: https://www.photopea.com/learn/scripts

**Comment by Nils-1st-retail** [comment]
Super, that's fantastic :)
Thank you very much for the help
