### ISSUE TITLE
Feature Request: Vertical Typing

### ISSUE THREAD

**Issue by SunbeamStarship** [photopea/photopea#2966]
I think the ability to type vertically as well as horizontally would increase the versatility of the text tool. This feature is in Photoshop but very few other programs that I am familiar with.

**Comment by photopea** [comment]
Hi, could you send me a PSD with vertical text to support@photopea.com ?

**Comment by nothingshiru** [comment]
> Hi, could you send me a PSD with vertical text to [support@photopea.com](mailto:support@photopea.com) ?

Because I didn't see his reply, I have sent you a PSD file with vertical typing.

**Comment by photopea** [comment]
thanks, I am working on it now :)

**Comment by photopea** [comment]
I made this PSD file with two identical text layers.

But the distance between lines in the first layer is bigger than in the second layer. Do you know why is that?
[Vertical typing.zip](https://github.com/photopea/photopea/files/6102965/Vertical.typing.zip)

**Comment by nothingshiru** [comment]
Maybe it is about the version of photoshop I used. 
I have just tried horizontal typing and it has the same line spacing. 
[V and H.zip](https://github.com/photopea/photopea/files/6105747/V.and.H.zip)

The setting of line spacing is default. 
![$CFAQQ@ICNUNPQ`` @C~@AT](https://user-images.githubusercontent.com/79258245/110416286-69b4b180-80ce-11eb-8ffd-f6bb6b6d6f8f.png)
自动 means automatically.

**Comment by nothingshiru** [comment]
I'll try it tomorrow.

**Comment by nothingshiru** [comment]
Well, I have just tried it. 
I can create the same text layer by changing line spacing manually. 
![UNXY7)D~ S@P4R432 K(P{4](https://user-images.githubusercontent.com/79258245/110491398-36087480-812c-11eb-8dc5-f2255e2ed471.png)
![6 {0ZAEP6LN@O3CEQ3ZZ7TS](https://user-images.githubusercontent.com/79258245/110491421-3b65bf00-812c-11eb-9c2a-046dbd38acf7.png)
[New Vertical typing.zip](https://github.com/photopea/photopea/files/6109384/New.Vertical.typing.zip)

**Comment by photopea** [comment]
But the original layer has Automatic line spacing. So you should be able to recreate the same text layer somehow.

**Comment by photopea** [comment]
I implemented the basic vertical typing.
