### ISSUE TITLE
Feature Request: AVIF support

### ISSUE THREAD

**Issue by josephrocca** [photopea/photopea#2967]
* Previous (closed) issue: https://github.com/photopea/photopea/issues/2242
* AVIF support will soon be in all major browsers: https://caniuse.com/avif
* The visual quality of AVIF vs WEBP at the same file size is significantly better: https://jakearchibald.com/2020/avif-has-landed/demos/compare/?show=f1&img=/c/f1-match-7a06c7c4.webp
* Encoder and decoder are already available as open source WASM modules: https://github.com/GoogleChromeLabs/squoosh/tree/dev/codecs/avif (and you can see them in action here: https://squoosh.app/)

Cheers!

**Comment by photopea** [comment]
Do you really have AVIF files in your computer, which you were not able to open with Photopea? Or you just read some articles and got excited about the new format?

Each new feature makes Photopea bigger. Now, Photopea is around 2 MB (e.g. JPG decoder is only 6 kB), and adding 1 MB of AVIF decoder sounds stupid to me.

**Comment by josephrocca** [comment]
Oh, I'd definitely load the uncommon/large codecs lazily! But I agree 100% that it's still niche. I use Photopea all the time and today was the first time that I had a need for AVIF, and my use case is not a common one. I was considering using the format for part of a machine learning pipeline and wanted to quickly create a few little test images. There are other tools like squoosh that can do the conversion, so it's really just a "nice to have" - not worth it if it takes your time away from more important features. I'll close for now. Cheers!

**Comment by photopea** [comment]
I have added the support for AVIF files by decoding them through a browser (so it works only in browsers with AVIF support in <img> element).

**Comment by photopea** [comment]
BTW. people open 10,000 AVIF files in Photopea every day. It is the 9.th most opened format (after PNG, JPG, PSD, WEBP, SVG, PDF, AI and GIF).

**Comment by choephix** [comment]
@photopea Awesome! Any plans to support exporting as AVIF?

**Comment by photopea** [comment]
Since AVIF is a complex format, we will wait until browsers offer the AVIF encoder, see https://stackoverflow.com/questions/61206083/create-image-from-canvas-with-avif-image-format

For now, you can use a plugin! Press Window - More - Plugins, look for the AVIF plugin. Use "Save AVIF" in that plugin.

**Comment by choephix** [comment]
Awesome, thanks!
