### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2968]
**Shortcuts**
1. Holding key of tool to switch to that tool temporarily.
For example, when you are using brush tool, you can hold the E key to switch to eraser tool, once you release the E key, you will come back to brush tool.

2. Change the shortcut of rotate view tool to R key, like Photoshop.
3. Double clicking on the icon of hand tool in toolbar to reset the degrees of canvas if canvas have been rotated.

**Curves**
1. Hand tool
Clicking on image will create a corresponding point on curve in rgb channel.Holding shift+ctrl and clicking will create points on curves in r/g/b channels.If click and drag upward/downward, the point will be controlled.

2. Input and Output
The value of point can be change precisely.

3. Reset
Clear the points added. 

4. Sliders at bottom

5. Default points undeletable
Now if having 3 or more points on curve, when control the rightmost/leftmost points along border, the points are too easy to be deleted
![)_YDOIG1ZXP5AD HD1JEYR4 (1)](https://user-images.githubusercontent.com/79258245/109629445-cbc96000-7b7e-11eb-8ac4-5913bb3cd979.png)

**Comment by mustafaGFX** [comment]
that's why I love photoshop, small details make a bid deference ❤️

**Comment by photopea** [comment]
Shortcuts

1) I think there are many people used to pressing E to enable the Eraser permanently. If we disable the Eraser after releasing E, it will confuse many people.
2) In our case, all tools in a same group should have the same key.
3) Implemented

Curves
1) Added this option, next to choosing white - black - middle colors
2) I think it is not important, only makes things complicated
3) There is the Reset button on the right side of every adjustment
4) I think it is not important, only makes things complicated
5) Fixed

**Comment by nothingshiru** [comment]
Shortcuts

1. Does it really confuse people? I don't think people would keep holding the key of tool while they are using the tool.
2. But in the devices with small screen, the tools that have different key can go to a same group.
3. I think the icon of rotate view should have this functionality too, because most of time that canvas has been rotated means people have chosen rotate view tool, the icon of hand tool has become the icon of rotate view tool. I'm very sorry that I didn't notice this point.
![Screenshot_20210303_041851](https://user-images.githubusercontent.com/79258245/109709531-97ce5900-7bd7-11eb-9f6b-d8e3b126888c.jpg)

Curves

1. It doesn't work in adjustment layer, the "Sample from image" has the same issue.Could they be fixed? 
Could they be unselected? If we are adjusting curves or levels, we can't move or zoom in/out the canvas now.
2. Maybe it is not important.
3. But there isn't the button in adjustment layer.
4. Yeah, it is not important.

**Comment by photopea** [comment]
Double-clicking the Rotate View tool will reset the rotation to 0. Double-clicking the Hand tool changes the zoom to Fit the screen.

I added the Reset button to the settings of adjustment layers. Sampling from image is a separate topic, I added it here: https://github.com/photopea/photopea/issues/2969
