### ISSUE TITLE
saveToOE is bigger than save from menu

### ISSUE THREAD

**Issue by busaway** [photopea/photopea#2970]
Hi, I tried saveToOE script but apparently file size is bigger than saving from menu

saveToOE("webp:0.03") => 510KB
and menu option quality is 3% => 243KB

also for happen when save to PNG 

is there any more step for compressing the result?

**Comment by photopea** [comment]
I tried to reproduce it at https://www.photopea.com/api/playground .

I run a script: app.activeDocument.saveToOE("webp:0.03");  and it returns a buffer of 8640 Bytes. Then, I try to export it as WEBP with a quality of 3%, it also shows a size of 8640 Bytes. 

You can not set the quality of a PNG after the colon. It is possible only for JPG and WEBP, see here: https://www.photopea.com/learn/scripts

**Comment by busaway** [comment]
I see so PNG can't set quality from script.
I think because I use animated PNG and save it to animated webp 
![image](https://user-images.githubusercontent.com/1103263/109800140-698c6000-7c4f-11eb-8dca-bb500d45b032.png)

**Comment by photopea** [comment]
I found a bug and fixed it. Exporting animated WEBP through the API should work well now.
