### ISSUE TITLE
The points around image didn't change after applied mask

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2973]
Original image
![screenshot_20210304_003238](https://user-images.githubusercontent.com/79258245/109839557-2c8d9100-7c82-11eb-9a5c-ade29c78ce5d.jpg)
Mask
![screenshot_20210304_003358](https://user-images.githubusercontent.com/79258245/109839589-34e5cc00-7c82-11eb-8d64-950f0a6bfb9b.jpg)
Applied mask
![Screenshot_20210304_003944](https://user-images.githubusercontent.com/79258245/109839613-3dd69d80-7c82-11eb-8610-eeed783c3a74.jpg)

**Comment by MichalSZZ** [comment]
I think it's work good. Like in Photoshop. You have raster mask. That mask type have not points to controle the shape of mask. You can do it if you have vector mask. But points when transformin layer will be displayed from shape.

**Comment by photopea** [comment]
@MichalSZZ it is about Applying a mask to a layer (combining it with pixels, the layer mask disappears). 

I fixed the problem. It should work better now.
