### ISSUE TITLE
Cannot copy image to clipboard

### ISSUE THREAD

**Issue by xvdg06** [photopea/photopea#2974]
**Reproduce:**
1. Select the image
2. Click Edit > Copy
3. Observe: Image is not copied to the clipboard

**System info:**
- OS: Windows 10 Pro for Workstations
- Browser: Firefox 86.0 (64-bit)

**Comment by photopea** [comment]
Try this: 

**Reproduce:**
1. Select the image
2. Click Edit > Copy
3. Click Edit > Paste, image is pasted as a new layer

That is the best we can do. Firefox is quite a bad browser and does not allow a website to put an image into a system clipboard.

Recently, Firefox implemented image-set, six years later than Chrome. So maybe in 2027, Firefox will let websites copy images into a clipboard.

Whenever we asked Firefox to add some new feature, their response was like "websites are not supposed to do that, it is too dangerous". So we do not ask them anything anymore.
