### ISSUE TITLE
Alt key remains detected if released before mouse button in alt-drag duplication

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#2976]
Photopea continues to detect the alt key if I release the alt key before the mouse button while duplicating a layer using alt-drag.

## Steps to reproduce

1. After ensuring that extensions are disabled, open a new project in Photopea.
2. While holding down the alt key, click and hold on the layer in the Layers panel. Without letting go of either button, drag the mouse down by a centimeter.
3. Release the alt key first. Then release the mouse button.
4. Without holding any key, click and drag the bottom layer in the Layers panel down by a centimeter, then release the mouse button.

## Expected result
Neither step 3 nor step 4 should duplicate the layer. (If Photoshop also duplicates the layer in step 3, then you could keep that behavior.)

## Actual result
Both step 3 and step 4 duplicate a layer. There are now three layers.
Clicking an eye icon next to one of the layers will turn off the visibility of the other layers. If the freehand brush tool is selected before step 2, the cursor will be a cross corresponding to the temporary eyedropper.

## Additional notes
Tapping the alt key after step 4 ends the bug.

**Comment by photopea** [comment]
I can not reproduce it in Chrome on Windows.

It is a known bug in Firefox, which has to be fixed by Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1568130

**Comment by dentistformyeye** [comment]
I reproduced it on a Chromium browser on Mac and Chrome on Windows. Both browsers were on version 89.0.4389.72, the latest stable versions.

**Comment by photopea** [comment]
I can reproduce it now, I made a smaller case and reported it to google: http://jsfiddle.net/kyuz3w9f/1/ . Let's see what they say.

**Comment by photopea** [comment]
Sadly, it seems like there is no way to fix it.

The standard explicitly tells the browsers, that if any element is dragged, keyboard events should not be told to a webpage: https://html.spec.whatwg.org/multipage/dnd.html#:~:text=From%20the%20moment%20that%20the%20user%20agent%20is%20to%20initiate%20the%20drag-and-drop%20operation%2C%20until%20the%20end%20of%20the%20drag-and-drop%20operation%2C%20device%20input%20events%20(e.g.%20mouse%20and%20keyboard%20events)%20must%20be%20suppressed.

So you have to release Alt only after you stop dragging a layer.

**Comment by dentistformyeye** [comment]
That's fine. Thanks for letting me know.
