### ISSUE TITLE
Magic Wand Problem...

### ISSUE THREAD

**Issue by elinarodin** [photopea/photopea#2978]
When I select images with the magic wand, the whole image is being selected (not just the background), what should I do?

![Screenshot 2021-03-05 at 1 53 10 PM](https://user-images.githubusercontent.com/80131129/110177636-269acb80-7dba-11eb-96f3-9a06247eb382.png)

**Comment by photopea** [comment]
Hi, you set the Tolerance to a very high number. Set it to a smaller number and enable Contiguous. See here: https://www.photopea.com/learn/advanced-selecting

**Comment by elinarodin** [comment]
Thank you so much!
It worked!!!!
