### ISSUE TITLE
Suggestion: Export css

### ISSUE THREAD

**Issue by LorincJuraj** [photopea/photopea#298]
HI. Just one quick suggestion. It will be great to be able to export css of all Text layers. Best case scenario, it will also export the layers text (as a comment). I am pretty sure, this will be very handy for web developers.

The result could look something like this

```
/*Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet voluptatem error quis ducimus dolor amet culpa nobis placeat nulla optio nihil aliquid, modi, eligendi facilis veritatis enim, perferendis?*/
#layer_name{
	font-size: 24px;
	color: rgb(0,0,0);
	font-family: "DejaVuSans";
}


/*Saepe voluptates, beatae at quos ipsum neque quis repellat illo nisi magnam distinctio, animi ut! Aperiam quae iste facere excepturi illum reprehenderit eveniet architecto neque similique. */
#another_layer_name{
	font-size: 34px;
	color: rgb(255,0,0);
	font-family: "DejaVuSans";
}


/*Ipsum accusantium est odit facilis, cupiditate tenetur aliquam non sit, culpa ad iusto. Adipisci, distinctio beatae eius est quod ipsam magnam neque voluptatum totam numquam necessitatibus perferendis vero dicta consequatur officiis amet quaerat qui maiores. Sed suscipit, quasi assumenda in sunt, nostrum blanditiis ad. Necessitatibus, consectetur.	*/
#last_layer_name{
	font-size: 14px;
	color: rgb(0,0,0);
	font-family: "DejaVuSans";
}
```

I doesn't need to be valid CSS. I mean if layer is called `Some layer name` the result coud look even something like this:
```
/*Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet voluptatem error quis ducimus dolor amet culpa nobis placeat nulla optio nihil aliquid, modi, eligendi facilis veritatis enim, perferendis?*/
Some layer name{
	font-size: 24px;
	color: rgb(0,0,0);
	font-family: "DejaVuSans";
}
```

or maybe like this:
```
/*Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet voluptatem error quis ducimus dolor amet culpa nobis placeat nulla optio nihil aliquid, modi, eligendi facilis veritatis enim, perferendis?*/
/*Some layer name*/
#layer1{
	font-size: 24px;
	color: rgb(0,0,0);
	font-family: "DejaVuSans";
}
```

**Comment by photopea** [comment]
I would not use the name of layers. In most cases I have seen, people do not use nice names.

Including the text of the layer in the comment is a nice idea. But if we export the CSS for the whole PSD, authors would have to edit it for their own purposes. What about exporting the whole PSD as HTML? We can already epxort PSD as SVG, so it would be very similar.

**Comment by LorincJuraj** [comment]
> I would not use the name of layers. In most cases I have seen, people do not use nice names.

That's true. But there should be some identifier. Even if it would be `layer1`

> Including the text of the layer in the comment is a nice idea.

This way it would serve two purposes - exporting styles and exporting content at the same time.

> But if we export the CSS for the whole PSD, authors would have to edit it for their own purposes. What about exporting the whole PSD as HTML? We can already epxort PSD as SVG, so it would be very similar.

In my experience, computer generated code (css or html) is always messy and you can not use it as it is anyway and need to edit it anyway. I think exporting html would just cause more mess in the code. But that's just my opinion.

BTW I have found one missing think and it is kind of a deal breaker for me - in current CSS the font style are not complete - there are missing thinks like `line-height` and `letter-spacing` which means I still need to use Photoshop. If this would work, Photopea would probably be great Photoshop replacement for web developers (maybe not enough for designers yet, but definitely for developers).

**Comment by photopea** [comment]
You say, that computer generated HTML would be messy. But one big CSS file for the whole PSD would be messy too, wouldn't it?

How do you get line-height and letter-spacing in Photoshop?

**Comment by LorincJuraj** [comment]
Yes, it definitely would be, but I thought you want to export html AND css which would be more messy then just css. And my idea was just to export css for text layes, so it would be just 20-30 elements tops which is acceptable.

Or maybe exporting just selected layers, but I guess I would still prefer export of all text layers. It might become messy but still better then switching to editor 20-30 times and exporting the layers one by one.

**Comment by photopea** [comment]
How do you get line-height and letter-spacing in Photoshop?

**Comment by LorincJuraj** [comment]
This is example output of Photoshop

```
.Sed_ut_perspiciatis_unde_omnis_iste_natus_error {
  font-size: 17px;
  font-family: "Myriad Pro";
  color: rgb(78, 77, 77);
  line-height: 1.294;
  text-align: justifyLeft;
  position: absolute;
  left: 302.175px;
  top: 697.77px;
  width: 879px;
  height: 60px;
  z-index: 94;
}
```
 It exports line-height but doesn't the letter-spacing (which is pretty annoying), but I am still able to check it using `Character` window (it is labeled as `Set the tracking for the selected characters`. I haven't find a way to see this on Photopea.

**Comment by photopea** [comment]
We also have Character window in Photopea.

Do you think that properties "left, top, width, height, z-index"are necessary for text layers? Should we add them too?

**Comment by LorincJuraj** [comment]
I have somehow missed the Character window in Photopea - thanks.

And regarding the positioning attributes (left, top etc) - I have never used them, but somebody might like them. I don't know.  I would suggest  to do it without them, so you want waste your time developing something nobody will actually use and in case people will ask for that implement it later.

**Comment by photopea** [comment]
Hi, I improved the CSS export, it adds letter-spacing and line-height properties into the output CSS.
