### ISSUE TITLE
There is always a same area painted with red in magic cut

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2981]
When you open magic cut first time,  you can see the edge of image is painted with red. 
![screenshot_20210307_011323](https://user-images.githubusercontent.com/79258245/110215429-bf2d6a80-7ee4-11eb-8cd1-0de1f58299e9.jpg)

**Comment by photopea** [comment]
Yes, I know. Do you know any better way how to guess what is definitely a background?

**Comment by nothingshiru** [comment]
You can let users do it manually.

**Comment by photopea** [comment]
The user can press "Clear" at the top and do it manually. But in your case, you can just erase a bit on a horse with the Grey color.
