### ISSUE TITLE
zoom in bug

### ISSUE THREAD

**Issue by LETMESAYMYISSUE1128726821** [photopea/photopea#2983]
when i zoom out with -, and then i press + it still zooms out. kinda annoys me a little.

**Comment by photopea** [comment]
Hi, it should not zoom when you press Plus or Minus. The shortcuts for zooming are Ctrl+Plus and Ctrl+Minus.

What kind of device do you have? Are you pressing keys on a keyboard or something else?

**Comment by LETMESAYMYISSUE1128726821** [comment]
when i hold down command too, sorry for the misunderstanding.

**Comment by photopea** [comment]
I tried it on my Macbook, Command and Minus works correctly, but I can not find the Plus key on the keyboard.

Do you have a Plus key on your keyboard? Is there still a problem if you close Photopea and open it again?

**Comment by LETMESAYMYISSUE1128726821** [comment]
it works when i let go of the command key, just annoys me. i do have plus.
i hold command, press minus, let go of minus, (not command), press plus and
it zooms out instead of in. nothing really.

**Comment by dentistformyeye** [comment]
It probably has to do with a bug in MacOS that I learned about here: [#2191](https://github.com/photopea/photopea/issues/2191#issuecomment-639075103).
You'll just have to let go of the command key every time you want to use a different shortcut.

**Comment by LETMESAYMYISSUE1128726821** [comment]
ah ok

**Comment by photopea** [comment]
Yes, right, so this is the bug in Mac OS. It is hard to tell if and when will Apple fix it :(

BTW. you can use the Ctrl key instead of Command. It works the same in Photopea and does not have such bug.
