### ISSUE TITLE
Points around the images not appearing 

### ISSUE THREAD

**Issue by Boobica** [photopea/photopea#2985]
When trying to move and resize images the points that normally around the image aren't appearing.

**Comment by photopea** [comment]
Maybe you disabled the Transform Controls of the Move tool. Do you know where are Transform Controls?

**Comment by Boobica** [comment]
No I don't. Would you be able to explain or direct?

________________________________

**Comment by photopea** [comment]
I don't really understand what you need. But I just thought maybe you disabled the Transform Controls of the Move tool.
![image](https://user-images.githubusercontent.com/15955558/110259986-af785980-7faa-11eb-98d0-5d7e261d50c6.png)

**Comment by photopea** [comment]
You did not even mention what tool you are using. I recommend you to read our manual to learn what tools are: https://www.photopea.com/learn/workspace

**Comment by Boobica** [comment]
yes that was it. Thank you so much!

Sorry, I am a beginner, thank you so much for your help!

________________________________
