### ISSUE TITLE
The action that changing blend mode of folder is recorded wrong

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2987]
Changing the blend mode of a folder would be recorded wrong. The action will set the blend mode to the next one. 
For example, 
I set the blend mode to normal, the action will set it to dissolve;
I set the blend mode to luminosity, the action will set it to pass through.

**Comment by nothingshiru** [comment]
I have found another wrong action. The "crop" became changing canvas size.

**Comment by photopea** [comment]
I fixed the problem with recording the blend mode change of a folder.

The cropping can be always done with Image - Canvas Size. There is no way to distinguish if an action was made with Canvas Size or the Crop tool.

**Comment by nothingshiru** [comment]
There are some other issues about recording action.

1. "Bring to front" and "Bring forward" doesn"t work.
The action "Move Layer" was recorded into action panel, and when I used the action, the step "Layer Order" appeared in history panel, but the layer was not moved at all.
"Send to back" and "Send backward" works.

2. "Merge down" and "Merge layers" can't be recorded.
In Photoshop they can be recorded. And I have record a action containing one of them in Photoshop. That action can work in Photopea.

**Comment by photopea** [comment]
Our support for actions is very basic. At the moment, we focus at executing .ATN files correctly. Photopea can not record actions properly now.
