### ISSUE TITLE
URGENT!!! Photopea says: - No memory enought!!!

### ISSUE THREAD

**Issue by luisckc** [photopea/photopea#2988]
Hi. I had problems with memory to run Photopea, with 8GB + 6GB of the video card. I talked to you through report # 2796 (I ask you to see the details there). I now have 16GB + 6GB. I no longer have advertisements loading too often and crashing everything, as I now have the premium version of Photopea. Today it is impossible to work, as it locks frequently and only closes the browser (losing what I did, because it doesn't even save) and opening again. Notice in the attached photo that there is memory and processing left over. Now and then problems of this kind and others have happened and I don't know what else to do ...
![RAM](https://user-images.githubusercontent.com/67866380/110527538-d7280880-80f5-11eb-9205-00a1cdc5513d.png)

**Comment by photopea** [comment]
What web browser are you using? Is it updated? Maybe your browser just kills every website that uses more than 3 GB of RAM. If you do something and browser kills Photopea, can you do the same thing in another browser, to see if it also kills Photopea?

**Comment by luisckc** [comment]
More often, I use FlashPeak Slimjet 32 bits, super light, based on
chromium. I tested it on Firefox 32 bits, same thing. Both updated.
Can Windows or the browser itself establish maximum memory for using a
website?
I was just working on the Slimjet again and I managed to do everything
without any crashes, in the same file. Sometimes with a delay in loading a
layer. It happened sometimes, but today it was happening all the time. Now
it has improved a little. Was something done? Did Photopea happen to run on
64-bit browsers?

Em ter., 9 de mar. de 2021 às 16:51, Photopea <notifications@github.com>
escreveu:

**Comment by luisckc** [comment]
I need to work with files at 600 DPI / PPI. If I had a more robust machine,
I would use the standard of photographers that is 1200 DPI / PPI ... I
can't work below 600 ... And I don't have the money to buy Photoshop ...
That's why I signed up for Photopea Premium .. .
I am testing on the latest version of the Microsoft Edge 64 bit browser and
it has not crashed once ...
I ask again if Photopea was programmed for 64-bit browsers ...

Em ter., 9 de mar. de 2021 às 17:38, Photopea <notifications@github.com>
escreveu:

**Comment by photopea** [comment]
Websites can not be made for a specific browser. A website is a HTML code like <html>, <body> etc. It is like saying if some JPG file was made for a 64-bit image viewer, or if a MP3 file was made for a 64-bit audio player. Websites, songs, etc. are not made for a specific processor like Intel or AMD.

What version of Chromium is used in FlashPeak Slimjet? Many experimental browser use 3 year old Chromium in their latest releases. Otherwise, report the problem to the creators of FlashPeak Slimjet.

You still did not tell me the size of your image. 600 DPI for 10x10 inches needs four times more memory, than for 5x5 inches document (because the area is four times larger).

**Comment by luisckc** [comment]
I use 32 bits because they are faster and take up less memory. Slimjet
Version 29.0.2.0 (based on Chromium 87.0.4280.66) (Official version) 32 bits
You're right. When searching the internet, I found that 32-bit applications
have difficulties with files larger than 2GB. I will install 64-bit
versions and test better. If there was no crash on the Edge (64 bits),
maybe there is the answer. Thanks for the help. I will do several tests. I
ask if you want feedback ...

Em ter., 9 de mar. de 2021 às 19:35, Photopea <notifications@github.com>
escreveu:
