### ISSUE TITLE
Command button is not working on MacOs as it should

### ISSUE THREAD

**Issue by photoelf** [photopea/photopea#2989]
Instead of Command button it is Contol button now, so instead of Cmd+A, Cmd+C, Cmd+V MacOs have to use Ctrl+A, Ctrl+C, Ctrl+V which is unnatural for mac users.

It is the same in Opera and Chrome of recent versions on two different Macbook Pro 16"

**Comment by photopea** [comment]
Did it work in Photopea in the past?

**Comment by photoelf** [comment]
Yes it was until few hours (up to 6) back.

**Comment by photopea** [comment]
I am very sorry, it should be fixed now. Do a hard refresh of a website, in case your browser is still showing you a cached version.
