### ISSUE TITLE
When you open a svg-file have problems

### ISSUE THREAD

**Issue by splincode** [photopea/photopea#299]
While viewing this file in a straight line in the browser, everything is fine, but when I load it directly into the photo, everything breaks, and the essence of the problem is this:

1. I uploaded the file by reference in the photo
https://angular.io/assets/images/logos/angular/angular.svg

2. Added text there and exported as SVG

3. Then he rediscovered it in the photopee and it does not work

[angular-svg.zip](https://github.com/photopea/photopea/files/1443444/angular-svg.zip)

**Comment by photopea** [comment]
Hi, thank you very much for reporting it. We are very sorry for this error.

The problem was not with opening an SVG, but with saving SVG. We fixed it. Please do it again and export a new SVG. The new SVG should be openable in Photopea.
