### ISSUE TITLE
List of filters covered a large part of image in filter gallery in small screen

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2991]
Having a hide button would be great. 
And I also found we can't zoom the image in filter gallery because of lack of zoom tool. 

![Screenshot_20210310_031236_com android chrome](https://user-images.githubusercontent.com/79258245/110610838-96012880-81c9-11eb-8217-abf14b3944de.jpg)

Here is the filter gallery in Photoshop
![ASI$3DYTBZ3$JY37B%SCU4F](https://user-images.githubusercontent.com/79258245/110611571-4cfda400-81ca-11eb-8de1-52b5d9f02a96.jpg)
![8KPR M1}HCT)RT HK2AI686](https://user-images.githubusercontent.com/79258245/110611605-54bd4880-81ca-11eb-833f-b164760354f0.jpg)

**Comment by photopea** [comment]
Hi, could you change the webpage zoom in your browser to e.g. 70%? Does it help?

**Comment by nothingshiru** [comment]
I can't find anyway to change it in Android Chrome.

**Comment by photopea** [comment]
You can hide and unhide the filter previews now.

Also, you should be able to pinch-to-zoom with two fingers.

**Comment by nothingshiru** [comment]
I can't zoom with fingers when the image is uncovered. No response. 

I think zoom tool like in liquify filter&refine edge is more reliable.

**Comment by photopea** [comment]
Are you sure? Did you click with two fingers and move them apart? It should work both in Filter Gallery and in Save for Web window (File - Export As ...)

**Comment by photopea** [comment]
Pinch-to-zoom should also work in the main workspace over the main document.

**Comment by nothingshiru** [comment]
The problem is only happening in filter gallery.

**Comment by nothingshiru** [comment]
I have never zoom the image in "export as" before. I have just found the problem also happened in there.

**Comment by photopea** [comment]
I am sorry, there was a bug, it should work well now. When the complete image is visible, you can not move it.
