### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by Solarphoenixes** [photopea/photopea#2994]
I apply several changes to my image, however, when I click on export as png or pg, it saved a copy of the original unmodified files.

**Comment by photopea** [comment]
Hi, which export did you click? I would like to repeat it on my computer.

**Comment by photopea** [comment]
To export your document as a PNG or JPG, click File - Export As - JPG or PNG.

You can learn more about how to open or save files here: https://www.photopea.com/learn/opening-saving
