### ISSUE TITLE
Update Refine Edge

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#2995]
Make it like select and mask in Photoshop. 

**What will we have?**

1. More space to be added options. 
2. Bigger area to be displayed image. 

**How do select and mask do?** 

Remove tools and panels temporarily except these 
1. quick select tool
2. refine edge brush tool (the gray square in refine edge in current photopea is the same.) 
3. brush tool
4. lasso tool
5. hand tool and zoom tool
6. properties panel
And put all options into properties panel. 

Like this image I made. 
![Refine Edge expected](https://user-images.githubusercontent.com/79258245/110798676-5e6faa80-82b5-11eb-930c-71d27f6c605c.png)

And here is the select and mask(called refine edge in old version) in Photoshop. 
Sorry, there's no english in the Photoshop I used. 
![here](https://user-images.githubusercontent.com/79258245/110703421-b7e0c680-822e-11eb-96aa-c2ca0e9eea18.jpg)

**Comment by photopea** [comment]
We already have a different Refine Edge, and the Magic Cut.
