### ISSUE TITLE
Increase image resolution ai

### ISSUE THREAD

**Issue by coolcraftnet18** [photopea/photopea#2998]
Do you think we could get something like that? https://www.cnet.com/google-amp/news/adobe-photoshop-uses-ai-to-quadruple-your-photos-size/

**Comment by photopea** [comment]
I don't think it is useful in practice. Modern cameras have more and more pixels. All these methods usually invent new content, which often has nothing to do with the original content, and can be very misleading.

If you want to make the illustrations sharper (like the playing card at your link), try our vectorizer: https://www.photopea.com/tuts/vectorize-raster-images/
