### ISSUE TITLE
Blend mode darken - unexpected behaviour

### ISSUE THREAD

**Issue by regy42** [photopea/photopea#300]
Hi, 
blendmode darken works per channel and not like photoshop by luminosity formula (or some similar formula).

0.21 R + 0.72 G + 0.07 B.

**Comment by photopea** [comment]
Hi, what do you mean? Can you show us some example?

I think that the Darken mode works in Photopea the same way as in other editors, and it is correct this way.

**Comment by regy42** [comment]
![image](https://user-images.githubusercontent.com/4135505/32417366-c3c4c508-c258-11e7-9667-89bf8b8b152e.png)

**Comment by regy42** [comment]
Hi, 
sorry it's my mistake, I compared wrong blend modes (darken in photopea with darken color in photoshop). 

Sorry for my mistake :-).
