### ISSUE TITLE
edit text

### ISSUE THREAD

**Issue by gillenergy** [photopea/photopea#3001]
![Menus-old](https://user-images.githubusercontent.com/80476907/110826600-3d7e6980-8263-11eb-8891-fb3d88a8bd9d.jpg)
Cant edit an existing text like before, by clicking on the T icon just a small box get put on the layer and cant do anything with it

**Comment by photopea** [comment]
I think your file is a JPG file. There is no text or layers in a JPG file.

Or is it an editable file?

**Comment by gillenergy** [comment]
that’s right but it opens as psd in photopea isn’t that right?

Sent from my iPhone

On Mar 11, 2021, at 12:47 PM, Photopea ***@***.***> wrote:

﻿

I think your file is a JPG file. There is no text or layers in a JPG file.

Or is it an editable file?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/photopea/photopea/issues/3001#issuecomment-796920104>,
or unsubscribe

**Comment by photopea** [comment]
What do you mean? If you take a JPG photo of a newspaper, you can not open that photo in MS Word and edit the text. And Photopea does not know what is in your photo either.

**Comment by photopea** [comment]
I will close it because of lack of details.
