### ISSUE TITLE
App is not fullscreen on ultra-wide monitor

### ISSUE THREAD

**Issue by michael-motornyi** [photopea/photopea#3002]
![image](https://user-images.githubusercontent.com/33175499/110831226-af29d800-82a2-11eb-909a-3c71e7e54ac4.png)

**Comment by photopea** [comment]
There should be advertisement on the right side of the editor.

Ads are our main source of income. We would not exist without ads. Please, watch ads in Photopea, or buy a Premium account (full-screen Photopea for 10 cents a day).

**Comment by michael-motornyi** [comment]
@photopea  Ah... Ok, thank you! Closing this issue
