### ISSUE TITLE
Existing layer styles duplicate when adding a new one and unable to rename layer styles

### ISSUE THREAD

**Issue by Novel-Worm** [photopea/photopea#3004]
Whenever I add in a new layer style on photopea/ save the one I just created, all my existing layer styles duplicate. This clutters up the collection of layer styles and it's very difficult to work with those. Also, whenever I try to rename any style, an error message pops up, saying "please complete the current action first" no matter when I try this

**Comment by photopea** [comment]
I fixed the problem with renaming styles.

Look into Edit - Local Storage, to see what .ASL files you have there. Delete some of them, or replace them with new ASL files.
