### ISSUE TITLE
Anchor and handle can't be moved properly

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3006]
Hold Shift and move anchor or handle while holding ctrl or using direct select tool, They are moved along red/pink line. They should be moved along green line. 
![Screenshot_20210312_114142_com (1) (1)](https://user-images.githubusercontent.com/79258245/110891395-db8a3680-832c-11eb-8bf6-025780ef8d42.png)
Hold Shift while creating a new anchor by pen tool or holding Alt to move one handle, the handle is moved properly.

**Comment by photopea** [comment]
fixed, thanks for reporting it :)
