### ISSUE TITLE
Not enough RAM .xd file (Need 2226MB)

### ISSUE THREAD

**Issue by bedilbek** [photopea/photopea#3007]
I have the same issue as #692 and #2453. I am running Google Chrome on Ubuntu 18.04. 
I am trying to open a 200MB .xd file on my computer where I have 24GB of RAM, but it still gives an error that it needs 2226MB. I also tried to set v8 options on executing google chrome like the following:
```bash
/usr/bin/google-chrome-stable --args --js-flags="--max-old-space-size=8192"
```

**Comment by photopea** [comment]
I am not very familiar with chrome options :(

Photopea converts each file to PSD (raster file) before opening it. So an empty document with one artboard 100,000 x 100,000 pixels would be 1 MB as an XD file, but it needs 40 GB of RAM as a raster document (4 Bytes per pixel).

How large is your document in pixels? Could you remove half of content and open it again?

**Comment by photopea** [comment]
I have to close it because of a lack of details.
