### ISSUE TITLE
Virtual Keyboard and Mouse

### ISSUE THREAD

**Issue by Kumar808** [photopea/photopea#3008]
Sir, 
    Can you Add "Virtual Keyboard And Mouse" like Ctrl, Alt, Shift etc key which you have already added in Photopea ????
   
  It will be very helpful for using Photopea in Touchpad Device.

**Comment by photopea** [comment]
Hi, what exactly do you want to be added? The keys Ctrl, Alt, Shift are already there.

**Comment by nothingshiru** [comment]
I think he's meaning virtual full keyboard

**Comment by Kumar808** [comment]
Yes I mean Virtual full keyboard to use shortcut key in Touchpad Device

**Comment by Kumar808** [comment]
> Hi, what exactly do you want to be added? The keys Ctrl, Alt, Shift are already there.

 I mean Virtual full keyboard to use shortcut key in Touchpad Device. And Virtual Mouse to Draw any small shape properly as well as click, right click, and double click properly . Click, long press, double click is not working in some options within Photopea.

**Comment by photopea** [comment]
What is a Touchpad Device? I know a touchpad as a part of a laptop.

I think a virtual keyboard or a mouse should be a part of the device software, not a part of a website. How do you use other programs without a virtual keyboard? Maybe there is some software that could help you.

**Comment by Kumar808** [comment]
> What is a Touchpad Device? I know a touchpad as a part of a laptop.
> 
> I think a virtual keyboard or a mouse should be a part of the device software, not a part of a website. How do you use other programs without a virtual keyboard? Maybe there is some software that could help you.

Touchpad means Android Mobile or Tablet.
There is no need of Virtual Keyboard and Mouse within every software. It will be better if Photopea provides this feature.

 These two apps have this feature because it is needed within these apps.
https://play.google.com/store/apps/details?id=com.cloudmosa.puffinFree

https://play.google.com/store/apps/details?id=com.andropenoffice
 You have already Added Virtual Ctrl, Alt, Shift key in Photopea thats why I have asked you to Add full keyboard layout in Same way. It will be very useful for Android user.

**Comment by photopea** [comment]
If you need to type, e.g. in a text layer, or typing the image size, or renaming something, your device should show you a keyboard.

**Comment by Kumar808** [comment]
> If you need to type, e.g. in a text layer, or typing the image size, or renaming something, your device should show you a keyboard.

I know it sir. But we can't use shortcut key using device keyboard. And it is very hard to draw, resize and position Small Shape by Drag and Drop without Virtual or Physical Mouse. 
 Sir, Please implement this feature if it is possible.
And I think you can't understand my problem. 
I am very very sorry if I am disturbing you.

**Comment by photopea** [comment]
I think we should make Photopea easy to use without a keyboard, instead of showing a virtual keyboard.

The current virutal keys at the bottom of a toolbar are just a temporary solution, until we come up with a better way to do it.

**Comment by Kumar808** [comment]
> I think we should make Photopea easy to use without a keyboard, instead of showing a virtual keyboard.
> 
> The current virutal keys at the bottom of a toolbar are just a temporary solution, until we come up with a better way to do it.

Sir, Can you atleast Add a Button anlong with current virtual keys to "Enable and disable Device Keyboard" Anytime by Tapping on that Button sothat we can use some shortcut key   ???
