### ISSUE TITLE
Requests about pen tool

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3009]
1. None fill as default setting in path mode. 
If we want to fill something, we can go to use shape mode. 

2. Path mode as default setting in pen tool. 

3. Delete the anchor selected currently by pressing delete/backspace key one time, delete the whole path by pressing second time. Like Photoshop. 

I found shape mode useless now. 
Because path mode has all the options which shape mode has,  and has the options which shape mode doesn't have. In Photoshop, there are no fill and stroke options in path mode.

**Comment by photopea** [comment]
If you choose the Path or Pixels mode of some tool, there are no Fill or Stroke settings now.

I implemented Delete / Backspace as you suggested.
