### ISSUE TITLE
Magic wand contignuous mode not working on transparent parts

### ISSUE THREAD

**Issue by regy42** [photopea/photopea#301]
Some problem with edges, if i use rubber to make a hole inside painting, its ok. But in case on image below it's not working as expected:
![image](https://user-images.githubusercontent.com/4135505/32417231-922ab4dc-c256-11e7-8759-ee62853f1e2c.png)

**Comment by photopea** [comment]
So you want only the left side to be selected, and not the right side (with contiguous ON) ?

**Comment by regy42** [comment]
Yes, I think that with continious enabled only one side shoud be selected. Simply same behaviour as is with colors:
![image](https://user-images.githubusercontent.com/4135505/32417414-b0239b4a-c259-11e7-83a8-f2d09e332549.png)

**Comment by photopea** [comment]
Fixed. Thank you for reporting it!
