### ISSUE TITLE
Feature Request: Limiting the areas of color that would be affected by Hue/Saturation

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3012]
![screenshot_20210313_052325](https://user-images.githubusercontent.com/79258245/111000306-c2c96180-83bc-11eb-914f-29b8f851280c.jpg)

Have a look at this video from 4:12 to 5:36. 
https://www.youtube.com/watch?v=5iUMLvx8H8Q

**Comment by photopea** [comment]
Hi, I don't think it is that useful. You can already choose between multiple hues (Red, Green, Cyan ...). So just choose
