### ISSUE TITLE
Can't Save

### ISSUE THREAD

**Issue by derekschacker** [photopea/photopea#3015]
Cursor doesn't change to pointer when hover over "File" button. Blue-background text visible. Cannot click file button. 

![Screenshot 2021-03-14 085132](https://user-images.githubusercontent.com/80628975/111069281-abfd3a80-84a2-11eb-9d4e-6a1be86ef1cf.jpg)

**Comment by photopea** [comment]
Hi, does it happen every time you open Photopea and try to save a file? Did it happen more than once?

**Comment by photopea** [comment]
I have to close it because of lack of details.
