### ISSUE TITLE
Saving wont work, is it because i'm using the app

### ISSUE THREAD

**Issue by pollyklarkson** [photopea/photopea#3018]
Hi, I was working on the photopea app(because it works faster on my pc) and i edited my psd file and clicked "save" and did "ctrl + s" many many times. It even lets me exit the app without the "Leave app? Changes that you made may not be saved." window popping up so i thought it saved already.

Then when i opened it it shows that all the work i had done the day before wasn't saved at all :(( it happened yesterday too but i thought it was on me, so i made x100 sure that i saved and saved but when i opened it again nothing was saved :(( didn't have this issue until now so i thought it might be new & wanted to bring it up

is it because i worked on the app or is it really a bug? i hope it gets resolved if it is because i really love using photopea :((
![image](https://user-images.githubusercontent.com/80638338/111075578-a3007d80-8523-11eb-88dd-054523384f83.png)
![image](https://user-images.githubusercontent.com/80638338/111075581-a4ca4100-8523-11eb-9a19-cae47d7c54f4.png)
(also if there's an issue that's the exact same as mine it's because i tried signing in with a temp-mail account, got flagged lmao😗✌)

**Comment by photopea** [comment]
Hi, Photopea is just a website and it can not open anything from your computer automatically.

When you are saving a file, you should see a specific file (like JPG of PSD) in your computer. Next time, when you start Photopea, you should Open a file from your computer (File - Open). It is all described here: https://www.photopea.com/learn/opening-saving

**Comment by pollyklarkson** [comment]
Ohhhhh!! Thank you so much for referring me to this, I totally didn't know! 😅 My bad my bad, thank you so much again, now I know better ^^
