### ISSUE TITLE
How to disable new zoom transition effect?

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#3019]
There's an effect similar to css transitions applied to action of scale change (zoom in / out)
It used to be instant, now it's an animation.
It makes zoom practically unusable, which is particularly problematic if you frequently zoom in/out while working with a PSD.
There doesn't seem to be an option in preferences, and, as I understand, zoom is done within the canvas, so it's not just a css property that can be overriden with browser extension?

**Comment by photopea** [comment]
The zooming effect should never last longer than a third of a second. 

Is your WebGL on? Check it in More - Use WebGL. The WebGL is really important, as Photopea runs 10x slower than it could, if you don't have WebGL. Look into it, maybe installing some drivers or a different browser will help.

**Comment by ewnjtgouierg** [comment]
It DOES run around third of a second or whatever.
It doesn't help. For my the only acceptable time for this effect is 0. Not sure, may be other users are ok with this.

**Comment by photopea** [comment]
@ewnjtgouierg Could you please answer the question about the WebGL?

**Comment by ewnjtgouierg** [comment]
Yes, I do have WebGL ON.
I didn't answer b/c you started with the point that it should be FAST and if not - then I should check the WebGL.
But it IS fast, so I figured the WebGL part was irrelevant to my case.
So, WebGL is ON, and the effect is fast - it is very fast. The problem is that there's a problem even when it is fast, the effect itself is the problem (again, for me - may be it's totally ok for majority of the users, it would surprise me, but well, strange things do happen).

Also, about recommending to turn WebGL ON / OFF: https://github.com/photopea/photopea/issues/40#issuecomment-525696020

**Comment by photopea** [comment]
I changed the zoom animation. Now, it should always take the same time, no matter how fast your computer is.

Could you try it again and see if it is still too slow?

**Comment by ewnjtgouierg** [comment]
it became a little faster, but it is still there
the zoom still happens _after_ you roll the mouse wheel or hit ctrl +/-
normally, when you use things (like scroll or zoom) the action is synchronous with your moves
I mean, there can be a lag when you use outdated hardware, but adding a lag on purpose?... I don't know what to say
is it impossible to make an option to have NO animation/effects whatsoever?

**Comment by ewnjtgouierg** [comment]
p.s. even if you forget that it's a delay, the presence of effect itself is super-distracting. Again, sorry, may be I'm the odd one here. Has this feature been added long ago? (I searched of course, and haven't found any other complaints about it here)

**Comment by photopea** [comment]
I think adding an option to disable this effect would be too complicated. I do not want to have 1000 settings in Photopea, useful only to 0.0001 % of users.

Have you reloaded photopea with Shift+F5 to make sure your browser is not showing you the old cached version?

**Comment by ewnjtgouierg** [comment]
i was talking about an option to disable ALL effects (including possible new effects you will most certainly add in the future ;)

yes, as I said it IS faster now
it IS usable now
it was completely unusable when I started this thread
now it is usable, it still sucks (for me) but it is in line with the rest of the 99% of the software that adds effects everywhere because it can without an option to disable that
so I cannot ask for more considering I'm in a 0.0001% and don't even have a subscription now :)
thanks

**Comment by photopea** [comment]
I still think Photopea is not running at 60 frames per second in your case. Maybe the WebGL is running on the CPU instead of the GPU. You can learn more if you go to about://gpu in your browser (all options should be "hardware accelerated").

e.g. moving layers should be as smooth as in this video: https://youtu.be/evjEjns7npI?t=35

**Comment by ewnjtgouierg** [comment]
Canvas: Hardware accelerated
CheckerImaging: Disabled
Flash: Hardware accelerated
Flash Stage3D: Hardware accelerated
Flash Stage3D Baseline profile: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Native GpuMemoryBuffers: Software only. Hardware acceleration disabled
Rasterization: Software only. Hardware acceleration disabled
Video Decode: Software only, hardware acceleration unavailable
Video Encode: Software only, hardware acceleration unavailable
WebGL: Hardware accelerated
WebGL2: Hardware accelerated

by the way, now it seem to become much slower than it was when I started this thread

**Comment by photopea** [comment]
What version of a browser do you use? Is it updated? Is it not a Beta version?

**Comment by ewnjtgouierg** [comment]
sorry, I do use an old version (Chrome 64)

I checked in FF 84.0.2 and it is same slow there too, I'll check in latest Chromium and update

it was around a third of a second yesterday, as you said, then it became faster when you posted this comment https://github.com/photopea/photopea/issues/3019#issuecomment-799281547 and then when you closed the issue, it became much slower for me
