### ISSUE TITLE
Issues uploading fonts

### ISSUE THREAD

**Issue by rowan010101** [photopea/photopea#302]
The option to upload fonts seems to have disappeared?

**Comment by photopea** [comment]
Hi, how did you upload fonts?  We did not change anything regarding fonts. You can open your fonts using File - Open, or Drag-and-drop.

**Comment by rowan010101** [comment]
When I drag and drop my fonts, they say it loaded, but it doesn't appear in the font options or on the image itself.

**Comment by photopea** [comment]
Look at the end of the list of fonts. Or send us your fonts to support@photopea.com .

**Comment by photopea** [comment]
I have to close it because of lack of details :(
