### ISSUE TITLE
Something is wrong with holding Shift and moving anchor

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3020]
If the handle of the anchor is invisible, I can move the anchor. 
If the handle of the anchor is visible, I can't move the anchor. 

https://user-images.githubusercontent.com/79258245/111133561-a17f9580-85b5-11eb-92a0-d7880da99576.mp4

**Comment by photopea** [comment]
When you hold Shift, you are adding the anchor to selected anchors, and then, you are moving all selected anchors. It works the same in Adobe Photoshop.
