### ISSUE TITLE
Issue and request about pressure controlling brush

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3021]
**Issue**

1. The maximum size of brush could be bigger than setting. 
![Screenshot_20210315_174259](https://user-images.githubusercontent.com/79258245/111137907-4d2ae480-85ba-11eb-8ae9-87be3302fbf7.jpg)

**Request**

1. The options turning on/off can be remembered If logged in. Like the foreground/background color. 
![screenshot_20210315_181717](https://user-images.githubusercontent.com/79258245/111138367-cd514a00-85ba-11eb-83d6-d7994f21a71b.jpg)

2. Add a option setting the minimal size of brush when turning on "pressure control brush".
![X7Q4FNJ3F_98AKEWWSREOB2](https://user-images.githubusercontent.com/79258245/111138648-25884c00-85bb-11eb-8eac-7260c1961cbe.png)
In Photoshop, it is below the option Size Jitter in brush panel.

**Comment by photopea** [comment]
Sorry, it seems like too much work and not that many people need it.

It seems like you will keep posting features of Adobe Photoshop which are missing in Photopea, until Photopea looks identically as Photoshop, am I right? :D

**Comment by nothingshiru** [comment]
What about the first request? Turning on/off can be remembered or turning off as default. 

In tablet the size will be controlled by the area touched. It is very difficult to control a little difference of area by fingers. What would be painted might be like this
![新建项目](https://user-images.githubusercontent.com/79258245/111187434-ef64bf80-85ee-11eb-8ccd-150614f3497a.jpg)
It is gross, so I turn it off almost every time using brush tool. 

Turning off can be remembered or as default will help a lot. If so, I don't need to turn it off manually every time.
