### ISSUE TITLE
The shape path with a italic name is undeletable

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3024]
![screenshot_20210316_062631](https://user-images.githubusercontent.com/79258245/111229321-ab8aae00-8620-11eb-929e-9306c6c9f496.jpg)

**Comment by photopea** [comment]
You should delete it by deleting a shape layer

**Comment by nothingshiru** [comment]
I clicked on the button at bottom but nothing happened. 

https://user-images.githubusercontent.com/79258245/111229811-8f3b4100-8621-11eb-8d34-50795bda5d0d.mp4

**Comment by photopea** [comment]
That is right, this item only symbolizes the path of a shape layer. You can only delete a shape layer in Layers panel.

**Comment by nothingshiru** [comment]
> You should delete it by deleting a shape layer

Thanks. I have just found I should delete it in Layer panel instead of path panel.
