### ISSUE TITLE
Select Pixels Broken in Action

### ISSUE THREAD

**Issue by KojoZero** [photopea/photopea#3026]
Hello, I made an action that rasterizes the current layer, aligns it "Layer 0" and crops it using select pixels (ctrl+click) on "Layer 0". Everything in the action works fine except for the select pixels and the crop ends up being way off.

Here's the action
[Select Pixels Broken.zip](https://github.com/photopea/photopea/files/6146209/Select.Pixels.Broken.zip)

**Comment by photopea** [comment]
I can not run your action in Adobe Photoshop. What should I do to make your action work in Adobe Photoshop?

Did you make your action in Photopea? Photopea is not good at making actions.

**Comment by KojoZero** [comment]
The action I sent earlier was made in Photopea, here is the action made in photoshop. Also, for some reason when I make the action in photoshop it doesn't work at all in photopea. 
[Auto Align Photoshop Ver.zip](https://github.com/photopea/photopea/files/6151213/Auto.Align.Photoshop.Ver.zip)

**Comment by photopea** [comment]
Your action should work well now. Note, that it can not be applied to any document with a layer named "Layer 0". But I am confident, that if it runs in Photoshop, it should run the same in Photopea.
