### ISSUE TITLE
Text highlight option or tool

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3027]
Hi, 
in marketing materials very popular is highlighting the text. That style you can see on social media graphics, YT thumbnails, captions in movies etc.

![highlight-text](https://user-images.githubusercontent.com/38118273/111281965-c4ee2300-863d-11eb-9adc-73a5d7aebcbd.jpg)

In Photoshop users for years wanted that option, but Adobe do nothing with that. It is possible to have something like that in Photopea? I know that is very simple to do for example in CSS, but here (in Photopea editor) it should to work live for every text modification. I know that is hard to store that information in PSD file to keep PSD compatibility with Photoshop. But you are a genius and maybe it is a little chance to have that in character properties panel :)
If it is not possible to do in that way... maybe you can make some new window like Guide Gay to make that once (maybe as a separate shape layer). Functionality that is important for me:

- changing text background color
- changing paddings top bottom right left (as default it can be same size as a text - like highlighting text by selection in browser)
- highlighting from selected part of text
- linking with chain position of new highlight layer with a text layer (if highlighting as a option like in Word or any other editor can't be done in Photopea)

- making underline from text in different color than text (and different weight and style - like in stroke path options) - that isn't so important

**Comment by photopea** [comment]
The PSD format allows setting additional parameters of text, such as Stroke, Text Background, etc. I added an arrow button, which unlocks more options. 
![image](https://user-images.githubusercontent.com/15955558/124279236-8bd3b300-db47-11eb-8587-69356d0918fa.png)

You can play with it here: https://www.photopea.com/#ibz1CAFco .  This PSD is fully supported by Adobe Photoshop (will render the text correctly, if you modify it).

**Comment by MichalSZZ** [comment]
WOW. You are A M A Z I N G.
you added something that was in Photoshop's specification but wasn't in their Application :D
Thank you!

BTW. Now Photopea users can do pranks to Photoshop users making the text with strokes or backgrounds that they can not turn off :)

Some hack:

- If I want to have padding left or right I can add spaces before and after the text
- I see that I can change height of the highlighted background by changing the Leading parameter (the next line background is glued to upper one)
- If I want to have some space between lines I can set the Baseline Shift

**Comment by photopea** [comment]
Thanks :) this is maybe a bit dirty solution,  I am not sure if your hacks will be rendered identically in Adobe Photoshop.

Photoshop uses the same text format as Adobe Illustrator, and probably the same text rendering engine, so I think these text parameters originate from Illustrator.

**Comment by MichalSZZ** [comment]
In Illustartor in Character panel I didn't see any option for background or stroke.
But when I added special functions I found "Character rotation" that I didn't know before.
![obraz](https://user-images.githubusercontent.com/38118273/124286506-529f4100-db4f-11eb-937c-edefb60fffdd.png)

Stroke can be added in Illustrator in appearance panel (but I think it is for the whole layers not as a text special function there). Still I can not easy find highlight option for text in Illustrator. But it is not your problem.
Once again thanx!

**Comment by nothingshiru** [comment]
> The PSD format allows setting additional parameters of text, such as Stroke, Text Background, etc. I added an arrow button, which unlocks more options.
> ![image](https://user-images.githubusercontent.com/15955558/124279236-8bd3b300-db47-11eb-8587-69356d0918fa.png)
> 
> You can play with it here: https://www.photopea.com/#ibz1CAFco . This PSD is fully supported by Adobe Photoshop (will render the text correctly, if you modify it).

I can't see the arrow on the button. Even though I have refreshed the page a few times.
![screenshot_20210703_094623](https://user-images.githubusercontent.com/79258245/124339859-d571db80-dbe3-11eb-831f-4d96002d44fc.jpg)

**Comment by photopea** [comment]
It is a standard character: 🡇  . Try to update your OS, if it does not support it.

**Comment by MichalSZZ** [comment]
On my phone with android there is no icon un Photopea and even in Gmail when  I got notification with your last message ehen you pasted the arrow sign. ;)

**Comment by photopea** [comment]
Ok, I replaced that character with the ellipsis: "..."

**Comment by nothingshiru** [comment]
I wonder if different position of stroke is supported.
![Screenshot_20210704_214250_com android chrome_edit_549423561286995](https://user-images.githubusercontent.com/79258245/124387678-0fd99680-dd12-11eb-9f2d-7822cf6e60ca.jpg)

**Comment by photopea** [comment]
The PSD format has two modes: "Stroke before Fill" and "Stroke After Fill". Now, it is hard-coded to "Stroke After Fill". The stroke is always aligned to the center.
