### ISSUE TITLE
Stylus on touch screen improvement

### ISSUE THREAD

**Issue by wernight** [photopea/photopea#3028]
Could you offer to auto-disable drawing using **touch** when a **stylus is used**. For example on Pixelbook with the pen. Google Keep for example does that but it's not a great drawing tool.

Reason: Without this, it's very easy to touch the screen while holding the stylus which makes Photopea zoom or draw at the wrist touch point instead of only drawing at the stylus.

2 finger touch (but not stylus + touch) should still be allowed to zoom in/out / pan. However just disabling nearly all touch when a stylus is detected would already improve a lot.

**Comment by photopea** [comment]
Can you open a virtual keyboard at the bottom of the Toolbar and enable "No Touch"? Does it help?

**Comment by photopea** [comment]
I think the "No Touch" switch fixes this.
