### ISSUE TITLE
Transparency and interlinear

### ISSUE THREAD

**Issue by kreaterra** [photopea/photopea#3029]
Hello, thank you for the ability to make a psd out of Figma. But I noticed a few mistakes. If in Figma we set the value of interlinear, line spacing in percent - your program does not understand. Only if set initially in points.

And when exporting, it loses the transparency of the fill. Your program understands layer transparency, but does not understand fill transparency.

If you fix it, I will be very grateful to you. But thank you very much all the same.

I will wait for your reply :)

**Comment by photopea** [comment]
Hi, could you send me a .FIG file (as small as possible) to support@photopea.com , where the result is different than it should be? :) thanks!

**Comment by photopea** [comment]
I have to close it because of lack of details :( Or maybe it was fixed over the email.
