### ISSUE TITLE
Features Requests: Button in pen tool/Option in paint bucket tool

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3030]
1. Add a "Create Shape" button next to the "Make Selection" button in pen tool. 
Clicking the button would create a shape layer based on current path. 

2. Add "All Layers" option in paint bucket tool. 
![111569969-bf7c0e80-87de-11eb-881f-08073ab5f515](https://user-images.githubusercontent.com/79258245/116730854-8fe63600-aa1b-11eb-81eb-e4682eb1b3e9.jpg)

Take this image for example. 
![Screenshot_20210501_004447_com](https://user-images.githubusercontent.com/79258245/116730914-a55b6000-aa1b-11eb-93f8-ed683082f1d8.jpg)
With this option, we'll be able to fill the circle with color and the color filled is in the blank layer. 
Like this
![Screenshot_20210501_004447_com (1)](https://user-images.githubusercontent.com/79258245/116731198-f9fedb00-aa1b-11eb-96e5-10b90cd33664.jpg)

**Comment by MichalSZZ** [comment]
Both of your features are good. But they are from different topics. Next time maybe it will be better to add two new issues?

Ad. 1
That functionality will be good for me too (icon in paths window). Now I make it in that way
![obraz](https://user-images.githubusercontent.com/38118273/111591947-699c6c00-87c8-11eb-98cb-a9063d483fbe.png)

**Comment by photopea** [comment]
I have implemented both :) thanks for reporting it!
