### ISSUE TITLE
BUG with mask on smart filter

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3031]
When I use 100% black mask (opacity, hardness and color) on smart filter mask, in Photopea there is a glow effect like this
![obraz](https://user-images.githubusercontent.com/38118273/111583346-8c288800-87bc-11eb-9530-ab01cfc646e4.png)

https://www.photopea.com/#iKXy7hoOk

PS. yesterday I had one more problem (after saving in Photopea to test in Photoshop - in photoshop the file opened normaly but without a mask on filter. Today I can't reproduce it.

**Comment by dentistformyeye** [comment]
> When I use 100% black mask (opacity, hardness and color) on smart filter mask, in Photopea there is a glow effect like this

The apparent glow is part of the blurred flower layer. The black area in the filter mask isn't big enough:
![image](https://user-images.githubusercontent.com/51429646/111642306-5abbb680-87d4-11eb-9345-ddbaad7b1d55.png)

**Comment by MichalSZZ** [comment]
@dentistformyeye  but Photoshop render it proper. 
And if I make bigger mask it look the same
![obraz](https://user-images.githubusercontent.com/38118273/111646072-a173d580-8801-11eb-80fe-a2a519ae8587.png)
The blur go out over the layer size... it is a BUG for me

**Comment by photopea** [comment]
The problem was, that PSD files (with smart filters) were generated incorrectly in Photopea. I fixed it. After you export your document as a PSD, it should look in Photoshop the same as in Photopea.

A thin line of black pixels (in Photopea and Photoshop) is caused by your mask being a bit larger than the original image.
