### ISSUE TITLE
Eyedropper tool - sampling ring for better UX 

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3033]
Now the cursor in Photopea has only the arrow in that tool (even not a cross - it has that cross when you switch to eyedropper with ALT when using brush tool or sampling color in color picker mode).

In Photoshop it's named "sampling ring". It is circle with old color in bottom and a new one (changing live) at the top. It is good but not the best experience for me. It can be as an option on toolbar if user turn on it.

I love that color sampler from developer tool in the Firefox browser

![obraz](https://user-images.githubusercontent.com/38118273/111587812-fa704900-87c2-11eb-8cb9-a89e1cfc1027.png)

in Chrome it looks similar (it think that is even better with cross outside the ring - you see under the cross a normal size of sampling area and pixel zoom below)

https://forum.dobreprogramy.pl/uploads/default/original/3X/d/e/deacc2ad4fab232ec4a69be778cdacaf375db4ac.gif

I can see the magnify and each pixel - and I know what part I am sampling (as you can see it is hard to set proper color in text when it has a initialiasing) 

If it is hard to have that as a cursor addon (i know it can slow down and cursor will be laggy) - that can be showed as a some kind of little window or something like that (with fixed position).

The color showed in hex is a good and important information for me too. But can be ignored by you.

What do you think about it?

**Comment by photopea** [comment]
Do you really think that magnified image preview is a good idea? I think it is extremely hard to move a mouse exactly by one pixel.

When I need to select precisely, I zoom in, so that I see the zoomed pixels right in front of me, and it is easier to choose the right color.

**Comment by MichalSZZ** [comment]
Example from Firefox is not the best option in the world. 
That GIF with animation from Chrome Developer Tool (the idea of it) can be more precisely in designing (if you want to see what are you sampling)
That can be only an option in Eyedropper Tool. Something like  "[ x ] precise sampling " in the top toolbar of that tool. I like to see Magnify and a HEX color when sampling. 
And yes - now I do it as you described (zoom in and out all the time) but I do it only to pick correct pixel. With that option I wouldn't do that anymore.

That how it looks like in Affinity Designer and Affinity Photo
![obraz](https://user-images.githubusercontent.com/38118273/117225642-11223c00-ae13-11eb-8640-35483703afa5.png)
And that ring with old and new color as you can see in Photoshop or Procreate
![obraz](https://user-images.githubusercontent.com/38118273/117225826-8c83ed80-ae13-11eb-8b02-880537908963.png)

**Comment by photopea** [comment]
I think I invented a new workflow. Once you press the mouse, a 12x zoomed version appears. Also, your mouse becomes 12x slower, so you are more precise. What do you think?

The bad thing is, that after you release the mouse, the real cursor has moved quite a lot.

**Comment by MichalSZZ** [comment]
I don't know now what to say... 
For me - now it is very hard to know where I am...
![obraz](https://user-images.githubusercontent.com/38118273/117319107-4a968e00-ae8b-11eb-8340-49c4b70a8b93.png)
circle and point stay in same place and only the content inside is moving... it is strange for me

And there is a BUG when I hold the mouse button and go to the left toolbar :)

What do you think about displaying 12x zoomed version, only after by longer holding the Left Mouse Button? 
When User want to simply click and pick the color as usual - it will be work as always. But when he would like to have zoomed version, he could press mouse button for example 1500 ms. But circle should move like in other programs... And the HEX color info or RGB would be great

Maybe someone else could join into this discussion? @nothingshiru @mustafaGFX @dentistformyeye @hxim @avagp what is your opinion about that feature?

**Comment by avagp** [comment]
Totally agreed with that feature.

I have had a couple of times to click many times the color I want.

Also, as now, when I pick the color I have to watch the 2 squares on the
bottom left, and that disconnects my sight evaluation, because the squares
are surrounded with other colors (black/white depending on your theme)

:D

**Comment by dentistformyeye** [comment]
> circle and point stay in same place and only the content inside is moving... it is strange for me

I think the circle should move with the mouse, too.

>I think I invented a new workflow. Once you press the mouse, a 12x zoomed version appears. Also, your mouse becomes 12x slower, so you are more precise. What do you think?
> The bad thing is, that after you release the mouse, the real cursor has moved quite a lot.

I prefer having the cursor be at normal speed. However, perhaps slowing down the cursor by 2x instead of 12x would still be okay. I think most people with a mouse/trackpad would be fine without the slower cursor, but people using Photopea on a touchscreen device might benefit from it.

**Comment by avagp** [comment]
Yes. The circle should follow the cursor. If not it is pretty much the same
as it is now

The speed should be slowed, but it has to be tested :/

**Comment by photopea** [comment]
I made it work the same as in Adobe Photoshop. You can enable or disable the "Sampling Ring" around the cursor.

There is a second option - "Zoom", which will render a zoomed image in the middle of a sampling ring.
