### ISSUE TITLE
Something is wrong with Background in Liquify

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3035]
When turning on Background, the adjustments in the area at bottom is invisible. And there are some other issues. I don't know how to describe it. 

https://user-images.githubusercontent.com/79258245/111598761-82c60c80-880a-11eb-9529-039e3c5285f4.mp4

**Comment by photopea** [comment]
I can not reproduce it. Can you send me your PSD to support@photopea.com ? Make sure it really happens in the PSD which you send to me.

**Comment by nothingshiru** [comment]
It is not only happening in a specific file. 
I have just found the issue happens when cropped image and there are pixels outside of canvas.

**Comment by photopea** [comment]
Please, send me your file. I need to reproduce it somehow. Photopea works the same for everyone.

**Comment by nothingshiru** [comment]
Here's a file.
[shot 2018.zip](https://github.com/photopea/photopea/files/6163261/shot.2018.zip)

**Comment by photopea** [comment]
it should be fixed now, thanks! :)
