### ISSUE TITLE
Broken Color Layer

### ISSUE THREAD

**Issue by Lo-Tsu** [photopea/photopea#3037]
I am trying to color over the layer, but it wasn't working.

https://user-images.githubusercontent.com/80911799/111664625-f6065900-87df-11eb-8d45-988cb1b4cb83.mp4

**Comment by photopea** [comment]
What if you close Photopea and open it again? Does it never work? Are you clicking or just moving a mouse?

**Comment by photopea** [comment]
I have to close it because of lack of details.
