### ISSUE TITLE
Hide sliders in Filter Gallery like in Liquify

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3041]
On small screen, the sliders in Liquify can be hidden, it is nice! 
But in Filter Gallery  we can't do that at the moment. 
![Screenshot_20210320_234627_com android chrome](https://user-images.githubusercontent.com/79258245/111881511-a4cab500-89eb-11eb-91f8-6dda257135ec.jpg)
![Screenshot_20210320_234625_com android chrome](https://user-images.githubusercontent.com/79258245/111881514-a7c5a580-89eb-11eb-8f6d-46b1d1c8ca0e.jpg)
![Screenshot_20210320_234639_com android chrome](https://user-images.githubusercontent.com/79258245/111881516-a85e3c00-89eb-11eb-840e-934eccf61eaf.jpg)
So there's only a small part of image we can watch when using a device with small screen.

**Comment by photopea** [comment]
I have added the "Menu" button, which hides the menu completely.
