### ISSUE TITLE
Make the sliders in Liquify can be hidden on all devices

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3042]
The sliders can be hidden on my phone but not on my tablet. 
My tablet's screen in portait mode is almost twice as wide as my phone's, but the images it displays are actually only about 10mm wider due to the sliders can't be hidden on my tablet. 
![Screenshot_20210321_022624_com android chrome](https://user-images.githubusercontent.com/79258245/111882237-8a92d600-89ef-11eb-869f-27d74523db80.jpg)
Although my tablet's screen is bigger than my phone's, it is not that big. I still wanna hide the sliders.

**Comment by photopea** [comment]
Now, the sliders in Liquify are "static" only when the width of the screen is 200 px larger than the height.

Also, I removed the window margin in Liquify and Filter Gallery, so there is more space for the image area.
