### ISSUE TITLE
Feature Request: Full screen mode with menu, toolbar etc. 

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3043]
Now Photopea has 3 screen mode. 
1. Normal
2. Normal (Hide menu, toolbar etc.) 
3. Full screen (Hide menu, toolbar etc.) 

When I press Tab key after switched to full screen mode by press F key, what would happen is switching back to normal mode instead of showing menu, toolbar etc. in full screen mode. 

**Why I want a full screen mode with menu, toolbar etc.?**
Because there is a big area occupied by the menu of browser. In a tablet or a phone, it is a quite big area. 
![Screenshot_20210321_031145_com android chrome](https://user-images.githubusercontent.com/79258245/111883672-cf226f80-89f7-11eb-9f6a-a96194d6f7ab.jpg)

I have tried Photopea in lots of browsers on Android. 
There are 2 important points

1. Layers need to be able to be dragged. 
2. When I close Photopea, ask me if I really what to close. 

The browsers that are eligible are only Chrome and Edge. But both of them don't have they own full screen mode. 

If I install Photopea from Chrome and open it, there is no the menu of browser. 
![Screenshot_20210321_040554_com android chrome](https://user-images.githubusercontent.com/79258245/111884179-d8f9a200-89fa-11eb-97fe-313483466b9a.jpg)
But if I return by mistake, Photopea will be closed direct without asking me if I really want to close. And I would lose my unsaved file！So I won't use this. 

And I think there need to be some options in "View" menu for the people who are using tablet or phone without real keyboard to switch screen mode.

**Comment by nothingshiru** [comment]
So what I'm saying is
we need

1. Full screen mode with menu, toolbar etc. 
2. Options for switching screen mode.

**Comment by photopea** [comment]
But you can switch to a fullscreen mode by pressing F11 in a browser, right? There should be a solution for mobile browsers too I think.

**Comment by nothingshiru** [comment]
No, the function keys are not woking in the browsers for Android.

**Comment by photopea** [comment]
On a touchscreen, you can re-arrange the layers by pressing Layer - Arrange - Bring Forward, etc.

I did not know that mobile Chrome lets you close Photopea with unsaved work. I will report it to Google (there is nothing a website can do to prevent being closed now).

I fixed the screen modes: press View > Screen Mode, to select between "Standard" or "Menu bar and canvas". There is a third mode, "Canvas Only", but if people enabed it in View > .... , they would not know how to exit this mode. So now, it can be enabled only with a keyboard by pressing F.

There is a Fullscreen button at the top menu.

**Comment by nothingshiru** [comment]
We can't put layers into folder by those options. It is still important that layer can be dragged. 

Anyway, thanks for all the work you have done.

**Comment by nothingshiru** [comment]
If full screen mode is enabled, pressing return key will exit full screen mode first. Partly full screen mode helps prevent people from closing photopea by mistake.

**Comment by photopea** [comment]
I think many people want to scroll the Layers list with their finger, too. So it is not clear, what should happen, if you tap the layer and move your finger (most people expect scrolling).

Full screen ... are you talking about desktop or mobile? Are you suggesting anything specific?

**Comment by nothingshiru** [comment]
Only if people tap and hold for 1 second without moving, the layer would be dragged. It is same as dragging the icon on home page of a phone. And it is how it works in Chrome and Edge on Android.
I have never heard anyone say that it is confused. 


I was talking about mobile. 
I was thinking that photopea could enable some stuff invisible if there are unsaved file, and tapping return key will close that stuff first then ask people if really want to close. If not, enable that stuff again automatically. If yes, next time tapping return key will close photopea. 
I don't know if this could be done.
