### ISSUE TITLE
request - add a radial symmetry function to the brush tool

### ISSUE THREAD

**Issue by taco3654** [photopea/photopea#3045]
Photoshop has an option where you can turn on an ability to paint symmetrically with 2, 3, 4, 5 etc sides. This would be a helpful function to be built into photopea and would aid in the creation of many different projects.

**Comment by Erelynn** [comment]
I'd like this too. It can be helpful for creating patterns.

**Comment by mustafaGFX** [comment]
I have been thinking about this too, but i was afraid to open an issue about this cuz Ivan works on photopea alone and there's a lot of things that worth working on, if this would be easy to do, it will be graet

**Comment by TheRadicalDreamer** [comment]
![download](https://user-images.githubusercontent.com/11801254/217649717-5b1ea771-a7d7-4d10-8d09-8c7c0eb22e9e.jpg)

**Comment by photopea** [comment]
I have implemented it.


https://github.com/photopea/photopea/assets/15955558/606d2980-ae3b-4ff9-87b7-6b8720fdc5da
