### ISSUE TITLE
Unable to switch tools with the same key binding

### ISSUE THREAD

**Issue by Philoian01** [photopea/photopea#3046]
Hi.
I've been struggling with this issue for a while, and just now tested it again using Edge, Firefox, and Opera. When I go to switch, for example, the Brush Tool to the Pencil Tool by pressing the "B" key again, nothing is changed. The same goes for any other tool with a key binding. I am running up-to-date versions of these browsers. 
Thank you.

**Comment by photopea** [comment]
We changed this feature several months ago.

To switch to other "B tools", like the Pencil Tool, press Shift + B.

There are many people who use only the Brush tool, and they do not like when they are switched to the Pencil tool, just because they pressed B more than once.
