### ISSUE TITLE
Exporting as a png actually exports as a txt

### ISSUE THREAD

**Issue by spipsdew** [photopea/photopea#3049]

**Comment by photopea** [comment]
Hi, your browser extension is renaming the downloaded files. Disable that extension, or use Photopea in Incognito mode (where all extensions are disabled).

**Comment by spipsdew** [comment]
I tried that and it still didn't work. I think it was because I didn't name
the project. When I gave it a name it worked as intended.

Thank you anyway! I love photopea.
