### ISSUE TITLE
High DPI related glitches

### ISSUE THREAD

**Issue by PiranhaGreg** [photopea/photopea#305]
Ahoj, mám notebook 15.6" s 4K displayem a všiml jsem si pár drobností, které se v programu vykreslují špatně (a nejspíš souvisí s vysokým DPI).

![chrome_2017-11-05_22-08-49](https://user-images.githubusercontent.com/3635737/32419344-b3559e48-c278-11e7-93fc-8d63e078d401.png)

- [ ] Popisky nad skupinou vrstev (zde _Phone 7_ a _Desktop HD_) se neškálují.
- [ ] Tvar kurzoru jakéhokoliv štětce při kreslení není jemný (z přiloženého snímku je jasný, jak to myslím). Navíc je u každého štětce vlevo nahoře malý bílý čtverec (je vidět oproti tomu velkému červenému fleku). Tvar kurzoru je navíc cca dvojnásobně velký, než pak reálně kreslím na plátno.
- [ ] Při volbě velkého štětce není část čísla indikujícího jeho velikost vidět.

Jinak ale skvělá práce. Takhle pokročilý grafický webový editor jsem ještě neviděl. Když zrovna nebudu u svého PC, je odteď Photopea jasná volba. Sem tam si i hraju s WebGL a dalšími webovými API, takže tuším, jakou spoustu práce to muselo dát...

**Comment by photopea** [comment]
Ahoj, všechno bylo opraveno. Kurzory byly vyřešeny jen pro Google Chrome - pro ostatní prohlížeče to dnes nelze :( tak snad někdy v budoucnu.

Díky!
