### ISSUE TITLE
Apple font emoji fonts' glyphs do not show up

### ISSUE THREAD

**Issue by parmonov98** [photopea/photopea#3050]
![image](https://user-images.githubusercontent.com/24564577/112576228-b6f58a80-8e13-11eb-8eac-3e78ae75870f.png)
in photopea

![image](https://user-images.githubusercontent.com/24564577/112576460-24a1b680-8e14-11eb-9adc-9508020716bd.png)

in photoshop 

I loaded the font in ttf format.

**Comment by photopea** [comment]
Hi, I fixed the problem.

It still might take 5 - 10 seconds to render all glyphs in your font. Decoding PNGs is quite slow.

**Comment by parmonov98** [comment]
> Hi, I fixed the problem.
> 
> It still might take 5 - 10 seconds to render all glyphs in your font. Decoding PNGs is quite slow.

I uninstalled and installed, refreshed with cache clear, but it didn't work. 

system info:

Google Chrome | 89.0.4389.90 (Official Build) (64-bit)
-- | --
Revision | 62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
OS | Linux
JavaScript | V8 8.9.255.20
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
Command Line | /usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end --origin-trial-disabled-features=SecurePaymentConfirmation
Executable Path | /opt/google/chrome/google-chrome
Profile Path | /home/dev/.config/google-chrome/Profile 1


OS: Kubuntu

**Comment by parmonov98** [comment]
> > Hi, I fixed the problem.
> > It still might take 5 - 10 seconds to render all glyphs in your font. Decoding PNGs is quite slow.
> 
> I uninstalled and installed, refreshed with cache clear, but it didn't work.
> 
> system info:
> 
> Google Chrome	89.0.4389.90 (Official Build) (64-bit)
> Revision	62eb262cdaae9ef819aadd778193781455ec7a49-refs/branch-heads/4389@{#1534}
> OS	Linux
> JavaScript	V8 8.9.255.20
> User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
> Command Line	/usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end --origin-trial-disabled-features=SecurePaymentConfirmation
> Executable Path	/opt/google/chrome/google-chrome
> Profile Path	/home/dev/.config/google-chrome/Profile 1
> OS: Kubuntu

but it worked with opera.  I think something is wrong with chrome.

**Comment by parmonov98** [comment]
on opera the icons are loaded without colors. balack&white. 

and not full. 

![image](https://user-images.githubusercontent.com/24564577/112715848-aa9d2a80-8f04-11eb-8573-a869e830fe11.png)

**Comment by photopea** [comment]
For me, everything works well in Chrome.

The emojis in your screenshot are from Liberation Sans font. You should switch to another font to see glyphs in another font.

**Comment by parmonov98** [comment]
> Hi, I fixed the problem.
> 
> It still might take 5 - 10 seconds to render all glyphs in your font. Decoding PNGs is quite slow.

![image](https://user-images.githubusercontent.com/24564577/112716050-da98fd80-8f05-11eb-9089-9436ec238454.png)

![image](https://user-images.githubusercontent.com/24564577/112716084-074d1500-8f06-11eb-8b3c-d391f91607f9.png)
I waited a minute. but anyway it didn't work.

**Comment by photopea** [comment]
Can you try steps mentioned here: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
If nothing helps, could you send me that font to support@photopea.com , so that I try it myself?

**Comment by photopea** [comment]
Your font was different than mine. I fixed the bug, your font should work now, too.

**Comment by parmonov98** [comment]
You're awesome man!
