### ISSUE TITLE
Exporting Vector file format does not export text Gradient Overlay

### ISSUE THREAD

**Issue by JSmartDigital** [photopea/photopea#3051]
Hi, 

I'm not sure if this is an issue or something wrong with what I am doing. I try to export a logo with text in a vector format like svg or pdf and the gradient overlay I have on the text disappears, and the text turns black. Ideally I want to export the text as vector paths as well as the rest of the image.

https://www.loom.com/share/7d38d12566ae4a6baef7e58dcd1c9a09

**Comment by JSmartDigital** [comment]
Update: I was able to convert the text to a Smart Object and this worked for exporting the text with the gradient Overlay.

**Comment by MichalSZZ** [comment]
Try to change text to vector before exporting (right click on the layer name and then "convert to shape".
Smart object is not a vector object in SVG even if it have a vector inside.

**Comment by JSmartDigital** [comment]
> Try to change text to vector before exporting (right click on the layer name and then "convert to shape".
> Smart object is not a vector object in SVG even if it have a vector inside.

Thank you!

**Comment by photopea** [comment]
I fixed the problem. When you export a text layer with a Gradient Overlay into SVG, the gradient is used correctly.
