### ISSUE TITLE
Gives Error Message When Trying to Open File

### ISSUE THREAD

**Issue by AirGEL** [photopea/photopea#3052]
It's giving me an "Error, please send your file to support@photopea.com and we will try to solve it" message when I try to open a file that I've successfully open hundreds of times before.

**Comment by photopea** [comment]
Have you tried to open your file more than once?

**Comment by AirGEL** [comment]
yes, like 3 times
It finally opened after closing my browser and reopening it

**Comment by photopea** [comment]
Is it a large file? Is your web browser older than five years?

**Comment by AirGEL** [comment]
no the file's only like 4 KB, my browser is probably 5 years old though

**Comment by photopea** [comment]
I recommend you to update your web browser. Browsers are usually free, you do not need to pay for them.
