### ISSUE TITLE
Animations don't merge correctly

### ISSUE THREAD

**Issue by JoBr1998** [photopea/photopea#3053]
When I try to emerge two animations, they turn out cropped and jumpy instead of being merged correctly. I've tried to use different blending settings, but nothing fixes the problem. Here's a picture of what it looks like after I crick Layer --> Animation --> Merge:

![Screenshot 2021-03-26 at 23 11 39](https://user-images.githubusercontent.com/81444311/112697814-acc1a380-8e88-11eb-9383-21539b629be9.png)

**Comment by photopea** [comment]
Can you show us how your two original animations look like and what is the result?

**Comment by JoBr1998** [comment]
Sure!

![Screenshot 2021-03-27 at 00 17 13](https://user-images.githubusercontent.com/81444311/112702242-1b0b6380-8e93-11eb-8190-f4a51dc32596.png)
![Screenshot 2021-03-27 at 00 21 28](https://user-images.githubusercontent.com/81444311/112702249-21014480-8e93-11eb-9472-30b1490ccae7.png)

End result:

![Screenshot 2021-03-26 at 23 11 39](https://user-images.githubusercontent.com/81444311/112702261-2e1e3380-8e93-11eb-90bc-bb1e35dc1a6e.png)

They're pretty big in proportions (540px x 420 px) but only about 1.5MB in size each. It's strange because I have sucessfully merged animations of that size before.

**Comment by photopea** [comment]
I see two static PNG images. They are not animated.

**Comment by JoBr1998** [comment]
That's because they're screenshots. I didn't know if you could upload gifs. My bad. But here they are then:

![2](https://user-images.githubusercontent.com/81444311/112702869-3d9e7c00-8e95-11eb-9e17-5fe39a7133e4.gif)
![ex (4)-2](https://user-images.githubusercontent.com/81444311/112702880-44c58a00-8e95-11eb-90e4-79a1ed9febfc.gif)

End result:

![2-2](https://user-images.githubusercontent.com/81444311/112702966-9110ca00-8e95-11eb-9fb4-0380e1dbacc5.gif)

**Comment by photopea** [comment]
What exactly would you like to get after "merging animations"? People usually merge e.g. an animation of a falling snow with an animation of a dancing penguin. One animation will run on top of another one.

But in your case, one animation would cover another one, so only one can be visible.

**Comment by dentistformyeye** [comment]
I think the issue that @JoBr1998 is addressing is the automatic trimming. There should be a way to turn automatic trimming off.

**Comment by photopea** [comment]
Oh, I tried to merge these two specific gifs and I see the error now. I am very sorry, it is fixed now.
