### ISSUE TITLE
Sorting Glyphs by font  as in photoshop

### ISSUE THREAD

**Issue by parmonov98** [photopea/photopea#3055]

**Comment by photopea** [comment]
What exactly does it mean?

**Comment by parmonov98** [comment]
> What exactly does it mean?

for example, I switched to font1, but I wanna use font2's glyphs. then I have to change font again. but I wanna change only in glyphs panel.

**Comment by photopea** [comment]
I see, I added the font selector into the Glyphs window. BTW. this font selector changes the global font, just like in Adobe Photoshop.
