### ISSUE TITLE
new project tamplates

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#3057]
I always set the size 2000x2000 pixel when I create any new project, every time I open photopea I have to change the size from 1280x720 to  2000x2000. so I thought it will be a great idea to save the sizes you always set as a template. my idea is : 

![Screenshot (92)](https://user-images.githubusercontent.com/70863817/112755881-f45c4280-8fe2-11eb-8121-07b79410be12.png)

**Comment by photopea** [comment]
Hi, I think not that many people need this, and it would make the interface quite confusing. So I would rather not do that.

BTW. after you close this window, and open it again, there should be values from the previous time.
