### ISSUE TITLE
Smart object after cropping layer with mask - wrong dimensions of layer

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3059]
1. Make a small selection on layer with image
2. Make a mask from that selection
3. Crop image using Trim function
4. Make a smart object from that layer
5. Use Ctrl+T to check the size of layer

Size of that layer (smart object) should to be like a image size after cropping. 
After editing a smart object itself, size should to be like a mask (image size after cropping) - not like a original layer without mask.

**Comment by photopea** [comment]
The smart object (if you double-click it) has the size of the original layer, not the mask. I think that is correct.

**Comment by MichalSZZ** [comment]
Ok but after step 4 when you duplicate that layer into another project it should to have size as a project size after cropping. That how it work in Photoshop. If you cant reproduce that I will try to make a wideo.

**Comment by photopea** [comment]
Ok, I have fixed it :)

**Comment by MichalSZZ** [comment]
Thank you!
