### ISSUE TITLE
Language detection

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#306]
1) I think that detection language from browser (headers) could be great for new users. Implementation is simple.
2) Translate "welcome banner" to Czech please :)

**Comment by photopea** [comment]
Hi, what Welcome banner do you mean? it is already translated.

**Comment by landsman** [comment]
I can see english welcome message with czech UI:

![snimek obrazovky 2017-11-06 v 13 04 12](https://user-images.githubusercontent.com/3184228/32440340-00b1f040-c2f3-11e7-9f6e-b8ff3cf87ef5.png)

**Comment by photopea** [comment]
Hi,

1) Now, the "intro" contains the list of appropriate languages, you can choose your one by clicking it.
2) The text at the top is too long and I think there are more important things to translate. We don't have many Czech users, so I don't think it would be so helpful.

**Comment by landsman** [comment]
2. I can translate it, if you will add this fields to https://www.photopea.com/translate/ ;-)

**Comment by photopea** [comment]
I think we should only translate phrases, that will never change. I am afraid, that this text will change many times in the future, but nobody will translate it again.

**Comment by landsman** [comment]
Just let allow translate and we'll see. Full-translated app for new visitors could be more friendly.
What about language detection idea?

**Comment by photopea** [comment]
This Intro text requires formatting (bold text, font size etc.). Current translations don't allow formatting. Lets wait until there are many visitors from some country, then we will translate it.

**Comment by landsman** [comment]
It can be in markdown and you can use some markdown to html library :-)
