### ISSUE TITLE
Feature Request: Entirely Online Workflow

### ISSUE THREAD

**Issue by Erelynn** [photopea/photopea#3064]
Hi,

I really love Photopea and I use it all of the time because it's incredibly useful. I especially like that I can access this great tool without having to download anything on my computer.

Photopea has most of what I need except for one feature. The feature that I'm talking about is the ability to save my work online without having to save anything into my computer. I would like to be able to import images into Photopea from my email or Google Drive. I would also like to save my work directly into my email or Google Drive, without having to save it on my computer first. Having this option will allow us to keep our workflow entirely online, which can be very useful. Sometimes I'm sharing a computer with others and I prefer not to save anything on it. I'd much rather save my work online, using private methods such as email and Google Drive. Since Photopea is an online program, some of the users are likely to want to work with their files entirely online. This type of feature is also great because we would be able to access our files from any computer. We can work freely even if we're not using a personal computer, since we won't have to download anything on it.

I suggested uploading from and saving files into services such as Google Drive because it's easy and free to use. But I also don't mind any alternatives that are free, private and will allow me to work with my files online.

I really hope a feature like this gets added because an entirely online workflow would be the most beneficial to me. It would allow me to work with Photopea no matter what computer I'm using, and access my work from anywhere. This feature would make Photopea perfect in my eyes.

Thank you very much for creating this wonderful program and making it available to everyone! You guys are really great! :)

**Comment by photopea** [comment]
You can integrate Photopea with a Google Drive, do you know about it? https://www.youtube.com/watch?v=p7kjmwhlNrA

**Comment by mustafaGFX** [comment]
what if...
![Screenshot (94) (1)](https://user-images.githubusercontent.com/70863817/112841605-fab0f400-90a0-11eb-8250-6543e2585aad.png)

would it be good to be able to share the image directly from photopea to any platform ....?
I have been thinking about this Feature for a long time

**Comment by photopea** [comment]
I think @Erelynn wants to save the work somewhere, and then, open it from there in Photopea. You can not save a PSD to Instagram, and then, open it from Instagram in Photopea.

**Comment by mustafaGFX** [comment]
@photopea 
yeah I understand, but what do you think about my idea, should I open it in different issue

**Comment by photopea** [comment]
I don't know if these social networks allow other websites to make posts like that.

**Comment by mustafaGFX** [comment]
> I don't know if these social networks allow other websites to make posts like that.

they do
all apps I use have this feature, even the mobile apps,
the first step is to render the image, after rendering it will be shared as a normal image

**Comment by photopea** [comment]
I know about mobile apps. But do you know a website, which lets you create Instagram posts with one click?

**Comment by mustafaGFX** [comment]
sure

open any template on canva

![Screenshot (97)](https://user-images.githubusercontent.com/70863817/112876485-dca9ba80-90c5-11eb-94c4-9e9592d549aa.png)
.
.
.
Share it to any platform, let's say Facebook

![Screenshot (97) (1)](https://user-images.githubusercontent.com/70863817/112876561-f3501180-90c5-11eb-857d-d07ab7396155.png)
.
.
.
give the site the permissions ( for one time )

![Screenshot (97) (2)](https://user-images.githubusercontent.com/70863817/112876668-111d7680-90c6-11eb-9550-720a261d9854.png)

![Screenshot (97) (3)](https://user-images.githubusercontent.com/70863817/112876774-33af8f80-90c6-11eb-9b5e-1e964ae2ab28.png)
.
.
.
the permissions will be automatically turned on
![Screenshot (97) (4)](https://user-images.githubusercontent.com/70863817/112876805-3dd18e00-90c6-11eb-9f00-9737b289ad07.png)
.
.
.
press ok
![Screenshot (97) (5)](https://user-images.githubusercontent.com/70863817/112876985-75403a80-90c6-11eb-8e30-81e679e3ef98.png)


now you can share the image any time by one click

**Comment by mustafaGFX** [comment]
canva.com

**Comment by mustafaGFX** [comment]
also, canva let me use [Grammarly](https://app.grammarly.com/docs/new) when typing, it helps me a lot, can photopea do the same

![Screenshot (104) (2) (3)](https://user-images.githubusercontent.com/70863817/112879189-2051f380-90c9-11eb-9cac-c89acdcad77f.png)

**Comment by photopea** [comment]
In Canva, that means connecting their Facebook app to your account. And in case of Twitter, you have to give Canva full permissions to your account (they can post or delete tweets, follow and unfollow people, etc).

You are the only person who asked for this, so I think it is not that important. People are ok with saving files to a computer in between.

Grammarly means sending everything people type to a Grammarly server. That can be considered bad for privacy.

**Comment by mustafaGFX** [comment]
got it

**Comment by Erelynn** [comment]
Thank you! I understand that this feature might be challenging to implement properly. Thank you for pointing out the privacy issues, as I think that's important to take into consideration. I personally don't care about posting anything directly to social media, but I wanted to use private methods (such as email or Google Drive) to store & access my files without saving them on my computer. Even if this feature is not possible, I still hope there will be an alternative way to save files without having to save them directly to my computer. It would be a useful feature to me because I'd be able to work on creative projects even when I'm not at home.

**Comment by photopea** [comment]
@Erelynn we are planning to provide our own cloud storage in the future. Meanwhile, you can connect Photopea with your Google Drive or Dropbox. Have you tried it? Open www.Photopea.com , it is on the left side.

**Comment by photopea** [comment]
We have our own cloud storage now, we call it Peadrive: https://twitter.com/photopeacom/status/1575196954971279362
