### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by thomas-monaghan** [photopea/photopea#3066]
Photopea is not responding and/or going extremely slow.

**Comment by photopea** [comment]
have you tried to close it and open it again? Is your document more than 1 billion pixels?

**Comment by thomas-monaghan** [comment]
It seems that the issue is when I select the B3 format to work in I get a lot of lag.  I am using a different size now and the issue is gone.

**Comment by thomas-monaghan** [comment]
I mean under Print - B3 - 353 x 500

**Comment by photopea** [comment]
Check if your WebGL is on (More - Use WebGL) and if your browser uses GPU acceleration (go to about://gpu). It is often disabled on compters that are older than 10 years. Is your browser updated? It could run better in some other browser.

**Comment by photopea** [comment]
I have to close it because of lack of details.
