### ISSUE TITLE
Dragging sliders/texts with finger is not working properly

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3067]
Dragging these is not working properly

1. Texts of Opacity/Fill of layer
2. Sliders of Blend If in Layer Style
3. Texts of options in Live Shape in properties panel

It seems like there's only 0.1 seconds that the values are being controlled by moving finger to right/left after I tapped the sliders or texts. 

Dragging the texts of options in pen tool to change the value is working properly. 
For example, I drag the "Flow" in pen tool, the value of flow can be changed all the time if my finger is keeping on screen after tapped the "Flow".

**Comment by photopea** [comment]
I am very sorry, it should all be fixed now. Labels of numerical inputs should be draggable with a finger, as well as Blend If sliders.
