### ISSUE TITLE
Quick Select Tool is selecting the parts of image outside of canvas

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3069]
![screenshot_20210330_085902](https://user-images.githubusercontent.com/79258245/112917948-524d6f00-9136-11eb-8da7-a4fb2804a2f6.jpg)

**Comment by photopea** [comment]
I think that is useful. If you copy-paste it into a new layer, you can move the layer in the future and reveal hidden area, without selecting it again.
