### ISSUE TITLE
drop-down menu vs. welcome banner

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#307]
Check this:

![snimek obrazovky 2017-11-06 v 13 03 35](https://user-images.githubusercontent.com/3184228/32440313-e80b0ae0-c2f2-11e7-9b5e-1e6e555a3042.png)

On https://www.photopea.com/translate/ missing these fields for translate...

**Comment by photopea** [comment]
Ok, the position of menus was fixed.

**Comment by landsman** [comment]
Good job! :-)
