### ISSUE TITLE
Duplicate to artboard

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3070]
Something very weird happens when i try to duplicate layers to an artboard.

Layers get blank, and i cannot select a particular artboard

here is a video:
[Screen recording 2021-03-29 23.38.16.zip](https://github.com/photopea/photopea/files/6225806/Screen.recording.2021-03-29.23.38.16.zip)

**Comment by avagp** [comment]
additionally, if i have the artboard tool preselected when i create a new project with artboards, the (+) icons does not display. You need to change the toll, and then back to artboard in order to display them.

**Comment by avagp** [comment]
I will add more problems:
[Screen recording 2021-03-30 01.17.57.zip](https://github.com/photopea/photopea/files/6226151/Screen.recording.2021-03-30.01.17.57.zip)

Also, on the new artboards, i cannot get horizontal/vertical center guides (the red ones) when moving layers

**Comment by avagp** [comment]
glitches duplicating layers on artboards:
[Uploading Screen recording 2021-03-30 01.54.54.zip…]()

**Comment by photopea** [comment]
I fixed the problem with duplicating into the second artboard, even when the first artboard is chosen.

Also, I fixed the problem with the artboard tool not showing the pluses, even when the tool is enabled.

I can not recreate other problems. Could you share PSD files and describe what should I do?

**Comment by photopea** [comment]
BTW. creating a new artboard does not duplicate guides from a previous artboard. You need to create guides from scratch. Guides always belong to a currently selected artboard, and they will disappear if you select another artboard. It works the same in Adobe Photoshop.

**Comment by avagp** [comment]
So here i am doing it again, i am attaching the PSD, but as i can barely tell, is not about my files.
[Screen recording 2021-03-30 15.08.43.zip](https://github.com/photopea/photopea/files/6231210/Screen.recording.2021-03-30.15.08.43.zip)
[Uploading Back Luca.zip…]()

**Comment by avagp** [comment]
So here i am doing it again, i am attaching the PSD, but as i can barely tell, is not about my files.
[Screen recording 2021-03-30 15.08.43.zip](https://github.com/photopea/photopea/files/6231210/Screen.recording.2021-03-30.15.08.43.zip)
[Back Luca.zip](https://github.com/photopea/photopea/files/6231213/Back.Luca.zip)

**Comment by avagp** [comment]
I have to add this here, but if you want i will add it in a separate thread:
D) When creating a project without artboards, and then i realise i need artboards, i select the artboard tool, but:
first: the canvas does not convert to an artboard, so i have to retrace the canvas border with the tool and add all the layers inside it.
second: i don't get the pluses to duplicate the same canvas size, so again i have to "duplicate" manually the canvas.

**Comment by avagp** [comment]
Yes, now it is working the pluses.

**Comment by photopea** [comment]
I fixed the issue, when some layers were not moved when duplicating to a specific artboard.

Regarding the "impossible artboard size": Photopea is a raster editor and the size of an artboard should be in whole pixels. If you have a DPI of 72, and you want a document of 1.3 inches x 1.3 inches, that is 93.6 x 93.6 pixels. We can not make half-pixels, so we have to round it to 94 pixels = 1.3056 inches.

It works the same in Adobe Photoshop.

**Comment by avagp** [comment]
Have you fixed the (C) and (D) ?

**Comment by photopea** [comment]
Yes, layers are moved to the correct spot, and pluses should always be present.
