### ISSUE TITLE
The mask on fill layer(color, gradient, pattern) is not working correctly

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3072]
It works correctly before. Now no matter what the mask looks like, it is same as a totally black mask. Fill layer is being hidden. 
![screenshot_20210330_141851](https://user-images.githubusercontent.com/79258245/112942993-7d9a8300-9163-11eb-8566-118ee73aae23.jpg)

**Comment by photopea** [comment]
I am sorry, this error was introduced yesterday, when fixing another issue.

I fixed it again now. Hope I did not break anything else.
