### ISSUE TITLE
Enable virtual Alt key and tap mask with finger for showing mask only is not working

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3073]
Enable virtual Shift key to show/hide mask is working, but enable virtual Alt key to check mask is not working.

**Comment by dentistformyeye** [comment]
Enabling the virtual Ctrl key and clicking a layer/mask icon in the Layers panel to select non-transparent pixels also doesn't work.

**Comment by photopea** [comment]
Both cases support the virtual keyboard now :)
