### ISSUE TITLE
the image disappears after I change the color OR try to convert it to smart object

### ISSUE THREAD

**Issue by faith1983** [photopea/photopea#3074]
I've been using photopea for a while, but for some reason I can't design anymore, I make a picture and if I change the color, it disappears, the app becomes black, sometimes I can add elements to my design, and the app turns black after I try to change those added elements, and if I am lucky enough, I can make it and finish all the design, and the whole thing disappears once  I try to convert it to a smart object, it's really frustrating knowing that I have done this process before and managed to create a lots of designs, but it has been 2 days now that I am uncapable to do anything, please please help

**Comment by photopea** [comment]
Hi, maybe your device does not have enough RAM memory.

When it happens, can you press Window - More - Memory, and tell us how much memory is used?

**Comment by faith1983** [comment]
Thank you for your quick reply, here is the information that I found:
Processor Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz   1.50 GHz
Installed RAM 8.00 GB (7.76 GB usable)
System type 64-bit operating system, x64-based processor
Pen and touch No pen or touch input is available for this display

**Comment by photopea** [comment]
I need a description of what should I do to make the problem happen on my computer. 

If I can not make it happen on my computer, I can not fix anything :(

**Comment by faith1983** [comment]
Is is possible that the document I am working with is bog, see I open an
esp image from my laptop size 20x20 inch 72 dpi , I resize it to 33 x 46 in
300 dpi or 29 x 41 in 300 dpi, sometimes it crushes at this step, sometimes
I manage to change the designs and crushes when I add extra elements like
circles and abstract shapes , and sometimes it crushes when all the things
are added and I decide to convert the whole elements and layers into a
smart object before I save it on my laptop

**Comment by photopea** [comment]
33x46 inches at 300 dpi is quite a lot.  It is 9900 x 13800 pixels, or 136 million pixels.

Why don't you use 72 DPI? If you use only vector-ish content (circles, squares, text ...) you can increase the DPI later without a loss of quality.

**Comment by faith1983** [comment]
Thank you for your support ,really appreciate it, you know even if you did
not give me a solution, your interaction is priceless , thank you so soooo
much

**Comment by photopea** [comment]
Just use a smaller DPI. Photopea or Photoshop will always be laggy with 136 million pixels. Also, your memory will run out faster.
