### ISSUE TITLE
Auto-reseted

### ISSUE THREAD

**Issue by vqsvq** [photopea/photopea#3075]
I wanted to use photopea, when I opened it it started to be kinda laggy.
After that, I opened a new proyect and started editing normally. I wanted to use text tool but it seemed like I didn't have any font, none of the ones that I loaded, that also happened with brushes, styles, patterns, gradients, actions etc..
I really don't know what happened because I never reseted it and now I can't use it because I had many things :(

**Comment by photopea** [comment]
I need a description of what should I do to make the problem happen on my computer.

If I can not make it happen on my computer, I can not fix anything :(

**Comment by photopea** [comment]
Do you have any browser extensions? Maybe your browser extensions cause the problem. Do you think you know what your extensions do?

**Comment by vqsvq** [comment]
> Do you have any browser extensions? Maybe your browser extensions cause the problem. Do you think you know what your extensions do?

I have one, i will desactivate it and see if it works, thank you!

**Comment by photopea** [comment]
I will close it because of lack of details.
