### ISSUE TITLE
Can't move artboards

### ISSUE THREAD

**Issue by progproc** [photopea/photopea#3076]
Once I create an artboard, I can't easily move it. Dragging a move tool does nothing. Draging an artboard tool creates a new artboard.

Please enable moving the whole artboard, e.g. by clicking and dragging the name of the artboard.

Thank you.

**Comment by photopea** [comment]
Hi, when I create an artboard, I can drag it with the Move tool.

Could you describe steps, what should I do to see the problem happen?

**Comment by photopea** [comment]
Oh, I see, I think you are using Firefox. If you use Firefox, you should never press Alt on the keyboard. You probably pressed Alt, and now, things are breaking.

I have been asking Mozilla to fix it for over two years: https://bugzilla.mozilla.org/show_bug.cgi?id=1568130 . You can join me in begging Mozilla to fix it, or you can switch to a better browser.
