### ISSUE TITLE
Filter Gallery error on empty selection

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#3077]
When I select empty selection and after that I try to do
Filter - Filter Gallery - Cutout or Conté Crayon or Underpainting
After I click OK it does nothing and shows error see screenshot
![image](https://user-images.githubusercontent.com/6370548/112986480-d701b280-9161-11eb-9fc3-19ccde6c3e04.png)

**Comment by photopea** [comment]
I fixed it, thanks for reporting! :)
