### ISSUE TITLE
More problem with undo after creating artboard

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#3078]
1. Open pea.psd
2. Create artboard with Artboard Tool
3. Resize artboard with control squares on left and right so the width is smaller like this
![image](https://user-images.githubusercontent.com/6370548/112988481-2cd75a00-9164-11eb-90bf-6bd506bd6539.png)
4. Click on "Open" in hisotry window to undo everything
5. Original pea.psd is not restored and image is broken (layers moved) as seen in this screenshot
![image](https://user-images.githubusercontent.com/6370548/112988685-660fca00-9164-11eb-895c-bd6a42c9ab4e.png)

**Comment by photopea** [comment]
It is fixed now, thanks! :)
