### ISSUE TITLE
Can glyphs and other panels be resizible ? 

### ISSUE THREAD

**Issue by parmonov98** [photopea/photopea#3079]
![image](https://user-images.githubusercontent.com/24564577/112992454-9dd93a80-9181-11eb-8c71-1e5ce8ecd581.png)

**Comment by photopea** [comment]
Hi, I made Glyphs and other panels resizable. There is a black triangle at the bottom left corner, which you can drag.

**Comment by parmonov98** [comment]
you're my duuuuuuuude! thanks a lot. if this goes well, apparently I'll be your subed user or Patreon :)

**Comment by parmonov98** [comment]
> you're my duuuuuuuude! thanks a lot. apparently I'll be your subed user or Patreon soon :)

I think there's a problem, resizing  is not smooth, I guess. but it is better than nothing.

**Comment by photopea** [comment]
The smoothness depends on how many glyphs are currently displayed (and need to be redrawn). It takes about 0.2 seconds to redraw 6000 glyphs in DejaVu Sans (45 x 45 pixel image for each glyph, so 12 million pixels in total).
