### ISSUE TITLE
minify app

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#308]
Hi,

I was check file: [ext.js](https://www.photopea.com/code/external/ext.js), [FNTS.js](https://www.photopea.com/code/FNTS.js), [LNG2.js](https://www.photopea.com/code/LNG2.js) and I see not minified source code. Do you think about full-minify? It could have smaller size.

I can create gulp file, tasks for automated deployment with minify by one command, would you be interested?

Second question: How do you solve browser-caching these files if you will release new build of app? I think that some version parameter (timestamp of last change) should be great solution.

**Comment by photopea** [comment]
Hi, if we minify ext.js, FNTS.js  and LNG2.js, they will be about 40% smaller.

But our web server delivers JS files with gzip compression, and after GZIP, the difference is only about 5 %, so it is not worth it.

All JS files of Photopea have caching time set to 60 seconds, so they are reloaded every time you visit Photopea.
