### ISSUE TITLE
Percentage Rulers should go to 100% on X and Y axis

### ISSUE THREAD

**Issue by smoli** [photopea/photopea#3080]
**Steps to reproduce:** 

* Load an image that has an aspect ratio != 1, e.g. https://www.photopea.com/?fbclid=IwAR15lhJMIlAy5PmlRBUbKDY_7qCOoD96TLKqTGYvHRW6sRsoGXvEVtVmH0U#iXRJPSqbl
* Enable Rulers
* Set Rulers to percent
* Ruler on X-axis spans 0% to 100%
* Ruler on Y-axis now uses the same intervals for percentages. In the example it goes from 0% to 150%

Ruler seems to always use the width of the image to determine what 100% is and then interprets the height as a percentage of the width.

**My expectation:**

Rulers span from 0% to 100% irrespected the aspect ratio. If you have an image size 400x200 100% on the x axis is 400 pixels and 100% on the y axis is 200 pixels.

I use this feature very often to determine e.g. the center of an image.

**Comment by photopea** [comment]
I am not sure about this. Then, if you draw a rectangle, where the widht is the same value as the height (in percent), it will not be a square anymore.

Also, if you select a square, its width will be bigger than its height (in percent).

**Comment by smoli** [comment]
That one big commercial product acts exactly as you describe it. 

Rulers to me are primarily a tool to create accuracy using helper lines. I don't see a necessary connection of the ruler dimensions to other tools like selections or drawing-tools.

But even then I'd say there are instances where one might like to create some element in the image that is 80% of the height with a 10% margin at the top. That gets quite difficult if the y-ruler goes to 56.25% in a 1920x1080 image. In Photopea I now need to take out the calculator and compute the pixels myself. With the ruler going to 100% I could simply create a helper line while holding down shift.

**Comment by photopea** [comment]
Are you talking about Adobe Photoshop? BTW. there should be snapping to the middle of the document by default. It should be no problem to align something to the middle.

**Comment by smoli** [comment]
Yes, I'm talking about Photoshop. At least in CS4 Drawing a rectangle covering a full 400x200 image has a heigth and width of 100%. Getting the center is of course only one use. But maybe I'm using percentage rulers differently than most.

![image](https://user-images.githubusercontent.com/1009634/113032065-b81a1500-918f-11eb-95f9-54356cb1f536.png)

**Comment by photopea** [comment]
I fixed the problem. The vertical ruler is also 0 - 100 % now.

**Comment by smoli** [comment]
Awesome. Thank you!
