### ISSUE TITLE
Github Discussions In Repository [enhancement]

### ISSUE THREAD

**Issue by UnrealApex** [photopea/photopea#3081]
Instead of people asking questions and for feature requests in the issues section, I think it would be more useful to have them ask in discussions. Issues #3028 ,#2792,#2798 ,#2351 ,#2707,#2351, #3030, #3063, and a few closed issues would be a great example of this.  GitHub Discussions would allow users to make and vote on feature requests and answer questions all while not clogging the issues tab where bugs are normally reported. Let me know what you think.

**Comment by photopea** [comment]
People are free to discuss whereever they wish. Many people are also discussing on Reddit: https://www.reddit.com/r/photopea/
