### ISSUE TITLE
Photopea apresenta Bug em projetos com 10800px de largura

### ISSUE THREAD

**Issue by carlosraamos** [photopea/photopea#3083]
Ao criar um novo projeto nas dimensões 10800 x 1080px e plano de fundo branco, uma parte do plano de fundo fica transparente. Aparentemente parece ser um bug, onde o Photopea não reconhece da maneira correta projetos com largura de 10800px.

PS: a ideia é criar um template padrão para carrossel do instagram.
@photopea

**Comment by photopea** [comment]
Hi, maybe your computer does not have enough memory and it crashes. try using a smaller resolution.
