### ISSUE TITLE
importing image sometimes show main menu

### ISSUE THREAD

**Issue by gave3137** [photopea/photopea#3084]
when i want to edit photos and import a image from my files explorer
this show up idk how
![image](https://user-images.githubusercontent.com/81748495/113277236-b58ffa80-930a-11eb-9a57-2f272597d443.png)
ivan if you see this please fix this bug

**Comment by photopea** [comment]
Is your web browser updated? If not, update it. If yes, send me your file to support@photopea.com

**Comment by photopea** [comment]
I have to close it because of lack of details.
