### ISSUE TITLE
automatepod doesnt let me open csv file

### ISSUE THREAD

**Issue by grasshopper1979** [photopea/photopea#3086]
When I want to upload a csv file in automate POD, no window opens to let me choose from.  I looked for the settings in chrome extensions, but all seems to be like it should
![Screen Shot 2021-04-02 at 10 55 36](https://user-images.githubusercontent.com/81802615/113400372-fbe46880-93a1-11eb-8281-204907d2612f.png)
![Screen Shot 2021-04-02 at 10 57 16](https://user-images.githubusercontent.com/81802615/113400584-5087e380-93a2-11eb-8468-4feeb54628f6.png)

**Comment by photopea** [comment]
Hi, we did not create this browser extension. You should ask the creator of that extension about your problem.
