### ISSUE TITLE
.abr files not working

### ISSUE THREAD

**Issue by saas133** [photopea/photopea#3087]
https://gumroad.com/d/efe47172e1b77bf6ba2e95aafe183b3f
above is attached the link where i got my brushes, as ive checked,it is an abr file.
this set wasnt working as the inking showed up ten seconds after i actually did it.and after downloading this i tried it with more abr files,the packs did not show.

**Comment by photopea** [comment]
I can not download it there. Could you please attach the ABR file here in this thread, or send it to support@photopea.com ?

**Comment by saas133** [comment]
[abr brush.zip](https://github.com/photopea/photopea/files/6266902/abr.brush.zip)

**Comment by photopea** [comment]
I opened your brushes in Photopea, three brushes were added to the list of brushes. They seem to work well.

What exactly is the problem?

**Comment by photopea** [comment]
Is your web browser updated? It can be slow just because your browser simply can not make any website fast.

**Comment by saas133** [comment]
the brushes arent accurate,theyre slow and photopea wont let me upload more than 2 brushes.

**Comment by photopea** [comment]
Can you record a video of what you mean by "not accurate"? They work very well in my case.

**Comment by saas133** [comment]
i updated it already

**Comment by photopea** [comment]
I think I can see it now. When you click, it gets stuck for a second, and makes a long line. Is this what you meant?

**Comment by saas133** [comment]
yes,except for me this starts as soon as i download it,ive tried re-downloading

**Comment by photopea** [comment]
What do you download?

**Comment by saas133** [comment]
i meant ive tried re downloading the brushes or in more appropiate terms,re-uploading.

**Comment by saas133** [comment]
as in i deleted the brushes from local storage and tried to upload them again

**Comment by photopea** [comment]
It will not help. Photopea is slow. I know why it is slow and I know how to fix it. It will take me an hour or two.

**Comment by saas133** [comment]
thank you i will check back in a few hours

**Comment by photopea** [comment]
It should be fixed now.
