### ISSUE TITLE
clone tool does not pickup the source when using Alt+click on chromebook

### ISSUE THREAD

**Issue by ollihub66** [photopea/photopea#3088]
Hi All,
my clone tool does not pickup the source when using Alt+click on chromebook.
when I press Alt, the cursor changes into a target symbol, keeping the Alt key pressed, I click,
the cursor return as the brush, but when I move the brush, it doesn't show the content of the source, just a transparent brush.
when I click on the area to be replaced, the message "select the source by pressing Alt and clicking on the image" reappears again...
help please,
does this happens to you too ?
thanks for your help,
Ollivier

**Comment by photopea** [comment]
Hi, this is a well-known bug in Chrome OS. Google promised me, that they will fix it by the end of April.

Until then, you can use a virtual "Alt" key at the top of the menu (alse useful for devices without a keyboard, such as phones).

**Comment by ollihub66** [comment]
ah thank you so much for the workaround, 
I hadn't noticed the virtual 'alt' key.
great,
problem solved
