### ISSUE TITLE
[BUG Export TGA] Exported Mask Result Different

### ISSUE THREAD

**Issue by keyserjaya** [photopea/photopea#3089]
Before Export:
![image](https://user-images.githubusercontent.com/14213507/113502261-c8e6d400-955d-11eb-9755-d2d99bdf187c.png)

After Export. The result is different, same as when i open again in Photopea:
![image](https://user-images.githubusercontent.com/14213507/113502313-28dd7a80-955e-11eb-9bd9-2f18fda4d0a8.png)

How to reproduce:
1. Import this psd: 
[WFXM_T_BulletHoles Metal psd.zip](https://github.com/photopea/photopea/files/6254120/WFXM_T_BulletHoles.Metal.psd.zip)
2. Export to TGA > set file size to 64x64 > Press Save
3. After download complete.... > rename/change extention to TGA
4. Open again in Photopea

**Comment by photopea** [comment]
Hi, what do you mean by "change extension to TGA"? The saved file should already have the TGA extension.

Can you try to save a TGA file in Incognito mode? I think that some of your browser extensions is renaming files to TXT for you.

**Comment by photopea** [comment]
I have fixed the problem. Additional channels should be exported correctly, when you set a custom image size.
