### ISSUE TITLE
problem with "Escape or Confirm"

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#309]
I added text and before confirming or canceling I went into blending options of layer.
After moving opacity slider it spawns very large number of "Escape or Confirm the current action (in the top menu)" messages that keeps going long time (minutes) and can't be stopped.

**Comment by photopea** [comment]
Hi, when you are editing text, you should only edit this text and not anything else. You have to escape or confirm the editing, before doing anything else.

Please see https://www.photopea.com/learn/text-layers .

**Comment by hxim** [comment]
@photopea I know that I did it by accident the problem is you can't get rid of this unstoppable flow of "Escape or Confirm the current action (in the top menu)" messages incoming and continue with work on image if this accidently happens (it overlaps almost entire screen). It generates hundreds or thousands of messages and it shows only one per second so it keeps going for several minutes or longer... Can you fix this please?

**Comment by photopea** [comment]
Ok, I understand. I fixed it.

Now, such message can be shown at most onece per second. So you will not get 100 messages at once.

**Comment by hxim** [comment]
Thanks, I confirm it works with no issue for me now.
