### ISSUE TITLE
Photopea .png save requiring file association

### ISSUE THREAD

**Issue by grayphoenixgames** [photopea/photopea#3090]
While saving files in photopea, only when I try to save .png files, does it require a file association with an app to preview the file. Any other file extensions I save as do not require this. This preview needs to be able to be disabled.

**Comment by photopea** [comment]
Hi, I don't really know what you are talking about. When I save a PNG file in Photopea, a .PNG file is created in my computer, which I can use as any other PNG file in my computer.

What do you mean by "preview the file"? Is it happening in a web browser or it is a problem in your computer after saving?

**Comment by MichalSZZ** [comment]
@grayphoenixgames are you sure that is a PNG file? That behavior as you mentioned is when somebody wants to view in system preview the WebP files...
Sometimes I saw on the websites files that look like from extensions as PNG but in specification of coding that file it was a WebP.
