### ISSUE TITLE
[bug] text layer issues

### ISSUE THREAD

**Issue by nathgit** [photopea/photopea#3091]
I can create one text layer, but once I finish editing it & click the checkmark, it no longer responds to clicks & I can't create a second text layer. This seems to only happen at random with any known cause. I even tried closing & reopening Photopea, with no change.

**Comment by photopea** [comment]
Hi, I tried to create two text layers and it worked well. What exactly should I do to see the issue that you are describing?

Does it still happen after you disable all browser extensions?

**Comment by nathgit** [comment]
I have tried to reproduce the issue again & (of course) so far it hasn't happened again, so I don't know what was causing it before, but hopefully it won't happen again.

**Comment by photopea** [comment]
Maybe someone else will find steps how to reproduce this issue. I will close it until then.
