### ISSUE TITLE
Brush tool

### ISSUE THREAD

**Issue by ERRORNOTFOUND40** [photopea/photopea#3092]
When i draw with the brush tool, the color is a reddish pink that has a tiny bit of opacity. the pencil tool and bucket tool also have this, PLEASE HELP

edit: when i try to change color, it just turns into a shade of gray

**Comment by photopea** [comment]
Can you show us a screenshot of what you mean? I think you enabled the quickmask (by pressing Q), press Q again.

**Comment by photopea** [comment]
I have to close it because of lack of details.
