### ISSUE TITLE
Photopea API can't access a few images on my server because of CORS policy

### ISSUE THREAD

**Issue by NickDomanti** [photopea/photopea#3093]
Photopea does't seem to be able to load some images, the issue should be the CORS policy judging by the error in the console
(this doesn't happen with all images, only with a few)
![Screenshot (84)](https://user-images.githubusercontent.com/71645425/113687913-1764b180-96c9-11eb-99fa-f4c80e4906a8.png)

As you can see, while requesting the same image through Chrome's REST Client, there is the Access-Control-Allow-Origin header properly defined, this made me think that my implentation isn't the problem but that there is probably a bug in Photopea, do you know anything about this?
![Screenshot (83)](https://user-images.githubusercontent.com/71645425/113687586-c785ea80-96c8-11eb-8a26-ae13fca5c01a.png)

EDIT: I even tried setting the header value to *, but nothing changed.

**Comment by photopea** [comment]
It would be so much easier if you wrote the URL of your image.

**Comment by NickDomanti** [comment]
I'll answer on Github

Il giorno mar 6 apr 2021 alle ore 11:38 Photopea ***@***.***>
ha scritto:

**Comment by NickDomanti** [comment]
https://gestionale-edilservice.it/website-images/AB4U.jpg this is one of the problematic images
https://gestionale-edilservice.it/website-images/ACWC.jpg and this is one of the working ones, if you want to compare

**Comment by photopea** [comment]
So I created this URL, which is supposed to load your image, and it works well: https://www.photopea.com#%7B%22files%22:%5B%22https://gestionale-edilservice.it/website-images/AB4U.jpg%22%5D%7D

So I have two hypotheses:

- your browser is caching the old version of your image, which did not have the CORS record
- you have a browser extension, which breaks Photopea

**Comment by photopea** [comment]
Both problems should be "fixed" if you do it again in Incognito mode.

**Comment by NickDomanti** [comment]
I confirm that in Incognito mode works, I still have to "fix" the issue outside of it, thank you so much anyway

**Comment by photopea** [comment]
You should clear the cache of your browser. But you can be sure that it works for the rest of the world, as they did not try to load your image with no CORS as you did.
