### ISSUE TITLE
Font size issue

### ISSUE THREAD

**Issue by dmytrohavrysh** [photopea/photopea#3094]
Hi!
When I open a psd file with a custom font and try to measure the font size with the Text tool, the font size does not match the correct value. For example, if I click on a font and get a value of 20, although the font size is actually 30 [Image](http://prntscr.com/115zxfy) If you change the font by at least 1 pixel, it instantly decreases.[Image](http://prntscr.com/115zyqn)

**Comment by photopea** [comment]
In a text layer, each character can have a different size. Are you sure that your whole text has the same text size? Could you share a PSD with us?

**Comment by dmytrohavrysh** [comment]
Yes, i sure. I selected the right text layer. Here is the link to psd: [PSD](https://dropmefiles.com/4opYA)

**Comment by photopea** [comment]
I think it should be fixed now.
