### ISSUE TITLE
Artboards - Drag and drop images don't fall on (0,0) of the artboard

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3095]
When drag and dropping images to the canvas, they fall in the 0,0

But when adding an image to an artboard, it keeps falling on 0,0 of the canvas, not the artboard.

So everytime i have to discover where the image landed.

**Comment by avagp** [comment]
This also happens when duplicating layers with AltGr+click

And maybe when duplicating with the layer's menu

**Comment by avagp** [comment]
Duplicated layers on artboards should land on the same coordinate as its source.

**Comment by photopea** [comment]
Now, the dropped image will be placed on top of a selected layer (or at the top of the folder, if a selected layer is a folder). It will always be inside a current artboard.

I fixed the problem with duplicating layers inside an artboard, too.
