### ISSUE TITLE
Warp dialog issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#3097]
A.
1. I opened Warp dialog in Type Tool.
2. I switched to other tool (Move Tool for example)
3. Warp dialog can't be closed with cross button in top right corner of dialog window.
Screenshot:
![image](https://user-images.githubusercontent.com/6370548/113825484-50605d00-9781-11eb-8651-d32ad8c5d621.png)

----

B.
Also I don't know why those buttons (Cancel and Confirm) are shown next to Warp button when Warp dialog is open
![image](https://user-images.githubusercontent.com/6370548/113825830-bc42c580-9781-11eb-865c-11a998ed119d.png)
They seem to do nothing and I think they shouldn't appear in case of Warp dialog.

**Comment by photopea** [comment]
It should be fixed now. Hiding confirm buttons when showing a window is too much work, sorry :(
