### ISSUE TITLE
darker user interface

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#3099]
I spend a lot of time using photopea and photoshop in my darkroom as main softwares, so can you make photopea darker or give me the option as adobe photoshop does?

photoshop

![Screenshot (109)](https://user-images.githubusercontent.com/70863817/113936304-e2a34800-97f7-11eb-96ba-88792f406a8a.png)

photopea
![Screenshot (110)](https://user-images.githubusercontent.com/70863817/113936340-ed5ddd00-97f7-11eb-9e96-24abbcf9d367.png)

it might be weird but sometimes I find photopea so bright, making it darker won't be a problem right?

**Comment by mustafaGFX** [comment]
I made a color palette to show you how much photoshop darker than photopea
![New Project (29)](https://user-images.githubusercontent.com/70863817/113937286-319dad00-97f9-11eb-93a2-7375aaff79c6.png)

**Comment by nothingshiru** [comment]
I like the color in Photoshop too.

**Comment by mustafaGFX** [comment]
would this be good?
the current theme called dark, and the new one called black

![Screenshot (112)](https://user-images.githubusercontent.com/70863817/114033088-3c9a2100-987d-11eb-8eff-67078ac1a222.png)

**Comment by photopea** [comment]
Hi, I have added a new theme into More - Theme - Super Black. Is it ok?

**Comment by mustafaGFX** [comment]
it's perfect
thanks :)
