### ISSUE TITLE
project size by clipboard

### ISSUE THREAD

**Issue by Studioartcz** [photopea/photopea#31]
Hi,

what about create new project by width, height sizes from my clipboard?
I want copy some selected area to as new project with this sizes.

How i can check sizes of selected area?

**Comment by photopea** [comment]
Hi,
webpage (unlike native app) can not read the content of Clipboard before it is inserted in "onpaste" event. 

What about Crop tool? You can crop the new project according to the content or selection (there are 3 buttons).

**Comment by Studioartcz** [comment]
Hi, 

but selected area & CTRL + C web can read :)

**Comment by photopea** [comment]
I think it can be sloved now by cropping according to content.
