### ISSUE TITLE
Add support for DDS format

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#310]
It would be nice to support DDS format.

[brick.zip](https://github.com/photopea/photopea/files/1447100/brick.zip)

**Comment by photopea** [comment]
@PiranhaGreg Only ETC2 compression is supported by WebGL. DXT compressions can be available as GL extensions on some Windows devices, but many of our users don't have Windows.

Also, Photopea can run without WebGL completely, so we can not count with WebGL.

**Comment by photopea** [comment]
Done! Photopea can open and export DDS files!

**Comment by PiranhaGreg** [comment]
That was fast 👍 !

Are you planning release this as standalone library? I would be interested...

**Comment by photopea** [comment]
Yes, I would like to release it as an open-source :)  There is decompression of BC1, BC2, BC3 and BC7. Compression of BC1 and BC3.

**Comment by photopea** [comment]
Ok, so as you probably noticed, the Texture compression library is here: https://github.com/photopea/UTEX.js
