### ISSUE TITLE
Issue: Angle of handle might be a little off while holding Shift key and Dragging them

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3100]
Create a anchor with horizontal handles then hold Shift key and drag the handle. The angle of handle might be a little off while it should be absolutely horizontal in this case. 
![Screenshot_20210501_013430](https://user-images.githubusercontent.com/79258245/116733189-5fec6200-aa1e-11eb-9dd8-62cba0f9bf4f.jpg)

https://user-images.githubusercontent.com/79258245/116733193-611d8f00-aa1e-11eb-8c1e-f1f5634f1728.mp4

**Comment by photopea** [comment]
Fixed, thanks for reporting!
