### ISSUE TITLE
Warp moving wrong control point

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#3102]
1.) Edit - Transform - Warp.
2.) Move bottom right control point
3.) Try to move other control point with mouse (where is mouse cursor in this screenshot)
![image](https://user-images.githubusercontent.com/6370548/113973979-79debe80-983d-11eb-9d7b-72db7b825d55.png)
4.) Wrong control is moved (see screenshot what happened)
![image](https://user-images.githubusercontent.com/6370548/113973999-806d3600-983d-11eb-8da3-40e441b6c306.png)

psd: 
[New Project.zip](https://github.com/photopea/photopea/files/6276318/New.Project.zip)

**Comment by photopea** [comment]
Fixed, thanks for reporting!
