### ISSUE TITLE
hue/saturation, saturation doesn't go to -  when colorize is checked

### ISSUE THREAD

**Issue by parmonov98** [photopea/photopea#3103]
https://youtu.be/VFIu57ricmc

**Comment by photopea** [comment]
That is how it should work.

**Comment by MichalSZZ** [comment]
@photopea I think thatcomparing to Photoshop UI, there after check the Colorize option, slider of saturation have 0 to 100% not -100 to 100% as in Photopea now. That can be misleading for the user - "why I can not move to the left".
And after that the default option for Colorize in Photopea is "desaturate" that make image black and white (saturation is in the middle but that is saturation 0). When user doesn't change the saturation to something bigger that 0 any change in hue is invisible.

@parmonov98  is that your problem as I wrote above? 
BTW - your selection on that video was the first thing what I saw, but it isn't a problem of that case I think
