### ISSUE TITLE
Artboards: duplicated layer appears always in place of artboard that is first from the left

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3104]
https://www.photopea.com/#iGsPy6jDV 

**Step to reproduce:**
1. Select (on layers palette) some layer from artboard in the middle of two other ones.
2. Use Ctrl+J to duplicate

**What is expected:**
Layer shoud appear in same place on the same artboard.

**What is now in Photopea:**
Layer is in correct artboard folder, but in wrong place on the project

**Comment by MichalSZZ** [comment]
I dont know byt maybe it is related with this issue: https://github.com/photopea/photopea/issues/3095

**Comment by photopea** [comment]
It should be fixed now.
