### ISSUE TITLE
brushes

### ISSUE THREAD

**Issue by saas133** [photopea/photopea#3105]
hi there!I was wondering if you could add better settings for brushes.by that i mean:
in photoshop ,you have way more brush settings which are useful,including:
![image](https://user-images.githubusercontent.com/81762306/114018600-53cd1480-9865-11eb-8897-963ee64c1c40.png)

**Comment by photopea** [comment]
I am too busy to make all this :( Could you mention one brush parameter, that is the most important to you?

**Comment by saas133** [comment]
hi!thanks for replying!maybe brush pose?could you follow up to this maybe when you have the time?Your reply is appreciated:)

**Comment by photopea** [comment]
Sorry, our brush engine is very simple now, and it is not possible to add these advanced parameters :(
