### ISSUE TITLE
brush angle

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#3108]
I noticed that in a lot of tools in photopea you put the angle control tool, like in gradient shape, and some filters

![Screenshot (113)](https://user-images.githubusercontent.com/70863817/114193148-869f0780-994e-11eb-8f2a-59b1ab366719.png)

At the same time, this tool doesn't exist in the brunch settings which is the most used tool I guess

![Screenshot (114)](https://user-images.githubusercontent.com/70863817/114193408-c6fe8580-994e-11eb-85b7-27ae49f4f877.png)

would it be a problem if you put this tool there as photoshop and affinity designer do?

![Screenshot (115)](https://user-images.githubusercontent.com/70863817/114193708-15138900-994f-11eb-8c95-0a896b2f2fee.png)

**Comment by mustafaGFX** [comment]
hi
I need this feature

**Comment by Kennyman2021** [comment]
Honestly this feature will greatly help users who wants to do photo compositing and painting in photopea.

**Comment by mustafaGFX** [comment]
@Kennyman2021 
it will help almost everyone, I don't what will be a problem if @photopea  made it

**Comment by mustafaGFX** [comment]
at least give me the option, would it be a problem to give me the option to turn on or off the brush angle in the settings?

**Comment by photopea** [comment]
I will add this feature tomorrow.

**Comment by photopea** [comment]
I made this kind of selector of the angle and the roundness.

I am sorry it took me so long, I was working on something else.
