### ISSUE TITLE
Cant export

### ISSUE THREAD

**Issue by Stephperiodt** [photopea/photopea#3110]
Everytime i export it instead turns into a text file with a bunch of random letters numbers and symbols

**Comment by photopea** [comment]
Hi, you have a browser extension, which renames files from Photopea to TXT. If you do not know how to turn that extension off, use Photopea in Incognito mode (where extensions are disabled).

**Comment by Stephperiodt** [comment]
No its still not working

**Comment by Stephperiodt** [comment]
> Hi, you have a browser extension, which renames files from Photopea to TXT. If you do not know how to turn that extension off, use Photopea in Incognito mode (where extensions are disabled).

Hi, its still not working

**Comment by photopea** [comment]
Have you tried in the incognito mode?

**Comment by photopea** [comment]
I think you are lying, you did not disable all browser extensions.

**Comment by Andre-Bra** [comment]
> Everytime i export it instead turns into a text file with a bunch of random letters numbers and symbols

I also had the same problem. I disable all browser extensions and it worked (Chrome)

**Comment by photopea** [comment]
@Andre-Bra there is no need to disable all extensions. It is usually just one extension which renames files. But we ask people to disable all extensions to show, that the problem is in an extension they use, and not in Photopea.
