### ISSUE TITLE
Vector Copy Paste Issue

### ISSUE THREAD

**Issue by Daniru2007** [photopea/photopea#3111]
**I can't copy selected vector images.**

I think that there are no option to copy or paste vector images in the photopea
I don't know whether is it a bug I think you can add it as a feature.
Love to see that option too...

![Screenshot_1](https://user-images.githubusercontent.com/75978227/114289899-0e912880-9a99-11eb-9871-7a7250d4bc51.png)

**Comment by photopea** [comment]
You can copy-paste layers by pressing Edit - Copy, Edit - Paste, or Ctrl+C, Ctrl+V.
