### ISSUE TITLE
RAW highlights issues from DJI Mini 2

### ISSUE THREAD

**Issue by BuildTheRobots** [photopea/photopea#3113]
Just tried importing a RAW image from a DJI Mini 2 Drone and it doesn't seem to be getting interpreted properly.

Issue is the flare around the sun, in Photopea it's looking extremely red/pink (screenshot included).
Adobe's interpretation seems more "correct" (screenshot included).
Darktable seems to make sense of it too (screenshot included).

Greatest of thanks.

DJI Created Raw:

[DJI RAW: DJI_0021.zip](https://github.com/photopea/photopea/files/6291612/DJI_0021.zip)

DJI Created JPEG:

![DJI_0021](https://user-images.githubusercontent.com/5307527/114302149-b6215180-9abf-11eb-97b2-80f1dfe226b1.JPG)

Photoea Screenshot:

![Capture - photopea](https://user-images.githubusercontent.com/5307527/114302164-c3d6d700-9abf-11eb-859c-a31bd40b6904.PNG)

Adobe Screenshot:

![Capture - adobe camera raw](https://user-images.githubusercontent.com/5307527/114302175-ccc7a880-9abf-11eb-8e10-e41965e15ae5.PNG)

Darktable Screenshot

![Capture - darktable](https://user-images.githubusercontent.com/5307527/114302189-d4874d00-9abf-11eb-9f3b-9c089136d787.PNG)

**Comment by photopea** [comment]
This problem happens for all raw files, which contain overexposed areas. It took me an hour to find a solution, which works for 95% of cases (including your case). But I am working on a proper solution. It should be done soon (I hope).

**Comment by BuildTheRobots** [comment]
Thank you very much for the response -and apologies for causing you more problems.
I am in absolutely no rush to get this fixed, it just seemed par for the course that the first file I threw into Photopea turned out to be problematic.

Massive thanks and respect for the Photopea - even with this bug it's extremely impressive and nice to use :)

**Comment by photopea** [comment]
It should work much better now :)

**Comment by BuildTheRobots** [comment]
Brilliant - thank you very much :)
