### ISSUE TITLE
cropped "Account" pop-up window on smartphone 

### ISSUE THREAD

**Issue by DanAlka** [photopea/photopea#3115]
![Screenshot_20210412-020101](https://user-images.githubusercontent.com/34134499/114326196-e276b580-9b33-11eb-8273-209974ba5f32.png)

Not really a bug: just a small design/UI thing.
"Account" pop-up window is viewed cropped (not resized/auto-adjusted to fit the screen) on smarthphones and if you want to move (or close) the window to the left (to see the rest of the window):                                                                                                           it's not possible unless you drag and move the window by very top area (the thin line where "Account" is written)..

Thanks for the great software!

Photopea is the best editing software there is!

greetings from Prague, 

Dan

**Comment by photopea** [comment]
I fixed the problem. The Account window should work much better on small screens now :)

**Comment by DanAlka** [comment]
Thank you for a quick fix! It works / perfect now. 
Dan
