### ISSUE TITLE
using photopea will crash my surface?

### ISSUE THREAD

**Issue by taintedtoffee** [photopea/photopea#3117]
I can open photopea, but using it for longer than a minute will cause it to crash, the screen go black and then it shuts down my device destroying my drawing. I would say it is a device issue but my sibling has been having the same issue on their device, and it only occurs on photopea, nothing else. it used to go dark less frequently, but it would power off my device, then I found a function in settings that would prevent it from shutting down, so it just went dark for a second then came back. but now all of a sudden if I make a brushstroke, it lags then shuts off everything again, even with the setting function?? its become intolerable.

**Comment by photopea** [comment]
I think Photopea runs out of memory, and your browser shuts it down.

How large documents are you editing? Is it a million pixels, ten million, a hundred million? E.g. 5000x5000 pixels is 25 million.

How much RAM do you have in your device? Is your web browser older than 5 years?

**Comment by taintedtoffee** [comment]
I most often work in canvases at 800x1280 pixels or just 800x800 (both
sizes had this issue.) and I only have about 8.0 GB used on this thing.
(sorry if that's not a sufficient answer to the RAM question, i'm not the
most tech savvy) it's BRAND NEW. I'm also not sure how to check the age of
my web browser, but I doubt age should be the issue.

**Comment by taintedtoffee** [comment]
additionally, I just used a miniscule canvas, (50x50) out of curiosity. same issue, no change.

**Comment by photopea** [comment]
That is really strange. A website should not be able to turn off your computer. I think your device is damaged, you should return it to the one who sold it to you.

**Comment by photopea** [comment]
Are there any news? I will close it for now.
