### ISSUE TITLE
Text box problem

### ISSUE THREAD

**Issue by GraphicDesignTeacher** [photopea/photopea#3118]
I was using the pen tool to create custom text boxes which was working surprisingly well. I opened an existing project to continue working and the function no longer works. No custom text boxes or regular rectangular text boxes drawn with the text tool. The line of type just extends until I hit the enter key. All my students are having the same problem.

**Comment by photopea** [comment]
I think some of your browser extensions could be breaking Photopea. Does the problem happen with all extensions disabled?

Also, it is really useful if you share a screenshot of what exactly happens in Photopea.

**Comment by photopea** [comment]
I think you saved your project as a JPG or PNG.

If you want the text to be editable in your file, you should save your work as a PSD: File - Save as PSD.
