### ISSUE TITLE
open image in photopea

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#3119]
recently I used to open images by their URL, it takes a lot of time to open the image in a new tab then copy the URL then going to photopea and click file>open more> open from URL, it takes about 15 seconds to just open 1 image, imagine how much it takes to open 10 images

and I have noticed that I can open the images to the browser apps like Pinterest by right click the image and click the app icon
![Screenshot (121)](https://user-images.githubusercontent.com/70863817/114579312-08a86c80-9c7e-11eb-8461-325d4da7ccda.png)

so can you make the same thing to photopea, please don't ignore me cuz I really need this

**Comment by mustafaGFX** [comment]
can u answer me

**Comment by photopea** [comment]
Do you have a Pinterest browser extension in your web browser?

**Comment by mustafaGFX** [comment]
yes I have

**Comment by photopea** [comment]
You see "Pinterest" on right-click probably because you installed a Pinterest extension into your web browser.

You can copy images on the web by right-clicking an image and choosing Copy. Then, you can paste them into any photo editor (Photopea, Photoshop, Gimp) with Ctrl+V.
