### ISSUE TITLE
Can't open sketch file, Loading screen.

### ISSUE THREAD

**Issue by Zed2018** [photopea/photopea#312]
Hello, can you plz help me, i can't upload my sketch file, the screen stay at "loading" screen. I want to convert it from sketch to PSD.
my file : https://we.tl/PHbtXdcM2A
Thx and sorry for my bad english !

**Comment by photopea** [comment]
Hi, your Sketch file contained CMYK color, which was not supported, so we fixed it, you can open your file now.

Note, that your file is quite large, it may take 1 minute to open, and it may require 5 GB of RAM. We will try to improve this in the future. 

Until then, if it still crashes, you can split your file into multiple Sketch files, or don't use Stroke on the whole folder (it takes 20 seconds and 1.5 GB of RAM to compute in your case).

**Comment by Zed2018** [comment]
thx !!! it work :)
