### ISSUE TITLE
Zoom level is brutal

### ISSUE THREAD

**Issue by Romarain** [photopea/photopea#3120]
The zoom level in Photopea is too brutal.
Do I need to define "brutal" ? Do I need to make a video ? 
Do I need to make two distinct screenshots and post it here ?

Level 12 of zoom :
![2021-04-13_22h28m22s_chrome](https://user-images.githubusercontent.com/22033256/114616925-bf6d1280-9ca7-11eb-98b0-2d85b561c65e.jpg)

Level 13 of zoom : 
![2021-04-13_22h28m26s_chrome](https://user-images.githubusercontent.com/22033256/114616896-b5e3aa80-9ca7-11eb-83cc-df910e704a81.jpg)

**I can't have a descent level of zoom to work.**

**Comment by photopea** [comment]
Hi, the zoom can be any number. Press View - Rulers. Then, double-click the zoom value at the bottom left corner.

**Comment by Romarain** [comment]
Yep, but the purpose is not to have to enter a value with a keypad (wich is too long), but to use the shortcuts (ALT+Mousewheel).
