### ISSUE TITLE
quality and size bug

### ISSUE THREAD

**Issue by markeljyt** [photopea/photopea#3121]
When I do a thumbnail on my phone the size will be at 1280 x 720, when I download the thumbnail from my phone onto my computer and try to use it in photopea the quality and size will change to 721 x 406 when I try to export it. When I do send it back to my phone the quality will be completed lowered in quality compared to when I first had it on my phone

**Comment by photopea** [comment]
It looks like your image is modified, when you transfer it between your phone and your computer.

What is the size of your image (in Bytes) on your phone and your computer? Is the size the same?
