### ISSUE TITLE
Text disappears if I change font weight or style

### ISSUE THREAD

**Issue by alexwe91** [photopea/photopea#3123]
Hi
the Text disappears if I change font weight or style. The layer is still there but the text is not visible anymore. Safari, MacBook Air 2020 M1

**Comment by photopea** [comment]
can you rewrite the text, without changing its style or font?

**Comment by alexwe91** [comment]
yes, if I dont change style, then I can rewrite



Am Mi., 14. Apr. 2021 um 18:07 Uhr schrieb Photopea <
***@***.***>:

**Comment by photopea** [comment]
Does it happen for every PSD file you open in Photopea? Can you update your web browser?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
