### ISSUE TITLE
Fonts loaded from device are not working

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3125]
No matter what I typed, there's only blank.
![screenshot_20210415_010355](https://user-images.githubusercontent.com/79258245/114750662-ce76c200-9d86-11eb-8518-eb6a76cc8990.jpg)

https://user-images.githubusercontent.com/79258245/114750669-d0408580-9d86-11eb-9401-636b7d1f6f2a.mp4

The .otf files were downloaded from here. https://github.com/adobe-fonts/source-han-sans/tree/release
![Screenshot_20210415_010457](https://user-images.githubusercontent.com/79258245/114750807-f82fe900-9d86-11eb-9069-cad8c43d3346.jpg)

There's nothing in Glyphs panel. 
![screenshot_20210417_171906](https://user-images.githubusercontent.com/79258245/115108112-43bddf00-9fa1-11eb-8376-13aff61fb3d8.jpg)

**Comment by nothingshiru** [comment]
I know there are already Source Han Sans in Photopea. But loading them will cost me a lot of time everytime I opened Photopea. Is there a way to download them into my device?

**Comment by photopea** [comment]
I set the caching for fonts to 14 days. So if you use them once in Photopea, they should be stored in a cache for 14 days (and not re-downloaded during these 14 days).
