### ISSUE TITLE
Feature Request: Option "Roundness" in Minimum/Maximum filter

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3126]
Now there is only Squareness in Minimum in Photopea. When I apply it to a circle, the circle is no longer a circle. 
![screenshot_20210415_160533](https://user-images.githubusercontent.com/79258245/114836734-8ba7ff00-9e05-11eb-958c-b97ec131b821.jpg)
![screenshot_20210415_160028](https://user-images.githubusercontent.com/79258245/114836744-8cd92c00-9e05-11eb-87da-78a6cabc47a0.jpg)

Most of time I want to preserve the shape.

**Comment by dentistformyeye** [comment]
In addition, I would also like to be able to use decimal values for Minimum and Maximum.

**Comment by photopea** [comment]
I have added the "Round" shape for the Minimum and Maximum filters, and decimal values for the radii! :) 

But if the image or the radius is too big, it will still be rendered as a square, because of the performance.

**Comment by dentistformyeye** [comment]
It works fine when WebGL is on, but has different results when WebGL is off. When WebGL is off, the Circle mode acts like the Square mode.
1. After ensuring that extensions are turned off, go to Photopea and choose File > New. Click Create.
2. Go to More > Use WebGL and turn WebGL off.
3. Set the foreground color to black. Use the brush tool to make a dot on the canvas.
4. Choose Filter > Other > Minimum. Change the shape to Circle. >> The expanded brush mark still looks like a square; there's no visual change.

Also, when WebGL is off, inputting a value for the radius that isn't a whole number produces weird results and seems to consume a disproportionate amount of memory.
1. After ensuring that extensions are turned off, go to Photopea and choose File > New. Change the width and height to 200 px. (If I use the default 1280 x 720, I run out of RAM in step 4 and the site crashes.) Click Create.
2. Go to More > Use WebGL and turn WebGL off.
3. Set the foreground color to black. Use the brush tool to make a dot on the canvas.
4. Choose Filter > Other > Minimum. Change the value in the text box to 7.9 and press the Enter key to confirm the new radius value.
![image](https://user-images.githubusercontent.com/51429646/117087446-7562d400-ad1d-11eb-988a-2aadd85dd38d.png)
![image](https://user-images.githubusercontent.com/51429646/117087478-8f9cb200-ad1d-11eb-8b76-e87bc78c0182.png)

**Comment by dentistformyeye** [comment]
Could you also allow for the lowest radius value for Minimum/Maximum to be 0.1 px?

**Comment by photopea** [comment]
I have set the minimum Radius to 0.1 px and fixed the problem with non-integer radius without WebGL

The circular shape would take too much time to compute without WebGL, so it is available only with WebGL.

**Comment by dentistformyeye** [comment]
Thank you!
