### ISSUE TITLE
Using text tool causes top of screen to go blank

### ISSUE THREAD

**Issue by sandra110684** [photopea/photopea#3127]
Whenever the text tool is chosen the top of the screen and all of the menu bars disappear. It does not appear to happening with any other tools. Any idea on what I can do to fix it? 
![image](https://user-images.githubusercontent.com/82589228/114869923-2b8d6a80-9dbd-11eb-82f1-c8e0d0361794.png)

**Comment by photopea** [comment]
Can you try these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I think your web browser is not updated, or a beta version. Everything should work well in a modern, stable web browser.
