### ISSUE TITLE
Please do not activate the search box when open fonts panel

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3129]
On tablet or mobile phone, the virtual keyboard will show up and cover stuffs when the search box is activated. 

But we're not going to search fonts by typing everytime open fonts panel, we could choose the fonts that are collected. And we don't want virtual keyboard showed up, especially when using a mobile phone with small screen. 
![Screenshot_20210415_220330](https://user-images.githubusercontent.com/79258245/114884693-8d3eea80-9e38-11eb-801c-f7b8bce36172.jpg)

**Comment by photopea** [comment]
fixed!
