### ISSUE TITLE
Cannot Open Sketch File / Opens Broken

### ISSUE THREAD

**Issue by tragicrich** [photopea/photopea#313]
We have been having issue uploading Sketch files today. Initially they would not load at all and just showed the loading bar. We removed the "pages" from the Sketch file and saved them individually, now the file opens but none of the assets are loading.

There are javascript errors, these errors are from the individual files without the pages. These files open, but are unusable as too many assets are missing:

[home-m.zip](https://github.com/photopea/photopea/files/1448188/home-m.zip)

Uncaught TypeError: Cannot read property 'IM' of undefined
    at Function.wh.$K (pp.js:1789)
    at Function.wh.$K (pp.js:1766)
    at Function.wh.$K (pp.js:1766)
    at Function.wh.$K (pp.js:1766)
    at Function.wh.RS (pp.js:1750)
    at Function.w_.XW (pp.js:5615)
    at w_.XE (pp.js:5608)

**Comment by photopea** [comment]
Hi, I just tried to open your file in Photopea and it worked fine, I can not see any error. Can you reload Photopea.com and try it again?

**Comment by tragicrich** [comment]
Hello, 

Sorry if I was unclear. The file was not opening originally when using Sketch "pages". We removed the pages and exported as individual files. It now opens, but none of the images / buttons /gradients are shown.

The file should appear like the attached jpg.

![home-m](https://user-images.githubusercontent.com/28912570/32471531-a2bdddd0-c312-11e7-87fb-f7eb7e6d677f.jpg)

**Comment by photopea** [comment]
In your file, there is a folder "home-in", and "Floating CTA" inside it. This "Floating CTA" should have a 1 pixel border around it, but your preview does not have any border, I see only drop shadow. 

How do borders on folders work in Sketch?

**Comment by tragicrich** [comment]
My other designer was able fix the issues with the files. Unfortunately I am not sure what he changed...but at least this is fixed.

**Comment by photopea** [comment]
Can you ask your designer to take a look at this thread and maybe answer some questions? We must make Photopea work with all Sketch files correctly.

**Comment by photopea** [comment]
I am closing it because of lack of details. Hope somebody will report it again, somebody with more time to cooperate.

**Comment by tragicrich** [comment]
The majority of the issues were caused by the fact that my designer had several different artboards shown in a single sketch file. Once we broke the artboards out into their own files Photopea was able to render the file.

**Comment by photopea** [comment]
I understand. But I would still like somebody to answer my questions above. We are making a viewer of Sketch files, but we don't have Sketch App or any Mac OS device at all, so we don't know what is the right way of displaying Sketch files in some cases.
