### ISSUE TITLE
Saving as .pdf file

### ISSUE THREAD

**Issue by FynniX** [photopea/photopea#3132]
Hello,
there is a problem with saving as a pdf when using a script.

This is my Code Snipped:

`var pdfOptions = new PDFSaveOptions();
pdfOptions.preset = "[Smallest File Size]";
app.activeDocument.saveAs(new File("output.pdf"), pdfOptions);`

**Comment by FynniX** [comment]
I think the problem here is, that the presets arent included

**Comment by photopea** [comment]
Your code should work well now. Is it enough for your needs?

**Comment by FynniX** [comment]
Thanks, works now
