### ISSUE TITLE
Angle controller in Layer Style can't be dragged properly and easily with finger

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3135]
![screenshot_20210416_173201](https://user-images.githubusercontent.com/79258245/115005634-a304ec00-9eda-11eb-9e74-dfcf9a31bb79.jpg)

1. Can't be dragged properly with finger
there's a same problem as #3067 

2. Can't be dragged easily with finger
It's too small for tablet/phone. Having a button next to it for get it bigger would be nice.

**Comment by photopea** [comment]
There was a bug, it should be fixed now.
