### ISSUE TITLE
The action which is creating folder is executed incorrectly in Photopea

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3136]
The action creating folder by clicking on the button at bottom of Layer panel is executed as same as Group Layers(shortcut: Ctrl+G). 

The difference is that Group Layers will put current layer into the new folder, but Clicking on the button will not. 

Here's the action creating folder. (Recorded in Photoshop) 
[Create Folder.zip](https://github.com/photopea/photopea/files/6331197/Create.Folder.zip)

**Comment by photopea** [comment]
Thanks a lot, it is fixed now.
