### ISSUE TITLE
Bottom red, green, and blue Blend If sliders don't work unless another slider is changed

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#3137]
1. After ensuring that extensions are disabled, copy-paste the following image into Photopea.
![image](https://user-images.githubusercontent.com/51429646/115042946-f1e25f80-9ea1-11eb-98b3-bfa07ea831a6.png)
2. Choose Layer > New Adjustment Layer > Hue/Saturation in the top menu.
3. Set the Hue parameter of the adjustment layer to 45.
![image](https://user-images.githubusercontent.com/51429646/115043453-877def00-9ea2-11eb-9ad8-007ab1bf4b65.png)
4. Right-click the adjustment layer in the Layers panel and choose Blending Options.
5. Change the Blend If color option to red. Drag the bottom-right handle to a number less than 100, then drag it back to 255. >> Nothing happens to the image, even though part of the top layer is supposed to disappear/reappear as the handle moves.
![image](https://user-images.githubusercontent.com/51429646/115045707-c319b880-9ea4-11eb-9470-172938365105.png)

6. Change the Blend If color option to gray. Drag the bottom-right handle to 254.
7. Change the Blend If color option to red. Drag the bottom-right handle to a number less than 100. >> This time, part of the top layer disappears, as expected.

The handle in step 6 can be for any slider other than the bottom slider for red, green, or blue. For example, you could instead change the top-left handle for red from 0 to 1.
![image](https://user-images.githubusercontent.com/51429646/115046415-68cd2780-9ea5-11eb-9d96-8a896a07dbd3.png)

**Comment by photopea** [comment]
I am very sorry, there was an error on my side (and it was in Photopea for years). It is fixed now.

**Comment by dentistformyeye** [comment]
Thanks for the fix 👍
