### ISSUE TITLE
There should not be a single click when move/zoom canvas with 2 fingers

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3138]
**Touching canvas with 2 fingers and keeping the fingers on canvas and moving/pinching should only move/zoom canvas**

Now in Photopea, a single click is applied when touched canvas with 2 fingers. 
Moving/zooming canvas with 2 fingers, 
while brush tool is being selected, canvas will be painted;
while path tool is being selected, a anchor will be created;
while one of select tools is being selected and there's selection on canvas, the selection will be deselected. 
These are not expected. 

This video is showing what will happen if move/zoom canvas while brush tool is selected in Photopea. 
https://user-images.githubusercontent.com/79258245/115104608-377b5700-9f8c-11eb-921f-4fde8edbaed6.mp4

Photopea might not be able to know that people are going to move/zoom canvas. Because touching canvas with 2 fingers absolutely at the the same moment is unlikely possible. There might be a time interval of tens of milliseconds between first finger touching and second finger touching. 

**Drawing APPs like Medibang, Sketchbook etc. have solved this problem**

For example, I zoom/move canvas with 2 fingers in Medibang. 
When my first finger touched, canvas were painted because the app hadn't known I was going to move/zoom canvas.But when my second finger touched within a very short time interval, the app had understood that I was going to move/zoom canvas. And the black point painted with my first finger was disappeared because the app had known that i wasn't going to paint anything but move/zoom canvas. 

Here's a video showing how Medibang worked when I moved/zoomed canvas. 
https://user-images.githubusercontent.com/79258245/115060353-593bf600-9f1a-11eb-9288-51e86f4ffdc1.mp4

**All in all, I think there shouldn't be a single click when there's second finger touched within a short time interval after the first finger touched**

It will be very, very nice that this problem is fixed !

**Comment by photopea** [comment]
I think I have fixed it. Let me know if it works as expected.

**Comment by nothingshiru** [comment]
There are some problems with some of tools when zooming/moving canvas with fingers. 

**Paint Bucket Tool**
image will be filled with color after all fingers released. 

**Eyedropper Tool**
The color under the finger that touched first will be sampled when that finger touched. 

**Ruler**
Existing ruler will be cleared. 

**Pen Tool with shape mode**

**Rectangle, Ellipse, Object select**

**In transform**

**Comment by photopea** [comment]
I think I fixed all these problems.

**Comment by nothingshiru** [comment]
With these windows opened, the image would be sampled

1. Levels
2. Curves
3. Hue/Saturaion
4. Color Range

**Comment by nothingshiru** [comment]
Hi. Did you see my reply above? Could they be fixed?

**Comment by photopea** [comment]
It is hard to fix. Do not zoom with two fingers, when a window is opened.
