### ISSUE TITLE
Perspective Transform

### ISSUE THREAD

**Issue by Evinawer** [photopea/photopea#314]
Hello, First of all, congratulations for the great job you have done here!

Second, in your Learn guide you write that thre is a Perspective Transform, but I can't find it in the menus, neither using a key while the Free Transform...

**Comment by photopea** [comment]
Hi, the Free Transform and Perspective transform are in one tool: Edit - Free Transform.  To do Perspective transform, hold Ctrl and drag corners of the rectangle. If it does not work, do any other shortcuts with Ctrl work?

** Perspective and Warp transform are not possible on Text layers.

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by Evinawer** [comment]
They answered already to the request, I had no need to write more details.
Sorry if I haven't say "Thank you", it just, I have read it now.

2017-11-13 17:30 GMT+01:00 Photopea <notifications@github.com>:
