### ISSUE TITLE
Script: Import image as a layer into another open image

### ISSUE THREAD

**Issue by mprinc** [photopea/photopea#3140]
Hi, 

I wonder is there a way to use script support to "inject" an image (with URL) into a separate (existing, preset and positioned) layer of an already opened image.

The idea is that we have a template and we want programmatically inject the image of a person, participant, into it

If that is not possible, we might be also happy with [JSON configuration object](https://www.photopea.com/api/) to pass both template and person image, but I do not envision how we would be then able to merge both of them into a single one (person image on the top of the template at particular position)

**Comment by photopea** [comment]
It should be possible to do using a script. You can e.g. find a solution for Adobe Photoshop and run it in Photopea.

I wrote a related article some time ago: https://www.photopea.com/tuts/edit-smart-objects-with-a-script/

**Comment by mprinc** [comment]
Thanks @photopea,

Yes, we are familiar and comfortable with scripts and use them very much both with Adobe (Photoshop and Illustrator) but also with Photopea.

The challenge we have is: how to programmatically (through script) load (into an existing Photopea document) a new remote image and add it into a specific layer of the existing document.

**Comment by photopea** [comment]
You can send it to Photopea iFrame through postMessage - https://www.photopea.com/api/live

Or you can run a script

    app.open("... url of a photo ...");

**Comment by mprinc** [comment]
Thanks a lot! I am aware of it, but was not sure how on the `postMessage` I can get an image from ArrayBuffer into a layer ...

**Comment by photopea** [comment]
It is all described in my link. There are demos, too.
