### ISSUE TITLE
Feature request: Keyboard shortcut for closing the current project

### ISSUE THREAD

**Issue by signalp** [photopea/photopea#3141]
I do it quite a bit while importing pics from a device and doing some cropping before saving to my computer, 

most other things I use are keyboard shortcuts (exporting, new project, cut/paste) but in order to close I have to get back to the mouse just to locate the closing "X" and click it after I'm done and before creating a new one from a clipboard-paste.

Would be great to have it! thank you

**Comment by avagp** [comment]
Maybe Ctrl+W will be good?  :)

**Comment by photopea** [comment]
@tomayac Is there a way for a website to detect Ctrl+T, Ctrl+N and Ctrl+W shortcuts in Chrome?

I see you created a Keyboard Lock API, but why do you allow it only in fullscreen? It makes no sense to me.

Could you create a single permission - "good website permission", which unlocks the permissions for the Keyboard, Clipboard,  webcam and microphone, etc? 

It feels like you are using the PWA installation as an analogy to giving all permissions. But many people fully trust a website, but still dont want it to keep any "track" (icon, bookmark ...) in their device.

**Comment by tomayac** [comment]
There is some discussion around registering keyboard combinations going on in https://crbug.com/1178625 and https://crbug.com/904479. You are probably subscribed to both bugs (or even taking part in the discussion).

The "good website permission" discussion is partly happening in the [MSEdgeExplainers/InstallTimePermissionsPrompt repo](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/InstallTimePermissionsPrompt/Explainer.md), but as you say, this is gated around installation. Maybe you can chime in and make your voice heard regarding how this would be useful for not installed experiences.
