### ISSUE TITLE
Cannot select all vectors

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3142]
when i select a bunch of folders, the last one is not selected (for vector editing)
Here is the PSD and a video :)
[Archive (1).zip](https://github.com/photopea/photopea/files/6329536/Archive.1.zip)

**Comment by photopea** [comment]
I don't know what to do, because these things in Photopea work 100% the same as in Photoshop :(

In Photoshop, if you want to move a layer, it is enough to select a parent folder. But if you want to activate a shape layer, you need to select that layer (not just the parent folder).

So, unfold the last folder (at the bottom) and select the layers inside it, too.

**Comment by avagp** [comment]
I get it.

But i have read a lot of problems in Photoshop, that are still not ironed out, and you have the opportunity to make something better.

I remember when Google Drive came out. For a couple of years its goal was to be as similar as possible to MS Office.

But at some point they pivoted towards giving what MS Office could not give, and all new features came up, and now many people prefer it over MS Office.

So, are you willing to copy everything Photoshop has, even what you think could be better?

I want to know what to expect

**Comment by avagp** [comment]
Sorry if it sounds rude Ivan. I am not mad or anything.

:)

Cheers

**Comment by avagp** [comment]
Photoshop have imperfection.
I know you want to be as similar as you can to it, but maybe improving/tweaking some features on the process can be a good opportunity to get a better use experience.

At least, i believe this particular behavior is counter intuitive, it should select all the shapes even the ones on the last folder. What do you think Ivan?

**Comment by photopea** [comment]
I think Photoshop did it on purpose. When you select a folder of layers, showing all blue contours of all vector shapes inside the folder would look too confusing. Many people would be surprised about what does it mean, how to get rid of blue contours.

Also, if you select a folder with shapes with different fill, it is not clear which fill should be at the top panel of a vector tool.
