### ISSUE TITLE
Speichern PSD im Web

### ISSUE THREAD

**Issue by Rotstift9** [photopea/photopea#3143]
Bei der Speicherung als PSD im Web für 6 Monate erhalte ich keine URL. Es hat aber schon mal geklappt. Was könnte falsch sein? Betrifft Firefox und Google Chrome.

**Comment by photopea** [comment]
I do not understand. Could you write it in English?

**Comment by sebastianvitterso** [comment]
_Google Translate:_ 

> When I save it as a PSD on the web for 6 months, I don't get a URL. But it worked before. What could be wrong? Affects Firefox and Google Chrome.

**Comment by photopea** [comment]
I think Popup windows are blocked by your browser. Or some browser extension is blocking our server. Try to disable all browser extensions.

**Comment by photopea** [comment]
I have to close it because of lack of details.
