### ISSUE TITLE
Navigator zoom uses a weird scale (0-21)

### ISSUE THREAD

**Issue by Baegus** [photopea/photopea#3144]
The zoom value in navigator goes from 0 to 21 (where 12 is actually 100%), which is kind of strange. Perhaps it would be less confusing if it was coverted to a percentage instead.

**Comment by photopea** [comment]
But how large should be 100% ?

**Comment by Baegus** [comment]
> But how large should be 100% ?

Not sure if I understand the question.
In Photoshop, the scale is represented by percentage and goes from 0.33% to 12800%, where 100% is right in the middle and (obviously) represents the original size of the document (much like _12_ in Photopea). I just think it would make more sense to represent the zoom with percentage instead of integers.

**Comment by photopea** [comment]
I fixed it :) The slider uses percentages now.

**Comment by Baegus** [comment]
Awesome!
