### ISSUE TITLE
Export to PDF - layer style is not correctly render

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3145]
It should be like this:
![Screenshot 2021-04-17 19 53 54](https://user-images.githubusercontent.com/11801254/115129732-b2f1fe00-9fb6-11eb-8cee-117212aeb57e.png)

But i exports like this:
![Screenshot 2021-04-17 19 53 59](https://user-images.githubusercontent.com/11801254/115129740-b8e7df00-9fb6-11eb-9a19-7f4d40a3cb3f.png)

Here is the PSD:
[bug.zip](https://github.com/photopea/photopea/files/6330261/bug.zip)

**Comment by avagp** [comment]
i figured out.

When outer glow effect is selected, photopea creates a bitmap shadow under the entire shape, but not solely it perimeter (like inner glow does).

So when a non-filled shape has outer glow, it shows all the bitmap underneath

here is a sample PSD:
[outer glow (1).zip](https://github.com/photopea/photopea/files/6330300/outer.glow.1.zip)

**Comment by avagp** [comment]
can that be changed, and work similar to inner glow? (which leave a blank space inside the shape?

**Comment by photopea** [comment]
It should be fixed now :)
