### ISSUE TITLE
Feature Request: Scale and Offset in Apply Image

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3148]
These options are important for Frequency Separation. 

![screenshot_20210418_233214](https://user-images.githubusercontent.com/79258245/115151301-dabc9100-a09e-11eb-8986-8d0d8f42cdb0.jpg)
 
**What do the options do?**
The result after blended by Blend Mode will be divided by the value of Scale then plus the value of Offset. 

For example, there is a layer A filled with (RGB 200, 200, 200), and a layer B filled with (RGB 100, 100, 100). 
I use Apply Image on layer A, and choose layer B in the Apply Image window. The Blend Mode is subtract, scale is 2, offset is 128. 
The result will be (200 - 100) ÷2 + 128 = 178

**Comment by MichalSZZ** [comment]
Yes. It is a great method for retouching the face. In photopea i have to use different method for that, but Frequency Separation is more universal and powerfull.
Can you add this feature?

**Comment by photopea** [comment]
Hi, I added this feature.

**Comment by MichalSZZ** [comment]
@photopea  I think it doesn't work for Frequency Separation method like this https://youtu.be/dBqhAIoQkdU?t=56 can you watch the video (change the speed to 1.5 ;) ) and try it yourself?

**Comment by photopea** [comment]
Sorry, it should be fixed now :) thanks!

**Comment by MichalSZZ** [comment]
I think that it works good now. Thanks
![obraz](https://user-images.githubusercontent.com/38118273/115522680-9db5f180-a28c-11eb-8e5d-1be27e1b9ab2.png)

**Comment by MichalSZZ** [comment]
![obraz](https://user-images.githubusercontent.com/38118273/115523625-8cb9b000-a28d-11eb-9310-1ad59d639cf6.png)

**Comment by MichalSZZ** [comment]
This is the result of the Frequency Separation method only (before any other retouch techniques). I think now it works correct (before - in the step "Apply image" with Subtract was only grey layer as a result). Thanks a lot!
