### ISSUE TITLE
[help wanted] make a selection from text (tattoo)

### ISSUE THREAD

**Issue by nathgit** [photopea/photopea#3149]
Is it possible to take a picture of a tattoo (hebrew text) & make a selection from it?

Here is the PSD. I included a text layer of what the tattoo says.

**Comment by MichalSZZ** [comment]
Yes. It is possible. But I think that Github is not the best place for asking for help. In this place user should add task with bugs or features to implement.

Try to use Reddit instead.

**Comment by nathgit** [comment]
@MichalSZZ I don't have a reddit account for security reasons. suppose I _could_ create one for that. It's just that they have had a lot security issues, user data leaks etc;

**Comment by photopea** [comment]
You mention a PSD, but I can not see any PSD. If you want to select something from an image, you can use the Magic Wand tool. If you want to create a tattoo containing your text, type it with the Type tool.
