### ISSUE TITLE
Magnetic Lasso Failing to work/crashing

### ISSUE THREAD

**Issue by MrSirSquishy** [photopea/photopea#3150]
I use Photopea on Google Chrome and the Magnetic Lasso does not work, I've used the lasso before but as time went on it got more broken, and now it refuses to function, I select it and when I try and use it, my computer hits a major lag spike, freezing up everything and sometimes crashing chrome.

**Comment by photopea** [comment]
Hi, could you try these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
