### ISSUE TITLE
Issue: The step “Move” in history panel appear only once

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3154]
No matter how many times I've moved the layer, there is only one step about "Move". 

https://user-images.githubusercontent.com/79258245/115285804-e41e2a00-a180-11eb-949f-ca1287c1862a.mp4

**Comment by nothingshiru** [comment]
I noticed that moving layer by move tool is different from free transform. I'm not sure if this is an issue. I'll try it in Photoshop later. I'll close this if it isn't an issue.

**Comment by photopea** [comment]
If you move the same layer many times, we think it is better to keep it as one step in history (that moves from the original and the final position, all positions in between are lost).

It is the same for changing the opacity of the same layer. Only the original and the final opacity are tracked in History.
