### ISSUE TITLE
Issue: Values in Hue/Saturation are not independent when Colorize turning on/off

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3155]
The values in current page of Hue/Saturation wasn't changed when turn on Colorize. And they wasn't changed when turn off Colorize. 

Fro example, I have adjusted the values of yellow range, then turn on Colorize, there would be the same values in Colorize mode. And then turn it off, the range became master and there were the same values. 

So there's only yellow adjusted before, there would be master and yellow adjusted after, and they have the same values. 

Values in Colorized On/Off should be independent.

**Comment by photopea** [comment]
I think I have fixed it.
