### ISSUE TITLE
Feature Request: Add "Right Click" in virtual keys in toolbar

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3158]
Is it possible?

**Comment by avagp** [comment]
just to know, are you using a chromebook?

**Comment by nothingshiru** [comment]
> just to know, are you using a chromebook?

No. Why are you asking me that?

**Comment by avagp** [comment]
because in chromebooks it has a problem with right clic

**Comment by photopea** [comment]
Now, you can do a long-tap on a touchscreen to show a context menu.

Except of the Layers panel (and other draggablel elements), where a long-tap will start drag-and-dropping an element.

The "Virtual keys" was supposed to be a temporary solution, until we come up with better solutions for devices without a keyboard.
