### ISSUE TITLE
Need a time label to comfirm if Photopea is updated

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3159]
There were several times you said the issues was fixed. But I didn't see the issues fixed until I tried again a few hours later even though I had refreshed my browser. 

A time label(GMT) of update time would be helpful to comfirm if i'm using newest version. You can put it in top menu "More".

**Comment by photopea** [comment]
Our JS files have the caching of one hour.

If you want to load the latest version of a website in Google Chrome (and ignore the cached version), press Shift+F5, or use the Incognito mode.
