### ISSUE TITLE
Polygonal Lasso Doesn't Work

### ISSUE THREAD

**Issue by warchou01** [photopea/photopea#3160]
Like in the title, **polygonal lasso** doesn't work. What is interesting the lasso or magnetic lasso work as usual.

I tried windows 10 app and in a tab of chrome browser.

**Comment by richardgoslingAOS** [comment]
We too are experiencing this, seems like it is either really slow and then eventually times out the page so you can no longer edit.

**Comment by photopea** [comment]
I am very sorry, it is fixed now.

**Comment by warchou01** [comment]
unfortunatelly the problem still exists.

**Comment by richardgoslingAOS** [comment]
Thanks, @photopea confirmed. I clear my browser cache before the change took.

**Comment by warchou01** [comment]
OK! I cleared cache too, it works now!

thanks @photopea and @richardgoslingAOS  

have a good day :)
