### ISSUE TITLE
Issue: app.activeDocument.source gives a typError if there is no activeDocument

### ISSUE THREAD

**Issue by EnricoKestenholz** [photopea/photopea#3162]
I was trying to check the document that was active using a liveMessage 

`app.echoToOE(app.activeDocument.source)`

If the user closes the only active document it will give a typerror and it will not post the message. 

Unfortunately I wasn't able to find  an alternative command to check if there are activeDocuments before calling for the source.

**Comment by photopea** [comment]
You can e.g. try `app.documents.length!=0` , see here: https://www.adobe.com/content/dam/acom/en/devnet/photoshop/pdfs/photoshop-cc-javascript-ref-2019.pdf
