### ISSUE TITLE
Corner radius dialog box - can't close

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3167]
![obraz](https://user-images.githubusercontent.com/38118273/115526931-d5269d00-a290-11eb-9774-727aaed4016e.png)
the first error in console is when I try to click OK
second one appear when I try to close window by X

before that I have selected all corners by the direct selection tool (as I remember)

`pp.js:5912 Uncaught TypeError: Cannot read property 'add' of null
    at p.I$.adJ (pp.js:5912)
    at e_.Zg (pp.js:10386)
    at e_.mB (pp.js:10385)
    at aJ.eV.f (pp.js:9)
    at aJ.a5.f (pp.js:8589)
    at aJ.fw (pp.js:8773)
p.I$.adJ @ pp.js:5912
e_.Zg @ pp.js:10386
e_.mB @ pp.js:10385
eV.f @ pp.js:9
a5.f @ pp.js:8589
aJ.fw @ pp.js:8773
pp.js:5913 Uncaught TypeError: Cannot read property 'clone' of null
    at p.I$.adJ (pp.js:5913)
    at e_.Zg (pp.js:10386)
    at e_.UW (pp.js:10385)
    at e_.eV.f (pp.js:9)
    at e_.a5.f (pp.js:8589)
    at e_.bI.aqE (pp.js:9825)`

**Comment by photopea** [comment]
I can not reproduce it :( could you share a PSD or some other steps?

**Comment by MichalSZZ** [comment]
I will try. I does happened to me second time just now. I have to see what steps I am doing.

**Comment by MichalSZZ** [comment]
Ok - Open this file:
https://www.photopea.com/#ig2gsbLL9

- select some sharp corners with shift (not all of them) using direct select tool 
- use corner radius button on toolbar and make some radius (dont click OK or nothing else in that window)
- select another sharp corner without closing corner radius window
- try change radius and close or accept

I don't know if that was steps in my first time with this bug - but now these steps works to reproduce issue

**Comment by photopea** [comment]
You are not supposed to select new corners while the window is opened :/ 

Now, the Corner Radius window will lock the document.

**Comment by MichalSZZ** [comment]
> 
> 
> You are not supposed to select new corners while the window is opened :/
> 

If user don't know about limitation - he will probably break the rules supposed by the creator of software :D
For that reasons in software companies there are a lot of testers :)

thanx a lot!

**Comment by photopea** [comment]
@MichalSZZ you are my tester, thank you very much for doing all this :)
