### ISSUE TITLE
Feature Request: Delete Path/Anchor in right-click menu

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3169]
With Pen /Free Pen/Path Select/Direct select tool selected, 

show Delete Anchor in right-click menu for delete the anchor clicked only when right click on a anchor;
always show Delete Path in right-click menu for delete the paths which are selected when right click on wherever as long as click inside canvas. Path is selected even there's only one anchor of it actually selected.

**Comment by photopea** [comment]
I have added these options to the right-click menu.
