### ISSUE TITLE
undo Disable Layer Effects problem

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#317]
open pea.psd demo file
open "Blending options" of layer "pea"
check checkbox "Drop Shadow" (Drop Shadow appears in Layers window)
click eye next to Drop Shadow in Layers window (Disable Layer Effects appears in history)
change opacity in "Layer Style" pop-up and click OK (Layer Style appears in history)
undo last step in history - Layer Style (Drop Shadow disappers from Layers window)
try to undo last step in history - Disable Layer Effects 
->
TypeError: A.add.lmfx[u.vq[F[0]]].v[F[1]] is undefined

**Comment by photopea** [comment]
So the "earlier" problem is, that when you open a Layer Style window and change something in the Layers panel (e.g. Opacity), it is remains the same in the Layer Style window.

The solution could be to forbid all non-window actions, when some window is open. I think it works the same way in Photoshop. Do you agree?

**Comment by hxim** [comment]
Yes I agree

**Comment by photopea** [comment]
It was fixed. When some windows is opened, controls outside this window should not work.
