### ISSUE TITLE
The export to SVG is wrong size

### ISSUE THREAD

**Issue by nissimzur** [photopea/photopea#3170]
The PSD export to SVG result in wrong SVG size. 
For example : retange of 200mm X 200mm when export to SVG. The SVG file show as 150mm X 150mm

**Comment by photopea** [comment]
Hi, how do you know that your SVG file is 150 x 150 mm? How do you measure the size of a SVG file in millimeters?

**Comment by photopea** [comment]
I have to close it because of lack of details.
