### ISSUE TITLE
Issue: When Deleted path of a shape layer, there's a blank shape layer left

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3171]
Path is deleted by pressing Delete key or option in right-click menu after selected the path.

**Comment by photopea** [comment]
That is correct, people often want to delete a current path and draw a new one into the same layer.

You can press Delete again, to delete a whole layer.

**Comment by nothingshiru** [comment]
But when draw a new path, there will be a new shape layer, and the blank shape layer is still there below the new shape layer.

**Comment by photopea** [comment]
You should draw with the "Path" mode into existing layers. A "Shape" mode always creates a new layer.
