### ISSUE TITLE
Applied layer effect to folder, doesn't apply to all shapes inside it

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3172]
Here is a video:

[WhatsApp Video 2021-04-22 at 20.26.zip](https://github.com/photopea/photopea/files/6361920/WhatsApp.Video.2021-04-22.at.20.26.zip)

**Comment by photopea** [comment]
This works absolutely the same in Photopea as in Adobe Photoshop.

Applying a style to a folder is not the same, as applying that style to each layer. A style on a folder is like merging all layers into one, and applying a style to that one layer.

The same goes with the Opacity. Changing the Opacity of a folder is not the same as changing the opacity of each layer.

**Comment by photopea** [comment]
Look at this demo about the Opacity, where one image covers another :)

https://www.photopea.com/#iHRbakedR

**Comment by avagp** [comment]
Perfect!!

Great example :)
