### ISSUE TITLE
Inappropriate ads for school kids

### ISSUE THREAD

**Issue by MrVanKurin** [photopea/photopea#3177]
I am a middle school teacher, and we are able to teach our students photo editing on their chrome books because you offer this amazing free software.  Unfortunately, we may need to stop using it because the ads are often inappropriate.   Especially the adds that have women wearing risque outfits, or hardly any clothes at all.  I understand you make money from ads, so I understand you  need them.  I also understand ad blockers will hurt your ability to get revenue.  Is it possible to have a compromise and only support adds that will not toxify the classroom environment?

**Comment by photopea** [comment]
Are you using any browser extensions, which are allowed to modify websites?

We had such reports in the past, and always, it was a browser extension inserting inappropriate ads into Photopea.

**Comment by MrVanKurin** [comment]
Our district has all extensions and add-ons locked down.  Any extensions we have are strictly educational and are added outside of teacher control.

Thank you,

Scott VanKurin
Technology Education Teacher
C.P. Weber Middle School
Port Washington School District
________________________________
From: Photopea ***@***.***>
Sent: Friday, April 23, 2021 2:23 PM
To: photopea/photopea ***@***.***>
Cc: Scott VanKurin ***@***.***>; Author ***@***.***>
Subject: [External Sender] Re: [photopea/photopea] Inappropriate ads for school kids (#3177)


CAUTION: This email originated from outside of our organization! Do not click links, open attachments or reply, unless you recognize the sender's email address and know the content is safe!

Are you using any browser extensions, which are allowed to modify websites?

We had such reports in the past, and always, it was a browser extension inserting inappropriate ads into Photopea.

**Comment by photopea** [comment]
I still think you are using extensions, which insert inappropriate ads into websites. There is nothing Photopea can do about it.

I don't know what educational value you see in an extension, which inserts inapropriate ads.

**Comment by MrVanKurin** [comment]
There are no extensions adding ads.  The only place I get inappropriate ads is on Photopea.

Thank you,

Scott VanKurin
Technology Education Teacher
C.P. Weber Middle School
Port Washington School District
________________________________
From: Photopea ***@***.***>
Sent: Monday, April 26, 2021 8:37 AM
To: photopea/photopea ***@***.***>
Cc: Scott VanKurin ***@***.***>; Author ***@***.***>
Subject: [External Sender] Re: [photopea/photopea] Inappropriate ads for school kids (#3177)


CAUTION: This email originated from outside of our organization! Do not click links, open attachments or reply, unless you recognize the sender's email address and know the content is safe!

I still think you are using extensions, which insert inappropriate ads into websites. There is nothing Photopea can do about it.

I don't know what educational value you see in an extension, which inserts inapropriate ads.

**Comment by photopea** [comment]
We had cases in the past, when a school used extensions, which inserted inappropriate ads into Photopea.

I would need some proof from you. E.g. a screenshot, which shows an inappropriate ad in Photopea.com, while all browser extensions are disabled.
