### ISSUE TITLE
site won't open large files

### ISSUE THREAD

**Issue by maddicaddis** [photopea/photopea#3178]
This is so frustrating. I tried opening a 37.2mb size PSD file on photopea but the site kept crashing. I can't load any of my larger files but i can't afford photoshop and I don't have the space to put GIMP on my chromebook. Does anyone know what's happening?

**Comment by photopea** [comment]
That is really strange. Could you send us your PSD to support@photopea.com ?

**Comment by photopea** [comment]
The problem was, that a PSD cotnainted sixty layers 3000x2000 pixels, and each layer had a Stroke + Bevel and Emboss.

Photopea needs 90 seconds to render all layer styles in this case, and a browser closes it, as it thinks it is stuck.
