### ISSUE TITLE
Paste error

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#3179]
When I  paste image to photopea with CTRL+V I copied before from browser (via context menu) it always shows some error - image is still pasted correctly it seems:

1.
![image](https://user-images.githubusercontent.com/6370548/115952190-e8ca4180-a4e4-11eb-87fd-5ecc478301aa.png)

2.
![image](https://user-images.githubusercontent.com/6370548/115952244-229b4800-a4e5-11eb-9710-62fd9c71ef11.png)

**Comment by photopea** [comment]
it should be fixed now.
