### ISSUE TITLE
Problem with double click on rulers

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#3180]
I had text layer under ruler like this:
![image](https://user-images.githubusercontent.com/6370548/115952986-55473f80-a4e9-11eb-8867-a14bd4a7e6ca.png)
Then I double clicked with Move Tool selected on ruler so text layer was under the ruler. (Type Tool is selected automatically)
![image](https://user-images.githubusercontent.com/6370548/115953040-95a6bd80-a4e9-11eb-83ad-60804a7c7b9e.png)
Then I double clicked again
![image](https://user-images.githubusercontent.com/6370548/115953072-b66f1300-a4e9-11eb-99b1-969f0d5f048f.png)
It exited Type Tool and went back to Move Tool but the boxes and lines around text keeps on screen
![image](https://user-images.githubusercontent.com/6370548/115953127-e4545780-a4e9-11eb-8691-03e23b721e7f.png)
Now when I use other tools and switch layers it does not remove the boxes a lines and black color from text selection stays where text was before as seen on screenshot

**Comment by photopea** [comment]
It should be fixed  now.
