### ISSUE TITLE
Set "Pressure Detection Off" as default

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3182]
On touchscreen devices, size of brush would be affected by touch area. It's difficult to control touch area precisely with finger. This function may not be suitable for touchscreen devices. 

And size of brush is not only affected when selected brush tool. It's also affected when selected healing brush tool, stamp clone tool, blur tool etc. 
But the options of pressure detection are only visible when selected brush tool, pencil tool, eraser tool. 
With other tools selected, to avoid the effects of pressure detection, we have to select brush tool etc. to turn the options off first. This is inconvenient. 
![screenshot_20210426_161142](https://user-images.githubusercontent.com/79258245/116050506-23310b80-a6aa-11eb-9317-10a173eeaccd.jpg)

**Comment by photopea** [comment]
Ok, I set it to Off for all tools by default.
