### ISSUE TITLE
Half pixel in bottom right on android

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#3184]
On my android tablet (Samsung S5e) with Chrome browser if I zoom in to bottom right corner of any image it shows image is 0.5 pixel too large. (color from bottom and right line of pixels is repeated) See on screenshot how pea.psd image ends on 512.5 coordinates instead of 512.0.
![obrazek](https://user-images.githubusercontent.com/6370548/116033075-10461900-a661-11eb-8725-81c7741df35b.png)
On PC it renders pixels correctly for me.

**Comment by photopea** [comment]
I think it is because the WebGL on your device makes calculations with 16-bit floats. As the technology improves, all devices will switch to 32-bit floats and these errors will disappear.

Try to update your web browser, or your OS, or disable WebGL.
