### ISSUE TITLE
Issue: "Close the current window first" pops up when adjusted layer style of gradient/pattern layer

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3185]
When drag sliders, change values etc. the message pops up. 
![Screenshot_20210426_235419](https://user-images.githubusercontent.com/79258245/116113932-84c59a00-a6eb-11eb-8b6c-ac574d9cf963.jpg)

**Comment by photopea** [comment]
Fixed, thanks for reporting :)
