### ISSUE TITLE
Issue: The full name of some fonts can't be seen

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3188]
![Screenshot_20210427_172821](https://user-images.githubusercontent.com/79258245/116219801-9b690100-a77e-11eb-9c25-313d2032fd3a.jpg)

**Comment by photopea** [comment]
A font name and a font preview should be on one line (if a screen size allows it).

I removed the padding, it should fit on one line now.

Normally, if you hover over a font name with a mouse, a full font name should appear. But I don't know how to solve it for mobile devices :(

**Comment by nothingshiru** [comment]
How about a button for hiding fonts preview?

**Comment by photopea** [comment]
I am afraid of having too many buttons, too many switches. So we have a solution only for people with a mouse - the full name is displayed after hovering a mouse over the font name.
