### ISSUE TITLE
More Rams

### ISSUE THREAD

**Issue by lol123-0** [photopea/photopea#3189]
it is saying that I dont have enough rams even tho I have a 8gb Ram laptop. It won't let me use the Magic Wand

**Comment by photopea** [comment]
How large is your photo (width and height in pixels) ? 8GB might not b enough for some operations, especially if you have too many programs already opened on your computer.

But first, make sure that your web browser is updated (it could be an issue of a browser).

**Comment by photopea** [comment]
I have to close it because of lack of details.
