### ISSUE TITLE
Spanish Characters

### ISSUE THREAD

**Issue by Dipareja** [photopea/photopea#319]
I'm trying to add a text in Spanish in a psd file and I can't use any character with accents, like á, é, í, ó or ú that are common in Spanish. I already tried selecting only Latin-1 Fonts, and any of those include characters with accents. Please help!!

**Comment by photopea** [comment]
Hi, the default font DejaVu Sans should allow you typing these characters. All Latin-1 fonts also should work. What do you see instead? Can you send us a screenshot?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
