### ISSUE TITLE
Feature Request: "Ignore White" in Vectorize Bitmap options

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3190]
It will be a nice feature to add - "Ignore White" like in the Illustrator trace options (see below)

![obraz](https://user-images.githubusercontent.com/38118273/116323577-9af05a80-a7be-11eb-92cd-6a745f4de671.png)

It is a great thing for those people who scan their paper drawings and want to have black artwork without the white background (in Photopea now there are many unnecessary layers after the vectorize).

Or maybe better? You can name that feature - "Ignore Background" and the user will have an option to set a background color (color picker will be appear - to type in or pick up color from the project). As the default for the preview (after check this option) it can be set to white.

**Comment by photopea** [comment]
I think we could do that. But why don't you remove white pixels with Magic Wand, before vectorizing? :)

**Comment by MichalSZZ** [comment]
Yes. I can. It is just a simplest way to do that in Illustrator.
Monochrome 2 color image was only an example. In Illustrator you can can use colorful image just from scanner and do nothing with it before tracing. Algorithm use some methods for simplifying the image and know what is background and what is artwork.
 
It is a great option for user without special knowledge about program.

You can add this in your "free time" ;) it is not necessary for me. I know how to prepare image for vectorizing (levels, threshold, filters etc)

**Comment by photopea** [comment]
I am still not sure about this :( We would have to add a parameter for a color to remove (all vector shapes with that color would be removed from the output). But sometimes, you want to keep some white parts, while removing others.

I would prefer if users do this before or after the vectorization, and the vectorization works exactly with the colors it receives at the input.

**Comment by MichalSZZ** [comment]
The tool should to by user friendly as much as can it be :)

Maybe you could think about more "presets" like in Illustrator. You can set parameters best for that preset and ability of options for only few of them. For example - when user want black and white image without any other color, there can be option to check "ignore white". In other presets some inputs can be different or disabled.

That tool you can improve without compatibility with Photoshop because that is your feature and does not affect on PSD structure.

But that is only my suggestions. Someone can use Photopea only for factorizing bitmaps. I know ppl who have great skills in photo manipulations and don't know nothing about shapes, paths etc.

**Comment by MichalSZZ** [comment]
@photopea - can we reopen this issue and talk about it again?

I answered on Reddit today https://www.reddit.com/r/photopea/comments/rcmlqd/how_to_replace_a_color/ 
this guy wants to change black letters to white.
![obraz](https://user-images.githubusercontent.com/38118273/145543940-9b54f4e8-e212-4b4a-88c1-a8bde2094034.png)
The graphic was so simple to vectorize it so I did it.
Photopea made magic and the shapes are really great. But when I wanted to delete background... the problems have started.
![obraz](https://user-images.githubusercontent.com/38118273/145544584-46f92307-15cd-4881-b1a9-1046d39cb29c.png)
deleting white shapes do nothing for user without skills
![obraz](https://user-images.githubusercontent.com/38118273/145544848-015a7211-beb8-476f-96eb-774a432ab731.png)
I know how to do it correctly (merging to one layers and making boolean operations) :) but this tool can have one click background remover for images like this. Illustrator has this option as I mentioned in posts above..

**Comment by photopea** [comment]
Why dont you remove white pixels first, and then, vectorize? Just use the Magic Wand, it takes 2 seconds.

**Comment by MichalSZZ** [comment]
@photopea you have absolutely right! My bad. I wanted to have functionality from Illustrator but I forgot, that illustrator haven't tools for selecting and removing background. I was thinking in 'illustrator way' about that.
Thank you - that was so simple.
