### ISSUE TITLE
The sample tools need to be able to be unselected

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3193]
![screenshot_20210429_212036](https://user-images.githubusercontent.com/79258245/116559310-e62b7a00-a932-11eb-9a26-5d6a2b63eb25.jpg)

The sample tools are now always selected when opened these windows. 

1. Levels
2. Curves
3. Hue/Saturation
4. Color range

With sample tool selected, image would be changed when moved/zoomed canvas with fingers or clicked on image with mouse by mistake. Then we have to reset and adjust again. 

We're not going to sample from image all the time. The sample tools need to be able to be unselected. And unselected is default.

**Comment by photopea** [comment]
I solved it for Levels and Curves (if you disable the sampling item). But it is too hard to solve for others :(
