### ISSUE TITLE
Saved or exported files are being downloaded as extension.txt

### ISSUE THREAD

**Issue by berithpy** [photopea/photopea#3194]
When I try to save or export a file its being saved as whatever format I pick `.txt`, for example if I save it as psd i get a `psd.txt` file
Here is an example gif of it happening
![photopeasavebug](https://user-images.githubusercontent.com/8316977/116622280-6ee5ee00-a912-11eb-91e8-baee2412cb0c.gif)

My current fix is just to rename the downloaded files as whatever.psd

**Comment by photopea** [comment]
Hi, could you disable all browser extensions and try it again?

**Comment by photopea** [comment]
I think disabling an extension solved it.
