### ISSUE TITLE
Cropping tool doesn't allow for cropping a single layer

### ISSUE THREAD

**Issue by codybeeber1** [photopea/photopea#3195]
I can not get the program to crop a single layer every time even when I select the "Current Layer" section on the crop tool.

**Comment by nothingshiru** [comment]
That's how crop tool works. 

To crop single layer, you should use rectangle select tool to select the area that you want, then inverse your selection and press delete key.

**Comment by photopea** [comment]
I recommend reading www.Photopea.com/learn to learn how Photopea works.
