### ISSUE TITLE
Editing Smartobject with Smartfilters bug.

### ISSUE THREAD

**Issue by FynniX** [photopea/photopea#3197]
Hello,
if I edit my Smartobject with Text Content in it and saving it then is the Smartobject not visible anymore. This is only happening if a Smartfilter is applied. In photoshop is no issue. Thats the reason why its visible at the start. I think the problem here has something to do with saving the Smartobject.

Test PSD:
[test.zip](https://github.com/photopea/photopea/files/6408121/test.zip)

1.
![image](https://user-images.githubusercontent.com/47634930/116755424-adf76a80-aa0a-11eb-9c50-7c5ced7026b7.png)

2.
Editing the text and saving
![image](https://user-images.githubusercontent.com/47634930/116755498-cc5d6600-aa0a-11eb-8a90-dbb65ee154d6.png)

3.
Now its not visible anymore
![image](https://user-images.githubusercontent.com/47634930/116755542-daab8200-aa0a-11eb-80b2-f61cc58e9353.png)

Greetings Fynn

**Comment by photopea** [comment]
If you have one black pixel, and you apply a gaussian blur on it, radius of 100 pixels, that one black pixel will disappear.

In your case, it is the Dust and Scratches filter. That filter makes your text disappear (try to enable and disable it), while in Photoshop, it probably does not do anything at all.

**Comment by FynniX** [comment]
Ok thanks
