### ISSUE TITLE
El orden de los pinceles no cambia

### ISSUE THREAD

**Issue by NOesjelly** [photopea/photopea#3199]
Hola, estuve tratando de seleccionar el color de una imagen (alt+click) y el color seleccionado pasa al pincel (color de goma) secundario, cuando uso el pincel secundario, y repito lo mismo... el color va al pincel (color de goma) primario... me es incomodo estar cambiando una y otra vez el color primario del secundario.
para empeorar la cosa no guarda los colores en las muestras y al combinarlos en "superposición de colores" solo aparece uno o dos colores de todos los que seleccione.
es decir, el color primario y segundario funcionan por separado, ya no como una unidad...
la el color de goma (borrador) es a donde se va todas las selecciones.
gracias.

**Comment by dentistformyeye** [comment]
@photopea I don't understand all of it, but I think part of it has to do with the fact that  alt-click with the brush tool now sets the background color, but it used to set the foreground color.
@NOesjelly For now, to sample the foreground color, you can press the i key to switch to the eyedropper and click normally. To switch back to the paintbrush, press the b key. To switch the order of the foreground color and background color, press the x key.

**Comment by photopea** [comment]
Oh, I see, it should be fixed now. @dentistformyeye thanks! :)
