### ISSUE TITLE
Feature Request: Support accessing layer comps through script

### ISSUE THREAD

**Issue by mcgard** [photopea/photopea#3200]
This would be a handy feature for when relying heavily on layer comps to make many multiple versions of the same base image with tweaks

PS Javascript example:
```
var layercomps = app.activeDocument.layerComps;

var pngOpts = new ExportOptionsSaveForWeb; 
pngOpts.format = SaveDocumentType.PNG
pngOpts.PNG8 = false; 
pngOpts.transparency = true; 
pngOpts.interlaced = true; 
pngOpts.quality = 100;

for (i=0; i<layercomps.length; i++) {
    layercomps[i].apply()
    var outDocName = "~/Desktop/" + layercomps[i].name + ".png"
    var pngFile = new File(outDocName);
    app.activeDocument.exportDocument(pngFile, ExportType.SAVEFORWEB,pngOpts)
}
```

**Comment by photopea** [comment]
I have implemented the missing parts, your script should work well in Photopea now :)

Note, that websites do not have a direct access to a hard drive. Your files will be offered to you to download in a ZIP archive.

**Comment by mcgard** [comment]
Amazing. Works like a dream. Thank you so much!
