### ISSUE TITLE
Need icons for adjustment layers and panels

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3201]
Sometimes it's not easy to distinguish them. 
![screenshot_20210503_003303](https://user-images.githubusercontent.com/79258245/116820755-2eec6880-aba9-11eb-9cc3-ab66eff67cdc.jpg)
![screenshot_20210503_004051](https://user-images.githubusercontent.com/79258245/116820759-30b62c00-aba9-11eb-8204-e7752f50ebe0.jpg)

**Comment by photopea** [comment]
I felt too lazy to come up with icons myself, so I decided to use the first three letters. Would you be able to create icons for Photopea?

**Comment by nothingshiru** [comment]
There's nothing I know about designing/creating icons. But it sounds interesting. If I create icons by vector tools in Photopea, will it work?

**Comment by photopea** [comment]
Sure. We need icons as PNG files, 160x160 pixels, black color on a transparent background. Like this: 

https://www.photopea.com/img/tools/pencil.png
https://www.photopea.com/img/tools/clone.png

**Comment by nothingshiru** [comment]
I have created some icons for adjustment layers. 
[Icons for adjustment layers.zip](https://github.com/photopea/photopea/files/6428897/Icons.for.adjustment.layers.zip)

**Comment by photopea** [comment]
Hey, that is very nice! 

Could you make the Levels icon look like a Histogram?

Can you make the Vibrance icon a triangle instead?

Can you make Color Balance "more elegant" somehow? 

Channel Mixer - could you make circles a bit smaller?

Photo Filter - Could you get rid of the radial gradient? Draw the gloss with a solid color somehow.

**Comment by photopea** [comment]
Some of your icons are "rectangular", but some are a "square". What if we made all of them square? the "Curves" icon looks unnatural and "squeezed", it could be a square, what do you think?

**Comment by nothingshiru** [comment]
I remade all of them. 
![图标 (2)](https://user-images.githubusercontent.com/79258245/117215181-759fc400-ae30-11eb-80a3-3ef05040a0f6.jpg)
[Icons.zip](https://github.com/photopea/photopea/files/6430491/Icons.zip)

**Comment by photopea** [comment]
Wow, these look amazing! Could you remake the Color Balance? Make it more like the old one.

Photo Filter - can you remove the dot in the middle, and make the short curve thicker and closer to the center?

**Comment by nothingshiru** [comment]
![Icons](https://user-images.githubusercontent.com/79258245/117218702-37a59e80-ae36-11eb-9a52-1806e1a0e7c6.jpg)
[Color lookup & Balance.zip](https://github.com/photopea/photopea/files/6430664/Color.lookup.Balance.zip)

**Comment by nothingshiru** [comment]
I changed the size of icons which don't have sqaure outside a little bit. 
![Icons (1) (1)](https://user-images.githubusercontent.com/79258245/117249288-ea482200-ae73-11eb-9548-b4e8875294f6.jpg)
[Icons new.zip](https://github.com/photopea/photopea/files/6432113/Icons.new.zip)

**Comment by photopea** [comment]
So I put your icons into Photopea. How do you like it? I think they look great, you did an amazing work! :)

Can you please write it here explicitly, that you allow me to use your icons in Photopea for free? :)

**Comment by nothingshiru** [comment]
Sure. The icons I put here are absolutely free for  Photopea.

**Comment by nothingshiru** [comment]
I see that you added square to the icons which didn't have it. Is it necessary?

**Comment by photopea** [comment]
every layer thumbnail has a border, it is an internal style

**Comment by nothingshiru** [comment]
Sorry, I forgot the replace color adjustment layer. 

![新建项目](https://user-images.githubusercontent.com/79258245/117562026-5a7cc080-b08b-11eb-88a1-788962f0d4fd.png)

**Comment by photopea** [comment]
Thanks a lot :) I also forgot, that we offer this adjustment layer.
