### ISSUE TITLE
Open File - Cannot open PDF properly

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3204]
I cannot open this pdf.

It does open though, but glitchy:
![image](https://user-images.githubusercontent.com/11801254/116943368-6dcdfd00-ac41-11eb-9d7e-e3e9a1e687f6.png)

Here is the doc:
[Doc_2021-05-03_14-08-12.pdf](https://github.com/photopea/photopea/files/6418232/Doc_2021-05-03_14-08-12.pdf)

**Comment by photopea** [comment]
fixed, thanks for reporting! :)
