### ISSUE TITLE
Cannot Copy Things

### ISSUE THREAD

**Issue by EddieIdek** [photopea/photopea#3205]
I've been trying to work on stuff and I tried doing Ctrl + A and Ctrl + C to copy but it just doesn't want to work and it's pretty frustrating. Can anyone help me please?

**Comment by photopea** [comment]
Hi, you probably refused to give Photopea clipboard permissions. Click on the Lock icon next to www.Photopea.com and give Photopea the clipboard permissions.

**Comment by photopea** [comment]
I think it was solved.
