### ISSUE TITLE
drag and drop stopped working.

### ISSUE THREAD

**Issue by howardemilya** [photopea/photopea#3206]
we used to be able to drag and drop an image file to the editor — this no longer works. only way to open a new image file is to go through the menu bar and file -> open -> then search through way too many files on my computer to figure out where the image is.

**Comment by avagp** [comment]
i can do it @howardemilya 

:/

Maybe close and open photopea?

**Comment by photopea** [comment]
It works for me too. Could you try these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/
