### ISSUE TITLE
Paths - Subtracted paths don't give the same effect

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3207]
I made the same shape (it is duplicated)
But one i changed to have a fill, and the other don't have any fill.

The left one subtracts the stroke perfectly, but the other don't.
![image](https://user-images.githubusercontent.com/11801254/117096829-28d8c200-ad38-11eb-9d8a-d52d4c79ed80.png)

Here is the file:
[image.zip](https://github.com/photopea/photopea/files/6425054/image.zip)

Unless it is something intended, both ways should work as the one on the left.

**Comment by photopea** [comment]
fixed, thanks for reporting! :)
