### ISSUE TITLE
Delete Anchor deselect your current shape

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3208]
I don't know if this is intended or not.

I have across a lot of thing that i believe are weird, but happen to be intended.

Well, when using the Pen tool and placing anchors. If you click with the tool to add an anchor, and then press Backspace, similar to the polygonal selection tool, you will delete the last anchor you added.

Then if you press again to add a new anchor, you will create a new path layer, instead of adding a new anchor the current shape. 

So, is this intended?
I believe it should work like the polygonal lasso, where backspace works like and Undo action.

**Comment by avagp** [comment]
Here is a video:
https://video.drift.com/v/abFSJr5ny6w/

**Comment by photopea** [comment]
This works the same in Photopea as in Adobe Photoshop and probably other programs. So I think it is better to keep it that way.

Use Alt+Ctrl+Z to do a step back, instead of the backspace.
