### ISSUE TITLE
I can't see a photo when I open a image or create a project in Photopea.

### ISSUE THREAD

**Issue by photopeauser1** [photopea/photopea#3213]
Almost everyday I use photopea. Before this issue happened, I can see the photo which I am editing, but now, it's the opposite. I couldn't see any photo at all when I open a image or create a project. How can I overcome this issue?
![Screenshot (24)](https://user-images.githubusercontent.com/83713434/117156795-0a9cb180-ad8c-11eb-9bd4-ca5d5be1b89b.png)

**Comment by photopea** [comment]
try to reload Photopea several times. We fixed it hours ago.
