### ISSUE TITLE
More Pen Tool Options

### ISSUE THREAD

**Issue by munirsafi** [photopea/photopea#3214]
Definitely a huge thank you first for such a fantastic tool! I love using it, but was wondering if it's possible to request a feature to have more control over how shapes are created.

In Photoshop, when using the pen tool to create a shape, you're able to define if that new shape should be drawn to a new layer, subtracted, or excluded. I see these options are available as paths, but not available as part of shape creation/drawing.

Here is an image of what I'm referring to:
![shape-options](https://user-images.githubusercontent.com/12715116/117212060-d21ac900-adc7-11eb-99c4-8c5bc2435173.gif)

(Left to right: Shape draws to new layer, Shape draws to current layer, Shape subtracts from current layer, Shape draws from intersection, and Shape excludes on overlap in current layer)

If this is possible already using the pen tool to draw a shape, please let me know how it'd be accessible. I feel like the functionalities are all there already, it just hasn't been added as available options (for the pen tool at least).

**Comment by photopea** [comment]
These options are available in Photopea for many years.

If you have just one shape, it makes no sense to set its boolean operation.

If you switch to the Path mode, you can choose the boolean operation for the second and next paths.

https://www.photopea.com/learn/vg-creating

**Comment by munirsafi** [comment]
Maybe I wasn't clear in my initial posting. I don't want to have just one shape. I want multiple shapes in one layer. Unfortunately, switching to path and selecting a different boolean operation does allow for multiple paths in one layer, but i removes the shapes.

The UX of the pen tool is quite confusing, I'm not sure how what I'm asking for can be achieved using the options that are available now.

**Comment by photopea** [comment]
Each vector tool has two modes: A shape mode (creating a new layer with a single shape), and a Path mode (adding new shapes to a current vector layer, with boolean operation). 

These things work the same in Photopea and Photoshop, but I think your Photoshop is 15 years old :/

**Comment by munirsafi** [comment]
I'm not sure how it works with Photoshop CC (I assume it works the same way), but In CS6 you're able to create new shapes into the currently selected shape layer.

Here is a link to what I'm referring to with a short video: 
http://pixelstreetstudios.com/photoshop/photoshop-cs6-topics/combining-shapes/

If this is impossible to do with Photopea, I'll end this conversation here as I don't want to take up more of your time. I appreciate you responding very quickly. Thank you.

**Comment by photopea** [comment]
It is possible to do, but I will remake it, so that it works more like Photoshop.

**Comment by munirsafi** [comment]
Thank you so much! I really do appreciate it, it really will help boost the vector design process of the pen tool on Photopea. Again, thank you for taking the time to discuss this and consider the feature additions.

**Comment by MichalSZZ** [comment]
That is a great feature but I usually make that in a different way in Photoshop (the fastest method)

In Photoshop when you are on shape layer, you can easily draw another shape on that layer with boolean operation by using a shortcuts (Shift - add, Alt - subtract, Shift+Alt - intersect).
![obraz](https://user-images.githubusercontent.com/38118273/117224302-e1256980-ae0f-11eb-8ed4-cd5d3f08c7eb.png)
The icon after button pressing change to that boolean method and the cursor have in that time + - x little sign.
It works like in selections with those shortcuts.

https://github.com/photopea/photopea/issues/1970 I wrote some time ago about that but now, when I read that, it is not so clearly what I have wanted there ;)

**Comment by munirsafi** [comment]
Hopefully we can get the addition of shortcuts too once the functionality has been implemented as well? @photopea if it's not too much extra to ask for.

**Comment by photopea** [comment]
Ok, I made it work like Photoshop.

The Binary Operation menu is present in both Path and Shape mode. In Shape mode, it has one extra value: New Layer.
