### ISSUE TITLE
Feature Request: Show handle of adjacent anchor on activated anchor side

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3216]
Sometimes a curve in path is affected by 2 curve anchor. Showing the handle of adjacent anchor on activated anchor side would be helpful to adjust the curve. 

I have made some images to show you what I think. 

When activated one anchor
![Screenshot_20210508_000657_com android chrome](https://user-images.githubusercontent.com/79258245/117481917-3c816400-af96-11eb-9b18-017b0b73d68f.jpg)

When activated two anchors
![Screenshot_20210508_000657_com android chrome (1)](https://user-images.githubusercontent.com/79258245/117481941-47d48f80-af96-11eb-9b2a-7bcad97135dd.jpg)

When dragged the handle of adjacent anchor, show the handle on the other side. But that anchor won't be a "Activated" anchor as the middle anchor is. So the handle of the anchor on far left won't be a adjacent anchor of which handle will be showed. 
![Screenshot_20210508_000657_com android chrome (2)](https://user-images.githubusercontent.com/79258245/117482679-4a83b480-af97-11eb-9907-9dc8aa02f2b1.jpg)

**Comment by photopea** [comment]
Is it about the Pen tool or some other tool? in Direct Select, you can select as many anchors as you want - see here https://www.photopea.com/learn/vg-manipulation . Handles of all selected anchors are displayed.

**Comment by nothingshiru** [comment]
It's about pen tool. 

Direct Select won't work satisfactorily when creating path. 

**Here are 2 reasons why I think so** 

1. When creating path, there are new activated/adjacent anchors that are impossible to be activated previously by Direct Select. 

2.  After activated anchors we want to adjust, to continue creating anchors in the same path, there would be one more step to do, that we have to select the anchor at the front of the path manually.

**Comment by MichalSZZ** [comment]
I think that he is talking about that

![obraz](https://user-images.githubusercontent.com/38118273/117801626-d4ac7100-b254-11eb-99a2-3ef3dd2a0c84.png)
(the middle point is selected - Photoshop view)

and that how it look in Photopea
![obraz](https://user-images.githubusercontent.com/38118273/117801848-08879680-b255-11eb-91c8-852e60cfbfb9.png)
also middle point is selected but I don't see other controllers of neighbor points (with curves lines - how long they are and in which direction they are - important information when you edit one point)

**Comment by nothingshiru** [comment]
No new tools are needed. My request is that display handles of anchors like Photoshop does. 

You can see how it looks like by using pen tool to create path or using direct select to select some anchors of path in Photoshop.

**Comment by MichalSZZ** [comment]
When you draw a new path with a Pen Tool, you can switch (for a moment) to Direct Selection Tool with a Ctrl key when you have to make a little changes in points that was added before.  And after corrections you can still add new points to the path again without ending the whole process of pen drawing.

Same thing you can do with Direct Selection Tool on any paths. 

In Photopea we don't see the neighbors handlers of the points

**Comment by photopea** [comment]
I see, it should be fixed now.
