### ISSUE TITLE
WHAT IS GOING ON.

### ISSUE THREAD

**Issue by BasicBroom** [photopea/photopea#3217]
IM FURIOUS! I SPENT 2 HOURS WORKING ON AN IMAGE and as SOON as I click on the image after liquifying it, IT REVERTS ALL ITS CHANGES FOR NO REASON. AND IT WON'T LET ME UNDO THAT CHANGE?????? The thing suddenly wants to zoom in for every time I try to move my mouse, AND IT'S JUST NOT WORKING AT ALL!

I've been using this program for 4 years now! Why is it all of a sudden doing this!

**Comment by photopea** [comment]
I can not replicate such behaviour. What should we do to make the problem happen on our computer?

Are you using Firefox and you pressed the Alt key? Firefox has a bug related to the Alt key. Never press the Alt key if you use Photopea in Firefox.
