### ISSUE TITLE
Unable to change shape color

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#322]
When I try to change color of shape it announces "Close the current window first" after I select different color and I am unable to change the actual color of shape in Properties window - option "Solid color fill".

**Comment by photopea** [comment]
That is the result of fixing this: https://github.com/photopea/photopea/issues/317

When you hit OK in the color picker, the action is performed while the window is still open. I fixed 317 without thinking too much ... So I undid it and 317 is still unfixed.

**Comment by photopea** [comment]
I fixed it again, so both this and 317 should be fixed.

**Comment by hxim** [comment]
@photopea 
You fixed it wrong if you open Color Picker dialog after opening Blending options dialog it allows you to manipulate with things now...

open pea.psd demo file
open "Blending options" of layer "pea"
check checkbox "Drop Shadow" (Drop Shadow appears in Layers window)
! open color picker from Properties window - Solid Color Fill
click eye next to Drop Shadow in Layers window (Disable Layer Effects appears in history)
change opacity in "Layer Style" pop-up and click OK (Layer Style appears in history)
undo last step in history - Layer Style (Drop Shadow disappers from Layers window)
try to undo last step in history - Disable Layer Effects
->
error

**Comment by photopea** [comment]
Amazing, thanks a lot! Actually, I was aware of this, but I was to lazy to fix it properly. But now it should be fixed well (i.e. when Layer Styles window is open, you should not be able to do anything else).
