### ISSUE TITLE
The color of shadow slider need to be different from the color of highlight slider

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3220]
Without different colors, sometimes it's hard to tell whether the slider is shadow or highlight. 
![screenshot_20210507_235410](https://user-images.githubusercontent.com/79258245/117477578-bca4cb00-af90-11eb-99db-5e9a960e2302.jpg)

Have a look at the sliders in Photoshop
![1$Z7LBLE9ZD45}LD7K1 9QP](https://user-images.githubusercontent.com/79258245/117477670-de05b700-af90-11eb-8531-348713c0b619.png)

**Comment by photopea** [comment]
You are right, I fixed it.

**Comment by nothingshiru** [comment]
the color of shadow sliders need to be changed. Now they almost blended into background. It's hard for eye to see them. 
![Screenshot_20210510_192317](https://user-images.githubusercontent.com/79258245/117652699-01905380-b183-11eb-848b-129544ac07a3.jpg)

**Comment by photopea** [comment]
I made a black slider a bit brighter.
