### ISSUE TITLE
Issue: There are two problems with density of mask

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3221]
There are 2 problems with density of mask. 
The problems are not appearing in the mask on fill layer. (Color, Gradient, Pattern) 

**1. The effect is incorrect when decrease density of a full black mask**
Decreasing density from 255 to 254 would make the full black mask be like a full white mask. 

**2. The affected area is incorrect when adjust density of mask**
When adjust density of mask, the affected area is a rectangle, and the width and height of the rectangle are depending on the colors that are not black in the mask. 
![Screenshot_20210508_031229_com android chrome](https://user-images.githubusercontent.com/79258245/117499631-12d43700-afae-11eb-9fe5-0e70fec82ac2.jpg)
![Screenshot_20210508_031229_com android chrome (1)](https://user-images.githubusercontent.com/79258245/117499639-149dfa80-afae-11eb-91af-3696ad214706.jpg)

Here's a PSD to test. 
https://www.photopea.com/#iQ7W0pr8F

**Comment by nothingshiru** [comment]
When the mask is on fill layers, it works fine. 
![screenshot_20210508_011916](https://user-images.githubusercontent.com/79258245/117485922-8b7dc800-af9b-11eb-897e-cc0db1a0d54a.jpg)

**Comment by nothingshiru** [comment]
There is more than one problem with density of mask. 

I created a full black maks and painted a white circle in it. 
See what happened

https://user-images.githubusercontent.com/79258245/117494266-ab66b900-afa6-11eb-995d-6f822905300a.mp4

here's the psd
https://www.photopea.com/#i90Q1eZMe

**Comment by photopea** [comment]
Fixed, thanks for reporting!
