### ISSUE TITLE
double crash

### ISSUE THREAD

**Issue by Jonas22rr** [photopea/photopea#3222]
i sat for 2 hours was about to save it when the page crashes. 
I tried again sat for 2 hours and it crashed again!!!

**Comment by photopea** [comment]
Hi, what browser do you use? Only a browser can "kill" photopea, it never crashes by itself.

Can you update your browser? If you know your computer does that, can you e.g. save your work every 30 minutes?

**Comment by photopea** [comment]
If you work with hundreds of millions of pixels (e.g. 20 layers 4000 x 4000 = 320 million pixels), you need a lot of RAM memory. Layers that you delete still stay in RAM, so that Photopea can let you go back to the previous state.

How much RAM do you have? You need 8 - 16 GB for the best work with large documents.

**Comment by Jonas22rr** [comment]
I used Crome and hav 32 gb RAM

**Comment by photopea** [comment]
That is strange. And how large are your documents? How large your PSDs are?

**Comment by Jonas22rr** [comment]
Sorry but I don’t know what you mean with my documents and my PSDs. 

So in my pc is the rtx3070 oc and my cpu is Ryzen 7 3800x if you mean that

**Comment by photopea** [comment]
Photopea runs inside the RAM memory. If you open any photo in Photopea, and start to duplicate a certain layer many times, the memory will always run out at some point, and the browser will kill Photopea. It can be 10 copies of a layer, or 10000 copies of a layer, depending on how many pixels are there in a layer.

Each pixel takes four Bytes. So if your document has 10 billion pixels, 32 GB of RAM is not enough.

There is nothing we can do about it. A browser does not tell us how much free RAM the user has, so Photopea can not predict the crash and tell you to save your work in advance.

@tomayac is there a way for a website to know, that the memory is running out and it could be killed by Chrome?

**Comment by Jonas22rr** [comment]
Ok I understand. 
Thankyou for your fast and friendly answers! 
I find that this program is fantastic clear this little problem, but it is for free!!!
Thankyou for everything and have a nice rest weekend 
Perhaps you can find a answer for this error

**Comment by tomayac** [comment]
The best there is so far is the [Device Memory API](https://w3c.github.io/device-memory/#sec-device-memory-js-api). It will give you static RAM information, but not dynamic RAM usage data. 

Some folks at Google (@pwnall, @oyiptong) are working on a [Compute Pressure API](https://github.com/oyiptong/compute-pressure/blob/main/README.md), but so far RAM usage isn’t part of the equation.
