### ISSUE TITLE
Issue: The text box of layer name is still activated after tapped Enter on virtual keyboard

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3223]
![Screenshot_20210508_013606](https://user-images.githubusercontent.com/79258245/117487825-2d9eaf80-af9e-11eb-911d-25674c05911e.jpg)

Could you make it the same as pressing Enter on real keyboard?

**Comment by photopea** [comment]
Is it Chrome on Android? I just tried it and it does not dispatch regular keyboard events. I think afraid only Chrome / Android developers can fix it. Maybe it works on some different phones or in different browsers.

**Comment by nothingshiru** [comment]
I'm very sorry for forgetting to reply you in this issue. 

I have tried Chrome, Edge, Firefox on different Android devices. 
In all of them, tapping Enter key on virtual keyboard doesn't work for ending renaming layers. But pressing Enter key on a real keyboard works. 

Is it about the difference of "Enter" between virtual keyboard and real keyboard?

**Comment by photopea** [comment]
It is hard to tell. It is a browsers job to tell a website what key is pressed. If a browser does not tell it to a website, there is nothing a website can do :(

**Comment by nothingshiru** [comment]
Tapping Enter can apply values when changing values. In this case, the Enter key on virtual keyboard works same as the Enter on real keyboard.

https://user-images.githubusercontent.com/79258245/119902077-54d31600-bf79-11eb-9b43-0db7f6675d72.mp4
