### ISSUE TITLE
Attempting to create a Replace Color adjustment layer breaks panels and the workspace

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#3224]
1. After ensuring that extensions are disabled, open Photopea and open the browser console. Choose File > Open. Open an image that looks different from a new document in Photopea.
2. Choose Layer > New Adjustment Layer > Replace Color. >> The properties panel appears as if a Replace Color adjustment layer is active, but only the original layer exists in the Layers panel. The History panel only shows the Open state. A red error appears in the console.
3. Click the visibility toggle on the image layer in the Layers panel. >> Nothing changes.
4. Click on the layer name. >> A `no escape` message appears in the console.
5. Close the document. Then attempt to open a new document using File > New > Create. >> The image from before appears in the workspace, but the Layers panel is empty and greyed-out.

After step 2:
![image](https://user-images.githubusercontent.com/51429646/117558021-313a4100-b047-11eb-8608-49a4b66abc2a.png)
![image](https://user-images.githubusercontent.com/51429646/117558026-42834d80-b047-11eb-81ca-fbfadb0e957e.png)

The bug still happens if you open a new document instead of an image file in step 1, but the result of step 5 would be hard to notice. After step 2, the lock icon on the layer would also not do anything.

**Comment by photopea** [comment]
I am very sorry, it should be fixed now.
