### ISSUE TITLE
The yellow square and dark background color confuse people

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3225]
When tapped some buttons (not only enabled), the yellow square and dark background color were displayed. Sometimes it can confuse people so that they don't know whether the buttons are enabled or disabled. 
![Screenshot_20210509_224815_com android chrome](https://user-images.githubusercontent.com/79258245/117576942-3fd03900-b0d7-11eb-981a-4967d3e9d1e0.jpg)

When tapped top menu or tools in tool bar, there's no the problem. 

https://user-images.githubusercontent.com/79258245/117569876-3636d900-b0b7-11eb-8c3a-b9b5a2032fca.mp4

**Comment by photopea** [comment]
I think it is a behaviour of a browser, which highlights the last clicked button. It can be useful to some people. I am afraid we can not do anything about it.

**Comment by nothingshiru** [comment]
Hi. 
The yellow sqaure no longer appear now. And I have not updated my browser. Is that you fixed it? 

But when disabled button, there's still dark background so that it can't be distinguished whether it's disabled or enabled unless clicked somewhere else and the dark background disappears. 

Can this be fixed?
