### ISSUE TITLE
Downloading a layer from xd file in png discards transparency of the layer and replaces with white background

### ISSUE THREAD

**Issue by abhijit-paul** [photopea/photopea#3226]
Steps to reproduce:
1. Import a xd file in Photopea
2. Select a layer with a transparent image
3. Click download png 
4. Issue: The downloaded file has white background instead of transparent as was there in the layer

**Comment by photopea** [comment]
Hi, I am very sorry, it is fixed now.

**Comment by mschipperheyn** [comment]
This is still the case

**Comment by photopea** [comment]
What should I do to see the problem myself?
