### ISSUE TITLE
Fonts and Brushes Dissapearing

### ISSUE THREAD

**Issue by AlyssaEvangeline** [photopea/photopea#3228]
When I import fonts, they stay until I exit and save the design, but when I go back to edit it, the fonts disappear and I have to re-import them. The same thing happens with the brushes. How do I keep that from happening? Thanks!

**Comment by photopea** [comment]
Something is wrong with your browser environment. Can you disable all browser extensions and see if there is a message? I think one of your extensions is blocking messages in Photopea.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
