### ISSUE TITLE
Issue: Icons size of adjustment layer didn't change automatically when other thumbnails changed

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3229]
The thumbnail size depends on ratio of canvas. When changed the ratio, the thumbnails of layer and fill layer changed automatically, but icons of adjustment layer didn't. 
![Screenshot_20210512_111245](https://user-images.githubusercontent.com/79258245/117913364-c439dc00-b2d0-11eb-9e57-eb434ab18a36.jpg)

**Comment by photopea** [comment]
fixed, thanks for reporting!
