### ISSUE TITLE
Issue: With Rulers enabled, part of image is covered when Fit The Area

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3230]
In order not to be covered, the image can be smaller when Fit The Area by double-click on hand tool icon. 
![screenshot_20210512_161126](https://user-images.githubusercontent.com/79258245/117942464-ac4c7180-b33d-11eb-8d90-9de67f9e0988.jpg)

**Comment by photopea** [comment]
I fixed it, so that it is always at least 4 px from the ruler.

**Comment by nothingshiru** [comment]
Now Fix The Area there is always a gap in right side. And with Rulers unabled, there is gap in left side too. 
![Screenshot_20210512_224619_com android chrome](https://user-images.githubusercontent.com/79258245/117997435-79e94700-b332-11eb-93f2-3042efad4590.jpg)


When Rulers is enabled, it should be similar to this
![Screenshot_20210512_225354_com android chrome](https://user-images.githubusercontent.com/79258245/117997613-a4d39b00-b332-11eb-81cd-fc06136b2daa.jpg)

When Rulers is unabled, it should be same as before
![Screenshot_20210512_225419_com android chrome](https://user-images.githubusercontent.com/79258245/117997705-bae15b80-b332-11eb-9040-3e61e269914e.jpg)

**Comment by photopea** [comment]
Ok, it is now bigger, if rulers are disabled.

**Comment by nothingshiru** [comment]
What about the gap in rith side when rulers are enabled? The image can be bigger too.

**Comment by photopea** [comment]
making it 100% like Adobe Photoshop is too much work, sorry :(
