### ISSUE TITLE
Mode of vector tools in a group should be the same

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3231]
When changed mode in one tool, the mode in all tools in a group should be changed too. 

For example, Change mode from shape to path in Rectangle, then switch to Ellipse, the mode in Ellipse should be path too. 
![Screenshot_20210512_162205](https://user-images.githubusercontent.com/79258245/117943884-2cbfa200-b33f-11eb-9d28-445426252a13.jpg)

The pen tool and free pen tool are in another group, so changing mode in pen tool will change the mode in free pen tool but won't change the mode in Rectangle, Ellipse etc.

**Comment by photopea** [comment]
I made all tools share the same vector drawing mode.

**Comment by nothingshiru** [comment]
Could you make shape tools group has independent mode from pen tools group? 
 
Because the pixel mode can be selected in shape tools group but can't in pen tool. So they should be different. 

Also I noticed that we can't select pixel mode in free pen tool in Photoshop, but we can do that in Photopea. Could it be changed?

**Comment by photopea** [comment]
Now, the pixel mode is re-mapped to Shape mode for the Pen tool.

I think there is no problem with letting the Fre Pen tool draw pixels. It is an extra feature, you do not have to use it.

**Comment by nothingshiru** [comment]
Ok.
