### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by playsenge** [photopea/photopea#3232]
THE ISSUE IS THIS IS TOO GOOD WHY IS THIS PROGRAM SO GODLIKE HOW DID YOU DO THIS

Ok here's an actual issue:
When you have a file in for example 800x800 and you want to export as ICO it just crops the image, really annoying, it should just scale it down to 256x256.

**Comment by photopea** [comment]
The ICO format supports at most 256x256 pixel images. When you want to turn a larger image into ICO, it is not clear, if you want to crop it, or scale it down (or something else).

If cropping is not what you want, just set the image size to 256 manually.
