### ISSUE TITLE
Template/ Smart Object gets distorted suddenly

### ISSUE THREAD

**Issue by anythingwhatever** [photopea/photopea#3233]
My templates/ smart object (the arrow) gets distorted every time i try to re-orientate it (see left). This issue is new and has never happened before
![Screenshot 2021-05-12 180200](https://user-images.githubusercontent.com/84073987/117957120-4ca99280-b34c-11eb-9d2e-37ca200eac57.png)

**Comment by photopea** [comment]
How can I reproduce the issue? Could you share a PSD file with the arrow with us?

**Comment by photopea** [comment]
It should be fixed now.
