### ISSUE TITLE
Issue: Invisible handle of anchor could be dragged

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3234]
None of anchors are activated, but their handles could be dragged. 

https://user-images.githubusercontent.com/79258245/117957442-a9a54880-b34c-11eb-97f5-062b06382c49.mp4

Sometimes I wanted to select multiple anchors but clicked on the invisible handle. The handle would be dragged then I have to press Ctrl+Z to undo the mistake.

**Comment by photopea** [comment]
fixed, thanks for reporting!
