### ISSUE TITLE
Feature Request: Add ticks in front of panels in top menu "Window"

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3235]
Add ticks in front of the panels that are enabled. 
![Screenshot_20210512_194540_com android chrome](https://user-images.githubusercontent.com/79258245/117971817-f09b3a00-b35c-11eb-97a4-063d225b3d43.jpg)

**Comment by photopea** [comment]
Ok, I added these checkmarks for windows, which are added into a right bar at the moment (even if they are "collapsed").

BTW. ticks are little bugs which suck blood :D https://en.wikipedia.org/wiki/Tick

**Comment by nothingshiru** [comment]
Didn't use a proper word to be translated into English. 🙃
