### ISSUE TITLE
Suggestion : Pixel Sort

### ISSUE THREAD

**Issue by JeremixxGithub** [photopea/photopea#3236]
I would love to have a **Pixel Sort plugin** for Photopea! 
Well.... I just felt like Wind isn't enough so I decided that there might be some Pixel Sort thing or more feature to the Wind effect. 

https://openprocessing.org/sketch/422167/ Take this as an inspiration. kthxbye.

**Comment by photopea** [comment]
What exactly does it do? Is it just like an "artistic filter", to make the image "look interesting"?

It is hard to tell if anyone other than you would be interested in such effect.

**Comment by photopea** [comment]
I think this effect is "nicer" for videos than for images. So I will leave it for the time when we develop a video editor.
