### ISSUE TITLE
GIF exporting incorrectly

### ISSUE THREAD

**Issue by nenochis-1** [photopea/photopea#3237]
Hi there!
I created a GIF from scratch and it is exporting with a blank added frame and deleting a path. in the 40% progress
![templateTierrasMayas](https://user-images.githubusercontent.com/46464895/118054984-e3764f00-b34c-11eb-89ac-ed3c6eb158b0.gif)

I added the psd file in the zip so you can check that also
[templateTierrasMayas.psd.zip](https://github.com/photopea/photopea/files/6469491/templateTierrasMayas.psd.zip)

Thank you!!

**Comment by photopea** [comment]
So I guess you want an animation with five frames, right?

But you have six layers starting with "\_a\_". There is a layer named "\_a\_frm11,500" in one of your folders, which generates a separate frame. Just rename it to something else.

![image](https://user-images.githubusercontent.com/15955558/118103390-26cacf00-b3da-11eb-9f1d-463ba5bdb07d.png)
