### ISSUE TITLE
Fearture Request: Position self-adaption of panels

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3239]
Open Photopea on a phone, 
with portrait mode, all panels are in a volume, 
with landscape mode, panels are in different volume as same as on PC. There's no problem. 

But when opened with portrait mode then switch to landscape mode, the panels are still in a volume so that we have to scroll down to find the panels below.
![Screenshot_20210513_214412_com android chrome](https://user-images.githubusercontent.com/79258245/118138654-2c0b3680-b439-11eb-87a0-0fff3c850a04.jpg)
![Screenshot_20210513_214449_com android chrome](https://user-images.githubusercontent.com/79258245/118138694-36c5cb80-b439-11eb-8f4d-ce1e0dd43963.jpg)

When opened with landscape mode then switch to portrait mode, the panels are still in two different volumes so that we no longer have bigger area for displaying image. 
![Screenshot_20210513_221716_com android chrome](https://user-images.githubusercontent.com/79258245/118138726-3decd980-b439-11eb-9eb3-42024d9a2f53.jpg)
![Screenshot_20210513_221727_com android chrome](https://user-images.githubusercontent.com/79258245/118138746-42b18d80-b439-11eb-8333-f87befdef391.jpg)

If panels can go into one panels when in portrait mode, and the panels that are normally in left volume go into left volume when in landscape mode, exprience on mobile phone can be better.

**Comment by photopea** [comment]
fixed, thanks for reporting :)
