### ISSUE TITLE
Color Lookup adjustment layer doesn't reset properly

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#3240]
The Color Lookup adjustment layer has an option for loading an LUT in the Properties panel. Once an LUT gets loaded, resetting and undoing fail to properly disable the LUT. (The option stays darkened, as if it is still selected.) When WebGL is on, the LUT still gets rendered. When WebGL is off, Photopea correctly behaves as if the LUT is disabled.

1. After ensuring that extensions are disabled, open a new document (white being default) in Photopea. Go to More > Use WebGL to make sure that WebGL is enabled.
2. Choose Layer > New Adjustment Layer > Color Lookup. Toggle WebGL twice. >> The workspace turns black when WebGL is on.
3. In the Properties panel of the Color Lookup layer, choose Arabica 12.CUBE. Observe the list of loaded LUTs.
4. Click the Reset button. Observe the list of loaded LUTs. Toggle WebGL twice. >> When WebGL is on, the document still looks as if it has the LUT enabled.
5. Go back to the Open state in the History panel. Add the Color Lookup adjustment layer again. Observe the list of loaded LUTs. >> The same result as in step 4.

During step 2 when WebGL is on:
![image](https://user-images.githubusercontent.com/51429646/118196349-e0499480-b41a-11eb-873d-deea34b251ce.png)

During step 3, the result is correct. The entry for Arabica 12.CUBE in the list of loaded LUTs is darkened, which means it is selected.
![image](https://user-images.githubusercontent.com/51429646/118196441-01aa8080-b41b-11eb-87cf-8ac9307fddb7.png)

During step 4, the entry for Arabica 12.CUBE is still darkened, even though it is supposed to be unselected. When WebGL is on, the document is still orange:
![image](https://user-images.githubusercontent.com/51429646/118196700-72519d00-b41b-11eb-8e8e-e96dbba63aad.png)

During step 5, the entry for Arabica 12.CUBE is still darkened. When WebGL is on, the document is still orange:
![image](https://user-images.githubusercontent.com/51429646/118196834-ad53d080-b41b-11eb-9bee-c1bee1dac51f.png)
The entry for Arabica 12.CUBE should be the lighter grey, as shown below, after clicking the reset button or undoing:
![image](https://user-images.githubusercontent.com/51429646/118197538-27388980-b41d-11eb-9a77-8bf21e9144fc.png)

**Comment by photopea** [comment]
We can not guarantee any specific behaviour of an adjustment layer, for which the LUT has not been chosen. Such layer can do "anything" to the image (it can be different things with WebGL on and off).

The user should do one of two things:
- create a color lookup adjustment layer and choose a specific LUT for it
- not create a color lookup layer at all, or hide an adjustment layer, which has no LUT selected
