### ISSUE TITLE
Issue:Half of the cross in New Project window is outside of screen

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3243]
It seems that the thing which is aligned with the edge of screen is the scrollbar of templates but not the edge of this window. 
![Screenshot_20210514_170449_com android chrome](https://user-images.githubusercontent.com/79258245/118248942-72af6e00-b4d7-11eb-886c-f1ad194e5f4b.jpg)

**Comment by photopea** [comment]
fixed, thanks for reporting! :)
