### ISSUE TITLE
Support for HEIC images (from apple devices)

### ISSUE THREAD

**Issue by nmiodice** [photopea/photopea#3244]
Would love to see some baseline support for HEIC images, as most apple phones will produce these by default when taking photos

**Comment by photopea** [comment]
The HEIC is a proprietary format from Apple, and we can not use it commercially without paying them a fee.

I think people should avoid using non-open formats, if they want their images to be usable in on-Apple programs.

**Comment by photopea** [comment]
You can open HEIC now! It is available in a plugin by @hxim . Press Window - Plugins, and choose "JPEG XL, AVIF" plugin. An icon will appear in the right bar, which lets you load HEIC images.
