### ISSUE TITLE
Bug - keyboard shortcut for zoom in/out gets confused on mac

### ISSUE THREAD

**Issue by nmiodice** [photopea/photopea#3245]
Steps to reproduce:
 - Press/hold `cmd` key on a mac. Keep it pressed for all steps below
 - Zoom in by pressing `+` while continuing to hold `cmd`
 - Zoom out by pressing `-` while continuing to hold `cmd`
 - Press `+` while continuing to hold `cmd`

You'll notice that on the final step (press `+`) that the image will zoom out, not in!

**Comment by photopea** [comment]
Hi, it is a well-known bug in Mac OS. It was reported before:

https://github.com/photopea/photopea/issues/2983
https://github.com/photopea/photopea/issues/1949
https://github.com/photopea/photopea/issues/1726
https://github.com/photopea/photopea/issues/1637

You can try to ask Apple kindly to solve it, or buy a different device. There is nothing a program running on Mac can do about it :(
