### ISSUE TITLE
all exporting/save options are in txt files

### ISSUE THREAD

**Issue by thaynos** [photopea/photopea#3246]
what it says in the title. i tried all formats.
it works if i use a txt to jpg converter tho.

**Comment by photopea** [comment]
Do you use a browser extension called "Download Manager"?

**Comment by photopea** [comment]
I think one of your browser extensions is renaming downloaded files. Try to find and disable that extension. Or disable all browser extensions (I never used one in my life and my web experience is still great).

**Comment by thaynos** [comment]
i do in fact use free download manager. but the files did not download on the manager rather in downloaded in my browser only. ive never had a problem with the manager and i use it for torrenting/faster downloading speeds.

**Comment by thaynos** [comment]
it worked when i turned off the download manager. but why does it only happen for this app? other photo editing apps works perfectly with this download manager.

**Comment by photopea** [comment]
You should ask the authors of the Download Manager, why do they do it. Browser extensions have "more rights" than websites. They can change the behaviour of any website, a website can not do anything about it.
