### ISSUE TITLE
Feature Request: Vertical display mode in Refine Edge/Magic Cut

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3247]
Now there's only horizontal display mode. When using phone with portrait mode, the displayed image is quite small. If we got vertical display mode, the difference of size of image would be like this
![Screenshot_20210516_195602_com android chrome](https://user-images.githubusercontent.com/79258245/118397152-3752a200-b685-11eb-85cc-9ca77872afb8.jpg)
![Screenshot_20210516_195602_com android chrome (1)](https://user-images.githubusercontent.com/79258245/118397155-39b4fc00-b685-11eb-8a06-9bce641a08db.jpg)

Vertical display mode is also useful for working with wide image on PC.

**Comment by nothingshiru** [comment]
And it would be better if Photopea can choose vertical/horizontal mode automatically. 

The area for displaying image and the ratio of the image are fixed. Is it possible that calculating sizes of image in two modes then choosing the mode which is displaying bigger image automatically? 

Besides, a toggle button for people to switch mode manually is still necessary.

**Comment by photopea** [comment]
I have fixed it. It also depends on the size of a layer. E.g. if a layer is 500x100 pixels, the previews will be on top of each other, even on a "landscape" screen.

**Comment by nothingshiru** [comment]
"Reduce Colors" and "Vectorize Bitmap" needs this feature too.

**Comment by photopea** [comment]
Sure, it works that way now :)
