### ISSUE TITLE
spin blur

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#3248]
hi
recently I used to do some Technique to make realistic shadows in my artworks in photoshop, this Technique depends entirely on spin blur in photoshop, and This technique consists of spin blur the shadow line as it is shown in this image : 
![Screenshot (150) (1)](https://user-images.githubusercontent.com/70863817/118404462-3fa1e180-b673-11eb-9251-80a50bd81130.png)
.
.
I tried to do this technique in photopea with the radial blur filter, but it was very very hard to reach the right point with input methods and I can't see exactly where is the point of spin : 
![Screenshot (151)](https://user-images.githubusercontent.com/70863817/118404616-eb4b3180-b673-11eb-921c-07b95c14d5cc.png)
.
.
I thought if you add a visual control as photoshop does in the spin blur, it would be so much easier
![Screenshot (151) (1)](https://user-images.githubusercontent.com/70863817/118404748-73313b80-b674-11eb-9e34-413530bc8d0d.png)
.
.
this little point will make a huge difference
![Screenshot (150) (2)](https://user-images.githubusercontent.com/70863817/118404936-66611780-b675-11eb-9b03-5aa36dbb8c42.png)
.
.
you will find the same point in photoshop>filters>blur gallery>spin blur

**Comment by photopea** [comment]
I fixed it. Now, you can click into the image to choose the center of the Radial Blur.

We will add advanced blurs as part of these filters: https://github.com/photopea/photopea/issues/2792

**Comment by mustafaGFX** [comment]
> I fixed it. Now, you can click into the image to choose the center of the Radial Blur.

thank you very much :)
.
.


> We will add Spin Blur as part of these filters: #2792

fantastic

**Comment by aftermathroblox2-create** [comment]
import cv2
import numpy as np
from moviepy.editor import VideoFileClip

def apply_radial_blur(image):
    # Hinahanap ang gitna ng video frame
    h, w = image.shape[:2]
    center_x, center_y = w // 2, h // 2
    
    # Gumagawa ng spin/radial blur gamit ang OpenCV
    num_steps = 10
    blur_output = np.zeros_like(image, dtype=np.float32)
    
    for i in range(num_steps):
        angle = (i - num_steps / 2) * 0.5  # Ang tindi ng ikot
        M = cv2.getRotationMatrix2D((center_x, center_y), angle, 1.0)
        rotated = cv2.warpAffine(image, M, (w, h), flags=cv2.INTER_LINEAR, borderMode=cv2.BORDER_REFLECT)
        blur_output += rotated
        
    return (blur_output / num_steps).astype(np.uint8)

# I-load ang iyong kinunang video
clip = VideoFileClip("input.mp4")
# Ilagay ang radial blur effect sa bawat frame
blurred_clip = clip.fl_image(apply_radial_blur)
# I-save ang bagong video
blurred_clip.write_videofile("output.mp4", codec="libx264")
