### ISSUE TITLE
Alt Key + Pen tool not working in illustrator

### ISSUE THREAD

**Issue by Sid1301** [photopea/photopea#3249]
I am not able to use the pen tool when I am holding the alt key in illustrator.

https://user-images.githubusercontent.com/84304869/118435736-23e31d80-b6fd-11eb-9649-7fc813d55d8b.mp4

**Comment by photopea** [comment]
Hi, sorry, we are not the creators of Adobe Illustrator. You should report it to Adobe, it is a company from the USA.
