### ISSUE TITLE
Move "No Touch" to top-right

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3251]
"No Touch" is not a virtual key. I think it shouldn't be together with virtual keys.
 
 How about moving it to top-right? 
![Screenshot_20210517_171301_com android chrome](https://user-images.githubusercontent.com/79258245/118465130-27de6200-b734-11eb-9010-77ced85ce8a2.jpg)

**Comment by photopea** [comment]
I think not that many people use that option, so it is wrong to show it to everyone like this.

**Comment by nothingshiru** [comment]
I use virtual keys frequently. But the virtual keys window is being larger unnecessarily Because of this hardly used option. So I prefer it to be moved elsewhere. 
![Screenshot_20210517_181822_com android chrome](https://user-images.githubusercontent.com/79258245/118474046-3aa96480-b73d-11eb-95e6-3bac23171849.jpg)
