### ISSUE TITLE
Leave virtual keys window open like panel window

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3252]
Normally the virtual keys would be disabled soon after be enabled. It can be more convenient if the virtual keys window is keeping open. Like panel window, click on icon to open and click again to close. 

And position of the window need to be moved because it has covered other icons now. 

I think it can be like this
![Screenshot_20210517_165557_com android chrome](https://user-images.githubusercontent.com/79258245/118466905-e18a0280-b735-11eb-9ad1-57ee3a436c1a.jpg)

**Comment by photopea** [comment]
Fixed, the virtual keys panel will stay until you click the button again.
