### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#3253]
I designed new icons for the right panel in photopea to look more professional

here is before
![Screenshot (156) (1)](https://user-images.githubusercontent.com/70863817/118408131-5ac91d00-b684-11eb-8510-00502ef1d962.png)
.
.
here is the after
![Screenshot (156) (2)](https://user-images.githubusercontent.com/70863817/118408147-73d1ce00-b684-11eb-8e60-cb9bfd530397.png)

![Screenshot (156) (3)](https://user-images.githubusercontent.com/70863817/118408411-d1b2e580-b685-11eb-8df4-82cecca9eec2.png)

![Screenshot (148)-svg](https://user-images.githubusercontent.com/70863817/118500889-784fc280-b728-11eb-835a-5396066c8b64.png)

what do you think ...?
if you like the idea I can send you all these SVG icons, let me know

**Comment by photopea** [comment]
they look amazing, did you create them yourself, from scratch?

**Comment by mustafaGFX** [comment]
thanks :)
and yes I did create almost all of them from scratch, and some of them have been created by editing some free open source icons

**icons created from scratch:**
info
histogram
actions
layer comps
characters
glyphs
3d

**edited open source icons:**
properties
navigator
brush settings (mixed by 2 different icons)
paragraph
tool preset
The rest of the icons

**Comment by photopea** [comment]
For Photopea icons, I need PNG files 160x160 pixels, black color on the transparent background.

If possible, the graphics should be aligned to a 8-pixel grid. Can you do that?

![image](https://user-images.githubusercontent.com/15955558/118662142-10fd4580-b7f0-11eb-8a73-ab2e12b97435.gif)

**Comment by mustafaGFX** [comment]
I will check it out

**Comment by mustafaGFX** [comment]
like this
![Screenshot (158)](https://user-images.githubusercontent.com/70863817/118669740-4c027780-b7f6-11eb-9702-1f894648117d.png)
?

**Comment by photopea** [comment]
Your image is 100 pixels wide, it should be 160 pixels.

Your grid is 5 pixels, it should be 8 pixels.

**Comment by photopea** [comment]
So just scale it up to 160%.

**Comment by mustafaGFX** [comment]
I did exactly what you said, I guess you concluded that I did it wrong cuz of the ruler, it was in Percentile measurement

![Screenshot (160)](https://user-images.githubusercontent.com/70863817/118674383-09db3500-b7fa-11eb-8707-ce7467c0977f.png)


![Screenshot (161)](https://user-images.githubusercontent.com/70863817/118674519-1f505f00-b7fa-11eb-8f65-a4b66650c248.png)


![Screenshot (162)](https://user-images.githubusercontent.com/70863817/118674545-25464000-b7fa-11eb-9dbf-c1d76ef71d16.png)

**Comment by photopea** [comment]
Ok I see, that is great then! :)

**Comment by mustafaGFX** [comment]
great,
I will align all the icons and send them, but some icons cant be aligned because it's balanced in the current shape like CSS and tool presets icons, must they all be aligned?

**Comment by photopea** [comment]
no, just do the best you can.

**Comment by photopea** [comment]
Can you send me the PSD, too?

**Comment by mustafaGFX** [comment]
yes I will send you both formats, png, and PSD files to support@photopea.com

**Comment by mustafaGFX** [comment]
I sent them

**Comment by photopea** [comment]
Could you place all icons into one PSD instead of having multiple PSDs, please?

**Comment by mustafaGFX** [comment]
I have just done that :)
check your inbox

**Comment by mustafaGFX** [comment]
it's my pleasure :)

**Comment by nothingshiru** [comment]
@mustafaGFX 

Wow, these icons look pretty good. 

You had designed icons for the panels in left volume but seemed to have forgotten the panels in right volume. Would you design icons for those panels in future? 

Anyway, thank you for what you did. 
![screenshot_20210522_161728](https://user-images.githubusercontent.com/79258245/119220012-d7437c00-bb1a-11eb-990d-f5313203e12e.jpg)

**Comment by photopea** [comment]
the panels on the right are "collapsed" to icons only on mobile devices, which is a minority of users. The current icons are more important. But it would be great to have icons or everything.

**Comment by nothingshiru** [comment]
@photopea 
Hi. I have created two icons for Layer panel and Path panel.
![Layers Paths](https://user-images.githubusercontent.com/79258245/124256977-774ee500-db5e-11eb-89eb-8900e6b56108.jpg)
[Layers&Paths.zip](https://github.com/photopea/photopea/files/6753804/Layers.Paths.zip)

And I have 2 suggestions.

1. The Adjustments panel uses the same icon as the Adjustment layer in the Layers panel.
![Screenshot_20210702_175054](https://user-images.githubusercontent.com/79258245/124257391-eaf0f200-db5e-11eb-91e4-5a925679fa21.jpg)

2. The Channel panel use the same icon as the Channel Mixer adjustment layer.

**Comment by mustafaGFX** [comment]
@photopea 
>the panels on the right are "collapsed" to icons only on mobile devices, which is a minority of users. The current icons are more important. But it would be great to have icons or everything.

oh sorry. I haven't seen this comment since then, ist's  on May 22,
I hope I'm not too late, see if @nothingshiru  icons are good, if they are not, I can make new ones

@nothingshiru btw your icons look so good, are they aligned to an 8-pixel grid?

**Comment by nothingshiru** [comment]
> @nothingshiru would you be okay if I designed the Layer panel and Path panel icons too...?

That's OK.

**Comment by photopea** [comment]
@nothingshiru I did it all just as you said :) thanks for your great icons! :)

**Comment by mustafaGFX** [comment]
they look cool 
now there are just 3 icons left
I will see what can i do

**Comment by nothingshiru** [comment]
> they look cool
> now there are just 3 icons left
> I will see what can i do

Hi. Could you design a new icon for the "Replace Color" adjustment layer too?
When I created the icon now is used, I didn't come up with a good idea. And now I still don't know what would be good.

**Comment by mustafaGFX** [comment]
@nothingshiru gotcha
