### ISSUE TITLE
Color option

### ISSUE THREAD

**Issue by nnotari85** [photopea/photopea#3255]
When I am trying to change the color on a letter on a Layer (checked stroke) it is just gray no color options available. Please help.

**Comment by dentistformyeye** [comment]
Are you clicking the small rectangle in the bottom left here?
![image](https://user-images.githubusercontent.com/51429646/118568686-5bc28300-b746-11eb-89a3-58051e6e6955.png)

**Comment by nnotari85** [comment]
I finally figured it out! Thank you!
