### ISSUE TITLE
Fearture Request: Display virtual keys in toolbar instead of in window if there is enough space for virtual keys in toolbar

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3256]
Window is not needed when the space of toolbar is sufficient. 
![Screenshot_20210518_042215_com android chrome](https://user-images.githubusercontent.com/79258245/118552984-45daaf80-b792-11eb-8a8a-16730ec75f57.jpg)

**Comment by photopea** [comment]
I think the current "clean" design is beautiful in a way. With more buttons, Photopea would look too complciated. Also, 80% of users of Photopea use it on desktops, so they will not need these buttons at all.

**Comment by nothingshiru** [comment]
Sorry I didn't describe it clearly enough. 

I didn't mean that display virtual keys all the time. 
What I thought is that if there's enough space, clicking virtual key icon display virtual keys in toolbar instead of in a window. I like clean too, and that's why I asked for this feature.

**Comment by nothingshiru** [comment]
The topic of my request might be similar to "position of virtual keys window".

**Comment by photopea** [comment]
sorry, it is too complex.
