### ISSUE TITLE
SVG doesn't open / render correctly

### ISSUE THREAD

**Issue by holygekko** [photopea/photopea#3258]
When I generate + download a background from: https://bgjar.com/shiny-overlay

It fails (completely) to render correctly in photopea.

Expected:
[https://imgur.com/29xqoVP](https://imgur.com/29xqoVP)

Photopea:
[https://imgur.com/RHSRvym](https://imgur.com/RHSRvym)

link to svg content: [https://pastebin.com/TmjmWNy1](https://pastebin.com/TmjmWNy1)

**Comment by photopea** [comment]
Fixed, thanks for reporting :)
