### ISSUE TITLE
Magic Wand

### ISSUE THREAD

**Issue by Subzero13YT** [photopea/photopea#3259]
https://user-images.githubusercontent.com/76538841/118675544-aa186600-b7c8-11eb-87be-d6a6d5aa22e9.mp4

when I select an area and then I delete it, and try and go and delete a different area in the picture I cant, it just gets stuck in the same area, sometimes I have to use the magic wand in another layer and the deselect it to get it to work on the one am working on

**Comment by photopea** [comment]
It is because the Subtract mode is enabled (in the top left corner).

Or you use Firefox and you pressed Alt. There is a bug with the Alt key in Firefox. You can ask Firefox to fix it, or switch to some better browser.
