### ISSUE TITLE
Emoji Windows

### ISSUE THREAD

**Issue by Elina72** [photopea/photopea#3260]
Hello, 
My name is Elina. The emoji windows is popped up and I don't know how to get rid of it. Could you please help me, if you can?
Thanks in advance.

**Comment by mustafaGFX** [comment]
Click on the emoji icon to open the window and click again to close it, you can open and close any window by the same way
![Screenshot (154)](https://user-images.githubusercontent.com/70863817/118688833-b28f9180-b806-11eb-8af7-a14073093527.png)

**Comment by Elina72** [comment]
Thank you soooooo much!!!!

**Comment by mustafaGFX** [comment]
you are welcome :)

**Comment by photopea** [comment]
I am glad you figured it out :)
