### ISSUE TITLE
Feature Request: Add "Lock Guides" option above "Clear Guides" option in View

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3264]
It can prevent inadvertent movement of guides when move layer and there are too many guides. 
![screenshot_20210519_160106](https://user-images.githubusercontent.com/79258245/118777785-07411400-b8bc-11eb-86db-6e0e2f41d1fa.jpg)

**Comment by photopea** [comment]
I have added this option into View - Lock Guides.
