### ISSUE TITLE
Polygon Lasso Tool not showing guide line

### ISSUE THREAD

**Issue by cerysmees** [photopea/photopea#3265]
When using the polygon lasso tool, the guide line used to line up to make a new point does not show so you cannot be accurate with your shape.

Screenshot doesn't really say much but my mouse was over to the right and there was no guide line anymore

Using Google Chrome, also tried on incognito mode

My colleagues are also experiencing the same issue

<img width="1440" alt="Screenshot 2021-05-19 at 10 29 03" src="https://user-images.githubusercontent.com/84444818/118790190-6e939f80-b88d-11eb-92bd-e23652dd4bb2.png">

**Comment by photopea** [comment]
sorry, it is fixed now. Just reload Photopea (and make sure it is reloaded, as your browser could store the old version in cache).
