### ISSUE TITLE
Angle and Distance "NaN" in Layer Style Inner Shadow

### ISSUE THREAD

**Issue by playsenge** [photopea/photopea#3266]
![image](https://user-images.githubusercontent.com/40773107/118799455-0a79d700-b89f-11eb-8149-42d58f1d219b.png)
Umm... Yeah... That was the default value that showed up today when I opened Photopea. It's definitely something super easy, and it's not even that annoying but still.
Also didn't notice, but the distance also says it.

**Comment by photopea** [comment]
Hi, could you tell me some steps, what should I do to make it happen?

**Comment by nothingshiru** [comment]
@photopea 
Delete the value and press enter key.
