### ISSUE TITLE
Issue: Enabling No Touch while a finger is touching on canvas causes bug

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3267]
To reproduce

1. Touching on canvas with finger, doesn't matter what tool is selected
2. enable NoTouch
3. Release finger
4. Disable NoTouch

https://user-images.githubusercontent.com/79258245/118801273-68281680-b8d3-11eb-9572-48812c7dcff4.mp4

**Comment by photopea** [comment]
I dont know how to fix it. Just dont do it.

**Comment by nothingshiru** [comment]
I think this is one of reasons to move NoTouch somewhere else. What do you think?

**Comment by nothingshiru** [comment]
@photopea 

I think this might be a bug in Chrome for Android. 

I have tried these steps in Chrome, Edge, Firefox on Android. Only Firefox doesn't have this bug. 

Also, I found sometimes this bug would happen when used Magic Wand, Quick Selection, Object Selected. I had reported it months ago in #2897 . I just found out it is the same bug as this one. 

Could you report it to Chrome?
