### ISSUE TITLE
Issue: Bugs with deleting smart filters by dragging filters to trash icon

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3268]
There are 2 bugs. 

1. The smart filters on current smart object would be deleted/cleared, no matter on which smart object the smart filters that I dragged are. 
2. With multiple smart objects selected, smart filters can be deleted, but can't be cleared. And only the smart filters on the smart object at the bottom of all smart objects would be deleted. 

Here's PSD for testing
https://www.photopea.com/#icGuR2_7M

And here's video recorded what was going on

https://user-images.githubusercontent.com/79258245/118822405-b72d7600-b8ea-11eb-967c-85155a202e15.mp4

**Comment by photopea** [comment]
fixed, thanks for reporting! :)
