### ISSUE TITLE
upload mockups

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#3270]
I have about 300 mockups on my pc but the uploading process of one mockup takes a lot of time and effort, I have to publish the file and thumbnail and copy the links and getting into a very annoying and tiring process for just uploading one PSD template, is there any way to make this process easier, I want a button that makes the upload process automatedly and I just type the details (name and description)

**Comment by mustafaGFX** [comment]
I think this process is better : 
after clicking on ( _**publish as a free template**_), this is what will happen in the background

1. photopea publish the PSD
2. photopea gets the link of the PSD
3. photopea gets the thumbnail by converting the PSD into a png
4. photopea open me a window that asks me to name the template and put the description

and that's it

**Comment by photopea** [comment]
I have added a new button "Upload Current Document as a Template", which will upload a current document to Photopea and a preview to Imgur.

In general, I think it is not a good idea to "throw" many PSDs at once and expect they become popular. The most important thing is a good title and a description. When there are many PSDs in the future, people will type keywords to search between them.

![image](https://user-images.githubusercontent.com/15955558/119108108-248ef300-ba20-11eb-8fe6-bed29db3997d.png)

**Comment by photopea** [comment]
Please, upload only our own work. Do not upload the work of others without their permission.
