### ISSUE TITLE
Artboards - Cannot center layers within an artboard

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3271]
Layers inside an artboard does not get the red alignment, of the center of the artboard.
[Cards Pizza TOP.zip](https://github.com/photopea/photopea/files/6510750/Cards.Pizza.TOP.zip)

I am attaching a PSD.

Try aligning both plates within the center of its artboard.

**Comment by avagp** [comment]
I just wanted to add:

THANK YOU FOR ADDING ARTBOARDS


My work is so much better now.

Check this:
![Screenshot 2021-05-19 14 10 23](https://user-images.githubusercontent.com/11801254/118862734-0f915300-b8ac-11eb-9ebc-de26d0c285be.png)
![image](https://user-images.githubusercontent.com/11801254/118862806-233cb980-b8ac-11eb-8d1d-0103c63b68fd.png)

**Comment by MichalSZZ** [comment]
@avagp yes you are right! Some work with atrboards is now so easy. I had lesson with my students today about making web banners using artboards. Different sizes in one PSD file and easy export feature.

BTW. Today on my lesson I saw small bugs in artboards and I will try to report it as soon as possible:)

**Comment by photopea** [comment]
fixed, thanks for reporting! :)
