### ISSUE TITLE
image being invisible when i use a pack

### ISSUE THREAD

**Issue by imzeflash** [photopea/photopea#3272]
so i wanna use a lighting and effects pack to make a yt thumbnail but whenever i use it and its ready for me to import my background image, the image i want to use gets imported to be invisible in my project and doesnt even show up on the layer section. what should i do

**Comment by photopea** [comment]
How do you import an image? Can you maybe record a video of what you do?

**Comment by photopea** [comment]
I have to close it because of lack of details. We can keep discussing it in a closed issue.
