### ISSUE TITLE
Can't Install Photopea On Mac!

### ISSUE THREAD

**Issue by Gundish** [photopea/photopea#3274]
![Proof](https://user-images.githubusercontent.com/84504294/118958787-5bf99300-b97f-11eb-961e-dcae31a3e03b.png)

**Comment by photopea** [comment]
AFAIK this works only in Chromium - based browsers now - https://caniuse.com/?search=PWA  Ask Apple to implement this feature into Safair, if you want it to be available in Safari.

**Comment by Gundish** [comment]
> What browser are you using? That feature works only on updated webkit browser (Chrome, new Edge).

I am Using Safari

**Comment by Gundish** [comment]
> AFAIK this works only in Chromium - based browsers now - https://caniuse.com/?search=PWA Ask Apple to implement this feature into Safair, if you want it to be available in Safari.

Ok Thanks 😀
