### ISSUE TITLE
adjustment panel

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#3277]
since you update the adjustment icons, why don't you put them in one panel as photoshop does

![Screenshot (163)](https://user-images.githubusercontent.com/70863817/119023000-8d835600-b9a1-11eb-8518-6bffc2cff000.png)

![Screenshot (165)](https://user-images.githubusercontent.com/70863817/119027027-2916c580-b9a6-11eb-9871-eab0a35dd491.png)

![Screenshot (166) (1)](https://user-images.githubusercontent.com/70863817/119027044-2d42e300-b9a6-11eb-860f-0e61fd3b15de.png)

if you give me the option to turn on/off it, it will be great

**Comment by mustafaGFX** [comment]
it will be so much easier and faster for manipulation designers and photographers to edit their photos

**Comment by photopea** [comment]
We do not have an option to add a panel block between History and Layers :( or to resize them. Can I put it next to History, so you can see just one or the other?

**Comment by mustafaGFX** [comment]
no problem it will be great too

**Comment by mustafaGFX** [comment]
sometimes I arrange the panels in photoshop like this, do you think it better arrange?

![Screenshot (167)](https://user-images.githubusercontent.com/70863817/119028876-40ef4900-b9a8-11eb-8f4b-bf7b78920aac.png)

**Comment by photopea** [comment]
I added a separate panel with Adjustments. You can close any panel by right-clicking its label and choosing "Close"
