### ISSUE TITLE
Issue: Can't create shape based on the path which is created by shape tool with path mode

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3278]
To reproduce

1. Select one of shape tools and change mode to path
2. Create a path
3. create a fill layer

The thumbnail of the fill layer in path panel is correct, but what happened on canvas is incorrect. It seems the path has been ignored. 
![screenshot_20210521_022428](https://user-images.githubusercontent.com/79258245/119030248-35b61080-b9dc-11eb-8ed0-ea4c787e013d.jpg)

**Comment by photopea** [comment]
fixed, thanks for reporting! :)
