### ISSUE TITLE
Make "zooming in/out canvas by pinching with fingers" smoother

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3279]
Now pinching with fingers is the same as clicking on canvas with zoom tool. Could you make it same as scrolling horizontally with zoom tool which is smoother?

**Comment by photopea** [comment]
fixed, thanks for reporting :)

**Comment by nothingshiru** [comment]
Thanks. 

Can we get this feature in these windows as well? 

1. Reduce Colors
2. Vectorize Bitmap
3. Refine Edge
4. Magic Cut
5. Filter Gallery
6. Liquify

**Comment by photopea** [comment]
No, these windows work only with fixed zooms.
