### ISSUE TITLE
Artboards - selecting by clicking on the artboard name with Move Tool and Artobard Tool

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3280]
In PSD project with artboards, it should to be possibility to select an artboard by clicking its name above that artobard.
(in Photoshop after first click with Move tool the tool is changing to Artboard Tool)

- One click - artboard in layer palette is activating 
- Clicking with Shift on artboards name in working area should select those artboards on layers palette.

**Comment by photopea** [comment]
I have implemented it. Clicking the artboard label with any tool will select that artboard. If you click it with the move tool, it will also switch to the artboard tool.
