### ISSUE TITLE
Artboards - Guide (pixel position hint) with wrong position of Guide

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3281]
- Select the artboard on layers palette to activate this artboard.
- From left ruler start dragging the guide
- position in dark rectangle next to guide is showing in pixels X position of total project dimensions - not artboard guide position

each artboard should to have position as in the ruler (X and Y)

**Comment by photopea** [comment]
Fixed! Even if ruler units are precents, the value will be related to the current artboard :)
