### ISSUE TITLE
Artboards - duplicating the layer in one artboard and dragging it on layers palette to another artboard

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3282]
1. Selects some layer on artboard 1
2. Ctrl+J to duplicate
3. Start dragging that layer on layers palette to different Artobard

**What is now:**
The layer is in another Artboard (in layers palette) but in the same place as original layer in artboard in work area.

**How should it work:**
After the end of dragging the layer to the another Artboard in layers palette - layer should be in another artboard with position X and Y of its oryginal place in last Artboard

**Comment by photopea** [comment]
fixed :) btw. it is not related to duplicating at all. Simply, moving a layer "logically" in "Layers" will move it "physically" on a canvas to a new location.
