### ISSUE TITLE
Artboards - exporting only a selected artboards

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3284]
Now I don't know how to do that in Photopea...

In Photoshop that can be done by clicking right mouse button on artboard name in layers palette (in context menu there are two options - "Export as..." and "Quick Export as PNG"

You probably will say that I can use download button in Move Tool but...

1. It works only for one artboard (two or more are exported as one file - with those 3 artboards)
2. When the user don't set the background color (for example as color fill) it export with transparency - exporting artboard in Photoshop and Photopea (export as function in menu) doesn't do that

**Comment by photopea** [comment]
I fixed the problem with the Quick Export as PNG. Now, it will always export a complete artboard with the correct background.

You can also use File - Export As - PNG, and enable "as artboards", to get a ZIP file with all artboards.
