### ISSUE TITLE
Artboards - "Export as" window

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3285]
In "Export as" window in Photopea it will be great to see an option to select artboards visually (with check-boxes to each artboard separately).
Now I have one big window with all artboards as the one file with transparency... (new user don't expect to have ZIP file with those artboards - he can be confused)
I can not select artboards to export (that is the most wanted feature - any listed under is like a "nice to have" feature),
I can't set different quality to each artboard (the Google Display Network have some limits in KB for each format)
I can't set different file format for each artboard (some can be PNG and some JPG)

In Photoshop there are two options for exporting (Save for Web - it works with artboards like in Photopea now) and "Export as" with many additional functions

**Comment by photopea** [comment]
Now, you can export a single artboard with a "Quick export" button at the top, or all artboards in a ZIP with File - Export As, I think it should be sufficient. I am afraid of adding too many new features, because it could look messy. There are already many items in the File menu.
