### ISSUE TITLE
Making a new text layer with Shift

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3287]
Clicking on canvas with text tool and Shift it makes new text layer but in different mode as normal.
That trick is very helpful when you want to put new text layer on text or shapes:

- some other text layer that is in that place (for example - in the background I have some very big text with low opacity - when I try to set the new text layer in normal mode it is always trying to edit that layer below...)  In this situation now in Photopea I can't do anything - even locking that text layer below doesn't help (in Photoshop too - don't worry :) )
- if I have shape below and forget to make new a layer and don't want to put the text into that shape as a text container. Shift click will be a good solution for that problem - but that is now so important as a first example

**Comment by photopea** [comment]
I implemented it for both cases :)
