### ISSUE TITLE
Feature suggestion - UI for adding plugins

### ISSUE THREAD

**Issue by yikuansun** [photopea/photopea#3288]
Though the current Photopea plugin system works great for developers, it may be difficult or unintuitive for users to have to change the JSON data in the URI to add a plugin. Maybe there could be a way to upload small JSON files with individual plugin data, and be able to toggle them under the `Window` section of the menubar?

**Comment by photopea** [comment]
Hi, do you want to be able to put your plugin into Photopea, which will be available to all users of Photopea? I think people can upload "nasty" plugins this way.

If you have a nice plugin, show it to me and I can add it into Photopea.

**Comment by yikuansun** [comment]
Hi,
I think you might've misunderstood... my idea was for individual users to be able to download plugins (perhaps JSON file) from 3rd part developers and be able to install them to their own workspace, the same way users can upload brushes and custom layer styles to Photopea. Maybe they could be stored in the `Local Storage` panel. Maybe there could also be "featured plugins" panel where people could quickly install verified plugins, similar to Visual Studio Code's Marketplace?

**Comment by photopea** [comment]
Do you have an example of such JSON file plugin?

I think today, authors make plugins for a specific software (e.g. Photoshop or GIMP). There is no standard for plugins, which work in more than one program.

If we invent a JSON plugin format, which any program can use, these plugins will work only in Photopea for now. I don't know if there is anyone interested in making plugins for Photopea only. Would you like to make plugins for Photopea?

**Comment by yikuansun** [comment]
This is true, different programs do have different plugin formats.

I was thinking of using the same kind of JSON formatting that is used in the `environment`. For example, here is a plugin I made for more advanced lens flare rendering:
```
{
    "name"  : "Progen Flares",
    "url"   : "https://yikuansun.github.io/progenflares/photopea_plugin",
    "width" : 1000,
    "height": 500,
    "icon"  : "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/High-quality_lens_flare_rendering.png/1200px-High-quality_lens_flare_rendering.png"
}
```
I am, however, open to other ideas for formatting the plugin data.

I would very honestly be happy to develop plugins just for Photopea, as Photopea is my favorite free editor. I think that the plugins system has a lot of potential for making Photopea more customizable and welcome, but I think this feature would be utilized a lot more if it was more accessible for end-users.

If you would like, maybe I could write a little code snippet for this? Are there certain functions in your code that are used for you to easily be able to open popup boxes and menu options and whatnot?

**Comment by photopea** [comment]
I could add your plugin into Window > More > Advanced Flare. The Emoji plugin is aready there, it is not made by us.

Your plugin is great. You could detect the document size from Photopea using echoToOE() script. You could even show a preview right in Photopea, if you make a step back and add a new layer (with a script).

Once there are tens of plugins, we could make a public gallery of plugins, similar to PSD templates, which are added and used by users.

**Comment by mustafaGFX** [comment]
@yikuansun wants the normal user to get the plugins easily by just upload them, the normal users don't know what is JSON data .. honestly, it took me 2 days to figure out how to install plugins and it wasn't easy as a non-coding-educated person

Is it fair that only programmers or coding educated can use plugins?

**Comment by yikuansun** [comment]
@photopea Thanks for the feedback on my plugin! I have added the auto-detect document size and will try to do the advanced preview.

The plugin gallery sounds like a good idea!

**Comment by yikuansun** [comment]
> Once there are tens of plugins, we could make a public gallery of plugins, similar to PSD templates, which are added and used by users.

@mustafaGFX I think they're going to make a gallery of plugins just like the PSD templates, so that should be good for us!

**Comment by photopea** [comment]
Let me know when it is done and I can add your plugin into Photopea :) It would be great if your website looked good even in a smaller window.

**Comment by yikuansun** [comment]
@photopea I think I'm about done with it! I made the design more responsive and added a preview layer within Photopea. I initially had it update whenever values were changed, but this caused many performance issues, as users could update values much faster than Photopea could add the image, so I made the layer update on a button press rather than automatically.
I also slapped together an icon: [https://yikuansun.github.io/progenflares/icon.png](https://yikuansun.github.io/progenflares/icon.png) It is not the best icon, as I didn't really have an idea of branding for it, so if you want to replace it with your own, that would be fine.

**Comment by photopea** [comment]
Thanks for updating your plugin! I just noticed that you render it all with SVG, that is amazing!

Have you thought about letting the user to click on the preview, to choose the location of the flare? Photopea can do with the Lens Flare. Also, some sliders would be nice, instead of asking a user to type everything :)

**Comment by yikuansun** [comment]
@photopea Thanks for the suggestions! I hadn't thought about using mouse events for positioning; I added that feature, and it worked great. I haven't added sliders yet, but I will try to do so soon.

I have found a small robustness issue in the on-document preview. Currently, every time the preview is updated, I execute the following steps in order: add the new image, merge with the old one, and change the blend mode. However, `app.open` seems to be asynchronous - if I clump the scripts for adding/merging/changing blend mode together, the merging and blend mode change might finish before the new image is added. This is why I use a system of asynchronous functions that execute new scripts after catching the `done` message (I wrote a small wrapper for this, [https://github.com/yikuansun/PhotopeaAPI/](https://github.com/yikuansun/PhotopeaAPI/)). This works most of the time, but there is a low occurrence of the `done` message from the `app.open` being received early. Because this happens seemingly randomly in my eyes, I cannot say for sure the situations for this happening. Do you think there is a way to execute the scripts in order without this any chances of this problem? Thanks!

**Comment by photopea** [comment]
That is right. If your script has two lines of code, the first line is app.open(), the second line of a script is executed before the opening is finished.

But the "done" should be called correctly, only when the loading is done. Can you show me an example, where "done" is called at a wrong time?  There is "done" for finishing a script, and "done" for loading a document.

**Comment by yikuansun** [comment]
Here is a screen recording:

https://user-images.githubusercontent.com/38194363/119836859-11709d00-bed0-11eb-9603-db9657123df2.mov

The expected outcome is I add a new lens flare and merge it with the old one, which usually works, but this time the old lens flare merges with the layer below it and the new lens flare is added afterwords. I looked in developer tools and it didn't have any errors.
Do you think you could make `app.open` synchronous in a script? Or do you think there is there a workaround?

**Comment by photopea** [comment]
Are you giving Photopea a file as the URL / URI? Could you send it as an ArrayBuffer with the PNG image instead? That would work synchronously (but with two messages).

**Comment by yikuansun** [comment]
> Are you giving Photopea a file as the URL / URI? Could you send it as an ArrayBuffer with the PNG image instead? That would work synchronously (but with two messages).

I tried this method. It worked synchronously, but the image from the array buffer opened in a new document, rather than as a smart object in the original document. Is there a way to prevent this? If not, I can just try to make the best out of `app.open`; I could actually get rid of the bug completely by removing the blend mode change, though in my opinion the blend mode change is helpful.

I changed my system to remove the old image by reverting to a saved history state, as you originally suggested (the reason why I was using merging earlier was because I had trouble figuring out how to use history states). This makes the history look much cleaner and it is also safer because adverse effects will be reverted.

**Comment by photopea** [comment]
an arraybuffer will open a new document, but you can run a script, that will copy a layer from the new document into a previous document, and will close the new document.

Even if you open with app.open(), wait for the correct "done" (there will be two) and you should be good to go with another script. I think you are not counting "done"s properly in your video.

**Comment by yikuansun** [comment]
I'm not sure... I think I count the dones correctly because I use an asynchronous function for each script which creates an event listener and deletes it after "done." This works most of the time, it's just seemingly random blips where the order ends up being wrong. I'll keep working on it and if I will contact you if I make any improvement or find out the problem.

In the meantime, I will work on a particle simulation plugin similar to those in cinematic VFX softwares. I think this can be good for both photo manipulation and graphics creation.

**Comment by photopea** [comment]
You can make multiple filters, which share the Photopea integration. If you improve your integration code, it will be improved for all your filters.

It would be great, if you show me a short piece of code, which demonstrates the incorrect behaviour of Photopea, at least once, if repeated many times.

**Comment by yikuansun** [comment]
@photopea 
Here is how I have defined `Photopea.runScript` (full JS library at https://github.com/yikuansun/PhotopeaAPI/blob/master/photopea.js):
```
    async function(contentWindow, script) {
        var myPromise = new Promise(function(resolve, reject) {
            var outputarray = [];
            var messageHandle = function(e) {
                if (e.source == contentWindow) {
                    outputarray.push(e.data);
                    if (e.data == "done") {
                        resolve(outputarray);
                        window.removeEventListener("message", messageHandle);
                    }
                }
            };
            window.addEventListener("message", messageHandle);
        });
        contentWindow.postMessage(script, "*");
        var returnedMessage = await myPromise;
        return returnedMessage;
    }
```
As you can see, this sends a message to Photopea, then waits for "done," collecting all responses up until it, and deleting the event listener once "done." Since this function is asynchronous, we can wrap it in an asynchronous function and use `await` to run it "relatively synchronously" (same result as using `.then()`):
```
(async function() {
    await Photopea.runScript(window.parent, `app.open("https://www.photopea.com/api/img2/pug.png", null, true);`);
    await Photopea.runScript(window.parent, "app.activeDocument.activeLayer.translate(20,20);");
})();
```
This code is fundamentally the same as what my plugin runs. I'm not sure why, but my plugin usually runs the scripts in the right order, with maybe a 20% chance of failure, but as far as I've seen this snippet never runs them in the right order. Please let me know if I've made a mistake in my function or the snippet that I've sent, I suppose there is always that possibility 😅 

I hope this helps give a clearer picture of the problem!

**Comment by photopea** [comment]
I am not very familiar with Promises and "async" / "await". Maybe these demos could help you: https://photopea-api-demo.glitch.me/ - look at their source code.

**Comment by hxim** [comment]
@photopea Hi I confirm it is not working. I added exactly this case to https://photopea-api-demo.glitch.me/demo3.html and it is sending done too early it seems. See this sceenshot or try yourself there. Just open pea.psd and click BUTTON and you will see it in history it is executed in wrong order.
![screen1](https://user-images.githubusercontent.com/6370548/120323054-5ee07600-c2e5-11eb-83dd-e1184554aa39.png)

**Comment by photopea** [comment]
According to the current API, Photopea sends "done" when the script finishes, and when a document is added to Photopea.

Your just send Photopea a script, and when it finishes, you move the current layer. But a finished script does not mean that a document was added. You should wait for the second "done" message.

**Comment by hxim** [comment]
>  You should wait for the second "done" message, if you want to move a smart object made by your script.

@photopea 
Hi I just modified https://photopea-api-demo.glitch.me/demo3.html so it waits for two "done" messages but it is not working either. There is no second "done" message - it looks like photopea sends only one "done" after calling
`postMessage('app.open("https://www.photopea.com/api/img2/pug.png", null, true);',"*");`
see screenshot:
![obrazek](https://user-images.githubusercontent.com/6370548/120328808-7d497000-c2eb-11eb-9f03-76d53d314265.png)

**Comment by photopea** [comment]
Oh, you are right. According to the API, "done" is sent after a new document is opened. In your case, no document is opened (just a new layer is added).

Find another way to detect, if a smart object was loaded (e.g. check the number of layers with a script ever 50ms).

Also, you can open an image as a separate document, wait for two "done"s, and copy a layer to another document (with a script).

**Comment by hxim** [comment]
OK I updated https://photopea-api-demo.glitch.me/demo3.html to check the number of layers with a script ever 50ms.
It is much more complicated but it is working.
Current working version:

```
     var countLayersScript = "function cnt(d) { var r=0; if (d.layers) { for (var i=0; i<d.layers.length; i++)  r+=cnt(d.layers[i])+1; } return r; } app.echoToOE(\"layerCount=\"+(app.documents.length == 0?0:cnt(app.activeDocument)));"
      var layerCount, loading = false, wnd, timer;
      function iframeLoaded(pp) {
        wnd = pp.contentWindow;
        window.addEventListener("message", ppReady);
      }

      function waitAndCheckLayersCount(ms) {
        window.setTimeout(function() { console.log("sending count layers script"); wnd.postMessage(countLayersScript, "*"); }, ms);
      }

      function ppReady(e) {
        console.log(e);
        if (loading && e.data.indexOf("layerCount=") == 0) {
            var count = parseInt(e.data.substring("layerCount=".length));
            if (layerCount == null) {
                layerCount = count;
                console.log('sending: app.open("https://www.photopea.com/api/img2/pug.png", null, true);');
                wnd.postMessage('app.open("https://www.photopea.com/api/img2/pug.png", null, true);',"*");
                waitAndCheckLayersCount(50);
            } else {
                if (count != layerCount) {
                    loading = false;
                    console.log('sending: app.activeDocument.activeLayer.translate(20,20);", null, true);');
                    wnd.postMessage("app.activeDocument.activeLayer.translate(20,20);","*");
                } else {
                    timer++;
                    console.log("waiting for "+(timer*50)+" ms");
                    if (timer < 300) waitAndCheckLayersCount(50); else loading = false;
                }
            }
        }
      }
      function buttonClick() {
        if (loading) return;
        layerCount = null;
        loading = true;
        timer = 0;
        console.log("sending count layers script");
        wnd.postMessage(countLayersScript, "*");
      }
```

**Comment by photopea** [comment]
You can also send images to Photopea as ArrayBuffers, it works synchronously in real-time.

**Comment by mustafaGFX** [comment]
you know what!
I think I will learn javascript ❤️

**Comment by yikuansun** [comment]
> OK I updated https://photopea-api-demo.glitch.me/demo3.html to check the number of layers with a script ever 50ms.

Version using my library:

```
            var layers_count = (await Photopea.runScript(window.parent, `
                function cnt(d) { var r=0; if (d.layers) { for (var i=0; i<d.layers.length; i++)  r+=cnt(d.layers[i])+1; } return r; } app.echoToOE(cnt(app.activeDocument));
            `))[0]; // Script thanks to @hxim
            var layerCheckInterval = setInterval(async function () {
                var new_layers_count = (await Photopea.runScript(window.parent, `
                    function cnt(d) { var r=0; if (d.layers) { for (var i=0; i<d.layers.length; i++)  r+=cnt(d.layers[i])+1; } return r; } app.echoToOE(cnt(app.activeDocument));
                `))[0]; // Script thanks to @hxim
                if (new_layers_count == layers_count + 1) {
                    clearInterval(layerCheckInterval);
                    console.log("Image has been added");
                }
            }, 50);
            await Photopea.runScript(window.parent, `app.open("${imageURI}", null, true);`);
```

**Comment by yikuansun** [comment]
Hi @photopea,

Do you think you could make a prototype plugin gallery? I could upload my lens flare plugin, which now has features such as low quality preview to improve performance, draggable control points for light center/point to, drag input boxes left and right to decrease/increase value, and save/upload preset. I could also upload the stock photo plugin that I use in my personal environment:
```
            {
                "name"  : "Pexels",
                "url"   : "https://www.pexels.com/",
                "width" : 400,
                "height": 500,
                "icon"  : "https://www.pexels.com/assets/icons/pexels-icon-644533b609157fd990b1a6675626d63077ae1fb81e819c83f81dc2242877d413.png"
            },
```
Plugins such as these, though not developed for or integrated with Photopea, are very useful in my opinion. I use Photopea for photo manipulation and I very often go to Pexels to get the stock photos, and it is nice to be able to open the site very quickly from Photopea.
[Chartmaker](https://github.com/hxim/ChartMakerPlugin) could also be in the plugins gallery

I predict that once the plugin gallery is implemented, more people will notice the plugins feature and therefore more people will make plugins.

**Comment by photopea** [comment]
In Photopea, all plugins in Window - More - .... are external plugins (not part of Photopea). We added the QR Code Maker pluin today.

There are not that many people making plugins, so if you have a nice plugin, I can manually add it into Window - More ... for now.  Your Flare plugin is a bit weird to me. I think most of people would be confused by so many settings. Could you provide 5 - 10 predefined settings instead (with good names), and allow only changing positions and 2 -3 main colors?

**Comment by mustafaGFX** [comment]
@photopea 
the lens flare plugin isn't finished yet, we still have a lot of improvements and ideas to do, maybe you think it's wired because of Lots of settings, and it's not resizeable yet, we may layout these setting in just 4 or 5 windows, eg (look, lens, rays, location)

the mentioned improvement by @yikuansun was in the backend and some of them aren't noticeable by a normal user, I think the plugin will be perfect very soon, it will be the greatest plugin have ever made for photopea :)

**Comment by yikuansun** [comment]
> There are not that many people making plugins, so if you have a nice plugin, I can manually add it into Window - More ... for now.

I think that because of the lack of UI for adding plugins, users may not know of the option even if they have ideas for plugins. I only heard of Photopea plugins when randomly looking through the API section of the blog, and I feel like I'm one of the only people who does that 😅  
A plugin gallery will not only show that making plugins is possible, but it will also make uploading them much more convenient. 
I think it would be beneficial for Photopea to have a strong plugins system for a few main reasons:
 - **Crowdsourcing** - since Photopea is not open source, a great way for users to contribute to the software they know and love is to make plugins. I remember a very old issue asking where the source code was. There will also be less people opening feature requests and more people actually making features. I think this concept is related to the success of GIMP.
 - **Customization** - users of Photopea can choose what plugins to use
 - **Marketing** - if someone runs across a page or repository for a Photopea plugin, they will probably look into Photopea. Also, plugins would make Photopea more powerful, also making it more attractive to users.
Also, regarding "there are not that many people making plugins," I think that not all of the plugins have to be specifically made for Photopea. For example, people can make plugins out of stock image or asset sites that they often visit while editing (as I mentioned earlier, I do this with Pexels). Also, it is very easy to "port" separate web apps to Photopea plugins. My lens flare plugin was actually originally a standalone app, but I used query string to check if the app is being used normally or in Photopea, and modify the DOM and other functionality as such. All of this potential would be much more used if people knew about plugins and if plugins were easy to upload.

> Your Flare plugin is a bit weird to me. I think most of people would be confused by so many settings.

Regarding making a simpler interface, I understand your point, but my vision was to make a very customizable system that beginners and advanced users can all be satisfied by. This is why I felt that it was so important to make the flare completely procedurally generated, using raw shapes instead of pre-rendered textures - I wanted there to be many options. I do, however, see your argument and I think that your suggestions of better labels and presets would definitely be beneficial. However, I would try to add these without removing any of the more advanced options. If you have any suggestions in this area, I'd be happy to hear them :) As @mustafaGFX said, we are actively working on improving the plugin.
I could also add a short documentation or tutorial video (currently my Github README says stuff like "fill out the input boxes" 😅 )

**Comment by mustafaGFX** [comment]
I have a very important thing to say, maybe the options in the plugin aren't too many as you think, they are just not arranged in the way that feels you it's clean or simple, I believe everything can be complex if you make it unarranged, I also believe that working on technical things before working on the user experience and user interface gives you so much better result, let's not judge the plugin for now.... we all will be surprised too soon :)

BTW, plugin gallery would be so much better, which anyone can choose what plugin he wants

**Comment by photopea** [comment]
I want to put plugins into Window - More - ... for now. If there are more than 20 plugins, I will add a gallery, where you can enter a description of a plugin, a thumbnail, etc. (similar to PSD templates).

Contact me directly, when you want your plugin to be added.

**Comment by mustafaGFX** [comment]
@photopea 
It looks fare

**Comment by yikuansun** [comment]
Hi @photopea ,

Could you make a simple dialog box where people could upload the JSON file for a plugin just for their own usage? This could perhaps be opened through `Window -> Load 3rd Party Plugin` or something similar. I have worked a lot on my lens flare plugin and would like to be able to distribute it. This would also make testing easier for developers. Also, I feel like some people might not realize that they can develop plugins (which is true in a way), and seeing this option will inform them.

Thank you!
