### ISSUE TITLE
Make default size of image Fit The Area in these windows

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3289]
Image has been displayed 100%(Pixel to Pixel) in these windows now. part of image is out of view while working with high resolution images on low resolution screen. 

1. Reduce colors
2. Vectorize bitmap
3. Filter Gallery
4. Liquify
![Screenshot_20210522_083434_com android chrome](https://user-images.githubusercontent.com/79258245/119209360-bc501800-bad8-11eb-83c0-44c64df46263.jpg)

And in these other windows, image isn't displayed as large as possible. The scale level is chosen from "... 25% > 33.33% > 50% > 66.67% > 100% ..." now. 

1. Refine edge
2. Magic cut
![Screenshot_20210522_083452_com android chrome](https://user-images.githubusercontent.com/79258245/119209417-15b84700-bad9-11eb-8c3b-e9006a77f57d.jpg)

It would be more comfortable that make the image Fit The Area so that we will be able to get image as large as possible while the full image is in view.

**Comment by nothingshiru** [comment]
Besides, I had replied in some closed issues. I don't know if you will notice them. 
Just to remind you
#3247 
#3256 
#3279

**Comment by photopea** [comment]
Hi, I set those windows to the "adapted" default zoom.

Sadly, right now, we support only zoom values of N, or 1/N or 2/N, for an integer N. You can have 50% or 33%, but nothing in between.

**Comment by nothingshiru** [comment]
> Sadly, right now, we support only zoom values of N, or 1/N or 2/N, for an integer N. You can have 50% or 33%, but nothing in between.

Thanks for explaining. I get it.
