### ISSUE TITLE
problem with long name of layer

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#329]
I renamed layer to 
"Lorem ipsum dolor sit amet, ei vim apeirian rationibus, mea elitr intellegam conclusionemque at. Sumo elitr consulatu ei per, no aliquam omittam mel. Has eu ubique rationibus, munere viderer numquam ad sit. Justo dissentiunt his id, novum dolore ea mea. Altera invenire consulatu te sea."
(this is more than 256 characters)
Then I saved as PSD to my computer.
Then I tried open that file form my computer - it failed...

**Comment by photopea** [comment]
You are right, PSD contains layer names also in so-called Pascal strings, where the length of the string is stored in 1 byte. Now, names longer than 255 characters will be trimmed to 255 characters.
