### ISSUE TITLE
Feature Request: Display panels in one volume when width of sidebar is over N% of width of page

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3290]
In portrait mode of my phone, panels are displayed in one volume. On my tablet, they are displayed in two volumes. The size of my tablet screen is bigger, but I still don't think it's big enough. Therefore I prefer panels to be displayed in one volume in portrait mode on my tablet. 

How about displaying panels in one volume when width of sidebar is over N% of width of the page? For my devices, 12.5%(1/8) might be good. 
![Screenshot_20210522_201810_com microsoft emmx](https://user-images.githubusercontent.com/79258245/119228023-81cf9500-bb43-11eb-8ec4-89add8068696.jpg)

Or there is better solution?

**Comment by photopea** [comment]
I changed the mechanism of the default look. It should work better now.

BTW. do you know that you can expand and collapse these panels with <> and >< ?

**Comment by nothingshiru** [comment]
Panels are still displayed in two volumes. 
![Screenshot_20210524_203801_com android chrome](https://user-images.githubusercontent.com/79258245/119349213-78bffe80-bcd0-11eb-81a7-6e025dbbfcc1.jpg)


> BTW. do you know that you can expand and collapse these panels with <> and >< ?

I know that. Why do you mention that here?

**Comment by photopea** [comment]
Oh, now it should be fixed.
