### ISSUE TITLE
Straighten option for Crop Tool

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3291]
Hi, 
i have recommended Photopea on some portal and one of the user has said that he tested it but it found some function that he use a lot and it isn't in Photopea. Straighten option for Crop Tool.
Some time ago I have added issue for straighten layer with free transform in ruler tool. But If someone is for example Photographer, he works mostly on one layer and first step of editing is to straighten the photo.

Can you add that feature for crop tool? After clicking in button it should appear ruler like in ruler tool. But the whole image should rotate - not layer only.

**Comment by photopea** [comment]
Sure, I added this option :)
