### ISSUE TITLE
Slowdown after 50+ layers

### ISSUE THREAD

**Issue by quantuminformation** [photopea/photopea#3292]
In FF its become unusable at this many layers, any tips to improve the speed?

![image](https://user-images.githubusercontent.com/216566/119273528-a42ce580-bc0b-11eb-8a84-a896a3607e6d.png)

In safari it seems fine.

**Comment by photopea** [comment]
If it runs slowly in Firefox, but runs fast in other browsers, I think it is a bug in Firefox. Is your firefox updated? Could you disable some browser exetnsions in Firefox? Is WebGL on? Check in More - Use WebGL.

**Comment by photopea** [comment]
I have to close it because of lack of details. We can keep discussing it in a closed issue.
