### ISSUE TITLE
Issue: Can't change width of sidebar by finger properly

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3294]
There's same problem like #3067 

https://user-images.githubusercontent.com/79258245/119298877-7a69d200-bc90-11eb-9180-8ce4cf583ba0.mp4

**Comment by photopea** [comment]
If we made the touch area larger, it would look ugly. It is 3px now. I think people who are serious about photo editing should get a mouse.

**Comment by nothingshiru** [comment]
It's not about whether the sidebar is easy to drag or not. I didn't request sidebar can be dragged easily. 
The point is what's going on while I was dragging sidebar. 

You have fixed similar issues in #3067 #3135 . There's nothing visible changed.
