### ISSUE TITLE
I can't edit any layer

### ISSUE THREAD

**Issue by Leggo87** [photopea/photopea#3295]
![image](https://user-images.githubusercontent.com/73044361/119299657-b7ed4180-bc35-11eb-821e-1750e7cac812.png)
I spent 2 hours trying to bypass this and I have no luck. Not sure if I am doing something wrong, since I read and followed every step in every tutorial I saw but I couldn't edit a single layer. 

I just want to draw normaly, but I can't.

**Comment by MichalSZZ** [comment]
1. You have a Shape layer - you can't draw on that type of layer. Shape, Smart Object, Text layer, locked by padlock layer - aren't editable

2. You have a Pencil tool with 0% opacity. Even if you create empty raster layer for drawing - everything what you will draw will be invisible until you set the tool opacity bigger than 0%

3. What is strange for my on your screenshot? Shape on background layer should to have fill - you don't have...

**Comment by photopea** [comment]
I think when you drew the ellipses, you set the Fill to "none" and the Stroke to "none".

You can learn how to use Photopea at www.Photopea.com/learn

**Comment by MichalSZZ** [comment]
> 
> 
> I think when you drew the ellipses, you set the Fill to "none" and the Stroke to "none".
> 
> You can learn how to use Photopea at [www.Photopea.com/learn](http://www.Photopea.com/learn)

Hmm - I think that should to be fixed then...

thumbnail of that layer should to be empty - without fill in that case

**Comment by Leggo87** [comment]
The layers become unable to be editable after using eclipses, (I tried after some refreshing sleep) and it seems that, not sure if it is intended.

**Comment by Leggo87** [comment]
I tried lot of different thing but in the end I couldn't get pass working on an eclipse. It is a small inconvenience, but not ground breaking.

Thanks for the help!

**Comment by photopea** [comment]
What do you mean by an eclipse?

I really recommend spending some time learnihg how to use Photopea: www.Photopea.com/learn , so that we can at least understand each other.

**Comment by Leggo87** [comment]
Thanks for the advice. I will.
