### ISSUE TITLE
Can't move layers with move tool or arrows

### ISSUE THREAD

**Issue by alternate-dreamscape** [photopea/photopea#3297]
When I try to move layers up or down in a project, they stay in their original place. This happens when i move them using the arrow keys as well. How do I fix this?

**Comment by photopea** [comment]
Hi, are you using the Move tool? Could you show us a video of what is happening, or any description of how can we reproduce it?

**Comment by photopea** [comment]
Do you know what are empty (transparent) layers, and what is the "Auto-select" option of the Move tool?

**Comment by SarahEsteve** [comment]
same here ! can't move layers !

**Comment by SarahEsteve** [comment]
nor folders :/

**Comment by alternate-dreamscape** [comment]
> Hi, are you using the Move tool? Could you show us a video of what is happening, or any description of how can we reproduce it?

Here is a screen recording of the bug.

https://user-images.githubusercontent.com/84713868/119338944-4810a280-bc99-11eb-9f5d-9b16b0daa651.mp4

**Comment by photopea** [comment]
Oh, you mean moving layers in the Layers panel. I thought you mean moving layers on a screen with the Move tool.

It is fixed now, reload Photopea with Shift+F5 to make sure your browser is not showing you the old cached version.
