### ISSUE TITLE
Cannot move layer above or below another layer.

### ISSUE THREAD

**Issue by omega2275** [photopea/photopea#3298]
This bug has recently started where all the layers cannot be moved in the layer selection. I would try move "layer 5 copy" above layer "6" and the layer would just stay in the same location.
![image](https://user-images.githubusercontent.com/25404001/119338504-fe6b8c00-bc87-11eb-8708-c5abb56902e7.png)

**Comment by photopea** [comment]
It is fixed now, reload Photopea multiple times.

**Comment by omega2275** [comment]
I still have the issue after restarting!

**Comment by photopea** [comment]
I think your browser is showing you an old version. Clear the cache, or use Photopea on another computer, or in Incognito mode.
