### ISSUE TITLE
photopea crop canvas resize

### ISSUE THREAD

**Issue by digarteach** [photopea/photopea#3299]
Why does cropping only adjust canvas size and not actually crop the photo? I'm doing a kaleidoscope lesson and the steps require a photo to be rotated 60 and placed in the corner and then cropped. Then copies made to rotate around the center, but first we have to increase canvas size and when we do that the image reappears as if it were never actually cropped....

**Comment by photopea** [comment]
When you do cropping, you can enable "Delete Cropped Pixels" at the top. Is that what you need?

**Comment by photopea** [comment]
Does there exist any software, which does what you need, so that we can understand what you need?

**Comment by digarteach** [comment]
Photoshop... basically when you crop an image the part that gets cut should
remain behind the now reduced canvas..

this is the tutorial we use.
https://digital-photography-school.com/how-to-create-kaleidoscope-patterns-from-your-photos/
when you get to the step where you increase the canvas size the image just
reappears as if it were never cropped..

**Comment by photopea** [comment]
When you do cropping, you can enable "Delete Cropped Pixels" at the top. Is that what you need?

**Comment by digarteach** [comment]
yes! thank you so much. Also for replying very quickly.

**Comment by nothingshiru** [comment]
@photopea 
I notice that the pixels outside canvas won't be deleted when use the crop in top menu "Image", even though the "Delete Cropped Pixels" in crop tool is enabled.

**Comment by photopea** [comment]
@nothingshiru The Image - Crop is not related to the Crop tool and its settings.
