### ISSUE TITLE
Can't add vowels in arabic

### ISSUE THREAD

**Issue by AnonymoZ** [photopea/photopea#330]
Hello,
It's a bit weird what's happening:
When I paste Arabic with vowels into Photoshopea, I see spaces between the letters, but not when the Arabic has no vowels.

![untiktled](https://user-images.githubusercontent.com/24578655/32595454-731e9a86-c549-11e7-9b75-ddb84dfa15f9.png)

Try it:

وتتمنى لكم اسرة الموقع أجمل الأوقات

[A.Thuluth_p30download.com.zip](https://github.com/photopea/photopea/files/1456784/A.Thuluth_p30download.com.zip)

**Comment by photopea** [comment]
Hi, I just tried to paste your text into Photopea with your font and I see this:
![pea](https://user-images.githubusercontent.com/15955558/32601276-59a23e16-c542-11e7-8861-22d072756f00.png)

Is this right or wrong? If you have Photoshop, could you create a PSD file, that looks correct in Photoshop, but incorrect in Photopea?

**Comment by AnonymoZ** [comment]
Ok, lemme explain:
In English, that would look like: Hy! Wht's gng n hr?

To complete the meaning, you need **vowels**.
And in Arabic, it's the little things above and below the letters.

These are placed _on_ the letters, not next to them.

But what's happening in Photopea (for this font in particular, by the way, not the default font) is that it fails to put them exactly on the letters and instead, it puts them (where you're seeing them).

Here is a vowelled phrase (sorry for not giving you earlier):

الْجُمْلَةُ الاسْمِيَّةُ

And no, I don't use Photoshop (sorry about that).

**Comment by photopea** [comment]
Hi, Photoshop renders your string with your font like this, is this the correct way to render it?
![jwr4clp](https://user-images.githubusercontent.com/15955558/33138857-d7a8befc-cfab-11e7-9c20-4fb51d301ace.png)

**Comment by AnonymoZ** [comment]
Yes, this one's 100% correct.

**Comment by photopea** [comment]
Hi, it should be fixed now (to some degree). The vowels are all in the same height.

**Comment by AnonymoZ** [comment]
Thanks a lot!
