### ISSUE TITLE
Glitchy

### ISSUE THREAD

**Issue by KittenLuvr7884** [photopea/photopea#3301]
When I tried to save my gif it was going really slow and I could not save it very easily I had to wait at least a minute or two before it loaded

**Comment by photopea** [comment]
Hi, what is the width and the height of your GIF, and how many frames does it have?

**Comment by toscik-why** [comment]
nie mogę zapisać bo zapisuje poprzednią prace

**Comment by photopea** [comment]
I have to close it because of lack of details. We can keep discussing in a closed issue.
