### ISSUE TITLE
Issue: Too many colors have been sampled while scrolling on image with Eyedropper tool

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3302]
To sampled color with finger, our finger always have to scroll on image until we touched the area in where the color we want is. But when we do that, there are too many colors would be sampled into swatches. 

I think colors should be sampled into swatches only when finger is off the screen. 

https://user-images.githubusercontent.com/79258245/119603063-0f9ad100-be1f-11eb-814d-831bb3046120.mp4

**Comment by nothingshiru** [comment]
I have tried same thing in Photoshop and noticed that there's nothing to do with finger. 

The color should be sampled into swatched only when released left buttong of mouse or finger.

**Comment by photopea** [comment]
I fixed it. Hope nobody will complain about the new way it works.
