### ISSUE TITLE
Screen will suddenly freeze up and not allow me to use paintbrush or eraser.

### ISSUE THREAD

**Issue by femboycheems** [photopea/photopea#3303]

**Comment by photopea** [comment]
It never happened to me. What should I do to make it happen?

My guess is, that you do it on a phone with low RAM, and your document is too large. Is that right?

**Comment by femboycheems** [comment]
No, I do it on a Dell chromebook. Document is a PSD file that is 12 mb. I can do a bit of editing, like one line with the brush, but then it will freeze and I have to save, close the website, and upload the file again.

**Comment by photopea** [comment]
Could you open your PSD and press Window - More - Memory? How much memory is used?

Also, how much RAM your Chromebook has? Is your Chromebook software updated?

**Comment by femboycheems** [comment]
The file takes up 12 mb. Chromebook has 4 gb of RAM and was updated this morning.

**Comment by photopea** [comment]
And what about the Memory window in Photopea?

čtvrtek 27. května 2021 femboycheems ***@***.***> napsal(a):

**Comment by femboycheems** [comment]
It says 46.2 MB RAm and 46.2 MB GPU. Sorry for my late reply.

**Comment by photopea** [comment]
That is quite small. Does the problem still happen if you use Photopea in Incognito mode?

**Comment by femboycheems** [comment]
I am working on a school chromebook that does not allow me to use incognito, so I can't try it.

**Comment by photopea** [comment]
Could you record a video of what you do? Because no matter what I try, I can not make such problem happen.
