### ISSUE TITLE
Issue: (Hold Ctrl and press / key) is working same as (Hold Ctrl and press + ) 

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3305]
Both of them are zooming out.

**Comment by photopea** [comment]
We did it because there is a Minus character on that key on a German keyboard.

**Comment by photopea** [comment]
https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/German-Keyboard-Layout-T2-Version1-large.png/1024px-German-Keyboard-Layout-T2-Version1-large.png
