### ISSUE TITLE
Issue: "Shift + Ctrl + N" would create a new layer below current layer

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3306]
Now it works same as hold Shift and click the new layer button in Layer panel. It shouldn't be like that.

**Comment by photopea** [comment]
It seems like Shift+Ctrl+N always opens a new incognito window in Chrome, I am afraid we can not change that :(

**Comment by nothingshiru** [comment]
You can do it in full-screen mode or press "Shift+Ctrl+Alt+N".

**Comment by photopea** [comment]
So Shift+Ctrl+Alt+N creates a new layer below a current layer, in a regular mode. 

Also, Shift + Ctrl + N in fullscreen creates a new layer below a current layer.

What shortcut would you like to have and for what?

**Comment by nothingshiru** [comment]
By this shortcut, I would like to create new layer above current layer instead of below.

**Comment by photopea** [comment]
Ok, done :)
