### ISSUE TITLE
Can't edit Text

### ISSUE THREAD

**Issue by Marqqz** [photopea/photopea#3307]
Whenever I save my work as PSD, and open them again. All my texts can't be edit for some reason, is there any way to fix this?

**Comment by mustafaGFX** [comment]
@Marqqz 
I think your internet is slow..... when you open the PSD again it takes a little bit of time to load the used font... try to connect to a faster network or use a local storage font

**Comment by Marqqz** [comment]
I pressed 'Open From Computer' Opened my PSD File and when after it's done loading, all my text doesn't have the Text icon anymore besides their names. I can't also edit them anymore. And I'm not sure if my internet connection has something to do with this since this has been happening to me a lot now.

**Comment by photopea** [comment]
I think you saved your document as a JPG. JPG files do not have text layers, they have just one layer.

Could you record a video of what you do and what happens, and what would you like to happen instead?

Also, it is possible, that some of your browser extensions are modifying files before they are saved to a hard disk. Have you tried to do the same thing in Incognito mode? The incognito mode is the only way to prevent your extensions interfering with your work.

**Comment by photopea** [comment]
I have to close it because of lack of details.
