### ISSUE TITLE
Crop Tool - ALT in fixed ratio option don't scale from center 

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3308]
With Alt button it change to free transformation of cropping area. It is a bug only in Fixed Ratio

**Comment by photopea** [comment]
I see, that if you drag the corner of the cropping rectangle with alt, with the Fixed Ratio enabled, the ratio is not preserved. Is that what you mean?

**Comment by MichalSZZ** [comment]
Yes exactly. Just how it works in any other option i  crop or any other transformation (for example in free transform tool)

**Comment by photopea** [comment]
fixed :)
