### ISSUE TITLE
I can't scroll through a project when zoomed in, the filter gallery menu is glitched, there's this shadow thing that takes up part of the properties menu, the tool menu is out of order and glitched, I can't even select anything

### ISSUE THREAD

**Issue by gyatmaster** [photopea/photopea#3309]

**Comment by photopea** [comment]
I do not observe such thing when I open www.Photopea.com . Is your web browser updated? Photopea does not work well in browsers that are more than ten years old.

**Comment by photopea** [comment]
I have to close it because of lack of details. We can keep discussing in a closed issue.
