### ISSUE TITLE
Start Photopea from Home Screen

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#331]
let's implement it, if the web allows it.

**Comment by landsman** [comment]
... and tutorial / one click way for create MacOS dock icon / Ubuntu doc icon :)
Great could be window without "URL address" bar as can I see on zive.cz screenshot...

**Comment by landsman** [comment]
Here is prepared icon for Mac OS:
[Photopea.zip](https://github.com/photopea/photopea/files/1457870/Photopea.zip)

**Comment by landsman** [comment]
https://www.64k-tec.de/2010/11/creating-file-shortcuts-on-three-different-operation-systems/

**Comment by photopea** [comment]
We added an option More - Install Photopea. But it does not work in all browsers now. We should look at it again in the future, once the standard is more stable.

**Comment by landsman** [comment]
Yeah, don't work on macOS :/

**Comment by photopea** [comment]
What about Three dots - Další nástroje - Přidat na plochu?

**Comment by landsman** [comment]
![snimek obrazovky 2017-11-13 v 21 29 49](https://user-images.githubusercontent.com/3184228/32747677-cde8cc20-c8b9-11e7-8394-70cbd7f69dd3.png)
