### ISSUE TITLE
Filter - Avarage Blur - wrong results (brighter than it should to be)

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3310]
Today I want to do lesson about "fake" low-poly design (polygonal lasso tool and Blur Avarage).

But something work wrong for me. Look place with triangle seletion:
![obraz](https://user-images.githubusercontent.com/38118273/119797890-f192a680-beda-11eb-8dc0-f27e125f1968.png)
and the result:
![obraz](https://user-images.githubusercontent.com/38118273/119797996-0a9b5780-bedb-11eb-9a07-a9436c6650ff.png)

the same place in Photoshop look OK:
![obraz](https://user-images.githubusercontent.com/38118273/119798244-40d8d700-bedb-11eb-99cc-a3d759cc6ead.png)

now I'm only testing how Photopea can do that... but at 4pm I have a lesson :) If that is something hard, I can make something else for my students - don't worry :)

**Comment by nothingshiru** [comment]
I downloaded your images and tried Average blur in Photopea. My result is similar to the result in your Photoshop. 
![119797890-f192a680-beda-11eb-8dc0-f27e125f1968](https://user-images.githubusercontent.com/79258245/119811080-47863f00-bf19-11eb-8904-818ee6751d45.jpg)

https://www.photopea.com/#iu3UYBo6O

**Comment by MichalSZZ** [comment]
On my computer there is something wrong look: https://youtu.be/iH1iD58_1Y8
@photopea do not close this issue - I will test it later with my students on different laptops.

**Comment by photopea** [comment]
Fixed, thanks for reporting :)

It did not happen for a content in a separate layer. It happened only when a filter is applied to a selected part in a bigger layer.

**Comment by MichalSZZ** [comment]
@photopea thank you! for the moment I was thinking that I'm crazy ;)

**Comment by MichalSZZ** [comment]
@photopea I don't want to make new Issue because it is related with your fix.

Now Average work good. But around selection there is 1px transparent area.  Few hours ago there wasn't that problem. I'm working on one layer with many triangle selections. And after I make one I use Average blur. Then around the effect appear the transparency. It is a bug. 

How does it look now:
![obraz](https://user-images.githubusercontent.com/38118273/119847634-6ed60f80-bf0b-11eb-966a-25fa24ebff3a.png)
how was a few hours ago:
![obraz](https://user-images.githubusercontent.com/38118273/119847764-8d3c0b00-bf0b-11eb-835b-a59e2f2dd5e5.png)
there are some lines (not blurred) but it was because of very fast and not so precise selecting

Once again thanx for fixing the Average bug. You can see eyes and other dark elements how it look now and before your fix. (but now is another bug with transparency around selection)

**Comment by photopea** [comment]
Ouch, I am very sorry :( it is fixed now.

**Comment by MichalSZZ** [comment]
My students are very impressed about speed of your work :)

Thank you very much!
