### ISSUE TITLE
how to remove the chequered background of transparent images

### ISSUE THREAD

**Issue by thaynos** [photopea/photopea#3311]
exactly what it says in the title. 
ive gone to view>show>grid/pixel grid and turned both off with no change
![image](https://user-images.githubusercontent.com/83282129/119808992-b6ea3780-bef5-11eb-88c4-4c7c72b731ae.png)

**Comment by photopea** [comment]
Hi, if your images have a background, they are not transparent.

You can use e.g. Magic Cut to remove background form images: https://www.photopea.com/tuts/magic-cut-remove-image-background-online/

**Comment by photopea** [comment]
This image has no transparency, it is a JPG image. Just because something has white and gray squares, does not mean it is transparent.

![image](https://user-images.githubusercontent.com/15955558/119820835-2fe79000-bef2-11eb-9fc0-edcb758e4ba0.jpg)
