### ISSUE TITLE
importing psd to other apps

### ISSUE THREAD

**Issue by thaynos** [photopea/photopea#3312]
i dont know why but when importing psd from photopea to gimp it shows up as curropted in gimp. but if i open the psd using photopea it shows up properly. isnt there a way to make the psd work cross-apps?

**Comment by photopea** [comment]
There was a bug in GIMP in loading PSD files. https://gitlab.gnome.org/GNOME/gimp/-/issues/6659

Can you update your GIMP?

**Comment by photopea** [comment]
I think the problem should be fixed in the latest GIMP. But let me know if it still does not work.
