### ISSUE TITLE
Aligning layers horizontally cause them to move A LOT

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3314]
when i select to layers and use the alignment buttons both layers move to the right, in stead of aligning.

Here is a video:

[Screen recording 2021-05-28 00.00.57.zip](https://github.com/photopea/photopea/files/6558099/Screen.recording.2021-05-28.00.00.57.zip)

**Comment by photopea** [comment]
Hi, I could not reproduce such behaviour. Could you show me your PSD?

**Comment by avagp** [comment]
Ok, i could not reproduce it again, BUT

I discovered another problem: the adjustment layer -> Color Fill propagates itself towards all artboards.

You can check it when trying to transform it.

![image](https://user-images.githubusercontent.com/11801254/120088534-8655f980-c0bf-11eb-8a37-40b10173d777.png)

**Comment by photopea** [comment]
It should work like Adobe Photoshop now.  A color fill layer has no transform rectangle.

**Comment by avagp** [comment]
I could reproduce it again.

But when i close photopea, and open again, i cannot.

**Comment by photopea** [comment]
The problem is, that if you select specific knots of a shape layer, the size of the shape layer is the size only of these selected knots.

I fixed it. Whenever you click on anything the Layers panel, all selected knots of all shape layers are forgotten.
