### ISSUE TITLE
BUG: Artboard - Duplicating into an artboard gets all layers messed up

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3315]
This i show i have the work on another project:
![image](https://user-images.githubusercontent.com/11801254/119931425-5ee01f00-bf4f-11eb-9d66-7faf9d0e909a.png)

Here it gets after being duplicated into an artboard:
![Screenshot 2021-05-28 00 54 50](https://user-images.githubusercontent.com/11801254/119931458-6ef7fe80-bf4f-11eb-96d3-edb76e47c694.png)

**Comment by photopea** [comment]
I really need some PSD to see it.

**Comment by avagp** [comment]
[Archive (3).zip](https://github.com/photopea/photopea/files/6565507/Archive.3.zip)
Here it is.

Open both.

Select all layers, but the background on Logo Cultura, select Duplicate into Cartas Cultura - Artboard Back

**Comment by photopea** [comment]
I was a bit lazy once, when implementing one feature, and it resulted in this bug.

I am very sorry, I did it properly this time, and it should work correctly now.

**Comment by avagp** [comment]
Thank you Ivan, you everything but lazy man.

Your work give us users a great tool to keep working.

Thank you very much for your care!
