### ISSUE TITLE
BUG: Artboards - You cannot reorder artboard folders!

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3316]
If i create an artboard, and then a second one.

i cannot move the folder of the second one to the primer, because it disappears!

And if i get them order again, i get them merged!

Here is a video:
[Screen recording 2021-05-28 01.00.13.zip](https://github.com/photopea/photopea/files/6558273/Screen.recording.2021-05-28.01.00.13.zip)

**Comment by photopea** [comment]
I am sorry, it is fixed now.
