### ISSUE TITLE
Guides no longer showing up

### ISSUE THREAD

**Issue by MeiliTT** [photopea/photopea#3317]
There appears to have been an update recently. Since then, I haven't been able to get the guides to show up.

**Comment by photopea** [comment]
Hi, can you enable View - Extras, and View - Show - Guides? Does it help?

**Comment by MeiliTT** [comment]
Yes! That was it. Thanks!

**Comment by photopea** [comment]
No problem! Also, it is enabled automatically, if you try to make a new guide.
