### ISSUE TITLE
Request: Make Name/filename text entry box wider

### ISSUE THREAD

**Issue by cloudcathedral** [photopea/photopea#3318]
Hi there,

Love the tool, but have one small request - 

Is it possible you could make the text entry box where you set the Name: to be wider?

It's quite short currently, only around 13 characters.

I frequently need to rename files to download variations, etc - usually the end of the filename, which is almost always cut off, and the small window means a lot of scrolling is required to change any text to the right.

Thanks

**Comment by photopea** [comment]
Hi, do you mean in File - New? I made it a bit wider.

**Comment by nothingshiru** [comment]
@photopea 

I think this window need to be wider too. (Double click on document's name) 
![screenshot_20210529_223042](https://user-images.githubusercontent.com/79258245/120074087-d340cc80-c0cd-11eb-8c1c-fa4db99b417d.jpg)

**Comment by photopea** [comment]
Ok, I made it wider, too.
