### ISSUE TITLE
Improve loading screen

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#332]
What about some simple "reset.css" for loading screen?
In Safari it looks little bit crazy:

![snimek obrazovky 2017-11-09 v 14 43 38](https://user-images.githubusercontent.com/3184228/32608376-7886b00e-c55c-11e7-86df-6ff116f3120e.png)

**Comment by photopea** [comment]
Covering it all with something would only add an "overhead". The best solution would be to make loading faster, so the user can see the program immediatelly.

We put all tool icons into a single file: https://www.photopea.com/code/PIMG.js  and the loading seems to be faster. Maybe we can put all images into this file?

**Comment by landsman** [comment]
I think that regular files can be cached better than this file, do you test it?

**Comment by landsman** [comment]
First load in private window crashed on this:

![screen shot 2017-11-17 at 16 34 24](https://user-images.githubusercontent.com/3184228/32955092-4062a480-cbb5-11e7-9692-49dbc96db416.png)

**Comment by landsman** [comment]
Oh, second too. It is prepared for loading without saving any data to cookies etc? I think that there is some error. 

![screen shot 2017-11-17 at 16 36 12](https://user-images.githubusercontent.com/3184228/32955159-72a5e588-cbb5-11e7-9406-fe3851c130c1.png)

**Comment by photopea** [comment]
Hi, this is very strange, it never happened to me. Can you please update your web browser?

**Comment by landsman** [comment]
Updated, same. It's only in private mode.

**Comment by photopea** [comment]
The meaning of a private mode is, that the website should not be able to detect that it is private mode (and work the same as in non-private mode).

What version of Safari do you have? It should be fixed according to this: https://bugs.webkit.org/show_bug.cgi?id=157010

**Comment by landsman** [comment]
Version 10.1.2 (12603.3.8)

**Comment by landsman** [comment]
Try it in https://www.browserstack.com

**Comment by photopea** [comment]
Your version of Safari is not available in the free version of BrowserStack.

I see, that the latest Safari is the version 11. Apple says they will not fix any bugs in Safari 10. I recommend you to upgrade (somehow) or use another browser. We will never change our code just to avoid bugs in browsers. It is not right.

**Comment by landsman** [comment]
OK, I can upgrade just to macOS Hight Sierra.

**Comment by landsman** [comment]
After upgrade is private mod all right. 
Startup looking same:

![screen shot 2017-11-17 at 21 47 04](https://user-images.githubusercontent.com/3184228/32968329-2df5e7b8-cbe1-11e7-9f0d-45a4f18bade8.png)

**Comment by photopea** [comment]
But it is like this just for a second, right?

**Comment by landsman** [comment]
It's about internet connection. I recommend some black background, white centered spinner and hide animation. It could looking more professional.
