### ISSUE TITLE
export issue

### ISSUE THREAD

**Issue by Tushar559** [photopea/photopea#3320]
when i export photo in jpg file then the file download in text document

**Comment by photopea** [comment]
Hi, can you disable all your browser extensions and try it again? I think one of your extensions is renaming files.

**Comment by Tushar559** [comment]
i have two extensions 1st: free download manager 2nd: kaspersky Antivirus

**Comment by photopea** [comment]
I think "free download manager" is doing it. Try to ask the authors of your extension to fix it.

**Comment by Tushar559** [comment]
thanks for solving this issue
