### ISSUE TITLE
How to use mouse controls and keyboard in Mobile version of Photopea AND Photopea API tools ?

### ISSUE THREAD

**Issue by riazuddinshaik** [photopea/photopea#3321]
Hi Dear,

           A superb platform for many users across the world and we really feel greatful for this. I have a quick questions.

(1) How to use ctrl+mouseleft click in MOBILE version of photopea?

(2) If we integrate API in our website or android mobile application, Can we make customizations like we do not need all tools but we are in need of only tools to work in our application like warp, vector mask, brightness, contrast, layer mask, object selection.
Could we make customizations like above asked?

Please, reply sir as we are really in need of hour. Our whole project is depend on this customizations. We need only five or six tools to work on image in our mobile application. If possible, Please let us know how to move forward through email or openly on this GitHub platform as our developer worked very hard day and nights and just halted at final step. It would be really thankful not only for us but many users across the world.

looking forward for your reply sir...

Thankyou

**Comment by photopea** [comment]
Hi, many things are simply not possible to do without a keyboard or a precise mouse.

1) there is a virtual keyboard button at the bottom left corner. You can enable virtual Alt, Ctrl, Shift ... it is a temporary solution, until we come up with something better.

2) Yes, you can customize the UI through our API, remove tools, menus, etc. See here: https://www.photopea.com/api/environment

**Comment by riazuddinshaik** [comment]
Dear Sir,

      We really appreciate and thankful on quick reply. We really admire
your work.

Once again, A big thanks to you for giving such platform to us with
customisation.

Is there possibility of virtual mouse same like as you said virtual
keyboard?

Really looking forward to hearing from you

Sincerely yours,
Riaz
Photopea Fan

**Comment by photopea** [comment]
There is no "virtual mouse". I do not know what you mean by that, and how would such virtual mouse work.

You are supposed to use your finger on a touchscreen as a pointing device. "click on stuff" with your finger, just like you do on other websites in your mobile browser.

**Comment by riazuddinshaik** [comment]
Dear Sir, I completely agree with you.

When adding patterns on clothes, we are suppose to hold ctrl+mouse left click, so that it selects the outer area of duplicate layer.

I was searching for same option in photopea sir

I was not able to reply in GitHub for the same question. So, Ian messaging you here. Pls don't mind sir.

Thank you.

I found small issue... When we select any object and then if we click on making duplicate layer of selected object..  then object selection is not showing but instead again same background layer is showing.

For example, there is a men wearing shirt and trouser .. I used object selection tool and made ONLY shirt selection .. now if I click on duplicate layer then still it's showing the men with shirt and trouser in new(duplicate) layer... Actually, it should show ONLY shirt sir.... 

Please, correct me if Iam wrong sir... As the same was working in Photoshop but not in our photopea...

Thanks a lot sir....

We can close the ticket sir as I got full info and great help on same day but please reply something for just above mentioned issues before closing ticket...

**Comment by photopea** [comment]
If you copy-paste a part of a layer in Adobe Photoshop, it is inserted as a new layer, and the old layer is still visible, so nothing changes in what you see.

These things work the same in Photopea and Photoshop. I think you do not know Photoshop very well.

**Comment by nothingshiru** [comment]
@riazuddinshaik 

Are you trying to do what the shortcut "Ctrl+J" do? 

If so, you should use the option "Layer > New > Layer Via Copy" instead of "Duplicate Layer".

**Comment by riazuddinshaik** [comment]
@photopea Sir, As you said, Iam not professional in Photoshop. Iam in learning stage and my computer hangs always and run too slow. Simultaneously, I found Photopea with mobile version which made me so happy.

I try to figure out all the options carefully sir before I ask you next time

It really helped a lot for us. We never thought that we get API of such wonderful tool. 

Once again, A big thanks. Take care sir. Bye Sir

**Comment by riazuddinshaik** [comment]
@nothingshiru Hi, I understood and follow. Thank you.
