### ISSUE TITLE
Can the menu key on keyboard be used as the right mouse button?

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3322]
The menu key that I'm talking about is this one.
![IMG_20210529_230234](https://user-images.githubusercontent.com/79258245/120075113-94614580-c0d2-11eb-87c8-3547687e0bdb.jpg)

On Windows, it's doing the same thing as the right mouse button does. So I'm wondering whether it can be used as right mouse button in Photopea.

On some Android devices, the function of right mouse button is "back" that will try to close Photopea when using Photopea. So it will be helpful that we can use menu key as right mouse button.

But here'a important question. Can the menu key on beyboard be used on Android?
So far, I didn't find anything that the menu key can do on my Android devices.

**Comment by photopea** [comment]
Go to this website, click into the white area and press keys on a keyboard: http://jsfiddle.net/p45f44zb/14/

It will show you a list of keys, that are pressed. What is a code of your key?

Do you want to see the menu after pressing a key, or after holding a key and clicking?

**Comment by nothingshiru** [comment]
Honestly, I'm using Logitech K380 which is not the regular layout keyboard. There are 4 customizable keys, and the menu key on my keyboard is one of them. On that website,  when I press any of the cutomizable keys, I can't see codes like when I press the other keys.
![IMG_20210530_031114](https://user-images.githubusercontent.com/79258245/120082384-50cc0300-c0f5-11eb-9540-7d36c7e9f1ad.png)

But I have just discovered that pressing that menu key would open the menu of browser.(This only works in Chrome, not in Edge neither FIrefox) This means that is a usable key.
![Screenshot_20210530_031455_com android chrome](https://user-images.githubusercontent.com/79258245/120082432-aaccc880-c0f5-11eb-8f6b-8a9671ed4f87.jpg)

**Comment by photopea** [comment]
If a website can not detect that key, Photopea can not detect it either :(

You can ask the creators of your browser to make that key work. But I think it is better to stick to regular keyboard layouts, instead of every keyboard being unique and with different keys.

**Comment by nothingshiru** [comment]
I have found out that the menu key on my keyboard is doing the same thing as the menu key in Android does. In another words, that key is one of the three keys of Android(MENU, HOME , BACK), instead of the menu key of Windows.
![screenshot_20210530_160358](https://user-images.githubusercontent.com/79258245/120096948-aa1d4c00-c160-11eb-84c0-c929587908c3.jpg)

I don't know whether this messsage would help.

**Comment by nothingshiru** [comment]
Unfortunately, I have tried a regular keyboard, and the menu key on the regular layout keyboard does the same thing as the Android menu key too. It's no different than the menu keys on the keyboard I'm using.

**Comment by photopea** [comment]
the problem is, that a browser does not tell a webpage, that this key was pressed. So we can not detect it.
