### ISSUE TITLE
Unresponsive when trying to name 2 layers the same thing

### ISSUE THREAD

**Issue by nickolasjadams** [photopea/photopea#3323]
I accidently tried to name a second layer the same as another.  
It wouldn't let me rename it or exit the renaming action.
I tried naming it something else. I tried renaming the other layer. 
Now a lot of stuff isn't working. 
![image](https://user-images.githubusercontent.com/15788998/120080563-c6dd5500-c076-11eb-986a-7de2c4fc0a6e.png)

**Comment by photopea** [comment]
Hi, what should I do to make this problem on my computer? I tried naming two layers the same, but it works well.

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by nickolasjadams** [comment]
I'm not sure what I did to break it.  Should have investigated more before opening an issue. Sorry!

**Comment by photopea** [comment]
It would be really useful if you try to reproduce an issue right after it happens, while you still remember, more or less, what you did :)
