### ISSUE TITLE
Photopea isnt working 

### ISSUE THREAD

**Issue by yenom19** [photopea/photopea#3325]
when i try and change the dpi or save it or use text it goes unresponsive and is super frustrating because im a business owner and use it to design and i have to get designs in asap and photopea doesnt work. Ive tried it on my lap top and 2 desktops, i tired private browser, restarting sooo many times. I tried to check my wifi and everything is fine so its just photopea. Its not working and i dont know what to do

**Comment by photopea** [comment]
Can you describe some steps, what should I do, to see at least one feature not working? Everything always worked for me.

I need to be able to reproduce the bug on my computer or my phone, to be able to fix it.

**Comment by photopea** [comment]
Also, it sounds suspicious, that you say like "nothing works", but at the same time, it sounds like you have been using Photopea regularly.

**Comment by hamuz** [comment]
I can't get it load, even in new Incognito window.

![image](https://user-images.githubusercontent.com/550499/120108279-2453cd80-c16d-11eb-8888-38de1e74a24e.png)

and the grey background doesn't change.

There are also errors in the console:
![image](https://user-images.githubusercontent.com/550499/120108295-39c8f780-c16d-11eb-8cf2-2fc36aae5d99.png)

**Comment by AndrewCristian** [comment]
Hello!
I have the same issue.

**Comment by photopea** [comment]
Hi, is your basic language english?

**Comment by AndrewCristian** [comment]
Yes!

**Comment by photopea** [comment]
Photopea was broken for a minute, you probably loaded it during that minute.

Can you reload Photopea with Shift+F5? Can you open it in Incognito now?

**Comment by AndrewCristian** [comment]
I will try.

**Comment by AndrewCristian** [comment]
Isn't working, I see only a grey background.

**Comment by photopea** [comment]
I switched back to the old version, does it work now?

**Comment by FreedomFighterSparrow** [comment]
Seems to work now.

**Comment by AndrewCristian** [comment]
Yes, now it is working!
Thank you very much!

**Comment by yenom19** [comment]
> Also, it sounds suspicious, that you say like "nothing works", but at the same time, it sounds like you have been using Photopea regularly.

Yes I’ve been using it regularly but it just started acting up this week

**Comment by yenom19** [comment]
> Can you describe some steps, what should I do, to see at least one feature not working? Everything always worked for me.
> 
> I need to be able to reproduce the bug on my computer or my phone, to be able to fix it.

It’s really laggy and it won’t let me save

**Comment by photopea** [comment]
Can you record a video of your problem?

**Comment by yenom19** [comment]
I tried a different laptop and it worked but now the only thing is the
contour button isn’t working

**Comment by yenom19** [comment]
Never mind it doesn’t work. I think I’m just gonna to find another app bc
this is very frustrating

**Comment by photopea** [comment]
You just need a normal browser and a normal internet connection to use Photopea.com .

**Comment by yenom19** [comment]
What do you mean normal browser?

**Comment by photopea** [comment]
I mean a browser, that is not too old (not older than 10 years), and without extensions, that could break Photopea (there are extensions which remove Javascript, or remove images from websites).

**Comment by yenom19** [comment]
Which browser do you recommend?

**Comment by photopea** [comment]
I recommend Chrome, Firefox, Safari, Edge, Opera, etc.

**Comment by yenom19** [comment]
Thank you I’ll will try that out!

**Comment by yenom19** [comment]
Nope doesn’t work for me

**Comment by photopea** [comment]
Maybe your internet does not work well, or you are using browser extensions.

**Comment by yenom19** [comment]
It’s working well on all of the phones in the house
