### ISSUE TITLE
Cant open file resided in system file 

### ISSUE THREAD

**Issue by rahulsain** [photopea/photopea#3327]
I want to open this pdf file
`file:///C:/Users/username/AppData/Local/Temp/MicrosoftEdgeDownloads/091d8ea8-098b-4793-9179-7f81e0a3046b/Exp-7%20matrix%20algebra-converted.pdf`

Please enable option to open the files which are resided in system directory (Local Disk C:)

**Comment by photopea** [comment]
Sadly, websites can not go through files inside your computer. If every website could read files in your computer, some of them would probably steal your private data, etc.

You need to use File - Open in Photopea.
