### ISSUE TITLE
stuck on new layer, won't allow to change or delete layers

### ISSUE THREAD

**Issue by Krizzy3** [photopea/photopea#3328]

**Comment by photopea** [comment]
Could you describe some steps, how we can reproduce it?

**Comment by photopea** [comment]
Otherwise, I think you probably ran out of RAM memory (e.g. you created several thousands of layers or something), and your browser decided to kill Photopea, as it has no more memory to offer.

**Comment by photopea** [comment]
I will close it now, but you can provide more information.
