### ISSUE TITLE
Create fan pack.zip

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#333]
What about create some fans / media pack for download containing:

- full logo in: SVG, PNG, JPG (transparent / black background / white background version)
- icon from logo in: SVG, PNG, JPG (transparent / black background / white background version)

In future I can imagine e-shop with: stickers, mugs, t-shirts etc <3

**Comment by photopea** [comment]
Do you really think people are interested in such fan pack? :)  Where should we offer it for download?

**Comment by landsman** [comment]
Yeah, sure! :-) 
I think that blog can be good place for it.

**Comment by photopea** [comment]
Hi, I added some logos into this repository!

**Comment by landsman** [comment]
Good :-) thanks
