### ISSUE TITLE
Save as psd change to format .bib

### ISSUE THREAD

**Issue by ryadhiprasetya** [photopea/photopea#3330]
Everytime i save file as psd, the format change to .bib
![image](https://user-images.githubusercontent.com/47018482/120124213-7d5b4a00-c1dd-11eb-8af5-18c0f1824c92.png)
![image](https://user-images.githubusercontent.com/47018482/120124229-92d07400-c1dd-11eb-9b8b-3993a98717af.png)
![image](https://user-images.githubusercontent.com/47018482/120124236-9bc14580-c1dd-11eb-8d49-726583b937ba.png)

I need to manually change the format to psd

**Comment by photopea** [comment]
I think you use a browser extension, which renames the files saved by websites.

Try to disable that extension. I recommend disabling all your extensions, if you are not sure about what exactly they do.

**Comment by photopea** [comment]
I think disabling a browser extension will fix it, so I will close it for now.
