### ISSUE TITLE
.tiff file not opening correctly

### ISSUE THREAD

**Issue by casperzwaart100** [photopea/photopea#3331]
I recently got a mockup from yellowimages. 
I was wondering how/if I could open that. 

Right now when I open it I just get a flat image without any layers 

![image](https://user-images.githubusercontent.com/85107635/120178733-1607bf00-c20a-11eb-8bbc-7469cef6dfcf.png)

**Comment by photopea** [comment]
Are you sure your TIFF contains more layers? Did they give you a PSD file, too?

**Comment by casperzwaart100** [comment]
Yes, I am sure it contains more layers. They have not given me a .psd file, I've requested one but they haven't gotten back at me yet.

**Comment by casperzwaart100** [comment]
I fixed it, simply asked someone to make the .tif file a .psd file. Thx. Great website btw

**Comment by photopea** [comment]
I would like to announce that we support these "PSD-ish TIFF" files now! :) After opening them in Photopea, you can see the same content as you would see in Adobe Photoshop.

See https://github.com/photopea/photopea/issues/6311
