### ISSUE TITLE
infinite canvas

### ISSUE THREAD

**Issue by Roxgame95** [photopea/photopea#3332]
Infinite canvas is great feature for people who don't know the size of what they are drawing i know that there is resize option but resizing every time i get out of boundaries is time consuming .
this option will make photopea even better than photoshop it self please think about it

Currently there is 3 apps with this feature that i know of:
Mypaint
Mischief
Leonardo

**Comment by photopea** [comment]
The infinite canvas is really easy to create in vector-based editors. But Photopea is raster-based, and it is really hard in such case.

Actually, the canvas in Photopea is infinite. If you move an object far away form the center, it will not be deleted.

But there is a "visibility window" - a rectangle, and only objects inside that rectangle are displayed. You can change that "visibility rectangle" any time with the Image - Canvas Size, or the Crop tool (draw a larger rectangle and confirm).
