### ISSUE TITLE
Issue with zooming

### ISSUE THREAD

**Issue by s-varia** [photopea/photopea#3333]
Whenever I try to zoom into an image in Photopea, the page will also zoom in: this has been the case for both devices I've checked for the issue. Is there anything that causes this, or any way to stop it from happening?

**Comment by nothingshiru** [comment]
Are you using Photopea on mobile phone? 
In some browsers, there's option like this one. Disabling it would fix the problem. 
![screenshot_20210531_225111](https://user-images.githubusercontent.com/79258245/120211125-28faad80-c263-11eb-8e07-327b15d76ab7.jpg)

**Comment by s-varia** [comment]
Thanks for the response: I'm not using photopea on mobile, both devices I checked it on are desktop.

Of note, I'm also facing issues with saving PSD files, which someone else seems to be facing too. Possibly related?

**Comment by nothingshiru** [comment]
There's nothing more I know. Let's wait for developer's response.

**Comment by photopea** [comment]
I am very for this bug, it should be fixed now.
