### ISSUE TITLE
BUG - Fail to open directories with non-ASCII characters

### ISSUE THREAD

**Issue by becelli** [photopea/photopea#3335]
I've had some issue today when trying to load files from a folder with non-ASCII characters.
I also tried an .png file and as expected, it didn't work.

Name of the directory
![/home/becelli/Pictures/GJFM/05-31, Visitação](https://i.imgur.com/uIgYPhE.png)

When I renamed the folder to only "05-31", it loaded normally.

**Comment by photopea** [comment]
I could not reproduce such behaviour (Chrome on Windows 10), could it be a bug in your OS or your browser?

**Comment by becelli** [comment]
Thank you for response. The problem is with my browser (Brave) on Linux.

I tested Brave on Windows, Firefox and Chromium on Linux, and all of them worked perfectly.
