### ISSUE TITLE
Issue: Panels and Workspace are not working properly

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3336]
This bug is on Android devices. 

**Problems**

1. Scrolling on canvas with one finger would zoomed the canvas, no matter which tool was selected. 
It seems there is a invisible finger is always touching on canvas. 

2. In panels, there would not be changes in real time, or would not be any changes.(In fact, different panels bahave slightly differently.) 
In History panel, there would not be any new steps. 
In Channel panel, when create a new channel, we can't see the new channel unless we collapse and reopen Channel panel. There 

**To Reproduce**
Here are 2 ways to reproduce:

①Enable "No Touch" while a finger is touching on canvas, and disable it after release the finger on canvas. 

②Use Magic Wand, or Quick Select, or Object Selection. (This way doesn't cause the bug everytime.) 

**Since on Android this bug can be reproduced in Chrome and Edge but not in Firefox, I think it might be a bug of Chromium.**
I had replied in a closed issue with this message, But it seems that you didn't noticed. Meanwhile, I made a new discovery, that it is workspace and panels that are affected by the bug. So I submitted this bug in a new issue.

**Comment by photopea** [comment]
I was experimenting with new parameters today. Is it working now?

**Comment by nothingshiru** [comment]
No.

**Comment by photopea** [comment]
Do not enable "No Touch" when you are touching a screen. I can not see any bug with the Magic Wand.

**Comment by nothingshiru** [comment]
As I said, the second way doesn't always cause this bug. Because there is still a chance of causing this bug, I dare not use those tools. 

https://user-images.githubusercontent.com/79258245/120233634-ddf39100-c288-11eb-8a62-5d598faa3f0b.mp4




The first way is just for reproducing the bug definitely, so that you can see what the bug looks like.

**Comment by nothingshiru** [comment]
@photopea 

I found another behavior causing this bug. It is touching canvas with two fingers without moving for a while. This is just a function of my device, But it caused this bug in Chrome.

https://user-images.githubusercontent.com/79258245/120901459-a3656c00-c66d-11eb-8352-941c6b0c9d69.mp4

This way also doesn't cause this bug in Firefox. I'm sure that's the problem with Chromium.
