### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by Addelamar** [photopea/photopea#3337]
Today I am getting the above error. Restarting doesn't help and removing all extensions doesn't help either. Who has an idea?

**Comment by photopea** [comment]
Are you using Photopea at www.Photopea.com ? When I open www.Photopea.com , I do not see such error.

Actually, there is no such message in our software Photopea, so it is not Photopea who prints such message.

**Comment by Addelamar** [comment]
Thanks for your quick response. Take a look at the address bar. There I read: ref=extenstion
![photopea1](https://user-images.githubusercontent.com/75486778/120228737-08732900-c24c-11eb-95db-ffa6a55b2c81.jpg)

**Comment by Addelamar** [comment]
I have found the problem. I worked with an extensions of Google Chrome.
Again Thanks.
Ad

Op ma 31 mei 2021 om 19:40 schreef Photopea ***@***.***>

**Comment by photopea** [comment]
I see you are at a website "freeonlinephotoshop.com" . It is not our website.

Our website is www.Photopea.com . Use Photopea there, as it contains less ads than your website.
