### ISSUE TITLE
PSD files saving with 0 bytes when downloaded from Chrome

### ISSUE THREAD

**Issue by Just-Another-Black-Sheep** [photopea/photopea#3338]
Hii, I'm experiencing some issues when I'm downloading my work as PSD files in Chrome, they keep saving with no size and once I download them I can't open them in Photopea.

I made several "test" PSD files where I tried adding different amount of layers and all those test files that I downloaded as PSDs ended up having 0 bytes and when I tried to open them in Photopea I got an "Unknown file format: /u0000/u0000/u0000/u0000" message.

I'm using Chrome on my laptop, and from what I can tell I'm on the latest version and I'm not a beta Chrome user. I did try to use Photopea in incognito mode, I disabled all the extensions I had, I cleared out the cookies but none of these things fixed the issue.

But all is alright when I try to save files in Firefox, so I'm just wondering is my issue related to my specific Chrome??

And I'm assuming that all my previous work I saved (while I still wasn't aware of this issue) can't be recovered since the files were saved with 0 bytes in size so no content within that file was actually saved?

**Comment by photopea** [comment]
I am very sorry, it should be fixed now. Can you reload Photopea and try it again?

**Comment by Just-Another-Black-Sheep** [comment]
Everything works fine now, thank you for fixing the issue so quickly :))
