### ISSUE TITLE
Problem - Objects to Artboard

### ISSUE THREAD

**Issue by smalldead** [photopea/photopea#3340]
I'm can't drag any objects (Layers/Text/etc) to any artboard that I create, am I doing something wrong? I go to the layers panel and drag the layers on artboard, and didn't work :c

**Comment by photopea** [comment]
What do you mean? I can drag and drop layers in the Layers panel between artboards, it works fine. How can I reproduce your problem?

**Comment by smalldead** [comment]
That's exactly what I can't do, this problem can be caused because I use Microsoft Edge?

https://user-images.githubusercontent.com/77790815/120319137-0e522400-c2b7-11eb-9f0f-727667645d90.mp4

**Comment by photopea** [comment]
You are not dragging layers into an artboard, but in between artboards. There really was a bug related to placing layers outside artboards, and I fixed it.

If you want to drag a layer into an artboard, or any other folder, release the mouse when you are on the lable of that folder (and the wole folder is highlighted, not just the top / bottom part).
