### ISSUE TITLE
Non-Destructive Blur Effects

### ISSUE THREAD

**Issue by WebSpectrum** [photopea/photopea#3341]
I realise this may not at the top of your to do list, but as an old Fireworks user it would be really useful to have non-destructive blur, gaussian blur etc effects.

**Comment by photopea** [comment]
I think what you need are smart filters on smart objects. You can turn them off and on any time: https://www.photopea.com/learn/smart-objects

**Comment by WebSpectrum** [comment]
Was talking about opening Fireworks PNGs where objects have blue effect applied

**Comment by photopea** [comment]
What is a blue effect?

**Comment by WebSpectrum** [comment]
Sorry typo .... blur effect

**Comment by photopea** [comment]
Photopea converts Fireworks PNG files into PSD files. Not all features of Fireworks are available in a PSD format.

Can you show me an example of a Fireworks PNG, and also, create a PSD manually, so that I can see, how do you want your Fireworks PNG file converted?

**Comment by WebSpectrum** [comment]
Hi, if I open a Fireworks PNG, any layers (text, vectors, shapes) with blur, gaussian blur live filter effects applied in Fireworks are rasterised ...

**Comment by photopea** [comment]
What does it mean by that? I think I do not have such Fireworks PNG.

**Comment by WebSpectrum** [comment]
[Here's a sample Fireworks PNG ](https://www.webspectrum.co.uk/live_blur_filters.fw.png)with some liver filter blur effects applied to text, shape and vector:

**Comment by photopea** [comment]
vector shapes are converted into blurry vector shapes. That is correct.

We can not create a text with a blur, because that is not possible in a PSD format. You can not do it e.g. in Adobe Photoshop.
