### ISSUE TITLE
Gradient stroke

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3342]
I am doing somethig wrong?
when trying to do a gradient stroke to a shape i do the same as a gradient fill, but i get different results
![image](https://user-images.githubusercontent.com/11801254/120254756-8c331280-c258-11eb-9b52-063ad95f383a.png)

Here is the PSD:
[Box Lud8.zip](https://github.com/photopea/photopea/files/6572806/Box.Lud8.zip)

**Comment by photopea** [comment]
I fixed it, the gradient stroke with transparency should be rendered the same as in Adobe Photoshop now.

**Comment by avagp** [comment]
I needed the file before the fix, and i made another white layer on top of the color lines, with a gradient to make the same effect of vanish.

But when exporting to PDF, it disappears
![image](https://user-images.githubusercontent.com/11801254/121120993-bd798880-c7ec-11eb-88c7-b11d8024d2b2.png)

**Comment by photopea** [comment]
I am afraid that PDF gradients can not contain any transparency :(  All PDF files that I have seen in my life had fully visible gradients.

You can rasterize such layer in Photopea, and it will be inserted as a semi-transparent bitmap into the PDF. Or maybe we could do that automatically? :/

**Comment by avagp** [comment]
Oh  :( Too bad.

Well i tried making them go gradient to white, to "make them disappear"

BUT....
![image](https://user-images.githubusercontent.com/11801254/121216309-c69b4180-c84e-11eb-9923-ee27cae776a5.png)

It does not render. I am doing something wrong? ( i don't want to rasterize, because i loose the ability to change)

**Comment by photopea** [comment]
Could you send me your PSD?

Do not use PDF as a format which you edit in the future. BTW. if you have AI files, Photopea opens AI much better than PDF.

**Comment by avagp** [comment]
The pad is in the first comment :)

**Comment by photopea** [comment]
I tried it, but I do not see any colored columns in that PSD.  https://i.imgur.com/EqtAIpY.png

**Comment by avagp** [comment]
i had to sent you another version.

Here is ti the one with the stripes:
[Box Lud8 (1) (1).zip](https://github.com/photopea/photopea/files/6619681/Box.Lud8.1.1.zip)

**Comment by photopea** [comment]
It turns out that gradient strokes were impossible to export to a PDF (such layers were skipped). I implemented it :)

If you just need to print it, I think it is ok to use a large resolution and "rasterize all" into a PDF :)

**Comment by avagp** [comment]
![image](https://user-images.githubusercontent.com/11801254/121379689-46d6ab00-c912-11eb-9a34-8a0d3a16ba44.png)
 now it works!
