### ISSUE TITLE
Export to PDF - When exporting some texts move

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3343]
Here is the rasterized PDF
[Box Lud8 (2).pdf](https://github.com/photopea/photopea/files/6573355/Box.Lud8.2.pdf)

Here is the vector PDF
[Box Lud8 (1).pdf](https://github.com/photopea/photopea/files/6573357/Box.Lud8.1.pdf)

i lose the gradient fill of the rainbows on the right, and the style of the text "solo para +18" on the left is moved.

Here is the PSD
[Box Lud8 (1).zip](https://github.com/photopea/photopea/files/6573361/Box.Lud8.1.zip)

**Comment by photopea** [comment]
I believe it is fixed now. I tried your PSD with "vectorize text" and it seems correct. 

PDF does not support gradients with transaprency, so just rasterize that layer in Photopea, so that it is a bitmap.

**Comment by avagp** [comment]
The gradients it is fixed now, with your implementation.

But this text was weird. I will try again.

Thanks!
