### ISSUE TITLE
PSD I just saved wont open and seems glitchy

### ISSUE THREAD

**Issue by JAMHouseMedia** [photopea/photopea#3344]
I was just working on a project in Photopea that started acting weird when trying to rotate multiple layers. Now the save file for it shows zero layers and has a strange line on it. I can still open the PSD in GIMP so I don't think the file is corrupted.

![troubleshooting](https://user-images.githubusercontent.com/85190815/120370800-e1f3d300-c2c9-11eb-83fe-e8ffe393183d.jpg)

**Comment by JAMHouseMedia** [comment]
An earlier iteration of the project opens and works fine
![troubleshooting 2](https://user-images.githubusercontent.com/85190815/120371354-8544e800-c2ca-11eb-9655-279e2d6f67aa.jpg)

**Comment by photopea** [comment]
Could you find steps how to turn your original PSD into an unopenable PSD? We need to reproduce a bug somehow.

**Comment by photopea** [comment]
Could you send me your unopenable PSD to support@photopea.com ?

**Comment by JAMHouseMedia** [comment]
> Could you send me your unopenable PSD to [support@photopea.com](mailto:support@photopea.com) ?

Yep

**Comment by photopea** [comment]
So that PSD is a bit damaged (the layer structure). Is it possible that you ran out of RAM when working on it? 

Could you try to recreate it and save a PSD each two minutes, until you find, which steps generates a damaged PSD?

**Comment by JAMHouseMedia** [comment]
> So that PSD is a bit damaged (the layer structure). Is it possible that you ran out of RAM when working on it?
> 
> Could you try to recreate it and save a PSD each two minutes, until you find, which steps generates a damaged PSD?

Interesting. I assume that's possible, but it's not something that I knowingly experienced before. Are there optimization steps I can take for when I'm using Photopea? I have 8gb of ram and I was only watching Youtube and using Photopea. 
I'm taking a little break from the project right now because it was a couple hours of poking around with ideas, but I'm also going to try and have a friend open and resave my damaged psd in photoshop when he gets home to hopefully save some time.

Thanks for the help :)

**Comment by JAMHouseMedia** [comment]
I'll leave my memory usage window open when I get back to work on this to keep an eye out for spikes

**Comment by photopea** [comment]
Did you have any other problems? I will close it for now.

Photopea is a raster editor, so if you make the DPI 2x smaller, you will need 4x less memory.

**Comment by JAMHouseMedia** [comment]
Sorry for the slow reply, I was out of town.
Nope. I think it's very likely it was running out of RAM issue using larger DPI than necessary. Thanks for the help :)

**Comment by photopea** [comment]
Look for at least 8 - 16 GB of ram when you buy a new computer :)
