### ISSUE TITLE
Won't create a PSD 

### ISSUE THREAD

**Issue by claire565** [photopea/photopea#3345]
Hi.  Every time I go to save my file as a PSD nothing happens?

Not sure if it's a bug or my laptop, but it was working last week but not now.

When I click File - Save as PSD nothing happens.

It does save when I click on create PSD/PSB so no drama but thought I'd best report it.

Thanks.

**Comment by photopea** [comment]
Hi, are you using Google Chrome? Is it updated?

Could you open Photopea.com in Incognito and save a PSD? Maybe your browser extensions are blocking it.

**Comment by claire565** [comment]
Hi.  Yes, it's in Chrome and it's updated.

I've tried in Microsoft Edge and it works there.

It does seem to save in an incognito tab so, as you say, looks like something is blocking it.

I did have an update recently so I'm wondering if that has anything to do with  it.

However, I have since installed your app onto my laptop and it works in that, so I'm not sure why it's not working in the browsers.

Like I say, it's not a major issue as I can save via PSD/PSB option so no drama, just wanted to report it.

I have no idea what is blocking it, so no idea where to look to resolve the issue. 

Also, just wanted to say, Photopea has been an invaluable piece of software for me and has helped me out more than I could ever say, so thank you!

**Comment by photopea** [comment]
I think you are using a browser extension, which is blocking Photopea from saving files. Read this to learn how extensions work: https://support.google.com/chrome_webstore/answer/2664769?hl=en 

You should decide, if you want Photopea to save files to your computer, or you want an extension, which blocks websites from saving files.

Extensions are disabled in Incognito mode.

Thanks! :)

**Comment by claire565** [comment]
Hi.

Having checked, the only extension that's running is my McAfee Antivirus and I recently installed a newer version, so it must be that.

I don't want to disable it so I'll use the app or incognito mode.

Thanks for your help! :)

**Comment by photopea** [comment]
You can also write to McAfeee and ask them to fix their extension.
