### ISSUE TITLE
Issue: It's not easy to notice which slices are selected

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3348]
Now it looks like
![screenshot_20210602_185100](https://user-images.githubusercontent.com/79258245/120468955-59ae2480-c3d4-11eb-8905-5cbf9dd9478a.jpg)

How about making the selected slices different in color? 
Like this
![screenshot_20210602_185100](https://user-images.githubusercontent.com/79258245/120469101-85310f00-c3d4-11eb-9190-da0c9aa82bd0.jpg)

**Comment by photopea** [comment]
Sure! I made them orange.

**Comment by nothingshiru** [comment]
Thanks :) 

Could you make the label orange too? 
![screenshot_20210602_200219](https://user-images.githubusercontent.com/79258245/120477010-d4c80880-c3dd-11eb-8db4-3afb71d1acd3.jpg)
