### ISSUE TITLE
type tool dosent work

### ISSUE THREAD

**Issue by burhankhanzada** [photopea/photopea#3349]

**Comment by photopea** [comment]
Can you try it in incognito mode, where all your browser extensions are disabled?

**Comment by burhankhanzada** [comment]
yeah tried now but it's the same it doesn't create type box automatically and when it tries to create it manually by dragging mouse its creating box on from when i drag from bottom to up its weird even after textbox created it's not accepting any text or may not showing text

**Comment by photopea** [comment]
Do you see a message that the font was loaded?

**Comment by burhankhanzada** [comment]
no i haven't see any message like this

**Comment by photopea** [comment]
Can you open and save this font to your computer? https://www.photopea.com/rsrc/fonts/fs/LiberationSans-Bold.otf

**Comment by burhankhanzada** [comment]
well i have download that font and try again but it doesn't work with that then i noticed that that for is set to DejaVu Sans when i change the to Liberation sans then loading dialog showed and after 2 seconds it shows and Liberation Sans loaded and text showed so maybe yesterday this font loading process doesn't start that's why text not showing

**Comment by photopea** [comment]
I think your browser extensions could be breaking Photopea. Are you using Chrome? Can you send me a screeshot of chrome://extensions, so that I see, that you are not using any?

**Comment by burhankhanzada** [comment]
![Screenshot 2021-06-03 213042](https://user-images.githubusercontent.com/18241005/120679820-06f76a00-c4b3-11eb-8426-eff6a2921f04.png)

**Comment by photopea** [comment]
Can you disable all extensions? Is the issue still happening?

**Comment by burhankhanzada** [comment]
well it's working now with all my current settings as i already told its may just font loading issue may be caused by my internet because yesterday and today it's being frequently disconnecting so i don't think disabling extension make any difference

**Comment by photopea** [comment]
Oh, I see. Fonts should stay in the browser cache for a while.
