### ISSUE TITLE
Translate - search

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#335]
Please add search input for https://www.photopea.com/translate/ I want translate one field from EN to CZ and I don't know how can I search it.

![snimek obrazovky 2017-11-09 v 15 12 03](https://user-images.githubusercontent.com/3184228/32609596-7700a74a-c560-11e7-8307-059e56614457.png)
![snimek obrazovky 2017-11-09 v 15 12 36](https://user-images.githubusercontent.com/3184228/32609597-771ac9cc-c560-11e7-8614-9d3a9328b17e.png)

**Comment by photopea** [comment]
The optin "don't use palettes" was creted specifically for one user, because of the bug in Adobe Reader: https://github.com/photopea/photopea/issues/286  . I plan to remove this option as soon as Adobe fixes Adobe Reader.
