### ISSUE TITLE
no tool

### ISSUE THREAD

**Issue by Hubi13** [photopea/photopea#3350]
there is no tool to transform the string into a curve, e.g. a flag, as it is in photoshop

**Comment by photopea** [comment]
What do you mean by that? What is a string? I know only a guitar string :D

**Comment by MichalSZZ** [comment]
I think that he wats to warp text in rhe predefinied way.

In Photopea it works too. Look for Warp option.

**Comment by photopea** [comment]
I don't think it is about text. I think it is about some flags in Photoshop, but who knows what it means.

**Comment by dentistformyeye** [comment]
I think Hubi13 is trying to make a flag wavy, as if it were blowing in the wind. Edit > Puppet Warp or Filter > Liquify might work.

**Comment by MichalSZZ** [comment]
Once again I think that he talked about warping the text with the predefinied "flag" method...
![](https://i.imgur.com/ciJYAIA.jpg)

**Comment by photopea** [comment]
I have to close it because of lack of details.
