### ISSUE TITLE
Lens Blur Filter - option for invert a depth map

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3351]
Can be added that feature? Today I prepared a Depth map and when loaded it in filter window, everything was inverted in field of depth (because I used white for that is in front and black for far away things).

In the Photoshop there is a checkbox for that feature in filter window. It is called "invert" ;) It is in a depth map field section.

**Comment by photopea** [comment]
Sure, I added the "Invert" Checkbox :) I dont understand how could I forget about it when I created the menu.
