### ISSUE TITLE
Saved PSD changes names, and don't have .PSD extension

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3352]
Something is wrong since a couple of days, but today i have recorded  the whole trigger:

https://video.drift.com/v/abORWPLjNMw/

**Comment by photopea** [comment]
Could you prepare a simple steps how can I reproduce it? Maybe with two projects instead of three? Could you reproduce it with a demo pea.psd?

**Comment by avagp** [comment]
let me try to debugg the behaviour

**Comment by avagp** [comment]
mmm.

as far as i get, it happens with everything but a PSD

**Comment by photopea** [comment]
When you press File - Save as PSD in Photopea, the suggested name should always be the name of your document in Photopea, with ".psd" at the end.

Is your Chrome updated? If not, could you update it?

**Comment by photopea** [comment]
Just to be clear, you need Chrome 91 to use Photopea properly. Saving will not work as it should in Chrome 90 or older.

**Comment by avagp** [comment]
It does. I was on m90, and now i am on m91, and it works.

:O

**Comment by photopea** [comment]
It seems like there ar too many people using chrome 89 and 90, so I disabled this new feature.

The new feature was, that if you save a document as a PSD to your computer once, then, File-Save will update the file in a computer, without any window in between.

**Comment by avagp** [comment]
maybe wait a couple of months. but that feature is a good addition!
