### ISSUE TITLE
Replace the squares with the eraser icon

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3353]
The black square in Refine Edge is a "eraser". But in Magic Cut, the "eraser" is the grey sqaure. It is kind of confused. 
It would be better to replace the squares with eraser icon.

**Comment by nothingshiru** [comment]
Besides, I think the white sqaure in Refine Edge can be replaced with brush icon.

**Comment by photopea** [comment]
In Refine Edge and Magic cut, the middle square is an "eraser".

But if you start Refine Edge with no selection, everything is painted by black. But if you start Magic Cut with no selection, everything is painted by "eraser".

Maybe we could replace white and black (in RE) with red and green, as in MC.

**Comment by photopea** [comment]
I think I will leave it as it is for now.

**Comment by nothingshiru** [comment]
I can't think of a good idea right now. That's fine to leave it as it is.
