### ISSUE TITLE
Cannot Copy using Firefox

### ISSUE THREAD

**Issue by paulodetarso-ccal** [photopea/photopea#3356]
I'm trying to use Photopea with Firefox (Windows 10), but the copy command does not work. It works normally with Google Chrome, but not with Firefox. I cleared all cookies and tried again to see if I missed something related to clipboard permissions, but I can't see any prompt asking me permissions for it.

The problem occurs with different laptops. Any idea?

**Comment by photopea** [comment]
Hi, I have the latest Firefox. I opened a JPG image in Photopea.com , created a selection, pressed Edit - Copy, Edit - Paste, the selected part was inserted as a new layer.

Is that what you mean? Or what do you mean by "Copy"? How can we reproduce your issue?

**Comment by paulodetarso-ccal** [comment]
Hi, copying from Photopea (a merged layer, for example) and pasting in another application, such as Paint, Microsoft Word, without exporting and saving the file. I use this a lot, but since I migrated from Chrome to Firefox, this is a real problem for me.

**Comment by photopea** [comment]
Firefox is a bit "backward" browser. It does not allow websites to put images into a clipboard (so that images can be pasted elsewhere). I even think most of Firefox users would consider it as a "dangerous" feature, which would be abused by websites.

Use another browser which supports the modern Clipboard API, or ask Firefox to fix it: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API#clipboarditem

**Comment by photopea** [comment]
As the link shows, a website can place an image into a clipboard in all web browsers, except of Internet Explorer and Firefox.

**Comment by paulodetarso-ccal** [comment]
I see. Thanks for the reply. I saw on the link you shared that we can enable this feature manually, accessing the `about:config` and then changing the value of `dom.events.asyncClipboard.clipboardItem` to `true`. After that, I tested here and worked!

**Comment by paulodetarsofm** [comment]
Unfortunately, after changing the option above, yes, I can copy from Photopea and paste outside it, however, now, the opposite stopped working, I can't paste something copied from outside the Photopea and paste inside it. And worse, even if I change the option `dom.events.asyncClipboard.clipboardItem` to `false` again, doesn't work.

To summarise, don't use Photopea with Firefox 😔

**Comment by photopea** [comment]
I am sorry to hear that. You can ask Firefox to fix it.
