### ISSUE TITLE
Can't Save Psd's

### ISSUE THREAD

**Issue by M10crawford** [photopea/photopea#3358]
When I load up a psd I can save it as a psd but when I add another layer it doesn't save as a PSD or won't even allow me to add another layer.

**Comment by avagp** [comment]
@M10crawford i had a similar problem recently, do you have chrome 91? If not, can you update and then try again?

**Comment by M10crawford** [comment]
@avagp It is chrome 91, still not working.

**Comment by photopea** [comment]
I think your browser is blocking the download of two files. Google it, I found this: https://www.howtogeek.com/428416/how-to-enabledisable-multiple-file-downloads-in-chrome/

**Comment by M10crawford** [comment]
that did not fix it.

**Comment by photopea** [comment]
Can you confirm, that it happens in a browser where no extensions are enabled?
