### ISSUE TITLE
Export SVG - Second stroke layer style is not rendered

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3359]
Here, look at this:
![image](https://user-images.githubusercontent.com/11801254/120738872-92c2c380-c4be-11eb-8aa9-4c08deb53045.png)

both numbers have layer styles, but one have 2.

The one with 2 layer styles don't get it when exporting to SVG.

Here is the PSD:
https://www.photopea.com/#itZAsBUDq

(btw, do you prefer that i upload the PSD on archive or public on photopea.com ?)

**Comment by photopea** [comment]
Sadly, you can have only one stroke in SVG :(  https://stackoverflow.com/questions/32394435/is-it-possible-to-have-two-strokes-on-an-svg-element

Place a copy of a shape behind your shape, and give each shape one stroke. Or merge all layers into one raster layer.

**Comment by MichalSZZ** [comment]
I can't check it but what will be exported if you add stroke to the layer and group that layer and add secound stroke to the folder?

**Comment by avagp** [comment]
At least they now that it will be a feature:
![image](https://user-images.githubusercontent.com/11801254/120823258-4199ea80-c525-11eb-8b38-2bb09dfe6de7.png)

@MichalSZZ i've tried what you said with high expectancies, but it doesn't do the trick  :(
