### ISSUE TITLE
Very poor service - file wont save

### ISSUE THREAD

**Issue by notkingobada** [photopea/photopea#3360]
After having to start from scratch twice, I now have to face a new issue: the file wont save, everything seems... normal, it does what it should, but doesnt actually have to save, so I imagine i have to elt Photopea disapoint one more time and i have to waste more of my time cuz i have to restart it? or is there somehow a way to fix this?

**Comment by dentistformyeye** [comment]
What menu options have you tried? For most file formats, make sure you're using File > Export as. If you want a PSD, File > Save as PSD should work for most purposes.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
