### ISSUE TITLE
Photopea Bug

### ISSUE THREAD

**Issue by khamarisprings** [photopea/photopea#3361]
Please fix this bug. I select ¨New Project¨ and then I set my height and width to 500, and then I set my background to transparent and then I click create. The next thing I do drag and drop a image from my file and then I put it in photopea. This is where the problem starts. I selected the image I drag and dropped and I click blending options, after that, I selected ¨color overlay¨ and I set the color to red. I set the opacity down a bit and all I see the transparent background and not the image that I drag and dropped before. I can´t make my profile picture and it makes me mad. Please reply soon as possible.

Khamari

**Comment by photopea** [comment]
I think you enabled the "Color overlay" checkbox, but you did not click it to choose the options of Color Overlay.

If that is so, you are changing the Opacity of a whole layer, not the opacity of color overlay. Is Color Overlay highlighted, or just the checkbox checked?

Please read this: https://www.photopea.com/learn/layer-styles . I think you simply dont know how to use Photopea or Photoshop, you need to learn before using them.

**Comment by photopea** [comment]
I have to close it because of lack of details.
