### ISSUE TITLE
Command+X/ Cut not working

### ISSUE THREAD

**Issue by Kingstonboie** [photopea/photopea#3364]
I dont know if there is any option that I enable that prevents the cut from working because I just finished a project and when I moved on to the next one I couldnt even cut, all other shortcuts are working fine and I tried to cut it manually but that didnt work either. I cut by using rectangle select and then Command+X

**Comment by photopea** [comment]
I am very sorry, it is fixed now.

**Comment by Kingstonboie** [comment]
Still not working.

**Comment by photopea** [comment]
You are seeing an old version cached by your browser. Clear the browser cache, or open Photopea on another device.

**Comment by Kingstonboie** [comment]
Thanks it works now :)
