### ISSUE TITLE
Delete doesn't work

### ISSUE THREAD

**Issue by DemisBiscaro** [photopea/photopea#3366]
I'm using PhotoPea with Firefox 88.0.
I select the area I want to delete and I press "Delete" key, but the area is not removed.
If I do the same within Google Chrome browser, the feature works correctly.

Please, have you got any hints to fix this issue?

Thank you.

**Comment by photopea** [comment]
There was a bug in Photopea, which lasted for about 10 mintues, and was fixed after that. You probably opened Photopea in Firefox during these 10 minutes. Just reload the webpage.
