### ISSUE TITLE
Issue: Dissolve blend mode doesn't work properly at all

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3367]
![Screenshot_20210606_002547](https://user-images.githubusercontent.com/79258245/120898521-c5ef8900-c65d-11eb-806f-20898120db65.jpg)

**Comment by photopea** [comment]
I think this is anohter WebGL-related bug. Your device has 16-bit floats instead of 32-bit. Can you press More - Use WebGL?

**Comment by nothingshiru** [comment]
Well, it works after I disabled WebGL.

**Comment by photopea** [comment]
fixed, it should work even with WebGL on all devices.

**Comment by nothingshiru** [comment]
Thank you very much!
