### ISSUE TITLE
free api for image upscaling

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#3368]
recently I used to use the ai upscaling very much.... like _**[bigjpg](https://bigjpg.com/)**_ and **_[imglarger](https://imglarger.com/)_** ..... but it was tiring to make this process in different software, 

so I thought if this feature was in photopea itself it will be great, and I found a free API access for a similar feature, can it be added to photopea?

I'm not sure if it would be as good as the sites that I use, but I believe that it would be a very great new feature

![1_title_2020_kia_optima (1)](https://user-images.githubusercontent.com/70863817/120905204-b9186880-c650-11eb-8260-24b9c0606ad7.png)

![1_title_2020_kia_optima (1) (1)](https://user-images.githubusercontent.com/70863817/120905270-56739c80-c651-11eb-878e-7f06ee56c424.png)

**Comment by mustafaGFX** [comment]
the API : 
https://deepai.org/machine-learning-model/torch-srgan

**Comment by photopea** [comment]
I just tried BigJpg and the result is not very conincing in my case :( I enlarged my eye four times.

![ivan_face (1) (1)](https://user-images.githubusercontent.com/15955558/120915187-b21a4600-c6a2-11eb-805a-8e78a27f326d.jpg)

**Comment by mustafaGFX** [comment]
that's weird, I have just tried enlarging some faces, and I noticed that it doesn't do well with faces

![GettyImages-1092658864_hero-1024x575 (1)](https://user-images.githubusercontent.com/70863817/120925611-9716f880-c6d9-11eb-87ec-d3e1fcd92ba0.png)

![KOVy09R2_4x](https://user-images.githubusercontent.com/70863817/120925585-777fd000-c6d9-11eb-9def-2a6fbc4a0ca7.png)

![image (1)](https://user-images.githubusercontent.com/70863817/120925843-c37f4480-c6da-11eb-929d-36fb5ee9372c.png)

I think these softwares aren't specialized in enlarging faces ( you can try remini if you are interested )

![1622986886693 (1)](https://user-images.githubusercontent.com/70863817/120926701-4ce44600-c6de-11eb-8f67-8de6681b493e.png)

**Comment by mustafaGFX** [comment]
BTW imglarger is so much better than bigjpg 

imglarger:
![53SIoyxw_4x](https://user-images.githubusercontent.com/70863817/120926923-368aba00-c6df-11eb-9470-7aeb06540e30.png)


bigjpg :
![images (1)](https://user-images.githubusercontent.com/70863817/120926934-42767c00-c6df-11eb-96b7-8941d073a8f9.png)

**Comment by mustafaGFX** [comment]
is it even a good idea?
should I close the issue

**Comment by photopea** [comment]
ImgLarger is definitely better. But I am afraid they do not offer a free API. 

Maybe in the future, we can add such feature right inside Photopea. It would require loading a neural network (50 - 300 MB) and it would be nice if browsers supported https://caniuse.com/webgpu , so that it runs in 10 seconds instead of 2 minutes.

**Comment by mustafaGFX** [comment]
great,
what about this link ...could it help?
https://deepai.org/machine-learning-model/torch-srgan

**Comment by mustafaGFX** [comment]
# QUICKSTART API REQUEST
```
curl \
    -F 'image=YOUR_IMAGE_URL' \
    -H 'api-key:a05fdd7e-e26e-433e-9c60-426c30c3756e' \
    https://api.deepai.org/api/torch-srgan 
```

Super Resolution cURL Examples
# Example posting an image URL:

```
curl \
    -F 'image=YOUR_IMAGE_URL' \
    -H 'api-key:a05fdd7e-e26e-433e-9c60-426c30c3756e' \
    https://api.deepai.org/api/torch-srgan 

```

# Example posting a local image file:

```
curl \
    -F 'image=@/path/to/your/file.jpg' \
    -H 'api-key:a05fdd7e-e26e-433e-9c60-426c30c3756e' \
    https://api.deepai.org/api/torch-srgan 

```

**Comment by xan2622** [comment]
<h3>Image Upscaling with Javascript:</h3>

article: https://thekevinscott.com/super-resolution-with-js/
codesandbox: https://codesandbox.io/s/upscaling-1-0xmbx?file=/src/index.js
github: https://github.com/thekevinscott/UpscalerJS
live demo: https://www.upscaler.ai/

<img src="https://user-images.githubusercontent.com/1732773/180609430-d2a694e2-b125-4a64-9840-0cd4efbdbc62.gif" width="50%" height="50%">

**Comment by photopea** [comment]
Maybe @hxim could make a plugin for it?
