### ISSUE TITLE
Feature Request: Grouping brushes/patterns

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3369]
Without that feature, it is hard to find the brushes/pattern we want when we have many imported brushes/patterns. And when we export them, all brushes, even the default brushes would be exported into a single file. That's not what we want.

**Comment by mustafaGFX** [comment]
yes I have suggested this feature before, it really helpful

**Comment by camoody1** [comment]
I've recently opened a new request for this same issue.
#5220 
Looks like this is a pretty popular request.

**Comment by photopea** [comment]
I have implemented this feature, it works for Brushes, Gradients, Patterns, Styles and Shapes.

Items are separated into groups, each group has a name at the top (the name of a file which contained the items).
