### ISSUE TITLE
loading fonts

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#337]
I select new font (not yet loaded) while no text is selected (when text is selected it shows no error).
After I write first letter it shows me this error in console, but everything seems to work:
Uncaught TypeError: Cannot read property 'OY' of null
    at i.rJ.rY (pp.js:2391)
    at i.rJ.rw (pp.js:2371)
Alert: Font !PaulMaul loaded.

**Comment by photopea** [comment]
Fixed. Thank you!
