### ISSUE TITLE
Issue: editor screen broken/glitched

### ISSUE THREAD

**Issue by cookie-isjason** [photopea/photopea#3370]
The problem is that every time I create a new project, the screen appears as a white canvas blocking my background and anything I add. I am new to Photopea and had watched a couple of tutorials  but I am unable to fix the issue.
![screenshot-www photopea com-2021 06 06-07_39_20](https://user-images.githubusercontent.com/85439979/120923206-50a2a900-c69b-11eb-8922-4b60c4d4522b.png)

**Comment by photopea** [comment]
Does it happen in an updated browser with no browser extensions? Can you try it in Incognito mode?

**Comment by cookie-isjason** [comment]
I realize the problem now. I was using a browser that has tight security systems (Brave) so I have switched to chrome. It's fixed now

**Comment by photopea** [comment]
I am very sorry to hear that. Maybe it can be changed by changing the settings of your browser.

Brave modifies websites significantly, so I do not consider it to be a standard browser. You can ask Brave developers to fix it.

@mkarolin @kjozwiak @LaurenWags

**Comment by kjozwiak** [comment]
@cookie-isjason do you by any chance have `Fingerprinting` set as `strict`? If you change it back to `Default`, does the issue go away?

**`Strict FP enabled`** | **`FP set as Default`**
------------------------|--------------------------
![image](https://user-images.githubusercontent.com/2602313/121065187-7d87b680-c796-11eb-8e05-9efdf79c3093.png) |  ![image](https://user-images.githubusercontent.com/2602313/121065316-a019cf80-c796-11eb-9a4c-96196a1dfc67.png)
