### ISSUE TITLE
Issue: "All" option in fonts menu is not checked by default

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3373]
All the options right below it are checked by default, so it should have been checked by default as well. 
![Screenshot_20210607_164836](https://user-images.githubusercontent.com/79258245/120988130-da906600-c7b0-11eb-84fd-9c9f211760d9.jpg)

**Comment by avagp** [comment]
yes, i kinda counter intuitive.

It should begin with All, and have the rest unselected. :)

**Comment by photopea** [comment]
Fixed :) 

There is a difference between the left side and the right side. 

A displayed font must satisfy **at least one** condition on the left. The more you check, more fonts you see.

A displayed font must satisfy **all** conditions on the right. The more you check, less fonts you see.
