### ISSUE TITLE
Feature Request: Double-click on slider to reset that slider

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3374]
I use it a lot in Lightroom. It can reset just one slider instead of all sliders. I think it's a nice feature to add into Photopea. When using adjustments which have multiple sliders like Hue/Saturation, Selective Color, etc. it would be helpful. 
 
What do you think?

**Comment by photopea** [comment]
Hi, it should already work like that.

**Comment by nothingshiru** [comment]
Well. It seems too hard to do that by finger.

**Comment by nothingshiru** [comment]
Is it possible to make touchable area (invisible) of sliders bigger? Only for TouchEvent.

**Comment by photopea** [comment]
It did not work on a touchscreen in Chrome at all :( it should work now.

**Comment by nothingshiru** [comment]
Thanks☺️
