### ISSUE TITLE
Issue: The lower sliders in Gradient Editor are too easy to be deleted

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3375]
When drag them vertically across the guides in this screenshot, they would be deleted. You can see that the lower sliders would be deleted too easily. 
![screenshot_20210607_171735](https://user-images.githubusercontent.com/79258245/120992172-ec740800-c7b4-11eb-9497-c78d72acb181.jpg)

**Comment by photopea** [comment]
fixed, thanks for reporting! :)
