### ISSUE TITLE
Replace color adjustement layer darkens

### ISSUE THREAD

**Issue by FlarosOverfield** [photopea/photopea#3376]
Steps to reproduce:

- Load a file with two or more layers, select the top layer
- Make new Replace color adjustement layer (this doesn't happen with normal replace color tool)
- Set selected color to #ffffff
- Move the hue slider around back and forth
- The selected color will slowly turn gray, then brown (?), then black on it's own

**Comment by photopea** [comment]
I think it behaves as it should in my case. Could you record a video of what is happening? Are you sure it is different than applying Replace Color to a merged content?

**Comment by FlarosOverfield** [comment]
https://www.youtube.com/watch?v=SQDa9kwlJYc

**Comment by nothingshiru** [comment]
I also observed another bug. It is that the selected color would change when open color picker via properties panel and click ok without doing anything else. 

To reproduce:

1. Create a new document, then create a Replace Color adjustment layer. 
2. Set the selected color to white. (RGB 255, 255, 255) 
3. Click ok and open the color picker. 
4. Repeating step 3, you'll see the values of RGB are changing.

**Comment by photopea** [comment]
Ok, it should be fixed now, thanks a lot! :) 255 should stay 255.

**Comment by FlarosOverfield** [comment]
It's a lot less pronounced on Camoody1's video than mine, but pretty much.

T h a n k k
