### ISSUE TITLE
Feature Request: 1 CLICK  Sky Replacement

### ISSUE THREAD

**Issue by DanAlka** [photopea/photopea#3377]
Hello Ivan, 

I wonder if you plan to add 1 CLICK  Sky Replacement in Photopea in the future? 

I know there are several ways already how to replace the sky.. 
For example:
Replace Sky 1_using Photopea.com
https://www.youtube.com/watch?v=-knLliwj-WA&ab_channel=VinceCampi

But I have in mind a more easy/quicker/automatic/AI way how to do it.. Similar to what LUMINAR has or the latest Photoshop...
As seen -for example- here: 

Replacing the SKY in LUMINAR AI
https://youtu.be/s9bpuUzUnoA
https://youtu.be/cVvhUnjEooA?t=17

Photoshop sky replacement
(How Would I Edit Your Photo with Scott Kelby and Erik Kuna | The Grid Ep 464)
https://youtu.be/n3N-IbA4OZA?t=878

Thanks for the amazing work !!!

Greetings from Prague, 

Dan

**Comment by photopea** [comment]
I think it would take me weeks or months to develop such feature, so I think it is not that important for users, so I give it up :(
