### ISSUE TITLE
liquify tool

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#3379]
I used to see the before and the after of any process I do

and thought that the liquify tool has this feature but discovered that it doesn't, can you add a `before and after` button as lightroom and some softwares do? maybe a hover or slider 
![Lightroom-Before-After-Button-1024x607](https://user-images.githubusercontent.com/70863817/121079064-fa884f80-c7d9-11eb-91d5-f9fbbe8a871c.png)

![Comparing-Before-and-After-Views-in-Lightroom_Page_2_Image_00011](https://user-images.githubusercontent.com/70863817/121079183-1f7cc280-c7da-11eb-93cf-4fbac5efd01a.jpg)

**Comment by photopea** [comment]
I have added the "Preview" checkbox, which you can turn on and off. If you draw into a picture, it turns on the checkbox automatically.

**Comment by mustafaGFX** [comment]
where?
I can't find it 

![Screenshot (195)](https://user-images.githubusercontent.com/70863817/121207406-8ac9a180-c879-11eb-9d53-7ee3123fbd87.png)
