### ISSUE TITLE
problem with ALT in Firefox

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#338]
If I press ALT once in Firefox it shows me Firefox main menu of browser. If I continue with my work in Photopea it thinks all time ALT is still pressed (and for example brush is not working).

**Comment by photopea** [comment]
It seems there is no way a webapp can prevent this behavior of Firefox :( that is really stupid.

Somebody solved it by restarting his computer: https://support.mozilla.org/cs/questions/1152763
You should change it in the browser settings: https://superuser.com/questions/770301/pentadactyl-how-to-disable-menu-bar-toggle-by-alt

**Comment by hxim** [comment]
But in this demo:
https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_event_mouse_altkey
it correctly detects if ALT is pressed or not. Can't you use same method?

**Comment by photopea** [comment]
This lets us detect the Alt key only when clicking. But our current structure of events is, that we need to know when exactly was the key pressed, and when it was released. So e.g. we could have some action after releasing the Alt key (which is not possible now in Firefox).

What would you want to happen when you release Alt in Photopea? If you prefer some Photopea function over the FF menu, report it to Firefox developers, so they allow webapps to prevent this event.

**Comment by hxim** [comment]
Hmmm... Let me explain again. The main problem is if you accidently press  and release ALT key (with no other key) and then you go back to photopea by clicking with mouse somewhere on page it will not realize you released ALT key. So you continue work with photopea and most things work and after some time you want to use brush and it is not working ... It happened to me and it was very confusing and it took me long time to realize what is going on. If you could reset your variable or whatever where you remember if ALT is pressed or not every time user clicks with mouse somewhere it would resolve this issue.

**Comment by photopea** [comment]
You are talking about ways to overcome the bug in a browser. If we did this for every browser / OS / device / hardware type ... Photopea would become extremely complicated and hard to maintain.

Photopea requires a browser, which allows detecting each keyboard press and release, right at the moment when it happens. If your browser can not do it, you will have problems with using Photopea. So if you still want to use PP in Firefox, please, disable this feature. https://support.mozilla.org/cs/questions/1084123
