### ISSUE TITLE
Unique Doubt - Canvas Shape

### ISSUE THREAD

**Issue by riazuddinshaik** [photopea/photopea#3380]
Dear Sir,

            Firstly, Thanks for all the help. I would like to change the canvas SHAPE same as image SHAPE in Photopea? 

This feature I needed to check whether the image will autofit into canvas if we create a canvas SHAPE?

Is it possible to create Canvas SHAPE like T-Shirt ?
Else Is it possible to make canvas shape changes same as image shape which would be inside canvas

Example : I made T-Shirt image fit into square shape canvas (transparent) but still the T-Shirt is inside the square shape as I still see outside of T-Shirt (image) has transparent canvas in square shape.

Now, I would like to see canvas shape same like T-Shirt Shape. Can we do it ?

Thanks in advance sir...

**Comment by riazuddinshaik** [comment]
As there is a script for image to autofit canvas ... Can you provide script for canvas to autofit same like shape of image ? 

Very helpful if possible...sir... thank you!

**Comment by riazuddinshaik** [comment]
@MichalSZZ 

Hello,
Thanks for your reply. I was looking solution for firat thing which you wrote. I understood. I have two quick questions.
(1) Any chances of erasing the unwanted canvas part?
(2) Any particular reason why it's impossible?

**Comment by riazuddinshaik** [comment]
@photopea 

Dear Sir,

Is it really impossible to make unwanted canvas erase or having canvas other than rectangle shape according to MichalSZZ?

If really impossible, can you make a script so that it may useful for many users across world who think such feature is possible in ONLY photopea?

Thankyou.

**Comment by MichalSZZ** [comment]
Every graphic aplikation saves files as a rectangle file. If you see something that have other shaper, it is rectangle too, but with the transparency.

For erasing the background there are mmetmanyhods in Photopea. Try to learn basics in Photopea learn page.

**Comment by photopea** [comment]
@riazuddinshaik Your English is quite hard to understand. Can you ask your friend or a colleague to write it for you?

This is a place to report bugs, not a place where we teach you how to use Photopea.

You can learn Photopea at www.Photopea.com/learn . Photopea can also do everything Adobe Photoshop can, so find a solution for Photoshop and do it in Photopea. Or ask at online forums about how to do it in Photoshop.
