### ISSUE TITLE
Issue: Double-clicking on slider doesn't reset the value but set the value to median

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3383]
For example, I create a Channel Mixer adjustment layer. The default value of red is 100%, the maximum value is 200% and the minimum value is -200%. When I double-click on the slider, it became 0% instead of 100%.

**Comment by photopea** [comment]
Ok, I made it go to 100% after the double-click. But a zero is also a frequent value for Channel Mixer, so I am not fully convinced that it is the right choice.
