### ISSUE TITLE
Feature Request: Let users set other fonts as default fonts

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3384]
This feature is useful for the people who are always using a particular font. 

Without this feature, we now have to select the fonts that we want manually everytime opened Photopea. And when opened the fonts menu, we might have to wait for seconds for loading the fonts menu.

**Comment by photopea** [comment]
In Photopea, whenever your select a text layer (in Layers), the font of that layer is set as the current font.

What if we make Photopea remember the last font you used, and that font will be set next time you open Photopea?

**Comment by nothingshiru** [comment]
Sounds great.

**Comment by photopea** [comment]
Done! When you open Photopea.com , you will see the font you used when you closed it :)
