### ISSUE TITLE
Can't find font

### ISSUE THREAD

**Issue by Marqqz** [photopea/photopea#3385]
Anyone knows this font? I used it in photopea but I ran into some problems now I can't find the font again. It would be great if anyone founds it!
![Untitled](https://user-images.githubusercontent.com/84855051/121234925-41218c80-c862-11eb-98af-72f08a35eb22.png)

**Comment by hxim** [comment]
I found it
![image](https://user-images.githubusercontent.com/6370548/121468635-6fff4600-c9bb-11eb-82bb-c5a9c0650f03.png)

**Comment by photopea** [comment]
Great! :)
