### ISSUE TITLE
Issue: With PWA on Android, pressing the back key will exit directly without asking

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3387]
Is there anything Photopea can do?

**Comment by photopea** [comment]
Closing Photopea PWA on Android (with unsaved work) also does not show any message. Same as closing Photopea in Chrome for Android. I think only Chrome developers can fix it.

**Comment by nothingshiru** [comment]
Indeed, closing Photopea in Chrome for Android would show message, unless you disabled "Pop-ups and redirects". (Settings > Advanced > Site settings > Pop-ups and redirects)
