### ISSUE TITLE
font size slider in Firefox

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#339]
Font size slider is not working properly in Firefox. It moves a little bit first but then stops while I am still holding mouse button.

**Comment by photopea** [comment]
This is strange. Note, that it happens only when a text layer is entered.

**Comment by photopea** [comment]
I found the smaller example: https://jsfiddle.net/x11py6Lw/

I filed a bug to Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1416509  After they fix it, everything should work. Until then, you can use the Label: Click on the text "Size" and drag left or right, it works the same way in all sliders.
