### ISSUE TITLE
Issue: Clicking words in vertical text layer would make the "line" vertical

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3390]
When create a new text layer and type words, the "line" is horizontal. Once clicked on the words, it became vertical and hard to be found.
![Screenshot_20210609_212614_com android chrome_edit_23713818395860](https://user-images.githubusercontent.com/79258245/121364665-92b53e80-c96a-11eb-9a37-79ba85f55dad.jpg)

https://user-images.githubusercontent.com/79258245/121364682-95b02f00-c96a-11eb-841a-43f7142212fb.mp4

**Comment by photopea** [comment]
Hi, I moved the cursor one pixel to the right, so that you can see where it is.

**Comment by nothingshiru** [comment]
The position of the cursor will be different for different letters in different fonts. It can still be hard to be found. Is it possible to make it always horizontal?
![Screenshot_20210617_225206_com android chrome](https://user-images.githubusercontent.com/79258245/122422011-61b6b880-cfbf-11eb-93a1-3a44e5c3dd46.jpg)
