### ISSUE TITLE
Saving issues

### ISSUE THREAD

**Issue by BigExplodingDonkey** [photopea/photopea#3391]
All of a sudden, photopea isn't saving my files. I just finished a project and went to download it, and it wouldn't save any sort of file or anything. It just does nothing. I've tried saving it as different file types- nothing. I'm using the website version so if I refresh all my work will be unsaved. Is there anything I can do to save my project or transfer it somewhere without losing its progress?

**Comment by photopea** [comment]
Did saving ever work before? Saving can be blocked by a browser extensions. Or maybe you set the browser settings to not allow Photopea (or all websites) save files.

**Comment by BigExplodingDonkey** [comment]
It has always worked before- and it isn't the browser or anything because I've been able to save in the past, and I opened a new photopea tab which I can save on. It's just a glitched tab I guess?

**Comment by BigExplodingDonkey** [comment]
I just need some way of transferring my work- the only problem is I cant move layers between tabs from my work- so I would have to physically copy and paste what's on each layer onto a new webpage, then recenter it because it would not automatically center it. You should add a feature to move layers to another photopea tab by dragging into the layers box.

**Comment by BigExplodingDonkey** [comment]
I fixed the issue- it was the browser actually- I don't know how this didn't happen for the other photopea tab I opened, but it was blocking the downloads because it said "this site is wanting to download multiple files- allow or deny access".

**Comment by photopea** [comment]
"this site is wanting to download multiple files- allow or deny access" - this issue is reported here at least twice a week.

I don't know what is causing it, because I am also using Chrome for many years, and it has never blocked the downloading process like that.
