### ISSUE TITLE
Feature request: Dither Filter

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3393]
Hi,
it is possible to have that filter in Photopea?

With it, we can simulate an old games, old printers etc.

Something like this (but that is not an official Photoshop filter):
https://i.stack.imgur.com/hXFkH.gif

http://www.ximagic.com/g_results_background.html

site that does it:
https://ditherit.com/

and some articles and YT about that:
https://surma.dev/things/ditherpunk/
https://www.youtube.com/watch?v=0L2n8Tg2FwI
https://www.youtube.com/watch?v=IviNO7iICTM

**Comment by photopea** [comment]
In Dithering, you need to specify a palette of 2 or more colors (e.g. white and black, or red,green,blue ...).

Dithering is a way to improve the look of an image, if the palette is limited. We limit the palette in PNG / GIF export, when you decrease the quality. I am planning to add a Dithering checkbox into a GIF export (as GIF has only 256 colors).

We also do dithering when drawing gradients. Try to draw a dithered gradient from white to black, you will see "grains".

Are you sure you just need to convert a layer to a dithered black-and-white layer? Or do you want to specify a palette, or ask Photopea to find a palette? 

Photopea can already find a palette of N colors in Image - Reduce Colors.

**Comment by MichalSZZ** [comment]
>
> 
> In Dithering, you need to specify a palette of 2 or more colors (e.g. white and black, or red,green,blue ...).
> 
Yes. I know that and selecting number of colors and the color for each one will be great for a parameter in filter window (something like in https://ditherit.com/)

>
> Dithering is a way to improve the look of an image, if the palette is limited. We limit the palette in PNG / GIF export, when you decrease the quality. I am planning to add a Dithering checkbox into a GIF export (as GIF has only 256 colors).
> 

Yes. I know it - when I made my first graphics on Amiga 600 there was the limitation for used colors per image. And when I wanted to draw people I had to change all the palette in that way to have more for skin colors. I was making fake pixel art dithering for gradients too :)
Now when I make animated GIFs in my job, I use dithering and many other functions in Export for the web - to have smaller and better looking images.

>
> We also do dithering when drawing gradients. Try to draw a dithered gradient from white to black, you will see "grains".
> 
That is a great feature for better gradient look. Thanks for adding that.

>
> Are you sure you just need to convert a layer to a dithered black-and-white layer? Or do you want to specify a palette, or ask Photopea to find a palette?
> 
Yes. I want to use it as a filter - not only as an export feature to flat images. Image that situation:
I am making a retro style advertising. Want to add gradient for the text. That gradient have 2-3 colors (like in 80s posters). And then I make dithering for it, and maybe transform it 8x bigger with nearest neighbor method for the better result (biggest pixels).
It can be good for ppl who are making retro pixel art graphics. I have read many post on forums where someone was asking about it. The only answers was to change color mode in Photoshop (image-mode-indexed colors). But that limit the functions of program itself.
>
> Photopea can already find a palette of N colors in Image - Reduce Colors.

Good news. I didn't know that.

**Comment by alexharris** [comment]
Hi, I am the maker of ditherit.com. Ditherit.com uses [RgbQuant.js](https://github.com/leeoniya/RgbQuant.js) to do the actual dithering. If photopea uses <canvas> element to display images, it probably would not be hard to implement! Let me know if I can answer any questions.

**Comment by photopea** [comment]
@alexharris The dithering is just four lines of code, there is no need for some huge library.

The author of RgbQuant.js is @leeoniya . You just reminded me how I argued with him about the quality of palettes in our PNG minifier UPNG.js https://github.com/photopea/UPNG.js/issues/43

**Comment by alexharris** [comment]
I use a bunch of features of the RgbQuant library for DitherIt!, although I am sure there are better ways to do it. It is just a learning project for me. 

Anyways, sounds like you have it covered. Good luck!

**Comment by photopea** [comment]
I have implemented the dithering filter under Filter - Other - Dither (at the end). Here is how it looks like: https://www.photopea.com/#iGFk6I3VV . Be sure to zoom in to 100% or more, it looks strange when zoomed out :)
