### ISSUE TITLE
Issue: Can't close the menu by clicking the button again

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3394]
This type of button.
![Screenshot_20210610_182523](https://user-images.githubusercontent.com/79258245/121510047-d1560200-ca19-11eb-9cbd-e56c40543c12.jpg)

![Screenshot_20210610_182431](https://user-images.githubusercontent.com/79258245/121510042-cf8c3e80-ca19-11eb-8c73-9daddd166d13.jpg)

**Comment by photopea** [comment]
This is completely up to a browser. We can not change it.

**Comment by nothingshiru** [comment]
The fonts menu can be closed by clicking the button again. It doesn't look like those buttons. I don't know what's the difference behind them. 

But there are some buttons look very similar to the fonts menu button but can't be closed by clicking the buttons again. Can you change them?

The brush menu, gradient menu, stroke menu.
![新建项目](https://user-images.githubusercontent.com/79258245/121670012-93231600-cadf-11eb-9cf5-2fa5fcbeac40.jpg)

**Comment by photopea** [comment]
I think you should be able to close your original menu in your browser if you click outside of it.

**Comment by nothingshiru** [comment]
Yeah, I can do that. 
But I have to find a empty area to click in case open/do something I don't want. It would be better that I can closed the menu by click the place where I click to open.
