### ISSUE TITLE
Issue: Unable to separate sliders of Blend If after clicked these buttons

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3396]
To reproduce:

1. Create a new project
2. Open Refine Edge/Magic Cut
3. Click any one of these five buttons
![Screenshot_20210611_024229_com android chrome_edit_116538345711383](https://user-images.githubusercontent.com/79258245/121580794-bc03c680-ca5f-11eb-91b7-57fe744ddaa7.jpg)
4. Close Refine Edge/Magic Cut window
5. Double-click the Background layer and try to separate sliders of Blend If by holding Alt key.

**Comment by photopea** [comment]
I am so sorry. It is fixed now.
