### ISSUE TITLE
Can't Save Files as PSD

### ISSUE THREAD

**Issue by CliqueIt** [photopea/photopea#3400]
I've been having a lot of problem with the program today. I've been able to figure most of them out but this one has me flummoxed. I can't save anything as PSD.

When I hit the Save as PSD option, nothing happens. When I hit Save as PSD/PSB . . . it tells me the file is 10kb and downloads a blank .txt file.

Not sure what to try next.

**Comment by photopea** [comment]
Hi, could you try these steps? Does anything help? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I think it was caused by a browser extension. There is nothing we can do about it. You decided to install an extension, so that it renames your files to TXT.
