### ISSUE TITLE
PWA and Service Worker offline support

### ISSUE THREAD

**Issue by LuHuangMSFT** [photopea/photopea#3401]
Photopea would be even more useful as an installed PWA if it could be used offline. This can be supported through adding offline logic to the service worker. There may be other requirements.

References:
https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/offline
https://preview.pwabuilder.com/serviceworker

**Comment by photopea** [comment]
I have added the offline support. It is not related to "installed PWA" or anything.

Simply, a browser caches Photopea when you are online, and if you go to www.Photopea.com offline, it will run a cached version.

**Comment by LuHuangMSFT** [comment]
Saw the changes in sw.js. Works great now even if offline.
