### ISSUE TITLE
Am not able to save my smart objects using command + s

### ISSUE THREAD

**Issue by Jeff1144** [photopea/photopea#3402]
I am working on a project and i am trying to save a smart object, and i pressed command + s and it isnt saving! i cant save it using file + save(smart object)! Why not? can you help?

**Comment by photopea** [comment]
We need to reproduce this problem somehow. Could you send us your PSD to support@photopea.com and tell us, which smart object we should try to edit and save?

**Comment by Jeff1144** [comment]
Actually, i fixed the problem. Thank you.

**Comment by Jeff1144** [comment]
i have a different problem.

**Comment by Jeff1144** [comment]
I saved over a file on accident, and now it has no layers so i am unable to edit the file and unable to change it back to the original.

**Comment by Jeff1144** [comment]
nvm i fixed it
