### ISSUE TITLE
Errors regarding "Save as PSD" and "Save as PSD/PSB..."

### ISSUE THREAD

**Issue by thethimteam** [photopea/photopea#3403]
After editing my project, when pressing "Save as PSD", no action occurs.

When clicking on "Save as PSD/PSB...", it displays that the file to be saved only has a size of 10kb, and when I click "Save", it saves a "null.txt" file on my device instead of the PSD file of the project.

![image](https://user-images.githubusercontent.com/85777268/121765130-5d336f80-cb7b-11eb-93c5-06a77a14efaa.png)

![image](https://user-images.githubusercontent.com/85777268/121765140-6c1a2200-cb7b-11eb-91cc-129c85928825.png)

**Comment by photopea** [comment]
Does it happen in a browser, which has no extensions installed? Browser extensions can modify any website in any way.

Also, you did not describe any steps how to reproduce this problem. I tried to save some random PSD and the size is not 1000 B.

**Comment by JabezVillamarzo** [comment]
Me too. In my case, I was doing two stroke layers in a layer. Not sure what you made of it, but here you go.

**Comment by photopea** [comment]
I am very sorry, there really was a bug, if you added a stroke to a layer, it could not be saved as PSD. It is fixed now.
