### ISSUE TITLE
Please make more words translatable

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3406]
Just let users to translate the words. Nothing bad, isn't it?

**Comment by photopea** [comment]
I think there are about 500 words that can not be translated now. We can offer 15 words for translation each week. Which 15 words should we make translatable this week?

**Comment by nothingshiru** [comment]
1.OK
    2.Reset
    3.Lock Guides
    4.Clear Slices
    5.Extras
    6.Save Selection
    7.Smart Object
    8.Artboard Tool
    9.Anti-alias
    10.Sample All Layers
    11.Dither
    12.Sampling
    13.Brush Center
    14.Start of Stroke
    15.Background Color

**Comment by photopea** [comment]
I think words like "OK", "Reset", "Extras", "Anti-alias" are the same or similar in all languages (which use the Latin alphabet). But I guess they do not say anything e.g. to Chinese people, who can not read latin.

@MichalSZZ  @Avagp  what do you think guys?

**Comment by avagp** [comment]
You are right. Those words comes from latin languages. But obviously not mean a thing to other roots.

I believe you should let every word to be translatable.

And if you have a limit of 15 per week, and there is 500 not translated by now, maybe you should begin :P

**Comment by MichalSZZ** [comment]
@photopea yes, "OK", "Reset" are obvious for everyone who use computer. Some other can be translated but it is not necessary. For example "extras". Anti-alias isn't translatable in my language I think... I can use some other word for replace it but it wouldn't be anti-aliasing.

I didn't look in translation of Photopea for a long time. But I think that biggest problem is for non latin lenguages ego don't know latin letters.

**Comment by avagp** [comment]
But if chinese users for example translate OK to OK. So be it.

They are the only ones who knows if those words are commonly known in their
language :)

**Comment by nothingshiru** [comment]
The words are quite different.
![Screenshot_20210616_013355](https://user-images.githubusercontent.com/79258245/122099439-92beae00-ce44-11eb-9d46-d41f9374892d.jpg)

**Comment by avagp** [comment]
:)

See, let all words be translatable.

**Comment by nothingshiru** [comment]
I selected about three hundreds of phrases.
![Screenshot_20210620_211831](https://user-images.githubusercontent.com/79258245/122675745-6ec8e700-d20d-11eb-87a2-034f222f7db0.jpg)

Here's the list. 
[List 2021.06.20.zip](https://github.com/photopea/photopea/files/6682419/List.2021.06.20.zip)
You can do it from left to right.

**Comment by photopea** [comment]
I just remembered, when I released Photopea in 2013 for the first time, I refused to make translations for several years, because I thought that all people will know English  soon (or at some point) :D

**Comment by avagp** [comment]
XD

**Comment by nothingshiru** [comment]
> We can offer 15 words for translation each week. 

There was no progress on this after the first week :(

**Comment by photopea** [comment]
Do you have any new suggestions, what should be translated? E.g. 10 of them?

I am "resisting" so much, because I think that more and more people can speak English, and I am afraid, that if we change the structure at some point, some phrases might become redundant.

**Comment by nothingshiru** [comment]
There are still many people who do not understand English. Language is a barrier that needs to be removed.

One of the reasons I would like to see a full native language interface is that it would not only make it easier for the people to understand what the options do, but it would also allow people to find the options they are looking for faster. 

> if we change the structure at some point, some phrases might become redundant.

I don't quite understand this.

**Comment by nothingshiru** [comment]
Here are the 10 words I picked.

1. Preset Manager
2. Reduce Colors
3. Add (in Apply Image)
4. Preserve Transparency
5. Resample
6. Bicubic Shaper
7. Arrow (in Parametric Shape tool)
8. Brush Center (in Color Replacement tool)
9. Start of Stroke
10. Background Color

**Comment by avagp** [comment]
That will be a good little method.

Nothingshiru can give words that are not translatable.

I can do the same in Spanish if you will


Le jeu. 23 sept. 2021 à 08:13, nothingshiru ***@***.***> a
écrit :

**Comment by photopea** [comment]
I made these phrases translatable, thanks! :)

**Comment by nothingshiru** [comment]
Picked some new. 

    1.Profile
    2.Artboards
    3.Slices From Guides
    4.Sampling Rings
    5.Zoom
    6.Sharp
    7.Crisp
    8.Strong
    9.Smooth
    10.Social

**Comment by photopea** [comment]
I made them all translatable. I am not so sure about Social - maybe we should rename it? But "Social networks" is too long.

**Comment by nothingshiru** [comment]
I have no idea neither...

**Comment by nothingshiru** [comment]
Got these.

    1.Reduce Noise
    2.Auto
    3.Apply at canvas bounds
    4.Current Path
    5.Scale Effects
    6.ZigZag
    7.Kaleidoscope
    8.Flame
    9.Fibers
    10.Solarize
    11.Trace Contour
    12.Wind
    13.Fourier
    14.Fourier Transform
    15.Inverse Fourier Transform
