### ISSUE TITLE
Hotkey hints in searchbar

### ISSUE THREAD

**Issue by JerryGreen** [photopea/photopea#3407]
I really like the search bar so I don't have to navigate the whole menu, but instead of just menu items:

![image](https://user-images.githubusercontent.com/13215662/121814455-a9b9a080-cc8a-11eb-86f0-fbc929d1de50.png)

I'd like to have something like this:

![png](https://user-images.githubusercontent.com/13215662/121814448-9e667500-cc8a-11eb-9222-5114102fa453.png)

**Comment by photopea** [comment]
that is a great idea! I just added it :)
