### ISSUE TITLE
Suggestions for the texts

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3408]
1. Change 简化字 中文 to 简体中文, 正體字 中文 to 繁体中文. (In More - Language, and www.photopea.com/translate)
2. Make "Apply Image" the same as the one in Image menu.
![Screenshot_20210614_100515](https://user-images.githubusercontent.com/79258245/121830652-0b642400-ccf8-11eb-85d3-6c9835bedc93.jpg)

3. Make "Add Guides" the same as the one in View menu.
4. Make "Clear Guides" the same as the one in View menu.
![Screenshot_20210614_101005](https://user-images.githubusercontent.com/79258245/121830966-e7551280-ccf8-11eb-9f97-e6d41e443ba8.jpg)

5. Change px, in, etc. in Canvas Size and Image Size to Pixels, Inches, etc. Make them the same as the words in Preferences.
![Screenshot_20210614_101604](https://user-images.githubusercontent.com/79258245/121831473-1e77f380-ccfa-11eb-87ea-354f71a31202.jpg)

6. Make the "Merge" in Layer - Animation different from the one in path menu in Direct Select.

7. Changes in More - Theme.
Change Silver to Light Grey, 
Black to Grey, 
Iron Blue to Blue, 
Snow White to White, 
Danish Purple to Purple, 
Spuer Black to Dark Grey.

8. Make the "Randomize" in Fibers filter and Wave filter the same as the one in New Project window.

**Comment by photopea** [comment]
I fixed all expect of 5 and 6.

I guess "mm" and "cm" are not used in Chinese, but they are clear to the rest of the world, I think. I do not want to show long words to everyone. 

There is a similar problem: Some countries do not use numerals like 0, 1, 2, ... They use 一二三四五六七八九十  in China and Japan. Or arabic numerals: https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Clock-in-cairo-with-eastern-arabic-numerals.jpg/330px-Clock-in-cairo-with-eastern-arabic-numerals.jpg

**Comment by nothingshiru** [comment]
I added 8.

"mm" and "cm" are very common in China too. And they are just two letters in Chinese.

We use 0, 1, 2, ...too. I have never learned or seen the numerals on that clock.

**Comment by photopea** [comment]
I added long unit names to Image - Image Size, Canvas Size and New Project. I fixed "Randomize", too. Thanks! :)

**Comment by nothingshiru** [comment]
Excellent! :)

Here are two more.

1. Make the "Normal" in Filter - Distort - Spherize the same as the one in Blend Mode.

2. Change the "Size" in Filter Gallery - Artistic - Paint Daubs to "Brush Size". Make it the same as one in e.g. Dry Brush.

Could you please reopen and leave this "issue" open till all words is translatable? I might find more others.

**Comment by photopea** [comment]
Fixed! I am afraid all phrases will never be translatable. There are too many of them, and I change some of them from time to time.

**Comment by nothingshiru** [comment]
In filter Gallery, there is "Brush type" in Paint Daubs, but a "Grain Type" in Grain. I think the "Brush type" should be changed to "Brush Type".

**Comment by photopea** [comment]
fixed, thanks! :)

**Comment by nothingshiru** [comment]
New

1. Make the "Square" in Minimum/Maximum filter and Lens Blur filter - Shape the same as the one in Wave filter.

2. Change the "px, %, mm, in" in Export as window as well.

**Comment by photopea** [comment]
1. fixed
2.  it would take more space, which is a problem on tiny screens.
3. I think these phrases could be changed in the future, so I am not sure about them yet.

**Comment by nothingshiru** [comment]
2 more.

1. Make the "Invert" in Lens Blur filter the same as the one in adjustments.

2. Make the "Path" in Path Select the same as the one in the mode menu of Pen tool.
![screenshot_20210926_120352_edit_132066371820473](https://user-images.githubusercontent.com/79258245/134793307-a4fb5143-ed0b-42db-9f6b-901f862e8fd3.jpg)
![Screenshot_20210926_120401_com microsoft emmx_edit_132055173509016](https://user-images.githubusercontent.com/79258245/134793310-51ce7ce7-0b06-4770-ae14-db4b765399b8.jpg)

**Comment by photopea** [comment]
ok done :)
