### ISSUE TITLE
Interface does not use full width of display

### ISSUE THREAD

**Issue by gingerbeardman** [photopea/photopea#3409]
I work with a portrait display, 1080px wide, so this problem makes the interface even narrower.

This is running in Chrome.

Q: is there any way to make use of the full width? If I pay for Premium?

- Portrait display
  ![Screen shot 2021-06-14 at 10 01 17](https://user-images.githubusercontent.com/49612/121867543-f8515400-ccf7-11eb-8b40-3406a462f73e.png)

- Landscape display
  
![Screen shot 2021-06-14 at 10 05 28](https://user-images.githubusercontent.com/49612/121867719-29ca1f80-ccf8-11eb-9646-beb7c0bafe53.png)

**Comment by photopea** [comment]
Hi, there should be advertisement on the right side of Photopea. You are probably deleting it.

Please, watch ads in Photopea. Almost nobody wants to pay for Premium, and Photopea would not exist today, if everyone hided ads as you do.

**Comment by gingerbeardman** [comment]
Hi, thanks. I pre-emptively disabled my adblock because of this reason but they are still not displayed. I will investigate how else they may be getting blocked.

Thanks for making a great app.
