### ISSUE TITLE
API - can't open the file from another server, CROSS is enabled

### ISSUE THREAD

**Issue by nikisbeta** [photopea/photopea#341]
Hi,
Photopea  can't open the file from another server.
https://www.photopea.com/?p={%22files%22:[%22http://services.data.tvprofi.cz/icon256.png%22]}

CROSS is enabled. 
Server with test file return Access-Control-Allow-Origin="*"
http://services.data.tvprofi.cz/icon256.png

Stay hanging on loading :
![loading](https://user-images.githubusercontent.com/8208104/32670944-c5c91cc8-c645-11e7-9ecf-1de35b368005.jpg)

**Comment by photopea** [comment]
Hi, in my browser console, I see this:

pp.js:5604 Mixed Content: The page at 'https://www.photopea.com/?p=%7B%22files%22:%5B%22http://services.data.tvprofi.cz/icon256.png%22%5D%7D' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://services.data.tvprofi.cz/icon256.png'. This request has been blocked; the content must be served over HTTPS.

I think your website has to use HTTPS, just as Photopea does :(

**Comment by nikisbeta** [comment]
Thank you, I've added SSL and everything works !

**Comment by photopea** [comment]
perfect! :)
