### ISSUE TITLE
Save As > SVG File like Adobe Illustrator

### ISSUE THREAD

**Issue by DrewS138** [photopea/photopea#3410]
Hello, 

For Photopea, any plans to add the same save as options like Adobe Illustrator for SVG Files?
![svg](https://user-images.githubusercontent.com/74819605/121979631-e4782180-cdcd-11eb-8bcd-f2398bfe9930.png)

**Comment by photopea** [comment]
Hi, but what exactly is wrong with SVG files from Photopea? What exactly are you missing?

**Comment by photopea** [comment]
I have to close it because of lack of details. I think Photopea has the important SVG settings, and other settings are not needed.
