### ISSUE TITLE
Background Color Overlay

### ISSUE THREAD

**Issue by ozguraybar** [photopea/photopea#3411]
When i click background ==> Blending Options ==> Color Overlay and I apply black color, this program is stopped.

**Comment by Crytkee** [comment]
I have this problem too.

**Comment by photopea** [comment]
I am very sorry, it should be fixed now.

Your browser will show you the old Photopea for the next hour (because of our caching), so clear your cache (Shift+F5), or use Photopea in Incognito in the next hour.
