### ISSUE TITLE
Color Overlay

### ISSUE THREAD

**Issue by Crytkee** [photopea/photopea#3412]
I'm trying to make a symbol for the USFR (United Soviet Federation of Roblox) and I tried to do a color overlay on the sickle and it wouldn't overlay and instead, the site crashed.

**Comment by photopea** [comment]
I am very sorry, it should be fixed now.

Your browser will show you the old Photopea for the next hour (because of our caching), so clear your cache (Shift+F5), or use Photopea in Incognito in the next hour.

**Comment by Crytkee** [comment]
Alright, thank you!
