### ISSUE TITLE
cant export files as jpg

### ISSUE THREAD

**Issue by teddyjain** [photopea/photopea#3414]
Unable to export files as jpg or any other format.

**Comment by photopea** [comment]
Did it ever work before? Could you disable all browser extensions and try it again?

If you use Google Chrome, it often blocks the download of more than one file (and you should see an alert about it).

**Comment by pamoroso** [comment]
I'm experiencing a [similar issue](https://twitter.com/amoroso/status/1405123374175735810). None of the options under the `Export as` menu work: when clicked nothing happens. The options do work in incognito though, so it may be an extension issue but I don't get any download alerts.

Yesterday everything worked fine. I'm using Chrome OS Stable 91.0.4472.102 on an ASUS Chromebox 3.

**Comment by photopea** [comment]
Can you reload Photopea with Shift+F5?

**Comment by pamoroso** [comment]
Clearing the cache and reloading fixed the issue for me, thanks.
