### ISSUE TITLE
كيفية إضافة الطبقات وحذفها

### ISSUE THREAD

**Issue by fouadelomari** [photopea/photopea#3415]
كيفية إضافة الطبقات وحذفها

**Comment by photopea** [comment]
We have manuals only in English: https://www.photopea.com/learn/layers

**Comment by fouadelomari** [comment]
اقصد النوافذ لا اقدر ان اتحكم في حذفها و فتحها وشكرا

**Comment by photopea** [comment]
Sorry, we discuss only in English here.
