### ISSUE TITLE
16 bit / 32 bit depth support

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#3417]
It would be nice if we allowed editing 16 bit and 32 bit images.

Adobe Photoshop and Gimp already support it.

**Comment by SimonHeggie** [comment]
YES!

Thankyou!! This will supercharge Photopea's compositing capabilities.

-S

**Comment by mustafaGFX** [comment]
yes it would be great, I have suggested this one year ago, and the RGB/CMYK colors as well

**Comment by photopea** [comment]
I have implemented the 16-bit and 32-bit color depth: https://blog.photopea.com/photopea-5-6-advanced-color-depth.html
