### ISSUE TITLE
Photopea delay

### ISSUE THREAD

**Issue by Jordansosa47** [photopea/photopea#3418]
is:issue is:open My Photopea is extremely slow. I have tried using the app on chromebook and the website through chrome and at moments it will run smooth but then it will start to run very slow. When I try to apply filters, or use sliding bar for brightness and contrast it is delayed. I have tried turning off browser extensions and incognito mode, But it still is slow

**Comment by photopea** [comment]
How fast is your Chromebook? How large are your photos? If your chromebook is old and photos are large (e.g. 4000x6000 = 24 million pixels), some operations can be slow.

**Comment by photopea** [comment]
I have to close it because of lack of details.
