### ISSUE TITLE
Error handling on the height and width inputs when creating a new project

### ISSUE THREAD

**Issue by KillickNZ** [photopea/photopea#3419]
When creating a new project and setting the height and width, if the user puts in a large enough number the website crashes and doesn't respond

**Comment by photopea** [comment]
Photopea requires 4 Bytes of RAM for each pixel. And sadly, websites can not check how much RAM a computer has.

So if you enter 50,000 x 50,000 pixels = 10 GB of RAM, there is no way for us to know, if it will fail or not :(  We do not want to set a limit e.g. to 10,000 x 10,000, as it would restrict users, who have plenty of RAM
