### ISSUE TITLE
Layers window issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#342]
When I first open Photopea and no file is opened.
In upper part of "Layers" windows: You can manipulate controls for Blending mode and Opacity (they are not disabled as should be) and recieve this error when you change something there:

Uncaught TypeError: Cannot read property 'selected' of null
    at m_.Kz (pp.js:5190)
    at te.Uk._ (pp.js:6)
    at te.h._ (pp.js:4053)
    at te.PR (pp.js:4221)

**Comment by hxim** [comment]
Also you can go to Layer Comps - New Layer Comp
or Properties - Mask
both producing different errors...

**Comment by photopea** [comment]
Hi, this all should be fixed now. Thank you for reporting it.
