### ISSUE TITLE
Changing a smartobject deletes the free transformation applied to it.

### ISSUE THREAD

**Issue by FynniX** [photopea/photopea#3421]
Hello,
I have a smartobject with text in it. If I change the text inside and save it, then the transformation on the smart object changes.
See pictures:
1. Without change:
![1](https://user-images.githubusercontent.com/47634930/122432594-c0ffd300-cf95-11eb-9c41-9679646559b9.PNG)
2. With change:
![2](https://user-images.githubusercontent.com/47634930/122432621-c52bf080-cf95-11eb-8d86-9d5c8b574648.PNG)

Example File:
[beispiel.zip](https://github.com/photopea/photopea/files/6671571/beispiel.zip)

**Comment by photopea** [comment]
I tried to do the same thing in Adobe Photoshop, and absolutely the same thing happens, as in Photopea.

How did you produce your PSD file? Is there any software, that can modify your smart object while keeping it "bended"?

**Comment by FynniX** [comment]
Hi, 
which version of photoshop do you have? Thats how it works in photoshop at my pc:

1. Without change:
![1](https://user-images.githubusercontent.com/47634930/122447269-db40ad80-cfa3-11eb-8e42-09bee4f4b09b.PNG)
2. With change:
![2](https://user-images.githubusercontent.com/47634930/122447291-e1368e80-cfa3-11eb-802e-29ea892e62d1.PNG)

At my photoshop it does work.

**Comment by photopea** [comment]
I tried it in Photoshop 20.0.3 . What version do you have?

Why exactly is the smart object like this? Is there any warp or Liquify or something applied?

**Comment by FynniX** [comment]
I use Photoshop 22.3.1
i will answer the second question later.

**Comment by FynniX** [comment]
We use the warp function of photoshop

**Comment by MichalSZZ** [comment]
I don't k ow in which PS version it was added but there is a option to add horizontal and vertical sections to warp tool.

And now I see that in PS 21 they added something new features that I even did not tested yet

https://helpx.adobe.com/photoshop/using/warp-images-shapes-paths.html

**Comment by FynniX** [comment]
Will you add the new feature of photoshop to photopea? Would be cool.

**Comment by photopea** [comment]
It seems quite complex to make. Maybe I will wait a year or two, as more people ask about this feature.
