### ISSUE TITLE
TIFF file shown as random coloured pixels

### ISSUE THREAD

**Issue by deflated-fruit** [photopea/photopea#3424]
Uploading a large (232MB) TIFF image in Photopea shows a mess of multicoloured pixels with no bearing to the original image
<img width="1267" alt="Screenshot 2021-06-18 at 11 47 01" src="https://user-images.githubusercontent.com/66580940/122549892-e7bc1900-d02a-11eb-81ca-3e0743ce2fee.png">

**Comment by photopea** [comment]
Is there any program which opens your TIFF correctly?

Could you send us your tiff to support@photopea.com?

**Comment by photopea** [comment]
I have to close it because of lack of details.
