### ISSUE TITLE
convert selection into path

### ISSUE THREAD

**Issue by thomasruta** [photopea/photopea#3425]
misses some selection parts in order to convert a raster to vector.
No matter if I use the autoselect or click in the layer to select.
![image](https://user-images.githubusercontent.com/177512/122554308-1b05a480-d039-11eb-8dd6-52cef5d01a49.png)
the convert selection to path does not work propperly :-(
![image](https://user-images.githubusercontent.com/177512/122554506-5bfdb900-d039-11eb-890c-a693955c728d.png)

Greetz
T

**Comment by photopea** [comment]
Hi, could you try Image - Vectorize Bitmap instead? I think it should work much better.

**Comment by thomasruta** [comment]
But still it is back if it doesn't convert the selection to path is selected

Photopea ***@***.***> schrieb am Sa., 19. Juni 2021, 13:29:

**Comment by photopea** [comment]
Could you share your image, so that I can reproduce it?
