### ISSUE TITLE
Why is the unit of stroke pt instead of px?

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3426]
![screenshot_20210618_212352](https://user-images.githubusercontent.com/79258245/122568221-1ca48c00-d07c-11eb-8b42-daac9ae5d313.jpg)

I tested it. It seems to be the same as px. And it is px in Photoshop.

**Comment by MichalSZZ** [comment]
I always wanted to ask about it :D and why it is set ro 4.4pt not  r
Full 4 :)
If I good remember (now I can't look because I am on vacation)... in font size there is "px" and in Photoshop is "pt"?
But there if I good remember that pt is better for different PDI

**Comment by photopea** [comment]
I think someone asked me in the past to change "px" to "pt" and I did it.

I changed it back to "px". The "pt" unit means physical size: 1/72 of an inch. This field represents pixels in our case.
