### ISSUE TITLE
Adjustment Layer - Only Apply to first Layer Below

### ISSUE THREAD

**Issue by WebSpectrum** [photopea/photopea#3427]
How do you apply an adjustment layer to just the uppermost layer and NOT to all other layers below that?

**Comment by WebSpectrum** [comment]
To answer my own question - right click the adjustment layer in layers panel => clipping mask ... It was right there in front of me just didn't see it ...

**Comment by photopea** [comment]
That is right. You can enable "clipping mask" to any layer.

To be precise, "clipping mask" makes that layer use the transparency of a layer below, it "crops" the layer by a layer below.
