### ISSUE TITLE
Not Full width in ultra-wide monitor

### ISSUE THREAD

**Issue by bigmpc** [photopea/photopea#3428]
I am using 2560 x 1080 ultra-wide monitor but Photopea can not cover the whole screen as you see:

![Photopea on in ultra-wide monitor](https://user-images.githubusercontent.com/11869014/122587552-7b9edc80-d04d-11eb-9f56-ac0e0a6ecf59.png)

I

**Comment by photopea** [comment]
There should be advertisement on the right side. Please, watch our ads, or get a Premium account (to have "full width"), it costs less than a dollar a week.
