### ISSUE TITLE
Double-clicking customizable filters on smart objects with the same source makes the smart objects move to the same location

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#3429]
When a filter with a menu gets added to a smart object and afterward a filter (with or without a menu) gets added to another smart object with the same source, double-clicking the filter of the former object makes the former object move to the same location as the latter object.
It doesn't matter whether a smart object is the original or the copy; only the order in which the filters are added matters. The filter with a menu must be added first.

1. Open a new document in Photopea. Create a new layer, which should automatically be called Layer 1.
2. Switch to the brush tool. Draw on Layer 1. Right-click Layer 1 in the layers panel and choose Convert to Smart Object.
4. Switch to the move tool. Hold down the alt key and click-and-drag the brush mark to a different place so that a second (duplicate) smart object (which should automatically called Layer 1 copy) gets created.
5. Make one of the smart objects the active layer. Click Filter > Blur > Gaussian Blur. Click OK on the menu that pops up.
6. In the Layers panel, switch the active layer to the smart object without a filter. Click Filter > Blur > Average.
7. In the Layers panel, double-click the Gaussian Blur filter. >> In the workspace, the layer with Gaussian Blur teleports to the same location that the layer with Average is in.

If Layer 1 copy is the layer in step 5 and Layer 1 is the layer in step 6, then Layer 1 copy teleports to Layer 1 in step 7:
![image](https://user-images.githubusercontent.com/51429646/122657754-62bd2680-d134-11eb-9e36-46f9d61cb29f.png)
![image](https://user-images.githubusercontent.com/51429646/122657758-6cdf2500-d134-11eb-91eb-5845e2112e0f.png)

If Layer 1 is instead the layer in step 5 and Layer 1 copy is the layer in step 6, then Layer 1 teleports to Layer 1 copy in step 7.

**Comment by photopea** [comment]
It has been reported before, but I did not know how to reproduce it.

Now, I know, and I fixed it. Thank you very much! I really appreciate what you are doing. Without you, these bugs could remain in Photopea for many next years.
