### ISSUE TITLE
Layer Style Window Doesn't close

### ISSUE THREAD

**Issue by TaoPlakrapong** [photopea/photopea#3432]
This window (number 1) doesn't close. So normally if i double click on "number 2" i get another window, were you have many
option you can do. But now .... this window pops open when i double click on "number 2".. and can't close it, and it is not the window what i want.  

![pea002](https://user-images.githubusercontent.com/86193507/122676210-5640d880-d1dd-11eb-9cf5-12f7c9e946dd.jpg)

**Comment by photopea** [comment]
Could you reload Photopea with Shift+F5 (or clear the cache somehow, to be sure you are using the latest version)?
