### ISSUE TITLE
[bug] Zoom keyboard controls minus "sticks"

### ISSUE THREAD

**Issue by aklatzke** [photopea/photopea#3433]
Platform: Mac
Chrome running in "Saved App" mode (from taskbar)

When using CMD +/- for zoom controls, after you press "-", the camera will only zoom out on subsequent presses of either "+" or "-"

Repro:
- open any document
- press CMD + to zoom in
- press CMD - to zoom out
- press CMD + => will zoom out rather than in

Releasing CMD and pressing + will work again

**Comment by photopea** [comment]
Hi, this is a well-known bug in Mac OS: https://stackoverflow.com/questions/25438608/javascript-keyup-isnt-called-when-command-and-another-is-pressed . If Command is pressed, releasing other keys is not reported to a program (and program thinks that all keys are still pressed).

https://github.com/electron/electron/issues/5188

Only Apple can fix this bug. You can ask Apple to fix it, or use Photopea on a different device.
