### ISSUE TITLE
Crop Tool - default crop size in Fixed Ratio

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3434]
When I have some photo in landscape orientation (for example 1920x1080 px) and set Crop to Fixed Ration 1:1, it makes square crop area but outside the  project size for the height.
It should to be a crop area inside the project size - in my example 1080x1080 as a first crop area, not 1920x1920 as it is now.

**Comment by photopea** [comment]
Fixed! Now, if you have a fixed ratio, the cropping rectangle is as big as possible, but INSIDE the rectangle of a document.

**Comment by MichalSZZ** [comment]
Great! Thanks
