### ISSUE TITLE
Crop Tool - first crop area from project size

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3435]
It will be easier when the user will have the cropping area view enabled, just when he is switching to Crop Tool.

Now in Photopea he should to use one of the predefined buttons or draw a new crop area.
In Photoshop when user want to use crop Tool - just when he use C shortcut or Tool icon, it sets the first and default cropping area from canvas size. Then User can crop only the sides of the project without any worries about height. Or draw any new cropping area by dragging as always.

**Comment by photopea** [comment]
I implemented it! 

Note, that there is a special thing (in Photoshop, and now, in Photopea). If you just enabled the Crop tool, and there is a default rectangle, you can click-and-drag to draw a new rectangle.

But in all other cases, you can not draw a new rectangle over the current one. You should "escape" the current rectangle first.

**Comment by MichalSZZ** [comment]
@photopea I know abiut that special thing in Photoshop and even I wanted to describe how it should to work, but with my terrible english it could be a bigger mess with that information than without ;)
