### ISSUE TITLE
Vectorize Bitmap

### ISSUE THREAD

**Issue by mattfertitta** [photopea/photopea#3436]
Every time I use Vectorize Bitmap I get kicked off of the Photopea platform.

**Comment by photopea** [comment]
Could you send us an image, which you are vectorizing, to support@photopea.com ?

**Comment by mattfertitta** [comment]
Sure, I can. But It’s any and every image I try to use

**Comment by photopea** [comment]
I tried it on this image: 
![bunny](https://user-images.githubusercontent.com/15955558/122772115-57d6d300-d2a7-11eb-8ade-475be1cdb164.png)

and it works well. Does it work for you on that image?

**Comment by mattfertitta** [comment]
Thanks. Let me try

**Comment by mattfertitta** [comment]
I tried it, and it does work, quite slowly. 






Although, when I try to see other options this is what I get almost every time. 

I’m ok with it running a bit slow, as normal. 
But I usually get an Error has occurred message and lose whatever work I had.

**Comment by photopea** [comment]
Could you please reply in a browser at https://github.com/photopea/photopea/issues/3436 ? I do not see any images in your response.

Please, send me an image, which makes the vectorization crash, to support@photopea.com

**Comment by mattfertitta** [comment]
This is the usual message I get 

It just happened when I tried they image

**Comment by photopea** [comment]
You are probably sending images, but they are not displayed. Please, write replies at a Githubs website.

**Comment by mattfertitta** [comment]
Ok. Thanks. 

Good to know my images aren’t appearing in my emails. That’s fun. 
Thanks for letting me know

**Comment by photopea** [comment]
You did not send emails to us (to photopea.com), you were sending them to github.com .

**Comment by photopea** [comment]
Could you send an email to support@photopea.com , or share it with us in any other way? I am sorry that GitHub does not fully share your emails with us.
