### ISSUE TITLE
Keyboard shortcuts for Canvas Size dialog

### ISSUE THREAD

**Issue by gingerbeardman** [photopea/photopea#3438]
When Canvas Size dialog is displayed:

(In Acorn, or modified Photoshop) I can press: <kbd>cmd</kbd>+<kbd>numeric pad number</kbd>

to choose one of the 9 directions to anchor crop

```
1 2 3
4 5 6
7 8 9
```

eg. cmd+4 choose West direction

<img width="354" alt="Screen shot 2021-06-21 at 21 25 30" src="https://user-images.githubusercontent.com/49612/122823391-35f54480-d2d7-11eb-94c4-feb63504e9ef.png">

It would be great to have these added.

**Comment by photopea** [comment]
Is there any place on the internet, which mentions this shortcut? I have never heard about it. I don't want to add a shortcut which will be impossible to find.

Also, I could allow moving the center point with arrow keys instead.

**Comment by gingerbeardman** [comment]
Hmm, I don't know, but I'll see if I can find some docs.

I have been using these shortcuts for 20 years 😅 they are muscle memory for me.

**Comment by gingerbeardman** [comment]
Sorry, I just checked and I added the feature myself using scripts. D'oh!

It's originally from in the Acorn image editor, not Photoshop 🤪

But, it would still be good to get keyboard control for this. Cursor keys is a good idea.

**Comment by photopea** [comment]
I implemented it. But you need to click outside the text field, because in the text field, the cursor keys modify the value.

**Comment by gingerbeardman** [comment]
Works great, thanks!
