### ISSUE TITLE
First responder text field

### ISSUE THREAD

**Issue by gingerbeardman** [photopea/photopea#3439]
When I open Canvas Size dialog, I expect to be able to start typing the numbers immediately.

Currently I have to focus the text field using the mouse, which interrupts my workflow.

Tab cannot be used to jump to text field because it is the key to hide/show UI.

Please make first element in each dialog have focus when it is shown.

<img width="359" alt="Screen shot 2021-06-21 at 21 27 40" src="https://user-images.githubusercontent.com/49612/122823625-82d91b00-d2d7-11eb-867a-7e789247dfa5.png">

**Comment by photopea** [comment]
Done, you can even use Tab now :)

**Comment by gingerbeardman** [comment]
👏

many thanks!

**Comment by gingerbeardman** [comment]
I use noticed that once you reach Relative control, tab stops working and hides UI again? At that point, it's not possible to Shift+Tab to go backwards through the tab order.

**Comment by photopea** [comment]
You can switch through a Checkbox with a Tab now.

It was blocked before, maybe it was blocked on purpose, and now, another bug might arise, which I am not aware of :(

**Comment by gingerbeardman** [comment]
Thanks again.

Such is the way with software development. All you can do is try your best.
