### ISSUE TITLE
Where is the button open on the URL in quick access?

### ISSUE THREAD

**Issue by splincode** [photopea/photopea#344]
![image](https://user-images.githubusercontent.com/12021443/32698052-f156cccc-c7ae-11e7-89bf-5af547503f11.png)

**Comment by photopea** [comment]
Hi. I think if we add that button to the Quick Access, there would be too many buttons. Please, use File - Open from URL instead.

You can also copy an image from elsewhere (right-click - Copy, and then paste it into Photopea).

**Comment by splincode** [comment]
It is unfortunate that the button will not be added

**Comment by photopea** [comment]
File - Open from URL takes only 0.5 sec more time :)
