### ISSUE TITLE
Photopea error, select box when blending options

### ISSUE THREAD

**Issue by 3cvil** [photopea/photopea#3442]
https://imgur.com/rEzCKD0

When you are editing text, the box appears on the text whether you have selected it before or not. I think this is a bug because it makes it much harder to see the text with a box on top of it.

**Comment by photopea** [comment]
I think you have the Move tool activated, and you enabled "Transform Controls" at the top, am I right? You can disable it there, too.

**Comment by 3cvil** [comment]
> I think you have the Move tool activated, and you enabled "Transform Controls" at the top, am I right? You can disable it there, too.

Yeah that works, so the issue is solved but I think that it should be turned off by default :)

**Comment by photopea** [comment]
It is turned off by default, you yourned it on yourself, or someone broke into your computer :D

**Comment by 3cvil** [comment]
> It is turned off by default, you turned it on yourself, or someone broke into your computer :D

oh no D: 
I meant when you are on the blending options gui the transform box closes automatically then re opens when you close it :)

**Comment by photopea** [comment]
> oh no D:
> I meant when you are on the blending options gui the transform box closes automatically then re opens when you close it :)

It should not work like that now.

**Comment by 3cvil** [comment]
> > oh no D:
> > I meant when you are on the blending options gui the transform box closes automatically then re opens when you close it :)
> 
> It should not work like that now.

already fixed?!

**Comment by 3cvil** [comment]
also is there a shortcut to do confirm as its a pain to keep having to scroll up and tick the little checkmark, but it cant be "ENTER" as with text it makes a new line

**Comment by photopea** [comment]
There is Ctrl +Enter :) 

What exactly do you want to be fixed?
