### ISSUE TITLE
"LOADING" bar is persistent.

### ISSUE THREAD

**Issue by Jim2525** [photopea/photopea#3445]
It covers several controls,
![photopea bug](https://user-images.githubusercontent.com/58643637/123026099-9eacf180-d3a9-11eb-90e0-81509316d40d.png)

**Comment by photopea** [comment]
Do you know what is the text  #..... in the URL bar and who put it there? I think it is related.

**Comment by Jim2525** [comment]
I have access to photopea through the MediaCloud app.
________________________________

**Comment by photopea** [comment]
Try to report it to MediaCloud then. There is a problem with their configuration of Photopea.

**Comment by photopea** [comment]
I have to close it because of lack of details.
