### ISSUE TITLE
Issue: Unable to use Hand tool and Zoom tool when Layer Style window is opened

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3446]
When any other window is opened, we are able to use Hand tool and Zoom tool.

**Comment by photopea** [comment]
If you are editing the Gradient fill, clicking and moving in the document will move the center of a gradient. The same goes for Pattern fill. If you are editing a Drop Shadow, Inner Shadow or Satin, dragging in the document will move the shadow.

Do you think we should remove these features and allow users to move the document?

**Comment by nothingshiru** [comment]
No. That's a good feature.
