### ISSUE TITLE
Issue: Thumbnail of pattern is blurry in Properties panel/Preset Manager

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3447]
It is clear in Layers panel.
![Screenshot_20210623_181247_com android chrome_edit_376274032427999](https://user-images.githubusercontent.com/79258245/123080873-f7cf6080-d44f-11eb-8e40-0bef32df501d.jpg)

The size of pattern is 3×3 px. Is it about interpolation?

**Comment by photopea** [comment]
fixed, thanks for reporting! :)
