### ISSUE TITLE
Update translation

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3449]
The translation of "File" in 简体中文 has been changed incorrectly by someone. I just corrected it. Please update the translation.
![Screenshot_20210623_231149_com android chrome_edit_393552883207133](https://user-images.githubusercontent.com/79258245/123123307-50ffba00-d479-11eb-8025-e6faf3d3f7a6.jpg)
![Screenshot_20210623_231354](https://user-images.githubusercontent.com/79258245/123123314-52c97d80-d479-11eb-8a80-15d8a5f06b88.jpg)

**Comment by photopea** [comment]
I updated it :)
