### ISSUE TITLE
Cant copy and paste an image on Photopea 

### ISSUE THREAD

**Issue by Trod28** [photopea/photopea#3450]
Wont allow me to copy and paste images

**Comment by photopea** [comment]
I just tried it and it works for me. Could you try these steps?

**Comment by Trod28** [comment]
Tried them all, it still wont work

**Comment by photopea** [comment]
How are you copying and pasting? Do you copy in Photopea and paste in Photopea? Can you try it in the Incognito mode?

**Comment by Trod28** [comment]
I copy the image through google by right clicking and copying, then paste the image by typing ctrl v. and ive tried doing it through incognito

**Comment by Trod28** [comment]
Ive been using that method for a while now

**Comment by photopea** [comment]
When you right-click an image in Google Image Search, do you choose "Copy Image" or "Copy Image Address"?

**Comment by photopea** [comment]
I just tried to do the same, and the image is pasted into Photopea correctly :( Could you record a video of what you do? Maybe there is something you forgot to tell us.

**Comment by Trod28** [comment]
Ok

**Comment by Trod28** [comment]
The file is to big

**Comment by photopea** [comment]
Could you put it on Youtube? Or send it to support@photopea.com ?

**Comment by Trod28** [comment]
OK, i sent the vid

**Comment by photopea** [comment]
I see, that is really strange. So it happens on a Chromebook, when Photopea is in the Installed mode.

Is your Chrome OS updated? If not, could you update it?

If it does not help, could you go to chrome://extensions and "untick" all extensions (temporarily disable them), does it help? You can enable them later.

**Comment by Trod28** [comment]
Tried all of that it still won't work, I also Updated my chromebook

**Comment by photopea** [comment]
Could you open Photopea in a browser instead of the installed mode?

Do you still copy the same image? Could you try to copy other images or from other websites?

**Comment by Trod28** [comment]
Yup tried it still not working

**Comment by photopea** [comment]
I give up then :( I dont know what could be causing it. Can you paste images into Imgur.com ?

**Comment by Trod28** [comment]
It's ok then, thanks for the help👍

**Comment by photopea** [comment]
What about Imgur? Can you go to www.Imgur.com and paste an image with Ctrl+V?

**Comment by Trod28** [comment]
Yeah I can

**Comment by H3LTHCARE** [comment]
its doin the same for me, i can copy and paste from anywhere but google

**Comment by photopea** [comment]
I think your browser is showing you all the old version of Photopea, which had a bug. 

Could you Right-click Photopea, Inspect Element, "Application" at the top, "Service Worker" on the left, and "Stop" the current service worker?

**Comment by Trod28** [comment]
Is it under status?

**Comment by H3LTHCARE** [comment]
once i hit stop then what

**Comment by photopea** [comment]
Try to press Unregister or Update , and reload Photopea. Maybe more than once. This mechanism is still not fully clear to me.

![image](https://user-images.githubusercontent.com/15955558/123149852-032b8780-d462-11eb-828e-5a7b4864c8ba.png)

**Comment by bend4vis** [comment]
@Trod28 are you on chromebook?

**Comment by Trod28** [comment]
Yes, I am

**Comment by bend4vis** [comment]
When you save an image as PNG or JPG and try to view it in your files, does it say 'decoding failed'?

**Comment by Trod28** [comment]
No, it doesn't.

**Comment by bend4vis** [comment]
Has your app sort of crashed and is failing to perform things?

**Comment by Trod28** [comment]
It has once

**Comment by bend4vis** [comment]
Can you still not copy and paste from google?

**Comment by Trod28** [comment]
No, I can't.

**Comment by Yohandz** [comment]
Have you allowed photopea to read clipboard? There is a permission in the site settings called clipboard.

**Comment by Trod28** [comment]
Yes, I did.

**Comment by casperzwaart100** [comment]
I might have a workaround.
The problem seems to be on google/chrome's side. 
All you have to do is open the image in a new tab, and then you can copy-paste it. 
Works for me

**Comment by Trod28** [comment]
Ok I'll try that

**Comment by Trod28** [comment]
IT WORKED. Thank you! @casperzwaart100

**Comment by photopea** [comment]
I still think it can be fixed, if you Unregister your Service Worker. Otherwise, your browser will still show you an old version of Photopea with this bug.

**Comment by Trod28** [comment]
I've tried doing that and it still doesn't work

**Comment by photopea** [comment]
I think it should be fixed now.
