### ISSUE TITLE
Loading bar persistent when editing text 

### ISSUE THREAD

**Issue by MzMiya** [photopea/photopea#3451]
Hi Photopea, 
A very weird loading bar which won't end while I was changing the font of my text in an edit. The image wasn't heavy at all. I am using Photopea in Firefox's 89.0.1 browser (Google Chrome sucks right now) on a Windows 10 PC, i7-7700K, 16gb system.  

![SS PHOTOPEA PERSISTENT LOADING BAR JUNE 23 2021](https://user-images.githubusercontent.com/86370549/123133313-98f0f380-d41d-11eb-9721-c5cb7042a213.png)

**Comment by photopea** [comment]
I just tried it in the latest Firefox and such thing does not happen :( Do you use any browser extensions? Could you disable them?

**Comment by totallytuesday** [comment]
I am having the same issue on Chrome. Now I'm unable to create text at all.

**Comment by photopea** [comment]
Can you try it in Incognito mode, or with all browser extensions disabled?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
