### ISSUE TITLE
Copy and pasted not working

### ISSUE THREAD

**Issue by NartMan192013** [photopea/photopea#3454]
Sooo uhhh when I try to copy and paste, it didn't work. I also try to do it manually but it didn't work. Any solution????

**Comment by photopea** [comment]
Could you close Photopea or close a browser and open it up again? 

Did it ever work before in your case?

**Comment by tcull-14** [comment]
I am having the same issue and I have done everything to try and fix it

**Comment by slowmoed** [comment]
Same problem here. Copying a photo from another site and pasting it into photopea isn't working. Might be because auto-select is toggled when pressing ctrl?

**Comment by photopea** [comment]
When you copy an image on another website, does it also copy any text? I.e. can you paste it into a text editor?

We updated Photopea, such that if there is both text and an image present, only the text is processed.

**Comment by photopea** [comment]
I have to close it because of lack of details.
