### ISSUE TITLE
Change icons app or favicon size

### ISSUE THREAD

**Issue by ryadhiprasetya** [photopea/photopea#3458]
![Screen Shot 2021-06-27 at 09 09 56](https://user-images.githubusercontent.com/47018482/123530753-330bb100-d728-11eb-8c90-78d6fc086a2e.png)
![Screen Shot 2021-06-27 at 09 09 47](https://user-images.githubusercontent.com/47018482/123530755-356e0b00-d728-11eb-9cf0-679e610ff319.png)

Try to pin photopea to mac dock and seeing Icon size feel different with other apps.

**Comment by photopea** [comment]
Hi, are all other apps in your menu Web Apps? Then, I would be able to check what they do to make icons smaller.

Otherwise, it is a bug in your system, which makes icons of webapps bigger.

**Comment by photopea** [comment]
I have to close it because of lack of details. Also, I feel like there is nothing a website can do about the way the OS decides to process the icon.
