### ISSUE TITLE
Loading bar never goes away

### ISSUE THREAD

**Issue by totallytuesday** [photopea/photopea#3459]
I was editing text, picking different fonts and colors for a 2 word phrase. I don't recall which fonts, but I have left the PhotoPea tab open for a full week hoping it will go away and allow me to finish my project. The Loading Bar is still there, and I am no longer able to create new text.
![photopea bug](https://user-images.githubusercontent.com/86551915/123539351-2c604800-d6ee-11eb-8e2a-e05f9dc14f9e.png)

**Comment by photopea** [comment]
Can you close it and try it again? Only bugs which can be replicated can be fixed.

**Comment by photopea** [comment]
I have to close it because of lack of details.
