### ISSUE TITLE
Not able to save anything directly as PSD

### ISSUE THREAD

**Issue by Dostic** [photopea/photopea#3460]
I'm trying to create a new file in the size of 3500x1500 pixels, doing that and trying to save that file as a PSD will always result in an "empty" file with a size of 0 bytes and when I try to open it I always get the error message: "unknown file format: "\u0000\u0000\u0000\u0000". After this happened over and over again I tried to create one in any size I can think of and the bug persists at any file size. This also only seems to happen when I use the button "Save as PSD". Using the button called "Save PSD/PSB..." the file saves properly.

**Comment by photopea** [comment]
Hi, are you using a Chrome browser? Can you update it, please?

**Comment by Dostic** [comment]
I'm using Opera and I had no issues saving it directly as a PSD two days ago. My browser did not update during that time as far as I'm aware.

**Comment by photopea** [comment]
Can you update your Opera? We update Photopea several times a day. Some new features require the latest versions of browsers.

**Comment by Dostic** [comment]
My opera was up to date the entire time, I finished all of my projects though.
If it occours again I will just utilize the way of saving again.

**Comment by AzterixGFX** [comment]
Hi I currently have the same problem and just lost hours of work. I've updated my browser but when I try to re open the PSD on photopea, it just says "unknown file format: "\u0000\u0000\u0000\u0000"
Is there anyway I can get my progress back becauseI can't afford to restart

**Comment by photopea** [comment]
Your file is probably 0 Bytes. That happens when you close the browser too early, while Photopea still says "saving ..." at the top.

If you can make Photopea produce a 0 Byte file without closing it too early, let us know!
