### ISSUE TITLE
Can't save a psd over 10 mb

### ISSUE THREAD

**Issue by m1chaelog** [photopea/photopea#3461]
Whenever I try to save a file larger than 10 mb as a psd, it pauses for a couple seconds then does nothing. Could yall remove the size limit or turn it back to what it was before. Thank you.

**Comment by photopea** [comment]
Hi, we do not have any size limit. I just tried to save a 100 MB PSD and it worked well.

Can you update your web browser? If it does not help, can you disable all your browser extensions?

**Comment by m1chaelog** [comment]
Im using a chromebook and just updated it but the same thing happens

**Comment by photopea** [comment]
So are you able to save PSD files smaller than 10 MB?

**Comment by m1chaelog** [comment]
Yes. I tried saving it online to see if it would change and it said the limit is 10 mb so I merged some layers and it saved. So it probably means there's a size limit.

**Comment by photopea** [comment]
Can you disable all your browser extensions and try it again?

**Comment by nothingshiru** [comment]
> Hi, we do not have any size limit. I just tried to save a 100 MB PSD and it worked well.

I think he is saving files via FIle - Publish online - PSD. 
When I saved files via that option while the files are bigger than 10MB, I did see a pop-up message, said that there was a limit of 10MB.

**Comment by photopea** [comment]
Yes, there is a limit of 10 MB on publishing a PSD file on our server.

**Comment by photopea** [comment]
I have to close it because of lack of details.
