### ISSUE TITLE
it is reall laggy and I can't edit

### ISSUE THREAD

**Issue by silvertail11624** [photopea/photopea#3462]
It is laggy and after I use it for a little bit it makes it so I'm not able to edit it and it doesent save so I have to screenshot it and close the tab and then open another tab put it the screenshot and then be able to draw and even after doing that it happens again so I have to keep in doing this over and over.

**Comment by photopea** [comment]
Hi, are you using a phone or a desktop? How large is your image in pixels? You can check it in Image - Image Size.

Also, is your web browser updated?

**Comment by photopea** [comment]
I have to close it because of lack of details.
