### ISSUE TITLE
I can't save this image as a png as it's just blank

### ISSUE THREAD

**Issue by desbest** [photopea/photopea#3463]
I can't save this image as a png as it's just blank
Adblock, tracking blocking, and extended tracking protection is off.
I'm using Firefox 89 for Windows 10 21H1

![projects_dripbite-m](https://user-images.githubusercontent.com/1139316/123559014-7d754800-d791-11eb-9257-760d73b10fe3.png)

**Comment by photopea** [comment]
Hi, do you mean opening your PNG in Photopea and saving it back as a PNG? I tired it and it works, a correct PNG is saved to my computer.

**Comment by desbest** [comment]
Yes I uploaded the file to Photopea from my computer. Here's what I get when I save the file as a png from Photopea.

The resulting file is 1KB.

![projects_dripbite-m](https://user-images.githubusercontent.com/1139316/123559983-528df280-d797-11eb-9da0-0f9969812ea1.png)

![pdam frame 1](https://user-images.githubusercontent.com/1139316/123559980-4b66e480-d797-11eb-999a-6f28d1f516e6.png)

-----

Then if I use [Faststone Capture](http://faststone.org) to save it again as a png I get this.

![projects_dripbite-m again](https://user-images.githubusercontent.com/1139316/123559985-5457b600-d797-11eb-9d23-ccb0f708ddd9.png)

![pdam frame 2](https://user-images.githubusercontent.com/1139316/123559982-4efa6b80-d797-11eb-9008-997efdf3bf03.png)

**Comment by photopea** [comment]
It should definitely be bigger than 1 kB. It should be 36 kB.

Can you disable all your browser extensions, if you have any, and try it again?

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by desbest** [comment]
I uninstalled [Ublock Origin](https://addons.mozilla.org/en-GB/firefox/addon/ublock-origin/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) and [Canvas Blocker](https://addons.mozilla.org/en-GB/firefox/addon/canvasblocker/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) from Firefox and now it works. I don't feel the need to investigate what feature was blocking it as I don't need those extensions any more.

**Comment by photopea** [comment]
I think you should report it to authors of a problematic extension, so that they fix it. I still wonder so many people allow random extensions to rewrite files right under their hands, without even knowing about it.
