### ISSUE TITLE
On macOS, zooming in and out with the trackpad causes an error with "preventDefault"

### ISSUE THREAD

**Issue by dentistformyeye** [photopea/photopea#3464]
On macOS, zooming in and out with the trackpad makes a red error appear in the browser console.
![image](https://user-images.githubusercontent.com/51429646/123573294-aac6f380-d79b-11eb-9ca8-6e809dbd119a.png)
`[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.` (The URL seems to be outdated.)

The error happens regardless of whether a project is open in Photopea. It doesn't seem to interfere with anything, but since it keeps getting triggered, it might eat up memory.

**Comment by photopea** [comment]
fixed, thanks for reporting :)
