### ISSUE TITLE
Photopea wont paste images from google unless i rightclick them and press "open in new tab" before copying

### ISSUE THREAD

**Issue by jskswaps** [photopea/photopea#3465]
Photopea wont paste images from google unless i rightclick them and press "open in new tab" before copying, how can i fix this so that i can just copy them from google images?

**Comment by photopea** [comment]
Could you update a service worker in your Photopea? Try to google how to do it.

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by jskswaps** [comment]
hi! sorry about the late response. i updated service worker inside of
inspect elements, and still no change

**Comment by jskswaps** [comment]
and if this helps understand it more; when i drag and drop an image from
google into photopea it shows "unknown file format <htm"

**Comment by photopea** [comment]
Can you disable all your browser extensions, update your web browser, and try it again?

**Comment by jskswaps** [comment]
just tried, and still no change

**Comment by photopea** [comment]
Can you try it in Incognito mode?

**Comment by jskswaps** [comment]
nope, still doesnt work in incognito mode.
