### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by AndrewCristian** [photopea/photopea#3466]
Hello,
Are you working at the site at this moment? Photopea isn't working properly.

**Comment by photopea** [comment]
What exactly is not working?

**Comment by AndrewCristian** [comment]
It's lag, I cant copy or duplicat into another layer...

**Comment by photopea** [comment]
What should I do to see the bug happen? I just tried some copying and it seems to work fine.

**Comment by photopea** [comment]
If you are copy-pasting 15 million pixels or more, there can be a lag of 2 - 5 seconds, because in Chrome, we use a system clipboard, and sadly, Chrome always applies a PNG compression on an image. It works like this for the past two years.

**Comment by AndrewCristian** [comment]
So, I want to put a logo on an icon and I work on two different projects in Photopea ( one for the logo and one for the icon) and when I want to copy or duplicate the logo on the icon, isn't working..

**Comment by photopea** [comment]
How exactly do you copy or duplicate the logo? Do you use edit - copy, or Layer - Duplicate Into ?

**Comment by photopea** [comment]
Are you sure that what you are doing ever worked in Photopea before?

**Comment by AndrewCristian** [comment]
Duplicate into

**Comment by AndrewCristian** [comment]
> Are you sure that what you are doing ever worked in Photopea before?

Yes!

**Comment by photopea** [comment]
I just tried to duplicate layers from one document to another and it works.

Could you send me your two documents to support@photopea.com and describe, which layers should I duplicate?

BTW. is it not working or is it just slow?

**Comment by AndrewCristian** [comment]
Now its working, I made on my phone (IOS) and I have finished.

**Comment by AndrewCristian** [comment]
> I just tried to duplicate layers from one document to another and it works.
> 
> 
> 
> Could you send me your two documents to support@photopea.com and describe, which layers should I duplicate?
> 
> 
> 
> BTW. is it not working or is it just slow?

I'll try again on my macbook and if isn't working, I will send you! 
Thank you!
