### ISSUE TITLE
Translation Issue (German Loca)

### ISSUE THREAD

**Issue by Sil3ntz90** [photopea/photopea#3472]
It should be "Auf Hintergrundebene reduzieren". (Layer > Flatten Image) 
NOT "Hitlergrundebene"~ Hitler was a dictator and has nothing to do with the word "Hintergrund".
![image](https://user-images.githubusercontent.com/63884065/124014420-ca505d00-d9e3-11eb-8cd4-4b354753dd48.png)

**Comment by photopea** [comment]
I am very sorry. Our translations are open for anyone to modify, and such vandalisms appear from time to time. I fixed it.

**Comment by dabo248** [comment]
![photopea-1](https://user-images.githubusercontent.com/11370593/124018365-0e456100-d9e8-11eb-8315-c4887d2f0308.png)
![photopea-2](https://user-images.githubusercontent.com/11370593/124018369-0f768e00-d9e8-11eb-82dc-b5c2305bb89c.png)

Same vandalisms here ☝️

**Comment by photopea** [comment]
fixed :)

**Comment by Sil3ntz90** [comment]
> fixed :)

The OK Button says "LOOOOL" it could be "OK" or "Bestätigen". In Adobes Photoshop it's labled with "OK". =)
