### ISSUE TITLE
Bug: Copying doesn't factor in clipping masks

### ISSUE THREAD

**Issue by GavHern** [photopea/photopea#3473]
When I use <kbd>Ctrl</kbd> <kbd>Shift</kbd> <kbd>C</kbd> to copy my selection to the clipboard, any layers with a clipping mask will not be clipped. I've also noticed that any effects on those layers arent applied to the copied image.

**Comment by photopea** [comment]
Ctrl+Shift+C will copy a selected part of a "merged image" - what you see in front of you (so it does not matter what layer is selected when you copy it). I just tried it and it seems to work well, even when there are clipping masks.

Can you describe steps, how can I reproduce the problem?

**Comment by joshuaff** [comment]
hii

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by joshuaff** [comment]
oh
________________________________
