### ISSUE TITLE
Cannot Export

### ISSUE THREAD

**Issue by Hard2Please** [photopea/photopea#3474]
I can no longer 'export as'.

I used to be able to give an export a filename and chose the folder to save it in. Now it just downloads. This creates more work. Please revert the 'improvement' back to the save dialogue box.

**Comment by photopea** [comment]
Hi, the saving mechanism is fully under a control of your browser. There is nothing a website can do about it.

Are you using Chrome? Then go to settings and enable "Ask where to save each file before downloading."

**Comment by Hard2Please** [comment]
I am using the app on my computer, not in a browser. It used to open a save dialogue box. Now it doesn't.

**Comment by photopea** [comment]
Did you press More - "Install Photopea" in Photopea.com ? It still runs in a browser and behaves according to your browser settings.

**Comment by Hard2Please** [comment]
Ok, Apparently it is in Microsoft edge. I have tried to open in chrome but the Install Photopea is greyed out.

**Comment by Hard2Please** [comment]
I've changed the download setting in Edge now I can click to open a save dialogue box, because microsoft

Many thanks

**Comment by photopea** [comment]
I think Chrome and Edge work almost identically now, as they are based on Chromium engine.

**Comment by Hard2Please** [comment]
How can I change my app to chrome instead of edge as chrome greys out the 'install photopea' option even though I have a subscription and am logged into photopea
