### ISSUE TITLE
Cannot Install Photopea

### ISSUE THREAD

**Issue by Hard2Please** [photopea/photopea#3475]
![image](https://user-images.githubusercontent.com/86781842/124126986-21e9d980-da73-11eb-8aa4-d09124201663.png)

How do I install the app please

**Comment by photopea** [comment]
I think it works only in Chrome and Edge now. 

Look into about://apps , maybe it is already installed.

**Comment by Hard2Please** [comment]
You are a star. Already loaded. Now it's in chrome it's working as it used to.

The moral of the story is...don't use edge lol

**Comment by photopea** [comment]
ok great :)
