### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by maoweifan** [photopea/photopea#3476]
Hello, I need to use JavaScript for complex image processing due to some problems at work. I have learned about such an excellent project as Photopea. I really hope to get some help. At present, I am quite confused about the technology selection. I hope the Photopea team can Solve my doubts and give me some suggestions on the selection of libraries for image manipulation and some suggestions and precautions for canvas manipulation. I'm very sorry to trouble you, and I look forward to your reply.

**Comment by maoweifan** [comment]
It would be better if you can reply to me by email！`1689166982@qq.com`，thanks

**Comment by photopea** [comment]
Hi, I gave a talk about creating Photopea: https://www.youtube.com/watch?v=IZmaeC_Ma5A

I am not very good in Javascript or "canvas manipulation". I would be able to make Photopea in any programming language, and the code would be almost identical to what it is now (but with a different syntax).

**Comment by maoweifan** [comment]
Hello, I would like to ask, do you use javascript to process some pictures on the browser side or on the server side?

**Comment by maoweifan** [comment]
I want to know how to read, operate, and write psd files, can you tell me?

**Comment by maoweifan** [comment]
What I need to do is to parse the psd file, mainly the layer information, and then replace some of the layer information with pictures and text, and then export it to a PNG file. I tried `psd.js`, but it can't satisfy me, so I want to ask you how to parse PSD, nothing more. thank you very much

**Comment by photopea** [comment]
I made my own parser according to https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/ . I do not share my parser with anyone.

**Comment by maoweifan** [comment]
ok , I know, thanks
