### ISSUE TITLE
Feature Request: Delete mask by press Backspace or Delete key

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3477]
Pressing Backspace/Delete to delete the raster/vector mask when the mask is selected.

**Comment by nothingshiru** [comment]
I requested this feature after I had found that I could do this in Photoshop. Maybe I missed something?

**Comment by MichalSZZ** [comment]
> 
> 
> I requested this feature after I had found that I could do this in Photoshop. Maybe I missed something? I'll test it again in Photoshop later.

Yes. In Photoshop, when you are on raster mask (that rectangle is selected) and you hit the delete or backspace. It delete only the raster mask - not the whole layer with raster mask.

**Comment by photopea** [comment]
Ok, I implemented it.
