### ISSUE TITLE
Feature Request: Shortcuts for selecting channels

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3478]
Ctrl + \ for selecting the raster mask on current layer.
Ctrl + 2, 3, ..., 9 for selecting RGB channel, Red channel, ..., Alpha 4 channel.

Ctrl + Alt+ \ , 2, ..., 9 for loading the mask/channel as selection.

**Comment by photopea** [comment]
I implemented it for masks. I think it can be confusing for channels, many people could press it accidentally and be surprised, why the image became grayscale.

**Comment by nothingshiru** [comment]
You can implement Ctrl + 2 as well. It is selecting RGB channel so the image would not become grayscale. And we will be able to switching between image and mask.

**Comment by nothingshiru** [comment]
> You can implement Ctrl + 2 as well. It would select RGB channel, so the image would not become grayscale. With this shortcut, we will be able to switch between image and mask quickly.

What do think about this?

**Comment by photopea** [comment]
Since selecting channels in Photopea does not work the same as in Photoshop, I am afraid to modify this part of Photopea.
