### ISSUE TITLE
Feature Request: Lock/Unlock(All) current layer by pressing / key.

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3479]

**Comment by photopea** [comment]
I implemented it.

**Comment by nothingshiru** [comment]
it doesn't work.

**Comment by photopea** [comment]
It works only for the slash key on the numapd (that is the only key that worked for me in Adobe Photoshop).

**Comment by nothingshiru** [comment]
The one on the left side of the right Shift works for me in Photoshop.

**Comment by photopea** [comment]
I just added it to that key, too.

**Comment by nothingshiru** [comment]
Thanks

**Comment by nothingshiru** [comment]
It doesn't work as expected. 

Even if there are others locked, it can now only control "all". The expected operating mechanism is unlock the layer completely first when there are other locks are locked.

**Comment by photopea** [comment]
In Photoshop, the "/" button enables or disables the last locks. When all locks are disabled, it still remembers the last enabled lock, and sets them back. I think it would be too complicated to do.

**Comment by nothingshiru** [comment]
What about make "/" not just lock/unlock "All" but ALL four locks. 
![screenshot_20210719_213255](https://user-images.githubusercontent.com/79258245/126168594-323874ff-6a96-42cf-bb2f-6c7cc3f5420a.png)

**Comment by nothingshiru** [comment]
That's good.

**Comment by photopea** [comment]
Ok, I made it work that way.
