### ISSUE TITLE
Issue: Problems about the brush in Refine Edge/Magic Cut

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3480]
1. "Hardness" option doesn't work.
2. The brush is stll a round brush when selecting a special brush which is not a round brush.
3. When selecting a special brush, changing Size doesn't work.
4. Painting with the special brushes looks like creating selection by using Polygonal Lasso Select while Alt is been holding.
5. The brush moves back and forth between the first finger and the second finger when using two fingers to scroll over the image.
6. When just opened Photopea, Can't paint anything with special brushes before paint something with round brushes.
7. After painting with special brushes, close and reopen Refine Edge/Magic Cut and paint with special brushes again. Somethings are wrong.

**Comment by nothingshiru** [comment]
Besides, I think that only the Size option is necessary in Magic Cut.

**Comment by photopea** [comment]
In Magic Cut and Refine Edge, what you are painting can have only three different colors (e.g. red, green, transparent). So there is no point of having "hardness".

There was a bug there, and I fixed it. Custom brushes should work well now.
