### ISSUE TITLE
Issue: The highest values of zoom levels are not same

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3482]
Zoom in by Zoom tool, it's 3200%, by two fingers it's 6400%, by the slider in Navigator panel it's 4000%.

**Comment by photopea** [comment]
I think it is not an issue, people rarely zoom to these levels anyway.

**Comment by nothingshiru** [comment]
6400% is the level that we can paint or select a special pixel with finger. .... I expect you to make them all 6400%. 😊

**Comment by photopea** [comment]
The Zoom tool was already at 6400, so I just increased it in the Navigator to 6400.

**Comment by nothingshiru** [comment]
The Zoom tool is still 6400% for me.

https://user-images.githubusercontent.com/79258245/124374669-ec8df780-dccf-11eb-8e76-e711c5eacb0f.mp4

**Comment by photopea** [comment]
I am sorry, it should be fixed now.
