### ISSUE TITLE
Unable to post from clipboard when copying an image from a website. this was possible less than a month ago.

### ISSUE THREAD

**Issue by benleonheart** [photopea/photopea#3483]
As said; photopea won't read the clipboard data correctly, as it will not allow me to paste an image I've copied from a webpage. But, if I take a screenshot, then it **does** allow me to; just not when I do it from a website.

This used to work perfectly a couple of weeks ago.

**Comment by photopea** [comment]
Hi, could you describe steps how can I reproduce the problem? No matter what I do, pasting a copied image always works for me :(

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by benleonheart** [comment]
> I have to close it because of lack of details :(

Hey, I just wanted to thank you, I don't know what happened, but it works flawlessly again!! **Thanks so much!**
