### ISSUE TITLE
Automatic translation

### ISSUE THREAD

**Issue by JustHeadcrab** [photopea/photopea#3484]
I have a question, how to disabe automatic translation on photopea? I can't find out in photopea anymore, because I was using this site in english for months, and now it is translated to other language. Any ideas? Thanks.

**Comment by JustHeadcrab** [comment]
ok nevermind, I fixed it

**Comment by photopea** [comment]
Photopea has localizations under More - Language - ....  They were written by humans and should be correct.

If your browser performs additional translation, you should disable it in your browser.
