### ISSUE TITLE
Ubuntu Appimage

### ISSUE THREAD

**Issue by GoroDaimon** [photopea/photopea#3486]
Please create universal appimage for Linux please. Photopea online need web browser and internet.

**Comment by photopea** [comment]
Hi, I don't even have any Linux to test such appimage thing :( And as we update Photopea 10x a day, I doubt users would update their offline version so often.

I am sure there exist web browsers for Linux. Photopea runs offline, if it was opened by your computer at least once in the last year (just disconnect from the internet, open www.Photopea.com in a browser and it will be there).
