### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by YardaneCvTW** [photopea/photopea#3488]
I just started using this and I'm having issues with the text popping up. I was creating two seperate texts, the 2nd text wasn't popping up. even when I restart it begins to happens again.

**Comment by photopea** [comment]
Hi, what does it mean "text popping up"? What should I do to see the problem in Photopea?

I tried to create two text layers, and it seems to work well.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
