### ISSUE TITLE
New text parameters

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#3489]
I just tried new text parameters and with font "Lilly" you can see several issues in this image.
![image](https://user-images.githubusercontent.com/6370548/124352545-11676980-dc01-11eb-927d-a079d8a9a234.png)
1. Blue background in the first line does not go to the top of letters "W" and "l" (same in the last line with letter "p")
2. There is small gap in between letters "e" and "l"
3. There is small gap in between lines of texts
4. Stroke has "strange unwanted spikes" in some places (in the bottom of "W" or in right part of letter "e")
5. Background of letter "e" goes over letter "W"

**Comment by photopea** [comment]
I fixed it :)

**Comment by hxim** [comment]
Hi it seems 3 4 5 are fixed but I still see gap in between "e" and "l" (2) and background is not covering letter "W" in top left and "p" in the bottom (1). See this screenshot:
![image](https://user-images.githubusercontent.com/6370548/124394205-aa2fdf00-dcfe-11eb-9017-f4635a8adae0.png)

**Comment by photopea** [comment]
I fixed the gap. Also, the rectangle of each character is inflated by the thickness of the stroke line.

**Comment by hxim** [comment]
Hi I noticed when I change "Scale Horizontally" from 100% to other value it scales background wrongly.
On 50% background is half of needed width (25% of original width) and on 200% it is double of needed width (400% of original width).
See screenshots:
![image](https://user-images.githubusercontent.com/6370548/124731038-28b09a80-df12-11eb-8336-c759b6e3eb95.png)
![image](https://user-images.githubusercontent.com/6370548/124730957-16cef780-df12-11eb-9069-e03d12766bcc.png)
