### ISSUE TITLE
Font request

### ISSUE THREAD

**Issue by TriAce** [photopea/photopea#349]
Is there any way to add Proxima Nova? https://github.com/elliakou/proxima-nova-web-fonts

Thanks if you can,
Tri

**Comment by photopea** [comment]
Hi, it seems like Proxima Nova is not a free font, you are supposed to buy it (even though somebody put the files on GitHub).
http://www.fontbros.com/families/proxima-nova
https://www.fonts.com/font/mark-simonson-studio/proxima-nova

If you own this font, you can load the TTF file into Photopea using File - Open, it will appear at the end of the list of fonts.

**Comment by TriAce** [comment]
Oh, thanks! I'll buy it this month then.
