### ISSUE TITLE
Change the background color of the menu of tools

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3490]
![Screenshot_20210703_233819](https://user-images.githubusercontent.com/79258245/124359584-3935ec00-dc58-11eb-9d71-23c63695c90d.jpg)

I am often confused by the icons of these two tools because of different color. I think it could be better to make the color of menu same as the toolbar, and the color of icons in menu same as the icons on toolbar.

**Comment by photopea** [comment]
Ok, I made this menu dark, too. I think @avagp will appreciate it, too :)

**Comment by avagp** [comment]
🤩
