### ISSUE TITLE
Move panel window a little bit

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3491]
Make the top of panel window align with the top of side bar, and completely attach on the side bar. Would it look better?
![Screenshot_20210703_234843_com android chrome](https://user-images.githubusercontent.com/79258245/124360056-3b994580-dc5a-11eb-9a9e-77fba0a3c1df.png)

**Comment by photopea** [comment]
fixed, thanks for suggesting it!

**Comment by nothingshiru** [comment]
The top of panel window doesn't align with the top of side bar.
![Screenshot_20210704_214542_com android chrome](https://user-images.githubusercontent.com/79258245/124387602-d4d76300-dd11-11eb-8a3b-db914b9a812c.jpg)

**Comment by nothingshiru** [comment]
> The top of panel window is still not aligned with the top of side bar.
> ![Screenshot_20210704_214542_com android chrome](https://user-images.githubusercontent.com/79258245/124387602-d4d76300-dd11-11eb-8a3b-db914b9a812c.jpg)

@photopea You might forget to move it up.

**Comment by photopea** [comment]
I like it as it is, I don't think it should be moved up.
