### ISSUE TITLE
Issue: Problem with brush when choose Direction

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3492]
![新建项目 (2)](https://user-images.githubusercontent.com/79258245/124360819-67b6c580-dc5e-11eb-9816-6913f02f83fe.png)
They look like this.

To reproduce

1. Choose a brush that is not a round brush (For example the twelve one in brush menu).
2. Choose Direction in Brush panel - Tip Dynamics - Control.
3. Paint something.

**Comment by photopea** [comment]
What is the problem? What is wrong?

**Comment by nothingshiru** [comment]
There should not be these stuffs.
![IMG_20210704_004356](https://user-images.githubusercontent.com/79258245/124361300-f9bfcd80-dc60-11eb-9cd1-c5f02c609cc8.png)

https://user-images.githubusercontent.com/79258245/124361313-07755300-dc61-11eb-948a-98eb435b4a84.mp4

**Comment by photopea** [comment]
The direction of the movement is not known when you click. I think it works like this in other programs, too.

**Comment by dentistformyeye** [comment]
If I recall correctly, Krita keeps track of the brush direction even when the mouse button isn't being pressed

**Comment by photopea** [comment]
I fixed it. If the angle is controlled by the direction, the first click does not paint anything.
