### ISSUE TITLE
[Galaxy Tab S7+] Touch and Pen Issue

### ISSUE THREAD

**Issue by nm12b3** [photopea/photopea#3493]
First of thanks for making a great tool! I found some bugs while I'm using Pen and Touch together.

(1) If I try to use a pen, while the finger is on the screen (without releasing the finger), an error occurs. The signal of pen and finger switches!

(2) Also, If the TWO fingers are on the screen (without releasing the finger), and try to use a pen, it will the canvas is fixed and both touch and pen input stop working.

I guess I'm not very good at describing, but I hope this problem is fixed.

Thank you!

**Comment by nothingshiru** [comment]
> (2) Also, If the TWO fingers are on the screen (without releasing the finger), and try to use a pen, it will the canvas is fixed and both touch and pen input stop working.

When 3 or more finger are touching on canvas, canvas would be lock in case of touch by mistake. It sounds like the stylus is now considered a finger touch in this case.

**Comment by photopea** [comment]
Try to touch the screen with "one thing" only (finger or stylus, it is not important). Also, you can press the virtual keyboard at the bottom left corner, and enable "No Touch" - that will ignore all touches from fingers. Does it solve your problem?

**Comment by nm12b3** [comment]
Thanks for reply! Once it is not working, I need to restart the project. Currently, using with No touch mode as you recommended, but I really miss finger zoom in-out, and simple touch short-cuts.

**Comment by photopea** [comment]
The main goal of "No Touch" is to prevent fingers from painting. So all you need is to be albe to zoom with fingers while NoTouch is enabled?

**Comment by nm12b3** [comment]
> The main goal of "No Touch" is to prevent fingers from painting. So all you need is to be albe to zoom with fingers while NoTouch is enabled?

If I would add my humble opinion, I think the touch features from another drawing tool could be a good option.
I normally just turn off the single-finger touch, (but it seems like it still works with menus not canvas).

Two fingers gesture: Zoom in/out 
Single finger gesture: Only works with menus

![2](https://user-images.githubusercontent.com/30891487/124391390-0a4e6300-dcb6-11eb-9feb-72f8ced64f05.png)

**Comment by photopea** [comment]
Sadly, I do not have a device with a stylus, to try it out and figure out, what the user experience should look like.

So when you have these settings, and only a stylus is allowed to paint, and you touch the screen with your fingers or with a palm of your right hand accidentally while painting, doesn't it bother you, that it moves / zooms the canvas? Or are touch events ignored when a stylus touches the screen?

**Comment by nm12b3** [comment]
> Sadly, I do not have a device with a stylus, to try it out and figure out, what the user experience should look like.
> 
> So when you have these settings, and only a stylus is allowed to paint, and you touch the screen with your fingers or with a palm of your right hand accidentally while painting, doesn't it bother you, that it moves / zooms the canvas? Or are touch events ignored when a stylus touches the screen?

Here is my test result!

1) When the pen is already used, the touch signal is completely blocked. While the pen is used, I can't use any menu or moves/zoom with touch.

2) Also, I found an interesting thing. Even though the finger was already used for touch events (such as moves/zooms or selecting menu), the touch events completely stop if the pen signal interrupts. I guess ClipStudio prioritizes the pen signal for palm rejection.

Thank you!

**Comment by photopea** [comment]
It all sounds too complicated, and also, Google Chrome has too many bugs, related to using several pointing devices.

Lets discuss it again in a year, when browsers are more consistent.
