### ISSUE TITLE
Issue: Bug with finger touch and mouse click

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3494]
**In Chrome for Android**

Here are 2 ways to reproduce.

First way
Left-click or right-click anywhere on the page while a finger is touching on canvas.

Second way
1. Left-click or right-click anywhere on the page and hold.
2. Touching on canvas with a finger and hold.
3. Release Left-click or right-click.
4. Release finger.

It would look like that there is a invisible finger touching on canvas. And the panels no longer works properly. 
Once the bug happened, we have to reopen Photopea.(Refresh page or close Chrome and reopen it.)

**Comment by nothingshiru** [comment]
**In Firefox for Android**

To reproduce

Left-click or right-click anywhere on the page while two fingers are touching on canvas.

> It would look like that there is a invisible finger touching on canvas. And the panels no longer works properly.

Same bug happened. But in Firefox, we can fix it by tap on canvas with two fingers instead of reopening Photopea.

**Comment by nothingshiru** [comment]
There's another bug in Firefox.

To reproduce

1. Touching on canvas with a finger.
2. Left-click or right-click anywhere on the page and hold.
3. Release finger.
4. Release left-click or right-click.

The bug can be reproduced by taking the same steps in a different order.(2 > 1 > 4 > 3)

Photopea thinks the left mouse button is being pressed. Tapping with finger or clicking with mouse anywhere on the page would fix it.

**Comment by photopea** [comment]
I think it is a bug in Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1226383 . 

Do you know any HTML or Javascript? Could you maybe create a simplified cases of the problem, and report it to browser developers?

**Comment by nothingshiru** [comment]
> Do you know any HTML or Javascript? Could you maybe create a simplified cases of the problem, and report it to browser developers?

Sorry. I don't know anything about those things.

**Comment by nothingshiru** [comment]
By the way, I think this bug is quite similar to "Enabling NoTouch while a finger is touching on canvas" and "Used Quick Selection" that I reported before.
