### ISSUE TITLE
Keyboard shortcuts not working after using checkbox

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#3497]
Immediately after I check or uncheck any checkbox no keyboard shortcut is working. Also happens if I select different value in any dropdown/combobox. When I click somewhere else it starts to work again.
For example after I click here:
![image](https://user-images.githubusercontent.com/6370548/124399270-93978100-dd1a-11eb-80b2-36c2f9ec72de.png)
I press CTRL+A to select all and nothing happens.

Or I select different value here
![image](https://user-images.githubusercontent.com/6370548/124399315-d78a8600-dd1a-11eb-85e9-ba67099e9a80.png)
and after that CTRL+A or any other keybord shortcut is not working

**Comment by photopea** [comment]
I completely rebuilt our keyboard handling mechanism. I hope I did not break anything else.
