### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by YusufSuleman** [photopea/photopea#3498]
Don't leave an excuse for not providing it.

**Comment by photopea** [comment]
Hi, I do not understand, how can we help you?

**Comment by YusufSuleman** [comment]
Release the source code of Photopea.

**Comment by photopea** [comment]
Sorry, Photopea is not open source :(

**Comment by quantuminformation** [comment]
Let give our life's work away for free @YusufSuleman, sorry this isn't communism.

**Comment by HamidRezaAshkiyan** [comment]
I think he means by opening the source you get so much more to contribute, you grow faster and of course no one steal your code there are so many open source premium software out there like Bitwarden.
I believe open source is the next major thing and I open my source even if they are premium software products.

But at the end it is your choice, Thanks for such a good product.

> Let give our life's work away for free @YusufSuleman, sorry this isn't communism.

**Comment by quantuminformation** [comment]
- and of course no one steal your code there are so many open source premium software out there like Bitwarden
lol
