### ISSUE TITLE
Ad warning popping up. 

### ISSUE THREAD

**Issue by cyclops365** [photopea/photopea#3499]
I have an adblocker but I don't run it on Photopea. But since today, the ad warning comes up saying that I'm using an Adblocker and to turn it off.

**Comment by photopea** [comment]
Hi, is the ad on the right side displayed properly?

**Comment by camdrpea** [comment]
having the same issue i dont see any ads but ive turned off all my adblockers and it pops up every minute its really annoying...

**Comment by photopea** [comment]
If you do not see ads, your device is brobably blocking them. Could you turn it off?

If you do not know what is blocking ads, could you turn off all your browser extensions and open Photopea.com again?

**Comment by cyclops365** [comment]
> Hi, is the ad on the right side displayed properly?

No there are no ads.




> If you do not see ads, your device is brobably blocking them. Could you turn it off?
> 
> If you do not know what is blocking ads, could you turn off all your browser extensions and open Photopea.com again?

Will give it a go next time I'm on. Thanks.

**Comment by CryoPlenilune** [comment]
> If you do not know what is blocking ads, could you turn off all your browser extensions and open Photopea.com again?

Did this and the ads still didn't appear properly, however it works just fine in incognito mode. Cleared site data for photopea and ads pop up again just fine!

@cyclops365 If you're using chrome, go into the site settings and clear the data, or just clear your cookies! Should work just fine.

**Comment by Oubaido** [comment]
I swear that adblock is not available but is says to me  there is a adblock please stop this problem it is very annoying and i never work with this

**Comment by CryoPlenilune** [comment]
> I swear that adblock is not available but is says to me there is a adblock please stop this problem it is very annoying and i never work with this

Try clearing your cookies and cache! That's what worked for me and everything is back to normal :)

**Comment by photopea** [comment]
Guys, I wrote this tutorial, it should help: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/
