### ISSUE TITLE
Clone Button not working

### ISSUE THREAD

**Issue by johnmhaney** [photopea/photopea#35]
The clone button seems not to be working for me. Help please

**Comment by photopea** [comment]
Hi, do you mean Clone tool? You must choose the source first using Alt, and then you can copy this source at the new destination by drawing. 

https://www.youtube.com/watch?v=6nQRe6gbQ2Y

**Comment by photopea** [comment]
I have to close it because of the lack of additional information :( feel free to reopen it at any time.

**Comment by avagp** [comment]
I does not work.
I cannot enable the ankle to start cloning.

I hold Alt and click: nothing
I press Ctrl and click: nothing
I hold Ctrl and click: nothing
I press Alt gr and click: nothing
I hold Alt gr and click: nothing
I press Alt gr and click: nothing
an so on...
Nor i get the helping text at the top anymore.
I am on chrome

I can record a video if you want.

**Comment by avagp** [comment]
I am working on a chromebook  btw :P

**Comment by photopea** [comment]
It is probably related to this: https://bugs.chromium.org/p/chromium/issues/detail?id=248762  Users on phones and tablets would have the same problem, because of no keyboard.

Do you propose any solution, that does not use keyboard?

**Comment by avagp** [comment]
At least for chromebooks... when i press Alt the option for the selected tool indeed changes. But if i click it gives me the right-click issue.

Maybe the Alt click should not be a key combo, but instead Alt button should be a function toggle.

For example on Zoom tool, if i press Alt, the zoom tool switches to zoom-out and stays that way. If i press Alt again it should change to zoom-in. That way i can have the Alt comfort :)
