### ISSUE TITLE
Layer Style - multiple files

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#350]
I open 2 files
In first file I open Layer Style dialog
I check "Drop Shadow"
I go to second file
I click OK
->
Drop Shadow is applied on Layer in first file but item in History is added in second file
(and because of it you cannot undo your action in first file)

**Comment by photopea** [comment]
It was fixed. The new behavior is the follwoing: If you try to switch between projects

- when a tool is "locking the UI" (Type tool, free transform): the tool is escaped and projects are switched
- when a window is "locking the UI" (Layer Style, Filter, Adjustment): projects are not switched, there is a message to close the window
