### ISSUE TITLE
Photopea is telling me to turn off my ad blocker even though I don't have it on

### ISSUE THREAD

**Issue by FartMaster57** [photopea/photopea#3500]
It keeps giving me a pop up that says to disable my ad blocker, but I already have my ad blocker off for photopea, I always have.
![Screenshot 2021-07-05 171206](https://user-images.githubusercontent.com/58342249/124518391-40720c80-ddb4-11eb-8a50-df8ae61793d3.png)
![Screenshot 2021-07-05 171227](https://user-images.githubusercontent.com/58342249/124518394-423bd000-ddb4-11eb-846d-537acac96a08.png)

**Comment by FartMaster57** [comment]
Nevermind I think I actually found out why

**Comment by FartMaster57** [comment]
So, I thought it was maybe my VPN and not just my adblocker, but after whitelisting Photopea on my vpn and re-whitelisting Photopea on my adblocker it still does not show me ads on the website and tells me to disable my adblocker. Ads will show up on incognito mode, but there shouldn't be any extensions causing them to be blocked in a normal Chrome window since the site is whitelisted.

**Comment by photopea** [comment]
My guess is, that you probably have no idea, what your extensions actually do.

Can you disable them all and try Photopea again? Then, you can enable them back, one by one, until you find the one which removes ads.

**Comment by FartMaster57** [comment]
I completely disabled the adblocker and vpn extensions and now the ads show up fine, I'm gonna re-enable them one at a time to see which one is causing it

**Comment by FartMaster57** [comment]
So, It seems to be the VPN. But even if I disable everything on the vpn that is supposed to block things, it still blocks the ads

**Comment by sprodays** [comment]
Having this same issue and even tried opening Photopea in incognito mode on Chrome and the issue persists!

**Comment by FartMaster57** [comment]
After disabling the ad blocker on the VPN, the pop-up telling me to disable my ad blocker is gone, but there's still no ads showing up

**Comment by photopea** [comment]
@FartMaster57 I guess it is a bug in that VPN extension. You should report it to the person who created your extension.

**Comment by FartMaster57** [comment]
@photopea Okay I'll do that

**Comment by photopea** [comment]
We have an article about it, maybe it could help others: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by FartMaster57** [comment]
> Having this same issue and even tried opening Photopea in incognito mode on Chrome and the issue persists!

Try reinstalling chrome altogether
