### ISSUE TITLE
"Your device seems to be blocking ads" popup but all adblockers are disabled

### ISSUE THREAD

**Issue by sl9dge** [photopea/photopea#3502]
Everything is in the title, ads just won't show up and I have the pop up asking me to disable adblockers every few seconds, which is anoying to work (freezes whatever I'm doing) especially considering my adblockers are disabled. I'm on Chrome.

**Comment by CryoPlenilune** [comment]
It was a cookies/cache problem for me, so try clearing those!

**Comment by photopea** [comment]
Hi, what exactly is an adblocker? Any browser extension could try to remove ads from websites. Have you tried to disable all your extensions?

Try these steps: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by TuxPaper** [comment]
What I don't understand is, other web sites show ads just fine when I turn off Ad Block for them.  But Photopea doesn't.  It's clear to me, Photopea is doing something completely different than the majority of web sites that use ads.  But yeah, put it on us users fix it.. that's great PR for sure.
