### ISSUE TITLE
Is it possible to have the vertical align parameter in a text box?

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3504]
It will be a nice feature for templates with text boxes for paragraph.

In Illustrator it can be set for example to the bottom of the text box (like in TD in HTML)

![obraz](https://user-images.githubusercontent.com/38118273/124582894-c04eb400-de52-11eb-83a5-26cff0dc9d68.png)

I know that can be impossible but you do such of magic so oft (like text highlighting like in Illustrator) :)

**Comment by photopea** [comment]
I don't think such parameters can be stored in PSD files (which is our main format). Is this possible in Adobe Photoshop or any other PSD editor?

**Comment by MichalSZZ** [comment]
Sadly... I don't know any raster editor who can do such thing.

It is possible in Illustartor, InDesign, Figma, Sketch etc.
Ok thanks for your answear

**Comment by photopea** [comment]
I am afraid we can not implement such thing, in order keep our PSD files compatible with Adobe Photoshop :(
