### ISSUE TITLE
Adblock message appearing when no adblockers are enabled

### ISSUE THREAD

**Issue by goku12x** [photopea/photopea#3506]
Adblock message appearing when no adblockers are enabled.

**Comment by photopea** [comment]
Hi, try these steps: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by CryoPlenilune** [comment]
> Adblock message appearing when no adblockers are enabled.

Try clearing your cookies and cache. It's what worked for me!

**Comment by goku12x** [comment]
> > Adblock message appearing when no adblockers are enabled.
> 
> Try clearing your cookies and cache. It's what worked for me!

This worked, thanks!
