### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by poggers16** [photopea/photopea#3507]
I have a problem with photopea. It displays images weirdly. I tried it on desktop mode, it doesnt work.
![Screenshot_2021-07-07-12-06-18](https://user-images.githubusercontent.com/83654349/124703233-1d626c80-df1c-11eb-9921-597444b40d35.png)

**Comment by photopea** [comment]
Hi, could you send me your PSD file, which is displayed like this, to support@photopea.com ?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
