### ISSUE TITLE
About tuning on Ad Blocker on the browser Opera with the site tab Photopea 

### ISSUE THREAD

**Issue by BoscoMM** [photopea/photopea#3508]
Am I not supposed to use Photopea on the browser Opeara, is this company really needs money? It keeps showing the text notice saying "We use advertisement to get money for our development. Your device seems to be blocking ads. Please, let us show you ads, or buy a Premium account (Account - Log In - Buy).  5" But the fact that no ads are showing up even I turned the ads blocker off

**Comment by photopea** [comment]
I think you still have a browser extension, which is blocking ads. Maybe this can help you: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by CryoPlenilune** [comment]
> Am I not supposed to use Photopea on the browser Opeara, is this company really needs money? It keeps showing the text notice saying "We use advertisement to get money for our development. Your device seems to be blocking ads. Please, let us show you ads, or buy a Premium account (Account - Log In - Buy). 5" But the fact that no ads are showing up even I turned the ads blocker off

Try clearing your cookies and cache! That seems to be the usual issue
