### ISSUE TITLE
Ad Block not detecting 

### ISSUE THREAD

**Issue by DanielHoworth** [photopea/photopea#3510]
I've been using Photopea for a long time and have always had ad block paused on it and never had an issue. No I keep getting the pop off telling me to turn off my ad block. Even though it **is** off.

**Comment by photopea** [comment]
Do you see ads in Photopea or not?

Try this maybe: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by CryoPlenilune** [comment]
> I've been using Photopea for a long time and have always had ad block paused on it and never had an issue. No I keep getting the pop off telling me to turn off my ad block. Even though it **is** off.

Try clearing your cookies and cache!

**Comment by cyclops365** [comment]
"All extensions disabled, still no ads?
The servers of our partners could be blocked in your network (DNS block). It could be done by your internet provider, your school, your parents, your brother, or your government (in China or Iran). Get in touch with them and ask them why they do it. In general, when you pay someone for the internet connection, all public websites should be accessible, non of them should be blocked or censored."

This isn't really helpful. We can't ask our Government anything like this.

**Comment by photopea** [comment]
If your government removes ads from websites, that means your government knows what websites you visit and what do you do on them. That is quite scary. I think you can and should ask your government about this, if that is true.

**Comment by sl9dge** [comment]
I had the same issue (reported here) I just switched from Chrome to Firefox.

**Comment by CryoPlenilune** [comment]
> If your government removes ads from websites, that means your government knows what websites you visit and what do you do on them. That is quite scary. I think you can and should ask your government about this, if that is true.

This is not likely to be what's happening in 99.99% of cases. Photopea's ads come from google, so it is very unlikely that they're being blocked by an ISP. Google is blocked in china but it is extremely unlikely that your users are from china without employing the use of a VPN at least (meaning the ads would no longer be blocked.) 

Please just add some basic troubleshooting steps to your documentation, such as clearing your cookies and cache. The fact that you don't mention this at all when it's proven to be the answer across multiple tickets by now kind of makes me think you don't know about this very simple fix.

**Comment by photopea** [comment]
I don't think clearing cookies can help. If you disabled the ad blocking, just close and open Photopea, and it should work. There is no need of clearing cookies.

**Comment by TuxPaper** [comment]
I posted this on a closed issue:

> What I don't understand is, other web sites show ads just fine when I turn off Ad Block for them. But Photopea doesn't. It's clear to me, Photopea is doing something completely different than the majority of web sites that use ads. But yeah, put it on us users fix it.. that's great PR for sure.

Seriously, you are going to keep getting this issue raised over and over again (not by me, but by an endless stream of users), because Photopea is doing something non-standard.

**Comment by TuxPaper** [comment]
Cleaning cookies for "photopea.com" and "www.photopea.com" worked for me. The ads started displaying properly, at least for a few days, and then I have to repeat.

Every other "turn off ad blocker" prompt made from other sites work fine when I turn off ad blocker.  It's clear to me that it's something that Photopea is doing differently than every other page out there.

My request to the devs is to switch to the way other sites handle the ad-blocker prompt and ad-delivery.  I have no problem displaying ads for such a great project.

**Comment by photopea** [comment]
I guess it was fixed, so I will close it now.
