### ISSUE TITLE
Incorrect SVG export 

### ISSUE THREAD

**Issue by tejasgsh** [photopea/photopea#3511]
When I export a text layer of psd to svg, the export is not exactly as psd. 

This happens especially when the psd has text with one of the words in a sentence in a different color. 

I am attaching a sample screenshot of exported svg and original psd for your reference.

Thanks,
Tejas
![original-psd](https://user-images.githubusercontent.com/83121835/124763444-992adc00-df51-11eb-849d-bd3a6fff1816.png)
![exported-svg](https://user-images.githubusercontent.com/83121835/124763454-9b8d3600-df51-11eb-9d79-912d2fa7f565.png)

**Comment by photopea** [comment]
It should be fixed now :)
