### ISSUE TITLE
Text Placement

### ISSUE THREAD

**Issue by Crytkee** [photopea/photopea#3513]
I'm not able to place any text at all. It doesn't even show that the font loaded or anything. Could I please have help because this is kind of important what I'm doing!

**Comment by photopea** [comment]
Hi, could you try these steps? Let me know if it helped. 

https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by Crytkee** [comment]
its been fixed for over a month my dude
