### ISSUE TITLE
Curves & levels sample from image inverse?

### ISSUE THREAD

**Issue by philip757** [photopea/photopea#3515]
When I press Image --> Adjustments --> Curves/Levels --> or make a curves/levels layer adjustment and then click the shadow/black box (Sample from image) and click on a dark brown color from the background image it makes the photo darker and turns it more blue? It maybe it inverts the color selected or something. I tested it on a few images and they all did the same.

**Comment by photopea** [comment]
I just tried the same feature in Adobe Photoshop, and it works identically as in Photopea.

Are you sure you know what is that feature for? I think you need something else. Do you know any program which contains a feature that you need, so that we can see what you need?

**Comment by philip757** [comment]
Oh I didn't see you had to go into auto options and then choose Enhance Per Channel Contrast in photoshop maybe you could add that

**Comment by photopea** [comment]
Do you want a feature from Adobe Photoshop to be added to Photopea? What feature do you mean? Where is "Auto Options" in Photoshop?

**Comment by philip757** [comment]
If you go to curves there will be a auto button over the curve. Its used for color correction when making a composition. I wanna use it to blend the subject to the background. And yes i would like the feature to be added in photopea.

![Screenshot 2021-07-09 11 07 36](https://user-images.githubusercontent.com/87145257/125054052-16fffc00-e0a6-11eb-82d8-5fe09cee6979.png)

Auto options look like this:
![Screenshot 2021-07-09 11 07 49](https://user-images.githubusercontent.com/87145257/125054814-e4a2ce80-e0a6-11eb-9426-b1a519d1d678.png)

**Comment by photopea** [comment]
Let's work on it in this issue: https://github.com/photopea/photopea/issues/3572
