### ISSUE TITLE
Bug in smudge brush

### ISSUE THREAD

**Issue by HalfVoxel** [photopea/photopea#3516]
Two typos (255->248 and 24->21) cause the smudge brush to make the picture sliiightly more yellowish over time.

![image](https://user-images.githubusercontent.com/1144597/124986680-2e0a0400-e03c-11eb-8d71-878af7fbb7b7.png)

Example
======
Start, using a circular brush with 50% strength and 0% hardness:
![image](https://user-images.githubusercontent.com/1144597/124988166-f13f0c80-e03d-11eb-805f-658fd0cdc059.png)

Result (note that it's very yellow, the blue channel is much lower than the others):
![image](https://user-images.githubusercontent.com/1144597/124988109-e08e9680-e03d-11eb-8463-c98b8c4448d2.png)

**Comment by photopea** [comment]
I fixed it!  It happened only with Hardness<100%, that is why I never noticed it.

BTW. how did you find it in our code? :D

**Comment by HalfVoxel** [comment]
Cool!

Haha, I was debugging my own smudge tool implementation and decided to compare it to an existing implementation that I knew worked. It was a bit annoying to de-uglify the minified javascript code, but the inner workings were pretty clear after that.
