### ISSUE TITLE
Upload Font - Mont

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3518]
This font gets an error when uploading.

I can use it, but it does not get saved after close.
[Uploading Mont.zip…]()

**Comment by photopea** [comment]
I think the problem is not with a font, but with a Local Storage.

I have heard about cases, when a local storage in Chrome does not allow storing over 250 MB. How much data do you have there? You can check in Edit - Local Storage.

**Comment by avagp** [comment]
960kb

**Comment by photopea** [comment]
Your font was not uploaded to github, could you share it again?

If you load some other font to Photopea, is it added to a Local Storage?

**Comment by avagp** [comment]
this is the font:
[Mont.zip](https://github.com/photopea/photopea/files/6792497/Mont.zip)
It does not stick

But i have just tried with this other:
[relate.zip](https://github.com/photopea/photopea/files/6792522/relate.zip)


If i upload the whole zip, it loads, but it is not saved.

If i only upload the ttf file it loads AND saves.

**Comment by photopea** [comment]
Oh, you should have said that eariler. You need to load TTF or OTF files directly, files from a ZIP can not be stored in a local storage.

**Comment by avagp** [comment]
:)

i didn't know that zip files cannot be stored. Because it loads correctly,
i wouldn't suspect
