### ISSUE TITLE
Photopea Freezing

### ISSUE THREAD

**Issue by MorganM97** [photopea/photopea#3519]
I was drawing something, and then Photopea freezed on me. However, despite that, it still continues to give me adds. What's worse is that I haven't got a chance to save it as PSD, and with it being frozen, it won't let me save, and I didn't want to close the Photopea to avoid losing my progress of my image. Is there a way to fix all that?

**Comment by photopea** [comment]
What do you mean by freezing? How can I reproduce it? 

Can you make it happen in a browser with no browser extensions? Maybe you have an extension, which is mining bitcoins on the background or something, and uses too much memory, what causes a crash.

**Comment by MorganM97** [comment]
Like it's not letting me click on anything from the Photopea tab. And yes, I do have an extension, but I only drew the image on the tab instead, and I didn't want to close it to avoid losing progress of it, since I never got the chance to save it

**Comment by photopea** [comment]
I tried to draw in Photopea and it worked well. I need to make Photopea freeze myself, to be able to fix it. Please, describe steps how to make Photopea freeze.

**Comment by MorganM97** [comment]
I've been drawing the image for hours, from the sketch and then to the lineart. But just as I was about to color it, that's when it crashed.

**Comment by photopea** [comment]
Do you have at least 8 GB of RAM memory? If you have less, I recommend saving your work as a PSD at least once an hour.

I recommend disabling some browser extensions, in case some of them are influencing Photopea.

**Comment by MorganM97** [comment]
I have like about 16 GB of RAM memory, but thanks for the tip there. Looks like I have to start over the image from scratch, and it was a birthday gift for a friend of mine whose birthday is coming up later this month

**Comment by photopea** [comment]
Update your browser, old browsers could have bugs and close websites, that were opened for too long.

Maybe use a smaller resolution, e.g. 2000x2000 pixels instead of 4000x4000, or a smaller DPI.

**Comment by MorganM97** [comment]
I use Google Chrome, not sure if it has an update for that
