### ISSUE TITLE
Red eyes removal

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#352]
Sometimes I need remove red eyes from my photo. What is recommended way to remove red eyes in Photopea? Photoshop has specialized tool for it. Do you plan to add it to Photopea?

**Comment by photopea** [comment]
I think it can be done by selecting the eyes and changing saturation / brightness. But you are right, a speical tool would be great.

**Comment by nkkollaw** [comment]
There are so many apps for that...

**Comment by photopea** [comment]
@nkkollaw We don't want users to open their photos in 26 programs, to do what they want to do :D We need such feature in Photopea (you can do it now with desaturation / colorize, but it is probably too complicated).

**Comment by photopea** [comment]
Hi, I added such tool (it is in the same category as the Spot Healing Brush Tool, just like in Adobe Photoshop).

It is a very simple implementation. You paint with ti like with a brush. It desaturates and darkens the "red-ish" color below it.
