### ISSUE TITLE
Artboards - Background is not transparent

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3520]
Different from normal canvas, the artboards cannot have a transparent (chess) background.

So working with white layers get them invisible.
![image](https://user-images.githubusercontent.com/11801254/125006111-5d644500-e02b-11eb-944f-c1f398cb0827.png)

**Comment by photopea** [comment]
Many PSD files contain smart objects, which are PDF (with a transparent background, without a "white page"). So we need PDF artboards to have a transparent background.

But if we display every PDF artboard with a transparent background (chess), it would look confusing, the text would be hard to read. That is why I decided to visualize a transparent artboard with a white color.

Do you see any other solution? Would you mind, if Photopea opens all PDF files with "chess" as a background?

**Comment by MichalSZZ** [comment]
I think Photopea should open all PDF files as they look after opening in a browsers or any other PDF viewer. Mostly with white background. Or when user is opening the PDF file - it should to be option to change default white color?

In Photoshop when I create a new file with the artboards option checked - I can set the default background (default is white) to any other (for example black). When I export - the background in files from artboards is then black not as default one.

Maybe there is a parameter for changing the background of the artboard? After opening - like changing background for the "custom canvas color"?

Funny thing: In Photoshop I can't export artboards with transparency - even when I check that in "export as" window or in "artboards to file" :) It has always the default background color when I am exporting to PNG-24

**Comment by avagp** [comment]
Let me add my perspective to this:

I believe the default transparency of the artboards should be the same as the canvas: chess-transparent or the one you selected when creating the project.
![image](https://user-images.githubusercontent.com/11801254/125100209-d5238580-e0a6-11eb-832a-938b22539528.png)

Because, as now, if i create a new project with transparent background and artboards on, it will show white backgrounds, which is not what i have selected, and feels like a bug.

So taking that approach of the default system, now the PDFs will show chess-transparent, which is not a big deal, but if you are opening written documents, it could be. I do open written documents myself time to time, but I can totally bear it.

BUT, in Photoshop when you import a PDF file, it shows a prompt window, where you can set some settings:
![image](https://user-images.githubusercontent.com/11801254/125100889-99d58680-e0a7-11eb-8106-da0af13bc31b.png)

I personally don't want you to develop such a window, which i presume most of the time users will just click OK with the default options, but maybe, if you get people asking for white backgrounds, this could be a workaround.

OR, have an option on the menu bar where we can change the transparency background color of the actual project (if there is such a option like that, i am not aware of 🙃)

**Comment by avagp** [comment]
So, the quick solution might be adding a settings on the menu to change the background color of the actual project.

That way, you can leave everything as is now. People don't get any different, and users who work in white will have to change the background setting.

But please do make transparent background with artboards if i set it so on the creation of the project.

**Comment by avagp** [comment]
i need to export this logo in transparent background, but i can't  :(
Here is the PSD:
https://www.photopea.com/#iEH90kwQO

**Comment by photopea** [comment]
What do you mean? You set a white background to both artboards. And you also added a blue fill layer to each artboard. Why should it be transparent?

**Comment by avagp** [comment]
XD
I im removing the blue background, but i still get white background.

When i created the project i set chess-transparent background. When i create an artboard, it turns white.
(go ahead and create a new project with transparent background an artboards, it will be white)

Hope you can watch this video (it includes a bug):
[Screen recording 2021-07-11 13.47.02.zip](https://github.com/photopea/photopea/files/6797387/Screen.recording.2021-07-11.13.47.02.zip)

**Comment by photopea** [comment]
Your artboard has a background set to White. Set it to Transparent to export a transparent image.

Both White, and Transparent background of the artboard are visualized witha  white color, there is no checkboard behind artboards.

**Comment by avagp** [comment]
If both white and transparent background of the artboards are visualized
white (which i don't get why). How i do set the background to transparent
so i can export a white shape and get transparent background?

**Comment by photopea** [comment]
Ok, I made it work the same as in Adobe Photoshop.

The downside is, that almost all PDF files have a transparent background, which will be displayed with a chess board (which is not a problem for Photoshop, as Photoshop can not edit PDF files).

**Comment by avagp** [comment]
![image](https://user-images.githubusercontent.com/11801254/125210498-3053a480-e26e-11eb-9e2b-4755edc25081.png)


sorry, but the second artboard should be transparent as well?

**Comment by avagp** [comment]
I get the downside, but i do prefer that.

I could presume many people don't open written PDF documents on photopea. I personally do to change some things, but twice a year.

:)

And despite all, thank you Ivan.

Thank you very very much.

Sorry if sometimes i present myself as pushy

**Comment by photopea** [comment]
In your screnshot, you set white background to the artboard on the right.

**Comment by avagp** [comment]
How do i do that?
https://video.drift.com/v/abAfAIhInQw/

**Comment by photopea** [comment]
I think Window - Properties is the only way to change the artboard background in Adobe Photoshop, so I made it the same in Photopea.

I added the background parameters to the top menu of the Artboard tool :)

**Comment by avagp** [comment]
Can i ask that if i set the first artboard as transparent, the next one will be the same?

So, for instance, if i set a background color (blue), i always get blue when creating a new artboard?

**Comment by photopea** [comment]
Sure,but set the artboard color on the Artboard tool.

úterý 13. července 2021 Radical Dreamer ***@***.***>
napsal(a):

**Comment by avagp** [comment]
Here you mean?
![image](https://user-images.githubusercontent.com/11801254/125545286-4d79446a-dea1-482c-815d-224ca3dbfbd2.png)

Tell me when that update is done! :D

**Comment by photopea** [comment]
The Artboard Tool has an option to set the background of new artboards.

![image (2)](https://user-images.githubusercontent.com/15955558/125779311-17730676-855a-4479-b0dc-0dfa60c28425.png)

**Comment by avagp** [comment]
and....?

:)

Did you develop the feature?

**Comment by photopea** [comment]
What do you mean?

**Comment by avagp** [comment]
it is just a quality of life improvement:
[Screen recording 2021-07-22 12.41.17.zip](https://github.com/photopea/photopea/files/6863913/Screen.recording.2021-07-22.12.41.17.zip)

Btw, on new project you don't have a color picker when set to background
![image](https://user-images.githubusercontent.com/11801254/126676789-caaa43f7-c3fb-421a-9e1b-12cd4fb6dd94.png)

And also, on the new project window says background and in the Artboard tool says custom:
![image](https://user-images.githubusercontent.com/11801254/126676849-93f172d0-679d-446d-8326-0ac836884c40.png)


Shouldn't be the same?

**Comment by photopea** [comment]
I made it work this way. When you select an artboard, the background for future artboards is set to the background of a current artboard.

**Comment by avagp** [comment]
Perfect!!

Thanks Ivan

**Comment by photopea** [comment]
Sorry for refusing to do it right away :D

**Comment by avagp** [comment]
;) don't worry

Sorry to bother you again, but on the new project window it says background
instead of custom (or it says custom when creating artboards, instead of
background)
But also it does not have a color picker to pick your background color:
[image: image.png]

[image: image.png]

**Comment by photopea** [comment]
You can not set the custom color of a background when creating a new document.

The "Background" option means using the background color from the bottom of a toolbar.

Also, I can not see any images in your message. Please, do not send emails to github, reply at Github.com, or send emails to Photopea.com .

**Comment by avagp** [comment]
Here are the images attached:
![image](https://user-images.githubusercontent.com/11801254/127522907-064fc528-099b-4818-8129-4ddc45b25deb.png)
![image](https://user-images.githubusercontent.com/11801254/127522925-9747595a-a18d-46a1-a10c-ff442793c75a.png)


Oh... I did not even SUSPECT that you can select the color from the toolbar before creating a new project.
It is the same on Photoshop? Because i find it pretty non-intuitive.

🧐

**Comment by photopea** [comment]
So what exactly would you like me to do?

**Comment by avagp** [comment]
In Photoshop when you create a new project, and set it to custom background.

The color picker is right next to it, like the artboard tool has
![image](https://user-images.githubusercontent.com/11801254/127540282-8ca16a6e-6b00-44cf-af9e-295354751867.png)

So i was wondering if Photopea could have the same color picker next to custom Background on the new project window.

:)

**Comment by photopea** [comment]
Done :)

**Comment by avagp** [comment]
:)
