### ISSUE TITLE
Artboards - Feature request: invisible artboards show not be exported

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3521]
I have many projects with artboards. And sometimes i am having versions of the same thing, and i don't want to import it all everytime, and then going to the zip file and delete the ones i don't want to share.

So, if an artboard-folder is invisible (eye closed) it won't be exported.

Could it be ?  :)

**Comment by photopea** [comment]
If you want an artboard to be "exportable", add the "-e-" to the name, and then, use File - Export Layers.

**Comment by photopea** [comment]
But I see it exports transparent images now. So I fixed it - invisible artboards are not in a ZIP anymore.

**Comment by avagp** [comment]
Good! so much more intuitive approach
