### ISSUE TITLE
Photopea crashes

### ISSUE THREAD

**Issue by Bazz1027** [photopea/photopea#3522]
REDDIT Posts

ivanhoe90
·
3d
What is the size of your document in pixels? Is it a million, 100 million, a billion pixels?

Also, is your web browser updated? What do you mean by "compressed the incoming images"?

After Photopea.com is loaded, you can disconnect from the internet and use it offline. Photopea never sends anything anywhere, your internet speed is not important at all.

.

level 2
Bell14Maxx
OP
·
2d
Hey Ivanhoe 90

Thanks for taking the time to answer.

The original canvas is 4500 x 5400 p = 24,000,000 p

Browser updated 14days ago

After the issue arose I re did the designs but ran the images through an online compression tool

Regarding the internet I wasn't sure how much Photopea relied on the web but considering what you are saying it might be a memory issue

I got the jobdone eventually by completing 2/3's the exporting as a PNG and bringing it back to complete it, it worked but was very time consuming

Thanks again

.

User avatar
level 3
ivanhoe90
·
2d
24 million pixels is not that much, how many layers did you have? Is WebGL enabled? You can check in More - Use WebGL.

Also, what operation exactly was slow? Or was even e.g. zooming in and out slow?

I recommend saving PSD over PNG, so that you can have all your layers, etc.

.

level 4
Bell14Maxx
OP
·
2d
Hi

Agreed 24 mil should not have touched the sides and Yes webGL is enabled.

Usually I use about 7-12 layers, again not that many.

It's not always the exact same operation in different designs but each design has it's own point of failure

example: one design I completed but some dufuss (me) had a spelling error, Photopea was struggling as I wrapped up so I managed to save it, but when I brought it back it loaded but as soon as I went to correct the spelling it all went belly up.... 7 layers on that one

example 2: design completed and want to do a distressed overlay, the overlay loaded but as soon as I clicked on the overlay image, down went Photopea

I used to use Powerpoint but.....I'll let you work out how much fun I had doing that, Photopea is a much better option

Yep! tried saving a project that I was struggling with as PSD but when opened again the same problem was back, so saving as PNG did allow me to complete the job.

Not perfect but!!

I'm starting to think the problem maybe hardware related ie graphics card but I've always been able to run multiple apps but now I'm shutting down all other apps while using Photopea which is probably not needed and the issue still exists.

Anyway, thanks again

B & M

1

.
User avatar
level 5
ivanhoe90
·
2d
Are you using any browser extensions? Some extensions could be mining bitcoins in the backgorund. Even when the extension is named "Google Search", do not get confused, anyone can create an extension with such name.

Please, try to reproduce some issue (find steps, which make Photopea crash every time when you follow them). Then, press "Report a bug" in the top right part of Photopea and describe it to us.

.

**Comment by photopea** [comment]
Hi, are you the person from Reddit? Did you find a way to reproduce the issue?

**Comment by Bazz1027** [comment]
Heyt-shirt design

 

Guilty as charged 😊

 

Yes it has happened again, and in this case I was just trying to apply grunge effect to a t shirt design. 

 

Not sure what to do next

S

**Comment by photopea** [comment]
What is a grunge effect? Can you describe steps, how can I reproduce the problem on my computer?

**Comment by Bazz1027** [comment]
Hi

OK a grunge is also called distressed and I will use it as an overlay to make my tshirt design look older, vintage or dirty. It’s simply an overlay when clipped adds a dirty effect to the design.

 

I tried to send a couple of file but they were rejected at your end

Cheers

**Comment by photopea** [comment]
What end do you mean?

Can you make Photopea crash again? If yes, could you describe how you do it? Photopea never crashed when I was using it.

**Comment by Bazz1027** [comment]
Hi

Sorry for the delay….real job issues, anyway I’ve gone away from trying to apply grunge effect and I’ve returned to a text based design that has the same issue of Photopea crashing.

 

I’ll lay out everything that happens leading up to the crash and what happens next, and yes I can get it to crash consistently

 

OK

Start by opening a new project 4500 x 5400px 100 dpi on transparent background

 

Text 1 Waxxed 700 pxl, expaned to 1305pxl via move tool & chicle font coloured dark blue, increased via move tool to 3105 pxl and warped using upper shell and adjusting it to give a 60’s larva lamp vibe

 

Text 2 Vaxxed same settings as 1

 

Text 3 Caffeinated same settings as 1 & 2

 

Text 4 & smaller

 

Each text was coloured and a 23pxl white stroke, I then added a coffee cup graphic but only the same height of a text line. Somewhere during the creating the stroke on the third text line the Photopea crashed, I mean black screen in the work space but I did notice the move tool handle were still showing when I move the cursor over the hot spot. When the crash occurs the software re boot and come back as black workspace but the layer panel shows the layer that I created.

 

That is about it, to my knowledge no other settings existed, and the project was created in incognito mode

 

I’d appreciate your thoughts

 

Thanks

**Comment by photopea** [comment]
I think I did the same thing and it worked well.

![image (3)](https://user-images.githubusercontent.com/15955558/125780319-2fe0d469-af9c-4d7a-8ebf-18002e5a2f4b.png)

From what you describe, it sounds like your computer ran out of WebGL memory. Is your computer older than 10 years? Does it still crash, if you disable WebGL in More - Use WebGL?

**Comment by Bazz1027** [comment]
Hey thanks

 

Yep it makes no sense to me either I’m currently working on a design while not that complicated has about 4 or 5 effect to 9 different text elements and some other graphic and no issue, YET!! Go figure…

 

The laptop I’m using is barely 12 months old and was originally purchased as a gaming pc so it’s well speced

 

I’ll try disabling web GL and see but I might max out the RAM, but that seems like a waste but might help

 

Look, I appreciate your time and patience, Thank You

**Comment by photopea** [comment]
Photopea should not crash on such a new laptop. Could you update your web browser? What browser and version do you use?

**Comment by photopea** [comment]
How many tabs do you have opened besides Photopea? Of course, if other websites use a lot of memory, browser will not be able to give this memory to Photopea, even for a simple task.

**Comment by Bazz1027** [comment]
OK, I hadn’t thought of that, but it sounds a bit querky but I’ll shut down chrome and try it again

 

Thanks

**Comment by photopea** [comment]
I hope it was fixed. So in short, there is always some limit, when your computer runs out of RAM, and kills Photopea.

**Comment by Bazz1027** [comment]
Hey thanks for checking in……….I’m thinking it’s a local issue, but I’ve got work arounds, so I’m still using Photopea….and enjoying it.

Thanks for your patience

Cheers

**Comment by CyanShulkerBox** [comment]
I have the same issue......ummm.... Its not really the same BUT.... When I save a png on my mobile photopia/photopea app on my mobile, it Crashes... 

Android 11

**Comment by CyanShulkerBox** [comment]
Also.... How can I rasterize layer on photopea???

**Comment by photopea** [comment]
Press Layer - Rasterize.

**Comment by CyanShulkerBox** [comment]
> Press Layer - Rasterize.

When I press, NOTHING happends

**Comment by CyanShulkerBox** [comment]
And I need to not crash when i save my project to PNG.

**Comment by CyanShulkerBox** [comment]
And I need to not crash when i save my project to PNG.

**Comment by photopea** [comment]
What do you expect to happen when you rasterize? The effect depends on a kind of layer.

Please, describe, what should I do to make Photopea crash. If I can not see the problem myself, I can not fix it.

**Comment by CyanShulkerBox** [comment]
I dont mean when i rasterize, I crash....
I mean... When i save/download my finished project to png, i crash
