### ISSUE TITLE
Filters drop down menu

### ISSUE THREAD

**Issue by JoelVandas** [photopea/photopea#3523]
i cant select any filters to apply to my image? No selection in the filter tab is working i checked the other tabs and i get drop boxes for them but i cant select anything in the filters drop down menu? im trying to apply a guassian blur but when i click nothing happens?

**Comment by photopea** [comment]
Hi, I am very sorry, it is fixed now.

**Comment by JoelVandas** [comment]
still doesn't seem to be working? i have reloaded photopea

**Comment by photopea** [comment]
Have you hard-reload it with Shift F5? Browsers store Photopea for one hour, so you are still seeing a version from an hour ago.

Or use Photopea in Incognito mode for the next hour, until your browser is able to load the actual website in a normal mode.

**Comment by JoelVandas** [comment]
its working now thank you for doing it so quickly :)
