### ISSUE TITLE
save button doesn't work

### ISSUE THREAD

**Issue by NicoLuiten** [photopea/photopea#3526]
I use a chromebook and the save button doesn't work. 
Now I have to use the "Save PSD/PSB" button to save but this create each time a new document. 
the "save" (control + s) button did work until a week ago. 

I have tried to use it with a black chromebook account (without any extensions installed) but it was having the same issue. 

Best 
Nico

**Comment by photopea** [comment]
Hi, I am very sorry, it is fixed now. Reload Photopea with Shift+F5.
