### ISSUE TITLE
Polygone lasso tool changing selection seems to also effect (pen tool, free hand lasso tool and magnetic lasso)

### ISSUE THREAD

**Issue by richardgoslingAOS** [photopea/photopea#3528]
We have seen an issue with the polygon tool, if you draw a shape and then draw a different shape then a random shape is displayed.

Bit odd am grabbing screenshots now, but if this is a known issue please can you let us know.

**Draw Triangle with Polygon Laso Selector**
![image](https://user-images.githubusercontent.com/58290878/125063923-ff297780-e0a7-11eb-9a3d-31425e661327.png)

**Draw another Triangle over the top**
![image](https://user-images.githubusercontent.com/58290878/125064112-339d3380-e0a8-11eb-8f9a-c8856e722aef.png)

**Random Shape is displayed**
![image](https://user-images.githubusercontent.com/58290878/125064157-40218c00-e0a8-11eb-940e-505834731d0c.png)

**Comment by photopea** [comment]
I am very sorry, it is fixed now.
