### ISSUE TITLE
Saying I have an ad-blocker when I don't have mine enabled

### ISSUE THREAD

**Issue by UsedSpxse** [photopea/photopea#3529]
I don't have my adblocker currently enabled as on Brave you can disable it. I disable it and reload and wit 10 seconds and I get the notification saying I have it enabled, I then tried enabling and disabling and I get the same result. I tried to even install the Photopea app and it is resulting in the same way. This is getting really annoying as I am using Photopea every day now and I need to be able to work quickly without having to constantly click 'Ok'.

**Best Regards,**
Space

![image](https://user-images.githubusercontent.com/82980901/125083753-c59c4080-e096-11eb-846d-9931439b8f18.png)

**Comment by photopea** [comment]
But do you see ads in Photopea or not?

**Comment by UsedSpxse** [comment]
I do not.

**Comment by UsedSpxse** [comment]
![image](https://user-images.githubusercontent.com/82980901/125090548-7279bc00-e09d-11eb-80ca-9865fb987900.png)This is what I see,

**Comment by UsedSpxse** [comment]
I see this. 
![image](https://user-images.githubusercontent.com/82980901/125090624-8ae9d680-e09d-11eb-870b-5852cfa10b62.png)

**Comment by photopea** [comment]
I don't know much about the Brave browser :( There are many people with normal browsers, who do not see such any message in Photopea. So clearly, your browser is "different" somehow.

I think it is a bug in your browser. You can ask the creators of your browser to fix it, or use another browser.

**Comment by UsedSpxse** [comment]
Yup, I'll use Chrome for Photopea.
