### ISSUE TITLE
Ads are not blocked still getting popup

### ISSUE THREAD

**Issue by sunnag7** [photopea/photopea#3531]
I use a brave browser which has a built-in adblocker, I turned it off for photopea.com, but still receiving a popup saying "We use advertisement to get money for our development. Your device seems to be blocking ads. Please, let us show you ads, or buy a Premium account (Account - Log In - Buy).  5"
Also my system hangs due to this and cannot work further. Can you please make this adblock popup less intrusive. I am happy to watch ads.

**Comment by photopea** [comment]
Hi, can you disable the ad blocking? I am not familiar with Brave and don't know how to do it :(

I tried Photopea in Chrome, Firefox, Edge and Safari, without any ad blockers, and there was no intrusive message.

Or ask someone with Brave who knows how to turn off ad blocking.
