### ISSUE TITLE
Adblocker popup

### ISSUE THREAD

**Issue by domenique1** [photopea/photopea#3533]
Hello,

My Adblocker was off and I kept getting the popup persistently, and then I uninstalled it and kept getting it (even after refreshing and emptying my cache)... I've always turned it off to support y'all, but this popup is really f-ing annoying.

**Comment by domenique1** [comment]
Also, once I click 'OK', my tool is set to being clicked and messes up what I'm doing.

**Comment by photopea** [comment]
Hi, try this tutorial: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/
