### ISSUE TITLE
A problem with opening a PSD files.

### ISSUE THREAD

**Issue by beluwuga** [photopea/photopea#3534]
Hello, writing from a Windows OC from Opera GX, after yersteday i got created my project, after one day when i got tryed to open this project with a PSD format i got error that unknow format and code of error u0000 i dont know anything about that problem.
I 
![obraz_2021-07-10_170453](https://user-images.githubusercontent.com/87236830/125167459-f4064280-e1a0-11eb-836e-6d7a6ba25f0d.png)
will wait for the any instructions/helps if i can get it from you. Thanks so much.

**Comment by photopea** [comment]
Can you open any other image file from your computer in Photopea?

Can you open your PSD in any program other than Photopea?

Can you share your PSD file with us?

**Comment by beluwuga** [comment]
Hello, thanks for responding today, sorry for problems with grammar, of course i can send a file in a dropbox bc Github doest  support PSD files. I can open that image like in one big object. But i dont have photoshop or any etc programms. I can't open any of my projects.  Sorry for problems i can send a file tommorov.

**Comment by beluwuga** [comment]
https://drive.google.com/file/d/1af8TfNFQaRHxgC8UALXvsFqbn478vvnT/view?usp=sharing
https://drive.google.com/file/d/15qrZqyf-9GZCtX15wemGB4EFfPvZIjTs/view?usp=sharing 
a two files that i cant open. Waiting for the response.

**Comment by photopea** [comment]
I requested access to your files. You can send them to support@photopea.com , too.

**Comment by beluwuga** [comment]
Done.

**Comment by photopea** [comment]
Both of your files have 0 (zero) bytes. So they can not have any content.

I think you are using a browser extensions, which removes content from downloaded files. Try to disable that extension, or disable all extensions, if you don't know what they do.

**Comment by beluwuga** [comment]
Its telling that all my files got destroyed?

**Comment by photopea** [comment]
I don't know. If they are zero bytes, they are empty.

neděle 11. července 2021 beluwuga ***@***.***> napsal(a):

**Comment by photopea** [comment]
We switched to the old saving mechanism, it should not create zero-length files even in Opera.
