### ISSUE TITLE
Cannot open saved PDF

### ISSUE THREAD

**Issue by Mehss** [photopea/photopea#3537]
Hello,
I am having problem with a file
https://www.photopea.com/#i04w_ou7E

while i can publish the file via photopea, trying to save it as PDF and reopening it in photopea/other programs result in an error
![image](https://user-images.githubusercontent.com/54127504/125188649-b667ef00-e25e-11eb-81f0-de1b856f2e96.png)

if it affects anything, the file used an .AI template, but i cannot find a way to save it as .AI in photopea

**Comment by Mehss** [comment]
i am sorry about the lack of ads, i just realized that the site has ads after i looked up other issues

**Comment by photopea** [comment]
Hi, I opened your link. I exported your document as a PDF (test.pdf, 191 kB). That PDF is openable in Adobe Reader, in a Chrome browser, in Photopea ... so I think there is nothing wrong with that PDF.

How large is your PDF? Is it the same as mine? Do you use any software, which can modify downloaded files (to protect you from downloading viruses or something)?

**Comment by Mehss** [comment]
i'm sorry, not pdf, psd

**Comment by photopea** [comment]
I opened your link and pressed File - Save as PSD. A file "test.psd" was saved to my computer, 4.1 MB.

Try these and let me know if it helped: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details :(
