### ISSUE TITLE
Artboard - Moving artboard crashes Photopea

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3538]
Hi Ivan.

Here is my PSD:
[Cartas Cultura Chupística.zip](https://github.com/photopea/photopea/files/6797567/Cartas.Cultura.Chupistica.zip)

If you move the Artboard named: Regla B, it will get a windows 95 effect 
![image](https://user-images.githubusercontent.com/11801254/125208247-6a697a00-e25f-11eb-8967-953333cbae87.png)

And then Photopea gets stuck. But is only with that artboard :/

**Comment by avagp** [comment]
![image](https://user-images.githubusercontent.com/11801254/125208311-971d9180-e25f-11eb-8c36-a5a428319b5b.png)

**Comment by photopea** [comment]
I think I have fixed it, thanks for reporting! :)

**Comment by avagp** [comment]
https://www.photopea.com/#imkMD0Qz-

Here is the updated file.

Keeps happening when moving the frame around the cards
![Screenshot 2021-07-12 18 24 49](https://user-images.githubusercontent.com/11801254/125363501-b4755d00-e33e-11eb-8c6a-7b51ef0df95a.png)

**Comment by avagp** [comment]
Also, with the same file if i copy to a new project all the artboards on the first row i get this:
![image](https://user-images.githubusercontent.com/11801254/125363747-336a9580-e33f-11eb-874b-977532785803.png)
