### ISSUE TITLE
Live shape with ability to change corner radius even after rotation

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3539]
Almost a year ago Adobe gave us a new functionality for live shapes. 
For example the rectangle shape can have an active corner radius parameter - even after rotation.

Is it possible to implement that feature in Photopea?

**Comment by MichalSZZ** [comment]
Hi @photopea 
Do you need PSD with that shape, generated in newest PS CC? Or any other help?

**Comment by mustafaGFX** [comment]
I have asked for this before #2737

I hope @photopea responds cuz this feature is needed

**Comment by photopea** [comment]
Yes, I would like to implement it :)

**Comment by photopea** [comment]
I implemented it :)
