### ISSUE TITLE
Free Transform issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#354]
I created new file.
I used Free Transform and with mouse I moved bottom right corner so width and height are zero.
First issue is it shows "NaN" instead of number in the top now.
Additionaly when you do this you can't grab the corner and move it back you are stuck with zero width or height.
After I set by this method zero width and height I confirmed and used Free Transform again.
It showed few pixel squere for some reason so I zoomed in and did it again (set width height to zero) and confirmed.
Third time I tried to use Free Transform it shows 0x0px now...
Next I selected all (CTRL+A)
And tried to do Free Transform again
->
Uncaught TypeError: Cannot read property 'UN' of null
    at m.G.xs (pp.js:2802)
    at m.G.enable (pp.js:2799)
    at ct.Kb (pp.js:5913)
    at ct.KQ (pp.js:5879)
    at ct.Nl.v (pp.js:6)
    at ct.ky.v (pp.js:4124)
    at c$.ky.v (pp.js:4124)
    at c$.pd (pp.js:6041)
    at kQ.Nl.v (pp.js:6)
    at kQ.ky.v (pp.js:4124)

**Comment by photopea** [comment]
It should be fixed now.
