### ISSUE TITLE
Artboards - Incorrect guides

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3540]
On this file:
[Cartas Cultura Chupística.zip](https://github.com/photopea/photopea/files/6797712/Cartas.Cultura.Chupistica.zip)

I am trying to put a guide on the center of the artboard (which is 700px wide), and i put it on 350, but i noticed it is not the center:
![image](https://user-images.githubusercontent.com/11801254/125210815-131fd580-e270-11eb-81e5-2bd078b073c8.png)

Differs what the guide indicates to what the ruler indicates.

I see that the ruler is correct, not the guide.

**Comment by photopea** [comment]
your ZIP contains a PNG file and I could not reproduce your screnshot with it :(

**Comment by avagp** [comment]
Sorry, here it is:
https://www.photopea.com/#iLsHLzVN_

**Comment by photopea** [comment]
I fixed it :)
