### ISSUE TITLE
Bug na função de traçado da ferramenta retângulo (u)

### ISSUE THREAD

**Issue by raabedesigner** [photopea/photopea#3541]
O photopea é uma ferramenta excelente, mas recentemente um bug na função de traçado da ferramenta retângulo (u) tem me atrapalhado bastante.
  Quando ativo a ferramenta U, se tento MOVER o retângulo, ele deixa marcas no meu design, estragando tudo. 
  Esse bug é recente, antes estava funcionando normal. Espero que possam resolver logo.

///

  Well, photopea is a great tool, but recently a bug in the rectangle tool's stroke function (u) has been bothering me a lot.
  When I activate the U tool, if I try to MOVE the rectangle, it leaves marks on my design, ruining everything.
  This bug is recent, before it was working normally. I hope they can resolve it soon.

**Comment by avagp** [comment]
Acho que tem a ver com esse bug
#3538

**Comment by photopea** [comment]
I am sorry guys, it should be fixed now.
