### ISSUE TITLE
Artboards - Moving artboards with properties, don't move the layers along it

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3544]
When moving layers drag and dropping my the cursor, all good.

But if i change the X,Y properties of the artboard, only the space moves, but all the layers stay put.
![image](https://user-images.githubusercontent.com/11801254/125365608-901b7f80-e342-11eb-81b7-a2d13a7a9efb.png)

**Comment by photopea** [comment]
fixed :)

**Comment by avagp** [comment]
:D
