### ISSUE TITLE
Shapes are invisible

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3545]
On this file:
https://www.photopea.com/#i4cw4Uv-L

The little icons on the corner of the last card are invisible, but they are over there!  :O
![image](https://user-images.githubusercontent.com/11801254/125367192-b4c52680-e345-11eb-84b6-6a27ebdf909b.png)

**Comment by photopea** [comment]
They seem to be located outside the artboard :(

![image (1)](https://user-images.githubusercontent.com/15955558/125418837-e8fe96e2-9498-47b7-9f76-3f26d8a978de.png)

**Comment by photopea** [comment]
Enable "transform controls" of the Move tool, to see where any layer is.

**Comment by avagp** [comment]
mmmm

the problem was, that i copied the frame from another artboard, and all moved along, but the cebadas.

That is why.

But i have tried now doing the same thing, and i cannot repro, so i presume you fixed it with the other recent fixes.

:)
