### ISSUE TITLE
Export EMF - Exporting nothing 

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3546]
I might be the only user exporting to EMF, but i use it for making vector graphics on PowerPoint.
[try to EMF.zip](https://github.com/photopea/photopea/files/6805011/try.to.EMF.zip)

But when trying to view it i get nothing.
(i use this to view https://products.aspose.app/imaging/image-view/emf)

And when importing to PPT, i get this:
![Screenshot 2021-07-12 20 31 15](https://user-images.githubusercontent.com/11801254/125372097-420d7880-e350-11eb-91d8-9bed04f12adc.png)

I have done this before. And PPT can import EMF.

Even though Photopea opens it perfectly.

**Comment by avagp** [comment]
If i export to SVG and then convert it to EMF on CloudConvert.com

I can insert it on PPT

**Comment by photopea** [comment]
Hi, could you share a PSD, which generates this "broken" EMF file?

**Comment by avagp** [comment]
https://www.photopea.com/#i6BsxycvJ

**Comment by photopea** [comment]
It should be fixed now :)

**Comment by avagp** [comment]
Hello again.

I am trying to download this PSD to EMF, and when i open it, looks like this:
![image](https://user-images.githubusercontent.com/11801254/132797398-579959dc-366f-40e7-85c0-e9190b40e5a8.png)

PSD: [Tipo A.zip](https://github.com/photopea/photopea/files/7141158/Tipo.A.zip)

**Comment by avagp** [comment]
i learned how EMF works.

You cannot have a vector over a vector.

That is why i get this square on the 3.

I have created separated vectors for all, and works great!

**Comment by photopea** [comment]
When I export your PSD to EMF as it is, it becomes a 8 kB file, and I can not open that EMF in MS Paint.

How do you open your EMF files? Is there a bug in MS Paint?

**Comment by avagp** [comment]
I open it a EMF viewer really.

I didn't know that it could be opened in MS Paint.

I use EMF to create custom vector graphics for Google Slides actually, like i answered you in issue 3723

**Comment by photopea** [comment]
Could you tell me a link to the EMF viewer for Windows? There are lots of apps named "EMF viewer", I am scared of downloading some viruses.

**Comment by photopea** [comment]
BTW. I think you are putting too much effort into it. If you export a PNG of 4000x4000 pixels, it still can be 10 - 100 kB large, and the quality is sufficient for most of cases.

Look at this PNG, it is 4000x4500 pixels and 70 kB.

![acid](https://user-images.githubusercontent.com/15955558/132961291-7856ea25-0b3d-46e5-b0a9-f2e0ad139749.png)

**Comment by avagp** [comment]
For windows, i don't know.

I use this online viewer: https://products.groupdocs.app/viewer/emf

And i have tried using hi-def images, but it is not the same. :/

On the final printed product, you can tell the difference on definition between vectors and bitmaps.

**Comment by photopea** [comment]
Please, ask Google to support modern formats like SVG or PDF. Or use other tools to convert SVG to WMF / EMF.

I think we should boycott WMF and EMF, just like Apple boycotted Flash Player on an iPhone, in order to speed up the switch to open standards (SVG and PDF).
