### ISSUE TITLE
Home and End while typing text

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#355]
I can use only cursor arrows to navigate cursor while typing text with Type Tool but keys Home and End on my keyboard are not working. I would like to use them to move cursor to the beginning or to the end of text.

**Comment by photopea** [comment]
It was implemented! Thank you for your suggestion.

**Comment by hxim** [comment]
@photopea 
It works ok but I just noticed I can't use Shift+Home and Shift+End when making selection.
Can you make it so when holding Shift you don't lose selection?

**Comment by photopea** [comment]
It was fixed, too.
