### ISSUE TITLE
cutout filter

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#3550]
whenever I apply the cutout filter this happens and everything is gone :(  

![Screenshot (235)](https://user-images.githubusercontent.com/70863817/125611118-a1b18349-1a5d-4c32-a0e7-b591d354c47a.png)

**Comment by photopea** [comment]
Can you describe how I can reproduce it? Can you show me a picture, on which it happens?

**Comment by photopea** [comment]
I tried it with this image: https://www.photopea.com/promo/icon512.png  and it does not crash, it works as expected :(

**Comment by mustafaGFX** [comment]
try here
https://www.photopea.com/#iQ19CH6Xu

maybe cuz I change the values quickly ?!
I don't know but it doesn't crash with any other filter

**Comment by nothingshiru** [comment]
> maybe cuz I change the values quickly ?!

I tried on my device. And that's right. when changed the values quickly, Photopea crashed.

**Comment by photopea** [comment]
My old code contained a crazy and "dirty" algorithm (I was not sure about its correctness), and it used a lot of memory in some cases.

I made a new algorithm, which is simpler and more transparent. It shoud not crash now, and it can even give better results. This method is also used in Vectorize Bitmap and Reduce Colors.
