### ISSUE TITLE
text does not show up when im typing, I cannot see the text I typed 

### ISSUE THREAD

**Issue by Joslim2** [photopea/photopea#3551]

**Comment by photopea** [comment]
Can you try it in Incognito mode? I think you have a browser extension,
which breaks Photopea

Ivan

středa 14. července 2021 Joslim2 ***@***.***> napsal(a):

**Comment by Joslim2** [comment]
how to do this?

**Comment by photopea** [comment]
Are you using Google Chrome? Go into about://extensions, and disable all extensions there.

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by Joslim2** [comment]
yers
