### ISSUE TITLE
When I save a Psd the file is saved as a 0 byte file

### ISSUE THREAD

**Issue by 100020001** [photopea/photopea#3552]
When I save a PSD the **file is saved as a 0 byte file**.
If I save as PSD/PSD a PSD, the file is saved correctly.

**Comment by photopea** [comment]
Could you update your web browser? Does it happen again n Incognito mode, too?

**Comment by 100020001** [comment]
Oh. Actually Im running "WebCatalog". Just updated to the latest. Same. Cleared browsing data. Same.

**Comment by photopea** [comment]
Can you disable all your browser extensions and try it again?

**Comment by 100020001** [comment]
I have no extensions installed.

**Comment by photopea** [comment]
If your browser uses Chromium 90, it will not work. Use a browser with Chromium 91 or later, or Firefox/safari.

**Comment by 100020001** [comment]
The build of WebCatalog I have installed users Chromium "91.0.4472.124" according to navigator.appVersion.

**Comment by photopea** [comment]
Our File - Save uses File System API https://web.dev/file-system-access/ in Chromium browsers.

I think your browser extensions, or the creators of your browser blocked it somehow.  Ask the creators of your browser to unlock it, or use some better browser like Opera, Edge or Safari.

**Comment by 100020001** [comment]
Does the "Save PSD/PSB" not use the same functionality? Since that that works to save Psd. But when I choose "Save PSD", the file gets corrupt and saved s empty.
It's kind of dangerous and I actually lost a lot of work by having a file deleted.

**Comment by photopea** [comment]
No, Save PSD/PSB, and File - Export do not use this functionality.

You just need a normal browser to use Photopea correctly, and no extensions, which modify or block standard browser features.

I am very sorry that your files were lost, but if your browser or your extension decides to clear a downloaded file, there is nothing a website can do about it :(

**Comment by photopea** [comment]
I recommend to use a "normal", updated browser in order to use Photopea.

What you report is a bug in your browser. Ask people who created your browser to fix it, or switch to a different browser.
