### ISSUE TITLE
Adblock Bug

### ISSUE THREAD

**Issue by Jousw** [photopea/photopea#3554]
What Is This I Don't Have Any Adblock Enabled 
![Photopea](https://user-images.githubusercontent.com/87468448/125751789-f5a09f67-e73e-4088-9e48-ca8503334324.png)

**Comment by PeTr0sLaV** [comment]
![image](https://user-images.githubusercontent.com/87473381/125768157-de76a8c2-bb99-4445-b535-1223d9ac1f1f.png)
I have the same problem.

**Comment by photopea** [comment]
Hi guys, try this: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by photopea** [comment]
I guess you managed to fix it, so I will close it now.
