### ISSUE TITLE
I've paid premium but it seems don't work

### ISSUE THREAD

**Issue by yanghocho** [photopea/photopea#3555]
I paid 40 for 365 day single premium, but my browser still says I must turn on adblock or pay for premium.
Can check my photopea account yanghocho@naver.com and fix the issue?

I have paypal reciept but idk I can put the number in public or not.
mail to me if needed.

please fix this ASAP

**Comment by photopea** [comment]
There is usually an easy fix, try these steps: https://www.photopea.com/tuts/premium-account-does-not-work/

**Comment by photopea** [comment]
But I see you have started a case on PayPal, so I sent you a refund. But you can keep the Premium :)
