### ISSUE TITLE
Feature Request: Bigger anchor/handle for touchscreen

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3556]
Current size of them are too small for finger. 
It would be nice to have an option to make it twice or three times bigger. You can add it in Edit - Preferences. 
![screenshot_20210716_033208](https://user-images.githubusercontent.com/79258245/125846844-ff0c59b4-d0e2-4556-92ed-1fde0a3427f4.png)

**Comment by photopea** [comment]
Many devices have both a touchscreen and a mouse.

I fixed it: if the current event is a touch, the active area is larger. I applied it to a the free transform, too.

**Comment by nothingshiru** [comment]
Wow, I didn't think that was possible. 
Could you apply it to guides too? Now it is not very easy to move a existing guide with finger.

**Comment by photopea** [comment]
done :)
