### ISSUE TITLE
Feature Request: Auto-click on blank area after disabled virtual keys/ closed virtual keys menu

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3557]
On Chrome, Edge, Firefox for Android, when disabled a virtual key or closed the virtual keys menu, they still have a dark background color until clicked on anywhere else. 
Is it possible to let Photopea click on blank area automatically when a virtual key has been disabled or virtual keys menu has been clicked? 
![screenshot_20210716_035016 (1)](https://user-images.githubusercontent.com/79258245/125850992-2acc3e56-6b8a-4594-87f7-0888e5a7249c.png)

**Comment by photopea** [comment]
It should be fixed now.

**Comment by nothingshiru** [comment]
Nice！
