### ISSUE TITLE
Feature Request: Make height of window of properties panel adjustable

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3558]

**Comment by photopea** [comment]
Hi, do you mean only the Window - Properties window - dragging the "black corner"? Is there anything what does not fit in the current size?

**Comment by nothingshiru** [comment]
It obscures more than a quarter of the canvas on my device. Sometimes I want to make the window a little smaller.
![Screenshot_20210716_165647_com android chrome](https://user-images.githubusercontent.com/79258245/125922676-50890d60-dece-4b59-9045-bcaeefd55896.png)

**Comment by photopea** [comment]
I fixed it, but there is still a maximum width of 280 pixels.

**Comment by nothingshiru** [comment]
What i meant was making the height of the window adjustable, and providing vertical scroll bars when the window size is not large enough to display all the content......

**Comment by nothingshiru** [comment]
I recently learned a little bit of html and now made this [https://jsbin.com/pafujaq/4/edit?css,output](url) to explain my idea. 
The maximum height of .window should be the same as the height of .container. But I don't know how to do that.

**Comment by photopea** [comment]
I don't think it is a good idea. I prefer the "automatic height", avoiding sliders.

Some adjustments have only one slider, so they use a small space, while large adjustments use a lot of space. Seeing all options at once is better than scrolling in a small window.

**Comment by nothingshiru** [comment]
It is good to be able to see all options at once. But sometimes the images in the canvas need that space more than the panel window. 

Take a look at the screenshots of my phone. 

![Screenshot_20210718_162238_com android chrome](https://user-images.githubusercontent.com/79258245/126061095-24334f58-d9bc-4c23-81bc-c971006e629a.jpg)
![Screenshot_20210718_162307_com android chrome](https://user-images.githubusercontent.com/79258245/126061099-10e111f6-4207-4f15-b0d5-9f63131d88ab.jpg)

More than half of the area is taken up by the panel window. Adjustable width didn't help. In this case I prefer to see only one slider at once.

**Comment by photopea** [comment]
Ok, I made the Properties window fully resizable and scrollable.

**Comment by nothingshiru** [comment]
> The maximum height of .window should be the same as the height of .container. 

Is this can be done?

**Comment by nothingshiru** [comment]
> Can this be done ?

Hi, what do you think about it ?

**Comment by photopea** [comment]
What is a container? What exactly do you mean by that?

**Comment by nothingshiru** [comment]
The point of "Panel Height Adjustable" is to make the panel smaller rather than larger than necessary. The maximum height of the panel should be just high enough to display all options (the black scrollbar is not visible at this point), and the panel height should not be adjustable any further.
![Screenshot_20210731_180112_com android chrome](https://user-images.githubusercontent.com/79258245/127736697-e0e0492d-25fd-46cb-a83c-d57520f5dfe1.png)

**Comment by photopea** [comment]
We can not make a different mechanism of dragging a corner for each panel. It should work the same for all panels.

I think it is useful to resize the panel to whatever size you want, e.g. for Glyphs, to see as many glyphs as possible.
