### ISSUE TITLE
Issue: Menu bar goes back

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3559]
To reproduce:

1. Make the page just a little wider than the menu bar. 
2. Select a tool with a number of options beyond the viewport. (For example, the Move tool)
3. Scroll to the right of the top bar.
4. Select a tool with fewer options. (For example, the Hand tool)
5. Try to open a specific menu in menu bar. 

Another menu is opened because the top bar goes back to left.

I recorded a video.

https://user-images.githubusercontent.com/79258245/125916295-ee159eb6-19c8-4e3c-8cb1-380dbb48ebb4.mp4

My opinion: 
If the top bar would go back, just make it go back when I select the Hand tool instead of when I click on the menu.

**Comment by photopea** [comment]
I fixed it. When you switch tools, or resize a window, the top panel is "snapped" back to the default position.
