### ISSUE TITLE
Confusing message

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#356]
I forgot to confirm when typing text and went into Layer Style dialog.
I tried to change something there and it showed me "Close the current window first." I didn't know what is going. It was wrong and very confusing message it should say "Escape or Confirm the current action (in the top menu)." in this case.

**Comment by photopea** [comment]
I made a big change. The message "Escape or Confirm" is never shown. Instead, the current tool is always confirmed automatically, before proceeding to the requested action.

**Comment by RenNnlesse** [comment]
when i tried to edit a layer it said close current window and i don't know what it meant by that
![image_2021-07-04_202736](https://user-images.githubusercontent.com/85294047/124403740-a4310280-dcec-11eb-9b45-d6d3d0dd4823.png)

**Comment by photopea** [comment]
Hi, how exactly did you edit a layer? I tried many things, but can not make this message appear.
