### ISSUE TITLE
Replace "Speed" in GIF exporting with Frames Per Second

### ISSUE THREAD

**Issue by orangecarnation** [photopea/photopea#3560]
The GIF exporting in photopea is honestly superb, but I could do without the vague "Speed" percentage.  Being able to simply type in what FPS I want it to play in would make things much simpler.

**Comment by photopea** [comment]
In a GIF animation, each frame can be displayed for a different period of time. So there is no "global FPS", e.g. the first half of a GIF can play at 5 FPS, while the second half can play at 20 FPS.

You can enter the time for each frame in a layer name, see this: https://www.photopea.com/learn/animations
