### ISSUE TITLE
Selected photo coudn't be scaled, manipulated or even move

### ISSUE THREAD

**Issue by owenlim225** [photopea/photopea#3561]
Whenever I select the photo, it wouldn't move, can't be scaled or even rotate. There's always a tiny box on the top left edge that whenever I used said tools, the box is the one that moves around. But nothing happened with the photo I selected.
![image](https://user-images.githubusercontent.com/87555304/126023266-0e2f616a-83e1-499c-a639-c6b7c0e4fbc6.png)

**Comment by photopea** [comment]
Hi, I am not able to reproduce it :( Can you describe some steps how to make it happen?

**Comment by photopea** [comment]
I will reopen it once you provide some steps how to reproduce it.
