### ISSUE TITLE
Fix your annoying begger's notification.

### ISSUE THREAD

**Issue by Lexxos** [photopea/photopea#3563]
I get it, but I have disabled all possible plugins including my browser and DNS and still your message persists. How this doesn't violate any browser's terms of use is beyond me because it certainly goes against Google's.

**Comment by photopea** [comment]
Hi, are ads displayed in Photopea in your case? If there are no ads, you (or someone else, who processes each page you visit, e.g. a browser extension) are bocking them.

Try this: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/
