### ISSUE TITLE
Issue: Guides remains red

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3564]
To reproduce:

1. Create a guide.
2. Create a selection and snap it to the guide.
3. Click inside selection to deselect.

The way to fix it:
Create a new selection and move it.
![screenshot_20210717_195536](https://user-images.githubusercontent.com/79258245/126036241-ab15e430-b12d-4b28-9088-37c5577deee4.jpg)

**Comment by photopea** [comment]
I can not reproduce it :( the selection contour is black/white, it is never red.

**Comment by nothingshiru** [comment]
I mean the color of guides but not the color of selection coutour. When moving something attaching on the guides, the guides become red, doesn't it?

**Comment by nothingshiru** [comment]
Well, I tried it again with mouse and found out that this only happen with finger.

**Comment by photopea** [comment]
I still can not reproduce it. I am doing it with a finger. When a selection is snapped to a guide, there is a red line, which disappears after I release my finger.

**Comment by nothingshiru** [comment]
Did you do step3?

Tap inside the selection to deselect.

**Comment by photopea** [comment]
You are right, I am sorry, it is fixed now.
