### ISSUE TITLE
Issue: The value of the guides position is not its real position

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3565]
To Reproduce:

1. Create a document with 2*2 px and double-click on Hand tool to zoom in.
2. Create a guide by dragging from the ruler and release mouse button at 0.55px when dragging it.

The guide is actually located at 1px but in View - Add Guides it is 0.55px.
![Screenshot_20210717_204140](https://user-images.githubusercontent.com/79258245/126037306-0e995c56-b060-43f2-8a27-ee0dfca10a1a.jpg)

**Comment by photopea** [comment]
Fixed, thanks for reporting! :)
