### ISSUE TITLE
Cannot Transform Objects When Rasterised

### ISSUE THREAD

**Issue by krillbill** [photopea/photopea#3566]
![image](https://user-images.githubusercontent.com/54211355/126039159-d6ec083f-d812-419e-b035-f8139affbe92.png)
Whenever I select an area within the smart object, as soon as I try to transform it the cursor is moved onto the blue outlined object and moves that instead. Pressing undo to before the outline appeared does not remove it and there is no layer which has that object in it, I have tried making a new layer and deleting existing ones. Before the triangle on the left was rasterised, transforming it added the blue outline into the shape.

**Comment by photopea** [comment]
I think you created a Work Path.

Go to Window - Paths, and deselect the work path, or delete it.

You can learn more here: https://www.photopea.com/learn/vector-graphics
