### ISSUE TITLE
Google Font - Baloo Da 2

### ISSUE THREAD

**Issue by nasirkhan** [photopea/photopea#3567]
Not all the Google fonts are available in Photopea. There is not much Bengali Language Google font is available now, Baloo Da 2 is a font Google recently published. It would be really helpful if you please add this font. 

https://fonts.google.com/specimen/Baloo+Da+2

**Comment by photopea** [comment]
Hi, we do have the "Baloo" font in Photopea, which has a "Da 2" subfamily. Is that what you need?

![image (4)](https://user-images.githubusercontent.com/15955558/126059214-482a7333-e486-4f5a-8328-ebf069d19124.png)

**Comment by nasirkhan** [comment]
Thanks for the reply. 

I know Baloo font is there, and Baloo Da 2 is a sub family. But the Baloo font do not have all the character sets of other language. Like Baloo Da 2 has both Bengali and English block character, whereas Baloo do not have the Bengali characters. 

Here I have attached the related screenshot. I added a text with HindSiliguri as well to make you understand that other Bengali fonts is working fine. 

**Photopea**
![New Project(3)](https://user-images.githubusercontent.com/396987/126060650-e478b71f-8d96-480a-ab2f-712df3975d6f.jpg)

**Google Fonts**
![Screenshot 2021-07-18 at 14-15-59 Google Fonts](https://user-images.githubusercontent.com/396987/126060658-8d5808fe-3dbf-4ebb-9946-3aabe85610c5.png)

Google Fonts Preview: https://fonts.google.com/?preview.text=%E0%A6%AC%E0%A6%BE%E0%A6%82%E0%A6%B2%E0%A6%BE%E0%A6%A6%E0%A7%87%E0%A6%B6&preview.text_type=custom&subset=bengali

**Comment by nasirkhan** [comment]
Thank you, I was not sure that the Sub families are available in that menu. Thanks. 

Is it possible to add a filter to get fonts of some specific language. There is a such feature in Google fonts: https://fonts.google.com/?preview.text=%E0%A6%AC%E0%A6%BE%E0%A6%82%E0%A6%B2%E0%A6%BE%E0%A6%A6%E0%A7%87%E0%A6%B6&preview.text_type=custom&subset=bengali

**Comment by photopea** [comment]
Font filters are above the font menu. Do you want us to add a Bengali font filter?
![image (5)](https://user-images.githubusercontent.com/15955558/126077386-a84ce481-f75b-43eb-974b-e9c0e7069b44.png)
