### ISSUE TITLE
Ad Block

### ISSUE THREAD

**Issue by pgaspars** [photopea/photopea#3568]
I added the exception rules and the program keeps returning the message about the subject.

**Comment by JuMiGa** [comment]
Second this, I added the exception and the program keeps interrupting.

**Comment by JuMiGa** [comment]
And for the record, I am seeing ads but the message still shows. It seems you are only checking for the presence of plugins, not whether your ads are being displayed.

**Comment by JuMiGa** [comment]
![image](https://user-images.githubusercontent.com/20935256/126051966-61a3877c-8441-48e5-ad55-cd972e322f37.png)
Here are the ads I'm getting and the window is still being shown, constantly interrupting.

**Comment by photopea** [comment]
There is no way for a website to know, if you are using any extensions. We only detect if ads were loaded properly, or something interfered with the process. If we can not load ads, we might show our own "buy photopea" banner.

You are saying, that your extension is still blocking ads, even after you disabled it. It is clearly a bug in your extension, you should report it to a person who created it. Or disable that extension, or find a better ad blocker.

This might help you: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by photopea** [comment]
As a proof, disable all browser extensions and you will see, that Photopea won't show you a message. So your extension clearly interferes with Photopea in some way (otherwise, Photopea would not be able to detect it).

**Comment by JuMiGa** [comment]
This screenshot is from disabling all extensions, next time think before you close your tickets.

**Comment by photopea** [comment]
@JuMiGa Are you using Photopea at www.Photopea.com ?

**Comment by JuMiGa** [comment]
I was not, it was through www.freeonlinephotoshop.com/photopea/

The link provided seems more stable than the old link.

**Comment by photopea** [comment]
I opened Photopea at http://www.freeonlinephotoshop.com/photopea/ , but I don't see any message about the ad block :(  I do not have any adblocks.

Are you using a Brave or Firefox browser with some "security" settings, which block ads as a result?

**Comment by pgaspars** [comment]
I'm using your webapp... so I shouldn't use it anymore?

Att,
Gaspar

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: ***@***.***>
Enviado:domingo, 18 de julho de 2021 05:25
Para: ***@***.***>
Cc:Pedro ***@***.***>; ***@***.***>
Assunto: Re: [photopea/photopea] Ad Block (#3568)


I was not, it was through www.freeonlinephotoshop.com/photopea/<http://www.freeonlinephotoshop.com/photopea/>

The link provided seems more stable than the old link.

**Comment by photopea** [comment]
@pgaspars I think there is a bug in your ad blocker. You should report it to the creator of your ad blocker. 

Websites should not be able to find out any information about a visitor (e.g. what extensions they are using). So if Photopea shows a message in your case, but does not show a message to other people, it is clear that your browser does something differently.
