### ISSUE TITLE
FIX YOUR ADS!!

### ISSUE THREAD

**Issue by Lexxos** [photopea/photopea#3569]
The response I got from the team about their begging notification.

_________________________________________________

Hi, are ads displayed in Photopea in your case? If there are no ads, you (or someone else, who processes each page you visit, e.g. a browser extension) are bocking them.

Try this: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

_Originally posted by @photopea in https://github.com/photopea/photopea/issues/3563#issuecomment-881884786_

__________________________________________

AS I HAVE STATED: I disabled all third party plugins, and included your website from being blocked by the browser. Ads still show. Message still persists which is AGAINST Google's terms of service of which I will be reporting your site for spam and misuse of notifications for having such a lazy response and closure of the ticket without evaluating it.

**Comment by photopea** [comment]
Sorry, we do not provide any service to people, who refuse to pay or to see ads.

What is a "third party plugin"? Do you see any message if you open Photopea in the Incognito mode?

**Comment by JuMiGa** [comment]
Photopea doesn't even load in incognito, what kind of question is this? All plugins are disabled as well

**Comment by photopea** [comment]
@JuMiGa what browser do you use? can you update it? Photopea.com works fine for me in Incognito.

**Comment by stell** [comment]
I too have no problem looking at ads, but whatever i do ads are not displayed and a nonstop Alert makes using photopea impossible. No adblocking active, accepted all you cookies and so on. This messed up behavior goes since around 3 weeks.

**Comment by photopea** [comment]
@stell Have you tried Photopea in an incognito window (where all browser extensions are disabled)?

**Comment by stell** [comment]
@photopea I created an windows App Link for photopea. Adding -incognito to the call seams not to work.

**Comment by photopea** [comment]
Do you have any extensions enabled in your browser? Have you tried to turn them all off?
