### ISSUE TITLE
Type Tool behaviour

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#357]
I noticed using Type Tool is sometimes uncomfortable because of two things:
1) When I click on Type Tool and before typing any text I select some font and/or size. After I click to start typing text it is always reset to default DejaVu Sans 24 pt. Is this bug or feature? I think it should use and remember my preselected font/font size  and other character settings.
2) When I have Text layer selected and I choose another font or font size (in the top bar or Character window) I would expect to change entire text to font/font size I just selected. But in Photopea it seems I must enter the typing mode and select all text first and then do my changes and then unselect it to see how it looks without selection. This is very uncomfortable.

**Comment by photopea** [comment]
Ok, the "Photoshop-like workflow" was implemented. I should have done it a long time ago, but I was a little lazy :(

**Comment by hxim** [comment]
@photopea 
I like it it works very well now.
Only thing I don't like is when I use multiple colors or font sizes in one text layer. When I go away from this layer and come back with Type Tool color is reset to black and size is reset to 1pt in this case.
I think it should keep previous color/size or maybe is also possible take it from first letter of text.

**Comment by photopea** [comment]
In this situation, the values in the top menu should correspond to the style of the whole layer, not just the first letter. Photoshop has an "empty font", "empty color", "empty size" etc. for this situation. We don't have these "empty" values implemented in our UI (so you see a black color, size 1 etc.).

You should enter the layer to edit each part of the text separately. Or you can still change properties without entering, they would be applied to the whole text.

**Comment by hxim** [comment]
@photopea
OK. But you seem to handle "empty font" differently from "empty color" and "empty size" here.
With "empty font" it seems you keep last selected font (and not replace with default font) there but
with "empty color" and "empty size" you replace with default "black" and "1pt". I don't know what was your intention but I would prefer behaviour like the one with "empty font" because of this reason:
When I have Type Tool selected and I click on some layers it will sometimes suddenly reset "font size" to "1pt". You then start typing new text layer and it is now set to only 1pt which is extremely small so you can't even see what you are typing... I think Photoshop also somehow remembers last "font size" and don't let you type with "1pt" size font in new layer.

**Comment by photopea** [comment]
Photopea shows 1px  and a black color, but these values mean "empty".  That is how "empty" looks like now in Photopea. It is just the visual look, not the meaning.

If you start a new layer after leaving the layer with "1px" (which means empty), it will have the size 24px. I.e. everything should work exactly like in Photoshop.

**Comment by hxim** [comment]
Yes I understand. "empty" values needs to be implemented in UI. It is very confusing now...

**Comment by hxim** [comment]
One more thing. When I use Type Tool and I click first to start writing and before writing anything I change to different font/size/color and after that I write my text it thinks it has multiple fonts/sizes/colors and shows "empty" values it should recognize that entire text is one font/size/color i think.

**Comment by photopea** [comment]
Hi, so I fixed all the mentioned problems. An empty value for the font size is 20 instead of 1.
