### ISSUE TITLE
'github' login page's error

### ISSUE THREAD

**Issue by lilalalala** [photopea/photopea#3573]
![企业微信截图_16266644778073](https://user-images.githubusercontent.com/25168736/126098266-350a3e53-70be-4b92-bf43-13736f1b9ac0.png)

**Comment by lilalalala** [comment]
var_dump()

**Comment by photopea** [comment]
Hi, could you set a name and an email address in your GitHub settings? That is the two values that we need. You can set a fake name, it does not matter.
