### ISSUE TITLE
Already Paid for 90 days, but Pop Ups to turn off blockers keep come out. What to do ?  

### ISSUE THREAD

**Issue by berguna99** [photopea/photopea#3574]

**Comment by photopea** [comment]
Hi, have you tried to reload a website? Or close and open it again?

**Comment by berguna99** [comment]
Ok.. I've tried your suggestion... need to use for a while to know. Thanks for suggestion.

**Comment by photopea** [comment]
Photopea detects the ad blocking only at the beginning. Sorry for not being clear. Let me know if there is anything else I can help you with.
