### ISSUE TITLE
Issue: Ruler tool

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3575]
1. Clear button only clear the ruler in canvas but not the values in text box. 
2. Values in text box are editable but will have no practical effect. I don't think editable text box is needed. Just show the values. 
3. Changed unit of Ruler in Edit - Preferences, values of ruler tool are still pixels. 
4. Angle value doesn't have the ° sign.

**Comment by photopea** [comment]
Fixed :)
