### ISSUE TITLE
Part of the value is obscured by finger. 

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3576]
When creating a selection or dragging a guide with finger, part of the value is obscured. 
![IMG_20210719_173000](https://user-images.githubusercontent.com/79258245/126138727-6c3592bf-508f-44bd-b026-55ddce1f767b.jpg)
It might be better to make it right-align when using finger. I'm not very sure the problem can be solved this way though.

**Comment by photopea** [comment]
Fixed, thanks for reporting! :)
