### ISSUE TITLE
Feature request: add a "Reduce Noise" at the "Noise" filter, like Photoshop

### ISSUE THREAD

**Issue by ThatMario** [photopea/photopea#3583]
Hi there!

I love using Photopea, but I've notice the app is lacking some major features, and espicially one : the "**Reduce Noise**" in the _Noise filter_. Reducing noise on this website is barely impossible, and doing with the "Median" filter's not giving the same results than the real button. PLS add this necessary feature.

**Comment by photopea** [comment]
Hi, I implemented the Reduce Noise filter in Filter - Noise - Reduce Noise :)

![noise](https://user-images.githubusercontent.com/15955558/126625872-96687ad9-29b2-4873-8604-78d53c268792.jpg)

**Comment by ThatMario** [comment]
Thanks you very much! :)
