### ISSUE TITLE
Opera GX not saving Photopea psd files

### ISSUE THREAD

**Issue by ButWhyZac** [photopea/photopea#3584]
This is a **notice** that Opera GX doesn't save psd files from photopea. I have no idea why this could be happening but I stumbled upon it anyway. I don't know if this is just for me or it's for everyone using opera GX. 

This is an issue that I found during making a thumbnail, when I chose to save my project to psd, the file would save as 0kb. And when I would try to open the file an error will come up saying unknown file format (**as seen in the picture below**).
![image_2021-07-20_115636](https://user-images.githubusercontent.com/87681327/126250519-0e8696f3-34c5-4b50-8efc-8d7853f6905e.png)
    
Again, I don't know if this is just for me but for anyone that has stumbled onto this same issue; use chrome when going to create something on photopea, it seems to work fine on chrome.  

_Also, may we have a moment of silence for those who lost their work this way..._ 
Anyway, have a good day!

**Comment by photopea** [comment]
We use the "showSaveFilePicker" API to save files in browsers, which support it. It should be supported by Chrome, Edge, and Opera: https://caniuse.com/?search=showSaveFilePicker 

When it is done in Opera, opera creates an empty file :(  Maybe @mwicat @r4fek @psliwka  could tell us why it happens?

So far, I can only recommend you to switch to a better browser.
