### ISSUE TITLE
Ad not appearing and spam problem

### ISSUE THREAD

**Issue by Setsugo** [photopea/photopea#3585]
so I keep getting spammed by "please turn off your adblocker" even though I already turned off my adblock. Yet the ads doesn't appear and I still get spammed by the turn-off-adblocker thing. I tried turning off my entire extensions and the result is still the same. Help please

**Comment by Setsugo** [comment]
Nvm I just found some tactic to by pass it

**Comment by photopea** [comment]
have you reloaded Photopea after disabling your ad blocker?
