### ISSUE TITLE
Free transform issue

### ISSUE THREAD

**Issue by owenlim225** [photopea/photopea#3586]
Whenever I have this problem, my project screw up. I don't know how this always happen but whenever I tried to transform an image, there's always a change this would happen. The image could be moved but couldn't be used any transform features. Whenever this happen, there would be a cube in the top left edge that when I tried to transform the image (scale it, rotate it, warp it, etc) will the one that moved. Please help me.

![image](https://user-images.githubusercontent.com/87555304/126413550-af3e1e80-fbd0-43a5-8820-b5b403f33dff.png)

**Comment by photopea** [comment]
Could you describe how can I make it happen? Can you share your PSD with me?

**Comment by photopea** [comment]
I have to close it because of lack of details.
