### ISSUE TITLE
Feature request: viewer/editor for embedded IPTC photo metadata

### ISSUE THREAD

**Issue by bquinn** [photopea/photopea#3587]
Photopea looks great! Congratulations on an excellent product.

Have you considered supporting IPTC embedded metadata? Photoshop and other professional photo editing tools have very good support for IPTC properties as well as Exif ones.

It seems that the current version of Photopea supports Exif fields (through the file -> file info menu) but no IPTC fields (in either the older IIM or newer XMP formats) as far as I can tell.

If you would like some help or advice in supporting these fields, please let me know.

**Comment by photopea** [comment]
Photopea should already support the IPTC. 

We have just one internal format for metadata. When you open a file, we combine metadata from EXIF, XMP and IPTC into one metadata. When you export e.g. a JPG, or metadata is stored as EXIF, XMP and IPTC. Have you tried it?

**Comment by bquinn** [comment]
When I open the [IPTC Reference image](http://iptc.org/std/photometadata/examples/IPTC-PhotometadataRef-Std2019.1.jpg) and go to "File -> File Info" I see fields shown in the attached screenshot. I should see many more fields than this. Should I be looking somewhere else?
<img width="1268" alt="Screenshot 2021-07-21 at 11 09 51" src="https://user-images.githubusercontent.com/309976/126454793-d6a9a366-bdbf-41f9-88ad-a52e96ee03c5.png">

**Comment by photopea** [comment]
I think I have fixed it. All IPTC tags from your file should be detected by Photopea now :)

**Comment by bquinn** [comment]
Thanks very much! It's a big improvement -- but there are still many fields that are not supported.

It looks like you support the IIM fields (the old format that pre-dates XMP) but not the XMP versions of IPTC fields that are supported by Photoshop, Fotoware, Photo Mechanic etc. 

[This page](https://getpmd.iptc.org/getpmd/html/stds/ipmd) will show you all of the IPTC metadata that is embedded in the test image, in both IIM and XMP format. It's a bit trickier because some of the fields have structures, they're not simple key/value pairs.

Some of these fields are required for [Google's Licensable Images feature](https://developers.google.com/search/docs/data-types/image-license-metadata), for example, so it would be awesome of Photopea could support them.

Also it would be great if we could add IPTC fields (in IIM or XMP) to images. Right now the only fields that can be added from the drop-down appear to be Exif properties.

[The full standard specification](http://www.iptc.org/std/photometadata/specification/IPTC-PhotoMetadata) is a lot to read, so [we recently created a machine-readable file that has all the technical details necessary to fully support IPTC fields in both IIM and XMP formats](https://www.iptc.org/news/iptc-photo-metadata-techreference-helping-software-developers-to-implement-the-iptc-photo-metadata-standard/). That might help with your implementation work.

Thanks again for your help in supporting IPTC metadata in Photopea!

**Comment by photopea** [comment]
By the way, what about supporting XMP metadata only? Now, Photopea can partially recognize XMP, EXIF and IPTC. But would it be ok, if we worked only with XMP metadata?

XMP was designed to replace all previous metadata standards from the past.

**Comment by bquinn** [comment]
That's a long story... unfortunately the situation is that the world is full of photos which use all three formats. We support IPTC-IIM for backwards compatibility and many major providers (Reuters, Getty Images) still sell thousands of photos using IPTC-IIM for metadata.

So while you could support only XMP if you want, you would probably end up with some unhappy users who can't access or edit their metadata.

Regarding Exif, it is still the only format supported by most cameras and many professional photographers rely on a workflow based on Exif on the camera and IPTC (IIM or XMP) for editing and publishing.

**Comment by photopea** [comment]
Currently, the strategy of Photopea is to extract both XMP, EXIF and IPTC metadata, and combine them all into one XMP metadata. When exporting, we deduce the EXIF and IPTC metadata, and attach all XMP, EXIF and IPTC to a file. 

Your file does not contain any other IPTC metadata, but it contains following XMP metadata: https://pastebin.com/ycEiSv05 . Photopea detects (and lets you modify) only certain XMP tags, ignoring others. Which other XMP tags would you like to be able to work with? Is there an image editor, which works with metadata the way you want, so that I can see what you need?

**Comment by bquinn** [comment]
Thanks for continuing to look into this.

One thing to clear up: what many people call "IPTC metadata" is actually what we call "IPTC-IIM metadata", ie the old [Information Interchange Model](https://iptc.org/standards/iim/). But IPTC Photo Metadata standard doesn't just define fields using the IPTC-IIM format, it also defines many fields using the XMP format. I know it's a bit confusing and a lot of people mix up the names, but we always draw a distinction between the field definitions (the IPTC Photo Metadata Standard) and then the ways to express those in embedded metadata (in either IPTC-IIM or XMP format). Hope that makes things a bit clearer.

The IPTC Standard defines terms which for historical reasons fall across all of these namespaces in XMP format:
* `xmlns:Iptc4xmpCore='http://iptc.org/std/Iptc4xmpCore/1.0/xmlns/'`
* `xmlns:Iptc4xmpExt='http://iptc.org/std/Iptc4xmpExt/2008-02-29/'`
* `xmlns:plus='http://ns.useplus.org/ldf/xmp/1.0/'`
* `xmlns:dc='http://purl.org/dc/elements/1.1/'`
* `xmlns:photoshop='http://ns.adobe.com/photoshop/1.0/'`
* `xmlns:xmp='http://ns.adobe.com/xap/1.0/'`
* `xmlns:xmpRights='http://ns.adobe.com/xap/1.0/rights/'`

You can see these in the XMPid field in the [Photo Metadata TechReference file](https://iptc.org/std/photometadata/specification/iptc-pmd-techreference_2019.1.yml) ([JSON version](https://iptc.org/std/photometadata/specification/iptc-pmd-techreference_2019.1.json))

[Here's a list of the image editors that supports IPTC Photo Metadata](https://iptc.org/standards/photo-metadata/software-support/). Probably the best support is in Photoshop, Photo Mechanic and Photo Supreme.

Of course, we will be happy to add Photopea to the list!

**Comment by photopea** [comment]
In Photoshop, do you mean File - File Info? 

In that case, I see the metadata categories on the left, which you can choose, and view metadata from that category. For each category, there is a specific set of parameters, which can be modified. The "total" metadata can be modified only as raw text (XML).

Do you think it is the best way to provide the metadata access? Now, Photopea displays only the non-empty metadata parameters, and they are all in one list instead of multiple categories.

I think we should focus more on the practice. What software or service requires metadata, which can not be added to a file inside Photopea now?
