### ISSUE TITLE
New feature - Exporting 'Layer Comps' to files

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3588]
Hi, it would be nice to have that functionality. 
I use layer comps to show many states (active, hover, dropped down option etc.) and moving cursor on page project.

It would be very handy if Photopea could export all my Layer Comps as a files ( just PNG - or with window with options like in exporting layers) to ZIP for example.

**Comment by photopea** [comment]
Hi, do you think you could write a Photoshop script, which does that in Photoshop? Then, we could make the script work in Photopea.

**Comment by MichalSZZ** [comment]
I'm afraid that I can't do it because I don't have so much programming skils.
In Photoshop it is an easy option  in File > Export > Layer Comps To Files
Look here from 6:15 https://youtu.be/kcYEHQql67Y

**Comment by photopea** [comment]
I have added a button to the bottom of the Layer Comps panel :)

It simply runs a script, which exports all layer comps as PNG images.
