### ISSUE TITLE
Requesting for desktop app

### ISSUE THREAD

**Issue by nikhil-toobler** [photopea/photopea#359]
Hi Photopea,

The product is really awesome and very useful to all who don't have photoshop/sketch app. 

But I'm really struggling to import large size sketch file [200mb or like that] into the app or couldn't save-as sketch file as PSD format. I got an error message which like "Insufficient RAM space" or page get stopped even I'm running on 8GB RAM. This may be the deficiency of using the web app. 

Hope this can be solve if photopea provides a desktop app for windows/mac.

Thanks and looking forward to you :)

Nik

**Comment by photopea** [comment]
Hi Nikhil,

we are aware of this problem. It is caused by the structure of our program. It is not caused by any limitation of web apps. If we made a desktop app, it would work absolutely the same.

We would like to improve this in the future, so you can open e.g. 4 GB PSD file.

**Comment by nikhil-toobler** [comment]
Oh! This is awful. Please lemme know once it's done. Thanks for the services :)
