### ISSUE TITLE
Feature suggestion - Import plugin for personal use

### ISSUE THREAD

**Issue by yikuansun** [photopea/photopea#3590]
Hi,

Could you make a simple dialog box where people could upload the JSON file for a plugin just for their own usage? This could perhaps be opened through `Window -> Load 3rd Party Plugin` or something similar. I have worked a lot on my lens flare plugin and would like to be able to distribute it, even if it is not available by default. This would also make testing easier for developers. Also, I feel like some people might not realize that they can develop plugins (which is true in a way), and seeing this option will inform them.

Thank you!

**Comment by photopea** [comment]
Just tell me the code of your plugin and I will add it into Window - More - ...

**Comment by yikuansun** [comment]
That is fine.
I was thinking that since the plugin system is mostly just iframe interaction, maybe I could make a plugin that could be used to import plugin data and open the specified plugin? This would be useful for the reasons I mentioned earlier, as well as saving your time in adding every plugin yourself.

**Comment by photopea** [comment]
If you really need certain plugins in your Photopea, you can compose a specific URL and save it as a bookmark in your browser.

Once there exist more plugins for Photopea, I will create a plugin gallery.
