### ISSUE TITLE
Broken adblocker detector and corrupting psd files.

### ISSUE THREAD

**Issue by firebranches** [photopea/photopea#3591]
The notifications keep ongoing every 5second-ish saying that I had an ad blocker turned on. I even tried to reload pages and went to different browsers and does not work either. Even on incognito mode.
And when I am saving a project. It either rollbacks to the first one or corrupts the PSD file. It's sad and infuriating to see my recent hard works are getting corrupted.

**Comment by photopea** [comment]
Hi, do you see ads in Photopea? If not, do you know what is blocking them?

Corrupted PSD: could you describe any steps, which I can perform to get a corrupted PSD? Make sure these steps always create a corrupted PSD on your computer.

**Comment by firebranches** [comment]
You make a PSD file and then edit a bit. Then try to click save as PSD onto the same file you saved. And when the Adblock detector thing popped up, click save and click 'ok' it happens in the original opera browser. But if you do it on chrome, you click 'save'.

And no, I do not see any ads and I do not know what's blocking them.

**Comment by kksudo** [comment]
ADS +1 issue

**Comment by photopea** [comment]
There is a bug in Opera, you can not save PSD files in Photopea in Opera, see https://twitter.com/tomayac/status/1418483029824131074

**Comment by kksudo** [comment]
In my case - it's :
Google Chrome:  Version 92.0.4515.107 (Official Build) (64-bit)
OS: 5.8.0-63-generic #71~20.04.1-Ubuntu SMP Thu Jul 15 17:46:08 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux


All AdBlock extensions are disabled ...

**Comment by photopea** [comment]
@kksudo You can not see ads in Photopea and you disabled all extensions? Do you have any antivirus or a firewall, which could be blocking some domains?

**Comment by kksudo** [comment]
@photopea 
Sorry, unfortunately  it was the AdBlock :)) 

I  added the https://www.photopea.com to the exceptions sites, but ads not showed, when I disabled completely in the chrome settings these extensions, I got ads )

An issue can be closed

**Comment by photopea** [comment]
There was never any issue related to ad block detection in Photopea.

All the issues, reported here in the last month, are about me convincing people, that they are really using an adblock, even if they think they don't :)
