### ISSUE TITLE
Screenshots are messed up

### ISSUE THREAD

**Issue by AirGEL** [photopea/photopea#3592]
When I try to screenshot a project all the image it captures is black

**Comment by photopea** [comment]
Hi, do you mean pressing PrintScreen on your keyboard, and then, pasting it somewhere? Can you take a screenshot of other websites, e.g. www.Google.com ?

**Comment by AirGEL** [comment]
no, I do not mean printscreen, I'm talking about using Firefox's scheenshot feature, other websites work fine, photopea works except for where the project is

example:
![image](https://user-images.githubusercontent.com/73725883/126573915-cdf0e961-4893-4377-8cf1-d84e58829ca6.png)

**Comment by photopea** [comment]
I think it is a bug in the screenshot feature in Firefox. Can you take a screenshot of a game e.g. Krunker.io?

**Comment by AirGEL** [comment]
yeah probably is a firefox issue since a game is doing the same thing
