### ISSUE TITLE
Paid $40 for subscription and still getting the popup

### ISSUE THREAD

**Issue by PatriotCafe** [photopea/photopea#3593]
Hi, I purchased your 40 subscription and I am still getting the "get a membership pop up " every 30 sec.

**Comment by photopea** [comment]
Can you close Photopea and open it again?

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by PatriotCafe** [comment]
What details do you need?

On Aug 3, 2021, at 1:12 PM, Photopea ***@***.***> wrote:

﻿

I have to close it because of lack of details :(

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_photopea_photopea_issues_3593-23issuecomment-2D892057041&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=pDAKjUsr6jkmc4rBqjQ8yCWX5p900gvyqDyZ-_YHRdY&m=O0SVNzafhmrFSaQikQTnDV9CgK4fHW9ODBBXsRCH0fA&s=F54mi25r8tr3JD81F4CC6DCZUpGi9-onC1X38KbCnq4&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AU5YL5RNTGUNECNPC6UJVN3T3AWP5ANCNFSM5AY42HEQ&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=pDAKjUsr6jkmc4rBqjQ8yCWX5p900gvyqDyZ-_YHRdY&m=O0SVNzafhmrFSaQikQTnDV9CgK4fHW9ODBBXsRCH0fA&s=fsHJgWZndBCUrr5eUY6nPDiXDxaN9p__ZmHG3BL0rQA&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=pDAKjUsr6jkmc4rBqjQ8yCWX5p900gvyqDyZ-_YHRdY&m=O0SVNzafhmrFSaQikQTnDV9CgK4fHW9ODBBXsRCH0fA&s=kgS9_tQbAZ8wUxZ5Pg0nY0XErbwCdL3mZQExd1t_92U&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26utm-5Fcampaign-3Dnotification-2Demail&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=pDAKjUsr6jkmc4rBqjQ8yCWX5p900gvyqDyZ-_YHRdY&m=O0SVNzafhmrFSaQikQTnDV9CgK4fHW9ODBBXsRCH0fA&s=apBJVnXTSwEQzwyOkiRwyP2kbBUsLzfRWm3WNCG8k38&e=>.

**Comment by photopea** [comment]
Did you try to close Photopea and open it again? Is Premium working well now? The "Account" button should be green.

**Comment by PatriotCafe** [comment]
Its Yellow, and the email connected to this is ***@***.******@***.***>, I might have uses ***@***.******@***.***> when I paid the $40.


Sincerely,
Marzena Jonak,



[cid:C7DC2A4E-1AD3-4A84-98F9-E49590D4C313]

￼Where Patriots shop for CBD!

***@***.******@***.***>
Direct 847.567.4911

www.thepatriotcafe.com

**Comment by photopea** [comment]
Can you log out and log in "another way"? Maybe you logged in with Facebook before, and now, you logged in with Google, and you have a different email address at each service, so Photopea can not know, that it is still you. Let me know if it helped.

It is all described here: https://www.photopea.com/tuts/premium-account-does-not-work/
