### ISSUE TITLE
Cannot create Newline / Line break in Point Text

### ISSUE THREAD

**Issue by NnjaChurch** [photopea/photopea#3594]
For some reason I am having a lot of inconsistencies with the Type tool. I am trying to write things on multiple lines, but I cannot seem to get line breaks to work. It only seems to work if I copy a Type Layer from a previously working one and then edit it there.
Pressing Enter does not create the line break, and it also does not work in the Paragraph Mode either.

**Comment by photopea** [comment]
Could you try these steps and let me know if it helped? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by NnjaChurch** [comment]
Update: I ran Photopea in Incognito mode, and I believe that the bug seems to be caused by the popup that runs when ads are blocked. As soon as the popup occurs, I can no longer create line breaks. (Note that even though I have adblock disabled for photopea, ads still do not load unless I turn adblock on and back off).
As a temporary fix I will just use Photopea in Incognito mode for now (until the adblock issue I've been seeing from other users is resolved)

**Comment by NnjaChurch** [comment]
Update 2: This is just an update on both the AdBlock and the Newline situations. I closed Photopea and cleared all the cookies related to the website, then made sure that adblock was turned off for the site. Now I automatically load ads on the first try, and the newline also seems to work.
It is possible that if cookies are created with adblock enabled, it breaks entirely? I'm not exactly sure, but it seems to work well now.

**Comment by photopea** [comment]
I think your browser extension was breaking Photopea. Browser extensions can modify any website in any way they want.

We are not resolving any "adblock issue" at the moment. If you "disable adblock for Photopea", but you still can not see ads, the bug is in your adblock, not in Photopea.
