### ISSUE TITLE
Fenêtre de publicité toujours active

### ISSUE THREAD

**Issue by MatDuf6** [photopea/photopea#3595]
Bonjour,
Comme demandé, j'ai changé mes préférences publicitaires pour que vous puissiez bénéficier des revenus. J'ai également désactivé le bloqueur de pubs. Cependant, la fenêtre continue de s'afficher toutes les 30 secondes malgré le rafraichissement de la page...

**Comment by photopea** [comment]
Hi, do you see ads in Photopea or not? Have you tried to reload the webpate?

Try this: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
