### ISSUE TITLE
Ad Blocker warning issue

### ISSUE THREAD

**Issue by herdingfish** [photopea/photopea#3596]
I have fully disabled AD Block for this site 

![New Project (12)](https://user-images.githubusercontent.com/87812248/126636013-f2132039-d13f-48ad-89f1-869177c16185.png)

but this message appears every few seconds rendering the site unusable:

'We use advertisement to get money for our development. Your device seems to be blocking ads. Please, let us show you ads, or buy a Premium account (Account - Log In - Buy). If you just unblocked ads, reload Photopea.  5'

what can i do?

**Comment by photopea** [comment]
I wrote this tutorial for you: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by photopea** [comment]
I think it has been fixed.
