### ISSUE TITLE
Poligonal Live Shape with round corners made in PS - can't transform in Photopea

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3597]
Here you are a ZIP file with sample corupted PSD
[live-poligonal-shape-PS.zip](https://github.com/photopea/photopea/files/6862239/live-poligonal-shape-PS.zip)

**Comment by MichalSZZ** [comment]
I think it is related with https://github.com/photopea/photopea/issues/3539

in new shape properties panel you can change number of sides in polygonal tool and it corner radius

**Comment by photopea** [comment]
The polygon in Photoshop is so weird.

There is some width and height of a polygon live shape. If you change the corner radius, the width and the height changes, too!

It is not clear, what width and height to enter, to make all sides the same length (nice symmetric circular shape). If Width=Height, it is usually stretched vertically.

**Comment by photopea** [comment]
Also, if you have a rotated rectangle, and you change the corner radius, the X and Y change, too (as they are the the X and Y of a top left corner of a bounding box of a shape).

**Comment by MichalSZZ** [comment]
It is probably associated with the new ability to rotating the rectangles with a round corners without losing a live shape feature?

**Comment by photopea** [comment]
Fixed :)

**Comment by MichalSZZ** [comment]
Thanks a lot!

And yes - it is so weird (in Photoshop too). After rotation and changing the number of sides, polygonal shape has no longer identical angles for all corners. It looks skew
