### ISSUE TITLE
Cannot open specific files

### ISSUE THREAD

**Issue by A-spectz** [photopea/photopea#3599]
When opening (large) files they tend to say error, and then I'm unable to open them. Is there a reason for this. If you want me to attach the file, reply that back to me.

**Comment by photopea** [comment]
Hi, how large are your files? Are they PSD, JPG, or other files? how much RAM do you have?

**Comment by A-spectz** [comment]
They are like 400mb files and i have 4gb of ram, i know its little.

**Comment by photopea** [comment]
I am afraid 4 GB of RAM is not enough for your 400 MB file :(
