### ISSUE TITLE
Cannot copy image from Google

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3600]
This have happened a couple of weeks ago.

I might believe is google, but other sites receive the image as always, so i though that maybe was Photopea.

I cannot go to a picture, select copy image and then Ctrl+V on Photopea.

It says invalid format.

**Comment by photopea** [comment]
By "google", you mean google image search? I just tried it and I can copy and paste images this way.

Does it happen in a web browser with all extensions disabled?

**Comment by avagp** [comment]
mmm yes.
let me show you

**Comment by avagp** [comment]
[Screen recording 2021-07-23 01.33.03.zip](https://github.com/photopea/photopea/files/6866753/Screen.recording.2021-07-23.01.33.03.zip)

In other sites like github, gmail, etc all method works

**Comment by photopea** [comment]
I searched for "cat images" on google Image search, and copied the same image as you did. I still could not reproduce it :( the image was pasted correctly in Photopea. 

My only explanation is, that google image search works differently in each country. 

I think in your country, copying an image copies the image URL as a text. So I modified the pasting a bit, does it work now?

**Comment by photopea** [comment]
Is it possible, that your stand-alone Photopea is running in Safari or Firefox? Have you tried to open Photopea as a website next to google image search?

**Comment by avagp** [comment]
Now it works.  :)

thanks

**Comment by burnsboyamazing** [comment]
It fixed issues copying the image from Google.
[Screen recording 2024-02-14 21.01.26.webm](https://github.com/photopea/photopea/assets/154830140/3e7be074-0f0f-448a-9991-42c82d974a26)
![Screenshot 2024-02-14 21 02 14](https://github.com/photopea/photopea/assets/154830140/e3aec121-a87f-4ff0-9aff-84645028bea2)
