### ISSUE TITLE
Нельзя добавить новые кисти. 

### ISSUE THREAD

**Issue by redmin22882** [photopea/photopea#3603]
Извините но почему я не могу загрузить кисти? Так как скачал несколько наборов кистей но ни один не работает. 

Это не на сайте а в вашем приложение. 

Надеюсь увидите

**Comment by photopea** [comment]
Could you share your ABR files with us?

**Comment by redmin22882** [comment]
> Не могли бы вы поделиться с нами своими файлами ABR?

Хорошо но пожалуйста покажите как тут отправить файлы?

**Comment by photopea** [comment]
Please, send it to support@photopea.com

**Comment by redmin22882** [comment]
Извините пожалуйста но я не могу зарегистрироваться. Пишет много ошибок. Может есть другой вариант? Пожалуйста

**Comment by kksudo** [comment]
@redmin22882 Не нужно регистрироваться, достаточно отправить на указанную почту файлы.

**Comment by redmin22882** [comment]
> @ redmin22882 Не нужно регистрироваться, достаточно отправить на указанную почту файлы.

![Screenshot_20210724-191555](https://user-images.githubusercontent.com/74855608/126871233-b263e839-700f-450f-a861-e70da7f429ee.png)

Да хоть и глупый но я серьезно пытаюсь

**Comment by redmin22882** [comment]
Я хочу отправить но вот что вылазит (

**Comment by kksudo** [comment]
@redmin22882 
Необязательно кликать на адрес почты.
1. Можно просто скопировать это адрес `support@photopea.com` почты в буфер телефона
2. Зайти в любой почтовый клиент (gmail например), который есть у вас на телефоне
3. В поле кому вставить из буфера адрес
4. Прикрепить нужные файлы и отправить ......

**Comment by redmin22882** [comment]
Спасибо огромное уже всё получилось) очень вам благодарен)

**Comment by kksudo** [comment]
@redmin22882 
P.S.: На этом ресурсе (github.com) обычно общаются на английском, чтобы информация была доступна максимальному кол-ву людей из разных стран.

**Comment by redmin22882** [comment]
Эх хорошо. Я просто тут не часто сижу и поэтому на русском. В любом случае я вас услышал и буду пользоваться переводчиком так как очень плохо знаю английский. 

anyway I hope it will be better this way

**Comment by photopea** [comment]
I was able to load your brushes into Photopea and to paint with them.

I just see, that you mentioned an app. What app are you talking about? We do not have any app. We only have a website www.Photopea.com . 

![image](https://user-images.githubusercontent.com/15955558/126894463-6f9cddb2-a53c-475e-8faa-64b1550cd867.png)

**Comment by redmin22882** [comment]
> Мне удалось загрузить ваши кисти в Photopea и рисовать ими.
> 
> Я просто вижу, что вы упомянули приложение (в вашем приложении). О каком приложении ты говоришь? У нас нет приложения. У нас есть только веб-сайт [www.Photopea.com](http://www.Photopea.com) .
> 
> It should be "в вашем приложении" and not "в вашем приложение", you should learn Russian! :D
> 
> ![изображение](https://user-images.githubusercontent.com/15955558/126894463-6f9cddb2-a53c-475e-8faa-64b1550cd867.png)

It is very strange....

**Comment by photopea** [comment]
So I guess it is fixed. You should always use Photopea at www.Photopea.com, as it is our only official release.
