### ISSUE TITLE
I lost between hundreds of layers

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#3604]
when I have more than 100 layers it becomes too hard to find the layer without searchnig tools, even grouping layers makes it harder
can you please put the search tools as photoshop do ?

![Screenshot (253)](https://user-images.githubusercontent.com/70863817/126880567-b8227dfb-6bcc-45f4-8cc8-12342999dc57.png)

**Comment by mustafaGFX** [comment]
what do you think?

**Comment by photopea** [comment]
I agree!

@nothingshiru Could you create the 3 missing icons for the "Kind" filter? Image Layer, Shape Layer, Smart Object layer.

**Comment by nothingshiru** [comment]
@photopea 
Are these okay?
![Icons](https://user-images.githubusercontent.com/79258245/129117213-895040cd-a67e-469a-aadd-c2775450cde8.png)
[Icons.zip](https://github.com/photopea/photopea/files/6971930/Icons.zip)

**Comment by photopea** [comment]
I have added the layer filter to the top of the layers panel. Now, you can filter layers according to "Kind" and "Name" :)

**Comment by mustafaGFX** [comment]
> @nothingshiru Could you create the 3 missing icons for the "Kind" filter? Image Layer, Shape Layer, Smart Object layer.

oh, I'm so so sad right now :(
I was on travel and forgot to open GitHub, I'm so sorry :(

when I opened photopea today I was surprised, a lot of changes have been done to the look and the new layer filter was surprised

can I please redesign the icons, please?

**Comment by mustafaGFX** [comment]
and maybe if you can make the icons a little bit smaller to look cleaner?

**Comment by photopea** [comment]
The Text and Adjustment icons are used in Photopea elsewhere, they must have the same size everywhere. And other icons need to have the same size as these two.

**Comment by mustafaGFX** [comment]
> The Text and Adjustment icons are used in Photopea elsewhere, they must have the same size everywhere. And other icons need to have the same size as these two.

what if I designed new original icons?
