### ISSUE TITLE
"Not enough RAM (Need ..... MB)"

### ISSUE THREAD

**Issue by sankev1** [photopea/photopea#3605]
Can anyone explain what this means? thanks
![Screenshot (607)](https://user-images.githubusercontent.com/87925653/126890198-9bc00607-3ac5-4310-afd9-3b666747c50a.png)

**Comment by photopea** [comment]
Photopea attempted to allocate 26 terabytes of RAM. it is probably a bug. What did you do to make it happen?

**Comment by sankev1** [comment]
> Photopea attempted to allocate 26 terabytes of RAM. it is probably a bug. What did you do to make it happen?

I was making my project then all of a sudden it said it needed more RAM.

**Comment by photopea** [comment]
Can you make this alert happen again?

**Comment by sankev1** [comment]
> Can you make this alert happen again?
Fortunately this is fixed. I tried it with Opera GX browser. Thanks for the help

**Comment by photopea** [comment]
When you have a problem again, try to reproduce it multiple times. When can fix a problem only if we can reproduce it.
