### ISSUE TITLE
the picture is not saved. 

### ISSUE THREAD

**Issue by redmin22882** [photopea/photopea#3606]
sorry, of course, but what's going on ?! No seriously, at first there was a problem with brushes and now you can't even save a picture. not as PNG not in others. what's happened?! seriously i was on the previous version "69" and now I have upgraded to "1.0" and guess what? Now you cannot add brushes like this and save the image. And by the way, gradients cannot be added either. 

Seriously, I sincerely ask you to fix the problems as your Photoshop is the best.

**Comment by photopea** [comment]
Hi, what is a version 69 and 1.0? Are you using Photopea at www.Photopea.com ?

**Comment by redmin22882** [comment]
> Привет, а что такое версия 69 и 1.0? Вы используете Photopea на сайте [www.Photopea.com](http://www.Photopea.com) ?

no just an app. I do not like sites so much and therefore use your application. 

Sorry, maybe I'm making a mistake and it's not yours but ... Here ... 
![Screenshot_20210725-142942](https://user-images.githubusercontent.com/74855608/126894449-c182b5a9-58fe-4cce-bb0c-01b14393fd15.png)

**Comment by photopea** [comment]
Where did you find it? Is it for Android? we never made any app for Android.

**Comment by photopea** [comment]
Also, our app is called "Photopea", not "photopia".

**Comment by photopea** [comment]
Go to www.Photopea.com and press More - Install Photopea.

**Comment by redmin22882** [comment]
> Где вы его нашли? Это для Android? мы никогда не делали никаких приложений для Android.

hmm this is extremely strange since you can download it everywhere just by writing the name of your site. and the photopia is just the name of the application, and when you enter, the original photopеа

**Comment by redmin22882** [comment]
And yes everything for android

**Comment by redmin22882** [comment]
> Перейдите на сайт [www.Photopea.com](http://www.Photopea.com) и нажмите Еще - Установить Photopea.

Hmm sorry but how? I do not see how and where to install. And in any case, it's strange that the application is and works absolutely like your site but not yours ...

**Comment by photopea** [comment]
"you can download it everywhere" - like where?

**Comment by nothingshiru** [comment]
I heard last year that a guy made "Photopea" into an Android software and posted it on a forum. It didn't take long for him to be reported and the software was no longer working.

**Comment by redmin22882** [comment]
> В прошлом году я слышал, что один парень превратил Photopea в программу для Android и разместил ее на форуме. На то, чтобы о нем доложили, не потребовалось много времени, и программа перестала работать.

Ps mobile. So it was called. Initially, I used it before)

**Comment by redmin22882** [comment]
> "везде можно скачать" - вроде где? Не нашел в Google Play.



> "везде можно скачать" - вроде где? Не нашел в Google Play.

https://www.google.com/url?sa=t&source=web&rct=j&url=https://m.apkpure.com/ru/photopea/com.wphotopia_9508791&ved=2ahUKEwiO-8D8k_7xAhWi-ioKHUPJBmYQFjAGegQIHxAC&usg=AOvVaw0dPGvoiKXZ_njvh_C7kfTC

**Comment by redmin22882** [comment]
> "везде можно скачать" - вроде где? Не нашел в Google Play.

https://www.google.com/url?sa=t&source=web&rct=j&url=https://apk.support/app-ru/com.wphotopia_9508791&ved=2ahUKEwifuYKSlP7xAhVys4sKHd3YBTUQFjAGegQIChAC&usg=AOvVaw1XinBFIgX5epfUB5VHJgbd

**Comment by photopea** [comment]
We provide only www.Photopea.com . You can press More - Install Photopea to install it into your device.

![image (1)](https://user-images.githubusercontent.com/15955558/126899231-47c3f826-d1a3-45ba-b210-91bc67ca6836.png)

All other apps are fake, they probably contain viruses. It is up to you, if you want to use such APKs. But we can not fix any problems in these APKs, as they are not under our control.

**Comment by redmin22882** [comment]
Yes, everything is now loaded brushes and everything is through your application. which I could download through your website. thanks!)
