### ISSUE TITLE
AD blocking issue

### ISSUE THREAD

**Issue by sanse329** [photopea/photopea#3609]
dear photopea develepors,

i regularly use photopea, but lately i was blocked from the site because i had an ad blocker, once i turned it off it still blocked me, please fix this issue so that i can contiue making in your awesome website

**Comment by photopea** [comment]
Hi, what do you mean "you were blocked"? What do you see when you open www.Photopea.com ?

**Comment by photopea** [comment]
We do not have any blocking in Photopea. Every person in the world should see the same thing when they open  www.Photopea.com (unless they have a web browser from 1996) :)

**Comment by davidanttony** [comment]
Getting the same issue for last 4 days :)

In incognito mode the ads load fine -- but in normal mode, they do not load and I get the message :

`We use advertisement to get money for our development. Your device seems to be blocking ads. Please, let us show you ads, or buy a Premium account (Account - Log In - Buy). If you just unblocked ads, reload Photopea.  5`

Thanks kindly

AND THANK YOU for a GREAT GREAT plugin -- I will be reviewing it soon on Affyboy youtube channel -- super great tool :)

**Comment by NabeelJ-Git** [comment]
I am experiencing the same issue. I use AdBlock but I whitelist Photopea. This has worked in the past, but now it gives the "Your device seems to be blocking ads" dialog box regardless of whether AdBlock is paused for Photopea or not. However, if I disable the AdBlock extension entirely in chrome://extensions, then the site works.

**Comment by photopea** [comment]
The difference between the Incognito and the normal mode is, that all extensions are disabled in Incognito.

That means, that you are using an extension, which block ads. If you don't know which of your extensions block ads, try to disable all of them.

https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by photopea** [comment]
A website (like Photopea) can not disable your browser extensions :( Sadly, it works the other way, extensions have a full control over each website.

**Comment by TuxPaper** [comment]
Admins, you will keep getting these issues filed by your users until you recognize that it's YOUR problem.  If every other site can handle showing ads with Adblock whitelisting the site, YOU SHOULD TOO.


Or, keep closing the issues and blaming the users. You do you.
