### ISSUE TITLE
Could you add "transparency shapes layer" bending option in photopea

### ISSUE THREAD

**Issue by Mohammed-mohdaly** [photopea/photopea#3611]
The "transparency shapes layer" bending option is in photoshop. It's so useful, especially with color dodge mode. It makes a white spot like a real light. I hope you could add it to photopea.

![Screenshot 2021-07-26 052115](https://user-images.githubusercontent.com/87958243/126926038-bf281f3b-c740-402a-8e12-b5fce802bc67.jpg)
![Screenshot 2021-07-26 052405](https://user-images.githubusercontent.com/87958243/126926044-8acb6656-0619-44a8-ba22-dd40746b0f7f.jpg)

**Comment by photopea** [comment]
From what I see, disabling this option just disables layer stlyes. Or does it do anything else? Could you share a PSD file, where disabling this option performs something "interesting"? :)

**Comment by Mohammed-mohdaly** [comment]
No, I think you get the wrong end of the stick. Disabling this option with selecting color dodge changes the layer to look like real light. 
Sorry but I don't have photoshop. But these videos will show you the result of disabling this option. And thanks for your attention😄.
https://youtu.be/go_EBl2zsQ4?t=467 (this video in Arabic but clarifies the idea)
https://youtu.be/n3NniavNOIM?t=810

**Comment by photopea** [comment]
I see, but I still can't understand what it does in terms of color modification.

Is there any other blend mode, which looks different with "transparency shapes layer" disabled? Or any other useful usage of it?

**Comment by photopea** [comment]
So I give up, I don't know how this feature works, and how to buid it :(
