### ISSUE TITLE
How to create an Account

### ISSUE THREAD

**Issue by bosssorin** [photopea/photopea#3613]
Hi there again , 
I saw only Log In but not, Create an Account .

I want to make an abonament on you website for that reason i put so many questions

**Comment by photopea** [comment]
Logging in to Photopea through a third service will create a new account, if you still don't have any.

**Comment by bosssorin** [comment]
> Logging in to Photopea through a third service will create a new account, if you still don't have any.

What do you mean if I don't have any?  So is not possible to create an account just only with third parties like facebook google and so on ?

**Comment by photopea** [comment]
No, you can create an account in only through a third-party service.

This way, we do no thave to store any passwords, and users don't have to remember any passwords.

**Comment by bosssorin** [comment]
> No, you can create an account in only through a third-party service.
> 
> This way, we do no thave to store any passwords, and users don't have to remember any passwords for Photopea.

Ahah ! I seeeeee now okay, i've got it now, we just only connect for instant with facebook then after connected, then we choose whatever option of abonements we what like 10$ or 40$.
Then you cards like Visa or  Paypal that's only it's attached to you website right ?

**Comment by photopea** [comment]
yes
