### ISSUE TITLE
Everypixel Plugin

### ISSUE THREAD

**Issue by yikuansun** [photopea/photopea#3615]
Hi,

I found a stock image site called Everypixel that scrapes images from everyone's favorite stock image websites such as Pexels, Unsplash, and Pixabay. It allows CORS so it can work as a Photopea plugin.
Here is the JSON data:
```
{
    "name": "Everypixel",
    "url" : "https://www.everypixel.com/free",
    "icon": "https://www.everypixel.com/i/mobile_icons/apple-touch-icon.png"
}
```
I have tried it and I think it works pretty well. Even though it is not natively integrated with the Photopea API, it is pretty nice to be able to quickly access it from within Photopea.
I think this will provide an alternative to the default Gallery plugin that more advanced Photopea users will appreciate. It provides a bigger and better selection of images, and they can be downloaded at higher resolutions (I find that the images in Gallery are a little too low resolution for those doing serious photo manipulation).
Please let me know what you think!

Thanks!

**Comment by photopea** [comment]
I find that website to be extremely hard to use inside a small frame. The "cookie policy" reappears each time you click on something.

I think 99% of users would try to drag-and-drop a photo into Photopea, which breaks their website (it becomes unusable). How do you actually get a photo from there to Photopea?

**Comment by yikuansun** [comment]
@photopea 

> I find that website to be extremely hard to use inside a small frame. The "cookie policy" reappears each time you click on something.

These are definitely true concerns, it isn't quite as aesthetically pleasing as it could be.

> I think 99% of users would try to drag-and-drop a photo into Photopea, which breaks their website (it becomes unusable). How do you actually get a photo from there to Photopea?

If you scroll down there will be a link to open the external page (Unsplash, Pexels, etc.) where you can download the image. I guess that this unintuitiveness does make it not quite ideal, especially for beginner users.

It'd be cool if people could add their own plugins (just to use on their own account/instance of Photopea), and they could choose to add the Everypixel plugin (this guarantees that they know what they are doing). But you do raise fair points, and I will close this issue.

I also just realized that you now use largeImageURL for the Pixabay gallery, I'm not sure if this was always the case but the images do seem higher resolution now, so one of my Gallery complaints was invalid. However, I do prefer Unsplash and Pexels, maybe I'll make plugins for those in the future.
