### ISSUE TITLE
Eyedropper does not work

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3616]
https://www.photopea.com/#iPKLbX7TU

it only get white everytime.
![image](https://user-images.githubusercontent.com/11801254/127072305-40a2b4a6-e530-4990-a43e-ea867f23ad0a.png)

**Comment by avagp** [comment]
it happens the same when i pick a color for a shape

**Comment by photopea** [comment]
I can not reproduce it :( could you share your PSD?

**Comment by avagp** [comment]
It is there on the URL

**Comment by avagp** [comment]
It only happens on that PSD.

On the rest don't

**Comment by avagp** [comment]
Open the URL and pick a color

**Comment by photopea** [comment]
I opened your PSD in Adobe Photoshop and it works the same. It is not an error, that is how it should work.

When you select a mask or a channel in a document, a color picker will pick from that channel. A color can be only a shade of gray.

Your document has a Quick Mask activated, see https://www.photopea.com/learn/selections

**Comment by avagp** [comment]
:O

Ok i got it. 

So, i press Q by mistake, i should ask you if you can set a little warning when you enter or quit Quick Mask.

Could you??

**Comment by photopea** [comment]
If you try to paint into any layer, it will paint into a quick mask instead.

If we show a message "you entered a quick mask", most of people would not notice it, or would not understand what it means and why is it displayed.

**Comment by avagp** [comment]
So, there is a way I can tell if I turned on?

Without going to the menu?

**Comment by photopea** [comment]
It is shown in Select - Quick Mask Mode.

**Comment by nothingshiru** [comment]
In Photoshop, the background color of layer would become red when Quick Mas Mode is turned on. 
![QQ截图20210730091907](https://user-images.githubusercontent.com/79258245/127585479-875154b0-29c7-45d5-b0ad-f735c0ce60d4.png)

**Comment by avagp** [comment]
That could work on Photopea!

**Comment by photopea** [comment]
Ok, I have implemented it :)

**Comment by avagp** [comment]
Yey!

**Comment by PenguinIsrael** [comment]
i just want to say thank you for asking this too. i couldn't pick a color too and couldn't understand why, i thought maybe it happens only on mobile or only on chrome, and i tried other editing apps. but photopea on mobile is really good. even the side ad is hidden.

photopea may not be totally open source but it is an amazing work. im impressed and think i'd keep using it
