### ISSUE TITLE
Unknown file format.

### ISSUE THREAD

**Issue by cyclops365** [photopea/photopea#3617]
![image](https://user-images.githubusercontent.com/72573834/127124443-c9c2b56b-a6df-46ec-85db-3e695928586e.png)

So I'm getting this sometimes after saving a psd file then reopening it when I need to work on it again.

**Comment by photopea** [comment]
Hi, how large is your PSD file? Is it zero Bytes?

Opera browser has a bug. It saves PSD files with zero bytes (an empty file). Is that your case?

**Comment by cyclops365** [comment]
Hi. Yes the file size is 0 bytes. I'm using Edge.

**Comment by photopea** [comment]
Do you get a 0-byte file every time you save a PSD in Photopea?

**Comment by cyclops365** [comment]
No

**Comment by photopea** [comment]
Can you find steps, how to make Photopea produce a zero-byte PSD file?

**Comment by cyclops365** [comment]
Sorry, I don't understand

**Comment by photopea** [comment]
Can you open Photopea.com and do something, and save the PSD of zero bytes at the end?

**Comment by cyclops365** [comment]
No I can't seem to anymore. This only started happening yesterday.

**Comment by photopea** [comment]
Photopea had a bug a week ago. If the PSD was too large, the saved file was zero bytes. This bug has been fixed or several days now.

Your PSD was produced a week ago or longer, right?

**Comment by cyclops365** [comment]
No, it's one I've just created now.

**Comment by cyclops365** [comment]
I will send the file to your email

**Comment by photopea** [comment]
A file of zero bytes does not contain any data, there is no need to send it to me.

I would prefer if you could describe some instructions, how can I make Photopea create such file.

**Comment by cyclops365** [comment]
I'm sorry, I'm not sure if it's your English but I cannot understand what you're asking. Maybe the bug has reappeared?

**Comment by photopea** [comment]
So the bug is, that Photopea exported a PSD file, which is 0 Bytes. This is wrong, this should never happen.

To be able to fix it, I need to make it happen on my coputer. I need to know, how to make Photopea export a PSD file of 0 Bytes. How did you do it? In my case, I always get a PSD, which is more than 0 Bytes.

**Comment by yikuansun** [comment]
@cyclops365 What did you do to get that 0 Byte file in the first place?

**Comment by photopea** [comment]
I have to close it because of lack of details. If you know how to make Photopea produce a 0 Byte file, while all browser extensions are disabled, let us know!
