### ISSUE TITLE
Path text is not align?

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3618]
I don't know if this a bug ir not, but my text is not correctlly aligned when using the guides.
![image](https://user-images.githubusercontent.com/11801254/127202929-423d4b85-7e5d-4078-a9d5-2cfb16616f1a.png)

https://www.photopea.com/#iV4ASoGMR

**Comment by photopea** [comment]
Sorry, I don't have your font to render it :(

But I think in this case, the author of your font made it this way. These gaps are under the control of a font.

**Comment by avagp** [comment]
[resources.zip](https://github.com/photopea/photopea/files/6889183/resources.zip)

here are my fonts.

Just in case, upload them and check if it is the font, so we can get it clear

**Comment by photopea** [comment]
Thanks, I downloaded your PSD and your fonts to my computer, and opened them in Adobe Photoshop, and the text is rendered identically as in Photopea.

**Comment by avagp** [comment]
Thanks :D

That solves the mystery
