### ISSUE TITLE
Using QuteBrowser I can't import a file

### ISSUE THREAD

**Issue by LamprosPitsillos** [photopea/photopea#3620]
I am using [qutebrowser](https://github.com/qutebrowser/qutebrowser) .
While trying to import a file , no pop up appears.
Maybe its the browsers fault, Just reporting it anyway .
I made issues in both repositories.

**Comment by photopea** [comment]
I think it is a bug in their browser, as Photopea works well in other browsers. You can ask them to fix it, or switch to another browser.
