### ISSUE TITLE
Spot Healing Brush strokes persist

### ISSUE THREAD

**Issue by VollmerMarcel** [photopea/photopea#3621]
When drawing with the Spot Healing Brush Tool using left mouse button the brush strokes persist and become part of the picture. "Undo" will not get rid of them.

How to reproduce:

1. Select Spot Healing Brush Tool (J),
2. draw and keep the left mouse button pressed,
3. press the middle mouse button (mouse wheel) and keep it pressed,
4. release the left mouse button (notice how you can still draw!),
5. release the mouse wheel.
The grey lines you have drawn are now part of the picture.

**Comment by photopea** [comment]
I have fixed it. Clicking or releasing the middle button should be completely ignored by Photopea now.
