### ISSUE TITLE
Unkown JSON file opened. See the content in console

### ISSUE THREAD

**Issue by Ethan2606** [photopea/photopea#3622]
![Screenshot (2)](https://user-images.githubusercontent.com/88131430/127444605-159b14b0-37d8-46eb-8806-02b6f23f97ef.png) 

This is what happens when I try to load a psd file into photopea. I paid for these psds and need help ASAP

**Comment by photopea** [comment]
Who created your PSD file? Are you or anyone else able to open your PSD file in any program (other than Photopea)?

**Comment by Ethan2606** [comment]
> Who created your PSD file? Are you or anyone else able to open your PSD file in any program (other than Photopea)?

An instagram page created it for me. I dont know what other programs I could try to open it in.

**Comment by photopea** [comment]
Could you share your PSD file with us? I can not make my Instagram give me any PSDs :/

**Comment by Ethan2606** [comment]
> Could you share your PSD file with us? I can not make my Instagram give me any PSDs :/

https://drive.google.com/drive/folders/1E2TgiuHnGvVaa3wFOanS2Djs1HHHM3oV?usp=sharing

**Comment by photopea** [comment]
Sorry, but I can not download a file from your link :( could you maybe send it to support@photopea.com ?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
