### ISSUE TITLE
Clipboard Error

### ISSUE THREAD

**Issue by ryannoor41** [photopea/photopea#3623]
Whenever I try pasting an image on Photopea it keeps coming up with the same error: "Clipboard error: (No valid data on clipboard.)". I've been using Photopea for weeks and I never had this issue until now. I've tried pasting with Ctrl-V and manually, I've tried pasting on many browsers (all of them are up to date), I even tried on a different device and I still get the same error message. I can copy and paste images on other websites and applications, but not Photopea. This is really frustrating because I love using Photopea, but I just can't paste my images to edit them anymore. Btw the files I'm trying to copy and paste are just simple PNG files and I've made sure my clipboard can be accessed by Photopea.

**Comment by photopea** [comment]
Hi, when you copy an image, can you paste it in Imgur.com ? If yes, can you paste it into Photopea right after pasting it into Imgur, i.e. the same image, without copying anything else in between?

**Comment by ryannoor41** [comment]
> Hi, when you copy an image, can you paste it in Imgur.com ? If yes, can you paste it into Photopea right after pasting it into Imgur, i.e. the same image, without copying anything else in between?

I've tried pasting in Imgur.com and it worked, but not on Photopea, I have a link to me doing it if you don't believe me.
https://imgur.com/a/3M5fOrH

**Comment by photopea** [comment]
That is so strange :( I would like to try reproduce the same behaviour on my computer. How did you copy your image? 

When I right-click an image on some website, and choose "Copy image", I can always paste it into Photopea.

**Comment by ryannoor41** [comment]
> That is so strange :( I would like to try reproduce the same behaviour on my computer. How did you copy your image?
> 
> When I right-click an image on some website, and choose "Copy image", I can always paste it into Photopea.

Oh, I think I see the problem, whenever I copy the image from the "Photos" viewer it doesn't paste onto Photopea, but if you do it from a website it'll work. This is weird because it worked before but then it suddenly stopped working recently. Thanks for your help, now I can go back to editing my photos.
