### ISSUE TITLE
Default panel window size is a little bit large

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3625]
After you made them adjustable, they are little bit large. 
![Screenshot_20210730_093659_com android chrome](https://user-images.githubusercontent.com/79258245/127586956-0b6a11a5-607f-4b18-ad45-392d06215911.jpg)
![Screenshot_20210730_093703_com android chrome](https://user-images.githubusercontent.com/79258245/127586958-c0c7f156-7d02-422c-866d-24823bc3e5db.jpg)

**Comment by photopea** [comment]
The default size is the same for all windows now. What exactly do you want to be different?

**Comment by mustafaGFX** [comment]
make every window has its suitable size because the same size for all windows is not a good idea, every panel needs a specific size to be Appropriate

**Comment by nothingshiru** [comment]
For the Properties panel, the default size only needs to be just right to show all options. For the a panel, we don't need it to be so big most of the time, just as big as before, after all, we can now manually adjust it to the desired size

**Comment by photopea** [comment]
Right now, each panel can be either resizeable, or have a fixed size all the time. So if we give Layer Comps a fixed size, it can not be resizable.

**Comment by MichalSZZ** [comment]
Layer Comps can be smaller with ability to resize. Not everyone give names as long as me ;) but when someone have longer comp names, now he can drag and resize to a little bit bigger

**Comment by nothingshiru** [comment]
I didn't mean fixed size.
I noticed that the default sizes of the different resizable panels are somewhat different, which means that their default sizes can be set independently, right?
