### ISSUE TITLE
Artboards - Resizing and then moving an artboard in undoable 

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3628]
Here is the video of the bug:
[Screen recording 2021-07-30 22.04.58.zip](https://github.com/photopea/photopea/files/6910503/Screen.recording.2021-07-30.22.04.58.zip)

When having an artboard if i resize it, and then move it. If i press Undo (Ctrl+Z) it returns to the last point, but then resize to another size, giving a weird final result.

![image](https://user-images.githubusercontent.com/11801254/127725572-7017cb1e-420b-44c2-9d29-4918ae3c4df0.png)

**Comment by photopea** [comment]
fixed, thanks for reporting :)
