### ISSUE TITLE
Crop Tool problem

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#363]
I made selection Rectangle Select and I released my mouse exactly on "Crop Tool" icon on toolbar.
Also happens with other tools like if you use Gradient Tool or selecting text with Type Tool and you release you mouse button on that icon.
->
pp.js:2284 Uncaught TypeError: Cannot read property 'wL' of null
    at f.A_.wL (pp.js:2284)
    at rZ.grN (pp.js:5951)
    at rZ.rT.K (pp.js:6)
    at rZ.gk.K (pp.js:4148)
    at rL.gk.K (pp.js:4148)
    at Fx.gk.K (pp.js:4148)
    at Fx.A$ (pp.js:5429)

Also "Zoom tool" has similar problem it show this when you relese mouse button on icon with various tools
->
pp.js:1288 Uncaught TypeError: Cannot read property 'x' of null
    at Function.z.eb (pp.js:1288)
    at f.LZ.wL (pp.js:2674)
    at rZ.grN (pp.js:5951)
    at rZ.rT.K (pp.js:6)
    at rZ.gk.K (pp.js:4148)
    at rL.gk.K (pp.js:4148)
    at Fx.gk.K (pp.js:4148)
    at Fx.A$ (pp.js:5429)

**Comment by photopea** [comment]
A similar problem: The key C switches to the Crop tool. While dragging Rectangle Select, press C. The same problem.

**Comment by photopea** [comment]
Fixed. Thank you!

**Comment by photopea** [comment]
I fixed it by forbidding to switch tools while the mouse is down. But I forgot, that it should be allow to switch from Move to Free Transform when a user drags Transformation Controls.

**Comment by photopea** [comment]
I fixed it again. 
- tools in the toolbar are switched on "click", not just "mouseup"
- when tools need to be switched by a keyboard shortcut, the mouse must be released.
