### ISSUE TITLE
בעיה עם פקודת ctrl+

### ISSUE THREAD

**Issue by adi3355** [photopea/photopea#3630]
היי, אני לא מצליחה להדביק תמונות בתוכנה (אני משתמשת בתוסף). בדקתי וזה קורה רק בתוכנה הזו. ניסיתי פורמט אחר וניסיתי לעשות הפעלה מחדש למחשב, לא עוזר.
אשמח לקבל את עזרתכם,
עדי

**Comment by photopea** [comment]
Hi, do you copy images from a folder and paste them into Photopea? Have you tried to use File - Open?

**Comment by photopea** [comment]
We are trying to fix it here: https://github.com/photopea/photopea/issues/2118#issuecomment-889959373
