### ISSUE TITLE
Feature request: add an "Enhance" button and "Preserve Details 2.0" for resampling

### ISSUE THREAD

**Issue by ThatMario** [photopea/photopea#3632]
![super_resolution](https://user-images.githubusercontent.com/87676924/128245412-c84d531e-abde-4784-b86f-4755a990a150.png)

![photoshop-preserve-details-2](https://user-images.githubusercontent.com/87676924/128245482-f1ab7dc3-1902-474c-af09-81a70d7eb0c6.png)

Hi there!

I've an idea of feature that can be added to Photopea, it's to add a "Preserve Details 2.0" in the photo size change resample list bar or or an equivalent of this option that we have in Photoshop. Also, is it possible to add an "Enhance" button to upscale photo? You know what I mean?

I'm asking those options, like that we can do more easily: upscaling photos. ;)

Thanks you and have a nice day!

**Comment by photopea** [comment]
I am not convinced, that this feature is actually useful for anyone. Could you try to upscale this photo 4x? 
![image](https://user-images.githubusercontent.com/15955558/128252604-3e90e0b8-5745-4b10-98e7-94aff3fcd518.jpg)

The result of Photopea (bilinear) is on the left, the result of Preserve Details 2.0 is on the right.
![ivan_face](https://user-images.githubusercontent.com/15955558/128252666-dea05121-7b56-425a-8cfe-070fef814d37.jpg)
 
It makes some parts sharper, but smooths the rest too much, it looks very unnatural, like a painting.

**Comment by photopea** [comment]
So I would prefer not to implement it, as it would probably be too hard and take me weeks, while the effect is not worth it.
