### ISSUE TITLE
Stitch together images doesn't work wont allow the simple copy paste process, says 'Clipboard Error: Read Permission Denied'

### ISSUE THREAD

**Issue by h1110** [photopea/photopea#3633]
Stitch together images doesn't work wont allow the simple copy paste process, says 'Clipboard Error: Read Permission Denied'

**Comment by photopea** [comment]
So the problem is with copy-pasting, right? How do you copy-paste? What should I do in Photopea to see such error? Did you give Photopea permissions to access the clipboard? Click the lock icon in your browser and give the permissions.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
