### ISSUE TITLE
cannot resize any element other than open & place image

### ISSUE THREAD

**Issue by thevegasmovement** [photopea/photopea#3634]
when I first started using this, I was able to reize an element using the handle bars. Now, the only thing I can resize is an image that I've placed. I've made sure that the layer was on top and all that. I can MOVE the element but I cannot RESIZE it

**Comment by photopea** [comment]
I think you have enabled "Transform controls" in the past, but now, they are disabled.

Select the move tool and enable "Transform controls" at the top.

You can also use Edit - Free Transform, to transform all selected layers.

**Comment by thevegasmovement** [comment]
hi when I login I am presented with purchasing again even though I bought a
year. I cleared my cookies and now I am not sure what to do because I never
received a key or anything

**Comment by thevegasmovement** [comment]
I refreshed and it looks like we are good to go

**Comment by photopea** [comment]
I am glad it works.
