### ISSUE TITLE
Feature Request: Add a way to turn off the saving reminders

### ISSUE THREAD

**Issue by AirGEL** [photopea/photopea#3636]
The saving reminders get annoying when I have 4 documents open, and 3 of them I have no intention of saving. Can there be a way to turn these reminders off (preferably by document)?

**Comment by photopea** [comment]
That means that you have a document, that is modified, and has not been saved for more than an hour. Aren't you afraid, that your browser would crash, or your device runs out of battery, and you lose all unsaved work?

If you don't want to save that work, why don't you close that document? Or return to the original state in that document, so that there is no "unsaved work" detected by Photopea.

**Comment by WilliamTDoran** [comment]
That's not a reason to not give us the option. The notifications are obnoxious, interrupt workflow, etc. Plus I'll often have documents open that I use as reference or the like for what I'm actually working on, and so have no need to save but still need to keep open.

**Comment by photopea** [comment]
We received many reports from users losing their work

https://www.reddit.com/r/photopea/comments/owojd1/any_way_to_regain_lost_work/
https://twitter.com/KazeYoTsutaete/status/1418991198497296387
https://twitter.com/ItsNovaRBLX/status/1420575411889524738

**Comment by WilliamTDoran** [comment]
Yeah and it's a good feature to have in general I'm sure, but it's no use to me so I'd like a way to disable it for my own use.

**Comment by Weesals** [comment]
I'd like an option to turn this off too. I often resize, crop, or recolour images, then export and leave them open in case I want to adjust further, but I don't want to save them since there's no work to save that isn't already exported.

**Comment by photopea** [comment]
You can disable this massage in Edit - Preferences now.

Also, Photopea is checking for unsaved work once every 30 minutes, instead of 10 minutes as before (so if you keep it enabled, you will see the message at most 2x an hour, instead of 6x).

**Comment by WilliamTDoran** [comment]
Awesome, thank you
