### ISSUE TITLE
Add Reduce Noice in Actions, please <3

### ISSUE THREAD

**Issue by AFA0000** [photopea/photopea#3637]
When recording Action I applied "Reduce Noise" filter but it was not recorded. Thank You !
![image](https://user-images.githubusercontent.com/88556499/128556049-45780bbc-82ca-4e66-8cb2-c31ea53e6318.png)

**Comment by Yash-Kumar-Gupta-0845** [comment]
autoconnect with system speaker and record section

**Comment by photopea** [comment]
It is fixed now, thanks for reporting :)
