### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by agiraud2** [photopea/photopea#3643]
I don't manage to download my creation on Photopea.
I go to File > Export as > png, I have a pop-up, then I click on save but nothing happens...
How can I do ?

**Comment by photopea** [comment]
Hi, did it ever work before in your case? Did you look into a folder, where your downloaded files are usually stored?

**Comment by MyraVerz** [comment]
i have a similar issue, but mine is that when i hit download it automatically downloads as .txt

**Comment by photopea** [comment]
@MyraVerz Are you using a browser extension "Free Download Manager"? This extension renames downloaded files to .TXT

**Comment by MyraVerz** [comment]
oooh, I do! thanks for answering!
