### ISSUE TITLE
it doesn't save anything

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#3645]
yesterday I opened a PSD file and edited it ad click ctrl+s, then went to file>save (to make sure)
and opens it again and I was surprised that nothing of my edits was saved !!

i did that many times and a lot of my work has been gone :(

**Comment by photopea** [comment]
File - Save is not available for standard files in Photopea now. It should be gray. How did you click it?

**Comment by mustafaGFX** [comment]
here
![Screenshot (273)](https://user-images.githubusercontent.com/70863817/128877724-cde897f1-75e1-4169-bc26-c0cdc650bd08.png)

**Comment by mustafaGFX** [comment]
hey, it works well now !!

**Comment by photopea** [comment]
File - Save works only on documents, which were opened from your computer. 

In the future, I need some steps to reproduce a bug. I can not fix a problem, if I can not reproduce it.

**Comment by mustafaGFX** [comment]
gotcha
