### ISSUE TITLE
how to delete photopea account? it is a free account but i want to delete the account and start a new one.

### ISSUE THREAD

**Issue by HarryMonteno** [photopea/photopea#3646]

**Comment by photopea** [comment]
Whato do you mean by deleting an account and starting a new one? What is wrong with your account?

**Comment by HarryMonteno** [comment]
> Whato do you mean by deleting an account and starting a new one? What is wrong with your account?

actually i accidently created an account with my work email id which i am not allowed to. so i want to delete that account and make another with my personal email id and use this wonderful app.

**Comment by photopea** [comment]
You can log in only using your Google, Facebook, Microsoft or Github account. These services tell us your name and your email address.

Log out of Photopea and log in e.g. with Facebook (or other service, where you have a different email address).

**Comment by HarryMonteno** [comment]
Thank you Photopea
