### ISSUE TITLE
How do I disabled save reminders?

### ISSUE THREAD

**Issue by rocifier** [photopea/photopea#3651]
Whether I save my work or not, I keep getting a modal prompt saying "You haven't saved untitled.psd for 1135 minutes, would you like to save it now?"

- Generally I have saved it so no I don't want to
- If I choose no it keeps asking me if I leave my computer idle. If I'm painting from photopea as my reference this is really annoying as I have to put my brush down and click no
- If I do save it, it always creates a new file download and if I clicked yes every time then I would end up with hundreds of separate .psd files
- Can I please disable that popup altogether somehow?

**Comment by photopea** [comment]
What message exactly do you see? It should contain instructions about disabling the message.

Please, reload Photopea.com in your browser at least once a week, to be sure you are using the latest version.

**Comment by rocifier** [comment]
A message basically the same as above quote marks but no instructions to disable it. I'll try hard reloading my page now and see what it says

**Comment by rocifier** [comment]
Awesome there is now a setting in edit->preferences. You could close this issue now, thanks!

**Comment by photopea** [comment]
I still wonder why you did not see "Edit - Preferences" in the message. Photopea is displaying it for at least a week now.

**Comment by rocifier** [comment]
I leave my browser running 24/7 (by sleeping my machine). Because I had active work open in photopea, I hadn't reloaded that tab.
