### ISSUE TITLE
Illegal photopea clone?

### ISSUE THREAD

**Issue by ioma8** [photopea/photopea#3652]
Hello, do you know of this website? Is it done with your agreement? Its basicaly clone of Photopea.
https://www.freeonlinephotoshop.com/

**Comment by photopea** [comment]
They just inserted www.Photopea.com into their website as the iframe. Many people do it, there is nothing wrong with it.

I wonder why would anybody prefer to use Photopea on their site, rather than at Photopea.com . But I think they do not "steal" users from us.
