### ISSUE TITLE
All file handlers in manifest not used by Chrome OS

### ISSUE THREAD

**Issue by Nu11u5** [photopea/photopea#3653]
Chrome OS supports using file handlers declared in the manifest to allow opening local files directly in Photopea through the file manager.  However, it appears that Chrome OS only supports the first 10 file handlers declared in the manifest, and the rest are ignored.  I do not know if this behavior is seen on other platforms.

### Suggested work-around

Until/if Chrome OS is updated to support more than 10 file handlers, I suggest that the file handlers are sorted by popularity, so that the most commonly used file types are in the first 10 entries in the list.

**Comment by Nu11u5** [comment]
![Screenshot 2021-08-13 11 42 06](https://user-images.githubusercontent.com/617690/129392233-232406fe-622a-4cde-91a4-0daf5dd567c3.png)

Notice that only 10 file types are listed.  PNG is include while JPG is not (as an example).  This is reflected in ChromeOS when trying to open an image file with Photopea.

**Comment by photopea** [comment]
I ordered them by popularity :)

However, when someone double-clicks a JPG or a PDF, I think it should be opened in some default viewer, instead of Photopea.

**Comment by Nu11u5** [comment]
> I ordered them by popularity :)
> 
> However, when someone double-clicks a JPG or a PDF, I think it should be opened in some default viewer, instead of Photopea.

Awesome and thanks!

With Chrome OS (as with other platforms) you can set the default app from a list, or pick an alternative through an "Open with" menu.  The default viewer works well, but it is very convenient to pick a file > open with > Photopea.

**Comment by photopea** [comment]
ok great :)
