### ISSUE TITLE
Difference in photo export quality 

### ISSUE THREAD

**Issue by Crosshat12** [photopea/photopea#3654]
Every time I export a photo from Photopea it seems to export at a lower quality than what I'm seeing in the Photopea editor. It is slightly blurrier and less sharp. Just wondering how I can get it to export my photo in the same quality as what I'm seeing in the editor.

**Comment by photopea** [comment]
I think when you view your photo, it is zoomed in, or zoomed out. That creates a blur effect.

Put a ruler on your screen and measure some part of your image in Photopea. Then, measure the same part in your image viewer. It is probably a different size. Scaling an image up or down (bilinear interpolation) creates the blur effect.
