### ISSUE TITLE
Exporting layers results in an empty zip file

### ISSUE THREAD

**Issue by Laurennial** [photopea/photopea#3655]
Anytime I hit "export layers," the resulting zip file is empty. Windows says it's invalid, and when I open it to look at it, nothing is there. I unclick the box that says "only export layers beginning with -e-," and I have it trim transparent parts, export as PNG at 100% quality. The dialogue box says there are 20 layers to export, but nothing is there. This particular zip file says it's 273KB as well, but there's nothing in it? I'm not sure what's up. Attached is the file I'm trying to export the layers of. Originally, each layer was a folder of paths that I rasterized first.

[various blue waves-ai.zip](https://github.com/photopea/photopea/files/6984530/various.blue.waves-ai.zip)

Is there something I'm doing wrong or is this a known issue? Thanks!

**Comment by photopea** [comment]
Photopea creates a PNG file for each layer, and names that file according to the name of a layer.

I think the problem is in having the "<" and ">" characters in a file name. Could you remove them from layer names? Or maybe Photopea could remove these characters when exporting a PNG.

**Comment by Laurennial** [comment]
> Photopea creates a PNG file for each layer, and names that file according to the name of a layer.
> 
> I think the problem is in having the "<" and ">" characters in a file name. Could you remove them from layer names? Or maybe Photopea could remove these characters when exporting a PNG.

you angel! I would have never thought of this. That was the problem. It would be mega convenient if there was a way Photopea could remove or ignore those characters because all of the files I use that I would want to export the layers from have them (gahhhh) BUT I totally understand if that's not possible or it's a huge pain, etc. But thankfully I now know the problem and I can work around it. THANK YOU. I adore Photopea so much, I'm constantly telling people about it and I pay to use it because the cost is so reasonable and I get SO SO SO much value from it. You're amazing, thank you!

**Comment by photopea** [comment]
I have fixed it. The following characters will be replaced with the underscore when exporting layers: #%&{}\<>*?/$!'\":@+`|=

I am very sorry for not realizing this problem before.

**Comment by Laurennial** [comment]
> I have fixed it. The following characters will be replaced with the underscore when exporting layers:
> 
> ```
> #%&{}\<>*?/$!'\":@+`|=
> ```
> 
> I am very sorry for not realizing this problem before.

It's totally okay! It probably doesn't happen very often haha. I'm writing again to let you know, though, that the feature has stopped working; it stopped working after the site was buggy for a little bit (I noticed there was a day where clicking various parts of the dropdown menus didn't work, but I wasn't worried because I knew you'd have it fixed right away) so I figured you might have done a rollback or something to a more functional version, where this fix wasn't implemented. Sorry to be a pest, but it's a HUGE help for me! If it's not a pain to get that feature working again, I'd really appreciate it. 

Thank you so much for all you do, I wish all software devs were as dedicated as you are!

**Comment by photopea** [comment]
Hi Laurennial, yes, I switched to the old version.

I think the real bug is in your ZIP program, which does not work well, when file names contain "<". Can you try another ZIP program? Or simply rename your layers in Photopea.

**Comment by Laurennial** [comment]
> Hi Laurennial, yes, I switched to the old version.
> 
> I think the real bug is in your ZIP program, which does not work well, when file names contain "<". Can you try another ZIP program? Or simply rename your layers in Photopea.

I can try another zip program, photopea just uses the windows default one so if I make something like 7 Zip the default instead that might help? I can rename my layers, but my problem with that is that I often have files that have 20+ layers I would have to rename. The situation is that I use a Japanese website, AC Illust, and I download the AI files to open in Photopea (thank you for that as well, by the way) and merge multiple layers to make it much easier to remove and use certain elements of the art. I know that's confusing to explain lol let me add a photo of what I mean: 

https://thumb.ac-illust.com/1d/1de35436c848895190d64743943d42e6_w.jpeg 

So, what I do with the export layers thing, is I merge the layers of each of those little images and export the merged parts. it makes it way easier to use the materials, which is what that site is for. 

I'll see if something like 7 Zip ignores those characters, that would also fix the problem. Thanks for your fast reply!

**Comment by Laurennial** [comment]
update, 7-zip works for this! I'm not sure why the default Windows one breaks in this way, but that means you don't have to worry about this! Thanks again, I appreciate your work a lot!

**Comment by photopea** [comment]
Maybe you can update your Windows, and the new version will have the ZIP issue fixed :)

I use WinRar and it can also handle characters like "<" in file names.
