### ISSUE TITLE
Google Charts plugin

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#3656]
I created this new plugin. It can generate svg for basic chart types via Google Charts API from here https://developers.google.com/chart
Plugin URL:
https://www.photopea.com/#%7B%22environment%22:%7B%22plugins%22:%5B%7B%22name%22:%22Google%20Charts%22,%22url%22:%22https://hxim.github.io/TwemojiPlugin/gcharts/gcharts.html%22,%22width%22:380,%22height%22:400,%22icon%22:%22https://hxim.github.io/TwemojiPlugin/gcharts/icon.svg%22%7D%5D%7D%7D

**Comment by MichalSZZ** [comment]
Super cool!

I have few questions:
1. Why some of parameters have inputs (like font size). For this example it is easy to set, but in some of these parameters with input HTML element, I don't know what to write...

2. Can you set defeult font different than Arial? Some kind of free font used by Photopea

3. Is it possible to name catalogs in different way than Layer, Layer, Layer... for example as a name of options (Legend, Title, Graph, x-y-axisx-axis-values-values etc.)

I cheked it on mobile phone but it looks great for me! And will be very usefull!

**Comment by hxim** [comment]
@MichalSZZ 
Thanks.
1.) In the bottom of Options window there is link going to Google Charts Guide page for example for PieChart it goes to here https://developers.google.com/chart/interactive/docs/gallery/piechart#configuration-options - There you can read about all complex paramters in Configuration Options section - only difference is you need to enter them in JSON format which means for example for pieSliceTextStyle paremter you enter
`{"color": "red", "fontName": "Arial", "fontSize": 15}`
instead of
`{color: "red", fontName: "Arial", fontSize: 15}`
(with quotes for attribute names)
2.) I did not set those default values this is what is provided by Google Chart API as you can read in Guide
3.) I don't think so beacuse SVG is generated directly by Google Chart API and I put it to Photopea without modifications. I would need to parse the svg and somehow detect which folder means what and then reassemble it (or rename folders after insertions with some script) - seems too complicated.

**Comment by MichalSZZ** [comment]
OK, thanks. I understand all.
With my sugestions it can be more user friendly for non technical users. 
But now it is great also. Amazing job.
I made all my charts in adobe illustrator with build in chart maker. But it has very simply editor with only a few graph types

**Comment by photopea** [comment]
Hi, that is great! I added it under Window - More - Chart Maker :)

You can keep discussing it here. Maybe you could make a UI for adding values for people, who don't know JSON, or allow CSV format. But these are just some ideas.

Also, I wonder, how well you replicated the UI of Photopea :D

**Comment by hxim** [comment]
Hi,
1.) Fixed some bugs.
2.) Alowed entering data in CSV which will be immediately automatically converted
3.) Most of complex options have new edit button now which opens new window so you don't need to enter in JSON objects manually.
4.) There may be issue with loading fonts because when people specify font family with regular name it will not be loaded to photopea because it needs it in postscript name - we discussed it here: https://github.com/photopea/photopea/issues/2199#issuecomment-647915962
