### ISSUE TITLE
Bug's Report

### ISSUE THREAD

**Issue by YasirKhan9193** [photopea/photopea#3657]
Hello, I am using Photopea for seven days. It is the best alternative to photoshop and I love it. All the features are amazing but now I have got an issue.
1. The color Picker is not working
2.  Gradient is not working
3. Is there any illustration application of Photopea.

Please resolve these issues, I will be grateful for this.
Thank You.

**Comment by photopea** [comment]
Hi, thanks! 

What should I do to see the color picker or the gradient tool not working? Whenever I use them, they seem to work fine.

Photopea can open PDF, SVG and AI files, you can create vector graphics in it. We do not have any other software for vector graphics now.

**Comment by photopea** [comment]
I have to close it because of lack of details.
