### ISSUE TITLE
When I use my stylus to draw, and switch and move the mouse, the mouse continues to draw lines until I click

### ISSUE THREAD

**Issue by kmichnicki** [photopea/photopea#3661]
1. I draw with the pen
2. I move the mouse and it leaves a line until I click

This tells me that the editor is not detecting that the pen has lifted from the screen.

Also, there is a huge delay between putting the pen down, and the program recognizing that I've drawn something. Is it talking to the server each time a mark is made? I feel like it would be better if all the drawing was done in javascript. I think you can compile code and run it from the browser, which would be faster than sending data to the server, if indeed that is what you are doing.

**Comment by photopea** [comment]
Sadly, I don't have a pen to try it out :( Photopea was not built to use the stylus and the mouse simultaneously. So Photopea never detects releasing the stylus? And it keeps drawing until you close Photopea (I mean, without using a mouse at all).

What is the resolution of your document? Is it 1, 10 or 100 million pixels? Processing 100 million pixels 60 times per second is hard, so it can be laggy.

**Comment by photopea** [comment]
A pixel is 4 Bytes (8 bits for red, green, blue and transparency), 100 million pixels would be 400 MB. 

If Photopea was sending something to a server, it would need to send 400 MB 60 times per second. You would need 192 gigabit internet upload and 192 gigabit download.

**Comment by photopea** [comment]
It should be fixed now.
