### ISSUE TITLE
index file (html) in "jpg export" isn't working

### ISSUE THREAD

**Issue by rocktambulos** [photopea/photopea#3666]
Hi, when I export my sliced design (a website) as jpg, the zip is showing all the files in the same folder, instead of a img folder and the index file separated. No matter how I export the files, the result is an unique folder with images and an index file among it, that in fact, doesn't work. When I open the index file, is blank. What could be happening? Thanks in advance

**Comment by photopea** [comment]
I am very sorry, it should be fixed now.
