### ISSUE TITLE
I cant download the program

### ISSUE THREAD

**Issue by xxTxx12** [photopea/photopea#3668]
when I click _more_, the photopea download button is disabled

**Comment by photopea** [comment]
It is "install Photopea", not "download photopea". Photopea already works offline.

The "Install Photopea" is supported only by Chrome, Edge and Opera (and probably Safari) at the moment :(

**Comment by shuo-tian** [comment]
Still can't do it. Using Chrome.
![image](https://github.com/photopea/photopea/assets/120124789/59f0a71d-2be7-41e1-86fc-dc69128a2539)

**Comment by camoody1** [comment]
@shuo-tian It looks like Chrome thinks you already have it installed. Check your Chrome Installed Apps menu to see if it lists Chrome as already being installed as a web app. If it does, choose to uninstall it and then try again.

**Comment by photopea** [comment]
Look at the end of this article: https://www.photopea.com/tuts/install-photopea-to-your-device/

**Comment by CleerzScripts** [comment]
> [@shuo-tian](https://github.com/shuo-tian) It looks like Chrome thinks you already have it installed. Check your Chrome Installed Apps menu to see if it lists Chrome as already being installed as a web app. If it does, choose to uninstall it and then try again.

its the same thing for me but when i check apps it doesnt say i have it
