### ISSUE TITLE
Integrate Sentry

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#367]
I recommend integrate some error handling tool like https://sentry.io.
You can analyse not-reported errors easily from great logs with alerting (email / slack, ...).
They have handling for javascript which I am using on many sites (https://www.npmjs.com/package/raven-js).

**Comment by photopea** [comment]
Hi, it is usually not enough to know an error (exception) and the place in code where it happened.

We also need to know what exactly the user did before it, and the actual PSD or other file. Even if we had it all, it may take many hours of studying the data, to be able to reproduce the bug.

We have quite many bug reports from our users, so I think it is enough now.

**Comment by landsman** [comment]
Its not about these error. It can be some stupid mistake during fixing another error (typo etc) and you will don't know about it and hope that some user will report it. Github account is is a regular barrier for simple report.

**Comment by photopea** [comment]
I am too lazy to study the documentation, it can take me a whole day to implement it. I don't think it is worth it.

We have many bug reports over the email (which is shown in the top "info bar" above the editor).
