### ISSUE TITLE
SVG does not open correct in Photopea

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3670]
I have some SVG assets exported from Figma. One of them have shadow and blur on shape that is correctly showed in Firefox browser, but when I open it in Photopea in has no shadow and the circle shape hasn't set "feather" parameter in vector mask option.

When I open full project from .fig file, it looks like it should to look - with blurred glow (feathered shape) and shadow as a drop shadow effect.

Can you look on it?

BTW. Big congrats to you, because Photopea opened that SVG file better than Illustrator :)
[Group 311.zip](https://github.com/photopea/photopea/files/7020657/Group.311.zip)

**Comment by zcraber** [comment]
I faced a similar issue. 
File: [icon.zip](https://github.com/photopea/photopea/files/7021022/icon.zip)

**Inkscape** opens it correctly:

![image](https://user-images.githubusercontent.com/61133303/130223477-9000470e-0648-45f3-8a36-2e96f4cd2b5c.png)

**Photopea**:

![image](https://user-images.githubusercontent.com/61133303/130223426-1a69830d-54d3-4ed0-afbe-ce9414f96189.png)

**Comment by MichalSZZ** [comment]
@zcraber it was made in Figma too?

@photopea I have some other problems with figma files opened in Photopea.

Mix-blend-mode: color from Figma can't be translated as a color blend mode in Photopea. Cliping Masks doesn't work in my .fig file opened in PP. Do you want to send it by email?

**Comment by zcraber** [comment]
> @zcraber it was made in Figma too?

It's actually an icon designed by Facebook. Not sure which software is used.

**Comment by photopea** [comment]
I fixed the problem. Two SVGs presented here should look correctly in Photopea now.

SVG filters are a complex thing. Now, Photopea uses a "stupid" mechanism to detect a gaussian blur, drop shadow and inner shadow filters. 

If the image is too small in Photopea, enlarge it with Image - Image Size.

**Comment by zcraber** [comment]
> If the image is too small in Photopea, enlarge it with Image - Image Size.

Just a suggestion to this; in PSP (Paintshop Pro), while opening an SVG file they've got an option to enter a custom size which is handy.

**Comment by photopea** [comment]
I am afraid it would bother users too much, if we show them such window when opening every file.

I think users prefer to open a file and see it right away, which works perfectly for 99% of cases.

**Comment by zcraber** [comment]
> I am afraid it would bother users too much, if we show them such window when opening every file.

You probably didn't notice, I specifically mentioned **SVG** files.

**Comment by photopea** [comment]
Yes, I know. Personally, when opening a file, I want to see it right away, without setting any parameters.

Since your SVG has a viewbox of 16x16 pixels, I think it is right to show it as 16x16 pixels.
