### ISSUE TITLE
Ability to brush over transparency without darkening pixels underneath

### ISSUE THREAD

**Issue by cmot17** [photopea/photopea#3672]
If I use a 50% opacity brush, I get this, which is what I want:
![image](https://user-images.githubusercontent.com/25753364/130267279-039b9d59-5ab8-4c87-8a77-b09aa1e63de0.png)
Now if use the same brush again, it darkens the color where the two strokes intersect: 
![image](https://user-images.githubusercontent.com/25753364/130267354-c6dfb7e6-52d7-423a-960a-5f321dfca5c6.png)

This behavior is normally fine, but it would be very useful to have a mode where the intersection point would be the same opacity as the rest.

P.S Thank you so much for photopea, it's an amazing software!

**Comment by photopea** [comment]
The solution is simple! Keep the brush opacity at 100%, but set the layer opacity to 50% :)

**Comment by cmot17** [comment]
> 
> 
> The solution is simple! Keep the brush opacity at 100%, but set the layer opacity to 50% :)

Unfortunately this problem is appearing where I have a file that I need to edit with transparency in it already. So I am not able to do that.

**Comment by photopea** [comment]
Draw it into a new layer (brush opacity 100%), set the layer opacity to 50% and merge it with the old layer.

Brush opacity is a completely redundant feature. The same effect can always be reached by merging layers.
