### ISSUE TITLE
Justified alignment does not work

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3673]
![image](https://user-images.githubusercontent.com/11801254/130296030-231996c9-da20-4851-aa64-60859cfc176e.png)

The center alignment with justify, does not apply.

It is the same as center alignment.

**Comment by photopea** [comment]
You selected a mode, where each line of a paragraph is justified, except of the last one (the last line is aligned to the center).

I think in your case, each line of text is ended with a new line. So each your line is a separate paragraph (and it is the last line of a one-line paragraph). Am I right?

**Comment by photopea** [comment]
I am 99% sure I am right, so I will close it :)

**Comment by avagp** [comment]
sadly, you are right :P
