### ISSUE TITLE
templates

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#3678]
I didn't know that when I click on the template image it opens ( and I guess not everybody knows ) because there is no hover or at least an icon or anything that tells me to click the image

I think if you add this icon as a hover it will be clearer

![Screenshot (284)](https://user-images.githubusercontent.com/70863817/130452363-6eae4bb5-9766-44f4-928b-70ca89cae168.gif)

![screen-capture](https://user-images.githubusercontent.com/70863817/130452367-8dde7dc7-ec8a-4e2d-aa1c-b972fc3bed4e.gif)

**Comment by photopea** [comment]
When you hover over the image now, it says "Open XXY template"

**Comment by mustafaGFX** [comment]
it doesn't do anything with me

**Comment by mustafaGFX** [comment]
> it doesn't do anything with me
