### ISSUE TITLE
PDF export - texts are duplicated

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3679]
![image](https://user-images.githubusercontent.com/11801254/130489451-1865aa38-94f9-4e45-85ae-745ad5d3f0fa.png)

Can you see that the export preview shows 2 text overlayed?

**Comment by avagp** [comment]
weirdly, i closed and open photopea, and export it again.

Now it works fine.

Why this happens?

**Comment by photopea** [comment]
Save for Web in Photopea uses a built-in PDF viewer of your browser.

I think there is a bug in your built-in PDF viewer. I think you reported similar issues in the past.

What browser do you use? Can you update it? Is it a beta version of a browser?

**Comment by avagp** [comment]
It is chrome.
Is in stable v92

It is updated.

**Comment by photopea** [comment]
Is it Linux? Is it a built for your linux distribution (not a built from google) ?

**Comment by avagp** [comment]
It is chrome os.

**Comment by photopea** [comment]
Then, I give up :( But I can't see where could be a problem in Photopea.

**Comment by avagp** [comment]
it is weird.

If i can trigger it, i will totally report back.
I always do it.

But this time when refreshed i got it fine, so that is why i cannot go
further :P
