### ISSUE TITLE
Global angle problem

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#368]
I added some text
I added Drop Shadow with Angle 30 degrees and Use global angle is ON in Layer Style
Then I went again into Layer Style and changed that Angle to 127 degrees.
I Undo my last step (Step Backward)- Angle changes back to 30 degrees (OK)
I Redo (Step Forward) - Angle is not returned to 127 degrees. (it is still 30 degrees)

**Comment by photopea** [comment]
It was fixed. Thank you!
