### ISSUE TITLE
Blend Modes Stopped Working

### ISSUE THREAD

**Issue by c45kie** [photopea/photopea#3685]
I don't know what happened, but something went wrong when I was transferring a picture over to a tab and now none of the blend modes will work when I use the brush tool. No matter what I choose, it stays at normal. I try exiting out and refreshing my computer to maybe reset it but it's not working, and it's doing the same thing on a different web browser. I have no idea what to do.

**Comment by photopea** [comment]
I have to close it because of lack of details.
