### ISSUE TITLE
Gallery Plugin not responsive

### ISSUE THREAD

**Issue by yikuansun** [photopea/photopea#3686]
Hi!

I noticed that the gallery plugin can look awkward when the plugin window gets resized:
![image](https://user-images.githubusercontent.com/38194363/131054435-0299eb90-3634-4bc7-9d58-15c498cbe546.png)
I think there is a CSS property called `column-count` which is perfect for image galleries like this one.

Thank you!

Also, since different plugins have different ideal window sizes, maybe you could bring back the width & height from the old plugins API for setting the initial dimensions before manual resize?

**Comment by yikuansun** [comment]
@photopea 
> I still think plugin authors should do their best to make a plugin work at any resolution. 30% of our users use Photopea on phones, which often have tiny screens.

Hi Ivan, I can't help but notice that Peas Maker uses a larger window size, despite being a plugin. I'm not convinced that this feature should be limited to Peas Maker. My plugins are responsive, but most of them work better at larger window sizes (for some of them, the user will basically resize them immediately anyway). As for mobile support, many of my plugins don't work on mobile anyway. The Plugins menu doesn't even display well on my phone.

**Comment by photopea** [comment]
Ok, now, plugins should start at a width Max(300px, a third of a document canvas width)

**Comment by yikuansun** [comment]
@photopea Hi Ivan, thanks for the quick reply. Sorry I couldn't get back to you sooner. I don't think I was clear enough with my suggestion. What I meant is that the developer of the plugin should be able to choose the plugin's default window size using the `width` and `height` properties. This would mimic the behavior of every other panel in Photopea, which has an ideal size but can still be resized to the user's liking. The old size (300x485 or whatever it was) makes for a fine default if the `width` and `height` properties are omitted. Using 1/3 canvas width is strange because it will resize the plugin in unexpected ways (I had some plugins which were meant to be narrow but are are too wide now).

**Comment by photopea** [comment]
Some of our users have a phone, but others have 32" 4K screens. I think the creators of plugins should make their plugins work at any resolution. In the worst case, you can show a message "drag the corner of this plugin to enlarge it", if the plugin window is too small.

I am afraid that plugin creators would abuse this feature and always make fullscreen plugins, which could ruin the experience of users.

**Comment by yikuansun** [comment]
@photopea Thanks again for the fast reply. However, I am skeptical of the validity of your concerns. Several of my plugins and hxim's plugins work well in a small window, so developers will definitely not "always make fullscreen plugins." On the other hand, some of my plugins are terrible in a small window (notice that I made the Progen Flares 2 plugin use a popout window just because there was no way to scale down the UI). Those plugins don't work on mobile anyway.

I don't think you have to worry about plugin developers "ruining the experience of users." Frankly, some of the plugins in the gallery are not user friendly to begin with. These plugins just become less popular and don't get installed.

All I'm asking for is to make the plugin windows work the same as any other panel in the right sidebar: they can be resized, but by default they are displayed at an ideal size chosen by the developer. 300x485 is perfectly fine if the developer omits `width` and `height`. Plugins are just way more powerful (and user-friendly) if we developers have that extra bit of control.
