### ISSUE TITLE
iPad issues

### ISSUE THREAD

**Issue by MrVahidTT** [photopea/photopea#3688]
Hi, 80% of photopea features doesn't work with iPad mouse cursor and users should use their fingers to touch or drag elements. Please optimize for iPads. Thanks.

**Comment by photopea** [comment]
I am sorry, I don't have an iPad to test it.  What is "iPad mouse cursor"? Do you mean an external mouse?

Is your iOS updated? Maybe you are using an old iOS, which does not work well.

**Comment by photopea** [comment]
Is this an iPad? It seems to work quite well: https://www.youtube.com/watch?v=7tfiP8Wd1pw

**Comment by photopea** [comment]
I have to close it because of lack of details.
