### ISSUE TITLE
Czech diacritics do not work when exporting into PDF file

### ISSUE THREAD

**Issue by jankrnavek** [photopea/photopea#3689]
Czech diacritics do not work when saving content into a PDF file.
The error occurs when you create a new file, insert the sentence ''Příliš žluťoučký kůň se napil žluté vody'' and save as a PDF file. 
Thank in advance for fixing.

**Comment by photopea** [comment]
Sadly, Photopea can not do advanced text export in PDF at the moment. PDF was created a long time before Unicode or Open Type fonts.

Please, enable "vectorize text" when you export non-english text into a PDF.
