### ISSUE TITLE
cant resize any images

### ISSUE THREAD

**Issue by Ticketon1** [photopea/photopea#369]
cant resize any images using chrome or safari
os Sierra 10.12.6 (16G29)

used to work now it wont

what can be done?

THX!

**Comment by photopea** [comment]
Hi, how do you resize images with Photopea?

**Comment by Ticketon1** [comment]
The diagonal cursor that allows fee transform and then press shift to keep proportion.

**Comment by photopea** [comment]
I am very sorry for that. It is fixed now.

**Comment by Ticketon1** [comment]
Awesome! Thank you so much.
