### ISSUE TITLE
Free transform

### ISSUE THREAD

**Issue by Ispenttoomuchtimemakingausername** [photopea/photopea#3690]
I can't free transform without it auto selecting a layer for me, so I can't flip a text layer I need to.

**Comment by photopea** [comment]
What exactly should I do to see the bug happen?

**Comment by Ispenttoomuchtimemakingausername** [comment]
I can't free transform at all. I try alt-ctrl-t and it selects a random layer. I did edit-transform-flip and it flipped the other layer. I couldn't free transform the layer I wanted to.

**Comment by photopea** [comment]
You should select a layer or multiple layers in the Layers panel. See here: https://www.photopea.com/learn/layers .

Are you sure, that thre Free Transform starts on another layer than the one that is selected?

You can also use "auto-select" of a move tool to select layers by clicking them. But naturally, it works only on layers that are not completely covered by another layer.

**Comment by Ispenttoomuchtimemakingausername** [comment]
Got it working. I think it was something to do with the file because it would select a layer that I could see in the image but I don't think it actually existed...

**Comment by photopea** [comment]
Ok I am glad it works :) you never know if an image contains one layer or 100 layers, until you look into the "Layers" window.

**Comment by Ispenttoomuchtimemakingausername** [comment]
Right thanks for your time
