### ISSUE TITLE
you have an ad literally covering up menu options

### ISSUE THREAD

**Issue by daknapp0773** [photopea/photopea#3691]
https://i.imgur.com/JNqtLA2.png

That cannot be intentional? Because if so...holy crap

**Comment by photopea** [comment]
I think you have a browser extension, which inserts such ads into Photopea. Let me know if it happens in a browser with all extensions disabled.

**Comment by daknapp0773** [comment]
I disable those for photopea. Not the case here

**Comment by photopea** [comment]
I am sure if you disable all extensions completely, the problem will disappear.

**Comment by daknapp0773** [comment]
My man...I disable them on your site already. I ran adblock until you requested the whitelist, which I then did by just disabling all extensions on your page. You have an errant ad my friend. It is not an extension causing it.

**Comment by MichalSZZ** [comment]
I am sure that Photopea said true. That type of baner does not exist on photopea. Their ads are showing only on the right side and they are not floating as yours.

And do not add Photopea to whitelist only for some of adblocking addon. Try to turn off for a moment all of your addons. One of them (who has nothing to do with ads) can put it own banners on sites.

Mayby your computer is infected? 

Did you tried open photopea on other browser? Microsoft Edge, Chrome, Opera for example?

**Comment by daknapp0773** [comment]
I already stated that I did this. I have removed ALL extensions already.
They were removed for photopea when I initially got the ad. It is not an
extension causing the issue, I don't know how to be more clear.

**Comment by avagp** [comment]
i don't have that ad on my side.

I really think it is something with your browser daknapp  :/

Did you tried open it on incognito to see if there is any difference?

**Comment by daknapp0773** [comment]
I haven't had it since, but I have adblock back on :( nothing about my
browser would have caused it my friend. I just wanted to let you know what
you have. Nothing on my machine is creating walgreens ads, and if it was,
it would be happening on other sites too. It has literally been only your
website. I hardly whitelist anyone to even get an ad. Take that as you
wish, but again, it is not my browser that created the ad.

**Comment by MichalSZZ** [comment]
You are on photopea.com? Not on any other site adress like freeonlinephostoshop.com that looks exactly like photopea?

Can you enter photopea.com on other computer, tablet or phone and check it there?

I have use photopea from 3 years or more and never was so agressive ads there.

**Comment by photopea** [comment]
Can you make that ad appear again? When it appears, can you right-click Photopea > Inspect Element > Console, there should be a line with a number 0, 1 or 2. What number do you see?

Can you repeat it multiple times? Is it true, that when the ad appears, the number is always e.g. 1? (so the ad never appears for numbers 0 and 2) ?

**Comment by photopea** [comment]
I have to close it because of lack of details.
