### ISSUE TITLE
Spammy sites embedding photopea

### ISSUE THREAD

**Issue by josephrocca** [photopea/photopea#3692]
* https://www.freeonlinephotoshop.com/
* https://www.freephototool.com/
* https://fixthephoto.com/online-gimp-editor.html
* ...

**Comment by photopea** [comment]
Right now, anyone can insert Photopea into their websites. Do you think we should stop it?

I wonder why do people prefer using these sites instead of Photopea.com , even though they see, that it is named "Photopea" there, and they could try to look for it directly.

**Comment by josephrocca** [comment]
> Right now, anyone can insert Photopea into their websites. Do you think we should stop it?

Up to you of course, since it's just a one-header change in this case. I have dealt with people doing similar things to my sites - even to the point of copying all my HTML/JS including my Google Analytics tags, which is how I found out - there was unusual data flowing into my analytics. In the end I wasn't able to stop them - they lied to reverse the DMCA takedown and I wasn't prepared to go to travel overseas and get a lawyer and go to court.

If you leave it too long, then they can get a significant share of your traffic despite giving a worse user experience. At that point it can become harder to get them to stop because they're more incentivised to work around your blocks. Currently, according to SimilarWeb, it looks like they're getting at least a few hundred thousand hits per month in aggregate - so not a large fraction of your traffic, but certainly non-trivial.

They get traffic despite their spamminess simply because Google is not as good at ranking results as you'd think - e.g. your site should obviously rank 1 for "online gimp editor", but that `fixthephoto.com` page does instead due to their SEO "hacking". You could produce several landing pages (one for each obvious keyword like "online ____ editor") and you'd probably be able to claw back the traffic, but maybe that is time that could be better spent improving your app.

You could just put a popup in your app if you detect that it's running in an iframe - telling users that they can go to photopea.com for the "full" version, or something like that. Maybe disable a feature or two as well - enough to prod the user towards your site, but not enough for these spammy sites to go to the effort of, e.g. copying your HTML/JS and trying to remove any barriers that you might have put in the way of a simply copy-paste of your app (I suggest adding these if you haven't got any).

Another option is to just bit the bullet and create a few landing pages for the keywords they're targetting. That's not fun, but it might be less effort in the long term.

I'll close this now - just wanted to let you know :+1:

**Comment by photopea** [comment]
Thanks. I know about all these websites, as I see them in Google Analytics. None of them has more than 20,000 pageviews a month.
