### ISSUE TITLE
Editing PSD file

### ISSUE THREAD

**Issue by Betty40** [photopea/photopea#3693]
Hi there,
I am saving my customizable image in PSD and SVG format. I wish to open this file at a later date and add text to it. In my original image I have a font and colors, effects. How do I customize this image at a later date using my SVG or PSD file? I wish to add name of child for example but want the program to know what text, color and effect was used in the original image..How do we do this? Why can't photpea save our project history? That way we can go back and edit same project over and over without losing all our work. I need to personalize projects at later dates... Can you help me please?

**Comment by photopea** [comment]
Save your file as a PSD (not SVG) in order to keep all the parameters.

After you open a PSD file again, you should see the same thing as when you exported that PSD. See here: https://www.photopea.com/learn/opening-saving

**Comment by Betty40** [comment]
Yes, I know. I see the same file but I wish to edit that same image with
text. I have the header text on image and I wish to add personalization of
the name of the child to each new image. I wish the name of the child I am
adding would recognize the text colors, gradient, effects like in the PSD
file I saved.
This is what i don't know how to detach the text layer saved in psd to edit
and copy.
Elisabeth

**Comment by photopea** [comment]
I don't understand what you need :(  If you took a photo of a newspaper, and open the photo in Photopea, the text (in the newspaper) is not editable by default.

Maybe ask at our Reddit: https://www.reddit.com/r/photopea/

**Comment by Betty40** [comment]
Kingdom-Kub-Girl-PSD-Pink-Font-NAME-PSD.psd
<https://drive.google.com/file/d/10WEjSWDbxFBgykJyMiNx2p5cdCxey2ib/view?usp=drive_web>


Hi there,
here is the image with text I saved in PSD format. See the text, it has
color, effects..etc.
Once it is saved in PSD, I don't know why I can't ungroup the layers again,
so that I can add the name of the child and keep text exactly same font ,
colors, text effect.
There is a way to do it in photoshop by ungrouping layers. How do we do
this in Photopea, so I can edit text and keep all text effects?
Thanks,
Elisabeth

**Comment by photopea** [comment]
I can not access your file. Could you give me the access?

**Comment by photopea** [comment]
I can open your file in Photopea and I can edit text layers.

What do you mean by "ungrouping layers"? Could you send me a screenshot of what you see? Please, reply on a webpage https://github.com/photopea/photopea/issues/3693 , because email replies can be broken.
