### ISSUE TITLE
Safari shows black background

### ISSUE THREAD

**Issue by twa96** [photopea/photopea#3698]
Hello

I have discovered a major problem using Safari. The pictures are showing up on my websites as they appear in Photopea - with the black background which shows I have removed the original background. 

![31155080-1545514643887](https://user-images.githubusercontent.com/33432900/131373837-967b463f-f611-4904-a707-291701514ad5.jpg)

This does not happen with Firefox and Chrome. 

Regards

**Comment by photopea** [comment]
I do not understand. Do you have a PNG image in a website, and it looks different in every browser? I think the problem is not related to Photopea. If the PNG is not corrupted, it should be displayed always. the same way.

**Comment by twa96** [comment]
I use photopea in shopify. The above image is what is showing in my website when I have removed the background and saved to shopify. 

Am i supposed to save as png or jpeg? 

The above only shows in the Safari browser. Firefox and Chrome does not show the above.

**Comment by photopea** [comment]
Is your Safari updated? Try to update it, or report this bug to Apple. PNG files can have transparency, but not JPG files.

**Comment by twa96** [comment]
Its updated. Have sorted out what to do. Export as PNG then upload again. 

Thanks for your time.

**Comment by photopea** [comment]
I don't know what exactly you are doing. But maybe something modifies a PNG file before it gets to your server.
