### ISSUE TITLE
Shapes that are not live shapes

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3699]
It is possible to be because i had imported this file from a PDF, i have redone all the shapes, but one.

![image](https://user-images.githubusercontent.com/11801254/131417104-4e392869-8c81-4250-a1c9-2a072f129c45.png)

The etiqueta layer of the black&white horizontal logo, does not have Live Shape properties enabled.  :/

[Logo Pasalo Chancho (nuevo).zip](https://github.com/photopea/photopea/files/7080053/Logo.Pasalo.Chancho.nuevo.zip)

**Comment by photopea** [comment]
Photopea can not detect a shape in a PDF or EPS now, and convert it to a live shape.

Is that what you mean? Detecting live shapes in PDFs?

**Comment by avagp** [comment]
I am not suggesting nothing, but maybe converting shapes into live shapes
will be a good idea.

**Comment by avagp** [comment]
This still is something i would like to have.

Like you said, detecting live shapes or converting them into live shapes, automatically or by a menu

**Comment by avagp** [comment]
Is this too difficult?

**Comment by photopea** [comment]
It is easy, but I am a bit overwhelmed with other work :(

**Comment by avagp** [comment]
You haven't found a developer to help you yet? :(

**Comment by photopea** [comment]
I found one, but I told him to work on InDesign import, and he has been doing it for a month now, and it is probably still far from done.

**Comment by photopea** [comment]
The InDesign support will probably cost me around 5 - 10 thousand USD, I don't know if it is worth it :/

**Comment by avagp** [comment]
Ufff.

Hope it is worth. That'll be a mayor step towards competing with Adobe Cloud

**Comment by avagp** [comment]
Now that you have InDesign ready, can you take this issue? 🙃

**Comment by avagp** [comment]
👀

**Comment by photopea** [comment]
I have implemented this feature :) Photopea should detect live shapes in all vector formats (pdf, svg, ai, sketch, xd, figma, ...).

Photopea can detect a circle, an ellipse, a rectangle, a rounded-rectangle, as long as they are not rotated. The corner radius of a rounded rectangle must be the same for all corners. You can try it with the PDF below
[shapes.pdf](https://github.com/photopea/photopea/files/7981550/shapes.pdf)

**Comment by avagp** [comment]
Yoo-hoo!

Thanks!
