### ISSUE TITLE
Export to PDF - Stroked text gets a square

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3701]
![image](https://user-images.githubusercontent.com/11801254/131708755-cc11e1bb-dd89-49bb-8c55-177a1c7d86d8.png)

Look at the second CHIQUES

Here is the PSD:
[chiques (2) (1).zip](https://github.com/photopea/photopea/files/7092880/chiques.2.1.zip)

**Comment by avagp** [comment]
This is still happening :/

The stroke effect on the text is not exported.

**Comment by photopea** [comment]
it is fixed now :)
