### ISSUE TITLE
Feature request: Macro recording for scripts

### ISSUE THREAD

**Issue by Norgus** [photopea/photopea#3703]
If it is possible, it would be very handy to be able to press a record button for scripts, perform the actions, then have the script to tweak/base more complex scripts upon.

It would also be very nice if it were possible to convert already recorded action sets to scripts.

**Comment by photopea** [comment]
Our scripts and actions are based on scripts and actions in Adobe Photoshop.

Do you think every Photoshop action could be converted into a script? I am not that sure about it.

**Comment by photopea** [comment]
I have to close it because of lack of details.
