### ISSUE TITLE
Page not comming up

### ISSUE THREAD

**Issue by HARESHFC** [photopea/photopea#3705]
The page is glitched I tried everything!
![image](https://user-images.githubusercontent.com/90001724/131898357-650ab923-4914-412b-8944-8e4e8f0335ba.png)

**Comment by photopea** [comment]
Could you try these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details :(
