### ISSUE TITLE
The default width of the panel is sometimes a bit narrow

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3706]
With portrait mode on my device, 2 textboxes have gone to another line.
![Screenshot_20210903_183527_com android chrome](https://user-images.githubusercontent.com/79258245/131994797-759ab5dc-ba4a-473a-8cd2-795a38967168.png)

With landscape mode, there is no this problem.

**Comment by photopea** [comment]
I made the Levels window resizable :)
