### ISSUE TITLE
Photopea does not use all page space

### ISSUE THREAD

**Issue by Diegovsky** [photopea/photopea#3707]
For some reason, there is some chunk of the screen not being used (right side):
![image](https://user-images.githubusercontent.com/46163903/132043436-9b4a8d91-4805-433a-8405-03fc2e525ac5.png)

I'm on firefox 91.02.

**Comment by photopea** [comment]
There should be advertisement on the right side. Please, watch our ads, we would not exist if people did not watch our ads.

You can also pay 10 USD to hide ads for 90 days (press Account at the top).

**Comment by Diegovsky** [comment]
Oh sorry, I thought my adblock was disabled. Thanks for the quick response.
