### ISSUE TITLE
I cannot load photopea

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3708]
:/

I don't know what happened.

I have tried this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

Don't...

These are my extensions (i have none enabled, ever)
![image](https://user-images.githubusercontent.com/11801254/132074241-7c7e67e9-af85-4561-b162-fc68a5933d28.png)

I can still reproduce my bug on incognito mode.

How To Repro:
1.- Enter photopea.com on incognito
2.- click on account > log-in
3.- Select Google and enter your account
4.- It will redirect, but nothing will change, you won't be logged in.
5.- Refresh
6.- Photopea won't load:
![image](https://user-images.githubusercontent.com/11801254/132074339-ea9f99fc-f2fc-4726-8d73-ab8a7245ce77.png)

**Comment by photopea** [comment]
I am very sorry :(  it is fixed now.  It happened only to those who were members of a team.

**Comment by avagp** [comment]
Because I deleted all the site info, I lost my team leader email.

Can you please share it to me again to ***@***.***?

Thanks Ivan!

**Comment by photopea** [comment]
Hi Alvaro, these settings (your team leader, etc) are saved at our server. I wonder how did you get them deleted.

You are in my team: ivan.kuckir@gmail.com

**Comment by avagp** [comment]
Thanks!  :D
