### ISSUE TITLE
Tools and selection not working properly

### ISSUE THREAD

**Issue by Amber-Ozen-and-Ibarakazen** [photopea/photopea#3709]
When attempting to use the text setting and healing tools, the background layer was selected and transformed. unable to reselect the proper layer without hiding all layers behind it.

I have no idea how it happened or why it happened, this was the first time. How I fixed it was by switching to a new window and back again.

**Comment by photopea** [comment]
I think you enabled the "Auto-Select" of the Move tool at the top.
