### ISSUE TITLE
Pen errors

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#371]
I just tried to use Pen or Free Pen and it shows this error
->
Uncaught TypeError: this.K[a].pv is not a function
    at NK.rs (pp.js:6036)
    at zF.NI.l (pp.js:6)
    at zF.ze.l (pp.js:4162)
    at zF.pv (pp.js:4181)

**Comment by hxim** [comment]
All tools where there is more under one button does this probably caused by your fix from #363

**Comment by photopea** [comment]
Ok, I fixed the switching of tools. I suppose Pen errors was also related to this problem.
