### ISSUE TITLE
log in / account issues

### ISSUE THREAD

**Issue by svlringen** [photopea/photopea#3710]
i'm currently having what seems to be log in / account issues with both the site and app. i'm already logged into my account for photopea, however i'm unable to click on most of the tools and many other features do not appear. i have opened photopea in incognito mode and it works fine. i do use an adblocker, however, i have whitelisted the site since i purchased the 90 day premium. it was working fine 2 days ago and then suddenly it looks like this when i opened the app. 

i have some other extensions downloaded, but i've been using them alongside photopea for over a year and i've never experienced this before.

![Screenshot 2021-09-04 102045](https://user-images.githubusercontent.com/73749696/132103173-01d47a8f-9962-4a6d-81f9-4de15b78c4bb.png)

**Comment by photopea** [comment]
Hi, that is weird. Just in case, could you temporarily disable all your extensions and try Photopea again?

**Comment by svlringen** [comment]
i have logged in without the extensions and i'm still encountering the same
issue. photopea seems to work when i'm not on my account. everything loads
fine when i am not signed in, but then photopea begins to "bug out" once i
do.

**Comment by photopea** [comment]
I am soooo sorry. The problem was on my side. It should all be fixed now.

**Comment by svlringen** [comment]
it's working perfectly now! thank you so much for your help.
