### ISSUE TITLE
Free transform controls issue 

### ISSUE THREAD

**Issue by antonitwo** [photopea/photopea#3711]
I can't adjust the size of an image because it appears this squares, what can i do? 
![image](https://user-images.githubusercontent.com/90108755/132104013-9dff27a5-b0db-4b7b-b9f4-5b323cc5b997.png)

**Comment by photopea** [comment]
Could you send me your file to support@photopea.com , so that I can try to reproduce this issue myself?

I need to make it happen on my computer, but I don't know how.

**Comment by alexsaman** [comment]
this problem is on PC you cannot do CTRL T cause it opens a new window. 
and when you import an image there is no handler

**Comment by photopea** [comment]
" it appears this squares" - what squares?

Use Photopea at www.Photopea.com
