### ISSUE TITLE
Shut down

### ISSUE THREAD

**Issue by Betty40** [photopea/photopea#3712]
For no reason, your program shut down on me 3 times today. I lost all my work. I was trying to save it and the whole thing shut down on me :(

**Comment by photopea** [comment]
How much RAM do you have in your computer? What is the resolution of your documents? Is your web browser updated?

**Comment by Betty40** [comment]
My computer is 2 years old. The ram is high. I am working with png 4500px and setting them to 300dpi when I save. But it crashed on me when I wanted to save the psd. It did that several times. Is 300dpi really 300,000? That what shows up. Is that the highest quality I can set it to? Will my image quality be excellent for print on demand?

**Comment by photopea** [comment]
Browsers usually "kill" Photopea when they think it uses too much RAM, or if there is not enough free RAM (e.g. you have too many tabs opened in the browser). There is nothing we can do about it :(

Your documents are probably too large. Try to save your work as a PSD at least once an hour, especially when you work with large documents. Photopea should offer you to save as a PSD, if you haven't saved your work in a long time.

I recommend 16 or 24 GB of RAM for working with large documents.

**Comment by Betty40** [comment]
Yes, I had many tabs opened when working and my files are large too. Thanks for the advice!! The free transform works now, so I was able to edit the picture with the baby lion and add the name I wanted! I wasn't sure how to work the Free Transform but now I do. I work with photopea every day! Great software! :) Thanks for your help :)

**Comment by photopea** [comment]
The Free Transform is described here: https://www.photopea.com/learn/free-transform  I really recommend reading it.

I think that one hour of reading Photopea.com/learn will save you at least 50 hours of struggle while using Photopea in your life :)
