### ISSUE TITLE
History, Saved Work Files

### ISSUE THREAD

**Issue by Betty40** [photopea/photopea#3714]
Is there a way to view a history of our last work done on this photopea software? I am a paid member and I thought I would see my past work by becoming a member? Can you create a section we can click that would remember our past work? This way, we could go back in that file and continue our work?

Please create this option, this would help so many people :)

**Comment by photopea** [comment]
You can go back only within a "session". Once you save your work as a PSD, only the latest state is saved.

Have you tried to save your work every 15 minutes as a separate PSD? Then, you would have many versions of your file.

Also, you can create a copy of a layer and hide it (the eye icon), in case you need the original layer in the future.

**Comment by photopea** [comment]
If you expected to have this feature (editing history saved inside a PSD), I can refund you (as we do not have it and it would probably make PSD files 10x larger).

**Comment by Betty40** [comment]
No refund needed. I'm enjoying the software. I did think paying would help me save my files but it's o.k. I will do what you said and save more often :) Thank you for your help

**Comment by photopea** [comment]
ok :) keep copies of layers in your document, in case you want to return to them in the future.
