### ISSUE TITLE
Native eye dropper in Chrome

### ISSUE THREAD

**Issue by ThomasOrlita** [photopea/photopea#3715]
Chrome now supports the [Eye Dropper API](https://github.com/WICG/eyedropper-api). This seems like an interesting feature that could be integrated into Photopea.

    await new EyeDropper().open()

**Comment by avagp** [comment]
but when click and hold eye dropper it is kinda the same?

Or no?

**Comment by photopea** [comment]
This EyeDropper API should allow picking a color from any pixel of the screen (even outside a web browser). 

It is not available in Chrome yet. Also, I think you can just take a screenshot and paste it into Photopea. So I will close it for now.
