### ISSUE TITLE
Vertical aligned text

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3716]
I can assure that there is an option for this, but i cannot find it.

When i am using a text box, i have the option to align the text horizontally, but not vertically.

Besides using: 
![image](https://user-images.githubusercontent.com/11801254/132400022-64d7eadf-7184-4672-8d31-2248d43eb85b.png)

There is an option like how Powerpoint vertically align text within text box??

**Comment by photopea** [comment]
As we store documents in the PSD format, we can offer only features avaliable in it. And in PSD, text can be aligned only in one axis (the axis of a baseline) :(

**Comment by avagp** [comment]
buuu

it is fine.

there is plenty of workarounds
