### ISSUE TITLE
Layer Style child windows

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#372]
I open Layer Style window and from it I open Color Picker or Countour Editor.
Then I can close Layer Style window and Color Picker/Contorur Editor is still open.
If I change something in that ColorPicker/Contorur Editor and hit OK it is applied on Layer but it is not recorded in History so you can't undo your action.

**Comment by photopea** [comment]
I fixed it. When there are multiple windows open, only the top-most window accepts mouse events.

Thank you!
