### ISSUE TITLE
Type Tool: Letter after `f` gets misplaced / disappears when exporting as PDF

### ISSUE THREAD

**Issue by yvnbunag** [photopea/photopea#3720]
Given the following text:
![editor](https://user-images.githubusercontent.com/42926334/132507165-a188bcf8-dc64-4c73-aabb-fe762d2c732b.png)

When exporting as PDF, the letters unusually gets misplaced on the export view and when the file gets exported:
![pre-export](https://user-images.githubusercontent.com/42926334/132507388-5fe83e97-1cdf-4877-a262-59deb1bbf034.png)
![exported](https://user-images.githubusercontent.com/42926334/132507389-9de54ad3-e3a0-47dd-9d14-afd82dddf42e.png)

Ticking the "vectorize text" option on the export modal fixes the issue, but there may be cases where the text is ideal to be preserved so that it is select-able and copy-able (e.g., URLs, email addresses).

The texts in the given example are the only ones I have encountered.

**Comment by photopea** [comment]
Could you copy-paste your text here on Github? Is the "fl" two characters, or one special character?

When I type "Workflow" in Photopea, it is exported to PDF correctly.

**Comment by yvnbunag** [comment]
Here are the words:
- Workflow
- Proficiency
- Full Professional Proficiency

One thing I have noticed is it doesn't seem to be dependent on the current font used, since exporting to PDF without vectorizing the text falls back to the default font (not sure what font).

The browser I use is Chrome Version 91.0.4472.164 (Official Build) (64-bit) for Ubuntu 19.04.

Attached is a PSD file of the sample:
[letter-shift.zip](https://github.com/photopea/photopea/files/7132644/letter-shift.zip)

BTW this issue is not urgent on my end, as there are workarounds:
- Vectorizing text
- Correcting the generated pdf in https://www.sejda.com/pdf-editor

Thank you for the free software!

**Comment by yvnbunag** [comment]
Additional Info - Bug may be related to letters following `f` (in this case, `fi` and `fl` being combined into a single ligature:
https://user-images.githubusercontent.com/42926334/132628624-12452729-730f-42b5-b8c0-45785f7a2078.mp4

**Comment by photopea** [comment]
When I type these words in Photopea, and export a PDF (without vectorizing text), the text is displayed correctly.

I think the bug can be in your PDF viewer. Can you open the PDF in some different PDF viewer? Could you share your PDF with us here?

![image](https://user-images.githubusercontent.com/15955558/132655058-be8c1e4b-27cf-4eca-968f-449eed9c46f8.png)

**Comment by yvnbunag** [comment]
It is consistent across these viewers:
- Chrome Browser
- Ubuntu Document Viewer
- WPS office (mobile)

I was able to replicate the bug in other environments as well:
- Firefox Browser, Ubuntu
- Chrome Browser, Windows, First time use

Additional info: here are the fonts I used:
- Roboto
- Raleway
- Bebas Neue

See attached generated PDF:
[letter-shift.pdf](https://github.com/photopea/photopea/files/7135095/letter-shift.pdf)

**Comment by photopea** [comment]
Ok, I am very sorry, it is fixed now.

Note, that Photopea can not insert fonts into a PDF at the moment. But we are planning to add this feature in the future.

**Comment by yvnbunag** [comment]
I was able to confirm that the fix was applied.

No worries, thanks for looking into it!

> Note, that Photopea can not insert fonts into a PDF at the moment. But we are planning to add this feature in the future.
This would be a nice feature, thanks!
