### ISSUE TITLE
content aware fill

### ISSUE THREAD

**Issue by Jeefr** [photopea/photopea#3721]
Add content aware fill
Green indicates the places from which the program copies Remove an object

Places that are not colored green The program does not copy anything from them

This helps the user not to have a problem removing objects in the image

https://youtu.be/Is5B-6t3GZ4?t=717

![IMG_20210909_114743](https://user-images.githubusercontent.com/86309220/132654485-b861c03f-ff3e-473c-bbc1-be8c1489cdd8.jpg)

**Comment by photopea** [comment]
Sorry, I don't know how to do it :(  Have you tried to select the object, and then,  Edit - Fill - Content Aware?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
