### ISSUE TITLE
weird page layout

### ISSUE THREAD

**Issue by endigma** [photopea/photopea#3722]
chrome 91, also tested with qutebrowser which is blink of some sort.

![image](https://user-images.githubusercontent.com/34945114/132748050-e874df2c-a65a-4230-8303-62992dec5e32.png)

seems to be related to this element

![image](https://user-images.githubusercontent.com/34945114/132748158-c04fe269-bbc7-41fc-8935-50f7d04eb4d0.png)

deleting the div the empty space still shows

**Comment by photopea** [comment]
Hi, there should be ads on the right side of Photopea.

Please, watch our ads. Since almost nobody wants to pay for Photopea Premium, ads are the only reason we still exist. Photopea would go bankrupt a long time ago, if everyone was hiding ads as you do.
