### ISSUE TITLE
Feature - Export as WMF

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3723]
Hi!

I have had this doubt a couple years ago, but i would like to check again.

It is possible to Photopea to export WMF?

**Comment by photopea** [comment]
Hi, the WMF format can be fully replaced by more popular formats, like SVG or PDF.

Are you sure that your software can not load SVG or PDF? How old is that software?

**Comment by avagp** [comment]
Powerpoint years old.

PPT and google slides only supports WMF vectors.

That's why i am asking :)

**Comment by photopea** [comment]
I was not able to insert SVG, EMF or WMF into Google Slides. How sould I do it?

I don't have Office, but according to this, PowerPoint can work with SVG: https://blogs.articulate.com/rapid-elearning/edit-svg-graphics-powerpoint/

**Comment by avagp** [comment]
I convert the EMF to WMF on cloudconvert.com

Then upload the WMF to Google Drive.

Open it as Google Draw.

Now i can insert it into Google Slides.

**Comment by photopea** [comment]
Are you sure? I loaded a WMF file to Google Drive, I double-click it, but there is no default app to open it.

**Comment by avagp** [comment]
Here is a video:
[Screen recording 2021-09-12 06.21.23.zip](https://github.com/photopea/photopea/files/7149337/Screen.recording.2021-09-12.06.21.23.zip)

Here is a WMF file:
[example wmf.zip](https://github.com/photopea/photopea/files/7149334/example.wmf.zip)

**Comment by photopea** [comment]
I still can not open a WMF in Google Drive :( Double-clicking says "No preview available".

Please, ask Google to support modern formats like SVG or PDF. Or use other tools to convert SVG to WMF / EMF.

**Comment by avagp** [comment]
Thanks for trying though!

I have asked a couple of times.

:)
