### ISSUE TITLE
Provide a cloud storage

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#3726]
We could provide a tiny storage (50 - 100 MB) to users of Photopea. It would not be limited to PSD files, but users can upload any files. Premium users would get more storage (gigabytes).

We could offer a mechanism for sharing files (allow others to view files or even modify them).

**Comment by oriol003** [comment]
Would be great for storing assets such as fonts and actions for a team.

**Comment by flaneurette** [comment]
Would be great... would be useful to automatically save a PSD every minute or so, so that work can be recovered...

**Comment by avagp** [comment]
good idea!

**Comment by photopea** [comment]
The problem is, that if your upload internet speed is 1 Megabit, saving a 120 MB file would take around 2 minutes (while it can be saved to a device in 2 seconds for SSD).

There is also a mechanism for giving a website a direct access to a specific folder in your device. Then, Photopea can read from the folder or write into it without asking you (without any open / save dialog). After you open Photopea.com , you would see all files of that folder right in front of you. You can click and open them directly.

**Comment by photopea** [comment]
We have implemented a Peadrive!

**Comment by TheRadicalDreamer** [comment]
You are really skilled Ivan!
