### ISSUE TITLE
When Super Duper Secure Mode Enable is enabled in Edge Chromium appears Your Browser is too old, please update it.

### ISSUE THREAD

**Issue by celphogeek** [photopea/photopea#3728]
Hi photopea team,

Today I'm here to share a problem with photopea, in Microsoft Edge we have to the option Super Duper Secure Mode in edge://flags, when enabled we see Your Browser is too old, please update it. Here's the screenshot
![image](https://user-images.githubusercontent.com/29079236/133174850-6c4c70d0-a054-4d11-88a5-0a62736b85e0.png)

When we restore this option to default mode, photopea just works. 

Here's what the Super Duper Secure Mode do 
Disables the JIT and enables new security mitigations to provide a more secure browsing experience.

In firefox if you disable JIT and other javascript components appears this message too. But for now, the focus of the post is for Edge Chromium, I'm using the latest version 93.0.961.47.
![image](https://user-images.githubusercontent.com/29079236/133175062-1fdf12e9-65fe-4b6f-a883-7a21dd17658d.png)

**Comment by photopea** [comment]
I think by "secure mode", they mean disabling Javascript.

Photopea is a software, and it requires executing some advanced code, which is written in Javascript in our case. Without the ability to run Javascript, we can not provide any advanced features. So it is up to you, if you want to allow Javascript, or stay "secure" and ban Javascript. 

But personally, I think Javascript is not dangerous, and I have it enabled in my browser.

You should still be able to e.g. read our manual without Javascript: https://www.photopea.com/learn/
