### ISSUE TITLE
Payment made but not reflecting

### ISSUE THREAD

**Issue by rashmin-sejpal** [photopea/photopea#3729]
Dear Support Team, 

Account: nitin.wadavale@oneinsure.com 

We have made the payment for US$ 10 for 90 days subscription. At the end of the payment we received the below message.

![image](https://user-images.githubusercontent.com/40287716/133198619-0043554c-68ec-46d2-84d9-90ccad46a855.png)

Can you please credit the account.

thanks
rashmin

**Comment by photopea** [comment]
Hi Rashmin, I do not see any "strange" payments in our Paypal in the last two days.

Could you share a screenshot of the transaction in PayPal? Or at least tell us, what is your paypal name and when the transaction happened?

**Comment by rashmin-sejpal** [comment]
You are right….there is no charges on our credit card statement.

 

Thanks for the prompt response !

**Comment by photopea** [comment]
ok, I will close it now. Let me know if you ever have any other problems.
