### ISSUE TITLE
Can't login va Chromebook/Google using FB - HELP!

### ISSUE THREAD

**Issue by MsHeatherGrace** [photopea/photopea#3730]
Anyone else have this problem? I emailed support@photopea.com, so if you're THEM and reading this, please help me resolve asap. Thx, Heather :)

**Comment by photopea** [comment]
Hi, what happens when you log in with Google or Facebook? Can you show me a screenshot of what the problem looks like?

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by MsHeatherGrace** [comment]
What are you talking about? Can't login via Chromebook/Google computer using FB login. Doesn't go anywhere.
    On Sunday, September 19, 2021, 03:17:57 AM PDT, Photopea ***@***.***> wrote:  
 
 


I have to close it because of lack of details :(

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by photopea** [comment]
Can you share a screenshot of what you see after you choose "Facebook" to log in?

Please, reply at https://github.com/photopea/photopea/issues/3730, do not send emails to GitHub.

Also, I think you might have browser extensions, which are breaking Photopea. Try to disable them all temporarily.
