### ISSUE TITLE
Issue: The default selected option in properties panel is Mask when a new adjustments layer is created

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3731]
![screenshot_20210919_220424](https://user-images.githubusercontent.com/79258245/133930556-d8e30e26-ac14-4bb4-96e1-85774d353f0a.jpg)

It should be Layer.

**Comment by photopea** [comment]
When you make an adjustment layer in Adobe Photoshop, the raster mask is selected, too. We need this to be albe to run some Photoshop ATN actions.

I fixed it, if a current layer is an adjustment layer, the default active item in Properties is "Layer", not a "Mask".
