### ISSUE TITLE
Menu block when the Type tool is used

### ISSUE THREAD

**Issue by WRocha33** [photopea/photopea#3733]
Hi,

I understand that my access is only free, but is there a way that there's not going to be an error when the Type tool is being used?

There's a black rectangle that shows, every time I tried to use the Type tool. 

Is there's a way to resolve this?

Thank you.
![Photophea error](https://user-images.githubusercontent.com/66781113/133933793-8683dff9-9b15-459e-8dc3-f95020af747c.jpg)

**Comment by photopea** [comment]
Hi, can you try the usual steps? I am 99% sure it will help! https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because if lack of details.
