### ISSUE TITLE
Ad Renders Site Unusable

### ISSUE THREAD

**Issue by theeaglexiii** [photopea/photopea#3734]
For the past week I keep getting 1 specific ad that renders Photopea unusable.

It 'uses' one space of the three ad squares on the side of the site, and is only visible within that square, but it is full screen behind the website. Clicking anywhere on the screen where the ad is 'behind' takes me to the ads website (fwiw it's jersey.com) When the add closes, Photopea becomes usable again, but it reappears anywhere from 30secs - 3mins after stopping. I literally can't get any work done like this. I can't change my ad consent to stop it reappearing.

I know this is a specific issue with whoever supplies your ads but it still needs to be sorted.

Many thanks

**Comment by photopea** [comment]
Can you confirm, that you can still see that ad, when you disable all your browser extensions?

Many people use extensions, which insert ads into websites, and people don't even know about it. Even an elementary school got in touch with us in the past, and it turned out all their Chromebooks were equipped with ad-inserting extensions by their provider.

**Comment by theeaglexiii** [comment]
Thanks for the response. I can confirm that with all browser extensions off I still see the ad.

**Comment by photopea** [comment]
Can you maybe record a video of a browser, where you show a page with extensions, and then open Photopea.com , and use it until the ad appears? I want to show it to my ad provider as a proof.

**Comment by PixelPartner** [comment]
This issue seems to appear again.
It happened to me yesterday, but I was in a hurry and didn't identify the advertiser.
Just now, everything worked as expected.

**Comment by photopea** [comment]
Could you share a screenshot of the "bad ad"?

**Comment by PixelPartner** [comment]
![Bildschirmfoto 2024-06-27 um 15 48 16](https://github.com/photopea/photopea/assets/73567/eb71ee04-3f37-47e0-b5a1-3e8d7f39a077)
Happened again, same Ad.

**Comment by photopea** [comment]
I am confused. So it is not a fullscreen ad, but it is on the side? Could you share a screenshot of your whole screen?

**Comment by PixelPartner** [comment]
The rest of the screen looks functional, but whenever you want to select a tool or select a region, the ad interferes.A click on the tool bar either toggles sound on/off or even opens a new tab with the fragrance website.In a rare moment, when a second ad comes up on the right, Photopea works, but selecting a region is interrupted midway.I'm using macOS15 beta Safari18Am 28.06.2024 um 00:02 schrieb Photopea ***@***.***>:﻿
I am confused. So it is not a fullscreen ad, but it is on the side? Could you share a screenshot of your whole screen?

**Comment by photopea** [comment]
I will report this ad to our ad provider.

**Comment by PixelPartner** [comment]
Great, the same ad appeared again, unfixed and causing the same trouble.
My workaround: wait for the few milliseconds when the [x]=close of the ad appears and click. Worked after the third try. But later it came back again.

**Comment by photopea** [comment]
Could you send me a screenshot of the ad, so that we can block that product?

**Comment by PixelPartner** [comment]
Same screenshot and URL that opens the product page as mentioned before.
Your Ad partner did NOT block it.

**Comment by PixelPartner** [comment]
Sorry, after a few times closing the Ad, it didn't appear again.
Maybe next time - and then I might try ingognito.
