### ISSUE TITLE
kerning 

### ISSUE THREAD

**Issue by shonahan** [photopea/photopea#3735]
can kerning be added this month?

**Comment by photopea** [comment]
Hi, what is kerning? Can you show us an example? 

Do you mean this? https://github.com/photopea/photopea/issues/3682

**Comment by shonahan** [comment]
yes

**Comment by photopea** [comment]
Then, let's discuss it there, there, there is no need to start a new issue.

**Comment by shonahan** [comment]
where's the "there"?

**Comment by photopea** [comment]
I mean the original issue: https://github.com/photopea/photopea/issues/3682

**Comment by shonahan** [comment]
but I'm asking about the date when kerning will be added.

**Comment by photopea** [comment]
I can not promise you any date at the moment.

**Comment by shonahan** [comment]
I see. i apologise if i sound rude. Regarding some problems I'm facing, hence, I'm asking about kerning update.
