### ISSUE TITLE
Cannot switch blending modes with the arrow keys on the keyboard anymore

### ISSUE THREAD

**Issue by benleonheart** [photopea/photopea#3739]
Hi, so previously, I was able to select a layer, then click on the blending mode drop down menu and select, for example "Multiply" , or "Soft Light"  or "Overlay" and from there, I would just move within the list using the Up and Down arrow keys, for a faster, more efficient way of previewing the blending mode I wanted.
I am not able to do that anymore, this started around 2 months ago.

Thanks for this amazing project btw.

**Comment by photopea** [comment]
Hi, I am very sorry, it should work again.
