### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by flaneurette** [photopea/photopea#3741]
Could you remove the preview text from new images? I see text like: "what is love" etc... . It is rather annoying to see it. Would rather see blank images. More classy and professional. Overal good program and glad I am a subscriber.

**Comment by MichalSZZ** [comment]
I think that works like a complete templates - not only a new project with image on it. It is for people who don't know well Photopea but want to make graphic with text and image. Preview show how the project will look like with photo and font on it. You can mix them to set what you like and then edit.

If you want to make a new project and then add a image - first of all choose blank project (don't even look or click on the right side ;)) then use the Gallery plugin to search free to use images:
![obraz](https://user-images.githubusercontent.com/38118273/134129673-3d3cc1be-a4c1-4414-98ce-f7b69ab33f2b.png)

**Comment by photopea** [comment]
These templates are for poeple, who need to create graphics with text.

If you need only an image, press Window - More  - Gallery, or use images from other places.

**Comment by photopea** [comment]
Our templates contain a background image (or a solid color), some decoration (a border, a white or a black stripe) and the text.

Do you want templates with a background image and a decoration (and no text), or only an image?

**Comment by nothingshiru** [comment]
It would be great to have a new "With ..." here for getting rid of the texts. 
![screenshot_20210921_165611](https://user-images.githubusercontent.com/79258245/134143302-c174f00c-d02b-4af3-b31e-78dc30dd77f2.jpg)

**Comment by flaneurette** [comment]
Or perhaps a lorem ipsum generator... designers use those a lot. Text in some foreign language, such as Latin is rather pleasing as it doesn't interfere with the image itself.

**Comment by flaneurette** [comment]
Example of Lorem Ipsum generator:

![screenshot_20210921_165611](https://i.ibb.co/2PzMsQ3/template.png)

**Comment by MichalSZZ** [comment]
I have requested for Lorem Ipsum generator ~3 years ago here #963. Maybe it's time to talk about it again if more people want to have that feature?
