### ISSUE TITLE
Issue: Double-clicking on the right side of layer name would open Layer Style window

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3744]
Is it a expected behavior?

https://user-images.githubusercontent.com/79258245/134165359-486ee371-10a2-4267-8c37-2f0ebbdd05bd.mp4

**Comment by photopea** [comment]
Yes, double-clicking a layer (not the layer name) opens the Blending Options window.

**Comment by nothingshiru** [comment]
In the video you can see that I still double clicked on the name of the layer. 

I just noticed that the text box for changing the layer name appeared the moment I double-clicked on the layer name, which means that Photopea knew I was going to rename the layer, but the Layer Style window appeared unexpectedly. 

I think that the Layer Style window shouldn't be opened in this case.

**Comment by photopea** [comment]
I can not reproduce this bug in Chrome for Android :( When I double-click a layer name, the renaming appears. When I double-click elsewhere, the Layer Style appears, never both.

**Comment by nothingshiru** [comment]
Try to make the layer name long and double-click on the right part of it.

**Comment by photopea** [comment]
I think I have fixed it. Is it fixed?

**Comment by nothingshiru** [comment]
Yes, it is fixed. Thanks.
