### ISSUE TITLE
An extra black square

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3745]
Why are there 2 black in fill type menu? Is it intentional?
![Screenshot_20210921_201851](https://user-images.githubusercontent.com/79258245/134169402-e5909150-988d-4a12-8eaa-72c0407a81ce.jpg)

**Comment by nothingshiru** [comment]
If the reason is that there gotta be 10 colors, how about making it same as in swatches?  (foreground color, red, green, ..., grey, white)
![screenshot_20210921_202342](https://user-images.githubusercontent.com/79258245/134170030-4f5158d4-4368-47a7-b0a8-7f742ef8fd7d.jpg)

**Comment by photopea** [comment]
This shows you the last 10 colors, that were used. At the beginning, we fill it with some "random" colors.
