### ISSUE TITLE
Suggestion: CD templates, Cover art.

### ISSUE THREAD

**Issue by flaneurette** [photopea/photopea#3746]
Would be nice to have CD templates: 

- CD insert
- Jewelcase Insert
- Jewelcase Booklet. 
- Optional: round CD-R, DVD. for stickers. (I am not using these, but perhaps someone else is.)

Digital media such as MP3's also take such covert art which is a similar size.

As I am using these from time to time, and then I have to go on Google to look for all the sizes. Would be very nice if Photopea can accommodate these. 

Another request would be for print media: 

- Postcard (US, International set at 300 DPI)
- Poster (basic poster size set at 300 DPI)

That is all I am missing in PhotoPea.

**Comment by photopea** [comment]
Hi, where exactly would you like it to be in Photopea? Do you mean the free PSD templates?

**Comment by flaneurette** [comment]
Would be great if it can be added in:

New Project > Print > CD templates (or another name)

> Social | Print | Photo | Screen
>>>> CD media

**Comment by flaneurette** [comment]
I believe it is called media, then...

Media:
- CD insert
- Jewelcase Insert
- Jewelcase Booklet.

http://www.canadianmusicartists.com/coverdesign.html
more detailed: https://www.stebbing.co.nz/application/files/4115/8328/7305/Stebbing_2019_CD_Spec_Booklet.pdf

Print:
- Poster
- Postcard

Poster sizes: https://www.rushflyerprinting.com/standard-poster-size/
Postcard sizes: https://images.saymedia-content.com/.image/t_share/MTc0OTg2NjM5NjM2OTY0ODA0/postcard-size-guide.jpg

**Comment by camoody1** [comment]
Taking this request one step further...

Would it be possible for us to save our own templates to the New Project window? I would like to create my own canvas sizes for different projects and save them to that quick access menu for New Projects. I'm not sure this is possible, however, given that Photopea is web-based.

**Comment by photopea** [comment]
@camoody1 is there any specific kind of things that you often create? Maybe we cold make Photopea remember the size which you used last time, after you close Photopea.

**Comment by camoody1** [comment]
I like to create wallpapers for different mobile phone and tablet resolutions. So, it would be helpful to be able to save my own canvas sizes like you already have for several Apple products and some older Samsung devices. It certainly isn't nearly as important as some of the other feature requests in your queue, but it would be a nice to have.

**Comment by photopea** [comment]
@camoody1 Could you tell me about what specific scren sizes are you interested in?

BTW. I think today, all wallpapers should be made at a high resolution, e.g. 4K, and a device will resize them to their own resolution automatically. There is no need to create 20 versions of your wallpaper for 20 devices.

**Comment by camoody1** [comment]
This is a super low priority request. You can just cancel it.

**Comment by photopea** [comment]
ok
