### ISSUE TITLE
Bug: on aspect ratio

### ISSUE THREAD

**Issue by flaneurette** [photopea/photopea#3747]
Sometimes, when I enter a number in Width, and then place the cursor in Height, width defaults to the previous number and have to re-enter the value in Width. Sometimes multiple times, especially when I want to re-size an image. Happens especially when I have multiple images open that are quite large.

**Comment by photopea** [comment]
Can you please describe steps, how to reproduce it?

If you enter one value, and the aspect ratio is locked, only the second value can change, not the first one.

**Comment by flaneurette** [comment]
When default values are:

w: 1980
h: 1200

I place cursor in **width**, and type: 600

Then I place cursor in **height**, and **width** defaults back to 3000. 

Then I have to retype, sometimes up to 3 times before it automatically makes the correct aspect ratio.Sometimes it happens, but not always. Mostly when I edit large images and PSD files set at 300 DPI. Could be a memory issue?

**Comment by photopea** [comment]
Where exactly do you type these values? It is so confusing :(

**Comment by photopea** [comment]
Could you write the instructions on how to reproduce the bug? Like 1. open www.Photopea.com, 2. .... and so on?

**Comment by flaneurette** [comment]
I use it when resizing an image. Image > resize.

**Comment by photopea** [comment]
Do you mean Image - Image Size? I just tried to enter the Width as "600", but when I click the Height, only the Height changes, not the Width :(

Could you maybe record a video of it?

**Comment by flaneurette** [comment]
Think you can close the issue. 

It probably is a memory issue on JavaScript threading, but that is due to the browser itself and how it allocated memory. Could result in larger bugs though, but depends on installed memory and browser architecture. Currently used chrome.

**Comment by photopea** [comment]
I still would like to fix it, if you could describe some steps on how to reproduce it.
