### ISSUE TITLE
Drag&drop layer reordering don't work in Samsung Internet Browser.

### ISSUE THREAD

**Issue by txzylinski** [photopea/photopea#3749]
Drag and drop layer reordering via long touch don't work in Samsung Internet Browser on Galaxy Tab s7+. On Chrome it work as intended.

**Comment by photopea** [comment]
I am afraid I can not do anything about it :( The creators of the Samsung browser should fix it, so that websites work properly. Or try Firefox, if you want to avoid Chrome.
