### ISSUE TITLE
Clicking on arrow when the option is visible shouldn't open once again that window

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3750]
![obraz](https://user-images.githubusercontent.com/38118273/134305084-149f6609-a886-48f2-940f-d7204d0050dd.png)
By default clicking once again on that tiny triangle - should close opened window - like clicking everywhere outside this window.
Now it is trying to open once again.

**Comment by nothingshiru** [comment]
This problem is present in almost all the small triangular buttons used to expand the menu. Except these
![screenshot_20210922_172207](https://user-images.githubusercontent.com/79258245/134317883-bf665230-495c-47f6-b6a0-5a917063f7f5.jpg)

I'm also looking forward to this problem being fixed.

**Comment by photopea** [comment]
I fixed it wherever I found it. Let me know if I have missed anything :)

**Comment by nothingshiru** [comment]
The Fill and Strokes.
![IMG_20210922_183701](https://user-images.githubusercontent.com/79258245/134329344-229497cd-1d99-4e9d-859d-f4db628efc82.jpg)

The buttons with triangle icon in Levels and Curves.
![IMG_20210922_183642](https://user-images.githubusercontent.com/79258245/134330036-fc2747c5-ab3d-4858-b372-c52b2d751add.jpg)


And there are some buttons which don't have the triangle icon. But the style of the menu opened by clicking on them is similar. I'm not sure if they are relative to this issue. 

They are warp and arrow.
![screenshot_20210922_183458_edit_805516854157292](https://user-images.githubusercontent.com/79258245/134330151-537cd73e-963c-4dbe-b69d-874a2184ca77.jpg)
![screenshot_20210922_183540_edit_805506930521876](https://user-images.githubusercontent.com/79258245/134330163-8a79b65b-59e8-4355-a411-f130ac248943.jpg)

**Comment by photopea** [comment]
I have fixed them all :) thanks!

**Comment by nothingshiru** [comment]
This one was missed.
![IMG_20210922_202032](https://user-images.githubusercontent.com/79258245/134342658-58e9c5bb-8ffd-466c-931c-d2babbb87849.jpg)

**Comment by nothingshiru** [comment]
Just found that the menu button in Liquify was left out.

**Comment by photopea** [comment]
fixed, thanks for reporting! :)
