### ISSUE TITLE
Holding the Shift button in Angle picker - snapping to 15 degree 

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3751]
In any place where there is this Angle Picker in the Circle 
![obraz](https://user-images.githubusercontent.com/38118273/134310806-6b9c95e3-6edc-48c0-bd61-66d2d363c95d.png)
it should to snap to 45 degree when user hold the Shift button and rotate line for the perfect x15 angle, instead of typing in the text box.

**Comment by photopea** [comment]
Fixed, thanks for reporting! :)
