### ISSUE TITLE
Path is not available

### ISSUE THREAD

**Issue by F1nessa** [photopea/photopea#3752]
![image](https://user-images.githubusercontent.com/91188593/134318494-9b5f61cf-a3cf-4cf1-8421-40504e247f1e.png)
![image](https://user-images.githubusercontent.com/91188593/134318580-35a0fc2e-5bc6-46e6-a132-29fc835c1278.png)

Hello!
First of all, I want to thank you for this amazing app.

I founded out that paths are not showing. 
The first screen: pic is opened in Photopea
Second, in PS

KR

**Comment by photopea** [comment]
Hi, could you share your PSD with us?

**Comment by F1nessa** [comment]
Oh sorry, I just realized that is .tif file format. 
I'm not sure that this format is supported

Anyway, please find the file below

[A_LEFT_Energy .zip](https://github.com/photopea/photopea/files/7210391/A_LEFT_Energy.zip)

**Comment by photopea** [comment]
Your file is actually a PSD file wrapped inside the TIFF. Only Photoshop can detect these PSDs in TIFFs. So your TIFF will behave this way (with paths and everything) only in Photoshop.

Can you save your work in the PSD format instead? Photopea works perfectly with the PSD.

**Comment by F1nessa** [comment]
Unfortunately, I need exactly this format. 
Thanks for support

**Comment by photopea** [comment]
Ok. These TIFFs will work with paths only in Photoshop, you will not be able to see your paths anywhere else.
