### ISSUE TITLE
Transforming some part of a shape layer - transform controlers arround all shape - not the selected part

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3753]
![obraz](https://user-images.githubusercontent.com/38118273/134324858-759a78ab-1060-45bf-9579-75781d7ad09d.png)

Step to reproduce:
1. Type some text
2. Convert text to a shape
3. Using Direct Select Tool - select first letter only
4. Use Ctrl + T to transform

Now the whole shape has a transform controllers - but changes are making only for selected area.
Transforming rectangle and the reference point should to be only for selected points.

**Comment by photopea** [comment]
It is related to this issue: https://github.com/photopea/photopea/issues/3684 . I believe that now, it works the same as in Photoshop.

If you select some paths with a Path Select, only the rectangle will be made only for those paths.

But if you select only some points with the Direct Select, the rectangle is made for the whole vector shape (to prevent a 0x0 rectangle when you select just one point).

**Comment by MichalSZZ** [comment]
OK I understand. It works different in Photoshop (there I can choose only few knots in one letters and transform it and the transform rectangle contains only that part) but now I know more about "how" and "why" it works in that way in Photope'a.
