### ISSUE TITLE
Shift button when the parametric shape is drawing doesn't lock the x15 degree angle snapping

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3755]
I am sure that was working before - here on my tutorial about shapes that I made ~1 year ago https://youtu.be/5VNrylcxZ9w?t=102

**Comment by photopea** [comment]
I am very sorry, I have fixed it. 

Note, that the Shift at the mouse-down defines, if the shape should be "united" with the previous shape. Only the Shift pressed while "drawing" will apply constraints to the shape.

**Comment by MichalSZZ** [comment]
@photopea yes I know it very well. I think that was my suggestion some time ago here on Github. I use that feature a lot.

And thanks for your quick fix.
