### ISSUE TITLE
Annoying menu

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3760]
To reproduce

1. Clear the text box.
2. Click on the blank text box. 

it even shows me the values that I have filled in other text boxes. I don't use them at all. 
![Screenshot_20210923_193004](https://user-images.githubusercontent.com/79258245/134500269-5ec5bff5-f873-4e41-a84e-a29502166c50.jpg)

Can it be removed or disabled?

**Comment by photopea** [comment]
I can not reporduce it in my Android :( Maybe it is something specific for your browser? Can you disable it in the settings of your browser or your phone?

**Comment by nothingshiru** [comment]
I found it. it is related to a setting about the address autofill in Chrome.
