### ISSUE TITLE
Getting a Message "Not enough RAM! (need 101MB)" 

### ISSUE THREAD

**Issue by casperzwaart100** [photopea/photopea#3761]
Hey, 

I am currently using photoshop, for the first time on my new Macbook pro (16gb RAM) 

Now I am making a custom football kit, which has a file that is 6000x6000. And then with smart layers you can edit small parts of the shirt. Now I was trying to merge 2 items together on a seperate smart layer page 4500x4500px. 

Here is the message I am getting: 
<img width="754" alt="Schermafbeelding 2021-09-23 om 14 56 05" src="https://user-images.githubusercontent.com/85107635/134511665-ef724b85-7a7f-4091-a7ca-4baa137f2f91.png">

I don' t think I should be getting it, since I have plenty RAM

thanks

**Comment by photopea** [comment]
Hi, do you mean you are using Photopea? We do not provide any Photoshop.

What web browser are you using? Can you update it to the latest version?

**Comment by casperzwaart100** [comment]
Yeah sorry, photopea ofc. 

It should be the most recent, since I downloaded it yesterday. However there is a software update available so I' ll check that
