### ISSUE TITLE
Collapse font files that belong to a same font

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3765]
Please make them collapsible and expandable
![screenshot_20210924_234525](https://user-images.githubusercontent.com/79258245/134704359-6ac78c2e-03fa-4bce-aec2-96ce9c4a198c.jpg)

**Comment by photopea** [comment]
But why? You dont have that many files there. Also, I think the Noto fonts are already in Photopea, arent they?

**Comment by nothingshiru** [comment]
Now I have more files. Each font has 6 or 7 files for different weights. Managing them becomes not so easy.

Although you made a change to the cache time before, I don't know why I still need to re-download the fonts so often. So I downloaded them and imported them into Photopea from my device.

I would like to ask if Photopea is considering supporting variable fonts.

**Comment by photopea** [comment]
The fonts should be cached by a browser for two weeks. Are you sure your fonts are downloaded more often than that? Do you have any browser extensions, that can clear browser cache?

I dont think there are many variable fonts out there at the moment. Do you have any variable fonts?

**Comment by nothingshiru** [comment]
> Are you sure your fonts are downloaded more often than that? 

Yes. And the font is often set to the default DeJaVu sans instead of the font I used last time. 

> Do you have any browser extensions, that can clear browser cache?

I don't have any extensions.

> I dont think there are many variable fonts out there at the moment. Do you have any variable fonts?

I have a variable fonts of Noto Sans. It contains 8 weights and the file size is much smaller than 8 separate files.

**Comment by photopea** [comment]
How much smaller are the Noto fonts? I see that there are 6 weights for each Noto font like HK, JP, etc.

Can you describe how can I reproduce resetting the current font to DejaVu Sans? Photopea should always open with the font that you used last time.

**Comment by nothingshiru** [comment]
The variable font is 30MB, and the total of 7 separate files is 115MB. 

I don't know how to make it happen manually.

**Comment by photopea** [comment]
The Local Storage is a "bag of random files", there are not only fonts. There is no clear way how to "collapse" similar files - whatever that means. Maybe I could let you create folders, etc.

I will close it, and make a new issue requesting the support for variable fonts.

**Comment by nothingshiru** [comment]
OK :)
