### ISSUE TITLE
Layer Style Bug

### ISSUE THREAD

**Issue by raabemartinsdesigner** [photopea/photopea#3767]
Hello. My name is Rahab, I really appreciate photopea!
But there's one problem:

When I open "Layer Style" and select "Drop Shadow", I want to add another "Drop Shadow". But if I do and choose to put the Angle in 90º, all "Drop Shadows" will turn their angle into 90º. And if I select "Bevel and Emboss" and change their Angle to 110º, all the "Drop Shadow" angles will turn into 110º too.

  Please, help me with this problem! Thank you.

***

Olá! Meu nome é Raabe, eu gosto muito do Photopea, e uso bastante. Mas ultimamente um problema tem atrapalhado muito meus designs, gostaria de pedir ajuda por favor:

Quando eu abro o "estilos de camada", e adiciono "Sombra Externa", posso configurar o ângulo para 90º, por exemplo. Até aqui tudo bem. O problema é que se eu adicionar uma nova Sombra Externa e mudar o ângulo dela para 110º, o ângulo da OUTRA sombra externa automaticamente muda para 110º também. E se eu adicionar "Bisel e Relevo", o ângulo vai estar em 110º, e se eu mudar o ângulo do Bisel e Relevo para 50º, TODOS OS ÂNGULOS vão mudar automaticamente para 50º.

Por favor, me ajudem. Obrigada.
![Screenshot](https://user-images.githubusercontent.com/91345712/134729397-6260c1fd-ff5b-4da8-9f7e-ca47a1af1f72.png)

**Comment by MichalSZZ** [comment]
It is a normal behavior and should work like you wrote. If you don't want it, just turn off "use global light" checkbox.

**Comment by raabemartinsdesigner** [comment]
> It is a normal behavior and should work like you wrote. If you don't want it, just turn off "use global angle" checkbox.

Thank you so much!
