### ISSUE TITLE
Layer styles window opening when reordering layers

### ISSUE THREAD

**Issue by Ennllel** [photopea/photopea#377]
Hi there!
When I try to move the layers in layers pannel the layer styles window opens unexpectedly like in the example below. Doesn't happens every time, let's say 2 out of 3 times.

![pplayers](https://user-images.githubusercontent.com/7062453/33090810-8bd09a1a-cef5-11e7-9bfe-f9ebdccd7b65.gif)

**Comment by photopea** [comment]
Hi, I changed our code a little. Does it still happen?

**Comment by Ennllel** [comment]
Works fine now :)
