### ISSUE TITLE
Issue: Smart object not working when opened in affinity photo

### ISSUE THREAD

**Issue by tripujiyanto** [photopea/photopea#3771]
Hi,

I made a smartphone mockup with 3d software for modeling, and Photopea to create a psd file. In this psd file I created 3 smart objects (for two phone screens and for the logo).

All smart objects work fine and perfectly in photopea and without any problems. Then I save it to a psd file, the size is about 166 MB (4615 x 3000 px 300dpi, with a total of about 27 layers)

![ss1](https://user-images.githubusercontent.com/37952055/134788278-7a235315-6a79-4913-8709-4146a282189b.jpg)

Then I tried to open the psd file with Affinity Photo, although it can be opened, but there is an issue message. And after I checked in Affinity Photo, all the smart objects have been converted to pixels, and even the raster masks are not there.

![ss2](https://user-images.githubusercontent.com/37952055/134788284-4be53dfa-2399-490b-958c-d12959bee270.jpg)
![ss3](https://user-images.githubusercontent.com/37952055/134788286-e315d8c3-eb10-4d06-9f9d-96d17b197c64.jpg)

Then I tried to download the mockup file from fr**pik (web mockup provider), and I opened the psd file in Affinity Photo, after I checked it turned out that the smart object worked well in Affinity Photo.

![ss4](https://user-images.githubusercontent.com/37952055/134788291-7b9ee899-0ba4-4518-af95-30c44df6aa4b.jpg)

My question: Are smart objects created in Photopea not working properly when opened in other software?

note: i don't have adobe photoshop on my pc, so i haven't checked on PS.

thank you.
sorry for may bad English

**Comment by photopea** [comment]
I think it is a bug in Affinity Photo.

If you create an identical PSD file in Adobe Photoshop, and open it in Affinity Photo, I think there would be the same problem. So I think the problem is not related to Photopea at all.

**Comment by photopea** [comment]
So your PSD is working in Affinity Photo? Could you open it in Photopea and save as a new PSD, does that PSD work in Affinity Photo?  

Could you re-save a new PSD it in the latest Photoshop? Does it still work in Affinity Photo?

Also, is there anything you miss in Photopea, that you decided to use two programs instead of one?

**Comment by tripujiyanto** [comment]
Thank you for your response,

I've been doing various experiments on smart objects from Photopea. And there is something strange about the Photopea smart object, from the three techniques (warp, distort, perspective transform) only warp works normally. For more details, please watch this video.

[https://www.youtube.com/watch?v=bii5avYLXyo](url)

From the video, there is a bug in the smart object from Photopea, and not a bug from Affinity Photo.

Also, is there anything you miss in Photopea, that you decided to use two programs instead of one?

Answer :
I use Photopea to save the final psd file, and Affinity Photo only to check the file, Affinity Photo is not suitable for mockup designs because it can't save smart objects in psd files.

Notes :
I decided to install Photoshop simply because I was very curious about this problem. If this problem is resolved, I will continue to use Photopea.

Photopea is the best

**Comment by photopea** [comment]
Hi, sorry, but your video is too long with no sound, I have no idea what you are trying to "tell me" in the video :(

Are you saying, that a PSD file from Photopea is opened "strangely" in Adobe Photoshop? Could you tell me more details (with a short text instead of a long video)?

**Comment by tripujiyanto** [comment]
> Hi, sorry, but your video is too long with no sound, I have no idea what you are trying to "tell me" in the video :(
> 
> Are you saying, that a PSD file from Photopea is opened "strangely" in Adobe Photoshop? Could you tell me more details (with a short text instead of a long video)?

I'll explain in text from the video:
The psd file from Photopea can be opened in Photoshop, but after I edit the smart object and save the smart object, something strange happens (the smart object becomes smaller after editing). I feel there is a bug in the Photopea smart object.

![image](https://user-images.githubusercontent.com/37952055/134826030-7fe28d39-3f13-4a47-88f0-1da0c3a3dd3b.png)
before

![image](https://user-images.githubusercontent.com/37952055/134826043-f5f6b4b5-ef6e-4213-af38-cd01913f6578.png)
after

**Comment by photopea** [comment]
I am not able to reproduce it :(

I created this PSD in Photopea, and it seems to work well in Photoshop (updating the smart object). Can you try it in your Photoshop
[New Project.zip](https://github.com/photopea/photopea/files/7234278/New.Project.zip)

**Comment by tripujiyanto** [comment]
Your psd file works fine and perfectly in my Photoshop. Smart object size does not change after editing. What browser do you use to open Photopea?

Try opening this psd file, I created it using Photopea (this file has a problem with the smart object when editing it in my photoshop)
[from photopea3.zip](https://github.com/photopea/photopea/files/7234660/from.photopea3.zip)

**Comment by photopea** [comment]
There used to be a bug in Photopea a year ago, which could produce these corrupted PSD files. Did you create your PSD with Photopea a year ago?

Can you describe steps, how to create a PSD (in current Photopea) with one smart object, which would "shrink" after editing that PSD in Photoshop?

**Comment by tripujiyanto** [comment]
> There used to be a bug in Photopea a year ago, which could produce these corrupted PSD files. Did you create your PSD with Photopea a year ago?
> 
> Can you describe steps, how to create a PSD (in current Photopea) with one smart object, which would "shrink" after editing that PSD in Photoshop?

psd file that I sent was made today, and the phone mockup psd file I created a few days ago.

for the steps in making a psd on photopea, you can see the link to my previous youtube video.

steps:
1. create a new file in photopea
2. create a rectangle > convert to smart object
3. press ctrl+T (transform) > distort
4. move the corner points to where you want > enter
5. save as psd > open in photoshop

but strangely the way above works (smart objects work fine in Photoshop).

but for my phone mockup psd file, the size of the smart object shrinks after editing in photoshop.

is my phone mockup psd file corrupt?

**Comment by tripujiyanto** [comment]
> So you are writing down steps, which do not demonstrate any bug? That is not what I asked for :D

yes there is no bug, but for the case of the PSD file I sent earlier there was a bug (maybe my mockup psd file is corrupt?)

all psd files i created using photopea

**Comment by photopea** [comment]
@nothingshiru could you help us? Could you create a PSD in Photopea, with a smart object, which gets shrinked after editing it in Adobe Photoshop? I would like to reproduce it somehow.

**Comment by nothingshiru** [comment]
> @nothingshiru could you help us? Could you create a PSD in Photopea, with a smart object, which gets shrinked after editing it in Adobe Photoshop? I would like to reproduce it somehow.

Sorry, I was not able to create such a PSD in Photopea.

**Comment by photopea** [comment]
So the bug happened only if you changed the DPI of the main document, or the DPI inside the Smart Object.

I have fixed it. Now:
- Every PSD should work the same in Photopea as in Photoshop (your smart object will shrink after you edit it in Photopea now).
- These "weird PSD files" should not be produced anymore, no matter what you do with the DPI. Every PSD should work the same in Photopea as in Photoshop.

However, you would have to "fix" your current PSD manually in Photoshop or Photopea.

Also, I think these changes are not related to your original question about Affinity Photo. You would have to show us, that Affinity Photo can not open a PSD from Photopea, while it can open an identical PSD created in Photoshop, so that you can tell there is something wrong with Photopea PSD.

**Comment by photopea** [comment]
I am glad it works! I have "switched" the direction of the flag, but I dont know how to fix other effects :(
