### ISSUE TITLE
Issue: There is gap between the fill and Outside stroke of the rounded rectangle at the rounded corners

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3772]
Here is a example PSD.
https://www.photopea.com/#iNcc7JOWQ

![Screenshot_20210926_114023_com microsoft emmx_edit_130739020594113](https://user-images.githubusercontent.com/79258245/134792767-9da0b16a-e1bd-4dc8-9c4d-47bd015fec15.jpg)

**Comment by photopea** [comment]
fixed, thanks for reporting! :)
