### ISSUE TITLE
Feature request: Free transform center control point as "scale center" and not only "rotation center"

### ISSUE THREAD

**Issue by adiazhermidas** [photopea/photopea#3775]
First of all congratulations on your excellent product.
I was wondering if the adjustable center control point of the free transform tool (below) could be updated so it would work as a "scale center" and not only as a "rotation center". Is it very hard to code?
It would greatly simplify image overlap operations (such as matching floor plans of various levels), that otherwise require a lot of trial and error, and it is the main reason I still keep my old copy of Photoshop installed.
Thank you very much.
Alberto Diaz Hermidas
Architect, Spain

![image](https://user-images.githubusercontent.com/55656347/134801710-21dc3200-40e0-4c5a-a971-b20f12f29a12.png)

**Comment by photopea** [comment]
Hi, how exactly do you do it in Photoshop?

I believe the Free Transform works 100% identically in Photopea and Photoshop. You should hold the "Alt" key when you drag corners, to scale it "around the center" (in Photoshop and in Photopea). 

You can learn how to use the Free Transform in Photoshop (and in Photopea) here: https://helpx.adobe.com/photoshop/using/free-transformations-images-shapes-paths.html

**Comment by adiazhermidas** [comment]
Dear Photopea representative,
Excellent! You answered my question perfectly! I will only used Photopea from now on.
In my old version of Photoshop I don't have to press the Alt key to use the center control point as the center of scale. I guess that is because it is ancient (Photoshop 6, ca 2001, apparently).
I didn't know that you had to press Alt to use it as a center of scale in newer Photoshop versions or in Photopea.
It also confused me that the center control point seems to work as a "rotation center" in Photopea even without holding down the Alt key. At least it does in my system.
Perhaps you could indicate in your (excellent) help system that the center control point can be used both as "scale center" and "rotation center" (currently it only indicates "rotation center"), and that the Alt key needs to be pressed for it to work as a "scale center".
The need to press the Alt key does not seem to be documented.
Thank you very much and best regards,
Alberto

**Comment by photopea** [comment]
Ok, I wrote it here: https://www.photopea.com/learn/free-transform :)

**Comment by adiazhermidas** [comment]
Excellent, thank you very much.
