### ISSUE TITLE
Photopea crashes and corrupts large .psd files when overwriting

### ISSUE THREAD

**Issue by LazarLazarov** [photopea/photopea#3776]
I tried exporting a 270mb psd file for a 300dpi poster and foolishly wanted to not write yet another file and instead overwrote the latest one, which resulted in the Photopea page crashing and corrupting the .PSD file losing me hours of work. 

Thanks, I'll be sure to never use Photopea for critical work again :+1:

**Comment by photopea** [comment]
I am very sorry for what happened to you :( We recommend having at least 4 - 8 GB of free RAM when working with large files. 

And an updated web browser.
