### ISSUE TITLE
When the activated path is shape path, creating fill layer should not create shape layer

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3778]
![screenshot_20210927_143419](https://user-images.githubusercontent.com/79258245/134856566-6f9e4387-1e3e-4777-9120-534ccff08c98.jpg)
![Screenshot_20210927_143505](https://user-images.githubusercontent.com/79258245/134856585-2735aed0-0844-4c4f-8b6f-46c77055e6a4.jpg)

Now if current layer is a shape layer and I create a fill layer directly, the layer will be created is shape layer instead of fill layer.

**Comment by photopea** [comment]
fixed, thanks for reporting!
