### ISSUE TITLE
Unknown space on the right

### ISSUE THREAD

**Issue by shahhafiz** [photopea/photopea#3779]
![image](https://user-images.githubusercontent.com/32601070/134861207-f2445d4a-61ac-4a61-bb52-f3398e416ee6.png)

**Comment by photopea** [comment]
There should be ads. Please, watch our ads. We would go bankrupt a long time ago, if everyone removed ads like you do :(

**Comment by shahhafiz** [comment]
Yes, my bad. You guys are doing great work. Will disable the ad blocker.
