### ISSUE TITLE
One of the buttons in the New Project window needs to be moved a little to the right

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3781]
![screenshot_20210927_225203](https://user-images.githubusercontent.com/79258245/134933238-9e0ff3c9-b1a5-4728-b9cb-f1cfe25309c6.jpg)

And the icon inside it needs to be enlarged a bit, now the icon doesn't look in the center of the button. 
![screenshot_20210927_224905](https://user-images.githubusercontent.com/79258245/134933574-9b4916ee-86a6-4446-8ff8-66eaa0ff8e1a.jpg)

**Comment by photopea** [comment]
fixed, thanks! :)

**Comment by nothingshiru** [comment]
Size of the icon inside wasn't changed yet.

**Comment by photopea** [comment]
Use the incognito mode to be sure you are seeing the latest version.
