### ISSUE TITLE
When submitting an image with multiple layers secondary layers disappears 

### ISSUE THREAD

**Issue by richardgoslingAOS** [photopea/photopea#3783]
We insert images with multiple layers

![image](https://user-images.githubusercontent.com/58290878/134940097-22aeeffd-6244-4211-bfc5-8ffd154fe4a0.png)

When you click on the layer the 2nd layer it disappears

The following error appears in the console 
![image](https://user-images.githubusercontent.com/58290878/134939983-6ad4feb0-a508-4c63-9e52-40c17b9df0b5.png)

Uncaught TypeError: Cannot read properties of undefined (reading 'elementsIDs')
    at o.value (eval at <anonymous> (photopeacomnew.min.js:2), <anonymous>:1:544274)
    at eval (eval at <anonymous> (photopeacomnew.min.js:2), <anonymous>:1:543065)

**Comment by photopea** [comment]
I think the error in the console is related to ads, it is not from Photopea.

Can you describe how can I reproduce this issue in Photopea?

**Comment by photopea** [comment]
I think I know what you mean. It should be fixed now.

**Comment by richardgoslingAOS** [comment]
Thanks that's great

**Comment by richardgoslingAOS** [comment]
great support as always thank you soooo much!!
