### ISSUE TITLE
Smart objects not saving correctly in photopea

### ISSUE THREAD

**Issue by EAPrintables** [photopea/photopea#3784]
When I save my smart object the final image is very small and not filling in the full pixel space.

**Comment by EAPrintables** [comment]
Hi I've never had any issues before. Earlier today, the images were saving
fine then it suddenly just stopped working properly. I didn't make any
changes to the DPI values as far as I'm aware.

**Comment by photopea** [comment]
Today, we have changed the way Photopea works. Could you send us your PSD file to support@photopea.com ?

**Comment by MitkoNed21** [comment]
I am having the same issue, old Smart objects when edited appear small when they are updated

**Comment by photopea** [comment]
Could you send us your PSD file to support@photopea.com ?

**Comment by EAPrintables** [comment]
yes! this is exactly what's happening with mine.

**Comment by photopea** [comment]
We can not fix it without having a PSD file, in wihch it happens :(

**Comment by photopea** [comment]
It should be fixed now.

**Comment by e54684** [comment]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
