### ISSUE TITLE
Make them buttons on the initial window

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3786]
Yesterday i was working with my teammate and i clicked the "Open From Computer" button on initial the window.

And she was shocked that never though those bullet points where buttons!
![image](https://user-images.githubusercontent.com/11801254/135025505-f4fde0b9-66d3-4e4b-b2a7-9391bd92c330.png)

And in her defense, they don't seem to be clickable.

So, a little suggestion would be, give them a little redo, and make them look like actual buttons.

That's all :)

**Comment by photopea** [comment]
You are not the first one who says that! :D We are planning to remake it completely soon, when we add storage options.

But the mouse cursor changes into a finger when you move a mouse on top of the buttons.

**Comment by nothingshiru** [comment]
Coincidentally, I was going to say the same thing :)

I also think that the icons of supported formats at the bottom need a little change. They look too much like clickable buttons.

**Comment by MichalSZZ** [comment]
All that you guys mentioned is true!
Bulletpoints without a underlined link - tells nothing to user. It is just a list with words.

Now it can be changed easily to something like this:
![obraz](https://user-images.githubusercontent.com/38118273/135080708-9c31679f-8b1e-4e8c-9db2-45bec01ce7b4.png)

icons are from https://fonts.google.com/icons with Apache 2.0 licence

**Comment by avagp** [comment]
Hey @photopea when is this going to change?  :)
