### ISSUE TITLE
Change to Move tool from Artboard Tool when user is clicking on layer name in layers palette

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3788]
It should work it that way - it is faster for me (and works like that in PS) because when I made for example copy of one artboard and rollout an artboard folder and I am choosing  a layer to move, then the arrow keys on keyboard doesn't work in Photopea and layer doesn't moving

**Comment by photopea** [comment]
I have implemented it! If you have the Artboard tool, and you click on layers in the Layers panel, it will switch to the Move tool, as in Photoshop.

**Comment by MichalSZZ** [comment]
Thank you. 
And I see now, that it should work the same way if someone is clicking enywhere on the canvas.
The Artboard tool is only working outside the artboard canvas.
