### ISSUE TITLE
Actions -> Canvas Size relative not saved properly

### ISSUE THREAD

**Issue by pepea28** [photopea/photopea#3790]
I wanted to record an action that adds 20 pixels around an image and adds a shadow.
The action `Canvas Size` is saved but i checked the "Relative" option : 
![image](https://user-images.githubusercontent.com/28830638/135103653-dffb6b83-1e95-4649-8a34-08aaa5a1b588.png)    

However, that's the absolute final width and height that is saved in the action :

![issue_photopea_actions_canvas](https://user-images.githubusercontent.com/28830638/135117813-6b0aacd6-8a03-4279-a150-050e41e211fb.gif)

For information, if I do this action in Photoshop, save it in a `.atn` file, and import the `.atn` into Photopea, the behavior is OK.

**Comment by photopea** [comment]
It should be fixed now :)
