### ISSUE TITLE
Feature Request: Auto-focus on the text box in Name dialog

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3791]
When opening the Name dialog, renaming the document is our only purpose. Auto-focus on the text box would be more convenient.
![screenshot_20210929_002147](https://user-images.githubusercontent.com/79258245/135128230-bd236ab9-4431-4325-b3c4-75887ba8bd09.jpg)

**Comment by photopea** [comment]
There is auto-focus on this dialog when you open it. It does not work on a phone, I guess it is a bug in Chrome for Android.

**Comment by nothingshiru** [comment]
Auto-focus on this dialog does not work properly on Firefox either. 

But why auto-focus on Image Size dialog works?

**Comment by photopea** [comment]
I have fixed it.
