### ISSUE TITLE
Default position of Name dialog on phone needs to be moved

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3793]
It appears at top-left. The position of the OK button is just above the document tabs. 
When I double tapped on the document name, the Name dialog was opened and closed quickly since the OK button was tapped too. 
![Screenshot_20210929_025834_com android chrome_edit_307762757551996](https://user-images.githubusercontent.com/79258245/135150726-158a68fe-9abd-4dcf-88e7-62ea9dc6db17.jpg)

**Comment by avagp** [comment]
i have used photopea on the phone a couple of time just for urgency, but it really need a rework.

:/

**Comment by photopea** [comment]
I have fixed it! :)

@avagp what exactly needs a rework? About 30% of our users use Photopea on phones for many years.

**Comment by avagp** [comment]
I believe it can be more mobile friendly.

Bigger buttons, maybe a different interface.

It's my opinion. And I believe you had a issue on this git about how to
redesign the mobile experience.
