### ISSUE TITLE
Цвета

### ISSUE THREAD

**Issue by AlexanderLugovsky** [photopea/photopea#3794]
Хотелось бы видеть при выборе цвета - галочку  набор "Веб Цветов".

Очень хороший редактор. Вы сделали очень хорошую и востребованную работу, большое Вам спасибо.

**Comment by photopea** [comment]
Hi, thanks a lot! Why do you need only "web colors"? Today, any device can display any color, there is no need to limit yourself to "web colors".

**Comment by photopea** [comment]
I have added the "Web colors" checkbox to the bottom of the color picker in Photopea.
