### ISSUE TITLE
Image appears in my project but the photo doesn't appear

### ISSUE THREAD

**Issue by thezj1234** [photopea/photopea#3795]
Whenever I upload a photo to a project, it appears in the project but the photo doesn't appear in the project. Is there any way to fix this problem? Thanks!
![Screen Shot 2021-09-28 at 6 25 34 PM](https://user-images.githubusercontent.com/91550405/135245339-d0513046-2134-46c4-a3dc-b7afb10776a0.png)

**Comment by photopea** [comment]
There was a bug like this a couple of days ago. Did you have Photopea.com opened for several days without reloading? Try to reload it. Otherwise, please, share the file you are inserting with us.

**Comment by thezj1234** [comment]
> There was a bug like this a couple of days ago. Did you have Photopea.com opened for several days without reloading? Try to reload it. Otherwise, please, share the file you are inserting with us.

Hi! I refreshed the page and attempted to put a photo in a project and it works! Thank you so much!

**Comment by photopea** [comment]
Ok I am glad it works :)
