### ISSUE TITLE
[No Valid Data on Clipboard] after copying an image from website in Firefox to Photopea on Chrome

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3796]
![obraz](https://user-images.githubusercontent.com/38118273/135272474-597b4670-cecc-4bd4-8a9e-42d2b408fb4a.png)

I use FF as my main browser.
Before it was working good.
Now I have problems when I try to copy some image from any website in Firefox Browser and want to paste it Chrome PWA version of Photopea.

FF copy an image -> paste in Photopea opened on Chrome = not working
FF copy an image -> paste in Photopea opened on Firefox = works good

Any idea what is going on?

**Comment by MichalSZZ** [comment]
Thans. Now I know what to do. If that message is showing only in that one specyfic situation... maybe some sgort description or a link to the help will be the answer?

But in the past it worked well and the new document (as I remember) had size of copied image?

**Comment by photopea** [comment]
This needs to be fixed by Chrome.
