### ISSUE TITLE
Issue: The order of multiple layers of the same kind created with "Create Layers" is reversed

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3798]
here's a example.

Before
![Screenshot_20210930_033916_com microsoft emmx](https://user-images.githubusercontent.com/79258245/135338324-6d1d278a-3dd4-4383-aeb4-138e94e07d46.jpg)

After
![Screenshot_20210930_033916_com microsoft emmx (1)](https://user-images.githubusercontent.com/79258245/135338348-08db38c8-39bd-4fbe-997d-aa5d45b7e731.jpg)

**Comment by photopea** [comment]
fixed, thanks for reporting! :)
