### ISSUE TITLE
Uploading an image

### ISSUE THREAD

**Issue by dp-crypto** [photopea/photopea#3799]
I always encountered an error everytime I uploaded this image.
![pexels-paul-blenkhorn-sensoryarthouse-3517899](https://user-images.githubusercontent.com/52707875/135509423-329553e2-1170-4194-95ac-093b5b80e32b.jpg)
![pexels-paul-blenkhorn-sensoryarthouse-3517899](https://user-images.githubusercontent.com/52707875/135509656-776b36f9-2296-4af6-a49b-da438f105976.jpg)

**Comment by photopea** [comment]
I can open your image in Photopea witout any problems. Are you doing it on a phone? It is a 40 MPx image and you need to have 2 - 3 GB of free RAM to decode it.
