### ISSUE TITLE
Export as WEBP in Firefox

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#380]
In Firefox
Open pea.psd
File - Export as - WEBP (now no preview is showing)
Save
pea.webp is created but its content is PNG file (with .webp extension)

**Comment by photopea** [comment]
We were not able to find any WebP encoder in Javascript, so we decided to use Canvas.toDataURL("webp"). Apparently, Firefox and Safari do not support this format: https://caniuse.com/#feat=webp

Letsl wait, until browsers implement it, or any WebP encoder in Javascript appears.

**Comment by DemetryCode** [comment]
Same problem has started this week

**Comment by photopea** [comment]
What do you mean? You were never able to export Webp files in Photopea running in Firefox. You need to use a different browser for this.

**Comment by DemetryCode** [comment]
I don't know about firefox, you mentioned safari in your comment above and this week I have same issue in safari as in the started message. Am I mistaken that it has worked in safari before? I mean I used photopea exactly to convert jpg to webp with export function hmm

**Comment by photopea** [comment]
UPDATE: according to the latest news, it works in all browsers except of Safari and Internet Explorer :( https://caniuse.com/?search=todataurl%20webp  (it works in Firefox)

**Comment by DemetryCode** [comment]
I see, sorry for disturbing you! 🙏 Looks like I confused browsers I used, my bad

**Comment by photopea** [comment]
No problem :/ Maybe report it to Safari and ask them to add this feature?

**Comment by photopea** [comment]
I think you should at least try :)
