### ISSUE TITLE
noise and gifs

### ISSUE THREAD

**Issue by no0000000000** [photopea/photopea#3800]
whenever i try to add noise to gifs, the frames get damaged.  it's pretty much _only_ when i add noise.

**Comment by photopea** [comment]
What do you mea by "add noise" and damaged? Could you send me a PSD, which is exported into an incorrect GIF?

**Comment by no0000000000** [comment]
I mean, when I use the noise filter? It damages the frames and therefore the gif doesn't work?
![Screen Shot 2021-10-05 at 2 12 05 PM](https://user-images.githubusercontent.com/75169133/136079392-1a057d63-b4ad-4331-9e3c-aa15c1d77cac.png)

**Comment by photopea** [comment]
I have tried to add noise to frames of an animation (layers), and the exported GIF looks fine. 

Are you making it up? If not, can you tell me precisely what should I do to see the problem, or describe what are you doing?
