### ISSUE TITLE
Issues with the text.

### ISSUE THREAD

**Issue by Skrrt2005** [photopea/photopea#3801]
I've been 2 hours now trying to put a text in a template I got and the text tool is simply just loading forever.

**Comment by photopea** [comment]
Could you try these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by Skrrt2005** [comment]
Had to go incognito for text to work again, thanks.

**Comment by photopea** [comment]
You have a browser extensions, which breaks Photopea. Can you turn it off, or ask the creator of your extensions to fix it?

I am 100% sure, that if you disable all your extensions, Photopea will work perfectly :)
