### ISSUE TITLE
Adding Noise, Uniform

### ISSUE THREAD

**Issue by flaneurette** [photopea/photopea#3803]
It seems when I create a blank image, then Adding Noise from the filter menu: it does add noise but it is not really Uniform. I can see all kinds of patterns in it, even shapes and letters. The Gaussian function works better, and seems true noise as I cannot see any patterns in it.

Is this a bug?

**Comment by photopea** [comment]
Hi, could you share a screenshot of what exactly do you see? Are you sure your original image is fully white?

Have you tried to use Photopea without any browser extensions?

**Comment by flaneurette** [comment]
Still in there, even without disabling. Also tried in FireFox, still similar issue. The patterns are faint, but are there... I thought uniform would be more uniform and less random, as it seems to make patterns. Sometimes it even makes faint faces, as weird as that is...

**Comment by flaneurette** [comment]
Gaussian is called normal distribution and uniform is aimed at probability, apparently. But with uniform probability patterns can appear due to the rectangular distribution, and then it is **less** uniform than Gaussian because of the box model... as I learned on wikipedia. Then why is it called uniform? haha... strange.

**Comment by photopea** [comment]
Could you show me a screenshot of what you see? I am really curious. I do not see any patterns. You are not supposed to see any patterns in a normal web browser.

**Comment by flaneurette** [comment]
I guess I am rather sensitive to patterns... the patterns are faint though, sometimes they appear like random letters, as in a CAPTCHA.  However, it makes sense, as uniform distribution is also used in statistics, that is how they can detect patterns. With Gaussian, that is much more difficult.

**Comment by photopea** [comment]
So can you show it to me, please? :D

**Comment by flaneurette** [comment]
Attached PSD in zip. I made a hidden layer that shows what I see.

[uniform.zip](https://github.com/photopea/photopea/files/7286592/uniform.zip)

**Comment by photopea** [comment]
I am attaching what you sent me. 

I really think it is a normal behaviour. If you throw a black sand on a white paper, you would see similar things. If you toss a coin 1000 times, you can not complain that there were four heads in a row. It is not a broken coin. If a cloud in the sky looks like a horse, it is not a broken cloud. Such things are natural.

![uniform](https://user-images.githubusercontent.com/15955558/136048744-d4e45551-6276-4966-9c34-01e154802ef0.png)

**Comment by flaneurette** [comment]
Interesting.

Does it depend on how one tosses the sand? :)

It seems, if we toss it from a Gaussian method, do we toss it in a bell curve, which seems to create less patterns: if we toss sand from above there seems to be better distribution. But if we toss it from angles, or rectangular points, more patterns can appear because the angle of tossing? as the angle is the restricted by many predetermined factors, such as resistance, wind and densities.
