### ISSUE TITLE
i cant copy paste images

### ISSUE THREAD

**Issue by hetrgsefadfegrh6jr7** [photopea/photopea#3805]
I copied and image but im having problem pasting, when i ctrl + V it creates a new artboard any way to avoid this issue?

**Comment by photopea** [comment]
When I paste an image in Photopea with Ctrl+V, a new layer with my image is created, but no new artboard :(

What exactly should I do to see a problem which you describe?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
