### ISSUE TITLE
Unable to open saved .psd file

### ISSUE THREAD

**Issue by tittlejoseph** [photopea/photopea#3806]
I took time to build a file, exported as PSD to local machine and later next day when trying to open, it is not allowing me.

**Comment by ctaleck** [comment]
I tried saving a PSD using the Opera browser on a Mac and I was unable to open the file.

![image](https://user-images.githubusercontent.com/8421373/135910426-95881019-5534-4b76-9aa4-27a58a14cf3e.png)

Later, I saw that it was showing as zero bytes.

**Comment by photopea** [comment]
There used to be a bug in Opera, which resulted into PSD being an empty file in some cases. So your work is lost, as opera did not save it into a computer, as Photopea asked it to do :(

I think Opera fixed it, so just update your Opera. Or try some better browser, like Safari or MS Edge.

**Comment by ctaleck** [comment]
Opera version was 78.0.4093.231 error occurred.

Opera version after update is 79.0.4143.72, and I confirmed the save PSD bug to be fixed.
