### ISSUE TITLE
Brush smoothing issue when drawing with graphics tablet.

### ISSUE THREAD

**Issue by af-n** [photopea/photopea#3808]
When I draw with Photopea and I have the smoothing cranked up to a high number, it doesn't register when I try to make a dot.

**Comment by photopea** [comment]
I tried to set the Smoothing to 100%, I click and release a mouse, and it draws a "dot". Is this what you are doing? If not, what are you doing?

**Comment by af-n** [comment]
By the way I'm using a drawing tablet, not a mouse. However, I think I found the specific problem, dots don't register properly with a drawing tablet when I have _pressure sensitivity_ on. Check video for what I mean.

https://user-images.githubusercontent.com/47723802/136122148-e3c802da-8a99-4c92-9563-8ab13806fddf.mp4

.

**Comment by photopea** [comment]
The "Smoothing" works like you are dragging the pen on a "thread", it will always be located a couple of pixels "behind" the real cursor - https://www.youtube.com/watch?v=U5p73v9r_F8   Is that what you mean?

**Comment by af-n** [comment]
I honestly don't know how to explain it, but Photopea's smoothing does not work like how Photoshop's does. It also does not feel as fluid as Photoshop.

https://user-images.githubusercontent.com/47723802/136621662-5ac68f66-073e-449b-8ab7-f759a61b4287.mp4

**Comment by photopea** [comment]
Could you maybe explain, what exactly is different? I do not have a graphics tablet :(
