### ISSUE TITLE
Feature Request: Two/Three finger-tap to step backward/forward

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3810]
Almost all the drawing APP I have tried has such a handy feature. It would be nice if Photopea could have such a feature too!
![Screenshot_20211006_031800_jp co celsys clipstudiopaint googleplay_edit_776610061739828](https://user-images.githubusercontent.com/79258245/136089870-d462d439-501f-43ea-8164-c3f8f26a7835.jpg)

**Comment by photopea** [comment]
We already have a two-finger tap for stepping backward. Unfortunately, it is not possible to implement a three-finger tap to step forward.
