### ISSUE TITLE
Photopea opens window then freezes

### ISSUE THREAD

**Issue by Skyun-arse** [photopea/photopea#3817]
I opened a window saying Layer style then the window just stops responding, it was stuck on the screen. I could not close it, and any other button I press does not do anything. The only thing that resolved it was to refresh the page, deleting my work.

**Comment by photopea** [comment]
Can you make it happen again? We need steps to reproduce the problem, to be able to fix it :(

**Comment by photopea** [comment]
So it is working now? Maybe you have browser extensions, which are breaking Photopea.
