### ISSUE TITLE
Object becomes completely black when becoming a certain size

### ISSUE THREAD

**Issue by casperzwaart100** [photopea/photopea#3819]
Hey,

I am having this issue when using Photopea on Firefox, whenever I make an object bigger or merge 2 objects together that are big when combined it becomes completely black. 
Here is a before picture: 
<img width="912" alt="Screenshot 2021-10-07 at 20 05 58" src="https://user-images.githubusercontent.com/85107635/136439618-2534901f-d69f-4306-baf3-eed8870e9ac3.png">

On the right you can see the 2 objects seperate, they're the black blocked parts. 

Here is the picture after they're merged:
<img width="912" alt="Screenshot 2021-10-07 at 20 06 20" src="https://user-images.githubusercontent.com/85107635/136439774-ada2f81c-6ca9-4808-95b8-9b418254d5a7.png">

I've used different browsers using Photopea, Safari just boots you out before you even get to that point, Chrome crashes the page. So it might be a browser issue, but I wanted to let you know anyways. 

I love the website, thank you.

**Comment by photopea** [comment]
Can you please send me your PSD file to support@photopea.com ? :)

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by photopea** [comment]
Can you update your operating system or GPU drivers? Are you using any exotic browser, or a beta version of a browser?

Try these steps: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/
