### ISSUE TITLE
Ruler

### ISSUE THREAD

**Issue by Alexandr-plohoj** [photopea/photopea#382]
I am grateful to you for creating this application. I have to make websites by templates, that give me and I lack one very important tool - a ruler. With this tool, I would like to measure the distance from one block to another. I and many others will be happy if you add to the application a tool such as a ruler.

**Comment by photopea** [comment]
Hi, there is a ruler in View - Ruler.

Another rulers are in the Move tool: enable Distances at the top. Select your object (layer) and move your mouse over another object. You will see the distance between objects.

https://imgur.com/r7vyvTI

**Comment by Alexandr-plohoj** [comment]
Not all objects are achievable when using the distance tool, for example, as on the image of the border of a circle or there is a need to measure up to a certain part of object. I would like to set the beginning and end of the ruler.
![2017-11-22](https://user-images.githubusercontent.com/31807767/33147132-bdffd612-cfd7-11e7-970c-2947daf00c09.png)

**Comment by Alexandr-plohoj** [comment]
I take care of every pixel that I have to count on a calculator.

**Comment by photopea** [comment]
Ok, I added a new ruler tool, it is under the Eyedropper.
