### ISSUE TITLE
The Bucket Tools Low Tolerance Levels Don't Work Well With Transparent Bits And Selection Bleeding

### ISSUE THREAD

**Issue by Kristopian** [photopea/photopea#3821]
You Can Have A Black Pixel And A Grey Transparent Pixel And The Web Editor Counts Them Both As The Same Color Even Though There Is 0 Tolerance And They Are Clearly Different Colors, Is This Just A Chrome Issue Or Is It More Widespread,
And When You Make A Selection With The Wand Or Lasso Tool, And Draw Using The Brush Or Pencil Tool It Sometimes Bleeds Through The Selection This Is A Kind Of Rare Occurrence And It Doesn't Really Affect Anything Unless You'r Doing Something Low Res.

**Comment by photopea** [comment]
Hi Kristopian, what is a "grey transparent pixel"? Do you mean a black transparent pixel? A black transparent pixel is grey only on a white background. It can be brown on an orange background, etc. It is still black, even if you decrease its transparency.
