### ISSUE TITLE
Premium Plan Not Yet Started

### ISSUE THREAD

**Issue by Vienster** [photopea/photopea#3822]
Hello,

I've sent a wire transfer for a year subscription two days ago. When will that plan start for me?

**Comment by photopea** [comment]
Hi, how exactly did you send a wire transfer? Our system requires paying with a card. Did you pay with a card?

**Comment by Vienster** [comment]
I've attached the route I took to pay. I tried paying with my card multiple
times, but the bank stopped the transaction, and I just used this route.
Since I found it, I figured it was an option for payment. The money is out
of my account.

**Comment by photopea** [comment]
Hi, could you please open  https://github.com/photopea/photopea/issues/3822 in your browser and write a reply there?

You are sending emails to GitHub.com and github does not show us attachments which you send them.

**Comment by Vienster** [comment]
[Photopea.pdf](https://github.com/photopea/photopea/files/7317556/Photopea.pdf)

**Comment by photopea** [comment]
I do not see the payment in our database yet. Let's wait a couple of days, I dont know how long these bank transfers take (they are probably paused on weekends).
