### ISSUE TITLE
Wacom Tablet not working on Chromium-based browsers

### ISSUE THREAD

**Issue by eduardomunhozr** [photopea/photopea#3824]
on linux using the standard drivers bundled with Zorin OS 16, the Intuos pen small tablet has its point and click captured but not its pressure sensitivity

**Comment by photopea** [comment]
Hi, did you enable "Stylus Pressure Controls Opacity", as described here: https://www.photopea.com/learn/brush-tools ?

**Comment by photopea** [comment]
The browser should give a website the value of the pen pressure. A website does not have any other connection to a device, we can work only with what we get from a browser :(

Maybe try these steps: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/
