### ISSUE TITLE
Eraser not erasing black and white filter

### ISSUE THREAD

**Issue by fportelos** [photopea/photopea#3832]
I have a classroom full of the same chromebook devices, that are updated. I had the students place a black and white mask over a color picture and then erase some of that mask. For a small percentage, it is not working. Just nothing happens.

This happened a few years ago. Haven't found a pattern. We restarted and even used different photos.

**Comment by photopea** [comment]
So this happened a few years ago? Is it still happening today?

**Comment by photopea** [comment]
I really need some steps how to reproduce it. Can you open Photopea and find steps, which always lead to the problem? I need to see the problem myself to be able to fix it. And I can not make it happen on my computer (but maybe I am doing something differently than you).

**Comment by fportelos** [comment]
Step one create a new canvas that is 1,000 by 1000 pixels
Step 2 copy an image from Google images
Step 3 paste the image into the canvas
Step 4 add a black and white mask using the black and white semi-circle in the layers section.
Step 5 click eraser and begin erasing the black and white mask layer. That's where it stops working on some machines all the same Chromebooks and two years ago it was ThinkPad lenovo's.

-Francesco A. Portelos
STEM Career Workspace

IS 27 Anning S. Prall
mrportelos.com

"The foundation of every state is the education of its youth." - Greek Philosopher Diogenes
________________________________

**Comment by photopea** [comment]
It is called a Raster Mask - https://www.photopea.com/learn/masks  

When you "paint with the eraser" into a raster mask, it "paints with white". There can be only shades of grey in the raster mask.

You can also buy a book about Adobe Photoshop to learn how these things work.

**Comment by photopea** [comment]
In the second part of the video, your background color is black: https://i.imgur.com/tIelpJk.jpg   While in the first part, it is probably white (it is not shown in your video).

**Comment by fportelos** [comment]
That was it! Thank you. That's what was causing the problem.

-Francesco A. Portelos
STEM Career Workspace

IS 27 Anning S. Prall
mrportelos.com

"The foundation of every state is the education of its youth." - Greek Philosopher Diogenes
________________________________
