### ISSUE TITLE
Duplicate layer - layer name + 'copy' - needed in Actions made in PS

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3834]
Now when you have a layer for example "Background" and want to duplicate it by dragging on the new layer icon or using CTRL+J, you have "Layer 1" and next "Layer 1 copy"

It should to be [Original layer name] + 'copy'. In my example it should to be 'Background copy'; 'Background copy 2' etc.

Why? Because layer names are using in ATN files with actions.

**Comment by photopea** [comment]
Could you check if it works as it should now? Otherwise, share your ATN file, so that I can use it for testing.
