### ISSUE TITLE
3 Bugs in one (Resample image; artboard background; artboard history)

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#3838]
I was about to make 3 issues, but is too much XD and i have to leave, so i record  a video showing the 3 bugs at the same time'
[Uploading Screen recording 2021-10-14 15.11.26.zip…]()

**Comment by photopea** [comment]
E.g. if you have a red circle, a diameter of 3 inches, you can "sample" it (rasterize it) at a certain precision (one sample = one pixel).

E.g. you rasterize it at 300 x 300 pixels (DPI = 100). Later, you can resample it at 600 x 600 pixels (if you still have the vector data). That is what sampling means.
