### ISSUE TITLE
Export as wrong format displayed

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#384]
Sometimes when I do "Export as" it shows wrong format in dropdown list.
For example if I do:
1) Open pea.psd
2) Export as - DDS
3) Change Format to "GIF"
4) Save
5) Export as - JPG
6) Close "Save for web" window
7) Export as - GIF
->
Now it shows "PNG" instead of "GIF" in Format field.

**Comment by photopea** [comment]
It should be fixed now. thanks!
