### ISSUE TITLE
it wont let me change the font!

### ISSUE THREAD

**Issue by ashleyroseeeeeeeee** [photopea/photopea#3842]
everything is working fine, but when i go change the font the entire program freezes and wont work anymore. ive closed it and opened it multiple times, but it just wont change.

**Comment by sash000000** [comment]
> everything is working fine, but when i go change the font the entire program freezes and wont work anymore. ive closed it and opened it multiple times, but it just wont change.

Found this solution from Photopea  https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
It is usually caused by browser extensions. I will close it now.
