### ISSUE TITLE
DDS file

### ISSUE THREAD

**Issue by KiaraTu** [photopea/photopea#3847]
When I open a dds file or when I save it with an alpha channel and then open the file later, the alpha channel did not appear. 
Only appear the RGB channels and no alpha.  
What can I do to correctly save and open an image with an alpha channel in Photopea?

**Comment by photopea** [comment]
Hi, what do you mean by an alpha channel? Do you mean transparency?

I made a document with transparent parts in Photopea, I saved it as a DDS. I loaded that DDS into Photopea and it looks the same (transparent areas are preserved). So what exactly do you mean?

**Comment by KiaraTu** [comment]
- [ ]

**Comment by KiaraTu** [comment]
> Hi, what do you mean by an alpha channel? Do you mean transparency?
> 
> I made a document with transparent parts in Photopea, I saved it as a DDS. I loaded that DDS into Photopea and it looks the same (transparent areas are preserved). So what exactly do you mean?

I mean that when I open the dds file that I just created with an alpha/transparency channel, this channel disappears and an cant edit. 
exemple:
![image](https://user-images.githubusercontent.com/92692897/137645353-af393c31-5145-43c2-9d38-11a932f0cb5a.png)

When I open it again:
![image](https://user-images.githubusercontent.com/92692897/137645383-7df33102-244b-466c-9022-d7b4a0a583ee.png)

**Comment by KiaraTu** [comment]
I'm trying to make a normal em specular map for a game creation. 
I'll put here my psd file.
When I saved it in dds and import it to the program that I use to create things for The Sims 4, it looks like a png file.. not dds with transparency/alpha channel. 
[Normal and Shaddow Map.zip](https://github.com/photopea/photopea/files/7360890/Normal.and.Shaddow.Map.zip)

**Comment by photopea** [comment]
Do you have an example of such a DDS file, which works well in the Sims 4, so that we can see what you need?

I have a following DDS file with four channels, does it work well in your case
[bc3compressed.zip](https://github.com/photopea/photopea/files/7574815/bc3compressed.zip)
?

**Comment by photopea** [comment]
I have to close it because of lack of details.
