### ISSUE TITLE
Keyboard Shortcuts window (Firefox)

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#385]
In Firefox it seems like some keyboard shortcuts are missing in Keyboard Shortcuts window. Maybe it is bug in Firefox browser because I looked and HTML and CSS is there but nothing is showing. 

https://imgur.com/Z6bBSKy

**Comment by photopea** [comment]
This is really strange. I reported it to Firefox and hope they will solve it: https://bugzilla.mozilla.org/show_bug.cgi?id=1420528
