### ISSUE TITLE
Open the Color Picker after double-clicking on the color spot in the Color Window (on the right sidebar) 

### ISSUE THREAD

**Issue by xan2622** [photopea/photopea#3850]
Feature request: 
**Allow double-clicking on the color in the Color Window (on the right sidebar) to open the Color Picker.**

<img src="https://user-images.githubusercontent.com/1732773/137779648-59bdfad4-16c9-4153-a197-cd82a0c298c0.png" width="25%" height="25%">

Currently, the Color Picker window is only accessible from the color in the left toolbar: 

<img src="https://user-images.githubusercontent.com/1732773/137778797-46fd9146-8b93-4622-b5c4-f059e931ab72.gif" width="75%" height="75%">
I think it would be convenient to be able to open the Color Picker window by double-clicking on this other color spot.

**Comment by photopea** [comment]
done :)
