### ISSUE TITLE
Feature request: "Chameleon Adaptive Palette" -like plugin

### ISSUE THREAD

**Issue by xan2622** [photopea/photopea#3851]
Hi Ivan.

I'd love to see a photopea plugin similar to **Chameleon Adaptive Palette**: 
https://cubebrush.co/reeks/products/mnci3q 
https://youtu.be/A_otv3IYaco

This plugin would allow to quickly pick an alternative color from different palettes (Brightness, Hue, Intensity, Tint, Tones, RHChroma, Saturation, Complementary colors, Analogous colors, Previous colors, Custom colors, etc..)

These palettes (composed of rows of 10 colors gradiants) would adapt themselves to the current front color.

This plugin would be very helpful for digital painters.

**Comment by hxim** [comment]
@xan2622 @photopea @MichalSZZ 
Just finished my adaptive palette plugin test version. You can try it via this link:
https://www.photopea.com/#%7B%22environment%22:%7B%22plugins%22:%5B%7B%22name%22:%22Adaptive%20Palette%22,%22url%22:%22https://hxim.github.io/TwemojiPlugin/adapal/adapal.html%22,%22width%22:380,%22height%22:400,%22icon%22:%22https://hxim.github.io/TwemojiPlugin/adapal/icon.svg%22%7D%5D%7D%7D
What do you think?

**Comment by photopea** [comment]
@hxim wow, thanks a lot!

@xan2622 do you like it? Should I add it to Photopea (so that it is available for everyone) ?

**Comment by xan2622** [comment]
![amazed](https://user-images.githubusercontent.com/1732773/142495492-1ece5ddc-c55f-4e80-8592-49a0d8beb31c.gif)

I am speechless. 😮 
@hxim THANK YOU, THANK YOU, THANK YOU 

@photopea Sure, please do (if it's ok with hxim) ; I can't stop testing his palette plugin (and I will report any bug if I notice one, but for the moment, I have found none).

**Comment by photopea** [comment]
Ok, I have added it into Window - More - Adaptive Palette :) 

I noticed, that if you change the color in Photopea, your plugin detects it, which is great :)

**Comment by xan2622** [comment]
Would it be possible (to increase the discoverability of this plugin) to enable it by default for a week or two? (or forever? lol I like the plugin so much)

And if the idea to add a [Mixer Brush](https://github.com/photopea/photopea/issues/3985) is accepted, this will make Photopea a really interesting tool to do _digital painting_. I can't wait.

**Comment by xan2622** [comment]
Hi @hxim. I have another idea for your plugin.

Would it be possible to add a **new row to display a gradient of colors between the foreground and the background color**?
Some kind of "color mixer" between two colors: 

Mock-up:
<img src="https://user-images.githubusercontent.com/1732773/142739410-3bff10d2-ea94-42b3-976e-b6bbf6fc636d.jpg" width="33%" height="33%" />

Krita has a similar feature: https://docs.krita.org/en/general_concepts/colors/color_mixing.html#the-digital-colors-mixer
But I think only one row would suffice.

Here are some similar Javascript projects (maybe their code could help you develop this gradient between FG and BG colors): 
- https://meyerweb.com/eric/tools/color-blend/#9900FF:CCCC00:10:rgbd
- https://www.cssscript.com/javascript-library-generate-linear-gradient-color-stops-gradstop-js/
- https://www.w3docs.com/tools/color-mixer

**Comment by hxim** [comment]
@xan2622 Hi, yes I added row "FG to BG" according to your picture. Also I added ability to right-click on palette to select background color. Colors for gradient are for now mixed same way as is in "Previous" row - it varies brightness and saturation and hue with linear interpolation between two colors.

**Comment by xan2622** [comment]
Thank you for all what you've done, hxim. 

---

To achieve my other suggestion (that I posted in my [second comment](https://github.com/photopea/photopea/issues/3851#issuecomment-946037973)): 

> Also, there could be another row (another palette) showing a range of colors used in the opened image?
> Maybe you know this instagram page that shows palettes used in movies: https://www.instagram.com/colorpalette.cinema/

... I have found this project on Github: https://github.com/lokesh/color-thief
Demo: https://lokeshdhakar.com/projects/color-thief/

Could it be used to add another row that would display colors taken directly from the current Photopea project?

**Comment by hxim** [comment]
@xan2622 
Hi I added "From image" row using the project color-thief you linked. I set it so it should update every 8 seconds because it is needed to transfer/export image from photopea to analyze its colors and it can take some time.

**Comment by xan2622** [comment]
@hxim : you rock! I don't know what else to say. ☺

**Comment by xan2622** [comment]
@hxim : do you have a Paypal account or a Patreon page (to let me thank you with a donation) ?

**Comment by hxim** [comment]
> @hxim : do you have a Paypal account or a Patreon page (to let me thank you with a donation) ?

No, I don't.

**Comment by MichalSZZ** [comment]
@hxim I am wondering if it will take much time to add a feature for save the palette (from image) as a file who can be added as a Swatches or exported to another program.

For example I am making a set of body parts extracted only with skins. And from those layers I am making a universal Swatch for digital painting for skin tones.

**Comment by hxim** [comment]
@MichalSZZ Hi I just added ability to export each line of palette as ACO file. You click "Ex" button and then somewhere on line of colors you want to export and it will download ACO file with those colors. Let me know if it works as expected.

**Comment by MichalSZZ** [comment]
@hxim  It has very hard to understand UX but works fine :) Thank You!
