### ISSUE TITLE
Can't type texts

### ISSUE THREAD

**Issue by lilymyname** [photopea/photopea#3855]
Even if you try to type it, it doesn't work. Only the phrase "Fonts not loaded yet" comes to the top. Can you fix it?
![20211019213800](https://user-images.githubusercontent.com/92796950/137910880-0471433c-289e-4956-9a57-81fd4b1ae798.png)

**Comment by Janovat** [comment]
i tried incognito mode as well

**Comment by ryanoc1** [comment]
This happens intermittently for me. Some days I cannot access fonts and have to give up, using incognito windows as well. I have not yet been able to determine a pattern. When it next fails I will try your link above (currently the link downloads a font and fonts work in photopea for me)

**Comment by photopea** [comment]
It should be fixed now.
