### ISSUE TITLE
text is pixelated

### ISSUE THREAD

**Issue by mathtime4345** [photopea/photopea#3856]
![image](https://user-images.githubusercontent.com/86930466/137911215-ab89240a-93e3-4e88-89e9-4f214dce7157.png)

**Comment by photopea** [comment]
That is the way raster graphics work. Try to increase the text size and zoom out a bit.

**Comment by MichalSZZ** [comment]
Look on this parameter 
![obraz](https://user-images.githubusercontent.com/38118273/137969546-a70e16fe-b555-4255-ba0c-ce18dd38a2cc.png)
"Aa" should not be set to "none"

or blending mode for layer is not set to "dissolve"
![obraz](https://user-images.githubusercontent.com/38118273/137969762-d5846d21-afd8-480d-a022-ab31821b152b.png)


I don't know if it it your problem but check this out

**Comment by photopea** [comment]
I guess it has been solved.
