### ISSUE TITLE
Bolding text function not working

### ISSUE THREAD

**Issue by NYBPB** [photopea/photopea#3857]
Hello,
I was wondering if someone can help me trouble shoot for why the bold text function is not rendering properly? You will see that when I open the file, the bold text is showing, but when I go to click on the text to edit, the bold goes away and then I cannot make it look like it's bolded again (even though the text styles button on the side has the bold selected).

I have tried on Chrome, incognito, and even the downloaded app version. I have tried on my old Windows 10 and this new Windows 11 computer. Any insight would be greatly appreciated, thank you!

![Open](https://user-images.githubusercontent.com/92797575/137915942-ef0b92f5-796e-439c-a38a-1014b6d9270d.png)
![Edit](https://user-images.githubusercontent.com/92797575/137915946-4dd5d1e2-ada9-460e-8664-7ccb76b8b5b9.png)
![Not Bold](https://user-images.githubusercontent.com/92797575/137915949-b5a1bb76-519c-4c12-84a5-de91ffff9fdf.png)

**Comment by photopea** [comment]
Could you send me your PSD file to support@photopea.com? Was it made in Photopea?
