### ISSUE TITLE
I used a text tool, but I can't see the letters.

### ISSUE THREAD

**Issue by Haereum** [photopea/photopea#3859]
I'm using Photopia in a useful way.
However, it has not been available since October 19, 2021.
This is because it is not connected to the photopia site.
However, the problem was solved today and used again.
However, there was a problem with the text tool I used.
The handwriting is not input.
On the layer, letters are input and marked, but no letters are seen on the image.
An answer to this is required.

I am not an English speaking person. Therefore, I am sending this article to you using a 

![화면 캡처 2021-10-20 114914](https://user-images.githubusercontent.com/92837371/138020030-7a182548-0de2-43b1-9669-233113bf5539.png)

**Comment by photopea** [comment]
Do you see a message about loading a font?

Try these steps: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it, because the person stopped responding :(
