### ISSUE TITLE
[MacOS] Cannot open any files

### ISSUE THREAD

**Issue by ryanoc1** [photopea/photopea#3860]
From Chrome on mac File -> Open does nothing when I click it. On windows it opens the file menu. Had refreshed page with cache disabled before trying. Also tried a new incognito window. This was working before a few days ago.

Google Chrome | 94.0.4606.81 (Official Build) (arm64)

These are the only messages shown in the debug console:

```
Service worker active
pp.js:8354 Extra parameter Spcn
pp.js:186 2
```

Additionally dragging and dropping a file onto the photopea canvas to try and open it does not show a highlight rectangle on the canvas border, and releasing the mouse does nothing.

**Comment by photopea** [comment]
Hi, try these steps and let me know if it helped: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/
