### ISSUE TITLE
Photopea web app doesn't work at all

### ISSUE THREAD

**Issue by lilymyname** [photopea/photopea#3862]
I read the guideline "what to do when photopea doesnt work", and tried everything in that. But nothing helped. My photopea downed at start page and keep loading. What should I do to solve this problem?
![20211021003409](https://user-images.githubusercontent.com/92796950/138130135-7f50059d-56c7-4f1d-993a-cb55d313c82b.png)

**Comment by photopea** [comment]
We have about 3,000 users from Korea every day. It seems like it works well for most of them, as you are the only ones reporting it. Can you ask your internet provider about it? I really think your internet provider is responsible for unavailability of websites.

**Comment by photopea** [comment]
I have to close it because the person stopped responding :(
