### ISSUE TITLE
Artboard - Tool is deselected and duplicated artboard goes far away

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3863]
[Screen recording 2021-10-20 17.04.04.zip](https://github.com/photopea/photopea/files/7384020/Screen.recording.2021-10-20.17.04.04.zip)
Here is a video showing both bugs.

First. i don't know if it intended, but if you have the artboard tool selected, and then select any layer on the layers panel, it will change to move tool

And the second is, when i duplicate for the third time an artboard with its content, it duplicates, but goes way to far down.

Third, i might say, that after duplicating or creating and artboard with the (+) button, the new artboard should be automatically selected, so i can duplicate quicker, rather than reselecting every time. (tell me if you understand)

Here is the PSD: 
[DR.zip](https://github.com/photopea/photopea/files/7384021/DR.zip)

**Comment by photopea** [comment]
it should be fixed now, thanks for reporting! :)
