### ISSUE TITLE
The photopia page does not open, and even if it opens, text tools cannot be used.

### ISSUE THREAD

**Issue by Haereum** [photopea/photopea#3864]
The photopia page does not open, and even if it opens, text tools cannot be used.

I am a person living in Korea. As of today, he was using Photopia very well until two days ago. However, as of October 19, 2021, we are not using Photopia at all.
I had to load for a very long time, but the page didn't open.
I tried again today, and I finally opened the page, but it's still the same that I can't use it. There is still a window saying that it is loading, and the text tool I need to use is still not available.

I had to turn my computer off and on dozens of times because of this problem, and there is no problem solved.

I want to use Photopia. If you know anything about this, please give me an answer.

**Comment by photopea** [comment]
We have about 3,000 users from Korea every day. It seems like it works well for most of them, as you are the only ones reporting it. Can you ask your internet provider about it? I really think your internet provider is responsible for unavailability of websites.

**Comment by photopea** [comment]
I have to close it because the person stopped responding :(
