### ISSUE TITLE
Add support for Jpeg-XL (.jxl) files

### ISSUE THREAD

**Issue by rcoenen** [photopea/photopea#3867]
Please add support for opening and saving of JPEG-XL (.jxl) files

**Comment by photopea** [comment]
I will wait, untij JPEG-XL becomes more popular. Moreover, I do not know about any Javascript library for parsing JPEG-XL, which we could use.

Photopea can already open AVIF.

**Comment by bradietilley** [comment]
18 months since the last comment here. JPEG-XL steadily

**Comment by photopea** [comment]
People open 600,000 JPG files in Photopea every day. Our JPG decoder is around 4 kB.

I think people will open around 6 JXL files in Photopea every day. A JXL decoder is like 50 kB I guess.

JXL images still can not be opened in any browser. But you can open it in Photopea! Press Window - Plugins, and look for "JPEG XL".

**Comment by rcoenen** [comment]
I think this is more about using Photopea as a workhorse tool to *produce* JXL by webdesigners etc
