### ISSUE TITLE
How to transform selection

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#387]
I selected some shape and then I wanted to rotate it (only selection without image under it).
I couldn't find simple way how to do it.
After some time I found way - i can 1. create new layer 2. fill it 3. do free tranform 4. delete layer
but it is rather complicated may be there is some key or function in Photopea to do it directly or you can add some feature so you can apply free transform on selection directly...

**Comment by photopea** [comment]
Hi, I guess in your case, the selection could be replaced by raster mask:   https://www.photopea.com/learn/masks

Photoshop has an option Edit - Transform selection. It is a different action that the Free Transform. Would you like to have it in PP?

**Comment by hxim** [comment]
Yes this action would be very useful:
https://www.photoshopessentials.com/basics/selections/transform-selection/

**Comment by photopea** [comment]
It has been implemented, see Select - Transform Selection.

It is a different tool than the Free Transform, you can not enable it with Ctrl + T.
