### ISSUE TITLE
Artboard - When dropping an image on Photopea, it goes to (0,0) on canvas

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3872]
If i have multiple artboard, and i drop an image on Photopea, it goes to (0,0) on canvas, no (0,0) on the selected artboard.

So, mos of the time the layer is in the artboard's folder, but out of the artboard bounds.

![image](https://user-images.githubusercontent.com/11801254/138530505-adc24189-4afc-465d-921b-92d3c521ce3a.png)

It should go to (0,0) on the selected artboard

**Comment by photopea** [comment]
You said "dropping" multiple times, so I was trying to drag-and-drop an image into an artboard (which worked well).

I have fixed the bug with Ctrl+V :)

**Comment by avagp** [comment]
Sorry for being imprecise. :(
