### ISSUE TITLE
CMYK: color picker - imputs for CMYK colors

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3883]
For inputs fields like in RGB or HSB. All in 0-100%.
It helps when you have to set color as a CMYK in the project

**Comment by photopea** [comment]
Ok, I have added the "CMYK gammut" checkbox to the bottom of the Color Picker. It will mark the "unprintable colors" with gray.

I think entering CMYK values is too confusing and nobody really does that, so I will not add it to Photopea.

**Comment by avagp** [comment]
It's perfect!

As you said, nobody will enter numbers, but the gamut warning is perfect.

Thank you very very much.

Now I can work much better with the printer. Even create stuff from scratch
now with the warning


╰(＾3＾)╯
