### ISSUE TITLE
Please make Shift and Alt work in shape tools the same way as in the select tool

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3889]
To create a square selection, we can enable Shift before starting drawing. But to create a square with rectangle tool, Shift can only be enabled while we are drawing. It's not very comfortable for mobile phone users.

**Comment by photopea** [comment]
Ok, I think now, the shape-drawing in Photopea should work the same as in Adobe Photoshop.

**Comment by nothingshiru** [comment]
Thanks
