### ISSUE TITLE
The anti-aliasing effect on the brush is not very good

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3891]
See the differences between Photopea and Photoshop. The values of brushes are same. (size: 20px; hardness: 100%; opacity: 100%; flow: 100%; smoothness: 0%;)

left one: Photoshop;
Right one: Photopea;
![screenshot_20211027_103724](https://user-images.githubusercontent.com/79258245/138990927-34d7620f-11ab-405e-bd0d-4af408608a7a.jpg)

Lower ones: Photoshop;
Upper ones: Photopea;
![screenshot_20211027_103746](https://user-images.githubusercontent.com/79258245/138991029-28370061-c5ee-4f4e-abba-fcef1e29074c.jpg)
![screenshot_20211027_103830](https://user-images.githubusercontent.com/79258245/138991038-d03b5c02-d22e-4092-b925-284ee6f2a7ce.jpg)

**Comment by photopea** [comment]
Is it better now?

**Comment by nothingshiru** [comment]
It is better, but still not great. 

I created paths and stroked them in Photoshop and Photopea. Here is the psd. 
[new.psd.zip](https://github.com/photopea/photopea/files/7450262/new.psd.zip)
You can zoom in to observe the difference.

**Comment by photopea** [comment]
I have improved it further.

**Comment by nothingshiru** [comment]
It looks weird in a straight area.
![new](https://user-images.githubusercontent.com/79258245/139683462-bb8f6ca5-7606-4699-9abc-ad88274df134.png)

**Comment by photopea** [comment]
I am afraid I don't know how to make it better, so I give up :(
