### ISSUE TITLE
The top and bottom margins of the “Anchor" in Canvas Size dialog need to be increased

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3893]
Now it's not easy to tap the top part or bottom part with finger.
![IMG_20211028_004822](https://user-images.githubusercontent.com/79258245/139110937-51b656bc-0bbf-4cd0-a926-4698a62ebbe4.jpg)

It would be better to make it like this.
![screenshot_20211028_003611](https://user-images.githubusercontent.com/79258245/139111160-fee6d505-d97c-4ef4-b458-e8acaa2023d8.jpg)

**Comment by photopea** [comment]
fixed, thanks for reporting :)

**Comment by nothingshiru** [comment]
Top margin is necessary. Without it, we can't tap the top row with finger.
