### ISSUE TITLE
Replace the "Filter" checkbox in Layers panel with a "All" option

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3897]
Remove the "Filter" checkbox, then add a "All" option into the dropdown menu. The interface can be more clean. 
![Screenshot_20211029_004442](https://user-images.githubusercontent.com/79258245/139300075-427c9063-2c1b-4b4f-98cf-e3bc949345dc.jpg)
What do you think?

**Comment by photopea** [comment]
I have removed the line with filters. You can add them back by clicking the "menu look" button at the bottom left corner.

**Comment by nothingshiru** [comment]
It doesn't look great :(

I think it is better to add it in top-right, like in History panel and Channels panel. 

like this
![Screenshot_20211121_003001_com microsoft emmx](https://user-images.githubusercontent.com/79258245/142734287-3728d849-5223-4501-b5d9-368918af7fe8.jpg)

**Comment by nothingshiru** [comment]
I just found that the "All" option I suggested is unnecessary, and so is the "Filter" checkbox. When "Kind" is selected but none of the icons on the right is checked, all layers are already displayed on the Layers panel.
![IMG_20211121_005654](https://user-images.githubusercontent.com/79258245/142735002-e6233db9-2d62-4d16-9cd3-3d287a656e49.jpg)

**Comment by photopea** [comment]
I have added the "context menu". I think it is nice to be albe to enable / disable all filters with one click, without losing filter settings.

**Comment by nothingshiru** [comment]
Oh, I didn't think about it.

I think filter should be disabled when unchecked Filter in context menu. People may uncheck Filter in context menu by mistake while there are filters enabled, then can't find they layers.
