### ISSUE TITLE
Properties - Solid Color Fill

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#390]
When you make some vector shape in Properties - Layer
 there is "\<b\>Solid Color Fill\</b\>" (with those \<b\> tags visible)
Also can you change it so if you select some color here and make new shape it will use selected color. Now it seems to always use red color so if you make more shapes you need to change color for each shape manually.

**Comment by photopea** [comment]
Hi, it is fixed now. The "vector shape style" (fill and stroke) now works the same way as text style. There is a "global" setting. Once you select some layer, the global setting is changed.
