### ISSUE TITLE
Best way to run Photopea on Ubuntu-based Linux?

### ISSUE THREAD

**Issue by wbrells** [photopea/photopea#3900]
Until very recently it seemed possible to "install" Photopea as a "Snap" or "Flatpak" app on Linux systems such as Zorin or Ubuntu. Now, Photopea doesn't appear at all in the Snap Store and the version in Flathub won't install! I know that Photopea can be run from a browser, but it looks nicer when "installed" without menu bars, etc. Is there, I hope, a new recommended way of running Photopea in Linux?

BTW I just noticed a new "Snap" app called librephoto which claims to be a downloaded version of Photopea, and I wondered if this a legitimate app? (I tried installing it, but the program claimed a file was missing and would not start!)

Many thanks,

Wayne

**Comment by vikdevelop** [comment]
> Many thanks to everyone for their suggestions! It seems the best way to "install" Photopea is to:
> 
> 1. Install Chrome via the appropriate ".deb" file.
> 2. Bring up Photopea and "install" it.
> 3. Have Chrome create a Shortcut for Photopea. This will place an icon on the desktop.
> 4. Right click that desktop icon and select the Allow Launching option.
> 
> It should now be possible to run the "installed" Photopea by clicking on the desktop icon.
> 
> Wayne

@wbrells Hi. I maintain Photopea on FlatHub. What are the specific problems with installing Photopea from FlatHub? When you enter the command:  `flatpak run com.github.vikdevelop.photopea_app`  what does it tell you?

**Comment by wbrells** [comment]
I suspect that the FlatHub install of Photopea should work fine! However, I'm trying to avoid the extra overhead & file space incurred by either FlatHub or Snap. Since Photopea is a web application and can be **installed directly from the Linux version of Chrome** I don't really see the need for anything else...

**Comment by smysamet** [comment]
Hi, I just clicked install Photopea from More section on the top menu. But it doesn't work offline. How can I use Photopea offline because I sometimes my Wifi goes off. @photopea

**Comment by photopea** [comment]
Can you open www.Photopea.com in your web browser when you are offline? It is not related to the "install" option. But if your internet is "slightly working", it will still try to load the actual website. You need to disconnect from the internet completely.

**Comment by smysamet** [comment]
I didn't change anything but it started to work offline now. Thanks anyways.
