### ISSUE TITLE
2020 ps warp  Is it supported

### ISSUE THREAD

**Issue by muyichuanqi** [photopea/photopea#3901]
2020 ps warp  Is it supported

**Comment by muyichuanqi** [comment]
![cb53ae530f69ad9a8d075ecee27c4a38](https://user-images.githubusercontent.com/12714782/139516386-df1cdb3a-cd12-41ce-b968-4fce233b9574.gif)

**Comment by muyichuanqi** [comment]
![37d12f2eb9389b50dd46af01e709f3d4e6116ee9](https://user-images.githubusercontent.com/12714782/139516412-57a717ca-be0b-4927-b31b-54ac138b9cb1.jpeg)

**Comment by scbizu** [comment]
For some more details:

Photopea currently do not support export psd with puppet warp as svg format , the exported `.svg` file do not contain the `path` metadata  , so that the smartFilter like PuppetWarp cannot render to the svg file .

I tried to use [ag-psd](github.com/Agamnentzar/ag-psd) to parse the psd and extract the `warp.customEnvelopeWarp`'s `meshPoints` , and use these mesh points to rewrite the svg file via [warp.js](https://github.com/benjamminf/warpjs) , things get better but we are tightly depend with the photopea , and really wish photopea can impl it .

Ping me if you need some other informations .

**Comment by photopea** [comment]
@scbizu interesting. How do you represent a raster image with a Puppet Warp in SVG? Do you save plain pixel data, or you have the original image + a transformation?

**Comment by scbizu** [comment]
@photopea The latter , original image + transformation , but the algorithm is really case-specified , which means I need to resolve every pixel adjustment for different image , but the result is not always perfect though .

With the plain pixel data replacement , things will be better ?  I try to use the python tool [psd2svg](https://github.com/kyamagu/psd2svg) to do the stuff , which is , first do the SmartObject Puppet Warp and resource replacement and then use `psd2svg` to export the svg file .  I find that the embed SmartObject image(the svg `g.image` tag) was edited  , but the result is better than my `original image + transformation` implementation . However, the limitation of this way is that I cannot replace the SmartObject image to the other image unless I do the image manipulation by myself , it is really hard with my poor graphic knowledge base :( .

**Comment by photopea** [comment]
I have implemented this feature. Let me know if it works as you expected.

**Comment by scbizu** [comment]
@photopea  Could I know how you impl it ? I tried to export some psd with the puppet warp but it seems that nothing happened .

**Comment by photopea** [comment]
I am afraid I can not disclose the details of my code. 

"I tried to export some psds with the puppet warp but it seems that nothing happened" - what does it mean? Is there a problem in Photopea?

**Comment by scbizu** [comment]
@photopea  I am sorry for my offense . Here are some my reproduce steps: 

* Create a .psd file with puppet warp in photoshop .
* Import the .psd file to photopea , and the puppet warp effect also can be recognized by photopea (the Puppet Warp layer can be found inside the parent layer).
* Export the .psd file as .svg (click the `add raster graphics`) 
* Open the .svg file , and compares it  with the .svg file without Puppet Warp , the former lost the layer information and only has one background image 

So , I have a question , does photopea impl it with the `plain pixel data` way  ?

**Comment by scbizu** [comment]
@photopea I am so sorry for my offense .

I tried the .psd with Puppet Warp , and exported it as .png and .svg , the results are different: 

For .png:

![CleanShot 2022-12-01 at 11 52 02](https://user-images.githubusercontent.com/8732481/204961982-d56266ef-b61e-4b86-ae63-e068adbb3174.png)

For .svg: 

![CleanShot 2022-12-01 at 11 55 18](https://user-images.githubusercontent.com/8732481/204962284-f30de15e-24f3-4796-ad35-1bb66caa35e7.png)

---

The Puppet Warp is missing if exports as the .svg file , and here is my [origin.psd](
https://drive.google.com/file/d/1rQ67RRFL2X-qJ0dsQ78OsjQYixquRy_k)

**Comment by photopea** [comment]
Oh, I see, I have fixed it.

Now, if your smart object has any smart filters (like Puppet Warp), a rasterized version is inserted into the SVG as a PNG file. That is the same as rasterizing the smart object layer before the export.

**Comment by photopea** [comment]
sorry, it should be fixed now.

**Comment by scbizu** [comment]
Cool , I see it ~

**Comment by zzq0324** [comment]
@photopea could you please share me which algorithm used to support warp/distort?  Thank you very much.

**Comment by zzq0324** [comment]
> warp.js
@scbizu could you please share me which algorithm used to support warp/distort by `warp.customEnvelopeWarp's` meshPoints ? Thank you very much.

**Comment by scbizu** [comment]
@zzq0324 If you are interested with puppet warpping , you should check this [repo](https://github.com/mikecokina/puppet-warp) and do some researches with [ARAP FLATTEN](https://www-ui.is.s.u-tokyo.ac.jp/~takeo/papers/takeo_jgt09_arapFlattening.pdf)

**Comment by zzq0324** [comment]
> @zzq0324 If you are interested with puppet warpping , you should check this [repo](https://github.com/mikecokina/puppet-warp) and do some researches with [ARAP FLATTEN](https://www-ui.is.s.u-tokyo.ac.jp/~takeo/papers/takeo_jgt09_arapFlattening.pdf) , but for the psd's `warp.customEnvelopeWarp` , I can not tell too much about it .

@scbizu Does puppet warpping can implement like this? 
<img width="712" alt="image" src="https://github.com/user-attachments/assets/0d5f7c2b-85ac-47a4-b77f-d7ebdad35885">
