### ISSUE TITLE
Language Filter

### ISSUE THREAD

**Issue by nasirkhan** [photopea/photopea#3902]
Is it possible to add a Language Filter for the fonts? Photopea is using the Google Fonts and it has options to show fonts by supported language of the font.

**Comment by photopea** [comment]
The Baloo Da 2 was not there, so I fixed the bug.

I dont think the alphabetic order would be good. Some writing systems does not correspond to the name of a language, or the name of a country (e.g. Cyrillic, Latin, Hangul, Kanji, Devanagari).

**Comment by nasirkhan** [comment]
Thanks for adding that. I recently found that Noto Sans Bengali and Noto
Serif Bengali has been added to the Google fonts. Can you add those fonts
too?

I think language name would be more user friendly than the alphabet script
names. Also Google fonts uses the language names so it might be easier find
the same fonts here as well. I have seen that many of the general user do
not know all the script names and many of the times it is not necessary to
know as well. But again it is your call to use the alphabet script name or
language name.

--
Nasir Khan Saikat
https://nasirkhn.com
