### ISSUE TITLE
Adblocker is Enabled

### ISSUE THREAD

**Issue by Vision11x** [photopea/photopea#3907]
Hello Photopea Staff I wanted to inform you about this issue even thought i have my ad blocker disabled it provides me with an error saying Adblocker enabled please disabled and to be honest its kind of irritating Please fix this issue Thanks
![image_2021-10-31_151012](https://user-images.githubusercontent.com/88927939/139572450-035d7122-5748-4852-8a59-1da097ed6ae7.png)
!

**Comment by photopea** [comment]
But do you see the ads or not? If you are blocking ads, this message should be displayed. That is a correct behaviour.

Maybe this could help you: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by giankd22** [comment]
![image](https://user-images.githubusercontent.com/93597158/139865144-60703586-0f5c-41f4-8252-8ce6e56d80e9.png)

@Vision11x They do not wish to help you even if you have ad-block disabled.

**Comment by giankd22** [comment]
Just use https://pixlr.com/nl/e/#editor
