### ISSUE TITLE
Ad-blocker message

### ISSUE THREAD

**Issue by Hidd3nOasis** [photopea/photopea#3908]
This pop-up message keeps popping up even though I have the ad-blocker paused on the site
![peaCapture](https://user-images.githubusercontent.com/82104786/139573850-c8268fb7-ce07-4ea3-a0ad-e0ee5699a532.JPG)
![PausedCapture](https://user-images.githubusercontent.com/82104786/139573851-8c40d155-55d2-4b66-8b1a-919f8f371ee1.JPG)
.

**Comment by photopea** [comment]
But do you see the ads, or not? If you are blocking ads, this message should be displayed. That is a correct behaviour.

Maybe this could help you: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by JirkaVasica** [comment]
Hi,

Today I've encountered the same message. This wasn't happening in the past. I am using vivaldi with blocked trackers, but enabled ads (https://help.vivaldi.com/desktop/privacy/tracking-and-ad-blocking/). I've always seen the ads. Temporarily I've disabled the tracker blocking for the photopea, which solved this issue. However it would be great to support the tracker blocking while showcasing the ads.

**Comment by photopea** [comment]
I am afraid we can not show the ads properly, if you are blocking the domains of our partners :(

**Comment by S0ulan** [comment]
> I am afraid we can not show the ads properly, if you are blocking the domains of our partners :(

Then just do not bother is with the pop up? One time its ok but do not spam this on us. I wont unblock the ads sorry. But I guess the pesky pop up can be disabled in firefox via modifiying css or javascript. Will try that :)

**Comment by photopea** [comment]
I do understand, that you want to get Photopea completely for free, without paying and wihtout seeing ads. But if everyone did that, Photopea would disappear a long time ago. We exists thanks to people who pay or who watch ads. 

It would be unfair to make some people watch ads, while letting others hide them.

**Comment by photopea** [comment]
It is similar to when you like a new pair of shoes in the store. You would like to get them without paying. But if everyone did that, all shoe stores woud disappear, and nobody would make shoes at all.

**Comment by jcathey92** [comment]
Previously I could whitelist this site so the ads would show up, but my adblocker for other sites could still work. I'm happy to have ads as I think this program is amazing, but am struggling to make it work. Do I need to completely turn off my ad blocker for all sites in order to support free photopea now?

**Comment by themreza** [comment]
>I do understand, that you want to get Photopea completely for free, without paying and wihtout seeing ads. But if everyone did that, Photopea would disappear a long time ago. We exists thanks to people who pay or who watch ads.

I strongly disagree. I think that with your current strategy to combat ad-blockers, you will lose a significant chunk of your users.

The web app is running fully in the browser, maybe with a few non-essential server-sided features. It can be deployed like any other static jamstack website for a relatively cheap price.

Plus, Photopea is a cloned version of Adobe Photoshop, so other than porting it to web, you haven't added something proprietary. I'm not sure how you get away with Adobe suing you, but it's actually not that difficult to remake it.

**Comment by photopea** [comment]
This article should help you: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by JirkaVasica** [comment]
> > I do understand, that you want to get Photopea completely for free, without paying and wihtout seeing ads. But if everyone did that, Photopea would disappear a long time ago. We exists thanks to people who pay or who watch ads.
> 
> I strongly disagree. I think that with your current strategy to combat ad-blockers, you will lose a significant chunk of your users. Don't you think YouTube could've done the same? Don't they know about ad-blockers?
> 
> The web app is running fully in the browser, maybe with a few non-essential server-sided features. It can be deployed like any other static jamstack website for a relatively cheap price.
> 
> Plus, Photopea is a cloned version of Adobe Photoshop, so other than porting it to web, you haven't added something proprietary. I'm not sure how you get away with Adobe suing you, but it's actually not that difficult to remake it. I'd love to see an open-source version so people can self-host it.
> 
> I wouldn't have minded paying for a subscription if it wasn't bombarding me with ads in the guest version and if it actually had something proprietary and exclusive.
> 
> I just wanted to share my opinion because it's sad to see something so useful be so annoying.

There is only one ad on the side, which is outside your main focus view point. It is the bear minimum for the amount of features offered. For our company it is much more useful to use photopea occasionally for free with ads rather then paying monthly subscription of photoshop for everyone in the company. Those who need some specific filters, vector graphics etc. are using paid services, but others are using photopea and we can all use the same formats and workflows without spending huge amounts of money. We should all be more grateful for the huge amount of R&D that was put in to creating photopea

**Comment by giankd22** [comment]
Just use https://pixlr.com/nl/e/#editor

**Comment by yes-iexist** [comment]
I had my adblock paused for photopea, and was seeing advertisements, but it still said "Are you seriously using an adblocker?" and "Photopea would not exist if everyone did what you do"

**Comment by photopea** [comment]
When you are blocking ads, Photopea shows you a banner for "Photopea Premium". That is not a standard ad (which makes us money).
