### ISSUE TITLE
[Feature Request] Make holding Shift while edge auto-scrolling scroll faster

### ISSUE THREAD

**Issue by louie-github** [photopea/photopea#3909]
In Photoshop, when making selections via the Rectangular Marquee tool, when using the Polygonal Lasso tool, etc., moving the cursor to the edge of the viewport scrolls to that side to show more of the picture. Photopea also does this.

However, in Photoshop, if you hold "Shift" while doing this, it makes the page scroll much faster. This is very helpful when making long selections, or when using said Polygonal Lasso tool.

I would like to request that Photopea do the same thing, especially for the Selection tools and the Polygonal Lasso tools. I'm not sure if any other tools would need this behavior too.

Thank you!

**Comment by MichalSZZ** [comment]
I always used spacebar before to move faster in that case. I didn't know about that shortcut. It's good to read Photopea github for news like that :)

**Comment by photopea** [comment]
I have implemented it :) when you hold Shift, it is scrolling 8x faster.
