### ISSUE TITLE
Copy Paste error

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#391]
1. New file
2. CTRL+A
3. CTRL+C
4. CTRL+V
5. Click with mouse on "Layer 1"
6. Go two steps back in history (click on "Open" in History window)
7. CTRL+A
8. CTRL+C
9. CTRL+V
->
Uncaught TypeError: Cannot read property 'clone' of undefined
    at k$.NE.lR (pp.js:2929)
    at iy.lR (pp.js:5851)
    at iy.AP.v (pp.js:6)
    at iy.w.v (pp.js:4111)
    at iy.gic (pp.js:5889)
    at iy.KL (pp.js:5865)
    at iy.AP.v (pp.js:6)
    at iy.w.v (pp.js:4111)
    at iy.xW (pp.js:5938)
    at iy.xl (pp.js:5926)

**Comment by photopea** [comment]
Fixed. Thanks!

**Comment by TareshA** [comment]
Hi, I have a similar problem. I seeem to be unable to copy/paste anything within the program, even between layers. I am able to cut the image but unable to paste it anywhere else (tried both with keyboard shortcuts and via menu). I am working in google chrom. 
Any advice?
Thxs

**Comment by photopea** [comment]
Try to update your Chrome browser.
