### ISSUE TITLE
Request: Uncheck "All" by default on the fonts menu

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3910]
That will allows low-performance devices to open the font menu faster.

**Comment by photopea** [comment]
This is for choosing all categories. If you uncheck it, there are no fonts :(

**Comment by nothingshiru** [comment]
Sorry I forgot that since I usually only use imported fonts. 

Is there a way to make the font menu to be opened faster? For example, only commonly used fonts are displayed by default, or the fonts list is loaded after the font menu is opened.

**Comment by photopea** [comment]
I have made the menu open about 10 times faster.
