### ISSUE TITLE
Please don't use Alt+scroll shortcut for zooming (or for anything else)

### ISSUE THREAD

**Issue by edison23** [photopea/photopea#3911]
Please don't use the alt+mousescroll shortcut for anything (or at least make it configurable so a user can choose to use something else for zooming) because in XFCE (desktop environment for Xubuntu), alt+scroll is by default used as an accessibility shortcut for zooming the whole desktop.

I know I can use ctrl+plus or ctrl+minus for zooming in Photopea but I'd like to have the option to do it with mouse too.
I'd suggest replacing the function for shift+scroll -- it's now vertical scrolling that can be done without key modifier so it could be used for zooming.

I'm sorry if there has already been a discussion about this; I briefly searched for exisitng issues but didn't see this OS specific issue mentioned.

Thanks, Ivan, for your hard work, I loved Photopea from the first moment! Greetings from Brno :)

**Comment by photopea** [comment]
Hi, sorry, but Alt+scroll is used for zooming in almost all graphics editors. 99% of people want it this way.

Your browser should prevent the default behaviour of Alt+Scroll, so it should not zoom your desktop. You should find another way how to zoom your desktop while using Photopea.

**Comment by edison23** [comment]
It's not an issue of the browser, that's a system-wide shortcut on Xubuntu that's not customizable (and obviously, no app can override system shortcuts).

**Comment by photopea** [comment]
I think an operating system should allow programs to use such basic shortcuts.

**Comment by edison23** [comment]
I agree, I just wanted to point out that there's a group of users that need to use the Ctrl+plus/minus shortcut because the alt+mousescroll is limited to the system use for them (that's why I suggested the use of shift+mousescroll shortcut as an option).
