### ISSUE TITLE
Ad blocker

### ISSUE THREAD

**Issue by thisshhitisstupid** [photopea/photopea#3912]
I can't edit and pictures with this stupid ad blocking message. I've turned everything off. I've reset. Nothing works.

**Comment by photopea** [comment]
Do you see ads in Photopea? If not, you are blocking them. Usually, by default, a browser displays a website as it is. You have to do some additional settings, or install extensions, to block ads. Do you remember when you did it and how?

Try this: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by flaneurette** [comment]
Also have the same issue... I clicked enable ads, because my subscription just ended. I tried to renew, but it only accept credit card, but I only have paypal.

**Comment by Yamat0** [comment]
I have the same issue, i use AdBlock but i have it turned off for photopea.com 
Is there any other sites I need to open to get this to work?

**Comment by photopea** [comment]
So you told your AdBlock to not block ads in Photopea, but it is still
blocking ads? That sounds like a bug in your AdBlock. Why don't you report
it to the creators of your AdBlock? There is nothing a website like
Photopea can do about it, when your extension is blocking ads.

pondělí 1. listopadu 2021 Zakarias Persson ***@***.***>
napsal(a):

**Comment by Yamat0** [comment]
well, no, it works as it should, but I think your site is sending adds from another domain or something like that. because if I turn it on for all websites, i get the adds. I cant run without adblock as you get so many viruses from uncalled for banners. what bannernetwork do you use? maybe we need to add that to the okay banners?

**Comment by flaneurette** [comment]
I do not have adblock. I have chrome browser. In chrome, I right-clicked 'lock' then -> allow ads.

Which domains are serving the ads? because those might be blocked by different settings, DNS, ISP settings, firewalls, etc. So I can drill down where the issue is.

**Comment by flaneurette** [comment]
Tried FireFox browser a moment ago, and it does not give the popup message.

**Comment by flaneurette** [comment]
That said, I do have a huge .HOSTS list with blocks spam, virus and other IP's and domains. About 50.000 lines. I use it as a "parental" filter for unwanted content as well. But if it works in FireFox, then it's not the .HOST file issue.

**Comment by giankd22** [comment]
I have the same problem and it only appeared a couple of days ago. It only happens in Chrome. I use ad block in Firefox and when I pause it for Photopea in Firefox Photopea still works. But in Chrome it keeps giving me the same message. It works for a short while and after that it just crashes and tells me that I'm using ad blocker, even though Photopea is paused! It's definitely on your side @photopea 

![image](https://user-images.githubusercontent.com/93597158/139860830-37acac7f-65e7-41ca-9697-b0443f8c344a.png)
![image](https://user-images.githubusercontent.com/93597158/139860920-7d1a3193-aa34-46b2-ade7-c3a931e982fa.png)
![image](https://user-images.githubusercontent.com/93597158/139860960-942451a7-05bf-437d-86da-346958c4bd27.png)

**Comment by giankd22** [comment]
If I clear cookies/cache it works again for a short while but then an ad breaks it..

**Comment by photopea** [comment]
So you do not see ads in Photopea? Try to disable all your extensions, if you do not know which ones are blocking ads.

@giankd22 can you tell me, if ads are shown after disabling all extensions?

**Comment by giankd22** [comment]
> So you do not see ads in Photopea? Try to disable all your extensions, if you do not know which ones are blocking ads.
> 
> @giankd22 can you tell me, if you see ads after disabling all extensions?

I have tried this, this is not the issue. It does the same thing when I disable all other extensions. This strongly leads me to believe all other extensions do not cause this issue, the issue happens for me after a short while of using Photopea. I've always had these exact settings, yet somehow the issue suddenly started a couple of days ago. I have not changed anything yet somehow this problem suddenly pops up.

As software developers making revenue from ads, I think you have a responsibility to at least check this and find out IF the problem is not on your side, or if you can fix it together with f.e. ad-block. This will only annoy people, not actually make them buy premium. I'm sure I'm not the only one to just move to a different free Photoshop if you are not willing to look into this. 

I'm reasonably certain of my case, my extensions are not the problem.

**Comment by photopea** [comment]
The volume of Premium orders increased quite a lot, after we introduced this message.

There were lots of people in the past, who claimed they disabled all their extensions, but they were lying, and ads did appear after disabling a certain extension. 

So I started to ignore all these reports now.

**Comment by giankd22** [comment]
Very nice service @photopea, I will no longer be using your software, with or without ad block.

**Comment by giankd22** [comment]
If you don't know how to fix, just ignore. Nice :-)

Op di 2 nov. 2021 om 15:15 schreef Photopea ***@***.***>:

**Comment by flaneurette** [comment]
Noticed that Photopea loads many addresses, one of them is rfihub.com, known for distributing viruses. I blocked that domain in my hosts file, and not wanting to unblock it.

https://www.google.com/search?q=s+rfihub.com&oq=s+rfihub.com&aqs=chrome..69i57.3357j0j4&sourceid=chrome&ie=UTF-8

https://howtofix.guide/p-rfihub-com-remove/

It also shows mature content.

**Comment by flaneurette** [comment]
> I have the same problem and it only appeared a couple of days ago. It only happens in Chrome. I use ad block in Firefox and when I pause it for Photopea in Firefox Photopea still works. But in Chrome it keeps giving me the same message. It works for a short while and after that it just crashes and tells me that I'm using ad blocker, even though Photopea is paused! It's definitely on your side @photopea

There can be many stages in a request that may pass through filters and firewalls. Could be at the ISP side, routers, parental filters, windows defender, hosts file, antivirus software, i.e. it is not reliable enough to locate a single cause, because it could be many or even all of them.

**Comment by giankd22** [comment]
There are no changes to any of that and it suddenly doesn't work anymore

> > I have the same problem and it only appeared a couple of days ago. It only happens in Chrome. I use ad block in Firefox and when I pause it for Photopea in Firefox Photopea still works. But in Chrome it keeps giving me the same message. It works for a short while and after that it just crashes and tells me that I'm using ad blocker, even though Photopea is paused! It's definitely on your side @photopea
> 
> There can be many stages in a request that may pass through filters and firewalls. Could be at the ISP side, routers, parental filters, windows defender, hosts file, antivirus software, i.e. it is not reliable enough to locate a single cause, because it could be many or even all of them.

**Comment by flaneurette** [comment]
> > I have the same problem and it only appeared a couple of days ago. It only happens in Chrome. I use ad block in Firefox and when I pause it for Photopea in Firefox Photopea still works. But in Chrome it keeps giving me the same message. It works for a short while and after that it just crashes and tells me that I'm using ad blocker, even though Photopea is paused! It's definitely on your side @photopea
> 
> There can be many stages in a request that may pass through filters and firewalls. Could be at the ISP side, routers, parental filters, windows defender, hosts file, antivirus software, i.e. it is not reliable enough to locate a single cause, because it could be many or even all of them.

Pixlr also shows the same ad platform as Photopea, but I do not get a popup. So I don't know. 

I tried to extend my Photopea subscription, but suddenly it only accepts creditcards, which I don't have. I like Photopea and want to see it succeed, but now it is quite hard to work with it and might have to try another alternative.

**Comment by giankd22** [comment]
> > > I have the same problem and it only appeared a couple of days ago. It only happens in Chrome. I use ad block in Firefox and when I pause it for Photopea in Firefox Photopea still works. But in Chrome it keeps giving me the same message. It works for a short while and after that it just crashes and tells me that I'm using ad blocker, even though Photopea is paused! It's definitely on your side @photopea
> > 
> > 
> > There can be many stages in a request that may pass through filters and firewalls. Could be at the ISP side, routers, parental filters, windows defender, hosts file, antivirus software, i.e. it is not reliable enough to locate a single cause, because it could be many or even all of them.
> 
> Pixlr also shows the same ad platform as Photopea, but I do not get a popup. So I don't know.
> 
> I tried to extend my Photopea subscription, but suddenly it only accepts creditcards, which I don't have. I like Photopea and want to see it succeed, but now it is quite hard to work with it and might have to try another alternative.

@flaneurette I'm giving up on Photopea, Pixlr works perfectly for me I just found out :)

**Comment by flaneurette** [comment]
> @flaneurette I'm giving up on Photopea, Pixlr works perfectly for me I just found out :)

Yes, it does the basics. Might go for Photoshop, but found it difficult as it had many installation failures. It's never perfect.

**Comment by flaneurette** [comment]
Went and bought Photoshop, seemed the most reasonable option for me.

**Comment by photopea** [comment]
A website can not put a virus into your computer. Domains can not distribute viruses. Showing an ad does not put a virus into your computer, that makes no sense.

**Comment by giankd22** [comment]
@photopea what makes no sense is that you don't listen to anyone, AT ALL :)

Op wo 3 nov. 2021 om 00:15 schreef Photopea ***@***.***>:

**Comment by photopea** [comment]
@giankd22 I am ready to help, but you should cooperate and try the steps, which I suggest. As far as I remember, you refused to try to run Photopea with your extension disabled. Even though it takes only 5 seconds to uncheck the checkbox.

**Comment by giankd22** [comment]
The point is that WITH the extension PAUSED. It SHOULD work as it always
has worked before. However, you changed something a couple of days ago, and
coincidentally it does not work anymore since that change.

Ad-block is PAUSED, which means advertisements are allowed to be shown on
your website, however, they still don't. Conclusion: you messed it up.
Again, I'm done with your software. Thanks for your suggestions!

Op wo 3 nov. 2021 om 10:44 schreef Photopea ***@***.***>:

**Comment by photopea** [comment]
What do you mean by "extension paused"? Are you sure you know all settings of your extension and what they do?

I decided to allow people to block ads again. But I might enable it in again in the future.

Also, it is really shocking, that you think your extension is disabled or paused or whatever, and you dont even know that it is still watching and modifying all your websites and what you do on them.

**Comment by flaneurette** [comment]
Usually there are many points of view, and often they are all correct.  Photopea is an amazing piece of work, really enjoy it and probably took a great deal of effort to create it. So I understand the frustration from both sides.
