### ISSUE TITLE
They were not problems with devices

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3913]
I had reported such 2 bugs which you might think they are bugs on devices before.

1. Brush cursor doesn't move with mouse.
2. Using Quick Select might cause invisible finger touching on canvas.

Today I found that they can be reproduced on PC.
To do that, you can press F12 and Ctrl+Shift+M when you opened Photopea on Chrome or Edge. It will simulate the page as on mobile phone and you will find the bugs.

So can the bugs be fixed?

**Comment by photopea** [comment]
When the desktop Chrome is simulating a mobile device, i think it simulates a finger. So obviously, it does not tell a website, where a finger is, if it is not touching the screen.

So I still think it is a bug with a device. Or can you show me a webpage, where a similar thing works?

**Comment by nothingshiru** [comment]
Well, it did simulate a finger. 

But what about second problem? Quick Selection is not related to whether cursor moves along with mouse.
