### ISSUE TITLE
Problem with floating window of "Loading" 

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3915]
When use Photopea offline or with low net speed, if I select a font or other options that need to be laod with internet, this floating window keeps on there all the time. It covers menu and options, make us unable to use Photopea normally.
![screenshot_20211101_120251](https://user-images.githubusercontent.com/79258245/139620845-3beb6427-73f7-4ab5-881e-6486ec194fc0.jpg)
This problem needs to be solved somehow.

**Comment by photopea** [comment]
Is it still happening?

**Comment by nothingshiru** [comment]
Still happening. In addition, I would like to ask, how do you plan to solve it? It is not a bug.

**Comment by nothingshiru** [comment]
Can that floating window be closed manually? Can we interrupt the loading?

**Comment by photopea** [comment]
So is it about loading a font? I think you just need to wait until the font is loaded. How slow is it really in your case?

**Comment by nothingshiru** [comment]
Sometimes it takes me 10 seconds to load one font weight. And I'm not just talking about loading fonts but loading patterns and brushes which need internet. 

The point is that the floating window prevents us from using Photopea normally. If offline, they won't be loaded and we will have to reopen Photopea to close the floating window.

**Comment by photopea** [comment]
We moved to a new webhosting. Is it still slow to load stuff? BTW. are you in China? Are foreign websites slowed down in China?

**Comment by nothingshiru** [comment]
>Are foreign websites slowed down in China?

Yes.

**Comment by photopea** [comment]
I am afraid, if you have a slow interent, and a font is large, you will have to see the Loading message until the font is loaded.
