### ISSUE TITLE
I can't rename the layers

### ISSUE THREAD

**Issue by faith1983** [photopea/photopea#3916]
Hi,
I wanted to report a bug, I can't rename the layers whenever I make double click

**Comment by photopea** [comment]
Hi, I just tried and it works for me. Does it happen every time or only sometimes? What web browser do you use?

**Comment by faith1983** [comment]
No this is the 1st time, I use chrome

**Comment by faith1983** [comment]
Hi, it just worked again,  I don't know what happened but thank you soo
much for ýour quick reply, you're the best

**Comment by photopea** [comment]
It should be fixed now.
