### ISSUE TITLE
Request: Use percentages for arrow shape values

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3917]
Because the values are fixed numbers, we are currently unable to preserve the looking of arrow when change the width of line. It will be better to use percentages.
![Screenshot_20211102_112558](https://user-images.githubusercontent.com/79258245/139782203-61cdeab6-5e63-4d4a-ae23-f49c2b74f701.jpg)
The default width of the arrow can be set to 300% of the line width, and the length of the arrow can be set to 100% of the arrow width.

**Comment by photopea** [comment]
Sorry, but it would be too hard to implement :( Even the preview in arrow options does not show the real thickness of the arrow. Also, some people might want to set the arrow size in pixels.

**Comment by nothingshiru** [comment]
I thought it only needs to automatically perform simple multiplication calculations. Why can it be too hard?
