### ISSUE TITLE
Images won't load properly from my drive

### ISSUE THREAD

**Issue by UltiWeeb** [photopea/photopea#3918]
whenever I try to open an image for editing it works very inconstantly and sometimes doesn't work at all!

**Comment by oksana594** [comment]
у меня вообще не открываются

**Comment by photopea** [comment]
Do you mean openign a file with File > Open ? So what happens when "it doesn't work"? Can you send me a file, which you can not open, to support@photopea.com ?

**Comment by photopea** [comment]
I have to close it because the person stopped responding :(
