### ISSUE TITLE
adblock message

### ISSUE THREAD

**Issue by oblongsean** [photopea/photopea#3919]
i uninstalled my adblock and restarted my computer and the message still comes up

**Comment by photopea** [comment]
Hi, have you tried to disable all your extensions? You can disable them temporariyl, without deleting them (there should be a checkbox next to each extension).

**Comment by giankd22** [comment]
> i uninstalled my adblock and restarted my computer and the message still comes up

Just use https://pixlr.com/nl/e/#editor @oblongsean
