### ISSUE TITLE
PSD Issues

### ISSUE THREAD

**Issue by rowan010101** [photopea/photopea#392]
When I save a PSD from Photopea and then try to open it from my library back into Photopea, it says that the file type is unrecognized.

**Comment by photopea** [comment]
Hi, can you tell us more? We crated many PSDs and all of them were "openable" in Photopea after saving. What are the steps for create such corrupted PSD?

**Comment by rowan010101** [comment]
I have three separate PSD's that I put into the same project. It's a border, and two coloring PSD's. I can save the icons as PNG's perfectly fine, but when I click on "save as PSD" it lags a bit and saves. Then, when I try to open up the PSD in Photopea again, it says "Unknown File Format"

**Comment by photopea** [comment]
Can you send us these PSDs to support@photopea.com ?

**Comment by photopea** [comment]
Did you receive my email?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
