### ISSUE TITLE
Photopea doesn't want to fix the ad block problem

### ISSUE THREAD

**Issue by giankd22** [photopea/photopea#3920]
Don't try to use Photopea with ad block paused, it will not work and they don't want to fix it

@CodeBenaiah @sanse329 @regularsteven @Kozmozzz @tiddyslave @mikemarchal @cha-i 

![image](https://user-images.githubusercontent.com/93597158/139865574-300ac4c1-cc74-425d-a63e-80a550180e43.png)

**Comment by photopea** [comment]
Can you show me a screenshot of chrome://extensions ?

**Comment by giankd22** [comment]
[image: image.png]

Op di 2 nov. 2021 om 15:30 schreef Photopea ***@***.***>:

**Comment by giankd22** [comment]
![image](https://user-images.githubusercontent.com/93597158/139868157-3a38b268-1ee6-420d-85d5-0bc71a775e57.png)

**Comment by photopea** [comment]
are you using any antivirus or a firewall? Can you access https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js ? Can you access https://cmp.uniconsent.com/v2/85d3b9563e/cmp.js ?

Do you know what domains are you blocking on your computer?

**Comment by photopea** [comment]
You still have one extension enabled in your screenshot. Do you really trust the extensions from who-knows-who so much?

**Comment by giankd22** [comment]
I have ad block enabled but your website is EXCLUDED from scanning/blocking ads. What about this do you not understand? I do not have external firewalls. Again, this problem suddenly arose and I have not changed any settings. It has always worked like this and since this week it doesn't. Coincidentally you changed the options last week. How do you not ee the pattern here?

![image](https://user-images.githubusercontent.com/93597158/139869492-658c97c5-8323-462b-ae10-556ead8e5eae.png)

Again, it has ALWAYS worked like this, now it doesn't.

![image](https://user-images.githubusercontent.com/93597158/139869666-4cb9dd13-b643-4394-af84-29950c4de9a8.png)
