### ISSUE TITLE
![image](https://user-images.githubusercontent.com/93597158/139866980-bd861abd-1652-4fec-860c-87e8548e2d58.png)

### ISSUE THREAD

**Issue by ghost** [photopea/photopea#3921]
![image](https://user-images.githubusercontent.com/93597158/139866980-bd861abd-1652-4fec-860c-87e8548e2d58.png)

But, with all extensions removed @photopea still displays this annoying message and it just doesn't work.

![image](https://user-images.githubusercontent.com/93597158/139867031-22fb2449-1cdd-481c-b0cf-d940c46fbcbd.png)
![image](https://user-images.githubusercontent.com/93597158/139867058-e2fe4e8e-359e-449d-bc0c-2efbfab551bf.png)
![image](https://user-images.githubusercontent.com/93597158/139867085-dc282b79-ee4b-4b00-8f71-49222d079a95.png)

_Originally posted by @giankd22 in https://github.com/photopea/photopea/issues/3920#issuecomment-957701333_

**Comment by photopea** [comment]
I was talking about people with 0 extensions, you have 1 extension.

**Comment by giankd22** [comment]
@photopea I think you're stupid or you just play to be stupid, I'm going to stop using your stupid software.
@everyone else: https://pixlr.com/nl/e/
