### ISSUE TITLE
Ad block triggered message

### ISSUE THREAD

**Issue by mfjramirezf** [photopea/photopea#3925]
Hi!!
My ad blocker is off and I'm still getting so often that ad blocker message asking for premium.

**Comment by photopea** [comment]
You did not mention, if you see ads in Photopea or not?

Try this maybe: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by photopea** [comment]
Let me know if it helped :)

**Comment by mfjramirezf** [comment]
Hi! Thanks for that!. I've realized the problem. I had disabled my
adblocker on the entire Photopea site. But, apparently, your ads come from
another domain. So, my adblocker was still doing his job. After a while, I
realized that I had to completely disable adblocker to finally see ads in
Photopea 🥳

Greetings!
