### ISSUE TITLE
rectangle unwanted blue color

### ISSUE THREAD

**Issue by neobie** [photopea/photopea#3927]
Hi. Wondering why the rectangle tool always have blue border color ?

![image](https://user-images.githubusercontent.com/4213973/139999089-71682b27-67cd-4124-ad92-481473e09fce.png)

**Comment by MichalSZZ** [comment]
It is showing the path. Rectangle or any tool from this group of tools are vector based shapes.

In menu view->show->paths you can turn of visibility of that extra blue stroke (but in the futyre it is extremaly helpful)
