### ISSUE TITLE
I can't copy the content of a hidden layer...

### ISSUE THREAD

**Issue by paconaranjo** [photopea/photopea#3928]
Even if I mark Sample All layers...

I need to set it visible then copy and then hide the layer again. 

Thanks...

**Comment by photopea** [comment]
I am able to copy a content of a hidden layer (Make a selection, Ctrl+C), if that layer is selected in Layers :(

Did you do something else? Can you describe steps how can I reproduce your problem?

**Comment by paconaranjo** [comment]
When I make a selection on a hidden layer and use Ctrl + J (New layer Via Copy).

**Comment by paconaranjo** [comment]
I see the problem, i'ts not Layer Via Copy, it's Color Range in hidden layer. Can't detect a thing, I need to add an action to set the layer visible for Color Range.

**Comment by photopea** [comment]
When you selected a part of a hidden layer and did Layer Via Copy or Via Cut, the new layer was also hidden. I have fixed it.

The Color Range is selecting form pixels of a whole document (so it can not detect the hidden layer), in Photoshop and Photopea.

If you have actions, wihch work differently in Photoshop and Photopea, share them with us! :)
