### ISSUE TITLE
Massive empty space on the right half of the screen [19x6]

### ISSUE THREAD

**Issue by Sollace** [photopea/photopea#3929]
I've only just started looking at Photopea, but one thing that stands out to me is this gigantic gap on the right-hand side of the screen. It feels like the program isn't sizing correctly for my display.

I have tried disabling ad blockers and it doesn't seem to be due to ads that would occupy this area.
![image](https://user-images.githubusercontent.com/6429283/140033092-97ee3255-1bd7-4656-8612-85b86a117973.png)

**Comment by Sollace** [comment]
I'm somewhat able to fix it using a userstyle, though there is still a lot of absolute/hardcoded sizes and positioning within Peazip that I cannot touch.

```
/*remove pointless div*/
.flexrow.app > div + div {
    display: none;
}
.flexrow.app > div,
.flexrow.app > div > .cmanager + div {
    width: 100% !important;
}
.mainblock {
    flex-grow: 1;
}
.mainblock > .block > .panelhead + div {
    width: 100% !important;
}
.intro {
    left: 50% !important;
    transform: translate(-50%);
}
```
![image](https://user-images.githubusercontent.com/6429283/140034504-43d583d4-639e-47ca-a36f-07b25c8b44e3.png)

**Comment by photopea** [comment]
There should be ads on the right side. Ads are the reason we still manage to exist. We would disappear a long time ago, if everyone was removing them.

What web browser are you using? Can you find out what extension is blocking ads (if you are using any extensions)?

**Comment by Sollace** [comment]
Sure! I'm using Firefox 88.0.1

I normally just use uBlock to remove ads, but I did try turning it off in case it was that. Might be something built in that I don't know about, so give me a few minutes to investigate with another browser.

**Comment by Sollace** [comment]
I'm seeing a lot of CORS errors in the console. Could this be the cause?
![image](https://user-images.githubusercontent.com/6429283/140035727-9d4b3857-81ad-4589-91e3-5942cd9e105b.png)

**Comment by Sollace** [comment]
Yeah, it appears to be the built-in tracking protection that's causing this. Specifically the "Cross site tracking cookies" setting.
![image](https://user-images.githubusercontent.com/6429283/140036428-e34d77c5-5866-4641-9ee7-55dfbb688669.png)

Given it's not a problem with Photopea, I'm just going to close this. Sorry about that.
