### ISSUE TITLE
Type tool problem

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#393]
Open pea.psd
Select word "Photopea" in "Welcome to Photopea" text and change its color
(Now nothing changed because there is "Color Overlay" effect)
Disable "Color Overlay" effect in "Welcome" layer (by clicking eye in layers window)
Now click on layer "Description" in layers window
->
it changes something in "Description" Layer and you can't undo your last step
if you try to undo multiple steps in History window some items in that window disappear

**Comment by photopea** [comment]
Another example: open pea.psd, choose Type tool, click on the "Description" layer, it "changes something".

**Comment by photopea** [comment]
I believe it is fixed now. Thanks!
