### ISSUE TITLE
adding padlock (to block) to the folder not blocking layers inside that group

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3930]
It should work in that way as I described in the title

**Comment by photopea** [comment]
what do you mean by that? What is "blocking layers"?

**Comment by MichalSZZ** [comment]
![obraz](https://user-images.githubusercontent.com/38118273/140036747-327c8d89-f788-4283-97ee-72486488ec58.png)

I am clicking on the padlock icon in the layers palette (when I have folder selected on it) and all layers inside that folder should to be locked automatically (I think that I used wrong word for describing that :) I still have very poor English when I am writing fast without any translator)

**Comment by photopea** [comment]
I think I have fixed it :) thanks for reporting it!
