### ISSUE TITLE
Does not work on iPad’s web browser, canvas input interpreted as page scrolling

### ISSUE THREAD

**Issue by eliax** [photopea/photopea#3931]
This would be a great tool to use with the iPad’s Apple Pencil, but as is it won’t take input from fingers either. Do note that on iPhones it does work. The issue has to do with how the web page is setup, where in the iPhone is static/fixed but on the iPad is dynamic and it flows. Essentially the app within the browser takes input as a finger trying to scroll the page instead of as input in a canvas. This could be easily fixed and it’d bring a lot of users into the Photopea ecosystem.

**Comment by photopea** [comment]
There are thousands of peoplte using Photopea on iPads right now, "as it is".

What iOS do you have on your iPad? Have you tried to update it?

**Comment by gbunoni** [comment]
> There are thousands of peoplte using Photopea on iPads right now, "as it is".
> 
> What iOS do you have on your iPad? Have you tried to update it?

No at all, On iPad is unusable, I’ve the same problem, after a wile the program simulate another invisible finger keep touching on canvas. I’ve the same problem non only in one single document but in every document, can you help me?

**Comment by photopea** [comment]
@gbunoni but it happens only if you paint into an unrasterized layer, and the message appears, right? I am aware of this. Or is there any other bug?

**Comment by gbunoni** [comment]
It happens when i want to paint, erase, select, move something etc. etc. software block itself and it is impossible to continue work or save project

**Comment by photopea** [comment]
It should be fixed now. Is it fixed?
