### ISSUE TITLE
When using Photopea as a PWA it keeps losing the login status

### ISSUE THREAD

**Issue by codepo8** [photopea/photopea#3933]
Every time I restart it, I need to log in again. Is this because of missing cookies? Could the tool recognise that it is being launched as a PWA and not have the ads?

![image](https://user-images.githubusercontent.com/13508/140127429-5936d842-0c05-43f5-ab7c-99eac653b31c.png)

**Comment by codepo8** [comment]
It is even worse, the ad code doesn't realise I am running the app as a PWA and it can't show the ads.
![image](https://user-images.githubusercontent.com/13508/140129514-362d92a4-c69e-41dc-9585-22ef6d3995dd.png)

**Comment by photopea** [comment]
Your browser is running your ad-blocker even in this "PWA mode". 

As there were too many people blocking ads in Photopea, we decided to ask them to disable their adblocks. So you have to to disable your Adblock, or buy Premium :/

**Comment by photopea** [comment]
You probably also have an extension, which deletes website data (in case of Photopea, these are data about you being logged in). Do you know how many extensions are you using and what they do?

**Comment by codepo8** [comment]
I am not running any ad blockers at all, this is Microsoft Edge without any extensions.

**Comment by photopea** [comment]
Can you open about://extensions in your Edge? Are there any items? Are you sure you "installed" Photopea when you were using MS Edge?

**Comment by codepo8** [comment]
Yes, I work on Edge and showed off Photopea as a great PWA :) 
I don't have any blocking extensions. 
Could it be a strict tracker setting? 
![image](https://user-images.githubusercontent.com/13508/140156118-3c6becbb-7a3a-4d94-a892-778e878b93af.png)

**Comment by photopea** [comment]
yes, you are probably blocking the domains of our ad providers this way.

**Comment by avagp** [comment]
i am with the same situation though.

I thought it was my unstable internet connection, but seems something related to chromium maybe.

**Comment by photopea** [comment]
@avagp I am very sorry, we moved to a new web hosting on Tuesday, and it will probably take time to tune it up :/

**Comment by avagp** [comment]
To be honest @photopea this have been happening more than a week ago.

My session is lost like 4 or 5 times during the day.

:/

**Comment by photopea** [comment]
Photopea logs out automatically if it detects it is offline. Is it possible that you went offline during a day?

**Comment by avagp** [comment]
Probably.

I will check now knowing this information.

I'll report you back

**Comment by avagp** [comment]
Yes!

That's my problem :(

I have an unstable internet conexion. 

I am working, and a couple times during the day i lose my signal for a couple of seconds, then it comes back, but i keep working on photopea.

But then i close it, work on something else, then open it again, and my session is gone.

is this a decision? Can it leave my account rechecked or something after i return online?

**Comment by avagp** [comment]
@photopea can you please modify that rule?

I have an unstable internet connection.

Can you please do not log out immediatly after disconnecting?

**Comment by photopea** [comment]
Yes, I will try to look into it.

**Comment by avagp** [comment]
Any updates?

Presumably before the server change i did not have this issue, regardless of the same crappy internet i have.

I would really like to have the premium experience again :(

**Comment by photopea** [comment]
It should be fixed now. Going offline should not log you out. However, you can open the Account window only when you are online.
