### ISSUE TITLE
Can't save the update in google disk undefined updated 

### ISSUE THREAD

**Issue by vadimz95** [photopea/photopea#3934]
when I try to save modified images from google drive, I get an error
Alert: Saving "IMG_20211102_095253.jpg" to Google Drive ...
pp.js:12491 PATCH

**Comment by photopea** [comment]
Hi, is the bug still happening?

**Comment by photopea** [comment]
I have to close it because the person stopped responding :(

**Comment by minnie90716** [comment]
I have the same bug right now, how can I solve the bug?

**Comment by photopea** [comment]
Did you keep it opened in your browser for several days? Maybe the token ran out, and Google Drive does not accept a file to be saved anymore.

You can save it to your computer and upload to Google Drive.

**Comment by minnie90716** [comment]
No, I didn't. I just opened it few minutes, and it can't save it from Photopea to Google Drive. 
I used Photopea for Google Classroom, so that I can't give back my students homework after I corrected their mistakes right away, I have to find new ways to return students homework. It bothers me a lot.

**Comment by photopea** [comment]
I am able to save files back from Photopea to Google Drive.

Can you describe, what should I do to see a problem which you describe? Or even better, can you record a short video of what exactly you do?

**Comment by photopea** [comment]
"I just opened it few minutes" - what does this mean?

**Comment by txrmira** [comment]
i'm having the same issue when i am saving it will show undefined updated

**Comment by minnie90716** [comment]
The video is when I use photopea and what to save it to Google Drive, however, it appeared "undefined update".

 [New Recording - 2022/7/18 下午6:09:47](https://vimeo.com/730945094/64ecf04e8e)

**Comment by minnie90716** [comment]
I have tried to open other Google Classroom, it could work. However, when I want to use photopea to the classroom which run by other person, it can't work anymore.

**Comment by photopea** [comment]
I am not familar with clasrooms. Maybe the other person must allow you to modify files somehow.
