### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Roxgame95** [photopea/photopea#3935]
The server throwing an error right now : 502 Bad Gateway

**Comment by 1trackprojects1** [comment]
I'm having the same issue

**Comment by EAPrintables** [comment]
Same. The site isn't loading at all

**Comment by Roxgame95** [comment]
The problem looks like got fixed 
thank you

**Comment by photopea** [comment]
Hi, we moved to a different IP address about 40 hours ago. Is it possible, that your computers were still using the old DNS records for some reason?
