### ISSUE TITLE
[ai] wrong fill color

### ISSUE THREAD

**Issue by Ser-Gen** [photopea/photopea#3936]
File
[new_year.zip](https://github.com/photopea/photopea/files/7474484/new_year.zip)

Export from Adobe Illustrator  
![new_year](https://user-images.githubusercontent.com/1856145/140307077-4273f644-b9a9-4158-9f4f-7264bfc04785.png)

Export from Photopea
![new_year photopea](https://user-images.githubusercontent.com/1856145/140307513-ac7a0f36-caba-492d-b8fb-500041876d01.png)

![property in ai interface](https://user-images.githubusercontent.com/1856145/140307557-d443a615-61d9-4292-b150-379b6559bb54.png)

**Comment by photopea** [comment]
Fixed, thanks for reporting! :)
