### ISSUE TITLE
Ads & Ad Blocker Dialog Box

### ISSUE THREAD

**Issue by Tolboy46** [photopea/photopea#3937]
I've added you to my whitelist but ads don't pop and I keep getting the dialog, very annoying. First time it's ever done this for me

**Comment by herdingfish** [comment]
Same is happening for me.

**Comment by photopea** [comment]
Hi guys, I have written a short tutorial about how to fix it. Let me know if it helped :) 

https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by Tolboy46** [comment]
I've added to pause list whitelist and everything else I can. The only time it works is if I turn off AdBlock completely, which isn't happening. Not on my end, if you can't correct after what I assume was an update after yesterdays outage, I'll just find another program. Which is a shame because I very much enjoyed using this.

**Comment by photopea** [comment]
If you tell your AdBlock to enable ads at Photopea, but it is still blocking ads, I guess it is a bug in your AdBlock, not in Photopea :(

**Comment by Tolboy46** [comment]
A Google Chrome extension having "a bug" = Unlikely
Someone screwing up when you updated = Likely
I notice the notification isn't popping anymore so thanks for fixing it.

**Comment by photopea** [comment]
There are too many people who dont know how to disable their ad blockers, so we decided to let them use ad blockers for a while. But we will re-introduce the message again in the future.

**Comment by Tolboy46** [comment]
Well, I certainly know how to use them. You must have had a script issue. It's okay, everyone makes mistakes.
