### ISSUE TITLE
Font i've been uploaded not showing

### ISSUE THREAD

**Issue by zacky17** [photopea/photopea#3938]
Hello,

i've been uploaded some fonts, why it not showing on loaded fonts?

**Comment by photopea** [comment]
Hi, do you mean opening fonts using File - Open? Were you asked about saving your font? Did you confirm it?

The fonts are saved in the Local Storage. If you ever clear website data, fonts and other data are deleted.

**Comment by photopea** [comment]
I have to close it because the person stopped responding :(
