### ISSUE TITLE
"All" is still unchecked when not all fonts styles are checked

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3939]
![Screenshot_20211105_004649](https://user-images.githubusercontent.com/79258245/140382898-dec598b3-6256-419c-9d0a-61fe44926673.jpg)

**Comment by photopea** [comment]
All is a button for turning all values On or Off, it is not related to the current state of values.

**Comment by nothingshiru** [comment]
It runs differently from other apps.

Let me give you an example, in a file management app on phone, when not all files in a folder are checked, the "All" button will not be checked, if you click the "All" button, all files will be checked, and if you click it again, all will be unchecked.

Could you make it works in the same way?

**Comment by photopea** [comment]
I have fixed it. The "All" checkbox is on only when all categories are enabled.

**Comment by nothingshiru** [comment]
Good.
