### ISSUE TITLE
Smart Object not updating completely

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#394]
Open pea.psd
Convert layer "top bar" to Smart Object
Open that Smart Object (double click)
Now go back to and duplicate layer "pea" into "top bar.psd" (smart object file)
Go into "top bar.psd" and move green circle so it is visible
Update Smart Object with File - Save (Smart Object)
->
when go back to "pea.psd" green circle should be now visible (but it is not)

(note: if you manipulate with sliders in Properties - Mask in that layer it suddenly starts updating correctly)

**Comment by photopea** [comment]
This is also related to my "huge change" :(

**Comment by photopea** [comment]
It is not related to my "huge change", it was there before ... it happens only for vector shapes.

**Comment by photopea** [comment]
Simpler example: Duplicate the "pea" layer. Save as PSD. Open PSD (in Photopea), the new pea has wrong layer style.

**Comment by photopea** [comment]
Fixed.
