### ISSUE TITLE
The "eye" icon on the folder and files inside it

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3940]
In Photopea there are only 2 states of "eye" icon in layers palette.

- Normal - layer is visible
- Grayed out - layer is invisible

In Photoshop there is 3rd state - no "eye" icon. 
It is for invisible (hidden) layer inside a folder. Hidden by the user.

When I turn off visibility of the "eye" icon next to the folder, all visible layer with icon, should have grayed out "eye" icon. Layers that was hidden by the user have not any eye and hiding - unhiding layers by the eye icon on the folder doesn't do anything for that layers.

Now in photopea, folder can have an eye icon greyed out (and all layers are hidden) but icons for hidden layers inside folder has normal "bright" eye.

**Comment by photopea** [comment]
But I have always thought it is better as it is now in Photopea. You can switch any eye at any time. A layer is displayed, if it is visible and all parent folders are visible.

In Photoshop, if a folder is hidden and you switch the eye of a layer inside it, the folder becomes visible again. Do you want it to work this way?

**Comment by photopea** [comment]
I have implemented the three states of the eye, it should work as the PS now.
