### ISSUE TITLE
"Remove Ad blocker" pop-up continues to pop-up even after Ad Blocker removed

### ISSUE THREAD

**Issue by bobbyapurks** [photopea/photopea#3942]
I stopped ad block for photopea, 'cause I love y'all, but the pop-up continuously appears even after?

**Comment by mentisy** [comment]
Same with me. Using uBlock Origin version 1.38.4 on Chrome 94.0.4606.81.

**Comment by photopea** [comment]
But do you see ads or not? Try this: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by bobbyapurks** [comment]
Hey thank you so much, that was it! Sorry, just following the instructions on the pop-up. Closing this now, and appreciate the help!
