### ISSUE TITLE
Stops drawing 

### ISSUE THREAD

**Issue by MaksimMelan** [photopea/photopea#3945]
gives you the opportunity to draw! You cannot choose a tool, you can draw in a new document, you cannot in an old one, the canvas seems to be hooked into one place. for some reason, nothing can be done with him. android Samsung tab s7 + 

https://user-images.githubusercontent.com/64986385/140561328-49262356-b1ef-4666-8cf6-8538f6b8d8c7.mp4

**Comment by photopea** [comment]
So you can draw in one document, but not in another? Can you update your web browser?

**Comment by MaksimMelan** [comment]
Browsers are updated (I tried it in Chrome and Yandex.Browser - with Alice). If you update the page itself, then the project is served, you have to load the new one. (can we continue communication in Russian?). Some kind of sticking occurs, and it becomes possible only to change the zoom of the canvas. maybe it is due to touching the screen with your hand while drawing or when switching between browser tabs. Prozba - please add to cancel the action Double tap with two fingers on the screen (canvas), to return - double tap with three fingers! (This is done in Prokrate on ipad and Infiniti Painter on Android). this is the standard for these actions on touchscreen tablets. I don't have a keyboard with me to press Ctrl Z, and it's very inconvenient to climb into the curtain.

**Comment by nothingshiru** [comment]
@MaksimMelan 
Have you used Quick Selection, Object Selection, Magic Wand? Or enabled No Touch when finger is touching on canvas.

>please add to cancel the action Double tap with two fingers on the screen (canvas), to return - double tap with three fingers! 

I requested such a feature. #3810

**Comment by nothingshiru** [comment]
@photopea 
I think it is the same bug that I reported that invisible fingers keep touching on canvas. And after reading what he said, I discovered that this bug only occurred in one document, and we didn't need to refresh the page.

**Comment by gbunoni** [comment]
https://user-images.githubusercontent.com/93867307/140646295-f02e4375-55c5-446c-96b6-e1bfe107b047.mov

On iPad is unusable, I’ve the same problem, after a wile the program simulate another invisible finger keep touching on canvas. I’ve the same problem non only in one single document but in every document, can you help me?

**Comment by photopea** [comment]
What if we make a following design decision: Whenever you remove a finger from a screen, all fingers are forgotten. 

So if you touch the screen with a finger A, then add a finger B, then remove A, Photopea will forgot both fingers. 

I guess there are no scenarios, when you are using more than one finger, then you release one finger, but you want to keep doing something with the rest of fingers. Am I right? With pinch to zoom, if you are touching with two fingers, and you remove just one finger, and then, add it back, it would not zoom again. You  would need to make Photopea register two fingers again.

**Comment by gbunoni** [comment]
> What if we make a following design decision: Whenever you remove a finger from a screen, all fingers are forgotten.
> 
> So if you touch the screen with a finger A, then add a finger B, then remove A, Photopea will forgot both fingers.
> 
> I guess there are no scenarios, when you are using more than one finger, then you release one finger, but you want to keep doing something with the rest of fingers. Am I right? With pinch to zoom, if you are touching with two fingers, and you remove just one finger, and then, add it back, it would not zoom again. You would need to make Photopea register two fingers again.

Sorry, you are not right, i never use finger but Apple Pencil or mouse. I think is a bug on the web app.

**Comment by photopea** [comment]
So you are never touching the screen with more than one thing, and the bug still happens?

**Comment by gbunoni** [comment]
> So you are never touching the screen with more than one thing, and the bug still happens?

Exactly, and after this bug never will work, it is impossible also to save the project

**Comment by photopea** [comment]
In your video, you are zooming in and out, but the Zoom tool is not enabled. Are you doing it by touching Photopea with two fingers? You said you never use finger.

**Comment by gbunoni** [comment]
> In your video, you are zooming in and out, but the Zoom tool is not enabled. Are you doing it by touching Photopea with two fingers? You said you never use finger.

It zoom but I don’t use two finger but the Apple Pencil, photopea think the I have one finger touching the screen and  use the touch of the Apple Pencil like a second finger. there is no way to solve this problem

**Comment by gbunoni** [comment]
Look, this is the problem. This little dot that simulate erroneously a touch on the screen even if there is not a real finger on the screen 
![A8F59D90-E346-4E27-AADE-ADECCF376AC1](https://user-images.githubusercontent.com/93867307/140648933-31da7516-90fb-4d68-9f8d-a96d802af6da.jpeg)

**Comment by gbunoni** [comment]
> In your video, you are zooming in and out, but the Zoom tool is not enabled. Are you doing it by touching Photopea with two fingers? You said you never use finger.

Any news? Have you adjusted that problem?

**Comment by photopea** [comment]
I think I have fixed it. Is it fixed now?

**Comment by gbunoni** [comment]
> I think I have fixed it. Is it fixed now?

I’ve tray. no, It is not fixed :(

**Comment by photopea** [comment]
Can you try Photopea in the Incognito window?

**Comment by gbunoni** [comment]
> Can you try Photopea in the Incognito window?


I’ve tried,  same bug! Randomly simulate a touch on the screen, and it’s is impossible to continue working

**Comment by nothingshiru** [comment]
@photopea @gbunoni 
The fixed problem is related to the prompt about rasterizing smart objects. But in gbunoni's video, the bug appears after he used Quick Selection. So I think you two are talking different things.

**Comment by gbunoni** [comment]
> @photopea @gbunoni
> The fixed problem is related to the prompt about rasterizing smart objects. But in gbunoni's video, the bug appears after he used Quick Selection. So I think you two are now talking different things.

It is not a problem with quick selection, the bug appears in every scenario randomly

**Comment by nothingshiru** [comment]
> It is not a problem with quick selection, the bug appears in every scenario randomly with iPad Pro

The bug appeared after you use the quick selection, not just during the use of the quick selection. Even if you switch to other tools, it still exists.

**Comment by photopea** [comment]
Is it happening only on iPad?

**Comment by gbunoni** [comment]
> Is it happening only on iPad?

I only try with iPad Pro 12.9 2020, on safari

**Comment by gbunoni** [comment]
> > It is not a problem with quick selection, the bug appears in every scenario randomly with iPad Pro
> 
> The bug appeared after you use the quick selection, not just during the use of the quick selection. Even if you switch to other tools, it still exists.

No, this video is only an example, I repeat: the bug appear randomly in every scenario and independently on the instrument i use

**Comment by gbunoni** [comment]
> Is it happening only on iPad?

Have you find the bug? Believe me, it is unusable

**Comment by photopea** [comment]
I do not have an iPad to test it and reproduce the problem :( can you reproduce this problem on an Android phone with a finger? That is what I have.

**Comment by gbunoni** [comment]
> I do not have an iPad to test it and reproduce the problem :( can you reproduce this problem on an Android phone with a finger? That is what I have.

I understand, I have an Android phone but it wouldn't make sense to do a test on Android. The problem exists on iPad and most users who use photopea do it on iPad Pro, what I reported is a very serious problem that makes the software unusable, it is more important to solve it for you and not for me. I could also use another software if I wanted but this would mean for you that no one will ever approach the use of photopea. I'm sure you'll understand what I mean

**Comment by photopea** [comment]
Does the problem still persist?

**Comment by gbunoni** [comment]
> Does the problem still persist?

Yes

**Comment by photopea** [comment]
What iPad and what pen would you recommend me to buy, to be able to test this?

**Comment by gbunoni** [comment]
> What iPad and what pen would you recommend me to buy, to be able to test this?

I use iPad Pro 2020 12’’ with Apple Pencil

**Comment by MaksimMelan** [comment]
> What iPad and what pen would you recommend me to buy, to be able to test this?

if you need cheaper, then take the Apple iPad 10.2 "(2021) Wi-Fi 64 GB. although I did not recommend 64 GB, but this is the cheapest option of the modern ones. If you want to work on it constantly, then it is better to take more memory -128 or better 256 GB.I use Samsung myself.There is the same problem with the program (I tried to use it all the time - nothing was playing) .Samsung with a stylus has a lot of models, you can buy a used tab s3, tab s4 (once had support OS Linux mode), the modern cheapest model tab s6 lite (the same price as the ipad, but you can add a memory card, use it as a phone with calls, etc.) I now have a 12-inch tab s7 +, (I don't like ios and their file system. maybe later I will buy a second-hand ipad because of the Prokrate program)

**Comment by photopea** [comment]
But can you reproduce this problem on an Android device whit fingers only (without using a stylus)? If yes, I could reproduce it on my Android phone, without buying an iPad.

I am not planning to use an iPad, I wanted to buy it just to be able to reproduce the bug. It will probably go to my shelf after that, for eternity :D

**Comment by photopea** [comment]
I already have an iPad. If you still have any bugs, please, let me know.
