### ISSUE TITLE
`Document.saveToOE()` when multiple files are open

### ISSUE THREAD

**Issue by jelveh** [photopea/photopea#3947]
As far as I understand, `Document.saveToOE()` only returns an `ArrayBuffer` of the document and no other metadata, which is completely fine when only one file is open. However, in the case, where there are multiple files open in PhotoPea I can't seem to find a way to determine which file the response of `Document.saveToOE()` relates to. Is there any way to determine which file was saved? Maybe return a name/unique ID along with the `ArrayBuffer`?

Generally speaking, messages received by the parent window seem to be global and in case multiple files are open maybe attaching some file-specific ID/name to the message would be appropriate.

Thank you!

**Comment by jelveh** [comment]
Seems like I was going about this the wrong way. For anyone else interested, PhotoPea exposes a very powerful scripting protocol that is described here: https://www.photopea.com/learn/scripts

The scripting protocol and inter-window messaging allow you to do pretty much anything you need.

**Comment by photopea** [comment]
The method "saveToOE()" must be executed on a specific document, e.g. app.documents[3].saveToOE("psd") 

You must know on which document you are calling it, when you execute a script. You can also use e.g. app.echoToOE(myDocument.name);

**Comment by jelveh** [comment]
Thank you very much for your quick response.

This method works for the most part but a very serious issue can arise sometimes: if the user opens two different files with the **same name** (e.g. `/document/image.psd` and `/photos/image.psd` have the same name, but are different files) it won't be possible to differentiate between the two based on name alone. I was hoping maybe there is a way to attach a unique, custom ID to documents that will kind of act like file handles. This way when communicating with Photopea every file is uniquely identified regardless of its name.

**Comment by photopea** [comment]
When a file is sent to server, there is the "source" parameter: https://www.photopea.com/api/

Do your users open files from their computer, and you want to "steal" them using the "saveToOE()" script? You know, that there are X files opened, you can know a size of each PSD file, the name, etc. You can create IDs yourself (e.g. run a script, wich changes a name of a document). The user can open the same file from the same location twice. Shold the IDs be the same or different?
