### ISSUE TITLE
If I turn a hidden layer into a smart object I lose it.

### ISSUE THREAD

**Issue by paconaranjo** [photopea/photopea#3948]
https://user-images.githubusercontent.com/719690/140637226-8d1e788a-d22a-449a-bf49-ad86be7bdf0f.mp4

**Comment by photopea** [comment]
Hi, that is a correct behaviour. Your layer has moved into a Smart Object, and it is still hidden there. You would have to unhide it inside that Smart Object. The visibility of a smart object has no relation to the visibility of layers inside it.
