### ISSUE TITLE
just check screenshot

### ISSUE THREAD

**Issue by qulgentle** [photopea/photopea#3950]
![Uploading Screenshot_20211107-213217.png…]()

**Comment by photopea** [comment]
Hi, sorry, I can not see anything :(

**Comment by qulgentle** [comment]
oof
github is trash loading pics
lemme try again
![Screenshot_20211107-213217](https://user-images.githubusercontent.com/77129815/140658406-4eff73d5-b2b5-49ec-86bf-6ed909a178dd.png)

**Comment by photopea** [comment]
There should be advertisement on the right side of Photopea.

Please, watch our ads. As almost nobody wants to pay for a Premium account, ads are the only reason we still exist. Photopea would disappear a long time ago, if everyone was blocking ads as you do.

**Comment by qulgentle** [comment]
oooh, I'm ready to support you as much as i can,but id be glad if the ads section was somewhere else
sorry guys, I really love your "app" (kinda like a website but still an app)

**Comment by photopea** [comment]
You can order Premium, it costs only 3 USD a month, and your workspace will be larger for the whole month.
