### ISSUE TITLE
can't use "surface blur"

### ISSUE THREAD

**Issue by bl00dym4ry** [photopea/photopea#3953]

**Comment by photopea** [comment]
It seems like it works for me. What should I do to make it not work? Does Photopea shut down when you start Surface Blur, or what exactly happens?

**Comment by bl00dym4ry** [comment]
exactly! as soon as I click, a black screen appears and photopea goes out. I turn it back on, redo the same changes, wait 10 minutes for "surface blur" and it does the same but all this only on the computer, on the phone everything works fine. I do not understand.

**Comment by photopea** [comment]
Try these steps, let me know if it helped: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by bl00dym4ry** [comment]
nothing, the same happens to me :(

**Comment by photopea** [comment]
How large is your image? the Width and the Height in pixels?

**Comment by photopea** [comment]
I have to close it because the person stopped responding :(
