### ISSUE TITLE
Update The Pen Tool To Make It Like Photoshop's

### ISSUE THREAD

**Issue by Kristopian** [photopea/photopea#3957]
I Love The Way You Make Vector Art In Photoshop, It Is A Free-Handish System Where You Draw A Line Or Shape And It Turns That To A Vector.
-Tangent Below
I Love Photopea And I Don't Really Like Comparing It To Photoshop Because I Use Them Both About The Amount Of Time But I Honestly Love The Personalisation Photoshop Offers Over Photopea's, But I Do Find Myself Using Photopea A Bit More Because Of Its Ability To Be Used Online.
-Shameless Plug Below
My 6 Year Old Niece Grabbed My Drawing Tablet And Drew This 
![Kitty](https://user-images.githubusercontent.com/91993172/141012155-c292e574-7f3d-4484-849f-22b637366469.png)
Not Edited Besides The Name Censer

**Comment by photopea** [comment]
That is a nice drawing! What feature exactly would you like to be added or improved?

**Comment by Kristopian** [comment]
The Pen Tool In Photoshop Has A Feature Where You Can Freehand Vector Lines

**Comment by photopea** [comment]
Do you mean the Freeform Pen tool? We have it in Photopea, too.

https://helpx.adobe.com/photoshop/using/drawing-pen-tools.html

**Comment by Kristopian** [comment]
sorry i seem to have missed that

**Comment by mudwolf** [comment]
> Do you mean the Freeform Pen tool? We have it in Photopea, too.
> 
> https://helpx.adobe.com/photoshop/using/drawing-pen-tools.html

Isn't this the link to Official Adobe Website and I can't find the freeform pen tool in photopea .

**Comment by photopea** [comment]
It is called a Free Pen in Photopea

**Comment by camoody1** [comment]
> > Do you mean the Freeform Pen tool? We have it in Photopea, too.
> > https://helpx.adobe.com/photoshop/using/drawing-pen-tools.html
> 
> Isn't this the link to Official Adobe Website and I can't find the freeform pen tool in photopea .

![Screenshot_20230508_114028_Edge](https://user-images.githubusercontent.com/73725653/236868247-d2a093a7-780c-4980-b1fa-9898c9ee4e29.png)
