### ISSUE TITLE
Update the Stroke Path option in the Pen tool!

### ISSUE THREAD

**Issue by cgaldieri** [photopea/photopea#3958]
I know, **I KNOW** that we already discussed this on #3818! but **IS** important! as i already said
> Hello, so i make Minecraft thumbnails and i would really want the ~~Trace~~ Stroke path feature on photopea, its basically a must have feature for thumbnails and photopea is the only free tool that is almost identical to photoshop, thanks for reading!!!

But the photopea version is not completed yet!, you missed a menu, which contains 2 options:
- A option to choose which tool to 'stroke'
- A option to simulate pression

Both are also must use options. i don't have any images showing these options, but i can describe how the 2nd works, because the one i already described! So the 2nd works like this:
- Use the tool choosed in the 1st option
- The middle part of the path is always the larger `using the tool "max" size, defined before on the tool settings`
- The the ends of the path are always the smallest and with lowest opacity `the 'end' of the 'end' is totally or almost(idk if is totally or almost btw) invisible(0% of opacity)`

i dont have any images showing the menu or even a example of the result

# THANKS FOR READING

**Comment by MichalSZZ** [comment]
In Photoshop there is an option to stroke path with brush (or any other brush like tool) with pen pressure. 
![obraz](https://user-images.githubusercontent.com/38118273/141088639-dfa34e88-23b6-45a8-945a-b2ab896b48cb.png)

You can show that menu by clicking with ALT key on the stroke path icon in Paths palette.

**Comment by cgaldieri** [comment]
Whis is exactly waht i want

**Comment by cgaldieri** [comment]
@photopea HEY!!!! feature request

**Comment by cgaldieri** [comment]
you finnally came @photopea

**Comment by photopea** [comment]
Sorry, there are 110 other requests, and I am still alone working on Photopea :(

**Comment by cgaldieri** [comment]
ok

**Comment by cgaldieri** [comment]
i really need this, BUT this is your work, so do them, when you have time, try doing this one

**Comment by photopea** [comment]
We have implemented it, you can choose a tool for stroking and simulate the pressure :)
