### ISSUE TITLE
Not able to rename the layer in photopea by double clicking on it

### ISSUE THREAD

**Issue by ArjunShubh** [photopea/photopea#3959]
I am not able to rename the layer by double clicking, Please fix this bug. Is there any other method to rename the layer in photopea?

**Comment by MichalSZZ** [comment]
Two of my students have the same bug. 
I asked them to show chrome://extensions and they have no addons there.
I don't know how to reproduce it. On my machine - everything is OK.

In Photoshop there is a different place to do that - menu "Layer" -> "Rename Layer..."

**Comment by avagp** [comment]
i do can change it

**Comment by photopea** [comment]
I have fixed some weird behaviour of renaming. It should work better. Let me know if you still have problems.

**Comment by MichalSZZ** [comment]
Thanks!

@photopea you can think about adding rename feature in other place. In PS it is in menu 'layer'

**Comment by photopea** [comment]
I am afraid there would be too many items in the "Layer" menu, and it would be too confusing :(
