### ISSUE TITLE
Free Transform - close file error

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#396]
You can close file while doing Free Transform it does not cancel/confirm trasform and trasform controls stay on screen and it produces error when you click ALT or try to use confirm or cancel button

**Comment by photopea** [comment]
Hi, it is fixed now. But I have a strange feeling, that some other part could break (I removed one line of code and I am not sure what was the purpose of that line).

**Comment by hxim** [comment]
@photopea 
I open pea.psd
turn on Transformation controls
resize layer little bit
close file
->
Uncaught TypeError: Cannot read property 'T' of undefined
    at Yy.clear (pp.js:2831)
    at G.eO.disable (pp.js:2419)
    at Yv.yc (pp.js:5862)
    at Yv.yS (pp.js:5871)
    at Yv.yJ (pp.js:5873)
    at Ys.xh.R (pp.js:6)
    at Ys.K.R (pp.js:4078)
    at Ys.YK.pQ (pp.js:5707)
    at NF.xh.R (pp.js:6)
    at NF.K.R (pp.js:4078)

**Comment by photopea** [comment]
fixed, too.

**Comment by hxim** [comment]
start creating shape with Pen
close file
press ALT
->
pp.js:2621 Uncaught TypeError: Cannot read property 'M' of undefined
    at I.ML.I.Mt.iX (pp.js:2621)
    at zY.Ei (pp.js:5910)
    at zY.Eu (pp.js:5890)

**Comment by photopea** [comment]
Fixed.

**Comment by hxim** [comment]
no file is open
select Direct Select tool
press ALT
->
pp.js:2693 Uncaught TypeError: Cannot read property 'F' of undefined
    at i.he.wy (pp.js:2693)
    at Nx.yu (pp.js:5911)
    at Nx.yH (pp.js:5891)

**Comment by photopea** [comment]
You just uncovered a new class of errors - pressing keys when no project is open (we need to fix it for each tool).

**Comment by photopea** [comment]
Fixed.
