### ISSUE TITLE
Feature request: Curvature Pen Tool

### ISSUE THREAD

**Issue by kxtsuki** [photopea/photopea#3960]
[more info on it here](https://helpx.adobe.com/photoshop/using/drawing-pen-tools.html)

**Comment by photopea** [comment]
Hi, I have added the curvature pen tool. Let me know if it works as you expect.

**Comment by rakibulhasankanon** [comment]
> Hi, I have added the curvature pen tool. Let me know if it works as you expect.

I appreciate your concentration on this tool. But it should be accurate. When I am taking a new anchor point then the vector handle is very little, and the shape doesn't look like it should be. Please do some research on Photoshop or Illustrator's Curvature pen too.

You are doing a very good job. Thanks a lot.

Pardon my English.

**Comment by photopea** [comment]
What do you mean?
