### ISSUE TITLE
Artboard - Moving a group of layers to another artboard

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3961]
When i have a big group of layer selected and i want to move them to another artboard, the detection that those layers are in the new artboard is by the middle center of the group and no my cursor.

Please take a look at the video attached:
[Screen recording 2021-11-10 13.03.00.zip](https://github.com/photopea/photopea/files/7514192/Screen.recording.2021-11-10.13.03.00.zip)

If i drag the layer group to and leave my cursor on the new artboard it does not move the layers, but if i leave the middle of the group, it does.

**Comment by photopea** [comment]
fixed, thanks for reporting :)  BTW. I usually understand from the description, there is no need to make videos :)

**Comment by avagp** [comment]
:)

Making video is no great of a deal, and sometimes i can explain batter.

But thanks for fixing it!
