### ISSUE TITLE
Artboard - Export to PDF

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3962]
When i hide the artboards on the eye icon, and then export to png, the zip only contains the visible artboards, which is fine.

But when i do the same, but trying to export to PDF, i get the other artboard but blank.

![image](https://user-images.githubusercontent.com/11801254/141156289-b4a9c821-6c90-4132-8df7-6ad507c33f36.png)

It should only show and export the visible ones.

**Comment by photopea** [comment]
fixed :)
