### ISSUE TITLE
TPL+ATN file not working

### ISSUE THREAD

**Issue by Calixer** [photopea/photopea#3965]
It's to change text style. (auto leading, etc) my friend uses ps and sent me a tpl file (tool preset) but i can't seem to use it, is it because the feature is not available yet? or is it because of my way importing it?
for atn, the action is weirdly not playing, it does absolutely nothing
please help.
https://drive.google.com/folderview?id=1aHkPDveiuqk8DglImHxoD5XjkYaCXYQB
here is both the atn and tpl, and also show me the ways if you succeed using them...

**Comment by photopea** [comment]
Hi, your actions should work in Photopea now. However, it seems like your actions dont really do anything to the text in Adobe Photoshop. Let me know if there is something some action should do, and it is not done in Photopea.
