### ISSUE TITLE
Feature Request: Add a textbox into Save for Web dialog for renaming file

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3966]
It would be convenient for exporting multiple jpgs with different names while preserving the name of the psd.

**Comment by photopea** [comment]
The default name is a name of your document in Photopea. Your web browser should provide you an option to choose the final name, and a final location of a saved file.

**Comment by nothingshiru** [comment]
On mobile phone, the file is saved immediately after tapped the save button.

**Comment by photopea** [comment]
And is it saved with a name of a document in Photopea? What if there already exist such file? Is it replaced, or is the name changed automatically by a browser?

**Comment by nothingshiru** [comment]
If there's already such file, they will be like this: 
file.jpg
file (1).jpg
file (2).jpg
file (3).jpg
and so on.

**Comment by nothingshiru** [comment]
The results are same no matter what format the file is.

**Comment by photopea** [comment]
Can you update your browser? In the latest Chrome-based browsers, the browser should ask you, when you are saving a PSD for the first time.

**Comment by nothingshiru** [comment]
I cleared all data of my browser and updated it. Then I saw this
![Screenshot_20211119_193648_com microsoft emmx](https://user-images.githubusercontent.com/79258245/142617576-fbab2180-17d2-4603-a985-a246887a3f02.png)
I think I had checked "Don't show again" before.

But this pop-up window only appears when there already exsits a file with same name instead for the first time saved file.

**Comment by photopea** [comment]
I could add a field for a new name into the "Save for Web". But I am afraid almost nobody needs it, so it will only make the UI more confusing.

**Comment by nothingshiru** [comment]
If it looks like this, I don't think it's confusing. Please add it.
![Screenshot_20211120_075738_com microsoft emmx](https://user-images.githubusercontent.com/79258245/142706298-e144ca5e-d43e-46ca-b70a-395d33bbd37d.png)

**Comment by photopea** [comment]
Ok, I have added the field for a file name.
