### ISSUE TITLE
is this happening for anyone else?

### ISSUE THREAD

**Issue by ilysfmjkihu** [photopea/photopea#3967]
<img width="1440" alt="Screen Shot 2021-11-10 at 6 50 16 PM" src="https://user-images.githubusercontent.com/93348527/141215470-0ba1c0f8-ff50-4606-b35a-350aa95cee59.png">

it won't let me load anything.

**Comment by photopea** [comment]
Is it still happening?

**Comment by Llama2123232** [comment]
I get that error that as soon as I upload a file, google closes me and photopea also closes

**Comment by photopea** [comment]
Try this maybe: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because the person stopped responding.
