### ISSUE TITLE
[BUG]- Creating new shape (parametric) by clicking on stage - wrong sizes

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#3968]
Hi,

there is a bug when you create the parametric shape by clicking and adding W & H size in pop up window. 

Shapes are created bigger and it has strange angle...

Steps to reproduce:

1. Create new document
2. Use parametric shape tool
3. Set 4 sides in top toolbar (for rectangle, square)
3. Click on project to have pop up window with new shape parameters
4. Set for example 400 x 400
5. New shape is bigger and have not proper angle (Should to be straight to X and Y - look how it is made in PS) 

I wanted to do triangle this method but results was so so bad :) Wrong size and angle that will be big problem for my students :) I expected the base of the triangle will be perpendicular to the Y axis (as it is in Photoshop).
There can be Triangle with the width exactly like W parameter and height like H parameter. Unequal triangle.

**Comment by MichalSZZ** [comment]
Is there any chance to fix that?

**Comment by photopea** [comment]
Adobe Photoshop does not have the Parametric Shape tool. It only has the Polygon tool. Our Parametric shape can make a polygon, a star, an arrow, and a spiral.

The Polygon tool in Photoshop is strange. You draw it from the top left corner, and there is no way to make all sides equal. 

So you tell Photopea that you want a polygon 200x200 pixels, e.g. a triangle or a pentagon. Will you ever use it? Such polygons have each side with the different length.

**Comment by photopea** [comment]
I have fixed it a little. You should specify a square for the new Parametric Shape, and a new shape will be inside that square. 

But as I said before, if you have a square, and you want a new triange, pentagon, or a star, to touch all sides of a square, that new shape will be "stretched". So I am avoiding this (only one corner touches the square).

**Comment by MichalSZZ** [comment]
I am very sorry for no response. I had very bussy week.

Yes - Photoshop polygon tool is making a very strange shapes (not equal side lengths). I saw that when I was making hexagons.
But I think they made it in that way when they added a year ago live shape to polygonal and stars. I think before it was like in Photopea.

Thank you for your fix. Now is better. But... when I make a triangle by clicking and entering width and height - none of them are the width or height of my triangle.

**Comment by photopea** [comment]
I know. But if I draw a triangle with your width and height, you decide to make a triangle with equal sides, you would not be albe to do it (as you would not know what width and height to enter).

**Comment by nothingshiru** [comment]
We are able to create equilateral polygon in Photoshop. There are 2 options inside the menu for setting free, fixed ratio, fixed size, etc.

**Comment by photopea** [comment]
There is a "Symmetric" option in Photoshop, which is the only way to make a symmetric polygon. So now, Photopea works as the Symmetric mode in Photoshop.
