### ISSUE TITLE
How to make a stroke with Pen?

### ISSUE THREAD

**Issue by KiaraTu** [photopea/photopea#3969]
Hi
I have a question about using the Pen (P). It always creates a shape and when I want to make just a stroke a dialog box appears saying that the layer is not editable. But when I click on another layer the pen selection disappears.
![image](https://user-images.githubusercontent.com/92692897/141339051-8380de8f-6a1a-43f3-b877-da59fd383742.png)

![image](https://user-images.githubusercontent.com/92692897/141339000-955b286c-1395-41c0-9c03-f718007432e2.png)

**Comment by photopea** [comment]
The answer is the same as for Adobe Photoshop.

You need to draw with a path mode. If you want to paint a stroke along the path, you need to select a regular (pixel) layer.

https://www.photopea.com/learn/vg-creating

Or just find a tutorial about how to do it in Photoshop.

**Comment by KiaraTu** [comment]
Thanks, I wasn't realized that wasn't in path made.. as the page is automatically translated I was a little lost.

**Comment by nothingshiru** [comment]
@photopea 
Could you make the path mode the default? Like Photoshop do.
