### ISSUE TITLE
Normal and Shaddow Map dds

### ISSUE THREAD

**Issue by KiaraTu** [photopea/photopea#3970]
I'm trying to make a normal em specular map for a game creation. 
I'll put here my psd file.
When I saved it in dds and import it to the program that I use to create things for The Sims 4, it looks like a png file.. not dds with transparency/alpha channel. 
[Normal and Shaddow Map.zip](https://github.com/photopea/photopea/files/7360890/Normal.and.Shaddow.Map.zip)

**Comment by photopea** [comment]
I am afraid I do not understand. Your PSD seems to be completely different from your DDS.

I have no experience with Sims 4.
