### ISSUE TITLE
The app cruches when I open a file

### ISSUE THREAD

**Issue by FIREAD220** [photopea/photopea#3971]

**Comment by photopea** [comment]
How large is your file? You usually need about 3x to 10x more RAM memory than the size of your file.

**Comment by snemvalts** [comment]
It crashes for me with this image for example, when browsing and opening it. It's only 50kb. Laptop has 8GB RAM + more from swapping
![image](https://user-images.githubusercontent.com/3755903/141473272-dde81486-d20c-4e02-a13e-a79f512b5d28.png)

**Comment by photopea** [comment]
Try this https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I hope it helped. Let me know if there are still any problems.
