### ISSUE TITLE
Request: Remove the shadows on letters and icons

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3972]
Shadows are not good for reading. 
![screenshot_20211112_220808](https://user-images.githubusercontent.com/79258245/141480690-1b9e4402-edc6-41d1-9c17-6218477ef61e.jpg)

**Comment by avagp** [comment]
the shadow of the text, right?

**Comment by nothingshiru** [comment]
> the shadow of the text, right?

Right.

**Comment by photopea** [comment]
Do you mean the 1-pixel dark shadow behind the "Background" label and behind icons?

**Comment by avagp** [comment]
On other themes there are better contrasts
![image](https://user-images.githubusercontent.com/11801254/141848198-3d6757ae-11f8-4444-97c5-cb09044b6ca5.png)


Like in Light Grey theme

**Comment by nothingshiru** [comment]
> Do you mean the 1-pixel dark shadow behind the "Background" label and behind icons?

Yes.

**Comment by photopea** [comment]
I like the shadow and I think it makes the text look better.

**Comment by nothingshiru** [comment]
> I like the shadow and I think it makes the text look better.

Complex effects make eyes tired. You can find that the texts in most websites or apps will not have any shadows or other special effects.

**Comment by nothingshiru** [comment]
And the shadows of texts being at top while the shadows of button being at bottom results a weird looking. 
![screenshot_20211116_053333](https://user-images.githubusercontent.com/79258245/141857391-8e7b9677-ef40-41bf-8e21-82f7fb9eaab7.jpg)
