### ISSUE TITLE
The minus sign in Color Range is incorrect

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3974]
It is too long. 
![screenshot_20211112_222846](https://user-images.githubusercontent.com/79258245/141483336-5b0e3e05-aa21-4ea7-b468-a1268d0d75f3.jpg)
Also I would like to ask whether the one in Hue/Saturation is correct.
![screenshot_20211112_222909](https://user-images.githubusercontent.com/79258245/141483498-2cbd468b-0730-41c8-8cbd-db8d961b0fef.jpg)

**Comment by photopea** [comment]
fixed! :)
