### ISSUE TITLE
Request: Improve the look of the slider menu

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3975]
1. Add border. 
border-width: 1px; 
border-color: (Use the same color as the border of the brush menu);

2. Add padding left and right. 
padding: 0 8px;

3. Turn it into a rounded rectangle. 
border-radius: 4px;

Do you think it is better?
![Screenshot_20211113_000530_com microsoft emmx (1) (1)](https://user-images.githubusercontent.com/79258245/141642309-d23de642-1610-4667-88d2-235bb1a08cba.png)

**Comment by photopea** [comment]
ok I made it like this :)

**Comment by nothingshiru** [comment]
I'm very sorry that I didn’t clearly understand the effect of padding. 
What I expected is that the width of container is preserved and the slider is shorter. Could you make it like that?

**Comment by photopea** [comment]
But I think it looks fine now, too short would be uncomfortable to use.

**Comment by nothingshiru** [comment]
I just think it’s better to align the slider and the label in the center. How about moving it 8 pixels to the left?
![Screenshot_20211118_201926_com microsoft emmx](https://user-images.githubusercontent.com/79258245/142424429-d858489b-3736-4772-8cda-4a42d372b076.jpg)

**Comment by photopea** [comment]
Ok, I moved the floating bubble to the left a bit.

**Comment by nothingshiru** [comment]
Now it looks nice :)

**Comment by nothingshiru** [comment]
Can the floating bubble of virtual keys have border and rounded corners too?

**Comment by photopea** [comment]
Done :)
