### ISSUE TITLE
Quick Mask No erase

### ISSUE THREAD

**Issue by Acadian** [photopea/photopea#3976]
When entering quick mask,  I cannot erase mask selection.  Erasing just causes it to add to the mask selection.

**Comment by photopea** [comment]
When you erase channels, masks, or a quick mask, the Eraser tool actually "paints with a background color". So it depends on whether your background color is black or white, it will either "add to a mask" or "remove from a mask".

The foreground and a background colors are at the bottom of a toolbar.
