### ISSUE TITLE
When i try to export the gif the app crashes.

### ISSUE THREAD

**Issue by JDAFFDADAKFDAHFDAKJ** [photopea/photopea#3977]
I tried it on multiple devices and it is always the same thing. Also i forgot to add this, it is not about the specific gif or anzthing like that, i also tried with other gifs and pics. It works with pics but not gifs whenever i click on file and then export and click and just nothing happens for a bit and it just crashes and i do it over and over again could someone please tell me what is this about?

**Comment by photopea** [comment]
Can you open this GIF in Photopea and then, save it back as a GIF, without any editing
![animated](https://user-images.githubusercontent.com/15955558/141642965-b2516d2e-8133-4550-84cb-69d467f4706f.gif)
?
