### ISSUE TITLE
Show selection border around current selected layer

### ISSUE THREAD

**Issue by mariusa** [photopea/photopea#3978]
In GIMP there's a dashed border  around current selected layer:
![2021-11-12_23-14](https://user-images.githubusercontent.com/1283842/141535256-8be297fd-309d-4686-b020-4954568e044d.png)
![2021-11-12_23-14_1](https://user-images.githubusercontent.com/1283842/141535266-b9821f16-8575-48cd-8f00-7533623e8daf.png)

This makes it easy to identify the layer in img.

photopea doesn't have this, I can't tell what's the layer in img after selecting it in layers panel. Hard to move it etc.
Please Show selection border around current selected layer.

**Comment by MichalSZZ** [comment]
You can turn on "transform controls" in Move tool. It show layer bounds after selecting the layer.

**Comment by mariusa** [comment]
Thanks, that works!
