### ISSUE TITLE
space is left.

### ISSUE THREAD

**Issue by EntryFireRun** [photopea/photopea#3979]
![image](https://user-images.githubusercontent.com/91599874/141606940-db689783-e610-490e-b0ec-10c86f555b8e.png)
*An empty space is left on the far right of the menu.*

**Comment by xan2622** [comment]
This is where ads appear.

**Comment by EntryFireRun** [comment]
I didn't know because there was a program that blocks advertisements.

**Comment by xan2622** [comment]
No ads = no photopea. 
https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by EntryFireRun** [comment]
Um... I think I need to watch the commercial. I made a big mistake.

**Comment by xan2622** [comment]
Note that you are not obliged to click on the commercial. 
You can just let ads appear on the right side and continue using Photopea.

If your adblocker extension (in your web browser) blocks ads, you might want to whitelist Photopea (no need to completely disable your adblocker).

**Comment by EntryFireRun** [comment]
Thank you.
