### ISSUE TITLE
WON'T LET ME SAVE PICTURE

### ISSUE THREAD

**Issue by mickie123456789** [photopea/photopea#3982]
I spent 1 hour editing a picture and it let me save it 
then i spent another hour on the picture and it wont let me save it again . i need help asap

**Comment by mickie123456789** [comment]
??? now other functions arent working

**Comment by photopea** [comment]
How do you save your pictures? What should I do at Photopea.com to not be able save my picture (whatever that means)?

**Comment by photopea** [comment]
I have to close it because the person stopped responding :(
