### ISSUE TITLE
Match color doesnt work if source isnt in the same file as the target

### ISSUE THREAD

**Issue by kxtsuki** [photopea/photopea#3984]

**Comment by photopea** [comment]
I can not reproduce it. Could you provide steps how to reproduce it?

**Comment by kxtsuki** [comment]
> 
> 
> I can not reproduce it. Could you provide steps how to reproduce it?

Checked again and the bug seems to be fixed since it works fine now :)

**Comment by photopea** [comment]
Ok :)
