### ISSUE TITLE
Script to change app.foregroundColor and app.backgroundColor

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#3986]
This photoshop script to change current foreground and/or background color in photopea is not working. I can read it but I am not able to change it from my plugin via script. (nothing happens current color is not changed)
```
var color = app.foregroundColor;
color.rgb.red = 255;
color.rgb.green = 0;
color.rgb.blue = 255;
app.foregroundColor = color;
```

**Comment by photopea** [comment]
Fixed! You should be able to set both app.foregroundColor and app.backgroundColor :)

**Comment by hxim** [comment]
Thank works great as you can see in my adaptive palette plugin in #3851
