### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3987]
Hi, I created a icon for Notes panel. 
And I changed the icon of Gallery panel a bit. The grey background is removed and the size is enlarged to 160*160. 
Besides, I think the icon of the filter of images kind in Layers panel can be replaced with this one.

Do you think they look good?
![icons (2)](https://user-images.githubusercontent.com/79258245/141694148-8ea8ffcc-3a89-4aec-aa87-f65df9c634ab.png)
[icons (1).zip](https://github.com/photopea/photopea/files/7534403/icons.1.zip)

**Comment by nothingshiru** [comment]
Icons for history panel and swatches panel.
![Icons2](https://user-images.githubusercontent.com/79258245/141693949-917aaeb7-9714-490c-ab14-8674f0977b1e.png)
[Icons2 (1).zip](https://github.com/photopea/photopea/files/7534388/Icons2.1.zip)

**Comment by photopea** [comment]
I have updated the Notes icon. I used the color lookup icon for Swatches (Swatches is a table of colors). But your History icon looks like the Notes icon with some "time".

**Comment by nothingshiru** [comment]
What about the gallery icon?

> I used the color lookup icon for Swatches (Swatches is a table of colors). 

I was not sure if that's ok, so I created a palette icon.


> But your History icon looks like the Notes icon with some "time".

I think it's a list of things done. Does it make sense?

**Comment by photopea** [comment]
We already have a gallery icon and I think yours looks identical. How exactly is it better?

**Comment by nothingshiru** [comment]
The gray background of the current one makes it look not good in light color theme. I removed it.
![screenshot_20211120_074512](https://user-images.githubusercontent.com/79258245/142705256-e7c933d7-b495-49d8-bb4e-c7e25194dee1.jpg)

**Comment by photopea** [comment]
Actually, the Gallery is a plugin (it is in Window - More), and icons of plugins have always the same color (the colors do not change when changing a theme, like for other icons).

**Comment by nothingshiru** [comment]
I improved it. 
Now it always has a same color. And here is the comparison with the original one.
![Screenshot_20211120_182054_com microsoft emmx](https://user-images.githubusercontent.com/79258245/142723072-459edf19-edc7-4025-ac3d-9d912178e854.png)
[Gallery.zip](https://github.com/photopea/photopea/files/7574347/Gallery.zip)

Is it fine?

**Comment by photopea** [comment]
I allowed plugins to provide "modifyable icons", and updated the gallery icon.

**Comment by nothingshiru** [comment]
Thanks. 

Could you replaced the one in Layers panel too?
![screenshot_20211120_193853](https://user-images.githubusercontent.com/79258245/142725046-f967678f-abda-486c-aae1-ef4aa58fb68c.jpg)

**Comment by photopea** [comment]
but why? that icon is fine.

**Comment by nothingshiru** [comment]
New one is better...

**Comment by nothingshiru** [comment]
Should I create a new History icon? 

I see that the icons about history in a lot of APPs are just a clock. How about we do the same?

**Comment by photopea** [comment]
I put your icon for a History. I modify your icons a bit, when I feel like they need slight fixes. I hope it is ok with you.

**Comment by nothingshiru** [comment]
That's ok. Thanks
