### ISSUE TITLE
Alt + Click : doesn't work

### ISSUE THREAD

**Issue by iamophaniel** [photopea/photopea#3989]
Hello,

I'm trying to follow a Youtube tutorial on Photopea (https://www.youtube.com/watch?v=ZRTCZQRvNgc).
At several point in the video it asked to "Alt + Click", for exemple at 9:15 in the video.
However it doesn't work for me.
I tried on different computer and different browsers, however the result is the same : for photopea, even if I hold my ALT key it react like if I don't and just do a basic left click

**Comment by photopea** [comment]
Can you Alt+click with the brush tool? Does it paint a dot? Are you on a Chromebook?

**Comment by iamophaniel** [comment]
I'm not on Chromebook
And Yes alt+click in the brush tool paint a dot

**Comment by photopea** [comment]
Can you go here: http://jsfiddle.net/p45f44zb/14/ , click into the bottom right part and press Alt?

That tool should show you all keys, that are pressed at the moment. What code do you see when you press Alt?

**Comment by iamophaniel** [comment]
Well, I tried and the key ALT is nost recognised ...
I tried with MAJ, Ctrl, ... I can see them be written in bottom right part, but for ALT nothing is shown

**Comment by photopea** [comment]
So what operating system and what browser is this? Does your Alt key do anything outside the web browser?

**Comment by iamophaniel** [comment]
It's a Windows 10,
i prefer to use opera GX as a browser but I tried on Mozilla, Chrome, (But I won't Microsoft Edge) ...
And Yes the ALT keys works perfectly in the web browser, it open the FILE menu ; and outside of the web browser too

**Comment by photopea** [comment]
Have you tried this in all browsers?  http://jsfiddle.net/p45f44zb/14/

**Comment by iamophaniel** [comment]
I restarted my PC and it seems to work on chrome but still doesn't on my main browser (opera GX)

**Comment by photopea** [comment]
I think it is a bug in your Opera, is it updated? Are you using any browser extensions in Opera?

**Comment by photopea** [comment]
I have to close it because the person stopped responding :(
