### ISSUE TITLE
Ad is causing severe lag

### ISSUE THREAD

**Issue by HarmonyFerreira** [photopea/photopea#3991]
For some reason, the app is acting like the ad is covering the entire screen. So every time I go to paint the program acts as though I double-clicked on the ad on the sidebar.

The ad doesn't open, but the program stalls for about 15 seconds. And when it returns again anything I did after that stroke ignores my pressure settings and draws straight lines to where I clicked. while the program was frozen.

The bounding boxes for the ads need to be re-evaluated.

**Comment by HarmonyFerreira** [comment]
it is also causing issues with the menus and saving

**Comment by photopea** [comment]
I 99.99 % sure that you have a browser extension, which inserts ads into Photopea. Let me know if it still happens after you disable all your extensions (or in Incognito mode).

We have this tutorial: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by HarmonyFerreira** [comment]
So I solved it by restarting the program. I saved and closed everything and then opened it again and it worked fine. it probably WAS an issue with chrome, not Photopea but the only active extension I have is a security one that BLOCKS harmful ads so idk what was going on.

probably just a server timeout issue.

**Comment by photopea** [comment]
That is the best way to make people install a virus, call it "security extension that blocks harmful ads" :)

How many users does your extension have? Did you try to google the name of your extension or the creator?

**Comment by HarmonyFerreira** [comment]
it's a McAfee security extension...

provided by Bell Canada.

pretty sure it's legit lol
