### ISSUE TITLE
Issue when launching

### ISSUE THREAD

**Issue by G1Lyos** [photopea/photopea#3992]
Hi! 

I have a newly occuring issue whenever I open Photopea. Screenshot for what is occuring. This has only begun happening in the last two days. 

![PhotopeaIssue](https://user-images.githubusercontent.com/94466375/142009347-4e0c2631-41a1-41b6-b2a5-625a5a8a28a7.PNG)

**Comment by photopea** [comment]
can you open Photopea in a web browser? Could you update your web browser?

**Comment by G1Lyos** [comment]
Thank you for your reply, it only works in Incognito mode, my browser is fully updated too

**Comment by photopea** [comment]
So it works in Incognito? Try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by cgaldieri** [comment]
the photopea is not loading the css style

**Comment by photopea** [comment]
I have to close it because of lack of details :(
