### ISSUE TITLE
Align icons missing in Chromebook

### ISSUE THREAD

**Issue by mfuller526** [photopea/photopea#3993]
My friend has a Chromebook and we could not see the align icons. I see them fine in my MacBook Pro w Firefox and Chrome (Firefox screenshot below).

<img width="733" alt="Screen Shot 2021-11-16 at 9 41 45 AM" src="https://user-images.githubusercontent.com/1572817/142037506-79cdc42d-849c-405f-a81d-5671a494eef4.png">

**Comment by photopea** [comment]
So what exactly does your friend see? You can drag-and-move this top bar (e.g. if you use Photopea on a phone with a small screen).

**Comment by mfuller526** [comment]
See's nothing to the right of "SVG". I clicked on the " <> " to reveal info, text, etc. Unfortunately I am not there now.

**Comment by photopea** [comment]
Just tell your firend that he can click and drag the top bar with a mouse or with a finger.
