### ISSUE TITLE
Vector from AI looks super weird

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3995]
I cannot describe, but the vector image is not like it should.

It has all this rays.

![image](https://user-images.githubusercontent.com/11801254/142087710-2e24b567-9f37-4fb7-b55e-bcd7bfc9d11d.png)

And should look like this:

![vectorstock_32841325](https://user-images.githubusercontent.com/11801254/142087731-fc1b925d-db3c-4adb-86cb-8917a94dc790.png)

here is the AI
[vectorstock_32841325.zip](https://github.com/photopea/photopea/files/7550762/vectorstock_32841325.zip)

**Comment by Kristopian** [comment]
Photopea Struggles With Vectorization (The Raster To Vector AI Thingy) When The Image Has Multiple Colors, Two Colors For A Layer And Using Reduce Colors Will Produce A (Slightly) Better Image

**Comment by photopea** [comment]
This was a really stupid bug ... I only had to add two characters into my code to fix it :)

**Comment by avagp** [comment]
Hahahaha
Cool!
