### ISSUE TITLE
Opening photopea error message

### ISSUE THREAD

**Issue by PeterChu01** [photopea/photopea#3998]
Opening photopea error message
![20211118_001619](https://user-images.githubusercontent.com/94348022/142240785-bf1d9776-e318-4eac-8da0-1377fcdbe8d5.jpg)

**Comment by photopea** [comment]
Did you try to open some file in Photopea? Could you send us your file? We can not fix the problem without seeing your file.

**Comment by PeterChu01** [comment]
Open photopea show the error, the open my file.  Here is the link.

 

 <https://1drv.ms/u/s!AlWtslGKsLULgjPlaqJuG1j1-jTO?e=wwsljJ> https://1drv.ms/u/s!AlWtslGKsLULgjPlaqJuG1j1-jTO?e=wwsljJ

 

Regards,

Peter Chu

**Comment by photopea** [comment]
I was able to open your PSD in Photopea without any problems. Did you try to open it more than once?

Your PSD file is 700 MB. You would need about 4 GB of free RAM and about 3 GB of free GPU memory to open it in Photopea.

**Comment by PeterChu01** [comment]
Hi,

 

My problem is really when I initially pointed to photopea and open the app itself, then there prompt the error message even before I use photopea to open another file. 

 

Regards,

Peter Chu

**Comment by photopea** [comment]
Are you using Photopea at www.Photopea.com ? I just opened it and there is no error message :(

**Comment by PeterChu01** [comment]
Hi,

 

Please check the video.  

 

https://www.dropbox.com/s/8tzlu8qerby619r/20211118_231359.mp4?dl=0

 

 

Regards,

Peter Chu

**Comment by photopea** [comment]
Try these steps: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/
