### ISSUE TITLE
Vector - Extrange rays on vector

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3999]
[Screen recording 2021-11-17 16.57.38.zip](https://github.com/photopea/photopea/files/7557649/Screen.recording.2021-11-17.16.57.38.zip)

![Screenshot 2021-11-17 16 55 22](https://user-images.githubusercontent.com/11801254/142274176-c4205ba4-6947-4385-b026-ff72c4061049.png)

Ok, now i need a video.

At some points of zoom the vector anchors, send blue rays! (just visually)

**Comment by avagp** [comment]
i think it is similar to https://github.com/photopea/photopea/issues/3995

**Comment by avagp** [comment]
here si the PSD
[Shape 2.zip](https://github.com/photopea/photopea/files/7557686/Shape.2.zip)

**Comment by photopea** [comment]
I can not reproduce it with your file :(  I think I would not be able to create such beautiful effect even if I tried to make it on purpose :D

Are you using Linux? I remember that in the past, your browser was rendering the same PDF file differently each time. Have you tried to update your browser, or try some other browser? Is it a Beta version of a browser? Maybe it is a bug in your browser, which happens only on Linux.

**Comment by avagp** [comment]
:/

I am on Chrome m94 stable channel.

To be clear, the tays appear on pixel to pixel zoom.

If you really cannot repro on Chrome, maybe we can create an issue on chromium project, maybe is something with the GPU rendering

**Comment by photopea** [comment]
The current Chrome is Chrome 96, could you try to update it?

**Comment by avagp** [comment]
Chrome on ChromeOS is 94
![image](https://user-images.githubusercontent.com/11801254/142734950-f6aee927-b1ca-43f2-a800-49c6d7696960.png)


I won't be changing channels, to get to 96, because this is my working device.

But leave this issue open, when i get the update i will come back and report.

**Comment by photopea** [comment]
You still did not tell me if you are using Linux, or what OS is that. Maybe you have problems with your drivers.

I will close it, but we can keep discussing it.

**Comment by avagp** [comment]
I have chrome os

**Comment by photopea** [comment]
Maybe you could report it to Chrome Developers? As a bug in context2D vector drawing. 

What if you move Bézier points slightly, is it still happening? Does it happen at every zoom level?

**Comment by avagp** [comment]
i am attaching a video, so i can show you what i did.

Maybe it have something to do with this shape in particular. Or certain anchors.

https://wetransfer.com/downloads/09970aba33e927f3029822f500de339220211122162518/91bcd29542580d09182c32e54be8360a20211122162518/b17815

**Comment by photopea** [comment]
Wow, that 650 MB video is too long :D

Your shape has 11 points: https://www.photopea.com/#ixzZNXnmm  , Could you remove some points, but make sure it remains buggy? I want to find the simplest shape, which causes the bug.

**Comment by avagp** [comment]
Here
https://www.photopea.com/#iD8gQojWf
![image](https://user-images.githubusercontent.com/11801254/143081661-ca19264d-381f-4aa2-a527-61fb6318acd4.png)

**Comment by avagp** [comment]
I got one with 3 anchors
![image](https://user-images.githubusercontent.com/11801254/143082260-cc95e439-3325-49b0-8574-b1a74b8009ce.png)


https://www.photopea.com/#iM-PDIH_7

**Comment by photopea** [comment]
Could you see the same problem here? There is a white area at the bottom right, scroll it to see the whole picture.

https://jsfiddle.net/ohL18wxb/1/

**Comment by avagp** [comment]
I see the shape.

But don't see the glitch.
![image](https://user-images.githubusercontent.com/11801254/143090093-7702eef8-7a2b-4d13-bb88-bf8bc331ce6d.png)


Although, the zoom in JSFiddle is not the same/

**Comment by photopea** [comment]
What about this? Do you see an error here? https://jsfiddle.net/xvLjh6br/

**Comment by avagp** [comment]
no
![image](https://user-images.githubusercontent.com/11801254/143092986-e78a7f91-dff4-43c9-90a3-c79be62a9bca.png)

**Comment by avagp** [comment]
I believe it has something to do with the blue stroke surrounding shapes.
![image](https://user-images.githubusercontent.com/11801254/143093410-2a7fc17e-0d1d-4aed-9802-fca962e1d61e.png)


Where it gets glitchy the stroke is not on the perimeter of the shape.

**Comment by avagp** [comment]
Also, when i change zoom levels, from pixel to pixel to fixed, the blue shape changes a little

**Comment by photopea** [comment]
Could you maybe simplify your shape even more? Make it a straight triangle?

**Comment by avagp** [comment]
There
![image](https://user-images.githubusercontent.com/11801254/143133939-b602d139-4772-4786-b017-114969e6c00b.png)

https://www.photopea.com/#iJyPUqcU-

**Comment by photopea** [comment]
What about this? Do you see an error here?  https://jsfiddle.net/61mvz42r/

Do you see an error at all zoom levels?

**Comment by avagp** [comment]
![image](https://user-images.githubusercontent.com/11801254/143140872-8470626a-b932-4fd8-9b10-c1734e39899f.png)

i don't see anything.

And for zoom level, you mean Ctrl+(+) on the web browser?
![image](https://user-images.githubusercontent.com/11801254/143140993-4a53ad1d-529b-4e34-a712-344604df0352.png)

**Comment by photopea** [comment]
I think I give up then :( I would really need a computer, where it happens, to be able to explain the bug to Google. Maybe try using Firefox? Or hope Google will fix it in the next release.

**Comment by avagp** [comment]
i will report it to chromium project.

Hope we can get some info there :/

**Comment by avagp** [comment]
Hey Ivan, they replied from chromium:
![image](https://user-images.githubusercontent.com/11801254/144496291-4305af3c-f6d8-45d2-a3ec-dc46d8238916.png)

**Comment by photopea** [comment]
so it will probably be fixed with a future Chrome OS update.

**Comment by avagp** [comment]
Now i have v96 and it got fixed :D

**Comment by photopea** [comment]
great! :)
