### ISSUE TITLE
unable to open .psd files

### ISSUE THREAD

**Issue by mvkishore** [photopea/photopea#4]
When I try to open .psd files which has been saved from adobe photoshop are not working at all.

**Comment by photopea** [comment]
Hi, thank you for reporting that. There may be a bug in Photopea.

Can you send me one of your files to support@photopea.com, so I can check what is the problem and fix it as soon as possible?

**Comment by photopea** [comment]
Unable to reproduce this bug. Feel free to reopen it, if you have a problematic PSD file.
