### ISSUE TITLE
Add gray shadow around the image

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#40]
It will look better.

**Comment by photopea** [comment]
Done. Let me know if you like it :)

**Comment by ewnjtgouierg** [comment]
May be just me, but I'd really like to be able to turn off this shadow (I don't need it at all, but I understand if other users like it). When working with image, I need to see the image lines and colors, precisely where the image ends etc, and the effect interferes.

**Comment by photopea** [comment]
You really don't see where the image ends? Can you show us what you see?

**Comment by ewnjtgouierg** [comment]
attached is a good example: the left edge of the image is a ~gray-scale gradient line, and the decorative shadow doesn't help at all, to put it mildly :D
of course, there're many cases when it doesn't happen, but even then, when you zoom in - imho - shadow doesn't look good (it just becomes a blurry something)
I understand that originally it was probably added as an effect for typical scenario of opening a photo and applying some filters etc - then it probably looks nice as a shadow decoration for the photo
but when you zoom in, do some precise work with small things etc, the shadow is, in essence, an extra information which draws your attention, but doesn't belong to the image your work on

anyway, it's just an opinion. for me it's interfering, but may be I'm unusually sensitive to such etc

**Comment by photopea** [comment]
Have you tried to change the theme? More - Theme - Black ?

**Comment by ewnjtgouierg** [comment]
the degree to which this becomes an issue does depend on how specific image and specific theme match up, but changing theme from your preferred one to something else to resolve an interface issue, of course, is not something anyone would want. By the way, I switched to the brighter theme (from the original dark one) as a suggested solution to another problem. But I was glad b/c I belong to those who always prefers white and never understood how other people use those dark themes lol

a related question:

I understand that you cannot add a setting for every little thing to resolve every wish that may be only one user has. It's costly + would complicate preferences. But have you considered some method to have kind of "advanced" settings for "advanced" users?
For those who is technically savvy and can run some script when page is loaded?
Like, in example of this issue, you could add a flag photopea.canvasShadow, and tell me and whoever might want the same later, to set photopea.canvasShadow to false?

**Comment by photopea** [comment]
I made two "worst cases" for you. In the first one, I fill the document with a color of a shadow. In the second example, I filled the document with a color of a theme.

I think the shadow is always better. At least, it tells you, where the document is located. I can not imagine any case, where it would be better without a shadow.
![image](https://user-images.githubusercontent.com/15955558/63768569-d7283500-c8d0-11e9-839b-b9f589410702.gif)

**Comment by MichalSZZ** [comment]
In Photoshop, you can change workspace background color by clicking right mouse button on it. Then you can change to white, black, gray or to custom color. I use that function from time to time, to see how e.g. web banner will look like on white.

**Comment by ewnjtgouierg** [comment]
ok, I'm kind of confused - you give literally 1 - very specific and artificially created - example, when having no shadow is a problem - and based on this you're saying that shadow is always helpful and you cannot imagine any case where it's a problem, even while I gave you the real-life example of that in the very beginning?

**Comment by photopea** [comment]
I don't like complicated things with many complicated options. That is why I don't want to add an option to disable shadow.

If your document is exactly the color of a shadow, you can temporarily change the color theme.

**Comment by ewnjtgouierg** [comment]
"If your document is exactly the color of a shadow, you can..."
^^^^^^  this was the problem that _you_ raised, actually lol

**Comment by ewnjtgouierg** [comment]
the problem is the thing you added from the beginning - the shadow - is a complicated thing, which adds more problems than it solves

**Comment by photopea** [comment]
You can hide shadow by pressing More - Use WebGL.

**Comment by ewnjtgouierg** [comment]
thank you, of course, it works for me 100%, but that's all until one day someone who does need WebGL asks the same, or I post some other issue and you reply: "do you have WebGL off? this feature needs WebGL to work well" ))
you say you don't like complicated options - but that's exactly why I wrote a full paragraph suggesting adding flags of some sorts = without adding any settings to interface; you didn't reply to that - probably means that doesn't work for you, ok
googled & found PS introduced similar shadow at some point, but they do offer a way to disable it in settings, luckily b/c some people asked about it, finding it similarly "annoying"
anyway, thanks for the workaround! cheers

**Comment by MichalSZZ** [comment]
@photopea I understand what author of this issue want to have in Photopea. One of my friend (graphic designer with +15 years of experience) doesn't like canvas shadow too. He has shadow turned off for the workspace in photoshop all the time.

Adobe saw this problem in the past and gave his users possibility, to change this two options (shadow and backdrop color) manually in Photoshop prefferences.
