### ISSUE TITLE
font loading error

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#400]
font Ebrima from here https://www.dafontfree.net/download-ebrima-f63976.htm
won't load with error
->
Uncaught No postScriptName!
sM.$y @ pp.js:19
sM.To @ pp.js:13
$e.AY @ pp.js:5836
sn.l @ pp.js:6
a.l @ pp.js:4075
a.l @ pp.js:4075
$r.Aq @ pp.js:5667
$r.Ak @ pp.js:5650
FileReader (async)
$r.WK @ pp.js:5627
$e.AY @ pp.js:5830
sn.l @ pp.js:6
a.l @ pp.js:4075
a.l @ pp.js:4075
$m.AC @ pp.js:5737

**Comment by photopea** [comment]
It was fixed, thank you!
