### ISSUE TITLE
The Free Pen Option Seems A Little Jank

### ISSUE THREAD

**Issue by Kristopian** [photopea/photopea#4000]
I Was Messing Around With The Free Pen But I Noticed It Seems A Little Off
https://files.catbox.moe/e5hqpd.mp4
https://files.catbox.moe/yi9xgu.webm

**Comment by photopea** [comment]
Does there exist a software, where you do the same thing you did in Photopea, and it draws what you want? If it is even possible. Maybe your mouse is shaking too much.

**Comment by Kristopian** [comment]
I Noticed Sharp Corners Are Really Hard With Photopea While Sharp Corners Seem To Happen Way To Much By Default In Photoshop But You Can Adjust Photoshop's Free Pen A Lot More Freely In Photoshop To Fix That

**Comment by photopea** [comment]
It should work better now :)

**Comment by Kristopian** [comment]
Thanks
