### ISSUE TITLE
is .PSD extension neccesary? 

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4001]
This is more like a question rather than a suggestion.

I was wondering if there is a need to have on every name tab '.psd'? 🤔

I am missing a case where it should be necessary??

Because i think it just adds more space on the name tab.

**Comment by photopea** [comment]
I think it just says, that every opened thing is an "advanced document", which can have layers, etc.

People might think, that if they open a JPG instead of a PSD, they can not add layers to it.

**Comment by avagp** [comment]
I get it :)

thanks for explainning
