### ISSUE TITLE
saving psd into jpg for chrome

### ISSUE THREAD

**Issue by jordanfe13579** [photopea/photopea#4002]
I'm trying to export my PSD file into a jpg file but every time I hit save it doesn't download onto my computer as it used to, this has been happening for about 2 weeks now.

**Comment by photopea** [comment]
Try these steps. Let me know if it helped. https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by jordanfe13579** [comment]
Thanks it was the new extension I added big help!

**Comment by photopea** [comment]
What extension was it? Do they say in the description, that it will block downloading of JPG files?
