### ISSUE TITLE
I save by psd and then this:

### ISSUE THREAD

**Issue by tyngocminh20071** [photopea/photopea#4004]
![image_2021-11-18_194209](https://user-images.githubusercontent.com/83491995/142417264-7c9c4b65-c9a0-4683-bad6-15e1d770cfa9.png)
its 0 kb and i cant even open it, very nice, waste 1 hour of mine

**Comment by photopea** [comment]
Can you describe how can I make Photopea produce a zero-byte file?

When you save a PSD, there should be a message "saving ...". You should close Photopea only after this message goes away.

**Comment by tyngocminh20071** [comment]
i think the "save as psd" is broken. i just tried again and it still 0kb, pls fix it

**Comment by photopea** [comment]
Try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I think the user is using some browser extension, which prevents websites from saving any files to a computer.

**Comment by tyngocminh20071** [comment]
ah but the "save PSD/PSB.." works

**Comment by photopea** [comment]
Did you try the steps in my link?

If you are ok with "Save as PSD" not working, and you want to use "Save PSD/PSB", I can close this issue.

**Comment by photopea** [comment]
I have to close it because of lack of details.
