### ISSUE TITLE
Export PDF - Reverse pages

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4009]
![image](https://user-images.githubusercontent.com/11801254/142695462-974532ba-bb69-4342-902a-dfeaf7e187a8.png)

Could be a checkbox that changes the order of the pages?

**Comment by photopea** [comment]
I am afraid almost nobody needs it, so it will only make the UI more confusing. Could you reorder them in the Layers panel?

**Comment by avagp** [comment]
Yes i can reorder it.

But I order my layers putting the first elements on top and the last on bottom. So that apply to art boards, first on top, last on bottom.

So it is exactly the reverse order of export.

@nothingshiru and @MichalSZZ just to know. How do you order your art boards on the layers panel?

**Comment by photopea** [comment]
Ok, I have added a checkbox to reverse pages, instead of a checkbox to rasterize text (as I think nobody was using it).

**Comment by avagp** [comment]
Thanks.
Probably none used it if you export in PDF.

But I was wondering, do you have a tracker of some sort? Like a anonymous logger, where you track how many times X element was clicked on every session?

Of course not tracking any personal information.

That could give you an idea when you modify or add a feature.

**Comment by photopea** [comment]
I was too lazy to create such statistics. But I am counting the number of opened files of each type :D
