### ISSUE TITLE
Export to PDF - Vectorize text does nothing

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4011]
Vectorize text option does not change the PDF preview, neither exports as indicated.

![image](https://user-images.githubusercontent.com/11801254/142734801-0d760f89-ad94-4c01-bd9f-b0a1f99530f7.png)

**Comment by photopea** [comment]
That is really weird. Could you share your PSD with me? I can not reproduce it in "pea.psd".

**Comment by avagp** [comment]
There: [Rules Disco Rayado.zip](https://github.com/photopea/photopea/files/7582854/Rules.Disco.Rayado.zip)


It keeps happening :/

**Comment by photopea** [comment]
There was a bug. Our PDF exporter could not vectorize text, which had the special "text-stroke". The same bug was in the SVG export. Since the process of generating a new PDF crashed, you were still seeing the old PDF file.

I have fixed it :)

**Comment by avagp** [comment]
It realates with this bug?

**Comment by photopea** [comment]
no, it was not related.
