### ISSUE TITLE
Export JPG as Slices. Save button Not working.

### ISSUE THREAD

**Issue by jared33edwards** [photopea/photopea#4012]
Export as JPG is working fine when the Slices field is unchecked. But when the Slices field is checked the JPG Export save button isn't working.

**Comment by jared33edwards** [comment]
<img width="1268" alt="Screen Shot 2021-11-20 at 11 48 00 AM" src="https://user-images.githubusercontent.com/48071188/142736243-f49cb24b-0508-45b7-bb0c-913883322a74.png">

**Comment by photopea** [comment]
sorry, it is fixed now :)
