### ISSUE TITLE
problem with SVG file

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#4014]
open this file https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg
The stars are rendered wrong in Photopea. In browser looks good.

**Comment by photopea** [comment]
I am afraid it can not be fixed. Self-intersecting shapes are always drawn this way in PSD files :(

Try to draw this star (five vector points) in Adobe Photoshop and you will see it is not possible.

**Comment by MichalSZZ** [comment]
Ok thanks for your answer
