### ISSUE TITLE
Brush Masking

### ISSUE THREAD

**Issue by Shu2ik** [photopea/photopea#4015]
As awesome and great Photopea is as frustrating it can get when working with the brush tool on a mask.
It gets very, very sluggish real quick even if the document file isn't that large. Same goes with applying filters on smart objects.

**These are my system specs:**
iMac ( Retina 5K, 27-inch, 2017)
3,8 GHz Quad-Core Intel Core i5
32GB 2400 MHz DDR4
Radeon Pro 580 8GB

**Comment by photopea** [comment]
Are you talking about painting into a raster mask of a layer? How large is your document (in pixels) and how large is your brush?

**Comment by xInstead** [comment]
Using layer mask. Current resolution is 3500x7000
The brush size doesn't make a difference but it's impossible to work with it. The delay is like 1-3 seconds.

**Comment by photopea** [comment]
I just tried it in a 3500x7000 document and there is a delay, but it still runs at about 10 frames per second.

What web browser are you using? Is it more than 10 years old? Have you tried to update it, or do it in another web browser?

**Comment by xInstead** [comment]
Microsoft Edge latest version

**Comment by photopea** [comment]
I have made painting into a mask about 30 times faster :) let me know if it is ok now.

**Comment by xInstead** [comment]
I think I figured out where my problem actually lies.
It was and still is really bad with raster masks on color fill layers. It gets very sluggish with higher dimensions.

**Comment by photopea** [comment]
You are right, it is slow on fill layers. I will look into it :)

**Comment by photopea** [comment]
I am sorry, but it is very hard to make it work faster. You have 24 million pixels in your mage, and it takes around 0.04 seconds to redraw them. So it will run at 25 FPS instead of 60.
