### ISSUE TITLE
Feature Request: Add Transform Handles to quickly modify a selection

### ISSUE THREAD

**Issue by xan2622** [photopea/photopea#4016]
_The Gimp_ has an interesting way to modify selections: by moving the "_transform handles_" that are located in corners and at the top/bottom/left/right side of the selection.

<img src="https://user-images.githubusercontent.com/1732773/142756711-c35dac07-e631-4d9f-961a-51baeca74573.png" width="50%" height="50%" />

It would be convenient if Photopea featured these handles as well (maybe as an option, activatable by a checkbox ?).

Mock-up: 
(an icon would obviously take less space on the option bar rather than a checkbox): 
![transform_handles](https://user-images.githubusercontent.com/1732773/142756704-92abaff0-22d6-4b8c-ab86-6a908b2398da.png)

One big advantage of these "_transform handles_" is that they allow to modify a selection without using modifier keys (ALT or SHIFT).
https://youtu.be/Z2w_IFU_He4?t=73

**Comment by xan2622** [comment]
I've made an icon (in case you agrees to implement this suggestion): 
![transform_handles](https://user-images.githubusercontent.com/1732773/142758833-21669e2c-3a3d-46fb-9178-3809073fc302.png)

**Comment by photopea** [comment]
A rectangular selection is just one of many possible selections. It is used quite rarely. People usually make selections with the Lasso tools, or the Magic Wand.

In Photopea, you can press Select - Transform Selection, and transform any selection (not just rectangular), rotate it, etc.

**Comment by photopea** [comment]
I think Select - Transform Selection should be used in this case.
