### ISSUE TITLE
Misleading path reordering buttons for top and bottom paths in multisubpath layer

### ISSUE THREAD

**Issue by xilehence** [photopea/photopea#4018]
If the top subpath in a layer is selected, the "move up" ▲ triangle button should be desaturated, since that operation is impossible.
Likewise, selection of the bottom path should disable the "move down" ▼ button.
Selection of multiple paths should show both buttons, but only actually move those for which operation is possible.

Is there an implicit or implied order of the execution of such operations, such as bottom to top?
If there is an apparent conflict, such as trying to promote both elements of a 2-subpath path, i suppose that the bottom path would initially move to the top, and then the formerly top path, just implicitly demoted, would then get repromoted, so final order would be the same.

**Comment by photopea** [comment]
These buttons will always try to move all selected paths one step up or down. The result should be "as you would expect" - selected paths keep the same order within each other, just like the unselected paths.

**Comment by photopea** [comment]
I will close it, as I think it works as expected.
