### ISSUE TITLE
Brush Smoothing Options

### ISSUE THREAD

**Issue by xan2622** [photopea/photopea#4019]
Even before Photoshop introduced "_Brush Stroke Smoothing_" options in CC 2018, an utility already had these options: [LazyNezumi Pro](https://www.anonymz.com/?https://lazynezumi.com).

Both [Photoshop](https://youtu.be/9XuNNap4rLU) and _LazyNezumi Pro_ feature the following options: 

1. Pulled String Mode
2. Stroke Catch-Up
3. Catch-Up on Stroke End

As you can notice in this [link](https://www.anonymz.com/?https://lazynezumi.com/smoothing) and in this [video](https://youtu.be/lsIbF6Rvmak?t=336), this software features another option: 

4. the Weighted preset
 
Do you plan (one day) to implement these options?

---

Here is some (related?) javascript code that I found: 
- info: https://stackoverflow.com/questions/10567287/implementing-smooth-sketching-and-drawing-on-the-canvas-element
- demo: http://labs.crosspop.in/Croquispop/croquispop.html

**Comment by photopea** [comment]
I believe Photopea already has all these features built-in (they are enabled automatically, there is no need to enable them).

E.g. the "pulled String Mode" is enabled when you set the "Smooth" to more than zero.

Are there any specific problems you encounter while drawing?

**Comment by photopea** [comment]
I feel like you are simply throwing videos about Lazy Nezumi Pro at us, without even trying to check what is available in Photopea already :(

**Comment by xan2622** [comment]
> I feel like you are simply throwing videos about LazyNezumi Pro at us,

😕 I just shared the video to illustrate my suggestion... 
btw, these options are also present in Photoshop... (I guess I should have mentioned only it).

I have of course used the _Smooth slider_ in Photopea and as you said, it reacts like it pulls a string.
But well, I think that it could be interesting to have an option to "_Catch-Up on Stroke End_".
