### ISSUE TITLE
Feature Request: "Scripts" that affect lines 

### ISSUE THREAD

**Issue by xan2622** [photopea/photopea#4021]
This [utility](https://www.anonymz.com/?https://lazynezumi.com/scripting) allows to modify (on the fly) the shape, the pattern of a drawn line.

To do that, the artist can choose a pattern or an effect within several presets but can also write his/her own scripts that will affect the line.

These scripts can (for example) automatically draw patterns (dashes, dots, ...) while drawing straight lines, tweak the pressure response curve, or even add noise (jiggles) to lines by adding randomness to the pen pressure. 

It would be cool if Photopea had a plugin to do the same. This would allow to create a lot of variations in drawn lines.
Examples: 

<img src="https://user-images.githubusercontent.com/1732773/142770319-b557541e-8c51-4949-8307-b677876ee4ac.png" width="50%" height="50%" />

<img src="https://user-images.githubusercontent.com/1732773/142770373-969f67b4-1908-4759-9bc9-793d349534fc.jpg" width="50%" height="50%" />

**Comment by photopea** [comment]
I do agree, that Lazy Nezumi Pro is a great program. But why don't you simply use Lazy Nezumi Pro, instead of asking us to turn Photopea into Lazy Nezumi Pro?

I am afraid that if we add all features of all existing editors into Photopea, it would become a huge mess. Adding a feature is just one thing. But integrating it into the rest of tools is much harder. Also, with too many features, it becomes harder to find a feature you need, and I am afraid nobody will ever find out, that Photopea has such plugin. So I give it up.

**Comment by xan2622** [comment]
> I am afraid that if we add all features of all existing editors into Photopea, it would become a huge mess.

That is not what I would want either. :(
But there are good features here and there that are worth taking a look at (IMO), but of course, there would be no point of integrating all features of all editors into Photopea.

I just like to brainstorm ideas, trying to find good ideas to enhance softwares I use. 
Just like other guys who suggested new features for Photopea on Github, I just tried to contribute with an idea (which, I think, would have been nice to have in Photopea). 

> Also, with too many features, it becomes harder to find a feature you need, and I am afraid nobody will ever find out, that Photopea has such plugin

I think that many users don't know about the available plugins because their discoverability is quite low (IMO).  I guess _new Photopea users_ might not have the idea to go to "Window > More" menu.

I understand that you may not like some suggestions people (like mine), I am not offended, I hope you are not offended either by my three suggestions in a row.
