### ISSUE TITLE
Photopea keeps freezing

### ISSUE THREAD

**Issue by Obversa** [photopea/photopea#4022]
Photopea keeps freezing up on me today whenever I try to undo/redo actions. Possibly linked to video ads loading?

**Comment by photopea** [comment]
Could you describe how can I make Photopea freeze? After I open www.Photopea.com , what should I do next?

**Comment by Amariiii** [comment]
Yes the same thing is happening to me

**Comment by photopea** [comment]
Could anyone of you describe, how can I make Photopea freeze? Does it happen on a phone?

**Comment by Issavo** [comment]
Whenever I zoom in, it freezes.

**Comment by photopea** [comment]
Hi do you zoom in? I want to make it freeze myself. What device should I use? Is it a phone or a laptop?

**Comment by photopea** [comment]
I have to close it because of lack of details.
