### ISSUE TITLE
Request: Add options into context menu of Layers panel

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4024]
Please add these options into the context menu.

1. Select Pixels
2. Convert to Shape
3. Convert to Point/Paragraph Text

**Comment by photopea** [comment]
they are already in the context menu.

**Comment by nothingshiru** [comment]
I mean here.
![Screenshot_20211122_174836](https://user-images.githubusercontent.com/79258245/142839444-d42b23ef-ee35-4573-bd4c-7494a6572614.jpg)

**Comment by photopea** [comment]
but we already have them in the context menu, why would we have it twice?

**Comment by nothingshiru** [comment]
Becauce we can't use them without a mouse now.

**Comment by photopea** [comment]
So when you long-click a layer in the Layers Panel with a finger, it starts to drag-and-drop the layer, right? 

Maybe we could make it such that if you long-click a layer thumbnail, it will open a context menu. What do you think?

**Comment by nothingshiru** [comment]
> So when you long-click a layer in the Layers Panel with a finger, it starts to drag-and-drop the layer, right?

Right.

> Maybe we could make it such that if you long-click a layer thumbnail, it will open a context menu. What do you think?

I’m not sure if that’s good, but it’s worth trying.

**Comment by photopea** [comment]
I have implemented it. Long-tap also works as a right-click on a raster mas, vector mask and a filter mask thumbnails.

**Comment by photopea** [comment]
you should drag layers by long-tapping them anywhere else than the thumbnail. Long-tap on a thumbnail is for a context menu.

**Comment by nothingshiru** [comment]
We would face the problems when we drag masks.

**Comment by photopea** [comment]
ok, I removed these features from masks, so that they can be drag-and-dropped.
