### ISSUE TITLE
There seems to be a bug with the brush tool

### ISSUE THREAD

**Issue by Tornadof123** [photopea/photopea#4025]
There seems to be a new bug with the brush tool today where it has varying levels of glitching. While trying to smooth out lines with the brush tool it either wont do anything at all, will only partially smooth out the line, leaves uneven pixels, or wont do anything to certain parts of the picture. I don't believe that this issue is on my end as I tested it on a couple computers and it happened on both.

**Comment by photopea** [comment]
We updated the brush tool yesterday. What should I do to see the bug? Whatever I try, it seems to work fine in my case.

**Comment by Tornadof123** [comment]
After further investigation it appears that this bug only happens when you use the lasso tool to select your area and you go outside of the photo. It works normally when you keep the lasso completely in the photo, but once you bring it outside it starts getting buggy. This bug appears to be new because I have always used this technique and it has never been a problem for me until yesterday.

**Comment by photopea** [comment]
I tried it, but I still can not see the bug: https://i.imgur.com/o4fq11J.jpeg

Could you describe exact steps, which will let me see the bug?

**Comment by Tornadof123** [comment]
This isn't the best of examples but here is how it looks when the bug is happening: https://imgur.com/a/2HQibNc

In that picture I had the brush tool, with the hardness down to 0% and just went along the entire edge of the darker area and all those random weird straight boxes appeared and it didn't really smooth anything. However for whatever reason when I tried to replicated the glitch multiple times today sometimes it worked normally and sometimes it didn't. 

I guess the best way that I can try to give steps for you to replicate it is by first doing a lasso select area (and try to shape it like it did in my picture). Second would be to drop the brightness levels of the selected area. Third would be to select the brush tool and turn the hardness all the way down to 0% with the brush size being somewhere around the size of 150-200. The next step I guess would be to try and smooth the edges of the darker area and see if it does the bug or not.

**Comment by photopea** [comment]
I think I have probably fixed it, could you try it again?

**Comment by Tornadof123** [comment]
Unfortunately it seems to still be happening on my end.

**Comment by photopea** [comment]
So it happens only for the masks? I wish you told me that before. Could you maybe make a short video of you opening www.Photopea.com and what you do next?

**Comment by Tornadof123** [comment]
Here is a video of me going through the steps and the bug happening: https://imgur.com/a/9Ob13ou

**Comment by photopea** [comment]
I am very sorry for this bug :( it is fixed now!
