### ISSUE TITLE
Error with delete on Curvature Pen

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4027]
When "Curvature Pen" tool is selected and I press DELETE or BACKSPACE on keyboard to delete layer following error appears in console.

pp.js:6164 Uncaught TypeError: Cannot read properties of undefined (reading 'add')
    at I.z0.I.hE.H5 (pp.js:6164)
    at I.z0.zm (pp.js:6225)
    at fL.zm (pp.js:12993)
    at fL.lI (pp.js:12953)

**Comment by photopea** [comment]
fixed, thanks for reporting :)
