### ISSUE TITLE
Some old PSDs won't open correctly

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#403]
I have some old PSDs (from 2002 version of Photoshop).
Some of them work correctly but most won't open in Photopea or open only with errors.
I will send you files to support@photopea.com

Feathers.psd
Footprints.psd
Frosted Glass.psd
Lines.psd
Mountains 1.psd
Puzzle.psd
Rust Flakes.psd
Snake Skin.psd
Strands 1.psd
Stucco 2.psd
Piccolo site.psd
Postcard.psd
Tomato.psd
Blender.psd
Bomb.psd
Fruit Animation.psd
Hand.psd
Harvest.psd
Morning Glass.psd
write-on.psd
Banner.psd
Eagle.psd
Flower.psd
Bubbles.psd
Carpet.psd
Coarse Weave.psd
Crystals.psd
Denim.psd
Purples.psd
Rough.psd
Slate.psd
Stone.psd
Streaks.psd
Stucco.psd
Water.psd
Wood.psd
Woven.psd
Zebra.psd
12 sided (25%).psd
Cees (10%).psd
Crumbles.psd
Fragment layers.psd
Honeycomb (10%).psd
Mezzo effect.psd
Pentagons (10%).psd
Random strokes(25%).psd
Rectangular tiles (10%).psd
Schnable Effect.psd
Streaks pattern.psd
Twirl pattern.psd

**Comment by photopea** [comment]
Hi, it all should be fixed now. Some files had problems for the same reason (so fixing one problem solved many files). Thanks!
