### ISSUE TITLE
Dragging layer on Android

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4031]
There is a little problem. 
When dragging layer, part of the layer below is moving together visually. 
![Screenshot_20211123_111327](https://user-images.githubusercontent.com/79258245/142967026-eed5814d-ab69-4c68-94de-a66682305e0b.jpg)

**Comment by photopea** [comment]
This happens on Chrome on Windows, too. I think it is a bug in Chrome. It does not happen in Firefox. You can report it to Chrome developers, if you want.
