### ISSUE TITLE
Weird Glitches of Photopea

### ISSUE THREAD

**Issue by Jykie** [photopea/photopea#4034]
Since yesterday, some of the features on photopea have been acting up whenever i tried to edit. Here are the following glitches that has occurred so far:

- Everytime I sample a new piece of image with the clone stamp, the previous sample i laid down instantly disappear.
- Whenever I tried to mask out a piece of image, the image would disappear.
- This morning, I tried to use puppet warp and everytime I opened the feature, the image i tried to use it on disappeared.
- I also, painted on a new layer then closed the visability to check the underlying image and when I open the visability again, the parts that were painted disappeared.

This has never happened before and I'm not sure what's going on. I restarted my laptop yeasterday to see if that could help but it has not.

**Comment by photopea** [comment]
I can not reproduce any of this :( Could you describe how to reproduce it? Exact steps? And make sure, that these steps always cause a bug on your end.

**Comment by jaelkwakkel** [comment]
I have the same problem. To reproduce:
1. Create a new document.
2. Create a new layer(Layer1)
3. Draw on this layer(Layer1)
4. Create a new layer(Layer2)
5. Draw on this layer(Layer2)
6. Press the eye-icon on the first layer(Layer1)
7. The second layer acts weird(shrinks or something)(Layer2)

**Comment by Jykie** [comment]
For the masking, I created a shape with the pan tool and filled it with a solid color. I then link another image on top. Then I copy the image again, and use the mask to mask away some parts. Then when I repeat the step again, that's when it gets weird. 
For the clone stamp, I link a new layer, set the clone stamp to sample current layer and below. I sample an image, lay it down. Then when I go to clone another part of the image, the previous sample put down disappear.
Puppet warp, I select the image of my model I want to warp and when I click on the image, most of it disappears.
Hope this helps.

**Comment by photopea** [comment]
Lets work on it one by one. I tried your 8 steps, but nothing is weird :(

Could you maybe record a short video of how you do it?

**Comment by jaelkwakkel** [comment]
https://user-images.githubusercontent.com/62651445/143064272-4475db4d-b6e2-4379-a8cf-9d6df45d3657.mp4

**Comment by photopea** [comment]
That is so weird, I still can not make it happen on Windows or on Mac.

What is your OS and your browser, including the version? Can you make it happen at www.Photopea.com opened in the Incognito?

**Comment by photopea** [comment]
Oh, I see it now. It happens only with the large brush size (175 pixels in your case), I really missed that.

**Comment by jaelkwakkel** [comment]
> Oh, I see it now. It happens only with the large brush size (175 pixels in your case), I really missed that.

Oh, sorry I did not test this with a smaller brush.

**Comment by photopea** [comment]
Ok it should be fixed now :) I am very sorry for that. I really did not expect that such a serious bug can happen.

**Comment by photopea** [comment]
Your browser could be caching the old Photopea for an hour, so hard-reload it, or open it in Incognito until then.

**Comment by Jykie** [comment]
Ok I will try this and let you know how it worked later on
