### ISSUE TITLE
Vector Stroke - When changing stroke on a shape, the fill color get transparent

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4035]
![image](https://user-images.githubusercontent.com/11801254/143079019-bcf70131-858d-467e-a77a-c6ad740046c1.png)

Select a path.

Change the fill color.

Now select a stroke color.

It should change the fill color to transparent

**Comment by photopea** [comment]
I am afraid I can not reproduce it, and I do not understand what the problem is. Changing Stroke has no effect on Fill, and vice versa.

**Comment by MichalSZZ** [comment]
Yes, there is definitely something wrong with switching colors in that place. I had this issue a few times.

**Comment by photopea** [comment]
But I can not reproduce it using your steps, can you open www.Photopea.com and reproduce it?

**Comment by photopea** [comment]
I think I can reproduce something.

**Comment by avagp** [comment]
I am also trying to get the correct repro.

I can prepro it some times, and sometimes don't

**Comment by avagp** [comment]
I got it.

1. Create a shape and set the fill and stroke to transparent
2. Select fill color, then set fill transparent, then set fill color again.
3. Set stroke color

It should change fill

**Comment by photopea** [comment]
I am very sorry, it is fixed now.

**Comment by avagp** [comment]
[Screen recording 2021-11-23 16.33.18.zip](https://github.com/photopea/photopea/files/7590587/Screen.recording.2021-11-23.16.33.18.zip)


Here is a video (a little one)

**Comment by avagp** [comment]
Thanks Ivan!

Don't apologize! It is part of the development!

We are here to help you iron out things :)
