### ISSUE TITLE
Pattern .pat files disspaears

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4036]
I don't know the correct behaviour of .pat files, but i have a file with one, and it shows, but i cannot select it.

https://www.photopea.com/#i24JcEXO0

Look for the layer 'Desgaste'

**Comment by photopea** [comment]
Your layer is a Fill layer (it is not a vector shape layer). Change the fill of a fill layer in the Properties window (double-click the layer thumbnail).

**Comment by avagp** [comment]
the pattern is not there
![image](https://user-images.githubusercontent.com/11801254/143136782-3446c40a-d591-46df-b090-90d9d0cf3b6d.png)

I uploaded couple days ago, but is not there anymore

**Comment by avagp** [comment]
Also, when i create and save .pat files they are not stored on local storage?
![image](https://user-images.githubusercontent.com/11801254/143137097-5b112a95-b410-4031-827c-e70edf1c47d9.png)

**Comment by photopea** [comment]
This is a pattern inside a PSD file. It is not available in the pattern gallery. If you open 5 PSD files, you can not apply a pattern from one file to another file. A pattern gallery can not change depending on how many PSD files you open.

PAT files are saved to your computer. You need to load them into Photopea, so that they are saved in the Local Storage.

**Comment by avagp** [comment]
And if it patter files are inside PSD.

Why i cannot see it in the PSD that have it?

**Comment by photopea** [comment]
PSD contains patterns, not pattern files. Just like a layer style from one PSD can not be used in another, unless you add it to a gallery. It works the same in Photoshop.

**Comment by photopea** [comment]
Use the "Define New" command
![image](https://user-images.githubusercontent.com/15955558/143141237-b92eacce-b922-4da3-99c5-36270a0c8be0.png)
.

**Comment by avagp** [comment]
Ok.... that did the trick.

But why it disappeared on the first place?

Because i have it was there when i created it
