### ISSUE TITLE
PDF Export - Shape layer not blending properly

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4037]
![image](https://user-images.githubusercontent.com/11801254/143137582-f7accb33-df71-4134-a39d-1935817b1e2d.png)

In this picture i have a shape layer with a pattern (white with black dots)

And i have the layer set to linear burn.

When i export to PDF it does not look that the layer kept the blending option.

https://www.photopea.com/#i-mUVHI6G

**Comment by photopea** [comment]
Sorry, but PDF supports only these blend modes: https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdf_reference_archive/blend_modes.pdf

Merge your layers, or try to rasterize all.

**Comment by avagp** [comment]
Oh!

Thanks for the info.

Darken made the work
