### ISSUE TITLE
freezes and then work fully lost

### ISSUE THREAD

**Issue by estrellangelica** [photopea/photopea#4040]
It happens since a few weeks while it was working perfectly before on my Mac. If it's because of the excessive adds, consider stoping because this is a major issue and really brings a highly negative experience. Thanks

**Comment by photopea** [comment]
Does it happen in a browser, where all browser extensions are disabled? I think the ads which you see could be inserted by some of your browser extensions.

**Comment by photopea** [comment]
I have to close it, because the person did not respond.
