### ISSUE TITLE
Angle Tool - Let us move 45

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4041]
On Photoshop, this tool shows a compass con the middle.

And also, while pressing shift, you can move in proportions, like 45, 90, etc

Just like transform does.

When using this tool i cannot get the exact angle i want by only using the mouse (i know it can set it on the top left corner)

**Comment by avagp** [comment]
BTW, when using the text tool upside down (angle 180) i cannot create a text box dragging down-left, because it is up-side down, the text box is done by dragging up-right.

Also the text is not created upside down, so it is uncomfortable.

**Comment by avagp** [comment]
👀

**Comment by avagp** [comment]
Any update for this?

**Comment by avagp** [comment]
because i design a lot of boxes, many times i have to turn the canvas around
![image](https://user-images.githubusercontent.com/11801254/151041752-4a51056c-b7a1-4419-96bd-18e9b96c80cc.png)

**Comment by photopea** [comment]
I can not find any info about the "Angle Tool" in Adobe Photoshop :( Do you have any links describing it?

How should the text tool work with the rotated canvas? Should it create a text layer that is "straight" to the current view?

**Comment by avagp** [comment]
Rotate tool, sorry :)

Look at this:
https://www.youtube.com/watch?v=ADCxjDQLCro

And about the text: Yes, it should be 'straight' to the current angle.

At least, the actual way is pretty difficult to work with.

**Comment by photopea** [comment]
I have fixed it. You can see the compasses now. Holding Shift will rotate in multiples of 45 degrees.

The new text layer is rotated according to the document rotation.

**Comment by avagp** [comment]
I cannot cycle through hand and rotate tool by holding Shift+H

:/

**Comment by photopea** [comment]
What is Shift+H? You have never mentioned it :(

**Comment by avagp** [comment]
Every tool on Photopea can be cycled with Shift + [the_letter_of_the_tool]

For example: Shift+V cycles between Move and Artboard
Shift+I cycles between Eyedropper and Ruler
And so on...

But the Hand tool does not change when i hit Shift+H

**Comment by photopea** [comment]
Oh, that is an exception (someone told us to do it this way because of Photoshop). They use different keys, even when they are in the same group.

Press H for the Hand tool, R for the Rotate View tool.
