### ISSUE TITLE
in the beginning of my use of photopea it was all right, now it won't open psd templates in working area from desktop application meantime you could open these templates in browser..

### ISSUE THREAD

**Issue by sardorpomidor** [photopea/photopea#4042]

**Comment by photopea** [comment]
We do not have any desktop application. If you pressed "More - Install Photopea", it just creates creates an icon on your desktop, but Photopea still runs in a web browser (if you uninstall your browser, it will stop working).

You can not open any PSD file from your computer? Try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it, because the person stopped responding.
