### ISSUE TITLE
moving tool not working 

### ISSUE THREAD

**Issue by Mochimoooon** [photopea/photopea#4043]
Hi, I'm just here to report a bug you see whenever I used the ctrl alt v together I get a clipboard error. But when I used ctrl fn v together I still get a clipboard error so I was wondering if I'm doing anything wrong???

**Comment by photopea** [comment]
What exactly do you want to press, and what do you want to happen? how are your shortcuts related to the Move tool?

**Comment by Mochimoooon** [comment]
I'm sorry nevermind I accidentally click on auto-select and that's why I was having a problem sorry for wasting your time

**Comment by photopea** [comment]
no problem :)
