### ISSUE TITLE
moving a layer over another display the right click menu

### ISSUE THREAD

**Issue by emmpcoder** [photopea/photopea#4046]
Issue: when moving a layer in the layer panel over another, the contextual menu shows see:

![bug_layer_move_to_put_one_over_another_trigger_popup_menu](https://user-images.githubusercontent.com/95192725/143789939-5a77e6c3-7a73-4c7d-b407-d2c55855a34e.png)

Browsers: 
reproduced with:
Chrome Version 96.0.4664.55 (Official Build) (x86_64)
Safari Version 15.0 (15612.1.29.41.4, 15612)
Firefox 94.0.2 (64-bit)

OS: Mac Os Catalina 10.15.7

Troubleshooting done: tested with a different mouse, same issue

Thanks to fix this issue quickly. Photopea is a fantastic tool, used by thousands, thanks for your time and effort.

**Comment by photopea** [comment]
If you click and hold a layer thumbnail for a while, the context menu appears. We did it for people who have a touchscreen and no mouse, so that they have a chance to open a context menu.

Drag-and-drop layers by "catching" them by other parts, not a thumbnail.

**Comment by emmpcoder** [comment]
That do you mean by 'other parts'? 
I work this way with photoshop since 2004 at least. 
Could you make this a setting so certain users device and ways don't impact others?

**Comment by photopea** [comment]
ok, I have removed this feature.

**Comment by nothingshiru** [comment]
> ok, I have removed this feature.

Can you make the trigger condition like this? 

**Tap on thumbnail and hold 1.5s with finger without moving**

You can't just remove it. Phone/Tablet users need this feature.

**Comment by Abcd-Arnab-2005-github** [comment]
Yes, it is the only way to access the menu. 
Please bring it back, we don't think this will affect that much

Or, maybe make it draggable only when you click and hold on the thumbnail



Or, maybe you can add a little icon on the end of the layer, which will make it draggable
Something like this:
![Screenshot_20211201-202811](https://user-images.githubusercontent.com/89312965/144257763-ed61d231-2266-48a8-88ee-1284e2d1fc1f.png)
