### ISSUE TITLE
Problem with Anchor in Canvas Size dialog

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4047]
When dragged anchor point with finger, the anchor point will be moved after clicking anywhere.

For example, when I drag the anchor point to the left then click on the blank area on the right, the anchor point is set to the right.
![example](https://user-images.githubusercontent.com/79258245/143864448-f31fd7e6-2149-4e93-b15a-a8a3e3ae7177.png)

**Comment by photopea** [comment]
fixed, thanks for reporting :)
