### ISSUE TITLE
ITS erasing what im drawing as im adding the paint

### ISSUE THREAD

**Issue by Cosmic-g4mer-YT** [photopea/photopea#4048]

**Comment by Cosmic-g4mer-YT** [comment]
the tool doesnt work it inverted it it eraaed t 4 me
________________________________

**Comment by Cosmic-g4mer-YT** [comment]
the Paint tool was erasing the artwork
________________________________

**Comment by photopea** [comment]
You need to tell me what I should do on my computer, to see the bug happen. I can not fix a bug, which I do not see myself :(

**Comment by photopea** [comment]
There are no robots here. Sorry, I will close it now.
