### ISSUE TITLE
Idea Make It So You Can Use The Freepen And Click A Drawn Path To Extend It To Make Sharp Corners

### ISSUE THREAD

**Issue by Kristopian** [photopea/photopea#4049]
I can't seem to find a way to fuse paths but I might be blind, but I did notice that I can't really make a shape/path with sharp corners under 45 degrees and a possible fix would be to make it so you can extend a path with freepen by clicking and dragging the end, it might also help to be able to have a bucket tool that fills in paths and can fuse them into a shape.

**Comment by Kristopian** [comment]
Sorry If I Seem Demanding Or It Just Seems I Complain A Lot But I Really Do Love Photopea, So I'm Sorry If I Seem A Little Much At Times. I Know How Hard Development Is And The Amount Of Time It Can Take.
-Kristopian

**Comment by photopea** [comment]
Hi, could you rewrite your text, so that capital letters are only at the beginning of a sentence? I am not used to such text, it is very hard to read :(

**Comment by photopea** [comment]
I have to close it because the person stopped responding :(
