### ISSUE TITLE
Patch Tool sometimes freezes Photopea

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#405]
Patch Tool sometimes freezes Photopea.
I just sent you to support@photopea.com example file so you can reproduce issue like this:
1. open PatchToolProblem.psd
2. zoom in little bit
3. go to "Layer 1" layer and with Select - Color Range (fuzziness:40) make selection
4. go to "Background" layer
5. open Info window (so you can see x y coordinates)
6. select Patch Tool and apply with:
   start position pixel x=0 y=0
   end position pixel x=-13 y=19
->
photopea and browser not responding...

**Comment by photopea** [comment]
It was fixed, thank you! The problem was in the division by zero.
