### ISSUE TITLE
Some issues for Touchscreen devices in Photopea (Android)

### ISSUE THREAD

**Issue by Abcd-Arnab-2005-github** [photopea/photopea#4051]
Some issues for touch devices that I find (an Android Tablet):

1. On _Chrome or duckduckgo or samsung browser_, after sometime after importing images and trying to edit, **The Main Area stops responding to touch input**. Other regions still work fine.
2. But on _Mozilla Firefox_, there is no issue with the main area, instead, I **can't drag or drop any element on Firefox**, I can't reorder the layers for example
3. **The Refine Edge tool doesn't work properly**, After drawing some lines, the display area stops responding and the options on the top bar also stops working.

I tried to include screenshots, but they don't show anything related to the issue.

**Do note that my Tablet doesn't have high spec, it has a snapdragon 413,  but I don't think that should be a problem because some of the issues are working in one browser and not working on another**
Also, I know that some of the issues are probably opened already, but I can't find them, Thank you.

**Comment by photopea** [comment]
The problem 2. is a bug in Firefox. Only Firefox can fix it. I could ask them to fix it, but they never fixed anything. I think Firefox will stop existing soon anyway.

I think the problem 1 and 3 are related, but I can not reproduce them :( Could you describe how to reproduce it? @nothingshiru maybe you can reproduce it on an Android device?

**Comment by Abcd-Arnab-2005-github** [comment]
> The problem 2. is a bug in Firefox. Only Firefox can fix it. I could ask them to fix it, but they never fixed anything. I think Firefox will stop existing soon anyway.
> 
> I think the problem 1 and 3 are related, but I can not reproduce them :( Could you describe how to reproduce it? @nothingshiru maybe you can reproduce it on an Android device?

Oh Thanks a lot!
Somehow, the 1st issue doesn't occur anymore. It occurs very rarely _when I try to crop a smart object._
The 3rd issue is most probably due to my weak processor and my fault. But for some reason, it doesn't occur that much now.
The issue was happening because _**when I tried to zoom in on the image, it drew a thick line and everything froze.**_

https://user-images.githubusercontent.com/89312965/144431652-065d8024-7566-40af-8172-867f60310352.mp4

I figured out that we only have to **zoom on the "Right" image.**
Anyways, I think this issue should be closed now, as these are probably the limitations of using a weak processor and touch input.

**Comment by nothingshiru** [comment]
Device performance might be the point of problem 3. 

If "Grey" area exist, drawing with "White", "Grey", "Black" would be laggy. The website would be stuck for a while.

@Abcd-Arnab-2005-github Try to set the value of border to 0 after open Define Edge window, then do the same thing. Does the problem still happen?

**Comment by nothingshiru** [comment]
Regarding problem 1. 
There are a few ways to make the main area stop responding on Chrome for Android. For example, using Quick Select. 
But not only touch input will be affected, the mouse will also be affected. I'm not sure if the problem you saw is same or not.

**Comment by Abcd-Arnab-2005-github** [comment]
> Device performance might be the point of problem 3.
> 
> If "Grey" area exist, drawing with "White", "Grey", "Black" would be laggy. The website would be stuck for a while.
> 
> @Abcd-Arnab-2005-github Try to set the value of border to 0 after open Define Edge window, then do the same thing. Does the problem still happen?

@nothingshiru 
Yes it sometimes does happen when trying to use it on high resolution images. This is I guess, surely due to the device's performance.

**Comment by Abcd-Arnab-2005-github** [comment]
> Regarding problem 1. There are a few ways to make the main area stop responding on Chrome for Android. For example, using Quick Select. But not only touch input will be affected, the mouse will also be affected. I'm not sure if the problem you saw is same or not.

I don't have an adapter to use the mouse, but, Yes it lags and sometimes freezes in Chrome or similar browsers.
However, it doesn't freeze in Firefox but we can't use Firefox because we can't drag layers.

This has probably something to do with the device memory. As I see this happen after the history panel is full with edits

**Comment by photopea** [comment]
@nothingshiru I can not make the main area stop responding with the Quick Select. Yes, Photopea is frozen during "image analysis", but then, eveyrthing works again. Do you have steps how to reproduce it?

**Comment by nothingshiru** [comment]
According to his descriptions, the problem
1. Not happen on Firefox for Android.
2. Only happen in main area, not menu bar and tool bar.

It is a problem I had reported. 

Steps to reproduce

1. With Quick Select selected, tap on image.
2. Tap on image again and slide, you'll see it is zooming.
3. Release then tap and slide image again, you'll see there's no responding. Also the panels doesn't work properly anymore.

**Comment by Abcd-Arnab-2005-github** [comment]
Update:      Now, dragging of layers don't work in any of the browsers except Google Chrome. In my case.

**Comment by Abcd-Arnab-2005-github** [comment]
The issue with Quick selection, sometimes happen, sometimes not.  It is most probably due to the _Weak hardware__

**Comment by photopea** [comment]
I have fixed the bug with Qick Select on touchscreens.

Is there any other problem?

**Comment by nothingshiru** [comment]
Try to move/zoom canvas with 2 fingers when Quick Select tool is selected. The canvas is "tapped".

**Comment by photopea** [comment]
I did it and it seems to work fine. Note, that if you have a large resolution, you need to wait for the "Image Analysis" to finish.

**Comment by nothingshiru** [comment]
Selection was changed and you can find the new steps of Quick Selection on history panel.

**Comment by photopea** [comment]
I would prefer to focus at bigger issues, rather than such details.
