### ISSUE TITLE
Why is some elements in red?

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4052]
![image](https://user-images.githubusercontent.com/11801254/143985397-a41a36cd-8780-4160-8de0-3c2b71fb18c8.png)

Selected layers and also the canvas is red.

Why is that?

Here is the PSD: \https://www.photopea.com/#iH06tr8_2

**Comment by MichalSZZ** [comment]
You are in Quick mask mode :)
Turn off this under foreground and background color switcher.

wt., 30 lis 2021 o 05:24 Radical Dreamer ***@***.***>
napisał(a):

**Comment by photopea** [comment]
That is a quick mask mode, see here: https://www.photopea.com/learn/selections

**Comment by avagp** [comment]
![image](https://user-images.githubusercontent.com/11801254/144081937-973adf6a-3294-4a71-8c94-1165481e7403.png)


Sorry...
