### ISSUE TITLE
Subtract doesn't work when there's only one rectangle path in the path layer

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4053]
To reproduce

1. Create a document and unlock the Background layer.
2. Add vector mask(Reveal All).
3. Create a rectangle path with Subtract mode. 

Mask doesn't work. 
But when I created a new path or drag anyone of anchor points of the rectangle path, the mask works.

**Comment by photopea** [comment]
I am very sorry, it is fixed now.
