### ISSUE TITLE
work lost

### ISSUE THREAD

**Issue by Tayen1** [photopea/photopea#4054]
i went on another tab, when i came back my work was gone 
![image](https://user-images.githubusercontent.com/95316592/144128804-f3cbbdfe-49ca-4ffe-b5f8-97fc7ccc3cd3.png)

**Comment by photopea** [comment]
Your computer probably does not have enough GPU memory for such a large document. What was the width / height / DPI of your document? You probably need a better computer to be able to work with such large dimensions or DPI.

BTW. even in this state, you can press File - Save as PSD, and save your work.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
