### ISSUE TITLE
Request: Replace the icons of Path Select and Direct Select with each other

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4057]
It make more sense that Path Select has a outline icon. And that's how Photoshop do.

**Comment by photopea** [comment]
I made it work the same way as Photoshop. The "Direct Select" icon is white. The "Path Select" icon is white with black in the middle. But there is a problem, the white icon is completely invisible, if you set the Theme to Light Gray. Do you think we should fix it and how?

**Comment by nothingshiru** [comment]
They don't need to have a specific color. Just let Path Select be a outlined icon, and Direct Select be a filled icon.

**Comment by photopea** [comment]
I am afraid that will not work. Most of people want the Path Select to be black inside, while the Direct Select is white inside. See https://github.com/photopea/photopea/issues/2735 . So these two icons should not change when you change a theme.

**Comment by nothingshiru** [comment]
I think the point of that issue is about the color of floating bubble of tools. It wasn't changed when theme was changed, so icons would look different and people were confused.

I had requested you to make the bubble color always same as theme color. You had fixed it.

@avagp How do you think?

**Comment by photopea** [comment]
Here you can see, that the "Path select" was always black in Photoshop, and "Direct Select" was always white. I think that is what users expect. But I wanted to avoid making special icons for each color theme.

You say "let Path select be an outlined icon", but it was usually not outlined in Adobe Photoshop.

![photoshop-direct-selection-tool](https://user-images.githubusercontent.com/15955558/144599718-a8bdd332-c42a-4488-9a2b-87c8ad87b3ab.gif)

**Comment by nothingshiru** [comment]
Sorry, I was wrong. 
The two icons in Photoshop are different in color, not in shape. I thought difference is shape(filled, outlined) but they are actually not.

**Comment by avagp** [comment]
Ok, my problem was that the menu bubble does not change with the theme. It was solved.

Of course i had the similar issue than @nothingshiru because i came from photoshop and i was used to certain colors for certain tool (direct select and path select). But after the adjustment in the theme i just got used to the reversed colors (i use light theme).

But i personally think you should revert the change @photopea, in light theme here are the tools:
Path:
![image](https://user-images.githubusercontent.com/11801254/144625023-639800f5-075b-4a92-a7c0-e343fdfd4979.png)
Direct:
![image](https://user-images.githubusercontent.com/11801254/144625032-93bb58d1-81f8-455c-977e-08b6c3643aef.png)

Are unsuable

**Comment by avagp** [comment]
I believe the best should be changing the icons without a particullar color, just like Ivan said:

Direct: Should have reverse outline
Path: should have Reverse fill

In that way, on a dark theme:
Direct should look black with white outline
And Path should look like white with black outline.

In a light theme:
Direct should look white with black outline
And Path should look like black with white outline.

**Comment by avagp** [comment]
This is my little contribution towards differentiate the icons.

Taking in account that they are already different from photoshop, this could also help:

![New Project (1)](https://user-images.githubusercontent.com/11801254/144628778-68cfe7c5-1771-4378-a72c-ea8cd3f5cd05.png)

Which makes sense of what each tool does.

**Comment by photopea** [comment]
I decided to do what @nothingshiru asked in the first place. I just swapped the icons.

But now, in a light theme, Path select is white inside (which is not as in Photoshop). But I guess these people are in a minority and they will get used to it.

**Comment by avagp** [comment]
When does it change?

**Comment by photopea** [comment]
It is changed now.

**Comment by avagp** [comment]
Perfect!

Still the icon shape change could be a good idea 😁

**Comment by nothingshiru** [comment]
While you were talking, I was trying to create icons that preserve similar color in different theme...
![Screenshot_20211203_235755_com microsoft emmx](https://user-images.githubusercontent.com/79258245/144635760-0fd48863-4d1b-4d46-8ac6-829f63533be3.gif)

**Comment by avagp** [comment]
i totally get why Ivan tries to keep it simple. And I appreciate it.

I can personally say i am use to the reversed colors of those tools, knowing that i have a light theme. I easily got used to it.

As it is now is fine :)  But still i believe the shapes could be different for better recognition.

Just like hand and rotate tool does
![image](https://user-images.githubusercontent.com/11801254/144639373-66eab711-9aef-43be-a8f8-40fb5c591d99.png)
![image](https://user-images.githubusercontent.com/11801254/144639377-33f037ba-894d-47a7-98af-d30c0a790a96.png)
