### ISSUE TITLE
Values of Exposure adjustment are different than Photoshop in operating

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4060]
**The values of Exposure and Gamma correction are different in operating.**

### Differences

**1. The smallest unit in textboxes.**
It is 0.01 In Photoshop, but 0.001 in Photopea.

**2. The smallest unit in sliders.**
[Exposure] It is 0.01 in Photoshop, but 0.2 in Photopea.
[Gamma correction] It is 0.01 in Photoshop, but 0.035 in Photopea.

**3. The positions of the values in the slider**
They are linear in Photopea, but not in Photoshop.
They should be like this.
![ex](https://user-images.githubusercontent.com/79258245/144164524-5cb9a082-3bfc-4cda-83ce-9610620dece7.png)

**Comment by photopea** [comment]
I have added "logarithmic" sliders to the Exposure and the Gamma correction. However, we do not have a slider, which increases to the left side. I think it is not important.
