### ISSUE TITLE
Stroke gaps work differently than Photoshop

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4061]
Differences.
![Strokes](https://user-images.githubusercontent.com/79258245/144351911-a25a4d63-3c36-400d-8208-568f9b5e09c4.gif)

**Comment by nothingshiru** [comment]
I didn't test the third gaps. I'm not sure if it works properly with Inside/Outside position strokes. 
![Screenshot_20211201_112505](https://user-images.githubusercontent.com/79258245/144166597-6d39b585-f279-4735-9bfc-a9e5901384bd.jpg)

**Comment by photopea** [comment]
Hi, I am aware of this problem, but I don't know how to fix it :( we render vector graphics through a context2d of a HTML Canvas element, and it can not do that.

Stroke positions (outside-center-inside) do not exist in vector graphics (e.g. in PDF or SVG files). I think you should always make strokes aligned to the center, if you want to create vector content.
