### ISSUE TITLE
Delete/Backspace key cannot cut off the path

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4062]
In Photoshop, the delete anchor point option in context menu and pressing Delete/Backspace key are working differently. 
They are like this
![Screenshot_20211201_113402_com microsoft emmx](https://user-images.githubusercontent.com/79258245/144168711-4b577583-3ac0-4351-8e06-30b623d973f9.png)

But in Photopea, they work in the same way.

**Comment by photopea** [comment]
Is the method on the right side actually useful in practice? It turns a closed path into an open path. If you delete a point at the bottom left, it will create two independent points.

**Comment by nothingshiru** [comment]
It is useful. 
For example I want to create a semicircle, In Photoshop I can create a circle with ellipse tool then delete one of the anchor points to get it. Now I can't do this in Photopea.

**Comment by photopea** [comment]
Hi, I have done it, you can test it here: https://www.photopea.com/#i5Ugw0OWk

**Comment by nothingshiru** [comment]
Nice! Thank you very much.
