### ISSUE TITLE
Snap unexpectedly

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4064]
Even if you hold Shift key and move the layer vertically, the layer will still snap to the left or right. 

To reproduce

1. Create a document with a resolution of 1280*720 px.
2. Check View > Snap, and View > Snap To > Document bounds.
3. Create a shape and set the position to X: 6, Y: 0.
4. Press Ctrl + 1 to set the zoom level to 100%.
5. Hold Shift key and move the shape layer vertically.

After moved, the position X should still be 6, but it becomes 0.

**Comment by photopea** [comment]
fixed, thanks for reporting :)

**Comment by nothingshiru** [comment]
Do the same steps but replace step 5 with "Click on the layer". It is still snapped to the edge unexpectedly :(

Clicking on a layer doesn't always mean people are going to move the layer. So "Snap" should be applied only when the layer is moved at least 1px.

**Comment by photopea** [comment]
I can not reproduce it with "click on the layer" :( Are you doing it on a touchscreen? Maybe it is not precise, and you move the layer a bit.

**Comment by nothingshiru** [comment]
You are right. 
I tested it again and found that the layer was moved imperceptiblely when I tapped it with finger.
