### ISSUE TITLE
Can't open the layer menu

### ISSUE THREAD

**Issue by Abcd-Arnab-2005-github** [photopea/photopea#4065]
This happens in an Android Tablet or a mobile (sometimes)
This issue was not there a few days ago.
(Google Chrome)

[

https://user-images.githubusercontent.com/89312965/144228316-f1d7a2b8-decd-4653-b0fd-ae4bfbc7b147.mp4

So, when I try to tap and hold, the layer can only be reordered (in Chrome), Mozilla Firefox on the other hand does completely opposite.
(Mozilla Firefox)

https://user-images.githubusercontent.com/89312965/144228778-c9cc6486-bfa7-4132-8498-0cf64690b65f.mp4

On mobile phones on the other hand, It is possible to open the layer menu, But, We have to tap and hold for a very specific amount of time.

(Mobile Chrome)

https://user-images.githubusercontent.com/89312965/144229802-013c78f6-68f8-4fe0-ae6a-23761a1fd63d.mp4

**Comment by photopea** [comment]
I think it is just a difference between Chrome and Firefox. In Chrome, long-tap will start dragging an obect, while in Firefox, long-tap acts as a right-click.

Either Chrome, or Firefox would have to fix it, so that it works the same in both browsers.

**Comment by Abcd-Arnab-2005-github** [comment]
> I think it is just a difference between Chrome and Firefox. In Chrome, long-tap will start dragging an obect, while in Firefox, long-tap acts as a right-click.
> 
> Either Chrome, or Firefox would have to fix it, so that it works the same in both browsers.

Okay, Thanks!
but a few days ago, long tapping and holding on the layer (without moving fingers)(in chrome) was opening the layer menu. 
Just recently, I found that this issue.

Usually, this would have happened:
![1638369623587](https://user-images.githubusercontent.com/89312965/144254615-0885cebc-0213-4a6f-8811-75ec2e003a88.jpg)

**Comment by photopea** [comment]
I know, but one of users complained about this feature: https://github.com/photopea/photopea/issues/4046

**Comment by Abcd-Arnab-2005-github** [comment]
I am not sure (obviously), but I think there is something to do with the touch sensitivity

Now, the tab that I use is very sensitive to touch input,
like, even if I put 16 pages of paper on the screen, it will still register my touch input perfectly.

But the phone is not that sensitive. 
 
I don't know. I will delete this comment if you think it makes this page a bit messy. Thanks!

**Comment by Abcd-Arnab-2005-github** [comment]
Thanks a lot!
I suggested a way on that issue, please bring back that feature because it was needy

I am sorry if I look selfish or mean. This software is very powerful. If it works nicely on a phone or a tablet, then it will be amazing!

**Comment by Abcd-Arnab-2005-github** [comment]
These were the ways that I suggested, (since that issue is closed now)


1) Maybe make it draggable only when you click and hold on
     the thumbnail



2) Or, maybe you can add a little icon on the end of the layer, 
     which will make it draggable

Something like this:
![Screenshot_20211201-202811](https://user-images.githubusercontent.com/89312965/144257763-ed61d231-2266-48a8-88ee-1284e2d1fc1f.png)



(I mean Photopea isn't meant to be copying photoshop, it can have it's own way of doing things if that doesn't ruin the user experience, It's a great app and we all appreciate all the hard work that you have put into this)

**Comment by Abcd-Arnab-2005-github** [comment]
> I know, but one of users complained about this feature: #4046

> ok, I have removed this feature.
>_Originally posted by @photopea in https://github.com/photopea/photopea/issues/4046#issuecomment-981674981_

Thanks for replying!
These are the ways that I suggest.

(Please consider adding the feature again. That was the only way of being able to use the layer menu in Mobile or Tablet devices.)


1) Maybe make it draggable only when you click and hold on
     the thumbnail



2) Or, maybe you can add a little icon on the end of the layer, 
     which will make it draggable

Something like this:
![Screenshot_20211201-202811](https://user-images.githubusercontent.com/89312965/144257763-ed61d231-2266-48a8-88ee-1284e2d1fc1f.png)



(It's a great app and we all appreciate all the hard work that you have put into it)

**Comment by Abcd-Arnab-2005-github** [comment]
> I know, but one of users complained about this feature: #4046

> ok, I have removed this feature.
>_Originally posted by @photopea in https://github.com/photopea/photopea/issues/4046#issuecomment-981674981_

Thanks for replying!
These are the ways that I suggest.

(Please consider adding the feature again. That was the only way of being able to use the layer menu in Mobile or Tablet devices.)


1) Maybe make it draggable only when you click and hold on
     the thumbnail



2) Or, maybe you can add a little icon on the end of the layer, 
     which will open up the menu

Something like this:
![Medibang Paint Layers](https://user-images.githubusercontent.com/89312965/144389669-863d2ddb-495a-4292-a49c-9e15fd987819.png)




(It's a great app and we all appreciate all the hard work that you have put into it)

**Comment by photopea** [comment]
I have added an option into the "hamburger menu". Note, that it enables a context menu only on thumbnails, you can still drag-and-drop layers by touching them elsewhere.

![image](https://user-images.githubusercontent.com/15955558/144399464-88b1cba5-54d6-4ba2-9a39-9ba89c47d86d.png)

**Comment by Abcd-Arnab-2005-github** [comment]
Thanks man!
That was really quick!

Love you!
