### ISSUE TITLE
SVG Parser Can't Parse SVGs with comment

### ISSUE THREAD

**Issue by joshauh46** [photopea/photopea#4066]
Hi,

The SVG parser doesn't seem to be working with SVGs that have comments after manually removing the comment I was able to import the SVG in PhotoPea.

To reproduce try importing this demo SVG
https://s3-symbol-logo.tradingview.com/tesla.svg

**Comment by photopea** [comment]
It is fixed now :)

Basically, Photopea completely ignores the name of your file. It uses the actual content (first X Bytes) of a file to deduce the format of a file. So you can have a PNG file, rename it to "music.mp3", and Photopea will still open it :)

Now, Photopea will accept files starting with "<!--" as SVG :)
