### ISSUE TITLE
Problem with the Outer Glow

### ISSUE THREAD

**Issue by raabemartinsdesigner** [photopea/photopea#4067]
Hi! I love Photopea, but a lot of times this error happened and it's very frustrating when I need to use the outer glow:
![Screenshot](https://user-images.githubusercontent.com/91345712/144638271-c84cf404-4165-4396-9f3a-cf5b744c393f.png)

See: in this screenshot, the Outer Glow is activated, but does not appear. But if I click the "eye" in the background layer, it appears:
![Screenshot (1)](https://user-images.githubusercontent.com/91345712/144638427-c103e235-cf5f-4c69-8fcf-3b1e0c8b9ea6.png)

Could somebody help me to solve it, or fix this bug please! Thank you already.

**Comment by raabemartinsdesigner** [comment]
layer style is like this
![Screenshot (2)](https://user-images.githubusercontent.com/91345712/144639133-0b439849-55c4-4212-a88c-5f01942c52ab.png)
if may help

**Comment by photopea** [comment]
I think that is a correct behaviour. What exactly do you want to happen instead?

**Comment by raabemartinsdesigner** [comment]
I just realized, I was wrong, sorry
It's working
Wasn't appearing because of the background color
Sorry for wasting your time but thank you for answering me!
