### ISSUE TITLE
Move Tool - Aligning layers with a locked layer

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4068]
If i have 2 layers: layer A unlocked and layer B Locked.

If Layer A is inside and smaller than layer B, i should be able to select them both and align layer A over B, but because B is locked A does not align.

But in this particular case B does not have to move.

It this intended?

**Comment by avagp** [comment]
👀

**Comment by photopea** [comment]
If you decide to move or re-align a set of layers, all selected layers need to be unlocked. Otherwise, nothing will be moved.
