### ISSUE TITLE
prespective is not working

### ISSUE THREAD

**Issue by naderbensalah** [photopea/photopea#4070]
the "prespective" function in free transform does not work it does the same thing as "scale"
i hope you fix asap

**Comment by photopea** [comment]
I pressed Edit - Transform - Perspective, and it seems to work right. What did you do?

**Comment by naderbensalah** [comment]
it only change the perspective when i change the numbers in the tool
bar but i doesn't work when i use the transform controls

**Comment by photopea** [comment]
what do you mean by "perspective function in free transform"? What exactly should I do to see the problem happen?

**Comment by photopea** [comment]
I have to close it, because the person stopped responding :(
