### ISSUE TITLE
Fractal Noise Plugin

### ISSUE THREAD

**Issue by yikuansun** [photopea/photopea#4071]
Hi,

Could you please add this fractal noise plugin that I made?
```
{
    "name"  : "Fractal Noise",
    "url"   : "https://yikuansun.github.io/photopea-fractalnoise",
    "width" : 1000,
    "height": 500,
    "icon"  : "https://upload.wikimedia.org/wikipedia/commons/b/bc/Value_noise_2D.png"
}
```
It's just a more customizable/advanced alternative to the clouds filter.

Thanks!

**Comment by photopea** [comment]
Ok I have added it :)

**Comment by hxim** [comment]
@yikuansun Hi, your plugin will stop working if you use it without any image opened because of your scripts to extract document width and height will cause error and return nothing i think.
`app.echoToOE(app.activeDocument.width.toString());`

**Comment by yikuansun** [comment]
@hxim I'm pretty sure the error is ignored because my code calls the command asynchronously. If I open the plugin without having a document open, it just makes the size 1280*720. Did you observe a different result?

**Comment by hxim** [comment]
> @hxim I'm pretty sure the error is ignored because my code calls the command asynchronously. If I open the plugin without having a document open, it just makes the size 1280*720. Did you observe a different result?

@yikuansun Yes, it open once but if you click "Add to document again" it will not work. See this screenshot (it is showing Unknown file format: "\u0000\u0000\u0000\u0000" message):
![obrazek](https://user-images.githubusercontent.com/6370548/144753993-b7ebca84-e1a4-4c11-9a6b-017050c59fa0.png)

**Comment by yikuansun** [comment]
> Yes, it open once but if you click "Add to document" again it will not work

@hxim I've fixed it.
