### ISSUE TITLE
Feature Request: Variable Stroke Width

### ISSUE THREAD

**Issue by ExplosiveKrypton** [photopea/photopea#4073]
Hey there! I've been using the pen tool on Photopea a lot more recently, but I've noticed that it's a bit difficult to give paths some emphasis or fluidity. This can be particularly troublesome when trying to taper paths, drawing objects or scenes with depth, etc. etc. Something akin to the "width" tool in Adobe Illustrator or the "pressure" tool in Paint Tool Sai would solve this, and generally be a pretty helpful gem to have in Photopea.

**Comment by photopea** [comment]
Hi, are you drawing with a stylus? You can set the Brush tool to make the size correspond to the pen pressure.

Or is it about vector graphics? I think Paint Tool Sai can not do vector graphics.

**Comment by nothingshiru** [comment]
Maybe he's taking about such a effects?

Stroke with different width on a path.
![screenshot_20211206_014408](https://user-images.githubusercontent.com/79258245/144757426-607676cd-44a0-4623-9480-d5114c420719.jpg)

**Comment by ExplosiveKrypton** [comment]
The image that Nothingshiru posted is pretty much exactly what I'm referring to. And no, I don't have a tablet/stylus, but I feel that the pen and variable width would fill in as a more specific/controlled alternative to pen pressure, and as an option for people who don't have a tablet/stylus.

**Comment by ExplosiveKrypton** [comment]
As for the Paint Tool Sai example, admittedly the "width" tool from Adobe Illustrator is closer to what I meant. The "pressure" tool in Paint Tool Sai allows you to control the width/"pressure strength" of curves on linework layers.

**Comment by MichalSZZ** [comment]
I think the biggest problem is compatibility with PSD format.

I love stroke in illustrator and its stroke styles. You can by one click change the look of illustration. You can add a fake pen pressure to the  path or some fancy effect looking like real brush. And all of that will be as a vector path.

**Comment by ExplosiveKrypton** [comment]
That's a good point. Maybe it'd be possible to convert into PSD using Photoshop's simulate pressure stroke path? I'm not 100% sure how that would work. But also, opening an Illustrator file with certain features like this usually doesn't get carried over into Photopea either; at least at the moment.

**Comment by MichalSZZ** [comment]
Here is the sample of the Illustartor's "Variable Width Profile" in action.
![obraz](https://user-images.githubusercontent.com/38118273/144818179-193d7efd-83c9-499f-843e-c6fbc71a08f8.png)
and here is the AI file to test:
[variable-width-profile.zip](https://github.com/photopea/photopea/files/7659467/variable-width-profile.zip)

BTW. It is so great that  Photopea can open such of AI file and transform that stroke into a shape outline (with some bad render in corners but that is not so important).

**Comment by photopea** [comment]
So you draw "the center of a curve" in Illustrator, and set the thickness of each part. But if you export it as an SVG, and import it back to Illustrator, can you still change the thickness? As far as I know, vector fromats (SVG and PDF) do not support anything like this.

**Comment by MichalSZZ** [comment]
It is as you said. After saving as a SVG, stroke is changed to outline. It looks like my stroke but it is a simple path with fill.

**Comment by photopea** [comment]
I am afraid I would have to give it up.

It is not clear, how should it be integrated into Photopea. We would probably need a new tool in a toolbar, with a unuque mechanism and the workflow. It is not clear, if vector stroke properties can be applied to it or not (dash pattern, joints, etc).

So it would be really hard, and I am afraid not that many people need it at the moment.

**Comment by MichalSZZ** [comment]
That is an amazing feature for vector illustrators. But I understand. Thank you for looking on that request. It was not mine but I love that idea (automatic stroke width presets and stroke width tool)

Please make a list (only for you) with features that are great but you could't add them becouse PSD limitation. Maybe it will change in the future (PSD structure or your thinking about compatibility with that format)
