### ISSUE TITLE
Feature Request: add TIFF and TGA file types in Export layers...

### ISSUE THREAD

**Issue by xan2622** [photopea/photopea#4074]
Could you please consider adding the TIFF and TGA file types in "Export layers..."
Those are wildly used in the photography, publishing and 3D industries. 
Thank you in advance.

<img src="https://user-images.githubusercontent.com/1732773/144739853-1efa8a13-df06-4aa8-aa27-ea62218b5a50.png" width="50%" height="50%" />

**Comment by photopea** [comment]
Ok, I have added them. But you should know, that the data, which Photopea stores in TGA or TIFF, can be stored in a PNG. You are only wasting space (PNG files are the smallest) and ruining the versatility of your files (only some programs can open TIFF and TGA).
