### ISSUE TITLE
Density of the mask from Photoshop doesn't work

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4076]
To reproduce the problem

1. Create document in Photoshop.
2. Create a Solid color layer. 
3. Set the density of the mask on the Solid color layer to for example 40%. 
4. Save the document as psd. 
5. Open the psd in Photopea.
6. Check the density of mask in properties panel. 

You will see that the value of density is correct, but it doesn't work on image actually.

Here is a psd that contains a solid color layer with mask of which the density is set to 40% (102 in Photopea). 
[Example.zip](https://github.com/photopea/photopea/files/7657674/Example.zip)

**Comment by photopea** [comment]
fixed, thanks for reporting :)
