### ISSUE TITLE
problems opening images then the image disappears when you open a layer

### ISSUE THREAD

**Issue by isthereanythingavaliable** [photopea/photopea#4077]
For some reason when I open an image on to photopea it takes a long time to load then when I add a new layer the image disappears and photopea freezes.

**Comment by photopea** [comment]
Could you try this and let us know if it helped? Also, do you use Photopea on a phone?

https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it, because the person stopped responding :(
