### ISSUE TITLE
Request: Display widths, heights and position in Properties panel

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4079]
Now only Live Shape has that. Please add that for all layers except fill layer and adjustments layer. It would be convenient.
![screenshot_20211206_154128](https://user-images.githubusercontent.com/79258245/144807245-4f0415c0-dd19-44f8-a73d-a58efcc54b67.jpg)

**Comment by photopea** [comment]
I think in Photoshop, it simply applies a Free Transform to the layer. You can enter the values by enabling the Free Transform. I am not a fan of having many ways to do one thing :/

**Comment by nothingshiru** [comment]
**It's convenience is very different from Free Transform in actual use.**

Let's say, we want to move a layer to a position precisely in pixels. 
There are 4 steps we have to do.
    1.Edit > Free Transform.
    2.Set the center point to top-left.
    3.Enter values.
    4.Check.

But if we have the input boxes in properties panel,  entering values is the only one step to do. 
When we have 5 layers to move, 10 layers to move or even more, this feature can save us much time.

**Comment by photopea** [comment]
Ok I will do it.

**Comment by photopea** [comment]
I have implemented it :)

**Comment by nothingshiru** [comment]
Great!

**Comment by nothingshiru** [comment]
In some situations, changing position of a shape that is not a live shape doesn't work.

Here's a way to reproduce.

1. Create a shape by Curvature Pen.
2. Try to change the values of position.

The position doesn't change. 
When you input a new value then press enter, the value changes back to the original value, though there's new step appeared in History panel.

**Comment by photopea** [comment]
I am sorry, it is fixed now.

**Comment by nothingshiru** [comment]
Little problem when you select Artboard.
![screenshot_20211216_184303](https://user-images.githubusercontent.com/79258245/146357705-98d78145-2147-4a0c-80f9-2281b78261bc.jpg)

**Comment by photopea** [comment]
fixed :)
