### ISSUE TITLE
Backspace removes a anchor point(s), but does not keep the path closed anymore?

### ISSUE THREAD

**Issue by LetTSunShine** [photopea/photopea#4080]
When you hit backspace on an anchor point in a path, it would delete that one anchor point in the path, but now it would open up the path. It used to be that the path would still be closed, even when you delete anchor point(s) when you press backspace on it.

**Comment by photopea** [comment]
Our users asked us to make it work this way, because it works this way in Adobe Photoshop.

To remove the anchor "the old way", right-click it and choose "Delete Anchor".
