### ISSUE TITLE
Where are my brushes?

### ISSUE THREAD

**Issue by BeastCrawler** [photopea/photopea#4082]
I watched a few different videos about how to make mist or fog in photopia, but I don't have half the brushes they have in the video. and it's not only that one video. I searched through 8 different videos and 2 different websites, and I only have half of the default brushes. like the ones I need are 7, or 50...

**Comment by photopea** [comment]
You can load new brushes into Photopea as ABR files. What is "7 or 50"? You can change the size of any brush.

**Comment by BeastCrawler** [comment]
Look at the brushes I have in the first screen shot and the the brushes you say I should have on your website!!

**Comment by photopea** [comment]
I can not see your screenshot. Did you send it as an email? To what address did you send that email?

**Comment by BeastCrawler** [comment]
![image1](https://user-images.githubusercontent.com/93610226/145096044-839c7a28-2dd2-446e-b29d-55b4ea91694d.jpeg)
![image0](https://user-images.githubusercontent.com/93610226/145096048-86de000f-4e66-424c-8750-08886b47d2ec.jpeg)

**Comment by BeastCrawler** [comment]
There, I was responding to the wrong email.

**Comment by BeastCrawler** [comment]
as you can see, the first screenshot shows the brushes I should have on YOUR website. the second is showing the brushes I have.

**Comment by photopea** [comment]
We deleted some redundant brushes, so that Photopea is loaded faster. You can create your own brushes, or download some brushes from the internet and import them into Photopea.

**Comment by BeastCrawler** [comment]
How can I make these brushes??

**Comment by photopea** [comment]
It is described in the manual: https://www.photopea.com/learn/brush-tools
