### ISSUE TITLE
stale photopea.json file

### ISSUE THREAD

**Issue by xilehence** [photopea/photopea#4083]
We have made a bilingual (English & Japanese) interface for Photopea (available through https://u-aizu.ac.jp/~mcohen/welcome/courses/AizuDai/undergraduate/IT06%20HI&VR/Photopea.html), based on the "photopea.json" file (posted to github.com/photopea/OpenWord/tree/master/examples). However, that file is somewhat stale, last updated 5 years ago, so doesn't reflect newer Photopea features.  If that file could be refreshed, we can leverage its menu commands etc. for our bilingual interface. Thank you.

**Comment by photopea** [comment]
Hi, you can always find the latest file at https://www.photopea.com/translate/ , at the bottom, disable "minified" and "ZIP", and download the latest JSON file (English is the first language in it).

**Comment by xilehence** [comment]
Hi, Ivan.
How can we translate parts of the GUI that don’t have entries in the translation tables?
For instance, the "Quick Mask" and "Virtual Keys” buttons at the bottom of the tool bar don’t seem to be localizable.
Any advice appreciated.

M.C. from M.C. (Merry Christmas from me)

**Comment by photopea** [comment]
"Quick Mask Mode" is translatable, but some are not. I am not sure, if these features will stay in Photopea as they are, or if they will change, so I dont want to ask people to translate them yet.
