### ISSUE TITLE
Merging layers - When merging layers i get a square

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4084]
Maybe i am doing something wrong but i get a white square when i merge this layers:
![image](https://user-images.githubusercontent.com/11801254/144964799-b23d6bff-2be2-4281-9d3f-02d476ba3129.png)

On this project:
https://www.photopea.com/#iv7edqsDj

**Comment by avagp** [comment]
From this:
![image](https://user-images.githubusercontent.com/11801254/144964872-6dcfb3c1-59f7-41e3-8b92-6ae10be691e5.png)


to this:
![image](https://user-images.githubusercontent.com/11801254/144964878-1ae24fc8-c008-46be-9363-361f4b925a9e.png)

**Comment by photopea** [comment]
Hi, I am very sorry, it is fixed now.
