### ISSUE TITLE
não consigo selecionar a palavra(marca da empresa) para trocar de cor

### ISSUE THREAD

**Issue by BrancaEscobar** [photopea/photopea#4085]
Bom dia!
estou tendo muita dificuldade, ou seja, não estou mais conseguindo selecionar a palavra, no caso uma logo marca, pra simplismente alterar a cor, ou pra qualquer coisa que seja! Não consigo! Será que podem me ajudar?

**Comment by photopea** [comment]
Hi, can you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by avagp** [comment]
Branca, você não pode selecionar nada?

**Comment by photopea** [comment]
I have to close it because of lack of details.
