### ISSUE TITLE
Suggestion: Check extension on the browser

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4086]
Hi Ivan, i don't know if this is possible, but because i've seen a lot of unsolved issues that may or may not have to do with extensions. 

Maybe Photopea can check which extensions the user has on his browser (i don't know if it possible).

Maybe just a little menu where you can ask them to check so you can really know if the  user has or not something that it is interfering.

The common user does not know if has a extension or not, many malicious extensions just install themselves without permission.

What do you think? It is possible? It is useful?

**Comment by photopea** [comment]
Sadly, there is no way for a website to know, if there are any extensions installed, or which extensions are there. That would be a way to fingerprint visitors.

I have discussed it with Google, you can look here: https://bugs.chromium.org/p/chromium/issues/detail?id=1236262

**Comment by photopea** [comment]
I will close it, as it is technically impossible for a website to find out, what browser extensions are installed, or what programs are installed in a computer.
