### ISSUE TITLE
Export to PDF - infinite symbol gets filled when vectorized 

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4089]
![image](https://user-images.githubusercontent.com/11801254/145129263-a5cb1003-0cf7-4737-a809-1e7ea0ef5dff.png)

**Comment by avagp** [comment]
Also some shapes
![image](https://user-images.githubusercontent.com/11801254/145129384-1a790dbd-e698-48b6-ad5a-7ddd786740be.png)



Here is the PSD

This is urgent, can you please check it asap?

**Comment by photopea** [comment]
Hi, I can not open a file at your link :(

**Comment by avagp** [comment]
try this one
https://www.photopea.com/#ilm5cKnTb

**Comment by avagp** [comment]
Something is wrong with this file  >:c

Here it is the ZIP
[bug on vecctor.zip](https://github.com/photopea/photopea/files/7686929/bug.on.vecctor.zip)

**Comment by avagp** [comment]
[Archive (2).zip](https://github.com/photopea/photopea/files/7687264/Archive.2.zip)

I now you don't like videos, but this is the only way i can show you what i've discovered.


Btw, please fix the login problem (#3933). I always have ads on now

**Comment by avagp** [comment]
i fixed it by changing the type of merges and order of the path within the shape

**Comment by photopea** [comment]
I am very sorry for the delay, the PDF export of your document should work correctly now, without you having to do any modification.
