### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by MrMavin** [photopea/photopea#409]
When I open a .PSD file on Photopea my RAM consumption will grow over Firefox process. When I close that file, the amount of used RAM will still remain the same, just like if the document was never closed.

The only way to clear used memory is to close and reopen Firefox browser.

In my case this memory usage will freeze the entire system if it reaches 100% utilization. And by opening a bunch of documents it will happen in no time!

**System informations**
**OS:** Fedora 27 Workstation
**Kernel:** Linux 4.13.16-302.fc27.x86_64

Please let me know if you want extra informations and sorry for my English writing skills.

**Comment by photopea** [comment]
Hi, there really was a leak and it should be fixed now. Thank you very much!
