### ISSUE TITLE
When I try to move a layer, the background moves

### ISSUE THREAD

**Issue by Melayanzzz** [photopea/photopea#4091]
As the titel suggest, Can't seem to find a way to upload a picture of it

![image](https://user-images.githubusercontent.com/95828287/145293283-4f667c9d-bfaf-4c95-8fde-0b373bf58f51.png)

**Comment by photopea** [comment]
You have enabled the Quick Mask by pressing "Q". Press "Q" again to disable it. See https://www.photopea.com/learn/selections
