### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by lnfel** [photopea/photopea#4093]
I just noticed today that memory usage on Microsoft Edge process is not going down after I close a project. I use photopea like almost everyday and nothing of this sort happened before. I am using a very old PC with 2GB ram that is why the issue is so apparent.

I was able to work with a few large image files by closing photopea tab (which fortunately clears the ram) and opening another one to edit another image.

System info
OS: Windows 7 Ultimate SP1
Microsoft Edge version: 95.0.1020.44 (Official build) (64-bit)

**Comment by photopea** [comment]
Hi, it should be fixed now. It might take your browser a while to release the memory, but it should be cleared eventually.
