### ISSUE TITLE
Brush Interpolate (Shift + Click) Logic Is Incorrect 

### ISSUE THREAD

**Issue by Arucious** [photopea/photopea#4095]
On most programs if you click somewhere with a brush, and then you shift click somewhere else, it connects the two with a line as if you had drawn it with the brush, the same size as the brush clicks. This creates a sort of 2D cylinder, the same as if you had just drawn with the brush in a straight line across the canvas. 

On Photopea I think it is inserting brush clicks of the given width between the two brush points. This means that instead of getting smooth lines between the start and end, you end up with a caterpillar of brush clicks interpolated the start and end brush click that cause the lines in between to be wiggly

I have attached a video of this behaviour. 

https://user-images.githubusercontent.com/37028027/145596697-62fdc6be-31d0-466e-9a71-fe3b150e2ef2.mp4

**Comment by photopea** [comment]
This is how all painting programs work. If you want to make spacing smaller, click Window - Brush - decrease the Spacing.

**Comment by Arucious** [comment]
you're right -- I just tested it in Photoshop and the behaviour is the same. The illusion of straight lines is coming from the circles being small enough so making the brush spacing smaller or the brush itself smaller should do the trick.
