### ISSUE TITLE
Website keeps opening 5+ folder windows seemingly at random

### ISSUE THREAD

**Issue by geymin** [photopea/photopea#4096]
It seems that the website wants to be able to view all files in the folder for some reason? This hasn't happened before so I assume it's a new bug?
This bug is making the website almost unusable as it closes whatever dropdown i'm trying to use

**Comment by photopea** [comment]
What exactly should I do to see the bug? I open www.Photopea.com and no such thing happens.

**Comment by sawayoshisy** [comment]
I've been having a similar issue; the website keeps opening multiple windows to "select a folder" with seemingly no reason to do so. Been having it happen on both Chrome and Opera on Win10.

**Comment by photopea** [comment]
Can you try these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/  does it happen when you disable all your browser extensions? I still can not make it happen :(

**Comment by SssweetNothings** [comment]
I don't understand how to can't find the problem, at random the website will open loads of folders and even crash, I have restarted my pc and it's none nothing. It's so frustrating as I need to get editing work done and I can't cause it's bugged

**Comment by liakat15** [comment]
Same thing keeps happening to me. This is so frustating. It takes forever to work on anything because I keep getting constantly interrupted with a thousand folders trying to open at once.

**Comment by photopea** [comment]
Can at least one person tell me, if the same problem happens in the Incognito mode of your browser?

**Comment by DeeBurrg** [comment]
Same happening to me. I tried incognito mode and a whole new browser. It seems like this cropped up ever since they changed the box where u can start new projects. I turned off pop ups and it worked for a while and went back to the old version, but i tried again and its back on the new. Randomly pops up without clicking or doing anything. Gotta get this fixed,

**Comment by liakat15** [comment]
> Can at least one person tell me, if the same problem happens in the Incognito mode of your browser?

I tried it in incognito mode for about an hr. It didn't happen in the beginning when I first started but then like 30 mins in it started again. First like 2 folders would open. And then as time went on it went back to how it was.

**Comment by Naught0** [comment]
This happened to me in incognito. It normally happens when I am creating a new project and selecting 'transparent' background, but it just happened to me randomly in incognito as I was trying to apply a radial blur. Let me know if / how I can submit logs to help.

**Comment by RiloTheFox** [comment]
> Same happening to me. I tried incognito mode and a whole new browser. It seems like this cropped up ever since they changed the box where u can start new projects. I turned off pop ups and it worked for a while and went back to the old version, but i tried again and its back on the new. Randomly pops up without clicking or doing anything. Gotta get this fixed,

How do you get to an old version of Photopea?

**Comment by photopea** [comment]
I still could not reproduce it, but I think I have fixed it. Let me know if it is still happening.
