### ISSUE TITLE
Match color doesnt work if source is the same file as the target

### ISSUE THREAD

**Issue by kxtsuki** [photopea/photopea#4097]
Nothing happens no matter the layer you set as target.

**Comment by photopea** [comment]
If your source layer is the same as the target layer, you just match colors of the image with itself, which obviously does not change the image. What makes you think it should do "something" and what that "something" is?

**Comment by photopea** [comment]
What should I do to see the bug happen?

**Comment by kxtsuki** [comment]
Simply use the match color function and put the source the same document your layer is in. No matter the layer you set as target no changes happen

**Comment by photopea** [comment]
I just tried it, and it seems to work correctly in my case (it changes the look of the edited layer). Can you maybe record a video of what exactly you are doing?

**Comment by photopea** [comment]
Are you sure you are using the "Match Color" adjustment in www.Photopea.com , and not in www.Pixlr.com or some other tool maybe?

In Photopea, you can not set "a layer as a target". You can choose only the source layer.

**Comment by photopea** [comment]
ok :)
