### ISSUE TITLE
On Russian language top menu does not fit the screen

### ISSUE THREAD

**Issue by akadatsky** [photopea/photopea#4099]
I have Macbook Air 13.3 and run it in the Chrome browser
<img width="1440" alt="Screenshot 2021-12-11 at 14 37 12" src="https://user-images.githubusercontent.com/2796990/145676846-16c15e83-d8f2-4101-8183-73c1511705d7.png">

**Comment by photopea** [comment]
I see, what would you suggest to do? Should we make the text smaller or remove some buttons? Should we provide only English?

**Comment by akadatsky** [comment]
I would group buttons on the right side (About, Report a bug, Learn, Blog, Api) into a submenu.

**Comment by photopea** [comment]
But if it is hidden in the submenu, people will not know, that a "Report a bug" button exists. Now, they see this button all the time.

Could you translate some phrases into a shorter version in Russian? Maybe редактирование , изображение , can you make them shorter?

**Comment by avagp** [comment]
Maybe report a bug should have a bug icon? :)

**Comment by photopea** [comment]
I have fixed it. On a smaller screens, some buttons will be removed from the right side.
