### ISSUE TITLE
'Save as PSD' Does Not Work On Linux

### ISSUE THREAD

**Issue by butters16** [photopea/photopea#41]
I am loving the potential, great work!! However, 'Save as PSD' does not do anything on Linux. I am using Ubuntu 15.10 (64-bit) and Chrome Version 50.0.2661.102 (64-bit). Upon clicking the 'Save as PSD' menu item, the menu remains and nothing seems to happen. There is an error in the console output:
pp.js:365 Uncaught TypeError: Cannot read property '__name' of nullU.writeDescriptor @ pp.js:365Ra.writeAddInfo @ pp.js:398pa.writeLayerRecords @ pp.js:408pa.Encode @ pp.js:404da.writeLayerInfo @ pp.js:427da.writeLayerAndMaskInfo @ pp.js:426da.Encode @ pp.js:421Fa.EncodePSD @ pp.js:1040Fa.SaveProject @ pp.js:1040la.doSysaction @ pp.js:1057Pa.dispatchEvent @ pp.js:112H.dispatchEvent @ pp.js:840H.dispatchEvent @ pp.js:840Qa.onSelect @ pp.js:1085Pa.dispatchEvent @ pp.js:112H.dispatchEvent @ pp.js:840Za.onMU @ pp.js:1037

**Comment by photopea** [comment]
Hi, thanks for reporting it. You have discovered a bug in Photopea. You had a problem with saving a Text Layer.

Did you work with the initial "pea.psd" or your own PSD? What adjustments did you do with the project, before it became "unsavable"? Can you send me your PSD and describe steps, how can I reproduce this bug? support@photopea.com

**Comment by Studioartcz** [comment]
Hi, i have same system. I will try this too.

**Comment by photopea** [comment]
This bug does not depend on the browser or OS. It was caused by some specific kind of text layer, which Photopea can not handle properly. It would really help to know the details (PSD and adjustments).

**Comment by butters16** [comment]
Sorry, I tried to reproduce the error, but could not. I started over and it's been working well. Thank you!
