### ISSUE TITLE
Export as SVG breaks the text

### ISSUE THREAD

**Issue by SCP002** [photopea/photopea#4100]
If vectorize text option is selected.
![Новый проект (7)](https://user-images.githubusercontent.com/22541678/145678345-81b973ae-e647-498f-8cdd-490af84cb195.jpg)

**Comment by SCP002** [comment]
[issue-4100-sample.zip](https://github.com/photopea/photopea/files/7697292/issue-4100-sample.zip)
Added zip archive with the sample .psd file to test it.
P.S: Left hand side text isn't affected by this bug (probably because it was added earlier?).

**Comment by photopea** [comment]
Hi, I am very sorry, it is fixed now.  Also, Photopea should produce smaller SVG files than before :)
