### ISSUE TITLE
Save Files directly on the website [REQUEST]

### ISSUE THREAD

**Issue by rehansanish** [photopea/photopea#4101]
A cool thing to do will be being able to save your files on the site. It can be saved on your Photopea account instead of your hard drive. It will be convenient since if you have a lot of work, it will be hard to search the file. Or this can be supported in the Photopea app.

**Comment by photopea** [comment]
We are planning to provide a Cloud Storage, e.g. 100 MB for everyone for free, and possibly more for those, who pay for Premium.

But have you tried to click on "This Device" or "Google Drive" on the left side? This way, you can open and save files to a certain "Storage", it is very comfortable.

**Comment by rehansanish** [comment]
I only got the update now! Thanks for the update!

**Comment by photopea** [comment]
We have added a PeaDrive storage!

@MichalSZZ @hxim @radicaldreamer could you test it out? It is on the left side in the storage list. It should work the same as other storages. It allows sharing between teams.

**Comment by MichalSZZ** [comment]
@photopea I don't have any team. Can I be a member of some your test team?

I tested it now on mobile and I dont have some icons (maybe it is some windows system font or something like that).
In the landscape mode on mobile this photopea cloud icon is cute off a little.

When in hit close X button it do nothing and program freeze.

**Comment by MichalSZZ** [comment]
I'm logged in. Maybe I don't understand something but when I tried to Save the file in a menu file Save more -> PSD to Storage I have error (I'm saving in Share folder).
![obraz](https://user-images.githubusercontent.com/38118273/191205734-6bd8ee0d-8a55-4c6c-b2dd-f39c42688b42.png)

**Comment by photopea** [comment]
The Share folder should contain teams (which you made, or which accepted you), and you should save into some folder inside a team, for which you have rights.

Maybe I should write some tutorial about it. But what about the non-team part?

**Comment by photopea** [comment]
We have added our own cloud storage named Peadrive: https://twitter.com/photopeacom/status/1575196954971279362 . You can upload files from your computer or download them to your computer.
