### ISSUE TITLE
My file disappeared!

### ISSUE THREAD

**Issue by evaweiss2** [photopea/photopea#4102]
All of my work, months of work, is gone!  I opened it and nothing is left.

**Comment by photopea** [comment]
What "work" are you talking about? Do you mean PSD files inside your computer? Websites can not delete files on your computer. Photopea.com is a website.

**Comment by evaweiss2** [comment]
Yes.  I opened my PSD in Photopea and months of work disappeared, before my eyes.  I tried to press “undo” but nothing was in the history area. Is it possible you were hacked?

Sent from my iPhone

On Dec 12, 2021, at 6:17 AM, Photopea ***@***.***> wrote:

﻿

What "work" are you talking about? Do you mean PSD files inside your computer? Websites can not delete files on your computer. Photopea.com is a website.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fphotopea%2Fphotopea%2Fissues%2F4102%23issuecomment-991878951&data=04%7C01%7C%7C730066456aaf471e9eb908d9bd610728%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637749046690180701%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bcDLznsNnI6WUVuXm2CZyMpmGSBQEocxjN8pvgNiizo%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACK7FG2CU2IB5INX6XNARRLUQSAFXANCNFSM5J3OM6NA&data=04%7C01%7C%7C730066456aaf471e9eb908d9bd610728%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637749046690190697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1NWhfDhQ7hLOUpCHfQ1pVpAJx8kyQveYSn2jKM8124U%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C730066456aaf471e9eb908d9bd610728%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637749046690190697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jdsLX72pEFIPar0IyaeEb2hVkfSqlXI916z8Wak3%2F5E%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C730066456aaf471e9eb908d9bd610728%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637749046690200689%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CIoyV7u3w4%2FE%2FV9esMeYwFm%2BsO6CTLOk4q2ESUdh3gc%3D&reserved=0>.

**Comment by photopea** [comment]
If you open a file from your device in Photopea, and it "disappears" in Photopea, it should still stay stored inside your device.

Are you doing it on a phone? Phones have low RAM memory, and Photopea is not able to open large files with a small RAM.

**Comment by evaweiss2** [comment]
Hi,

Thanks for writing back and inquiring.

Here are some answers to your questions:

- It is not the PSD file that disappeared, it is the layers I created that disappeared.  I had roughly 15 folders of layers, one for each page. (I’m working on a children’s book.)

- I work from my iMac Pro. I only email from my iPhone.

- when I closed and reopened the file in photopea, the layers were gone.  When I reopened the PSD file in Photoshop (I downloaded a 14 day trial) some of the layers were gone — about 3 pages worth of layers.

In any case, it’s not so bad, as I still have the original art, exported Jpegs to work from, and the text in word format.

I should have backed up my PSD on a thumb drive.  However, it is still freaky watching ones work disappear before one’s eyes.  I suspect it’s a security issue but I can’t be sure.

Best,
Eva W.

Sent from my iPhone

On Dec 12, 2021, at 8:49 AM, Photopea ***@***.***> wrote:

﻿

If you open a file from your device in Photopea, and it "disappears" in Photopea, it should still stay stored inside your device.

Are you doing it on a phone? Phones have low RAM memory, and Photopea is not able to open large files with a small RAM.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fphotopea%2Fphotopea%2Fissues%2F4102%23issuecomment-991901996&data=04%7C01%7C%7C505d1aa58ae44126495408d9bd7633c7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637749137636110772%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HnrhNDuxGAuURgtwtwmM1hHGZ85SAUPEYg7qdwCn5sU%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACK7FG6ZLWXI7AEP425356TUQSR6DANCNFSM5J3OM6NA&data=04%7C01%7C%7C505d1aa58ae44126495408d9bd7633c7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637749137636120761%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=trvCYXC7%2FxfRyemgIRVxDdY3f7rgoGxtRKpWaAink90%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C505d1aa58ae44126495408d9bd7633c7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637749137636120761%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=atkxkk79jDT2srveRVZ1%2FdAqmjD0oQUGJm%2BNFm0MiTE%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C505d1aa58ae44126495408d9bd7633c7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637749137636130758%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FSc2rbe56%2FyzgkmuXtYjHfnM%2FlA2clX%2B0DjS0I%2BdJe0%3D&reserved=0>.

**Comment by photopea** [comment]
Photopea should not modify a PSD file in your computer, unless you press File - Save.

If yo still think Photopea removed your layers by mistake, could you describe, how can I make Photopea delete layers?

**Comment by evaweiss2** [comment]
To be honest, when I saw a few layers disappear, I panicked, it happened so fast.  I can’t say that I did not press “save” to prevent more layers from disappearing.  I worked on this 16-page children’s book for a year, with some hand-sewn, some drawn, and some digitally created assets.

To slow down a bit...here are some steps:

 I opened the file and everything was ok.

 I added folders to organize the layers, and put some layers into “archive” folders within folders.

 I opened a jpg photo in another tab and copied part of the image.

 I went back to my main file to paste it.

 I first noticed something was wrong when I did not see the area delineated around my pasted selection.

 Maybe the layers did not load properly, yet. But many of the layers were gone.

 Here I think I saved to prevent more layers from disappearing.

 I opened  and reopened my file to make sure.
 I  checked on the size of the file: still roughly 250MB.

 I started to try to replace my lost folders, changed tabs, returned and saw more layers gone.

 There was only layer 143 and a collapsed archive folder which would not expand.

 Here I did not save, and just closed.

 Open reopening in photopea, I saw that same layer 143 and a collapsed archive folder which would not expand.

 Open opening in photoshop trial, I saw my PSD minus the 3 folders initially lost and plus the replacement folders I added.

In conclusion:

It could be a loading issue instead of a security issue.  But if a folder or layer does not load, and the user presses save, does that mean that folder or layer is gone forever?




Sent from my iPhone

On Dec 12, 2021, at 9:43 AM, Photopea ***@***.***> wrote:

﻿

Photopea should not modify a PSD file in your computer, unless you press File - Save.

If yo still think Photopea removed your layers by mistake, could you describe, how can I make Photopea delete layers?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fphotopea%2Fphotopea%2Fissues%2F4102%23issuecomment-991910626&data=04%7C01%7C%7Ca333b7e9134b48f3272808d9bd7db742%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637749169905022531%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uZY11oaC8z%2FUdzMaC6SQHBiVe2R0xJ%2BH5Lch9VLBbKM%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACK7FG2DXFZQSWDELWO7EGDUQSYHZANCNFSM5J3OM6NA&data=04%7C01%7C%7Ca333b7e9134b48f3272808d9bd7db742%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637749169905022531%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=B1%2B6W%2F8HTLRzGnPulNgJhsLlCwioFj3puK0gs7fBTeQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca333b7e9134b48f3272808d9bd7db742%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637749169905022531%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=IrwQwOOJpHGCCupjvYTBTjQ0DRqOJwS8eAZTwO%2FKfD0%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca333b7e9134b48f3272808d9bd7db742%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637749169905022531%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZV468C07Qu0b%2Ft7Drvv4lESFWDYGCz4iChtUbNoQMeY%3D&reserved=0>.

**Comment by photopea** [comment]
Can you make Photopea delete layers like this again?  If I can make it happen on my computer, I could dig deeper and fix it.

If you open a PSD (in Photoshop or Photopea), delete layers, and save it back (replacing an old PSD in your computer), that new PSD is the only file you have at that moment.

**Comment by evaweiss2** [comment]
I will see if I can reproduce it.  I don’t think it would be easy.

I think that the key elements are:

- Long history (I was working on this file for months, since June 2021, at least 4x per week, in the same browser tab, saving occasionally.)
- groups of layers
- Lots of layers deeply nested in lots of folders
- flipping between tabs to copy& paste
- possibly saving while the file is still loading

Maybe you can have a message pop up saying the file is still loading, so don’t save yet?

When I opened that PSD in photoshop, I got the message that some “groups were found corrupted and repaired”.




Sent from my iPhone

On Dec 12, 2021, at 10:40 AM, Photopea ***@***.***> wrote:

﻿

Can you make Photopea delete layers like this again? If I can make it happen on my computer, I could dig deeper and fix it.

If you open a PSD (in Photoshop or Photopea), delete layers, and save it back (replacing an old PSD in your computer), that new PSD is the only file you have at that moment.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fphotopea%2Fphotopea%2Fissues%2F4102%23issuecomment-991920129&data=04%7C01%7C%7C4cecac657987402fbb7308d9bd85beea%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637749204395177581%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=k8cQFtUE5iOogGGywf7w2Yh68IWgXy2OCace8bwY75g%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACK7FGYMSADLTQTRB2CKFD3UQS67LANCNFSM5J3OM6NA&data=04%7C01%7C%7C4cecac657987402fbb7308d9bd85beea%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637749204395177581%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=M4j4N4m4jw8PRPez0x8v3L1AF2I%2BGfLG02Qg7ZWTXSc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C4cecac657987402fbb7308d9bd85beea%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637749204395187576%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sGH4S5LRA9VDHLFhv5OTyrFjPOQ1uarO97pbweRmrN4%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C4cecac657987402fbb7308d9bd85beea%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637749204395187576%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sFkT1GiU8%2FMU5yrLD62Efw0wBjTYJ5sObUbIxvylkd4%3D&reserved=0>.

**Comment by photopea** [comment]
Ok, I am very sorry for what has happened to you. A web browser can kill any website at any moment. They often do it when a website asks for too much memory.

If you work with large documents, and you know your memory is low, try to save your work at least once a day.
