### ISSUE TITLE
introduction screen

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#4104]
hi
today when i opened photopea I was surprised that the introduction screen had been updated, I liked it and support these types of updates :)
however, it has some cons that make me uncomfortable and make me want to open this issue.
I made some edits to the new introduction screen that might make it more clean and modern, and also designed a new one and I'm sure that you will like it get some ideas

### your new introduction screen edits :

- make the right menu light (as you did on the templates page ) because unity in design is required.
- align everything to the center

![Screenshot (356)](https://user-images.githubusercontent.com/70863817/145694765-eab15e47-4890-4649-8a7a-6b55e0945a12.png)

.
.
.
### my new introduction screen edits :

- the home page has only recent files/images/templates
- PSD templates in the right menu
- you can remove the Image from recent by clicking on the 3 dots in the right bottom of it then chose "remove from recent"

![Screenshot (356) (1)](https://user-images.githubusercontent.com/70863817/145694970-40b79515-4b40-4c8e-886c-6b02595aad72.png)

- when clicking "new project" this window appears

![Screenshot (356) (3)](https://user-images.githubusercontent.com/70863817/145695085-75376c19-053d-4356-861f-eabd8a236e2e.png)

**Comment by mustafaGFX** [comment]
i'm exited to know your thoughts about it

**Comment by photopea** [comment]
You talk about aligning the menu to the center, but in your screenshot, it is not in the center (of the right part).

I made the left column brighter. The colors correspond to a current color theme.

A list of last documents is not possible, because websites can not read your hard drive. Have you looked into "This Device"? You can sort your documents by the date modified, and set the view to "Icons".

I think it is wrong to make the user click twice to start making a new file.

**Comment by mustafaGFX** [comment]
> You talk about aligning the menu to the center, but in your screenshot, it is not in the center (of the right part).

not the menu, the logo and the page content, it look cleaner :

![Screenshot (363) (1)](https://user-images.githubusercontent.com/70863817/145732443-761a9b30-5a59-4582-9730-5f06256f8028.gif)


> I think it is wrong to make the user click twice to start making a new file.

i totally agree with you aobut this point

BTW we have amazing plugin that almost finished, we will show you tomorrow :)

**Comment by avagp** [comment]
i also think the suggestion of center the content look better, and it keeps continuity with the older version

**Comment by photopea** [comment]
Ok I have put it to "the center". Note, that in every language, words are different, and the three buttons could be not aligned nicely into a rectangle, that is why I wanted it to be aligned to the left side.

**Comment by avagp** [comment]
Well, it looks good imho.

Even though, i believe there is a problem with margins and line-heights:
![image](https://user-images.githubusercontent.com/11801254/145908851-01f481ec-cc23-4136-b8dc-34a28c465348.png)

And also with the width of the dropzone. 
![image](https://user-images.githubusercontent.com/11801254/145908841-8e2a8c60-cb51-4bcc-9879-c552983c28d2.png)

**Comment by xan2622** [comment]
Here is how it looks here: 
![85355](https://user-images.githubusercontent.com/1732773/146731969-7c1b2dc1-ecd3-46e1-9925-fc8499f013cc.jpg)

@photopea, Would it be possible to move (PSD, AI, XD...) icons from the bottom to bellow the "Drop any files here" frame (as shown in mustafaGFX's mock-up)?

**Comment by photopea** [comment]
On a tiny screen (e.g. where height is 300 pixels), "the formats" cover the frame "drop any files here". If they were right below that frame, they would be hidden in such case.
