### ISSUE TITLE
Bug: Paths lost / revert to old state when editing shape layer

### ISSUE THREAD

**Issue by KyoGrou** [photopea/photopea#4105]
Happened randomly while editing the paths in shape layer that have many paths in it, some of the paths will disappear / revert to its old state (deleted paths reappear for example); Usually on a pre-exist file, not newly created file.

The bug occurs when using Transform tool, Copy, Cut, Paste paths between layers. I didn't check if directly editing the paths using Pen tool or using other tools will make it happen.

![image](https://user-images.githubusercontent.com/30156458/145700079-b7268238-2787-4d95-aa95-034b23bf01c6.png)
![image](https://user-images.githubusercontent.com/30156458/145700100-efc1a885-8105-45ef-8518-7f9e6077b7f3.png)

![image](https://user-images.githubusercontent.com/30156458/145700133-1ab268f0-035c-4416-942d-5668e43780a5.png)
![image](https://user-images.githubusercontent.com/30156458/145700164-bec72450-a878-4394-b32d-74b720a96595.png)
![image](https://user-images.githubusercontent.com/30156458/145700175-d754d488-78c9-48d6-aea3-8abe4cb38af0.png)

**Comment by photopea** [comment]
Could you describe how can I reproduce such bug?

**Comment by KyoGrou** [comment]
As I said above, it happened randomly, but I think it usually happen on my on-going files (draw, edit lots of shapes; save file to computer, shut down, open file on the next day, edit shapes and then it happened)

**Comment by photopea** [comment]
I still believe it happens when you do something specific. 

I can not fix a bug, which I can not reproduce :( let me know once you find how to make it happen.

**Comment by KyoGrou** [comment]
I will attach the file here, I can still re-produce the bug when I just open and edit the shape layer.
![image](https://user-images.githubusercontent.com/30156458/146014489-32180d70-2f84-41d0-bfa2-05042f4b114d.png)
My other catch is that when I tried using transform directly on that path, it got replaced into another path, like it has some problem with how the layer keep track of the paths in it.
![image](https://user-images.githubusercontent.com/30156458/146015133-052e4876-95db-430b-837c-ae841aeaea12.png)
![image](https://user-images.githubusercontent.com/30156458/146015209-03316db2-6fa2-4520-9805-1713c744b103.png)

**Comment by KyoGrou** [comment]
Yes, I made it entirely in Photopea.
