### ISSUE TITLE
Feature request: Duplicate transform, duplicate using arrow keys (paths)

### ISSUE THREAD

**Issue by KyoGrou** [photopea/photopea#4106]
- Ctrl + Alt + T: Duplicate selection and enable transform, useful for working with shapes (creating donuts ?)
- Ctrl + (Shift) Arrow keys: Worked well with raster layers, but the shape layer doesn't have this feature.

**Comment by photopea** [comment]
Web browsers do not allow us use Ctrl+T for free transform, so if we use Ctrl+Alt+T for duplicate+free transform, there would be no shortcut left for the Free Transform.

arrow keys move a path only if you select at least one path, e.g. with the Path Select tool. Also, you can move it with a keyboard if you switch to the Move tool.

**Comment by KyoGrou** [comment]
Sorry I mentioned the wrong shortcut keys on the previous comment,
What I meant is [Alt + (Shift) Arrow keys] to duplicate the path using move command, not to move the path itself.

About the Transform Duplicate, is it possible if we assign another shortcut ?

**Comment by photopea** [comment]
You can duplicate paths by holding Alt and moving it with the Path Select tool. The Move tool is for moving layers, not paths.

**Comment by KyoGrou** [comment]
Yes, what I meant is when using the Path Select tool, with the paths already selected (with the Path Select tool), you can press Alt + Arrow keys to duplicate and move it, just like how you move (edit) the paths with the arrow keys when you are on the Path Select tool

**Comment by photopea** [comment]
I see, I made it work like that.
