### ISSUE TITLE
It takes longer to open Photopea

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4108]
Before this week, after I opened Photopea once with vpn, I can open it without vpn quickly for a period of time. But now as long as I don't use vpn, it will always take a long time to open. If I disconnect from the internet, I can open it much faster :(

**Comment by photopea** [comment]
I don't think it is related to any change in our website. You are from China, right? Are there any restrictions of non-Chinese websites? I think you should ask your internet provider about it.

Can you check, which files take the longest to load in your case? It is shown in the Inspect Element.

**Comment by nothingshiru** [comment]
It's "fbevents.js" that takes longest time. When I saw it in DevTools, the UI of Photopea appeared at the same time. 
![-79345a557f6671ad](https://user-images.githubusercontent.com/79258245/145751681-769c477c-2c69-44c3-b24e-439548835bcd.png)
Facebook is banned in China.

**Comment by photopea** [comment]
What about now ? Is it fixed?

**Comment by nothingshiru** [comment]
It is fixed :)

**Comment by photopea** [comment]
ok great :)
