### ISSUE TITLE
Some issues on Introduction and This Device

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4109]
1.) When I open image and select brush and then close all my documents. It keeps cursor of selected tool (brush in this case) on introduction screen.
![iss1](https://user-images.githubusercontent.com/6370548/145770763-275944c4-e046-48b4-a4e1-cd466f44c6b4.png)
2.) There is "New Folder" option in This Device tab even before I load any device and it shows error in console when I click it.
![iss2](https://user-images.githubusercontent.com/6370548/145772002-54dd72f3-a767-4d1e-941b-18db3d5a1d19.png)
3.) There are some missing texts in english translation for some Sort and View options in "This Device"
![iss3](https://user-images.githubusercontent.com/6370548/145772078-79499b8e-9511-49af-9e6b-074ef00b14ca.png)
4.) When I try to save new project using  "Save More" - "As PSD to Storage"- In this dialog I cannot type in Name input field. When I press some letter it autofills name of file in that folder instead of writing that letter or when I press delete it tries to delete some file instead of deleting letter.
Screenshot before I pressed letter "s" on keyboard:
![iss4](https://user-images.githubusercontent.com/6370548/145771878-e771ce6d-006f-4ddc-848c-84282cf410cb.png)
Screenshot after I pressed letter "s" on keyboard:
![iss4b](https://user-images.githubusercontent.com/6370548/145771884-55bd4d2d-db07-41b7-9641-60d98b97b001.png)
(note: there is file "screenshot_chrome.png" in that folder, I want to name my file "moje stránka.psd")

**Comment by photopea** [comment]
It should all be fixed now, thanks for reporting :)
