### ISSUE TITLE
the application lags too much 

### ISSUE THREAD

**Issue by redmin22882** [photopea/photopea#4111]
What happened to Photopea? After updating the interface, he started to lag a lot. I can’t even work normally in “photopea” because sometimes it says that there is not enough memory, but at the same time I have it, and in abundance 
![Screenshot_20211213-094600](https://user-images.githubusercontent.com/74855608/145781801-8b6b601c-a166-4713-b7e0-4eb909c0e633.png)

**Comment by photopea** [comment]
Can you tell me what should I do in Photopea to see the lag?

**Comment by redmin22882** [comment]
> Подскажите, что мне делать в Photopea, чтобы увидеть отставание?

Easy to work as it started to lag a lot, especially when I used the tool "pen" I don't know, maybe it's just my problem, but I hope it can be fixed

**Comment by redmin22882** [comment]
In addition, sometimes the inscription "not enough memory" is displayed, and believe me, there is a lot of it. At least for using photopea

**Comment by photopea** [comment]
I give up. You need to tell me exact steps, what should I do to see "not enough memory". Otherwise, you can be making it up.

**Comment by redmin22882** [comment]
> Я сдаюсь. Вы должны указать мне точные шаги, что мне делать, чтобы увидеть «недостаточно памяти». В противном случае вы можете это придумывать. 

Coming up? Do not forget that I sent a screenshot where I showed this inscription

**Comment by redmin22882** [comment]
It comes out from me when I just want to open * psd "or just a photo that I want to edit

**Comment by redmin22882** [comment]
Перевод от Гугл тут ужасен...

**Comment by photopea** [comment]
Did you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by redmin22882** [comment]
> Вы пробовали это? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

No, I have not tried this, but I have no data problems that were written there... So I have no idea what to do, since the photopea started to lag very much, besides, the "quick selection" function does not work for me And I also have no idea why, although my device may be outdated.

**Comment by redmin22882** [comment]
В любом случае я крайне извиняюсь за написание на английском языке, так как перевод не совсем корректно работает
