### ISSUE TITLE
randomly asking to select folder

### ISSUE THREAD

**Issue by bebta** [photopea/photopea#4113]
For some reason when I try drawing a line or etc, it will randomly ask me to select a folder even when I did not want to select any folders.  This happens a lot for some reason and seems to have started right after the new update. Sorry if the explanation wasn't that helpful. 
![image](https://user-images.githubusercontent.com/96068527/145839111-893bc333-645f-4d13-9500-2351967a8156.png)

**Comment by photopea** [comment]
Did you try to close Photopea and open it again in the last 24 hours?

I think we have fixed that problem yesterday. Can you close Photopea and open it again, to make sure the latest version is loaded?

**Comment by bebta** [comment]
> Did you try to close Photopea and open it again in the last 24 hours?
> 
> I think we have fixed that problem yesterday. Can you close Photopea and open it again, to make sure the latest version is loaded?

I tried opening and closing it again and it seemed to have worked. Thank you for the help.
