### ISSUE TITLE
Request: Decrease the opacity of grid

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4115]
when grids are displayed, it is difficult to see the image clearly. 
![screenshot_20211214_113221](https://user-images.githubusercontent.com/79258245/145928586-8dcbf169-2f7e-4466-a747-734c4421bde4.jpg)
Can the opacity of grid be decreased? it is better to change it to 10%.

**Comment by photopea** [comment]
I think that is how it should look like. If you don't want grid, disable it in View - Extras. If you want the gaps to be bigger, change them in Edit - Preferences.

But if you really think it could look better, can you show me how do you want it to look like?

**Comment by nothingshiru** [comment]
Sorry, I gave a wrong example image. there's no way to see the colorful photo clearly when grids are displayed.

What I want is that grids can be grey in white background. Like this
![新建项目](https://user-images.githubusercontent.com/79258245/145992034-72156e66-2fb4-4c12-9eec-fa7e8c89cd00.png)

**Comment by photopea** [comment]
I don't think this grid will look well on a photo. Can you show me an image of your photo with a grid on it, as you want it to look like?

**Comment by photopea** [comment]
Our current grid "inverts" the color behind it. It turns white to black, black to white, red to cyan, yellow to blue, and so on.

**Comment by nothingshiru** [comment]
I discovered that. 
Have a look at this psd and try to adjust a opacity of the grid layer. That's the effects I would like to have.
www.photopea.com/#i7UKvdvtp

**Comment by nothingshiru** [comment]
I discovered that. 
Have a look at this psd and try to adjust a opacity of the grid layer. That's the effects I would like to have.
www.photopea.com/#i7UKvdvtp

**Comment by photopea** [comment]
I think your grid is very hard to notice at some places. People rarely use such fine grid, the gaps are usually bigger.

**Comment by nothingshiru** [comment]
Grids don't always need to get too much attention. They can be just for layers to snap to. For example my grids are for ensuring the position of layers can be divided by 8.
