### ISSUE TITLE
Menu bleeding

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4117]
![image](https://user-images.githubusercontent.com/11801254/145932929-fb5a81dd-ed86-4ec7-aa46-7a427016d355.png)

When i right-click a paragraph layer i get this option, which is not correctly aligned

**Comment by photopea** [comment]
I can not make it happen on my computer :( Can you try it in Incognito mode, or update your browser?

**Comment by avagp** [comment]
I can't repro again myself :/

**Comment by photopea** [comment]
ok
