### ISSUE TITLE
Request: Fixed ratio by default in Free Transform

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4118]
![screenshot_20211214_142942](https://user-images.githubusercontent.com/79258245/145945261-ca1bb03b-e24a-4ca9-8144-0fe82f37f712.jpg)

**Comment by photopea** [comment]
You probably mean keeping aspect ration on by default, and disabling it when pressing Shift. But I like the way it works now.

**Comment by nothingshiru** [comment]
No. This request is just about the values in textbox.

**Comment by nothingshiru** [comment]
Specifically, the request is enabling the "Lock" by default. No changes to dragging.

**Comment by photopea** [comment]
Ok, I set it to Enabled as a default value.
