### ISSUE TITLE
Save More - As PSD to Storage not working

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4119]
When I tried to save new project using "Save More" - "As PSD to Storage" it did not work. Clicked "Save" button and nothing happens and error is shown in console - see this screenshot:
![image](https://user-images.githubusercontent.com/6370548/145954177-b3db33b1-6387-4cb2-a3bb-644095a75355.png)

Edit: I figured when I put ".psd" extension in the name it will work - error appears only when I write name without extension.

**Comment by photopea** [comment]
Fixed :)
