### ISSUE TITLE
Touch input on pen displays

### ISSUE THREAD

**Issue by joeyjo08** [photopea/photopea#4121]
Hello, i have a 2 in 1 laptop that is touchscreen with a pressure sensitivity pen by wacom, unlike photoshop when i go to draw, the touchscreen picks up my palm and i have to erase everytime and it gets annoying. Is there a way there can be touch input in photopea?? thank you. also I have problems with loading the fonts already installed on my windows computer. It sees as i have to load them 1 by 1. any feedback or fixing these would be appreciated, thank you.

**Comment by nothingshiru** [comment]
1. You can enabled "No Touch" to ban finger touch from canvas. 
![screenshot_20211215_081536](https://user-images.githubusercontent.com/79258245/146099866-42de2e94-0958-4840-8d44-1e3860cdb236.jpg)

2. Select the fonts then drag and drop them into Photopea.

**Comment by photopea** [comment]
That is correct, enable "No Touch" at the bototm of a toolbar. Photopea and other websites can not see fonts or any other files in your computer. You can 1000 TTF files from your computer into Photopea using File - Open.
