### ISSUE TITLE
Saving projects

### ISSUE THREAD

**Issue by joeyjo08** [photopea/photopea#4122]
I usually save projects in 300 dpi to always get the best quality for my designs. Although when i work in photopea for an extended time, it gets real slow and when i go to save, it takes at least 15 seconds or it says save but doesn't save. the only solution I found that sometimes works for this issue is manually saving a new PSD, and hoping it saves before it crashes/freezes.

**Comment by photopea** [comment]
Hi Joey, Photopea is a raster editor and its speed depends on the total number of pixels. So if you have 50 million pixels, it is 50x slower than if you had one million pixels. You need a better computer (faster CPU, more RAM) to work with large documents (a lot of pixels).

What kind of graphics do you create? If you work with vector graphics, the DPI is not important at all, you can work even with a DPI of 70.

**Comment by photopea** [comment]
We are planning to make a vector editor soon.
