### ISSUE TITLE
Feature request: Switch tool temporary by pressing and holding shortcut key

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4123]
There are some tools that are usually used temporarily, for example Rotate, Zoom... With this feature, we don't have to find the key of previous tool to press after used the temporary tool. It is convenient and efficient.  

In Photoshop, we can long-press the key to select the tool, long-press for 1 second, after releasing the key, it will switch back to the previous tool.

**Comment by photopea** [comment]
Even if we implement it, I think people would never find it (as it does not work this way in any other program), so nobody will ever use it.
You should be able to pan and zoom with two-finger gestures, right?

**Comment by nothingshiru** [comment]
Photoshop, Clip Studio Paint... work in this way. This a feature mainly for keyboard&mouse, and it works for all tools instead of only zoom tool.
![screenshot_20211216_074329](https://user-images.githubusercontent.com/79258245/146285000-6d01bcc0-fa7a-4abe-b2f2-e0d16ac5131e.jpg)

**Comment by photopea** [comment]
Are you asking for this feature (with a keyboard)? I thought you have a touchscreen device.

**Comment by nothingshiru** [comment]
Sometimes I use keyboard&mouse for efficiency.

**Comment by photopea** [comment]
I will close it, as I think not many people would use it.
