### ISSUE TITLE
Request: Improve the looking of the bubble for the texts of selection size

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4124]
1. Round cornor. 
2. Decrease opacity.
3. Make the size adaptive to the texts.

background-color: rgba(0,0,0,0.8);
border-radius: 4px;
padding: 4px 8px;
![Screenshot_20211215_180214_com microsoft emmx](https://user-images.githubusercontent.com/79258245/146171306-78631453-2e35-4204-88a0-938b2c188e24.png)

**Comment by photopea** [comment]
Ok I made it as you said :)

**Comment by nothingshiru** [comment]
1. padding-right is missed.
![Screenshot_20211216_080213](https://user-images.githubusercontent.com/79258245/146283785-5d850aae-5b99-4f3a-aa5b-1d5a4c770c00.jpg)

2. The size is not adaptive to different languages.
![Screenshot_20211216_074535](https://user-images.githubusercontent.com/79258245/146283859-e142dd93-326a-444c-b385-229969269644.jpg)

**Comment by photopea** [comment]
Now it should be fixed.
