### ISSUE TITLE
PDF does not have all assets

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4125]
When i open this PDF (and others) i don't get all the image.  :(

![image](https://user-images.githubusercontent.com/11801254/146208459-678f0eeb-b05f-493c-b635-50873e544ecc.png)
![image](https://user-images.githubusercontent.com/11801254/146208288-f0ceaf79-b710-440b-970c-d9970665d255.png)

[KH R4 DONE.pdf](https://github.com/photopea/photopea/files/7720376/KH.R4.DONE.pdf)

**Comment by photopea** [comment]
Your file is actually an AI file. You can tell it is AI, because there is quite nice layer structure, and the file is 10x larger than a PDF could be.

I fixed it, except of the hair pattern, Photopea does not support it.

**Comment by avagp** [comment]
:(

It is too difficult to support the hair pattern??

Even like rasterizeing it??

**Comment by avagp** [comment]
How does PDF support it, but Photopea not?

**Comment by photopea** [comment]
Photopea can not load patterns even from PDF files. Patterns in PDF and AI are vector patterns (repeated vector shapes), there is no such thing in PSD.
