### ISSUE TITLE
Menu screen is disaligned

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4126]
I believe there is a problem with margins and line-heights:
![image](https://user-images.githubusercontent.com/11801254/145908851-01f481ec-cc23-4136-b8dc-34a28c465348.png)

And also with the width of the dropzone. 
![image](https://user-images.githubusercontent.com/11801254/145908841-8e2a8c60-cb51-4bcc-9879-c552983c28d2.png)

**Comment by photopea** [comment]
how can I reproduce it? Is your web browser updated?

**Comment by avagp** [comment]
to repro:
1.- open photopea.com

:)

**Comment by avagp** [comment]
I have and updated browser

**Comment by avagp** [comment]
When changing to another language, the dropzone does not adjust.

(because it has a min-width  property)

**Comment by photopea** [comment]
I see it like this.
![image (1)](https://user-images.githubusercontent.com/15955558/146285610-fea72263-cf76-40c6-afb7-ef0315dad627.png)

The dropzone should not be adjusting. The dropzone is the whole Photopea window.

**Comment by avagp** [comment]
When i delete the icons i got it correct
![image](https://user-images.githubusercontent.com/11801254/146286783-065cbc96-ace6-4501-8eb5-87bb25e8166c.png)


![image](https://user-images.githubusercontent.com/11801254/146286761-6001cdc4-4d5e-48b0-9042-4d565ca8857b.png)

**Comment by avagp** [comment]
I changed them to emojis :)
![image](https://user-images.githubusercontent.com/11801254/146287361-adf998a9-3036-46e5-973b-475a323d2f77.png)

Because the emojis have the same line height

**Comment by avagp** [comment]
i will report it to chromium

**Comment by photopea** [comment]
ok
