### ISSUE TITLE
"Merge Down" button not working

### ISSUE THREAD

**Issue by s-lyw** [photopea/photopea#4127]
Hi team, 

Specifically after cropping an image, I click on the merge down button but it doesn't work. Which makes the next step undoable, like when I click on magic wand it doesn't respond. 

Appreciate your kind assistance.

Thank you.

**Comment by photopea** [comment]
Hi, I just tried to merge down a layer, but it seems to work fine.

Could you describe steps, what should I do after opening www.Photopea.com to see the problem? And make sure these steps really do cause a problem in your case.

**Comment by s-lyw** [comment]
Hi,

Steps as below
1. Open image
2. Crop image
3. Merge layer 
4. Merge layer doesn’t work and entire page freezes


Note: This happened to me twice this week. The first time when it happened, I tried chrome incognito, another browser and all didn’t work. So I didn’t use and today it happened again and I clear browsing data and cache from beginning of time and still the same.

**Comment by photopea** [comment]
I can see a bug, when there is just one layer, and you choose "Merge Down".

Is that what you describe? Are you merging a layer down, while there is only one layer in the project?

**Comment by s-lyw** [comment]
After cropping the image, it’s still 1 layer but I need to merge so that when I use magic wand, it doesn’t show the unwanted parts. I have been doing this for over a year but only recently faced this issue.

**Comment by s-lyw** [comment]
https://user-images.githubusercontent.com/96218411/146394903-c21b0a45-f46d-463b-a5f6-653eac5fdf71.mp4

**Comment by photopea** [comment]
"Merge" means merging two or more layers together. You can not merge anything, if you have just one layer.

What exactly do you mean by "unwanted parts"? The magic wand should never select pixels, that are outside the screen.

**Comment by s-lyw** [comment]
As mentioned earlier, I have been doing the same steps for over a year with no issue. I might have worded my issue unclearly..

**Comment by photopea** [comment]
That was a bug, and I have fixed it. You are not supposed to be able to merge just one layer with itself.

If you tell me what you need to do, I can tell you how to do it.

**Comment by s-lyw** [comment]
It works now, thanks for fixing!
