### ISSUE TITLE
Problem after Save More - PSD to Storage

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4130]
1.) I created new project.
2.) I opened Save More - PSD to Storage. Then I clicked This Device - It showed me my in PSD files in folder.
3.) I canceled/closed this dialog window (with cross in top right)
4.) I closed all my documents.
5.) I selected This Device in introduction screen
6.) PROBLEM: Only PSD files are visible and cannot be opened (double click doing nothing) and in the bottom there is Name field and Save button that should not be there. See screenshot:

![image](https://user-images.githubusercontent.com/6370548/146317302-6f429147-15c3-44d6-bf61-b053eef36c65.png)

**Comment by photopea** [comment]
Thanks, I have fixed it :)
