### ISSUE TITLE
Delete channel problem

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4132]
1.) Create new project.
2.) Go to Channels and create new channel with "New" button - "Alpha 1" is created
3.) I am not able to delete it - when I click "Delete" button it only shows this error "Uncaught Chnl" - see screenshot
![obrazek](https://user-images.githubusercontent.com/6370548/146321443-9a64867d-dde5-4049-8718-47ac81838d34.png)

**Comment by photopea** [comment]
fixed, thanks!
