### ISSUE TITLE
Bug, Feature request: Newly created Layer Styles have the same values as the most recent style

### ISSUE THREAD

**Issue by KyoGrou** [photopea/photopea#4133]
I don't really know if this is a bug or a feature, when I create a layer with the custom Layer Style (let's say a thick blue stroke for example), then create another and if I went through RMB -> Blending Options -> Stroke, the style is the same with the previous one (a thick blue stroke), even on a newly created layer. The same goes for adding more of that effect on the same layer using the [+] buttons in the Layer Style window.

I think this behavior makes sense when using the [+] buttons, but on a newly created layer it's weird, since normally we would expect something fresh to work on, and it's easier to make new styles from the default values rather than a bunch of custom numbers and colors (gradients for example). (And since we have the Alt + Drag to copy the Layer Styles, this problem make even less sense)

So this problem led to this: I think would be nice if we have a "Default" button so the user can quickly go back to Photopea's default value. This helps one to have a new style to quickly start working on, even if they use the [+] buttons or they messed up badly and want to quickly go back.

![image](https://user-images.githubusercontent.com/30156458/146354422-336a3444-4f5b-4e46-bd98-3a35bb935192.png)
![image](https://user-images.githubusercontent.com/30156458/146354483-d1f69178-09a6-4095-8037-1b2180edcdb4.png)

**Comment by photopea** [comment]
I see what you mean, but this is how it works in Adobe Photoshop, and how most of users want it to work.

The same happens with vector shapes. If you draw a green shape with a blue stroke, the next shape will also have a green filll with the blue stroke. Same for text layers, etc.
