### ISSUE TITLE
Your browser is too old. Please, update it. Doesnt Open the Editor

### ISSUE THREAD

**Issue by Sakibthenoobcoder** [photopea/photopea#4134]
I use Microsoft Edge
Version 96.0.1054.57 (Official build) (64-bit)

It is the most updated version of Microsoft Edge. Still Photopea Doesn't Turn on rather it shows this Prompt.

![image](https://user-images.githubusercontent.com/88200560/146487736-017ccdfd-94b3-4379-a8d5-45cc848200b6.png)

**Comment by photopea** [comment]
We show this message, when the browser does not support WebAssembly. Usually, only old browsers don't support WebAssembly.

Did you disable WebAssembly somehow on purpose? You need a browser with WebAssembly to use Photopea.

**Comment by Sakibthenoobcoder** [comment]
I never tried to disable the Web assymbly

**Comment by photopea** [comment]
You probably enabled "Secure mode" or something. Disable it, or use a different browser, which works according to web standards:

https://www.zdnet.com/article/edge-super-duper-secure-mode-turns-off-the-javascript-jit-compiler-for-extra-security/

**Comment by Sakibthenoobcoder** [comment]
Still It does not work. I turned of the security option

**Comment by photopea** [comment]
Do you have any browser extensions? They could be doing it, too.

**Comment by Sakibthenoobcoder** [comment]
Sorry To disturb i just solved the problem. I just done a mistake in security
