### ISSUE TITLE
Empty folder in This Device problem

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4135]
After I double clicked on empty folder in This Device it did not open with message in console.
"Uncaught (in promise) DOMException: A requested file or directory could not be found at the time an operation was processed."
After that I tried to open normal file but it is no longer working and it is stuck on "Opening..." and the same error appears in console again. See screenshot (I double-clicked on folder Photos and then I double-clicked on icon_big.png several times)
![image](https://user-images.githubusercontent.com/6370548/146511539-3c8a4823-ff6a-4d2f-977a-f0865dc31cda.png)

**Comment by photopea** [comment]
I am sorry, it is fixed now.

**Comment by hxim** [comment]
Unfortunately it is not working in case of new created folder.
1.) right-click - New Folder and confirm with ENTER
2.) double click New Folder
3.) double click any file
4.) same problem as before - see screenshot
![image](https://user-images.githubusercontent.com/6370548/146555025-61cfe76e-921a-4b16-8e05-e00e08bca075.png)

**Comment by photopea** [comment]
sorry, it is fixed now :)
