### ISSUE TITLE
Antialiased selection produces pixel errors when deleting selected part of image

### ISSUE THREAD

**Issue by SebiTimeWaster** [photopea/photopea#4138]
![image](https://user-images.githubusercontent.com/3726309/146545289-8e8df5d5-326c-42b8-935b-a1332e190f7f.png)

the circle should be cut antialiased, but it produces no soft edges and these weird missing pixels in certain places:

![image](https://user-images.githubusercontent.com/3726309/146545411-0abb8f2c-da21-41f2-b3ca-f6f43556a878.png)

**Comment by photopea** [comment]
I do not know what you did. What should I do to see the problem myself?

**Comment by photopea** [comment]
Are you sure you know how pixels work?

If you draw a red circle on a black background, pixels "on the edge" will be brown. Do you want to select a brown pixel somehow, press Delete (which only changes the transparency) and turn a brown pixel into black?

**Comment by SebiTimeWaster** [comment]
ok, i removed the blue layer behind to make it more visible:

![image](https://user-images.githubusercontent.com/3726309/146556719-94c1521e-0253-4aca-afc1-1d31c8633935.png)

i just created a round selection positioned it over a picture and pressed delete.

none of the pixels at the edge are transparent and there are pixels missing in between.

**Comment by SebiTimeWaster** [comment]
it is not even following the outline it is showing me with the selection:

![image](https://user-images.githubusercontent.com/3726309/146557142-e69f9681-f778-4b0a-b341-6e0cc89f6ccf.png)

**Comment by photopea** [comment]
It is still not clear to me wha tyou did. What should I do to see the bug? When I delete a circular selection (I disabled "anti-alias"), it is deleted like this
![image](https://user-images.githubusercontent.com/15955558/146558693-ed24f78e-5f8c-4edf-9cda-8b0153422238.gif)
.

**Comment by SebiTimeWaster** [comment]
yes, if you disable antialiasing, it is correct. but i am talking about antialiased selections, as this is literally the first word in the title of my bug report.

**Comment by SebiTimeWaster** [comment]
the antialiased selection produces a dithered 1 bit representation of what should be an 8 bit transparency information.

**Comment by photopea** [comment]
If I enable antialiasing, deleting a selection looks like this.
![image (1)](https://user-images.githubusercontent.com/15955558/146570715-001d09b6-8dd4-4bd7-9396-711e93995854.gif)

**Comment by SebiTimeWaster** [comment]
trying to recreate the bug i managed to get the bug 2 out of 10 times. you have an intermittent problem there. on every try i did the same thing.

**Comment by photopea** [comment]
Are you using the Brave browser? Did you try to use a normal browser with no browser extensions?
