### ISSUE TITLE
Export SVG

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#414]
Hi,

nice function should be export with minify source code of SVG and convert inline styles to classes. For example:

This:
```
<path id="Layer" style="fill: #d6005d" ... >
```
To:
```
<style type="text/css">
<![CDATA[
.p1 {fill: #d6005d}
]]>
</style>
<path id="Layer" class="p1" ... >
```

It's better for CSS styling.

**Comment by photopea** [comment]
But in this case, each element would have a different class. Or do you mean also detecting the same styles for different elements?

**Comment by landsman** [comment]
I mean replace all inline styles to classes. Its comfortable for front-end coders. They don't need edit manually source of svg anymore with this feature :)

**Comment by photopea** [comment]
Done :)
