### ISSUE TITLE
Another issue on This Device screen

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4141]
I clicked twice very quickly (like double click but I moved my mouse cursor in between first and second click).
First click was on empty space below "template.psd" file in This Device screen.
Second click was slightly higher on "template.psd" file in This Device screen.
Error appeared in console and "Opening..." message is stuck on screen.
![image](https://user-images.githubusercontent.com/6370548/146639869-6b61b7f3-ab70-416a-92ab-42b6cea954a8.png)

**Comment by photopea** [comment]
fixed, thanks! :)
