### ISSUE TITLE
Bug: Angle adjustments on the Live Shape that merged by multiple Live Shapes work improperly

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4143]
**To reproduce:**

1. Create a shape by Rectangle tool.
2. Duplicate it by pressing Ctrl + J.
3. Merge them by pressing Ctrl + E.
4. Adjust the angle in Properties > Live Shape.

**What happened**

- Inputting a value and pressing Enter, the shape rotated but the value in textbox didn't change.
- Dragging and holding slider, the shape rotated quickly, and kept rotating when you stopped dragging but kept holding slider. And the slider wasn't being dragged visually.

**Comment by photopea** [comment]
I am not able to reproduce it now :(

Each live shape has its own angle. If you select multiple live shapes, you can e.g. add 20 degrees to an angle of each shape. But there is nothing like "an angle of two shapes".
