### ISSUE TITLE
Icon for dotted stroke for the shape has a wrong representation (line)

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#4144]
![obraz](https://user-images.githubusercontent.com/38118273/146745613-9d960206-7966-4d08-9159-7a688614c92d.png)

And I think that dashed line can be better too (longer dashes and bigger spaces).

**Comment by photopea** [comment]
Ok, I have made the line thicker. These are only two pre-defined configurations for Dashes. You can create lots of other configurations by typing the pattern yourself.
