### ISSUE TITLE
Export multiple PNGs with text strings as a bulk

### ISSUE THREAD

**Issue by Polzavatel** [photopea/photopea#4145]
I have an excel file with several text strings, which I'd like to add to every image and export in PNG format in bulk.
Can you help me with that?
Thanks.

**Comment by photopea** [comment]
Photopea can not open excel files :( but maybe you can create a script, which will do it for you. 

Or maybe this can be useful: https://fishtrone.wordpress.com/2019/02/25/generating-images-from-code-with-photopea/

**Comment by photopea** [comment]
BTW. it is not a bug in Photopea, you should not discuss it here. You can ask about help e.g. on our Reddit: https://www.reddit.com/r/photopea

**Comment by MichalSZZ** [comment]
If I good understood - he would like to have feature like in Photoshop that you can find in that place 
![obraz](https://user-images.githubusercontent.com/38118273/146792201-77051c5e-abf9-4fec-83ae-4ee82633394a.png)

But yes,in Photoshop you have to sync the PSD file with .txt or .csv file with data set. In Photopea there are plugin for Charts that can generate charts when you import your data to window. Maybe as a plugin it can be possible?
![obraz](https://user-images.githubusercontent.com/38118273/146793185-f8b15803-56ff-45d1-926a-b3329af41f12.png)

This week I will have to use that function in Photoshop to do certificates for ~500 people. But I have software to do that.

**Comment by photopea** [comment]
I think somebody asked for the Variables feature before, but I thought it is not that important.

**Comment by MichalSZZ** [comment]
Ok you can think about it if you have some more important thing on your to-do list. But please add this feature on that list :)

I use it very rarely. But without that feature making diplomas or any other automation could be a big problem.

Variables is one thing but batch processing with naming files and saving copies are another thing.

If you will have an option (and full support) to use File System API for saving multiple files. You should thing about batch processing files from user folder. And than add Variables

**Comment by photopea** [comment]
I never used batch processing in Adobe Photoshop. It is possible now with our storages "on the left" (This Device, Google Drive, Dropbox). Where should I start? Can you describe the most basic workflow, how you batch-process files  in Photoshop or some other program?

**Comment by MichalSZZ** [comment]
Yes but maybe it will be better to create a new issue for that?
Batch processing is a some kind of final part for exporting files with variables.

I used it with actions too. In batch processing you can point what action should to be used.

for example:

- adding watermark layer to photos, scaling down and exporting as JPG with they own compression.  (when you want to give your client samples from photo session (now it can be done with lightroom I guess...)
- cropping photos to squares and saving hundreds of it
- adding borders to photos
- renaming photos (it can be done in any of those points above)
- adding specific look to Photos (by color corrections, LUTs or actions)

I am not using that function very oft in my job now.

Workflow can be like this.

1. Record some action and save it.
2. Open Batch processing dialog window (File->Automation->Batch)
3. Choose that action that should be added in batch processing
4. Choose source folder with your files
5. Chose destination folder
6. Set the proper naming of files that you want to have (there can be presets for it for easily naming)

**Comment by photopea** [comment]
File->Automation->Batch is for applying actions on files. You can not even open that window, if there are no Actions.

Now, I think maybe we should offer some simple, basic, yet useful actions in Photopea. Just as we offer LUTs.

Do you know where I could find a set of such "default" actions? Or could you create one for us?

**Comment by MichalSZZ** [comment]
@photopea I will create an issue for that (some basic actions). But that should be an issue (place) for everyone who want to add some actions to Photopea.

And one more thing - as you mentioned above - Batch is for applying actions. But could you look on "File -> Script -> Image prcessor"? I think it a functionality that can be done with or without actions added to exported files.

**Comment by photopea** [comment]
I have implemented Image - Variables. It works similarly to Adobe Photoshop, except if you want to use images, you should load them through a special button (as Photopea can not access your hard drive).

You can try it out on this PSD: https://www.photopea.com/#i9PNZAEuk , you can use the set of images attached below
[flags.zip](https://github.com/photopea/photopea/files/7876044/flags.zip)

**Comment by MichalSZZ** [comment]
Hi. I just tested your sample and it works!
But someone should to do a tutorial for this because it is hard to understand for beginners without any sample file. 

It will be great for certificates for students.

**Comment by photopea** [comment]
What about Youtube tutorials for Photoshop? Will they work? Or I can write it into Photopea.com/learn

**Comment by MichalSZZ** [comment]
I have no problem wirh reading, even in english, but we live in 2022 and almost everyone are looking video tutorials on YT. It can by on YT and in learn section too. But I like video tutorials when you can see everything.
My speaking skills in english are very poor. Maybe you can ask someone from Photopea Pro to do such a tutorial?

**Comment by photopea** [comment]
I wrote a manual for Variables in Photopea: https://www.photopea.com/learn/variables . We probably do not need a video tutorial now.
