### ISSUE TITLE
Zeus Plugin

### ISSUE THREAD

**Issue by yikuansun** [photopea/photopea#4146]
Hi,

I have made this plugin:
```
{
    "name"  : "Zeus",
    "url"   : "https://yikuansun.github.io/lightning-experiment/?photopeaPlugin=yes",
    "icon"  : "https://yikuansun.github.io/lightning-experiment/icon.png"
}
```
It is just a simple lightning renderer which generates overlays that can be used in photo manipulations and other graphics.

I was wondering if you could add it to Photopea?

Thanks!

**Comment by photopea** [comment]
What if we call it "Lightning Maker", so that it is more clear what it is? Also, people will be able to find it by pressing the "?" at the top.

**Comment by yikuansun** [comment]
That would be fine.
Perhaps we could have a combination of the two, like "Zeus - Lightning Maker," or "Zeus - Lightning FX," to give it more identity? I also have Zeus as a standalone app, so it would reflect that.

**Comment by photopea** [comment]
Ok, I have added it to Photopea. BTW. the inserted smart object looks quite blurry each time.

**Comment by photopea** [comment]
Look at this: https://www.reddit.com/r/photopea/comments/ry7284/zeus_lightning_maker/

**Comment by yikuansun** [comment]
Sure, I'll change that. Thanks for bringing it to my attention!

**Comment by yikuansun** [comment]
I've handled it and replied to the person on Reddit.

**Comment by yikuansun** [comment]
> the inserted smart object looks quite blurry each time.

I used to use Gaussian for the softness algorithm, which made it look blurry, but I switched to Box Blur and it now it looks a little nicer.

**Comment by yikuansun** [comment]
Hi @photopea ,

I tried to move Zeus to the Plugins panel, but for some reason it shows up in the Add Plugins manager but not in All Plugins (where others can install it). (I have ensured that Make Public is checked.) This is especially strange because I've succeeded in uploading other plugins in the past.
Could you please take a look at the database to see if there is a bug?

Thanks!

**Comment by photopea** [comment]
It seems like you have provided the same JSON file for "Zeus - Electric Energy FX" and "Sprite Replicator". Photopea removes duplicities when creating a final list of plugins. The same goes for templates (if two of your templates have the same "File" value, only one will be published).

Please, provide a different JSON for the "Zeus - Electric Energy FX".

**Comment by yikuansun** [comment]
I see. That is my fault, sorry.
Do you think you could add a `textarea` below the file upload button, so we can preview and modify the data easier?
