### ISSUE TITLE
Bug: Photopea doesn't close a google ad after google closes it

### ISSUE THREAD

**Issue by rocifier** [photopea/photopea#4149]
As per image below, when google closes an ad, I would expect photopea to also close the advertisement freeing up precious screen real-estate:

![image](https://user-images.githubusercontent.com/1772304/146930621-87cace81-9727-42d4-ae2e-7535b6519b1d.png)

This can be reproduced by clicking the close button on the advertisement and providing a valid reason to google.

**Comment by photopea** [comment]
If anyone could remove ads so easily, we would not make any money at all :(  Also, there would be no point in paying for Photopea Premium, if you could use 100% of your monitor in the free version.

**Comment by rocifier** [comment]
I see. I thought the ads were pay per click. If it's pay per impression then it makes sense to keep a rotation going there. When I click close I am telling google 100% I will not be clicking on the ad - it doesn't even let me see it!
