### ISSUE TITLE
Error Code When using MS Edge Dev Edition

### ISSUE THREAD

**Issue by PCRacer** [photopea/photopea#4150]
![PhotoPea](https://user-images.githubusercontent.com/96520393/147062402-b7f09afb-4dac-4374-9cf6-8ac2ba66f5ab.png)

I am getting this error message in Microsoft Edge Developer's edition...

**current version I am using: v98.0.1100.3**

**Comment by photopea** [comment]
This means, that WebAssembly is not available in your browser. Usually, it is not available in old browsers.

Enable WASM in your browser, or use a different browser. Photopea can not work without it. Photopea works great in regular MS Edge in my case.
