### ISSUE TITLE
Bug: Hand, Zoom In and Zoom Out in Liquify become eraser after pressed Ctrl, Shift or Alt

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4151]
**To Reproduce**

1. Create a new project.
2. Open the Liquify window.
3. Select Hand, Zoom In or Zoom Out.
4. Press Ctrl, Shift or Alt.
5. Draw on image.

**What happened**

The image is erased.

**Comment by photopea** [comment]
fixed, thanks for reporting :)
