### ISSUE TITLE
Request: Hold Alt to switch to rebuild, shrink, blow temporarily in Liquify

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4153]
Now in Photopea we can hold Alt to "push to right", "twirl anticlockwise" when selected "push to left", "twirl". That works same as in Photoshop. 

In Photoshop, we can also hold Alt to:
1. Switch to rebuild when selected smudge.
2. Switch to shrink when selected blow.
3. Switch to blow when selected shrink.

Can these features be added into Photopea too?

**Comment by photopea** [comment]
Done :)
