### ISSUE TITLE
PDF don't display correctly

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4154]
![image](https://user-images.githubusercontent.com/11801254/147146706-8f8ccfae-6aeb-4529-be36-9edeaa5bfa5c.png)

I don't get the numbers when i add this PDF to my existing project:
[Soi Terrible Cuentero - EAN-13-0731299197507.pdf](https://github.com/photopea/photopea/files/7764842/Soi.Terrible.Cuentero.-.EAN-13-0731299197507.pdf)

**Comment by photopea** [comment]
This is a known issue, when you place a PDF or an SVG with text into another document.

All current mechanisms expect, that the file will be placed and rendered immediately. However, Photopea might need several seconds to download necessary fonts.

For now, you can "fix" it by opening the smart object, waiting for the text to be rendered, and save + close.

**Comment by avagp** [comment]
I did that.  But seemed like a work around for a bug, that is why i reported

**Comment by photopea** [comment]
Ok I have finally fixed it :)
