### ISSUE TITLE
Photopea Not Working

### ISSUE THREAD

**Issue by JunoJog** [photopea/photopea#4155]
Photopea doesn't work on my certain gmail account, but works on my other one when I switch accounts in chrome. It seems like the one that works is updated somehow.. how can I update it on my other gmail?

**Comment by photopea** [comment]
Hi, what do you mean by "owrking on your account"? You are supposed to open www.Photopea.com and use it, there is no need to create any account.

If you are logging in to Photopea, could you clear your browser cache and cookies for Photopea.com ?

**Comment by JunoJog** [comment]
I clearly said on a certain GMAIL account in chrome.. Whenever I switch google chrome accounts, it works. And I even tried to clear browser cache and cookies for it and it still doesn't work.

**Comment by photopea** [comment]
So what happens when you open www.Photopea.com ? Do you see a white screen? Or what do you mean by "not working"?

**Comment by GAH282wind** [comment]
I see a  white screen help me in chrome it loads but there is a white screen

**Comment by photopea** [comment]
Are you in India? Someone reported they can not open Photopea from India.

**Comment by GAH282wind** [comment]
why I can't use it in India I need it for work. and this is for only me are for full India

**Comment by GAH282wind** [comment]
and yes I am in India

**Comment by photopea** [comment]
There are 10,000 people from India, who used Photopea today.

You should ask your internet provider why they are blocking Photopea for you. Ask your friends if they can open www.Photopea.com , I am sure they can.

**Comment by GAH282wind** [comment]
No problem. now it's working and thanks.
