### ISSUE TITLE
Artboard - Duplicate glitch

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4156]
https://www.photopea.com/#i6kLjPvWB

When i duplicate the last artboard from the PSD above:
![image](https://user-images.githubusercontent.com/11801254/147185374-fc9b168f-ddfb-4218-b110-0c4994ed981d.png)

I get this:
![image](https://user-images.githubusercontent.com/11801254/147185404-5ac3f055-e1e2-407b-bbf0-0250238e14ee.png)

I duplicate the artboard by clicking Alt+Click on the (+) button

**Comment by photopea** [comment]
It should be fixed now :) it was related to WebGL (your WebGL can not handle textures larger than 16384 pixels). Now, Photopea will disable WebGL if you make your document that large.

**Comment by avagp** [comment]
fine, now it works.

But what issue or complications i will have when WEBGL is deactivated?

**Comment by photopea** [comment]
Photopea should work identically with WebGL enabled and disabled.

Photopea will be much slower without WebGL. I do not recommend disabling it.
