### ISSUE TITLE
Extras automaticaly activating

### ISSUE THREAD

**Issue by abdlkrmdlgr** [photopea/photopea#4158]
when i use Magic Wand Tool, view->extras automaticaly activating.  after that if i uncheck extras menus, it's deselecting all magic wand's selection

**Comment by photopea** [comment]
Extras are hiding all elements on top of the image (guides, grid, selection, slices, ...). Do you want to make selections with a magic wand, and not see them?

**Comment by abdlkrmdlgr** [comment]
Ok, didn't show again after unchecked it. thanks a lot.

**Comment by laukstein** [comment]
@photopea This issue is happening again. Now when selecting anything.

**Comment by laukstein** [comment]
@photopea This is still happening, and is confusing, feels like a bug.

**Comment by photopea** [comment]
If you disable "extras", the selection is not visualized above the document, but it still is there.

So we must enable extras when the user makes a selection, because the user needs to see what has been selected.

You should use Select - Deselect to deselect.
