### ISSUE TITLE
Unable to open the colour palette

### ISSUE THREAD

**Issue by jonatanelgstrom** [photopea/photopea#4159]
I just got this bug which is a first for me where I can't open the colour palette.
I'm clicking, double clicking, right clicking all that stuff on the black square and nothing is happening, I can switch to the white secondary colour but that one can't be opened either.

Not sure how this happened, all I know is that I had two different Photopea tabs open and when I finished the second one and closed that and went back to work on the first, I found that I could not select any colours.

**Comment by photopea** [comment]
Do you mean opening a Color Picker window? We do not have any color palette.

Do you log in to Photopea (is the "Account" button orange)? I just tried to open two tabs of Photopea.com and paint in them, but there is no such problem :(

**Comment by jonatanelgstrom** [comment]
Yes sorry, I meant the colour picker.

I can open the colour picker now when I have opened a new tab, so not sure what happened there

**Comment by photopea** [comment]
What if you close all Photopea tabs? Are you still not able to open it in some case?

**Comment by jonatanelgstrom** [comment]
No it's working again, I'm guessing something went wrong on that tab itself
