### ISSUE TITLE
Does photopea not work well with certain browsers or laptop brands?

### ISSUE THREAD

**Issue by Jykie** [photopea/photopea#4164]
Hi, I was wondering if there are certain browsers or laptop models that doesn't work well with Photopea? I'm asking since I want to upgrade to a new laptop and I want one that can handle photopea and not lag or freeze when using multiple layers and large canvas sizes for my photo editing.

**Comment by photopea** [comment]
The better device you have (faster CPU, faster GPU, more RAM), the better it should work. Be aware of the Alt+click issue on Chromebooks https://www.photopea.com/tuts/alt-click-problem-on-chromebooks/  and the command key issue on Macbooks. These issues affect all the software, not only Photopea.
