### ISSUE TITLE
Request: Make the icons of locks and filters smaller

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4167]
Could you please make them the same size as the icons at the bottom of Layers panel? They are now as big as the icons in the toolbar. It is a bit crowded. 
![screenshot_20211228_034745](https://user-images.githubusercontent.com/79258245/147503291-45c81a8a-a381-4ac6-a9e4-9b88be761626.jpg)

**Comment by photopea** [comment]
I have made these icons 25% smaller.

**Comment by nothingshiru** [comment]
The background of icon(clickable area) doesn't need to be smaller.

**Comment by nothingshiru** [comment]
Hi. Could you change it?

**Comment by photopea** [comment]
Sorry, it would be too hard :(
