### ISSUE TITLE
Path's stroke inccorectly displayed

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4168]
i was wondering why this happened:
![image](https://user-images.githubusercontent.com/11801254/147506088-a132ded6-da23-4709-a1bf-508bd460e561.png)

Is this an intended behaviour?

https://www.photopea.com/#i1oEUHLre

it is a composed path with over 20 parts inside, and all are now merged, but when i enable stroke, some of them gets the stroke property

**Comment by photopea** [comment]
I think it is some extreme case, where our vector merger can not merge the objects properly.

what exactly do you want to be stroked? In Photoshop and Photopea, only the outline of a shape is stroked. If you want to stroke each polygon, put them into separate layers.  Otherwise, make polygons cover each other, or make a tiny hole between them.

**Comment by avagp** [comment]
yes, that is exactly the behaviour i want.

If the shape is all together, then only stroke the outline.

But if it is separated, stroke each piece.

But in this particular case, is all together, and it strokes some of the shapes. SSo it is very weird.

**Comment by photopea** [comment]
This is how your PNG is rendered in Adobe Photoshop. Do you want it to look like this? 
![box](https://user-images.githubusercontent.com/15955558/147553134-9b4af479-ffcd-41be-aebc-7d304ea18192.png)

**Comment by photopea** [comment]
Maybe you can make two copies, one with fill-only, another with stroke-only.

**Comment by avagp** [comment]
I am really surprised that this shape looks so weird.

Let me ask you something:

Can you make this shape have stroked only the outline and having only one shape?

**Comment by avagp** [comment]
Now i get it!
![image](https://user-images.githubusercontent.com/11801254/147579149-40bf1e45-f94e-4141-88b4-2bfad8a414b6.png)

![image](https://user-images.githubusercontent.com/11801254/147579153-a174aa00-48d5-4881-97a7-9af422058ae6.png)

The shapes where milimetrically "separated"

**Comment by photopea** [comment]
In Adobe Photoshop, you can not have two rectangles "touching each other", and both of them being stroked.

**Comment by avagp** [comment]
Yes! thats good to know know

**Comment by avagp** [comment]
I have found a bug related to this, i will fill another issue
