### ISSUE TITLE
Vectorize bitmap unite separateed layers

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4169]
I use vectorize bitmap a lot.

And i have encounter this problem many time. And most of the time i fix it manually, but now it too much work.

So, the problem is, that sometimes the vectorized image get shared layer paths between different shapes.

For example, this doodle:
![Fondo Doodle](https://user-images.githubusercontent.com/11801254/147506925-f840fd53-f38e-4f49-a719-da7976382a5b.jpg)

Whe it is vectorized some doodles get share the same path payer, making impossible to handle them separately, as you can see here:
![image](https://user-images.githubusercontent.com/11801254/147507036-961d433b-f495-48d9-8637-211cc4e38c61.png)

So, this could be fixed somehow? That separated drawings get separated path layers?

**Comment by photopea** [comment]
Have you tried to delete the white color with the magic wand? Or I can add a checkbox "delete white color". Is that what you want?

**Comment by photopea** [comment]
If there is a black circle A, and a white circle B inside A, and a black circle C inside B, it is impossible to tell, if C is "on top of B", or if C is a hole in B, and you see A through it.

**Comment by avagp** [comment]
No, my point is about how the feature group the shapes together

Here is a video
![image](https://user-images.githubusercontent.com/11801254/147524534-e14aabf2-7c43-4cb0-9ed9-63f1e1692952.png)

**Comment by photopea** [comment]
Your video is from July :(

Can you maybe show me a simplified PNG, and a PSD which Photopea gives you, and a PSD of what you want to have (make it manually)?

**Comment by avagp** [comment]
Sorry, i gave you the wrong URL for the video:
https://video.drift.com/v/abP0dPhp6e8/

Try that, and if you need a simplified version, please ask me

**Comment by photopea** [comment]
I thought that there is always one object that is vectorized, so I decided to merge parts of the same color, to keep the number of layers small.

You see, that in your vectorization, you get 293 layers. If we do not merge paths, you could get 3000 layers. What if I add a checkbox "combine parts of the same color"?

**Comment by avagp** [comment]
But if now same colors are merged, why not all white is the same layer?

I would totally like to have that feature, then i will merge the ones i need myself.

**Comment by photopea** [comment]
I have fixed it, the resulting layers should be much "nicer" now :)

If you enable "Merge colors", it should merge much more shapes, and give you less layers as the result. I did a test with some photo, the result had 1228 layers. Now, the same vectorization is converted into 49 layers.

If you disable "Merge colors", every layer has "inner parts" as layers right on top of it, so it should be easier to find related parts. Parts, that are surrounded by the same part (which is still surrounded by some part) are also merged.

**Comment by avagp** [comment]
Ok, it is better for me with the new option to not merge colors. Thanks!

But still, can you please check this image ( https://www.photopea.com/#iNM37VJoL ) and how it cluster the colors?

There are weird color groups

**Comment by photopea** [comment]
I guess that is the result with "merge colors" enabled. Do you think you can cluster it better? How many layers do you think you can get?

**Comment by photopea** [comment]
BTW. I get much better result, if I vectorize black-and-white, and remove the background layer at the end: https://www.photopea.com/#ipJK_MuaM

But I think it is impossible to have it in less than six layers.

**Comment by avagp** [comment]
![image](https://user-images.githubusercontent.com/11801254/147698221-bef3032e-3bc9-49e4-8317-74f435b673c7.png)


For example, why those layers are not merged with the other white layers??

**Comment by avagp** [comment]
I am understanding how you process the image.

I get why those are not, because those are more "inside" or "over" the other colors.

Seems very good to be honest :)

Thanks for such improvement

**Comment by photopea** [comment]
Two white layers are not merged together, because they are on top of each other, and there is a black layer between them.

**Comment by avagp** [comment]
i thought it was that :)

Then let's close this issue
