### ISSUE TITLE
Can't delete a layer by using the delete key

### ISSUE THREAD

**Issue by kiran-vemuri** [photopea/photopea#417]
Env: Firefox quantum on macOS High Sierra

https://github.com/photopea/photopea/issues/416 ended up creating a bunch of layers/shapes. When I select the layer/shape and hit the delete button, it throws an error `layer not editable`. But if I right click and delete, I can delete that shape.

**Comment by photopea** [comment]
The Delete key is used for deleting selected pixels. Since you tried to delete pixels from a vector shape, it does not work. Please read this to learn about deleting layers: https://www.photopea.com/learn/layers
