### ISSUE TITLE
Shape opens when an anchor is deleted

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4170]
Check this psd:
https://www.photopea.com/#irCb4yBfN

It as a closed shape, but if you delete one anchor, it opens itself
![image](https://user-images.githubusercontent.com/11801254/147512893-16ee8383-0d1b-4da7-8b66-94dcde744097.png)

![image](https://user-images.githubusercontent.com/11801254/147512894-36c4a9f0-7423-41ef-b88b-e872e9279b78.png)

**Comment by photopea** [comment]
That is how it works in Adobe Photoshop. You should right-click the anchor point and choose "Remove Anchor Point", to delete it without disconnecting.

**Comment by avagp** [comment]
So, "remove anchor point, is not the same as hitting backspace on the keyboard?

**Comment by photopea** [comment]
Yes, see https://github.com/photopea/photopea/issues/4062

**Comment by avagp** [comment]
Ok, IT WAS the same.

Now i see, so all fine :)
