### ISSUE TITLE
Merge Folder with only paths

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4171]
Can i ask that if a folder, with solely path layers, is merged, the final layer is still a path, rather than a bitmap?

This happens a lot to me, and i have to open every folder and select all the paths inside, then merge it, because if i merge it from the folder i get a normal layer

😬

**Comment by avagp** [comment]
Can this be done? Or it is against the laws of Photoshop? :)

**Comment by photopea** [comment]
Sometimes, each path has a different fill / stroke, or they have layer stlyes, masks, etc. I will add a separate option "Merge Shapes" next to "Merge Layers".

**Comment by avagp** [comment]
Good! :D
Thank you Thank you Thank you Thank you !

**Comment by avagp** [comment]
Where i can find this new option??

**Comment by photopea** [comment]
I have added it to "Merge Layers", which should work as you want now :)

**Comment by photopea** [comment]
You should still use the "Merge Layers", there is no "Merge Shapes". But it should merge folders now.

**Comment by avagp** [comment]
When i merge this folder full of shapes, i get a bitmap  :/

**Comment by photopea** [comment]
I am so sorry :( it should be fixed now.

**Comment by avagp** [comment]
Yes, it is fixed now :)

Thanks
