### ISSUE TITLE
Vectorize bitmap does not display anything

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4172]
![image](https://user-images.githubusercontent.com/11801254/147515905-8fd29711-4683-45ce-9c14-4eac259092a5.png)

This particular image i don't get any vector, on that configuration

**Comment by klade-png** [comment]
maybe use inkscape or something to vectorize there then import it into photopea?

**Comment by avagp** [comment]
Still happens, when i deselect reduce noise.
![Screenshot 2022-01-18 11 27 58](https://user-images.githubusercontent.com/11801254/149956333-3f232049-5dcb-47b7-9642-f454caafd531.png)
![Screenshot 2022-01-18 11 27 44](https://user-images.githubusercontent.com/11801254/149956338-2c9dfcde-6335-49a9-81e5-116806f9876b.png)

Here si the image:
![image (8)](https://user-images.githubusercontent.com/11801254/149956327-3d98fd59-00e0-4b73-8327-c914fb390bb4.png)

Why this happens?

**Comment by avagp** [comment]
Why this happens??

**Comment by photopea** [comment]
You want to find the best two colors. The "Cartoon" mode goes through the image and looks for colors, such that there is a 3x3 pixel square area with the same color (this color is added to a palette).  Cartoons usually contain a 3x3 square with the same color.

Your image contains only a 3x3 area of transparent color. There is no 3x3 area with the same shade of black / gray in your case. I made Photopea switch to a Photo mode, if the Cartoon mode finds less than two colors.

BTW. I recommend increasing the contrast in images as yours (make blacks darker and whites brighter) before vectorizing or erasing the background.

**Comment by avagp** [comment]
I have not modified the image, so you say this set is actually 'Photo'?:
![image](https://user-images.githubusercontent.com/11801254/151049921-ffb76554-dacd-44fe-98ca-d85139900994.png)

**Comment by avagp** [comment]
Btw i was very surprised, that in fact the image did not have any 3x3 same shade of black/grey.

When i used the eye dropper i could see it.

Thanks for the complete explanation, that will help me on the future
