### ISSUE TITLE
Auto refresh page and all work reset

### ISSUE THREAD

**Issue by i3bdulaal** [photopea/photopea#4173]
Hi

As I mentioned in the title

Photopea page auto refresh after several minutes and I lost all my works

This problem happed when you update the menu to the new one

Wish this problem fixed soon

Its high priority 

Thanks

**Comment by i3bdulaal** [comment]
> Hi, Photopea should never "auto refresh". What should I do to see Photopea "auto refresh"?

As I'm using it on Safari you can try to open any project and try to do some steps and just wait few minutes it auto refresh the page.

For now I'm using other Chrome because I think this problem in Safari to save memory.

Wish this problem on Safari only because its so bad if happened on all browser

Thank you

**Comment by photopea** [comment]
You should be able to change the settings of your browser. If a browser closes websites without asking you, it is definitely wrong. Maybe this can help you: https://apple.stackexchange.com/questions/1264/is-there-a-way-to-disable-web-page-auto-refresh-in-safari

**Comment by i3bdulaal** [comment]
> https://apple.stackexchange.com/questions/1264/is-there-a-way-to-disable-web-page-auto-refresh-in-safari

Thanks for reply 

i did solution

Wish problem resolved

Thanks
