### ISSUE TITLE
Transform - lost focus on X & Y with the keyboard

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4174]
When selecting a layer and then transform it to move it around.

If you click the angle input, you can increase or decrease the number by using the arrow keys.
![image](https://user-images.githubusercontent.com/11801254/147579639-a9ddbae2-a555-4ae0-b8cd-9a05e41cf373.png)

But this is not possible with the position inputs X & Y.
![image](https://user-images.githubusercontent.com/11801254/147579727-b4e3279f-3ee4-40d8-bf34-a840549dbebc.png)

If you click the input and use the arrow keys, only the first hit changed the parameter, but the n ext one, will move the layer.

Example:
Create a layer
press Ctrl+T to transform
Select X input
Press down arrow key thrice

It will move one step left, and 2 steps down.

Is this intended? Because doesn't feels like

**Comment by photopea** [comment]
it should be fixed now.
