### ISSUE TITLE
Photopea Lags and Freezes when i have too many layers

### ISSUE THREAD

**Issue by Jykie** [photopea/photopea#4175]
I find photopea starts to lag badly when I have a lot of layers in my project when working on a small canvas (1080x1080), and if I'm working on a larger canvas (3000x5000), it lags straight from the start of editing. I also found that if I try to upload the project file back into photopea to continue editing, the website immediately freezes, and eventually crash. Is there a way I can fix these issues?

**Comment by photopea** [comment]
Hi, how old is your computer? how much RAM do you have? Is your WebGL on? You can check it in More - Use WebGL.

**Comment by Jykie** [comment]
My laptop is about 3 years old, Installed Ram is 4.00 GB (3.83 GB usable), and the chrome://gpu site says Hardware Accelerated next to webGL. I don't know if that means it's on.

**Comment by photopea** [comment]
4 GB of RAM might be not enough for certain documents. Do you have other programs or browser tabs running while using Photopea?

Can you describe steps, which always make Photopea crash on your computer?

**Comment by Jykie** [comment]
I do photo manipulation so I cant really explain the steps since it varies project to project. And usually I have a couple tabs open to look for stock images as I'm working, as well as YouTube. But I don't run any other programs, and I make sure I don't have any miscellaneous tabs open. Only the ones that I need.

**Comment by photopea** [comment]
If your document is 3000x5000, and you have lots of layers, 4 GB of RAM might not be enough.

I don't know what else I can recommend it. Buy a better computer, or save your work every 15 minutes, in case your browser decides that Photopea uses too much RAM and kills it.

**Comment by Mario28412** [comment]
> 4 GB of RAM might be not enough for certain documents. Do you have other programs or browser tabs running while using Photopea?
> 
> Can you describe steps, which always make Photopea crash on your computer?

i have 16 RAM , i7-11700f and rtx 2060 6 g , i have so much lag in app in browser and like a app also

**Comment by camoody1** [comment]
> > 4 GB of RAM might be not enough for certain documents. Do you have other programs or browser tabs running while using Photopea?
> > Can you describe steps, which always make Photopea crash on your computer?
> 
> i have 16 RAM , i7-11700f and rtx 2060 6 g , i have so much lag in app in browser and like a app also

Record a short video showing the extreme lag in Photopea and what you have open while doing it. Those PC specs are better than mine and I really don't have any "lag" to speak of.🤷🏽‍♂️
