### ISSUE TITLE
Action buttons out of proportion

### ISSUE THREAD

**Issue by BramNUFC** [photopea/photopea#4176]
I just noticed these 3 icons are a lot bigger than the other 3?
![Knipsel](https://user-images.githubusercontent.com/96789352/147590468-9c6c2d7b-c1a1-4ba5-9b32-93ea5ff08c0e.JPG)

**Comment by photopea** [comment]
I am very sorry, it is fixed now.

**Comment by BramNUFC** [comment]
> I am very sorry, it is fixed now.

Thanks!
