### ISSUE TITLE
Margins on text are incorrect when using anything other than left alignment

### ISSUE THREAD

**Issue by syegulalp** [photopea/photopea#4177]
If I create a text block and set the left and right margins of the text inside, it provides the appropriate spacing as long as the text is left-aligned. Setting the text alignment to anything else causes the text margins to be rendered wrong.

120px margin on both sides, left-aligned

![image](https://user-images.githubusercontent.com/401657/147707365-1ff9b38d-cda2-4676-95cf-b5f2bdfea3f1.png)

120px margin on both sides, justified

![image](https://user-images.githubusercontent.com/401657/147707409-bad0410f-518d-4d34-a531-2bdbd1b22099.png)

**Comment by photopea** [comment]
Hi, that is quite a serious bug! Thanks a lot for finding it. I have fixed it.
