### ISSUE TITLE
Inner Glow not working properly.

### ISSUE THREAD

**Issue by BasedChadWriter** [photopea/photopea#4178]
So I wanted to make a fantasy map using Photopea, and I needed to add inner glow, so I clicked it, and it darkened my first layered (because it was selected) and not just the edge of it. Can anyone help me?

**Comment by photopea** [comment]
I don't know what you did, but what makes you think it should do something different?

Our effects work similarly to Adobe Photoshop. You can buy a book about Photoshop to learn the meaning of each effect.

**Comment by BasedChadWriter** [comment]
Hello, I made a mistake while painting, and I put a transparent black cover over the layer, so I apologise.

**Comment by BasedChadWriter** [comment]
I accidentally painted the whole layer with transparent black, so it didn't work, fixed it!
