### ISSUE TITLE
PDF does not load correctly - missing data

### ISSUE THREAD

**Issue by kappische** [photopea/photopea#4179]
Seems like some data is not read, like the roof tiles on this pdf.

Open the file in a pdf reader and you can see the correct result
[A-40-3-100.pdf](https://github.com/photopea/photopea/files/7791928/A-40-3-100.pdf)

**Comment by photopea** [comment]
I think the roof is using "vector patterns". Photopea has no analogy for vector patterns, so we can not extract them from PDF files, sorry :(
