### ISSUE TITLE
Improve zoom/magnify controls

### ISSUE THREAD

**Issue by kiran-vemuri** [photopea/photopea#418]
* Hitting Ctrl+ does nothing
* Hitting Ctrl- makes the image smaller (Zoom out)
  * Subsequent Ctrl- and Ctrl+ icons only do zoom out
* The magnifying lens icon on the left side only does zoom in/magnify
* There's no magnifying lens icon to do zoom out.

**Comment by photopea** [comment]
So you are saying, that Ctrl and + don't zoom out. What device and a browser do you have? Does it have multiple plus keys?
Read this: https://www.photopea.com/learn/navigation  to find out how the Zoom tool works (basically, you can just hold Alt to switch between zoomin gin and out).

**Comment by kiran-vemuri** [comment]
Currently on FF Quantum, macOS High Sierra on a 2015 MBP. Single +/- Keys.

* Alt key works 👍 

Issue:
* Ctrl- does zoom out
* Ctrl+ does nothing

**Comment by photopea** [comment]
This is really strange. Can you please go here: http://jsfiddle.net/p45f44zb/3/ , click on the bottom right area, and press some keys? It should show the keys that are currently pressed on the keyboard.

What do you see when you press Ctrl and + ?

**Comment by photopea** [comment]
I have to close it because of lack of details.
