### ISSUE TITLE
File in this device folder saved wrong

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4180]
I opened from This device file named "template.psd" located in folder "Nová složka" with double click.
1.) Photopea shows its name as "Nová složkatemplate.psd" instead of just "template.psd"
2.) I modified this picture and when I tried to save it with File-Save(This Device) it saved into root folder insted of folder "Nová složka" and with wrong name "Nová složkatemplate.psd" see screenshots:
![image](https://user-images.githubusercontent.com/6370548/147734239-9e7d73dd-e0a9-43db-9291-6796e7d706d0.png)
![image](https://user-images.githubusercontent.com/6370548/147734243-b93063e1-13b0-49fd-8961-61f8f87f0e1f.png)

**Comment by photopea** [comment]
Fixed, thanks for reporting! :)

Also, I made a mouse back/forward key work inside storages.
