### ISSUE TITLE
File corrupt during saving

### ISSUE THREAD

**Issue by peanuts99** [photopea/photopea#4181]
My project is corrupt during saving. end up the file turn 0KB.
How do I retrieve its history so that i able to get previous save version ?

![Capture](https://user-images.githubusercontent.com/96802484/147737956-70afd265-98ca-4d45-a98c-e0151d5e840c.PNG)

**Comment by photopea** [comment]
We do not store any data at our servers. You can save your work only to your computer.

Can you describe, how can I make Photopea save a 0KB file? Can you make it happen again?

**Comment by peanuts99** [comment]
Indeed my work save in my PC. During saving process in Photopea, it shown saving corrupted. And the file inside my folder turn 0kb.



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by photopea** [comment]
Can you produce a 0 Kb file with Photopea again?

If you are saving a large file (e.g. 100 MB or more), there is a message "Saving ..." at the top. Do not close Photopea until this message goes away. If you close it earlier, you will get a 0 byte file.

Did you close Photopea too early? I am afraid we can not help. Your browser lets you close any website at any point, no matter if saving is finished or not :(

**Comment by peanuts99** [comment]
Nope. I saw the saving on top. I did not close before its done. Add on, I save it then went to toilet. Nobody touch the PC.  Which I why I ask advice here. And I definitely will not want to have another chance to experience this again.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by photopea** [comment]
If that is what happened, there should be away to make Photopea do it again.

Can you open just any file and do any random editing (like for 20 seconds), and make Photopea produce a 0 Byte file again?

**Comment by peanuts99** [comment]
It's happened again .

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by photopea** [comment]
I still need a description, how to make it happen. I can not fix it otherwise.

**Comment by peanuts99** [comment]
I also did not know how does it happen. It occur during saving

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by peanuts99** [comment]
Suddenly saving corrupt 😳

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by peanuts99** [comment]
It happened again.
Realize  the page suddenly froze, turn slow pace
And this time have error report mentioned " out of memory "
And my file turn 0kb. Previous data all gone.

Hope this help you. I felt so annoyed this happened so many time and need to rework from scratch everytime.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by peanuts99** [comment]
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by photopea** [comment]
How much RAM memory do you have in your computer, and what was the size of that PSD file?

**Comment by peanuts99** [comment]
32gb ram for my PC and the size of file about 12,000 kb only

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by photopea** [comment]
Can you make Photopea produce a 0-Byte file again? If yes, can you record a video of how you produce a 0-Byte file in Photopea? Share this video with us.

**Comment by peanuts99** [comment]
Nope. I was unable to do that . I have shared a lots of information to you and ur team and I'm facing lots of data lost. Please give me solution soon.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by photopea** [comment]
Sorry, it can not be fixed until you provide any proof that it really happened (a video record, or a description of steps, how to make it happen).

**Comment by peanuts99** [comment]
I already told you how it happened thru the day email...please look at previous email...

During saving, the page itself suddenly froze ...that email. I mentioned in step for you and yet you say I did not list description nor step ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by photopea** [comment]
I can not make the problem happen, and neither can you (as you say). At least one person in the world must be able to make it happen, and record it on a video, so that I can analyze it further.

**Comment by alexrx5** [comment]
just wish i had photoshop this has just randomly completely corrupted me projects twice after spending hours on them for nothing. nice.

**Comment by photopea** [comment]
Photopea should ask you to save your work every 30 minutes. If your computer is not powerful enough, we recommend saving regularly. Also, many browsers do not let a website use more than 16 GB of RAM.
