### ISSUE TITLE
The median filter is a bit different from the one in Photoshop

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4182]
If there are 9 pixels in the "area", Photoshop choose the 5th one which is the median,  but Photopea choose the 6th one. 
If there are 6 pixels in the "area", Photopea choose the 4th one. Photoshop choose the 3rd one in some cases and choose the 4th one in other cases. I can not figure it out.

**Comment by photopea** [comment]
The only problem I find with the Median is, that I don't know, how Photoshop handles the transparency. 

Are you talking about a case with all opaque pixels? Could you show me an example of what you mean?

**Comment by nothingshiru** [comment]
> Are you talking about a case with all opaque pixels? Could you show me an example of what you mean?

Yes, I'm taking about cases with all opaque pixels. I hadn't tested transparent pixels.

For example I have such a 3*3 image. If I apply median with value of 1px radius in Photoshop, the image wouldnot be changed. But in Photopea it would be changed.
![screenshot_20211231_193030](https://user-images.githubusercontent.com/79258245/147821619-888e3756-57db-496e-9407-e8431eb6a4fa.png)

**Comment by photopea** [comment]
Thanks! It should be fixed now :)

**Comment by nothingshiru** [comment]
I figured out how the Median filter in Photoshop works when there are an even number of pixels in the area.

For example I apply Median with value of 1px radius to such a 3*2 image.
If its color is ranked 1st to 3rd in the order, then its color will be replaced with the 3rd color. If its color is ranked 4st to 6rd in the order, then its color will be replaced with the 4rd color
![未标题-1](https://user-images.githubusercontent.com/79258245/147847385-70924783-86cd-4f7a-b9b3-37f73dfb567f.png)

**Comment by photopea** [comment]
Does it work differently in Photopea?

I think we should not care about the pixels on edges (which do not have all neighbours). We should care only about pixels, which have all 8 neighbours.

**Comment by nothingshiru** [comment]
Yes, it works differently in Photopea. 

When there are an even number of neighbor pixels, Phototopea always treats “half the number + 1” as the median, but Photoshop treats "half the number" or "half the number + 1" as the median according to the pixel. 

The difference results different effect on edges of image. Applying Median with value of 1px, the width of "edges" is 1px. With value of 2px, the width is 2px...
