### ISSUE TITLE
Gradient layer is not limited in a artboard

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4186]
To reproduce

1. Create a document with artboard.
2. Create a gradient layer in the artboard.
3. Create a new artboard on the right.

The gradient effects changed. Its effects is up to document size instead of artboard size.

**Comment by nothingshiru** [comment]
If I do these steps in Photoshop, the gradient effects is not changed. But if I drag the gradient layer form the first artboard to the new artboard, its effects changed.(it is up to document size)

Honestly, the effects in Photoshop is not clear to me.

**Comment by MichalSZZ** [comment]
We all should keep in mind that Photoshop has bugs too :)
I remember that gradients adj layers and artboards are one of them...
On my computer I have always two different version of Pgotoshop. One new one (but not the newest relase) and a year or two years older that is stable. It is neccessary when you make graphics proffesional with deadlines. There can't be place for software bugs.

**Comment by photopea** [comment]
I think in Photoshop, a fill layer is always adapted to the total size of the document (which you see in Image - Image Size). But when you move artboards, the image size changes, and the fill layer is updated at various stages of that change, or it forgets to be updated.

The behaviour in Photopea should be consistend, it adapts to the total size of a document. If you want a different behaviour, draw vector rectangles.
