### ISSUE TITLE
app.activeDocument.activeLayer.remove behaving differently than normal

### ISSUE THREAD

**Issue by yikuansun** [photopea/photopea#4188]
Hi,

This is a problem that I just noticed today, that I never experienced before with some of my plugins. These plugins use an advanced preview system in which a preview is placed onto the Photopea document, and when the user changes settings in the plugin GUI, the preview is deleted from the Photopea document and a new one is added, creating the illusion that the preview is updating. This has worked flawlessly in the past, but today they just broke. What happens is that the second time a preview is supposed to be added, it doesn't- so the initial preview just gets deleted. Even weirder, the next time the user changes something in the GUI, the latest preview and the one that didn't show before up both get added. Below is a video demonstration of this happening with the Particle System.

https://user-images.githubusercontent.com/38194363/147861291-f61fa330-fc69-4bb3-b4fd-efbadcb22902.mp4

Thank you!

**Comment by yikuansun** [comment]
Sorry, this is not a problem with `app.open`. It is a problem with `app.activeDocument.activeLayer.remove();`: this script executes without sending `done`.

**Comment by photopea** [comment]
Hi, I am very sorry, it should be fixed now.
