### ISSUE TITLE
Error Smart Object / Layer Style

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#419]
Very annoying bug I couldn't even go back to my file and save my changes.
I wanted to open Smart Object by double clicking but I missed the icon and Layer Style dialog opened.
Then I double clicked on icon and it opened Smart Object file but Layer Style dialog is still open and you can't close it and go back to main file due to error.

To reproduce:
Open pea.psd
Convert "top bar" layer to Smart Object
Open Layer Style dialog for that layer
Double click icon of "top bar" layer (you are transferred to "top bar.psd" file)
Click "x" to close modal window
->
Uncaught TypeError: Cannot read property 'add' of undefined
    at Function.GI.Xu.XK (pp.js:3007)
    at GI.Xu.Ba (pp.js:2996)
    at GA.Ba (pp.js:5861)
    at GA.DB.Z (pp.js:6)
    at GA.F.Z (pp.js:4100)
    at Ga.F.Z (pp.js:4100)
    at _w.F.Z (pp.js:4100)
    at _w.CJ (pp.js:5003)
    at _w.Cs (pp.js:5001)
    at _w.DB.Z (pp.js:6)

**Comment by photopea** [comment]
It was fixed. Thank you!
