### ISSUE TITLE
Feature Request: Move Graphics on the Canvas by Dragging Them, Regardless of the Layer Selected

### ISSUE THREAD

**Issue by Erelynn** [photopea/photopea#4190]
I often import multiple graphics that I need to reorganize on a single canvas. I find it time-consuming to work on these types of projects in Photopea, simply because I cannot move a graphic unless I locate & select its layer. This is very challenging to do when I have uploaded many images, and have a lot of layers to work with as a result. I wish there was a way to simply hover over an image and drag it where I need it to be, regardless of the layer that I have selected. It is so much faster to point my mouse cursor to an image & drag it directly than it is to scan through a whole bunch of layers every time I need to move something. A feature like this would allow me to spend more time planning my design instead of searching for a specific layer, only to be able to move a picture around. This feature will help me be able to more easily create collages that include many pictures, as well as different types of designs that require the use of several graphics.

Thank you for reading my feature suggestion :)

**Comment by nothingshiru** [comment]
With Move tool selected, check Auto-Select on the option bar then you can drag layers in canvas immediately.

**Comment by photopea** [comment]
Enable the Auto-select, see https://www.photopea.com/learn/layer-manipulation
