### ISSUE TITLE
There need to be icon in front of hidden layers

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4191]
Such an icon can help people to understand the status of layers' visibility much easier. it is important especially for beginners of Photopea.
![Screenshot_20220102_195503_com microsoft emmx](https://user-images.githubusercontent.com/79258245/147875555-22de8587-79fb-40bb-8f88-ead24db0169a.png)

**Comment by nothingshiru** [comment]
In Photoshop, there is square in this place. But now I think it may not be intuitive.

Such a icon can be much easier to understand.
![Screenshot_20220102_195503_com microsoft emmx](https://user-images.githubusercontent.com/79258245/147875323-676ba1f6-e42d-4079-93e3-e9b3b1bc1344.png)

**Comment by photopea** [comment]
I think a stroked eye looks almost identical to a regular eye. I decided to use a square there.

**Comment by nothingshiru** [comment]
Fine.
