### ISSUE TITLE
Logos at the bottom

### ISSUE THREAD

**Issue by devirdua** [photopea/photopea#4192]
can you take off the logos of the footer thats sucks dont let you work good and the efects of snow if is on subscription dude take it off tanks.

**Comment by photopea** [comment]
Hi, I am sorry, I do not understand.

**Comment by YusufSuleman** [comment]
@devirdua He/She won't understand. Expect that He/She won't do it and wants money.

**Comment by photopea** [comment]
How can I help you?

**Comment by YusufSuleman** [comment]
@photopea Remove the Snow Effects.
