### ISSUE TITLE
File not loading

### ISSUE THREAD

**Issue by Unebe-rcg** [photopea/photopea#4193]
I edited a file and saved it in .pdf format. Since then its not loading properly. I have tried opening files in other formats like .png and .jpg, they are working file but not that .pdf one.

**Comment by photopea** [comment]
Photopea does not guarantee opening every PDF correctly.

What is your goal? PDF files were not supposed to be edited any further. Save your work in PSD files, if you want to work with it again in the future.

**Comment by Unebe-rcg** [comment]
I tried to save it in PSD but it constantly shows saving screen and nothing happen. So I was forced to save it in .pdf and edit it later. First it was taking like 10 min to open but now that file is not loading.

**Comment by photopea** [comment]
Saving PSDs should always work. Are you able to save PSDs now? If not, try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by Unebe-rcg** [comment]
Tried them. I am able to export file in all formats just PSD is not working.

**Comment by photopea** [comment]
So you can not export a PSD even of an empty file?

**Comment by Unebe-rcg** [comment]
Yes.

**Comment by Unebe-rcg** [comment]
Meanwhile I am able to edit that file and save it to different formats too but not PSD.

**Comment by photopea** [comment]
Are you able to save a PSD in the Incognito mode, as the article suggested?

**Comment by Unebe-rcg** [comment]
Yes, I tried it in incognito mode.

**Comment by photopea** [comment]
What browser and version exactly are you using?

**Comment by Unebe-rcg** [comment]
Opera Brower and its the latest version.

**Comment by photopea** [comment]
But can you tell me the version? I just tried Photopea in Opera 82.0.4227.43 and I can save PSD files.

**Comment by Unebe-rcg** [comment]
![image](https://user-images.githubusercontent.com/96997819/147889882-4d577df2-09a7-48a8-8c7e-435de0ec37ba.png)

**Comment by photopea** [comment]
Did you enable any "security settings", "privacy protection", "malware blocking", any buzzword-sounding option, which might modify the standard functionality of websites?

**Comment by Unebe-rcg** [comment]
No, I haven't. 🥺

**Comment by photopea** [comment]
Have you tried to restart your computer? Maybe your Opera is acting out and needs to be restarted.

Anyway, it works in my Opera, so I think you have some strange settings. If you do not understand the settings of Opera, I recommend you to switch to another browser. There is nothing I can do to make it work, I am sure the problem is at your side.

**Comment by Unebe-rcg** [comment]
Thanks, I will try that and if that also didn't work then maybe I have to start my project again and complete it in just one go.
Again, thanks for your time. It's much appreciated.
