### ISSUE TITLE
os support request: os: Macos

### ISSUE THREAD

**Issue by klade-png** [photopea/photopea#4194]
Hello there hope you guys are doing happy and healthy!

Sorry for my bad English but I was wondering if it's possible to bring install support for photopea on macOS?

stay safe and happy new year,
Klade

**Comment by photopea** [comment]
It should work on Mac OS in these browsers: https://developer.mozilla.org/en-US/docs/Web/API/Window/onbeforeinstallprompt#browser_compatibility

**Comment by klade-png** [comment]
No i mean download support like in windows

**Comment by photopea** [comment]
What do you mean by "download support in Windows"? I think we do not have such thing.

**Comment by klade-png** [comment]
When you go into windows on the tool bar you can see there is an option called install

**Comment by klade-png** [comment]
i mean more in tool bar on the top
<img width="165" alt="Screen Shot 2022-01-02 at 3 22 06 PM" src="https://user-images.githubusercontent.com/96974114/147892078-1c2f1c69-6d8a-46bc-8861-3a38214e058e.png">

**Comment by photopea** [comment]
The "Installed" Photopea still requires a browser to run. This option is available only in browsers that I mentioned above. It does not work in Safari or Firefox now.

**Comment by klade-png** [comment]
oh ok thx
