### ISSUE TITLE
Make it Open Source.

### ISSUE THREAD

**Issue by YusufSuleman** [photopea/photopea#4196]
Make it Open Source Quickly. You failed last time. Don't be a hypocrite. I can't even use Adobe Photoshop on Linux and GIMP is not` enough. Don't be a hypocrite. Make it Open Source. You are no benefit to humanity Make it Open Source.

**Comment by photopea** [comment]
Hi, sorry, I worked on Photopea for 9 years and I do not want to give it away for free. That is like building a house for 9 years and then, setting it on fire. Would you do that?

**Comment by YusufSuleman** [comment]
Please do it.

**Comment by photopea** [comment]
We are not planning to make Photopea open-source at the moment.
