### ISSUE TITLE
Make it Open Source

### ISSUE THREAD

**Issue by YusufSuleman** [photopea/photopea#4198]
Why are you not listening? 

#4196 
Also, why are you ignoring me.

**Comment by MichalSZZ** [comment]
What else he can do except ignoring you?
Your request is so silly and naive. Why you just don't ask Adobe to give Photoshop to the Open Source society?
Their software is even better that Photopea... so please go to the Adobe forum and put your Spam there.
Free software is not the same as Open Source Software.
And there are Open Source softwares that are not free. 
Go and read about it.

**Comment by photopea** [comment]
We are not planning to make Photopea open-source at the moment.
