### ISSUE TITLE
Key commands 

### ISSUE THREAD

**Issue by SimonFricker** [photopea/photopea#42]
Could you add the Photoshop key commands
http://morris-photographics.com/photoshop/shortcuts/downloads/PSCC%20Keyboard%20Shortcuts%20Mac.pdf

**Comment by photopea** [comment]
You mean all of them? Lots of actions are not possible in Photopea yet, so it is not possible to make a keyboard shortcut.

BTW. do Ctrl+A, Ctrl+R, Ctrl+U ... work on Mac? I am curious, if Mac browsers attach the same code to Command key, as Windows browsers attach to Control key.

**Comment by SimonFricker** [comment]
Pressing control on a mac brings up Hue/Saturation dialogue. 

The other key commands do not work as far as I can tell. 

BTW: I like using CMD + T  = Free transform

**Comment by photopea** [comment]
There are lots of shortcuts, which are not available to a webapp.

E.g. in Chrome, Ctrl+T opens a new Tab, Ctrl+N opens a new window etc., while they are programmed to do Free Transform and New Project. In Firefox, they work correctly.

**Comment by SimonFricker** [comment]
What if you entered fullscreen mode?

**Comment by photopea** [comment]
I think that browsers should work the same in both classic and fullscreen mode.

**Comment by Studioartcz** [comment]
Some "legend of supported shortcuts" will be good too! :)

**Comment by tomasnosek** [comment]
I think you can easily add some basic tool shortcuts - move tool "V", text "T" etc. It's fine as a start. No need for advanced shortcuts yet.

**Comment by photopea** [comment]
Hi, I have added keyboard shortcuts for tools (V for move, T for text etc. ).
