### ISSUE TITLE
"Give you money" flow is kind of confusing when I don't already have an account. 

### ISSUE THREAD

**Issue by nfriedly** [photopea/photopea#4200]
I'm trying to give you some money, because I've used Photopea for years and it's awesome. I don't really want or need an account, but it says something about needing to be logged into an account when I click on the money button. On the screen I see Log In and Account buttons. I don't yet have an account to log into, so I click the Account button at the top and... nothing happens. I though maybe the "pay money" modal was blocking it, but if I close that and then click Account it brings back the "pay money" modal:

<img width="795" alt="Screen Shot 2022-01-03 at 2 51 47 PM" src="https://user-images.githubusercontent.com/114976/147973810-60562e05-a38f-449a-a779-54795dfe8db8.png">

I eventually figured out that Log In was the way to create an account, but I though you might want to know about the confusion here.

**Comment by photopea** [comment]
Thanks a lot! We do not accept donations, as we want to give users something in return (e.g. removal of ads and a larger workspace). "Log in" is for logging into Photopea with your Facebook / Google / other account. In case you did not log in before, it will create a new record in the user database.
