### ISSUE TITLE
Missing Terms and Conditions in payment flow

### ISSUE THREAD

**Issue by nfriedly** [photopea/photopea#4201]
If I click on Terms and Conditions in the first screen, it says

> Your verbiage goes here...

<img width="515" alt="Screen Shot 2022-01-03 at 3 00 36 PM" src="https://user-images.githubusercontent.com/114976/147974637-4b4dd7e8-fac4-4899-a3ff-f59cc6318b66.png">
<img width="556" alt="Screen Shot 2022-01-03 at 3 00 26 PM" src="https://user-images.githubusercontent.com/114976/147974643-f54a622e-bfd4-4525-89aa-9d9aff6d4545.png">

**Comment by photopea** [comment]
I have never seen this screen. This is made by our partner, who provides payments. I think it looks and works differently in each country, according to local laws.

**Comment by nfriedly** [comment]
🤷

**Comment by nfriedly** [comment]
I'm in USA for what it's worth.

**Comment by photopea** [comment]
So were you able to pay? Do you need any other help?

**Comment by nfriedly** [comment]
Yes, I was able to pay. It just looked wrong, and I thought you might want to know about it.

**Comment by photopea** [comment]
ok thanks, I will look into it.
