### ISSUE TITLE
Smart Object transformation don't remember the update on canvas

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4202]
I had a project with a smart object inside. 

The smart object size was 2x1 (for example), and then i enter it to edit it.

I changed the canvas size from 2x1 to 1x1, then i saved

On the main project the smart object was updated without any issue.

But when i it Ctrl+T to transform it from the W & H inputs on the top bar, i got different %
![image](https://user-images.githubusercontent.com/11801254/147977628-65b1308b-ef29-4d28-948e-a685d7195f6b.png)

If i change one input, the other will change as well, because the chain icon is enabled, which is something i want, but it drastically adjust itself to and equal % number.
 
![image](https://user-images.githubusercontent.com/11801254/147977706-52a8af9c-9ad7-42a6-bf0b-83111850a54a.png)

PSD: https://www.photopea.com/#iqB3uzw0c

**Comment by avagp** [comment]
basically the pizza gets angrier :P

**Comment by photopea** [comment]
It should be fixed now :) you will not see it on your current smart objects, but if you crop them again, and save, it should work properly.
