### ISSUE TITLE
Warp boxes to drag are very difficult to click on

### ISSUE THREAD

**Issue by elikalt** [photopea/photopea#4203]
The boxes that pop up for warping an image have very very tiny click boxes and I have to scroll around the box for mins to find it and click on it to drag. I wasn't having this problem a couple weeks ago when I was warping images.

**Comment by photopea** [comment]
Hi, could you show me a screenshot of how it looks?

**Comment by elikalt** [comment]
My pointer can't pick up the boxes to drag them

**Comment by elikalt** [comment]
The boxes on that picture to warp it aren't registering with my cursor and
have very tiny drag boxes. I'm not sure how to explain it. But distort and
the other transform option's boxes pick up my clicks perfectly.

**Comment by photopea** [comment]
Can you take a screenshot and share it with us? Reply in a browser, not through an email.

**Comment by elikalt** [comment]
![Screenshot 2022-01-03 7 13 02 PM](https://user-images.githubusercontent.com/97067581/148008685-d4862cb6-9a62-4e36-912c-bd3679edb6b4.png)

**Comment by photopea** [comment]
Do you mean the 4x4 (16) squares for dragging the warp transform? Their size looks ok to me. The size of Free Transform squares should be identical.

So you can not click and drag these boxes at all?

**Comment by hxim** [comment]
@photopea Hi, I just tried and it seems you need to have smart object transformed to smaller size to make the bug happen.
See this screenshot you cannot drag square in this mouse position:
![image](https://user-images.githubusercontent.com/6370548/148057527-6cbab70b-524f-468b-81d0-2d5375f00b37.png)
To reporoduce:
1. New project 1024x768 (white background)
2. Unlock background layer
3. Covert background layer to Smart Object
4. Free Transform to 20% width and height
5. Click Warp button
6. Try to move/drag any of 16 squares - it will work only in small part of (middle) area of each square.

**Comment by nothingshiru** [comment]
I tried it too.

It seems like the draggable area of the control point shrinks as the layer shrinks. The problem has nothing to do with smart object.

**Comment by photopea** [comment]
@hxim @nothingshiru  guys, I don't know what would I do without you. Thanks a lot for tracking down this bug! :)

It is fixed now. But I think it has always worked like this in Photopea in the past.

**Comment by elikalt** [comment]
thank you
