### ISSUE TITLE
Swap the positions of Refine Edge and Color Range

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4208]
Refine Edge is used to refine existing selection, which means it is close to "Modify". So the one above the Modify should be Refine Edge instead of Color Range.

**Comment by photopea** [comment]
I put Refine Edge right under Modify.

**Comment by nothingshiru** [comment]
Color Range and Magic Cut are for creating selection, while Refine Edge and Modify are for modifying selection. So my idea was, put Color Range and Magic Cut together and put Refine Edge and Modify together, then divide them by the divider. 

The only thing need to be done is just as the title described...

**Comment by photopea** [comment]
Ok, I did it.

**Comment by nothingshiru** [comment]
Thanks :)
