### ISSUE TITLE
Cloning doesn't seem to work

### ISSUE THREAD

**Issue by donnyv** [photopea/photopea#421]
Tried holding Alt or K down and nothing happens. 
Chrome 63.0.3239.84 (64 bit)
Windows 10

**Comment by photopea** [comment]
Hi, did you do it according to the manual? https://www.photopea.com/learn/bt-basic

If it still does not work, can you describe what did you do?

**Comment by donnyv** [comment]
Not sure what I did but it wasn't working for a certain gif image. When I opened a new tab with the same image it works fine. If I can repeat the issue I'll let you know.

Fantastic by the way!! I shared it on twitter.
