### ISSUE TITLE
Cut and Copy Merged should be disabled when there's no selection

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4210]
Without selection, Cut and Copy merged works like copy. They should be disabled to prevent people from thinking that they can successfully Cut or Copy Merged without selection.

**Comment by photopea** [comment]
I have fixed it. I disabled the shortcuts, too.

**Comment by nothingshiru** [comment]
Copy should not be disabled.

**Comment by photopea** [comment]
You are right, I did not realize that.
