### ISSUE TITLE
Photopea

### ISSUE THREAD

**Issue by samt2001** [photopea/photopea#4211]
I cant continue edit a thumbnail i have already made can someone please help me with support on how to edit something what has already been edited

**Comment by photopea** [comment]
Are you not able to open a PSD file in Photopea? Or what exactly do you mean?

**Comment by klade-png** [comment]
lol, I think he means that his edited png file is not letting him edit it. or he is new and got stuck with the marching selection box where he couldn't edit anything outside of it.

**Comment by photopea** [comment]
I will close it, as the original author stopped responding :(

**Comment by samt2001** [comment]
How do you not know what a thumbnail is you run a website what you can make
pictures on and you dont know what a thumbnail is

**Comment by samt2001** [comment]
Wow so every single person doesnt know what a thumbnail is
