### ISSUE TITLE
Copy & Paste problem

### ISSUE THREAD

**Issue by strawberryxfields** [photopea/photopea#4213]
For some reason, I can't use the Copy &/ Paste options, neither the shortcuts, nor the commands under the 'Edit' menu. I have 'allow' checked for clipboard permission in my browser. It doesn't work in Incognito mode, or in the app either. My browser (Google Chrome) is updated.

**Comment by photopea** [comment]
You need to make a selection, to copy a specific part of a layer. If you want to duplicate a whole layer, press Layer - Duplicate, or Ctrl+J.
