### ISSUE TITLE
Problema em copiar e colar/ Problem copy and paste

### ISSUE THREAD

**Issue by Vitor12121212** [photopea/photopea#4214]
As teclas e atalho ctrl c/ ctrl v não estão funcionando no Photopea. Reitero que as mesmas funcionam normalmente em outras áreas do computador!
The keys and shortcut ctrl w/ ctrl v are not working in Photopea. I reiterate that they work normally in other areas of the computer!

**Comment by photopea** [comment]
I am sorry, it is fixed now.

**Comment by n3ttoexe** [comment]
i got a problem too... jully 2023

**Comment by photopea** [comment]
hi, try this first: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/
