### ISSUE TITLE
Issue w/ opening MP4's

### ISSUE THREAD

**Issue by gearbit** [photopea/photopea#4216]
I'm trying to open a 5 second mp4 and the program only seems to open to the first second. I've tried messing around with the frame rate and resolution of the mp4 but it still only opens up to that first second. I tried to open a longer mp4 but am encountering the same issue. I'm not really sure what to mess around with to try to figure out the cause of the issue. I am using the browser version.

**Comment by photopea** [comment]
Hi, does it work now? We fixed a bug related to videos today, so it probably caused another bug.

**Comment by gearbit** [comment]
It does! Thank you for such a quick response, I appreciate it.

**Comment by photopea** [comment]
Ok, I am sorry for it.
