### ISSUE TITLE
Alphablend, smooth algorithm, drawings, snapping, coordinates

### ISSUE THREAD

**Issue by techeditorsrc** [photopea/photopea#4217]
Some issues. Maybe, smooth pixels algorithm need corrections to make more correct smooth, some pixels look less smoothed than other. Vector points need to be at the center of the pixel, this fix another bug, stroke shape with 1px in options will look 1px on the screen.Vector rectangle stroke with 1px height giving wrong color, base stroke shape lines not 100% color alpha. And stroke smooth also with wrong alpha. Snapping for pen drawing not working. And I would add more tools and more features for vector drawings.

**Comment by photopea** [comment]
Hi, what is a "smooth pixel algorithm"? What do you mean by "some pixel look less smooth"?

**Comment by techeditorsrc** [comment]
When I draw with the Brush tool, first look, some pixels look less smooth, for example, anti-aliasing for some pixel 95%, 90%, 85%, 35%, 25%, 10%, 5%. It's look like pixel less anti-aliased. And vector rectangle with 1px stroke and without fill color,  rectangle with 1px height, wrong anti-aliasing. Also, would be good to have indicator of zoom %.

**Comment by photopea** [comment]
What zoom do you have? Enable Rulers:  View - Rulers, to see the zoom at the bottom left corner. Images might look ugly at a certain values of zoom.

Also, it would be 1000x better if you shared an image of what you see, instead of describing it with words (which I still do not understand).

**Comment by photopea** [comment]
I have to close it because of lack of details.
