### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by Gustaw0000** [photopea/photopea#4218]
There is no way to install plugins for photopea, at least this one won't install and when you drag it to photopea an error pops up.

https://app.mediafire.com/4o8uuyctosv1j
![image](https://user-images.githubusercontent.com/70661990/148559781-c1ec05ab-c887-415a-b718-454c5f4456c5.png)

**Comment by photopea** [comment]
I downloaded it and there is no mention of Photopea.

Who made this plugin? Did the author say, that it is a plugin for Photopea? Maybe it is a plugin for Microsoft Word or PowerPoint.

**Comment by Gustaw0000** [comment]
The author of the plugin is profactions, the plugin was made for Photshop so I thought it should also work in Photopea

**Comment by photopea** [comment]
No, plugins for Photoshop do not work in Photopea. Only plugins for Photopea work in Photopea.
