### ISSUE TITLE
app crashing while opening

### ISSUE THREAD

**Issue by Bharath143-cyber** [photopea/photopea#4219]
please make sure that u will make it right i love this app im using this app since one year but after updating it is crashing it is displaying no internet connection please try again later

**Comment by photopea** [comment]
Hi, what updating do you mean? Are you using Photopea at www.Photopea.com ?

Is it crashing or displaying "no internet connection"?

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by Bharath143-cyber** [comment]
Displaying no internet and also in app

**Comment by photopea** [comment]
Ask your internet provider about it. Are you in Iran or China? The governments might censor the internet for you.
