### ISSUE TITLE
Add export for web for optimized assets like tinypng and single layer export.

### ISSUE THREAD

**Issue by Jo3l** [photopea/photopea#422]
I have to use windows at work on my pc because of photoshop, I work as fronted developer and I only need to export some layers and optimize assets. If you can add this, I can go back to my beloved ubuntu again. Thanks for your work!

**Comment by photopea** [comment]
What exactly do you mean?  If you press File - Export As - PNG, you can export optimized PNGs. You can also right-click any layer and choose Get PNG.  We also have a separate PNG minifier: http://upng.Photopea.com

**Comment by Jo3l** [comment]
Sorry, I used a really big image to do the tests and the png quality (colors) was sooo slow that looked blocked.

The export is really great, I checked with smaller ones and it's almost perfect. It would be great add  color dithering like diffusion, pattern or noise.

![image](https://user-images.githubusercontent.com/8069723/34078783-5b90d118-e321-11e7-8ea6-4a99ec814380.png)

**Comment by photopea** [comment]
I suggest to save your picture (and all photos in general) as JPG or WebP. They would be much smaller than PNG, while having a better quality and much faster to export.

We don't have dithering in the output PNGs, because it usually increases the file size. It is better to use a slightly higher quality instead.

**Comment by Jo3l** [comment]
I need to use png because of it's alpha channel.
I know dithering increases the size of the png, but sometimes the relation of size and quality must be a user decision.

Anyway your software is amazing, and I only wanted to add some suggestions like layer export and better optimized output assets.

**Comment by photopea** [comment]
Thanks! BTW. WebP also supports alpha channel.

PNG example: 
1) The PNG with 50 colors is 50 kB. 
2) The same PNG with 30 colors (no dithering) is 30 kB. 
3) The same PNG with 30 colors and dithering is 50 kB. 

3) looks much better than 2) thanks to dithering, 3) looks as good as 1). But dithering (and any other noise) increase the size, so I recommend to use 1) instad of 3) (they have the same size).

**Comment by photopea** [comment]
I implemented Floyd-Steinberg dithering in the past, but it increased the size quite a lot. Maybe we need some dithering methods, which don't affect the Deflate compression that much. It requires doing some research.

Could you do some experiments and implement some dithering? We can solve it in our PNG library: https://github.com/photopea/UPNG.js
