### ISSUE TITLE
font not working

### ISSUE THREAD

**Issue by energiesgraphiques** [photopea/photopea#4221]
I'm using the Bahnshrift font on my PDF/AI file.
[(https://www.dafontfree.co/bahnschrift-font/)](https://www.dafontfree.co/bahnschrift-font/)
As it is a special font (weight is customisable with a slider in Illustrator/Photoshop), it doesn't show in your program, and even after loading it manualy from my drive, the bold-light... option doesn't show or work.

**Comment by photopea** [comment]
I downloaded your fonts. It contains 15 TTF files, but they all look identical in Windows Font Viewer.

Photopea does not support variable fonts at the moment.
