### ISSUE TITLE
Suggestion: Make Ctrl+Enter escape the transformations input

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4225]
![image](https://user-images.githubusercontent.com/11801254/148863193-df8fda04-2876-4377-afd6-cc24a1890369.png)

It would be awesome, i don't know if it is possible, to use Ctrl+Enter to escape and apply the modification when you are on a transformation text input. 

If you are transforming a layer, and you press Ctrl+Enter it will apply and escape the transformation, but if you are inside an input, it won't.

:)

**Comment by avagp** [comment]
is this possible?

**Comment by photopea** [comment]
I made it work like this: If you are typing a value, pressing Enter will confirm the value which you typed, AND it will escape the input. Then, you can press Enter again to confirm the Free Transform, or keep editing the transform.

**Comment by avagp** [comment]
PERFECT!!!

now i am 15% more quick editing :D

**Comment by avagp** [comment]
I don't know if it is a regression or not, but can you make Esc button to cancel the editing on the inputs?

**Comment by photopea** [comment]
done :)

**Comment by avagp** [comment]
(◍•ᴗ•◍)❤

Il lun 21 feb 2022, 20:38 Photopea ***@***.***> ha scritto:
