### ISSUE TITLE
How many GB of RAM do I need for photopea?

### ISSUE THREAD

**Issue by Jykie** [photopea/photopea#4226]
Hi there,

Is 64 GB of RAM enough to handle Photopea? I need to purchase a new laptop for my photo compositing and want to make sure I purchase a device that can handle both Photopea and any large file sizes without difficulties. What would be the recommended GB of Ram for Photopea?

**Comment by photopea** [comment]
Each pixel takes four bytes. So for a 10,000 x 10,000 pixel layer, you need 400 MB of RAM. For 10 such layers, you need 4 GB of RAM, and so on.

But with more RAM, you can run many different apps / websites simultaneously. So the more, the better. I think 16 GB of RAM is fine for most of the graphics work.

**Comment by Jykie** [comment]
Thank you so much! I'll definitely keep that in mind

**Comment by raabemartinsdesigner** [comment]
hahahahahha! my device is only 2GB of RAM... I can't make graphics bigger than 4000px, the whole thing stop and I lose my job. However I use photopea for work every day of the past 6 months, best site ever

**Comment by photopea** [comment]
I really recommend getting more than 2GB of RAM. I am trying to sell a 8GB RAM module form my laptop for $30 and nobody wants it :D
