### ISSUE TITLE
Feature Request: Magic Eraser!

### ISSUE THREAD

**Issue by Squizyton** [photopea/photopea#4227]
I don't know if this has been requested enough but,

One of the features I used a lot in Photoshop was Magic Eraser,

And I think it would also benefit Photopea to also have it!

It's an awesome feature and save's a lot of nuisance and headache

**Comment by Squizyton** [comment]
The magic eraser tool works similarly to the magic wand tool in Photoshop. It selects a larger area based around contrast in pixel then just deletes them.

And then you can choose the tolerance so it determines how close to the selected Pixel it selects.

**Comment by photopea** [comment]
We have added the Magic Eraser
