### ISSUE TITLE
unsupported text layer

### ISSUE THREAD

**Issue by tiger62** [photopea/photopea#423]
See attachment: psd created with Photopea: simple Logo with special ttf Font. (also attached)
Problem: Text layer not editable to change font size etc.
[AZ_Logo_Neu_Font.zip](https://github.com/photopea/photopea/files/1565603/AZ_Logo_Neu_Font.zip)
[Allianz-Positiv.zip](https://github.com/photopea/photopea/files/1565609/Allianz-Positiv.zip)

**Comment by photopea** [comment]
Your font is quite strange. It has the os2 value "sTypoAscender" equal to 0, which I have never seen before. But I made it work without it.

Could you please re-create your PSD file? Or double-click the layer and make the constraining rectangle taller.

**Comment by tiger62** [comment]
PSD recreated - yes, it works now! - Thank you!

**Comment by photopea** [comment]
Thank you for reporting it! You are awesome! :)
