### ISSUE TITLE
Feature Request: Add toggle buttons for Free Transform shortcuts for tablet/mobile users

### ISSUE THREAD

**Issue by JesperHedin** [photopea/photopea#4230]
I use photopea a lot on my tablet. As I don't have a keyboard, I havn't found a way to use the Free Transform shortcuts Shift (to keep aspect ratio), Alt (to scale around center) or Ctrl (to skew). Would love to see them as check boxes in the toolbar for Free Transform 

Thanks! 

![TransformShortcuts](https://user-images.githubusercontent.com/43420006/149341317-e39f403c-fbaa-4eca-bcb9-b2f44e906abc.png)

**Comment by photopea** [comment]
Hi, there are virtual keys at the bottom of the toolbar (bottom left corner), which can help you :)
