### ISSUE TITLE
default file handler for jpg files

### ISSUE THREAD

**Issue by rich2323** [photopea/photopea#4232]
I have "installed" photopea as a PWA and that is working fine.  I have also change the setting in Chrome to enable File Handling API. 

This now gives me the ability to right click on a .png file and click "Open With" and select Photopea...this works perfect. I can now double click on a .png file and it opens in Photopea. Perfect!

But, I cant do this same step for .jpg files....  Photopea is not even an option. 

What am I doing wrong?

Rich

**Comment by photopea** [comment]
What if you rename your file to ".jpeg", is it possible?

**Comment by rich2323** [comment]
Thank you for your quick reply. 

Renaming the file works, but I have hundreds of files and folders that I would have to change...is there any way to get it to work without renaming?

Thanks,

Rich

**Comment by photopea** [comment]
I have updated our manifest: https://www.photopea.com/manifest.json ,  and it should handle .jpg files now. Try to refresh Photopea somehow, or restart it somehow, to make your borwser update the manifest.

BTW. do uppercase extensions work, like ".PNG"?

**Comment by rich2323** [comment]
The .jpg option now works!! the upper case .PNG does not work.  We are heading the right direction.

**Comment by rich2323** [comment]
If i click on a uppercase .PNG file it opens Photopea but does not open the file, and that is the same for .JPG

**Comment by rich2323** [comment]
lower case png and lower case jpg do work as of right now

**Comment by photopea** [comment]
Let me know if there is anything else I missed :)
