### ISSUE TITLE
Save back to original fileformat

### ISSUE THREAD

**Issue by rcoenen** [photopea/photopea#4233]
Please allow for saving back to original fileformat for at least .png and .jpg in addition to .psd

As discussed in #1901 this will really contribute to the workflow when working especially in PWA mode.

Please note: The Photoshop workflow is than when after opening a .jpg or .png in Photoshop and any features are used (such as layers, editable path, etc etc.) that can only be stored in .psd but no in it's original .jpg or .png format, then the save feature stills work but the PSD file save requestor pops up allowing the user to save in .psd -or- any other format such as .svg, after which the for that file format relevant save options (compression etc.) pops up. Essentially doing an export.

Unsure what the best approach for Photopea is here, I strongly feel that hitting CTRL-S should save back to it's original format when possible... but when it requires to be saved in .PSD perhaps
-in file menu: grey out 'save' thus only keep 'save as PSD" active
-when hitting CTRL-S simply trigger the Save as PSD file requestor?

**Comment by nothingshiru** [comment]
I happened to see a video on youtube the other day about the save function of Photoshop. It may help to understand.
Here's the link https://www.youtube.com/watch?v=5CS_oieQL7c

**Comment by rcoenen** [comment]
That video is brilliant. It exactly explains the well thought through workflow w/r saving in Photoshop.
Compare: Photopea currently always forces me to make a Dave as PSD copy.

**Comment by photopea** [comment]
Ok, I have implemented it. If you open a file from your computer in Photopea, and it is one of the formats below, File - Save will be enabled, and it will rewrite the original file, in the original format.

    "psd","jpg","png","gif","webp","svg","bmp"

**Comment by rcoenen** [comment]
The speed at which you delivered this truly shows the power of PWAs...!

I just tested it and it works brilliantly!

Thanks so much!
