### ISSUE TITLE
Issues with Layers

### ISSUE THREAD

**Issue by Kreativelly** [photopea/photopea#4237]
Hi There,

First time user of Photopea...
I'm having a problem with the layer menus, I don't seem to have all the options open to me as I see in many demos online...

Is there something I am missing or need to 'engage' within the program to get the full list of options.

Example is in the pic I attached...I want to use the drop shadow option, but I am limited in what I can adjust and most of the time, it doesn't do anything of note.

Advice would be greatly appreciated
<img width="1440" alt="Screen Shot 2022-01-16 at 12 17 01 pm" src="https://user-images.githubusercontent.com/97814647/149643644-b1a9ea8f-74b9-48f4-854c-c3aeb1988d3a.png">
.

**Comment by photopea** [comment]
You can learn how to use styles here: https://www.photopea.com/learn/layer-styles , or buy a book about Adobe Photoshop.

You need to learn a difference between clicking a checkbox and a label, it works differently.
