### ISSUE TITLE
Eyedropper for Color Picker

### ISSUE THREAD

**Issue by ddevineacs** [photopea/photopea#4238]
I notice that the eyedropper tool lacks a color picker, which can be quite inconvenient. Is this something that you can add?
![image](https://user-images.githubusercontent.com/90146392/149643664-7484f926-87ca-4cad-9d49-5fc01b0916ed.png)

**Comment by ddevineacs** [comment]
Edit: I found the color picker tool, it's just kinda hidden

**Comment by photopea** [comment]
I recommend you to learn how to use Photopea at www.Photopea.com/learn .
