### ISSUE TITLE
Unable to paste

### ISSUE THREAD

**Issue by amyjewitt** [photopea/photopea#4239]
**Edit, I figured it out! Thanks

Not sure if this a me thing, but I can't seem to copy and paste anything - whether I'm using a shortcut or from the dropdown menu. I attached a screenshot of the error code that appears. It appears to be making a copy, however, the error code occurs when I try to paste.

<img width="1440" alt="Screen Shot 2022-01-15 at 8 22 30 PM" src="https://user-images.githubusercontent.com/97814756/149643769-9c72939f-ca20-4def-a132-b8b5e1a66a5b.png">

**Comment by photopea** [comment]
Try this, let me know if it helped: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
