### ISSUE TITLE
Crashing on exporting .sketch file to psd

### ISSUE THREAD

**Issue by albytom** [photopea/photopea#424]

**Comment by photopea** [comment]
Hi, could you send us your Sketch file to support@photopea.com ?

**Comment by albytom** [comment]
Thanks for the prompt reply. The issue was with the machine I used, which
had no dedicated graphics card. Tried the same file with another machine
and it worked like a charm. The application is awesome.



yours in Christ,
with Love,
Albert

Mob:+919446823066
Office: albertdominic@live.in

**Comment by photopea** [comment]
Photopea shouls work on every machine. Try to disable WebGL (More - Use WebGL) to run it on low-end computers.
