### ISSUE TITLE
Resizing (Image -> Image Size...) doesn't work if the image has an alpha channel (not layer transparency)

### ISSUE THREAD

**Issue by max99x** [photopea/photopea#4242]
To repro:
- Create a new project.
- Add a new channel.
- Click Image -> Image Size...
- Change the size numbers.
- Click Ok
- Observe that nothing happens.

This works just fine on images with only RGB channels though.

**Comment by photopea** [comment]
I am very sorry, it is fixed now.

Wait one hour or clear your cache to be sure you are not using the old Photopea.
