### ISSUE TITLE
Brush

### ISSUE THREAD

**Issue by Dupzell** [photopea/photopea#4245]
Hi there,
Trying to use the brush tool but it keeps bugging. I'm able to do 2 small lines holding ctrl and then nothing. If I close and come back in I can do the 2 small lines again but that's too time consuming and not productive at all.
Thanks

**Comment by Dupzell** [comment]
I'm now also having issues with the eraser tool... It's not working at all.
Thanks

**Comment by photopea** [comment]
Try these steps: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
