### ISSUE TITLE
site is slow

### ISSUE THREAD

**Issue by serenityatmosphere** [photopea/photopea#4246]
when i open photopea, it takes so long for it to load, why is this happening?

**Comment by photopea** [comment]
How long exactly does it take to load? Are other websites fast, e.g. Youtube.com ?

**Comment by serenityatmosphere** [comment]
the other websites are normal, but for photopea, it takes around 2 - 3 minutes to load the site for some reason

**Comment by popbee** [comment]
2-3 minutes is insanely slow,  Here I measured about 1.5 seconds (Google Chrome, Developer tools (F12) opened on the `Network` tab, `Disable cache` option checked)
If you refresh, it's still super slow?

**Comment by serenityatmosphere** [comment]
![Screenshot 2022-01-18 202807](https://user-images.githubusercontent.com/97888664/149937456-1ac4d3f9-d4cd-4937-8471-ff36d65fbbf5.png)
im not sure if this is just me or not, but this is what happens when i try opening it

**Comment by photopea** [comment]
@serenityatmosphere so you can not open Photopea at all? Were you able to open it in the past? In what country are you located?

**Comment by serenityatmosphere** [comment]
hong kong, i can still open it before and now, but the problem is that it takes a while to load, im not sure why

**Comment by photopea** [comment]
Is it going through a chinese firewall? Maybe that is slowing down the website.

Can you open it faster on another network, e.g. on your mobile phone , instead of a wifi?

**Comment by serenityatmosphere** [comment]
its not going through a chinese firewall, my wifi is fine but its still slow, even on mobile

**Comment by photopea** [comment]
Is it really 3 minutes? I think you should ask your internet provider about it. Our servers do not slow down Photopea.

**Comment by nothingshiru** [comment]
I have the same problem. It takes me about 3m20s.

**Comment by photopea** [comment]
Are you also in Hongkong? Or where are you?

**Comment by nothingshiru** [comment]
I'm in Chinese mainland.

**Comment by photopea** [comment]
I still believe your internet providers are responsible for this. We do not slow down Photopea on purpose for specific countries.

Did you get in touch with your internet provider? Did you ask them about this issue?

**Comment by popbee** [comment]
A blank screen is nearly impossible to diagnose.

If you are using Google Chrome, what about opening Developer tools and go to the Network tab.  Clear all the entries (icon next to the red icon) and then refresh the page.  Wait till it's done.  This gives out every single web requests and how long they took to load, including when they started, etc.
Also you could look into the "Console" messages to see if there is any suspicious messages in there.

Maybe it is something very specific that is slow that might give a hint to discover the source of the problem. Also make sure you try in incognito without any extensions/plugins turned ON. Do you have any special software like an antivirus that could also affect networking?   Do you have another device, like a phone on the same network (wifi) and try to see how long it takes on it.

![image](https://user-images.githubusercontent.com/1083830/150004600-7c2bddfb-987c-43d1-a76f-40ce2f97893c.png)
Image from https://developer.chrome.com/docs/devtools/network/

**Comment by nothingshiru** [comment]
I saw that the UI showed up at the moment that pp.js in Network tab was loaded. It doesn't always take me 3 minutes to load, sometimes it takes me 1 minute, dozens of seconds, or a few seconds. 

I guess it's just short-term network fluctuations in my case.

**Comment by photopea** [comment]
Have you tried to get in touch with your internet provider and ask them, why is it slow?

**Comment by nothingshiru** [comment]
No. For personal reason, I didn't do that.

**Comment by alixsep** [comment]
This is because of your region (China). Checking network panel of the dev tools show no issues for me.

@photopea they don't have youtube available there in China, using it via VPN can actually cause some serious sentences for them.

**Comment by serenityatmosphere** [comment]
im from hong kong and we dont have any chinese firewalls, im able to access to youtube without a VPN

**Comment by photopea** [comment]
@serenityatmosphere can you ask your internet provider why Photopea.com is slow? Can you try Photopea.com at your friend, who has a different internet provider?

**Comment by photopea** [comment]
I think your provider is not letting you access certain websites. There is nothing we can do about it :(
