### ISSUE TITLE
Benefits of Open Source

### ISSUE THREAD

**Issue by Aki-Riku** [photopea/photopea#4249]
Photopea's current business model would be mostly unaffected if it went open source. Since the project is mostly funded off of advertisements and donations. 

Going open source would bring a lot of new attention to the project (and thus more donations and ad revenue). Since Photopea is very well-made, it would become a big competitor to GIMP and could take a large portion of their market share (and revenue). Photopea would also get a lot more features because of people adding new code to the project. People would also be able to submit their own bug fixes for the project. 

Other similar projects such as Only Office and Mail Spring have seen a large increase in users and funding after they became open source. 

Since Photopea already operates under a freemium model and uses Github for issue tracking... The transition to open source wouldn't be that much of a hassle, and it would be an overall net positive for the project.

**Comment by klade-png** [comment]
Agreed it would cool with all the plugins and such that come from individual contributors.

**Comment by sasha066** [comment]
By making the project open, you can get a big contribution to it from the community, thereby making the product much better, and with great functionality. Thanks to them, it may even be possible to make the product better than Adobe. And you can also come up with better ways to monetize if you need profits from the development of the project.

**Comment by photopea** [comment]
I would like to keep Photopea closed-source.

**Comment by therealbluepandabear** [comment]
dude shut up

**Comment by camoody1** [comment]
I completely understand wanting to keep the application closed-source. But I won't lie, it would be nice to see all this crazy AI coders create some amazing plugins for their engines. That's the only thing really standing between Photopea and Photoshop - those damn neural filters. 😆
