### ISSUE TITLE
Long saving 

### ISSUE THREAD

**Issue by Kuras1337** [photopea/photopea#4251]
I have a work on which I have been sitting for a long time and I have been trying to save it for half an hour but only the inscription saving is displayed. Anyone know how I can fix this without losing my job?

**Comment by photopea** [comment]
Hi, do you mean saving a PSD file? How large is your document? Do you have a large size or many layers?

Maybe your computer ran out of disk space, or it ran out of RAM memory. Can you delete half of layers, save a PSD, do a step back, and save another half as another PSD?

**Comment by photopea** [comment]
Were you able to save a PSD in the past, or is it your first time using Photopea? If you never saved a file in Photopea successfully, try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
