### ISSUE TITLE
Variables - live preview by jumping to the next/prev row in Data Set editor

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#4255]
I just tested Variables option with CSV data and it is AWESOME feature!

One thing for better UX:
Can you add live preview of inserted data? It should change states of text and visibility - one click in the right arrow should show next data row.
Like in Layer Comps -  (BTW in PS in Layer Comps there are arrows to jump and easy show each saved state). 

I made my certificates in Illustrator and there is something like that (in Photoshop and InDesign too). And in MS Word in Mail Marge function there is a Preview Results where you can easily show (and test if everything is good) each generated document before you send mass correspondence.

I prepared two different UI for that (it can be disabled/greyed out when there is no CSV file)
![data-set-preview-v2](https://user-images.githubusercontent.com/38118273/150520252-16bbcb5e-f4c4-4cc5-bf03-1b70352f7f23.png)
![data-set-preview](https://user-images.githubusercontent.com/38118273/150520254-3064d2e3-e9c1-47ee-9130-0ae422e873c6.png)

**Comment by photopea** [comment]
I have added a checkmark next to each line of data. I think it is better this way.
