### ISSUE TITLE
why is photopea always crashing?

### ISSUE THREAD

**Issue by lislmao** [photopea/photopea#4257]
while one is opening a new file, it'll stay on loading and or completely crash and it just freezes. please help.

**Comment by photopea** [comment]
What device do you use? Maybe your device is not powerful enough.

**Comment by lislmao** [comment]
> What device do you use? Maybe your device is not powerful enough.

i use a newer chromebook! it stays on a white screen after opening a new project and then trying to import the project to make modifications!

**Comment by lislmao** [comment]
it was also working perfectly fine a couple of hours before!!

**Comment by photopea** [comment]
Try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by lislmao** [comment]
after trying everything possible, i believe its because i have a far too updated version chrome. perhaps i could try a new browser.

**Comment by photopea** [comment]
What version of Chrome do you have?

**Comment by photopea** [comment]
I have to close it because of lack of details.
