### ISSUE TITLE
Add "Dither" to "Reduce Colors"

### ISSUE THREAD

**Issue by tommendenhall** [photopea/photopea#4258]
I would like the number of colors in a GIF next to the quality %. If I select 50% I get random values between 125-130 in Irfanview.  If the slider is not accurate enough let me enter integer value 1-256.
Thanks,
Tom

**Comment by photopea** [comment]
The "Quality" slider can make the file smaller, by using a smaller palette. In "Export GIF", the goal is to make the image as close to the original as possible, and as small as possible.

If you want a specific number of colors, or a specific palette, use Image - Reduce colors.

**Comment by tommendenhall** [comment]
Maybe I'm doing something wrong but when I use Image - Reduce Colors and then go to export GIF I no longer have the ability to dither the image? I think it's because dither only changes pixels in close proximity. The quality slider allows me to limit colors and dither.

**Comment by photopea** [comment]
Maybe we could add "Dither" to "Reduce colors", but nobody asked for it yet :/

We also have a filter: Filter - Other - Dither, but there are only specific palettes.

Why exactly do you want e.g. 115 colors in your GIF? Why do you mind if there is 114 or 116 colors instead? When there are only 3 colors in your image, you can not get 115 colors in your GIF.

**Comment by tommendenhall** [comment]
More for artistic reasons than technical. When comparing images it's easier to recreate the effect if I know the exact settings. I know most people are interested in the highest quality image with smallest file size.

**Comment by photopea** [comment]
If you want a specific effect on your image, create exactly what you need inside the Photopea, do not use the compression mechanisms for creating effects.

**Comment by tommendenhall** [comment]
That's why thought dither should be part of Image - Reduce Colors.  I am not using dither for compression, it's for art. I think I have my answer so not going to repeat myself.
Thanks,
Tom

**Comment by photopea** [comment]
ok

**Comment by photopea** [comment]
I have added the "Dither" option to "Reduce Colors".

**Comment by tommendenhall** [comment]
I was not expecting this to happen at all and never so fast an update.
Thanks,
Tom
