### ISSUE TITLE
Implement Smart Adjustments (and convert Color Adjust from Sketch into PSD)

### ISSUE THREAD

**Issue by cpllan** [photopea/photopea#426]
As the title says, when opening a Sketch file the color ajust wont transfer to the PSD.

Love your tool, saves me so much time!!!! Thanks for the hard work!

**Comment by photopea** [comment]
Hi, I didn't know such thing is possible in a Sketch file. Could you please attach a Sketch file, which contains such feature? Or send it to support@photopea.com

**Comment by cpllan** [comment]
In the example sketch file the image is in black and white bacuse I decrease the saturation to "0" but when open in Photopea is showing the color 

[TEST.zip](https://github.com/photopea/photopea/files/1594735/TEST.zip)

**Comment by photopea** [comment]
Your adjustment is defined for the bitmap. Can Color Adjust be defined only on bitmaps in Sketch? Or on other objects, too?

Photopea converts bitmaps to Smart Objects, which can have Smart Adjustments. But they are not supported by Photopea yet (PP supports only Smart Filters).

**Comment by photopea** [comment]
Hi, it was implemented, Color Adjust form Sketch is transformed to Smart Adjust of a Smart Object in PSD.

By the way, PSD supports two kinds of Brightness/Contrast: New and Legacy. When you choose Image -
 Adjustments - Brightness/Contrast, you can enable Legacy to see the difference.

Can you tell me, to which kind corresponds Brightness/Contrast in Sketch?

**Comment by cpllan** [comment]
Not sure to which one correspond. Thanks for implementing! 

Will you have premium longer than 90 days? A year?

**Comment by photopea** [comment]
Can you send me a Sketch file, that contains a more interesting photo and has a custom Brightness and Contrast?

What price would you pay for Premium for a year?

**Comment by cpllan** [comment]
Not sure, just asking :) Still got left from my 90 days

Will send the file over when I get home.

**Comment by cpllan** [comment]
Ok here is the file, also I've attached a jpg of how it looks on sketch 

[photopea.zip](https://github.com/photopea/photopea/files/1710050/photopea.zip)
![desktop hd copy](https://user-images.githubusercontent.com/12215167/36015980-c08b1424-0d25-11e8-8f46-b3496f21c9b0.jpg)
![desktop hd](https://user-images.githubusercontent.com/12215167/36015981-c0ae1668-0d25-11e8-8962-1328bba6e51a.jpg)

**Comment by photopea** [comment]
Thanks! 

Could you tell me, what is the range of each parameter (Hue, Saturation, Brightness, Contrast) ? The minimum and the Maximum value.

**Comment by cpllan** [comment]
MIN          DEFAULT             MAX
HUE                         -3.14                0                     3.14
SATURATION              0                  1                          2
BRIGHTNESS             -1                  0                         1
CONTRAST                 0                  1                         4

**Comment by photopea** [comment]
Thanks!  BTW. can you send me a Sketch file, where a photo has Contrast 0.5 and another photo with Contrast 2 (all other parameters default)?  BTW. Sketch files already contain a preview inside them :)

**Comment by cpllan** [comment]
[photopea 2.zip](https://github.com/photopea/photopea/files/1711963/photopea.2.zip)

There you go.

**Comment by photopea** [comment]
Ok, thanks. I fixed it. Now it looks exactly the same! :)

**Comment by cpllan** [comment]
Awesome, thanks for everything, also thanks for all the hard work, Photopea is amazing.
