### ISSUE TITLE
tried importing a project, was able to open a new project & one part of the materials for said project, tried importing other part and then black screen

### ISSUE THREAD

**Issue by lislmao** [photopea/photopea#4260]
![image](https://user-images.githubusercontent.com/98196230/150654735-a3732b7c-66e1-44b7-a3c1-f479e435bcd5.png)

what do i do now? i cleared my cookies and stuff, nothing else happened. i even reset my computer entirely.

**Comment by photopea** [comment]
Did you try these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

E.g. can you make Photopea crash in a web browser with no browser extensions? Unless you do, I think one of your browser extensions is breaking Photopea.

**Comment by lislmao** [comment]
it doesn't have any extensions open at the moment, still not working.

**Comment by photopea** [comment]
You are clearly using extensions in your screenshot.

**Comment by lislmao** [comment]
it was after. there were no extensions the second time.

**Comment by photopea** [comment]
Can you maybe record a video of you making Photopea crash? Maybe I will know more from your video, and I will be able to repeat it myself.

**Comment by photopea** [comment]
I have to close it because of lack of details.
