### ISSUE TITLE
在edge浏览器中无法打开photopea

### ISSUE THREAD

**Issue by ihsz-OldFriend** [photopea/photopea#4261]
在edge浏览器中无法打开photopea，提示您的浏览器太旧了(没有WebAssembly)。请更新它。
我使用google打开就可以没问题，按理说edge和google是同一个内核啊

**Comment by photopea** [comment]
You have enabled "Enable security mitigations for a more secure browser experience" in your Edge. It disables WebAssembly. Photopea can not run without WebAssembly.

**Comment by ihsz-OldFriend** [comment]
Thanks very much


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "photopea/photopea"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月23日(星期天) 下午5:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [photopea/photopea] 在edge浏览器中无法打开photopea (Issue #4261)





 
You have enabled "Enable security mitigations for a more secure browser experience" in your Edge. It disables WebAssembly. Photopea can not run without WebAssembly.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
