### ISSUE TITLE
How to close that empty grey window with only "Change Consent" button in it?

### ISSUE THREAD

**Issue by Zokec** [photopea/photopea#4267]
How to close that empty grey window with only "Change Consent" button in it? I was very happy to use Photopea some days ago, but now suddenly there is that big empty area with button Change Consent. I don't even know what is that and why I need it, if I just want to edit my own photos. I can open or close anything else in Photopea, but this big grey empty box is there and I can't close it. WHY? Please tell me how can I close it, so I can use my whole screen to edit photo, without need to buy now wide monitor, just to be able to edit my photo in Photopea, because I can't close that big empty window on the right side! Thank you! =:-O

**Comment by photopea** [comment]
What is a grey empty window? Could you send use a screenshot of what you see?
