### ISSUE TITLE
Can't Open PSD

### ISSUE THREAD

**Issue by DHV123** [photopea/photopea#4269]
Whenever I try to open this PSD on Photopea it says  Unknown file format: "/u0000/u0000/u0000/u0000 and then it says 0 bytes in File Explorer, what can I do to get it back?

**Comment by photopea** [comment]
I think your PSD is damaged, it is empty and has 0 Bytes.  You probably closed Photopea too early, while there was still written "Saving ..." at the top. You should not close Photopea until the message "Saving ..." disappears.

**Comment by DHV123** [comment]
> I think your PSD is damaged, it is empty and has 0 Bytes. You probably closed Photopea too early, while there was still written "Saving ..." at the top. You should not close Photopea until the message "Saving ..." disappears.

That must've been the problem, I remember closing it a bit early. Thank You

**Comment by DHV123** [comment]
> I think your PSD is damaged, it is empty and has 0 Bytes. You probably closed Photopea too early, while there was still written "Saving ..." at the top. You should not close Photopea until the message "Saving ..." disappears.

Is there a way to recover it?

**Comment by photopea** [comment]
I am fraid it is not possible :( Make backups of your files, if you know you will close Photopea too early.
