### ISSUE TITLE
new bug

### ISSUE THREAD

**Issue by cxrindgo** [photopea/photopea#427]
Being able to copy layers from one project to another doesn't work. It's not really a _bug_, per say, so sorry if that's a bother, but I think it would be really useful. If you can already do that some other way, please let me know!! Thank you for your hard work. <3 ;-;

**Comment by photopea** [comment]
Hi, you can copy layers between documents, see here: https://www.photopea.com/learn/layers - at the end of the page. What did you do to copy layers, before deciding that it does not work?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
