### ISSUE TITLE
How to close "Change Consent" window?

### ISSUE THREAD

**Issue by Zokec** [photopea/photopea#4270]
I was very happy to use Photopea few days ago. But today, that big grey empty window appeared on the right side, having only one "Change Consent" buttons inside it and nothing else. I don't need that and I don't even know what is that. And when I edit the photos, that empty grey area seems that it must stay there... WHY??? I just want to edit my own photos and I want to have full width of monitor available for editing, not needing to buy one wide screen monitor now, just because I can't close that big empty grey window at the right side inside Photopea, which occupies 25% of width of entire monitor. Everything in Photopea can be opened or closed, except this BIG grey empty area, which I don't know how to close it. Please help! Thank you!

**Comment by photopea** [comment]
Hi, can you show us a screenshot of what exactly you see?

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by Zokec** [comment]
Sorry for late response (I was busy last weeks, didn't think about editing photos).
Here is the screenshot of your program, you can see that big blank area on the right side, with big "Change Consent" button. I don't need it, I don't know how to use it, I don't want it there to occupate that big portion of the screen, which I want to use rather for editing the photo, menus, to see the photo appear bigger, as that is what I need, not that big blank area.
Do you maybe know how to close it?
Thank you.
![Screenshot 2022-03-04 at 14-19-42 Photopea Online Photo Editor](https://user-images.githubusercontent.com/98305942/156771299-5afdf962-b101-4f82-8f95-aaa1294d8f25.png)

**Comment by photopea** [comment]
There should be ads on the right side. Please, disable your adblock. Photopea would not exist today if everyone did what you do.

**Comment by Zokec** [comment]
> There should be ads on the right side. Please, disable your adblock. Photopea would not exist today if everyone did what you do.

I don't even know that I block the ads. So all this space should be ads? That's a lot. Usually people put only a banner...

**Comment by Zokec** [comment]
> You can also pay for the Premium account, it is less than 4 dollars a month.

Hmm, I already pay a lot for many stuff which I don't use at all. I used Photopea only to stretch one photo (this one above is just to entertainment, so it's not empty space in the post). If I would start to use it more, then maybe.
Thank you until then.

**Comment by photopea** [comment]
Ads never take more than 15 percent of th screen. You probably made your window smaller
