### ISSUE TITLE
Ugly UI

### ISSUE THREAD

**Issue by alixsep** [photopea/photopea#4272]
Hi, before anything thanks for creating this awsome project.

I personally don't enjoy the looks of photopea, I am a frontend developer and I want to completely redesign the whole website.
It would be a huge honor if I can contribute to this project.

I can show figma UI renders if Interested.

**Comment by photopea** [comment]
Hi, sure, it sounds great! Show us what you created :)

**Comment by avagp** [comment]
I am going to follow this issue out of curiosity :P

**Comment by nomandhoni-cs** [comment]
@avagp let's see how photopea change

**Comment by alixsep** [comment]
![PPRD Final](https://user-images.githubusercontent.com/59757582/151253228-21d95dab-073f-4ead-8c55-b0e6a5b2fa81.png)

I didn't go into full detail, just wanted to show what I have in mind. Hope you like it ❤

**Comment by klade-png** [comment]
That looks really clean and nice!

**Comment by photopea** [comment]
I like what you did to a tiny logo on the left. Maybe we should use this as our main logo? But Photoshop, Affinity and Pixlr are blue, too :/
![photopea_intro](https://user-images.githubusercontent.com/15955558/151270453-f2ebe5b2-c20c-43e1-bd1d-7e5a5a86bfc4.png)

**Comment by alixsep** [comment]
I chose blue because the grays I used in that design got a little bit of blue tone, green tone looked ugly to my eyes. but anyways, other than logo, any comment on the rest of the design?

**Comment by alixsep** [comment]
and no please don't change the logo to blue. the green tone is good because pea is also grean. so photopea should be green i guess 😅

**Comment by Sheldonimo** [comment]
It seems to me a very modern and minimalist design, I love it

**Comment by avagp** [comment]
I like it!

**Comment by SanyamPunia** [comment]
That's a really nice design

**Comment by avagp** [comment]
> and no please don't change the logo to blue. the green tone is good because pea is also grean. so photopea should be green i guess 😅

Or maybe, keep the green, but make it more vibrant, like glow, as the blue one does

**Comment by avagp** [comment]
Maybe we can have a closed-beta testing?  :) So we give feedback

**Comment by photopea** [comment]
@alixsep I have implemented some of your ideas into www.Photopea.com . I deleted unnecessary borders, added round corners at some places, etc. 

BTW. there are color themes in Photopea: More - Theme - ....  I have added your colors as the blue theme. What do you think?

BTW. do you have an idea for the design of windows? E.g. the Color Picker window?

**Comment by alixsep** [comment]
@photopea !!!!! thanks!!!! I am happy that I had an affect on the project! yes it looks better and that's great!

Yes I have an idea for the color picker too. I will design any part of the UI if you ask me. may I get added to contributor's list? 🙏 I will dedicate some good time working on photopea.

**Comment by photopea** [comment]
Sorry, we do not have any contributors list.  The list here on GitHub are just some random people.

There is no need to "dedicate good time". I am just asking if you or anyone else has an idea about how could a window in Photopea look like :) I can not promise, that I will make it exactly as you suggest.

Also, what about buttons, like the "OK" button? They are "3D" now. I think making them black is wrong. The text input, and the dropdown menu are already black, and I think a button should look differently.

**Comment by alixsep** [comment]
Alright, it's late night now for me, imma design a demo tomorrow 😅❤

**Comment by avagp** [comment]
@photopea can you please recheck the light theme, because the new inbetween lines does not look correct in this theme, please take a look in comparison:
![image](https://user-images.githubusercontent.com/11801254/151480031-6b4bd823-4b87-4092-a7ac-2bc0e14ea3a7.png)
![image](https://user-images.githubusercontent.com/11801254/151480037-1feaa8aa-d515-4e3c-8df1-eb77d0ae6077.png)

**Comment by MichalSZZ** [comment]
It should to be some changes in panels tab.

1. Pointer cursor like when you are over layer in layers tab (when  you can do something like "click" there should to be cursor telling that)
2. Hover effect on inactive tab. I am showing that on my screen added below. With cursor pointer, it can be a hover effect creating clickable area of a button (I used an active tab color with a 0.3 opacity)
3. In path panel it should to be a little space bellow. Like in layers palette - 6px of space between Layer tab and blending option select.
![pannels](https://user-images.githubusercontent.com/38118273/151521263-0642ea0a-05d5-49f0-8f21-7a8fe3d72c18.png)

In general - all changes are going in a good way - but in UI it should to be added not partly - because it makes chaos in many places.

**Comment by photopea** [comment]
Ok I did it as you say.

**Comment by MichalSZZ** [comment]
No, you didn't :)

- There isn't a pointer cursor (hand)
- The hover state is like an active. It has full color and is sticky to the panel.

**Comment by photopea** [comment]
I think the pointer cursor is wrong. Browser tabs in chrome also dont have the pointer cursor. The hover state is the same as active, which means it can be activated and become a new active tab.

**Comment by mustafaGFX** [comment]
> ![PPRD Final](https://user-images.githubusercontent.com/59757582/151253228-21d95dab-073f-4ead-8c55-b0e6a5b2fa81.png)
> 
> I didn't go into full detail, just wanted to show what I have in mind. Hope you like it ❤

yesssss that looks very clean, I have been having a problem with the UI since I started using photopea and now it looks very very good, goo job and i hope photopea l will look that clean one day

**Comment by avagp** [comment]
@photopea just out of curiosity, why it is not possible or why you prefer not, to change the whole UI like @alixsep proposed?

**Comment by mustafaGFX** [comment]
> @photopea just out of curiosity, why it is not possible or why you prefer not, to change the whole UI like @alixsep proposed?

I have a guess on this point, and I hope my words are not disrespectful and offensive, the creator of photopea doesn't wanna be "one of the creators", he wants to always be the one-person creator of a very hard-to-make app.
that's why he only get's inspiration of whatever you give him of ideas, suggetions, advices

it's a good Vision but nothing can be "perfect" by only one person, or that's how I see it :/

**Comment by photopea** [comment]
@avagp Every change requires a lot of work on my side. I have implemented only the "easy parts", which have a big effect, and I could do them in a couple of hours.

That design is not the "desing of the current Photopea". The vertical bar with Characters, Paragraphs, Glyphs ... is missing. Many tools are missing in a toolbar. I think it is wrong to have so many swatches, with a little space for layers.

Icons in a toolbar are too big, I think it is better to have smaller icons, so we can fit more tools simultaneously.

Also, I am not convinced about replacing all our icons for these icons. It is not clear who made them, and how many other apps are using them. Also, I think that many of these icons might be hard to understand to people coming from Adobe Photoshop.

If you are talking about the blue-ish desing, it is implemented in More - Theme - Blue.

**Comment by photopea** [comment]
@alixsep what font did you use? Is it a free font? It seems to be a bit smaller than our current font, and I am not sure it is good to make the font smaller :/

**Comment by avagp** [comment]
Thanks for sharing your creative process @photopea :)

Thanks for being so open to suggesstions!

**Comment by MichalSZZ** [comment]
> [...] The hover state is the same as active, which means it can be activated and become a new active tab.

I tried to hover tabs on Chrome, FF and Edge on Windows and they have not the same behavior as yours. When user is over the inactive tab - the tab only change color a little on hover. It not look like the active tab. 

About your decision about cursor - I agree.

**Comment by yikuansun** [comment]
I'm no UX designer, but I feel like the popup windows, especially the title bars of them, feel outdated:
![image](https://user-images.githubusercontent.com/38194363/152659416-0c40d022-eab5-4cec-b89e-7d4122f1bad5.png)
I've noticed that many modern "sleek" designs stray away from gradients. But, who am I to judge. @alixsep I'd be interested in your opinion on this.

**Comment by photopea** [comment]
@alixsep Are you still here? Do you have any ideas about the style of windows?

**Comment by yikuansun** [comment]
@photopea I was thinking maybe you could override the default `:focus` outline effect? Even something simple, like adding a `1px solid` border (and setting `outline` to `none!important`), is a good-looking alternative to the default. Of course, a more ambitious effect like an animated underline or shadow would be cool.

Here's an example of a simple `:focus` effect, where I just modify `border` and `color`.
![image](https://user-images.githubusercontent.com/38194363/159137644-89a4fa1d-0d85-4b0c-9ee8-f11c2db93598.png)

**Comment by photopea** [comment]
@yikuansun Where exactly should it be applied? When I enter any text box in Photopea, there is a border (white in Chrome, blue in Firefox).

**Comment by yikuansun** [comment]
@photopea Yeah, there's a default "border," I just don't think it looks very good in general, and it also interrupts the native app feel of Photopea.

For instance, try out these CSS rules and compare them to the status quo.
```
input, textarea, select {
    background-color: var(--bg-input);
    color: var(--text-color);
    border-radius: 3px;
    border: 1px solid var(--bg-input);
    transition: border 0.5s;
}

input:hover, textarea:hover, select:hover {
    border: 1px solid var(--text-color);
}
```
This is just a simple example, you can be a lot more ambitious about it if you want; here's a nice article on the possibilities: https://css-tricks.com/having-a-little-fun-with-custom-focus-styles/

**Comment by photopea** [comment]
Current borders in Photopea look different than the ones in your screenshot. Could you show me, what exactly you dont like, and how do you want it to look instead?

**Comment by yikuansun** [comment]
Here's the status quo (in Brave, same as Chrome but the `outline-color` is white instead of orange):
![image](https://user-images.githubusercontent.com/38194363/159187579-2a52426d-9385-494d-8ef8-3bb8bc3f6d04.jpg)
I mean, it's fine, but it's the default style and looks old and not clean.

Here is a simple `box-shadow`, as mentioned in my previous comment:
![Layer 1](https://user-images.githubusercontent.com/38194363/159187577-f6bf8a73-ef98-4fed-9dcf-70a79c1bcdc1.jpg)
Along with a smooth `transition`, it would look pretty cool and much cleaner.
I propose defining a new CSS variable, `--accent-color`, and making this the color of the `box-shadow`s as well as the slider, checkbox, and other components which currently just use the default HTML colors.

**Comment by photopea** [comment]
Ok, I have added your style with the hover effect and a transition. It does look pretty cool.

Regarding a new color for it: I am afraid that it might be too colorful, what do you think? On the other hand, I could use such color as the left border for the current tool in a toolbar (see the first image at the top).

**Comment by yikuansun** [comment]
@photopea Sorry, I was being a little careless when typing the code snippet... the new rule was meant for `:focus`, not `:hover`. Though it would look good with both focus and hover; how about a combination of both?
Here's the updated CSS:
```
input, textarea, select {
    background-color: var(--bg-input);
    color: var(--text-color);
    border-radius: 3px;
    border: 1px solid var(--bg-input);
    transition: border 0.5s;
}

input:hover, textarea:hover, select:hover, input:focus, textarea:focus, select:focus {
    border: 1px solid var(--text-color); /* perhaps replace with var(--accent-color) */
    outline: none!important;
}
```


> Regarding a new color for it: I am afraid that it might be too colorful, what do you think? On the other hand, I could use such color as the left border for the current tool in a toolbar (see the first image at the top).

Yeah, I realize the danger of messing with users' color perception, and I think having a mostly-grey look is good. But I would imagine that having a consistent color for sliders, checkboxes, highlighted text, and borders of focused inputs wouldn't add way too much color, especially since 95% of the UI would still be grey. I'd recommend just experimenting with it and seeing whether you like it or not. I do agree that the accent color for current tool could look pretty good. Pretty nice design by @alixsep !

**Comment by photopea** [comment]
I have updated your style and added blue strips to the toolbar.

**Comment by yikuansun** [comment]
@photopea Looks great, thanks!!

**Comment by photopea** [comment]
Thanks!

**Comment by bruce-c-liu** [comment]
Hi, I'm just a passerby browsing random github issues. Just wanted to say how awesome and receptive @photopea is to feedback on this app. Keep it up!

**Comment by osama-h-rana** [comment]
![image](https://user-images.githubusercontent.com/13495205/175699313-bd814a51-6d79-4bd8-8969-6c96454a4dbd.png)

Not sure if I should open a new issue for this but the color picker for the blending options (eg stroke color) is too perfectly aligned with the window underneath and I've been caught out by the "OK" button on the right not being the correct "OK" button to hit. 

I'd suggest either staggering the windows, or to increase the shadow effect to make the windows more prominent.

**Comment by photopea** [comment]
In your screenshot, there are still two OK buttons visible. I recommend you to just move the window elsewhere. It will be opened at the same position next time.

**Comment by osama-h-rana** [comment]
@photopea that doesnt seem to be the case: https://www.youtube.com/watch?v=4e8k_Cf4G-4

**Comment by impressivewebs** [comment]
> ![PPRD Final](https://user-images.githubusercontent.com/59757582/151253228-21d95dab-073f-4ead-8c55-b0e6a5b2fa81.png)
> 
> I didn't go into full detail, just wanted to show what I have in mind. Hope you like it ❤

@alixsep Was wondering if you could comment on this issue I opened with the design: https://github.com/photopea/photopea/issues/5453

Any thoughts on the UX for that the active vs. inactive file?

**Comment by TheRadicalDreamer** [comment]
I remember this issue.

I really like the icons they have here.

So i was wondering, @photopea, i know you like to be similar to Photoshop, so users can change platforms without much friction. But just like Google Docs tried years ago to be just like MS Word, at some point they pivoted and began to work to become different in their own way (not only aesthetically, but also functionally). Do you think that Photopea will take that same product development route, and begin to differentiate from Photoshop at some point? Like for example using another set of icons, like the ones @alixsep used of the mockup? Or adding new functions?

I am just wondering :)

**Comment by camoody1** [comment]
> Do you think that Photopea will take that same product development route, and begin to differentiate from Photoshop at some point? Like for example using another set of icons, like the ones @alixsep used of the mockup? Or adding new functions?
> 

My own totally unasked for opinion on this question is that it would be a big mistake to drift too far from the Photoshop esthetic if at all possible. What makes Photopea so great is that it's easily accessible for users coming from using Photoshop either in school or at work when they can't afford it at home. It's great to be able to hop onto YouTube, search for a Photoshop tutorial and know that 90% of that tutorial will perfectly translate to Photopea.

**Comment by photopea** [comment]
@TheRadicalDreamer it is not clear who made these icons, and if that author will allow us to use them (in a commercial product). It really needs to be figure out, we can not just use these icons like that.

Or we could draw new ones in a "similar style", but the design contains only 15 icons, and there are 56 tools in Photopea, so we still need to invent 41 icons ourselves. Unless someone does it for us :)

**Comment by TheRadicalDreamer** [comment]
There's no harm in asking :)


@alixsep?

**Comment by photopea** [comment]
Maybe someone can make a browser extension, which will change the Photopea font to some else font.

**Comment by camoody1** [comment]
> Maybe someone can make a browser extension, which will change the Photopea font to some else font.

Nah. You would just tell everyone to use Incognito Mode to disable it, anyway. 😂

**Comment by photopea** [comment]
We never told anyone to use the Incognito Mode! We ask people to try the Incognito as a proof that Photopea can run properly without their extensions :)
