### ISSUE TITLE
what version of chrome is photopea running on?

### ISSUE THREAD

**Issue by lislmao** [photopea/photopea#4273]
Wondering what version of chrome Photopea is currently supporting because I'm currently trying to run it on Version 97.0.4692.91 and it's not running for me without extensions or after clearing my cookies and cache.

**Comment by photopea** [comment]
I just tried to open Photopea.com on Chrome 97.0.4692.99 and it seems to work fine.

What exactly do you see when you open www.Photopea.com ?

**Comment by lislmao** [comment]
okay so i can open it and create a new project as seen here, 
![image](https://user-images.githubusercontent.com/98196230/151050770-cb0cbf36-c6b6-4a6a-9839-ef4160192dc5.png)
but then fades to a dark screen ( as seen below ) when i try opening something from my computer 
![image](https://user-images.githubusercontent.com/98196230/151050900-56619290-6a1e-4938-881f-769687bd79db.png)

**Comment by photopea** [comment]
What exactly are you opening from your computer? Is that file larger than 2 GB?

**Comment by lislmao** [comment]
The file is about 1.1mb.

**Comment by lislmao** [comment]
i have tried it in incognito mode! and it just stays on the blackscreen. i even uninstalled all of my extensions.

**Comment by photopea** [comment]
Can you send me your file to support@photopea.com ?

**Comment by lislmao** [comment]
already sent the email.

**Comment by photopea** [comment]
I am very sorry. There was a bug in our GIF decoder. Decoding your GIFs resulted in an infinite loop.

It should be fixed now.
