### ISSUE TITLE
Canvas size keeps reducing itself from 24x36 to 11x17

### ISSUE THREAD

**Issue by GregSimonis** [photopea/photopea#4274]
I am working with a 24x36 (canvas size) plan as a PSD file. As I edit it, it resizes itself to 11x17. I can resize the canvas back to 24x36 YET for the background image layer, I lose anything outside of the 11x17. Everything was working fine until I drew the sidewalk area in.
1. How do I fix this?
2. Why is it doing this
The 1st image below shows the file AFTER being resized to 11x17. The 2nd image below shows the file AFTER I resize it back to 24x36, in which the background image displays nothing outside the 11x17.
![CanvasKeepsResizingFrom24x36To11x17-11x17view](https://user-images.githubusercontent.com/98435930/151084804-7d4c1d05-3f4d-4ded-976d-49826d4d8736.PNG)
![CanvasKeepsResizingFrom24x36To11x17-24x36view](https://user-images.githubusercontent.com/98435930/151084807-5485955d-7722-4069-8595-3adc8c118dce.PNG)
?

**Comment by GregSimonis** [comment]
I started over from scratch rather than take more time to figure out why it did this.

**Comment by photopea** [comment]
Could you describe steps how can I make it happen at www.Photopea.com ?

Maybe your browser extensions are breaking Photopea, see https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/
