### ISSUE TITLE
Saving windows not closing 

### ISSUE THREAD

**Issue by loraine19** [photopea/photopea#4275]

**Comment by photopea** [comment]
Hi, what should I do to produce this problem myself? There is no saving window after I open www.Photopea.com

**Comment by loraine19** [comment]
i don't know.
but that happend after saving or auto saving and the windows ``saving... "
don't close.
So I can't use photopea and I have to restart and lose all my work ...

**Comment by photopea** [comment]
Could you do exactly what you did again, and see if it happens again? We really need some hints how to make it happen. How much RAM do you have?

**Comment by photopea** [comment]
I have to close it, because of lack of details.
