### ISSUE TITLE
Desaturation not working since yesterday

### ISSUE THREAD

**Issue by olem78** [photopea/photopea#4276]
Hi, Thank you for this fantastic online app
I was working on yesterday and some new buttons appeared a few minutes in the tool bar. 
I thaught  about an update of Photopea
Since all the sub menu "layer / adjustments" is down 
Thanks for your help
Olivier

**Comment by photopea** [comment]
Hi, I opened an image in Photopea and pressed Image - Adjustments - Desaturate, and it works.

What should I do to see the problem?

**Comment by olem78** [comment]
Hi
Thanks for your quick answer!
Sorry for that. I use Photopea on chrome since months and I really love it.

I tried to open my psd file on *chrome* and *Firefox* and some image /
adjustments do strange things or nothing at all on both:

For ex: image / adjustments/Desaturate = nothing

Best regards
Olivier

example : before
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]

Hue/Saturation
[image: image.png]
[image: image.png]
Saturation can be '100' but can't be lower than '0'


*Olivier Lemoigne*
Consultant - chef de projet web
*06 59 51 54 14*
***@***.*** ***@***.***>

  SIRET : 537 409 773 00026

**Comment by photopea** [comment]
Please, open Github.com in your browser and reply there.

You are replying with emails, but to what address are you sending these emails? It is not support@photopea.com and we did not receive your images.

**Comment by photopea** [comment]
I have to close it because of lack of details.
