### ISSUE TITLE
movement tool, text tool and layer selection/clipping masks

### ISSUE THREAD

**Issue by Qurasdigital** [photopea/photopea#4277]
hi ive been using photopea for my work almost every day and I've been having some persistent issues 

1) movement tool

occasionally when using the movement tool whenever I move an object it makes a copy of a new layer and puts that in the new location
this happens with both arrow key and mouse dragging movements and means I have to delete all the duplicates 

2) clipping mask
this issue happens in tandem with issue 1  whenever I click on a layer to select it toggles a clipping mask every time the layer is left-clicked

3) text tool 

trying to select text becomes impossible sometimes as clicking on the text box whilst the text tool is open moves the scaling point which is in the centre of the box by default, so I am unable to fully interact with the box

these issues each happen multiple times a day, ive tried closing are reopening photopea, turning on and off the computer, refreshing and clearing cashe on the browser version

these issues are on both browser and pc version

**Comment by photopea** [comment]
If you hold Alt before moving a layer, it will create a copy of a layer.

If you hold Alt before selecting a layer (in the Layers panel), it will turn on a clipping mask on it.

It sounds like Photopea thinks you pressed Alt (but you did not). That is really strange. What web browser and operating system are you using?

**Comment by Qurasdigital** [comment]
im using google chrome, when i use it through search engine, but i mainly use the desktop version

**Comment by Qurasdigital** [comment]
currently on windows 10

**Comment by photopea** [comment]
Did  it ever happen in a browser with no browser extensions? E.g. can you make it happen in the Incognito mode?

**Comment by MichalSZZ** [comment]
I have the same issue from time to time. I have clear (without any extensions) new Chrome on Win 10. 
But I know exactly what is happening and i have my own trick that works 10/10. 
When I see layers copying themselves without reason (when dragging) or transforming from center etc.

Then I am pushing very fast the left ALT button. And it works again.

It seems for me that ALT is sometimes don't turn off.

**Comment by photopea** [comment]
Maybe you press Alt, enter a text box, and release Alt inside that text box. Is it possible?

Photopea is not aware of keys, that are pressed or released in a text box. E.g. if you press Ctrl+A in a text box, it selects a text instead of creating a selection of the whole image.

**Comment by photopea** [comment]
I have to close it because of lack of details.
