### ISSUE TITLE
Can't rename layers on multiple pc's laptops

### ISSUE THREAD

**Issue by PMSYT** [photopea/photopea#4279]
Every time I try to rename a layer the double clicking simply doesn't allow to change the name easily, I have to spend 20 minutes clicking over and over again until a miracle happens which is annoying to say the least. All I ask is for there to be a way to change the layer name without double clicking via setting or something if not then I'll be forced to stop using Photopea since this issue is completely ruining my experience. Hope you can help.

**Comment by LordAlpargata** [comment]
I have the same issue, when i double click the img of a gif file to change names it doesnt allow to, my file has less than 1000 layers (580 to be exact) here are my specs 

Processor	Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz, 3401 Mhz, 4 Core(s), 4 Logical Processor(s)
Installed Physical Memory (RAM)	8.00 GB
GPU 	NVIDIA GeForce GT 730


![PFuJ11m 1](https://user-images.githubusercontent.com/57241015/151550775-5dfad2a4-f52f-4c43-b5ed-a741af72b486.gif)

**Comment by photopea** [comment]
It should be fixed now. Selecting a new layer can still take a while, but once the layer is selected, double-clicking the name should work instantly.

**Comment by LordAlpargata** [comment]
It's ok now, thanks so much!!!

![X7VF6Bh 1](https://user-images.githubusercontent.com/57241015/151573415-57b39a10-ec43-4b7b-afd7-c0f0161a043f.gif)

**Comment by photopea** [comment]
BTW when renaming, you can press Enter to confirm it, or Escape to return to the old name :)
