### ISSUE TITLE
Hide Ads Panel still showing

### ISSUE THREAD

**Issue by johancodes** [photopea/photopea#428]
Hello,

I have a premium account and still see the ads panel. 

At first login, I see the panel AND the ads, and after a refresh I don't see the ads but the empty panel with the "Hide Ads" link.

So please : `if (premium) { $(adsPanel).hide(); }` 

Thank you 👍

**Comment by photopea** [comment]
Hi, it never happened to me :(  Could you please clean the cookies (and other local data) related to Photopea.com ? Or try to login in anonymous window?

**Comment by johancodes** [comment]
Cleaned all and I don't have the "go to premium" ad but I still have the empty 50px(ish) wide right panel in normal & anonymous window.

Thank you.

**Comment by photopea** [comment]
Do you see any errors in the browser console?  What browser do you use? Can you try to update it? What if you resize the window a bit?

**Comment by johancodes** [comment]
Using FF or Chrome. Have last version of both. Resized or not, no console errors and panel still visible.
I disabled Adblocker and same thing happens.

**Comment by photopea** [comment]
Is there anything "odd" in the way you are using Photopea? Could you send us the screenshot how it looks?

**Comment by johancodes** [comment]
![hide-ads](https://user-images.githubusercontent.com/7516373/34260313-bd3b0d88-e665-11e7-9831-452a8f1eb496.png)

**Comment by photopea** [comment]
When you have a Premium, there should be a message, for how many days your Premium account remains. You have no such message in the Account window, i.e. the system thinks you have no Premium.

Photopea identifies you by your email. If you log in with two different emails, they are considered as two different accounts. Your Premium was bought for ondem....jd@gmail.com , but there is another account with your name and an email jod...@gmail.com . 

Could you change your Facebook / Google / GitHub settings, to make them all give us the same email?

**Comment by johancodes** [comment]
Oh yeah, I had two gmail accounts opened and it logged in on the first one. Forgot on which I was premium.
You're right, it works fine.
Sorry about that.
Thank you.

**Comment by photopea** [comment]
No problem. I am glad we solved it.
