### ISSUE TITLE
Today's Update Breaks Photopea's Text Features

### ISSUE THREAD

**Issue by ManasMalla** [photopea/photopea#4281]
Photopea is a very useful tool and aids many like me and I use photopea almost everyday and recommend it to many of my friends and family. I have been able to work on photopea without any issue till yesterday. But the UI update which has rolled out today on photopea seems to break the features related to text : 
Unable to change text size or any other parameter related to text (such as leading, trailing, stroke, etc) by using the text field. The text disappears even if reducing the text size but doesn't happen when using the sliders.

**Comment by photopea** [comment]
Oh, I am soo sorry. It is fixed now.
