### ISSUE TITLE
Crop tool usability (resize vs rotate)

### ISSUE THREAD

**Issue by Nu11u5** [photopea/photopea#4283]
The crop tool allows resizing the crop area as well as rotating it.

To resize the crop area the user must click on the resize handles specifically (on each corner or middle of each edge), and the click zone is not very large (only a few pixels).  In contrast the user can click *anywhere* on the edge of the crop area (or a significant portion of the screen outside of it) to rotate it.  This behavior seems inverted.

It makes little sense that the most common operation (resizing) implements <1% of the clickable area as compared to the rotate operation.

Please look into making the crop tool resize operation easier to use, and harder to use the rotate operation by mistake.

**Comment by Nu11u5** [comment]
Example case:

I've just positioned and resized the crop tool on 3 of 4 edges where I want it.  When I go to click the 4 edge's resize handle I miss-click and perform a rotate instead.  Now the crop tool is no longer square, and I have no way of returning it to the original position except by "eyeballing it".  The only option is to cancel the crop tool and start over.

**Comment by photopea** [comment]
I absolutely agree with you. I made the "touch area" of these points much larger. It should be easier to move them now.
