### ISSUE TITLE
please, I'm beggin you

### ISSUE THREAD

**Issue by raabe-ctrl** [photopea/photopea#4284]
please please please with all flowers and love in the world. Could you please add a function of export files as .eps?
  I'll explain.
  I'm a freelancer, just got a new client. He wants me to send my art with the editable file in .eps, so he can open it on Illustrator. I said I use photoshop, not because I wanted to tel a lie, but because I didn't wanted to explain that I use a free online advanced photo editor, that does exactly the same that photoshop does (...except for exporting an .eps file). I admit I also thought that he wouldn't take me seriously if I told him I don't use Adobe.
  So, I'm sorry, I'm confessing all my sins now, but pLEASE FOR THE SAKE OF MY job, pretty please, pLeAsE let me export it as .eps!
  please ;-;
  Now that I've done away with all my dignity, I just want to say thank you for photopea, this big online amazing gift.
  (And I'm never gonna say that I use photoshop in my life, EVER AGAIN.)

**Comment by raabe-ctrl** [comment]
![meme-crying-cat-2-1](https://user-images.githubusercontent.com/91345712/151709778-1365b244-acea-4b05-9e9c-6516d93d40ae.jpg)
plwease

**Comment by photopea** [comment]
EPS format was a predecessor of the PDF.

There is no "Editable EPS".  There are AI files, which are embedded inside EPS or PDF files, and only Adobe Illustrator can extract the AI file out of EPS or PDF, and let you edit it.

Can you export a PDF from Photopea, rename it to ".AI", and send it to your client?

Also, can you export an SVG? SVG files are editable in Illustrator and other editors.

**Comment by raabe-ctrl** [comment]
thank you for your answer. My client accepted me to send the files in .psd. I didn't knew pdf could be editable, I'll try that. Thank you so

**Comment by photopea** [comment]
If they accept PSD, use PSD. Only PSD can store all features of Photopea.
