### ISSUE TITLE
Photopea keep showing "saving ..." msg on Cancel save open source file

### ISSUE THREAD

**Issue by i3bdulaal** [photopea/photopea#4285]
Hello,

There is a small bug in Photopea when open source file and cancel save process, there is a "saving ..." msg keep showing for ever

<img width="1400" alt="Screen Shot 2022-01-30 at 11 25 56 PM" src="https://user-images.githubusercontent.com/73427994/151716567-6b403aa0-29ef-4a54-ab45-6b12260d57cd.png">

<img width="1400" alt="Screen Shot 2022-01-30 at 11 26 18 PM" src="https://user-images.githubusercontent.com/73427994/151716564-8bc02b2a-46ff-40f4-a01e-e7046f614b88.png">

**Comment by photopea** [comment]
You are right! I did not expect anyone to try to save the file, and then, cancel saving the file. It should be fixed now :)
