### ISSUE TITLE
Why when I change the dpi on my project to 600 dpi does it revert to 72 dpi? 

### ISSUE THREAD

**Issue by PudDud** [photopea/photopea#4286]

**Comment by photopea** [comment]
I pressed Image - Image Size, entered the DPI "600" and pressed "OK". Then, I pressed Image - Image Size, and there is still "600".

What should I do to see the problem, which you describe?

**Comment by PudDud** [comment]
Thanks. I can do a video capture to show you

**Comment by photopea** [comment]
ok

**Comment by PudDud** [comment]
Hi --

Here is my video of trying to change the dpi in Photopea. It was too large
to send in email, so here is a Youtube link:  https://youtu.be/4BMuw4teQiY

**Comment by photopea** [comment]
It says "Video unavailable - This video is private"

**Comment by PudDud** [comment]
Sorry, I thought you could see it if I give you the link. I've changed it
to unlisted now and please use the same link.

**Comment by photopea** [comment]
I can not make this happen with any of my files :( Could you send me your file as a PSD to support@photopea.com ?

**Comment by photopea** [comment]
I see you are in the middle of typing (you have entered a text layer). Could you record a video of the whole process, from opening www.Photopea.com, opening a file, and so on?

**Comment by PudDud** [comment]
DD Twosday TShirt Design Project File.psd
<https://drive.google.com/file/d/1wAi9NehtlopAwNNa5HxyoiXNfZmLagrj/view?usp=drive_web>

Sure, let me know if you need access to the file.

**Comment by PudDud** [comment]
Yes, sure, I can do that.

**Comment by PudDud** [comment]
Thanks, here's the new link to the video showing the full process from
opening Photopea, adding my file, and the same issue happens:

https://youtu.be/5Twm2XjOiqY

**Comment by photopea** [comment]
Ok I see the problem happening now. I am going to look into it.

**Comment by PudDud** [comment]
Thanks! So very much appreciated!

**Comment by photopea** [comment]
I see you have a text layer "happy", where the text size is 187499 px. If you try to edit that layer with the Type tool, Photopea crashes. The Image Size operation in Photopea tries to re-render all text layers (and it crashes on that text layer).

Did you make your PSD in Photoshop or in Photopea? Did you set the text size to "187499 px" on purpose? Could you replace your layer with another having a normal text size?

**Comment by PudDud** [comment]
Thanks, I will look at that again. I thought I fixed that error, but could
have missed it correcting other parts.

**Comment by photopea** [comment]
Once you set a "normal" text size of your text layer (you can do it in Photoshop or Photopea), you will be able to work freely with your document.

**Comment by LRostron** [comment]
I am having the same issue with students.  They are trying to save their images as PNG with a dpi of 300 but once saved it converts to a dpi of 96

**Comment by photopea** [comment]
Hi, how exactly do you determine, that a PNG file has a DPI of 96?

I think that your tool can not detect DPI of a PNG file properly, so it shows 96 for every PNG file.

Can you find a PNG image, for which your tool shows a different DPI (not 96)? This question is not related to Photopea at all.

Also, if you send an image over social networs, DPI information can get lost.
