### ISSUE TITLE
Cannot download photopea

### ISSUE THREAD

**Issue by Master-Teaz1941** [photopea/photopea#4288]
I cannot Download Photopea for a reason and on a previous issue post you said it works on opera but I have opera but it doesnt work
![image](https://user-images.githubusercontent.com/98853839/152062544-dc8296eb-0c8a-42d3-8863-df12bc19c9de.png)

**Comment by photopea** [comment]
I thought it works in Opera, but I just tried it, and it does not.

A website needs to receive a signal from a browser, that it is allowed for installation. Then, we enable that button in Photopea.

Maybe Opera will send Photopea a signal only after you visit it multiple times. Ask Opera guys about it, or switch to another browser.

**Comment by photopea** [comment]
@webinista do you know if Opera will ever fire "beforeinstallprompt" event? this webpage says it does it already, but it never happens in practice: https://developer.mozilla.org/en-US/docs/Web/API/BeforeInstallPromptEvent

**Comment by webinista** [comment]
@photopea I do not. I haven't worked for the company in nearly a decade and don't know what their current product road map looks like.

**Comment by photopea** [comment]
I will close it now. This option works only in Chrome and Edge for now. You will have to ask the authors of your browser, if you want it to be supported (as it is fully under the control of a browser).
