### ISSUE TITLE
Photoshop action doesn't work properly in Photopea

### ISSUE THREAD

**Issue by Edqe14** [photopea/photopea#4289]
I was trying out an action in photopea since I'm lazy to open photoshop but it doesn't do anything when I clicked apply. [Action file](https://cdn.discordapp.com/attachments/754045769430073415/788161541643042826/holographic.atn)

**Expected**
![image](https://user-images.githubusercontent.com/34704796/152123070-4084d13f-57b8-4c39-8ff7-8ebb8b3e892d.png)

**Actual**
![image](https://user-images.githubusercontent.com/34704796/152123281-7d0637ae-334d-4997-a833-eab703772117.png)
*yep, it dissapeared*

Devtools console when applying the action
![image](https://user-images.githubusercontent.com/34704796/152123798-6d3d762c-0c7b-4d77-93fe-c2bbdb34a7bb.png)

**Comment by Dvd-22** [comment]
I'm having a similar issue. When I transform a layer that has a Pen drawing on it, it just disappears and becomes invisible. This have been happening recently only

**Comment by photopea** [comment]
I am very sorry for the problem, your actions should run well now.
