### ISSUE TITLE
[FR] Grid Offset x,y preference for image grid

### ISSUE THREAD

**Issue by Nu11u5** [photopea/photopea#4290]
The image grid has options for "Grid Gap" in Edit > Preferences, but no option to set the x,y pixel grid offset.

Not all use-cases for an image grid need a grid aligned to 0,0.

Grid offset is offered by other image editors like Gimp.

**Comment by photopea** [comment]
Have you tried Guides? See here: https://www.photopea.com/learn/guides-grid-snapping

We have a Guide Guy: Window - More - Guide Guy, it lets you add guides automatically in a "grid" with an offset.

**Comment by Nu11u5** [comment]
Thanks for pointing out the tool - I'm not sure if it will be simpler for my workflow than a fixed grid but I will try it out.

Although now I am noticing that I cannot specify a decimal number for the grid size, only integers (even though e.g. Edit > Preferences displays two decimal digits) and instead it rounds the result.  This may seem like an odd need for a raster image, but after a few grid intervals it can cause a shift of several pixels.

**Comment by photopea** [comment]
Do you want a different grid (with a different offset) for each document you work with? The Grid parameters would have to be stored inside a PSD file. However, to keep our PSDs compatible with Adobe Photoshop, we can not add new features to PSD files. So I am afraid it is not possible to have a custom grid inside each document.

**Comment by Nu11u5** [comment]
For my purposes the grid is only needed for a specific set of operations and then discarded, so I have no need for the grid to be saved with the file.

That said, it could be useful if the grid was per-window/tab but not a requirement.

With the file limitation in mind I can see how using the Guide Guy tool to create a grid is a compromise for a general use-case.  Does the PSD format support decimal guide positions?

---

My specific uses case is I am editing grid-maps for virtual tablet top (VTT) gaming.  The maps were arbitrarily rescaled before publishing so the maps' grid are no longer pixel-aligned.

My workflow in GIMP is:

1. Enlarge the canvas and center the image
2. Measure the map's average grid size (map grid edge-to-edge divided by the number of cells)
3. Set the editor's grid size (always a decimal)
4. Set the editor's grid offset to align with the map (updates in real-time in GIMP)
5. Crop the canvas on the gridline immediately outside the image bounds
6. Rescale the image to the needed scale
7. The map is now perfectly scaled and aligned for import into the VTT

I would like to be able to do something similar on Photopea.

**Comment by photopea** [comment]
I think you should use the Guide Guy for this. Guides can be decimal. They are saved inside a PSD file. They are not exported with the PNG, etc.

**Comment by Nu11u5** [comment]
When entering a decimal into Guide Guy it gets rounded to the nearest integer.

**Comment by photopea** [comment]
I recommend you to learn Photopea at www.Photopea.com/learn to find out what is possible, and how to do your task in a Photopea way. Rather than asking us to add GIMP features, so that you can do your task in a GIMP way.

Why dont you use GIMP, when you already know how to do it there?

**Comment by Nu11u5** [comment]
The tutorial page doesn't have any information about the Guide Guy tool.

I would like to learn how to accomplish my task in Photopea, both because it is a promising app and also I want to use an app that works well on Chromebook.

Also I am wondering if the issues mentioned in my last post are bugs or just a misuse of the tool.

**Comment by photopea** [comment]
I belive your task must be doable in Adobe Photoshop, and Photopea should have an analogy to pretty much all features of Photoshop by now. So you just need to learn how to use Photoshop or Photopea. Maybe you do not need guides at all.

**Comment by Nu11u5** [comment]
Is there documentation for the Guide Guy tool?  This feature seems unique to Photopea (or does the equivalent feature in Photoshop have a different name?).

**Comment by photopea** [comment]
You can add decimal values into the Guide Guy now. The Guide Guy is our alternative to the Guide Guide plugin: https://guideguide.me/
