### ISSUE TITLE
Merging layers - When merging layers I get a square (same as someone else)

### ISSUE THREAD

**Issue by Lambchop9999** [photopea/photopea#4291]
When I try to merge two layers it highlights the top layer and deselects the bottom- nothing merges

Hoping to teach this tomorrow. Thanks

<img width="330" alt="Screen Shot 2022-02-02 at 7 45 29 PM" src="https://user-images.githubusercontent.com/98933075/152278343-e0894c0d-6327-48fc-94c3-46d3716335e1.png">

**Comment by photopea** [comment]
Hi, I have selected two layers, right-clicked one of them and choose "Merge Layers", they were merged into one layer.

What exactly did you do?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
