### ISSUE TITLE
Exporting

### ISSUE THREAD

**Issue by C41T** [photopea/photopea#4292]
It's no longer letting me export what I have made in photopea.
Not sure if anyone else is having the same problem.
I've tried opening and closing photopea over and over and still the same thing.

**Comment by photopea** [comment]
Hi, do you mean using File - Export as - JPG? Or something else? What happen instead? Do you see a message "We are not letting you export", or your computer shuts down, or something else? :D

**Comment by photopea** [comment]
Try this first: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by C41T** [comment]
Yeah I've tried, I also looked to see if other people had the same problem and tried what was suggested, nothing worked, I has exported a file with png earlier and it was fine, and now it just won't work. If need be I can show a screenshot of what it looks like when I press export.

**Comment by photopea** [comment]
ok show me, or record a short video.

**Comment by C41T** [comment]
![image](https://user-images.githubusercontent.com/98938703/152335655-639a2b1f-d16c-4747-bf7c-b40921838914.png)
That's what it comes up with, and when I press save it does nothing, like nothing comes up or anything, it jut does nothing at all.

**Comment by photopea** [comment]
What browser and operating system is this? Is it a phone? Were you ever able to save a file in the past?

Sometimes, a browser saves the file in the background, without letting you know. It depends on how you configure your web browser (or maybe your browser can not be configured at all).

**Comment by photopea** [comment]
Could you please confirm again, that you have tried it in the Incognito Mode and it does not work?

**Comment by C41T** [comment]
I have tried incognito, I've tried disabling the web extensions, haven't tried on phone because I need to keep it on laptop. Is there any other way I could fix it?

**Comment by photopea** [comment]
What browser and operating system is this? Were you ever able to save a file in the past?

**Comment by photopea** [comment]
Could you maybe record a short video of you opening Photopea.com , opening your file and trying to export it?

**Comment by photopea** [comment]
I have to close it because of lack of details.
