### ISSUE TITLE
Google Drive Shared Drive NOT AVAILABLE

### ISSUE THREAD

**Issue by pedro-tugame** [photopea/photopea#4293]
@photopea
I want to start by thanking you for creating photopea and keep improving it :)

Any change that you could make a deeper integration with Google Drive?

At the moment we can't open/browse files from a "shared drive" only files from "my drive" and since our team has all the files on "shared drive" it means that every time that I need to use photopea I need to download files or copy them inside google drive .

Thanks and have a great day.
Pedro

**Comment by photopea** [comment]
Could you test it? There is a new item on the left side.

**Comment by photopea** [comment]
It should work now.

**Comment by pedro-tugame** [comment]
It's working... thanks

**Comment by PedroHase** [comment]
Hi @photopea, we are having a similar issue where shared drives are not accessible to us after giving permission (personal Drive works):

<img width="735" alt="image" src="https://user-images.githubusercontent.com/73759210/163714404-863606b6-1006-42e6-a7cc-2b48d2b9a1df.png">

We tested this on both MacOS and Windows, as well as on Chrome and Firefox.

**Comment by dobrichovsky** [comment]
> Hi @photopea, we are having a similar issue where shared drives are not accessible to us after giving permission (personal Drive works):
> 
> <img alt="image" width="735" src="https://user-images.githubusercontent.com/73759210/163714404-863606b6-1006-42e6-a7cc-2b48d2b9a1df.png">
> 
> We tested this on both MacOS and Windows, as well as on Chrome and Firefox.

Hi @PedroHase, are you sure these are actually shared _drives_ (of an organization, be it business/educational/non-profit - you can't create shared drives from a personal account) like these: https://support.google.com/a/answer/7212025?hl=en? I can see and use mine in Photopea. Other shared items should be in your personal drive; we currently don't support the "Shared with me" tab you would find in your Google drive as it's not really a folder, but a collection of files that anyone ever shared with you - but you should be able to access folders/files that someone shared with you and you added them to your google drive through the personal drive.
