### ISSUE TITLE
Transforming pen layers make them dissappear.

### ISSUE THREAD

**Issue by Dvd-22** [photopea/photopea#4296]
Hi! I'm a pretty active Photopea user and I just love it. That being said, the problem is this

Whenever I make a new line with the pen, and then try to transform it, it just magically dissappear.

Here's how it happens:
1. Make any shape with the pen tool.
<img width="178" alt="image" src="https://user-images.githubusercontent.com/75691650/152414606-48f70d7c-d671-4fa1-91d4-9d8e700e8892.png">

2. Select the layer and try to transform it.
<img width="213" alt="image" src="https://user-images.githubusercontent.com/75691650/152414660-f3594ab5-e8fe-48da-ba39-877e12261d91.png">
<img width="273" alt="image" src="https://user-images.githubusercontent.com/75691650/152414713-065ab8a8-e3ad-428a-a731-873507714e42.png">

3. You'll notice how it suddenly turns invisible and (at least on my case) it looks like a square on the layer bar.
<img width="243" alt="image" src="https://user-images.githubusercontent.com/75691650/152414758-2030e3eb-546a-4e55-932a-00cce04dafdf.png">
<img width="218" alt="image" src="https://user-images.githubusercontent.com/75691650/152414778-74f84b62-c38d-4386-8fb0-bc7e0f2932ab.png">

This has only been happening recently and it has absolutely ruined some of my projects. Would love to see it fixed.

**Comment by photopea** [comment]
Hi, I am soooo sorry  :(  It is fixed now.

**Comment by Dvd-22** [comment]
Thank you so much!
