### ISSUE TITLE
Color comes back after rotating it

### ISSUE THREAD

**Issue by SkellyNellyBoo** [photopea/photopea#4298]
When I turn the layer's saturation all the way down and then I move it or rotate it in Free Transform, the color comes back like I've never set saturation to -100. Really annoying

**Comment by photopea** [comment]
That is how the Free Transform works on smart objects. After you confirm the transform, smart adjustments and filters will be applied again.

**Comment by SkellyNellyBoo** [comment]
After I confirm it doesn't change back. It's not really problematic tho

**Comment by photopea** [comment]
Could you record a video of what happens?

**Comment by SkellyNellyBoo** [comment]
I realized there's a different problem not with Hue/Saturation. Everything works fine when I get saturation down manually, but when I use CTRL+SHIRT+U then after transforming it the color comes back.

**Comment by nothingshiru** [comment]
When WebGL is enabled, there is a limit to the image size. When image size exceed the limit, the canvas become black. 

Your image size may exceed the limit when you rotate the layer.

**Comment by SkellyNellyBoo** [comment]
The problem is about Desaturating through a shortcut and after transforming, it gets its color back for some reason.

**Comment by photopea** [comment]
Hi, I am very sorry, there was a bug, the Ctrl+Shift+U is not supposed to work on smart objects. It is fixed now.
