### ISSUE TITLE
"Invisible finger" fixed on canvas when rotated a locked layer

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4299]
To reproduce

1. Create a new project.
2. Select Move tool. 
3. Checked Transform controls.
4. Rotate current layer(the locked background layer) with finger.

Try to swipe on canvas, you'll find that you are zooming canvas, because a "invisible finger" is fixed on canvas after step 4.

---
Over the past year, I've "found" a number of ways to reproduce this bug, and I've seen other users trigger it inadvertently. It is a big problem.

I had used Figma for weeks. It can be used on browser for Windows and Android...and works with finger, like Photopea. In the weeks, I had never met such problem, which make me think that the problem is in Photopea instead of browser or devices.

I really hope Photopea can fix this problem.

**Comment by photopea** [comment]
I am very sorry, it should be fixed now. Please, let me know, if you ever find a similar problem.
