### ISSUE TITLE
Sprite Replicator Plugin

### ISSUE THREAD

**Issue by yikuansun** [photopea/photopea#4300]
Hi,

I've made the following plugin for creating complex graphics involving duplicating a texture many times:
```
{
    "name"  : "Sprite Replicator",
    "url"   : "https://yikuansun.github.io/sprite-replicator/?portal=photopea",
    "icon"  : "https://raw.githubusercontent.com/yikuansun/sprite-replicator/master/icon.png"
}
```
Here is an example:
<img width="968" alt="replicator photopea plugin screenshot" src="https://user-images.githubusercontent.com/38194363/152656903-64aea9ec-8251-4a86-9486-da3064d802e1.PNG">

Could you please add this to Photopea's list of plugins?

Thanks!

Edit: another example, showing a different kind of effect you can make:
![image](https://user-images.githubusercontent.com/38194363/152657273-07adc276-2ef4-4ee2-a745-5d1651b719b6.png)

**Comment by photopea** [comment]
That looks great! BTW. do you track a number of users of your plugin? Are there many people interested in your plugins? I think they are pretty hard to find in Photopea.

BTW. have you thought about writing tutorials about your plugins? If you write a tutorial, you can get into Google Search, and your tutorial (which leads to your plugin) would be the first thing people find when searching for "Replicate Layer". Also, you could add a link to your tutorial into your plugin, so that people can learn how to use it, and see the different effects you can make.

All these plugins (which do not exist in other software) are confusing to use, as nobody knows what they can do, and what they are good for.

**Comment by MichalSZZ** [comment]
Very helpful addon! Thanx!

I agree with Ivan - without tutorials (I like the most video tutorial but I have no problem with reading too :)) almost nobody will use those plugins.

@yikuansun is it something like this Photoshop feature? https://www.youtube.com/watch?v=BFxeIJZGUSg I saw this hidden trick few months ago and I was absolutely shocked about it.

**Comment by yikuansun** [comment]
> do you track a number of users of your plugins? Are there many people interested in your plugins? I think they are pretty hard to find in Photopea.

I don't track number of users, so I'm not sure.
As far as making plugins easier to find, maybe they could have their own panel in the menubar? I think Adobe Photoshop does this now:
![image](https://user-images.githubusercontent.com/38194363/152698153-721d31d4-7ed1-4c10-b8e1-9e0faf984fc4.png)

> BTW. have you thought about writing tutorials about your plugins? If you write a tutorial, you can get into Google Search, and your tutorial (which leads to your plugin) would be the first thing people find when searching for "Replicate Layer". Also, you could add a link to your tutorial into your plugin, so that people can learn how to use it, and see the different effects you can make.

I'm still refining my tutorial-making skills, but I have made a tutorial on Sprite Replicator that explains it and demonstrates some effects. I've added a question mark button to Sprite Replicator that opens the tutorial.

> your tutorial (which leads to your plugin) would be the first thing people find when searching for "Replicate Layer".

My videos don't get a lot of views 😢 so I don't think this will happen. But I suppose the tutorial will still help the people who do find it.

**Comment by yikuansun** [comment]
> is it something like this Photoshop feature? https://www.youtube.com/watch?v=BFxeIJZGUSg I saw this hidden trick few months ago and I was absolutely shocked about it.

@MichalSZZ I don't have Photoshop, but from the PTC video you linked I infer that it is kinda like Sprite Replicator. Sprite Replicator allows you to control X and Y variance, though, whereas it seems like the Photoshop script just spreads over the whole document area. Also, I allow blend mode control 😎

**Comment by nothingshiru** [comment]
It would be nice to have a "plugin store" panel like a app store where users can find the icon, name, description, author, etc.

**Comment by avagp** [comment]
I believe @nothingshiru hit the nail

**Comment by jointri** [comment]
Photopea plugins are just tiny snippets of javascript right? I agree with @nothingshiru that a plugin store is a great idea. Would it be possible @photopea to make it possible to work with emscripten (C or C++ code turned to javascript or webassembly with a special compiler) so C or C++ plugins can be used as well with photopea?

**Comment by yikuansun** [comment]
> Photopea plugins are just tiny snippets of javascript right?

@jointri Currently, Photopea plugins are entire web apps, embedded into Photopea using HTML's iframe component. Interaction between the plugin and Photopea runs on JavaScript's `postMessage` function.

Don't know how emscripten works, but WebAssembly is definitely an idea. Only problem is, it might not be viable cross-browser. Not sure how well C or C++ can be compiled into JS.

**Comment by photopea** [comment]
WebAssembly is a part of every modern browser: https://caniuse.com/wasm

Photopea works in browsers without WebGL, but it does not work in browsers without webassembly.

**Comment by yikuansun** [comment]
@photopea So... are we gonna get a plugins marketplace?

**Comment by photopea** [comment]
I am thinking about it. Clicking "install a plugin" would probably add a URL of the plugin + the URL of the icon into the Cookies of a browser, so that we can open the same plugin next time the user visits Photopea.

But what would be a mechanism for deleting plugins? It would be nice to track, how many people are using a plugin. We probably need a database on a server, each Install would increment the number in it, uninstall would decrement the number on the server.

**Comment by avagp** [comment]
Go on!

You are about to create an ecosystem

**Comment by yikuansun** [comment]
@photopea Thanks so much for your consideration! I'm very excited about having a plugins marketplace in Photopea.
> But what would be a mechanism for deleting plugins?

Currently, we can remove "plugins" by right-clicking their icon in the toolbar. I suppose something similar could be implemented for installed plugins? Or, the plugin could be uninstalled from the same interface that it was installed. Are you asking this question from more of a UX standpoint, or as a mostly technical problem?

**Comment by nothingshiru** [comment]
@photopea Hi. I notice you made a plugins windows... Honestly, it is far from what I expected. I think it should be a panel instead of a full screen window.

**Comment by photopea** [comment]
I have made a Plugin gallery in Window - Plugins. The interface is very similar to Free PSD Templates. Please, add your plugins there.

If someone installs your plugin, and you update it (change the JSON: name, icon URL or site URL), should all your users be switched to a new version, or should they keep using the old one? Should the number of installs start from zero, or should the old installs stay?

**Comment by photopea** [comment]
Also, please, put all your old plugins there, so that I can remove them from Window - More.

**Comment by photopea** [comment]
Just like there are PSD Templates and Plugins, I would like to let people upload "Actions", "Brushes", "Gradients", "Styles", "Patterns", "Shapes" and "LUTs". All with the same interface and same mechanisms. 

Could you come up with categories for each kind of resources? The categories will be displayed on the left side.

@MichalSZZ what do you think about this? Do you have an idea about categories for these resources?

**Comment by avagp** [comment]
@photopea why won't you put everything in the same "Marketplace"  window, and then add categories and subcategories such as Plugin, Brushes, Patterns, Templates?

**Comment by photopea** [comment]
Do you think it would be better? I think people who look for Templates probably don't need gradients, so there is no need to make a 50-pixel bar at the top (with a menu).

**Comment by avagp** [comment]
The benefits of having one place for everything, is that something can catch me an eye, that I have not looked for.

Especially if somehow you show more assets from the same author on the details page of each item.

Also, it shows how much the community is doing to improve and expand the Photopea capabilities.

Think like the app store or the play store.

**Comment by yikuansun** [comment]
@photopea Thanks so much for making the plugins gallery!! It is awesome

I think @avagp is making some good points

**Comment by MichalSZZ** [comment]
> Just like there are PSD Templates and Plugins, I would like to let people upload "Actions", "Brushes", "Gradients", "Styles", "Patterns", "Shapes" and "LUTs". All with the same interface and same mechanisms.
> 
> Could you come up with categories for each kind of resources? The categories will be displayed on the left side.
> 
> @MichalSZZ what do you think about this? Do you have an idea about categories for these resources?

It is a very cool idea to have place for that free stuff like actions, styles, gradients LUTs etc. 
For most people on the world it shouldn't load such a big repository. 

Plugin Gallery should be separated from the Assets gallery. That are two different things. 
But if somebody will find a good UI/UX solution to show that in efficient way as the marketplace - hmm why not.

There are two different asset types. One - files that have their own "Adobe file type" like ATN. And other for assets like backgrounds or icon sets. We should think about that for the future work on Marketplace.
To the assets category I have something like that in my mind:

1. Actions (with possibility to add the instruction with images - "step by step - how to")
2. Brushes (there are many people who make brushes and maybe they will add some materials - look on that site https://www.deviantart.com/tag/brushes).
3. Gradients (something like that https://coolors.co/gradients but it should to be grouped in categories)
4. Color schema (https://colorhunt.co/) but it can be as an addon with possibilities like in https://colorhunt.co/)
5. Icons sets (some of the premium authors give for free small set - for example line icons in one thickness but there are in the same style color icons, 5 different thickness and full filled - if they will have possibility to add link to their site, with place to purchase a full pack it will be a benefit for them). Of course there are many packs with Open Source or another free Icons
6. Backgrounds - in that place it can be a place for backgrounds with, for example 'paper textures', 'bokeh', 'photo studio backdrop gradient', 'wooden desks and tables', 'brick walls' etc.
7. Seamless patterns
8. Overlays (layers that user can add to the photo, with special blend mode, for making a cool 'instagram' effect). It can be a sun rays, rain drops, snow, smoke on black background, shadows (window shadows, widow shutters, plants shadow) etc.
9. Textures
10. Styles
11. LUTs

**Comment by photopea** [comment]
@MichalSZZ Thanks for your comment! But could you come up with e.g. 5 to 10 categories for Actions, 5 to 10 categories for Styles, Brushes, LUTs, etc?

**Comment by yikuansun** [comment]
Actions
 1. Color grading
 2. Retouching
 3. Selection
 4. Stylize
 5. VFX

Styles
 1. Textures
 2. Glows
 3. 3D
 4. Effect
 5. Blending

Brushes
 1. Painting
 2. Sketching
 3. VFX
 4. Shapes
 5. Weathering

LUT's
 1. Cinematic
 2. Photo
 3. Romantic
 4. Fantasy
 5. Moody

**Comment by photopea** [comment]
As I read your categories, I have no idea what they mean in most of cases. Did you make them up, or you copied them from somewhere? Maybe we should not have categories at all? People could search by keywords.

**Comment by photopea** [comment]
@hxim Do you know about this API? https://www.colourlovers.com/api  Could you create a plugin for Photopea to use their palettes right inside Photopea?

**Comment by TheRadicalDreamer** [comment]
@photopea can i say something regarding @yikuansun categories?

Don't define the subcategories now. Begin with the categories, and then along the way, you'll figure out the subcategories when each category has 20 or more items.

You might restrain the growth or the beginning of this "marketplace". 

Go on and begin :)

I know it will be a blast!

**Comment by photopea** [comment]
@TheRadicalDreamer but you know, once there are hundreds of brushes and actions with no category assigned, someone would have to go and choose a category for each of them :/ that would be a lot of work.

**Comment by TheRadicalDreamer** [comment]
I know. But that's why I said 20. Do not wait until you get 100 on each
category.

Do as you feel Ivan. I am only sharing my opinion. Either way has pros and
cons. :)

**Comment by MichalSZZ** [comment]
I agree with @TheRadicalDreamer . Maybe when we will have more content, then we can try to make categories for them.

**Comment by MichalSZZ** [comment]
@photopea and @hxim I see here that we are talking about some ideas of future plugins. I found this sites and I think that they can be cool things if their APIs can be connected with Photopea.

1. https://undraw.co/
2. https://www.opendoodles.com/
3. https://www.humaaans.com/
4. https://openpeeps.com/

**Comment by yikuansun** [comment]
In my opinion, we face a more immediate issue with the plugins gallery. @photopea As you mentioned to me before, letting users upload plugins freely and publicly allows for malware, junk, or corrupt data, which may even be uploaded by accident. First of all, the JSON file importing system seems to have no verification system. Using HTML inputs for each parameter might be better, since you can at least verify that the URL's are functional. This will also make it easier for plugin developers to view and edit their plugins. Some sort of a loose approval system could also be helpful just to prevent really bad stuff. I'd be happy to be on a "board" which helps verify plugins before they go public.

**Comment by photopea** [comment]
I have added galleries for other resources. So in the Templates / Plugins window, there is a menu at the top to switch between them. You can upload your own, too.

There is not much spam for now, but if there is, we will certainly come up with ideas how to deal with it.

**Comment by yikuansun** [comment]
@photopea Could you please add a preview of the JSON file below the Upload File button? Sometimes I can't tell if I've uploaded the right file. Another option is using text inputs instead of a file input.

Also, a smaller issue - sometimes my Creator/Brand Name gets reverted back to my original account name.
