### ISSUE TITLE
Pressure controlled flow

### ISSUE THREAD

**Issue by abhisekp** [photopea/photopea#4301]
For brush tool,

Photoshop has both opacity and flow pressure controlled.

In Photopea, we only have Opacity pressure controlled. Can we have a pressure-controlled flow as well?

Appreciate it. Thanks :)

**Comment by photopea** [comment]
Hi Abishek,

is there any difference between the Opacity pressure controlled and the Flow pressure controlled? Could you show me an image demonstrating the difference?

I know the difference between Opacity and Flow in cases, when you paint the same stroke over itself. So it makes sense to modify the opacity at each moment of a stroke. Should that be called Opacity or Flow? And what is the logic between the other one?

**Comment by photopea** [comment]
I have added this feature, it is avaliable in Window - Brush - Transfer, the "Control" parameter under the "Flow Jitter".

But it works the same as the Opacity control, they are combined.
