### ISSUE TITLE
there is an error in script using photopea. pp.js:7526 Uncaught TxLr

### ISSUE THREAD

**Issue by seossine** [photopea/photopea#4304]
I want to change the partial color of the text layer

But in Photoshop, it works, but in Photopia, it doesn't, and an error pops up.

pp.js:7526 Uncaught TxLr

this is my code.

could you check this code and this code is available in photopea?

-----------------------------------------------------

var lays = app.activeDocument.layers;

for(var i=0; i<lays.length; i++)

{

//lays\[i\].visible = false;

//lays\[i\].opacity = 50;

lays\[i\].name = "My Layer "+i;

lays\[i\].name = "My Layer "+i;

var textColor = new SolidColor;

[textColor.rgb.red](https://textColor.rgb.red) = 255;

[textColor.rgb.green](https://textColor.rgb.green) = 0;

[textColor.rgb.blue](https://textColor.rgb.blue) = 0;

if( lays\[i\].kind == 2){

	lays\[i\].textItem.color = textColor

}
}

function changeColor(start, end, Red,Green,Blue) {

//Sanity checking: is the active layer a text layer?

var activeLayer = app.activeDocument.activeLayer;

if (activeLayer.kind == LayerKind.TEXT) {

if ((activeLayer.textItem.contents != "") && (start >= 0) && (end <= activeLayer.textItem.contents.length)) {

//The indentation that the Script Listerner gives you is weird, but it's useful.

var idsetd = charIDToTypeID("setd");

var action = new ActionDescriptor();

var idnull = charIDToTypeID("null");

//The action reference specifies the active text layer.

var reference = new ActionReference();

var idTxLr = charIDToTypeID("TxLr");;

var idOrdn = charIDToTypeID("Ordn");

var idTrgt = charIDToTypeID("Trgt");

reference.putEnumerated(idTxLr, idOrdn, idTrgt);

action.putReference(idnull, reference);

var idT = charIDToTypeID("T ");

var textAction = new ActionDescriptor();

var idTxtt = charIDToTypeID("Txtt");

//actionList contains the sequence of formatting actions.

var actionList = new ActionList();

//textRange sets the range of characters to format.

var textRange = new ActionDescriptor();

var idFrom = charIDToTypeID("From");

textRange.putInteger(idFrom, start);

textRange.putInteger(idT, end);

var idTxtS = charIDToTypeID("TxtS");

//The "formatting" ActionDescriptor holds the formatting. It should be clear that you can

//add other attributes here--just get the relevant lines (usually 2) from the Script Listener

//output and graft them into this section.

var formatting = new ActionDescriptor();

var idClr = charIDToTypeID("Clr ");

var colorAction = new ActionDescriptor();

var idRd = charIDToTypeID("Rd ");

colorAction.putDouble(idRd, Red);

var idGrn = charIDToTypeID("Grn ");

colorAction.putDouble(idGrn, Green);

var idBl = charIDToTypeID("Bl ");

colorAction.putDouble(idBl, Blue);

var idRGBC = charIDToTypeID("RGBC");

formatting.putObject(idClr, idRGBC, colorAction);

var idSz = app.charIDToTypeID("Sz ");

var idPnt = app.charIDToTypeID("#Pnt");

$.writeln (activeLayer.textItem.contents);

formatting.putUnitDouble(idSz, idPnt, activeLayer.textItem.size*2);

textRange.putObject(idTxtS, idTxtS, formatting);

actionList.putObject(idTxtt, textRange);

textAction.putList(idTxtt, actionList);

action.putObject(idT, 2934, textAction);

executeAction(idsetd, action, [DialogModes.NO](https://dialogmodes.no/));

}

}

}

var textlayer = app.activeDocument.artLayers.getByName("My Layer 44");

app.activeDocument.activeLayer = textlayer;

changeColor(1,5,255,255,0);

**Comment by photopea** [comment]
Sorry, I am not smart enough to make this script work in Photopea :(

Change the color of layers simply using textItem.color = textColor;  without creating actions.
