### ISSUE TITLE
Group mask not importing from xcf

### ISSUE THREAD

**Issue by fnix2** [photopea/photopea#4305]
Please, if it's not difficult, add the ability to import group masks from the xcf format (GIMP). Presently group masks just disappear when imported from xcf.

**Comment by photopea** [comment]
Done :)

**Comment by fnix2** [comment]
[https://tmpfiles.org/dl/210787/photopea_mask_test.xcf](url)

**Comment by fnix2** [comment]
[https://tmpfiles.org/dl/210787/photopea_mask_test.xcf](https://tmpfiles.org/dl/210787/photopea_mask_test.xcf)

**Comment by photopea** [comment]
I can not download it :(

**Comment by photopea** [comment]
But I think I know what you mean. Let me know if it works better now.

**Comment by fnix2** [comment]
Unfortunately it doesn't work either.

Sorry for the bad link. [This link should work](https://drive.google.com/file/d/1peJr9tDWkeUXH7GLGlbVLYqZBn9329R8/view?usp=sharing).

**Comment by photopea** [comment]
Ok I see, it should be fixed now.
