### ISSUE TITLE
PDF with justified text not rendering properly

### ISSUE THREAD

**Issue by triosniolin** [photopea/photopea#4307]
I have a PDF I created by exporting from Word, with justified text inside a table. This PDF renders correctly in the Adobe Reader (Version 2021.011.20039) but the justified text goes off the right margin when I import into Photopea.
[Matted Pet Release.pdf](https://github.com/photopea/photopea/files/8028915/Matted.Pet.Release.pdf)

**Comment by photopea** [comment]
Your text requires the Calibri font, which is a commercial font, not available in Photopea. Photopea can not extract the font out of a PDF file at the moment. So just load your font into Photopea (File - Open - TTF file) and the text should be displayed correctly.
