### ISSUE TITLE
My saving isnt working and isnt closing

### ISSUE THREAD

**Issue by Vanquisity** [photopea/photopea#4308]

**Comment by photopea** [comment]
Did it happen more than once? Did you try to save more than one file? Did saving ever work for you in the past?

**Comment by Vanquisity** [comment]
this is my first time using Photo pea i saw a tutorial on youtube on how it works but when i tried to save my project it didnt save and the tab didnt go away ive tried many times and also different files im not sure whats going

**Comment by photopea** [comment]
Are you saving the right way? Please, read this to learn how to save: https://www.photopea.com/learn/opening-saving

If it still does not work, try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of no response from the author :(
