### ISSUE TITLE
GoPro GPR

### ISSUE THREAD

**Issue by olegvakulenko** [photopea/photopea#4310]
Hi!

Your project successfully opens GoPro GPR files. Could you share any information on exactly how to convert the source file to an editable bitmap. All my experiments give a different color reproduction and image contrast.

Thank you!

**Comment by photopea** [comment]
Hi Oleg, GPR files are DNG files with the custom compression. You should make a general DNG processor. Do you know how to work with DNG files? Have you read the DNG specification?

**Comment by olegvakulenko** [comment]
At the moment, I work with GPR in several stages. First, I convert the original file to DNG using gprtool. Then I convert the received DNG to PPM through LibRaw. All this I do with Java.

**Comment by olegvakulenko** [comment]
Unfortunately, I could not find a toolkit for native work with DNG for Java.

**Comment by olegvakulenko** [comment]
If you are using LibRaw, then perhaps the list of parameters for conversion could help me.

**Comment by photopea** [comment]
I use only my own code. I wrote my own TIFF parser, lossless JPG decoder, GPR decoder etc. in Javascript :/ There are no libraries for this in Javascript, so I had to implement everything myself.

I used this specification https://www.adobe.com/content/dam/acom/en/products/photoshop/pdfs/dng_spec_1.4.0.0.pdf

**Comment by olegvakulenko** [comment]
I'm impressed with what you've done! 
Is there anything that can help me exists in open source?

**Comment by photopea** [comment]
What do you mean? I dont know about existing open-source libraries.

**Comment by olegvakulenko** [comment]
I mean, is there any of what you've done in the public domain? I can only roughly imagine what kind of work you have done, and therefore I won’t even begin to uninhibit asking about access to this. Moreover, I don’t even know how the JavaScript code can help me? Unless you try to rewrite everything in Java...

**Comment by photopea** [comment]
I have published UTIF.js , which can parse raw sensor data out of GPR: https://github.com/photopea/UTIF.js/
