### ISSUE TITLE
OH MY GOD

### ISSUE THREAD

**Issue by Ohmygodwhyisntthisworking** [photopea/photopea#4312]
Please make it less laggy, i have a SkyTech Prism 2!!!!! That is a 2,000 dollar gaming pc and PhotoPea STILL lag's, it lagged for so long i had to close my browser and now i have to redo my whole project which was 50% of my grade, please make it less laggy.

**Comment by photopea** [comment]
Is your browser updated? Did you disable the GPU acceleration like in this case? https://github.com/photopea/photopea/issues/4280
