### ISSUE TITLE
Menu bar - deeper items are not hidden when user is out of that category

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#4313]
It isn't a bug. Only a suggestion how does it work in other programs.

For example go to menu "Edit" then "transform" it will show all options in sub-menu for transform editing.
When you go up in menu Edit (for example to copy or paste), that sub-menu od transformations doesn't hide.

It should hide automatically when the user isn't on transform item. With a little delay - 0.5-1s for example.

**Comment by photopea** [comment]
I made it work like that.
