### ISSUE TITLE
Guide Guy - units from ruler

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#4314]
Hi, now I am making a documents for prints and want to do layouts with guides.
It is harder to make for example 1,5 cm from the right, when your document is A4 horizontal and end with 29,7 cm. It is only an example - i know how to subtract it in my head :D

When I have rulers set to cm and choose "View -> add guides" there is possibility to change units (and as default it is set to that from the rulers).
When I want to make a more difficult layout with a Guide Guy plugin - there are only PX. 

In Photoshop in "New Guide Layout" - its sets units from rulers at the start.

**Comment by photopea** [comment]
Done :)
