### ISSUE TITLE
Unable to open saved files

### ISSUE THREAD

**Issue by erinmulry** [photopea/photopea#4317]
I try to open psd files I saved from the previous day from photopea to my google drive and I get an error message.

**Comment by photopea** [comment]
Could you send your file here with us?

**Comment by erinmulry** [comment]
When i dropped the psd file into this box I get an error message that says "We don't support that file type."

**Comment by photopea** [comment]
Send your file to support@photopea.com

**Comment by photopea** [comment]
I have to close it because of lack of details.
