### ISSUE TITLE
how to i access my public url?

### ISSUE THREAD

**Issue by erinmulry** [photopea/photopea#4318]

**Comment by photopea** [comment]
What is your public url?

**Comment by erinmulry** [comment]
there is an option to save my work on a public url but then it gives me no address?

**Comment by erinmulry** [comment]
I am using the program with my highschool class on Chromebooks and they are struggling to save working documents that they can pull up and work on multiple class days.

**Comment by photopea** [comment]
Your browser is probably blocking the popup windows. Can you change the settings?

**Comment by photopea** [comment]
I will close it now, I guess it has been fixed.
