### ISSUE TITLE
Poor Navigator scrolling performance

### ISSUE THREAD

**Issue by Baegus** [photopea/photopea#4322]
When I use the Hand tool to move the document around, it is very smooth (actually much smoother than Photoshop), but when I use the Navigator panel, it is pretty choppy (especially on larger documents). It's still perfectly usable, but the difference is definitely visible.

Perhaps Photopea uses a different redrawing method when using Navigator?

**Comment by photopea** [comment]
I just tried and it seems equally smooth to me. Maybe the difference is, that in Navigator, it moves much faster than with the Hand tool (larger steps). Also, it moves in the oppisite direction than where you move your mouse.

**Comment by Baegus** [comment]
There is no difference with smaller projects, but opening a large (almost 500 MB) PSD with a lot of layers, it is very noticeable. I made a little screencast here: https://youtu.be/xbXRrGcec0c (running on i7 7700K, GeForce 1060)

**Comment by photopea** [comment]
You are absolutely right, I am very sorry, it is fixed now.

**Comment by Baegus** [comment]
Nothing to be sorry about! :D Thank you!
