### ISSUE TITLE
Remove Pen Anti Alias

### ISSUE THREAD

**Issue by scinfu** [photopea/photopea#4323]
How can I disable Anti Alias from Pen Tool?

<img width="89" alt="Schermata 2022-02-14 alle 13 44 24" src="https://user-images.githubusercontent.com/201132/153866608-687f1dd3-ace2-4308-b6ef-d4578b300ea0.png">

Thank you

**Comment by photopea** [comment]
Sorry, but vector shapes are always rendered with anti-aliasing in Photopea :(  Maybe increase your resolution, so that it is not visible that much.

You can right-click a vector shape and choose "Make Selection". There, you can disable Anti-alias, and then, fill the selection with some color.
