### ISSUE TITLE
smooth does not work

### ISSUE THREAD

**Issue by yunica** [photopea/photopea#4326]
hello, excellent job with the tool.
I am browsing the [js reference](https://www.adobe.com/content/dam/acom/en/devnet/photoshop/pdfs/photoshop-cc-javascript-ref-2015.pdf?mv=affiliate&mv2=red) and I want to implement this functionality, but I am not getting the result.
Is there a variation to execute this line of code or more exact documentation?

` app.activeDocument.selection.smooth(10) `

Thank you for your comments.

**Comment by photopea** [comment]
I have implemented it :) sorry for the delay.
