### ISSUE TITLE
Stops on loading

### ISSUE THREAD

**Issue by Loeiks** [photopea/photopea#4327]

**Comment by photopea** [comment]
Hi, what do you mean?

**Comment by Loeiks** [comment]
Hi! Thanks for fast answer :) When I load a PSD file it's loading forever (it was not my original file it was from PSD templates btw)

**Comment by photopea** [comment]
Which PSD template is it? Does it happen for all PSD templates you try to open?

**Comment by Loeiks** [comment]
No just happened only a single PSD I was able to open another one without any problem
![image](https://user-images.githubusercontent.com/90484193/154146513-0519071f-8d9c-4d46-aa70-efbb8c29c159.png)

This template had the problem!

**Comment by photopea** [comment]
This template has too many layers with too many layer styles, it takes eternity to render them. I will delete this template, as it is unusable.

**Comment by photopea** [comment]
I have deleted the template.
