### ISSUE TITLE
damaged gif frames.

### ISSUE THREAD

**Issue by no0000000000** [photopea/photopea#4328]
i was trying to make a gif.  15 frames.  i added each picture, made the frames, went to save. there were NO extra steps, there were NO adjustments.  just adding the frames and saving.  but it said the frames were damaged.

**Comment by photopea** [comment]
Hi, could you save your work as a PSD file and send it to me? I will try to export it as a GIF myself to see what is going on.

**Comment by no0000000000** [comment]
> Hi, could you save your work as a PSD file and send it to me? I will try to export it as a GIF myself to see what is going on.

I can't.

**Comment by photopea** [comment]
I dont know how can I help you then :(

**Comment by no0000000000** [comment]
I don't know what a PSD would do seeing as I already said I made _**literally**_ no changes.  All I did was add frames and save. There is _**literally nothing**_ to see anyway.

**Comment by photopea** [comment]
I need to make the same error happen in Photopea myself. Whenever I try it, a GIF is exported correctly.
