### ISSUE TITLE
Color of the text from a Sketch file isn't getting the colors, all colors become black

### ISSUE THREAD

**Issue by snak10** [photopea/photopea#433]
For example:

I have a orange background with a white text layer. 

When i open it on Photopea, the text layer is filled with black.

<img width="222" alt="screen shot 2017-12-27 at 17 35 35" src="https://user-images.githubusercontent.com/19668787/34391386-61cd9f3a-eb2c-11e7-9424-4e3b41b4ede1.png">

**Comment by photopea** [comment]
Hi, can you please send us your Sketch file to support@photopea.com ?

**Comment by photopea** [comment]
Thanks! There was some unexpected format of the color, so I implemented it, it should work well now.

Thank you very much! I wish tere were more people like you, who report problems.

**Comment by snak10** [comment]
Oh my god you are extremely fast! Thank you so much ! 
You just saved me tons of hours of work !!!!!!!!!!
Sereously, like at least 3 days of work.
