### ISSUE TITLE
Put focus on first input field in new windows/dialog boxes

### ISSUE THREAD

**Issue by setiawanj** [photopea/photopea#4330]
For example, when you open the Hue/Saturation window, no input field is selected. I think it would be a good idea (as in Photoshop) to have the first input field selected:

![image](https://user-images.githubusercontent.com/23211031/154180417-3fba1f4d-8d12-406f-9779-16422d02d31a.png)

I make heavy use of keyboard shortcuts. In Photoshop, if I want to darken a layer for example, I would Ctrl+U to bring up the Hue/Saturation window, press Tab twice to select the input field for Lightness, type in a value, and press Enter. This means my hands don't have to leave the keyboard. Currently in Photopea, if I press Ctrl+U and then press Tab, it shows/hides the panels/toolbar.

This is also true of other windows. For example, if an input field was automatically selected in the New Project window, users could press Ctrl+N, and then tab to the width/height to enter new dimensions, without having to have your hands leave the keyboard to do so.

Just a small quality of life improvement that I think would be appreciated by long term Photoshop users, and help with their adoption of Photopea.

**Comment by photopea** [comment]
I have added this feature to Hue / Saturation and some other adjustments and filters.

Let me know if there is any other Adjustment or a Filter, for which it makes sense to implement it.
