### ISSUE TITLE
Photopea ''This Device'' doesnt load

### ISSUE THREAD

**Issue by MaestroPulga** [photopea/photopea#4335]
Hi, i just wanted to recreate one of my works and edit something. I opened my pc and tried to work on the project. But my Device doesnt open my stuff? What can i do?

**Comment by photopea** [comment]
Hi, this works only in Chrome, Edge and Opera, other browsers do not support it yet :(

Can you simply do File - Open and File - Save?

**Comment by MaestroPulga** [comment]
I always used Chrome, but today when i opened chrome -> Photopea -> „Load from ‚this Device‘, it opened the page but it was all white, nothing showed up from my works. Also not after refreshing the page. Also, i did a new work then and tried to save it, but i can only safe it into dropbox, neither into the device or google drive.. :/

**Comment by photopea** [comment]
Try these steps: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by MaestroPulga** [comment]
Didnt work.. i think they're just gone because i throwed something on my pc into the trash? Like a Browser save or something? idk.. but in 'This Device' there's no more files anymore :/

**Comment by photopea** [comment]
Could you maybe record a short video of what is happening? Start by opening www.Photopea.com in your video.

**Comment by MaestroPulga** [comment]
https://user-images.githubusercontent.com/99841373/154802546-cf7b723c-114f-4ed1-a84a-76eb7bb8af03.mov

It says' the page is 'unsave' but thats only because the certificate, i already checked those parts so it cant be a problem with that :/

**Comment by photopea** [comment]
The chrome will never let an "unsafe website" to use the device storage.

Photopea should never be marked as "unsafe" by any browser. Our certificates are totally correct.

Did you install any browser extensions or other software, which marks Photopea as "unsafe"?

**Comment by MaestroPulga** [comment]
It says 'root is expired' Idk.. can't change anything on there. And no, i really didnt download anything new or something.

**Comment by photopea** [comment]
What version of Chrome are you using? Do you see any extensions at about://extensions?

**Comment by MaestroPulga** [comment]
98.0.4758.102, nope nothing

**Comment by photopea** [comment]
could you send me a screenshot of about://extensions ?

**Comment by MaestroPulga** [comment]
![Uploading Screenshot at Feb. 19 15-32-41.png…]()

**Comment by photopea** [comment]
I can not see anything, could you attach it in the browser?

**Comment by MaestroPulga** [comment]
Sorry my fault
https://imgur.com/0h19Bns

**Comment by photopea** [comment]
Could you temporarily disable the four extensions, which are enabled, restart the browser, and try it again?

**Comment by photopea** [comment]
Did it help?

**Comment by MaestroPulga** [comment]
Oh sorry, forgot to answer. No it didnt :/ I think they are gone.. i will create the stuff i made new and safe it into dropbox, its not a that big problem. Maybe the Browser somehow cleaned itself or anything idk. Thanks for the help anyways ❤️

**Comment by photopea** [comment]
Photopea can save files only to your computer, so your work must be somewhere in your computer.

You should investigate, why is Photopea marked as "unsafe". Maybe you have some viruses in your computer. There are millions of people using Photopea and nobody reported, that Photopea is "unsafe", something is wrong with your device.

**Comment by MaestroPulga** [comment]
I will try to check it again later, it only says the root-certificate is expired and not valid anymore. Can‘t find any other problem on it. Also it always worked but when i reported it was all gone. I dont know why. Never had a Virus or something
