### ISSUE TITLE
Can't upload a picture after payment

### ISSUE THREAD

**Issue by LenaK-A** [photopea/photopea#4339]
Hi! After I made a payment for 3 months Photopea stoped letting me upload pictures from device (macbook air 2017) to edit, both dropping in window and using a menu upload button. Is this a temporary mistake or can you fix it? 
My account in PP starts with to.elenaka
![Screen Shot 2022-02-17 at 5 37 13 PM](https://user-images.githubusercontent.com/99892385/154503965-6d20b906-1d5a-4bfe-9cbf-92c9a3718aa0.png)
r

**Comment by photopea** [comment]
This feature is available to everyone for free. Ordering a Premium does not have anything to do with this feature.

Did it work in the past? Did you try to close Photopea and open it again? Note, that it does not work in Safari and Firefox now, but works in other browsers.

**Comment by photopea** [comment]
I have to close it because of no response :(
