### ISSUE TITLE
Would be nice if there was Font Awesome already at the font picking button

### ISSUE THREAD

**Issue by snak10** [photopea/photopea#434]
Would be nice if there was Font Awesome already at the font picking button

**Comment by photopea** [comment]
Hi, could you please help us out?  We added FontAwesome as two separate font files. It all works well for PSDs. But some Sketch files have text with the font "FontAwesome", and it is not clear, which of these three fonts should be used. Do you have any idea?

**Comment by snak10** [comment]
Sure, i would love to help you guys!

What i did to test:
Opened Photopea and them choose the two fonts: FontAwesome 5 Brands Regular/FontAwesome 5 Free Regular.

Wrote some icon-text that i get from https://fontawesome.com/cheatsheet on each one, them exported as SVG so i could open in Sketch.

When i opened it on sketch, both fonts worked when i replaced Helvetica to my “FontAwesome” font in Sketch panel.

Some screenshots were attached to this e-mail.

Anything else, you can contact me :)




Atenciosamente,

Alexandre Soares
UI/UX Designer
Fone: 61 98325-3060
E-mail: alex.soares11@gmail.com
Portólio: www.behance.net/alexandreintodesign

**Comment by photopea** [comment]
Thanks. I would like to be able to open Sketch files with Photopea and render the text, that has the "FontAwesome" font. How do you create FontAwesome text in Sketch? Is it just selecting one of fonts (just like with any other font), or you have some special plugin for this?

One of my Sketch files contains the character "f0e6", which should be a "message bubble", but I can not see it in any of the font files.

**Comment by photopea** [comment]
Ok seems like I found the "f0e6" icon. I guess it is available only in a Pro version of FontAwesome, that is why I can not render it in Photopea :(  https://fontawesome.com/v4.7.0/icon/comments-o/

I guess I can close it now. If anybody has a Pro version of FontAwesome, they can load their fonts manually into Photopea.
