### ISSUE TITLE
A piece of code on the "Payment complete" page

### ISSUE THREAD

**Issue by Baegus** [photopea/photopea#4340]
There seems to be a little piece of PHP code on the "Payment complete" page:
![chrome_2022-02-18_10-38-41](https://user-images.githubusercontent.com/3513696/154657676-8a583ab8-afb9-426c-85f7-b1c84dfbbb92.png)

**Comment by photopea** [comment]
What did you do to see such screen? Did your payment go well?

**Comment by Baegus** [comment]
I paid for Premium for 1 year normally with my VISA (Česká Spořitelna), then I got redirected here when I approved the payment using the George app. My payment went through and now I have Premium, I just noticed the strange piece of code and thought it might be an issue.

**Comment by photopea** [comment]
I think you are using extensions, which prevented that page from closing itself (and getting you back to the editor).
