### ISSUE TITLE
Uploaded font (.ttf) is not availible

### ISSUE THREAD

**Issue by tonlosfotografie** [photopea/photopea#4341]
Uploaded fonts (.ttf) are not availible.
If you are checking "local memory/storage" the uploaded font is theme - but availible for use in the font list.

**Comment by photopea** [comment]
Do you mean "but not availible for use"?

I just tried and I can load a TTF font in Photopea. Could you send me the font which can not be loaded?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
