### ISSUE TITLE
PDF presentation

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4342]
In File/Automate/PDF presentation I tried to add images contained in "images.zip" zip archive and it is not working (see screenshot)
In tutorial you write "You can select JPG, PNG, GIF, TIFF, BMP, or any other format."
I am not sure what (any other) formats are supported here but I tried to add some SVG, PDF or PSD files and none of them are working for me. Also I noticed after I change language from Czech to English text in this dialog did not change and I needed to refresh browser with photopea to change language in this dialog/window.
![image](https://user-images.githubusercontent.com/6370548/154764142-7d65feef-d1cc-4713-a560-bb7e1e2d02dd.png)

**Comment by photopea** [comment]
Sorry. Now, it is only for non-structured raster formats, marked as "Raster" here: https://github.com/photopea/photopea

I have fixed the tutorial. Also, I fixed the problem with switching the language.
