### ISSUE TITLE
Window - Notes

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4344]
I went to Window - Notes.
I am not sure how this window is supposed to work but whenever I clicked arrows in the bottom they do nothing and I get this error in console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at k9.ci (pp.js:12755:86)
    at hH.aS.c (pp.js:9376:49)
    at hH.io.c (pp.js:9381:43)
    at hH.Kk (pp.js:9453:34)
```

**Comment by photopea** [comment]
Thanks, it is fixed now :)
