### ISSUE TITLE
Image Not Loading

### ISSUE THREAD

**Issue by Sidgupta123** [photopea/photopea#4347]
I wanted to add an image to an uncompleted project but the image did not load
It would just show "loading" at the top of my screen

**Comment by photopea** [comment]
Can you close Photopea and make it happen again? If yes, could you share the image with us? The one which you tried to load.

**Comment by Sidgupta123** [comment]
Actually, all I needed to do was restart my browser
The problem is fixed now

**Comment by photopea** [comment]
Ok, I am glad it works. Maybe you were out of RAM in your computer.
