### ISSUE TITLE
Add Paypal/other payment options

### ISSUE THREAD

**Issue by alangrainger** [photopea/photopea#4348]
Hi team. I would love to sign up for a premium account for myself and my business team, but I (and likely many others) don't feel comfortable adding payment data to a random unknown payment processor like comgate.cz. 

Would it be possible to add Paypal or another known safe provider like Stripe?

I'd like to personally put down a $300 USD bounty for this, as I want to support your app and your development, and I'd really like to buy a plan for my team.

**Comment by photopea** [comment]
Hi! We stopped accepting PayPal, as PayPal takes around 10% of money in fees. I think it is probably similar with Stripe. By accepting cards, we pay only 1.5% in fees (7x less).

Would you be interested in an option to pay 10% more, when you pay through Paypal?

We accept over 600 payments a month with the current method. You would probably be able to find some complaints in this forum, if there was any problem. If you don't trust our payment mechanism, how can you trust us with your files that you edit?

**Comment by alangrainger** [comment]
> If you don't trust our payment mechanism, how can you trust us with your files that you edit?

Because editing images doesn't cause financial loss or require storing my credit card info on an unknown provider. That is a **really** weird argument. It's not that I don't trust you, it's that I don't trust comgate.cz with my payment data.

> Would you be interested in an option to pay 10% more, when you pay through Paypal?

Yes.

I can see that you also denied using crypto payments, which would cost you no fee at all to accept: https://github.com/photopea/photopea/issues/2705 . The argument against was that they change in value, however you could accept USD or EUR stablecoins.

No stress for me to continue using the platform for free, I just wanted to support you but I'm fine to not do so.

**Comment by photopea** [comment]
There was a teacher who wanted to teach Photopea in their school, but he could not load it in the browser. His school told him something like "we block all websites from the eastern Europe, because terrorists live there, who would hack our computers and steal our data".

I think it is very wrong, when you decide to give a monopoly on payments to a few companies, who were rich enough to invest into marketing and make everyone trust them. At the end of the day, everyone ends up paying more than they could for nothing.

**Comment by alangrainger** [comment]
> I think it is very wrong, when you decide to give a monopoly on payments to a few companies

If you did believe that then you would offer crypto. https://github.com/photopea/photopea/issues/2705

**Comment by photopea** [comment]
As the value of any cryptocurrency often decreases by 5 to 20 % within 24 hours, I think our losses would be even bigger than when using PayPal.

**Comment by alangrainger** [comment]
Please refer to my previous comment:

"The argument against was that they change in value, **however you could accept USD or EUR stablecoins.**", which do not change in value.

**Comment by photopea** [comment]
Could you recommend any good provider of such payments?

**Comment by alangrainger** [comment]
Bitpay, Coingate, and Coinbase are your largest providers, and they each charge 1% transaction which, which is 33% less than your current option:

- https://bitpay.com/online-payments
- https://coingate.com/accept
- https://commerce.coinbase.com/

Crypto.com claims to do this for 0% transaction fees and a [0.5% fee to withdraw](https://help.crypto.com/en/articles/4190887-what-should-i-know-about-crypto-com-pay-fees-and-payment) from your account, however I've not used their merchant platform, so I couldn't comment on how good it is:

- https://crypto.com/pay-merchant
