### ISSUE TITLE
Can't use filter "surface blur"

### ISSUE THREAD

**Issue by lissaispunk** [photopea/photopea#4349]
Hi team, whenever I click on filter "surface blur" a black screen appears. I have to refresh or turn photopea back on, but as soon as I try to "surface blur", it shots down again. Already tried it on an incognito window :(

**Comment by photopea** [comment]
I can not reproduce such behaviour :(

Hi, did it ever work in the past? What operating system and a web browser do you use?

**Comment by ProgrammingLife** [comment]
@lissaispunk Maybe you should update your browser? Try to use fresh Chrome browser.

**Comment by photopea** [comment]
I have to close it because of lack of details. Nobody else reported such problem.
