### ISSUE TITLE
Font size in px and pt have same value

### ISSUE THREAD

**Issue by LorincJuraj** [photopea/photopea#435]
Hi. When you check font size using the Character tool it show size in pt, but when you want to get the CSS for the same text, it shows the size in px and has the same value, which is incorrect. As far as i know 1px = 0.75pt

**Comment by photopea** [comment]
Hi, I changed it, "px" labels are used for the font size now. Thanks!

**Comment by LorincJuraj** [comment]
Great. Thanks.
