### ISSUE TITLE
Normal Map filter misses the outside edge pixels

### ISSUE THREAD

**Issue by superrednova42** [photopea/photopea#4350]
Applying the normal map misses the first and last rows/columns of pixels. I only noticed since I need it for a tiling normal map and there was a weird line at the seam.

Examples:
![image](https://user-images.githubusercontent.com/39013503/154895111-866d9921-6776-4e82-b1fb-563337067b49.png)
![image](https://user-images.githubusercontent.com/39013503/154895414-9d4e50ea-63af-4e8b-abec-29e7243abcb3.png)
![image](https://user-images.githubusercontent.com/39013503/154895676-ce46ca74-d050-4f43-bb3d-7e526cb65aca.png)

Comparison of before and after along one edge:
![image](https://user-images.githubusercontent.com/39013503/154895796-8ace2afa-79d9-49c1-8cb8-c5e8bc78a490.png)
![image](https://user-images.githubusercontent.com/39013503/154895730-0fe8199e-30b4-48ba-970e-f864841c1df2.png)

**Comment by photopea** [comment]
fixed, thanks for reporting!
