### ISSUE TITLE
Eye dropper - glitch

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4352]
This is just a minor glitch, that maybe is related to chrome, but i prefer to report it anyway.

When you click to check a color, it displays the hovering window with small fonts:
![image](https://user-images.githubusercontent.com/11801254/155008357-291d3508-8217-40e4-b190-747d8c5e25ba.png)

But if you move the cursor, it enlarges to the proper font size:
![image](https://user-images.githubusercontent.com/11801254/155008385-b62924ba-5685-4368-8e45-76729216374b.png)

**Comment by photopea** [comment]
fixed :)
