### ISSUE TITLE
Photopea does not accept bitcoin

### ISSUE THREAD

**Issue by fongsai-yuk** [photopea/photopea#4354]
Cryptocurrency is a viable means of payment with lower fees. Please do consider it.

**Comment by photopea** [comment]
As the value of any cryptocurrency often decreases by 5 to 20 % within 24 hours, I think our losses would be quite large, compared with usual payments. Are you planning to pay for photopea with a cryptocurrency, or you are just promoting it?

**Comment by fongsai-yuk** [comment]
2 birds one stone. Indeed. What little I've managed to eke out in my line of work has depreciated substantially. But I am willing to contribute - I like photopea and would like you to know that... I guess when the price of my savings has reverted back to its usual. But in all seriousness, yes, I would like to contribute to photopea sometime soon, hopefully with cryptocurrency. 

Volatility necessitates that one converts immediately to a stable coin of your choosing once received.

**Comment by photopea** [comment]
I think there are not that many people interested in crypto payments for Photopea, so it is not worth implementing.

**Comment by fongsai-yuk** [comment]
Okay, thank you.

**Comment by jacobburrell** [comment]
I was hoping to pay for Photopea today with bitcoin via the lightning network.

You can easily add [BtcPayServer](https://btcpayserver.org/) as an option for free and have all funds instantly converted to national currency.

There are some paid options that offer even easier integration even with your bank account such as [OpenNode](https://opennode.com/).

I see you have Paypal as a checkout option, they also have bitcoin integration in [checkout](https://www.paypal.com/us/business/accept-payments/checkout) but as mentioned, their fees are quite high and it doesn't seem they have the lightning network (which is instant with low fees, designed for small volume transactions) as an option.

**Comment by xrviv** [comment]
FYI. I do not know jacob and i did not convince him to make this post. :)

**Comment by photopea** [comment]
There would probably be 1-  2 people interested in paying in Bitcoin per year, so it is not worth it to integrate it. Also, I think even these people have a payment card issued by their bank, which they can use to pay (without making any "payment accounts" - whatever it is).
