### ISSUE TITLE
Photopea Starts to Glitch During Editing

### ISSUE THREAD

**Issue by Jykie** [photopea/photopea#4355]
Here are the following issues that occurs every time I would edit:

* If I'm tapping on the canvas, the cursor would start to move the canvas around regardless of if I'm using the brush tool or free transform. 
* I'm unable to click on another layer. It stays stuck on whatever layer I'm currently on.

For reference, I use a Samsung Galaxy Tab S7 with 8 GB Ram and 256 SSD. Even when the file itself doesn't have that many layers, this issue would occur. And I can't recount the exact steps in my photo editing since what I do varies from project to project.

**Comment by photopea** [comment]
Hi, could you record a video of how you make Photopea move the canvas around? Starting with opening Photopea at www.Photopea.com ?

**Comment by Jykie** [comment]
Hi, I'm trying to upload the video recording but it doesn't seem to be working. How do I send the recording on here?

**Comment by photopea** [comment]
Could you upload it e.g. to Youtube and share a link with us?

**Comment by ZenithPixel** [comment]
https://user-images.githubusercontent.com/100442812/155784561-8194a19e-7314-428a-b5e9-4340304db73e.mp4

@photopea

**Comment by photopea** [comment]
Can you make it happen on purpose? Find a way to make it happen on purpose.

I have an Android phone. Could you describe some steps, what should I do after opening www.Photopea.com , to produce such behaviour? I can fix it only if I can make it happen myself to analyze it.

**Comment by ZenithPixel** [comment]
> Can you make it happen on purpose? Find a way to make it happen on purpose.
> 
> I have an Android phone. Could you describe some steps, what should I do after opening [www.Photopea.com](http://www.Photopea.com) , to produce such behaviour? I can fix it only if I can make it happen myself to analyze it.

It happens somewhat randomly, sometimes if I tap for magic wand with my finger, or sometimes if i've been editing for a long time without saving or if i'm using my stylus. It might have something to do with the pressure applied to the canvas but i'm not sure. It's pretty random and I've tried to recreate it, it sorta just happens out of nowhere. I first encountered this problem like 5 or 6 months ago.

**Comment by photopea** [comment]
@nothingshiru could you reproduce it maybe?

**Comment by Jykie** [comment]
Hi, have you seen the video recording I sent about the issues? Again, I use a Samsung Galaxy Tab S7 with 8 GB and 256 SSD. I never had these issues on my old laptop, but since switching to this tablet, I keep experiencing them.

**Comment by photopea** [comment]
This issue happens only when you touch the display at more than one place. So it can be only on touchscreens (so not on laptops).

I need someone to tell me, how exactly can I make it happen on my phone :(

**Comment by Jykie** [comment]
It's completely random, I don't how you can reproduce it on your phone. Like I said, I would pull up a file and start editing and then after a while the issues will start occurring. 
What I do for each project is different because I make different designs. All I know is that these issues have started to occur ever since I switched to a tablet.

**Comment by photopea** [comment]
It should be fixed now.
