### ISSUE TITLE
save to OE is not working

### ISSUE THREAD

**Issue by lanadeldel** [photopea/photopea#4357]
hi ivan，Do I have to specify the server address to use this api, I have read the documentation but I don't know how to send it,?

**Comment by photopea** [comment]
Please, read www.Photopea.com/api . The "saveToOE" script is for sending web messages from the iframe to the parent frame, it is not related to any server.

**Comment by lanadeldel** [comment]
> Please, read [www.Photopea.com/api](http://www.Photopea.com/api) . The "saveToOE" script is for sending web messages from the iframe to the parent frame, it is not related to any server.

thank you so much,now i get it! :)
