### ISSUE TITLE
Is the site still available for Microsoft Edge?

### ISSUE THREAD

**Issue by SurfaceTherapy** [photopea/photopea#4358]
I can't oben the Photopea website, because it says that my browser is too old. I'm on Win 10 and the latest version for the Edge.

**Comment by photopea** [comment]
Hi, you probably configured your browser to disable WebAssembly. WebAssembly and Javascript support is required for running Photopea in a web browser.

Maybe this can help you: https://github.com/photopea/photopea/issues/3728

**Comment by SurfaceTherapy** [comment]
Java Script is on and it is recommended by the browser to be on.

**Comment by photopea** [comment]
You have disabled the webassembly. It is required for Photopea to work.

**Comment by photopea** [comment]
https://twitter.com/photopeacom/status/1485184824029716480
