### ISSUE TITLE
exports feature broken

### ISSUE THREAD

**Issue by smalldotteam** [photopea/photopea#4359]
Trying to export a PDF of a PSD made in Photopea with artboards. But I get this broken Save for Web interface that doesn't work.
No matter what format I choose to export it defaults to this PDF option. When i save and download the file it exports it is a 0 B filesize. This is happening repeatedly.

![image](https://user-images.githubusercontent.com/76067706/155430006-c43d05c8-8dea-4b61-ad34-6346af996cc7.png)

Then if i can get the PDF interface to show up, it blends all the artboards into one page like this.
![image](https://user-images.githubusercontent.com/76067706/155431128-587796fa-dc51-4371-a50d-6acfb60402ff.png)

**Comment by photopea** [comment]
Could you share your PSD file with us, so that I can reproduce the bug myself?

**Comment by photopea** [comment]
Thanks! It is fixed now :)
