### ISSUE TITLE
Shape broken after Flip Horizontally

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4360]
After I do Flip Horizontally (or some other transforms) on my shape layer with multiple paths my shape is broken. It seems like one of the paths is deleted and other path is duplicated (triangle disappears and top rectangle appears twice) for no reason.
See screenshots:
Before Image/Flip Horizontally:
![image](https://user-images.githubusercontent.com/6370548/155508240-25356304-b5ba-40c3-9ed5-bb9879645262.png)
After Image/Flip Horizontally:
![image](https://user-images.githubusercontent.com/6370548/155508279-17f0c3bd-9e81-4f5d-8dc5-aa41148ba0f8.png)
PSD file:
[image1-svg.zip](https://github.com/photopea/photopea/files/8131770/image1-svg.zip)

**Comment by photopea** [comment]
This happens after Free Transform, or any modification of the path.

The bug is in a PSD itself. The "rounded rectangle live shape" is set to the third shape, but only the 4. and 5. paths are rounded rectangles.

Could you describe, how did you produce this PSD?

**Comment by hxim** [comment]
Yes,
1.) I opened this svg file
[image1.zip](https://github.com/photopea/photopea/files/8140749/image1.zip)
2.) After that I selected "Path Select" tool, clicked on top rectangle path (Path 3) and clicked up arrow button in toolbar two times. (So it moved to Path 5 position I think)
See screenshot (I clicked here twice):
![obrazek](https://user-images.githubusercontent.com/6370548/155707853-b51b52d0-5347-48b7-86ff-e60988be8af0.png)
3.) And I saved it as PSD

**Comment by photopea** [comment]
I am very sorry for this bug, it is fixed now. Create your PSD again and it should be ok now.
