### ISSUE TITLE
No ungroup function for .EPS files

### ISSUE THREAD

**Issue by indigoextra** [photopea/photopea#4361]
Hello,
A lot of the .eps files that I receive have different elements grouped together.
Basically this means that they act as temporarily merged layers. In order to edit one part of a group (e.g. move a fork that's positioned over a plate in an image), then I need to click 'Ungroup', which separates the group so each one is an independent layer.
I can't see this option anywhere in Photopea. It would be great if you can add it.
Thank you,
Martin

**Comment by indigoextra** [comment]
Just found out how to edit it, by selecting individual items in the right-hand groups, rather than from the image itself.

**Comment by photopea** [comment]
The terminology in Photopea is a bit different than in Adobe Illustrator. Look here: https://www.photopea.com/learn/vector-graphics
