### ISSUE TITLE
B.keyOriginShapeBBox is undefined

### ISSUE THREAD

**Issue by lanadeldel** [photopea/photopea#4362]
I encountered this problem when parsing the psd file, I think this should be a bug.:)

**Comment by lanadeldel** [comment]
<img width="532" alt="DE2D01B2-7F66-4116-8A14-39CA5DDCBDBF" src="https://user-images.githubusercontent.com/48135307/155838441-2c49771a-0cd0-4ff6-a440-559849ca17cd.png">

**Comment by lanadeldel** [comment]
<img width="490" alt="6ACFD9D7-0CF1-4271-A474-E77A77D543BB" src="https://user-images.githubusercontent.com/48135307/155838484-1d166b10-3690-452e-838c-403ced88e9d8.png">

**Comment by photopea** [comment]
Did it happen when opening a PSD file in Photopea? Could you share your PSD file with us, please?

**Comment by lanadeldel** [comment]
> Did it happen when opening a PSD file in Photopea? Could you share your PSD file with us, please?

yesss,Here is the link to the file："http://s3.cn-north-1.amazonaws.com.cn/photo-center-prov/images/91rr3AHARTasVhdqqVyNm4TGH9ub5wHb8VhZiE45/40bd6bffb940d8eefd8c5eee3eebb1ee.psd"

**Comment by photopea** [comment]
I have opened your file in Photopea, but I can not see any problems in the console. What should I do to see the problem?

**Comment by lanadeldel** [comment]
im sorry,I use another library to write arraybuffer, this error should be caused by it
