### ISSUE TITLE
saveToOE possibly broken?

### ISSUE THREAD

**Issue by yikuansun** [photopea/photopea#4363]
Hi,

I am trying to use `saveToOE` in my plugin. For my purposes I need the data URI, so I convert as such:
```
        var binary = "";
        var bytes = new Uint8Array(buffer);
        var len = bytes.byteLength;
        for (var i = 0; i < len; i++) {
            binary += String.fromCharCode( bytes[ i ] );
        }
        var imageuri = "data:image/png," + window.btoa(binary);
```
This creates `imageuri`, but it is corrupt. I have also tried, just to test, converting to Blob
```
var myblob = new Blob([new Uint8Array(buffer)], {type:"image/png"})
```
which also returns corrupt data. I therefore suspect that `saveToOE` is broken.

Thanks!

**Comment by yikuansun** [comment]
Sorry, I got Blob working, so it was probably an error with my own code that caused the data URL to be broken. I'll just convert it to Blob and then to data URL.

**Comment by photopea** [comment]
Your code with strings / URI should work, too. Can you check if it works?

I did not do any changes in this part of Photopea for months.

**Comment by yikuansun** [comment]
After looking at some old code, I realized that, quite hilariously, the issue was that I left out `;base64` from the URL.
Thanks for the support, as always!
