### ISSUE TITLE
Flatpak version can't save PSD files

### ISSUE THREAD

**Issue by ProgrammingLife** [photopea/photopea#4364]
Trying to use flatpak version of Photopea (2.2). If I click "Save as PSD" - it does nothing. Even if I choose: Save More -> Save as PSD. Absolutely the same behaviour. With the web version things work great.
I use Linux Mint 19.1.
How to fix it?

**Comment by photopea** [comment]
Hi, I dont know what is "flatpak" :( We make only the web version. You should ask the author of your software about this problem.

**Comment by photopea** [comment]
Why exactly do you use the "flatpak" version instead of Photopea.com ? Did you try to press More - Install Photopea, to get a "native" experience?
