### ISSUE TITLE
Color Theater Plugin

### ISSUE THREAD

**Issue by yikuansun** [photopea/photopea#4365]
Hi,

I've developed a new plugin called Color Theater. Here are some before/afters, which you can view more of at https://lunalgraphics.github.io/about-colortheater
![image](https://user-images.githubusercontent.com/38194363/155866283-da2aa4f4-d1ef-4231-a4a7-2adbda40358d.png)
Because of the preset-based workflow, I think the plugin will suit all levels of users.
![image](https://user-images.githubusercontent.com/38194363/155866466-7201daa1-00f4-47eb-b84a-f0fdd87432d7.png)
Here is the JSON data:
```
{
    "name"  : "Color Theater",
    "url"   : "https://lunalgraphics.github.io/colortheater/?portal=photopea",
    "icon"  : "https://lunalgraphics.github.io/colortheater/icon.png"
}
```
Could you please add it to Photopea?

Thanks!

**Comment by photopea** [comment]
I have made a Plugin gallery in Window - Plugins. The interface is very similar to Free PSD Templates. Please, add your plugins there.
