### ISSUE TITLE
RGB -> CMYK

### ISSUE THREAD

**Issue by pungor23** [photopea/photopea#4366]
I change the color mode to CMYK but the program will export RGB picture anyway. Could you help me with this?

**Comment by photopea** [comment]
Hi, what do you mean by "export RGB picture"? In what format are you exporting?

**Comment by avagp** [comment]
That, when you export to pdf or png for example, the color go back to normal.

I know the color mode CMYK is only a visual filter when editing, but for people who work printing, we need to export on the color pallet of CMYK.

I was about to ask you if we can have CMYK in the color picker and in the eye dropper. Because the print always ask me which color CMYK i use, because I send them a RGB image.

**Comment by photopea** [comment]
So you want to have a "filtered" colors in an exported PNG? Because there is no such thing as a "CMYK PNG" and "RGB PNG".

How do you tell if a PDF is a CMYK PDF or RGB PDF?

**Comment by avagp** [comment]
Yes. For example, this is my work on photopea:
![image](https://user-images.githubusercontent.com/11801254/156435371-f7dfdef5-c3fd-4377-8208-0f2d611b8051.png)

and this is the composite file i get from my printer before print:
![image](https://user-images.githubusercontent.com/11801254/156435307-9db9a18d-37ee-4722-a871-841cacad1ae7.png)


So, every time i have to indicate which is the correct CMYK green color which i would like to use for printing.

**Comment by avagp** [comment]
because is cannot give a filtered PDF/PNG they do it on photoshop and send it to me again.

What should be correct, is that I send the filtered file so they just print.

**Comment by avagp** [comment]
Also, the CMYK gamut in the color picker iss super useful, but still, i would like to be able to control the CMYK color picker as the hex and rgb one.

**Comment by photopea** [comment]
So what about this: If you have a CMYK mode enabled in your document in Photopea, all exported files (JPG, PNG, PDF ...) will have "CMYK filtered" colors? 

About the CMYK in the color picker, there are many strange things: In Photoshop, if you enter CMYK (0,0,0,100), you get RGB (35,31,32). But if you enter RGB (35,31,32), you get CMYK (70,67,64,74). The colors (70,67,64,74) and (0,0,0,100) are identical in CMYK.

**Comment by pungor23** [comment]
@photopea Any photo I export in any file format comes out RGB. I have the same issue as @avagp, I want to send this file for printing and I cannot since after I turn mode to CMYK, the file will be saved in RGB. I do not know if As far as I know png can only be RGB, but jpg can be CMYK. If you have a Photoshop you can check that jpg picture in cmyk mode from Photopea exported will result in an RGB file.

**Comment by photopea** [comment]
@pungor23 I think you are wrong, there is no "CMYK JPG". Can you share a JPG file, and name some software (other than Photoshop), which tells, that this JPG is CMYK?

**Comment by pungor23** [comment]
@photopea I use CYAN for this. It can tell. https://cyan.fxarena.net/

**Comment by avagp** [comment]
> So what about this: If you have a CMYK mode enabled in your document in Photopea, all exported files (JPG, PNG, PDF ...) will have "CMYK filtered" colors?
> 
> About the CMYK in the color picker, there are many strange things: In Photoshop, if you enter CMYK (0,0,0,100), you get RGB (35,31,32). But if you enter RGB (35,31,32), you get CMYK (70,67,64,74). The colors (70,67,64,74) and (0,0,0,100) are identical in CMYK.

I don't see that in the converer i am using :/
![image](https://user-images.githubusercontent.com/11801254/156884267-9608b770-b7bb-499f-b8ff-0ba083ff1b5a.png)

**Comment by avagp** [comment]
>So what about this: If you have a CMYK mode enabled in your document in Photopea, all exported files (JPG, PNG, PDF ...) will have "CMYK filtered" colors?

i believe that a filtered jpg/png/pdf will be sufficient for us.

What do you say @pungor23 ?

And also have CMYK in the color picker and eye dropper tools  :)

**Comment by pungor23** [comment]
@avagp I absolutely agree!:)

**Comment by avagp** [comment]
i use this tool to convert a file to a "filtered" png:
https://www.rgb2cmyk.org/

**Comment by pungor23** [comment]
@avagp I used it too and sometimes white backgrounded pictures came out with light grey background... so it is not 100% working :/

**Comment by photopea** [comment]
I was talking about Photoshop with default settings, not some random website. Of course, there are thousands of RGB and CMYK spaces, so there are millions of ways to convert between RGB and CMYK.

**Comment by photopea** [comment]
BTW. this is a complete rubbish: https://colordesigner.io/convert/cmyktorgb 

It uses a formula 
Cyan = 100%  - Red
Magenta = 100% - Green
Yellow = 100% - Blue

It lets you convert any RGB value to CMYK, it does not correspond to any CMYK space used in practice.

**Comment by avagp** [comment]
>BTW. this is a complete rubbish:

Thanks for warning me! XD

But regarding the CMYK RGB convertion... How does Photoshop do it? Can we just copy that?

**Comment by avagp** [comment]
I am using adobe color
This
![Screenshot_20220305-154715](https://user-images.githubusercontent.com/11801254/156888593-760df20c-d57e-426a-8756-4e43d1745ce6.png)

Converts to this:
![Screenshot_20220305-154719](https://user-images.githubusercontent.com/11801254/156888603-846beaf1-1df8-4a4e-b263-efc377585934.png)

**Comment by pungor23** [comment]
I cannot show you since I have no Photoshop, but  PS has a same mode changer as in Photopea. You just change it to CMYK and you can save it in CMYK. If that was your question.

**Comment by photopea** [comment]
BTW this https://color.adobe.com/ is the same "rubbish method" as this: https://colordesigner.io/convert/cmyktorgb

If you want, I can implement this method very easily. But it is not the CMYK-RGB conversion of Adobe Photoshop.

**Comment by pungor23** [comment]
What will be the difference then?

**Comment by photopea** [comment]
I have fixed the problem. When you enable a CMYK mode in Photopea, all raster expored formats, and the PDF format, will have identical colors as the ones you see in Photopea.

**Comment by avagp** [comment]
Thank you @photopea! 
This will make work easier 💚

**Comment by avagp** [comment]
> BTW this https://color.adobe.com/ is the same "rubbish method" as this: https://colordesigner.io/convert/cmyktorgb
> 
> If you want, I can implement this method very easily. But it is not the CMYK-RGB conversion of Adobe Photoshop.

I am surprised that adobe color have a different method than Photoshop. :O

**Comment by pungor23** [comment]
@photopea you are awesome, thank you!

**Comment by pungor23** [comment]
@photopea I have changed the mode to CMYK and exported .jpg and the saved file is still CMYK. :(

**Comment by photopea** [comment]
I dont think there exist any "CMYK JPG" file anywhere in the world. If you disagree, could you share an example of such CMYK JPG with us?

**Comment by photopea** [comment]
I see, it is probably not a very standard way of saving JPG, see https://www.quora.com/Can-a-JPEG-be-CMYK  . The file is 10x larger than it could be.

Is it really needed? Do you get a bad result when you print a JPG out of Photopea as it is?

**Comment by pungor23** [comment]
@photopea the printing house my company is in connection with requires the pictures this way. Do not ask me why🤷🏼‍♂️ Maybe it is necessary for modern printers, idk

**Comment by photopea** [comment]
It would be too much work to make Photopea create such JPG files. Nobody else asks for it.

Your printing house should be able to print JPGs from Photopea precisely. Or ask your employer (who decided to use that specific printing house) to provide you a software to do your work.

**Comment by pungor23** [comment]
@photopea you're going to laugh. It just happened.😄 I have had a meeting with my supervisors where I explained the issue so I already have PS on my computer😃 Anyways thanks for your extreme helpfulness! I will definetely will continue using Photopea in my everyday life!
