### ISSUE TITLE
Bad text alignment when vectorizing

### ISSUE THREAD

**Issue by Baegus** [photopea/photopea#4368]
I have some text layers in a PSD (made in latest Photoshop), but when I vectorize one of them (`text1`) in Photopea, the text jumps a bit. The same thing happens if I edit it using the Type tool.

PSD here:
[alignment.zip](https://github.com/photopea/photopea/files/8159914/alignment.zip)

**Comment by photopea** [comment]
It should be fixed now. Thank you for reporting it!
