### ISSUE TITLE
Loading jpeg creates glitched image.

### ISSUE THREAD

**Issue by sugoidesune** [photopea/photopea#4369]
loading the jpeg in any way creates a glitched image in 2 layers.
the top layer looks normal but the quality appears to be that of a thumbnail
![image](https://user-images.githubusercontent.com/20317691/156213003-b1181533-bca9-47ec-a4d6-d2402f82b1e0.png)

original jpeg from dji mini drone:
![DJI_0502](https://user-images.githubusercontent.com/20317691/156213236-fbc8ba5b-b1ee-4412-88a1-bda9dedc27a3.JPG)

**Comment by photopea** [comment]
This looks like a bug in a library that we use, I reported it to the authors: https://github.com/nothings/stb/issues/1298

**Comment by photopea** [comment]
It is fixed now :) Thanks for reporting it!

BTW. your file really contains two JPG images (a hi-resolution and a low-resolution). Photopea stretches the low-resolution one, as it often contains a depth map, so that you have your depth map at the same resolution.
