### ISSUE TITLE
Integrate with menuing system

### ISSUE THREAD

**Issue by titlestad** [photopea/photopea#437]
Our platform, FriendUP, has a complete menuing system that is themable and retargetable (turns into a mobile menu on phones, can be per window or global like on Mac / Ubuntu). We'd like to use this menu system instead of the one inside of Photopea, and we see that there is some simple support for this now.
How would we be able to use postMessage() to send all the commands that is in the Photopea menu system, and how can we go about getting information calling back when the Photopea menu state has changed?

**Comment by photopea** [comment]
what menu are you talking about? Do you want just to change the look, or also the functionality?

**Comment by titlestad** [comment]
Look at the screenshot:

https://pasteboard.co/H1wnqYv.jpg

As you can see, we have our own menuing system. Would be cool to be able to use this, as when you run Photopea in a window, we could attach the menu to the top of the screen.

Another example:

https://pasteboard.co/H1wo8FU.png

**Comment by photopea** [comment]
Oh, you mean the top menu (File, Edit ...). I think that such integration would complicate the API, everything would be so much more complex. What about displaying Photopea without your menu, just with Photopea menu (i.e. make the PP area taller and hide your menu)?

**Comment by titlestad** [comment]
Well, I could do that. But how could I then add our functionality for making our file dialogs appear? I know you have support for hiding/defining the menu, but when you receive messages from your menu, wouldn't it be possible to receive these messages into the same loop, just triggered by an onmessage()?

**Comment by photopea** [comment]
Again, what exactly do you want to be done? What file dialogs do you need? Does your app is also inside a browser, or it is "a browser" itself? If it is a browser, just connect your file dialog to the File input form element.

**Comment by titlestad** [comment]
FriendUP runs in a browser, yes. So it's a "web app" itself. It runs Photopea in a window managed iframe. We have our own file dialogs, disks, etc. So it's a full OS (connected through WebRTC/WebSockets and HTTP to our cloud kernel) in a browser.

**Comment by titlestad** [comment]
Example of inbrowser:
https://pasteboard.co/H1wvjs0.jpg

**Comment by photopea** [comment]
I think you are right. We need a way to pass files to and from Photopea on a clients side. Let me think what would be the best way to do it. So should I close this and discuss it in the previous thread?

**Comment by titlestad** [comment]
Yeah sure :-)
