### ISSUE TITLE
With 4K monitor, bottom 5-6 layers in Layers panel do not get shown, cannot be clicked on

### ISSUE THREAD

**Issue by seandanger** [photopea/photopea#4370]
Hello, thank you for Photopea!

As the title suggests, I'm having a problem where the bottom layers shown in the Layers panel are blank and unclickable.  It happens based on the scroll position of the document, and I don't seem to have this problem on my laptop, just on my 4K monitor.  

Here's a video demonstrating (and narrating) the issue: https://www.youtube.com/watch?v=1akAOiFnpN8

For now my workaround is to add about 9 fake layers to every project so they push my real layers up the list, but it would be very nice to not have to do this each time!  Thank you.

**Comment by photopea** [comment]
It is fixed now, thanks for reporting :)
