### ISSUE TITLE
justified text

### ISSUE THREAD

**Issue by simsebas** [photopea/photopea#4371]
hey there!
I have been using photopea as a premium user for quite a while and love it. The one thing I simply don't know how to work is 

justified text!

As I understand it, each line with words should start on the very left side and end on the very right side. The spacing in between words will vary to accommodate making it look completely square. left centered works, right centered works. middle centered works, but I simply cant justify it. Please help!!!  thank you!

do I need to create a textbox?   how?

**Comment by photopea** [comment]
I have to close it because of lack of details.
