### ISSUE TITLE
"Fonts not loaded yet" error.

### ISSUE THREAD

**Issue by rainy421** [photopea/photopea#4372]
When trying to edit text boxes containing custom fonts, I'll sometimes be able to edit a little bit of the text but then it locks up with the message "Fonts not loaded yet" (despite the fonts loading and displaying fine). I then can't edit the layer, the text cursor disappears and the layers window on the right becomes somewhat unresponsive. I've tried dragging the fonts into the window again and it will load them but give me a bug report error. This issue's only appeared today or so, and I'm not sure what the cause is.

**Comment by rainy421** [comment]
> 

Hi there, yep. I've tried Incognito and it still happened, also tried the desktop client of Photopea, and I've tried several different templates that all did it.

**Comment by rainy421** [comment]
> 

I'm not really sure, having never debugged anything myself. I'm part of a community that makes card game content and several of us are experiencing this problem. We use a text box that has two different fonts in it simultaneously (one in a top section and one lower down), perhaps that's the problem? It doesn't seem to happen in other text boxes that use only one font.

**Comment by photopea** [comment]
Can you send me your PSD file to support@photopea.com , so that I try it myself?

**Comment by rainy421** [comment]
Okay, sent

**Comment by saifalfalah** [comment]
Same error happening with me. And I see this in console:

`caught TypeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Value is not of type 'long'.`

**Comment by photopea** [comment]
@saifalfalah what should I do after opening www.Photopea.com to see the error which you describe?

**Comment by jajouka79** [comment]
this makes photopea unusable unfortunately, searching for an alternative

**Comment by photopea** [comment]
@jajouka79 if you tell me what the problem is, I can try to fix it.

**Comment by xXwatermelon** [comment]
This error is still happening lol

**Comment by photopea** [comment]
What should I do to see it happen myself?
