### ISSUE TITLE
PDF Presentation form doesn't work

### ISSUE THREAD

**Issue by belykh** [photopea/photopea#4374]
Steps to reproduce:
Add some files and click "Export as PDF"

Result:
Nothing happens

Error in the console:
```
Uncaught TypeError: Cannot set properties of undefined (setting 'U1')
    at Function.bZ.Xq (pp.js:3750:95)
    at Object.ha.bs.yF (pp.js:526:96)
    at g6.OZ (pp.js:11094:65)
    at bz.e3.c (pp.js:9383:49)
    at bz.b8.c (pp.js:9388:43)
    at bz.lb (pp.js:9458:34)
```

Formatted piece of code:
```
    bZ.Xq = function(u, W) {
        W.U1 = !1;
        W.fO = 8;
        var S = new Uint8Array(u), b = 0, N = 0, J, au = !1, gz = !0, jZ = !1, eo = 0, ap = 0;
        N = bZ.vm(W, S, b);
        bZ.MD(0, N - b, "PSD Header");
        b = N;
        N = bZ.at3(W, S, b);
        bZ.MD(0, N - b, "Color Mode Data");
```
Windows 10, Chrome `Version 98.0.4758.102 (Official Build) (64-bit)`

**Comment by photopea** [comment]
Hi, I just tried it and it works fine for me.

What kind of files are you loading? It supports only simple raster formats like JPG, PNG, GIF, TIFF, etc.

**Comment by belykh** [comment]
oh, sorry
you are right

I wanted to convert several PSD files into PSD
Checked for JPG - it works fine.

Probably it would be better to add a files filter to the dialog or check file types after adding?
Thank you!

**Comment by photopea** [comment]
I have fixed it. You can use PSD files in the PDF Presentation now.
