### ISSUE TITLE
Suggestion - Convert path stroke to vector shape

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4375]
Hi @photopea I already know what i am going to ask goes beyond classic Photoshop, BUT as far as i can see, this is a hi requested feature for Photoshop, that maybe Photopea can have before.

I know that vectors should be worked on illustrator or another vector program, but hear me out.

Normally i have this situation:
I create a shape within my work on photopea, i send it to print, and the printer need to adjust it, so he modifies the dimensions of the image and canvas, and without noticing he modifies the design, how? the strokes of the shape do not adjust to the new size (this also happens with the radii of the regular shapes)

![image](https://user-images.githubusercontent.com/11801254/156664159-32d291ae-977a-4a5d-be94-a9ecd3ca8d96.png)
![image](https://user-images.githubusercontent.com/11801254/156664250-5f6bea30-2a97-4749-a803-59277c005881.png)

---
![image](https://user-images.githubusercontent.com/11801254/156664332-150e0417-dc62-46a4-83cf-15abde3c7f29.png)
![image](https://user-images.githubusercontent.com/11801254/156664339-b16de0fa-b7c5-4f2b-8599-eb0b328b6f27.png)

The work around i have been doing is converting to smart object. But in the end, every shape i do i have to convert it in smart object, so it is not modified in the process of printing.

And i have came with an idea of converting the stroke of a path to a vector shape, that way is not lost the real shape when modified.

And i came across that many people have this issue and would like Photoshop to have it as a solution. The only real solution now is to use illustrator in between.

So, i was wondering, can this be a real thing in Photopea???

Can Photopea respond before Photoshop to a community problem?
https://community.adobe.com/t5/photoshop-ecosystem-discussions/cs6-how-to-convert-a-path-stroke-in-a-vector-shape/td-p/4531476

**Comment by MichalSZZ** [comment]
I am using this feature in Illustrator very oft.
![obraz](https://user-images.githubusercontent.com/38118273/156739915-db416bf7-225d-4935-9102-19ae74f125a2.png)
It will be great to have some "Illustrator like" functionalities that aren't related with the PSD specification (they are not editable after making an operation on path/shape).
Another one frequently used by me is "offset path". It makes path bigger or smaller (to outside/inside - like in Photoshop Select->Modify->Expand/Contract).

**Comment by avagp** [comment]
Thanks @MichalSZZ the second feature is also very used by the community.

Both will very useful.

I don't have illustrator myself so. That is why I related so much in smart objects. 

Thanks for sharing :D

**Comment by photopea** [comment]
So what you need is, if you have a Live Shape, a rounded rectangle with the corner radius of 10 pixels, and you increase the size of the image 4x, you want the radius to increase 4x, too, right?  And you want to do it for the text stroke, too, right?

We already do it for Layer styles (e.g. the size of a Stroke, the distance of a drop shadow, etc.). We do it for the stroke of vector shapes, too. Is there anything else?

**Comment by photopea** [comment]
Now, if you increase the mage size with Image - Image Size, the text stroke also increases, and the live shape corner radius also increases. But if you enlarge the rectangle with the Free Transform, the corner radius stays the same.

I don't know what would be the algorithm for Offset Path, I am afraid it would be too complicated :(

**Comment by avagp** [comment]
Thanks Ivan,

The corner radii keeping was a thing.
[](https://user-images.githubusercontent.com/11801254/156664332-150e0417-dc62-46a4-83cf-15abde3c7f29.png)[](https://user-images.githubusercontent.com/11801254/156664339-b16de0fa-b7c5-4f2b-8599-eb0b328b6f27.png)image
image

But with @MichalSZZ we were talking also about what illustrator has called: Outline stroke.

Where i can make the stroke of a shape an individual shape. 
So i don't have the following problem:
[](https://user-images.githubusercontent.com/11801254/156664159-32d291ae-977a-4a5d-be94-a9ecd3ca8d96.png)[](https://user-images.githubusercontent.com/11801254/156664250-5f6bea30-2a97-4749-a803-59277c005881.png)image
image

(look at the hands of the banana)

**Comment by photopea** [comment]
If you have a stroke thickness of 4 pixels, and you do Image - Image Size, and increase the size to 200%, the stroke should become 8 pixels thick.

But if you do a Free Transform, the stroke will stay 4 pixels thick.

So what exactly do you need? How did you get an unscaled stroke in your screenshot?

**Comment by avagp** [comment]
>So what exactly do you need? How did you get an unscaled stroke in your screenshot?
By free transforming it :/

Sadly, on big printers, there are bad "designers" who really destroys your work when adjusting them before printing (this is always necessary).

That is why i prefer to convert everything to shape, so EVEN if they transform everything by Free Transformation tool, the proportions will remain the same within the illustration.

@MichalSZZ i don't know if you do this because of my same reason, why you use this feature in Illustrator?

**Comment by photopea** [comment]
What if I add a checkbox "edit stroke thickness"  to the Free Transform?

I don't have a method for converting a stroke into a shape. But once you do that, there is no way to work with it as a stroke anymore (e.g. change the thickness, the dash pattern, etc).

**Comment by avagp** [comment]
>What if I add a checkbox "edit stroke thickness" to the Free Transform?

That won't do the trick. Because i have to prevent the editing outside the platform of Photopea.

>I don't have a method for converting a stroke into a shape. But once you do that, there is no way to work with it as a stroke anymore (e.g. change the thickness, the dash pattern, etc).

I do it by: duplicating the shape > disabling the fill > turn the dpi to 300 > rasterize the image > vectorize bitmap (normally cartoon and merge olors)

**Comment by photopea** [comment]
If your clients modify the PDF, and it ruins the stroke, it is a bug in their software and needs to be fixed, right?

Have you tried to export PDFs with "rasterize all"? Vector graphics is not necessary, when you have a large resolution.

I am afraid that rasterizing+vectorizing would produce very "imperfect" results, circles would not be round, etc.

**Comment by avagp** [comment]
> yes. It's a layer 8 problem though :P

They use illustrator as far as I know.

I prefer don't rasterize, because of this same reason. I need them to be able to modify a bit.

As you said rasterize + vectorize give some imperfections, but I can live with them now.

The only way I have found is doing this rasterize+vectorize method. That's why the only solution i am thinking in is the convert stroke into a path.

If you can do that I believe we can close this issue.  :/

**Comment by MichalSZZ** [comment]
@avagp 

One of the first thing in my head:

I bought an icon set on istockPhoto (line icons). They are made perfect on paths (editable paths with strokes only). But I have an idea to make the icon with inversion. Then I add the shape as a background (circle or hexagon for example) and I make cutout to have background and transparent icon inside. I cannot make the boolean operations with shape and path. I have to transform path to the shape.
