### ISSUE TITLE
Photopea Starts to Glitch when Editing: UPDATE

### ISSUE THREAD

**Issue by Jykie** [photopea/photopea#4376]
Hi, I've submitted an issue before with the same title about some glitches I am experiencing. 

I now have a new issue where every time I try to use the smudge tool it would cause photopea to freeze completely. It's been like this since yesterday and I don't know what to do.

I contacted Samsung and they said that my tablet was up to date and there were no issues with the tablet itself. The issues I'm having may have more to do with how Photopea is reacting to the tablet.

I was wondering if you have any suggestions on what I can do to fix this issue?

I have yet to hear back from you since the last thread and it's been over a week and I really need this issue resolve for my work.

**Comment by photopea** [comment]
I just tried the Smudge tool on my phone. It is quite fast with the brush size under 100 pixels. It gets slow with a larger brush size.

What is the size of your brush? Are you sure it worked faster in the past? Maybe your device is simply not powerful enough.

**Comment by Jykie** [comment]
Yeah it worked fine before and the size I had it on was around 20 so not that large. Also my device has 8 GB Ram and 256 SSD. Is that really not enough for photopea?

**Comment by photopea** [comment]
Could you record a video of the Smudge tool glitching, so that I can see how it looks like?

**Comment by photopea** [comment]
I have to close it because of lack of details.
