### ISSUE TITLE
mouseup doesn't end drag when cursor is over an ad

### ISSUE THREAD

**Issue by sophiebits** [photopea/photopea#4377]
If you drag "Opacity" to the right, then release your mouse while your cursor is on top of an ad, then Photopea doesn't register the release of the mouse button. 

<img width="301" alt="image" src="https://user-images.githubusercontent.com/6820/156858381-e8edd52b-3382-4847-96cf-e789acc63a45.png">

It seems to work if the mouse is anywhere else over the entire application interface. I assume the issue is that the `mouseup` event handler is on a nested element rather than on `window`.

**Comment by photopea** [comment]
The ad is a "separate entity", which handles the mouse events in its own way. I am afraid there is no way for us to fix it, other than removing the ad = 90% of our income.

Can you not release the mouse somewhere else? You can also pay for a Premium account, it costs 10 USD for 90 days of no ads.

**Comment by sophiebits** [comment]
I understand that the ads live in their own iframe. One way to fix this would be to temporarily add `pointer-events: none` to the ads while dragging on another part of the interface. I verified that by adding this style to `.pgAdWrapper`, the `mouseup` event can be successfully recorded. So you should be able to apply that style on `mousedown` and then remove it on `mouseup` (to allow for the ads to still be interacted otherwise).

When setting opacity to 100% it is very natural to drag to the right and release, when your mouse would be over an ad. That's why I think more people will run into this.

I will also consider paying for a Premium account – thanks for developing a high-quality product!
