### ISSUE TITLE
removing all inputs

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4378]
In some cases, finger, key or mouse released, but Photopea does not consider they released. Whether a button for executing such as touch up, mouse up... would solve such a proplem?

**Comment by photopea** [comment]
I have implemented it. Once you release a pointer (a finger, a mouse, a stylus), all pointers are deleted. Could you check if it works well?

I guess there is no workflow which requires using 2 fingers, releasing one finger, and then adding it back (while the first finger is still touching). Now, after releasing one of two fingers, two fingers are "forgotten", and adding a second finger will act as having just one finger on the screeen.

**Comment by nothingshiru** [comment]
I did a quick test on touchscreen with fingers. It works well.

**Comment by photopea** [comment]
Ok, lets hope the old issue with an "invisible finger" will never happen again. And if it does, touching and releasing the screen should fix it.
