### ISSUE TITLE
Publish online: to imgur both png and jpg not working

### ISSUE THREAD

**Issue by Yabla1** [photopea/photopea#4379]
When I try to publish to imgur it only shows the prompt alert asking to proceed, I click ok, it shows this message "saving to imgur ..." but nothing happens, even if I wait for minutes, even if it's a small size image.

I'm using Firefox Release 97.0.2 March 5, 2022

**Comment by photopea** [comment]
Photopea should open a new browser window of Imgur. Do you have popup windows blocked in your browser?

**Comment by photopea** [comment]
Maybe your extensions are blocking it Can you try it in the Incognito mode?

**Comment by Yabla1** [comment]
It works perfect in incognito mode, and in permissions for www.photopea.com it says "http://i.imgur.com Allowed Temporarily".
When I tried it back in normal window (not incognito) it works too. Thank you.

**Comment by photopea** [comment]
ok perfect.
