### ISSUE TITLE
Mouse disappears

### ISSUE THREAD

**Issue by DarkMatter78** [photopea/photopea#438]
When I use some of the tools the mouse disappears on the work space so I can't see what I am doing.
I use Chrome

**Comment by photopea** [comment]
Can you be more precise, what tools do you use? so we can reproduce it?

**Comment by DarkMatter78** [comment]
For instance the rectangle tool

בתאריך 8 בינו׳ 2018 21:15,‏ "Photopea" <notifications@github.com> כתב:

**Comment by photopea** [comment]
Photopea uses custom SVG cursors, which probably cause problems. Can you update your browser? Do you have a Retina screen?

**Comment by photopea** [comment]
We restored to the default cursor. We will implement once the Firefox implements image-set.
