### ISSUE TITLE
[Feature request] Viewport controls using Scripting API

### ISSUE THREAD

**Issue by Baegus** [photopea/photopea#4380]
I've been trying to port one of my Photoshop scripts that sets the Zoom level to 100% and automatically scrolls the viewport to a layer that I select in the script's UI.

Basically, I get the layer's boundaries and set the viewport position to those coordinates through a script based on [this `set_doc_position(x,y)` function](https://community.adobe.com/t5/photoshop-ecosystem-discussions/scripting-for-zoom-and-scroll-in-cc2018/m-p/10048762#M191468). This is a super hacky and inaccurate way to do it, but it works.

Do you think it would be possible to implement some viewport controls into Photopea's Scripting API?

**Comment by photopea** [comment]
There is a special object app.UI in Photopea, which lets you control the UI: https://www.photopea.com/learn/scripts

I have added a method scroll(DX,DY), which corresponds to clicking with the Hand tool, moving by DX,DY, and releasing the mouse. Hope it helps!

**Comment by Baegus** [comment]
That's amazing! It definitely helps, but it only seems to work relative to my current position. Would it be possible to scroll to an absolute location in the document, for example 30px from the top and 200px from the left, so that I could always reliabily reveal the layer I want?

**Comment by photopea** [comment]
I have added app.UI.scrollTo(x,y) , which scrolls to a specific point of image (in pixel coordinates).

**Comment by Baegus** [comment]
I think you should win an award for the best customer support on the planet. Thank you, seriously.
