### ISSUE TITLE
A File Decoding Error

### ISSUE THREAD

**Issue by Legogeek33** [photopea/photopea#4381]
I had recently tried to open up a new drawing from last night only to find it won't allow me and the phrase "unknown file format: \u0000\u0000\u0000\u0000" is constantly popping up. I've rebooted my computer, searched for updates, etc. It claims the file is empty and thus it won't load on anything else either. If it helps, the canvas size is 5238 x 2880. If you can offer any help whatsoever I would greatly appreciate it.

**Comment by photopea** [comment]
I think you closed Photopea before the file was written to your hard drive. Your file is 0 bytes. You should not close Photopea before the message Saving disappears.

**Comment by Legogeek33** [comment]
> 

The only issue is that I watched the saving message disappear, but it didn't save any changes to the PSD. Then I decided to go to bed and I woke up, opened Photopea, and there was an extra file with "crswap" at the end.

**Comment by photopea** [comment]
Could you rename that "crswap" to "file.psd"? Does it open in Photopea?

I really think you closed Photopea before "saving ..." disappeared. If not, please, tell me, how can I produce such a damaged PSD in Photopea myself.

**Comment by Legogeek33** [comment]
I don't know honestly, my computer has the most ridiculous mishaps ever and it genuinely gets on my nerves as I still can't tell how it happens. The worst issue is that recently certain changes don't save to my PSD at all. Also, I don't close Photopea often, and I certainly did not last night.

**Comment by Legogeek33** [comment]
I do hope that didn't come off as rude, I've just been having a crazy weekend.

**Comment by photopea** [comment]
Use File - Save as PSD to save a new version of your file (instead of replacing the old version).

After saving, check, if your PSD is not 0 Bytes. If you find some steps about how to create a 0-Bytes PSD in Photopea, I can pay you $1000 for finding a bug.

Browser extensions could ruin the process, too. If I were you, I would disable those you dont need. I use my browser with absolutely no extensions.
