### ISSUE TITLE
Not all metadata being saved - some metadata seems to be changed.

### ISSUE THREAD

**Issue by wbrells** [photopea/photopea#4382]
I've just noticed that quite a bit of EXIF metadata in a JPG file is being lost when I export that image as a new JPG file, even when I have the "attach metadata" option checked. The dropped data probably isn't that critical, but I'm wondering if this behavior is to be expected?

More critically, it appears that some IPTC information is MODIFIED before being saved in an exported JPG file. For example, in the original JPG file I have Caption set to **Photo #4**. In the exported JPG file this Caption has become just **Photo #** without the 4! This would appear to be a "bug" of some type...

Thanks,
Wayne

**Comment by photopea** [comment]
Photopea converts all metadata to XMP, and then, saves it back to XMP / EXIF / IPTC. Only a special set of metadata is supported.

Please, share a photo, where metadata is deleted, and what metadata it is.

**Comment by wbrells** [comment]
I've attached the requested data as follows:
EXIF-Orig-1.png    The first part of EXIF data from the original JPG fileEXIF-Orig-2.png    The second part of EXIF data from the original JPG fileEXIF-Photopea      The EXIF data retained when saving with Photopea
I hope this helps!


Wayne B'Rells
The above signature shows that this is a valid message from me! 

    On Monday, March 7, 2022, 09:37:48 AM EST, Photopea ***@***.***> wrote:  
 
 


Photopea converts all metadata to XMP, and then, saves it back to XMP / EXIF / IPTC. Only a special set of metadata is supported.

Please, share a photo, where metadata is deleted, and what metadata it is.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by photopea** [comment]
To what email address are you sending emails?

**Comment by wbrells** [comment]
Per instructions on your last email, I just did a "Reply to this email directly". Is that not OK? I can reply on GitHub if that is a better option...

Wayne B'Rells
The above signature shows that this is a valid message from me! 

    On Monday, March 7, 2022, 09:57:38 AM EST, Photopea ***@***.***> wrote:  
 
 


To what email address are you sending emails?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by photopea** [comment]
yes, please, reply at Github, because your attachments are lost.

**Comment by wbrells** [comment]
Here once again is (hopefully) the requested data as follows:

EXIF-Orig-1.png    The first part of EXIF data from the original JPG file
EXIF-Orig-2.png    The second part of EXIF data from the original JPG file
EXIF-Photopea      The EXIF data retained when saving with Photopea

I hope this helps
![EXIF-Orig-2](https://user-images.githubusercontent.com/44944548/157073426-5118e53a-6676-45f9-8cd8-e1449d75f721.png)
![EXIF-Orig-1](https://user-images.githubusercontent.com/44944548/157073427-e0cdbdab-7e23-4f83-b195-5426a6e2329b.png)
![EXIF-Photopea](https://user-images.githubusercontent.com/44944548/157073431-f223386a-6131-4f3f-991d-085181ac3758.png)
!

**Comment by wbrells** [comment]
I hope you were able to understand the above listings of EXIF data - they are a bit out-of-order! There is probably not much that can be done to preserve ALL of the EXIF data, but I am concerned about the apparent dropping of some IPTC information which could cause problems. Is this (apparent) problem been reported by anyone else? Thanks, Wayne

**Comment by photopea** [comment]
The goal of Photopea is not only to preserve metadata, but we also let users add and remove metadata to their files, using File - File Info.

I do not know which of the metadata in your screenshot are IPTC. Could you please share a file with us, which loses metadata after re-saving in Photopea? It would help me with testing.

**Comment by wbrells** [comment]
![Marker 4](https://user-images.githubusercontent.com/44944548/157354642-9372a96e-124e-45fa-9a26-1f098d7015d7.jpg)
![Marker 4-pea](https://user-images.githubusercontent.com/44944548/157354672-cd053105-0206-44b0-890e-38b889b9e812.jpg)

Here, I hope, are the original JPG file and then the version exported by Photopea. Wayne

**Comment by photopea** [comment]
I see the four IPTC parameters in your first JPG file:

        [  0, '\x00\x04']
        [120, 'Photo #4']
        [ 55, '20211219']
        [105, '4']

Photopea detects only the parameter "55", which is a Date. Which other parameter would you like Photopea to detect?

**Comment by photopea** [comment]
There really was a bug with last letters disappearing (the letter "4" disappearing from "Photo #4"). I have fixed it.

**Comment by wbrells** [comment]
I'm very glad that the problem with the missing last character in the IPTC data has been fixed - that was my main concern related to preserving JPG metadata. Was my minor concern about preserving ALL the EXIF data ever resolved? (As can be seen near the top of this message thread, there are fewer EXIF entries in a JPG file after it is saved with Photopea. None of the "missing" entries seem very significant, but I was just concerned that this behavior might be revealing a more serious problem...)

**Comment by photopea** [comment]
No, there is no way to make Photopea preserve all EXIF attributes. As I said, Photopea makes every attribute modifiable. We need to manually create a text field for each parameter in your metadata editor.

Currently, we support around 100 metadata fields. If you want, I can add some more, which you need. But there exist tens of thousands of EXIF parameters, it would take me ages to add them all, while nobody probably needs them.
