### ISSUE TITLE
Save Pictures Glitch

### ISSUE THREAD

**Issue by MistakeCode** [photopea/photopea#4384]
Hi, it doesn't let me save pictures nor export them as PNG, JPG, etc. Can you please check it out? Thanks!

**Comment by photopea** [comment]
Hi, could you reload Photopea with Shift + F5?

**Comment by MistakeCode** [comment]
I did that multiple times, but it still doesn't work; it worked perfectly four hours ago, though.

**Comment by photopea** [comment]
What should I do to see it not working?

I opened a JPG file in Photopea. Then, I pressed File - Export As - JPG. A JPG file was saved to my computer.

**Comment by Pradama** [comment]
Experiencing the same issue here, not sure about other features, but it keeps exporting a corrupted PNG file after I cropped an image.

**Comment by photopea** [comment]
Please, someone, describe some steps which lead to the problem.

**Comment by MistakeCode** [comment]
I guess it works with some pictures and with others doesn't, because I tried with one picture and it worked, then I tried with another one and it didn't let me save it nor export it as PNG or JPG: it doesn't even show the picture on the side.

**Comment by Pradama** [comment]
It seems that way. Weirdly enough, it just miraculously exported the image I've been trying to export. Not sure what happened, but it seems to be working perfectly now on my end.

**Comment by MistakeCode** [comment]
I've just noticed it mostly happens when you put a filter on the picture.

**Comment by photopea** [comment]
I am very sorry, there really was a bug. Please, reload Photopea with Shift+F5 and try it again.
