### ISSUE TITLE
Undo/Redo

### ISSUE THREAD

**Issue by Abeelme** [photopea/photopea#4385]
Hello 
Can you please add the Feature of Undo by taping two finger on touch screens 
and thank you so much

**Comment by photopea** [comment]
I have implemented it! :) I wanted to make three-finger tap to go forward, but there is a problem with it.

So let's say the first finger touches the screen at time T1. If a brush is selected, it draws a spot on the layer (and tracks it in History).
If the second finger touches at time T2, it does a step back to delete the spot, and lets you move fingers to zoom.
If you add a third finger at time T3, nothing changes, you can still zoom with the first two fingers.
If you release any of fingers at T4, the zooming stops. If there were 2 or more fingers on the screen, and the difference T4-T3 is less than 0.1 seconds, we can perform a step back or forward, depending on how many fingers were there.

Sadly, at the first event, which one finger draws a spot, it also clears the "future part of history" by adding a new action.

But we could make the "triple-tap to go forward" work for tools, which do not modify the document.

In addition, when the first finger touches the screen, we could pause for 0.1 seconds to see, if more fingers will be added, and if not, tell the Brush to draw a spot. But it will add a delay when drawing. Movements during that 0.1 seconds would be ignored.

What do you think @nothingshiru?

**Comment by Abeelme** [comment]
I just want to say thank thank you so much 
wow you are an amazing man it worked

**Comment by nothingshiru** [comment]
@photopea 
Sorry. I don't quite understand why three-finger tap doesn't work. 

>But we could make the "triple-tap to go forward" work for tools, which do not modify the document.

To do such a gesture, we have to select the "tools" first. It is no more convenient than use the history panel...

>In addition, when the first finger touches the screen, we could pause for 0.1 seconds to see, if more fingers will be added, and if not, tell the Brush to draw a spot. But it will add a delay when drawing. Movements during that 0.1 seconds would be ignored.

delay is awful. Just let the spot be drawn at first.

**Comment by photopea** [comment]
When the spot is drawn at the first touch, the "draw" action is added to the history, which replaces the "future history" of previous work. So you can not step forward anymore.
