### ISSUE TITLE
Copy and Paste

### ISSUE THREAD

**Issue by mswukovitz** [photopea/photopea#4386]
I am unable to copy and paste. I am using Photopea with my class right now and none of the students can either. We are all on different devices. Our brower has the clipboard on and allowed. We disabled all extensions and have tried restarting the program. We have tried different file types also. I have done this in the past and I am not sure why today isn't working. Thanks for your time and support.

**Comment by ezgranet** [comment]
I am having the same issue, but only on Chrome (not Safari!)

**Comment by photopea** [comment]
What should I do to see the bug myself? I tried painting in Photopea, selected it with a lasso, pressed Ctrl+C and Ctrl+V, and it was paseted as a new layer.

**Comment by ezgranet** [comment]
Regrettably, I just updated Chrome to 99.0.4844.51 and still am having the bug.

**Comment by photopea** [comment]
What exactly should I do to see the bug? What should I copy and where, and paste into Photopea? Whatever I try, it always works :(

**Comment by mswukovitz** [comment]
Here is a video of what I am seeing. In the blank pauses, I am doing the key commands Cnt C and Cnt V.

**Comment by photopea** [comment]
I am very sorry, there really was a bug, it is fixed now.
