### ISSUE TITLE
Error: "Your browser is too old" when accessing photopea.com in latest version of Microsoft Edge

### ISSUE THREAD

**Issue by ToFab** [photopea/photopea#4387]
When accessing photopea.com in the latest version of Microsoft Edge you are being greeted with the following message

![image](https://user-images.githubusercontent.com/3883944/157628686-3e95dd2c-bb38-4929-b0f8-8adfa16b6630.png)

Browser info:
![image](https://user-images.githubusercontent.com/3883944/157628789-05871467-6321-4c10-980b-14e295d635bf.png)

After clicking OK you see a blank page
![image](https://user-images.githubusercontent.com/3883944/157629025-72fb96d0-9402-4a17-8577-395547bd0b4b.png)

I do not get the error message in Brave or Firefox. 

If this error message is intended may I suggest that some additional info is included regarding what to do because there is nothing to upgrade to.

**Comment by photopea** [comment]
Could you go to edge://settings , choose "Privacy, search and services" on the left side, scroll down to "Enhance your security on the web" and disable the switch?

![image (3)](https://user-images.githubusercontent.com/15955558/156672749-44cdd6b2-6a80-4f3d-82b8-8ccf63d9f52a.png)

**Comment by ToFab** [comment]
Thank you. That solved the issue :)

**Comment by sam1310** [comment]
> Could you go to edge://settings , choose "Privacy, search and services" on the left side, scroll down to "Enhance your security on the web" and disable the switch?
> 
> ![image (3)](https://user-images.githubusercontent.com/15955558/156672749-44cdd6b2-6a80-4f3d-82b8-8ccf63d9f52a.png)

Probably more secure to add `https://photopea.com` as an exception, rather than turning off the entire feature.

**Comment by photopea** [comment]
@sam1310 not at all. The web standards are already design in a way which guarantees security. This is just a marketing trick of Microsoft, trying to sell you something "others don't have". But it only breaks the functionality, that is all.
