### ISSUE TITLE
Can't save

### ISSUE THREAD

**Issue by Ragekraft** [photopea/photopea#4388]
I tried saving my image like 20 times and didn't work and still isn't working

**Comment by Ragekraft** [comment]
also I tried both save as PSD and export

**Comment by photopea** [comment]
Did it ever work in the past? Can you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by Ragekraft** [comment]
It did work with another project but that particular project was not being saved so I took it's screenshot and cropped it

**Comment by Ragekraft** [comment]
So like the p1 was not saving but when I opened p2 it saved 
So I took a screenshot of p1 and saved the screenshot

**Comment by Ragekraft** [comment]
and yes it has worked everytime in the past and hence I use photopea

**Comment by photopea** [comment]
Are you able to open www.Photopea.com right now, and re-create a situation, such that the file is not saved after you press Save?

**Comment by photopea** [comment]
I have to close it because of lack of details.
