### ISSUE TITLE
Debugging script

### ISSUE THREAD

**Issue by maLikiz** [photopea/photopea#4389]
Hi, I'm trying to use one of the scripts to export multiple files +json. But unfortunately I get errors and can't debug them. In the browser inspector, I get errors unrelated to my code.

Script: https://github.com/EsotericSoftware/spine-scripts/blob/556429846f40f1eae54a48c561a8dbf0479e4717/photoshop/PhotoshopToSpine.jsx

![image](https://user-images.githubusercontent.com/4878139/157743012-267fcfad-5ded-455c-9453-1959787f3ac4.png)

**Comment by photopea** [comment]
I am afraid that script is too heavy for me to debug. Do you maybe have a shorter script?

**Comment by maLikiz** [comment]
Unfortunately not. I am not its creator. I was just looking for an analogue of Photoshop that could execute this script.

This script generates json of layers, where their names, coordinates, sizes, and so on are described. And it also exports png layers.

When using an incorrect script, I expected the browser console to inform me about the location and cause of the error. But it refers to the code from pp.js, which makes it impossible to understand which part of the code causes an error when executing this script.

**Comment by photopea** [comment]
Your script uses many features, that are not supported now. It creates UI elements, makes ActionDescriptors (which even I dont understand in Photoshop). It would take me weeks to add all these features.

I recommend you to write your own script using a subset of Photoshop scripts. Many companies do it to analyze PSD files in Photopea. These scripts are not executed by a browser. They are executed by our own JS interpreter.
