### ISSUE TITLE
allow zoom during black&white

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#439]
https://youtu.be/BIfWupTF774

**Comment by photopea** [comment]
We made an important decision some time ago, that when some window is open (e.g. Adjustment or Layer Style), all mouse events are delivered to that window. I.e. regular tools (like Zoom tool) do not work, if any window is open.

Try using Adjustment layers to do Black and White. You change parameters in the Properties panel, there is no window for it (i.e. you can use the Zoom tool). See https://www.photopea.com/learn/other-layers
