### ISSUE TITLE
 Image Canvas Glitch?

### ISSUE THREAD

**Issue by strexgth** [photopea/photopea#4390]
Hi, good evening, 

 When I try to switch between projects or add a new image from File>Open From URL, it will randomly make the projects invisible. All I have to do is click either a tool (not tried yet), but I use the Rectangle Select tool to just click on the canvas, and it'll return. 
 Everything works fine, but this bug/glitch is just bothersome.

**Comment by photopea** [comment]
I tried several things, but I can not see the problem :(

Could you please write specific steps, which I should do to see the problem myself?

**Comment by strexgth** [comment]
Okay, sure. 

First, I'm on a Linux Distribution (Mint), and I am using the Photopea application, not the website. 
You can try to copy and paste this URL image (Kanye West) into "File>Open More>Open from URL...>Current Project"

https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Kanye_West_at_the_2009_Tribeca_Film_Festival_%28cropped%29.jpg/800px-Kanye_West_at_the_2009_Tribeca_Film_Festival_%28cropped%29.jpg

And that's what does it for me.

**Comment by photopea** [comment]
What is a "Photopea application"? We only have a website, but you can also press More - Install Photopea, to get a browser-less experience. We do not have any other "applications". You should ask the person who made your application.

**Comment by strexgth** [comment]
OH, wow. That's weird. There is a software application version of "Photopea" on flathub.org  That's where I downloaded and installed it from. I thought you were the makers of that app?

**Comment by photopea** [comment]
I dont know flathub.org :( Maybe ask them to fix it.

I recommend opening www.Photopea.com and pressing More - Install Photopea. You will get an icon on your desktop (or on a homescreen of your phone), which will offer you a browser-less experience.

**Comment by strexgth** [comment]
Okay, will do. Thanks.
