### ISSUE TITLE
Hello, when ever i try tu use the brush tool to paint something, nothing is appearing.

### ISSUE THREAD

**Issue by Data445** [photopea/photopea#4392]

**Comment by photopea** [comment]
Maybe you are painting with white color on white background.

**Comment by Data445** [comment]
> Maybe you are painting with white color on white background.

i checked and that wasn't the problem, my backround is white and i chose the colour green.

**Comment by MichalSZZ** [comment]
Maybe you have opacity of the brush set to 0 or flow set to 0? It is in the top menu of the that tool.

**Comment by Data445** [comment]
> Maybe you have opacity of the brush set to 0 or flow set to 0? It is in the top menu of the that tool.

Hello,i managed to fix the problem, but it wasn't anything to do with opacity or colour of the brush, i think it was just a little bug.
