### ISSUE TITLE
[Suggestion] Functionality to read *.kra (Krita Document) files

### ISSUE THREAD

**Issue by Mwalters75** [photopea/photopea#4393]
*.kra files are Krita Documents not exported to a diffrent format
<sup>It's also open-source, so that's one reason!</sup>

**Comment by photopea** [comment]
You can open .KRA and .KRZ files in Photopea now. Could you try it and if you can not open a specific file, or it does not look right, could you send it to me to support@photopea.com ?

**Comment by Mwalters75** [comment]
It works,
![image](https://user-images.githubusercontent.com/67456566/159267448-cffbe75c-987e-4a13-af72-a60cdcb2964a.png)
But, animations are glitched, but other that that, it works!

**Comment by photopea** [comment]
Photopea does not support animations like Krita does. So all we can do is e.g. show the initial state of the animation. Does it work like that? Do you think there is a better way to convert your KRA files to PSD files?

**Comment by photopea** [comment]
So the support should be there, I will close it now.
