### ISSUE TITLE
I can't use "gaussian blur" 2

### ISSUE THREAD

**Issue by batudc** [photopea/photopea#4394]
When I use the Gaussian Blur filter, the image disappears. Everything is fine before that, but after clicking the filter the image disappears, even the preview.
![Screen Shot 2022-03-11 at 10 20 10 PM](https://user-images.githubusercontent.com/101424851/157939161-6ad67681-1d48-46f1-99f3-82291b00e7c0.png)
![Screen Shot 2022-03-11 at 10 20 18 PM](https://user-images.githubusercontent.com/101424851/157939263-84453385-acea-4ed4-98ea-a39bb5c01129.png)
![Screen Shot 2022-03-11 at 10 20 21 PM](https://user-images.githubusercontent.com/101424851/157939304-499dca79-4f50-4dc5-a8ca-2edfcaca339e.png)
![Screen Shot 2022-03-11 at 10 20 29 PM](https://user-images.githubusercontent.com/101424851/157939333-6c9a80f9-5b10-487c-8627-373009da050f.png)
![Screen Shot 2022-03-11 at 10 20 32 PM](https://user-images.githubusercontent.com/101424851/157939355-6f252b0f-00b3-4613-9908-188d90cea277.png)

**Comment by photopea** [comment]
What exactly do you want your image to look like? Your image is 5x5 pixels and you set the blur radius to 7.2 pixels. That is why the result is almost transparent (bluring a 5x5px dot by 7 pixel radius makes it almost diappear).

**Comment by batudc** [comment]
Whatever it is the problem always happens! There is a different example here.
İ did another think before but today when i just unvisible the efect and make it visible back the image disappears

https://user-images.githubusercontent.com/101424851/157975799-df5a9f44-83c8-4e8c-9d77-e5e0f11ee614.mov

.

**Comment by photopea** [comment]
I can not reproduce such behaviour :( Could you try these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

Also, what is the resolution of your image? Is it over 200 million pixels?

**Comment by batudc** [comment]
Yeah resolution is 1080*1920 but it's also not about that or about pixels! This was working before.... i tried with different browsers did everything what i can do already :(

**Comment by photopea** [comment]
Our Gaussian Blur runs on the GPU. Did you change drivers or something? Can you reboot your device?

**Comment by photopea** [comment]
It works with any browser in my case :( Please, update your browsers and try to disable extensions.

Maybe you have a specific extension in all your browsers except Brave.
