### ISSUE TITLE
Liquify being a piece of... bad.

### ISSUE THREAD

**Issue by USERPASTE** [photopea/photopea#4397]
Every time i use it, it doesn't do anything and disappears. I can't see what i'm doing and its really annoying. Why does it do this and how can i stop it without losing my work?

**Comment by photopea** [comment]
What should I do to see the Liquify not working? Whenever I try it, it always works perfectly :(

Are you using Photopea at www.Photopea.com ? Is your web browser updated?

**Comment by photopea** [comment]
I have to close it because of lack of details.
