### ISSUE TITLE
.png files unable to open

### ISSUE THREAD

**Issue by Powerman7224** [photopea/photopea#4398]
when opening some .png files an error message pops up saying that the file is unable to be opened as it contains system files.

**Comment by photopea** [comment]
Are you using any browser extensions? Is the folder in your computer protected somehow?

**Comment by Powerman7224** [comment]
No

ISA
________________________________

**Comment by photopea** [comment]
Could you send me a PNG file, which you can not open in Photopea, to support@photopea.com ?

**Comment by photopea** [comment]
I have to close it because of lack of details.
