### ISSUE TITLE
Raster mask

### ISSUE THREAD

**Issue by suburbansteve** [photopea/photopea#4399]
When I have an image open and try to use a gradient on a raster mask it just treats me like I've painted it all with black, everything disappears, if I use a soft brush it works fine and only the part I paint disappears leaving a graded edge to the stroke.. its driving me crazy as I really have no idea what's happening, some advise would be really appreciated.
Thanx.

**Comment by photopea** [comment]
Don't use gradients with a transparency in masks. Use e.g. a white-black gradient.
