### ISSUE TITLE
Select layer by clicking on its pixels.

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#44]
Now, you can choose the active layer in Layers panel only. 

It would be nice to choose layer through the image by clicking on its pixels. In Adobe Photoshop, it can be done with Move tool, while holding Control.

**Comment by tomasnosek** [comment]
+1 - very important app feature for better UX

**Comment by photopea** [comment]
Done :)

**Comment by Studioartcz** [comment]
Thanks!
