### ISSUE TITLE
drop shadow

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#440]
hi,

where can I setup "drop shadow" to the my layer?
thanks

**Comment by photopea** [comment]
You can do it in the Layer Styles window. Double-click the layer (in the Layers panel), or right-click it and choose Blending Options. See here: https://www.photopea.com/learn/layer-styles

**Comment by photopea** [comment]
Would you prefer any other way to do it?

**Comment by landsman** [comment]
Missing me in the "layer" main menu and in right-click. I know "Layer properties" I think.

**Comment by photopea** [comment]
Hi, I added the option Layer - Layer Style - ....
