### ISSUE TITLE
Raster mask not resolved

### ISSUE THREAD

**Issue by suburbansteve** [photopea/photopea#4400]
In this tut    https://www.youtube.com/watch?v=dbf5aCz7hr8     at about 1min 20 seconds the person replicates a layer changes the bottom layer to multiply and leaves the top at normal, then places a raster mask on the top layer and with the gradient tool set to black to no colour he then adds gradients to different part of the layer.
I cannot replicate this, if I use a gradient black to white its fine but only work for one pass then resets itself each pass I make so I cannot grade a part of the image to highlight it.
I hope you understand my description if not the vid link will show you.
Thanx

**Comment by photopea** [comment]
it is already in our todo list: https://github.com/photopea/photopea/issues/2481
