### ISSUE TITLE
Ctrl+Shift+Tab does not go to the previous tabbed document

### ISSUE THREAD

**Issue by setiawanj** [photopea/photopea#4401]
I don't have Photoshop installed so I can't confirm/compare behaviour. Going by (muscle) memory however, I seem to recall that Ctrl+Shift+Tab will take you to the previous tabbed document (similar to many other desktop applications). Currently, this shortcut behaves the same as Ctrl+Tab (takes you to the next tabbed document).

**Comment by photopea** [comment]
I have implemented it! Note, that probably all browsers do not allow websites to use Ctrl+Tab shortcut (they switch tabs when you do it), but it should work in the "installed" mode. I hope browsers will let websites use this shortcut in a regular mode, too.
