### ISSUE TITLE
Exported DXF files not opening in AutoCAD 2020

### ISSUE THREAD

**Issue by AsafeMendes** [photopea/photopea#4403]
When I try to open it in autocad it enters an unidentified command that asks me to press enter but no new windows are open, when I drag and drop the file on a new drawing it says that the DXF entry is invalid or incomplete.

[Here ](https://fromsmash.com/LogoSphotopea)is, zipped and attatched, a PSD file which I opened in Illustrator and exported to DXF and is working fine as well as the DXF file itself  as a sample.

**Comment by photopea** [comment]
It seems like your link is expired :( could you attach a ZIP file here on Github?

**Comment by AsafeMendes** [comment]
I'm having a problem uploading zip files, some of them are accepted, some don't. The ons I'm compressing aren't being accepted, I uploaded to [google drive ](https://drive.google.com/drive/folders/1v5FSENbONryxkfe_mXSyHQnWoAJfoKOD?usp=sharing)

**Comment by photopea** [comment]
So you made your PSD in Adobe Photoshop, and you use Adobe Illustrator to convert it into a DXF?

Are you aware, that there are Paths in your PSD, which are not visible initially? Did you create them?

Maybe we could find a simpler workflow, which would work for you, which does not require a 100 MB PSD file.

**Comment by AsafeMendes** [comment]
Yes I created it initially in photopea but only photoshop allows me to export the paths to Illustrator and then to DXF. I need those paths bc they are transformed in the curves in the DXF

**Comment by photopea** [comment]
So you are using three different programs to get your work done? Have you tried to draw vector layers in Photopea, and then, export a DXF?  It is described here: https://www.photopea.com/learn/vector-graphics   Or load an SVG into Photopea and export a DXF?

**Comment by AsafeMendes** [comment]
Well, my first PSD files for this process always come from photopea as it fits me better than photoshop, but as my original post in this topic describes I can't open the DXF generated in photopea using my AutoCAD 2020

**Comment by photopea** [comment]
Try to make shapes in Photopea as I described. If you do, the DXF from Photopea should be ok. Did you try it?

**Comment by AsafeMendes** [comment]
I did, e drew rectangles, lines ans elipses as path and as vector shapes, AutoCAD doesn't accept none of them

**Comment by photopea** [comment]
Can you open this document https://www.photopea.com/#i2UHUCusv  and export it as DXF? When I did it, I got a 320 Byte DXF file.  I uploaded the DXF file into this DXF to PDF converter: https://www.zamzar.com/convert/dxf-to-pdf/  and it gave me a PDF with two rectangles.

Are you sure that 320 Byte DXF does not work in AutoCAD? Can you send me a screenshot of an error?

**Comment by photopea** [comment]
I have to close it because of lack of details.
