### ISSUE TITLE
Import PDF - some things are not being import

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4404]
![image](https://user-images.githubusercontent.com/11801254/158636793-ffd1b6b0-94bb-49d4-b850-abc0749c913d.png)

For some reason, this document did not load correctly.
[results.pdf](https://github.com/photopea/photopea/files/8265281/results.pdf)

Can you check please?

**Comment by photopea** [comment]
I have improved the way Photopea handles your file.
