### ISSUE TITLE
I'm trying to make an empty but what I save it it's blurry

### ISSUE THREAD

**Issue by akio00343f** [photopea/photopea#4405]
I'm trying to make an empty but what I save it it's blurry whyyyyyyyyyyyyyyyyyyyyyyy????????????![New Project (8)](https://user-images.githubusercontent.com/98995016/158718702-4dc50a75-5e90-4198-9a1b-35c0e48402a3.jpg)???????????????????????????????????

**Comment by akio00343f** [comment]
I'm trying to make an empty but what I save it it's blurry

**Comment by photopea** [comment]
Hi, what is an empty?
