### ISSUE TITLE
Feature Request: Option to Insert Arrows at the Ends of a Line

### ISSUE THREAD

**Issue by Erelynn** [photopea/photopea#4406]
I use the **Pen** and **Line** tools to create arrows, but it's tedious because I have to draw them by hand since there is no option to insert an _arrow head_ at the end of a line. It would be very helpful if a feature like this is added because it will help me create better looking arrows in a much easier and faster way.

**Comment by photopea** [comment]
Hi, have you tried this? https://twitter.com/photopeacom/status/1424285930471534593

**Comment by Erelynn** [comment]
> Hi, have you tried this? https://twitter.com/photopeacom/status/1424285930471534593

Thank you for letting me know. It's helpful that this feature is available for the **Line tool**. I wish it would also be available for the **Pen tool** because a lot of the time I need to draw **curved arrows**.

**Comment by photopea** [comment]
I cant see how such feature can be added to the Pen tool.

If you draw arrows manually, add them to the Shape gallery using Edit - Define New - Custom Shape.
