### ISSUE TITLE
Feature Request: Slice Image into a Specified Number of Equal Parts

### ISSUE THREAD

**Issue by Erelynn** [photopea/photopea#4407]
Photopea has a slice tool but I haven't found any way that this tool can be used to automatically divide the image into equal parts. I wish there was an option for me to specify the exact number of slices I want the image to be split into.

Photoshop has this feature and these are some examples of how it works.

This video shows how the slice tool can be used to split an image horizontally to create an Instagram Carousel.
[https://www.youtube.com/watch?v=ixwHFw36vDE](url)

This video shows how the slice tool can be used to split an image vertically in order to prepare a Webcomic for upload.
[https://www.youtube.com/watch?v=DTioZoLSXP8](url)

It is a tool that makes the process easy, fast, and accurate. I hope this feature gets added to Photopea because it would be very helpful.

Thank you!

**Comment by photopea** [comment]
I have implemented it. When using the Slice Select tool, there is a button "Divide" in the top menu.

**Comment by MichalSZZ** [comment]
I just tested. Works great!
@photopea  Could you add a live preview when user type the value?

**Comment by photopea** [comment]
done :)

**Comment by MichalSZZ** [comment]
thx :)

**Comment by Erelynn** [comment]
> I have implemented it. When using the Slice Select tool, there is a button "Divide" in the top menu.

That's great to hear. Thank you! :)
