### ISSUE TITLE
Text selecting and carriage return issue

### ISSUE THREAD

**Issue by Phealoon** [photopea/photopea#4408]
It seems that when trying to select a group of text, the typical highlight box is missing. In addition, anytime I type a sentence and hit the enter key, instead of issuing a carriage return, the text cursor moves to the center of my sentence and writes over the top of the current text. This happens even when making a text box area as well.

**Comment by photopea** [comment]
That sounds very weird. Could you maybe record a video of it? Did you set the Leading (line height) to zero?

**Comment by photopea** [comment]
I have to close it because of lack of details.
