### ISSUE TITLE
Holding modifier key with multiple commands repeats first action

### ISSUE THREAD

**Issue by chaserau** [photopea/photopea#4409]
First of all, amazing product, very in awe of the effort that has gone into this.

Just want to report a frequent bug I encounter to do with modifier keys (alt,ctrl,option) where holding the modifier down while pressing a series of other individual keys seems to cause unexpected behaviour.

A specific example, in Photoshop I frequently speed zoom-in and out holding 'Command' then pressing '+' in repeated quick succession, or holding Command and hitting '-' in repeated quick succession. That works fine in photopea, BUT if I hold 'command', press '+' a few times, then, while still holding down the 'command' key, start pressing '-' to zoom out, the application continues to zoom in, as if I were still pressing the '+' key.

I've noticed other unexpected behaviour to do with this 'held modifier' bug. One example I just managed to produce was holding 'command' then pressing 'A' (select all), 'C' (copy), 'V' (paste), and then 'Z' (undo). Instead of undoing the last step, it seems to glitch.

Realise this seems like a very niche and pointless request, but having a job where I need to turn out pretty highly detailed graphic work on a very tight schedule, being able to run through multiple commands in a fraction of a second is really crucial to my workflow, and this is about the only thing holding me back from making Photopea my design software of choice.

Once again thanks for developing such amazing software. Truly in awe of your work.

**Comment by photopea** [comment]
It is a well-known bug in Mac OS. When you hold a Command key, and release some key, the release is not reported to the program. So if you still hold Command and release the Minus, Mac OS does not tell us that you released the Minus.

https://stackoverflow.com/questions/27380018/when-cmd-key-is-kept-pressed-keyup-is-not-triggered-for-any-other-key

You can ask Apple to fix it. Otherwise, you have to release the Command key before zooming in. Or use the Ctrl instead of the Commadn key.

**Comment by photopea** [comment]
It is not a pointless request. It is reported very often to us. I wish we could do something about it. If you have a device with Windows, Linux, Chrome OS etc, there is no such problem.

https://github.com/photopea/photopea/issues/4320
https://github.com/photopea/photopea/issues/4008
https://github.com/photopea/photopea/issues/3433
https://github.com/photopea/photopea/issues/3245
https://github.com/photopea/photopea/issues/2983
and so on.

**Comment by dnicolson** [comment]
I'm not so sure this isn't technically possible on macOS. [Figma](https://www.figma.com/) does not have this problem.

It's difficult to reason about minified JavaScript, but Figma references the `metaKey` property far more than Photopea does.

This [Pen](https://codepen.io/chriscoyier/pen/mPgoYJ) seems to also indicate that it's possible using various combinations of Command key combinations.
