### ISSUE TITLE
bad saving to the raster?

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#441]
![screen shot 2018-01-09 at 01 37 56](https://user-images.githubusercontent.com/3184228/34699477-d10ac2dc-f4dd-11e7-8621-d0b261aa0eb9.png)

PSD in mail...

**Comment by photopea** [comment]
The exported JPG is correct (zoom in to see the noise), but the preview in Photopea is not correct.

When you have a bitmap 1000 x 1000 px and the preview on your monitor is only 500 x 500 px, the image should be scaled down, and one preview pixel would have the average color of 4 original pixels (the noise would be decreased, that is what you see in your JPG).

Right now, Photopea does not compute the average of 4 pixels, but it takes the color of the top left pixel (so it preserves the noise even after you zoom out). We will fix it in the future.

**Comment by photopea** [comment]
If you disable WebGL in Photopea (More - Use WebGL), the preview will be correct. We will fix the WebGL version soon, too. We are planning to rebuild the whole rendering pipeline, so it can handle much larger images.
