### ISSUE TITLE
Can't move layers and folders to another file tab.

### ISSUE THREAD

**Issue by lunaracore** [photopea/photopea#4410]
I have two tabs open: one for my photo and the other for my PSD filter. I tried to click and drag the filter folder to the tab as one does, but it doesn't get dragged with the cursor. How do I fix this? Help me, Github. You're my only hope.

**Comment by photopea** [comment]
You can not drag items from the Layers panel to another tab. You can only drag layers from the workspace area this way (with the Move tool).
