### ISSUE TITLE
Cannot adjust layer icon size!

### ISSUE THREAD

**Issue by Asectic** [photopea/photopea#4411]
Hmm... I don't know how to include an image here on Github yet. So I'll link the same post I made on Reddit:

[https://www.reddit.com/r/photopea/comments/tgtnw0/increase_size_of_layer_components/](url)

But essentially I cannot find any option to enlarge layer icon sizes in Photopea. I'm just not sure if that feature has been implemented yet, but if it has can someone advise me what to do? I use an 24 inch iMac desktop, and with Photopea's current layer icon sizes, I cannot see any layer images properly. So I want to be able to enlarge every single layer icons in the layers panel.

**Comment by photopea** [comment]
There is a menu at the top right corner of the Layers. You can increase the Preview size there now.
