### ISSUE TITLE
[Suggestion] Guide Layout and Minor Bug

### ISSUE THREAD

**Issue by Ajethiel** [photopea/photopea#4414]
I work with students who use Photopea for game development, and I would love the addition of easy ways to set up more precise Guides. Sadly the grid feature doesn't help when we need 3 columns and 4 rows of sprites. We tried to use the "Add Guide" feature, and it wasn't immediately clear that it asks for a list of inputs seperated by commas - we initially tried adding one at a time and it'd delete our previous guide we added. (Clearer UI would help!)

Photoshop has a great feature called Guide Layout that lets the user define how many rows and columns they want, without having to use math to divide it up ourselves. My students have a range of disabilities so this would be super beneficial accessibility-wise, and would also save many more people some headache and make work faster and more efficient!

We also noticed a bug where when dragging a selection in from another open photopea document/tab, a guide would often move as though it thought it was being selected and dragged instead of the selection that was being dropped in. This can be avoided by copy pasting a selection in instead, but I feel I should report the bug anyway.

**Comment by MichalSZZ** [comment]
menu Windows -> More -> Guide Guy. That is what you need for the Guide Layout :)

**Comment by photopea** [comment]
The Windows -> More -> Guide Guy should help you :)

You can not drag selections to other tabs in Photopea now. Copy-paste the selected content into a new layer (e.g. with Ctrl+J) and drag that new layer.
