### ISSUE TITLE
Layers Channel

### ISSUE THREAD

**Issue by XxxX-Rj-XxxX** [photopea/photopea#4415]
Hi 

i was working on a project and my layers channel suddenly disappeared

**Comment by photopea** [comment]
Do you mean the Layers window? Press Window - Layers.

**Comment by XxxX-Rj-XxxX** [comment]
thank you so much

still getting use to this never used it before.
________________________________

**Comment by photopea** [comment]
You can learn a lot at www.Photopea.com/learn .
