### ISSUE TITLE
Keep aspect ration without Shift, change size freely with Shift

### ISSUE THREAD

**Issue by Abeelme** [photopea/photopea#4416]
Hello 
Can you please make the same aspect ration when resizing without shift ! 
and shift for free resizing just inverse it

**Comment by TheRadicalDreamer** [comment]
how does it work on Photoshop?

It does make things more easy tbh

**Comment by MichalSZZ** [comment]
Yes. But not for users like me - who are using Photoshop with that behavior for 20 years :)
In new Photoshop it works like you described, but there is an option to use it in old style version :) For all dinosaurs like me :)
I like to use Shift to have the same ratio, but I understand - those better for UX - change. But it should to be an option (toggle) to work with Shift like in old Photoshop too.

**Comment by photopea** [comment]
I have implemented it! Here are some details to explain what it actually is!

- it affects only the Free Transform (other rectangle-making tools - Crop tool, Text tool, Rectangle Select tool - are not affected)
- the main option is this tiny chain icon, which locks the aspect ratio
![image (1)](https://user-images.githubusercontent.com/15955558/166737694-15a3a18f-b4d8-46fa-86c7-b1ac54a8146a.png)
- it is enabled by default. If you switch it, Photopea remembers it after closing and re-opening
- the Shift key simply "inverts" the functionality of the Chain icon

So just disable this icon and the Free Transform will work "the old way" forever.

**Comment by TheRadicalDreamer** [comment]
Great solution for all tastes!

**Comment by photopea** [comment]
There are so many people complaining about it, e.g. https://twitter.com/ErinNudi/status/1522213335831355392

**Comment by TheRadicalDreamer** [comment]
It has more to do with not announcing it rather than the uncomfortable of
changing the mode.

Do a post on Twitter. Maybe there you can see real reactions :)
