### ISSUE TITLE
Feature Request: Cropping Graphics After Importing Them Into the Canvas

### ISSUE THREAD

**Issue by Erelynn** [photopea/photopea#4417]
I’d like to be able to crop photos & graphics that I import into the canvas after I have imported them. I only want to crop individual graphics, without cropping the rest of the canvas.

I’m usually bringing together multiple graphics on a single canvas and they’re not always cropped perfectly. Because of this, I have to open them on a new canvas just to crop them, and then I have to save them on my computer again before I can import them on the canvas I’m working on. It’s a tedious process, and I often need to go back & forth because I don’t always crop them perfectly right away. It’s hard to know what the cropped image will look like until I import it into the canvas I’m working on and view it in relation to everything else. This problem could be avoided if I was able to crop the graphics after I import them, since then I’ll be able to see exactly how I need to crop them according to what will work best with the overall design.

So, I wish there was a way to crop imported photos & graphics, without affecting the rest of the canvas. It'd be helpful if I could crop graphics like I am able in Canva, where I can crop each graphic individually and even go back to change how much of the graphic is cropped.

Thank you for reading my feature suggestion :)

**Comment by photopea** [comment]
You can draw a Rectangular selection on top of a layer, press Ctrl+J to duplicate the selected content into a new layer, and delete the old layer.

**Comment by MichalSZZ** [comment]
Try to use vector mask. It should work for you. But you have to read how does it work in Photoshop.

I don't use Canva but I think they use that function to do that. But maybe with a little better UX than in Photoshop/Pgotopea. I saw that feature in many simple (for user) web aps.
