### ISSUE TITLE
cant save

### ISSUE THREAD

**Issue by tincan771** [photopea/photopea#4418]
I can't save my work anymore. When i try, the whole Photopea Browser Window disapears.

**Comment by tincan771** [comment]
> I can't save my work anymore. When i try, the whole Photopea Browser Window disapears.

And it's shown this in the browser : blob:https://www.photopea.com/4d130ee5-c88a-434d-8b7a-857e06fc7b45

**Comment by photopea** [comment]
What browser and device do you use? Is your browser updated? Did it ever work in the past?

**Comment by tincan771** [comment]
I use firefox, the latest update. It worked very well in all the weeks before!

**Comment by photopea** [comment]
What should I do in Firefox to not be able to save my work? When I save a file as a PSD in Photopea in Firefox, it is saved correctly :(
