### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by illucent** [photopea/photopea#442]
Hello! I want to translate UI to ukrainian, clicking on "Українська" shows 2 fields:
"English:" (as source language) and "Nederlands:" (as target lang) instead of Ukrainian (uk),
or may be another translation tool e.g. https://weblate.org ?

**Comment by photopea** [comment]
Hi, sorry, it happens dometimes, that our "translation database" gets damaged, and I have to restore the previous version manually. So I restored it. I still don't know why it happens.

Weblate seems too complex, users have to register in order to translate.

**Comment by illucent** [comment]
:) Thanks!

**Comment by photopea** [comment]
Нема за що! :)  I returned from Ukraine yesterday! :D

**Comment by photopea** [comment]
So how is your translation going? :) Ukrainian is almost complete.

**Comment by illucent** [comment]
it was a lot of holidays i will complete translation at monday

**Comment by illucent** [comment]
Hi! Translated (ukrainian) uk_UA 100%, i have some experience with image and photo manipulation software and used tech dictionaries, so i think translation is proper, please update lang database. Thanks.

**Comment by photopea** [comment]
Hi Andrew, thank you very much!
BTW. Sharpen Edges - Збільшити різкість країв  - are you sure this is correct? The "edge" does not mean an edge of some surface, but places, where colors change.

E.g. https://en.wikipedia.org/wiki/Edge_detection  is translated as https://uk.wikipedia.org/wiki/%D0%92%D0%B8%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F_%D0%BA%D0%BE%D0%BD%D1%82%D1%83%D1%80%D1%96%D0%B2

**Comment by illucent** [comment]
yes not sure, i've used most common names as if for non-scientists

**Comment by photopea** [comment]
Ok, thanks, I just published it :)

**Comment by illucent** [comment]
Hi again! Using  https://photoshoplessons.ru/perevod, https://www.microsoft.com/en-us/language/Search and wikipedia corrected all translated strings. Please update ukrainian translation.

Some strings in english web UI have no corresponding strings to translate in localised ukrainian:

```
File -> Export as
Save for web -> don't use palettes ( checkbox )
Layers ( panel ) ->  filter names (starts with "Pass through")
Edit -> Define new
```

**Comment by photopea** [comment]
Ok, I just updated it. BTW.  I edited the ukrainian translation yesterday, too.

Some phrases are not available for the translation, because I am not sure about them in English. They would probably be changed / removed in the future.

**Comment by illucent** [comment]
clear :)
