### ISSUE TITLE
PSD Documents failing to save to Goodle Drive

### ISSUE THREAD

**Issue by master-puller** [photopea/photopea#4421]
# Bug
### Expected behavior:
When using the command `CTRL + S`, or manually clicking save to drive, the PSD format should save to Google Drive, possibly with a backup stored locally. While the file is not saved it should display an unsaved work prompt at the browser. Closing the tab in photopea should also display this prompt.
### Actual behavior:
Photopea pops up a window messaging `saving`, and can quit the window immediately. All work is lost without any indication or warning of the user

### System / Browser
- Windows 10 10.0.17134
- Firefox 98.01 (64 bit)

**Comment by photopea** [comment]
I double-clicked a PSD file in Google Drive, it was opened in Photopea. I edited it and pressed Ctrl+S, it was saved correctly to Google Drive.

What should I do to see the behaviour that you describe? Is it about a specific file? Could you share it?

**Comment by photopea** [comment]
I have to close it because of lack of details.
