### ISSUE TITLE
Photpea to Zepline

### ISSUE THREAD

**Issue by mubeenfayyaz20** [photopea/photopea#4422]
HI Phtopea i need some help can you tell me how i can export PSD from Photopea and upload into zepline account

**Comment by photopea** [comment]
Try File - Save as PSD.

**Comment by mubeenfayyaz20** [comment]
no there is no option to save on zepline

**Comment by mubeenfayyaz20** [comment]
Please help its very urgent

**Comment by mubeenfayyaz20** [comment]
no, i want to upload the PSD into zepline  via using photpea
