### ISSUE TITLE
cannot copy from app

### ISSUE THREAD

**Issue by luikluikluik** [photopea/photopea#4424]
we cannot copy an image from the site, it just doesnt work, when i paste it there's something older in the clipboard

also: it would be soooo much better if when we create some new project it would automatically suggest the size of the picture in the clipboard, like almost every other app do

**Comment by photopea** [comment]
Hi, what do you mean by "copy from app"? What should I do to see the problem myself?

Photopea should detect the content of your clipboard, and set the default size to the size of that content. But sadly, only Chrome and Edge browsers support it at the moment.

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by photopea** [comment]
Are you using Firefox? There is a bug with a clipboard in Firefox. You can ask Firefox to fix it, or switch to a better browser.
