### ISSUE TITLE
CORS policy error when saving files

### ISSUE THREAD

**Issue by lanadeldel** [photopea/photopea#4425]
1,I configured the server address using the url：
<img width="778" alt="BCF90C68-7014-4FAD-A6DB-5B935FD54780" src="https://user-images.githubusercontent.com/48135307/159666056-1e93e93d-291c-457c-b051-f7dccb65bd6b.png">
2,I use a script to save the file：
<img width="694" alt="CA371CA8-F39B-4891-8E71-A59186989DD2" src="https://user-images.githubusercontent.com/48135307/159666287-0e99a8ec-70ce-41e2-8a74-204abf8a903d.png">
3,I have configured the following parameters：
Access-Control-Allow-Origin: *
4,this is error :
<img width="1279" alt="0D724E6A-0B9B-460E-9833-1ECCE0CDA620" src="https://user-images.githubusercontent.com/48135307/159666709-549bd4df-3ceb-47a5-a998-86b9976fa384.png">
any ideas? thank you!

**Comment by photopea** [comment]
So there is no error when loading files, but an error when saving files?

When Saving, Photopea also makes a HTTP request to your server. The response of your server should also return the CORS headers.

**Comment by lanadeldel** [comment]
there is no error when loading files, but an error when saving files? yess
thx i will check it

**Comment by lanadeldel** [comment]
hii,If I use script to open a file, can I also use  script to save it?
<img width="751" alt="29B794DE-4D0C-4281-A4B5-354AE1FC0424" src="https://user-images.githubusercontent.com/48135307/159875751-628b415b-791b-4f7d-8afe-8a21d3915a00.png">

**Comment by lanadeldel** [comment]
it worked ,thank you very much

**Comment by photopea** [comment]
ok :)
