### ISSUE TITLE
cannot Save File as .psd AT ALL - Cannot save to drive even when logged in...

### ISSUE THREAD

**Issue by JessMTermini** [photopea/photopea#4426]
Hum so I tried logging in both via google and github because the both menu options under file > Save as PSD and file > Save are grayed out. (See screenshots). In the screenshot you can see I am logged in as the Account button is active, ie. color change to yellow.

When I go to Account page it shows me logged in but that's it, nothing else. As a side note, would be great if we could save our files (push our files) to a github repository...

It is worth it to note this file started from a template. I am wondering if that is the reason it is not letting me save my changes? Is there a permission or limitation on how we can save derivative works? That's the only thing I can think of at this time as to why this is. If it's not a permissions issue, then I don't know what it is and something is very wrong. Sad because I saw on the templates page we could add our own templates and I was just playing around to see what Photopea could do and created a pretty decent work that might have made a good template. Other than that is just scary if I can't save to .psd, because, well you know, that's really only the most important file extension to be able to keep the original and be able to continue to make changes...etc etc..ok well, please do let me know. I am an a chromebook, but that probably shouldn't matter either...(?)

ok, well ty. Hope I can get this to work. I so need a working copy of Photopea ie (poor mans photoshop!!)...or rich mans...$2000.00/month? Damnnnnnnnnn. As cool as it is, still love it and love you, but still, damnnnnnn, lol...but no, all kidding aside, you deserve it. WE NEED PHOTOPEA!! Bleep Adobe!! ok, lemme go now and shut up. Thank you!!!!!!!!!

UPDATE: Just returning, on a more serious note. I am about to completely lose the whole work. As I cannot close Photopea without saving otherwise everything will be lost forever. Afraid to shut my compter. About to lose everything...:( oops, oh well....I will wait a little longer. lol, I have no idea what to do...Photopea has confiscated, no HIJACKED my entire document, the entire file... ^^

![Screenshot 2022-03-23 08 57 18](https://user-images.githubusercontent.com/100001251/159706873-c7346e4e-84ff-429d-96a3-753fe15ec90d.png)

**Comment by photopea** [comment]
First of all, logging into Photopea does not give you any extra features. It does not change anything.

Photopea templates were made by our fans. We do not allow people to download a PSD of a template, as someone might "steal" these PSD files and resell them, etc.

You can only export the template as a JPG / PNG file, etc.

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by JessMTermini** [comment]
Sorry but, what's the point of starting with a template if you cannot continue to build on it. I would assume if someone is willing to share it with the world -as a template - that implies you're being given the rights to adapt and to create derivative works. I can understand not allowing redistribution but as a designer also, this seems very misleading. Also as a designer I would never want to waste hours of my precious time on any design I could not come back later to continue where I left off, which cannot be done without the source files, nor would I waste any time creating an original work, (yes this can absolutely be done!!) without owning the source files as my proof of ownership. I will not go on ranting, as this is my personal opinions and I respect that you have yours as well and if you'd like to know why I feel so strongly about this, please feel free to reach out as I'd love to continue to elaborate. From a users perspective, it is considered common industry practice to expect a template to be able to make derivative works while also maintaining some sort of copyright and continued ability to adapt and modify as long as necessary (not time limited to one interaction- which this becomes without the ability to save progress in any meaningful way). I guess my most important takeaway here is it was very misleading and there was nothing mentioning the rights, as the rights seemed implied (from expected industry wide use standards), and in this way I feel wasted a WHOLE lot of my time that could have been saved as I literally had to go through this entire process and contact you on here in order to find an answer, which many people do not know how to even use a site like github or want to even goo through the page long lengthy process just to answer a simple question such as this...so I am sure many people could get upset at this or just quietly leave losing all their work. I lost that entire work by the way. I would suggest renaming the designs from templates to something like test examples, or trials, and at the very least making it quite clear any adaptations will not be able to be saved as source. I worked hard on it and was proud of it, regardless if I started from a template. I left my computer open with the app live for days so as not to loose my work tying up precious screen and processing resources all for it to be lost in the end anyway. Very bad experience for me all the way around. Maybe something to think about. Idk, just some friendly food for thought. Thanks for responding at least anyways. Much appreciated for that, cause atleast I know now. Anyways, take care. Thank you, and Best of luck to you...Godbless.

**Comment by photopea** [comment]
The idea of a template is, that you change something and export a JPG / PNG. 

Many people offered their templates with a condition, that nobody can download them as a PSD.
