### ISSUE TITLE
Text is not editable

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4427]
i don't know, but the text layer that i have on a particular project breaks when i edit it.
[Screen recording 2022-03-23 22.18.59.zip](https://github.com/photopea/photopea/files/8337645/Screen.recording.2022-03-23.22.18.59.zip)

**Comment by avagp** [comment]
Here is the PSD:
https://www.photopea.com/#iyGctu9-B

**Comment by avagp** [comment]
https://user-images.githubusercontent.com/11801254/159823356-e4c04b25-55d3-40b1-98a7-b426f628cdab.mp4

**Comment by avagp** [comment]
I solved it.

For some reason, it had a huge stroke on the font. I don't know why it changed, and why it didn't keep the original size.

It shouldn't happen

**Comment by photopea** [comment]
There was a bug in Photopea. If you set the Text Outline Width to 3px, and you free-transformed your text, the Width still showed the old value.
I fixed it. Now, you should see, that your text has a stroke Width of 81 pixels.
