### ISSUE TITLE
Export PDF - It doesn't export all the canvas

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4428]
![image](https://user-images.githubusercontent.com/11801254/159829430-03be764b-2fc4-4a2d-8db7-ac866726449f.png)

**Comment by photopea** [comment]
How can I reproduce it? Could you send me a PSD version of your file?

**Comment by avagp** [comment]
I could not reproduce it either.

But, i was on another computer. With a vectorized image with the previous version (the one that did not merge colors), and it had problems with ram (i got the warning a lot of time when working).

In my computer does not happen :/
