### ISSUE TITLE
Layers not displaying correctly with WebGL enabled

### ISSUE THREAD

**Issue by AirGEL** [photopea/photopea#4430]
2 of my layers are not displaying correctly when WebGL is enabled

Reloading Photopea does nothing, the issue is still there

With WebGL disabled:
![image](https://user-images.githubusercontent.com/73725883/159882938-64c4ddfe-4dee-4dfd-bd36-e731f4189c60.png)

With WebGL enabled:
![image](https://user-images.githubusercontent.com/73725883/159883073-cfbdbbca-7045-463f-8a89-a38728ecb732.png)

**Comment by photopea** [comment]
That is strange. Could you share your PSD with us, or send it to support@photopea.com ?

**Comment by AirGEL** [comment]
[](https://drive.google.com/file/d/1AxGVARCJTG9R0BP9n8JdnkkalQGNn_sD/view)

It wouldnt let me upload it here, so there's a google drive link

**Comment by photopea** [comment]
It seems like your computer supports the WebGL textures of up to 16384 pixels. Some of your layers are larger than that.

Now, Photopea will check the size of each layer, and will disable the WebGL automatically. Note, that Photopea will run slower without the WebGL. You can delete the invisible parts of these layers, to use WebGL again.
