### ISSUE TITLE
Allow fuzzy selection drag like in GIMP.

### ISSUE THREAD

**Issue by jointri** [photopea/photopea#4431]
I love photopea so far, but there is one thing that I love from GIMP that should be in photopea if it isn't already in.

If you use the magic wand or any similar tool in GIMP, you can have a "draw mask" to highlight what you're going to select and move the mouse to make the selection larger or smaller as necessary.

![GIMP](https://user-images.githubusercontent.com/81046576/159916268-00480606-078a-4db9-a468-20e2e7d0557b.png)

It's godsend making selections significantly easier and more flexible in GIMP because you know exactly what is going to be selected. Can that please be implemented in photopea if it's not already in it? I couldn't find anything like it how GIMP does it.

**Comment by photopea** [comment]
What is this feature called? I gried to google "gimp draw mask", but no such thing exists.

There are masks in photopea: https://www.photopea.com/learn/masks

**Comment by jointri** [comment]
It's under the documentation for fuzzy selection, literally called "draw mask". Probably wasn't the best name to pick for GIMP, but it's a helper to make precise selection as long as the mouse button isn't released.
https://docs.gimp.org/2.10/en/gimp-tool-fuzzy-select.html
If you scroll down to the bottom, you'll see another image example of the "draw mask" feature.

**Comment by photopea** [comment]
I am afraid we dont have such feature. But we have a Quick Mask: https://www.photopea.com/learn/selections

**Comment by jointri** [comment]
The "draw mask" functionality from GIMP is so convenient that it's a bit of a pain to re-adjust to photopea not having it. If such a functionality was implemented to where I can select an area, hold down the mouse button to move the mouse to adjust what I want to select, and release when satisfied, I would certainly be using photopea a lot more. Could it be implemented into photopea please?

**Comment by jointri** [comment]
If I could enhance what I mean, here is a gif example of what GIMP is capable of.
![Animation](https://user-images.githubusercontent.com/81046576/159952248-1f2e73d8-dfec-4f05-b92b-de0fed9bb1c4.gif)
If you could right click it and select "open image in new tab" to get a fullscreen view, it could perhaps help explain what I mean by "draw mask".

**Comment by jointri** [comment]
One additional note of worth, GIMP can fuzzy select with and without the "draw mask" meaning that it can extend the selection as regular ants or if the checkbox is selected add a magenta color to make it more obvious what is being selected. Just thought you should know.

**Comment by jointri** [comment]
@photopea 
I believe I have discovered what I am saying should be in photopea. I posted a gif above of GIMP fuzzy selection abilities, having the "draw mask" is optional, but one thing that would be highly useful for photopea is ability to drag the fuzzy selection like in GIMP, either showing the ants as you drag it or the magenta coloring. Have I cleared everything up?

**Comment by photopea** [comment]
I get it now. When you click with the Magic Wand in GIMP, you can drag the mouse to Left / Right to change the Threshold (you can see the value chaning on the left side), before you release the mouse. I think it is a neat feature.

@nothingshiru @michalszz  What do you think about it guys? Would you like to have it in Photopea? But it would be hard to discover, as most people use Photopea in a "Photoshop way".

In Photopea, it is called "Tolerance", it is located at the top, and you should set it before using the Magic Wand.

**Comment by MichalSZZ** [comment]
It is interesting. But it will be hard to show it as goog as in GIMP without this colored selection.

**Comment by jointri** [comment]
@photopea @MichalSZZ 
I would say adding in the coloring could be an optional thing. GIMP has baked in ability to change the threshold by holding down the mouse and dragging to change the threshold. The coloring is just a helper to let you see better what is being selected. It's still highly noticeable without it. In other words: What should be added without having to add in an option is if you hold down the mouse button, you can change the threshold/tolerance level for huge convenience of making specific selections. Here is another gif example of what happens when you disable the draw mask.

![AnimationNew](https://user-images.githubusercontent.com/81046576/160026766-913511bc-ec5b-4a6e-96ce-ac42f44097fe.gif)

**Comment by nothingshiru** [comment]
It looks cool!

**Comment by jointri** [comment]
> It looks cool!

Glad you like it. I think adding in small things from GIMP will go a long way to attract an even wider audience than merely just photoshop users. Dragging the mouse to move the tolerance and optionally having a mask coloring the selected areas will be awesome to have in photopea.

**Comment by photopea** [comment]
I have implemented it. To visualize a selection with a color, press Q to switch between a regular and a quick mask mode.

**Comment by nothingshiru** [comment]
Can you make the tolerance value change in real time while dragging, and then restore the original value when the mouse button is released. Note the left side of jointri's GIF, you will see what I mean. It allows us to control more precisely.

**Comment by photopea** [comment]
Ok done.

**Comment by jointri** [comment]
@photopea You're awesome man. Thanks!
