### ISSUE TITLE
Holes where SVG overlaps

### ISSUE THREAD

**Issue by NickyMorg** [photopea/photopea#4432]
Whenever I paste an SVG, the areas where that SVG overlaps go missing showing the transparent background.

Original SVG:
![photopea](https://user-images.githubusercontent.com/49461498/159990742-7a6dc3f9-e4e1-4407-b7f8-d4870d43d1e9.svg)

SVG after importing:
![Photopea _ Online Photo Editor - Personal - Microsoft​ Edge 3_24_2022 3_01_33 PM](https://user-images.githubusercontent.com/49461498/159991279-bd3263f3-714c-49a2-97f4-2c914805d99a.png)

**Comment by photopea** [comment]
Your SVG contains a path, which intersects itself. In that case, Photopea and Photoshop always fill such path with the "evenodd" ruling. There is no solution for it at the moment :( just draw paths which do not intersect itself (but they can intersect other paths).
