### ISSUE TITLE
Make phases of filters translatable

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4433]
Could you please make the phases of filters in Filter menu and Filter Gallary translatable? Except HSB/HSL...

**Comment by nothingshiru** [comment]
and the label texts of the sliders in Filter Gallary

**Comment by photopea** [comment]
I think there are too many of them. There are like 100 phrases. We dont even translate filters in the filter gallery.

**Comment by nothingshiru** [comment]
It would be really helpful to have them translated. Especially when we are learning the Photoshop tutorials in native languages. With translated name, we will be able to find the filters used in the Photoshop tutorials quickly in Photoepa. Please

**Comment by photopea** [comment]
I made the names of filters in the filter gallery translatable.

**Comment by nothingshiru** [comment]
Thanks a lot!

Could you make the names of the filters in filter menu translatable too? There are 15 of them.

Normal Map
Kaleidoscope
ZigZag
Reduce Noise
Flame
Fibers
Solarize
Trace Contour
Wind
Color to Alpha
Particles
Fourier
Fourier Transform
Inverse Fourier Transform
