### ISSUE TITLE
Add canvas background color into the area that can display image

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4435]
Example
![New Project](https://user-images.githubusercontent.com/79258245/160129638-532d7b4d-09b5-428d-bd2a-5881891ab402.jpg)

there are such a area in Save for Web, Reduce Color, Vectorize Bitmap, Color Range, Magic Cut, Filter Gallary...

**Comment by photopea** [comment]
Done! BTW. do you think I should remove the padding at the top and left side of the image area, so that there is more space for the image itself? This can be useful especially on small screens such as phones.

**Comment by nothingshiru** [comment]
> remove the padding at the top and left side of the image area, so that there is more space for the image itself

Sounds good.

**Comment by photopea** [comment]
ok done :)

**Comment by nothingshiru** [comment]
I notice the result part in Vectorize Bitmap does not have the background.

**Comment by photopea** [comment]
fixed.
