### ISSUE TITLE
Strange behavior when opening images via pasting

### ISSUE THREAD

**Issue by KiraResari** [photopea/photopea#4436]
What I do often is take screenshots using the PrintScreen key, and then pasting them into Photopea when I don't have a file open (aka, when the start page with "New Project", "Open from computer" and "PSD Templates" is shown). This usually works fine the first time around, and I get an image containing the entire screen capture.

However, as I go through my process of cropping the screen capture to the desired area, editing it, saving it, and finally closing it before repeating the process, things start getting weird:

Sometimes, when I paste the new screen capture, instead of the original correct behavior, I just get a window the size of the last edited image that I saved and closed, where that image exists as a second layer in the background behind the pasted layer of the screen capture (only a portion of which is visible). This happens to me regularly, but I haven't been able to reproduce it yet.

Sometimes it happens instead that the screen capture is displayed in full, but there's a second layer behind it containing the old screen capture. This one is relatively easy to reproduce:

1. Make a screenshot using PrintScr
2. Paste it into Photopea on the start page via Ctrl+V
3. Edit that image in any way
4. Close the image without saving it
5. Switch to any different window so Photopea is not the active window anymore (this step is important; without it, the bug won't occur)
6.  Make another screenshot using PrintScr
7. Paste it into Photopea on the start page via Ctrl+V

=> Now you have an image that contains both the old edited image and the new screen capture as layers

**Comment by photopea** [comment]
Are you using Firefox? As Firefox does not allow access to a clipboard, there is a weird behaviour in it.

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by KiraResari** [comment]
Yes, I'm using Firefox. Can I give you some details so you can re-open this?
