### ISSUE TITLE
Unify floating bubble window style

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4437]
I notice the dialog style changed. It looks great. 
How about using the same style on floating bubble window? Replace border with shadow and unify the radius values...

Currently they are like this...
![image](https://user-images.githubusercontent.com/79258245/160158914-551f92ca-92d2-420d-8b6c-9b8edd9ff865.png)
![image](https://user-images.githubusercontent.com/79258245/160159107-2e4f3837-8463-4dcc-8794-77d9a449a58f.png)
![image](https://user-images.githubusercontent.com/79258245/160159150-8de616d5-188d-4ab5-b34e-7eac44c1146a.png)

**Comment by nothingshiru** [comment]
I notice the gap between toolbar and tools window is not as same as the one between toolbar and virtual key window. Please fix it.

**Comment by photopea** [comment]
What about the context menu? When you press File , Edit ... should we make round corners?

**Comment by nothingshiru** [comment]
I thinked about the context menu, but I'm not very sure if it would be good.

**Comment by photopea** [comment]
I have unified it a bit. The tool menus stay the same, because they are context menus.

**Comment by nothingshiru** [comment]
Fine.

**Comment by nothingshiru** [comment]
> What about the context menu? When you press File , Edit ... should we make round corners?

I see the context menu on Windows 11 has round corners. It looks not bad. I think the context menu Photopea can has round corners too.

**Comment by nothingshiru** [comment]
> What about the context menu? When you press File , Edit ... should we make round corners?

I see the context menu on Windows 11 has round corners. It looks not bad. I think the context menu Photopea can has round corners too.

**Comment by photopea** [comment]
It would look like this
![image](https://user-images.githubusercontent.com/15955558/160636812-0190c420-83aa-4b3c-aa1c-632adfc9db62.png)

**Comment by nothingshiru** [comment]
Looks nice.

**Comment by nothingshiru** [comment]
Do you decide to change it?

**Comment by photopea** [comment]
I think I will keep the sharp corners on context menus, while others are round.
