### ISSUE TITLE
Make properties bar snap back to left only when switching tools

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4438]
Now it snap back when I open/close panel, switch document... It doesn't make sense that a behavior which doesn't affect the amount of options in properties bar make properties bar snap back.

**Comment by photopea** [comment]
What do you mean? What is a properties bar? How does it snap back to the left? There is a toolbar on the left.

**Comment by nothingshiru** [comment]
Sorry. I mean the top bar. related issue #3559

**Comment by photopea** [comment]
ok done :)

**Comment by nothingshiru** [comment]
Great!
