### ISSUE TITLE
Saving to PSD and exporting PNG features don't work on iPhone 12 (Google Chrome)

### ISSUE THREAD

**Issue by ProgrammingLife** [photopea/photopea#4440]
Tried to save to PSD and export to PNG my work but both items do nothing when I click it.
iPhone 12, Google Chrome is up to date.

Guys, do you face any troubles when saving your work on iPhone?

**Comment by photopea** [comment]
Could you try Safari? All iOS browsers are just skins on top of Safari.

**Comment by photopea** [comment]
I have to close it because of lack of details.
