### ISSUE TITLE
Exported image from Photopea becomes more saturated than the image in the site

### ISSUE THREAD

**Issue by str4ng3-zz** [photopea/photopea#4441]
![image](https://user-images.githubusercontent.com/102424556/160245565-a6eecf27-4657-4509-9b1d-bf54cd219fba.png)

The left part of the image is the file before the export. The right side is the downloaded picture after export. I observed that when I switch the 'Convert to sRGB' button back-to-back, it becomes more saturated each time.

**Comment by str4ng3-zz** [comment]
> The left part of the image is the file before the export. The right side is the downloaded picture after export. I observed that when I switch the 'Convert to sRGB' button back-to-back, it becomes more saturated each time.

![image](https://user-images.githubusercontent.com/102424556/160245832-9579870d-a381-4877-bebe-9ab08ae5b2e8.png)

**Comment by photopea** [comment]
Could you share your file with us? It does not happen with my file.

**Comment by photopea** [comment]
I found the problem, it should be fixed now.
