### ISSUE TITLE
Font completely disappears

### ISSUE THREAD

**Issue by tpolomsky** [photopea/photopea#4442]
Hi, I have been using photopea for about a year, and this issue keeps happening on and off. I've put up with it for a long time, but I just can not stand it anymore.

I load in a PSD, click on a font layer, double click on the actual text, and the text disappears. I try to load in a font, and when I start typing, nothing appears. On my screen, it shows I am typing characters, but the characters aren't appearing. It is as if I am just hitting the space bar a bunch of times.

Please help with this. I love photopea, but this is certainly frustrating.

**Comment by photopea** [comment]
Hi, please, try this first: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
