### ISSUE TITLE
The background color of tab on which cursor hover should not be as same as the background of actived tab

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4443]
![image](https://user-images.githubusercontent.com/79258245/160259112-82cfca55-e39e-43a3-bb47-6af95a8ae0a8.png)
The mouse pointer is not captured in the screenshot but this makes it clearer what I mean. It is hard to tell if a tab is actived or hovered by mouse pointer.

**Comment by nothingshiru** [comment]
The background color of the tab hovered by mouse pointer being a little bit darker than actived tab could be better.

**Comment by photopea** [comment]
I think it is fine as it is.
