### ISSUE TITLE
Optimize the save dialog on the small screen

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4445]
Currently the save dialog on moble phone is like this. The space for image preview is too small to use.
![www photopea com_ (1)](https://user-images.githubusercontent.com/79258245/160313381-4647a060-5504-4ebb-9b46-b94592c55961.jpg)

It would be much better to be like this
![image (1)](https://user-images.githubusercontent.com/79258245/160312419-73dd793e-804c-494c-a1b2-3f6e8a72072d.jpg)

My idea is that when <del>height of viewport is larger than width of viewport, </del>
* Make the size be 100% of viewport.
* Put options part at top, preview part at bottom. The max-height of options part is 50% of the dialog height. If there are a lot of options, make options part be scrollable, but the save button is always fixed at the bottom of the options part(not scrolled).

**Comment by photopea** [comment]
I have implemented it, I think it looks amazing :)

BTW. do you think on large screens, the Save For Web should be ful-screen? I kept it as a small window, because I think small windows look cool, and you still see the program behind the window (so it is a "new window" and not a "new screen").

**Comment by nothingshiru** [comment]
It does not seem to be necessary on large screen.

**Comment by nothingshiru** [comment]
Here are a few problems.

* When the virtual keyboard comes out, the style change. I see this happen when the viewport height is 394px or less. I think we should get rid of the effects from viewport height.
![Screenshot_20220329_063021_com microsoft emmx](https://user-images.githubusercontent.com/79258245/160498943-6498d3b7-2a47-46ea-80c3-fa049334a020.jpg)

* The position of options part would be push up when the virtual keyboard comes out. It would be better to put the options part at top so it's position won't change when inputing. 

* The style change only when viewport width is 599px or less. But the width of my tablet is 600dp... Can you set it to 699px? That's the value the panel bar become one column.

**Comment by photopea** [comment]
I have changed the "limit" to 660 pxiels width.

I disagree with you. When the keyboard appears, I think it is useful to see both the image and the options. We can not hide the image and show only the options.

Also, I think the options should be at the bottom. E.g. when you are dragging the Quality slider, you should not cover the image with your finger.
