### ISSUE TITLE
Is it possible to make .psd files open with Photopea by default?

### ISSUE THREAD

**Issue by QuestionQuest117** [photopea/photopea#4446]
It would be quite useful if I could open all .psd files with Photopea by default. It's annoying that I have to open Photopea and hunt for the .psd file to work with it or click-drag the file into Photopea and that I can't just double-click the file and have it open in Photopea.

I assume this is a limitation on Windows' end, but it would be nice to confirm. Are there any workarounds? I tried hunting for where Photopea as an app is downloaded, but it seems whatever is downloaded when you do that is very minimal and is still largely just a web browser (would also be nice if such apps were more like actual apps and could be used offline...). I tried having any .psd file be opened from https://www.photopea.com, but that didn't seem to work either as that change didn't save and it didn't open Photopea. Is there anything else I can try?

**Comment by nothingshiru** [comment]
#1901

**Comment by photopea** [comment]
It is already implemented in Photopea. We just need to wait until web browers support it.

It should be available in Chrome 102 and other Chromium based browsers, so probably around this summer https://bugs.chromium.org/p/chromium/issues/detail?id=829689#c142

**Comment by photopea** [comment]
The standard Chrome release already supports File Handling API, so you can double-click files in your computer to open them in Photopea.com .

https://twitter.com/photopeacom/status/1531325944501354497
