### ISSUE TITLE
Allow premium users to disable analytics

### ISSUE THREAD

**Issue by hialvaro** [photopea/photopea#4448]
It would be a lovely feature for premium users to be able to completely disable all the analytics and tracking from the site. Paying for privacy is a motivation for me and I think it is for many users. It can be an option only available for premium users :) This feature would look good on the list!

![](https://rimgo.pussthecat.org/anvMi6l.png)

**Comment by photopea** [comment]
Ads are disabled in Premium, and Google Analytics is the only "foreign code" that remains.

What exactly is wrong with Google Analytics? They are very popular, and used on many websites. If a large part of our users pays for Premium, we would have no idea how many people are using Photopea.

Or are you uncomfortable about the fact, that we know the number of users of Photopea in a day? 

In general, it depends on you, whether there is a number 344 872, or a number 344 873 as a number of users of a certain day. Do you consider the difference between these numbers to be your "private data"?

I guess it is similar to whether a show owner has a right to count the number of visitors of their shop in a day.

**Comment by jointri** [comment]
@photopea I can empathize with what @hialvaro is saying. I believe the issue at hand is that it's google. Google is not known for being ethical with their data collection and naturally one will want to use something else. There do exist alternatives to google analytics, but I cannot vouch the quality of them.

**Comment by photopea** [comment]
I don't think Google knows much about you, when you use Photopea. Google Analytics record that your IP address visited Photopea.com at a certain time, the screen resolution of that device, etc. I don't think Google shares that data with anyone else other than me.

**Comment by photopea** [comment]
@tomayac Hey, you are from Google, do you think Photopea should stop using Google Analytics?

I looked at Matomo and others, and in my opinion, if they store data on their servers, they must follow the laws in a country where they are located. So I don't think it is easier for US government to get data from Google, than from Matomo.

Personally, I feel like the creators of GA alternatives write these articles, with one simple formula: "rich guys" = "bad guys".

What about GitHub? I think GitHub knows more about Photopea users than Google knows about Photopea users. GitHub is owned by Microsoft.
