### ISSUE TITLE
Trouble uploading a 2nd image

### ISSUE THREAD

**Issue by chrt222** [photopea/photopea#445]
Hello,

I am having an issue with uploading images.
The first image goes up just fine, then when I try to add another one (drag and dropping from document folder to the space in the browser. A loading image pops up and just stays like that as seen in the screenshot link below.

https://gyazo.com/e77336b621e728d33cb5e92bd8f13d3e

I have tried clearing the cache and cookies of the browser and restarting computer as well as tried using Microsoft Edge browser and Chrome browser.

Thank you for any help with this.

**Comment by photopea** [comment]
Hi, could you send us your second image to support@photopea.com , so we can see what is going on?

**Comment by chrt222** [comment]
Just sent it, however it seems any type of image I use whether png or jpg or different size, it is the same result

**Comment by photopea** [comment]
Hi, I am very sorry. This bug is related to the yesterdays update of Photopea. I just fixed it and it should work now.  

Thank you very much for reporting it! Many people probably had the same problem, but you are the only one who actually helped to solve it. Thanks!

**Comment by chrt222** [comment]
I can confirm it is working now. Thank you for the help and quick fix!
