### ISSUE TITLE
Importing SVG file breaks text...

### ISSUE THREAD

**Issue by CodeWithJaz** [photopea/photopea#4450]
Firstly, thanks for putting out such a great product.

Now, when I export an SVG file and reimport it, it breaks down words into letters, and they all overlap - left-aligned. But if I export it as a PSD file, it maintains sanity. Should not happen
![image](https://user-images.githubusercontent.com/102587467/160583358-fe4b0016-f4c7-4111-87e2-b5f1adc91433.png)

**Comment by photopea** [comment]
I have to close it because of lack of details :(
