### ISSUE TITLE
Gradient align with layer? 

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4452]
I don't know, but when i select a fill gradient to align with the layer, should it keep the same orientation even if i rotate the layer?

https://user-images.githubusercontent.com/11801254/160711632-aef160bc-521d-4539-85d3-ff53a27b64ed.mp4

**Comment by MichalSZZ** [comment]
It works good. It doesn't have anything to do with angle. When you uncheck "align with layer" - you will have gradients fill to size of your artboard - but you will see only that part what is in that shape.

**Comment by avagp** [comment]
So, how do I set a gradient with a certain angle relative ti the layer ,
and then be able to move it around without losing the angle i set?

**Comment by MichalSZZ** [comment]
You are working with vectors only?
My workaround for this is creating a smart object. But I don't know that it will be good for you.

When something is in the smart object. Changing angle of that layer doesn't change gradient angle or effects angle

**Comment by MichalSZZ** [comment]
Maybe @photopea have some oder ideas how to do that. On shapes I am doing that manually

**Comment by photopea** [comment]
This would be pretty hard to make :/  That is probably why it does not work this way in Photoshop.

Also, I think there might be people who want the gradient not to change when they use the Free Transform.

**Comment by avagp** [comment]
It is too difficult to have the angle of the gradient be always the same distance apart from the angle of the layer?🤔

**Comment by avagp** [comment]
Like if i set the gradient to 15
And the Layer is 0

If i rotate the layer to 90, the gradient should be 105

**Comment by photopea** [comment]
In Photoshop and Photopea, the gradient is computed by the bounding box of a layer. And When you rotate the layer, the bounding box is a completely different rectangle. So you need to change the Angle, the Scale, and the Offset, to make the gradient look the same.

**Comment by avagp** [comment]
Oh, i see.

Than it is ok.  :D

Thanks for the explanation!
