### ISSUE TITLE
Remove shadows from window title

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4453]
In lighter themes, it makes the text unclear.
![image](https://user-images.githubusercontent.com/79258245/160724838-80d64e4c-0b99-4dcb-a8e9-4522f1e4cb49.png)
![image](https://user-images.githubusercontent.com/79258245/160724853-2e391c65-fa8b-41e3-868d-33edeb515279.png)

And in dark themes, it is hard to be noticed. I think it is meaningless.

**Comment by photopea** [comment]
done.
