### ISSUE TITLE
Can vector shapes be treated as actual vectors rather than rasterized?

### ISSUE THREAD

**Issue by jointri** [photopea/photopea#4455]
This is a feature request for something when working with vector graphics such as an Adobe Illustrator file. The vectors get rasterized and then treated as any regular drawn bitmap image. What would be great to have is not to rasterize the vector images, but manipulate it like any other vector can be in other programs. I have a few images to demonstrate what I mean.
First is the zoomed out of a sample vector using the path tools-
![photopea](https://user-images.githubusercontent.com/81046576/160816198-b746aa94-d3c1-4609-8d3f-053a75914c14.png)

Now here it is zoomed in, notice how it was turned into a rasterized image rather than have it be like a vector image, this also happens if you import an inkscape or AI file.
![zoomedin](https://user-images.githubusercontent.com/81046576/160816306-da8d622b-8b1b-4ece-899f-07f8ca6a9697.png)

Here is an example image of what I would suggest should happen with vector images. Instead they should be manipulated the same way they would be in inkscape or Adobe Illustrator.
![inkscape](https://user-images.githubusercontent.com/81046576/160816502-2624bd93-78dc-4d1d-8ab7-bf2476e987ef.jpg)

Please and thank you for consideration.

**Comment by photopea** [comment]
It is impossible to have certain features, e.g. Layer Styles (e.g. Shadows, Bevel and Emboss ...), and smooth vector shapes, at the same time.

That is why in Photoshop, if you zoom in, you will see huge pixels of a vector shape. While in Adobe Illustrator, there are no Layer Styles.

Maybe we could add a switch to "Vector View", which would work as you describe, but layer styles would disappear. Or we can make a separate program, which would be a vector editor (smooth shapes at any zoom), but no layer styles.

**Comment by jointri** [comment]
I do like your separate program idea as a vector editor where it would default to AI file rather than psd. We would be able to double click on vector shapes to manipulate them like in my third picture, yes?

**Comment by jointri** [comment]
@photopea 
What do you think of going forward with that idea to have vector art done in a separate program. It would make sense because photoshop is meant for raster images and illustrator is meant for vector images. Plus you could get an even larger pool of people looking to abandon both photoshop and illustrator.

**Comment by jointri** [comment]
Another thing I want to point out, is that raster editors like photoshop or photopea just aren't suitable for editing vector images. They rasterize it and I can't freely manipulate mathematical points like I can in a vector editor. It severely limits what I can do in photopea/photoshop with a vector image compared to using an actual vector image editor. This isn't just about having the edges look perfectly smooth, but treating them as true vector images rather than just a rasterized image with limited manipulation.

**Comment by jointri** [comment]
Heck, if you were to introduce a separate subscription for vector image editing, I would pay for both photopea and whatever you would call the vector image editor. No questions asked.

**Comment by photopea** [comment]
Photopea is a full vector editor. It can open AI, PDF and SVG files. It can export vector SVG and PDF files. Only the preview inside Photopea is pixelated.

**Comment by jointri** [comment]
Is it possible with photopea to be able to double click on any point in an existing path to create a new path? Is it possible with photopea to fully manipulate a vector like in inkscape or illustrator?

**Comment by jointri** [comment]
Also, @photopea at the very minimal, paths and vectors should not be pixelated, instead smooth as silk.

**Comment by jointri** [comment]
Before I close this, can you consider not pixelate vectors and paths? Have them look like it was done in inkscape or illustrator?

**Comment by jointri** [comment]
@photopea 
The reason why I ask to not pixelate vectors and paths is because you have this SVG here:
![acid](https://user-images.githubusercontent.com/81046576/160844579-ad927d78-de45-4220-919a-b99bc812efe1.svg)
It looks like this in photopea:
![Screenshot 2022-03-30 at 09-21-49 Photopea Online Photo Editor](https://user-images.githubusercontent.com/81046576/160844601-5dfb2ee8-33b7-4c76-b895-8ecae88426dd.png)
It would be a huge benefit to see vectors and vector images not be pixelated or rasterized.

**Comment by photopea** [comment]
Can you press Image - Image Size, and resample the image with a higher DPI? 

As I said, it would require a completely different painting mechanism, which would break other features of Photopea.

**Comment by jointri** [comment]
Thanks anyways for all the help. I'll try to adjust to photopea as a vector editor. Keep up the good work :)
