### ISSUE TITLE
pencil alpha works like bruch

### ISSUE THREAD

**Issue by rafaelcastrocouto** [photopea/photopea#4456]
pencil alpha channel should not add up just like the colors. this makes drawing pixel art shadows almost impossible since if you click twice on the same shadow pixel it will change the opacity.

**Comment by photopea** [comment]
How else should it work? Do you know any program which works as you describe, so that I can take a look?

**Comment by rafaelcastrocouto** [comment]
tge alpha should work the same way as the other rgb channels.
just set the opcity value, no blend mode

check any decent pixelart editor

**Comment by photopea** [comment]
If you paint with black, with 50% opacity, it should always make the pixel darker. Are you saying it should not change the pixel?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
