### ISSUE TITLE
impossible to achieve some values on opacity range 

### ISSUE THREAD

**Issue by rafaelcastrocouto** [photopea/photopea#4457]
the opacity range only accepts int numbers from 0 to 100 making impossible to set an alpha value of 44 hex (0-255) on the color value with the pencil/brush tool

**Comment by photopea** [comment]
Yes, our opacity is integers now (0% - 100%). We do not support decimal numbers. Your value 0x44 is 68/255, which can not be even expressed as a decimal number (it is 0.26666666666666666.....).

So we do not support fractions of different denominators, there are only the 100 values.

**Comment by rafaelcastrocouto** [comment]
you can keep the 100 range, 
all u have to do is to allow floats and give it a 100/255 step value
