### ISSUE TITLE
ArtLayer filter methods not being applied to correct layer

### ISSUE THREAD

**Issue by setiawanj** [photopea/photopea#4459]
I posted a related issue on Reddit that has since been resolved. I've since found that when you use one of these ArtLayer filter/adjustment methods, it applies it to the selected layer, not the layer whose method you're calling.

For example, if you create a new document, fill it with some content (white background for example, doesn't really matter), make some selection on the layer, and then run this script:

```
app.activeDocument.activeLayer.duplicate();
var shadowAL = app.activeDocument.artLayers.getByName(app.activeDocument.activeLayer.name);
app.activeDocument.activeLayer.duplicate();
shadowAL.adjustBrightnessContrast(-100, 0);
```

You should end up with three layers. Even though you call `adjustBrightnessContrast` on `shadowAL` (which is the middle layer), it applies it to the top/selected layer.

Perhaps I'm missing something, or is there some issue?

**Comment by photopea** [comment]
Hey, it should be fixed now.

Note, that duplicate() does not change the activeLayer. It makes a copy, but the old layer is still selected.
