### ISSUE TITLE
Mouse cursor colors

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#446]
1. When image has gray color (7f7f7f) Rectangle Select or Crop Tool cursor is invisible when on top of this color
2. Also when in Firefox browser Brush and Quick Selection cursor is almost invisible (you can still see it but not very much) when on dark gray (background color around actual image in default theme) or on black color

**Comment by photopea** [comment]
1. We use the standard CSS cursor property for the Crop Tool. So it happens for any website with such cursor and the background. Should we report it to the browser developers?

2. This should work the same in Firefox and Chrome. Can you show us a screenshot with the difference between browsers?

**Comment by hxim** [comment]
1. Maybe or maybe you could use custom cursor as for other tools?
2. screenshots: https://imgur.com/Phx445n

**Comment by photopea** [comment]
Hi, our cursors are rendered incorrectly in both Chrome and Firefox. I submitted following bugs:

- https://bugzilla.mozilla.org/show_bug.cgi?id=1451873
- https://bugs.chromium.org/p/chromium/issues/detail?id=829517
