### ISSUE TITLE
Resize Selection on Image Resize

### ISSUE THREAD

**Issue by PAEz** [photopea/photopea#4460]
In Photoshop if you resize the image the selection also gets resized to match.
I use to (havent used PS in YEARS) do this to make clipart from cartoons.....
Resize the image to a multiple of 2 or 4 or 8,etc using bilinear or I think I also had bicubic (cant remember)
Use the magic wand
Then resize back using the same sample method
Then clear the selection (or did I clear and then resize?...been so long)
...I thought of this as giving me like a subpixel way of using the magic wand and it gave damn nice outlines.
In PP this is more of a pain because you have to transform the selection after the resize.
I guess now if I wanted to do such I might use the refine edges (only just learnt about that, very cool feature), but still I think the selection should resize.

**Comment by photopea** [comment]
It is quite hard for us resize the selection during Image Resize. Now, we only resize layers, channels and paths.

I have a solution for you: press "Q" to turn your selection into a Quck Mask (a special channel), resize, and press Q again to turn the quick mask back into a selection.
