### ISSUE TITLE
Image cannot fit the area by shortcut Ctrl + 0 if it is rotated with Rotate View

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4464]
To reproduce

1. Rotate image with Rotate View tool. 
2. Press <kbd>Ctrl</kbd>+<kbd>0</kbd> or click View > Fit The Area.
![New Project (1)](https://user-images.githubusercontent.com/79258245/161401381-d42465ac-7d6f-4028-a097-a646682bd6cf.jpg)

**Comment by photopea** [comment]
it is fixed now :)
