### ISSUE TITLE
CAN NOT ADD TEXT

### ISSUE THREAD

**Issue by ebnguyen13** [photopea/photopea#4466]
Can not add more text or see any text/word when open file

**Comment by photopea** [comment]
try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by ebnguyen13** [comment]
I'm already read it, and it's not and didn't solve my case, you can see in the image below
![image](https://user-images.githubusercontent.com/102934667/161678319-e6c246cd-e565-426c-9b69-d5959a8e3a2f.png)
It happens even when I use app. I've been using Photopea for more than 2 years and just had this problem since about Feb this year.

**Comment by photopea** [comment]
It seems like your web browser can not load fonts from our server. Can you access this font and save it to your computer? https://www.photopea.com/rsrc/fonts/fs/DejaVuSans.otf 

Also, is your browser updated?

**Comment by ebnguyen13** [comment]
I saved the font and installed it. However, nothing changed. I have accessed with both ME as shown below. And yes, I'm using the latest version of Chrome
![image](https://user-images.githubusercontent.com/102934667/161714194-ca1843aa-e12d-4b48-ad2a-a43a47af16fd.png)

**Comment by photopea** [comment]
When the problem happens, can you right-click Photopea, choose "Inspect Element", switch to "Console", and show me a screenshot of what you see in the Console?

**Comment by ebnguyen13** [comment]
Here you are
![image](https://user-images.githubusercontent.com/102934667/161879543-20904ced-7405-453a-b60a-3ba15734fb46.png)

**Comment by photopea** [comment]
There are so many things Photopea fails to load in your cases. E.g. the file "basic.zip" with brushes, gradients, etc. Moreover, I even see that the ad on the right side of Photopea is not displayed.

There is some "entity", which stands between your browser and the internet, sees everything you do online, and is allowed to block certain resources. You said it is not a browser extension. Did you install anything into your computer, which is tracking / censoring your web traffic? It could be called "anti-virus", "firewall", "privacy-protector", "web-monitor" etc

**Comment by photopea** [comment]
I have to close it because of lack of details :(
