### ISSUE TITLE
Histogram should have background color

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4469]
Without background color, it's hard to tell if there are colors touched 0(or 255) or not.
![image](https://user-images.githubusercontent.com/79258245/161620644-35e137e7-74ad-49d2-8966-6d8b114e0990.png)

Also, the there need to be a top margin, because the histogram will touch the dropdown menu when it has background color.
![image](https://user-images.githubusercontent.com/79258245/161621554-245e61a8-20f2-4735-bdf5-b1532cb1e89a.png)

**Comment by photopea** [comment]
fixed! BTW. the vertical axis is a quantity of a specific color in the image. It is not limited by 0-255.

**Comment by nothingshiru** [comment]
I know it and I meant the horizon axis.
