### ISSUE TITLE
Opening huge files

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#447]
Photopea must be able to open huge files (i.e. files, that don't fit into RAM).

This requires 
- special internal representation of graphics
- special rendering and preview mechanism
- special work with the memory (HDD / RAM / GPU memory)

This will fix following problems:
- opening large PSDs (1 GB or more)
- opening large Sketch files (now, PP may crash for big Sketch files)
- WebGL - related crashes (users have to disalbe WebGL manually now)

We don't know how to do it yet. This issue shows, that it is in our todo list.

**Comment by ioma8** [comment]
Skusil bych asi cestu Filesystem API:

https://www.html5rocks.com/en/tutorials/file/filesystem/

Např si dej do prohlizeca:

window.requestFileSystem  = window.requestFileSystem || window.webkitRequestFileSystem;
window.requestFileSystem(window.TEMPORARY, 5*1024*1024 /*5MB*/, function (e) {console.error(e)}, function (e) {console.error(e)});

To ti na filesystemu alokuje prostor o velikosti 5MB apod, co jsem pochopil nemelo by to byt omezene.

Co se tyce podpory, je to experimentalni featura, kterou nedoporucují pouzivat, ale podle tabulky to vsechny moderni prohlizece podporuji. Zkusil bych nad tim zauvazovat.

https://developer.mozilla.org/en-US/docs/Web/API/FileSystem

Dej vedet.

**Comment by legopitstop** [comment]
This also happens when resizing an image. usually results in a crash or mad lag.

**Comment by photopea** [comment]
@legopitstop Could you tell us more? We work with 100 MPx images in Photopea (10 000 x 10 000 pixels) and it never crashes or lags.

**Comment by legopitstop** [comment]
Well, to start off I create Minecraft mods. which use .png Images, I was creating a bed texture 16px in-game but the actual image is 64px I wanted to make the same texture to be 102,4px (HD) so after doing some calculations I figured that I needed a 4096 x 4096px image, here are the image size settings I used if it helps: Width:4096 Height:4096 DPI:96:000 Resample: True Interpolation: Nearest Neighbor. I am running photopea on windows 10 home, Hp notebook, Chrome Version 80.0.3987.132 (Official Build) (64-bit) I Hope all this is somewhat helpful.

**Comment by photopea** [comment]
So I made a new document in Photopea, 1024x1024 pixels, and pressed Image - Image Size, entered 4096x4096 pixels, Nearest neighbour. It was resized correctly.

Is that what you did? Could you describe your steps how to make Photopea crash? Also, try them multiple times to make sure it works.

Otherwise, Photopea, just like any other website, will crash, if you dont have enough free RAM.

**Comment by legopitstop** [comment]
most likely I don't have enough free RAM, This also happens on my Chromebook but those things don't handle very well.

**Comment by photopea** [comment]
How much RAM do you have? Can you close some browser tabs?

**Comment by legopitstop** [comment]
I have 4.00Gb (3.45 Usable) RAM. I will try again.

**Comment by legopitstop** [comment]
Ok, I figured it out it is an image 64x64px with 16 layers then resize the background layer to 4096px so it resizes all 16 layers.

**Comment by legopitstop** [comment]
I also closed all programs, except discord and chrome, and closed all tabs except photopea and github.

**Comment by photopea** [comment]
Each layer 4096x4096 pixels requires 67 MB of RAM.  With WebGL, each layer is stored twice (a copy on the GPU).

Disable WebGL (More - Use WebGL) so that Photopea uses 2x less RAM (but it will be slower without WebGL).

**Comment by legopitstop** [comment]
disabling WebGL helped and successfully resized each of the layers. caused a little lag but not as much as before. Mabe make it automatically turn off WebGL if you are opening/resizing a large image or add the WebGL checkbox to the image size with an info icon telling what it does? overall photopea is still the best!

**Comment by photopea** [comment]
Many people have 8 GB of RAM or more. Then, working with 16 layers 4096x4096 with WebGL is absolutely no problem. Sadly, we can not check how much RAM the user has.

Try working with smaller resolution (2048x2048) or less layers (e.g. 10).

**Comment by legopitstop** [comment]
I mostly wanted to use the layer so I can resize a mass amount of textures then export each layer to save on a little time. but it managed to resize and export each layer. just a little bit of hiccups along the way.

**Comment by photopea** [comment]
I will close it now, as it seems people have enough RAM nowadys.
