### ISSUE TITLE
Some phrases are not swicthed when language is switched

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4470]
To reproduce

1. Open Photopea and set the language to 简体中文.
2. Refresh the web.
3. Set the language to English.

![image](https://user-images.githubusercontent.com/79258245/161629116-2ee75aaf-b641-43ea-9812-cc6954be0acb.png)
You'll find some translatable phrases are not swicthed correctly. 
For example,
1. the Name in save dialog,
2. the Format in save psd/psb dialog,
3. the Resample in image size dialog,
4. the Preserve Transparency in Fill dialog (the same phrase in Apply Image is swichted correctly)...

They maintain as the language that is set when you just opened Photopea.

**Comment by photopea** [comment]
fixed! :)
