### ISSUE TITLE
Noise Filter is being removed during export!!

### ISSUE THREAD

**Issue by mjmeeks** [photopea/photopea#4471]
Hi, when i export my photo. doesnt matter the format. When I had gaussian noise too it, for some reason now when i export its randomly removing the noise when i had exactly how i liked it. But then i tried it with just a random photo off of the internet with the same layers and everything and it adds. so im confused on why suddenly it's removing the noise from this specific picture. Please help

**Comment by photopea** [comment]
If you set the export quality to low, or you export as GIF, the noise might disappear. Or if you zoom out the photo, you can not see the noise.

Can you describe what should I do to see the noise disappear in Photopea?

**Comment by mjmeeks** [comment]
so i try to export it as a PNG but i also tried JPG and it removes it from this specific picture. i keep the quality at 100% and when i zoom i cant see the noise. its confusing because i woke up this morning to see if it would do it with a random photo online, with same layers everything the exact same. and even when i zoom out i still see the noise i added

if i flatten the image so that all the layers are one it looks the exact same as i want it. but when i export it the noise is removed. im going to try really quick and see if maybe for some reason on the zoom out its not there but will be when i export it

**Comment by mjmeeks** [comment]
yeah i exported it and the exported file the noise is removed just like when i zoom out in the export as menu. but then when i look at it in the program, it looks how it should be

**Comment by photopea** [comment]
Could you show me the image, to which you can not add the noise, so that i can try to add the noise myself?

**Comment by mjmeeks** [comment]
well i add a noise to a layer. but yeah let me see how i can do that. do i need to upload it somewhere and send the link, email or?

**Comment by photopea** [comment]
You can send it to support@photopea.com

**Comment by mjmeeks** [comment]
okay its sent

**Comment by photopea** [comment]
I just tried it and it seems to work well. Note, that your file contains two images, which Photopea inserts into two layers. Maybe you applied the noise to an invisible layer.

Also, do you really know how to save files in Photopea? I.e. using File - Export As - JPG?
![image](https://user-images.githubusercontent.com/15955558/161642451-d0144d06-8374-4659-9673-4ab8cc768d1c.jpg)

**Comment by mjmeeks** [comment]
no its not working! that layer 1 i dont use. i make a dupilcate of the main layer then the dupilcate i add blur, then noise, then i add a mask and me around me so the the noise and blur is around me. then i go file, export as, then png and savc. let me take a screenshot i still have the window open, its a glitch

**Comment by mjmeeks** [comment]
okay i took one. see look, im not making this up

https://imgur.com/DW5hOuo

**Comment by photopea** [comment]
That is what I said as the first thing: "if you zoom out the photo, you can not see the noise."

You zoomed out, that is why you do not see the noise. Zoom in, e.g. to 100%, to see the noise.

![mL9tz5f](https://user-images.githubusercontent.com/15955558/161645789-10d93e8a-89e8-4927-b3bd-1b5546a58660.jpeg)

**Comment by mjmeeks** [comment]
and i told its not there when i export either, theres no noise. its clear. and you clearly see the noise in the other picture. so why? how can i get that when i export the noise is there like in the other one

when i do it with other pictures online it does it, thats how i created this aesthetic. why with the camera photos i took is not showing when i export? its not showing and i told you that. i told when i zoomed i couldnt see it. but when i export its not there

**Comment by mjmeeks** [comment]
i guess a better question is. how do i make so that it exports and looks like the one in the program, theyre the same size practically but you can see the noise in the one in the program. you can see it around the lights, you cant see it in the exported AFTER its exported

**Comment by mjmeeks** [comment]
here is a screenshot of the EXACT picture, AFTER export. there is no noise there, it removed it from how i created it to be.

https://imgur.com/mVU5Teq

**Comment by mjmeeks** [comment]
okay i think i figured it out, i tried it with another picture and your right, now its lessening the noise when i zoom out like with the camera photos and when i export the noise it isnt like in the one i created. so for some reason, the noise goes down after exporting from what it was. so ill just have to work around that i guess so that export has more noise than it does when i export it

**Comment by mjmeeks** [comment]
well whatever, disappointing but for whatever  reason it changed where it lessens the noise from how it was. ill just have to figure out another way for it to be more clear that the noise is there now in the photos...

**Comment by photopea** [comment]
I will try to explain it.

Let's say you have an image of 10x10 pixels. You add a noise to it. But you zoom out to 10%, so it is just 1x1 pixel on your screen. Of course, you can not see any noise in a 1x1 pixel image (one single pixel on a screen).

When you zoom out to 10% in Photopea, it selects a random pixel in the 10x10 pixel area and shows it on a screen (this method preserves noise). But the Save for Web, or any existing image viewer, it computes the average color of the 10x10 pixel area and uses it as the color of a pixel (this method removes noise).

I hope it is more clear now :)

**Comment by photopea** [comment]
Add noise to your photo using any other program, and you will see, that when you view it zoomed-out on your computer, you can not see any noise. This is not related to Photopea at all.

**Comment by mjmeeks** [comment]
it doesnt make sense because the pictute i was working on in the side by side is also zoomed out. but i can see the noise, when i made pictures with Photopea last month, i could see the noise zoomed out after export. example:

https://ibb.co/V3zHqCX

so i dont want to annoy you. but HOW do i make it so the noise looks like it does in the also zoomed out photo, pre export like in side by side screenshot above? because the photo on the workshop is not zoomed in

**Comment by photopea** [comment]
Your photo is 3500 x 5250 pixels (18 million pixels). But you want it to be only 350 x 525 pixels on your screen (183 000 pixels). There are billions of ways, how to select 183 000 pixels out of 18 million pixels).

I dont know what else to say. If you think another program can do something Photopea can not, send me a JPG from that program, and a JPG from Photopea, so that I can see the difference.

**Comment by mjmeeks** [comment]
so youre saying if it was smaller, the noise would show how i expect it? so that picture in the photopea screenshot i sent you, thats not the export preview, is literally smaller than the export preview for some reason?

otherwise yeah, it doesnt make sense. in the photopea screenshot i showed you with the export example zoomed out, next to the photo i was originally working on. theres a clear difference in the noise thats visable, even though its the same photo. i know you can see that but when its exported that noise appears less until you zoom waaaay in. where the other is zoomed out and you can see the noise stronger. but theyre the same picture i thought at the same size

**Comment by mjmeeks** [comment]
okay makes sense! thank you and sorry for any trouble ive given you
