### ISSUE TITLE
Text moving out of bounds when trying to export as SVG

### ISSUE THREAD

**Issue by christinameyne** [photopea/photopea#4474]
I have a text logo I'm trying to save as SVG, but one line of the text moves out of bounds to the left. It looks perfect when saved as a JPG or PNG.

**Comment by christinameyne** [comment]
Strange, I do have the font on my computer. I didn't have Vectorize Text checked, but when I do, it just changes it to a default font, which won't work for me. I created the logo in Photoshop, but since you can't export as an SVG there, I uploaded the file to Photopea to export from there.

It's a really strange thing it's doing, it just moves the main text (but not the secondary text) about 500 pixels to the left, and out of the image.

**Comment by photopea** [comment]
That is still very strange. Could you put your PSD into a ZIP archive and share it here? Attach it to your comment.

**Comment by christinameyne** [comment]
Sure
[Logo Final PhotoPea.zip](https://github.com/photopea/photopea/files/8430303/Logo.Final.PhotoPea.zip)
!

**Comment by photopea** [comment]
So your document uses "Noe Display - Bold" and "Optima" fonts, none of them is in Photopea by default. The PSD only contains rasterized (pixelized) text. You will be able to save pixels (PNG, JPG ...), but not edit text, or convert it to vectors.

Load the necessary fonts into Photopea using File - Open. Then, you can type with them, or vectorize text. Websites do not see fonts inside your computer, so you have to load them manually.

**Comment by christinameyne** [comment]
I understand that it doesn't have the text, but I didn't rasterize either one in Photoshop. The only strange part was that it was moving out of bounds every time I tried to save it. That's all.

**Comment by photopea** [comment]
When you export to SVG, the text is not exported as pixels, but as  SVG text. It is rendered differently, because the SVG viewer does not have a necessary font.

**Comment by christinameyne** [comment]
Got it: it's not strange at all, it's expected to do wacky things. (I do know what SVG is, that's why I was using your program--which is great by the way.) I'm good now, as I said, I just had to move it out of bounds the other direction. Now I know if I ever need to export an SVG again, I'll just do that.
