### ISSUE TITLE
My new plugin: SimilarLetter

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4475]
You select letter with Magic Wand tool and enter which letter it is, then click button and it will offer 20 most similar letters in Photopea fonts (internally it creates 16x16 pixel image from your selection and compares to each of 16x16 rendered images of that letter for all photopea fonts)
Can help you:
1.) Identify font from rasterized image (if font from Photopea was used) or 
2.) Find similar looking font included in Photopea to some unknown or known font in your raster image/logo/screenshot etc.
3.) You can also sketch shape of letter with brush and find some font with has simlar looking letter

Note: You can combine results for multiple letters by CTRL+click on "Find Similar Letter" button.
![image](https://user-images.githubusercontent.com/6370548/161792987-f78be268-4f02-47ef-88ae-726093db5d3f.png)

Edit:
Here is the link:
https://www.photopea.com/#%7B%22environment%22:%7B%22plugins%22:%5B%7B%22name%22:%22SimilarLetter%22,%22url%22:%22https://hxim.github.io/SimilarLetterPlugin/simlet.html%22,%22width%22:300,%22height%22:436,%22icon%22:%22https://hxim.github.io/SimilarLetterPlugin/icon.png%22%7D%5D%7D%7D

**Comment by photopea** [comment]
I have made a Plugin gallery in Window - Plugins. The interface is very similar to Free PSD Templates. Please, add your plugins there.

**Comment by hxim** [comment]
@photopea Hello, can you help me? I don't understand how to enter URL of plugin and/or its icon into this form. Should I somehow use File button and upload some file? What should be in it? I tried to add this testing "debug plugin" but it is not working :(
![obrazek](https://user-images.githubusercontent.com/6370548/163441439-65d6d3cd-ad43-4d4e-829a-b4011b43c608.png)

**Comment by photopea** [comment]
That is right, the plugin is the JSON. The "Thumbnail URL" can be anything, e.g. a screenshot of your plugin, or some interesting results, a GIF ... etc.

**Comment by photopea** [comment]
Here are your other plugins. You can use the trick with "===" to make a grayscale icon, see https://www.photopea.com/api/plugins
```
{
	"name"  :"Emoji",
	"url"   :"https://hxim.github.io/TwemojiPlugin/twemoji3.html",
	"icon"  :"https://hxim.github.io/TwemojiPlugin/icon.svg"
},
{
	"name"  :"QR Code Maker",
	"url"   :"https://hxim.github.io/TwemojiPlugin/qrcode/qrcode.html",
	"icon"  :"https://hxim.github.io/TwemojiPlugin/qrcode/icon.png"
},
{
	"name"  : "Chart Maker",
	"url"   : "https://hxim.github.io/TwemojiPlugin/gcharts/gcharts.html",
	"icon"  : "https://hxim.github.io/TwemojiPlugin/gcharts/icon.svg"
}
```

**Comment by photopea** [comment]
@hxim I can see your plugin for Jpeg XL and AVIF. Photopea can actually open AVIF.

Could you make a plugin for opening HEIC files from Apple devices?

**Comment by xan2622** [comment]
Thank you @hxim for making this plugin. It works like a charm. This is a very convenient plugin!

![192037](https://user-images.githubusercontent.com/1732773/177198114-c2937014-e33d-42c6-8961-ca876bdf2106.png)

**Comment by photopea** [comment]
@hxim I see your plugin adds a lot of items into a history. Could you do steps backward, before adding the letter?

Also, it is an amazing plugin!

**Comment by hxim** [comment]
@photopea 

> @hxim I can see your plugin for Jpeg XL and AVIF. Photopea can actually open AVIF.
> 
> Could you make a plugin for opening HEIC files from Apple devices?

Unfortunately I don't know how to read HEIC files in javascript.


> @hxim I see your plugin adds a lot of items into a history. Could you do steps backward, before adding the letter?
> 
> Also, it is an amazing plugin!

OK, I added 
```
var oldHistoryState = app.activeDocument.activeHistoryState;
...
app.activeDocument.activeHistoryState = oldHistoryState;
```
into main script.
Also I could use `app.activeDocument.suspendHistory()` in script for adding and resizing text layer
to provide a single history state for the entire script but it seems it is not working/implemented in photopea.

**Comment by xan2622** [comment]
> Could you make a plugin for opening HEIC files from Apple devices?

Maybe this library could help?
https://github.com/alexcorvi/heic2any
https://alexcorvi.github.io/heic2any/

**Comment by hxim** [comment]
> > Could you make a plugin for opening HEIC files from Apple devices?
> 
> Maybe this library could help? https://github.com/alexcorvi/heic2any https://alexcorvi.github.io/heic2any/

I just added opening HEIC files with this library. Please check if it works correctly.
