### ISSUE TITLE
Always zoom the canvas with a point on the canvas as the reference point

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4477]
I found that in Photoshop the canvas never goes outside the workspace while zooming. Maybe Photopea can works in the same way?

# What I found
With zoom tool, canvas is always zooming with the point closest to the position you click on as the reference point. 
With the shortcut <kbd>Ctrl</kbd>+<kbd>+/-</kbd>, canvas is always zooming with the position closest to the centre of workspace as the reference point.

For example, in this image the white area is canvas and gray area is workspace.
With zoom tool, If you click on the A(or C ) point and drag, canvas would zoom as you click on B(or D ) point and drag. 
With the shortcut <kbd>Ctrl</kbd>+<kbd>+/-</kbd>, canvas would zoom as you click on F point which is closest to the E point the centre of workspace.

![新建项目](https://user-images.githubusercontent.com/79258245/161897576-4e4ac5e3-a5e0-48a0-9ee5-95ea23337e64.jpg)
The shortcut <kbd>Alt</kbd>+<kbd>Wheel</kbd> should work as same as zoom tool. 
Other ways for zooming should work as same as the shortcut <kbd>Ctrl</kbd>+<kbd>+/-</kbd>.

Because the reference point is always on canvas, the canvas never goes outside the workspace.

**Comment by nothingshiru** [comment]
I may not have explained it clearly, so you may need to try it in photoshop.

**Comment by photopea** [comment]
You are absolutely right, such behaviour is much better, I made it work that way :)

Also, there was a restriction in the Zoom tool, such that if the zoomed image was smaller than the workspace, it was always centered. I removed this restriction.

**Comment by nothingshiru** [comment]
> if the zoomed image was smaller than the workspace, it was always centered

This feature can be reserved for Fit The Area, as Fit The Area is not only used to zoom canvas but also used to review the canvas entirely.

**Comment by photopea** [comment]
Sorry, it is fixed now.
