### ISSUE TITLE
Setting tolerance on Magic Wand tool turns cursor into an auto-Undo P.I.T.A.

### ISSUE THREAD

**Issue by chrisasbo** [photopea/photopea#4478]
This only seems to happen when I select the Magic Wand selection tool.  If I click on the Tolerance box, type in a new number and hit enter or click in the working area (outside the canvas), afterwards any movement (without clicking) of the cursor across the image is equivalent to hitting Ctrl-Z for every single pixel I move.  I can Shift-Ctrl-Z my way back to where I was, so these are behaving like genuine history backsteps, but at the same time the Tolerance number will reduce itself until it reaches 0, where it will stop.  Mouse-over'ing the opposite direction does not have the opposite effect on the history, but seems to on the tolerance.
If I drag the cursor around from the right sidebar, up and across the menus and down onto the tools bar, no such effect is produced, and I can switch tools which deactivates the bug.  However, once the bug has occurred, the magic wand tool is effectively out of commission, usually for the rest of my session, as the bug becomes active again while the wand is selected at all.

**Comment by photopea** [comment]
I am not able to reproduce shuch bug on my laptop or on my phone. Could you write steps like 1) Open www.Photopea.com, 2) .... and make sure these steps always lead to such bug? Also, are you using a touchscreen?

**Comment by chrisasbo** [comment]
I suddenly can't recreate it.  I'm using a different desktop than the desktop (all win 10) that was giving me problems.  There's a chance it's a bug related to the mouse or mouse settings in windows, but I'd kind of expect it to present in far more situations and this has always been connected to tolerance adjustment of the magic wand.

I actually made a screencap vid demonstrating it, but even scaled down and turned into a GIF it was too large to post so I didn't bother with it, lol.  If I have the issue arise again, I'll find a way to post a demo of it.

**Comment by DeathByCh0c0** [comment]
Seconded, same issue here.

**Comment by photopea** [comment]
@DeathByCh0c0 could you describe what should I do to see such beahviour?
