### ISSUE TITLE
Disabling antialiasing with the pen tool

### ISSUE THREAD

**Issue by CaramelUrsa** [photopea/photopea#4479]
hello, would it be at all possible for you to add an option to disable AA on the pen tool? similar to how you added it for the typing tool in issue #2129? photopea has all the options i need for pixel art and sprite editing except for this. thanks.

**Comment by photopea** [comment]
Do you mean rendering vector shapes, like a circle, witout anti-aliasing? Are you creating pixel art? It seems wrong to me to use vector-editing tools for pixel art.

**Comment by photopea** [comment]
Have you tried to use selections, e.g. Ellipse selection, and fill them? You can disable the anti-aliasing in the top menu.

**Comment by CaramelUrsa** [comment]
I'm mostly interested in using the pen tool to make curves without having to figure out how I want to place the pixels to achieve a good looking curve. usually for the outline on character. I hope the image below explains what mean well enough
![example but without a typo](https://user-images.githubusercontent.com/55702042/162048367-78386daa-19df-4a06-b944-9d0ac67e3b42.png)

**Comment by photopea** [comment]
Do you know a difference between the Brush and the Pencil tool? See https://www.photopea.com/learn/bt-basic

Draw a path in a Path mode - e.g. as a Work Path: https://www.photopea.com/learn/vector-graphics . Then, click "Stroke Path" at the bottom of the Paths panel. It will draw with a current tool (a Pencil) alnog the path. I hope that should do what you need :)
