### ISSUE TITLE
Suggestion for usability - Let user move over the design with mouse right click or mouse middle click

### ISSUE THREAD

**Issue by carlos-mg89** [photopea/photopea#448]
I find it a bit tedious to have to click always on the hand tool to let me move around the design. Other design tools let you do that quite easily, and it would be very good to do so.

Alternatively, giving to each tool or at least the most used ones, a keyboard binding would be awesome. that way, I shouldn't have to move the mouse to the toolbar to change between zoom in/out, hand, selection.

**Comment by photopea** [comment]
Hi Carlos, You can quickly switch to the Hand tool if you press Spacebar, and once you release it, you will go back to the previous tool. You can also scroll vertically with a mouse wheel, or horizontally with a wheel + Ctrl. You can also activate the Hand tool by pressing H. 

You can find more here: https://www.photopea.com/learn/navigation  . Do you think it is enough?

**Comment by carlos-mg89** [comment]
Thanks for the quick reply @photopea , I was using your recommendations yesterday and they worked quite well :) I really believe that you should provide along with the title that tells you the name of the tool, in the left toolbar, which key is bound to it. I found other keys associated with other tools. Like Z for the Zoom.

By the way, scroll vertically or horizontally works tremendously slow in this app (not in my browser though). It is like reaaally slow.

The tips for zooming in and out with the ALT key is fantastic!

Thanks and keep working like that! The tools is really great. It has some issues but I'm sure you keep working hard. I'll try to describe anything I find in order for you to know.

**Comment by photopea** [comment]
Now, when you keep a mouse on top of a tool button, it will show you the tool name and the keyboard shortcut. Thanks for the suggestion!

What do you man by "scroll works slow"? Is it moving by small steps, or Photopea gest stuck while moving?

**Comment by carlos-mg89** [comment]
Wow! It was as fast as a lightning :D I already see the keyboard shorcuts!

Yeah, I meant it scrolls by small steps. If you go to a normal website, and you scroll down, typically each each step of the mouse wheel gets me the page 3-4 lines up or down. In photopea is like a few pixels only. I have a sketch file, with a height of 2000px, and is like 5-10 pixels per step of the weel. Maybe it happens only on my browser :s 

I have Firefox 57 on Ubuntu 17.10, I could try with a different browser and/or OS too.

**Comment by photopea** [comment]
It is very strange. What is the resolution of your monitor?

Can you change the step size in mouse settings in Ubuntu?

**Comment by carlos-mg89** [comment]
The resolution of my monitor is 1920x1080.

I guess I can change the step size, but if works perfectly fine in other applications and in Mozilla Firefox (my default browser). If I change it, the rest of my applications won't work well.

**Comment by DanMan** [comment]
@photopea Can we please get the mouse panning, too? Like in Gimp or Inkscape, where you can pan the canvas around with the middle mouse button?

**Comment by photopea** [comment]
@DanMan  What do you mean by that? I have a mouse wheel in the middle of my mouse. I can roll it and Photopea pans Up / Down. I can also push it to the sides, which makes Photopea pan to the Left / Right.

You can also press the Spacebar (quick switch to a Hand tool) and pan with the left mouse button pressed. Then, you can release the Spacebar, and you will get back a previous tool.

**Comment by DanMan** [comment]
@photopea If you press and hold down the middle mouse button anywhere on the canvas, it grabs it so you can pan it around. My mouse wheel cannot be pushed to the sides.

I find the spacebar solution (I know, PS does it) sub-optimal, especially when working with text blocks. I keep adding spaces to texts instead of panning the canvas around.
