### ISSUE TITLE
Photopea switched text to tiny letters (Don't suggest zoom)

### ISSUE THREAD

**Issue by bratakus** [photopea/photopea#4481]
Suddenly Photopea started making text tiny. If I open a file (JPEG) from yesterday I can type normally. But any new JPEG image I open text is automatically tiny. I read some suggestions in Reddit, like checking zoom, but obviously that's not the solution. Photopea is basically useless to me now.

**Comment by photopea** [comment]
So you open a JPG with text inside it, and it is too small? What if you open your JPG in another program, like some image viewer?

**Comment by bratakus** [comment]
Any JPEG opened, if I try to write text on it, appears tiny. JPEGS already created in Photopea with text written on them, I can write text normal size. I opened a few old creations I made in Photopea, to check. All checked out.  But any new photo (JPEG) if I try to write text on it, it's tiny.

________________________________

**Comment by bratakus** [comment]
Checked. Weird thing is I can drop an old Photopea creation into the file I'm working on & I can text in it fine. But when I click the new JPEG I'm working on, text is tiny.

Thanks for replying.
________________________________

**Comment by photopea** [comment]
I think your document is zoomed out. Can you tell me, what zoom do you have in the "small text document" and in the "big text document"? Press View - Rulers, the zoom will be in the bottom left corner.

**Comment by photopea** [comment]
Let's say you write 1-inch text on a small box, and 1-inch text on a huge box. You want to take a photo of each box with your phone. 

After you take a photo of the first box, you need to "move away" from the second box, so that it fits into the photo. As a result, both boxes will be equally large on your photos, but the text on the first photo will be larger than the text on the second photo.

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by bratakus** [comment]
Thanks for replying. You identified the problem. If I go back to  Photopea, I'll wrestle to fix it.
________________________________
