### ISSUE TITLE
Using file handler api on Edge does not work, but in chrome it does

### ISSUE THREAD

**Issue by Ciberbago** [photopea/photopea#4485]
Hello, first of all... Great app! I love it, the only thing it would make it perfect would be allowing me to open psd files directly from my desktop.

I'm on windows 11, and I use Edge as my browser. And I tried the steps listed in this comment to be able to open files with the PWA:
https://github.com/photopea/photopea/issues/1901#issuecomment-1010608610

I did them, but it didn't work. I tried in 3 different machines and didn't work, until I tested using chrome instead of Edge... and it worked. I don't know if edge handles permissions differently but what happens is: I open the file, and the PWA app opens but without the file. And in chrome it just works. It would be a shame having to install chrome just to use photopea in a more comfortable way. Is there something I'm missing in how to resolve this?

Thank you in advance.

**Comment by photopea** [comment]
I don't recommend doing such complicated tricks as described here: https://github.com/photopea/photopea/issues/1901#issuecomment-1010608610

In a couple of months, it will be supported by default (in Chrome, probably in other browsers, too), and will work for everyone without any extra steps.

There are "Storages" on the left side of the introduction screen. Can you try "This Device" and give Photopea access to a specific folder of your computer? Then, you can open files with a double-click and save them back with Ctrl+S, without any extra dialogues in between.
