### ISSUE TITLE
Add canvas size on the right side of zoom level

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4486]
When using Photoepa on low performance devices I often check the image size before I start editing the image. If the size is large, I will reduce it. It would be nice if I could see the image size immediately after opening the image. 
![New Project](https://user-images.githubusercontent.com/79258245/162330354-255dce01-a07f-4eb9-ba45-08fbdfc2356c.png)

**Comment by photopea** [comment]
Should it be displayed only with rulers, just like the Zoom value?

I think most people usually know how large their image is (more or less). This extra field would cover the image and it might bother some people.

**Comment by nothingshiru** [comment]
Maybe there could be a option in Preferences for display/hide it?

**Comment by photopea** [comment]
I have added the document size in pixels to the corner.

**Comment by nothingshiru** [comment]
Thanks
