### ISSUE TITLE
boxes around tools 

### ISSUE THREAD

**Issue by kirkew** [photopea/photopea#4488]
all of a sudden I have a little box around the paint tools and the smudge tools when I try to use them on a photo.  Makes it hard to see what I'm doing on a project.  What happened.  No more accuracy!

**Comment by photopea** [comment]
Can you show us a screenshot of what you see?

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by kirkew** [comment]
This is the “boxes” around several of the tools in your online photopea program including the clone tool, the paint tools, and the blur/sharpen/smudge tools. Can you help me. This just started happening about two months ago out of nowhere. I’ve been happy using your program and I’ve really enjoyed fixing up photos I have and doing creative stuff as well.   I am running it on my ASUS laptop and running software windows 10.  


Sent from my iPhone

> On Apr 24, 2022, at 4:59 AM, Photopea ***@***.***> wrote:
> 
> ﻿
> Closed #4488.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
>

**Comment by photopea** [comment]
I can not see any images :( Could you open the github in your browser and reply there, instead of sendinge mails to github?

**Comment by kirkew** [comment]
OK here is an example of what the tools now look like that I mentioned.   Kirke
On Mon, Apr 25, 2022 at 01:55 PM, Photopea  wrote:
 I can not see any images :( Could you open the github in your browser and reply there, instead of sendinge mails to github?

**Comment by photopea** [comment]
I still can not see any images. To what email address are you sending emails?
