### ISSUE TITLE
Feature request: Trim

### ISSUE THREAD

**Issue by pandronic** [photopea/photopea#449]
The Trim function as it is implemented in Photoshop (you can find it in Image > Trim) is very useful and sorely missing from Photopea. It's very useful for quickly cropping images with transparent or uniform background. Also it's especially useful when cropping images with very subtle colors that are very hard to distinguish (like for example gradients and drop shadows).

Edit: In other tools like Sumopaint - the feature is known as Auto-crop.

**Comment by dw9694** [comment]
Yes, this functionality, would not be superfluous.

**Comment by photopea** [comment]
The Crop Tool already has some related settings: cropping by the current layer or by the selection size.

What if we add this as an extra button to the Crop Tool?

**Comment by dw9694** [comment]
I will be grateful.

**Comment by pandronic** [comment]
It would be OK. I can't wait for this feature :D

**Comment by photopea** [comment]
Hi, so I did the following: when you open an image (e.g. PNG) with "transparent edges", they are not parts of the layer content area.

I.e. you can use the Crop tool - Crop by current layer (or total content - all layers) to trim the image by alpha. Or do you need to trim a specific backgorund color (e.g. by top left pixel) ?

**Comment by pandronic** [comment]
It's not bad, but it would be great if you could also trim by color. Here's how Photoshop implements this feature:

![trim](https://user-images.githubusercontent.com/315108/38665883-3160dd90-3e46-11e8-9276-01a12938cc24.png)

**Comment by photopea** [comment]
Hi, this was added into the Image - Trim. There are no options, it trims by Top Left pixel color, all four sides are on.

**Comment by pandronic** [comment]
I missed that.
