### ISSUE TITLE
PDF Export - When exporting pattern filled shapes, shape stroke is also rasterized

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#4491]
![image](https://user-images.githubusercontent.com/11801254/162549022-c613b4d5-f82e-40bb-981d-c1fd76f19ec9.png)
![image](https://user-images.githubusercontent.com/11801254/162549082-ca66736f-12b5-4110-851a-335bbaada376.png)

I don't know if this is intenteded, but at least is weird

**Comment by photopea** [comment]
As we can not export pattern fills, the only thing we can do is to rasterize the whole layer :(  Maybe you can put the stroke into a separate layer on top of it, what do you think?

**Comment by avagp** [comment]
Yes. I will do that.

But it won't be inside the shape.

For my particular case is not important, because the shape will.be cut.

But I bet is not the same for other projects
