### ISSUE TITLE
Feature request: Color sampler tool

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4492]
In Photoshop, this tool can place eyedroppers on image. When a adjustment layer is activated, or a adjustment dialog or filter dialog is open, we can see the original values of the sampled pixels and the changed values at the same time in Information panel. 
![image](https://user-images.githubusercontent.com/79258245/162554114-c3841bc4-bf7c-424d-bf6a-020ab74e892a.png)
![image](https://user-images.githubusercontent.com/79258245/162554155-3f673fc8-b653-49c5-9268-315abfc975ae.png)

I really wanted this tool when I was experimenting with the effects of the filters in Photoepa.

**Comment by photopea** [comment]
To sum up how it works: 
- you define several points in the document, each has a X,Y coordinate
- if you select any adjustment layer in the Layers panel, the info panel shows the RGB color at each point before and after applying the selected adjustment layer (even if there is a completely black layer on top of it).
- if you select anything else (non-adjustment layer, multiple adjustment layers ...) the Info panel shows a final RGB color at each point.

It would be quite hard to implement into our model :(

**Comment by nothingshiru** [comment]
Is it possible to be implemented if there are only final values?

**Comment by photopea** [comment]
We have implemented the color sampler tool.
