### ISSUE TITLE
Memory leak in OpenSUSE Tumbleweed, KDE Plasma, and Firefox 98

### ISSUE THREAD

**Issue by jackson2k2** [photopea/photopea#4495]
Specific version: 98.0.2 20220322144853. 6 gigabytes of swap

After having three files open in Photopea of slightly intensive image work, leaving the computer on a blank screensaver for over 2 hours will result in a 6GB+ memory leak, causing the entire computer to take 10-20 minutes to open up, 10 minutes to draw the Firefox window, and 20 minutes to close the Photopea tab itself.

**Comment by photopea** [comment]
What does it mean exactly? What do you call a memory leak and why?

A website might ask for a certain amount of RAM. It is up to a browser to give it to a website, or not. 

Every pixel in Photopea needs 4 Bytes of RAM. So if you have 10 billion pixels in your document, it will need 40 GB of RAM, etc. Do you think Photopea asked for more RAM than it should? Could you describe what should I do to see such problem?

**Comment by jackson2k2** [comment]
Asking for more RAM than it should even without any single action done (i.e. even in inactivity) is a sign of a memory leak.
The images were simple 400x340, 540x640, and 640x480, with only a few basic layers (only a few of them had any layer effects).

**Comment by photopea** [comment]
When you are not doing anything in Photopea, the amount of used memory should not grow.

Are you saying it is growing when you do nothing? Did you try to run Photopea without any browser extensions? Is your browser updated?

**Comment by photopea** [comment]
I have to close it because of lack of details. But we can still discuss it if you want.
