### ISSUE TITLE
add full source code  / builds for  5 most common  cpu architecture (and operating system combo)

### ISSUE THREAD

**Issue by tigercoding56** [photopea/photopea#4496]
"Since Photopea is not fully open-source, this repository serves as a place for bug reports, feature requests, and general discussion" and since Photopea is not fully opensource this removes any ability of the user to build a  desktop version on  non supported cpu architectures (like ARMHF arm64 pentinum4 PowerPC ) decreasing how many people can use photopea also with the source code being available people could make pull requests in order to fix bugs more efficiently  and decrease development costs   since  probably about 89 of users do not know how to compile things from source   and of those that do probably  about 70 % do not   how to change the source code to remove ads (if that is the reason the source code is not provided ) so the decrease in development costs  would get much  lower  and the profits would probably not get to low also  if you do not want copys of this program without your ads being distributed you can choose a more restrictive opensource license  (like a custom cc-by-Nd which still allows for development forks so that people can fix bugs )    this issue is there for 2 reasons one to make people more aware of opensource and  2 because a GitHub repo to report bugs instead of a simple bug report email for a program that does not provide its source code in said repo is a bit strange    and 3 so that if the source code is ever released i  can finally get a version (of offline editor ) working on my raspberry pi that is running archlinux since no one provides builds for that specific combination of hardware and operating system  if for whatever reason you decide to not release the source code an instead provide builds for  arm64 please make sure that an appimage is also provided since appimages  can run on most GNU/linux based operating systems

**Comment by photopea** [comment]
Hey, I think you should learn how to use periods and commas, instead of writing such long sentence, that is hard to read! :D

What do you mean "compile"? Photopea is written in Javascript and runs on any device with a web browser. E.g. if your microwave has a browser, it will run Photopea. Photpea should run perfectly on ARM, Pentium 4, PowerPC and other architectures, as I think there do exist web browsers for them.

**Comment by tigercoding56** [comment]
i i mean creating a executable that runs on whatever cpu architecture / hardware it is made on

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by tigercoding56** [comment]
i also was assuming the desktop version was in c (also some java projects install with a process that uses gradle which i find similar to compiling )

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------

**Comment by photopea** [comment]
Photopea aleady runs on any computer with a web browser. I do not want to give my source code to anyone.

**Comment by tigercoding56** [comment]
ok (could i ask why because that helps me understand other people )
also i should close this issue because it is resolved (as photopea runs on any device with a browser i was thinking there was a offline version )

Sent with [Mayprotoon](https://protonmail.com/) unsecure email.

------- Original Message -------

**Comment by JoCat** [comment]
If you, like me, want to have a separate desktop application, then you can use electron/Neutralinojs/webview/etc. for writing a wrapper application 🤔

**Comment by photopea** [comment]
You can press More - Install Photopea in www.Photopea.com

**Comment by JoCat** [comment]
> You can press More - Install Photopea in [www.Photopea.com](http://www.Photopea.com)

When I click on this item in the menu, nothing happens ¯\_(ツ)_/¯

**Comment by photopea** [comment]
It is available only in Chrom and Edge, Firefox and others refuse to support this feature.

**Comment by JoCat** [comment]
ok, looks like chrome/chromium based browsers don't know how to do that))
