### ISSUE TITLE
unable to save the png

### ISSUE THREAD

**Issue by BobTheBetrayer** [photopea/photopea#4498]
i cant save the file by the normal steps
File > Export As > .png

**Comment by photopea** [comment]
Hi, what about JPG or GIF? Does it happen to one document or to all documents you tried (if you tried to save more than one)? Could you also try these steps first? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
