### ISSUE TITLE
License

### ISSUE THREAD

**Issue by raphaelbastide** [photopea/photopea#45]
What is the license of Photopea? Is it F/Loss?

**Comment by Studioartcz** [comment]
Why?

**Comment by raphaelbastide** [comment]
Why am I asking this question? I guess because I am curious 😉

**Comment by photopea** [comment]
I decided to offer the tool to the people for free, but never thought too much about the licence. But it is not open-source. Photopea may have bugs and I can not guarantee anything.

Which licence would be the most appropritate? What do you think?

**Comment by raphaelbastide** [comment]
I personality use open source software only. I want to be free to use, study, modify it.
Also I guess you base your code on many open source piece of code right? Attaching an open source license to your program is a good way to give back to the community. For the choice of a licence, here is a good resource: https://tldrlegal.com/

**Comment by photopea** [comment]
I guess Photopea is something like Facebook or Google. It is web service, which is free to use, but you can not see the source code or modify it. What licence is that?

BTW. what open-source tool you use to search the web, instead of Google search?

**Comment by raphaelbastide** [comment]
I personality use open source software only, _for creation_. And I use DuckDuckGo instead of Google search, which is not open source but ethically better imo.

**Comment by photopea** [comment]
I am going to release my TTF / OTF font parser, on which I have been working for couple of months, as open source on this account. It was made for Photopea, but I think it can be useful to others.

Similarly, I would like to publish some other libraries, which were made for PP at the beginning, but are very versatile.

**Comment by RalphCorderoy** [comment]
> It is a web service, which is free to use, but you can not see the source code or modify it. What licence is that?

Note, if it uses other software then its licence may be influenced or governed by theirs, e.g. https://en.wikipedia.org/wiki/Affero_General_Public_License
It might be nice to list any libraries or software used for running Photopea on the site, as a hat-tip acknowledgement and also so others that care can see none of them affect Photopea's SaaS no-source-available status.

**Comment by photopea** [comment]
I agree that it is nice to list lbiraries, which were not made by Photopea, but I am not sure how deep should I go.

I am have a web hosting, which delivers Photopea over HTTP protocol. There is an operating system running on that computer, I think that it is some version of Linux, but I would have to ask my hosting provider about the details, what software is used there.

Also, Photopea uses many browser technologies, for example a 2d context of Canvas element. It has great features such as vector drawing (PP uses it for rasterizing vector masks and fonts). Browser technologies are a part of "Photopea experience" and saved us hundreds of hours of time. Photopea code would be twice larger, if there was no 2d context. But the libraries used for this may vary, depending on a browser.

**Comment by RalphCorderoy** [comment]
I'd ignore the OS, web server, text editors, what's in the user's browser, etc., and stick to libraries your hand-written front and back-end source pulls in. They are the things most likely to have a licence of interest.

**Comment by photopea** [comment]
I made no special server-side code for Photopea, everything runs on a clients side in a browser. Right now, PP uses only third-party libraries for decoding PNG, JPG, WEBP and GIF formats, but I am planning to replace them with my own libraries soon, because they are quite bad. The new libraries will be published at this account as an open-source, just like Typr.js.

**Comment by photopea** [comment]
That's a great idea!

**Comment by Ads20000** [comment]
Please see #1023 for my argument in favour of releasing the UI code (and any other code by Photopea that hasn't been released) :)

**Comment by photopea** [comment]
@Ads20000 I am sorry, I have no plans to release Photopea as open-source. Why don't you try to persuade Adobe to release Photoshop as open-source?

**Comment by Ads20000** [comment]
I didn't think you were planning to make money from Photopea though, so I see no reason why the sources shouldn't be open? It means that if you ever discontinue maintenance of the project someone else can pick it up etc?

**Comment by photopea** [comment]
@Ads20000 We are making money with Photopea and I am afraid, that if we released PP as open-source, we would not make that much money (because everybody would be able to use it cheaper or for free elsewhere).

**Comment by Ads20000** [comment]
@photopea Apologies, I didn't see the stuff on the Account screen
![screenshot from 2018-11-04 01-14-41](https://user-images.githubusercontent.com/3178485/47958968-324e0b80-dfcf-11e8-9875-fe0ed6d1f882.png)

Someone would, in theory, be able to host it elsewhere without ads, yes, though presumably they would have to find another way to pay for the hosting costs etc?

**Comment by photopea** [comment]
@Ads20000 I would never call the GPL licence an open-source. If people can not use the source code in any way they want, showing that code to the public does not have any benefit to anybody.

**Comment by Ads20000** [comment]
They can use it in any way that they want, except for modifying it and then releasing the modified code as closed-source.

**Comment by julianxhokaxhiu** [comment]
Or actually, even contributing if possible, which would speed up development on your side. Though there is no obligation of course, but it would have been a nice to have.

But if you do this primarly to live with it, then I get your fear. Although as already suggested by others, you may start considering Patreon and when reaching maybe your desired goal ( per month ) you may then consider doing this project totally FOSS.

**Comment by hialvaro** [comment]
Hey, I see this has been quiet for a long time. I just want to say that I would love to see Photopea going open source. First to say, Open Source doesn't mean "Free as for money" or that it will be directly stolen by other companies. This is what Open Source licenses are for.

Open sourcing a project means creating a community around it, it means getting help from a lot of nice and evoked volunteers that would help mantaining, solving bugs, resolving doubts from users, etc. While the main developers could keep working on new features.

Open sourcing a project means paying a bit more respect to the users as you, as a company, trust them to see your code. Means that the project can grow in a sane and awesome way as many Open Source projects did.

If you're afraid of someone stealing your code, or a fork getting more attention I can assure that you're safe about that. If you set a proper license that avoids someone stealing your code for commercial use, or whatever you want you are safe from that. Forks are not big problems, you already have a strong and loyal userbase so you can be sure that forks would only be small projects (mostly personal projects to try out and play with the code). 

You can inspire on projects like Gimp, Inkscape, Audacity, Nextcloud, LibreOffice, VLC... Those big projects have been in the Open Source community for years and they have been improving more and more, growint its user base, getting more volunteers, getting economically stable through sponsors and donations from users, etc. And no one has stolen the code nor any fork has got more attention.

I see that Open Sourcing a project if anything it is a great step towards a more sane code and builind an awesome community. Your work will still (and will forever) be appreciated by everyone and you will keep on leading the project if you want it like that. Let people contribute and build Photopea along with you.

I respect any decision you take as it is your project. Still I hope you will consider this and think about it. Best wishes with your awesome project, I use Photopea a lot and I have paid premium several times (donation-like).

Here are some links so you can read more about why Open Sourcing is really good:
[Why Open Source - Google](https://opensource.google/docs/why/)
[Reasons why Open Sourcing is good for your business](https://www.pcworld.com/article/209891/10_reasons_open_source_is_good_for_business.html)
[Why Open Source](https://opensource.com/life/15/12/why-open-source)

**Comment by aloisdg** [comment]
I dont use photoshop because of the license. For the same reason I wont use photopea either. Gimp/Krita will do the trick. I am still using to much close source software (e.g. GitHub) to start using one more. Good work though. Looks good.

**Comment by photopea** [comment]
@aloisdg thanks! I also use a lot of closed-source software, e.g. Google search.

**Comment by landsman** [comment]
> You can inspire on projects like Gimp, Inkscape, Audacity, Nextcloud, LibreOffice, VLC... Those big projects have been in the Open Source community

@hialvaro Problem is that Photopea have only one author, from beggining. Software which you metioned was created by default from community.

There is not any sense for make Photopea open-source. Some small packages which Photopea using are already [published](https://github.com/photopea?tab=repositories).

**Comment by aloisdg** [comment]
@landsman selfhosting Photopea make a lot of sense.

**Comment by landsman** [comment]
@aloisdg yes, maybe for you but not for author.

**Comment by aloisdg** [comment]
@landsman his software his rules :)

**Comment by vishnupsatish** [comment]
He worked on Photopea for around 3-4 years, for 5 hours every day, he has every right to keep it closed-source and make money. Making Photopea free is itself a big service to community.

**Comment by blackcrack** [comment]
[strike]his[/strike] this rules b...s... because not open developing in a great GPL2 Community huge possibilitys, 
bigger and more Internationality as them of American "MIT" ... 
'aiiihhhhh...

**Comment by zerofill** [comment]
> his this rules b...s... because not open developing in a great GPL2 Community with a huge possibility's, bigger and more Internationality as them of American "MIT" ... 'aiiihhhhh... and i am more !! as 25 Years in the Net and early's BBS'es 0X who had bring the Software in any Land .. The GPL2 is the best Choice for a Software to interacting and Exchange together with the Code in free way !
> 
> best Blackcrack

I have no idea what you are saying.

**Comment by MMachado05** [comment]
Not to necro this or anything, but you could always use a source-_available_ license such as the BSL. This would allow you to publish the code for people to observe and audit, while letting you retain relatively exclusive rights to actually *deploy* it.

Like others in this issue thread, I'm also a personal fan of F/LOSS, but I don't pretend that getting crowded out by pseudo-competitors who may just want to ruin your livelihood isn't a real problem (take the unfortunate situation the primary dev of the [Sodium Minecraft mod](https://github.com/CaffeineMC/sodium-fabric/issues/2400) was put through as an example).

I, nor anyone else, are in any position to tell *you* what *you* can do with your software. But making the terms under which the product can be used more explicit is always a good thing!
