### ISSUE TITLE
Transformation control squares not appearing

### ISSUE THREAD

**Issue by jmontoya2580** [photopea/photopea#4500]
Hi
The transformation control squares aren't appearing whenever I wanted to resize an image freely. I have the checkbox turned on.
![Screen Shot 2022-04-11 at 3 03 15 PM](https://user-images.githubusercontent.com/103458299/162824021-65140a9c-c94a-4e6e-a295-a5fda2bc843f.png)

**Comment by photopea** [comment]
Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by jmontoya2580** [comment]
> Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

I have updated my browser, Google Chrome, and I have tried opening it in incognito mode, but I still encounter the same issue. I don't have any firewalls or antivirus programs that are changing what I see on my site. I also use a Macbook that runs macOS High Sierra version 10.13.6

**Comment by photopea** [comment]
Ok I see, thanks. Have you tried it with different images and different layers in them? You simply never see the transform controls?

I need to be able to make it happen myself, but I always see the controls.

**Comment by jmontoya2580** [comment]
> Ok I see, thanks. Have you tried it with different images and different layers in them? You simply never see the transform controls?
> 
> I need to be able to make it happen myself, but I always see the controls.

I always never see them when I use a different image or using layers. Its weird and I'm not sure why
![Screen Shot 2022-04-13 at 12 08 55 PM](https://user-images.githubusercontent.com/103458299/163233840-dccc4dab-6737-4526-a808-bb9817d29950.png)
![Screen Shot 2022-04-13 at 12 08 41 PM](https://user-images.githubusercontent.com/103458299/163233843-a8e4aaba-ff12-42a8-9b78-2c83fb281987.png)
![Screen Shot 2022-04-13 at 12 08 17 PM](https://user-images.githubusercontent.com/103458299/163233845-d1d6245a-7cbc-46d3-a78b-c7de20b80a0c.png)

**Comment by photopea** [comment]
Could you show us a screenshot of your whole screen? What kind of layer is selected at that moment?

**Comment by photopea** [comment]
High Sierra is an old browser. Could you update it, in case there are bugs in GPU drivers? Have you tried to use Safari?

**Comment by jmontoya2580** [comment]
> High Sierra is an old browser. Could you update it, in case there are bugs in GPU drivers? Have you tried to use Safari?

Ok it seems I can see the control squares when I open the page up in Safari. Guess I will use it on there now lol. Thank you for your help!
![Screen Shot 2022-04-16 at 4 50 37 PM](https://user-images.githubusercontent.com/103458299/163692420-9ae98cb4-8a09-409a-9a74-518670ce9e5c.png)

**Comment by photopea** [comment]
That is really weird. It should work in all browsers. Are you using a beta version of Chrome? Or what version of Chrome did you use?

**Comment by jmontoya2580** [comment]
> That is really weird. It should work in all browsers. Are you using a beta version of Chrome? Or what version of Chrome did you use?

I'm using Version 100.0.4896.88

**Comment by photopea** [comment]
There is probably some bug in your Mac OS. Could you update your Mac OS? Also, did you try to restart your computer?

**Comment by jmontoya2580** [comment]
> There is probably some bug in your Mac OS. Could you update your Mac OS? Also, did you try to restart your computer?

The Mac model that I'm using is very old and can only upgrade to High Sierra OS. Also I brought it over to a friend's repair shop to replace my battery and to check if there's any problems. It seems there wasn't any.

**Comment by photopea** [comment]
I think that the latest Chrome has a bug related to such old hardware. 

We could report it to Google and ask them to fix it, but as it is so old, just use Safari for now.
