### ISSUE TITLE
Can't Close Window Layer Style

### ISSUE THREAD

**Issue by TogelIDN** [photopea/photopea#4501]
I tried to click everything without refreshing the page because I haven't saved my project. I can't close the window layer and can't switch to my other project. I also tried to do Shift + F5 but it told me to finish the current action first which is the window layer. Is there any way to close it without refreshing my whole page? :c so sad
![image](https://user-images.githubusercontent.com/103500352/162941131-6b0f8c74-e896-4c68-bfb8-bac2192526bd.png)

**Comment by photopea** [comment]
Hey, could you open Photopea separately and try to make it happen again? I would like to know how to make it happen, to be able to fix it.

**Comment by TogelIDN** [comment]
So I came from another window (number 1), I accidentally rapidly double clicked the panel (number 2) and it redirects me to the new tab , my double clicked on the new tab panel number 2 opened the layer style and it won't close :/
![image](https://user-images.githubusercontent.com/103500352/163147440-3cddf613-4296-4943-aa4f-de098be90ede.png)

**Comment by TogelIDN** [comment]
is there any way to fix it? because I still have it opened in my chrome..

**Comment by photopea** [comment]
I made a new adjustment layer, set the clipping mask for it, and double-clicked the spot in your screenshot, but the layer style window still looks normal :(

Can you open Photopea separately, and make such broken window appear again?

**Comment by TogelIDN** [comment]
I will pay more attention if it happens again.. sad I have to close all the current tabs then :c Thank you !

**Comment by photopea** [comment]
I really need some description about how to make it happen. It never happened to me :( I can not fix it otherwise.

**Comment by adriangug** [comment]
Same issue here, it happened to me twice.

**Comment by photopea** [comment]
I need someone to describe to me how to make it happen :(
