### ISSUE TITLE
Disable distort and perspective when there are text layers selected

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4502]
When there are text layers selected, these two option "don't work" as expected. I found that in Photoshop they are disabled in such situation. Could Photopea do the same?

**Comment by photopea** [comment]
fixed! :)

**Comment by nothingshiru** [comment]
Warp worked. It shouldn't be disabled.

**Comment by photopea** [comment]
Warping text is possible only with the "Warp" button of the Type tool. You can not drag the 16 points as you do in the Warp Transform.

**Comment by nothingshiru** [comment]
Sorry, I didn't notice that, because I only adjusted the options at top bar. 
Can you not to disable it but hide the control points? It is convenient to be able to switch between warp and transform. The warp dialog cannot do this.

**Comment by photopea** [comment]
I am afraid I do not understand. What can you do in Photoshop, that can not be done in Photopea?

**Comment by nothingshiru** [comment]
In Photoshop, I can switch between transform and warp quickly by clicking the icon at top bar, and I can also move the layer. 
![image](https://user-images.githubusercontent.com/79258245/163709842-fb00a3db-b0b5-4df9-8f1a-4fa9fb368f74.png)

**Comment by photopea** [comment]
But the warp for a text layer is different than the warp for regular layers. I will leave it as it is. Access the text warp through the Type tool.
