### ISSUE TITLE
Live Shape - Can't transform -> flip

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#4503]
Steps to reproduce:

1. Create rectangle Shape
2. Go to the properties panel 
3. Uncheck "same radii" and make round corners (top left and bottom right) as much as possible.
4. Ctrl+T, right mouse click, and choose "Flip horizontally" 

A year ago it worked well. It can be related with modification made some time ago to have functionalities like rotating the live shapes etc.

**Comment by photopea** [comment]
fixed! :)

**Comment by MichalSZZ** [comment]
@photopea it works. But now I see another thing. https://www.photopea.com/#i4TF1VcDh go there an try to select two layers with shapes. CTR+T and then do "flip horizontally".

**Comment by photopea** [comment]
I am very sorry, it is fixed now :)
