### ISSUE TITLE
Is there any option to export clipping mask in SVG?

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#4505]
I know how to do it in other way, but making vector graphics using clipping masks are the easiest way.

Look at my problem 
![obraz](https://user-images.githubusercontent.com/38118273/163343579-9c90af41-cc4b-4f2d-871f-0f570d22a4c6.png)
 and the result of exporting as SVG

![obraz](https://user-images.githubusercontent.com/38118273/163343833-4c4564ba-198f-4e7f-9e0d-457272d896be.png)

Don't look at eyebrows - it is another (different) problem

**Comment by photopea** [comment]
I have implemented it :) 

If you open the exported SVG back in Photopea, you will see, that it actually puts all clipping mask layers and "the bottom layer" into one folder, and sets a vector mask on that folder.

**Comment by MichalSZZ** [comment]
I just tried it out. Works like a charm! Thank you!
