### ISSUE TITLE
Shift doesn't work in free transform when I want to do "Skew" with Ctrl+Alt+Shift

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#4506]
Steps to reproduce:

1.  Make a rectangle shape
2. Use Ctrl+T to edit transformation
3. Hold Ctrl+Alt+Shift and drag the top middle point
4. Move right and left

It shouldn't move top and down when use is holding Shift in that mode and dragging that point of transformation. Skew should be locked to right and left. Same thin with middle right or left point of transformation.

It does work correctly with Shift + Ctrl and Alt and dragging the corners.

**Comment by photopea** [comment]
Fixed! :)
