### ISSUE TITLE
Missing UI

### ISSUE THREAD

**Issue by IceyDicey** [photopea/photopea#4507]
![Screenshot 2022-04-14 1 23 52 PM](https://user-images.githubusercontent.com/103674510/163441780-fc6143a5-53ee-482a-841d-a9799f6daaa8.png)
As you can see in this picture the layers and history are missing. I didn't do anything different than I usually do I just opened Photopea like normal.

**Comment by photopea** [comment]
I see you have lots of browser extensions. Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/
