### ISSUE TITLE
After I renamed plugin it cannot be uninstalled

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4508]
I made two "Chart Maker" plugins. Initially I named both in JSON with same name "Chart Maker" but it appeared to me it wasn't working correctly so I renamed old one to  "Chart Maker 1" and new one I kept "Chart Maker". Everything seemed to be working but after some time i figured out that in my account I have still installed old one "Chart Maker 1"  showing with name "Chart Maker" but in Plugins there is nothing showing installed so I cannot remove/uninstall it from my account. See screenshots:
This one cannot be uninstalled:
![obrazek](https://user-images.githubusercontent.com/6370548/163475092-d56700d1-e5c4-4ac9-81bc-a4d1ea95bf24.png)
As you can see here nothing is showing installed:
![obrazek](https://user-images.githubusercontent.com/6370548/163475191-6cd051ff-4aaf-4cea-bdd9-90615623b116.png)

**Comment by photopea** [comment]
There are several questions we need to answer first:
- if the author updates a resource (provides a new file), should it replace the old resource (e.g. an old plugin) for everyone who instlled it before the update? Should we keep track of a number of Installs for a completely different file?
- if the author deletes the resource, should users, who installed it in the past, still be able to use it?

What do you think?

**Comment by hxim** [comment]
In my opinion:
If new JSON file is provided and url of plugin is the same it should auto update for everyone. If url is changed it should not.
I mean If resouce is deleted from plugin gallery or URL is changed maybe ask user when plugins are loaded (Photopea is opened and user log in) "You are using old version of plugin XXX. Do you want to "Keep old version" "Update to new version" "Remove from Photopea" ("Update to new version" button would be available only when plugin still exists but with different URL). This way user could uninstall a plugin no longer existing in gallery with "Remove from Photopea" button.
People would be able to use the resource author deletes only when they always click "Keep old version" when plugins are loaded.
I would keep track of a number of Installs per URL of plugin not per JSON file.

Note:
I am going to update icon of all of my plugins in the future with better icon and with  "===" trick you told me (this requires changing JSON file of each plugin). It would be unfortunate if it caused some problems to all users that will install those plugins in the meantime.

**Comment by photopea** [comment]
I have decided that each file represents a different plugin. Install count is tracked for a specific file. So if someone installs your plugin, and you provide a new file, your users will still use the old plugin, and your new file will have a new install count starting at 0.

Please, keep your JSON file the same for a specific plugin. You can still update the website and the icon, which are located at URLs that you provided.

**Comment by hxim** [comment]
OK, but how do I put "===" before icons url. I can't without modification of JSON file. And some icons I wanted to make in different format SVG instead of PNG - I cannot do that without changing JSON file either (They will have different file extentsion)

**Comment by photopea** [comment]
Maybe unpublish your plugin and publish it back once you make an icon.

**Comment by hxim** [comment]
OK I will unpublish and republish with "===" and with SVG format now and replace the actual SVG icon at same URL later.

**Comment by photopea** [comment]
I have fixed the problem. If you go to the Plugins gallery, you will see an option "Installed", which shows installed plugins. If a an installed plugin is not present in the gallery of plugins (e.g. the author deleted it), the plugin name is "????", but it still can be uninstalled.
