### ISSUE TITLE
File turns into a .Dms file??

### ISSUE THREAD

**Issue by LynxClawSenpai** [photopea/photopea#451]
When I click save as a Psd file it turns it into a dms file
How do I fix it?

**Comment by photopea** [comment]
Hi, is it happening for all PSD files you try to save?  What if you try to download a PSD from the internet directly, like this  one? https://www.photopea.com/api/img2/fnt_preview.psd

**Comment by LynxClawSenpai** [comment]
![19921990-d0d2-4f83-8a07-7f3a92674c0c](https://user-images.githubusercontent.com/35384771/35304708-15b155a2-005c-11e8-8717-7f99f6be72ae.jpeg)
When I click this it saves to a .dms file downloading a psd file works fine ^^

**Comment by photopea** [comment]
Can you try it again in an anonymous window? Can you maybe try another browser?

**Comment by LynxClawSenpai** [comment]
What browser works the best all the ones I tried had a hard time loading could be WiFi problems but maybe it’s something else

**Comment by photopea** [comment]
Photopea should work in all browsers. It sounds like you have some virus in your computer, which renames the files. Can you try it in anonymous window?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
