### ISSUE TITLE
Keep radius proportions when transform

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4510]
I believe i have opened an issue with this, but i couldn't find it.

Anyways. I has resizing a live shape and the raddi is kept, but absolutely, not relatively.

So if i have a rounded square, when i shrink it, i get a circle.

I don't know if this is intended.

**Comment by avagp** [comment]
https://user-images.githubusercontent.com/11801254/163493760-6dccecb6-aa1e-44fa-9a47-671b4f9e34c8.mp4

**Comment by MichalSZZ** [comment]
It is a normal behavior and it should work in that way (in Photoshop it works the same).

But I am curious... - is it possible to add a checkbox in properties panel in live shape? Something like "scale corner radius when transform"

**Comment by TheRadicalDreamer** [comment]
@photopea sorry to bother you, but it is kinda urgent for me this feature.

It is possible to add?

**Comment by TheRadicalDreamer** [comment]
That could be!

Because when I need to resize, are shapes that should not be modified!

Please add that!

**Comment by photopea** [comment]
I have added it! In the Properties panel, "Live Shape" section, there is a button for converting a live shape into a regular path.

**Comment by TheRadicalDreamer** [comment]
THANK YOUUUUUUUU

No more problems with logos.

Thank you!

**Comment by TheRadicalDreamer** [comment]
@photopea I believe you have an issue.

I have turned to path many live shapes. Then save the PSD.

When opened again, the shapes are live again.

**Comment by photopea** [comment]
Yeah ... this is our new feature. Photopea auto-detects live shapes in all files that you open (PSD, SVG, PDF, Figma, Sketch, XD, ...). 

Do you think we should disable it for the PSD? PSDs made in old version of Photoshop and Photopea did not have live shapes, but Photopea will create them automatically.

**Comment by TheRadicalDreamer** [comment]
I get why this is a good feature. I have encounter this myself.

Can you check, only on PSD, if i converted a live shape to path, to keep that?

Or maybe you can create another button next to **->path**, a -**>live_shape** button, so you can convert, on demand, each path to liveshape, instead of making it automatically when you open the file?

That way, in both cases we have the feature, but in our terms.

**Comment by photopea** [comment]
Do you really mind, that your path was turned back into a live shape? It should not change how it looks.

**Comment by TheRadicalDreamer** [comment]
I do

**Comment by photopea** [comment]
So you have a rectangle with a corner radius 40. You convert it into a path, make it 4x smaller and save a PSD.

You open a PSD and there is a live shape. The corner radius is 10. If you need to transform it again, just convert it into a path before transforming.

I can disable this auto-detection completely for all PSD files.

**Comment by TheRadicalDreamer** [comment]
Yes, i have done that exactly. Everytime i have to convert it.

What bothers me is that i have set a particular setting to the shape, and
its overwritten everytime.

How i can disable auto-detection? And if i disable it, how i can convert
paths to live shapes?

**Comment by MichalSZZ** [comment]
Converting normal shapes into the live shapes is great.
Maybe you can add  a special popup window when the PSD is opening about possibility to turn on live shapes or keeping shapes without it?
Something like that appear in Photoshop when something new in PSD file is detected and Photoshop asks about opening with some (possible) problems or flatten the layers.

**Comment by TheRadicalDreamer** [comment]
I am not fan of pop-ups :(

If that's the solution, i prefer how things are now.

**Comment by photopea** [comment]
I have disabled the auto-detection of live shapes in PSD files. If you remove the live shape information, it will stay as a regular path forever. But we still detect live shapes in PDF, SVG, Figma, Sketch, XD and other formats.

**Comment by TheRadicalDreamer** [comment]
That will be great.

most of the time i manage logos. So when i resize them i lose the real
shape.

Sometimes i convert them to smart objects, but when i am working with
vectors i lose the quality.

So @photopea/photopea ***@***.***> can you make an option
to keep  the corner radius proportions when transforming??  Please  :D
