### ISSUE TITLE
Tools are hard to see on a high DPI displays

### ISSUE THREAD

**Issue by joegatling** [photopea/photopea#4512]
I am using Photopea on my Mac, and I am running into a lot of difficulty seeing a lot of the tools because they appear very tiny on my high DPI Retina display.

For example, the rectangle select tool creates a very thin 1-pixel outline around the selected pixels, but a single pixel on the Mac display is absolutely miniscule. Attached below is an image with the selection tool active. As you can see, it is really had to visually distinguish because of how fine it is. (Arrows added in case you have trouble finding it)

<img width="631" alt="Screen Shot 2022-04-16 at 20 49 23-2" src="https://user-images.githubusercontent.com/3136323/163699661-164dcaf8-d71f-46dd-8fab-c0325348c8aa.png">

I believe the simplest fix would be to detect the high-DPI display and double the size of tool UI thickness across the board.

Steps to reproduce:
1. Open Photopea on a Mac (I am using a MacBook Pro, but I suspect any Retina display Mac would suffice)
2. Use the rectangle select tool select a portion of the image
3. Observe that the rectangle is very hard to see.

**Comment by photopea** [comment]
I have implemented it. The thick selection contour should be displayed to users with a device pixel ratio over 2.5. You can see your ratio e.g. here: https://johankj.github.io/devicePixelRatio/

**Comment by joegatling** [comment]
Hi!

I checked that pixel ratio website on my MacBook Pro (16-inch, 2019) using Safari and it shows me **2**. Is that expected? It seems to be below your 2.5 cutoff for thick UI, but the selection box and brush outlines are still very hard to see.

Would it be possible to expose an option to enable this feature?

**Comment by photopea** [comment]
I have set the DPR limit to 1.9, so it should work for your case, too. A thicker outline is drawn for the brush cursor, too.

**Comment by joegatling** [comment]
I just tested it out. This is great, thanks!
