### ISSUE TITLE
<NEW BUG>Light and Transparence

### ISSUE THREAD

**Issue by guihaenisch** [photopea/photopea#4516]
Hi there, when opening the attached file, Photopea is bugging.
This never happens before.
![7Z_2104 w018 n001 857B p15 857](https://user-images.githubusercontent.com/102599244/163734775-4140952a-11ee-4220-ba79-521f701dfefe.jpg)
[7Z_2104.w018.n001.857B.p15.857.zip](https://github.com/photopea/photopea/files/8502570/7Z_2104.w018.n001.857B.p15.857.zip)

**Comment by photopea** [comment]
Your file is the Adobe Illustrator file, and it contains many Gradient Meshes. Photopea does not support Gradient Meshes.

Open your file in a program, which supports Gradient Meshes. I think it is only the Adobe Illustrator :(
