### ISSUE TITLE
Unable to save the JPG

### ISSUE THREAD

**Issue by NJJutube** [photopea/photopea#4517]
I did it like normal File, Export as, JPG, and something new pops up, I click save and it still doesn't work.

**Comment by photopea** [comment]
Try this, let me know if it helped: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
Did you try it in the Incognito mode?

**Comment by NJJutube** [comment]
yes

**Comment by photopea** [comment]
What web browser and version do you have? Could you record a short video of what is happening? Did it ever work in the past?

**Comment by NJJutube** [comment]
I will try to send a short video, and also it did work in the past plenty of times.

**Comment by NJJutube** [comment]
[https://clipchamp.com/watch/nMXPQqGZqPG](url)

**Comment by NJJutube** [comment]
uh sorry [https://clipchamp.com/watch/nMXPQqGZqPG](url) is not working, Idkw

**Comment by NJJutube** [comment]
Here you go.
https://user-images.githubusercontent.com/103960486/163880290-bf0ea937-1213-4a60-b205-0eef4678daab.mp4

**_

**Comment by photopea** [comment]
What does the "Saving ..." at the top mean? That should not be there. You can not expect anything to work in such situation which is already wrong.

Please, show me, how do you make such message with "saving ..." appear for such long time. It never happened to me.

Record the whole process, from opening www.Photopea.com to saving a JPG.

**Comment by NJJutube** [comment]
here it is

https://user-images.githubusercontent.com/103960486/163894258-e0f42a92-5621-4c71-ad8f-c5d09258c8a1.mp4

**Comment by photopea** [comment]
The "Save for web" window should show you a preview of the image on the left side.

Could you record the whole process, from opening [www.Photopea.com](http://www.photopea.com/) to saving a JPG (in the Incognito mode) ?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
