### ISSUE TITLE
Start from 9 not 3.33

### ISSUE THREAD

**Issue by jack-fdrv** [photopea/photopea#4518]
![220419011553(1)](https://user-images.githubusercontent.com/4230282/163886270-01369fde-b5b5-4a22-b1fd-83d84b7d7afe.png)

**Comment by jack-fdrv** [comment]
Actually the original photoshop is cheaper =)
If there any way how i can buy life license, or year for 20$?

**Comment by photopea** [comment]
The cheapest = "starting" Photopea is $10 for 90 days, which is $3.33 a month. We do not sell any life licenses. 

What is the original Photoshop? I thought there is just one Photoshop.
