### ISSUE TITLE
Feature request: Predefined zoom setting

### ISSUE THREAD

**Issue by uwu-as-a-service** [photopea/photopea#4519]
Have a default zoom value for all newly imported images

**Comment by photopea** [comment]
I think it is not useful. It is better to set the zoom such that the image is fully visible. Since each image has a different resolution, a different zoom is needed for each image.

**Comment by uwu-as-a-service** [comment]
I happen to work on several images at a time which are all the same size, and it would certainly help if I didn't have to manually zoom in everytime I switched to a new page.

**Comment by uwu-as-a-service** [comment]
> I think it is not useful. It is better to set the zoom such that the image is fully visible. Since each image has a different resolution, a different zoom is needed for each image.
@photopea 

I happen to work on several images at a time which are all the same size, and it would certainly help if I didn't have to manually zoom in everytime I switched to a new page.

**Comment by photopea** [comment]
Do you want zooming in one document change the zoom of all other documents? Have you tried the View - Pixel to Pixel and other options?

**Comment by uwu-as-a-service** [comment]
> Do you want zooming in one document change the zoom of all other documents? Have you tried the View - Pixel to Pixel and other options?

A default zoom value that would be applied to any newly imported files. It seems like I have to zoom everything manually everytime I switch to a new file, so I want all files to be pre-zoomed to my defined value somewhere in the settings.

**Comment by uwu-as-a-service** [comment]
> So what would your zoom value be? If it is e.g. 25%, and you open a 100x100 pixel image, you can see it only as 25x25 pixels.
> 
> Similarly, if you open a 10,000 x 10,000 pixel image, you will see only the small part of the middle, not the whole image.
> 
> I can't see how such thing could be useful.

Like I mentioned before, I work with images that all have a fixed size. The zoom value would be predefined in settings. Even better if you could set a default position as well

**Comment by uwu-as-a-service** [comment]
Image for reference below. This is how it looks like for me by default.
![image](https://user-images.githubusercontent.com/92350991/170738473-6b78af7c-b1ce-4eb8-8856-e20dd081f763.png)

**Comment by photopea** [comment]
Could you share one of your images with us? I would like to try it myself.

**Comment by uwu-as-a-service** [comment]
> Could you share one of your images with us? I would like to try it myself.

https://drive.proton.me/urls/32PS52ESE4#0UuyjGOxCavv

**Comment by photopea** [comment]
Could you also tell me your screen resolution? When I open your PSD, it is quite large.

**Comment by photopea** [comment]
I have added the "All Documents" checkbox to the Zoom tool and the Hand tool. If it is enabled, zooming and panning will be applied to all documents.
