### ISSUE TITLE
Error in Photoshop file: wrong signature while opening smart object layer

### ISSUE THREAD

**Issue by msilen** [photopea/photopea#452]
When I try to open smart object layer I get this error. File was created in photoshop. In photoshop it opens fine.

**Comment by photopea** [comment]
Hi, could you please send us your PSD file to support@photopea.com ?

**Comment by msilen** [comment]
Done, I've sent the file.

**Comment by photopea** [comment]
Hi, it was fixed, you can open your PSD file now. Thank you very much! :)
