### ISSUE TITLE
Magic Wand is going crazy

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4521]
WHen i use the magic wand the history of the project begins to jump!

https://user-images.githubusercontent.com/11801254/164065727-ce5d13cc-46b5-477c-9024-035791f0d336.mp4

https://user-images.githubusercontent.com/11801254/164065751-da7ee962-de64-4fb3-a018-d33c2ae7e4e0.mp4

**Comment by TheRadicalDreamer** [comment]
https://user-images.githubusercontent.com/11801254/164066315-2c8e5472-c376-49c2-a7ea-5e397572322e.mp4

I do the following:

- Insert image
- transform it
- rasterize it
- crop it
- magic wand to select certain spots, and then.... the black magic begins

**Comment by TheRadicalDreamer** [comment]
i can repro everytime

**Comment by TheRadicalDreamer** [comment]
I opened and closed Photopea many times. But still happening.

**Comment by photopea** [comment]
I have tried what you say, but I can not reproduce it :( Are you saying you can not reproduce it either?

**Comment by TheRadicalDreamer** [comment]
I cannot repro anymore.

I deleted the file and began again. That was the only fix.

Sorry i did not kept the PSD.

But now it does not happen.
