### ISSUE TITLE
Press "enter" to close canvas resize window

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4522]
![image](https://user-images.githubusercontent.com/11801254/164077492-b3d101bd-d60f-4bfb-939b-10a9a40a5776.png)

This window, differently from the others, is not closed automatically when i press Enter twice.

Also Image size window

**Comment by TheRadicalDreamer** [comment]
Maybe all windows could be set OK with Ctrl+Enter.

What do you think?

**Comment by photopea** [comment]
It should be fixed now :) It already worked for Image Size.
