### ISSUE TITLE
Stroke sharp corners get peaks, that make it unusable

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4524]
https://user-images.githubusercontent.com/11801254/164525352-11cccb95-5ace-4d39-9134-10b2ce168a9f.mp4

**Comment by TheRadicalDreamer** [comment]
I still have problems with this.
https://www.photopea.com/#iwdHpQCFf

![image](https://user-images.githubusercontent.com/11801254/164373143-19d8f8f2-23f1-468f-a864-1a889e2e66d9.png)
![image](https://user-images.githubusercontent.com/11801254/164373149-4719ecb7-7b7a-4c01-907f-7431b3207b65.png)
![image](https://user-images.githubusercontent.com/11801254/164373152-4f3f4594-7502-473b-a617-415b0ede012c.png)

**Comment by TheRadicalDreamer** [comment]
https://user-images.githubusercontent.com/11801254/164525352-11cccb95-5ace-4d39-9134-10b2ce168a9f.mp4

**Comment by TheRadicalDreamer** [comment]
Also the O, have this weird rays inside

**Comment by TheRadicalDreamer** [comment]
I get why it gets SO sharp
https://user-images.githubusercontent.com/11801254/164568993-ef61181c-431c-4114-86c4-7d1cc484bb38.mp4

**Comment by photopea** [comment]
I have fixed it. I hope I did not bring anything else.

We use the Canvas 2D context for drawing vector shapes. It supports only the "center stroke", so we draw a center stroke and erase the inner side of a shape, to draw the "outer stroke".

**Comment by TheRadicalDreamer** [comment]
Sorry, but this could be fixed as well?
![image](https://user-images.githubusercontent.com/11801254/165002444-afc0010c-94d2-4954-a1b5-b1008a8b7980.png)

![image](https://user-images.githubusercontent.com/11801254/165002472-e4cf5ed0-b820-491c-9d10-9e96c6ed681a.png)

https://www.photopea.com/#iNbjofNBr

**Comment by photopea** [comment]
A) that is how it should be rendered! Create the same thing in Adobe Photoshop or any other vector editor, it will look identically.

B, C) I think it is related to our rendering method of Context2D, and can not be fixed until we create our own rendering method. I asked about it here: https://stackoverflow.com/questions/72001021/svg-circle-where-the-stroke-width-is-bigger-than-the-diameter

**Comment by TheRadicalDreamer** [comment]
A) you are right. Keep as is then. :D

B,C) it would be great to have it solved. 🧐
