### ISSUE TITLE
When Export Layer, don't export with Gradient Map

### ISSUE THREAD

**Issue by powerml2** [photopea/photopea#4526]
Hi guys.

Thank you for the program. It's very great.

The bug that I found is this: I have many layers, and I create a Gradient Map. When I use "Export Layers", the Layers are exported without the effect of the Gradient Map. I hope this make sense because English is not my first language.

Thanks and Peace.

**Comment by photopea** [comment]
What is a Gradient Map? Do you mean the Gradient Map Adjustment Layer?

Each layer is exported separately, while all other layers are hidden. Maybe put all your layers into a folder and make that folder exportable by naming it "-e-".
