### ISSUE TITLE
Unable to download invoice

### ISSUE THREAD

**Issue by fdebef** [photopea/photopea#4527]
I get this error in browser console, after clicking on Invoice button under Account:
```
Uncaught` TypeError: Cannot read properties of null (reading 'acc')
    at gU.BP.aqu (pp.js:11186:61)
    at fV.fJ.c (pp.js:9494:49)
    at fV.eJ.c (pp.js:9499:43)
    at fV.Zr (pp.js:9567:95)
```

**Comment by photopea** [comment]
That is really strange. Did you try to close and reopen Photopea? Could you try to log out and log in again?

**Comment by fdebef** [comment]
Same result :(
Prerequisites:

- Logged in with Google account (Workspace for Business)
- Chrome on MacOS
- Chrome on Windows
- Disabled/uninstalled Privacy Badger

Tried log out, tried different computer. All same results.

**Comment by photopea** [comment]
Could you tell me under what email address did you log in to Photopea?

**Comment by fdebef** [comment]
filip at cyrmex cz

**Comment by photopea** [comment]
I can not see your record in a database. Did you use Photopea at all while being logged in?

I created a dummy record for you. Could you try it again?

**Comment by fdebef** [comment]
Anyhow, now it works!
