### ISSUE TITLE
Photopea freezes when tapping "swap colors" button with finger

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4529]
To reproduce
1. Create a new project.
2. Select brush tool.
3. Paint on canvas.
4. Swap colors.

Repeat the step 3 and 4, you'll see Photopea frozen and you cannot paint anything on canvas anymore. The effect of this bug is similar to the "invisible finger".
![New Project (2)](https://user-images.githubusercontent.com/79258245/164739137-df8fee5c-fd33-4ab0-bb0b-9afe9e15726d.jpg)

**Comment by photopea** [comment]
It should be fixed now.
