### ISSUE TITLE
Script for "Get PNG"

### ISSUE THREAD

**Issue by JaydevM** [photopea/photopea#453]
I like "Get PNG" button, but i want to automate thing and get PNG of every layer of PSD.
I see "Process Layers" example code for iterating over each layers, but what method should i call for "Get PNG"?

P.S. I just discovered this in Google Drive App and this is exactly what i was looking for since forever.
Great Work.
BTW, Is this your full time job?

**Comment by photopea** [comment]
Hi JaydeM, thank you! Yes, it is my full time job, but I don't even make a minimum wage right now.

Exporting many layers at once sounds like a great idea. But there can be many kinds of layers (text layers,  adjustment layers, smart objects) and I am not sure what would be the best exporting mechanism. Somebody may want to export a group of layers as one PNG.

Do you have any example of a PSD and the output set of PNGs? Do you have any experience with Avocode or Zeplin? I think those programs can do it.

**Comment by JaydevM** [comment]
> Yes, it is my full time job, but I don't even make a minimum wage right now.

This is dilemma of open source developers. To monetize or not monetize.
I hope you will figure-out a way for that.

> Do you have any experience with Avocode or Zeplin? I think those programs can do it.

You read my mind. I'm a developer and i want to extract assets from PSD files, 'for free without creating any account' implied.

> there can be many kinds of layers (text layers, adjustment layers, smart objects) and I am not sure what would be the best exporting mechanism. Somebody may want to export a group of layers as one PNG.

That is right. Lots of layer some of them might depend on other like masking layer.
I'm planning to use something like `if(lays[i].visible==true)` for that.
Still not fully automatic but reduces great amount of workload.

> Do you have any example of a PSD and the output set of PNGs?

You can test this for any freely available PSD designs of web site or mobile apps.

**Comment by photopea** [comment]
What would be better? Should we have an automatic export of the whole PSD with lots of preferences, or we should encourage users to write their own scripts / rewrite existing ones?

**Comment by JaydevM** [comment]
### Ideal Semi-Automatic Solution for Asset Extraction:
* Iterate through all layers in Postorder manner // [See Page 4 Example 6.1](http://www.di.ubi.pt/~cbarrico/Disciplinas/DataStructures/Download/Non-binary_Trees.pdf)
  * Show preview of current layer only // we can do this by making every other non-child layers "invisible", because creating PNG preview for each iteration will be expensive
  * Ask user if he wants this previewed layers as PNG? // simple dialog box with "yes/no" button will do
    * If yes then immediately start downloading previewed layers as PNG
  * go to next layer

*Give some option such that user can pause/resume iteration process any time. // give each iteration a incremental number so user can skip through some iterations*

* After each single layer assets are extracted, user will **manually** extract multi layer assets (different combination of sibling layers).
// alternatively we can use some creative tree traversal algorithm which can do smart sibling only permutations

If we can create example script of this then users will be encouraged to write/modify their own scripts.

I think main challenge here is creating a dialog box with "yes/no" button.
Is it possible through script to create dialog box?

**Comment by JaydevM** [comment]
Note that my solution is generally applicable even for messy PSD files which do not have proper names and/or hierarchy.
For starters, we can offer some demo script of extracting assets from PSD with proper layer names.
E.g. Iterate over every layers; If layer name starts with "ICON_" then extract it as PNG.

**Comment by photopea** [comment]
My idea was to make a form, where user will set the settings, click Export, and the ZIP archive with assets will be offered for the download. 

Right now, we already have the SVG export, which exports an SVG file containing everything (PNG, JPG images or even fonts). There was an idea to make an automatic HTML export somehow some time ago.

**Comment by JaydevM** [comment]
Right. Exporting whole PSD as HTML is also a good idea, but this also fails where two or more layers are supposed to be merged in single Icon/PNG.

In conclusion, we can say that there is no universal solution for asset extraction because designers use all kind of messy and bad practice to make design look better.
We can do our best by **reducing** most of repetitive work. // This should be our main focus.
Users must do some manual work.

In summary, here are options we have explored so far:
1. Extracting every JPG/PNG files in PSD. (just like SVG export, because most of assets are already stored in JPG/PNG format)
2. Some form where user can set various settings/preferences like "Regular expression on layer name", "visible property of layer", etc. and get all assets as ZIP which satisfy that settings/preferences.
3. [Ideal Semi-Automatic Solution for Asset Extraction](https://github.com/photopea/photopea/issues/453#issuecomment-359943457)
4. Some simple example scripts for:
   1. iterating over all layers
   2. all property names and method call signatures (like "Process Layers" example)
   3. exporting a single layer OR multiple layers as PNG

   Users are supposed to edit this example script as per their requirement.

Personally for now i would like to see 4.3: Example code for exporting a single layer as PNG.

**Comment by photopea** [comment]
Right now, you can not save a single layer as a PNG from a script. You can only do it through the mesaging API: https://www.photopea.com/api/live

I am afraid users would not want to write or edit any scripts. I think it is not a way to go.

Can you take a look at Zeplin or Avocode, how they do it, or if they can do it at all? Let's not reinvent the wheel.

**Comment by photopea** [comment]
As far as I know, PSD format can not store any exportable information.

I made the following mechanism of exporting assets: You should name a layer as "-e-....." to make it exportable (it can be even a folder of multiple layers). Then, press File - Export Assets. Here, you can choose which format and size you want to export. 

All exportable layers will be exported in a ZIP file with a single click.
