### ISSUE TITLE
Quick Mask Bug

### ISSUE THREAD

**Issue by ootap** [photopea/photopea#4530]
An issue with quick mask that completely breaks the project. Pressing Q or even selecting it from the drop down will freeze all functionality of the project. This is new as I was using it not too long ago.

Here's an error in console: 
![image](https://user-images.githubusercontent.com/96444260/164770572-7e76e5d2-1f39-455d-8875-d68b150ba944.png)

To reproduce: Make a selection and press Q and attempt to do something.

<3

**Comment by photopea** [comment]
I am very sorry :( It is fixed now.
