### ISSUE TITLE
Freezing when using mask feature

### ISSUE THREAD

**Issue by EndeavorStudio** [photopea/photopea#4532]
When I click the icon to rasterize, everything freezes and I can't do anything.  it was working last night just fine.  I'm working in a large file 5000x5000px 300 dpi.

**Comment by cyanharlow** [comment]
I think this may also be related to my issue https://github.com/photopea/photopea/issues/4531 which i originally thought was attributed to large file size, but I've since been able to replicate this issue in a smaller file that also uses quite a lot of masking.

**Comment by photopea** [comment]
it should be fixed now (probably).
