### ISSUE TITLE
Multiple pdf files exported on Firefox 99.0.1 Win 10 Pro 10.0.19044 build 19044

### ISSUE THREAD

**Issue by iapyx-00** [photopea/photopea#4533]
Hi,

When using File > Export as > PDF, multiple PDF files are exported at full document size. First, two documents are exported without a file name (two files named "pdf") then the correct "projectName.pdf" as expected.  Prepending a name/prefix to the first two files produces working .pdf document(s).

Thanks

![multi_pdf_cap](https://user-images.githubusercontent.com/44683892/164800803-26bfc4c5-bb9b-446c-b285-8145abd72522.PNG)

**Comment by photopea** [comment]
In my case, when I export a PDF in Photopea in Firefox, a PDF file is opened in firefox instead of Photopea, and I lose all my work.

Have you looked into Firefox settings, if it can be changed?

**Comment by photopea** [comment]
The usage of Firefox is dropping and I think I know why :(

**Comment by photopea** [comment]
I have found a following solution. In Firefox, open "about:preferences". Enter "pdf" into the search bar.

As "Action" for the PDF, choose "Save File".
![image](https://user-images.githubusercontent.com/15955558/164970676-33775791-d754-42a5-bc83-2190d0b45d21.png)
