### ISSUE TITLE
Liquify is bugged after consecutive use

### ISSUE THREAD

**Issue by jackson2k2** [photopea/photopea#4534]
![index](https://user-images.githubusercontent.com/17772724/164876452-77d3e969-d029-47b5-ac9c-2e9b17faca8d.png)
After successful attempts of using Liquify, the filter tool begins to spaz out and no longer shows anything besides an undefined checkboard. You can not drag out of it, and your only option is to exit and restart Photopea-- or, if you're lucky enough, you can zoom to the sides and drag your way out.

**Comment by photopea** [comment]
Could you describe some steps, how can I make it happen on my computer?

**Comment by photopea** [comment]
I have to close it because of lack of details.
