### ISSUE TITLE
Feature request: Vector View

### ISSUE THREAD

**Issue by jexxmusic1** [photopea/photopea#4535]
### Vector View

I would really like to know whether there is a chance that Photopea will implement **vector-based viewing** in the future. It works like this: Click the **File** button, go to **Project View** and select either **Pixel** or **Vector**. I'm working on pixel, as well as vector design too. Would greatly appreciate it if you would add this feature. 

Cheers, Jeremy.
![jexxinium_icon](https://user-images.githubusercontent.com/91823994/164986303-942f396a-43f8-43a1-9df2-c5026682a404.gif)

**Comment by photopea** [comment]
Do you mean not seeing pixels after zoom-in? But there still will be raster layers and raster masks, so there will be pixels for them, right?

**Comment by MichalSZZ** [comment]
@photopea  I think that I know what he would like to have as a feature in Photopea. 
I wrote some time ago about that here on GitHub. Illustrator can show its paths in pixel preview. 
Sometimes I am making only vectors in Photopea. Like icons, shapes or logotypes. Without any FX like shadows and so on.
I would like to have vector preview - just like browsers show the SVG files. Zooming in doesn't show pixels there for paths, gradients etc.

**Comment by photopea** [comment]
Imagine when you export a PSD file to SVG. So many things are lost. Some blend modes dont work, clipping masks, etc.

I think it would be really confusing for so many users. I would spend more time explaining how it works, than creating such "vector mode".

Why dont you simply increase the DPI in Photopea when creating vector graphics?

**Comment by MichalSZZ** [comment]
But that is how its work now... I can do graphics with a lot of effects and Save my project to SVG. And I will lost a lot - but I know why. 
I am talking only about the vector preview of paths during editing. For example. I do an icon 60x60 px. I have 1200% zoom for better design experience and I see large pixels with anti-aliasing.
In Illustrator I can turn on pixel preview for better pixel editing experience. It will be nice to have in Photopea View->Vector Preview for better vector preview.
But I will understand if that will be hard to implement in Photopea.
I work mostly in Adobe (because my company pay for it) but I have my finger crossed all the time for Photopea :)

**Comment by JexxMusic** [comment]
Sorry for not replying! I understand that you can increase the DPI. What I want actually meant is to view only paths and shapes in higher quality. Vector View also should disable pixel grid.

**Comment by photopea** [comment]
@MichalSZZ @TheRadicalDreamer  I have implemented the Vector Viewing Mode.  It can be enabled for each document separately in View - Mode - Raster / Vector . You can switch the view at any time.

Following elements can be "infinitely zoomed":
- vector shape layers
- text layers
- smart object layers (if you have a 1000x1000 px smart object, placed as 4x4 px, you can zoom in and see the original pixels)

Many things are ignored in this mode (layer styles, smart filters, adjustment layers, raster and vector masks).

Maybe ve could create a separate vector editor, which will be Photopea with the Vector view mode enabled by default, and the pixel-related tools removed (brush tools, eraser, selection tools, adjustments, etc).

**Comment by JexxMusic** [comment]
Thanks so much! I appreciate your work. Keep up your project as far as it goes!

**Comment by TheRadicalDreamer** [comment]
> Sorry for not replying! I understand that you can increase the DPI. What I want actually meant is to view only paths and shapes in higher quality. Vector View also should disable pixel grid.
> 
> Edit : Whoa I was so late, wasn't I? 😅

But that decrease your browser performance i believe :/

**Comment by TheRadicalDreamer** [comment]
> @MichalSZZ @TheRadicalDreamer I have implemented the Vector Viewing Mode. It can be enabled for each document separately in View - Mode - Raster / Vector . You can switch the view at any time.
> 
> Following elements can be "infinitely zoomed":
> 
> * vector shape layers
> * text layers
> * smart object layers (if you have a 1000x1000 px smart object, placed as 4x4 px, you can zoom in and see the original pixels)
> 
> Many things are ignored in this mode (layer styles, smart filters, adjustment layers, raster and vector masks).
> 
> Maybe ve could create a separate vector editor, which will be Photopea with the Vector view mode enabled by default, and the pixel-related tools removed (brush tools, eraser, selection tools, adjustments, etc).

And Ivan drops the mic and the people go crazy! 🎉🎉🎉


I will try it right now!

**Comment by TheRadicalDreamer** [comment]
Some shapes get filled with black :/
![Screenshot 2022-05-09 00 16 07](https://user-images.githubusercontent.com/11801254/167339730-e04f027a-1d39-4b55-8b33-de22fe667dbf.png)
![Screenshot 2022-05-09 00 16 01](https://user-images.githubusercontent.com/11801254/167339733-80a15ff8-d8a2-404e-97e5-455f1c7a9a1f.png)

**Comment by TheRadicalDreamer** [comment]
I have to say, i DO love the idea of a new Photopea, only for vectors. Like a AI like program.
Photopea-Vector will be great!

I do work a lot on vectors and many  times i have to modify AI but i cannot do it properly on photopea.

**Comment by MichalSZZ** [comment]
@photopea did you turn off that feature? after the busy weekend now I wanted to check this cool feature and I don't see where I can find it...

About Photopea for vectors... I think that would be better step to have that kind of software in your portfolio. Everybody want to have Video software, but I am aware of that will be a problem for a device performance and for the browser itself. I am making Motion Design animations in After Effects and I know that effects applied on the video frames are killing my PC in preview mode. And without live preview this kind of software is useless.

**Comment by TheRadicalDreamer** [comment]
> @photopea did you turn off that feature? after the busy weekend now I wanted to check this cool feature and I don't see where I can find it...
![image](https://user-images.githubusercontent.com/11801254/167450263-067951bc-49e5-4717-a93f-8d0fe60d5a51.png)

**Comment by TheRadicalDreamer** [comment]
I would like to go a bit deeper on the zoom. I don't know if it possible.
![image](https://user-images.githubusercontent.com/11801254/167454238-040cadcd-824b-44e8-9905-952486401da9.png)


This for example is the most zoomed i can have, but still is difficult to select the anchor's handle.

**Comment by photopea** [comment]
did you make such short handles on purpose? I think it would look the same if it was just one point (polygon instead of a curve).

**Comment by photopea** [comment]
I have implemented the Drop Shadow style, and the Smart Blur on Smart objects for the Vector View. I think the Vector View is getting closer to the regular view, but it is infinitely zoomable.

**Comment by MichalSZZ** [comment]
@TheRadicalDreamer thank you for the screen shot. Ivan wrote that it is in menu View -> Mode and I looked there (in the place like in Illustrator). I even didn't think to look in Image -> mode :)

**Comment by MichalSZZ** [comment]
Ivan you are a genius! You made exactly what I expected!

**Comment by ebmh** [comment]
@photopea Is this feature still active? I can't find it anymore. :)

**Comment by photopea** [comment]
We are planning to release a new vector editor soon, where the vector view will be the only view.

**Comment by TheRadicalDreamer** [comment]
![yes-bob-esponja](https://user-images.githubusercontent.com/11801254/215563590-6d902ac2-f2a3-4834-8c28-d0e46afcc8c9.gif)

**Comment by TheRadicalDreamer** [comment]
I'll be the first user in the waiting line!!!

**Comment by photopea** [comment]
Thanks! But how should we call it? Vectorpea? 

@MichalSZZ @hxim

**Comment by TheRadicalDreamer** [comment]
Yes.

It is not a super fancy name, but it does it all correctly:

-It links the name of photopea to the new platform
-It indicates what the new platform is about
-It is easy to remember


If not, what will be: illuspea?

**Comment by camoody1** [comment]
Victorpea! 😆

**Comment by camoody1** [comment]
Or perhaps Photocarrot!

**Comment by photopea** [comment]
What about "Vecpea"? The name does not tell you what "Vecpea" does, so it is just like Apple or Google :/ but it is quite short.

**Comment by camoody1** [comment]
I honestly think Vectorpea is a great name for all the reasons @TheRadicalDreamer stated.

The only other reasonable name, in my opinion, would be Illustrapea.

**Comment by MichalSZZ** [comment]
I think we don't need to use "Illustra" prefix in the name of the app. 

Short Illupea can be better but the main question is - do you want to do Illustrator alternative that the main extension and file structure will be .ai? If yes Illupea will be good. 


Vectorpea tells everything about the program. But maybe too much?
Vecpea - how does it sound for the nativ english speaker?

**Comment by MichalSZZ** [comment]
BTW. I liked very much the idea of Vector View in Photopea. Even if that wasn't perfect ('beta' suffix can tells about that)

**Comment by camoody1** [comment]
I only suggested Illustrapea because Photopea is similarly close to Photoshop. That tells the user exactly what he or she is getting into. But your point is well taken... only take that name if your intention is to build an Illustrator replacement like Photopea is a Photoshop replacement.

Otherwise, stick with Vectorpea. That name is much more understandable than Vecpea. "Vecpea" sounds like some sort of prescription drug. 😆

**Comment by ebmh** [comment]
Nice, you already have a plan when this will happen? ♥️

**Comment by photopea** [comment]
I need to work on it for about 10 hours before I can publish it.

But I am doing other things, so I dont know when I will find these 10 hours of time :( today, I have been trying to make Photopea open raw photos from Olympus E-5 digital camera with a correct white balance. I spent the whole day trying to fix it, without finding any solution. And someone else sent me a raw photo from Nikon - .NEF today, which I will need to take a look at, too.

**Comment by TheRadicalDreamer** [comment]
Take you time Ivan.

We are not in a rush :)

I believe I speak from all, thank you for your great work, your wonderful creation, and incredible attention to the community.

We are glad you did heard our ideas. But don't feel pushed man.

:D

**Comment by smeargtr** [comment]
I think Vectorpea is great as it has the same syllables as photopea. Also cant wait for it to come out!

**Comment by photopea** [comment]
I think "Vectopea" could be good, as it shares "topea" wiht "Photopea", and the difference is "Pho"-"Vec"

**Comment by camoody1** [comment]
"Photo" is a full word, though, as is "Vector". "Vecto" isn't a word. Vectorpea and Vectopea are close enough to not be a big deal either way, but I still think "Vectorpea" makes more sense. 🤷🏽‍♂️

Excited to see what you've been working on, either way.🙂

**Comment by TheRadicalDreamer** [comment]
Yes. And the initial word gives you a hint of the software :)

So vector i believe should be better
