### ISSUE TITLE
feature request: add overlay on the area that will be cropped

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4536]
![image](https://user-images.githubusercontent.com/79258245/164989319-8befd27e-b08e-4f82-8559-d0dad7e3a40c.png)

**Comment by photopea** [comment]
I think it has no practical meaning, other than making Photopea look even more like Adobe Photoshop.

**Comment by nothingshiru** [comment]
It make users able to preview the cropped image clearly. It is a common feature for the crop tool in image editor/painting software. Not only Photoshop has it, but also GIMP, CSP, Krita, Procreate...
