### ISSUE TITLE
Styles gallery issues

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4537]
I added "Cool Text Styles" - first item into "Styles gallery". I found two issues:
1.) When I install this with Install button. It does not refresh styles appering in Window-Style window. I need to define new style to make it refresh. In Layer Style window they appear correctly.
2.) When I have both plugins and styles from this gallery under "INSTALLED" there appear items without names from other type of object (when I have plugins selected there is empty item for "Cool Text Styles" and when I have styles selected there are empty items for all of instelled plugins)

**Comment by photopea** [comment]
both fixed, thanks! :)
