### ISSUE TITLE
hebrew translation wrong

### ISSUE THREAD

**Issue by alondon17** [photopea/photopea#4538]
![image](https://user-images.githubusercontent.com/29633387/165071844-4d1eb8c3-fb40-48b7-b1ea-5f12125a00b4.png)

**Comment by photopea** [comment]
Could you fix it at www.Photopea.com/translate ?

**Comment by alondon17** [comment]
I meant remove the sdf

**Comment by photopea** [comment]
It is updated now. Thanks!
