### ISSUE TITLE
Export PDF - shape gets different output

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4540]
![image](https://user-images.githubusercontent.com/11801254/165219748-62dda8a3-2ecc-487b-aaad-8b11bef26406.png)

Look, i don't know why it gets a line in the middle (i know there is a shape there, but why it shows when exporting)

PSD: https://www.photopea.com/#iRr3CuIIC

**Comment by photopea** [comment]
You have set the "Fill" property of a parent folder to 40%. I dont know if PDF supports the "opacity of a folder". Currently, every shape in the folder is drawn with the 40% opacity.  So the gray ellipse does not cover the background completely.

I will do some research to see if it is possible to reproduce the behaviour of a PSD in the PDF.

**Comment by photopea** [comment]
Here is a simpler case, try to export it to SVG or PDF: https://www.photopea.com/#iZxGssFZR

**Comment by TheRadicalDreamer** [comment]
yes, that's exactly the issue.

For my particular case i can put a white square on top and fade it

**Comment by photopea** [comment]
I have implemented it. The PDF export supports the transparency and the blend mode of the groups now. These features can be nested - you can have a semi-transparent folder inside a semi-transparent folder inside ...

And of course, Photopea can load PDF files with such transparency of groups correctly, too.

I made this demo: try to export it as a PDF, and then, load it back: https://www.photopea.com/#iExuCfn40

**Comment by TheRadicalDreamer** [comment]
Great!!

You are awesome!
