### ISSUE TITLE
Square around the brush cursor

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4541]
to reproduce
1. Creat a mask on a layer.
2. Hold <kbd>Alt</kbd> and click on the mask.
3. Select brush tool.
4. Hold <kbd>Alt</kbd>+<kbd>Mouse right button</kbd> and move horizentally or vertically.
![新建项目 (2)](https://user-images.githubusercontent.com/79258245/165288785-0534179d-178e-4a64-b521-b209e680b776.png)

**Comment by photopea** [comment]
fixed :)
