### ISSUE TITLE
Folder should be activated when it is collapsed if there layers activated inside the group

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4543]
![image](https://user-images.githubusercontent.com/79258245/165292661-c2001353-1588-4b98-9de0-498f01bc0cf9.png)
For example, there is a Folder 1 with Layer 1 inside it activated. If I collapse the Folder 1, the Layer 1 should be unactivated and the Folder 1 should be activated, but Photopea doesn't work like that. 

In Photoshop, if I want to create a new layer above the Folder 1, I can simply collapse the Folder 1 and create it, but if I do the same steps in Photopea, the new layer would be created above the Layer 1.

**Comment by photopea** [comment]
fixed :)
