### ISSUE TITLE
Keywords searching doesn't work in installed "Unsplash Images" plugin

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#4545]
Everything is in the title. It doesn't work for me in installed PWA on Chrome and Firefox too

**Comment by photopea** [comment]
The Unsplash is a really bad service. They limit us to have at most 50 requests per hour, and I guess it gets used pretty quickly.

@hxim Could you create a plugin with Unsplash images? They can increase the traffic to 5000 requests per hour, but you must go through some confirmation process. I was too busy to study it all.

**Comment by photopea** [comment]
I will close it for now.
