### ISSUE TITLE
photopea project by Kayyy

### ISSUE THREAD

**Issue by dripps05** [photopea/photopea#4546]
![Screenshot 2022-04-27 8 10 49 AM](https://user-images.githubusercontent.com/104504483/165516648-76fd558f-4abd-42db-a369-97ada568a6eb.png)
This was completely colored in all nice and neat and it bled and faded it was one solid color with pink and it did that how do I fix it?

**Comment by photopea** [comment]
Did you save your work as JPG? JPG is only for photographs (of a real world). Save these "cliparts" as PNG.

To fix these artifacts, try Image - Reduce Colors. It will turn bright gray to white, drak gray to black, etc.

**Comment by dripps05** [comment]
its not a real life image its an anime drawing thingy should i still save it as a JPG?

**Comment by photopea** [comment]
It is not a photo of a real person, so do not use JPG! Save it as a PNG. Here is a diagram:
![EQpsKKMWsAAhV_S](https://user-images.githubusercontent.com/15955558/165519198-a737a030-7679-4044-909e-4c844675ac2f.jpg)

**Comment by dripps05** [comment]
Ok! Thank you!!!
