### ISSUE TITLE
Multiple Shapes in Unite mode don't apply their stroke correctly

### ISSUE THREAD

**Issue by Teh-Mad-Cow** [photopea/photopea#4547]
![image](https://user-images.githubusercontent.com/5084133/165811760-d115904c-0630-4e10-af28-c0e61885e4a5.png)
Up until April 27th, photopea would generate the expected output. But now it draws the stroke irrespective of overlapping shapes. Also for some reason adding a shape in subtract mode to this makes it go back to the expected output.

**Comment by photopea** [comment]
There was an issue from @TheRadicalDreamer, which I have fixed on 27th of April.

I have fixed this, and broke that issue from @TheRadicalDreamer. @TheRadicalDreamer, could you remind me what it was, so that I try to fix both at once?

**Comment by TheRadicalDreamer** [comment]
My issue was that i wanted to SHOW the lines of the shapes, like the "actual" example.

But at the end. What I did was to separate milimetrically the shapes in order to show the strokes.

When the shapes overlap. They get their strokes "substracted". So, maybe you should move the shapes a little to the center.

It is always good to upload the psd @Teh-Mad-Cow 

Can you upload it?

**Comment by photopea** [comment]
@TheRadicalDreamer I mean another issue that you had recently, I cant remember what it was. But you will see it once and you will report it again :)

**Comment by TheRadicalDreamer** [comment]
XD

Expect me to report. Totally

![New Project](https://user-images.githubusercontent.com/11801254/165860609-a5df5db4-d923-426d-b1ad-7cd45a9b6044.png)

**Comment by Teh-Mad-Cow** [comment]
I didn't save a psd of it when the issue existed, but I recreated it if you still wanted to see how it was organized.
[issue 4547 example.zip](https://github.com/photopea/photopea/files/8587186/issue.4547.example.zip)

Hope your issue doesn't crop up again, mate.

**Comment by photopea** [comment]
As I said, it is fixed.

**Comment by Teh-Mad-Cow** [comment]
I know, sorry I was just replying to missed notifs. Thank you for how timely you resolved this.
