### ISSUE TITLE
Export not working with Chrome Browser on iPhone

### ISSUE THREAD

**Issue by angeloruggieridj** [photopea/photopea#4548]
Hi, i write the steps to reproduce the problem:

1. Open file .PSD
2. Edit
3. Save as .PNG (or .JPG)
Any pop-up is available to start the download. During the request, there is the loading bar but nothing else.

Tested with Incognito mode and also with Normal session.
With Safari browser, with the same steps, it works.

Other info: iOS 15.4, Chrome v.100

**Comment by photopea** [comment]
Apple does not allow any other browsers to run on iOS. Every browser in the iOS is running on top of Safari. So only Apple can decide how the websites look and work in iOS.

I think Apple does not allow other "browsers" to use the Download feature. Opening Photopea directly in Safari is the best thing you can do at the moment.
