### ISSUE TITLE
Text just disappear on Mobile when I want to edit text-area

### ISSUE THREAD

**Issue by angeloruggieridj** [photopea/photopea#4549]
Hi, i write the steps to reproduce the problem:

1. Open file .PSD (it loads all fonts used)
2. Edit the first text-area (for example, that use OpenSans font)
3. The text that is in that area just disappear. The text is editable but transparent.

Tested with Incognito mode and also with Normal session, on Chrome and Safari, same behaviour.
Tested on Mac, with Chrome browser and same PSD File, it allows to edit text-area without problem because it converts missing font with another font. The process that converts text in another font is not working on mobile.

**Comment by photopea** [comment]
I have a feeling like your problem happens only on an iOS device, is that right? You did not mention it in your steps!

**Comment by angeloruggieridj** [comment]
Yes, only on iOS device (it doesn't matter if you're on Safari or other browser, the behaviour is the same).
I've partially solved using Font Upload function and added the missing font before edit text.

Now the problem is the following: Does Photopea remember font upload after a refresh (or a new PSD File upload)? Is it available with registered users?

**Comment by photopea** [comment]
I have to close it because of lack of details.
