### ISSUE TITLE
"Single-click on canvas with shape tools" can only create shape

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4551]
We are not able to create path or pixels by this way. It always create a shape no matter what mode is selected.
![image](https://user-images.githubusercontent.com/79258245/165935491-9797e061-4ffa-4073-84bf-34afcc62f3a8.png)
![image](https://user-images.githubusercontent.com/79258245/165935659-ea757913-394f-4ad3-b72a-419a27c7a8b9.png)

**Comment by photopea** [comment]
It should be implemented now.
