### ISSUE TITLE
AD block issue

### ISSUE THREAD

**Issue by QuanilCZ** [photopea/photopea#4552]
I want to know why is photopea saying to me "do you have an adblocker on?" Yes I have it, but It's turned off on photopea permanently. I think it is a bug or something and it makes me feel bad even though it's turned off. Nemám mluvit Česky spíš...
![Bez názvu](https://user-images.githubusercontent.com/104645457/165991203-635b5205-279c-4fa8-a000-125c87bcdae7.png)
![Bez názvu1](https://user-images.githubusercontent.com/104645457/165991350-08649e77-ae13-456b-a8ab-8be1a0e277cd.png)

**Comment by litemotiv** [comment]
I'm sorry to report i have the same issue on my browser (Brave), it has an internal adblocker but it's disabled for photopea.com. I have no other extensions installed. The 'ad blocker' popup started showing just recently, but i don't think i have any other settings i can disable.

**Comment by QuanilCZ** [comment]
@photopea On other pages where i have it disabled etc. Youtube ads are poping up normaly and it should be same here and I don't know why it's not working here. I tryied to disable all of my extensions ( I have 3) and after enabling AD blocker and allowing ADs on photopea I got the same result

**Comment by photopea** [comment]
What if you disable all your extensions, without enabling the ad blocker? Do you finally see ads on the right side of Photopea.com? The ad might look like the one below. The ad for Photopea Premium means you have an ad blocker.
 
![image (4)](https://user-images.githubusercontent.com/15955558/166111612-28bf792f-0d61-43e5-8e0b-513c62568adb.png)

**Comment by photopea** [comment]
@litemotiv I think Brave is still blocking some domains in your case. If you don't know how to disable it, try another browser. Or ask at some Brave forum.

**Comment by photopea** [comment]
@QuanilCZ I think your adblocker is lying to you. If Photopea can still detect, that a certain extension is enabled, it means that this extension is still "doing something", what allows a website to detect it. When an extension does nothing to a website, a website can not tell if it is enabled or not.

**Comment by litemotiv** [comment]
> @litemotiv I think Brave is still blocking some domains in your case. If you don't know how to disable it, try another browser. Or ask at some Brave forum.

It appears the UniConsent script is being blocked, apparently Brave deems this to be privacy infringing.

**Comment by impressivewebs** [comment]
FYI same problem here. My Photopea hasn't shown ads for some time now, and I'm using Brave. Interestingly, if I use a private window with no extensions running, the ads show up normally. I'll have to go through my extensions one by one and see which one is causing the problem, but it does seem to be a Brave-specific issue.

**Comment by photopea** [comment]
Keep in mind, that when there is "something" removing ads from websites for you, that "something" must go through every word of text and every image you ever see on the web, on all websites. That pretty much corresponds to another person standing next to you and looking at your screen. The scary part is, that so many people are not aware of having such "something" on their computer :(

**Comment by photopea** [comment]
Although, the necessary permissions you give to each extension don't look that scary at the first sight
![image (5)](https://user-images.githubusercontent.com/15955558/166126662-c4efaf81-1367-4ccd-a697-7f2efbd84ed9.png)

**Comment by litemotiv** [comment]
@photopea what's being blocked on some of our browsers is not the ads themselves but the UniConsent script that is trying to profile and track us using 'precise geolocation data', and then share that information with **850+** third party marketing providers. 

![image (5)](https://i.imgur.com/CplrN9y.png)

I invite people to click around through the settings of that script and see how ridiculously complicated it is to disable any advanced tracking being done, including the list of marketing providers personal data is being shared with. 

Disabling any of this requires manually deselecting each single one of the 850 marketing partners individually (!), which is obviously something nobody will ever be able to do. 

![image](https://i.imgur.com/mJcaf5W.png)

It's just an evil tracking script trying to disguise itself as a friendly consent popup, i can understand why my browser wants to block it.

**Comment by photopea** [comment]
There are many parties, which "compete" for the displaying of an ad to you. A message "IP address 231.12.43.171 is visiting www.Photopea.com right now, how much could you pay for showing them an ad?" is sent to many parties, and they all respond with a bid, the highest bid wins.

A webpage cannot know anything about you, your name, address, phone number, or the content of your hard drive. A website can not know your location or GPS. The only thing they can know is that a specific IP address visited Photopea at a specific moment.

**Comment by photopea** [comment]
Sending a message from one IP address to another is the basis of the internet. If don't want a website to know your IP address, you should send requests through another IP address, e.g. using a VPN.

**Comment by litemotiv** [comment]
@photopea when someone does go through the trouble of disabling everything in the UniConsent preferences, then the result is basically an adblocker, leaving an empty ad-frame on the page. Below is a screenshot from vanilla Edge without any extensions, where every option in UniConsent is disabled:

![img](https://i.imgur.com/FUEfLce.png)

For Photopea this is a worse outcome than if the UniConsent script is blocked but the 'Support Photopea' banner is still visible, right? 

IMO the sensible approach would be that if either the tracking is disapproved or the UniConsent script is blocked as a whole - which is basically the same as saying 'no consent' - then Photopea could just show anonymous ads. 

I do want Photopea to make money, but i don't want to spend my time figuring out opaque consent systems to see what kind of personal data they are trying to collect and share with third parties.

**Comment by photopea** [comment]
@litemotiv I think my current ad provider does not offer any ads in such case (when you refuse anything). So what you are doing is fine for us.
