### ISSUE TITLE
Can't install a second time the app on mac

### ISSUE THREAD

**Issue by UrNicePeople** [photopea/photopea#4553]
When you install the first time the app it works, but if you delete it and try to go "more" and "install Photopea", you cannot click anymore on it to install. 

I removed this app by mistake and now it seems like I can't download it anymore. 

Thanks ! 
<img width="224" alt="Capture d’écran 2022-04-29 à 20 17 59" src="https://user-images.githubusercontent.com/104649010/166000891-c74422d1-ce20-449a-bd8f-655ccd77f2c8.png">

**Comment by photopea** [comment]
It all depends on a specific browser and OS that you use.

Is it Chrome? I think Chrome still considers it to be installed. Try to uninstall it in about://apps
