### ISSUE TITLE
Website (photopea.com/learn) responsive issue in mobile?

### ISSUE THREAD

**Issue by zcraber** [photopea/photopea#4554]
Frome Chrome browser in Android.

![Screenshot_2022-04-30-13-41-05-006_com android chrome](https://user-images.githubusercontent.com/61133303/166097732-4fc197f3-0b42-412c-85c6-ab7d3811257b.jpg)

**Comment by photopea** [comment]
I dont think there are many people trying to read it on such tiny displays.

How do you think it should look instead? I dont think we can come up with a way to display it on a tiny screen properly.

**Comment by zcraber** [comment]
> How do you think it should look instead?

I think you can reveal it from the side using a toggle button for mobiles.

**Comment by photopea** [comment]
I think it would be better if you read it in the landscape mode.
