### ISSUE TITLE
A lot of items in menus are not disabled when they are unavailable

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4555]
They should be disabled to indicate what are unavailable in the situation.
![image](https://user-images.githubusercontent.com/79258245/166099421-fade5910-55d6-4402-8b95-0b0aa7233d57.png)

In addition, a item with sub-menu should be disabled if all items inside the sub-menu of that item are disabled.
![image](https://user-images.githubusercontent.com/79258245/166099440-aaa0f569-5bfb-47df-bc4e-2ce24d1bb877.png)

**Comment by photopea** [comment]
I have disabled elements, which require an opened document to work.
