### ISSUE TITLE
I can't install photopea on my PC and im sad ;-;

### ISSUE THREAD

**Issue by 007serialgamer** [photopea/photopea#4556]
Hello i wanted to install Photopea on my pc for do a Minecraft ressource pack easier but i can't because i can't click on the button
can i get help please
![image](https://user-images.githubusercontent.com/92458058/166106008-561b13b1-eb25-4b27-8218-1f3105dd4f8f.png)

**Comment by photopea** [comment]
This works only in Chrome and Edge now :(

If you still have problems, open about://apps and uninstall it there first.
