### ISSUE TITLE
Documents do not save

### ISSUE THREAD

**Issue by m1chaelog** [photopea/photopea#4557]
When I save a document, it shows the saving message, then goes away, like it normally does. However, when you try to close the document or tab, it says unsaved changes. Then when you try to open the file from downloads or google drive, it says unknown file format.

![image](https://user-images.githubusercontent.com/86570620/166116906-a7ec9285-d90a-4ba0-a21a-2d5e40cea01a.png)

**Comment by photopea** [comment]
Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by m1chaelog** [comment]
My browser is up to date and I've tried opening other documents that I saved before yesterday and they all work. This specific document is when the problems started happening.

**Comment by photopea** [comment]
The error in your screenshot means, that you are opening a file, that is 0 Bytes large (empty = no data).

Did you try to save a PSD file more than once, and it always results into saving a 0 Byte file?

**Comment by m1chaelog** [comment]
whenever I saved it, it just showed saving..., which it normally does

**Comment by photopea** [comment]
How large are the files which you can not open? are they 0 Bytes?

**Comment by photopea** [comment]
The only explanation I have is, that you closed Photopea before the saving process finished, and the PSD file in your computer turned out to be 0 Bytes.

I will close it for now. If you can tell us, how to make Photopea produce a 0 Byte file, other than closing it too soon, I will reopen it and will examine it.

**Comment by m1chaelog** [comment]
k thanks
