### ISSUE TITLE
Request failed to save file, even tho I have set   "Access-Control-Allow-Origin: *" on CORS

### ISSUE THREAD

**Issue by guillermoFragachan** [photopea/photopea#4558]
Well the issue is the following, I am trying to save a file from the playground to my local enviroment, and for some reason the request fails from the Photopea dommain is the one making the request, I have tried fetching from other website in the console and it just works fine, but seems to fail on Photopea (even if i do not use the "save" feature and only make a normal fetch GET request from the console),

CORS options are set as:
`expressApp.use(cors())`

I get a normal response when fetching anywhere else but in photopea i get this: 

![image](https://user-images.githubusercontent.com/3945636/166137320-b1679a44-82c9-4ff2-a94e-f08f01f08a43.png)

The request is not even processed in the console as other websites where I have tried the same fetch request

**Comment by photopea** [comment]
By "fetching", you mean Photopea sedning data to your server in a HTTP request? Are you sure that all responses from your server contain correct CORS headers?

**Comment by guillermoFragachan** [comment]
> 

Exaclty, I mean that the request to my server is failing, i have set the response of the endpoint to be "Access-Control-Allow-Origin: *", but the request is not even processed on the server console, while from other websites works well

**Comment by photopea** [comment]
Could you send me a link, where I can test what you have and check the CORS headers of the response of your server?

**Comment by photopea** [comment]
I have to close it because of no response from the author.
