### ISSUE TITLE
Unable to store response from saveToOE 

### ISSUE THREAD

**Issue by guillermoFragachan** [photopea/photopea#4559]
I have been yesterday trying different things with the API, most of those test has been made from the console, I was wondering if there
my first thing is that i get two responses, one with an array buffer which i guess is the correct and another on just with data "done", if someone could explain me this, it would be very helpful: 
![image](https://user-images.githubusercontent.com/3945636/166138005-b2b03c1c-9968-48fe-8232-a31bf6001667.png)

Now the real problem is that when i am trying from the dev Console of Chrome to get the response as a variable I am not able to access the object with the following code:

`var array
 window.addEventListener("message", function(e) { array = e.data; });
var wnd = document.getElementById("pp").contentWindow;
console.log(array)`

The code above just returns "undefined"

I have tried many other things with Scripts, etc . but I have not been succesful to get the binary on the outer enviroment

**Comment by photopea** [comment]
Please, read our API: https://www.photopea.com/api/. 

The "done" message is described here: https://www.photopea.com/api/live

We can not provide you any assistance, if you are running your own scripts on www.Photopea.com. You should use Photopea only according to our API.

**Comment by guillermoFragachan** [comment]
Yes that is understandable but this piece  of code is taking form the API documentation `var array window.addEventListener("message", function(e) { array = e.data; }); var wnd = document.getElementById("pp").contentWindow; console.log(array)`

I just change the alert to a variable, I was just wondering if there is a way to get the BLOB on the outer system since I am not able to make a request to the server I was looking for an alternative

**Comment by photopea** [comment]
You must be able to make requests to any server.

Could you show me a link, where I can test what you have? I bet you did not set the CORS headers rigth.

**Comment by photopea** [comment]
I have to close it because of no response from the author.
