### ISSUE TITLE
bitmap tracing feature request / idea proposal

### ISSUE THREAD

**Issue by illucent** [photopea/photopea#456]
functionality like implemented here https://online-converting.com/autotrace/

**Comment by photopea** [comment]
I had an idea about this feature a long time ago. Let's call it "raster to vector" :)

We already can do raster quantization (reduce the number of colors in a nice way) - you can see it in a PNG export. We can also convert polygons to bézier curves (Free Pen tool). So we just need to connect it together.

**Comment by photopea** [comment]
Why did you close it? Let me close it once it is done :)  In which menu would you place this function?

**Comment by illucent** [comment]
I think it would be logical to place under menu "Image": "Image->Trace to SVG".

**Comment by photopea** [comment]
This method could be used to convert real videos into cartoons.

**Comment by illucent** [comment]
I've came across another similar tool http://www.samcodes.co.uk/project/geometrize-haxe-web/

**Comment by photopea** [comment]
My bunny is better now!  http://svgur.com/s/5W9   but still, eyes are not perfect circles.

**Comment by photopea** [comment]
Ok it was implemented, see here: https://blog.photopea.com/vectorize-bitmaps-in-photopea.html
