### ISSUE TITLE
A fill style is set before creating shape, but the shape will still be without filled

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4560]
to reproduce
1. Create a shape without filled.
2. Create a new blank layer.
3. Set a fill style on top bar. 
4. Create a shape.

The shape created in step 4 is without filled, though a fill style was set in step 3. It seems to be that if the last activated shape layer is without filled, the new shape will still be without filled even you set a fill style before create the new shape.

**Comment by photopea** [comment]
fixed!
