### ISSUE TITLE
The thumbnail of shape without filled and stroke is filled

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4561]
![image](https://user-images.githubusercontent.com/79258245/166140629-879d0176-0dc0-4538-be13-c45c97a4192c.png)

**Comment by photopea** [comment]
fixed!

**Comment by nothingshiru** [comment]
I find thumbnail of shape without filled is blank, even it has stroke.
![image](https://user-images.githubusercontent.com/79258245/166231012-11587258-0987-4258-95cc-7e018936c46c.png)

**Comment by photopea** [comment]
fixed!
