### ISSUE TITLE
Photopea is whitelisted and I see ads, but I still got the guilt-trip messages

### ISSUE THREAD

**Issue by osama-h-rana** [photopea/photopea#4563]
As you can see in the screenshot, I have this website whitelisted for ads (denoted by the green thumb). I can also clearly see the ads on the right for photopea premium. Am I doing something wrong?

![ads](https://user-images.githubusercontent.com/13495205/166150447-070ecf96-ad64-49b9-a6a7-d539b5f35a44.png)

**Comment by photopea** [comment]
Ads for Photopea Premium is displayed only when the ad blocker is detected.

I dont know how to disable the ad blocking in your case :( Could you try Photopea in the Incognito window?

**Comment by photopea** [comment]
I wrote this tutorial for you: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by osama-h-rana** [comment]
I'll see if I can reliably repro the issue and report back
