### ISSUE TITLE
Auto-Select checkbox issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4564]
Auto-Select checkbox is always automatically checked after I use Free Transform. I need to uncheck it every times which is very annoying.
1.) I have Move Tool selected and Auto-Select is unchecked.
![image](https://user-images.githubusercontent.com/6370548/166154185-fd484466-2b2c-4eca-be6c-d48b8c22a93e.png)
2.) I press CTRL+ALT+T to do Free Transform. I move or resize layer and confirm with button in top toolbar.
![image](https://user-images.githubusercontent.com/6370548/166154213-fe848cc7-1b3c-42f9-a3b3-c253239714bc.png)
3.) Auto-Select is now checked for no reason.
![image](https://user-images.githubusercontent.com/6370548/166154221-e7e0474f-0b99-44c2-bc96-60c626018129.png)

**Comment by nothingshiru** [comment]
This bug also occurs when press <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>C</kbd>/<kbd>I</kbd>/<kbd>N</kbd> to open a dialog then close it by click on the "X". If I press <kbd>Esc</kbd> to close the dialog, there is no such a bug.

**Comment by photopea** [comment]
it should be fixed for Ctrl+T . This checkbox does not have any effect on the functionality and will be updated when you press any key, or switch tools.
