### ISSUE TITLE
Website keep crashed 

### ISSUE THREAD

**Issue by mrhill090988** [photopea/photopea#4565]
Anything I do on our guys website its just crashed  can you please fix this so people can use its to design stuff like myself. Thanks you. Remember you guys made the site so fix its

**Comment by photopea** [comment]
What should I do to make Photopea crash? It never crashed in my case :( Are you running it on a phone from 2011 or something?

**Comment by photopea** [comment]
I think your phone is not powerful enough for the kind of work you are doing. Try to save your work as PSD more often, or get a more powerful device.

**Comment by mrhill090988** [comment]
It's kinda funny you all think am using my phone, you think am that dumb well am not. And photopea you here to help people not to being people down, I make sure I to something about.

**Comment by mrhill090988** [comment]
> I think your phone is not powerful enough for the kind of work you are doing. Try to save your work as PSD more often, or get a more powerful device.

Who said I was using a phone in the first place, not me!!!

**Comment by mrhill090988** [comment]
> What should I do to make Photopea crash? It never crashed in my case :( Are you running it on a phone from 2011 or something?

I don't think I said that, I was saying its was crashing all the time, its your guys time to fix your website. And by the am not using a phone so you really don't need to be a smart ass "PHOTOPEA" I make sure to put bad reviews out on you guys!!!!

**Comment by photopea** [comment]
There are 3 million people using Photopea and nobody reports any crashing.

Could you tell us what kind of device are you using, and how much RAM does it have? We need to make Photopea crash ourselves somehow, to experience the problem first.

**Comment by photopea** [comment]
Also, the majority of our users runs Photopea on phones.

**Comment by mrhill090988** [comment]
> There are 3 million people using Photopea and nobody reports any crashing.
> 
> Could you tell us what kind of device are you using, and how much RAM does it have? We need to make Photopea crash ourselves somehow, to experience the problem first.

You telling me no one have reported to you guys that photopea have not crash, I show a post yesterday someone was having the same issue but you guys have over 300 million people using your site and you have to be rude like this wow, awesome company. Oh ya update its had the crash anymore since I post my first comment so its fine now.
