### ISSUE TITLE
Photopea freezing for about 2 to 3 minutes.

### ISSUE THREAD

**Issue by ajfreelancer** [photopea/photopea#4566]
Last week, I started to face this problem. Every time I select the brush and click on the top left to change its size, it gets stuck for 2 to 3 minutes. And when it's hung up if I try to do anything, Chrome says the webpage isn't responsive, do you want to close it or Wait.

Please guide me. Am I doing anything wrong? For reference, I haven't tried anything new to my browser in the past week or added any extension.

**Comment by photopea** [comment]
Hi, is it one of the basic Photopea brushes? Or what brush are you using?

I need to make the problem happen on my computer. Could you tell me what should I do to make it happen myself? I tried many brushes, but it never froze.

**Comment by ajfreelancer** [comment]
Thanks for the response. Yes, it's the default brush that appears when I click on the brush from the toolbar. It never happened before a week.

My laptop's RAM is 8GB. Does that get to do anything with it? But if that was the problem it should have always been there.

**Comment by photopea** [comment]
Did you try to close your browser and open it up again? Did you try these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by ajfreelancer** [comment]
Yes, I have closed the browser and opened it again but it has occurred several times. I'll try the steps mentioned in the link you sent. Thank you so much for your concern.

**Comment by photopea** [comment]
I have to close it because of no response from the author.
