### ISSUE TITLE
Unable to run the PSD template

### ISSUE THREAD

**Issue by saifeddinetrabelsi** [photopea/photopea#4567]
<img width="839" alt="Unable to run the PSD template" src="https://user-images.githubusercontent.com/104760593/166211357-692ac31f-625a-4945-b282-86b3dc97fe59.PNG">

Bonjour,

je voulais savoir pourquoi, la Template ne peux pas se lancé .

Toujours bloqué au niveau du chargement.

Merci de m'aider svp

**Comment by photopea** [comment]
Are you opening a template form free PSD templates? Or your own file?

**Comment by saifeddinetrabelsi** [comment]
Merci pour votre réponse 

Oui, comme d'habitude je suis aller à cette page :
https://www.photopea.com/templates/c-mockups
par la suite je choisi un modèle OSD mais la page reste loqué sur " Chargement" .

J'ai essayé avec un autre PC et ca fonctionnait correctement.

Je ne sais pas pourquoi ca ne fonctionne pas avec cet ordinateur alors que je l'utilise souvent .

**Comment by photopea** [comment]
Sorry, I don't speak French :( Ask some of your friends to report it in English.

**Comment by photopea** [comment]
Try these steps: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

Try to disable all your browser extensions.

**Comment by saifeddinetrabelsi** [comment]
Thank you for your answer

Yes, as usual I went to this page:

https://www.photopea.com/templates/c-mockups

then I choose a PSD template but the page remains locked on "Loading".

I tried with another PC and it worked fine.

I don't know why it doesn't work with this computer when I use it often.

I also tried this link you sent me: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/
but it still doesn't work.

**Comment by photopea** [comment]
Have you tried it in the Incognito mode? Does it still dont work?

**Comment by saifeddinetrabelsi** [comment]
How to use Incognito mode please?
Thank you in advance

**Comment by photopea** [comment]
https://www.computerworld.com/article/3356840/how-to-go-incognito-in-chrome-firefox-safari-and-edge.html

**Comment by saifeddinetrabelsi** [comment]
I tried in Incognito mode but it doesn't work.

I don't know why this error occurred, because I use photopea every day and it works perfectly well.

But since this morning every time I want to use the PSD mode, I choose the model I click OK.

I would have this page stuck in loading.

![image](https://user-images.githubusercontent.com/104760593/166256014-b101539d-8e62-430b-a03a-8b5b00a54480.png)

**Comment by photopea** [comment]
Could you tell us which PSD template are you opening?

**Comment by saifeddinetrabelsi** [comment]
all PSD templates
I tried today too, cleared the browser cache and reset it but I still have the current loading page?

**Comment by photopea** [comment]
Can you access Backblaze? That is where we store all our templates  https://www.backblaze.com/

**Comment by saifeddinetrabelsi** [comment]
Yes I can access

**Comment by photopea** [comment]
Can you right-click Photopea and choose "Inspect Element", switch to "Console". Do any errors appear there when you try to open a template?

**Comment by saifeddinetrabelsi** [comment]
no error.

every time I access a PSD model, the page is stuck on loading, that's all

**Comment by saifeddinetrabelsi** [comment]
![image](https://user-images.githubusercontent.com/104760593/166670351-f0fc5567-6366-47c1-9c06-97ce94ff7958.png)

**Comment by saifeddinetrabelsi** [comment]
![image](https://user-images.githubusercontent.com/104760593/166670512-e2342f56-064b-4f60-a046-9183cf8f9ea7.png)

**Comment by saifeddinetrabelsi** [comment]
![image](https://user-images.githubusercontent.com/104760593/166670717-00087671-0a9a-4c4c-904b-db3f32a11cab.png)

**Comment by photopea** [comment]
Your browser can not load the file from Backblaze.

Can you download this file? https://f000.backblazeb2.com/file/psdshared/70imObZ3 . You should be able to download a file, that is 43.5 KB in size.
