### ISSUE TITLE
No abilty to scroll across project when zoomed in

### ISSUE THREAD

**Issue by AMR01110011** [photopea/photopea#4568]
It's really not a bug, but it would be nice to be able to scroll across a project without needing to switch the the Hand Tool. Adding vertical and horizontal scroll bars to the work area would solve this problem.

**Comment by photopea** [comment]
There are at least 5 other ways how to "scroll", see https://www.photopea.com/learn/navigation

**Comment by photopea** [comment]
I have to close it because of no response from the author.
