### ISSUE TITLE
Open From Drive Always asks for connect

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4569]
Everytime i open Photopea and it has been closed for a while i have to connect my google account again.

I can repro everyday, but still i don't know how much time it has to pass or what condition have to be met.

**Comment by photopea** [comment]
Are you using any browser extensions that could clear cookies?

@dobrichovsky do you know how long the access tokens usually last?

**Comment by TheRadicalDreamer** [comment]
![image](https://user-images.githubusercontent.com/11801254/166562489-b2e0ca44-4e3e-4589-82f3-ddb9e837d4b5.png)

Not really

**Comment by photopea** [comment]
But a new logging in is like two clicks, right?

**Comment by photopea** [comment]
BTW. do you know what your "google docs" extension do? Did you see any differences when you uninstall it? Google docs work without any extensions.

**Comment by TheRadicalDreamer** [comment]
Yes, it only 2 clicks, but i am worried anyways.

My extension let me edit my google drive files offline:
https://chrome.google.com/webstore/detail/google-docs-offline/ghbmnnjooekpmoecnnnilnnbdlolhkhi

**Comment by dobrichovsky** [comment]
Hi @TheRadicalDreamer, access tokens (a kind of code the storage gets from Google after authentication, which is then used to directly access your files) should be valid for one hour, and after that our storage has to reauthenticate and request a new one from Google - but if you are logged into your Google account in your browser, when you click "load storage", the storage should just open a pop-up window to the Google's authentication page and that should handle the fact that you are already logged in to your Google account and not require you to re-enter your password, or to grant access to Photopea again - but you will have to choose which Google account you want to use. This is a design/security measure by Google drive and more or less all other services, as we have no way of keeping an access token securely - it is only stored in your browser, and therefore expires quickly to prevent potential misuse.

**Comment by photopea** [comment]
@dobrichovsky so is it a bottle neck at our side or at Google? If we are introducing any "security limitations" ourselves in this cases, we should definitely remove them.

When the user re-opens storage, could we get new access tokens "under the hood", without showing the login window?

**Comment by dobrichovsky** [comment]
It's Google's (and the same goes for Drobpox and Onedrive and everyone else) - because we have everything in JS, we cannot use the authentication flow via refresh tokens (the "client secret" - unique to the OAuth 2.0 Client ID that we use - is required to verify that it is us making the request - this would have to be server-side as this secret cannot be exposed in JS). Unfortunately we always have to show the login window, that is the only way of getting access tokens purely through JS.

**Comment by photopea** [comment]
I still do not fully understand. If this client secret is is unique for each user, there should not be a problem to store it in cookies. In the worst case, the user can only get access to their Google Drive, nothing more, right?

**Comment by dobrichovsky** [comment]
No, the client secret is the "client" secret of our Google app - you'll find it in the Google Developer console under Credentials -> OAuth 2.0 Client IDs - if you click on the the ID that we use for authentication, it's there on the right as "Client secret". It is used when authentication is done server-side, where it can be stored securely, like that you can request a long term access token and a refresh token, but we can't do that client-side in JS.

**Comment by photopea** [comment]
I will close it now, as it is a limitation of Google, not of Photopea.

**Comment by TheRadicalDreamer** [comment]
No, only 2 that totally do not interfere.
[image: image.png]

**Comment by TheRadicalDreamer** [comment]
Thanks for explaining it all.

What you described is exactly what happens to me.

I get now why it is, i get how unsecure could be giving the secret on JS,
it is potentially stolen by any extensión or script in any site.

So, it is not a limitation, but a protocol.

I can rest now :)
