### ISSUE TITLE
ads

### ISSUE THREAD

**Issue by skywalker005** [photopea/photopea#4572]
the ads, especially videos, that change every 30 or so seconds are website breaking.  my browser will just freeze because of all the ads, and in turn i can't do anything.
i enable ad blocker, i get slammed with these every 30 seconds instead.
if the ads didn't make the site unusable, i would leave them on.  can the ads be fixed in any way?
![Screen Shot 2022-05-04 at 6 09 14 PM](https://user-images.githubusercontent.com/101187093/166834231-a23e26fc-57d0-41cc-9e85-f851ddb8c0e8.png)
![Screen Shot 2022-05-04 at 6 09 19 PM](https://user-images.githubusercontent.com/101187093/166834232-d13e2b95-4a12-4449-ac34-9172ee82e4cb.png)
![Screen Shot 2022-05-04 at 6 09 28 PM](https://user-images.githubusercontent.com/101187093/166834234-aecdea60-39e4-4661-9093-fc2436c4eec6.png)

**Comment by photopea** [comment]
The ads should never slow down Photopea. Could you record a video of what ads do you see? Or provide some other proof that they slow down Photopea?

**Comment by TerrorTerror13** [comment]
I'm having the same issue. There is a constant video ad that is attempting to run on the right-hand side of the workspace.

**Comment by photopea** [comment]
Video ads do make us more money. But they should not be displayed too often, or slow down the computer.

**Comment by skywalker005** [comment]
Couldn't add videos to the email, let's see if this works.

https://user-images.githubusercontent.com/101187093/167540552-d864d6ab-14f8-4f54-9216-4edead290f91.mp4


https://user-images.githubusercontent.com/101187093/167540554-2813b5c0-27e0-41d0-acee-cd3ace9ff149.mp4

**Comment by photopea** [comment]
That is unbelievably slow. Are all websites that slow? Could you press Shift+Escape to see what sites use the CPU?

I think you might have browser extensions which are mining bitcoins in the background. Could you disable all your extensions (in about://extensions) and try it again?

**Comment by skywalker005** [comment]
It's only photopea.
The only extensions I have are for discounts and ad / pop up blocking.
I also continuously encounter an issue where, no matter how many frames or how little editing, my gif frames get damaged.  And the site sometimes crashes my entire window.

**Comment by photopea** [comment]
When this happens, could you press the "three dots" of your browser, More Tools, Task manager? What websites use the most of your CPU at that moment? Could you show us a screenshot?

**Comment by photopea** [comment]
Also, how long has Photopea been opened? Do you close it at least once a day?

**Comment by skywalker005** [comment]
I close it after each use, which is pretty frequently.  I also close the entire browser frequently to try and avoid slowing & crashing.

This is the browser's CPU.
![Screen Shot 2022-05-11 at 10 55 34 PM](https://user-images.githubusercontent.com/101187093/167982944-a1c766ce-19b4-41ea-84a7-2df1096d2ef6.png)

**Comment by photopea** [comment]
No processes seem to slow down Photopea in your screenshot. Could you take a screenshot at the moment when Photopea is "frozen"?

**Comment by skywalker005** [comment]
But my computer and other websites aren't the issue.  Photopea is.  I've already stated it's the only website I use that causes crashing and freezing.  Someone else commented on this thread saying it happens to them too.

**Comment by skywalker005** [comment]
I don't know when it'll freeze again, and I can't click anything when it's frozen.

**Comment by photopea** [comment]
I really need some proof, that it is the ads that are slowing down Photopea, and not e.g. your extensions or some other computer program you use.

Could you make it freeze, and then, click into the address bar with "Photopea.com" and press Shift+Escape? That should not be frozen.
