### ISSUE TITLE
Ads Issues 

### ISSUE THREAD

**Issue by lukemax47** [photopea/photopea#4573]
My browser was blocking ads by default. Kept getting spammy popups to allow them. Allowed them yet still kept getting popups. Paid for membership and now I'm only able to export the image once. Then I have to close the tab and reopen it before it will let me save again. Please fix this bug it is really annoying.

**Comment by lukemax47** [comment]
After removing all browser stored settings, and reloading my browser it appears fixed. I had to reenable multiple downloads again.

**Comment by photopea** [comment]
Photopea checks for an ad blocker just once. If you disable it, reload Photopea.

"saving only once" sounds hard to believe. How can I make it happen?
