### ISSUE TITLE
Free Transform Bug

### ISSUE THREAD

**Issue by dankungdtw** [photopea/photopea#4574]
https://user-images.githubusercontent.com/104962864/166865065-f7d9af7c-f8bf-428f-8d80-a4f3734f64b5.mp4

**Comment by Morg19** [comment]
Having the same issues, It's not resizing like It's suppose too and I don't know how to make it stop

**Comment by photopea** [comment]
You should disable the aspect ratio lock (the chain icon at the top between "W" and "H").

Or just hold the "Shift" key to do the "squeezed" transform.
