### ISSUE TITLE
BUG Free Transform

### ISSUE THREAD

**Issue by dankungdtw** [photopea/photopea#4575]
https://user-images.githubusercontent.com/104962864/166875131-fde090bd-6cfe-43eb-85fd-1b0a8e24bae2.mp4

**Comment by photopea** [comment]
You should disable the aspect ratio lock (the chain icon at the top between "W" and "H").

Or just hold the "Shift" key to do the "squeezed" transform.

Did you try it?

**Comment by BisexualSimp** [comment]
Just wanna Report a Bug that deals with the aspect ratio feature, When I enable the feature it doesn't lock it

https://user-images.githubusercontent.com/86283395/166907174-96e43ac4-d490-4046-af09-d3a92c9ba33d.mp4

**Comment by youssef382** [comment]
when i hold shift the aspect ratio between height and width are not be the same 
pls try to solve this problem quickly because i need to finish my work

**Comment by photopea** [comment]
@BisexualSimp thanks, I have fixed it!

@youssef382 You should disable the aspect ratio lock (the chain icon at the top between "W" and "H"). Or just hold the "Shift" key to do the "squeezed" transform.

**Comment by youssef382** [comment]
thank you very much @photopea

**Comment by dankungdtw** [comment]
@photopea it worked thank u
