### ISSUE TITLE
cant open a PSD file

### ISSUE THREAD

**Issue by Bablox360** [photopea/photopea#4578]
Hi, I tried to open a PSD file that I created in photopea a while ago and whenever I try to open it, it says unknown file format.

**Comment by photopea** [comment]
How big is your PSD file? If it is 0 Bytes, you closed Photopea too early, before the file was properly saved. You shoud not close Photopea when there is a message "Saving ..." at the top.

**Comment by Bablox360** [comment]
The psd file is 306 kb

**Comment by photopea** [comment]
Could you share it with us here, so that I try to open it?

**Comment by Bablox360** [comment]
it says unsupported file type and I don't see PSD on the supported file types...

**Comment by photopea** [comment]
Github says that? Could you send it to me on a CD? I can write you my address.

**Comment by Bablox360** [comment]
sorry, do you mean a physical compact disc, sorry if that's a dumb question

**Comment by photopea** [comment]
Could you send it over an email to support@photopea.com ?

**Comment by Bablox360** [comment]
lemme try

**Comment by Bablox360** [comment]
thats wierd? it says in the files app that the file is 306 kb but in gmail it says that it is 0 bytes?

**Comment by Bablox360** [comment]
could this also be caused by saving all my files from one laptop and putting them onto a new computer?

**Comment by Bablox360** [comment]
AHA

**Comment by Bablox360** [comment]
it worked, 
thanks for all your help support person 🙏

**Comment by Bablox360** [comment]
I had to open the file and then re save-as and then dragged it into photopea.

**Comment by photopea** [comment]
Hi, you sent me a XCF file, that is 149 kB. Photopea can not create XCF files. I can open your XCF file in Photopea.

**Comment by Bablox360** [comment]
yeah i created it in photopea then saved it and when i reopened it after saving the first time, it opened in gimp, and when i re save as'ed it changed it to an XCF file and for some reason the size changed

**Comment by Bablox360** [comment]
this is the original file name for the PSD file
Aunt_Grizelda_in_The_Lorax (1) (5).psd

**Comment by Bablox360** [comment]
and this is the second one that I sent you
Aunt_Grizelda_in_The_Lorax (1) (5)
and the type of file was GIMP 2.10.20 (.xcf)

**Comment by photopea** [comment]
You sent me only an XCF file which works in Photopea. Please, send me a file which does not work in Photopea.

**Comment by Bablox360** [comment]
ah ok

**Comment by Bablox360** [comment]
it says it is 0 bytes when i try to send it in Gmail but in the file manager it says it is 306 KB

**Comment by yyc-crafts** [comment]
I've had the same issue with saving PSD files. If I try to save it to a specific location it doesn't save, but if I just save it to my download file, it'll save right away. I've lost a few PSD files before I figured this out. Many hours of work gone😩

**Comment by photopea** [comment]
@yyc-crafts Guys, please, let me know what should I do on my computer to get a damaged PSD file. Photopea never gave me a damaged PSD file. I need some proof, that it is really possible to make Photopea create a damaged PSD file.

I think you closed Photopea before the "Saving ..." message disappeard (saving did not finish), or you use browser extensions, which damage the downloaded files (including PSDs from Photopea).
