### ISSUE TITLE
Selecting more than one folder

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4581]
:/
https://user-images.githubusercontent.com/11801254/167028210-1ffa4914-3f31-419e-b736-bc673381b2f1.mp4

**Comment by photopea** [comment]
that is a correct behaviour.

Please, open all folders. Or imagine there are no folders. A layer is highlighted only when it is selected, not when the "parent" folder is selected.

**Comment by photopea** [comment]
Select multiple folders with Ctrl, not with Shift, if you dont want layers inside to be selected.

**Comment by TheRadicalDreamer** [comment]
Good to know! :)
