### ISSUE TITLE
Regarding Ads

### ISSUE THREAD

**Issue by AMR01110011** [photopea/photopea#4582]
If you would like people to watch your ads, I suggest not allowing any animated ads. Prior to my most recent project, I did not use an ad blocker on this computer. Then, when I was working in Photopea the other day, the adds kept flashing animations. This was extremely distracting. I'm sure you can understand that when working in a visual medium such as photography, it's very difficult to concentrate on your work when an ad keeps obnoxiously blinking at the edge of your vision. I downloaded an ad blocker because I couldn't concentrate on my own work due to the ads. 

I don't recall ever seeing animated ads on your site in the past, so maybe something changes with your ad settings. Should Photopea commit to not having animated ads, I will happily view them ionn the site, until then I need to have them off in order to complete my work. Thanks!

**Comment by photopea** [comment]
Hi, could you maybe record a video of such flashing ad? So that I have a proof for my ad partners and show it to them?

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by AMR01110011** [comment]
Yeah, I'll see what I can do. It probably won't be today, but I'll get to
it soon
