### ISSUE TITLE
agrandir une image

### ISSUE THREAD

**Issue by marchande5457** [photopea/photopea#4585]
Bonjour,

je n'arrive plus à agrandir une image en conservant les dimensions par la touche maj ou Ctrl.

I can no longer enlarge an image by keeping the dimensions by the shift or Ctrl key.

Estelle

**Comment by marchande5457** [comment]
I have spoke English in the texte

**Comment by photopea** [comment]
You can learn how it works here: https://www.photopea.com/tuts/new-free-transform/
