### ISSUE TITLE
new document

### ISSUE THREAD

**Issue by marchande5457** [photopea/photopea#4586]
Hello !

when I create a new document, I enter the size in mm: 297 then 210 and I change the dpi 250 and at that time the software changes me the millimeters. I do reentry 297 and 210

(je saisis la taille en mm : 297 puis 210 et je change les dpi 250 et  à ce moment là le logiciel me change les millimètres)

Estelle

**Comment by photopea** [comment]
When I enter a DPI in the New Document window, I do not see any millimeters. Are you sure you know how Photopea works? Could you record a short video of what you are doing?

**Comment by photopea** [comment]
I have to close it because of lack of details .
