### ISSUE TITLE
Weird Glitching in Photopea

### ISSUE THREAD

**Issue by Jykie** [photopea/photopea#4588]
Ok so since the day before yesterday, Photopea would suddenly become unresponsive and I wouldnt be able to edit even though I can still click on the other features.

At the start it happened once of twice between a few hours so I didn't think much about it, but now its happening just minutes after I start editing. 

I've already tried exiting out twice and the night before I had shut off my tablet but the problem still persists.

And now there's something wrong with the masking. Everytime I go to paint black it would go weird then fill the canvas with black. I've never had this happened before.

Here's two links of two recordings I uploaded on YouTube that will show what I'm talking about:

Masking Glitch: https://youtube.com/shorts/ukoiL0qJfe8?feature=share
Other Glitch: https://youtube.com/shorts/_rGQAwGDwwI?feature=share

**Comment by EcoShark** [comment]
Same here!

**Comment by photopea** [comment]
I need to make it happen on my computer myself shomehow.

When it happens, can you save your work as a PSD file and send it to me to support@photopea.com ? I will try to do the same thing, hope it will happen on my computer, too.

**Comment by Jykie** [comment]
I'm trying to send it but it keeps saying the psd file exceed the 25 MB total attachment limit. I don't know what to do. For reference, I'm using the Galaxy Tab S7 by Samsung.

**Comment by photopea** [comment]
Could you zip your PSD into a ZIP archive? Or use some onlin file sharing services?

**Comment by Jykie** [comment]
Ok, I just emailed you my psd files. Hope it helps

**Comment by photopea** [comment]
I have opened your file in Photopea, painted into a mask, but I can not see any strange behaviour.

In your PSD in the video, there is a face of a woman. But the PSD that you sent me is completely white (there is a white layer on top). Could you send me the exact PSD that you used in your video? Also, can you make sure after you open www.Photopea.com, select a mask and paint, that the problem happens every time?

**Comment by Jykie** [comment]
The white layer was their to help compress the file. Could you delete that layer and try again?

**Comment by EcoShark** [comment]
Sorry I haven't submitted any files for you to look at.  When the problem
came up a couple times, I just stopped using the site and didn't save
anything.

Thanks,

*Julie Shark | Founder | *www.EcoShark.net <http://www.ecoshark.net>

**Comment by photopea** [comment]
ok
