### ISSUE TITLE
pencil tool

### ISSUE THREAD

**Issue by ebdjesus** [photopea/photopea#4589]
when selected Pencil tool, Custom Brush and 10 px the size becomes smaller.
I've tried using Mozila and Chrome browsers and the same thing happens.

![photoshop](https://user-images.githubusercontent.com/51535131/167167718-23315447-ba1e-4fce-a980-0b0fd2d5e168.jpeg)

**Comment by photopea** [comment]
I tihnk the size "10" is the radius of the brush circle. A square needs to be inside a circle. So 10 is the diagonal of the square.

**Comment by ebdjesus** [comment]
@photopea Thanks, I just thought it was weird, because two weeks ago I used the square with 10 px and I was painting according to the screen pixels

**Comment by photopea** [comment]
The Size is always a diameter. It is a diagonal in case of the square brush.
