### ISSUE TITLE
Local Storage not working

### ISSUE THREAD

**Issue by maddicaddis** [photopea/photopea#4590]
I have a lot of things stored to my local storage on photopea - fonts, ASL files, things like that. but this morning they were all wiped - over 60 mb of data just gone. i tried reuploading everything (which took AN HOUR) and it didn't save any of them. this has happened to me multiple times over the years and i'm getting freaking sick of it!

**Comment by photopea** [comment]
I think you have browser extensions, which clear website data (cookies, local storage, etc). Are you using any browser extensions, which could do that?

Browser extensions are "stronger" than websites. Websites can not disable your browser extensions :(

**Comment by maddicaddis** [comment]
yes i do have browser extensions. i don't know which one of them would clear website data but i also have the photopea browser extension. should i just delete that?

**Comment by photopea** [comment]
We never made any Photopea browser extension, it is probably some virus.

I recommend disabling all extensions and enabling them only when you really need them. Check, what of your extensions have permissions to see and modify the content of websites.

**Comment by maddicaddis** [comment]
yes, i meant the app. i have a chromebook and i was able to get some form of a photopea app. i use the website more, though. I checked my browser and disabled my extensions and modified their permissions like you said, hopefully that works.

**Comment by photopea** [comment]
Ok, I will close it now. As I said, either you deleted website data yourself, or some extension on your chromebook deletes website data for you.
