### ISSUE TITLE
Using AdBlocker message pops up but ads are allowed and shown on screen

### ISSUE THREAD

**Issue by Beercules48** [photopea/photopea#4591]
Hi,
the message "accusing" me of using an AdBlocker pops up when I export files even though the AdBlocker is disabled AND the ads are clearly visible on screen.
Browser: Brave [Version 1.38.111 Chromium: 101.0.4951.54 (Official Build) (64-bit)]
Shields are down for photopea.com.
The issue started roughly two weeks ago if memory serves.
Screenshot of the message and the ads:
![image](https://user-images.githubusercontent.com/41172359/167213860-a94ca52d-0211-49c4-a06f-79e0d716bfd7.png)
While not impossible to use, that message is annoying and I really would like this issue to be fixed.
Thank you!
Edit to add:
No extensions that could conceivably block any ads are installed. I only use the built in capabilities of Brave and those are disabled. All cookies are allowed.

**Comment by photopea** [comment]
I dont know what is blocking ads in your case :( Could you try Photopea in the Incognito mode?

If you can not find the way to make Brave stop blocking our ads, maybe try a different browser?

There are millions of people who do not see this message about the ad blocker. So there must be something your browser is doing differently than other browsers. You need a browser which can run a website the way it was made, without changing anything.

**Comment by Beercules48** [comment]
Okay I tried some things, here is what I found: it works exactly once. When I clear all cookies and load photopea, it works. When I reload the page, it breaks, and the message pops up again. I haven't done anything but reload the page, didn't change any settings. Only thing I did was accept or reject the cookies when prompted. It doesn't change anything whether I accept all cookies, just some or reject all. When I reload or reopen the page, it stops working. Until I manually clear the cookies via the Brave settings, then it works again, once. All cookies are allowed in the settings.
In incognito mode the behavior is exactly the same.
Photopea.com is even additionally explicitly whitelisted in the Brave settings to accept all cookies, even third party ones.
Thanks for the very quick answer, that is much appreciated!

**Comment by photopea** [comment]
We test the presence of an ad blocker by trying to connect to certain domains. That means, that your browser is blocking certain domains. Or maybe it could be your firewall, your employer, etc.

Anyway, try Photopea in another browser to see what it is.

**Comment by Beercules48** [comment]
It seems to me that it is a problem with Brave's built in "second layer" protection against trackers and the like, over which I have no control. That I should be the only one experiencing this strikes me as odd, but I have accepted this as the cause. I submitted a "broken site with shields" report to the Brave developers.
Photopea works fine in Firefox, so I will use that for the time being. Slightly inconvenient, but that is not your fault. Thanks for the rapid support.

**Comment by pcmusic75** [comment]
Hi,
I have exactly the same problem as Beercules48 with 2 pop-ups accusing me using an AdBlocker, and I'm not using the online link but the Photopea app which is detecting an imaginary AdBlocker. There is no AdBlocker when I'm using the app. So please fix that bug.

**Comment by photopea** [comment]
@pcmusic75 The problem is on your side, you are blocking ads. If you dont know how to change the settings of your browser, try another browser.
