### ISSUE TITLE
Photopea Cannot Open IFF ANIM Image Sequence

### ISSUE THREAD

**Issue by blenderbach** [photopea/photopea#4592]
Photopea cannot open an ANIM IFF Image Sequence file. The ANIM format comes from the Commodore Amiga, and is a format that stores frames sort of like a GIF. Here's an example file.
[Camera Iris.zip](https://github.com/photopea/photopea/files/8644658/Camera.Iris.zip)

**Comment by photopea** [comment]
I have implemented this format! I tried to open several animations from http://www.randelshofer.ch/animations/amiga.html and they all seem to work well.

But I think nobody will ever find out, that they can open .ANIM files in Photopea. Could you maybe write about it on Wikipedia https://en.wikipedia.org/wiki/ANIM  ? There are "External links" at the bottom. You could add "Photopea.com - a tool for opening .ANIM files online".  If I write it myself, they will delete it as a self-promotion.

**Comment by blenderbach** [comment]
> I have implemented this format! I tried to open several animations from http://www.randelshofer.ch/animations/amiga.html and they all seem to work well.
> 
> But I think nobody will ever find out, that they can open .ANIM files in Photopea. Could you maybe write about it on Wikipedia https://en.wikipedia.org/wiki/ANIM ? There are "External links" at the bottom. You could add "Photopea.com - a tool for opening .ANIM files online". If I write it myself, they will delete it as a self-promotion.

Sure! I'll try! :)
