### ISSUE TITLE
Seeing ads yet still being shown the shaming message

### ISSUE THREAD

**Issue by SirHaesslich** [photopea/photopea#4593]
![изображение](https://user-images.githubusercontent.com/38571860/167247478-2fc45812-512a-4b5d-a11b-f4d15b75c41c.png)

**Comment by photopea** [comment]
Could you try this? https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by SirHaesslich** [comment]
This link is the same as the one provided by the final click-through of "whitelist us" sequence, I did see it.
Currently I don't have any non-cosmetic extensions installed.
Not sure about the provider/government regulations bit, yes, but still though, I do see an ad, and it even explicitly mentions Photopea in it.

**Comment by photopea** [comment]
Your browser is still blocking the domains of our ad providers, that is why we show you such message.

What browser are you using? Did you try a different browser? Did you try the incognito mode?

**Comment by SirHaesslich** [comment]
Mozilla; have just tried Chrome to no avail, same with incognito.
Oh well.

**Comment by photopea** [comment]
what is "no avail"? Do you have a firewall or other software, which could block certain websites or domains?

**Comment by photopea** [comment]
What are cosmetic extensions? Could you try to disable all your extensions for a while?

**Comment by SirHaesslich** [comment]
I have an antivirus; just added Photopea to the list of trusted sites. Will see if that helps later; cannot keep on actively testing right now. All extensions besides simply color themes have been disabled.

**Comment by photopea** [comment]
Are you sure you are not using Brave? Because the ad blocking can not be disabled in Brave.

After you disable extensions, you must reload Photopea. Photopea tries to show you ads just once (at the beginning).

I will close it now, but we can keep discussing it when you find time.
