### ISSUE TITLE
Side panels Layout: Wrapped Tabs height not accounted in panel height

### ISSUE THREAD

**Issue by popbee** [photopea/photopea#4594]
The Layers panel normally extends to fit the window exactly, but the calculation is off when Tabs are on 2 lines. In that case, the Layers panel *bottom bar* is not visible anymore.

Steps to reproduce:

Open a document in Photopea. Reduce size of right side panels until **| History | Swatches | Color |** tabs wraps on two lines. See that the Layers panel is extending beyond the window (and side browser native scrollbar is showing).  Gets worse when **| Layer | Channels | Paths |** tabs wraps too.  

Normal:
![image](https://user-images.githubusercontent.com/1083830/167266049-e106e694-1cc3-4f21-9848-13f2a6595b01.png)

Issue:
![image](https://user-images.githubusercontent.com/1083830/167266065-283b0f5a-bedc-4cf5-99cc-33f46e16b74e.png)

**Comment by photopea** [comment]
fixed! :)

**Comment by popbee** [comment]
Another related issue:

The same thing can be said for the Layers bottom bar itself !   I mean, it wraps "out" of the window (and the browser scrollbar appears).

![image](https://user-images.githubusercontent.com/1083830/167308644-af7b2a3e-1ea2-43e8-bf5c-a3704f29347d.png)

**Comment by photopea** [comment]
fixed :) thanks!
