### ISSUE TITLE
Photopea APP cannot work

### ISSUE THREAD

**Issue by Dida83** [photopea/photopea#4597]
If I click on the Photopea app icons, a new blank tab opens on the Chrome browser ...
Chrome is current - Version 101.0.4951.54 (Official Build) (64-bit)

Can you help me?

**Comment by photopea** [comment]
Could you go to about://apps and uninstall Photopea? Then, go to https://www.photopea.com, press More - Install Photopea.

**Comment by Dida83** [comment]
I solved in Chrome> settings> site settings> delete Photopea data!

Many thanks for your support!

**Comment by photopea** [comment]
ok, great!
