### ISSUE TITLE
Can't add image to layer in PSD

### ISSUE THREAD

**Issue by hivexliving** [photopea/photopea#4599]
I've been using the same PSD file forever, dragging my image into one of the layers, press ctrl + S to update the smart object and it was working fine but now I can't drag and drop my image onto the layer. Why? Or how else can I do it?

**Comment by photopea** [comment]
Did you try to close and reopen Photopea? Did you try it with several different files and it happens always?

**Comment by hivexliving** [comment]
I just tried it in Explorer and it worked. So it's just Chrome it doesn't work in.

**Comment by photopea** [comment]
Photopea does not work in Internet Explorer. Do you mean Microsoft Edge?

Could you try to update your Chrome or restart Photopea in it?

**Comment by hivexliving** [comment]
Yes, Edge, I thought that was Explorer that no one uses. I'll try updating Chrome and reload Photopea. Thanks!

**Comment by photopea** [comment]
Did you fix it? I guess you did, so I will close it now.
