### ISSUE TITLE
Curser

### ISSUE THREAD

**Issue by mathiasrw** [photopea/photopea#46]
Love this !

Input: The courser should change to indicate what you are doing. 

Its counterintuitive to have a normal arrow pointer when you are about to select an area

**Comment by photopea** [comment]
Hi, what selection tool do you mean? Rectangle select, or lasso, magic wand ... ? Do you think any standard cursor would be appropriate? http://codepen.io/chriscoyier/pen/uCwfB

**Comment by mathiasrw** [comment]
I suggest always having `crosshair` whenever the courser is above the canvas unless the "move" tool is selected where I suggest `move`/`all-scroll`

**Comment by photopea** [comment]
Hi, I just changed Rectangular and Ellipse selection to have "crosshair" cursor. When you move the selection, there is "move" cursor.
