### ISSUE TITLE
Display document info at bottom (dimension in pixel, zoom level)

### ISSUE THREAD

**Issue by photopeafan** [photopea/photopea#460]
Document dimension in pixel (ex:1280x720) and current zoom level(ex:50%) are good info to display
somewhere in the interface
Even better zoom level can be entered as value in the field for preview purpose
Also the zoom buttons in zoom tool tool bar not working on a Mac with firefox

**Comment by photopea** [comment]
Hi, I am not sure about that. Photoshop has this info. We would probably have to add scrollbars, too. I think it is better to use this space for the image, instead of scrollbars. The dimension can be found in Image - Canvas Size.

**Comment by photopeafan** [comment]
Or maybe just show it right after the top menu, just a tiny text would help
I know it can be accessed under menu, but having it constantly displayed would be more convenient.

**Comment by photopea** [comment]
I can show it in the bottom left corner. But should it be there always, or only with the rulers on? I am afraid too many people would rather have the "full rectangle" for their workspace.
