### ISSUE TITLE
Guides to multiple Artboard

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4600]
I have a doubt about adding guide to multiple artboards

https://user-images.githubusercontent.com/11801254/167491025-efe6cf99-3f44-4c5e-8654-6e957b5880fd.mp4

On photoshop it can be done:
https://helpx.adobe.com/photoshop/using/artboards.html
![image](https://user-images.githubusercontent.com/11801254/167492931-e8d8d743-e6a0-4a17-b939-48067d3a13ef.png)

Also 
![image](https://user-images.githubusercontent.com/11801254/167492964-45b302e0-798d-4130-9fe7-7cb4d387c392.png)

**Comment by photopea** [comment]
I have fixed it. If you select more than one artboard, the new guide will be a "canvas guide" (visible always).
