### ISSUE TITLE
Better mobile experience

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4601]
I do know that the desktop experience is the main one and probably the way most of users use Photopea, BUT, i can bet that i am not the only one who got his ass saved when i had to make a modification on the fly on a PSD with only my phone.

The possibility to have a full editing software on the phone is a great feature that adobe cannot have.

So, that being said, i have a little video (4 little parts) which shows different ideas that might help to have a better mobile experience in Photopea.

https://user-images.githubusercontent.com/11801254/167503523-ad71ce7c-0091-4e4c-8e43-a270fa18219f.mp4

https://user-images.githubusercontent.com/11801254/167503546-4cd0f4f4-7541-4f9b-9593-fae18f53a4b3.mp4

https://user-images.githubusercontent.com/11801254/167503554-3c66d583-fcef-4ea8-9fc9-bf022408cad4.mp4

https://user-images.githubusercontent.com/11801254/167503567-a5167567-b306-40c6-9d06-b9b0edd9b454.mp4

In synthesis:

- Ungrouped tools and scrollable (without the color picker)
- Bigger icon (double height) for the keyboard button
- Adjustable tabs for history, layers, and so.
- Always be in Fullscreen mode.
- Responsive dropdown menus

**Comment by photopea** [comment]
1) I don't think scrolling is a good solution. Especially on desktops with small screens, many people would not understand they need to scroll. What about creating 2 - 3 columns of tools?  The idea of goruping tools is, that we keep the most important tools, while less important tools are hidden in a sub-menu.
2) How do you propose to solve it? We could add a scrollbar into the Brush Panel. But isn't the scrollbar of the whole editor pretty much the same thing?
3) 4) We do not escape the fullscreen mode when you open files. Your browser seems to do it automatically. I just tried the desktop Chrome and the same thing happens. I will report it to Chrome Developers.

**Comment by TheRadicalDreamer** [comment]
1. I don't believe there is a problem of having scroll, but only for mobile. You say people with a small screen won't get the scrolling, but it is already like that. The top tool bar is side scrollable now, and is not intuitive at all. Maybe we have to test, so maybe there should be a view option, not by default, to not group the tools, and make it vertically scrollable.

So: the top tool bar, yes, totally add a second or third row.
But the left tool bar, i belive you should give an option to be scrollable, ate least momentanealy.

And the last issue: Can you get the keyboard icon to be twice as big? Or cover the hole vertical space?
![image](https://user-images.githubusercontent.com/11801254/170160175-68e73862-1671-4acd-8f63-eed8765a82f1.png)

As i said in the videos, it is really usefull on mobile, and it is really small tobe hitting it all the time.

**Comment by TheRadicalDreamer** [comment]
What about resizeable layer and history tabs?
![image](https://user-images.githubusercontent.com/11801254/170160447-b4f34263-45a4-4eff-a98c-7bb809eeb5d6.png)


It is hard to use the layer tab if it is such small

**Comment by photopea** [comment]
I have created a keyboard icon.

I think on a small screen, the side panels should be collapsed, and you should open just one separate panel, like Layers, which will be stretched along the whole screen height.

**Comment by TheRadicalDreamer** [comment]
Looks better.

Can the keyboard button be like this?:
![image](https://user-images.githubusercontent.com/11801254/170530677-8fbb548d-c5d9-4b42-a6e6-95e8c63e3ff4.png)

(padding: 15px 2px)

That way i can hit it without missing on mobile.

**Comment by TheRadicalDreamer** [comment]
> I have created a keyboard icon.
> 
> I think on a small screen, the side panels should be collapsed, and you should open just one separate panel, like Layers, which will be stretched along the whole screen height.

ok i get the idea.

**Comment by TheRadicalDreamer** [comment]
no way the keyboard icon can have that padding??  :)

**Comment by photopea** [comment]
then, there would be less space for the tools.

**Comment by TheRadicalDreamer** [comment]
I have to disagree 
![Screenshot 2022-06-24 12 35 07](https://user-images.githubusercontent.com/11801254/175588561-3abd5de6-90d8-4ede-9f49-de5aeb99ca5e.png)

https://user-images.githubusercontent.com/11801254/175588612-585bad2c-e0a7-4aee-b06b-269e2bc99ad7.mp4

**Comment by TheRadicalDreamer** [comment]
I would like to comment this issue #4792 here.

The mobile window/modal on mobile is difficult to use. And this person made a new design

**Comment by photopea** [comment]
it is done now.
