### ISSUE TITLE
Snap to grids in mm

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4602]
How i can set grid and snap shapes and layers to those grids when i am working in mm?

It seems that it is following the pixel

https://user-images.githubusercontent.com/11801254/167505464-572afa6f-6607-4fb9-b4d5-3afad00cdbe5.mp4

**Comment by photopea** [comment]
I just checked it in Photoshop, and it seems that Photoshop always snaps all tools to the pixel grid.

So make the grid which has a size in whole pixels.

**Comment by TheRadicalDreamer** [comment]
But then. Can we have resolution pixels/mm? 

So every guide set in mm will match the pixel?

**Comment by photopea** [comment]
I think so many parameters would be too confusing :( Maybe use the calculator to convert mm to inches?

**Comment by TheRadicalDreamer** [comment]
No.... Please do not do this to us.

Please, we use CM/MM for everything i hardly know 1 inch is 2.54.

**Comment by photopea** [comment]
I have added the dropdown menu, which lets you insert pixels per cm.

**Comment by TheRadicalDreamer** [comment]
![image](https://user-images.githubusercontent.com/11801254/168402998-392f00a9-effc-4826-b0ab-67f639d071b7.png)

I have a question, why does this happens?
Why the shapes cannot have vertices aligned to grid vertices??

**Comment by photopea** [comment]
What do you mean? Corners of a shape can have any coordinates. If you dont like it, you can move any corner in Photopea.

**Comment by TheRadicalDreamer** [comment]
I mean that those corners cannot be in the middle of the grid. I've tried :(

**Comment by photopea** [comment]
Yes, the Path Select Tool moves items by whole pixels.

If you have a rectangle 100 x 100 pixels, it would be impossible to move it elsewhere on a whole pixel, you would always be a little "off".

**Comment by TheRadicalDreamer** [comment]
You know what. 

When i changed the DPI from inches to cm, i could adjust the shapes perfectly.
![image](https://user-images.githubusercontent.com/11801254/168706381-3ee39add-503e-4058-ae6b-34c0aa3f5791.png)

So thanks for giving us that feature
