### ISSUE TITLE
Change DPI when you have guides in mm

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4604]
When you change the DPI when you have guides in mm, the guides are moved to another place. I believe it has to do because are bonded to the pixel, not the mm it was set on.

https://user-images.githubusercontent.com/11801254/167509933-dc98b91a-d8ca-4b68-852a-cfc3004aeb41.mp4

**Comment by TheRadicalDreamer** [comment]
Why an artboard in mm cannot be exactly the number i want?
![image](https://user-images.githubusercontent.com/11801254/167510786-a944de75-86c0-4d97-9acd-9596f61de47e.png)


I want 160mmx210mm in this case.

What is the reason behind this problem?

**Comment by TheRadicalDreamer** [comment]
![image](https://user-images.githubusercontent.com/11801254/167511000-98d0c82a-cfe9-4dfe-8660-8ba1cdee59ae.png)


Why the grid is set to 5mm, but the grid is 4mm? (the guide line is the 5mm mark)

**Comment by TheRadicalDreamer** [comment]
https://user-images.githubusercontent.com/11801254/167511461-2631d480-5050-4387-bc77-6f3c85d65270.mp4

**Comment by TheRadicalDreamer** [comment]
https://user-images.githubusercontent.com/11801254/167514497-505107f7-4473-4112-8890-700c87aebbdb.mp4

Here is a Photoshop tutorial using grid to make tables (what i am trying to do)
https://www.youtube.com/watch?v=CHAHLQFayok

**Comment by TheRadicalDreamer** [comment]
![Screenshot 2022-05-09 20 22 47](https://user-images.githubusercontent.com/11801254/167519007-3b8849ad-6082-4280-9089-24f5814c8f0f.png)

Can we have grids less than a inch?

Can we have resolution pixel/centimeter ?

in photoshop i believe you can change that

**Comment by TheRadicalDreamer** [comment]
Sorry for so many comments :)

I believe they are all related, but i prefer to speak up rather than keeping the issues to myself

**Comment by photopea** [comment]
I have fixed it :) when you scale the image, the guides will be moved, too. The grid step can be set to any number.

The artboard size must be in the whole pixels, so it is rarely the whole inches or milimeters.

The "vector view" is just a view now, the functionality of Photopea does not change.

**Comment by photopea** [comment]
Sorry, Photopea is a photo editor, that works with pixels. We must say "No" sometimes :(

**Comment by photopea** [comment]
It should be possible now.
