### ISSUE TITLE
Weird Glitching in Photopea

### ISSUE THREAD

**Issue by Jykie** [photopea/photopea#4605]
Hi, I just checked back in to see you have closed my case. Why is that? And what about my issue? Were you still unable to replicate the problem?

**Comment by photopea** [comment]
I thought you do not use Photopea anymore. Could you tell us how to replicate the problem?

**Comment by Jykie** [comment]
I never said that. There was another person commenting in the thread about them having the same problem I think. I sent you the psd files of the issues and asked if you could delete the layer with the white and try again.

 The problem lies with the masking, as stated before, it would become unresponsive when I try to use it. And then it did this thing where it would go weird as you're masking, then make the canvas completely black.

**Comment by photopea** [comment]
I did many things with your PSD, but I did not see a behaviour as in your video :(

Are you able to open www.Photopea.com and make that bug happen on purpose? That is called "replicating a bug". If you can, please, describe to me how to do it (in a few simple steps).
