### ISSUE TITLE
Unknown file format on CDR files

### ISSUE THREAD

**Issue by fdebef** [photopea/photopea#4606]
When trying to open some CDR files, the system falls into endles loop:

```
0
pp.js:13502 Service worker active
pp.js:8876 Extra parameter Spcn
pp.js:13229 Alert: Unknown file format: "appl"
pp.js:13229 Alert: Unknown file format: "\u0000\u0000\u0000\u0000"
pp.js:13229 Alert: Unknown file format: "þÿÿÿ"
pp.js:13229 Alert: Error. Please, send your file to support@photopea.com and we will solve it.
ext.js:612 unknown command 29256 1026
64596ext.js:612 unknown command 0 0
```
[Reklamační protokol štítky.txt](https://github.com/photopea/photopea/files/8661312/Reklamacni.protokol.stitky.txt)

Counting the last line endlessly. Some CDR files I can open with no problems. Change attached file suffix to CDR and try. 

MacBook Pro M1 Pro, tried both Safari and Chrome, same results.

**Comment by photopea** [comment]
I have implemented the support for these CDR files, it should work now :)
