### ISSUE TITLE
Color replacement tool not working

### ISSUE THREAD

**Issue by Circlesandsquares** [photopea/photopea#4607]
The colour replacement tool is not working unless it's on a colour i have paint brushed on. Here is a picture of me drawing a line (over both the picture and the colour i have paint brushed on.
![angel-wing-7006-43c4c887f1a78a06a2554d6c7b1ba048@1x](https://user-images.githubusercontent.com/105290314/167627693-07af23d2-55b4-489b-ac54-d24bea54870e.png)
)

**Comment by photopea** [comment]
I think you are using it in the "Hue" mode. You need to switch to a Color mode to be able to colorize grayscale images.

You can also buy a book about Adobe Photoshop, as these features work the same as in Adobe Photoshop, to learn how it works.
![image (1)](https://user-images.githubusercontent.com/15955558/168269455-65286d5d-6762-45f7-a9b5-8d5024a8f9cb.png)

**Comment by IdarielTakiz** [comment]
Hello! I am new to photopea, but I am also struggling with your color replacement tool. it simply paints over, like a paint brush, it does not *replace* a color with another. 

I am using Mac book pro with a never sufficiently to be cursed M1 chip. I have followed the steps in your YouTube video and browsed your open help tickets and nothing addresses the color replacement tool overwriting what is beneath it instead of turning one color into another.

As an example, in trying to lighten the hair in this image, it simply draws a stripe
![8330DC21-4A31-4CC0-9F16-16D72CDD1A88](https://user-images.githubusercontent.com/110003294/180907267-f992baca-a4a5-4060-a7ef-9efa7066eec8.jpeg)
.

**Comment by photopea** [comment]
I do not understand it. I just tried to use the Color Replacement tool over your image, with your foreground color, and it does not "paint with it" like in your example.

Why don't you show us what parameters you set at the top?

**Comment by photopea** [comment]
Also, do you know how layers work? I think you could be painting in an empty layer on top of your "hair layer".

You can learn how to use Photopea at https://www.photopea.com/learn/

**Comment by IdarielTakiz** [comment]
oooh that is a good thought; i am not very good at it yet. Let me take a picture of my settings. 
I am just half afraid that it is another M1 glitch; quite a few things that should work don't with the M1 chip. 

I could not get the color replacement tool to respond at all after I went in and made sure i was on the right layer. So I recreated the whole file (I hadn't managed any progress anyway) to see if it was glitched. and as you can see, this time nothing happened at all when I did the color replacement. which makes me so sad. 

In any event, here is the pic with my settings.


I will go to the Photopea sight and see what is there!

![56A30CFD-2744-4F41-A70E-9F881CB5682B](https://user-images.githubusercontent.com/110003294/181141839-31272af7-d060-432d-bbba-0a518c29a681.jpeg)
!

**Comment by photopea** [comment]
There is absolutely no glitch in your case. Photopea works exactly as it should. If you change the hue of a black color, it stays black.

This feature works identically to Adobe Photoshop. I think you should buy a book about Adobe Photoshop and learn what is out there, to be able to choose the right tool for your problem. You are buying a plane and complaining it can not go underwater. You need a submarine, not a plane.

If you are too lazy to learn anything, ask our community at https://www.reddit.com/r/photopea

**Comment by Circlesandsquares** [comment]
Photopea, I was shocked to open my inbox this morning and seeing you being so rude to a user. It's rather unprofessional. Maybe make it easier to find colour replacement tools on your learn page because I couldn't find it anywhere and I went through every single topic.
Lighter colours don't work well going over darker colours and you're using hue mode IdarielTakiz. I find colour mode works much better when it comes to switching colours on darker backgrounds. Although, it's still a dark background so it'll still be dark. I am still a novice in this so I don't know if that will work but hopefully it does.

**Comment by photopea** [comment]
This is a place for reporting bugs. We do not provide private lessons of photo editing for free here :(

**Comment by Circlesandsquares** [comment]
It's okay Photopea. Everyone loves that you have a free photo editing, you don't need anything else.
