### ISSUE TITLE
Student discount 

### ISSUE THREAD

**Issue by RihanArfan** [photopea/photopea#4610]
Firstly, thanks for making Photopea! It's an extremely helpful tool to make Photoshop accessible to more.

I know Photopea is free but it would be nice if premium/ad free is available to students for free. You could integrate with GitHub education pack, StudentBeans or UNiDAYS for this.

**Comment by photopea** [comment]
We could do that, but how would the client prove that they are a student? Anybody would check the checkmark "Student" and would get Photopea for free.

**Comment by RihanArfan** [comment]
UNiDAYS and Student Beans are the most common ways that companies verify student status. If a user tried to sign up as a student, you'll verify by redirecting to them using their API. 
 https://partner.studentbeans.com/brand-solutions/student-verification/
https://corporate.myunidays.com/en-us/student-verification

**Comment by photopea** [comment]
That just looks too complicated. Photopea is already free to use with ads. I think our Premium account is not that much expensive.
