### ISSUE TITLE
Feature request: Search Bar in Storage

### ISSUE THREAD

**Issue by DizzyHSlightlyVoided** [photopea/photopea#4611]
I think it'd be useful to have a search bar of some sort, for finding specific filenames in Storage (filesystem, Google Drive, etc). This would be a must-have for directories containing lots and lots of files.

**Comment by photopea** [comment]
You can press a letter on the keyboard, and it will "loop" through items starting with that letter. Did you try it?

**Comment by DizzyHSlightlyVoided** [comment]
Yeah, but it's less-effective when there are lots files beginning with that letter.

**Comment by photopea** [comment]
There are many things that could be improved. E.g. we dont have copy-pasting files (and folders of files). The future copy-paste should work between different storages.

**Comment by photopea** [comment]
I recommend using this button to sort items by Name. You can type a letter to jump to the first file starting with that letter. Unless you have hundreds or thousands of file in a folder, it should be enough.
![image (2)](https://user-images.githubusercontent.com/15955558/170035581-fd042ef8-37e4-4b70-8071-1cc959344d89.png)
