### ISSUE TITLE
No "relink to file"

### ISSUE THREAD

**Issue by DizzyHSlightlyVoided** [photopea/photopea#4612]
PhotoPea appears to completely lack the "relink to file" functionality, both in terms of creating such a link, and loading it from an existing file (a linked file appears as a raster layer instead of a Smart Object with a link-icon).

**Comment by photopea** [comment]
Photopea is a website, and websites can not access your hard drive (to find a linked file). That is why we prefer to have all embedded content inside one PSD file.  We could have the linking functionality with Storages, but not many people use storages.

**Comment by DizzyHSlightlyVoided** [comment]
Eh, fair enough. I mean, Storages *would* be the way to get it to work, and really, this was my one remaining complaint compared to vanilla PhotoShop. Oh well.

**Comment by photopea** [comment]
Do people really use it? I mean, you move the PSD to a different folder, or send it to someone, and the problems begin.

**Comment by DizzyHSlightlyVoided** [comment]
Well, *I've* used the functionality for files I wasn't planning on moving around, i.e. exporting a UV file from Blender and having Photoshop immediately reload it within the PSD I was using to make the actual textures. (Though admittedly the "immediate reloading" part is probably hard within Photopea ...)

**Comment by photopea** [comment]
Just drag-and-drop a new version into your PSD in Photopea and you should be done.

**Comment by DizzyHSlightlyVoided** [comment]
I know, I know! Just one more step, I guess, heh.

**Comment by MichalSZZ** [comment]
@photopea in a big marketing campaigns it is a useful feature but I can live without it and many members of my team didn't use it. But let me explain.
I have key visual graphic that is used in all marketing materials. I make PSD file with 20 artboards for Google Graphic Network Ads and some other banners. I have another PSD file with materials for social media. Another one is with graphic that will be placed on website. In all those PSD file I am placing one smart object. When the client want to do one 'little' change, I can edit one smart object and changes will apply in all artboards and other PSD files. 
But that is my point of view and I am doing it in that way only in big campaigns. File placed from cloud is better for teams working in many members on one campaign.

**Comment by photopea** [comment]
I have added the feature Layer - Smart Object - Replace Contents.

I think it is similar to "relink to file", but you have to choose the new version of your file manually (the PSD does not remember the file location).
