### ISSUE TITLE
CTRL/shift + click not working when using the Move(V) Tool

### ISSUE THREAD

**Issue by benleonheart** [photopea/photopea#4613]
when you use the move tool and resize a layer while keeping the proportions intact, you usually have to press shift and then drag from a corner of the object/layer... now it's as if it's permanently pressed, meaning that to resize without altering the proportuions, you have to just click and resize, which is not the intended behaviour...

this also applies for ctrl+click

**Comment by dvdlm** [comment]
![image](https://user-images.githubusercontent.com/47398685/167722848-ae72b936-90ae-4eff-aa4e-1d3012617348.png)

Try toggling the icon shown here. This swaps between the two behaviors you mentioned, and also keeps the shift-click variant the opposite of the behavior.

**Comment by photopea** [comment]
It works this way now: https://www.photopea.com/tuts/new-free-transform/
