### ISSUE TITLE
[Bug] in "Clipping Mask" clipping layer applies clip-mask to.. nothing!

### ISSUE THREAD

**Issue by Yabla1** [photopea/photopea#4615]
**Reproduce**: This happens when you clip-mask a layer, then you move the clipping layer to the bottom in the Layers tab. The Clipping effect still remains active/applied and the clipping layer clips nothing!
Plus when you move the clipping layer back on top of another layer - it does clip it, as in normal case.

Ironically, this sounds more of a feature than a bug!

![image](https://i.imgur.com/LePNEW8.png)

**Comment by photopea** [comment]
Just disable the clipping mask on a layer before moving it.
