### ISSUE TITLE
[Feature Request] "Save PSD as..." or "Save as..."

### ISSUE THREAD

**Issue by Yabla1** [photopea/photopea#4617]
Can you please change the "**Save as PSD**" to "**Save PSD as...**" or, to be more abstract/versatile "**Save as...**" so we can save files with the name of our choice, plus choosing location to save each files to -instead of the default "**/Downloads**". Plus add make this location default to save files, or even further, option to specify a default location for each file format we save. But by default, any file format not specified/attributed a custom location/folder, it will be defaulted/saved by default to the first custom location for all files we save.

This use case appears to be _rare_: but if a user needs organizes certain files by format for further processing like running batch script/instructions on **all** the files of a specific folder like to upload, rename, apply filter, actions, etc.

**Comment by photopea** [comment]
Websites do not "see" your hard drive, and can not do anything to it.

The name of a file, and the destination folder, are fully in control of your web browser. If your browser decides not to save the file at all, or delete half of the file, a website can not do anything about it. A website will not even know about it.

Read the manual for your browser to learn how to configure the file saving process. Also, some browser extensions can modify your saving process.
