### ISSUE TITLE
(cmd +) shortcut not working for zoom in 

### ISSUE THREAD

**Issue by photopeafan** [photopea/photopea#462]
Shortcut for zoom in not working on mac with firefox and safari

Also "fit the area" still leaves plenty of space on the sides compared to photoshop
Also "zoom out jump" too large from "fit the area" when full screen browser, finer zoom steps is preferred.

**Comment by photopea** [comment]
Hi, do you mean Ctrl and +  (Command and +) ? They seem to be implemented correctly for me.

Can you go here, click into the white area and press Command and Plus? What do you see? http://jsfiddle.net/p45f44zb/3/

**Comment by photopeafan** [comment]
Yes, and in the page you provide
When hold down command, it shows ["meta"]
When hold down plus key, it shows ["="]  (on a mac keyboard the = and + is on the same key)
When hold down both, it shows ["meta","="]
After release, it leaves []
When hold longer then release, it leaves ["="]

**Comment by photopea** [comment]
Ok, it should work with "=" now.
