### ISSUE TITLE
Export to WMF

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4621]
I know this is an old format, but it is the only format that Google Slides accepts vectors.

Can we have support for it?

**Comment by photopea** [comment]
SVG is the most used vector format. Are you sure your tool does not support SVG?

**Comment by TheRadicalDreamer** [comment]
![image](https://user-images.githubusercontent.com/11801254/168166746-a107a9bb-5944-4367-a55c-98db45396f62.png)

Pretty sure...  :(

**Comment by photopea** [comment]
In Google Slides, I press Insert - Image - Upload from computer, and I can not load the WMF from my computer :(

How exactly do you load WMF to Google Slides? Have you tried to load the EMF the same way?

**Comment by TheRadicalDreamer** [comment]
Yes I tried uploading emf. Doesn't work.

Upload the wmf to Google drive and open it with Google draw. There you can
copy it and paste it to a Google slides

**Comment by photopea** [comment]
Do you mean Google Drawings? How do I do that? It is not in the "open with" menu.
![image (1)](https://user-images.githubusercontent.com/15955558/169786889-f53a798b-c217-4e97-bc2a-74a04a3c68e5.png)

**Comment by TheRadicalDreamer** [comment]
Here is a little step by step tutorial:
https://user-images.githubusercontent.com/11801254/169870253-657bae70-1484-4679-a529-51184dd6f597.mp4

**Comment by photopea** [comment]
I still can not open WMF files in my Google Drive, no matter how many times I click them. Maybe you are the only one who can open them?

I still think that WMF is an outdated format. You should put pressure on Google to implement SVG or EMF.

**Comment by TheRadicalDreamer** [comment]
> I still think that WMF is an outdated format. You should put pressure on Google to implement SVG or EMF.

Totally, i have sent countless requests. But they are not like you, that replies. I don't even know if someone have read me :/

**Comment by Caroyiem** [comment]
Hey there friends, I'm having exactly the same problem, as a client wants his PNG icons to be editable (color) in Google Slides. Apparently Google Drawings disabled this file type for editing. Now it only allows JPEG, PNG, PDF. So basic, it's so odd this.

Have any of you been able to solve it? :)

**Comment by TheRadicalDreamer** [comment]
As far as i know, now there is no way to do it now.

:(
