### ISSUE TITLE
PNGSaveOptions unsupported

### ISSUE THREAD

**Issue by johnteske** [photopea/photopea#4623]
I'm getting an `pp.js:9317 Uncaught new PNGSaveOptions` error when I try calling `new PNGSaveOptions()` in a script.

**Comment by photopea** [comment]
In order to fix it, could you provide a short script, which uses your code and does something interesting, and works in Adobe Photoshop?

**Comment by johnteske** [comment]
I don't have PS at the moment but the minimal reproducible error is to simply call, `var opts = new PNGSaveOptions();`, with the intention of passing in to `app.activeDocument.saveAs`.

I've seen the `PNGSaveOptions `referenced in a number of PS scripts online that should work with PS2020.

**Comment by photopea** [comment]
it should be implemented now :)
