### ISSUE TITLE
Content aware leaves border marks

### ISSUE THREAD

**Issue by MuziCodes** [photopea/photopea#4624]
It works when I do Edit > Fill > Content Aware. But not
                              Edit > Content Aware
I can live off with the first option as it has a shortcut. But I still get the border marks when I go back in history

**Comment by photopea** [comment]
There is "Edit > Fill > Content Aware" in Photopea. There is no "Edit > Content Aware", maybe you are using a different program and not www.Photopea.com ?

What should I do to see the "border marks" when i go back in history? I tried it and I cant see any border marks.

**Comment by MuziCodes** [comment]
[Here's what I meant by the first comment](https://imgur.com/gallery/UdeofNF)

As for the history problem, it occurs sometimes when I do "Edit > Fill > Content Aware". Then after many edits, if I undo couple of times. Similar tracks are produced

**Comment by photopea** [comment]
That is a Content-aware scale and it is not a content aware fill.

Please, tell me some steps how can I make the bug happen.

**Comment by MuziCodes** [comment]
I see. Sorry I can't say the steps because it happens after I do content aware fill then go back in history a couple of times then it appears. Anyways the bug rarely happens. Thanks for your support

**Comment by photopea** [comment]
Once you are able to make it happen on purpose, let me know!
