### ISSUE TITLE
History is limited

### ISSUE THREAD

**Issue by MuziCodes** [photopea/photopea#4625]
Perhaps group similar effects or give access to longer history

**Comment by photopea** [comment]
They are already grouped, e.g. moving the same layer multiple times. What else would you like to group?

**Comment by MuziCodes** [comment]
![image](https://user-images.githubusercontent.com/39677932/168474931-f217fcdb-05db-4397-8180-6e282f60e589.png)

You can write something like clone 5x

**Comment by photopea** [comment]
But you can use the Clone 10 times, and then, you want to go back just one step. But Photopea would let you go back only all 10 steps (as 10 steps are recorded as 1 step). I think people will hate it.

**Comment by MuziCodes** [comment]
I see, I was thinking about a drop down method. But thanks! I think you can close the thread now

**Comment by photopea** [comment]
More steps in history require more RAM to remember them all.
