### ISSUE TITLE
Filters on PDF

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4627]
I don't know if this is intended, so i would like to ask:

I have a red shape, if i set the blending option to Luminosity, it turns grey.

But when exported to PDF, i lose the grey effect.

It happens the same when i put a Adjustment Layer of Black&White, the output is colored.

So the only way i found (without changing the colors of the shape) is to raster. 

There is a way around? My first attemps are suposed to behave like they did?

**Comment by arcanna** [comment]
I am experiencing a similar issue. If I have any layer that has a Blending option applied, when going to Export or Print as a PDF, the layer with the effect on it loses any masked applied and occasionally loses the blending effect as well.
Can only raster and then export to PDF but this is not sufficient when producing a file for high res printing.

**Comment by TheRadicalDreamer** [comment]
Exactly @arcanna

**Comment by photopea** [comment]
I made the red ellipse over the image and set the blend mode to Luminosity. During the PDF export, it stays grey, try it here: https://www.photopea.com/#ii-kE0TNu

How can I reproduce your problem?

**Comment by TheRadicalDreamer** [comment]
https://www.photopea.com/#iMcUHx6n3

Here.

Export it to pdf

**Comment by photopea** [comment]
I just tried and it looks the same as in Photopea.

I think it was fixed back when we fixed the opacity of folders (several weeks ago).

![xEDDksQ](https://user-images.githubusercontent.com/15955558/169787436-0ab9fcbf-0aca-4135-a924-c1fa917b1f19.png)
a

**Comment by TheRadicalDreamer** [comment]
Yes, it got fixed
