### ISSUE TITLE
Have to deselect keys to change which way I'm zooming in/out

### ISSUE THREAD

**Issue by Xxforlife** [photopea/photopea#4628]
the title probably doesn't make any sense but what I mean is that when I hit the Command (⌘) key on MacOS then hit the plus and minus signs to zoom in and out, it only works one way. for example say I'm currently holding command and - to zoom out, if I keeping holding in command and change the other key to + it zooms out instead of zooming in.

**Comment by photopea** [comment]
It is a bug in MacOS. MacOS does not tell an app, that a key was released, when you hold Command. You need to release the Command "in between", or use Ctrl instead of Command.

You can also ask Apple to fix it, or buy a different computer :D
