### ISSUE TITLE
Deselecting any layer by clicking blank area in layer panel

### ISSUE THREAD

**Issue by photopeafan** [photopea/photopea#463]
To prevent unwanted movement, I deselecting anything in photoshop by click in blank area, but in photopea I create a blank layer for this purpose, which is an extra step.

**Comment by photopea** [comment]
Hi, do you mean clicking the blank area with a Move tool in the workspace (with Autoselect)? Or clicking a blank area in the Layers panel?

**Comment by photopeafan** [comment]
Both would be good, sometimes the layers panel is full, so you have no blank space to click to deselect anything, so using blank workspace to deselect anything is also useful.

**Comment by photopea** [comment]
The current structure of Photopea expects, that at least one layer is selected all the time.

Similarly, each document must have at least one layer (you can not delete all layers). I prefer keep it this way.
