### ISSUE TITLE
Photopea won't let me export

### ISSUE THREAD

**Issue by Nixerer** [photopea/photopea#4630]
i will go ahead and press file>export as>png> and then when the save for web thing comes up i press save but it does nto save.

https://user-images.githubusercontent.com/105604254/168487597-17fbbecf-a851-4986-aebe-2fd70369b2fe.mp4

**Comment by photopea** [comment]
It is hard to tell what happened :( Could you share your PSD with me, so that I can try it myself?

**Comment by Nixerer** [comment]
It won’t let me export the psd either

**Comment by Nixerer** [comment]
I’m using the app

**Comment by photopea** [comment]
we dont have any app. Always use www.Photopea.com as the main source of Photopea.

**Comment by Nixerer** [comment]
There is a web app. One that if you press a button it will take my website to a web app

**Comment by photopea** [comment]
Can you make your problem happen at www.Photopea.com ?

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by Laagreene** [comment]
try doing this:
Take a screenshot on Windows 10 and automatically save the file, press the Windows key + PrtScn. Your screen will go dim and a screenshot of your entire screen will save to the Screenshots folder
