### ISSUE TITLE
Not important: Large Widths on New Project Freeze/Crash Photopea

### ISSUE THREAD

**Issue by amark** [photopea/photopea#4631]
I am a HUUUUUUGE fan of photopea, I use it all the time. Thank you an infinite amount.

Here is a quick bug report on something that is not important, doesn't matter. But thought might as well tag it for in 10 years from now:

Replicate:

File -> New -> Width: type in 100000000 (everything freezes/crashes, and I wasn't even able to reload, unless I went to incognito tab)

**Comment by photopea** [comment]
If you make a file 1000 x 100000000 pixels, it will require 400 GB of RAM. I guess you don't have that much, and that is why browser decided to "kill" Photopea.

But maybe, 10 years from now, you will have more than 400 GB of RAM, and it will work well.

It will crash even if you enter 1000x1000 pixels, if your device does no thave 4 MB of free RAM.

**Comment by photopea** [comment]
And sadly, websites can not know how much RAM you have, to be able to tell you in advance that it will fail.
