### ISSUE TITLE
Ad Blocker

### ISSUE THREAD

**Issue by soroushtech** [photopea/photopea#4635]
I don't use AdBlock, fixthepicture asked me if I use it, and there was no "I don't" button to submit, I'm Not happy to read - "Photopea would not exist if everyone did what you do"
![Screenshot (1441)](https://user-images.githubusercontent.com/100304111/168550007-f02d094f-3f2c-4bb2-98be-36ceea5cafd0.png)
.

**Comment by photopea** [comment]
what is "fixthepicture"? Try using Photopea at [www.Photopea.com](http://www.photopea.com/) .

You have four extensions and any of them could be blocking ads. I can also make an ad blocker and name it "Google Translate", and people will install it.

**Comment by so-mironov** [comment]
I basically don't use ad-blockers, but Photopea keeps shaming me :D 
Use Chrome without any ad-block extensions, don't use any PC ad-blockers.

**Comment by photopea** [comment]
@so-mironov What is an ad-blocker? 

Click the extension button in Chrome, you will see: "These extensions see and change information on this site". How many extensions do you have in that list?

It looks like this: https://www.reddit.com/r/photopea/comments/uolfhl/the_ads_arent_loading_even_with_the_adblockers/

**Comment by so-mironov** [comment]
Bitwarden, Downloads Pro (just button to open downloads list), Friendly Tab, ImTranslator, Lightshot. That's all.

**Comment by so-mironov** [comment]
Ads are displayed in the incognito and not in the incognito both, I see advertising. In the incognito Photopea shaming me too :D

**Comment by photopea** [comment]
Are you sure you are using Chrome and not Brave? Do you have any firewall or antivirus which could be blocking domains?

**Comment by so-mironov** [comment]
Original Chrome only. I have antivirus and try to turn it off and use Photopea in VirtualBox just installed Windows with Chrome - still the same result. For me it is ok, thanks Photopea for work anyway :)

**Comment by photopea** [comment]
Can you access https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
or https://cmp.uniconsent.com/v2/85d3b9563e/cmp.js from your computer?

**Comment by so-mironov** [comment]
pagead2.googlesyndication.com doesn't work... due to country restrictions, I think. Unfortunately, there is nothing I can do about it :-(

**Comment by photopea** [comment]
What country are you in?

**Comment by so-mironov** [comment]
Russia...

**Comment by photopea** [comment]
I see, why don't you switch to a VPN?

**Comment by so-mironov** [comment]
Free VPN is slow, for paid I can't pay, because out bank cards are blocked... But I think, I should find the way...

**Comment by photopea** [comment]
I have updated this article, which should explain everything: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

So again, if your browser, your antivirus, or your government, are blocking domains of our ad providers, ads can not work properly :( We think it would be unfair, if many users watch our ads, while others will be allowed to get away with blocking them.

Thank you away for watching our ads or buying Premium!
