### ISSUE TITLE
₿ symbol

### ISSUE THREAD

**Issue by AdiuvoInc** [photopea/photopea#4636]
When using text, ₿ symbol doesn't show correctly. This bitcoin symbol works fine with the fonts Microsoft Sans Serif and Bebas Neue Regular. If I load these fonts in the editor, the symbol still fails to show properly.

**Comment by photopea** [comment]
I have tried the font "Noto Sans" and the bitcoin symbol is shown correctly.

Could you show me a font, which definitely has this symbol, but Photopea can not render it? I think Bebas Neue does not have the bitcoin symbol.

**Comment by photopea** [comment]
I have to close it because of lack of details.
