### ISSUE TITLE
Adblocker is off but I'm still getting popups

### ISSUE THREAD

**Issue by nivenhuman** [photopea/photopea#4637]
It's not a bug that impacts functionality, but it's probably worth at least noting. I've set all my adblockers to not run on photopea, but it still gives me the popups I had before I disabled them. 

![image](https://user-images.githubusercontent.com/105753175/168913015-382c7cf8-e583-4d13-a2da-9d29da048171.png)

**Comment by photopea** [comment]
You are still blocking our ads. What extension are you using? Check this: https://twitter.com/photopeacom/status/1526134857608441856

Also the Brave browser has a built-in ad blocker that can not be disabled at all.

**Comment by DragonNZ** [comment]
I get the same, edge chrome in private mode, photopea says that ad blocker is active and shows an ad!

![image](https://user-images.githubusercontent.com/4507081/169644052-7292571b-07b7-4c41-b74e-418bd760267d.png)

**Comment by photopea** [comment]
@DragonNZ Do you have any antivirus or firewall, which is blocking some websites? Maybe your antivirus is blocking the domains of our ad providers.

**Comment by DragonNZ** [comment]
No third party anti-virus installed. Just standard windows 10 protection. Firewall is off. No domains are blocked.
What is an example domain that I can check?

**Comment by photopea** [comment]
Can you access https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js  and https://cmp.uniconsent.com/v2/85d3b9563e/cmp.js ?

**Comment by DragonNZ** [comment]
Yep, both on private mode and not in private mode.
It gives me the cmp.js file (downloads it as f.txt for some reason).
(function(sttc){/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/  ...

**Comment by DragonNZ** [comment]
cmps.js loads just fine

!function(n){var e={};function t(r){if(e[r])return e[r].exports;var o=e[r]={i:r,l:!1,exports:{}};return n[r].call(o.exports,o,o.exports,t),o.l=!0,o.exports}t.m=n,t.c=e,t.d=function(n,e,r){t.o(n,e)||Object.defineProperty(n,e,{enumerable:!0,get:r})},t.r=function(n){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(n,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(n,"__esModule",{value:!0})},t.t=function(n,e){if(1&e&&(n=t(n)),8&e)return n;if(4&e&&"object"==typeof n&&n&&n.__esModule)return n;var r=Object.create(null);if(t.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:n}),2&e&&"string"!=typeof n)for(var o in n)t.d(r,o,function(e){return n[e]}.bind(null,o));return r},t.n=function(n){var e=n&&n.__esModule?function(){return n.default}:function(){return n};return t.d(e,"a",e),e},t.o=function(n,e){return Object.prototype.hasOwnProperty.call(n,e)},t.p="",t(t.s=0)}([function(n,e,t){n.exports=t(1)},function(n,e){function t(n){if(o[n])return o[n].exports;var e=o[n]={i:n,l:!1,exports:{}};return r[n].call(e.exports,e,e.exports,t),e.l=!0,e.exports}var r,o;o={},t.m=r={88:function(n,e,t){n.exports=t(89)},89:function(n,e){if(window.__unic_cmp_id="85d3b9563e",window.__unic_cmp_host="https://cmp.uniconsent.com",document.currentScript&&document.currentScript.src){var t=new URL(document.currentScript.src).origin;t&&(window.__unic_cmp_host=t)}function r(n,e){var t=document.createElement("script");t.src=n,t.async=!1,t.onload=function(){window[e]()},t.onerror=function(n){},document.head.appendChild(t)}function o(){r(window.__unic_cmp_host+"/v2/main.min.js","__unic_start")}window.__unic_loadapp=o,window.Promise&&window.fetch&&window.Symbol?o():r(window.__unic_cmp_host+"/v2/polyfills.js","__unic_loadapp")}},t.c=o,t.d=function(n,e,r){t.o(n,e)||Object.defineProperty(n,e,{enumerable:!0,get:r})},t.r=function(n){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(n,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(n,"__esModule",{value:!0})},t.t=function(n,e){if(1&e&&(n=t(n)),8&e)return n;if(4&e&&"object"==typeof n&&n&&n.__esModule)return n;var r=Object.create(null);if(t.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:n}),2&e&&"string"!=typeof n)for(var o in n)t.d(r,o,function(e){return n[e]}.bind(null,o));return r},t.n=function(n){var e=n&&n.__esModule?function(){return n.default}:function(){return n};return t.d(e,"a",e),e},t.o=function(n,e){return Object.prototype.hasOwnProperty.call(n,e)},t.p="",t(t.s=88)}]);

**Comment by photopea** [comment]
Could you try to disable your windows 10 protection?

Ads in Photopea are based on these two files, so clearly, something in your computer is blocking these domains. Could you disable all of your extensions temporarily?

**Comment by DragonNZ** [comment]
I'm not sure why you think the domains are being blocked, it loaded the urls that you gave me without issue.
Note for google.js I didn't post all of the file, I just posted the header so that you could see it had been downloaded

**Comment by DragonNZ** [comment]
I have looked at the browser inspector and had a look at blocked requests. Now I see them.

The google ads script that you are using is trying to send tracking data back and is being blocked by Edge as it prevents tracking of my information.

Sending ads is not blocked, they just don't have the option to be personalised as I like to keep my private data private.

So basically, you need to stop using ad services that try to collect personal data. 

I don't mind the ads, but taking personal information is not on.

Cheers.

**Comment by photopea** [comment]
What personal data exactly did they get about you?

Sorry, but I don't think our ads are harmful. If you think they are, you should block Photopea.com the same way you are blocking other domains, to make sure you are not harmed.

**Comment by DragonNZ** [comment]
Sorry, I think you misunderstand.

I am not blocking any domains on purpose, the Edge web browser blocks trackers. That is the choice of Microsoft not me.

I have nothing against ads, they are useful and people may promote what they have to sell, that is how business works.

But trackers are a completely different story. This is data being collected without your permission on your viewing habits, when you view things, what you view, where you are that sort of personal information. Completely invasive.

I am seeing your ads, but I am saying that you are trying to serve up google ads as well, and I don't think you understand that google are also using trackers. It's those trackers that are triggering the blocking by Microsoft's Edge browser.
If you don't like Edge blocking the trackers, you will need to take that up with Microsoft as there is nothing I can do about it.

Short story, I am allowing ads, and you have written a detection routine that is getting it wrong and you are putting up nags telling people that they are  bad for blocking ads, which they are probably not doing on purpose by all accounts.
That is why people are raising these issues with you.

**Comment by photopea** [comment]
I am not playing this game if good and bad websites, good small companies and bad Google, etc. Feel free to block whatever you want. If you think a company is breaking laws, you should go to the police.

**Comment by DragonNZ** [comment]
Good grief. Get a grip. Police? No idea what you think the game is. 
How many times do you need to be told?
I'm not blocking any ads.
If you don't like public criticism of calling out people for blocking ads that they are not blocking, then take your software down,
