### ISSUE TITLE
Unable to save .psd file through script

### ISSUE THREAD

**Issue by AbstractVoid** [photopea/photopea#4638]
Using the Photopea script window (File > Script), I have been able to save .png and .jpg images, but I run into issues when trying to save .psd files. I have been using the photoshop scripting reference found [here](https://github.com/Adobe-CEP/CEP-Resources/blob/master/Documentation/Product%20specific%20Documentation/Photoshop%20Scripting/photoshop-javascript-ref-2020.pdf)

When I run the code:

```
let psdOpts = new PhotoshopSaveOptions();
psdOpts.alphaChannels = true;
psdOpts.annotations = true;
psdOpts.embedColorProfile = true;
psdOpts.layers = true;
psdOpts.spotColors = true;

psdFile = new File("output.psd");
app.activeDocument.saveAs(psdFile, psdOpts, true);
```

Nothing happens, and the console logs the error:

![uncaught new photoshopsaveoptions](https://user-images.githubusercontent.com/33007416/169096942-0af15f3f-7f4b-471e-ade2-74ad6ff7f3c5.png)

When I try using:

```
let webOpts = new ExportOptionsSaveForWeb();
webOpts.format = SaveDocumentType.PHOTOSHOP;
webOpts.quality = 100;

file = new File("test.psd");
app.activeDocument.exportDocument(file, ExportType.SAVEFORWEB, webOpts);
```

I get a different error:

![export options save for web](https://user-images.githubusercontent.com/33007416/169097087-f8073dd2-f508-4890-a127-58e2e1b73efa.png)

The same thing happens above when I try different formats such as `SaveDocumentType.PHOTOSHOPDCS_1` or `SaveDocumentType.PHOTOSHOPDCS_2`.

I have been using Google Chrome. I've tried it in incognito, and same result. I also tried it using the brave browser, as well as Mozilla Firefox, and have been unsuccessful there as well.

Any help is appreciated. Thanks for creating Photopea, it's awesome! 😄

**Comment by photopea** [comment]
I tried to run your first script in Photoshop, it did not work. I changed "let" to "var" and it worked in Photoshop. It works in Photopea now.

I tried to run your second script in Photoshop and it did not work :/

If you have any other script, which works in Photoshop, but not in Photopea, let me know! :)
