### ISSUE TITLE
How would plugins like gmic work with photopea?

### ISSUE THREAD

**Issue by jointri** [photopea/photopea#4639]
How would it? Would it be possible with emscripten or another C++ -> Javascript compiler?

**Comment by photopea** [comment]
I think it is possible.

Did you check the feature Window - Plugins? We have many plugins there.

I asked a guy at the Gmic forum to add Gmic to Photopea as a plugin, but he did not reply yet: https://github.com/dtschump/gmic/issues/13#issuecomment-1126899472

**Comment by jointri** [comment]
@photopea 
The thread maker replied like a week ago. What do you think we should do next?
https://github.com/dtschump/gmic/issues/13#issuecomment-1130933532

**Comment by photopea** [comment]
We need a person who can compile C into WASM and can prepare such plugin for Photopea.

**Comment by photopea** [comment]
@hxim Would you like to create such plugin? You just need to compile the Gmic library into Wasm, and then, make a binding from Javascript. It is not as hard as it sounds. I am sure thousands of people would appreciate it!

**Comment by hxim** [comment]
> @hxim Would you like to create such plugin? You just need to compile the Gmic library into Wasm, and then, make a binding from Javascript. It is not as hard as it sounds. I am sure thousands of people would appreciate it!

@photopea No, not really. Seems pretty hard at least for me.

**Comment by yikuansun** [comment]
@hxim Pretty sure C to WASM is not that complicated, you can use a tool like Emscripten.

**Comment by jointri** [comment]
@photopea 
I don't think gmic is going to happen anytime soon. The resulting WASM would be huge and you would have to have photopea know how to talk to the compiled JS/WASM code. Why not just implement all the filters yourself from scratch?

**Comment by photopea** [comment]
I will close it now. But anybody in the world can make a GMIC plugin for Photopea and publish it in our plugin gallery (Window - Plugins).
