### ISSUE TITLE
Delete layer with delete key on keyboard

### ISSUE THREAD

**Issue by photopeafan** [photopea/photopea#464]
A very intuitive action that is missing, have to click the trash can on bottom right, drag n drop delete is also not available

**Comment by photopea** [comment]
It was implemented (deleting layers both with Delete and Backspace). BTW. nice nickname! :D

**Comment by photopeafan** [comment]
But now when filling a layer with opt-delete, it also got deleted right after it's filled.

**Comment by photopea** [comment]
This should be fixed now, too. Thanks!

**Comment by photopeafan** [comment]
It can still be deleted pretty easily if you release both keys at about the same time, 
have to deliberately ensure the delete key is released before the opt key, to prevent it from deletion.

**Comment by photopea** [comment]
But it happens in Photoshop, too. If you press Alt + Delete, release Alt, but keep holding Delete, it will delete layers.

**Comment by photopeafan** [comment]
Maybe there's some "small" response timing difference in photoshop or maybe it's a mac specific thing, because with the same "press-release timing", I had never got layers deleted after the filling.

**Comment by photopeafan** [comment]
Yes, it worked, now how about also add "fill with background color" with cmd-delete

**Comment by photopea** [comment]
Ok it is done, too. Thanks!
