### ISSUE TITLE
Please add a feature where if signed in, Photopea saves the last project you worked on along with previous others

### ISSUE THREAD

**Issue by BasicBroom** [photopea/photopea#4640]
Please add a feature where if signed in, Photopea saves the last project you worked on along with previous others so you don't loose progress. it's really annoying when my computer shuts down or restarts and I lose all progress on an image I was working on. It's even more frustrating that the "save as" feature doesn't actually save it, it just saves as a Krita file for some reason and now photopea can't open it anymore.

**Comment by photopea** [comment]
Are you sure you know how to open and save files in Photopea? Please read this and let me know that you understood everything:  https://www.photopea.com/learn/opening-saving

**Comment by photopea** [comment]
I have to close it because of lack of details.
