### ISSUE TITLE
Script to count layers in other documents

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4642]
I am trying to count layers in open documents (in my plugin) with script similar to this one:
https://stackoverflow.com/questions/26623283/photoshop-javascript-to-get-all-layers-in-the-active-document
While for activeDocument it works and returns correct number.
`alert(app.activeDocument.layers.length);`
But for other open documents accessed with app.document[index] it still returns number only for active document (for any index).
for example this is not working if active document is not first document:
`alert(app.documents[0].layers.length);`

**Comment by AbstractVoid** [comment]
You can work around this by setting the active document to the designated document. Example:

```
var documents = app.documents;

for (var i = 0; i < documents.length; i++) {
     app.activeDocument = app.documents[i];
     alert("Document " + (i + 1) + ": " + app.activeDocument.layers.length + " layers.");
}
```

![image](https://user-images.githubusercontent.com/33007416/169573093-25bf19d3-0ee5-4ab7-8f8c-307f16b4ce50.png)

**Comment by hxim** [comment]
I tried this approach, but there is another issue when switching app.acitveDocument in script.
If I run script like this to switch to other document and back it will sometimes scroll up History window (if selected item is not last).
See this screenshots:
before running script
![image](https://user-images.githubusercontent.com/6370548/169586714-fe1a3673-78bb-4412-8daa-026611929a42.png)
after running script
![image](https://user-images.githubusercontent.com/6370548/169586726-34f62443-8835-47ae-a86c-275095cf9176.png)
And I need to update list of documents in my plugin every few seconds so it changes when documents changes.
I want to display list of documents like this (layer count should be in "L" column):
![image](https://user-images.githubusercontent.com/6370548/169587687-005dadae-8177-4f2f-ba64-4861c860c763.png)

Actual script I am using:
`function lc(doc){var c=0;for(var m=0;m<doc.layers.length;m++){if (doc.layers[m].typename==='ArtLayer') c++; else c+=lc(doc.layers[m]);}return c;} var s = 'MDC_INFO:'; for (var i = 0; i < app.documents.length; i++) { s += app.documents[i].source+'\\n'+app.documents[i].name+'\\n'+app.documents[i].width+'\\n'+app.documents[i].height+'\\n'+(app.documents[i]==app.activeDocument)+'\\n'+lc(app.documents[i])+'\\n'; } app.echoToOE(s);`

Modified script (with work around) which causes scroll up of History window issue:
`function lc(doc){var c=0;for(var m=0;m<doc.layers.length;m++){if (doc.layers[m].typename==='ArtLayer') c++; else c+=lc(doc.layers[m]);}return c;} var s = 'MDC_INFO:'; var ad=app.activeDocument; for (var i = 0; i < app.documents.length; i++) { app.activeDocument=app.documents[i]; s += app.documents[i].source+'\\n'+app.documents[i].name+'\\n'+app.documents[i].width+'\\n'+app.documents[i].height+'\\n'+(app.documents[i]==ad)+'\\n'+lc(app.documents[i])+'\\n'; } app.activeDocument=ad; app.echoToOE(s);`

**Comment by photopea** [comment]
Hi, sorry, it should be fixed now.
