### ISSUE TITLE
EXPORT

### ISSUE THREAD

**Issue by Just-Me-123** [photopea/photopea#4645]
Hello, hope you are doing great! please the export option doesn't work anymore. I tried different browsers and same problem/.

**Comment by photopea** [comment]
Hi, could you tell me what should I do to see the problem? Or could you record a video of what you do?

**Comment by dumpaccount123** [comment]
Hello, I am experiencing this bug as well.
Video attached:
https://streamable.com/jp7cut

**Comment by photopea** [comment]
It should be fixed now.
