### ISSUE TITLE
Align layer to the whole canvas without selecting mutiple ones

### ISSUE THREAD

**Issue by photopeafan** [photopea/photopea#465]
For positioning layer relative to the whole canvas, can be done with an empty layer, which is an extra step

**Comment by photopea** [comment]
Where should this aligning function be located? Do you mean aligning buttons in the top bar of the Move tool?

**Comment by photopeafan** [comment]
Yes, the buttons in the tool bar.
For this purpose photoshop have a drop down menu for chosing "align to selection" or "align to artboard"

**Comment by photopea** [comment]
What about snapping? The layer can be snapped to the canvas border when you move it. Isn't it enough<
