### ISSUE TITLE
Sometimes i can't save when image is too big

### ISSUE THREAD

**Issue by Utrasel** [photopea/photopea#4650]
I was working on a image that's around 11000 x 7000 but when i try to save it doesn't save, it says "saving" but it doesn't save, i use control s to save

**Comment by photopea** [comment]
I just created a 11000 x 7000 file with one white layer, I was able to save a PSD.

I think your computer simply runs out of RAM memory, there is nothing we can do about it :( either get more RAM, or work with smaller documents.

If you think you have enough RAM, please, describe, what should I do to see such problem myself.

**Comment by Utrasel** [comment]
> I think your computer simply runs out of RAM memory, there is nothing we can do about it :( either get more RAM, or work with smaller documents.
> 
> If you think you have enough RAM, please, describe, what should I do to see such problem myself.

I have 8 gigs of ram and im on a 5K imac, i think 8 gigs of ram is enough for photopea even though images larger than 15000 x 15000 lag a lot

**Comment by SuraAY** [comment]
My pc is 16 GB of Ram and its same problem

**Comment by photopea** [comment]
What kind of image are you opening? E.g. if it is 100,000 x 100,000 pixels (10 billion pixels), 16 GB of ram could be not enough.

We need to see this problem ourself to be able to fix it. Please, tell us what should we do (e.g. what image should we open).
