### ISSUE TITLE
Open DDS File Make colour turn invert/bluish

### ISSUE THREAD

**Issue by ShadeRedeye** [photopea/photopea#4651]
as title say whenever open DDS File it become like this
![Screenshot_1](https://user-images.githubusercontent.com/84408428/169673230-22fce86d-b49c-4d4e-8137-0261c618620e.png)

**Comment by photopea** [comment]
Could you please share your DDS file with us?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
