### ISSUE TITLE
Layers in lower level shouldn't be "hidden" respectively when hold Alt and click on the eye icon of layers in higher level

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4652]
Here is a example image. 
![image](https://user-images.githubusercontent.com/79258245/169678224-1e1ebb76-0a41-468f-a5cb-77f10595a987.png)
In Photoshop, when I hold Alt and click on the eye icon of a layer in level 2, the layers in level 2 and level 1(same and higher level) are "hidden", but the layers in level 3(lower level) are not. 
In Photopea, all layers are "hidden" except for the layer of which I hold Alt and click on the eye icon.

The "hidden" layers I mean here are the layers with sqaure icon instead of grayed out eye icon.

**Comment by photopea** [comment]
Ok, it should work like that now.

Hiding a layer at level X (with Alt) will hide all layers at level X or lower (unless the layer is the one you clicked on or its parent).
