### ISSUE TITLE
Problem with ternary conditional operator in script

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4653]
` a ? b : c` instead of giving value of `b` or `c` it gives you name of variable which is string "b" or "c"
This script should print "2" but it prints "b":
```
var a=1,b=2,c=3;
alert(a==1?b:c);

```
Screenshot:
![obrazek](https://user-images.githubusercontent.com/6370548/169696697-6ff0daab-9e1d-4b82-a0ec-0377f2fce920.png)

**Comment by photopea** [comment]
Sorry, it should be fixed now!

BTW. did you get my email that I wrote you on 6th of May?
