### ISSUE TITLE
"Define New Brush" bug

### ISSUE THREAD

**Issue by PainterPortraitAnchor** [photopea/photopea#4654]
When defining a new brush and selecting it, attempting to use the new brush either only defines a portion of the object defined as the brush.

Often, when defining a new object as a brush, attempting to use the newly created brush results with a cross-hair cursor instead of the shape of the new brush, causing painting to fail, even when caps lock/alt is not pressed.

**Comment by photopea** [comment]
Could you please describe exact steps, what should I do to see the problem happen myself? And please, do these steps yourself to make sure they really lead to your problem.

**Comment by PainterPortraitAnchor** [comment]
Issue "Solved": Bug Occurs when using Firefox extension "Disconnect".

1: Object is drawn on canvas
2: User selects "Edit"
3: User selects "Define New" 
4: User selects "Brush Tool" from sidebar
5: User selects enters "Pick Brush" menu
6: User selects newly defined brush [Displayed in "Pick Brush" menu without issue; logo is seen of the object defined as brush.]
7: Mouse cursor is turned into small cross-hair
8: User attempts to use newfound cross-hair cursor as brush, this fails / User attempts to use cross-hair cursor as brush, only a portion of the newly defined object is drawn onto canvas.


As this issue stems from a third party extension, I do not believe it is an internal fault with the program- With this revelation comes the closing of the thread.

**Comment by photopea** [comment]
I am very sorry, it is fixed now. Thanks for your help!
