### ISSUE TITLE
Crashing website

### ISSUE THREAD

**Issue by adonysiac** [photopea/photopea#4655]
Hello!

I have some trouble using photopea. When I'm using it on a normal window, the website crashes and tells me that the page has a problem. The only way I found to use the website is to navigate in Private Window.

Thank you in advance!

**Comment by photopea** [comment]
I think you have browser extensions, which are mining bitcoins inside Photopea. Did you try to use Photopea with no extensoins?

Yes, the incongito mode runs with no extensions.

Personally, I dont use any extensions in my browser.
