### ISSUE TITLE
Feature request: "smart filters"

### ISSUE THREAD

**Issue by DizzyHSlightlyVoided** [photopea/photopea#4656]
Photoshop has a feature called "smart filters". Essentially, you can apply filters to a Smart Object, and the filters will affect the appearance in the final image non-destructively, that is, without affecting the contents of the Smart Object (and without having to rasterize and re-apply every effect every time the contents of the smart object is updated).

**Comment by photopea** [comment]
Photopea has smart filters since 2017, did you try it?

**Comment by DizzyHSlightlyVoided** [comment]
... That's odd. It wasn't working on one of the documents when I tried it ... but now it's working just fine.

It's quite possible I had the wrong layer selected due to a misclick or something. This has happened before!
