### ISSUE TITLE
PSD templates little bug

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#4659]
1. Open Photopea
2. Click on PSD Templates Button 
3. Go to top menu and click 'Templates' highlighted tab (templates will turn off - it should do nothing in my opinion - but that is not a bug)
4. Try to click the same button as in point 2. Nothing gonna happen 

BTW. How can I share a link to a specific category to someone?

**Comment by MichalSZZ** [comment]
@photopea thank you. And I am still curious - how do you get a link to the specific template category? I am not see it when I am working on the PWA.

**Comment by photopea** [comment]
You must browse the templates at www.Photopea.com/templates . Only there you can see a link of each page.
