### ISSUE TITLE
Fearture request: layer thumbnail clipped to layer/document

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4661]
difference between them
![image](https://user-images.githubusercontent.com/79258245/169811438-f3acbc1c-0884-4e3c-99ca-fe6c1838b7af.png)

thumbnail clipped to layer is good for us to see what the layer looks like, while thumbnail clipped to document is good for us to see where the layer is. But currently we can't make the thumbnail of shape layer clipped to document or the thumbnail of other layer clipped to layer.

Could you add options in overflow menu of layer panel for switching between these two style?

**Comment by photopea** [comment]
I thought that vector layers should be clipped to layr bounds, while pixel layers to document bounds.

So you say we should clip all types of layers the same way? What should be the default clipping method?

**Comment by photopea** [comment]
I have implemented it. It is available in the menu of the Layers panel.
