### ISSUE TITLE
I've been trying to make a pfp recently, but whenever I used the rectangle tool to make a border it doesn't work 

### ISSUE THREAD

**Issue by Exautled** [photopea/photopea#4664]
Pls If anyone knows why give me advice
![Screenshot 2022-05-23 214600](https://user-images.githubusercontent.com/106130755/169938355-de456455-b24f-4dd2-a567-8f0be4e506ed.png)

**Comment by photopea** [comment]
What exactly does not work? You should either draw a rectangle, or click once to enter rectangle parameters (as in your screenshot).

**Comment by MichalSZZ** [comment]
What position of the stroke do you have?  Not "outside"? You can check it when you expand the "line" near the px width of the stroke

**Comment by Exautled** [comment]
> What exactly does not work? You should either draw a rectangle, or click once to enter rectangle parameters (as in your screenshot).

The overlay for the border it isn't becoming transparent like it usually does

**Comment by Exautled** [comment]
> What position of the stroke do you have? Not "outside"? You can check it when you expand the "line" near the px width of the stroke

It wasn't a stroke

**Comment by photopea** [comment]
What is an overlay?

I recommend you to learn how Photopea works at www.Photopea.com/learn

**Comment by MichalSZZ** [comment]
> 

Do you have the blend mode for your new shape layer set as 'Overlay' in your Layers Palette?
