### ISSUE TITLE
Variables - Export to PDF

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4665]
It will be really useful to have PDF as a export file. 😃

So i can use vectors or create formal documents
![image](https://user-images.githubusercontent.com/11801254/170161489-29ef7942-2326-4655-ac33-f12f6a87e09e.png)

**Comment by MichalSZZ** [comment]
If it will be possible +1 from me.

**Comment by photopea** [comment]
As you know, PDF export does not always show you what you expect.

What options should we use for this PDF export? Should we do it like Adobe Photoshop (always rasterize everything) ?

**Comment by MichalSZZ** [comment]
Selectable texts will be the biggest feature... but we know that isn't possible now (?). And shapes as a vectors. But again - as you wrote - there are many problems with it. 

Before the export it should show us the preview with options - and the user should confirm it and choose what he would like to have.

**Comment by photopea** [comment]
I have added the third "tab", where you can set the export format (JPG, PNG or PDF) and its parameters.

It have updated the manual: https://www.photopea.com/learn/variables

**Comment by TheRadicalDreamer** [comment]
THIS IS HUGE FOR ME!!

THANK YOU IVAN!

I have using third party programs to make this for the last 3 years.

I am going to transfer my work completely to Photopea!!

**Comment by TheRadicalDreamer** [comment]
Oh. Good question.
I can't have the same settings as when you export one?

At least for me I always vectorize the texts, and that's all, but I bet
some people will prefer other settings. Maybe that's why it is better to
modify the variables windows a bit and add the exported file settings.

:)

What do you think?

**Comment by TheRadicalDreamer** [comment]
i believe i miss replied another thread.

All is ok with this one.
