### ISSUE TITLE
Open ai

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4666]
I don't know if this is a problem,but I prefer to share it.

Many times my provider sends me ai files where the work is way bigger than the canvas. And i was wondering if the opening of the ai file in Photopea has something to do. Or it is just them being weird at working.

Here is the file:
[李亿祥书本(1).zip](https://github.com/photopea/photopea/files/8768800/1.zip)

![Screenshot_20220525-031707](https://user-images.githubusercontent.com/11801254/170203578-a3c45ffb-ac47-4340-bd8d-95793504333f.png)

**Comment by photopea** [comment]
I have opened your file in Adobe Illustrator and this is how it looks like:
![image (3)](https://user-images.githubusercontent.com/15955558/170256533-c014b907-5dff-46e9-97ec-44f6cc6b3333.png)

The main difference is, that Illustrator shows elements outside canvas, but Photopea and Photoshop do not.

Why does your provider create such tiny canvas?

**Comment by photopea** [comment]
ok :)

**Comment by MichalSZZ** [comment]
Maybe that file was created in some other program like CAD? Or something like that for machines who understand where to cut paper? And only it was exported to AI for graphic designer who is responsible to add graphics for this product grid?

**Comment by photopea** [comment]
Who knows. I just know that Photopea opens AI files the same as Adobe Illustrator.

Your AI file is ony 23 kB, while AI files are usually over 500 kB.

**Comment by MichalSZZ** [comment]
> Who knows. I just know that Photopea opens AI files the same as Adobe Illustrator.
> 
> Your AI file is ony 23 kB, while AI files are usually over 500 kB.

And that is a good point for my theory that it was exported from some other software like CAD.
