### ISSUE TITLE
Impossible to move layers order without Crash photopea from my Chromebook 

### ISSUE THREAD

**Issue by Githuber229** [photopea/photopea#4667]
Hello

Impossible to move layers order without Crash photopea from my Chromebook google pixelbook go ( chrome OS ) 8Gb ram core i5 8th gen.. please help  thanks

**Comment by photopea** [comment]
Could you try this and let me know if it helped? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
