### ISSUE TITLE
Feature request - Vectorize Bitmap Multiple Layers

### ISSUE THREAD

**Issue by JasperCyan** [photopea/photopea#4668]
![image](https://user-images.githubusercontent.com/64249844/170242288-b5b509a1-3919-40d9-bf9d-4ee657ed9a2c.png)
Multiple selected layers, allow vectorize bitmap, and will vectorize the selected layers. 

or to allow vectorize bitmap to work with actions (does not work at the moment presumbly since it's not standard Photoshop feature)
![image](https://user-images.githubusercontent.com/64249844/170242880-6a4b8183-2b15-4a6a-81d5-3ee33669d54e.png)

Do you think it's possible to add?

**Comment by photopea** [comment]
Simply merge your layers before you vectorize them. I am afraid we can not turn it into an action.
