### ISSUE TITLE
Some unicode characters doesnt work

### ISSUE THREAD

**Issue by yozdas** [photopea/photopea#4669]
This unicode (U+10C27): 𐰧 belongs to Old Turkic does not work, i did not tried the rest.
https://unicode-table.com/en/10C27/

**Comment by photopea** [comment]
What font are you using? You need a font that supports this character.

Do you think there exists a font in the world, where the author drew a picture for this character? I really don't think that when a person makes a font, they draw hundreds of thousands of characters to cover the whole Unicode.

**Comment by yozdas** [comment]
it is weird because layer's font supports the unicode,
the font i use is DejaVu Sans, which also supports U+2706: ✆ 
what font name is used for layer's text?
![Screen Shot 2022-05-26 at 16 28 16](https://user-images.githubusercontent.com/37111998/170497312-38230d8f-e92b-4818-bddf-d228c4c32a07.png)

**Comment by photopea** [comment]
I dont know about browser :( 

We use "Open Sans" in our CSS, but I think a browser has a database of all Unicode characters, in case the webpage font does not contain that character.

**Comment by yozdas** [comment]
So it doesnt have a solution. Thank you.

**Comment by photopea** [comment]
Just find a font which contains that character, and load it into Photopea using File - Open.

The solution is the same for Photopea, MS Word, Adobe Photoshop, etc. You need a font first to be able to type that character.
