### ISSUE TITLE
Why Do I Need To Accept Trackers?

### ISSUE THREAD

**Issue by TheIanKirby** [photopea/photopea#4670]
I turned off the ad-block feature on Opera but left I on the tracker-blocker. Ads won't display. Isn't there a way for the ads to display without needing trackers?

**Comment by photopea** [comment]
I don't know what Opera means by Trackers. We just need to access specific domains for our ads to work properly.

Maybe ask Opera about it. They will add www.Photopea.com to their list of trackers once. You should not ask us why, you should ask them.

**Comment by TheIanKirby** [comment]
Sorry, I meant to clarify that Photopea responds with "Ad Blocking Detected" even when Tracker-blocking is the only option enabled. Ads still show when both options are off. Thanks for your time.
