### ISSUE TITLE
Feature request: smoother experience of zooming

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4672]
In Photoepa, when hold Alt and scroll mouse wheel, the zoom levels are changed to a specific value. For exmample I zoom in canvas start from 25%, the values will be 25%-33.33%-50%-66.67%...
In Photoshop, instead of specific value,the value increases by 1/10 for each upward roll and decreases by 1/11 for each downward roll. For example I zoom in canvas start from 50%, the values will be 50%-55%-60.5%-66.55%... The experience is much smoother.

**Comment by photopea** [comment]
Ok, I made it work the same as in Adobe Photoshop. The "wheel step" changes the zoom by 10%.

Note, that if you start e.g. at 200%, you can never get to 100%, or 50%, or 300% using a mouse wheel (in Photoshop and now in Photopea, too).

**Comment by photopea** [comment]
It depends on the settings of your mouse wheel / trackpad etc. Many mouses have wheels with no "steps", it can be turned smoothly.

**Comment by photopea** [comment]
It is the same for me.

**Comment by photopea** [comment]
Could you try to scroll with two fingers on a touchpad?
