### ISSUE TITLE
Commonly used fonts are gone

### ISSUE THREAD

**Issue by KeremArdicli** [photopea/photopea#4673]
Commonly used fotns like Times New Roman or Arial is now gone.

**Comment by photopea** [comment]
We never had such fonts. 

We never had a licence to provide such fonts. If you need Arial, you can buy it here and load it into Photopea: https://www.fonts.com/font/monotype/arial

**Comment by KeremArdicli** [comment]
I thought these are free fonts. Sorry for taking your time.

**Comment by photopea** [comment]
If you have Microsoft Windows, you already paid for them when paying for Windows. So just load the TTF files into Photopea.

**Comment by KeremArdicli** [comment]
fantastic. it works like a charm. this is the best ever web app i have ever used. gib kudos to you...

P.S. My ad blocker is not active only for your page...
