### ISSUE TITLE
Feature request: alert "undo ..." when tap on canvas with two finger

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4675]
Sometimes I don't know that I undo a step accidentally. It would be helpful if there can be a alert. 
Like this
![image](https://user-images.githubusercontent.com/79258245/170701079-f0e24812-938e-48f3-9160-628eb7a82a1d.png)

**Comment by photopea** [comment]
I think such popping messages would bother many users. I think you should learn not to undo things accidentally over time.
