### ISSUE TITLE
Scale issues and move tool

### ISSUE THREAD

**Issue by Strange-Watermelon** [photopea/photopea#4676]
I use Firefox for Photopea and recently the move tool doesn't move layers unless the cursor is on the layer, I tried this with Chrome and it seems to work normally.

I am unable to use lock aspect ratio and center scale with the Shift and Alt keys on both browsers while scaling layers. (Edit: I have read https://www.photopea.com/tuts/new-free-transform/ and i understand now)

**Comment by photopea** [comment]
I think you have enabled the Auto-select feature: https://www.photopea.com/learn/layer-manipulation

**Comment by Strange-Watermelon** [comment]
It works now thank you!
