### ISSUE TITLE
Ads work in Brave But still photopea detects it as ad blocker 

### ISSUE THREAD

**Issue by egyleader** [photopea/photopea#4677]
In brave browser , if you disabled the ads and tracker blocker built in in the browser the ads show probably as shown in this screenshot ,,  but photopea still detects it as an ad blocker and bother me with messages ,, 

![Screenshot_20220528_181134](https://user-images.githubusercontent.com/31688162/170833719-94b1c7aa-a538-4abe-9633-ca08ec2975e3.png)

**Comment by photopea** [comment]
It is not possible to prevent Brave from blocking ads. You can ask Brave to fix it, or use a different browser.

See here: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/
