### ISSUE TITLE
Free transform doesn't appear to be working (on mac at least)

### ISSUE THREAD

**Issue by greatgrapescreative** [photopea/photopea#4679]

**Comment by photopea** [comment]
Maybe you need to read this: https://www.photopea.com/tuts/new-free-transform/

If it does not help, tell us, what exactly is happening in your case, and what do you want to happen instead.

**Comment by greatgrapescreative** [comment]
Good morning,

Thank you for this information. Maybe I used the wrong wording. I am trying to warp lettering to mold around different surfaces. I used to just single click the transform… border or whatever its called and it would turn from 9 squares to 16. At that point I could free warp the word. I don’t  see that as an option any longer. I hope this makes sense. Thank you for your help!

**Comment by photopea** [comment]
That is called a Warp and it is not available for text layers. You must convert your layer into a vector shape, or rasterize it.

You can also buy a book about Adobe Photoshop to learn how these things work.
