### ISSUE TITLE
Advert covering the screen

### ISSUE THREAD

**Issue by philbradshaw** [photopea/photopea#4681]
Every few seconds an advert completely fills the screen stopping me using the product.

![image](https://user-images.githubusercontent.com/36735364/170949737-1505903c-538b-438a-98ed-47495113cab9.png)

**Comment by photopea** [comment]
Hi, could you try to use Photopea wit **absolutely all** your browser extensions disabled? Does it still happen?

In all previous cases, a browser extension was inserting these ads into Photopea.

**Comment by philbradshaw** [comment]
Hi 

No, its not that. I use Firefox and I turned off all the extensions. Still get the problem sometimes. Its always the same ad - for The North Face. I think its to do with that ad.
regardsPhil

    On Monday, 30 May 2022, 09:37:28 BST, Photopea ***@***.***> wrote:  
 
 


Hi, could you try to use Photopea wit absolutely all your browser extensions disabled? Does it still happen?

In all previous cases, a browser extension was inserting these ads into Photopea.

**Comment by photopea** [comment]
Could you share a screenshot of "about:addons" ?

**Comment by philbradshaw** [comment]
Attached as requested.
Phil

    On Monday, 30 May 2022, 12:14:51 BST, Photopea ***@***.***> wrote:  
 
 


Could you share a screenshot of "about:addons" ?

**Comment by photopea** [comment]
To what address are you sending emails?

**Comment by philbradshaw** [comment]
just responding to the email sent to me

    On Monday, 30 May 2022, 12:58:46 BST, Photopea ***@***.***> wrote:  
 
 


To what address are you sending emails?

**Comment by photopea** [comment]
Please, discuss with us at a website https://github.com/photopea/photopea/issues/4681 .

Github has some bugs with their emails. Always discuss at a website where you posted your question.

**Comment by photopea** [comment]
I have to close it because of lack of details.
