### ISSUE TITLE
New project pick up width & height of the clipboard's image

### ISSUE THREAD

**Issue by thang1160** [photopea/photopea#4682]
I think this feature will save a ton amount of time. 
It will be more convenient for users to copy an image from the internet, create a new project and paste it. Instead of downloading & open it, plus they may have to delete it from the computer later.

**Comment by MichalSZZ** [comment]
But it works in that way for me. Make sure that you have enabled the permission to use a clipboard in Photopea. And you are copying from Chrome (for example) and paste in Photopea opened in Chrome. There is a problem with copying to clipboard from Firefox and pasting to Photopea that is opened in Chrome PWA version.

**Comment by thang1160** [comment]
I see, It doesn't work for me because I use Firefox

**Comment by photopea** [comment]
I was wrong, only Firefox and Internet Explorer don't support this feature, see https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem#browser_compatibility

You can ask Firefox to fix it, or switch to a better browser.
