### ISSUE TITLE
Outer glow for layer - wrong rendering for semitransparent pixels [from Reddit]

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#4685]
I tested it and the same file made in Photopea looks different after opening in Photoshop.

It is not my issue - https://www.reddit.com/r/photopea/comments/uzm7lt/outer_glow_only_working_on_painted_pixels_with_40/

and here is prepared by me for the test file https://www.photopea.com/#iVp-tvd4i

**Comment by photopea** [comment]
it should be fixed now. I hope I did not break other effects. The Stroke effect could be a bit thicker now.
