### ISSUE TITLE
desktop version of photopea won't close

### ISSUE THREAD

**Issue by fivecent-dime** [photopea/photopea#4686]
the desktop version of photopea in linux won't close unless I use a task manager or terminal

**Comment by photopea** [comment]
Do you mean you installed Photopea with More - Install Photopea? Or what is the desktop version?

**Comment by Mwalters75** [comment]
> Do you mean you installed Photopea with More - Install Photopea? Or what is the desktop version?

I think they're talking about [this](https://www.flathub.org/apps/details/com.github.vikdevelop.photopea_app)

**Comment by photopea** [comment]
I don't know what that is. They should ask the author of that thing.

**Comment by yikuansun** [comment]
I know Electron.js has issues where it won't handle the "Leave site?" dialog properly. Try saving or closing all of your Photopea documents before closing the app.
