### ISSUE TITLE
Feature request: Mixer Brush (Willing to Pay for this Tool) 

### ISSUE THREAD

**Issue by Phealoon** [photopea/photopea#4687]
As I have been using Photopea for some time now, I have noticed that there is no way to smoothly blend colors. ( Smudge, Blur, Gradient, etc) and other approaches simply won't do the job. I would be willing to pay for this tool as it is ESSENTIAL for serious painting projects. Please give this option some serious thought before closing this thread.  Thank you so very much, Ivan, God Bless you.

(Please refer to this video for an example) https://youtu.be/EsFf9mQ0Upo?t=264

**Comment by photopea** [comment]
Have you tried the Smudge tool with different parameters at the top?

**Comment by photopea** [comment]
Ok lets discuss it there: https://github.com/photopea/photopea/issues/3985

**Comment by LaOLaS** [comment]
for me as well this tool is very important and essential, I'm also willing to support the development if this feature can be implemented faster (I took the distributor license and if this feature will not come than I will not extend it :(...

and smudge tool is definitely not the same.
