### ISSUE TITLE
Requesting unified transform tool.

### ISSUE THREAD

**Issue by jointri** [photopea/photopea#4690]
[Unified Transform](https://docs.gimp.org/en/gimp-tool-unified-transform.html) is a godsend from GIMP that I would love to see in photopea.

It combines several tools: [Rotate](https://docs.gimp.org/en/gimp-tool-rotate.html), [Scale](https://docs.gimp.org/en/gimp-tool-scale.html), [Shear](https://docs.gimp.org/en/gimp-tool-shear.html) and [Perspective](https://docs.gimp.org/en/gimp-tool-perspective.html), performing one or several of these actions at once in one single operation. Combining two or more options gives you almost infinite possibilities of transformation.

Could you consider please implementing such a tool? It would be highly convenient.

**Comment by photopea** [comment]
I think our Free Transform tool can do all that. It has been in Photopea since 2013.

Do you know how our Free Transform tool works? https://www.photopea.com/learn/free-transform

**Comment by photopea** [comment]
I have to close it because of lack of details.
