### ISSUE TITLE
Custom Shape tool aspect ratio

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4691]
Using Custom Shape tool it is not possible to keep aspect ratio of orignal shape.
I can set any ratio but I don't know what original ratio of image (as shown in preview) is.
Only way I found was making screenshot of preview of shape and measuring its width and height which is very uncomfortable.
Screenshot:
![image](https://user-images.githubusercontent.com/6370548/171720036-79018b81-0d33-4637-b448-4adcb739406d.png)
How can I insert it with original ratio of width and height?

**Comment by TheRadicalDreamer** [comment]
did you hold shift when inserting the shape?

**Comment by hxim** [comment]
> did you hold shift when inserting the shape?

Yes it added 1:1 when holding shifft and not original ratio

**Comment by MichalSZZ** [comment]
Some time ago I have added that as a problem to fix. https://github.com/photopea/photopea/issues/1362 and then was fixed by Ivan (or I didn't check it proper). And second one https://github.com/photopea/photopea/issues/1377

**Comment by photopea** [comment]
I think I made it work like this because of some actions. But I don't remember what it was, so I have reverted back to the way it used to be.
