### ISSUE TITLE
Open from decive, what does it do?

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4692]
![image](https://user-images.githubusercontent.com/11801254/171877878-f68bc711-1b0a-461e-9483-3e04ebc03516.png)

i cannot open any file, but folders when i select that option on the home screen.p

**Comment by photopea** [comment]
You should select a folder in your computer. Then, Photopea will get access to that folder (it can create new files, delete files, etc).

**Comment by TheRadicalDreamer** [comment]
AAAAAAAAAAAA

I didn't know that

**Comment by photopea** [comment]
okay :)
