### ISSUE TITLE
Vectorize Text does not work when exporting as PDF?

### ISSUE THREAD

**Issue by benpeco** [photopea/photopea#4693]
Vectorize Text option when Exporting .psd to .pdf is no different between the two files (see attached).

[Page5 (1).pdf](https://github.com/photopea/photopea/files/8834935/Page5.1.pdf)
[Page5.pdf](https://github.com/photopea/photopea/files/8834936/Page5.pdf)

**Comment by photopea** [comment]
Hi, your PDF contains only one raster image, there are no text layers. What exactly is the problem?

**Comment by benpeco** [comment]
I'm working with .psd files with text layers on Photopea. When I export the file as .pdf, and tick the box to vectorize text, the text does not vectorize.

**Comment by benpeco** [comment]
Here you go https://www.dropbox.com/s/677829z6iezf4xk/Page5.psd?dl=0

**Comment by benpeco** [comment]
Thank you, this effectively answered my question, however if I do not raster the file my mask layers do not work properly, but I think this is more of a general photoshop knowledge question I'll need to research and figure out. Thanks

**Comment by MichalSZZ** [comment]
@photopea is it possible to have restarized all graphics but have text as vector in PDF?

**Comment by photopea** [comment]
@MichalSZZ Sure, but what if a pixel layer covers a part of text?

Do you have problems with PDF looking too much different than a PSD? I think we can keep improving it, step by step.
