### ISSUE TITLE
Pressing Enter does not line break in text box, writes over same line

### ISSUE THREAD

**Issue by benpeco** [photopea/photopea#4694]
I am working on a .psd file that when I am writing a line of text in a text box, then press enter, the cursor does not advance to the next line down, but instead writes over top of the line of text I just wrote.

**Comment by photopea** [comment]
Maybe you set the Leading value to zero? Did you learn how to use Photopea before using it? https://www.photopea.com/learn/text-style

**Comment by benpeco** [comment]
Apparently the text boxes that were previously created kept unticking the 'Auto' box in Leading automatically, even per line. With 'Auto' ticked it works properly. Thanks
