### ISSUE TITLE
photopea keeps damaging frames

### ISSUE THREAD

**Issue by skywalker005** [photopea/photopea#4698]
each time i try to make a gif right now, it says the frames are damaged.  there is hardly any editing at all, and i don't touch the frames at all before putting them into photopea.  the process is 1:1 crop, resize to 80x80, smart sharpen 150% radius 1.0.

**Comment by photopea** [comment]
Are you exporting a GIF from Photopea and it does ot work? Could you share your document with us, as it looks at the moment before the export? You can send a PSD file to support@photopea.com

**Comment by photopea** [comment]
I have to close it because of lack of details.
