### ISSUE TITLE
Photopea will not let me install the app?

### ISSUE THREAD

**Issue by RileyTasticPlays** [photopea/photopea#4699]
I tried different browsers but for some reason the "Install Photopea" button is dimmed and I can't click on it. Is this intentional?

**Comment by costorella** [comment]
> I tried different browsers but for some reason the "Install Photopea" button is dimmed and I can't click on it. Is this intentional?

No need installation

**Comment by photopea** [comment]
Sadly, this works only in Chrome and Edge :( Aslo, check if Photopea is not installed already (in  about://apps )

**Comment by photopea** [comment]
I have to close it because of lack of details.
