### ISSUE TITLE
Freezes continually in Chrome Browser and menus are unresponsive

### ISSUE THREAD

**Issue by ChiefMonkey** [photopea/photopea#47]
Continually freezing.  Menus don't work such as the layers won't select but double clicking still opens the properties.  Really good idea but still too many bugs and problems to use.

**Comment by photopea** [comment]
Hi, we never noticed anything of what you mentioned. Can you be more specific? What are the steps to make Photopea "freeze"?

**Comment by tomasnosek** [comment]
I have no freezes too. Chief, try another browser to be sure there is no problem with your browser or some extension.

**Comment by photopea** [comment]
I have to close it because of the lack of details :( feel free to reopen it.
