### ISSUE TITLE
Export multiple vector layers as SVG

### ISSUE THREAD

**Issue by prudas** [photopea/photopea#470]
Hello,

firstly I would like to thank you for great job you have done! I am sorry in forward if this is possible and I am only lack of knowledge all possibilities of Photopea.

Problem: I miss the possibility to export multiple vector layers as SVG (I can download each one as separate SVG vector graphic (by selecting object, rightclick, get SVG), but I am not able to select more layers (or one folder) and when I merge layers they "lost"? vector information and are downloaded only as SVG containing base64 encoded graphics)

It is useful when I have graphical manual in svg (or design in sketch etc.) containing more icons represented as groups of shapes for example.

<img width="1371" alt="snimek obrazovky 2018-02-01 v 10 29 32" src="https://user-images.githubusercontent.com/8956118/35671157-d4445cb4-073a-11e8-946d-7e4abf9d921c.png">

Example SVG: [marker.svg](http://prudek.com/marker.svg)

Here is what I get after merging layers:
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 49" width="32" height="49"><defs><image width="32" height="49" id="img1" href="data:image/png;base64,iVBORw0KGgoAAAANSUh...</svg>`

and what I need is:
`... </g><path d="M16,0 C7.178,0 0,7.178 0,16 ...
`

**Comment by photopea** [comment]
Hi, I have added the Get SVG button into the top menu. It will download all selected layers as one SVG file. 

You can lear here how to select layers: https://www.photopea.com/learn/layers  Thanks! :)

**Comment by prudas** [comment]
Thank you for really fast reply and feature, which worked fine for my purpose.

I noticed some differences between original and exported svg (just for your improvements of Photopea, I am perfectly happy with solution for now). I also experienced padding problem in many online svg convertors I have used so far.

Same example SVG (generated in Sketch app): marker.svg
<img width="281" alt="snimek obrazovky 2018-02-03 v 12 00 21" src="https://user-images.githubusercontent.com/8956118/35766528-b5646144-08da-11e8-895c-f0bba0631c23.png">

Photopea - open file - select top layer directory (Page-1) - get SVG
<img width="285" alt="snimek obrazovky 2018-02-03 v 12 01 49" src="https://user-images.githubusercontent.com/8956118/35766552-eeaa94d2-08da-11e8-803f-4e72c47abe10.png">

Photopea - open file - export as SVG (settings all defaults)
<img width="215" alt="snimek obrazovky 2018-02-03 v 12 09 59" src="https://user-images.githubusercontent.com/8956118/35766567-2bf6a0b0-08db-11e8-9e65-403035fca929.png">

1. Black background:
There are two layers in icon (path id="path-2..) - one black, one white (don't ask me why..) and I guess that their order matters.

2. Extra padding:
See in the screenshots

Daniel

**Comment by photopea** [comment]
The black layer in Oval-4 has quite an advanced filter. Photopea can not convert such filters into PSD right now. I am not even sure if it would be possible.

The padding is caused by blurry edges. Photopea expands the image to fit the whole blurry path, which may be larger than the original path. If you delete the black blurry circle, there will be no padding.

**Comment by photopea** [comment]
BTW can you load this SVG back into Sketch and get the original content?

**Comment by prudas** [comment]
Thank you for explanation.

BTW answer -> Yes, colleague successfully loaded PhotopeaExportedSVG into Sketch and exported it as same SVG (without blurry edges, probably uses just different export approach though ) - same as before.

I think export works OK then.
