### ISSUE TITLE
impossible to modify a smart filter after having applied it.

### ISSUE THREAD

**Issue by costorella** [photopea/photopea#4700]
hello, before buying a one year license of photopea i would like to report a bug. When using a dynamic filter on a dynamic layer from an ipad (safari or chrome or firefox) it is impossible to reopen the parameters via the gear as on a pc for example. It just doesn't do anything and I can't find the menu that would change the dynamic filters once applied. thank you

**Comment by photopea** [comment]
I am very sorry, it should be fixed now.

**Comment by costorella** [comment]
Thx, it's work with bluetooth mouse connected but not with finger or pencil. Thank you for your quick reply

**Comment by photopea** [comment]
Try to reload Photopea. It should work fine with a finger, you need to double-click it.
