### ISSUE TITLE
Focus Stacking - enhancement request

### ISSUE THREAD

**Issue by lasabine** [photopea/photopea#4701]
Sorry if this isn't the place to post this (not sure where to ask this), but does Photopea have "focus stacking" capabilities? If not, is it possible to add this functionality? Thanks again for your fantastic work!

**Comment by photopea** [comment]
Sure, we could add it! Could you provide some of your photos to us, for testing? :)

**Comment by lasabine** [comment]
Hello!

That's great to hear!

So here are 300 truffle pics (RAW-DNG) that I shot with a Nikon Z5.

I've included the final focus stacked truffle pic for your reference as
well (I used Helicon Focus 8 to do this).

I had to convert the RAW-NEF files to RAW-DNG to do the focus stack within
Helicon.

If you need anything else, please let me know.

Thank you for all of your hard work!

Regards,

Leila

 300 Truffle Pics-RAW-DNG_Nikon Z5.zip
<https://drive.google.com/file/d/1GLfLEohVq4ZQXtAeCrcrYCrtAZUciKHJ/view?usp=drive_web>
 Truffle - Focus Stacked_Final - 2022-05-14 11-2...
<https://drive.google.com/file/d/1eKVDgfA1T_IFmuyJC_nF2Yc44DlyEWoc/view?usp=drive_web>

**Comment by photopea** [comment]
Could you send me 5 - 10  JPG images to support@photopea.com ? If you share it on Google Drive, make sure they are accessible from the Incognito mode, and not only from your account.

**Comment by photopea** [comment]
I have implemented this feature! Here is a tutorial: https://www.photopea.com/tuts/focus-stack-images-online/

**Comment by lasabine** [comment]
You are amazing!!! Thank you so much!

**Comment by lasabine** [comment]
Hi! I opened 1 image and then I followed the next step "Open and Place" (I selected 99 JPEG photos) and then I get this error message  "Not enough RAM, need 41 MB"  and "Not enough RAM, need 92 MB". Also, the RAWS aren't loading as layers. Got any suggestions for these issues?

<img width="554" alt="image" src="https://user-images.githubusercontent.com/73072252/174419987-1a56e83b-f307-4b00-b16d-6c2838a17bc1.png">
<img width="552" alt="Screenshot 2022-06-17 220512" src="https://user-images.githubusercontent.com/73072252/174420306-432d2691-8113-483f-8c12-d7415cb8b3fd.png">

**Comment by photopea** [comment]
Currently, each RAW needs to be manually "confirmed" in RawPea window, to be opened as a regular document. You will need to do this for each RAW file.

Your images ar 24 MPx, so each requires 100 MB of RAM. To open 100 of them, you need 10 GB of free RAM. The stacking method requires about 400 MB per image, so you will need 40 GB of RAM.

If you don't have enough RAM, try to merge each each 10 images together, and then merge these 10 results together.

Also, I think your focus steps are too small. Try to merge only images 1, 5, 10, 15, 20, 25 ... maybe that is enough.
