### ISSUE TITLE
Unable to drag images and elements while running inside of VMware workstation/player & Linux

### ISSUE THREAD

**Issue by rbreaves** [photopea/photopea#4702]
So in my case I am running Ubuntu 22.04 and MS Edge to be specific. I do see this error in the console when trying to move layers or resize images, it all fails to do anything, just stays static. Also cannot create a selection box or anything like that.

[.WebGL-0x270000364600]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels (this message will no longer repeat)

**Comment by photopea** [comment]
That sounds like a bug in your browser. Could you try these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

If your system can not run WebGL properly, could you disable it in More - Use WebGL?

**Comment by photopea** [comment]
Photopea can not work without Webassembly.

Did you try More - Use WebGL in Photopea, as I told you?

**Comment by rbreaves** [comment]
Wasn’t an option under more so I have no idea what you’re talking about under edge or chrome.

**Comment by photopea** [comment]
There is a button "More" at the top of Photopea.com 

![image (1)](https://user-images.githubusercontent.com/15955558/172550301-e8b25882-5d3e-4a47-9772-db4c0333d2bf.png)

**Comment by rbreaves** [comment]
Oh.. in the app. Well the browser has more too lol. Will check it later.

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by rbreaves** [comment]
It’s very specific to VMware - it’s really their fault on not implementing OpenGL properly I think.
