### ISSUE TITLE
Vanishing point ?

### ISSUE THREAD

**Issue by costorella** [photopea/photopea#4703]
here I started yesterday a photopea license but I do not see the vanishing point option.

**Comment by photopea** [comment]
We do not have such feature in Photopea. It should be added soon.

If you want a refund, send us some details of your payment to support@photopea.com

**Comment by costorella** [comment]
> We do not have such feature in Photopea. It should be added soon.
> 
> If you want a refund, send us some details of your payment to [support@photopea.com](mailto:support@photopea.com)

No no, I don't want a refund. I love photopea and I support the project. So I will wait wisely ;)
