### ISSUE TITLE
希望可以自定义快捷键

### ISSUE THREAD

**Issue by hmhlonely** [photopea/photopea#4704]
![image](https://user-images.githubusercontent.com/32634045/172361724-ea6ff0ac-84aa-420c-b020-f004e6000c2b.png)
这两个我不常用，想自己设置鼠标滚动就是缩放

**Comment by MichalSZZ** [comment]
In Photopea you can not set your own key shortcuts. These are the same as in Photoshop. You should use them as they are now. That is a browser limitation.

**Comment by photopea** [comment]
Sorry, I do not speak Chinese :(
