### ISSUE TITLE
(Not an bug or issue, just a suggestion) can you please add 3d extrusion?

### ISSUE THREAD

**Issue by CoderBro6** [photopea/photopea#4705]

**Comment by photopea** [comment]
what is that?

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by MichalSZZ** [comment]
In Photoshop, long time ago, there was something like 3D Extrude and Bevel like in Illustrator has. Easy tool with own window to edit properties.

But they removed that years ago. Later they have added really advanced 3D functions. But as I know... Adobe will remove it once again and move it to Dimension.

Simple 3D extrude is nice tool. For example if you want to rotate layer in 3D space and add depth to it (height).

https://youtu.be/AIpjwt4xIEI very short video how does it work in Illustrator

**Comment by photopea** [comment]
I have noticed that people often do it by making many copies of a layer: [photopea.com#tGrEBNpQ0](https://www.photopea.com/#tGrEBNpQ0)

**Comment by ANDREI12333** [comment]
@photopea A way to do it natively would be prefered.

**Comment by ANDREI12333** [comment]
> We have added a "3D" Layer Style.

Well. There is no way to rotate it in 3d like up, down, right or left.

**Comment by photopea** [comment]
No, Photopea is a 2D editor, not a 3D editor.
