### ISSUE TITLE
Vector Mode - Drop shadows through the text 

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4706]
![image](https://user-images.githubusercontent.com/11801254/172480684-6004ce42-f4a9-41c8-adbd-ad250133632d.png)

**Comment by TheRadicalDreamer** [comment]
When you have a drop shadow on a text layer, and you are on Vector Mode, you can do a zoom and the drop shadow goes over the text, watch the video:

https://user-images.githubusercontent.com/11801254/174679290-68a9b250-77d6-4b2b-894c-68f3eba3c42b.mp4

**Comment by photopea** [comment]
I am afraid it is a limitation of our current solution. You can not use a stroke and a drop shadow simultaneously. It requires (fill) + (stroke), but our solution performs (fill shadow) + (fill) + (stroke shadow) + (stroke) - stroke shadow on top of fill

**Comment by TheRadicalDreamer** [comment]
But this is only visually.

![image](https://user-images.githubusercontent.com/11801254/175577088-e78dc0d3-4b73-4f55-8753-33f1dff46bfd.png)

And only on certain zoom.

You really can't solve it?

**Comment by photopea** [comment]
In your PDF, the drop shadow is rasterized, you will see pixels when you zoom in (so it is actually a raster mode). In Photopea Vector Mode, we need the shadow to be zoomable, too.

**Comment by TheRadicalDreamer** [comment]
XD

I still don't get it.

Why it goes over the text font when on zoom in, but not in zoom out?

**Comment by photopea** [comment]
All these errors are fixed now! The vector mode is a step closer to the raster mode (and also zoomable) :)
