### ISSUE TITLE
change DPI deletes some shapes!

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4708]
https://www.photopea.com/#i8Am2VuOW

Go and change the DPI of the file, the i should dissapear

![image](https://user-images.githubusercontent.com/11801254/172501843-6a361760-4757-4866-b8ec-73893397fb27.png)

**Comment by photopea** [comment]
This comes from the time, when Photopea auto-detected live shapes in PSD. The dot over "i" was detected as a rectangle, and the bottom part was thrown away.

So in short, your PSD is damaged. Photopea should not produce PSDs like this anymore. Export your file as a SVG, and load it back, to get a fixed PSD.
