### ISSUE TITLE
Error opening file to Photoshop

### ISSUE THREAD

**Issue by EzhovIgor** [photopea/photopea#471]
After converting the file from the sketch to psd, the file does not open in Photoshop. Error: could not complete your request because the file is not compatible with this version of photoshop.
What could it be? The file is broken? Or something with the version of Photoshop? Prompt. Thank you.

http://joxi.ru/v29GVPuGM4ezrG

**Comment by photopea** [comment]
Hi Igor, can you please send me your original Sketch file to support@photopea.com ?

**Comment by EzhovIgor** [comment]
Has sent. I forgot the title of the letter, I'm sorry.

**Comment by photopea** [comment]
Hi Igor. Thanks for the file. I fixed the problem, you can use it now.

When we convert a Sketch into a PSD, we give each PSD layer the name of the original Sketch layer. Apparently, Photoshop can not open a PSD, when some layer name is longer than 256 characters.

Some of your layer names had more than 400 characters, so I "crop" them and use just the first 256 characters for the new PSD layer. The new PSD works with Photoshop now.

BTW. the Montserrat font, so it supports Cyrillic now.

**Comment by EzhovIgor** [comment]
Hey. Very strange. I do not have such long names for layers. I'll try again, thanks for your time and your work.

**Comment by EzhovIgor** [comment]
Excellent! Everything worked out! Wonderful service.
