### ISSUE TITLE
Gradient fill doesn't show anything

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4710]
![image](https://user-images.githubusercontent.com/11801254/172555755-ec617fd4-2024-463f-b4e6-71419c91097d.png)

This bug has been for almost a month now.

When i have a gradient fill, it does not show anything on the thumbail

**Comment by MichalSZZ** [comment]
I have that problem too. No gradient preview in fill thumbnail.

**Comment by photopea** [comment]
sorry :/ it is fixed now!
