### ISSUE TITLE
the pen stroke don't have some options

### ISSUE THREAD

**Issue by Randmaster123** [photopea/photopea#4712]
the pen stroke has no options to choose a brush type as a stroke, nor does it have a pressure simulation effect.

![image](https://user-images.githubusercontent.com/78036272/172722725-1e4883e4-17d9-42d9-b4af-44e3b7867762.png)
![image](https://user-images.githubusercontent.com/78036272/172723980-af0ae926-e0e5-40e0-bc89-1d4a35703c0c.png)

I want to do something like this: https://youtu.be/LreOh9Djy4U?t=277

Photopea is very useful, but since I use a mouse to draw, I find it tedious having to edit each stroke to make it thinner or thicker, and since I can't use the brush for that either because I only use a mouse...

I just have to report the problem...

(I'm an spanish speaker so my english may be bad)

**Comment by popbee** [comment]
That's a feature request of no small feat. 

I mean, it's not "missing" options, it's a whole new feature you are asking! lol :)

**Comment by Randmaster123** [comment]
well, we can take my problem like a new idea to improve photopea. 
(I realized what do you mean, and yeah LOL, but since they have different caps, adding a triangle cap or something similar would be enough)

**Comment by photopea** [comment]
I have implemented the missing feature, it all should work now.

Please, follow your video precisely! First of all, you are drawing in the Shape mode, while they are in the Path mode (Trazado)
![image](https://user-images.githubusercontent.com/15955558/174410979-b3108f72-8bb1-487d-9260-39ef14aa5164.png)

Learn more here: https://www.photopea.com/learn/vector-graphics  https://www.photopea.com/learn/vg-creating

Then, just stroke the path with the Brush, like they do in your video.

**Comment by popbee** [comment]
@photopea 
Just tried it and clicked on "Shape" and the Color Picker is opening (?)  Am I doing something wrong?
![image](https://user-images.githubusercontent.com/1083830/174448855-bfd0b412-20d0-4106-9cad-019c0de8e96a.png)

**Comment by MichalSZZ** [comment]
@popbee everything is fine. That button makes shape from your path (path is not a layer, it hasn't any fill or stroke). When the new layer appears - you have to choose color for new shape.

**Comment by photopea** [comment]
If you still refuse to learn Photopea at www.Photopea.com/learn, or buy a book about Adobe Photosohp, I would recommend you to follow the Youtube video precisely. Then, let us know which second of your Youtube video did not work in Photopea.

**Comment by popbee** [comment]
Thank you @photopea, I was indeed confused and spoke too fast, sorry about that. I did some more research now.  (I am just trying to help here.)

Indeed it **all works fine like the video that was posted**. But I maybe @Randmaster123's use case would be better suited with the `Simulate Pressure` feature normally found in Photoshop's `Stroke Path with ...`?

![image](https://user-images.githubusercontent.com/1083830/174490679-6047b40a-f69e-47c1-a3c5-a02d003c700a.png)

This applies a synthetic *pressure curve* along the length of the path when stroking. For this to do anything, you need to have `Pen Pressure` controlling some brush parameters. The `Fade` option I think is not well suited to simulate pressure (it's fixed length and only fades off).

![image](https://user-images.githubusercontent.com/1083830/174491341-981a5704-19be-4bc7-ba44-87f4fc6c25b0.png)

![image](https://user-images.githubusercontent.com/1083830/174491289-4073cb82-4fee-4ccc-8a5f-0b8da9fa6c0b.png)

The feature is visible with `Stroke Path...` in the `Path`'s right-click context menu or the similar option in `Pen+Path` tool's right click menu on the canvas. Clicking the bottom bar's `Stroke Path with Brush` will not show a popup with the option (same as Photopea). But you already do have a menu when using the `Pen` tool, so maybe you could add this there OR have a Preferences to `Simulate Pressure on Stroke Path with Brush`. I assume someone that wants this might want this option always. You still have to enable pen pressure controls for this to work.

![image](https://user-images.githubusercontent.com/1083830/174492175-e0cb698d-3da4-4793-ad5c-5c9a2ae5419e.png)

Unless you have this feature hidden somewhere I can't seem to find it.
my 2 cents.

**Comment by nickolasjadams** [comment]
@popbee Really composed and well written response for what I feel was a little bit of unwarranted rudeness in their response. 
I also came here looking for how to simulate pressure like I have in photoshop. it's fine that it's not as easily attained in photopea, but I agree that it would be a very nice improvement.

Really appreciate this software and all the sweat that's been poured into it anyways. It's an amazing feat.

**Comment by photopea** [comment]
We already have the "Simulate pressure" option in Photopea.

![image (2)](https://github.com/photopea/photopea/assets/15955558/8207fc9f-de1f-45cb-9c49-7398e5825406)

**Comment by nickolasjadams** [comment]
For everybody who wants to know how to get that Stroke Path dialog box.
On Mac you hold the option key down and click the stroke path button.

<img width="258" alt="image" src="https://github.com/photopea/photopea/assets/15788998/0689f612-572a-4087-b71f-92101ad0f036">
