### ISSUE TITLE
Vector Mode - Text returns to original position after switching modes

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4713]
https://www.photopea.com/#iswIydfbb

If you change from raster to vector mode,  the text: 40x40 will move

**Comment by photopea** [comment]
I just tried and it is not moving :( are you sure you tried it at your link?

**Comment by TheRadicalDreamer** [comment]
No, it does not happen.

And my local copy does not happens now :(

**Comment by TheRadicalDreamer** [comment]
https://user-images.githubusercontent.com/11801254/172748239-b554ac63-628b-41ae-b6b0-5c6fb1cc9e9b.mp4


it happened again.

Maybe it has to do with the resizing the canvas or image before

I am trying to isolate it

**Comment by photopea** [comment]
Maybe send me your PSD (where it happens) to support@photopea.com

**Comment by TheRadicalDreamer** [comment]
When i close and open the PSD again i cannot repro.

I will try to trigger it

**Comment by TheRadicalDreamer** [comment]
I'VE GOT IT

Enter this PSD: https://www.photopea.com/#ig7EWQVun

Move a Text (the ones of the top)

Then switch to Vector Mode, and you'll see it never moved.

You can switch back and forth to Raster Mode and get how it behaves.

**Comment by TheRadicalDreamer** [comment]
BTW, in vector mode Photopea is sttutering.

It is more hard to the hardware?

**Comment by photopea** [comment]
The bug should be fixed now.

Yes, the vector mode could require more computation. Show us how do you make it stutter, and I will see if I can optimize it.

**Comment by TheRadicalDreamer** [comment]
Now i cannot open a particular file in vector mode, please take a look:

https://user-images.githubusercontent.com/11801254/175784285-e3c0d4b5-ef11-4b6b-aa59-c0d951a6ce1c.mp4



PSD: https://we.tl/t-ss6BGMfxpj

**Comment by TheRadicalDreamer** [comment]
Here i am opening the other file:

https://user-images.githubusercontent.com/11801254/175784335-9747a030-0a96-4dbb-9f22-14fbb83dc94a.mp4

**Comment by photopea** [comment]
The vector mode does not support Pattern fills. It never did. It is not related to this issue. Make a separate report about it :)

**Comment by photopea** [comment]
I have implemented the pattern fills in the vector mode, they should look well now.

**Comment by TheRadicalDreamer** [comment]
Good! 

I will be working more on vector mode then
