### ISSUE TITLE
CMYK Mode - When exporting to pdf the colors of one part of the project revert to RGB

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4714]
![image](https://user-images.githubusercontent.com/11801254/172732914-9ed8403e-fbd9-4c73-8405-eecca6cb5907.png)

Here the PSD: https://www.photopea.com/#iplL2vivb

**Comment by TheRadicalDreamer** [comment]
Can you spot the difference on the right rainbow?

**Comment by TheRadicalDreamer** [comment]
I believe is becuase the rainbow is under a transparent layer

**Comment by TheRadicalDreamer** [comment]
I believe it is caused because the rainbow is under a transparent layer

**Comment by photopea** [comment]
Right now, Photopea turns vector shape colors to "CMYK colors", but smart object colors (e.g. an embedded JPG file as a smart object) are not changed to CMYK. I will fix it.

**Comment by TheRadicalDreamer** [comment]
Can you please 🥺 fix it soon?  Is a work i have to deliver 🙏

**Comment by photopea** [comment]
It is fixed now :)

**Comment by TheRadicalDreamer** [comment]
✧\(>o<)ﾉ✧
