### ISSUE TITLE
Copy and paste text, makes it smaller

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4716]
https://user-images.githubusercontent.com/11801254/172764539-fed4ff01-b1df-472c-9729-15015db3cae1.mp4

**Comment by photopea** [comment]
So you make a text layer with a text size 10px. If you free-transform it to make it 5x bigger, the Size value will show you 50 px. But if you copy-paste it into another layer, is still 10px . The Free Transform is not copied.

Another example. You make one text layer with text, and make two more copies. You will make the second copy 2x bigger, and the third copy 5x bigger. If you copy-paste text between layers, it will always have the size of the text around it, even though the text size is different in every layer.

**Comment by TheRadicalDreamer** [comment]
And that's how Photoshop works?

Because, in my humble opinion, maybe there should be a key combo, like: Ctrl+Shift+V to paste the text with the destination format.
