### ISSUE TITLE
Artboards - Duplicate (Ctrl+J) an artboard with guides, it will copy ALL guides of all artboards to the Global guides

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4717]
https://user-images.githubusercontent.com/11801254/172767733-68ca8402-d153-4f4d-ba23-d3ee8f31a003.mp4

**Comment by TheRadicalDreamer** [comment]
[guides.zip](https://github.com/photopea/photopea/files/8867016/guides.zip)


Here. try to duplicate and move.

Each duplicated artboard have a different behaviour

**Comment by TheRadicalDreamer** [comment]
I still get this bug.

Please fix it. If not artboard guides are kind of unusable

**Comment by TheRadicalDreamer** [comment]
Here is a video showing how to trigger it from scratch
https://user-images.githubusercontent.com/11801254/174680136-a7c7587d-f862-4d90-aa7a-26fd2a7d6cad.mp4

**Comment by TheRadicalDreamer** [comment]
This is horrible, i can barely work :(

Please correct this.

Also, can you please make global guides and artboard guides different color? Like fucsia or something?

**Comment by TheRadicalDreamer** [comment]
@MichalSZZ have you had this issue?

It is preventing me to work correctly with multiple page projects. 

Also after a couple of minutes photopea goes crazy and begins to sttuter

**Comment by photopea** [comment]
I am very sorry for this, it should be fixed now. Artboard guides have a different color now.

**Comment by TheRadicalDreamer** [comment]
Thanks!

Now i can go back to work.

Just asking, but there is a way to add global guides dragging from the ruler, but when you already have artboards?

Like holding alt/ctrl/shift and draggin the guide from the ruler?

**Comment by photopea** [comment]
The only way I know in Photoshop (and Photopea) is deselecting all layers. Use the Move tool and Ctrl+click (or Auto-select + click) into an empty space.
