### ISSUE TITLE
PSD does not keep the settings of DPI or Layer view 

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4718]
![image](https://user-images.githubusercontent.com/11801254/172895574-c2380749-5675-4932-83b7-903eee374f8b.png)
(i like thumbnails by layer for example)

![image](https://user-images.githubusercontent.com/11801254/172895582-ea448e36-8451-4c2b-b94c-f0e06b0491e8.png)
(i like pixels/cm for example)

Everytime i open a PSD file i have to reset this 2 settings to keep working like i like.

Shpuldn't be bonded to the PSD or the account?? Like rules unit of measure does?

**Comment by popbee** [comment]
I suspect PSD files only has a DPI value (Dot Per Inches).  The actual "units" I don't think is actually encoded in the file.

I suppose the feature request here would be to remember those things locally (like preferences). (?)

**Comment by TheRadicalDreamer** [comment]
Yes. Local preferences

**Comment by photopea** [comment]
Photopea will remember the Layers panel options now.

Do you think the Image Size / New Document units (of Width, Height) should correspond to the Ruler units? If you change from Pixels to Inches in the New Document, it should change the ruler units?

**Comment by TheRadicalDreamer** [comment]
Not necesarely.

I don't use that way, for me is always the same units of the documents as the ruler.

But, i kinda feel that in some occasions you can like to work in pixels on a mm document.
