### ISSUE TITLE
Show image only in full screen like "f" shortcut on photoshop

### ISSUE THREAD

**Issue by costorella** [photopea/photopea#4721]
Sorry for my bas english. I use photopea on IPad without physical keyboard and i dont find how to show my image quickly on fullscreen without tools and menu bar like "f" shorcut on photoshop. Its is very useful for me. I found hoW to bide tools but its not that i want. Thx

**Comment by photopea** [comment]
But if you were able to go fullscreen on an iPad, how would you exit that fullscreen mode? There is no keyboard on an ipad. Also, there are no buttons in this view mode.

**Comment by costorella** [comment]
> But if you were able to go fullscreen on an iPad, how would you exit that fullscreen mode? There is no keyboard on an ipad. Also, there are no buttons in this view mode.

It's true that I didn't think of that lol.  imagine a watermark icon?  I do not really know.  But I can tell you that apart from that photopea on ipad is much more practical than Photoshop and affinity photo.  If we could have some finger shortcuts that would be great

**Comment by photopea** [comment]
Did you try the fullscreen button at the top? Also, there is View - Screen Mode - Menu Bar and Canvas

**Comment by costorella** [comment]
> Did you try the fullscreen button at the top? Also, there is View - Screen Mode - Menu Bar and Canvas

yes on ipad this button is useless since thanks to an option on safari it automatically goes into application mode to work in full screen.

**Comment by photopea** [comment]
Photopea has already a Fullscreen option under View - Mode - Fullscreen. If it does not work, it means your web browser does not support it, try another browser (unless you are on an iPad, where all browsers are running on top of Safari).
