### ISSUE TITLE
Clicking and dragging on opacity arrows should adjust opacity

### ISSUE THREAD

**Issue by setiawanj** [photopea/photopea#4722]
A 'nice-to-have' that exists in Photoshop, that would be.. nice to have in Photopea.

This is in reference to the "Opacity" and "Fill" fields in the Layers panel. They have a down arrow to the right, that will reveal a slider upon clicking.

In Photoshop, if you click on the arrow and keep your mouse down, moving the mouse to the left will decrease opacity/fill opacity, and moving it to the right will increase opacity/fill opacity. Currently in Photopea, you can only click on the arrow - dragging thereafter does nothing.

Obviously not something important, but would be a nice touch that some people (me at least) would appreciate.

**Comment by photopea** [comment]
"In Photoshop, if you click on the arrow and keep your mouse down, moving the mouse to the left will decrease opacity/fill opacity, and moving it to the right will increase opacity/fill opacity." - I have never heard of such feature in Photoshop :( could you record a short video of how it works? Or some video on Youtube that shows it?

**Comment by photopea** [comment]
Oh, you mean dragging the mouse over the slider! You did not say that.

Do you know that you can also click the label "Opacity" and drag it to the left / right ? In Photoshop and in Photopea.

**Comment by photopea** [comment]
I think it would be too hard to make, just drag the label
