### ISSUE TITLE
Feature Request: LCH in color picker

### ISSUE THREAD

**Issue by popbee** [photopea/photopea#4724]
Color Picker dialog to support "LCH" values. (Lightness, Chroma, Hue an alternate representation of CIE L\*a\*b) 

I strongly believe in LCH color model (also spelled LCh to differentiate the hue from HSB/HSL which is not the same) to help pick colors for beautiful designs. This is the culmination of researches on color and the human eye and is becoming a CSS standard. Today well known algorithms can "map" a LCH color to sRGB (through  CIE Lab/XYZ domain).

For example, for a project of mine, I needed a series of well balanced colors for which a single text color appear with equal contrast on any hue value.
![image](https://user-images.githubusercontent.com/1083830/173197433-1aad8ff5-f638-43d5-b991-80a2aabe6128.png)

Some LCH values are obviously out of gamut for sRGB but it's often good enough to "map to the closest sRGB" within the color picker. Since this is a physical model, some of the LCH values are not really bounded (there is no theorical maximum to how much chroma you can have) but sensible values exists and you can probably follow what Lea Verou have done here:  https://css.land/lch/  Her blog post explaining some of the basic theory:  https://lea.verou.me/2020/04/lch-colors-in-css-what-why-and-how/  Mind you, she is co-editor of the "CSS Color 5" spec, so she seem to know what she is talking about.

![image](https://user-images.githubusercontent.com/1083830/173197631-92799680-b057-47be-897c-1ddb4a2bb115.png)

But wait, there's more:

**Like Photoshop, but better.**
As an additional bonus, maybe you can do like photoshop with a radio button in front of each value that modify the color gradients. Note that Photoshop has the L\*a\*b color option. LCH is a vastly superior option and truly "make sense" for designers.  L\*a\*b makes no "useful" sense other than the "L" component (which is almost the same thing as the L in LCH).

![image](https://user-images.githubusercontent.com/1083830/173198101-a36c9c3e-243b-4dd6-a223-8180914711ca.png)

Here's a *suggested* layout for PhotoPea (also added more swatches) and a sRGB Gamut option:

![image](https://user-images.githubusercontent.com/1083830/173203195-f8119a2f-93fd-4512-bc75-a56ec9723ba9.png)

my 2 cents
Bernard

**Comment by photopea** [comment]
Honestly, I think there are dozens of color representations, which are just as popular as LCH. We can not implement them all :(

Maybe @hxim could create a plugin for this?

**Comment by popbee** [comment]
> dozens of color representations
name ONE  that is actually useful

**Comment by popbee** [comment]
Wait, you support plugins now?   So I can do it myself?

**Comment by photopea** [comment]
Sure, here it is: https://www.photopea.com/api/plugins . Plugins are at Window - Plugins.
