### ISSUE TITLE
Exporting shapes as SVG doesn't maintain rotation

### ISSUE THREAD

**Issue by FatmaAkram** [photopea/photopea#4726]
I made an SVG with multiple rotated rectangles, but when I export, it gives a  different output with all shapes aligned vertically.

### Expected
<img width="799" alt="image" src="https://user-images.githubusercontent.com/43050730/173245281-c805c323-5f80-453f-8f69-33d64c178b14.png">

### Result
<img width="561" alt="image" src="https://user-images.githubusercontent.com/43050730/173245306-19e9cd79-657c-4abf-aaa7-06671bb07629.png">

Anything, in particular, I'm doing incorrectly?
Thanks

**Comment by photopea** [comment]
I am very sorry, it should be fixed now.
