### ISSUE TITLE
Shows adblock enabled but I made sure to disable adblock!

### ISSUE THREAD

**Issue by seattle713** [photopea/photopea#4729]
I'm having a problem where the annoying reminder  "Are you using an AdBlocker? Photopea would not exist if everyone did what you do. Please watch our ads." but there are literally ads showing on the sidebar.
![photopea bug](https://user-images.githubusercontent.com/82445086/173384657-42496d01-794e-4d91-acbe-c3e166e13ac5.png)

**Comment by seattle713** [comment]
In case someone tries to say I clearly don't have adblock disabled since the "Support Photopea!" ad is showing in the first picture, it still has the popup when it shows 3 ads.
![photopea bug 2](https://user-images.githubusercontent.com/82445086/173385042-063af8e7-0d9c-4b99-9199-e1799b50fea9.png)

**Comment by photopea** [comment]
Where are ads? the images on the right side are my own games, that I made in 2013. I tell people with ad block to play my games. I do not get any money if you play my games.

**Comment by photopea** [comment]
Please, disable our ad block and watch our ads. I know you might laugh at it, but it is true: if everyone blocks ads as you do, we would not exist :(

**Comment by Aodham** [comment]
I've come to report same problem. I use AdBlocker Ultimate on Firefox, but I have disabled it on Photopea.

**Comment by photopea** [comment]
I think your ad blockers are lying to you. As I understand:

- if you delete your ad blocker completely, Photopea shows ads
- if you turn on ad blocker, Photopea says "ad blocker detected"
- if you "disabled it on Photopea", Photopea says "ad blocker detected"

So clearly, your ad blocker is lying to you. It is obviously a bug in your ad blocker, it is still blocking ads in Photopea.
