### ISSUE TITLE
PDF import error

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#473]
I checked new PDF import and when opening some PDF files it shows this error:

ext.js:2028 Uncaught e
PDFI.getInt @ ext.js:2028
PDFI.readXrefTrail @ ext.js:2006
PDFI.readXrefTrail @ ext.js:2013
PDFI.Parse @ ext.js:1385
I.PDF._t @ pp.js:177
um.DN @ pp.js:5914
um.Df @ pp.js:5907
FileReader (async)
um.Dz @ pp.js:5885
uK.Xz @ pp.js:6089
zP.F @ pp.js:6
j.F @ pp.js:4297
j.F @ pp.js:4297
uj.DJ @ pp.js:5988

**Comment by photopea** [comment]
Hi, can you attach your PDF file here?

**Comment by hxim** [comment]
Yes here it is
[mapa1.pdf](https://github.com/photopea/photopea/files/1692710/mapa1.pdf)

**Comment by photopea** [comment]
It was fixed, thank you!

**Comment by hxim** [comment]
Hi I found different pdf file causing this error:
[070ae04e-127c-11e8-8e7d-000c29a578f8.pdf](https://github.com/photopea/photopea/files/1728658/070ae04e-127c-11e8-8e7d-000c29a578f8.pdf)


ext.js:1646 Uncaught e
PDFI.operator @ ext.js:1646
PSI.step @ ext.js:1048
PDFI.render @ ext.js:1484
PDFI.Parse @ ext.js:1410
Z.PDF.Fw @ pp.js:178
Nh.cn @ pp.js:5975
Nh.cv @ pp.js:5968
FileReader (async)
Nh.cb @ pp.js:5946
NK.Tb @ pp.js:6150
qU.A @ pp.js:6
FV.A @ pp.js:4353
FV.A @ pp.js:4353
Nk.TL @ pp.js:6049

**Comment by photopea** [comment]
It was fixed, too. Thank you :)
