### ISSUE TITLE
Open sourcing project

### ISSUE THREAD

**Issue by vkhobor** [photopea/photopea#4730]
Is there an chance you will open source this project?

There are many options to keep more control over your code and still open source it.

A few ideas:
- AGPL preventing usage of your software on servers
- Requiring CLA signing, so in the future you can still change your mind and close source any further development
- With CLA signing I think its even possible to keep all rights to you.

Some people might want to contribute via code, and that could be helpful

**Comment by photopea** [comment]
I think we would lose the ability to make money from our software, if we open-source it. 

Usually open-source projects contain only 10% of original code. But in our case, it is 100%.

**Comment by vkhobor** [comment]
I should not suggest open-sourcing it. 

You can 100% own the code, and open-source, with a contributor license aggreement.(CLA) Microsoft does that with VSCode.
- This would prevent forking I think.

Then technically, only tech savy people could build it for themselves(which many do not do), others would have to use it in cloud.
