### ISSUE TITLE
Press Enter to submit name layer

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4731]
![image](https://user-images.githubusercontent.com/11801254/173703768-d5eeb1e4-d5d7-431b-b4fa-e6bbb73760df.png)

Can we press Enter to hit OK?

**Comment by TheRadicalDreamer** [comment]
Can this be implemented?

**Comment by photopea** [comment]
Fixed! You need to press Enter or Escape to finish the text input, and then, Enter or Escape to close the window.
