### ISSUE TITLE
Text box shows some text out of the box

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4732]
https://user-images.githubusercontent.com/11801254/173705823-7fcbd53b-625b-450f-9fdc-a176f58909c9.mp4

**Comment by photopea** [comment]
could you share a PSD?

**Comment by TheRadicalDreamer** [comment]
Here: https://www.photopea.com/#i__FnATbJ

**Comment by TheRadicalDreamer** [comment]
Still happens :)

**Comment by photopea** [comment]
fixed :) click into text layers to re-render them.
