### ISSUE TITLE
Generate JPGs with a depth map

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#4735]
It would be nice to let people combine a RGB layer and a grayscale layer into a file, which contains both color data and a depth map.

It could be a part of the 3D Depth Viewer plugin.

**Comment by MichalSZZ** [comment]
Hi. What a great news! 
Did you get my mail that I sent to you week ago? Is that issue related with my links? I think that Adobe in their 'Neural Filters' use the same techniques as in demos linked in my email. And its 'Depth Blur' works like build-in 'Depth Prediction AI' but without generated  depth map (that is useless for most people). Just the tool that is a combination of generated grayscale depth map, subject selection (was in my links too) and 'lens blur filter'. Look https://www.youtube.com/watch?v=5Cp0tZjuHws

**Comment by photopea** [comment]
All these AI solutions require a "model", which is usually 30 - 300 MB in size. Once you have a model, a photo can be processed in 1 - 2 seconds, or a minute at most.

I wrote to the Hugging Face on Twitter. Maybe we could come up with a way of cooperation.

**Comment by photopea** [comment]
The original user wanted it on Reddit or Twitter. I dont know who it was or if he still needs it, so I will close it now.
