### ISSUE TITLE
Variable Fonts support and other quirky text stuff

### ISSUE THREAD

**Issue by rice7th** [photopea/photopea#4736]
It would be awesome to be able to use variable fonts in Photopea, and on top of that add also cool text control like Figma does:
![Screenshot 2022-06-17 at 01 52 50](https://user-images.githubusercontent.com/93940240/174196439-40b25693-d182-47d4-b93c-ec923452a42f.png)

Thanks in advance

**Comment by photopea** [comment]
Lets discuss it at a newer issue: https://github.com/photopea/photopea/issues/5601

**Comment by photopea** [comment]
We do support variable fonts now: https://x.com/photopeacom/status/1871266773221212165
