### ISSUE TITLE
Shape broken after Flip Horizontally and SVG export

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#4737]
1.) I created arrow in circle (fa-arrow-circle-right) with Custom Shape tool (32x32 on 38x38 canvas).
2.) I flipped it with Edit-Tranform-Flip Horizontally
3.) I exported as SVG.
4.) Shape in SVG is broken - only shows black circle.

[leftarrow.zip](https://github.com/photopea/photopea/files/8926069/leftarrow.zip)
contains: leftarrow.psd - PSD which exports to black circle, leftarrow.svg - Exported SVG

Note: When I rotated it 180 degrees it exported correctly.

**Comment by photopea** [comment]
it should be fixed now.
