### ISSUE TITLE
THE "LAYER STYLE" ICON

### ISSUE THREAD

**Issue by PapiFlak** [photopea/photopea#4738]
WHEN TRYING TO CLOSE THE "LAYER STYLE" ICON, IT DOESN'T RESPOND TO ME. IT HAS BEEN HAPPENING TO ME VERY CONTINUOUSLY IN THIS LAST WEEK, I WOULD LIKE TO REQUEST SUPPORT TO BE ABLE TO ERADICATE THIS PROBLEM...

**Comment by photopea** [comment]
I am not able to see such problem. Could you describe steps, what should I do after opening www.Photopea.com, to always see such problem?

**Comment by PapiFlak** [comment]
yes, sometimes when I enter the "gradient" icon in the letters, it
constantly won't let me close the gradients icon when I'm done degrading my
letters, it just stays static

**Comment by photopea** [comment]
What is the gradient icon? I don't understand.

Could you tell us, what should we do to see the problem that you describe? Or could you record a video of the problem?

**Comment by photopea** [comment]
I have to close it because of lack of details.
