### ISSUE TITLE
Small viewport bug on Ubuntu

### ISSUE THREAD

**Issue by WhiteLeash** [photopea/photopea#474]
Hello - only one small problem on Ubuntu with viewport and "layers column" - it have small gap on right where could be utilized for much wider viewport.

My spec:
- 1680x1050 monitor
- Ubuntu 16.04 lts
- Mozilla Quantum 58.0.1 64 bits

![](https://i.imgur.com/7cALgQ1.png)

**Comment by photopea** [comment]
There should be advertisment, and you are hiding it somehow. What a naughty boy!

![](https://i.imgur.com/FDghO4X.png)

**Comment by WhiteLeash** [comment]
Ahh :/ ok! I will off on photopea then ^.^
