### ISSUE TITLE
Shape heart is smushed when opened

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4740]
This pdf:
[Norte - Corazón A - Chakana.pdf](https://github.com/photopea/photopea/files/8936402/Norte.-.Corazon.A.-.Chakana.pdf)

When you look at it, looks like:
![image](https://user-images.githubusercontent.com/11801254/174500332-590457ce-ff8b-494f-9fdc-88b0bf8a0f26.png)

But when you open it, looks like this:
![image](https://user-images.githubusercontent.com/11801254/174500351-7dd50a4b-7ba0-47f3-8567-7e9dc735edfd.png)

**Comment by photopea** [comment]
fixed, thanks! :)
