### ISSUE TITLE
Ok Knop bij kleurkiezer

### ISSUE THREAD

**Issue by Vinnie2Fast4U** [photopea/photopea#4744]
beste,

Bij het editen van een text wou ik men kleur aanpassen, toen ik dat gedaan heb wilde ik op OK drukken maar dat werkte niet, dus probeerde ik het nog is en het werkt tot het tijdstip nu nog steeds niet. Kan u mij Verder helpen?

Vince VK
Vince.van.kerckhoven@outlook.com

**Comment by photopea** [comment]
Hi, could you write it in English?

**Comment by Vinnie2Fast4U** [comment]
Hello!

i was editing my F1 design and i was changing the colors of the text and when i did that i wanted to click on the OK button but it didnt work and now i am for 2 hours stuck in thats screen, i just can't klick on the OK button
i will send you a picture down below!

cheers
![Schermopname (37)](https://user-images.githubusercontent.com/107872239/174639802-78e87e9c-d432-4cdd-86dc-8b36cb4209a9.png)

**Comment by photopea** [comment]
Please, describe, what should we do in Photopea to run into such problem ourselves.
