### ISSUE TITLE
Suggestion - Last 3 fonts used

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4747]
I know we have stars to set favorite fonts.

But il will be great to have the last 3 fonts selected ont he top of the search bar, like other plastforms do.

![image](https://user-images.githubusercontent.com/11801254/174672711-9ba50799-a8e7-44cc-8c89-562cebbc23bc.png)

:)

**Comment by photopea** [comment]
I have implemented it! It shows last 9 fonts, except of the current font.

**Comment by TheRadicalDreamer** [comment]
good rework !
