### ISSUE TITLE
Cannot replace file variable

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4748]
![image](https://user-images.githubusercontent.com/11801254/174676512-abcd259d-08dd-4541-9811-16e1bd05c8fc.png)

When working on variables, after i export. The file tabla goes back to the demo.

If i upload it again it is not replaced. And the export don't have the new file, so i have to close the file and open it again  :(

Everytime i upload a new file it should replace the last

**Comment by TheRadicalDreamer** [comment]
If i try to upload the same file it behaves like i told you.

**Comment by MichalSZZ** [comment]
I had that problem too some time ago.

**Comment by photopea** [comment]
Fixed! You can load the same file (same file name) multiple times :)

**Comment by TheRadicalDreamer** [comment]
Thanks!
