### ISSUE TITLE
Change the * of the modified not saved project

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4749]
Some of my files have long names, and because of that i cannot see when they have the * at the end.
![image](https://user-images.githubusercontent.com/11801254/174678830-6e467386-808d-467e-bf39-d37099154a8c.png)

And sometimes i have closed without saving.

So i was wondering if you can set the * BEFORE the project's name.

Or a more elegant solution is to change the background color of the tab and add that colored line on the left, just like selected tools have
![image](https://user-images.githubusercontent.com/11801254/174678886-32a60f85-4f72-4816-bbb6-e53f18556b0d.png)

**Comment by photopea** [comment]
It should be fixed now, the asterisk should always be visible.
