### ISSUE TITLE
Text Gaussian Blur and suddenly skewed

### ISSUE THREAD

**Issue by enzyme69** [photopea/photopea#475]
I have a Text in a layer. I duplicate the Text Layer, rasterize and apply smooth gaussian blur... suddenly text become skewed without reason. Maybe a bug.

**Comment by photopea** [comment]
Hi, it never happened to me. Can you send me your PSD before applying the gaussian blur?  My mail is support@photopea.com

**Comment by photopea** [comment]
I am going to assume it is solved now.
