### ISSUE TITLE
Cannot log to account

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4750]
If i don't have an account i can enter to google?

So i can load my fonts in the future?

![image](https://user-images.githubusercontent.com/11801254/174686460-47685c03-848b-41b2-8879-f618387356a9.png)

**Comment by TheRadicalDreamer** [comment]
I am trying to log into a free account for a friend. But is displayed this after connected to google account

**Comment by photopea** [comment]
It is a bug in Google Chrome. Logging in works only if Photopea is not "installed" to your device. Go to about://apps and uninstall it.

**Comment by photopea** [comment]
I can not reproduce it however :( so if you could describe how to reproduce it (start with Photopea uninstalled), it would be great!
