### ISSUE TITLE
Export SVG - circles gets a triangle

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4751]
https://www.photopea.com/#id4ckqSc6
Esport this to svg, and open it:

![image](https://user-images.githubusercontent.com/11801254/174709948-4529baf8-e693-4a81-aac9-a4990f3bde31.png)

**Comment by TheRadicalDreamer** [comment]
This other file:
https://www.photopea.com/#iZ4Nyu8TO

Export it to SVG and the poitn will be ascending and not in line

**Comment by photopea** [comment]
It is fixed now.

BTW. you have hundreds of one-point shapes in your PSD files. How did you make them?

**Comment by TheRadicalDreamer** [comment]
I made accidentally with vectorize image.
Some random pixels converted into shapes... I believe
