### ISSUE TITLE
Restrict me to open pdf files on google chrome

### ISSUE THREAD

**Issue by sefinehtesfa34** [photopea/photopea#4752]
I am so tired to open pdf files on google chrome. This came after I install Photopea.

**Comment by photopea** [comment]
Could you tell your computer to open your PDF files in some other program? Maybe look into a manual for your operating system. Or uninstall Photopea (there is no need to install it, as you can always use it at www.Photopea.com)

**Comment by sefinehtesfa34** [comment]
I am using Ubuntu 20.04.  When I search the app name in my system, I can
see. But when I tried to uninstall photopea, I couldn't uninstall photopea.

**Comment by photopea** [comment]
If you installed Photopea with More - Install Photopea, you must go to your browser, to about://apps, and uninstall it there.

**Comment by photopea** [comment]
I have to close it because of lack of details.
