### ISSUE TITLE
Open SVG - text gets smushed

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4753]
Save this SVG
![Step inside_ 2cm](https://user-images.githubusercontent.com/11801254/174895817-fd0bc385-66ac-448a-b310-d65915b1487a.svg)

Open it in Photopea. Should look like this;
![image](https://user-images.githubusercontent.com/11801254/174895851-7a8045c1-f908-417d-9a1f-542cb68d3076.png)

But it looks like this:
![image](https://user-images.githubusercontent.com/11801254/174895910-772eea98-47ae-4513-a740-40a02b590670.png)

**Comment by photopea** [comment]
fixed! :)
