### ISSUE TITLE
PDF Export - Stroke does not export

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4754]
Open this PSD:
https://we.tl/t-ss6BGMfxpj (it is heavy)

Enable the layers top and bottom
![image](https://user-images.githubusercontent.com/11801254/174898398-98c5b1c8-ec39-4acd-ae82-7a732da92ff8.png)

Export to PDF.

You'll get it without strokes
![image](https://user-images.githubusercontent.com/11801254/174898458-e96a262f-26af-430f-a836-67f798422c23.png)

**Comment by TheRadicalDreamer** [comment]
Here is a lighter version
[Top.zip](https://github.com/photopea/photopea/files/8953385/Top.zip)

**Comment by TheRadicalDreamer** [comment]
This is a major issue for me.

Please consider fixing it soon :(

**Comment by TheRadicalDreamer** [comment]
@photopea 

Have you checked this?

**Comment by TheRadicalDreamer** [comment]
Seems fixed now

**Comment by photopea** [comment]
Photopea does not support any pattern fills. If you use them, use "rasterize all".

**Comment by TheRadicalDreamer** [comment]
Wait.

But this is a intended behaviour??
![image](https://user-images.githubusercontent.com/11801254/175665301-04553717-eca1-4bbb-a1c4-de95567cc349.png)

**Comment by TheRadicalDreamer** [comment]
But my projects did export correctly before.

This is before (may):
![image](https://user-images.githubusercontent.com/11801254/175665593-3d426d71-0d28-496d-ad5a-fb92abeec08d.png)

This is after (jun):
![image](https://user-images.githubusercontent.com/11801254/175665690-0514be6a-9fda-4923-899f-046f3724756d.png)

**Comment by TheRadicalDreamer** [comment]
It have always had this stokes with pattern
![image](https://user-images.githubusercontent.com/11801254/175665882-88e62b3e-e58c-4bb9-a213-8c0fb3048704.png)

**Comment by TheRadicalDreamer** [comment]
I know that when exporting patterns in PDF they get raster, even if i don't set rasterize all, that's ok.

But it is not ok that i can see the stoke pattern and i cannot export it.

**Comment by photopea** [comment]
sorry, it is fixed now!

**Comment by TheRadicalDreamer** [comment]
THANK YOUUUUUUUUUUUUUU!!!
