### ISSUE TITLE
I cannot save PSD file

### ISSUE THREAD

**Issue by MouseCradrecal** [photopea/photopea#4755]
I've tried saving a psd file but it just shows saving and it is taking very long and still not saved.

**Comment by photopea** [comment]
Did you try it multiple times for different files, and it never worked?

**Comment by simdi123** [comment]
Its not allowing me to save or export my work I've already lost 5 hours of work because of this. What do I do

**Comment by photopea** [comment]
I have to close it because of lack of details.
