### ISSUE TITLE
psd files won't open

### ISSUE THREAD

**Issue by domettrw** [photopea/photopea#4756]
I can't even open my psd files, it keeps saying unknown file and a lot of zeros

**Comment by photopea** [comment]
Are you files 0 Bytes in size?

Sometimes, when you save a PSD in Photopea, and you close Photopea while it is still saving, you get damaged PSD files (0 Bytes).

**Comment by domettrw** [comment]
no they're not

**Comment by domettrw** [comment]
I mean I'm trying to open eavery single type of psd files but it doesn't open, when I try a normal picture it opens normally. I need to edit these psd files asap

**Comment by photopea** [comment]
I have to close it because of lack of details.
