### ISSUE TITLE
photopea not loading properly

### ISSUE THREAD

**Issue by Godkr** [photopea/photopea#4759]
![Screenshot_2](https://user-images.githubusercontent.com/90626616/175274422-30c032bf-f3bc-45c9-9e60-3854082df5be.png)
**I bought a new monitor and this happened**

**Comment by photopea** [comment]
What web browser are you using? DId you try the Incognito mode, as described here? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
