### ISSUE TITLE
what is this "raster quantization"?

### ISSUE THREAD

**Issue by enzyme69** [photopea/photopea#476]
You mentioned about PNG export and "raster quantization" option, but I am not seeing it.

When exporting as PNG, there is this "use color palette" option, just wondering what it does?

Thanks!

**Comment by photopea** [comment]
Hi, what do you mean by "I mentioned"? When exporting PNG, you can set the Quality (smaller Quality will produce smaller files).

TLDR: "don't use palettes" makes the resulting PNGs a bit larger, that is all it does.

Full answer: There can be PNG with palettes or PNG without palettes (without palettes are slightly larger). A PNG viewer must be able to open both kinds of PNG. There is a bug in Acrobat Pro software - it can not load PNG with palettes. Some lady complained about it, so I added this option just for her. When Adobe fixes it, I will remove this option.

**Comment by photopea** [comment]
I am going to assume it is solved now.
