### ISSUE TITLE
Ad blocking message state may be incorectly saved.

### ISSUE THREAD

**Issue by S-INFINITY** [photopea/photopea#4760]
I love using an adblocker but I do turn it off for sites that deserve it. I'm a little concerned however as even after disabling my adblocker, it says "Ad blocking detected". I'd like a little check to be done if possible if there is a bug causing the state of the blocker detection to not refresh on reload.

Steps to reproduce:
- Launch Photopea using Adblock. (I'm using Version 4.46.20)
- Disable Ad blocking for Photopea using the extension quick settings -> Be sure to click always instead of just once
- Refresh the webapp and check if the "Ad blocking detected" in the top right has changed.

It could just be a visual bug, but I think it's more because using Photopea on incognito launches completely different ads.

Here is what it looks like for me along with all the extensions I have installed. Perhaps it's being caused by another extension.
![image](https://user-images.githubusercontent.com/63537458/175302427-0ae58bb8-ecb5-4ccb-9475-768ce7019668.png)
![image](https://user-images.githubusercontent.com/63537458/175302533-c18900fb-95a2-4378-877e-13c28ff1d87a.png)

Apologies for any grammatical mistakes, I'm dyslexic.

**Comment by photopea** [comment]
I think it is a bug in your ad blocker. It tells you that it is disabled, but it is still blocking ads in Photopea.

Did you try to disable your ad blocker completely (temporarily)?

**Comment by S-INFINITY** [comment]
Hey, turns out you're correct. It seems to be a bug in the adblocker rather than Photopea. Thanks.
