### ISSUE TITLE
direct selection doesnt work 

### ISSUE THREAD

**Issue by stuntbounce** [photopea/photopea#4763]
direct selection doesnt work , i cant move objects with it at all. Pls get this fixed im trying to make a shirt!

**Comment by photopea** [comment]
It seems to work fine for me. Are you sure you know what is the direct selection for? What should I do to see it not work?

**Comment by stuntbounce** [comment]
It doesnt move any object for me and yes I selected the layer i wanna adjust things in. Really weird. But apparently not everybody got that problem. Really annoying this

**Comment by photopea** [comment]
The Direct Selection tool is for making vector graphics. You can learn it here and in articles below it: https://www.photopea.com/learn/vector-graphics

Use the Move tool to move layers.
