### ISSUE TITLE
Translation in UI

### ISSUE THREAD

**Issue by nicolaslevet** [photopea/photopea#4765]
HI,

how is it possible to correct translation mistakes in the French UI, also to suggest yet untranslated items in the Photopea UI?

**Comment by nicolaslevet** [comment]
Thanks for your answer!

I translated what was possible to translate, it appears that some of the texts are not accessible (for example, the ones in the preference pannel). I also made minor changes (caps and Accented caps, among others). The major thing I have change is the ambiguous term "feather" and "pen". in French, the **pen** tool must be translated by "plume" but "feather" in a photo retouching context must be replaced with "contour progressif".
If I spot other mistakes I con't correct, I'll let you know.

**Comment by photopea** [comment]
Thanks a lot! I have updated the translations in Photopea.com :)

**Comment by nicolaslevet** [comment]
Hello,

thanks for the changes.

I spotted many many other untranslated or badly translated lines in the French UI, and none of them seem to be accessible through your « Create translation » page. As I’m not a code guy what would be the best solution for me to inform you what as to be corrected? Text file ? Screen capture? Any other way ?

Thanks for your answer

Nico

**Comment by photopea** [comment]
Every french phrase comes from phrases at www.Photopea.com/translate . Often, Photopea makes a combination of two or more phrases from there, to create a new phrase (which might produce an incorrect phrase). You can tell us about it here.

**Comment by nicolaslevet** [comment]
Hello,
Thanks for your answer, there are so many remaining English terms that don't come up in the translate page find field, very strange. 
A few examples, among dozens others
-Account type (in the account WIndow)-Make frames (in Layer Menu -> Animation)-Screen mode (in View Menu)-Sampled colors (in Color Range Window)
I have tried to search these terms separately, but with no result, hmm, I'm a bit puzzled...

I also noticed that in many places, Radius and Angle have both been translated by "angle", when it'a about degrees in French it's OK with "angle" but Radius should have definitely been translated by "Diamètre"
   
thanks for your guidance
Nico

**Comment by nicolaslevet** [comment]
Thanks, now I understand, I’d spotted around 180 texts that are frozen in English (I compared with other languages)

by the way I made a global change I changed the word « raster "and "rasterize» by  "de pixels » and « pixeliser »
