### ISSUE TITLE
Brush Is Not Working

### ISSUE THREAD

**Issue by Rebelf9** [photopea/photopea#4766]
The Brushes On my Photopea is not Working, for some reason the brush tool will not change color no matter what color I pick, and it's acting that way for the tools that involve stroking, even the eraser How do I fix this?

**Comment by Rebelf9** [comment]
all the tools involving colors, won't change and keeps living with some sort of red color..

**Comment by MichalSZZ** [comment]
Use Q on your keyboard. I think you are in Quick Mask mode.

**Comment by photopea** [comment]
I think you are in the Quick Mask mode, see here: https://www.photopea.com/learn/selections
