### ISSUE TITLE
Can't open a 13MB Sketch File

### ISSUE THREAD

**Issue by ethanbeyer** [photopea/photopea#477]
Before upload, I turned off WebGL. I try to open a Sketch file (12.7 MB) and I just see the "Loading" banner. I've waiting up to 12 minutes to see if it will open, and it just remains blank.

**Comment by photopea** [comment]
Hi, can you please send us your Sketch file to support@photopea.com ?

**Comment by ethanbeyer** [comment]
Sent. Thanks!

**Comment by photopea** [comment]
Fixed!
