### ISSUE TITLE
Please make these phrases translatable

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4770]
I picked some that are seen very frequently.
1. DPI
2. Automate
3. Raster
4. Vector (Beta)
5. Variables
6. Scale Effects
7. Current Path
8. Defringe
9. Pattern Preview
10. Screen Mode
11. All Documents

**Comment by photopea** [comment]
I made almost all of these phrases translatable. Others are planned to be removed from Photopea.
