### ISSUE TITLE
Why alert if we have nothing on clipboard when open New Project dialog?

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4771]
![image](https://user-images.githubusercontent.com/79258245/175770809-3fde3bc3-0eb0-4cf1-bb60-5ab478c4fb9d.png)
So far, I think it is not helpful but annoying.

**Comment by photopea** [comment]
This is needed to make the initial size of a document (width and height) correspond to the size of an image in your clipboard (if you have any). Do you think we should remove this feature?

**Comment by photopea** [comment]
ok, it should not be displayed now.
