### ISSUE TITLE
Adblock documentation improvement

### ISSUE THREAD

**Issue by osama-h-rana** [photopea/photopea#4772]
There's a few improvements that can be made to the [adblock documentation](https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/):

- The link to the problematic Adblock is broken as there's a `"` at the end of the URL.
- I'd also suggest improving the grammar in a particular paragraph, here's my suggestion:
This extension is known for blocking ads: [I don't care about cookies](https://chrome.google.com/webstore/detail/i-dont-care-about-cookies/fihnjjcciajhdojfnbdddfaoknhalnja?hl=en). What extension was blocking ads in your case? Let us know in comments below! The [AdBlock extension](https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom) is known for being active even if you disable it for a specific website. On the other hand, AdBlock Plus or uBlock Origin can be fully disabled for a specific website.
- I'm not sure what the "comments" are, maybe replace that with reddit?

**Comment by photopea** [comment]
thanks, I have fixed it! :)

**Comment by osama-h-rana** [comment]
You missed "know". Should be "known".

Happy to help :)

**Comment by photopea** [comment]
fixed, thanks! :)
