### ISSUE TITLE
Photopea lags when i use the move tool/crop tool

### ISSUE THREAD

**Issue by Utrasel** [photopea/photopea#4773]
When i use the move and crop tools, photopea lags for some reason, could you fix it?

**Comment by photopea** [comment]
Could you describe how should I make Photopea lag?

**Comment by Utrasel** [comment]
> Could you describe how should I make Photopea lag?

Just use the move/crop tool, you don't even do anything, it just lags a bit

**Comment by Utrasel** [comment]
All other tools have no lag

**Comment by Utrasel** [comment]
Tried deleting cookies but didn't work

**Comment by photopea** [comment]
It is perfectly smooth when I try it. What is the Width and the Height of your image? Press Image - Image Size to see it.

Also, is WebGL on? Check in More - Use WebGL.

**Comment by Utrasel** [comment]
> It is perfectly smooth when I try it. What is the Width and the Height of your image? Press Image - Image Size to see it.
> 
> Also, is WebGL on? Check in More - Use WebGL.

Yes, tried it with a smaller image and still lags
webgl is on

**Comment by photopea** [comment]
Could you try these steps, before we go further: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/ Maybe you are using a browser extension which slows down websites, or something.

**Comment by photopea** [comment]
I have to close it because of lack of details.
