### ISSUE TITLE
Feature request: Press F2 to rename selected layer

### ISSUE THREAD

**Issue by MattKleinsmith** [photopea/photopea#4774]
F2 is used to rename files and other entities on Windows, Ubuntu, Blender, and other software.

This feature would create a smoother experience for people who have F2 muscle memory.

Dream: I hope one day all software converges to a common set of default hotkeys, with the option to change them, like video games.

**Comment by xan2622** [comment]
I second this suggestion.

**Comment by photopea** [comment]
It would be very hard to implement it into our system :/ 

I have never heard of this shortcut. Also, F2 may work differently in image editors, and it is hard to tell if renaming a layer is what users expect.
