### ISSUE TITLE
Text tool seems to be entirely broken. 

### ISSUE THREAD

**Issue by NaokiS28** [photopea/photopea#4776]
The text tool doesn't seem to be rendering at all. Using default fonts and black colour and no matter the size or colour, it will not render. Text is also not selectable once you deselect it.

**Comment by xan2622** [comment]
It works fine here (I have just tested a minute ago). 
Firefox 101.0.1 (64 bits) on Windows 10.

**Comment by NaokiS28** [comment]
I'm on Safari Version 15.5 (17613.2.7.1.8) and it was working prior but seems there's a new update which might be incompatible?

![Screenshot 2022-06-26 at 9 00 58 PM](https://user-images.githubusercontent.com/83862255/175831846-35640445-72af-46da-bd4c-58299aee4bf3.png)

**Comment by photopea** [comment]
I just tried Safari 15.0 on my Macbook, and Safari 15.5 on my iPad, both work well.

Do you have any browser extensions? Did you try to turn Safari off and on?

**Comment by NaokiS28** [comment]
I will try again tomorrow. It is probably me then

**Comment by photopea** [comment]
I updated my Safari to 15.5 on my Macbook, and the text also works :(

**Comment by NaokiS28** [comment]
This can be closed as a non-issue, seemed to have been some cache related issue
