### ISSUE TITLE
Export PDF - Vector mask support

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4777]
Does PDF support vector mask??
![image](https://user-images.githubusercontent.com/11801254/176038812-30838d09-7c8a-4827-a2e7-65ca4ab04045.png)

**Comment by photopea** [comment]
vector masks should be supported in the PDF export now :)

**Comment by TheRadicalDreamer** [comment]
Still i have the issue:

Here is the PSD:
[J - Lanzador.zip](https://github.com/photopea/photopea/files/9035132/J.-.Lanzador.zip)

And why i can't see the dots of the head (in the project and in the export?)

**Comment by TheRadicalDreamer** [comment]
[K - Toki.pdf](https://github.com/photopea/photopea/files/9035135/K.-.Toki.pdf)

**Comment by photopea** [comment]
I think the dots on the head are a vector pattern, which are not supported in PSD.
