### ISSUE TITLE
Color Balance in CMY?

### ISSUE THREAD

**Issue by nicolaslevet** [photopea/photopea#4779]
Hello,

Color balance Pannel should have CMY settings (in addition of RGB), RGB is not very convenient, and most Photoshop users use this pannel with default CMY.

Thanks a lot if you can help on this one.

**Comment by photopea** [comment]
Ok, I have changed the labels on the three sliders (CMY added).

**Comment by nicolaslevet** [comment]
That's very kind of you, very helpfull, thank you!
