### ISSUE TITLE
Dynamic Symbols 

### ISSUE THREAD

**Issue by cpllan** [photopea/photopea#478]
Hey, I just discovered a new issue when converting Sketch to PSD. A huge part of Sketch is the ability to create dynamic symbols and then overwrite them with inputs, the overwrite can be text, can be an image or another symbol. This is what makes Sketch vastly better than Photoshop for Web/UI design.

The problem is when converting to PSD in Photopea the overwrite won't work, It will revert back to the original state. 

This might be difficult to include in Photopea but wanted to bring it to your attention.

Attached please find a simple file with a Symbol, the original symbol on the left says AB, the one on the right is the same symbol but with the text overwrite to say CD, in Photopea both says AB meaning that Photopea is not listening to the overwrites. 

Again thanks again for all the hard work,
Alex ✌️

![group](https://user-images.githubusercontent.com/12215167/36270057-aad576ec-122f-11e8-9529-4e872d1f90cc.png)
[Test.zip](https://github.com/photopea/photopea/files/1728627/Test.zip)

**Comment by blakesisu** [comment]
I'm experiencing a similar issue in general, where when opening a sketch file, sketch symbols aren't functioning as they 'should' (should being contextual within sketch itself).

**Comment by cpllan** [comment]
My workaround, until this gets fixed, is that I duplicate the artboard and the 'detach from symbol' every single symbol element then Photopea.

**Comment by photopea** [comment]
@cpllan  Hi, we just implemented overriding text content by symbol instances (you will see "CD" on the right, after you open your file in PP). Can you please show us more small examples, where other parameters are overridden?

It is not possible to preserve Symbols from Sketch into PSD. There are Smart Objects in PSD, but they work a lot differently (e.g. in Sketch, the artboard can contain symbols A and B, and also A can be placed inside B. In PSD, each Smart Object represents a separate file, and Smart Objects can not be shared between files - the A in the main document can not be "linked" to the A inside B). So we decided to "clone" the whole symbol for each instance.

**Comment by cpllan** [comment]
[Iphone.zip](https://github.com/photopea/photopea/files/1866706/Iphone.zip)

Yes I kinda knew that keeping the symbol functionality from Sketch would not be possible because photoshop wasn't designed that way, that what I think makes Sketch great.

With Sketch you can nest symbols within a symbol and make anything dynamic. So attached an example of how someone would use this. (this is only two levels of symbols but this can be unlimited). 

Let me know if you need further explanation of how this works

**Comment by photopea** [comment]
Amazing! Thanks a lot!  I just fixed it and your Sketch file looks in Photopea exactly the same as in Sketch. Let me know if you find any other errors.

BTW. Sketch files contain a special page, which contains all symbol masters. We preserve this page into a PSD (for your file, it is the folder "Symbols" on top of "iPhone X" artboard). Is it ok, or should we rather omit this page with symbols completely?

**Comment by cpllan** [comment]
I think omitting the symbols will be the path I would take, since symbols wont work on PSD.

Thanks for your work

**Comment by photopea** [comment]
This special folder with symbol masters is more like a "gallery" of symbols. They don't have any "symbol properties" in the PSD.

**Comment by cpllan** [comment]
Wow works perfectly, love it!

**Comment by cpllan** [comment]
Exactly, I normally delete that layer since there's no need in Photoshop.
