### ISSUE TITLE
[feature] quick export of visible layers

### ISSUE THREAD

**Issue by uselessgames** [photopea/photopea#4780]
feature request:
a button to quickly export as png all visible layers.

the current export button is for selected layers, which is often not useful when using folders, non visible layers, etc. 

thank you for an amazing tool! use it daily and even disable ad blocker to support you. cheers.

**Comment by photopea** [comment]
What does it even mean?

"export all visible layers" - do you want all layers as one file, or each layer in a separate file (mutliple layers) ?

**Comment by uselessgames** [comment]
> a button to quickly export as png all visible layers.

takes all visible layers, flattens and export to png. 
currently you have a 'export selected layer as png, or svg' it is a similar function but for all visible layers versus selected.

**Comment by MichalSZZ** [comment]
Isn't it a "File->Export as->PNG" feature?

**Comment by uselessgames** [comment]
> Isn't it a "File->Export as->PNG" feature?

that is the current way which is 4 clicks (file, export as, png, quality) and would be fine for one or two images. but often times i have to export 20+ images from different layer configurations.

**Comment by photopea** [comment]
There are thousands of features in Photopea. We can not make them all one-click features.

Use File - Export As - PNG, or Alt+Ctrl+Shift+S.
