### ISSUE TITLE
Export as SVG file > Include Color Overlays & Effects like Photoshop

### ISSUE THREAD

**Issue by JasperCyan** [photopea/photopea#4782]
Helllo, 
It would be great if the File > Export as > SVG would support color overlays.

You can see in the attached files that the image has a white color overlay to chnage the color from black to white, but Photopea when exporting does not support the color overlay. (perhaps the other effects also)

Download raw PSD file > https://gofile.io/d/MOuq9r
![Martial Art Club-Photopea](https://user-images.githubusercontent.com/64249844/176288857-99f9003c-f34d-4e9d-8a55-03b07227fd30.svg)
 
![Martial Art Club-Photoshop](https://user-images.githubusercontent.com/64249844/176288845-2c9f1750-b63e-4e26-83ec-d1f525c722b0.svg)

**Comment by photopea** [comment]
I am afraid I do not understand :( How exactly do you convert this PSD file to an SVG in Adobe Photoshop?

**Comment by JasperCyan** [comment]
> I am afraid I do not understand :( How exactly do you convert this PSD file to an SVG in Adobe Photoshop?

Through the File > Export as > SVG
https://www.bwillcreative.com/how-to-save-svg-files-in-photoshop/

**Comment by photopea** [comment]
Ok, it should be fixed now.
