### ISSUE TITLE
Cannot use PayPal for payment

### ISSUE THREAD

**Issue by smhk** [photopea/photopea#4783]
The site will instantly triple revenue if PayPal is added as a payment method; that's the standard industry figure for software products. Pls add PayPal so I can pay.

**Comment by smhk** [comment]
hi @photopea  !  sorry for the delay in answering

**Yes,** I would pay 10% more to use paypal.  This is completely normal.  Folks want the convenience.

I've processed 100s of millions for major corporations and millions for my own products.

One interesting thing is, folks willingly pay 30% fees on the two app stores. Fees are part of life.

I suggest you make a trial of offering paypal .  Give it six months. **Yes**, charge more for paypal.

(Make it a different deal.  Just add a new item "PayPal™ deal: six months for $25".  You don't have to "explain" why it's a couple dollars more, every living human knows all this.  And don't bother with the short terms. PayPal payers are "convenience shoppers", they want simplicity.)

You'll be amazed how many sales you get.  Good luck!

**Comment by photopea** [comment]
I have added the PayPal option with a 10% fee.

**Comment by MichalSZZ** [comment]
I think it is a good test for you. In UX it is called MVP and this one little thing can turn your thinking about people and their thinking about secure payments in Internet and money saving.

**Comment by smhk** [comment]
The new PayPal system works perfectly. I already bought a license.

Getting users to pay is all about convenience.  Best of luck!

It's so much better with no ads. What a great product!

**Comment by photopea** [comment]
thanks! :)
