### ISSUE TITLE
freezing

### ISSUE THREAD

**Issue by Bunnly** [photopea/photopea#4784]
I want to make a curve with the pen tool and i choose stroke. i click on the screen and photopea freezes.

**Comment by photopea** [comment]
I am not able to make Photopea freeze :( could you describe exact steps, which always make Photopea freeze? Or record a short video of what you do?

**Comment by Bunnly** [comment]
I used a tool and then the next time i used it photopea freezes so i dont know what happened

**Comment by photopea** [comment]
Please, show some proof of what happened and how did you make it happen.

**Comment by photopea** [comment]
I have to close it because of lack of details.
