### ISSUE TITLE
Layer Combinations do not work when exporting to SVG

### ISSUE THREAD

**Issue by Baegus** [photopea/photopea#4786]
I think there's a bug when using the **Export Layers** -> **Combinations** feature. It works fine when I export to PNG, but it only creates completely empty canvases when using SVG.

Exporting a single layer as SVG works fine with this project, so it's probably caused by the Combinations feature.

**Comment by photopea** [comment]
It should be fixed now, could you let me know if it works? I dont know what happened, I just updated a new version and it started working.

**Comment by Baegus** [comment]
> It should be fixed now, could you let me know if it works? I dont know what happened, I just updated a new version and it started working.

Yup, works now. Thanks!
