### ISSUE TITLE
https://fixthephoto.com/ > release clipping mask option missing and ungroup option missing.

### ISSUE THREAD

**Issue by sinaibnamin** [photopea/photopea#4787]
https://fixthephoto.com/  the online illustration tool > release clipping mask option missing and ungroup option missing.

**Comment by photopea** [comment]
We are not Fix the photo, we are Photopea. How exactly can we help you?

**Comment by reikrom** [comment]
https://fixthephoto.com/pl/illustrator-online.html might be due to them embedding your website

**Comment by photopea** [comment]
I know, but I still don't understand what the author wanted :(
