### ISSUE TITLE
Photopea Locking Up when opening specific file

### ISSUE THREAD

**Issue by blackops786187** [photopea/photopea#4788]
Hi,

I am trying to open up a sketch file from this [link ](https://www.behance.net/gallery/146257857/Street-Fighter-6-UI-Kit?tracking_source=search_projects%7CTekken%206) in photopea in order to convert it to a psd file to use in Adobe Photoshop CC. 

When i open it, the UI effectivly locks up and attempting to save it results it gets stuck on saving. Also other projects open up at the same time lock up aswell. This happens on all browsers so im assuming the file is at fault. I have tried resetting the browsers to no avail

Can you advise?

**System Details**
- Windows 10 21H2 (Build 22000.739)
- Ryzen 5 3600x with 32gb RAM

**Browsers Tested**
- Firefox 102.0
- Chrome 103.05060.66

**Comment by photopea** [comment]
Fixed! :)
