### ISSUE TITLE
UI of save dialog for mobile devices

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4792]
I tried to draw a mobile style UI for the save dialog. How does it look?
![dialog](https://user-images.githubusercontent.com/79258245/177046189-3d1e0085-14f0-4ca0-967e-81345fcac6be.png)

You can find the details in [this figma file](https://www.figma.com/file/kdSrPB9JXhqTjiyCeK30lF/save-dialog?node-id=0%3A1)

**Comment by photopea** [comment]
Have you seen the current export dialogue?

Your design is missing the exact size (in Bytes). Also, i think the preview area is very small. When you export a JPG, it is very useful to zoom in and see the quality.

I see you have labels on top of text fields (a Photoshop style). But shouldn't we have the same style for big and tiny screens?

**Comment by photopea** [comment]
I have implemented the new style :)
