### ISSUE TITLE
Feature Request: an OCR plugin

### ISSUE THREAD

**Issue by xan2622** [photopea/photopea#4797]
Hi.

I think it would be useful if Photopea had an **OCR plugin**.
The user would load an image with a text, the plugin would detect the text and display it as a readable (and selectable) text.

Here is an open-source project that might help create this plugin: https://github.com/naptha/tesseract.js

**Comment by xan2622** [comment]
As usual with OCR systems, the text recognition works best with paragraphs displayed with a high contrast.

![Capture d’écran 2022-07-08 231513](https://user-images.githubusercontent.com/1732773/178072529-449be048-f330-4baf-8763-bf1f2ddfbadd.png)

Here (below) the result missed the "W" but again, it's because of the library, not because of your implementation (which once again, amazes me by its quality. The UI is simple, efficient.).

![Capture d’écran 2022-07-08 232320](https://user-images.githubusercontent.com/1732773/178072542-42fd0790-10cb-4805-8efa-c4ee5d5ab190.png)

Another example with a paragraph slightly blurred (at the bottom):

![Capture d’écran 2022-07-08 233438](https://user-images.githubusercontent.com/1732773/178073473-d07728c3-973e-4d10-9d4c-90b4ddcafda7.png)

Thank you @hxim for this plugin.

**Comment by photopea** [comment]
@hxim wait a minute, are you a magician or what? :D I literally think you might be spending more time developing photopea features than I do.

**Comment by sizeblut** [comment]
> Tôi vừa thêm plugin OCR sử dụng API Tesseract.js vào các plugin. Vui lòng kiểm tra xem nó có hoạt động chính xác không.

Can I ask you about the OCR plugin you created? I can't find it anywhere anymore. Did you delete it?

**Comment by photopea** [comment]
Go to www.photopea.com and press Window - Plugins. The OCR Plugin is still there.
