### ISSUE TITLE
"app.open()" not working

### ISSUE THREAD

**Issue by Brook-sys** [photopea/photopea#4798]
the command "app.open()" doesn't work, it just pops up a box that says "Loading...." and it never returns, I've tested it with several images from different sources and it's always the same, the only site that worked was "i.imgur", I wanted to understand if it's a mistake or a proposal.

**Comment by photopea** [comment]
I think it is because of the CORS restriction.

In general, a website at a domain A can not load and read a single bit of information from a domain B, unless the domain B explicitly allows it.  https://en.wikipedia.org/wiki/Cross-origin_resource_sharing
