### ISSUE TITLE
A gap at right side both of a site and an app on the computer

### ISSUE THREAD

**Issue by SlimeChannel** [photopea/photopea#4799]
![A screenshot](https://user-images.githubusercontent.com/94016092/177429539-95ba1260-bf16-4e2f-8098-cacbed406a61.png)

**Comment by photopea** [comment]
There should be advertisement on the right side.

Are you using any ad blockers? Which one are you using?

**Comment by SlimeChannel** [comment]
I'm not using any ad blockers, maybe it's because i'm from Russia? The same thing as on youtube, I mean, that there are no advertisements for me. It would be logically

**Comment by photopea** [comment]
Did you try to disable all your browser extensions? You can never know what extension does what. They are all allowed to modify the website any way they want.

**Comment by SlimeChannel** [comment]
No, I just disabled everything and there are still no ads. It's definently not because of extensions.

**Comment by xan2622** [comment]
My guess is that if you [refused cookies the first time you opened Photopea](https://github.com/photopea/photopea/issues/4552#issuecomment-1114163653) (especially read [this comment](https://github.com/photopea/photopea/issues/4552#issuecomment-1114179010)), you can't see ads at all.

**Comment by photopea** [comment]
Try this: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
