### ISSUE TITLE
Snapping

### ISSUE THREAD

**Issue by aolko** [photopea/photopea#48]
please add snapping

**Comment by mathiasrw** [comment]
Snapping to what? the border?

**Comment by aolko** [comment]
to grids, to objects, to guides, you know, like in photoshop

**Comment by mathiasrw** [comment]
It just makes it easyer if we are specific in our requests to the developer

**Comment by tomasnosek** [comment]
At first - there is no grid in photopea yet. Most important is a Grid system and snapping to this. It's a core feature. +1

**Comment by photopea** [comment]
Snapping and Grid have been added :)  sorry for a one-year delay.

**Comment by aolko** [comment]
Shapes do snap, other tools like brush - don't

**Comment by photopea** [comment]
But isn't it counter-intuitive? You need brushes to move "freely" while drawing.

**Comment by aolko** [comment]
look at photoshop
![](https://forums.adobe.com/servlet/JiveServlet/downloadImage/2-3404815-54440/Screen+shot+2011-01-15+at+2.52.50+PM.png)

**Comment by photopea** [comment]
Ok, I enabled snapping for "brushy" tools too (brush, eraser, clone stamp, dodge, smudge ...). Do we need it for any other tools?
