### ISSUE TITLE
Elements blocking click Photoshop Online

### ISSUE THREAD

**Issue by alanbeltrao** [photopea/photopea#4800]
Hey! 
There is a container that is making it impossible to open a menu bar, because it overlap these options. It's circled in red in the attached screenshot.
It's not just the logo, but a shadow behind the logo that prevents clicking.
It only works perfectly when I delete the element by inspect element. But it sucks having to do this all the time. (Print attached).
I hope it gets resolved.

![WRITE](https://user-images.githubusercontent.com/108808693/177556760-9b71e42d-5225-42cc-900b-3d6faac2c2f4.jpg)
![INSPECIONAR](https://user-images.githubusercontent.com/108808693/177557292-88b51eac-b41d-4d4a-a225-77f8ac6c1e10.jpg)

**Comment by photopea** [comment]
Hi, could you try to use Photopea at www.Photopea.com ? We can not decide how people embed Photopea into their websites :(
