### ISSUE TITLE
SIMPLE and amazing feature idea that would be hugely popular.

### ISSUE THREAD

**Issue by smhk** [photopea/photopea#4801]
I had 10 images (actually .webp).  I opened my awesome PAID! copy of photopea

On my mac, I selected the 10 images and dragged them in to photopea - works perfectly

Next I simply wanted to save them as jpg - so, Export as -> JPG -> tap Save -> Tap "X" close on that file window.

**It would be incredible if there was a batch feature.**

The super-simple way to do this:

On the "Save for web" dialog box. Simply add another checkbox, "[ ] Save all >10< open files?"

That's it. It's that easy.

It would be an incredible feature, particularly for programmers.

**Comment by photopea** [comment]
While a 3000x4000 px image file could be just 1 MB in size, it uses 192 MB of memory when opened in Photopea. You might quickly run out of RAM when opening them all simultaneously.

Check Window - Plugins, there is a plugin "Batch Edit Tool", would it be sufficient for your needs?

**Comment by MichalSZZ** [comment]
There are sites doing exactly what you need. What that sites doesn't have? Did you make a research?

**Comment by smhk** [comment]
hi @photopea  I guess, most programmers use 32 - 64 + gb machines these days.  I just opened 5 files in photopea with no issue.

I will check out the plugin thanks, but it would be a super-handy feature, more basic and everyday than fooling with a plugin.  One extra buttoin "save all"!

**Comment by photopea** [comment]
I have added this feature into File - Automate - Convert Formats.

Unlike your proposed solution, this can handle hundreds of files at once.

**Comment by smhk** [comment]
Wow.  incredible.
