### ISSUE TITLE
Magic cut

### ISSUE THREAD

**Issue by DaafPF** [photopea/photopea#4803]
when I open magic cut, and then try to select, my project keeps disappearing. At first I didn't have this, but if I keep clicking on something, my workpiece goes away. *I can no longer make youtube videos. this is a serious problem.*

**Comment by photopea** [comment]
what is the Width and the Height of your document? You can see it in Image - Image Size.

**Comment by DaafPF** [comment]
when i zoom in with magic cut it also becomes invisible, it disappears and i don't know what to do about it, no matter how big it is, if i magic cut and do something it disappears.

**Comment by DaafPF** [comment]
when i zoom in with magic cut it also becomes invisible, it disappears and
i don't know what to do about it, no matter how big it is, if i use  magic
cut and do something, it disappears.

Op do 7 jul. 2022 om 19:20 schreef Photopea ***@***.***>:

**Comment by photopea** [comment]
So you are able to make this problem happen on purpose, and it breaks every time? Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
