### ISSUE TITLE
upload an image into a PSD file

### ISSUE THREAD

**Issue by Brook-sys** [photopea/photopea#4804]
I know there is a way to do this using "app.open()" but this method is limited to links and there is still the issue of CORS and etc, I would like a way to be able to add an image (local file) through code, I followed some code demos using arraybuffer however this creates a new PSD file, I wanted a way to add to an already created PSD file.
Is it possible?
To be more specific I was creating a site in Localhost with Js, to automate an image editing that would be tedious, and would need an image to be added to a psd file.

**Comment by photopea** [comment]
If you send Photopea a file (arraybuffer), it is opened as a separate document. But then, you can run a script, which copy-pastes a layer from one document to another, and closes the old document.

Also, you can call app.open() with a URI which contains the file already, like "data:image/png;base64,iVBORw0KGgoAAAAN..."

**Comment by photopea** [comment]
I have to close it because of lack of details.
