### ISSUE TITLE
Request: Selection Tool "Fixed Size" Unit Support

### ISSUE THREAD

**Issue by Elevory** [photopea/photopea#4805]
Hi, love the product! It's honestly hard to believe how much more responsive Photopea is compared to the industry standard. As far as I can tell, there are just a few missing features.

For example, PhotoShop allows us to enter a unit in the "Fixed Size" boxes of the Selection Tool:

![image](https://user-images.githubusercontent.com/29494707/177893276-23b8312a-7817-4a84-a032-30178a6c581e.png)

This is particularly useful when you want to quickly select, say, half your canvas by percent.

Any chance this could be added in the future?

Thanks!

**Comment by photopea** [comment]
It would be very hard to add :( When selecting, the tool should snap automatically to the center of the canvas.
