### ISSUE TITLE
Request: Auto-Select Group Instead of Layer

### ISSUE THREAD

**Issue by Elevory** [photopea/photopea#4806]
Hi,

When clicking on an object with the Move tool in PhotoShop, you can choose whether to select the object's layer or the group it belongs to. Is there a similar option in PhotoPea?

![image](https://user-images.githubusercontent.com/29494707/178054936-a0131eee-ab29-42a1-b992-79241229f727.png)

Thanks!

**Comment by photopea** [comment]
I am afraid there are already too many items in the Move Tool menu at the top. Should we remove the "quick export", or at least the scale parameter?

**Comment by Elevory** [comment]
> Should we remove the "quick export", or at least the scale parameter?

I wasn't aware of the quick export options - they're pretty cool and I bet some people make use of them with regularity. That said, how about migrating these features into a new subtool? i.e. Move Tool / Artboard Tool / Quick Export Tool. I imagine that would solve the menu space issue.

**Comment by xan2622** [comment]
May I suggest to move the "_Scale for exported files [1x   ]  and the ⬇️PNG ⬇️SVG buttons_) ... 
![Capture d’écran 2022-07-19 191504](https://user-images.githubusercontent.com/1732773/179814619-882b83a7-a149-4f56-bf6f-ab6526c4aeb4.png)

...into a new "Quick Export" button?
![Capture d’écran 2022-07-19 191504(1)](https://user-images.githubusercontent.com/1732773/179814700-9e4e0139-e78c-46c3-8005-8382bb989a1e.png)
... a "Quick Export" button that would display a simple pop-up window like this one: 
![19 194426](https://user-images.githubusercontent.com/1732773/179820463-ce2db02b-dd59-4d40-b8de-f412ca9d9787.png)


This way, adding the Group/Layer drop-down menu wouldn't take much space: 
![Capture d’écran 2022-07-19 191504(2)](https://user-images.githubusercontent.com/1732773/179814787-7de160f4-669f-4cc4-b45a-0fbc40bf9bd7.png)

**Comment by Elevory** [comment]
That looks great, [xan2622](https://github.com/xan2622)! My only suggestion would be to have the "Quick Export" button occupy a space in the top menu instead - perhaps to the left of the "Account" button. I don't think it makes much sense that we have to activate the Move Tool in order to quickly export something.

**Comment by xan2622** [comment]
> My only suggestion would be to have the "Quick Export" button occupy a space in the top menu instead - perhaps to the left of the "Account" button

tbh, I am not a huge fan of adding other tools/options/buttons onto the top menu. 😕 

But I agree with you, I think these "Quick Export" options ("Scale for exported files [1x ] & the ⬇️PNG ⬇️SVG buttons") look a bit weird located on the "Move tool" toolbar.

I tend to think that it would make more sense to add a "Quick Export" entry on that right-click menu:

![Screenshot_20220721-084129_Firefox](https://user-images.githubusercontent.com/1732773/180149382-97ba653d-bd3b-4151-98d5-2c5bbf076aca.jpg)

This would allow the user to export the selected layer or the selected group.. but that would make this right-click menu bigger.. UI design is sometimes not that easy. 😅

**Comment by photopea** [comment]
it should be implemented now :)
