### ISSUE TITLE
Request: Improve Snap Guide Lines

### ISSUE THREAD

**Issue by Elevory** [photopea/photopea#4807]
Hi,

When working with a document that has many layers, it can be difficult to snap an object to an intended location - the red guide line should extend further to help the user understand what an object is being snapped to.

To illustrate the problem, here is the snapping guide in PhotoPea:

![image](https://user-images.githubusercontent.com/29494707/178058063-dc9c54b0-13ab-491c-85ff-6f49b7829fd9.png)

And here it is in PhotoShop:

![image](https://user-images.githubusercontent.com/29494707/178058022-ff2868a0-142a-459d-bed8-dbc11650653c.png)

Thanks!

**Comment by photopea** [comment]
I have implemented it! When snapping to layers, the line is longer, to the center of a snapped object.
