### ISSUE TITLE
Feature Request: VintageJS plugin

### ISSUE THREAD

**Issue by xan2622** [photopea/photopea#4808]
To apply a quick vintage effect on an image, it would be convenient if Photopea had a plugin like this:

source code: https://github.com/rendro/vintageJS
demo: http://rendro.github.io/vintageJS/

There would be an option (a checkbox) to let the user decide if he/she wants to add the "vintage border" and another one for "scratches, tears, cracks" (or even, several checkboxes for one of these "picture imperfections").

**Comment by Elevory** [comment]
Personally, I would rather see PhotoPea concentrate on adding support for "Neural Filters" like PS, which includes a Style Transfer option suitable for getting that vintage effect:

![image](https://user-images.githubusercontent.com/29494707/178123957-cebef7ed-66c6-4951-9642-902dab793864.png)

That said, I don't expect a free PhotoShop alternative to compete in the costly realm of machine learning - vintageJS might be a more realistic request.

**Comment by xan2622** [comment]
While I'd be happily surprised to see _Neural Filters_ in Photopea (and probably being developed by Ivan himself), VintageJS could be implemented by another developer. One does not preclude the other.

**Comment by photopea** [comment]
@xan2622 come on! If you really know how to use Photopea or Photoshop, you can create these effects in 15 seconds. Or you could probably find actions online (.ATN), which do that.

**Comment by xan2622** [comment]
I do (I have been using PS since CS 2, IIRC) but some other people might not know..
And this kind of quick effect is pretty common in other photo editors.. so I thought it was a legitimate request.

**Comment by photopea** [comment]
You can use this style transfer in Photopea now: https://twitter.com/photopeacom/status/1430988598929764355
