### ISSUE TITLE
Feature Request: a Clouds Generator plugin

### ISSUE THREAD

**Issue by xan2622** [photopea/photopea#4809]
It would be pretty cool to be able to generate our own realistic clouds thanks to a "Clouds Generator" plugin. 
IMO, the following project succeeds to create very visually credible clouds:

Article: https://css-tricks.com/drawing-realistic-clouds-with-svg-and-css/
Demo: https://www.nephele.cloud/
Source Code: https://github.com/beauhaus/Nephele

<img src="https://user-images.githubusercontent.com/1732773/178110049-1d72b546-f14c-41ca-8a59-732319f50bcb.png" width="60%" height="60%">

The demo allows the user to modify values such as: 
- blur radius
- spread radius
- numOctaves
- baseFrequency
- scale
- seed

**Comment by Elevory** [comment]
Those look much nicer than PhotoShop's generated clouds! (Which, to be fair, are used more as a way of adding noise than actual clouds.)

**Comment by photopea** [comment]
@hxim would you be interested in it? If you decide to do it, and send an SVG to Photopea, let me know if there are problems.

**Comment by hxim** [comment]
I looked into it and I was able to replace CSS box-blur which is used there with SVG ellipse, radialGradient and feGaussianBlur features. I don't think I will be able to load such SVG to photopea (as vector image). I plan if possible to convert it to raster (PNG) first and send it to Photopea as raster image.
Possible UI of plugin:
![obrazek](https://user-images.githubusercontent.com/6370548/179369729-32c1401c-ff6d-4c51-b286-89617a8f7001.png)

**Comment by xan2622** [comment]
Would it be possible to add a "Random" button (or maybe two, one to randomize all "Cloud options" and another one to randomize all "Shadow options")?

**Comment by hxim** [comment]
Hi, I added it to Photopea. Please tell me if you have more ideas or something is not working.

**Comment by xan2622** [comment]
This cloud generator is really impressive! Thanks a million @hxim.

My first test: 

![dfgdfg](https://user-images.githubusercontent.com/1732773/180054583-4693a041-e49f-474a-a7ac-f3d798c309a9.png)

**Comment by Elevory** [comment]
> Hi, I added it to Photopea. Please tell me if you have more ideas or something is not working.

Love it! It's great to see Photopea introducing features that not even PhotoShop has. I mean, let's be honest, these aren't exactly "clouds":

![image](https://user-images.githubusercontent.com/29494707/180104678-d88d6326-9196-40d6-91d6-e80f2691ca6a.png)

Anyway, great work. :)

**Comment by photopea** [comment]
@hxim wow, that is amazing!

My long-time dream came true! (to make Photopea a platform, which groups various graphics features from different authors - a place to share such features, instead of them being randomly scattered across the internet).

Note, that since your plugin is a website, you can eventually ask people for money for using your plugin, etc.

**Comment by photopea** [comment]
@hxim Hey! Do you think it would be possible to turn Photopea into a Figma plugin? I found this: https://www.figma.com/plugin-docs/setup/ But I can not see, if thy allow displaying a whole website in an iframe. If yes, we could integrate it and inter-connect it with Figma and their API.

People could use Photopea to edit raster graphics of Figma documents inside Figma.
