### ISSUE TITLE
Request: Pencil Tool's 1-pixel thick, aliased lines improvement

### ISSUE THREAD

**Issue by konstantin3002** [photopea/photopea#4810]
Hello! 
When using the Pencil tool for creating lines (shift + lmb), I noticed that the lines themselves are drawn a bit weird, compared to the PS one (with the same brush settings). Comparison below:
![image](https://user-images.githubusercontent.com/67711684/178111281-cd440e34-7f16-43fe-a845-0adc29105bfc.png)
Photopea on the left, PS on the right.
I can only guess it's the rendering/rasterization rules issue.

I mostly use PS for pixelart, so it's kind of the only thing stopping me from switching from PS altogether.
Thanks in advance!

**Comment by photopea** [comment]
It should be fixed now. The painting in Photopea in this case should look the same as in Photoshop.

**Comment by konstantin3002** [comment]
Can confirm, the change in thickness for 1 pixel thick pencil has gone away.
But the new lines experience sudden changes in pattern:
![image](https://user-images.githubusercontent.com/67711684/179175584-5ce7c251-f0e1-40ef-aa57-26774ffdec63.png)

**Comment by photopea** [comment]
Adobe Photoshop does the same thing, if that is what you mean.

**Comment by konstantin3002** [comment]
Not really:
![image](https://user-images.githubusercontent.com/67711684/179181770-67c2c57d-659f-4a2b-83c8-6921c8082ac0.png)
Red ones are photoshop ones

**Comment by konstantin3002** [comment]
(same picture without the Photopea lines, the pattern should be more visible this way)
![image](https://user-images.githubusercontent.com/67711684/179182122-f94669cd-fc85-4859-a78a-2b545b4834f3.png)

**Comment by konstantin3002** [comment]
And, just in case, the most strange-patterned line next to a photoshop one:
![image](https://user-images.githubusercontent.com/67711684/179183420-2a2bd880-66d7-4387-a358-9daafeaa29ac.png)

By the way, is it technically a different issue? Should I make a new one, since this one is closed now? 
I'm not very familiar with github issue etiquette, sorry...

**Comment by photopea** [comment]
you are right, sorry, it should be fixed now.

**Comment by konstantin3002** [comment]
It is fixed, can confirm. Thank you!

**Comment by photopea** [comment]
Thank you for reporting it so thoroughly, and for your cooperation! :)
