### ISSUE TITLE
Glitch/unexpected behavior between transparent gradient and layer mask

### ISSUE THREAD

**Issue by Elevory** [photopea/photopea#4811]
Hello,

I'm encountering what is either a bug or unexpected behavior when trying to apply a gradient to a layer mask. More details:

- This gradient is fully opaque black at one end, and fully transparent at the other end.
- The layer mask is fully opaque white.
- When applying the gradient to the mask, the expected result is that it will smoothly transition from white to black.
- Instead, the mask becomes completely black.
- This is not consistent with PhotoShop's behavior.

Here's a video demonstration:

![brave_nt2qC24plD](https://user-images.githubusercontent.com/29494707/178123586-00f6b439-8f9b-4442-baff-362778fb96b9.gif)

Thank you!

**Comment by photopea** [comment]
It has been reported in 2020, I will try to fix it ASAP: https://github.com/photopea/photopea/issues/2481
