### ISSUE TITLE
Feature Request: "WaveFunctionCollapse Patterns plugin

### ISSUE THREAD

**Issue by xan2622** [photopea/photopea#4812]
[**WaveFunctionCollapse** ](https://github.com/mxgmn/WaveFunctionCollapse) is an algorithm that generates randomly distributed patterns based on an input bitmap image.

Implemented in Photopea (natively or rather, as a plugin), it would allow users to create very interesting patterns based on the currently active layer or selection.

**Javascript port:** 
Source Code: https://github.com/kchapelier/wavefunctioncollapse
Demo: 
[Interactive OverlappingModel demo](http://www.kchapelier.com/wfc-example/overlapping-model.html)
[Interactive SimpleTiledModel demo](http://www.kchapelier.com/wfc-example/simple-tiled-model.html)
[Animated SimpleTiledModel demo](http://www.kchapelier.com/wfc-example/simple-tiled-model-animated.html)

<img src="https://raw.githubusercontent.com/mxgmn/WaveFunctionCollapse/master/images/wfc.png" width="100%" height="100%">

The "Circuit" tileset: 

<img src="https://user-images.githubusercontent.com/1732773/178134244-b853436d-36a5-4d0a-97b7-ec1fec4a0c2d.png" width="50%" height="50%">

The "Summer" tileset: 

<img src="https://user-images.githubusercontent.com/1732773/178134245-3b74b8cd-584b-4ad9-b0f6-f4589db857cf.png" width="50%" height="50%">

**Comment by photopea** [comment]
I am really afraid that you are the only person who would use it :( but do you really want to use it? or you just find it interesting?

**Comment by xan2622** [comment]
I find the algorithm interesting yes. I would definitely use it and I think it might interest other artists who want to create patterns/textures. 

The examples shown above are very low quality patterns, imo, they don't really show what could be created with other better source graphics. 

That being said, I understand that you don't want the GitHub repository to be cluttered by hundreds of requests. You can close the issue if you want.

**Comment by photopea** [comment]
We could ask @hxim or @yikuansun if they want to turn it into a plugin. Ask the actual author to make a plugin for Photopea (it is extremely simple).

**Comment by xan2622** [comment]
I am sad that coding was not one of my skills (I tried to learn several times in the past but it is beyond than what my brain can do). 

As you suggested, I shall try to ask elsewhere other developers if they agree to create a plugin.
