### ISSUE TITLE
MAGIC CUT BUG

### ISSUE THREAD

**Issue by Gabryspino** [photopea/photopea#4813]
![Screenshot (369)](https://user-images.githubusercontent.com/109082108/178268756-8f07293b-1032-4178-9120-8a6f3425b03a.png)
using magic cut or enhance edge, clicking on the image with any color this happens

**Comment by photopea** [comment]
How exactly can I make it happen?

**Comment by Gabryspino** [comment]
happens by clicking the image

**Comment by Gabryspino** [comment]
sometimes by clicking returns to normal for less than a second

**Comment by photopea** [comment]
Sorry, I was not able to make it happen from your description :(
