### ISSUE TITLE
Magic Wand - Always leave a margin of the selection

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4815]
Many many times when i select a color with the magic wand and delete the selection it leave a margin of color, that was never selected.

Even if  the shape was exactly ONE color.
[Screen recording 2022-07-12 19.59.22.webm](https://user-images.githubusercontent.com/11801254/178618317-ed6f59c5-2b8c-4ff6-acdf-7da863118c7a.webm)

**Comment by photopea** [comment]
I can not reproduce it :( Do you set the "Feather" value at the top? 

If you have a white-to-black gradient, and you click on the black color with a magic wand, it will select black and not grey. You should use the Tolerance value at the top.

**Comment by photopea** [comment]
Also, why dont you record the whole screen, so that I can see what parameters you set, and if you do it in an empty layer or in a white layer?

**Comment by TheRadicalDreamer** [comment]
Yes sorry.

I didn't noticed i had 1 in the feather value.

That is all  :\
