### ISSUE TITLE
[XD] Photopea generating redundant filled overlay rectangles

### ISSUE THREAD

**Issue by timbotimbo** [photopea/photopea#4816]
I tried opening an .xd app design in Photopea, and it all seems to work besides some small icons.
I stripped down the document to only the elements with some issues.

In Photopea  (and a Photopea .psd export in Photoshop)  there seems to be a fill layer covering the icons.
<table>
<tr><td>Adobe XD</td>
<td>Photopea</td>
</tr>
<tr><td>

![xd](https://user-images.githubusercontent.com/11444698/178732901-73e190fb-4049-48e7-ae52-96e410a5aa6e.jpg)</td>
<td>

![photopea](https://user-images.githubusercontent.com/11444698/178732910-5bfc5f66-f060-4aac-a5b5-a4dd021dce9e.jpg)
</td>
</tr>
</table>

Looking further I can disable a "Rectangle x" layer in Photopea for nearly every element to get the working right.

![photopea-rectangles](https://user-images.githubusercontent.com/11444698/178733489-634b38ed-25e4-4fc6-b69f-38b7cbb7aba1.jpg)

I did not make the design, so it might have to do with the designer using weird layers and opacities.
Given that all elements were copied into a single artboard, some still include their parents with rounded corners etc.

But given that this is simple to reproduce, it can't hurt to post here.

In the following zip file is a small project to reproduce it.
[photopea-test.zip](https://github.com/photopea/photopea/files/9102092/photopea-test.zip)

**Comment by photopea** [comment]
Sorry, there was a bug, it is fixed now. Thanks a lot! :)
