### ISSUE TITLE
can't export file as other format 

### ISSUE THREAD

**Issue by Iamnotn3rd** [photopea/photopea#4817]
I'm working on my design ( using crop tool and select tool ) and then I can't export my file as png and other format 
it's just like that 

![Screenshot from 2022-07-13 22-11-50](https://user-images.githubusercontent.com/109126514/178775382-391e5d96-2ebe-45f5-b305-54af44733b3d.png)

**Comment by photopea** [comment]
That is strange. Could you save your work as a PSD and share it with us? Or press File - Publish Online - PSD, and show us the link.

**Comment by Iamnotn3rd** [comment]
I can't even save my file as PSD format and can't do anything related to that ! should I upgrade to premium?
![Screenshot from 2022-07-14 17-51-48](https://user-images.githubusercontent.com/109126514/178971616-4c85ac01-5ef6-44cf-badb-e8aa2bd4b3db.png)

**Comment by photopea** [comment]
I have to close it because the person stopped responding.
