### ISSUE TITLE
Weird pixels generating everytime a LUT is applied

### ISSUE THREAD

**Issue by turkdelight** [photopea/photopea#4818]
Purple, sometimes Green, pixels generate every-time I apply a color LUT to a picture. The image is fine when it stands as original but as soon as  LUT is applied it distorts the image and generates these pixels, changing the blending option alleviates some of the pixels but never all. I use Photopea on other devices and never have this problem, only on this specific computer. I don't have this issue with any other program like Photoshop that I use LUT's with
![006 (1)](https://user-images.githubusercontent.com/109312393/179073426-535a9e12-2bf6-4653-806a-a2e818ada98b.png)
![010 (2)](https://user-images.githubusercontent.com/109312393/179073429-cb6c9585-4018-400d-90dc-ff951966dae9.png)
![010](https://user-images.githubusercontent.com/109312393/179073436-4bc10002-a79f-4754-a8f0-e7
![MVI_1291 00_14_06_06 Still037](https://user-images.githubusercontent.com/109312393/179073704-d91bc6b9-d37c-4b91-a642-198e6eeb567e.png)
79d9734a71.png)
![MVI_1291 00_14_06_06 Still037 (1)](https://user-images.githubusercontent.com/109312393/179073710-a2bb8a72-c930-4aa3-840f-4e61cea04c2d.png)

![IMG_1215 (1)](https://user-images.githubusercontent.com/109312393/179073116-c0033bbc-38cf-4a92-a360-46e2931ee168.png)
![006](https://user-images.githubusercontent.com/109312393/179073121-5dc0d60a-e597-4f06-bf66-99c14bb8525b.png)
.

**Comment by photopea** [comment]
Could you please share your LUT with us?

**Comment by turkdelight** [comment]
> Owner
Sure but they are all CUBE, XMP, 3DL files. I can say I downloaded the same LUT packages for different computers and only one computer is giving me the pixelated issue but on every other computer with the same exact LUT file I don't have any issues on Photopea... that's why it's kind of frustrating as I feel like the issue is something not simple.

**Comment by photopea** [comment]
I still need to see the problem myself somehow :(

**Comment by photopea** [comment]
I have to close it because the person stopped responding.
