### ISSUE TITLE
Downlad 

### ISSUE THREAD

**Issue by anamarii1** [photopea/photopea#4819]
I wanted to report a problem, I downloaded a project as PDS and then closed the Photopea app. When I tried to open it in the same place, it told me that there was an error: "Unkown file format: \u0000\u0000\u0000u0000". If it was a project that I wouldn't have bothered losing, I would have let it pass, but this was an important project. in which I dedicated time to it and due to a problem I no longer have it. Please tell me that I can recover it.

**Comment by photopea** [comment]
Just make sure the "saving" disappears before you close Photopea.

**Comment by anamarii1** [comment]
thanks :)
