### ISSUE TITLE
crop bug

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#482]
See: https://youtu.be/xSjOQa4sxY8
I expected crop auto "selection" for actual canvas size but there is old canvas size.

**Comment by photopea** [comment]
Our cropping does not "trim" layers (so the layer remains wide, while the canvas is smaller).

You can simply draw your own rectangle from the top left corner to the bottom right corner (there is snapping on corners). Or resize the wide rectangle (also easy thanks to snapping).
