### ISSUE TITLE
I closed all AdBlocker, but still received the "Confirm"

### ISSUE THREAD

**Issue by DagueLee** [photopea/photopea#4820]
I closed my Adblock Plus and the "RemoveAds" script, but still received the "Confirm: Are you using an AdBlocker?". 
Why?
What should I do to avoid the "Confirm"?

**Comment by photopea** [comment]
I don't know what exactly is happening on your computer :(  

Could you try to temporarily disable all your extensions and everything else, what could modify the standard behaviour of websites?

**Comment by DagueLee** [comment]
> I don't know what exactly is happening on your computer :(
> 
> Could you try to temporarily disable all your extensions and everything else, what could modify the standard behaviour of websites?

OK, I'll try, thank you for replying.

**Comment by DagueLee** [comment]
> I don't know what exactly is happening on your computer :(
> 
> Could you try to temporarily disable all your extensions and everything else, what could modify the standard behaviour of websites?

No, it doesn't work.

**Comment by DagueLee** [comment]
I don't know why, it disappeared after I rebooted my laptop.

**Comment by photopea** [comment]
Photopea checks for ad blockers only once, at the start. If you disable your ad blocker while using Photopea, you need to re-open Photopea again.

**Comment by DagueLee** [comment]
> Photopea checks for ad blockers only once, at the start. If you disable your ad blocker while using Photopea, you need to re-open Photopea again.

Gotcha, thank you.
