### ISSUE TITLE
Resize/move/etc. context gets "stuck" on alpha channel

### ISSUE THREAD

**Issue by DizzyHSlightlyVoided** [photopea/photopea#4821]
Steps to reproduce:

1. Draw a rectangle shape, creating a new layer.
2. Create an alpha channel in the Channels tab.
3. Paste an image into, drawl lines in, or otherwise modify the alpha channel.
4. Attempt to move the rectangle.

It is now impossible to move or resize anything with the Move Tool or Free Transform except the contents of the alpha channel. Doesn't matter if you're clicking directly on the rectangle while its layer is selected, doesn't matter if the alpha channel is currently set non-visible. You can open the properties for the rectangle, modify and resize it, and the Move Tool will still focus exclusively on the alpha channel. Even pasting will paste to the alpha channel, regardless of what else you have selected.

The only way to get out of it is currently to either delete and remake the alpha channel (Undo traps you right back in the alpha channel's context), or to close and reopen the file.

**Comment by photopea** [comment]
I agree, if you select a specific channel, all tools are supposed to work on that channel.
