### ISSUE TITLE
Hide keyboard shortcuts labels in menu items on mobile phone

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4823]
People are unlikely use a external keyboard while using mobile phone. Hide these labels can make the UI simpler. How do yo think?
![image](https://user-images.githubusercontent.com/79258245/179382927-48cc2b8c-09bb-4a8a-8284-3134c59eb272.png)

**Comment by photopea** [comment]
I am afraid we can not tell if there is a keyboard or not. We could show keyboard shortcuts only on large screens (800 pixels wide or more), but is it the right way?

**Comment by iulover99** [comment]
how about make a options to hide and show it, so we'll let user decide whether or not they want to see them
