### ISSUE TITLE
when select a channel, other channels should be hidden and unselected

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4824]
That's how Photoshop works. Since other channels are hidden, only the selected channel is display on canvas, so people can easily understand that they are editing a channel in such a case.
![image](https://user-images.githubusercontent.com/79258245/179389615-dba0959b-b54c-4c2c-a752-2fc112c84787.png)

**Comment by photopea** [comment]
It should be fixed now.

**Comment by photopea** [comment]
it should also be fixed.
