### ISSUE TITLE
cannot add color sampler to color samplers collection.

### ISSUE THREAD

**Issue by g-freecss** [photopea/photopea#4828]
According to the docs that's how I add a color sampler to a color samplers collection, of a document.
`app.activeDocument.colorSamplers.add([10,10]);`

Although its correct, it does not work.

You can reproduce this in the playground.
<img width="328" alt="Screenshot 2022-07-17 at 19 04 58" src="https://user-images.githubusercontent.com/109038129/179419132-f27e31fc-a8dc-435f-85d3-9a7ea8c790da.png">

Is there any workaround? Is this bug already identified and being worked on?

**Comment by photopea** [comment]
We do not support color samples.

**Comment by photopea** [comment]
We have implemented the color sampler tool. Your script should work now.
