### ISSUE TITLE
Colors change when I upload a psd

### ISSUE THREAD

**Issue by LIFrench** [photopea/photopea#4829]
Hi,
I uploaded a psd to translate it, but the colors have been automatically changed by the website. Is this a known issue ? Have someone encountered such a problem before and know a way to fix it ?

Best regards

**Comment by photopea** [comment]
Could you share your PSD with us, or at least some screenshots? What do you compare it to? Colors in Photopea are different than colors in what program?

**Comment by photopea** [comment]
I have to close it because the person stopped responding.
