### ISSUE TITLE
Scaling layers with (non-rasterized) vector objects results in distortions

### ISSUE THREAD

**Issue by ocram** [photopea/photopea#4830]
1. You have a layer that is a “Vector Smart Object” (with a single effect: drop shadow).
 2. You select that layer in the list of layers by clicking on it to mark it as selected.
 3. You go to “Edit” → “Transform” → “Scale”
 4. In the toolbar with the attributes at the top, the width is now shown as something like 68600.00% and the height is shown as something like 70400.00%, instead of 100%.
 5. When changing any of the two percentages (e.g. via scrolling), both are suddenly mapped to the same value (1:1 aspect ratio), e.g. 68599.00%.
 6. And the problem and bug is that this immediately distorts the aspect ratio of the layer and decreases its size by a lot. So the layer becomes very small and distorted, even though you just scrolled to scale slightly.

This problem disappears when “Rasterize” is first applied on the layer – but that’s usually not what you want, obviously.

**Comment by photopea** [comment]
I am afraid I can not reproduce it :( 

The Width and the Height are linked to the same ratio only if the "chain" icon between them is enabled.

**Comment by ocram** [comment]
Thanks for looking into this!

> I am afraid I can not reproduce it :( Could you share your PSD with us?

Since the file is proprietary, I’m not allowed to share it here publicly, unfortunately. But I’ve just sent the file to your “support@” email address so you can use it for debugging and reproducing the problem internally.

> The Width and the Height are linked to the same ratio only if the "chain" icon between them is enabled.

I know that. But the thing is, if I rasterize the layer first, both the width and the height will be initialized to `100.00%` when scaling. So the lock/chain does not matter.

But if I do *not* rasterize and instead keep the vector (which is, of course, what I want), both width and height are initialized to those huge percentage values indicated before (which are *not* 1:1).

So locking the aspect ratio via the chain icon *shouldn’t* actually make any difference. And it’s not the issue here.

Also, clicking the “X” icon to cancel does not do anything when scaling the vector (wrongly). Cancelling does not restore the old size but instead keeps the distorted, tiny version of the layer.

Finally, it turns out, this is not specific to scaling at all, but a general vector problem: That’s because, when choosing to *edit* the “Smart Object”, after making a tiny change and saving it back to the original file, the layer in the original file is distorted just in the same way as it would have been with scaling.

**Comment by photopea** [comment]
It should be fixed now :)
