### ISSUE TITLE
Put "Create translation" at top of the list

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4831]
People will more easily find that they can help translate. 

Besides, could you change the "Create translation" to "Help translate"? "Create translation" sounds like I can create translation for languages that are not existing in the list yet. I think "Help translate" might be better.

**Comment by photopea** [comment]
If we promote it too much, there will be more vandals, too.

At the moment, it seems like all translations are pretty much finished, there is no need to tell even more people to translate it.
