### ISSUE TITLE
Eraser in raster

### ISSUE THREAD

**Issue by Hembc230** [photopea/photopea#4834]
The Raster mask is not erasing when i use the eraser tool.

**Comment by photopea** [comment]
Raster mask can not have transparent parts. It can only have white, black or gray parts.

The Eraser tool "paints" with a Background color (while the Brush tool paints with a Foreground color). Are you aware of this?

**Comment by Hembc230** [comment]
either way it use to 'paint' with the background color but it doesn't anymore

**Comment by photopea** [comment]
What should I do to see the bug myself?

**Comment by photopea** [comment]
I have to close it because the person stopped responding.
