### ISSUE TITLE
Suggestion: Add keyboard shortcut to hover labels for all buttons to improve learning curve

### ISSUE THREAD

**Issue by danielhaan** [photopea/photopea#4836]
## Suggestion
I would like to suggest adding keyboard shortcuts to the text when hovering buttons in the application. I cannot imagine it would be too hard to implement if only a bit tedious.
I know it's already added in some places (like the tool selection buttons), but would be ideal for all locations.

## Benefit
This will help users to "learn as they go" and become super users. This benefits the user (more efficiency, easier learning curve), and will also benefit photopea (better users are more likely to buy a license).

If this is not of interest, feel free to simply close the issue without comment :-)

**Comment by photopea** [comment]
I beleive that it is already done. Many buttons do not have any keyboard shortcuts.

Please, tell us, which buttons have shortcuts, but it is not displayed at hover.

**Comment by photopea** [comment]
I have to close it because the person stopped responding.
