### ISSUE TITLE
Feature request: Copy + Paste layer styles

### ISSUE THREAD

**Issue by rcoenen** [photopea/photopea#4838]
I like to copy the layer effects (outline, drop shadow, etc etc) from layer A and paste them onto layer B - just like how it work sin Photoshop

**Comment by MichalSZZ** [comment]
Or you can drag and drop layer style with Alt to duplicate all the effects or separate layer style.

**Comment by rcoenen** [comment]
Ok that is well hidden.. and quite different than Photoshop's contextual (right-click) menu:

<img width="254" alt="Screenshot 2022-07-21 100538" src="https://user-images.githubusercontent.com/753704/180233903-d3c964f6-7c30-4504-a3ed-baea43657118.png">

**Comment by xan2622** [comment]
tbh, I like that the _Layer Styles_  commands (copy, paste, clear) are in a sub-menu. It lowers the right-click context menu height a bit.

**Comment by photopea** [comment]
I have added the layer-style-copying actions to a context menu of layer styles. They are grouped, too, as I think it is "less messy".
