### ISSUE TITLE
Experiencing odd behavior regarding marquee selection bounds

### ISSUE THREAD

**Issue by Elevory** [photopea/photopea#4839]
Hi,

First, just wanted to say thank you for addressing some of the other issues I posted so quickly. Gives me a lot of optimism about this product's future! 👍 

Moving onto the issue: with the rectangular selection tool, I noticed I could select any region outside of the canvas. I thought this could be intentional behavior, but I'm no longer able to reproduce it (perhaps the app was updated in the last few days?)

However, I'm still seeing some inconsistencies with the tool. Here's an example with "fixed size" mode:

https://user-images.githubusercontent.com/29494707/180105778-addf0901-018f-4c96-92dc-e7f859f0b473.mp4

As you can see, it extends beyond the top and left of the canvas by the size I've specified - 100px in this case. It is properly constrained to the bottom and right sides.

Harder to reproduce is an issue with "fixed ratio" mode whereby the tool is not constrained by ratio nor canvas boundaries:

https://user-images.githubusercontent.com/29494707/180106252-f4ed61aa-db9b-4256-8341-6c21acf2f941.mp4

I'm not sure what conditions cause this - I had to restart my screen recording a few times to capture evidence of it.

Let me know if I can provide any other useful debugging info. Thanks!

**Comment by photopea** [comment]
Our users wanted us to make it work the same as in Adobe Photoshop. The tool should never draw outside the document area. But you can move the selection later anywhere you want.

I have fixed the issue of the first video. However, I can not make Photopea draw "freely", when a "Fixed Ratio" is selected :( Do you see any errors in a web console when it happens?
