### ISSUE TITLE
Cursor Issue

### ISSUE THREAD

**Issue by karthickraja96** [photopea/photopea#484]
Hi Photopea creaters,
 Hatsoff to your efforts for making this wonderful tool online. Minor issue im facing in photopea is, whenever i choose a tool and get in to workspace cursor is not changing in to icon it remains the same.
For example i f we choose a paint brush we cannot assume how large or small the brush is, so it is uncomfortable to use. Kindly fix this issue.

**Comment by photopea** [comment]
Hi, thank you! The size of brush cursor should correspond to the diameter of the actual cursor.

What browser and OS do you have? Can you please update your browser and see if it helps?

**Comment by karthickraja96** [comment]
Thank you so much for the response. I am using google chrome, and windows 7 OS.

**Comment by photopea** [comment]
Thanks! What is your devicePixelRatio? You can find it here: https://johankj.github.io/devicePixelRatio/

What cursor exactly do you see when using a Brush tool?

**Comment by karthickraja96** [comment]
Pixel ratio is 1. I will explain it very clearly if we choose any tool and enter in to the work space it will automatically change in to the tool's icon. But in my case it is still remains as the **mouse cursor** (If the paint brush is selected then the cursor should be in **round shape** but it is'nt.)

**Comment by photopea** [comment]
"if we choose any tool and enter in to the work space it will automatically change in to the tool's icon" - how do you know that?

So you have several computers and it works differently on your computer than on other computers? Or did it work differently before (on your computer)?

**Comment by karthickraja96** [comment]
Yep, ofcourse it worked once but not for a while, once the page is reloaded we are facing the same. I have been using photopea for the past 2 months worked more than 10K images. Please fix this.

**Comment by photopea** [comment]
We did not make any changes to the behavior of cursors. They work the same for me as they used to (I also have Chrome and Win 7).

Can you try to open Photopea in anonymous window? Will cursors start to work? Can you try to disable some browser extensions?

**Comment by karthickraja96** [comment]
We did not make any changes to the behavior of cursors. They work the same for me as they used to (I also have Chrome and Win 7). - Okey  i think problem is on our side it seems. Let me try all the ways you've said and update. Thank you!

**Comment by karthickraja96** [comment]
Thank you! Close my request. I am working so fine with your tool, If any further issue i'll let you know. If i can rate your site would rate u 4.5 out of 5. Great job keep going :)

**Comment by photopea** [comment]
Why not 5 out of 5? :D Do you know a better free photo editor? :D  Please, give us a "heart" here: https://alternativeto.net/software/photopea/ (or write a short review - one sentence).
