### ISSUE TITLE
Thoughts on the Photopea Community & Support Eco System

### ISSUE THREAD

**Issue by rcoenen** [photopea/photopea#4840]
One of the best things about Photopea, other than being a free, browser-based, equivalent to Photoshop, is the massive organic community support: Dozens of helpful posts n anything from Facebook to Reddit, and hundreds of How To Youtube videos.

In order to help & cultivate the growth of this grassroots support system, we might want to introduce a clear "numbering" scheme to Photopea. Increasingly I find outdated examples online that were written or recorded using a version of Photopea that now has evolved. And it is hard to tell sometimes.

Just like how there are youtube videos showing "hot to export animated Gifs in Photoshop 6" vs "Photoshop CS 2022" -- the workflow has changed drastically between these versions that are about 10 years apart after all -- we should do the same with Photopea. Photopea is now 8 years old. Photopea 2022 is not the same as Photopea 2013 anymore. 

Probably it's worth introducing some form of easy recognizable "version" every time a (not so-) major UI update happens? This so that Youtube videos, Reddit posts, etc. can refer to "Photopea 2022" so that in 2024, when someone is looking for a specific answer to a problem, and when that answer is no longer correct in 2024... then someone can post an update for the "Photopea 2024"? 

Thoughts?

**Comment by Elevory** [comment]
I agree that PhotoPea could use a better versioning scheme. It's also useful for marketing purposes (i.e. _"PhotoPea 2024 is finally here... check out all these new features!"_).

On the other hand, you have to keep in mind that this is a small product by one (?) developer - it's not going to follow the same sort of rigid development lifecycle that's sort of necessary with larger software like PhotoShop.

Either way, when I go to About -> PhotoPea I want to see something about a version (as much as I enjoy reading about Ivan's backstory.)

**Comment by xan2622** [comment]
I regret that https://blog.photopea.com/ is not more often updated. I wish this page could be like a changelog with all changes listed (it seems that currently, only major updates are showcased).

**Comment by photopea** [comment]
Hi guys. I don't think that when you did something in Photopea in 2013, it is done differently now. Features were added, but all old features should still work! Could you show me a tutorial for Photopea which does not work anymore?

Photopea is updated around 15 times a week. During the last months, I have been fixing bugs and improving existing features, rather than adding new ones. When I add a small feature, I post about it on Facebook and Twitter. Once there is a lot of new features, I make a blog post mentioning them all. 

You see that there are five months between Photopea 5.2 and 5.3. But it was updated 300 times during that period, and new features were added gradually during the five months, rather than all at once.

**Comment by rcoenen** [comment]
Ivan - my observation actually goes back to #4838 ("Copy + Paste layer styles")
I thought that if you were to change the behaviour now, and model it closer to Photoshop CS 2022, the old tutorials will break since the menu has now changed. I am afraid that without some versioning scheme, you might be painting yourself in a corner here.

**Comment by photopea** [comment]
@rcoenen Right-clicking the layer and choosing "copy layer styles" works both in Photoshop and Photopea, I have no plans to change that.

**Comment by rcoenen** [comment]
It's not the same - it's hidden in a submenu. See screenshots

So you might not want to consider this particular change but of you were to
change any other ones, you'd be running in similar problems without a
versioning scheme i believe

**Comment by photopea** [comment]
I have added the layer-style-copying actions to a context menu of layer styles.

Again, I never removed any option in Photopea, all old tutorials should still work. It makes no sense to make tutorials for a specific version of Photopea.
