### ISSUE TITLE
Invisible Photo Issue

### ISSUE THREAD

**Issue by JTF2004** [photopea/photopea#4842]
Hello, 

I want to remove the background for a picture. When I add fuzziness to the picture, and press Ctrl X it makes an invisible (or duplicate) version of it and I am unable to scale the original picture to the size I want. I am trying to make a shirt for a video game. 

![Screenshot (4)](https://user-images.githubusercontent.com/109787747/180386827-9eaddc4b-a6d5-4ac7-a542-08ac2c0bf30f.png)

Thank you, 
JTF2004 
7/22/2022

**Comment by photopea** [comment]
I think Photopea works according to the manual, but you just don't know how to use it.

You can read our manual at www.Photopea.com/learn, or ask people to help you at https://www.reddit.com/r/photopea
