### ISSUE TITLE
Feature Request: make the (Fixed Size) Rectangle Selection appear as soon as a left click is performed

### ISSUE THREAD

**Issue by xan2622** [photopea/photopea#4844]
When you use the **Rectangle Select tool (with Fixed Size)**, you have to slightly drag the cursor a few pixels away in order to make the rectangle selection appear. Is this behaviour on purpose? 
I tend to think that the rectangle selection should appear as soon as a left click is performed. This would be especially useful, while the canevas has been zoomed in a lot..

![firefox_LmDOWDiKLZ](https://user-images.githubusercontent.com/1732773/180484183-e150494b-460a-4507-9e5a-1bb2c53d53e0.gif)

Also, would it be possible to make that rectangle selection appear at the bottom right from the cursor? (currently, it appears at the top left)

**Comment by photopea** [comment]
That is on purpose. The user should be able to click with this tool to deselect. Sometimes, when clicking, the mouse can move a bit. Zoom in to select tiny areas.
