### ISSUE TITLE
Feature Request: Style Transfer (plugin?)

### ISSUE THREAD

**Issue by xan2622** [photopea/photopea#4845]
Hi.

I have discovered an interesting javascript code. Based on **TensorFlow**, it allows to copy the *art style* of an image and apply it to another image.
- https://codepen.io/Coderesting/pen/YzrOOzp
- https://www.tensorflow.org/js/
- https://magenta.tensorflow.org/blog/2018/12/20/style-transfer-js/

Perhaps, it could help create the *Style Transfer* filter that @elevory mentionned in this [message](https://github.com/photopea/photopea/issues/4808#issuecomment-1179612877)?

**Comment by photopea** [comment]
It looks interesting, but I think it is just a toy. I don't think anybody wants to use it to do actual work :/

**Comment by xan2622** [comment]
> It looks interesting, but I think it is just a toy. I don't think anybody wants to use it to do actual work :/

Ivan, don't be so skeptical. 😉 For the _Adaptive Palette_ plug-in, you were also [a bit dubitative](https://github.com/photopea/photopea/issues/3851), but take a look at its download statistics: it is now one of the most downloaded. I bet it will also be the case here.

Also, I think it's going to be more useful than most of the current filters: 

![130548](https://user-images.githubusercontent.com/1732773/180602495-7c7d60b8-06ee-4c1b-bbea-65ad1f097c52.png)

**Comment by photopea** [comment]
The thing is, that Photopea runs fully in your browser, it never uploads anything to the internet.

This demo: https://codepen.io/Coderesting/pen/YzrOOzp sends your image to some server. Everything is done on some server. It is hard to tell who is maintaining that server and for how long it will work.

Maybe @hxim could make a plugin for it. But in general, I would rather not add such features which require sending images to a server.

**Comment by xan2622** [comment]
Understood. Too bad. 
It would have been a nice feature to have.
