### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'B')

### ISSUE THREAD

**Issue by Spongeyboi** [photopea/photopea#4846]
Browser: Opera

Clicking on a menu bar button throws a TypeError. See below.
![image](https://user-images.githubusercontent.com/71215126/180498960-881c0ab0-6d87-42af-b330-e85d07aed737.png)
![image](https://user-images.githubusercontent.com/71215126/180499133-02430b60-38de-48cf-973b-657cb84a8717.png)

**Comment by photopea** [comment]
sorry, it is fixed now.
