### ISSUE TITLE
Drop down menu does not open

### ISSUE THREAD

**Issue by chinallc** [photopea/photopea#4848]
If I select any layer, the menu does work. If I don't select any layer (for example, I select an empty space) the menu doesn't work. The chrome console throws this error:

pp.js:11964 Uncaught TypeError: Cannot read properties of undefined (reading 'add')
    at Object.w (pp.js:11964:30)
    at ap.update (pp.js:9783:39)
    at ap.update (pp.js:9785:47)
    at ap.update (pp.js:9785:47)
    at eR.WD (pp.js:14200:85)

It's my first time reporting a bug and using github, so there may be missing information on each bug or more details. I'll be waiting for an answer in case someone needs more information to solve the error.

![DScreenshot 2022-07-22 205301](https://user-images.githubusercontent.com/109833583/180584097-f13dae3c-402a-4c08-a519-4ffdf44e6ca2.png)
![CScreenshot 2022-07-22 205247](https://user-images.githubusercontent.com/109833583/180584098-8af60938-8b06-4dca-8912-436a4f28f0d9.png)
![BScreenshot 2022-07-22 205229](https://user-images.githubusercontent.com/109833583/180584099-3dacec0b-52a7-4f58-b407-b599090bdcc0.png)
![AScreenshot 2022-07-22 205153](https://user-images.githubusercontent.com/109833583/180584100-e1e8980b-3e6a-4637-a995-c3f89170efa5.png)

**Comment by photopea** [comment]
sorry, it should be fixed now.
