### ISSUE TITLE
Shortcut for Undo / Redo

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4849]
In Photoshop, we can press <kbd>Ctrl + Alt + Z</kbd> to use Undo / Redo quickly. Is it possible to be implemented in Photopea?

**Comment by photopea** [comment]
For several decades, Ctrl+Alt+Z in Photoshop was to go backward, Ctrl+Shift+Z was to go forward. I think these are the shortcuts that users are used to, and we should not change them.

**Comment by photopea** [comment]
I have to close it because the person stopped responding.
