### ISSUE TITLE
Scrollbars

### ISSUE THREAD

**Issue by my2iu** [photopea/photopea#485]
Can you add scrollbars to images? When I'm zoomed in, there should be a scrollbar on the image to scroll around easily. I figured out that I could hold down the space bar to quickly switch to the hand tool, but that's not immediately obvious. It would be easier for people to learn if you just had some scrollbars.

**Comment by photopea** [comment]
Hi. Several people asked for scrollbars in the past. Basically, I think they would take too much space (10 - 20 pixels in each dimension). You can navigate with the Spacebar (Hand tool) or with a mouse wheel (or Ctrl + wheel for horizontal scroll).

With Alt+Wheel, you can zoom out, move mouse to another place and zoom in. This is usually faster than scrollbars / Hand tool.

**Comment by my2iu** [comment]
Power users can use keyboard shortcuts etc. For amateur users who need to occasionally edit photos (the types of people most likely to use Photopea), having scrollbars like every other photo editing program would make it easier to use. To make room, you can remove the toolbar middle bar with all the three letter titles.

**Comment by photopea** [comment]
I think that new users would use scrollbars maybe for an hour or two, until they discover a Hand tool, that can be switched with a Spacebar. After that, scrollbars would only take space ... users may be too lazy to hide them.

Navigation is also described here: https://www.photopea.com/learn/navigation

**Comment by istvan-ujjmeszaros** [comment]
The thing is that I had to Google a lot before found this ticket and were able to actually scroll the viewport. There should be some quick hint of basic navigation.

**Comment by kr37** [comment]
I agree, Photopea's methods are great, but nevertheless, for the first-timer, it's not at all clear, so I ended up here. I suggest just moving the hand tool up to the top of the tools, so it's one of the first ones people notice.

**Comment by Perksey** [comment]
Just landed here from Google.
