### ISSUE TITLE
Action panel: some actions are not working

### ISSUE THREAD

**Issue by Aly-Moataz-Shorosh** [photopea/photopea#4850]
As: creating a text, open an image, save,

there also no automate batch in photopea,

thanks a lot for you effort for this wonderful tool <3

**Comment by quantuminformation** [comment]
i am unable to export psd or save jpg in FF atm, lost some work too

**Comment by quantuminformation** [comment]
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/216566/180602118-730c7c62-b369-4fe2-a0fd-f180c3df3f97.png">

**Comment by photopea** [comment]
Could you tell me how can I reproduce it?

I opened Photopea.com in Firefox, crated an empty document, and saved it as a PSD, it worked.

**Comment by photopea** [comment]
I have to close it because the person stopped responding.

**Comment by quantuminformation** [comment]
i used another file and issue was gone, sorry for delay
