### ISSUE TITLE
i just loss so many hours

### ISSUE THREAD

**Issue by mattydood** [photopea/photopea#4852]
I spent like 2h making this picture and out of nowhere it so please refresh the page and ive loss alot of progress this has happened a couple times now idk why its happening

**Comment by xan2622** [comment]
Hi @mattydood. Haven't you seen a reminder advising you to save your project? 
 [Feature request: autosave](https://github.com/photopea/photopea/issues/760)

**Comment by photopea** [comment]
Are you using it on a phone? Browsers often kill Photopea, when it asks for too much RAM memory, and there is not enough RAM memory.

There is nothing we can do about it. Simply, get a better device (with more RAM), or work with smaller documents (smaller resolution, etc).
