### ISSUE TITLE
Triggering Google Translate

### ISSUE THREAD

**Issue by wordlesswind** [photopea/photopea#4854]
![image](https://user-images.githubusercontent.com/9050713/180644492-2b83bcba-207d-4254-851c-f17ee08ec600.png)

It's not a big deal, it's just that this little window pops up every time I open Photopea. Maybe the way Photopea loads translations is not to Google's taste :)

**Comment by photopea** [comment]
I think this is a behaviour of your browser which you set. We can not change it. Only you can change it in settings. Look into the manual of your browser.

**Comment by wordlesswind** [comment]
> I think this is a behaviour of your browser which you set. We can not change it. Only you can change it in settings. Look into the manual of your browser.

This is indeed browser behavior, but not relevant to me. I have a need to translate English (英语、英文) to Chinese (中文) using Google Translate. 

Even though Photopea provides a Simplified Chinese translation, apparently Google Chrome still recognizes it as English. So it will always prompt unless the "Ask to translate English" option is turned off.

In any case, it's up to you or the Chrome team whether you want to solve this trivial problem. But you don't want to fix it, so...that's all.

**Comment by photopea** [comment]
@nothingshiru do you have the same problem?

**Comment by photopea** [comment]
@nothingshiru do you have the same problem?

**Comment by wordlesswind** [comment]
> ~I don't have this problem on Chrome for Windows.~
> 
> I have this problem after I pressed Ctrl + F5 to refresh Photopea. And the popup never show up after I refreshed twice.

I installed Photopea as a Chrome app, so maybe that has something to do with that too. Currently I have closed the tip as per https://github.com/photopea/photopea/issues/4854#issuecomment-1193376528, thanks.
