### ISSUE TITLE
Bug: Document created for "svg" automatically

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4855]
To reproduce
1. Copy `<svg` into clipboard
2. Open the New Project dialog

A "image.psd" will be created for that "svg" when you do step 2.

**Comment by photopea** [comment]
I can not reproduce it. Opening a New Project dialog does not create a new file automatically :( only pasting the "<svg" into Photopea does (Ctrl+V or Edit - Paste).

**Comment by photopea** [comment]
I can not reproduce it. What browser and OS are you using?

**Comment by photopea** [comment]
I guess it is a bug in Edge. could you report it to them?

**Comment by photopea** [comment]
It should be fixed now.
