### ISSUE TITLE
Проблема

### ISSUE THREAD

**Issue by Worker14** [photopea/photopea#4858]
Добавьте - в - пункт - "Файл" - пункт - "Сохранить как" - и - вообще - 

лучшее - враг - хорошего !!! - я - всем - говорю - что касается - работы - чего-то оптимального - каких-то оптимальных разработок - то - если - вы что-то делаете - то - постарайтесь - если есть - что-то оптимальное - всё это скопировать ! - ну - и - потом - что-то делайте сами !!! - 

так - и - в случае - с - photopea - я - точно не знаю - но - вроде - лидер рынка - в - этой области - приложение - Adobe Photoshop 2022 - я - около - 2-ух лет пользовался - этой программой - по - платной подписке - во всём - правда - не разобрался - но - вроде - пойдёт ! - короче - копируйте - их наработки - и - что-то делайте сами !!! - мысли - это - дела !!! - дела - это - мысли !!! - думай !!!

![Думай_!!!_а _п _](https://user-images.githubusercontent.com/99514167/180900816-b4e918f8-84d4-402a-82de-b42d0a275aeb.png)
![оптимальное_мышление_2_](https://user-images.githubusercontent.com/99514167/180900887-8859d149-f6de-410e-8873-765ac5e93f8c.png)

**Comment by Worker14** [comment]
🤑

**Comment by photopea** [comment]
There is File - Export As. What exactly do you need?

**Comment by photopea** [comment]
I have to close it because the person stopped responding.
