### ISSUE TITLE
resizing layer from drag'n'dropped photos pixilates the layer

### ISSUE THREAD

**Issue by monthly-marko** [photopea/photopea#4859]
steps to reproduce
1) start new project
2) drag and drop the image from your computer (ideally photography)
3) scale the image to half of it's size
result: very much pixilated image (even after export)
expected result: image with the original (apparent) resolution

**Comment by photopea** [comment]
I think that is the correct behaviour.

Could you prove, that there is a software in the world, which can "do it better"? For me to see, that it is possible to do it better.

**Comment by monthly-marko** [comment]
hi, thanks for writing back. pixlr editor. i did the same thing there to compare and was happy with the result (once i exported the result as png). i hope my description was not misleading in some way

**Comment by photopea** [comment]
Could you share two images of the same thing from Pixlr and Photopea, so that we can see that Pixlr is better?

**Comment by photopea** [comment]
In my experience, placing one image into another always gives the identical result, in Pixlr and Photopea. That is why I am asking, as it sounds very suspicious.

**Comment by photopea** [comment]
I have to close it because the person stopped responding.
