### ISSUE TITLE
Cropping

### ISSUE THREAD

**Issue by my2iu** [photopea/photopea#486]
The crop tool currently requires me to choose the point in the upper-left corner first and then set the lower-right corner. I often do my cropping from the lower-left or other corners depending on what works best for my image, so this restriction seems unnecessarily annoying.

Also, it's fine that the crop tool can be used to make an image bigger, but I like how Photoshop restricts the bounds of the crop tool to be within the bounds of the image. That way, I can quickly swipe my mouse and crop off the right of a photo while keeping the left edge the same. Can you make that the default behavior or make a button so that I can toggle the behavior?

**Comment by my2iu** [comment]
Actually, I'm now sort of confused about what exactly the crop tool does because even after cropping, the old parts of the image that were cropped out still seem to exist but are just hidden. And I can maybe crop at the subpixel level? If I make a rotated crop or crop at the subpixel level, does that resample the image or is my original data still there? Maybe you should change the name of the tool to something other than "crop" because it doesn't behave the way normal crop tools behave. Maybe call it mask tool or something?

**Comment by photopea** [comment]
The rotation / resampling should work similar to Photoshop.

Unless you rotate the cropping rectangle, there is no resampling. Cropping does not remove content from layers, it just changes the "viewing window", similar to Canvas Size.

**Comment by my2iu** [comment]
I think the crop rectangle should snap to pixel boundaries then and not let you crop half a pixel.

**Comment by photopea** [comment]
The Crop rectangle does snap to image boundaries. When there is no rotation, it will be "rounded" to the whole pixels after you confirm it.

**Comment by photopea** [comment]
But I will add the option of drawing a rectangle in "any direction".

**Comment by photopea** [comment]
It has been fixed - you can draw a cropping rectangle in any direction.
