### ISSUE TITLE
Page Load Error!

### ISSUE THREAD

**Issue by alizoyan** [photopea/photopea#4861]
This
![image](https://user-images.githubusercontent.com/104099819/181046776-8b0e6001-f08f-486b-9077-28d9da0fb453.png)
 error appears on opera a lot and other browsers too!

**Comment by alizoyan** [comment]
The page never loads even after several reloads or browser/PC restarts even on fast network connection!

**Comment by alizoyan** [comment]
In the ss above u can see that shield is crossed its because I have disabled all blocking for Photopea but it still bugs!

**Comment by alizoyan** [comment]
This is how homepage loads:
![image](https://user-images.githubusercontent.com/104099819/181048084-5d4e2da0-47ae-4c6c-a9bd-608ae504f3f6.png)

**Comment by photopea** [comment]
I think you are using a web browser from 2008. Could you switch to a web browser, that is no more than 10 years old, 2012+?

**Comment by alizoyan** [comment]
Its the latest 2022 feb updated version of my browser
pls check and tell if your cdn or server is missing some things or is far from my location: Pakistan

**Comment by alizoyan** [comment]
It was running fine for months but started bugging a week ago on the same browser

**Comment by photopea** [comment]
But what web browser is it? Do you use any extensions? 

Try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by alizoyan** [comment]
I use Opera GX Browser and i have no extension that effects photopea or any website also all features for phtopea like sd block and tracker block are disabled for photopea

**Comment by alizoyan** [comment]
Te link doesnt help me for anything!

**Comment by alizoyan** [comment]
lemme try in incognito cuz sometimes it bugs also vpn is not helping too also ima clear cookie and try if it helps

**Comment by alizoyan** [comment]
It works in incognito but is very slow, so slow that i cant use it and i have fast network so can u help me with that also is there a way i can use it normal tab?

**Comment by photopea** [comment]
If it works differently in Incongito, it means you are using browser extensions. Could you show us a screenshot of about://extensions?

**Comment by alizoyan** [comment]
![image](https://user-images.githubusercontent.com/104099819/181309480-ae386163-79d1-4fc7-8aa5-74f5803409ce.png)

**Comment by photopea** [comment]
One of your extensions is breaking Photopea.

If you don't know which one, disable them all. I am sure Photopea will work perfectly after that.

**Comment by photopea** [comment]
You wrote "I use Opera GX Browser and i have no extension" which is a lie. Next time, do not lie to us, if you want us to help you.
