### ISSUE TITLE
Adblocking detection backfires on Chromium v103.0.5060.134 on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by yikuansun** [photopea/photopea#4862]
Even when I disable all extensions, Photopea replaces the normal ad section with the "ad blocking detected" game ads. Ads work fine on other sites I visit, so I attribute the problem to a flawed adblocking detection algorithm. I'll try to look into it more, but I'd suggest not removing the actual ads section when ad blocking is detected, just in case the detection may be inaccurate. One way to do this is to use fixed/absolute positioning to position the game ads *over* the normal ads section, rather than replacing it, if that is allowed.

**Comment by photopea** [comment]
We consider ads to be blocked when certain domains are blocked (photopea can not access them). Maybe your internet provider or your government is blocking certain domains in your case. Or you have a firewall or something.

**Comment by yikuansun** [comment]
I see. That does make sense.

May I ask what provider you are using for your ads? (Google, Facebook etc.)

**Comment by photopea** [comment]
It is a company from Bulgaria.

Could you try these steps? https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

If it is not in your computer, could you connect through a different network?

**Comment by yikuansun** [comment]
Alright, thanks for letting me know.

I have tried these things. I'm sorry, but I don't think I can get ads working.

**Comment by photopea** [comment]
Where do you live?

**Comment by yikuansun** [comment]
I'm currently in the States

**Comment by photopea** [comment]
Is it possible that your school or your employer is blocking ads? Did you try other internet providers?

**Comment by yikuansun** [comment]
I suppose it might be a network problem. I don't think I can switch providers at the moment.
