### ISSUE TITLE
Request for android 

### ISSUE THREAD

**Issue by Saikatsaha1996** [photopea/photopea#4863]
I downloaded photopea android application v1.0 from 3rd party sites.. really just awesome application in android..
Working fine.. but can't save anything to internal storage.. app crashed.. 

It is possible to add support official for android application..

Because when i am useing web browser.. screen is short , i can't use full screen.. so can it possible to add android application.. it really very professional application.. 
![Screenshot_2022-07-27-17-01-16-934_com android chrome](https://user-images.githubusercontent.com/72664192/181236754-1a5f219e-5929-49cc-ad33-ea3ac760bb69.jpg)

**Comment by photopea** [comment]
we do not have any android application, you probably downloaded a virus.

In Photopea, you can press More - Install Photopea.

**Comment by Saikatsaha1996** [comment]
> we do not have any android application, you probably downloaded a virus.
> 
> In Photopea, you can press More - Install Photopea.

Thank you for your response

**Comment by Saikatsaha1996** [comment]
> we do not have any android application, you probably downloaded a virus.
> 
> In Photopea, you can press More - Install Photopea.

@photopea nice working very fine thank you ;)
