### ISSUE TITLE
Layer is not editable

### ISSUE THREAD

**Issue by summer-cook** [photopea/photopea#4864]
I am trying to edit an eps file that I imported. I would like to just swap out the colors. After importing, I am able to see all the individual shapes inside the layer, and I can manually change the colors of a single shape, but I haven't been able to use the "Replace Colors" tool. These are the steps I am using

1. Select the layer (layer 1)
<img width="1370" alt="Screen Shot 2022-07-27 at 9 33 48 AM" src="https://user-images.githubusercontent.com/73361970/181302320-cf44c330-4979-4e74-8d6e-a4875afacd0b.png">

2. Image -> Adjustments -> Replace Color
<img width="682" alt="Screen Shot 2022-07-27 at 9 38 00 AM" src="https://user-images.githubusercontent.com/73361970/181302127-19ea1a06-a387-4dca-9891-5ecc9f350425.png">

I always get "The layer is not editable."

How can I swap out the colors in a vector image without having to do it shape by shape? It seems like there should be a way to select all shapes of a specific color and then replace colors.

**Comment by summer-cook** [comment]
I also tried switching to "vector mode" with no luck. Still get the error message "The layer is not editable"

How can I make the layer editable?

**Comment by photopea** [comment]
The "replace color" is for raster graphics, e.g. photographs, and it changes the pixels of one layer.

If you dont need vector graphics, merge everything using Layer - Flatten Image. You can use Replace Color then.

All these things work the same as in Adobe Photoshop. So I really recommend spending several hours learning Photopea or Photoshop, before using it. You can read www.Photopea.com/learn

**Comment by photopea** [comment]
Ask for help at https://www.reddit.com/r/photopea , this is a place for reporting bugs.
