### ISSUE TITLE
Patch and healing tool want to change lightness and doesn't fully replace the original 

### ISSUE THREAD

**Issue by softyoda** [photopea/photopea#4865]
An option in photoshop allow to replace (with smooth edge still) but not change the luminance / brightness once healed/patched. I didn't find that option in photopea.

**Comment by photopea** [comment]
Where exactly is such option in Adobe Photoshop? I have never heard of it.

**Comment by softyoda** [comment]
![example](https://user-images.githubusercontent.com/13988751/181450563-f349c91c-1283-4731-adcb-3576264aed81.gif)
Here is a gif example showing the excepted behavior.

**Comment by photopea** [comment]
I think that is how it should work. If you are healing the area, and there is a blue color on one side, and brown on another, the new content must be "something in between.  How exactly should Photopea connect a face to a sky in a "nice manner"?

I think you should use the Clone Stamp for what you are doing.

**Comment by MichalSZZ** [comment]
@Photopea on second part of his GIF there is showed (new) feature in Photoshop that makes it in different way. I didn't even know about it. I have to try it.

**Comment by softyoda** [comment]
Yes, the second part of the gif show how photoshop act with "replace" feature (it doesn't blend the brown part and that is easier to remove things)

**Comment by photopea** [comment]
Oh, I did not notice there is a photoshop part in a GIF. It is not a video, so I thought it has finished.

I still do not understand, what is the difference between the Healing Brush tool with "Replace", and the Clone Stamp?

**Comment by softyoda** [comment]
They allow to only paint the cloud without having a giant brown paint.

**Comment by photopea** [comment]
@softyoda but have you tried the Clone Stamp? Are you sure you know what it is?
