### ISSUE TITLE
Save as psd gets stuck

### ISSUE THREAD

**Issue by dvdnhm** [photopea/photopea#4866]
If I open an .ai file and use any item/layer from that file, I cannot save the work as .psd, it gets stuck.

The console has this error:
pp.js:4132 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at S.wJ (pp.js:4132:70)
    at aF.U9 (pp.js:3679:45)
    at aF.$n (pp.js:3659:63)
    at i_.Ei (pp.js:3778:6)
    at ci.aeX (pp.js:3857:42)
    at ci.Z4 (pp.js:3844:102)
    at jX.ayR (pp.js:4034:57)
    at jX.atj (pp.js:4032:97)
    at jX.a97 (pp.js:4027:49)
    at jX.Z4 (pp.js:4008:25) 
![image](https://user-images.githubusercontent.com/6667615/181521415-7abf6891-5946-422f-a024-86cb5484282b.png)

**Comment by photopea** [comment]
I tried to open several AI files in Photopea, and I was able to save them as PSD.

What is "use any item from that file"? Could you share your AI file with us, and tell me what should I do to make the problem happen?

**Comment by dvdnhm** [comment]
I received an AI file from our logo designer, and I was opening it with photopea. Save fails on two conditions:
- trying to save the .ai file as .psd
- after copying any element in .ai file to a new file .psd file in photopea

I will send the .ai file over a Twitter DM

thanks

**Comment by photopea** [comment]
I opened your file in Photopea, I can save it as a PSD.

I copied a layer from your AI file into a new, empty document. Both documents can still be saved as a PSD :(

Are you sure you can reproduce your problem every time you try? If yes, how?

**Comment by dvdnhm** [comment]
If you have time we can do a Google meet and I can show how I managed it 😄

**Comment by photopea** [comment]
Could you record a short video with what you do?

**Comment by dvdnhm** [comment]
I cannot replicate the problem, I will send a video if happens again.

**Comment by photopea** [comment]
ok
