### ISSUE TITLE
Vertical Type Tool isn't working well

### ISSUE THREAD

**Issue by Sirhaf** [photopea/photopea#4868]
i think you may see the problem right on the picture below
<img width="120" alt="image" src="https://user-images.githubusercontent.com/110225850/181717151-1941bcc7-8a30-4763-96b6-03561343e44e.png">
So, I want to write "Haaaaa..." vertically. but the application can't understand what i mean. i've try to press enter every alphabet there but it looks not good. Can the developer fix this? Oh then, the write marker isn't looks well too.

**Comment by photopea** [comment]
How do you do it? When I use the vertical type tool, each letter is on a separate line.

**Comment by photopea** [comment]
I have to close it because of lack of details.
