### ISSUE TITLE
cannot open local files

### ISSUE THREAD

**Issue by khamelion81** [photopea/photopea#4869]
almost consistently cannot open local files.  on rare occasion i can, copy/paste does not work

**Comment by laura-scognamiglio** [comment]
Same for me i can't open local files, have a nice day

**Comment by laura-scognamiglio** [comment]
the solution is to drag & drop the pic from your fild

**Comment by photopea** [comment]
Do you mean using File - Open in Photopea? Is there any error message? What device are you using? a phone, a tablet, mac, windows ?

**Comment by laura-scognamiglio** [comment]
Yes It's File - Open & place and also  File - Open , there is no error message and i'm using a mac m1 with the macOS Monterey v12.4

**Comment by photopea** [comment]
could you try these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details. It was probably caused by browser extensions.

**Comment by laura-scognamiglio** [comment]
Thank you it's was because a maj apple or my browser, i've saw that oppening files was a problem with several website so it's not because of Photopea, have a nice day!
