### ISSUE TITLE
Make Photopea Self Hosted?

### ISSUE THREAD

**Issue by ItsNoted** [photopea/photopea#4870]
This is an amazing project! is there any way this can be containerized using docker so we can self host it on our own servers?

**Comment by MarseyLivesMatter** [comment]
Agreed! It's been a life-saver and the convenience means that I only need to carry a small Chromebook around, but it would be perfect if I could use it offline too.

**Comment by StanDaMan0505** [comment]
I love photopea for a long time. Would love it even more if i could run it locally. :-*

**Comment by photopea** [comment]
Photopea runs locally already (no data is sent to any server while you use it). Once you open www.Photopea.com , you can disconnect from the internet and still use it.

If you open www.Photopea.com at least once, it is cached in your computer forever, and you can open it in your browser even when you are offline.

We offer a self-hosted version here: https://www.photopea.com/api/accounts#self-hosted

**Comment by ItsNoted** [comment]
> We offer a self-hosted version here: https://www.photopea.com/api/accounts#self-hosted

A self-Hosted version costs between $500 and $2000 per month. You should pay for a whole year (12 months) in advance, and you will get resources, that will work for exactly one year. After each year, you can decide, if you want to pay for a next year (and get new resources), or terminate it. You can get two updates during a year for free (at any time), each next update costs $300.

Yeah, no thanks.

**Comment by jamiew0w** [comment]
> > We offer a self-hosted version here: https://www.photopea.com/api/accounts#self-hosted
> 
> > A self-Hosted version costs between $500 and $2000 per month. You should pay for a whole year (12 months) in advance, and you will get resources, that will work for exactly one year. After each year, you can decide, if you want to pay for a next year (and get new resources), or terminate it. You can get two updates during a year for free (at any time), each next update costs $300.
> 
> Yeah, no thanks. Even if this project is your way to make a living, you can still charge much lower price and make a decent amount. And probably get a lot more customers too. This is ridiculous. Is your target client ballers only? Corporate companies? because this is not priced at consumer levels.

Your attitude is horrific. I even reached out and gave you context beforehand but it's clear you didn't read it. Also, you're entitlement is off the charts. You are not their target audience for self hosting. 
Go ask Adobe to open source photoshop, then offer them a much lower price and see how that works out for you.

Also, who thumbs up their own comments?

Seeing as you position yourself as some kind of "open source curator", this is a very ugly side of you to show publicly. You should be ashamed.

**Comment by ItsNoted** [comment]
> > > We offer a self-hosted version here: https://www.photopea.com/api/accounts#self-hosted
> > 
> > 
> > > A self-Hosted version costs between $500 and $2000 per month. You should pay for a whole year (12 months) in advance, and you will get resources, that will work for exactly one year. After each year, you can decide, if you want to pay for a next year (and get new resources), or terminate it. You can get two updates during a year for free (at any time), each next update costs $300.
> > 
> > 
> > Yeah, no thanks. Even if this project is your way to make a living, you can still charge much lower price and make a decent amount. And probably get a lot more customers too. This is ridiculous. Is your target client ballers only? Corporate companies? because this is not priced at consumer levels.
> 
> Your attitude is horrific. I even reached out and gave you context beforehand but it's clear you didn't read it. Also, your entitlement is off the charts. You are not their target audience for self hosting. Go ask Adobe to open source photoshop, then offer them a much lower price and see how that works out for you.
> 
> Also, who thumbs up their own comments?
> 
> Seeing as you position yourself as some kind of "open source curator", this is a very ugly side of you to show publicly. You should be ashamed.

You are so right. What was I thinking?!!

**Comment by photopea** [comment]
@jamiew0w thanks for defending me!

As said earlier, I want to provide Photopea only at www.Photopea.com . It already works offline thanks to the "eternal caching". 

There are many clients paying for a self-hosted Photopea, many of them pay much more than $2000 a month. Since anyone with an "independent copy" of Photopea can publish it on their website, with their own ads (to make money) and compete with our version (or provide it with no ads and leave us without any income), we would rather avoid that.

**Comment by ItsNoted** [comment]
I found a standalone desktop version! No need to connect to the internet or a web interface. It's awesome. Great program thank you!
