### ISSUE TITLE
RAW photopea : image veiw going black when you move any sliders

### ISSUE THREAD

**Issue by Toasty485** [photopea/photopea#4871]
![image](https://user-images.githubusercontent.com/110294215/181917425-556e139e-fe1e-4654-8c3b-fe418ce89df1.png)
 This is what it look like when you move any of the sliders. When you click open , the image appears with the adjustments

**Comment by photopea** [comment]
Could you send me your file to support@photopea.com ?

**Comment by Toasty485** [comment]
What do you mean file? It's any raw file I try to upload if that helps. I
won't be able to give an example of a file until Tuesday as I'm away
currently. It the raw files produced from a Nikon d40 so NEF I believe.

**Comment by photopea** [comment]
I think the same problem happens here, so let's discuss it there: https://github.com/photopea/photopea/issues/4875
