### ISSUE TITLE
Grids not dragging?

### ISSUE THREAD

**Issue by humankaleidoscope** [photopea/photopea#4872]
I tried watching tutorials and reading the user guide on the Photopea website but I just can't figure this out. Supposedly, you should be able to click and drag guides from the rulers. I have "extra" enabled, and view rulers, but when I click on it I can't "drag" the guides. They just automatically pop out underneath the ruler, but I cannot "drag" them, nor can I reposition them, even after trying to lock my layers in place so that (hopefully) the program realizes the only thing I could possibly be trying to select with the Move tool IS the guide.

Does anyone know how to fix this? Is it a bug? I'm trying to create a grid pattern on which to accurately align text.

**Comment by photopea** [comment]
I just tried it and dragging guides works.

Could you describe, what should I do after opening www.Photopea.com to see guides not draggable? Or record a video of what you do after opening Photopea. Is it related to one specific file that you open from your computer in Photopea, for which it does not work, or you tried it on several different files?

**Comment by photopea** [comment]
I have to close it because of the lack of details.

**Comment by kvabakoma** [comment]
Not exactly... but I'm close to it. 

What I've been doing was using the pen tool in path mode to make a selection, cut it from a layer and paste it to a new layer.

This behaviour happens with some combination of the pen tool usage. Trying to add anchor points, or may be adding an anchor point and then, with a created anchor point, attempt to create a guide. Something like this.
