### ISSUE TITLE
ad blocker disabled but still getting notification.

### ISSUE THREAD

**Issue by TidusWulf** [photopea/photopea#4874]
I disabled ublock origin for photopea.com, but photopea still thinks I'm blocking ads. Could be caused by Privacy Badget or Disconnect? I'm using firefox.

**Comment by photopea** [comment]
I don't know which one of the software on your computer is blocking Photopea :(

Try this maybe: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by TidusWulf** [comment]
Alright. I'll mess around with my other extensions and see if I can figure
it out.

**Comment by photopea** [comment]
Hope it helped.
