### ISSUE TITLE
No image preview when sharing photopea.com on social media

### ISSUE THREAD

**Issue by davestewart** [photopea/photopea#4876]
There are often times I want to promote PhotoPea on my Twitter profile, but [when I share the link](https://twitter.com/dave_stewart/status/1553761848364769282) there's no preview:

![image](https://user-images.githubusercontent.com/132681/182033291-4ffebf98-3bc6-48b0-b478-11ee0fd8c1f2.png)

I think this is a shame as it's such a great product and a decent preview image would go a way to showing off Photopea and demonstrating to potential users the attention to detail we really enjoy in the product.

You can use something like [Meta Tags](https://metatags.io/) to create the correct cross-vendor tags and [Twitter Card Validator](https://cards-dev.twitter.com/validator) to check what they look like to users.

**Comment by photopea** [comment]
I believe we have several meta tags likning to image previews of Photopea.

So I think it is a bug in Twitter. Why dont you report it to Twitter?

**Comment by davestewart** [comment]
Perhaps formats have changed since you first set up your tags, as the ones on your site are not compatible.

Here it is in the Facebook sharing debugger:

![image](https://user-images.githubusercontent.com/132681/182141139-e9e3e885-a51d-4c80-a172-45d1b8d6b9bb.png)

Here it is in the Twitter card validator:

![image](https://user-images.githubusercontent.com/132681/182141218-7739ded3-7ef2-4c90-983f-947c9f1c3bac.png)

Here it is in the Linked in post inspector:

![image](https://user-images.githubusercontent.com/132681/182141362-5d8aa83c-2cbc-45b2-93ed-2197e9a80c52.png)

If you want to be compatible with the main platforms, here are the tags you should use:

```html
<!-- Primary Meta Tags -->
<title>Photopea: advanced photo editor</title>
<meta name="title" content="Photopea: advanced photo editor">
<meta name="description" content="Photopea Online Photo Editor lets you edit photos, apply effects, filters, add text, crop or resize pictures. Do Online Photo Editing in your browser for free!">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://www.photopea.com/">
<meta property="og:title" content="Photopea: advanced photo editor">
<meta property="og:description" content="Photopea Online Photo Editor lets you edit photos, apply effects, filters, add text, crop or resize pictures. Do Online Photo Editing in your browser for free!">
<meta property="og:image" content="https://www.photopea.com/promo/screens/scr1.png">

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://www.photopea.com/">
<meta property="twitter:title" content="Photopea: advanced photo editor">
<meta property="twitter:description" content="Photopea Online Photo Editor lets you edit photos, apply effects, filters, add text, crop or resize pictures. Do Online Photo Editing in your browser for free!">
<meta property="twitter:image" content="https://www.photopea.com/promo/screens/scr1.png">
```

If you want to provide correct image sizes, they are unfortunately [different between platforms](https://buffer.com/library/ideal-image-sizes-social-media-posts/).

- Facebook: 1200 x 630
- Twitter: 1200 x 675
- Linked In: 1200 x 628

I hope that's helpful.

**Comment by photopea** [comment]
We already have this in Photopea:

    <meta name="thumbnail" content="https://www.photopea.com/promo/screens/scr5.png" />

This should be enough for social networks to find an "image of our website". We are not going to promote any specific social networks in our source code, or let private companies dictate what our source code should look like.

**Comment by davestewart** [comment]
Stick it to the man 🖕 eh!
