### ISSUE TITLE
Redefine edge not working 

### ISSUE THREAD

**Issue by JNocillo** [photopea/photopea#4877]
Basically, it starts ok but then when i click on the original image, it disappears alongside the preview. It also reappears randomly after cliking again.
![Captura de pantalla 2022-08-01 022453](https://user-images.githubusercontent.com/110360607/182051847-307c6760-4eeb-410f-92db-b9281f91ae03.png)
![Captura de pantalla 2022-08-01 022546](https://user-images.githubusercontent.com/110360607/182051896-4d58ac90-3f50-457c-9d9e-3d18f5c0384e.png)

**Comment by photopea** [comment]
We are discussing it here: https://github.com/photopea/photopea/issues/4875
