### ISSUE TITLE
I can't use copy - paste

### ISSUE THREAD

**Issue by chinallc** [photopea/photopea#4878]
I just try and it doesn't work. I select a layer, copy (CRTL + C) and when I want to paste it nothing happens. I also tried using the "copy" and "paste" buttons from the menu in the "edit" tab. In the console it seems that there are no errors. I've already reloaded the page and tried several files. Although I have noticed that bugs sometimes occur, I report them and you fix them quickly. Thanks.
![Screenshot 2022-07-31 215445](https://user-images.githubusercontent.com/109833583/182057660-e9fe666d-7623-4672-97c3-0b8e6ec95ca2.png)

**Comment by alistairsinclair** [comment]
Same for me I can't copy-paste things, hope they will fix it soon

**Comment by photopea** [comment]
it should be fixed now.
