### ISSUE TITLE
Can't open files from computer

### ISSUE THREAD

**Issue by shirophine** [photopea/photopea#488]
i have chromebook plus and when i want to open file from the computer it wont work. only loading message and that's it.

https://i.imgur.com/5ChFlCD.png

**Comment by photopea** [comment]
Hi, can you send us a file that you are trying to open? Please, send it to support@photopea.com , or attach it here.

**Comment by shirophine** [comment]
attached is the file, is it because the file larger than 500 kb? i keep thinking it's because the file's size.
    On Thursday, February 22, 2018, 9:42:22 AM PST, Photopea <notifications@github.com> wrote:  
 
 
Hi, can you send us a file that you are trying to open? Please, send it to support@photopea.com , or attach it here.

**Comment by photopea** [comment]
Hi, I am sorry, I did not receive a file :( can you write a separate email to support@photopea.com ?

**Comment by photopea** [comment]
Your PNG file seems to be damaged. But other image viewers can open it.

I fixed the issue. Now, you can open it in Photopea, too.
