### ISSUE TITLE
Photopea margin space

### ISSUE THREAD

**Issue by mgrisham8423** [photopea/photopea#4880]
I printed photopea from two different computers because one was my work computer and the other my home computer. My work computer prints the margins correctly well I should say image size but everything is exactly the same on my home computer and the image puts too much white space …it is not taking my image size. I compared everything and they are identical but I must be missing something

**Comment by photopea** [comment]
How do you print stuff? You should export a PDF file first. The same PDF file should be printed in the same way on all printers. So if two different printers print the same PDF file differently, it is a problem in printers, not in Photopea. Am I missing something?

**Comment by mgrisham8423** [comment]
Thank you so much ..I agree it has to do with my printer. Do you think it could be I need to download a driver?

**Comment by photopea** [comment]
I really dont know. But it is a task of your printer to print the PDF file exactly as it is.
