### ISSUE TITLE
Freezing on save

### ISSUE THREAD

**Issue by gustavolendimuth** [photopea/photopea#4881]
It's freezing when I try to save after a message remembering to save an open file.
![image](https://user-images.githubusercontent.com/37625398/182455622-0f4af1ec-d2ee-4d15-980b-bb95539ef57f.png)

**Comment by photopea** [comment]
Could you tell me what should I do to make Photopea freeze myself?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
