### ISSUE TITLE
Shift shortcut for even scaling not working on macos in Chrome Apps

### ISSUE THREAD

**Issue by ezgranet** [photopea/photopea#4882]
Until recently, holding down shift when scale-transforming an object allowed for uniform scaling as a shortcut (as it does on desktop applications) but recently, when I try to do this, it completely doesn't work and thus the object scales unevenly.  Could this shortcut be restored? (Running Chrome 103.0.5060.134 on a mac running macOS 12.5)

**Comment by photopea** [comment]
Hi! Please, read this! :) https://www.photopea.com/tuts/new-free-transform/
