### ISSUE TITLE
When I load a specific pdf the text gets misaligned

### ISSUE THREAD

**Issue by Tylerwong2** [photopea/photopea#4886]
<img width="301" alt="Screen Shot 2022-08-04 at 2 13 29 PM" src="https://user-images.githubusercontent.com/100496279/182921622-97ae0b71-b6c4-4032-bb2c-aa6db16819ff.png">

**Comment by photopea** [comment]
I think your PDF needs a font, that is not available in our font database. Our default font makes your text wider.

Can you load the necessary font using File - Open?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
