### ISSUE TITLE
Actions - When applying filter it does not apply

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4888]
At least this is the only filter i have seen this happen, but i cannot be sure it is the only one.

When i apply the smart sharpen through actions, it does not actually apply. I can't even change the settings afterwards.

Here is the PSD: 
https://www.photopea.com/#iZH-MSCq5

Here is a video:
[Screen recording 2022-08-05 00.21.17.webm](https://user-images.githubusercontent.com/11801254/183001272-f39a0ce2-a17b-4fa0-9726-48e7e4b20deb.webm)

**Comment by photopea** [comment]
it should be fixed now.
