### ISSUE TITLE
Can't publish a transparent PNG file when exported 1x format?

### ISSUE THREAD

**Issue by surajitsur26** [photopea/photopea#4890]
Can't publish a transparent PNG file when exported 1x format? 'Scale for exported files' is not appearing from last 4-5 [days.]

![Untitled-1](https://user-images.githubusercontent.com/110711256/183235853-e5cf426f-cb31-4124-9864-f764c03c7cec.jpg)

**Comment by photopea** [comment]
Hey, I did not know anybody was using this feature. I have made a single download button with all original options.

**Comment by surajitsur26** [comment]
Thank you very much.
