### ISSUE TITLE
Text doesn't work

### ISSUE THREAD

**Issue by Bella565** [photopea/photopea#4891]
Hi.

When using the text option, I'm typing and nothing is happening, but when I tick to say okay, the layer on the right shows what I've typed, but there is nothing in the design I'm working on.

I use Photopea all the time so I know I'm doing it right, but no matter what colour or font I use, it's just not working.

Can someone have a look and let me know if I am doing something wrong?

Thanks.

**Comment by photopea** [comment]
I think you have installed browser extensions, which break Photopea.

Try this, let me know if it helped: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/
