### ISSUE TITLE
Better DDS Compression Request

### ISSUE THREAD

**Issue by ReeceBar** [photopea/photopea#4892]
I don't entirely know what compression method Photopea uses, but the tool Cathedral Assets Optimizer at Nexusmods uses BC7 compression and produces less compression artifacts than Photopea. Both files came to be 5.33MB in file size. Maybe Photopea can switch to also use BC7 compression for DDS files?
![CAS PPea](https://user-images.githubusercontent.com/42558495/183269320-b047e296-13eb-4d90-a5ed-da9d3bfe01bb.png)
[GMonk CAS PPea Compare.zip](https://github.com/photopea/photopea/files/9275929/GMonk.CAS.PPea.Compare.zip)

**Comment by ReeceBar** [comment]
BTW CAS is only for DDS files, Bethesda games only uses that type of file so I can't just switch to a different file type like png.

**Comment by photopea** [comment]
We use BC1 and BC3 compression during the DDS export.

BC7 is very complex. The BC7 compressor would be much slower, and I don't know if there are enough people interested in it.

Also, if you have no transparency, BC3 files are 2x smaller than BC7 files.

**Comment by photopea** [comment]
Someone asked about it here: https://github.com/photopea/photopea/issues/4785

**Comment by ReeceBar** [comment]
"Our goal is to create the most advanced and affordable photo editor." I think apart of that would be BC7 compression so people using DDS files can have quality over quantity/saving some time. You could allow us to choose the compression method if it's too slow for people. Anyway, I hope I've convinced you to try to make an option for BC7 compression, even if you don't thanks for at least considering it.

**Comment by ReeceBar** [comment]
"Our goal is to create the most advanced and affordable photo editor." I think apart of that would be BC7 compression so people using DDS files can have quality over quantity/saving some time. You could allow us to choose the compression method if it's too slow for people. Anyway, I hope I've convinced you to try to make an option for BC7 compression, even if you don't thanks for at least considering it.

**Comment by ReeceBar** [comment]
*I accidently hit closed, sorry if that messes anything up here

**Comment by photopea** [comment]
I have improved our DDS compression. There still are some artifacts, but it should look much better than before.

**Comment by ReeceBar** [comment]
Still though, wouldn't it be best, quality wise to add a BC7 compression option? I guess it's no biggie, I can just use CAS to compress DDS files, and just turn off compression of DDS files for when editing them in PhotoPea.
 Sorry but it seems like the artifacts are worse now, it has more pixelated blue stuff around the patch
![PPeaNew](https://user-images.githubusercontent.com/42558495/183496373-6d4480a2-09b7-4486-a7a5-de2ea1a3af52.PNG)
[GMonkOutfit_d Photopea New.zip](https://github.com/photopea/photopea/files/9284433/GMonkOutfit_d.Photopea.New.zip)

**Comment by photopea** [comment]
Are you opening BC7 DXF files in Photopea to compress them for the second time? Could you compress the original (uncompressed) file instead?

**Comment by photopea** [comment]
If you convert BC7 to BC1 or BC1 to BC7, new artifacts always appear.

**Comment by ReeceBar** [comment]
"Are you opening BC7 DXF files in Photopea to compress them for the second time" the pic is the original being compressed by your new compression tweaks you've recently made. If you want, you can do it yourself, here's the original file
[GMonk Original And Uncompressed.zip](https://github.com/photopea/photopea/files/9285416/GMonk.Original.And.Uncompressed.zip) I've also included a version that has been uncompressed.

"If you convert BC7 to BC1 or BC1 to BC7, new artifacts always appear." Okay, don't see why I would need to convert BC7 to others when that one seems to produce the best quality, but thanks for the tip.

**Comment by photopea** [comment]
Your "uncompressed" photo was actually compressed with BC7 in the past, it has many artifacts - "cubes of solid color", see the animation. I was asking if you have an original image that has never been compressed.
![image](https://user-images.githubusercontent.com/15955558/183531082-1a3a1caa-7819-497e-bc5f-ce3338b1733f.gif)

**Comment by photopea** [comment]
Your files are 22MB and 5MB, but the bigger one does not have a better quality. The colors of pixels are absolutely identical. You or someone else opened the 5MB file in Photopea and exported it with no compression, to get the 22MB file. But that does not improve the quality.

**Comment by ReeceBar** [comment]
Sorry, I guess I don't have an uncompressed version. Anyway, are you still considering adding a BC7 option for better quality, as shown earlier it has less artifacts than how PhotoPea compresses DDS files normally? And the improvements you said you did to make it better made it somewhat worse, as I've also shown it adds more blotchy pixels than before the improvements, can you undo the tweaks that you've done? I've made a side by side comparison
![PhotoPea New Compression](https://user-images.githubusercontent.com/42558495/183565566-623e56c2-3759-45ac-9678-6c8768ae029c.png)

**Comment by photopea** [comment]
I have implemented the BC7 compression. It is much slower than BC1 (1 second per megapixel). Also, I improved the BC1 properly this time.

Here is a screnshot of BC1, BC7 and No compression.
![image (7)](https://user-images.githubusercontent.com/15955558/185075062-db978137-4c0e-4180-baf0-d7e92fbe956c.png)

**Comment by ReeceBar** [comment]
Thank you! Just tried it out, doesn't feel slow to me, even if it is much slower I much prefer better quality, thanks for implementing BC7 compression, I really appreciate this!
