### ISSUE TITLE
photopea will not let me import any mockup files

### ISSUE THREAD

**Issue by blvndxed** [photopea/photopea#4893]
for the past 2 days, i have been trying to drag and drop my mockup files to use. I've restarted the app, restarted my computer, deleted and re-installed and even tried to use it on the browser. none of this has worked. when I drag in the PSD file or image - it just says loading and never loads. please respond asap, thanks.

**Comment by photopea** [comment]
Could you send us one of your files to support@photopea.com ?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
