### ISSUE TITLE
screen bug

### ISSUE THREAD

**Issue by OmerAtayilmaz** [photopea/photopea#4895]
I resize the chrome size but after I resized to full screen the app stuck at the small screen.

<img width="1140" alt="Screen Shot 2022-08-08 at 12 20 29" src="https://user-images.githubusercontent.com/64100323/183384840-66acdfef-0e62-43ff-a7f2-04616b02df7b.png">

**Comment by photopea** [comment]
I am afraid I do not understand what is in your picture. Is it a web browser? Are you using Photopea at www.Photopea.com ? Why did you cut off the URL address of where you use Photopea?

**Comment by NorbertKrupa** [comment]
I think he is referring to the issue of the right side of the screen being blank.
<img width="1495" alt="Screen Shot 2022-08-11 at 1 49 17 PM" src="https://user-images.githubusercontent.com/3281285/184217057-b2a556e1-a9aa-424d-a7e5-6799e09881ac.png">

**Comment by photopea** [comment]
There should be advertisement on the right side. Please, do not block our ads. Photopea would not exist if everyone did what you do.

**Comment by NorbertKrupa** [comment]
It would help if I logged in 🤦 -- it disappears after logging in

**Comment by photopea** [comment]
I thought it is obvious, that you can not use your Premium account without logging in. If you paid for Photopea but you see ads, you need to log in.
Once you log in and leave, you should stay logged in at your next visit, if there was less than 30 days in between.
