### ISSUE TITLE
Microsoft Edge’s new Enhanced Security breaks Photopea

### ISSUE THREAD

**Issue by Vivelin** [photopea/photopea#4896]
Microsoft Edge’s new [enhanced security mode](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-security-browse-safer) breaks Photopea. The link above mentions why:

> Sites that use WebAssembly (WASM) are not currently supported in this mode. If you require access to a site that needs WASM, consider adding it to your exception site list as described in [Exception site list](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-security-browse-safer#exception-site-list).

Currently, Photopea show the following message when this is turned on:

> Your browser is too old (no WebAssembly). Please, update it.

This message is quite misleading. I don’t know if it’s possible to detect whether the user is running in this mode, but either way, it might be worth changing the message for users that use Edge to tell them to add an exception for Photopea.

**Comment by photopea** [comment]
WebAssembly has nothing to do with "enhanced security". Microsoft is lying. 

It is a bug in Edge. Please, report it to Edge.

**Comment by photopea** [comment]
If you google "photopea edge problem", you will find this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/ 

It explains how to fix it.

**Comment by JeffreyCA** [comment]
I think a better workaround is to add `https://www.photopea.com/` to **Exceptions**:

![Untitled](https://user-images.githubusercontent.com/9157833/188333392-55469ba7-e394-4e94-800d-35ca39cb8a11.png)

**Comment by photopea** [comment]
I think somebody should simply explain to Microsoft, that WebAssembly is not dangerous, as they think, it is not any more powerful than Javascript already is.
