### ISSUE TITLE
I want to support you

### ISSUE THREAD

**Issue by rene-hermenau** [photopea/photopea#49]
I love your photopea project. Photoshop is the last bastion i have to remove from my Windows system. Than i am able to move completely to linux:) so I like to support your project. Is there any way to send you some monthly donation or give you human resources assistance and to support your work anyway?

You find my mail address on my user profile:
https://github.com/rene-hermenau

**Comment by photopea** [comment]
Hi Rene, thanks for your offer :)  I am planning to implement some form of subscription, which will be completely voluntary. You can help me right now by reporting bugs, writing tutorials or simply sharing Photopea with others in social networks :)

By the way, you can use Gimp on Linux, too :) But if you have a lot of work in PSD format, Gimp will probably ignore some advanced PSD features.

**Comment by Studioartcz** [comment]
@photopea Gimp is terible if you know PS!

**Comment by photopea** [comment]
But I think that PS also may seem terrible, when you are used to Gimp :)

**Comment by tomasnosek** [comment]
PS is terrible too in many ways

**Comment by rene-hermenau** [comment]
The tool you do not know is the most terrible one:)

> You can help me right now by reporting bugs, writing tutorials or simply sharing Photopea with others in social networks

I am already doing;)

**Comment by photopea** [comment]
Hi, so now you can support us in a convenient way :) With Premium account, you don't get any extra features, but you can support the development of Photopea.

https://blog.photopea.com/photopea-premium.html

**Comment by photopea** [comment]
Hi, thanks! We want Photopea to be free for most of the people. You can order a Premium account in Photopea (e.g. for 90 days), which will hide ads and enlarge the workspace :)
