### ISSUE TITLE
When moving text with arrow got error messages

### ISSUE THREAD

**Issue by reefdev** [photopea/photopea#490]
![capture 2018-02-23 a 16 47 34](https://user-images.githubusercontent.com/2813640/36602853-5e0325d6-18b9-11e8-90ca-160f1b0c5999.png)

**Comment by photopea** [comment]
Do you remember what you did before it happened? There appears to be an empty selection, which had to be removed by a previous tool (what tool did you use before)?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
