### ISSUE TITLE
Can't Download Photopea

### ISSUE THREAD

**Issue by Bees1234** [photopea/photopea#4901]
I'm on google chrome and cannot download Photopea. Yesterday I did have the option to download, but now it has just gone grey. I have Chrome updated to the latest version, so I have no idea what the issue is.

**Comment by photopea** [comment]
do you mean "Install Photopea"?

**Comment by Diorsses** [comment]
me tooMe too. Why is this happening? I feel really bad. I can't install it!

**Comment by photopea** [comment]
It works only in Chrome and Edge. If it is not availabe, you need to uninstall it first at about://apps

**Comment by photopea** [comment]
I have to close it because of lack of details :(
