### ISSUE TITLE
Not saving

### ISSUE THREAD

**Issue by zaqstavano** [photopea/photopea#4902]
For the last few days I haven't been able to save psd files with Photopea. It sucks because it will let me save the file as soon as I create it but once I start adding things or make any changes it doesn't let me save. It just says "saving" forever. It's been devastating but hope it gets fixed soon.

**Comment by photopea** [comment]
There is nothing to fix. Saving works for everyone except of you.

Please, try these steps and let me know if it helped: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by zaqstavano** [comment]
oof. it was an extension that was causing the problem.
so glad it's working for everyone. there truly is nothing to fix. good job.

**Comment by photopea** [comment]
Could you tell us what was the name of the extension, or a link to where you downloaded it?

**Comment by zaqstavano** [comment]
Sure, it was PhotoMania.
https://chrome.google.com/webstore/detail/photomania/ohodmcahedcphoipgooelhjcfahodhcj

**Comment by zaqstavano** [comment]
This issue started up again today, no idea what's causing it this time as I haven't installed any new extensions.

**Comment by photopea** [comment]
Does it happen in the Incognito mode?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
