### ISSUE TITLE
Some questions about Reduce Color

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4903]
1. Why limit the number of colors to a maximum of **50**? Can we have more?
2. Which areas of the image are considered noise?
3. How are cartoon pictures and photos treated differently?
4. What is segmentize mainly used for?

I would be grateful if you could explain in detail how they work. Knowing that, we can make better configurations for different images.

**Comment by photopea** [comment]
When using Reduce Color, I think you should play with it yourself to see what is the difference. The names of parameters are only "the clue".
