### ISSUE TITLE
It does not give to download PSD formats

### ISSUE THREAD

**Issue by yair121812** [photopea/photopea#4906]
It does not give to download PSD formats

**Comment by photopea** [comment]
what does it mean?

**Comment by yair121812** [comment]
Like I'm trying to download but it loads for an hour

**Comment by photopea** [comment]
So saving never works? Can you create a new document and save it right away? 

Also, read this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details :(
