### ISSUE TITLE
Can't load PSD anymore

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4907]
i have installed Photopea as a PWA, but chrome is not picking my PSD files as openeable anymore.

I could at some point. Is this a chrome issue?

**Comment by photopea** [comment]
Did you set Photopea as the main program for opening PSDs? Maybe you should tell your operating system what program to use for opening PSDs. You don't tell us what operating system are you using, and if it worked before on that OS.

**Comment by TheRadicalDreamer** [comment]
I am using chromeOS, and yes, it worked before. So i guess is a OS issue

**Comment by photopea** [comment]
could you uninstall it in about://apps and install it back again?

**Comment by TheRadicalDreamer** [comment]
Chrome://apps does not give me any site... :/

**Comment by TheRadicalDreamer** [comment]
but i will uninstall it 
![Uploading image.png…]()

**Comment by TheRadicalDreamer** [comment]
But still i cannot open it anymore.

I believe i should open a ticket on chromium bug tracker

**Comment by photopea** [comment]
After uninstalling, did you try to install it back again?

**Comment by TheRadicalDreamer** [comment]
Yes

**Comment by TheRadicalDreamer** [comment]
Do you want me to create a chromium issue?

**Comment by photopea** [comment]
If you can reproduce it, and you are ready to discuss it with the Chrome team, go ahead!

**Comment by photopea** [comment]
so I will close it now.

**Comment by TheRadicalDreamer** [comment]
This got corrected on v105 of chrome.

I did made an issue on the chromium report platform, and they did changed it. 

It was a bug.
