### ISSUE TITLE
Team add button doesnt work

### ISSUE THREAD

**Issue by MSsecrentlegend** [photopea/photopea#4908]
when i someone adds me or i add someone and click add it doesnt really do anything i pressed it alot of times a waited alot and nothing still happens, i tried it with multiple devices but still it doesnt work.

**Comment by photopea** [comment]
Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by MSsecrentlegend** [comment]
sorry but it still didn't fix it.

[image: width=]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by photopea** [comment]
So are you asking to join a team, or accepting members into your team? It is not clear. Could you show us what you see in front of you?

Also, reply at github.com, instead of sending emails to some random email addresses of Github.

**Comment by photopea** [comment]
Could you share a screenshot? So that I check what team is it and who you are adding

**Comment by MSsecrentlegend** [comment]
sorry it took me long but here
https://user-images.githubusercontent.com/111090891/184554518-a41f5f52-72dc-4e52-b3d8-19c52497ac52.png

**Comment by MSsecrentlegend** [comment]
@photopea so?

**Comment by photopea** [comment]
I still don't understand why it does not work for you.

Could you try it in the Incognito mode? Do you see any errors in a web console (right click - Inspect Element - Console) ? I requested to join your team, could you add me?

**Comment by photopea** [comment]
Are there any news?

**Comment by MSsecrentlegend** [comment]
i tried in incognito mode but still can't add anyone

**Comment by MSsecrentlegend** [comment]
and also i got an error saying "pp.js:10600 Uncaught TypeError: Cannot read properties of null (reading '0')
    at hN.AC (pp.js:10600)
    at c5.aD.X (pp.js:9794)
    at c5.dg.X (pp.js:9799)
    at c5.Ze (pp.js:9872)"

**Comment by photopea** [comment]
There seemed to be a bug, such that only users with a Team Premium account could add members. It should be fixed now. Could you try it again?

**Comment by MSsecrentlegend** [comment]
It works now thank you!

**Comment by photopea** [comment]
I am very sorry for this, I should have tested it with a non-premium account.
