### ISSUE TITLE
How to remove it from ubunut applications?

### ISSUE THREAD

**Issue by lizhan17** [photopea/photopea#4909]
I don't know why it keep appear in my appilcation search. I should never install it.  
I cannot open pdf files also. Because it keeps reminding me of using photopea to open pdf file, which is insane.

![image](https://user-images.githubusercontent.com/32379931/184258759-fbbc0599-8a17-492a-85be-35c140b5d570.png)

**Comment by lizhan17** [comment]
solved. 

rm $HOME/.local/share/applications/chrome-*.desktop

**Comment by photopea** [comment]
How did you install it? If you pressed More - Install Photopea.com, it usually can be uninstalled in "about://apps" in your browser.

**Comment by lizhan17** [comment]
I didn't remember when and how i installed. Since only use it for several times.  
Thanks for your helping. I found it can be uninstalled in about://apps
