### ISSUE TITLE
Problem editing text layer

### ISSUE THREAD

**Issue by MariaUbaldo** [photopea/photopea#491]
Hi, 

My problem is that when I open an image and edit some of its text layers the size of the text increases and the font type changes. In my case, I have an image with lots of text around it, and this just happens in some parts of the text.

Thanks in advance :-)

**Comment by photopea** [comment]
Hi, you must have a font file (TTF or OTF) if you want to draw new characters with that font. Photopea already has a database of 3500 free fonts (like Open Sans or Lato), so you should not worry about such fonts. 

But if there is a commercial font in your PSD (like Helvetica or Arial), you must buy such font (or maybe you bought it with your operating system already) and load it into Photopea using File - Open. Hope it helps :)

You can see the name of the original font in the top menu.

**Comment by MariaUbaldo** [comment]
Thanks for the attention :-D
