### ISSUE TITLE
Problem with Dimensions, DPI and lack of RAM

### ISSUE THREAD

**Issue by jeffdore** [photopea/photopea#4911]
![photopea](https://user-images.githubusercontent.com/108548352/184441443-64d024e0-6c48-4570-bb84-4b8fabe23cb9.png)
![photopea1](https://user-images.githubusercontent.com/108548352/184441447-8a34c837-2fca-4e4a-b8a4-af72d57abae0.png)

Hello
When creating a new project and entering the attached settings, Photopea has a lack of memory. I've tried on other machines with more mb, even so the problem persists. How can I solve? Thanks.

**Comment by photopea** [comment]
You are crating an image of 70,000 x 20,000 pixels (1.4 billion pixels, 1400 megapixels). 

In such image, each layer needs 4.7 GB of RAM, so you need about 10 GB of RAM  for a document with one layer.

Get more RAM, or set the lower DPI. It is a raster editor, not a vector editor (where the DPI does not matter).
