### ISSUE TITLE
Filter - Ink Outlines leaves all white

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4912]
PSD: https://www.photopea.com/#ivRAPb3Nj

The skull has a different preview from what i get after hitting OK

![image](https://user-images.githubusercontent.com/11801254/184455997-1dad7c55-e28f-48eb-9aff-f98e48ff0cb8.png)

![image](https://user-images.githubusercontent.com/11801254/184455938-40cb0206-c003-4a84-a41d-372ea6249866.png)

**Comment by photopea** [comment]
thanks, it is fixed now! :)
