### ISSUE TITLE
Vector Movement - When rotated it does not respect the movement 

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4913]
When i rotate the canvas i can select a layer and move it with the arrow keys relative to my rotated perspective.
This changes when i enter transform controls, which is fine.

BUT

When i move a shape with the Path Select tool and i move it with the arrows, it moves like i am in transform controls.

It should behave the same as move tool. If i select and move, the move is relative to my rotated position, but if i hit Ctrl+T then it moves according to the canvas

**Comment by photopea** [comment]
The Free Transform, the Path Select and the Direct Select tools should respect the document rotation now.
