### ISSUE TITLE
Missing part of CSS code in imported PSD

### ISSUE THREAD

**Issue by GitUser200607** [photopea/photopea#4914]
After importing PSD to my project, I can display CSS properties of button element, but _inner shadow_ property does not display as CSS code (but the effect is working):
`width: 321px;`
`height: 80px;`
`background-image: linear-gradient(0.0deg, #2798b9 0%, #3ab6da 100%);`
`border: 4px solid rgba(0,0,0,0.22);`
`box-shadow: inset 0px -5px 0px 0px rgba(0,0,0,0.17);`

**Comment by photopea** [comment]
It is hard to tell if the CSS in Photopea is good or bad, since you did not share your PSD with us.

Could you write down a CSS code, that you want to get in this case? When you use a CSS of Photopea, are you sure it does not do what you want?

**Comment by GitUser200607** [comment]
Layer: Ellipse 1 Copy 4
I cant cut other layers (and I don't know, can I share this file. So when you check it, I will delete it, ok?
[WordPress2.zip](https://github.com/photopea/photopea/files/9334034/WordPress2.zip)

**Comment by GitUser200607** [comment]
There is also missing CSS property in the layer "Записаться на интенсив!":
`text-transform: uppercase;`

**Comment by photopea** [comment]
I have fixed the problem. The Inner Shadow, and the uppercase text, are converted into the correct CSS properties.

Let me know if anything else is missing (and if it can be described in CSS)! :)
