### ISSUE TITLE
Shortcut ] not working on brush

### ISSUE THREAD

**Issue by raabe-ctrl** [photopea/photopea#4915]
When I press [ shortcut on brush, it increases the size. But when I press ] to decrease, it does not work. I wonder if it's a problem of my computer, but it's a new one, I just bought it. Please could you help me? Thank you.

**Comment by photopea** [comment]
Hi, both [ and ] work for me. What language settings do you have on your keyboard? Did you try another language? Do these shortcuts work in other software?

**Comment by raabe-ctrl** [comment]
Both [ and ] work on other softwares, but only in Photopea ] doesn't. I use Portuguese, and even when I switch to English, it does not work. But it's working in yours, so I guess it's something with my computer... I was wondering if it was a bug from Photopea, but it's not. Anyway thank you ! :D

**Comment by photopea** [comment]
Try to disable all your browser extensions, see if it helped.
