### ISSUE TITLE
Can't use inverse tool?

### ISSUE THREAD

**Issue by Arcolgio** [photopea/photopea#4919]
I have no idea why but i am unable to use the inverse tool from either the menu or the command. In the menu the option is greyed out as if it is unavailable. I am in Windows 10 using OperaGX if the info helps at all.

Edit: I also later tried in Chrome with no success.

**Comment by photopea** [comment]
Do you mean Image - Adjustments - Inverse?

What are you inverting? You can not invert a folder of layers, or a text layer, etc. You should select one or more regular layers, to adjust their colors.

**Comment by Arcolgio** [comment]
Select - Inverse

I only had one layer selected.

**Comment by photopea** [comment]
An empty selection can not be inverted.

E.g. if you select all (Ctrl+A), then you invert it, and then, you can not invert it again (as nothing is selected at that point).

Could you show us a screnshot of what is selected in your case?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
