### ISSUE TITLE
Laggy tools

### ISSUE THREAD

**Issue by BramNUFC** [photopea/photopea#4920]
When I try to move around with the clone stamp or eraser for example, it's a bit laggy. I'm pretty sure it's not caused by my internet connection

**Comment by photopea** [comment]
How large is your document and how many layers do you have? What is the size of your brush?

**Comment by BramNUFC** [comment]
> How large is your document and how many layers do you have? What is the size of your brush?

I've restarted and it seems to be fixed now. Think it was just some small images with a couple of layers, so idk what caused it

**Comment by photopea** [comment]
Please, once you can make Photopea behave incorrectly, tell us how you do it.
