### ISSUE TITLE
No cooldown with shortcuts

### ISSUE THREAD

**Issue by matangoldstein** [photopea/photopea#4921]
When I press CTRL + V for duplicating a layer, 
Or CTRL + Z to go back a step,
Instead of happening once, the action will repeat 5-7 times

**Comment by photopea** [comment]
Try this, let us know if it helped: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by matangoldstein** [comment]
Nothing about this bug seems to appear there

**Comment by photopea** [comment]
Does this problem happen in Photopea in Incognito mode, or when you disable all your extensions?

I can not make this problem happen in Photopea. Maybe I need browser extensions that you have for this "repeating funcitonality".

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by matangoldstein** [comment]
It does happen also on incognito

**Comment by photopea** [comment]
Are you sure it is not an error of your keyboard? Could you record a video of how it looks like? So far, nobody else in the world reported such problem, so I think it is a problem of your device.

**Comment by matangoldstein** [comment]
Will check
