### ISSUE TITLE
Blank space appears

### ISSUE THREAD

**Issue by mu0s7afa** [photopea/photopea#4922]
Blank space appears on the right side, I thought it's because of the adblocker, but it's the same when I disable it.
![00](https://user-images.githubusercontent.com/87569592/185303923-6097bd62-c0e8-4d71-ab85-1ade9f58958d.jpg)
![01](https://user-images.githubusercontent.com/87569592/185303927-20e540bc-daac-4644-b521-61cef47dd9bf.jpg)

**Comment by photopea** [comment]
Could you try it in the Incognito mode?

**Comment by mu0s7afa** [comment]
Still the same.

**Comment by xan2622** [comment]
I guess it happens because the first time you used the Photopea website, you probably rejected the cookies.

**Comment by photopea** [comment]
There should be ads on the right side. Do you have any software in your computer, which could be blocking certain websites / domains? Like a firewall or a pi-hole?

**Comment by mu0s7afa** [comment]
Yes, The ad has just appeared, The issue was related to my firewall.

Thanks for quick response.

**Comment by photopea** [comment]
Thank you for supporting us by watching our ads.
