### ISSUE TITLE
How to not load fonts

### ISSUE THREAD

**Issue by dehyang** [photopea/photopea#4923]
I use a lot of Chinese for my manuscript, and the loading font is super slow

I just want to select a local font to load

**Comment by photopea** [comment]
If you load the font once, it should stay in your cache for 14 days. So please, do not delete your cache (or disable your extensions, which delete the cache). Don't use Photopea in Incognito, which deletes the cache.

You can load fonts from your computer into Photopea using File - Open.

**Comment by dehyang** [comment]
> If you load the font once, it should stay in your cache for 14 days. So please, do not delete your cache (or disable your extensions, which delete the cache). Don't use Photopea in Incognito, which deletes the cache.
> 
> You can load fonts from your computer into Photopea using File - Open.

It takes several minutes to open each .ai file

The reason is to download fonts

Can you cancel the download?

**Comment by photopea** [comment]
The text in the AI file can not be rendered without having a font.
