### ISSUE TITLE
turkish translate problem

### ISSUE THREAD

**Issue by cyb3rsalih** [photopea/photopea#4925]
I really love to use photopea and notice little translate problem. 

"Yatay" - "Dikey" which means Horizontal and Vertical written in wrong order.  

<img width="353" alt="Screen Shot 2022-08-18 at 15 34 45" src="https://user-images.githubusercontent.com/17196669/185395974-0bdd03da-ef25-4d58-8c29-842ead4df1cc.png">

Thanks

**Comment by photopea** [comment]
Did you look into the English version? Press More - Language - English (you can switch the language without closing Photopea).

So if you divide it into 4 parts horizontally, it will make 4 columns going from left to right (in the horizontal direction). Is that how you understand it?

**Comment by cyb3rsalih** [comment]
wow, I didn't understand like this.

Thanks.
