### ISSUE TITLE
Projects not Saving/Exporting

### ISSUE THREAD

**Issue by ThatCrispyToast** [photopea/photopea#4926]
When attempting to save or export a project through the file menu or `Ctrl+S`, the project just continues as if I didn't do anything. The star next to the filename in the tab does disappear though, indicating that it thinks that it has saved itself. I've tried using it in incognito mode and disabling all of my extensions, but the issue persists.

**Comment by photopea** [comment]
If you opened an existing file from your computer, pressing Ctrl+S will replace the old file with a new one, there is no window in between. If the old file is not replaced, try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

Also, sometimes Chrome allows just one saving of a file, and blocks other savings. You should tell Chrome to let Photopea save more than one file.

**Comment by raabe-ctrl** [comment]
@ThatCrispyToast I guess it's not an issue, it's normal behavior
![Captura de tela 2022-08-18 160409](https://user-images.githubusercontent.com/91345712/185474487-a6806e40-fb78-405c-a911-a155aaeb1e22.png)
  If you press Ctrl + S, or the button indicated by the red arrow, it will replace the existing file from your computer.
  To export a project, a new file, you need to click on "Save as PSD", "Save More" or "Export As".

**Comment by photopea** [comment]
I guess it has been solved.
