### ISSUE TITLE
Cannot preview problem with shapes

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4927]
[img150.pdf](https://github.com/photopea/photopea/files/9377655/img150.pdf)

I have this PDF file with vectors.

As  you can see: 'a' and 'e' have a white dot in the middle.

![image](https://user-images.githubusercontent.com/11801254/185494562-cce01176-7ab4-4f5e-bacf-5311b30c2043.png)

When  you open this file in Photopea, you don't see that issue.

As soon as you export it you can see them.

Why this happens? It can be fixed?

If not, can we be able to reproduce it inside Photopea, so i can know before exporting it?

**Comment by photopea** [comment]
The PDF from Photopea seems to be completely fine. I have discussed it here: https://stackoverflow.com/questions/72001021/svg-circle-where-the-stroke-width-is-bigger-than-the-diameter

I made a smaller version of this problem: [Ra.pdf](https://github.com/photopea/photopea/files/9377911/Ra.pdf)

I think it is a bug in your PDF viewer. Adobe Reader renders it correctly. But in general, I would recommend you not to make a stroke thicker than the hole.
