### ISSUE TITLE
Export layer to file

### ISSUE THREAD

**Issue by GitUser200607** [photopea/photopea#4928]
Missing (or I could not find) Layer operation "Export to file..."

**Comment by photopea** [comment]
What should such feature do? Do you know, that when you have a Move tool, there is a button "Save selected layers"?

**Comment by GitUser200607** [comment]
Ah, yes. this it what I needed. 
There is a File->Export Layers...
It would be great to have an option to export _current selected_ layer, because not all can find this "Save selected layers" button quickly.

**Comment by GitUser200607** [comment]
__

**Comment by photopea** [comment]
There is a limited amount of space in the File menu. If we put 125 features into it, it would be very messy.
