### ISSUE TITLE
Drag n drop jpgs from other browser tab directly to photopea to import as doc or layer

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#493]
Drag n drop jpgs to canvas for import as layer
Drag n drop jpgs to document tab area for import as new doc
This would be very handy for quick editing jpgs found on the web from other tabs, without first saving them to the disk

**Comment by photopea** [comment]
Hi. Drag n drop from where? You can drag and drop files from your device already. I am not sure if it is technically possible to detect dropping images from other webpages (or even to drag images from webpages).

To avoid saving a file locally, you can usually right-click it, press Copy Image, and then press Ctrl+V in Photopea.

**Comment by hgs54371** [comment]
Drag n drop image from another web tab into the photopea tab, I'm on a mac with trackpad in firefox.
I'm so used to this method that I forgot it can also be done with right click copy and keyboard paste.
If direct drag n drop is also usable, this would be even more convenient

**Comment by photopea** [comment]
Ok, we have implemented it. It should work now. Thanks for suggesting this feature! :)

**Comment by hgs54371** [comment]
When drag from google search image or web page either as a doc or a layer, it shows loading then unknown file format: <htm or <!DO

**Comment by photopea** [comment]
But can you drag and drop images this way into some other webapp?

**Comment by hgs54371** [comment]
I can drag n drop an image from a web page into another tab with google open to use google search by image

**Comment by hgs54371** [comment]
Maybe I'm not dropping it onto the correct area? In google search by image, you have to drop it on the correct field it provide, otherwise it goes to another page

**Comment by photopea** [comment]
Are you sure you can drag from Google Search to Google Search? For me, when I drag an image into Google Search, it just pastes a link, that was set to that image.

**Comment by hgs54371** [comment]
Search for random thing then go to the image tab, or just go
https://images.google.com/
The search field in the image tab respond differently when drop image onto

**Comment by hgs54371** [comment]
This page also is also browser dependent, in firefox simple drag n drop works, but in safari have to click the camera icon first, Then the drag n drop works

**Comment by photopea** [comment]
You can drag and drop images into Photopea, if
- the image is not a link
- it is a link, but to some another image

**Comment by hgs54371** [comment]
So drag n drop images directly from google image search results can work with google image search field itself, also can work with mac(drag n drop to desktop/folders), but not photopea, what are the differences here, can this be improved ?

How the first two can read that as image but photopea cannot

**Comment by photopea** [comment]
Ok, I fixed it, you can drag images from google search into Photopea ... but only "minified" images, not "expanded" images.

Also, you can drag images either to the current document, or to the project bar - to open them separately, etc.

File - Open from URL: now you can choose, whether the image should be inserted into a current, or into a new document.

**Comment by photopea** [comment]
I can not get the same search results as you did. Have you tried saving that image and opening it in PP separately?

**Comment by hgs54371** [comment]
That is ok but my point is that there are still differences between these mini images for any given keyword search result and that they haven't yet been covered/load-able with current feature
