### ISSUE TITLE
Cannot link photopea to my github account so that I can buy the annual license

### ISSUE THREAD

**Issue by eapengeorge001** [photopea/photopea#4930]
Hello,
I am trying to create an account and go premium and buy an annual license for Photopea but whenever I try and connect it to my GitHub credentials to create an account, I get an error message when I try and link the accounts. The error message is as follows:-
<<Photopea didn't receive your name.
Please, enter the missing parameters at your GitHub account.>>

Please help as I want to go Premium. Photopea is an awesome tool!
Thanks,
George.

**Comment by photopea** [comment]
Go to your Github settings and enter some name into the form. That should fix it.

**Comment by photopea** [comment]
I think it has been solved.

**Comment by eapengeorge001** [comment]
Perfect. It has been solved. Thank you!
George.
