### ISSUE TITLE
When uBlock Origin extension is turned off, it gives a message saying adblocker is on

### ISSUE THREAD

**Issue by chamikavi** [photopea/photopea#4931]
title

**Comment by photopea** [comment]
You are probably using an ad blocker. Did you try to use Photopea with all your extensions disabled?

**Comment by pl-stanislav** [comment]
Same thing. I turned off AdBlock but stiil receiving message about blocker

**Comment by photopea** [comment]
I mean turning off all your browser extensions. Did you try it?

**Comment by DevoLakeGH** [comment]
This same issue occurs with me, I have ALL browser extensions disabled and the problem still persists.

**Comment by photopea** [comment]
@DevoLakeGH could you share a screenshot of about://extensions in your browser? Also, do you use any antivirus or a firewall, which could perform web censorship?

**Comment by jointri** [comment]
I used to think ads wouldn't work no matter what, but after testing it on windows 11 with firefox and both the firefox native tracker blocker turned off AND ublock origin disabled for the site, I got the ads that I should have been receiving. Remember that firefox as well as chromium based browsers block trackers by default so disable that too.
