### ISSUE TITLE
Photopea in Linux

### ISSUE THREAD

**Issue by rialbbe** [photopea/photopea#4933]
We have some issue when saving and some buttons in Linux Pop OS in HP laptop and other OS or desktop or laptop. I hope it will soon resolve. And I am a user Photopea in Linux. You can see some issue on my youtube channel in rialbbe. 

In addition to this, I can't open or sometimes it can't save in Linux or sometimes it save but zero file size indicate. Buttons can't be click. But you can use by using spacebar. I'll post another video in the next few weeks for more information for improving the application especially in Linux users.

**Comment by photopea** [comment]
All web browsers in the world should work the same. I think it is a problem with your system or your browser. Try a different browser. Photopea.com should work perfectly in all correct web browsers. 

Also, try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

If you downloaded and installed some "software" called Photopea, it is probably a virus. We never made any installable software, we only have a website.

**Comment by rialbbe** [comment]
I have downloaded it via Pop Shop app store in both Pop OS Linux in school office desktop and my personal laptop with the same issue. I'll try to uninstall and install in a different way or outside Pop Shop app store. I'll keep you to update.

**Comment by photopea** [comment]
I have no idea what you are talking about. Photopa is a website and it should be used in a web browser at www.Photopea.com . If you have problems with a program, you must ask the person who made it. We did not make the thing that you are using.

**Comment by macbian-linux** [comment]
A third party submitted an unofficial Electron wrapper of the Photopea website to the open source Linux app store [Flathub](https://flathub.org/home). That would show up in the Pop!_Shop because it has Flathub support. The app has no association with Photopea.

**Comment by rialbbe** [comment]
Any suggestions for Linux users? I've tried also the website version and
it's not working well too, in Linux users.

**Comment by rialbbe** [comment]
2022-08-23 09-49-25.mp4
<https://drive.google.com/file/d/1pc-dDHR2mvO0k1OvFUl9oAG6EluytmuV/view?usp=drive_web>

**Comment by rialbbe** [comment]
Yes. I just noticed that some photopea app are 3rd party. Now, I've used a
chromium browser to download the app. I hope there will be no issue on
this. Last time I tried to download it via brave browser and firefox. And
both have similar issues. I hope this one will be good enough as I used a
chromium browser to download. Anyways, thanks for the tech support and I've
get back to you as soon as possible if any issues arise.

**Comment by photopea** [comment]
I will close it, as it is not related to our product. If you download a virus named "Photopea" and it deletes your whole hard drive, it there is nothing we can help you with.

**Comment by rialbbe** [comment]
> I will close it, as it is not related to our product. If you download a virus named "Photopea" and it deletes your whole hard drive, there is nothing we can help you with.

I've download from your website already. As of now, it work perfect. Thanks. In the next few weeks I'll make some video review on your software from Linux. Thanks for the help. It gave me, peace of mind as I learn this, that not all in the app store are legit.

**Comment by photopea** [comment]
Thank you!
