### ISSUE TITLE
Security of plugins

### ISSUE THREAD

**Issue by xan2622** [photopea/photopea#4934]
Hi Ivan.

I have a question about the security of plugins.

I wondered if all plugins were checked before they are made available on the website from the Window > Plugins interface? 
Do you review their source code (to avoid security problems on your users' computers)?

I am sure you care about the security of your website but I wondered how this process was made.
Plugins can't be automatically uploaded to the website, can they? 
Do you request from developers that they release the source code of their plugins as open-source on Github (for example)?

I don't know coding at all but I've heard that it's possible to hide malicious code in Javascript (in other languages too of course), that's why I wondered..

For example, the new plugin "Soo" doesn't have any description, just a name and an image.. It's difficult to understand what it does. After installing it, I haven't been able to figure out where it added buttons or options.. Is it risky to install this plugin?

![2444](https://user-images.githubusercontent.com/1732773/185766794-05a920b4-f7c2-43eb-92e6-d84061bc833d.jpg)

**Comment by photopea** [comment]
In the case of "Soo", the user uploaded the ATN file (actions) as a plugin, so it adds actions into Photopea. I just deleted this plugin from the gallery (but it is still installed for you, you need to uninstall it manually).

If you install a plugin, and open it, it can see your current document, see all layers, and insert anything into your document, or delete anything. So there is no big "harm" they can do (if the plugin deletes a layer, you can do a step back, if the plugin adds a layer, you can delete it).

Of course, if someone finds a plugin doing something "bad", they should report it to us, and we will ban all current and future plugins from that user.

**Comment by xan2622** [comment]
Thank you very much for these explanations.
