### ISSUE TITLE
Photopea super slow

### ISSUE THREAD

**Issue by Felipin300** [photopea/photopea#4935]
why photopea is super slow?

**Comment by photopea** [comment]
It seems to work fast in my case. What should I do to see Photopea working super slow? Or could you record a video of what you do and how slow Photopea is in your case?

**Comment by elhananjair** [comment]
@photopea I am trying since yesterday and the loading status is showing for long time, I tried to open psd file and it doesn't download the fonts.
![Screenshot from 2022-08-23 09-17-15](https://user-images.githubusercontent.com/69236638/186084593-f3d9bb18-7735-47ca-8677-213621c2bff5.png)

**Comment by photopea** [comment]
Try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by elhananjair** [comment]
@photopea thank you so much I installed as an app from chrome and it works perfect now

**Comment by photopea** [comment]
I will close it now, because the original person stopped replying.
