### ISSUE TITLE
Is BC3 compression no longer available? 

### ISSUE THREAD

**Issue by riiverview** [photopea/photopea#4936]
Hi! I'm trying to export some DDS files (the application I'm using them for can only read BC3/DXT5 & I've been using Photopea to create these textures up until a week or two ago at most). Having used Photopea just now, BC3 compression doesn't seem to be accessible— I know BC7 support was recently added, I don't know if that's related. Is it no longer supported? 
I'm able to convert the files externally, so it's not a problem beyond mild inconvenience if it's not supported any more (or I could just be totally mistaken!), I'm just after a little clarity, if that's okay. :)
Thank you!!

**Comment by photopea** [comment]
We created the BC7 compression. The file size in BC7 is identical to BC3 (1 Byte per pixel), but the image quality is much much better!

Why don't you export in BC7 instead of BC3? The texture size on the GPU is identical, you just get the better quality.

**Comment by riiverview** [comment]
Hi!! Thank you for your response! I've tried to export in BC7, and that works well, it's just that what I'm using doesn't support BC7 (it uses older graphics hardware).
It's fine, though, I'll export them as PSDs & convert them externally.
Thank you for your time again! :)

**Comment by photopea** [comment]
Ok, I have added the BC3 compression back :)
