### ISSUE TITLE
Video pre-training dataset

### ISSUE THREAD

**Issue by jhlusko** [photopea/photopea#4937]
I think photopea is in a unique position to create an image-generation AI. Diffusion models like Dall-E are cool, but can't be edited easily. What if instead of creating images they created photopea sessions?

Consider the recent progress in Minecraft AI: https://openai.com/blog/vpt/

Similar progress could be made for Photopea if there were a labelled dataset of user actions. A small dataset has been created for photoshop: https://www.researchgate.net/profile/Jingchun-Cheng/publication/329091216_Learning_from_PhotoShop_Operation_Videos_the_PSOV_Dataset/links/5bf4f52b4585150b2bc64557/Learning-from-PhotoShop-Operation-Videos-the-PSOV-Dataset.pdf

This is small (74 hr) compared to the 2000+ hrs that OpenAI bought for minecraft.

Since Photopea is web-based it is in a unique position to allow users to opt-in and collect these training sessions, if such a feature were available. What do you think?

**Comment by photopea** [comment]
I have no idea how should I handle such a request. You are asking us to make something what does not exist, and existing things are far from what you are asking for.
Are you a scientist who would be able to develop it? Could you develop it for Photopea? I never tried to do any research for which my laptop is not powerful enough.

**Comment by jhlusko** [comment]
Sorry the above request is unclear. The feature I am suggesting is allowing users to opt-in to session collection using something like https://openreplay.com/

The resulting database is valuable but expensive to produce normally. I think an open dataset like this would be valuable to the research community. I think the Minecraft example shows how a dataset like this could be used.

I am not a scientist but I have some experience in the area and would be interested in working on the project.

**Comment by photopea** [comment]
I am not convinced that having a recording of the work of all our users could be useful for anything. If you want to make a neural network for editing photos, such editing could lead to many different results. I am not good enough in this area.

You can use videos on Youtube of people using Photopea, if that is what you need for your research.
