### ISSUE TITLE
noise & damaged frames

### ISSUE THREAD

**Issue by skywalker005** [photopea/photopea#4938]
every time i'm making it a gif, it will damage the frames upon trying to add any amount of sound.  it will save perfectly fine without it, but damages the second i add noise.  i've had this issue for some time now.

**Comment by photopea** [comment]
Hi, Photopea can not add any sound. Are you sure you are using www.Photopea.com ?

**Comment by photopea** [comment]
I think I have found the problem. It should be fixed now.

**Comment by skywalker005** [comment]
I'm so sorry! I meant "noise." Not sound.
