### ISSUE TITLE
PDF Export - blend mode export different from the preview

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4939]
![image](https://user-images.githubusercontent.com/11801254/186267128-f874c646-91da-4af6-8a59-b7fe84444b27.png)

ere is the PSD 
[bug.zip](https://github.com/photopea/photopea/files/9410691/bug.zip)

**Comment by photopea** [comment]
Hi, I think it is related to the CMYK view. Your PSD, when opened in Photopea, looks differently than when opened in Photoshop.

I would recommend working in the RGB mode, or enable "rasterize all" when exporting, just like Photoshop does.

**Comment by TheRadicalDreamer** [comment]
But why does it shows different from what i see on Photopea?

It should be the exactly the same :/

**Comment by photopea** [comment]
One layer (one image) always looks the same, no matter if it is CMYK or RGB.

If you have two RGB layers A and B merged with Color Burn, and you turn the result into CMYK, it will look the same (you are converting one RGB image to CMYK).

If you have two RGB layers A and B, you convert each layer to CMYK separately, and merge two CMYK layers with a Color Burn, it will look totally different.

When you switch between RGB and CMYK in Adobe Photoshop, it asks you to merge all layers, otherwise, the result will be different.

I think this feature added a lot of confusion. I can either remove the CMYK preview from Photopea, or make all exported PDFs always fully rasterized.

**Comment by TheRadicalDreamer** [comment]
Why this blue pattern is not lightblue when exported to PDF even in RGB mode?
[Not blue.zip](https://github.com/photopea/photopea/files/9562630/Not.blue.zip)

**Comment by photopea** [comment]
What exactly are you talking about?

PDF format has no adjustment layers, they are ignored when exporting a layered PSD.

I recommend you to enable "rasterize all" when exporting a PSD, that is what Adobe Photoshop does. Or delete all your Adjustment layers (that is what Adobe Illustrator does, there are no adjustment layers).

**Comment by TheRadicalDreamer** [comment]
I didn't understand that PDF does not have an adjustment layer. And that CMYK is an "adjustment layer" as well.

Sorry, now i get the full issue.

It is fine as it is. I prefer to be the way it is right now, so i can rasterize each piece separately before exporting.

Thanks Ivan for explaining!

**Comment by TheRadicalDreamer** [comment]
Please do not touch the CMYK mode. It has been super useful in all my works.

Sorry i still would like to understand the issue:

When I have CMYK mode enabled, it is like I have rack RGB layers convert to
CMYK separately?

So why when I am editing it looks like one color? And then another when
exported?

It has to do with that the Color burn blend while editing blends in RGB and
then process the final color as CMYK to show me the final color while
editing?

**Comment by TheRadicalDreamer** [comment]
I cannot rasterize. I need the export file to be somewhat editable.

:/

Why the CMYK mode is different?
I believe it has something to do with the pattern filling the shape.

**Comment by photopea** [comment]
This happens in Photoshop, too. When you have two layers with "Color Burn", and you switch from RGB to CMYK, the image will look differently.

**Comment by TheRadicalDreamer** [comment]
Yes, i have tested now myself.

I have to correct the base color to be the same as the one i get with the blend mode. 

So at least this is finished for me.

Thanks!
