### ISSUE TITLE
Issues with Login?

### ISSUE THREAD

**Issue by spxceaced** [photopea/photopea#4941]
I'm not able to log in to remove the side banner and such with my premium. Just to access the website I had to clear my cookies so it logged me out because it otherwise only showed a black screen and nothing else.

![image](https://user-images.githubusercontent.com/106488788/186446018-443f0bbc-5fec-4115-a0f8-40635c15e2a1.png)

**Comment by photopea** [comment]
sorry, it should be fixed now.
