### ISSUE TITLE
Cannot load Photopea

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4942]
I cannot load the page.

I have refreshed, and cleared cache.

I can open it in incognito, but when login i get this
![image](https://user-images.githubusercontent.com/11801254/186446956-02c78e1e-3657-4dd8-848b-6fc3cfe5e842.png)

And then tries mento log into, i believe, is YOUR google account
![image](https://user-images.githubusercontent.com/11801254/186447072-2ab7b907-3ec2-47b0-a57b-d3e83624c4ca.png)

**Comment by photopea** [comment]
sorry, it should be fixed now.
