### ISSUE TITLE
everything becomes red?

### ISSUE THREAD

**Issue by SkyTheAlmighty1** [photopea/photopea#4943]
i've been working on this file for a while, and something just... happened after a long time.
![image](https://user-images.githubusercontent.com/102106676/186534529-95e812e7-554d-42d5-a2aa-a7083425fb27.png)
the layer select turned red, which isn't anything huge, but it also prevents me from drawing with the brush, and it draws red with the eraser. 
![image](https://user-images.githubusercontent.com/102106676/186534942-21f21d6f-d8fb-4916-8d08-1b19e5561376.png)
(^ that red was drawn with the eraser)
what's going on?????

edit: dragging does this too
![image](https://user-images.githubusercontent.com/102106676/186538663-8c9480f6-5d77-4f70-bd4b-67343dbdb1da.png)

**Comment by SkyTheAlmighty1** [comment]
i don't have this issue with new projects by the way, just this specific one that i've been working on for a while.

**Comment by photopea** [comment]
You have enabled the quick mask, see: https://www.photopea.com/learn/selections

Press Q on your keyboard to enable / disable the quick mask.
