### ISSUE TITLE
Please put https://www.photopea.com/learn into a github repo.

### ISSUE THREAD

**Issue by jaimet** [photopea/photopea#4944]
https://www.photopea.com/learn contains lots of errors, some typographic, some content errors, some "English grammar" errors (but don't worry - your English is **_way_** better than either my Czech or my Ukrainian!)

If the source to https://www.photopea.com/learn was available in a github repo, I could send you PRs to correct those errors.

HTH.

**Comment by photopea** [comment]
Isn't it too complicated to do it through GitHub? I don't think there will be many people interested in rewriting it. Could you just write down all errors that you found in a comment?

**Comment by jaimet** [comment]
> Could you just write down all errors that you found in a comment?

Ok. I'll try to get it done this week. :+1:

**Comment by photopea** [comment]
I edit an article at Photopea.com/learn once a year. There should be a mechanism to notify the translators, which part has been modified, and needs a new translation. It all gets too complicated ... We should rather invest into teaching people English :)

**Comment by TheRadicalDreamer** [comment]
Yes, totally, education is the key.

But in many countries english is not an option. Here in my country around 1% speaks fluent english.  :P

There should be a notification of some sort to indicate the translator.

In fact, if i am in the notify system i would totally help translate.

**Comment by zcraber** [comment]
@photopea Does the current documentation have any open licenses (like CC or GFDL)? If so, I'm willing to create a copy & translation (Malayalam language) of the documentation using [Docusaurus](https://github.com/facebook/docusaurus).

**Comment by photopea** [comment]
Do you mean www.photopea.com/learn ? You can translate it to your language and publish it yourself, as long as you say that the original is at Photopea.com/learn .

Maybe I could create a system, where everyone can translate our manuals to other langauges, and it will be published at www.Photopea.com/learn .

**Comment by zcraber** [comment]
Yes, I meant photopea learn.
