### ISSUE TITLE
Layer opacity is reduced to 60% or 44% on horizontal scroll or on shortcut key usage

### ISSUE THREAD

**Issue by nbuz1** [photopea/photopea#4945]
On horizontal scroll with the mouse scroll wheel (the one I have has the tilt click function for horizontal scroll)  the active layer's opacity drops to  60% on the first tilt, and 44% on the second, and it stays there. If I put Photopea out of focus (eg Alt+Tab to another app) then back, then the first right tilt will put the layer visibility on 66% again, then 44% on the second, BUT left tilt leaves it on 44%.

100% reproducible, it happens every time, without exception. No special steps or order of actions needed. Just start Photopea, new or existing project, scroll left or right, and it happens.

Edit: It does not happen using the built in touch-pad of the laptop. Two finger horizontal scroll on the touchpad works as expected.

Sometimes the same opacity reduction  happens on changing tools with hotkeys. Eg. pressing V for the select tool results in reducing the opacity, or M for the selection tool as well. However, this is only sometimes, and I have not found a way to reproduce it.

It happens both on the installed app version and on the website, on Windows 11.

Edit 2:   Brush opacity is reduced to 66% if modifier key is used, such eas shift click to get a straight line. Also, I havent found the steps to reproduce, but it's frequent.

**Comment by photopea** [comment]
I am not able to reproduce any of that. What is a horizontal scroll and why it works differently than a horizontal scroll on a touchpad? Are you sure you can reproduce it in a web browser with absolutely no browser extensions? Or e.g. in the Incognito mode?

**Comment by photopea** [comment]
In Photopea or Adobe Photoshop, if you type numbers on a numeric keyboard https://iczc.cz/d7v38db49aglh9gfg3k1iblnve-3_1/obrazek , you type the new opacity of a current layer. Photopea ignores, if NumLock is enabled or not.

If your "left horizontal scroll" corresponds to pressing "4" on a numeric keyboard, and your "right horizontal scroll" corresponds to pressing "6" on a numeric keyboard, you are typing the new opacity with your mouse.

**Comment by photopea** [comment]
When the Brush is enabled, typing on a numeric keyboard is typing the new opacity for the brush.

**Comment by nbuz1** [comment]
Hello, thanks for all the details.
I do not have a num-pad at all on my 13" laptop.

By "horizontal scroll" I mean tilting left or right the mouse scroll wheel of an external usb mouse : 
![image](https://user-images.githubusercontent.com/75635139/186962247-7dc0863a-b713-4096-9fd5-54ac537e39cd.png)
 
So, you're right, I cannot reproduce it without the external mouse,  and I can assume that it must be a mouse driver issue.

However, the only app the reacts this way, is  Photopea. I tired getting the same results in other apps, and I cannot. Eg. I can never provoke typing 4 or 6 in Notepad with the mouse scroll wheel, as Photopea detects it, nor in a  browsers url bar, or anywhere else, not even after the key sequences used in Photopea. 

Furthermore, once the detection is broken, the real keyboard is also detected as nupad, like "V" = 4, so every time I press "V" the same opacity reduction happens.

So it both is and isn't a Photopea issue.   The combination to provoke this is Photopea + Elecom Mouse Assistant.
I updated the mouse driver and restarted while I was at it, and the issue is still present.

So you can decide to look into or ignore it,  in the light of the above, it's up to you.

Thanks for hunting down the reasons behind the issue, anyway, it saves a whole lot of frustration, at least.

Cheers

**Comment by photopea** [comment]
"like "V" = 4, so every time I press "V" the same opacity reduction happens." - I do not understand, how can be V=4?

I have the same feature on my mouse wheel. When I press the wheel left and right, it scrolls the canvas horizontally.

Are you using Windows 11 Beta? I use Windows 10.

**Comment by nbuz1** [comment]
Window 11 Home, v10.0.22 build 220000
I have no idea how "V" becomes num-pad 4, 
but I'm 99% positive that it is the Elecom Mouse Assistant driver that comes with Elecom brand mouses.
It is strange that it only happens in Photopea. Is there some sort of log could send?

**Comment by photopea** [comment]
So you can make Photopea type 4 by pressing V? You found a bug that happens without a mouse? Could you tell me more?

**Comment by nbuz1** [comment]
Tilt to left gives Numpad4 and to the right Numpad6 in jsfiddle.
V is detected as V in jsfiddle, but it is detected as Numpad4 in Photopea, but only after using the mouse.

**Comment by photopea** [comment]
I think it is a bug in your mouse. Ask the developers to fix it, or not use the horizontal wheel scroll in Photopea.
