### ISSUE TITLE
Undo (ctrl+z) breaks while editing text layer

### ISSUE THREAD

**Issue by derek-adair** [photopea/photopea#4946]
discovered a way to break the undo feature.  I am not sure if this is replicated in other areas.

**To Replicate:**

1. Paint bucket background to black
2. Create a text box
3. Ctrl+Z 
4. _Nothing happens_
5. escape to de-select text
6. Ctrl+Z 
7. Black background turns white AND text layer deleted

**Expected Behavior:**

1. Paint black
6. create text box
7. Ctr+Z
8. Text box is deleted
9. ctrl+Z
10. black background turns white

**To bypass the bug:**

1. Paint black
2. Create Text box
3. **hit escape to de-select text**
4. ctrl+z
5. text layer removed

User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0

**Comment by photopea** [comment]
There was a different error. If you escape a newly created empty text layer, it should be deleted (but it still remained in the layers list). It should be fixed now.

Pressing Ctrl+Z while typing in a text layer should return you to a previously typed text, it should not initiate Edit - Step Backwards.

**Comment by derek-adair** [comment]
Thanks for your hard work!  You are appreciated.
