### ISSUE TITLE
Cannot export anything as a gif, only with images.

### ISSUE THREAD

**Issue by DevoLakeGH** [photopea/photopea#4947]
For context: Whenever I try to upload stuff as a GIF or create a GIF in particular, the animation does not show up on the screen, just the panel and when I export it the file is technically blank. Then when I exit out of the thing and try again I cannot export as anything now when trying to open said export options.
![image](https://user-images.githubusercontent.com/112192797/187253989-6b2c721a-f04b-42ad-b3c3-2ca503c24454.png)
Proof.

**Comment by DevoLakeGH** [comment]
And to this very day, this bug still has not been fixed. Not saying that because I am growing impatient, but because I am growing annoyed because I cant even do animation on this thing!

**Comment by photopea** [comment]
I just tried to export GIFs and it works perfectly fine. Could you try these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

If nothing works, could you save your document as a PSD file, and send it to support@photopea.com ? I will try to export your work as a GIF myself, to see what is going on.

**Comment by DevoLakeGH** [comment]
Its fixed now? Finally.

**Comment by DevoLakeGH** [comment]
Nevermind, I think the issue is with a certain file.

**Comment by DevoLakeGH** [comment]
![image](https://user-images.githubusercontent.com/112192797/187999549-8f111015-dfcc-461c-a434-a8432afa30ce.png)

**Comment by DevoLakeGH** [comment]
It does that when I try to animate THIS.

**Comment by DevoLakeGH** [comment]
Oh god dammit, I think it has to do with PNGS.

**Comment by photopea** [comment]
could you save it as a PSD and send it to support@photopea.com ? I really need to see it happen myself.
