### ISSUE TITLE
Tools Sample from Outside Selection

### ISSUE THREAD

**Issue by elfein727** [photopea/photopea#4949]
Steps to reproduce:
1. Open an image
2. Select an area
3. Use blur tool near edge of selection

Expected behavior:
Colors from outside selection are not sampled.

What happens:
Colors from outside of selection contribute to color of pixels inside selection.

I don't know how exactly this could be implemented because I do not know how the tool system works, but the interface would preferably be a toggle between sampling from outside selection and only sampling inside selection.

**Comment by photopea** [comment]
I see what you mean. But Photopea works the same as Adobe Photoshop, and probably other programs, too. 

Why don't you press Ctrl+J to duplicate selected pixels into a new layer, and blur it there?

**Comment by photopea** [comment]
There is a Clone Stamp, which also might need to sample outside the selection. Do you also consider it wrong?

**Comment by elfein727** [comment]
> I see what you mean. But Photopea works the same as Adobe Photoshop, and probably other programs, too.
> 
> Why don't you press Ctrl+J to duplicate selected pixels into a new layer, and blur it there?

That's actually exactly what I do, but what ends up happening is the transparent pixels get sampled into the selection. This can be good at times, such as when blending two images, but is bad for pixel art.

> There is a Clone Stamp, which also might need to sample outside the selection. Do you also consider it wrong?

No, that makes sense.

**Comment by elfein727** [comment]
Sorry if this is a waste of time.

**Comment by photopea** [comment]
I just tried to do what you said, and Adobe Photoshop also samples transparent pixels even in a new layer. So I guess this is the behaviour that most of people expect.

But you can place your image part temporarily into a new document. Photopea and Photoshop never sample outside the document bounds.

**Comment by elfein727** [comment]
That works! Thank you!
