### ISSUE TITLE
Requesting for user friendly

### ISSUE THREAD

**Issue by karthickraja96** [photopea/photopea#495]
Hi photopea Warm morning!
       While saving the images after working it is saving in downloads as per default.
But, my request for user friendly is images should save in the location where the image is imported from(source). So, by applying this user can easily replace the existing image with worked image. Kindly add this option if it is possible, thank you.

**Comment by photopea** [comment]
Hi, I am sorry, but it is technically not possible right now :( Photopea just "offers a file for a download", it can not access your hard drive and rewrite files just like that (it is still just a website).

Check your browser settings. You could choose the default folder, or make a browser always ask you about the location for saving the file. For Chrome, here is how to do it: https://support.google.com/chrome/answer/95759?co=GENIE.Platform%3DDesktop&hl=en

**Comment by karthickraja96** [comment]
Hi, Thanks for the response and suggestion, will communicate if any further
issues.
