### ISSUE TITLE
drop image into photopea and it gets stuck on loading?

### ISSUE THREAD

**Issue by Zidzods** [photopea/photopea#4951]
hi, I've recently encountered this problem when trying to drop an image file into photopea. I'm no expert on photopea by a longshot, so came here hoping someone has an explanation. when dropping the image into photopea, it fails to load and the white loading bar just stays on my screen.  any ideas as to why this happens? thanks

**Comment by Zidzods** [comment]
the problem is it worked fine before with the exact same files, so im unsure

**Comment by photopea** [comment]
Could you send us your file to support@photopea.com ?

**Comment by Zidzods** [comment]
okay will do thanks

**Comment by Zidzods** [comment]
ive left an email, but its a PNG

**Comment by photopea** [comment]
I did not receive any image :(

**Comment by photopea** [comment]
I have to close it because of lack of details.
