### ISSUE TITLE
sombras

### ISSUE THREAD

**Issue by tenshichan89** [photopea/photopea#4954]
in color range, in shadow does not select the shadow when I click

**Comment by photopea** [comment]
I just tried and it seems to work fine. You should see the shadows white in the preview. Press "OK" to confirm it.

**Comment by tenshichan89** [comment]
I did that and it didn't work, I'm going to send you some prints, and there's one more bug, when I'm going to make a digital art effect using the surface blur the drawing the part of the painting is cracked even when I put a gaussian blur

**Comment by tenshichan89** [comment]
![efeito sombra](https://user-images.githubusercontent.com/112516637/189446955-a82824fe-5936-487b-9b4e-1e177cd6c760.png)
where's the shadow?

**Comment by tenshichan89** [comment]
![efeito arte final](https://user-images.githubusercontent.com/112516637/189447613-0e97592c-4085-43b7-ad71-6fdc33f1af6b.png)
got cracked

**Comment by tenshichan89** [comment]
![Sem título3](https://user-images.githubusercontent.com/112516637/189449162-32441dfd-f1d8-48e0-bad0-32e1c65cb40c.png)
this is before I separate the shadow from the drawing

**Comment by photopea** [comment]
I feel like you are using the wrong tool for your task. You should do it differently. I recommend you to learn all features of Photopea at www.Photopea.com 

If you there is some other program, which can do what you need, show us, and we will make Photopea work the same.

**Comment by tenshichan89** [comment]
no, i always used these effects and it never went wrong, and i always used the same tools i used now in photopea, because i'm not using photoshop anymore

**Comment by photopea** [comment]
Could you tell me exactly, what should I do in Photopea to see the bug myself? So that I can compare if the same thing happens in Photoshop or not.

**Comment by tenshichan89** [comment]
so, I can't say, this never happened in photoshop, but if you want I can show you a video of the effects I'm doing and you can see the error

**Comment by tenshichan89** [comment]
![51353612_2113918598663991_3555315009267433472_n](https://user-images.githubusercontent.com/112516637/189543888-eb0a2dc5-5296-4480-a907-pesquia 253fd4c525be.jpg)
the digital art effect was supposed to look something like this, of course, with a little less color since it doesn't have color search like photoshop

**Comment by photopea** [comment]
I still do not understand :( is it related to the Color Range feature?

**Comment by tenshichan89** [comment]
https://user-images.githubusercontent.com/112516637/189546788-0bde70ee-8d25-411d-be10-a4bd646917fa.mp4

aqui o video do efeito arte final

**Comment by tenshichan89** [comment]
https://user-images.githubusercontent.com/112516637/189547232-897aae6c-835e-4cc8-9eaf-59829aa40998.mp4

aqui o video do efeito sombra

**Comment by tenshichan89** [comment]
> Ainda não entendi :( está relacionado ao recurso Color Range?

então um sim e o outro não vê os dois videos para vc entender melhor

**Comment by photopea** [comment]
I tihnk Adobe Photoshop works the same. I tihnk that is what these filters should do.

**Comment by tenshichan89** [comment]
> Eu acho que o Adobe Photoshop funciona da mesma forma. Acho que é isso que esses filtros devem fazer.

é mas, o efeitoarte final ainda fica craquelado(e eu nem sei pq), o efeito sombra consegui arrumar

**Comment by photopea** [comment]
Sorry, I do not speak Portuguese :( Maybe ask a friend who speaks English to describe your problem better.
