### ISSUE TITLE
Go Fullscreen on PWA

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4955]
O was thinking...
Maybe the mobile experience can be better if  the pwa goes to Fullscreen automatically after launch.

Besides feeling more like a full fledged app it can adjust the elements automatically to the screen size.

What do you think?

**Comment by photopea** [comment]
Sadly, no browser allows a website go fullscreen without clicking some button. They probably consider it to be a user abuse, if a website went fullscreen right after opening.

**Comment by TheRadicalDreamer** [comment]
i created an issue on chromium
