### ISSUE TITLE
Photopea PSD files include 0-length image resource blocks that break some 3rd-party PSD parsers

### ISSUE THREAD

**Issue by tannerhelland** [photopea/photopea#4956]
Hello!

Some 3rd-party PSD parsers have trouble with PSDs saved by Photopea.  For example Paint.NET, as reported here:

https://github.com/PsdPlugin/PsdPlugin/issues/17

A user notified me of a similar crash when loading Photopea PSDs into [my own PSD parser](https://github.com/tannerhelland/PhotoDemon), which led me to investigate in more detail.

I believe this is caused by Photopea writing image resource blocks with a length of 0, specifically image resource ID 0x0415 `Unicode Alpha Names`.  This is an optional block that *should* consist of a valid Unicode string.  Even if a null string is embedded the resource block itself should still be 4-bytes long in order to store a Unicode string length field [per the spec](https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577409_69883).

The PSD spec is unclear on whether 0-byte image resource blocks are OK, but it appears Photoshop checks this case and handles it gracefully.  Only 3rd-party PSD readers are affected AFAIK.

Since this is an optional resource block, and Photopea does not actually store useful information in the block, I think it would be preferable to not write this 0-length block at all.  This would improve PSD compatibility with 3rd-party software and even save a few bytes in saved PSD files!

Thank you for investigating.

**Comment by photopea** [comment]
I am very sorry for that! It should be fixed now, Photopea should not include a 0x0415 block with a length of zero.

But just like Photopea is evolving, every piece of code should be evolving. It should be very simple for the author to fix their parser. I don't think a resource of a length 0 is against the spec.

**Comment by tannerhelland** [comment]
Great work, @photopea .  Thank you for your fast response!
