### ISSUE TITLE
Add Crop Marks For Printing When Exporting

### ISSUE THREAD

**Issue by EugeneQilo** [photopea/photopea#4957]
It will be nice to have crop markings added automatically to the edges when exporting the file. Right now when exporting, you can add margin but no way to add cropping marks

**Comment by photopea** [comment]
Would you like a checkbox when exporting a PDF? Or you want a button, which will add a new layer into a document with crop markings?

Should the crop markings be four crosses at corners, or one rectangle? How thick should be the line?

**Comment by photopea** [comment]
Not sure if anyone needs it, but we have added it to the PDF export.
