### ISSUE TITLE
Actions - Move angle on a layer does not take the pivot point in account

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4958]
If you record a angled move for a layer on an action, it won't remember the pivot point.

This is crucial for example if i want to move it by the corner not by the center.

**Comment by photopea** [comment]
Hi, what is an "angled move"? Are you talking about the free transform tool?

**Comment by MichalSZZ** [comment]
Maybe he is talking about this point as in my screenshot?
![obraz](https://user-images.githubusercontent.com/38118273/188862534-07362fb8-664b-4937-98ed-cc360d0641f5.png)

**Comment by TheRadicalDreamer** [comment]
Yes I am.

I am talking about the point where Michal guide crosses

**Comment by TheRadicalDreamer** [comment]
@photopea ?

**Comment by MichalSZZ** [comment]
When I made my screenshot I have tested this method in Photoshop and there anchor point works good when I rotate layer and record the action.

**Comment by photopea** [comment]
I think I have fixed it. The anchor point stays fixed to the document, instead of being relative to the layer.
