### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by mcroteau** [photopea/photopea#4959]
What you have done is out of this World! I can't thank you enough. However, I am unable to purchase. Im having problems with PayPal and the Card I used wont process. Can you set up a Patreon account? I would like to donate.
Forgive me for the unprofessionalism.
http://patreon.com.
Thank you. You are the best.
MIke

**Comment by photopea** [comment]
Thanks! I feel bad about accepting donations. I always want to give something in return.

What exactly is the problem with ordering a Premium account? There are lots of people who paid for it. It is not a subscription, it is a one-time payment.

**Comment by jointri** [comment]
@photopea You absolutely should accept donations. It may be more profitable than ads which may not always work depending on the browser. I would pay a bit just to use this, it's awesome.
