### ISSUE TITLE
Feature Request: Remove Frames from a GIF in a Certain Order

### ISSUE THREAD

**Issue by Erelynn** [photopea/photopea#4963]
I want to suggest the ability to delete frames from a GIF in a certain order. For example, I may want to delete 1 out of 6 frames from a GIF. So, if I specify that Photopea should delete 1 out of 6 frames, then it should count to 6 and delete a frame. Then from that point, it would count again to 6, and delete another frame. It should go on in this sequence until it reaches the end of the GIF.

It's best if this feature is flexible, so the user will be able to choose the sequence that the frames will be removed. For example, another person might want to remove 1 out of 4 frames, and another person may want to remove 1 out of 3 frames, and so on.

The result of this feature is that the GIF will become faster, but also the file size will be reduced. My main reason for wanting this feature is to reduce the size of the GIF without compromising its content. I'm often having trouble with GIFs being too large and websites not accepting them because the file size is too big. I've tried reducing the quality and dimensions of the GIF, but it's usually not enough to reduce the file size to the degree needed to upload it on websites. The best solution that I've come across is the feature that I'm suggesting here, where the size would be reduced by removing a frame out of a certain number of frames. I like this solution the best for decreasing GIF size because it still allows me to keep the contents of the GIF the same, so I won't have to cut the GIF short by removing parts that I don't want to remove.

Thank you for reading my feature suggestion :)

**Comment by photopea** [comment]
I guess you have too many frames, that you are too lazy to do it by hand :) Also, I guess your frames have all the same delay (each frame is displayed for the same duration of time).

Maybe we could put it at the GIF export. You can set "keep 80% of frames", which will delete one in 6 frames. We could compare each two consecutive frames, and delete only those, which are similar to the previous or to the next frame

**Comment by Erelynn** [comment]
> I guess you have too many frames, that you are too lazy to do it by hand :) Also, I guess your frames have all the same delay (each frame is displayed for the same duration of time).
> 
> Maybe we could put it at the GIF export. You can set "keep 80% of frames", which will delete one in 6 frames. We could compare each two consecutive frames, and delete only those, which are similar to the previous or to the next frame. What do you think?

Thank you for your reply! It would definitely help to have some automatic way to remove frames because a GIF often has a lot of frames, and it would be very inconvenient & inaccurate to delete them in a specific order by hand.

I think your idea to delete frames that are similar is interesting, but it might not necessarily work for all animations. It may pose some issues with the flow of the animation.

For example, if I'm creating a GIF animation with GIPHY from a video clip, some parts of the animation will have more frames that look similar to one another. The reason they look similar is that the action was moving slower in the video on those parts. Although all frames have the same delay, some parts of the animation will give the appearance of slower action by having a similar image repeating on multiple consecutive frames, while other parts will depict faster action by containing more variation in the frames that are next to each other. This is something I would want to maintain in the animation, because it's the natural flow that things are happening in the video. Some parts will have slower action, and some parts will have faster action. For this reason, I prefer if the frames are removed in an exact order (e.g., 1 out of 6 frames, 1 out of 4 frames, etc), because this will speed up the animation uniformly, while also maintaining the natural flow of the action from the original video.

I hope my explanation makes sense :)

Thanks again!

**Comment by photopea** [comment]
I think you did not understand me well.

If there are two similar frames shown for 100ms each, we replace them with one frame that is shown for 200ms. To the timing will remain the same. Unless you need a GIF with a constant framerate.

**Comment by Erelynn** [comment]
> I think you did not understand me well.
> 
> If there are two similar frames shown for 100ms each, we replace them with one frame that is shown for 200ms. To the timing will remain the same. Unless you need a GIF with a constant framerate.

To be honest, I'm not sure how the mechanics of it would work. When uploading to social media sites and forums, I don't know if it would make a difference whether the GIF has a constant frame-rate or if the frame rate differs. I'm sure you would know more about what will work best. The only thing I can say is that I usually create GIFs from videos, using GIPHY. As long as the GIF animation maintains the same flow as the video clip, then it should be fine. It's okay if the GIF becomes faster due to the reduced frame rate, as long as that speed is applied uniformly to the entire GIF. I'm sure you'd be more familiar than I am on the best way to accomplish this. So, just do whatever you feel is best. I'd think anything is fine as long as I will have the flexibility to reduce the file size of my GIF as much as is needed to upload to specific websites, and as long as the content of the GIF remains the same.

Thank you for considering my suggestion :)

**Comment by photopea** [comment]
When you export a GIF, there is a "Reduce Frames" slider now, which you can set to 50% to drop half of frames :)
