### ISSUE TITLE
Feature Request: Combine Multiple GIF Files into One

### ISSUE THREAD

**Issue by Erelynn** [photopea/photopea#4964]
I would like to build an animated GIF by combining 2 or more GIFs together into 1 file. I don't mean overlaying them on top of each other like stickers. What I mean is putting them together as one GIF, so they play one after the other.

These are some examples if you want to get a better idea of what I'm suggesting:

This example shows how to merge GIFs in Photoshop (using Photoshop's timeline).
https://www.youtube.com/watch?v=_bbWfXS9NtQ

This example shows a GIF builder app that performs the function of combining several GIFs together.
https://www.youtube.com/watch?v=6SHLo-Jbp6U

Since GIFs often come in different dimensions, there need to be a few options to correct this when the GIFs are joined together. There should be an option to add a background color (such as black) to fill in the parts that are left empty by a GIF that isn't long enough or wide enough to be a perfect match to the dimensions of other GIFs in the compilation. While the size differences between GIFs will be resolved by stretching a GIF to be a similar size as other GIFs, there still needs to be a background color to cover the parts that are left empty due to the differences in dimensions. Additionally, there should also be a second option to partially crop out the GIFs whose dimensions need to be adjusted to match those of other GIFs. In this case, the GIF would be zoomed in until it fully fits within the frame, and any parts that fall outside of the frame would be cropped out. Not everyone will want to crop the GIFs because that may cut out important parts, but it's still a useful option that would work well for certain GIFs. A user may choose one of these 2 options, depending on their needs. This process should be automatic, so that results can be achieved quickly with only a few changes to the settings.

Thank you for reading my feature suggestion :)

**Comment by photopea** [comment]
I think you can do it already by copying layers from one document into another document.

I think you should learn the main animation mechanism, that is described here: https://www.photopea.com/learn/animations . Once you understand it, everything should be clear :)
