### ISSUE TITLE
Photopea giving the error "unknown file type 'Meth'" when I try to upload a .png file to edit. 

### ISSUE THREAD

**Issue by mejoscenga** [photopea/photopea#4968]
Photopea is giving the error "unknown file format 'Meth'" when I try to upload a .png file to edit. Photopea cannot open a png from computer. I have tried with multiple png files, on Microsoft Edge and Mozilla Firefox, and tried saving the png a few ways before uploading in case how I saved it on the computer first would help. I am using Windows 11 in case that is partly the cause, and the png files have transparency.

**Comment by photopea** [comment]
Are you able to open your PNG file in any other image viewer? Does it happen for only one file, or for several different PNG files? Did you try to run Photopea with no extensions (or in the Incognito mode)?

**Comment by rexxa6** [comment]
it actually doesn't work only for 1 file i tried to open 3 file different ones and it's still error

**Comment by photopea** [comment]
Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
