### ISSUE TITLE
The letter å

### ISSUE THREAD

**Issue by Gafral** [photopea/photopea#4969]
I can suddenly not use the letter å. The third last letter in the swedish alfabet.
It works in all other programs, like here as you can sea, so my keyboard works fine.
ä and ö which is the two last letter in the swedish alfabet also works fine.

**Comment by photopea** [comment]
Were you able to type it in Photopea in the past?

**Comment by Gafral** [comment]
Yes.

mån 5 sep. 2022 kl. 11:05 skrev Photopea ***@***.***>:

**Comment by photopea** [comment]
How exactly do you type å on a swedish keyboard?

**Comment by Gafral** [comment]
we have a special key for it.

Den mån 5 sep. 2022 kl 12:43 skrev Photopea ***@***.***>:

**Comment by Gafral** [comment]
I did just discover that it seems to be only with the cicle fonts.
I have tested around twenty others and they all work perfectly.
Sorry to have troubled you.I will just have to use another font. Problem
solved.

Den mån 5 sep. 2022 kl 13:30 skrev Lasse Fagerberg ***@***.***

**Comment by photopea** [comment]
I just switched my keyboard to Swedish and I can type å.

In the font filter, enable the "Latin-1" filter https://en.wikipedia.org/wiki/Latin-1_Supplement
![image (1)](https://user-images.githubusercontent.com/15955558/188443483-03ceb330-066c-4b43-8aa1-23366b4e3f89.png)
