### ISSUE TITLE
Image Not Save

### ISSUE THREAD

**Issue by vimalbhatasana** [photopea/photopea#4970]
![image](https://user-images.githubusercontent.com/76198601/188592580-386970a1-f087-404b-a88a-021e0dcbcb5d.png)

When saving the image by resizing it, the image is not saved.

**Comment by photopea** [comment]
What is "saving the image by resizing it"? Did you try to disable all your browser extensions?

**Comment by photopea** [comment]
I have to close it because of lack of details.
