### ISSUE TITLE
[Feature request] File > Automate > Convert Formats > SVG format support

### ISSUE THREAD

**Issue by JasperCyan** [photopea/photopea#4972]
Hello, 

Is it possible that this can be supported?

File > Automate > Convert Formats > Choose Format Dropdown > SVG

Saves all source images as SVG file. 

I am trying to bulk convert PDF > SVG.

**Comment by photopea** [comment]
Did you try to convert a PDF into an SVG in Photopea manually? Are you sure this conversion gives you what you want?

**Comment by JasperCyan** [comment]
> Did you try to convert a PDF into an SVG in Photopea manually? Are you sure this conversion gives you what you want?

Yes it works very well, in fact bettter then normal Photoshop/AI export SVG since text layers are much better supported. (Export as > SVG)

**Comment by JasperCyan** [comment]
Photopea is one of the only tools that correctly formats text inside the exported SVG files.

Is it possible to add this on a technical level or is it not possible at all? SVG format is a bit more tricky then standard image formats. 

Having a macroscript/automation is a work around, but since it will have to load the file in the editor each time before exporting as SVG it would be time consuming, whereas the convert formats feature is almost instant and does not involve editor loading.

**Comment by photopea** [comment]
It is implemented now. The input files can be any format. The output files can be any raster format or SVG or PDF.

There is just one problem: if the input file contains text layers, and the necessary fonts are not loaded when you click "Export", text will be missing in raster files, the conversion to SVG will crash.

You can open your PDF in Photopea in a regular way to make it load fonts, before the batch conversion.

**Comment by MichalSZZ** [comment]
> There is just one problem: if the input file contains text layers, and the necessary fonts are not loaded when you click "Export", text will be missing in raster files, the conversion to SVG will crash.

Is there any information about missing fonts in the GUI when the user uploads his files? A little warning message about the problem, what font is missing, and what to do to keep good results of conversion. Sorry but I can't check this right now, but I think that is very important.

**Comment by photopea** [comment]
When you open any document, there are "bubbles" at the top saying "Arial -> DejaVu Sans", etc. You can see these messages in a web console, too.

When you select a text layer and the font is missing, there is "-" in front of the name of a font (so "- Arial" instead of "Arial")
