### ISSUE TITLE
Unable to open 2GB Sketch file on Photopea

### ISSUE THREAD

**Issue by heywaiiz** [photopea/photopea#4973]
Hi! I'm trying to open a Photopea sketch file but it's just loading forever. Can I ask for help please? The file can be found here

**Comment by photopea** [comment]
You usually need 10x more free RAM than the size of your Sketch file. So you need 20 GB of RAM in your case.

Also, Google Chrome does not allow to use more than 8 GB of RAM on some platforms.

**Comment by heywaiiz** [comment]
Got it - thanks admin!
