### ISSUE TITLE
On Linux, Photopea not remembering location of files to be edited

### ISSUE THREAD

**Issue by wbrells** [photopea/photopea#4974]
I usually edit a number of photos during a single session. On Windows, Photopea remembers the directory where those photos are located so it is easy to open/edit/export photos one after another. On Linux (MX Linux 21.2 specifically) Photopea keeps going back to showing a directory of **Recent** files rather than the directory containing the photos that I'm editing!

**Question:** Is there some setting that will make Photopea automatically return to the directory containing the just-edited photo? The current situation really slows down the editing process since I have to keep moving through several levels of directories in order to locate the next file to edit! BTW MX Linux uses the **Thunar** file manager in case that is significant.

Thanks,
Wayne

**Comment by photopea** [comment]
Are you talking about a situation, when a website is allowed to rewrite file on your hard drive directly, without any Download dialog in between?

This web standard is supported only in the latest Chrome, Edge and Opera. It is not available in Safari or Firefox yet. Also, some of your browser extensions could block it, in order to prevent websites from writing viruses to your hard drive.

**Comment by wbrells** [comment]
My normal editing steps involve:
1) Starting Photopea under Chrome
2) Selecting Open From Computer
3) Navigating to the directory containing the first JPEG file that I'd like to edit
4) Selecting that file and clicking on Open
5) Editing that file as needed
6) Clicking on File > Export as > JPG
7) Click on Save which (as desired) comes up in the directory containing the ORIGINAL JPEG file
8) Click on Save which saves the updated photo as a JPG file as desired

NOW THE PROBLEM: I click on File > Open... which takes me to a listing of recently accessed files rather than to the directory containing the JPEG files that I'm editing! I then have to navigate back to the directory containing the JPEG files so I can continue editing. THIS DOES NOT HAPPEN UNDER WINDOWS where I'm immediately taken to the original directory.

I really hope there is some way to get Photopea under Linux to act the way it way is does under Windows. This will save me a lot of time...

Thanks,

Wayne

**Comment by photopea** [comment]
Oh, I see. These things are completely up to your web browser. A website has absolutely no idea what is on your hard drive, what folders are there. Are you using any browser extensions? Maybe they are doing this. Could you disable them all? Otherwise, report it as a bug to the creators of your browser.

**Comment by wbrells** [comment]
It does appear that my problem is caused by the way the Chrome browser under Linux decides what directory to open. I've tried using Firefox and with a slight Settings change it seems to handle the opening and closing of directories as I would prefer. By default, Firefox automatically saved my Exported JPG files in the Downloads directory without asking. HOWEVER if I go to Settings in Firefox and, under Files and Applications > Downloads, check the box for "Always ask you where to save files", the save and open directories then remain correct (i.e. the directory containing the files that I'm editing).  Note that the "Save files to" box still shows "Downloads", but fortunately that doesn't seem to really be the case when the above-mentioned box is checked.

Unfortunately, I can't find any "Settings" in Chrome that will fix my Directories problem. I'd prefer to use Chrome since Firefox doesn't support Progressive Web Apps (PWAs) such as Photopea, but that doesn't really seem to be practical...

Thanks for pointing me to the source of my problem,

Wayne

**Comment by photopea** [comment]
Yeah, browsers still need a lot of development to work as we want them to work. I really recommend you to report it.

Also, try using the Storage. At Photopea.com , click "This Device" on the left, and let Photopea access a certain folder in your computer.
