### ISSUE TITLE
LaTeX editor plugin

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#4976]
Somebody asked for the Latex editor: https://www.reddit.com/r/photopea/comments/x9c5kj/is_there_a_way_to_write_latex_text_in_photopea/

There are lots of services, which convert a string with latex into a PNG / SVG, like https://www.mathjax.org/

Latex Plugin would be a great idea! We could store the original latex source in a layer name, to allow editing the Latex layer in the future.

@hxim does it sound interesting to you? :)

**Comment by hxim** [comment]
@photopea Yes, sounds interesting. I will look into it when I have some time.

**Comment by hxim** [comment]
I added the plugin as "MathJax LaTeX Editor" to Window - Plugins. Please let me know if something is not working.

**Comment by photopea** [comment]
Wow, man that is amazing! You are amazing! :) 

I renamed it to simply "LaTeX Editor" (Mathjax is still in the description), is it ok? I think that looks nicer.

**Comment by hxim** [comment]
> I renamed it to simply "LaTeX Editor" (Mathjax is still in the description), is it ok? I think that looks nicer.
Yes, sure it is ok :)
