### ISSUE TITLE
Ad blocker detected badly

### ISSUE THREAD

**Issue by Dinophox** [photopea/photopea#4977]
I'm allowing all website to show ads, and I like to support the products that deserve it. But the app constantly says I'm using ad blocker even though I'm not. 
I love your product, and I'm allowing ads to show, but the pop-up always comes up. Not sure if it's possible to fix this.

**Comment by photopea** [comment]
Why do you think you are not using an ad blocker? Could you for example try to disable all your browser extensions and try it again?

Many ad blockers lie to users, they are blocking ads while saying they are not blocking ads.

**Comment by Dinophox** [comment]
I see all the ads that I see when the ad blocker is completely disabled. I don't see the point, why would the Chrome extension lie about showing or not showing the ads.

**Comment by photopea** [comment]
But did you try to use Photopea with all extensions disabled? Not of users don't know what their extensions do

**Comment by Dinophox** [comment]
Yes, and it worked, but the problem is that I have to allow the ad blocker on every page. 
I just want it to recognize that I'm not using it. All the other pages are working fine with exclusion of their pages.

**Comment by photopea** [comment]
Web pages do not know what extensions is the user using. We just check if the domain of our ad partner is accessible. If the domain is blocked, we consider it to be ad blocking. So just stop blocking it and the ads will work.

**Comment by Dinophox** [comment]
<img width="285" alt="Screenshot 2022-09-09 at 16 27 47" src="https://user-images.githubusercontent.com/28341951/189373438-95edff29-bdd3-4a15-adc0-1b38f9375a64.png">
Ok. Here is the screenshot. If it's ok to be like this, I'm fine with this

**Comment by photopea** [comment]
Once we detect an ad blocker, we show links tor my games, which I made before making Photopea (that is what you see). I dont get any money when you play my games, but I hope you have fun :D It also feels nice when someone plays my game :)

So yes, you are not contributing financially in any way. But for now, we tolerate people who block ads, so it is fine :)

**Comment by Dinophox** [comment]
I would like to contribute if it's a fair amount. If I were you, I would make a cloud storage for files in Photopea that would be accessible anywhere once I sign up. That would be a cool feature to have. There are many ways how to grow it financially. 

But I'm not really blocking ads because once I turn it on it shows nothing at all.

**Comment by photopea** [comment]
We are planning to introduce a cloud storage next week!

What you "turn on" and "nothing at all"? If you open Photopea in the Incognito mode (with no extensions), ads should work well.

**Comment by Dinophox** [comment]
That's great news, congrats!
When I fully turn on the ad blocker, I see no ads, nothing. Just the empty sidebar.

**Comment by photopea** [comment]
That is weird. Ads are added 3 seconds after Photopea is loaded. Did you wait for 3 seconds?

What web browser are you using?

**Comment by Dinophox** [comment]
Chrome.

**Comment by photopea** [comment]
Could you show me a screenshot of what you see at Photopea.com after having it opened for 10 seconds in the Incognito mode?

Are you sure you are not using Brave or something?

**Comment by Dinophox** [comment]
In incognito and without ad blocker, I see normal ads. 
When the ad blocker is paused, I see your games.
When the ad blocker is on, I see nothing at all, just an empty sidebar.

**Comment by photopea** [comment]
So you see a proof, that when you tell your adblocker to "pause" (whatever it means), it is still blocking ads (otherwise, a website would not be able to detect it).

It is clearly a bug in your ad blocker. Did you report it? Did you try other adblockers?

**Comment by Dinophox** [comment]
I don't see it as a bug because on all the other website I see pretty much all the ads. Also, it blocks ads on YouTube.
The other day I disable it and couldn't watch YouTube because of the amount of ads coming through. 
I don't see a bug here. Maybe it is still blocking something, but for sure 90% of stuff is available. 
If I were you, I would allow normal ads to be displayed when ad blocker is detected. It still would show ads from Google, and so you could earn some revenue. It's only my opinion.

**Comment by photopea** [comment]
You never told us, what ad blocker you are using.

If you are using https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom  , please, switch to AdBlock Plus, or any other adblocker. They can be truly disabled for one website only.

**Comment by Dinophox** [comment]
Yeah, good point. I just changed it to Adguard. I liked it more for a change.

Now it shows the ads when I turn it off. 

Maybe write a <paragraph> so people not to use that particular ad blocker in case they want to contribute
