### ISSUE TITLE
File not saving

### ISSUE THREAD

**Issue by raabe-ctrl** [photopea/photopea#4979]
Ctrl + S doesn't work anymore, the message "Saving..." appears but the "*" still there, as a sign the file has not been updated. I have lost a lot of work because of it. Please help me

**Comment by photopea** [comment]
Could you record a short video of you opening Photopea.com which ends with you not able to save?

I need to see what exactly do you do, because saving always works in my case :(

**Comment by raabe-ctrl** [comment]
it's working again... thank you so much

**Comment by photopea** [comment]
But I did not do anything :(
