### ISSUE TITLE
Click and drag at the eyeball column in layers panel to toggle muti layers at once

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#498]
In photoshop you can quick toggle visibility of multiple neighboring layers by click and drag on the eyeball column in the layers panel.
This is a good feature to have

**Comment by photopea** [comment]
It was implemented.

**Comment by hgs54371** [comment]
It worked in firefox,

But now in safari mac, nothing happens when click on the eyeball

**Comment by photopea** [comment]
When you press the mouse on the eyeball, the layer should be hidden (i.e. before releasing the mouse). What exactly happens in Safari?

**Comment by hgs54371** [comment]
Just like I said, nothing happened, as if you click in the blank area

**Comment by photopea** [comment]
Ok sorry for that. It should work in Safari now.
