### ISSUE TITLE
Font Glyph view - display width(right edge) of spaces or all glyph

### ISSUE THREAD

**Issue by Dimon-II** [photopea/photopea#4980]
When choosing standard non-breaking spaces and special spaces in an icon font, it's useful to see their size. I also want to change the color of the background for white glyphs or show transparency with a checkerboard.
![image](https://user-images.githubusercontent.com/29166758/189524756-03b2ddb9-cd41-45aa-a15f-f772c38f596a.png)
![image](https://user-images.githubusercontent.com/29166758/189524991-56af0142-0b79-4ea2-8486-ba2422a59eb4.png)

**Comment by photopea** [comment]
I have implemented it! Empty characters have a green line, which shows how much space that character occupies.
