### ISSUE TITLE
Не закрывается приложение

### ISSUE THREAD

**Issue by ma-pda** [photopea/photopea#4981]
Добрый день.
Приложение понравилось и все же до фотошопа немного надо доработать. В частности мне лично часто приходится использовать инструмент "исправление или дефоормация перспективы" а тут ее нет. Ну и еще проблема - приложение крестиком закрыть не получается.

**Comment by photopea** [comment]
Hi, we do not have any app. Photopea.com is a website and you should use it in a web browser.

Ask the person who made your app to fix it (we did not make it).
