### ISSUE TITLE
Offset cursor for mobile users to make it easy to brush or erase etc 

### ISSUE THREAD

**Issue by Shareef101** [photopea/photopea#4982]
There should be an inapp offset cursor because finger blocks the screen while using brush or erasing or edge defining. So there should be an onscreen touchpad and can add right and left click button

**Comment by photopea** [comment]
I have implemented it! Go to Edit - Preferences, you can set the cursor offset there.

It is applied to all tools. Or do you want it to apply only to the brushy tools?

Sadly, we can not show you where your cursor is, before you touch the screen. Have you thought about buying a stylus, or an external mouse instead?
