### ISSUE TITLE
Navigator panel not showing any of the image

### ISSUE THREAD

**Issue by MsSamp** [photopea/photopea#4983]
I can move around the image and the red box outline is present, however the image only shows initially; then it disappears. I have tried this in a regular browser as well as in incognito mode. I will attach what it looks like before I actively use the Navigator and immediately after clicking into the panel.
![before](https://user-images.githubusercontent.com/91342434/189542037-5f8cb45c-0953-4197-8777-ec7a0fa21f6f.png)
![using the navigator panel slider image disappears](https://user-images.githubusercontent.com/91342434/189542056-4823ebc6-f32b-4a85-b7c0-6c4c456a6f4f.png)

**Comment by photopea** [comment]
This is a bug in Google Chrome. It works perfectly well in Firefox or Safari. I have reported it on the 1st of August: https://bugs.chromium.org/p/chromium/issues/detail?id=1348939

I modified my code a bit, so that it overcomes this bug.
