### ISSUE TITLE
Cannot reenable WebGL

### ISSUE THREAD

**Issue by yikuansun** [photopea/photopea#4984]
The "Use WebGL" menuitem seems to only be able to disable WebGL, but not reenable it.

**Comment by photopea** [comment]
When you open Photopea.com , WebGL is always enabled (if available). And you can enable / disable it.

If it is not available, it is disabled, and you can not enable it.

Could you tell me what should I do to see the bug myself? I can enable and disable it.

**Comment by yikuansun** [comment]
I see. I suppose what happened to me is that when I tried to render too high a value with the Maximum filter, WebGL became no longer available (hence I couldn't enable it again).
Even after I removed the maximum filter, though, I still couldn't bring back WebGL. How do you check if WebGL is unavailable?

**Comment by photopea** [comment]
I have no idea what you are doing. WebGL is unavailable, if you open www.Photopea.com and press More, and the "Use WebGL" is disabled

**Comment by yikuansun** [comment]
It happens when I use the Maximum filter and set the value too high, for example to 41 px. Photopea disabled WebGL automatically, and whenever I try to check "Use WebGL" it keeps saying "Disabling WebGL."
How does your code check if WebGL is unavailable? Does it check every time you press "Use WebGL"?

**Comment by photopea** [comment]
Changing the filter options from one value to another should never disable WebGL. That is definitely  a bug.

So you see a message Disabling WebGL when you move the Raidus slider?

**Comment by yikuansun** [comment]
Yup. It works fine with low values, but around 20px it crashes for a moment, then disables WebGL.
The same happens when I input a high number into the text input field instead of the slider.

**Comment by photopea** [comment]
I think Chrome kills a WebGL process, if it is taking more than 2 seconds.

Is your WebGL hadrware-accelerated? You can see it in about://gpu . What is the resolution of your image? It takes longer for large resolutions.

**Comment by yikuansun** [comment]
> I think Chrome kills a WebGL process, if it is taking more than 2 seconds.

That makes more sense. My WebGL is hardware-accelerated. I usually work with images at least 1920x1080, so it would make sense that the process would take a bit of time. Nor sure why Chrome kills it though. Am I confused here? I was under the impression that WebGL was faster than Context 2D. Even if I'm wrong, isn't it be extremely inefficient to kill a process only to re-run it with a different method?

**Comment by photopea** [comment]
There are Minimum, Maximum and the Surface Blur implemented on the GPU. It performs R x R x 4 operations per each pixel (R = radius). The disadvantage is, that it takes more time when you increase the Radius.

I have implemented a brand new Maximum and Minimum on the CPU (for the square shape)! It is very fast (4 operations per pixel) and takes the same time, no matter what the Radius is!

Photopea will still use the GPU for small Radiuses, but for a large Radius, the fast CPU version will be used :) You should not be afraid of large Radiuses anymore.

**Comment by yikuansun** [comment]
Awesome, thanks!!
