### ISSUE TITLE
[Feature request] desktop app

### ISSUE THREAD

**Issue by MrInternetGitHub** [photopea/photopea#4985]
it will be cool if there was a desktop app that I could open when I'm not connected to the internet

**Comment by photopea** [comment]
You should be able to open www.Photopea.com in your browser when you are not connected to the internet. Can you try it and tell us if it works?

**Comment by bzimm3** [comment]
I was able to download it on my PC, but the option is grayed out on my Mac.

**Comment by photopea** [comment]
the "Install Photopea" works only in Chrome and Edge. Other borwsers did not implement it yet.
