### ISSUE TITLE
Artboards not working

### ISSUE THREAD

**Issue by skrevat** [photopea/photopea#4986]
Covering my bases here, cross posted from reddit --

So I'm working on formatting a book (okay, a journal) on photopea and two days ago, the artboards were working pretty seamlessly. Yesterday, a problem started where there seems to be an off by one error whenever I tried to `Duplicate Into...` -- I'd select duplicate into artboard 3, and it would duplicate into artboard 4. Annoying, but I rolled with it. Now I'm trying to export, where each artboard should export into its own PDF, and instead there's just one big PDF with a birds eye view of the artboards. Anyone know how to fix this? Thanks!

**Comment by skrevat** [comment]
Ok, in case anyone else is interested, here's what the problem seems to be...at least with the exporting issue -

The artboards I were using were initially created by the "New Project" option in the "Duplicate Into" menu. It seems that these projects, while having the UX of an artboard, was not marked as at artboard on, like, at exporting level. Creating a new project that was explicitly an artboard, duplicating into that, and attempting to export worked. Yay!

**Comment by photopea** [comment]
I am afraid I do not understand.

Could you tell me, what should I do after opening www.Photopea.com, to see the bug myself?

**Comment by skrevat** [comment]
Open a new artboart.
using click - shift - click, select multiple artboards/folders
right click, select Duplicate Into
For "Destination" select "New Project"
Go to the new project
File > Export as > PDF
Instead of a bunch of individual pages, the whole artboard is trying to print (see attached picture)
<img width="516" alt="Screen Shot 2022-09-12 at 4 01 28 PM" src="https://user-images.githubusercontent.com/6656062/189773002-32f7af68-88a0-4da4-bd63-5905b141e413.png">

**Comment by photopea** [comment]
What is "open a new artboard"? Do you mean a new document with one empty artboard? How can I select multiple artboards in a document with one?

**Comment by photopea** [comment]
I think I undrestand now.

A document is exported as PDF pages ONLY IF every layer is in some artboard.

If you duplicate into a new document, such document has an empty backgorund layer, that is not in any artboard. You just need to delete that layer.
