### ISSUE TITLE
Run Actions On Multiple Images

### ISSUE THREAD

**Issue by Abystus** [photopea/photopea#4987]
I have several images that have outlines/halos on them that I would like to remove. I am able to use the defringe layer option and it works perfectly, but it is very tedious to do each image individually, save, open the next one, etc.... Is there a way we can get a bulk way to process several images with this feature similar to the bulk file converter to where all could be processed and zipped up for download? Any help is appreciated.

**Comment by photopea** [comment]
Do you know a way how to do it in some other software? You can not do it in Photopea now, but maybe I could come up with a solution (and make it similar to some other solution, to avoid reinventing the wheel).

@MichalSZZ do you have any ideas?

**Comment by Abystus** [comment]
@photopea I would think it could live under the automate option you have already. Automate > Defrige (opens a select file/files dialog like the converter does, and options related to the defringe that would be applied to all files selected. Once the operation is complete it would zip all files and download like the converter does.

**Comment by MichalSZZ** [comment]
In Photoshop you can record an action and then use this action in bulk conversion for whole catalog. In this action should to be record save/export step too.
I write now from memory but I can check it later if you wish to.
