### ISSUE TITLE
Type Tool Inactive

### ISSUE THREAD

**Issue by fsalvat0** [photopea/photopea#4988]
I have opened and closed and rebooted. For whatever reason, the type tool in Photopea is not engaging. I can't even select it. I use this tool daily and need some help with this on the fly. Thanks

**Comment by photopea** [comment]
Hi, could you try some of these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by fsalvat0** [comment]
As soon as the Windows update has finished I will try that link

**Comment by fsalvat0** [comment]
It appears to be trouble with an extension because when I use an incognito page the type tool functions. I use them so I have to have them. How do I rectify this in a regular window?

**Comment by photopea** [comment]
What do you mean by rectify? If you use an extension, which breaks Photopea, you should ask the creators of your extension to fix it.

**Comment by photopea** [comment]
I have to close it because of lack of details.
