### ISSUE TITLE
When grouping layers above a group, sometimes it got nested in the said group after grouped themselves.

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#499]
When grouping something(cmd-g), the new grouped folder sometimes end up being in the below group, have to drag it out, which is an extra step

**Comment by hgs54371** [comment]
And I also found this weird behavior that the new grouped folder jumps down 2 steps in the layers panel when no other folder exist.

**Comment by hgs54371** [comment]
Yes, the real behavior is that the newly grouped folder will jump down 2 step in layers panel, and when there's another folder below, it will jump in.

**Comment by photopea** [comment]
I think it was fixed.
