### ISSUE TITLE
Problem importing .fig Files

### ISSUE THREAD

**Issue by jrgadot421** [photopea/photopea#4990]
Just recently Figma updated their .fig file structure and now there's a problem importing .fig into Photopea

**Comment by jrgadot421** [comment]
These are some of the Console Errors I encoutered while importing .fig files:
![image](https://user-images.githubusercontent.com/113568511/190388821-4219a37f-ed73-419a-bb48-6b555f36d8bf.png)

**Comment by photopea** [comment]
Hi, could you send me your FIG file to support@photopea.com ?

**Comment by jrgadot421** [comment]
Hi, I have sent you an email with subject line "Report Problem #4990 (Problem importing .fig Files)".

**Comment by photopea** [comment]
That is really interesting. I have never seen a FIG file like this. How did you get it? Was it exported right from Figma?

I am trying to export FIG files from a current Figma, and they all work well in Photopea. I loaded your FIG to Figma, and exported back as a FIG, and that new FIG works in Photopea, too.

**Comment by goodmanius** [comment]
Since today , any layouts in the format have stopped opening .fig. What is the problem? Tell me what to do, I urgently need to convert a layout from figma to psd. All raster elements open separately from the layout

**Comment by photopea** [comment]
We have implemented the support for the new Figma format. Please, try it again. Let me know if it works.
