### ISSUE TITLE
SmartObject transform is not a true 'nearest neighbour'

### ISSUE THREAD

**Issue by jeancallisti** [photopea/photopea#4991]
**Scenario :** 
- Create new empty image 1500x1500px with a white background
- Create a new layer
- Using the pencil tool (i.e. no softening of any kind) draw a big blue shape in the layer
- Zoom in to double check that all pixels of that layer are either fully blue or fully transparent
- Convert the layer to a SmartObject
- Using the transform controls, resize the smart object to a tiny size : 10x10px
- In the top bar, make sure you select "nearest neighbour" as the re-scale algorithm, and apply the changes (tick box next to it)
-  Now, zoom in to see the tiny shape

**Expected ( good) : the shape from the smart object is displayed with no smoothing whatsoever** (i.e. all pixels of the shape are rendered either fully blue or fully white). That's expected because because there was no smoothing inside the smart object and no smoothing during rescale.
**Observed (bad) : The shape has some smoothing.** Some pixels on the outline of the shape appear not fully opaque, i.e. they are rendered in lighter shades of blue against the white background.

![image](https://user-images.githubusercontent.com/1881493/190400483-94669f6f-b29a-49c9-8521-fe10d6ca1066.png)

**Comment by photopea** [comment]
Sadly, we are restricted by the PSD format (our main format), where a smart object can not have a nearest-neighbor interpolation :( So no PSD editor can offer this feature.

Please, rasterize your object into a regular layer to use the NN interpolation.

**Comment by photopea** [comment]
I have added the option into Edit - Preferences, where you can set the interpolation method for Smart Objects.
