### ISSUE TITLE
Brush outline not showing up.

### ISSUE THREAD

**Issue by DrBorlon1** [photopea/photopea#4993]
Hello, I've been using Photopea for a while now, and I have had no problems with it, but just recently the brush outline has started not to show up anymore. This makes it hard to see what size my brush is, and I have to adjust it multiple times to get it right because I cannot see it.

**Comment by photopea** [comment]
Hi, try these steps: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by JazzMage** [comment]
its capslock that turns it on and off
