### ISSUE TITLE
Raster mask does not appear in SVG

### ISSUE THREAD

**Issue by SchwaOtt** [photopea/photopea#4995]
Hello Ivan,

As I wrote in the title, I have a raster mask in my project and it doesn't appear in SVG export. In PNG is right. Could you help me, please? Is there an issue, or something missing?

THX.

![image](https://user-images.githubusercontent.com/34573380/190691705-d631b77d-41c0-4b6f-9450-ec82add570a1.png)
![image](https://user-images.githubusercontent.com/34573380/190692957-b0ffe556-5a3d-47ad-8ea5-133c2834c76f.png)

**Comment by photopea** [comment]
Can SVG files have raster masks? I think raster masks are impossible in SVG files, just like adjustment layers, etc.

**Comment by SchwaOtt** [comment]
Ok, I see. I thought that the tick on "add raster graphics" is "converting" masks.

Is there a solution, or any function to this, or should I not use a mask if I want SVG?

**Comment by photopea** [comment]
Have you tried to add a vector mask instead?

**Comment by SchwaOtt** [comment]
Not, my first version was a simple shape. The vector mask will be working?

**Comment by MichalSZZ** [comment]
Yes. Vector masks will work in SVG.
If you don't know how to do it like you did your raster mask, try to click with CTRL button on yoyr raster mask. It should load selection. Then open path panel and there at the bottom should to be an icon to convert selection to vector path.

**Comment by SchwaOtt** [comment]
@MichalSZZ Do you think the "Selection to Path" button? Ok, I pressed... Now:

![image](https://user-images.githubusercontent.com/34573380/190862872-c7a9b454-fbdb-441c-b221-c03c98c8fe96.png)

How to turn this into a vector mask? Sorry, I'm not an expert.

**Comment by MichalSZZ** [comment]
Now if you have that path, go to the layers palette (if you have group for that arrow that will be ok ) and click with left mouse buttom and Ctrl in the raster mask icon. Now you should to have a vector mask from path on your folder.

**Comment by SchwaOtt** [comment]
Thanks. :) I have a Path now. 
![image](https://user-images.githubusercontent.com/34573380/190872056-28689931-e857-453b-bf3b-cf85b7f892f9.png)
And have a group for arrow with raster mask.
![image](https://user-images.githubusercontent.com/34573380/190872133-11ca6db2-3eb0-44cc-a4a5-f9945ff94f36.png)
But I cannot make vector mask from raster mask and path. Could you help me, please? And thank you very much in advance!

**Comment by MichalSZZ** [comment]
On weekend I don't turn on my computer and all that I write I write from my head as I remember it. 

Outer circle on your screenshot has a raster mask. I dont remember but vector shape maybe can not have a vector mask. Try to hit CTRL+G on that layer to group it. Delete raster mask from that layer. Go to the path panel and select duplicated path. When you switch to the layers palette you should to have blue shape visible. CTRL+D to deselect if you have some selection. Click on the folder with you layer and now (if you still see the path) click with CTRL (or ALT - I don't remember now) in the layer mask icon.

**Comment by SchwaOtt** [comment]
Ohh, happened something strange... At the first time I could do with success.
![image](https://user-images.githubusercontent.com/34573380/190973101-579287a8-9e25-42b3-81cf-61841472f8ba.png)
But it didn't work in further attempts. The vector mask is not working as I expected. Steps: Left click + Ctrl on raster mask. On Path panel, click on "Selection to Path" (Work Path). The blue shape appears, Work Path drags to "New" icon (Path 1).

As I think, here is the problem. Path 1 is empty, seemingly, but blue shape is there.
![image](https://user-images.githubusercontent.com/34573380/190983907-12f4ce8b-0b4b-43e4-b20d-db346b0a8a7e.png)

Next: On the Layers panel, grouping layer and raster mask. Delete raster mask. Click on Folder 1 and add to vector mask from Current Path.

The vector mask is empty, but the blue shape is visible.
![image](https://user-images.githubusercontent.com/34573380/190981808-e0821af3-faa9-4b4c-bdac-da9aaa3c6adb.png)
![image](https://user-images.githubusercontent.com/34573380/190981864-314ea3ed-1347-4bcd-a160-cc2d7fd7b6d7.png)

@MichalSZZ Do you have any idea? What is missing?

**Comment by MichalSZZ** [comment]
Can you share PSD file by publishing it online? File -> publish online -> PSD

**Comment by SchwaOtt** [comment]
[https://www.photopea.com/#i0Zd1CGYI](url)

As I think the reason for the issue is the large layer size (4K). When I cut out smaller area, the method is working well. What do you think?

**Comment by MichalSZZ** [comment]
I think there is a problem with Photopea as you said. The first time I added a vector mask but another time I had problems. 
That was my very fast test - I will dig into it later.

**Comment by SchwaOtt** [comment]
Ok, thank you!

**Comment by photopea** [comment]
Vector masks can not replace Raster masks, as Raster masks might contain partial transparency (while the sape in vector masks defines fully transparent and fully opaque areas).

There was a but such that the new vector mask was not active after adding. It should be fixed now.

You can add a vector mask by clicking Layer - Vector Mask - Add.

**Comment by SchwaOtt** [comment]
Thank you.
