### ISSUE TITLE
A major overhaul is needed for the UI and UX

### ISSUE THREAD

**Issue by loumizhu** [photopea/photopea#4996]
Hello 🖐🏻
I'm a long time user of many design software (from 90s era) and works with a marketing company
For collaborators who are marketers ( not designers ), I recommended using photopea to work on graphic design done by designers.
the adoption of Photopea by these collaborators has been nearly null. 
I tried to know why:
Many times they were in tight schedule and had to do some small changes in the design, and they had the source file in their hand .
These people would go on the trouble of  recreating the whole design in Canva to make that small change on the design. The problem was: the software was behaving weirdly (according to them) Resizing an element in word or powerpoint just needed to grab the handles and do it, in Photoshop you had to confirm the resizing by pressing Enter, the software is blocked unless you hit Enter and ESC ! that is insane from the point of view of a newcomer.
I have witnessed a lot of these bizarre occurrences and concluded that these people were not being lazy, but were genuinely trying to do the work, but the slight hiccups they encountered when opening some software prevented them from trying further and risking losing their valuable time. Due to tight schedules...
all of this to say: Modern UI/UX is IMPORTANT ! a lot of old software have wonky and not intuitive UI, behavior, UX , quircks .
PhotoPea has alrdy all of the modern features ( it's online, on web-browser) sharing file on the cloud is there. the software is fast. and I love the fact, it's one developer who made it.
but the UI is old, the UX need some changes
I think the photoshop UI is not suited for major use, and new designers are no longer attached to these software.
The adoption of Figma for example has been spectacular among fellows workers.

**Comment by photopea** [comment]
Do you have any specific suggestions? What would you like us to do?

**Comment by loumizhu** [comment]
thanks for your reply
If I can suggest things, there would be many small changes to make it intuitive and welcoming for new-comers:

- a share link that immediately get you the shared file opened and with authorizations to edit  (like in google docs / sheet ) Even from a different account (this way I can send a design to a colleague and he will have edit access immediately)  Have a share button in right click menu , or right top screen, https://bit.ly/3SxxXqz - https://bit.ly/3RV16fh
- The sharing should conform to all major collaboration tools. I should be able to have all the feature (who get view access , edit access, share by link ? or restricted ... ) 
- Eliminate any steps in authorizing photopea. Example: when I click google drive to access my google drive, the app shows a blank screen with a small button on top left to authorize. That's a major obstacle for a scared non designer who is not used to complicated User interfaces. he will not see it. That app should proceed to authorization page immediately (big and on the center of screen)
https://bit.ly/3Lua4O3

- Decluttering the UI, Newcomers will adopt the tool easier and veterans designers can still find their tool after opening the right menu, hold down on the tools buttons to find more tools, or use the search feature
- Default opened Palettes should be the properties -or tool options and layers
 : https://bit.ly/3qQt3ce
 
- Defaults tools should favor vector
- Transform Tool: should be active by default when selecting any element. The handle should be smaller
	Remove the need for  Confirmation (pressing enter) when transforming.
	
- Select layer: Auto-select active by default
- Publishing png is weird, not only it uses an alert window for no reason (no need to confirm)
but sometimes doesn't work  https://bit.ly/3Bsm9ib
Publish by saving on my drive and showing it only to people I want is the one to go instead of imgur

I can go for more if you let me :)

**Comment by photopea** [comment]
Thanks a lot for your feedback! :) 

- The sharing feature is at File - Publish Online - PSD, which will give you a link that opens Photopea with your document, for anyone who opens your link. Maybe we should rename "File - Publish Online" to "File - Share"? But this option shares everything publicly at a public link.

- We have teams and sharing in the PeaDrive (on the left). You need to make a Photopea account, create teams and add each other to a team.

- Sadly, Google Drive and other APIs  do not allow us to connect automatically, there must be a button click to initiate the Google Login window. But if you log in once, it stays logged in next time. I have made the button bigger.

- I am very afraid to remove / hide any tools. There are millions of people used to this layout from Photopea or Photoshop, they would be very confused. People use complex tools to do complex work. Others can use Canva.

- We will release a vector-oriented version of the editor, but Photopea should focus at raster graphics primarily.

- I changed the auto-select to be enabled by default. But transform controls are not used by many people, they prefer to enable the Free Transform manually. The transforming can be confirmed by switching to another tool or selecting another layer.

- we received many emails from people who published images to imgur "accidentally". We still receive such emails, but much less after we introduced the alert window.

**Comment by loumizhu** [comment]
Thanks for your reply and willingness to discuss this topic

- The sharing feature : The location of the feature is key. The naming too. As I mentionned, new users / novice designers / Non-Designers are missing out on this software. The reasons are often baffling from the point of view of a normal designer, but daunting to newcomers: The location of the feature, the naming , the number of clicks to get to it. Thus I think renaming it to Share might help. in the search box, it can even have hidden keywords Like publish , share, send to

- Google Drive :) The bigger centered button will get the user to click on it. If you can make the background part of the theme ( I have the dark theme, and the huge white background is screaming: i'm not part of this UI )

- Shared-Drives : Private Folder . No instructions here, nothing to do. Any new user will be put off by this thinking : this software isn't even finished . I suggest putting an authorize button and a message
like :
Connect Your Onedrive to PhotoPea
Load your Google Drive Shared Drives to PhotoPea 

  - Many people don't realize these are different cloud storage that are not part of the current tool they're using


  - The PeaDrive : (or any other drive)
  - No instructions, no actions to do, User will stop here
  - I didn't even realize I could use this, since I relied on putting my files on google drive.

- "I am very afraid to remove / hide any tools."
I think you can suggest to new user with a welcome screen if they want
Photoshop Interface
or
Simplified Interface

They do it in Blender and many other software. This will gain you a lot of new users

 - Sharing in google drive if I right-click a file I can't share it without opening it.
Even if I look in the file menu
https://bit.ly/3CqpZdq
This will definitely stop any collaborator from going Further

- We received many emails from people who published images to imgur "accidentally". We still receive such emails, but much less after we introduced the alert window.
	- I was mentioning the fact you're using the (ugly) alert window instead of nice looking alert window. It's "just" an aesthetic thing, but many new users will judge the software by first impressions and its look. Same goes for some popup window or msgs when loading. https://bit.ly/3RuSpY6 
	- I understand in some case, where you're preventing the closing of the Tab with an alert msg ( to save the document before closing ) I don't know if PhotoPea auto saves, but there is no indication of it (maybe add ad small msg top right , like they do in google docs)

**Comment by photopea** [comment]
Thanks a lot for your feedback!

- I have added the "Share" option when you right-click a document (with the Move tool).
- Storages have a big button and a big icon with a description now.
- I really dont want users to ask questions when they open Photopea for the first time. Many of them will have no idea about what a photoshop or a simplified interface means.
- What should the "Share" button in Google Drive do? Share with who? Do you mean sharing publicly through a link like this? https://www.photopea.com/#ipNO7outk.psd . What if the user edits a file in a google drive, should the link open the old version or the new version?
- I think our alert messages are beautiful and clear. I dont know what new design you have in mind.

**Comment by loumizhu** [comment]
- I really dont want users to ask questions when they open Photopea for the first time. Many of them will have no idea about what a photoshop or a simplified interface means.
Exactly, the UI should be Self explanatory. 
Yet I disagree, for new comers. Many platforms may asks some questions about the users when they first login and this doesn't make the user drop the tool. 
For photoshop users, they will choose
The welcome screen don't need to be a modal "window" locking you into choosing or not
it can be a typical welcome like the new window: where you choose from a template or a preset ....
OR it can be a small tooltip letting you know, there is two type of interface
The simpler figma like interface
the photoshop interface

- What should the "Share" button in Google Drive do? Share with who? 
Just like the google drive share button
Share with who ever you want (enter email)
choose wethere he can view it or edit it or comment ...

- Do you mean sharing publicly through a link like this? https://www.photopea.com/#ipNO7outk.psd .
 What if the user edits a file in a google drive, should the link open the old version or the new version?
If the share link gives Edit access, save on the old version
if the share link gives View Access only, no choice the new user can only save into a new copy
( just like how google drive works)

As for the suggestions, I still may suggest more if you let me ( like dropping the need to confirm when transforming )

**Comment by xan2622** [comment]
I think two interfaces are not needed. 

What I would like to see is the ability to move panels and snap them wherever the user wants, like in Photoshop (and a cookie would save the UI as it is for the next time the user re-opens Photopea). 

A simplified UI is not necessary, IMO. The current one is not that complicated to use (and very well known by Photoshop users).

**Comment by photopea** [comment]
@loumizhu are you a professional user of any image-editing software? Have you used one or more image editing apps for thousands of hours? You might be telling us how should a plane look like, while never flying a plane.

**Comment by loumizhu** [comment]
@xan2622 
I'm thinking about novice users who are not accustomed to graphic software. PhotoPea can be a great collaboration tool between professional designers and novices / clients. A simplified interface can boost the adoption of the tool by occasional users and non designers.

@photopea 
I have been using graphical software since 1999. Professionally, since 2003. I used a lot of graphic , 3D , painting software.
I'm currently working as the head of the marketing & design department inside an IT agency. We've done many types of design works (Posters, print, UI/UX, animation, Video ...). I'm also a professor in a private Design university.
From my experience working with many collaborators, including developers. Many don't even want to open Photoshop, even for a small thing like changing a title inside it. some marketers and copywriter likes design, but still have trouble navigating through photoshop interface as they only need it 10 % of their time.
I'm only thinking about making it easier for them.

I think you've done a great job with this software and hope the best for it. 
I still hope it will have a greater reach like Canva or Figma, as it has more features and capability.

thanks for your time

**Comment by photopea** [comment]
Ok, do you have any more suggestions? I am not convinced about the usefulness of the Share button which you describe. There are already many ways to share stuff in Photopea.

**Comment by photopea** [comment]
I will close it now, but we can keep discussing it.

**Comment by loumizhu** [comment]
Alright

If you're still open to discussing suggestions:
About the suggestions I mentioned
It is about making the most used features, more visible.
Sharing a design between coworkers , clients, people you work with is the most common things users will ask me for ( in my experience )
Thus making a share button visible and using similar terminology like popular tools make it easier (industry standard)

I'm not only suggesting, adding sharing to the top right of the screen
I'm suggesting make it available everywhere (File menu, Right click on file, right click on canva,top right interface, the search button) .
It is a statement to let your users know Photopea is not just photoshop on the browser, it is a  collaborative tool capable of competing with all  mainstream graphic tools.


When I search for the sharing in the search button, I don't find it. Search should include every clickable thing in the software, no ?

Ambiguity : Publish or Share . the naming can be important
Publish Online in the file Menu : I might think " I don't want  to publish this publicly, this might not be the way to share my design with someone else "

If you still think it is not useful, you can make a test and see how many times it is used.

**Comment by photopea** [comment]
I renamed "Publish online" to "Share", it can be searched now :)
