### ISSUE TITLE
Bug: Merging a folder (containing layers) shouldn't name it with the name of the first layer inside that folder

### ISSUE THREAD

**Issue by xan2622** [photopea/photopea#4997]
Merging a folder (that contains several layers) should name the newly created layer with the same name as the previous folder, and not the name of the first layer in order in that folder.

![firefox_Vwe88yy3Lx](https://user-images.githubusercontent.com/1732773/190876416-1f0fe4bd-63d0-45d5-8e44-622241a6e206.gif)

In this video, you can see that merging the "Skull" folder creates a new layer with the name "What a beautiful day".
But it would make more sense if the new layer is named "Skull" (after all, in this example, the user wanted to merge the whole folder).

**Comment by photopea** [comment]
fixed! :)
