### ISSUE TITLE
Bug: Some "layer colors" make the "eye symbols" not easily visible 

### ISSUE THREAD

**Issue by xan2622** [photopea/photopea#4998]
Depending on the "layer color" that the user chooses, it might not be easy to see if layers are visible or invisible.
Some colors make it really difficult to see the "eye" symbol.

![explorer_0nA8XPEWt0](https://user-images.githubusercontent.com/1732773/190877087-ec7c1697-4be9-42b7-81af-4293de87193c.gif)

Maybe these "eyes" could be much darker if the layer color is too bright?
Or maybe a simpler solution: just make them all much darker. 

Mock-up: 

![32052](https://user-images.githubusercontent.com/1732773/190877095-7f9e3c4c-9027-4288-b4b9-4a376fab00b5.png)

**Comment by photopea** [comment]
it should be fixed now :)

**Comment by xan2622** [comment]
Thank you. 👍
