### ISSUE TITLE
Photopea constantly crashing

### ISSUE THREAD

**Issue by GoldenTyler115** [photopea/photopea#4999]
Hello! I use photopea a lot, and I love it. It's the best editing software I've ever used that doesn't cost a crazy amount of money. I also love the fact that it's online and you don't have to download it, but it always crashes. This is what Crome says every time it crashes: 
![image](https://user-images.githubusercontent.com/106202491/190930406-d0689b72-6fb0-48cf-b09b-31e513164dfe.png)

Normally I wouldn't care, I would just go back to the site and finish my project. But it doesn't save, so I have to restart sometimes projects that I've been working on for more than an hour. How can I fix this? Thanks!

**Comment by photopea** [comment]
Is there anything specific what you do before it crashes? Can you make it crash on purpose?

**Comment by GoldenTyler115** [comment]
Nope! It just randomly happens, it gets really glitchy right before it crashes.

**Comment by photopea** [comment]
How much RAM memory do you have? Browsers often kill a website if they feel like it uses too much RAM.

**Comment by GoldenTyler115** [comment]
11.9 GB.

**Comment by photopea** [comment]
Your screenshot says "Error Code: Out of Memory". So I think it ran out of RAM. There is nothing Photopea can do about it, you simply dont have enough RAM for the kind of work you are doing.

Press Window - More - Memory to see how much RAM is each document using. Also, save your work regularly when working with large files (where there is a risk of crashing).

**Comment by GoldenTyler115** [comment]
Alright, thanks! Just a suggestion, maybe add like an auto save option if possible. Thanks, again.

**Comment by photopea** [comment]
There is an auto save message. You probably disabled it in Edit - Preferences.
