### ISSUE TITLE
Unable to open files

### ISSUE THREAD

**Issue by nkk27** [photopea/photopea#5]
Been trying to open files from my computer into photopea to edit but it won't open them (these are photoshop and AI files with extension ai or psd)
Please help

**Comment by photopea** [comment]
Hi,  there may be bug in Photopea. Can you attach one of your files in your comment? Or send it to support@photopea.com? Thank you very much. We will try to fix it as soon as possible.

**Comment by photopea** [comment]
Unable to reproduce this bug. Feel free to reopen it, if you have a problematic PSD file.
