### ISSUE TITLE
More contrast in dialog boxes telling something to user

### ISSUE THREAD

**Issue by tomasnosek** [photopea/photopea#50]
You have some dialog boxes like "this layer is not editable" user barely can see because of no contrast and very shor time to see.

**Comment by photopea** [comment]
Why do you think so? There is a white box with a black text, which is displayed for 2 seconds.
![pea](https://cloud.githubusercontent.com/assets/15955558/16433371/3193089c-3d8a-11e6-8d44-e1ffee33cf7f.png)

**Comment by tomasnosek** [comment]
Man! That's the problem :D

**Comment by photopea** [comment]
So how do you want it to look like? Bigger letters? or showing for a longer time?

**Comment by tomasnosek** [comment]
Both! :) When you want to tell something to user, you have to be sure its highly visible and this design looks as chameleon in jungle. Make a contrast. Try to use some different color of box or push it to front by using some overlay over the UI, box borders etc.

**Comment by photopea** [comment]
I made the text bigger and added a little pop-out animation.
