### ISSUE TITLE
Ability to rename the file when save out as psd / jpg

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#500]
Often times you don't come up a name for it until you're saving it out.
So the best time for naming a file would be at the save out stage.
But right now it seems like you have to do it either at the very beginning, or after it was saved out as New Project.jpg / psd

**Comment by photopea** [comment]
Hi, this depends on your browser settings. You can set your browser to ask you for a location of the saved file. You can usually enter a new name during this stage.
