### ISSUE TITLE
Stable Diffusion for PhotoPea?

### ISSUE THREAD

**Issue by nigelp** [photopea/photopea#5000]
Hi, Christian Cantrell has created a [CCX plugin for Photoshop](https://christiancantrell.com/#ai-ml) which embeds Stable Diffusion inside the program. 

Now we can install local instances of SD on Windows/Mac PCs, I wonder whether it's possible to create a plugin for Photopea which can use the local model to create art from inside Photopea?

**Comment by photopea** [comment]
These models usually are several GB in size. If Photopea downloaded it from our server to your computer, it will not be able to store it permanently (websites can not write data to your hard drive), so Photopea would have to re-download it each time you want to use it.

Do you already have a model in your computer? In that case, maybe we could use it from there.

We would also need something like https://caniuse.com/webgpu to run the model fast.

**Comment by nigelp** [comment]
>>  Do you already have a model in your computer?

Yes I do. There's a bunch of GUI versions which let you download the model
to your local computer as part of the install. That's really what I was
talking about.

**Comment by photopea** [comment]
To use that Photoshop plugin, you will need to create a DreamStudio account, and you will need to pay DreamStudio  basically for each click of the button "Dream". I can create such plugin in 2 hours.

Are you aware of this? Or do you expect that this feature  in Photopea to work for free?

**Comment by PAEz** [comment]
Or one that has a simple server you could connect to.....
https://github.com/invoke-ai/InvokeAI
I know the one @nigelp mentioned uses a server, but buggered if I know how it works.  Whereas the one I mentioned above has a very simple server to work with (but less options).

And a DreamStudio (or any of the other online APIs) would be great.  I want a free one but I know a lot of people wont care and it can be faster and not every one has the GPU needed.  I only have a 1060 so its not the quickest, but I dont care still lots o fun.

**Comment by photopea** [comment]
@nigelp I dont think there is a Photoshop plugin which can run a Stable Diffusion method for free, is there? You can not integrate a web app with a Python script, etc.

**Comment by PAEz** [comment]
@nigelp In the meantime if you want a free image editor with local SD support, try Krita with https://github.com/sddebz/stable-diffusion-krita-plugin . Seems to work great.

And Ivan if you know some python the server for the Krita plugin could prolly be altered to work well for a PP plugin as well.  Works from a http server you could work with, youd just have to add some stuff to serve/return/delete the work files as the the Krita plugin has access to that stuff through python, but the calls to SD are done through the server.

**Comment by xan2622** [comment]
The next version of Christian Cantrell's Photoshop AI plugin will allow to run the plugin locally: 
https://twitter.com/cantrell/status/1578143611153063936
https://christiancantrell.com/#ai-ml

The more I discover of these AI projects, the more I am amazed.

https://user-images.githubusercontent.com/1732773/194482836-26f65556-78bd-4683-9760-f2f8b5ed9a20.mp4

**Comment by xan2622** [comment]
Adobe is planning to extend Photoshop features with more AI tools: 
https://prototypr.io/post/adobe-ai-max-sneaks-2022

**Comment by photopea** [comment]
I have added the DALL-E image generator under Window - More - DALL-E. I added them, as they were the only ones with a publicly described API.

**Comment by xan2622** [comment]
I hope in the future, we will be able to do **inpainting** and **outpainting**.


Just a side question: Is there a reason it's located in ` Window - More - DALL-E ` and not in the Plugins window?

**Comment by JRowe47** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui
AUTOMATIC1111 might be able to partner with you to integrate SD directly into Photopea.

It'd be really easy to handle inpainting and outpainting with the existing functionality of AUTOMATIC1111's UI.

**Comment by JRowe47** [comment]
AUTOMATIC1111 Stable Diffusion web ui runs locally, so you're pulling from http://localhost:7860/ for free. It can be run on systems with as low as 2GB vram GPU, and is very performant even on lower end hardware.

**Comment by photopea** [comment]
The software for stable diffusion is like 20 GB of data. Photopea is only 1.5 MB. With the internet speed of 10 Mbit, you would have to wait 4.5 hours just to download it (while Photopea is downloaded in 1.2 seconds).

**Comment by nigelp** [comment]
Not sure where you're getting those numbers from.

You can install Stable Diffusion on your local machine in about 15 minutes
tops. The model itself is only 4 GB (1.4).

Once SD is installed on your computer it's there for good. No need to
download again. Just fire it up and generate away.

**Comment by JRowe47** [comment]
Yes, with a decent 100mbps connection, you're looking at about 15-20 minutes to install locally. It takes less than 10 seconds to start up on my laptop - it's an excellent fit, I'm certain you'd find thousands of appreciative users with this one feature, and you'd be stepping on Adobe's toes by matching one of their latest features with an arguably better media synthesis system.

**Comment by xan2622** [comment]
https://www.speedtest.net/global-index#mobile

**Comment by PAEz** [comment]
A bunch of us want to use our computer, electricity and wotnot and already have the 4gig model downloaded.
The 1.5 version of the Photoshop plugin/script added local support and to do so made a local server with a  publicly described API.....
https://github.com/cantrell/stable-diffusion-api-server

**Comment by FlarosOverfield** [comment]
![image](https://user-images.githubusercontent.com/24918282/200056598-5c389364-3be4-4bf1-b7fe-da0b8a6ad8ef.png)
Billing Hard Limit message appears, never used Dall-E before. Maybe make it Premium exclusive if money is an issue?

**Comment by photopea** [comment]
@PAEz I dont think there is a way for a website to detect if you have DALL-E in your computer, or even communicate with Python etc :(

**Comment by photopea** [comment]
I have implemented the AI Inpainting according to a layer mask.

Try it here: https://www.photopea.com/#iyUddEhaQ.psd . Press Window - More - Dall-E, enable "Inpaint" and click "Generate".

**Comment by photopea** [comment]
I have changed the mechanism of payments. Any user in the world can use it for free, but they can generate 1 image per minute. The usage is unlimited for those who paid for Photopea Premium.

You can still insert your own API Key and use it under your own account.

**Comment by VapidLinus** [comment]
> I have implemented the AI Inpainting according to a layer mask.
> 
> Try it here: https://www.photopea.com/#iy9fmiZ_g.psd . Press Window - More - Dall-E, enable "Inpaint" and click "Generate".

Terrifying! Not sure what's up with the artefacts on both images.
![image](https://user-images.githubusercontent.com/4418470/200184875-85d79381-fba1-4b0c-a6f5-6c2970db4fd8.png)

Seriously though it's insane how fast you are at adding new features. Both the Dall-E integration in general and now this inpainting feature. I appreciate your work very much and am happy to keep paying for premium 💚

**Comment by photopea** [comment]
It took me about an hour to add inpainting. I am working on other features, too :)

**Comment by nigelp** [comment]
Really cool indeed. :) Do you by any chance have any documentation on how
to use it? I have got random results by chance, but when I tried something
deliberate I got an "Error, not RGBA, RGB" or something like that. I'm
clearly doing something wrong. :)

**Comment by photopea** [comment]
Do you know how to use raster masks? The masked area will be filled with a new content.

E.g. I tried to draw content around my eye, the prompt was "goat riding a bike" https://www.photopea.com/#ia-0NAQef.psd

![ivan_face](https://user-images.githubusercontent.com/15955558/200190440-abd86caf-2f28-4d2d-bcb0-9059caad94ff.gif)

**Comment by MichalSZZ** [comment]
I am here just to write - awesome work Ivan! I tried inpaint and I am impressed! Respect!

**Comment by DenverCoder1** [comment]
The Dalle2 integration looks great!

Stable Diffusion is also available as an API via https://replicate.com - it also requires an API key though and I believe it costs money per second.

**Comment by DenverCoder1** [comment]
Seems to work great :+1: 

I noticed that the tab now says "Stable Diffusion" but in the API Keys tab it says "get your own at beta.openai.com" but that is the website for DALLE, not Stable Diffusion.

Is that possibly a mistake?

![image](https://user-images.githubusercontent.com/20955511/202616833-cb1da927-0aa8-4efc-94d4-2842773ac94c.png)

**Comment by PAEz** [comment]
@photopea Maybe youd prefer their new REST API?.....
https://api.stability.ai/docs
...no in/out painting and wotnot, but its alpha so should get better.

**Comment by photopea** [comment]
I tried to implement it, but they do not support CORS, so it is not possible to use their API from the browser.

**Comment by PAEz** [comment]
What!?!?!?!

Wish I wasnt so tired all the time, Im not that smart and all but I looked at the code for Automatics and I think I could slip a couple of buttons in there to transfer from PP, to it, and back again.  Theres some details I dont get for masks and how to handle non square selections and size difference but I could prolly get the basics done.  Just getting rid of the save, load, save, load, etc would make me happy.  I was hoping someone else would do it, but I might give it a go this week.  I just gotta check a couple of things like if I minimize a plugins window/dialog is the frame still running?  I want that frame to communicate with a tab so you can have a full window as theres a lot in the interface.  Meh, Ill try and look later.

**Comment by photopea** [comment]
@PAEz I dont know what are you talking about. You can learn how to use our current plugin here: https://www.photopea.com/tuts/use-stable-diffusion-for-free/

**Comment by photopea** [comment]
I will close it now, but we can keep discussing it.

**Comment by PAEz** [comment]
For starters your plugin is NOT Stable Diffusion but Dall-E and thats doesnt interest me as much.
Automatic11111111111111's is a local distribution of Stable Diffusion with an insane amount of options and features.
It is a webui that communicates with Python using Gradio.
It should be possible to make a plugin for PP that asks for the url of your local webui and then loads that interface as a plugin.
A few mods of the python source could ping PP to see if its there and if so then add a couple of buttons to the webui to transfer the images back and forth between the two.
I dont do Python but a looking at the docs for Gradio and the source for the webui it looks like these things wouldnt be to hard to add.
The interface for the webui is to big to fit in a PP plugin as the window/dialog is typically to small.  But it should be possible to add some code that makes the ui open in a new tab and communicate from the new tab to the plugins iframe and then to PP.

And i find it nuts that a rest api is having cors issues.

**Comment by remixer-dec** [comment]
[This](https://github.com/BlinkDL/Hua#use-your-local-a1111-server) is a good example of a webapp communicating with a local SD api server

**Comment by photopea** [comment]
I have decreased the waiting time from 2 minutes to 1 minute (for non-premium users).

**Comment by camoody1** [comment]
> [This](https://github.com/BlinkDL/Hua#use-your-local-a1111-server) is a good example of a webapp communicating with a local SD api server

This is a really nice implementation of Inpainting and Outpainting. Really great for extending the canvas.

**Comment by xan2622** [comment]
Just wanted to mention **Stable Horde** : a (free and open-source) crowdsourced distributed cluster.

> It allows people without a powerful GPU to use Stable Diffusion or Text generation models like GPT/OPT by relying on spare/idle resources provided by the community. It also allows non-python clients, such as games and apps, to use AI-provided generations.

Website: https://stablehorde.net/
Github page: https://github.com/db0/AI-Horde
FAQ: https://github.com/db0/AI-Horde/blob/main/FAQ.md

**Comment by camoody1** [comment]
I wish I had a newer GPU so I could start using these local Stable Diffusion installations. I'm still using an AMD R9 390, unfortunately. Someday, maybe I'll be able to get am RTX 4070 Ti and really dig into this AI world.

**Comment by Mandraw** [comment]
So still no news on an implementation using the local API from A1111 ? It would really be the best option for people that have the GPU to support it

**Comment by photopea** [comment]
Hi guys, I found this, maybe it could be useful to you: https://www.reddit.com/r/StableDiffusion/comments/12141hw/wip_simple_photopea_integration_for_webui/

**Comment by camoody1** [comment]
> Hi guys, I found this, maybe it could be useful to you: https://www.reddit.com/r/StableDiffusion/comments/12141hw/wip_simple_photopea_integration_for_webui/

This would be an excellent plugin for Photopea. I see that you posted a comment. I did as well. Would love to see some more Photopea users comment there asking for a plugin. :)

**Comment by camoody1** [comment]
> Just a heads up, I made a plugin to interface A1111 in photopea here: https://github.com/huchenlei/stable-diffusion-ps-pea
> 
> Documentation is WIP, but you can already use it. Fixing Face Demo: https://www.loom.com/share/fb11c0206d7045469b82fe9d6342bd15

Very excited to do some testing on this. I tried to create an image from a blank canvas using the new SDXL model and it got stuck at 12%. I'm not sure if that's a bug on your end, a configuration problem on my end, or just growing pains from the new SDXL integration into Automatic1111.

What you've designed so far, though, is outstanding! You might need to add an option to select a VAE, though, since SDXL has a separate file for that.

**Comment by camoody1** [comment]
@huchenlei This works great for Inpainting. Well done!

**Comment by huchenlei** [comment]
@camoody1 Thanks! VAE selection is on the development plan. I will make it ready asap.

**Comment by photopea** [comment]
As I understand, people have the Stable Diffusion program running on their computers, which creates a web server and can communicate over the HTTP protocol, using some API. The plugin can connect to any web server and communicate over the pre-defined API. You are supposed to connect to your own local server (made by the Stable Diffusion program).

**Comment by huchenlei** [comment]
@camoody1 VAE selection implemented. You can find the selection box under `Advanced Settings` now.

**Comment by camoody1** [comment]
@huchenlei You should absolutely post about your plugin on the Photopea subreddit and Facebook pages. This is really a game changer for integrating Photopea with local installations of Automatic1111. It's so much better than trying to use the built-in Automatic1111 inpaint tool. And it's an amazing upgrade in quality for people editing their own photos and images in Photopea. So many great models and LoRAs to play around with.
