### ISSUE TITLE
Drag and drop channels and paths on mobile

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#5001]
I can't drag path in paths panel on mobile by long holding left mouse button to run dragging option (like in layers palette to drag on file icon or trash icon). It is my normal behavior for duplicating or deleting channels and paths in these panels.

Android. Chrome.

**Comment by photopea** [comment]
It should be fixed now, at least for Chrome on Android. 

In Firefox for Android, the long tap initiates a right-click.

**Comment by MichalSZZ** [comment]
OK thank you. 
But if in FF long tap initiates a right-click - can be there a context menu?
In Photoshop there are two options in the Channels panel: "Duplicate channel..." and "delete channel".
In "Duplicate" there are 3 dots at the end because it has more options to duplicate. But this feature is not necessary.

For the paths panel, there are more options but most of them correspond with icons at the bottom (some of them are greyed out if for example there isn't any work path)
