### ISSUE TITLE
Rectangle Select ~ Drag scrolling diagonally scrolls wrong for 2/4 directions

### ISSUE THREAD

**Issue by KiraResari** [photopea/photopea#5003]
**Repro**

1. Zoom into your picture so only a small part of it is on-screen
2. Use the rectangle select tool to try and select an area larger than what you have on-screen by clicking and dragging into one of the corners

**Expected Behavior**

* The screen should scroll in the direction of the corner that you have dragged into

**Actual Behavior**

* For the top left and bottom right corner this works as expected
* However, if you drag into the bottom left or top right corner, the screen instead scrolls to the top left

**Comment by photopea** [comment]
it should be fixed now :)
