### ISSUE TITLE
sticky shortcuts

### ISSUE THREAD

**Issue by pisforplayer** [photopea/photopea#5006]
Alt(Zooming), Clipping-Mask shortcut and Layer visibility toggle seem to simultaneously act up. one example would be that zooming sometimes happens without pressing Alt key, and another would be that when you turn on visibility to a layer, the closest layer or all other layers would go invisible. I do use photopea daily and during this technical issue I also noticed when; 'magic-wand selecting + inverse' input, [hitting clear or backspace/delete] would fill the inverse selection and say paint bucket did so in the history tab.

**Comment by photopea** [comment]
Before we proceed, what web brwoser do you use and is it updated to the latest version?
