### ISSUE TITLE
Copying and Pasting frames in a group while the group is closed

### ISSUE THREAD

**Issue by TurnaboutTom2005** [photopea/photopea#5008]
Everytime I try to copy and paste a few frames in a group, if the group is closed, the entire application stops functioning properly. I can't make any edits to my projects, I can't save anything either. The only thing I can do is close the app and restart, losing the progress I had made in the process.

**Comment by photopea** [comment]
I just tried to copy and paste layers into a closed folder and it seems to work perfectly.

Could you tell us how do you copy and paste frames into a group? What exactly do you do?

**Comment by photopea** [comment]
I have to close it because of lack of details.
