### ISSUE TITLE
[Request] Hotkeys for Expand and Contract Selection

### ISSUE THREAD

**Issue by Abystus** [photopea/photopea#5009]
It would be nice to have some hotkeys for these as fumbling through the menu when doing repetitive tasks gets old. I'm not sure what keys are available for use, but I wouldn't mind utilizing the 2 keys left of the backspace while holding ctrl+shift such as:

![image](https://user-images.githubusercontent.com/1529049/191899850-d3697ff7-032f-4558-b3a5-7b3dd6cec005.png)

**Comment by photopea** [comment]
It is not usual to expand or contract the selection too often. When exactly do you need it? E.g. if you do it after the Magic Wand, maybe you should increase the Tolerance.

**Comment by Abystus** [comment]
@photopea Well increasing the tolerance isn't a pixel perfect increase all around, so it leads to bleeding in other areas and jagged edges. As to why I needed Expand/Contract so much, I am removing the background from sprite sheets for a game where the background isn't a single color throughout (either do to compression, blurring, etc...), so I can magic wand around them at a tolerance, but I can only go so close before the tolerance can't be bumped anymore and I require just a pixel perfect expand by 1 or 2 pixels. Now imagine the sprites have gaps inside you also have to do, for example inside arms that the original magic wand didn't get as it wasn't part of the original selection outside the sprite. I then have to magic wand inside of each of those, then go expand each one by 1 to 2 pixels and delete. This can be quiet a repetitive task, and having to go to the menu every time to find the expand got quite annoying.

**Comment by photopea** [comment]
I don't think anyone else would need this feature. I would rather keep the keyboard shortcuts "free" (when someone presses keys accidentally, it is better if nothing happens).

Try to select with the magic wand mutliple times (hold Shift to add to a selection).
