### ISSUE TITLE
Default jpg save out quality 50% too noisy especially for text

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#501]
The default jpg quality 50% is too noisy for content with text
Have to change it every time to 90% which is an extra step

**Comment by photopea** [comment]
What about saving it as a PNG? PNG is usually smaller, if you have only a text on a solid color background.

**Comment by hgs54371** [comment]
I usually have pictures and text mixed together, png not good for pics

**Comment by photopea** [comment]
The 90% JPEG can be 3x bigger, than 50% JPEG. Maybe we can just make Photopea remember your setting after you close it and open it again.

**Comment by photopea** [comment]
If you save a JPG once, the quality slider is preserved when you save JPG afterwards (but it is reset when you close Photopea).
