### ISSUE TITLE
Editing tools brought up in the menu

### ISSUE THREAD

**Issue by AliAlasfoor** [photopea/photopea#5011]
I just opend photophea from a nother tab that was opened and saw this
![image](https://user-images.githubusercontent.com/91006066/192097826-a9ac4c36-cc07-4cd7-8b77-bd3e09f85083.png)

Like what the hell! What are the chances! [Also i am just bug reporting this to fix this]

**Comment by photopea** [comment]
I can not reproduce it. Do you see this each time you open www.Photopea.com ?

**Comment by photopea** [comment]
I have to close it because of lack of details.
