### ISSUE TITLE
broken completely

### ISSUE THREAD

**Issue by pisforplayer** [photopea/photopea#5012]
photopea, my alt for photoshop, now just does not work after more than a year of usage. not to be passive aggressive but i take my art very seriously and i have routines and deadlines i personally make and this is very inconvenient.

**Comment by xan2622** [comment]
Hi. 
Which web browser (and version do you use) ?
What OS ?
Have you tried to clear all your cookies and web data (or at least, only for photopea.com) and retry it ?

**Comment by photopea** [comment]
Could you try these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by pisforplayer** [comment]
> Could you try these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by pisforplayer** [comment]
I only use incognito tabs for designing

**Comment by pisforplayer** [comment]
> 

i just cleared the sites data and refreshed the tab and nothing has changed, all the controls are still scrambled.

**Comment by photopea** [comment]
could you show us a screenshot of what do you mean by "scrambled"? Also, what web browser are you using?

**Comment by pisforplayer** [comment]
I live in the U.S. and its actually not possible to screenshot these bugs due to them being functions but i can explain them. issue 1. the cursor being used to scroll is switched from magnifier 🔍to a black and white pointer and circle like what you would see in panning an image via chrome tab. pressing [ ctrl ] sometimes leaves a residual input effecting zoom or layer selection. issue 2. I can't open layer groups. issue 3. when using top tab bar options like; file, edit, image etc... left clicking displays the specific tab options at the bottom of the window and cuts it off. issue 4. magic wand selecting pixels and inverse clearing fills the canvas with the selected color. issue 5. [ ctrl ] shortcut created a clipping mask instead of [ alt ] shortcut. issue 6. one occurrence took place where toggling the (👁) icon or visibility of a layer changed the visibility of other layers that were unselected.

**Comment by photopea** [comment]
Let's start with the first issue. Nobody else ever reported it. What OS and what version of Chrome are you using? Does it happen after you disable all your browser extensions?

**Comment by pisforplayer** [comment]
Windows 11, Chrome 105.0.5195.127 (Official Build) (64-bit)

**Comment by photopea** [comment]
Could you maybe record a short video of the issue, which starts with opening Photopea.com?

**Comment by pisforplayer** [comment]
I apologize for the timing of this reply, but actually my recording software auto hides the mouse. but thankfully i have successfully transfered my process over to photoshops free trail until we can resolve what we're dealing with.

**Comment by photopea** [comment]
Please, provide some proof that there is actually something wrong. Othrewise, you could be making it up.

**Comment by pisforplayer** [comment]
yeah nah I wouldn't gain anything making up a problem and wasting time. i just am unable to show you the issues but thank you for your consideration regardless.
