### ISSUE TITLE
constantly crashes

### ISSUE THREAD

**Issue by ravencroftgraphics3d** [photopea/photopea#5013]
I have been trying to use this for DAYS now and on different browsers and all with the same results.... freezing, and then crashing losing all work, uploaded brushes and fonts and DAYS of wasted work time. it USED TO fine but now.... NOPE! chrome and firefox both it constantly freezes on and crashes making it impossible to use. i'd say update to fix it but it appears they issue has been reported several times already and nothing was fixed.

**Comment by photopea** [comment]
That sounds very confusing. Could you record a short video of opening Photopea.com and making it crash?

**Comment by ravencroftgraphics3d** [comment]
it really isn't confusing, it keeps freezing and then crashing going back to the start screen causing the loss of all current work and the loaded fonts and brushes i added disappear. it happens constantly. it especially crashes every time i try to load a new font. makes working impossible. taking a video is impossible as it happens without me having to do anything and happens sometimes 5 minutes in before i can even get anything started or after 45 minutes when i am deep into a project. it crashes and the crash screen says to 'reload' the page, which you'd think would bring me back to my work... but it doesn't it resets everything back to the start page and i have to start all over again. every. time. this never used to happen so i am not sure what changed, and this is the only site/program i am having this issue with so... it happens with both mozilla and chrome so it is not the browser that is the issue.

**Comment by photopea** [comment]
Your browser could kill Photopea because there was not enough RAM memory in your device. We can not increase RAM in your device, you must buy more RAM.

We can not fix something which we can not see happening :(

**Comment by photopea** [comment]
I have to close it because of lack of details.
