### ISSUE TITLE
Inconsistent convention regarding aspect ratio for resizing of Custom Shapes

### ISSUE THREAD

**Issue by xilehence** [photopea/photopea#5014]
When resizing a custom shape, the aspect ratio is currently (and traditionally) unconstrained except when chording with the Shift key. To be consistent with the new convention that aspect ratio is preserved by default, as with other Shapes, it Custom Shapes should also preserve aspect ratio unless the Shift key chord relaxes that constraint.

**Comment by photopea** [comment]
I disagree with you. I think the Ellipse tool should let you draw any ellipse, and the rectangle tool should let you draw any rectangle. It should not draw circles and squares by default.

**Comment by photopea** [comment]
There is no "new convetnion". You probably mean the settings of the Free Transform tool, which you can change, see here: https://www.photopea.com/tuts/new-free-transform/
