### ISSUE TITLE
Disambiguation of Quick Mask (for selection) and Layer Mask icons (for raster mask and vector mask)

### ISSUE THREAD

**Issue by xilehence** [photopea/photopea#5015]
The icons for Quick Mask (at the bottom of the Tools bar) and the Layer Mask (at the bottom of the outer sidebar) are identical, even though their respective button operations are different. Photoshop disambiguates them by dashing the embedded circle in the Quick Mask icon, and Photopea could adopt the same iconification.

**Comment by photopea** [comment]
I think the icon represents a mask, any kind of mask. I dont see a problem with using the same icon at two places.
