### ISSUE TITLE
Tool tip for Layer Mask not modulated by chording modifier

### ISSUE THREAD

**Issue by xilehence** [photopea/photopea#5016]
The tool tip (hovering reminder) for the Layer Mask (at the bottom of the outer sidebar) shows "Add Raster Mask", even when the chording modifier (Cmd for macOS, Cntl for Windows) is pressed to switch its function to adding a Vector Mask.

**Comment by photopea** [comment]
Now, when a layer has a raster mask, the label says "Add Vector Mask".

But our current UI model does not allow changing the label after pressing a key. It would be very hard to remake.

**Comment by xilehence** [comment]
Thanks, Ivan.
The solution you deployed is fine, but if you wanted to accommodate possibility of adding Vector Mask but not a Raster Mask,
you could factor out the commonality between the two operations, and have the tooltip say just “Add Mask” or “Add Raster or Vector Mask”.
Anyway, continued gratitude for your great DCC tool!
