### ISSUE TITLE
Variables - Visibility

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5019]
When setting a variable to enable the visibility of a layer. By default it works with TRUE and FALSE values.

For example i have a project right now that uses variables to change the background color of a card:
![image](https://user-images.githubusercontent.com/11801254/193119486-902b9c6c-ceb5-4156-a0fa-d4ac1714060f.png)

And right now i have a CSV set like this to change those:
![image](https://user-images.githubusercontent.com/11801254/193119624-4d4565d0-33ad-4171-bc16-65e27002780c.png)

It will be a lot easier and clean to work with a CSV like this:
![image](https://user-images.githubusercontent.com/11801254/193119775-c5bcd3ca-403c-4e35-ad3e-c9c24a2c03b3.png)

As now, if a variable is set to enable the visibility of a layer and it has null/empty it shows the layer. And on the other hand, if it has something, it hides the layer. So in the end the more "efficient" and clean CSV i can have is:
![image](https://user-images.githubusercontent.com/11801254/193122280-a51f035e-ad64-4b38-8230-d7279280d9a9.png)

So.... Could Photopea's variables work the other way around? To recognize empty/null as FALSE and something (different from FALSE) as TRUE.

**Comment by photopea** [comment]
So basically, if the column is used for the visibility, and there is no value, it should be interpreted as "invisible".

done :)

**Comment by TheRadicalDreamer** [comment]
:D
