### ISSUE TITLE
loading problem

### ISSUE THREAD

**Issue by kleanins** [photopea/photopea#5020]
my project is not opening. its stucks at loading. i tried at phone, another browser and another pc. 
could someone send thit psd to me? https://www.photopea.com/#ilzSS6Ex8
![image](https://user-images.githubusercontent.com/57459418/193123352-1a3cec76-d979-45b6-8c0e-cef04050be7c.png)

**Comment by cmwkings33** [comment]
Same for me. It's like the application is hung.

**Comment by photopea** [comment]
I can open your link, it shows me a document with a girl with headphones.

Could you try to disable all your browser extensions? Also, maybe your internet provider is blocking the domain of our storage provider.

**Comment by kleanins** [comment]
> 

can you send me psd?

**Comment by photopea** [comment]
Sure, here it is.
[W1W11W.zip](https://github.com/photopea/photopea/files/9685756/W1W11W.zip)
