### ISSUE TITLE
Cannot add any images

### ISSUE THREAD

**Issue by kaylaaaaaaaa** [photopea/photopea#5022]
I can’t add any images. I have tried pasting the URL but that did not work so I typed it all manually and no image was added even though it said it was loading. Also won’t let me add any from the files of my laptop either.

**Comment by photopea** [comment]
Are you using Photopea at www.Photopea.com ? Try this maybe: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
