### ISSUE TITLE
Error Code \u0000\u0000\u0000\u0018

### ISSUE THREAD

**Issue by Ashtoneicher** [photopea/photopea#5023]
This code pops up any time I try to upload a photo from google drive or amazon photos. I have tried downloading the photos to my computer directly, and it says "unknown file format: '\u0000\u0000\u0000\u0018'" I have tried other photos already on my computer and they work just fine, and I have tried incognito mode with the same results. It must be something with the photos passing through drive or amazon photos, because when I get on my phone (where the photos originated) and jump on the browser of photopea on there, I can upload the pictures just fine directly from my phone.

**Comment by photopea** [comment]
Hi, how exactly is it related to Photopea? Did you export your photos from Photopea and now you can not view them?

**Comment by Ashtoneicher** [comment]
I am trying to start a new project, and i an am pulling from Content that is in my drives to open it in photopea, but photopea will not open them In any capacity. I keep getting that error code

Sent from my iPhone

On Oct 2, 2022, at 5:08 PM, Photopea ***@***.***> wrote:

﻿

Hi, how exactly is it related to Photopea? Did you export your photos from Photopea and now you can not view them?

**Comment by photopea** [comment]
What is "pulling from Content"? Could you record a video of what you are doing, and start with opening www.Photopea.com in your browser?

**Comment by photopea** [comment]
I have to close it because of lack of details.
