### ISSUE TITLE
it is so bad

### ISSUE THREAD

**Issue by Drskarim** [photopea/photopea#5026]
it doesnt work too complicaTED i donts know how 2 use it it is -10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000*s

**Comment by Drskarim** [comment]
i like this guys review very acurate

**Comment by photopea** [comment]
Hi, how can I help you?

**Comment by rokobuljan** [comment]
This issue should be closed.

**Comment by photopea** [comment]
Ok I will close it because of lack of details.
