### ISSUE TITLE
Corrupted file

### ISSUE THREAD

**Issue by nrdrehs** [photopea/photopea#5027]
When my students are saving projects they are getting 0 bytes and at the end of file it says psd.crswap
This is happening multiple times.  How do we fix they are losing their work?

**Comment by photopea** [comment]
I think it is probably because they closed Photopea before the file was properly saved. When Photopea says "Saving..." at the top, do not close it, until that message "Saving..." diappears.

When you tell your web browser to close a website, there is nothing a website can do about it.
