### ISSUE TITLE
Add guide moves the previously added one

### ISSUE THREAD

**Issue by ror6ax** [photopea/photopea#5028]
Hi guys. Congratulations on creating such an amazing application!

I've observed a behavior that is likely not what you meant to happen. I can add one guide as expected by View -> Add guides. But if I repeat the process and try setting second guide in such a way - the first guide gets moved to the new location.

**Comment by photopea** [comment]
The View - "Add Guides" contains a list of all guides in a document. You are rewriting the position of the one existing guide.

**Comment by photopea** [comment]
You should type a space and type a second number there.
