### ISSUE TITLE
Liquify

### ISSUE THREAD

**Issue by MSMAI06** [photopea/photopea#5029]
I am trying to liquify multiple layers. The first text layer that I rasterized, I am able to go to Filter > Liquify > Rasterized > Liquify. However, when I do this for the second text layer that I rasterized. It becomes a transparent background when I click 'Liquify' even if background is on.

**Comment by photopea** [comment]
I just rasterized two text layers and applied the Liquify on each of them, it seems to work fine.

Please, describe the exact steps, which always lead to the problem which you are describing.

**Comment by MSMAI06** [comment]
1. New Project > Print > Letter > Create
2. File > Open & Place, I then select my image to fit the area
3. Add New Layer > Rename 'Black' > Paint Bucket Tool > Turn layer to black > Adjust opacity to 40%
4. Add Text on image > Select Text > Filter > Liquify > Rasterize Text > Liquify (successful)
5. Repeat 4 and when prompt with the liquify screen all I see is transparent background and the background is already switched to the on position

What I am finding that is working is saving the project as PSD and reopening it. However, I would have to do this each time when I want to liquify (which will be a lot, because I'm trying to test out typography before I teach it to my middle schoolers).

**Comment by photopea** [comment]
I tried what you described, but it still seems to work correctly in my case.

Did you maybe switch to an empty layer in between? Are you sure a rasterized text layer is selected? 

Also, could you try it in the Incognito mode, or without any browser extensions?

**Comment by photopea** [comment]
I have to close it because of lack of details.
