### ISSUE TITLE
The cursor to drag out shape should be more accurate

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#503]
The cursor as a starting point to drag out shapes like rectangular should be more accurate,
Right now the shape doesn't start right at the tip of of the cursor which is not good enough for detailed work.

**Comment by photopea** [comment]
Hi, can you tell me, what is your browser and devicePixelRatio? (https://johankj.github.io/devicePixelRatio/)

**Comment by hgs54371** [comment]
I'm on a mac with firefox, Device Pixel Ratio is 1

**Comment by photopea** [comment]
And what about the Brush cursor? Is it drawing exactly where you press the mouse?

**Comment by hgs54371** [comment]
I think my real problem is that the shape tool is a big cursor hiding the thing being drawn onto, (I'm drawing rectangular box behind text as its bg), it's hard to estimate the spacing to leave, a thin cross cursor like the rec select tool would be better

**Comment by photopea** [comment]
I believe it was fixed.
