### ISSUE TITLE
Pen option not working (but shape is....?)

### ISSUE THREAD

**Issue by timevantos** [photopea/photopea#5030]
someone please figure this out... i make custom designs with shapes, abstract like shapes etc... this is making it very hard to design atm.

**Comment by photopea** [comment]
What do you mean? What pen option?

**Comment by timevantos** [comment]
Pentool, it glitches and doesn’t work for some project(s) of mine

**Comment by photopea** [comment]
What should I do to see it not working? It seems to work fine in my case.

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by timevantos** [comment]
figured out the issue, the project size was making my photopea glitch i
opened a new project and the pentool worked fine… just very strange but
cant afford photoshop since its a bit of a budget especially with the other
apps i need as well for designing been using photopea since 2018-2019 had
no issue til couple of weeks ago sadly
