### ISSUE TITLE
Imported PDF > Linebreaks for multiline text boxes that are not aligned left.

### ISSUE THREAD

**Issue by JasperCyan** [photopea/photopea#5031]
When importing a PDF file any textbox that has text aligned center or aligned right will be split into individual text lines. 

Each text inside the textbox is imported as a separate text layer, meaning the user cannot edit PDF text flow easily. 

You can see it working correctly in other online software like:
https://pdf.online/edit-pdf-text 
https://online.sodapdf.com/ 

Steps to reproduce:
- Import PDF file with a multi-line textbox - center align or  right align 
- Try to edit the paragraph text-box and each line can only be edited one by one instead as a textbox.

Note:
The PDF textbox works correctly when the text is aligned left. 
The PDF textbox works correctly if all lines inside the textbox are the same character length.

Please see attached PDF file for textbox example:
[textbox-not-working.pdf](https://github.com/photopea/photopea/files/9706348/textbox-not-working.pdf)

![image](https://user-images.githubusercontent.com/64249844/193806304-49307af3-8c95-4429-a0f8-db126cf67d49.png)

**Comment by maxpetrusenko** [comment]
Not sure how to word it, but there is still some issue importing pdf, the text box  gets smushed ( not sure how to word it, but it could be related to this issue

![Screen Shot 2023-03-07 at 12 14 26 PM](https://user-images.githubusercontent.com/37906420/223497866-f939dd81-c3fd-4c07-b1dd-26f9e84c8b10.png)

**Comment by photopea** [comment]
Hi, could you share your PDF with us?
