### ISSUE TITLE
Zoom in does not work after zoom out if Command key is not released

### ISSUE THREAD

**Issue by dnicolson** [photopea/photopea#5032]
To reproduce:
1. Open PNG image
2. Press ⌘-
3. Press ⌘+ (without releasing the ⌘ key)

On the second press, the image is zoomed out again and not zoomed in.

I'm wondering if it would make sense to omit the " + " between the keys as on macOS:
<img width="15%" src="https://user-images.githubusercontent.com/2276355/193915059-f8e4d69e-d7d8-4bed-b9a9-743c1f038a6b.png">

**Comment by photopea** [comment]
This is a bug in your mac, see https://github.com/photopea/photopea/issues/4409
