### ISSUE TITLE
Layer selection not working correctly

### ISSUE THREAD

**Issue by deanbyrne95** [photopea/photopea#5033]
Using Photopea in Firefox 105.0.2 and I am running into an issue with the layer selection - it is over-selecting the layers' size - either double its size or selecting the entire area of the canvas which makes layering vertically/horizontally incredibly difficult.

I have tried making new layers and drawing in values but it seems as if it does not resolve it.

Here is a screenshot of said issue:
![image](https://user-images.githubusercontent.com/4136983/194056570-179ae717-0d04-4dbb-b4c7-2b03d01126fd.png)

**Comment by photopea** [comment]
What if your layer contains almost transparent, pixels at the corners? Could you share your document with us so that I can take a look?

**Comment by photopea** [comment]
I have to close it because of lack of details.
