### ISSUE TITLE
why is it not opening psd files

### ISSUE THREAD

**Issue by Hakan3545** [photopea/photopea#5034]
@photopea 
**why is it not opening psd files**

![Photopea-Online-Photo-Editor](https://user-images.githubusercontent.com/115147634/194275044-eb2f46f9-b606-468d-953c-903a9b1427d8.png)

**Comment by photopea** [comment]
It should open a window with PSD Templates. Do you really see "Loading" after clicking this button? Could you try it in the Incognito mode?

**Comment by Hakan3545** [comment]
**Yes I see. but it says loading in incognito tab**

![Screenshot 2022-10-08 at 04-25-44 Photopea Online Photo Editor](https://user-images.githubusercontent.com/115147634/194680828-a42352cf-d28d-4ec4-9cc5-d5c78c1de286.png)
![Screenshot 2022-10-08 at 04-25-15 Photopea Online Photo Editor](https://user-images.githubusercontent.com/115147634/194680834-205141fc-c8ea-422b-8aa8-5d9bb50ea131.png)

**Comment by photopea** [comment]
I think something in your device is blocking the domain of our cloud storage Backblaze. Can you download e.g. this file? https://f000.backblazeb2.com/file/psdshared/JqlhM2V8

**Comment by photopea** [comment]
I have to close it because of lack of details.
