### ISSUE TITLE
Icons Disappeared

### ISSUE THREAD

**Issue by SamSYI** [photopea/photopea#5035]
This started a few days ago, I can't see any icons in the layers tab. This seems to only happen in chromium-based browsers, I tried mozilla and it works fine there. And no, I'm not using adblock but ads arent appearing in chromium browsers anyway. 
![image](https://user-images.githubusercontent.com/61864519/194458260-7ac705d8-43e4-4a41-9740-a640d375ecf5.png)

**Comment by photopea** [comment]
Is your current browser more than 10 years old? Could you update it?

**Comment by SamSYI** [comment]
It's not old, both the browsers I tried were downloaded somewhat recently. Here are the versions: 
![image](https://user-images.githubusercontent.com/61864519/194499254-72514bfb-85d8-4697-b8ec-99d9e25a9342.png)
![image](https://user-images.githubusercontent.com/61864519/194499288-cba2a29d-5a4e-4897-b9a7-6aabf5d8540c.png)
As I said, the problem started a few days ago. It was working just fine before.

**Comment by photopea** [comment]
Could you send me your PSD file to support@photopea.com ?

**Comment by SamSYI** [comment]
done

**Comment by photopea** [comment]
I looked at your PSD, but it seems to work fine in my case. Brave is not a real browser, so we don't even try to make Photopea work in it. But does it really not work in Edge? Did you try to disable all your browser extensions?

**Comment by SamSYI** [comment]
Ah I realized I was using Dark Reader, I disabled it and it's fixed now. Not sure what changed, I was using it before and didn't have the issue. Thanks for the help!
![image](https://user-images.githubusercontent.com/61864519/194700498-c802eca4-7241-4f09-a616-f90f8a458f96.png)

**Comment by photopea** [comment]
If Photopea seems broken, it is caused by your browser extensions in 99 percent of cases.
