### ISSUE TITLE
Shortcuts interfere with system shortcut (Linux Ctrl+Alt+T)

### ISSUE THREAD

**Issue by Combinacijus** [photopea/photopea#5037]
When on Linux Free Transform tool shortcut Ctrl+Alt+T does not work because it opens terminal on Linux machine. I'm sure other shortcuts are incompatible too. 

Is there a way to remap shortcuts or maybe ignore system shortcut or any other way to use them?

**Comment by photopea** [comment]
What keyboard shortcut would you like to press for the Free Transform?

I think that the OS should let an app (a web browser in this case) re-define a "system shortcut" and not start the terminal in some cases. So that sounds like a bug in your OS.

**Comment by Combinacijus** [comment]
Any of those seems ok: Alt+T  or  Alt+Shift+T  or  Ctrl+Alt+Shift+T  or Y
Is it possible to have 2 shortcuts for 1 actions so it doesn't brake back compatibility for other users?

I wouldn't say it's not OS bug but a feature. Open terminal shortcut Ctrl+Alt+T have same priority as lock screen (Win+L) or show desktop (Win+D) or screenshot (PrtSc). They are designed to work everywhere and that's the behavior most people want. I check default "system" shortcut and most of them starts with Win key which makes sense but it seems that due to history opening terminal is done with Ctrl+Alt+T by default and every Linux user knows that so changing it is not an option although I think that it could have been Win+T but oh well. As it is know on default Linux installation Ctrl+Alt+T is not usable for any other app

**Comment by Combinacijus** [comment]
After installing Photopea Free Transform works with Ctrl+T thanks

![image](https://user-images.githubusercontent.com/16375702/195626813-c25ab88c-b9b2-4d66-904b-ebfc542c8a90.png)

You can then open app from address bar while on website it just opens dedicated window no real downloading needed
![image](https://user-images.githubusercontent.com/16375702/195626523-8cea16e9-cb40-4627-96c2-e2ed767178bb.png)

**Comment by photopea** [comment]
Photopea starts the Free Transform when Ctrl and T are pressed at the same time. It works like this since 2013.

The problem is, that most of current browsers don't tell a website, when Ctrl and T is pressed, and they open a new browser tab instead. On the other hand, when you add Alt to it, they dont open a new tab, and deliver the keyboard shortcut to the website.

Any keyboard combination, which contains Ctrl and T, will start a free transform (unless the browser prevents it for something else).

**Comment by sozipp** [comment]
use "https://sozipp.github.io/Input-Remapper-for-Photopea/" and remap your key
