### ISSUE TITLE
When selecting a dark theme, the menus are still white

### ISSUE THREAD

**Issue by martinszeltins** [photopea/photopea#5038]
When a dark theme is chosen the UI turns dark except for the menus. It would be nice if the menus also turned dark like all UI.

![image](https://user-images.githubusercontent.com/34019878/194753378-e924fa5c-5100-4d5b-ba34-c8b2b3bd906f.png)

**Comment by photopea** [comment]
I think it looks better as it is now. Dark menus would blend with the background.

**Comment by martinszeltins** [comment]
> I think it looks better as it is now. Dark menus would blend with the background.

If you look at Photoshop they have dark menus and they look great.

**Comment by photopea** [comment]
Where are dark menus in Photoshop? Could you show me a screenshot?

**Comment by martinszeltins** [comment]
> Where are dark menus in Photoshop? Could you show me a screenshot?

@photopea for example here (and they look very nice)

![image](https://user-images.githubusercontent.com/34019878/195585622-6bcbfdaf-50b6-4c37-831c-23068ebff5cc.png)

**Comment by MichalSZZ** [comment]
I think it is related to settings in your OS. Probably you have a dark mode in the whole Mac system setting. 
I have a dark theme in my PS in Windows where I don't have dark mode in OS and my menus are white like in Photopea now.

**Comment by martinszeltins** [comment]
> I also think it is caused by our OS settings. If you switch it to white, menus will be white.
> 
> Photoshop menus on Windows are white.

@photopea But even if my OS settings are set to dark mode - the menus on Photopea are still white.

**Comment by MichalSZZ** [comment]
@photopea  do you think about something like that?
![obraz](https://user-images.githubusercontent.com/38118273/195599656-14ded93f-e990-4718-a019-55286c54c351.png)
or can you also do blurish background?

**Comment by MichalSZZ** [comment]
BTW. My colors in the screenshot are taken from the currently dark mode. 
![obraz](https://user-images.githubusercontent.com/38118273/195600430-8f33b731-136f-4481-8b36-09ec863851b6.png)
background from hover menu item:
`.cp_light {
  background-color: rgba(53,53,53,0.95);
  color: #fff;
}`
hover item from input background
#252525 with 100% opacity

HR line black and font color white

But what about other color themes?

**Comment by MichalSZZ** [comment]
I see that my changes in CSS affect more things, like every right-click context menus:
![obraz](https://user-images.githubusercontent.com/38118273/195604474-d2b16638-d9d2-4243-ba4f-d09098ea5cdd.png)
![obraz](https://user-images.githubusercontent.com/38118273/195604560-6fd30a4e-92e9-41b5-b2ff-d85e5ecc4789.png)

I like this style - it is more modern, but maybe not so clear for all people who don't use dark mode daily. I am not UX designer but Photoshop doesn't change it in dark mode - maybe they have some reasons.

**Comment by xan2622** [comment]
@MichalSZZ I really like these changes. 
I hope that your modifications for the dark menus will be implemented in Photopea.

**Comment by photopea** [comment]
We can recreate any style, even the dark blurry one.
![image](https://user-images.githubusercontent.com/15955558/195714806-37209203-fbfc-4c70-a541-4c80ed0c4c05.jpg)

**Comment by photopea** [comment]
I also made a macOS-ish one

![image (1)](https://user-images.githubusercontent.com/15955558/195722888-519dbc03-c244-41c6-a921-fdb7c9ab1796.jpg)

**Comment by photopea** [comment]
I have put a semi-transparent one on Photopea.com . But I think it is uglier than the white one, what do you think?

**Comment by martinszeltins** [comment]
> I have put a semi-transparent one on Photopea.com . But I think it is uglier than the white one, what do you think?

Thank you! I really love the new semi-transparent menus. I think it looks beautiful. Definitely better than the white that was before. 👍🏻

**Comment by MichalSZZ** [comment]
It looks really great.
I'm wondering if it is not too transparent.
Problem: Dark menu - white project. White theme - black project.
Now it is 0.35 alpha. Maybe 0.5 will be more readable (better contrast for letters).

BTW. You can make a Facebook pool with a graphic representation of these two UI designs and ask users. Old and new ones. (there are your users - but they can be novices in UX - be careful). The second place to ask someone about your changes is LinkedIn - there are many professionals. I see all the time some posts with Two UX/UI scenarios and users vote with heart or thumbs up  - which version is better. Many professional users write something important in comments.
Voting with reactions is very popular - easy for the users and your post will be visible on others' walls. Viral marketing in a place good for the business.

**Comment by MichalSZZ** [comment]
Maybe you can add an option for the old - white full transparent background of the menu as an option? I don't know how to name it... :)
![obraz](https://user-images.githubusercontent.com/38118273/195812931-77382c6c-6b9d-4591-b5ac-819a7b2d9beb.png)

**Comment by photopea** [comment]
I am not a fan of too many options. I think the menus should look the same for everyone.

**Comment by MichalSZZ** [comment]
> I am not a fan of too many options. I think the menus should look the same for everyone.

Sure! You are the author and you have the final decision. I have only a problem with one thing. I like the new - modern style. I like it a lot. But the old one had better contrast and it was better for reading in any color in the project. But maybe it is a problem of transparency - I don't know.

**Comment by martinszeltins** [comment]
Thew new one definitely looks more modern. I also think ideally it should respect OS preferences. If I am working at night and I have dark theme enabled, it is very bad if all of a sudden a white menu appears.

**Comment by photopea** [comment]
I think this new menu is very ugly, compared to the old one. I am a fan of a simplicity and readability, and the new menu is too complex (many lines, borders, transparencies, round corners) and hard to read.

**Comment by xan2622** [comment]
When an interface is using a dark theme, I expect menus to also be dark. I think it fits better with the UI, it is easier for the eyes (that's why I didn't like much the previous white menus of Photopea).

I hope that menus in Photopea will also be dark (and matching the rest of its UI) but not necessary with this "_aero transparency effect_". Yes, it is fancy and looks good but I don't think [the "aero" transparency](https://github.com/photopea/photopea/issues/5038#issuecomment-1278511815) fits the rest of the Photopea UI.

What about using this solid color? 👇
<img src="https://user-images.githubusercontent.com/38118273/195604474-d2b16638-d9d2-4243-ba4f-d09098ea5cdd.png">

**Comment by martinszeltins** [comment]
It looks like different people prefer different styles. Some like white menus, others like the MacOS style better and others prefer them dark gray.

I think users should be at least given a choice to choose what they prefer.

**Comment by MichalSZZ** [comment]
On Reddit and here people write comments that they like the changes. And it is something big becouse most of people don't say if they like something, rather they will make a comment when something is wrong or don't work.

For me. It is more modern and many people likes all these fancy look designs. You should keep this changes but try to give the people choice. Old one, dark one without transparency. And this MacOS looking. 

Maybe in the theme section, maybe in prefferences. I don't know. But for the new users - photopea will look more modern with this change.

**Comment by photopea** [comment]
Ok, maybe I will start to like it eventually, once I get used to it :)

**Comment by photopea** [comment]
There is a big group of people wanting the old style of menus, and people wanting the new style. I can make it switchable in settings, but I think 99.9% of people would use it under the default settings (as they will not know they can change it).

So the question is, what should be the default look? Could you discuss it with each other and agree on one style?

See here: https://github.com/photopea/photopea/issues/5063

**Comment by photopea** [comment]
Old menus are back. You can switch to glass menus in Edit - Preferences - Glass Menus.

**Comment by martinszeltins** [comment]
> Old menus are back. You can switch to glass menus in Edit - Preferences - Glass Menus.

Awesome, I like that users have a choice now (if they know where to find it).

**Comment by alexanderst19** [comment]
looks great!
