### ISSUE TITLE
[Feature Request] Adjust grid colour

### ISSUE THREAD

**Issue by nolddor** [photopea/photopea#5039]
Currently, on **View > Show > Grid** menu there is no way to adjust Grid colour lines

As pixel artist, this comes in handy... as i usually work on low res images <3

**Comment by photopea** [comment]
Our method paints the grid lines with the "inverted" color. Do you want them to be a fixed color? Does any program in the world has such solution? Does it work well?

**Comment by nolddor** [comment]
> Do you want them to be a fixed color?
Yes
> Does any program in the world has such solution?
Photoshop, see [How To Change The Photoshop Transparency Grid Color](https://www.addictivetips.com/windows-tips/change-photoshop-transparency-grid-color/)
> Does it work well?
At least for me, yes.

**Comment by photopea** [comment]
You can change the Grid color now. Go to Edit - Preferences.
