### ISSUE TITLE
Scroll bar in layers panel blocks the layer style drop down toggle

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#504]
So when the Scroll bar appears in the layers panel, it also blocks the layer style drop down / fold up toggle, render it unusable

**Comment by photopea** [comment]
What browser do you have? Can you please try another browser?

**Comment by hgs54371** [comment]
I'm on a mac with firefox, just tried on safari it doesn't have this problem

**Comment by hgs54371** [comment]
The scroll bar in firefox is floating above the drop down icon
So it's not clickable right after scrolling, have to wait like a second or two for it to disappear first.
![screen shot 2018-03-15 at 4 13 17 am](https://user-images.githubusercontent.com/36803688/37428558-91711f4c-2807-11e8-978b-83163d2a1036.jpg)

**Comment by hgs54371** [comment]
They look and behave the same

**Comment by photopea** [comment]
Then I guess you should wait for it to disappear, then click the arrow. In general, scrollbars should not interfere with the page area. Otherwise, I think it is a bug in Firefox.
