### ISSUE TITLE
Rulers and Scrollbars [feature-request]

### ISSUE THREAD

**Issue by rokobuljan** [photopea/photopea#5040]
Feature request: Rulers and Scrollbars 

(PS: I could not find that option anywhere + I know that using Space+Drag we can reposition the draw area)

I know this is a hard one but, would be _nice-to-have_: 

-  **Scrollbars** in the **canvas area** (like i.e: Photoshop, as a mean to move/pan without keyboard shorthand)
- **Rulers** (px or other units) on the top and left of the canvas area (where 0/0 points at the canvas origin)

**Comment by photopea** [comment]
I really think they are not useful, they only take a screen space. You can scroll with a mouse wheel (ctrl+wheel for horizontal), or with two fingers on a trackpad or a touchscreen. There is a Hand tool, too. There is also Window - Navigator.
