### ISSUE TITLE
Drag and drop of images between two tabs no longer possible

### ISSUE THREAD

**Issue by riru90** [photopea/photopea#5041]
When I try to drag and drop an image or text from tab 1 to tab 2, it doesn't work anymore for some time and a strange line appears on the screen (see screenshot). please fix it so it's just dragging and drop again between the 2 tabs (tested in chrome, edge, firefox and safari)
![photopea_error](https://user-images.githubusercontent.com/115423844/194773617-b6060e5e-23a9-4b9a-b227-1659a23abe1f.png)

**Comment by photopea** [comment]
Hi, copying layers by dragging them to another tab works perfectly for me in Photopea.com

Could you record a video of what you do, and start by opening [www.Photopea.com](http://www.photopea.com/) , so that I can try the same thing as you do?
