### ISSUE TITLE
Angle measurement

### ISSUE THREAD

**Issue by CodingNix** [photopea/photopea#5043]
I can't find a way of doing angle measurements like in the image. I think it would be a very useful resource.

![](https://www.aljabri.com/blog/wp-content/uploads/2018/12/forward_vs_recessed.jpg)

**Comment by MichalSZZ** [comment]
It can be done just like in Photoshop:

1. Use the Ruler tool (it is hidden in a place where Eyedropper is).  "I" Shortcut (Shift+I to switch from Eyedropper)
2. Draw the first line
3. Holding "ALT" (option on mac) draw the second line from one of the line ends.

**Comment by photopea** [comment]
That is right, angles can be measured with the Ruler tool.
![image (1)](https://user-images.githubusercontent.com/15955558/195628138-926f4c82-96cd-4356-b121-25cddc25a3a3.png)
