### ISSUE TITLE
Exporting layer combinations causes page to be unresponsive

### ISSUE THREAD

**Issue by MoeBuckz** [photopea/photopea#5046]
After structuring 26 layers and attempting to export layer combinations; page becomes unresponsive shows error message to wait or close page. when clicking wait unresponsive error begins to loop
<img width="1154" alt="Screenshot 2022-10-10 201343" src="https://user-images.githubusercontent.com/115511822/194970863-8cf7fbb2-cb38-454a-8172-665a5e5ed289.png">

**Comment by photopea** [comment]
I have fixed it. Now, every second, you will get a message saying how many images has been exported so far.
