### ISSUE TITLE
Editing of text in the text layer not undoable

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#505]
I once accidentally replaced a paragraph with a single alphabet, but I found it undoable with the undo function, which is very dangerous if not being careful.
The undo function should also be functional for text field in the text layer

**Comment by photopea** [comment]
After you "commit" a text change, it is saved as one item in the History. If you type and delete "a" twenty times (by repeatedly typing "A" and backspace), it would be stupid to store it as fourty separate items in history. Step Back / Forward works only for history items.

While you have entered a text layer, you should be able regular shortcuts, that work in your browser for editing text in form items.
