### ISSUE TITLE
Crashes when uploading a file

### ISSUE THREAD

**Issue by marketingmd** [photopea/photopea#5050]
Every time I try to upload a file .sketch it comes up with a "page cannot be displayed" if I resize it or leave at original size.

**Comment by photopea** [comment]
How large is your Sketch file and how much RAM do you have? Is it a phone or a desktop device?

**Comment by marketingmd** [comment]
It’s 1281 MB, is that the problem? Sorry about thinking it was a bug on your site.

**Comment by photopea** [comment]
Yes, since Photopea is a raster editor, it needs a lot of RAM to rasterize vector objects. So your Sketch file might need 30 GB of RAM to be converted  into an editable PSD file.
