### ISSUE TITLE
Photopea deleted every file by itself

### ISSUE THREAD

**Issue by raivologo** [photopea/photopea#5052]
Hi! It's me once again.

So, I'm recently working of a huge project, lots of layers and such. But when I was working on one of the layers, everything disappeared, Photopea glitched out, so I closed it and opened it again. When I tried opening my project again, it said it was empty, and had 0KB.

How can I recover the file how it was before that happening?

**Comment by photopea** [comment]
A browser might kill a website when there is not enough RAM memory.

If your RAM is too small, or your documents are too large, save your work regularly, e.g. every 20 minutes. Go to Edit - Preferences and enable "Remind me to save".

If you did not save your work properly, there is nowhere to "recover it from". We do not have any cloud storage and a website can not write stuff to your hard drive.
