### ISSUE TITLE
Quick selection tool is so vague

### ISSUE THREAD

**Issue by MatiazTa** [photopea/photopea#5054]
When i try to select something with quick selection, it selects almost everything in one or two clicks (same as substracting selection)

This doesn't happen in photoshop, in photoshop it allows you to use the tool as if it were a brush and here it is as if it were another magic wand, please fix the tool

**Comment by photopea** [comment]
I dont know how to make it better :( just use Photoshop instead, if you already have it.

**Comment by MatiazTa** [comment]
bruh
