### ISSUE TITLE
Unknown File Format u0000/u0000/u0000

### ISSUE THREAD

**Issue by cmcjenkin** [photopea/photopea#5055]
Trying to open images that I shot with my phone and it won't open them. Keep getting the same error.

The details:
Took pictures on my iPhone and moved them to my computer.
I have changed the file format via Save As/Export from another tool to jpg, jpeg, and png, still wont open any of the formats.
Photo's are 1.5+/-mb, I have verified file formats and other details.
Running Chrome, up to date, both incognito and regular windows have the same problem, machine is Windows 11 Pro.
Cleared cookies and cache. Logged out of my paid version and back in.

What else can I provide to source a remedy?

**Comment by photopea** [comment]
So you have a JPG file, which can be opened in every program except of Photopea? Could you show us your file? Attach it here in a ZIP archive.

**Comment by cmcjenkin** [comment]
See attached.
![20221014_145418427_iOS_png](https://user-images.githubusercontent.com/115835588/195940893-102291dc-097b-4f72-b5e4-2797c667833f.png)
![20221014_145418427_iOS_jpeg](https://user-images.githubusercontent.com/115835588/195940895-54499778-5923-43cd-9575-d235edcaed03.jpeg)
![20221014_145418427_iOS](https://user-images.githubusercontent.com/115835588/195940957-efa308e0-80ef-4c6a-b995-581f0ea2da4f.jpg)

**Comment by photopea** [comment]
These are HEIC images, not JPG. E.g. you can not open them in a web browser (if you click the links in your comment).

Press Window - Plugins, and use the HEIC Plugin to open your file.
