### ISSUE TITLE
page display not working in Safari - Aspect messed up

### ISSUE THREAD

**Issue by dfarness** [photopea/photopea#5056]
Attached a screen shot of the issue and what the image should look like. 

![Screen Shot 2022-10-14 at 4 49 17 PM](https://user-images.githubusercontent.com/34730219/195958637-404218f6-1e2e-420c-a4ce-850c2ab6acbe.png)
![PA140036](https://user-images.githubusercontent.com/34730219/195958645-6e866769-c629-42e5-812e-c63a2d8b2dd9.JPG)

**Comment by photopea** [comment]
When I open your image in Photopea, it looks correctly. Do you have this problem with all images that you open in Photopea? Did it work correctly before? Can you update your Mac OS?

**Comment by dfarness** [comment]
This happens with all images. I am running the latest update to Mac OS.
I'm using a 2014 Mac Mini.  I think it happened after the Safari update.

I found the solution on my own.

Here it is:
1 In Safari preferences select "show develop menu in menu bar"
2 In develop menu choose "Experimental Features" and uncheck "WebGL via
Metal"

**Comment by photopea** [comment]
I still think it is a bug in your device. There are millions who use Photopea on Apple devices, and nobody reported such problem.

Is the "WebGL via Metal" enabled by default? If you enabled it and it caused problems, it is probably better to disable it.

**Comment by dfarness** [comment]
Yes. "WebGL via Metal" is enabled by default. It is possible my graphics
card is having an issue but it doesn't show up in any Apple diagnostics.
Also, I just did a clean install to the latest version of MacOS a few weeks
ago.
I'm not saying this is necessarily a photopea issue but I wanted to share
this solution for anyone else that might run into this issue.

**Comment by dfarness** [comment]
FYI This does not happen on my 2017 macbook air. Even with "WebGL via
Metal" checked.

Could be a 2014 Mac Mini issue.
