### ISSUE TITLE
Accidentally merging layers with keyboard shortcuts

### ISSUE THREAD

**Issue by plohoj** [photopea/photopea#5058]
I often use the eraser [E] but sometimes I accidentally press [Ctrl+E] which causes the layers to be merged. I notice too late that my layers have been merged.

I read in one of the issue (#2687) that it is difficult to implement the hotkey setting.
I would like to be able to disable some keyboard shortcuts, or at least see a notification that the layers have been merged (to undo the last action).

**Comment by photopea** [comment]
That would be too complicated. Just be careful with what you press on your keyboard. If you merge layers, you can always do a step back (Edit - Step Backwards).
