### ISSUE TITLE
Export individual artboards (esp. for SVGs)

### ISSUE THREAD

**Issue by trevordunn** [photopea/photopea#5061]
I'd like the ability to export a single artboard as a png, svg, etc. Right now there is an "Artboards" option when exporting, but it's behavior is weird (e.g. the width/height values seem to be ignored) and it's not available for SVGs. Would be nice if I could just target a single artboard in the "Save for web" panel, change my settings, and export it.

**Comment by TheRadicalDreamer** [comment]
If you turn invisible some artboards, it will only export the visible ones

**Comment by trevordunn** [comment]
@TheRadicalDreamer Even with that though it still doesn't export artboards individually. E.g. if I have two artboards, one on the left and one on the right, and I hide the left one, if I try and export a png or svg then there's just a blank space where the left one was and the exported image isn't just framed around the right artboard. It's weird. Artboards should be treated as completely separate images when exported and not merged together... that's kind of the point of them.

**Comment by TheRadicalDreamer** [comment]
Let's divide this issue in 3 so they can work on each feature separately. Let me help you

**Comment by TheRadicalDreamer** [comment]
I've created these issues: https://github.com/photopea/photopea/issues/5079 and https://github.com/photopea/photopea/issues/5080

So the dev can see them isolated

But i don't get the issue with the blank space.  I did create an artboard and exported in PNG and i've got the borders correctly on each artboard

![Artboard 3](https://user-images.githubusercontent.com/11801254/198324460-b76c49ea-18f8-4d0d-929b-40400d7c725b.png)
![Artboard 1](https://user-images.githubusercontent.com/11801254/198324469-b70a367d-aa6c-4ffd-86bc-c32137ff963e.png)

Here is the PSD:
[New Project artboards.zip](https://github.com/photopea/photopea/files/9880570/New.Project.artboards.zip)

**Comment by photopea** [comment]
To export a single layer, folder of layers, or an artboard, use the Quick Export button at the top (while using the Move tool).

![image (3)](https://user-images.githubusercontent.com/15955558/199188022-fc0e9b2e-dba9-40a4-b1ef-86ef72ffda16.png)
