### ISSUE TITLE
Feature request: way to turn off transparent menus

### ISSUE THREAD

**Issue by aporia-cc** [photopea/photopea#5063]
A recent update seems to have made all photopea menus transparent, showing through a blurred version of whatever is on the canvas. Personally I find this very distracting and it also seem to add quite a load onto my older computer so that now menu navigation feels more sluggish than before. It might be a neat feature to others but could you please consider adding a toggle to turn this off? Here is an image of what I mean. The menus used to be solid black.

Thanks for your time.

![Untitled](https://user-images.githubusercontent.com/52726013/197067075-73a77f72-f391-4f02-a3c8-1d88096c251d.jpg)

**Comment by flingrocks** [comment]
Looks bad too if the web browser doesn't support backdrop-filter, since lack of a fallback provided means menu background is then completely transparent. So for starters, might I suggest using a feature query in CSS, so a `@supports (backdrop-filter: blur(24px))` section for the rule (default rule being outside before that).
Then, there is whatever performance cost associated with backdrop-filter to consider, which may make having a choice welcomed.

**Comment by MichalSZZ** [comment]
@aporia-cc @flingrocks please read https://github.com/photopea/photopea/issues/5038 there are my sugestions to let users to choose an aption of menus' background.

**Comment by photopea** [comment]
What browser does not support backdrop-filter ? Was it updated in the last five years?

**Comment by flingrocks** [comment]
True, more browsers do support it than had a few years ago. 
Firefox has had it now for around 80 days, I think. The Firefox ESR release was like 3 days ago, but that is 102.4.0, just shy of the version 103 features.

**Comment by vendoNZ** [comment]
maybe lower the amount of transparency so it is more subtle, set background transparency to say 95%. If the background is white it can be hard to read the menu items.

**Comment by photopea** [comment]
But why? is it hard to read? Could you share a screenshot?

**Comment by vendonz** [comment]
Certainly. Note that this is an issue for "older" people like me who have more difficulty with low contrast text (google: reduced contrast sensitivity)
![New Project](https://user-images.githubusercontent.com/116385416/197363609-ebdbdd37-d79e-4800-a390-98bf6627b2ab.png)

**Comment by photopea** [comment]
There is a big group of people wanting the old style of menus, and people wanting the new style. I can make it switchable in settings, but I think 99.9% of people would use it under the default settings (as they will not know they can change it).

So the question is, what should be the default look? Could you discuss it with each other and agree on one style?

See here: https://github.com/photopea/photopea/issues/5038

**Comment by vendonz** [comment]
the effect is nice, it is common in most desktop applications menus, its just that your effect has too much contrast. If you browse the [apple.com](https://www.apple.com/imac-24/) website you will see it in the sticky header but it is more subtle so you barely notice it. You don't have to change anything, it is still readable, its just that for a small number of people low contrast text causes eye strain, so maybe just tone it down a little :)

**Comment by martinszeltins** [comment]
If I had to vote then I would vote for the new look as the default with an option to witch back to the old one. The old menus feel like legacy compared to the new ones which look much more modern.

**Comment by xan2622** [comment]
If an option is added to choose the style of menus, please let the user choose between:
- the [new half-transparency one](https://user-images.githubusercontent.com/52726013/197067075-73a77f72-f391-4f02-a3c8-1d88096c251d.jpg) 
- the [previous white menus](https://user-images.githubusercontent.com/34019878/194753378-e924fa5c-5100-4d5b-ba34-c8b2b3bd906f.png)
- a [dark menu with solid colors](https://user-images.githubusercontent.com/38118273/195604474-d2b16638-d9d2-4243-ba4f-d09098ea5cdd.png) (this is the one that I would pick)

**Comment by MichalSZZ** [comment]
@xan2622 it was my sugestion too. Like themes. If someone like the white theme it is in the option like many other themes. It should work like that for menus too. But the modern one should to be as default - maybe with 0.5 alpha (if now it is still ~0.35 - I didn't check it for last week.)

**Comment by aporia-cc** [comment]
My strong preference would be to have solid color menus back. I think ultimately form should serve function. A solid menu is easier to read and less distracting, while the only function I can think of for transparent menus is having it look subjectively nicer for only some users. Being distracted by color blobs and straining to read menu lettering is a constant cognitive load for someone who's using the program. It's basically all downside and no upside when it comes to workflow. I don't think that's really worth it if the supposed benefit is simply having the menus look more "modern."

**Comment by photopea** [comment]
I have switched back to white menus, as I think they are much better.

**Comment by martinszeltins** [comment]
> I have switched back to white menus, as I think they are much better.

Will there be a way to choose to switch to the modern menus?

**Comment by photopea** [comment]
You can switch it in Edit - Preferences - Glass Menus.
