### ISSUE TITLE
Hi when i open a project any transparent back ground appears black 

### ISSUE THREAD

**Issue by LthrJockTo** [photopea/photopea#5065]
The transparent background which normally shows as a checkerboard now appears black upon open of either a new file or an existing file.  Using Windows, with a chrome browser. 
Was working ok until this afternoon, is this a setting or is there a bug?

**Comment by photopea** [comment]
Try to restart your browser or your computer. Or try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
