### ISSUE TITLE
How to get rid of these gray grid lines

### ISSUE THREAD

**Issue by dedok3000** [photopea/photopea#5067]
I tried importing [this](https://www.freepik.com/free-vector/pedestals-podium-abstract-geometric-empty-museum-stages-exhibit-displays-award-ceremony-product-presentation-gallery-platform-geometric-blank-product-stands-realistic-3d-set_10308154.htm) .EPS file but for some reason there are these gray lines that remain after export:

![Screenshot_1](https://user-images.githubusercontent.com/29264019/197391108-2105d986-4ceb-403f-89de-e8105ce74f58.png)

They are not supposed to be there, I don't have them in my Illustrator for example. So how to disable them in the editor? Thanks.

**Comment by photopea** [comment]
I think they come from Gradient Meshes, see https://blog.photopea.com/photopea-5-0-open-illustrator-files.html

Photopea is not the best tool for editing EPS and AI files. This is the best we can do. Our main format is PSD.

**Comment by photopea** [comment]
I think you will need to pay for Adobe Illustrator if you need to edit files like this one.
