### ISSUE TITLE
ctrl-click as right click doesn't work on macOS

### ISSUE THREAD

**Issue by gabrielf** [photopea/photopea#5068]
Hi, I'm experiencing issue #2162 when using ctrl-click as secondary click. Right clicks work fine when using any of the gestures but not using ctrl-click. I have no idea how Photopea detects right clicks but I just tried making an HTML element with a `oncontextmenu` event handler and it detects ctrl-click just fine. Maybe ctrl-click has another purpose in Photopea that makes it impossible to support? 

Any of these settings work:
<img width="360" alt="image" src="https://user-images.githubusercontent.com/137649/197404568-2c1a868b-2117-46a8-804e-f52b1d88663c.png">

But deactivating the gesture and relying on ctrl-click does not.
<img width="352" alt="image" src="https://user-images.githubusercontent.com/137649/197404579-5ef3aa3c-a55f-4817-ad3e-4f7789a5a1ee.png">

This is on latest macOS (Monterey 12.6) and latest Google Chrome.

I mainly post this for others experiencing the problem, the work around of activating a gesture is fine for me. Photopea is awesome, thank you! 🙏

**Comment by photopea** [comment]
Photopea requires the Ctrl+click and Alt+click for many shortcuts. You will not be able to use Photopea properly, if you can not do Ctrl+click or Alt+click.

**Comment by gabrielf** [comment]
I suspected something like that, thanks!
