### ISSUE TITLE
Full screen doesn't fill the screen area on the right

### ISSUE THREAD

**Issue by johnnyblz2412** [photopea/photopea#5069]
Im using a huion pen display from my galaxy s10+ which works great but there is a lot of unused space left on the right side of the screen. It would be great if full screen could scale correctly and fill that area or at least allow me to drag the window more to the right. Please see the screenshot attached

![Screenshot_20221023-183908_Chrome](https://user-images.githubusercontent.com/116509775/197405274-cbf4e209-d2b7-450a-8dfe-67508bd3d4ed.jpg)

**Comment by photopea** [comment]
Are you using it in a web browser at www.Photopea.com ?

**Comment by johnnyblz2412** [comment]
Yes, it is through chrome web browser but from a smartphone set in desktop
mode, normal mobile browser mode does the same. Again this is from mobile
phone web browser using samsung Dex outputing the video on a huion pen
tablet 16pro 2.5k.

**Comment by photopea** [comment]
There should be advertisement on the right side. It seems like you are blocking our ads :(

Please, watch our ads! We depend on them. Photopea would not exist if everyone did what you do.

**Comment by johnnyblz2412** [comment]
Interesting as on my phone i've never used anything that blocks ads, to be
honest i've never even looked into it as i had no need for it but man...now
that you mention it like "...everyone did what you do" it hit me hard as it
sounds like you're accusing me of some crime which im not okay with at all
even if i'd use some block addon you probably talk about a user being
unethical by using ad block but how is it ethical on your side to ask for
3€ every month and advertise it as "ONE TIME PAYMENTS ONLY, NO
SUBSCRIPTION" like literally if that's not the definition of a monthly
subscription then i don't know what it is. Also asking for subscription
instead of a fair fixed price is doing exactly what Adobe did wrong to
their customers destroing the future of ownership and that puts you in the
exact same position "IF EVERYONE DID WHAT YOU DO" every software would turn
into trash quickly even your favorite videogame or movie but i guess for
convenience in your case the rule "if everyone does it (like e.g.: adobe)
even if it's bad, why can't i do the same?" wins here so there goes guilt
and all the ethical stuff down the drain right from the bat. I guess i will
be better off using the full featured version of photoshop connected to one
of my PC's and only pay for one subscription instead of 2. Good luck with
the business and ethical lessons.

Best regards,

Paul
