### ISSUE TITLE
Paste image from web as another new project when projects already opened as tabs

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#507]
When there's no projects opened as tabs in photopea, paste an image from web will create a project with its exact same dimension.

But when there's already projects opened as tabs, paste an image will only import it as a layer within the current tab/project.

There's no easy way at this stage to paste that image as another project with the dimensions set automatically and correspondingly.

**Comment by hgs54371** [comment]
Hi, have this been considered, having to adjust each project canvas size to fit each new image is cumbersome when opening multiple projects at a time

**Comment by photopea** [comment]
Today, webpages can not read the clipboard data unless it is pasted (e.g. to read image dimensions in a New Project dialogue). Native apps can do it.

But if you copy pixel data from Photopea, it is saved into internal clipboard, which is used as a default dimension for New Project dialogue. So paste it into a project and then copy it out, create a new Project, and paste again.

**Comment by hgs54371** [comment]
But right now select one random layer and go edit-copy then paste, it's still the image copied from web, and this dimension info isn't show in new project either

**Comment by photopea** [comment]
In a browser, you can right-click an image in a browser - Copy Image URL. When you paste the URL into Photopea, it is opened as a separate project.

**Comment by hgs54371** [comment]
When doing this, it pastes the previous image in clip board to current project AND creates a new project with image from the link
