### ISSUE TITLE
Suggestion: PDF to DWG export

### ISSUE THREAD

**Issue by UltimateOptics** [photopea/photopea#5070]
Hi there,

Could I request a feature to be added to allow for pdf's to be exported into .DWG file format? If it is an editable PDF it identifies the layers/lines on the pdf and creates .dwg lines.

You can do this feature in Adobe Illustrator 

Thank you and great website!
Tom

**Comment by photopea** [comment]
Could you show me such DWG file, so that I can edit it? Can I edit it in a regular PDF viewer?

**Comment by photopea** [comment]
I have to close it because of lack of details.
