### ISSUE TITLE
Templates thumbnails not showing 

### ISSUE THREAD

**Issue by Abeelme** [photopea/photopea#5071]
![Screenshot_20221024_011109_Kiwi Browser](https://user-images.githubusercontent.com/44150697/197425267-ce277a7d-76a4-473a-baf5-9bedec33d61e.jpg)

**Comment by photopea** [comment]
Try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

I think something in your computer is blocking imgur.com , where almost all of our thumbnails are stored.

**Comment by Abeelme** [comment]
> Try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/
> 
> I think something in your computer is blocking imgur.com , where almost all of our thumbnails are stored.

Yes the problem is I can't reach to imgur web site itself 
Thank you so much

**Comment by photopea** [comment]
Maybe get a different internet provider. The one which allows you to visit any website.
