### ISSUE TITLE
i have the premium app version, and i cannot entry to app with my gmail

### ISSUE THREAD

**Issue by Mononinja24** [photopea/photopea#5075]
I need as solution, i from Perú and  i pay the premium version of the app and y cannont acces to this app  with my acount of gmail in my android (galaxytab s8plus)

**Comment by photopea** [comment]
Could you log in in a different way? The same way as you did when you paid for Photopea?

See here: https://www.photopea.com/tuts/premium-account-does-not-work/

**Comment by photopea** [comment]
I have to close it because of lack of details.
