### ISSUE TITLE
Suggestion: Scroll Bar

### ISSUE THREAD

**Issue by AndySixxx** [photopea/photopea#5076]
Kindly put a scroll bar when we zoomed our project in Photopea. It is hard to drag at the main point of the project since the application has no scroll bar.

If the Photopea the said suggestion, please teach me thru email.

**Comment by photopea** [comment]
Learn how to use the hand tool with a spacebar: https://www.photopea.com/learn/navigation . There is a (ctrl + ) mouse wheel for scrolling.
