### ISSUE TITLE
Color Picker won't close and needs to refresh the page

### ISSUE THREAD

**Issue by AndGz** [photopea/photopea#5078]
Steps to try to reproduce the bug
1) Have a background layer
2) Create new Adjustment Layer ex:  Replace Color.. , Gradient Map.. (that has the opportunity to use color picker)
3)  I have created Replace Color - then clicked the color icon from the Properties tab
4) Because it is selecting the mask of the Adjustment layer to be active by default I always change it, to be able to pick the color needed not the color of the mask
5) While the color picker it is opened I miss-clicked on the background layer and now the OK or X close button won't react and that make the Photopea to not work properly

Found a solution now accidentally also, by using Crop tool it may return some of the normal behaviour.

**Comment by photopea** [comment]
It should be fixed now! When you select a different layer while the color picker is opened, actions inside the color picker will be ignored.

**Comment by AndGz** [comment]
Works great, will not have to worry to miss-clicks on other layers
