### ISSUE TITLE
Artboards - Export as SVG

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5079]
It would be great to be able to export the Artboards as SVG. Especially when i work solely in vectors.

Right now only PNG, JPG and PDF has this option:
![image](https://user-images.githubusercontent.com/11801254/198320779-b5f3c217-0f4f-42ea-8399-4a24c570b74f.png)

SVG doesn't
![image](https://user-images.githubusercontent.com/11801254/198320786-36e1dc40-92cc-4d96-9565-4f37c2e99d57.png)

**Comment by TheRadicalDreamer** [comment]
Also, when the Artboard option is checked, can we have a difference in the preview? Like a gallery or something that let's you see the exported images individually? Like PDF does with the pages.

**Comment by photopea** [comment]
We have added the checkbox.
