### ISSUE TITLE
Artboards - Artboard size is ignored when exported

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5080]
I have an artboard 100x170 cm, and a DPI of 100 px/cm 

When exported i get an image of 1000x1700 pxs.

Shouldn't be 10.000x17.000 pxs?

![image](https://user-images.githubusercontent.com/11801254/198322957-ee12f46f-e428-4f7e-9342-e29f84d3bafc.png)

**Comment by photopea** [comment]
I made an artboard of 100x170 cm, 100 pixels per cm. The exported size is 10.000 x 17.000 pixels.

Please, describe how to reproduce the issue.

You mention "1000x1700 pxs.", but your screenshot says "1000 x 2000"

**Comment by TheRadicalDreamer** [comment]
I post the wrong screenshot.

Even though, i've understood my mistake.

I wasn't  converting mm to cm, that's why.

It is all fine now.

 If you could add CM to the drop down list for Image and canvas size
![image](https://user-images.githubusercontent.com/11801254/200023656-b046ebf0-7c3d-4d8e-9240-4c528fc808a0.png)


It would be cool :)

**Comment by photopea** [comment]
Ok, I have added centimeters :)
