### ISSUE TITLE
Fonts and Brushes not saving

### ISSUE THREAD

**Issue by amiv112** [photopea/photopea#5082]
I have a premium account. 
For about a month now, none of my presets are saving even logged in. I've had to load fonts, brushes, and patterns multiple times but they only stay during the session. If I close out of the app or even the browser version, all those loads disappear.

Is anyone else having this issue? How do I fix this?

**Comment by photopea** [comment]
First of all, Photopea works the same for those who pay and who do not pay.

When you load a font into Photopea, are you asked to save it in a Local Storage? You could be using a browser extension, which blocks or clears the loacal storage.

**Comment by amiv112** [comment]
Correct, it does ask for me to save it in a local storage. I'm going to disable any browser extensions and try again.
Fingers crossed it works. 
Thanks!

**Comment by photopea** [comment]
Did it help?

**Comment by photopea** [comment]
I will close it, as I think it helped.
