### ISSUE TITLE
Photopea - The Mix Arab Font  Issue

### ISSUE THREAD

**Issue by newuser202219** [photopea/photopea#5084]
Greetings,

 I encountered an issue with the font named Mix Arab, as it shows the letters separately. 
For example, instead of appearing like this "مرحبا", it appears like this "م ر ح ب ا".
I've checked the tracking, it is at 0%, and I don't have this issue with other fonts.

Thank you in advance for your help.

**Comment by photopea** [comment]
A font preview is written like this (incorrectly). But once you start typing, it should be typed correctly. Is that right?

**Comment by newuser202219** [comment]
Once I start typing the letters appear separated

**Comment by newuser202219** [comment]
This is how it looks.

![Uploading IMG_20221031_171541.jpg…]()

**Comment by newuser202219** [comment]
![photopea](https://user-images.githubusercontent.com/117099736/199057871-2e75a938-c938-49e9-b855-83a3c039e376.JPG)

**Comment by photopea** [comment]
Did you load this font into Photopea yourself? Can your font be used properly in some other program? Maybe it is an error in the font.

**Comment by newuser202219** [comment]
Yes I loaded it myself. It works with Photoshop.

![photopea](https://user-images.githubusercontent.com/117099736/199064688-de75adcb-a85f-4b98-a7cf-8ca4caae0cf6.JPG)

**Comment by photopea** [comment]
Could you send me your font? In what year was it made?

**Comment by photopea** [comment]
You can attach it here in a ZIP file.

**Comment by newuser202219** [comment]
Sorry, I couldn't find out what year it was made. I just downloaded it from a website. 
[TheMixArab.zip](https://github.com/photopea/photopea/files/9903358/TheMixArab.zip)

**Comment by MichalSZZ** [comment]
This font is probably from 2007. 
Maybe it is problem with ligatures?

**Comment by photopea** [comment]
In short, your font is too old (from 1994) and our current text engine can not handle it. Find a newer, Opentype version of the font.

**Comment by newuser202219** [comment]
I understand. Thank you all for your help.

**Comment by photopea** [comment]
Ok I take it back.

So I have fixed, your font should work fine now :) But Photopea became 80 kB larger because of this :D

**Comment by newuser202219** [comment]
It works perfectly! Thank you very much for your time and effort. Sorry for the extra 80 kb xD

**Comment by MichalSZZ** [comment]
> Ok I take it back.
> 
> So I have fixed, your font should work fine now :) But Photopea became 80 kB larger because of this :D

Can I ask what was the problem? Only the main topic of the problem. Not the solution - that I will never understand :D

**Comment by photopea** [comment]
I had to attach an extra code (harfbuzz library), which can process these "archaic" fonts.
