### ISSUE TITLE
[Feature request] Implement window-controls-overlay api

### ISSUE THREAD

**Issue by glitch128** [photopea/photopea#5085]
I would like the window-controls-overlay api to be implemented to give Photopea a more app-like experience.

**Comment by glitch128** [comment]
hey, is this ever going to be implemented?

**Comment by photopea** [comment]
Sorry, we are a bit busy with other tasks :( There are issues that were opened in 2020 and still are not closed.

**Comment by glitch128** [comment]
it's literally two lines of code. here you go
[pp.js.txt](https://github.com/photopea/photopea/files/13877787/pp.js.txt)
[manifest.json](https://github.com/photopea/photopea/files/13877788/manifest.json)
I added 
`"display-override": ["window-controls-overlay"],`
to manifest.json, and changed 
`"position:relative; width: "+l+"px; height: "+b+"px; overflow:hidden; white-space: nowrap; "` 
to 
`"position:relative; width: env("+l+"px, titlebar-area-width); height: "+b+"px; overflow:hidden; white-space: nowrap; "`
in pp.js
everything else is the exact same. you can check

**Comment by photopea** [comment]
okay, it should be implemented now :) But I did not implement it for possible browser elements on the left side (such as on Macs).
