### ISSUE TITLE
"Loading" Bar stays

### ISSUE THREAD

**Issue by mtberk1** [photopea/photopea#5086]
Hi,
No matter what I do, Loading bar keeps staying on top of my browser screen. 
Just opening up
Using different browser
Uninstalling pc version
opening a graphic,
saving and closing a graphic.
I tried everything I can come up with but it still stays and its getting annoying since it covers some of the buttons.

When I open it in incognito mode, it disappears, but If I log in, it comes back.

All of this information made me thing it is not a client-side issue. 

Any ideas on how to solve it?

Thank you and have a nice day.
![Ekran Alıntısı](https://user-images.githubusercontent.com/117184666/199251876-b5050ff0-f36b-48b6-afc0-6f1cbaac310b.JPG)

**Comment by photopea** [comment]
Could you go into Window - Plugins - Installed, and uninstall plugins, which are not in our gallery anymore?

**Comment by mtberk1** [comment]
It solved the problem. Thank you so much!
