### ISSUE TITLE
Menu and Tool Bar On Free Account 

### ISSUE THREAD

**Issue by serio1977** [photopea/photopea#5087]
unfortunately lost the menu and toolbar after text input (chrome)
 
![Screenshot_2](https://user-images.githubusercontent.com/106419664/199271000-75f365a7-285c-47d1-b195-f87955549956.jpg)

**Comment by photopea** [comment]
Could you try to update your Chrome? If it does not help, try to disable some of your extensions.

**Comment by photopea** [comment]
I have to close it because of lack of details.
