### ISSUE TITLE
Feature Request: a way to ONLY snap to grid intersections .

### ISSUE THREAD

**Issue by Zachruff** [photopea/photopea#5088]
I am trying to make a boardgame layout, and it would be nice for an option for snapping to only snap to grid points and refuse to stop anywhere else on the canvas. Right now I have my snapto settings like this 
![image](https://user-images.githubusercontent.com/70397032/199270970-c5487c75-ddd7-4b55-8413-dd1f1271072f.png)
but since my grids squares are really big (>100px) I still need to zoom super far in to get the snapping to activate when placing my path points for example
![image](https://user-images.githubusercontent.com/70397032/199272154-edd3dd48-6e17-432f-89d1-7e48ef3953ac.png)

AFAIK in photoshop there is a way to make snap to only snap to the grid intersections which is what i want. Thank you!

**Comment by photopea** [comment]
Snapping "at intersections" is snapping to a "vertical line of a grid" and to a "horizontal line" at the same time. So if you move to a point where it snaps both, you got it. What exactly is the problem with the current way?

I have never heard of any software that "snaps at intersections". So it is hard to tell if it is actually useful.

**Comment by Zachruff** [comment]
Ah sorry, that is what I mean. My example picture is poor but when only snapping to grid is enable its still possible to drag points on areas that don't have a vertical or horizontal line which is still somewhat annoying

**Comment by photopea** [comment]
Are you using Photopea on a touchscreen with a finger? Try to get a stylus to be more precise.

Sorry, but we implement only features, which are useful to a large group of people. I dont think this is.
