### ISSUE TITLE
PSD File stuck on "saving..."

### ISSUE THREAD

**Issue by Zachruff** [photopea/photopea#5089]
![image](https://user-images.githubusercontent.com/70397032/199279382-6ea59081-47d9-4d39-8e5e-f3834557e765.png)
Hi, i have been working on this PSD file for a while and when I went to save it it got stuck on the saving prompt. I tried different ways of saving the pds file and none worked (although the png export did work).

I opened the psd file that is on my desktop and it is still the old revision meaning it has not yet saved. I am scared to touch anything now but is there any way you can salvage it before all my work is gone? Thank you.

**Comment by Zachruff** [comment]
![image](https://user-images.githubusercontent.com/70397032/199286641-baa472ee-667e-41aa-8d28-644ae8050655.png)
the interface still works, but when testing i had hidden/showed some layers and now stuff is starting to break. Additionallyy i had the save reminder featured enabled but it only decided to show up after this issue occured. Is there any form of true autosave planned/implemented yet?

**Comment by Zachruff** [comment]
Update: moving the old .psd document out of the folder it was in, then saving again in a new location caused the save to be "successful" this time. All the other saves created a 0kb psd file. This time the psd file actually has stuff in it but when i re-open the saved psd file it seems like it was corrupted during the save and looks like how it did in the screenshot above

**Comment by photopea** [comment]
Could you describe, what should we do to see such behaviour ourselves? Can you make this behaviour happen again?

You could be using browser extensions, which modify files saved by websites. Click here to see which of your extensions are allowed to modify the beahviour of Photopea.
![image (5)](https://user-images.githubusercontent.com/15955558/199577509-61c71f57-354b-4d20-a205-a92108be597f.png)

**Comment by Zachruff** [comment]
sadly it seems I am unable to re-create it, but It might have been that it was a too big PSD.it was originally like 11000x8000 px which made the program very slow, I then made it half as large (5000x4000) before trying to save

**Comment by photopea** [comment]
If your RAM memory is low, your browser could stop the saving process of our webapp. If you know your RAM is low, and you work with large documents, save your work at least every 20 minutes, just to be sure.
