### ISSUE TITLE
Won't allow me to resize image every time I click off of it 

### ISSUE THREAD

**Issue by AmityBlight** [photopea/photopea#5090]

**Comment by AmityBlight** [comment]
> 

What do you mean I don't know how to? Of course I do! But this is a whole different situation, every time I click off an image, to **for example** recolor or edit another image, it _doesn't_ want to resize when I _click back on the previous image again_, the _free transform_ edit tool is usually automatic when I click on the _said_ image, but it doesn't appear to resize it in any way, here let me show you what I am talking about down below, I screen recorded it just in case.

https://user-images.githubusercontent.com/73378234/200070522-babc0f7d-75be-4757-8ffa-b33b2ca51167.mp4

**Comment by photopea** [comment]
Enable "Transform Controls" at the top, I guess that is what you had in the past.
