### ISSUE TITLE
Photopea only pretended to save

### ISSUE THREAD

**Issue by FlarosOverfield** [photopea/photopea#5091]
I was working on a project for four hours, and repeatedly pressed CTRL+S. Every time i did, the "saving..." window appeared, but the asterisk on the title remained. I couldn't figure out why until four hours in, when Photopea froze. When i reopened the project, all my progress was gone, back to four hours ago. I must have pressed CTRL+S 24547652705692106596405646547156230 times during those four hours.

**Comment by photopea** [comment]
Have you ever been able to save a PSD propertly to your computer? You could be using browser extensions, which do not allow any website to save anything to your computer.

If you can make the problem happen in some regular browser with no extensions, please, tell us, what should we do to see the bug ourselves. Or record a video of how you make Photopea "not save" a file.

**Comment by photopea** [comment]
I have to close it because of lack of details.
