### ISSUE TITLE
Loading Bar covers options

### ISSUE THREAD

**Issue by rspalding23** [photopea/photopea#5092]
The loading bar never goes away, which means I can't access certain options.
This happens when I am trying to use text especially.

**Comment by photopea** [comment]
Could you show us a screenshot of what you mean?

**Comment by Apollo1290** [comment]
![Screenshot 2022-11-04 9 15 18 AM](https://user-images.githubusercontent.com/117461133/199997565-49f00973-59ed-4972-9e09-561be7ece62b.png)

**Comment by photopea** [comment]
Look into Window - Plugins, uninstall certain plugins (often, people upload nonsense as a plugin, which leads to this bug).

**Comment by rspalding23** [comment]
Uninstall certain plugins?
a nonsense plugin, could you be a bit more specific?
The same bug appears while using different browsers, on different computers, and for different people. 
This NEVER used to happen just a few months ago, and I haven't added plugins since, but the problem now occurs often for lots of people.
 

![chrome extensions](https://user-images.githubusercontent.com/117280315/200040824-88e9a1dd-cb77-4789-9c7d-a0c850700a41.png)

**Comment by photopea** [comment]
No, I mean Window - Plugins in Photopea.com 
![image (1)](https://user-images.githubusercontent.com/15955558/200122904-7dcb9b3e-62ac-4b55-b991-b6f7ea42460e.png)
