### ISSUE TITLE
Crop Tool, Uncropping canvas when a change has been made

### ISSUE THREAD

**Issue by Winter2552** [photopea/photopea#5093]
I'm currently editing a smart image on a 100mb+ file,
The smart image canvas size keeps reverting back to its original size when a significant change has been made, such as a delete or a transform tool use. I've put what happens when you delete after a canvas crop below, hope you can find a fix :)
[Link in-case embed is being annoying :)](https://gyazo.com/79c782f732b0599065b959e6fbd22c4f)
PS your doing an amazing job on this piece of software! 

https://user-images.githubusercontent.com/24249738/199594331-135e2203-a07b-4e76-905f-2f9f6ce2d105.mp4

**Comment by photopea** [comment]
It is not clear what you did in your video. Can I somehow make it happen myself? Do I need your file?

**Comment by Winter2552** [comment]
Hi!
I initially cropped the canvas, then deleted an element by pressing del, I didn't have much time to show as I was recording with gyazo.
I'll link the file I was working on [here.](https://drive.google.com/file/d/1IsymQNRnlOzWwQlBYHJIVzbZdWGw_76P/view?usp=share_link)
![Screenshot 2022-11-02 212113](https://user-images.githubusercontent.com/24249738/199605214-37d8e20e-8977-4f78-b7c0-1197ac49e84d.png)
You then open the smart image BACK 29 EDITABLE, either will do, and then delete anything from the hierarchy and you should hopefully get the result seen in the video

**Comment by MichalSZZ** [comment]
@Winter2552  in your case shown in the video, it looks like deleting a shape layer is making a function that is called - "reveal all". Menu image - reveal all. How did you delete a layer? What shortcut did you use? Is that problem appears when you delete a layer when you have another tool active (not crop tool)?

BTW. @photopea  in the menu Image there is an option called Trim - with the Shortcut "Ctrl + ." I tried that shortcut and it doesn't work for me. In Photoshop there isn't such a Shortcut.

**Comment by photopea** [comment]
@Winter2552 I am afraid I can not reproduce what you describe. Could you find exact steps, which lead to the problem every time, instead of "hopefully"? :D 

@MichalSZZ "Ctrl + ." works the same as Image - Trim with default settings in my case.

**Comment by Winter2552** [comment]
Hi @MichalSZZ, I used my del key to delete the layer. And yes the same thing happens when I use the move tool, I’ll see when using other tools and delete the layer using del also causes the same issue.

**Comment by Winter2552** [comment]
Hey @photopea apologies for the late reply, I was at work.

I've done some more screen recordings, this time on a fresh open of the project I sent you.
https://user-images.githubusercontent.com/24249738/200067485-52334201-1e75-4db9-a239-82ce416d8069.mp4

It does it on any change, whether that be a delete layer or moving an object.

My only thought of what the cause could be is that the original canvas size was double in height and it seems to be reverting to those dimensions whenever a change happens in the timeline, even though there is no content in that area.

https://user-images.githubusercontent.com/24249738/200067795-738a4503-b47b-4b4e-9707-9e968aa57298.mp4
I don't know if it's some cache in my browser that may be affecting it, is that something photopea stores?

**Comment by photopea** [comment]
I just tried to edit your PSD in Adobe Photoshop, and it does the exact same thing in Adobe Photoshop.

The document inside your smart object contains an Artboard, that is larger than the current canvas (I dont know how you achieved it). You should make that artboard smaller, see https://www.photopea.com/learn/artboards

**Comment by Winter2552** [comment]
Ahhh that would explain it thank you for clearing it up :)
