### ISSUE TITLE
Guides disappearing

### ISSUE THREAD

**Issue by cricketcoded** [photopea/photopea#5096]
I'm trying to create a guide positioned at a certain vertical percentage of the image. The guide only appears for a split second when I press OK - only for the duration of when I am actively clicking the button - before either disappearing or moving elsewhere on the canvas. If I add two guides, at 33% and 66% for example, only one will appear. The other will be pushed off the screen. It seems as though the guide numbers keep multiplying. Attached are images of creating the guide, what happens when I press 'OK', and then what the numbers appear as when I go back in to edit the guides. It only seems to be impacting the percentage option of adding guides. 
![a](https://user-images.githubusercontent.com/117485066/200073939-a09179cb-4a54-437d-895f-6153558c7d67.PNG)
![b](https://user-images.githubusercontent.com/117485066/200073944-a5d96e54-96c4-4531-b512-48b40f1e35e5.PNG)
![c](https://user-images.githubusercontent.com/117485066/200073948-997a320f-5048-4760-bfd8-8179e932a44a.PNG)

**Comment by photopea** [comment]
I am very sorry, it should be fixed now.
