### ISSUE TITLE
loading stuck

### ISSUE THREAD

**Issue by BaranBRTTKY** [photopea/photopea#5099]
my project is not opening. its stucks at loading. i tried at phone, another browser and another pc.
could someone send thit psd to me? https://www.photopea.com/#tQLzPWOfm
![193123352-1a3cec76-d979-45b6-8c0e-cef04050be7c](https://user-images.githubusercontent.com/71255944/200181411-591a09f0-1e79-4979-81a9-f9f9c2264e64.png)

**Comment by photopea** [comment]
I can open it fine. Could you try to disable all your browser extensions? Maybe they are blocking our cloud.

If it still does not work, your internet provider is probably censoring your web content.

**Comment by BaranBRTTKY** [comment]
can you send me psd?

**Comment by BaranBRTTKY** [comment]
hey?

**Comment by photopea** [comment]
There is something wrong with your computer. Try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by BaranBRTTKY** [comment]
not working

**Comment by photopea** [comment]
Did you try the incognito mode? Can you open https://www.backblaze.com/ ?

**Comment by BaranBRTTKY** [comment]
yes

**Comment by photopea** [comment]
Do you see any errors in a web console when opening a template? Could you send us a screenshot?

Also, could you send us a screenshot of about://extensions ?

**Comment by BaranBRTTKY** [comment]
![image](https://user-images.githubusercontent.com/71255944/200355084-30ac6f5d-d882-4784-a441-1c032a637891.png)
![image](https://user-images.githubusercontent.com/71255944/200355054-d32a59d4-5e38-46bf-87d8-9870a46774ac.png)

**Comment by photopea** [comment]
So when you click https://f000.backblazeb2.com/file/psdshared/jkjhuw7U , can you download the file?

**Comment by BaranBRTTKY** [comment]
no
![image](https://user-images.githubusercontent.com/71255944/200372541-3a753b06-0443-4f84-90f5-b6294b51eb9f.png)

**Comment by BaranBRTTKY** [comment]
no
![image](https://user-images.githubusercontent.com/71255944/200372541-3a753b06-0443-4f84-90f5-b6294b51eb9f.png)

**Comment by photopea** [comment]
That is a regular web address, which should be accessible on every device connected to the internet.

Ask your internet provider why are they blocking that address.
