### ISSUE TITLE
Scroll issue when selecting type

### ISSUE THREAD

**Issue by tomasnosek** [photopea/photopea#51]
When you select type tool and try to change font in toolbar, screen scroll and hide part of UI.
![type_scroll_err](https://cloud.githubusercontent.com/assets/20184728/16413119/40f1931c-3d30-11e6-9530-d81f73bd217c.png)

It's happen everywhere - chrome, ff, edge, so it's not a browser problem

**Comment by photopea** [comment]
Oh, I am sorry. It should be fixed now.

**Comment by tomasnosek** [comment]
what a speed! :) Works perfectly now
