### ISSUE TITLE
Text tool is not working

### ISSUE THREAD

**Issue by karthickraja96** [photopea/photopea#510]
Hello photopea, text tool is not working this is the first time am using  that tool. Can you please solve this issue.

**Comment by photopea** [comment]
Hi, can you tell us what exactly happens? Do you use it according to the manual?

**Comment by karthickraja96** [comment]
Hello, where can i see the manual?

**Comment by photopea** [comment]
Hi, here is the manual: https://www.photopea.com/learn/text-layers

**Comment by karthickraja96** [comment]
Wow! Thank u so much. I've been trying to type in a plain background the
text is not appeared .Now i tried by uploading an image it worked. Sorry
the mistake is on my side.😐

**Comment by photopea** [comment]
No problem :) you can read the rest of the manual, too!  

One hour of reading it can save you 100 hours of struggle in the future :)

**Comment by karthickraja96** [comment]
Kudos to the creator and the team working under client interaction. May i
know which country is photopea from.

**Comment by photopea** [comment]
Hi, I am the only developer, I am from the Czech Republic :)  https://blog.photopea.com/creating-photopea.html

**Comment by karthickraja96** [comment]
Dear Ivan Kutskir,

Nice to meet you sir. Happy to see such an young talent. You became one of
my inspiration. Im sure im gonna follow you in every social networks.🙂

**Comment by nenarahin** [comment]
Hi Photopea , textbooks tool is not working . When I select text tool and try to type something, the selected tool automatically changing to another. All other tools working fine. Please help.

**Comment by photopea** [comment]
@nenarahin When you select a Type tool, you should click into the document, to create a Type layer. Then, you can type. Learn how to use a Type tool here: https://www.photopea.com/learn/text

**Comment by nenarahin** [comment]
@photopea I have clicked into the document and type layer is created as well. But when I type something nothing appear on the document instead tools swapping occures.

**Comment by photopea** [comment]
Do you see any errors in a web console? Is your browser updated?

**Comment by andyfork94** [comment]
@photopea I also experience this same problem whenever I type a text, nothing shows on the document

**Comment by photopea** [comment]
@andyfork94 are you using the latest browser? What browser do you use?

**Comment by andyfork94** [comment]
@photopea yes it's up to date I use chrome browser, I tried on my Android and PC but still the same problem

**Comment by photopea** [comment]
Do you see any errors in a web console?

**Comment by andyfork94** [comment]
No I don't see any error

**Comment by photopea** [comment]
That is strange. Do you see "Font Deja Vu loaded" when you click to type? Can you record a short video of what you are doing?

**Comment by andyfork94** [comment]
Yes it's loaded. How do I send the  video across to you?

**Comment by andyfork94** [comment]
I just sent a video to support@photopea.com

**Comment by photopea** [comment]
That is really strange. Do you have any browser extensions? Can you disable them? Or try Photopea in an incognito window?

**Comment by nenarahin** [comment]
I have also send video to support@photopea.com

**Comment by andyfork94** [comment]
@photopea it works when I use incognito tab, it would be better if you could rectify the issue. Thanks for the help

**Comment by photopea** [comment]
Some of your extensions prevents Photopea from rendering vector shapes (characters). Disable that extension, or report it as a bug to the creators of your extension.

**Comment by photopea** [comment]
Some of your extensions prevents Photopea from rendering vector shapes (characters). Disable that extension, or report it as a bug to the creators of your extension. There is no way we can fix it.

Your extension could also close Photopea every time you open it. We would not be able to fix it. Extensions can do anything they want any website.

**Comment by yeetsfje** [comment]
Hi Photopea. I'm trying to use the text tool but nothing is showing up. When I made a text box and started typing, nothing showed up, not even the "font dejavu sans". I used Photopea yesterday and it worked fine. I am trying to do an urgent project. Please help?

**Comment by photopea** [comment]
@yeetsfje Can you try it in incognito window? Can you update your browser?

**Comment by yeetsfje** [comment]
I tried it in incognito mode. worked. thanks so much!

**Comment by photopea** [comment]
That means, that some of your extensions is preventing Photopea from rendering text. Try to disable one some of your extensions.

**Comment by sebastianpatten** [comment]
Yea my browser is hiding all text (running chrome and a few extensions)

**Comment by photopea** [comment]
@sebastianpatten Try to disable all your browser extensions.

**Comment by sebastianpatten** [comment]
Yea i did. Still no workey. I'll try to have a deeper dig tonight

**Comment by photopea** [comment]
Make sure the font is loaded (there is a message at the top about a font being loaded).

**Comment by sebastianpatten** [comment]
Weird - looks like its working now - shrugs.

All I can think of was the fonts were 404'ing from a network request point
of view.

**Comment by photopea** [comment]
Are you using any browser extensions? They could be blocking OTF font files.
