### ISSUE TITLE
Scripting "app.activeDocument.colorSampler()" support

### ISSUE THREAD

**Issue by LoganTimothy** [photopea/photopea#5104]
I looked up photoshop scripts to help find a color of a given point and it said to use "app.activeDocument.colorSampler()". When used within code though it causes the whole script to not work at all. Can this get supported? 

Script i looked up for reference: https://community.adobe.com/t5/photoshop-ecosystem-discussions/how-to-i-get-the-color-value-of-a-a-particular-location-in-the-canvas-via-script/td-p/10667449

**Comment by photopea** [comment]
There is no app.activeDocument.colorSampler() in Adobe Photoshop.

Do you mean app.activeDocument.colorSamplers.add([x,y]) ?

**Comment by LoganTimothy** [comment]
Sorry i was just paraphrasing the whole situation. I just meant anything to do with colorSampler in general.

**Comment by photopea** [comment]
We need to create a Color Sampler tool for Photopea first.

**Comment by LoganTimothy** [comment]
Could a color tool get added?

**Comment by photopea** [comment]
What is a color tool?

**Comment by photopea** [comment]
We have implemented the color sampler tool.

You can use a script like this to retrieve colors from an image: https://stackoverflow.com/a/48192241/978280
