### ISSUE TITLE
Multilayer TIFF files are not properly recognized

### ISSUE THREAD

**Issue by GlebDeryuing** [photopea/photopea#5105]
A large number of TIFF files created in PHOTOSHOP are used in your work. The layers there are images, adjustment layers, masks. When imported into PHOTOPEA, the image is merged into a single layer, although support for TIFF files is indicated, they are not supported correctly. Maybe I am doing something wrong? Thank you for your reply.

I have attached one of the files for testing purposes. 
https://www.mediafire.com/view/nmqazf4waza53rc/0504734_%25D0%25BB%25D0%25B8%25D0%25BC%25D0%25BE%25D0%25BD.tif/file

**Comment by photopea** [comment]
Hi Gleb, is there any software, other than Adobe Photoshop, which can open your TIFF with multiple layers? Or at least tell, that there are more than 1 layer?

**Comment by GlebDeryuing** [comment]
Files can be opened by Krita, but not quite correctly. Each of the files has several layers, like in PSD: in my case (jewelry) - material layer, stones layer, adjustment layers and a hidden source layer of the product photo. Link above has one of them.

**Comment by photopea** [comment]
Can Krita open your TIFF "in a better way" than Photopea?

If your TIFF file can be opened only by Adobe Photoshop, and no other program in the world can open it with layers, why dont you save it as a PSD instead of TIFF?

**Comment by photopea** [comment]
I think you should use the PSD format (which can be opened by many programs) rather than format, that is supported only by Adobe Photoshop.

**Comment by photopea** [comment]
@GlebDeryuing I would like to announce that we support these "PSD-ish TIFF" files now! :) After opening them in Photopea, you can see the same content as you would see in Adobe Photoshop.

See https://github.com/photopea/photopea/issues/6311
