### ISSUE TITLE
When exporting to pdf file is all messed up

### ISSUE THREAD

**Issue by orange109** [photopea/photopea#511]
Please see the 2 documents i exported, one is png (info is hidden) which is totally fine, and the pdf is completely messed up.

The text is right to left Hebrew, and the fonts were uploaded automatically when i imported the psd (the fonts files are on the same folder as the psd)
The psd was originally made in photoshop.

[SEM1 & SEM2 (1).pdf](https://github.com/photopea/photopea/files/1770222/SEM1.SEM2.1.pdf)
![export png ok](https://user-images.githubusercontent.com/28766286/36832159-1ffb4ef2-1d33-11e8-870d-a9cc7dd6d1f7.png)

PLEASE HELP

**Comment by photopea** [comment]
Hi, was that file originally PSD or PDF? Or you created a new one? Can you send us that source file, too?

**Comment by orange109** [comment]
Hi

It was originally a PSD that was created elsewhere (probably photoshop)

Please give me an email address so I could send the PSD

**Comment by photopea** [comment]
It is support@photopea.com

**Comment by photopea** [comment]
Hi. The first issue was, that when you tried to edit text, it assumed that your text is left-to-right. It is fixed now (and you should be able to edit text correctly).

Another issue is saving text to PDF. It is quite a complex task and Photopea does not fully support it yet (especially for non-latin characters). I recommend converting text to a Shape (bézier curves) by right-click - Convert to Shape. Then you can export the correct PDF.
[SEM1 & SEM2.pdf](https://github.com/photopea/photopea/files/1826286/SEM1.SEM2.pdf)

**Comment by kolle1986** [comment]
> Hi. The first issue was, that when you tried to edit text, it assumed that your text is left-to-right. It is fixed now (and you should be able to edit text correctly).
> 
> Another issue is saving text to PDF. It is quite a complex task and Photopea does not fully support it yet (especially for non-latin characters). I recommend converting text to a Shape (bézier curves) by right-click - Convert to Shape. Then you can export the correct PDF. [SEM1 & SEM2.pdf](https://github.com/photopea/photopea/files/1826286/SEM1.SEM2.pdf)

I tried that with one paragraph and after hit save, photopea just frizzed. I have repeated the process couple of times but same thing happened again.

**Comment by photopea** [comment]
To make sure your PDF looks exactly as in Photopea, enable the "rasterize all" option.

We can not tell you more without actually seeing your PSD file.

**Comment by Phantasm4X20** [comment]
﻿ Viking - Ladies - Back - Sleeves Ramm 22x240.psbJason RammOn Wed, Apr 26, 2023 at 1:03 PM Photopea ***@***.***> wrote:
To make sure your PDF looks exactly as in Photopea, enable the "rasterize all" option.
We can not tell you more without actually seeing your PSD file.

**Comment by camoody1** [comment]
@Phantasm4X20 That last post you left appears to be empty?

**Comment by Phantasm4X20** [comment]
Viking - Ladies - Back - Sleeves Ramm 22x240.psb
<https://drive.google.com/file/d/1Y-vwD2iSppV17JlBEVq0AEQAGL1pB9cQ/view?usp=drive_web>

Jason Ramm

**Comment by photopea** [comment]
Please, do not send email to random github addresses. Open github in your web browser and reply there.
