### ISSUE TITLE
Affinity Import Distorts Font

### ISSUE THREAD

**Issue by GDelmy** [photopea/photopea#5110]
Hey!

I'm newer to using Photopea and so far enjoy a lot of the functionality.

However, one of the major reasons I'm using it is to convert the odd file from Affinity to PSD. However, when I import my working files, the text almost always gets distorted and I'm unsure if there's anything that can be done about that. Less important, it drops colour adjustment layers but that I can work around. Is it simply a miscommunication between Photopea and Affinity files?

How it started:
![image](https://user-images.githubusercontent.com/118030876/201450087-472a264f-8dbf-4d3e-a9fb-c869b9265d2a.png)

How it's going:
![image](https://user-images.githubusercontent.com/118030876/201450074-0425a317-29da-43c1-8ccf-c062a4f7e9f8.png)

Thanks!

**Comment by GDelmy** [comment]
Bumping this with another example:
![image](https://user-images.githubusercontent.com/118030876/202817590-143eaa9a-c26b-4c85-b57f-9eab2d270859.png)

**Comment by photopea** [comment]
Hi guys, it should be fixed now! Let me know if it works.
