### ISSUE TITLE
Doesn't Work 'Continue'

### ISSUE THREAD

**Issue by PoweredByAndrox** [photopea/photopea#5112]
Hello, i tried to test code
```js
for (var i = 0; i < 10; i++)
{
	if (i == 2 || i == 4 || i == 6)
	{
		continue;
	}
	alert(i);
}
```

And that 'continue' nothing does at all!
Also my script where has "for in" is not running.

**Comment by PoweredByAndrox** [comment]
"Layers: unknown property  undefined". How do i can to identify where it was called to solve it somehow?
I can put a break point in browser and find some info (vars) in my script but not every time i can do this because i have a low-spec PC that won't work with pp.js (because too large for 2GB memory)

**Comment by photopea** [comment]
I am very sorry, there was a bug in our Javascript interpreter, your code should work fine now.

**Comment by PoweredByAndrox** [comment]
Another bug in 
```js
var SomeVar = undefined;
alert(!SomeVar);
```
