### ISSUE TITLE
Transparent Background Eraser?

### ISSUE THREAD

**Issue by RealSiesgo** [photopea/photopea#5113]
All of a sudden the background eraser became transparent and started deleting like 25% of the pixels only.

How do I fix this?

https://imgur.com/a/UZkMO4X --> here's how it looks

**Comment by MichalSZZ** [comment]
You have set the brush transparency. Probably with the keyboard shortcut - 4.
Try to hit 0 on your keyboard to set it to 100%

**Comment by photopea** [comment]
@MichalSZZ that is amazing, I would have never thought of it :D

It is fixed now, pressing keys will not affect this tool anymore, just reload Photopea.com
