### ISSUE TITLE
Extras automatically turn on when try select, deselect.

### ISSUE THREAD

**Issue by blacksmith01** [photopea/photopea#5115]
I often use the selection mode not to touch the image.
But extras keep automatically turns on.
It bothers me checking the image. 
How can I prevent it?

**Comment by photopea** [comment]
If you disable "Extras", it hides the grid, the guides ... and the current selection.

Would you like to make a selection without seeing it on top of a document (marching ants)?

**Comment by blacksmith01** [comment]
do you mean disable is Uncheck Menu->Filter->Extras ?
of course I already tried.
but it keeps turn on when i click canvas on select mode.

**Comment by photopea** [comment]
There is no Menu - Filter - Extras, are you using www.Photopea.com ?

**Comment by blacksmith01** [comment]
oh, sorry. Menu - View - Extra is correct.

**Comment by photopea** [comment]
As I said, the selection must be visible, and if Extras remained disabled, a selection would not be visible.

**Comment by blacksmith01** [comment]
https://youtu.be/iultvpDNXIU

I uploaded video about this.

**Comment by photopea** [comment]
As I said, that is a correct behaviour.

**Comment by blacksmith01** [comment]
Is there no way to permanently turn off Extras?

**Comment by photopea** [comment]
No.

**Comment by MichalSZZ** [comment]
@photopea  in Photoshop it works a little bit differently:

If you have for example grid and guides enabled in the menu View->Show, and you have some guides or selections, and then you will turn off "extras". It will hide all your selections and guides and grid.

But... if you make a new selection (in add mode or any other boolean than basic) - the selections that were made before will show with the new one (but the guides or grid will not show). The same thing with guides - when you drag a new guide - the guides from the past will show - but not the selections or grids.

There are "tick" and "minus" in that menu. Look at Photoshop how it works there.

**Comment by photopea** [comment]
In Adobe Photoshop, you disable Extras, draw a selection, and Extras stay disabled. Then, you enable Extras, and disable them back, and the selection is hidden.

Do Extras hide selections or not in Photoshop? I think it is very confusing.

**Comment by oh-ko** [comment]
I agree that the automatic appearance of Grid when you use Select is very annoying, I was also looking for how to remove it
