### ISSUE TITLE
[bug] My photo is distorted when I load it 

### ISSUE THREAD

**Issue by jellypuno** [photopea/photopea#5117]
Here's what happened:
1. I downloaded the photo in Google Photos
2. After that I opened it in Photopea
3. The photo ended up like this:
![image](https://user-images.githubusercontent.com/45042840/202302886-c65dc69d-8cbc-4ce9-9564-699daeaf70fd.png)

I was editing other photos earlier and it was okay. For some reason, this one is broken. If I open it in my PC's photo editor, I can view it properly. I tried to re-download and restart my PC and it is still the same.

**Comment by photopea** [comment]
Could you send me your photo to support@photopea.com ?

**Comment by photopea** [comment]
There is a bug in the JPG decoding library that we use. I reported it to the authors: https://github.com/nothings/stb/issues/1409

**Comment by photopea** [comment]
I think I will close it, since your file seems to be damaged. You should report the error to those who created your file.
