### ISSUE TITLE
Ability to remove a single layer style instead of clear all or just turn off.

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#512]
The layer style management of a layer is not very flexible right now
There's no option to create multiple ones of the same type on one layer, like multiple outside strokes.
And when you try add something else they add to the drop down list in the layers panel.
But you can't delete a single one, can just clear all or turn off visibility.

**Comment by photopea** [comment]
So I just updated Photopea. There are two main changes:
1) Anything can be dragged to a Garbage Bin (layers, layer styles, smart filters ...)
2) Some styles have a Plus sign next to them, which allows creating multiple instances of that style (the functionality is similar to Adobe Photoshop).

**Comment by hgs54371** [comment]
1. Drag layers on to the new folder for grouping them would be good as well

2. When I click on the plus signs, nothing happens

**Comment by photopea** [comment]
You have to enable a style first, before cloning it with a Plus sign.

**Comment by hgs54371** [comment]
Yes, I've already have the checkbox checked

**Comment by photopea** [comment]
Then it must be duplicated.

**Comment by hgs54371** [comment]
This is another browser specific thing, On safari it works but on firefox do nothing, both mac version

**Comment by photopea** [comment]
That is awful, that in 2018 we see a different behavior in browsers.

I made it work in both. Thanks!

**Comment by hgs54371** [comment]
Yes, it worked.
And how about also a minus sign for deleting unused ones instead of having to clean up in layers panel after closing the dialog
