### ISSUE TITLE
Vanishing Point stamp tool.

### ISSUE THREAD

**Issue by bluep55** [photopea/photopea#5121]
Brilliant. The introduction of Vanishing Point. Photopea just gets better and better.
One thing I have noticed with the new Vanishing Point feature is the lack of the small image at the target point when using the Stamp Tool.
This is visible when using the Clone Tool in the main window and it is also visible when using the Vanishing Point Stamp Tool in Photoshop.
Main window Image attached just for demonstration. 
It’s not a big deal at all, but just wondered if it was a bug or if it is designed this way. 
Thank you. 

![SnapshotA (1)](https://user-images.githubusercontent.com/118609932/202851486-8417cd32-8e3d-47cb-aed2-df706a7b5359.jpg)

**Comment by photopea** [comment]
Hi, please, discuss it in the original thread: https://github.com/photopea/photopea/issues/2355
