### ISSUE TITLE
PDF order by name wrong

### ISSUE THREAD

**Issue by lin-ycv** [photopea/photopea#5122]
My files on the left, named numerically from 0~53, but the result PDF is in some random order?
![image](https://user-images.githubusercontent.com/60565737/203011291-6e9318b5-3e20-49d1-a5f5-dadb7c109604.png)

**Comment by photopea** [comment]
Could you share your PSD file with us?

**Comment by lin-ycv** [comment]
There is no PSD file, just a bunch of jpg in a folder
I selected batch, PDF presentation, for source I selected all the files in the folder, check order by name.
Am I suppose to open all the jpg in photopea first?

**Comment by photopea** [comment]
Is it about File - Automate - PDF Presentation? I just tried to use it, but it ordered my files alphabetically.

What should I do to see a problem which you describe?

**Comment by hxim** [comment]
@lin-ycv You need to prefix your numbers with zeros because numerical order is different to alphabetical. For expample 10 comes after 2 in numerical order, but 10 comes before 2 in alphabetical order. If you name your files 001.jpg 002.jpg 003.jpg ... it will be sorted correctly.

**Comment by photopea** [comment]
That's correct. Photopea will print all files starting with "1" before files starting with "2".

So "12.jpg" will be before "2.jpg".

**Comment by lin-ycv** [comment]
I don't think that's the issue, it's going 
1
2
**5**
**54**
3
4
6
**0**
**22**
7
**29**
**51**
....etc
![image](https://user-images.githubusercontent.com/60565737/203249510-8d7b35b0-54a8-447b-868f-598d1b6c77bf.png)

I've attached the files i'm encounting this issue with (first 40 photos)
[2022-11-21_155627.zip](https://github.com/photopea/photopea/files/10064852/2022-11-21_155627.zip)

**Comment by hxim** [comment]
> I don't think that's the issue, it's going

@lin-ycv Hi, I just tried and it will be sorted alphabetically after you click Expert as PDF if you clicked "Order images by name" chekcbox. What you see in "PDF Presentation" dialog window is how it is before it is ordered by name that is why you see 01.jpg, 02.jpg, 05.jpg, 03.jpg, 04.jpg, 00.jpg. But after you actually export to PDF it will be in correct order inside exported PDF file.

**Comment by lin-ycv** [comment]
you're right, my bad, didn't actually export, assumed the displayed order is the export order.

**Comment by photopea** [comment]
I think the display order is an order in which you selected files

**Comment by lin-ycv** [comment]
The display order seems to be arbitrary
Selected: 00, 02, 04, 03, 01
Open dialog shows: 01, 02, 03, 04, 00
Displays: 01, 02, 03, 00, 04
![copy](https://user-images.githubusercontent.com/60565737/203458879-cfa9f994-dbb9-4943-9b43-3d368a2f7afa.gif)

I don't think it's a big deal as long as the export is correct, but might be a bit confusing for first time users who are used to ps.
The export order is the same as displayed order in ps, and we can drag the order around.

Maybe a note or a tooltip can be added to avoid future confusions?

**Comment by photopea** [comment]
The files will be listed in an alphabetical order now. But unless you tick "order images by name", they will be in your PDF in a random order.
