### ISSUE TITLE
picture size won't change to pixels (NaN)

### ISSUE THREAD

**Issue by ftisxties** [photopea/photopea#5123]
Hey, i don't know if it's the right place to ask but i tried changing the size of my picture but when i enter my number, it goes 'NaN' and i usually work with pixels not inches, and it won't let me change into pixels.
Am I doing something wrong?

Thank you.

**Comment by photopea** [comment]
Could oyu open www.Photopea.com and do it again? If you can, could you tell me how you did it? Where did you enter what?

**Comment by Leenassoni** [comment]
your application very bad

**Comment by Leenassoni** [comment]
pixcel change

**Comment by photopea** [comment]
I have to close it because of lack of details.
