### ISSUE TITLE
Mouse Cursor below actual position

### ISSUE THREAD

**Issue by AlexReed51** [photopea/photopea#5124]
The mouse cursor is below the actual position of the tools selected (happens with all tools). I'm not great at code speak so let me recreate this for you on the video below.
Macbook Air M1 (2020)
macOS Monterey
Version 12.5.1

Google Chrome (Up to date)
Version 107.0.5304.110 (Official Build) (arm64)
Using the downloaded browser client

https://user-images.githubusercontent.com/118816380/203304637-e4f0794d-6048-469f-8592-0efadd510dea.mov

**Comment by AlexReed51** [comment]
Happens on the browser (photopea.com) version too. Video below.
https://user-images.githubusercontent.com/118816380/203305166-a5f65590-266a-44bd-b6b4-04d4772eccf5.mov

**Comment by photopea** [comment]
Look into Edit - Preferences - Cursor Offset.

It was done for touchscreen users, so that they can see what they are painting under their finger.

**Comment by AlexReed51** [comment]
That worked! Thank you! Might be worth setting the default value to 0. I haven't touched that so not sure how it happened for me.
You can close this issue.

**Comment by photopea** [comment]
It is at 0 by default. You must have had changed it.
