### ISSUE TITLE
Exported PDf cannot be opened on AI

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5125]
This is a difficult  bug to repro. Specially because i don't have AI myself.

But the issue is that i work with another company that opens my exported PDFs in AI, but in the last couple of weeks i have had issues with 2 PDFs in particular. And i don't know what's the issue. 

I can give you the PSDs:

https://www.photopea.com/#iYsTsZREr.psd 
https://www.photopea.com/#iebTvjjxW.psd

And you can export it to PDF and only vectorize the fonts. Don't rasteriza anything
![image](https://user-images.githubusercontent.com/11801254/203384824-fae29b30-ed42-416d-aeb9-46fc22847d63.png)

This is the issue they get:

![Screenshot_20221122-144716](https://user-images.githubusercontent.com/11801254/203385502-5ca20d4a-c942-4486-997f-ec080d623a83.png)

![Screenshot_20221122-144726](https://user-images.githubusercontent.com/11801254/203385509-c1b50d43-b172-4c3e-ab36-bff5c2f9c359.png)

On both it reads: Acrobat reader have encountered a problem with the format of the file. Too few operands

**Comment by photopea** [comment]
I am very sorry, it should be fixed now.

The problem was that you used the "Dissolve" blend mode. There is no such mode in PDF, so the PDF file contained literally "Undefined blendmode", which your software could not handle.

Now, Photopea will export objects with "Dissolve" as a "Normal" blend mode.

**Comment by TheRadicalDreamer** [comment]
Thanks!

Just to check.

Where i have used Dissolve blend mode?

And what does "Pass Through" blend mode do? Seems the same as "Normal"

**Comment by photopea** [comment]
It is on the Skull - "Carlota"
