### ISSUE TITLE
Getting error message 'Billing Hard Limit has been reached' when using Stable Diffusion

### ISSUE THREAD

**Issue by gse123** [photopea/photopea#5128]
Hi there,

I get this error whenever I try and use the Stable Diffusion function in Photopea.  Worth noting that it only does this when i'm logged in with my premium subscription account... if I log out and use the free version anonymously, it works fine (although I get the 100 sec per image timer).

Any ideas? 

Thank you

**Comment by photopea** [comment]
Are you sure? It should not work when you log out, too. Could you please check?

**Comment by gse123** [comment]
logged out and back in multiple times, and restarted my computer etc. When logged in I get the hard billing error. When logged out it works fine (albeit with the timed restriction to 1 image per minute or so)

**Comment by photopea** [comment]
That is really weird. It should not work when you log out. I just tried to use it while logged out, and I see the Billing hard limit, too.

Are you using our API Key or you entered your own?

**Comment by gse123** [comment]
the Photopea key. But actually, it is not working when I log out either. (it was yesterday or the day before when I last tried).

Any ideas when it will be operational again? Really interesting feature!

**Comment by photopea** [comment]
The thing is, that I have to pay 2 cents per each image that someone generates.

Our users generated 15,000 images, and I paid $300 for it so far. I think I dont want to give away more money than $300 a month. So it will reset on the 1st of December.

Did you try to insert your own API key? It is very simple, see https://www.photopea.com/tuts/use-stable-diffusion-for-free/

**Comment by photopea** [comment]
It should work again.
