### ISSUE TITLE
Failes to save after use of Ellipse tool

### ISSUE THREAD

**Issue by KaspRosen** [photopea/photopea#5131]
This has happened to me the last few days. I've testet it; opened a document, made a circle and tried to save - nothing happens when I click Save As PSD. Kinda weird :-)

The same thing happens if I try it with Rectangle, Line, Parametric shape and Custom shape.

**Comment by photopea** [comment]
Can you save an empty document as a PSD, without drawing anything? Can you save a PSD at all?

**Comment by photopea** [comment]
Try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by KaspRosen** [comment]
I can. I'm also able to save files consisting of text, images and so on - but not with shapes. 

I have tried both Firefox, Chrome and Safari (working on a mac).

**Comment by photopea** [comment]
Did you try to use Photoepa with no browser extensions?

**Comment by photopea** [comment]
I have to close it because of lack of details.
