### ISSUE TITLE
could move mask but not copying. but i understood how to

### ISSUE THREAD

**Issue by PenguinIsrael** [photopea/photopea#5132]
first create a new mask. then copy mask onto it. it will duplicate. at least for me. i expected it to copy even without it. but it only created a new layer of the black and white mask

**Comment by photopea** [comment]
What exactly do you mean? I dont understand. Could you be more precise? What is "copy mask"?

**Comment by PenguinIsrael** [comment]
instructions:
1. have a layer with a mask

2. select mask

3. edit > copy

4. paste on desired layer

expected result:
- desired layer now has a duplicate of the same mask

result:
- new layer made of the mask (the masked is copied as a new layer and not on a layer. cant drag it onto it either)

**Comment by photopea** [comment]
Did you make a selection in between? Or what is "Select Mask"? You also had to click the mask thumbnail in the layers panel.

**Comment by PenguinIsrael** [comment]
i mean i clicked it in the side layers tab.

it doesnt have to be an issue. i just couldn't duplicate masks until i figured that i need to create a new mask before i copy the original onto it.

i wanted to leave this "issue" so anyone wondering why they dont manage to do that will find a way to do it.

**Comment by photopea** [comment]
you can hold Alt and click-and-drag the mask to a new layer. Any way of copying a mask which works in other programs, should work in Photopea.
