### ISSUE TITLE
How do I replace smart objects through scripts, now that is selecting local files but I want to customize files

### ISSUE THREAD

**Issue by zhengjianxiao** [photopea/photopea#5134]
var desc = new ActionDescriptor();
var idnull = charIDToTypeID( "null" );
desc.putPath( idnull, new File('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKr0Kj1XrEzBJQk-6RuK8pTrltgS3w3MXDNQ&usqp=CAU') );
executeAction( stringIDToTypeID( "placedLayerReplaceContents" ), desc, DialogModes.NO );

**Comment by photopea** [comment]
Try this: https://www.photopea.com/tuts/edit-smart-objects-with-a-script/

**Comment by zhengjianxiao** [comment]
I know this, but it is to edit the smart object, what I want is replaced with placedLayerReplaceContents smart object images, there are now, but I, would you let me choose a local file, then replace, I want to pass through script pictures directly, rather than select files

**Comment by zhengjianxiao** [comment]
Just like ActionDescriptor.putPath has no effect

**Comment by photopea** [comment]
Try app.open() - https://www.photopea.com/learn/scripts

Then, call your script. Photopea can not do waiting while processing the script, so you need to wait until you call the second part of the script.
