### ISSUE TITLE
impossible de séléctionner le contour d'un objet

### ISSUE THREAD

**Issue by Ora84** [photopea/photopea#5135]
Bonjour,

je commence à travailler avec votre logiciel mais je n'ai pas le raccourci pour séléctionner le contour d'un objet. Comment régler ce problème.
Voir photo.

Mercid de votre réponse.

Best regards
Ora
![can't find the selection option](https://user-images.githubusercontent.com/119136019/204109198-6978dbb4-b99a-4ae6-89c5-09da7826f7ba.png)

**Comment by photopea** [comment]
There are more tools hidden under each button: https://www.photopea.com/learn/workspace
