### ISSUE TITLE
New errors in PSD files after open and saved in photopea

### ISSUE THREAD

**Issue by krkaushalsingh** [photopea/photopea#5137]
My PSD files was edited in photopea and loaded using aspose psd library.
Old files are loaded and processed successfully.
However, same file when opened and just saved in photopea shows load failed error when loaded using aspose psd library- s

Inner exception error message as genearted in aspose PSD library on (PsdImage)Image.Load(Server.MapPath(pdfFile))) : 
"Assigned  items miss the expected keys: warp"
Aspose library were not modified.

Any new change in PSD file save?

**Comment by krkaushalsingh** [comment]
![Hex Diff on Save](https://user-images.githubusercontent.com/119317274/204291473-c3bb4219-1de9-4311-b4b5-7bcb04a529bc.png)

Here is snapshot of the files comparison in hex format. Left is file just saved using photopea.
Issue is related to missing wrap in PSD file upon save.
Wrap related changes are visible in comparison.

Pls suggest solution. urgent.

**Comment by photopea** [comment]
I am very sorry, it should be fixed now. The PSD files, which Photopea produces now, should be accepted by your library.

You can re-convert your old PSD files by the current Photopea.

**Comment by krkaushalsingh** [comment]
It's resolved now.
Thanks for your prompt support and solution.
Cheers and wishes for you 👍
