### ISSUE TITLE
Bug during text box creation

### ISSUE THREAD

**Issue by LLpm55** [photopea/photopea#5138]
Approximately 24h ago, everything was just fine.

Today, somehow, I can't create text boxes anymore.
In the 3 steps (placing 1st corner with a click, dragging the mouse to the desired position for 2nd corner, placing 2nd corner with a click), it fails at the last one.
No matter how much I click, placing the 2nd corner doesn't work.

(also, somehow the text box now appears blue rather than the usual black when I drag my mouse to attempt to place the second corner)

The bug is present at least in Firefox 107.0 (64-bit) and Pale Moon 31.4.0 (64-bit).
And, again, yesterday it worked just fine. So if ever you deployed something approximately within the last 24h, then it could be the cause.

**Comment by alxmedic** [comment]
Same issue here with Chrome, Edge, and the Windows App.

**Comment by TheCW-H** [comment]
Issue isn't just creation. Editing existing text boxes is also an issue. You can select the box, causing the text to change in size on click.  If the text is not locked it has a possibly of sticking to your cursor until you change tools.

**Comment by photopea** [comment]
guys, I am very sorry, it should be fixed now.

**Comment by robinbijlani** [comment]
Just came here to echo the reports and saw it get fixed before my eyes. Thanks!

**Comment by krkaushalsingh** [comment]
Hi Just came across the issue mentioned by [TheCW-H] "Issue isn't just creation. Editing existing text boxes is also an issue. You can select the box, causing the text to change in size on click. If the text is not locked it has a possibly of sticking to your cursor until you change tools."

Textbox - multiline  sticks to the cursor and released only when clicked on layer name.
When textbox text is dragged, its box remains fixed where as text moves . Pls refer snapshot.
![photopea box issue](https://user-images.githubusercontent.com/119317274/204407815-2c0a0377-6651-4b0d-b2ab-13458de796e9.png)

**Comment by photopea** [comment]
Please, clear your cache (or wait an hour and reload Photopea, or use Photopea in the Incognito mode).
