### ISSUE TITLE
Define a certain pixel count or aspect ratio for rec selection, like 1280x720 or 16:9

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#514]
When extracting something out of a larger image(other than cropping), it's important to rec select either by a certain pixel count or aspect ratio, which is not found in the rec select tool right now.

**Comment by photopea** [comment]
It was suggested many times. But this can be done through Image - Canvas size.

**Comment by hgs54371** [comment]
But I want to keep the canvas size, as it is the "canvas", the extracted parts are going to be used as elements in the canvas. I want to keep the extracting work within the same doc, without opening other docs for each extracting parts of different dimensions
