### ISSUE TITLE
Page freezing

### ISSUE THREAD

**Issue by EAPrintables** [photopea/photopea#5140]
When I attempt to use the move tool, the page freezes and I'm no longer able to carry on editing my work. I can still click on the other editing tools but none of them work or make any changes on the canvas.

**Comment by atgfk** [comment]
I also experience this

**Comment by photopea** [comment]
What should I do after opening www.Photopea.com to see it happen myself?

**Comment by Hamjab** [comment]
> What should I do after opening [www.Photopea.com](http://www.Photopea.com) to see it happen myself?

It happens randomly, it's also happening to me now. I have to refresh the page and open a new project each time.

**Comment by SkeemoJ** [comment]
> 

just start working on something it just freezes

**Comment by SkeemoJ** [comment]
> 

just start working on something and it'll freeze

**Comment by photopea** [comment]
I am very sorry, it should be fixed now. Clear your cache or wait an hour.

**Comment by SkeemoJ** [comment]
> I am very sorry, it should be fixed now. Clear your cache or wait an hour.

how do you clear cache lol

**Comment by EAPrintables** [comment]
> I am very sorry, it should be fixed now. Clear your cache or wait an hour.

Thank you. It seems to be working normally again.
