### ISSUE TITLE
Undo (Ctrl+Z) when refining edge in Object Selection creates anomalies

### ISSUE THREAD

**Issue by sh0nuff** [photopea/photopea#5141]
Reproduce: 
Choose Object Select,
Drag square around item
Choose Refine Edge
Expand foreground
Type Ctrl-Z

See example of what this does [here](https://imgur.com/a/hPNs6Eg)

**Comment by photopea** [comment]
I am very sorry, it should be fixed now. Clear your cache or wait an hour.

**Comment by sh0nuff** [comment]
Wow! Such a quick turnaround! No apologies necessary, I'll be renewing my subscription - thanks!!
