### ISSUE TITLE
Stuck in zoom when first opening a file

### ISSUE THREAD

**Issue by GamingNascar** [photopea/photopea#5142]
I find that whenever I open a file to edit, the page is zoomed in so you can't see the window on the right. Occasionally when I use keyboard shortcuts it will switch and zoom in on the right window so I can't see the toolbox. Usually I have to reload which makes it pretty annoying to have to dig through my files again.

**Comment by photopea** [comment]
Could you show us a screenshot of what you mean?

**Comment by photopea** [comment]
I have to close it because of lack of details.
