### ISSUE TITLE
Blending options on folders not showing on children during SVG export

### ISSUE THREAD

**Issue by duckboy81** [photopea/photopea#5143]
Hello there!

It looks like when you export an `SVG`, layers with a blending effect applied via a folder do not have their effect applied.

Steps to reproduce:

1. Create a folder
2. Create a layer with some text in this new folder
3. Create a blending effect for this layer (I chose `Color Overlay`)
4. Export to `SVG`
5. Resulting SVG shows original layer color

Thanks for this amazing tool!

EDIT: Effects applied directly to the layer work correctly.

**Comment by photopea** [comment]
it should work now :)
