### ISSUE TITLE
Pausing/Unable to click the buttons

### ISSUE THREAD

**Issue by RizsimStudiosOfficial** [photopea/photopea#5144]
<img width="1248" alt="is this a bug" src="https://user-images.githubusercontent.com/61947503/205132514-6234e467-3e08-4f0b-92ac-a92b208d1cf7.png">

**Comment by photopea** [comment]
That is not how Photopea should look like. How old is your web browser? Could you update it?

**Comment by RizsimStudiosOfficial** [comment]
idk i have the latest google chrome browser so i have no idea

**Comment by RizsimStudiosOfficial** [comment]
like at random points it will look like this every time i open it up

**Comment by RizsimStudiosOfficial** [comment]
https://user-images.githubusercontent.com/61947503/205235438-616e93b6-fea8-4dba-b194-cf5b9c531627.mp4

**Comment by RizsimStudiosOfficial** [comment]
> That is not how Photopea should look like. How old is your web browser? Could you update it?

idk i have the latest google chrome browser so i have no idea like so like at random points it will look like this every time i open it up

**Comment by photopea** [comment]
Try this maybe: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

Your browser extension could be modifying Photopea.

**Comment by photopea** [comment]
I think it is caused by your browser extensions. Let me know if you have problems with Photopea while using it with no browser extensions.

**Comment by RizsimStudiosOfficial** [comment]
yeah i did fix it because malwarebytes had a an allow list so i put the website there and it fixed it

**Comment by RizsimStudiosOfficial** [comment]
> I think it is caused by your browser extensions. Let me know if you have problems with Photopea while using it with no browser extensions.

yeah i did fix it because malwarebytes had a an allow list so i put the website there and it fixed it
