### ISSUE TITLE
[Feature Request] Pressing return to close/apply sliders

### ISSUE THREAD

**Issue by chaserau** [photopea/photopea#5145]
Absolutely in love with Photopea (both as a feat of coding and also as a user).

One thing that I keep tripping up on is that in Photoshop, you can use the return key to apply/hide an input slider (eg in layer opacity or paintbrush 'flow'). I believe this is because in Photoshop it keeps the text input focused while you are using the slider, and the slider hides when input focus is lost (eg. you press the return key).

This can be used a power user trick, as on a full keyboard you can use your mouse thumb to tap return after adjusting a slider, and also because the text input is always focused, you can quickly type in values after using the slider (there seems to be a bit of logic around clearing the text when you start typing in Photoshop though which I won't attempt to deconstruct here).

Just a small quibble really, and isn't a breaking issue, but it does really speed up your workflow if you're editing every day. Once again amazing software though, and keep up the great work!

**Comment by photopea** [comment]
When you have such "floating element", you can hide it by clicking somewhere else, or pressing Escape (in Photoshop and Photopea).

You can hide it with the Enter key now, too.

**Comment by chaserau** [comment]
Wow, fast fixes! Thanks so much. :)
