### ISSUE TITLE
Photopea freezing and not saving correctly

### ISSUE THREAD

**Issue by teachersantos** [photopea/photopea#5146]
Hello Photopea team!
I am a Highschool teacher in California, USA who uses Photopea with my students. They love it!

Yesterday 11/30/2022 from 9:00am to 1:05pm many of our students had issues with
*Freezing
*Buttons not working
*Files not saving
*Program crashing

I was wondering if perhaps there was a server issue on your side?

Or is it that too many of my students are using your program and causing a server issue on our end?

Thank you so much!!!!

**Comment by photopea** [comment]
Hi, there was a bug in Photopea, which lasted for about two hours. I am very sorry, it should be fixed now.

But maybe the reason was something else in your case. Could you please tell me what you do to make Photopea freeze? Or record a video of it?

**Comment by photopea** [comment]
I have to close it because of lack of details.
