### ISSUE TITLE
Could not import pdf files?

### ISSUE THREAD

**Issue by zhideys** [photopea/photopea#5147]
As the title, whenever I open or drag a pdf file into photopea, no matter what browser is (chrome, firefox), the tabs will always freeze and stop working. I don't know the cause, but this is the computer configuration I'm using: 
Device name	DESKTOP-NRL74M3
Processor	AMD Ryzen 5 5600H with Radeon Graphics            3.30 GHz
Installed RAM	8.00 GB (7.38 GB usable)
Device ID	FD719461-B366-4A0C-B53D-6A5BE0717AD7
Product ID	00356-24518-69952-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Pen support
I really need photopea to convert some pdf files into psd, hope you guys could help. Thank you so much!

**Comment by photopea** [comment]
I just tried to open about 50 different PDF files in Photopea and they all worked.

How large is your PDF? Photopea needs to rasterize every document at 144 DPI. So if your document is 200 x 200 inches, that is 829 million pixels and 8 GB of RAM might not be enough.

Or if the document is 100x smaller, but there are hundreds of layers, you get the same thing. Not all PSDs can be converted into reasonable editable PSD files.

**Comment by zhideys** [comment]
> I just tried to open about 50 different PDF files in Photopea and they all worked.
> 
> How large is your PDF? Photopea needs to rasterize every document at 144 DPI. So if your document is 200 x 200 inches, that is 829 million pixels and 8 GB of RAM might not be enough.
> 
> Or if the document is 100x smaller, but there are hundreds of layers, you get the same thing. Not all PDFs can be converted into reasonable editable PSD files.
Thank you for reply. So it was my file, it's 59,9kb and contained several pages, I'll extract it then.

**Comment by photopea** [comment]
It would help a lot if you shared your PDF file with us.

**Comment by photopea** [comment]
I have to close it because of lack of details.
