### ISSUE TITLE
Photopea keeps crashing

### ISSUE THREAD

**Issue by diannegleich** [photopea/photopea#5148]
I get almost 99% thru a picture, but before I can save it - Photopea crashes and locks up so I am unable to save or do anything. This has happened 3 times in a row now ???? Then I see something about it not being able to run in chrome after December 2022??!! WHY?

**Comment by photopea** [comment]
Hi, where do you see such thing about not being able to run in Chrome?

**Comment by diannegleich** [comment]
well. it came up in chrome on a search for why photopea was crashing...
trying to find it again...

Thanks!

Dianne Gleich
***Always copy in ***@***.***
***@***.***> in case i am out of office***
Transportation Administrative Assistant
General Express a Division of ARL Transport
Contact # 815-714-2845 Ext. 219
Contact us here directly or visit: www.genxchi.com

*Where Passion + Purpose Delivers Excellence!*


*Drayage-Storage-Secured Parking*
*Transloading/Reworks-Onsite Scale*
*Chassis Stacking-Maintenance (tractor, container, chassis)*
*Refrigeration Monitoring/Fueling - **Let us know where we can help!*


CONFIDENTIALITY NOTICE: The contents of this email message and any
attachments are intended solely for the addressee(s) and may contain
confidential and/or privileged information and may be legally protected
from disclosure. If you are not the intended recipient of this message or
their agent, or if this message has been addressed to you in error, please
immediately alert the sender by reply email and then delete this message
and any attachments. If you are not the intended recipient, you are hereby
notified that any use, dissemination, copying, or storage of this message
or its attachments is strictly prohibited.

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
12/02/22,
11:00:20 AM

**Comment by photopea** [comment]
Could you tell me how can I make Photopea crash? Or record a vido of how you make Photopea crash? So that we have a proof and see what is happening.

**Comment by diannegleich** [comment]
I am just working there, creating additional layers.... erasing
backgrounds,  and then all of a sudden it moves everything from the right
over to the left and locks up....
Below is how it looks when it crashes

[image: image.png]

Thanks!

Dianne Gleich
***Always copy in ***@***.***
***@***.***> in case i am out of office***
Transportation Administrative Assistant
General Express a Division of ARL Transport
Contact # 815-714-2845 Ext. 219
Contact us here directly or visit: www.genxchi.com

*Where Passion + Purpose Delivers Excellence!*


*Drayage-Storage-Secured Parking*
*Transloading/Reworks-Onsite Scale*
*Chassis Stacking-Maintenance (tractor, container, chassis)*
*Refrigeration Monitoring/Fueling - **Let us know where we can help!*


CONFIDENTIALITY NOTICE: The contents of this email message and any
attachments are intended solely for the addressee(s) and may contain
confidential and/or privileged information and may be legally protected
from disclosure. If you are not the intended recipient of this message or
their agent, or if this message has been addressed to you in error, please
immediately alert the sender by reply email and then delete this message
and any attachments. If you are not the intended recipient, you are hereby
notified that any use, dissemination, copying, or storage of this message
or its attachments is strictly prohibited.

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
12/02/22,
11:12:25 AM

**Comment by photopea** [comment]
To what address exactly did you send your last email? I do not see any images. Our email address is support@photopea.com

**Comment by diannegleich** [comment]
i replied to the email you sent....   photopea/photopea <
***@***.***>

here is the pic again

I am just working there, creating additional layers.... erasing
backgrounds,  and then all of a sudden it moves everything from the right
over to the left and locks up....
Below is how it looks when it crashes
[image: image.png]

Thanks!

Dianne Gleich
***Always copy in ***@***.***
***@***.***> in case i am out of office***
Transportation Administrative Assistant
General Express a Division of ARL Transport
Contact # 815-714-2845 Ext. 219
Contact us here directly or visit: www.genxchi.com

*Where Passion + Purpose Delivers Excellence!*


*Drayage-Storage-Secured Parking*
*Transloading/Reworks-Onsite Scale*
*Chassis Stacking-Maintenance (tractor, container, chassis)*
*Refrigeration Monitoring/Fueling - **Let us know where we can help!*


CONFIDENTIALITY NOTICE: The contents of this email message and any
attachments are intended solely for the addressee(s) and may contain
confidential and/or privileged information and may be legally protected
from disclosure. If you are not the intended recipient of this message or
their agent, or if this message has been addressed to you in error, please
immediately alert the sender by reply email and then delete this message
and any attachments. If you are not the intended recipient, you are hereby
notified that any use, dissemination, copying, or storage of this message
or its attachments is strictly prohibited.

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
12/05/22,
07:09:00 AM

**Comment by photopea** [comment]
Sorry, write us an email to support@photopea.com if you want to tell us something. Your messages are filled with mess.
