### ISSUE TITLE
???

### ISSUE THREAD

**Issue by jdmhomeboi** [photopea/photopea#5149]
Ok so I'm an American Football uniform designer and I'm trying to create a design on the left collar, but for some reason, despite being visible when I click on that specific layer, on the uniform, it disappears. What is happening?

**Comment by jdmhomeboi** [comment]
![Screenshot (16)](https://user-images.githubusercontent.com/119703005/205378176-217eda24-eefc-40b8-80c3-dd874e6cb6b9.png)
![Screenshot (17)](https://user-images.githubusercontent.com/119703005/205378202-a391a056-e814-4617-b531-384980e24a26.png)

**Comment by photopea** [comment]
I think that is how it is supposed to work.

You can learn how to use Photopea at www.Photopea.com , or you can buy a book about Adobe Photoshop.

**Comment by jdmhomeboi** [comment]
No because that's not how it worked before. The layer would be visible in the section where it said "left collar" but it would disappear on the actual uniform the second I even save the smart object. What do I do?

**Comment by jdmhomeboi** [comment]
Is this a bug? Or is this just the settings that I may accidently have applied

**Comment by photopea** [comment]
I am afraid I do not understand. Could you share your PSD with us, and a PNG of how it should look like after opening in Photopea?

**Comment by jdmhomeboi** [comment]
I already have and I was supposed to get a URL link but for some reason, it's not allowing me to

**Comment by jdmhomeboi** [comment]
https://user-images.githubusercontent.com/119703005/205464329-9947e581-1809-4282-9f1a-746ae68abc97.mp4

This video should explain what I'm trying to say.

**Comment by photopea** [comment]
Please, send me your PSD file to support@photopea.com . You can delete all layers except the one with a blue stripe.

**Comment by jdmhomeboi** [comment]
I already have and I was supposed to get a URL link but for some reason, it's not giving it to me, so I can't share it.

And I already tried that. It didn't work

**Comment by photopea** [comment]
I did not receive any email from you. Can you send your file as an attachment of an email?

**Comment by jdmhomeboi** [comment]
Yes I can. I just did

**Comment by jdmhomeboi** [comment]
Football.psd
<https://drive.google.com/file/d/1yB4fUkOoniSaDMTgdMvlOIK9eduJp-jG/view?usp=drive_web>

**Comment by photopea** [comment]
I think you did not send your email to support@photopea.com. Please, chech the email address to which you are sending your emails. What address is it? Do you know how to check the recipient address in your email client?

**Comment by jdmhomeboi** [comment]
***@***.***

I sent the template. That’s my email

**Comment by photopea** [comment]
There really was a bug in Photopea. It should be fixed now. Thanks for helping us track it down!

**Comment by jdmhomeboi** [comment]
Thank u so much. I’ll lyk if it was fixed
