### ISSUE TITLE
"Close current window" even though a window isn't open.

### ISSUE THREAD

**Issue by vickilollsad** [photopea/photopea#5150]
So, I was making a little text icon and I went to blending options. Once I closed blending options I needed to go there again. I switched tabs in google chrome and tried to close the blending options window but it wasn't there. I tried to restart and delete something but it wasn't working at all. Please help me.

Thanks,

**Comment by photopea** [comment]
Could you tell me what should I do after opening www.Photopea.com to see such problem happen myself?

**Comment by photopea** [comment]
I have to close it because of lack of details.
