### ISSUE TITLE
My Photopea Is Not Saving Images AND Being On Zero Bytes

### ISSUE THREAD

**Issue by CalebPlayzRoblox** [photopea/photopea#5153]
I Try Saving A Image, No, How Many Bytes? ZERO

**Comment by DuckyMacfly** [comment]
Yeah, same problem here.

**Comment by photopea** [comment]
Does it still happen now?

**Comment by CalebPlayzRoblox** [comment]
@photopea yes

**Comment by photopea** [comment]
Try this https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details. The person did not provide any instructions on how to reproduce the issue.
