### ISSUE TITLE
File Corrupted when saving

### ISSUE THREAD

**Issue by gov123** [photopea/photopea#5155]
I was using Photopea for a while, it was working fine. But since two days which ever file I modify and save is becoming corrupted. The file becomes 0b.

**Comment by photopea** [comment]
Could you reload Photopea.com ? Does it still happen?

**Comment by gov123** [comment]
Yes. I have been trying different ways so far. Tried reloading. Tried in incognito. Tried restarting the system.

**Comment by photopea** [comment]
ok.
