### ISSUE TITLE
some keyboard shortcuts with the ctrl key aren't working 

### ISSUE THREAD

**Issue by Gameplayerr** [photopea/photopea#5156]
When i try to copy (ctrl+C), select all (ctrl+A) or move the selection (ctrl+ arrow keys), inputs that is essential in the photopea aren't working, at least for me in my computer. And i want to know if is a problem just with my PC or if is a issue with the website. If someone can help with this just answer me.

**Comment by photopea** [comment]
It works for me :( could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by Gameplayerr** [comment]
I found nothing relacted with my problem...

**Comment by photopea** [comment]
Did you try Photopea in the Incognito mode? What operating system and a web browser are you using?

**Comment by Gameplayerr** [comment]
No, and i use Brave in the Windows

**Comment by photopea** [comment]
Maybe try a different browser. Brave has many default settings which break many websites. Nobody else has reported such a problem recently.

**Comment by Gameplayerr** [comment]
Ah, the problem is: Chrome is very slow and Edge keeps changing my account to my brother's account, who owns the computer. But i can use the Opera GX, another browser that is in my computer

**Comment by photopea** [comment]
I dont see any reason why should Photopea run slower in Chrome than in Brave. Anyway, I think it is a bug in your browser, not in Photopea.
