### ISSUE TITLE
PDF clipping mask fails to work when mask is partially off canvas

### ISSUE THREAD

**Issue by DrewS138** [photopea/photopea#5158]
found bug:

If clip mask from PDF is outside canvas it default as rectangle not as semi cricle or whicvher shape it has normally: see file on attached to check it open PDF > Photopea. 
![pdfclipmask](https://user-images.githubusercontent.com/74819605/205868188-25e21428-26e4-487b-9a56-61e55578eb4d.jpg)
[ClipMask-Working (1).pdf](https://github.com/photopea/photopea/files/10164521/ClipMask-Working.1.pdf)
[ClipMask-NOTWorking (1).pdf](https://github.com/photopea/photopea/files/10164522/ClipMask-NOTWorking.1.pdf)

**Comment by photopea** [comment]
In our current model of PDF processing, any object can be clipped by at most one path.

When we see that something must be clipped by two or more intersecting paths, we need to choose only one of these paths.

I changed it, so now, it chooses the most complex of all clipping paths (a circle is more complex than a rectangle). It works well for your PDFs.
