### ISSUE TITLE
Can't drag corners of an adjacent plane when using Vanishing Point filter

### ISSUE THREAD

**Issue by BikoInnit** [photopea/photopea#5159]
When I try to drag the corners of an adjacent plane to place text on a 3D object it does nothing.
All the tutorials I see just drag the corners of the adjacent planes and position them in a way that the text looks believable, but Photopea for some reason doesn't let me do that. I'm not sure whether this is a bug or maybe just me not knowing how to use the tool, I can't seem to find anything beyond instructions that just do not work.

**Comment by photopea** [comment]
Could you maybe show a screenshot of what you mean? Or share a video and tell us what second of it is relevant?

**Comment by BikoInnit** [comment]
Sure! Here it is

https://user-images.githubusercontent.com/90649639/206249047-6e8f577f-3692-4f6a-ad66-57b565d06290.mp4

**Comment by photopea** [comment]
So I will close it, as I said, you can not deduce any meaningful 3D properties from such a made-up image.
