### ISSUE TITLE
Option-click an eyeball in layers panel to solo that layer

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#516]
This solo layer function is very useful, just like in photoshop

**Comment by photopea** [comment]
Done, thanks!

**Comment by hgs54371** [comment]
But now opt-click it again doesn't toggle them back to the original visibility of many other layers, it simply turns them all on, which is a big mess up

**Comment by photopea** [comment]
I think this mechanism is quite complex. Do people really use it that often?

**Comment by hgs54371** [comment]
It's good to have when you want to quick a/b compare how something look like by itself versus it in context with other elements (but not all) for inspiration reasons, photoshop has this, I found myself using quite often

**Comment by photopea** [comment]
Now it should work more like Photoshop.
