### ISSUE TITLE
Vanishing Point error

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#5160]
1) I selected Vanishing Point feature
2) I selected Brush in left toolbar and tried to use it on image
3) I tried to select Create Plane tool but it is not working and showing error - see screenshot
![image](https://user-images.githubusercontent.com/6370548/206122925-9d164bb8-1e74-4561-b3c8-e93b4469f59c.png)

**Comment by photopea** [comment]
fixed! thanks for reporting :)
