### ISSUE TITLE
PSD View colors blurred and brightened background images missing.

### ISSUE THREAD

**Issue by huna7a** [photopea/photopea#5161]
Cant see some colors when viewing psd files and some colors are blurred/brightened and background images are missing. Dont know what caused this, tried to close reopen the same window and tried to redownload the same psd, replaced the old psd with the freshy one, nothing seem to work. This issue occured two days ago, dont know what caused this change but its very nasty one.

**Comment by photopea** [comment]
Could you tell us some steps what should we do to see such problem? Maybe share your PSD file with us and a screenshot of how is it displayed in Photopea.com ?

**Comment by huna7a** [comment]
heres the picture and the psd file, I tried to open it with other site, no
issues, but I cant edit it from there, I can only preview it. I dont wanna
install Adobe Photoshop just for that.
 Take.psd
<https://drive.google.com/file/d/19ijGW6H77ca2_UGfVqI8O_uU9oh4NMz_/view?usp=drive_web>
[image: proof.jpg]

**Comment by photopea** [comment]
I am very sorry, there really was a bug in Photopea, it is fixed now.

**Comment by huna7a** [comment]
I installed Adobe Photoshop anyway, because I needed a working solution for my study. Thanks for the fix.
