### ISSUE TITLE
Photopea opens PSD files from .ZIP files with their layers being invisible

### ISSUE THREAD

**Issue by Yasmiiiin** [photopea/photopea#5162]
when i open a .zip file in photopea, all layers are invisible no matter if i manually wanted them visible or not. vectors from zip files are on the same place if opened.
edit: only PSD files from a ZIP file seems to be affected by this issue, even if photopea can open flat images or vector graphics as PSDs, and PSDs affected by this still shows the original layers from it when they were manually set to be visible or not.

**Comment by photopea** [comment]
Photopea tries to open every file in a ZIP separately. So it should work the same as if you unzipped it in your computer and opened all files in Photopea at once.

It would help us if you shared your ZIP so that we can see what is happening.

**Comment by photopea** [comment]
I am very sorry, there really was a bug in Photopea, it is fixed now.
