### ISSUE TITLE
photopea doesn't show PSD files properly

### ISSUE THREAD

**Issue by koyanagi1** [photopea/photopea#5166]
When I start photopea on the web and tried to upload a PSD file in my folde, it doesn't show properly from the beginning. It is supposed to show as attached original.png, but it actually show as the attached photopea.png. I tried to open in Incognito Mode, tried to disable the Enhanced Security Mode, but both didn't work.
![original](https://user-images.githubusercontent.com/120161550/206638645-66485865-4364-4e11-9ebc-df077635fa43.png)
![photopea](https://user-images.githubusercontent.com/120161550/206638699-e26db2f0-60a6-41d6-a536-89d1f73eeb94.png)

**Comment by photopea** [comment]
Hi, could you send us your PSD to support@photopea.com ?

**Comment by Mejbah09** [comment]
same problem with me

**Comment by photopea** [comment]
I am very sorry, there really was a bug in Photopea, it is fixed now.
