### ISSUE TITLE
PhotoPea is fully zoomed out

### ISSUE THREAD

**Issue by DirectContraband** [photopea/photopea#5167]
The zoom function was bugging and wouldn't let me move around the screen with only zooming in or out and then suddenly zoomed the whole photopea application out permanently 
![Photopeabug](https://user-images.githubusercontent.com/120167286/206652351-2b7a0339-be45-41a4-aabe-21d401800ad0.PNG)

**Comment by DirectContraband** [comment]
![Photopeabug](https://user-images.githubusercontent.com/120167286/206652550-6aa15666-6e56-4395-a514-abfc3088fead.PNG)
For reference against the rest of my screen

**Comment by photopea** [comment]
I think you have changed the website zoom in your browser. 

Press the "three dots" at the top right corner of your browser, and set the zoom back to 100%.
