### ISSUE TITLE
crashing.

### ISSUE THREAD

**Issue by ehllori** [photopea/photopea#5169]
I've been having trouble being able to finish a project because when doing something simple like erasing it will cause the window to freeze :(

**Comment by photopea** [comment]
Can you do it all again and make Photopea freeze again? If yes, could you tell us what you did (a few steps), or at least record a video of it?

**Comment by ehllori** [comment]
So I actually figured it out, everytime I was zooming out using my fingers,
it would zoom me out of the window and I wouldn’t be able to get me back
into the window properly, on mac btw

**Comment by photopea** [comment]
Photopea is configured in a way that you should always see at least a small corner if your work. So what exactly do you do?

**Comment by photopea** [comment]
I have to close it because of lack of details.
