### ISSUE TITLE
Script throws error when trying to access a text layers text color

### ISSUE THREAD

**Issue by mb-14** [photopea/photopea#5170]
I get the following error when trying to access the text item color for text layers in a Figma design file via a script:
`Uncaught TypeError: Cannot read properties of undefined (reading 'Values')`

The code I'm executing to get the color is as follows:
```
const color = textLayer.textItem.color
```

Note: This error does not occur in all text layers. It seems to be happening on certain text layers only (in this case it's happening for a layer that uses different colors for different words)

[Figma_design.zip](https://github.com/photopea/photopea/files/10208498/Figma_design.zip)

**Comment by photopea** [comment]
It should be fixed now.

So now, if you read the color or the size of a text layer, it will return the properties of the first character.

**Comment by mb-14** [comment]
Thanks for resolving this! I created a related issue around text styles (#5171). Let me know if that can be solved as well.
