### ISSUE TITLE
Layer Scaling Issue in SmartObject

### ISSUE THREAD

**Issue by Martinch713** [photopea/photopea#5173]
Not sure if I worded the issue correctly, but I'm finding issues with some PSD templates scaling layers correctly when saving smart objects. The image is saving scrunched and isn't filling the space as expected, leaving large white areas.

The left version of the attached image is what it should look like, and what it looked like a few weeks ago. Now when I try to replicate it, you see that the top layer is not scaling properly. This is happening on multiple computers in multiple browsers, no extensions, and with cache and cookies cleared. This is happening with several, but not all, of my template files.

![9DFD5F7C-694F-40E4-B4DE-BB0B7E65F971](https://user-images.githubusercontent.com/63259756/207225134-70f54388-60d1-4155-bc9b-48f25483ec50.png)

**Comment by photopea** [comment]
Could you send your PSD to support@photopea.com, so that I can look at it? We changed the way some smart objects are rendered about a year ago.

**Comment by Martinch713** [comment]
@photopea Sent. I had to send as a Google Drive link because the PSD was too big to attach.

Also this just started happening within the last couple of weeks. I just noticed on Saturday, December 3rd. But I didn't have the problem on November 12th.

**Comment by photopea** [comment]
Thanks for sending your file! It should be fixed now :) Try to re-apply the transform to see a correct result.

**Comment by Martinch713** [comment]
Thank you! It worked on multiple files that were having issues.
