### ISSUE TITLE
while dragging an item it swaps it to another item and drags it.

### ISSUE THREAD

**Issue by LogoBallers** [photopea/photopea#5174]
![PXL_20221213_074602018](https://user-images.githubusercontent.com/120449818/207256498-69004a01-4858-4b12-a734-880a781980aa.jpg)
![PXL_20221213_074614399](https://user-images.githubusercontent.com/120449818/207256510-4bd0f15a-dfd0-459e-8d76-b405a0deb117.jpg)

When I am trying to drag this folder, (mobile phone folder) it then only drags the screen out of the folder and not the entire folder. this has happened a few different times with different results, sometimes it pulls an item a lot further up the list and sometimes further down or inside a folder. either way the item that is selected is not the one that is dragged.

It has rendered this app useless as alternatives to dragging are so time consuming. (arrow keys still work.)

**Comment by photopea** [comment]
I think you have released your finger or a mouse in the middle of dragging. Nobody else reported such problem. Maybe there is a hardware problem with your mouse or your touchscreen. What should I do to replicate it? I can not make it happen :(

**Comment by photopea** [comment]
I have to close it because of the lack of details :(
