### ISSUE TITLE
Scaling issue within smart object layer

### ISSUE THREAD

**Issue by JENLYNNstockshop** [photopea/photopea#5175]
I saw someone else was having this issue and wanted to affirm that I, along with several of my colleagues are having the same issue. I sell mockups with smart object files and have not had this issue with files until the first week of December. When opening the smart object to place the design file within the smart object, once it's saved, the design only appears on a portion of the smart object image. See attached. These files have worked fine in photopea before, and currently work fine in photoshop, but until the last week I've been receiving reports that this is happening for multiple clients. Please advise!

Jenny
<img width="1085" alt="Screenshot 2022-12-13 at 2 18 56 PM" src="https://user-images.githubusercontent.com/120513082/207426009-b28b8d56-513a-4fcc-8522-150d02ac7ac4.png">
<img width="1082" alt="Screenshot 2022-12-13 at 2 24 37 PM" src="https://user-images.githubusercontent.com/120513082/207426099-8b361464-04c8-4f41-ba39-14d5c9295043.png">

**Comment by photopea** [comment]
I am very sorry for this, it should be fixed now. Let me know if it is not.
