### ISSUE TITLE
Can I add overprint to Stroke in Layer Style

### ISSUE THREAD

**Issue by zhengjianxiao** [photopea/photopea#5178]
this is in photoshop 
![image](https://user-images.githubusercontent.com/63221425/207799498-8d3de41b-0548-4216-adb4-94cba0d5df68.png)
![image](https://user-images.githubusercontent.com/63221425/207799692-048fda99-3a27-463a-a5b1-7a6ab0904364.png)
this is in photopea
![image](https://user-images.githubusercontent.com/63221425/207799850-90c9d14c-deb7-4aae-9a08-5fab6fd9095f.png)

**Comment by zhengjianxiao** [comment]
[test44.zip](https://github.com/photopea/photopea/files/10234848/test44.zip)

**Comment by zhengjianxiao** [comment]
And the waves in the smart filter aren't subtle enough
this is in photoshop
![image](https://user-images.githubusercontent.com/63221425/207802986-8b2da3fb-cedc-4405-9618-1704368611f5.png)
this is in photopea
![image](https://user-images.githubusercontent.com/63221425/207803164-c1cea8ad-7862-47c5-bf4c-79799b11da7f.png)

**Comment by photopea** [comment]
I have added the "Overprint" option and improved the Wave filter.
