### ISSUE TITLE
Keep doc size low when there's many exact same duplicated parts.

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#518]
I'm working on a doc which contains a lot of duplicated parts of the exact same element (just different position), I'm finding the doc size increase very fast.
This lead to me thinking that in some 3D programs like C4D or after effect, where there's particle objects and cloner objects, they use some "reference method" to duplicate them in large amount, without "actually" duplicating them, which is able to keep the file small and not bogging down the real time processing.

**Comment by photopea** [comment]
Do you mean PSD files? In PSD, each layer data is compressed separately, and I am afraid it is not possible. But if you use Smart Objects and export to SVG / PDF, "references" would be used instead.
