### ISSUE TITLE
Vanishing point problems 2

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#5180]
1) I created Plane with Create Plane tool.
2) I selected rectangle using Marquee tool.
3) I moved corner of Plane with Move tool
4) It generetes many errors in console while moving and plane and corner is not repainted during movement (only after left mouse button is released).
```
Uncaught TypeError: Cannot read properties of undefined (reading '1')
    at eO.VaPo.KT (pp.js:11780:35)
    at eO.VaPo.XF (pp.js:11707:99)
```
5) I pressed DELETE key on keyboard to delete this plane (while it still has selection in it)
6) It did not work and everything stops working - for example I can not switch tools or create new plane.

```
pp.js:11780 Uncaught TypeError: Cannot read properties of undefined (reading '1')
    at eO.VaPo.KT (pp.js:11780:35)
    at eO.VaPo.tK (pp.js:11701:67)
    at dG.tK (pp.js:12164:150)
    at b3.tK (pp.js:14751:116)
    at b3.IO (pp.js:14711:6)
```

**Comment by photopea** [comment]
fixed! Thanks a lot :)
