### ISSUE TITLE
I can't close the curent window!

### ISSUE THREAD

**Issue by bluntrapture** [photopea/photopea#5181]
I saw several comments with this problem. 
But never a solution. 
Photopea was having trouble recreating the situation.
But a lot of people, including me, still can't figure out to close a window.
There is no X in the top corner, no options when I right-click for closing the window, no trash can icons, and undo is not allowed.....unless I first close the current window! Which I can't for the life of me figure out how to do.

What ridiculously simple thing am I missing?

![phtpea](https://user-images.githubusercontent.com/120768979/208225739-ab86ba3d-2668-4701-93ed-92150a235dc2.jpg)

**Comment by photopea** [comment]
Hi, Photopea does not look as it should look. Is your web browser more than 10 years old? Could you download a modern web browser and try it again?

**Comment by bluntrapture** [comment]
I'm up-to-date with Windows 10 Dell XPS 8940 and Chrome.The screenshot is just the frozen dogpile of current windows --- I can't find any button or option to use to close them.
My problem is similar and almost word-for-word the same as a lot of others here.But I couldn't find a solution here, either.
I've had a stroke and so I'm a little bit dumber now, but I am pretty familiar with computers and apps and sites, etc.
So the pop-up that everyone and I am seeing is "CLOSE CURRENT WINDOW."
How?
Is there not a simple answer to how to close the current window? No button to click?

I'm still stuck.
    On Saturday, December 17, 2022 at 12:19:02 AM PST, Photopea ***@***.***> wrote:  
 
 


Hi, Photopea does not look as it should look. Is your web browser more than 10 years old? Could you download a modern web browser and try it again?

**Comment by photopea** [comment]
"My problem is similar and almost word-for-word the same as a lot of others here" - what are you talking about? Could you show us?

Please, tell me what version of Chrome are you using. Was it released before 2012 or after 2012? Also, try to run Photopea with no browser extensions, see https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by bluntrapture** [comment]
Chrome is up to date
Version 108.0.5359.125 (Official Build) (64-bit)

"what are you talking about?"

A couple comments that mention the same problem:

[JoshuaWyszynski](https://github.com/JoshuaWyszynski) commented [on Sep 28, 2020](https://github.com/photopea/photopea/issues/2485#issue-710478845)
"> I can interact with the window its self with moving it and clicking the setting in it, but I'm unable to close it or interact with anything out side that window. Closing the tab isn't an option for cause I need to save work. Is there a way to close that window with out losing work or a way to save files with right click inspect (ctrl+shift+I)"

"[hxim](https://github.com/hxim) commented [on Nov 13, 2017](https://github.com/photopea/photopea/issues/356#issue-273538962)
I forgot to confirm when typing text and went into Layer Style dialog.
I tried to change something there and it showed me "Close the current window first." I didn't know what is going. It was wrong and very confusing message it should say "Escape or Confirm the current action (in the top menu)." in this case."

"Posted by
[u/memeb0tt](https://www.reddit.com/user/memeb0tt/)
4 months ago
Can't close "layer style" window, I would appreciate some quick help because I'm not able to close it and can't do anything right now since I need to close the window, but sadly it doesn't allow me to."

"[u/showtunie](https://www.reddit.com/user/showtunie/)
2 years ago
Layer Style Glitch
I’m about to start freaking out.
I somehow opened the Layer Styles tab, and now it won’t let me close it. I can’t click outside of it, I can’t save my work. Can anybody help? Is there a way to restore Photopea after closing a window?"

So that's what I'm talking about --- the inability to Close the Current Window.
Is there a button to click, an 'X' to hit, some secret I haven't been told, or NO -- there is NOT a button, etc

That's all I'm asking: how to close the current window.

**Comment by photopea** [comment]
Please, try to run Photopea with no browser extensions. I think your extensions are breaking Photopea.

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by photopea** [comment]
Could you describe precise steps, which I should repeat to see the problem myself?

**Comment by demironmanx** [comment]
> Could you describe precise steps, which I should repeat to see the problem myself?
[Go to Chrome Extensions and turn them off](chrome://extensions/)
[Open Photopea.com](https://www.photopea.com/)
Press ALT + CTRL + N >>> Open new project
Type 'truck' into keywords
Press SHIFT + CTRL + N >>> Add new layer (Photopea must be in fullscreen, otherwise Chrome opens a new incognito tab by pressing SHIFT + CTRL + N)
While Layer 1 selected, Click Filter > Vanishing Point (VP)
Press C >>> Create Plane by clicking all four corners of the truck's side panel
Click OK on the upper right of the VP screen >>> Closes VP screen
Select a text layer from the layers panel on the right of the Photopea workspace
Press Confirm
Select Layer 1 and Select Filter > VP
Press T in the VP screen and select truck's side panel
Press CTRL + V to paste the pre-selected text layer >>> it says "Close the current window first."

**Comment by photopea** [comment]
I am confused about steps 9 - 10. Where should I press Confirm?

In the Vanishing Point filter, you should paste an image from the clipboard. 

To copy an image to a clipboard, you can e.g. select some part of the image and press Edit - Copy Merged. Or Edit - Copy to copy from the current layer.

**Comment by photopea** [comment]
You can not paste layers into the Vanishing Point! You can paste PIXELS, you need to make a selection to copy pixels.

**Comment by demironmanx** [comment]
![vanishing point success](https://github.com/photopea/photopea/assets/80745424/bc74cf0f-13f8-419c-97cc-4984f2cbebc6)

**Comment by photopea** [comment]
perfect :)  This can be done with the Free Transform tool, without the Vanishing Point Filter: https://www.photopea.com/learn/free-transform#:~:text=of%20predefined%20transformations.-,Perspective%20transform,-Scaling%2C%20rotating%20and
