### ISSUE TITLE
the cursor is not at where the actual working point

### ISSUE THREAD

**Issue by yingyezhufeng** [photopea/photopea#5182]
https://user-images.githubusercontent.com/9562379/208234417-043a6e70-2c94-43b9-8127-9b97874a369a.mp4

please see the the video if i didn't make it clear, the cursor icon is below the working point. I tried fullscreen and move the browser to my another monitor, both came up with the same issue.

OS: macOS monterey
browser: chrome Version 107.0.5304.121 

And i just tried safari, didn't see the issue, everything working well.

I found photopea.com recently and it's very convenient and efficient, thanks for the great work and best wishes to you guys.

**Comment by bluep55** [comment]
Under 'Edit,' 'Preferences,' make sure 'Curser offset' is set to zero.
![Screenshot 2022-12-17 140059](https://user-images.githubusercontent.com/118609932/208245828-8aaffb85-3140-464a-be67-6713b4420c04.jpg)

**Comment by photopea** [comment]
You probably chanded your Cursor Offset, as described above.

**Comment by yingyezhufeng** [comment]
indeed problem solved, i wasn't noticing at all because other functions all good. i could hardly remember whether it was me did that. thank you guys again, and sry for the delay in update.
