### ISSUE TITLE
Adjustment Issue

### ISSUE THREAD

**Issue by Spenc7r** [photopea/photopea#5184]
Hi Photopea Moderators, 

I'm having issues adjusting the Brightness/Contrast filter on your site. I have tried adding an adjustment layer, and also doing it directly to the layer, however it cannot be adjusted. The slider will not move, and the variables for the adjustments just say "NaN". Please fix this bug asap, because Photopea is a large part of my daily workflow.

**Comment by photopea** [comment]
Sorry, it should be fixed now.
