### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by ryuawata** [photopea/photopea#5185]
I've been unable to save files successfully. Whenever we press save, a notification that says 'saving...' appears but nothing happens. Below is what we're seeing in the console log:

<img width="819" alt="Screen Shot 2022-12-18 at 10 44 22 PM" src="https://user-images.githubusercontent.com/75017007/208349648-d3c79f82-1bb8-4233-a40c-4bd9bc90d29a.png">

Thank you!

**Comment by photopea** [comment]
It would really help if you told us you are editing a BMP file.

It should be fixed now :)

**Comment by ryuawata** [comment]
Sorry Photopea team! Noted, moving forward :)
