### ISSUE TITLE
Vanishing point problems 3

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#5188]
Problem 1
1.) Create Plane
2.) Move its corner with Move Tool
3.) Change Grid Gap
4.) Error shows in console and Grid Gap is not changed
Uncaught TypeError: Cannot set properties of undefined (setting '0')
    at cT.VaPo.aqi (pp.js:11695:51)
    at kk.c (pp.js:10164:49)
    at hd.c (pp.js:10169:77)
    at ht.mu (pp.js:10281:44)
    at ht.a6Q (pp.js:10291:95)

---
Problem 2
1.) Create two planes
2.) Select only first plane with Move Tool (click on it)
3.) Move its corner with Move Tool
4.) It will switch to second plane for no reason

---
Problem 3
1.) I changed Feather option in Marquee Tool to non-zero value
2.) It seems to have no effect on anything - it appears to behave as if Feather is always 0 when using Brush or Transofrm Tools

---
Problem 4
1.) I used Stamp Tool
2.) When I ALT+clicked blue cross appeared
3.) Now I want to use some other tools (for example Brush, Transform)
4.) Blue cross did not disappear even after I switched to other tools

**Comment by photopea** [comment]
Thanks, it should be fixed now :)
