### ISSUE TITLE
Crashing on reducing navigator window

### ISSUE THREAD

**Issue by fabiomcg** [photopea/photopea#5189]
I just lost a project because I simply reducing the navigator window that was in front of my work.
Then I realized that doing it again caused a new crash, so an error that always occurs.

Chrome 108.0.5359.125

**Comment by photopea** [comment]
Do you mean resizing the window by dragging its corner? I am trying to do it, but there is no crash :(

Maybe it happens only for a specific image size? Could you share your image with us, for which it happens?

**Comment by photopea** [comment]
I have to close it because of lack of details.
