### ISSUE TITLE
all bars and panels has lost

### ISSUE THREAD

**Issue by specialformyfuture** [photopea/photopea#5195]
when i tried to save a png file, somethig happens, and all panels lost from my workspace. I can use a hotkeys, but i need a panels, include a panel with save configs. can u help please
edit: to fix my problem i should enter a "menu bar and canvas" key, but there is no keys in my project

**Comment by photopea** [comment]
Could you share a screenshot of what you mean?

**Comment by specialformyfuture** [comment]
it's okay. I can save my project as a PSD and reopen it in new window.
