### ISSUE TITLE
Images not loading on photopea.

### ISSUE THREAD

**Issue by bloopgits** [photopea/photopea#5196]
I have tried restarting, resetting the cookies and refreshing the page. Can anybody help me
![Screenshot_1](https://user-images.githubusercontent.com/110291978/209148702-da738aab-7941-43e8-baff-bc4bf2bb67c2.png)
![Screenshot_2](https://user-images.githubusercontent.com/110291978/209148709-ab46d3e4-c2e2-411f-8c80-7eb55760710e.png)

**Comment by photopea** [comment]
Either your browser is too old, or you have browser extensions which break Photopea.

Please, report only problems which you can make happen in a modern browser with all extensions disabled.

**Comment by photopea** [comment]
I have to close it because of lack of details.
