### ISSUE TITLE
Feature request: support for ORF format

### ISSUE THREAD

**Issue by pcvd** [photopea/photopea#5198]
I would like to have support for the olympus/om-system ORF raw file format.

**Comment by photopea** [comment]
Could you share an ORF file with us here?

**Comment by pcvd** [comment]
Hi, PFA 1. ORF file from an Olympus camera and 2. ORF file from the OM-System camera.
[1 Olympus.zip](https://github.com/photopea/photopea/files/10324952/1.Olympus.zip)
[2 OM-System.zip](https://github.com/photopea/photopea/files/10324955/2.OM-System.zip)

**Comment by photopea** [comment]
Both of your images should work well in Photopea now. Could you try other ORF, if they work well?

**Comment by pcvd** [comment]
Both work fine now. Many thanks!
