### ISSUE TITLE
Scripting: how to open smart object?

### ISSUE THREAD

**Issue by yikuansun** [photopea/photopea#5199]
I was wondering if there was a way to open the activeLayer (assuming it is a Smart Object) as a document through Scripting (not a clone of the Smart Object, but the Smart Object itself; the idea is to modify the contents of the smart object and use Document.save() to update the smart object in the original document).

**Comment by photopea** [comment]
Sure, see here :) https://www.photopea.com/tuts/edit-smart-objects-with-a-script/ 

You can do everything the same way you do it in Adobe Photoshop.

**Comment by yikuansun** [comment]
Thank you!
