### ISSUE TITLE
Font styles

### ISSUE THREAD

**Issue by tomasnosek** [photopea/photopea#52]
Add editable font styles like in MS Word - beware of PS solution, it's a crap

**Comment by photopea** [comment]
Hi, what do you mean?  Do you mean the Style as a combination of size, color ... etc?

**Comment by tomasnosek** [comment]
exactly. Some tool with you can manage your font styles in document. PS has it, but designed very unwisely

**Comment by photopea** [comment]
In Photoshop, you create your own Character Styles / Paragraph styles, which are stored in a PSD. I can make Photopea load these styles and work with them the same way.

But I have another idea - we can detect all different styles (combinations of parameters) automatically, and create the list of all styles, that are used in the document. So you can not add or delete styles directly from that list. But you can click on them to apply an existing style to a selected text. What do you think?

**Comment by photopea** [comment]
Nobody suggested such feature in the past 3 years, so I guess it is not needed so much.
