### ISSUE TITLE
Distance with neighboring layer

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#520]
The distance info in move tool is very helpful when lining up layers, 
And the distance with neighboring layers is also helpful, but it's missing right now

**Comment by photopea** [comment]
When Distances is enabled (in a Move tool), select one layer and move your cursor on top of another layer. It should show the distance between them. Would you like it to work some other way?

**Comment by hgs54371** [comment]
When dragging one layer to position it right in between two neighboring layers, this would help to see if the distance on the two sides is already the same.

**Comment by photopea** [comment]
Neighboring layers could be completely unrelated layers, people would expect it to work for "visual neighbours", not "neighbours in the Layers panel". 

But there can be more than one layer on each side. Drawing rulers between each could be too messy. I think you should use a Grid or Guides in your case.

**Comment by hgs54371** [comment]
Yes, I mean visual neighbours for the nearest ones, maximum is four, one on each side, photoshop has this feature
