### ISSUE TITLE
Holy crap, what is going on?

### ISSUE THREAD

**Issue by ChaztasticChaz** [photopea/photopea#5201]
It's hard to say what's going on cause literally everything is failing. I can't use the paint brush tool cause all it does is put me into the colour picker tool. If I touch the layers it will create a mark or delete a layer, or turn it into a clipping mask. The blend modes are horrible,  they cause weird artifcating all over the place. Like, this used to be a great alternative to photoshop but now it's unusable at the moment.

**Comment by photopea** [comment]
There were 350 000 people using Photopea today  and nobody reported any such thing. Could you try this first? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
