### ISSUE TITLE
Feature Request: Monochrome/ B&W Mode

### ISSUE THREAD

**Issue by ABUCKY0** [photopea/photopea#5202]
In photoshop, Going to Image > Mode > Black And White allows the image to become black and white, but as a single channel. This would make editing black and white images eaiser, and making specific projects that require only a single channel for black&white would be much eaiser.

**Comment by photopea** [comment]
I am afraid that would be too much work for us, and almost nobody else needs it.

What is wrong in having identical values in red, green, blue, and editing all three channels simultaneously (= all three channels having the gray values) ? What exactly would be easier?

**Comment by photopea** [comment]
"on export if you want to export it as a single channel grayscale image," - what format are you talking about? How do you tell if a JPG or a PNG is a "single channel grayscale image"?

**Comment by MichalSZZ** [comment]
Here is a sample of how it looks like in Photoshop when the user switches to "Grayscale" color mode
![obraz](https://user-images.githubusercontent.com/38118273/213119474-c78786c6-0fbb-4c0e-b6a9-09168f16385c.png)

And after saving and opening it once again - the file has one channel in the channels palette and the color mode is "grayscale". This information is stored somewhere in the file. Photoshop after opening can read that. 

[Gold_Medal_Transparent_PNG_Clip_Art_Image.zip](https://github.com/photopea/photopea/files/10443721/Gold_Medal_Transparent_PNG_Clip_Art_Image.zip)

**Comment by photopea** [comment]
@MichalSZZ they talked about exporting as a single channel

**Comment by ABUCKY0** [comment]
Single Channel being grayscale in photoshop. Having only one channel only allows for b&w pictures. In photoshop, Grayscale is the single channel image.

**Comment by photopea** [comment]
We have only the RGB mode in Photopea. You can make grayscale pictures by painting only with shades of gray.

**Comment by ABUCKY0** [comment]
No I get that, just it would be nice to be able to export an image using just a single channel.
