### ISSUE TITLE
Not Open Properly

### ISSUE THREAD

**Issue by sourabhrawat25** [photopea/photopea#5203]
every tool show bigger in size and not showing images what i import so please solve this as soon as possible****

**Comment by photopea** [comment]
Try this https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by sourabhrawat25** [comment]
but yesterday it was working and today not

**Comment by photopea** [comment]
Let me know if you need any help.

**Comment by photopea** [comment]
I have to close it because of lack of details.
