### ISSUE TITLE
Recent change to brushes makes it much harder to precisely edit individual pixels

### ISSUE THREAD

**Issue by nckencke** [photopea/photopea#5205]
Until recently, I used to use the square brush (the one that defaults to 20px) when I wanted to edit individual pixels without bleeding into the neighboring ones. With the new version, if you're a little bit off, the brush affects neighboring pixels. This makes it very impractical to do things like create pixel art or edit one-bit black and white images.

I recognize that this update is an improvement for most people, and I welcome it in most cases, but is there a way I can use the old system when I need it? Can I access an old version of Photopea? Or, is there a better way to do what I was doing?

**Comment by nckencke** [comment]
Never mind, I found the pencil tool.

**Comment by photopea** [comment]
Yes, you should use the Pencil tool for this.
