### ISSUE TITLE
Can't export images. Saved as PSD but with 0 bytes.

### ISSUE THREAD

**Issue by YoCharged** [photopea/photopea#5206]
I can't export my image in PNG/JPEG and when I save my file as a PSD there is 0 bytes in the file. Basically I can't even save my work and I had to redo it twice. I was using Photopea for almost 3 years now and this is the first time I'm having this bug.

**Comment by photopea** [comment]
Could you tell me if it happens in a web browser with all browser extensions disabled?

**Comment by photopea** [comment]
Are there any news? We always recommend this when something does not work: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by YoCharged** [comment]
It now works, I think it was just because my storage was full. But thanks!

**Comment by photopea** [comment]
ok
