### ISSUE TITLE
List missing fonts using scripting API

### ISSUE THREAD

**Issue by mb-14** [photopea/photopea#5207]
I'm trying to list missing fonts using the scripting API based on the code provided here: https://community.adobe.com/t5/photoshop-ecosystem-discussions/list-of-missing-fonts-in-photoshop-psd-images/m-p/11845539

But it doesn't seem to be working. It throws the following error
`Uncaught TypeError: Cannot read properties of undefined (reading 'V')`

**Comment by photopea** [comment]
We dont support scripts involving ActionReferences .

Photopea prints all missing fonts in a web console right after you open a PSD.

**Comment by mb-14** [comment]
> We dont support scripts involving ActionReferences .

I feel like this should be mentioned in the documentation so that developers don't end up wasting time trying to implement and execute scripts involving ActionReferences.

**Comment by mb-14** [comment]
> Photopea prints all missing fonts in a web console right after you open a PSD.

Although quite useful, it's not enough when I want to relay any missing font information to a user who doesn't know how to access the web console. Is there any way you can provide programmatic access to these alerts?

**Comment by photopea** [comment]
I have implemented ActionReferences, your script should work now.

**Comment by mb-14** [comment]
It does work! Thanks!
