### ISSUE TITLE
Incorrect file path when uploading files to a folder in a private Google Drive

### ISSUE THREAD

**Issue by Wimull** [photopea/photopea#5209]
### Description
When uploading a file to a private  Google Drive folder through the drive view in the Photopea app and storing it to a folder inside that Drive, the file thens gets incorrectly assigned to the folder, with the uploaded file name being prefixed with that folder's name and the file being stored in the origin folder of the Drive.

### Example
![image](https://user-images.githubusercontent.com/100626007/209603111-34ecd6cb-d284-4bfe-b04d-3d0c6e753496.png)
![image](https://user-images.githubusercontent.com/100626007/209603153-690a6f4c-0b93-4005-9c77-ab318b809fba.png)

**Comment by photopea** [comment]
Thanks for reporting, it is fixed now :)
