### ISSUE TITLE
Grouping non neighboring folders leads to them disappearing

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#521]
When layer count reach a certain point, drag n drop to reorder layers in layers panel is not functioning, so I select non neighboring folders to group them(cmd-g), which leads to them disappearing

**Comment by photopea** [comment]
I just tried to group two non-neighbouring folders and they were grouped correctly. Could you please show us some PSD, in which it happens?

**Comment by hgs54371** [comment]
I think this is related to the "layer order" jump issue in layers panel when grouping layers, and there are many layers inside the folders being grouped, so it's a big jump down the order in the layers panel, which seems that it disappeared.
