### ISSUE TITLE
Cannot open files from my harddrive 

### ISSUE THREAD

**Issue by icejo123** [photopea/photopea#5211]
<img width="445" alt="Screenshot 2022-12-27 at 10 08 47" src="https://user-images.githubusercontent.com/121486158/209643315-f74aa574-6889-4be1-8f15-e3181cf6e735.png">
IFor the last couple of weeks I keep getting this. Dont understand why and cant find a solution. The folder is accessible to anyone on my computer

**Comment by photopea** [comment]
I never saw such thing. This message is from your web browser, not from Photopea.

Are you using File - Open? Did you try to open files from a different folder?

**Comment by icejo123** [comment]
thats weird. used file open and dragging. both dont work. the only folder it seems to work from is the desktop folder which is weird (and I usually dont have my files there)

**Comment by MichalSZZ** [comment]
@icejo123 are you using a Mac OS or Windows? On mac, there are some invisible files and folders that start with a dot nad __ (.DS_Store file and __MACOSX folder). That may be the reason.

**Comment by photopea** [comment]
I have to close it because of lack of details.
