### ISSUE TITLE
Need option to search inside documentation

### ISSUE THREAD

**Issue by zcraber** [photopea/photopea#5212]
Currently, there is no search option. 

![image](https://user-images.githubusercontent.com/61133303/209798536-459beb46-be21-402f-b99e-4a7df765c62b.png)

**Comment by camoody1** [comment]
Agreed. This would be a nice to have for new users, for sure.

**Comment by camoody1** [comment]
Test

**Comment by photopea** [comment]
Could you just use Google Search? 
![image](https://user-images.githubusercontent.com/15955558/210241870-ad064d70-a287-470b-a6e7-bd54eb9ec09d.png)

**Comment by zcraber** [comment]
> Could you just use Google Search? ![image](https://user-images.githubusercontent.com/15955558/210241870-ad064d70-a287-470b-a6e7-bd54eb9ec09d.png)

Isn't it better to implement [Google's custom search option](https://programmablesearchengine.google.com/) for websites then? It's easy to add and will provide tailored results from your website rather than googling the search term every time with "photopea learn".

**Comment by photopea** [comment]
Ok, I have added a search box to www.Photopea.com/learn :)
