### ISSUE TITLE
[Firefox] Photopea still showing Ad blocking detected after disabling adblocker for photopea only and switching off enhanced tracking protection

### ISSUE THREAD

**Issue by nesper8** [photopea/photopea#5215]
![Screenshot from 2022-12-29 21-44-06](https://user-images.githubusercontent.com/57890520/209980563-c4533449-785d-456d-8f8d-9e8d6c9a365b.png)

**Comment by photopea** [comment]
I am using Firefox with default settings and zero browser extensions. Here is what I see in Photopea.

![image](https://user-images.githubusercontent.com/15955558/209996645-2112775e-027e-440a-89c0-b7295b7f3ac4.jpg)

What do you mean by "disabling adblocker"? Do you still have any extensions enabled? Unless you created these extensions, you can never know what they do (they could be blocking ads).

**Comment by nesper8** [comment]
I have it enabled globally

What I referred to was Ublock Origin's ability to enable ads on user specific sites which I have set Ublock to not block ads from photopea

**Comment by photopea** [comment]
Did you try to disable all extensions? It could be a bug in your extension, did you try to report it to them?

**Comment by nesper8** [comment]
the only other extension i use is fastforward a shorturl bypasser
whats funny is that no ads are even displaying when i disabled ublock, enhanced tracking protection and fastforward

im closing the issue tho as this might not be a problem with photopea itself

**Comment by photopea** [comment]
Your internet provider could be monitoring and modifying your internet traffic.
