### ISSUE TITLE
CMYK Profile

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5217]
Here we go again with CMYK.

I want to share something: When changing modes in Photoshop or AI from RGB to CMYK, i believe, the project gets a profile that goes within.

So when someone opens a PSD from Photopea on Photoshop, even if it has the CMYK gamut, the profile is RGB:
![image](https://user-images.githubusercontent.com/11801254/210082023-9af721a2-1453-4682-b426-267becc05954.png)

And they always follow that indicator to know if the CMYK profile is applied.
![image](https://user-images.githubusercontent.com/11801254/210082032-93703534-04e1-4649-a4f0-4b6148c5fa37.png)

And they return me the image to change it, because they "see" that the image has not the adequate color profile

So, i know that the CMYK mode in Photopea changes the preview of the RGB profile, and it also exports the project within the boundaries of the color gamut of CMYK. But the PSD does not indicate, when it is open in Photoshop or AI, that it has a color profile attached.

Thus, my request will be that:
When i use the CMYK mode and save the PSD, it should have a CMYK profile in it, so when someone opens it in another editing software, they will be able to see that it is in CMYK color profile.

I am not asking to change the way the CMYK display colors, but to be able indicate on Photoshop or AI that i have worked on CMYK

**Comment by TheRadicalDreamer** [comment]
I know it looks like a tedious indication, and it is true, it is a legacy issue.

**Comment by photopea** [comment]
They should be able to press Image - Mode - CMYK Color in Adobe Photoshop, and have what they need. What is wrong with that?

**Comment by TheRadicalDreamer** [comment]
i know that they can do that, and i have said it.

But i am working against the instinct of a normal way to work.

They don't want to do or think more than they already do.

 And this happens only with me, so from their side, it seems that I am the cause of the problem.

This only happens because they see that indication on the tab of the proyect
![image](https://user-images.githubusercontent.com/11801254/210289318-49ba2daf-832c-441d-b6ff-b33682631adc.png)

**Comment by photopea** [comment]
We have implemented it. If you switch from RGB to CMYK, saved PSD files should be in CMYK.
