### ISSUE TITLE
Drag n drop reordering in layers panel not working after layer count reach certain point

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#522]
Other functions still work but this is the first function to not responding

**Comment by photopea** [comment]
Hi, I just crated several hundreds of layers and tried to reorder them. I made this demo: https://goo.gl/FemEgV

In Firefox, everything works fine.

In Chrome, everything is very slow. After you release the layer, you have to wait 5 or more seconds until you can see the result. I reported it to Chrome developers: https://bugs.chromium.org/p/chromium/issues/detail?id=820798

**Comment by hgs54371** [comment]
What I meant by layer count is not merely the numbers, but also the contents are heavy as well,
I'm on firefox mac version, problem as described as the first post, I thought maybe there's something specific to that function rendering it not usable when others still working fine

**Comment by photopea** [comment]
Can you show us a PSD, for which it happens?
