### ISSUE TITLE
Feature Request: Brush Groups for Better Organization

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5220]
I (97Buckeye from Reddit) know how to add brushes in Photopea. However, when I add a single brush or even a large group of them at once, they all just dump into the main list of all brushes. In Photoshop, they actually allow you to create Brush Groups that you can sort your brushes into to keep things tidy. Here are some screenshots showing what I'm talking about:
https://imgur.io/a/3n92dhD

Now, since Photopea is a web based application, maybe this isn't possible. But with your obvious genius, perhaps you could come up with some other option to achieve a similar result? :)

P.S.
If you can figure out a way to make this work, it would be great to apply the same folder organization to the available fonts in the application. The giant scrolling list of 100+ fonts is just screaming out for some organization.

**Comment by photopea** [comment]
The latest Adobe Photoshop also puts Gradients, Patterns, Styles and Shapes into folders. But not Contours :/

**Comment by photopea** [comment]
I have implemented this feature, it works for Brushes, Gradients, Patterns, Styles and Shapes.

Items are separated into groups, each group has a name at the top (the name of a file which contained the items).
