### ISSUE TITLE
Semi-transparent pixels in PNG output appear white-ish

### ISSUE THREAD

**Issue by lucadalli** [photopea/photopea#5223]
The shadows in this PSD are appearing white-ish when exported as a transparent PNG. Bug reproduced on Chrome and Firefox. 
https://www.photopea.com/#iZLq1VHT_.psd

**In Photopea with a dark background applied:**
<img src="https://user-images.githubusercontent.com/39853447/210261285-a1f4ce2c-4df4-4c65-93f6-ced28c1226fc.png" width="400">
**Exported as a PNG with a transparent background, viewed in Chrome with the dark background applied via DevTools:**
<img src="https://user-images.githubusercontent.com/39853447/210261421-bbfbcad2-e311-40af-a812-e0febdefdcaa.png" width="400">

**Comment by lucadalli** [comment]
Not a bug, my bad. Shadows in this PSD are white with Linear Burn applied.

**Comment by photopea** [comment]
Yeah, blend modes can not be stored in a PNG image.
