### ISSUE TITLE
Feature Request: Radial Symmetry to Brush Tool

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5224]
I found this feature has been requested at least twice before. You closed one ticket by referencing the other, and then closed the other by referencing the first ticket. I'm not sure you even meant to close them both?

The two tickets are #3045 and #3173

It sure would be helpful to have this option for creating brushes, patterns, and other symmetrical designs.

**Comment by MichalSZZ** [comment]
In digital painting, there is a method to draw faces/heads in that way.

**Comment by TheRadicalDreamer** [comment]
Yes!!! :D

**Comment by camoody1** [comment]
Bumping issue for a reminder 😁
![image](https://github.com/photopea/photopea/assets/73725653/d9caa467-ce24-4204-ae6a-b100059831b2)

**Comment by DigitalNaut** [comment]
It's not enough to just copy and mirror a layer every time you make a change like the dev suggested. Heck, even [a script](https://github.com/photopea/photopea/issues/6082#issuecomment-1751622789) to automate the process isn't nearly as useful.

**Comment by RunnitMusic** [comment]
BUMP.  symmetrical mode is great for logo/typeface work also

**Comment by paperjack93** [comment]
+1

**Comment by MichalSZZ** [comment]
This is a super useful tool for people who use the brush tool https://www.youtube.com/watch?v=9nW15KJwAuk watch the video - he uses the simplest one mirroring for drawing (and I thing most ppl here wanted to have that symmetry)

**Comment by ReynoldsCahoon** [comment]
Would love a symmetry preview while working on mirrored images.

**Comment by stefano-elysium** [comment]
+1

**Comment by photopea** [comment]
I have implemented it


https://github.com/photopea/photopea/assets/15955558/44c03ccb-7aff-4399-9ead-ea05c66269cd

**Comment by camoody1** [comment]
This is great, Ivan! Thank you
