### ISSUE TITLE
Photopea scripting - app.open

### ISSUE THREAD

**Issue by almousa1990** [photopea/photopea#5228]
Hi,

Thanks for the great efforts put in this amazing product. I am trying to use live messaging API but noticed an odd behavior with 'done' messages when using app.open.

The first case when app.open is used with only URL parameter (no asSmart), the iframe would send 2 'done messages'. the first after receiving the command, and the second after loading the actual file. Which in my humble opinion doesn't really help when trying to wait open action before executing further action.

Also, when using app.open with asSmart set to true, the iframe would send only the first 'done' message after receiving the file, with no additional messages after the file is loaded.

Note that happens when i try to open from external URL, and not sure if the issue persist with local files.

**Comment by photopea** [comment]
I think that is how it should work, as described at www.Photopea.com/api . You can load files yourself and send them as a binary ArrayBuffer to Photopea.

**Comment by almousa1990** [comment]
Thanks for the prompt feedback. The scripts executes as expected, the issue is with how photopea is sending ‘done’ messages as described above

**Comment by photopea** [comment]
There is a message "done" sent when the script finishes. The script could initiate a download of a file from the internet.

When a separate document is opened, Photopea also sends "done".

So in your example, a number of "done"s depends on the "asSmart" parameter.
