### ISSUE TITLE
pen pressure works, but with a weird diffect

### ISSUE THREAD

**Issue by leandrodreamer** [photopea/photopea#5229]
right at the start of the stroke and sometimes at the end the pressure detected jumps back to around 50%, the problem appears to happen whenever the tablet is at the lowest pressure, like photopea considers the "0" level as no pressure support (thats my guess)

https://user-images.githubusercontent.com/26260718/210656689-4224d90b-d6c9-41b4-8070-85d697eda720.mp4

tested on chromium and chrome in linux with a huion tablet, for reference here is the behavior in another web drawing app (aggie.io) in the same browser, system and tablet

https://user-images.githubusercontent.com/26260718/210656916-a8885d0b-6174-4762-83ee-10ae51a1ec56.mp4

here it works as expected, no matter how gentle i brush, in photopea if i brush very gentle it also jumps to a medium pressure

**Comment by photopea** [comment]
I think I have fixed it. Could you try it again? BTW. Clear your cache or use the incognito mode.

**Comment by leandrodreamer** [comment]
yea that seems to be fixed now, great!
![imagen](https://user-images.githubusercontent.com/26260718/210666137-14d6463f-7fd3-496d-ae3d-aa7ddb9a8b67.png)
