### ISSUE TITLE
Extract depth map from RGB-D data (Python, OpenCV, ImageIO, Open3D, Pillow)

### ISSUE THREAD

**Issue by aktumar** [photopea/photopea#5230]
Hello, I have a question regarding extracting the depth map from an image. How exactly are you extracting depth-map? I'd like to implement RGB-D reading into my Python code, but I'm running into a problem: I can't read the 4th channel. I'll show you more below.

## **What I got in Photopea:**

![2023-01-04-23-08-55](https://user-images.githubusercontent.com/57950494/210673256-e08298bb-54dc-4574-80c9-fe97e0773eec.png)

## **What I got through the code:**

![2023-01-04-23-10-57](https://user-images.githubusercontent.com/57950494/210673282-59632dd3-80f7-48f5-a643-ad0aebbb7108.png)

## **What I used to read the image:**

**1st try: OpenCV, [link](https://stackoverflow.com/questions/71938246/saving-rgbd-as-single-image)**
Error: _IndexError: index 3 is out of bounds for axis 2 with size 3_
```
import cv2 as cv
depth_image = cv.imread("IMG_2071_org_rgbd.JPG", cv.IMREAD_UNCHANGED)
img = depth_image[:, :, 0:3]  # First 3 channels are the image.
depth = depth_image[:, :, 3]  # Last channel is the depth
cv.imshow('img', img)
cv.imshow('depth', depth)
cv.waitKey()
cv.destroyAllWindows()
```

**2nd try: OpenCV, [link](https://stackoverflow.com/questions/57736832/how-can-you-read-rgba-using-opencv)**
Error: Alpha channel (4th channel, depth) is all 255
```
import cv2 as cv
depth_image = cv2.imread('rgbd.png', cv2.IMREAD_UNCHANGED)
img = cv2.cvtColor(depth_image, cv2.COLOR_BGR2BGRA)
print(img)
```

**3rd try: Pillow**
Error: Does not contain information about the 4th channel
```
from PIL import Image
from numpy import array
depth_image = Image.open("IMG_2071_org_rgbd.JPG")
ar = array(depth_image)
print(ar)How you process, thanks in advance for the answer.
```

**4th try: ImageIO, [link](https://betterprogramming.pub/point-cloud-computing-from-rgb-d-images-918414d57e80)**
Error: Does not contain information about the 4th channel
```
import imageio.v3 as iio
depth_image = iio.imread("IMG_2071_org_rgbd.JPG")
print(depth_image)
```

**Comment by photopea** [comment]
I neve used Python or any library which you mentioned.

Every camera stores a depth map in a different way. There is no universal way to detect a depth map.

Usually, there is a second JPG file inside the main JPG file from a camera. Photopea goes through each byte and looks for bytes 0xff, 0xd8, 0xff ...  which is usually a beginning of a JPG file.

**Comment by aktumar** [comment]
Okay, thanks for the feedback!
