### ISSUE TITLE
Brush Tool Not Working For Me (Photopea)

### ISSUE THREAD

**Issue by tystrks97** [photopea/photopea#5231]
I don't know why but for some reason my brush tool isn't working for me. It should be as simple as selecting the brush tool, picking a color, and brushing but nothing happens when I do. I don't know if I am doing something wrong but it's becoming frustrating  because I can't finish my design now.

**Comment by photopea** [comment]
Hi, are you using Safari?

**Comment by tystrks97** [comment]
No I was trying on Chrome first but it wasn’t working there. So I switched
to Firefox and it wasn’t working there either.

**Comment by photopea** [comment]
Could you maybe record a video of opening www.Photopea.com in an incognito window, and trying to paint, so that we can see what you do? Are you using a mouse / a pen / a finger on a touchscreen?

**Comment by tystrks97** [comment]
It’s working perfectly fine in incognito mode I’m able to edit my design
with the brush tool now.

**Comment by photopea** [comment]
I think you have browser extensions, which are breaking Photopea. Browser extensions are disabled in the incognito mode.

If you dont know what your browser extensions do, or how to turn them off, you can use Photopea in the Incognito mode.

**Comment by D1Z2YonVR** [comment]
@photopea i dont see the brush tool, and i need it for my thumbnail. Is there anyway you could help me?

**Comment by photopea** [comment]
Press the magnifying glass icon at the top and type "Brush", to find the brush tool.
