### ISSUE TITLE
when i try to draw with the paint brush tool i can only move verticaly OR horizantaly 

### ISSUE THREAD

**Issue by georgeporge90** [photopea/photopea#5232]
![Screenshot 2023-01-05 4 20 17 PM](https://user-images.githubusercontent.com/122064261/210904693-78abdb8d-bba3-41e4-8ff1-4fb083d6d6ea.png)

**Comment by georgeporge90** [comment]
i can only draw verticaly horizantaly

**Comment by camoody1** [comment]
Sounds like a stuck SHIFT key. Make sure both of them are free and not sticky.

**Comment by photopea** [comment]
Can you close Photopea and open it agan? Does it still happen? Also, try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by georgeporge90** [comment]
thank you
