### ISSUE TITLE
Ad blocking detector Doesnt detect when I disable it threw the extension settings

### ISSUE THREAD

**Issue by Squirrelpro123** [photopea/photopea#5234]
I set my adblocker to show ads on photopea but it still asks me to turn it off And switches them to developer ads
![Photopea _ Online Photo Editor - Google Chrome 1_6_2023 7_08_48 PM](https://user-images.githubusercontent.com/122133782/211124333-8e219a50-f3f5-4f82-9b3e-06c03ea3c008.png)

**Comment by photopea** [comment]
A website (e.g. Photopea.com) has no way to check if you have any browser extensions. When we can not establish a connection to our ad provider, we consider it to be an "adblocker usage". Something in your browser is blocking such connection.

If you told your extension not to interfere with Photopea, but it still does, it sounds like a bug in that textensions. Have you reported it to those who created it?

**Comment by Squirrelpro123** [comment]
Hey so I checked the extensions website and it had an article about it, I tried everything and it kind of worked, Until I refreshed and it thought I had it enabled again. Maybe its just false positives and the anti adblock is to strict? Heres a screenshot of the article to
![A site still asks me to turn off AdBlock although it's allowlisted or AdBlock is paused – AdBlock - Google Chrome 1_18_2023 9_50_05 PM](https://user-images.githubusercontent.com/122133782/213351351-ce26d97c-f59f-4e1d-9f4d-688790ff3324.png)

**Comment by photopea** [comment]
When we can not reach our ad provider, we consider it to be ad blcoking.

Did you try to disable your extension completely? What does Photopea say then? If Photopea works differently, your extension is clearly "doing something". Maybe try a different ad blocker.

**Comment by Squirrelpro123** [comment]
When I disable it completely they come back but It disables it for all websites, I tried a few other ones and most of them still had the anti adblock when I disabled it for the website but I just found an adblocker that when Disabled for photopea it doesnt show the anti adblock. Thanks!

**Comment by photopea** [comment]
You can ask the person who made your adblock to make a feature to let you to turn it off just for one website.

**Comment by Squirrelpro123** [comment]
I thought you where talking about disabling the extension itself, It already had that feature but It doesnt let me turn off what is considers tracker blocking and I think either the extension confused photopea or it blocked a thing required to show ads thinking it was a tracker I closed the issue it because Im just using a diffrent adblocking extension that works with photopea when I disable it and works fine

**Comment by photopea** [comment]
ok
