### ISSUE TITLE
wtf is your UI

### ISSUE THREAD

**Issue by CesarGift** [photopea/photopea#5239]
Everything is an issue your horrible system sucks, and also it has a terrible UI i cant even move pictures however i want to and cropping something that should be that simple is annoying and stupid pls just make it simple and useful

**Comment by camoody1** [comment]
Thank you for your feedback. Could you be a little more specific with your issues, please? Perhaps include some screenshots or a short video showing your concerns.

**Comment by photopea** [comment]
Also, try this first: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
