### ISSUE TITLE
Save frequently used fonts as favorite

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#524]
It would be good if some of the "default" can be changed to user preference,
such as canvas size, first font loaded, font size, color in color picker... or at least remember its last state.

**Comment by photopea** [comment]
Hi, I just made the New Project window remember the previous value.

Foreground / background colors (at the bottom of the toolbar) are already remembered even after closing Photopea. Default text parameters are easy to change. E.g. once you select some text layer, its format is set as default and will be used e.g. for the new text layer, that you create.

**Comment by hgs54371** [comment]
Yes, but I forgot to mention the title in post, I mentioned something else.
What I mainly mean is the ability to tag "several" fonts as "favorites", and have a "category" named "favorites" to choose from. In other words, a custom category of font"s"

**Comment by photopea** [comment]
That sounds like a nice idea. But where should such favourite fonts be located? I am afraid it would be too complex to use by regular users.

**Comment by hgs54371** [comment]
Put a click-able icon like a star in front of every fonts in the font list for tag them as favorites.
Add a checkbox category called favorites for storing these tagged fonts.
The checkbox category list now shows Sans Serif, Serif, Display, ... 
The favorites checkbox will be first on this list, above Sans Serif

**Comment by hgs54371** [comment]
Also the foreground/background colors not remembered properly, I'm on firefox mac version, every time I open it's red and black
