### ISSUE TITLE
Clicking on menus and buttons has no effect

### ISSUE THREAD

**Issue by andrewatya** [photopea/photopea#5243]
Dear Team,

I tried to export my PSD file to JPG, I ckicked on Export as .jpg, but no reaction. The menu does nothing. I tried a few other elements, and the same result. I uninstalled every plugin from Chrome. I opened it in Chrome, bot the same issue. For example: "More" menu, "About Photopea" submenu button. Click on it and nothing happens, no action on click.
Please help me.
Thanks,
Andras

**Comment by pluggyboy** [comment]
having same issue.

**Comment by andrewatya** [comment]
So, I have one solution: clear all cache in Chrome, restart Photopea or Chrome (temporary files).
It would be nice if stuff check this what happens in the back ;)

**Comment by photopea** [comment]
Just clear your cache, or wait an hour (you can use Photopea in the Incognito mode for the next hour).
