### ISSUE TITLE
No new project is created

### ISSUE THREAD

**Issue by Flurbis** [photopea/photopea#5248]
I just can't create a new project no matter how hard I try

**Comment by photopea** [comment]
Did you try to close Photopea and open it again?

**Comment by yesnomaybe23** [comment]
It's the same here. I closed photoshop, cleared cookies, restarted the computer, but nothing happens. I still can't create or open a project.

**Comment by photopea** [comment]
I can use www.Photopea.com without any problems. Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I think these people are using Photopea at some random websites, not at www.Photopea.com .

We are not responsible for other websites. Our product is only www.Photopea.com . Do not report problems with other websites to us, they are not under our control.
