### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by iamsickandtiredoftryingtofindusernames** [photopea/photopea#5249]
For some reason, my filters stopped working.  I also can't seem to find the relief filter.  Anyone else have this happen, or have advice for me?  Thanks!

**Comment by iamsickandtiredoftryingtofindusernames** [comment]
Thanks for getting back to me so quick!  I think the photo was probably jpeg (I didn't look at it, just dragged it from a google photo search).  I exported to SVG, opened that one, and all the filters work!  I also found the bas relief.
![soaring eagle](https://user-images.githubusercontent.com/122367760/211571271-cb3b83a0-835d-4122-90fe-34922e11fc35.svg)
![soaring eagle-svg](https://user-images.githubusercontent.com/122367760/211571327-172e7d64-b580-4be0-99c9-4b1b026813ad.svg)
First file is the SVG I saved, 2nd is the SVG after the bas relief.  I hope they show up!

I wanted to use the relief file to make a height map.  I'd like to be able to do this in photopea since I used to use photoshop at work and they're very similar, but that was in the 90's and so much has changed.  Anyhow, thanks again, and if you know about a height map in photopea, could you let me know?  If it's in the paid version, I'll happily pay.  If I can do the height map here, I can use photopea to set up g-codes for carving.

**Comment by photopea** [comment]
Do you still have any problems? Do you want us to add a new filter "height map"? Could you describe how that filter looks like?

**Comment by iamsickandtiredoftryingtofindusernames** [comment]
The height map would be for the 'Z' axis on a CNC router, which is depth.  Here's a picture that kind of shows what I'm talking about.  
![image](https://user-images.githubusercontent.com/122367760/211586543-df50d25d-426b-4cab-8f7e-26c6070f1feb.png)
 
CNC routering is still a hit and miss kind of thing.  It's difficult and frankly frustrating to the point you almost want to give up to figure things out.  Here's a website that shows a good example (I've been playing around with my CNC for months, doing lots of searches, and just today came across this one).  CAD, CAM, and Controller software, and they all have a learning curve after you find out you need 3, although some come with 2 (CAD and G-Code).  https://carbide3d.com/learn/free-cnc-software/#grbl  You have been so great working with me like this!

**Comment by iamsickandtiredoftryingtofindusernames** [comment]
Thanks, it's all good.  Just trying to slowly find my way thru the CNC world, and believe it or not...you were a lot of help!

**Comment by photopea** [comment]
Ok, I will close it now.
