### ISSUE TITLE
Leading in character panel can't change back to default "auto" once edited.

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#525]
After I tried other value in the leading pt field, and want to go back to "auto", it just jumped to zero.

**Comment by photopea** [comment]
You can set the value Auto by typing in "Auto" and hitting Enter.

**Comment by hgs54371** [comment]
I've tried this but it was not working when this post was created, but now it works, have you fixed something or there might still be something wrong

**Comment by photopea** [comment]
Previously, you had to enter "Auto".  I fixed it, so now the letter-case does not matter ("auto", "aUtO" ...)
