### ISSUE TITLE
Приложение не работает целый день

### ISSUE THREAD

**Issue by Adamkovski** [photopea/photopea#5250]
Здравствуйте, не могу создать, загрузить с компьютера psd и вообще что либо. Перезагружал, чистил историю и тд и тп, приложение не работает.

**Comment by photopea** [comment]
Hi, could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
We dont have any приложение , we only have a website www.Photopea.com

**Comment by camoody1** [comment]
So weird that you're getting multiple reports of not being able to open projects. I wonder if there's an internet issue somewhere that they're all being affected by? So odd.

**Comment by Adamkovski** [comment]
Thanks, none of the suggested options worked.
This program works online https://photopea.ru/photoshop-online but with
bugs, https://online-fotoshop.ru/ here is a nicer interface, before the new
year everything worked perfectly, now it doesn’t work at all.

вт, 10 янв. 2023 г. в 17:47, Photopea ***@***.***>:

**Comment by Adamkovski** [comment]
Not correctly expressed, does not work in the browser

вт, 10 янв. 2023 г. в 17:47, Photopea ***@***.***>:

**Comment by photopea** [comment]
You should use Photopea at www.Photopea.com .
