### ISSUE TITLE
feature request: anti-clockwise twirl

### ISSUE THREAD

**Issue by DuckyMacfly** [photopea/photopea#5251]
Hi! I just wanted to ask if it's possible to add anti-clockwise twirl tool in the liquify section since we already have the normal twirl tool. That would be great! Really enjoying the site so far, you guys clearly put a lot of work into it!

**Comment by photopea** [comment]
Hi, you need to hold Alt on your keyboard to twirl anti-clockwise. See https://helpx.adobe.com/photoshop/using/liquify-filter.html

**Comment by DuckyMacfly** [comment]
Ah right, thanks!
