### ISSUE TITLE
Photopea stopped responding mid-work

### ISSUE THREAD

**Issue by 3mr9** [photopea/photopea#5253]
**It happened once before.**
I cant move layers, change them, save the project (I can't download it, save it to storage. none of them work).
it happened after I add curve option for a text layer.
please help.
_Browser: Brave._

**Comment by photopea** [comment]
Are you using Photopea at www.Photopea.com ?

Could you tell me, what should I do after opening www.Photopea.com to see such behaviour?

**Comment by 3mr9** [comment]
this is what I'm using: (https://www.photopea.com/?utm_source=homescreen)
i don't know since I've had this problem once before, but if imp not mistaken it will happen after changing fonts for long texts.

**Comment by photopea** [comment]
So could you make it happen again? I need to see the bug happen myself, and to be able to make it happen myself.

**Comment by photopea** [comment]
Could you try this and let me know if it helped? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by 3mr9** [comment]
Hi sorry for late response.
yes I've tried it and it didn't work.
(btw. closing photopea resolve the problem, it will run just fine. but I don't want to lose my work again.
_this person on reddit seems to have the same problem_ (https://www.reddit.com/r/photopea/comments/108i1mo/please_help_i_cant_save_my_file_as_psd/?utm_source=share&utm_medium=web2x&context=3)

**Comment by photopea** [comment]
If Photopea works differently in the Incognito mode than in a regular mode, it is definitely caused by your browser extensions.

It is up to you, do what you want, but if you use an extension to block file downloads, there is nothing we can do.
