### ISSUE TITLE
photopea did not save the latest version of the file + problem when exporting

### ISSUE THREAD

**Issue by camilessss** [photopea/photopea#5254]
I spent 4 hours editing a file and saving periodically, both spontaneously and with the help of reminder notifications to save after x hours of work. I tried exporting the file to PDF and Photopea completely stopped, and the Google notification ("this tab has stopped") appeared. I waited a while, he didn't come back; believing that I had saved the psd file just now, I closed everything. When I opened it again, I found that the file was in the first version, hours ago, although I saved several times after that.

**Comment by photopea** [comment]
I made a new document in Photopea and pressed File - Save as PSD. Then, I changed something, and pressed File - Save, and closed Photopea.com . Then, I opened Photopea.com and loaded the old PSD, it showed me the second (last) version.

What should I do to see a behaviour which you describe?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
