### ISSUE TITLE
When trying to apply outter glow, program behaves in a truly bizzar fashion

### ISSUE THREAD

**Issue by aknight2015** [photopea/photopea#5255]
I try to use a gradient for an outer glow on a folder, and it switches to gradient overlay. I try and apply directly to layer and the layer contents just vanish.
[Screencast from 01-11-2023 05:23:43 PM.webm](https://user-images.githubusercontent.com/47067592/211931366-555a0a4d-2ab4-4aea-9ee2-d3c1117283b7.webm)

**Comment by camoody1** [comment]
I would suggest Sharing your PSD project and dropping a link to it here so someone else can try to reproduce the issue on their end.

**Comment by aknight2015** [comment]
I'm not comfortable sharing my logo.

**Comment by camoody1** [comment]
> I'm not comfortable sharing my logo.

Understandable. Hopefully the developer can still help you out.

**Comment by aknight2015** [comment]
Thanks. Glad you understand. Took me quite a few years to design it.

**Comment by photopea** [comment]
I do not see any incorrect behaviour in your video. At one point, you have the "crosshair" there, and 0.1 seconds later, you have a layer with "200". 

I tried to apply an outer glow to a folder, with a Gradient, and it seems to work well. Please, tell me, what should I do to see anything wrong in Photopea.com

**Comment by aknight2015** [comment]
When I apply a gradient to a folder, works great. I tried to apply an outer glow to the folder and when I selected the gradient I wanted it deselected outer glow and went to gradient overlay and changed the gradient I had there.

**Comment by photopea** [comment]
Can you make a 30 second video of you opening www.Photopea.com and showing the problem? Without any cuts in the video?

**Comment by photopea** [comment]
But what exactly should be wrong in your video? The Layer Style window covers the graphics most of the time, so I can not see properly what happens.

**Comment by photopea** [comment]
I really need you to write me a step-by-step guide of what should I do to see a problem. Similar to this: https://github.com/photopea/photopea/issues/5188

I will close it now, but we can keep discussing it.

**Comment by aknight2015** [comment]
Well, I fire up Photopea, I open PSD from computer. I created a new folder for the 200 text. I applied a gradient overlay to the folder. Then it doesn't matter if I apply an outer glow to the folder or the text as it all has the same effect when I try to use a gradient. The outer glow is deselected, it selects the gradient overlay, and changes the gradient to the new gradient I selected to be the outer glow, but it is applied as a gradient overlay instead.

**Comment by photopea** [comment]
" when I try to use a gradient" - what do you mean by that? Do you mean using the Gradient tool in a toolbar?

BTW. are you familiar with Adobe Photoshop? Do you think what you do works differently in Photoshop?

**Comment by aknight2015** [comment]
A gradient via the effects options. Inner Glow, outer glow, gradient overlay. It's labeled as EFF in the layers panel.

**Comment by photopea** [comment]
Could you create a simple PSD with 1 or 2 layers, which demonstrates the problem? Then, press File - Share -PSD, and show us a link. Also, attach a screenshot in your comment, and draw the arrows as what you think is wrong in that PSD.

**Comment by aknight2015** [comment]
https://www.photopea.com/#it1EZB0dt.psd
![Screenshot from 2023-01-06 20-26-09](https://user-images.githubusercontent.com/47067592/212117878-9c8d1d06-9d15-4594-96d1-a2460fc2f588.png)
![Screenshot from 2023-01-12 11-00-36](https://user-images.githubusercontent.com/47067592/212117884-3f4658fe-d202-4ff7-987c-40334cc805d3.png)
![Screenshot from 2023-01-12 11-01-07](https://user-images.githubusercontent.com/47067592/212117888-2d94b4a0-2fba-4bc7-b7ee-89bac8eaa17a.png)
![Screenshot from 2023-01-12 11-01-23](https://user-images.githubusercontent.com/47067592/212117891-48cefb80-369b-4153-b31d-706bf546d368.png)
![Screenshot from 2023-01-12 11-01-35](https://user-images.githubusercontent.com/47067592/212117893-f1119b6d-002a-44cc-812a-b68ea89e8bd4.png)

**Comment by photopea** [comment]
In every screenshot, your image looks as it should (corresponds to the layer styles that you set). What exactly is wrong, in what screenshot?

Note, that in the last screenshot, it is a style gallery, not a gradient gallery. Choosing a different style can enable or disable certain effects.

**Comment by camoody1** [comment]
How did you end up on the Blending Options tab in the last photo?

**Comment by aknight2015** [comment]
All I did was select the layer, and select EFF in the layers panel.

**Comment by photopea** [comment]
I still think you dont understand how things work in Photopea, rather than there is an error in Photopea.

I dont understand what do you think is wrong with your screnshots, and what would you like to see instead, at what point.
