### ISSUE TITLE
[Feature request] - Lens Blur filter with an option to get depth map with AI help

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#5257]
Hi, 
some time ago I chatted with you about a few AI-based projects. One of them was https://huggingface.co/spaces/nielsr/dpt-depth-estimation for getting the AI-generated DOF black and white map.

![obraz](https://user-images.githubusercontent.com/38118273/211948489-9aea610c-d238-4b11-9c46-196618193ecc.png)

It is the same thing (I think so) that Adobe implemented into its Neural Filter (in the 24 CC version there is  a Depth Blur functionality)

![obraz](https://user-images.githubusercontent.com/38118273/211951654-68703b22-ec41-4376-bdd3-8a9ddba08683.png)

and it can create depth map too

![obraz](https://user-images.githubusercontent.com/38118273/211951740-20e0d686-5fbc-41c9-8aae-8aea922af9cf.png)

After inverting B&W it looks like this from DPT depth estimator 
![obraz](https://user-images.githubusercontent.com/38118273/211951849-efeb4c1e-d742-47db-8781-985387ceeb6d.png)

AND now going to the point of my request:

You have implemented some time ago Lens Blur filter (I asked for this and once again big thanks for that!).

What do you think about adding an option to the list of source of a Depth Map - "AI estimated DOF"?

![obraz](https://user-images.githubusercontent.com/38118273/211952951-35f0fbed-6331-46d2-92f3-56f89c0699db.png)

**Comment by photopea** [comment]
To estimate this depth, you need a program, that is 200 MB in size, to run on a $2000 GPU for 15 seconds. Adobe can pay for powerful servers, as they get $10 from each user every month, but we get only 0.03$ from each user every month (from ads), so we can not offer them such service.

What about a tool, which makes a depth map from two photos (taken from different locations, e.g. 2 - 10 cm from one another). This could run on your computer. Would you mind taking two photos for this purpose?

**Comment by MichalSZZ** [comment]
OK all of these arguments about money are 100% understandable to me. That was only an idea of a super useful thing (for me). I don't know what is easy to implement with low cost and what is hard to develop and expensive. Thanks for the answer! 
Maybe in the future, these services will be cheaper or Photopea will have its own cloud server for AI tools :)

About making 2 photos - I know how it works but almost nobody thinks about that when making a photo. That feature should be a rescue for photos without lens focus depth of view.
Or you are talking about something simple - for example I made a few photos by phone (without portrait mode) and each was made by hand (without tripod etc.). These pictures I add to Photopea as a series (something like stack photos, panorama maker) and It will generate black and white Depth Map. But all objects in the photo should be in the same place without any movement? That is the cons? Not for photos with pets, children, cars, sports etc.

Now people are making unnatural background blurs - because they don't know how to make manually the Depth Map.

**Comment by photopea** [comment]
If you have two photos of the same object, taken from different locations (e.g. 5 cm apart), you can reconstruct a 3D. That is how a self-driving car uses two cameras to create a 3D model of what is in front of it. Or how Microsoft Kinect works.
![image](https://repository-images.githubusercontent.com/249933849/83664700-dc1a-11ea-9cc2-ddd55048cd8c)

**Comment by photopea** [comment]
I decided not to implement it, as I think there is not enough people interested in this feature.
