### ISSUE TITLE
[Feature request] Malayalam font filter

### ISSUE THREAD

**Issue by zcraber** [photopea/photopea#5258]
Follow up of the [Reddit](https://www.reddit.com/r/photopea/comments/10a25eq/couldnt_find_a_font_from_google_fonts_in_photopea/?sort=new) thread. Certain Malayalam fonts from Google Fonts are not showing up in Photopea. A filter for the Malayalam language will hopefully fix the fetching issue. (?)

**Comment by photopea** [comment]
Hi, I have added the Malayalam font filter.
