### ISSUE TITLE
Editing in the text field not undo-able

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#526]
Why is the editing of text field not undo-able, I often accidentally replace it with a single character when selecting all to do something else, but this is not undo-able.

**Comment by photopea** [comment]
The main History in Photopea (Edit - Step Forward / Backward) maintains the text layer before entering it, and after escaping it (https://www.photopea.com/learn/text-layers) .

If you want to go forward / backward while the text layer is edited, you should be able to use Ctrl+Z and Ctrl+Y.

**Comment by hgs54371** [comment]
I've read that in photoshop, undo/redo(one step, same one key) is for quick a/b toggle comparison, step backward/forward(multi step, separate keys) is the "usual" undo/redo in most other apps.

But now in photopea, in text field, the undo can be used like "usual"(multi step), but the Ctrl+Y(cmd-y) is not working for redo multi steps.

**Comment by photopea** [comment]
I think this feature in Photopea works the same way as in Photoshop right now. Can you show us a PSD and steps, which we should do, to detect a different behavior?

I am not familiar with the Ctrl+Y shortcut (neither from Photopea, neither from Photoshop). What should it do?

**Comment by hgs54371** [comment]
Right now in text field, the text editing actions are undo-able with (cmd-z) for several steps, but has no way to reverse these undo steps(redo)(press cmd-y nothing hapens).

**Comment by photopea** [comment]
That is very strange. I can use Ctrl+Y while editing a text layer.

Can you go here: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_textarea  , get into the text area on the right, try typing and try using Ctrl + Z,  Ctrl + Y inside it. Does it work?

**Comment by hgs54371** [comment]
Ctrl + Z (cmd-z) worked
Ctrl + Y (cmd-y) do nothing
On firefox mac version

**Comment by photopea** [comment]
Then, I guess it is a bug in Firefox. Could you report it to Firefox developers?

**Comment by hgs54371** [comment]
In the browser's Edit menu there's only two, undo(cmd-z) and redo(shift-cmd-z), I just found it worked for redo in text field, but not for photopea's step forward/backward (both do nothing)
What's the relationship between browser's own shortcuts and photopea's shortcuts, are they inheritable or something

**Comment by photopea** [comment]
When you are inside a text fileld, it works as if you were in the Textarea. Step forward / backward only works with states before and after the confirmation

**Comment by hgs54371** [comment]
So now in text field I can use (cmd-z) and (shift-cmd-z) as defined by browser
But (alt/opt-cmd-z) and (shift-cmd-z) as defined in photopea both not responding for steps stored in the history panel

**Comment by photopea** [comment]
The standard Step Forward / Backward works only when you escape the text field.

**Comment by hgs54371** [comment]
Yes, I mean outside the text field

**Comment by photopea** [comment]
Do you mean this? https://github.com/photopea/photopea/issues/537  Lets discuss it there.
