### ISSUE TITLE
Layer not selecting

### ISSUE THREAD

**Issue by Rahulswitspl** [photopea/photopea#5260]
I am not able to select multiple layers in layer penal while selecting holding select or ctrl. non of these are working.

**Comment by photopea** [comment]
What makes you think that this is how you should select multiple layers? 

I recommend you to read this (since all features of Adobe Photoshop work the same in Photopea) https://helpx.adobe.com/photoshop/using/selecting-grouping-linking-layers.html#:~:text=To%20select%20multiple%20contiguous%20layers,them%20in%20the%20Layers%20panel.

**Comment by camoody1** [comment]
![Screenshot_20230113_061235_Chrome](https://user-images.githubusercontent.com/73725653/212307083-360b974b-4905-4511-942e-8b1be8fd8e34.png)

**Comment by photopea** [comment]
Yes, that should work. It says "in the Layers panel", not on the canvas. Doesnt it work for you?

**Comment by camoody1** [comment]
This person opened two separate threads on Reddit yesterday asking this same question. It's been explained to him multiple times by myself and a couple others. He wants to move a multiple layers around on the canvas using the Select/Move Tool. I tried to explain how to use the CTRL key to select multiple layers in the layers panel, and then once these are selected, he can move those layers around at the same time. At one point, he has "Auto-Select" enabled for the Select/Move Tool and I had him disable that. He still claims that it's not working for him. I really don't know how else to explain it to him. My step my step instructions work fine for me. Perhaps he's just doing something weird that I'm not aware of or maybe he has a broken CTRL key. I don't know.

**Comment by photopea** [comment]
It is all explained in the link that I send. Because of typos, I think he is 11 years old and he hates reading.
