### ISSUE TITLE
When i try to scale my image out, the image goes black

### ISSUE THREAD

**Issue by Jykie** [photopea/photopea#5262]
Hello, everytime i use the transform tool to make my images bigger, the image go black. And then when i scale it back to it's original size, it becomes normal. It does this in all my project files on photopea. 

Here is the link to the screen recording I uploaded to YT showcasing the issue:
Video: https://youtu.be/bGhZmGjHkww

**Comment by camoody1** [comment]
This looks like it could be a graphics driver issue or a video memory issue. But I'm just guessing. Are you using a Chromebook?

**Comment by Jykie** [comment]
> 
I have a Samsung galaxy tab s7

**Comment by photopea** [comment]
When you scale it, your layer is 5052 x 1916 pixels (10 million pixels). It is probably the limit of the texture size of your GPU, which is probably 4096 pixels. Every device has this limit, e.g. it is 16,384 pixels on my laptop. You can check yours at https://webglreport.com/

You can disable WebGL (press More - use WebGL), or work with a smaller document and layers, where no size ever exceeds 4096. Photopea disables WebGL automatically when your document is larger than the limit.
