### ISSUE TITLE
CANT CLOSE THE COLOR PICKER WINDOW

### ISSUE THREAD

**Issue by sz333** [photopea/photopea#5264]
ive had to restart multiple projects because of this issue on this website. doesnt matter what browser or computer i use. the button highlights when i click it but it wont close!!!

https://user-images.githubusercontent.com/122643188/212408808-afc220f4-2613-4d62-8bab-dd5f54ce1d52.mov

**Comment by photopea** [comment]
Hi, how can I make it happen? What should I do after opening www.Photopea.com to see such behaviour?

**Comment by sz333** [comment]
i was changing the outer glow of the text in blender options, nothing fancy

**Comment by photopea** [comment]
I am trying to edit the color of the outer glow, but I can always close the color picker :(

Could you try it yourself again and maybe find a combination of operations, which leads to the problem?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
