### ISSUE TITLE
Unable to open specific ANIM IFF files in Photopea

### ISSUE THREAD

**Issue by blenderbach** [photopea/photopea#5265]
When attempting to open certain ANIM IFF files in Photopea, the frames are either pure white (Falling Sheep.anim) or black (Phone.anim) and the data is completely lost. Some ANIM IFFs also have the black frames however, these ones sometimes contain the data if you bring the brightness up in post (Organic Wiper.anim). However, usually these specific ANIM IFFs are unable to be opened at all and simply produce a Photopea error (SkyLine.anim). I have provided the four (anim) files here. Good Luck! :-D
[ProblematicANIMs.zip](https://github.com/photopea/photopea/files/10415672/ProblematicANIMs.zip)

**Comment by photopea** [comment]
Can you show me how these files, or at least one file, should look like? What colors should it have?

**Comment by photopea** [comment]
Your files have strange palettes, e.g. all black colors in a palette. I tried to detect it, and set the palette to shades of gray. Your images should work, except of "SkyLine.anim", which has a totally different compression, that is hard to implement.

**Comment by blenderbach** [comment]
> Can you show me how these files, or at least one file, should look like? What colors should it have?

I'm not exactly sure, as I cannot open them, but for example, one of the pure black ones that doesn't show up when brightening it, when running it in VideoToaster, it does display the preview, like the "Dance Party" one... The "SkyLine" comes out strange looking even when running through VideoToaster. I have provided the Dance Party and SkyLine GIFs, along with the Dance Party anim file. 
![ezgif com-gif-maker (51)](https://user-images.githubusercontent.com/87039308/212500367-8083dfea-05e7-4fa3-a2fc-ccdbdd3ce6b8.gif)
![skylinetoastercapturetest0001-0390 (1)](https://user-images.githubusercontent.com/87039308/212500432-d1ebca64-a029-4ef0-8534-eb9ad0149163.gif)
[UnusableANIMDanceParty.zip](https://github.com/photopea/photopea/files/10419020/UnusableANIMDanceParty.zip)

**Comment by blenderbach** [comment]
> Your files have strange palettes, e.g. all black colors in a palette. I tried to detect it, and set the palette to shades of gray. Your images should work, except of "SkyLine.anim", which has a totally different compression, that is hard to implement.

I didn't make these ANIM files. They are from the Open Source Amiga software, "VideoToaster". :-D

**Comment by blenderbach** [comment]
Oh my goodness!!! Most of the broken ones now actually work! Thanks! :-D
How in the seven seas did you even figure this out? 🥇

**Comment by blenderbach** [comment]
I could provide the source code of the program, which might help. 
https://www.discreetfx.com/DownloadFlyer.html
Inside the ZIP file is a folder called "switcher" and in there is a "SRC" folder. Inside there is a "animfxhandler.a" file, which, if I understand correctly, is the code responsible for running these ANIM files.
Hopefully this helps! :-D

**Comment by photopea** [comment]
I am afraid it will not help me. It would still take me hours to come up with a fix.

If there exists a program which can open your files, use it to convert them to GIF as soon as possible. It is a real "vulnerability" to keep an important work in such rare formats.

**Comment by blenderbach** [comment]
> I am afraid it will not help me. It would still take me hours to come up with a fix.
> 
> If there exists a program which can open your files, use it to convert them to GIF as soon as possible. It is a real "vulnerability" to keep an important work in such rare formats.

Alrighty! Thanks for the information! At least what you managed to do, is already a miracle! Thanks for the added compatibilities! :-D
