### ISSUE TITLE
Feature request: Revamp the configuration of animation frames

### ISSUE THREAD

**Issue by cow1337killer3** [photopea/photopea#5268]
Decouple frame configuration from layer titles by making right-click menu options. This will make the configuration more intuitive and also allow us to change configuration values for multiple layers at a time... currently, for example, when you want to change the frame duration of multiple frames, you have to edit the title of every individual layer which is very tedious.

1. Instead of prepending layer titles with "\_a\_", affix a small play button icon (▶) before the title. Add the following right-click menu options to layers that will toggle them between being a frame layer and a static (normal) layer: "Convert to Frame Layer" and "Convert to Static Layer".
2. Instead of appending layer titles with ",xxx", affix the frame duration after the previously mentioned play button icon (▶) and before the layer title. Make it in a smaller and lighter-colored font to distinguish that it's not part of the layer title. Add a right-click menu option to frame layers, "Change Frame Duration", which brings up a small window. In this window, have a textfield labeled "Frame Duration (ms):". To the right of the textfield, have a dropdown menu with options "Each", "Total (Uniform)", and "Total (Scaled)". 
  a. The "Each" option will set every selected frame layer's duration to the value in the textfield. 
  b. The "Total (Uniform)" option will change the summed/total duration of all selected frame layers, by dividing the value in the textfield by the number of frame layers selected. The resulting duration of each frame layer will be floor()-ed, and then the remaining duration needed to reach the total will be distributed to the frames in an even/sparse manner (**with 5 frame layers selected and a value of 13ms entered, the durations of the frames will be as follows: [3, 2, 3, 2, 3]**). 
  c. The "Total (Scaled)" option will change the summed/total duration of all selected frame layers in proportion to their existing durations. This is done by finding the current total duration of all selected frame layers, finding the percent that each frame layer comprises of the total, and multiplying that percent by the new total to get the new duration of each frame layer. Evenly distributing the remaining duration needed to reach the total is a little more complicated in this case, but something similar to the method mentioned previously might work. **With 5 frame layers selected that have current durations of [100, 500, 200, 400, 300] and current total of 1500, entering a new total of 3000 will result in new durations of [200, 1000, 400, 800, 600]**.
3. For parallel animations, instead of having to merge the frames of multiple animations into a new set of layers, allow every separate folder containing frame layers to be treated as a separate/parallel animation that will run concurrently with other folders. When a folder contains both frame layers and another nested folder also containing frame layers, the top-level frame layers will be treated as an animation, and the ones in the nested folder will be treated as a separate parallel animation. This would be a much better choice than having to merge frames

**Comment by photopea** [comment]
I think there are not so many people making animations, so I would rather hide all features into the Layer - Animations menu. A PSD from Photopea should still be compatible with every software which opens PSD files.

I think we should implement the Animation window instead of making the UI for the current animation mechanism: https://github.com/photopea/photopea/issues/4166
