### ISSUE TITLE
After pressing middle mouse button, the cursors gets stuck on movement wheel.

### ISSUE THREAD

**Issue by crapvile** [photopea/photopea#5270]

**Comment by photopea** [comment]
what are "the cursors" and the "movement wheel"?

**Comment by crapvile** [comment]
*Cursor, and the movement wheel you get after pressing the middle mouse button so you can move around the image. After I click it, it doesn't go away until I open a new tab. Refresh doesn't fix it.

**Comment by photopea** [comment]
When I press the middle mouse button in Photopea, it activates the hand tool and grabs the document, I can move it around. When I release that button, everything returns back to as it was (the document stays moved).

It sounds like it works differently in your case. Could you reset your mouse to some default settings?

**Comment by crapvile** [comment]
I looked into it and I fixed it, it was an extension I had called "Modern scrollbar" which conflicted with it. Thanks for help.
https://chrome.google.com/webstore/detail/modern-scrollbar/bgfofngpplpmpijncjegfdgilpgamhdk/related?hl=en

**Comment by photopea** [comment]
ok
