### ISSUE TITLE
Clipboard Movement Bug

### ISSUE THREAD

**Issue by CxryzNFTs** [photopea/photopea#5271]
There is a bug with pasting an image from your clipboard into Photopea, or when you press the shortcut "Search + V" on a Chromebook. 

When you press this shortcut, all canvas movements are inverted. When I try to move to the left on the canvas, it moves up, when I try moving to the right, the canvas moves down. Please fix this annoying bug, it's really interfering with my workflow. Thank you.

**Comment by photopea** [comment]
Could you try this first? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

Also, could you try to paste with Edit - Paste, or Ctrl+V ? I have never heard of "Search+V".

**Comment by CxryzNFTs** [comment]
Yeah I use a chromebook, that's how I access clipboard history.

**Comment by photopea** [comment]
Sorry, I dont have a chromebook to check it myself :( But did you try Ctrl+V or Edit - Paste?

**Comment by photopea** [comment]
I have to close it because of lack of details.
