### ISSUE TITLE
Javascript bug #4

### ISSUE THREAD

**Issue by PoweredByAndrox** [photopea/photopea#5275]
Hello, i tried my WORKING script and it doesn't work now...

Here's the sample where has bug:
```js
function ObjectPresent(source, object)
{
	if (source == undefined || object == undefined)
	{
		return false;
	}
	return source.hasOwnProperty(object.toString());
}

var MainData = {"type_random_fin_trans_dasdasda":{"only_plus":false,"only_minus":true}};

alert("test: " + (ObjectPresent(MainData, "type_random_fin_trans") && (MainData.type_random_fin_trans != undefined && !MainData.type_random_fin_trans.only_plus && !MainData.type_random_fin_trans.only_minus)));
```
Error log:
![image](https://user-images.githubusercontent.com/38520826/212670015-a994a393-5b13-4cfe-8536-6201cd6c06b4.png)

Can you update your code to show where's the error came? I mean a number line where's an error

**Comment by photopea** [comment]
Thanks for reporting! It should be fixed now.
