### ISSUE TITLE
Cannot open an image from pc using photopea

### ISSUE THREAD

**Issue by KevinEleven112** [photopea/photopea#5276]
ive tried open and copy and paste yet none of them work, my classmate also has the same issue
Thank you

**Comment by photopea** [comment]
Hi, are you using Photopea at www.Photopea.com ?

**Comment by KevinEleven112** [comment]
Yes ive used photopea at http://www.photopea.com and ive tried rebooting my machine

**Comment by photopea** [comment]
Try this then: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/
