### ISSUE TITLE
Files Won't Open in Photopea.com

### ISSUE THREAD

**Issue by SubBass49** [photopea/photopea#5277]
I keep getting a pop-up window that says "can't open files from this folder because it contains system files" even though the folders I'm trying to open files from DO NOT contain system files. I even tried creating a new folder with only one file in it, and the same message appears.

I worry that this will make Photopea un-usable for my students this upcoming semester.

Is this a new bug in Photopea? A result of newly-applied security settings, perhaps? Any suggestions or workarounds are appreciated.

Running Photopea.com on Chrome Browser Version 109.0.5414.75 (Official Build) (64-bit)

**Comment by photopea** [comment]
How do you open files? Are you clicking File - Open? Or you drag-and-drop a file into Photopea.com ?

**Comment by SubBass49** [comment]
I tried both methods and got the same result. Appears to be a Chrome issue, as the problem doesn't show up when I switch over to Firefox browser.My worry is that my students are issued Chromebooks, and I am not sure if they can access Firefox browser or if they are stuck with Chrome.Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Photopea ***@***.***> Date: 1/16/23  4:06 PM  (GMT-08:00) To: photopea/photopea ***@***.***> Cc: SubBass49 ***@***.***>, Author ***@***.***> Subject: Re: [photopea/photopea] Files Won't Open in Photopea.com (Issue
  #5277) 
How do you open files? Are you clicking File - Open? Or you drag-and-drop a file into Photopea.com ?

**Comment by photopea** [comment]
There was a similar problem here: https://github.com/photopea/photopea/issues/5261

Could you also try it in the incognito mode, or with all your browser extensions disabled?

@tomayac so can be restrictions even for the window["showOpenFilePicker"] ? 

In my case (Chrome on Windows 10), showOpenFilePicker() can open Documents and Desktop, but can not open C:/Program Files. However, <input type="file"> can open everything including C:/Program Files.

**Comment by photopea** [comment]
There was a similar problem here: https://github.com/photopea/photopea/issues/5261 

Could you also try it in the incognito mode, or with all your browser extensions disabled? Also, have you tried to open files from different folders (as it says you have system files in that folder)?

@tomayac so can there be restrictions even for the window["showOpenFilePicker"] ? 

In my case (Chrome on Windows 10), showOpenFilePicker() can open Documents and Desktop, but can not open C:/Program Files. However, \<input type="file"\> can open everything including C:/Program Files.

**Comment by tomayac** [comment]
`<input type=file>` is less powerful than `showOpenFilePicker()` or `showOpenDirectoryPicker()` since with the former you cannot write back into the file/folder, but with the latter you can.

**Comment by photopea** [comment]
@SubBass49 could you tell us, what folder in your device were you trying to open?

**Comment by SubBass49** [comment]
I attempted this with files from my downloads folder and from one other just to check.Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Photopea ***@***.***> Date: 1/17/23  2:20 AM  (GMT-08:00) To: photopea/photopea ***@***.***> Cc: SubBass49 ***@***.***>, Mention ***@***.***> Subject: Re: [photopea/photopea] Files Won't Open in Photopea.com (Issue
  #5277) 
@SubBass49 could you tell us, what folder in your device were you trying to open?

**Comment by photopea** [comment]
@tomayac is it possible that showOpenFilePicker() does not load from the Downloads folder? Because it works for me with the Downloads on Windows 10.

**Comment by tomayac** [comment]
It also works for me. My suspicion is that the original poster runs into some issues with how the home drives are mapped in their education environment.

**Comment by photopea** [comment]
@SubBass49 What operating system and what web browser do you use? Did you try to use Photopea in the incognito mode?

**Comment by SubBass49** [comment]
Tried on a desktop PC at work this morning, and the problem doesn't replicate. Both the laptop and the PC run Windows 10. The Chrome browser on the desktop is version 108.0.5359.125 and the laptop version is 109.0.5414.75Incognito work-around doesn't appear to get it done, either. Will see if students are able to use on their Chromebooks once they show up.For personal stuff, the Firefox work-around seems to be my best bet, but for functionality going forward and for my students sake, I sure hope this gets patched somehow.Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Photopea ***@***.***> Date: 1/17/23  6:21 AM  (GMT-08:00) To: photopea/photopea ***@***.***> Cc: SubBass49 ***@***.***>, Mention ***@***.***> Subject: Re: [photopea/photopea] Files Won't Open in Photopea.com (Issue
  #5277) 
@SubBass49 What operating system and what web browser do you use? Did you try to use Photopea in the incognito mode?

**Comment by prasiddharaj** [comment]
Hi,

I am facing the same issue on Chrome/Edge version 109

Any resolutions yet?

**Comment by photopea** [comment]
I have stopped using the file-system-access API. It should work now. Could you check, if opening files works? And if you can save them?

**Comment by SubBass49** [comment]
It appears that you have solved the issue! Whatever you did has the whole thing working again! Thank you so much! Cheers!Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Photopea ***@***.***> Date: 1/17/23  11:15 PM  (GMT-08:00) To: photopea/photopea ***@***.***> Cc: SubBass49 ***@***.***>, Mention ***@***.***> Subject: Re: [photopea/photopea] Files Won't Open in Photopea.com (Issue
  #5277) 
I have stopped using the file-system-access API. It should work now. Could you check, if opening files works? And if you can save them?

**Comment by photopea** [comment]
great!
