### ISSUE TITLE
Feature Request: New Option to Export Selected Brushes

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5278]
Current option in Photoshop
![brushes-not-showing-up-2](https://user-images.githubusercontent.com/73725653/212795513-34036606-742b-4a29-b761-8506b0c0f54d.jpg)

Being able to export selected brushes would allow a user to create his/her own custom brushes, export just those brushes to an ABR file, and then reimport them to Local Storage so they are available every time Photopea is reopened.

Additionally, this option would allow the user to create his/her own "favorite groups" of brushes. The user could select all the individual brushes they like as favorites, export them into a single ABR file, and then reimport them into Local Storage. With your new grouping feature, these brushes would append to the end of the brush list in their own group. This functionality would be great not just for favorites, but for grouping similar brushes from multiple files that you've imported. A user could import a file that has 20 brushes, select the one or two they actually want, export them into their own file, and delete all the other unwanted brushes.

**Comment by photopea** [comment]
It is already possible in Phtopea since 2016, have you tried it?
![image](https://user-images.githubusercontent.com/15955558/212840962-da1cfbd1-17ef-4163-a40a-0fa1c88ba074.png)

**Comment by camoody1** [comment]
I tried this before I submitted this request and it looked like it exported all the brushes instead of just the one I selected. In my test, I created a simple 15x15px square brush with the Define New Brush Tool. Then, I selected just that one brush from the brush list, chose to "Export as .ABR", and a 44MB file was downloaded. Now, perhaps my estimate is a bit low, but I can't imagine a single 15x15px brush being 44MB in size.🤷🏽‍♂️

**Comment by camoody1** [comment]
Actually, I just tried it again, and with your new "group" names, I can see that only that one brush WAS exported. That file size blows my mind for such a small brush!

Would it be possible to change that menu item to read "Export Selected Brushes as .ABR"? That might make it more clear for future users.

**Comment by camoody1** [comment]
Wow. I just created two similarly small brushes and exported those two. The exported file was 88MB in size. Is that normal? Does loading those brushes at startup of Photopea just eat up all my memory?

**Comment by photopea** [comment]
Yes, that is a bug, I am aware of it.

**Comment by photopea** [comment]
I will fix it today.

**Comment by photopea** [comment]
It should be fixed now. ABR files should be much smaller.
