### ISSUE TITLE
NS_ERROR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by PoweredByAndrox** [photopea/photopea#5279]
Yesterday photopea worked but now Firefox says it:
![image](https://user-images.githubusercontent.com/38520826/212857070-80825b21-82d0-447d-bfee-529eba19e1da.png)

What will need to do?

**Comment by photopea** [comment]
So I open https://www.photopea.com/api/playground in Firefox, and I see this. What should I do to see a problem that you describe?
![image (1)](https://user-images.githubusercontent.com/15955558/212872188-9c223bb9-deac-47f6-8c1f-1e583f182346.png)

**Comment by PoweredByAndrox** [comment]
I do it from the selenium nodejs (Webdriver) or how can i handle the web frame where works photopea on my linux server?

**Comment by PoweredByAndrox** [comment]
Hm, now it works... what was that i don't know!

**Comment by photopea** [comment]
Maybe you are using browser extensions, which often break the functionality of Photopea. So everything works as you want now?

**Comment by PoweredByAndrox** [comment]
"Maybe you are using browser extensions, which often break the functionality of Photopea" - No. The selenium creates a new browser profile.
I see my code broken (that bug with "Cannot read properties of undefined (reading 'T')" returns) xD

**Comment by photopea** [comment]
Please, if you think you have found a bug in Photopea, tell me exact steps, what should I do to replicate the bug.
