### ISSUE TITLE
scroll while selecting, to select more than fits in the screen

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#528]
when you have a big canvas (not fitting in one screen) and you want to select a part of it, which part spans more than one screen as well, in PS etc you can move mouse outside of the canvas (while still holding the button), this starts scrolling = panning (not too fast, not too slow), so that you can select more than fits into the screen.

**Comment by ewnjtgouierg** [comment]
when there's no such option, you have no choice but to try to zoom out and select, but this is very difficult b/c you might hardly be able where you need to start selecting etc in such zoom, or probably even impossible, because at that zoom Photopea can stick your selection to some nearby edge

**Comment by photopea** [comment]
It was implemented!   I think it is a really great feature. Thanks for suggesting it! :)

**Comment by ewnjtgouierg** [comment]
sorry for late comment
apparently there's a critical issue with the scroll speed

if zoom level is high enough, the speed of the scrolling will be unbearably slow (if you zoom in to precisely set the starting corner of the selection, and then you want to select the area that is full canvas high, for example)

I'm not sure yet how it is resolved in ps and other apps that have this feature, and can't check how it works there right now, sorry

most efficient would be, when mouse moves outside, to not just trigger uniform motion, but transpose mouse motion onto the panning. then, if you move mouse to the greater distance, you can pan further, and quickly

but it's probably not possible today in web apps, right?

not sure if that makes sense then to try to just make scroll speed proportional to zoom level - i'm afraid, this will make it harder to stop exactly where you want
