### ISSUE TITLE
Certain Specific ILBM/LBM/IFF InterLeaved BitMap images don't open correctly in Photopea, and also have no blue channel.

### ISSUE THREAD

**Issue by blenderbach** [photopea/photopea#5280]
When trying to open certain IFF Images, Photopea opens them wrong, and they are all in shades of yellow, and no blue channel is even extracted. When looking at the channels in Photopea, the blue channel is pure black. I will provide the image data, and how it should look like. Good Luck! :-D

![image](https://user-images.githubusercontent.com/87039308/212858574-a693a5f2-8c74-4ec5-b8e8-1d62afdac762.png)

[ScienceFact.zip](https://github.com/photopea/photopea/files/10433331/ScienceFact.zip)

**Comment by photopea** [comment]
Could you share a PNG of how exactly it should look like, rathrer than a screenshot? Could you share more images like this, maybe with photographs of a real scene?

**Comment by photopea** [comment]
I fixed it a bit, but there is a weird grid of 2x2 pixels.

**Comment by blenderbach** [comment]
> Could you share a PNG of how exactly it should look like, rathrer than a screenshot? Could you share more images like this, maybe with photographs of a real scene?

This is how the original looks like. 
![image](https://user-images.githubusercontent.com/87039308/213249049-0d19bf0d-3958-474d-a685-b21ca740a10b.png)

So far, this is a very great improvement! Amazing! :-D

I could give some more examples, which may help. I put three files here."VTFlyer.iff" for gradients testing, "MissionBGBars.iff" for color calibration so the colors will be decoded correctly, and "BackDrop3.iff" which is almost like a real photograph with a chessboard. All images here are the original PNGs. No screenshots of any kind. Good luck! :-D 👍 

VTFlyer.iff 
![image](https://user-images.githubusercontent.com/87039308/213249547-449ae5a1-2d41-4530-b280-50cd0f913b94.png)

MissionBGBars.iff
![image](https://user-images.githubusercontent.com/87039308/213249823-57e12aca-9a73-4060-a496-d47e2b468753.png)

BackDrop3.iff
![image](https://user-images.githubusercontent.com/87039308/213251174-3b2864db-38ad-4a49-989f-15154956aaf2.png)

[Photopea.zip](https://github.com/photopea/photopea/files/10448964/Photopea.zip)

**Comment by blenderbach** [comment]
> I fixed it a bit, but there is a weird grid of 2x2 pixels.

So far, I am amazed. This is a major leap in improvement. :-D Congratulations! 🥇

**Comment by photopea** [comment]
What program do you use to open these ILBM files? Can they be opened in more than one program?

**Comment by blenderbach** [comment]
> What program do you use to open these ILBM files? Can they be opened in more than one program?

ToasterPaint. The OpenSource Amiga Paint program from Video Toaster.
https://www.discreetfx.com/downloadtoasterpaint.html

**Comment by photopea** [comment]
@wiesmann could you help us? I could pay you $200 for implementing it into your library.

Otherwise, I have to give it up. There is not enough interest in this feature from other users. No "regular" editor can open them.

**Comment by wiesmann** [comment]
Hi, This ILBM project is a hobby for me. You certainly send me the problematic files and I can have a look when I have time (which won’t have before a few months) I give no guarantees and payments is out of questions. CheersMatthiasOn 19 Jan 2023, at 16:36, Photopea ***@***.***> wrote:﻿
@wiesmann could you help us? I could pay you $200 for implementing it into your library.
Otherwise, I have to give it up. There is not enough interest in this feature from other users. No "regular" editor can open them.

**Comment by photopea** [comment]
@wiesmann I was really excited about your project! However, this ILBM file seems like it is not described by any ILBM specification.
