### ISSUE TITLE
Not able to Save (CTRL+S)

### ISSUE THREAD

**Issue by cyclops365** [photopea/photopea#5283]
The Save function on the drop down menu is greyed out.

**Comment by camoody1** [comment]
> The Save function on the drop down menu is greyed out.

You need to do a "Save as" or "Save More" first. After that, the "Save" option will be available.

**Comment by photopea** [comment]
Chrome used to allow websites to write files directly to your hard drive (without any confirmation in between). But it caused a lot of problems - see https://github.com/WICG/file-system-access/issues/401 , so we stopped using it.

Use the File - Save as PSD to save a PSD (with a standard download procedure of your web browser).
