### ISSUE TITLE
Save Ctrl + S doesn't work anymore

### ISSUE THREAD

**Issue by raabe-ctrl** [photopea/photopea#5284]
![Captura de tela 2023-01-18 093131](https://user-images.githubusercontent.com/91345712/213172336-b4636db3-879f-4ac4-b2e4-ac5bc53c719b.png)
this save button used to work... if I opened a file and make changes, I could press Ctrl + S and the file would be automatically saved. Now it doesn't work anymore, I have to save a new file and replace the file I had before. Please, could you take that function back? (Also I tried the same thing in 2 browsers, the problem is still there)

**Comment by raabe-ctrl** [comment]
heyyyy it came back to work. Kind of. Now it will only work if I first save a new file, replacing the previous, and THEN ctrl s will work with this new file. Anyway thank you Photopea is an amazing site and almost everyday I see new things and new layout... its getting more and more awesome, thank youuuuuuuuuuuuu

**Comment by photopea** [comment]
Chrome used to allow websites to write files directly to your hard drive (without any confirmation in between). But it caused a lot of problems - see https://github.com/WICG/file-system-access/issues/401 , so we decided to disable it for everyone.

Use the File - Save as PSD to save a PSD (with a standard download procedure of your web browser).
