### ISSUE TITLE
Bug: Missing "Close" Button on Plugins Window

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5285]
After opening the Plugins window on my Android phone, there is no "X" (Close) button on the top right corner of the window. The Plugins window is impossible to close in the vertical format. In order close the window, I have to rotate the phone into horizontal format and click just barely outside the top right corner where the "X" (Close) button should be. This actually allows me to close the window, even though the Close button is missing.
![Screenshot_20230118_211356_Chrome](https://user-images.githubusercontent.com/73725653/213340318-8acb868b-ce77-45b4-986a-971b50c63b97.png)
![Screenshot_20230118_211420_Chrome](https://user-images.githubusercontent.com/73725653/213340322-00939e8c-dbcb-4dbe-b539-f540565fc1cf.png)

**Comment by photopea** [comment]
fixed!

**Comment by camoody1** [comment]
Awesome change. I like how you redesigned to tool bar.

Thank you, sir!
