### ISSUE TITLE
Actions not working

### ISSUE THREAD

**Issue by ontrendllc** [photopea/photopea#5287]
I have uploaded a new action.  When I click on it and hit play it does nothing at all.  I am switching from photoshop to here so not sure if im missing something.

**Comment by photopea** [comment]
Hi, could you attach your action here (e.g. in a ZIP file)? Actions often need a specific structure of a document (you might need to have layers with specific names, etc).

**Comment by ontrendllc** [comment]
Yes, thank you so much!

[White Layers - NEW.zip](https://github.com/photopea/photopea/files/10468781/White.Layers.-.NEW.zip)

**Comment by photopea** [comment]
Your actions have a step of converting a document into a Lab color mode. However, Photopea can not represent images in a Lab mode at the moment. So your actions can not be executed at the moment :(
