### ISSUE TITLE
File > Save (Smart Object) - Not working

### ISSUE THREAD

**Issue by LiteFaux** [photopea/photopea#5288]
Hello! I have been working with some files for a time now in PhotoPea, exporting them on a daily basis, but today something strange happened. When I try saving a Smart Object that I have updated with new graphics nothing happens, it doesn't respond to Ctrl + S or the File > Save (Smart Object) direct menu click function.  I reckon something went astray, but I haven't changed anything in the file except new smart objects. I have tried using older files and nothing happens. 

I can provide the file and the way I am trying to update the smart object. It's somewhat confidential for me so that's why I am not posting it straight away here.

**Comment by camoody1** [comment]
If you don't want to share the file immediately, you could instead start by recording a short video of you performing these actions and their results.

**Comment by LiteFaux** [comment]
Here is a video demo of what happens:

https://user-images.githubusercontent.com/123154018/213704904-2baf5d27-a6bf-4554-b8aa-5d923903f6de.mp4

I am clicking File > Save (Smart Object) & I am tryin the hotkey combination of Ctrl + S.

**Comment by LiteFaux** [comment]
Tested in Incognito (Chrome), same issue. Tested in Edge - still there. Tested another random file - works fine. 

From what I gather it's a file issue, but I can't fathom what is causing it. I can provide the developer with the original file to try and figure this one out.

**Comment by photopea** [comment]
Hi, could you send me your PSD file to support@photopea.com ?

**Comment by LiteFaux** [comment]
> Hi, could you send me your PSD file to [support@photopea.com](mailto:support@photopea.com) ?

Emailed, thank you!

**Comment by photopea** [comment]
I am very sorry, there really was a bug, it is fixed now.

**Comment by LiteFaux** [comment]
> I am very sorry, there really was a bug, it is fixed now.

Yes, seems to be working fine now. Thank you very much for the quick response and solution delivery!
