### ISSUE TITLE
it is impossibile to use the program online

### ISSUE THREAD

**Issue by Photopea5964** [photopea/photopea#5289]
I tryed severaltimes to use properly Photopea but it is impossible. For exampleto doe a batch process with several images. Or reduce ad image for the web.  Can you do sometihing for best results? Thank'you

**Comment by Photopea5964** [comment]
thank'you for your jobs. I home the program will be better in the future.

**Comment by camoody1** [comment]
> thank'you for your jobs. I home the program will be better in the future.

😂

**Comment by Photopea5964** [comment]
I Hope..... dear camoody1 - T9 is a tragedy. ;O)))))))))))

**Comment by photopea** [comment]
Hi, how can I help you? Could you please writeh a proper question?

**Comment by Photopea5964** [comment]
Yes thank you. The problem is that I can't compress multiple images in batch. When I go to locate the PHotopea folder then it crashes not allowing me to perform the operation. How should I proceed if I want to compress a batch of images in one operation?

**Comment by photopea** [comment]
Are you using File - Automate - Batch? Could you record a short video of the problem?

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by Photopea5964** [comment]
Ok. I have continued with  Photoshop at home. Not problem. I think the programm sometimes  suffers  of bugs.  But maybe it dipends from the connection. . Inviato da iPhoneIl giorno 1 feb 2023, alle ore 23:11, Photopea ***@***.***> ha scritto:﻿
I have to close it because of lack of details.
