### ISSUE TITLE
shouldn't selection outside of the canvas be ignored?

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#529]
in PS, when you want to select, say, upper half of the canvas, you "draw" - with selection tool - a rectangle, whose left, top and right edges are ANYWHERE outside of the canvas, and the bottom edge is where you need to "slice" the image in half. This way you don't need to concentrate and be precise about anything but the arbitrary bottom edge. What you "selected" outside of the canvas is ignored and selection automatically limited by the edges of the canvas.

In Photopea - unless I missed something - if you select extra area outside of the canvas, it is included in the selection, moreover, after you, for example, crop to this selection, your canvas takes in that outer space, now comprising some blank area

I'm not sure if there're some use cases for such behavior, but I believe that the PS behavior is much more useful in majority of the cases

Again, I suspect that I miss some switches etc - sorry if so

**Comment by photopea** [comment]
Fixed. Note, that this is related only to Rectangle select. I.e. not Ellipse select or Lassos.
