### ISSUE TITLE
"Can't open files in this location because it contains system files" -- THIS HAS NEVER BEEN AN ISSUE BEFORE.

### ISSUE THREAD

**Issue by lakelands** [photopea/photopea#5292]
"Can't open files in this location because it contains system files" -- THIS HAS NEVER BEEN AN ISSUE BEFORE.

![photopea error](https://user-images.githubusercontent.com/123207195/213798210-db57eaf8-b53d-4495-8a84-4e83cb6f81a0.jpg)
tion because it contains system files" -- THIS HAS NEVER BEEN AN ISSUE BEFORE.

**Comment by camoody1** [comment]
Reference issue #5282 or [this](https://www.reddit.com/r/photopea/comments/10g6x4w/unable_to_open_files/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button) Reddit post for more information.

**Comment by photopea** [comment]
It is because the latest version of Chrome and Edge works differently than before. Switch to the older version of Chrome / Edge, or use Firefox.

**Comment by lakelands** [comment]
No....we can't.  We are a school system with system-wide updates.  We can't just move from one browser to another.  YOU need to fix this issue.  Please let me know when this issue is fixed.


Jason Lubin

Lakelands Park Middle School

Digital Art / Grades 6-7-8

Webmaster



________________________________
From: Photopea ***@***.***>
Sent: Saturday, January 21, 2023 6:06 AM
To: photopea/photopea ***@***.***>
Cc: Lubin, Jason D ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [photopea/photopea] "Can't open files in this location because it contains system files" -- THIS HAS NEVER BEEN AN ISSUE BEFORE. (Issue #5292)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



It is because the latest version of Chrome and Edge works differently than before. Switch to the older version of Chrome / Edge, or use Firefox.

**Comment by camoody1** [comment]
> No....we can't. We are a school system with system-wide updates. We can't just move from one browser to another. YOU need to fix this issue. Please let me know when this issue is fixed. Jason Lubin Lakelands Park Middle School Digital Art / Grades 6-7-8 Webmaster
> […](#)
> ________________________________ From: Photopea ***@***.***> Sent: Saturday, January 21, 2023 6:06 AM To: photopea/photopea ***@***.***> Cc: Lubin, Jason D ***@***.***>; Author ***@***.***> Subject: [EXTERNAL] Re: [photopea/photopea] "Can't open files in this location because it contains system files" -- THIS HAS NEVER BEEN AN ISSUE BEFORE. (Issue #5292) CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe. It is because the latest version of Chrome and Edge works differently than before. Switch to the older version of Chrome / Edge, or use Firefox. — Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fphotopea%2Fphotopea%2Fissues%2F5292%23issuecomment-1399229838&data=05%7C01%7CJason_D_Lubin%40mcpsmd.org%7C2a3c4014d9304f2f1b6108dafb9f950d%7Cddf755e9bcd64a5ea4727c378a78c6c7%7C0%7C0%7C638098960067852741%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Fc00x5dDSwEZvaIvR0Ov4cGGj%2FWZHMqH%2F50bqASnV2k%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA5L74G2SB2EXAZQHF5UXW53WTO7MHANCNFSM6AAAAAAUB5C2MU&data=05%7C01%7CJason_D_Lubin%40mcpsmd.org%7C2a3c4014d9304f2f1b6108dafb9f950d%7Cddf755e9bcd64a5ea4727c378a78c6c7%7C0%7C0%7C638098960067852741%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xng2i4A9X0K2Ees7L0mx3VWM%2F26XooWt%2BaTZKqRjVPY%3D&reserved=0>. You are receiving this because you authored the thread.Message ID: ***@***.***>

No need to be rude about support for a free application. As the developer said, this is not an issue with his application. He made no changes to cause the issue. The Google Chrome developers have made a security privilege change that prohibits Photopea from saving the way it used to. He is in communication with the Chrome developers, but they won't be making any fast reversions.

You may need to find a workaround for the time being. There are a few other tickets for this same issue here on GitHub. I remember seeing one who had found a workaround regarding drive mappings or something. Maybe look thru the recently closed tickets to see if they can help.

**Comment by photopea** [comment]
@lakelands we can not fix it. you need to change your system.
