### ISSUE TITLE
This isn't a issue, is more a question

### ISSUE THREAD

**Issue by raabe-ctrl** [photopea/photopea#5293]

**Comment by raabe-ctrl** [comment]
sorry I clicked enter and it got published before I could explain myself.

![Captura de tela 2023-01-20 204237](https://user-images.githubusercontent.com/91345712/213824407-ab53c82b-fd62-4906-bb53-0859c6df8dc0.png)

Here's a screenshot from Figma. I have this font with special ligatures and alternate letters, and as I did in the image, on Figma I have these options where I can play with these font special characters. But in Photopea, I can't find a way to do the same. Is there some way to use the different properties of a font like this in Photopea? Thank you already

**Comment by raabe-ctrl** [comment]
the font is Vintages from Envato Elements

**Comment by raabe-ctrl** [comment]
In Photopea, the text just stay like this:
![image](https://user-images.githubusercontent.com/91345712/213824627-4ec340de-0496-4d6d-90f7-e28c66e6930c.png)
And I can't find a way to change it

**Comment by photopea** [comment]
Sorry, we do not support the option to change ligatures :( Maybe convert your text into a vector shape (in Figma), and sav a Figma file with the vector shape instead of a text layer.

**Comment by photopea** [comment]
These advanced stylistic options are available in Photopea now!
