### ISSUE TITLE
Export as .mp4 file problems

### ISSUE THREAD

**Issue by jjadeite** [photopea/photopea#5294]
So I made an animation using photopea, but instead of exporting it as a GIF, I am planning to export it as an mp4 for other purposes. Now everything looks fine in the preview, but once you export it, the exported mp4 file is broken. Windows Media Player cannot play it all, while VLC media player would only show just a single frame then the video would instantly end. This is not the case for GIF exports, because when I try to export it as a GIF, the animation is working.

In the end, I just exported my animation as a GIF and searched for a GIF to mp4 converter online as a workaround solution.
However, It would be great if next time, we could fully use the "export as mp4" without problems. 

Is there a solution we could do for this? Or is it some bug that needed to be fixed by the developers?

**Comment by camoody1** [comment]
The developer will likely request that send him your project file via email so he can check for bugs in his end.

Smart workaround on your part, though.

**Comment by photopea** [comment]
Did you try to open your MP4 file with Google Chrome? Some video players can not handle the case when each frame of a video has a different delay (they expect a constant framerate).

It would help if you saved your work as a PSD and shared that PSD with us.

**Comment by photopea** [comment]
I have to close it because of lack of details.
