### ISSUE TITLE
How can I subtract shapes from one another?

### ISSUE THREAD

**Issue by CxryzNFTs** [photopea/photopea#5295]
How can I subtract two different shapes, on seperate layers from each other on Photopea?
I can subtract a newly created shape from an already existing shape, however, I cannot figure out a way to subtract already existing shapes from one another. 

I've watched this tutorial on YouTube, but in Photopea, there is no "Combine Shapes" option.
https://www.youtube.com/watch?v=VHEAV1yc5Mg&ab_channel=VishapTVplus

Is there a way to subtract two shapes from one another using the steps in the video?

**Comment by camoody1** [comment]
1. Make sure that your newly created shape is exactly one layer above your existing shape.
2. Right-click on your newly created shape layer and choose "Merge Down". (Or click on Layer -> Merge Down)
3. Your new shape will now be on the same layer as your existing shape.
4. Using the Path Select Tool, click once on your new shape to select it.
5. On the top toolbar, change the mode from "New Layer" to "Subtract".
6. Your new shape should now be subtracting from your existing shape.

**Comment by CxryzNFTs** [comment]
Thanks for your help!

**Comment by photopea** [comment]
I have added the option: Layer - Combine Shapes - Subtract, etc.

**Comment by camoody1** [comment]
> I have added the option: Layer - Combine Shapes - Subtract, etc.

Oh fine. Just totally ruin my impressive workaround by making it simple. 😆

**Comment by photopea** [comment]
Your impressive workaround still works around! :)
