### ISSUE TITLE
Feature Request: Mixer Brush Tool

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5296]
Would love to see you add a Mixer Brush Tool to Photopea as seen in Photoshop. This tool would be a huge benefit to digital painters. It allows the user to create images and enhancements that are impossible with any other Photopea tool. As with all feature requests, I have no idea if this is something you can figure out, but you haven't failed me, yet! 😆

Here are a couple of videos showing what is possible with the tool and how the associated toolbar settings affect it.

https://youtu.be/df5iF12V1w0
https://youtu.be/Ovqr6q00UYM

**Comment by camoody1** [comment]
I just noticed that there's already a ticket open for this from back in 2021... #3985 . You had some notes in the ticket suggesting you were open to investigating adding the tool, but nothing seems to have come from it.

**Comment by photopea** [comment]
Yes, lets discuss it in https://github.com/photopea/photopea/issues/3985
