### ISSUE TITLE
Feature Request: AI Inpainting

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5297]
We've talked about this quite a bit and you've added some basic tools for DALL-E and Stable Diffusion, but I wanted to show you an example of "the ultimate dream" of how Inpainting should work.

[Link to Reddit Post](https://www.reddit.com/r/StableDiffusion/comments/10h1ros/editing_a_photo_with_inpainting_time_lapse/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button) 

I know it may not be possible to achieve at this time, but this is exactly what I have in mind when I talk about the power of Inpainting. It's similar to Content-Aware Fill, but much smarter and adds the ability to insert entirely new images to a photo.

Notice how the user starts with a large photo and zooms in to modify a much more manageable image size (less than 1024x1024). It would be awesome if you could manage something like this in Photopea, such that we could send just a portion of a much larger image to the Stable Diffusion API to be processed as an "image-to-image" request and returned and added back to the original image.

Very cool stuff.

**Comment by photopea** [comment]
I think the current Text to Image feature should be able to do all this, but with a different API, see https://www.photopea.com/tuts/use-stable-diffusion-for-free/

**Comment by Kryptortio** [comment]
I think [AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) is the most popular project. Might be a good [API to implement](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API) (no need to pay for a public API, but will be a bit slow without a good GPU) it has an option to grant Photopea [access with CORS](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/4294). Here is [example for how someone implemented it in Photoshop](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin) another good example for UI inspiration is [InvokeAI](https://github.com/invoke-ai/InvokeAI).

**Comment by photopea** [comment]
@Kryptortio have you tried to use it yourself? With Photoshop or any other software?

**Comment by Kryptortio** [comment]
No, I don't have Photoshop as I don't need it with Photopea around :)

I have used AUTOMATIC1111 a lot though and done some experimenting with inpainting using their UI (just started paying around a bit with [pix2pix](https://github.com/Klace/stable-diffusion-webui-instruct-pix2pix) as well).

If it helps here are [a couple of reddit posts](https://www.reddit.com/user/abdullah_alfaraj/submitted/) from the creator where they talk about the Photoshop plugin.

**Comment by photopea** [comment]
I mean if you tried to run the stable diffusion on your computer yourself.

**Comment by Kryptortio** [comment]
Sure, AUTOMATIC1111 is easy to [setup](https://github.com/AUTOMATIC1111/stable-diffusion-webui#installation-and-running) (--use-cpu command line option to [run on CPU](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings), have not tried that) and has gotten easier since I did it as there is now the option to [run it without even having to install it](https://www.reddit.com/r/StableDiffusion/comments/10kwln8/automatic1111_webui_binary_v100pre_released_no/) (Windows/NVIDIA only).

**Comment by camoody1** [comment]
I believe I recently saw some posts where this add-on now allows use of the HORDE sharing process where people share their unused GPU time to help others perform their enhancements. It's an interesting concept, but will easily be ruined if people don't share as much as they use.

**Comment by photopea** [comment]
I tried to inpaint using Window - More - Text to Image, and it seems to work quite well. I dont think many people are interested in an advanced tool with lots of options.

![Background](https://user-images.githubusercontent.com/15955558/216177119-683d1fbc-f1b6-4f4c-9489-6c9697a41c00.jpg)
![Background (1)](https://user-images.githubusercontent.com/15955558/216177125-53fdd557-b970-4287-a095-043e1ddfd4cd.jpg)
![file (3)](https://user-images.githubusercontent.com/15955558/216177126-6960c1c1-5ce0-4355-a5ca-2f336299f664.jpg)

**Comment by Kryptortio** [comment]
Just thought I should add it if here if anyone needs it, someone made an extension for integrating Photopea in the [AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui/) webui https://github.com/yankooliveira/sd-webui-photopea-embed

**Comment by camoody1** [comment]
> Just thought I should add it if here if anyone needs it, someone made an extension for integrating Photopea in the [AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui/) webui https://github.com/yankooliveira/sd-webui-photopea-embed

This is really nice work, Krypto. I wish I had an Nvidia GPU so I could take part in the amazing AI at home renaissance. Alas, I'm still using an old AMD R9 390 from about 8 years ago. Well done, sir.

**Comment by photopea** [comment]
We just added this feature to Photopea. No GPU needed, no plans, completely free. Just make a selection, switch to a Spot Healing Brush, and press "Remove with AI" at the top. More info here: https://github.com/photopea/photopea/issues/5516

Here is what it did to your image:
![image (2)](https://user-images.githubusercontent.com/15955558/236648782-57482016-5e50-4501-9f3c-436d10dea31b.jpg)
