### ISSUE TITLE
Feature Request: Save Brush Tool Settings as Styles

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5299]
As seen [here](https://www.photoshopessentials.com/basics/save-custom-brush-presets-photoshop-cc2018/), it would be very beneficial to allow users to save brush "styles" (foreground color, background color, brush settings). You could either save these styles along with the brush definition itself (as shown in the above link) or create a new place to save "brush styles" that could be applied to any selected brush from the brush list. 

Ideally, when a new brush is defined, Photopea should prompt the user to create a name for the brush, instead of assigning a generic file name as it does currently. Either that, or allow the naming of the new "brush style" itself (ex. blonde hair, brunette curly hair, green grass, brown fields, clouds, etc).

This feature request goes along with a thought you brought up in another ticket discussing the idea of saving font styles. Thought these were both good ideas.

**Comment by photopea** [comment]
But now, you can define your own brush, just like you can do it in Adobe Photoshop. Are you aware of it? You can rename brushes, too.

**Comment by camoody1** [comment]
Yes, I understand that I can create a new brush. What I'm asking to do is to save brush settings as a style so that I don't have to re-enter my preferred brush settings every time I switch to a new brush. It's not user friendly. It's not easy to remember each setting and it takes extra time that shouldn't be necessary.

These are the settings I'm talking about, btw...
![SmartSelect_20230123_044235_Chrome](https://user-images.githubusercontent.com/73725653/214008887-2def7827-51f4-406f-bcd4-22fa7ae2c0ce.jpg)

**Comment by photopea** [comment]
I still think you dont know how brushes in Photopea or Photoshop work. Maybe read this: https://www.photopea.com/learn/brush-tools

Or learn how people work with brushes in Adobe Photoshop to achieve what you want to achieve.

**Comment by photopea** [comment]
If you change the settings of a brush, you should define a new brush, to save it into a gallery.

**Comment by camoody1** [comment]
I don't think you're reading what I'm typing. 😆

After changing the brush settings to what I wanted, I DID define a new brush. That brush, in fact, did retain those settings... even when I selected other brushes that had different settings, when I came back to the newly defined brush, my desired settings were there. Perfect. However... In order to use that same defined brush in future Photopea sessions, I need to export that brush as an ABR file and the load that file in the future Photopea session. When I tested this process, the new brush was loaded into Photopea, but none of the settings I had previously defined were loaded with it. So, all those brush settings were lost.

I'm not sure how else I can explain this,cso hopefully, this makes sense. 🙂

**Comment by photopea** [comment]
I can not reproduce this problem :(

I selected one of default brushes, enabled "Tip Dynamics", "Scatter", "Color Dynamics", "Transfer", and defined a new brush. Then, saved that brush into an ABR (below). When I load the ABR into Photopea or Photoshop, it has all the parameters.
[brushes.zip](https://github.com/photopea/photopea/files/10479031/brushes.zip)

**Comment by photopea** [comment]
Sure, go to sleep! :)

I dont think it is a good idea to store a specific color with a brush. I would rather keep it as it works in Photoshop. So if you know about anything Photoshop can do with brushes, but Photopea cant, let me know :)
