### ISSUE TITLE
Use filter on fonts

### ISSUE THREAD

**Issue by tomasnosek** [photopea/photopea#53]
I would live a filters on font dropdown when i could filter sans-serif, serif fonts, font-weight types "normal, bold". You can find inspiration on google fonts.

**Comment by photopea** [comment]
Hi, there are filters (above the list of fonts), where you can choose caregories like sans-serif, serif .... but there are too many categories, so it is hard to find :)

**Comment by tomasnosek** [comment]
Was this there before? It's fine to have it there, but it's also in a way not so good for user experience.

**Comment by photopea** [comment]
It was always there. Maybe I should sort these categories according to the number of available fonts, so serif / sans would be the first.

**Comment by tomasnosek** [comment]
Numbers are not so important. Serif and sans-serif are simply the highest priority categories.

**Comment by photopea** [comment]
Why? I like Dingbat, too!

**Comment by tomasnosek** [comment]
:)

**Comment by photopea** [comment]
Hi, so it is fixed now. Categories are ordered by frequency. If you want to see just Sans-serif fonts, You untick all categories (by clicking All) and tick "Sans Serif" only.
