### ISSUE TITLE
Edge and other Chromium browsers reporting site as malware

### ISSUE THREAD

**Issue by FlarosOverfield** [photopea/photopea#5301]
![image](https://user-images.githubusercontent.com/24918282/214006899-a8f42bd9-9ff8-419c-ac53-7ffd7edb79c7.png)

**Comment by FlarosOverfield** [comment]
No extensions, happens in InPrivate mode too. The site is still accessible and usable

**Comment by photopea** [comment]
In what country are you located? Is it possible, that your web traffic goes through your government or some companies, which are allowed to censor it?

**Comment by FlarosOverfield** [comment]
I do live in Italy, which is **infamous** for censoring information, but this time it's not an issue with Italy.
Apparently someone using edge reported the site as unsafe, but the owner of Photopea can report it as a false positive here: https://feedback.smartscreen.microsoft.com/feedback.aspx
![image](https://user-images.githubusercontent.com/24918282/214027083-6691f54a-ce40-4fc8-a069-48a11a8e1efc.png)

**Comment by photopea** [comment]
I sent a form, but it is hard if anyone will react to it and when.

As it is not a bug in Photopea, but in your software, could you report a bug to the creators of your software?

**Comment by photopea** [comment]
Or at least do this. If it does not help, switch to a "better" browser (with a better malware detection).

![image (1)](https://user-images.githubusercontent.com/15955558/214031547-089ae65a-d283-43a0-8d72-fd83d3837359.png)

**Comment by FlarosOverfield** [comment]
...i already did that long ago. The intent was to warn you, the owner of Photopea, that someone is incorrectly reporting your site as malware. But sure, blame the user i guess

**Comment by photopea** [comment]
I dont know what more can I do about it :( It seems like anyone can make Microsoft block any site for all Edge users.

**Comment by MichalSZZ** [comment]
Same here in Poland

![obraz](https://user-images.githubusercontent.com/38118273/214074232-fae63956-08a7-4413-9bcb-83b9bce7be9c.png)

"Microsoft Defender SmartScreen" I don't if anyone with Windows has this MS Defender and this information, but I added +1 vote for a safe website.

Maybe that is a "special action" from people who can't use Photopea for some reason...

**Comment by camoody1** [comment]
I just checked... It's the same in the United States.

Someone is coming after our favorite web app.😡

**Comment by photopea** [comment]
It seems like Microsoft has fixed it. Thanks for your help!

**Comment by camoody1** [comment]
This is great news. Maybe enough of your users actually reported it being safe that an alert went off telling them that they were wrong. For whatever reason, that's a surprisingly fast resolution.

**Comment by FlarosOverfield** [comment]
> This is great news. Maybe enough of your users actually reported it being safe that an alert went off telling them that they were wrong. For whatever reason, that's a surprisingly fast resolution.

Or maybe, just maybe, don't tell users to "use a better browser", especially if there isn't one?

**Comment by photopea** [comment]
When this happens, every browser is better than Edge. If people keep using bad browsers instead of good ones, the progress will be very slow.

**Comment by FlarosOverfield** [comment]
So if haters report your site as unsafe it's magically Microsoft's fault instead of the haters? Amazing.

**Comment by camoody1** [comment]
> So if haters report your site as unsafe it's magically Microsoft's fault instead of the haters? Amazing.

Just log off your computer for awhile and go outside. Touch the grass. Maybe pet a dog. 🙄

**Comment by photopea** [comment]
@FlarosOverfield Of course it is. If a you allow anyone to block any website for 1 billion people just with one click, it is probably not a good model. 

If I tell the police that I don't like my neighbour, and they shoot my neighbour, that is not how the police should work.

**Comment by FlarosOverfield** [comment]
It's funny that you think _**one**_ person did this. I get DDOS'd every single day and i didn't even make a web app that absolutely destroys Photoshop and Krita.
