### ISSUE TITLE
SVG problem - Flag of Brazil is wrong

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#5302]
Flag of brazil in SVG format loads wrong. Layer with green color is shifted.
File URL:
https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg
Screenshot:
![image](https://user-images.githubusercontent.com/6370548/214010490-e7b7ac48-d73d-410b-92c0-a13ccd2d3e6a.png)

**Comment by photopea** [comment]
fixed! :)
