### ISSUE TITLE
(Feature Request) New 'Content Aware Fill' workspace feature similar to Photoshop.

### ISSUE THREAD

**Issue by bluep55** [photopea/photopea#5303]
Accessing Content Aware via ‘Edit’ / ‘Fill’ then choosing ‘Content Aware’ can at times be very hit or miss and inconsistent in it’s results.
For much more control and far better results it would be great if something similar to the ‘Content Aware Fill’ workspace feature used in Photoshop could be introduced to Photopea.
A couple of examples shown here:
https://www.youtube.com/watch?v=OiwqOAPE0kk
https://www.youtube.com/watch?v=RTAIadLP6Dk

**Comment by photopea** [comment]
It is already reported here: https://github.com/photopea/photopea/issues/4254
