### ISSUE TITLE
PeaDrive Issue

### ISSUE THREAD

**Issue by CxryzNFTs** [photopea/photopea#5304]
When I drag a file to upload to the Photopea Drive, it creates duplicates of other files as well.

How to replicate:
1. Navigate over to the Photopea Drive
2. Upload a couple files
3. You will soon see duplicate copies of files appearing

Please fix this bug, it's very annoying. Thanks

**Comment by camoody1** [comment]
Confirming that I, too, have this same issue. After you drag the first file into the Photopea drive, everything seems to be fine. But then when you drag in the second file, a copy of the first file is created along with the new second file. And if you drag in a THIRD file, the first file is AGAIN recopied (for a total of three copies), the second file is copied again (for a total of two copies) and the third file is copy in.

A very weird occurrence, indeed.

**Comment by photopea** [comment]
Fixed! Thanks for reporting it :)
