### ISSUE TITLE
VS Code Login In Bug

### ISSUE THREAD

**Issue by bradhave94** [photopea/photopea#5305]
I'm using the new VS Code extension and I want to log in to remove ads.

Clicking the 'Log In' button doesn't do anything.

![Code_tkNgrx46eU](https://user-images.githubusercontent.com/5970177/214293824-ab7239b7-fe96-442c-a81c-539ab3efd449.gif)

Getting the issue on Both Windows 11 and Ubuntu.

**Comment by photopea** [comment]
I am afraid that Visual Studio does not allow plugins open separate browser windows.

What if you log in at Photopea.com in your web browser? Do you stay logged in in Photopea in the Visual Studio?

**Comment by bradhave94** [comment]
No, unfortunately it doesn't work

**Comment by photopea** [comment]
Photopea plugin needs to open a new window to allow you to log in or pay. VSC seems to be blocking it. I think it is a bug in Visual Studio Code, we can not do anything about it. You can use www.Photopea.com in a web browser, too.

**Comment by photopea** [comment]
I have reported it here: https://github.com/microsoft/vscode/issues/172190

**Comment by bradhave94** [comment]
Gotcha, thanks. And yeah I use [www.Photopea.com](http://www.photopea.com/) all the time.
