### ISSUE TITLE
Displacement function doesn't work

### ISSUE THREAD

**Issue by vckh** [photopea/photopea#5307]
The displacement function doesn't work. Go to "filter" > "distort" > "displace". Then in the window that will appear you need to choose the FILE (usually it's PSD alike photoshop). But, the original working file can't be chosen due to bug. And if you will not choose the file, and hit OK, nothing will happen, the displace image will remain the same.

<img width="467" alt="Capture" src="https://user-images.githubusercontent.com/123519287/214446870-3b6c1373-1f60-4c71-af39-560b7fac63f4.PNG">

**Comment by photopea** [comment]
You need to choose a smart object. Photopea is a website and it does not see what files you have on your hard drive.

**Comment by camoody1** [comment]
@vckh Here's a super short example of how Photopea does displacement.

https://youtu.be/xXljwmwEIpM

**Comment by vckh** [comment]
Oh, @photopea many thanks for your help!

**Comment by vckh** [comment]
@camoody1 thank you!

**Comment by photopea** [comment]
BTW. Photoshop can embed a displacement map now, and now, Photopea does it too (by default)!

![how-to-use-a-displacement-map-in-photoshop-19](https://user-images.githubusercontent.com/15955558/235771858-b2c76504-7b61-46a5-aeab-6810ff31317f.jpg)

When creating a Displacement filter, you select a Smart Object (for Photopea) or a PSD file on your computer (for Photoshop), and it is embedded inside a filter! You can delete that Smart Object (for Photopea) or a PSD file on your computer (for Photoshop).

If you send that PSD to someone, they can open it (in Photopea or Photoshop) and edit everything, without having an extra Smart Object or a PSD file (for the displacement map).
