### ISSUE TITLE
Cant move layers anymore

### ISSUE THREAD

**Issue by zimbo86** [photopea/photopea#5309]
Hi, as described in #3219 i cannot move layers anymore.
I´m using latest 109.0.1518.61 Edge.

What I already did:
- Created a new project with a default template from the gallery - same behaviour
- Edge inPrivate Mode - same behaviour 
- Edge other browser profile (normally completely separated from the default profile) - same behaviour
- Copied my psd to an Azure VM, an run Photopea there - works without any issue.

**Comment by camoody1** [comment]
I'm not doubting what you're seeing, but I've been using Photopea for awhile this morning on my Android phone and have had no problems moving layers. I just tested with a template from the Photopea store and that worked fine, too. I use Photopea A LOT and have never seen this. Can you consistently reproduce this issue? If you restart your PC, does the issue persist? So odd that this is happening even in a brand new PSD file.

**Comment by zimbo86** [comment]
> 

.. see here:
[](https://streamable.com/89rsnp)
Will do a reboot now, keep you updated.

**Comment by zimbo86** [comment]
.. after a reboot its working.
system uptime was 12h..

**Comment by photopea** [comment]
It seems like a bug in your browser. Try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/
