### ISSUE TITLE
Smart filter is creating without mask from selection

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#5310]
This is a problem reported by another user od Reddit https://www.reddit.com/r/photopea/comments/10kvho7/about_smart_object_range_selection/

How to reproduce:
- convert layer to a Smart Object
- make a selection on a part of the image
- go to menu filter and use any of the filter (for example gausian blur)

How is now:
- Filter is on the whole layer. 
- Mask of the smart filter is white
- selection is all the time visible

How should to be:
- Filter should be only on the pixels that was inside the selection
- mask should to be black where was the selection and white outside
- I don't remember how it is in Photoshop but maybe after adding filter, selection is not visible
-

**Comment by photopea** [comment]
Done! :)
