### ISSUE TITLE
Navigateur fait tout planter

### ISSUE THREAD

**Issue by alex-lcdc** [photopea/photopea#5311]
Bonjour, 
Dès que je touche le navigateur pour déplacer la vue, photopea plante.
Merci pour ce logiciel quoi qu'il arrive, au top!

**Comment by photopea** [comment]
Hi, try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details :(
