### ISSUE TITLE
Block/Pixel brush issue

### ISSUE THREAD

**Issue by WaessrigesFuchs** [photopea/photopea#5312]
not sure if this is already known or if this is even a issue but the square brush
![image](https://user-images.githubusercontent.com/75032232/214957534-33b0eedd-ac36-43d5-bdb1-a96a1a3fa82f.png)
recently became sorta a blurry mess/anti aliased

this was completely fine around a month ago but since then i couldnt do much since it was one of the main things i used
hope this can be resolved in the future

**Comment by camoody1** [comment]
Interesting. I don't seem to notice anything blurry about my version of that brush. Could you post a screen shot of what you're seeing? What size is the canvas you're drawing on? Are you running the brush at 20 px or blowing it up to something very large?

**Comment by photopea** [comment]
Could you show us a screenshot of what you mean by blurry mess?

**Comment by WaessrigesFuchs** [comment]
old:
![image](https://user-images.githubusercontent.com/75032232/215091491-dff27f25-46ee-4fd6-9391-60c614c43372.png)
new:
![image](https://user-images.githubusercontent.com/75032232/215091539-a042e2cb-81b5-424e-ba67-c217274ab49b.png)
its also not related to the brush or canvas size

**Comment by camoody1** [comment]
Have you tried using the Pencil tool instead of the Brush Tool? The Pencil tool is crisp without ant-aliasing, while the Brush tool has the softer edges that you don't want.

**Comment by photopea** [comment]
You have to use the Pencil tool to avoid anti-aliasing. The brush tool has always been anti-aliased. I think your first image is made with the Brush tool.
