### ISSUE TITLE
'Isolated' box.

### ISSUE THREAD

**Issue by bluep55** [photopea/photopea#5313]
In portrait mode on my mobile phone (installed version), the 'Isolated' box in the gallery window is not visible, even when the gallery is pulled all the way to the left. My phone doesn't let the installed version rotate to landscape even though I have auto rotate turned on.

![Screenshot_20230127_001312_Chrome](https://user-images.githubusercontent.com/118609932/215081432-8c5a8bbe-1ed8-4f5f-b126-282290f33ef2.jpg)

**Comment by photopea** [comment]
You can type "Isolated" into a search box and it will work the same.

**Comment by bluep55** [comment]
Thank you. I didn't realise that 👍🙂

**Comment by bluep55** [comment]
In most cases it removes the background.

**Comment by camoody1** [comment]
Ahhh... I see. I just couldn't see the difference before. Now it makes sense. Thanks.

**Comment by bluep55** [comment]
Or there might be a plain background that can easily be removed.

**Comment by photopea** [comment]
It does not remove a background. It shows only images where the author wrote "isolated" into a description.

By "isolated", authors usually mean, that an object is somehow "isolated" from the rest of the image (usually a background is removed - transparent).

**Comment by camoody1** [comment]
Gotcha. Thank you for the explanation. 🙂
