### ISSUE TITLE
Unknown JSON file opened 

### ISSUE THREAD

**Issue by marino4ka2322** [photopea/photopea#5314]
Unknown JSON file opened.  See the content in the console
----CONSOLE------
DevTools failed to load source map: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
pp.js:11250 0
pp.js:14567 Service worker active
pp.js:9523 Extra parameter Spcn
pp.js:14290 Alert: Loading files from Google Drive ...
cb=gapi.loaded_0?le=scs:405 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing.
2
DevTools failed to load source map: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
cb=gapi.loaded_0?le=scs:386 Your client application uses libraries for user authentication or authorization that will soon be deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information.
pp.js:14603 
 GET https://www.googleapis.com/drive/v3/files/1sjNBuzxK5lcqWCQUhqffcEVwF5aHlvqo 404
pp.js:14364 
 GET https://www.googleapis.com/drive/v3/files/1sjNBuzxK5lcqWCQUhqffcEVwF5aHlvqo?alt=media 404
pp.js:14290 Alert: Unknown JSON file opened. See the content in the console.
pp.js:14438 
{error: {…}}
error
: 
{errors: Array(1), code: 404, message: 'File not found: 1sjNBuzxK5lcqWCQUhqffcEVwF5aHlvqo.'}
[[Prototype]]
: 
Object

**Comment by photopea** [comment]
Hi, do you think Photopea does not work as it should? What should I do to see it working not as it should?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
