### ISSUE TITLE
Ad blocker detected even though it is set to allowed for photpea.

### ISSUE THREAD

**Issue by j2m6lz5n** [photopea/photopea#5317]
Ad blocker detected even though it is set to allowed for photpea. I feel bad getting the message saying that I am the problem.

**Comment by photopea** [comment]
It could be a bug in your ad blocker. It is telling you it is off, but it is still blocking our ads.

Did you try to disable your ad blocker completely?

**Comment by erikmolenaarnl** [comment]
Same here. Using AdBlock 5.3.3:

![image](https://user-images.githubusercontent.com/22014267/215766209-c2487428-a888-44cc-8e18-9be854c81637.png)

**Comment by camoody1** [comment]
All these AdBlocker issues go away if you just donate $3.33 per month for using Photopea. 😁

**Comment by photopea** [comment]
@erikmolenaarnl It means that your ad blocker is lying to you, it is not really off.
