### ISSUE TITLE
Custom Shape panel in portrait mode.

### ISSUE THREAD

**Issue by bluep55** [photopea/photopea#5318]
Is there a way to make the 'Custom Shape' panel narrower in portrait mode on mobile (installed version)?
When scrolling down all the icons on the left side are hidden.

![Screenshot_20230128_222817_Chrome](https://user-images.githubusercontent.com/118609932/215295472-b18346d3-5d67-40b2-9fec-d40deff460df.jpg)

**Comment by photopea** [comment]
fixed!
