### ISSUE TITLE
Copy doesn't work I allowed so I can copy things to clip board and paste it but it doesn't really work its not letting me paste

### ISSUE THREAD

**Issue by litegotdubs** [photopea/photopea#5319]

**Comment by photopea** [comment]
Can you open a JPG image, draw a selection with a Lasso, press Ctrl+C and Ctrl+V, is a new layer created?

What web browser do you use?

**Comment by camoody1** [comment]
I have this same issue on my Android phone in the Edge browser. I can select with a marquee tool and copy paste, and I can copy paste after selecting pixels of a layer, but I cannot copy an image from a website and paste it into Photopea. I assume that is what the OP is trying to do.

**Comment by photopea** [comment]
I have fixed it in Chrome / Edge for Android. The Edit- Copy and Edit - Paste should cooperate with the system clipboard (which works even outside Photopea). Could you check if it works as you wanted?

**Comment by camoody1** [comment]
Yes sir! That fixes it for me. It's now working the way I would assume that it should. When I first attempted to paste from the clipboard, Photopea asked for permission to access the clipboard and then it lasted correctly. Thank you, sir.

**Comment by photopea** [comment]
Ok, I hope it is the solution for the original request, too.
