### ISSUE TITLE
Support sheet music

### ISSUE THREAD

**Issue by Toldry** [photopea/photopea#5320]
Here is a sample sheet music PDF file:

[chopin_nocture_9_2full PIANO.pdf](https://github.com/photopea/photopea/files/10529368/chopin_nocture_9_2full.PIANO.pdf)

Here is what it looks like when I open it on Chrome:

<img width="868" alt="image" src="https://user-images.githubusercontent.com/7353619/215315218-e0b64df8-f309-4da6-be33-b9f59f038682.png">

When I open it in Photopea, I get these font replacement messages:

<img width="895" alt="image" src="https://user-images.githubusercontent.com/7353619/215315262-5f29f367-58cd-49b9-9eef-f12195d43afe.png">

Here is what the sheet music ends up looking like in Photopea:

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/7353619/215315295-568827ff-b3e0-40f4-84b5-e66fd255da3d.png">

**Comment by Toldry** [comment]
I will buy a 365 day Photopea memberships when sheet music support will be implemented 🎶😊

**Comment by MichalSZZ** [comment]
I think that the biggest problem is missing font with notes. You don't have Opus Special Font and Opus Text Font. Without these fonts Photopea can't show notes.
But even if the 100% fonts will be loaded it can be a problem with PDF text interpretation. 
Can't wait what author will say about that.

**Comment by camoody1** [comment]
I actually tried downloading and installing fonts called Opus, Opus Special and Opus Text. Even after doing so, the PDF still did not open correctly in Photopea. I assume I just didn't have the exact correct font. I have no idea how you would go about finding the exact correct fonts.

**Comment by Toldry** [comment]
Here's another sample sheet music PDF file (of J.S Bach's Passacaglia and Fugue in C minor, BWV 582).

Opening this one has the additional problem of almost crashing Photopea because it is relatively large (19 pages)

[IMSLP81862-PMLP04326-bwv582-a4.pdf](https://github.com/photopea/photopea/files/10530258/IMSLP81862-PMLP04326-bwv582-a4.pdf)

**Comment by photopea** [comment]
It would take too much work, and there are not that many people who need it. 

PDF files were not meant to be edited by any program. They are mainly for reading / printing. You should not use programs like Photopea to write or edit music sheets.

What you can do is take a screenshot of your document and paste that screenshot into Photopea.
