### ISSUE TITLE
pasting photopea template links in text boxes causes the actual template to open

### ISSUE THREAD

**Issue by Z2r-YT** [photopea/photopea#5321]
this issue is rather miniscule, however, upon pasting links to photopea templates in text boxes, the template itself opens in a new file, as seen in this video;

https://user-images.githubusercontent.com/69476320/215325826-27c4e612-f3d0-49a6-b242-deeb2b3141a6.mp4

**Comment by photopea** [comment]
Hi, i can not make it happen :( what web browser do you use?

**Comment by Z2r-YT** [comment]
> Hi, i can not make it happen :( what web browser do you use?

I use FireFox!

**Comment by photopea** [comment]
okay, it should not happen anymore.
