### ISSUE TITLE
Straighten layer (in a crop tool)

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#5323]
Check if the line is "more horizontal" or "more vertical", and crop according to that.

**Comment by camoody1** [comment]
Issue opened in reference to Reddit request:
https://www.reddit.com/r/photopea/comments/10oi6jd/using_straighten_layer_tool/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

**Comment by photopea** [comment]
It has been implemented! :)

**Comment by camoody1** [comment]
Works for me! Thank you!

**Comment by camoody1** [comment]
That would be massively crooked photo, though. If the image is more than 45° off plum, I think the user can take the extra step to rotate it. 👍🏼
