### ISSUE TITLE
photoshop's frame tool?

### ISSUE THREAD

**Issue by tenkafubu** [photopea/photopea#5324]
Can you add something like photoshop's frame tool?

**Comment by MichalSZZ** [comment]
https://www.youtube.com/watch?v=DQEMO4ECLqc

I saw this feature when it was added a few years ago, but I never used it. 
It is something like the clipping mask (or vector mask) but without two layers - easiest to use.

This can be helpful in wireframing and prototyping UI or design mockups without graphic content. 
You can show the design of the flyer or web design with only places for images and text.

**Comment by tenkafubu** [comment]
Can you add this feature to photopea too?

**Comment by tenkafubu** [comment]
Can you add this feature to photopea too?

**Comment by camoody1** [comment]
> Can you add this feature to photopea too?

Why did you close this?

**Comment by tenkafubu** [comment]
I didn't know how to use it, so I made a mistake. 
I have restarted this.

**Comment by photopea** [comment]
I made a PSD file with a "frame layer" in Adobe Photoshop. I opened it in Photopea. The frame layer was converted into a folder with a smart object, and the folder has a vector mask on it.

So basically, it can be done already by putting stuff into a folder and giving the folder a vector mask. I think there is no need for this tool.

**Comment by tenkafubu** [comment]
Thanks for the advice. I learnt something new.
