### ISSUE TITLE
fonts freeze the ui

### ISSUE THREAD

**Issue by escelluns** [photopea/photopea#5325]
whenever i try to change my font on a text, it works the first time, but when i click again the whole screen freezes and i cannot click on anything so i cannot make any progress on my works and its only been happening the past three days idk what changed but it didn't change for the good that's for sure

**Comment by photopea** [comment]
Hi, try this, let me know if it helped: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
There was a bug with emojis in a text. It should be fixed now.
