### ISSUE TITLE
Simple aesthetics and layout problems

### ISSUE THREAD

**Issue by berto-dev** [photopea/photopea#5327]
Really stupid, but boring, layout problem: "side panel to the right of view is horrible and wrong floated"
![Immagine 2023-02-01 202737](https://user-images.githubusercontent.com/92259138/216144173-e3afa8db-4ea3-4dbd-b8bc-f18cebb3fb6c.png)

suggest:
- remove side panel to the right of view;
- remove "account" in red (it's not an error!);
- why sub menu doesn't have equal style of ui??
- center "photopea box of first canvas";
- reduce size of bottom icon (for consistency role of ui, make it in white and same style and change "any" whit a simple file icon)

Greetings

**Comment by mmontag** [comment]
Haha, best github issue I've seen yet.

**Comment by berto-dev** [comment]
I have installed it via simple pwa in edge / chrome. I don't have any ads blocker active for my decision... idiots.

This product have different problem in ux.
It's not a good idea insult someone who tries to help you. it reveals a lot about you.

**Comment by photopea** [comment]
Hi, the empty space should contain ads. The "installed" version should look the same as the browser version. Does it look the same? Could you open about://extensions in your web browser and show us what extensions you are using?

**Comment by berto-dev** [comment]
Surely... 
Chrome 109 on Windows 11. No difference between pwa and standard browser.
These are the chrome plugins:
![Immagine 2023-02-02 102350](https://user-images.githubusercontent.com/92259138/216285024-77881638-b49a-4518-bd01-b90bb6317186.png)

I like the project but would recommend solutions other than a banner.
If I can (give the comments above), I would make it appear a "photopea is sponsored by" overaly video once a day upon first opening. An advertisement a day is justified given the free use, it would increase your earnings better of little permanent banner and would not bother the general layout and ux.

With a more elastic layout it will also be possible to dynamically see if the height are greater than 1 and if the adv problem exists or not automatically.

it's my opinion, take as such.

**Comment by photopea** [comment]
That is a lot of extensions. Could you try www.Photopea.com in the incognito mode (where extensions are disabled)? Do you see ads?

Ads in Photopea take at most 15% of your screen. We check the total screen size, so if you make a photopea window smaller, ads are still large.

**Comment by berto-dev** [comment]
Sure.
I tryed it and i tryed to deactive all browser plugins.... but nothing has changed.

**Comment by camoody1** [comment]
Perhaps you're behind a firewall that has blocks these ads before they even get to your browser?

**Comment by mmontag** [comment]
Either way, upgrading to Premium will fix it... 😜

**Comment by camoody1** [comment]
> Either way, upgrading to Premium will fix it... 😜

Truth 👆🏼
😆

**Comment by photopea** [comment]
Do you see any errors in a web console, right after you open Photopea.com ?

**Comment by berto-dev** [comment]
@camoody1  & @mmontag can you stop to say a no-sense solution? Free or not free isn't the question and Github isn't a good space for make a stupid advertising, make a google and social ads for it. Be a pro, this is not a primary scool and i not have time for that. Thanks.  
  
@photopea nothig in console and in network... it's all perfect but bunner isn't showed.  
  
\`\`\`  
pp.js:11276 0  
pp.js:14592 Service worker active  
pp.js:9551 Extra parameter Spcn  
\`\`\`  
but the call of _...pagead/js/**adsbygoogle.js**_ and _cmp.js_ return an empy featch/XHR data:  "fail to load response data ..."

**Comment by photopea** [comment]
@berto-dev thanks a lot for your feedback! I have changed our adblock detection. Could you tell us what you see now? is it any different?

**Comment by berto-dev** [comment]
No, sorry... It's equal.

**Comment by photopea** [comment]
So what exactly do you see when you open www.Photopea.com and wait for the ads?

**Comment by berto-dev** [comment]
equal of top of this post.  
  
Version 110.0.5481.104 (Official Build) (64-bit)  
  
Nothing on _cookies blocked_  
_cookies run:_  
_\_\_unid_  
_\_ga_  
_\_ga\_49YR1RB5KP_  
_euconsent-v2_  
  
_in console:_  
_0_  
_pp.js:14627 Service worker active_  
_pp.js:9572 Extra parameter Spcn_

**Comment by photopea** [comment]
I think there must be something in your computer blocking our ads. Maybe it is not a browser extension, but something on a network level (an entity which checks every website that you visit, and decides if you should or should not see it).

Anyway, people who do not pay for Photopea always have "something" on the right side (either ads, or a request to disable their ad blocker). I am not able to reproduce what happens in your case :(

**Comment by berto-dev** [comment]
@photopea   
  
I'll have to try disabling the windows defender protections and see if there's something in runtime that blocks these situations. Now, from a contribution for you it's a topic of discussion for me too hahaha  
I'll update you as soon as I can experiment with 2 minutes
