### ISSUE TITLE
How many million dollars to open source Photopea?

### ISSUE THREAD

**Issue by mmontag** [photopea/photopea#5328]
Simple question: how much money do we need to raise? 😃 
Photopea open source would change the course of history, like alien technology, a gift to humankind.

**Comment by camoody1** [comment]
![52205448](https://user-images.githubusercontent.com/73725653/216192437-6b05f4f0-f66c-47d1-8366-117d2f6833a3.jpg)

**Comment by photopea** [comment]
Why don't you just pay someone "many million dollars" to crate a proper photo editor, or create it yourself? :D 

I really don't like the "mindset" that everyone must be ready to give something away, if you pay them enough money.
