### ISSUE TITLE
Crop Tool - Deleting Cropped Pixels Option 

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5331]
Ivan, sir...

Did you happen to fix some code on Thursday regarding the Crop Tool? I was trying to help an individual Wednesday night on Discord and he was having trouble getting the Crop Tool to work correctly. He wanted to deleted the cropped pixels, but he said they never went away. I figured he was just doing something wrong, but when I tried to show him, it didn't work correctly for me, either. Even though I would check the box to Delete Cropped Pixels, as soon as I went back to Transform the layer again, sure enough, all of the pixels outside of the crop (and off the sides of the canvas) were still there.

Well, after working with this guy for quite some time before realizing there seemed to be a bug, this person told ME to suck his d**k, told me to tell YOU to suck his d**k, and called Photopea "a piece of sh*t that couldn't even do a simple crop". He was a fine young man.

Anyway, I was going to record a video of it not working this evening and open a bug ticket, but tonight it's actually working.🤷🏽‍♂️ Did you do anything to fix it?

**Comment by photopea** [comment]
okay :D

I am not aware of the Crop tool not working, I did not fix anything. Please, write a report only when you find something not working in Photopea.
