### ISSUE TITLE
Floating buttons for confirm and cancel

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#5334]
Mobile users always have to scroll to the far right of the tool properties bar to click on confirm and cancel, which is very inconvenient. 

Is it possible to add floating buttons for confirm and cancel? 
<img width="890" alt="Slice 2" src="https://user-images.githubusercontent.com/79258245/216602150-a31c70a4-047d-4570-8fd4-a088f592c61a.png">
When the bottom edge of the box is inside the screen, the floating button is below the bottom edge of the box, when the bottom edge of the box is outside the screen, it is at the bottom of the screen

**Comment by bluep55** [comment]
A pity you closed this idea, it was a great suggestion..
