### ISSUE TITLE
Rotating stuff with ctrl + t creates fake pixels

### ISSUE THREAD

**Issue by B1BU** [photopea/photopea#5335]
When I rotate things by multiples of 90º (even with nearest neighbor active) it adds fake pixels to the image. If I press ctrl + t again, the silhouette of the image is slightly bigger than it should. This is probably more noticeable with pixel art.

**CORRECTION**: Apparently this only happens with nearest neighbor active

**Comment by camoody1** [comment]
Could you share an image that we could test that shows us this issue?

**Comment by B1BU** [comment]
> Could you share an image that we could test that shows us this issue?

Apparently this only happens with blending mode set to nearest neighbor.

![image](https://user-images.githubusercontent.com/44452075/216681264-bdbf93db-11b5-4175-acda-a30ad20bf1d5.png)
![image](https://user-images.githubusercontent.com/44452075/216681367-5634d848-e805-4839-9741-8dbcad161b1f.png)

**Comment by camoody1** [comment]
So, the image itself doesn't change, it just pads the image with extra transparent pixels to create a sort of frame around the original image? Is that what you're saying? Because the sofa image itself looks identical to me. 😆

**Comment by camoody1** [comment]
Are you seeing the difference in the X & Y values in the toolbar? Or are you seeing something more noticeable visibly that I'm just not noticing?

When I do a test of a 540x540 image, after I rotate it, the X, Y values change to 539x539. Is that what you're talking about? Just to be clear for the developers.

**Comment by B1BU** [comment]
It's more noticeable with smaller scale images, like game sprites and stuff like that (16x16, 32x32).

After rotating a layer, Photopea thinks the image is bigger than it actually is, it's like it adds 1 or 2 invisible pixels, as you can see from the blue square around the layer, the bounding box or whatever it's called. It becomes bigger, and that can affect the alignment of the layer.

A 16x16 layer would become like 17x18 or something.

Since this only happens when blending mode is set to nearest neighbor, that isn't really a big issue. I only set it to nearest neighbor because I thought it would be better for pixel art, but bilinear doesn't really affect it, so I'll just set the blending mode to that.

**Comment by photopea** [comment]
When you rotate a layer in Photopea, the center of the layer should stay at
the same place.

Imagine you are rotating a layer 1x2 pixels (1 pixel wide, 2 pixels tall).
What should be the result? The center of this layer should stay at the same
place.

What you want is hidden under Edit - Transform - Rotate 90 degrees. It
guarantees the same size, but it can move the layer a pixel or two to the
side.

Ivan

**Comment by B1BU** [comment]
"Edit - Transform - Rotate 90 degrees" is essencially the same as rotating with blending mode set to biubic. What I'm saying is that if I rotate it with the blending mode set to nearest neighbor the center changes, because the size of the layer changes randomly.

Before rotating:
![image](https://user-images.githubusercontent.com/44452075/216719256-45c495eb-4e4e-473e-8a7e-36e60268b10b.png)

After rotating it 90 degrees to clockwize, then 90 degrees counter-clockwise. It went from a 16x16 image to a 17x18 image.
![image](https://user-images.githubusercontent.com/44452075/216719330-aee0b1e9-aada-4918-b872-de8bafeb3b79.png)

**Comment by camoody1** [comment]
To be clear, though... while the overall image has increased in size, it's done so due to padding one empty vertical row of pixels and two empty horizontal rows of pixels. The actual colored pixels of the image that you have is not changing.

**Comment by B1BU** [comment]
> To be clear, though... while the overall image has increased in size, it's done so due to padding one empty vertical row of pixels and two empty horizontal rows of pixels. The actual colored pixels of the image that you have is not changing.

Yeah, but if I try to center the layer vertically, it will now be off center by one pixel.

**Comment by camoody1** [comment]
> > To be clear, though... while the overall image has increased in size, it's done so due to padding one empty vertical row of pixels and two empty horizontal rows of pixels. The actual colored pixels of the image that you have is not changing.
> 
> Yeah, but if I try to center the layer vertically, it will now be off center by one pixel.

Gotcha. You'd almost need to crop the empty padding off. I see what you're saying.

**Comment by B1BU** [comment]
That's what I was doing before I realized I could just set the blending mode back to biubic without it blurring the image. But if I need to resize something, I have to set it to nearest neighbor so it doesn't blur the image.

**Comment by photopea** [comment]
I have fixed it. Transparent areas are deleted ALWAYS after finishing the Free Transform (with any mode).

Edit - Transform - Rotate X degrees / Flip - should always provide pixel-perfect rotation / flip.
