### ISSUE TITLE
match colors in multiple images

### ISSUE THREAD

**Issue by tenkafubu** [photopea/photopea#5336]
I want to match colors in multiple images.
Is this same operation possible?
Photoshop
"Image"-> "Adjustments"-> "Match Color"

**Comment by photopea** [comment]
So the problem is, that you dont know how to do something in Photopea / Photoshop.

You can read www.Photopea.com/learn, or buy a book about Adobe Photoshop, or ask here: https://www.reddit.com/r/photopea
