### ISSUE TITLE
These three options related to smart object could be shorter

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#5337]
They just need to be called edit, replace and export. Can you change them?
![IMG_20230204_130636.jpg](https://user-images.githubusercontent.com/79258245/216749773-c5f50cc3-1429-45a2-ae5a-530c83b7f395.jpg)

**Comment by photopea** [comment]
I think it is important to point out, that you are not replacing just this layer (this smart object), but the actual content - all instances of the content in your document. Also, this is how it is called in Adobe Photoshop, so it might look more familiar to PS users.
