### ISSUE TITLE
Can we just get the link directly when shared a document?

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#5338]
It is not necessary to open a new tab. 
![Slice 1 (2)](https://user-images.githubusercontent.com/79258245/216752217-9ab85a7c-7591-4fac-9f1b-b36c885f452c.png)

**Comment by photopea** [comment]
Done! :)

**Comment by photopea** [comment]
the links that you see should work after copy-pasting them into a browser window. The "Open" button did not work, I have fixed it.

**Comment by photopea** [comment]
The URL should be without a slash character.

**Comment by photopea** [comment]
It is an automatic conversion. But you should use the shorter urls in practice.

**Comment by camoody1** [comment]
> When I share the link with others, they can't click on it directly to open it.
> 
> What problem is it to have a slash? I don't understand.

I agree. The link would be better with the slash.

**Comment by photopea** [comment]
Ok I have added the slash. I prefer short URLs, so it is shorter without a slash.

The shortest URL would be photopea.com#iWUXB8klS - it works, but you have to create it manually.

**Comment by MichalSZZ** [comment]
Maybe some web browsers thinks that # is an anchor to the section's ID
