### ISSUE TITLE
there's no way to tell current zoom level?

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#534]
subj

**Comment by photopea** [comment]
I know :(   But you can zoom in / out, if the current zoom is not suitable for you. You can also press View - Pixel to Pixel, to go back to 100% zoom.  Do you really need to know the zoom in practice?

**Comment by ewnjtgouierg** [comment]
thanks, 100% was what I needed
I would rename it to "Zoom 100%" - I didn't find it
menu is View, and it's only related to Zoom by being in the same section of the menu with Zoom commands, I suspect many people will fail to find it just like I did

this is considering that many things are about compromise b/c you alone building such a complex software in js, which is outstanding already, so most users, being devs themselves, probably understand and report to you only critical issues,
but ideally of course you would want to know, while doing the same ctrl+/ctrl-, when you are at 100% without having to do anything extra for this (opening menu and clicking a command)
