### ISSUE TITLE
Replace Last Filter with the filter used last time

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#5342]
I rarely use this option, because many times I forget which filter I used. In Photoshop, it works as I described in the title.

**Comment by photopea** [comment]
I have implemented it. But the label will show the name of the last filter used in the current document. however, the "global last filter" will be applied when you click it.

**Comment by camoody1** [comment]
> How about resetting it to Last Filter when switched document.

Agreed. It would be very confusing to read one thing and have it do something else.

**Comment by photopea** [comment]
I have reset it to as it worked before.
