### ISSUE TITLE
Confirm and Cancel buttons.

### ISSUE THREAD

**Issue by bluep55** [photopea/photopea#5345]
Someone yesterday suggested having floating buttons for ‘Confirm’ and ‘Cancel’ as it can be very awkward using them in their current position on mobile phone. 
Link here: https://github.com/photopea/photopea/issues/5334#:~:text=confirm%20and%20cancel-,%235334,-Closed
Unfortunately, they then closed this request.
This would be an excellent and very useful modification making these buttons much more user friendly when using on mobile phone.
Although closed, could it still be possible for you to implement this idea or something similar?
Thanks.

**Comment by photopea** [comment]
It is implemented now.
