### ISSUE TITLE
EPS export

### ISSUE THREAD

**Issue by Sherali913** [photopea/photopea#5346]
While selling on stock sites or other sites, 
They always demand .ai or .EPS . Photopea can't export both. So this is feature requested . 

I know PDF and svg also vector but we have to look globally , what's websites demand and what's clients demand , 
So exporting eps is good choice to work on. @

**Comment by photopea** [comment]
We are preparing a new vector editor, which will be able to save AI files. Please, follow us on Facebook or Twitter to now when it is out.
