### ISSUE TITLE
Lens Blur (uniform distribution) Killed With Large Radius

### ISSUE THREAD

**Issue by yikuansun** [photopea/photopea#5348]
When you try to create a lens blur effect (uniform distribution) with a large radius to create bokeh, WebGL is killed by Chrome. Maybe you could render a lower quality output when the radius is high, to prevent the process from taking too long?

**Comment by photopea** [comment]
What radius are you talking about? Could you tell me what should I do to see it happen?

**Comment by yikuansun** [comment]
Radius 85 using raster mask as depth map. Take this file, for example: https://www.photopea.com/#iU8CCvyl0 If you slide the radius back and forth a few times it will break.

This is a year-and-a-half-old issue, so I don't really care about it anymore (nowadays I just use Blur Gallery).

**Comment by kuckir** [comment]
I can not make Photopea crash :( But it says "radius too large" when over 65 pixels. Are you sure you can make Photopea crash even today? Could you tell me about your OS / Browser / GPU?

**Comment by yikuansun** [comment]
Sure. It will still crash now but it is still way better than it was back when I raised this issue.

OS: Ubuntu 22.04.5 LTS 64-bit
Browser: Brave [Version 1.70.126 Chromium: 129.0.6668.100 (Official Build) (64-bit)](https://brave.com/latest/)
GPU: Mesa Intel® UHD Graphics (CML GT2)

Not that powerful of a computer for editing.

**Comment by photopea** [comment]
okay, I will close it now.
