### ISSUE TITLE
Thumbnail Resource Format wrong size on psd files

### ISSUE THREAD

**Issue by daaaaa** [photopea/photopea#5349]
According to Photoshop file format doc [thumbnail resource format](https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577409_74450) should be like that:

| Length   	| Description                                                              	|
|----------	|--------------------------------------------------------------------------	|
| 4        	| Format. 1 = kJpegRGB . Also supports kRawRGB (0).                        	|
| 4        	| Width of thumbnail in pixels.                                            	|
| 4        	| Height of thumbnail in pixels.                                           	|
| 4        	| Widthbytes: Padded row bytes = (width * bits per pixel + 31) / 32 * 4.   	|
| 4        	| Total size = widthbytes * height * planes                                	|
| 4        	| Size after compression. Used for consistency check.                      	|
| 2        	| Bits per pixel. = 24                                                     	|
| 2        	| Number of planes. = 1                                                    	|
| Variable 	| JFIF data in RGB format. For resource ID 1033 the data is in BGR format. 	|

Whenever I save a brand new photopea file to .psd or open an existing .psd file into photopea and than save it, the property `Size after compression` seems to have the wrong value. **The value is smaller by 2 every time**.

Since the `Size after compression` value is used to perform consistency check, the PSD parser I am using refuses to parse PSD files created by photopea.

I was thinking this was a bug of the PSD parser I am currently using, but the very same behaviour is shown by another parser.
So, this led me to think that there is a small bug in photopea .psd export.
Other tools creating .psd files I tested (paint tool sai, affinity, clip studio paint) compute the `Size after compression` value of the Thumbnail Resource Format correctly.

Can you check if there is a missing +2 somewhere in setting the value for the `Size after compression` field?

**Comment by photopea** [comment]
I see, it should be fixed now :) 

to be precise, when writing a resource ID 1036, Photopea was adding zero bytes to the end, so that the size of the whole resource is a multiple of 4. It is not happening anymore.
