### ISSUE TITLE
Pressing tab jumps between value fields "within" HSB or RGB column

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#535]
In color picker,
When entering H,S,B consecutively to get a precise number, after entering value for H, hit tab, it jumps to "G", it would be better to keep them jumping/looping within same H-S-B or R-G-B value fields

**Comment by hgs54371** [comment]
Hi, have this been considered yet, the tab jump between hsb rgb field is very cumbersome, have to tab twice to get from h to s

**Comment by photopea** [comment]
It was fixed. Thanks!

**Comment by hgs54371** [comment]
But this got the shape messed up

![screen shot 2018-03-21 at 6 00 35 am](https://user-images.githubusercontent.com/36803688/37685318-0198c2a0-2cce-11e8-938b-a2906891cc5d.jpg)

Changing it from 16 to 17 helped

![screen shot 2018-03-21 at 6 01 25 am](https://user-images.githubusercontent.com/36803688/37685322-03872e12-2cce-11e8-9ddc-245cebc0fdaa.jpg)

**Comment by photopea** [comment]
Are you sure? Can you reload the page several times? Or open it in anonymous window?

**Comment by hgs54371** [comment]
This is specific to firefox, but not safari, both on mac

**Comment by photopea** [comment]
Is it better now?

**Comment by hgs54371** [comment]
Nothing changed yet

**Comment by photopea** [comment]
please, open it in anonymous window. I am still afraid you are using the old version.

**Comment by hgs54371** [comment]
I also found that it's squeezed horizontally or stretched vertically
If you click in the hue cube, the circle is stretched and below the cursor location, also in the hue strip
