### ISSUE TITLE
export different color object

### ISSUE THREAD

**Issue by ghost** [photopea/photopea#5350]
when i go to export a green object it gives me the original blue

**Comment by camoody1** [comment]
Could you record a short video showing what you're doing when this occurs? Or perhaps share your project and post the link to the PSD here so we can see what's happening?

**Comment by RizeAbove** [comment]
green bird.psd
<https://drive.google.com/file/d/1Nx3vnlg4t4LTWTAyHXJzeNHzY90ystIi/view?usp=drive_web>
thanks

**Comment by camoody1** [comment]
You actually don't need to use a Google Drive link for this. From within your project, click File -> Share -> PSD and then, after accepting a notification message, a new window will open with a shared link to your project. No need to save anywhere or share any of your drives. Just copy the link Photopea gives you and paste it here in the comments.

**Comment by photopea** [comment]
What is "exporting an object"? I have never heard of it.

**Comment by photopea** [comment]
I have to close it, because nobody is responding to me.
