### ISSUE TITLE
Scrolling Panel bar should not scroll the entire page

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#5352]
![Screenshot_2023_0206_125219.gif](https://user-images.githubusercontent.com/79258245/216886723-1fd90983-b39a-4cba-9281-aaf912fc5d8e.gif)

**Comment by MichalSZZ** [comment]
I have this problem even on the laptop's screen. I have many add-ons turned on in Photopea.

**Comment by photopea** [comment]
Even if we fix it, I am afraid there still will be problems if you try to use Photopea on a smart watch, etc.

**Comment by TheRadicalDreamer** [comment]
In order to go around that issue @nothingshiru click the Fullscreen button on the top right corner
![image](https://user-images.githubusercontent.com/11801254/217648903-f289385d-b6d5-44b3-9873-e5ecdcb9391b.png)

That the only way i can use photopea correctly when on mobile
