### ISSUE TITLE
Feature Request: Click on activated tool to open the tools menu

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#5353]
Faster response than long press for mobile user.

**Comment by photopea** [comment]
So you want the menu to be shown after every click? But then, you will have to click again elsewhere to hide it, even if you just want to select the main tool.

**Comment by photopea** [comment]
Now, if you use an eraser, you can click once to switch to a Brush tool. But with what you describe, clicking the brush tool would open a menu, and you need to click again somewhere to hide that menu.

**Comment by camoody1** [comment]
> Faster response than long press for mobile user.

I don't understand what you're asking for with this request. Could you be more descriptive of exactly what you want to happen using an example?

**Comment by photopea** [comment]
I tried it, but I think it is not intuitive. double-clicking a tool button will always open a menu. It is impossible to click the same button again to hide the menu.
