### ISSUE TITLE
[bug] copy and cut stops working

### ISSUE THREAD

**Issue by honeylump** [photopea/photopea#5354]
hi i don't know what the issue is but for some reason, after doing it a few times, copy & cut do not work anymore. paste still works but it refuses to copy or cut any new items. it's not an issue with the clipboard permissions because it works for 2-3 times once you open a document. then you have to save and close it, and reopen it for it to work again. really, really frustrating. copying and then pasting something from another app works btw, it's just from within the app.

**Comment by photopea** [comment]
Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

If it is still not working, could you tell us, what OS and a browser do you use? I really need to see it not working myself.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
