### ISSUE TITLE
I'm not able to see any layers

### ISSUE THREAD

**Issue by CrusherGaming** [photopea/photopea#5355]
![New Project](https://user-images.githubusercontent.com/90557391/217538074-6c79dc45-a50b-416c-a1f0-27e41f3256d6.png)

I'm not able to add new layers and even if I'm able to , I just simply can't see , any reason? I'm getting frustrated coz I'm not able to make a thumbnail because of this, Hope you look at the matter and let me know.

**Comment by camoody1** [comment]
On the top toolbar, click Window -> Layers.

**Comment by photopea** [comment]
Press Window - Layers.

**Comment by photopea** [comment]
See here: https://www.photopea.com/learn/workspace

**Comment by CrusherGaming** [comment]
Thankyou very much.
