### ISSUE TITLE
PDF Export - Text not displaying

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5356]
[Master Box.zip](https://github.com/photopea/photopea/files/10689863/Master.Box.zip)
In this file when i export it, i don't get the text correctly.

![image](https://user-images.githubusercontent.com/11801254/217650117-9fd54aeb-31be-4de1-a663-7f8610ff2fcf.png)

![image](https://user-images.githubusercontent.com/11801254/217650122-87669767-db1b-4d7e-aa7c-fb0c51f9fc8c.png)

**Comment by TheRadicalDreamer** [comment]
![image](https://user-images.githubusercontent.com/11801254/217651505-dbecbe77-94f4-4b7a-9f7a-76f8b2e0260b.png)

It doesn't work with any text :O 
Help!!

**Comment by TheRadicalDreamer** [comment]
![image](https://user-images.githubusercontent.com/11801254/217651907-fc180ff5-e35b-45da-a511-612cf3b2b6e9.png)


![image](https://user-images.githubusercontent.com/11801254/217652003-9eaa1e3b-241b-45be-b211-b265608b35e3.png)

**Comment by camoody1** [comment]
Remove the checkmark from "Vectorize Text". With nothing checked, the export works for me.

**Comment by TheRadicalDreamer** [comment]
I need the text to be vectorized :(

**Comment by photopea** [comment]
I am so sorry guys :( I was remaking a part of my code and did not realize an error. It is fixed now.
