### ISSUE TITLE
Publish Online feature gone

### ISSUE THREAD

**Issue by graphicjedi** [photopea/photopea#5359]
Why is the Publish Online feature missing

**Comment by MichalSZZ** [comment]
Now it is called 'Share' and is under the menu 'file -> share -> PSD'

**Comment by graphicjedi** [comment]
I tried that and it is not working for me.


Steven Ramirez

[cid:c372b3c6-21b5-4721-b9df-aba7ab827cdb]


Graphic Design / Animation Instructor
Century High School
Santa Ana Unified School District
________________________________

**Comment by photopea** [comment]
Try this https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by DevBadger10** [comment]
It works for me. File > Share > PSD. It saves it to Photopea for 6 months.

**Comment by photopea** [comment]
I have to close it because of lack of details.
