### ISSUE TITLE
"Recently used colors" in color picker or a color swatches panel

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#536]
When precise color is needed more than one time, it's more efficient to get them stored in some way, instead of having to manually enter each of them every time.

Having functions like "Recently used colors" in color picker or a color swatches panel would be good

**Comment by photopea** [comment]
Ok I added the history of colors into Color Picker. Do you need a separate Swatches panel, as in Photoshop? Or maybe some gallery of colors at the bottom?

**Comment by hgs54371** [comment]
Another row of slots that can drag n drop current color onto, for saving as swatches, 
(the history row of slots only get saved after "ok")

**Comment by photopea** [comment]
Is this how Swatches panel work in Photoshop? Are you sure it is a good idea to put it into a Color Picker?

**Comment by hgs54371** [comment]
Drag n drop into slots for saving is.

In photoshop, the swatches panel is very full featured, libraries and presets of swatches collections.

But what I usually use is just drag some wanted color into a current set or a custom set of swatch.

So for this type of usage, integrated as part of color picker is enough, without having a dedicated 

panel that takes up much space
