### ISSUE TITLE
Blur problem

### ISSUE THREAD

**Issue by HungLord** [photopea/photopea#5365]
When I exported, my pic gonna blur and that make me hate it

**Comment by camoody1** [comment]
Sounds like this could be one of those PEBCAK errors we've been seeing a lot of recently.🤔

**Comment by photopea** [comment]
Hi, could you show us what a blurred picture looks like? You can attach images to your posts.

**Comment by DevBadger10** [comment]
Wow, this issue's gone stale. @HungLord, has it started to work again? Does it still not work?

**Comment by photopea** [comment]
I have to close it because of lack of details.

@DevBadger10 actually, around 70% of people reporting bugs just mention some random thing and never respond again.

**Comment by DevBadger10** [comment]
> I have to close it because of lack of details.
> 
> @DevBadger10 actually, around 70% of people reporting bugs just mention some random thing and never respond again.

Wow! I have made some things like an esolang but noones activity using them. It must be really hard to actively maintain a project especially one of this size.
