### ISSUE TITLE
Fichier system

### ISSUE THREAD

**Issue by laurentD44** [photopea/photopea#5366]
Bonjour,

Quand je veux insérer des photos depuis d'ordinateur, un message apparait "le site ne peut pas ouvrir les fichiers de ce dossier, car il contient des fichiers systeme" ???

Comment faire pour débloquer cela ???

D'avance merci de vos retours d'expérience.
Laurent

**Comment by photopea** [comment]
Hi, sorry, I speak only English :(

**Comment by laurentD44** [comment]
Good morning,

When I want to insert photos from my computer, a message appears "the site cannot open files from this folder because it contains system files" ???

How to unlock this???

Thank you in advance for your feedback.

**Comment by laurentD44** [comment]
Good morning,

When I want to insert photos from my computer, a message appears "the site cannot open files from this folder because it contains system files" ???

How to unlock this???

Thank you in advance for your feedback.

**Comment by photopea** [comment]
It is a bug in the latest Chrome. Google should fix it soon. Until then, open files from a different directory, or use Firefox.
