### ISSUE TITLE
Ability to add "crosshair" guide based on layer

### ISSUE THREAD

**Issue by johtso** [photopea/photopea#5367]
Currently "Guides from layer" adds bounding box guidelines.

It would be really useful to be able to automatically add a pair of guidelines that cross through the centre of a shape. This would be really useful for situations where you want to have multiple concentric circles for example (but they're not in the centre of the document).

Currently I have to do some basic maths with the circle dimensions, and then manually add the guidelines.

**Comment by camoody1** [comment]
When you create a circle shape in Photopea, in the top toolbar, you can actually change the shape type from Free to Fixed Size. You can then type in the exact Height and Width of the shape that you want. One click on the canvas will then place that sized shape. For each differently sized circle, you can do this same process, but change the size that you want to achieve the concentric look. Put ONE circle per layer - it does not matter where you put each circle at this point. They can be scattered across the canvas.

Next, using both a vertical and horizontal guideline, create an intersection on your canvas exactly where you want the middle of the concentric circles to be. In the top toolbar, under View, make sure Snap is checked and under Snap To, make sure Guidelines is checked.

Now, using the Select/Move Tool, drag one of the circle layers to the guidelines intersection until the middle of the circle SNAPS into place at that intersection. The center of a circle shape will always snap to the guideline intersection. Repeat this same dragging process for each circle layer until they're all snapped into position as concentric circles.

**Comment by photopea** [comment]
Did you try the align buttons, which are at the top (of the Move tool)?

**Comment by MichalSZZ** [comment]
There is such a function in Photopea already.

Menu: Window -> More -> Guide Guy. 
This is a very helpful addon for creating guides.

You can do Grids but you can also add guides according to the layer.
But you have to do one little step: Click with CTRL (Cmd on mac) in your layer thumbnail (to creat the selection from shape).

Now use these icons at the bottom (2nd from the left and 2nd from the right)
![obraz](https://user-images.githubusercontent.com/38118273/219068709-9fd006c1-696a-48a2-8010-992d3cf13361.png)

**Comment by johtso** [comment]
Thanks so much for all the input! "Guide Guy" is super useful, definitely wouldn't have found it on my own, and most certainly wouldn't have known to select the shape like that!

Also handy to be able to quickly centre the two layers relative to each other using the move tool.
