### ISSUE TITLE
What to do when transformations rectangle doesn't match size of shape?

### ISSUE THREAD

**Issue by johtso** [photopea/photopea#5368]
I've found that a bunch of circles that I've made have a transformation rectangle that is larger than the circle, and the circle isn't centred within it.

I think this most likely happened due to me copying a circle that had some text attached to it.

Is there some way that I can get the transformations rectangle to be recalculated so that I can get snapping and the origin for scaling to be correct?

![image](https://user-images.githubusercontent.com/830800/219117493-d92ec739-ce65-48a9-b031-32eff4136d4e.png)

**Comment by camoody1** [comment]
This is a cool looking design, btw. I like it. Could you share the PSD so I can take a look at it to see what I can do? You can share the whole file by clicking File -> Share -> PSD and then dropping the link to the shared location here.

**Comment by johtso** [comment]
@camoody1 cheers! so I just realised that I can move the centre point of the transformation rectangle, which I can snap to the guideline I'm using.. and then use alt while scaling to keep it centred.

It would still be great to be able to get the box to fit the circle so that everything behaves in a more expected way though..

Here's a share: https://www.photopea.com/#iaDAmaxcr.psd

**Comment by MichalSZZ** [comment]
It is because of your mask for each layer.
Look - I made a selection from the mask to show you the problem:
![obraz](https://user-images.githubusercontent.com/38118273/219175646-a544fc8d-b1f7-4937-8bb0-07974b1de1cc.png)

You have to go to Reddit's Photopea Channel and there ask about your troubles. Here is a place for writing about bugs and improvements.

**Comment by photopea** [comment]
I feel so happy to see you guys explain stuff to each other :)

**Comment by camoody1** [comment]
> @camoody1 cheers! so I just realised that I can move the centre point of the transformation rectangle, which I can snap to the guideline I'm using.. and then use alt while scaling to keep it centred.
> 
> It would still be great to be able to get the box to fit the circle so that everything behaves in a more expected way though..
> 
> Here's a share: https://www.photopea.com/#iaDAmaxcr.psd

You definitely found the best solution for your issue. Well done. The other way to possibly deal with this (if you didn't want to move the center point of the transform box) would be to draw a temporary "throw away" circle that was larger than all your other layers and encircle them. Then, when you chose to Transform that group, the largest part of the group would always be that "throw away" circle and not your text or masks. Then, once you were done with the image, you could just delete the temporary circle.

Dirty, but it works. :)
