### ISSUE TITLE
Step backward (alt-ctrl-z) not working on mac (option-command-z)

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#537]
Can access with menu, but keyboard not working
Also step forward (shift-cmd-z) only worked in text field, not outside text field

**Comment by photopea** [comment]
And what about Alt-Command-Z ?

**Comment by hgs54371** [comment]
The alt and option is on the same key on a mac keyboard, but nothing happens when pressing them

**Comment by photopea** [comment]
Please, go here: http://jsfiddle.net/p45f44zb/3/

Click into the bottom right part. It should display all keys, that are pressed on the keyboard. Try press Alt-Command-Z . What do you see?

**Comment by hgs54371** [comment]
(alt/opt-cmd-z) shows ["alt","meta","ω"]
(shift-cmd-z) shows ["shift","meta","z"]

**Comment by photopea** [comment]
Is it some MacOS shortcut, that Alt+Z prints ω ?

**Comment by photopea** [comment]
Can you please update your MacOS and your browser? Just to make sure that we are not dealing with some ancient MacOS bug?

**Comment by hgs54371** [comment]
Both are latest versions, (alt-z) in text field creates Ω, alt is used to create many symbols

**Comment by photopea** [comment]
Does it print ["alt","meta","ω"] always, no matter in what order you press the keys?

**Comment by hgs54371** [comment]
(cmd-alt/opt-z) shows ["meta","alt","ω"]
(cmd-shift-z) shows ["meta","shift","z"]
I actually prefer to press cmd first in these shortcuts

**Comment by photopea** [comment]
No, I mean what if you press (cmd-alt/opt-z)  in 6 different orders.

**Comment by hgs54371** [comment]
z-alt-cmd show ["z","alt","ω","meta"]
z-cmd-alt show ["z","meta","alt","ω"]
cmd-z-alt show ["meta","z","alt","ω"]
alt-z-cmd show ["alt","ω","meta"]

Usually only cmd-alt-z this order is used

**Comment by hgs54371** [comment]
Hi, how is this issue progressed for now, the step for/backward function still only usable through top menu

**Comment by photopea** [comment]
It should be fixed now (Cmd - Alt - Z   should go backwards on Mac OS, too).

**Comment by hgs54371** [comment]
Both still not working for/backward

**Comment by photopea** [comment]
So Forward (Cmd - Shift - Z) worked before and now it does not work?

**Comment by hgs54371** [comment]
Forward only work in text field, just like the first comment in this post, nothing has improved

**Comment by photopea** [comment]
Are you sure? Can you reload the page?

I think we should wait a little. Maybe in the future, we will make more money, so we will buy a Mac computer and test it by ourself. Such testing "on distance" is really hard to do :(

**Comment by hgs54371** [comment]
The basic pressing method of cmd-opt-z and cmd-shift-z do nothing, but I found holding cmd-z(this will cause flashing between undo/redo very fast) Then at this time press opt/shift will do back/forward in a very quick fashion(can't just one step in a press)
