### ISSUE TITLE
Export image size stuck bug

### ISSUE THREAD

**Issue by hyperknot** [photopea/photopea#5370]
I tried to make an export, entered some values for the image size, then cancelled the dialog.

Now, no matter what I do, every time I get to the export dialog, those non-original pixel values are filled in. Actually if I put some invalid values, like abc, click cancel and open Export again, it is filled in.

This is obviously a bug, it should revert to the original values every time I open the export dialog.

<img width="235" alt="image" src="https://user-images.githubusercontent.com/494223/219204583-a61f56c3-e2d7-4a2f-98c0-7970c316f731.png">

**Comment by photopea** [comment]
Could you try to clear the cache of Photopea? It should be fixed then.

**Comment by hyperknot** [comment]
Nope, it's still present, even after cleaning cache.

**Comment by photopea** [comment]
What if you use Photopea in the Incognito window?

**Comment by camoody1** [comment]
Mine does this, too.

https://user-images.githubusercontent.com/73725653/219377742-036d3c39-99ed-4a3a-8320-47b9faa9b726.mp4

**Comment by photopea** [comment]
It should be fixed now. A "nonsense value" will be converted to a number 1.

**Comment by hyperknot** [comment]
But it should always revert to the original value, no matter what happened
before, not?
