### ISSUE TITLE
How do I change stroke type?

### ISSUE THREAD

**Issue by YumYummity** [photopea/photopea#5371]
How do I change the stroke feature for text so that the text is outlined?
The current stroke type is inner/center, meaning that typing with stroke enabled reduces the text size itself and causes the stroke to take up the space. What I want is the outer stroke, meaning that the text will be outlined with whatever color the stroke is.

**Comment by photopea** [comment]
I am afraid I do not understand. How do you set the stroke of a text? Could you share a screenshot?

**Comment by camoody1** [comment]
Why not jusr type your text normally (without a stroke) and then apply a stroke after the fact using a Layer Style -> Stroke effect? The layer style window allows you to choose whether the stroke is Outside, Center or Inside.

I'm not sure what you're doing currently, but the process I described works easily and well.🤷🏽‍♂️

**Comment by YumYummity** [comment]
> Why not jusr type your text normally (without a stroke) and then apply a stroke after the fact using a Layer Style -> Stroke effect? The layer style window allows you to choose whether the stroke is Outside, Center or Inside.
> 
> I'm not sure what you're doing currently, but the process I described works easily and well.🤷🏽‍♂️


That worked, thank you! (I was just selecting the stroke checkbox next to where you select the color.)

**Comment by MichalSZZ** [comment]
@YumYummity 

Be carefoul with this type of stroke in the top toolbar. There isn't such a feature in Photoshop (background for the text too).

Someone who will open your file in PS, will have no possibility to modify it in PS.

:)

**Comment by camoody1** [comment]
Ohhhhh... I see what you were doing. Yeah, that Stroke effect you had selected will always be the "center" type stroke. It's the same checkbox you'd find when drawing shapes where you're given Fill and Stroke options.

Hope the Layer Style option helps you out. Play around with the Drop Shadow option, too. It's a great affect.

**Comment by YumYummity** [comment]
> @YumYummity
> 
> Be carefoul with this type of stroke in the top toolbar. There isn't such a feature in Photoshop (background for the text too).
> 
> Someone who will open your file in PS, will have no possibility to modify it in PS.
> 
> :)

Thanks for the warning, though I doubt anyone will need to open it in photoshop. Although, I could just rasterize it if it doesn't need to be edited any further.

**Comment by YumYummity** [comment]
As someone without photoshop, this is kinda useful info lol.
