### ISSUE TITLE
Bug Fix: The Gallery window missing search box

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5373]
On the mobile version of Photopea, the Gallery window does not have a box in which to type your search text when in portrait mode. You have to rotate into landscape mode in order to be able to search for an image.
![SmartSelect_20230216_090058_Edge](https://user-images.githubusercontent.com/73725653/219387513-b6bf9615-4297-4445-b806-a36a2236550e.png)

![SmartSelect_20230216_091116_Edge](https://user-images.githubusercontent.com/73725653/219388355-4adb752a-d797-436c-8766-71b504853988.jpg)

**Comment by photopea** [comment]
You should enlarge the plugin to see a search box. This plugin can not adapt to any screen size.

**Comment by camoody1** [comment]
Ah, yes. Duh. I didn't even realize I could drag that window any wider. Just a few pixels more is all that was needed.

Thanks
