### ISSUE TITLE
Make the default keyboard a numeric keyboard

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#5374]
For most text boxes only numbers are valid, making the default keyboard for those text boxes numeric would be easier to use for mobile users. Setting number as the type of input achieves this effect.

**Comment by camoody1** [comment]
Happy time game changer if possible. 😁

**Comment by prak899** [comment]
what is this issue for? Can you explain more details about the issue.

`

> _**### @Admin**_

`

**Comment by photopea** [comment]
I have implemented it. But it will not work in Safari (= all iOS browsers), see https://caniuse.com/input-inputmode
