### ISSUE TITLE
displacement filter bug

### ISSUE THREAD

**Issue by almousa1990** [photopea/photopea#5375]
Hello,

I have the following issue with the displace function of the smart filter:
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/4084573/219492927-f8cc93d5-80ea-4394-a294-f2bfe539b33d.png">

Steps to reproduce the issue:
1. Download the PSD files from: https://mockups-design.com/free-t-shirt-mockup
2. disable then enable the smart filters.

**Comment by photopea** [comment]
This filter works differently in Photoshop than in Photopea. You need to re-set the options of the filter.

Adobe Photoshop opens a file from your computer and uses it as a displacement map. But a website can not open access files on your computer.

**Comment by photopea** [comment]
It is impossible to edit your design in Adobe Photoshop. You will also need to tell Photoshop the path to a different PSD file: "disp.psd".  It is all described in "About_Displacement.txt".

To do it in Photopea, just drag-and-drop the "disp.psd" into the main PSD, double-click the "Displace" filter and select a displacement map.

The author of your PSD could make it much easier by enabling "Embed File Data In Smart Object" in the Displacement filter in Adobe Photoshop - https://www.bwillcreative.com/wp-content/uploads/2022/08/how-to-use-a-displacement-map-in-photoshop-19.jpg
