### ISSUE TITLE
Error file psd

### ISSUE THREAD

**Issue by AnnaAlek** [photopea/photopea#5376]
Uploading a .fig file
I save the file in the psd
The file that is downloaded from photopeach does not open
From other sites, files are opened and edited

I have a paid subscription, the service does not work

![image](https://user-images.githubusercontent.com/125646955/219599048-4ed19385-d7ba-4c60-80a5-8d9945027b70.png)

**Comment by photopea** [comment]
I am very sorry, it should be fixed now. Open your FIG file in Photopea again, and export a PSD again. Or even open your PSD and re-save it as a PSD. The new PSD should work in Adobe Photoshop now.
