### ISSUE TITLE
Text editing problem

### ISSUE THREAD

**Issue by San9er** [photopea/photopea#5378]
When editing a finished project, I want to edit the text on a specific layer, but when I try to edit the mode, it seems to turn on, but the text is not edited. There are no layer locks.

**Comment by bluep55** [comment]
Make sure you are on the Type Tool 'T' before clicking on the type layer you want to edit.
If you are not on the type tool, you will need to double click on the type layer to make it editable.
Then place your curser on the text you want to edit.
If you have rasterised the text layer it is no longer editable.

**Comment by San9er** [comment]
I’m doing everything right, it feels like there is a * padlock *, but in fact it’s not there, I even tried to press the * padlock * 2 times. Nothing helps.

**Comment by camoody1** [comment]
This has the feeling of a standard PEBKAC error. 🤔

Would you mind sharing a link to your project so we can take a look at exactly what you're seeing? Or perhaps record a short video of you doing exactly what you're trying so we can see what's happening?

**Comment by San9er** [comment]
I figured everything out, some kind of "transformation control" was included. Thanks for the help)

**Comment by camoody1** [comment]
> I figured everything out, some kind of "transformation control" was included. Thanks for the help)

I've never heard of "transformation control". 🤷🏽‍♂️ Glad you got it figured out!

**Comment by photopea** [comment]
I guess you have fixed it!
