### ISSUE TITLE
Incorrect description of 'New Adjustment Layer' icon.

### ISSUE THREAD

**Issue by bluep55** [photopea/photopea#5380]
Nothing major, but when hovering over the 'New Adjustment Layer' icon with the mouse pointer it displays as 'Add raster Mask'.

![Snapshot_42](https://user-images.githubusercontent.com/118609932/219762928-eebe86e3-dd48-44f7-a2d6-4d272b7e00a4.jpg)

**Comment by photopea** [comment]
fixed, thanks!

**Comment by bluep55** [comment]
👍
