### ISSUE TITLE
image copying to and from outside sources

### ISSUE THREAD

**Issue by xXbombyplushXx** [photopea/photopea#5381]
Hey literally just joined and started using this after pixlr collapsed in on itself, and i wanted to know if there was anyway you guys could add the ability to copy and paste images from outside sources. So my reasoning for this is that i dont want to waste storage space trying to make shitposts on google slides where monstro from the binding of isaac wields an ak-47 and sets off to fight waluigi at the top of space mountain. I got really used to being able to copy and paste edited images..

Ya know, just a suggestion but yea.

**Comment by camoody1** [comment]
Just to be clear... Are you just asking to be able to right click on an image from a website, choosing to copy to clipboard, then opening Photopea and pasting directly into a new project? If that's what you're wanting to do, Photopea definitely already allows that.

Perhaps I'm misunderstanding exactly what you're wanting to do?

**Comment by photopea** [comment]
If you copy an image outside Photopea, you can paste it into Photopea (using Ctrl+V, or Edit - Paste).

If you copy something in Photopea (using Ctrl+C, or Edit - Copy), you can paste it outside Photopea. What is the problem?
