### ISSUE TITLE
Copy and pasting from another tab of photopea removes part of the image

### ISSUE THREAD

**Issue by TosNoomRepo** [photopea/photopea#5383]
![2023-02-19-17-19-35](https://user-images.githubusercontent.com/118944285/219978739-c1986544-7e36-4342-b63c-05f5f1d1bca3.gif)

**Comment by photopea** [comment]
Couls you share your PNG image with me, so that I try it myself?

**Comment by TosNoomRepo** [comment]
![Screenshot_2-removebg-preview](https://user-images.githubusercontent.com/118944285/220191496-3cb8c791-b4a9-48b0-9a0f-1d58c995ef26.png)

**Comment by photopea** [comment]
I can not reproduce it :( Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by TosNoomRepo** [comment]
That's weird. I'll try again in incognito mode. Thanks for trying, though!

**Comment by photopea** [comment]
The only difference between Photopea in Incognito and in a normal mode is that in Incognito, your browser extensions are disabled.

So you have one or more browser extensions which are breaking how Photopea works.
