### ISSUE TITLE
Hue slider default value should be 0 instead of 100

### ISSUE THREAD

**Issue by niclaswue** [photopea/photopea#5385]
Hi there,

first time using photopea for me. I wish I knew this existed earlier. One minor detail I noticed, which should be an easy fix is the default value for the Hue slider in the adjustment layer settings. As the value is relative, the default should be 0, however when I double click the slider it jumped to 100.

Thanks for fixing.

**Comment by photopea** [comment]
We are planning to remove a double-clicking feature. Please, just enter the value that you want. There is also a "Reset" button.

**Comment by DevBadger10** [comment]
@niclaswue Did Photopea's advice help? If so, please close this issue.
