### ISSUE TITLE
.car file will always say "Unkown file format: "FRAC"

### ISSUE THREAD

**Issue by Anth0nyAnderson** [photopea/photopea#5386]

**Comment by photopea** [comment]
What kind of file is it? Are there any programs in the world which can open CAR files? There are many formats which Photopea can not open, e.g. MP3 sound, etc.

**Comment by DevBadger10** [comment]
<img width="583" alt="image" src="https://user-images.githubusercontent.com/104037142/220806254-23c30d2f-8de7-47a9-8d2e-09fa73514b8d.png">
I'm thinking OP might be talking about going into it from the Open button? If this is the case, then @Anth0nyAnderson will need to just extract it.

**Comment by DevBadger10** [comment]
Actually, I found some more information. I added 'image' to the end of my Google and got this:
<img width="508" alt="image" src="https://user-images.githubusercontent.com/104037142/220809786-8d89ec06-cb99-4526-9227-61abbbf38f89.png">
It seems to be a real image format. I think that maybe OP should just use a .car to .psd file converter, cause I'm sure on of those exist. It seems like a really obscure file format that would only be necessary for @photopea  if you felt like it would be useful.

**Comment by photopea** [comment]
I would need the original author to tell us what he means by car files.

**Comment by Anth0nyAnderson** [comment]
It's like a nascar scheme template, and i'm trying to extract it into a .psd

**Comment by photopea** [comment]
Could you share your file with us?

Who gave you that file? Did the person tell you what program you should use to open it?

**Comment by DevBadger10** [comment]
I cannot find anything online relating to it (at least from a google), so, as Photopea said, the fe is needed to find out exactly what format it is.

**Comment by DevBadger10** [comment]
A search for the FRAC extension showed that it is bound to the Tinker program for molecular design. I think this may be a mix-up in Photopea's file opening engine. Is it supposed to be used with Tinker, @Anth0nyAnderson?

**Comment by Anth0nyAnderson** [comment]
> A search for the FRAC extension showed that it is bound to the Tinker program for molecular design. I think this may be a mix-up in Photopea's file opening engine. Is it supposed to be used with Tinker, @Anth0nyAnderson?

i believe so

**Comment by Anth0nyAnderson** [comment]
> Could you share your file with us?
> 
> Who gave you that file? Did the person tell you what program you should use to open it?

1. I can't really give you the file since it says "we don't support that file type" but, i can give you the website where i got it from
2. found it myself 
3. ↑

**Comment by DevBadger10** [comment]
> > Could you share your file with us?
> > Who gave you that file? Did the person tell you what program you should use to open it?
> 
> 1. I can't really give you the file since it says "we don't support that file type" but, i can give you the website where i got it from  https://stunodracing.net/index.php?resources/daniel-suarez-2023-freeway-insurance-camaro-auto-club.16292/
> 2. found it myself
> 3. ↑

The fact that Photopea doesn't support it shouldn't affect you uploading it to GitHub? If you have the file downloaded, then can't you drag it into a comment? Or drag it from the site to GitHub? We want the **base image file**.

**Comment by Anth0nyAnderson** [comment]
> > > Could you share your file with us?
> > > Who gave you that file? Did the person tell you what program you should use to open it?
> > 
> > 
> > 
> > 1. I can't really give you the file since it says "we don't support that file type" but, i can give you the website where i got it from  https://stunodracing.net/index.php?resources/daniel-suarez-2023-freeway-insurance-camaro-auto-club.16292/
> > 2. found it myself
> > 3. ↑
> 
> The fact that Photopea doesn't support it shouldn't affect you uploading it to GitHub? If you have the file downloaded, then can't you drag it into a comment? Or drag it from the site to GitHub? We want the **base image file**.
i assume you didn't get what i mean, but what i'm trying to say is that GitHub doesn't allow the .car file

**Comment by DevBadger10** [comment]
Ooooh ok that makes sense. I'm not at my PC rn so can't look for it rn but I will in a sec

**Comment by photopea** [comment]
From what I have found so far, there is just one program in the world which can open these files. It is a videogame "Papyrus Studio's NASCAR Racing 2003 Season simulation". People create .CAR files also inside this game, see https://www.youtube.com/watch?v=WM-KZxRSdSg . There is no other program in the world which can work with these files.

I was able to detect two images in these files, but they have some kind of compression, similar to DEFLATE or LZW, but I can not figure it out.

However, some of them have no compression (you can open this one in Photopea)
[MTJ195002023.cup.zip](https://github.com/photopea/photopea/files/10819613/MTJ195002023.cup.zip)

**Comment by Anth0nyAnderson** [comment]
I can't really download NR2003 since it's for windows, and i'm using a chromebook, but thank you for trying to help me I appreciate it @photopea

**Comment by photopea** [comment]
So what exactly do you want to do after opening your file in Photopea? What is your goal?

**Comment by Anth0nyAnderson** [comment]
I want to use the scheme in an another game

**Comment by camoody1** [comment]
> From what I have found so far, there is just one program in the world which can open these files. It is a videogame "Papyrus Studio's NASCAR Racing 2003 Season simulation". People create .CAR files also inside this game, see https://www.youtube.com/watch?v=WM-KZxRSdSg . There is no other program in the world which can work with these files.
> 

I had this game. And it was awesome.

I miss old, fun games.

**Comment by photopea** [comment]
I am closing it, as we can not implement every proprietary format of every existing game. Games should use open formats like JPG or PNG for graphics.
