### ISSUE TITLE
WebGL creates threshold lines.  They disappear and go back to normal when I disable WebGL

### ISSUE THREAD

**Issue by Poke-Chop5678** [photopea/photopea#5387]
OpenGL OFF
![openGL off](https://user-images.githubusercontent.com/126006267/220417453-ab938f99-1454-4849-a9ef-55bafbc2f520.JPG)

OpenGL ON
![openGL on](https://user-images.githubusercontent.com/126006267/220417456-970e67cb-8011-4b58-b617-879b5315f712.JPG)

This started about 4 or 5 months ago.

**Comment by photopea** [comment]
Do you mean More - WebGL? What web browser (and version) are you using? What operating system is it?

**Comment by Poke-Chop5678** [comment]
So sorry.  You are correct.  It is WebGL.  I am using Chrome.

**Comment by photopea** [comment]
What version of Chrome is it? Is it a stable release or Chrome Canary?

Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by Poke-Chop5678** [comment]
I am on  Chrome stable Version 110.0.5481.104 (Official Build) (64-bit)

I tried the options from the link including incognito mode.  No luck. :(

I also found out that it seems to only cause this problem reading PSD
files.  FYI - All PSD files were created from Photopea

If I open another file type such as jpeg it's fine.

**Comment by photopea** [comment]
I believe Photopea works correctly, so there is a bug in your GPU drivers. Could you update them? Or use different ones?

Also, you did not mention, what operating system do you use. Also, did you try to restart a web browser? Does it happen in different browsers, too?

**Comment by Poke-Chop5678** [comment]
First of all, Thank you so much for your patience and time.  It is really
appreciated.  Here are the answers:

Windows 10.
I restarted and actually reinstalled chrome, edge, and firefox browsers.
All browsers exhibit the same problem.

I will reinstall GPU drivers and try that.  I will let you know if it is
successful.

**Comment by photopea** [comment]
You said it happens only for PSD? Could you save that PSD as a PNG and open that PNG, does it still happen? Also, is your PNG in a CMYK mode (see Edit - Mode).

**Comment by Poke-Chop5678** [comment]
I saved as a png and has no artifacts.  Perfectly normal.  PSD and PNG both
are in RGB mode.  If I switch the PSD from RGB to CMYK the artifacts are
still there.  I will try the GPU Driver tomorrow.  I have an Nvidia 3060.

**Comment by photopea** [comment]
Please, send me a PSD, for which it happens, to support@photopea.com .

Notice, that you were sending emails to some random gihtub address, do not send your PSD file there, send it to support@photopea.com .

**Comment by photopea** [comment]
I guess we have fixed it.
