### ISSUE TITLE
Text To Image hangs

### ISSUE THREAD

**Issue by DevBadger10** [photopea/photopea#5388]
Text To Image hangs when you try to run it without internet, and makes the software require a restart.

Edit: It also cannot be cancelled, because sometimes I accidently create it when it shoudnt' which makes it waste credits.

**Comment by photopea** [comment]
Could you tell me what should I do to see it happen? Could you share your PSD file where it happens?

**Comment by DevBadger10** [comment]
I will give you a recording. Also, I think the main problem is the addition of a 
"Stop Generating" button, cause I used Chrome's Install feature for it, which most other people won't use. Also, GitHub is saying it can't process the recording, sorry. You can reproduce it via going to Photopea, disconnecting your computer from the internet, then pressing Go on the text to image. As there is no stop button, this softlocks the text to image system. I also sometimes type in the wrong prompt, and it would be nice if I didn't have to waste credits when I mistakenly type something in.

**Comment by photopea** [comment]
I thought it is obvious, that Text-to-image can generate billions of various images, it has a knowledge of what each thing / person / animal in the universe looks like. Such a program must be tens of gigabytes in size. So it probably does not run on your computer and runs elsewhere.

**Comment by DevBadger10** [comment]
> I thought it is obvious, that Text-to-image can generate billions of various images, it has a knowledge of what each thing / person / animal in the universe looks like. Such a program must be tens of gigabytes in size. So it probably does not run on your computer and runs elsewhere.

Yes if course I know that I just thought maybe before performing it it might be able to ping google to make sure it won't hang as that makes me have to restart and lose potentially necessary history. I only have an issue with it hanging. I have dabbled in AI and know how big they could get.

**Comment by photopea** [comment]
I have fixed it. If you are offline, clicking the button will just tell you to get online.
