### ISSUE TITLE
Without releasing cmd, press between - + to toggle zoom in/out

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#539]
For now every (cmd+) respond the same as (cmd-) after a first (cmd-), you can't quickly toggle zoom in/out without releasing the command(ctrl) for every new zoom action (in both direction)

**Comment by photopea** [comment]
I think it is related to bugs in Safari, that we found earlier.

**Comment by hgs54371** [comment]
Which one do you mean, the step for/backward one ? 

This issue is in firefox also, not safari specific

**Comment by photopea** [comment]
I think it is because of some MacOS key combinations, which generate different characters instead of plus / minus.
