### ISSUE TITLE
Animated GIF always in forever

### ISSUE THREAD

**Issue by Sudipta22l** [photopea/photopea#5392]
Animated GIF always animating if you set repeat only 1 or 2 times it will not works, it's always forever mode..

**Comment by photopea** [comment]
How do you play your GIF? What program do you use? It could be a bug in your program, such that it plays every GIF forever.

Can you find a GIF anywhere in the world, which will be played only once or twice in your GIF player?

**Comment by DevBadger10** [comment]
Some GIF players play it for the amount of times it has been set, then loop it, so it might be repeating one or two times, the GIF program just loops it after that's done. 

As Photopea said, find a different GIF that plays one to two times. 

I think you should also google if there is a looping option on your program, as it may be turned on by default and you didn't notice it.

Another possible solution would be testing it out in a different GIF player.

I hope this helps you, @Sudipta22l.

**Comment by photopea** [comment]
I have to close it because of lack of details.
