### ISSUE TITLE
How do you draw the pixels on screen

### ISSUE THREAD

**Issue by therealbluepandabear** [photopea/photopea#5394]
Hello,

I know Photopea is not open source, but what is the methodology you use to draw pixels on screen?

Do you use the `fillRect` function, or do you use `putImageData`-type functions?

I'm thinking of creating my own sort of Photoshop-like app, so I would truly appreciate if you could give me some more info as to how this all works, at a very high level.

You're amazing btw, I honestly don't care that it's not open source, you deserve to make a profit off your hard work! Don't let the FOSS nuts bother you.

Regards,
thebluepandabear

**Comment by photopea** [comment]
Hey, our image is an array of bytes. We draw pixels by giving different values to each byte. We render the image on a canvas using Context.putImageData().

**Comment by therealbluepandabear** [comment]
> Hey, our image is an array of bytes. We draw pixels by giving different values to each byte. We render the image on a canvas using Context.putImageData().

Thanks for the reply.
