### ISSUE TITLE
FR: Remove Transparent Pixels of Threshold

### ISSUE THREAD

**Issue by DevBadger10** [photopea/photopea#5395]
After performing a colour to alpha, there are some undesirable transparent pixels left behind. I think a function that deletes these when their Alpha is under a certain threshold you set would be very useful.

**Comment by DevBadger10** [comment]
Ive seen their is a raster option, but I think a threashhold would be nice.

**Comment by photopea** [comment]
What exactly do you mean? It would be so cool if you attached a screenshot (which tells more than 1000 words).

**Comment by DevBadger10** [comment]
Hold up I can't get one rn I am on a trip I can in like 3 days or so

**Comment by DevBadger10** [comment]
I'll send a screenshot of the transparent pixels showing, a video of me making them show with colour to alpha and stuff also.

**Comment by photoeditorlover** [comment]
> I'll send a screenshot of the transparent pixels showing, a video of me making them show with colour to alpha and stuff also.

Is this what you meant. I mean some users are still using it though. There tons of option available other than using transparent pixels of threshold. 



https://i.stack.imgur.com/Ly0BW.png

**Comment by photopea** [comment]
I think I know what you mean. I have fixed it.

Now, after the Color to Alpha filter, the new opacity of each pixel will never be higher than its old transparency.
