### ISSUE TITLE
Variables - Export PDF in one file

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5396]
![image](https://user-images.githubusercontent.com/11801254/221285606-f097064d-347a-4c56-893c-81e0beb2206e.png)

Can we have the option to export in one PDF file when we use variables?

**Comment by TheRadicalDreamer** [comment]
I mean to have one pdf with multiple pages with all the variables printed. One in each one.

**Comment by TheRadicalDreamer** [comment]
Can this feature be applied? :)

**Comment by photopea** [comment]
It would be very hard to make. But what if you generate many PDF files, and then, use File - Automate - PDF presentation, to connect them together?

**Comment by TheRadicalDreamer** [comment]
I use I love PDF to do it.

Yes

It only more comfortable to have it outputted on one pdf directly from
Photopea
