### ISSUE TITLE
How to remove multiple anchors

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5397]
How can i select multiple anchors...
![Screenshot 2023-02-24 22 19 51](https://user-images.githubusercontent.com/11801254/221328245-d5114388-92aa-4ad8-961f-e2e5efd83a68.png)

...and remove them without leaving the shape open?
![Screenshot 2023-02-24 22 20 05](https://user-images.githubusercontent.com/11801254/221328242-8c95a0e1-211e-44e9-b6e9-4a02e7e57126.png)

Here is the PSD:
[fungus.zip](https://github.com/photopea/photopea/files/10829965/fungus.zip)

Because right now the only way i know i one by one with right click of Shift+Pen tool

**Comment by TheRadicalDreamer** [comment]
Also, if i have this shape opened
![image](https://user-images.githubusercontent.com/11801254/221328316-349a521d-be6f-40f7-807a-56d301977c16.png)

How can i close it? Pen tool? a special menu where you can close all shapes??

**Comment by DevBadger10** [comment]
Now, I don't use @photopea to this degree, but I just wanna say that that looks amazing, and I hope you find a way to close them so you can have that stunning image.

**Comment by photopea** [comment]
I think in Photopea, it works exactly as in Adobe Photoshop.

If you press Delete, it makes the path open. You need to right-click and choose "Delete Anchor Point", or click it with a Pen tool.

Let me know if you find something working differently than in Photoshop.
