### ISSUE TITLE
Why is so difficult to delete anchor points with pen tool?

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5398]
I am not able to select them to remove them :(

A little video explaining:
[Screen recording 2023-02-24 22.25.30.webm](https://user-images.githubusercontent.com/11801254/221328572-f554ca2c-d254-44a7-9513-12c6328c2c96.webm)

PSD:
[little frame.zip](https://github.com/photopea/photopea/files/10829983/little.frame.zip)

**Comment by camoody1** [comment]
You should be using the Direct Select Tool to select the individual points of an existing path. I was able to open your PSD file, choose the Direct Select Tool, and immediately select any point on the path that I wanted and drag them around. What you've got there is one giant "loop" with one side sitting on top of the other.
![SmartSelect_20230224_224827_Edge](https://user-images.githubusercontent.com/73725653/221334576-d6ab0d9e-b9e6-45d1-a6f9-bc1ec4a69296.jpg)

**Comment by TheRadicalDreamer** [comment]
Thanks, but i was trying to remove one with the pen tool.

Can you do that? Because i am not able to click the existing ones

**Comment by camoody1** [comment]
Yes. Just as I said, I used the Direct Select Tool, selected the point I wanted, and clicked DELETE on my keyboard. I then switched to the regular Pen Tool to close the path that my deletion had created.

**Comment by camoody1** [comment]
I'll be honest with you...

I've been trying to create a video for you to follow for the past half hour. I'm able to easily delete a point without issue. But I cannot for the life of me figure out how I reconnected the two points after I deleted the other. I've been able to randomly reconnect them three times, now, but I am totally unable to recreate that on command. I have no idea what string of clicks I did to make it happen. It truly makes no sense. 🤷🏽‍♂️

**Comment by camoody1** [comment]
I found this post on Reddit from a year ago. The first answer in the thread is from Ivan, the developer of Photopea. I don't know if he ever implemented this functionality. I would LOVE to know how I accidently did it three separate times, though. 😆

https://www.reddit.com/r/photopea/comments/n4c6du/how_to_connect_two_separate_vector_lines_at/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

**Comment by photopea** [comment]
You can delete any anchor point with a Pen tool just by clicking at it.

These tools in Photopea should work the same as they work in Adobe Photoshop. So please, just search for how to do your thing in Photohsop.

**Comment by camoody1** [comment]
@TheRadicalDreamer Okay, sir... after all that, I've finally figured it out. 😆

Here's a video showing me deleting the end point and reconnecting the two points prior to the deleted on to re-close the path.

https://user-images.githubusercontent.com/73725653/221346070-91938823-9078-4ab8-839d-2603742d2f27.mp4

**Comment by TheRadicalDreamer** [comment]
There is a little difference.

When i select multiple anchors with the Direct select tool and then hit the P key to change the tool to pen all the anchors get deselected.

So, as now, the only way to keep them selected is to change the tool with the cursor.

If that could be changed i will be really grateful :)

**Comment by camoody1** [comment]
> There is a little difference.
> 
> When i select multiple anchors with the Direct select tool and then hit the P key to change the tool to pen tool, all the anchors get deselected.
> 
> So, as now, the only way to keep them selected is to change the tool with the cursor.
> 
> If that could be changed i will be really grateful :)

Just so we're clear...

You agree that you now know how to easily select multiple points in a path and delete them with the path automatically "closing" itself. Yes? That was your initial issue.

Your NEW problem is that once you've selected those points that you want to delete, you don't like that you have to use the mouse cursor to change to the Pen Tool... you want to be able to just hit the "P" key on your keyboard. Because hitting "P", now, just deselects all the points that you have selected. Is that correct?

**Comment by camoody1** [comment]
>Do you want me to create another issue?

No, no. I just wanted to make sure I there was nothing else I could help you with. The problem you have left is strictly for the developer to handle.

**Comment by TheRadicalDreamer** [comment]
@photopea in photoshop you can select anchor points with the direct select tool, then hit P and change to pen and they will remain selected:

![image](https://user-images.githubusercontent.com/11801254/221937547-4af977fb-5499-4435-9bce-77674b150e74.png)

**Comment by photopea** [comment]
So I just checked, and Photopea literally contained a piece of code, such that if you pressed or released P when the pen tool was selected, it should deselect the selected anchor points.

I removed that piece of code. But I dont know why I wrote it. Maybe it breaks some functionality.

**Comment by photopea** [comment]
So it is a behaviour of the Adobe Illustrator. If you are drawing something with a Pen tool, and you want to leave the path open and start a new one, you press "P" to deselect the last point, and the next click will start a new path.

**Comment by camoody1** [comment]
😆
So what is your decision on the change, then? Are you going to leave that code in place to act as Illustrator does or remove it to match Photoshop?

Perhaps copy and paste that code into Vectorpea? 😁

**Comment by TheRadicalDreamer** [comment]
Please don't leave the illustrator functionality. That maybe corresponds to Vectorpea as @camoody1 says :)

**Comment by photopea** [comment]
Pressing P with a pen tool deselects selected anchors only when there was just one anchor selected. If there were 2 or more, pressing P does nothing.

**Comment by TheRadicalDreamer** [comment]
I don't know if this is intentional or not, but:
[Screen recording 2023-03-01 19.02.35.webm](https://user-images.githubusercontent.com/11801254/222275352-5c0f963a-5a9f-4256-ae97-208baff1b36d.webm)

When selecting anchor points that are not "in chain" (next to the other) and you remove them with the pen tool, you'll get 2 shapes at the end.

![image](https://user-images.githubusercontent.com/11801254/222276091-e2c24aa0-4f7b-4406-8588-6add5cc9944f.png)

![image](https://user-images.githubusercontent.com/11801254/222276098-1014403b-7420-45e6-98aa-f09891d87499.png)

**Comment by TheRadicalDreamer** [comment]
Another example.
The red arrows indicate the anchor i selected and removed
![image](https://user-images.githubusercontent.com/11801254/222277013-af1cfa69-3f4e-410b-bb87-11023e48489e.png)

![image](https://user-images.githubusercontent.com/11801254/222277022-5b5e8351-a513-4311-b4f4-5766bf7e14bd.png)

**Comment by photopea** [comment]
this is how it works in Adobe Photoshop.

**Comment by photopea** [comment]
So you should report it to Adobe :D

**Comment by MichalSZZ** [comment]
In Photoshop it works the same as in Photopea.
In Illustrator too.

But Adobe Illustrator has something really good for operation on Paths. When you select some points with the "direct select tool" a new menu will appear:

![obraz](https://user-images.githubusercontent.com/38118273/222363476-065b196f-5a7a-416b-a937-72f92c1b5806.png)

I really like it and I use it all the time. Especially aligning points or cutting a part of the paths.
But now I see, that little minus next to the pen tool on that toolbar - will give you the result that you want - deleting selected points without making two separate paths on one layer.
