### ISSUE TITLE
Combining Move tool and Fre Transform

### ISSUE THREAD

**Issue by tomasnosek** [photopea/photopea#54]
It would very nice to have some visible selection on selected object incuding anchor points with which you can do a basic operations - rotate, resize etc. It's a true benefit for user to see what is selected and what i can do with that.

**Comment by photopea** [comment]
In photoshop, it seems like a Move tool combined with a Free transform tool. Isn't free transform enough?

**Comment by tomasnosek** [comment]
The main goal is to tell user what is selected. On the corners of that selection should be points i can drag with and do this operations (resize, rotate). So, give user the choice to view this selection (free transform) after click on that object without the ctrl+T shortcut press. In PS its a feature of move tool you can check. You implemented "choose the object under cursor" that way.

**Comment by photopea** [comment]
So in Photoshop, there is just an extra border drawn with a move tool. When you manipulate that border, Move tool switches to Free Transform and you continue using Free transform (so two tools are not combined). It should be quite easy to do.

**Comment by photopea** [comment]
It was implemented.

When you check "Transformation control" for Move tool, the transformation rectangle will be drawn. When you manipulate the controls of the rectangle, Photopea switches to Free Transform. You can confirm / cancel the Free transform to go back to Move tool.
