### ISSUE TITLE
transform selection bug in complex PSD

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#540]
Hello!
I wanted to report the bug with "transform selection" function
When I use it (on specific, fairly complex PSD), the rectangle with the draggable edges, the one that appears for the transformation, and has to match the selection, does not match it - it appears somewhere else and has different dimensions.
I cannot replicate it on simple PSD created from scratch (I experimented with canvas size - thinking may be the reason is the large canvas - but in test PSD it still works fine), so I asked the owner of that PSD for a permission to send it to you for debugging, and he said it's ok.
It's probably not a good thing to publish it here for all the world though, so, may be you could tell me email address where I could send it?
Thanks

**Comment by photopea** [comment]
Hi, yes, you can send your PSD to support@photopea.com :)

**Comment by ewnjtgouierg** [comment]
thanks, sent it

**Comment by ewnjtgouierg** [comment]
just stumbled across the same issue in different & lighter PSD, and I think it might help, b/c in this one it's obvious that specific layer gets outlined instead of the selection, so I emailed it to you as well

**Comment by photopea** [comment]
What an interesting bug! It happened, if more than one layer was selected (selecting a folder means selecting all layers inside it).

It should be fixed now :) thanks!

**Comment by ewnjtgouierg** [comment]
yes, it works now, thanks a lot!
