### ISSUE TITLE
Ads being shown despite being premium AND logged in.

### ISSUE THREAD

**Issue by stephenrossscott** [photopea/photopea#5400]
Cleared cookies and cache tried to  login and out but still seeing ads despite being premium

**Comment by photopea** [comment]
Are you using Photopea at www.Photopea.com ? Could you share a screenshot of what you see?

**Comment by stephenrossscott** [comment]
Yes of course at that URL and ads on the right side of the screen. Same as
you'd see if you were using a free account.

**Comment by photopea** [comment]
Could you please share a screenshot with us? 

Please, reply in a web browser at Github.com . When you send emails to random github email addresses, github deletes attachments.

**Comment by stephenrossscott** [comment]
Love to take a screen shot but the site is down again. Plus It really would not show much. Just ads on the right. Anyway clearly bigger issues to resolve so hopefully once up it gets resolved.

**Comment by stephenrossscott** [comment]
Seems annual payment must have failed but no email and or warning-issues resolved.

**Comment by camoody1** [comment]
If you live in the US, you may need to contact your bank to let them know that you actually ARE making a purchase in the Czech Republic. I've had to call mine every time I've bought a subscription.

**Comment by stephenrossscott** [comment]
If you live anywhere it'd be the same for a CZ bank , cheers tho.

**Comment by photopea** [comment]
We dont have any subscription. When your Premium runs out, ads come back. You can pay for Premium again, Premium lasts for X days, and ads come back after that.

So do you have Premium or not?

**Comment by stephenrossscott** [comment]
Always had premium, expired but no warning or reminder. Issue closed, all good.

**Comment by photopea** [comment]
We dont send any reminders. If you dont use Photopea for six months, there is no need to pay for that period. Just pay once you use it and notice the ads.
