### ISSUE TITLE
Update: It is back up. ***PHOTOPEA DOWN***

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5402]
Currently, people are unable to log into Photopea. We try to go the website, and the browser just times out. Hosting issue, I would guess?

**Comment by versebrik** [comment]
can access it intermittently through the homepage, but can't access it with the extension program 😞

**Comment by camoody1** [comment]
Photopea is accessible again as of approximately 1am EST.

**Comment by photopea** [comment]
Sorry guys, there was a problem at our server, which lasted for 3 hours. We will do our best so that it never repeats again.
