### ISSUE TITLE
photopea templates not opening?

### ISSUE THREAD

**Issue by mucahitimre** [photopea/photopea#5408]
Photopea templates not opening, after clicking, staying to loading 

![image](https://user-images.githubusercontent.com/12904452/221405203-c52fa6dc-366d-4579-9330-e481656e2355.png)

**Comment by photopea** [comment]
Is there any censorship enabled on your computer / in your company? 

Try this and let us know if it helped: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
It is known that the Turkish government is censoring our templates. If you are in Turkey, please, change your government, or use a VPN.

**Comment by mucahitimre** [comment]
Thanks for answer, I opened when I use vpn.
