### ISSUE TITLE
Incorrect bounding box for SmartObjects with transparent edges

### ISSUE THREAD

**Issue by lucadalli** [photopea/photopea#5409]
On placement, the bounding box of a SmartObject with transparent edges is correct but after deselecting and reselecting, the bounding box does not consider the transparent edges. On resize, the bounding box corrects itself, often times causing the intended resize to turn into a move.

I am a user of the Photopea API and this is leading to critical bugs due to the aspect ratio of the SmartObject in Photopea not matching the expected aspect ratio of the image.

https://user-images.githubusercontent.com/39853447/221850053-f32f4c98-0e4c-4142-b936-32efa485e243.mp4

**Comment by lucadalli** [comment]
The image used in the reproduction demo above is attached for your convenience. 
![brisbane-cartoon](https://user-images.githubusercontent.com/39853447/221848679-573f7f5a-ac5f-47f3-9a34-3e525f21db5b.png)

**Comment by photopea** [comment]
First of all, this happens only when you enable "Transform Controls" in the Move tool. If you don't, this never happens.
![image](https://user-images.githubusercontent.com/15955558/225844855-746ddbae-2112-45ea-831b-7a95f2cd8ef2.jpg)

The way it works in Photopea is exactly how it works in Adobe Photoshop: 
- the rectangle of the "Move Tool" with "Transform Controls" is never rotated, it covers all non-transparent pixels. 
- the rectangle of the "Free Transform" can be rotated, it is a contour around the original image

![image (1)](https://user-images.githubusercontent.com/15955558/225845145-8ff1336e-2928-486e-a489-0599d860ef56.png)

How exactly is it related to the API? What part of the API?

**Comment by lucadalli** [comment]
> How exactly is it related to the API? What part of the API?

I am using using the snippet below to read the image dimensions.
```
const layer = app.activeDocument.activeLayer
const x = layer.bounds[0].value
const y = layer.bounds[1].value
const width = layer.bounds[2].value - x;
const height = layer.bounds[3].value - y;
app.echoToOE(JSON.stringify({ x, y, width, height }))
```
The problem is that the value of bounds does not account for transparent pixels. I just asked ChatGPT and it turns out Photoshop does it the same way.
Is not possible to retrieve the image size including non-transparent pixels?

**Comment by lucadalli** [comment]
I just came across this snippet that is supposedly able to read the SmartObject size, including transparent pixels.
Unfortunately it seems to be unsupported in Photopea.
```
const layer = app.activeDocument.activeLayer
if (layer.kind == LayerKind.SMARTOBJECT) {
    var r = new ActionReference();
    r.putEnumerated( charIDToTypeID( "Lyr " ), charIDToTypeID( "Ordn" ), charIDToTypeID( "Trgt" ) );
    var d = executeActionGet(r).getObjectValue(stringIDToTypeID("smartObjectMore")).getList(stringIDToTypeID("transform"));
    var x = [d.getDouble(0), d.getDouble(2), d.getDouble(4), d.getDouble(6)];
    var y = [d.getDouble(1), d.getDouble(3), d.getDouble(5), d.getDouble(7)];
    var l = [Math.min(x[0], Math.min(x[1], Math.min(x[2], x[3]))) ];
    var r = [Math.max(x[0], Math.max(x[1], Math.max(x[2], x[3]))) ];
    var t = [Math.min(y[0], Math.min(y[1], Math.min(y[2], y[3]))) ];
    var b = [Math.max(y[0], Math.max(y[1], Math.max(y[2], y[3]))) ];
    return [ UnitValue(l,"px"), UnitValue(t,"px"), UnitValue(r,"px"), UnitValue(b,"px") ];
}
```

**Comment by photopea** [comment]
Your second script runs fine in Photoshop, and I fixed the missing parts, so it runs in Photopea, too.

Note, that the "transform" is an array of 8 doubles - XY coordinates of four corners. It does not have to be a rectangle, it is a convex polygon. In your code, they compute an axis-aligned bounding box of the four corners.

**Comment by lucadalli** [comment]
Just tested it. Perfect, thank you so much!
