### ISSUE TITLE
add a guide in any mode as long as rulers are enabled

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#541]
in ps when you drag from a ruler, you always create new guide - without need for you to be in V mode and have guides visible at the moment. in case you have guides hidden, they are automatically enabled when you add a new one

this way it's a "single-gesture" operation
makes all sense, b/c much easier and doesn't interfere with anything

in photopea you have to ensure you are in V mode and have guides enabled, in normal situation when you do something and decide that you need to add a guide, to check some alignment, this means that you need to click V and then click View and Guides, and only after that you can add a guide. But why, when the rulers were already there from the beginning, and dragging from there is done only for adding a guide?

I think ps allows to move guides without switching to V mode as well (that makes sense), but I am not 100% sure and can't check at the moment.

**Comment by photopea** [comment]
But guides in PS can be moved only with the Move (V) tool, right?

**Comment by photopea** [comment]
The structure of our tools is quite complex and adding guides "from any tool" would be quite hard to implement.

But now, if showing Guides is off and you try to add one (drag it "from the ruler"), Guides are turned on instantly.

**Comment by ewnjtgouierg** [comment]
thanks a lot

& just to clarify for the case someone reads it later:

now it works almost exactly as in ps, the only little difference - you need to hold Ctrl when you start adding new guide
