### ISSUE TITLE
Cannot create a new project

### ISSUE THREAD

**Issue by dodycode** [photopea/photopea#5410]
is this project still alive? I'm trying to create a new project but nothing happens. 

But when I check the console, these error was shown:
![image](https://user-images.githubusercontent.com/20751329/221415966-9c88ac43-b86c-4cf1-abfe-61be9651de86.png)

**Comment by photopea** [comment]
I think you have browser extensions which break Photopea, try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by dodycode** [comment]
I think that's not the case. I've tried access using "guess account" in google chrome, but the error still exist when I trying to create a new project. (nothing happened, popup only get closed and error shown in console)
I think there's problem on the API? @photopea 
![image](https://user-images.githubusercontent.com/20751329/221474760-193e092e-f7a4-4357-9e0e-e16b7576d86e.png)

**Comment by photopea** [comment]
First of all, your browser says that Photopa is "not secure". Also, the top right corner of your browser says "Error". I think it is a sign that something is wrong with your browesr, not with Photopea. Could you fix it? Please, use Photopea in a browser which works normally.

**Comment by 1952-web** [comment]
No puedo abrir un nuevo proyecto.
me marca error y comunicarme con soporte tecnico.
mi punto es poder arrastrar una plantilla para pegar una imagen .

**Comment by camoody1** [comment]
> No puedo abrir un nuevo proyecto. me marca error y comunicarme con soporte tecnico. mi punto es poder arrastrar una plantilla para pegar una imagen .

Please record a short video clip of you trying to open a project so we can see exactly what you are doing and how the application is responding. Thank you.

**Comment by photopea** [comment]
I have to close it because of lack of details.
