### ISSUE TITLE
SVG stroke-opacity

### ISSUE THREAD

**Issue by Baegus** [photopea/photopea#5411]
It seems like Photopea doesn't support the `stroke-opacity` property in SVGs. For example, when I create a text layer, add the Stroke effect and set the opacity to 50%, it should export the SVG with `stroke-opacity: 0.5`. Ideally, this should work for importing SVGs as well (right now, Photopea ignores it and sets the opacity to 100%).

**Comment by photopea** [comment]
I think the Stroke effect in SVG is different than the Stroke layer style in Photopea / Photoshop.

You can have an SVG square with a stroke, which has "sharp corners", but if you stroke a square using a layer style, corners are always round. So I think it is a bad idea to convert an SVG stroke into the stroke layer style.

**Comment by Baegus** [comment]
> I think it is a bad idea to convert an SVG stroke into the stroke layer style.

I'm not sure what you mean - doesn't Photopea already convert it? When you have an SVG shape with a white stroke and open it in Photopea, it shows up as a layer style.

**Comment by photopea** [comment]
Could you be more precise? If you open a SVG in Photopea, Photopea should detect stroke-opacity (if not, show us your SVG).

If you think the stroke in a PSD is not converted correctly into a SVG, please, show us your PSD.

**Comment by photopea** [comment]
I have to close it because of lack of details.
