### ISSUE TITLE
Action is not saved (download).

### ISSUE THREAD

**Issue by Dildesign** [photopea/photopea#5412]
An action cannot be saved if the Transform Layer - Rotate step is used in that action.
Actions without this step can be saved normally.
Video of my problem:
https://drive.google.com/file/d/1gLN1w5nNRRfOa9OcLFayVM2epLWCNUjH/view?fbclid=IwAR3pqWM1j5fjPbwMnrGzOfwzihANRR2ROkJOkAlQu_to0a5o78Vg2-DR5xM

**Comment by photopea** [comment]
I can not reproduce this problem :( I tried to record Edit - Transform - Rotate, and I was able to export the ATN file with this action.
