### ISSUE TITLE
Paste screenshot from clipboard doesnt work anymore

### ISSUE THREAD

**Issue by gerasy** [photopea/photopea#5413]
On Ubuntu 20.04.5 LTS
Pasting from Clipboard doesn't work. It works in other Apps in the same browser, like web.telegram. Also Clipboard was allowed for this site in chrome settings. 
Chrome Version 107.0.5304.87 (Official Build) (64-bit)

**Comment by photopea** [comment]
It does work for me. Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
