### ISSUE TITLE
Feature proposing : Listing local fonts using `queryLocalFonts`

### ISSUE THREAD

**Issue by chartrandf** [photopea/photopea#5414]
`queryLocalFonts` is still in experimental phase, but it could be nice to show local font installed on the device. Since it will not be embedded in the product and you consume API, I may respect license agreement regarding commercial fonts.

https://developer.mozilla.org/en-US/docs/Web/API/Window/queryLocalFonts

**Comment by photopea** [comment]
Wow, that API is amazing! I didn't know it exists. Too bad it is not in Firefox and Safari yet.

**Comment by photopea** [comment]
I have implemented it! When you open a font list, there is a button "Local Fonts".

Right now, it is equivalent to drag-and-dropping all your fonts as TTF files into Photopea (new fonts will be added to the end of the font list).

In my case, it loads 430 files (700 MB) of fonts from my computer (Photopea allocates 700 MB extra RAM), takes about 4 seconds. Loading an actual TTF file is necessary for creating a font thumbnail. What do you think about this integration?

**Comment by camoody1** [comment]
I think I'd better never hit that button on my mobile phone. My poor baby would lock up instantly. 😆

**Comment by chartrandf** [comment]
Wow it's working very well, I think this is a great addition for the product 👍 🎉

----

> In my case, it loads 430 files (700 MB) of fonts from my computer (Photopea allocates 700 MB extra RAM), takes about 4 seconds. Loading an actual TTF file is necessary for creating a font thumbnail. What do you think about this integration?

Seems like a big import for the app when I may want to use 3-10 fonts only (330 files on my compute).

Is there a way to have preview «on-demand», this could prevent to import all files. Another solution is to have the possibility to select local fonts that we want to load, this will reduce the size of the import.

----

**`.psd` using local font**
When I open a `.psd` that uses a local font, it convert the font to «embed» font in the project. Is it possible to:
- On `.psd` load, check local font (if API available)
- Load local font used in Photopea
- Fallback to actual behavior if not found

**Comment by chartrandf** [comment]
I got an idea to improve the import. font preview could use plain HTML & CSS with `font-family` I think. This may prevent to load the file to show the preview, the browser will handle that for you.

**Comment by photopea** [comment]
This API is not available in mobile browsers yet: https://developer.mozilla.org/en-US/docs/Web/API/Window/queryLocalFonts#browser_compatibility - feel free to try it out.

If you set the CSS font-family, the web browser still needs to load 700 MB of fonts from a hard drive to make previews (even if they are not given to Photopea).

Or we could have PNG previews for all existing fonts at our server, and if we see that you have Arial, we would load a 1 kB PNG thumbnail from our server.

**Comment by chartrandf** [comment]
> Or we could have PNG previews for all existing fonts at our server, and if we see that you have Arial, we would load a 1 kB PNG thumbnail from our server.

It's a good solution :)

**Comment by photopea** [comment]
I take it back, I remade it completely. It is a Checkbox now.

![image (3)](https://user-images.githubusercontent.com/15955558/226173445-e3ebad89-fc56-4bf9-9d88-67727d025469.png)

Local fonts are included in the list when the checkbox is on. The state of the checkbox remains after closing Photopea.

When you enable it for the first time, all binary font files are loaded from your computer and analyzed (supported characters etc.), and we make thumbnails. All this is saved in a browser cache (400 Bytes per font). When you open Photopea next time, we already now what fonts you have, we know thumbnails, so the binary file is loaded only when you use the font.

**Comment by chartrandf** [comment]
Nice, great work 👏🎉
