### ISSUE TITLE
Transforming selected anchor points get all the shape

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5415]
When i direct select some anchor points and hit Ctrl+T to transform them i get the tool for all the shape, even though it only transforms the anchors i selected.

It will be better to have only the transform tool around the selected anchor points.

Also, when you have the transform tool activated and hit WRAP, and you distort the shape, the selected anchor points get big and fill the frame with the shape. It will be good to have it only on the little frame :)

Video:
[Screen recording 2023-02-27 11.55.14.webm](https://user-images.githubusercontent.com/11801254/221597853-9a4f5521-ba31-43f1-b1d7-6460b8f60075.webm)

**Comment by photopea** [comment]
Photopea should work the same as Adobe Photoshop.

When you free-transform the top two points of a rectangle, the transformation rectangle would be just a line, which you can not transform.

I think it could even be you, who reported it several years agon, and asked us to make it work as it works now.

**Comment by MichalSZZ** [comment]
> Photopea should work the same as Adobe Photoshop.
> 

In my Photoshop it works differently.

> When you free-transform the top two points of a rectangle, the transformation rectangle would be just a line, which you can not transform.
> 

Again - not. In Photoshop it takes the bottom edge of the transformation rectangle from the next lower point (not selected) in the path.

> I think it could even be you, who reported it several years agon, and asked us to make it work as it works now.

**Comment by photopea** [comment]
Could you show a screenshot of the difference betweeen Photopea / Photoshop?

**Comment by TheRadicalDreamer** [comment]
When transforming certain anchor points in photoshop, it create a transforming square only for the size of the points:
![image](https://user-images.githubusercontent.com/11801254/221935036-6a361543-eb59-4f4d-874a-1248e80c64ed.png)

**Comment by photopea** [comment]
Okay, it should work like that now.

But when you transform points with the same X or the same Y coordinate, Photoshop (and Photopea) still creates a rectangle around the whole shape.

**Comment by TheRadicalDreamer** [comment]
thanks! :D
