### ISSUE TITLE
Confirmation button label

### ISSUE THREAD

**Issue by cyberpunkangel** [photopea/photopea#5416]
![image](https://user-images.githubusercontent.com/47162573/221659231-13ccffc8-ee16-440d-94d0-eb409e482e93.png)

I think instead of "Learn More" should be "Yes", "Sí" or something

**Comment by photopea** [comment]
I switched the language from English to Spanish and here is what I see: 
![image (3)](https://user-images.githubusercontent.com/15955558/221689394-98f3baf8-6bed-470a-aea5-4b37fa419576.png)

Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/
