### ISSUE TITLE
changing image size

### ISSUE THREAD

**Issue by earthtojagk** [photopea/photopea#5417]
resizing an image with the properties menu with "keep aspect ratio" turned off is changing the number i'm inputting. if i type 391 px for example, it either changes to 390 or 392 when i press enter. it does the same when resizing by holding shift and dragging with the transform tool. it has also resized some images by a few pixels in a similar way when i have opened projects with exact dimensions on the images

**Comment by photopea** [comment]
I am not able to see such behaviour myself. Could you tell me what exactly should I do after opening www.Photopea.com to see it? Or share screenshots?

**Comment by camoody1** [comment]
@photopea Didn't you have a similar issue like this a few weeks back? In ticket #5335?

**Comment by photopea** [comment]
who knows, the person would have to tell us.

**Comment by earthtojagk** [comment]
> I am not able to see such behaviour myself. Could you tell me what exactly should I do after opening [www.Photopea.com](http://www.Photopea.com) to see it? Or share screenshots?

![2023-02-28-22-46-51-Trim](https://user-images.githubusercontent.com/126525406/222002476-bb9f2e4c-f0ea-46bf-8708-6a07cbe7e25f.gif)

**Comment by photopea** [comment]
You are using regular pixel layers (not a smart object or a vector shape).

Your image probably has semi-transparent pixels at the edges. Their transparency could drop during the transformation. But it should still look correctly.

If you want to change the size of your layer more than once, convert it to a smart object.
