### ISSUE TITLE
Text does not render correctly when export as pdf

### ISSUE THREAD

**Issue by Khald1998** [photopea/photopea#5419]
Here is the text on my screen 
![mbhjuU9](https://user-images.githubusercontent.com/108824412/222271081-88492cbd-3c1d-427a-938e-1b52ba0d4177.png)
Here is the text when trying to export as pdf
![image](https://user-images.githubusercontent.com/108824412/222271229-9f042436-4750-4646-93e7-b9d58668ee84.png)

**Comment by photopea** [comment]
We can not embed fonts into PDF files now. Please, enable the "vectorize text" option.
