### ISSUE TITLE
Export to PDF shows significant errors.

### ISSUE THREAD

**Issue by hisnameisjimmy** [photopea/photopea#542]
Original Source PSD:
[businesscard-horizontal-vista-front.psd.zip](https://github.com/photopea/photopea/files/1807737/businesscard-horizontal-vista-front.psd.zip)

Exported PDF:
[businesscard-horizontal-vista-front (1).pdf](https://github.com/photopea/photopea/files/1807739/businesscard-horizontal-vista-front.1.pdf)

Exported PNG:
![businesscard-horizontal-vista-front 1](https://user-images.githubusercontent.com/740373/37354201-64b52358-26e1-11e8-8411-a47b5138cd04.png)

**Comment by photopea** [comment]
Hi, we fixed the conversion of graphics (both PDF and SVG export).

Saving text into PDF is quite complex and Photopea can not do it properly at the moment. We recommend to convert your text to shapes for the best compatibility (right-click - Convert to Shape).

After that, you can get a PDF like this: 
[businesscard-horizontal-vista-front (2).pdf](https://github.com/photopea/photopea/files/1818968/businesscard-horizontal-vista-front.2.pdf)

**Comment by hisnameisjimmy** [comment]
@photopea Impressive turnaround! I don't think I've ever seen a 2-day fix.  Colors are still a bit off, but a big improvement.

Here's an example of color differences between photoshop PDF export (left) and photopea (right):

![businesscard-horizontal-vista-front_2_pdf__1_page__and_card_pdf__1_page_](https://user-images.githubusercontent.com/740373/37605411-69acf848-2b93-11e8-9d95-fa59a1f99458.png)

PNG export has the same issues.

**Comment by photopea** [comment]
Right now, Photopea supports only sRGB PSDs.  Your PSD contains some weird ICC color profile. When you open it in Photopea, Photopea assumes it to be in sRGB, while Photoshop probably assumes it to be in Adobe RGB or something like that.

Open your PSD in Photoshop and save it back as a PSD. When I do that, the new PSD is in sRGB and the colors in Photopea look the same as in Photoshop.
