### ISSUE TITLE
Error: 401 user's secret was already generated

### ISSUE THREAD

**Issue by jholder220** [photopea/photopea#5420]
I cannot seem to find any other page related to this issue, but one of my students is trying to access PeaDrive in Photopea and we keep getting this error that says "Error: 401 user's secret was already generated". We have attempted signing out and back in, clearing the cache, and switching devices but its the same error. This only happened on her account and no other student's.

**Comment by photopea** [comment]
Could you try these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by b-ridge-cloud** [comment]
This is issue is happening to me as well. I have been trying the suggestions with no luck.

**Comment by photopea** [comment]
Could you tell me what browser extensions do you use, which are allowed to modify Photopea? 

Click the "puzzle icon" at the top right corner of your browser and check which extensions have "full access" to read and modify Photopea.

**Comment by b-ridge-cloud** [comment]
I use Safari primarily and Chrome as a backup browser. There are no extensions installed when I check that in the settings. I tried clearing history to see if too many visits to the site is creating problems with the catche but that didn’t help. I tried the private and incognito setting, when I do that, there is no “error” generated but the peadrive is blank slate of white. I have tried on my laptop, iPad, and iPhone with same results.

**Comment by b-ridge-cloud** [comment]
Another possibility? Maybe I saved too much memory space in the peadrive? I would have thought it wouldn’t let me do that?

**Comment by photopea** [comment]
Can you press "Account" at the top and log in? If it still does not work, can you tell me what email address do you see when you log in?

**Comment by photopea** [comment]
Once you log in, your Account button shold become Orange. is it orange? Sorry, I can not see your email address.

Please, reply to me at www.github.com in your web browser. Do not send emails to random email addresses.

**Comment by b-ridge-cloud** [comment]
The account button is green.

**Comment by photopea** [comment]
Please, tell me your email address which you see after clicking the "Account" button. You can write it here on github or send an email to support@photopea.com

**Comment by b-ridge-cloud** [comment]
Issue fixed-thank you your help.

**Comment by RobertWo495** [comment]
Help I have the same issue and I can't slove it.

**Comment by photopea** [comment]
Please, tell me your email address which you see after clicking the "Account" button. You can write it here on github or send an email to [support@photopea.com](mailto:support@photopea.com)

**Comment by v1adko** [comment]
I now get the same issue (tried loading a file from PeaDrive on a different computer)
Email is vlad@logoi.dev

<img width="863" alt="Image" src="https://github.com/user-attachments/assets/3cfeb8fa-5712-4b31-af04-cd50033e16bd" />

**Comment by photopea** [comment]
I have reset it, try it again.

**Comment by someguynik** [comment]
I am having this appear every time I attempt to save my photos. I understand you have to reset it, does this mean I will lose my photos?

Email: --

**Comment by photopea** [comment]
Hi, I have reset it. Try to close Photopea and open it again. Do you also log in to Photopea from more than one device? I am trying to figure out why does it happen :D

**Comment by someguynik** [comment]
Thank you! Sadly I lost the photos but that's okay, I can edit them again. So what happened is I had sever tabs open from editing photos on different occasions. When I was finished with editing them, I realized I wasn't logged into my account, I proceeded to do so on each tab. After that, I hit "Ctrl + S" to save on each tab. at the top of my screen it kept saying "Saving..." and it wouldn't go away, I then manually did it by hitting "File" < "Save more" < "PSD to Storage" < "PeaDrive." I only didn't this on one photo, then the Error message came up and wouldn't go away , it kept spamming. Even when I closed out of PeaDrive, I was unable to preform another actions because of the spam.

Thank you for your help, I was able to finally save sometime once I re-opened the page!

**Comment by photopea** [comment]
You should not lose any photos. If you use the same Photopea account, and the peadrive works, you should see the content of your peadrive, we do not delet anything for our users.

**Comment by someguynik** [comment]
I just checked and they are not there. I was unable to save it to PeaDrive though because of the error message as I opened it up. It not a huge deal and I can re edit them, it wasnt too detailed anyway. Im just glad you guys were able to fix it.

**Comment by photopea** [comment]
Oh, I thouhgt your files were stored in Peadrive at some point (you saw them there).

**Comment by someguynik** [comment]
Oh yeah, I tried to but it wouldn't let me. Got the photos finished and saved now so it all good! Thanks for your help!

**Comment by Zenyski** [comment]
Hello, I also used PeaDrive to store some files, it's glitched, mind resetting mine as well?

Email: azizselim1212@gmail.com

**Comment by photopea** [comment]
I just did, could you try it again?

**Comment by Zenyski** [comment]
Um, would it glitch out if I checked it from my phone? I usually use my computer, maybe using two devices can bug it. Sorry for the late response, also if using two devices bugs it, I'll try it when I wake up after I open my computer.

**Comment by photopea** [comment]
you should be able to use Photopea however you want. If anything glitches, we are responsible for it, not you.

**Comment by ViceRaven** [comment]
> I just did, could you try it again?

I am also now getting the same issue. Http error 401: User's secret was already generated. My email is zuaresuddith@gmail.com

**Comment by photopea** [comment]
I have restarted it, could you try it again?
