### ISSUE TITLE
Image out of frame when entering Liquify mode

### ISSUE THREAD

**Issue by Photosounder** [photopea/photopea#5421]
Quite often when entering (or is it only when reentering?) Liquify mode the image is out of the screen for no clear reason and it's hard to find it when only seeing a grey background. When entering Liquify mode the zoom/offset of the view should be reset to something usable.
![2023-03-03 13 26 07](https://user-images.githubusercontent.com/7466235/222719863-53d8ae05-5700-43f5-91d9-cb05b73f99f1.png)

**Comment by photopea** [comment]
It should be fixed now :)

**Comment by Photosounder** [comment]
Now when I click on something in Liquify mode after zooming in it jumps to the middle of the image.

**Comment by photopea** [comment]
now it should be fixed.

**Comment by Photosounder** [comment]
Correct, thank you!
