### ISSUE TITLE
Language strings bug 

### ISSUE THREAD

**Issue by IamFlea** [photopea/photopea#5423]
0. Start a New Project. 
1. More > Languages > Turkce 
2. Filtre > Filtre galersi   (The filters are translated correctly)  
3. Close the filters
4. Daha Fazla > Dil > English 
5. Open Filter Galery again.

Now you can see that the filter names are in Turkish despite the chosen language is English. I think it is a minor bug anyway. :D 

((Ano, učím se Turecky na Duolingu :D :D ))

**Comment by photopea** [comment]
fixed! :)
