### ISSUE TITLE
A part of the screen is cropped out

### ISSUE THREAD

**Issue by RuffRaph** [photopea/photopea#5425]
![image](https://user-images.githubusercontent.com/127030987/222963426-40841832-f2aa-46b4-9acf-fc66b153fa11.png)

**Comment by camoody1** [comment]
What do you mean "part of the screen is cropped out"? How so? Do you mean that part of the application window is off screen? Is there a window slider to scroll left? Are you on a phone or a PC?

**Comment by RuffRaph** [comment]
> What do you mean "part of the screen is cropped out"? How so? Do you mean that part of the application window is off screen? Is there a window slider to scroll left? Are you on a phone or a PC?

I am on a pc and yes part of the application window is off screen like the tool bar

**Comment by camoody1** [comment]
Have you closed and reopened your web browser, then reopened the website? Which web browser are you using?

**Comment by RuffRaph** [comment]
> Have you closed and reopened your web browser, then reopened the website? Which web browser are you using?

yeah i did reopen my web browser and it still didnt work. Im using google chrome

**Comment by RuffRaph** [comment]
I have found the issue and it turns out that my web browser was the problem as when I used microsoft edge it worked well, Thanks for the help.

**Comment by camoody1** [comment]
Have you noticed if your scrollbars are missing on any other webpages? I found this forum post for Microsoft Windows...
https://answers.microsoft.com/en-us/windows/forum/all/missing-scroll-bar/d2eed655-a1cc-47c3-af67-14b1ffe4bc74

**Comment by camoody1** [comment]
> I have found the issue and it turns out that my web browser was the problem as when I used microsoft edge it worked well, Thanks for the help.

Excellent! Glad you figured it out. Have a great Sunday.

**Comment by photopea** [comment]
ok cool! :)
