### ISSUE TITLE
Issue: When using local fonts PDF's don't get exported correctly

### ISSUE THREAD

**Issue by cyrilknops** [photopea/photopea#5426]
Issue:
When using a custom (local font) and trying to export as PDF it doesn't use the custom (local font)
![Screenshot 2023-03-06 at 12 24 06](https://user-images.githubusercontent.com/17334353/223097298-065a1dd6-45de-4f52-a4b2-5ba1aff15655.png)

Current solution:
Convert all layers together to smart object and then export to PDF.

**Comment by photopea** [comment]
Hi, we can not embed fonts into PDF files now. Use the "vectorize text" option (on the right side).
