### ISSUE TITLE
Refreshing and crashing when loading ads

### ISSUE THREAD

**Issue by andrewatya** [photopea/photopea#5427]
When I use Photopea and it loads the next adverisement blocks on the right, refreshes the all screen and sofware UI, and my project desappears, and on the other tabs I see a white screen and a little crash icon on the upper-left corner instead of projects. I tried to disable OpenGL, empty cache, disable all the add-ons but the same issue. Before a quarter years I never met this yet.
I like Photopea, because this soft can preserve vector graphics after opening a pdf, svg... files.
Please check this.
Browser: Chrome 110.0.5481.178 (64 bit), 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz, Win 10 Pro, 22H2, 19045.2604, Windows Feature Experience Pack 120.2212.4190.0
Thank you!
Andras

**Comment by photopea** [comment]
Could you record a video of what is happening? I am afraid I do not understand.

Also, try this first: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by andrewatya** [comment]
here's a video about refreshing while working on projects:
https://drive.google.com/file/d/14PlT3yqQEv44Dj8zFsTo1zmqcQqle_RQ/view?usp=share_link
thanks

**Comment by photopea** [comment]
It is not refreshing, because you can still see the list of layers on the right side, you document is still opened. You still can save yor work as a PSD file (File - Save as PSD).

It looks like your GPU has crashed. How large is your second document in terms of pixels? Maybe you dont have enough GPU memory.

**Comment by photopea** [comment]
I have to close it because of lack of details.
