### ISSUE TITLE
Feature request: Add a "Auto-Blend Layers"

### ISSUE THREAD

**Issue by ThatMario** [photopea/photopea#5428]
Hi, I would like to see the option "Auto-Blend Layers" in Photopea. 
![Auto-Blend Layers](https://user-images.githubusercontent.com/87676924/223224467-8ad89c52-5fe8-4f09-8cf5-54e0155baf2e.jpg)

**Comment by photopea** [comment]
Did you try to press Edit - Auto Blend?

**Comment by camoody1** [comment]
Do you mean like this?
![Screenshot_20230306_170437_Edge](https://user-images.githubusercontent.com/73725653/223278580-350e8855-a0ec-4de8-968a-dc415bbf8577.png)

**Comment by ThatMario** [comment]
> Do you mean like this? ![Screenshot_20230306_170437_Edge](https://user-images.githubusercontent.com/73725653/223278580-350e8855-a0ec-4de8-968a-dc415bbf8577.png)

Yes

**Comment by photopea** [comment]
This feature has existed in Photopea for many years. So I dont understand your request.
