### ISSUE TITLE
Loading

### ISSUE THREAD

**Issue by Glodie63** [photopea/photopea#5429]
It is taking several minutes for the home page to load if it loads at all. What do you advise?

**Comment by photopea** [comment]
Are you talking about www.Photopea.com ? In what country are you located? Can you open other websites?

**Comment by Glodie63** [comment]
Tulsa, OK. Tried on phone and it loaded.

***@***.***

**Comment by photopea** [comment]
Does your internet provide have any restrictions? Do you use any browser extensions? Could you try to open www.Photopea.com in the incognito mode, or in a different web brwoser?

**Comment by photopea** [comment]
I have to close it because of lack of details.
