### ISSUE TITLE
View equirectangular image in a draggable spherical panorama way

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#543]
Just like the way google street view is presented
It's easier to view it in the same way as it will be presented while editing

How photoshop implemented this is using a command called spherical panorama under 3d menu,
to turn an equirectangular image layer into a panorama layer, and in properties panel also can define the field-of-view of the viewing camera(as mm of lens).
After editing, the dedicated export command injects some metadata for recognition from the destination viewing platform like google street view

example 
https://www.youtube.com/watch?v=AL9r6rKwFmI

**Comment by photopea** [comment]
So do you need just a panorama viewer, or the full editor (like in the video)? I think we should focus at more important features at the moment. But we can discuss it, too.

**Comment by hgs54371** [comment]
To be able to view it that way while editing, this is a actually popular function to have, google street view spheres creation rely on this to do the edits

**Comment by photopea** [comment]
This requires a brand new functionality for editing. It is not just a "different view".  E.g. if you you draw a little dot at the "south pole", it should actually draw a long line at the bottom edge of the image. I am not sure how many people are actually looking for such functionality at the moment.

**Comment by hgs54371** [comment]
Maybe you just haven't noticed that photo sphere is already a big thing on google map now

Just look at how many user submitted photo spheres there are in street view in google map for popular locations around the globe, mostly by tourists or business photographers, for example: 
https://goo.gl/maps/vpBRWdUU4qm
click on bottom left square to expand the map then zoom in to proper level for more blue dots to show, each blue dot is an user submitted sphere to click on

And they need to blur faces for privacy or add branding logos, before uploading.
This would be a big reason that people still go for photoshop, myself included

**Comment by hgs54371** [comment]
Hi, if view it that way While editing is too complex to achieve, then put a view toggle under view menu for previewing the result before uploading would be good.

There are several dedicated standalone app for this, there are online ones also, google for "online equirectangular viewer", but of course they are a separate package, it would be nice to preview these spheres without leaving photopea.
