### ISSUE TITLE
Detects adBlock when it is removed from Chorme

### ISSUE THREAD

**Issue by Stephanommg** [photopea/photopea#5430]
I had an adBlock extension for Google Chrome. The site detected it, and started to display a bar over the menu bar:
![image](https://user-images.githubusercontent.com/1700817/224064085-230c289a-908a-4f39-8ec3-e5926130fe74.png)

 I deactivated it but the site still detected it. I removed the extension, same result. I cleanned temp files and cookies, it stopped telling me that an adBlock was detected for a time, then returned to do so. Anyway, it keeps displaying this window over the menu bar, thus, I can't click on it.

**Comment by photopea** [comment]
You should use Photopea at www.Photopea.com . Could you try it and let me know how it works?

**Comment by Stephanommg** [comment]
It simply came back to normal now (some options of that appear appear but in somewhere else". And in  [www.Photopea.com](http://www.photopea.com/) that bar doesn't appear.

**Comment by camoody1** [comment]
www.photopea.com is the ONLY legitimate site to use this application. No other website or Play Store application is official. Do not use them.
