### ISSUE TITLE
Stuck on saving after creating a new path using pen tool

### ISSUE THREAD

**Issue by christophervinantius** [photopea/photopea#5431]
Whenever I try to save a .psd file after creating a new path using pen tool in it (to be more specific, I place the newly created path layer right above another layer consisting of path created using pen tool as well), the console always gives this error message:

Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at f.Gd (pp.js:4490:70)
    at bs.a3E (pp.js:4022:46)
    at bs.Rs (pp.js:4002:63)
    at bF.a2T (pp.js:4122:6)
    at dP.at1 (pp.js:4206:42)
    at dP.JJ (pp.js:4193:102)
    at ci.a0s (pp.js:4389:57)
    at ci.abX (pp.js:4387:99)
    at ci.ahT (pp.js:4382:49)
    at ci.JJ (pp.js:4363:25)

And it makes the 'saving...' progress there impossible to be finished properly.

**Comment by photopea** [comment]
I can not reproduce it :( could you be more specific? What should I do after opening www.Photopea.com to see the problem myself?

**Comment by christophervinantius** [comment]
https://drive.google.com/file/d/1ESJ8zRaSVAGQzTYE-jl0fe3j40PW_2t0/view?usp=share_link

Hopefully this clip may help, I have recreated the issue there. If it's still not really clear I can try to reproduce it again

**Comment by photopea** [comment]
I am very sorry, it is fixed now.

Basically, if you filled a vector shape with a right-click: Fill, or Alt+Backspace, it became unsaveable (it was not related to two shapes).
