### ISSUE TITLE
Does not fit screen

### ISSUE THREAD

**Issue by thepcproff** [photopea/photopea#5432]
When I open photopea is not responsive to my screen size and there is no slider bar at the bottom.  So I have to adjust the browser window size, but it becomes so tiny I can not read it. Also, how do I get basic fonts like Arial, times, etc,,,,

**Comment by photopea** [comment]
Could you show us a screnshot of what Photopea looks like?

**Comment by thepcproff** [comment]
![image](https://user-images.githubusercontent.com/95923572/224376635-358adf0d-2d97-448c-9ed5-fdc50caea055.png)

**Comment by photopea** [comment]
That is very strange. Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by adamrpostjr** [comment]
I am having the same issue, I am on linux in chromium!

**Comment by photopea** [comment]
You should report a but to the person who created your adblocker.

**Comment by thepcproff** [comment]
There are no ads, I’m a paying customer.

**Comment by photopea** [comment]
@thepcproff did you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.

There is definitely something breaking Photopea. If you use Photopea in any standard browser with no browser extensions (which have permissions to modify websites), it always runs correctly.
