### ISSUE TITLE
Camera Raw Files *.DNG Open Incorrectly

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5433]
I just installed the Expert Raw application for my Samsung Galaxy S21Ultra. It allows me to take a Raw photo immediately after taking a JPG. Thebraw file is saved as a DNG file. I can open these files and edit them in my Snapseed app on my phone, but when I open them in Photopea, they appear horribly corrupted. Below is an example of the Raw file in Photopea versus what the actual JPG looks like.
![SmartSelect_20230310_204338_Edge](https://user-images.githubusercontent.com/73725653/224459462-8d44e2bb-09bb-4323-a5d4-c0927a55aef8.jpg)
![20230310_203649](https://user-images.githubusercontent.com/73725653/224459465-82252f5f-82a3-436d-ac8e-6830cc5983e7.jpg)

I will also send a couple of my files to support@photopea.com for you to examine.

**Comment by photopea** [comment]
Thanks for reporting it! It is fixed now. It took me seven hours to fix it :D

**Comment by camoody1** [comment]
Nice! Can confirm it's working correctly on my phone, now. It's just amazing to me how quickly you can fix something would normally take months for a large company to go thru iterations, testing, and beta channels. Thank you for the great work you do.
