### ISSUE TITLE
it's being very slow and cursor shows up while drawing

### ISSUE THREAD

**Issue by lovebitez** [photopea/photopea#5435]
it's being very slow and when i tried saving an image the confirmation pop up wouldn't show up so i had to use export instead and while drawing instead of the usual drawing cursor my mouse pointer would show up instead and it would bug out and not allow me to click on anything else making my whole screen freeze and then i would have to restart my laptop

**Comment by lovebitez** [comment]
i forgot to mention i use a drawing tablet

**Comment by photopea** [comment]
Hi, what exactly should I do to see a problem myself? I dont have a drawing tablet, but I could try to draw with a mouse.

**Comment by lovebitez** [comment]
how do i explain it..i am not sure if it works with a mouse but if i clicked on something to fast it will begin to be slow at first and then if i do a long click it won't show the other options like with the selection tools and when dragging the pen the cursor will turn into the mouse pointer and with the other thing it'll happen randomly even if i don't click to fast.

**Comment by photopea** [comment]
Maybe try this first: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

There are millions of people using Photopea and nobody reported such thing. Of course, Photopea is slow, if your computer is slow, or if the task is too complicated (e.g. billions of pixels).

**Comment by lovebitez** [comment]
ah. alright

**Comment by lovebitez** [comment]
while i was drawing i can confirm the same thing happens with not just the mouse but the touchpad

**Comment by photopea** [comment]
So what is it that is happening? Could you maybe record a video?

**Comment by lovebitez** [comment]
i could try

**Comment by lovebitez** [comment]
https://user-images.githubusercontent.com/127608230/224546256-0d3e2baa-d224-4fdd-b353-660b8e3774cd.mp4

**Comment by photopea** [comment]
How large is your image? You can see it in Image - Image Size. 

Also, what CPU do you have? How old is your computer?

Could you show us a screenshot of "about://gpu" ?

**Comment by lovebitez** [comment]
it's 2000x2000.  i have a chromebook. are you seriously suggesting i get a new computer?

**Comment by photopea** [comment]
Yes, I think it could be because your computer is not powerful enough. 2000x2000 is 4 million pixels.

Is there any painting app that runs better than Photopea on your computer? Also, you did not show us the "about://gpu".

**Comment by lovebitez** [comment]
that's enough. i cannot afford another pc right now. and it's obvious you do not want to help with this. so i might as well just deal with it.

**Comment by photopea** [comment]
Could you open "about://gpu" in your browser and send us a screnshot of what you see?

**Comment by lovebitez** [comment]
fine. if it'll get you to stop asking. 
![image](https://user-images.githubusercontent.com/127608230/224558832-88419fe8-6734-4520-876d-d69edeae57fd.png)
 
![image](https://user-images.githubusercontent.com/127608230/224558859-b4c470ed-3960-498d-b68b-70f0f44d9a45.png)

**Comment by lovebitez** [comment]
![image](https://user-images.githubusercontent.com/127608230/224579685-04e725a8-9ebd-47f6-84b5-d57ef4bb7f71.png)

**Comment by lovebitez** [comment]
why are you asking so many questions about my laptop. Jesus Christ i only reported a bug. then it turns into this.

**Comment by camoody1** [comment]
> why are you asking so many questions about my laptop. Jesus Christ i only reported a bug. then it turns into this.

He's trying to figure out what specifically is causing YOUR problem since no one else is reporting what you're seeing. Hundreds of thousands, if not millions, use Photopea every day and your specific issue is getting the attention of the developer. Maybe don't be a jackass to someone trying to gather information to figure out your problem.

**Comment by photopea** [comment]
So far, my only explanation is, that your computer is not powerful enough. Proffesional artists invest thousands into powerful computers, and it is not possible to deliver the same experience on less powerful devices.

Try to update Google Chrome, it might help. Or use a lower resolution, e.g. 1000x1000.

**Comment by lovebitez** [comment]
last time i ever ask the devs for help.

**Comment by lovebitez** [comment]
very unhelpful.

**Comment by photopea** [comment]
we can not do miracles

**Comment by photopea** [comment]
We can not do miracles. And you refused to cooperate (you never answered how old your computer is, or what CPU you have, you refused to update your Chrome).
