### ISSUE TITLE
I Closed history and don't know how to get it back

### ISSUE THREAD

**Issue by CalebPlayzRoblox** [photopea/photopea#5436]
I was making an os concept but then my photopea wasn't letting me do anything but then I closed the history and the rest on accident so now I CAN'T SEE HISTORY
![Screenshot 2023-03-11 5 41 16 PM](https://user-images.githubusercontent.com/117236721/224514629-cb888b95-462e-4794-a3a3-035ba675b2af.png)

**Comment by CalebPlayzRoblox** [comment]
please help

**Comment by photopea** [comment]
If you closed a window, you can reopen it in the Window menu, e.g. Window - History.

**Comment by CalebPlayzRoblox** [comment]
So I Kinda Am Not On Windows, A Chromebook

**Comment by camoody1** [comment]
> So I Kinda Am Not On Windows, A Chromebook

And I'm on an Android phone... the application still has a menu at the top named "Window". Like the Dev suggested, click on Window -> History and the History window will reopen.

**Comment by CalebPlayzRoblox** [comment]
I thought they meant windows key

**Comment by photopea** [comment]
There is the "Window" in Photopea.com 
![image (3)](https://user-images.githubusercontent.com/15955558/224533178-27cdc75b-0842-4c58-9cdb-94595052500e.png)
