### ISSUE TITLE
Maybe the feature of saving images with the .PDF extension is faulty

### ISSUE THREAD

**Issue by Photoshoponlinevn** [photopea/photopea#5437]
I save the image by clicking File ➜ Export as ➜ PDF.

However, the pdf file has an unbelievable size, it is 9 times heavier than the original image file.

![1](https://user-images.githubusercontent.com/120770864/224518324-3651f940-6b37-40b9-9960-f0e54bd549de.jpg)

the original image
![2](https://user-images.githubusercontent.com/120770864/224518339-32ec6f0a-8715-4d40-a45e-b536c466afd2.jpg)

I tried reducing the quality to 90% and checking the box Rasterize all ➜ Image quality remains the same while the size is the same as the original file.

I noticed this error only occurs with .jpg images, .png images are completely normal.
![3](https://user-images.githubusercontent.com/120770864/224518347-fe062eb3-c355-43d4-a333-74361076c7b4.jpg)

#2

Batch convert images to pdf does not work.

#3

If the image is only full of text inside, the image quality will be noticeably reduced if I choose File ➜ Automate ➜ PDF...

However, if I use File Export as ➜ PDF, the image quality is much better, the text is still clear.

Why is that?

**Comment by photopea** [comment]
So you opened a JPG image in Photopea and exported it as PDF, and the PDF is 10x bigger? Did you try to export it as a PNG? The PNG is also 10x bigger, do you aslo think it is faulty?

**Comment by Photoshoponlinevn** [comment]
I tried converting the original image to png format and it doesn't give this error. The image below is an example, the final image is in png format. It has a capacity of 131kb, after converting to pdf format its capacity only increased slightly.

https://user-images.githubusercontent.com/120770864/224518347-fe062eb3-c355-43d4-a333-74361076c7b4.jpg

**Comment by photopea** [comment]
I do not understand, what the error is? Could you tell us, what should I do after opening www.Photopea.com to see the error?

**Comment by Photoshoponlinevn** [comment]
Why does converting JPG images to PDF cause the PDF file size to increase so much (an image with a file size of only 60kb can result in a PDF file size of up to 600kb)? However, if I use an image with the .PNG extension, I do not encounter this issue.

**Comment by photopea** [comment]
Could you share your JPG and PNG images?

**Comment by Photoshoponlinevn** [comment]
Here: https://user-images.githubusercontent.com/120770864/224518339-32ec6f0a-8715-4d40-a45e-b536c466afd2.jpg

**Comment by photopea** [comment]
I went to www.Photopea.com and pressed File - Open, and opened your image. When I export a PDF, it is 568 kB. When I export a PNG, it is also 568 kB. Are you sure your PNG was smaller?

**Comment by Photoshoponlinevn** [comment]
No, if the image file I send to you is in the .png format, when exporting to the PDF format, the file size of the PDF is very good.
This is a PNG image file, when exported to a PDF file, the file size is very good.
![choi-son-mau](https://user-images.githubusercontent.com/120770864/224546966-51bb27ca-60f2-4419-80a2-79d758cb5e23.png)

**Comment by camoody1** [comment]
I confirm what the Developer is seeing. I downloaded the JPG file you linked here. It was approximately 58kb in size. I opened it in Photopea and exported it as both a PNG file and a PDF file. In both cases, the new file sizes were approximately 570kb.

**Comment by photopea** [comment]
Your PNG and your JPG hare totally different images. Your JPG has about 30,000 colors, while your PNG has about 200 colors.

Of course, if you dont care about the quality, you can make a PNG or a PDF very small.

![224518339-32ec6f0a-8715-4d40-a45e-b536c466afd2 (1)](https://user-images.githubusercontent.com/15955558/224547961-976f0142-ea04-41a4-973a-ba97d4dbeaff.png)

**Comment by Photoshoponlinevn** [comment]
The issue I am concerned about here is the excessively large file size of the PDF file. If I use another application to convert a .JPG image with a file size of 57kb to a PDF file, I will get a PDF file with a file size of around 60KB, which is close to the original image. However, if I use Photopea, the file size increases up to 600kb.

If I use Photopea and convert the JPG image file to PDF using: File ➜ Automate ➜ PDF Presentation, the resulting PDF file size is very good, it does not become too large. Why?

**Comment by photopea** [comment]
Ok, it should work better now. 

Photopea will detect, if each layer of pixels could be a JPG file in the past, and if yes, it will compress it to the original file size (or even a smaller size, depending on the "Quality" slider).

**Comment by MichalSZZ** [comment]
@photopea is there an option to have compressed images in PDF file? When I save project to PDF in Adobe (Ps or Ai) I can choose how it should compress graphics.

**Comment by photopea** [comment]
@MichalSZZ It is all hidden under the "Quality" slider. Keep it at 100% to keep the original quality.

**Comment by Photoshoponlinevn** [comment]
Thanks
