### ISSUE TITLE
it will not save the image

### ISSUE THREAD

**Issue by sojournerbliss** [photopea/photopea#5440]
It's making me crazy i just did a bunch of edited and now the dang thing is frozen and it won't save and that sucks.

**Comment by camoody1** [comment]
Save it to a different cloud location. Mine sometimes locks up on Saving to one location, so I just save it to my online Photopea storage as a temporary means. That usually saves quickly.

**Comment by photopea** [comment]
Are you trying to press File - Save as PSD, or File - Export As? What exactly is frozen? Is the whole screen black?

Were you ever able to save properly in Photopea in the past, or it is your first time using Photopea and you are trying to save for the first time?

**Comment by photopea** [comment]
I have to close it because of lack of details.
