### ISSUE TITLE
my words are so small

### ISSUE THREAD

**Issue by adminZZAP** [photopea/photopea#5441]

**Comment by camoody1** [comment]
Add more letters. Make them longer. 🤷🏽‍♂️

**Comment by somethingLC** [comment]
Text font size I think it's *f+10

**Comment by photopea** [comment]
Hi, what do you mean? Could you share a screenshot of it?

**Comment by photopea** [comment]
I have to close it because of no response from the original person who posted it.

**Comment by adminZZAP** [comment]
sorry
