### ISSUE TITLE
Can't edit text layer

### ISSUE THREAD

**Issue by lemvria** [photopea/photopea#5442]
Hello, I keep having this issue where I will create a new text layer. Then close project. Then I will go back to the project and I won't be able to select and edit the text I was just working on. I saw that another person had a similar issue back in 2017, but I can't select the text box at all. It only creates a new text layer. I can't even duplicate the layer to edit it. Starting over would be the only way I can edit it, I would be fine with that considering how much time I have wasted troubleshooting this issue, but I don't know what font I used, LOL.

**Comment by camoody1** [comment]
For your text layer, what happens if you...
1. Switch to the Text Tool.
2. Select the Text layer in the layer list.
3. With your mouse, click directly in the middle of your line of text.

If you hit the Backspace or Delete key on your keyboard, do any of the letters disappear? Or dors that still create an entirely new layer? If it still creates a new layer, try doing this same process but in an "In Cognito" tab just to be sure there's no weird browser extension thing going on.

If it's still a problem, share a link to your project here and I'll see if I can edit the text line. 👍🏼

**Comment by lemvria** [comment]
Hi, thanks for getting back to me so quickly! It still creates a new text layer. It may very well be a browser issue. I went ahead and recreated the layer. I will share the link though, because this keeps happening and I would love to know how to fix the issue. It will not allow me to drop the file in here. If I send the link, it will just go to a new Photopea web browser, not sure how to create a link for you to view the issue. 
By the way, I all around really love and appreciate Photopea, so thanks for helping me!

**Comment by camoody1** [comment]
You can share your project by clicking File -> Share -> PSD and then copy the resulting link and sharing it.

Just to be clear... I'm just another user like yourself. I'm not the developer. I just help people whenever I think I have something to add. The main developer is Ivan and he does far more amazing work than I could ever hope. 😁

**Comment by photopea** [comment]
@lemvria If you want a text to be editable, you should save your work as a PSD file. 

You probably saved it as a PNG or a JPG file, these files can not have editable text.

**Comment by photopea** [comment]
Just like if you take a photo of a newspaper, and open that photo in Photopea, and you click on the text, it will create a new text layer instead of editing a text written on a newspaper.

**Comment by photopea** [comment]
Your file has just one text layer, and when I click it with a Type tool, I can edit text.

Could you try it in any different browser? Brave is known to have many problems.

**Comment by photopea** [comment]
Here is how it works for me when I select "EGE" (your text box is small and the word is outside of it).

![image (1)](https://user-images.githubusercontent.com/15955558/224806406-3fcd01d6-14f1-46ea-8420-8c272b71d05d.jpg)

**Comment by camoody1** [comment]
Your project works fine on Edge Browser on my Android phone, as well. As Ivan said, your text box is very small and easily missed. I couldn't click to edit any of the letters outside the box until I resized that box to incorporate all your letters. Then, I was able to click and highlight any part of the text.

This sounds like a Brave issue, possibly.

**Comment by lemvria** [comment]
Thanks for both of your feedback. I should have clarified that the issue I was having is with the "got ordinals" text layer. Apologies for not clarifying which text layer I was referring to.

**Comment by camoody1** [comment]
> Thanks for both of your feedback. I should have clarified that the issue I was having is with the "got ordinals" text layer. Apologies for not clarifying which text layer I was referring to.

Oh goodness. That's not a text layer. 😂 That word is just an image. It may have started off as a text layer originally, but someone rasterized it at some point, so now, it's just a regular image that's not editable as text. That explains why you get a new text line whenever you click there.

**Comment by photopea** [comment]
I think you should learn about layers and the difference between text layers and pixel layers: https://www.photopea.com/learn/layers

**Comment by lemvria** [comment]
Thanks to you both @photopea & @camoody1 - I most certainly know what a text file is...but thanks very much. 

And, I am not trying to edit the word "LEGENDORDINAL" ---- I am trying to edit the phrase "got ordinals?" which I have added as a screen shot below to show that it clearly was a text layer that I created....

Again, this is not the first time I have ran into this issue using Photopea. But it has only just started recently within the last 6-7 months I would say. I did not have an issue before. Every time I would click to edit my text, it would do so, but recently I can not..

![Capture](https://user-images.githubusercontent.com/36755368/229355384-1eabd5c5-923d-4cdc-a989-ec10a81090c9.PNG)

**Comment by photopea** [comment]
As I said, that layer is not a text layer. Maybe it was a text layer in the past, but somebody rasterized it.

If you think Photopea rasterizes layers without telling you, show us some proof, e.g. a video of it happening. Nobody else out of our 12 million users reported this problem. So I think you just need to learn how Photopea or Photoshop work.

**Comment by camoody1** [comment]
The "got ordinals" layer is NOT a text layer in your project. You are mistaken. It is simply a standard rasterized layer which cannot be changed using the Text Tool.
