### ISSUE TITLE
Bug Report: Hyperlink in Slice Not Working

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5443]
I'm following a tutorial as seen here:
https://graphicsmob.com/how-to-add-a-hyperlink-to-a-jpeg-in-photoshop-tutorial/#:~:text=How%20to%20add%20a%20hyperlink%20to%20a%20jpeg,the%20slice%20options%20pop-up%20window.%20...%20More%20items

I'm attempting to create a slice on an image, embed a hyperlink into it, and then export the project as a PDF. I want to be able to have someone open that PDF and click on the image slice to open a new window to the website I embedded.

I can create the slice. I can embed the Hyperlink. And I can export the project as a PDF. Bit when I open the PDF, the there's nothing clickable in the image. The hyperlink doesn't seem to have been exported.

This should work, yes? Or am I doing something wrong?

**Comment by photopea** [comment]
Hi, I have implemented it! If you have a slice with a link, it will be converted into a clickable area in a PDF file (and clicking it should open a link).

I dont know how your tutorial is related to it, as it is not about what you need (a PDF). I think Photoshop can not create PDF files with links.

**Comment by camoody1** [comment]
I just did exactly what I needed. Created a text area, sliced around it, added a hyperlink to a website, and then exported the project as a PDF. I was then able to open the PDF, click on the text, and go to the website. Worked perfectly. Thank you for fixing it. 😁

**Comment by photopea** [comment]
It was not fixing! You asked for a new feature, which does not exist in any photo editor.

**Comment by MichalSZZ** [comment]
Good to know about that new feature @photopea  ! I'm making many documents in Adobe Acrobat Pro in my company. Maybe some of them can be edited in Photopea.

**Comment by camoody1** [comment]
It definitely exists in Photoshop. I read a tutorial about how to do it and I also found this video. 🤷🏽‍♂️
https://youtu.be/n4GybC8bfiI

Now, they use Automate to publish their PDF and I just used Export As, but it's basically the exact same functionality, now.

Regardless, thank you for adding it to Photopea.

**Comment by camoody1** [comment]
I don't have Photoshop, I just work from tutorials and videos. If you're telling me it doesn't work in Photoshop, I believe you. Maybe it used to work and now in newer versions it doesn't. Or maybe I'm just misremembering what I saw. Regardless, what you've coded in Photopea is perfect and exactly what I needed. This new functionality matches what Figma allows users to do, and I appreciate not having to use another tool.
