### ISSUE TITLE
The selection is not well working

### ISSUE THREAD

**Issue by rutumm** [photopea/photopea#5445]
Whenever I try to select something or trying to select, photopaper automatically selects the upper part of the image instead of the selection it selects the upper part of it.

**Comment by photopea** [comment]
Could you share a screenshot so that we know what you mean? Are you aware of the auto-select option?

**Comment by rutumm** [comment]
![image](https://user-images.githubusercontent.com/127439739/224782740-3c6c3c77-3454-49f4-8bfd-9d696aba13ac.png)

While selecting and dragging, it is not getting selected from the corner which I have chosen instead; it is getting selected above the image.

**Comment by photopea** [comment]
Could you disable WebGL? Press More - Use WebGL. Does it work better?

**Comment by photopea** [comment]
There is a bug with your GPU drivers. Try to update your OS or your GPU drivers, so that you can keep WebGL enabled. Photopea will be very slow without WebGL (without GPU acceleration).
