### ISSUE TITLE
Color picker issues

### ISSUE THREAD

**Issue by Betty40** [photopea/photopea#5446]
![screencapture-photopea-2023-03-13-12_59_27](https://user-images.githubusercontent.com/89757170/224759374-a76ba5f4-200b-4773-9c6b-318b8a13fb8d.png)

I'm having issues with the color picker, it freezes there when I choose my last gradient color. It won't close. I try to confirm my colors and close the box to move forward and I can't. The color picker box stays open and freezes. It especially does this when I pick my last color in the gradient box. When all 5 gradient colors are selected, then it freezes and I can't do anything else on the design. It also does this on the effect stroke with the color picker box. 

Please fix this, it's been like this for a really long time.

Thank you!

**Comment by photopea** [comment]
Hi, what exactly should I do after opening www.photopea.com to see this problem myself?

**Comment by camoody1** [comment]
@Betty40 Specifically, if you could record a short video of you doing the exact process that causes the lockup and then upload it here, that would be most helpful for the developer. Thanks 👍🏼

**Comment by photopea** [comment]
Lets discuss it here: https://github.com/photopea/photopea/issues/5583
