### ISSUE TITLE
Photopea doesn't work with non standard keyboard layouts

### ISSUE THREAD

**Issue by PaulineNemchak** [photopea/photopea#5447]
Currently photopea doesn't work with other keyboard layouts but qwerty (you have to use QWERTY hot keys and it is difficult to remember).

**Comment by photopea** [comment]
What web browser do you use? Could you try Chrome or Edge?

**Comment by photopea** [comment]
Photopea does use the Keyboard API, and as I said, non-English keyboard layouts work for me in Photopea. Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
We have fixed it three years ago https://github.com/photopea/photopea/issues/1839
