### ISSUE TITLE
Text exists in layers, but is not actually visible on the page

### ISSUE THREAD

**Issue by yehuditSofer** [photopea/photopea#5448]
I create a text layer, using the Create Text button,
increases the font to a large size, writes the text,
But the text is not visible, even though it is found as an upper layer,
I choose the move tool button,
And there I select the shape change controllers check box,
but see nothing
They have something I'm missing here,
I'm just pointing out that this is not the first time I've used this software,
And nothing like this has ever happened to me...

**Comment by photopea** [comment]
Hi, try this, let us know if it helped: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by camoody1** [comment]
> I create a text layer, using the Create Text button, increases the font to a large size, writes the text, But the text is not visible, even though it is found as an upper layer, I choose the move tool button, And there I select the shape change controllers check box, but see nothing They have something I'm missing here, I'm just pointing out that this is not the first time I've used this software, And nothing like this has ever happened to me...

Create a text line just as you've written here (even if it seems to be invisible) and share your project link here. I'd like to see what exactly you've got.

**Comment by photopea** [comment]
I have to close it because of lack of details.
