### ISSUE TITLE
photopea filter

### ISSUE THREAD

**Issue by lparsonsss** [photopea/photopea#5449]
Filter Gallery keeps freezing, was just working fine yesterday.

**Comment by photopea** [comment]
Hi, what should I do to make Photopea freeze?

**Comment by photopea** [comment]
These filters can take up to 1 second per 1 million pixels. So if you have 25 MPx, it can take 25 seconds to apply a filter.

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by photopea** [comment]
There was a bug in the Cutout filter, which is fixed now.
