### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by suburbansteve** [photopea/photopea#5452]
Hi when opening photopea and adding layers to image the icon for each layer is blank the eye showing if the layer is visible and all the other  icons like the folder  and linked layers are just blank.
I've restarted and tried again with the same results.
any help would be appreciated, thanks
![Screenshot (1)](https://user-images.githubusercontent.com/101486716/225426417-21ce18e6-d36a-4db4-bec5-67eb287970d1.png)

**Comment by photopea** [comment]
I see you use lots of browser extensions. Try this first: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by suburbansteve** [comment]
Thanx a lot , after reading through the page in the link I opened it in a incognito page and it opened perfectly with everything showing as it should.
Thanks again

**Comment by photopea** [comment]
You have a browser extension, which breaks Photopea. You should learn about what your extensions actually do.

**Comment by photopea** [comment]
You have a browser extension, which breaks Photopea. You should learn about what your extensions actually do, once you allow them to modify all websites that you are visiting.
