### ISSUE TITLE
Fix color of "current" file

### ISSUE THREAD

**Issue by impressivewebs** [photopea/photopea#5453]
First of all, love the tool! I couldn't do my work without it.

When I open more than one file in Photopea, this is what I see:

![jJGfCgq](https://user-images.githubusercontent.com/558709/225440909-fc9b7db3-17af-4e28-adc3-86ee2cc4430a.png)

In this example, the "current" tab (according to Photopea) is the one with the lighter color. But from a UI/UX perspective, this is not correct. The current tab should be the one that is the same color as the area below it. This would indicate that it's "in front of" the other one. This coloring is backwards so I find it confusing when dealing with multiple open files.

**Comment by photopea** [comment]
Our user suggested this UI to us and we think it looks nice https://github.com/photopea/photopea/issues/4272#issuecomment-1022639274

**Comment by impressivewebs** [comment]
@photopea I think the idea behind this look for the "tabs" is that they are "buttons", and that's why the designer chose these colors (light = "front") but due to the fact that the dark area below is the same color as the inactive tab, it makes it appear as if the dark area is part of a large "page" that includes the tab in front. I'm sure if you consult with the designer, they will see my point. :)

**Comment by photopea** [comment]
Could you draw how you want to look it instead (and not describe it with words)? I think such a change requires a lot of other changes, and it is just too much work for such a small thing.

**Comment by bluep55** [comment]
Just noticed this. The text on the current tab in Photoshop appears to be brighter than the text on the hidden tab which makes it look more obvious that this is the open tab.
In Photopea, the the text on both tabs appears to be the same brightness.
Maybe make it the same as Photoshop. 

![Untitled-1](https://user-images.githubusercontent.com/118609932/225627761-3764d7fc-7040-47c8-b033-68887276e855.jpg)

**Comment by photopea** [comment]
Ok, I have made inactive panels text darker.

**Comment by impressivewebs** [comment]
@photopea Drawing it wouldn't really make a difference. What you see in the image I sent is exactly what I would do except the dark one should be the "active" one. Like I said, the reason the dark one appears to be the active one is because the dark background of the button matches the dark background of the area around the canvas below. So it all looks like one active unit.

Of course, if there were 3 or more files open then it would have a different effect. In that case, maybe the "light" button looks more prominent. But with two open it's very confusing which one is the active file.

**Comment by photopea** [comment]
I think the majority of the users prefer the way it works now, so in order to satisfy you, I would make lots of others angry :( I will leave it as it is.

**Comment by impressivewebs** [comment]
@photopea Not a problem, I completely understand. It would be nice to hear from other users to see if they agree, but if you think it's best this way, then that's fine.
