### ISSUE TITLE
Feature Request: Allow to Change Color of Guidelines

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5456]
As discussed in this Reddit post: [Link ](https://www.reddit.com/r/photopea/comments/11s5o1n/is_it_possible_to_change_the_color_of_the_ruler/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button) 

This is not the first time I've seen this request. User would like to be able to change the color of guidelines in Photopea (and potentially other lines) to make them more visible against images with similar colors as the default. Reddit post includes a screenshot of similar options from PhotoShop.

**Comment by photopea** [comment]
You can change it now in Edit - Preferences :)
