### ISSUE TITLE
Displacement map misaligned after applying transform warp

### ISSUE THREAD

**Issue by lucadalli** [photopea/photopea#5459]
The displacement applied to a SmartObject which has been warped appears to be misaligned.
I am more or less doing the steps described in [this tutorial](https://photoshopcafe.com/best-way-to-make-displacement-maps-in-photoshop-wrap-anything-around-any-surface/#:~:text=LET%E2%80%99S%20USE%20WHAT%20WE%20HAVE%20LEARNED%20TO%20WRAP%20A%20LOGO%20TO%20A%20TSHIRT%20IN%20PHOTOSHOP).

**Without warp** it works as intended:
![image](https://user-images.githubusercontent.com/39853447/225903920-128613dc-7fec-449b-8b3e-7f9b7f8a50c8.png)

**With warp** the displacement appears to be misaligned:
![image](https://user-images.githubusercontent.com/39853447/225901571-79fee641-0f4a-4e23-9a8b-1ece2e3862c1.png)

**Comment by photopea** [comment]
Could you describe simple steps how can we see it ourselves?

**Comment by lucadalli** [comment]
On further investigation, this is likely **not** a bug but more so my lack of understanding about how the displacement maps are applied. I can't for the life of me figure out how the displacement map is positioned.

If the SmartObject, document and displacement map are all the same size, the displacement is applied as expected.
If the SmartObject is smaller than the document, moving the SmartObject and reapplying the displacement map seems to influence the position of the displacement. This means that unlike a layer mask, the displacement is **not** applied relative to the document but is influenced by the position of the SmartObject.

I've been Googling and asking ChatGPT but can't find any good resources about how the displacement map position is determined. @photopea Are you able to provide some guidance?

**Comment by lucadalli** [comment]
I think I managed to resolve the issue. The displacement map was being stretched because the warp was causing part of the SmartObject bounds to go out of document bounds. When this happens the displacement map is stretched to cover the both SmartObject and the document, causing the displacement to be misaligned.

**Comment by photopea** [comment]
That is right, Smart filters are applied on the warped image, not on the original image. But you can have smart objects inside smart objects, etc.
