### ISSUE TITLE
Fill type gradient and pattern fly down panel too large hiding canvas contents

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#546]
In shape tool, the fly down panel for Fill type gradient and pattern is too long hiding much of the canvas, the % and px after each sliders each occupy a new line instead of staying on their own line, which create lots of dead space.

**Comment by hgs54371** [comment]
This is also a browser specific problem, on safari it's fine but not in firefox, both on mac

**Comment by photopea** [comment]
Can you send us a screenshot? Can  you try making the panel a little wider, if it helps?

**Comment by hgs54371** [comment]
![screen shot 2018-03-14 at 9 40 36 pm](https://user-images.githubusercontent.com/36803688/37405790-8c273350-27d0-11e8-8d5b-b1291de7ecfd.jpg)![screen shot 2018-03-14 at 9 41 07 pm](https://user-images.githubusercontent.com/36803688/37405812-a29e7436-27d0-11e8-928e-2ea84bd0277e.jpg)

Change width to 21 em helped

![screen shot 2018-03-14 at 10 00 43 pm](https://user-images.githubusercontent.com/36803688/37406890-42fe8d1a-27d3-11e8-8a3f-26e89b7f5f13.jpg)

**Comment by photopea** [comment]
This should be fixed now, too :)  Thanks!
