### ISSUE TITLE
Can't install plugins that are not made public

### ISSUE THREAD

**Issue by yankooliveira** [photopea/photopea#5461]
Hello!

I wanted to explore some of the possibilities for Photopea plugin development, but seems I can't have plugins installed in something similar "development mode" - i.e.: the only way to install a plugin is to make it publicly available.

**Step by step:**
1. Window -> Plugins -> click Add Plugins
2. Click New -> set up plugin -> do **not** check "Make public" box -> Click save
3. Plugin is listed under account, but not installable
4. Edit plugin -> tick the "Make public" box -> Save plugin
5.  Plugin is now accessible and installable

**Expected behaviour:**
1. Create new plugin, do not tick "Make public" box
2. Plugin is installable/uninstallable via "Add Plugin" list in profile, or listed just to your account 

Let me know if I did something wrong or if this is intended behaviour and it's ok to add unfinished plugins as public.
(And thanks for the great work in Photopea!)

**Comment by camoody1** [comment]
I'm not the developer, but I look forward to seeing what Plugins you come up with.🙂

**Comment by photopea** [comment]
You can make a plugin public, install it, and unpublish it. It will stay installed for people who installed it while it was public.

But you can add plugins to your Photopea using the URL string, as described here: https://www.photopea.com/api/
