### ISSUE TITLE
Tela cheia não funciona

### ISSUE THREAD

**Issue by LucasFilho** [photopea/photopea#5465]
Usando o clique na opção de tela cheia ou através do menu, a tela cheia não é ativada.

**Comment by LucasFilho** [comment]
Uso o Chrome em um ChromeBook. Já usava essa opção há vários meses, mas deixou de funcionar.

**Comment by photopea** [comment]
Sorry, I speak only English :(

**Comment by camoody1** [comment]
He wrote:

"I use Chrome on a ChromeBook.  already used this option several months ago, but no longer work."

**Comment by photopea** [comment]
Do you mean the fullscreen button at the top? Or how do you switch to fullscreen?

Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by mrst2023** [comment]
Alguém sabe como tirar aquela borda da direita do photopea, no meu fica só isso e olha que nem aparece anuncio por causa das extensões do meu notebook

**Comment by camoody1** [comment]
> 

This is not a question for GitHub. You should ask this kind of question on Reddit.

**Comment by camoody1** [comment]
> Alguém sabe como tirar aquela borda da direita do photopea, no meu fica só isso e olha que nem aparece anuncio por causa das extensões do meu notebook

This is not a question for GitHub. You should ask this kind of question on Reddit.
