### ISSUE TITLE
Ctrl Key Becomes Stuck

### ISSUE THREAD

**Issue by jackyyang09** [photopea/photopea#5467]
### Issue
Sometimes the Ctrl key stays pressed even when I have it unpressed. This is an issue because I frequently access the Hand tool with the Space key. The resulting Ctrl+Space shortcut turns it into the Zoom tool and I inadvertently zoom in/out a whole bunch and mess up my view. 
The issue eventually goes away after I press the Ctrl/Left-Alt/Shift keys a bunch. This is not an issue with my keyboard.

### How to Reproduce
I haven't been able to reproduce it intentionally, but it would happen frequently enough that it interferes with my workflow.
However, it occurs more often when Alt+Tabbing between windows and when using moving text with the Text tool (an operation that makes use of the Ctrl key).

### Other Details
I downloaded Photopea as a standalone app via Brave Browser. I'm currently running Windows 10.

**Comment by photopea** [comment]
If you release the Ctrl key outside Photopea, Photopea will not know you have released it. So in that case, we can not fix it :(

**Comment by photopea** [comment]
I have to close it because of lack of details
