### ISSUE TITLE
new patterns

### ISSUE THREAD

**Issue by Pashta2** [photopea/photopea#5468]
Loading new pattern is not working.

**Comment by camoody1** [comment]
Exactly what is happening? Step by step, what do you do and what happens? Which web browser are you using? Have you tried doing this in Incognito Mode? Have you tried restarting Photopea to see if that makes a difference? Could you record a short video showing exactly what is happening? Thank you.

**Comment by photopea** [comment]
It seems to work fine for me. What should I do to see it not working? How do you "load patterns"?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
