### ISSUE TITLE
Loading

### ISSUE THREAD

**Issue by FoxyNova** [photopea/photopea#5470]
The white loading bar is not going away. I restarted my pc, cleared browsing data, ended the task, signed out, and everything. It is not going away and I can't see the tool tabs when I am working.

**Comment by photopea** [comment]
Hi, could you show me a screenshot of the loading bar that you see?

Also try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details :(
