### ISSUE TITLE
Loading Glitch

### ISSUE THREAD

**Issue by averageIndividual9** [photopea/photopea#5471]
Hey, I just finished a project on Photopea and when I went to look at it the PSD it would get stuck on the "Loading" message. I thought it might have been a computer issue so I tried to load the PSD on a different computer and got the same Loading message there too.
Here's the link: https://www.photopea.com/#iyWeFCY-e.psd

**Comment by photopea** [comment]
Hi, I can not open your link. It seems like such file does not exist. You are mentioning some PSD, could you share that PSD file with us?

**Comment by averageIndividual9** [comment]
Unfortunately I only saved it as the link, I have had no problem with saving my projects in this format until now.

**Comment by photopea** [comment]
It is hard to tell what happened :( Whenever I publish a PSD, it is always saved correctly and the link works.

Could you try to save any document again (on the same device), does the new link work?

**Comment by averageIndividual9** [comment]
Yeah i'll check

**Comment by averageIndividual9** [comment]
https://www.photopea.com/#igBb5k9G9.psd
Yeah this works

**Comment by photopea** [comment]
I still dont know what happened in your case :(

When you publish a PSD, can you open that link in a browser, to make sure that it works? If the link does not open, save your file as a PSD to your computer. Only then, close Photopea.

Also, try to disable your browser extensions. Maybe some of them is breaking the functionality of Photopea.
