### ISSUE TITLE
Templates are loading forever

### ISSUE THREAD

**Issue by onuroski** [photopea/photopea#5472]
when i use vpn it is okay but without vpn it is not workingç

**Comment by photopea** [comment]
Hi, are you from Turkey? Your government could be doing a censorship (they do not allow you see certain web content).

Our files are stored at https://www.backblaze.com/, can you open that website?

**Comment by onuroski** [comment]
This website is not blocked.

**Comment by onuroski** [comment]
![image](https://user-images.githubusercontent.com/56877309/226709566-c7ca37f5-7081-4343-aeb5-7289f0287139.png)

**Comment by photopea** [comment]
Can you open and save this link? https://f000.backblazeb2.com/file/psdshared/4X9O4-US

**Comment by photopea** [comment]
Maybe ask your internet provider about it. It is a regular link which should work for everyone with an internet access.

**Comment by onuroski** [comment]
Too many people cannot open templates in Turkey. I asked my friends. They couldn't open either. Can you fix this problem maybe keeping all the templates in other links?
![image](https://user-images.githubusercontent.com/56877309/227199942-d6017cd2-db2d-4b8a-8c0e-b612f36450ef.png)

**Comment by photopea** [comment]
It seems like the Turkish government is blocking our cloud storage. We can not do anything about it. They could start blocking Photopea.com or Google.com tomorrow :(

We can not fix Photopea, you should fix your government.
