### ISSUE TITLE
artboards - Changing artboard size, transforms all artboard guides to global guides

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5473]
When changing the artboard size from properties tab, all artboard guides convert to global guides.
[Screen recording 2023-03-21 22.49.58.webm](https://user-images.githubusercontent.com/11801254/226781118-0ead1d7e-69dc-42e5-ae08-341a9f9227f0.webm)

**Comment by photopea** [comment]
I am very sorry, it is fixed now.
