### ISSUE TITLE
I'm having Issues with Saving

### ISSUE THREAD

**Issue by CxryzNFTs** [photopea/photopea#5474]
Hello,

I am having issues with saving in photopea. I have multiple projects failed to save because of this, and I don't know why! When I press "Ctrl + S" to save my project, it says "Saving..." and then after a few seconds, the "Saving..." message disappears. I still see the * by the file name, like New Project.psd*, so I know it's unsaved. I keep trying, pressing the Save button but nothing works. Please fix this glitch, I've lost many projects because of it..!

**Comment by photopea** [comment]
Hi, how exactly did you open your file? Did you open it from a computer, or you created a new one from scratch? Also, did you open a PSD, a JPG, a PNG ... ?

So you are not able to save any file at all, ever, or you were able to save sometimes? 

If you can never save any file at all, try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details :(
