### ISSUE TITLE
The interface of the online version of Photopeaha been minimalised

### ISSUE THREAD

**Issue by MarzenaDom** [photopea/photopea#5475]
Good morning, the interface of the online version of Photopea has been minimalised during usage.
I must have pressed a button and scroll - no idea. Now I cannot restore initial settings and use the programme.
Please help,
Marzena

**Comment by MichalSZZ** [comment]
Could you paste here a screenshot of what you are seeing? This can help us a lot to help you.

But here are the most common problems with the interface:

- If you have small UI, letters, and icons - you probably zoomed out your view in the browser. Try to look for the three dots or three lines on the top right side of the window. Then search for the "zoom or 'powiększenie'" and set it to 100%.
- If your toolbars disappeared - try to hit 'F' on your keyboard or the 'Tab' button a few times.

**Comment by photopea** [comment]
Hi, you need to reset the webpage zoom to 100%, see https://support.google.com/chrome/answer/96810

**Comment by MarzenaDom** [comment]
It has worked :) Thank you so much!
