### ISSUE TITLE
Variables - Variable for file names option

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#5476]
I didn't find any description of how to use it on Photopea's Learn page.

There is a text box in the "Variables" window and the "Export as" tab.

Is there an option to use some individual text + variable operation? For example:
'myProjectName' + Variable1 + 'final'

Now it is an Input with the type "text" - but if it uses only variables, shouldn't be a Select with Options to choose from column names in the CSV file? it will be more intuitive to use it like that. I tried and if I write my Variable "from hand" it will export correctly using rows from CSV file.

**Comment by photopea** [comment]
You can either keep a default names, or write file names as a CSV column, for every item.

**Comment by MichalSZZ** [comment]
@photopea I tried to name it by typing something in that text box, but the final images aren't with my file name typed in that input...

Can you try it?

**Comment by photopea** [comment]
You should enter the name of a variable ( a column in a CSV) into the text box.

**Comment by MichalSZZ** [comment]
OK, if I can't type my own file namein that text box - why you just don't change it to Select with predefined options from columns name? That is user friendly solution more better than letting user to type there anything.
