### ISSUE TITLE
New Feature: Photoshop Stable Diffusion Plugin?

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5478]
I don't have PhotoShop and I really don't know how its plugins work, but I just read an article about a new Stable Diffusion plugin for Photoshop that does everything you could ever want for an AI addition to Photopea. Is this plugin, or its functionality, in anyway able to be add to Photopea?

https://www.windowscentral.com/software-apps/this-photoshop-plugin-lets-you-add-ai-generated-elements-or-edits-within-seconds

Watch the video in the embedded Tweets in the article. The mountain art process is absolutely amazing.

**Comment by photopea** [comment]
The users of this Photoshop plugin have to pay a fee of 5 - 10 USD a month to Stability AI.

I dont think any of our users would be ready to pay, so it makes no sense to make a similar plugin for Photopea.

**Comment by camoody1** [comment]
Probably. On the other hand, if they're saving $15 per month by not subscribing to Adobe, maybe they'd spend that money on Stable Diffusion. 🤷🏽‍♂️😆

It sure is an amazing little process, though.

**Comment by photopea** [comment]
I used a photo of a woman from your link and tried our text-to-image plugin with inpainting, it worked quite well.
![image (2)](https://user-images.githubusercontent.com/15955558/236062169-acb7af45-415b-4107-9b12-74e123eab9e6.jpg)
![image (3)](https://user-images.githubusercontent.com/15955558/236062173-1b7d4740-05fb-4190-89ad-17d1fc3216a4.jpg)
![image (4)](https://user-images.githubusercontent.com/15955558/236062174-e6b77f90-dd4c-4906-96ea-9745fb4425ca.jpg)
![image (5)](https://user-images.githubusercontent.com/15955558/236062175-753a7411-55c5-4930-a901-c8a05a2ff166.jpg)
![image (6)](https://user-images.githubusercontent.com/15955558/236062177-b600e113-e22a-4471-86c1-e439a48fd563.jpg)
