### ISSUE TITLE
Edit adjustment layers

### ISSUE THREAD

**Issue by AdamD1986** [photopea/photopea#5479]
I'm in need of adjusting adjustment layers to remove glare from someone's eye wear and the way I've learned to do it is to create a curved layer and paint over it.  Photopea won't let me do this?

**Comment by photopea** [comment]
You probably painted over the raster mask of the adjusment layer. Please, ask for hepl here: https://www.reddit.com/r/photopea

**Comment by AdamD1986** [comment]
Is there another way to do what I'm trying to do?   The way I described is
ultimately how it's done in Photoshop.

**Comment by camoody1** [comment]
Could you record a video of exactly what you're trying to do? Or link a YouTube tutorial showing what you're describing from within Photoshop?

**Comment by AdamD1986** [comment]
https://www.youtube.com/watch?v=plOsuoh0eFg
