### ISSUE TITLE
Text of layer name in layers panel lower than layer icon

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#548]
This is specific to safari on mac, the text of layer name is lower than the layer icon before it, and partly cut off at the bottom

**Comment by photopea** [comment]
Hi, are you using the latest Safari?

**Comment by hgs54371** [comment]
Not that old but just updated anyway, still sinks down and cut off at the bottom, 
the "Layer" looks like "Laver"

**Comment by photopea** [comment]
I don't have an access to Safari to test it out. Could you maybe play a bit with Developer tools and find some CSS change, that would solve it?

**Comment by hgs54371** [comment]
I can find a file called all.css, which property should I change to what that would help?

**Comment by photopea** [comment]
Try Developer tools - web inspector. You should be able to change CSS "live" in the inspector, without reloading the website. https://developer.apple.com/safari/tools/

**Comment by hgs54371** [comment]
Is this the right place?
![screen shot 2018-03-14 at 9 47 01 pm](https://user-images.githubusercontent.com/36803688/37406130-620d70e2-27d1-11e8-8ef0-4ef8ae1f70c7.jpg)

**Comment by photopea** [comment]
Try to change it in Elements, not Resources

**Comment by hgs54371** [comment]
Found it, how could I change it that would help

![screen shot 2018-03-14 at 10 05 14 pm](https://user-images.githubusercontent.com/36803688/37407238-27e75074-27d4-11e8-8a51-e3558a311c9e.jpg)

**Comment by photopea** [comment]
you can rewrite, add or delete CSS right in the area on the right side. The top of the Label was supposed to be at the same height, as the top of the thumbnail.

**Comment by hgs54371** [comment]
I tried this, still nothing helped, any suggestions?

![screen shot 2018-03-14 at 10 32 42 pm](https://user-images.githubusercontent.com/36803688/37408732-a9b09a18-27d7-11e8-97e6-38bd8f6e9d2a.jpg)

**Comment by photopea** [comment]
Ok I reported a bug to WebKit. Hope they will fix it soon. https://bugs.webkit.org/show_bug.cgi?id=183637

**Comment by hgs54371** [comment]
How's this issue progressed, it haven't been fixed

**Comment by photopea** [comment]
I reported it to Apple, but they want a reduced case, which I can not make without a Mac OS device :(
