### ISSUE TITLE
Photopea keeps opening old project that doesn't even have on my computer anymore

### ISSUE THREAD

**Issue by ghost** [photopea/photopea#5481]
Hello. When I go to use my photopea, it keeps opening a previous project that I made, which is not even on my computer anymore, how do I stop loading that project, every time I open photopea

**Comment by camoody1** [comment]
Try clearing your browser cache.

**Comment by photopea** [comment]
Hi, we introduced a new backup mechanism, such that if your browser crashes, the old version of a document is still stored.

If you close that document properly (with the "X" button), it should not appear ever again. BTW. do you use Photopea in more than one panels at the same time?

**Comment by TheRadicalDreamer** [comment]
that new mechanism saved me last week. I was impressed to see the file again after photopea closed for not enough ram. I though it has a miracle, but now i know the saint :D

ThankS!

**Comment by Wanambisix** [comment]
Hi Photopea, the problem I have encountered with this new saving mechanism is that even if you properly close the file with the X, it will still load the previous unsaved versions of the file. Sometimes it loads more than 10 projects at a time which consumes lots of ram and leads to the browser freezing. If it is possible to make the mechanism not load already saved files it would be great.

**Comment by photopea** [comment]
Try to close all projects and reload Photopea. Do projects still appear? Do you have Photopea opened in more than one tab?

**Comment by Wanambisix** [comment]
They still appear after reloading. And if you manually close them and do a new project...the new project will also be part of the unsaved projects loading the next time you open Photopea. They just keep adding themselves. The only way of stopping this has been clearing cache and stored data which also deletes saved fonts. I use Chrome.

**Comment by Wanambisix** [comment]
![screenshot-www photopea com-2023 04 04-12_36_11 (1)](https://user-images.githubusercontent.com/105554573/229752354-56b41909-6bbc-4da9-ad22-0a78eedb1b9e.png)

This is after reloading.

**Comment by photopea** [comment]
Do you use it in a web browser, or in the "installed" mode - a single Photopea window?

Also, do you use any browser extensions? Could you show us a screenshot of "about://extensions" ?

**Comment by Wanambisix** [comment]
After disabling extensions it has not loaded the incomplete projects. I think the problem is the extensions. I will check and let you know which plugin is causing Photopea to behave this way.

**Comment by photopea** [comment]
Did you find out which browser extension was preventing Photopea from working properly?

**Comment by Wilbercorvid** [comment]
I also tend to have the similar issue too. When I opened up Photopea, it opened up about 20 projects. Even when I tried a few things, like closing the projects, or even refresh the page several times, they still appear. It does get rather annoying since there are some projects I don't want to work on anymore, or if there's already a project I've finished since.

**Comment by photopea** [comment]
You should be able to find an answer here: https://www.photopea.com/tuts/photopea-opens-up-old-files/
