### ISSUE TITLE
Suggestion: When using Crop, if you click Move Tool to perform cropping

### ISSUE THREAD

**Issue by carboncrystal** [photopea/photopea#5482]
**Suggestion:** When using Crop in Photopea (where you've already set your cutting area ), **if you click after the MoveTool** to perform cropping. 

This is the default behavior in Photoshop, it is very hard to get rid of this habit.

**Comment by camoody1** [comment]
I don't understand what you're saying. Please re-read what you have written, and then add some more information to more fully explain what you're asking.

**Comment by carboncrystal** [comment]
I'm sorry you didn't understand what I meant.
Below are the steps to reproduce:

**1. Open the photo in Photopea  > select the crop tool and select your crop area**

![Screenshot from 2023-03-25 08-26-08](https://user-images.githubusercontent.com/106466414/227700974-41bda647-87d8-413b-9576-162ecd7ae8b1.png)

**2. At this point in Phtoshop if you click on the Move Tool the cut is performed.**

![Screenshot from 2023-03-25 08-32-22](https://user-images.githubusercontent.com/106466414/227701132-06dec4ca-1918-4c4e-a46e-1e673135b837.png)

This is simply how Photoshop works. If you click on the Move Tool once you have selected the cropping area, the crop is performed.

In Photopea if you click on Move Toold after selecting your cropping area (out of habit), it cancels everything and you have to start from the beginning with the whole process :(

**Comment by camoody1** [comment]
Ah, okay. This is much clearer. Thank you.

**Comment by carboncrystal** [comment]
You're welcome!
By the way, Photoshop has almost the same behavior "to perform the current operation"  on almost everything if you click the Move Tool once current operation is performes (e.g Rectangle Select, Ellipse Select, Shape etc).

For those coming from Photosop it is very annoying to have their current operation "cancelled" just because they habitually click on Move Tool!

**Comment by photopea** [comment]
It should be implemented now. When you have a cropping rectangle, and you switch to any other tool, the cropping is confirmed before switching to another tool :)

**Comment by carboncrystal** [comment]
OMG, so fast! 
Thank you!

**Comment by bluep55** [comment]
This is so much better now when using on mobile phone.
No longer have to scroll all the way to the right hand side of the top menu bar to get access to the confirmation tick✔.
👍👍👍

**Comment by photopea** [comment]
I wish people reported more features like this, which make life easier (and dont require weeks of work on my side). I am not a user of Photopea myself.

**Comment by camoody1** [comment]
You don't use your own software?!

I feel like I'm being cheated on.

**Comment by photopea** [comment]
I am a programmer, I write code, but I made icons for Photopea in Photopea :)

**Comment by camoody1** [comment]
What made you decide to write Photopea? Usually, a one man team like yourself takesmon a big project like this because they have a need for something, so they just make it themselves. You just decided to try to recreate Photoshop for the heck of it?

**Comment by photopea** [comment]
I gave a talk about it https://www.youtube.com/watch?v=IZmaeC_Ma5A

**Comment by camoody1** [comment]
> I gave a talk about it https://www.youtube.com/watch?v=IZmaeC_Ma5A

That was a great video to watch. Thank you for the link. That was four years ago... are you still as passionate for the application as you were then? What are your plans going forward? Are you just basically in maintenance mode for Photopea at this point? Or do you have a roadmap of additional functionality you want to add? Or maybe you're building something else entirely, now? Just wondering. It's all so interesting how one guy just decided to take on Adobe. 👍🏼

**Comment by bluep55** [comment]
In reply to your comment yesterday about reporting more features like this to make things easier (and don't require weeks of work on your side). Would it be difficult to add 'Original Ratio' to the Crop Tool drop down menu, the way it is in Photoshop. This would make it simpler, especially on mobile phone, by not having to activate 'Shift' on the 'Virtual Keys' to keep the original ratio, then forgetting to turn 'Shift' off 😄

![Crop Tool Aspect Ratio](https://user-images.githubusercontent.com/118609932/227787380-63e8ec49-438a-42e7-a985-7304a80ce908.jpg)

**Comment by photopea** [comment]
Done! Also, I have added some pre-defined ratios, and a button for swapping the horizontal / vertical values.

**Comment by MichalSZZ** [comment]
Great job Ivan! Please add 4:3 ratio too.

**Comment by photopea** [comment]
Done :)
