### ISSUE TITLE
Feature Request: Content-Aware Vector Tracing

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5483]
This would be a really nice addition to Photopea and/or the new Vectorpea that you're working on.

https://youtu.be/PRpnPxHkkf8

**Comment by photopea** [comment]
I have no idea how it works. Did you try our Vectorize tool? https://www.photopea.com/learn/vg-vectorize

Are you sure this tool works better?

**Comment by TheRadicalDreamer** [comment]
it is similar, but maybe with that tool you can make better selections fo the shapes to be vectorized?? i dunno

**Comment by camoody1** [comment]
> it is implemented? Or discarted?

I just closed it because it didn't seem like Ivan felt it was needed. I still think it might be a nice addition to his Vectorpea applcation, but that's entirely his decision.

**Comment by photopea** [comment]
It seems like it is a Magnetic Lasso, which smoothens the curve.

I am not sure if we should invest our time into it, or invest time into improving one-click solutions like Image - Vectorize Bitmap. @camoody1 How often do you use this feature in Phtopshop?
