### ISSUE TITLE
复制并重复变换制作放射状背景

### ISSUE THREAD

**Issue by roseSting** [photopea/photopea#5485]
ctrl+alt+shift+t 不会进行复制

**Comment by photopea** [comment]
You can do ctrl+alt+shift+t to repeat the last transformation.

**Comment by MichalSZZ** [comment]
In Photoshop this shortcut makes layer duplication for each new transformation (new layer for raster and smart objects / adding a new shape in one layer for shapes).
Now in Photopea, it works like Ctrl + Shift + T in Photoshop.

**Comment by MichalSZZ** [comment]
@nothingshiru I agree. I use copy and repeat transform by using a shortcut. I don't use simple repeat transform function.

**Comment by photopea** [comment]
ok, Alt+Shift+Ctrl+T (or Shift+Ctrl+T in an environment which allows Ctrl+T) will duplicate selected layers and apply the last transform on them.
