### ISSUE TITLE
Folder is too small for finger

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#5486]
Could you make it as big as other layers？![Screenshot_2023_0328_003326.png](https://user-images.githubusercontent.com/79258245/228006834-d721e343-e0a9-4edc-a973-9e1a621f8e89.png)

**Comment by camoody1** [comment]
I, too, suffer from large fingers.

**Comment by TheRadicalDreamer** [comment]
![image](https://user-images.githubusercontent.com/11801254/228033233-0b550604-914f-471a-ad0d-0d73f66f8818.png)

Even huge thumbnails don't change the size of the folder.

Maybe the modify thumbnail size should affect folder icons as well

**Comment by photopea** [comment]
ok, I have made it 50% larger.

**Comment by camoody1** [comment]
I just refreshed my browser and the group "folder" layers still look the same size to me.🤷🏽‍♂️

**Comment by photopea** [comment]
It should definitely be larger, could you share a screenshot?

**Comment by TheRadicalDreamer** [comment]
Maybe it have to increase/decrease size with the increase/decrease thumbnail size, so each person can set it to the size they want to.  🤔

![image](https://user-images.githubusercontent.com/11801254/228301743-7519825f-35ed-4c38-ae45-cacc5273d076.png)

**Comment by camoody1** [comment]
I've attached 4 images. Each image is of a slightly larger thumbnail size as selected in the Layers menu. The folder section starts small and stays small. You can see that it isn't even tall enough to fit the entire letter "g". I would like to see it tied to the size of the other thumbnails. Or maybe just let it grow with the other thumbnails up to a max size twice as large as it is now.

![SmartSelect_20230328_213109_Edge](https://user-images.githubusercontent.com/73725653/228403429-f6d58af3-471a-4050-9bd5-2941a829b5fc.jpg)
![SmartSelect_20230328_213128_Edge](https://user-images.githubusercontent.com/73725653/228403432-e007a42b-0658-4ed4-93da-8770825ae50d.jpg)
![SmartSelect_20230328_213152_Edge](https://user-images.githubusercontent.com/73725653/228403434-54bcc308-6d1e-47ab-bb9a-48e6624d0f4d.jpg)
![SmartSelect_20230328_213215_Edge](https://user-images.githubusercontent.com/73725653/228403436-c6dd2919-826f-45c3-a7a4-033c34e58c70.jpg)

**Comment by photopea** [comment]
I am very sorry, there still was an error, it should work better now.
