### ISSUE TITLE
Clip mask dont work on text

### ISSUE THREAD

**Issue by BYTEZZ5** [photopea/photopea#5487]
If I clip mask for example, if I make a shape with pen tool and try to clipmask it on text, it just goes invisible, this issue is only with text, on images clip mask works fine.
![Nayttokuva_371](https://user-images.githubusercontent.com/129151839/228217598-d3125aed-70af-41e3-a08f-06cc28004cc1.png)
![Nayttokuva_370](https://user-images.githubusercontent.com/129151839/228217632-5560011d-4475-4faa-941e-8fef0738c6be.png)

**Comment by photopea** [comment]
This is how it should work. The old layer is drawn first. Then, the clipping layer on top is drawn. Then, layer effects are drawn (gradient Overlay in your case).

**Comment by BYTEZZ5** [comment]
What is "eff" where can I find it?

**Comment by BYTEZZ5** [comment]
And how do I turn it off, I dont see an option for it?

**Comment by BYTEZZ5** [comment]
Oh yes it worked, thanks alot.
