### ISSUE TITLE
lost progress

### ISSUE THREAD

**Issue by jjraw12345678** [photopea/photopea#5489]
did ctrl+s to save. it said it would save under said name, cant be found. its gone.

**Comment by bluep55** [comment]
If its the first time you've saved it and used ctrl+s, it normally saves as a PDF file (PSD logo shown below).
The first time you save this way it should ask you where you want to save it and show you the folder where its going.
If you can't remember which folder it was saved to try repeating the process with a newly created document, when the 'Save' window opens, take note where this document is being saved to.
Your lost document should be in the same place.

![Screenshot 2023-03-28 225947](https://user-images.githubusercontent.com/118609932/228378585-3b875f97-e0ea-42de-9bc6-fa163705c963.jpg)

**Comment by bluep55** [comment]
Also, look in your 'Download' folder.
Photopea may have saved it there.

**Comment by camoody1** [comment]
> Also, look in your 'Download' folder. Photopea may have saved it there.

Yep. Mine always save to my browser's Downloads folder by default.

**Comment by photopea** [comment]
If you open a file from a computer, and you use Chrome or Edge, Ctrl+S will rewrite the old file.

**Comment by photopea** [comment]
Otherwise, record a video of this problem, so that we know what you do.

Only problems which can be repeated, can be fixed.
