### ISSUE TITLE
Trying the postMessage API for loading an image with a base64 binary

### ISSUE THREAD

**Issue by titlestad** [photopea/photopea#549]
var data = loadedJPEGData;
var pea = PhotoPeaIframeDomObject;
var filename = 'thePath/to/image.JPG';
var type = filename.split( '.' );
type = type[ type.length - 1 ].toLowerCase();
var msg = {
	files: [
		'data:image/' + type + ';base64,' + Base64.encode( data )
	]
};
pea.postMessage( msg, '*' );

This leads to nothing happening. What am I doing wrong? Is there a JSFiddle for this?

**Comment by photopea** [comment]
Hi, the "msg" parameter (message) can be either String (for the script), or ArrayBuffer (for the file).

In your case, "msg" is a JS object, which does not have any meaning for the current API. I think you should put your "data" into an ArrayBuffer.

**Comment by titlestad** [comment]
Like this?

var ab = new ArrayBuffer( rawjpegdata );
pea.postMessage( ab, '*' ); ?

**Comment by photopea** [comment]
Please, follow the standard: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer  . Your use of the constructor is not valid.

I usually create a Uint8Array of bytes, and then get its buffer (array.buffer).

**Comment by photopea** [comment]
I am going to consider this fixed :)
