### ISSUE TITLE
My photopea crash very often

### ISSUE THREAD

**Issue by Eittu** [photopea/photopea#5490]
My photopea often crashes while I work on my graphics services for my clients and I can't recover all of my work and I find its very frustrating !

**Comment by Eittu** [comment]
> Tell us more about a device that you use it on.

I use a Windows 11 PC on the Install app on my PC and its 2 months that I use it

**Comment by photopea** [comment]
Can you make it crash on purpose? Could you record a video of making Photopea crash?

**Comment by Eittu** [comment]
> Can you make it crash on purpose? Could you record a video of making Photopea crash?

yes

**Comment by Eittu** [comment]
> Can you make it crash on purpose? Could you record a video of making Photopea crash?

**Comment by photopea** [comment]
Please, tell us how can we make Photopea crash.

**Comment by Eittu** [comment]
> > Can you make it crash on purpose? Could you record a video of making Photopea crash?

**Comment by AnonymousIrrelevant** [comment]
For me, I am using the Chrome app on a Chromebook and my Photopea has also crashed often. What I think is happening is that when the ads on the sidebar update, the program crashes because the crashes only happen for me when the ads update on the side.

**Comment by photopea** [comment]
Sorry, it seems like you are adding empty coments, so I will close it.
