### ISSUE TITLE
Crop Tool Abilities Lost

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5492]
I've seen one post on Reddit and two posts on Discord today asking about Crop Tool options that were lost when you added the different fixed ratios to the Crop drop-list. Previously, there were buttons in the top toolbar for "All Layers", "Current Layer", "Trim" and "Selection". Users would like to have them back if possible. You could probably just go back to how the top toolbar used to look, while keeping the new additions to the drop-list.

![image-1](https://user-images.githubusercontent.com/73725653/228954891-655e6abe-a65f-4af8-a8b0-339a2f67f403.png)

**Comment by photopea** [comment]
I just thought that it takes too much space, and nobody is probably using it.

I have added a special dropdown button for this: "..."

**Comment by camoody1** [comment]
Seems like a nice compromise. I'll let the people on Discord know. Ty
