### ISSUE TITLE
Estilo de camada

### ISSUE THREAD

**Issue by menezesmatias** [photopea/photopea#5494]
instalei uns estilos de camadas e ficou muito pesado e travando agora apago os mesmos e eles voltam de novo e não consigo usar o programa

**Comment by photopea** [comment]
Try to clear your browser cache. Also, share your styles with us, so that we see what is happening.

**Comment by menezesmatias** [comment]
como  compartilhe seus estilos com vocês?

**Comment by menezesmatias** [comment]
consegui obrigado, muito obrigado mesmo

**Comment by photopea** [comment]
ok great
