### ISSUE TITLE
SVG Gradient precision

### ISSUE THREAD

**Issue by burningreggae** [photopea/photopea#5498]
Hi!.
could you please allow the SVG export to use more digits in the offset in the gradient-steps?. 
Loading/viewing from psd is correct but export to svg (already in the preview) round to only one 1 digit precision which is not enough. ( the 0 and the 1 should be smth like 0.01 0.05 0.07)

Thank you!
`<linearGradient id="g4" x1="1583.5" y1="3161" x2="1583.5" y2="2769" gradientUnits="userSpaceOnUse">
			<stop offset="0" stop-color="#1b1b1b"/>
			<stop offset="0" stop-color="#121212"/>
			<stop offset="0" stop-color="#3e3e3e"/>
			<stop offset=".2" stop-color="#444444"/>
			<stop offset=".4" stop-color="#4f4f4f"/>
			<stop offset=".9" stop-color="#565454"/>
			<stop offset="1" stop-color="#636162"/>
			<stop offset="1" stop-color="#9ea4a8"/>
			<stop offset="1" stop-color="#4f4d4c"/>
			<stop offset="1" stop-color="#555150"/>
			<stop offset="1" stop-color="#0f0f11"/>
		</linearGradient>`

**Comment by photopea** [comment]
Oh, I am very sorry. It should be fixed now.

It should use 3 digits by default, and 2 digits when you enable "minify" now.

**Comment by burningreggae** [comment]
That was quick!. Thank you. it's working
