### ISSUE TITLE
o photopea está travando demais 

### ISSUE THREAD

**Issue by diekepessoa** [photopea/photopea#5499]
o photopea está travando demais, não estou conseguindo abrir mais nenhum projeto nele! já reiniciei o notebook mais não resolveu o problema!

**Comment by photopea** [comment]
How large is your project in MB? Did it crash when opening any project or just one specific project?

**Comment by diekepessoa** [comment]
qualquer projeto está travando!

**Comment by photopea** [comment]
Could you record a video of Photopea crashing?

**Comment by diekepessoa** [comment]
como adiciona vídeo aqui?

**Comment by photopea** [comment]
You can upload your video to Youtube and show us a link.
