### ISSUE TITLE
Delete mask

### ISSUE THREAD

**Issue by tomasnosek** [photopea/photopea#55]
Currently you are not able delete mask you created on some layer. You have to rebrush by white to change it or disable it, but you can't delete it. Try to add "delete mask" feature into context menu after R-click on layer.

**Comment by photopea** [comment]
There is an option in the menu: Layer - Raster mask/Vector Mask - Delete ... but right-button on a mask is a nice feature indeed! :)

**Comment by tomasnosek** [comment]
wooow, keep it simple man :)

**Comment by photopea** [comment]
The special context menu for masks was added :)
