### ISSUE TITLE
Update layer style color when choosing in color picker before hitting ok

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#550]
Every elements with a color picker like stroke, satin, color overlay, in/out shadow/glow would all be better and quicker if the color also updates with color picker just like text and shape

**Comment by photopea** [comment]
But if we did it this way, the experience would be much worse (because the image has to be redrawn while you choose the color). It would be very choppy.  BTW. Adobe Photoshop does not do it this way.

**Comment by hgs54371** [comment]
No need to be "realtime" while dragging, only update when the dragging stops and before hitting ok is enough.
Why would this be more difficult then the ones with text and shape?

**Comment by photopea** [comment]
it is not more difficult, but it will not be smooth. I think we have to do it while dragging. 

One usually tries 10 - 20 colors before confirming it. So I think dragging is easier than clicking 20 times.

**Comment by hgs54371** [comment]
I actually rarely do dragging, so for me, update with clicking is better enough than having to click ok every time to see the result
