### ISSUE TITLE
GIF Editing and Export

### ISSUE THREAD

**Issue by Hekspoilr** [photopea/photopea#5500]
After importing a GIF and dublicating it into the project layer it is always placed in the upper left corner of the project layer . 
Exporting the project as a GIF shows the edited GIF also always in the upper left corner , no matter where it has been placed during editing . Therefore i cannot properly add a GIF into an Image !

**Comment by photopea** [comment]
Hi, you probably moved just one layer to a new location, while other layers stayed at the top left corner. Maybe disable the Auto-select? Or use our tutorial: https://www.photopea.com/tuts/add-gif-into-a-still-image/

**Comment by Hekspoilr** [comment]
Thank You ! disabeling Auto - Select fixed the problem !
