### ISSUE TITLE
Can't save as a JPG. file

### ISSUE THREAD

**Issue by Zweixoxo** [photopea/photopea#5501]
I can save other file formats, except for JPG files.

**Comment by camoody1** [comment]
Please record a short video of you attempting to save as a jpg and post it here or on YouTube so that we can see exactly what happens.

**Comment by Zweixoxo** [comment]
97Buckeye ***@***.***> 於 2023年4月4日 下午3:35 寫道：﻿
Please record a short video of you attempting to save as a jpg and post it here or on YouTube so that we can see exactly what happens.

**Comment by photopea** [comment]
So what happens when you try to save a JPG?

Please, reply at www.github.com in your web browser, do not send emails to random email addresses.

**Comment by photopea** [comment]
Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by Zweixoxo** [comment]
I am able to save other types of files, but there is no response when attempting to save JPG files.
After trying the link you provided, I am still unable to save it.

**Comment by photopea** [comment]
Did you try to run Photopea in the Incognito mode, with all browser extensions disabled?

Also, what web browser and what OS do you use?

**Comment by zairars** [comment]
I am having a similar issue (and quite possibly maybe the same issue) with a Mac Book Pro that is updated to the most recent OS. Whenever I try to save as a JPG the screen freezes up on me.

**Comment by photopea** [comment]
Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
Did it help?
