### ISSUE TITLE
(Mac, Safari) Keeps on pasting any copied image every time I click a keyboard button or try to delete it.

### ISSUE THREAD

**Issue by Nitr0h** [photopea/photopea#5502]
<img width="285" alt="image" src="https://user-images.githubusercontent.com/91281667/229912181-51401698-8699-453b-90b2-5e0debe2bb0a.png">

**Comment by photopea** [comment]
What should I do to see it happen myself? When you close Photopea and open it again, what do you do to make this happen?

**Comment by Nitr0h** [comment]
It happens after I copy a photo from a website like Google images, paste it into photopea, hen just try to change layers or delete it. It starts duplicating itself.

Sent via the Samsung Galaxy A14 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by photopea** [comment]
Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details :(
