### ISSUE TITLE
Lasso select tool makes zig zags when using at 45 degree

### ISSUE THREAD

**Issue by degenonebug** [photopea/photopea#5504]
Good afternoon,

When Im using lasso select tool at degrees in between 90 and 180 trying to make a straight line it creates these zig zag shaped bumps. I can make only vertical and horizontal straight lines, but anything in between has this problem. Im painting in photopea, so I cant use other versions of lasso. Furthermore, once Im done using lasso select tool the selected area shrinks and makes my selections uneven with bumps. I checked this with both my art pencil and mouse on pc and on a tablet. Please fix this problem if you can and let me know.

Sincerely,
one of your supporters on premium

**Comment by photopea** [comment]
Hi, could you show us a screenshot of "bumps"? I still dont know what you mean. Maybe they are pixels?

**Comment by degenonebug** [comment]
![Screenshot_20230405_180544_Chrome](https://user-images.githubusercontent.com/65723400/230076228-bb3391aa-a749-47ac-9f14-3de2cd4f3f2d.jpg)

**Comment by degenonebug** [comment]
This was on galaxy tab s8 in chrome

**Comment by degenonebug** [comment]
https://user-images.githubusercontent.com/65723400/230140322-2819c467-d863-4c6d-b5aa-fedfc7d87b8b.mp4

Here is video

**Comment by camoody1** [comment]
@degenonebug Are you using a stylus in this video?

**Comment by photopea** [comment]
Hi, it should be fixed now.
