### ISSUE TITLE
Question: Are the images stored on the server

### ISSUE THREAD

**Issue by Wh1teT1ger55** [photopea/photopea#5505]
Hey,

I want to know if my uploaded or created files are stored on the server? I ask for my privacy.
I wouldn't ask if their would be an offline version of Photopea

Bye

**Comment by photopea** [comment]
Hi, how exactly do you upload? Or what does it mean?

If you open your files in Photopea, you could notice, that you can open a 500 MB PSD file in 1 second. That would mean, that your internet provider offers you a connection with a 4 gigabit upload speed.

So there is no upload. You can learn more here: https://www.photopea.com/learn/
