### ISSUE TITLE
Error while running script

### ISSUE THREAD

**Issue by miroljub1995** [photopea/photopea#5506]
We have seen error logs while running photopea in `iframe`:
JavaScript error: https://www.photopea.com/code/pp/pp.js, line 415: TypeError: i$.q2.w$(...)[226] is undefined

The script is something like this:
```js
app.activeDocument = app.documents[0];
res = {
    width: app.activeDocument.width,
    height: app.activeDocument.height,
    resolution: app.activeDocument.resolution,
};
app.echoToOE(JSON.stringify(res));
app.activeDocument.saveToOE('jpg');
```

Any idea what could be the reason?

**Comment by miroljub1995** [comment]
Looks like some PSD is not working in Firefox, but works in Chrome.

Firefox version: [111.0.1](https://www.mozilla.org/en-US/firefox/111.0.1/releasenotes/?utm_source=firefox-browser&utm_medium=firefox-desktop&utm_campaign=about-dialog)
OS: Ubuntu 22.04
[1666e6f9-75eb-4baf-a087-1700b204607c.zip](https://github.com/photopea/photopea/files/11184946/1666e6f9-75eb-4baf-a087-1700b204607c.zip)

Minimal script with an issue:
```js
app.activeDocument = app.documents[0];
app.activeDocument.saveToOE('jpg');
```
I can confirm that this script works for some other PSD.

**Comment by photopea** [comment]
I am very sorry for this bug, it should be fixed now.
