### ISSUE TITLE
Save as PSD

### ISSUE THREAD

**Issue by degenonebug** [photopea/photopea#5507]
Good afternoon,

When I save my file with Save as PSD it saves it as a separate file on my tablet samsung galaxy tab s8. Could you make it so new save overwrites old file? I dont always have internet ready to save on cloud. Sometimes when i save on cloud through dropbox,peadrive it says saving and gets stuck, so it is safer for me to save on tablet directly. 
![403ECAE8-456B-4CCC-9528-F28DC5AFB1DE](https://user-images.githubusercontent.com/65723400/230310539-c79460f4-40e0-486e-917e-5ada5baa0e4b.jpeg)

Sincerely,
premium supporter

**Comment by photopea** [comment]
Hi, Photopea.com is a website, and we can do only as much as your web browser allows us to do.

There is a new web standard, which allows websites to modify files in your device. Sadly, it seems like it is not supported by any mobile browser yet :( https://caniuse.com/?search=showSaveFilePicker   But it works on desktops (in Chrome, Edge and Opera for now).
