### ISSUE TITLE
Feature Request: Cylinder Warp

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5508]
I would like Photopea to have the same Cylinder Warp option as seen in Photoshop. The existing warp options do not work correctly for a cylinder shape (can, barrel, bottle, etc).

Here is a link to a video showing exactly what I am talking about:
https://youtube.com/shorts/CKinnYlKrqQ?feature=share

**Comment by photopea** [comment]
I have implemented it!

This warp needs to be edited "on the canvas", so we added control points to all other types of warp, they can all be edited on the canvas now.
![image (1)](https://user-images.githubusercontent.com/15955558/233852202-57f32cd2-a653-47cb-8150-c44bb7a9462f.gif)

**Comment by camoody1** [comment]
Great stuff. Thank you!

I have found what might be a big, though, in how Warp works with layers that have a mask on them. Please watch this video I recorded.

https://user-images.githubusercontent.com/73725653/233863315-b976293f-1db2-4bd8-a99b-513861ad2159.mp4

As you can see, without a mask, the Warp function works perfectly. No worries. When I undo the Warp, though, you can see in the Layers window that the thumbnail doesn't update to remove the Warp look. It still shows the layer as warped even though it has been returned to normal. That's not a big deal, though, just something that I noticed. The bigger issue is that after I apply a Raster Mask to remove the background of the layer with my logo, the Warp function no longer works. When I click it, nothing happens. The other transform functions still work, but not the Warp.

Is this something you can fix?

**Comment by photopea** [comment]
I have fixed it!

The correct behaviour is, that the warp can be applied only to one object. It can not be applied to two layers, or a layer and a mask.

You need to unlink a mask and apply the warp separately on a layer or on a mask.

**Comment by camoody1** [comment]
Okay. Makes sense. I can just apply the mask after having performed the Warp. Thank you!
