### ISSUE TITLE
Feature Request: Add Path Blur and Spiral Blur Filters

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5509]
Photoshop has two new-ish blur filters that I believe Photopea would benefit from having: Path Blur and Spiral Blur. These two blurs fill do a much better job handling perspective type blurs than the current options.

Here are two videos showing the tools in action. The first video is quite short while the second is much more in depth (only the first half of the second video relates to these blurs):
https://youtube.com/shorts/-aOWE2fi4sk?feature=share
https://youtu.be/cL1BvOtd5zY

**Comment by photopea** [comment]
Hi, I have added the Blur Gallery filter: https://www.photopea.com/learn/blur-gallery

**Comment by camoody1** [comment]
Outstanding! Happy New Year, Ivan!
