### ISSUE TITLE
Tag often used fonts as favorite and store them in a checkbox category called favorites

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#551]
Put a click-able icon like a star in front of every fonts in the font list for tag them as favorites.
Add a new checkbox category above Sans Serif called favorites for storing these tagged fonts.

This would be quicker for testing out from a set of fonts for a project instead of entering each of their name every time

**Comment by hgs54371** [comment]
Because an user customize-able filter is always better, this is a very basic feature, photoshop has it, I've been using it the first time I see it.
Isn't having a personalized font collection a common thing especially among designers?

**Comment by photopea** [comment]
It was implemented. You can mark favorite fonts with a Star. You can also filter out only Favorite fonts. The list of favorite fonts is preserved even after closing Photopea.

**Comment by hgs54371** [comment]
Works really well, now it's much quicker to switch between a small collection of fonts for trying around

**Comment by photopea** [comment]
Thanks. I also made the font list work faster (e.g. as you repatedly open and close it).
