### ISSUE TITLE
Filter Torn edges is not working

### ISSUE THREAD

**Issue by Arne-Peeters** [photopea/photopea#5514]
The filter "Torn edges" in the filter gallery is not working on jpeg files. If you apply it, the images turns blank. Could someone please help with this? Thanks

**Comment by photopea** [comment]
It seems to work fine in my case. Could you share a JPEG file on which you apply it?

**Comment by Arne-Peeters** [comment]
Huh now it works again! Thank you for your reaction anyway.

**Comment by photopea** [comment]
ok perfect.
