### ISSUE TITLE
Loading banner stuck

### ISSUE THREAD

**Issue by MCwarden25** [photopea/photopea#5517]
The loading banner stays even though its already loaded, blocking controlls.

**Comment by camoody1** [comment]
Mine does this occasionally, too. Same with the occasional Save banner. Nothing you can do at that point other than restart Photopea.

**Comment by photopea** [comment]
Look into Edit - Local Storage, or Window - Plugins - Installed. Maybe you have some items there, which are fake and lead to an error.

**Comment by photopea** [comment]
@camoody1 would you like to become an editor of our Templates and Plugins? When you go to Window - Plugins, and look at the top, there are Plugins, Brushes, Gradients ... uploaded by our users. People often upload nonense, and others install it. You would be able to delete those.

**Comment by photopea** [comment]
I have to close it because of lack of details.
