### ISSUE TITLE
Feature Request: Bigger padding on buttons mode

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5519]
Thi si a feature request.

I have bought a digital pen to draw on Photopea. I use a tablet.
And i have an issue: The buttons on the tools, the right side navigation and the tools settings are pretty small, so it is not so easy to click them quickly with the pen.

![image](https://user-images.githubusercontent.com/11801254/230981396-253a2de4-909e-4138-a354-ac8ba526bb34.png)
![image](https://user-images.githubusercontent.com/11801254/230981427-2ed1581f-2f42-4f90-af6c-64275441abf8.png)
![image](https://user-images.githubusercontent.com/11801254/230981479-7204e551-3bfc-4820-8ca5-750826dbac24.png)

So i was wondering if maybe there could be and option in the menu or somewhere where i can choose another version of size. Just one big version will be perfect. Something 50% more padding to the buttons will work.

**Comment by photopea** [comment]
That would be really hard to make. Could you increase the website zoom in your web browser? It should work nicely for Photopea.

**Comment by photopea** [comment]
I think increasing the webpage zoom should do exactly what you need. Photopea adapts nicely to a webpage zoom (but you might need to reload it).
