### ISSUE TITLE
easy to accidentally drag toolbox icons (instead of clicking), opening them in Photopea

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#552]
when selecting tool to use from the toolbox, it is easy to accidentally drag it instead, which results in Photopea opening the icon image as another file to edit

at least this is my experience in Chrome on Ubuntu

if it's not just the quirks of my system, I believe it's worth it to just disable drag'n'drop for these images

**Comment by photopea** [comment]
It should be fixed now. Thanks!
