### ISSUE TITLE
Lasso tool feather

### ISSUE THREAD

**Issue by degenonebug** [photopea/photopea#5523]
Good afternoon, 

Whenever I open new doc or the one I closed, I pick lasso tool and it has Feather setting in 0 px. I want to save my px amount for future use as I don't want to manually change it everyday. Can you give lasso tool a brush like property, so its settings can be saved please?

Screenshot shows where feather setting is
![2A5EE1B9-FBDB-44D9-9DA0-BB093AA63974](https://user-images.githubusercontent.com/65723400/231425168-339c6c34-45de-4abf-a0de-02dd6d30b98a.jpeg)

Sincerely,
Your premium supporter

**Comment by degenonebug** [comment]
Hello, do you plan to make this useful feature a reality or did you reject it? I just want to know @photopea

**Comment by photopea** [comment]
I have implemented it! 

Now, Photopea will remember the binary operation and the Feather value of every selection tool :)
