### ISSUE TITLE
I cant open my psd

### ISSUE THREAD

**Issue by MrRabbit238** [photopea/photopea#5526]
photopea wont let me open a psd that i have on my pc ( i know how to do it, but photopea wont let me )

**Comment by JorayLing** [comment]
Same here.

**Comment by salvatoresalvo** [comment]
Same problem

**Comment by JudahIreson82** [comment]
Also having the same problem.

**Comment by Megapikseli** [comment]
same

**Comment by Anastasia-Bzv** [comment]
Same here

**Comment by sudtichai** [comment]
use on microsoft edge

**Comment by camoody1** [comment]
Clear your cache and try it again. It's now working for me after clearing cache.

**Comment by photopea** [comment]
Sorry guys, it is fixed now, just clear your cache or wait 30 minutes.
