### ISSUE TITLE
Photopea suddenly doesn't load anything

### ISSUE THREAD

**Issue by DarkScener777** [photopea/photopea#5527]
Hours after the last Windows update I tried to reopen files, PDSs and JPEGS I was working on and they simply just DON'T open. 
NOTHING happens. I have the full paid version.

**Comment by HeikkiPauwels** [comment]
Same with the free version.

**Comment by HeikkiPauwels** [comment]
Why does it work there???
Makes no scense.

**Comment by nocdebalo** [comment]
i don't know, but at least it's still working somehow

**Comment by camoody1** [comment]
Clear your cache and try it again. It's now working for me after clearing cache.

**Comment by photopea** [comment]
Sorry guys, it is fixed now, just clear your cache or wait 30 minutes.

**Comment by HeikkiPauwels** [comment]
Thx
