### ISSUE TITLE
Can't Open Any of My Projects

### ISSUE THREAD

**Issue by DarkScener777** [photopea/photopea#5528]
I can't open any of my PSDs or JPEGS or anything in Photopea. What the hell, man?!

**Comment by Sudipta22l** [comment]
Same issue I also facing

**Comment by camoody1** [comment]
Clear your cache and try it again. It's now working for me after clearing cache.

**Comment by salvatoresalvo** [comment]
Only Microsoft Edge works. On Google Chrome and the installed app they don't work

**Comment by photopea** [comment]
Sorry guys, it is fixed now, just clear your cache or wait 30 minutes.
