### ISSUE TITLE
Error with font "firsttest" or "FORQUE"

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#553]
In font list there is font called "firsttest"
1. I selected text layer and if I click on it instead changing font it shows "Font FORQUE loaded." and nothing happens (I see in font list it appears new font "FORQUE" now that was not there before?)
2. Then i change font to some other font.
3. Now if I select font "firsttest" again it opens edit mode of text or something (confirm and cancel buttons appear in toolbar)
4. I click on cancel ("X") button in toolbar and it crashes Photopea and almost nothing works.

It shows this error in console:

Alert: Font FORQUE loaded.
Alert: Font Caudex Bold loaded.
Uncaught TypeError: Cannot read property 'add' of null
    at z.UY.UD (pp.js:2698)
    at z.UY.ie (pp.js:2689)
    at VQ.KP (pp.js:6432)
    at VQ.qT (pp.js:6417)
    at VQ.Pm.G (pp.js:6)
    at VQ.EF.G (pp.js:4524)
    at z.UY.UV (pp.js:2722)
    at z.UY.Uw (pp.js:2683)
    at z.UY.iq (pp.js:2649)
    at VQ.update (pp.js:6463)

**Comment by photopea** [comment]
Hi, I think it was fixed and it should work well now. Thanks!
