### ISSUE TITLE
ZOOM INVOLUNTARIO

### ISSUE THREAD

**Issue by Orly-Avellaneda** [photopea/photopea#5531]
Cuando estoy pintando en mi tableta y hago trazos, comienza a hacer zoom como si en lugar de pincel o lápiz, estuviera utilizando la herramienta zoom, debo haber hecho algún cambio en alguna cosa porque no recuerdo que lo hiciera antes.  Podrán ayudarme por favor. Gracias Orlando

**Comment by photopea** [comment]
Hi, you should touch the screen only with one point (e.g. a stylus), without adding your fingers. Two points will be used for zooming.

Could you record a video of what you do?

**Comment by Orly-Avellaneda** [comment]
Thanks for your response, my english is very poor, I prefer to explain the
problem in spanish l.
Intentaré, en correo aparte, adjuntar video con el problema que se da al
pasar el lápiz sobre la tableta utilizando pincel o lápiz, NO TOCO con mis
dedos, adjunto foto.
Desde ya, gracias por la ayuda que puedan darme
Saludos desde Argentina
*Orlando*

*No me conforma aprender para alcanzar un lúcida resignación*

**Comment by Orly-Avellaneda** [comment]
Aquí va el enlace, espero puedan verlo, gracias

https://drive.google.com/file/d/14oWBCQc6D-uaeRQ2inzrY6I2v74jq4Rb/view?usp=sharing

*Orlando*

*No me conforma aprender para alcanzar un lúcida resignación*

**Comment by photopea** [comment]
Sorry, I speak only English :(

**Comment by camoody1** [comment]
This looks like a hardware problem. You can see that painting with the paint brush works fine for several strokes. And then it randomly zooms in. Since no one else is reporting a similar issue, I can only assume there is some sort of screen problem with the tablet you are using.

**Comment by Orly-Avellaneda** [comment]
Ok, I'll check it out.
*Orlando*

*No me conforma aprender para alcanzar un lúcida resignación*
