### ISSUE TITLE
zooming and rotating on tablet

### ISSUE THREAD

**Issue by degenonebug** [photopea/photopea#5532]
Good afternoon,

Im using tablet with stylus for photopea Galaxy tab s8. I can easily zoom and move around with my two fingers on a canvas even while using brushes. However, I would like to be able to also rotate the canvas like I can do inside Clip Studio Paint with my two fingers while also being able to zoom and move around like I do now. I know that photoshop does not have this feature, but it would be a great feature to have in photopea. 

Sincerely,
your premium supporter

**Comment by TheRadicalDreamer** [comment]
i do have the same issue. I have a pen to draw, but because i am not able to rotate the canvas with a finger gesture, i have to rotate the tablet and then i cannot reach the other tools :/


Maybe there should be a drawing mode of some sort.

Or maybe when you have "Menu Bar and Canvas" (tab) enabled, you can do 2 finger zoom and rotate.

And in that matter, there is no digital button for that mode, and it is really handy when drawing. If i don't use it, most off the time i hit the Ads on the right side with my palm

**Comment by camoody1** [comment]
I could see where this would be a really beneficial option for those of us using Photopea on a touch device or with a pen.

**Comment by photopea** [comment]
I have implemented it! Actually, it took me only 10 minutes to implement and test on my tablet.

There is also a little "snapping" to zero degrees (so if someone just wants to zoom, they dont end up rotating the image by 1.76 degrees).

**Comment by camoody1** [comment]
> I have implemented it! Actually, it took me only 10 minutes to implement and test on my tablet.
> 
> There is also a little "snapping" to zero degrees (so if someone just wants to zoom, they dont end up rotating the image by 1.76 degrees).

How do I enable this functionality? I can't seem to make it rotate on my phone.

**Comment by photopea** [comment]
Just touch the screen with two fingers and spin them around. It works for me on an iOS and an Android device.

**Comment by camoody1** [comment]
I'm on my Samsung Galaxy S22 Ultra and I don't get any rotation when using my fingers. I can zoom in and out perfectly, but no rotation. I have reloaded Photopea several times. 🤔

**Comment by photopea** [comment]
Try Photopea in the Incognito window.

**Comment by camoody1** [comment]
I tried it in Incognito Mode and it works.
And I just tried it, again, in my regular mode and it works. No idea why it wasn't working for so long. Working great, now, though. 

And I'm on my phone, so I don't even think I can load extensions or plugins on my browser. 🤷🏽‍♂️

**Comment by photopea** [comment]
You need to do a hard-reload (Shift+F5 in Chrome).

When your device loads Photopea, it is stored in your computer for one hour, and your browser will not load it again in the next hour (it will show you the version saved on your computer), even if you reload it 100 times.

**Comment by TheRadicalDreamer** [comment]
i works perfectly for me!. And i am in a chromebook.

I LOVE IT!
