### ISSUE TITLE
Color contour for shapes 

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5535]
I know that when you select a shape it gets a blue contour, but what happens if i am working on a blue shape?

I am not able to see what i am selecting.

Maybe the contour should be determine by the color on the color picker, just like spot healing.

Or it should always be a lighter tone of the shape, or an inverse color of what is in on the screen.

This is what i am working on, and it is pretty difficult to see what i am selecting:
![image](https://user-images.githubusercontent.com/11801254/232046612-d4ade1b2-754d-4237-bee3-0b133b7c486f.png)

**Comment by photopea** [comment]
I am a bit afraid to have so many options in Preferences. Could you maybe change the color of your layer (temporarily)?
