### ISSUE TITLE
which blend modes does PDF accept?

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5537]
I am really concerned about this. :/

Does someone knows?

**Comment by photopea** [comment]
You can check the PDF specification, page 324 (printed at the bottom): https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf

Or here: https://printtechnologies.org/wp-content/uploads/2020/03/pdf-reference-1.6-addendum-blend-modes.pdf

**Comment by TheRadicalDreamer** [comment]
THANKSS!
