### ISSUE TITLE
There are display issues when importing with auto-layout feature

### ISSUE THREAD

**Issue by Thore98** [photopea/photopea#5538]
When importing Photopea into Figma, there may be display issues in Photopea if Figma's auto-layout feature is used

**Comment by photopea** [comment]
Hi, what is "importing Photopea into Figma"?

**Comment by Thore98** [comment]
Save a copy of the file in .fig format in Figma, and import it into Photopea

**Comment by photopea** [comment]
so you have a FIG file, which looks differently when opened in Photopea vs. when opened in Figma? Could you share that FIG file with us?

**Comment by Thore98** [comment]
Sorry, I found out it was caused by a local font mismatch and it has been resolved now

**Comment by photopea** [comment]
ok.
