### ISSUE TITLE
Invert mask of smart filter with cmd-i

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#554]
Right now it responds as adding invert color as another filter under same mask, but no way to invert the mask itself

**Comment by photopea** [comment]
It was fixed. Thanks!

**Comment by hgs54371** [comment]
A layer is added with unsharp mask, then invert the smart filter mask in order to "paint in" localized sharpen with brush, but only the mask icon is inverted, the effect stays still

**Comment by photopea** [comment]
It was fixed now, too. (inverting "empty" mask)

**Comment by hgs54371** [comment]
It works now, but then drag the "smart filters" to trash can leads to all frozen, I've created another post for this
