### ISSUE TITLE
Applying CSS style on Photopea Frame

### ISSUE THREAD

**Issue by cqtyve** [photopea/photopea#5540]
is there a possibility to add style to Photpea ?

**Comment by photopea** [comment]
Hi, we would like to have the same style for everyone. If you have a good idea bout the look, tell us and we will change it for everyone. 

You can probably make a browser extension which modifies the style of a website.

**Comment by camoody1** [comment]
Would you add images of Star Wars ships and weapons throughout the UI? Please? 🫶🏼

**Comment by photopea** [comment]
maybe someone could make an extension for it :D

**Comment by Far4153** [comment]
how to change the css and save these changes in photopia's css panel ?

**Comment by photopea** [comment]
The CSS window of Photopea works only "one way". It tries to describe the style of a selected layer with CSS, but it does not work perfectly. It does not work in the other way (from the CSS window to the layer style).
