### ISSUE TITLE
Feature Request: Copy layers to clipboard shortcut

### ISSUE THREAD

**Issue by AviceProjects** [photopea/photopea#5544]
Currently, the only way to copy all layers to the clipboard is to flatten the layers, select all pixels, and then press ctrl+c. It would be nice to have a shortcut for this.

**Comment by photopea** [comment]
When you create a selection, you can press Ctrl+C (or Edit - Copy) to copy a selected area as pixels to a clipboard.

You can also press Shift+Ctrl+C (or Edit - Copy Merged) to copy a selected area **from all layers** as pixels to a clipboard.
