### ISSUE TITLE
Bug with SF Pro fonts

### ISSUE THREAD

**Issue by PoweredByAndrox** [photopea/photopea#5545]
Attach the psd file that has bug in photopea

1. Photopea can't load the font if it was changed some settings through Photoshop (width, opt size and etc.)
2. In photoshop has option "TT" in the text settings but it won't work in Photopea

I reproduce it in this file 
[test_bug.zip](https://github.com/photopea/photopea/files/11271761/test_bug.zip)

Just google the SF Pro font from apple developer site

**Comment by photopea** [comment]
Could you share a font (TTF or OTF file) which you think was used in your PSD? I can not find it anywhere. 

This https://developer.apple.com/fonts/ contains only a DMG file, which I can not use on Windows.

**Comment by PoweredByAndrox** [comment]
Open it with 7z and find the fonts (in this case you need just SF-Pro.ttf)

**Comment by photopea** [comment]
It would really help me if you shared it here, as I dont know which one should it be.

**Comment by PoweredByAndrox** [comment]
I hope you fixed this bug...
[SF-Pro.zip](https://github.com/photopea/photopea/files/11272415/SF-Pro.zip)

**Comment by photopea** [comment]
Seems like it is a variable font, these fonts are not supported by Photopea yet :( https://fonts.google.com/knowledge/glossary/variable_fonts  I can implement it, but it might take me a week or two.

**Comment by PoweredByAndrox** [comment]
Ok, thanks!

**Comment by PoweredByAndrox** [comment]
Also, native (from Photopea) the font Roboto doesn't contain the "₸" - tenge currency symbol...

**Comment by photopea** [comment]
Are you sure that the Roboto font has this symbol?

**Comment by PoweredByAndrox** [comment]
Yes, i checked it.

**Comment by photopea** [comment]
Could you send me some proof, e.g. the TTF file of the Roboto font that you are using?

**Comment by camoody1** [comment]
This screenshot is from Google's Roboto font. I think that "t" glyph is what he's talking about.

![SmartSelect_20230429_160055_Edge](https://user-images.githubusercontent.com/73725653/235322074-69d33eb3-a05d-45db-9d2a-8a450bcb4380.jpg)

**Comment by camoody1** [comment]
@PoweredByAndrox Roboto Flex has the font glyph you're looking for. I just found it there.

**Comment by PoweredByAndrox** [comment]
I made a psd from Photoshop where used my downloaded Roboto from Android when i open it in Photopea and try editing it show it 
![ScreenShot_20230430171119](https://user-images.githubusercontent.com/38520826/235340775-445e60c6-d94c-41e1-8f61-7d669ff4a83a.png)

BUT when i load my Font into Photopea it works as need
![image](https://user-images.githubusercontent.com/38520826/235340807-62a4b062-ca1b-4090-b3bf-6b85f3e695c5.png)

[roboto-bug.zip](https://github.com/photopea/photopea/files/11360772/roboto-bug.zip)

**Comment by photopea** [comment]
That is so weird, I went here: https://fonts.google.com/specimen/Roboto and typed "100 ₸", but Roboto at Google Fonts can not display the "₸" symbol either. Their TTF file contains 1249 letters, while your TTF file contains 2547 letters.

Where did you get your TTF file? What is a reliable source of free fonts?

**Comment by PoweredByAndrox** [comment]
I just downloaded that font from other sites (just googled like "Roboto Android Font")
