### ISSUE TITLE
Layer Duplicate

### ISSUE THREAD

**Issue by PoweredByAndrox** [photopea/photopea#5546]
Can I duplicate the layer into another folder as in Photoshop?

**Comment by PoweredByAndrox** [comment]
Tried this https://community.adobe.com/t5/photoshop-ecosystem-discussions/move-the-current-layer-to-active-layer-group/m-p/8526780
But I need to place at the end and I tried https://theiviaxx.github.io/photoshop-docs/Photoshop/ElementPlacement.html (ElementPlacement.PLACEATEND) but no matter because all new layers in move to the first place (on the top of folder)

```js
var DuplicatedIconLayer = app.activeDocument.layers[IndexIconLayers].layers[data.rows[IndexRow].icon_index + LastDuplicatedIndex].duplicate();
DuplicatedIconLayer.move(app.activeDocument.layers[IndexIconLayers], ElementPlacement.PLACEATEND);
```

**Comment by photopea** [comment]
I have fixed a couple of things and the script from your link should work well now

    var doc = app.documents.add()          // create a Doc
    var lay = doc.activeLayer.duplicate()  // duplicate the background layer
    var set = doc.layerSets.add();         // add a LayerSet
    lay.move(set, ElementPlacement.INSIDE) // move the duplicate layer inside the LayerSet

If you have a script, which runs well in Photoshop, but does not in Photopea, let us know! :)
