### ISSUE TITLE
ICO format corrupted or missing metadata.

### ISSUE THREAD

**Issue by satolas** [photopea/photopea#5548]
**How I figured out the issue :** Got an uknown error building an Electronjs app using an icon.ico file created with Photopea.

**To recreate issue :** Just create a new file with photopea or import a png export it as ico.
And compare it with the same ico created with another software or any app that converted a .png to .ico.

**Problem :** Files are different in sizes and miss metadata like Dimension, Width, Height, Bit depth... (file.ico : right-click/properties/details).

**Expected behavior :** ico file should content metadata and comply with ico standards to be able to be used in any context and project.

![cNm7R2dXsj](https://user-images.githubusercontent.com/29286385/233381071-74bb71ae-b55d-49f5-8489-06b5110aba3d.png)
[icons.zip](https://github.com/photopea/photopea/files/11286706/icons.zip)

**Comment by photopea** [comment]
It happened only with non-transparent images. If all pixels of the image were opaque, the generated ICO file was damaged.

It should be fixed now :) Note, that in this case, an ICO from Photopea is 100x smaller than an ICO from your other tools.
