### ISSUE TITLE
When I try to open PSD files, it tells me unkown JSON filed opened. It does this for every single PSD I have.

### ISSUE THREAD

**Issue by MotziRBX** [photopea/photopea#5549]
![Screenshot 2023-04-20 125215](https://user-images.githubusercontent.com/131391069/233435112-337e3ec0-a62b-4eda-8011-6fcd469ebac8.png)

**Comment by MotziRBX** [comment]
And the ones that do open up, it doesnt even show anything. Like its blank...
![Screenshot 2023-04-20 130741](https://user-images.githubusercontent.com/131391069/233438451-bff68de2-548c-4283-bbfa-82dca1a564d8.png)

**Comment by MotziRBX** [comment]
> Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

I've basically tried all that. My browser is up to date, my extensions are disabled, In incognito mode, it will open the file, but it still shows up blank. I don't know what to do anymore. And my enhanced security has never been turned on, so it's not that.

**Comment by photopea** [comment]
Could you share your PSDs with us? You can put it into a ZIP and share it here.

**Comment by MotziRBX** [comment]
> Could you share your PSDs with us? You can put it into a ZIP and share it here.

Okay, I will try

**Comment by MotziRBX** [comment]
> Could you share your PSDs with us? You can put it into a ZIP and share it here.

The file size is too big for me to upload here. It's literally all my PSDs not working

**Comment by photopea** [comment]
Could you send it to support@photopea.com ? There are 250 000 PSD files opened in Photopea every dayn and nobody reported such a problem.

**Comment by photopea** [comment]
Why did you close it?

**Comment by MotziRBX** [comment]
> Why did you close it?

I realized there probably wasnt anything I could do about it. I saw other people have this problem in other issue tickets, but no one had a solution. So i'll see what works i guess.

**Comment by camoody1** [comment]
> > Why did you close it?
> 
> I realized there probably wasnt anything I could do about it. I saw other people have this problem in other issue tickets, but no one had a solution. So i'll see what works i guess.

I see in your first post that this project is a mockup. Are all of these PSDs mockup files that you've gotten off the internet? You said this problem affects ALL of your PSD files. Have you tried creating a project from scratch, saving it and then reopening it? Does THAT work?

**Comment by photopea** [comment]
Photopea can open every PSD file which Adobe Photoshop or some other program can open.

Please, send us your PSD file to support@photopea.com, it takes you 20 seconds and we will solve it for everyone for free.

**Comment by MotziRBX** [comment]
> > > Why did you close it?
> > 
> > 
> > I realized there probably wasnt anything I could do about it. I saw other people have this problem in other issue tickets, but no one had a solution. So i'll see what works i guess.
> 
> I see in your first post that this project is a mockup. Are all of these PSDs mockup files that you've gotten off the internet? You said this problem affects ALL of your PSD files. Have you tried creating a project from scratch, saving it and then reopening it? Does THAT work?

Yes they are all files I downloaded to edit, and use. I don't know how to make PSD text files from scratch so this is the only way I can use them.

**Comment by MotziRBX** [comment]
> Photopea can open every PSD file which Adobe Photoshop or some other program can open.
> 
> Please, send us your PSD file to [support@photopea.com](mailto:support@photopea.com), it takes you 20 seconds and we will solve it for everyone for free.

I tried sending them, but the files are too big. I tried zipping them, and still couldn't send them so yea.

**Comment by camoody1** [comment]
Do you have a link we can use to find them online like you did? Or can you save some of them to a Google Drive folder and share that folder here?

**Comment by MotziRBX** [comment]
> Do you have a link we can use to find them online like you did? Or can you save some of them to a Google Drive folder and share that folder here? That would get you around the file size limit.

sure i'll try.

**Comment by MotziRBX** [comment]
> Do you have a link we can use to find them online like you did? Or can you save some of them to a Google Drive folder and share that folder here? That would get you around the file size limit.

https://drive.google.com/drive/folders/1iBFfrbtcsfW_OC58gA67CwKiX0gRWgzs?usp=share_link

That's a google drive link to all the ones i've tried using so far.

**Comment by camoody1** [comment]
I was able to open the three that I tried and I'm using an Android mobile phone. I wonder if you have a PC problem? I see a lot of these files are quite large. Maybe you're running out of RAM? Can you tell us what device you're using and some of its specs? Ie PC/Mac/Android, RAM amount, operating system?

**Comment by photopea** [comment]
I downloaded "text_effect_071.psd" of your PSDs. I can open it in Photopea, but it "takes a while" - it is 4000 x 2500 pixels, there are about 30 layers with a Bevel and Emboss and Stroke style, so Photopea asks for 7 GB of RAM.

Try to disable WebGL in More - Use WebGL.

Also, could you tell which file exactly you can not open?

**Comment by MotziRBX** [comment]
> I downloaded "text_effect_071.psd" of your PSDs. I can open it in Photopea, but it "takes a while" - it is 4000 x 2500 pixels, there are about 30 layers with a Bevel and Emboss and Stroke style, so Photopea asks for 7 GB of RAM.
> 
> Try to disable WebGL in More - Use WebGL.
> 
> Also, could you tell which file exactly you can not open?

For me it's not working for any of them sadly. It will load into the website, but then the screen is just blank. Nothing shows up. I will try disabling the WebGL and see if that helps. I have plenty of RAM so i know it can't be that. I will see if disabling that works.

**Comment by MotziRBX** [comment]
> I downloaded "text_effect_071.psd" of your PSDs. I can open it in Photopea, but it "takes a while" - it is 4000 x 2500 pixels, there are about 30 layers with a Bevel and Emboss and Stroke style, so Photopea asks for 7 GB of RAM.
> 
> Try to disable WebGL in More - Use WebGL.
> 
> Also, could you tell which file exactly you can not open?

Also i'm opening them up directly from google drive onto the website, but even when I use the desktop app, they will load in but it will be blank.

**Comment by photopea** [comment]
Can you download a PSD to your computer and open it from your computer?

**Comment by MotziRBX** [comment]
> Can you download a PSD to your computer and open it from your computer?

Yes, but they are blank. They load in, but nothing shows up. Idk If i have to wait longer, but it shows all the layers on the side, just nothing in the editing area.

**Comment by photopea** [comment]
What operating system and a web browser do you use? Do you know how much memory your GPU has?
