### ISSUE TITLE
Loading svg file crashes chrome browser

### ISSUE THREAD

**Issue by AndreyChursin** [photopea/photopea#5550]
Loading any svg file crashes Сhrome browser!

**Comment by camoody1** [comment]
Have you tried opening Photopea in "Incognito" mode and then opening the SVG files? Sometimes, browser extensions can cause big problems with Photopea.

**Comment by photopea** [comment]
I just opened several SVG files in Photopea and they all work well. Could you share one of your SVGs with us?

**Comment by photopea** [comment]
Also, a website should not be able to crash the browser. Only the website (the tab) can be killed by a browser, but the browser should keep running.
