### ISSUE TITLE
Keeps crashing.

### ISSUE THREAD

**Issue by s-usan** [photopea/photopea#5551]
Why does my Photopea keeps crashing whenever i want to save a file?
Ps: I'm on free account not premium.

And is Photopea and photopia the same, or you changed your name.

**Comment by photopea** [comment]
Hi, our product is a photo editor Photopea, which can be used only in a web browser at www.Photopea.com

What exactly are you talking about?

**Comment by photopea** [comment]
I have to close it because of lack of details.
