### ISSUE TITLE
Poor image quality after adding a filter

### ISSUE THREAD

**Issue by MrSdows** [photopea/photopea#5552]
When I add a filter, no matter what, to the image (especially when there are a lot of details), then my image deteriorates greatly in quality. Is there any way to at least reduce this?

**Comment by photopea** [comment]
Hi, what is "quality"? Could you share the version of your image before and after the filter?

**Comment by MrSdows** [comment]
original image: ![New Project](https://user-images.githubusercontent.com/126389963/233780743-6be005e3-62af-491c-ace4-53a5cc5665a1.png)
image after applying the Unsharp Mask filter and boosting the green color: 
![New Project](https://user-images.githubusercontent.com/126389963/233780881-0aa5a4dc-4afc-4259-82fb-a83f7978da9e.png)
I did it quickly, so if you use most filters to make the image look better, it will look better, but the quality will deteriorate a lot. In this example, I'm not sure because I resized the image in Photopea. But I remember recently taking an image and just adding a filter to it, and the quality went down a lot, especially if you add a lot of things. There is no such thing in Abode Photoshop, as I understand it, due to the fact that Abode Photoshop has more "good" algorithms. But I'm not sure.

**Comment by MrSdows** [comment]
I understand that I may have taken the wrong filters because I did it quickly, but you can take any image with fine details (and most of the images that you have to work with are fine details) from the Internet, add some filters and the image will look worse.

**Comment by photopea** [comment]
I think your second image corresponds to applying certain filters to the first image, the result is correct. I can not see any decrease in "quality" (as I dont know what you mean).

Could you show us an image which you want to get out of Photopea instead? Can any software in the world do what you need? If yes, could you show us "what you need"?

**Comment by camoody1** [comment]
I'm looking at your second "after" photo and it looks like you've just applied very bad settings using the Unsharpen Mask. You need to turn your values way down.

Set your Amount to 120%, Radius to 0.8 px and Threshold to 10. I applied these settings and MY after image looks much better than your original.

**Comment by MrSdows** [comment]
I'm sorry, I think I figured out my mistake

**Comment by camoody1** [comment]
> I'm sorry, I think I figured out my mistake

Excellent! Have a great Sunday!

**Comment by MrSdows** [comment]
> > I'm sorry, I think I figured out my mistake
> 
> Excellent! Have a great Sunday!

Thank you very much too!

**Comment by photopea** [comment]
Let us know if we can help you out with anything.
