### ISSUE TITLE
Exporting as PDF and SVG removes font information

### ISSUE THREAD

**Issue by dnicolson** [photopea/photopea#5553]
After opening a PDF file Photopea recognizes the correct font but after exporting as PDF or SVG the font is set to Helvetica. 

To reproduce:
1. Open [Test text.pdf](https://github.com/photopea/photopea/files/11301625/Test.text.pdf)
2. Export as PDF

Using `pdffonts` from Xpdf:

`pdffonts Test\ text.pdf`
```
name                                           type              emb sub uni prob object ID
---------------------------------------------- ----------------- --- --- --- ---- ---------
AAAAAB+OpenSans                                TrueType          yes yes no            7  0
```

`pdffonts Test\ text\ exported.pdf`
```
name                                           type              emb sub uni prob object ID
---------------------------------------------- ----------------- --- --- --- ---- ---------
Helvetica                                      Type 1            no  no  no       [none]
```

**Comment by photopea** [comment]
Our PDF generator can not store fonts into PDF files yet. Please, enable "Vectorize text" when exporting a PDF. Or "rasterize all" to get exactly what you see in Photopea.

**Comment by photopea** [comment]
I will close it now.
