### ISSUE TITLE
Ads on top of layers area

### ISSUE THREAD

**Issue by Iyadbadriii** [photopea/photopea#5555]
https://imgur.com/a/COOR92O

**Comment by photopea** [comment]
"On top of layers area" - but I can not see any layers area below ads.

You can get a Premium account to remove ads, it costs only 16 cents for a day of Photopea with no ads. Press "Account" at the top.

**Comment by bluep55** [comment]
A bit late now but Is this what you mean?
If you click on the 2 tiny arrows shown inside the red circle the layers panel plus all other panels will re-appear.
Click on them again and they will disappear.

![New Project A (1)](https://user-images.githubusercontent.com/118609932/233960211-293b5282-d176-4687-8368-b3e460627bc7.jpg)
