### ISSUE TITLE
Not being able to drag and drop image layer into different tab? 

### ISSUE THREAD

**Issue by carspart** [photopea/photopea#5559]
Wont let me drag and drop image layer into different tab, drags the layer but its blank every time
Also when i go to copy and paste layer instead it loses its size and quality 

Both these issues never use to happen

**Comment by photopea** [comment]
Everything seems to work fine for me. Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by carspart** [comment]
I have tried and still not working, i noticed the issue seems to be with downloaded images doesnt work with but it did use to work fine

**Comment by camoody1** [comment]
Have you tried right clicking on the layer in the Layers panel and choosing "Duplicate Into..."? You can choose a different tab to move it to there.

**Comment by photopea** [comment]
Could you tell us what should we do to see the problem? If it happens only with a specific file, could you share that file with us?

**Comment by carspart** [comment]
![tester](https://user-images.githubusercontent.com/131678357/234050242-a3cb14af-32d2-4658-b1a0-e860e314c5a4.JPG)

**Comment by carspart** [comment]
![image](https://user-images.githubusercontent.com/131678357/234051244-1ef06da3-f9f9-4330-8885-2f827426653d.png)
![image](https://user-images.githubusercontent.com/131678357/234051271-f7f82c7d-4894-4f81-9267-cc6272184a66.png)

This is me dragging and dropping layer to the other tab but comes out as a blank layer

**Comment by carspart** [comment]
> I have tried and still not working, i noticed the issue seems to be with downloaded images doesnt work with but it did use to work fine

I H

**Comment by carspart** [comment]
> Have you tried right clicking on the layer in the Layers panel and choosing "Duplicate Into..."? You can choose a different tab to move it to there.

I have just tried this and still copy over a blank layer :(

**Comment by photopea** [comment]
You should drag and drop layers this whay from the canvas itself, not from the Layers panel.

**Comment by carspart** [comment]
> You should drag and drop layers this whay from the canvas itself, not from the Layers panel.

But this still doesn't work, even copy and pasting doesn't work the same as it changes the quality and size 
Isn't this a bug? as never had issues like this before and have tried loads of different way to try get this to work

Have you tried downloading the 1st image above to see what i mean, try and drop something into that image it will not work

**Comment by camoody1** [comment]
Could you record a video showing your entire process from copy to paste and then post it to Imgur or YouTube so that we could see exactly what you're doing and seeing?

**Comment by photopea** [comment]
What is "dropping something into the image"? I can place new layers into your image.
![image](https://user-images.githubusercontent.com/15955558/234296824-fa972506-0bba-480e-b7ee-10c003bf161b.jpg)

**Comment by carspart** [comment]
> What is "dropping something into the image"? I can place new layers into your image. ![image](https://user-images.githubusercontent.com/15955558/234296824-fa972506-0bba-480e-b7ee-10c003bf161b.jpg)

I cannot drag and drop and layer into that picture, as shown in images above where i sent to 2 screebshots

**Comment by carspart** [comment]
https://user-images.githubusercontent.com/131678357/234305432-ec91b18a-b085-4322-9f35-983b649a591b.mp4

heres a video showing what i mean

**Comment by carspart** [comment]
> Could you record a video showing your entire process from copy to paste and then post it to Imgur or YouTube so that we could see exactly what you're doing and seeing?

added video above

**Comment by photopea** [comment]
As I said before, you should drag it from the document canvas, and not from the layers panel.

Do you know what I mean by the Layers panel and by the document canvas?

**Comment by carspart** [comment]
> As I said before, you should drag it from the document canvas, and not from the layers panel.
> 
> Do you know what I mean by the Layers panel and by the document canvas?

i know what you mean by layers panel but not sure what you mean by document canvas?

I have tried varies ways

**Comment by camoody1** [comment]
> > Could you record a video showing your entire process from copy to paste and then post it to Imgur or YouTube so that we could see exactly what you're doing and seeing?
> 
> added video above

Thank you for recording that. Much appreciated.

**Comment by carspart** [comment]
> Seems like it used to work in Photopea in the past, so I will look into it.
> 
> https://youtu.be/xkoFT2rqJHM?t=159

okayy thankyouu

**Comment by photopea** [comment]
It should be fixed now.

**Comment by carspart** [comment]
Sorry the layer is coming over to other tab now but its still changing size, its suppose to stay the same size when move to another tab

**Comment by carspart** [comment]
https://user-images.githubusercontent.com/131678357/234532309-472fda44-b32b-41fa-8d53-7e8bb5c69caa.mp4

This also happens when copy and pasting which shoulnt distort original size

**Comment by photopea** [comment]
Copied layers keep the same size.

Your first document is 500x500 pixels, your second document is 1600x1600 pixels, can't you see it (e.g. on the rulers)?

**Comment by carspart** [comment]
okay thats makes sense thank you
