### ISSUE TITLE
Stamping layers (merge selected ones as a new layer and keep originals intact)

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#556]
Often times when merging selected layers, the originals are still needed, but there's no easy way to do it right now, photoshop called this stamp layers

**Comment by photopea** [comment]
I have never heard of that feature. I am trying to google it for Photoshop, but I see no results, just a shortcut Shift+Ctrl+Alt+E . I don't think many people use / know this feature.

**Comment by hgs54371** [comment]
Where do you expect the majority of your users to be located at? 
Try using Google NCR (No Country Redirect) google.com/ncr , to avoid biased search result caused by localized version of google search (also youtube). 
Maybe this is why some often used, really helpful features seems to be viewed by you as irrelevant, not important.
Anyways, after all, all that I can do is giving suggestions, isn't it?

**Comment by photopea** [comment]
I don't think my search results are biased.

Can you show me a documentation to Photoshop or some other software, where such feature is described? Or where the feature is located in Photoshop?

**Comment by hgs54371** [comment]
https://helpx.adobe.com/photoshop/using/layers.html
On the right, click Merging layers and scroll down a bit to see the section "Stamp multiple layers or linked layers"
This page shows as the first result for me googling "stamp layers", and I can also see plenty of blog tutorials, youtube tutorials, and forum discussions for this feature

**Comment by photopea** [comment]
The problem is, that when you right-click the layer (in Layers panel in Photopea), there are already many options. Adding another one - "Stamp Layers" - would make it even more messy.

So the only way to stamp layers in Photoshop is using the keyboard shortcut? Should we do it the same way?

**Comment by hgs54371** [comment]
What I often actually use is, select the layers to be merged, then right click - merge layers while holding option(alt), this method merge the selected layers as a new layer without deleting originals
This is more often used then merge down/up, which only involve one neighboring layer, and is not useful when merging a single layer with smart filters (flatten filters as a new one)

**Comment by photopea** [comment]
It was implemented, it should work pretty much the same as in Photoshop.  E.e. adding Alt will preserve original layers.

**Comment by hgs54371** [comment]
The merge layers is greyed out when only selecting one layer (for flatten smart filter and layer style as a new layer)

**Comment by photopea** [comment]
What do you mean by "greyed out"? What exactly did you do?

**Comment by hgs54371** [comment]
I want to merge a single layer with its painted raster/vector mask, smart filters and layer styles as a new layer (preserve original), but in right click menu merge layers is not click-able

**Comment by photopea** [comment]
Why do you call it "merge"? I would call it "duplicate and rasterize a new copy".

So try right-click - Duplicate, right-click - Rasterize.

**Comment by hgs54371** [comment]
In photoshop the "merge layers" function can be used for these two steps in one action, so I put it under the same term

**Comment by photopea** [comment]
How exactly do you duplicate-and-rasterize a layer in Photoshop in one step?

**Comment by hgs54371** [comment]
Right now in photopea I can do merge down with an empty layer underneath while holding opt/alt to achieve same result

**Comment by photopea** [comment]
Ok I thought there was some problem.

**Comment by hgs54371** [comment]
Yes, but I want to do this without that empty layer, merge itself with its accessories

**Comment by photopea** [comment]
Just do right-click : rasterize. I think a new option "Duplicate and Rasterize" would just make the menu more complex.
