### ISSUE TITLE
Psds stolen

### ISSUE THREAD

**Issue by watGFX** [photopea/photopea#5560]
This is an issue for our psds and work stolen, we put them for paid, and they get stolen and put in templates. Maybe a report button or something?

**Comment by camoody1** [comment]
Which templates are yours? Are they mockups? Are they the group of mockups added by the user Printisful about a week ago?

**Comment by photopea** [comment]
Could you go to https://www.photopea.com/templates/  and send us links of templates which are stolen? And provide some proof (e.g. that they were for sale elsewhere much earlier)?

If this keeps happening, we will definitely add a report button.

**Comment by watGFX** [comment]
![Screenshot 2023-04-25 7 53 22 AM](https://user-images.githubusercontent.com/131731186/234282506-a0106c8e-6ab7-4b08-9377-ff51c6baaf2c.png)
![Screenshot 2023-04-25 7 53 00 AM](https://user-images.githubusercontent.com/131731186/234282515-56c365bb-a971-43df-a2e0-041a443b97f3.png)

**Comment by watGFX** [comment]
most of those are ours
Ill send some proof, this design hub guy keeps stealing them, he has multiple accounts i think where we sold them

**Comment by watGFX** [comment]
only 2 of them are mine, but I know the people with the rest of them

**Comment by watGFX** [comment]
obv not the smartest idea selling on discord, but its still not supposed to be for everyone
![Screenshot 2023-04-25 8 03 51 AM](https://user-images.githubusercontent.com/131731186/234285328-48bf6e72-d809-426c-a098-273cac973e6c.png)
![Screenshot 2023-04-25 8 01 22 AM](https://user-images.githubusercontent.com/131731186/234285330-78b45c55-146a-4886-b86b-e64b07c14cfd.png)
![Screenshot 2023-04-25 7 58 31 AM](https://user-images.githubusercontent.com/131731186/234285332-9dfd6a33-26b4-495c-9d56-b4ae8e8523e8.png)

**Comment by camoody1** [comment]
I've seen some of these templates offered for free on other websites. If the user is posting templates that are supposed to paid for, though, those should be deleted for sure. Not sure where you stand on reposting free templates, though.🤷🏽‍♂️

**Comment by photopea** [comment]
I have unpublished all templates from that user.

When someone publishes a tmplate, we can not tell if it is stolen or not. That is why it is important that the original author reports it.

If someone publishes a free template, we can still take it down, if the original author wants it to be taken down. My idea was, that people who make templates would publish it in our database directly, and share links with each other, instead of sending PSD files between each other.

**Comment by watGFX** [comment]
thanks! ur the goat frr
