### ISSUE TITLE
THE ADS DOENST LET ME WORK

### ISSUE THREAD

**Issue by dohkovolnutt** [photopea/photopea#5562]
I'm trying to work in photopea and the "F" ads are popping up every 5 seconds ALL DAY LONG, cannot open a file, and if I do, I CAN'T DO ANY KIND OF EDIT.

**Comment by camoody1** [comment]
The ads should be off to the right side of the screen leaving you plenty of room for your canvas and tools. What exactly are you seeing on YOUR screen? Perhaps send a couple of screen shots so we can see what's happening.

Also, try running Photopea in "Incognito Mode". You might have some browser extensions causing you problems.

**Comment by photopea** [comment]
Photopea has no popping ads. I think you have a browesr extension, which inserts ads into Photopea: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

Please, report only problems for which you can prove that they still happen even with all browser extensions disabled.
