### ISSUE TITLE
Feature Request: Magic Eraser

### ISSUE THREAD

**Issue by AviceProjects** [photopea/photopea#5564]
The best we have is content-aware fill. Having an AI-powered magic eraser would be awesome. The cheapest API you don't have to request access to is Picwish.

**Comment by photopea** [comment]
I tihnk Picwish is quite expensive: https://picwish.com/pricing

Or are you already paying for Picwish and you want to use it through Photopea?

**Comment by camoody1** [comment]
@photopea I looks like they offer a totally free API option for image enlargement! You should absolutely jump on this. They only go up to 4x enlargement, but the results look really good!

https://picwish.com/image-enlarger

**Comment by photopea** [comment]
I looked here - https://picwish.com/photo-enhancer-api - and there is a button "Pricing". If it was free, I think there would be no button "Pricing".

**Comment by camoody1** [comment]
> I looked here - https://picwish.com/photo-enhancer-api - and there is a button "Pricing". If it was free, I think there would be no button "Pricing".

Yeah, I think I jumped to conclusions too quickly. Enlargement is free when done on their site or if you download their app. But apparently, it's considered as part of their Image Enhancement tool when it uses API. Crap.

**Comment by AviceProjects** [comment]
Yeah, it's around $0.01 per object removal, which is the cheapest advertised price I could find. You could contact other companies for a potentially cheaper API. If you can't find anything cheap enough, you could restrict the feature to premium users.

**Comment by photopea** [comment]
We have background removal in Photopea (Select - Remove BG) and we pay $0.001 per removal. We do a million removals per month, so it costs us $1,000 per month.

**Comment by AviceProjects** [comment]
Some other services you could quest access to are: depix.ai, magicstudio.com, and pixelcut.ai

**Comment by photopea** [comment]
We can implement only services with an API, where the cost is at most  $0.001 per action.

**Comment by AviceProjects** [comment]
Those services don't have prices listed. You would have to get a quote for the API by contacting them. I do know depix.ai offers a $9 unlimited personal plan, so that might be a good first one to contact.

**Comment by camoody1** [comment]
> Some other services you could quest access to are: depix.ai, magicstudio.com, and pixelcut.ai

magicatudio.com looks like the most useable tool of the three from my quick research. No pricing listed, of course, but they do offer an API option and their tool looks the most likely to require less development work.

**Comment by photopea** [comment]
The $9 plan of depix.ai does not include using the API: https://depix.ai/pricing

**Comment by AviceProjects** [comment]
> The $9 plan of depix.ai does not include using the API: https://depix.ai/pricing

I know, I said they might be a good first one to contact since they offer such a cheap personal plan :)

**Comment by photopea** [comment]
These AI features costs money. Even if we had the same number of users as Adobe Photoshop, we can not compete with them, simply because we dont get $15 a month from each of our users, like Photoshop does.

**Comment by AviceProjects** [comment]
@photopea 

If you want this feature added, I got a very promising email from Pixelcut saying that they handle over 10 Million API calls a day, and have some of the cheapest prices out there. You can set up a talk with them here https://calendly.com/pixelcut-ai/30min?month=2023-05

**Comment by photopea** [comment]
@AviceProjects I guess you work for Pixelcut. So how much does it cost? Could you publish the prices on your website?

I can pay 2 USD per 1000 object removals, would it be interesting to you? That is how much I am paying at Dezgo https://twitter.com/photopeacom/status/1656375367379177491

**Comment by AviceProjects** [comment]
No, I don't work for Pixelcut XD I just had some free time and wanted to help you find the cheapest price for this feature. I also emailed magicstudio, which told me they would get back to me in a few days. I also made sure the tell them I was unassociated with you, but I wanted an estimate for Photopea (So I wouldn't waste their time if you had already emailed them)
