### ISSUE TITLE
PDF mime types on Linux

### ISSUE THREAD

**Issue by tuconeves** [photopea/photopea#5565]
Photopea is changing the way the system recognize PDF files:

![With photopea](https://user-images.githubusercontent.com/88161035/234996314-db96d6f2-ffea-47d7-8c72-22923a49fbef.png)

![Without WPA](https://user-images.githubusercontent.com/88161035/234996431-7e083e32-de56-4d2a-b84f-53dc441f2021.png)

Since photopea is installed, the mime type of all pdf files is changed to image/pdf and the system handles it as images. Google Drive also doesnt recognize the file as pdf.

Disablling this option on Chrome WPA settings solves the problem, but we lost the "open with" funcionality
![WPA Settings](https://user-images.githubusercontent.com/88161035/234997204-35e85201-beed-45f2-8740-0df8b09b893d.png)

Is it possible to take off "image/pdf" mime type from photopea integration? PDF files are always handled as "application/pdf".

[Edit1: Using Zorin OS 16.2 and Chrome .deb]

Thanks

**Comment by photopea** [comment]
It is all written in our manifest: https://www.photopea.com/manifest.json

Basically, "file_handlers" is supposed to tell the OS, which formats can be opened by a webapp. Everything else is up to the browser and OS (how they deal with that information). If we removed the "pdf", you would not be able to right-click PDF files to open them in Photopea, right?

**Comment by photopea** [comment]
I have to close it because of lack of details.

Personally, I think Photopea just tells the OS what formats it can open. The behaviour of the OS is up to the OS.

**Comment by tuconeves** [comment]
> It is all written in our manifest: https://www.photopea.com/manifest.json
> 
> Basically, "file_handlers" is supposed to tell the OS, which formats can be opened by a webapp. Everything else is up to the browser and OS (how they deal with that information). If we removed the "pdf", you would not be able to right-click PDF files to open them in Photopea, right?

Thanks for replying!

Exactly! That's the point.
The standard pdf mime type is "application/pdf".

"image/pdf" doesn't even exist on IANA list https://www.iana.org/assignments/media-types/media-types.xhtml

Photopea is adding this mime type to the systems lists, and no other apps recognizes it. Neither google drive does. What about removing "image/pdf" from the manifest keeping just "application/pdf"?

**Comment by photopea** [comment]
Ok, I have changed the Mime type to "application/pdf" in manifest.json, hope it helps. You might need to "reinstall" Photopea.
