### ISSUE TITLE
Can't save IMG

### ISSUE THREAD

**Issue by vuiakne** [photopea/photopea#5566]
Can't save export image. When I press Ok in "You have to watch a short ad..." nothing happens and I can't watch ads. Sometimes it turns out that an empty window opens for 30 seconds, but this is very rare

**Comment by photopea** [comment]
Could you try it again? Do you have any apps or any software in your phone that could be blocking ads? Or maybe your school or your employer (who provides you the internet) is blocking ads?

**Comment by photopea** [comment]
I have to close it because of lack of details.
