### ISSUE TITLE
Not able to free transform?

### ISSUE THREAD

**Issue by fohrbz** [photopea/photopea#5567]
Everytime i go to free transform to make icons, it doesn't load nor transform. Also, it turns the whole screencap as if its got a blank background.

**Comment by camoody1** [comment]
How large is the image that you're trying to transform? I get symptoms like that when I'm messing with very large images on my phone and run out of VRAM.

**Comment by fohrbz** [comment]
Tbh I have no idea. I've never had the issue until now. And it's doing that to even my 200x100 sized icons.

**Comment by DarwinGamerLoko** [comment]
Yup, same problem here, regardless of image size. It must have started today because I used this software the whole day yesterday.

**Comment by fohrbz** [comment]
Yup! I literally just used it yesterday too!

**Comment by lxryn** [comment]
Mine is doing the same thing. It's very frustrating and annoying!

**Comment by lxryn** [comment]
it's like it's lagging

**Comment by gf12322** [comment]
Just made an account to say that I am having the same problem, it was working an hour ago now it started to happen.

**Comment by DarwinGamerLoko** [comment]
Btw I just found out that if you select the layer that you want to transform (CTRL + Click on the layer mini preview in the layers tab) and then CTRL + ALT + T the transform doesn't bug. Super weird, hope they fix it soon

**Comment by camoody1** [comment]
I messaged the developer. He lives in eastern Europe, though, so he's asleep, right now. Not sure if he'll get my message or not.

In the meantime, try using the Transform -> Scale tool. That seems to work okay for me.

**Comment by gf12322** [comment]
News: using the blending option ends up in the same bug

**Comment by lxryn** [comment]
> I messaged the developer. He lives in eastern Europe, though, so he's asleep, right now. Not sure if he'll get my message or not.
> 
> In the meantime, try using the Transform -> Scale tool. That seems to work okay for me.

this is not work for me 👎  :(

**Comment by camoody1** [comment]
> > I messaged the developer. He lives in eastern Europe, though, so he's asleep, right now. Not sure if he'll get my message or not.
> > In the meantime, try using the Transform -> Scale tool. That seems to work okay for me.
> 
> this did not work for me 👎 :(

Yeah. It's not working for me either, now. :(

**Comment by camoody1** [comment]
> 

Yes, this works for me, too. If I select the layer that you want to transform, I am then able to use the Free Transform tool.

**Comment by camoody1** [comment]
Oh, this is really weird. I just noticed that I can Free Transform to make my image LARGER, but not smaller. Making it larger works fine. Wild.

**Comment by lxryn** [comment]
mine did that for a short sec then started lagging again

**Comment by eRaZeCooler** [comment]
Looks like im having the same problem xD. Every time im scaling anything, and then i press the tick at the top to confirm the scaling. it just goes transparent.

**Comment by 0954lag** [comment]
Yeah this needs to be fixed, I cannot do anything rn because whenever I scale or make layers everything goes blank and freezes

**Comment by photopea** [comment]
I am very sorry, it is fixed now. Please, clear your cache, or wait an hour and reload Photopea. It should work well again.
