### ISSUE TITLE
PSD File Issue

### ISSUE THREAD

**Issue by JaxHendricks** [photopea/photopea#5568]
So, I am attempting to open a rather large PSD File (~1.2gbs) to edit one of my projects. I am getting a interesting error that says "Not enough Ram, Needs ##mb", and when I am able to get the projects to open, they are un-editable. I click on something and nothing changes and, none of the layers show up.

It is essentially acting like nothing exists when the project does open.

What I know:
This has never been a issue for me with photopea, and before the projects have opened fine. All of a sudden this has changed.

What I've tried:
Using different Browsers. Browsers used: OperaGX, Chrome.
Using Incognito Mode in both Browsers.

**Comment by photopea** [comment]
I am very sorry, it is fixed now. Please, clear your cache, or wait an hour and reload Photopea. It should work well again.
