### ISSUE TITLE
Only Loading

### ISSUE THREAD

**Issue by mithila1993** [photopea/photopea#557]
When I log into the site & open the file, it is only shown 'Loading' msg only

**Comment by photopea** [comment]
Hi, can you send us one of your files to support@photopea.com ?

**Comment by mithila1993** [comment]
Thanks for reply

**Comment by photopea** [comment]
so will you send it to us?

**Comment by mithila1993** [comment]
I sent the file

**Comment by photopea** [comment]
Was this file made by Photopea or Photoshop? It has a strange structure.

**Comment by photopea** [comment]
I fixed it, but I still don't understand it.

**Comment by mithila1993** [comment]
Thank you very much.. 
It was made by Photoshop. Now it is working.
I have another file. But it is not open through photopeo. (It shows same previous error)
Please help me to edit through photopeo
I sent file trough email
