### ISSUE TITLE
Scaling issues

### ISSUE THREAD

**Issue by eRaZeCooler** [photopea/photopea#5570]
Heya Designers. So whenever i put any images or anything onto photopea it shows as i pasted it. But as soon as i start scaling it and press the tick at the top of the screen to confirm the scaling, it just goes transparent. then im not able to do anything.

Ive tried restarting my Computer, which is not the problem.
ive tried uninstalling Photopea and reinstalling, which also dosnt work.

If anyone got an solution please let me know.

**Comment by sarunyoochun** [comment]
I'm working on the browser version and got exactly the same issues.

**Comment by arjayethPSU** [comment]
Same to me bro lol i thought its my computer fault

**Comment by Nightfall-21** [comment]
Yeah, same here

**Comment by photopea** [comment]
I am very sorry, it is fixed now. Please, clear your cache, or wait an hour and reload Photopea. It should work well again.
