### ISSUE TITLE
Scaling Bug

### ISSUE THREAD

**Issue by arjayethPSU** [photopea/photopea#5571]
Once i paste and image and resize it it will freeze and become blank pls fix asap

**Comment by eRaZeCooler** [comment]
aha, same problem..

**Comment by jeanphillippe** [comment]
Same issue yeah

**Comment by Nightfall-21** [comment]
Thank goodness I'm not the only one.

**Comment by FerdC17** [comment]
when I erase part of the png and try to scale it brakes the website and makes everything slow and causes the png to disappear

**Comment by photopea** [comment]
I am very sorry, it is fixed now. Please, clear your cache, or wait an hour and reload Photopea. It should work well again.
