### ISSUE TITLE
Freezing When Scaling

### ISSUE THREAD

**Issue by Nightfall-21** [photopea/photopea#5573]
Hello! So whenever I try to scale/resize an image, everything freezes and disappears. I have turned my laptop on and off, uninstalled and reinstalled the app, and tried to work with it in incognito mode, but it still doesn't work.

**Comment by Penguin070** [comment]
Having the exact same problem as well, everything else works except the transform options.

**Comment by photopea** [comment]
I am very sorry, it is fixed now. Please, clear your cache, or wait an hour and reload Photopea. It should work well again.
