### ISSUE TITLE
Cannot Resize Layer using Free Transform

### ISSUE THREAD

**Issue by Pimvard** [photopea/photopea#5577]
Everything freezes after using free transform. I have already removed all browser extensions, but the issue persists on both Chrome and Edge. This seems to be an issue only when using Photopea via PC. I have tried accessing it on both iPhone and Android browsers, and it works fine. The issue was discovered today; it was working normally yesterday. My PC specs are Intel Core i5 11th Gen, 16 GB of RAM, and RTX 2060 with 12 GB of VRAM.

**Comment by camoody1** [comment]
There was a Photopea issue with this earlier tonight, but the developer fixed it about an hour ago. It wasn't working for me earlier, either. But now it is.

Dev suggested clearing your browser cache and trying again.

**Comment by photopea** [comment]
It should be fixed now, just reload www.Photopea.com

**Comment by Pimvard** [comment]
Thanks, it works now.
