### ISSUE TITLE
Problem with actions and Filter Gallery

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5578]
Good day!
When trying to write filters from the Gallery to an action, commands are not inserted into the action stack. At the same time, having recorded a similar action in Photoshop, you can open it in Photopea. Despite the fact that Photopea says about an import error, this action works successfully

**Comment by photopea** [comment]
Hi, what is "write filters from the Gallery to an action"?

**Comment by Pt-home** [comment]
For example, i have add in action step 1  - Glowing Edges and step 2 - Cutout.
But now this steps no added near action recording.
Recording this steps in PS, save atn-file in PS, open atn in Ptotopea - OK, action added and true working...

**Comment by photopea** [comment]
Fixed! Photopea should be able to record filters from the Filter Gallery as actions now :)

**Comment by Pt-home** [comment]
Wonderful!
Ivan, many thanks for the project from the computer science teachers of Ukraine, Photopea opens up a lot of opportunities for children for creativity and education!

**Comment by photopea** [comment]
You are welcome! Thanks for helping us solve problems in Photopea :)

**Comment by Pt-home** [comment]
No problem:)
By the way, I just checked the rest of the filters (not from the Gallery) and there were several that also refuse to be added to the Action.
I guess that the roots of the problem are in the "great and terrible" executeAction()...
I will then open a new issue with a list of these filters that have not yet been added...
