### ISSUE TITLE
Issues with Transform

### ISSUE THREAD

**Issue by NeticDesigns** [photopea/photopea#5579]
Alright, so I was doing a Sci-Fi based GFX and used some vectors and stuff like that right? After, I was done with the logo for the GFX. I was gonna scale it down to make it smaller, suddenly Photopea paused for 10 seconds, my screen turns the darkest of blacks and it shows a gray screen of Photopea. I can still interact with Photopea, but I can't see my work.

**Comment by camoody1** [comment]
If you could hear me right now, you would hear the sound of TAPS playing on a trumpet.🎺
RIP 💀

**Comment by fohrbz** [comment]
This is the same issue i was having last night and they said they had fixed it but it's STILL doing it.

**Comment by fohrbz** [comment]
It also looks like photopea is down as of now.

**Comment by camoody1** [comment]
It's working fine for me right now. I even refreshed my browser to make sure it wasn't a new update causing issues.

Perhaps clear your browser cache and reload Photopea? No one else seems to be complaining of these issues, currently.

**Comment by fohrbz** [comment]
i tried that and it's not even loading on my phone either.

**Comment by camoody1** [comment]
> i tried that and it's not even loading on my phone either.

Photopea isn't loading at all for you? It's not just the transform issue from last night?

**Comment by fohrbz** [comment]
it was working and then i closed it out  for a second because the transform still isnt working.  and now its not loading at all. i cleared my cache, etc and even restarted my laptop but nope. nothing is working at all. idk if it's my hotel's wifi or what since i'm on vacay

**Comment by camoody1** [comment]
> it was working and then i closed it out for a second because the transform still isnt working. and now its not loading at all. i cleared my cache, etc and even restarted my laptop but nope. nothing is working at all. idk if it's my hotel's wifi or what since i'm on vacay

My bet would be on your hotel wifi having a block on the website for some reason. Can you use a phone hot spot for a couple of minutes to see if it works? I doubt your hotel has an IT guy available to help you.

**Comment by fohrbz** [comment]
YOU'RE RIGHT! it was indeed, my hotel's wifi that had it blocked.  it loaded perfectly the moment i turned my phone's hotspot on.

**Comment by fohrbz** [comment]
and now!! it's allowing me to free transform perfectly! thank you for suggesting that!

**Comment by camoody1** [comment]
Outstanding! Glad you're able to take care of your graphic design needs while on vacation. 😆

Now, go ask the front desk for $10 off your bill to cover your hotspot costs. 👍🏼
