### ISSUE TITLE
hide/show everything but doc with tab (or other key)

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#558]
ps has very convenient feature: you can hide / show toolbars/layers list/etc. with hitting TAB

not critical at all, but very convenient,  when you can hide everything except the document you work on with one key at any moment, to focus + utilize screen 100%. Then restore all the toolbars exactly as they were with another hit.

If such feature is ever considered, I would prefer for this to hide everything (including menu and what is under menu), kind of an almost "full screen", but may be others would prefer it to work differently

If TAB is not used in photopea, it'd be ok to follow the ps shortcut?

**Comment by photopea** [comment]
Hi. It was implemented.

I think this feature is really nice! And it only took like 3 minutes to implement. Thanks for suggesting it!
