### ISSUE TITLE
Color Picker

### ISSUE THREAD

**Issue by NeticDesigns** [photopea/photopea#5583]
I have an issue with my Color Picker, when sometimes while doing my graphical design. When I click "Okay!" on it, it doesn't even work or budge and when I click the gfx and move my mouse around it automatically picks a color, but I still can't close the god damn caption aka "Ok!". How can you fix it?

**Comment by photopea** [comment]
Hi, what should I do after opening www.Photopea.com to see this happen?

**Comment by GAMERBOYRYT** [comment]
Its also happening to me...

**Comment by camoody1** [comment]
@NeticDesigns @GAMERBOYRYT Could one or both of you please record a short video of you repeating this issue? You can upload the video to YouTube or Imgur and then drop a link here.

**Comment by NeticDesigns** [comment]
@camoody1, @photopea Well, said problem happens by surprise; not out of a normal occurrence, just completely out of the blue and random.

**Comment by camoody1** [comment]
If we can't repeat the problem, it's super difficult to find a solution. 🤷🏽‍♂️

**Comment by joestoneman** [comment]
Here is a short video displaying the issue: https://youtu.be/nS-vU33yHGs

The colour picker window gets stuck. Confirming or attempting to close does not work. The colour picker ring also gets stuck. Actions cannot override the issue.

**Comment by camoody1** [comment]
Another report of this same issue on Reddit.
https://www.reddit.com/r/photopea/comments/138521e/bug/?utm_source=share&utm_medium=web2x&context=3

**Comment by photopea** [comment]
I really wish I could reproduce it :( Guys, please, if you find a way how to make it happen on purpose (every time), I can pay you $500.

**Comment by camoody1** [comment]
> I really wish I could reproduce it :( Guys, please, if you find a way how to make it happen on purpose (every time), I can pay you $500.

That's it... I'm just gonna break it myself. I need $500.
