### ISSUE TITLE
Photopea keeps loading old/crashed files

### ISSUE THREAD

**Issue by CxryzNFTs** [photopea/photopea#5584]
So Photopea when I start it up, loads old/crashed files. I have tried almost every method to prevent this from happening, but it still does.

So first method I've tried was doing Ctrl + S, and closing the psd using the 'x'. The 2nd method was me just closing the psd without saving, And I've also tried clearing my storage. Nothing works.

How can I turn it off so that the crashed file doesn't load when I open Photopea? It takes up alot of ram.

**Comment by CxryzNFTs** [comment]
Note ; I already tried everything from here
https://github.com/photopea/photopea/issues/5481

I think it's best to add a system to manage the psds which are loaded or at least to turn them off.

**Comment by photopea** [comment]
Could you disable all your browser extensions (while not having Photopea opened), then, open www.Photopea.com, close all opened projects, close www.Photopea.com , and open www.Photopea.com again? Are your documents still there?

**Comment by photopea** [comment]
In short: with no browser extensions, closing a project in Photopea should close it permanently.

But it is hard to tell which of your extensions is breaking Photopea, that is why I suggest disabling all of them to try it.

**Comment by photopea** [comment]
Did it work? I will close it, but we can keep discussing it.
