### ISSUE TITLE
Issue with Cutout Feature from Filter Gallery after apply Poster Edges from Filter Gallery and Oil Paint from Stylize

### ISSUE THREAD

**Issue by JoshNelson27** [photopea/photopea#5585]
I have tried numerous ways of refreshing my page to resolve this issue but anytime I try to apply this filter after using poster edges filter and then the oil point feature from stylize from page becomes unresponsive when applying the Cutout feature after preforming those two things. Any thoughts or ways I could resolve this issue? Thank You

**Comment by photopea** [comment]
I have applied the Cutout filter to an image, and then, I applied the Oil Paint filter. It seems to work well.

How many pixels do you have in your image? 100, a million, a billion? Are you doing it on a phone? How old is your computer?

The Oil Paint filter runs on the GPU and if you dont have GPU-accelerated WebGL, your computer (or phone) will get stuck.

**Comment by apathyash** [comment]
Hello,
I'd just like to chime in that I am having a similar issue when using the Cutout filter. Once I've selected the cutout filter, the program slows and if I try to adjust the number of levels/edge simplicity/edge fidelity, the program freezes until the browser forces the page to quit.

**Comment by photopea** [comment]
It should be fixed now, thanks for reporting it! :)
