### ISSUE TITLE
Again Filters and Action

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5586]
Currently still not added to Action:
Blur:
LensBlur
Distort:
	Kaleidoscope
	ZigZag
Noise:
	Dispeckle
Pixelate:
	Crystallize
	Fragment
              Pointillize
Render:
	Fibers
Sharpen:
	Sharpen Edges
Stylize:
	Emboss
	Solarize
	Trace Contour
	Wind
Other:
	Repeat
	Color to Alpha
	Dither
	Particles
and 
      pair filters Fouriers
      
With regards and thanks for Photopea

**Comment by photopea** [comment]
Thanks for reporting! All these filters should be recordable now, and if you have an action with them, they should be executed correctly (even if the action was made in Photoshop or something else).

Note, that many of these filters are not available in Adobe Photoshop, so if you save them in the .ATN file, that step will not run correctly in Adobe Photoshop.

Those filters are: Kaleidoscope, Repeat, Color to Alpha, Dither, Particles, Fourier filters.
