### ISSUE TITLE
Unable to close/confirm Colour Picker tool window

### ISSUE THREAD

**Issue by joestoneman** [photopea/photopea#5590]
On many occasions we have been unable to close the colour picker window once opened. This is either applying the changes or closing to cancel. The colour picker ring which appears usually only when you click the tool, is also constant and will not disappear unless you track all the way back to before the initial action was performed:

![image](https://user-images.githubusercontent.com/121166392/235698346-9457e506-b89a-421a-9c49-377d69371eec.png)

**Comment by joestoneman** [comment]
The cursor also disappears when this error is happening.

**Comment by photopea** [comment]
Could you tell me, what should I do after opening www.Photopea.com to not be able to close the color picker?

**Comment by photopea** [comment]
Could you find a way how to make it happen? Do you open it from a toolbar or from some other place?

I need to make it happen on my computer, to be able to analyze it and fix it.

**Comment by photopea** [comment]
I will close it, as we are already discussing it here: https://github.com/photopea/photopea/issues/5583
