### ISSUE TITLE
Can't resize/transform images

### ISSUE THREAD

**Issue by TBAProgramming** [photopea/photopea#5591]
i'm opening photopea for make a logo but i'm want to upload image to photopea and want to resize/transform but won't do it
can someone help me

**Comment by TBAProgramming** [comment]
can anyone help me

**Comment by photopea** [comment]
Hi, what should I do to see such problem happen myself? Or could you record a video of a problem? 

What is an "image"? Is it a JPG file or what?

**Comment by photopea** [comment]
I have to close it because of lack of details.
