### ISSUE TITLE
Colour Picker or most closeable frames broken

### ISSUE THREAD

**Issue by LetsGoLolly** [photopea/photopea#5593]
Hello! Im using Photopea to make ui interface. Everytime i want to change a colour on the colour palett or when im doing a gradient on a object, it doesnt let it close. With that i mean when i click on the x or on OK, it doesnt close sometimes, i mean sometimes it works and sometimes it doesnt work, and then i have to reset my progress, because im closing Photopea. 

Im using Photopea on Google Chrome

**Comment by photopea** [comment]
We are discussing it here: https://github.com/photopea/photopea/issues/5583

It would be great if you could find specific steps which lead to this problem. I need to reproduce it somehow.
