### ISSUE TITLE
Question about correct execution through a script SmdS, Spng (and Spt also)

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5596]
**Problem 1**
In playground dont execute now:
`// =======================================================
var idGEfc = charIDToTypeID( "GEfc" );
    var desc57 = new ActionDescriptor();
    var idGEfk = charIDToTypeID( "GEfk" );
    var idGEft = charIDToTypeID( "GEft" );
    var idSmdS = charIDToTypeID( "SmdS" );
    desc57.putEnumerated( idGEfk, idGEft, idSmdS );
    var idStrL = charIDToTypeID( "StrL",  );
    desc57.putInteger( idStrL, 2 );
    var idHghA = charIDToTypeID( "HghA" );
    desc57.putInteger( idHghA, 0 );
    var idIntn = charIDToTypeID( "Intn" );
    desc57.putInteger( idIntn, 10 );
executeAction( idGEfc, desc57, DialogModes.NO );

// =======================================================
var idGEfc = charIDToTypeID( "GEfc" );
    var desc59 = new ActionDescriptor();
    var idGEfk = charIDToTypeID( "GEfk" );
    var idGEft = charIDToTypeID( "GEft" );
    var idSpng = charIDToTypeID( "Spng" );
    desc59.putEnumerated( idGEfk, idGEft, idSpng );
    var idBrsS = charIDToTypeID( "BrsS" );
    desc59.putInteger( idBrsS, 2 );
    var idDfnt = charIDToTypeID( "Dfnt" );
    desc59.putInteger( idDfnt, 12 );
    var idSmth = charIDToTypeID( "Smth" );
    desc59.putInteger( idSmth, 5 );
executeAction( idGEfc, desc59, DialogModes.NO );`

**Note**
My JS-skill very low, but I see in pp.js in 9009 line next code:
` if (e == "SmdS")
            d.X.akN(o.buffer, K, a, X.buffer, [S.StrL.v, S.HghA.v, S.Intn.v, S.FlRs.v, C]);
        if (e == "Spng")
            d.X.ajM(o.buffer, K, a, X.buffer, [S.BrsS.v, S.Dfnt.v, S.Smth.v, S.FlRs.v, C]);`

**Question 1**
 What is  S.FlRs and how right call SmdS and Spng in Photopea scripts?     

**Problem 2**
In playground dont execute now also:
`// =======================================================
var idGEfc = charIDToTypeID( "GEfc" );
    var desc14 = new ActionDescriptor();
    var idGEfk = charIDToTypeID( "GEfk" );
    var idGEft = charIDToTypeID( "GEft" );
    var idSpt = charIDToTypeID( "Spt " );
    desc14.putEnumerated( idGEfk, idGEft, idSpt );
    var idSprR = charIDToTypeID( "SprR", );
    desc14.putInteger( idSprR, 10 );
    var idSmth = charIDToTypeID( "Smth" );
    desc14.putInteger( idSmth, 5 );
executeAction( idGEfc, desc14, DialogModes.NO );`

**Question 2**
 How fixed and this problem? Note: in pp.js I'm not see 4-CharID "Spt ", but see fragments: e == "Spt"... May be problem in this?  

Thanks in advance for the answers and, of course, for Photopea)...

**Comment by photopea** [comment]
You say " dont execute now" , so it worked correctly in the past?

**Comment by Pt-home** [comment]
Of course, I don't know if it worked in the past. I just see that the problem is the absence of the fourth parameter, which is incomprehensible to me. And I can rely only on the fact that when calling these two first filters through the user interface, there are only three parameters

**Comment by photopea** [comment]
It should be fixed now, your scripts should run well now.

Note, that you have an error in this line - there is an extra comma:

    var idStrL = charIDToTypeID( "StrL", );

**Comment by Pt-home** [comment]
Great thanks!
