### ISSUE TITLE
Photopea not loading as intended

### ISSUE THREAD

**Issue by SwishSwashSwosh** [photopea/photopea#5598]
I have 10-12 GB of RAM available at any given time, old versions of photopea used to load 150+ MB files with mild strain, new versions now barely load anything higher than 50MB, tried opening a 90MB PSD file, went straight to white, tried to deselect a part and it takes 3 minutes for it to finally happen, mind you its then eating up 9GB of ram just loading mostly transparent images, will refuse to unload a folder

how do I make photopea not eat my RAM cards for lunch?

(also can't use GIMP as it completely breaks raster masks for no reason)

**Comment by camoody1** [comment]
Interesting. I was just working in a 253MB PSD file earlier this evening. It ran smoothly for me, though saving the PSD after making changes did take a minute or more.

Have you tried running Photopea in Incognito Mode? I've had issues before when one of my browser extensions caused problems.

**Comment by photopea** [comment]
Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

Every pixel takes 4 Bytes of RAM, the size of your PSD does not mean anything (as pixels are compressed).

You can have a 300 MB PSD with one layer (a photo), 10,000 x 10,000 pixels, it takes 400 MB of RAM in Photopea.

You can have a 20 MB PSD with one layer (fully white), 20,000 x 20,000 pixels, it takes 1.6 GB of RAM in Photopea.

If you could prove that the same file works worse in Photopea than it used to, that would be a "proof".

**Comment by photopea** [comment]
I have to close it because of lack of details.
