### ISSUE TITLE
Photopea Opening in Desktop Mode on my Samsung Galaxy S22 Ultra

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5599]
Something has changed in the last couple of days that is causing Photopea to open in Desktop Mode on my Samsung Galaxy S22 Ultra. No other website opens in desktop Mode by default. This even happens in Incognito Mode.

When I try to open a PSD from storage, the screen GUI becomes very small (as if on a desktop) and the project appears inverted in color. If I rotate to landscape mode, the project appears correct, though it remains in desktop mode. If I rotate back to portrait, the tiny GUI and inverted project reappears. If I try to switch to Mobile Mode, Photopea reloads and I have to reopen my project... which results in the same issue repeating.

If I select View -> Mode -> Fullscreen while in landscape, I can rotate back to portrait and it stays looking correct.

This same problem happens with installed Photopea, also.

This feels like it began around the same time you made the keyboard change for mobile devices... but that could just be a coincidence. Basically, Photopea is unusable on my phone, now.

Help me, Obi-Wan... you're my only hope.

**Comment by camoody1** [comment]
![Screenshot_20230505_051224_Edge](https://user-images.githubusercontent.com/73725653/236420719-50e50e4d-5e57-463d-b52a-7251d6f0f658.png)
![Screenshot_20230505_051234_Edge](https://user-images.githubusercontent.com/73725653/236420721-d042dc8b-ccfc-434c-b235-29a7e8b09f1a.png)
![Screenshot_20230505_051428_Edge](https://user-images.githubusercontent.com/73725653/236420725-90894917-745a-4e7f-a2b0-f3214920ca52.png)

**Comment by camoody1** [comment]
Additional Info:
If I open Photopea and choose to create a new project, the GUI stays normal size and I can work in the app. But as soon as I open an existing PSD, everything goes to poop.

**Comment by photopea** [comment]
Are you using Photopea at www.Photopea.com? I can not see the URL in your screenshots. What web browser do you use?

**Comment by camoody1** [comment]
I use Microsoft Edge on my phone. Like I said, this just started happening Wednesday night (US Eastern Time), I believe.

**Comment by photopea** [comment]
I did not do anything to Photopea. Are you sure your browser is not set to the desktop mode for Photopea?

**Comment by camoody1** [comment]
I am 100% sure that I have done nothing to make Photopea keep switching to Desktop Mode. 

As I said, when I open Photopea, now, it opens in Desktop Mode by default. If I switch it back to Mobile Mode, it reloads Photopea and closes the project. So, I open the project again, and Photopea switches back to Desktop Mode. No other website I go to does this. Everything opens in Mobile Mode by default. I have even cleared the browser cache for the Photopea site.

**Comment by camoody1** [comment]
Here is a link to a video I just made showing the issue I'm seeing. Enjoy my sexy voice, again.

https://youtu.be/pjPbM5mVSKs

**Comment by photopea** [comment]
I installed Microsoft Edge on my Android Phone (Pixel 4a 5G). When I do the same thing as you did in your video, but everything works well.

Could you try to open a file using File - Open, instead of a PeaDrive? Does it happen only with a PeaDrive?

Could you try it all in Google Chrome?

**Comment by camoody1** [comment]
Same problem whether opening from device, OneDrive or PeaDrive.

No problem in Chrome.

Installed Edge Beta... No problem in Beta.

Uninstalled Edge and then reinstalled... No problem in reinstalled Edge.

So... I guess some setting was corrupt. 🤷🏽‍♂️ Uninstalling and reinstalling seems to have resolved the issue.

I should have known better. Sorry to bother you.

**Comment by photopea** [comment]
No problem, I was pretty sure it is a bug in a browser on in the OS, but I still wanted to help you somehow.
