### ISSUE TITLE
Layers panel and canvas frozen after remove unsharp mask smart filter with drag n drop

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#560]
A photo is added unsharp mask, then remove with drag n drop to trash can (grab by the "smart filters" header with the mask icon, not the filter item itself), then the layers panel and canvas all freeze

**Comment by hgs54371** [comment]
Update, the whole app is basically not usable after remove a smart filter with drag n drop, not just layers panel

**Comment by hgs54371** [comment]
EDIT: before removing with drag n drop, I also click on the filter mask, use cmd-i to invert it(which only invert the icon itself but not the effects), the two issue seems related

**Comment by photopea** [comment]
It should be fixed now. Can you try it again?
