### ISSUE TITLE
ctrl not working

### ISSUE THREAD

**Issue by nghfk** [photopea/photopea#5600]
when ever I try you use a short-cut that involves using ctrl+z) it does not give time for me to press the second key it automatically registers it as just pressing ctrl and thus changing layers order instead of the desired command

**Comment by nghfk** [comment]
actually, this problem only happens with the  ctrl+z command

**Comment by camoody1** [comment]
Pressing CTRL by itself doesn't change the order of layers. Moving layers requires CTRL+[ or CTRL+]. It sounds like you've got a stuck key on your keyboard.

**Comment by photopea** [comment]
There used to be a bug like this in Firefox. Did you update your web browser in the past five years?

Could you tell us, what operating system and what web browser do you use, and what should we do after opening www.Photopea.com to see the problem happen?

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by lazarljubenovic** [comment]
This is happening to me, too. I'm on Ubuntu 20. It happens on both Chrome and Firefox, latest versions. On both browsers, the **left** CTRL key seems to be completely ignored, and just the second keystroke gets applied. CTRL-Z selects the zoom tool the moment I press Z. When I try to deselect the selection with CTRL-D, nothing happens, since D does nothing in that context. Feel free to ask for more details or if you want me to perform a specific series of actions.

(I assure you that the key is otherwise working normally and that it's not a hardware defect 😄)

**Comment by camoody1** [comment]
@lazarljubenovic Youre describing a totally different issue from what the original post claimed. You should open a new separate ticket.

**Comment by photopea** [comment]
Hi, could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

Could you open this, click into the white area and press keys? It should always show the keys that are pressed. Can it detect your Ctrl? https://jsfiddle.net/p45f44zb/14/

**Comment by lazarljubenovic** [comment]
@camoody1 Ah, I see now that I've read it more carefully. You're right, it's a different issue.

@photopea Woah, it doesn't register the left CTRL at all. Same [at keycode.info](https://www.toptal.com/developers/keycode). It never occurred to me that it could be a system-wide thing.

I'll fiddle around to see what could be causing this, but it's super weird: both Chrome and Firefox exhibit the same behavior, with all extensions disabled, incognito, etc. The key is working fine when handled by the OS (e.g. CTRL + arrows for moving around text in this textbox), but it doesn't get registered in JavaScript at all (e.g. I've opened dev tools and added `document.addEventListener('keypress', console.log)`, and the same for `'keydown'` and `'keyup'`, and nothing gets logged only for the left CTRL).

Rabbit hole, here I come! Thanks for the reality check. If you have any idea on where to start debugging this from, I'm all ears.

**Comment by photopea** [comment]
I am glad you solved it! You could try to report this to Ubuntu.

So just to clarify it if somebody finds this by searching the internet:

### A Ctrl Key in Photopea (and other websites) is not working on Ubuntu, if you enable "Locate Pointer" setting.

**Comment by itsankitbhusal** [comment]
> @camoody1 Ah, I see now that I've read it more carefully. You're right, it's a different issue.
> 
> @photopea Woah, it doesn't register the left CTRL at all. Same [at keycode.info](https://www.toptal.com/developers/keycode). It never occurred to me that it could be a system-wide thing.
> 
> I'll fiddle around to see what could be causing this, but it's super weird: both Chrome and Firefox exhibit the same behavior, with all extensions disabled, incognito, etc. The key is working fine when handled by the OS (e.g. CTRL + arrows for moving around text in this textbox), but it doesn't get registered in JavaScript at all (e.g. I've opened dev tools and added `document.addEventListener('keypress', console.log)`, and the same for `'keydown'` and `'keyup'`, and nothing gets logged only for the left CTRL).
> 
> Rabbit hole, here I come! Thanks for the reality check. If you have any idea on where to start debugging this from, I'm all ears.
> 
> EDIT:
> 
> * I've tried changing keyboard layouts from the OS, no luck.
> * I've noticed that the left CTRL gets recognized when I combine it with other keys. For example, if I hold down Right CTRL, and then press Left CTRL, I see the Left CTRL getting recognized.
> * The "trigger key" doesn't even have to be a modifier. If I hold down a key like "A", and then press "A" while holding it down, I see `ctrlKey: true` in the event (plus it gets properly recognized as a browser shell instruction to "select all").
> 
> EDIT 2: OH GOD I FOUND IT! I have a "Locate Pointer" accessibility setting turned on, which shows a pulsing circle around the cursor when you press left CTRL. Normally, it doesn't interfere with anything, but apparently there's something about how the even gets passed to JavaScript API that makes it pass undetected. Looks like it's a [weird issue](https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/1872230) with all sorts of things contributing to it happening.
> 
> That was a fun ride! Thanks again for the reality check 🙏🏻

Thank you brother, I also have same problem in pop os 22.04 and disabling the locate pointer does the job ✅
