### ISSUE TITLE
Letters "doubling" up when typing on a path 

### ISSUE THREAD

**Issue by ShawnyP3** [photopea/photopea#5602]
I'm typing on a rounded path. The first and last letters seem to have additional body added to the characters. Almost as if the letter is doubling up and overlapping a bit. 

Hard to describe but see the image attached. (I added a stroke so it could be seen easier)[](url)
![Photopea_J_Issue_1](https://user-images.githubusercontent.com/132779566/236640557-34e8cabd-f0c5-4bf6-93d5-d0cf3e917f00.png)

**Comment by camoody1** [comment]
What font is this? Does it happen with other fonts, too?

**Comment by ShawnyP3** [comment]
I can confirm when I get home but I think it’s OpenSans.

It does happen with other fonts too. It just seems to be happening on the first and last characters. It’s strange.

Let me know if I can help with any other info.

Sent from my iPhone

On May 6, 2023, at 4:09 PM, 97Buckeye ***@***.***> wrote:

﻿

What font is this? Does it happen with other fonts, too?

**Comment by camoody1** [comment]
This is what OpenSans Bold looks like on my device. My "J" looks nothing like yours, so it must be a different font.
![SmartSelect_20230506_175138_Edge](https://user-images.githubusercontent.com/73725653/236647967-b0b4a03a-12e1-4327-9432-992be94d12c5.jpg)

Let us know what you have whenever you get home.

**Comment by photopea** [comment]
It should be fixed now (or at least look much better now).

**Comment by ShawnyP3** [comment]
That’s incredible. It looks like it’s fixed.

Really appreciate it and that quickness and resolve was very unexpected.

Props to you for real.

Sent from my iPhone

On May 6, 2023, at 6:37 PM, Photopea ***@***.***> wrote:

﻿

It should be fixed now (or at least look much better now).
