### ISSUE TITLE
copy and paste not working

### ISSUE THREAD

**Issue by Michealwashere12** [photopea/photopea#5603]

**Comment by camoody1** [comment]
Copy/Paste is definitely working in the app. I've been using it all day. Perhaps you have a browser extension causing you issues? Assuming you're using Chrome, try opening Photopea in Incognito Mode to see if that helps. If that doesn't fix anything, perhaps record a short video to YouTube and post a link to it here so we can see exactly what is happening.

**Comment by photopea** [comment]
How do you copy and paste? What kind of a device and a web browser do you use?

**Comment by photopea** [comment]
I have to close it because of lack of details.
