### ISSUE TITLE
[iOS] Unable to open Drive subfolders

### ISSUE THREAD

**Issue by dbulawa** [photopea/photopea#5604]
Adding the website as a faux app using iOS Safari (Share -> Add to Home Screen), I am no longer able to open any subfolders in my Google Drive storage (using it in Safari itself, it works without a problem).

**Comment by photopea** [comment]
I am afraid it is a bug in Safari :( Could you update your iOS? Or try it in Chrome?

**Comment by dbulawa** [comment]
It works fine in the browser(s) themselves, only when pinned to the home screen via Safari (which is not possible via Chrome) it doesn’t. Will check again with coming iOS updates, if Apple fixes it. Thank you.

**Comment by photopea** [comment]
I think you need to log in to Google to use it, which needs opening another window, which could be impossible in the "homescreen icon mode". But maybe, if you log in in a browser, you can stay logged in in the installed mode.

**Comment by dbulawa** [comment]
Login also works fine, but it only shows me the top level and I cannot open any folder. I guess as a workaround I can just put my current work files in the main directory.

**Comment by dbulawa** [comment]
It just worked to open a folder!?! Closed the app and opened it again, and it didn’t work again 😵‍💫 done nothing different than before (pretty sure it is a Safari issue, though)
