### ISSUE TITLE
Site breaks Chrome Window Traversal Shortcut

### ISSUE THREAD

**Issue by podme** [photopea/photopea#5605]
On Chrome on Mac I need to do 

Cmnd+Shift+´ 

in order to swap browser windows. However, if I have photopea open, it interrupts this flow. Is this really necessary?

**Comment by photopea** [comment]
Which key exactly is "´"? I am trying to find a shortcut which you mean (in Chrome on Windows), but no shortcut does that.

BTW. you can always click into the text area of your browesr that contains the URL, and no Photopea shortcuts will work. E.g. Ctrl+S will save a website (a HTML file) to your computer.

**Comment by podme** [comment]
I'm on a German keyboard, but it's the one to the left of backspace, I believe it's = and + in US keyboards. Learn more here : https://zapier.com/blog/alt-tab-on-mac/
Actually that shortcut used to work for me, then weirdly I needed to add a shift to get it to work... I guess it's probably an edge case so I wouldn't worry about it

**Comment by photopea** [comment]
So it is not a Chrome shortcut, but a Mac shortcut? 

I can not find a character "´" anywhere in the text at your link.

**Comment by podme** [comment]
In the article it's command + `

That character shares a button with ´ on german macs.

**Comment by photopea** [comment]
I do have a Macbook with Safari, I would really like to fix it! But I can not find the shortcut (I can send you a photo of my keyboard, but I dont think you have a key which I dont have - I think I have tried them all).

So if you go to some website (not Photopea - tell me which one) in Google Chrome, and you press what exactly on your keyboard, what exactly happens? I will make sure that it works the same in Photopea, too.
