### ISSUE TITLE
Photopea crashing everytime I open it

### ISSUE THREAD

**Issue by GabrielJesusIsMyPastor** [photopea/photopea#5606]
The issue is hard to explain so bare me with me, when I open Photopea everything is running fine but for some reason after 30 seconds, previous projects that I had closed come up and crash the website. It doesn't matter how many times I close these projects, they, without fail, come up again, crashing Photopea.

Is there any way to fix this issue? Is it a bug? Any help is greatly appreciated.

**Comment by Pt-home** [comment]
Hi! Can you try opening Photopea in your browser's private mode? Will your problem continue to appear?

**Comment by photopea** [comment]
Some of your browser extensions are breaking Photopea.

In a browser with no extensions do this:

- open www.Photopea.com 
- if old projects appear, close them
- close www.Photopea.com 

Now, the "old projects" should never appear again.
