### ISSUE TITLE
Graphic going transparent when i use create smart object

### ISSUE THREAD

**Issue by fohrbz** [photopea/photopea#5608]
Every time i go to use the create smart object thingy, the entire graphic turns transparent :(

**Comment by camoody1** [comment]
Could you please record a short video of exactly what you're doing when this occurs? Drop a link to the video here. Smart objects definitely work in Photopea, so I'm not exactly sure what you're doing.

**Comment by photopea** [comment]
We changed the rendering of smart objects yesterday, so I believe you!

I just made an empty layer, painted something on it, right-click it, Convert to Smart Object, but it is not transparent. So what did you do?

**Comment by photopea** [comment]
I think it should be fixed now, could you try it again?
