### ISSUE TITLE
Use the New AI Healing Tool as a More Powerful Inpainting Tool

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5609]
Referencing ticket #5516

The current Text-to-Image Inpaint tool is lacking. I have tried to use it many times and came away feeling unimpressed. However, the new AI Spot Healing Tool is absolutely a game changer. I have been playing around with it today and have made amazing changes to images. It's really great. The only downside to the current tool is that we don't get to tell the AI what we actually want to put into the healing area. For a Spot Heal/Remove Tool, it works great. I can remove people or objects from images and the AI does an amazing job. But, if I'm reading the Dezgo API documentaion correctly, we SHOULD be able to do the same process but also provide the tool with a text description of exactly what we want to see in that healed area.

For example, I was messing with an image of a person who was holding a cell phone in front of her face. When I used the AI Spot Healing Tool to remove the cell phone, it would randomly choose what to replace it with. Sometimes, it chose an empty hand. Sometimes it chose a bouquet of flowers.  Since we're not passing a text description through the API of what we actually want, this makes sense. The AI tool is just picking whatever fits. But how much more powerful would it be if you gave us a dedicated Inpainting Tool that used the exact same API call, but also allowed us to type in a text description, like, "woman holding cup of coffee" or "woman holding glass of beer" or "woman holding a cigarette". That would be AWESOMELY powerful and exactly what I've been asking about for the last several months. If you enacted such a tool, you could remove the "inpaint" option you have in your current Text-to-Image tool. This new tool seems to handle it much better.

**Comment by camoody1** [comment]
Additionally, and you mentioned this in an earlier ticket, it would be great for both the new AI Spot Healing Tool and this new Inpainting Tool if you allowed the use of a "painting" style selection instead of actually having to use a selection tool before switching to the Spot Healing Tool. The current process is just a bit disjointed.

**Comment by photopea** [comment]
Let's discuss it in the old thread.
