### ISSUE TITLE
Different Browser, Same SHIFT Issue

### ISSUE THREAD

**Issue by Nitr0h** [photopea/photopea#5610]
Browser: Ungoogled-Chromium

For some reason, even on a different browser (last time I was using Firefox), Photopea randomly decides that I'm holding SHIFT forever when I'm not. This time I show with a keyboard test site that I'm not holding anything.

https://user-images.githubusercontent.com/91281667/236732924-32e9b506-4aa9-402f-a7ee-ebc9b52e6bc8.mp4

**Comment by photopea** [comment]
I do have a macbook with Safari to test it out! But it never happened to me.

Could you write a list of steps, what should I do to see it happen? E.g.

1) Open www.Photopea.com 
2) Open any JPG file in it
3) ....

**Comment by Nitr0h** [comment]
1. Create a 1920x1080 Project
2. Copy an image from the internet
3. Paste
4. Any button you press pastes it again?
5. Anything you do makes it seem like you're holding SHIFT, making it do something else?

**Comment by photopea** [comment]
I just tried it on my macbook, but I can not make it happen :(

Before your five steps, did you open a "fresh" www.Photopea.com, or you have already been using it for an hour and did your steps with it?

I need you to describe what you did from the moment of opening www.Photopea.com . Maybe record a video of opening www.Photopea.com and what you do next.

**Comment by photopea** [comment]
Could you update your MacOS? Do you use any browser extensions or a software which interferes with a keyboard?

**Comment by Nitr0h** [comment]
Nope.
________________________________

**Comment by camoody1** [comment]
Have you tried running your keyboard through a dishwasher cycle to get rid of any sticky dirt that could be causing your SHIFT key issues?

**Comment by photopea** [comment]
I think I give up. 

We have tens of thousands of Mac users using Photopea every day. I am 100% sure the issue is with your computer (and we can not fix it by modifying Photopea). I still want to help you somehow (e.g. tell you to change some Mac settings).

Did you try to reboot your computer? Could you try to disable all your extensions? Could you record a video of opening Photopea.com and the bug happening?
