### ISSUE TITLE
Again scripts: Spt, SprS and... fillOpacity

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5611]
Hi!
Problem 1. No work executeAction-based scripts:
For Spt     : [https://photopeaactionslib.olegpustovoit.repl.co/scriptSpt.jsx](url)
For SprS   : [https://photopeaactionslib.olegpustovoit.repl.co/scriptSprS.jsx](url)

Problem 2. No work trivial one-row-script:
`app.activeDocument.activeLayer.fillOpacity = 50;`

With hope and eternal gratitude...

**Comment by photopea** [comment]
all fixed! :)

**Comment by Pt-home** [comment]
Sincere gratitude and mutual congratulations - now you can say that ALL elements Filter Gallery can be launched by a script through the executeAction!
