### ISSUE TITLE
Crashing and then all images are gone and all work I've done it no longer 

### ISSUE THREAD

**Issue by BrendenJohns** [photopea/photopea#5613]
ever time for the last few weeks I've been creating football kits on Photopea whether it online or downloaded onto my desktop Photopea crashing and says disabling WebGP  (I haven't clicked on anything to disable it) and all my tabs are no longer there to be seen (it can be only one tab or multiple tabs, it happen every time)

does anyone know why this is happening? because I've been using photopea for a while and it never done this before until about 2 weeks ago and now it happens every time I use it

I really enjoy using Photopea and want to fix it some I can keep using it

![Untitled](https://user-images.githubusercontent.com/132944550/236911788-192de94e-ab35-40a4-b671-fce8b1ae698d.png)

**Comment by photopea** [comment]
It never happened to me. Maybe your computer ran out of RAM memory.

Photopea disables WebGL when your file is too large for your GPU to handle (e.g. 20,000 x 20,000 pixels = 400 million pixels).

What is the regular resolution of your documents (width and height in pixels) and how much RAM memory do you have?

**Comment by photopea** [comment]
BTW. even if the preview disappears, you should still be able to save your work (File - Save as PSD).

**Comment by BrendenJohns** [comment]
16GB RAM and its ACER Gaming laptop as well  why would it only just start to crash though it's never happened before but until about 2 weeks ago when it started to happen?

**Comment by BrendenJohns** [comment]
16GB RAM and its ACER Gaming laptop as well why would it only just start to crash though it's never happened before but until about 2 weeks ago when it started to happen?

**Comment by lxryn** [comment]
the same thing is happening to me and they said the same

**Comment by camoody1** [comment]
This only happens to me, as you said, when I have a very large image open or a bunch of tabs open. I have 8GBs of VRAM on my GPU and 32GB of RAM on my PC. When this happens to me, I try to close a couple of tabs that I have already saved to free up memory or just save the large document and then reopen it.

I would prefer that it didn't happen, but I can't change the limitations of the technology, unfortunately.

**Comment by lxryn** [comment]
<img width="1280" alt="Screenshot 2023-05-08 at 8 46 35 PM" src="https://user-images.githubusercontent.com/132114446/236973338-f41209a8-fe3e-4783-9d6b-2e4600c4afb7.png">

this is my current situation and sometimes this doesn't even pop up. it's a blank grey screen. And I can't even do anything with it. I have nothing open but these two tabs.

**Comment by lxryn** [comment]
<img width="1280" alt="Screenshot 2023-05-08 at 8 49 45 PM" src="https://user-images.githubusercontent.com/132114446/236973687-32a91f9d-f7e7-46df-ac26-bb91be3d9dad.png">
this gray screen

**Comment by camoody1** [comment]
I see that the Account button is red which means you don't have a premium account, which is absolutely fine, but I also notice that you don't have any ads on the side of your Photopea window. This would lead me to think you might have a browser extension that has an ad blocker? And if you have a blocker extension, you may have others. I'm not a Safari user, so I could be completely off base here, but is there an option in that browser to run in a "private" or "in cognito" mode?

**Comment by photopea** [comment]
When Photopea crashes like that, could you press Window - More - Memory, and share a screenshot of how much memory your work uses?

**Comment by photopea** [comment]
@lxryn please stop spamming about your issue in other issues. You already have an issue. Just wait for our reply.

**Comment by BrendenJohns** [comment]
> When Photopea crashes like that, could you press Window - More - Memory, and share a screenshot of how much memory your work uses?

![image](https://github.com/photopea/photopea/assets/132944550/24e2f1f6-1508-4f4f-b554-3845f0030fe1)
I've just done what you asked and this is what comes up

**Comment by photopea** [comment]
Can you make it happen while using www.Photopea.com in the incognito window of a web browser? I think your browser extensions could be breaking Photopea.

**Comment by BrendenJohns** [comment]
I've put it on my desktop as it was crashing on web browser but it still happens

**Comment by photopea** [comment]
But does it crash in the Incognito mode, when your browser extensions are disabled?

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by camoody1** [comment]
@BrendenJohns Could you maybe share one of your projects that isn't working for you here on this ticket? Perhaps @photopea could try opening it to see if the problem affects them, too.
