### ISSUE TITLE
Did you plan on doing this?

### ISSUE THREAD

**Issue by SwollenBaker** [photopea/photopea#5614]
I was trying to make a photoshopped image. I was trying to use another photo by dragging the image to the editor. Once I dragged an image into the editor, it creates the same image by itself. I swore I dragged the image once. Is this an intentional thing that you planned on doing, or is it simply a glitch? If it's a glitch, please fix it. Thanks.

**Comment by camoody1** [comment]
It's not clear to me what you're actually saying is happening. When you drag an image into Photopea, is it making two copies of the image? Is that what you're saying? Were you dragging the new image on top of an existing image in a project? Or were you dragging the image onto the Photopea blank project area to start a new project with that image?

**Comment by photopea** [comment]
Nobody else reported such a problem. Could you share a video or at least a screenshot of what is happening?

Also, try this and then see if the problem still happens: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
