### ISSUE TITLE
photopea is broken

### ISSUE THREAD

**Issue by lxryn** [photopea/photopea#5615]
<img width="1280" alt="Screenshot 2023-05-08 at 8 46 35 PM" src="https://user-images.githubusercontent.com/132114446/236973891-2a286934-3374-4190-81e9-70d97db11575.png">
<img width="1280" alt="Screenshot 2023-05-08 at 8 51 48 PM" src="https://user-images.githubusercontent.com/132114446/236973920-3b4dd675-36bc-439c-83ff-f8b73fb40f81.png">

I can't do anything. it acts like it wants to work but it just stays exactly like that

**Comment by camoody1** [comment]
Just to be clear, Photopea definitely isn't "broken". There are thousands and thousands of other people using it, currently. If it were "broken", there would be posts all over Reddit and here in GitHub. This definitely seems to be an issue with your personal setup. Hopefully, Ivan can help you find a remedy. Have you tried opening Photopea in a private or "in cognito" browser window?
