### ISSUE TITLE
Include scripts problem (and some little questions)

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5616]
Hi! 
In first, as said  Oscar Wilde: «Please do not shoot the pianist. He is doing his best» :) ...

**Problem 1**:
I have two trivial scripts in two saved files (as example):

_script_lib.jsx_
`var work_layer = app.activeDocument.activeLayer;`

_script_action.jsx_
`#include "script_lib.jsx"`
`work_layer.opacity = 50;`

In PS, of course, its correctly... 
**And very-very-very want it to work in Fotopea...**
At the same time, I understand, what Photopea saves scripts in a Local Storage not as file... But very-very-very want...

Because, quote motivates for me :)
«Instead of describing a new Document model, Photopea provides an interface similar to Adobe's scripting interface. It means, that the same scripts, that you wrote previously for Adobe Photoshop, could be used in Photopea to do the same task»    

**Question 1**
If I see in pp.js same code:
` ...... = "activeDocument documents fonts preferences displayDialogs foregroundColor backgroundColor version";`
` ...... = "charIDToTypeID stringIDToTypeID typeIDToStringID executeAction executeActionGet doAction showWindow UnitValue" `
then you can focus on it as currently available methods and functions from the Photopea Application?

**Question 2**
On my amateur opinion, doAction in PS looks like some kind of function "torn off from the model". In theory, it is possible to read the list of saved custom Actions in Photopea for its scripted use (compatible with the execution of the same script correctly in PS)?

Thanks!

**Comment by photopea** [comment]
Hey! :)

The "include": basically, a website can not just look at your hard drive and load a specific file, websites dont have such permissions. So I dont think it can be done. Maybe we could make a special form, where you choose the main JSX file and additional JSX files, which need to be included.

Question 2: I dont know what you mean, but if you have a script or an action which works in Photoshop but does not in Photopea, let us know (rather than adapting your code to Photopea).

**Comment by Pt-home** [comment]
Arrange any solution that is convenient for you to implement :)

There are many options (for example, just above the window for the current script is a text field, where, if necessary, the names of already saved JSIx scripts are indicated, separated by commas, in the order of inclusion) ...
All the same, such a service is supposed to be for those who understand programming a little, we’ll figure it out somehow;)

**Comment by photopea** [comment]
Ok, I have implemented it. Note, that "include" works recursively, so be sure not to make a loop with it :D

JSX files are stored in the Edit - Local Storage, and also visible at the bottom of the Script window. When you drag-and-drop a JSX file into Photopea, we will offer you to save that file to a local storage.

**Comment by Pt-home** [comment]
Wow, that's good, we'll try it, thanks!

**Comment by Pt-home** [comment]
![Worked](https://github.com/photopea/photopea/assets/29394245/09643fe5-f225-46c2-a402-138399ee4571)
Example how its easy and сomfortable now! Thanks!
