### ISSUE TITLE
Feature Request: Make the "Alt+click" Eyedropper look the same as the Eyedropper Tool

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5617]
Hopefully, a simple request...

When you use the Eyedropper Tool and click on an area of the image to select a color, there is a pop up "color ring" on the screen at your cursor point that shows you the new color details as well as a comparison between the old and new colors. This is great. However, when you're using the Brush tool, for instance, and you press the Alt key on your keyboard to use a shortcut to the Eyedropper, no "color ring" pops up at your cursor point. Instead, you just get a "plus sign".

It would be great if... 
1. Instead of the "plus sign", you actually popped up an image of an eyedropper (to let you know what function you're about to perform).
... and ... 
2. You popped up the same "color ring" gui that the full Eyedropper tool utilizes. These changes would better match Photoshop as well as just making the eyedropper experience more uniform.

**Comment by photopea** [comment]
I have implemented it. It works for the Brush tool and the Pencil tool.

So technically, if the Brush tool had any shortcuts involving Alt, they can not be used anymore (I hope there were none).

**Comment by photopea** [comment]
It turned out to be a problem here, so I took it back: https://github.com/photopea/photopea/issues/5627

**Comment by camoody1** [comment]
Wait... The Alt-Left Click has always worked fine to call the Eyedropper Tool. It just never showed the Eyedropper color ring. The issue on the other ticket was about Alt-Right Click. The two functions should be able to happily coexist, yes?

**Comment by photopea** [comment]
I have implemented it correctly this time. It should work for the Brush tool, Pencil tool, Color Replace tool, Background Erase tool, and the Paint Bucket tool.

**Comment by camoody1** [comment]
Thank you, sir!
