### ISSUE TITLE
so anyone wanna  tell me why its not loading my photos and only showing half

### ISSUE THREAD

**Issue by richgirl44** [photopea/photopea#5618]
![SharedScreenshot](https://github.com/photopea/photopea/assets/133017726/801cea63-19c5-4623-bba7-7fb098c696d5)

**Comment by photopea** [comment]
What is the size of your photos? Can you press Image - Image Size?

**Comment by camoody1** [comment]
Have you tried opening your image in Incognito Mode? It looks like you have an ad blocker, so maybe there is some other browser extension causing you issues?

**Comment by richgirl44** [comment]
> What is the size of your photos? Can you press Image - Image Size?
its 67mbs

**Comment by richgirl44** [comment]
> Have you tried opening your image in Incognito Mode? It looks like you have an ad blocker, so maybe there is some other browser extension causing you issues?

ive tried every method imaginable including the ad blocker and incognito mode but I've been told to compress it so im trynna see if that'll work

**Comment by richgirl44** [comment]
> I think there is a bug with your computer (the GPU). If your image exceeds a specific size (8192 or 16384 pixels), the part outside this limit will not be displayed.
> 
> You can disable the GPU acceleration in More - Use WebGL.

this actually worked thank you!!

**Comment by photopea** [comment]
I recommend fixing your computer somehow, because Photopea will be very laggy without the WebGL.
