### ISSUE TITLE
The new 'Remove with AI' tool.

### ISSUE THREAD

**Issue by bluep55** [photopea/photopea#5619]
Hi. I've been experimenting with the new 'Remove with AI' tool but have been getting some weird results.
Should it behave like the 'Heal' tool ( or Content Aware Fill )?
Occasionally it does what I thought it would do and removes the item I have selected with the appropriate background, but usually it replaces the object I've selected with random objects.
A couple of examples here:

![House to motorcycle](https://github.com/photopea/photopea/assets/118609932/03cef52a-f7b3-4092-8f52-e1a5ad7f82ac)

![Pugs](https://github.com/photopea/photopea/assets/118609932/ffa6e755-eabf-44c2-9938-95223888c0d1)

**Comment by photopea** [comment]
What if you select someones head and press "Remove"? Do you want to get a different head, or you want the person to have no head?

**Comment by bluep55** [comment]
If I pressed 'Remove' I'd want the object replaced with something similar and appropriate, not a house and trees replaced by a large motorcycle 😄, and a little Pug dog that's been replaced by what looks like a small plant pot 😂.

**Comment by photopea** [comment]
Lets discuss it in the original issue https://github.com/photopea/photopea/issues/5516

**Comment by photopea** [comment]
I deleted everything and added a new tool: "Magic Remove", it is below the Healing Brush tool.

Basically, it is a Lasso, with a "Remove" button at the top. You can also specify the new content of the area with a text description. It can handle areas of up to 1 million pixels now (e.g. 1000x1000).

@bluep55 I have entered "empty meadow" and it worked quite well
![image (4)](https://github.com/photopea/photopea/assets/15955558/6033e471-4ece-47ee-ae8d-851a3414c4f2)
