### ISSUE TITLE
Opt/alt-click new layer icon to create new fill layers

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#562]
There needs to be a simpler way to create fill layers(solid color/gradient/pattern) other than the top menu, either besides the adjustment layer icon or through opt/alt click the new layer icon at bottom right

**Comment by photopea** [comment]
In Photoshop, if you Alt-click the New Layer, you still have to choose many parameters in the New Layer window.  If you press Layer - New Fill Layer - Gradient, you can immediately choose a gradient in the Properties.

**Comment by hgs54371** [comment]
It's not the dialing-in the parameters that's cumbersome, 
It's the process of going from bottom right layers panel to top left menu - Layer - New Fill Layer - solid color fill, especially if you need multiples of them at a time, the creation of adjustment layers are already in layers panel, why not also fill layers ? Aren't they related in this context ?
