### ISSUE TITLE
Batch Automation tool not working

### ISSUE THREAD

**Issue by abhimanyu-gzp** [photopea/photopea#5620]
Batch automation tool isn't showing any options for "Action Set" and "Action" dropdowns.
I'm using Chrome (v110) on a Macbook with MacOS Ventura 13.0.1.

<img width="334" alt="image" src="https://github.com/photopea/photopea/assets/95204426/dd12ebb7-ee35-4ea7-8286-ecae00eee104">

**Comment by photopea** [comment]
Did it ever work before for you? In other words, do you know how to use it? You should create actions in Window-Actions first, or load the ATN file.

**Comment by photopea** [comment]
I have to close it because of lack of details.
