### ISSUE TITLE
Files coming up as empty

### ISSUE THREAD

**Issue by fohrbz** [photopea/photopea#5621]
so, i was literally using the same screencaps yesterday and today? they're coming up as empty files o bytes. and i know it's not my files because they're working perfectly on tumblr, and other places.  it's even doing it when i go to put in the screencap url. i tried it that way as well. 
![Screenshot 2023-05-10 7 34 04 AM](https://github.com/photopea/photopea/assets/113613369/1f97fdc6-7b4c-4fdc-9f2b-0273275f463d)

**Comment by fohrbz** [comment]
ignore the psd files. as that loaded perfectly. it's just uploading screencaps from urls that were just working yesterday perfectly.

**Comment by camoody1** [comment]
Can you give us a url that is no longer working for you?

**Comment by fohrbz** [comment]
Yeah! Of course! Try https://nina-dobrev.us/photos/albums/vampire%20diaries/season%204/Captures/418/TVD_018.JPG

**Comment by fohrbz** [comment]
okie, so weird but it just loaded! i think it might have been my computer? or a small bug that decided to mess up for a moment. I restarted my laptop just a few mins ago and yeah, it loaded right on up. so sorry about that!

**Comment by photopea** [comment]
Seems like it is solved, so I will close it.

**Comment by photopea** [comment]
Thank you @camoody1! :)
