### ISSUE TITLE
Ads on photopea pause videos from other places like chrome

### ISSUE THREAD

**Issue by MesaBlack** [photopea/photopea#5623]
I tried multitasking by watching a video and using photopea, when the ads started playing, pausing the video.
Any way to fix this?

**Comment by photopea** [comment]
A website definitely can not influence another website, that would be a bug in a browser.

Are you playing videos on youtube? Maybe it simply pauses when the video is not in focus (not related to Photopea).

**Comment by MesaBlack** [comment]
on a streaming service, paramount plus, and on youtube.
And the video pauses when an ad starts playing.
Which is also the case on the installed version.

**Comment by photopea** [comment]
What should I do to see it happen? What website should I open? I would like to see it myself.

It is not clear what do you mean by "ad playing in Photopea", do you mean like a video on the right side?

Could you try this first? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

Also, is it on a phone or on a desktop?

**Comment by MesaBlack** [comment]
open youtube and/or any streamer
yes, video on right side
and desktop

**Comment by photopea** [comment]
I just opened youtube and played a video, and then, opened Photopea.

Youtube video kept playing with a sound. There was one ad in Photopea playing a video with no sound. The ad had a button to unmute, when I clicked it, I could hear the sound of the ad (and the Youtube video kept playing).

Are you 100% positive, that it still happens when you do it all in the Incognito mode (i.e. with no browser extensions)?

**Comment by MesaBlack** [comment]
this would apply to paramount plus, at least in the us, is it in your country?

**Comment by photopea** [comment]
I need some proof that your problem is related to Photopea.

Can you open some other website instead of Photopea.com , does your Paramount keep playing?

Also, what web browser and what operating system do you have?

**Comment by MesaBlack** [comment]
The episode pauses when an ad, even the silent ones, start playing

**Comment by photopea** [comment]
What if you use Photopea at www.Photopea.com ?

Does it also happen when you play Youtube instead of Paramount?

**Comment by MesaBlack** [comment]
I'll see

**Comment by photopea** [comment]
I have to close it because of lack of details :(
