### ISSUE TITLE
Again scripts: Dstt and ClrB

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5624]
Hi! 
**Problem 1:**
var idDstt = charIDToTypeID( "Dstt" );
executeAction( idDstt, undefined, DialogModes.NO );

**Problem 2:**
var idClrB = charIDToTypeID( "ClrB" );
    var desc354 = new ActionDescriptor();
    var idShdL = charIDToTypeID( "ShdL" );
        var list7 = new ActionList();
        list7.putInteger( 0 );
        list7.putInteger( 0 );
        list7.putInteger( 0 );
    desc354.putList( idShdL, list7 );
    var idMdtL = charIDToTypeID( "MdtL" );
        var list8 = new ActionList();
        list8.putInteger( -64 );
        list8.putInteger( 47 );
        list8.putInteger( -59 );
    desc354.putList( idMdtL, list8 );
    var idHghL = charIDToTypeID( "HghL" );
        var list9 = new ActionList();
        list9.putInteger( 0 );
        list9.putInteger( 0 );
        list9.putInteger( 0 );
    desc354.putList( idHghL, list9 );
    var idPrsL = charIDToTypeID( "PrsL" );
    desc354.putBoolean( idPrsL, false );
executeAction( idClrB, desc354, DialogModes.NO );

Thanks...

**Comment by photopea** [comment]
fixed! :)
