### ISSUE TITLE
Invert checkbox in RoughPastels and Underpaiting

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5625]
Hi!
**Problem:**
I am 99.99% sure that turning the inversion parameter on/off does not affect the result of the filters RoughPastels and Underpaiting in any way...
I checked it on three different images and three arbitrary sets of settings (one copy of the image was processed with inversion, the other - without it) Blend Mode Difference all three times gives a black surface, which means all the pixels of the copies are the same...

**Notes:** Glass. Conte Crayon and Texturizer with similar interface work correctly.

**Comment by photopea** [comment]
Hi, it is fixed now, thanks for reporting it! :)

**Comment by Pt-home** [comment]
Thanks you!
