### ISSUE TITLE
Photopea displaying white screen when opening.

### ISSUE THREAD

**Issue by HardcoreGamer66** [photopea/photopea#5628]
Photopea has been a photo editor that I have used since 2021. It has been really good and has a ton of great features. About 1 week ago, I tried to open up Photopea, but my browser displayed a white screen. I tried restarting my computer, force quitting my browser, and clearing cookies for Photopea. I use a MacOS computer, with Safari as my main browser. Can someone please. help? I have no idea what is happening, and want to continue using Photopea.

**Comment by camoody1** [comment]
@photopea Another Safari issue with blank screen. I wonder if the browser changed something to cause issues?

**Comment by photopea** [comment]
Hi, could you tell us the version of your Safari, and the version of your MacOS?

Also, could you try Photopea in some different web browser? Does it work differently?

**Comment by HardcoreGamer66** [comment]
I have a MacBook Pro as the computer I use. My version of Safari is MacOS Ventura 13.3.1. Photopea works completely fine in Chrome, but I use Chrome for schoolwork, and don't want to switch browsers constantly.

**Comment by photopea** [comment]
Could you record a short video of opening www.Photopea.com in Safari? I mean opening from nothing, not a video of when Photopea is already opened.

**Comment by HardcoreGamer66** [comment]
https://github.com/photopea/photopea/assets/119811205/c564a997-e975-4862-89f3-13ce4f66c42a

**Comment by photopea** [comment]
Thanks a lot!

In Safari, could you press File - New Private Window, and open Photopea.com in that private window? Does it work?

**Comment by photopea** [comment]
Also, when Photopea is not working (a white screen), could you right-click it - "Inspect Element", switch to "Console", and send us a screenshot of what you see there?

**Comment by HardcoreGamer66** [comment]
<img width="1431" alt="Screenshot 2023-05-18 at 6 38 31 PM" src="https://github.com/photopea/photopea/assets/119811205/b90ef1c2-9c1b-4dc4-99b1-da92aac15481">

**Comment by HardcoreGamer66** [comment]
it does not work in a private window

**Comment by photopea** [comment]
That is really really weird.

Could you right-click the white space and choose "Show Page Source", and send me a screenshot of what you see?

**Comment by HardcoreGamer66** [comment]
<img width="1431" alt="Screenshot 2023-05-18 at 8 06 10 PM" src="https://github.com/photopea/photopea/assets/119811205/c9f8243f-5d7b-4ac2-916a-aba52e2f2761">

**Comment by photopea** [comment]
Ok, that is even stranger. The source code is completely empty.

Can you open https://www.photopea.com/learn/ ?

Can you open https://www.photopea.com/promo/icon512.png ?

**Comment by HardcoreGamer66** [comment]
no

**Comment by photopea** [comment]
It seems like Safari extensions do run in the Private Window. Could you try to disable all your extensions? See https://www.techbout.com/youtube-not-opening-mac-safari-64394/#:~:text=3.%20Disable%20Safari%20Extensions

**Comment by HardcoreGamer66** [comment]
I tried clearing cache. I was able to enter in Photopea the first time, but the second time I had the same results as before.

**Comment by photopea** [comment]
And what about the browser extensions? Could you show us a list of your current extensions in Safari?

**Comment by HardcoreGamer66** [comment]
I don't have any

**Comment by HardcoreGamer66** [comment]
<img width="773" alt="Screenshot 2023-05-20 at 8 18 56 AM" src="https://github.com/photopea/photopea/assets/119811205/2eec47ed-4676-4081-94e9-d779dcc9f67a">

**Comment by photopea** [comment]
I give up then :( There are many other people who use Photopea in Safari without any problems. Also, I can not see such behaviour on any of my Apple devices. So it is hard to tell what is wrong in your case.

**Comment by ciinorl** [comment]
Hello, mine doesn work. i am in windows laptop and in my other google account it works but my main doesnt work

**Comment by photopea** [comment]
Did you try to turn off all your browser extensions, which have your permission to modify the code of Photopea?

**Comment by ciinorl** [comment]
everything from the photopea blog post

**Comment by ciinorl** [comment]
but in colsole it shows 2 errors

**Comment by ciinorl** [comment]
Uploading Screen Recording 2025-01-09 211017.mp4…

**Comment by ciinorl** [comment]
https://github.com/user-attachments/assets/d895f01f-c156-4bd8-aaea-a087b6436adf

**Comment by photopea** [comment]
Could you try to open Photopea in the Incognito mode?

**Comment by ciinorl** [comment]
it works

**Comment by photopea** [comment]
Could you try to clear the website data of Photopea? https://www.photopea.com/tuts/photopea-opens-up-old-files/#:~:text=Clearing%20Website%20Data

**Comment by ciinorl** [comment]
THANK YOU!!!

**Comment by cookiemm023-del** [comment]
Hi! I have a problem with this. This happened yesterday while i was trying to make a new profile picture. I couldn't fix it anymore.

<img width="1916" height="1079" alt="Image" src="https://github.com/user-attachments/assets/b67ef930-6bd8-4f08-95cd-75ee7497ef4b" />

**Comment by photopea** [comment]
Hi, try to clear the website data: https://www.photopea.com/tuts/photopea-opens-up-old-files/#:~:text=Clearing%20Website%20Data
