### ISSUE TITLE
(suggestion) Direct skew/slanting feature

### ISSUE THREAD

**Issue by MesaBlack** [photopea/photopea#5629]
I'm trying to slant an image, and a skew option could be helpful.

**Comment by MesaBlack** [comment]
nope nevermind, in free transform

**Comment by camoody1** [comment]
You can Skew an image in Photopea by selecting the Transform or Free Transform tool and then changing the "H" or "V" values in the top toolbar.

However, it might be nice to simply add "Skew" to the tools listed under Edit -> Transform like it is in Photoshop. Might make for a smoother transition for Photoshop users coming to Photopea.

**Comment by photopea** [comment]
I have implemented it under Edit - Transform - Skew.

The Free Transform behaves exactly like Skew (in Photoshop and Photopea) if you hold the Ctrl and Shift keys.

**Comment by camoody1** [comment]
When testing the new Skew Tool, I found a difference between how it works via Transform vs Free Transform.

Here is a video showing what I found.
https://youtu.be/u6CvzxOPToY

**Comment by photopea** [comment]
It should be fixed now.

Note, that the Skew does not work like the Free Transform with Ctrl, but as the Free Transfom with Ctrl AND Shift keys!

**Comment by camoody1** [comment]
Looks good. Thank you, sir.
