### ISSUE TITLE
More patterns to choose from in pattern fill

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#563]
The options are very limited right now, would be great to have those that found in photoshop

**Comment by photopea** [comment]
Could you suggest any specific "universal" patterns? Photoshop has a big database of patterns, but I am afraid they are copyright-protected. Do you know about any free, yet useful patterns?

**Comment by hgs54371** [comment]
Haven't seem to found something like google fonts but for patterns, but just like fonts, having the ability to import user patterns with drag n drop would be good, photoshop pattern format is .pat

**Comment by photopea** [comment]
Loading patterns with drag n drop has been possible for more than a year: https://blog.photopea.com/patterns-and-fill-layers.html :)
