### ISSUE TITLE
Scripts: Execute custom steps from Action

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5630]
Hi!
**Note:**
I don't know of a direct possibility to run ONLY one, specifically chosen, step from a set of commands pre-recorded in the Action. 
And this would be a useful feature for operations that are extremely difficult to describe ordinary user in script (the same Liquify, as example).

**Problem**
You have in Photopea Action Palette Action Set with name "A". In this Action Set you have Action with name "B". In "B" - several pre-recorded ANY commands (>=2). We want execute ONLY second command, as example, from "B".
**Problem script:**
[https://photopeaactionslib.olegpustovoit.repl.co/one_step.jsx](url)
The script now works confidently in Photoshop, but so far resists working in Photopea:)

I'm sure it's fixable :) Thanks in advance...

**Comment by photopea** [comment]
Fixed! :)

I had no idea such things are possible with scripts / actions in Photoshop.

**Comment by Pt-home** [comment]
Thanks!
And I'm still in shock that the paths can be saved PS in JPG for a long time :)

**Comment by photopea** [comment]
Any program can attach any additional data to a JPG file, but usually, only that program will understand these extra data. Regular programs will ignore these data :)
