### ISSUE TITLE
Revert

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5631]
Hi!
For a long time I wanted to know why there is no File-Revert function, familiar to emigrants from the Photoshop world in Photopea world:)?
It is very commonly used and required.

And his trivial PS script don't work too: 
var idRvrt = charIDToTypeID( "Rvrt" );
executeAction( idRvrt, undefined, DialogModes.NO );

Thanks...

**Comment by photopea** [comment]
Where can I find it in Adobe Photoshop? How do people use it in Photoshop, who do not know scripting?

**Comment by Pt-home** [comment]
In menu File:)
![image](https://github.com/photopea/photopea/assets/29394245/969a4dd8-f84c-4a6a-b266-ead647fbae3a)
And she was already in PS 7 minimum
![image](https://github.com/photopea/photopea/assets/29394245/149850cb-55d8-47c8-be36-07996bb2b18b)

**Comment by photopea** [comment]
I dont think anybody needs this option, as you can re-open the file from your computer. So I would rather not add it to Photopea.

You can run a script which perfoms a step back many times.
