### ISSUE TITLE
Filter: Stamp Filter makes image either completely black or white

### ISSUE THREAD

**Issue by QuantamHD** [photopea/photopea#5632]
Initial Photo:
<img width="1293" alt="image" src="https://github.com/photopea/photopea/assets/3784748/b32565be-9cf2-4e7b-a7a7-6a0279e56753">

Post Stamp: No matter the parameter change.

<img width="1465" alt="image" src="https://github.com/photopea/photopea/assets/3784748/7d5f568c-bba6-4adf-9447-8360dc53a830">

**Comment by photopea** [comment]
These filters combine your foreground and your background color (the colors at the bottom of a toolbar). Do you have both of them black?

**Comment by QuantamHD** [comment]
Ah I did that was the issue! Thanks for the fast response.
