### ISSUE TITLE
Constant crashing

### ISSUE THREAD

**Issue by heidiloux** [photopea/photopea#5634]
Hey,I’ve been trying to contact Photopea for a while now with no response from them. I’m trying to use mockup files with smart objects to place artwork in but Photopea either crashes when I try to open the file, when I try to save the smart object or when I try to save the file. It just takes me back to the homepage. Is there any fix for this? I’ve emailed them so many times and nobody has responded at all.

**Comment by photopea** [comment]
Please, tell us more about your device, and how large are your files in terms of Megabytes and pixels (width x height).

**Comment by heidiloux** [comment]
iPhone 13, I’ve sent this information beforeAnd nobody got back to me, it’s not just this one it’s loads of them. On 13 May 2023, at 10:13, Photopea ***@***.***> wrote:﻿
Please, tell us more about your device, and how large are your files in terms of Megabytes and pixels (width x height).

**Comment by photopea** [comment]
where did you send it?

Also, what is the size of your file in megabytes and pixels? Or could you share your file with us?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
