### ISSUE TITLE
Used control z once and it deleted most of my drawing

### ISSUE THREAD

**Issue by OrangeOutlier** [photopea/photopea#5635]
I can't even begin to say how frustrated I am rn after losing 3 hours of work to a simple undo. I feel dumb for not saving but this usually isn't a problem. I was setting up a new layer when I was hitting undo on a couple of drawings and then all of a sudden I saw the layer underneath was missing a big chunk save for roughly sketched feet I made and the tops of horns. Everything else related to the body was gone and I had no way of possibly getting it back. I don't even know what to begin to do with a problem like this but if there is any fix that'd be great.

**Comment by camoody1** [comment]
Did you try using the Step Forward under Edit? Or check the History window?

**Comment by OrangeOutlier** [comment]
I tried both and I was still left with nothing.

**Comment by FireTiger898** [comment]
I had a similar issue, like when I would press cmd z one time, it registered more than once on photopea (everywhere else is FINE) and it's really annoying for me to manually udo from the history window. :(

**Comment by photopea** [comment]
Guys, I really need to see this behaviour happen in Photopea myself. Could you tell me what should I do to see it happen?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
