### ISSUE TITLE
everytime I uploaded a new font and use it, it seems doubling. Default fonts on photopea are not doubling, it just doubling on all new added/uploaded fonts on photopea. It is not doubling on other editing softwares, only on photopea. Any help or suggestions to solve this issue?

### ISSUE THREAD

**Issue by sheng30** [photopea/photopea#5636]
![problem 2](https://github.com/photopea/photopea/assets/133554107/744b9414-7391-4425-b893-13091d063466)

![photopea issue](https://github.com/photopea/photopea/assets/133554107/0c6c8ab3-9aba-4ba0-bc2e-78777d199191)

**Comment by photopea** [comment]
Press Window - Character, and disable the "Faux Bold" option (the first icon at the bottom).
