### ISSUE TITLE
Feature Request: CTRL-ALT-SHIFT-T

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5637]
In Photoshop, CTRL-ALT-SHIFT-T will repeat the last paste and move that was just made of an image copy. In Photopea, this keystroke only makes a copy... it does not include the move.

Seeing a video of how it works in Photoshop is much better than my explanation...
https://youtube.com/shorts/9kcaqpIROsc?feature=share
... and here is a more in-depth example...
https://youtu.be/pSG2YAiS7oU

In Photopea, additional shapes are pasted as new layers, but they're all pasted on top of each other instead of being moved slightly to the right each time.

We had a request for this functionality on the Photopea Subreddit here... 
https://www.reddit.com/r/photopea/comments/13hkiqx/help_with_copy_and_paste/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

**Comment by photopea** [comment]
Alt+Ctrl+Shift+T in Photopea corresponds to Ctrl+Shift+T in Adobe Photoshop. They do the same thing in both.

Current web browsers do not allow us to use shortcuts like Ctrl+T and Ctrl+Shift+T.  So we implemnted them in Photopea by adding Alt to each of them.

Photoshop contains Alt+Ctrl+T and Alt+Ctrl+Shift+T shortcuts, and we do not have an analogy to them (as we already use these shortcuts for omething else).

Sure, we can make Alt+Ctrl+T and Alt+Ctrl+Shift+T in Photopea do the same thing as in Photoshop, but then, we need new shortcuts for  Ctrl+T and Ctrl+Shift+T (without Alt).
