### ISSUE TITLE
Small "undocumented" Photopea option

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5638]
Hi!
Intresting moment...
In menu "Select" in Photopea not useful options "All Layers" and "Deselect Layers".

But this script **FULL correct** in Photopea:

id = stringIDToTypeID( "selectAllLayers" );
var desc = new ActionDescriptor();     
executeAction( id, desc, DialogModes.NO );

Anouther script - "mysterious':

id = stringIDToTypeID( "selectNoLayers" );
var desc = new ActionDescriptor();     
executeAction( id, desc, DialogModes.NO );

Photopea get Alert: Unknown action "selectNoLayers" and... **really removes the selection from all layers!** :)

May be "All Layers" and "Deselect Layers" in fact easily added to the top menu, they just forgot about them? :)

**Comment by Pt-home** [comment]
In PS:
![image](https://github.com/photopea/photopea/assets/29394245/b72ac43a-119a-4c8a-8ca6-3d4c4ad9268d)

**Comment by photopea** [comment]
Sorry, I can not run your script in Adobe Photoshop :( it throws an error.

I can make the script work, but I dont think anybody needs this feature to be added into the menus.

**Comment by Pt-home** [comment]
So I wrote that the scripts WORK in Photopea now :) The question was about whether you see the point in adding them in menu. You answered it, and issue I think closed in fact...

**Comment by photopea** [comment]
ok
