### ISSUE TITLE
Photopea Changing Image Colors When Opened

### ISSUE THREAD

**Issue by pkragthorpe** [photopea/photopea#5639]
When I open an image in Photopea, the color automatically gets changed. See these 2 screenshots. One is after opening the image in Photopea, no adjustments made. The other is after opening the image in Photoshop, no adjustments made. The colors of the people in the screenshot of photoshop image are what they should be. The photopea one shows what's happening when I open photos in it. 

![photopea-photo-color](https://github.com/photopea/photopea/assets/54859848/6f2d60b8-9e38-4ba1-aafe-923e0dd365d3)
![photoshop-photo-color](https://github.com/photopea/photopea/assets/54859848/6cf67fc3-a78e-4c26-b555-be4830f97b97)

Seems like Photopea is applying some kind of filter or color changing without my input.

**Comment by photopea** [comment]
Hi, could you share your file with us?

**Comment by pkragthorpe** [comment]
I can't upload it here, it's over 10MB. But here's a link to it if that works

https://www.paulkragthorpe.com/images/Group%20Shot_05-03-2023%20Flat.jpg

Funny thing is, if I open it in Photoshop and just save it without changing anything, it'll save compress the file size a bit and then it'll load fine on Photopea. Just when it's the full image is when it has issues. Give it a whirl and let me know if you see the same.

**Comment by camoody1** [comment]
@pkragthorpe Wow. That image really DOES look different in Photopea. I wonder what's happening to the colors? Crazy.

**Comment by pkragthorpe** [comment]
@camoody1 oh good, so it's not just me!

**Comment by pkragthorpe** [comment]
@camoody1 Really?! That's very strange. I guess I don't know how to see paths cause I only see one layer in photoshop and photopea.

**Comment by MichalSZZ** [comment]
Paths stored in JPG are possible  for a long time. But I was also shocked when I opened a JPG files (that was 15 years ago) and saw product photo with background in JPG and paths to easy separate only the product and its parts (that was a notebook packshots).

**Comment by gse123** [comment]
Hi,

It's because the original image is in an RGB color profile that Photopea doesn't support - ProPhoto RGB. 

I've converted the file for you into a regular RGB profile that should display correctly in Photopea:

https://we.tl/t-kdjTAnJS1b

This link will expire in a few days, so download it when you can.

Thanks

**Comment by Pt-home** [comment]
> Paths stored in JPG are possible for a long time. But I was also shocked when I opened a JPG files (that was 15 years ago) and saw product photo with background in JPG and paths to easy separate only the product and its parts (that was a notebook packshots).

I could not even imagine that such a thing exists and for a long time

**Comment by photopea** [comment]
I am soo sorry guys, it is fixed now.
