### ISSUE TITLE
Ability to toggle visibility of the edges around the shape layer

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#564]
When adding strokes as layer style to shape layers, it's better to view them without the edges showing around it.

Photoshop put this among other similar items in "Extras" as a visibility toggle, along with grid and guides under "view"

From adobe help (https://helpx.adobe.com/photoshop/using/grid-guides.html)

Choose View > Extras. This command also shows or hides **layer edges**, **selection edges**, **target paths**, and **slices**.

**Comment by photopea** [comment]
Now, this can be changed in View - Paths.

**Comment by vindolin** [comment]
This still leaves the control points visible which is really distracting when working with layer effects.
Photoshop hides them too.

**Comment by photopea** [comment]
@vindolin Thanks, I fixed the problem with Dots visible, while Paths are disabled.

I also added the Extras switch, which disabless all extras (paths, grid, guides), switchable with Ctrl+H.
