### ISSUE TITLE
Everytime I export an image as PNG, it saves automatically on Downloads and I can't choose where to save it on my files

### ISSUE THREAD

**Issue by StevePensando** [photopea/photopea#5640]
How do I fix this?

**Comment by photopea** [comment]
This is completely under your browsers control, a website can not decide what happens to a downloaded file.

If you use Google Chrome, there is an option "Ask where to save each file before downloading" in settings. There is probably a similar option in other web browsers, too.

**Comment by StevePensando** [comment]
Ok, thank you
