### ISSUE TITLE
Feature request: Brush resize shortcut

### ISSUE THREAD

**Issue by gse123** [photopea/photopea#5641]
Hi, something that I miss every time I switch from Photoshop to Photopea is the ability to quickly change brush sizes by holding down ctrl + Alt key (on a mac) and scrubbing the curser left and right.. (with up and down adjusting the hardness/softness) 

Is there anyway that this could be considered in a future update, as it makes changing the brush size on the fly so much smoother than repeatingly tapping the bracket key, or right-clicking and moving a slider.

Thanks!

**Comment by camoody1** [comment]
This functionality already exists in Photopea. On a PC, you hold ALT while right-clicking and dragging the mouse left/right or up/down. I assume it works with the equivalent keystroke on a Mac.🤷🏽‍♂️

**Comment by photopea** [comment]
Hi, what is "scrubbing the curser left and right" ?

I tried to hold Ctrl+Alt in Adobe Photoshop and move my mouse (with and without clicking it), it does not change the brush.

I tried to hold Ctrl+Alt in Adobe Photoshop and press the cursor keys on a keyboard, it does not change the brush.

Are you sure you know how to use Adobe Photoshop?

**Comment by camoody1** [comment]
@photopea Maybe they had some other personal shortcut setup somehow. Or maybe it works differently on a Mac for some reason. 🤷🏽‍♂️

The way it works in Photopea is definitely how it works in Photoshop.

**Comment by gse123** [comment]
'Scrubbing' is the proper term for the motion of dragging the mouse curser back and forth to change a parameter.

On a Mac  it is  Ctrl + Alt + Hold Left mouse button (I forgot to mention this in the original post). The shortcut must be slightly different than on PC. 

And you could say I know Photoshop - I have been a full time commercial retoucher for 10 years using photoshop as my main tool every day (on a Mac) for even longer than that. So at this point It's safe to say that I am very familiar with it. 

So if you have any questions regarding real world Photoshop use, as a point of comparison to Photopea i'd be happy to help.

Thanks for all your hard work!

**Comment by gse123** [comment]
> @photopea Maybe they had some other personal shortcut setup somehow. Or maybe it works differently on a Mac for some reason. 🤷🏽‍♂️
> 
> The way it works in Photopea is definitely how it works in Photoshop.

It's one of the rare cases where a shortcut difference between the Mac and PC version of PS isn't just swapping the ctrl / command keys.

**Comment by photopea** [comment]
@gse123 Are you sure about it? Could you switch to Photoshop and try it right now?

I think, whenever you press Ctrl, Photoshop switches you "temporarily" to the Move tool, and all following mouse actions will be processed by the Move tool (moving a layer, or cloning it with the Alt key).

**Comment by photopea** [comment]
Can you find that shortcut here? https://helpx.adobe.com/photoshop/using/default-keyboard-shortcuts.html  Or any other text from Adobe mentioning it?

If your Ctrl+left click acts as a right click on your mac (in all apps), then  Alt + Ctrl+left click should work as Alt+right click even in Photopea.

**Comment by gse123** [comment]
I'm not willing to spend any more time going back and forth on this to be honest... especially when there is not a problem to solve. Photopea mimics the Windows version of the shortcut, which will be the most common.

The Mac shortcut of ctrl + Alt +Left click and drag does not work in photopea, as it would not work on the PC version. They are different.

 Bear in mind that the key labelled 'ctrl' on a Mac has not got any relation to the Ctrl/control key on a PC... on a mac, the 'cmd' key is the equivalent of the PC command key. If you still don't believe me, then I don't know what else to say.

**Comment by photopea** [comment]
It is just weird, that nobody ever mentioned this shortcut before, and I can not find any mention of it at Adobes website.

Ok I will close it.
