### ISSUE TITLE
i switched tabs, and now its all blank??? i have been working for around an hour and dont want to lose all my work and refresh it

### ISSUE THREAD

**Issue by ninikasa** [photopea/photopea#5643]

**Comment by photopea** [comment]
What is "blank"?  Could you share a screenshot? Did you do it on a computer or on a phone?

If Photopea crashes, your work should be stored in a local storage, and it should be opened again when you open Photopea again.

**Comment by ninikasa** [comment]
this is how it looks, on a browser, also it shows me that there is nothing.
[image: image.png]

**Comment by photopea** [comment]
Please, open Github in a web browser and reply there.

You are sending emails to some random Github addresses, but Github does not deliver us your whole email.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
