### ISSUE TITLE
Doesn't show "css" information on psd file anymore.

### ISSUE THREAD

**Issue by koyanagi1** [photopea/photopea#5647]
With a psd file, I used to get css information by clicking an item in the file. It doesn't seem to do so any more.

**Comment by photopea** [comment]
The CSS panel shows a style of a currently selected layer. You can select layers by clicking on them in the Layers panel (on the right side).

You can also click the layers on the screen, if the "Auto-select" at the top is enabled (maybe you have disabled it). Or hold Ctrl to enable it temporarily. All this works only for the Move tool - the first tool in a toolbar.

**Comment by koyanagi1** [comment]
You are right!  "Auto-select" was somehow disabled. Thank you for your time.

2023年5月19日(金) 23:55 Photopea ***@***.***>:
