### ISSUE TITLE
I Problems Large Project

### ISSUE THREAD

**Issue by chiron2** [photopea/photopea#5648]
Take Problems Large Project takeout

**Comment by camoody1** [comment]
![809bfbc3-bc7a-41b7-b68c-fa126a8896c1](https://github.com/photopea/photopea/assets/73725653/67dda3fc-5f34-4836-b697-a8b4345ad66c)

**Comment by chiron2** [comment]
yes

**Comment by chiron2** [comment]
SBOX_FATAL_MEMORY_EXCEEDED

**Comment by photopea** [comment]
I think you simply dont have enough RAM memory for the kind of work that you do. Get more RAM, or work with smaller files only.

**Comment by chiron2** [comment]
how to does

**Comment by chiron2** [comment]
finish
