### ISSUE TITLE
Fonts do not work

### ISSUE THREAD

**Issue by SayenNyan** [photopea/photopea#5649]
app cannot download fonts within its system or wherever , so text tool doesn't work either. there is dialog window "Downloading" on the screen for hours

**Comment by photopea** [comment]
Could you try this and let us know if it helped? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by SayenNyan** [comment]
reinstalling browser worked, thx

**Comment by photopea** [comment]
ok great! I think the key was to remove browser extensions. If you install the web browser for the first time, it does not contain any extensions.
