### ISSUE TITLE
Need an example for the postMessage API

### ISSUE THREAD

**Issue by titlestad** [photopea/photopea#565]
Hey!

The documentation for the postMessage API is very minimal. I've been trying to use it to push binary data to load an image, but haven't been successful. 

I'd appreciate an example that loads the binary data of a JPEG and then loads it in an iframe using this new API. Is this possible?

**Comment by photopea** [comment]
I think the postMessage API is very simple and there is no need for any deeper explanation.

Can you show us what you have so far? Maybe the problem is in something different than you think.

**Comment by titlestad** [comment]
As I understood it from the latest communication here, I was just to send the ArrayBuffer.
I take the binary data and just push it.

I get nothing back from onMessage with an error message.

The iframe which holds Photopea is referenced in the "pea" variable.

var ext = msg.Filename.split( '.' );
ext = ext.pop();
			
if( msg.Path.indexOf( '.' ) > 0 )
{
	var p = msg.Path;
	var f = new File( p );
	f.onLoad = function( data )
	{
		var ab = new ArrayBuffer( data );
		pea.postMessage( ab.buffer, '*' );
	}
	f.load();
}

**Comment by titlestad** [comment]
Could be my binary data is erroneous, but I don't get a message back or console log that tells me what is happening.

**Comment by photopea** [comment]
are you sure the onLoad function is executed?  What exactly new ArrayBuffer(data) means? You have to learn Typed Arrays e.g. here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays

**Comment by photopea** [comment]
And ArrayBuffer has no property ".buffer" ... do you really see no errors in the console? Maybe because onLoad function is never executed.

**Comment by titlestad** [comment]
Onload is executed, for sure - I've tested that. I've tried pushing the ab object directly too, and I've tried pushing the data directly, and other combinations - that's why I'd like to see a working example. I can't from only the docs see how this should be performed.

**Comment by photopea** [comment]
I am not familiar with the File object. What exactly the "data" parameter is in onLoad?  I load everything with XmlHttpRequest.

This is not related to Photopea at all. I have to teach you, how to load files as ArrayBuffers in Javascript :D

**Comment by photopea** [comment]
BTW. when I call new File(string), I see an error: Failed to construct 'File': 2 arguments required, but only 1 present.

What kind of Javascript are you using?

**Comment by titlestad** [comment]
We have our own framework - I think this is kind of the thing I'm looking for; a working example. I will give it another try - but if I had a working example, it would be easier to reverse engineer.

**Comment by titlestad** [comment]
Only thing I get back while testing is: 

Uncaught TypeError: H.data.charAt is not a function
    at Mw.<anonymous> (pp.js:6323)
(anonymous) @ pp.js:6323
pp.js:37 Uncaught TypeError: s.data.charAt is not a function
    at MJ.mX (pp.js:37)

**Comment by titlestad** [comment]
Just getting this: Uncaught TypeError: H.data.charAt is not a function
    at Mw.<anonymous> (pp.js:6323)
(anonymous) @ pp.js:6323
pp.js:37 Uncaught TypeError: s.data.charAt is not a function
    at MJ.mX (pp.js:37)

Shouldn't I get a message like: The binary data is not in the right format - or something like that?

**Comment by photopea** [comment]
Ok I added another demo to https://www.photopea.com/api/live . It shows how to load a JPEG as ArrayBuffer and send it to Photopea. Hope it helps! Let me know if you still have any problems.

**Comment by titlestad** [comment]
Hey! Before closing, I see in your example that the file comes up as file.psd - any chance of supplying a filename?

**Comment by photopea** [comment]
Photopea converts each file that you open into PSD, and then from PSD to any other format, as you save it. If a user adds new layers, text layers, adjustment layers ... the name "file.jpg" in the top would make no sense (JPG can have just one layer).  

We can still discuss it even after I close it :)

**Comment by titlestad** [comment]
Works! Thank you got it to work.

**Comment by titlestad** [comment]
In the callback from Photopea, would be cool to get "This is your fileID" - and then be able to message: set name of file fileID with "Home:Documents/Myfile.jpg". This way it would be much easier for the user to recognize which file was opened from the Friend Workspace.
https://pasteboard.co/HcUQKuY.png

**Comment by photopea** [comment]
What do you mean by "set name of file"? Do you mean the text in the label of the panel (in Photopea)? I think it is not so important. When you save it (e.g. by calling a script), you can give it any name you want.

**Comment by titlestad** [comment]
If I have three images / projects open at the same time, I need to be able to know where to save the file. If not, I will have to use "Save AS" every time I save a project.

**Comment by photopea** [comment]
How do you plan to save the file? Do you get it back from Photopea by calling saveToOE() ?

**Comment by titlestad** [comment]
I want to get it back through the postMessage API - just get an arraybuffer back and store that on disk. As you saw from the screenshot above, it would make Photopea into a desktop application - in the Friend workspace. I want it to behave like one. Next up is drag & drop loading of files.

Friend is the "Native operating system" for web apps - and so part of the integration will have to be done in the app itself for it to be fully immersed. But I'm willing to do everything that is required that can be done on the Friend side using the API.

**Comment by photopea** [comment]
That sounds cool :)

You can get ArrayBuffer from Photopea by executing saveToOE() . So "Save" button must be outside Photopea. Or maybe we could extend our API, so File - Save sends the file to outer environment?

**Comment by rafasashi** [comment]
Is it possible to send ArrayBuffer to activeDocument and have it as a new layer instead of a new document?

I was expecting that App.open(url, as, asSmart) would do that but I only have an object returned in the console.

From photopea.com script box I have tried:

`app.activeDocument.open("https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Photopea_logo.svg/220px-Photopea_logo.svg.png", "PNG", false);`

**Comment by photopea** [comment]
Hi, if your image is stored on a HTTP server (accessible over the URL), you can use app.open() while setting asSmart to true.

You can also send an ArrayBuffer to Photopea and then run a script, that would copy a layer from one document to another, and will close the previous document.

**Comment by rafasashi** [comment]
Thanks for the prompt reply!

> You can also send an ArrayBuffer to Photopea and then run a script, that would copy a layer from one document to another, and will close the previous document.

So after sending the data PP open a new doc and I collect the layer with app.activeDocument.activeLayer;

The way you do for the clone example.

And then how can I send it to the first document?

**Comment by rafasashi** [comment]
BTW setting to true doesn't work:

app.activeDocument.open("https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Photopea_logo.svg/220px-Photopea_logo.svg.png", null, true);

**Comment by rafasashi** [comment]
My bad! It is working very well with app.open indeed thanks!
