### ISSUE TITLE
La herramienta "Pluma" ya no funciona como antes

### ISSUE THREAD

**Issue by Customair** [photopea/photopea#5651]
No sé si es una actualización, pero por favor vuelvan al anterior porque no funciona como está ahora

**Comment by camoody1** [comment]
An update was made to the Pen Tool to make it more closely match how it works in Photoshop. What part of the tool is not working correctly for you?

**Comment by photopea** [comment]
Pen tool should be fixed now. Also, I speak only English, we do not accept requests in other languages.
