### ISSUE TITLE
Pen Tool Pointer

### ISSUE THREAD

**Issue by AirGEL** [photopea/photopea#5653]
The pen tool pointer is blocking where I'm trying to place anchor points making it hard to put them exactly where I want them. It's also slower and less responsive than before. Is there some way to get the regular pointer back when using the pen tool?

**Comment by Gasaman08** [comment]
Am also facing the same problem, please bring back the regular pointer.

**Comment by camoody1** [comment]
> Am also facing the same problem, please bring back the regular pointer.

I like the new pointer. Please leave it.

**Comment by photopea** [comment]
Hi, could you show us a screenshot or a video of what you mean by "blocking where Im trying to place anchor"? 

In my case, it always places a point at the tip of a pen cursor, so you can predict where it is placed. Just like it used to do with an arrow cursor in the past.

**Comment by camoody1** [comment]
@photopea The only difference I see between the Pen cursors in Photoshop and Photopea is those in Photoshop have their little indicators towards the bottom right of the arrow while the Pen cursors in Photopea have the indicators in the top right. Maybe that slight difference is causing them issues? I kind of agree with you, though, the anchors drop exactly where the cursor pointer is, so I don't see how the indicators would ever be in the way. 🤷🏼‍♂️

**Comment by Gasaman08** [comment]
Atleast make it more responsive like before because its kind of slower now.

**Comment by camoody1** [comment]
> Atleast make it more responsive like before because its kind of slower now.

What is slow? Can you create a video to show us? I've noticed no slowness on my devices, but maybe I'm not pushing the application as hard as you are? 🤷🏼‍♂️

**Comment by Gasaman08** [comment]
https://github.com/photopea/photopea/assets/123094812/5c885681-4fcc-48e4-b5f0-1a6fd852bb4e

What would have usually taken me a few seconds has now taken over a minute and this was just to show how slow and unresponsive the pen tool has gotten.

**Comment by camoody1** [comment]
@Gasaman08 If Photopea is truly stuttering that badly for you, there's something else going on with your device. I can promise you, my PC and Android phone have no such slowness at all... I click and move just as smoothly as I ever have. In fact, as I said, I've noticed no difference in the speed of the application at all. I would suggest running Photopea in In Cognito Mode just in case you've got some rogue extension causing problems.

**Comment by photopea** [comment]
It looks like everything in your video is slow. Is it really related to the Pen tools? Are you sure it worked faster before? Did you look at your CPU usage?

**Comment by Gasaman08** [comment]
It is the pen tool, I was just trying the incognito method but still no change. At first it was a bit faster than before but went back to Its normal(slow) state. I even tried it on my friends PC which is a later version than mine but still no change. If you could just make it a bit faster and more responsive like before.

**Comment by camoody1** [comment]
@Gasaman08 You said that you have this same slowness on multiple PCs? Is it with all the tools or just the Pen Tool? Your video looks laggy doing absolutely anything. Is the slowness with all your PSDs? Or just this one?

If the video you posted above truly represents the sluggishness and speed that your mouse pointer moves in Photopea, you've got something else going on. If there was Photopea code causing that much slowness, we would see a LOT of complaints the same as yours. The image in your video is only 1080x1080. I have no problems running the Pen Tool in an image that size on my mobile phone or PC.

**Comment by photopea** [comment]
Could you maybe record your screen with a phone, so that we see that your video recording software is not slowing down Photopea?

**Comment by photopea** [comment]
I think it all should be fixed now.
