### ISSUE TITLE
Pen Tool Issue

### ISSUE THREAD

**Issue by CxryzNFTs** [photopea/photopea#5655]
Hello,

When I try going from a curved to straight line in photopea, I usually just do Alt + Click on the anchor point, then it becomes a straight line. However, with the new update, it seems like this doesn't work anymore. How can I go from curved to straight lines in Photopea with the new update?

**Comment by photopea** [comment]
Hey, it should be fixed now.

**Comment by CxryzNFTs** [comment]
I don't think so. Doesn't work for me.

**Comment by CxryzNFTs** [comment]
Update: It only works if I hold alt, and drag the point out. It used to work when I just held alt.

**Comment by camoody1** [comment]
@CxryzNFTs Make sure you completely restart Photopea in order to get his code changes to take effect.

I just tested the changes on my PC and this particular function seems to work as it should. While using the standard Pen Tool, if I hover over an existing anchor point, the cursor indicator changes to a "-" sign. If I then hold the ALT key, it turns into a "^" sign. If I hold the ALT key and left click on the anchor, it will immediately change from a Smooth Anchor to a Corner (or straight) Anchor. If I want to change it BACK to a Smooth Anchor, I hold the ALT key, left click the anchor and drag. This all seems to work as it should.

**Comment by CxryzNFTs** [comment]
I think you guys are misunderstanding what I wrote. So let me clarify; When I create a path, and I want to change a curved path to pointed path, one of the handles must be removed. I used to do this by clicking ALT and the anchor point, and this is during the process of path creation. This removes one of the handles, allowing for a straight path. 

Maybe @photopea you can add an option to go back to the old pen tool?

**Comment by CxryzNFTs** [comment]
I'm referencing 6:38 in this video by the way https://www.youtube.com/watch?v=Rk-JGsriJ4o

**Comment by camoody1** [comment]
> I'm referencing 6:38 in this video by the way https://www.youtube.com/watch?v=Rk-JGsriJ4o

Keep in mind that this video is using Adobe Illustrator. The Pen Tool in Illustrator does not work the exact same way as the Photoshop Pen Tool. In this case, however, I can confirm that Photoshop DOES work as shown in your video at the 6:38 mark.

@photopea Go ahead and add this functionality to the other two items I showed in the video I made for the other Pen Tool ticket. As @CxryzNFTs says, in Photoshop, as you are drawing a path with the Pen Tool, holding the ALT key and clicking on a just created Anchor point will remove the last handle of the path... not both on the anchor, just the last one.

**Comment by camoody1** [comment]
> Maybe @photopea you can add an option to go back to the old pen tool?

@CxryzNFTs There's no need to go back to the old pen tool. We just need to get all the functionality correct on the new one. Patience, Young Padawan. Ivan is quick with his fixes.

**Comment by photopea** [comment]
I just tried to Alt+click the "middle point" with a Pen tool in Adobe Photoshop, and both handles were removed. If I do it with a "Convert Point tool" in Photoshop (Alt+click the middle point), just one handle is removed.

I just made an update to Photopea and it should work the same.

**Comment by photopea** [comment]
I just implemented this: Alt+clicking the last point of the path with a Pen tool should remove one of the handles

**Comment by camoody1** [comment]
> I just implemented this: Alt+clicking the last point of the path with a Pen tool should remove one of the handles

I'm sure this made a lot of Photopea users happy today. Well done, you sexy, sexy man. 😆

**Comment by CxryzNFTs** [comment]
Good work, thank you for handling this matter very professionally.
