### ISSUE TITLE
Vectorize Bitmap: two problem and two idea

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5656]
Hi!
There are only a few small problems left...) 

The meaning of the problems and suggestions in the video:
[https://youtu.be/SuqU_rBH-oo](url)

**Problem 1**
This script no worked in Photopea (but correctly in PS):
[https://photopeaactionslib.olegpustovoit.repl.co/VB_correctLoop.jsx](url)

**Idea 1**
**_Add a Stroke checkbox to Vectorize Bitmap with the ability to select the thickness of an additional outline for a shape with a color that matches the fill color._**
If the idea works, then the ideal result would be a shape where the fill area and the area of the additional outline would be UNITED into a new shape with an outline of thickness 0.
Thus, the problem of holes at the junctions of neighboring shapes, which is inherent in almost all raster-to-vector tracers known to me, could largely go away.

**Problem 2**
This script no worked (and without checked issue #5654 its not possible yet) in Photopea (but correctly in PS).:
[https://photopeaactionslib.olegpustovoit.repl.co/VB_correctLoopOnlyShapes.jsx](url)

**Idea 2**
With no less surprise than the possibility of adding paths to JPG :), I learned that the descriptor of the operation "Working path from selection" contains the parameter "tolerance" in the Action Manager PS (by default = 2.0 pixels). At the same time, this operation in PS (well, in Photopea) is applied without the user being able to specify this parameter before use.
**_Maybe give Photopea to the user this opportunity through a small pop-up window?_**
Yesterday I checked its action in the PS with a script, it significantly affects the result. At the same time, visually, according to the default, Photopea now does this better than PS, for which another respect to Ivan. But to check how the tolerance setting works in Photopea without solving Problem 2 and of this study is not yet available.

Related Issues:
[https://github.com/photopea/photopea/issues/5654](url)
[https://github.com/photopea/photopea/issues/5650](url)

Forgive me for the many letters since Sunday morning, but when else can you work in peace?:)

**Comment by photopea** [comment]
Could you tell me how can I run your scripts in Adobe Photoshop?

I opened a JPG file and ran your first script, but it did nothing.

I think that adding a stroke to shapes is a very wrong solution. Some stroke will cover other strokes, and we have a new problem - figuring out the order of colored parts in Layers. If you enable "Polygons", the colored parts will "touch".

**Comment by Pt-home** [comment]
The script will run if you first split your file into a vector in Photoshop and save it to PSD, and then transfer it to Photoshop. The script goes through all the layers from the layers folder, which is automatically created by Photopea during vectorization

However my file is here https://photopeaactionslib.olegpustovoit.repl.co/VB.psd

**Comment by Pt-home** [comment]
![image](https://github.com/photopea/photopea/assets/29394245/a70ad102-95bc-45c7-8d88-5888d94af8ec)
Polygons. Do not set rounding less than 2 and the result (as for me) has more OTHER disadvantages.
I just asked if it makes sense to let the user choose what would be more convenient for him in a particular case. In any case, it's up to you, I just suggested and illustrated why :)

**Comment by photopea** [comment]
Do you need these scripts to do an actual work, or you just look for scripts which dont work in Photopea? There are LOTS of scripts which dont work in Photopea, and I would like to do work which helps as many people as possible.

I agree, that the gaps between shapes are a problem, but adding a stroke is a wrong solution.

BTW. in your image, between every two colors A and B, there are is a color, which is not a combination of A and B (e.g. it is much brighter than A and B). Vector graphics is never rasterized this way. Someone probably resized it in Adobe Photoshop (which adds sharpening). This causes many problems to the Vectorization.

![image](https://github.com/photopea/photopea/assets/15955558/afe1b0b4-973a-4a08-b218-34fe24f04f3f)

**Comment by Pt-home** [comment]
> Do you need these scripts to do an actual work, or you just look for scripts which dont work in Photopea? There are LOTS of scripts which dont work in Photopea, and I would like to do work which helps as many people as possible.

З твого дозволу, я відповім українською з деяких міркувань...
Так, кожен скрипт, про який я Вас питав потрібні мені для реальної роботи. А ці два - особливо.
Більш того, вона вже на 95%, завдяки Вашій допомозі, зроблено.
І її вже потроху зараз тестують пара десятків моїх маленьких учнів. І вони для цього відкривають Фотопіа...

Я тепер чудово знаю, що багато речей з Фотошопу не працюють у Фотопіа. Але, повірте, що я звертаюсь до Вашої допомоги лише там, де для РЕАЛЬНОЇ необхідності не бачу іншого шляху. І до речі, залишилось лише заставити працювати модифікацію виділень - Expand, Contract... Так, з мого напіваматорського погляду дивно, що навіть деякі атрибути документу неможливо досі "дістати" програмно - ту ж колекцію каналів, наприклад... Але - маємо те, що маємо.
До речі -  "There are LOTS of scripts which dont work in Photopea" було б зараз корисним доповненням у розділі https://www.photopea.com/learn/scripts, по великому рахунку. Може я б ще подумав, чи варто братись за задуману задачу

Крім того, сфера моїх педагогічних інтересів - впровадження концепції "Уся шкільна інформатика - в браузері".
І у кожній моїй статті у розділі "Растрова графіка" вказано лише один інструмент - Фотопіа.
У профільній старшій школі кожен рік тільки у мене близько ста студентів відкривають протягом семестрів Фотопіа. І будуть це робити при необхідності, бо їх научили цьому, а люди не люблять змінювати інструмент... 

Крім того, вважаю зараз використання GIMP шкідливим при навчанні дітей, бо це мертвий проект, але викладачі часто консервативні і не хочуть змінювати звичне. Тепер у мене майже на руках козирі, що можна об’єднати вивчення основ JS та використання бібліотек у цікавому вигляді програмної роботи з зображеннями за допомогою Фотопіа. І кожен викладач, якого я зможу тепер наочно переконати перейти на Фотопіа - це нова сотня людей, які почнуть її відкривати як студенти, а потім - як користувачі....

 Ну, і я завжди "забуваю" розповісти дітям про AdBlock:), до речі... Хай щось самі собі думають...

Ми знаємо, що ви один підняли та підтримуєте цю гору - Фотопіа. І це абсолютно Ваше право вирішувати, що є зараз актуальним щодо витрачання часу - це Ваш бізнес.  Я лише спробував аргументувати Вам свій власний погляд, чому у своїй сфері викладачі опосередковано працюють і на Ваш бізнес.

І якщо б у Фотопіа був розділ для скриптів, я б, наприклад, зразу виклав би туди будь-які корисні з моєї точки зору приклади та бібліотеку - хай, кому треба, користуються, на здоров’я. Ті ж Екшини там зараз, наприклад, багато не працюють повністю - як зустрінеться smartBlur - усе, стоп робота... Вони ж здебільшого Фотошопівські...

Ще раз, з великою повагою до Вашого продукту, до ваших зусиль та підтримки користувачів. Вибачте, якщо щось не так...
З повагою, 
Олег Пустовойт, Одеса.

**Comment by camoody1** [comment]
@Pt-home Are you currently living and working in Odessa? If so, how has the war affected your daily life? Odessa is right on the Black Sea, correct? Have you seen any naval or air force actions? I believe there is still a massive fight happening just east of Kherson which isn't too far from Odessa, yes? I do pray you and your students are safe.

**Comment by Pt-home** [comment]
[camoody1](https://github.com/camoody1) I hope this doesn't fall into the category of a flood:)

> Are you currently living and working in Odessa?
Yes, I am answering you now from Odesa... Moreover, I was born in Bakhmut and my native microdistrict is now on the screens of CNN. Life is an unusual thing, it always surprises

>If so, how has the war affected your daily life?
We were lucky in many ways - in fact, we are in the rear.
And thank God, in fact, life in our city is quite calm.
Yes, the episodes were different in the beginning. For example, we were selecting online candidates for the country team to participate in the world competition in design computer technology - and at that moment a rocket hit a house a couple of kilometers from where I was. But in comparison with other cities, Nikolaev and Kherson are episodes. By the way, Kherson, Mykolaiv and Ochakov closed Odesa from the war ...
It was hard in winter, when there was a nightmare with energy, but the system survived. As an example - I slept with the electric switch on - if the light comes on at three in the morning, you get up and record video lessons while you have the opportunity, so that later the children can work them out when the light is on them. A lot of work was done with the fact that schools were centers of assistance to residents, where there should have been electricity, the Internet, heat ... Nothing, they did it.
Since air defense works wonders, without exaggeration, studies have been interrupted three times over the past two months - all raids are at night, and their intensity is much lower. This is if in a nutshell.
The most paradoxical thing is that covid "helped" - we were already ready for the learning process remotely. And now we are coping calmly when a third of the students in the class, a third are in touch via Zoom from other countries, a third are on an external course ...
Work helps to keep the meaning and not think about the sad. Now we are bothering Ivan with our ideas and projects, we hope he is not very upset))

> Odesa is right on the Black Sea, correct?
Yes

> Have you seen any naval or air force actions?
Yes, at the beginning of the war, one of the naval episodes took place before my eyes - a good story by a good writer is worth something. Of course, I saw the work of air defense - but now I have such a sound sleep that I have not woken up at night because of this for a long time;) Human psychology is an amazing thing.

> I do pray you and your students are safe.
Thanks. 
"Все буде добре!" - "Everything will be fine":)

**Comment by Pt-home** [comment]
> I agree, that the gaps between shapes are a problem, but adding a stroke is a wrong solution.

Ok, a working script will suit me personally.
Since Adobe has not closed this thread for 10+ years :)
[https://community.adobe.com/t5/photoshop-ecosystem-discussions/cs6-how-to-convert-a-path-stroke-in-a-vector-shape/td-p/4531476](url) And anouther treds in the difference places...

Once again I will say that in Corel (it was certainly easier there, the stroke was converted into a shape and combined without all these descriptors, the usual object model, 10 lines) I checked this method like this: I took my own photos, converted with a tracer + script and sent to the stock ( 3 minutes, description took longer). And sinks check the vector in many ways and for tracing too. There were no responses. Well, for example, it looked like this, what I found, a lot of time has passed:
![image](https://github.com/photopea/photopea/assets/29394245/23d5fe63-9c2e-44e8-98eb-d6c0adac53de)

**Comment by photopea** [comment]
Your script https://photopeaactionslib.olegpustovoit.repl.co/VB_correctLoopOnlyShapes.jsx should work now.

I had to rebuild a big part of the source code, so there is a small chance that some other scripts, which worked in the past, will not work. If you find such scripts, please, let me know :)

**Comment by Pt-home** [comment]
Good news, great thanks... But I have good news too. With opened now two little issues, I know only one no-fixed script problem, little problem, from all big array operations Photopea. And its cool))

**Comment by Pt-home** [comment]
Ivan, I'm checked, but now((:
![image](https://github.com/photopea/photopea/assets/29394245/972763dd-8aee-47c7-8866-3fab7e3ddc3b)

**Comment by Pt-home** [comment]
And in pair scripts with putObject (colors input) today I see this:
Uncaught ReferenceError: **nobj is not defined** at kn.CP.Tb (pp.js:10425:1) 

But yesterday this moment will be correct...

**Comment by photopea** [comment]
What script are you running and on which file?

I always need two things:
- a script (as short as possible, but still causing an error)
- a PSD file to run the script on
