### ISSUE TITLE
Ad Blocker is Paused but I'm still getting the message that it's on.

### ISSUE THREAD

**Issue by actuallyambah** [photopea/photopea#5657]
Hi! I appreciate the software and intend to donate if I ever make a sale... In the meantime I told AdBlock to pause on your page. I See the green icon and it seems like it's paused but I still see the Game ad's and I get the (justified) passive aggressive message when I export an image.

**Comment by camoody1** [comment]
Try running Photopea in In Cognito Mode. We've seen this before where other extensions are causing issues like this.

**Comment by photopea** [comment]
According to our reserarch, you can not make this browser extension: https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom not block the ads. The only way is to remove it completely (as it is always blocking ads when it is on).  See https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom

You can also try other ad blockers like AdBlock Plus.

**Comment by FireTiger898** [comment]
Yeah, @actuallyambah same issue wit me!
