### ISSUE TITLE
Layer panel icons missing.

### ISSUE THREAD

**Issue by johnlyons** [photopea/photopea#566]
![screenshot 2018-03-21 at 6 01 57 pm](https://user-images.githubusercontent.com/4950528/37728398-140b33dc-2d32-11e8-9377-68b4f1e70988.png)

Hi, editing still works but I just noticed that the icons in the layers panel, normally on the left, seem to have disappeared.

**Comment by photopea** [comment]
Hi, we were just updating the way icons are loaded.  Seems like your browser loads the new JS files, but an old CSS file (probably from the cache). Can your reaload your page properly (e.g. Shift + F5) ?

**Comment by johnlyons** [comment]
That worked, thanks a million for your help!

**Comment by photopea** [comment]
no problem, sorry for such unexpected update :D
