### ISSUE TITLE
Brush tool wrong size

### ISSUE THREAD

**Issue by Sunufrate** [photopea/photopea#5661]
Good morning.
First of all thank you for creating and developing Photopea, it's a wonderful and useful tool and it's amazing to use something like that online and free.

I'm here to report you an annoying and important bug, related to the brush tool.
Basically the pixel size of all the round brushes (specially the hard round), is not respected.
If you select (with the maximum Hardness and flow) a 1 px size, the brush works good, but if you select a higher value, the brush size is always a couple pixel higher. As a result it's impossible to use a 2 px size brush.
Examples:

1) Brush size 1 px is good:

![1 px](https://github.com/photopea/photopea/assets/134371564/d5f5efe5-1ae7-4cfe-82cb-b91d1ef0273b)

2) Brush size 2 px, takes 4 pixels (the 2 additional pixel fill with 80% opacity even if I'm using the maximum hardness and opacity)

![2 pt](https://github.com/photopea/photopea/assets/134371564/cbc68d12-b5e6-4932-949e-97d001f69d5b)

3) Brush size 3 px, still takes 4 pixels (the 2 additional pixel fill with 100% opacity now)

![pt 3](https://github.com/photopea/photopea/assets/134371564/534209c4-a4f6-4ab2-ae0c-6598a317853a)

4) and so on, size 4px takes 7 pixel, but the external 2 lines are 50% transparent.

![pt 4](https://github.com/photopea/photopea/assets/134371564/d062a644-85e5-46b5-8f19-e3ece850d1ef)

The only way i found to fix this, it creating a custom brush and setting a 45° orientation, but it's not very good.
The line is too strong specially in rounds or corners.
So I hope the developers can fix this.

The brush is supposed to work in opacity only with low hardness, and is also supposed to fill the correct number of pixels.
Thank you
Best

**Comment by photopea** [comment]
Are you trying to make Pixel Art? Do you now about the Pencil tool?

**Comment by camoody1** [comment]
@Sunufrate From Google Bard...

The main difference between the brush tool and the pencil tool in Photoshop is that the brush tool creates soft-edged strokes, while the pencil tool creates hard-edged strokes. The brush tool also has a wider range of options for customizing the appearance of your strokes, such as shape, opacity, and size.

Here is a table summarizing the key differences between the brush tool and the pencil tool:

| Feature      | Brush Tool      | Pencil Tool |
| Edges         | Soft                 | Hard |
| Options      | More               | Fewer |
| Use cases | Painting, drawing, and sketching | Creating precise lines and shapes |

Here are some examples of how the brush tool and the pencil tool can be used in Photoshop:

* The brush tool can be used to create soft, natural-looking strokes, such as when painting a landscape or portrait.
* The pencil tool can be used to create sharp, precise lines, such as when drawing technical diagrams or illustrations.
* The brush tool can also be used to create effects, such as textures or patterns, by using different brush presets.
* The pencil tool can be used to create outlines or borders around objects in an image.

Ultimately, the best tool for the job will depend on your specific needs and preferences. If you need to create soft, natural-looking strokes, the brush tool is a good option. If you need to create sharp, precise lines, the pencil tool is a better choice.
