### ISSUE TITLE
New/Rename Feature: Generative Fill

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5662]
I think we may have the perfect name for the "Magic Replace" tool... Generative Fill

Photoshop has just released a new tool that is basically exactly what you've already started in Photopea. Here's a great video showing all aspects of it.

https://youtu.be/a3LXB-lA-Qw

First off, I love the name they use. It definitely fits what you're doing better than "Magic Replace". Also, they basically offer the new "Generative Fill" option whenever the user has a selection tool in use. So, instead of burying the tool in the healing tool section, they just make it a universal option on all select tools. This is nice because people won't feel as if they can only use the lasso select tool as we have, now.

With this new tool, they've also added a whole new interface in the layers section. This is pretty cool, but probably more than what is necessary for Photopea.

I believe this new PhotoShop tool is utilizing the new Adobe Firefly AI tool, whereas Photopea is using Dezgo. I've done a lot of these same functions they show in this video with Photopea. If you change the name of your tool to "Generative Fill" and made it available on all the selection tools, people looking for tutorials on YouTube might find videos for Photoshop AND Photopea.

Anyway, I just thought I would share this video to you to see if it gives you any new ideas for Photopea.
✌🏼

**Comment by camoody1** [comment]
What do you think about renaming "Magic Replace" to "Generative Fill" to match what PS has? Most of your other tools follow their naming conventions.

And what about offering the functionality as an option for every selection tool instead of just under the Healing Tools? I've found that the Removal option still doesn't work too well for me. But the replacement functionality does pretty well. So, it really is a better Generative Fill tool than it is a healing tool at this point. 

Even if you don't want to change the name, I still think it makes sense to remove it from the healing section and add it as an option to each of the selection tools.🤷🏽‍♂️

**Comment by photopea** [comment]
But Magic Replace is not a selection tool, it is a image-modifying tool (like a brush, eraser, clone stamp ...) . Selection tools can only modify a selection. Some image-modifying tools can do make selections, too (patch tool, magic replace ...).

I thing the "Generative Fill" is too long. Let's wait a few months to see how it all turns out.
