### ISSUE TITLE
Text tool bugs editor

### ISSUE THREAD

**Issue by LordDramatic** [photopea/photopea#5665]
For some reason when I use the text tool and when I start to type, the top of my screen goes missing and I can't get rid of it unless I refresh the page only to lose my progress
![Bug](https://github.com/photopea/photopea/assets/134564034/1e1b1667-bb9e-4022-b6e6-1f10964f142f)

**Comment by photopea** [comment]
Try this, I am sure it will help: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

In short, Photopea works correctly only in an updated browser, and you should not use browser extensions that try to modify Photopea.
