### ISSUE TITLE
Guide is not set on the center of the artboard

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5666]
![image](https://github.com/photopea/photopea/assets/11801254/c87878f6-31ff-43f6-90ce-54f03fb386e6)

When moving the guide to the center of the artboard it snaps to the middle but 0.01 mm off.

Also, when deleting an artboard and the undoing it, the artboard goes over the other one and its guides move to a negative position

https://github.com/photopea/photopea/assets/11801254/4b34aa2e-c8b5-4bed-a9a1-d5a36f0ff67c

The PSD: [no exact center.zip](https://github.com/photopea/photopea/files/11570074/no.exact.center.zip)

**Comment by photopea** [comment]
I think I have fixed both issues (and really hope I did not break anything).
