### ISSUE TITLE
Smart object canvas size is not updated

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5667]
![image](https://github.com/photopea/photopea/assets/11801254/af89955d-98f6-41cd-9fc2-4d8ccd950042)

![image](https://github.com/photopea/photopea/assets/11801254/5c070b8e-3f77-405e-8409-62c7e3762948)

here the PSD
[Layer 8.zip](https://github.com/photopea/photopea/files/11570146/Layer.8.zip)

**Comment by TheRadicalDreamer** [comment]
i got why XD

I didn't know that smart filters had size  :P

**Comment by TheRadicalDreamer** [comment]
The smart filter is not updated.

When i clear it, and then undo the action i get the whole layer

**Comment by photopea** [comment]
It should be fixed now, just resize your smart object.

This error appeared when we were trying to fix rendering of the Liquify filter, which gets broken when the source image is cropped differently. So that probably got broken now.

**Comment by TheRadicalDreamer** [comment]
Thanks!

Just to clarify, i didn't use liquify filter.

I just used a sharpen filter
