### ISSUE TITLE
Não consigo utilizar algumas fontes 

### ISSUE THREAD

**Issue by Kaizynnn** [photopea/photopea#5668]
Olá boa noite, estou aqui pra relatar um erro no site Photopea. O site esta apresentando problemas na hora de abrir determinadas fontes. Nem sempre isso acontece, as vez abre, as vezes não abre. Tem sido bem recorrente esse tipo de erro, espero que resolvam rápido, pois esta dificultando na hora de fazer certos projetos. 

muito obrigado pela atenção

**Comment by camoody1** [comment]
Which fonts aren't working correctly?
![bitmoji](https://sdk.bitmoji.com/render/panel/9d438724-a1e5-44b9-9172-377503bbffe6-33290fb4-ad75-46e6-8062-305f1f5378d9-v1.png?transparent=1&palette=1&width=246)

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by leodesign021** [comment]
o meu tbm esta assim, não abre algumas fontes!
