### ISSUE TITLE
ram file is 1.1gb

### ISSUE THREAD

**Issue by chiron2** [photopea/photopea#5669]
I full  RAM 1.1GB Bug in Photopea

**Comment by camoody1** [comment]
I'm not sure this is a "bug" as much as a fun feature of Chrome browsers. I have a project open in my Photopea webapp (Microsoft Edge) with a 3000x4000 pixel image. My current RAM usage for that tab is approximately 1.2GB. The tab for just this GitHub page is 213MB. And my YouTube page is 285MB.

**Comment by photopea** [comment]
I am afraid I do not understand. What is the issue? Your text does not have verbs :D

**Comment by camoody1** [comment]
> I am afraid I do not understand. What is the issue? Your text does not have verbs :D

😂

I think they're complaining that Photopea is using too much RAM on their PC. But as I posted, I'm not sure that's necessarily a Photopea problem. I just think every tab in Chrome or Edge takes up a huge amount of RAM.

**Comment by JessMTermini** [comment]
> I'm not sure this is a "bug" as much as a fun feature of Chrome browsers. I have a project open in my Photopea webapp (Microsoft Edge) with a 3000x4000 pixel image. My current RAM usage for that tab is approximately 1.2GB. The tab for just this GitHub page is 213MB. And my YouTube page is 285MB.

Sorry to butt in here, but I just had to once I read this..
You're saying you're NOT using Chrome, but using Microsoft Edge, and you ARE showing the same 1.2gb RAM usage for Photopea as he was having, while all your other tabs remain around 200mb-ish. That says more like it iS a Photopea thing and NOT simply a Chrome things, cause if it WAS just a Chrome thing, then I'd think YOU'RE Microsoft Edge Photopea Tab would also be around the same 200mb-ish as your other tabs.

Maybe I'm missing something here? Or maybe you meant to say something else???

**Comment by camoody1** [comment]
@JessMTermini I'm saying that Photopea, in my mind, absolutely should take up more RAM than a simple FitHub or YouTube tab. As Ivan says, each pixel on Photopea needs 4 bytes of RAM. If you start working with a large image, that's a lot of RAM. This is an advanced web application we're dealing with here... not a static webpage with some artwork. 🤷🏽‍♂️

**Comment by JessMTermini** [comment]
@camoody1 I completely agree with what you just said. Although, don't you think it's a little odd/mysterious/coincidental that your same browser tab is showing the exact amount of ram being used as the original poster. 

### Let's look at the variables
Most likely he has been working on his project for some time. This suggests he might have a higher amount of ram available to his project than yours, and we also don't know the size of the image he was working with... but, a 3000 x 4000 px image could be considered large depending on what you are actually working on (for print or the web)...

But even with those variables, ...for your brand spanking new tester tab to open with a 3000 x 4000 image and requiring the **exact same** as his (@chiron2), to me, just still doesn't add up,...

### Ok, so, Let's do some math
3000 x 4000 pixels = 12,000,000 bytes x 4 bytes each = 48,000,000 bytes which by these calculations...**if**

> Every pixel in Photopea need 4 Bytes of RAM. So if you have a million pixels, that is 4 MB, a billion pixels is 4 GB of RAM, etc. (by @photopea)

... then, your tab should equal around 48mb of ram which is necessary for that particular image. And when we add your regular browser overhead of approx. 220someting mb (as all your other open tabs show 213mb and 285mb respectively.) to your 48mb photopea project, that still only adds up to approx. 260mb-ish (+/- actual totals etc - using 220mb as the browser overhead and 48mb for 3000 x 4000 image.) !!

So it still looks to me that it IS definitely OFF, a Photopea **thing**? I don't know. We would need to know more about the original posters setup like his browser tab normals among other things, etc. But there is a **thing** going on here for sure. I don't know what it is...is it photopea, I don't know, maybe....But more testing would obviously need to be done here, but that would be up to you guys to decide if this information is worth enough to you to make you want to fully explore and test the situation out. But by based on what everything you have said earlier...some**thing** _is_ happening here. Some**thing** is just not right lol. Sorry to point out, and sorry to say...

...but alas maybe I am wrong. Maybe I did my math wrong or some**thing**??

**Comment by camoody1** [comment]
@JessMTermini A few things...

1. 1.1GB isn't "the exact same" as 1.2GB.
2. We have no idea how large the OP's image was because he never bothered to respond. 
3. Google Chrome and Microsoft Edge ARE basically the same browser because Edge is a chromium based browser.
4. You assumed the OP had been working with his image "for some time" and that mine was "a brand spanking new tester tab". We don't know that from the OP and, if I remember correctly, I had been working on my item for quite some time that day.
5. Ivan will have to answer as to rest of the RAM usage. But I disagree that a Photopea should only need the same base amount of RAM as a simple GitHub page being displayed. There are a ton of calculations being done on the local device in Photopea's code as compared to a simple display of a GitHub page. I never thought to look, but I'm sure PhotoShop takes up much more RAM than 220MB. And that's really a more viable comparison than a GitHub or YouTube page. Keep in mind, that if the OP had several Smart Objects in his project, those each add a ton of RAM overhead in Photoshop, as well as Photopea.

The point is that the OP stopped responding and didn't give us enough information to work with to determine if his RAM usage was unwarranted or not.

**Comment by camoody1** [comment]
I decided to check RAM usage between Photoshop CS6 (a very old version) and Photopea (as a webapp) on my PC.

Opening the same images and performing the same functions in both apps, Photopea is using about 400MB more than Photoshop - PS: 1.2GB vs PP: 1.6GB. Is it more? Yes, for sure. But given that Photopea is built on the web, I would assume it is less "tightly coded" than Photoshop that is a native app.

Now, I could be 200% wrong on all of this. LOL. I'm not on the Photopea development team. I'm just your average Joe Moron who uses Photopea as a hobby. Ivan is your real point of knowledge for all of this.
![bitmoji](https://sdk.bitmoji.com/render/panel/0f789e4d-9133-4194-85af-a55b4027d8b4-33290fb4-ad75-46e6-8062-305f1f5378d9-v1.png?transparent=1&palette=1&width=246)

**Comment by photopea** [comment]
You can get more information about how Photopea uses your RAM by clicking Window - More - RAM. It is an interactive chart, you can click each document to check each layer, each mask, each layer style, etc.

**Comment by camoody1** [comment]
> You can get more information about how Photopea uses your RAM by clicking Window - More - Memory. It is an interactive chart, you can click each document to check each layer, each mask, each layer style, etc.

Ah, nice. I had no idea. That should be helpful if the OP actually cared to write back. 🙂
