### ISSUE TITLE
Use thin cross cursor like in rec select tool for drag out shapes

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#567]
The big black cursor now in shape tool is difficult to work with small elements without zooming in.

A thin cross cursor just like in rec select tool would be better for tiny accurate elements

**Comment by photopea** [comment]
Shape tools (Rectangle, Line, Custom Shape ...) should have a standard "arrow" cursor now. What cursor do you see?

**Comment by hgs54371** [comment]
Yes, by that I mean the standard cursor

**Comment by photopea** [comment]
But a standard cursor should not be that hard to use. It has a "sharp" dot on the top left side, which is quite precise, just like the center of a cross.

**Comment by hgs54371** [comment]
When drawing around elements smaller then the cursor, it is hiding/covering them

**Comment by photopea** [comment]
It was fixed.
