### ISSUE TITLE
Can We Use Photoshop Plugins in Photopea?

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5670]
I'm sure that not ALL of the plugins would work, just like not all Actions will work, but maybe some would?

If we CAN use Photoshop plugins in Photopea, where do we install them?

I saw this great plugin for Automatic1111 that might be of interest to people who are running their own StableDiffusion setups at home.
https://youtu.be/Y3KJli8ohKI

**Comment by Pt-home** [comment]
@camoody1 
Hi!
https://www.photopea.com/api/plugins
I think, the objective differences between a classic program and a web application make your desire unrealistic for the time being. However, the author knows best

**Comment by camoody1** [comment]
> @camoody1 Hi! https://www.photopea.com/api/plugins I think, the objective differences between a classic program and a web application make your desire unrealistic for the time being. However, the author knows best

I believe you are correct, sir. Sadly, I am not a coder, so manipulating an existing Photoshop plugin to make it work in Photopea is beyond my scope of knowledge. Maybe someone else will take up the challenge. 🤷🏽‍♂️

**Comment by photopea** [comment]
Photoshop plugins are native programs. If you have a plugin for Windows Photoshop, you can not use that plugin in Mac Photoshop.

To use Photoshop plugins in Photopea, we would need a virtual machine to interpret the native code. It is hard to tell how fast would it work, and how large such program would be (probably between 10 kB and 10 MB).

@copy what do you think would be the best solution for this? Thousands of great Photoshop plugins have been made in the past 30 years, it would be great to reuse them, we just need a virtual machine to execute them.

**Comment by photopea** [comment]
I will close it now, as it would require months of work.
