### ISSUE TITLE
Same fonts, different sizes. A buggy behaviour from Photoshop

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5671]
I want to ask if i am the only one with this issue.

If you have resized a text layer with the transformation tool, you kinda break the layer, because next time you want to copy paste a text from or to that layer, the copied text will be distorted. And you cannot correct that (Unless you delete and create a new text layer).

Here is a video explaining it on Photoshop:
https://youtu.be/9P01qAn52Y8?t=485

Here is a video I explained in Photopea:
https://github.com/photopea/photopea/assets/11801254/106fdfe7-3946-4d44-b057-fd3bd8306a4a

Do you think this buggy behaviour should be kept on Photopea? Just to work like Photoshop?

What do you think @MichalSZZ @nothingshiru?

**Comment by camoody1** [comment]
I understand that it doesn't work the same way you want it to, and perhaps this is a bug, but isn't it just an easy work around to highlight your wrong-sized pasted text and change its font size to match the size of the other text? For example, in part of your video, you have text of size 80 and you paste text that pops in as size 24. Can't you just highlight that new text and change it to 80? I know it's an extra step, but it's not a game breaker, right?

I'm probably missing something, though.🤷🏽‍♂️

**Comment by TheRadicalDreamer** [comment]
Yes i totally can. But every time i paste content in that text layer i'll have to do it. 🫡

It is uncomfortable. 

Like imagine if the brush tool makes a little spot on the right every time you paint. Of course you can erase it every time, but it will be a bad UX.

**Comment by photopea** [comment]
fixed! :)

**Comment by TheRadicalDreamer** [comment]
YES!! Now Photopea is one layer better than Photoshop
