### ISSUE TITLE
Artboards - Position of inside layers

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5673]
![image](https://github.com/photopea/photopea/assets/11801254/5abee73f-af2b-48f2-8379-c4d65b488583)

I have a layer inside an artboard and the X&Y positions shown on the property panel are absolute, but i believe it should be relative to the artboard.

If not, it is not really useful to have that info imhp.

In the image above the X&Y should be (0,0)

**Comment by MichalSZZ** [comment]
@TheRadicalDreamer  it should work as you described - each element should be positioned to their artboard's X and Y
