### ISSUE TITLE
Loses sidebar

### ISSUE THREAD

**Issue by IrishJinx** [photopea/photopea#5675]
Whenever I sign in I lose part of the screen. I can't access the side bar to create or edit layers. I have purchased premium for 90 days.

**Comment by xan2622** [comment]
Hi. 
1. What web browser (and version) do you use? 
2. Have you tried to delete the cookies for Photopea.com?
3. Have you tried after disabling your browser add-ons/extensions?

**Comment by photopea** [comment]
Could you show us a screenshot of what you see after logging in? Also, what email address do you see in the Account window after logging in?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
