### ISSUE TITLE
Ad blocking detected when Im using no ad block

### ISSUE THREAD

**Issue by TheUsername102** [photopea/photopea#5676]
For some reason it keeps on saying I'm using ad-block when I'm not. I have no viruses or extensions or ad blocks.

**Comment by photopea** [comment]
Are you using Chrome? Can you click the "puzzle icon" in the top right part of your web browser? Could you show us a screenshot of what you see there?

**Comment by Tarik366** [comment]
What is your browser? Some browsers getting with built-in ad-blockers

**Comment by photopea** [comment]
I have to close it because of the lack of details :(
