### ISSUE TITLE
Bring Back the option to create a trnsparent icon

### ISSUE THREAD

**Issue by photoeditorlover** [photopea/photopea#5677]
I've been using transparent profile for years now. But, now whenever I clicked transform the number of times I zoomed in and zoomed out the percentage and height and weight won't stay put. It changes whenever I click and transform my profile. Whenever I create a transparent icon. I always go with 400 x 400 and 500 x 500 but whenever I changed into that it would change differently. Also, I would like a request to remove notice std symbols. In fact kindly create another type option below the vertical type tool and place the font symbols and international fonts such as hindi, arabic, malaysian, and indian fonts. Its not necessary for English users to used it though or just make it available for their own country.

**Comment by camoody1** [comment]
Could you record a short video showing us what you're talking about? I don't know about @photopea, but I'm having a difficult time understanding what you're talking about.

**Comment by photoeditorlover** [comment]
![image](https://github.com/photopea/photopea/assets/134752543/5d3c9342-424d-4641-9bdb-942faed946a2)
I don't have a video recorder on laptop though but the thing is it won't stay put. You can literally try it yourself. But, as this moment I'll try video recording it.

**Comment by camoody1** [comment]
@photoeditorlover If you have Windows 10 or Windows 11, you should have access to the Windows Snipping Tool. That has the ability to record a window on your screen as you work. You could try using that.

**Comment by photopea** [comment]
You have enabled the "lock aspect ratio" - the chain icon between the two values. If you change one, the other will be changed, to keep the aspect ratio.

Also, what is "notice std symbols"? Do you mean symbols for Sexually Transmitted Diseases?

**Comment by camoody1** [comment]
> Also, what is "notice std symbols"? Do you mean symbols for Sexually Transmitted Diseases?
😆😁😂

**Comment by photoeditorlover** [comment]
> You have enabled the "lock aspect ratio" - the chain icon between the two values. If you change one, the other will be changed, to keep the aspect ratio.
> 
> Also, what is "notice std symbols"? Do you mean symbols for Sexually Transmitted Diseases?
What do you mean, its in the list of fonts. I think you need to check font list and search it. I don't know if its a joke or a sarcasm. But, I think you need to recheck the fonts.

**Comment by photopea** [comment]
I guess it has been fixed, so I am closing it.

**Comment by camoody1** [comment]
@photoeditorlover Why would he need to remove the Notice STD fonts? I don't understand the request.🤷🏽‍♂️
