### ISSUE TITLE
why

### ISSUE THREAD

**Issue by 1mmxw** [photopea/photopea#5678]
![image](https://github.com/photopea/photopea/assets/89283487/b3f486c3-aa0c-4e07-b8db-6a3550cf732b)
why dont work this button

**Comment by photopea** [comment]
So what happens when you click it?

Also, are you modifying the content of Photopea? Could you press the "puzzle piece icon" at the top right part of your browser, and show us what you see there?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
