### ISSUE TITLE
Don't close documents after script (any) apply 

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5679]
Hi!
**Problem:**
1. Open document
2. File-Script,  insert any correctly script (for example - click on "Process layers" demos...)
3. Run script
4. Close File-Script
After this you can't close yore document (helped only reload Photopea).
If you open anouther document and apply script - this problem manifests itself similarly...
Thanks.

**Comment by photopea** [comment]
I can not reproduce it.
