### ISSUE TITLE
 help i pressed random button stuff and I saw something that said disabled  then all my pictures are now pixelated

### ISSUE THREAD

**Issue by RodneyLopez999** [photopea/photopea#5681]

**Comment by photopea** [comment]
I have no idea what you mean by "pixelated". Photopea works with pixels, and if you zoom in, you will always see large pixels on your screen.

**Comment by MichalSZZ** [comment]
@RodneyLopez999  are you sure that you are not in zoom mode? Maybe you have used Alt+mouse wheel or Ctrl+ +. Try to zoom out with Ctrl+0.

**Comment by photopea** [comment]
I have to close it because of lack of details.
