### ISSUE TITLE
Firefly / Generative Fill Plans

### ISSUE THREAD

**Issue by smoore2171** [photopea/photopea#5682]
Generative Fill and Firefly seem to be the major upcoming feature in photoshop that would hinder this projects ability to compete moving forward. 
https://www.youtube.com/watch?v=IVTyLYupECI

Any plans to try and start taking this on? It seems like a pretty huge undertaking and assuming Firefly uses cloud services to do the actual AI work, that could be problematic for a free version like this if hardware requirements are high.

**Comment by camoody1** [comment]
Do you mean something like this?
https://youtu.be/X_jRqH0eKtE

**Comment by photopea** [comment]
We have added the Magic Replace tool into Photopea several weeks ago, did you try to look for it before asking? :D We posted about it on all our social channels.

**Comment by camoody1** [comment]
> We have added the Magic Replace tool into Photopea several weeks ago, did you try to look for it before asking? :D We posted about it on all our social channels.

Ahead of the curve!
![bitmoji](https://sdk.bitmoji.com/render/panel/3fb3b537-745f-4667-a6c3-e0c397eb19ad-33290fb4-ad75-46e6-8062-305f1f5378d9-v1.png?transparent=1&palette=1&width=246)

**Comment by smoore2171** [comment]
Named different so I guess I hadn't noticed it. Have we done any comparisons of its performance compared to Adobes? How large of a prompt does it support?

**Comment by smoore2171** [comment]
The CS feature of previewing a few options before committing to one is also potentially a nice to have add

**Comment by camoody1** [comment]
> Named different so I guess I hadn't noticed it. 
@photopea I told you that you should rename it. 😆

> Have we done any comparisons of its performance compared to Adobes?
"We"? I didn't know you worked with Ivan. 😁

> How large of a prompt does it support?
As long as you want to type. He recently added additional options to allow adding a Negative prompt and several other settings.

@photopea I think it would be a big GUI improvement to remove the small text line window you currently have available for a text prompt and replace it with a separate popup window (like your current advanced settings window) that has an expandable multi-line text entry for both the Positive Prompt AND Negative Prompt. If someone wants to ge very detailed in their request (like I like to), it's not very friendly to have to keep scrolling back and forth to view our entire prompt. 💖

**Comment by camoody1** [comment]
> The CS feature of previewing a few options before committing to one is also potentially a nice to have add

I agree. The problem is that each of these images is an API call to a third-party tool. And each call costs money. Sadly, Adobe has bottomless pockets to provide these extra images, while Photopea does not. Perhaps Ivan could place some of these more advanced options behind a "Premium Account" paywall. But that would probably upset a lot of people who don't understand how CPU intensive and expensive this AI images are to create.
