### ISSUE TITLE
lagging

### ISSUE THREAD

**Issue by TheHuskyShark** [photopea/photopea#5683]
like when i try making thumbnails cuz i dont wanna pay a lot of money on photoshop to make a thumbnail but when i try moving the pic it lags and when i put the pic into to make it the quality it terrible

**Comment by camoody1** [comment]
Would you please record a short video showing us what you're seeing and what you're doing when the lag hits? I can tell you that I do all sorts of editing with Photopea on my mobile phone and I don't see any lag unless I'm using a very high resolution images with one of the more complicated filters.

**Comment by photopea** [comment]
I think the person who posted this is less than 9 years old, and we will not be able to get any useful information from them, so I am closing it right away.

**Comment by TheHuskyShark** [comment]
hold on 9 year old excuse me bro ur closing this becuase u think im a 9 year old nah bro im 18 bro

**Comment by camoody1** [comment]
Bro... bro bro bro bro. Broooo.

Bro,
Bro

**Comment by TheHuskyShark** [comment]
what are u bro about dude

**Comment by camoody1** [comment]
![image](https://github.com/photopea/photopea/assets/73725653/9c47a325-2c92-43bc-a762-28b4b6005f39)

**Comment by TheHuskyShark** [comment]
-_-

**Comment by photopea** [comment]
Please, tell us, what should we do after opening www.Photopea.com to see the problem. Make sure these steps lead to the problem every time. We need to see the problem ourselves first, to be able to fix it.
