### ISSUE TITLE
Nothing is showing up

### ISSUE THREAD

**Issue by Castle1607** [photopea/photopea#5684]
I was using this one day then the next nothing show up none of the pictures or even the blank canvas. please help.

**Comment by Castle1607** [comment]
![Untitled](https://github.com/photopea/photopea/assets/134254986/3f28595d-f1ed-432b-b34a-f97a1e0a57c1)

**Comment by photopea** [comment]
I guess it is not at www.Photopea.com ? Does the same happen at www.Photopea.com ? Does it happen every time when you use it? So it is broken permanently now?

**Comment by photopea** [comment]
Did you try to close it and open it again? Did it help?

**Comment by camoody1** [comment]
@Castle1607 You don't have any layers set to be viewable in your layers window. You even have your Background layer set to not show.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
