### ISSUE TITLE
Stroke path says "Layer is not editable"

### ISSUE THREAD

**Issue by MorganMode** [photopea/photopea#5685]
When creating a stroke path with a rectangle, it creates the shape. I then right-click to stroke and it gives the error "Layer is not editable."

**Comment by photopea** [comment]
What is "creating a stroke path with a rectangle"?

**Comment by MorganMode** [comment]
Using the shape tool in a rectangle with no fill and only stroke.

**Comment by MichalSZZ** [comment]
Maybe you are on "non empty" layer like a text layer, smart object, or locked layer. Be sure that you are on a new - empty layer, in the layers palette.

**Comment by camoody1** [comment]
@MichalSZZ Have you tried it yourself? I ran into the same issue the OP is describing. It's entirely possible that I was doing something wrong, but I checked all the obvious things to me.🤷🏽‍♂️

**Comment by MichalSZZ** [comment]
@camoody1 YES - to do a proper stroke of a path - you should use shape tools but in the "path" mode, not shape.
![obraz](https://github.com/photopea/photopea/assets/38118273/0897f753-ccf8-43ba-b604-ef55f12615f0)
When you are drawing the shape in a shape mode, the new layer with shape will appear and you can't stroke that path on the same (shape) layer. Stroke is a raster operation it can't be added to the shape (vector) layer.

**Comment by MichalSZZ** [comment]
In Photoshop you can't do such a thing - this option is greyed out:
![obraz](https://github.com/photopea/photopea/assets/38118273/93b40a52-9927-4a6c-9df4-7ac0754f17f5)

**Comment by photopea** [comment]
If you are talking about Edit - Stroke, it is a raster operation, and can be done only on raster layers.

Draw a working path (Path mode) and then, select a raster layer and your path, and you can stroke it.

**Comment by MichalSZZ** [comment]
But @photopea maybe you can gray out this option too, like in Photoshop? If something is impossible to do, it shouldn't be active as an option.

**Comment by photopea** [comment]
Ok, I just did :) Edit - Fill and Edit - Stroke are active only when a "paintable" layer is selected :)

**Comment by photopea** [comment]
done :)
