### ISSUE TITLE
writing tool glitch

### ISSUE THREAD

**Issue by abdeGR** [photopea/photopea#5686]
When you press the write button and write, the image you are writing on will turn into pixels please fix it

**Comment by camoody1** [comment]
@abdeGR I don't have any problems when using the Text Tool on my devices. Could you please create a video to show us exactly what you're doing when this occurs? We need to be able to recreate this problem in order to fix it.

**Comment by photopea** [comment]
Could you share a screenshot of the problem? I need some proof, or some steps how can I see it myself.

**Comment by photopea** [comment]
I have to close it because of lack of details.
