### ISSUE TITLE
Http request API response, is it possible?

### ISSUE THREAD

**Issue by xpcoder123** [photopea/photopea#5689]
Hey there,

Ive been reading through API documentation and how you can form a json query and pass it as a parameter in the url and Photopea executes and applies it. Even passing post request server url where Photopea will save the file result. It works fine through the browser, but is there any possibility to make requests outside the browser? like writing a php code or js that would execute the url and get a response back via http? If yes, can you please provide some details?

Thank you

**Comment by photopea** [comment]
Photopea is written in Javascript, not in PHP. We distribute it as a program that needs to run in a browser.

Our server is not capable of executing Javascript as a browser does. Also, doing it for you would drain the resources (CPU, RAM) of our server (now, it drains the computer on which it is running). Maybe you know how to run Javascript (Photopea) on your own server?

**Comment by photopea** [comment]
I will close it, as I think our current API should be enough.
