### ISSUE TITLE
Font size, color not change-able once put down the cursor/create the layer

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#569]
Usually one would put down the text cursor First (for showing its size) to determine what font size to choose based on the elements around them, how much space is left. 

But right now it's reversed, one can only have a close guess first, type out the whole content, confirm, Then finally adj its size.

**Comment by photopea** [comment]
Once you enter a text layer, you must select the text, that you want to re-style. If there is only a cursor (zero characters selected), the style of those 0 characters will be changed.
https://www.photopea.com/learn/text-layers

**Comment by hgs54371** [comment]
The text cursor height is not updating with the font size for previewing, and often times the font size just jump back when there's only a cursor

**Comment by photopea** [comment]
When no text is selected (and a text layer entered), changing style has no meaning.

**Comment by hgs54371** [comment]
After entering text layer, the adjusted font size, color is for the following typed out text to adopt.
This is behave correctly right now, but when this post was created, these adjustments would just jump back to the setting it was When entering text layer.

The only problem for now is that the Text Cursor is not blinking (just like HERE), and also it is not updating with the current size, it stays the size it was when entering text layer, so there's a problem with huge cursor typing out tiny text, or reversed
