### ISSUE TITLE
It is just me? or...something wrong with the website.

### ISSUE THREAD

**Issue by Tor-orge** [photopea/photopea#5690]
![Screen page mess up](https://github.com/photopea/photopea/assets/134862799/b545dc62-1c48-49c4-9787-1a7f968f7d73)
![k](https://github.com/photopea/photopea/assets/134862799/e968227d-ebc0-4a1b-a02e-43acaab018c4)
(Web page and other messed up)

**Comment by Tor-orge** [comment]
And also, I can't even use photopea because how messy web page it was

**Comment by camoody1** [comment]
It looks like it's just you, sir (or madam). 

I've been working in Photopea all day without any issues. And I just double checked it, again, now and it's still fine. If this had been a website issue, we would have seen a lot of people reporting the same issue as you. But it seems that you're the only person with this problem. Is it still looking weird for you? Perhaps try opening Photopea in In Cognito (Private) Mode to ensure there are no browser extensions causing problems.

**Comment by photopea** [comment]
You just need two things to use Photopea
- a modern, updated web browser
- no browser extensions, which modify the look of websites

I am sure that you are missing one of these two points. Please, tell us the name and the version of your web browser, and a screenshot of the list of your browser extensions.

**Comment by Tor-orge** [comment]
> It looks like it's just you, sir (or madam).
> 
> I've been working in Photopea all day without any issues. And I just double checked it, again, now and it's still fine. If this had been a website issue, we would have seen a lot of people reporting the same issue as you. But it seems that you're the only person with this problem. Is it still looking weird for you? Perhaps try opening Photopea in In Cognito (Private) Mode to ensure there are no browser extensions causing problems.

Thanks for giving me a solution, Now i can use a photopea like mostly people do :D

**Comment by Tor-orge** [comment]
> You need two things to use Photopea
> 
> * a modern, updated web browser
> * no browser extensions, which modify the look of websites
> 
> I am sure that you are missing one of these two points. Please, tell us the name and the version of your web browser, and a screenshot of the list of your browser extensions.

Atleast, it worked on cognito mode.

**Comment by camoody1** [comment]
@Tor-orge If it worked in In Cognito Mode, that means your regular mode has a browser extension that's causing you problems. You could disable all of your extensions and then add them back one at a time while testing Photopea to see which one is the problem.

**Comment by photopea** [comment]
Browser extensions know about every website that you visit, every image that you look at, every character that you ever type (in all websites). It is useful to know how many of them you have.

**Comment by Tor-orge** [comment]
[photopea](https://github.com/photopea)You don't have to forcing me to tell for "How many google extension do i have" like, it's already been fixed by me and the regular mode too by just deleting all of my google extension and clear all cached images and files as well.
![Proving](https://github.com/photopea/photopea/assets/134862799/9e6e3a50-3386-416e-80a7-b57a89730524)
