### ISSUE TITLE
Copy and paste doesn't work

### ISSUE THREAD

**Issue by crobertwatson** [photopea/photopea#5691]
I'm doing a simple rectangle select followed by Cmd+C, then opening a new project and using Cmd+V to paste the selection into it. When I do Cmd+V, nothing appears on the canvas. Also, there's nothing in the History tab to indicate that Photopea is doing any copy or paste operation. This is with the standalone app. When I do the same process on the Photopea website version of the tool, the copy-and-paste function works as expected.

**Comment by camoody1** [comment]
Hmm. I just tried this in Windows (using the installed webapp) and it worked just fine. Starting with an empty canvas, I switched to the Shape Tool, created a simple rectangle, immediately pressed CTRL-C, opened a new project, and immediately pressed CTRL-V. The rectangle pasted correctly. Obviously, Windows isn't the same as Mac, but at least we know the basic process is still working correctly.

Maybe @photopea can assist you on the Mac side if you're still experiencing this issue.

**Comment by photopea** [comment]
Did you install Photopea by pressing More - Install Photopea in the menu? In what web browser did you do that?

If you downloaded something called "Photopea" from the internet, it is not our Photopea.

**Comment by crobertwatson** [comment]
@photopea It's solved now. I was using the Brave (Chromium-based) browser initially. I had already uninstalled Photopea, so in Brave when I went to More > Install PhotoPea it was grayed out. I tried it again using a regular Chrome browser and More > Install PhotoPea wasn't grayed out. I installed it from Chrome. This time when I tried the copy/paste process there was a MacOS permissions dialogue asking for permission to use copy/paste, which I allowed. Now it works fine. So something about the Brave browser didn't trigger that dialogue, which was the likely cause of the problem.

**Comment by photopea** [comment]
We do not consider the Brave to be a web browser, as it breaks several crucial web standards.

E.g. here: https://github.com/brave/brave-browser/issues/17850

In short, you should use Brave, if you like pain, as it is going to waste at least an hour of your life each month of using it (just like it did in this case). There could be more websites which did not work for you, but you did not think it could be caused by Brave.

**Comment by photopea** [comment]
If a certain behaviour or a feature is useful to have in a web browser, all web browsers would do it automatically.

All that "security privacy protection thing" is pretty much the marketing of Brave, it does not give you any significant extra protection. 

It is like buying a phone with a 1-month battery, but you realize weighs is 3 pounds only after months of using it.

**Comment by crobertwatson** [comment]
That argument ignores conflicts of interest between browser vendors, like Google, and actually caring enough about user privacy to implement those features. They've stood to lose money around the ability to track ads for analytics purposes when cookies are automatically disabled unless a user chooses to enable them. In an ethical corporate and open web partnership paradigm, that should have been the default from day one the first time cookies were seen to cause privacy issues. But it wasn't because the browser vendors found them too lucrative. Firefox has added some curbs on privacy violations, but Brave was the earliest to break the most ground. Now Google is [stumbling around trying to play catch up](https://www.wired.com/story/google-floc-cookies-chrome-topics/) but still looking out for its own interests. Browsing with Brave has saved me from being tracked by 285,752 trackers & ads and has saved me many GB and hours of loading time. But this is off-topic for this thread.
