### ISSUE TITLE
putClass not added in ActionDescriptor

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5692]
Hi!

```
var desc = new ActionDescriptor();
var idNw = charIDToTypeID( "Nw  " );
var idChnl = charIDToTypeID( "Chnl" );
desc.putClass( idNw, idChnl );
```

give error:
**Uncaught putClass in pp.js:10423**

**Comment by photopea** [comment]
Hi, could you provide a script which does something interesting, for me to test it?

**Comment by Pt-home** [comment]
I'm not near computer now, but all scripts create Rastrize Mask started with this code. Give me pair hours

**Comment by Pt-home** [comment]
// =======================================================
var idMk = charIDToTypeID( "Mk  " );
    var desc505 = new ActionDescriptor();
    var idNw = charIDToTypeID( "Nw  " );
    var idChnl = charIDToTypeID( "Chnl" );
    desc505.putClass( idNw, idChnl );
    var idAt = charIDToTypeID( "At  " );
        var ref106 = new ActionReference();
        var idChnl = charIDToTypeID( "Chnl" );
        var idChnl = charIDToTypeID( "Chnl" );
        var idMsk = charIDToTypeID( "Msk " );
        ref106.putEnumerated( idChnl, idChnl, idMsk );
    desc505.putReference( idAt, ref106 );
    var idUsng = charIDToTypeID( "Usng" );
    var idUsrM = charIDToTypeID( "UsrM" );
    var idTrns = charIDToTypeID( "Trns" );
    desc505.putEnumerated( idUsng, idUsrM, idTrns );
executeAction( idMk, desc505, DialogModes.NO );

// =======================================================
var idMk = charIDToTypeID( "Mk  " );
    var desc510 = new ActionDescriptor();
    var idNw = charIDToTypeID( "Nw  " );
    var idChnl = charIDToTypeID( "Chnl" );
    desc510.putClass( idNw, idChnl );
    var idAt = charIDToTypeID( "At  " );
        var ref108 = new ActionReference();
        var idChnl = charIDToTypeID( "Chnl" );
        var idChnl = charIDToTypeID( "Chnl" );
        var idMsk = charIDToTypeID( "Msk " );
        ref108.putEnumerated( idChnl, idChnl, idMsk );
    desc510.putReference( idAt, ref108 );
    var idUsng = charIDToTypeID( "Usng" );
    var idUsrM = charIDToTypeID( "UsrM" );
    var idRvlA = charIDToTypeID( "RvlA" );
    desc510.putEnumerated( idUsng, idUsrM, idRvlA );
executeAction( idMk, desc510, DialogModes.NO );

// =======================================================
var idMk = charIDToTypeID( "Mk  " );
    var desc515 = new ActionDescriptor();
    var idNw = charIDToTypeID( "Nw  " );
    var idChnl = charIDToTypeID( "Chnl" );
    desc515.putClass( idNw, idChnl );
    var idAt = charIDToTypeID( "At  " );
        var ref110 = new ActionReference();
        var idChnl = charIDToTypeID( "Chnl" );
        var idChnl = charIDToTypeID( "Chnl" );
        var idMsk = charIDToTypeID( "Msk " );
        ref110.putEnumerated( idChnl, idChnl, idMsk );
    desc515.putReference( idAt, ref110 );
    var idUsng = charIDToTypeID( "Usng" );
    var idUsrM = charIDToTypeID( "UsrM" );
    var idHdAl = charIDToTypeID( "HdAl" );
    desc515.putEnumerated( idUsng, idUsrM, idHdAl );
executeAction( idMk, desc515, DialogModes.NO );

// =======================================================
var idMk = charIDToTypeID( "Mk  " );
    var desc534 = new ActionDescriptor();
    var idNw = charIDToTypeID( "Nw  " );
    var idChnl = charIDToTypeID( "Chnl" );
    desc534.putClass( idNw, idChnl );
    var idAt = charIDToTypeID( "At  " );
        var ref114 = new ActionReference();
        var idChnl = charIDToTypeID( "Chnl" );
        var idChnl = charIDToTypeID( "Chnl" );
        var idMsk = charIDToTypeID( "Msk " );
        ref114.putEnumerated( idChnl, idChnl, idMsk );
    desc534.putReference( idAt, ref114 );
    var idUsng = charIDToTypeID( "Usng" );
    var idUsrM = charIDToTypeID( "UsrM" );
    var idHdSl = charIDToTypeID( "HdSl" );
    desc534.putEnumerated( idUsng, idUsrM, idHdSl );
executeAction( idMk, desc534, DialogModes.NO );

// =======================================================
var idMk = charIDToTypeID( "Mk  " );
    var desc545 = new ActionDescriptor();
    var idNw = charIDToTypeID( "Nw  " );
    var idChnl = charIDToTypeID( "Chnl" );
    desc545.putClass( idNw, idChnl );
    var idAt = charIDToTypeID( "At  " );
        var ref117 = new ActionReference();
        var idChnl = charIDToTypeID( "Chnl" );
        var idChnl = charIDToTypeID( "Chnl" );
        var idMsk = charIDToTypeID( "Msk " );
        ref117.putEnumerated( idChnl, idChnl, idMsk );
    desc545.putReference( idAt, ref117 );
    var idUsng = charIDToTypeID( "Usng" );
    var idUsrM = charIDToTypeID( "UsrM" );
    var idRvlS = charIDToTypeID( "RvlS" );
    desc545.putEnumerated( idUsng, idUsrM, idRvlS );
executeAction( idMk, desc545, DialogModes.NO );

**Comment by photopea** [comment]
it should be fixed now :)
