### ISSUE TITLE
cant use control+ touchpad to see menu

### ISSUE THREAD

**Issue by noahshogan** [photopea/photopea#5694]
i was able to use this few days ago now i cant use control key plus touchpad click 

im using macos 
i tried it on several browsers( Brave, Chrome, Safari)
i tried to clear cookies and cache 

and yet im unable to use this combination anymore.

**Comment by photopea** [comment]
Do you mean the Ctrl+click shortcut to select the layer? Maybe you used the Command + click before?

**Comment by photopea** [comment]
So you want the Control + click work as a right click in Photopea? I think it depends on the settings of your system, there is nothing we can do about it in Photopea.

**Comment by photopea** [comment]
I just tried it on my macbook. Ctrl+click (on a touchpad or with a mouse) works as a right-click on a desktop.

However, in Photopea, Ctrl and Command work identically. Ctrl+click works as Command+click (and not as a right click). To do a right click in Photopea, I need to connect my mouse, or click with two fingers on a touchpad.

@radicaldreamer Do you have Photoshop on a mac? Could you tell us, if Ctrl+click works as a right click, or as Command+click in it?

**Comment by MichalSZZ** [comment]
@photopea  Ctrl+Click works like a Right Mouse Button in Photoshop on Mac. Cmd + Click works like Ctrl+ Click on Windows.

**Comment by noahshogan** [comment]
@photopea Thanks a lot! now its working again.
