### ISSUE TITLE
loading too long 

### ISSUE THREAD

**Issue by HarveyChiu** [photopea/photopea#5698]
loading for 2 hours. It's too long.
I can't do my job 
please assist me ！！！
![擷取](https://github.com/photopea/photopea/assets/135017033/67150c77-861a-4da4-9522-f6c435bc2bbb)

**Comment by photopea** [comment]
Are you trying to open a file in Photopea? Could you share that file with us?

I need to see the error myself, on my computer.

**Comment by senakiraz** [comment]
I have the same issues.. I tried 3-4 different mockups but it doesnt load

**Comment by camoody1** [comment]
> Could you share it with us? Is it named "action-video-game-3d-text-style-effect.zip" ?

Haha. That thing takes forever to open. And the smart object inside is even slower. Just a huge image.

**Comment by BarbaraDoganieri** [comment]
I have the same problem, any suggestion?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
