### ISSUE TITLE
Corner radius doesn't work on rectangle shape

### ISSUE THREAD

**Issue by JessMTermini** [photopea/photopea#5699]
I'm running the latest version of Chrome. Since there is no elliptical tool (unless there is one somewhere that I just can't find), we have no choice but to rely on the corner radius option for rectangles, but changing the radius/adding a radius doesn't do anything so I am stuck with only rectangular designs lol...just wanted to let someone know. Thank you.

**Comment by MichalSZZ** [comment]
![obraz](https://github.com/photopea/photopea/assets/38118273/7144d135-18e3-4e81-810a-1546567a32b6)
you don't see that tool here on your Photopea version?

you can do an ellipse that is a perfect circle: 

- with holding the Shift button,
- by clicking a left mouse button and a new window will pop up

![obraz](https://github.com/photopea/photopea/assets/38118273/7bec20c4-d50b-4efd-807e-b5e3d36bfa17)

Changing square to circle in the properties window works well for me.

**Comment by photopea** [comment]
You can learn how to use the toolbar here: https://www.photopea.com/learn/workspace

The options of each tool (at the top) have the properties of FUTURE OBJECTS (which you will draw). E.g. if you draw a black line, and you set the opacity to 50% at the top, your line will not become transparent. But future lines will become.

If you want to change the properties of existing objects, press Window - Properties.

**Comment by JessMTermini** [comment]
I am actually not sure what happened here because I am a seasoned photoshop user, and I remember looking for and trying to open the toolbar icons to check for and enable other toolbar options like the ellipse you mention, however, this was so long ago and I cannot go back to see what actually was happening, but on re-opening a new project tab today it seems to be back and showing up somehow. So oh well, as long as it's working now. Maybe it was a one time browser window glitch from low ram or something who knows, cause I am on a limited ramn chromebook at the moment. 

One thing I did found VERY cool. And I don't know if this is actually a glitch or was meant to happen thing way. But upon clicking to open a new project it straight away opened my last project I had been working on, which I wasn't expecting. So had that document actually been very important (this one was not it was just a simple tester file for something I was working on) it could have saved me a lot of hassle had I not saved it properly or any number of reasons. So kudos for that!!

**Comment by camoody1** [comment]
That's a purposely done feature Ivan added several months ago. It's an "autosave" feature of sorts for people who accidently would close out of their browser without saving. If you save everything before closing Photopea, the next time you open the app, it should not open any projects.

It's definitely been a big help for many.

**Comment by photopea** [comment]
Thanks! Yes, Photopea saves all unsaved projects as temporary files to your hard drive every 5 minutes (through IndexedDB).

If you close the project properly (with the "X" button), the temporary file is deleted from your hard drive.

If Photopea is closed without closing documents properly (e.g. your battery dies), and you start Photopea again, Photopea looks for these temporary files on your hard drive, and re-opens them, if it finds any.
