### ISSUE TITLE
CTRL+T for free transform opens new tab in Chrome

### ISSUE THREAD

**Issue by tomasnosek** [photopea/photopea#57]

**Comment by photopea** [comment]
That is a bug in Chrome, which I can not solve :(  See 
https://bugs.chromium.org/p/chromium/issues/detail?id=321810
https://bugs.chromium.org/p/chromium/issues/detail?id=119881  for more details.

If you really need to use Ctrl+T for a free transform, use some better borwsers, like Firefox or Internet Explorer.

**Comment by tomasnosek** [comment]
you will solve this by solving #54
