### ISSUE TITLE
 It's really dishonest (HSB/HSL)

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5702]
Hi! It's really dishonest;) 
Why is the simplest operation, with two primitive parameters, with the "unchanged" classic charid...
![image](https://github.com/photopea/photopea/assets/29394245/0d3981e8-848f-4a54-860c-b5f108781793)

1) **not added to Action**
2) **and doesn't run through the damn descriptor!**
var idHsbP = charIDToTypeID( "HsbP" );
    var desc = new ActionDescriptor();
    
    var idInpt = charIDToTypeID( "Inpt" );
    var idClrS = charIDToTypeID( "ClrS" );
    var idHSBl = charIDToTypeID( "HSBl" );
    desc.putEnumerated( idInpt, idClrS, idHSBl );
    
    var idOtpt = charIDToTypeID( "Otpt" );
    var idClrS = charIDToTypeID( "ClrS" );
    var idRGBC = charIDToTypeID( "RGBC" );
    desc.putEnumerated( idOtpt, idClrS, idRGBC );

executeAction( idHsbP, desc, DialogModes.NO );

![image](https://github.com/photopea/photopea/assets/29394245/e1c535eb-245f-4e8b-8441-be417ec1665f)
 It's really dishonest;)

**Comment by photopea** [comment]
I am afraid I do not understand. What exactly is the problem?

**Comment by Pt-home** [comment]
Problem - this script no working:
var idHsbP = charIDToTypeID( "HsbP" );
var desc = new ActionDescriptor();

var idInpt = charIDToTypeID( "Inpt" );
var idClrS = charIDToTypeID( "ClrS" );
var idHSBl = charIDToTypeID( "HSBl" );
desc.putEnumerated( idInpt, idClrS, idHSBl );

var idOtpt = charIDToTypeID( "Otpt" );
var idClrS = charIDToTypeID( "ClrS" );
var idRGBC = charIDToTypeID( "RGBC" );
desc.putEnumerated( idOtpt, idClrS, idRGBC );

executeAction( idHsbP, desc, DialogModes.NO );

**Comment by photopea** [comment]
fixed! :)

**Comment by Pt-home** [comment]
Wow, I learned so much new things about Photopia thanks to this little bug, but I still couldn’t understand why the HSB was not launched by the script)) We see the world from the other side)) It was a memorable quest))
