### ISSUE TITLE
Layer styles missing or strange - blending effects not working?

### ISSUE THREAD

**Issue by kristianbro** [photopea/photopea#5703]
How the image should look vs how it looks when I open it in Photopea.

How it should look ![Metatone - TV Ad Style - December 2022 - 1200x1200](https://github.com/photopea/photopea/assets/73835902/9416b62b-f57a-4d03-99bc-aaa6485fb89a)
How it looks when the PSD file is opened ![Metatone - TV Ad Style - December 2022 - 1200x1200](https://github.com/photopea/photopea/assets/73835902/1e0d5c84-3341-406b-b84a-a432bbfdd3d1)

Gradients on the bubbles in the background have gone.

Have tried clearing my cache, incognito mode, updating my browser (latest edition of Chrome Version 114.0.5735.91 (Official Build) (64-bit)) logged in and logged out.

**Comment by photopea** [comment]
Could you share your PSD file with us?

**Comment by kristianbro** [comment]
This is the template which used to work fine but as of this week it no longer displays properly when opened. This template is made in Photoshop then opened up in Photopea. No issues with this before this week: https://drive.google.com/file/d/1rkD_18WHY0TCR8ppOcMbDVHSDm7Ie30h/view?usp=sharing

We found a workaround whereby we have to convert the bubbles to an object and rasterize the layer styles in Photoshop. Then when opening in Photopea the layers appear as intended.

**Comment by photopea** [comment]
I am very sorry, it should be fixed now.

There is no need for any workaround. All PSD files should look in Photopea the same as in Photoshop (if not, let us know and we will fix it).

**Comment by kristianbro** [comment]
Thanks!

**Comment by camoody1** [comment]
@kristianbro Is that PSD working correctly for you, now? I refreshed Photopea and reopened the PSD you linked, but it still looks the same to me. No gradients.

Maybe I need to wait a while for the changes to take effect.🤷🏽‍♂️

**Comment by kristianbro** [comment]
Yes, just tried in incognito and all good :)

**Comment by camoody1** [comment]
@kristianbro Oh, I see. It's the Bevel that creates a "gradient".

Have a great day!

**Comment by photopea** [comment]
www.Photopea.com has a 1-hour caching. When your browser loads it from our server, it saves Photopea in your computer for the next hour. So if you open Photopea again during the next hour, it loads it from your computer (not from our server).

E.g. you load Photopea at 10:37 and you see a version A. We upload a new version B at 10:51. You open Photopea at 10:55 - you see a version A (from your computer). You open it at 11:25 - still a version A (from your computer). You open it at 11:40 and you see a new version B (loaded from our server, which is stored again to your computer, replacing the version A, and will be used for the next hour - until 12:40).

To force your browser to load a website a server, you can e.g.:
- clear the cache manually
- do a hard-reload (Shift+F5 in Chrome)
- open it in the Incognito
- open it in a different browser / different device (which did not open Photopea in the last hour, so it is not cached there)

**Comment by photopea** [comment]
@camoody1 that PSD had no gradients, it was an error with rendering the Bevel and Emboss style.
