### ISSUE TITLE
.gif export preview is playing at incorrect speed in certain cases when using Chrome

### ISSUE THREAD

**Issue by cow1337killer3** [photopea/photopea#5704]
This is in continuation of #5266 

I noticed that the bug is still here, and did some more testing. 

In Chrome, it turns out the exported gif file is actually at the correct speed, it's just that the preview gif in the export window is sometimes at the incorrect speed. Here's some scenarios:
* When exporting at 100% speed, the preview gif is playing at the correct speed.
* When exporting at 50% speed, the preview gif is playing **faster** than the exported file. With a 10 second long gif, I noticed the preview gif plays about 5 times for every 4 times the actual exported gif plays.
* When exporting at 150% speed, the preview gif is playing **slower** than the exported file. With a 10 second long gif, I noticed the preview gif plays about 8 times for every 9 times the actual exported gif plays.

I would guess that it's not an issue with Chrome lacking the compute resources, since changing the speed in the export window will subsequently change the speed of the preview. I guess it must be something with the Chrome engine.

In Firefox, the scenarios are all the same, except that the amount of speed the preview gif is off by is _very very very_ small. At 50% speed, the preview plays much closer to the correct speed, but I noticed that it was still slightly different after about 30 seconds or so. But the difference is almost imperceptible to the naked eye, which would make it totally fine for the purposes of "previewing" something.

**Comment by photopea** [comment]
it should be fixed now :)
