### ISSUE TITLE
Won't paste image

### ISSUE THREAD

**Issue by osb21313** [photopea/photopea#5706]
It can't paste images for me.

**Comment by photopea** [comment]
What exactly do you mean by "paste images"? The basic process is to press File - Open, and open a file from your computer.

**Comment by SoroushMehraban** [comment]
I have the same issue. When I use Rectangle select (M) and copy (or cut) a portion of image, the pasting operation (ctrl + V or edit -> paste) does not work.

**Comment by photopea** [comment]
try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by discgolfer5000** [comment]
Hello, I have had the same copy & paste issue many times on Chrome and Windows 10. Incognito mode and disabling real-time antivirus did not help. I just found the solution, which is to allow Photopea clipboard permissions in your web browser!

Problem: Copy (Ctrl+C) works fine in Photopea but I paste from the menu or by using Ctrl+V, nothing happens. However, I can immediately swap windows over to MS Word and paste the image over there just fine.

Clue: I tried the same thing in Brave and got a browser pop up "Share clipboard?" Allow or Block. Choosing Allow resolved the issue! 
![image](https://github.com/photopea/photopea/assets/89740372/98374e36-6fe4-41e6-ae0f-7d75a8887711)

Solution: Back over in Chrome, I noticed to the right of the URL, there is a clipboard icon with a red X on it, meaning clipboard permissions are blocked. It's very subtle. Just click on that icon, then choose to Allow Photopea access to the clipboard.
![image](https://github.com/photopea/photopea/assets/89740372/21e68408-51e2-4532-ba92-15127d4d273e)

**Comment by SoroushMehraban** [comment]
> Hello, I have had the same copy & paste issue many times on Chrome and Windows 10. Incognito mode and disabling real-time antivirus did not help. I just found the solution, which is to allow Photopea clipboard permissions in your web browser!
> 
> Problem: Copy (Ctrl+C) works fine in Photopea but I paste from the menu or by using Ctrl+V, nothing happens. However, I can immediately swap windows over to MS Word and paste the image over there just fine.
> 
> Clue: I tried the same thing in Brave and got a browser pop up "Share clipboard?" Allow or Block. Choosing Allow resolved the issue! ![image](https://user-images.githubusercontent.com/89740372/265237122-98374e36-6fe4-41e6-ae0f-7d75a8887711.png)
> 
> Solution: Back over in Chrome, I noticed to the right of the URL, there is a clipboard icon with a red X on it, meaning clipboard permissions are blocked. It's very subtle. Just click on that icon, then choose to Allow Photopea access to the clipboard. ![image](https://user-images.githubusercontent.com/89740372/265237157-21e68408-51e2-4532-ba92-15127d4d273e.png)

Thanks! It works now.

**Comment by photopea** [comment]
To let Photopea access your clipboard, you should let Photopea access your clipboard. This should not be a surprise :D

I think your browser asked you about allowing Photopea access you clipboard in the past, but you clicked "Block", so it did not ask again.
