### ISSUE TITLE
Adjustment layer is applied hundred times in pattern view

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5707]
[Patrón de Caras2.zip](https://github.com/photopea/photopea/files/11557423/Patron.de.Caras2.zip)

If you go to pattern view, the adjustment layer is applied hundred of times, so you cannot see the proper created pattern

![image](https://github.com/photopea/photopea/assets/11801254/6c227f6f-2149-4886-966d-0a5281acd986)
![image](https://github.com/photopea/photopea/assets/11801254/6f4a146b-0c16-43a6-8ef9-bfea7e8e4bfc)

**Comment by photopea** [comment]
fixed! :)
