### ISSUE TITLE
Index color Mode and Table color

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5708]
It will be possible to add this mode on Photopea?
![image](https://github.com/photopea/photopea/assets/11801254/3a62bee1-c1ef-4fc7-9b91-5f84fda048f3)

video explaining the whole mode and its potencial: https://www.youtube.com/watch?v=WcSQG-M8afk

With this i can control the amount of colors when i am working with pantone printing and other methods of print.

It will be great addition to have for people that work priting!

**Comment by photopea** [comment]
Hi, you can do a very similar thing using Image - Reduce Colors in Photopea.

**Comment by TheRadicalDreamer** [comment]
Yes, but i cannot tinker which colors combine or which colors i prefer to change o keep

**Comment by photopea** [comment]
The Reduce Colors should pick the best colors possible automatically. I dont think there is a need of a special color mode.

**Comment by photopea** [comment]
Now, you can choose your own colors in Image - Reduce Colors.
