### ISSUE TITLE
Cannot delete layers with delete key within text tool

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#571]
Have to switch to move tool first, which is an extra step

**Comment by photopea** [comment]
I manually made Delete and Backspace keys exclusive for the Type Tool (so no sortcuts containing Delete or Backspace can run, when Type tool is on). But I don't remember why :(

So I removed them from "exclusive" list and you can use all shortcuts normally now.

**Comment by hgs54371** [comment]
I've found when delete text in text layer with cursor selection, the layer itself is also deleted

**Comment by photopea** [comment]
@hgs54371  Can you please be more precise, how to reproduce it? I just tried to delete text with Delete in a text layer, and it never deletes the layer itself.

**Comment by hgs54371** [comment]
Type out multiple lines of text, click out in layers panel to confirm, re-enter that layer by click on those text, drag select a chunk of text, hit delete, the layer itself is also deleted.

On a mac keyboard there's only a delete key, and no backspace key

**Comment by photopea** [comment]
I tried it and it does not delete a layer. Maybe it is Mac-specific? Can you record a short video?

**Comment by hgs54371** [comment]
This is specific to firefox on mac,

I've reduced it to this,
Basically every deletion of text with a cursor Drag Select will also delete the layer

[testt.mp4.zip](https://github.com/photopea/photopea/files/1864586/testt.mp4.zip)

**Comment by photopea** [comment]
Are you using the latest Mac OS and browsers?

**Comment by hgs54371** [comment]
They're both updated

**Comment by photopea** [comment]
So I made Delete and Backspace exclusive to the Type tool. Maybe that was the original reason. How does it work now?

**Comment by hgs54371** [comment]
The layer deletion issue is gone, but now Drag Selected text often need two delete hit for it to delete, this seems to be specific to firefox also

**Comment by hgs54371** [comment]
The delete key is not functioning again within text tool for delete layers in layers panel

**Comment by photopea** [comment]
It seems like a bug in Safari or Mac OS (because it works fine in other browsers and OSs). Please report it to Apple.

**Comment by hgs54371** [comment]
This is also in firefox, it Was fixed, have you just changed something that make it not functioning again

**Comment by photopea** [comment]
As I remember, now, it can delete text, but not delete layer. Before, you could delete layer, but if you deleted text, it also deleted layer.

**Comment by photopea** [comment]
Ok, I returned it back. You should be able to delete layers with the Delete key with any tool. Does it work well now?

**Comment by photopea** [comment]
Hi, I made this demo: https://jsfiddle.net/0sv94ycr/3/

Enter the text area and type. Try Delete and Backspace. You should see the alert "Escape" when you hit Escapbe, but not for any other key. Does it work that way?

**Comment by hgs54371** [comment]
Everything works as described, esc also shows, no issue for now

**Comment by hgs54371** [comment]
Press delete key don't show "Escape!"

**Comment by photopea** [comment]
So does it delete a layer, when you select and delete text in Photopea? With the same browser and OS?

**Comment by hgs54371** [comment]
Only the 1st drag select delete after a one by one delete is normal, otherwise it deletes the layer also

**Comment by photopea** [comment]
I don't understand. Shouldn't your last sentence be two sentences?

**Comment by hgs54371** [comment]
That is just a situation where drag-select-delete didn't also delete layer itself, there are others, but most of the time drag-select-delete still also delete layer itself

**Comment by photopea** [comment]
But have you tried to do the same thing in the JSFiddle demo? Select text and delete it with the Delete key?

**Comment by hgs54371** [comment]
I tried same thing in both, in that demo no issue, in PP issue still.

I also found cmd-z undo is not working for undo "delete text also delete layer" this action, 
In the video I showed earlier, undo is working for this action

**Comment by photopea** [comment]
I really don't know what to do with it, since I can not reproduce with my browser and OS. Maybe just use another browser, which works. Once people start using other browsers, the authors of your broken browser would notice, that something is wrong, and would actually fix it.

**Comment by hgs54371** [comment]
Can't delete layer in text tool in more tolerable, so for now keep it exclusive is better than layer got deleted with text

**Comment by photopea** [comment]
Can you try it again to delete selected text in a text layer? It should print some words in a console. Can you show us what did it print?

**Comment by hgs54371** [comment]
This is the console, nothing else printed

![screen shot 2018-04-09 at 8 53 07 am](https://user-images.githubusercontent.com/36803688/38474601-7e41a362-3bd3-11e8-84b1-f079d028005d.jpg)

**Comment by photopea** [comment]
Did you delete a layer with pressing Delete before taking this screenshot?

**Comment by hgs54371** [comment]
"Delete layer with delete", "got layer deleted with text delete" these two things do nothing extra to the console

**Comment by photopea** [comment]
They should print "body" or something else into the console.

**Comment by hgs54371** [comment]
Indeed nothing, it's less annoying than delete layer with text, keep it exclusive would be better
