### ISSUE TITLE
Export vector to PDF takes too long

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5710]
I draw 2 images of a woman.

Both were vectorized via the Image to Vector tool.

But one can be exported to PDF and the other takes too much time, or sometimes doesn't even export at all.

I have tried multiple times to vectorize the image differently, with different options, and nothing.

I believe it has something to do with the shape of the illustration. Because, even if both are pretty similar, one makes Photopea to hang up and takes too long to process and the other export immediately. 

Here are both PSD, try to export them:
[Archive.zip](https://github.com/photopea/photopea/files/11641640/Archive.zip)

Thank you in advance @photopea

**Comment by Pt-home** [comment]
[Impossible to export.pdf](https://github.com/photopea/photopea/files/11641734/Impossible.to.export.pdf)
[Possible to export.pdf](https://github.com/photopea/photopea/files/11641735/Possible.to.export.pdf)
But the problem was, I had to wait 30 seconds while your "problem" file was being processed

**Comment by Pt-home** [comment]
And https://cloudconvert.com/psd-to-pdf and https://convertio.co/psd-pdf/
converted your file without problems

**Comment by TheRadicalDreamer** [comment]
There is a difference between both illustrations, see the video attached:

https://github.com/photopea/photopea/assets/11801254/6cfe10f9-b1cc-4c71-a548-49ea3424f706

On the second one you can even hear my PC struggling. One took one second to process, and the other around 30 or more.

What can it be?

**Comment by Pt-home** [comment]
![Possible to export](https://github.com/photopea/photopea/assets/29394245/145a3ca4-c148-4b41-8bb8-859973ead1b9)
![Impossible to export](https://github.com/photopea/photopea/assets/29394245/579f9db0-bdb1-49ca-b2f4-e97ce1a6f515)
The paradox is that a good file is twice as large as a problem one;)

**Comment by camoody1** [comment]
@TheRadicalDreamer Silly idea, I know, but try removing the nipples from the second image and see if the save time improves. That's the only real difference between the two images that I see as far as line art vs painted in areas. Maybe it's treating the nipples as thousands of tiny vector lines for some reason. 🤷🏽‍♂️

**Comment by photopea** [comment]
It is all because PSD and PDF work differently. In PSD, you have boolean operations (add, subtract, intersect, exclude) while in PDF / SVG, there is no such thing - there are path directions, windings and fill rules (even-odd, non-zero).

We had to convert from one to another, which took tens of seconds (finding all intersections between all paths), as you have thousands of points. This step is simply omitted now, if there are more than 5000 points.

**Comment by TheRadicalDreamer** [comment]
Thank you!! Now i can be exported!

BTW @camoody1 i tried the same last night, and nothing happened hehehe

**Comment by camoody1** [comment]
> Thank you!! Now i can be exported!
> 
> BTW @camoody1 i tried the same last night, and nothing happened hehehe

Thank God we don't have to blame the nipples! 😆
