### ISSUE TITLE
Effect Layer's doesn't work with Clipping Mask on

### ISSUE THREAD

**Issue by KaZlos** [photopea/photopea#5711]
title.
with clipping mask: bugged - only the frame should be darkened with the image unaffected
![image](https://github.com/photopea/photopea/assets/53111157/3fe7efbf-f5dd-4954-b645-7e2f6bd9d40f)
without clipping mask: as expected all layers are affected
![image](https://github.com/photopea/photopea/assets/53111157/db25f4c7-59f9-4d45-9c38-082458e7692e)

**Comment by camoody1** [comment]
I'm seeing the same issue. This seems like a new bug. I know I've applied Adjustment Layers using clipping masks many times in the past.

**Comment by photopea** [comment]
fixed!
