### ISSUE TITLE
Ad-Blocker detection triggered even with website whitelisted and the page reloaded

### ISSUE THREAD

**Issue by soggypaper** [photopea/photopea#5712]

**Comment by photopea** [comment]
Could you go to www.Photopea.com and click the "puzzle piece icon" at the top right corner of Google Chrome? Could you share a screenshot of what you see there?

**Comment by soggypaper** [comment]
Here they are
![Screenshot (2)](https://github.com/photopea/photopea/assets/135479174/09ebac60-e4dc-4e0d-8d4e-4814c7f71735)
![Screenshot (1)](https://github.com/photopea/photopea/assets/135479174/cf08c0f7-601e-4177-acfe-bfa16f8b8a36)

**Comment by camoody1** [comment]
AdBlock often seems to give false positives on the Photopea site. I believe Ivan generally recommends replacing AdBlock with another blocker, like uBlock Origin.

**Comment by photopea** [comment]
So it clearly says that your extension "AdBlock - best ad blocker" can change the information on the site.

If you disable it, i am sure our ads will work well. Maybe get in touch with people who made your extension and ask them to fix it somehow.

**Comment by photopea** [comment]
Just to be clear, a website has no way to know what extensions are you using. But if we can not connect to certain ad domains, we consider it to be ad blocking, and this is exactly what your extension does, even if they tell you they are not doing it.
