### ISSUE TITLE
Unwanted Project Opens Every Time I Start Photopea 

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5714]
I can't get rid of the thing! 😆

I have opened Photopea and immediately closed the project at least 20 times. As soon as I restart Photopea, the project immediately reopens. I opened Photopea in Private Mode and logged in... project appeared. I closed it and reopened Photopea (still in Private)... project still appeared. I SAVED the unwanted project. Closed Photopea and reopened it... project still reappeared with old name.

I've tried everything I can think of to get rid of this project. 😆

Help me 😭

**Comment by photopea** [comment]
What web browser do you use?

Are you sure that if you close all incognito tabs, and open one Incognito again, and go to www.Photopea.com, the old project appears?

**Comment by camoody1** [comment]
I'm on my Samsung Galaxy S22 Ultra mobile phone. I've tried in both Microsoft Edge and Google Chrome. I have no other In Cognito tabs open. As soon as I login on the In Cognito Photopea, the project pops up. 🤷🏽‍♂️

**Comment by camoody1** [comment]
Well, either you fid something to fix it, or me uninstalling the plugin called "camo" finally deleted it somehow. 

The project that was stuck open had an image on it that was created by the "camo" plugin. I can't imagine there's any way that plugin could cause my issue... but it's gone now. 🤷🏽‍♂️

**Comment by photopea** [comment]
Yeah, somebody uploaded a PSD file as a plugin, and Photopea loaded it every time when you opened it. I have deleted these plugins from our gallery, but many people have them installed, still.

Many people uploaded JPG files as Brushes, too, so if you installed these brushes, Photopea will open a JPG file instead of loading brushes when it starts.

**Comment by photopea** [comment]
Press Window - Plugins - Installed - and uninstall everything (if the name is "?????", it was already deleted from our gallery).

**Comment by camoody1** [comment]
What a wonderful thing to know for next April Fool's Day. 👍🏼
