### ISSUE TITLE
Full Screen Advertisement Jump Scare

### ISSUE THREAD

**Issue by Neophyter1** [photopea/photopea#5715]
Focusing on my work a sudden advertisement takes over my entire monitor. I skip the ad, however it comes back less than 30 seconds later. Im exausted from the forced exercise of fright. I no longer like Hulu.

**Comment by photopea** [comment]
We are already working on a fix.

**Comment by Neophyter1** [comment]
> We are already working on a fix.

Thank you.

**Comment by photopea** [comment]
It should be fixed, no fullscreen ads should appear anymore :)
