### ISSUE TITLE
Edit-fill does not work correctly with patterns

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5716]
Description of the problem - when choosing Edit-Fill  with a pattern, changing the blending mode and opacity does not work (everything is correct with filling with colors)
Gif for illustrated:
![ProblemsWithEdit-Fill](https://github.com/photopea/photopea/assets/29394245/e5761ef4-523a-4d4e-bfae-e42d1665fc80)

**Comment by photopea** [comment]
fixed! If you run an action of a pattern fill (form an ATN file, or made by a script), it should work, too :)

**Comment by Pt-home** [comment]
Thanks!)
