### ISSUE TITLE
selection tool doesn't select the area of the file that I'm Choosing. Please help

### ISSUE THREAD

**Issue by Jdeanak47** [photopea/photopea#5717]
I'm fairly new to using the software however I am always using it now, so any help would be appreciated. I've been having the issue of the selection of the file I'm choosing with the pointer for any tool, the area of the file that applies the current tool to it is always maybe half an inch or more above or below the area that I've selected it to. To make matters worse it only does it when I log into my premium account. I have to sign out of my premium account and access photo pea from a private browser in order to use it normally with the selection actually selecting what I'm choosing. I've attached screen shots of what I see.

![2023-06-04 (1)](https://github.com/photopea/photopea/assets/135550117/8e2b1e9b-e134-473a-b2c5-d5cd9483f442)
 
![2023-06-04 (1)](https://github.com/photopea/photopea/assets/135550117/ae7d38da-4f12-4daf-a448-b217c4ba92d4)
so, in the picture I use the pointe rand click to select where the red X mark shows and drag the pointer in the direction of the blue line all the way to the green check mark where I release the mouse. I intend for the area of the red box to be selected however the box above in the yellow is selected once I release the mouse and then it sort of rotates the selected area to a vertical shape.

**Comment by camoody1** [comment]
Welcome to the Photopea family!

Go to Edit -> Preferences and make sure that Cursor Offset is set to 0.

**Comment by photopea** [comment]
I also think you changed the cursor offset in Edit - Preferences.

This feature is useful for people with touchscreens, who want to paint with a finger, and dont want the finger to cover the result (so it paints above the finger).
