### ISSUE TITLE
Hulu full screen ad pop is back.

### ISSUE THREAD

**Issue by fohrbz** [photopea/photopea#5718]
I've cleared my cache, etc and it's still popping up. i have no extensions or anything so idk why it's still doing it. i know you guys have fixed it but apparently it didn't work. :(

**Comment by fohrbz** [comment]
it came back 
![Screenshot 2023-06-05 3 25 51 PM](https://github.com/photopea/photopea/assets/113613369/9fd410c1-803b-42e8-8a16-106013baf54b)

**Comment by photopea** [comment]
BTW. could you click the "puzzle piece icon" at the top right corner and share a screnshot of what you see there?

**Comment by fohrbz** [comment]
![Screenshot 2023-06-05 6 51 50 PM](https://github.com/photopea/photopea/assets/113613369/141794cd-9305-4044-ae7f-c0f405fb9ccc)

**Comment by viizzzzz** [comment]
Its not popping up anymore often, so i think it got fixed :D

**Comment by fohrbz** [comment]
it's popped up like 7 times for me today. i will say, its def not as bad as it was lOL!

**Comment by photopea** [comment]
@fohrbz Your screenshot literally says "these extensions can see and change information on this site". So the ad could be inserted by these extensions.

Could you disable your "MultiLogin" extension for a day and see if these fullscreen ads still appear?

**Comment by fohrbz** [comment]
ah! lemme see if that helps. i didn't know that's what that meant tbh? i only use that extension on tumblr but heck, atm i only have one rp account. so i really dont need the multilogin extension.

**Comment by fohrbz** [comment]
Just letting you know, I've completely deleted that extension and it's still coming up. And worse that it has been all day.

**Comment by camoody1** [comment]
> Just letting you know, I've completely deleted that extension and it's still coming up. And worse that it has been all day.

At this point, I would've just paid for the premium subscription. 😂

**Comment by fohrbz** [comment]
I would but  I'm in over my head with medical bills since I've been dealing with being sick.

**Comment by camoody1** [comment]
> I would but I'm in over my head with medical bills since I've been dealing with being sick.

Sorry to hear that. Photopea is great because it opens up image editing to the masses. I'm sure Ivan will get this problem resolved for you as soon as possible.

**Comment by fohrbz** [comment]
It's ok. I'm getting better at least. But I 100% agree. I love using photopea. And I have so much fun learning how to edit more and all. I'm sure too. Ivan works hard to make sure things get taken care of.
