### ISSUE TITLE
Help with the latest needed scripts

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5719]
If you have a moment, help these little scripts run in Photopea 

**Problem 1 - Lens Correction** 
https://photopeaactionslib.olegpustovoit.repl.co/problems/problemLensCorrection.jsx

**Problem 2 - Edit stroke** 
https://photopeaactionslib.olegpustovoit.repl.co/problems/problemStroke.jsx
Note: if change "Strk" on "stroke" - not result too

**Problem 3 - Bevel&Emboss + Stroke** 
https://photopeaactionslib.olegpustovoit.repl.co/problems/problemBevEmbContWithMpgS.jsx
Note: in Satin "MpgS" working  correctly

**Problem 4 - Rastrize Layer Style** 
https://photopeaactionslib.olegpustovoit.repl.co/problems/problemRastrizeLayerStyle.jsx
This script now in Photopea rastrize layer, but layer style - no...

**Problem 5 - Vector Mask** 
https://photopeaactionslib.olegpustovoit.repl.co/problems/problemVectorMask.jsx

Thanks for understanding! Thanks to your constant help and Photopea, we were able to bring our task to the finish line

**Comment by photopea** [comment]
Thanks a lot for reporting it! All your scripts should work now :)
