### ISSUE TITLE
Snap to both horizontal and vertical middle line of the canvas

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#572]
For example, move or scale text/shape from borders to the mid point of the canvas, 
with snapping this would be done much quicker

**Comment by photopea** [comment]
I made the central axis a new snapping element (just like if there was always a guide there).

I also made the middle of an object the new snappable point (not just the edges of the object).

Now, with a grid and guides off, in each axis, the canvas has 3 snapping locations, and an object has 3 snapping points, creating 3x3=9 locations, where the objects can be snapped. It creates 9x9=81 locations, where the object is snapped in both aces.

Before, it was 2x2=4 locations in each axis and 4x4=16 locations for both aces.

**Comment by hgs54371** [comment]
It would be better to show the line it is currently snapping to, for example as bright pink like in photoshop, otherwise you have to pay close attention to that "snap" movement to appear, which is very tiresome.

**Comment by hgs54371** [comment]
Hi, have this been considered, 

This is a very helpful visual aid for snapping

**Comment by photopea** [comment]
Ok I added these "snapping guidelines".

**Comment by hgs54371** [comment]
Why not extend them to the canvas border like in photoshop, instead of just show at layer border, I thought it wasn't there with the default red shape color, they are only shown when triggered, not an issue to be messy
