### ISSUE TITLE
ASL file load caused a CODE HUNG error message

### ISSUE THREAD

**Issue by Jgavin65** [photopea/photopea#5722]
OK, I made a rookie mistake this morning.  I recently bought a file package that had a lot of nice graphics, including asl files.  Using the Photopea APP, (which has worked great up until today) I loaded one of the smaller asl files (3.8MB), and it stalled the system via wait messages.  After that, I couldn't get control of my system (Win 10, latest updates, i7, 32GB, SSD) PP kept timing out.  I deleted the app, rebooted, and reloaded the PP app from the main screen.  Now the program isn't working well at all; very sluggish

TIA,

JoeG
[Gold _ Silver.zip](https://github.com/photopea/photopea/files/11688819/Gold._.Silver.zip)

**Comment by photopea** [comment]
Hi Joe, I opened www.Photopea.com and drag-and-dropped your ZIP file into it. Right away, I saw a message about layer styles being added. I could apply these layer styles to any layer.

What exactly should I do to see a problem which you describe? Could you try these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by Jgavin65** [comment]
After I sent the email, it occurred to me that I could delete the APP and try it again in a different browser.  So, I started PP in Chrome, and it fired right up. I loaded the ASL file, and it loaded almost instantly (as I had expected).  I think my problem was using Microsoft Edge.  Lesson learned.  I just tried the same experiment again using Edge.  same results. Endless WAIT messages.

I just tried to load the zipped PSD file but the file is 33MB.  Can you override this once?

**Comment by photopea** [comment]
Thousands of our users use Photopea in Edge. Could you try to clear the website data ("cookies") in Edge?

What do you mean by "override this once"? Photopea can open any file. If it is a ZIP, Photopea will unzip it and process each item inside separately. I have opened PSD files that were 1.2 GB in Photopea.

**Comment by Jgavin65** [comment]
I wanted to send you my file, it is 33 MB zipped, and it get bounced by the message handler because it is over 25 MB.

 

I’ll try clearing the cookies too!

**Comment by photopea** [comment]
You can upload your file somewhere and send me a link.

**Comment by photopea** [comment]
I have to close it, as the person did not respond.
