### ISSUE TITLE
Magic Cut not working

### ISSUE THREAD

**Issue by abuffery** [photopea/photopea#5723]
Hi,

I am following this youtube video from photopea pro and the magic cut is not working:  https://www.youtube.com/watch?v=qWYexxYUmiA

In the magic cut I do see the left side of my screen with the image of the model with the green and red marking but I see no image at all on the right hand side with the model cut out.

It is not that the image on the right is totally empty-blank-white, the issue I have is that there is nothing at all on the right hand side.  

The right hand side has the same darkgrey application background as the background that is around the model on the left.  

I have the same issue via desktop and the browser. 

I am using chrome. 

 I have used all the options available in the magic cut, and when I press OK I always end up with a full transparent canvas.  
 
Any clues why ?

![Screenshot 2023-06-08 at 15 30 24](https://github.com/photopea/photopea/assets/102527112/d0f64b15-2f2c-4130-8855-dd73d9ac71d1)

**Comment by Pt-home** [comment]
The same problem occurred 15 minutes ago

**Comment by camoody1** [comment]
Same here. Magic Cut is not working today.🤷🏽‍♂️

**Comment by abuffery** [comment]
Thanksss for the quick fix !!!
