### ISSUE TITLE
Ad Issues

### ISSUE THREAD

**Issue by Johnnycadesbf** [photopea/photopea#5724]
Hey there's been issues with the Ads on photopea where the ads don't load after you press ok! This never happened when ads weren't involved,  but now that they are I cannot download anything anymore. :(

**Comment by photopea** [comment]
Are you using Photopea on a phone, and you are trying to export a JPG / PNG? 

These ads work for thousands of users. Do you have any ad blocking app on your phone?

**Comment by photopea** [comment]
I have to close it because of lack of details.
