### ISSUE TITLE
New Dezgo Inpainting Model... Time to Update!

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5726]
Dezgo added a new photorealistic model to their options that is currently one of the best on the AI market... AbsoluteReality. They've added this to their Text-to-Image tool on their free tier and it gives amazing results. The bonus to this model is that it also has a working Inpainting function to it. And they've added that model to their Inpainting Tool, as well! They previously only had StableDiffusion 1.4 and StableDiffusion 1.5 Inpaining Models... I'm not sure which model you were sending in your API messages. But this is a new third option that should be the default choice for most Photopea instances. Ideally, you could just add the three models as a drop-list on the Advanced menu that you already have setup.

The trick to this model is that I believe they're only adding it to their new api.dezgo.com API and not their old RapidAPI client. I'm guessing they're trying to incentivize people to move off their old system by only adding new features to their new system. Makes sense, I suppose... no one wants to maintain a legacy system if they can get everyone off of it.

Here is a link to the new AbsoluteReality model. Beautiful stuff.
https://civitai.com/models/81458?modelVersionId=88418

**Comment by camoody1** [comment]
It looks like migrating from the old RapidAPI to the new api.dezgo.com environment is super simple. Shouldn't take you but a couple of minutes to update that... leaving you plenty of time to add the Model drop-list for us to use. 😁

From their website...
![image](https://github.com/photopea/photopea/assets/73725653/23f20aca-4df2-4bdd-9bc9-f1c74332e2cf)

**Comment by photopea** [comment]
Where did you find the info about a "new inpainting model"? According to their API, there are still only two models for inpainting: https://dev.dezgo.com/API/

BTW. I think we need to look for a replacement for Dezgo. Do you know about anything? At the current rate, I will be paying them thousands of USD per month. Otherwise, I would have to restrict the Magic Replace to Premium users only.

**Comment by photopea** [comment]
I see that your link offers the model for download, and it is "only" 2 GB. In the future, we could let users download it with a click (to their Local Storage: Edit - Local Storage, where it stays permanently), and run it on a users computer on their GPU using the WebGPU.

**Comment by camoody1** [comment]
Regarding the inpainting models currently available, you are correct... there are only two available right now. I misunderstood the Discord post that I read. While the AbsoluteReality model IS currently available for their text-to-image tool, they are still working to implement it into their inpainting tool. It will be available soon. This was confirmed to me by one of their Devs.

As far as your other comments, I have some thoughts on moving away from Dezgo, but I don't know that you would want them posted here for everyone to see since this would be really more of a business discussion than a tech issue. I don't think there's any way to make this post private, so I'll just say a few things and you can delete them if you want:

- I have not seen any other company offer the capabilities that Dezgo offers at anything remotely close to their prices. I looked around quite a lot back when I first started nagging you to add AI based image-to-image, inpainting and outpainting options. Most companies charge 5 to 10 times this, easily.
- AI technology is driving the current photo/image editing tech space right now. I think it would be an enormous mistake to remove AI tools at this point. Not only is Photoshop doubling down on their AI tools, but they've also just made Firefly available for free to Adobe Express users on the desktop and will soon add it to their mobile application. Additionally, I just saw that Pixlr has recently integrated AI inpainting to their app, and I believe GIMP has plugins as well. I think you would risk losing a lot of users if you dropped this support.
- I'm not sure how familiar you are with the Stable Diffusion toolset, but you mentioned being able to just download the AbsoluteReality model and then run it using WebGPU. While I don't pretend to have any idea what is possible with WebGPU, I DO know that these models are only a small part of everything that is necessary for a user to create images using Stable Diffusion on their home devices. In addition to the models, they would also need to install a front-end, like Automatic1111, Python and a couple other pieces of software and GitHub pieces. Of course, those are all in addition to the user needing a newer generation GPU with 16GB+ of VRAM. What companies like Dezgo offers simplifies all of this for the end user and that's what makes them so valuable.

In the end, this is obviously entirely your decision. You know your budget. You know your income and expenses. It's not my money being used. I can only offer you advice from an interested user who would like to see Photopea succeed. Having spoken with one of the Dezgo devs, I know that there are several exciting new tools that they will soon be offering to their customers. I think Dezgo and Photopea could work together to make one hell of a powerful image editing application. Even if most, or all, of this Dezgo power needs to be put behind a Photopea subscriber wall, I think it would be wise to keep the tools they currently offer and expand to even more of their tools in the near future. Perhaps you could use a Photopea API key for certain less advanced tools (at 512x512px max resolution) while allowing users to use their own Dezgo API keys for higher resolution images and more advance tools. Dezgo has a lot of their own subscribers who already pay them for advanced access. I'm sure they would love to have a powerful, integrated GUI like Photopea could offer.

Perhaps there's some sort of partnership that could be worked out between you and Dezgo. I don't know. But I do think it would be a big mistake to move away from offering AI tools in Photopea, or to move to another company that offers less.
