### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by grubby-spyware0g** [photopea/photopea#5727]
![image](https://github.com/photopea/photopea/assets/135968665/a9c11dcb-395c-45a5-8a4c-e6d13058f5fd)

**Comment by camoody1** [comment]
What issue are you trying to report?

**Comment by grubby-spyware0g** [comment]
the bug

**Comment by grubby-spyware0g** [comment]
![image](https://github.com/photopea/photopea/assets/135968665/03e4716d-e23d-480b-a119-27ce73664f63)
image is not shown after importing

**Comment by photopea** [comment]
Hi, try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

in short, we need to know if there is a bug when you use an updated browser with no extensions.

**Comment by photopea** [comment]
I have to close it because of lack of details.
