### ISSUE TITLE
Gaussian Blur not working 

### ISSUE THREAD

**Issue by tarsierz** [photopea/photopea#5728]
Tried using the blur tool and it creates a new layer. Any help fixing this?

**Comment by camoody1** [comment]
I was just able to successfully add a Gaussian Blur filter to one of my layers. Exactly what are you doing and what are you seeing? Could you try opening Photopea in "in cognito mode" and try again? It's possible you have a browser extension causing an issue. If it still doesn't work, perhaps you could record a short video to show us exactly what you're doing.

**Comment by camoody1** [comment]
> Tried using the blur tool and it creates a new layer. Any help fixing this?

Can you provide any additional information? Have you tried the suggestions in my previous comment?

**Comment by photopea** [comment]
I think it is best to close it, as the original person stopped responding.
