### ISSUE TITLE
Support Drawing Tablet?

### ISSUE THREAD

**Issue by ZainF123** [photopea/photopea#5729]
I bought a XP-Pen tablet from Amazon that allows you to draw using a pen on a black pad. However, when I go to draw, it only recognizes the initial tap input and doesn't draw any further---just a single dot where I first tapped. Is there a support feature I need to enable?

**Comment by photopea** [comment]
I know there are people who use Photopea with drawing tablets without any problems. 

Try this maybe: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
did you make it work?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
