### ISSUE TITLE
TEXT TOOL has issues

### ISSUE THREAD

**Issue by OCDmike** [photopea/photopea#573]
Having multiple difficulties with the TEXT TOOL.  I am able to work around some of them, but the major issue I am facing is that ALL TEXT IS IN CAPS

**Comment by photopea** [comment]
Hi, maybe you have the text style, which makes all characters Capitals. You can disable it in the Characters panel. Have you tried it?

**Comment by OCDmike** [comment]
I don't think that is it.  I can't even create a Text Box now

**Comment by photopea** [comment]
You can learn how to change style here: https://www.photopea.com/learn/text-layers 

Could you maybe take a video of what is going on on your computer?

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by quantuminformation** [comment]
I don't see the setting, I have the same issue

![image](https://user-images.githubusercontent.com/216566/113553183-a43f3a80-95f7-11eb-864b-4446c54e9f04.png)

**Comment by quantuminformation** [comment]
@OCDmike did you fix it?

**Comment by photopea** [comment]
You have enabled the "All Caps" switch.

![image](https://user-images.githubusercontent.com/15955558/113554485-b326ec80-95f9-11eb-8608-b875274d804d.jpg)

**Comment by quantuminformation** [comment]
dooh,

thx
