### ISSUE TITLE
Layer bug

### ISSUE THREAD

**Issue by jruss0420** [photopea/photopea#5730]
I can't access or find my layers on Photo Pea.  All I can see is "Channels"  and  "Paths".   I looked at your opened issues and none of them have reported this one.  Hopefully this helps

**Comment by camoody1** [comment]
On the top toolbar, click Windows -> Layers

**Comment by photopea** [comment]
Yes, click Window - Layers to open the Layers window. You can close any window by right-clicking the label and choosing "Close".
