### ISSUE TITLE
não consigo mudar a largura da imagem em pixels

### ISSUE THREAD

**Issue by LineDesign12** [photopea/photopea#5731]
imagem> tamanho da imagem
Não consigo deixar a largura e altura da imagem em "pixels", só fica em "polegadas".
![Captura de tela 2023-06-09 211756](https://github.com/photopea/photopea/assets/136027683/ddaa9168-4253-4fcc-9dd1-1079b8b2b45b)

**Comment by photopea** [comment]
You have disabled the "Resample", so you can not change the size in pixels. "Resampling" literally means changing the size in pixels (a pixel is a color sample).

You could say, you see something in front of you, and you record it using a million samples of color (pixels). But if it is too large, and you want to use just 10,000 samples, you need to resample it.
