### ISSUE TITLE
"Donut problem": converting a selection with inner boundaries into a Working Path

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5732]
Hi!
Description of the problem: If your selection is not a singly connected shape, then Photopea now does not correctly convert it to a work path, ignoring the inner boundaries of the selection...
The simplest example is a ring, a donut...

Example problem:
![ProblemConvertingSelectionsWithGapInVectorMask](https://github.com/photopea/photopea/assets/29394245/31d82c79-d76d-4e1a-b874-778787510810)
File from example:
![donut](https://github.com/photopea/photopea/assets/29394245/8fd010d7-41f1-49e3-8091-f4ce7b82ef36)

Notes: "Remove Background" also does not fully cope with this form, but it seems to me that there are other reasons

**Comment by photopea** [comment]
fixed! :)

**Comment by Pt-home** [comment]
Yes, thanks, now all correctly
