### ISSUE TITLE
photopea crashing on homepage automatically loading random projects

### ISSUE THREAD

**Issue by thenookiebear** [photopea/photopea#5734]
Just recently over the last week photopea website has been playing up, normally it's fine i go to the website click on new project or load a previous one, now when i go to the website it automatically loads about 8 random projects by it's self without me even clicking on anything and basically crashes, i have not changed anything recently, it's not my extensions, so i believe it to be a issue with photopea. any information to solve this problem ? Thanks.

**Comment by Pt-home** [comment]
Have you tried all the solutions to the problem from this list?
[https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/](url)

**Comment by thenookiebear** [comment]
> Have you tried all the solutions to the problem from this list? [https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/](url)

Yeah it's none of them causing the issue, it just randomly started a few days ago

**Comment by Pt-home** [comment]
What browser/version/operating system are you using? More details - more information to analyze the problem...

**Comment by photopea** [comment]
If you open www.Photopea.com in the Incognito mode, it definitely does not load any random projects. Are you telling the truth about reading the link?

**Comment by camoody1** [comment]
Have you recently installed any Photopea plugins from the plugins window?

**Comment by photopea** [comment]
I will close it because the person stopped responding.
