### ISSUE TITLE
[Closed] Layer Styles Won't Stay Deleted

### ISSUE THREAD

**Issue by MrStorm01** [photopea/photopea#5736]
## The title explains a lot. 

Here's a video to sum it up. Is there a way to keep styles deleted and not show back up when deleted? If not, currently, could that be added/fixed? 

https://github.com/photopea/photopea/assets/136375105/53d684f1-ca56-408d-9468-4919ef8b3ea4

**Comment by Pt-home** [comment]
I repeated all your actions exactly as in the video and all my styles were deleted... Weird

**Comment by MrStorm01** [comment]
...
I didn't pay attention to Local Storage. I think it fixed my issue.

**Comment by MrStorm01** [comment]
Yeah, found it. Sorry, the session is resolved.

**Comment by photopea** [comment]
yes, if you load an ASL file and tell Photopea to store it permanently, it will be stored permanently.

**Comment by MrStorm01** [comment]
Not exactly what I meant, @photopea.
