### ISSUE TITLE
Vertical Align for text box

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5737]
I know we have talked about this before on: https://github.com/photopea/photopea/issues/3716 and https://github.com/photopea/photopea/issues/3504 with @MichalSZZ 

I work a lot with variables, just like @MichalSZZ

That's why i have asked if variables can have one PDF export (with multiple pages) in https://github.com/photopea/photopea/issues/5396 and @MichalSZZ being able to give different names to the output file based on the uploaded CSV on https://github.com/photopea/photopea/issues/5476

None of those issues got "green-lighted", which is so sad.

So i was wondering: how can i give a temporary vertical align property to a textbox? Without having an actual setting in Photopea. I mean, maybe modifying a JS variable on the browser, or maybe having the option to apply the modification on the CSS window, i dunno.
![image](https://github.com/photopea/photopea/assets/11801254/394d0046-8323-4557-b80c-5510fc33c905)

I really need to have that option, even have it temporary and have to be done by hand every time, and not be saved on the PSD. I don't know if [Vectorpea](https://github.com/photopea/photopea/issues/4535) will see the light at  some point, and if it will have something like variables and vertical align text, which I can do my work with.

For all these years i have exporting all the assets to google slides, where i can vertically align and it also has something like variables (from an extension called [Autocrat](https://workspace.google.com/marketplace/app/autocrat/539341275670?hl=es))

But this workflow is really really slow, because i have to export every element and upload it on a cloud so google slide can use it on a variable, and cannot be modified on the document.

Well, i hope you can give us a workaround useful for variables. I bet @MichalSZZ will also find it useful.

Do you think you can make it happen?

**Comment by photopea** [comment]
Is there such a feature in PSD files? Because if users set the vertical align, and it is lost after saving a PSD file, they will be really confused.

**Comment by TheRadicalDreamer** [comment]
No. That's why asked if there is a work around solution, that does not saved into the PSD file.

That much i care about the vertical align. I would manually add a code or something everytime I open the file, if when I use variables it dynamically aligns the textbox that changes.

🥲

**Comment by photopea** [comment]
The Move tool has a button "Align Bottom Edges", which works with actual pixels (not with the text rectangle). Could it help you?

**Comment by TheRadicalDreamer** [comment]
No, because i use texts, that goes from 50 characters to 190 characters

Let me show you.

![image](https://github.com/photopea/photopea/assets/11801254/555b7fe9-3a17-4f4d-b24d-f35eb8e051b7)

**Comment by TheRadicalDreamer** [comment]
No. Because my use cade is on variables.

I have a textbox that changes on every iteration. And i need it to be vertically centered. But some content has 5 lines and other just one.

(Did I explained clearly?)

**Comment by photopea** [comment]
Ok, got it now!

BTW. I am really curious if there is a way to do it in Photoshop. Could you maybe ask in https://www.reddit.com/r/photoshop how to do it in Photoshop? So that we dont reinvent the wheel.

**Comment by TheRadicalDreamer** [comment]
I cannot enter the reddit community. It is private 
![image](https://github.com/photopea/photopea/assets/11801254/964a643e-4fbb-4552-b296-305b443247b1)

Even though if look up in google for vertical align a text box photoshop, you'll find a bunch of post about it, and many people mad about it.

https://community.adobe.com/t5/photoshop-ecosystem-ideas/p-center-text-vertically-in-bounding-box-like-indesign/idi-p/12248615

https://www.reddit.com/r/GIMP/comments/192cvl/help_how_do_i_center_text_vertically_within_a/

https://www.reddit.com/r/GIMP/comments/fvghmu/how_do_i_center_text_vertically_within_a_text_box/

https://graphicdesign.stackexchange.com/questions/26212/how-to-center-text-vertically-within-a-textbox-in-photoshop

in the last one, someone created a "script" for photoshop:
![image](https://github.com/photopea/photopea/assets/11801254/060b3752-9e00-4453-a72d-adf2d3ca2af9)

**Comment by MichalSZZ** [comment]
@TheRadicalDreamer I don't use Photopea in my work. I have a legal Adobe CC license for all products and I use them every day in my work. 
I used Photopea to learn my students graphic design (but now I don't have any class). And this is the best way to do that job!

But YES - this feature (vertical alignment for text) is very important and I don't know why Adobe has not implemented it for all these years in Photoshop.

Making it by the script that works only in Photopea is a good workaround - when the user opens it in Photoshop it will look like the project saved in Photopea but it will not have an automatic alignment feature in Photoshop. 

I am curious about the script that you pasted above because when I tested it - it works perfectly only for one-line paragraphs. 
The result is centering for the first line. Look:

![obraz](https://github.com/photopea/photopea/assets/38118273/a4a4a332-5747-45d0-b5e4-c8bb834f15dc)
![obraz](https://github.com/photopea/photopea/assets/38118273/5179e45e-e4a4-455c-9261-10a1bb53a6e1)

**Comment by photopea** [comment]
I have added a special switch for the vertical alighment (next to the Anti-aliasing switch at the top). Each text layer has this option (but it is used only for paragraph text).

If you open such a PSD in Adobe Photoshop, this option is ignored (for now) and Photoshop will render the text regularly (aligned to the top).

**Comment by TheRadicalDreamer** [comment]
I LOVE YOU!!! THANK YOUUUUUUUUU
![download](https://github.com/photopea/photopea/assets/11801254/5a309abc-6cbf-4bf6-b422-edecc9209d3e)

**Comment by MichalSZZ** [comment]
> I have added a special switch for the vertical alighment (next to the Anti-aliasing switch at the top). Each text layer has this option (but it is used only for paragraph text).
> 
> If you open such a PSD in Adobe Photoshop, this option is ignored (for now) and Photoshop will render the text regularly (aligned to the top).

You know what? I just bought the 1-year subscription as thanks for your incredible work! As I said - I don't use Photopea in my work but that was amazing what you just did. It Works perfectly - even better than in the Script that I tested.

Someone (maybe Photopea Pro) can make a video ('10 things that Photopea has and Photoshop should have') - that can be one of them.

**Comment by TheRadicalDreamer** [comment]
Totally!

There are a couple of things that Photopea can do better than Photoshop.

**Comment by TheRadicalDreamer** [comment]
It is me or the variables export option does not work?

**Comment by MichalSZZ** [comment]
BTW. If you want @photopea I can make icons for that function. Illustrator has it with Icons in the simple menu and with words in the complex paragraph window.
![obraz](https://github.com/photopea/photopea/assets/38118273/26a98718-7068-4708-8b4c-c91cd978a9c6)

**Comment by photopea** [comment]
@TheRadicalDreamer I tried this tutorial - https://www.photopea.com/learn/variables - I was able to export PDF files.

Please, tell me what should I do to see the problem mysefl.

**Comment by TheRadicalDreamer** [comment]
I had a color fill layer with content variable. I don't know why. I deleted it and made it again, and all was good.

BTW, i tried the vertical align with a project i am working.

It has a text with shadow, and the results are not correct, take a look:

![image](https://github.com/photopea/photopea/assets/11801254/500ecb28-552e-417a-afc8-09bc4fbacfd8)
![image](https://github.com/photopea/photopea/assets/11801254/7cbdcfcb-0a13-4b5a-afc3-3bb819d4ba55)
![image](https://github.com/photopea/photopea/assets/11801254/d10c2d5d-1c9c-4e00-9252-ec8a71845a47)
![image](https://github.com/photopea/photopea/assets/11801254/5352ff68-7ecd-47ec-9c22-529250c0faa7)

**Comment by TheRadicalDreamer** [comment]
Only the shadow got the vertical align centered, but not the text.

And i started like this:
![image](https://github.com/photopea/photopea/assets/11801254/409ff223-78be-410a-a438-ca596d0b21b5)


Here is the PSD if you want to take a look:
[CTSPK - Color Cards.zip](https://github.com/photopea/photopea/files/11750987/CTSPK.-.Color.Cards.zip)

**Comment by MichalSZZ** [comment]
> BTW. If you want @photopea I can make icons for that function. Illustrator has it with Icons in the simple menu and with words in the complex paragraph window. ![obraz](https://user-images.githubusercontent.com/38118273/245907600-26a98718-7068-4708-8b4c-c91cd978a9c6.png)

@photopea www.photopea.com/#i6uRCa3GA.psd you can export and use as PNG base64 for example here:
![obraz](https://github.com/photopea/photopea/assets/38118273/1f7e7be8-1a90-4016-b981-4a2dd08047a8)
they are made from your left text alignment icon

**Comment by camoody1** [comment]
@MichalSZZ 
![dcdf5b42acb95fa3551faa23a2f1e9e4 (1)](https://github.com/photopea/photopea/assets/73725653/00452e08-c5d5-45b9-a112-271c70ac1894)

**Comment by photopea** [comment]
@TheRadicalDreamer I am afraid I do not understand. What is wrong with the shadow? It seems to work well when I play with your PSD.

**Comment by TheRadicalDreamer** [comment]
This is what i am doing:
https://github.com/photopea/photopea/assets/11801254/c74c4ed6-3aba-4ff6-90d4-85c089ca4de0

This is the PSD:
[PSD.zip](https://github.com/photopea/photopea/files/11763261/PSD.zip)

**Comment by photopea** [comment]
got it, it is fixed now.

When you exported your PSD as a PDF, and it had a custom vertical align, it was ignored (it was not related to variables).

**Comment by TheRadicalDreamer** [comment]
THANKS!!! it works now!!

**Comment by TheRadicalDreamer** [comment]
BTW, do you think we can have a loading window or icon, to know that the variables are being created?

Right now i have to guess it is doing it, or hear my PC CPU struggling :P

A loading bar, a loading spinning icon, a "34/100 variations processed" text or something that indicates that it is still working?

**Comment by TheRadicalDreamer** [comment]
I have this text box i am trying to vertically align (centered). But it seems that it is not completely centered. It is a notch up:
![Screenshot 2023-06-15 21 11 12](https://github.com/photopea/photopea/assets/11801254/0db43e61-2913-4db0-995f-1f33030d33c7)
![Screenshot 2023-06-15 21 10 47](https://github.com/photopea/photopea/assets/11801254/0540094a-9c19-48c9-8feb-dd31f43e0a5d)
![Screenshot 2023-06-15 21 10 42](https://github.com/photopea/photopea/assets/11801254/006b26ef-d4f4-4b7e-a684-abcb1d1057b8)

The PSD:
[not centered.zip](https://github.com/photopea/photopea/files/11764769/not.centered.zip)

**Comment by photopea** [comment]
I made the PDF export faster when there are solid color layers. As for the align, I dont think the top of "d" and the bottom of "p" is the right measure. It is more complicated.

**Comment by TheRadicalDreamer** [comment]
https://github.com/photopea/photopea/assets/11801254/ebb056fd-de31-4a40-8f63-a4ac021b1d0c

I thought that the top of "d" and the bottom of "p" should be equally distant from the border of the text box.

So. This won't be more "corrected"?

**Comment by TheRadicalDreamer** [comment]
This is a vertical aligned text box on a squared canvas of the same size.

![Screenshot 2023-06-16 21 19 07](https://github.com/photopea/photopea/assets/11801254/1874b6d3-de67-4ae6-b5ae-225a45c22608)

I believe there is something off. Can this be corrected?

**Comment by camoody1** [comment]
@TheRadicalDreamer I think you need a drink to relax your perfectionism just a bit.😁

**Comment by camoody1** [comment]
@TheRadicalDreamer You're not wrong, though.😆
/
![SmartSelect_20230619_192136_Edge](https://github.com/photopea/photopea/assets/73725653/e41b3379-bee8-4223-81ff-73037b326d7b)
