### ISSUE TITLE
My keyboard is experiencing partial malfunction where certain keys and shortcuts are not working properly. 

### ISSUE THREAD

**Issue by CCCHEEJI** [photopea/photopea#5738]
My keyboard is experiencing partial malfunction where certain keys and shortcuts are not working properly. For example, the Ctrl+C, Ctrl+V, and arrow keys are not functioning. It is quite inconvenient as these functionalities are essential for various tasks. I have checked the keyboard settings and made sure that the appropriate drivers are installed, but the issue persists. I would appreciate any assistance or suggestions to resolve this problem. I'm currently using a virtual keyboard shown in the picture as a temporary solution. I would appreciate a prompt response.

![image](https://github.com/photopea/photopea/assets/136422536/97a655fa-3770-49af-b19b-7cd5940fbb91)

Thank you.

**Comment by camoody1** [comment]
Does your Ctrl-C and Ctrl-V work in other programs, like MS Word or Notepad? Or are you actually saying that your keyboard isn't working correctly _anywhere_ in Windows? If it's not working in any other program, I'm not sure why you would ask the Photopea team to resolve your issue. It sounds like a bad keyboard that needs to be replaced.🤷🏼‍♂️

**Comment by CCCHEEJI** [comment]
I can confirm that the Ctrl-C and Ctrl-V commands are working correctly in all other programs except for Photopea. Therefore, the issue seems to be specific to Photopea and not a problem with my keyboard. I kindly request a prompt resolution for this matter. Thank you.

**Comment by photopea** [comment]
Please, tell us your operating system (name and version) and your web browser (name and version).

I guess you are using some bluetooth keyboard on Android. It is very important to mention these things (that it is not a standard desktop environment).

**Comment by photopea** [comment]
Can you right click an image on some website, choose "Copy Image", go to www.imgur.com , and press Ctrl+V to paste it? It should be uploaded to Imgur. Does it work?

**Comment by photopea** [comment]
Also, could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by CCCHEEJI** [comment]
I'm glad that Photopea is working when you use it in Incognito mode. Thank you for your kind response.

**Comment by photopea** [comment]
This means, that you are using browser extensions, which break Photopea (browser extensions are disabled in the Incognito mode). So just disable your extensions and you can use Photopea in a regular mode.

It is really strange that you installed an extension which breaks the keyboard and you don't know about it.
