### ISSUE TITLE
An error while loading a sketch file

### ISSUE THREAD

**Issue by yurij-volokhov** [photopea/photopea#574]
Hi!
I just started using your webapp and tried to open my .sketch file. Its "loading" becomes infinite, while the js-console produces an error
`Uncaught e
ext.js:1735`

**Comment by photopea** [comment]
Hi, can you send us your PSD file to support@photopea.com ?

**Comment by photopea** [comment]
Hi, did you send the file?

**Comment by yurij-volokhov** [comment]
Hi! I haven't PSD, I've .sketch.
I'd sended it.

**Comment by photopea** [comment]
Hi. I was able to open your file "mob coinplace.sketch" in Photopea without any problems.

I don't know what happened :/  Can you try it again?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
