### ISSUE TITLE
In imported SVG files, gradients are displayed as one solid color

### ISSUE THREAD

**Issue by KiraResari** [photopea/photopea#5740]
**Repro:**

1. Create an SVG file with a gradient, such as:
```
<?xml version="1.0" encoding="UTF-8"?>
<svg width="512px" height="512px" viewBox="0 0 512 512" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <title>change anything in this icon copy</title>
    <defs>
        <rect id="path-1" x="0" y="0" width="512" height="512"></rect>
        <linearGradient x1="20.1882124%" y1="80.2831888%" x2="74.3035555%" y2="20.6938982%" id="linearGradient-3">
            <stop stop-color="#003A79" offset="0%"></stop>
            <stop stop-color="#68C4C7" offset="100%"></stop>
        </linearGradient>
        <polygon id="path-4" points="7.87238634e-15 1.18085795e-14 512 8.55914004e-15 512 512 1.96809658e-14 512"></polygon>
    </defs>
    <g id="change-anything-in-this-icon-copy" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="icon">
            <mask id="mask-2" fill="white">
                <use xlink:href="#path-1"></use>
            </mask>
            <g id="Mask"></g>
            <g id="Rectangle" mask="url(#mask-2)">
                <mask id="mask-5" fill="white">
                    <use xlink:href="#path-4"></use>
                </mask>
                <use id="Mask" fill="url(#linearGradient-3)" xlink:href="#path-4"></use>
            </g>
        </g>
    </g>
</svg>
```
2. Open the file in Photopea (for example via drag & drop on the start page)

**Expected Behavior**
* The gradient is correctly displayed

**Actual Behavior**
* Instead of the gradient, a solid color is displayed
* The color displayed seems to be that of the top left pixel (check by opening the SVG file normally)

**Comment by Pt-home** [comment]
Note:
[](https://validator.w3.org/check)  write:
Error Line 22, Column 82: Attribute id declares a duplicate ID value Mask.
…       <use id="Mask" fill="url(#linearGradient-3)" xlink:href="#path-4"></use>

Warning Line 17, Column 25: The first occurrence of the ID value Mask was here.
            <g id="Mask"></g>

**Comment by Pt-home** [comment]
You're right, there seems to be something wrong with the gradients. I created a very simple SVG - and it also opens in Photoshop with a solid start color:
![Gradient](https://github.com/photopea/photopea/assets/29394245/ceb06947-39cc-4d18-9a54-3d3ab098e928)

**Comment by photopea** [comment]
hey guys, it is fixed now.
