### ISSUE TITLE
Some more help with scripts

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5741]
Hi! When you have time - help with some more "stubborn" scripts:

**Problem 1 - Open file from PC**
Script:
`app.open("https://www.photopea.com/api/img2/pug.png");`
absolutly correctly, but scripts a-la:
`app.open("C:\Users\Oleg\Pictures\1\donut.png");`
or
`app.open("file:///C:/Users/Oleg/Pictures/1/donut.png");`
give alert "Loading" and "sleeping"...

**Problem 2 - Vector mask on current path**
Problem script - [https://photopeaactionslib.olegpustovoit.repl.co/problems/problemVectorMaskCurrentPath.jsx](url)
File for script  - [https://photopeaactionslib.olegpustovoit.repl.co/problems/donutVectorMask.psd](url)
Note: Doesn't accept Work Path, works as Hide All

**Problem 3 - Define brush**
Problem script - [https://photopeaactionslib.olegpustovoit.repl.co/problems/problemDefineBrush.jsx](url)
Note: But Define Pattern - working correctly with scripts

**Problem 4 - Texture Dilation**
Pre-note: Yes, this  is no-PS script, but filter turned out to be very useful and, perhaps, it will be possible to implement script, especially since it looks simple
Example script -  [https://photopeaactionslib.olegpustovoit.repl.co/problems/problemTextureDilation.jsx](url)

**Problem 5 - "Cropped" Color Range script**
Pre-note: This will require "more letters".
Color Range in Photopea works better than in Photoshop in Sampled Colors mode. 
Photoshop starts the Color Range window with Min and Max as Lab(100,0,0). 
Photopea seems to parse the file and put these parameters on the point of the color that "prevails" in a custom image. This makes Color Range very promising for automating background extraction.
What is the essence of the request - is it possible to make the "cropped" script, an example of which is below, where only one parameter, "Fzns", work similarly to the manual mode of Photopea, automatically substituting this "prevailing" color into Min and Max?
Example Script - [https://photopeaactionslib.olegpustovoit.repl.co/problems/problemCroppedColorRange.jsx](url)

Thank you!

**Comment by Pt-home** [comment]
Hi Ivan!
This scripts in zip:
[problems.zip](https://github.com/photopea/photopea/files/13829968/problems.zip)

**Comment by photopea** [comment]
Ok, so as I said, 1 is impossible to do.

I have fixed 2 and 3.

I am afraid to implement 4 and 5, as these scripts / actions would not work in Adobe Photoshop.

**Comment by milqnomadu** [comment]
how can 1 be possible? any workarounds to upload files from local?

**Comment by photopea** [comment]
Photopea is a website and websites can not see files in your computer. So we can not make such a script work.

Maybe run some local web server on your computer, to make your files available over the HTTP protocol.
