### ISSUE TITLE
where is the menu。chrome

### ISSUE THREAD

**Issue by tangbob** [photopea/photopea#5743]
![image](https://github.com/photopea/photopea/assets/1781398/9cbaa7b2-7ab8-457f-bb1c-782483acadb0)

**Comment by photopea** [comment]
What should I do to see this problem? I opened www.Photopea.com and it looks fine.

**Comment by tangbob** [comment]
yes，me too

**Comment by photopea** [comment]
So what should I do to see the problem?

Your error looks like you have added some strange text  after the URL "www.Photopea.com"
