### ISSUE TITLE
Photopea won't load fonts and icons correctly.

### ISSUE THREAD

**Issue by DelczBalazs** [photopea/photopea#5744]
Hey there!
I've been using a psd project for weeks and everything appeared in photopea as intended(fonts, icons).
Yet now it won't properly show even though it says the particular fonts were loaded.
I tried opening the original psd file and its not working either, i tried in photoshop and it opens as it should so the problem is not the file.
This also happens if i try to open it from another browsers or from incognito via photopea.

**Comment by photopea** [comment]
What should I do to see the problem myself?

Could you share your file with us and describe what should we do with it, to see the problem?

**Comment by DelczBalazs** [comment]
Hey,
i can only show pictures here because the project is not public:

This is what i get after opening the project even though i got the proper
fonts before( file works in photoshop fine)

[image: kép.png]
[image: kép.png]



i also tried opening fonts as local files, and it still doesnt some fonts
nor the font awesome icons it could find before
[image: kép.png]


Photopea ***@***.***> ezt írta (időpont: 2023. jún. 14., Sze,
23:13):

**Comment by DelczBalazs** [comment]
It's working again. What was the problem?

**Comment by photopea** [comment]
Photopea was re-rendering every text layer after opening a PSD. If fonts were not available, Photopea used a subsitute font. It is fixed now (original text layers are preserved, if you dont want to modify them).

**Comment by DelczBalazs** [comment]
Glad to hear it! Thanks for the fast help and keep up the good work!:)

Photopea ***@***.***> ezt írta (időpont: 2023. jún. 15., Cs,
19:42):
