### ISSUE TITLE
Artboard - Guide color

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5745]
We can change the color of the global guide and grid, but no the local/artboard guides.

![image](https://github.com/photopea/photopea/assets/11801254/fb4dc6dc-b585-4b28-a286-56c93fdf6ab9)

Can we have that option on the preferences menu?

**Comment by TheRadicalDreamer** [comment]
It is especially difficult to work when my background has a similar blue

**Comment by TheRadicalDreamer** [comment]
Can this be possible? :O

**Comment by TheRadicalDreamer** [comment]
please?  :)

**Comment by TheRadicalDreamer** [comment]
@camoody1
@photopea 

Do you think this is plausible?

**Comment by camoody1** [comment]
![IDontWorkHereLeonGIF](https://github.com/photopea/photopea/assets/73725653/bdac42a0-eddc-4a65-80c4-92073360775b)

**Comment by photopea** [comment]
okay, done! :)
