### ISSUE TITLE
With tracking above 0% and underlining text, the underline becomes segmented

### ISSUE THREAD

**Issue by kayadash** [photopea/photopea#5746]
I am using text with a custom tracking %. When using the "Text" button tool to underline the text, the underline becomes segmented instead of a complete line. This is dissimilar to Photoshop's handling which does not exhibit this behavior when completing the same task.

![rvLqSmI](https://github.com/photopea/photopea/assets/56059822/077bea93-b2c9-46db-9773-3acd66f5e0e0)

**Comment by bluep55** [comment]
How it is in Photoshop :

![Tracking Screenshot 2023-06-14 143004](https://github.com/photopea/photopea/assets/118609932/3ada215a-b6b2-4aec-b376-3f2a6563c4fc)

**Comment by photopea** [comment]
Hey guys, it should work better now :)
