### ISSUE TITLE
Equal gaps moves the edges layer

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5747]
I noticed that when i used Equal Gaps (on Move Tool)

The layer on the edge is moved, and should be an anchor for the others.

https://github.com/photopea/photopea/assets/11801254/fe560638-5f57-46e0-938b-40aff340eb0c

Here is the PSD. Select all layers, and hit equal gaps (horizontally)
[not so equal gaps.zip](https://github.com/photopea/photopea/files/11751026/not.so.equal.gaps.zip)

**Comment by photopea** [comment]
I think it is caused by "rounding error".

Let's say your layers are 1x1 pixel. They are at coordinates 0, 2, and 5

    X-X--X

One gap is 1 pixel, another is 2 pixels, so the average gap is 1.5 pixels. Whad would you like to be done in this case?

Of course, in vectorpea, we will work with exact numbers.

**Comment by TheRadicalDreamer** [comment]
Initially i thought it was better to let it be X-X--X

But that disallows people to get really equal gaps between layers.

And i can move the last layer a bit to the center if i need it to keep the width, taking in account that if it moves, it is because it does not have equal pixels to divide.

So, keep it as is.

Thank you for the explanation.  :)
