### ISSUE TITLE
Default setting on account - Default DPI

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5748]
Can we have a default DPI saved setting in my account?

Not the actual number, like 72.0, but **Pixels/Cm** rather than **Pixels/Inch**

I always work on cm, and it is just a step less to change every time I open a file?

![image](https://github.com/photopea/photopea/assets/11801254/dd7475f3-5188-439a-84c3-ba2f5dc61a95)

Or it not possible?

**Comment by photopea** [comment]
done :)
