### ISSUE TITLE
Nothing is showing up

### ISSUE THREAD

**Issue by BBQisbetter** [photopea/photopea#5749]
![image](https://github.com/photopea/photopea/assets/136750284/6ebfd066-c9ce-47a1-9af7-07e2d3e78f6c)

I am currently using photopea's online photo editor to make a logo. For a moment, I had another tab that I had opened to download a photo for my logo. When I went back to the online photo editor it showed that nothing was there. I made sure to check if my layers were disabled from visibility or not, and surprisingly, they hadn't been disabled. I wanted to try refreshing the tab but realized that I may lose my progress after refreshing. I am looking for assistance in being able to view my layers without losing my progress. I hope I get can get a good explanation of why I am experiencing this. Thank you for your time.

**Comment by camoody1** [comment]
I suggest just saving your project and then restarting Photopea.

**Comment by photopea** [comment]
try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

You should still be able to save your work as a PSD and restart Photopea.

**Comment by ayuanx** [comment]
Same here. Photopea is completely broken.

No matter what file type to open, it always shows a black canvas just like the screenshot above.

Firefox 114.0.2 64-bit

**Comment by camoody1** [comment]
> Same here. Photopea is completely broken.

Do you live in Turkey, by chance?

Obviously, Photopea is not "completely broken" or else Reddit and GitHub would be filled with people like you telling us they couldn't open anything.

**Comment by photopea** [comment]
It is probably a bug in your GPU drivers. Could you update them? Or update your operating system?

In the worst case, you can turn off the GPU acceleration using More - Use WebGL.

**Comment by ayuanx** [comment]
Never mind. It is a bug of **the latest Firefox 114.0.2**
Reverting back to Firefox 102.12.0, everything is fine.

**Comment by photopea** [comment]
Photopea works great for me in Firefox 114.0.2 . Maybe the new version stopped supporting your GPU.

**Comment by ayuanx** [comment]
> Photopea works great for me in Firefox 114.0.2 . Maybe the new version stopped supporting your GPU.

Hmm, that's a bit concerning.... and indeed, after I turned off hardware acceleration in Firefox 114.0.2, photopea just works.
