### ISSUE TITLE
copy-paste / cut-paste is not working

### ISSUE THREAD

**Issue by uscpsycho** [photopea/photopea#5750]
I can select areas and cut or copy them. But when I paste, the paste function does not work.

Tried creating a new layer and pasting to the new layer and that doesn't work either. 

I can't confirm that the copy function is working, but when I cut, the selected area is cut out, so I know cut works and I should be able to paste.

Chrome browser on Chromebook.

**Comment by photopea** [comment]
Nobody else reported such a problem. Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by MobileCowCamp** [comment]
I had the same problem. I did not have the correct layer choosen (Hilighted).

**Comment by photopea** [comment]
I have to close it because of lack of details.
