### ISSUE TITLE
Artboard "invisible" ?

### ISSUE THREAD

**Issue by JanzenJohn** [photopea/photopea#5751]
Im working with a few Artboards right now but one suddenly turned invisible
(maybe i pressed something by accident)

Saving and Loading does nothing so i believe it is a setting somewhere?
however the usual way of hiding artboards does not seem to change anything and is disabled as seen in the layer view
![image](https://github.com/photopea/photopea/assets/51709412/d412a68d-3a01-4142-8651-e3a70747e073)

any ideas how i can restore this artboard without just copying all layers inside into a new artboard ?

**Comment by JanzenJohn** [comment]
Aparantly it moved behind another taskboard, but now i have the issue that i cannot move the artboard away because "You cannot transform whole Artboards"

**Comment by JanzenJohn** [comment]
The Contents of the Taskboard did not move when it did. How do i move a taskboard without moving its content, so the contents are in the same place as before?

**Comment by photopea** [comment]
Hi, what is a taskboard?

BTW. you can not save your work as a PSD file? I think we should focus at it first.

Could you tell me what should I do after opening www.Photopea.com to see a problem which you describe?

**Comment by JanzenJohn** [comment]
> Hi, what is a taskboard?
> 
> BTW. you can not save your work as a PSD file? I think we should focus at it first.
> 
> Could you tell me what should I do after opening www.Photopea.com to see a problem which you describe?

Sorry I meant Artboard

With "saving and loading does nothing" I mean reloading the psd file in another browser keeps that artboard in its (moved) postion but the contents are still at the original location

**Comment by photopea** [comment]
So you have a PSD file which does not look as it should? Could you share that file with us?

Or just tell me what should I do on my computer to see the problem myself.

**Comment by JanzenJohn** [comment]
Yes sorry i did not get a push message for this issue, you can download the file under 

https://spass.johnjanzen.me/photopea/ongong(1)(1)(1).psd

**Comment by JanzenJohn** [comment]
For info it's artboard 6
the artboard itself somehow moved to the lop left, but it should be where the empty space is

however the content itself is still where the artboard would be

**Comment by camoody1** [comment]
Here you go. The pieces were moved down and to the right of their original positions, while the Artboard 6 was in position 1. I just moved each layer back to the correct place. I couldn't find anything in the layer labeled "brett copy 2".

www.photopea.com/#ioWZFQdB1.psd

**Comment by JanzenJohn** [comment]
yeah, i have since "fixed" this by recreating the artboard.
but how did you move the artboard without moving the contents of it / how did this happen, is there a keybind for moving artboards into position 1?

**Comment by camoody1** [comment]
They move separately by default on my device. I just moved the Artboard back into position and then pressed the CTRL key and left clicked on each layer individually to find where they were. Once I found them, I just used the Move Tool on each layer to drag where they were back to their correct position on the toolbar.

**Comment by JanzenJohn** [comment]
ok wierd, when i move the artboard the content move relative to it. ill try later and send a vid

**Comment by camoody1** [comment]
Okay, I checked again since I now know what I'm looking for...

When you move the Artboard itself, you are correct that all of the contents also move. So, when I dragged the Artboard back into position, all of its contents shifted down and to the right. Once the Artboard was in the correct place, I selected all of its content layers at the same time using the Shift key. Then, using the rectangular select tool, I drew a selection box around where I believed the contents to have moved (it doesn't need to be highly accurate, just a generally large rectangle) and then switched to the Move Tool and dragged the invisible contents up and to the left. As the contents reached the area of the Artboard, they appeared on top of the Artboard.

So, you can move the contents separately from the Artboard, but not vice versa.

**Comment by JanzenJohn** [comment]
yes but that moves it into a imperfect place, i somehow moved the artboard without moving the contents, and moving the contents i cant place them exactly where they where first drawn

**Comment by camoody1** [comment]
It's a hand drawn cartoon insect. How "exactly" do they need to be placed? 😆 They all move together as one, so they don't shift in regards to each other. You just have to put them into the correct spot on the Artboard.🤷🏽‍♂️

**Comment by photopea** [comment]
I can not open a link to your PSD file. However, these features in Photopea should work similarly to Adobe Photoshop. So which feature exactly works differently?

**Comment by photopea** [comment]
I have to close it, because nobody is responding to me.
