### ISSUE TITLE
Shape issues in centimetter

### ISSUE THREAD

**Issue by yahyeediting** [photopea/photopea#5752]
When i take shape in centimetter the shape is working
![Screenshot_20230617_132912_Chrome](https://github.com/photopea/photopea/assets/136894727/8a0c4c29-5e07-4a0f-bf15-7cdc8f98b72b)

**Comment by yahyeediting** [comment]
hi guys help me i am use phone i am tiktoker please help me

**Comment by camoody1** [comment]
I don't understand what you need or what your problem is.

**Comment by photopea** [comment]
What should I do to see the problem myself? Can you tell me exact steps? I need some proof that there is a problem.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
