### ISSUE TITLE
increase size multiple shapes bug

### ISSUE THREAD

**Issue by FranckCrea** [photopea/photopea#5753]
1)Create two squares(Using Rectangle tool,default options)
2)Try to scale the two squares at onces
You will see how the edges of the shapes become transparent.

(I don't know if it's a bug of if i have to activate a configuration.)
![image](https://github.com/photopea/photopea/assets/129773797/2b305ef7-3432-473e-abef-d7d761bff036)

**Comment by photopea** [comment]
You have a square 3x3 pixels, 2 pixels gap, and a square 5x5 pixels. It is 10 pixels between the left edge of the small one and the right edge of the big one.

You stretched it, so that the distance of 10 pixels became 11 pixels. So you made it 10% larger. So your small square is 3.3 x 3.3 pixels. How would you like a square of 3.3 x 3.3 pixels to be drawn?

**Comment by camoody1** [comment]
> You have a square 3x3 pixels, 2 pixels gap, and a square 5x5 pixels. It is 10 pixels between the left edge of the small one and the right edge of the big one.
> 
> You stretched it, so that the distance of 10 pixels became 11 pixels. So you made everything 10% larger. So your small square is 3.3 x 3.3 pixels now. How would you like a square of 3.3 x 3.3 pixels to be drawn?

Maybe he drew these using the Pen Tool and expected to see them enlarge without losing their sharpness as I commented in a question I posed earlier this week. It could be, as you explained to me, that he'll have to wait until Vectorpea is released to see what he expects to see.

**Comment by FranckCrea** [comment]
The shapes should increase in size as a  vector: @photopea 
![image](https://github.com/photopea/photopea/assets/129773797/fb59af65-6286-4978-bb8c-d495d45c7280)

**Comment by camoody1** [comment]
@FranckCrea 
Incoming reference #5739

**Comment by photopea** [comment]
You are scaling two shapes at once. The small square grew by one third, the big square grew by one fifth, and the gap between them did not grow at all.

This is not how scaling works in graphic editors. There is no computer program which will enlarge elements by a random scale as you want it.

**Comment by MichalSZZ** [comment]
@photopea  in Photoshop there is something like 'align edges' in the top toolbar (for shape and direct selection etc.).
With that option enabled - all straight shapes are without antialiasing when a pixel is between and not round in size.
ON for one rectangle:
![obraz](https://github.com/photopea/photopea/assets/38118273/848a078b-8bd0-4e16-bdb4-df16bb7e4c60)
OFF:
![obraz](https://github.com/photopea/photopea/assets/38118273/2f34b096-1a4e-4435-ad22-9c4f53829e34)

Maybe that is the solution?

**Comment by photopea** [comment]
I can not make Photoshop render squares as in your example. How did you do it?

BTW. I think I will ignore all Photopea requests for the rest of the year, as I want to focus at working on Vectorpea.

**Comment by MichalSZZ** [comment]
I have draw a shape without snapping to pixel grid with 'align edges' enabled. 

That isn't a request for a new functionality. I only show a method to view pixel perfect shapes as Photoshop has.

Keep focus on Vectorpea and fix only bugs.
