### ISSUE TITLE
Photopea crashing browser & internet (too many requests)

### ISSUE THREAD

**Issue by RealPandarex** [photopea/photopea#5756]
Hello! Whenever I want to use Photopea, the site will either be unresponsive on Edge and Chrome, or will crash my entire internet on Edge, and Chrome. 

As seen [here in these screenshots](https://ibb.co/album/KxJCFN), the developer console & network tab are getting spammed with more than 400 requests and errors in less than 10 seconds - which probably crashed my internet and sometimes the browser I assume.

### **Steps to Reproduce:**
1. Open Edge or Chrome browser. (latest version)
2. Navigate to photopea.com.
3. Upload an image, or photoshop file. I just copied and pasted an image from my clipboard that I received.
_This may only be reproduceable on weaker connections. Not sure, though._

### **Expected Behavior:**
Photopea should load properly and allow for smooth usage without any a) significant performance browser freezes/crashes issues or b) internet crashes after a few seconds or minutes.

### **Actual Behavior:**
Upon accessing Photopea, I encountered two primary issues:

- Unresponsiveness: The site becomes unresponsive once file is imported, making it impossible to utilize any of the features. The interface freezes, and interactions with the application are not registered. After some time clicking, the entire browser freezes.

- Internet Crash: In most instances, attempting to access Photopea results in a complete crash of my internet connection. This issue affects not only the browser but also disrupts the connectivity of other devices connected to the same network.

### **Potential Workaround:**
Enabling the "Block all cookies (not recommended)" option in Chrome seems to partially alleviate the issue. However, this workaround disables ads and significantly reduces or eliminates the excessive requests being sent. With other extensions like uBlock Origin it does also seem to work.

### **Additional information**
Operating System: Windows 11 Pro 10.0.22621 Build 22621
Edge Dev Version: 116.0.1908.0
Chrome Version: Version 114.0.5735.134
I [attached screenshots in an album](https://ibb.co/album/KxJCFN) because this issue would be too long when I included 6 more screenshots.

Without any blocking method, I am unable to use Photopea. Feel free to leave a comment if you need more information, or need someone with a weak internet connection to try a possible fix. :)

**Comment by photopea** [comment]
There are hundreds of thousands of people, who use Photopea in Chrome and Edge every day, and nobody reported such a problem. I can open Photopea right now, and open a file in it, and it works fine.

How many browser extensions do you have? I think some of them could be mining bitcoins etc. Please, report only problems which you can make happen with all extensions disabled.

Could you record a short video of the problem happening? And start by showing us that you have no extensions and only then open www.Photopea.com .

**Comment by RealPandarex** [comment]
Hi, thank you for your response!

On Edge Dev, I actually use a bit amout of extensions, but just one on Chrome - and that was Dark Reader.

I tried recording a video, but accidentally recorded a black screen. It actually crashed my internet, with Dark Reader installed. I ended up removing Dark Reader, and made a sucessful recording with phone recording as side recording. However, this try did not crash my internet after trying it a few times.

With just Dark Reader installed, I still get to 400 requests in a matter of seconds. I also somehow instantly see 900 network requests ONCE I press "Agree" on the site. That also made my brwoser slow and the site unresponsive.

The AHA Music recognition aswell as Google Docs offline extensions was installed, too, but deactivated.

That it all works normally for you and many others is clear to me. I still find it surprising why this happens, though. (And Chrome is not my main browser).

### My plan now:
I will reset my Chrome, try different things, disable all extensions and check settings + try different browsers. I will keep trying to find the cause and let you know here in the comments if there is any news. If I have more information, I'll let you know and try to provide a video.

**Comment by RealPandarex** [comment]
Hello, here am I with news:

I tried lauchning photopea.com on my Edge browser with extensions installed, it first didn't respond and then my internet died. Needed to my browser. Firefox worked fine, though.

Then I wanted to try with a clean installation browser - so I just freshly installed Google Chrome Dev. Opened it and launched photopea.com. It first went all well, until I pressed accept. The requests came in.

To ensure a fair test, I closed the browser, opened Chrome dev, started the recording and went on photopea again. This time, not many requests came in; Probably because the ads did not load. A few seconds later, I wasn't able to access any website and my phone also said "No Wi-Fi".

_While compressing my video to less than 10 MB, Photopea oepened in the background which, again, made my internet disconnect. This time just a few seconds and no restart was needed._

https://github.com/photopea/photopea/assets/113469471/9ac13b74-cefe-415d-9439-8d831a53309b

**Comment by photopea** [comment]
You said several times, that your router crashed. A website should not be able to crash your router. Are you sure you have a stable connection to the internet? Do other websites work well?

Also, we do not accept bug reports about running Photopea in experimental browsers. I should have sent you this first: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

So please, we need three conditions (which 99.9999 % of ours users have): a normal internet connection, a standard web browser and no site-modifying extensions. Could you record a video with these three conditions?

**Comment by RealPandarex** [comment]
Yes, other websites do work. I don't have the fastest connection, but it does work. But it shouldn't crash anything.

I have the feeling it has something to do with ads. If I don't agree, there won't be 1600 requests sending. Could you please check if you are having any errors or flooded network requests coming in? That would be awesome! 😊

And for the post: I have already viewed that post before writing this issue and taken all steps.

On Chrome stable, I wasn't able to reproduce it. (No extensions and with extensions called "Google Docs Offline". This problem exists for a few weeks/months. Before that, Photopea could be used like it should. And other people don't seem to have this. I ask you to please leave this issue open. I will continue to troubleshoot tomorrow and the next days. Are you okay with this?

**Comment by camoody1** [comment]
Just to add a bit of info regarding one of your extensions. I use the Dark Reader extension on my Edge browser, and I have no issues with using Photopea. Photopea is working smoothly for me whether I'm logged into my premium account or not.

Do you, perhaps, have an antivirus or firewall rule on your PC that is preventing Photopea from accessing its Ad sites? I see from the video that you posted that Photopea "thinks" you have an ad blocker installed, even though you say you have no extensions installed. That seems odd.

**Comment by RealPandarex** [comment]
Hello camoody1,

I also find that very odd. For me, Photopea used to work just fine back then. Before you commented, I recorded a video using Opera GX (stable) this time including no extensions. The default extensions are/were disabled.

I just opened up Photopea's website, and internet gone. This is no coincidence. And it is not because I opeend the developer tools since it also crashed when I used Photopea normally.

Your guess with the Firewall is actually a pretty good tip! I will try that. I will also see if it works on my Laptop.

I absolutely love Photopea and would like to make it better, and help fix this issue.

https://github.com/photopea/photopea/assets/113469471/bef81535-728f-4019-8244-4be28c96e78f

**Comment by photopea** [comment]
A computer connected to a wifi router should not be able to turn off or restart the router. That simply makes no sense to me. You should return that rounter and buy a proper one.

**Comment by camoody1** [comment]
Are you using a VPN? I see in your latest video that it says VPN in the top toolbar. Could this be an issue? What does the "Change Consent" button do in the Ad section? I don't see that button on my Edge or Chrome browser.

**Comment by RealPandarex** [comment]
> That simply makes no sense to me.

I know, right? 😅 All three conditions have been met multiple times.

> Are you using a VPN? I see in your latest video that it says VPN in the top toolbar.

The VPN was disabled. This is also the case for other browsers.

> What does the "Change Consent" button do in the Ad section? I don't see that button on my Edge or Chrome browser.

When you first open up Photopea, it will ask you for your consent. It's about cookies, data collection, product improvements, etc. Before I don't agree, it won't display ads nor send any requests.

You will see it one time when you open Photopea in an incognito tab, for example.

**Comment by photopea** [comment]
I will close it now. If you still have problems, let me know. But nobody ever reported such a problem, Photopea is a regular website, the same as any other website.

**Comment by RealPandarex** [comment]
Hi! I can indeed confirm that this is solved. After resetting my PC, all issues regarding internet crashes are gone.

I wish you a happy new year!
