### ISSUE TITLE
Lost everything

### ISSUE THREAD

**Issue by EllaRosewood** [photopea/photopea#5758]
Did a whole creation in Photopea, which doesn't autosave.
Accidentally hit the back button on my mouse.

"Catastrophic failure" This overrides the warning "Do you want to leave this page" just takes you back to the previous web page and everything is lost. Won't be using Photopea again, too much risk, very upsetting.

T.T

**Comment by camoody1** [comment]
It actually does auto-save every five minutes. Or, at least, that's the way it's supposed to work. It's supposed to protect from just such a situation. I assume you reopened Photopea and your project didn't reload on its own? Mine usually does. Very sorry about your loss.

**Comment by photopea** [comment]
If you go to a previous website from Photopea, it should ask you "Your unsaved work might be lost". If you confirm it, still, you will lose your unsaved work. That is how it should work.

Did the browser not ask you about losing your work?

**Comment by ErrorBot1122** [comment]
how do you open an autosave?

**Comment by photopea** [comment]
Maybe try this: https://www.photopea.com/tuts/photopea-opens-up-old-files/

**Comment by ErrorBot1122** [comment]
I don’t think this will work as it’s been a while since I opened my file and I’ve opened other files since then. (More info about my situation [here](https://www.reddit.com/r/photopea/comments/152g415/is_there_any_way_of_accessing_photopeas_autosaves/))
