### ISSUE TITLE
Keep brush size update with [ ] without disappearing

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#576]
The brush cursor disappeared everytime when adjusting size with [ ]

This is very counterproductive for a size adjusting feature

**Comment by photopea** [comment]
Ok I closed your previous issue regarding this.

I tried it in Chrome on Windows and everything works well. What browser and OS do you use?

**Comment by photopea** [comment]
What happens with the cursor if you switch tools wit keyboard (e.g. V for Move tool, then B for the Brush tool) ?

**Comment by photopea** [comment]
Does the cursor appears again when you move the mouse?

**Comment by hgs54371** [comment]
I'm on a mac, both firefox and safari do this

In brush tool, hit v, switched to move tool, standard cursor shows.
In move tool, hit b, switched to brush tool, brush cursor hides.

The brush cursor hides whenever there's a key pressed (keys not for any other tools),
and will come back with cursor movement

**Comment by photopea** [comment]
I saw the same behaviour in Chrome OS. I think it is the default behaviour in some operating systems.

I found this: https://apple.stackexchange.com/questions/71661/how-do-i-disable-hiding-of-the-mouse-pointer-while-typing-text

BTW. do you have access to Adobe Photoshop or Gimp? What happens in those programs when you do the similar thing?

**Comment by photopea** [comment]
I am not sure if the webpage can prevent this default behaviour, just like a native app can.

Can you go here: http://jsfiddle.net/p45f44zb/3/  to the bottom right area, press some keys and see if the cursor disappears? If you are familiar with Javascript programming, could you try to find a solution by changing the code on the left?

**Comment by hgs54371** [comment]
In that area, any key press still hides cursor

I can only try basic css, but js cannot

**Comment by photopea** [comment]
And what is the experience of using a quick Hand tool - pressing and releasing Spacebar? How does it work?

**Comment by hgs54371** [comment]
When holding space, the hand tool is usable, but the hand only shows and flickers when the cursor is Moving, when still, it hides

**Comment by photopea** [comment]
So seems like this is not fixable today :(  Lets try to reopen it in a year or two. Hope they will find a solution.
