### ISSUE TITLE
Logging is not enabled

### ISSUE THREAD

**Issue by bnovak99** [photopea/photopea#5761]
I get the error message "Logging is not enabled" when I try to save an image for the web on a Mac using CMD+shift+option+S

**Comment by bnovak99** [comment]
<img width="474" alt="image" src="https://github.com/photopea/photopea/assets/25965963/4d3aeb68-5a24-4018-b2a7-66a57dd38ebe">

**Comment by photopea** [comment]
Try this, let me know if it helped: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
