### ISSUE TITLE
lasso tool glitch

### ISSUE THREAD

**Issue by skywalker005** [photopea/photopea#5762]
when i cut images using the magnetic lasso, the zoom in/out function doesn't work at all, and the cropped image has sharp color around the edges (it's been either black or white every time, so far) when they aren't supposed to be there
![Screen Shot 2023-06-18 at 10 33 09 PM](https://github.com/photopea/photopea/assets/101187093/0cf52c93-2213-4302-a079-63607457a727)
![Screen Shot 2023-06-18 at 10 33 52 PM](https://github.com/photopea/photopea/assets/101187093/0f73e794-9386-496d-86e5-324c5379a59c)

**Comment by photopea** [comment]
You mention the magnetic lasso, but your screenshot is from the Refine Edge. How is it related?

**Comment by skywalker005** [comment]
Because that's the tool I was using to get to 'refine edge'

**Comment by camoody1** [comment]
The Refine Edge Tool and the Magnetic Lasso Tool are two entirely different tools. The Refine Edge Tool is available with any selection tool.

When trying to use the Zoom In and Zoom Out tools in the Refine Edge Tool, make sure you're clicking to zoom on the TOP image I'm the tool. It doesn't work if you click on the bottom image.

**Comment by photopea** [comment]
What should I do with a magnetic lasso, so that the "zoom function does not work"? What is a "zoom function" of a magnetic lasso?

**Comment by photopea** [comment]
I have to close it because of lack of details.
