### ISSUE TITLE
Feature Request - Add more units to Width and Height input boxes.

### ISSUE THREAD

**Issue by bluep55** [photopea/photopea#5763]
When using the Shape and selection tools to create a rectangle or ellipse in the Fixed Size mode, Photoshop has a selection of different units available to create these. Right clicking in the boxes shows what units are available.
Would it be possible to add extra choices to Photopea, which only has the option of pixels?

![Selection units](https://github.com/photopea/photopea/assets/118609932/e3a3b23f-183d-4af9-aa21-566785d33ac9)

**Comment by TheRadicalDreamer** [comment]
I believe the default are only pixels. :(

I also would like to have this feature

Or maybe it should follow the project dimensions.

For example i have a square of 100x100 (wxh) and i get a 35.mm square  ┐( ∵ )┌

**Comment by photopea** [comment]
I have implemented it! It always use the units of rulers now.

It was added to the Selection tools, Crop tool, and Vector Shape tools.

**Comment by bluep55** [comment]
👍
