### ISSUE TITLE
Vertical Align text box is not centered

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5764]
This is a vertical aligned text box on a squared canvas of the same size.

https://github.com/photopea/photopea/assets/11801254/8990efbe-8277-4a7f-8b53-f2abda55c048

This comes from the issue https://github.com/photopea/photopea/issues/5737

**Comment by TheRadicalDreamer** [comment]
This is an intended behaviour?

**Comment by photopea** [comment]
If you delete all letters "d" from the top line, should the whole text jump up? (because "a" and "s" would be the tallest letter).

Similarly, if you deleted all "p" from the bottom line, should it jump down?

**Comment by TheRadicalDreamer** [comment]
No it does not jump / modify itself when i delete the "d" or "p" on the top / bottom respectively.

My issue is related to the center of the textbox 

I have this textbox that is centered on the canvas:
![image](https://github.com/photopea/photopea/assets/11801254/02e9338f-d28f-4cd4-bf3e-cae23aa48cde)


But the text inside is not centered:
![image](https://github.com/photopea/photopea/assets/11801254/c6795916-df4f-4f13-99fd-399ace04c0ab)

**Comment by photopea** [comment]
This is just how our centering mechanism works. It is based on the number of lines and the size of a line. It ignores shapes of letters.

**Comment by TheRadicalDreamer** [comment]
Perfect.
So it is working properly.

Thanks!
