### ISSUE TITLE
Magic Replace Tool Not Working - Throws Error in Console

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5765]
When users try to use the Magic Replace Tool, no image is returned. When I looked into the browser console, I found the following error:

![image](https://github.com/photopea/photopea/assets/73725653/7bcde7d9-1293-4269-8822-ec23628f6f0f)

Several people have now reported error in Reddit, Discord and Facebook. Not sure when the problem started. Maybe dezgo finally deprecated their old API. 🤷🏼‍♂️

**Comment by sheep-dk** [comment]
I got the same problem

**Comment by camoody1** [comment]
> I got the same problem

Yeah, it's an "everyone" problem. I doubt this is a change the Photopea developer made because he should have been asleep for several hours and the problem seems to have just started within the last couple of hours. Could be the third party provider changed something about their API. We'll have to wait until @photopea wakes up from his slumber.

**Comment by xyzzart** [comment]
it is happening sometimes...

**Comment by photopea** [comment]
We ran out of money and our partner blocked the service for us. We are trying to fix it by sending them $3000, we are waiting for their response. Sorry for the trouble, I did not expect that this feature will be used so much.

**Comment by camoody1** [comment]
> We ran out of money and our partner blocked the service for us. We are trying to fix it by sending them $3000, we are waiting for their response. Sorry for the trouble, I did not expect that this feature will be used so much.

Are they still offering a 20% price cut if you switch to their new API service?

**Comment by gse123** [comment]
Fingers crossed they get it back live soon!

**Comment by sohoss** [comment]
나만 그런것이 아니었군.
가끔 사용하는 기능인데, 작동을 안하니까 매우 불편합니다.
지나가는 무료사용자

**Comment by sheep-dk** [comment]
> We ran out of money and our partner blocked the service for us. We are trying to fix it by sending them $3000, we are waiting for their response. Sorry for the trouble, I did not expect that this feature will be used so much.

Please keep update that when it will work? Thank you very much.

**Comment by photopea** [comment]
Hi guys, the Magic Replace should work again. If it does not work, hard-reload Photopea, or clear your cache, or open Photopea in an hour from now

**Comment by jpgoodnews** [comment]
still not working with prompts, 
if u leave the prompt empty, it will try to fix the image
for example if you circle the hands that has six fingers it will try to draw only five, etc
but i can't give any prompt to put new objects on the screen

**Comment by svgandme** [comment]
Is there a smaller limit on the Magic Replace function now? I tried the same workflow I've used successfully in the past but Magic Replace isn't working but if I select a small area it does work.
https://www.loom.com/share/b3fc07dfd2c5439babaa06afeeec8e08?sid=d0cf8454-cc38-42db-98e2-f17caa5d7c5a

**Comment by photopea** [comment]
If the area is too large, there should be a message telling you about it. I need to see the problem happen myself. Could you maybe share your image with us?

**Comment by svgandme** [comment]
@photopea Sure here's an example image that I tested and it's not working to remove the seam using Magic Replace (same process shown in the video) https://www.dropbox.com/scl/fi/bfn2rlffur1u09gtvz7gd/svgandme_Vintage_beautiful_colorful_3d_tooled_leather_of_cowboy_caffe4ab-bc65-4b76-ad67-f23af20197b1.psd?rlkey=duxdewon781hkuodg06xf1fjj&dl=1

**Comment by camoody1** [comment]
@svgandme The limit is 1000px by 1000px. Your image is 1024px. If you reduce the size of your canvas to 1000px tall and then scale your image down to fit that height, you can select the entire seem and Remove it with the Magic Replace tool. I tested it with your image and it works great.

**Comment by camoody1** [comment]
@photopea Btw... I tested his image at 1024px tall and no message was posted. It just didn't do anything to the selected area. Once I reduced the height of the canvas to 1000px and tried it again, the change occur as expected.

**Comment by photopea** [comment]
There really was a bug! It should be fixed now.
