### ISSUE TITLE
Copy and paste shrinks

### ISSUE THREAD

**Issue by Ljhwaf** [photopea/photopea#5766]
When I copy and paste something from another slide, It shrinks and becomes very small and the text size breaks

**Comment by camoody1** [comment]
Sounds like you're copying from a low resolution canvas and pasting to a high resolution canvas. If the canvases were the same size, the image would look the same when pasted.

**Comment by photopea** [comment]
I am pretty sure you are copying from a 10x10 inches document into a 100x100 inches document, so the copied content looks smaller in the new document (but it still has the same size). Use the Free Transform tool to enlarge objects.
