### ISSUE TITLE
batch editor not working

### ISSUE THREAD

**Issue by uppermillwill** [photopea/photopea#5767]
when I go to File>Automate>Batch I get the options as described in your help doc. However, the options for Action and Action Set are both blank and when I upload files and click Process Images, nothing happens.

Got this error in console if it helps: 

pp.js:12591 Uncaught TypeError: Cannot read properties of undefined (reading 'qH')
    at bb.Ok (pp.js:12591:14)
    at e$.T (pp.js:10561:49)
    at fS.T (pp.js:10566:77)
    at i7.jr (pp.js:10639:95)

**Comment by photopea** [comment]
You need to record actions, or load the ATN file: https://www.photopea.com/learn/actions

**Comment by photopea** [comment]
You can also buy a book about Adobe Photoshop to learn how it works.
