### ISSUE TITLE
Abusive amount of logged operations to the console

### ISSUE THREAD

**Issue by g-freecss** [photopea/photopea#5768]
Is there a particular reason for the `pp.js` script to keep logging messages to the client's browser console?
Now it even log my adobe script instructions sent via web messaging, which was not happening before. 
That is actually not very cool. Just wanted to know what is the reasoning behind all these console.logs.

Thanks

**Comment by Pt-home** [comment]
https://www.photopea.com/api/live

**Comment by g-freecss** [comment]
My problem is precisely that, the logging to the console of the user scripts sent via `postMessage`. This was not happening a month/two months ago. And I think that in my own application with a custom integration with photopea, the users of my application being able to see those scripts on browser's console, its just odd.

Since this was not happening until recently, I just wanted to understand what is the purpose of logging it to the console, since it does not have implications on functionality. And since I cannot silence them on my side, I am here asking to understand the point.

**Comment by Pt-home** [comment]
At the same time, a couple of weeks ago, another person asked the console to display more information for debugging convenience) How many people - so many different tasks and approaches. Can't your application clear the console? I just never had such a task

**Comment by Pt-home** [comment]
Out of curiosity, I have now put in my plugins console.clear(); in the right places and the console is perfectly cleaned, even from the iframe...

**Comment by photopea** [comment]
sorry, these scripts are not logged to the console anymore.
