### ISSUE TITLE
Tiny layer icon

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5769]
![image](https://github.com/photopea/photopea/assets/11801254/a523eb0d-c004-4871-878c-d7787e0bbb65)

Why the adjustment layers are SO small??

Before they had a square thumbnail

**Comment by camoody1** [comment]
Change your Layers option from "Thumbnails by Layer" to "Thumbnails by Document".

**Comment by TheRadicalDreamer** [comment]
No. it still happens when i change that setting.

**Comment by camoody1** [comment]
Mine is working fine. 🤷🏼‍♂️

**Comment by TheRadicalDreamer** [comment]
I know. The rest of my files are ok.

But check this one out: 
[Small adjustmen layer.zip](https://github.com/photopea/photopea/files/11841164/Small.adjustmen.layer.zip)

Create an brightness adjustment layer

**Comment by camoody1** [comment]
It's because your canvas is super thin. If you increase the canvas height so that it's almost a square, the thumbnails will match.

**Comment by TheRadicalDreamer** [comment]
But this only happens with adjustment layers that does not have a preview on the thumbnail
![image](https://github.com/photopea/photopea/assets/11801254/4bb04fec-aec8-4e4b-821a-aa297faa3ec2)


I believe this didn't happen before. I believe all those icons remain the same height of the pattern or color fill adjustment layer

**Comment by TheRadicalDreamer** [comment]
This is still an issue.

You can download the PSD and check.

I still believe that the icon size should be fixed

**Comment by TheRadicalDreamer** [comment]
This is the intended behaviour?

**Comment by photopea** [comment]
In general, the aspect ratio of a thumbnail should be the same as the aspect ratio of your document. The width and the height of a thumbnail is limited by 40 pixels.

The Text layers and the Fill layers have square thumbnails with a minumum size of 16 pixels. I have added the same rule for adjustment layer thumbnails.
