### ISSUE TITLE
Cannot paste image as new layer/doc in safari mac

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#577]
The method of import image from other web tab into photopea without saving locally first, by right click, copy image then cmd-v(paste) is not working in safari mac

The "paste" under top menu "edit" is greyed out most of the time, and seems only usable when cursor is in text field

Drag n drop also only respond as open the link in the photopea tab

**Comment by photopea** [comment]
Do you know about any website, where copy-paste of images works (in Safari)? 

We need to know, if it is even possible. If it is not, you should report the bug to Apple, or use another browser for it.

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by hgs54371** [comment]
Copy image address, then Open from url works for open as its own project, have to drag back to current project.
A feature to create new layer into current project from url would be good.

Like I mentioned, the "paste" is usable only when in text field, so this process needs/can to be done through text/url

**Comment by photopea** [comment]
Can you confirm, that you are using the lates Mac OS and latest Safari?

**Comment by hgs54371** [comment]
They're updated, maybe they keep "paste" only usable in text field for security "concerns", 

Anyways loading with URL is still usable, as a new project, but not as a new layer right now
