### ISSUE TITLE
Convert [Text] to Shape is currently available only through a contextual menu

### ISSUE THREAD

**Issue by xilehence** [photopea/photopea#5770]
Convert [Text] to Shape (which functionality is important for crafting text art) is currently available only through a contextual menu (right-clicking a text layer): there is no corresponding menu main command, and that command cannot even be found through the help search utility.  However, tablet users (i have an iPad) cannot easily invoke RMB (right mouse button), so it’d be convenient if a corresponding ordinary menu operation could be provided, perhaps under “Layer” in the top menu bar. (Photoshop has a separate “Type” menu.)

**Comment by photopea** [comment]
I have added it to Layer - Text - Convert to Shape
