### ISSUE TITLE
Selecting multiple layers and invoking a layer style applies the effect only to the bottom-most layer

### ISSUE THREAD

**Issue by xilehence** [photopea/photopea#5771]
Selecting multiple layers and invoking a layer style applies the effect only to the bottom-most layer. I think that the effect should be applied respectively to all selected layers. (Of course multiple layers could be grouped into a folder to which an effect is applied, but that is a different operation and generally looks different, besides not allowing subsequently articulated adjustment of the multiply added style.)

**Comment by photopea** [comment]
I think it would be very hard to formulate how this feature should work.

If one layer has a stroke and another does not, and you select them both, and open the Layer Style window, should it show the Stroke as enabled or disabled? There are many other similar questions.

I recommend either using a folder, or copy-pasting layer style between folders. Or you can define a new style in the style gallery.
