### ISSUE TITLE
Default application language.

### ISSUE THREAD

**Issue by DmYankovskyi** [photopea/photopea#5772]
I consider it a mistake the default language of the application is in rus., make the default language in Ukrainian or English, given that the creator of the application is Ukrainian and should not focus on orcs. Thank you!
![123](https://github.com/photopea/photopea/assets/135584984/ca73f1d7-d8b6-45ff-9a01-2f1128625464)

**Comment by camoody1** [comment]
What URL site are you using to view Photopea? Photopea's header never reads "Photoshop Online". You should only view the application at www.photopea.com

Also, i believe the default language selection is IP based. I love in the US and my default language is English. If you don't want to read Russian, use a VPN that links you to an English IP address.

**Comment by photopea** [comment]
Our website is www.Photopea.com .

Anyone can insert Photopea into their website and set the default language to any language.

What do you mean by "focus on orcs"?
