### ISSUE TITLE
Fake Photopea Editor Chrome Extension In Chrome Web Store

### ISSUE THREAD

**Issue by m32b64** [photopea/photopea#5773]
https://chrome.google.com/webstore/detail/photopea-online-photo-edi/ajmakemidedfmmlhamallpgmphpbnkdh

ALSO: Other interesting Photopea related extensions: https://chrome.google.com/webstore/search/photopea

**Comment by m32b64** [comment]
![image](https://github.com/photopea/photopea/assets/67080857/7332721c-731a-46be-9213-08595689d6d2)

**Comment by camoody1** [comment]
Look at the bullshit they wrote at the very bottom of their extension listing:

#Disclaimer: Please note this extension is NOT made by Ivan Kutskir and is made by an independent development team. All copyrights belong to their respective owners. It uses Photopea API.

Goddamn thieves

**Comment by photopea** [comment]
Wow, I dont mind when people insert Photopea into their website. But they should not call it "Photopea", as 99% of people would think it is made by us.

Sadly, I am not the owner of "chrome.google.com" website, so I can not remove it from there :( do you know how can we get it deleted? Or could you try to write to the person who published it there?

**Comment by camoody1** [comment]
You can report the extension from a link on the page. One of the options for reporting is that the extension uses copyrighted work. I tried to do that, but it asked me if I was the owner of the copyright and, of course, I'm not , so it wouldn't let me continue with my complaint. You'll need to do it yourself.

**Comment by m32b64** [comment]
Hey there,

Thanks for reaching out. Unfortunately, I won't be able to report the
extension for using copyrighted work as I'm not the owner of the copyright.
Have you tried reaching out to Ivan Kutskir, the owner of the copyrighted
work to see if they can report it themselves? Let me know if there's
anything else I can do to assist.

Best,

Michael Barrett

**Comment by camoody1** [comment]
@m32b64 I was responding to @photopea which is actually Ivan. I was actually telling him to report the extensions, not you. :)

**Comment by m32b64** [comment]
Gotcha. Hopefully not much red tape. But, even if there is, he should
pursue this

**Comment by photopea** [comment]
I asked the owner of OnlinePhotoSoft.com to fix it. Owners usually respond faster than big corporations.

**Comment by bluep55** [comment]
Also, it's absolutely unbelievable that the Chrome webstore are providing extensions which are specifically designed to block Photopea ads. Don't these people understand that without ads Photopea wouldn't exist 🤷‍♂️

**Comment by photopea** [comment]
I am too lazy to report it anywhere, so I just blocked it for the domain - Photopea can not be used at https://www.onlinephotosoft.com anymore.

**Comment by m32b64** [comment]
I submitted a review, warning those interested in Photopea that the
extension is in violation of the Chrome Web Store TOS and directed them to
the Photopea Web App.
