### ISSUE TITLE
Loggin from Dropbox is not working  it just appears white background

### ISSUE THREAD

**Issue by Chizuz** [photopea/photopea#5775]
Loggin from Dropbox is not working ( it doesnt appear the button to log in your dropbox account) it just appears a white background

**Comment by camoody1** [comment]
You may have some extension installed that is blocking window popups. When I click on DropBox, I get a separate window opening asking me to login to DropBox. Try opening Photopea in "In Cognito" mode to see if it works with no extensions running.

**Comment by photopea** [comment]
Hi, do you mean storages on the left side? I just tried it and it works for me.

Try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by Chizuz** [comment]
well i dont know what you did but now it works, thank you, I tried in incognito and maybe it wasnt working just in my browser ( im using edge)

> Hi, do you mean storages on the left side? I just tried it and it works for me.
> 
> Try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
Let me know if you have any problems.
