### ISSUE TITLE
flascing work area

### ISSUE THREAD

**Issue by SuperDamiano** [photopea/photopea#5778]
the work area flasc me during i draw and other functionality therefore i work bad

**Comment by camoody1** [comment]
Do you mean "flashing" work area? I don't know what "flashing" means.

If your screen is flashing while using Photopea, this certainly isn't a problem with the application. That sounds like a problem with either your PC, video card or video card drivers.

**Comment by photopea** [comment]
Sorry, I do not understand what do you mean :(

Maybe try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because the person did not respond.
