### ISSUE TITLE
Export PDF - Color fill adjustment layer is not visible

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5779]
I don't know if this is the intentional behaviour, but before the adjustment layer color fill in particular did export correctly when exported to PDF, but now  i get black colored layer

![image](https://github.com/photopea/photopea/assets/11801254/0ed0357d-5848-4897-9e6d-bb19fb101277)

**Comment by photopea** [comment]
thanks, it should be fixed now.
