### ISSUE TITLE
use a dropper mouse cursor with the color-picker tool?

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#578]
it seems to work in modern browsers with simple css style:

`cursor: url('..../something.svg');`

right now it just uses whatever default cursor was before, which is confusing

**Comment by photopea** [comment]
Hi, there is a problem in Firefox with custom cursors. They are always scaled by devicePixelRatio. We use them for brushes, and they are unusable in Firefox.

We will start adding custom cursors once it is fixed. https://bugzilla.mozilla.org/show_bug.cgi?id=1425694
