### ISSUE TITLE
problem using mouse on ipad

### ISSUE THREAD

**Issue by yoyo399** [photopea/photopea#5780]
if I drag and drop photos, the mouse doesn’t work. like i can’t edit with it at all, and its very very very annoying.

**Comment by camoody1** [comment]
Dragging and dropping works fine for myself and thousands of others. You likely either have a browser issue or a PC issue. What browser are you using?

Try to troubleshoot using these steps first.
https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because the person did not respond.
