### ISSUE TITLE
Resizing doesn't affect Photopea

### ISSUE THREAD

**Issue by Kade-github** [photopea/photopea#5781]
It seems like it doesn't want to fit the viewport inside, and it's mostly annoying when I have a window smaller and then I maximize it.

I've only tested this on Microsoft Edge, so it might be an Edge problem.

https://imgur.com/ZMceiIb

**Comment by camoody1** [comment]
I use Microsoft Edge and it works just fine. I see that you're not logged into Photopea, yet you have no ads showing. That tells me that you have one or more browser extensions installed... or a virus protector... that is blocking some parts of the app. It's quite likely one of these extensions is causing your issue. Try running Photopea in Private mode with no extensions. See if it works correctly then. You'll need to disable all your extensions and then re-enable them one at a time to find which one is causing the problem.

**Comment by photopea** [comment]
I think you use browser extensions which break the behaviour of Photopea. 

If you installed an extension without knowing that it will do this to Photopea, it is probably a bug, and you should report it to the creator of that extension.

Photopea always works perfectly, unless you give your extensions a permission to modify Photopea (which you did).
