### ISSUE TITLE
FR: Noise tool

### ISSUE THREAD

**Issue by DevBadger10** [photopea/photopea#5782]
It would add some noise to the layer. It would have the option of just putting noise on it, with either grayscale or color, or making noise based on the layer. For example,
<img width="449" alt="image" src="https://github.com/photopea/photopea/assets/104037142/1dd6a33f-9ee5-4af0-b2fb-729d68d481b9">
would become
<img width="451" alt="image" src="https://github.com/photopea/photopea/assets/104037142/0941d2d7-0f4d-48a7-9558-3b4595f94099">
So it'd just be a handy little wrapper tool for selecting and then adding noise.

It would go in the same category as the Blur, Smudge and Sharpen tools.

**Comment by camoody1** [comment]
There's literally already a Filter called Noise where you can... wait for it... add noise.🤷🏼‍♂️

**Comment by MichalSZZ** [comment]
![obraz](https://github.com/photopea/photopea/assets/38118273/159ac966-5fb6-420c-86a2-748a77376d17)

**Comment by DevBadger10** [comment]
> There's literally already a Filter called Noise where you can... wait for it... add noise.🤷🏼‍♂️

I know, that's literally how I got the example, but there's the filter to blue and a seperate blue tool. What I'm suggesting is a **seperate tool to add blur**.

**Comment by camoody1** [comment]
> > There's literally already a Filter called Noise where you can... wait for it... add noise.🤷🏼‍♂️
> 
> I know, that's literally how I got the example, but there's the filter to blue and a seperate blue tool. What I'm suggesting is a **seperate tool to add blur**.

I think this last statement is all mixed up. I assume you mean "blur" and not "blue". And I assume you meant to write "**separate tool to add noise**".

So, you want an actual tool, like the Brush Tool or the Paint Bucket Tool, that you can paint over an area to add noise, instead of using the noise filter. Is THAT what you mean?

**Comment by photopea** [comment]
BTW. there is a Sharpen tool, and when the image has the noise, it will make that noise stronger.

I also dont know what you mean.

**Comment by DevBadger10** [comment]
> > > There's literally already a Filter called Noise where you can... wait for it... add noise.🤷🏼‍♂️
> > 
> > 
> > I know, that's literally how I got the example, but there's the filter to blue and a seperate blue tool. What I'm suggesting is a **seperate tool to add blur**.
> 
> I think this last statement is all mixed up. I assume you mean "blur" and not "blue". And I assume you meant to write "**separate tool to add noise**".
> 
> So, you want an actual tool, like the Brush Tool or the Paint Bucket Tool, that you can paint over an area to add noise, instead of using the noise filter. Is THAT what you mean?

Yes 
 


> BTW. there is a Sharpen tool, and when the image has the noise, it will make that noise stronger.
> 
> I also dont know what you mean.

That makes it stronger, yes, but it'd be nice to paint some directly on to the image instead of having to fiddle around with lasoo select and not being able to get all of it. A mouse can give you more dexterity when using. 
The refine edge functionality can also work, but it'd just be a tad more convenient to have this.

**Comment by photopea** [comment]
I still think that nobody needs it, as there already are hundreds of ways to do it.

Just make a copy of your layer, apply a filter to it, add a raster mask and paint into the mask.

Or make a smart object, add a noise smart filter, and paint into a mask of a smart filter.
