### ISSUE TITLE
Convert to color profile

### ISSUE THREAD

**Issue by duckyb** [photopea/photopea#5783]
It would be great if Photopea added the option to convert an image to a different color profile, as Photoshop does.

![image](https://github.com/photopea/photopea/assets/27895007/001e4531-1267-4d20-b6e5-383ca1de93f3)

This process actually changes the color values of the image and is needed for what I'm trying to do.

**Comment by photopea** [comment]
Great request! But I am afraid not that many users need it, as everyone is fine with working in sRGB.

BTW. do you plan to upload your own color profile (ICC file), or you want to use one of 3 - 5 popular color spaces, which we should have on our side?

**Comment by klaslod** [comment]
Nice but like when did i ask

**Comment by photopea** [comment]
I have implemented it. Four color profiles are available: sRGB, Adobe RGB, ProPhoto RGB and Display P3.

You can either Assign a profile (keeping color values the same, the look might change), or Convert to profile (converting color values to another space, keeping the look the same).

It is available under Edit - Assign Profile, or Edit - Convert to Profile.

**Comment by duckyb** [comment]
Amazing, thanks!
