### ISSUE TITLE
Work area is too wide (goes offscreen)

### ISSUE THREAD

**Issue by peterbonov** [photopea/photopea#5784]
The work area is wider than my screen, so tools on the right (e.g. the layers, history etc.) are inaccessible. Sometimes I manage to scroll right, but then the stuff on the left becomes inaccessible (tool palette, tool settings, etc.).

![image](https://github.com/photopea/photopea/assets/87188214/f1f8ad95-fac7-4bcb-bc69-0fcb18532e30)

**Comment by photopea** [comment]
I am 100% sure it is done by a browser extension, which you have installed, and you allowed it to modify Photopea.

Please, report only bugs, which you can reproduce with all browser extensions disabled.
