### ISSUE TITLE
Brush width

### ISSUE THREAD

**Issue by tcorm** [photopea/photopea#5785]
Previously the brush tool worked exactly as I wished, and when the brush width was shrunk to one pixel, it would only brush a singular pixel if applied. However, now the brush paints a single pixel plus the four adjacent pixels to the one you applied the brush tool, which is incredibly aggravating as it ruins a project I was working on. Is this a new photopea update? If not, is this happening to anyone else? Is there someway I can fix the brush tool? Thank you in advance.

**Comment by camoody1** [comment]
If you only want a single pixel colored with no adjacent mixing, use the Pencil Tool, not the Brush Tool.

Per Google Bard...
The Brush Tool and the Pencil Tool in Photopea are both used to paint on images, but they create different effects. The Brush Tool creates soft, gradual strokes, while the Pencil Tool creates sharp, hard-edged lines.

The Brush Tool uses a "brush track" to create its strokes. The brush track is a small, repeating pattern that is used to fill in the area you are painting. The size and shape of the brush track can be adjusted, which allows you to create a variety of different effects.

The Pencil Tool does not use a brush track. Instead, it creates strokes that are made up of individual pixels. This means that the Pencil Tool can create very sharp, precise lines.

Here is a table that summarizes the key differences between the Brush Tool and the Pencil Tool in Photopea:

| Feature | Brush Tool | Pencil Tool |
|--------------|-------------------|-------------------|
| Strokes             | Soft, gradual    | Sharp, hard-edged |
| Brush track      | Yes                    | No               |
| Pixel accuracy | Less accurate | More accurate |
| Best use cases | Painting soft gradients, blending colors, creating smooth textures | Drawing precise lines, creating vector graphics |

Ultimately, the best tool to use depends on the specific effect you are trying to achieve. If you need to create soft, gradual strokes, then the Brush Tool is a good choice. If you need to create sharp, hard-edged lines, then the Pencil Tool is a better option.

Here are some additional tips for using the Brush Tool and the Pencil Tool in Photopea:

* To adjust the size and shape of the brush track, use the "Size" and "Shape" sliders in the Brush Tool options bar.
* To create a smooth gradient, use the "Opacity" slider to fade out the brush strokes as you paint.
* To create a vector graphic, use the Pencil Tool in "Path" mode. This will create a path that you can edit and manipulate.

I hope this helps!

**Comment by photopea** [comment]
I am pretty sure our Brush tool has always worked like this. You probably used the Pencil tool.
