### ISSUE TITLE
Need position info (x and y axis) of selected element

### ISSUE THREAD

**Issue by numzie** [photopea/photopea#5786]
Very simple request:

When an element is selected, I need to be able see the position of the element on the X and Y axis (top left corner of element selected).

**Comment by bluep55** [comment]
Is this what you mean?
If you open the 'Properties' panel X and Y positions are shown there.

![X and Y](https://github.com/photopea/photopea/assets/118609932/aabac400-8502-4f50-8619-df5fb2a047bc)

**Comment by camoody1** [comment]
This information already exists in the Properties window. The X and Y coordinates coincide with the selected element's top left corner.

**Comment by numzie** [comment]
Sorry - I looked and looked and searched the FAQ - thanks guys!

**Comment by photopea** [comment]
Note, that if your element is e.g. a circle, you will not see the center of the circle, but the coordinate of a top left corner of a bounding box of that circle.
