### ISSUE TITLE
Deleting thousands of swatches

### ISSUE THREAD

**Issue by Bossiskeyboard** [photopea/photopea#5787]
It's annoying to delete all my thousands of swatches, I want to delete them all by one click with an option called (delete all swatches)

**Comment by photopea** [comment]
What swatches? where? What should I do to see the problem that you see?

**Comment by TheRadicalDreamer** [comment]
you can try on Edit > Local Storage and look for the .aco files.

There you can remove then completely.

**Comment by photopea** [comment]
Swatches should disappear after you close and re-open Photopea.com

If they stay, they are probably in your Local Storage, delete them from there (Edit - Local Storage, look for ACO files).
