### ISSUE TITLE
Empty SmartObject with displacement filter is not resized on image resize

### ISSUE THREAD

**Issue by lucadalli** [photopea/photopea#5789]
Reproduction steps:
1. Open www.photopea.com/#itVrVt37V.psd
2. Use "Image Size..." to resize main document to 1000x1000px
3. Open SmartObject "Empty" and fill it with a color (ALT+Backspace)
4. Save SmartObject and return to main document
5. Observe that SmartObject "Empty" is not resized and instead of being 1000x1000px large is still 500x500px

**Comment by photopea** [comment]
Sorry, but Photopea can not do transforming of empty smart objects (you can not resize it with free transform). Your smart object is 0x0 pixels, and if you make it 2x larger, it is still 0x0 pixels.

I recommend not using empty smart objects (with no visible pixels) at all.

**Comment by lucadalli** [comment]
This bug is not related to Free transform but to "Image > Image Size...".
Everything works properly **if the SmartObject does not have a displacement filter**.

Please try the reproduction steps with this PSD: www.photopea.com/#iPHQd5HSl.psd
and you'll see that the SmartObject grows with the main document even though the SmartObject is "empty".

**Comment by photopea** [comment]
okay, it should be fixed now.

**Comment by lucadalli** [comment]
Works, thanks a lot!
