### ISSUE TITLE
selection tool latency

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#579]
when I use basic selection tool, it is not instant
Selection area is always "catching up" with the mouse move.
The lag is small, but it is significant and it is in one of the basic / most used tool.

Is it because it is drawn on canvas and it cannot be faster?
Do others have this issue too?
I have good / fast PC, but I admit it is not gaming / designer one, it doesn't have dedicated video card. Am I a rare case? But I am sure your target users are developers and other non-designers too?

I imagine that coordinating non-canvas select tool (I use transparent div with dash-styled border in one app, it works perfectly w/o any lags), with the content - that will be on canvas, might be too much.

May be there're other possible solutions?

It's just that select tool is one of the most used tools of the graphic editor, it's in the core of so many usage scenarios, I though I'd point this out as potential problem at some point later.

**Comment by photopea** [comment]
Hi, what browser and OS do you use?

What if you drag a layer with a Move tool? Is the lag smaller than with Selection tools? What about drawing with a Brush?

Also, can you try to make a browser window smaller, or go fullscreen?

**Comment by ewnjtgouierg** [comment]
Hi!

>what browser and OS do you use?

Chrome on Ubuntu 16.04.3

>What if you drag a layer with a Move tool? Is the lag smaller than with Selection tools?

The lag is much greater, but - also b/c it is big - it is kind of obvious that it's probably unavoidable today? I mean, moving around vector graphics in browser.

With selection, the lag is very small, it looks somewhat like the "ease" transition effect. It's easiest to notice if I start selecting from top to bottom and then quickly move mouse back up to the selection upper edge (while keeping it same wide) - then the lower edge jumps after the mouse at the end.

>What about drawing with a Brush?

yes, there's a lag issue, I cannot quickly draw a curve - a quick stroke results in straight lines, as if frequency of getting event from mouse is not high enough

>Also, can you try to make a browser window smaller,

making window half its size significantly reduces the latency of selection tool
can't say that for sure about brush - it's still impossible to quickly draw curves

> or go fullscreen?

doesn't seem to noticeable affect the lag of selection tool

**Comment by photopea** [comment]
Is WebGL on while you use Photopea (see More - Use WebGL) ? What about dragging guides?  (https://www.photopea.com/learn/guides-grid-snapping) - is it any faster?

What about dragging a fish in this game? http://bigfish.ivank.net/  Is there the same lag between the cursor and the fish?

**Comment by ewnjtgouierg** [comment]
WebGL was ON, but turning it Off doesn't noticeably affect select tool responsiveness
Dragging guides has some small lag too - very small
Dragging fish in a game works fine - can't complain (:

once again: it's a very small lag, tool is perfectly usable as now (so it's absolute low priority in the short run), it's just that "the feel" is not a "hi-fi" so I thought I post about it b/c select tool is one that is used so much

I'll check it on Windows and in future possibly on computers with fast video cards etc and update if I have any new info

**Comment by photopea** [comment]
In my case, the lag when drawing a selection is the same as when dragging a Guide, which is the same as when dragging a fish. I think I can not improve it any further, you should probably report it as a bug to developers of your browser or OS.
