### ISSUE TITLE
Feature request: add image size parameters to `Document.saveToOE`

### ISSUE THREAD

**Issue by lucadalli** [photopea/photopea#5790]
Allow the image size to be defined when calling `Document.saveToOE`

Example:
`app.activeDocument.saveToOE("png", 500, 500)` to export active document as 500x500px PNG

**Comment by photopea** [comment]
You can call a script for resizing a document before saving. And then, call a script for doing a step back.

**Comment by photopea** [comment]
I will close it now, as it can be achieved in a different way.
