### ISSUE TITLE
Improving Swatches panel

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5791]
I have been working a lot with large project where i have a given pallet of colors. And the swatches panel on photopea are a little short for the task.

So here is a video on how versatile you can create, organize and use the swatches on Photoshop.

https://www.youtube.com/watch?v=XaHy5_D1Gb8

(also they are way bigger icons which is so much comfortable)

If you need me to list all the features, ask me and i'll do it

**Comment by TheRadicalDreamer** [comment]
Photoshop's Swatches panel:
![image](https://github.com/photopea/photopea/assets/11801254/1f45f2cb-47f4-43aa-84fc-da68facb2f4b)

Photopea's Swatches panel:
![image](https://github.com/photopea/photopea/assets/11801254/da1c8581-f404-482d-9b37-0a40d2c89d3f)

**Comment by photopea** [comment]
I have improved it!
- thumbnails are bigger now
- colors are in folders (according to the ACO file which you loaded)

You can click a tiny triangle to switch to a list view (works for all resources: brushes, gradients, patterns ...)
You can right-click the item to rename it (works for all resources: brushes, gradients, patterns ...)

**Comment by TheRadicalDreamer** [comment]
Good!!

Now i have an issue.

Where are the new colors defined??

Can we have those 3 buttons?
![image](https://github.com/photopea/photopea/assets/11801254/acbca250-0407-456a-ad60-3f7e9d4b887c)

Create a folder, create a new swatch, delete a swatch or folder

**Comment by TheRadicalDreamer** [comment]
Also, i found some bugs in the new swatch panel.

You can see them in #5982
