### ISSUE TITLE
GUI Becoming horizontal?

### ISSUE THREAD

**Issue by funtime-foxy1** [photopea/photopea#5792]
So I'm trying to make an icon in photopea and...
![image](https://github.com/photopea/photopea/assets/70809736/678fc9f5-1664-41b0-be73-35f02b4f3fd0)

I dont know how this happened, I refreshed twice.

**Comment by camoody1** [comment]
Try these steps and report back, please. 🙂

https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by funtime-foxy1** [comment]
Thanks! It was my extension: "Blackbox Code Chat Autocomplete Extraction"

**Comment by camoody1** [comment]
> Thanks! It was my extension: "Blackbox Code Chat Autocomplete Extraction"

Good to know! Thank you for working through the issue. Have a great rest of your week!
