### ISSUE TITLE
Adding Raster Mask + Paint ERROR

### ISSUE THREAD

**Issue by MrHotSauceGD** [photopea/photopea#5793]
So I was using the Raster Mask to add for JPG Image and that raster mask makes the painting to work of clearing something that is unnecessary to combine with other images. Since there is a problem I found today, it did not clear and fade away the image, no matter how many times I've tried it, it just would not work. It is part of the process of where I would make my YouTube thumbnails and stuff, but is this a bug, error, etc. or something that you guys had removed? (Please do not close this)
![Screenshot 2023-06-27 210937](https://github.com/photopea/photopea/assets/137966381/78af0b4d-ccbc-4c3b-8589-287b8d612310)

**Comment by camoody1** [comment]
From what I see in the image you shared, your mask is entirely white. White shows everything and black hides it. You need to paint on the mask in black to hide what you don't want.

**Comment by MrHotSauceGD** [comment]
No, like this. Like I can not even do that. The circle discord profile picture thing with fades on it, that was the question that I want to know why I can not do that.
![BackStream vs Rat UP](https://github.com/photopea/photopea/assets/137966381/acb2bfb8-281d-4333-96d6-b26d4b2bf6d1)

**Comment by camoody1** [comment]
Make sure that you're using pure white and pure black for coloring the mask. If it's not pure, the mask won't work correctly.

**Comment by camoody1** [comment]
I mean, re-read what you wrote in your first post. It really just makes no sense. 🤷🏼‍♂️

> So I was using the Raster Mask to add for JPG Image and that raster mask makes the painting to work of clearing something that is unnecessary to combine with other images. Since there is a problem I found today, it did not clear and fade away the image, no matter how many times I've tried it, it just would not work.

**Comment by MrHotSauceGD** [comment]
Oh wait never mind, I had to change the front to black and the back to white. That is all I have to do, yikes.
![Screenshot 2023-06-28 112802](https://github.com/photopea/photopea/assets/137966381/cb2705ae-ce83-4350-9d5c-fa06e5c26200)

**Comment by photopea** [comment]
ok, I will close it.

**Comment by camoody1** [comment]
Glad you got it figured out.🙂
