### ISSUE TITLE
Variables bug with data sets

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5794]
After i imported a data set and export it correctly and saved the PSD. I opened the PSD and the data set was gone and instead i found these
![image](https://github.com/photopea/photopea/assets/11801254/cceabdd0-82fa-4a2f-a2b7-d2649854bce9)
![image](https://github.com/photopea/photopea/assets/11801254/48ae92d6-4b5e-4ebc-9eac-22e2e976ae14)

Also, when i have a project with 2 artboards and variables on both artboards at the end of the export i get the other artboard removed!! :O

**Comment by TheRadicalDreamer** [comment]
Everytime i open a PSD with variables i get this error on the data sets

**Comment by camoody1** [comment]
Well, stop opening a PSD with variables. Solved.

**Comment by photopea** [comment]
Could you provide steps how can I reproduce it? E.g. your PSD without variables and your data set, so that I can see it happening myself?

**Comment by TheRadicalDreamer** [comment]
PSD: www.photopea.com/#i8xAjAkPx.psd
CSV: [GL - Frases - Mes (2).csv](https://github.com/photopea/photopea/files/11918536/GL.-.Frases.-.Mes.2.csv)

Here they are

**Comment by photopea** [comment]
I tried to open your PSD in Adobe Photoshop and loaded your CSV, but it does not work either. It says that the CSV has too many variables. Could you use the CSV which has no extra columns?

**Comment by TheRadicalDreamer** [comment]
What do you mean with no extra columns? Fewer columns?

Or only columns that are used?

**Comment by photopea** [comment]
This is what Photoshop says

![image (3)](https://github.com/photopea/photopea/assets/15955558/ee56343e-64c0-4ace-9aaa-84db5d6615f3)

**Comment by TheRadicalDreamer** [comment]
[GL - Frases (1).xlsx](https://github.com/photopea/photopea/files/11932706/GL.-.Frases.1.xlsx)

This is the excel: on bare minimum.

And the PSD on bare minimum
[bare minimin artboards.zip](https://github.com/photopea/photopea/files/11932758/bare.minimin.artboards.zip)


Can you open it and make it worK?

**Comment by TheRadicalDreamer** [comment]
On a side note, i can open it, export it and all. It presents this problem that the data set disappears, but aside from that all seems fine.

Even though, my client cannot open the exported PDF on AI nor Photoshop.

Can you check this out?

**Comment by TheRadicalDreamer** [comment]
This is the file (from the same project) that she cannot open:
[GL - Phases.pdf](https://github.com/photopea/photopea/files/11932783/GL.-.Phases.pdf)

This is the error she gets:
![mmexport1688356953796](https://github.com/photopea/photopea/assets/11801254/05ec2fe3-8303-41b1-abd1-b092a0f93ece)

**Comment by TheRadicalDreamer** [comment]
Sorry to add up other issues related to the same project :|

**Comment by camoody1** [comment]
> This is the file (from the same project) that she cannot open: [GL - Phases.pdf](https://github.com/photopea/photopea/files/11932783/GL.-.Phases.pdf)
> 
> This is the error she gets: ![mmexport1688356953796](https://user-images.githubusercontent.com/11801254/250444026-05ec2fe3-8303-41b1-abd1-b092a0f93ece.jpg)

I was able to open this file with no error. 🤷🏼‍♂️

**Comment by TheRadicalDreamer** [comment]
Can you please try AI? 

That's the program my client uses. I don't have so I cannot try.

**Comment by camoody1** [comment]
> Can you please try AI?
> 
> That's the program my client uses. I don't have so I cannot try.

I don't have Illustrator, either. Sorry.

**Comment by camoody1** [comment]
I was able to open it in Inkscape, which is a free version of Illustrator, similar to how Photopea is a free version of Photoshop. But that's the best that I can do.

**Comment by MichalSZZ** [comment]
> Can you please try AI?
> 
> That's the program my client uses. I don't have so I cannot try.

I just opened it in Illustrator 2023 without any errors. But you posted screens from Adobe Acrobat...
And there were some problems (in Acrobat) after opening in "PDF edit" mode, but after all - Acrobat opened it normally.

**Comment by photopea** [comment]
Variable names can not contain spaces. I fixed it - Photopea will tell you when you enter a variable name with spaces.

Please, modify your PSD and CSV, so that variable names dont have spaces. If there still is a problem, please, report it in a new issue.
