### ISSUE TITLE
Variables - Export PDF: Reverse pages

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5795]
Can we have the same option to reverse pages, that we have when exporting a simple PDF but in variables?

Please... :)

![image](https://github.com/photopea/photopea/assets/11801254/0c6c27cb-6c20-41c2-b393-6da0c100a4a6)

![image](https://github.com/photopea/photopea/assets/11801254/b4e0b3b4-08fd-40bd-8816-2865e2d9e64e)

**Comment by camoody1** [comment]
Well...
![bitmoji](https://sdk.bitmoji.com/render/panel/7c560e91-d819-491c-9658-378012eb1aea-33290fb4-ad75-46e6-8062-305f1f5378d9-v1.png?transparent=1&palette=1&width=246)

**Comment by TheRadicalDreamer** [comment]
T.T

**Comment by photopea** [comment]
This option is enabled Always during the PDF export, if your document has more than one page (more than one artboard).

**Comment by photopea** [comment]
So, your document has one artboard, and you have X lines in a table, and you will get X PDF files. What do you mean by "reverse pages"?

**Comment by TheRadicalDreamer** [comment]
Reverse pages is the option that you have when your project has more than one artboard. That's fine.

But i would like to have that same option when i export to PDF though Variables.

![image](https://github.com/photopea/photopea/assets/11801254/3495d5fe-2ce5-440d-b67f-2198d907fbe0)

**Comment by photopea** [comment]
It should be there, if your project has more than one artboard. Isnt it? Could you send me a PSD so that I can see?

**Comment by TheRadicalDreamer** [comment]
Uploading Screen recording 2023-06-30 12.13.52.mp4…

**Comment by TheRadicalDreamer** [comment]
PSD: [www.photopea.com/#i8xAjAkPx.psd](http://www.photopea.com/#i8xAjAkPx.psd)
CSV: [GL - Frases - Mes (2).csv](https://github.com/photopea/photopea/files/11918536/GL.-.Frases.-.Mes.2.csv)

**Comment by photopea** [comment]
got it, it should be fixed now.

**Comment by TheRadicalDreamer** [comment]
![giphy](https://github.com/photopea/photopea/assets/11801254/f3c36eb8-13d4-4e24-9881-7f2d8f40a1e0)
