### ISSUE TITLE
Photopea workspace exceeding visible browser window

### ISSUE THREAD

**Issue by bethanyactually** [photopea/photopea#5796]
Every time I open Photopea, I have to zoom out in my browser window more and more to be able to see the layer windows, etc., on the right side of the page. Closing and opening Photopea does not help. Logging out and back in does not help. Restarting laptop does not help. Switching browsers does not help. (I tried both Firefox and Safari, and the problem occurred in both browsers, both of which were up to date with current software.)

Also, after editing for a few minutes, the Image options stopped working--Levels, Curves, etc.

**Comment by camoody1** [comment]
Sounds frustrating. Try these steps and report back the results.
https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
You installed a browser extension and you allowed it to modify Photopea for you. Please, do not allow your extensions modfy Photopea.
