### ISSUE TITLE
Variables - Exporting with hidden artboards

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5797]
When i am exporting with variables and i hide an artboard in particular (or even delete it), the process unhide it and export it with the others.

Probably this has to do with the fact that the artboard that is reappearing has layers which are affected by variables.

But it makes no sense that it also restores a deleted artboard!

**Comment by photopea** [comment]
It would be great if you shared a PSD file for testing (as simple as possible).

**Comment by TheRadicalDreamer** [comment]
[When i hide it.mp4](https://github.com/photopea/photopea/assets/11801254/6f98991b-8d64-4428-ae24-acbe06ef567c)


[When deleting it.webm](https://github.com/photopea/photopea/assets/11801254/7cec7abe-5447-4f3e-b244-c13197e62de0)

**Comment by TheRadicalDreamer** [comment]
Man, this is too weird.

I deleted all the layers that are not affected by variables on the data set (i was working for the other issue (#5794)) and when i set export PDF, all the layers got back!

Check this out:
[Screen recording 2023-07-03 00.09.22.webm](https://github.com/photopea/photopea/assets/11801254/0f9128ef-53d7-4835-b718-a10899c341f9)

**Comment by photopea** [comment]
Please, dont send any videos anymore! I need to reproduce it on my computer :) Could you send me a simpler example, with less variables? Because your current PSD and CSV dont work in Photoshop.

**Comment by photopea** [comment]
Variable names can not contain spaces. I fixed it - Photopea will tell you when you enter a variable name with spaces.

Please, modify your PSD and CSV, so that variable names dont have spaces. If there still is a problem, please, report it in a new issue.
