### ISSUE TITLE
Ai Replace tool is not working,again(

### ISSUE THREAD

**Issue by xyzzart** [photopea/photopea#5799]

**Comment by camoody1** [comment]
Our AI Image provider is experiencing an outage, currently. We'll have to wait until they come back online.

**Comment by camoody1** [comment]
Seems to be back up, at least for the time being. Both of Dezgo's GPU clusters were down.

**Comment by photopea** [comment]
it works for me now :)

**Comment by camoody1** [comment]
@photopea Yeah, Clem said the traffic was very high and they were continuing to monitor it.
