### ISSUE TITLE
transparent shape (fill type "None") doesn't work now? (filled with black instead)

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#580]
in new project trying to draw transparent rectangle
it is filled with black
trying to change it into transparent afterwards doesn't work either

+"Merge layers" and "Crop" tools make all existing transparent shapes (in PSD that was created elsewhere) filled with black - I guess it's that same issue

**Comment by photopea** [comment]
Sorry for that, I just fixed it.
