### ISSUE TITLE
Missing Stroke on Inner Path For SVG Open/Import With No Fill

### ISSUE THREAD

**Issue by redaxle** [photopea/photopea#5800]
When a shape with no fill and only a stroke has an inner, enclosed path is exported as SVG then re-opened, the stroke on the inner path is missing. The generated SVG appears to be correct.

#### Steps to reproduce:
 - Create a shape with an inside path, e.g. convert the letter "D" to a shape
 - Remove the fill and add a stroke
 - Export as SVG
 - Re-open the SVG. The path will be present but without a stroke. The stroke will only be on the outer path.

#### Additional notes:
 - The strokes on both paths are present if there is a fill on the shape.
 - This works as expected if the PDF format is used for the export/open

#### Before exporting to SVG
![photopea-shape-before](https://github.com/photopea/photopea/assets/6753947/652fc32c-8f67-4d0c-bb92-f0740855f788)

#### Sample svg file that's exported (seems fine)
![sample-file-with-problem](https://github.com/photopea/photopea/assets/6753947/0d5444fb-ea8f-4155-b6b5-851c825490f6)

#### After opening the SVG that's exported above
![photopea-shape-after](https://github.com/photopea/photopea/assets/6753947/95447fa7-175c-4db5-a9f1-702eec4d3e8a)

**Comment by photopea** [comment]
fixed :)
