### ISSUE TITLE
window clips to left, leaving controls inaccesable 

### ISSUE THREAD

**Issue by ashenprincx** [photopea/photopea#5801]
![image](https://github.com/photopea/photopea/assets/138213360/21de6e6e-fcaa-40d7-85fa-7c485fbd6b3f)
Happens randomly while working. sometimes corrects itself, but typically have to completely close window and reopen ti fix.

**Comment by camoody1** [comment]
Highly likely a browser extension issue. Try these steps and report back, please.
https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by ashenprincx** [comment]
thank you for your response, I will check this out.
I figured out that it was happening whenever I typed in a text box, and was
causing the window to slide to keep the text centered. clicking out of the
window and pressing backspace seemed to work though, for some reason.

**Comment by photopea** [comment]
We are ready to help you once you confirm it is not caused by your extensions, but it probably is.

**Comment by photopea** [comment]
I have to close it as the person did not respond.
