### ISSUE TITLE
Create coloring book

### ISSUE THREAD

**Issue by Anubias25** [photopea/photopea#5802]
That does: June 24, 2023 transform every photo into a coloring book
A photo in a coloring book / a painting page, a so -called "painting by numbers", does not work. The numbers disappear after OK. Plus two pictures.
Please clarify.
![a (2)](https://github.com/photopea/photopea/assets/114422147/18d847dc-3d5d-4c5a-aa95-402a603cf2b2)
![a](https://github.com/photopea/photopea/assets/114422147/ea59035b-c9d2-4a70-ad82-c5787e534fa2)

**Comment by photopea** [comment]
It should be fixed now :) try to vectorize it again!
