### ISSUE TITLE
Unable to Deselect Image

### ISSUE THREAD

**Issue by cricketcoded** [photopea/photopea#5803]
As of a day or so ago (June 28 ish) I am unable to deselect an image, even by using ctrl+D, which previously worked. If I am on a layer, the image is automatically selected with no way to deselect it - the pervasive blue box around it is very difficult to work with, as I can't see the appearance of what I'm editing. However, even when it's selected I still can't transform it without using ctrl+shift+T as usual, which means it's not even functional, just detrimental. The only way to get rid of the box around the image is to click off of the layer, but then I can't edit it. Previously, even if I had a layer selected, the image itself was not selected and highlighted unless I was using the transform command and I could easily get rid of the blue box through the use of ctrl+D. 
![3](https://github.com/photopea/photopea/assets/117485066/763bc67b-933e-436a-811b-77059ed82388)

**Comment by photopea** [comment]
I do not see any selection in your image.

Why dont you share a whole screenshot? What is the purpose of hiding the tool that you are using? The crop tool looks like this.

**Comment by photopea** [comment]
I have to close it as the person did not respond.
