### ISSUE TITLE
When trying to open a file it doesn't open,.

### ISSUE THREAD

**Issue by W1llam** [photopea/photopea#5804]

**Comment by camoody1** [comment]
Thank you for such a descriptive ticket. With this much information, surely the developers will easily be able to find a solution.👍🏽

**Comment by photopea** [comment]
Hi, what should I do to see such a problem myself? I tried to open several files, but they open fine, so you could be lying to us. Do you have any proof?

**Comment by photopea** [comment]
I have to close it as the person did not respond.
