### ISSUE TITLE
Short question

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5806]
Hello!
Ivan, can you find out, if it's not a secret :) - why didn't you start implementing Smart Blur and HDR Toning in Photopea? Between these two tools there is one common mathematical feature in the implementation of the algorithm, which is extremely interesting to me. And your answer might help me figure it out. Thank you

**Comment by photopea** [comment]
Hi, I have never heard of these features, I dont know what they do and what algorithm could they use. I dont think anybody ever asked for them. Are they features from Adobe Photoshop?

**Comment by Pt-home** [comment]
Your answer - surprise for me:)  

Yes, of course, they are in Photoshop
Filter-Blur-Smart Blur...
Image-Adjustment-HDR Toning...

For example - many user actions from "Photopea plugin" not working correctly, because its PS-actions clone and needing Smart Blur...

**Comment by Pt-home** [comment]
I'm really shocked))
People uploaded actions to the Photopea-Plugins section, they were buggy on the Smart Blur application and no one just asked - why not? :) The world will never cease to amaze...

**Comment by photopea** [comment]
The Smart Blur seems to be similar to the Surface Blur, it has the same parameters.

Do you know the algorithm behind the Smart Blur? If yes, I can implement it right away :)

**Comment by Pt-home** [comment]
In fact of the matter:)
The algorithm does not look complicated. I even implemented their analogue in the form of a private plug-in with my crooked amateur hands, even in several ways - both with walkers and through BACM. But there are two snags.
1. The specific weight function is unknown, the distribution by which the decision is made to blur the pixel or not, which Photoshop uses.
2. The speed does not suit me, because for each pixel you need to calculate this weight for the neighborhood of the radius - and this makes the process long on large photos. And I can’t figure out how to come up with this to implement by matrix multiplication.
If you want, I can email you (I really don't know) all the details and files. For me, this is a hobby for self-development, anyway. If there will be a useful addition for Photoshop from this, all the more so - an analogue of the Photoshop function, this is only a plus

**Comment by photopea** [comment]
Please, dont send me any files, I never look at other peopels code :D

Could you at least tell me with words what should be done to the photo? Even if your algorithm is bad and slow, does it give the correct result (same as Photoshop)? Could you find the description of this problem anywhere on the internet?

**Comment by Pt-home** [comment]
Okay, I can, but tomorrow. And short question - now in Photopea Surface Blur realized as image buffer matrix transform or no?

**Comment by photopea** [comment]
I dont know what is "image buffer matrix transform", do you mean a convolution? Or transforming each RGB color by a 3x3 matrix?

The Surface Blur is a Bilateral filter: https://en.wikipedia.org/wiki/Bilateral_filter

**Comment by Pt-home** [comment]
A convolution,  yes

**Comment by photopea** [comment]
The Bilateral filter, or a Median filter,  can not be done as a simple convolution.

**Comment by Pt-home** [comment]
Ok...
Let's define concepts - there is a specific Smart Blur of Photoshop and there is Smart Blur as a general principle of the method.
There is practically no specific information on the Internet, there are only general phrases ... The best I can offer to start is at this link [https://asserttrue.blogspot.com/2010/08/implementing-smart-blur-in-java.html](url)

1. March through the image pixel by pixel.
2. For each pixel, analyze an adjacent region (as variant, the adjoining 5 pixel by 5 pixel square, but in PS-filter radius is float!).
3. Calculate some metric of pixel variance for that region (main riddle - what kind of metric does the PS take)
4. Compare the variance to some predetermined threshold value.
5. If the variance exceeds the threshold, do nothing.
6. If the variance is less than the threshold, apply blurring to the source pixel. But vary the amount of blurring according to the variance: low variance, more blurring (high variance, less blurring).

In finish, author write:
"Ideas for further development:
Substitute a directional blur for the non-directional blur.
Substitute a Sobel kernel for the blur kernel.
Try other sorts of kernels as well."

Note. PS-filter has two additional modes which they call "technical" - "Edge Only" and "Edge Overlay".  May be, in first - PS selected edge regions and freezes them on blur
Note. On my opinion, there is a close analogy between Smart Blur (at small radiuses) and your Reduce Colors...

**Comment by Pt-home** [comment]
At the same time, there is no certainty to what exactly the weight function is applied - to the values of color channels, brightness, contrast, saturation ... In general, my modest knowledge is not enough. I tried to calculate for each pixel in a double cycle different distribution options (I tried 10 pieces) to the parameters of the color channels - sometimes something remotely resembles, but I can’t use large radii to check - the calculation time becomes prohibitive. And how (and is it possible in principle) to apply matrix transformations, convolutions (and most importantly - which ones) for this - here my modest knowledge is not enough

**Comment by Pt-home** [comment]
Unexpectedly, but it seems to me that I'm somewhere close :), but I'm not sure what exactly is near the PS-original;)
1) I blur the original (I want to try in the end on different types of blur, the parameter is radius)
2) I select the edges (parameter - threshold)
3) Those areas that I consider the edge - I leave untouched
There are no runtime problems with WASM at all
Now, I want to try to do another blur interpolation for pixels near the edges (I think that this was the setting of the PS filter "Quality"
![image](https://github.com/photopea/photopea/assets/29394245/ec916593-a27f-4a76-a089-9e13dda36e84)
![image](https://github.com/photopea/photopea/assets/29394245/39631379-efbb-4653-aaa0-a89f6c426775)

**Comment by photopea** [comment]
wow, that looks nice! Is it close to Photoshop results?

**Comment by Pt-home** [comment]
Thank you for evaluating the result) Of course, I like this option more, but this is not a PS analogue. At a minimum, their blur is similar to posterization, it is "flat" and here the result is "soft"... I will experiment further

**Comment by photopea** [comment]
I will close it, as not many users asked for this feature, and I have no idea how to make it.

**Comment by Pt-home** [comment]
I put my plugin in the public domain, so that those who need it can use
