### ISSUE TITLE
Feature Request: Texture, Clarity, Dehaze for Camera Raw?

### ISSUE THREAD

**Issue by CxryzNFTs** [photopea/photopea#5808]
Hello!

I was wondering if you guys are going to implement Texture, Clarity, and Dehaze sliders for the camera raw filter?

I think it'd be cool if it was added.

Thanks.

**Comment by CxryzNFTs** [comment]
@photopea Please add this!!

**Comment by photopea** [comment]
I dont know how.

**Comment by CxryzNFTs** [comment]
Polarr Camera Raw has this feature, I think Photopea should integrate that into their camera raw filter.
https://photoeditor.polarr.co/
![image](https://github.com/photopea/photopea/assets/71056820/444ef3dd-3d3a-43da-8873-71c6657dd0b0)

**Comment by photopea** [comment]
@CxryzNFTs Are you talking about Dehaze? Polarr Camera Raw dows not have Texture or Clarity feature. And their Dehaze works differently than the one in Adobe Camera Raw.

**Comment by photopea** [comment]
I have added more options to the Camera Raw filter.
