### ISSUE TITLE
Some problems with Magic replace

### ISSUE THREAD

**Issue by player868** [photopea/photopea#5809]
When using Magic replace to expand the cropping area of an image, if you don't fill in the descriptor, it will generate scenes with people from time to time, and it is really annoying to generate scenes with people, and then when expanding the cropping area of an image, there is a great possibility that if you don't fill in the descriptor, another separate image will be generated instead of a coherent image after expansion.

**Comment by player868** [comment]
![IMG_20230702_130224](https://github.com/photopea/photopea/assets/129951996/043ad285-2f27-4b98-9171-bcb4452781fd)This is an example with the problem that expanding the image of the cropped region without filling in the descriptors may instead favor random generation of separate images rather than incorporating the generated image into the original image, expanding the original image.

**Comment by camoody1** [comment]
The current Magic Replace Tool in Photopea is not intended to be used as an Outpainting Tool. It is meant to fill-in small parts of an overall image - Inpainting. Some users have had luck using the tool for other means by utilizing highly descriptive prompts and through the use of the Advanced Options. Base Stable Diffusion Inpainting - which is what this tool is based on - is not the same as the Generative Fill you see utilized in PhotoShop. There are additional tools that may be added to Photopea in the future, but this is what we have for the time being.

**Comment by photopea** [comment]
Are you saying, that you tried to outpaint the left part of the image, and Photopea created the right part of the image? Or did you plan to attach two images (before and after).

I need some proof of what you are saying. Or maybe I dont understand what you mean.

**Comment by player868** [comment]
> Are you saying, that you tried to outpaint the left part of the image, and Photopea created the right part of the image? Or did you plan to attach two images (before and after).
> 
> I need some proof of what you are saying. Or maybe I dont understand what you mean.

In short, it is to extend a narrow image into a wide image with magic replace, but the AI extended image does not match, not what I want.

**Comment by player868** [comment]
> 你是说，你试图绘制图像的左侧部分，而Photopea创建了图像的右侧部分？或者您是否打算附加两个图像（之前和之后）。
> 
> 我需要一些证据来证明你在说什么。或者也许我不明白你的意思。

In short, it is to extend a narrow image into a wide image with magic replace, but the AI extended image does not match, not what I want.

**Comment by photopea** [comment]
I tried to outpaint in Photopea and it worked well: https://twitter.com/photopeacom/status/1664363953290461184

I have no idea what do you mean by "does not match", as you did not share any proofs :(

**Comment by player868** [comment]
> 我试图在 Photopea 中画出来，效果很好：https://twitter.com/photopeacom/status/1664363953290461184
> 
> 我不知道你说的“不匹配”是什么意思，因为你没有分享任何证据:(

You may have difficulty understanding my explanation. Take the image I sent above in the comment section as an example, the large image in the image is the original image I want to process, and the small image is the result of using AI's magic replacement to process it, but I originally wanted to make this image I want to process expand the image in the outside direction using AI to make it a larger image. But there is a clear line of demarcation between the large and small images, and the AI expansion does not blend with the original image, which is the problem. Furthermore, in the image content above the comment, the small image is not uploaded by me, but is the result of AI processing.

**Comment by player868** [comment]
> 我试图在 Photopea 中画出来，效果很好：https://twitter.com/photopeacom/status/1664363953290461184
> 
> 我不知道你说的“不匹配”是什么意思，因为你没有分享任何证据:(

It may be difficult to explain to you clearly with only one picture, but I have done my best to explain to you clearly enough

**Comment by photopea** [comment]
I need to see it myself. Could you send me your image and tell me what should I do with it?

I can not use a photo from your camera which you gave us.

**Comment by photopea** [comment]
I have to close it as the person did not respond.
