### ISSUE TITLE
change cursor to "default" when changing "current" foreground/background colors ?

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#581]
if you select a color picker tool, cursor is changed to default.
But if you click on the boxes with current fg/bg colors, it is not.
So, for example, if you were using Hand tool, and then clicked on the fg color box to change it, the color picker interface appears and you can pick a color, but the cursor is still a hand cursor

Just for any case: I would not want the tool to be automatically switched to the eyedropper for good - only for it to have the appropriate cursor in the short time while this interface is active.

This is b/c it's just a very convenient way to pick colors:

1) click fg / bg box;
2) click the area with the color of interest
3) copy color code
4) hit ESC

so that current color is not changed, and, probably most important, the tool is not changed - I can continue to navigate canvas with the Hand tool, for example, and I don't need to switch tool and then switch it back

**Comment by photopea** [comment]
I would like to wait, until browsers implement custom PNG cursors for hi-DPI displays (cursors in Firefox are comletely messed up). Then, we can use a custom cursor for an Eyedropper and for a Color Picker.
