### ISSUE TITLE
Is there a problem with the "Halftone Pattern" filter?

### ISSUE THREAD

**Issue by carfk** [photopea/photopea#5810]
No matter what color I fill in after creating a new layer, when I use the "Halftone Pattern" filter in the "Filter Gallery", it always turns into a black background no matter how I adjust it.

**Comment by photopea** [comment]
This filter uses the foreground and the background color (bottom left part of the screen). Maybe you set them both to black.

**Comment by carfk** [comment]
ok, thanks <3
