### ISSUE TITLE
Request the official launch of the AI magic outside painting function

### ISSUE THREAD

**Issue by player868** [photopea/photopea#5811]
Dear Photopea team, hello. I am your loyal user and I often use Photopea's AI Magic Replace feature, which can replace a part of the image with AI. However, I found that this feature has a limitation, that is, it can replace existing areas, but it is not very good at adding new areas. If you do so, it may cause some parts of the image to become more blurry, distorted, or distorted, or to appear undesirable scenes when expanding to new areas. So I would like to make an official suggestion to Photopea. I hope there is a feature that can expand the image outward, the kind that turns a narrow image into a wide one. This way I can add more content to the image without worrying about various problems with the image. Do you have any plans to develop such a feature? If so, when will it be available? Thank you very much for your reply.

**Comment by photopea** [comment]
Hi Player, I think the Magic Replace can be easily used to out-paint images.

What problems exactly do you have? You say "not very good", but what does it mean? It looked well when I used it.

**Comment by player868** [comment]
> 嗨，玩家，我认为魔术替换可以很容易地用于绘制图像。
> 
> 你到底有什么问题？你说“不太好”，但这是什么意思？当我使用它时，它看起来很好。

If AI magic replacement is applied to expand the image area, the problem is that when I need to expand the original image that contains depth of field, distant focus, micro lens, shift photography and these blurring methods for the image edge, but these edges contain the above blurring methods, but I happen to need to use AI magic replacement to expand the image area starting with this image edge, then the AI may not recognize the content of the image properly. Another problem is that if I upload an image that may not be visible, this may also allow the AI to generate a messy image to expand the image area. Another point is that when I use AI magic replacement to expand the image, there is a chance that some images with all watermarks will be generated to expand the image. That's why I said in my last comment that AI magic replacement is probably not applicable to image area expansion.

**Comment by photopea** [comment]
Could you show us, what result Photopea gives you, and what you want to get instead?

**Comment by player868** [comment]
> 你能告诉我们，Photopea给你什么结果，你想得到什么吗？

It is enough to solve the above problems.

**Comment by photopea** [comment]
I have to close it as the person did not respond.
