### ISSUE TITLE
Does anyone know if there is a way to change the pixel colours

### ISSUE THREAD

**Issue by theoldweirdcheese495** [photopea/photopea#5812]

**Comment by camoody1** [comment]
I don't believe there is any way to change colors in Photopea. It strictly uses black and white... just like Photoshop.

Of course, I'm color-blind, soooo....

**Comment by photopea** [comment]
You can use the Brush tool to paint over pixels and change their color. Or you can use Image - Adjustments, which also change the color of pixels.

**Comment by photopea** [comment]
I have to close it as the person did not respond.
