### ISSUE TITLE
Feature Request: New Gradient Tool to Match PS

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5813]
Photoshop released an upgraded version of their Gradient Tool that makes it much more flexible and easier to properly place. I think it would be a worthy upgrade to add to Photopea when/if possible.

Here is a video showing its use. The Gradient discussion starts at 2:00...
https://youtu.be/TtgjhWqe3HE

**Comment by MichalSZZ** [comment]
> Actually, I wanted to implement exactly this into Photopea four years ago, but then, I got a bit lazy :)

5 years ago there was a request for that https://github.com/photopea/photopea/issues/610 
I think we discussed that in other issues and the main problem was compatibility with PSD format.

This isn't just in beta PS only (that I am testing now). It is a feature in a normal PS version. It works with masks, gradient layers and so. And it is very helpful for me.

**Comment by photopea** [comment]
@MichalSZZ I thought it is only for gradient fill layers (e.g. vector shapes with a gradient fill). Are you sure they have this interface for regular pixel layers, too?

**Comment by camoody1** [comment]
@photopea At about 3 minutes into this video, the editor uses the new gradient tool on an inverted mask on an adjustment layer.
https://youtu.be/lgO27OWWi0E

**Comment by MichalSZZ** [comment]
@photopea You know what? there is something strange in it. I tried it now for the raster mask (regular pixel layer?) and YES. I can change the gradient properties after making a gradient on the layers mask. But that works only for a while (maybe for the time that I don't create a new layer or something like that). Then in the properties panel, the "gradient adjustment" icon disappears.
![obraz](https://github.com/photopea/photopea/assets/38118273/b2714c15-a664-46d7-ab22-380a3c328845)

For the new gradient layer made with the gradient tool in "gradient" mode (I can't change to the "classic gradient" in the top menu like when I am using a gradient on the layers mask) - the new layer is created as a "gradient fill layer" with GUI on the canvas.

**Comment by camoody1** [comment]
> @photopea You know what? there is something strange in it. I tried it now for the raster mask (regular pixel layer?) and YES. I can change the gradient properties after making a gradient on the layers mask. But that works only for a while (maybe for the time that I don't create a new layer or something like that). Then in the properties panel, the "gradient adjustment" icon disappears.

Checkout the video I listed above. Look around the 5:30 minute mark. The Gradient adjustment bar comes back if you click on the mask. Is this what you're talking about?

**Comment by MichalSZZ** [comment]
Here are explained the new "gradient properties panel" and the layer mask gradient https://youtu.be/XOdVzEk6l1Q?t=634

**Comment by camoody1** [comment]
> Here are explained the new "gradient properties panel" and the layer mask gradient https://youtu.be/XOdVzEk6l1Q?t=634

The video I listed in my first post covers it more in-depth.

**Comment by photopea** [comment]
As you know, raster masks consist of grayscale pixels (between black and white).

In the latest Photoshop, any raster mask can have a gradient attached to it. This gradient is rendered on top of regular pixels. If you modify the mask (e.g. paint into it), the gradient is lost (it is "rasterized" into regular pixels, just like rasterizing a smart object to paint into it).

Similarly, if you save it as a PSD and reopen it, this mask gradient is also lost (rasterized into regular pixels).

Otherwise, the new Gradient tool works only with Gradient Fill layers. It can not paint gradients into a regular layer (e.g. paint five gradients on top of each other, with the opacity of 20%, into one layer).

**Comment by photopea** [comment]
I have implemented it.

The Gradient Tool can edit the Gradient Fill layers now, too! Also, it can edit vector shapes with gradients. It has the usual "gradient UI", where you manually drag two or more points to set the parameters of a gradient.

**Comment by photopea** [comment]
I have implemented it.

The Gradient Tool can edit the Gradient Fill layers now, too! Also, it can edit vector shapes with gradients. It has the usual "gradient UI", where you manually drag two or more points to set the parameters of a gradient.

https://twitter.com/photopeacom/status/1697976257873338373

The only difference from Photoshop is, that it can not create new Gradient Fill layers (you have to use Layer - New Fill Layer - Gradient Fill). So, on regular pixel layers, it still works as the old gradient.

**Comment by photopea** [comment]
I will close it, as it is implemented now.
