### ISSUE TITLE
Variables - Deleted layers reappear when exporting

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5815]
I  have a project with variables.

I delete any layer (related to a variable or not) and when i export to PDF with variables, the layers return to the project.

This also happens with the position and/or order of the layers.

To repro:
Open this PSD
[GL - Months A.zip](https://github.com/photopea/photopea/files/11938586/GL.-.Months.A.zip)

Delete an artboard, a layer, or move a layer.

Open Image > Variables and export to PDF.

You'll see that the moved/removed layer is back to where it was

**Comment by photopea** [comment]
I am very sorry, it is fixed now, thanks for reporting it!
