### ISSUE TITLE
Artboard - Guides turns off when hitting Ctrl+Clic 

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5816]
Create a project with an artboard.

Select the move tool and move a guide from the left to the artboard.

Now do Ctrl+Clic

The guide will disappear.

The toggle of View > Show > Guides won't work

And you can check that the guide is still there on View > Add Guides > Artboard 1

**Comment by photopea** [comment]
When you Ctrl+click somewhere, it is auto-selecting layers (the one you clicked) under your cursor. But locked layers are skipped and can not be selected this way.

I think there was nothing (or only locked layers) under your cursor when you clicked, which means deselecting all previously selected layers. 

And you need to select a layer in some artboard to see the guides of that artboard.

**Comment by TheRadicalDreamer** [comment]
Right!! 

Thank you for the detailed explanation
