### ISSUE TITLE
Variables - When unchecking a variable, the field gets deleted

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5817]
If you go to Image > Variables 

And go to the Visibility text field and you type something, then check the checkbox on the left, the text field will be deleted.

If you write again on the text field, and then uncheck the left checkbox, the text field will be deleted.

Many times i have to check or uncheck the checkbox to see and try something with the final exported file.

It should be good that the checkbox changes won't reset the text input. So we can write the variable name and enable/disable the variable bonding without to rewrite the variable name every time.

**Comment by photopea** [comment]
it should be fixed now.
