### ISSUE TITLE
Variables - Unknown layers

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5818]
In my file i can see on Variable's layers selection dropdown, that there is a layer that i don't have on my layers panel: </Layer group> copy

![image](https://github.com/photopea/photopea/assets/11801254/093aac80-8ac6-42d6-9100-31cc63d1e764)

You can check the file here:
[GL - Weeks.zip](https://github.com/photopea/photopea/files/11939614/GL.-.Weeks.zip)

You can see that there is 2 similar layers on this file

**Comment by photopea** [comment]
fixed!
