### ISSUE TITLE
Crashing opening native psd files

### ISSUE THREAD

**Issue by hallworth** [photopea/photopea#582]
I have been saving a series of psds as I worked on a design. Earlier, less complex versions with fewer layers etc open fine, but later more complex psd files are causing browser crash on open. With and without Webgl enabled. 
Chromium Version 64.0.3282.167 (Official Build) Built on Ubuntu , running on Ubuntu 17.10 (64-bit)

**Comment by photopea** [comment]
Hi, so all your PSDs were created with Photopea? Can you send one of such PSDs to support@photopea.com ?

**Comment by photopea** [comment]
I have to close it because of the lack of details :(
