### ISSUE TITLE
custom themes

### ISSUE THREAD

**Issue by nvkomimi** [photopea/photopea#5821]
what about custom themes? 

like plugins, these would also be shared, installed and used at will by users the same way in the same window for everything else user submitted

the kind of information to be expected when submitting a theme: name, description, author, thumbnail url and css (either url or upload css file)
in case of the css url: the people should post these themes (css files) on github and have photopea import them

context menu mockup:
![image](https://github.com/photopea/photopea/assets/76652465/9245d135-2a8d-48ed-847c-87387e12466e)

quickcss would open up a little code editor that would apply css on the fly, use local storage for this

note: "other themes" and "quickcss" could (or should) be called something else, I'm just putting the idea out here

**Comment by photopea** [comment]
But what exactly would you like to be changed by a theme? Current themes only change colors, they do not change the size of a menu, or a font, or a thickness of button borders. Should we ask people to write a CSS, or just a list of 12 colors?

**Comment by nvkomimi** [comment]
> But what exactly would you like to be changed by a theme? Current themes only change colors, they do not change the size of a menu, or a font, or a thickness of button borders. Should we ask people to write a CSS, or just a list of 12 colors?

I was thinking of full written css themes with the possibility to change everything, also:

the quickcss could give you a css template that'll only change the variables for the colours so you can try it out (and this would apply the css on the fly, basically instant preview), something like this:
```css
/* Make your own theme! Edit these values to change the colours or even add your own CSS */
:root {
  --base: #ffffff;
  --bg-panel: #3c3c3c;
  /* ...etc */
}
```
+ a button to "save and upload/share" it, which would open up the window for submitting a theme with what was in the quickcss

**Comment by photopea** [comment]
Our current CSS has 1,627 lines : https://www.photopea.com/style/all.css . We would probably need 10,000 more lines to describe what our CSS means, so that users read it to know the meaning of each part.

If you think the user should only write new colors, there is no need to ask them to learn CSS syntax, they can simply enter 10 different values in a form.

**Comment by nvkomimi** [comment]
> Our current CSS has 1,627 lines : https://www.photopea.com/style/all.css . We would probably need 10,000 more lines to describe what our CSS means, so that users read it to know the meaning of each part.
> 
> If you think the user should only write new colors, there is no need to ask them to learn CSS syntax, they can simply enter 10 different values in a form.

I didn't mean that you'd have to write new css, just have the current stylesheet and add another inline one to be used for quickcss etc.

**Comment by photopea** [comment]
I am also afraid that if we decide to make a significant change in our desing, user themes would become useless :(

**Comment by nvkomimi** [comment]
then I propose just a simple theme maker that changes the colours, option to instantly preview it and also the option to upload it as a user submitted theme on a theme tab which would work like plugins

my idea of custom css probably doesn't work as well and instead extensions like stylus should be used? however the custom css could also be introduced as a plugin maybe...

**Comment by photopea** [comment]
sorry, I think it is not a priority for now in a near future.

You can make a browser extension that will re-color Photopea. But nobody asked us about custom themes, other than we have already.
