### ISSUE TITLE
Need to improve the switch logic of the sub-function of the window option

### ISSUE THREAD

**Issue by player868** [photopea/photopea#5822]
When using the sub-function on the right, I found some problems, although the sub-function on the right is very convenient, but inevitably there will be redundant or unneeded sub-function. If I want to close this sub-function completely, I can only close it by right-clicking on the right sub-function, but I can't close the right sub-function by long-pressing it, which is especially unfriendly for mobile operation. Can the official add a long-press sub-function to close the operation? Thank you very much!

**Comment by photopea** [comment]
Hi, what is a sub-function?
