### ISSUE TITLE
Is it possible to implement the AI Creative Fill function in photopea similar to Photoshop beta ai?

### ISSUE THREAD

**Issue by player868** [photopea/photopea#5823]
Want a creative AI fill function exactly like Photoshop beta AI, specifically for the edge of the image selected areas to expand to a larger image size, the expanded screen are based on AI generation, can be seamless, not to be inconsistent

**Comment by MichalSZZ** [comment]
There is such a function. Expand your image by using a crop tool. Make a selection in a place of empty space. Go to the magic replace tool and in the top toolbar click on "Replace" (without filling any text in "content")

**Comment by camoody1** [comment]
@MichalSZZ It doesn't work consistently. It never has. But this has nothing to do with what Ivan can fix. This is entirely a third party tool. The result a user gets is entirely based on how descriptive they are with their prompt. And even then, sometimes it doesn't matter. The current tool being used is not, and will not be, an exact replica of what Adobe provides with Generative Fill.

**Comment by MichalSZZ** [comment]
@camoody1 I am using beta of Photoshop for a while and their Generative Fill works absolutly different than other tools (they respect property of used images and pay authors of oryginal). They use only stock photos/vector images from Adobe Stock. The images for AI learning was excelent quality, precisly selected. Results are great but only when there are many photos/graphics if the subject in the Stock.

**Comment by photopea** [comment]
I will close it, as the current Magic Replace is the best I can provide you. I wish that at least 0.1% of our users paid for Photopea Premium, but we are far from that :(
