### ISSUE TITLE
Very disaligned GUI

### ISSUE THREAD

**Issue by jk0424** [photopea/photopea#5825]
Any feature I use whether it be hue/saturation, the color pallete or even start new project, the GUI is severely disaligned, making the features unusable.
![2023-07-04 (1)](https://github.com/photopea/photopea/assets/138529946/b844df7b-c6bb-4bb0-ad78-f4224104ea78)
![2023-07-04 (2)](https://github.com/photopea/photopea/assets/138529946/b3b8d150-62c6-47e9-b631-8b8a8b5b522b)
![2023-07-04 (3)](https://github.com/photopea/photopea/assets/138529946/f8dc1ce7-f0af-4503-ada7-f4eed5a4d629)

**Comment by photopea** [comment]
I think Photopea is being modified by your browser extensions.

Please, let us know if it happens in case when none of your browser extensions has permissions to modify Photopea.

**Comment by photopea** [comment]
I have to close it as the person did not respond.
