### ISSUE TITLE
Fullscreen is broken in Firefox

### ISSUE THREAD

**Issue by MasterKia** [photopea/photopea#5827]
Steps to reproduce:
1. Go to `photopea.com` using Firefox and open the console.
2. Click on the "Fullscreen" icon.
3. Error in the console:
```
Uncaught TypeError: navigator.keyboard is undefined
    https://www.photopea.com/code/pp/pp.js
```

Entering these in the console fixes it:
```js
navigator.keyboard = function() {}
navigator.keyboard.lock = function() {}
```

According to MDN, `navigator.keyboard` is an experimental feature and is not supported by Firefox:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/keyboard#browser_compatibility

**Comment by photopea** [comment]
fixed! thanks :)
