### ISSUE TITLE
Color changing in text automatically bug

### ISSUE THREAD

**Issue by MarekS1215** [photopea/photopea#5829]
The first character in text items keeps on automatically changing to seemingly random colors. It takes a minute for it to replicate and only seems to happen with recently copy/pasted text items.

https://github.com/photopea/photopea/assets/125227726/a46fd229-d308-4d40-bacd-6c0d4118c346

**Comment by photopea** [comment]
Could you share your PSD with us? You can attach it here in your comment in a ZIP file.

**Comment by camoody1** [comment]
@photopea Is this possibly related to the change you made for issue #5754?

**Comment by photopea** [comment]
maybe, I need to reproduce it first

**Comment by camoody1** [comment]
I just noticed that the text in the video was changing to match the primary color he had selected. So, thought that would be a good starting point.

**Comment by photopea** [comment]
I still need a person to send me a PSD, so that I can reproduce it.

**Comment by photopea** [comment]
Could you tell me what should I do to see it myself?

**Comment by photopea** [comment]
I have to close it as the person did not respond.
