### ISSUE TITLE
after the crop to selection on zoomed image, resulting image is placed out of the view

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#583]
- open big enough image
- zoom in on something in its corner (far enough from the center)
- select something and crop to selection

expected result:

the resulting cropped image positioned in the center

actual result:

it is outside of the view

if you do this without zooming in, at 100%, resulting image IS placed in the center, however the selection, which you would expect to be on the resulting image's perimeter, is positioned somewhere else

**Comment by photopea** [comment]
It should be fixed now.
