### ISSUE TITLE
Can I add an undo result button for magic replace next to the replace button?

### ISSUE THREAD

**Issue by player868** [photopea/photopea#5830]
Is it possible to add an undo result button for magic replace next to the replace button? When the generated image results are very strange, it is very easy to undo the generated results on computer, but it is very troublesome to undo on mobile.

**Comment by player868** [comment]
@photopea

**Comment by camoody1** [comment]
@player868 He lives in the Czech Republic. Let him sleep. 😆

**Comment by photopea** [comment]
I have added the Undo button next to the Replace button.
