### ISSUE TITLE
Fill Pattern - Go beyond 100 on Off X/Y with arrow keys

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5831]
![image](https://github.com/photopea/photopea/assets/11801254/720efe62-f640-410d-a9be-ab72ba11a7f6)

Can we please be able to move 1 step (up or down) with the arrow keys beyond +100/-100 ?

But if i manually type 250 (for example) i get the correct result, but if i move the input with the arrow keys, it returns to 100 :/

**Comment by TheRadicalDreamer** [comment]
Video explaining: 

https://github.com/photopea/photopea/assets/11801254/be086ae6-7670-482d-8a06-95af1a929e84

**Comment by photopea** [comment]
it should be fixed now.
