### ISSUE TITLE
Adobe Illustrator is worst than Photopea

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5832]
Well, i am a bit frustrated, because i made a whole work on Photopea, without any issue.

But my printing provider opens it on AI, they cannot see every shape in the project.

This is how it looks like the page 13:
![image](https://github.com/photopea/photopea/assets/11801254/0f1c8701-1148-46a8-b742-0c07a9a293b4)

This is how AI opens it:
![image](https://github.com/photopea/photopea/assets/11801254/8d8404a2-9041-4d50-8272-558621365af7)

So, i am writing here to ask for an unconventional help: How Photopea can export a PDF file that AI can properly read?
Neither acrobat reader can see it properly.

Here is the PSD. Maybe it is something related to the shape, i don't know.
[Page 1.zip](https://github.com/photopea/photopea/files/11973796/Page.1.zip)

**Comment by TheRadicalDreamer** [comment]
I re made the shape: raster, and vectorized, and now it can be seen in AI.

I will close this issue, but maybe there is something still with the meta-data of the shape that is lost or broken.

In AI my clint got that message, so i leave it here.

**Comment by photopea** [comment]
Your shape is really weird. Why do you use both fill and stroke on it?

![image](https://github.com/photopea/photopea/assets/15955558/d49bb498-15f6-40a0-a4b7-85efb1ca2c8b)

**Comment by TheRadicalDreamer** [comment]
i use fill and stroke, because the illustration was drawn with brush first, then vectorized.

After that i have to shrink it to the adequate size, and when i do that some lines get too thin and cannot be seen, so i "correct" the illustration by using stroke.

**Comment by photopea** [comment]
It seems like Adobe Illustrator can not detect transparency groups properly. E.g. in this file: the fill and the stroke has a 50% opacity, but you should not see the fill under the stroke. So we must make a transparency group.

[opct.pdf](https://github.com/photopea/photopea/files/11995516/opct.pdf)

Each layer in a PSD has an opacity: a number between 0 and 255. Your layer shape has the opacity of 254. Both 255 and 254 are shown as 100% in the Layers panel.

I dont know how you managed to set the opacity of your layer to 254. If you type 100%, it should be set to 255. If you type 99%, it is set to 252. Setting it to 253 or 254 should be impossible.

So just set the opacity of "disappearing layers" to 100% and export a PDF again.

**Comment by TheRadicalDreamer** [comment]
Thanks!!

It did the trick! 🥳

I don't know how i got them to have 254 on opacity.  ¯\_(⊙_ʖ⊙)_/¯
