### ISSUE TITLE
The problem of window overflowing the screen

### ISSUE THREAD

**Issue by player868** [photopea/photopea#5833]
![IMG_20230707_165152](https://github.com/photopea/photopea/assets/129951996/c9e0f421-88ca-4654-9d15-d5c9eaec0347)
@photopea This can be an issue that needs to be fixed, it's like this, when I click on the advanced option of AI magic replacement [what is enclosed in the red box], the window screen display on the mobile side, the right side may be covered by the overflow, so it can't display this window properly, can you help me to move this overflow screen window to the orange box position? If you can, I'd be very grateful to the Photopea team!

**Comment by camoody1** [comment]
I have the same issue on my mobile phone.

**Comment by player868** [comment]
@photopea

**Comment by photopea** [comment]
fixed!
