### ISSUE TITLE
CMYK most common Profiles

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5835]
This is an old issue, i know, but i am still getting problems, and i want to check if this can be achieved

The thing is the color profile we have in Photopea is different from each Photoshop/Illustrator. 

So, somehow when i send to my client the CYMK PSD/PDF they get different CMYK codes for each color.

For example, i sent a square shape in red (cmyk 0,99,100,0)

When they open it, they see the file is in CMYK (fine) but they see cmyk 0,95,91,0

So i am not able to send the correct colors they need. 

And this also happens when i send to print. So the color is not the same, and the work, when the color is strict, is almost impossible. I have have to give them every color code, so they have to correct it.

I investigated and every country/continent have a different default cymk color profile:
CoatedFOGRA39 - For latin america and europe
US Web Coated (SWOP) v2 - For north america
Japan color 2001 Coated - For asia

So, i know it is a difficult task, but can photopea have the same range (or maybe the most used ones) of color profiles?

It is even possible to add them?

Thank you in advance

**Comment by TheRadicalDreamer** [comment]
Or maybe, can you tell us what color profile has Photopea?

So maybe in some cases I can ask them to change theirs

**Comment by photopea** [comment]
Every file (PNG, JPG, PSD, PDF, ...), not only from Photopea, must already contain all necessary information about the colors in it.

I did this with a color picker in Adobe Photoshop:
set CMYK 0,99,100,0,  I see RGB 237,33,36
I set RGB 237,33,36, I see CMYK 1,98,98,0

I made a rectangle in Photopea, set the color to CMYK 0,99,100,0
I exported it as a PDF, opened it in Adobe Illustrator, I see CMYK 1,98,98,0

Actually, 0,99,100,0  and 1,98,98,0 are the same colors. There are many ways to describe the same color in CMYK.

I guess you are using Image - Mode - CMYK, and you use it permanently. If you do, you lose some precision every time you open and save your work as a PSD. I recommend turning it on only once in a while, to check if your RGB colors are pritnable.

BTW I improved the color mechanism when exporting a PDF with the CMYK mode enabled in Photopea.

**Comment by TheRadicalDreamer** [comment]
> Actually, 0,99,100,0 and 1,98,98,0 are the same colors. There are many ways to describe the same color in CMYK.

What!? Really?


> I guess you are using Image - Mode - CMYK, and you use it permanently. 

You are right, because i only do print work. Why do i lose some color precision every time I open and save the file? Can you elaborate this point please?

I do work with cymk permanently because i always want to see and work with the final colors the project will get.

**Comment by photopea** [comment]
If you have some CMYK colors in Adobe Photoshop, and you switch to the RGB mode, and then, to CMYK mode, your colors will be different. And if you repeat it many times, you will end up with totally different colors.

Photopea always works in an RGB mode (the CMYK mode is just a hidden adjustment on top of the document). But if you save a PSD, we convert it to true CMYK colors, and when you open that PSD, it is converted back to RGB (but only pixel data, not the vector graphics).

If you work only with vector graphics, keeping CMYK on should be fine. And an exported PDF should have "more proper colors" now.

**Comment by TheRadicalDreamer** [comment]
Thank you for the detailed explanation.

I'll keep it memorized.

I do work 99% of the time in vectors and CMYK, so it should be fine for me.

**Comment by TheRadicalDreamer** [comment]
Also, i have to say that Photoshop ask you, when you open a PSD that have been saved as CYMK to open on a sRGB or a CMYK profile before showing you the project.

Now that you said that i believe it might be to prevent that change 
> But if you save a PSD, we convert it to true CMYK colors, and when you open that PSD, it is converted back to RGB
