### ISSUE TITLE
Stimulate Pressure with Pen Tool

### ISSUE THREAD

**Issue by CxryzNFTs** [photopea/photopea#5836]
Hello, is there a way to activate stimulate pressure when drawing lines with the pen tool? Look at the reference below, Photoshop has this feature.
![image](https://github.com/photopea/photopea/assets/71056820/16f0a44b-87e6-470e-a12c-9d37e49b22c0)

**Comment by camoody1** [comment]
@CxryzNFTs Have you even been able to use the Stroke Path option in Photopea? I keep creating Paths, but the option to Stroke the Path is always grayed out for me. If I right-click on the Path, it's grayed out. If I click on the Edit menu, the Stroke option is grayed out. It seems like it should be a very straight forward tool, but I just can't get it to work.

@photopea Am I missing something simple? Or is there a bug preventing the use of the Stroke option on Paths?

**Comment by camoody1** [comment]
Here is very short video showing how it should work. Of course, you should get the same dialogue box if you right-click on the Path or use the Stroke option under the Edit menu.
https://youtu.be/4rJ15vaYapU

**Comment by CxryzNFTs** [comment]
There is no "Stroke Path" option, or am I blind?

**Comment by CxryzNFTs** [comment]
I know how to stroke a path, but how do I enable "Stimulate Pressure"?

**Comment by camoody1** [comment]
@CxryzNFTs The video was on Photoshop. It was meant to show Ivan how it _should_ work.

**Comment by MichalSZZ** [comment]
There is an option to stroke a path.
Firt of all you have to draw a path. With a pen tool or shape tool BUT in a path mode (upper left corner switch mode from shape to path).
Then (for sure) make a new layer. Go to the Path palette and click on the 2nd icon from the left. Maybe there shoyld to be something in the Right Mouse button vut now I am checking on the mobile.

For pen presure simulation... maybe changing the Brush dynamic in the Brush setting can help?

**Comment by camoody1** [comment]
@MichalSZZ He knows how to use the Stroke function. He's just looking to add the option to Stimulate Pen Pressure like in Photoshop.

And no, setting the Pen Pressure option in the Brush setting does not affect the Stroke option. I tested that earlier. This would be new functionality.

**Comment by photopea** [comment]
I just checked and everything in Photopea seems to work exactly as in Adobe Photoshop.

Guys, this is not the place to teach each other how to use Adobe Photoshop or Photopea. Please, discuss these things at Reddit: https://www.reddit.com/r/photopea
![image (1)](https://github.com/photopea/photopea/assets/15955558/4efc9a7e-ebd6-4295-ad01-6fee88ae0416)

**Comment by photopea** [comment]
I just noticed that right-clicking the path and choosing "Stroke" did not open the Stroke Path window, so I have fixed it.

**Comment by camoody1** [comment]
THANK YOU

I tried 10 different times to reproduce how it works on Photoshop. Not once was I able to find the Stroke Paths popup window with the Simulate Pen Pressure. I thought I'd lost my mind or something.

**Comment by photopea** [comment]
You can also press Windows - Paths, and click the "Stroke Path" button at the bottom, with the Alt key pressed. 

It is all described here: https://helpx.adobe.com/photoshop/using/adding-color-paths.html

**Comment by CxryzNFTs** [comment]
Thank you very much.
