### ISSUE TITLE
Moving Layer Using Script

### ISSUE THREAD

**Issue by elijahgives** [photopea/photopea#5837]
Hello!
I'm wondering if there's a way using the Photopea Scripting API to move a layer to specific coordinates. I know `translate` exists, but I'm wondering if there's another way (e.x move a layer from it's current x position to x 1500).

**Comment by Pt-home** [comment]
Hello. I think the answer is no. In Photoshop, this is still possible through very cumbersome scripts using mouse coordinates or keyboard events. I recently spent a couple of months studying what and how works in Photopea using scripts and I can’t think of any other way than translate

**Comment by photopea** [comment]
I just tried this and it seems to work fine in Adobe Photoshop and in Photopea:

        function moveTo(l,X,Y) {
	        var bs = l.bounds;  
	        l.translate(X-bs[0].value, Y-bs[1].value);
        }
        
        moveTo(app.activeDocument.activeLayer, 400,200);

**Comment by elijahgives** [comment]
Would there be a way with this to center the layer on the x-axis? 
What I'm currently trying to do is edit text and then center it, but the issue I'm having is:
The length of the text is different, so the top left corner distance is different based on the text length. However, the top middle box is always the same x/y value no matter the text length. So I'm wondering if I can move it based on that rather than the top left corner position, allowing me to center the text no matter the text length. :)

**Comment by camoody1** [comment]
@elijahgives Instead of just a single text line, could you try using a paragraph box that is drawn to be the full width of the layer? Then, just set the text within that paragraph box to be centered. If you could set that up with a script, then you could edit the text to be whatever you want and it will always be centered on the layer.

**Comment by photopea** [comment]
Please, discuss this on Reddit. This place is for reporting problems in Photopea, not for getting courses on how to use it :D https://www.reddit.com/r/photopea

**Comment by That-Ruben** [comment]
When was this discussed in reddit? Does anyone have a link?
