### ISSUE TITLE
Неправильно работает свободное трансформирование

### ISSUE THREAD

**Issue by deniszszZ** [photopea/photopea#5838]
Вместо изменения длины или ширины фигуры меняется ее масштаб

**Comment by camoody1** [comment]
If you want to change JUST the length or the width of a shape, you need to uncheck the little "chain link" button in the top toolbar after you have selected the Transform tool.

**Comment by photopea** [comment]
You can learn how it works here: https://www.photopea.com/tuts/new-free-transform/
