### ISSUE TITLE
Photopea Filter Torn Edges doesn't work

### ISSUE THREAD

**Issue by Arne-Peeters** [photopea/photopea#5839]
Hi, when I try to apply the Torn edges filter in Photopea, it just leaves a white surface on my image (jpg file).
I tried it with several images.
Can someone please help me to fix this? 

<img width="1140" alt="Schermafbeelding 2023-07-08 om 17 26 05" src="https://github.com/photopea/photopea/assets/130282822/285fc1dc-b3d0-454c-b5b9-2969982db5ed">

Thanks a lot,
Arne

**Comment by photopea** [comment]
This filter combines the foreground color with the backgorund color. I think both are white in your case.

I have added a message. Now, Photopea will tell you, when these two colors are identical.

**Comment by Arne-Peeters** [comment]
You're right, thanks a lot for the help!
