### ISSUE TITLE
After a new fill layer is added, all layer icons in layers panel disappear

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#584]
This is specific to safari mac,
The action of adding a new fill layer, all three types, will cause all layer icons in layers panel to disappear, even after the fill layer is removed.

**Comment by photopea** [comment]
Can you show us a screenshot? Are you using the latest Safari? What about opening a PSD, that contains a fill layer?

**Comment by hgs54371** [comment]
Normal layers
![screen shot 2018-03-30 at 7 09 01 am](https://user-images.githubusercontent.com/36803688/38117765-789eb68a-33e9-11e8-8955-b1044b6afe89.jpg)

Fill layer added
![screen shot 2018-03-30 at 7 09 25 am](https://user-images.githubusercontent.com/36803688/38117767-7d739478-33e9-11e8-9d6b-575237230971.jpg)

Fill layer removed
![screen shot 2018-03-30 at 7 10 10 am](https://user-images.githubusercontent.com/36803688/38117770-7fadc36c-33e9-11e8-807c-7a691a1ccf54.jpg)

After this, creating any new projects the layer icons are also all black, have to refresh the whole page to return to normal

Save it as psd then reopen still the same

**Comment by photopea** [comment]
Can you see any errors in a browser console?

**Comment by hgs54371** [comment]
There's this error in console, but it was always there, 

Nothing additional happened before/after fill layer is added

![screen shot 2018-03-31 at 12 52 03 am](https://user-images.githubusercontent.com/36803688/38145821-cfda5794-347d-11e8-85d9-7f3d77e43c52.jpg)

**Comment by photopea** [comment]
Can you inspect the layer thumbnail element? Is the little canvas still there?

BTW. your main working area is black, is that correct or it is also a part of error?

**Comment by hgs54371** [comment]
[test2.mp4.zip](https://github.com/photopea/photopea/files/1864636/test2.mp4.zip)

Drag it and hover across others in layers panel will reveal them temporarily, the open/close of web inspector also will, I showed it in the video above

The black is just color manually changed

**Comment by hgs54371** [comment]
When the fly out brush panel is open, the layer icons also turn black, also specific to safari mac

![screen shot 2018-04-02 at 3 09 27 am](https://user-images.githubusercontent.com/36803688/38176578-0c1dae52-3624-11e8-8a9e-e7d24a74e3d5.jpg)

**Comment by photopea** [comment]
Do thumbnails disappear also after opening other panels? Or only Brushes?

**Comment by hgs54371** [comment]
Now I discovered, All panel open will turn them black

**Comment by photopea** [comment]
After all these trouble, I am seriously considering, that I will recommend my users not to use Safari (until Apple fixes it)  :(

**Comment by photopea** [comment]
I am giving it up. Just use another browser until Apple fixes it. If you have enough time, report it to Apple and discuss it with them (I don't own a Mac to be able to cooperate with them on fixing this bug).
