### ISSUE TITLE
Remove and replace

### ISSUE THREAD

**Issue by dada5872** [photopea/photopea#5840]
Remove and replace
Where did the button go
I am a new user and have just recharged $15
After opening it, the replace button cannot be found,
Seek help

**Comment by photopea** [comment]
Hi, could you show us a screenshot of what is going on? I do not understand.

**Comment by dada5872** [comment]
This is my interface, without the remove and replace buttons
![image](https://github.com/photopea/photopea/assets/69775612/73fee9eb-23a0-4d88-8507-72fd706db1b0)
-
-
-
-


This is someone else's interface. I took a screenshot from their feedback and they have these two buttons
![image](https://github.com/photopea/photopea/assets/69775612/fa5f0f75-50a4-4360-806d-85c6a56dc284)

**Comment by camoody1** [comment]
You've selected the wrong tool.

In the top image, you've chosen the Lasso Select tool. The bottom image has chosen the Magic Replace tool. It is located in the healing tools section.

**Comment by dada5872** [comment]
I found it, thank you

**Comment by camoody1** [comment]
You're welcome. Have a great week!

**Comment by photopea** [comment]
cool :)
