### ISSUE TITLE
Cannot edit/scale image size via the API within a smart object

### ISSUE THREAD

**Issue by achievrr** [photopea/photopea#5841]
Hi,

I am using Photopea's API to create some mockup automations and I'm experiencing some issues trying to scale/edit the image size within a smart object. 

ex: The initial image size inserted in the smart object is 1000x1000 pixels, and I want it to be 2000x2000 pixels so that it covers my entire smart object's mockup.

Here are the steps that I'm following:

1. Open PSD mockup in photopea
2. Detect and open smart object: var l = app.activeDocument.layers.getByName("smart"); 
3. Insert my desired image into the smart object: app.open("${url}", null, "asSmart:true");
4. **Here is where I'm facing issues, after inserting the image in the smart object, I am having trouble changing the size or positioning of the image. I tried searching within the API documentation but could not find any info about this.** 

Here is how the image gets imported:
<img width="1758" alt="howitlooks" src="https://github.com/photopea/photopea/assets/136190623/d1320c7f-2029-4b14-97ac-1189521dd76e">

Here is an example of how I want to edit it/scale it/change it's size:
<img width="1767" alt="howIwantitolook" src="https://github.com/photopea/photopea/assets/136190623/b934d3f1-42f4-49e2-9ee7-835cd7450424">

**After I the size is edited, I am saving the smart object, closing it, and exporting the output PSD as PNG using 'app.activeDocument.saveToOE("png");' Everything is working good, I just have to figure out how to change the size of the inserted image within the smart object before saving and closing the smart object.**

Any help would be much appreciated.

**Comment by photopea** [comment]
Since our scripts should work the same as in Adobe Photoshop, could you provide a script, which works in Photoshop, but does not work in Photopea?

BTW. the open() command initiates the download of a file. You should wait until the file is inserted, before you start working with it.

**Comment by photopea** [comment]
I have to close it as the person did not respond.
