### ISSUE TITLE
Feature Request: New Vector Shape Corner UI to Match PS

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5842]
The newest PS version has added a new UI element to make working with the corners of vector shapes easier. It's quite ingenious and would be a nice add for Photopea to have to keep pace with the Adobe updates.

Here is a video showing the new UI. The important part begins around 1:10...
https://youtu.be/tJ1N2TXODCc

**Comment by klaslod** [comment]
Have you ever heard the phrase "Id rather shove a cactus up my bum"

**Comment by bennyschmidt** [comment]
> to keep pace with the Adobe updates.

Is this a stated goal of Photopea? Should I look out for the Creative Cloud downloader soon? IMO Photopea is great because it's a free-to-use version of the Photoshop we all know and love from the iconic years.

**Comment by photopea** [comment]
I have implemented it. I think it is very useful, pretty much all design related programs have it.

![image](https://github.com/user-attachments/assets/01cfb511-76b5-4acc-9103-241527662632)
