### ISSUE TITLE
Magic Replace not working?

### ISSUE THREAD

**Issue by CxryzNFTs** [photopea/photopea#5843]
Hello, magic replace is not generating any result. I've attached a screen recording below and the image I used so you can try it for yourself.
[Screen recording 2023-07-09 5.34.36 PM.webm](https://github.com/photopea/photopea/assets/71056820/6627477a-08b3-4526-a2da-e1a263b63865)
![SummerWIP](https://github.com/photopea/photopea/assets/71056820/2eda29fc-7045-4f1a-aa6b-4bb8685743b6)

**Comment by camoody1** [comment]
It's likely that your selection is too wide. The maximum width and/or height allowable is 1024px.

**Comment by photopea** [comment]
It works fine for me. You might have to wait a bit more, or click it one more time.

**Comment by camoody1** [comment]
> It works fine for me. You might have to wait a bit more, or click it one more time.

It does "technically" work if you select a size smaller than 1000px, but lately, it's been returning some really bad results. When I try to fill in the sky on this person's image, I get all sorts of weird results.

Example:
![252181581-2eda29fc-7045-4f1a-aa6b-4bb8685743b6](https://github.com/photopea/photopea/assets/73725653/37cd23e6-f0b6-4617-b711-769ef13b5942)

I have to wonder if Dezgo changed something with Inpainting on their end or something.

**Comment by camoody1** [comment]
To be clear...

Actual Inpainting where I'm changing something inside an image still works well with a good prompt. But Outpainting to add additional image where there was nothing before feels like it has gotten worse.🤷🏽‍♂️

**Comment by photopea** [comment]
Maybe select the bigger part of the "known" image?

**Comment by camoody1** [comment]
> Maybe select the bigger part of the "known" image?

I thought that, too. But I tried small parts of the original image and larger parts. Both options, at least for this image, gave me pretty bad results. I do get some Outpainting that works occasionally, but I get a lot that turn out like this, too.

**Comment by camoody1** [comment]
I sent a message to Clem on Discord to see if he might have any insight.

**Comment by camoody1** [comment]
Clem said they haven't changed anything on their side since March. Maybe I've just run into a string of bad luck, recently. 🤷🏽‍♂️
