### ISSUE TITLE
Part of the menu is cut off?

### ISSUE THREAD

**Issue by Laurennial** [photopea/photopea#5844]
This is the same on my browser (Chrome, updated to the current version) and on the downloaded version of Photopea (which is basically just like a link anyway, right?). I thought at first that it was just set to some odd settings, but then I noticed that the word "About" was cut off on the upper right, so I zoomed out a bit (90%) and I could see the rest of the GUI on the right. 

This is a screenshot at 100% zoom:
![photopea 100 zoom](https://github.com/photopea/photopea/assets/54823524/ea6ecd14-b4f1-4440-a773-3d482a0ec90c)

This is zoomed out 90%:
![photopea gui zoomed out](https://github.com/photopea/photopea/assets/54823524/44357850-cb1d-4fef-bcd2-402ae0343737)

**Comment by photopea** [comment]
This is done by your browser extensions. Do you use Ublock Origins? I have heard that Ublock Origins does that sometimes. You should report it to Ublock Origins, as it is them who do this to you.
