### ISSUE TITLE
File save as 0 kb

### ISSUE THREAD

**Issue by bcblacker** [photopea/photopea#5845]
Twice I worked on a PSD project for several hours. I saved as I went and allowed ample time for saving (it was a larger file). Anything I can do to prevent this from happening a third time?

**Comment by bcblacker** [comment]
Yes
 It saved correctly for several days then one day or didn't. I restarted my
project, then on the second or third save it did the same thing again,
dropping the file size to 0 kb.

**Comment by raabe-ctrl** [comment]
it's a bug. It happens with me sometimes, when it's a very large file. I can't make Photopea produce it on purpose, but it happens. To avoid it, I try to always keep saving the file, and when it gets too heavy, I make a copy of it on my computer. Then, if the bug happens with the one I'm working on, at least I have the copy I made. Then I try something to reduce the file size, like rasterizing a large image (that is a smart object).

**Comment by photopea** [comment]
I have to close it as the person did not respond.
