### ISSUE TITLE
The sidebar letters are very tiny

### ISSUE THREAD

**Issue by Eastiwiesty** [photopea/photopea#5847]
![Screenshot 2023-07-10 215714](https://github.com/photopea/photopea/assets/138159744/a03a24fd-bbe5-4a8f-b360-00e89b96cb72)

**Comment by photopea** [comment]
I think it is this: https://www.photopea.com/tuts/interface-of-photopea-is-too-small/ :)

**Comment by photopea** [comment]
![image](https://github.com/photopea/photopea/assets/15955558/2d8ceb23-dad7-4d9c-8c4a-2ebd5bc2db05)
