### ISSUE TITLE
Show grid and guide are from the paid version? 

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5848]
I am wondering if these options are from the paid version.

Because my colleague cannot show them on his project

**Comment by camoody1** [comment]
Have you tried logging out of your account and seeing if they still work on your device? That would tell you if it's for paid accounts only.

**Comment by TheRadicalDreamer** [comment]
I tried.

Had no extension whatsoever.

He says he does something... Close this issue. But if I get to repro I'll
open a new one

**Comment by photopea** [comment]
I have to close it as the person did not respond.

**Comment by TheRadicalDreamer** [comment]
No, and i have worked next to him the last month, so, so far i cannot repro this bug :P
