### ISSUE TITLE
One small suggestion

### ISSUE THREAD

**Issue by player868** [photopea/photopea#5849]
In the AI Magic Replacement feature, when the selected box area is in the state of the AI Replacement area, can a progress bar in processing be displayed for this purpose?

**Comment by player868** [comment]
Simply put, when using AI Magic Replacement, if the AI in AI Magic Replacement is replacing the selected area, I would like to present the progress of the task in AI Processing as a progress bar.

**Comment by player868** [comment]
@photopea

**Comment by camoody1** [comment]
> @photopea

You don't need to specifically address the developer. He sees all of these posts.👍🏼

**Comment by photopea** [comment]
I have fixed it. There will be a message "Processing ..." at the top, until a moment that it is actually done.
