### ISSUE TITLE
no dotted lines

### ISSUE THREAD

**Issue by jbassiri** [photopea/photopea#5850]
The dotted line feature is not working. It is a complete line.

**Comment by camoody1** [comment]
Which fitted line feature? What tool are you using?

**Comment by photopea** [comment]
Are you talking about the Line tool? The Line tool draws a thin rectangle, not a stroked contour. You can learn more here: https://www.photopea.com/learn/vector-graphics

**Comment by MichalSZZ** [comment]
@photopea I think some time ago (2 years ago?) the line tool was changed, and now it works like the real line - not the rectangle with stroke like before.
Look (screen from Photoshop 24.6.0):
![obraz](https://github.com/photopea/photopea/assets/38118273/f227fbbc-9d55-4e8a-98ec-4506ed7e4b16)

**Comment by photopea** [comment]
The Line tool in Photopea should work exactly as in Adobe Photoshop now.

In Photoshop, if you set "Weight" to zero (at the top), it draws a two-point line. If you set it to more than zero, it draws a four-point line (a thin rotated rectangle).
