### ISSUE TITLE
Help with crop script

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5851]
This little thing does not work in scripts:
      **var bounds = [
            [0, 0],
            [50, 0],
            [50, 50],
            [0, 50]
          ];
      app.activeDocument.crop(bounds);**
And it is unexpectedly urgently needed:) Thank you!

**Comment by photopea** [comment]
Your script does not work for me :(  (not in Photoshop, not in Photopea).

I tried this and it works (in Photoshop and in Photopea)

    var bounds = [ 600,300,800,400 ];
    app.activeDocument.crop(bounds);

**Comment by Pt-home** [comment]
oh thanks, how did I not think to check this option instead of rummaging through the adobe documentation
