### ISSUE TITLE
There is a sentence about ad blocking

### ISSUE THREAD

**Issue by Rojamnyorski** [photopea/photopea#5852]
The sentence is there even though I did turn off the default block ads extension on Opera GX, even turning off other extensions such as DashLane, Grammarly, Enhancer for YouTube™ and, Opera Wallet still block your ads. I don't know why, but I'm sorry I didn't receive your ads. Please fix this!

**Comment by photopea** [comment]
Did you try to run Photopea with absolutely no site-modifying extensions? Maybe some of your extensions are still blocking ads.

**Comment by Rojamnyorski** [comment]
> Did you try to run Photopea with absolutely no site-modifying extensions? Maybe some of your extensions are still blocking ads.

I don't know what a site-modifying extension is but no ads have been shown. Good news, I figure out that make the ads shown, by turning off the Privacy Protection or blocking trackers. On Full Browser Settings > search Privacy Protection > Manage Exception > Add a website. Another option is to go to the website you want and then press the shield symbol with the check or x-mark symbol on the link bar or toolbar, next press turn off for this site.

**Comment by photopea** [comment]
great! I never used Opera and I had no idea they do this.
