### ISSUE TITLE
is it possible to create an image from user inputs?

### ISSUE THREAD

**Issue by Nerxxy** [photopea/photopea#5854]
for example, if i have a form sheet asking what colour gradient i want and i choose red to green can it make the gradient of red to green? is it also possible to have it animate infinitely?

i hope this makes sense. 

essentially i want to be able to make images like this:
https://cdn.7tv.app/misc/img_paints/tc23eu.webp
just from user inputs

**Comment by photopea** [comment]
So you want to make an animation like this? I made something similar in the past (click to randomize the effect) https://lib.ivank.net/demos/plasma.html

A Clouds filter with a Gradient Map adjustment could look similar. But in general, there can be billions of effects like this, I think you need to be a programmer to make such an effect.
