### ISSUE TITLE
Brushes Disappearing.

### ISSUE THREAD

**Issue by MotziRBX** [photopea/photopea#5855]
So um...my photopea has been crashing and every time I re open it all my brushes are gone. I have so many brushes I use daily for commissions, and they keep disappearing! I have to go back and find all the brushes again in my drive and reupload them. Does anyone know why this is happening?

**Comment by photopea** [comment]
Do you mean loading ABR files into Photopea? So they disappear only after Photopea crashes, or every time you close Photopea? Or does it crash because of you opening brushes?

It is not clear to me. I need to see your problem on my computer somehow. What should I do?

Note, that you also might have browser extesnions, which dont allow websites to store anything on your computer (like brushes).

**Comment by MotziRBX** [comment]
> Do you mean loading ABR files into Photopea? So they disappear only after Photopea crashes, or every time you close Photopea? Or does it crash because of you opening brushes?
> 
> It is not clear to me. I need to see your problem on my computer somehow. What should I do?
> 
> Note, that you also might have browser extesnions, which dont allow websites to store anything on your computer (like brushes).

Yes so basically I use the desktop app for photopea. I upload a bunch of .abr brushes to use for my commissions, and sometimes when I upload a new brush it’ll crash and then when I load photpea back up all brushes are gone as well as text styles. Idk why it’s doing this.

**Comment by photopea** [comment]
Could you look into Edit - Local Storage? How many files do you have there?

**Comment by MotziRBX** [comment]
> Could you look into Edit - Local Storage? How many files do you have there?

How do I get there? I can check. I had probably like 20 brushes imported

**Comment by photopea** [comment]
go to www.Photopea.com and you will see "Edit" at the top. click it, and you will see "Local Storage" at the bottom of the menu.

**Comment by MotziRBX** [comment]
> go to [www.Photopea.com](http://www.Photopea.com) and you will see "Edit" at the top. click it, and you will see "Local Storage" at the bottom of the menu.

Okay I opened that, and its showing them right now because I put them all back in last night, but when they disappear, they literally disappear and it says 0tb under local storage. :(

**Comment by photopea** [comment]
Did they disappear? What did you do to make them disappear? I need to reproduce this problem on my computer.

**Comment by MotziRBX** [comment]
> Did they disappear? What did you do to make them disappear? I need to reproduce this problem on my computer.

I imported them back in last night, but usually they disappear. I didn't do anything, sometimes it will crash in the middle of me making something and they'll all be gone. And sometimes when I import a new brush, they all disappear.

**Comment by MotziRBX** [comment]
> > Did they disappear? What did you do to make them disappear? I need to reproduce this problem on my computer.
> 
> I imported them back in last night, but usually they disappear. I didn't do anything, sometimes it will crash in the middle of me making something and they'll all be gone. And sometimes when I import a new brush, they all disappear.

also it happens with fonts I import as well.

**Comment by photopea** [comment]
Could you open Photopea and click the "puzzle piece icon" at the top right corner of your browser, and send me a screenshot of what you see there?

**Comment by photopea** [comment]
When you put files into a Local Storage, close Photopea, and reopen it again, are your files still in that Local Storage?

**Comment by MotziRBX** [comment]
> Could you open Photopea and click the "puzzle piece icon" at the top right corner of your browser, and send me a screenshot of what you see there?

Okay i can do that

**Comment by MotziRBX** [comment]
> Could you open Photopea and click the "puzzle piece icon" at the top right corner of your browser, and send me a screenshot of what you see there?

Oh wait, I use the desktop version of photopea.

**Comment by camoody1** [comment]
> > Could you open Photopea and click the "puzzle piece icon" at the top right corner of your browser, and send me a screenshot of what you see there?
> 
> Oh wait, I use the desktop version of photopea, So i dont have the puzzle piece thing.

Click on the three dots in the top right of the toolbar next to minimize. You'll see the puzzle piece (Extensions) under there.

**Comment by photopea** [comment]
Could you show us a screenshot of what you see? Even a "desktop version" is still running in your web browser, and all your browser extensions are running, too.

**Comment by MotziRBX** [comment]
> Could you show us a screenshot of what you see? Even a "desktop version" is still running in your web browser, and all your browser extensions are running, too.

Yes I can! I have a few ro extensions so that might be it? but idk ill screenshot

**Comment by MotziRBX** [comment]
![Screenshot 2023-07-17 152143](https://github.com/photopea/photopea/assets/131391069/ace11c40-91be-419c-aa11-8df43476119f)

**Comment by photopea** [comment]
Could you record a video of you opening Photopea (Local storage empty), loading your brushes, and doing other things, to end up with no brushes in a Local Storage?

**Comment by MotziRBX** [comment]
> Could you record a video of you opening Photopea (Local storage empty), loading your brushes, and doing other things, to end up with no brushes in a Local Storage?
![Screenshot 2023-07-20 172208](https://github.com/photopea/photopea/assets/131391069/eabba19d-20bc-48a6-82d7-fa1d6fb2921b)


yep, they've just disappeared again

**Comment by MotziRBX** [comment]
> Could you record a video of you opening Photopea (Local storage empty), loading your brushes, and doing other things, to end up with no brushes in a Local Storage?

The brushes show up when I load them in, but after a couple days, photopea crashes and they all disappear. Can't record me importing them because I have to find all the brushes I had again, and do it all over

**Comment by photopea** [comment]
When I load brushes into Photopea, they stay there for years, or until I delete them.

Do you ever clear the website data of websites? Or clear cookies, etc? Or do you have any antivirus or a system cleaner, which deletes everything that any website could ever save into your computer?

**Comment by photopea** [comment]
My suspicion was, that you are using a browser extension, which clears the website data for you.

**Comment by camoody1** [comment]
> > Could you record a video of you opening Photopea (Local storage empty), loading your brushes, and doing other things, to end up with no brushes in a Local Storage?
> 
> The brushes show up when I load them in, but after a couple days, photopea crashes and they all disappear. Can't record me importing them because I have to find all the brushes I had again, and do it all over

Since you are aware that this is an issue, I would suggest that you start putting all of your Photopea brushes and fonts into one folder that you can find and load easily. If you put them all into one folder, it will literally take you 15 seconds to reload them should this happen to you, again.

**Comment by MotziRBX** [comment]
> When I load brushes into Photopea, they stay there for years, or until I delete them.
> 
> Do you ever clear the website data of websites? Or clear cookies, etc? Or do you have any antivirus or a system cleaner, which deletes everything that any website could ever save into your computer?

No I currently don't have any antivirus cleaners nor do I clear my cache or anything ever. I'll look through my extensions.

**Comment by MotziRBX** [comment]
> > > Could you record a video of you opening Photopea (Local storage empty), loading your brushes, and doing other things, to end up with no brushes in a Local Storage?
> > 
> > 
> > The brushes show up when I load them in, but after a couple days, photopea crashes and they all disappear. Can't record me importing them because I have to find all the brushes I had again, and do it all over
> 
> Since you are aware that this is an issue, I would suggest that you start putting all of your Photopea brushes and fonts into one folder that you can find and load easily. If you put them all into one folder, it will literally take you 15 seconds to reload them should this happen to you, again.

K, I can try this for now

**Comment by camoody1** [comment]
> K, I can try this for now, thank you

I know it's not the best answer, but it's just a way to save yourself from extra pain when it happens again. Think of it as insurance. 🙂

**Comment by MotziRBX** [comment]
> > K, I can try this for now, thank you
> 
> I know it's not the best answer, but it's just a way to save yourself from extra pain when it happens again. Think of it as insurance. 🙂

You’re right! It’s a solution! Thank You very much!

**Comment by photopea** [comment]
I still recommend deleting all extensions, if you are not totally sure you need them. I use my web browser with absolutely no extensions and it is fine :)
