### ISSUE TITLE
Magic Replace - not working - still processing 20 min later

### ISSUE THREAD

**Issue by player869** [photopea/photopea#5856]
Being new to the Magic Replace feature - I have seen multiple tutorials showing how this should work but all I get is a processing bar. Is this feature stable or is it a little hit and miss?

**Comment by photopea** [comment]
We ran out of credits. The thing is that I have to pay $300 from time to time, so that you can use it.

I thought it will be enough to pay $300 once a week, but it is used more than I expected, I have to pay $300 almost every day now.

**Comment by camoody1** [comment]
Time to put a limit on it for non-Premium Accounts. Even if it's just 30 or 60 seconds. Anything to slow down the free users from clicking replace over and over and over.

Build out better options to make full use of Dezgo for Premium users, and limit the free users. That's the only way that makes sense for your business. I've gone through hundreds of large image creations on their website and I've still only used $6 worth of clicks. Let Premium Photopea users use their own Dezgo API keys to leverage a more integrated Photopea/Dezgo experience. **That's** the way forward.

**Comment by MichalSZZ** [comment]
@camoody1 Great idea about time limiting before the next request! Or maybe something like: "Wait 180 sec for the next prompt or watch a 15s video ad" 

And I also think that free use of AI things that @photopea  pays a lot of money should be without limitations only for premium users.
