### ISSUE TITLE
stroke isnt good: whenever im using the stroke, it overlaps in letters like R, A, and d. it overall just looks super bad and just makes text bad

### ISSUE THREAD

**Issue by cap2creates** [photopea/photopea#5857]

**Comment by camoody1** [comment]
Your description sucks. Perhaps include a photo or video next time to show the issue instead of being rude to people trying to help.

**Comment by photopea** [comment]
What stroke are you talking about? Do you mean the Stroke - a layer style? Could you share a screenshot of what you mean by "it overlaps" ?

**Comment by cap2creates** [comment]
![image](https://github.com/photopea/photopea/assets/138265340/28afee72-3090-44f4-8f8b-b5f6086fc105)

**Comment by cap2creates** [comment]
![image](https://github.com/photopea/photopea/assets/138265340/d3ca4dcf-d75c-48b1-9761-76e85185c8ee)

**Comment by camoody1** [comment]
So, these are vector shapes that you're trying to turn into letters? Is that what I'm seeing? If so, you'll need to combine the shapes into one so the app isn't trying to outline both shapes resulting in what you're seeing here.

**Comment by photopea** [comment]
What should I do to see this myself at www.Photopea.com? Why dont you share a full screen, so that we see what kind of layers do you have, etc?

**Comment by cap2creates** [comment]
i just used 100 px text, fredoka font with bold, and 3 px stroke and it did it with R and A

**Comment by cap2creates** [comment]
it also does it with a lowercase d

**Comment by camoody1** [comment]
This is what I get in Photopea when using Fredoka font, bold, 100 px, black and a 3 px stroke of white.
Exactly how should we reproduce the images you included above?

![image](https://github.com/photopea/photopea/assets/73725653/de19f879-433d-46b4-b265-edc5382481cc)

**Comment by cap2creates** [comment]
idk it did it for me with those settings

**Comment by camoody1** [comment]
You've got something else going on here. Can you record a short video of you making it happen? Start with Photopea closed and record everything from opening Photopea to applying the stroke. We're missing something here.

**Comment by camoody1** [comment]
I think I figured it out. 
![image](https://github.com/photopea/photopea/assets/73725653/8e239dd8-1aec-4878-bf56-7fa3b3aa63df)

I get this image if I right-click on the text layer I created and choose to "Convert to Shape". Is that what you did? Because that would make sense why I assumed you were using vectors to create your text.

**Comment by photopea** [comment]
Here is what you have (top) and what you should use instead (bottom)

www.photopea.com/#i_1g1-4E3.psd

You can learn more here: https://www.photopea.com/learn/layer-styles

**Comment by camoody1** [comment]
@photopea How did you achieve the look of the top line? I can't see what you did to get that look.

**Comment by camoody1** [comment]
> Try this: #4523

Wow. I didn't even know that was there. How do people find such things, but not know layer styles? 🤷🏽‍♂️

**Comment by cap2creates** [comment]
i guess i was using a different stroke, and there are 2.
![image](https://github.com/photopea/photopea/assets/138265340/4d7874b3-f021-4c14-a123-e9439fedf8bc)
