### ISSUE TITLE
Script selection checked error

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5859]
Hi!
This variant selection checked correctly in PS, but in Photopea - no...

var selectionExists = false;

try {
    var selection = app.activeDocument.selection.bounds.length;
    selectionExists = true;
}
catch(e) {
    // No selection
}

if (selectionExists) {
    alert("Selection");
}
else {
    alert("No selection");
}

Maybe there is another working way to check the existence of a selection? Thanks

**Comment by Pt-home** [comment]
app.activeDocument.selection.bounds == undefined

**Comment by Pt-home** [comment]
try {
              var bounds = app.activeDocument.selection.bounds;
} catch (e) {
              // 
}

**Comment by photopea** [comment]
did you try  if(app.activeDocument.selection==null) ?

**Comment by Pt-home** [comment]
In fact of the matter;)

To the playground:
if(app.activeDocument.selection==null) {
   alert("NO selection");
} else {
   alert("YES selection");
returns always "YES selection".

That's why the brain had to be perforated with selection.bounds...

It only works reliably like this:
**try {
var bounds = app.activeDocument.selection.bounds;
} catch (e) {
//
}**

Moreover, if replaced by
var bounds = app.activeDocument.selection.bounds.length;
will immediately return an error, ignoring the try

**Comment by photopea** [comment]
I have fixed it, your original code should work well in Photopea now.
