### ISSUE TITLE
select tool color always black when WebGL is Off

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#586]
It's absolutely 0 priority personally for me b/c I have WebGL ON - and it seems default so probably for most users the same?
just reporting it b/c I noticed and for the case developer needs it
With WebGL off selection rectangle is always black, so it's not visible when you select on black color etc.
Chrome on Ubuntu

**Comment by photopea** [comment]
We know about it, it is a feature not a bug. "inverting" colors under the strokes would take too much time, while with WebGL it is instant.
