### ISSUE TITLE
Panels dissapearing

### ISSUE THREAD

**Issue by NugetTacos** [photopea/photopea#5860]
So I was using photopea to make a roblox suit everything was going well till i tapped out of the app to check something and the tools panel dissapeard and the layer... 
and the windows button shows they are open.
![image](https://github.com/photopea/photopea/assets/139771908/ff89ebcf-c172-402d-b8fc-74815b765896)

**Comment by camoody1** [comment]
Click View -> Mode -> Standard and see if that helps.

**Comment by NugetTacos** [comment]
Yes it worked! Thank you very much it helped alot!

**Comment by camoody1** [comment]
Good stuff. Glad I could help. Have a great week!

**Comment by photopea** [comment]
cool :)
