### ISSUE TITLE
Cannot Export Into PNG

### ISSUE THREAD

**Issue by Dre4dfull** [photopea/photopea#5861]
Recently, I've been experiencing some issues with exporting items on Photopea. I use the app version for google chrome. I can only save it as a "PSD". Whenever I try to export as a png, jpeg, etc, it does not work. After I press "save", nothing pops up. This has never happened before. Please help :(

**Comment by Dre4dfull** [comment]
I use a MacBookAir Pro (11.6)
Google Chrome 
<img width="1440" alt="Screen Shot 2023-07-17 at 12 34 28" src="https://github.com/photopea/photopea/assets/102974299/f060325b-1d34-4839-835e-b4105b0bc0af">

**Comment by photopea** [comment]
Could you click the puzzle piece icon at the top right corner and show us how many site-modifying extensions do you use?

**Comment by Dre4dfull** [comment]
<img width="1440" alt="Screen Shot 2023-07-17 at 12 56 56" src="https://github.com/photopea/photopea/assets/102974299/c358c949-a3d7-4e26-8c87-c51555dc8acd">
Here:

**Comment by photopea** [comment]
Could you disable the two extensions, which can change the information on the site, and try to export a PNG again?

**Comment by Dre4dfull** [comment]
Result: IT WORKED. TYSM

**Comment by photopea** [comment]
It is probably just one of them that is causing problems. You can enable one by one to find which one it is.
