### ISSUE TITLE
`Document.suspendHistory()`is not implemented yet!

### ISSUE THREAD

**Issue by ErrorBot1122** [photopea/photopea#5862]
I'm trying to use `Document.suspendHistory()` to put all the actions in my script into 1 undo point, but for some reason running the script still adds a bunch of items to the history! Alter looking at the only result when looking it up here, I found this [comment](https://github.com/photopea/photopea/issues/4475#issuecomment-1175780990) on issue #4475 that briefly mentions it.

Please add this method, as it my script dose a lot of things that affect the history and I want to be able to undo basically all of it if needed.

### Full Script:
```js
const doc = app.activeDocument;

function main() {
  const layer = doc.activeLayer
  
  const layerNameRegex = /^_a_(.*?)(\d+)(,\d+)?$/
  
  const layerNameRegexResult = layerNameRegex.exec(layer.name)

  if (!layerNameRegexResult) {
    alert("INVALID LAYER NAME")
  }
  else {
    const layerFrameIndex = Number(layerNameRegexResult[2])
    
    const endingFrameIndex = Math.floor(Number(prompt("What animation frame should we end at? (Number must be above selected frame index)", layerFrameIndex + 1)))
    
    if (endingFrameIndex <= layerFrameIndex) {
      alert("Invalid response! (Number must be above selected frame index)")
    }
    else {    
      for (let i = endingFrameIndex; i > layerFrameIndex; i--) {
        let newLayer = layer.duplicate()
        
        let newLayerFrameIndex = i
        
        newLayer.name = layer.name.replace(layerNameRegex, "_a_$1" + newLayerFrameIndex + "$3")
        newLayer.visible = false
      }
    }
  }
}

doc.suspendHistory("Mass Duplicate Layer", "main()") // Not implemented :(
```

**Comment by photopea** [comment]
sorry, that would be very hard to implement into Photopea (not related to scripting).

Also, your script does not run in Adobe Photoshop anyway, so we can not look into it (we always compare the results of Photoshop and Photopea after the same script).
