### ISSUE TITLE
[FR] Support for Video Editing without Animation Layers.

### ISSUE THREAD

**Issue by ErrorBot1122** [photopea/photopea#5863]
I would love if you where able to add support for importing videos and editing without having to use **Animation Layers.** (Even thought this might be hard and maybe even impossible to add.)

I want this feature added because editing in Photoshop is almost like a *mini video editor + VFX software* combined and it make it so much easier to add effects and other  VFX to video. Especially for a beginner like me who has 0$ in his bank account.

*Photoshop Doc:* https://helpx.adobe.com/photoshop/using/new-video-features-photoshop-cs6.html
*Video Tutorial:* https://www.youtube.com/watch?v=WHxYHDvEEIg

I do understand if this is not possible to add as IK that most (if not all) of this application is running on the client. Also, you would need make it work on mobile devices witch my not even be feasible.

**Comment by camoody1** [comment]
If you want a free video editor with SfX built in, look up HitFilm Express. I've used that for years for my video editing needs. Photopea really isn't built to be a video editor. It can be useful for GIFs, but not videos over several seconds in length.

**Comment by ErrorBot1122** [comment]
> If you want a free video editor with SfX built in, look up HitFilm Express.

I used to use it but recently its become vary cooperate and almost everything costs money.

**Comment by camoody1** [comment]
> > If you want a free video editor with SfX built in, look up HitFilm Express.
> 
> I used to use it but recently its become vary cooperate and almost everything costs money.

I'm sorry. I didn't realize it had gotten so much worse since their sale to their new parent company. I've heard DaVinci Resolve's free version is really great, too. I haven't used it myself, though.

**Comment by ErrorBot1122** [comment]
> I've heard DaVinci Resolve's free version is really great, too.

I would use DaVinci Resolve resolve if it wasn’t for the fact that it’s known to be hard for beginners.

I just think that adding this feature would make this one of the best web based editor for both images and videos. It would be the simi-natural next step for the software. It would also benefit almost everyone!

_PS: I will probably use DaVinci Resolve in the future when I have the time._

**Comment by ikoshura** [comment]
> I just think that adding this feature would make this one of the best web based editor for both images and videos. It would be the simi-natural next step for the software. It would also benefit almost everyone!

I believe it's not impossible, but it would take a very long time to implement. Photopea took 9 years to reach its current level, so if we want something like VideoPea, AfterPea or VectorPea, we would probably need another developer to start working on it.

By the way, have you tried CapCut for PC? I think it's one of the best PC video editing software available. I've used filmora, Movavi, HitFilm, DaVinci, and Premiere, and while my favorites are Adobe Premiere and DaVinci Resolve, they sometimes run too slowly on my computer due to their heavy resource usage. CapCut, on the other hand, has all the important features you need, and it's lightweight and easy to understand. I highly recommend trying it out!

**Comment by ErrorBot1122** [comment]
I'm actually developing my own plugin to do this! Here's the [comment](https://www.reddit.com/r/photopea/comments/uzaevz/comment/jshyapq/?utm_source=share&utm_medium=web2x&context=3) where I mention it.

I'm going to close this issue even though it still applies. Ill also post updates from the reddit here as well to keep you guys updated.

**Comment by camoody1** [comment]
@ErrorBot1122 Good luck to you, sir! I look forward to seeing what you come up with! 👍🏽

**Comment by ErrorBot1122** [comment]
It’s sir

**Comment by camoody1** [comment]
![image](https://github.com/photopea/photopea/assets/73725653/daea6e98-79e1-4340-8fc3-14ae3f633276)

**Comment by mark325hr** [comment]
Would love to see the ability to import and edit videos using <a href="https://motionalightapk.com/">Animation of Alight Motion</a>. It would make adding effects so much easier, like Photoshop's video editing features, and would be a great addition for beginners. I know it might be hard to implement on mobile, but it would really improve the workflow!
