### ISSUE TITLE
Clone Brush Error

### ISSUE THREAD

**Issue by kasnyi** [photopea/photopea#5865]
Clone Brush , K Keys not working and not cloning anythings

**Comment by photopea** [comment]
What should I do to see it myself? Could you describe it with words or record a video of what you do (starting by opening www.Photopea.com) ?

**Comment by photopea** [comment]
Are you sure you know how to use it? Did you read our manual, or a book about Adobe Photoshop? https://www.photopea.com/learn/bt-basic

**Comment by kasnyi** [comment]
Hi my apologies, I cleared all old cache from my desktop and Mac and it worked now thank you for the trouble appreciate it
