### ISSUE TITLE
Login API

### ISSUE THREAD

**Issue by shenjo** [photopea/photopea#5866]
I have a scenario where I purchased a Distributor account and then embedded Photopea using an iframe. I want to automatically log in to this account after embedding it. However, I couldn't find any relevant API to accomplish this.

**Comment by shenjo** [comment]
My apologies. After testing, I discovered that by adding the domain to the whitelist, I was able to embed Photopea without advertisements and account buttons and so on . I initially thought that logging in was necessary to enjoy these benefits.

**Comment by shenjo** [comment]
thx anyway, will close this issue.

**Comment by photopea** [comment]
no problem :)

simply put, if anyone pays for a Distributor account, they can add any domain to the list. If your domain is in our list, it will run Photopea without ads :)
