### ISSUE TITLE
cannot move layers

### ISSUE THREAD

**Issue by tay111111** [photopea/photopea#5867]
hiya, ive been trying to move the layers around and it simply won't let me.

**Comment by photopea** [comment]
Could you show us a screenshot of what is happening? Are you talking about www.Photopea.com ?

**Comment by camoody1** [comment]
> hiya, ive been trying to move the layers around and it simply won't let me.

Moving layers definitely works, so you're either just missing something simple that we can help you with or your browser has some odd extension giving you issues. Drop us a short video showing what you're doing and the problem you're having so we can assist.

**Comment by Itayed** [comment]
> hiya, ive been trying to move the layers around and it simply won't let me.
its not working for me to

**Comment by camoody1** [comment]
@Itayed How To questions like this should be asked in the Photopea subreddit. This GitHub page is for actual application bugs and feature requests.

**Comment by photopea** [comment]
I have to close it because the person is not responding.
