### ISSUE TITLE
leaving photopea with Alt+Tab makes select tool stuck in subtraction mode

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#587]
steps to reproduce:
- switch to select tool
- leave photopea browser window with Alt+Tab
- return to photopea

result:
the select is stuck in subtraction mode, without you holding alt

i guess can be fixed by resetting on window blur event

This is small one but really crazy (: when you don't know what's going on, it just looks like select tools doesn't work sometimes (b/c, when you select something in sub mode and selection doesn't overlap with existing one, it's completely ignored). I've been wanting to report it for a while, but hesitated b/c  couldn't understand it

**Comment by photopea** [comment]
The problem was, that the keyboard state was reset after "blur", but icons in the top bar were not.

I simplified the mechanism a bit. The combining operation is the one in the top bar, unless you press Shift or Alt - then it is overridden (but the icon in the top bar does not change).

**Comment by ewnjtgouierg** [comment]
Thanks a lot for your hard work

p.s. you forgot to remove "Blur" debugging message? (:

**Comment by photopea** [comment]
ok thanks :D
