### ISSUE TITLE
Incorrect operation Brightness / Contrast in the mode "Use Legacy"

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5870]
Hi!
I have next file:
[UseLegasy.zip](https://github.com/photopea/photopea/files/12093565/UseLegasy.zip)

In Photoshop this file correctly raises the contrast, as expected:
![UseLegasyPSResult](https://github.com/photopea/photopea/assets/29394245/7d391bfa-9932-4301-b1ad-ea922128ec34)
But in Photopea I don't see the expected result, neither in manual mode nor through script:
![UseLegasyPhotopeaResult](https://github.com/photopea/photopea/assets/29394245/daa0a139-c7f0-4f04-9e33-039de7a9d384)
Thanks!

**Comment by photopea** [comment]
I tried to apply this adjustment on your file in Adobe Photoshop, and then, I added the Adjustment layer (with the same parameters) in Adobe Photoshop. Each one gives different results.

Do you think it is a bug in Adobe Photoshop?

**Comment by Pt-home** [comment]
I don’t know the answer to your question, because I don’t work much with adjustment layers. But the example that I sent you - I have been using this method for 15 years, no less. Any beginner example "How to make rain" or "How to make a starry sky from scratch" always refers to this method. Here I guarantee you 100% that starting from PS3.0, when they didn’t even think about adjustment layers, it worked as shown in my picture

**Comment by photopea** [comment]
I am not sure about this. I think it is a bug in the latest version of Adobe Photoshop.

Did you try to add a tiny black pixel into your image? Do you think it should change the way this adjustment works?

**Comment by Pt-home** [comment]
https://www.photoshopessentials.com/photo-editing/brightness-contrast/

**Comment by Pt-home** [comment]
Quote from Adobe:
"n normal mode, Brightness/Contrast applies proportionate (nonlinear) adjustments to the image layer, as with Levels and Curves adjustments. When Use Legacy is selected, Brightness/Contrast simply shifts all pixel values higher or lower when adjusting brightness. Since this can cause clipping or loss of image detail in highlight or shadow areas, using Brightness/Contrast in Legacy mode is not recommended for photographic images (but can be useful for editing masks or scientific imagery).
Note: Use Legacy is automatically selected when editing Brightness/Contrast adjustment layers created with previous versions of Photoshop."

Accordingly, for my layer mask, I expect the maximum range of transformation from white to black in the Legacy mode.
And I have a version of PS 20.0, that is, not a new one

**Comment by photopea** [comment]
The Brightness/Contrast in Photopea works 100% exactly as in Adobe Photoshop for Adjustment layers (in all modes, all configurations).

I think it is a bug in the latest Photoshop, when the regular adjustment works differently than the Adjustment layer. I think the regular adjustment should work identically to the Adjustment Layer.

@MichalSZZ what do you think?

**Comment by Pt-home** [comment]
In the same way, it can be considered a bug in Photoshop just not switching to Legacy mode in adjustment layers :) Since their functionality was coded when the regular mode had long existed :)

**Comment by MichalSZZ** [comment]
> 
> @MichalSZZ what do you think?

I am not sure but I think that "legacy" mode should work differently and the regular Adjustments from the menu Image -> Adjustments from Adobe Photoshop do it properly. I don't know why adjustments layer results are the same as these without "legacy" mode.

In my opinion - that is a bug in Adobe PS. But I could be wrong.

**Comment by Pt-home** [comment]
Prior to CS3 Brightness/Contrast applies a linear transformation to the transfer curve: adjusting brightness alters the polynomial constant, sliding the curve to one side; while adjusting contrast alters the polynomial scalar, expanding or compressing the curve. In later versions, the core behavior was changed to a non-linear transformation, while **this linear behavior is retained as Legacy mode**

Therefore, I raised the question itself, otherwise what would be the point of the very existence of this checkbox in the interface? Through the top menu of Photoshop, I can get both conversion options, just in theory. By the way, perhaps they ignore it (but for some reason they keep the unity of the interface?) in adjustment layers because the "old mode" itself was available before they were introduced.

**Comment by Pt-home** [comment]
Moreover, it all started for me because of the script:

var idBrgC = charIDToTypeID( "BrgC" );
              var descBrgC = new ActionDescriptor();
              var idBrgh = charIDToTypeID( "Brgh" );
              descBrgC.putInteger( idBrgh, 0 );
              var idCntr = charIDToTypeID( "Cntr" );
              descBrgC.putInteger( idCntr, 95 );
              var iduseLegacy = stringIDToTypeID( "useLegacy" );
              descBrgC.putBoolean( iduseLegacy, true );
executeAction( idBrgC, descBrgC, DialogModes.NO );

Its PS result:
![image](https://github.com/photopea/photopea/assets/29394245/6592aba2-d076-4f84-9e0c-b40af004fc8c)
Its Photopea result:
![image](https://github.com/photopea/photopea/assets/29394245/25b15893-9f52-4915-b849-19e17f285e12)

**Comment by Pt-home** [comment]
And the fourth option works differently than the first three in PS 20.0 too

**Comment by Pt-home** [comment]
I was so stuck in this contrast that I did not notice another feature.
If Legacy is turned off in my PS 20.0, then both through the menu and through the layer - the brightness range is from -150 to 150, if turned off - then from -100 to 100 ...

And in software it is always from -150 to 150, if anything

**Comment by photopea** [comment]
I think the Adjustments should work the same in Adjustment Layers, as in Smart Filters.

They do in Photopea, but they dont work the same in Photoshop. So I think it is a bug in Photoshop.

**Comment by Pt-home** [comment]
I further considered this issue and consulted. And my opinion remains the same - the correct legacy mode for adjusting the contrast in Photoshop works in the menu, and not in the adjustment layer. And since the use of legacy through an adjustment layer is a rare exception, they simply do not pay attention to it. But I agree that the world will not turn over if everything remains as it is)
