### ISSUE TITLE
not responding when click new project from menu

### ISSUE THREAD

**Issue by kadko** [photopea/photopea#5871]
not responding when click new project from menu,
"new project" and "new project with ready templates" options is better i think,

**Comment by photopea** [comment]
Since millions of people are using Photopea and nobody reported this problem, I am pretty sure something is wrong with your device / browser.

Could oyu try this first: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/ , let me know if it helped.

**Comment by kadko** [comment]
I haven't encountered this problem before since I am using about 2 years, happened many times in 2 days. I will check it out link you provided thanks

**Comment by photopea** [comment]
I have to close it, as there was no response.
