### ISSUE TITLE
How do I switch the account used to login?

### ISSUE THREAD

**Issue by HawkZhangS** [photopea/photopea#5874]
It seems I have no choice to choose which Microsoft account to login, how could I do that? I'd like to use a new account rather than the account of current Edge browser is using in the profile.

From the login window, I have no choice to switch to another account:
![1 (1)](https://github.com/photopea/photopea/assets/128666875/00b3edd8-c903-4085-8d15-b45c90f13207)

**Comment by camoody1** [comment]
I also use the Microsoft Edge browser. If I log out of my Microsoft account within Edge and then try to log into Photopea using my Microsoft Account, it actually prompts me to select an account to login with. Maybe you could try that and see if it helps.

**Comment by HawkZhangS** [comment]
Big thanks, it works perfectly.

**Comment by camoody1** [comment]
> Big thanks, it works perfectly.

Excellent. Glad I could help. Have a great day.

**Comment by HawkZhangS** [comment]
Yeah, you too!
