### ISSUE TITLE
I can't drag 100+ asl onto photopea

### ISSUE THREAD

**Issue by photoeditorlover** [photopea/photopea#5877]
the more i drag down asl down on photopea i got an error stating I can no longer drag multiple asl files onto the photopea. So, it only capable to upto 5 asl files. You had to open a new photopea to add another asl files. 
 Also ASL files is used for coloring text.

**Comment by photopea** [comment]
What should I do to see this problem myself? Are you loading 100 ASL files into Photopea? Could you share them with me, so that I try it myself?

**Comment by photopea** [comment]
I have to close it, as there was no response.
