### ISSUE TITLE
Sidebar has disappeared off the right of the screen

### ISSUE THREAD

**Issue by botherer** [photopea/photopea#5878]
My sidebar has disappeared off the right of the screen, and I cannot get it to appear. When I stretch the Chrome window wider, it briefly appears, then pings away again. Making the image smaller in the work area doesn't change anything.

![pea1](https://github.com/photopea/photopea/assets/3943684/86124773-c2ae-4740-b2dd-571a6a026baf)

Help!

**Comment by photopea** [comment]
This is done by one of your browser extensions. Do you use "ublock origin"? Ask the creators of your extension why do they do this.

**Comment by botherer** [comment]
Thank you!

**Comment by photopea** [comment]
ok, great!
