### ISSUE TITLE
photopea crashes every time i go onto website 

### ISSUE THREAD

**Issue by TheNookieBearYT** [photopea/photopea#5879]
So I had this problem start a few months ago, every time i go to photopea.com it tries to automatically load about 7 previous projects without clicking on anything, I have looked into this to try and solve the problem with no luck, lots of people say it's to do with extensions, So I have removed all of my extensions and still have the same issue, I have deleted my cache, I have tried letting it load all the projects and then closing them one by one, but the second i re visit the website it doe's the same thing and tries to load all my previous projects again, I can only run in a private window but then i lose all my fonts/styles etc i created, any fix for this?? Thanks 
![image](https://github.com/photopea/photopea/assets/139913422/5fcd7183-946a-4128-946d-5de909dd70c8)

**Comment by photopea** [comment]
Photopea always works perfectly when you dont use any browser extensions. One if your extensions is breaking it.

Try this: https://www.photopea.com/tuts/photopea-opens-up-old-files/

**Comment by TheNookieBearYT** [comment]
I am not using any browser extensions, i deleted them all, I got it to work by deleting cookies but now it's deleted all my fonts/styles long with it rip, Thanks for the help anyways.

**Comment by photopea** [comment]
That article describes it all. Your extensions did not allow Photopea function properly (truly close documents).

**Comment by photopea** [comment]
I have to close it, as there was no response.
