### ISSUE TITLE
I need to export resume as a readable PDF, but the text changes if I don't rasterize or vectorize. 

### ISSUE THREAD

**Issue by skiimusic** [photopea/photopea#5882]
So I have 2 resumes. They obviously need to be DOC or PDF so I can submit to job applications. 
I downloaded a template and have designed them for a while. I like how they turned out but for some reason, the only way I can have it look how it looks on Photopea is if I rasterize or vectorize the text. If I don't do this then the text gets messed up. 
I can't rasterize the text because I need it to be easily recognized by resume reading OCR software. Is there a solution this?

**Comment by photopea** [comment]
Sorry, Photopea can not create PDF files with custom fonts at the moment :( 

Maybe you can do a trick. Export your resume as a PNG, insert it into your resume, and set the opacity of text layers to zero. Export a PDF without vectorizing. The viewer will see the PNG (inside a PDF), but will be able to select the invisible text.

**Comment by skiimusic** [comment]
Thats actually genius. 
Thank you!
