### ISSUE TITLE
Problem with handling small selections

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5884]
Hi! This mysterious moment just blew my mind :). And he froze my almost finished project :(

The bottom line is that my scripts break down at the stages when "smooth" or "contract" with tiny selections work like Deselect.
After that, having managed to sometimes perform a couple of actions, they die without any error messages.

I came up with an example that will show the problem right in the Photopea Sandbox:
**console.clear();

var selectionBounds = [
            [0, 0], [0, 1], [1, 1], [1, 0]
          ];
app.activeDocument.selection.select(selectionBounds);

console.log("Step 1", app.activeDocument.selection.bounds, "We create selection...");

app.activeDocument.selection.smooth(10);

console.log("Step 2", app.activeDocument.selection.bounds, "Smooth now must work as Deselect...");

app.activeDocument.activeLayer.applyAverage();

// PROBLEM!!!
if (app.activeDocument.selection.bounds == undefined) {
   console.log("Step 3", app.activeDocument.selection.bounds, "Unattainable dream true...");
} else {
   console.log("Step 3", app.activeDocument.selection.bounds, "Unattainable dream false...");        
}**

Note: Changing smooth to contract will give the same sad effect for me...
I really hope for help...

**Comment by photopea** [comment]
I just tired your script in Adobe Photoshop and smooth / contract removes a selection, too.

Each pixel of a selection can have a value from 0 (not selected) to 255 (fully selected).

If you smooth (blur / feather) a single pixel of 255 (others are 0), it will spread to a large area, the maximum value will drop under 1.

If you contract a single pixel by more than 0 pixel, it will disappear, too. 

A selection must always have at least one pixel that is bigger than 0. If you set all pixels of a selection to 0, that is deselecting.

**Comment by Pt-home** [comment]
It is absolutely NORMAL that a small selection, when processed with a smooth or contract, becomes zero and the Deselect is executed.
I asked why app.activeDocument.selection.bounds not generate error in console on in if...
My apologies
