### ISSUE TITLE
How to get rid of backup files on photopea

### ISSUE THREAD

**Issue by Wraith2394** [photopea/photopea#5885]
Hey I wish to know how do I get rid of backup files on my photopea cause whenever I open up the app on my laptop it automatically uploads three files that I don’t have saved nor do I want them anymore and it keeps freezing up my laptop. Is there a way I can get rid of them completely?

**Comment by photopea** [comment]
try this: https://www.photopea.com/tuts/photopea-opens-up-old-files/

**Comment by Wraith2394** [comment]
Hey thanks for the tip on how to get rid of backup files on Photopea, but now I want to know where can I find browser extensions on Photopea if that's possible.

**Comment by Wraith2394** [comment]
Well I just want to know if I can get rid of backup files on my Photopea app if that’s possible.

**Comment by camoody1** [comment]
> Well I just want to know if I can get rid of backup files on my Photopea app if that’s possible.

I apologize, but I don't understand what you're asking here. What "backup files" are on your Photopea app? Ivan's link above solved your initial problem, correct?

**Comment by Wraith2394** [comment]
The ones that automatically keep popping up whenever I open up Photopea are what I’m trying to get rid of.

**Comment by camoody1** [comment]
I thought the link that Ivan posted resolved your issue. You actually thanked him in a follow-up message and then asked a different question. So, I guess I'm just lost. 🤷🏽‍♂️

**Comment by photopea** [comment]
Please, read my article. It clearly says, that you can find your extensions at "about://extensions"

You can learn about what is a browser extension here: https://en.wikipedia.org/wiki/Browser_extension

If you are the only user of your device, it was you who installed these extensions, so you should be aware of them.

**Comment by camoody1** [comment]
@Wraith2394 Are you asking how to find the browser extensions from the installed Photopea web app? You can find them under the "..." at the top right of your webapp window.

![image](https://github.com/photopea/photopea/assets/73725653/0b4d9e55-3180-4af1-a381-fba1b8eef88f)

**Comment by Wraith2394** [comment]
Yes and thank you! I’ll let you know if it works.

**Comment by Wraith2394** [comment]
Ok I think I figured out the extension part on photopea but what I want to know is how to get rid of the backup files that keep automatically pop up when I open up the appSent from my iPhoneOn Jul 24, 2023, at 6:33 PM, DarthBuckeye ***@***.***> wrote:﻿
@Wraith2394 Are you asking how to find the browser extensions from the installed Photopea web app? You can find them under the "..." at the top right of your webapp window.

**Comment by photopea** [comment]
If you close Photopea with some documents opened, and you open it again, there should no "backup files".

Are you sure Photopea is opening backup files, while you are using it with no extensions?

Could you send us a video of this happening (dont forget to record the list of your extensions, so that we are sure that you have disabled them).

**Comment by Wraith2394** [comment]
Ok I tried to close Photopea with some documents opened and when I opened
it again there seemed to be no "backup files" popping up but just today
when I first opened the app it automatically opened the "backup files".
Also I do have Photopea with some extensions. The two are Trend Micro
Toolbar and TestGen Plug In.

What else should I do in order to completely get rid of backup files?

**Comment by photopea** [comment]
Could you ask your browser extensions to not interfere with Photopea?

Or try to disable all your extensions for a week, to see if Photopea still keeps any "backup files".

Again, a browser extension is more powerful than a website. We can not do anything with it. Just like we can not help you if you dont have electricity in your device.

**Comment by photopea** [comment]
I have to close it, as there was no response.
