### ISSUE TITLE
whenever i try to type with text, it doesnt work.

### ISSUE THREAD

**Issue by henryelevatoroperator** [photopea/photopea#5886]
i click on the text option, and when i start typing, it just selects other tools.

**Comment by camoody1** [comment]
After you click on the text tool, you need to click somewhere on your canvas before you start typing. If you don't on your canvas first, you're typing will just act as if you're selecting new tool shortcuts.

**Comment by photopea** [comment]
Could you share a screenshot of what it looks like when you start typing?

**Comment by photopea** [comment]
I have to close it, as there was no response.
