### ISSUE TITLE
Saving images or Gifs

### ISSUE THREAD

**Issue by anniebooboos** [photopea/photopea#5890]
I'm not sure if this issue is just with me, but photopea won't let me save gifs or images on my laptop, it lets me export them as gifs or jpgs, but it won't save them. I tried on my other laptop and same issue happened there.

**Comment by photopea** [comment]
What do you mean by "it lets me export them as gifs or jpgs, but it won't save them"?

Could you try this first? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by anniebooboos** [comment]
Yes, like there is that option for the export and it let me do it, but it won't save them and they won't appear at the "downloads" file of my laptops. and thank you, i will try that !

**Comment by photopea** [comment]
Do other formats work, like JPG or PNG? Only GIF does not work?

**Comment by photopea** [comment]
I have to close it, as there was no response.
