### ISSUE TITLE
raster mask isn't working 

### ISSUE THREAD

**Issue by gojowckd** [photopea/photopea#5892]

**Comment by photopea** [comment]
Hi, what should I do to see it happen myself? Everything works fine for me.

**Comment by gojowckd** [comment]
no idea but for some reason my raster mask isn't showing the erased lines when i erase something on gifs? it works without a raster mask on photos but not gifs for, for some reason

**Comment by camoody1** [comment]
> no idea but for some reason my raster mask isn't showing the erased lines when i erase something on gifs? it works without a raster mask on photos but not gifs for, for some reason.

Masks have always worked for me on GIFs. You might be doing something a bit wrong. Could you share a link to your PSD here so we can see exactly what you've done?

**Comment by gojowckd** [comment]
www.photopea.com/#i55q3bLKj.psd here it is :)

**Comment by photopea** [comment]
Your mask is completely white. You need to paint with black to hide stuff.

Read this to learn how masks work: https://www.photopea.com/learn/masks

**Comment by gojowckd** [comment]
i figured it out! thank you for your help :)

**Comment by camoody1** [comment]
I was just gonna say... it seems to work fine for me. 🙂
![red gif](https://github.com/photopea/photopea/assets/73725653/395ae00c-887e-4d14-8774-4eae7d54b10a)
