### ISSUE TITLE
The eraser not working?

### ISSUE THREAD

**Issue by Sephlur** [photopea/photopea#5893]
Have there been any updates these days?

Since the eraser instead of erasing, it just "erases the image" and I can't find any other function that erases accurately like the eraser did before.
![image](https://github.com/photopea/photopea/assets/140516787/46ae2d7e-55a0-4555-a314-642795210ff7)

**Comment by MichalSZZ** [comment]
You have the opacity set to something less than 100% in the top bar.

**Comment by Sephlur** [comment]
no, the opacity is at %100 
![image](https://github.com/photopea/photopea/assets/140516787/527b92d3-c6bb-4d11-b437-1282e194a7b3)

**Comment by photopea** [comment]
cool

**Comment by Sephlur** [comment]
![afsdgasdfg](https://github.com/photopea/photopea/assets/140516787/1113f9bb-80c3-4612-9ff1-a82d8df10618)
I share the finished work Thanks!
