### ISSUE TITLE
Crop tool crops entire project when "Current Layer" option is selected

### ISSUE THREAD

**Issue by DurrtySteve** [photopea/photopea#5894]
I can't seem to crop only a selected layer, even when I choose "current layer" from the options menu within the Crop Tool.

See attached video.

https://github.com/photopea/photopea/assets/60979161/e1d345b6-a024-47ac-a6e6-35e93016267b

**Comment by camoody1** [comment]
You don't crop layers. You crop an entire canvas to a smaller size.
https://www.photopea.com/learn/image-size

**Comment by photopea** [comment]
Yeah, you really need to learn how to use Photopea or Photoshop, before actually using it. You can buy a book about Adobe Photoshop.
