### ISSUE TITLE
 i tried to size my image and it didnt let to use the corners to get the picture bigger

### ISSUE THREAD

**Issue by Itayed** [photopea/photopea#5895]
i tried to size my image and it didnt let to use the corners to get the picture bigger

**Comment by camoody1** [comment]
You're probably doing something wrong. It definitely works. Keep trying.

Also, when reporting a problem, it's helpful to include what tool you're using and exactly what you're doing and trying to do.

**Comment by photopea** [comment]
Please, describe, what should I do to see the problem myself. Or record a video of what you are doing.

**Comment by photopea** [comment]
I have to close it, as there was no response.
