### ISSUE TITLE
Fill Function is  not working

### ISSUE THREAD

**Issue by AnnaTK2301** [photopea/photopea#5896]
Fill Function is  not working
tried a lot of times and it still doesn't work

**Comment by camoody1** [comment]
The Fill function is definitely working. If it weren't, we would be seeing dozens of similar tickets to yours. It sounds like you might be doing something accidentally wrong. Could you record a short video for us showing exactly what you're doing when this isn't working for you? It would be far easier for us to help you that way.

**Comment by AnnaTK2301** [comment]
Thank you for quick response!
I tried a lot of times and the option shift f5 wasn’t active . I found the
mistake in the layer , sorry , everything is working perfectly .

**Comment by camoody1** [comment]
@AnnaTK2301 Glad to hear you figured it out. Have a great rest of your week!

**Comment by AnnaTK2301** [comment]
Thanks, you too!
