### ISSUE TITLE
the text function does not work

### ISSUE THREAD

**Issue by Motili12** [photopea/photopea#5897]
a sign with the inscription (Loading) constantly appears and the text is not visible

**Comment by camoody1** [comment]
Are you trying to select a new Font before this happens? Switching to the text tool doesn't result in a Loading screen in Photopea. There's something else you're doing that you're forgetting to tell us. Could you maybe record a short video showing us exactly what you're doing as it happens?

**Comment by photopea** [comment]
Did you try it in the Incongito mode? Does it work there?

You can learn more here: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by Motili12** [comment]
i just select the text function and when i click on the screen to start work nothing happens,
although all other functions work well
and yes i tried incognito

**Comment by Motili12** [comment]
I forgot to say that I have this error on both laptops

**Comment by camoody1** [comment]
@Motili12 Are you signing into a Photopea account when you use the application or just using it without signing in? If you are signing in, do you have Fonts that load when you first open Photopea? Could you please record a short video for us to see what happens from the very beginning of opening Photopea, creating a new project and trying to type some text? It could be that you're trying to load a font that is bad.

Also, weird question, but do you live in Turkey?

**Comment by Motili12** [comment]
No, I'm from Moldova
and i use photopea online
unfortunately I can't make a video and because of the weaknesses of the laptop

**Comment by Motili12** [comment]
sorry for bothering me, i already figured it out

**Comment by camoody1** [comment]
Oh? You got it working, then? What was the problem?

**Comment by photopea** [comment]
I am glad it worked. It was probably some browser extension, which blocked the loading of our fonts. Or the Brave browser, which is weird in too many ways. It would be nice if the person told us what the problem was.
