### ISSUE TITLE
Shapes are closed

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5899]
Someone can explain me why those 2 moons in my design are closed when exporting to PDF?

As far as i can tell, they change their mode from substract to exclude.

![image](https://github.com/photopea/photopea/assets/11801254/4d55e565-9ec9-4c04-94b7-faa53b1f4d13)

The PSD:
[Fondo estrellado.zip](https://github.com/photopea/photopea/files/12178594/Fondo.estrellado.zip)

**Comment by camoody1** [comment]
What do you mean by "closed"? When I export what you linked to PDF, the two moons look that same as when in Photopea. What are you saying is wrong? Maybe I'm just missing something obvious.

**Comment by TheRadicalDreamer** [comment]
Mine  exports like this:
![image](https://github.com/photopea/photopea/assets/11801254/ff332cd4-7b45-49da-981b-eca83a5fac4c)

**Comment by TheRadicalDreamer** [comment]
![image](https://github.com/photopea/photopea/assets/11801254/49e48fdb-4ba0-4d09-a389-29798f8aa1df)

**Comment by camoody1** [comment]
Oh yes, I see now. Yeah, it looks like that on mine, as well. What if you select both of the paths that make up each moon and Merge them into one shape? I bet that would work.

**Comment by TheRadicalDreamer** [comment]
it only one shape

But still, it differs from what i see in photopea

**Comment by TheRadicalDreamer** [comment]
it only one shape

But still, it differs from what i see in photopea

**Comment by camoody1** [comment]
But to answer your question, you're right... it's acting as an Exclude instead of a Subtract when exported. Definitely looks like a bug.

**Comment by camoody1** [comment]
It seems to work correctly when exported as a PNG, but not as a PDF.

**Comment by photopea** [comment]
So there are two states of Photopea
1) Subtract / Intersect / Union work correctly, but exporting complex shapes can take 5 seconds or more
2) Boolean operators dont work, but exporting a PDF takes 0.05 seconds.

Photopea has been in a state 1 for many years. But about a month ago, you complained about the speed, so I decided to switch to 2.

Try to avoid two vector shapes intersecting each other (i.e. draw a moon in a different way, or use our "Merge" feature).

As always, all this will be fixed in Vectorpea (which has no boolean opertors)! :D

**Comment by TheRadicalDreamer** [comment]
Thanks for the explanation.

Yes i did try to take the moons out of the whole shape and did work, and i was wondering why. No i know.

Thank you very much

**Comment by TheRadicalDreamer** [comment]
Can we have a notification / toast that alerts you that your shapes has too many points that you might get a different result, so i have to check it?

I am asking this because i have had this issue a couple of times and i haven't realized it after a long time, or when a revised them. And if photopea gives a warning at least i can correct it or double check
