### ISSUE TITLE
Text area

### ISSUE THREAD

**Issue by tomasnosek** [photopea/photopea#59]
Photoshop supports 2 text structures - line text without any space limitation and second one, the paragraph text which is limited by some defined space, f.e. 800px width, 400px height with hidden overflow. I'm not sure if you have it in Photopea, but its the basic text rule i mean. I didn't find it and i'm very upset to make lines by myself (pressing enter :)).

**Comment by photopea** [comment]
Yes, PP should support both text structures. To create the first one, just click anywhere with a Type tool. To create a "rectangular" structure, you should draw a rectangle with a text tool (press the mouse at one point - top left, and release it at the another - bottom right).

**Comment by tomasnosek** [comment]
Yep, i tried it of course, but text didn't fit to square i defined it for and overflowed him.

**Comment by tomasnosek** [comment]
Man, sry, i tried it once again and it works. I really don't know what was the problem, but maybe on my site...

**Comment by photopea** [comment]
There is probably a bug, which is hard to reproduce ... let me know when you find out, what exactly happens before this bug.
