### ISSUE TITLE
Better quality for "fit the area view" of large images

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#590]
Right now when zoom out(shrink) view on large images they are quite jagged compared to the default preview in mac which is quite smooth

This is not very visually appealing

**Comment by photopea** [comment]
You can have a better quality, when you disable WebGL (More - Use WebGL). This is supposed to be fixed with this issue: https://github.com/photopea/photopea/issues/447

**Comment by hgs54371** [comment]
When disable WebGL, the transform control is rendered as near black, when viewing against black theme background on a larger than canvas image, they are nearly invisible
