### ISSUE TITLE
Problem with typing

### ISSUE THREAD

**Issue by 1simonOK88** [photopea/photopea#5900]
I tried the typing tool in Photopea and it´s still typing: __  
instead of letters. I am using the app.  Please help.

**Comment by camoody1** [comment]
This sounds like a font issue. Have you tried other fonts? Does this happen with all fonts?

Could you please open Photopea in "In Cognito Mode" at www.photopea.com and try text there?

Also, what browser are you using and on what type of device?

**Comment by 1simonOK88** [comment]
Hi, I am using Google Chrome. And yes, it happens with all fonts

**Comment by 1simonOK88** [comment]
I also tried text on www.photopea.com and it worked.

**Comment by photopea** [comment]
What is the "app"? Where did you get it?

**Comment by 1simonOK88** [comment]
Did I do something wrong? Sorry for asking, I just don´t want to get into trouble

**Comment by 1simonOK88** [comment]
![photopea](https://github.com/photopea/photopea/assets/139695028/218ccfc2-fdbb-43e3-ab8b-109075b90877)
screenshot from my desktop

**Comment by camoody1** [comment]
@1simonOK88 You didn't do anything "wrong", but there is no official app version of Photopea. There is no where "get the app" from. Photopea is exclusively a web browser product. If someone is having you download something for Photopea, they're scamming you. Don't use that app.

**Comment by camoody1** [comment]
@1 You CAN "install" web apps from the settings menu of Chrome and Microsoft Edge. This will put a shortcut on your Windows taskbar that opens just Photopea in its own browser window when you click it. But that's still the same web based thing. It's not some separate app.

**Comment by 1simonOK88** [comment]
OOH my fault, sorry I didn´t know, it´s shortcut. Sorry.  But there is still one problem: with typing. I tried lot of fonts and every font just typed: __

**Comment by camoody1** [comment]
> I also tried text on [www.photopea.com](http://www.photopea.com) and it worked. But just on website. I am using the app, I said before. Could you help me please?

What about this? You said it worked on the website. That's where you should be using Photopea and not the app you got from firehorse.

**Comment by 1simonOK88** [comment]
It worked but when I selected another font, it stoped. so i switched to the original font (i mean the one that worked before) and it was typing ___ again

**Comment by camoody1** [comment]
Try following these steps;
https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
We never made any app. Photopea can be used only at www.Photopea.com in a web browser. We can not help you with random things you download from the internet. You should ask the person who made your app about it. We can help you only with Photopea.

**Comment by 1simonOK88** [comment]
I said I need help with typing, thats all. I don´t have a problem with any app. @camoody1 explained, i just have shortcut. I just Thought its app.

**Comment by 1simonOK88** [comment]
@camoody1 thanks for the steps :)
