### ISSUE TITLE
Feature - Combine shapes

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5901]
Here is a video showing that you can combine shapes into one, with a manu i don't see in Photopea
https://www.youtube.com/watch?v=seCm_xgKXF8

![image](https://github.com/photopea/photopea/assets/11801254/d20de27c-9742-480e-8dea-c9d28c6771a9)

Is it possible to do this in Photopea, if not, i would kindly ask if this is possible to implement.

Thanks :D

**Comment by MichalSZZ** [comment]
Choose two paths on the same layer (with path select tool with Shift) and use Merge. There is an option like in Photoshop.

**Comment by TheRadicalDreamer** [comment]
I didn't know that a Merge option appears when I select more than one
shape!

Thank you Michal!

**Comment by photopea** [comment]
The merge option is always there for every vector shape layer, it is not related to selecting any specific paths.
