### ISSUE TITLE
when i try to use the "Rectangle select" the box moves to a different spot where my mouse isnt 

### ISSUE THREAD

**Issue by Dawny12** [photopea/photopea#5903]

**Comment by camoody1** [comment]
Try these steps:

https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by Dawny12** [comment]
> Try these steps:
> 
> https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

It works in incognito, Thank you

**Comment by camoody1** [comment]
@Dawny12 If it works in Incognito, that means you've got a browser extension that's causing you issues when you're NOT in incognito. I suggest disabling all of your extensions and then re-enable them one at a time until you find out which one is the problem. Good luck to you!

**Comment by photopea** [comment]
Go to Edit - Preferences, set the Mouse Offset to zero.
