### ISSUE TITLE
Add support changable app/actions keyboard shortcuts

### ISSUE THREAD

**Issue by Tarik366** [photopea/photopea#5904]
I used actions with only keyboard shortcuts and now I press accidentally F2 or F11 keys :sweat_smile:. Please bring this feature

**Comment by photopea** [comment]
What exactly are you asking? I do not understand.

**Comment by Tarik366** [comment]
I was ask you can could do something similar to replaceable keyboard shortcuts like in Photoshop?

**Comment by photopea** [comment]
Sorry, we want the functionality of Photopea to be the same for everyone. If we let every user to redefine shortcuts, it could get quite confusing. Also, it is not clear which shortcut is not working for you.
