### ISSUE TITLE
Exportar Imagen a Formato AVIF

### ISSUE THREAD

**Issue by WintorABC28** [photopea/photopea#5905]
Buenos días, photopea.com es una plataforma que llevo utilizando desde hace varios meses y me gusta mucho, pero si me gustaría saber si pueden habilitar la opción de exportar en Formato AVIF. Muchas gracias

**Comment by photopea** [comment]
I think a good AVIF encoder could be pretty large. @hxim are there any AVIF encoders, that could be compiled to WASM? Would you like to make a plugin for it? :)

**Comment by photopea** [comment]
I have to close it, as the AVIF format is not that popular yet.
