### ISSUE TITLE
Action and Storage Path

### ISSUE THREAD

**Issue by jodice** [photopea/photopea#5906]
Hi I found two issues in using it. 
Firstly, the action feature cannot record the action of inserting an image. 
Secondly, I would like to ask if there will be a function to choose the storage path for images in the future.
Thanks!

**Comment by jodice** [comment]
The action feature cannot record the action of texting too.

**Comment by photopea** [comment]
Sadly, Photopea is a website. A website can not open any file from you computer without some kind of a "window" in between.

What do you mean by "choose the storage path"? The saving mechanism is up to your web borwser (a website can not know what folders you have on your device). If you use Chrome, try to enable "Ask where to save each file before downloading"

https://www.lifewire.com/change-file-download-location-in-chrome-4103622

Some people dont want any website to save any file to their device, so their browsers simply block attempt to safe file. Websites are not as powerful as you think :D

**Comment by jodice** [comment]
Understood! Thank you for taking time to answer my questions.
