### ISSUE TITLE
Automate POD won't start the Downloads once I select "GO"

### ISSUE THREAD

**Issue by TeriL12** [photopea/photopea#5908]
I've tried several ways to make it go and get me the image downloads.

  I have a VAR1, VAR2, VAR3 -- all of the text layers also indicate the corresponding variables.  

Not sure what else to try.

**Comment by photopea** [comment]
Hi, what is Automate POD? What feature of Photopea are you talking about?

**Comment by photopea** [comment]
I have to close it, as there was no response.
