### ISSUE TITLE
logged - the app won't load

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#5909]
Steps to reproduce it:

1. use safari
2. login via Google
3. refresh the page

<img width="1470" alt="Screenshot 2023-08-01 at 21 31 39" src="https://github.com/photopea/photopea/assets/3184228/ec56d57c-63d0-499f-a967-63d8c7586c9e">

**Comment by landsman** [comment]
I tried to remove all cookies, localStorage etc, and do login again. Now it's working just fine!

Anyway, an HTTP request with status code 404 to `/undefined` is still present.

**Comment by photopea** [comment]
I just tried your three steps and everything works fine :/

I do see the request to "www.photopea.com/undefined", even when logged out. Do you understand Safari? Can you find out what part of my code makes such a request?

**Comment by pnc** [comment]
@photopea I'll see if I can figure out repro steps, but I have the same issue.

The `/undefined` request might be a red herring. I set a URL breakpoint and it's triggered from here:

<img width="1552" alt="Screenshot 2023-08-04 at 21 18 17" src="https://github.com/photopea/photopea/assets/108524/1262d3d2-5463-4a12-aeb9-280b2393779c">

If you have a source map, I'm happy to set that up and try to debug.

**Comment by pnc** [comment]
The other obvious error is

<img width="418" alt="image" src="https://github.com/photopea/photopea/assets/108524/7a3691a8-d60f-4c3c-851b-1036b793207a">

<img width="1552" alt="Screenshot 2023-08-04 at 21 20 59" src="https://github.com/photopea/photopea/assets/108524/cc3f327c-70af-4f0a-b83e-bd8f3ea5cf3b">

**Comment by pnc** [comment]
If I set `x = "asdf-asdf"` in the debugger, this code doesn't throw an error and Photopea seems to work normally. I'm not sure what this code is supposed to do, but hopefully you do!

FYI, I love Photopea, pay for a monthly subscription, and was able to cancel Creative Cloud (finally) because of it. Thanks for the great product.

**Comment by photopea** [comment]
BTW. why it does not happen in other browsers?

**Comment by photopea** [comment]
I have to close it, as there was no response.
