### ISSUE TITLE
it keeps zooming me out my tools

### ISSUE THREAD

**Issue by SECURITEH** [photopea/photopea#5911]
i dont know whats happening but any time i log on or edit text it pans the tools to the right and i cant do anything but restart it and have it happen again. WHAT IS HAPPENING[]
![Screen Shot 2023-08-02 at 12 21 35 PM](https://github.com/photopea/photopea/assets/141200057/08f19bdf-f86c-4dfe-91a1-11b2d314642f)

**Comment by photopea** [comment]
Hi, try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it, as there was no response.
