### ISSUE TITLE
the brush does not keep up with the mouse

### ISSUE THREAD

**Issue by POlhaV** [photopea/photopea#5913]
when selecting a brush or eraser, the stroke lags behind the mouse

**Comment by photopea** [comment]
I never saw such a problem. What should I do to see it? Or could you record a video of what is happening?

**Comment by POlhaV** [comment]
Maybe I've changed something in the settings, but I've tried everything,
and it's still far away from the mouse

ср, 2 авг. 2023 г. в 12:28, Photopea ***@***.***>:

**Comment by POlhaV** [comment]
Thanks, everything works

**Comment by photopea** [comment]
Whenever you want to reset Photopea into "factory settings", just clear the website data ("cookies"), or use it in a different web browser (or in the Incognito mode).
