### ISSUE TITLE
Cannot drag and position the overlay image

### ISSUE THREAD

**Issue by AMERICANEAGLE1974** [photopea/photopea#5914]
After I select New Project, Create and then choose an image I want to apply an overlay, when I select the overlay image and change it's opacity instead an arrow that allows me to drag and position the overlay image, the cursor changes to a + and won't allow me to drag and position the overlay image. I've tried restarting the computer and reattempting, but nothing seems to get it to stop changing the cursor to a + and not allowing me to drag and position the overlay image. Can you look into this for me?

**Comment by camoody1** [comment]
Make sure you don't have the Auto-Select checkbox checked in your top toolbar. I don't exactly understand what problem you're seeing, but unchecking that box might help you with the tool not working the way you think it should.

If that doesn't work, record a short video showing everything you do from the start of opening a new project until it stops working the way you want it and paste a link to it here. That would be helpful for us to see for ourselves what you're actually doing. Thanks

**Comment by photopea** [comment]
Right, could you share a screenshot or a video of what is happening? It is not clear what tool are you using (in a Toolbar).

Also, try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it, as there was no response.
