### ISSUE TITLE
Default Tool Has Changed

### ISSUE THREAD

**Issue by joestoneman** [photopea/photopea#5915]
Good Morning,

The default hotkey has changed for the Spot Healing Brush tool. This was simply 'J' but now requires manual selection or shift + J 4 times. This is a tool I use often so is there a way to revert this back? I know this may seem like a small issue but It's a tool I use very often and so my muscle memory is throwing me off.

Kind regards,

Joe.

**Comment by photopea** [comment]
sorry, it is fixed now.
