### ISSUE TITLE
Add color management / ICC profile support

### ISSUE THREAD

**Issue by fuweichin** [photopea/photopea#5918]
Given the facts that
+ iOS embeds Display P3 ICC profile in photos by default since 2016 (iPhone 7), Android supports Display P3 photos since 2019 (Pixel 4)
+ Safari supports Display P3 canvas since v15.1, Chrome supports Display P3 canvas since v111
+ Lots of rencent laptop/monitor models support 90% or more DCI-P3 color gamut

It's time to add experimental color management support.

Here are some tasks I can imagine:
+ detect monitor's CapableColorSpace, browser's PredefinedColorSpace.
+ read embeded ICC profile when opening an image, check if the ICC color space matches one of PredefinedColorSpace, if the ICC profile matches PredefinedColorSpace and matches CapableColorSpace then set canvas working color space to that image color space described by ICC profile.
+ allow user to specify a color space (from those predefined, capable and preset) when creating a new image, if specified, embed corresponding ICC profile sidecar file to the image when saving.

Sorry to be so verbose, hope the color management feature will come as soon as possible.

**Comment by photopea** [comment]
Now, you should be able to open a file (JPG, PNG, WEBP ...) with any custom ICC profile, see the correct colors inside Photopea, and save it back in the same color profile. When you create a new document (in Photopea), click a "tiny triangle" to choose one of pre-defined color spaces.

The image in Photopea is displayed through the sRGB mode (in a HTML canvas). So if your JPG file is in Display P3, and your monitor can display P3, the colors outside sRGB will be displayed using the most-similar sRGB colors. 

Many people with new monitors (that can display more than sRGB) use the "vivid mode" - the brightest sRGB value is re-mapped to the brightest Display P3 value (which is much brighter or more saturated than the sRGB color). So when they open an image in Photopea, it looks more saturated than when opened in Photoshop or other native programs.

**Comment by fuweichin** [comment]
I made a Display P3 testing image in PNG/SVG formats, see attachments below.

When I open the testing PNG with Photopea, I cannot get correct colors, compared to colors rendered by iOS Photos, Google Photos or Windows Photos.

My monitor supports 100% DCI-P3 and is working in "Vibrant (Full)" color mode, Windows is set to use [Display P3](https://www.color.org/chardata/rgb/DisplayP3.xalter) ICC profile.

I didn't know Photopea already had color management support, but there may be some bug in my case, that's why I raise this issue.

colorbars-p3.png
![colorbars-p3](https://github.com/photopea/photopea/assets/1687235/844ca2d0-28ed-48b3-b236-c9aa79225392)

colorbars-p3.svg
![colorbars-p3](https://github.com/photopea/photopea/assets/1687235/cc1a6524-c4fd-4e4d-bebb-53d6fdc89f89)

**Comment by photopea** [comment]
The preview inside Photopea is still "cropped_ to sRGB colors. But if you open your file in Photopea, modify it, and export it back, the non-modified colors should still look the same.

We are planning to improve the preview in Photopea, but we dont have resources for it at the moment.
