### ISSUE TITLE
psd templates loading error

### ISSUE THREAD

**Issue by EditSquex** [photopea/photopea#5919]
![image](https://github.com/photopea/photopea/assets/119503930/cea2445f-9683-4d98-8248-aa251c0ce174)

**Comment by camoody1** [comment]
@EditSquex Try the steps on this page and see if they help you:
https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by EditSquex** [comment]
@camoody1 doesnt work :/

**Comment by camoody1** [comment]
So, what is the actual error? You said that there was an error? Or are you saying it's just stuck on loading? Which template are you trying to open? Can you attach the template here?

**Comment by EditSquex** [comment]
i tryed all templates and just stuck on loading...

**Comment by EditSquex** [comment]
i tryed 2 browser and again stuck loading screen

**Comment by camoody1** [comment]
Which templates? The Photopea templates? Or some templates you already own? Have you been able to open templates in Photopea previously? 

Do you live in Turkey, by any chance?

**Comment by EditSquex** [comment]
i living turkey, the photopea psb templates, I couldn't open it before.

**Comment by camoody1** [comment]
Ahh, that explains your problem. The Turkish government is blocking Photopea templates. You'll need to petition your government to let you use Photopea templates or you'll need to use a VPN.

Sorry about that. There's nothing that the Photopea developers can do.

**Comment by EditSquex** [comment]
:( thanks @camoody1

**Comment by EditSquex** [comment]
i can open with vpn thanks

**Comment by camoody1** [comment]
Good. I'm glad you were able to find a way to make it work for you. Have a nice weekend.

**Comment by photopea** [comment]
Yeah, Turkey is blocking Backblaze - our cloud storage provider: https://www.reddit.com/r/backblaze/comments/y3utnr/cant_connect_to_backblaze/
