### ISSUE TITLE
Dragged out shape isn't as defined in fill and stroke in tool bar

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#592]
After setting fill and stroke color in tool bar, the then dragged out shape sometimes jump to a different setting, for example both no fill and stroke

**Comment by photopea** [comment]
Please, be more precise how to reproduce the bug. It never happened to me and I can not make it happen.

If you select another layer in a Layers panel, the global shape style is replaced by the style of that layer. I think this is what happened in your case.

**Comment by hgs54371** [comment]
No, that is not the reason, more precise again,

When first enter shape tool, the default is Fill Red and Stroke None, now change that to Fill None and Stroke Red, then drag out the shape, the Fill is immediately switch back to Red, and the shape is also Fill Red
