### ISSUE TITLE
Script to replace a Smart Object Image

### ISSUE THREAD

**Issue by abetancurlobelo2405** [photopea/photopea#5921]
Hello, im struggling figuring out how to replace an smart object with photopea using scripts, i have tried this script https://gist.github.com/laryn/0a1f6bf0dab5b713395a835f9bfa805c but it doesnt seems to work with photopea, what im really looking for is a way to replace the current smart object layer image with another image stored in the cloud

**// select a layer that you want to work with
var l = app.activeDocument.layers.getByName("arrow");
app.activeDocument.activeLayer = l;

executeAction(stringIDToTypeID("placedLayerEditContents")); 

// now, the Smart Object is an active document, we can work with it
app.activeDocument.activeLayer.rotate(90);

// save the smart object and close it
app.activeDocument.save();
app.activeDocument.close();**

This example from photopea teach us how to replace text, but not images stored in the cloud (I know its more complicated), and thats what I want to do, but if you can give me some hint on how to do that I will really appreciate it, please help!, thank you all.

EDIT: 

I tried an script to open the smart object, edit it adding another image and then close and saving, I tried it on the photopea's playground, it closes the smartobject openned document but photopea says "smart object updated" and then "loading..." forever, the smartobject in the principal document is not changing here is the script:

function openSmartObjectContentsAndAddLayer(smartObjectLayer) {
  if (!smartObjectLayer || smartObjectLayer.kind != LayerKind.SMARTOBJECT) {
    alert("Please select a valid Smart Object layer.");
    return;
  }

  app.activeDocument.activeLayer = smartObjectLayer;

  var idEditContents = stringIDToTypeID("placedLayerEditContents");
  var desc = new ActionDescriptor();
  executeAction(idEditContents, desc, DialogModes.NO);

  var newDoc = app.activeDocument;
  var newLayer = app.open("https://loremflickr.com/640/360", null, true);
// save the smart object and close it
app.activeDocument.save();
app.activeDocument.close();

}

var activeDocument = app.activeDocument;
var smartObjectLayer = activeDocument.activeLayer;
openSmartObjectContentsAndAddLayer(smartObjectLayer);

maybe im missing something? is this the best way to replace a smartobject image?, thanks

PS. sorry for bad english

**Comment by photopea** [comment]
Photopea scripts can not do asynchronous waiting. So split your script into several parts, and call each part separately, with a delay between them (to be sure your image is loaded).

**Comment by abetancurlobelo2405** [comment]
> Photopea scripts can not do asynchronous waiting. So split your script into several parts, and call each part separately, with a delay between them (to be sure your image is loaded).

Yeah, i

**Comment by sakumar9** [comment]
Question on this: Photopea scripts can not do asynchronous waiting. So split your script into several parts, and call each part separately, with a delay between them (to be sure your image is loaded). ---> How???? Can you share an example?

**Comment by photopea** [comment]
Run a script 

app.open(url);

and a bit later, run a script

app.activeDocument.activeLayer.translate(20,20);

You can run a script by pressing File - Script and typing your script, and pressing "Run".

**Comment by milqnomadu** [comment]
@achesui did you find a solution. Can you share it please?
