### ISSUE TITLE
My project just deleted itself and refreshed

### ISSUE THREAD

**Issue by TFKuba** [photopea/photopea#5922]
I was making an overlay for my stream and while i was doing it photopea just refreshed for whatever reason and deleted my entire project

**Comment by photopea** [comment]
Are you using it on an old iPhone? What exactly should I do to see that problem myself? It never happened to me.

**Comment by MistyKaye01** [comment]
I am having the same problem! My project repeatedly deletes when Photopea sporadically refreshes. I am working on a desktop running Windows 11, that is fully up to date. This problem just started a few days ago. I would LOVE to know the solution, as this is very frustrating.

**Comment by photopea** [comment]
I have to close it, because the original author did not respond.
