### ISSUE TITLE
Bug: Merging a visually disabled folder makes the merged result layer empty

### ISSUE THREAD

**Issue by xan2622** [photopea/photopea#5925]
Merging a folder (that contains many layers) while its visibility is disabled makes the merged layer empty.

![firefox_VMlzuuejch](https://github.com/photopea/photopea/assets/1732773/311cb994-9f9d-43dc-91d4-268e483d6160)

**Comment by photopea** [comment]
What exactly would you like to happen instead, and why?

I noticed, that in Photosohp, the Merge is not available for a folder, which is hidden. So I made it work the same in Photopea.

**Comment by xan2622** [comment]
> What exactly would you like to happen instead, and why? 

I would expect that merging a "hidden folder" (with several layers inside), to result in a "single merged layer" (with pixels) but hidden (as the folder was). 

It seems that you made it impossible to merge a hidden folder. 😟
Please, would it be possible to restore this possibility but the way I explained in my previous sentence?

**Comment by photopea** [comment]
I think the result of merging must be a visible layer.

**Comment by camoody1** [comment]
This is an interesting question.

@xan2622 If you had a forty layer project with five hidden layers scattered throughout and then chose to merge all your layers, you obviously wouldn't expect those hidden layers to all of a sudden be included in the merge result. Right? But you DO expect hidden folders to be merged visibly? What if that folder had a few hidden layers inside of it when you merged them? Would you expect those layers to be merged with the other visible layers? Or would you expect them to be ignored?

Do you see how difficult the logic is there?

**Comment by xan2622** [comment]
> If you had a forty layer project with five hidden layers scattered throughout and then chose to merge all your layers, you obviously wouldn't expect those hidden layers to all of a sudden be included in the merge result. Right? 

Correct. These five hidden layers should not be included in the merge result.

> But you DO expect hidden folders to be merged visibly? What if that folder had a few hidden layers inside of it when you merged them? Would you expect those layers to be merged with the other visible layers? Or would you expect them to be ignored?

I would expect them to be ignored.

**Comment by photopea** [comment]
What if a hidden folder (which you are merging) has another hidden folder inside it? Should the content of that hidden folder be present in the new (hidden) layer?

**Comment by xan2622** [comment]
No. If it's hidden, IMO, it should be excluded.

**Comment by photopea** [comment]
Just make the folder visible, merge it, and make it invisible again.

**Comment by xan2622** [comment]
> Just make the folder visible, merge it, and make it invisible again.

That's a possibility indeed. But what I suggested aimed to increase productivity, user-friendliness.
