### ISSUE TITLE
`app.activeDocument.saveToOE("webp:0.8")` produces broken images for some input images

### ISSUE THREAD

**Issue by lucadalli** [photopea/photopea#5926]
For some input images, when using `app.activeDocument.saveToOE` to export a `webp` image with a quality parameter specified (ex: `0.8`), the output webp is broken and cannot be opened by neither Chrome nor Photopea itself.

I have emailed support an example image as I am not allowed to share it openly.

**Comment by photopea** [comment]
fixed! :)
