### ISSUE TITLE
templates not opening

### ISSUE THREAD

**Issue by majah20** [photopea/photopea#5927]
when I click on a template it doesn't open it only shows the loading message but it does not open

**Comment by camoody1** [comment]
@majah20 Do you happen to live in Turkey?

**Comment by majah20** [comment]
Am from kenya

**Comment by camoody1** [comment]
I know the government of Turkey actually blocks the Photopea templates. I'm not aware if the Kenyan government does as well. I am able to access the templates here in the United States. Do you have a VPN you could use to connect to a US server and then try the templates, again?

The other possibility is that you have a browser extension causing you issues. Try the steps listed here on this page and then try again:
https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
Yes, try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by majah20** [comment]
I don't have a VPN maybe you can help me on that

**Comment by camoody1** [comment]
@majah20 You could maybe try this free Chrome VPN extension. Please realize that I've never used this extension and Photopea offers no support for it if it causes you any issues (though it is very highly rated, so it will probably be fine).

https://chrome.google.com/webstore/detail/hola-vpn-the-website-unbl/gkojfkhlekighikafcpjkiklfbnlmeio

**Comment by majah20** [comment]
Thanks, I'll check it out.

**Comment by photopea** [comment]
There is nothing we can do about it. Your internet provider is probably blocking it. Try to switch to a different network.
