### ISSUE TITLE
Text is not showing up

### ISSUE THREAD

**Issue by Khyros98** [photopea/photopea#5929]
Whenever i type something on top of the project i've made, nothing shows up , it is like i'm typing blocks instead of letters , i will link the picture of the problem.
![Sin título](https://github.com/photopea/photopea/assets/141653675/5ffdceee-5878-4877-bb45-dfdc206d369e)

**Comment by photopea** [comment]
Hi, could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it, because the person did not respond.
