### ISSUE TITLE
Bug: drawing/filling round shapes

### ISSUE THREAD

**Issue by MinonoZ** [photopea/photopea#5930]
When drawing a closed path or using the ellipse shape tool, the filling does not follow the curve but in straight lines between anchor points.
![Screenshot 2023-08-07 192728](https://github.com/photopea/photopea/assets/141671269/ba4c2abd-6064-403c-9356-6900fd3cd443)

**Comment by photopea** [comment]
Hi, could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by MinonoZ** [comment]
Seems like it was a problem with my PC. Its fixed now, thanks.
