### ISSUE TITLE
Issue with Photopea crashing in Chrome, but working in Incognito window

### ISSUE THREAD

**Issue by Adonalyn** [photopea/photopea#5931]
Hi there!  I am unable to use Photopea on my regular Chrome Browser.  It takes forever to load and then eventually crashes.  The only way I can use it is to open an Incognito window.  I have a feeling it has saved some past progress and is trying to reopen, but I honestly wish it would not do that, because it causes a huge amount of latency when I want to open it again.

Thanks!

**Comment by photopea** [comment]
I am pretty sure that you use some browser extension, whch prevents Photopea from closing the old, temporary files. 

Try this: https://www.photopea.com/tuts/photopea-opens-up-old-files/ - especially the last part - clearing the website data.
