### ISSUE TITLE
DPI issues and text

### ISSUE THREAD

**Issue by ChiefC11** [photopea/photopea#5932]
So I have an image that has to be at 72 DPI. I can not resize the canvas. Whenever I try to add text onto it in a smaller font size (12 px) it appears blurred
![Pic 1](https://github.com/photopea/photopea/assets/117791537/d9059ba8-ade7-4e1a-b010-6fa63f71994e)

But, if I change the DPI to 144 or double what I already had it looks fine. But then the image is too big obviously.
In the image, If I have the text set at 24 px, it also looks fine and like I want it to be. Any work around to changing the dpi?

![Pic2](https://github.com/photopea/photopea/assets/117791537/d2078708-1c5c-4177-8fd9-1a867dd6f02a)
this is what i want it too look life for reference

**Comment by photopea** [comment]
When typing, there is the "Aa" option at the top - Antialiasing. Try to set it to "None".

**Comment by ChiefC11** [comment]
![image](https://github.com/photopea/photopea/assets/117791537/9a56f1b5-15b7-48a5-b80c-c513a17c9d50)
it makes it look like this

**Comment by ChiefC11** [comment]
any way to get rid of the extra pixels around it?

**Comment by photopea** [comment]
Can you use your font in some other program and make it look as you want?

Personally, I think you should use a larger text size, like 50 - 200 px. Because in your first image, the gap between "B" and "l" is 2 pixels, but in your second image, it is 1 pixel. Also, it would help if you told us the name of your font.

**Comment by ChiefC11** [comment]
It is a custom font, and I need it to be small because Im creating icons for a game

**Comment by photopea** [comment]
Could you prove that typing with your font in Photopea works wrong - i.e. differently than in some other program?

I could look into it myself, but oyu did not show us your font.

**Comment by photopea** [comment]
I have to close it because the person stopped responding.
