### ISSUE TITLE
Photopea will not keep my project loaded

### ISSUE THREAD

**Issue by MistyKaye01** [photopea/photopea#5938]
Whether I try to open an existing project or create a new project, Photopea is slow to load then refreshes (causing the loss of my progress or my project altogether). How do I stop this?

**Comment by photopea** [comment]
What device are you using? Do you use a phone, which is more than 15 years old? Also, how large is the file which you open?

**Comment by MistyKaye01** [comment]
I am using my desktop, with Microsoft Edge for my browser. I am trying to make a 22x192 inch file, but the size doesn't seem to matter, as it closes and refreshes wheter I have a small file (100KB) or a larger file (like 1.07MB).  My computer isn't old or using too much memory though

**Comment by photopea** [comment]
What DPI do you use? 192 inches at 300 DPI is 57600 pixels tall, that is quite a lot and you might need tens of GB of memory.

**Comment by camoody1** [comment]
@MistyKaye01 A 1.07MB file is still actually quite small. It's not uncommon for me to open and modify files over 30MB in size on both my phone and PC. It sounds like something specific to your PC or browser setup. Try following the steps in this guide to see if it makes any difference for your situation and then report back.

https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by MichalSZZ** [comment]
22 inches x 192 in with 300 DPI. @camoody1 can you work with that big file on your phone? Can you create a new file and work on it?

**Comment by photopea** [comment]
I still think it fails because of your work using too many pixels, thus too much RAM memory. Just use a smaller DPI, or wait until we make a vector editor.

You can press Window - More - Memory to learn more. As you can see, it is 380 million pixels and 2.4 GB of RAM for an empty document.

![image (1)](https://github.com/photopea/photopea/assets/15955558/b9c0f20e-073d-4c1d-8c0a-87de781f9e2f)

**Comment by camoody1** [comment]
@MichalSZZ God no. That would be an absolutely enormous image. Some of the PSD files I work with on my phone are over 40MB in size, but no single image anywhere near that large at that DPI.

I can handle an image that large in Photoshop without too much problem, but Photopea runs out of RAM and then disables WebGL. Maybe someday, if and when Ivan ports Photopea over to WebGPU, the application will be able to handle such large images. 🤷🏽‍♂️
