### ISSUE TITLE
Feature Idea: Swoosher

### ISSUE THREAD

**Issue by flaneurette** [photopea/photopea#5939]
I have an idea for a new feature, as I tried this in photopea, but could not find a way to do it.

I have this swoosher idea: 

1. put blobls paint on canvas. (just as tube of paint)
2. swipe and spread with a swoosher the paint out on a canvas, just as washing windows.

Is there a way to do this? ...or does this require a plugin to be build?

![New Project (15)](https://github.com/photopea/photopea/assets/30347642/0c0f28c0-6387-4a79-b0bc-b85031bfb099)

![x](https://github.com/photopea/photopea/assets/30347642/9a8205f4-70b0-4b75-af24-6681823d17dc)

**Comment by flaneurette** [comment]
It is similar as the Smudge tool, but without the blurring. It just spread paint out, and stops if the amount runs out. Just as in real life.

**Comment by photopea** [comment]
The Smudge tool has a parameter "Strength" at the top. Did you try to increase it?

**Comment by flaneurette** [comment]
Yeah that works, ticket can be closed.

**Comment by photopea** [comment]
okay! :) there is also a Liquify tool, search it on Youtube.
