### ISSUE TITLE
Projects not exporting or saving

### ISSUE THREAD

**Issue by Zeonprint** [photopea/photopea#5940]
Used Photopea for the first time, did what I needed to do, hit Export As SVG nothing happens. Tried Export as PNG nothing happens. Hit Edit Save, It's been saying it's saving for over 40 mins now. Tried escape, tried exit and it says you have unsaved changes - so it's obviously stuck. Is there a reason preventing Export?  Is there a known bug or glitch with Photopea in Chrome and if so can someone tell me how to check in Chrome that it's not preventing it downloading or saving?

**Comment by photopea** [comment]
Hi, there are 700,000 people using Photopea in a day, and nobody reported such a problem.

Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it, because the person did not respond.
