### ISSUE TITLE
Print option is gone. 

### ISSUE THREAD

**Issue by tkauffman1** [photopea/photopea#5942]
<img width="1125" alt="image" src="https://github.com/photopea/photopea/assets/31117738/651efb2b-a288-4a00-9f57-b3b3a5ac500d">

**Comment by tkauffman1** [comment]
From the menu click Print. 
Opens this 'save for web' modal, which used to have the print icon that would allow me to directly print things to my label printer.

**Comment by photopea** [comment]
it should be fixed now.
