### ISSUE TITLE
Automatic translation plugin

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#5945]
It would be nice to make a plugin, which loops through all text layers of a PSD document, and translates them into another language (through some free API, e.g. Google Translate).

@hxim what do you think about this idea? Would you be able to make it? :)

**Comment by Pt-home** [comment]
I had a similar task, and a completely free API (yes, and Google) was not found then. But maybe something has changed.

**Comment by photopea** [comment]
What do you mean it was not found?

**Comment by Pt-home** [comment]
As for me, I didn't find it. There was some kind of trick with an infinite GT API key, but, as far as I remember, it was not possible to bring it to working condition, and then the task ceased to be relevant

**Comment by Pt-home** [comment]
Forgot to say, as requests will be required...

1) Using fetch, for example
[https://playcode.io/1563377](url)
it does not formally give an error, but and it does not give a result 

2) Use XMLHttpRequest, for example
[https://playcode.io/1563382](url)
give an error:
pp.js:10327 Uncaught new XMLHttpRequest

**Comment by a2937** [comment]
This seems to be an interesting service for providing translations? Can you read more on it and see if it'll work?

https://libretranslate.com/

**Comment by photopea** [comment]
I think it should be doable with https://libretranslate.com/  .

I will close it for now, but hope someone makes it eventually :)
