### ISSUE TITLE
Photopea Crashes COMPLETELY when working with Masks

### ISSUE THREAD

**Issue by CxryzNFTs** [photopea/photopea#5946]
Hello Photopea Devs,

I am writing to alert you of an issue which has been bothering me lately, when I open a project with text and work with raster masking, the project completely freezes and photopea crashes. I would like to point out that, this only occurs when I "Invert" the mask using Ctrl + I, and then duplicating it right after, using Ctrl + J.

Below are some steps and a sample PSD which you can try this out on.

Steps to Replicate:
- Open the PSD file below
- Click on the mask I already created
- Invert it using Ctrl + I
- Then, you want to duplicate it right after, using Ctrl + J
- Observe Photopea as it becomes non-responsive 

Mock PSD File:
https://workupload.com/file/Xshs6h4YDep

As always, thank you for any help I can get on this.

**Comment by photopea** [comment]
fixed! :)

**Comment by CxryzNFTs** [comment]
Woah. That was fast, thank you SOO much!!

**Comment by photopea** [comment]
Thanks for reporting it!

Basically, it happened every time you pressed Ctrl+J, if the raster mask of a folder was active.
