### ISSUE TITLE
Unable to access Photopea.com in Australia

### ISSUE THREAD

**Issue by jcfoto** [photopea/photopea#5947]
Not establishing a connection from multiple browsers. Incognito or otherwise.

**Comment by camoody1** [comment]
Are you still having issues connecting? Photopea is definitely up and running.

What message are you seeing?

**Comment by photopea** [comment]
Could you try to connect through a different internet provider, e.g. a smartphone hotspot instead of wifi?

**Comment by fahad786khan** [comment]
you can also use an vpn

**Comment by photopea** [comment]
I am not aware of any country or government blocking www.Photopea.com, there should be no need for a VPN.
