### ISSUE TITLE
Cannot change font on a per character basis in a text layer like size and color can

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#595]
In a single text layer, text size and color and be changed on a per character basis, but font can't.
This is not very flexible

**Comment by photopea** [comment]
I can change font of each character. Are you sure? Can you send us a PSD?

**Comment by hgs54371** [comment]
When switching font In a text layer, it is not Loaded right after the switching, any typing now will result in tool switch, 
However if you also change the text size after Each font change, the font will load when you type out the following text

**Comment by photopea** [comment]
The font is not loaded unless it is needed for rendering some characters. If you have a PSD without any text layers, selecting fonts does not load any actual files.

Photopea expects, that you have a fast internet. After you switch a font of some text, you should wait until it is rerendered, then continue (it is instant with the fast internet).

I am still having trouble to understand what you mean. Please, be more specific in your descriptions.

"When switching font In a text layer, it is not Loaded right after the switching, any typing now will result in tool switch,"
- what it means to "switch a font in a text layer"? Is the layer entered? is any text selected?
- "any typing now" - when?

**Comment by hgs54371** [comment]
[test3.mp4.zip](https://github.com/photopea/photopea/files/1864755/test3.mp4.zip)

I showed it in the video,

Notice that the 2nd and 3rd group of triple h, I typed successfully Because I Also change the text size After Each font change, 

But the 4th time that I tried to type with yet another font, I didn't Also change the text size, Then it switched to hand tool (shortcut h), instead of load that font and output three h

**Comment by photopea** [comment]
It was fixed. Thank you!

**Comment by hgs54371** [comment]
Now I call it more accurate
Font change only loads after a following font size change

**Comment by photopea** [comment]
So does it work now or not?

**Comment by hgs54371** [comment]
Yes it worked now
