### ISSUE TITLE
When will it be open source? I also want to deploy it on my computer

### ISSUE THREAD

**Issue by geeeeeeeek** [photopea/photopea#5950]
When will it be open source? I also want to deploy it on my computer

**Comment by xan2622** [comment]
Related: 
https://github.com/photopea/photopea/issues/4730
https://github.com/photopea/photopea/issues/3498
https://github.com/photopea/photopea/issues/2021
https://github.com/photopea/photopea/issues/1604
https://github.com/photopea/photopea/issues/1051
https://github.com/photopea/photopea/issues/45

**Comment by photopea** [comment]
I dont have any plans to show my code to anyone now, so I will close it.
