### ISSUE TITLE
How to Save Custom Shapes in Photopea?

### ISSUE THREAD

**Issue by suji7498** [photopea/photopea#5953]
I am facing an issue in saving the Custom shape which I have created using a photo of my keychain photo,
The issue is,
When I create a Custom shape it gets saved till I use Photopea.
but when I close it the custom shape I saved gets vanish and I can only see the default Custom shapes available.

is there any way to save my custom shapes I have logged in to the Photopea account.

**Comment by photopea** [comment]
Press Edit - Preset Manager, and save your shapes as a CSH file. Then, load it next time you open Photopea, and tell Photopea to keep it in a local storage.

**Comment by suji7498** [comment]
Thanks found the solution, Great software. Is there any guide video for beginners which teach getting started with photopea

**Comment by bluep55** [comment]
Plenty to look at here.
https://www.youtube.com/results?search_query=photopea+basics
