### ISSUE TITLE
not exporting with transparent background

### ISSUE THREAD

**Issue by kristiestgeorge** [photopea/photopea#5956]
i have merged layers, removed the background and trying to export as PNG but keeps giving me a solid black background

**Comment by camoody1** [comment]
Paste a screenshot of your project so we can see what you're actually working with.

**Comment by photopea** [comment]
In what program do you see a "solid black background"? Maybe your program can not display PNG files properly.

**Comment by photopea** [comment]
I have to close it because of lack of details.
