### ISSUE TITLE
JPEG XL import/export support

### ISSUE THREAD

**Issue by TigerhawkT3** [photopea/photopea#5957]
Any plans for this? The response to issue #5905 (request for AVIF support) states that this sort of thing would involve an encoder/decoder that can be compiled to WASM. There's a [JPEG XL WASM decoder](https://github.com/niutech/jxl.js), but I don't know whether that helps or if it's not close enough to what would be needed here. There's a [reference codec implementation](https://github.com/libjxl/libjxl), but, again, I'm not sure how helpful that is. Anyway, would be neat to see this as an option in the future.

**Comment by photopea** [comment]
You can already do it in Photopea through a plugin. Press Window - Plugins - JPEG XL.

We will add a "native support" as soon as JXL files can be opened in a web browser (used on websites, etc), just like JPG, PNG, GIF and WEBP can.

**Comment by TigerhawkT3** [comment]
I tried installing that, but it doesn't seem to have affected anything - dropping in a JXL file for import says "unknown file format," and JXL doesn't seem to be in the list for export formats. Anyway, good to know that you plan on adding full support when browsers do, which seems to be starting some time this year with Apple. Thanks!

**Comment by photopea** [comment]
Once you install a plugin, the button appears on the right side of the screen (visible when a file is opened).

![image (3)](https://github.com/photopea/photopea/assets/15955558/0968a2b2-d484-4b50-b825-69bb83d99b54)

**Comment by Artoria2e5** [comment]
> a web browser

that's a dangerously low bar and will not keep this issue closed for long. Geek browsers like Waterfox, Palemoon, Firefox nightly, and Thorium already have JXL support. Safari 17 is already in beta. [Safari is ~20% of global browser usage](https://gs.statcounter.com/), partly because it's the only choice on iOS.

**Comment by photopea** [comment]
Photopea can open HEIC and JPEG XL files now using File - Open :)

**Comment by TigerhawkT3** [comment]
Nice! One day, Photopea won't rely on that plugin at all. Thanks!

**Comment by photopea** [comment]
Do you need to export AVIF / JPEG XL? I wonder what do you do with JXL files after exporting? What do you use them for?
