### ISSUE TITLE
Selection by color range doesn't take the sampled color into account

### ISSUE THREAD

**Issue by upavloff** [photopea/photopea#5958]
When selecting a particular color across all the image, the sampled color seems always to be black regardless of the actual sampled color. Seems like an easy fix.

**Comment by upavloff** [comment]
Try to copy-paste this image in it:
<img width="547" alt="image" src="https://github.com/photopea/photopea/assets/32176478/b0caced7-4e18-4450-a2ac-7e58da7e4d0b">

Then sample either the yellow or red with the eyedropper:
<img width="34" alt="image" src="https://github.com/photopea/photopea/assets/32176478/a0620f3b-1ffa-4018-ae4c-a03141be4878">

Then go into `Select`, `Color range...`. You will see that the selection with `Sampled color` always select the black region.

**Comment by photopea** [comment]
This is not how Color Range should be used. The Color Range feature is not related to the foreground color (which you picked before starting the Color Range).

Please, read our manual: https://www.photopea.com/learn/advanced-selecting . Or buy a book about Adobe Photoshop to learn how these things work.
