### ISSUE TITLE
By exporting PSD documents to create a pdf presentation they don´t go by numerical order, is that a way to solve this problem without editing all names in alphabetical order ? because photopea do not have an option to order by numerical order.

### ISSUE THREAD

**Issue by guidavid10** [photopea/photopea#5959]
![Captura de tela 2023-08-18 082911](https://github.com/photopea/photopea/assets/142593205/e6ec2808-b07a-4914-ae70-ef1378df1ab9)

**Comment by photopea** [comment]
What is the numerical order? How should we convert names of your files to numbers? Should we delete the first five characters - "Page "? But what if you have 6 characters before the number?

We use the alphabetical order, so maybe use "Page 001.psd" to order it.

**Comment by guidavid10** [comment]
thank you so much. just making sure if there was no other way to order by numerical order

**Comment by photopea** [comment]
You can have file names like "Page 238 last.psd" and "14 Page 83.psd" and how would you order them numerically? Which goes first of the two? Should we delete all non-digits and have "238" vs. "1483", or should we take only the first digit (238, 14), or only the last digit (238, 83) ? I think all options are confusing.

**Comment by camoody1** [comment]
My vote is to leave it as it currently is. I think adding any behind the scenes manipulation of the names would cause confusion for everyone else.
