### ISSUE TITLE
Cmd-1 in safari is for switching to the First web tab, interfere with zoom to 1:1 size shortcut

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#596]
When cmd-1 in safari for zoom to 1:1 size, it respond as switching to 1st web tab

**Comment by photopea** [comment]
In Chrome, Ctrl + 1 also switches to the first tab (and Ctrl + "+" zooms in the page, etc). 

But Photopea is able to "override" these shortcuts. It should work the same in every browser. I suggest you to report it to Apple as a bug.

BTW. you I don't remember, if you are using the latest Mac OS and the latest Safari.
