### ISSUE TITLE
The more history counts are, the more lag it gets.

### ISSUE THREAD

**Issue by farizmuzakki** [photopea/photopea#5964]
Photopea gets laggy when there are a lot of histories. Maybe it will be better if there is a setting to limit the maximum number of the history.

**Comment by photopea** [comment]
Hi, what should I do to see this problem? Photopea was never lagging in my case. Do you use it on a phone?

**Comment by farizmuzakki** [comment]
I'm using it on Windows PC. Maybe, do a graphic design works that utilizes
cut and paste by using rectangle & lasso selection, and adding and removing
some blending effects (layer style) on a layer.

**Comment by photopea** [comment]
Could you find some specific instructions? Or maybe record a short video of how you open www.Photopea.com and what you do next to make it lag?

**Comment by photopea** [comment]
I have to close it, because the person did not respond.
