### ISSUE TITLE
Feature Request: Paste on new project

### ISSUE THREAD

**Issue by wlfio** [photopea/photopea#5965]
Starting a project from the image in the current clipboard seems like a fairly sensible feature.

## How I'd imagine using it
Press file > new
Then paste with ctrl v or similar
Photopea could set the size of the new project to the size of the image in the clipboard and the base layer to the content. (or at least set the size only, so that it can easily be pasted in immeadiately on the new project with an already corre3ctly sized image)

## Current behaviour
At the moment pasting in the new project screen with an image, places a new layer ont he project already open if there is one.
So this shouldn't really be breaking any useful behaviour

**Comment by photopea** [comment]
Now, when you press File - New, and you have an image in a clipboard, the pre-set image dimensions should be the dimensions of the clipboard image (as long as your browser allows websites to "see" the clipboard content before pasting it).

What web browser do you use?

**Comment by wlfio** [comment]
Ahh, ok it works in chrome as a normal tab, but didnt work when i had photopea installed as a pwa, because it poped up a seperate permission prompt for clipboard access that I hadn't seen.

**Comment by photopea** [comment]
yes, you need to give Photopea access to your clipboard, if you want it to be able to access your clipboard.
