### ISSUE TITLE
Changing colors when importing PDF

### ISSUE THREAD

**Issue by SynZbigniewa** [photopea/photopea#5966]
When importing a PDF file, all colors of individual elements change to black.
I want to get vectors.
Where am I making a mistake?
Please help.
![test](https://github.com/photopea/photopea/assets/142808500/c7785dd4-237d-42fe-9785-9ea6864e8a0f)

**Comment by SynZbigniewa** [comment]
![test2](https://github.com/photopea/photopea/assets/142808500/8f555c7f-1e4a-4ff8-9da0-c3b469ced3c8)

**Comment by photopea** [comment]
Hi, could you share your PDF file with us?

**Comment by SynZbigniewa** [comment]
required documents sent by e-mail.
Thank You.

**Comment by photopea** [comment]
Did you send it to support@photopea.com ? I did not receive it.

**Comment by photopea** [comment]
Hi, it should work better now. BTW. you are exporting a PDF, not importing it :)

**Comment by SynZbigniewa** [comment]
What can I say.
I am very grateful for your help.
I think I know how to repay you :)
Regards
