### ISSUE TITLE
Path Select Tool selection area selection problem

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5967]
I have had this issue for a long time, but i didn't had the time to repro correctly.

The problem: 
When using the path select tool the selection area that you can do by click-hold and drag to select multiple paths does not work, unless you first select a shape first with the same tool, then the selection area works.

How to repro:
 Create 2 different shape layers. Click one with Path Select tool and move it around. Now select the other layer and make a selection area to select the other shape. You won't be able to. To correct this behaviour, click the shape first with the Path Select tool and then you can make a selection area that works.

[Screen recording 2023-08-21 10.57.06.webm](https://github.com/photopea/photopea/assets/11801254/34346fc2-afb8-4992-986e-1989a18e0758)

**Comment by photopea** [comment]
it should be fixed now, thanks for reporting! :)

**Comment by burnsboyamazing** [comment]
It fixed issues selecting the area/shape @TheRadicalDreamer.
[Screen recording 2024-02-14 12.38.32.webm](https://github.com/photopea/photopea/assets/154830140/b0080dfc-e355-46f9-b9e6-9618a976bcc8)
