### ISSUE TITLE
txt not editable

### ISSUE THREAD

**Issue by Photopeafan2** [photopea/photopea#5968]
What's wrong with this text box in this psd file from photopea? I can't select the text in it, not in the Brave or Chrome browser. When I open it in Photoshop, I can edit the text successfully. ( I had to compress the psd file, could not upload a psd file)
[things to do.psd.zip](https://github.com/photopea/photopea/files/12399646/things.to.do.psd.zip)

**Comment by photopea** [comment]
Everything works well, except that when you highlight an interval of letters in Photopea, they are not "higlighted" in the preview.

You have the Leading of "81.95". I tried to change it to 82 and then back to 81.95 and the highlight started to work.

How did you create this PSD file?

**Comment by photopea** [comment]
Here is a fixed version. 

If you find exact steps of how to produce such a PSD file (with un-highlightable text), let me know!
[things to do.zip](https://github.com/photopea/photopea/files/12402354/things.to.do.zip)
