### ISSUE TITLE
Uploading large Files freeze

### ISSUE THREAD

**Issue by triplex111** [photopea/photopea#5970]
WHen I upload an image that is around 50mb and then select the Wand the UI freezes and cannot use it. I have updated browser + restarted still no bingo.

**Comment by photopea** [comment]
How much RAM memory do you have on your device? Is it a phone?

Could you send me your PSD to support@photopea.com, so that I try it myself?

**Comment by triplex111** [comment]
I am on a mac 

8 gig memory 1867 mhz ddr3

**Comment by photopea** [comment]
when you open your PSD, press Image - Image Size, what size do you see?

**Comment by triplex111** [comment]
I saved the PSD and attached to email but it says the PSD is 0 bytes

**Comment by triplex111** [comment]
When I go to open the saved PSD file it says cannot open as it is zero. I will try download again

**Comment by triplex111** [comment]
It is flashing up the top saying 

Not enough ram need 2048

**Comment by triplex111** [comment]
Although I have 8gig

**Comment by triplex111** [comment]
If I try use the website with a smaller file it works fine

**Comment by triplex111** [comment]
It does say on the website "page unresponsive, exit page or wait"

**Comment by photopea** [comment]
So you have a 50 MB PSD file, which can not be opened in Photopea? Could you send me that file to support@photopea.com ?

**Comment by photopea** [comment]
I have to close it because the person stopped to respond.
