### ISSUE TITLE
[Feature Request] Export to PDF

### ISSUE THREAD

**Issue by kekkoudesu** [photopea/photopea#5972]
I lay out book interiors in inDesign. I brought a 216-page book into Photopea, not really expecting much...but I was kind of impressed that Photopea actually managed to not completely crash. Last time I did this, it was unusable. However, now it works with only some slowdowns, although obviously missing a bunch of inDesign features.

However, in order to use Photopea to edit a book layout, I need the ability to export to PDF.

I don't know if this is a use case Photopea even wants to support, but it's all I use inDesign for. There are a bunch of other issues too:

* Page numbers are garbled
* Text that is supposed to wrap around an image doesn't anymore; the image is just layered over the text

**Comment by photopea** [comment]
PDF export has been present in Photopea for many years. Our users export more than 20,000 PDF files in Photopea every day.

If you have an InDesign file which does not look right after opening in Photopea, please, share it with us. It would be the best if you share a file as-small-as-possible (e.g. delete pages which look ok).

**Comment by kekkoudesu** [comment]
Oh, sorry, I see I missed the option to export to PDF! It seems to work okay. I need some more options to produce a print layout that matches KDP/IngramSpark standards, though:

* The artboards are configured as two-page spreads, but it needs to be single-page spreads on export
* Configure Bleed
* Configure Margins (not inside of export settings but inside the main program)

Here's IngramSpark's interior checklist, for a full list of what they want, for example: https://www.ingramspark.com/hubfs/downloads/pdf-checklist.pdf

I tried with another .indd file and the text on most pages has been replaced by the text supposed to be present on only one page, the Table of Contents is broken, and many of the fonts are wrong. I might be willing to share the .indd file privately. 

Is this a use case you want to support? There are so many features Photopea would need to have in order to handle book interiors properly—and you'd need the ability to export to .indd too. No use making changes to the interior and not being able to save them except as a PSD.

As an image manipulation program, Photopea is very cool, and works a lot better than Adobe's Photoshop Web beta. Supporting afphoto is also amazing. I think handling the kinds of projects you can create in inDesign is a tall ask, though...

**Comment by photopea** [comment]
I guess you are right. We can not turn Photopea into Adobe InDesign, so it is better to leave it as it is.

**Comment by photopea** [comment]
So in General, Photopea works only with a PSD format. If you have an INDD file, please, create a PSD file with the identical content, and I will try to make Photopea produce the same PSD when you open your INDD in it.

In other words, I can only add features which are possible inside PSD files.
