### ISSUE TITLE
leading not working

### ISSUE THREAD

**Issue by Photopeafan2** [photopea/photopea#5973]
When I try to adjust the leading I can't go lower than the font size. The font is roboto, browser is brave, OS is OSX
In the zip file is a short movie and the psd file exported  from Photopea.
[leading in Photopea.zip](https://github.com/photopea/photopea/files/12443442/leading.in.Photopea.zip)

**Comment by camoody1** [comment]
Weird. I'm using Windows 11 and Microsoft Edge. Using the same font, I can reduce the leading as far as I want and the letters will lie right on top of each other. 🤷🏽‍♂️

**Comment by photopea** [comment]
You are right, there was a bug, I just fixed, it should work correctly now :)
