### ISSUE TITLE
Editing text removes spacings

### ISSUE THREAD

**Issue by cyclops365** [photopea/photopea#5974]
https://i.gyazo.com/30cfbd0731d76c30b3a1737ff550b4a6.mp4

Clicking to edit text from a previously saved document removes all spacings.

**Comment by cyclops365** [comment]
Now I can't use the Enter key to separate lines

**Comment by camoody1** [comment]
@cyclops365 Please share a link to your PSD here so we can see what's happening.

**Comment by cyclops365** [comment]
Microsoft Edge
Version 116.0.1938.54 (Official build) (64-bit)

**Comment by cyclops365** [comment]
https://drive.google.com/drive/folders/14HsSS6HRhRU2qkWAPwUlsrdxeeN3lcJv?usp=drive_link

**Comment by photopea** [comment]
I am very sorry, it is fixed now. Thanks for letting us know!
