### ISSUE TITLE
Trouble exporting (pixelated image) + pixelated interface

### ISSUE THREAD

**Issue by luludinamo** [photopea/photopea#5977]
Hello, I am trying to export a project which include vector lines, text and a smart 'noise' layer. When I try to export it (any format), the resolution is poor and pixelated. If I export it in PDF (with 'rasterize all' unticked) the image comes in great quality but some layers such the smart 'noise' layer and a text layer with a stroke outline do not appear. If I export it in PDF (with 'rasterize all' ticked) the image comes in poor/pixelated quality but all the layers appear.

I am also wondering in general why my the interface of my project is pixelated and would only appear crisp/HQ once I export it (with 'rasterize all' unticked). 

Please let me know how to solve it. 

Thank you

<img width="741" alt="ZOOM Rasterize all unticked" src="https://github.com/photopea/photopea/assets/143396176/2e0538be-a0c7-4c41-bb7a-1f841f12da81">
<img width="745" alt="ZOOM Rasterize all ticked" src="https://github.com/photopea/photopea/assets/143396176/78157e3a-a87f-4d95-bfc7-604ecc3a5886">
<img width="1512" alt="Rasterize all ticked" src="https://github.com/photopea/photopea/assets/143396176/5a5497c4-f3ca-4ff3-98f7-8c6362ee7a30">
<img width="1512" alt="Rasterize all unticked" src="https://github.com/photopea/photopea/assets/143396176/207f6dc1-2250-46a8-995b-f87ba31b9917">
<img width="1512" alt="General view" src="https://github.com/photopea/photopea/assets/143396176/60958660-8a90-4f7a-866e-7a6d38a09ccf">

**Comment by photopea** [comment]
Photopea/Photoshop are raster editors and when you zoom in, you will always see pixels.

But if the source of the content is vector graphics, Photopea can export it as vectors in PDF / SVG formats. Sadly, there is no analogy for "Add Noise" in the PDF format.

If you enable "rasterize all" during the PDF export, the PDF contains exactly what you see in Photopea. Could you try to use more pixels (bigger DPI)? 600 pixels is not much.

**Comment by photopea** [comment]
I will close it now, as it can be fixed only by enabling "rasterize all".
