### ISSUE TITLE
Photopea App on windows is not opening in full width

### ISSUE THREAD

**Issue by suji7498** [photopea/photopea#5978]
See the screenshot shared below, the app I have downloaded from Chrome is not responsive on Windows 11
![image](https://github.com/photopea/photopea/assets/32890666/669e6f75-01df-4736-bf08-4829069a5b94)

**Comment by photopea** [comment]
What is "downloaded from Chrome"? Did you go to www.Photopea.com and you pressed "Install Photopea"?

What do you see when you open www.Photopea.com in your web browser? Basically, the installed app should look the same as the website.

**Comment by camoody1** [comment]
@suji7498 To be clear, there is no official Photopea download or extension from the Chrome extension store. You should only open Photopea from http://www.photopea.com/. Also, it looks like you have some Chrome browser extensions installed that are blocking ads. That big blank area on the right normally shows advertisements that make Photopea free to use. If you're having trouble using Photopea, it is recommended that you disable all of your browser extensions and then add them back one at a time until you figure out which extension is causing you problems in the application.

Good luck!

**Comment by photopea** [comment]
I think you are blocking ads. Please, do not block our ads.
