### ISSUE TITLE
Magnetic Lasso tool not functioning.

### ISSUE THREAD

**Issue by VonBip** [photopea/photopea#5979]
When I try to use the magnetic lasso, I'm able to draw a border but when I try to close it a selection is not created and the border I drew is gone.

**Comment by camoody1** [comment]
@VonBip I just tested the tool and it worked fine for me. Try the steps discussed here and see if it helps you.
http://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

If it's still not working for you, please record a short video and post a link to it here so the developer can see exactly what you're doing. Thanks!

**Comment by photopea** [comment]
Press View - Show, make sure the "Selections" are enabled.

Or try this: http://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

If nothing helps, please, record a short video of what you are doing and what happens.

**Comment by photopea** [comment]
I have to close it, because the person stopped responding :(
