### ISSUE TITLE
Not being able to drag and drop images into new tabs?

### ISSUE THREAD

**Issue by sadcircus** [photopea/photopea#598]
You used to be able to drag images from one tab to another (as seen in this video at 3:01 - https://www.youtube.com/watch?v=YQclBuu4lOw&t=10s) now I can't? I'm not sure if this was an update or it's just not working on my computer as photopea was the best photo editor I could get a hold of now it won't work in the way I want it to. Shame.

**Comment by photopea** [comment]
Hi, I just tried it and it works for me. Can you try it again?

**Comment by sadcircus** [comment]
I tried it, still doesn't work.

**Comment by photopea** [comment]
What browser and OS do you use? Are you dragging an image to an existing tab, or to an empty area? What exactly happens instead?

**Comment by photopea** [comment]
can you try it in Anonymous Window?

**Comment by sadcircus** [comment]
Nope, still not working

**Comment by photopea** [comment]
Have you tried several PSD files or just one? What operating system do you have?

**Comment by photopea** [comment]
I am closing it, the discussion can continue here: https://github.com/photopea/photopea/issues/612

**Comment by sadcircus** [comment]
Okay
