### ISSUE TITLE
Field Blur in Photopea?

### ISSUE THREAD

**Issue by CxryzNFTs** [photopea/photopea#5980]
Hello! 

I was wondering if you can add Field Blur Filter to Photopea? Photoshop has this feature but Photopea lacks it, and it is a feature which should be implemented.
![image](https://github.com/photopea/photopea/assets/71056820/c46357e0-e166-42cb-a5fe-a299ac2b0996)

**Comment by photopea** [comment]
Hi, I have added the Blur Gallery filter: https://www.photopea.com/learn/blur-gallery
