### ISSUE TITLE
Cannot Define new swatches

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5982]
Your Operating System: chromeOS
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new project
3. Go to swatches panel
4. Define a new swatch

**Expected behaviour**
It should add a new swatch to the list or folder

**What really happened**
I get no new swatch on the swatch panel

**Video/Screenshot**
[Screen recording 2023-08-30 12.22.10.webm](https://github.com/photopea/photopea/assets/11801254/a892cc08-f270-4250-8c95-43e568708df1)

**Comment by photopea** [comment]
I have fixed it. New colors are added into a folder named "Default".

**Comment by burnsboyamazing** [comment]
It fixed issues defining new swatches @TheRadicalDreamer.
[Screen recording 2024-02-14 12.30.51.webm](https://github.com/photopea/photopea/assets/154830140/aae7d167-5a28-43f6-b24a-b34c5e5dc1e7)

**Comment by Alexander-Burns** [comment]
@TheRadicalDreamer It fixed the issue when defining new swatches in Photopea. See videos.
[Screen recording 2024-04-24 11.43.04.webm](https://github.com/photopea/photopea/assets/113866683/f71eea04-7f79-4991-a570-0876c421edf9)
