### ISSUE TITLE
Photopea iframe limit?

### ISSUE THREAD

**Issue by abetancurlobelo2405** [photopea/photopea#5983]
Hello, 

I'm currently creating (using photopea's live messaging) a script that basically, a user puts an image, and with photopea i can use that image (openning it up) as smart object, (the psd file with the smartobject to be replaced and that photopea opens is on the cloud), so it returns final image with the user's image as a mockup, everything works as expected, so my question is, what if multiple users when the app is deployed calls that scripts, for example, 1000 diferent users, calling the scripts to convert their images to smartobjects and then have its image returned as mockup, is this possible?, or photopea will have any limitations?, sorry for my bad english and thanks.

**Comment by photopea** [comment]
We do not have any limits for the "iframe usage" at the moment. You can use it as much as you want, by as many users as you want.
