### ISSUE TITLE
Shapes have incorrect properties

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5984]
Your Operating System: chromeOS
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open the PSD attached ([shapes in incorrect properties.zip](https://github.com/photopea/photopea/files/12494089/shapes.in.incorrect.properties.zip))
3. Get sure you have 100 DPI cm/pixel
![image](https://github.com/photopea/photopea/assets/11801254/81c5c042-2f4c-4bcb-a31f-5ccd8e0fbf05)
4. Go to the layer named 1.
5. Check its properties in the property window.
It displays:
![image](https://github.com/photopea/photopea/assets/11801254/b5a1e344-f52f-4c31-abdf-703346362b1e)
6. Get the Move Tool and hit Ctrl+T to transform
7. Go to the edge of the shape and press and hold the cursor on one of the white squares.
8. It should display the W and H
![image](https://github.com/photopea/photopea/assets/11801254/3ec24da3-46dd-49cc-806e-7a91ea2323c8)
9. Check the position X and Y if the shape

**What is the expected behaviour**
It should have the same numbers

**What actually happened**
The W,H,X & Y properties are different from what i see on the actual canvas. 

I personally believe the properties window is incorrect because of some different conversion of inch to cm

**Comment by TheRadicalDreamer** [comment]
What do you think @photopea ?

**Comment by TheRadicalDreamer** [comment]
How did you do it? 😱

I've been playing around with transform controls and direct select, but if i get (W: 8 , H: 20) & (X: 150 , Y: 0) on the properties panel, i get (W: 8.1 , H: 20.2) on the transform tooltip.

Here is a video of my trying (sorry for the white noise):
https://screencast.apps.chrome/1TQsQbL07yUmpubG6UtNqmAc85kOYisi5?createdTime=2023-10-16T15%3A56%3A31.432Z

**Comment by photopea** [comment]
Don't use the Free Transform, it incrases the size by 1 pixel, you need the change to be 0.00001 pixel.

Use the Direct Select. Make sure your guides are exactly at right positions (View - Add guides), or enable "snap to pixels" at the top (for the Direct Select).

**Comment by TheRadicalDreamer** [comment]
now i get it

Thanks for the explanation and the tip of snap to pixels
