### ISSUE TITLE
I am unable to mute Commercials with audio.

### ISSUE THREAD

**Issue by Neophyter1** [photopea/photopea#5986]
Your Operating System: AMD with Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Sure

**This must be done to see the problem**
1. Go to www.photopea.com
2. .... Use photopea
3. .... Become un-nerved because of unstoppable audio
4. .... Close photopea, become sad and depressed because of inability to mute audio ads.

**Comment by photopea** [comment]
I just went to https://www.photopea.com/ but I can not hear any sound :( could you record a video of what happens, as a proof?

Also, I think it could be done by your browser extensions. Please, send us a screenshot of the browser extensions, which have your premission to modify Photopea.

**Comment by Neophyter1** [comment]
Found the Sound switch. Going to the hamburger menu at the very top of the page. Then clicking on the url, i found the sounds off switch. The grey clouds fall back, to let the sun shine again. Without any sound of course....
If pics are needed to help anyone else. That would be no problem. Visual affects can be applied. It is photopea.....

**Comment by photopea** [comment]
Could you show us a proof that Photopea pays audio, and it is not played by your browser extensions? If yes, I can pay you 500 USD for finding this problem.

**Comment by photopea** [comment]
Was it an ad for "vans.de"? Are you in Germany?

**Comment by Neophyter1** [comment]
I am in the United States. The issue was resolved by turning all sounds off
in photopea.

**Comment by photopea** [comment]
Could you turn sounds on, and send us a screenshot of the ad which plays audio? It needs to be reported.

**Comment by Neophyter1** [comment]
Sure thing.

**Comment by Bella565** [comment]
I have the same issue here in the UK. I have this issue on my laptop, work PC and a work colleague has the same issue. Usually the adverts are automatically muted but it seems that the odd one isn't.

**Comment by photopea** [comment]
Could you show us a screenshot of these ads with audio, please?
