### ISSUE TITLE
unable to make a new txt layer

### ISSUE THREAD

**Issue by Photopeafan2** [photopea/photopea#5988]
MAC os x ventura
Brave
I have a freeze when I want to make a new txt layer

[New Project.psd.zip](https://github.com/photopea/photopea/files/12504386/New.Project.psd.zip)

https://github.com/photopea/photopea/assets/90322495/d7c944f2-42d7-4816-a1bc-dbf1063487fb

**Comment by photopea** [comment]
Hi, I am very sorry, it should be fixed now.
