### ISSUE TITLE
[Mobile] CANNOT select fonts from local storage to load

### ISSUE THREAD

**Issue by Poinet** [photopea/photopea#5989]
Your Operating System: Android (8.0.0)
Your Web Browser: Brave 
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open any images, literally anything you can edit.
3. Select the font tool
4. Click on "Load Font"
5. Now you can't select any font, they're kinda of disabled (cannot be selected)

![Screenshot_20230903_181506.png](https://github.com/photopea/photopea/assets/60430380/9e9e1cc0-9de3-477c-8452-ecdded50a7fa)
The grayed thing means that they are disabled, before I could select them but not anymore.

**Comment by photopea** [comment]
Photopea should be able to load TTF and OTF fonts.

Did it ever work in the past for you? Could you try it in Chrome or Firefox on Android?

**Comment by Poinet** [comment]
Yes it did work for me in the past, I tried it on Chrome, I was able to load the fonts but I am not able to load it on Brave.

**Comment by Poinet** [comment]
Basically, I was able to load fonts on Brave in the past until now, it seems that I can't load it.

**Comment by Poinet** [comment]
Update: Turns out that I couldn't load fonts on all other browsers (Firefox, Opera, Opera GX, etc) except for Chrome.

**Comment by photopea** [comment]
could you maybe restart your phone?  Can you open other files, e.g. JPG files?

**Comment by Poinet** [comment]
I did restart my phone, twice. The issue still persists

I couldn't open any type of file in fonts. (for loading fonts)

I can open any type of file (png, svg, etc) in open (for opening projects)
I can open .TTF and other font files in open

So the issue only occurs when trying to load fonts.

**Comment by Poinet** [comment]
I found alternative solution to fix the issue.

All you need is to open from files (any file manager) rather than opening from download.

But then it wouldn't allow me to select the entire folders and select multiple files at once.

**Comment by Poinet** [comment]
It seems that it has worked!

Pretty interesting though, but you should still try investigate the issue. Maybe change the way it loads.

**Comment by photopea** [comment]
So it works with File - Open, but does not work with the "Load font" button?

**Comment by Poinet** [comment]
Yeah exactly.

**Comment by photopea** [comment]
It should be fixed now. "Load font" should work exactly as File - Open.
