### ISSUE TITLE
How can we get Mockups generator photo outputs as 300 dpi?

### ISSUE THREAD

**Issue by appen111** [photopea/photopea#5990]
Photopea mockups generator outputs photos as only 96 dpi.
There is no problem at 300 dpi manually via smart object.
When I use the mockups generator, I can only get 96 dpi output.
I want 300 dpi output it's possible?

**Comment by photopea** [comment]
It should be fixed now. The exported images should have the same DPI as your PSD file now.

**Comment by appen111** [comment]
Now is working, thanks so much.
