### ISSUE TITLE
Sliders will not Separating in 'Blending options'

### ISSUE THREAD

**Issue by PatrykBr** [photopea/photopea#5991]
Your Operating System: Windows 11 Pro
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Start a new project
3. make a new layer
4. select the new layer and click 'Filter' > 'Vanishing Point'
5. apply a vanishing point to the layer
6. select the 'Blending Options' of any layer
7. the sliders will no longer be able to separate when holding alt and dragging the slider

**Comment by photopea** [comment]
Wow, that is amazing! I think I would never find this problem even in 100 years! 

Thank you very much for reporting it :) it is fixed now.
