### ISSUE TITLE
Cannot export artboard on WEBP

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5992]
Your Operating System: ChromeOS
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Have 2 or more artboards
3. Export them to WEBP

**What should be the expected behaviour**
It should export a zip with all the artboards. 

**What really happened**
It exports a big canvas with all in it

**Comment by photopea** [comment]
We did it only for the JPG, PNG, GIF and SVG. I have added the WEBP to the list.

**Comment by TheRadicalDreamer** [comment]
Thank you very much!
