### ISSUE TITLE
Cannot open smart object

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5993]
Your Operating System: Chromeos
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes
 
**This must be done to see the problem**
1. Go to www.photopea.com/#ifPNQ4_I7.psd
2. Open the smart object

It won't do it
![image](https://github.com/photopea/photopea/assets/11801254/2f6c25f1-5fd3-4e5f-88d8-67c7b39f565d)

**Comment by photopea** [comment]
I see an error when opening your link. Could you attach it here as a PSD file?

**Comment by TheRadicalDreamer** [comment]
[bad psd.zip](https://github.com/photopea/photopea/files/12525101/bad.psd.zip)

Here it is

**Comment by photopea** [comment]
Your smart objects are AI files. I have fixed the problem - you can open them now. However, the actual content is outside the canvas in these AI files (even if I open them in Adobe Illustrator), so you have to move it to the center.

BTW. these smart objects can not be opened in Adobe Photoshop, as Photoshop can not open AI files.

**Comment by TheRadicalDreamer** [comment]
Thank you.

These was sent by a client and she used AI to crate those and put them in
Photoshop for me.

And she has this practice that works outside the canvas :/
