### ISSUE TITLE
There should be a direct donate link (e.g. to PayPal) for arbitrary donation amounts

### ISSUE THREAD

**Issue by jakobjjw** [photopea/photopea#5994]
Hi,

I just wanted to donate an arbitrary amount, but without "buying premium".
Can't find a link / way for arbitrary donations anywhere...

BR

**Comment by photopea** [comment]
Sorry, we don't accept donations, we want you to get something in return.

The process of getting Premium should not be any harder than making a donation.

**Comment by jakobjjw** [comment]
Ok, thanks for the clarification!
