### ISSUE TITLE
Text stroke is not exported on PDF

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5996]
Your Operating System: ChromeOS
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com/#iuFXJIATe.psd
2. Export to pdf without rasterize

**Expected behaviour**
It should be displayed exactly as it is displayed in the project

**What actually happened**
It does not have the stroke.

![image](https://github.com/photopea/photopea/assets/11801254/c76c028a-64a8-4545-b388-46e992120640)

**Comment by photopea** [comment]
I have implemented it :)

**Comment by TheRadicalDreamer** [comment]
I got into an bug.
![image](https://github.com/photopea/photopea/assets/11801254/ed67c053-c3ab-400b-9c47-fb4ce02fe473)

if i change the DPI of the project, the exported text stroke is different in size

**Comment by TheRadicalDreamer** [comment]
Additionally, if the layer style is off, it prints it anyway
![image](https://github.com/photopea/photopea/assets/11801254/e0170e59-8c2c-4f23-b9b2-09e0f97a5e62)

**Comment by TheRadicalDreamer** [comment]
Also, if it has 2 or more text strokes, but only one activated. It takes the first one, even if it is disabled
![image](https://github.com/photopea/photopea/assets/11801254/2e32ed1d-b9d2-4dd3-8150-a52220dd49ee)

(I understand it is the expected behaviour to have only one stroke effect per layer 😁)

**Comment by photopea** [comment]
it all should be fixed now :)
