### ISSUE TITLE
Convert text into shape causes weird results

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5997]
Your Operating System: ChromeOS
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**

1. Go to [www.photopea.com/#iuFXJIATe.psd](http://www.photopea.com/#iuFXJIATe.psd)
2. Convert the text to shape

**Expected behaviour**
It should be displayed exactly as the text layer

**What actually happened**
It kinda looks like duplicated and off

![image](https://github.com/photopea/photopea/assets/11801254/00fc5fa9-5c93-4b97-9874-aa971e2ad348)

**Comment by photopea** [comment]
This is because you are using the "Faux Bold" (fake bold) on your text. Just disable it. 

It is also related to the fact, that vector graphics works differently in Photoshop and outside it. It will be fixed in VectorPea.

**Comment by TheRadicalDreamer** [comment]
Thank you for the explanation!

Did not know that :D
