### ISSUE TITLE
Merge folder with only path layers get a raster layer

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5998]
Your Operating System: chromeos
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com/#ir00H-XH3.psd
2. Select the folder layer
3. Merge it

It  should get a path layer, but it gets a raster layer.
![image](https://github.com/photopea/photopea/assets/11801254/0568ce09-81c7-4fb6-9d58-cf5a330143bd)
![image](https://github.com/photopea/photopea/assets/11801254/216c3e3f-18a2-4b76-b824-70e180830d81)

**Comment by MichalSZZ** [comment]
In Photoshop - it works the same way.
Is it the right way...? I don't really know.  For me - it is better to have one vector from vectors, but it will be a different behavior than Photoshop's

**Comment by TheRadicalDreamer** [comment]
As far as I know.
Photopea has that behavior, if only there is vectors, the merged layer is a
vector.

But I don't know why in this particular case works differently

**Comment by photopea** [comment]
I would prefer to keep it as it is.

Many people can say that merging two vector layers into one vector layer is wrong. E.g. you can have a drop shadow on one , but no shadow on another one. But "merging" should never change how the result looks like. So this is the degree of "cheating" that I am willing to accept :D

**Comment by TheRadicalDreamer** [comment]
For me it is perfect how Photopea works in this matter.

But i have to say that what i reported is an exception, that maybe has something to do with the folder, rather than the layers themselves.

Let me show you:
[Screen recording 2023-09-06 14.02.01.webm](https://github.com/photopea/photopea/assets/11801254/20a77404-ae23-4266-bc10-73b3296d6cf3)
