### ISSUE TITLE
Vectorize layer gets incorrect colors

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5999]
Your Operating System: chromeos
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Open this PSD
[luna.zip](https://github.com/photopea/photopea/files/12532774/luna.zip)
2. Select the path
3. Vectorize it

Should look like the one on the left, but instead looks like the one on the right
![image](https://github.com/photopea/photopea/assets/11801254/fed886d8-a75c-469c-9b99-78857b76fc10)

I know i can tweak the setting to achieve the desired image, but i was curious why it fill the lands of the earth, if the original image doesn't have them filled, only stroked.

**Comment by photopea** [comment]
Fixed!

This happened only when you had a hole, which was inside a colored shape, which was inside a hole, which was inside a colored shape. That is quite rare :D

**Comment by TheRadicalDreamer** [comment]
thank you Ivan <3
