### ISSUE TITLE
Transparent images have black backgrounds

### ISSUE THREAD

**Issue by byrning** [photopea/photopea#6]
Hi,

Firstly, awesome photo editor - thanks!

When opening a transparent image or creating a new image, the background/canvas is black by default. Surely it should be a checkered background indicating transparency, rather than black?

Thanks!

**Comment by photopea** [comment]
I just tried to open some PNG images and create new project, there is always a "checkered" background. How exactly did you get black background? Can attach your PNG files or a screenshot?

Thank you! You are helping to make PP better :)

**Comment by byrning** [comment]
I'm using OSX El Capitan. I've tried latest versions of firefox, chrome and safari and all experience the same thing.

Steps to reproduce:
1. go to http://www.photopea.com/
2. file > new (project canvas is black instead of checkered)

Thanks!

**Comment by photopea** [comment]
Thanks!
My guess is, that there is a bug in OSX implementation of OpenGL. What happens if you uncheck "WebGL acceleration" at the top? Is it still the same?

**Comment by byrning** [comment]
Yip, it looks like that is the issue. If there is no way around it other than unchecking the "WebGL acceleration" option, then it would be nice to be able to set that using the API.

Thanks!

**Comment by photopea** [comment]
I just tried to do it on my Android tablet and there is black background too, as you described. So maybe the bug is, that it works on Windows, while it is not supposed to.

I will try to fix it as soon as possible.

**Comment by photopea** [comment]
the problem was in division by zero, which is evaluated differently on Mac and Windows.

It should be fixed now :) Thank you very much for your help.

**Comment by byrning** [comment]
good to go - thanks!
