### ISSUE TITLE
Active area dragging

### ISSUE THREAD

**Issue by tomasnosek** [photopea/photopea#60]
If you make a circle with 10px diameter and you will give him 500px border (so visual diameter is 510px), you are able to catch it only in that original 10px object. It's little bit annoying

**Comment by photopea** [comment]
By border, do you mean a Stroke layer style? I think that the active area should be just the actual content, without layer styles.

**Comment by tomasnosek** [comment]
For me - what i see is what i want to catch :) But sure, it's an idea only and maybe my problem only.

**Comment by photopea** [comment]
There can be a problem, when Stroke or Drop shadow is partially visible, e.g. 10 % ... should the object be chosen when you click on the almost transparent drop shadow?

There are 1000 ways of defining, which object should be chosen. Everybody would prefer something different and it is not possible to satisfy everybody. I am going to keep it as it is.
