### ISSUE TITLE
Shared files available in Google Drive

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6000]
It is possible to have shared files section in google drive?

![image](https://github.com/photopea/photopea/assets/11801254/bfde6bbb-344b-4c85-b75e-9abe4d399c8f)

![image](https://github.com/photopea/photopea/assets/11801254/5d04652c-cb1f-4405-bac5-150613edf97e)

For example, the shared folder Guardiana Lunar i don't see it on the Google Drive browsing on Photopea

**Comment by photopea** [comment]
Hey, could you try this? 
![image](https://github.com/photopea/photopea/assets/15955558/245be228-bf85-477f-8bce-0c32eee056b2)

**Comment by TheRadicalDreamer** [comment]
But in reallity i have a bunch of folders shared with me. That i cannot see
![image](https://github.com/photopea/photopea/assets/11801254/bd654bb4-18a1-4fa0-943b-2bffdc612a97)

**Comment by photopea** [comment]
Hey, I have added Google Drive: Shared with me! in my case, it contains a lot of "garbage" - I never needed to look into it :)

BTW. is it ok that we have four storages related to Google Drive? Should we put it into one storage, with four folders at the top level?

**Comment by camoody1** [comment]
I think you should combine them into one storage section named "Google Drives" and then have the four separate folders at the top level.

**Comment by TheRadicalDreamer** [comment]
Totally agree .
One service, 4 folders.

But also I believe I also have a lot of junk in my shared files. But the
folder I showed is in my drive, is from my shared files, but it is a
shortcut I added.
