### ISSUE TITLE
Clipping layers are not supported in PDF??

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6001]
![image](https://github.com/photopea/photopea/assets/11801254/cb2a3e13-ff87-407c-9209-b336b04844c6)

**Comment by photopea** [comment]
There are lots of PSD features, which dont have any analogy in the PDF format.

We can export vector masks to a certain degree. If you want Photopea to work the same as Adobe Photoshop, use "rasterize all".

**Comment by TheRadicalDreamer** [comment]
:(

Oh well, i have to redo those then.

Thank you for the explanation!
