### ISSUE TITLE
Some buttons aren't working

### ISSUE THREAD

**Issue by kayrugold** [photopea/photopea#6002]
Your Operating System: Android Note 20
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open an image. 
3. Click Image > Image Size
4. Click Account Button
5.  Click Image > Canvas Size
6. Nothing happens.

**Comment by kayrugold** [comment]
Click File > New
Nothing happens

**Comment by bsviatun** [comment]
The same problems

**Comment by kristianbro** [comment]
The same 
Chrome Version 116.0.5845.180 (Official Build) (64-bit)

**Comment by photopea** [comment]
We had a little bug, which lasted for 5 minutes. If you opened Photopea during these 5 minutes, your version is broken. Could you reload Photopea (while clearing the cache), or reload it in an hour (our cache lasts for 1 hour)?
