### ISSUE TITLE
Some (A lot of) Buttons are not working anymore (Export, Selection etc...)

### ISSUE THREAD

**Issue by Funkix6** [photopea/photopea#6003]
Your Operating System: Windows 11
Your Web Browser: Firefox / MS Edge
The problem happens in the Incognito Mode, too: YES

**This must be done to see the problem**
1. Go to www.photopea.com
2. Load any image
3. Export as...

**Comment by BELEN1984** [comment]
I have exactly the same problem. How can I solve it?

**Comment by photopea** [comment]
We had a little bug, which lasted for 5 minutes. If you opened Photopea during these 5 minutes, your version is broken. Could you reload Photopea (while clearing the cache), or reload it in an hour (our cache lasts for 1 hour)?

**Comment by BELEN1984** [comment]
Thank you for your quick action. 

 

Best regards 

 

cid:5EF51655-BD48-4216-AA73-62376B893E71

 

Belén Moreno 

Dpto. Gestión | Management Dept.
 ***@***.***> ***@***.***
Tel. +34 958 670 715

Bodega | Winery
Finca Peñas Prietas. Ctra. Graena - La Peza. 18517 Graena, Granada – Spain 

 <http://www.bodegasmunana.com/> www.bodegasmunana.com     

Este mensaje y sus archivos adjuntos van dirigidos exclusivamente a su destinatario, pudiendo contener información confidencial sometida a secreto profesional. No está permitida su reproducción o distribución sin la autorización expresa de AGRO SIERRA NEVADA S.L. Si usted no es el destinatario final por favor elimínelo e infórmenos por esta vía.De acuerdo con lo establecido en el Reglamento General de Protección de Datos 2016/679 (RGPD) y la Ley Orgánica 3/2018, de 5 de diciembre, de Protección de Datos Personales y Garantía de los Derechos Digitales, le informamos que trataremos sus datos personales con la finalidad de realizar la gestión de bodega, gestión administrativa, contable y fiscal, así como enviarle comunicaciones comerciales sobre nuestros productos y/o servicios. Los datos proporcionados se conservarán mientras se mantenga la relación comercial o durante los años necesarios para cumplir con las obligaciones legales. Los datos no se cederán a terceros salvo en los casos en que exista una obligación legal.Asimismo, le informamos de la posibilidad de ejercer los siguientes derechos sobre sus datos personales: derecho de acceso, rectificación, supresión u olvido, limitación, oposición, portabilidad y a retirar el consentimiento prestado.Para ello podrá enviar un email a:  ***@***.***> ***@***.*** Además, el interesado puede dirigirse a la Autoridad de Control en materia de Protección de Datos competente para obtener información adicional o presentar una reclamación.Si usted no desea recibir nuestra información, póngase en contacto con nosotros enviando un correo electrónico a la siguiente dirección:   ***@***.***> ***@***.*** 

Datos identificativos:

AGRO SIERRA NEVADA S.L, B93572865, FINCA PEÑAS PRIETAS, CARRETERA DE GRAENA-LA PEZA S/N - 18517 - CORTES Y GRAENA - GRANADA, 958670715

 

Antes de imprimir este e-mail piense bien si es necesario hacerlo.

 

De: Photopea ***@***.*** 
Enviado el: miércoles, 6 de septiembre de 2023 12:08
Para: photopea/photopea
CC: BELEN1984; Comment
Asunto: Re: [photopea/photopea] Some (A lot of) Buttons are not working anymore (Export, Selection etc...) (Issue #6003)

 

We had a little bug, which lasted for 5 minutes. If you opened Photopea during these 5 minutes, your version is broken. Could you reload Photopea (while clearing the cache), or reload it in an hour (our cache lasts for 1 hour)?
