### ISSUE TITLE
VGradientEditor is not defined

### ISSUE THREAD

**Issue by josephrocca** [photopea/photopea#6004]
Your Operating System: Ubuntu 22.04
Your Web Browser: Chrome (latest version as of writing)
The problem happens in the Incognito Mode, too: No, works fine in incognito

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open a PSD
3. Try to change the color of some text, or export as webp (and maybe others, haven't tested)

I get this error in console when I click either of those two buttons (text color picker, or export):

![image](https://github.com/photopea/photopea/assets/1167575/563c079e-fc1f-4957-8af8-a4952a460fc1)

Haven't chiseled down a minimal reproduction, above are just the steps that led to the error, may not even just be specific to PSDs. I don't have an ad blocker enabled. Just posting in case others run into this and this issue can help triangulate. Please if no other similar reports for a while. The one I was editing was created with Photopea, not photoshop, in case that matters.

Currently I can only use Photopea in incognito mode.

**Comment by flaneurette** [comment]
I have same issue.

```
pp.js:15682 Uncaught ReferenceError: VGradientEditor is not defined
    at jw.cf (pp.js:15682:268)
    at jw.abI (pp.js:15689:27)
    at ag._l (pp.js:15317:16)
    at bh.h (pp.js:10675:49)
    at fc.h (pp.js:10680:77)
    at fc.h (pp.js:10680:134)
    at b3.EH (pp.js:15635:79)
    at bh.h (pp.js:10675:49)
    at fc.h (pp.js:10680:77)
    at by.u0 (pp.js:10753:95)
```

**Comment by photopea** [comment]
We had a little bug, which lasted for 5 minutes. If you opened Photopea during these 5 minutes, your version is broken. Could you reload Photopea (while clearing the cache), or reload it in an hour (our cache lasts for 1 hour)?
