### ISSUE TITLE
Photopea issue with Select > Modify > (Expand, Border, Contract, Feather, Smooth)

### ISSUE THREAD

**Issue by DreamJoshGaming** [photopea/photopea#6006]
I can't click expand and others on modify tools when i was trying to use it. I already select with magic wand and trying to click the expand and others but it wont work and also i already try to refresh di photopea and restart the computer it is still the same.

Please fix this issue or bug.

Thanks!

**Comment by photopea** [comment]
We had a little bug, which lasted for 5 minutes. If you opened Photopea during these 5 minutes, your version is broken. Could you reload Photopea (while clearing the cache), or reload it in an hour (our cache lasts for 1 hour)?
