### ISSUE TITLE
cant save png

### ISSUE THREAD

**Issue by kellyboy5523** [photopea/photopea#6007]
good evening team i was wondering if i could have some help please im new to yourproduct but im trying to export and save the file as per instructions and safe it as a png but it wont resgester at all

**Comment by photopea** [comment]
We had a little bug, which lasted for 5 minutes. If you opened Photopea during these 5 minutes, your version is broken. Could you reload Photopea (while clearing the cache), or reload it in an hour (our cache lasts for 1 hour)?
