### ISSUE TITLE
Can't export layers

### ISSUE THREAD

**Issue by haizdesign** [photopea/photopea#6009]
Your Operating System: Windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: No

**Comment by photopea** [comment]
So it works correctly in the Incognito mode? That means, that you are using browser extensions, which break the functionality of Photopea.

**Comment by haizdesign** [comment]
Chrome has just updated and it is now working again thanks. It was working yesterday so May have been down to the pending browser update. RegardsStuartOn 6 Sep 2023, at 10:46 am, Photopea ***@***.***> wrote:﻿
So it works correctly in the Incognito mode? That means, that you are using browser extensions, which break the functionality of Photopea.
