### ISSUE TITLE
saving alert about leaving page

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#601]
![screen shot 2018-03-31 at 21 39 47](https://user-images.githubusercontent.com/3184228/38166908-1fb8588e-352c-11e8-9815-16b2eab89481.png)

**Comment by photopea** [comment]
Hi, are you using the up-to-date browser?

Do you see Yes here? https://www.photopea.com/willitwork/

**Comment by landsman** [comment]
Yes for what?
It's up-to-date Chrome.

**Comment by photopea** [comment]
It should say big "Yes" or "No" at the top

**Comment by landsman** [comment]
Yeah, there is big "Yes"

**Comment by photopea** [comment]
And what happens if you choose File - Save as PSD, or "Get PNG" in a Move tool? It must be the same.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
