### ISSUE TITLE
Can't export to PNG or other Filetypes

### ISSUE THREAD

**Issue by CBimberg** [photopea/photopea#6010]
Your Operating System: WIN 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. File
3. Export as
4. PNG

As you may see, nothing happens. In the past a new Window poped up an I could choose the quality of the PNG File.

**Comment by photopea** [comment]
We had a little bug, which lasted for 5 minutes. If you opened Photopea during these 5 minutes, your version is broken. Could you reload Photopea (while clearing the cache), or reload it in an hour (our cache lasts for 1 hour)?
