### ISSUE TITLE
Feature Request. Improve visibility of folder boundary border.

### ISSUE THREAD

**Issue by bluep55** [photopea/photopea#6012]
Would it be possible, for the benefit of aging eyes, to make a slight tweak to the visibility of the folder border in the layers panel.
In photoshop, on a dark theme, when dragging a layer into the folder, the border appears to be a lighter colour making it more visible and easier to see.
In Photopea, possibly make the border lighter in dark themes when dragging a layer into it.
Thanks.

![Folder borders](https://github.com/photopea/photopea/assets/118609932/8904189f-be36-41bd-9cbf-ee1c4c3ba522)

**Comment by photopea** [comment]
it should be fixed now. These borders should be drawn using a text color now.

**Comment by bluep55** [comment]
> it should be fixed now. These borders should be drawn using a text color now.

That is so much better. Thank you 👍.
