### ISSUE TITLE
Photopea stops responding after selecting Gradient Tool

### ISSUE THREAD

**Issue by KinoHimari** [photopea/photopea#6013]
After selecting Gradient Tool, Photopea suddenly stops responding, tools can be selected but everything else such as layers and the project itself can't be selected/moved.

**Comment by photopea** [comment]
I just tried it myself, and the gradient tool works fine in my case.

I think it happens only with specific files. Could you tell me exactly, what should I do after opening www.Photopea.com, to see the problem? (Maybe attach a file which I should open in Photopea).

**Comment by KinoHimari** [comment]
For my case (I did it on a new file so it's not file-specific), what I did (and what triggered the problem) is simply just opening Photopea, make a new project, select gradient tool and use it (Though also happened by just selecting the gradient tool)

https://github.com/photopea/photopea/assets/144415988/dd5dcdb3-3b7d-488e-b912-09eb8ad4d59f

**Comment by photopea** [comment]
After you create a new document, there are no layers on the right side (in the Layers panel).

I need you to answer several questions, which are in our "bug report" issue template. Could you report a new issue and start with that issue template, and answer all points in it?
