### ISSUE TITLE
Feature Request: Expand Mockup Generation Automation Script

### ISSUE THREAD

**Issue by Gebarx** [photopea/photopea#6016]
Hi, and thanks for this amazing program.

It would be great if in the Mockup Generation Automation script, besides the loop that changes the designs, there were two more loops, one for changing colors of smart object, and a third for changing psd mockups.

So, in that setup, you would load a set of mockups, a set of designs, and a set of color hex codes, and the script would cycle through all three, creating all possible combinations of mockups, colors and designs. Alternatively, you could give it a csv file with different smart object colors for different designs and different mockups, if you don't want the same colors for all.

In case you are not going to give a high priority to something like that, could you perhaps post the Mockup Generation Automation Script for us to try to build this?

Thanks again for your great work.

George

**Comment by photopea** [comment]
Hi, what is the Mockup Generation Automation script?

**Comment by lucadalli** [comment]
@Gebarx I've built this exact functionality using the Photopea API over at https://mockcity.com/

**Comment by Gebarx** [comment]
> Hi, what is the Mockup Generation Automation script?

The script that runs through File>Automate>Generate Mockups.

I thought that when you choose this menu command, some kind of script runs to generate the mockups. Am i mistaken?

**Comment by Gebarx** [comment]
> @Gebarx I've built this exact functionality using the Photopea API over at https://mockcity.com/

I have checked this out. It's a great site, but as far as I can tell, it doesn't do that.

You can load all your mockups, yes, and you can load all your designs, but in the case of t-shirts, for example, I don't see how you can change the color of the shirt. You can only change the color of a square area in front.

Your demo video shows the whole tee changing color, but I was only able to change the color of this square area. My files are PSDs with the t-shirt and a square area in front that is a smart object where the design goes. Also they allow you to change the color of the whole shirt through a complex structure of layers, but as I said, when I used them at your site, only the area in front changed color.

Also, when you make mockups for a specific brand (let's say Bella+Canvas 3001), printed through Printify, it is highly recommended that you use the color hex codes that Printify gives for each shirt color (and which in some cases are not even the same as the color codes that Bella+Canvas itself gives for the specific color -- they say that they have experimented and their codes give better results).

Your site does not allow the user to give color hex codes. And even if it did, you would have to change colors manually, the same way I do it now in Photopea. There isn't some kind of input that would allow me, along with the PSDs and the designs, to also give a set of specific colors and get all possible combinations of PSDs, designs and colors, or some of the possible combinations if you don't want all PSDs and designs in all possible colors. (For instance, if the shirt has a saying on it written with black letters, you don't want it in black color because the letters will not be visible.)

So, have I misunderstood something? Is this possible with mockcity?

**Comment by lucadalli** [comment]
@Gebarx Attached is a video showing the two ways to add a background color. You can add a background color to a particular design and you can also define a "Fallback background" for the SmartObject which is applied when a design background is not specified.

If instead of the entire shirt changing color you are only getting a colored square it means that the SmartObject inside your PSD template does not cover and clip to the shirt or you mistakenly uploaded a JPG template not a PSD template.

You can add the same PSD template multiple times and set a different "Fallback background" every time to have different colored shirts.

I encourage you to test with the free templates in the library.

https://github.com/photopea/photopea/assets/39853447/f1a5b515-c358-4d9d-ac0b-3f64df023a93

**Comment by Gebarx** [comment]
OK, I checked it out. First, you can indeed give the color hex code, so that's OK.

However, in my templates the smart object is confined in a rectangular area in front of the shirt, it does not extend to the whole shirt, as it obviously does in your templates. Mine can also change shirt color, but it seems that they use a different way of doing it.

It seems in your library templates the whole shirt is a smart object. Is the rectangular area for the design a smart object also?

Would it be possible to download one such template to see how it is structured?

Also, any thoughts on how I could make my templates like that? Would it work if I converted the whole shirt in my templates to smart object?

**Comment by lucadalli** [comment]
The structure is simple and the typical one found in most mockups. As you rightly mention yourself, the entire shirt must be a SmartObject.

**Comment by Gebarx** [comment]
I had to search a lot to find templates that allow you to change the shirt color (they are all JPGs of a specific color, and if you wanted more colors you had to buy more templates), and they were all as I have  described. I didn't find any where the whole shirt is a smart object.

So where can I find such templates?

**Comment by lucadalli** [comment]
Here's a list from where you can source PSD templates: https://printondemand.tools/mockups
You might need to modify the templates a bit for them to work well with Photopea, especially if they have displacement maps.

**Comment by Gebarx** [comment]
OK, thanks I'll check it out.

**Comment by photopea** [comment]
I am afraid that if we ask users to enter hex codes next to the images (in File - Automate - Generate Mockups), it will be confusing to everyone except of you. It is not clear what is a "color of a smart object", do you mean the Color Overlay - Layer Style?

Maybe variables can help you: https://www.photopea.com/learn/variables

**Comment by Gebarx** [comment]
Well, in your example PSD for the variables, the one with the countries, the background layer has a light blueish color.

Let's say that we wanted to change that color depending on the continent the country is in, so a different color for Europe, for America, etc., and feed this color through a csv the way we feed the flag images, the names, the texts. How would we go about it?

**Comment by photopea** [comment]
There can be  a variable for the visibility of a layer. So maybe add 200 backgrounds of a different color, and set their visibility according to variables.

**Comment by Gebarx** [comment]
OK. So there is no way we could have the automation mockup script to add the necessary loops?

**Comment by photopea** [comment]
What are "loops"? The Mockup Generator is a tool, in a window, with buttons. There are no loops.

Try the Live Messaging API: https://www.photopea.com/api/live . You can send Photopea scripts, which will e.g. change properties of a layer, etc. But you will have to do programming.

**Comment by Gebarx** [comment]
OK, thanks!

**Comment by photopea** [comment]
I will close it now.
