### ISSUE TITLE
Peadrive: empty Peadrive page & other issues

### ISSUE THREAD

**Issue by narfnarfson** [photopea/photopea#6017]
Your Operating System: MacOS 12.6.7 (21G651)
Your Web Browser: Firefox/Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com. Make sure you are NOT logged in
2. Open Peadrive (it will show a blank screen)
3. Now, log in (I have my account set up through Google, but i'm not sure if that matters)
4. Try to open the Peadrive page. It will still be blank. Clicking on Home or another sidemenu item and going back to Peadrive does not fix or refresh the Peadrive page.

The only way to fix it that I've found is to refresh the browser, which is a drag if you already have a new project (Or projects)open.

Suggestion: If not logged in, when opening the Peadrive page, prompt the user to log in to their account

---
Other peadrive issues:

- In the filebrowser, some icons are missing (Both in Firefox and in Chrome)
<img width="788" alt="Screenshot 2023-09-08 at 18 23 39" src="https://github.com/photopea/photopea/assets/144478971/93532d8d-f461-40c7-8c5d-00857b7b11fa">

- You can have folders, but you can't seem to move files to them folder. 
Workaround I found : Open the file, save it (a copy) in the folder you want, delete the original. Not exactly fun.

And related to that:
- If you try to be smart and rename a file to "Folder/Filename.PSD" it does in fact not move the file to that folder and If you try to open/delete or rename it it gives the following error: **Path invalid**. Hopefully it wasn't a file you needed. ;-)
<img width="503" alt="Screenshot 2023-09-08 at 18 27 05" src="https://github.com/photopea/photopea/assets/144478971/d471987c-e578-4f46-b668-b1c1d44e4885">

**Comment by photopea** [comment]
Hi, I just tried it, but the issue does not happen in my case :( after logging in, my Peadrive shows me my files (without doing anything). Did you do anything strange to your pea drive?

**Comment by photopea** [comment]
I have to close it because of lack of details.
