### ISSUE TITLE
Feature Request: Apply "Clipping Mask" on folders in the right click menu

### ISSUE THREAD

**Issue by TheIanKirby** [photopea/photopea#6019]
Is it possible for you to include the ability to apply a clipping mask on a folder, so I don't have to merge a folder into an object? When I draw a character with eyes, this will let me position the sclera to be partially cut to the head and position the iris separately to test and look for a desired eye pose.

**Comment by photopea** [comment]
sorry, it is not possible for a folder to be a clipping mask in a PSD file. Even if we did it somehow, these PSD files would not look right in other programs.
