### ISSUE TITLE
Photopea API Environment: `autosave: 0` should disable autosave

### ISSUE THREAD

**Issue by lucadalli** [photopea/photopea#6021]
Setting `autosave` to `0` currently makes Photopea attempt to save continuously. Instead it should disable autosave.

**Comment by photopea** [comment]
Are you talking about our API - the Environment? https://www.photopea.com/api/environment

What makes you think that 0 should disable autosave? Keeping it empty should disable autosave.

**Comment by lucadalli** [comment]
Now that I'm reconsidering it, I agree, autosave `0` should not disable autosave but only attempt to save once after every change. Right now setting `autosave` to `0` is very buggy and attempts to save multiple times after every change. This is only something that I noticed not that I am actually bothered by, I am not interested in using this feature.

However, my concern is this console output after a period of inactivity even when `autosave` is left empty (disabled).
```
95 'saving Layer 1.psd' 2101736
```
Is this something else that I am mistaking for autosave? I just realized that despite the message the PSD document is not saved so I think it might be something else. Is it saving the PSD in IndexedDB?

**Comment by photopea** [comment]
Please, read our manual! https://www.photopea.com/api/environment

If you set Autosave to 0, it means it will try to save a file (File - Save) zero seconds after opening the file, and then, each zero seconds after the previous autosave.

The Web Console is not a part of the interface of Photopea. I can not help you with it.

The "localsave" should prevent the user from saving a document into their computer, just like the manual says.

**Comment by lucadalli** [comment]
I have read the manual. I understand that the autosave value is simply the interval at which saves are triggered.
My point is that if the document is already saved and there are no changes, it is wasteful to save again. In the case of a SmartObject, the additional wasteful saves still cause an expensive update in the parent PSD so everything becomes very laggy.
I just wanted to bring this to your attention. I am not bothered by it because I do not intend to set `autosave` to `0`.

To clarify, this console output `95 'saving Layer 1.psd' 2101736` is produced by Photopea at `pp.js:15213` after a period of inactivity (even with autosave disabled) and I would like to understand what it is "saving". The reason I ask is because I have a rare bug in my application that uses the Photopea API that I think might be related to this save. On fresh load of a PSD in my application, I think I am finding old state from a previous session.

I tried having a look at `pp.js:15213` but code is obfuscated/minified so I have no clue.

If you cannot help clarify what that console output produced by Photopea means, feel free to close this issue.

**Comment by photopea** [comment]
If you dont like the mechanism of "autosave", you dont have to use it. As I said, you are not supposed to look into a web console to use Photopea. We do not promise anyone to deliver any useful information through the console.
