### ISSUE TITLE
Text box not containing text

### ISSUE THREAD

**Issue by Bella565** [photopea/photopea#6022]
Your Operating System: Windows 11
Your Web Browser: Photopea downloaded to desktop (also use it on chrome)
The problem happens in the Incognito Mode, too: yes

I sometimes like to create a text box to a desired size and type my wording in that. Usually it contains it and keeps it aligned to the size of the box I've created.

For some reason now when I type, it carries on past the box.
<img width="1051" alt="Photopea" src="https://github.com/photopea/photopea/assets/66624640/1fddc71b-4be7-49e8-91e4-ed2df12b0171">

Can you advise what's changed as its also happening on three other computers and also in Chrome, Incognito mode, Edge and also on the downloaded app.

Thanks!

**Comment by MichalSZZ** [comment]
Try to make some spaces between letters and paste screenshot here.

**Comment by bluep55** [comment]
This is how it is in Photoshop without spaces.
![Text Box](https://github.com/photopea/photopea/assets/118609932/15da64f7-d0b4-4996-ad10-e8757e95a6b7)

**Comment by Bella565** [comment]
Thanks for the reply all.

Unfortunately mine and my colleagues just carries on past the box. It's been absolutely fine up until a couple of weeks ago and we both have the same issue on different laptops and PCs and even on different browsers.

It doesn't matter if we put spaces in or not, it just carries on past the box space and it's driving us mad!

Anyone else have the same issue? Is there a setting I don't know about?

Thanks all 🙂

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bluep55** [comment]
It works ok for me using Photopea if there's at least one space in the line of text.

**Comment by photopea** [comment]
Sorry, Photopea can not break a single word into multiple lines, as Photoshop can.

*** a word is a sequence of letters without a space - it would be several words, if there were spaces between these letters.
