### ISSUE TITLE
Gradient Editor not linking with Swatches

### ISSUE THREAD

**Issue by SilverMetalSparrow** [photopea/photopea#6023]
<img width="891" alt="image" src="https://github.com/photopea/photopea/assets/144563631/f1562c8c-c6fe-4aa5-ba62-e7d77a5b5d8e">

As you can see in this image, the Purple custom swatch isn't linking with the gradient upon loading up Photopea. Before it used to now it's not. Do you have a solution on how to fix this?

**Comment by photopea** [comment]
I dont think there is any relation between the Swatches panel and the Gradient editor.

You have two colors in your gradient, which one of them is supposed to change?

**Comment by photopea** [comment]
I think I have fixed it.

**Comment by SilverMetalSparrow** [comment]
The black one is supposed to change

**Comment by photopea** [comment]
why the black and not the white?

**Comment by SilverMetalSparrow** [comment]
I'm guessing because it's the primary color of the gradient thingy.. though I can't be too sure.

**Comment by SilverMetalSparrow** [comment]
Can you just make it so that they link upon opening the site?

**Comment by photopea** [comment]
I think Photopea works as it should. You can learn how gradients work in Adobe Photoshop here: https://helpx.adobe.com/photoshop/using/gradients.html , Photopea works the same.

**Comment by photopea** [comment]
Ok I think I know what you mean. Photopea really worked differently than it used to. It was caused by our upgrade of the Gradient tool: https://twitter.com/photopeacom/status/1697976257873338373

Now, it should work as before.
