### ISSUE TITLE
Unable to see pattern overlay

### ISSUE THREAD

**Issue by g0ldenface** [photopea/photopea#6025]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. create a canvas
3. insert shape or photo
4. go to select
5. click all
6. go to edit
7. click define pattern
8. minimize page
9. click on file
10. select new
11. double click on layer
12. select blending options
13. select pattern overlay
14. select the pattern you saved earlier
15. that pattern does not get applied to the document

**Comment by photopea** [comment]
I just tried it. I can define a new pattern and use it in the Pattern Overlay layer style.

What happens between steps 8 and steps 9? After you minimize the page, do you open Photopea in a new tab, or you un-minimize it?

Could you maybe record a short video of what you are doing?

**Comment by photopea** [comment]
I have to close it because of lack of details.
