### ISSUE TITLE
CHDK LVDUMPIMG Format Support?

### ISSUE THREAD

**Issue by MissionCyberSpace** [photopea/photopea#6026]
Hello! I've been working with CHDK formats and I've realized that Photopea doesn't support the LVDUMPIMG format. This is a very useful image format for debugging and filming higher quality video on less capable old cameras.

The lvdump format consists of a small header described in chdkptp lua/lvutil.lua (https://app.assembla.com/spaces/chdkptp/subversion/source/HEAD/trunk/lua/lvutil.lua)
and then a series of frames, each preceded by the frame length. The frames are in the CHDK live view format, as described in CHDK core/live_view.h 
(https://github.com/DIYBookScanner/chdk/blob/master/chdk/core/live_view.h)

I've included an lvdump frame in its original format in a zip file and a PNG of how it's supposed to look like.
Hopefully it's not too complicated, because I personally have no idea how this works, haha! 

[CRW_0000..zip](https://github.com/photopea/photopea/files/12570022/CRW_0000.zip)
![image](https://github.com/photopea/photopea/assets/127822838/6b9a4efd-8d33-4271-bb09-d0f9cc95a85b)

**Comment by photopea** [comment]
I have implemented this format, you should be able to open your file in Photopea now. It opens at most one image out of the file.

I did not find any such files online. If you have any, and they don't work right, please, share them with me :)

**Comment by MissionCyberSpace** [comment]
Amazing! 😱 
So far, I tested the one I shared and it worked extremely well! This is simply insane! 😀 
However I did test an animated lvdump, which contains several frames. Photopea couldn't open it and had an error.
I'll attach that file here just in case. (GitHub uploading only limits to 25MB, but the Zip file is about 40MB, so I had to host it externally. [https://cdn.discordapp.com/attachments/1059707960433053886/1172327378018635837/CRW_0002100f.zip?ex=655fe9f3&is=654d74f3&hm=e6685f4328d57b70338fb6f7c7f98294ec092f95821fb72d357ad0ca63b0d311&](url))
I will also test some other lvdump images that only have a single frame just to see how well the single lvump implementation works! So far, this is impressive beyond all doubt, as Photopea is the only software that can import and work with lvdump files! 
😎👍

**Comment by photopea** [comment]
I think I have fixed it. You should be able to open your large file now, and frames will become layers. Then, you can simply press File - Export as - MP4, to export it all as an MP4 video :)

BTW. some frames seem to be "cut" horizontally. Could you send me a PNG of some frame, which Photopea decoded incorrectly?

**Comment by MissionCyberSpace** [comment]
Well, that was extremely quick! 😮 
They're supposed to be cut  horizontally. 😃 
Well, they're not actually supposed to, but they do unfortunately. This is not a Photopea issue. It's a CHDK thing. The camera and CHDK PTP can't be in sync, so because of bandwidth limitations, screen tearing occurs where you have a frame that lags behind and you get two frames where the top part is the 1st frame and the bottom part is the second frame. So while it shouldn't do that, it does, and the file is perfectly being read in Photopea, as that is what it contains. Screen tearing frames at times. 😁 
All I can say is wow! This is extremely rad! 😄

**Comment by photopea** [comment]
No problem :) 

Regular color images use 3 bytes per pixel, but this format uses 1 byte per pixel for the brightness (grayscale image), and 2 bytes for the color information of each four (horizontally) consecutive pixels. So these are still raw data in a way, but with a lossy compression of 1.5 bytes per pixel (or 4+2 bytes per 4 pixels). 2x less data in total.
