### ISSUE TITLE
Install Photopea button does not work

### ISSUE THREAD

**Issue by Ch3rryS8da** [photopea/photopea#6028]
Your Operating System: Windows
Your Web Browser: Opera gx
The problem happens in the Incognito Mode, too: (button does not exist on incognito)

**This must be done to see the problem**
1. Go to www.photopea.com
2. Click the "Install Photopea" button
3. does nothing

**Comment by photopea** [comment]
It seems like this feature does not work in Opera :( maybe try to install it in Chrome or in Edge.

**Comment by photopea** [comment]
Or you can ask the guy who made Opera to make it work.
