### ISSUE TITLE
Photopea

### ISSUE THREAD

**Issue by catressonine** [photopea/photopea#6029]
Your Operating System: Apple
Your Web Browser: Chrome, Safari
The problem happens in the Incognito Mode, too: I can't use the "Export As" command multiple times. To save the file under different names, I need to restart Photopea each time. How can I fix this?

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
I think it is because you told your web browser to not let any website store more than one file. Do you remember telling it your browser?

Could you try it again, and when the problem happens, could you take a screenshot and send it to us?

**Comment by klaslod** [comment]
Okay i dont mind photopea it's decent

**Comment by photopea** [comment]
I have to close it because the person stopped to respond.

**Comment by ratatuille** [comment]
haha
