### ISSUE TITLE
Remove BG

### ISSUE THREAD

**Issue by Pasyano** [photopea/photopea#6030]
Your Operating System: Windows
Your Web Browser: Chrome, Brave
The problem happens in the Incognito Mode, too: Remove BG is not removing anything. I've tried it a lot of times last night and today it's just saying _Loading..._ I deleted my extensions and nothing happens. same thing on my phone. Any solution to this?

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
This service is quite expensive (sometimes up to 1 USD per image - https://www.remove.bg/pricing), and we ran out of money. We pay our service provider for each image, but we offer it for free to our users.

It should work again in 8 hours from now.

BTW. are you paying for Photopea Premium? Would it be ok if we offere this service only to Premium users?

**Comment by Pasyano** [comment]
Hi! thanks for explaining and quick response. I thought it was a problem on my end. 

No, I dont use premium sorry i dont have money right now to support you. if it would only be available to premium users whats the difference between subscribing to photopea and remove.bg?

sorry for my english and thank you for taking time to respond.

**Comment by photopea** [comment]
At remove.bg, you can get 40 images for 9 USD (in a month). In Photopea, you can get the unlimited number of background removals for 8 USD in a month.

If you are not paying, would you like to watch a video ad (15 seconds) to be able to process one image for free? Would it be ok?

**Comment by Pasyano** [comment]
Oh, thanks. Yes, im ok with it.

**Comment by camoody1** [comment]
@photopea Check out this site:
https://removal.ai/pricing

It's much cheaper than the remove.bg pricing and the results seem to be about the same. Should save you a few hundred dollars per month.

**Comment by photopea** [comment]
Our current background removal is much cheaper than this: https://removal.ai/pricing

**Comment by camoody1** [comment]
I thought in another post that you said you used https://www.remove.bg/pricing ? This is twice the price of what I suggested.

**Comment by photopea** [comment]
When a person watches a video ad, we get paid about $0.0015. We really can not afford to pay 3 cents per image.

If only a user was willing to pay 50 cents. He could get 300 background removals for it, without watching 300 video ads.

**Comment by camoody1** [comment]
You must be using this pricing, not the other one I thought... https://rapidapi.com/api4ai-api4ai-default/api/background-removal4/pricing

**Comment by camoody1** [comment]
Here is the webpage for the company who actually provides the API - https://api4.ai/apis/bg-removal

There is a phone number at the bottom of the page. Perhaps they could help you get back up and running.

**Comment by foxepapa** [comment]
i use the premium photopea guys its worth to buy and it is not expensive we all should help photopea!!

**Comment by photopea** [comment]
Hi, it should be fixed now.
