### ISSUE TITLE
select---> subject doesn't work

### ISSUE THREAD

**Issue by Kymmarella** [photopea/photopea#6031]
Your Operating System: windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Since yesterday I have found two instruments not working. The first is the remove BG, which has already been reported, the second is the select---> subject. Here too the loaded text comes out but the subject selection does not take place.

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by camoody1** [comment]
Switch to removal.ai
It's cheaper than remove.bg by about half.

**Comment by photopea** [comment]
Hi, it should be fixed now.
