### ISSUE TITLE
my fonts are enabled for photopea but for some reason it says it is not... maybe it is because edge uploaded? (sorry for bad english btw)

### ISSUE THREAD

**Issue by Askovv** [photopea/photopea#6033]
Your Operating System: Windows 11 Pro
Your Web Browser: microsoft edge
The problem happens in the Incognito Mode, too: no, it doesnt

**This must be done to see the problem**
1. Go to www.photopea.com
2. Use the Text Tool
3. Select a carried font
4. ....

**Comment by Askovv** [comment]
i tried to insert it again and worked, idk why it stopped working so suddenly but at least now i know i can just insert it again and use it normally

**Comment by photopea** [comment]
Hi, what is a carried font? But I am glad it works, so I will close it now.
