### ISSUE TITLE
Feature Request : adding menu to show/hide mask

### ISSUE THREAD

**Issue by houssem-108** [photopea/photopea#6034]
I'm having issues using alt+click on the thumbnail of a raster mask to show/hide the mask, on windows/chrome it just works.
on linux/firefox the alt key is being intercepted by my desktop environment or something and the shortcut doesn't seem to work.

ideally i want to be able to show/hide the mask from this context menu

![image](https://github.com/photopea/photopea/assets/118318819/f39e9ca5-05d4-42b5-9752-339f1d6e66b1)

**Comment by photopea** [comment]
But the first option - "disable raster mask" - actually is disabling the effect of the mask (the layer will look as if there was no mask).

Also, the shortcut is Shift+click, not Alt+click.

**Comment by houssem-108** [comment]
I'm talking about showing/hiding the mask(Alt+click), different from enabling/disabling the mask effect (Shift+click).
i posted the image of the contextual menu hoping it can be extended to include a show/hide mask command.

**Comment by photopea** [comment]
Oh, that is called the "Mask view". After you select the layer in Layers, press Window - Channels, and enable the mask visibility (the eye icon). You can disable the RGB, to see only the mask.
