### ISSUE TITLE
remove background in photopea function stopped working

### ISSUE THREAD

**Issue by Pantyusha2002** [photopea/photopea#6036]
Your Operating System: Windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: remove background in photopea function stopped working

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by Phx-666** [comment]
Also Select/Subject doesn't work...

**Comment by photopea** [comment]
We are working on a fix. Please, try the Magic Cut until it is fixed: https://www.photopea.com/tuts/magic-cut-remove-image-background-online/
