### ISSUE TITLE
Feature request - Be able to reorganize swatches from folder

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6037]
It will be great to be able to move and reorganize the swatches, by moving around the squares, and being able to create folders with custom names
![image](https://github.com/photopea/photopea/assets/11801254/da81e32a-c70f-4899-b98f-dc4faf52cfc7)

**Comment by klaslod** [comment]
oh my god no one gives one

**Comment by TheRadicalDreamer** [comment]
This is really useful when you have to create projects for clients that have brand books or brand pallets.

**Comment by photopea** [comment]
It should be fixed now.

ACO files can have a hierarchy - files in folders, folders inside folders, empty folders, etc.  Photopea can detect this hierarchy in ACO files and save it back into an ACO file.

You can drag and drop items within a hirarchy now. Most of options are available at the right-click. The same hierarchy has been added to Gradients, too. We could probably add it to Brushes and other resources.

**Comment by camoody1** [comment]
> It should be fixed now.
> 
> ACO files can have a hierarchy - files in folders, folders inside folders, empty folders, etc. Photopea can detect this hierarchy in ACO files and save it back into an ACO file.
> 
> You can drag and drop items within a hirarchy now. Most of options are available at the right-click. The same hierarchy has been added to Gradients, too. We could probably add it to Brushes and other resources.

Adding this new option to brushes (and fonts, if possible) would be great. 👍🏼
