### ISSUE TITLE
I can't access photopea

### ISSUE THREAD

**Issue by thesuavestrategist** [photopea/photopea#6038]
Hello, I've been using photopea a lot to design for like posters and such and today, it asked me for some kind of privacy policy which I rejected all and when I tried to open the app again, it won't let me in and says that I have to go to right and "change consent" But I can't see and don't know where that button is? This is the first time happened to me. Please help
![Photopea issue](https://github.com/photopea/photopea/assets/144883280/cb8f9657-5c45-4fdd-b587-0bafd306741f)

**Comment by photopea** [comment]
Hi, where are you from? Are you from Canada?

**Comment by thesuavestrategist** [comment]
Yes I am. I'm not sure what's going on? I've reload the app many times, but
still nothing.

**Comment by camoody1** [comment]
> Hi, where are you from? Are you from Canada?

We have someone on Reddit with this same problem and they're also from Canada. 🤷🏽‍♂️

**Comment by photopea** [comment]
We are trying to fix it.

Meanwhile, press the lock icon (right next to "photopea.com" of your browser) and delete the cookies /website data. Then, the website will behave as if you opened it for the first time.

**Comment by thesuavestrategist** [comment]
Ok, I'll check it out. Thanks!

**Comment by photopea** [comment]
Just clear the website data as I told you and it will work.
