### ISSUE TITLE
brush tool and erase tool, when used the line is indented from my cursor

### ISSUE THREAD

**Issue by AkhileshArshad** [photopea/photopea#6043]
Your Operating System: Microsoft
Your Web Browser: Microsoft Edge
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Normally use the brush tool to draw

brush tool and erase tool, when used the line is indented from my cursor
![image](https://github.com/photopea/photopea/assets/112542754/21459de6-d74a-48d4-a974-2cd9452c471e)

**Comment by photopea** [comment]
Press Edit - Preferences, set Cursor Offset to zero. You probably changed it without knowing what it means. 

This is useful for touchscreen devices, when you want to "see what you paint" (otherwise, it is under your finger).
