### ISSUE TITLE
Feature Request: Auto crop and straighten multiple photos

### ISSUE THREAD

**Issue by zcraber** [photopea/photopea#6044]
Photoshop has an option to automate cropping and straightening multiple photos in a document at once. It will automatically detect the blank space and crop them accordingly. It would be great if you could implement this in Photopea. 

![image](https://github.com/photopea/photopea/assets/61133303/aeeae460-f04d-4cd8-b672-ca0477a3ad8b)

This is particularly useful when you've got a single scan with multiple photos and you want to crop and straighten them individually.

**Comment by Bangdwiog** [comment]
![springobjects](https://github.com/photopea/photopea/assets/140507370/f16aa7c6-8d41-4423-912f-9c41cb522b44)
![hoe_copper](https://github.com/photopea/photopea/assets/140507370/b9451faf-9d70-495c-b3a6-3f6b2e7de4b5)

**Comment by zcraber** [comment]
> ![springobjects](https://user-images.githubusercontent.com/140507370/269862447-f16aa7c6-8d41-4423-912f-9c41cb522b44.png) ![hoe_copper](https://user-images.githubusercontent.com/140507370/269863031-b9451faf-9d70-495c-b3a6-3f6b2e7de4b5.png)

What's this?

**Comment by camoody1** [comment]
> > ![springobjects](https://user-images.githubusercontent.com/140507370/269862447-f16aa7c6-8d41-4423-912f-9c41cb522b44.png) ![hoe_copper](https://user-images.githubusercontent.com/140507370/269863031-b9451faf-9d70-495c-b3a6-3f6b2e7de4b5.png)
> 
> What's this?

It appears to be a grid of small images.

**Comment by zcraber** [comment]
> 
> It appears to be a grid of small images.

What's the point of posting it here?

**Comment by camoody1** [comment]
> > It appears to be a grid of small images.
> 
> What's the point of posting it here?

It would seem the commenter lacks a certain amount of intellect. Perhaps he put all of his points into Stamina or Magic. 🤷🏽‍♂️

**Comment by photopea** [comment]
I have added this feature! It is under File - Automate -  Crop and Straighten Photos. 

I have tested it on photos attached below. It works much better than in Photoshop (results are "straighter", without any white borders). It also runs faster than Photoshop (cca 1 second to process a 30 MPx photo).

[jpg.zip](https://github.com/photopea/photopea/files/13302071/jpg.zip)

**Comment by zcraber** [comment]
@photopea It works great with white background. But it's not working for images with black background. I've attached a sample image. It'd be great if you could implement this.

[test.jpg](https://github-production-user-asset-6210df.s3.amazonaws.com/61133303/292632589-cde8fb53-9204-4c3b-8a49-becad0d15124.jpg)

**Comment by photopea** [comment]
honestly, I dont know how to make it with this kind of background :(
