### ISSUE TITLE
Copy merged does not work as expected

### ISSUE THREAD

**Issue by icaine** [photopea/photopea#6047]
Hi, when i want to quickly edit image (without saving/downloading) and then just paste it somewhere (e.g. twitter). I was told that with Edit > Copy Merged i can achieve that (but not in Firefox). But it seems that it doesn't work in any browser.

Your Operating System: win10
Your Web Browser: Firefox/Edge/Chrome
The problem happens in the Incognito Mode, too: idk

**This must be done to see the problem**
Steps:
0. Go to www.photopea.com (Edge/Chrome)
1. Drag/Drop a picture to Photopea
2. Add a rectangle
3. Select both layers
4. Edit > Copy merged
5. Clipboard contains no picture just text `lrs;0;[0,1]`

PS: i am not sure if step 3 is mandatory, but if yes, there should be also an option to do it without it - something like export to clipboard.

**Comment by photopea** [comment]
Did you make a selection? What is "add a rectangle"? You need to select some area before copying it, see https://www.photopea.com/learn/selections

**Comment by camoody1** [comment]
@icaine Before choosing Copy Merged, make sure you type CTRL-A to select the entire image. That always works for me.

**Comment by icaine** [comment]
Ah, i see. (By adding a rectangle i mean adding a shape so that there will be two layers)

After some testing, to make it work, a selection (e.g. ctrl+a) must be made and at least one layer must be selected.
With no layer selected it does nothing. 
While with specific layers selected it always copy all layers regardless.
This all is imho a bit counterintuitive.. First hint is that to find out how it (exactly) works one needs to do some testing.

I would suggest to alter how it works to:
- no selection = all selection
- no selected layer = all layers selected
- specific layers selected = only those layers are used

**Comment by camoody1** [comment]
> Ah, i see. (By adding a rectangle i mean adding a shape so that there will be two layers)
> 
> After some testing, to make it work, a selection (e.g. ctrl+a) must be made and at least one layer must be selected. With no layer selected it does nothing. While with specific layers selected it always copy all layers regardless. This all is imho a bit counterintuitive.. First hint is that to find out how it (exactly) works one needs to do some testing.
> 
> I would suggest to alter how it works to:
> 
> * no selection = all selection
> * no selected layer = all layers selected
> * specific layers selected = only those layers are used

I like this idea. It is a bit counterintuitive to click Copy Merge and nothing actually happens unless you've actually selected everything. It's kind of implied that everything will be selected when you click Copy Merge. 🤷🏽‍♂️

**Comment by photopea** [comment]
I have fixed the bug. You can do "copy merged" with no layers selected now.

**Comment by photopea** [comment]
In Photopea and Photoshop, when there is no selection, copy-paste works with layers (e.g. copying 5 layers from one document and pasting them into another document, similar to Duplicate Into).

**Comment by icaine** [comment]
I am just used to Affinity Photo, where there is `copy flattened` (also ctrl+shift+c) and it works with no selection:)

I've just tried the fix and it seems it works (with selection like ctrl+a).

But otherwise it still clunky (with no selection):
- if single pixel layer is selected, copy merged is disabled
- if multiple layers (even pixel) selected, it duplicates behaviour simple copy (ctrl+c)

**Comment by photopea** [comment]
I am so sorry, I did not expect that there are so many bugs. It is all fixed now:

"Copy Merged" works when:
- there is at least one document opened
- AND there is a selection in that opened document

**Comment by icaine** [comment]
Seems much better now, thank you! 

But i am still puzzled, why not allow it to work also without the selection? Imho most people will just do ctrl+a and ctrl+shift+c anyway..

**Comment by photopea** [comment]
There are plenty of things in Photopea which you can copy and paste (layers, paths, channels, text inside text layers, layer styles, ...). I think every user must know about selections. The selection must be present to tell Photopea you want to work with actual pixels.

**Comment by icaine** [comment]
I am sorry, maybe i am missing something, but doesn't `merged copy` copy everything across layers as pixels? Like it doesn't care what types of layers are present (or selected), it just takes them all. And the only thing that makes a difference is what area is selected. I mean, it's great for it to copy only the selected area if there is a selection (e.g. Affinity doesn't have this:), but it would also make sense for it to copy the whole area if there is no explicit selection. That way it wouldn't take away any functionality, on the contrary, it removes redundant step and helps the user to achieve his goal faster;)

**Comment by icaine** [comment]
Idk, have you asked those 5 millions or how many of them reported that copy merged worked the weird way it did?;) And there are actually 2 people in this thread who would appreciate this tiny QoL improvement;)
