### ISSUE TITLE
Magic Replace tool not working(

### ISSUE THREAD

**Issue by xyzzart** [photopea/photopea#6048]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by Kwasi-ai** [comment]
Magic Replace Tool crashed

**Comment by camoody1** [comment]
I haven't been able to use it for a couple of hours, now. I just get stuck at the Processing message.

**Comment by camoody1** [comment]
@Kwasi-ai It's working now. I just checked with the provider. Their side was down for awhile. It just recovered a few minutes ago. Try it again.

**Comment by photopea** [comment]
The Magic Replace works fine for me. We really need some steps, how to see a problem.

**Comment by camoody1** [comment]
> The Magic Replace works fine for me. We really need some steps, how to see a problem.

It works fine now. It was down on Dezgo's end for about an hour and a half. They talked about it being down on their Discord. Maybe you should talk to them and have them notify you when their systems go down. You can apologize, now.
![image](https://github.com/photopea/photopea/assets/73725653/59032df8-2df6-4f81-b103-9d1d5e3f7cc6)

**Comment by Kwasi-ai** [comment]
The Magic Replace Tool us now working for me

Sent from Yahoo Mail on Android 
 
  On Wed, Sep 20, 2023 at 4:26 AM, ***@***.***> wrote:   



The Magic Replace works fine for me. We really need some steps, how to see a problem.


It works fine now. It was down on Dezgo's end for about an hour and a half. They talked about it being down on their Discord. Maybe you should talk to them and have them notify you when their systems go down. You can apologize, now.
