### ISSUE TITLE
Tect

### ISSUE THREAD

**Issue by TruHrz** [photopea/photopea#6049]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....
When using the "text" Button thing, It only makes a square of [] and nothing else, i need help.

**Comment by camoody1** [comment]
You can drag the Text tool to create a large text box to type in. Make sure your font size is large enough to see on your canvas and isn't the same color as your background. If you're working on a really large image and you're only using a size 24 font, it may be too small for you to see.

**Comment by photopea** [comment]
You can learn how to make text here: https://www.photopea.com/learn/text . If you still have a problem, please describe it using the correct terminology :D I dont know what is the text button thing :D
