### ISSUE TITLE
Mouse sensitivity bug with gaming mouse 

### ISSUE THREAD

**Issue by AliArtWorks** [photopea/photopea#6052]
Your Operating System: windows 10 virtual machine
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: didnt test

**This must be done to see the problem**
1. Go to www.photopea.com
2. Use any brush based tool on any layer
3. You will notice a difference in sensitivity when you use brush
4. Thanks

**Comment by photopea** [comment]
What is the difference in sensitivity? Could you share a video or at least a screenshot? 800,000 people used Photopea in the last 24 hours and nobody reported such a problem.

**Comment by photopea** [comment]
I can not see any video. Could you open github in a web browser and reply there?

**Comment by photopea** [comment]
ok, great!
