### ISSUE TITLE
Photopea is not GDPR compliant

### ISSUE THREAD

**Issue by AngryAnonim** [photopea/photopea#6053]
https://gdpr.eu/cookies/ states that "To comply with the regulations governing cookies under the GDPR and the ePrivacy Directive you must: [...] Allow users to access your service even if they refuse to allow the use of certain cookies".
I went to www.photopea.com and when prompted for cookie consent, I clicked "Reject All" (like I always do) and the site refused to work after that, prompting me to "change consent".

**Comment by photopea** [comment]
Sadly, our ad provider does not provide any ads, which can run without cookies.

I think it is very unfair to allow some users not see ads, while others watch ads. What exactly would you suggest us to do? 

Currently, we get about 500x more money from a paying user than from a free user (who "makes us money" by watching ads). So if we make Photopea usable only after the payment within the EU, and 99% of our users leave (and the 1% will pay for Premium), we will start to make 5x more money. But our goal was always to serve as many people as possible.

**Comment by photopea** [comment]
I will close it now.

The truth is, that now, there is no ad technology, which offers profitable ads without the "cookie consent". If we are not allowed to ask people to allow cookies, and we must always serve everyone (who allows or not allows cookies), it is like asking a restaurant to serve everyone (who does or does not pay), and hoping they will leave us a "voluntary tip".
