### ISSUE TITLE
I cant "change consent"

### ISSUE THREAD

**Issue by Tyler108x** [photopea/photopea#6054]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Do literally anything

Simply put, that spot on the right "change consent"? Theres _nothing there_. I cant change it if theres nothing there. I tried to change my ad settings for that site (and trust me I thought at first that having to enable all that shit was sketch as fuuuuck), made sure I had no extensions running or adblock on antivirus programs (I didnt), and thats when I realized it meant the giant grey bar on the side, and, like I said before, I enabled anything the site/app should need to get that little change consent thingy through. No dice. I'm sure I'm just missing something obvious to the point that ill be mortified to find out what it was, but regardless im trying to get on, have no issue with ads, and precisely use photopea because it doesnt require payment.... but now I cant get on there..

![Screenshot (420)](https://github.com/photopea/photopea/assets/145607340/47983135-3e70-45d4-aea9-11bad2c58469)

**Comment by photopea** [comment]
our ad provider has a bug. It tells Photopea that the user refuses to watch ads, when the user is from Canada, without even asking the user.

I decided to allow everyone who refuses to see ads to still use Photopea, until this issue is fixed. So you should be able to use Photopea now.
