### ISSUE TITLE
Feature request: no padding around canvas area

### ISSUE THREAD

**Issue by dimateos** [photopea/photopea#6055]
Photopea is a godsent but I sometimes find myself confused with the padding around the canvas area. Everything has the same color so there is no difference between background of empty areas, side padding that may cover image areas and top padding (tab bar). For example:

Full image fitting inside the edition area.
![image](https://github.com/photopea/photopea/assets/26868611/9d5a2196-9175-4599-bf2f-70a85eaf260a)

Zoomed in the top falls outside, due to color of the top padding it be actually cropped.
![image](https://github.com/photopea/photopea/assets/26868611/511a6395-b1cc-4106-8ca0-c4b664409212)

Zoomed even more, now the same effect happens at the sides but worse.
![image](https://github.com/photopea/photopea/assets/26868611/98843f95-632c-4a6e-9657-81a7cb6ea3e4)

### Suggestion
Ideally just let the edition area fill ALL available space. I would even make the top bar invisible and leave the tabs floating.

If the padding has to stay, at least use a bit different shade from the background. Also the side padding seems too large, like 4 times the tab bar?

**Comment by photopea** [comment]
I think these bugs are caused by your browser extensions, which are modifying Photopea. Please, report only bugs which happen in Photopea. Not bugs which happen in Photopea which was modified by your browser extensions.

**Comment by dimateos** [comment]
You are totally right. At the time I only only disabled a few extensions for testing but not all. Indeed it was caused by some extension, sorry for the misleading report.

I guess the top bar using the same shade as the background still holds, but that alone is more understandable so I consider it a minor issue. Please feel free to close the issue at your discretion.

Thanks!

**Comment by photopea** [comment]
yes, I think it is easy to get used to the top bar. On the other hand, it is nice when you dont have too many stripes of a different color in the UI.
