### ISSUE TITLE
when I click somewhere, it is 5 cm higher than I wanted

### ISSUE THREAD

**Issue by jiridobesss** [photopea/photopea#6056]
when I click somewhere, it is 5 cm higher than I wanted

**Comment by camoody1** [comment]
Edit -> Preferences and set Cursor Offset to 0.

**Comment by photopea** [comment]
Also, whenever you want to use Photopea as if you have opened it for the first time in your life (i.e. make Photopea forget all the custom settings that you have set while using it), just clear all the website data, it helps! :)
