### ISSUE TITLE
Photopea keeps reloading huge amounts of old projects

### ISSUE THREAD

**Issue by Zzoopie** [photopea/photopea#6058]
I'm having an issue with Photopea reloading huge amounts of old projects including some that have not even been saved. I looked through other people who had this issue and decided to disable all my Chrome extensions which did not work. I completely restarted my computer, closed all the projects when I was able to, reloaded the site; and I also decided to install the app, but the same problem occurred every time I tried to make a new project. 
![the issue](https://github.com/photopea/photopea/assets/145822730/86851c8a-1bb7-465b-ae43-6229190bb5c1)

**Comment by camoody1** [comment]
Some things to try:
https://www.photopea.com/tuts/photopea-opens-up-old-files/

**Comment by photopea** [comment]
Yes, this article should help: https://www.photopea.com/tuts/photopea-opens-up-old-files/

**Comment by Zzoopie** [comment]
After deleting the cookies it seems like the problem has stopped, so thank you!! I would also like to say I'm not sure if my extensions were causing this problem since I opened the site with and without extensions and the same problem happened; but here are all the extensions I was using.
![extentions](https://github.com/photopea/photopea/assets/145822730/e9610196-730b-4ac9-982e-76e5d527a9a0)

**Comment by photopea** [comment]
Please, read the article. Your extensions are not making Photopea open old projects, they make Photopea unable to close the old projects. So when you close a project with the "X" button, some extension blocks it (the document disappears, but will be opened the next time you open Photopea, with or without extensions).

I think you should delete "Google Docs Offline", as I think it is a virus and not really from Google.
