### ISSUE TITLE
Feature - Buttons on swatches panels (create & delete folder/swatch)

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6061]
Photoshop swatches panel have 3 buttons:
![image](https://github.com/photopea/photopea/assets/11801254/b4334196-b590-4ec5-bc0c-1159e4119d39)

- Create a folder,
- Create a new swatch,
- Delete a swatch/folder

Can we have those 3 buttons?
And also the ability to rename folders?

**Comment by TheRadicalDreamer** [comment]
This is so useful, because clients can share you the swatch of their brand/project or you can create one group of swatches for different types of content within the same project.

**Comment by photopea** [comment]
It should be fixed now.

ACO files can have a hierarchy - files in folders, folders inside folders, empty folders, etc.  Photopea can detect this hierarchy in ACO files and save it back into an ACO file.

You can drag and drop items within a hirarchy now. Most of options are available at the right-click. The same hierarchy has been added to Gradients, too. We could probably add it to Brushes and other resources.
