### ISSUE TITLE
Photopea not opening psd files

### ISSUE THREAD

**Issue by Gdesigns1** [photopea/photopea#6062]
![Screenshot_20230925-065056](https://github.com/photopea/photopea/assets/145959334/390e9752-6926-44f7-9f7b-3cde2d6fa030)
Your Operating System: Andriod phone google pixel 3xl
Your Web Browser:chrome, brave, microsoft
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
I just tried to open a PSD file in Photopea in Chrome on my Android phone, and it works fine.

What web browser do you use? How large is your PSD file in Megabytes?

**Comment by Gdesigns1** [comment]
The file is 12megabites and i used the chrome browser, brave, and even
Microsoft edge but to no avail

**Comment by photopea** [comment]
Did you try to open other PSD files? Does the problem happen only with one specific PSD file?

**Comment by Gdesigns1** [comment]
Yes i have tried to open more than 4 psd files but none is working

**Comment by photopea** [comment]
Could you send one of them to support@photopea.com ?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
