### ISSUE TITLE
Perspective Warp Crop tool?

### ISSUE THREAD

**Issue by CxryzNFTs** [photopea/photopea#6063]
Hello,

I am wondering if there is a feature like the Perspective Warp Crop Tool in Photopea, like the one in Photoshop?

Here is a video of what I mean by that: https://www.youtube.com/shorts/-YVj9Cj-DbY

Thank you,
Jake

**Comment by photopea** [comment]
Also, it is not a "crop tool" - it only transforms a single layer.
