### ISSUE TITLE
Photopea doesn't work

### ISSUE THREAD

**Issue by catressonine** [photopea/photopea#6064]
Your Operating System: Mac
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: I can't zoom in and out, the curves doesn't work. This problem started around 12 am. I cleared the cache, but it didn't help. 

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
I just tried it and everything seems to work fine for me, Curves work fine, I can zoom with the Zoom tool. Did you try to close Photopea and open it up again?

**Comment by catressonine** [comment]
It works again, I didn't do anything. Thank you for your reply.

**Comment by catressonine** [comment]
No, it doesn't work, sorry. I restarted the computer and the program. None of the tools work. Any ideas? In the morning everything was fine, then it broke. Maybe I deleted something?

**Comment by catressonine** [comment]
I figured it out. I accidentally changed the file size and it became simply huge. Problem solved.

**Comment by photopea** [comment]
ok
