### ISSUE TITLE
Problem after Merge Layers in SVG icon

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#6065]
Operating System: Windows 10
Web Browser: Google Chrome 117.0.5938.92
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open this SVG.
![bx-x-circle](https://github.com/photopea/photopea/assets/6370548/4d2d8308-76c4-4da0-9d87-d77ec8a270f6)
(note: this is icon from https://boxicons.com/?query=x+circle)

3. Select both layers and select "Merge Layers" from context menu
4. Problem: Black cross black fill color disappears / is transparent (should stay black)
Screenshot of what I see after merge:
![image](https://github.com/photopea/photopea/assets/6370548/45fbf4b9-375b-4f72-a5b6-1dedf982c9c2)

**Comment by photopea** [comment]
I think it works as expected. The large black circle has the "Unite" boolean operation, and is painted on top of the cross. Then, the smaller circle has an "exclude" operation.

To do what you probably expect, rasterize layers (to work with raster data), or place the cross on top of the circle before merging.

You can learn more here: https://www.photopea.com/learn/vg-structure
