### ISSUE TITLE
can't export file as 300 dpi

### ISSUE THREAD

**Issue by jar2200** [photopea/photopea#6066]
I've tried creating a new project in 300dpi, changed the canvas size to 300dpi and changed the image size to 300dpi and every time I export as png or jpg, it gets exported in 72 dpi or 762 dpi.

**Comment by photopea** [comment]
What should I do to see this problem happen? I just tried to do it myself and I go the JPG of 300 DPI, everything works correctly.

**Comment by jar2200** [comment]
I was hoping you could tell me because I don't know what else to do to get it to export as 300dpi or what I am doing wrong. I've tried it with multiple images including ones I had previous success on and I still can't get it to come out as 300dpi. I tried for about a week strait before coming here.

**Comment by photopea** [comment]
It is very unclear to me what you did. Please, start a new issue with a template, and describe the exact steps, what should I do to see the problem.
