### ISSUE TITLE
Photopea doesn't show ads at all

### ISSUE THREAD

**Issue by Sitotato** [photopea/photopea#6067]
Photopea detects ad blocking, even though I have no extensions enabled at all. This issue occurs on every browser, including when using Incognito Mode. I never intend to block ads, and this problem only happens on this PC in specific. Is there a fix for this? I want to not only support Photopea but also use features that require me to watch ads.

Your Operating System: Windows 11 Home
Your Web Browser: Google Chrome/Any
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com on any browser, could be done in Incognito Mode. (Extensions disabled.)
2. Look at the right to see that the ads are blocked.

**Comment by photopea** [comment]
Did you try it in Edge or in Firefox?

It could be blocked by your employer or your school, etc. Could you e.g. start a wifi hotspot on your phone and connect to the internet through it? Or just connect using any different network.

**Comment by Sitotato** [comment]
Thanks for your response. I tried using it in Edge and Firefox, but neither showed any ads.

I tried using my phone's hotspot, but that also didn't fix the issue. I then tried using a different available network, which unfortunately also didn't fix it.

**Comment by photopea** [comment]
Could you send me a screenshot of what Photopea.com looks like in your case? Could you also send me a screenshot of "about://extensions" in your case?

**Comment by Sitotato** [comment]
Here is the screenshot, with the pages next to each other. According to Google, the extensions are turned off.
![Schermafbeelding 2023-09-28 161250](https://github.com/photopea/photopea/assets/146284536/f206ef20-b838-4883-8aa7-d9e841b57cfd)

**Comment by photopea** [comment]
Can you open these files, or is your internet provider blocking them?
https://cmp.uniconsent.com/v2/85d3b9563e/cmp.js
https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js

Do you have any software on your device, which performs censorship or web traffic monitoring?

**Comment by Sitotato** [comment]
When opening the first one, I see a string of text:
![image](https://github.com/photopea/photopea/assets/146284536/aee4f7a1-dec5-436d-b224-d671540bf637)

When opening the second one, I get an error page:
![image](https://github.com/photopea/photopea/assets/146284536/1f34b523-ee85-4c71-bbd3-759b368b0251)

However, when opening with my laptop, a file named "f.txt" is downloaded, which contains a large amount of text.

**Comment by photopea** [comment]
The second link is a regular web address, that should be openable from any device connected to the internet.

Do you know who and why is blocking this address? Did you install any software into your device to censor the web traffic (decide for you what should be accessible and what should be not accessible)?

**Comment by Sitotato** [comment]
Good news! The issue seems to be resolved! ChatGPT adviced me to change my DNS settings. I did this and the Photopea site allowed me to turn on ads! For anyone who has the same issue, here are the steps ChatGPT gave me for Windows users:

1. Open Network and Sharing Center:
- Click on the Windows Start button.
- Type "Control Panel" and press Enter.
- In Control Panel, go to "Network and Sharing Center."

2. Change Adapter Settings:
- Click on "Change adapter settings" on the left sidebar.

3. Select Your Network Connection:
- Right-click on the network connection you're currently using (e.g., Ethernet or Wi-Fi).
- Select "Properties."

4. Change DNS Settings:
- In the Properties window, scroll down and find "Internet Protocol Version 4 (TCP/IPv4)" or "Internet Protocol Version 6 (TCP/IPv6)" depending on your connection.
- Select it and click on the "Properties" button.

5. Set DNS Servers:
- In the properties window, select "Use the following DNS server addresses."
- For Google DNS, use the following DNS server addresses:

Preferred DNS server: 8.8.8.8
Alternate DNS server: 8.8.4.4

- For Cloudflare DNS, use the following DNS server addresses:

Preferred DNS server: 1.1.1.1
Alternate DNS server: 1.0.0.1

6. Save Changes:
- Click "OK" to save your changes.
- Close all the windows.

I hope this helps other users that are facing the same issue. Thanks for your support and for making Photopea.

**Comment by photopea** [comment]
What DNS server did you use before that? How did you find that DNS server?

**Comment by Sitotato** [comment]
It was set to "Obtain DNS server address automatically", so I didn't pick one specifically.
I don't know what DNS server adresses do, but somehow the ads are showing up again.

**Comment by photopea** [comment]
You send a DNS server the domain, like google.com or GitHub.com, and the
DNS server tells you which computer (out of billions of computers connected
to the internet) corresponds to that domain. It can also block domains by
telling you that such domain does not exist.

All DNS servers of the internet should work the same. You found one that
does not :D

**Comment by Sitotato** [comment]
Quite fascinating; I suppose we learn something new every day! :)

**Comment by photopea** [comment]
Your screnshot literally says, that the DNS probe was finished, and it is NXDOMAIN (non-existing domain) - that is what the DNS server says. But this domain does exist, you just have to ask a different DNS server :)
![image (4)](https://github.com/photopea/photopea/assets/15955558/bd137c12-5d21-459a-b2b7-080328d29e88)

**Comment by Sitotato** [comment]
I see now, that makes a lot of sense! :)
