### ISSUE TITLE
Magic Replace/Remove Not Working! 

### ISSUE THREAD

**Issue by doyoudesignstudio** [photopea/photopea#6068]
Your Operating System: Windows 10
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Yes 

Here is a video below of the problem with the Magic Erase Tool. I also followed your step by step written instructions and still didn't work. I also have a friend who also says she tried to use the tool on her computer and couldn't either. 

I hope this can be resolved soon. I did buy the photopea membership so I have supported you, I really hope you can support me by fixing this error. I really needed for my small business. 

Thank you in advance for taking a look at this. 

Kimberly 
doyoudesignstudio@gmail.com 

https://drive.google.com/file/d/18TOppsuV0h86bv2btU2u7b-KlxcLWrez/view?usp=sharing)

at the end of video it got cut off but I was saying it goes back to the image not being removed.

**Comment by camoody1** [comment]
Just as a note: The Replace, Unite, Subtract and Unite buttons that you're referring to for the tool have no impact on the Magic Replace tool itself. Those options are simply there to help you make your selection with the selection tool before clicking either Remove or Replace.

What exactly were you trying to remove in your video? You have a large image with a nice bag and fall decorations and you've drawn a large rectangle shape over top of it. Then, you hit Remove. What exactly are you trying to achieve? In general, the way you use the Magic Replace tool is to make a selection (either with the Magic Replace tool itself or any other selection tool) around some subject or small error in your image that you want to remove or replace, and then use the tool to do that. You've drawn a shape seemingly randomly and then hit Remove. 🤷🏽‍♂️ I can't see the rest of your screen to see how you have your layers setup to be certain what's happening, but my gut is telling me that you're just misunderstanding how the tool is supposed to work.

I can assure you that the Remove and Replace functionality definitely works as I just tested it myself.

Hopefully, we can figure out what you're trying to achieve and help you get there. 👍🏽

**Comment by photopea** [comment]
I think you are confusing [Selections](https://www.photopea.com/learn/selections) with [Vector Shapes](https://www.photopea.com/learn/vector-graphics) . Plese, read both articles. You can also get a book about Adobe Photoshop to learn how these tools work.

You can use this tutorial to learn how to use the Magic Replace tool: https://www.youtube.com/watch?v=X_jRqH0eKtE  - note, they dont do any "no fill", there are no blue contours as you have.
