### ISSUE TITLE
Saved PSD from Google Drive shared folder shortcut are being duplicated

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6069]
Your Operating System: chromeOS
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open a file from google drive. That PSD has to be from a shortcut on your root folder, from a shared folder 
3. Modify it and save it.
4. The file will be correctly modified

The issue is:
Now i have a duplicated file in my root folder as well.

Check the video:
https://screencast.apps.chrome/1POGZTK3m-GpNhWZGe0AKggBLPrsi5xJ8?createdTime=2023-09-28T04%3A42%3A50.810Z

**Comment by TheRadicalDreamer** [comment]
This totally has something to do with https://github.com/photopea/photopea/issues/6000

I still cannot see folder's shortcut (i don't know if it is intended or not)
![image](https://github.com/photopea/photopea/assets/11801254/ad0c37b0-58a8-42c9-8041-c4fe8ef75c5e)

Also i believe it is a good idea to have all the Google drives services as one with sub--folders

**Comment by photopea** [comment]
At first, I thought that your report is about the Storages on the left side.

What exactly is a step 2? Did you press File - Open in your video? When I press File - Open on Windows, I do not have access to Google Drive. So this is pecific only to Chromebooks?

**Comment by TheRadicalDreamer** [comment]
another video:
https://screencast.apps.chrome/1REssvHKJ2PuwTuRNhPvrbRoZ-eCkVwmc?createdTime=2023-10-02T16%3A06%3A42.580Z

I have a shared folder, and i created a shortcut to it, to be able to have it displayed in my root folder
![image](https://github.com/photopea/photopea/assets/11801254/ee75ff89-48a5-46c0-91f9-bde5f2174946)
(you can do that to any shared folder from the dropdown menu > Organize > Add shortcut)

I opened a file from that folder from my local storage, this because i have the google drive extension installed, so i can access my google drive files locally. Chromebooks have this by default, but you can also have this on Windows, MacOS and other Linux distros.

I open the file, modify it, save it. It saves correctly, but also creates a copy of the file on my root folder. This is the issue.

**Comment by photopea** [comment]
I think this could be a bug in Chrome OS or in your extension. Could you describe steps, which I can repeat on Windows?

Can you reproduce it e.g. with "Storages" on the left side of Photopea? See https://www.photopea.com/learn/storages

**Comment by TheRadicalDreamer** [comment]
![image](https://github.com/photopea/photopea/assets/11801254/878a71f1-b7f3-4f90-b0ec-eee768e37e79)


It is supposed to be here, in configurations. That you can download the app that let you synchronize your files locally.

After that, you need someone to share you a folder and you have to add it as a shortcut to your root folder.

Then you should be able to open a PSD file located inside that folder, from the open locally on Photopea. When you save, you should get a copy of the file on the root folder.

Hope that helps, tell me if you need more explanations.

I cannot reproduce this bug if i open the "storages". Maybe it is related with the fact that the shortcut folder is not visible from my root folder on Photopea

**Comment by photopea** [comment]
Right now, Photopea asks your computer to give it a file. Then, Photopea asks your computer to replace that file with a new version of the file. Everything else is up to your computer (Photopea does not know if the file came from Google Drive, or an SD card, or a Hard Drive, etc.). So even if I can reproduce it, I can not fix it - it is a bug in your chromebook, you should report it to the creators of your chromebook.

**Comment by photopea** [comment]
cool! :)
