### ISSUE TITLE
CANNOT move layers, shapes and folders

### ISSUE THREAD

**Issue by Poinet** [photopea/photopea#6070]
Your Operating System: Android  (8.0.0)
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Literally load any project
3. Literally just try to select layers (by holding on it), it should show menu but would be able to move it while showing menu at same time
4. Now you can't move layers in newer version.

I have tried it on many other browsers, resetting caches, resetting device, resetting cookie, everything. Still doesn't work.

I assume that you have updated the website version which leads to this bug.

**Comment by photopea** [comment]
I do not understand the third step, what is "select layers by holding on it, it should show menu" - what menu? 

I can move layers with the Move tool.

**Comment by Poinet** [comment]
Oh my bad, I mean like changing orders of layers.
I can't move the order of layers to top from bottom or bottom from top.

When you hold on the layer, the menu would show up, but you were also able to move the order of layers while the menu was showing up (another small visual bug)

but now I can't completely move the order of layers.

**Comment by photopea** [comment]
Do you mean the Layers panel with a list of layers? Are you using a touchscreen? Is it an iPhone or Android? Did it ever work differently in your case on your device?

**Comment by Poinet** [comment]
Yeah and yes I'm using touchscreen, its obviously android, tablet.


Yes it has ever worked ever in my case before the latest version that caused the bug.

**Comment by photopea** [comment]
latest version of what?

**Comment by Poinet** [comment]
Of website, I thought you updated it. Just my assumption.

If you didn't update the website then I guess that doesn't really matter anyway.

**Comment by photopea** [comment]
What web browser do you use? Could you try a different web browser? 

When I open www.Photopea.com in Chrome for Android, I can drag and reorder layers in the Layers panel.

**Comment by camoody1** [comment]
Reordering the layers panels works for me, too, in Microsoft Edge on my Android phone.

**Comment by Poinet** [comment]
I use Brave, I have tried it on other browsers, even chrome, it doesn't work.

Here's a video:
https://github.com/photopea/photopea/assets/60430380/d2d2c969-b438-44ae-95e0-8f18ab8dd0ac

**Comment by photopea** [comment]
What version of Android do you use? I think it worked wrong in the old
Android.

**Comment by Poinet** [comment]
8.0.0

**Comment by photopea** [comment]
Can you update it? I also have this big on my old Android phone.

**Comment by Poinet** [comment]
Oh well unfortunately I can't update my current android version

**Comment by photopea** [comment]
I am afraid I can not help you. Only Google can fix it in their Chrome browser.

**Comment by Poinet** [comment]
I mean I am using brave as the main browser.
It has worked for me before the bug occurs.

I think you don't need to fix a bug, you just need to find way to implement the system that mobile users can use.

**Comment by camoody1** [comment]
@Poinet Photopea works fine on updated Android devices. I use it on my phone all the time.

**Comment by photopea** [comment]
To reorder layers (put one above / below another), you can select the layer in the Layers panel, and press Layer - Arrange - Move Forward / Backward.

**Comment by Poinet** [comment]
Honestly, that's not very effective way to arrange, I want something that allows me to drag rather than having to manually take many steps just to arrange layers.

Well, even I can't put the layers on folder (arrange from the folder to another folder) using this feature you suggested.

Is there way you could do to implement a way for us to drag the layers in order to arrange just like before the bug occurred. (same way pc users drag)

**Comment by photopea** [comment]
We did not change the way the Layers menu work in years. It must be something on your side.

We can not create a separate version of Photopea for each operating system, to overcome its bugs. The current version of Photopea works perfectly in modern Android.

You can try to convince Google to fix this bug in Android, or buy a new device with a newer Android.

**Comment by Poinet** [comment]
I see! I tried my other phone with modern Android and it seems that it worked perfect.

You're right that it must be something on my side. I guess I can try convince Google to fix it.


By the way, you should add a way for me to arrange layers from the folder to another folder (a feature suggestion) since there is no way for me to use Layer Panel > Arrange feature to arrange these layers from different folders.
