### ISSUE TITLE
Magic Replace Tool Currently Down

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#6071]
Your Operating System: Windows 11
Your Web Browser: Microsoft Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Attempt to use the Magic Replace Tool to either Replace or Remove anything.
3. Photopea displays a "Processing..." message that never goes away.

This is being reported by multiple users on Reddit, now. I can confirm that it is not working. No one on the Dezgo Discord is reporting a similar issue and I am able to process images directly on the Dezgo website. So, this appears to be an issue with Photopea tonight and not Dezgo as a provider. I left messages with my Dezgo contacts on the Discord server, but they're both offline until morning in France, I assume.

I first noticed this issue at approximately 10:00pm ESDT (New York time zone).

**Comment by blues034** [comment]
I also encountered this problem, last night was still normal, there is an official to reply

**Comment by camoody1** [comment]
@photopea I spoke with Clem on their Discord. He found the issue. Your API key expired earlier tonight. Oops. You'll need to contact them for a new key and update it in your code.

Good morning :)

**Comment by camoody1** [comment]
@photopea Update from Clem...

>[2:12 AM] Clem: I just edited the API key to expire on 9999-31-12 btw
>[2:12 AM] Clem: Once the cache reload it should fix the problem

So, maybe you won't have to do anything to fix it, afterall.

**Comment by camoody1** [comment]
And it's now working, again. 👍🏽

Looks like Clem took care of it.

Have a good Friday, sir.

**Comment by photopea** [comment]
I had no idea that an API key might expire. I will get in touch with Clem. Thank you for fixing it without me (by asking Clem to fix it), you are amazing! :)

**Comment by camoody1** [comment]
@photopea He said they normally don't. He wasn't sure why the Photopea one had an expiration. He said he'd been talking to you recently about API security and thought maybe you had changed something. But he wanted to get you back up and running fast, so he extended the expiration. I'm guessing you can just leave it there if you don't want it to expire. 🤷🏽‍♂️
