### ISSUE TITLE
Nothing appears to happen when clicking "Show short" when using Magic Replace tool

### ISSUE THREAD

**Issue by kiiboen** [photopea/photopea#6072]
Your Operating System: Windows 10
Your Web Browser: Firefox 118.0
The problem happens in the Incognito Mode, too: Yes.

**This must be done to see the problem**
1. Go to www.photopea.com.
2. Open any image and try to use "Magic Replace" on it.
3. Click "OK" when it asks if you want to watch a short to use the tool without making a premium account.
4. Nothing shows up. Nothing changes visually.

Maybe it's just my bad Wi-Fi, I don't know. I have my Ad-blocker turned off on Photopea, so I can see banner ads just fine.

**Comment by ronaldafrica** [comment]
I have exactly the same problem (( 
![1](https://github.com/photopea/photopea/assets/146488698/d18e0ba6-c5bd-440d-a769-d22153ab5159)
![2](https://github.com/photopea/photopea/assets/146488698/df595fcf-4d33-4e62-bda9-44c956650e10)

**Comment by photopea** [comment]
Do you use any ad blockers? Could you try to turn them off? You can not see ads if you are using ad blockers.

**Comment by ronaldafrica** [comment]
Ad-blocker turned off

**Comment by photopea** [comment]
Can you turn off all your browser extensions and try Photopea again?

Is it Chrome? Open Photopea and click the "puzzle piece icon" at the top right corner and show us a screnshot of what you see there.

**Comment by ronaldafrica** [comment]
Yes, Chrome. No "puzzle piece icon"
![1](https://github.com/photopea/photopea/assets/146488698/2f9abedc-5b54-4075-a9ab-a4d83122040a)
![2](https://github.com/photopea/photopea/assets/146488698/a455c59e-fa4f-4be2-912d-1e6368602d96)

**Comment by photopea** [comment]
Could you share a screenshot of your whole screen?

**Comment by ronaldafrica** [comment]
![3](https://github.com/photopea/photopea/assets/146488698/c5f4b766-2698-4899-92aa-c0ed180cc770)

**Comment by photopea** [comment]
What version of Chrome is this? Also, if you go to "about://extensions", can you share a screenshot of what you see?

**Comment by MichalSZZ** [comment]
Do I see Windows Vista here? Maybe that's the problem... on the old OS some browser can't work as good as on the supported OS with updates.

**Comment by ronaldafrica** [comment]
Chrome:  109.0.5414.120
Windows 7
![jdfme](https://github.com/photopea/photopea/assets/146488698/1ed8029a-6116-47f7-af45-7d8eaf7602fa)

**Comment by photopea** [comment]
Can you access these addresses from your browser?
https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
https://cmp.uniconsent.com/v2/85d3b9563e/cmp.js

Do you connect through some element or an entity (firewall, VPN ...) which could be blocking ads?

**Comment by ronaldafrica** [comment]
https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js               NOPE
https://cmp.uniconsent.com/v2/85d3b9563e/cmp.js         YES (CODES)
NO VPN...

**Comment by photopea** [comment]
Who is your internet provider? Can you ask them why do they block this link? 

https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js

Are you from Russia? Do you think your government could be blocking it? Can you open this link on other devices?

**Comment by ronaldafrica** [comment]
I'm from Russia. The link does not open ((  Don’t know if the government can block it. Can I use a time limit like a couple of days ago?

**Comment by photopea** [comment]
Could you connect through a different network? Or try a hotspot on your phone? You can try to change your DNS server to a different one.

We can not provide this feature for freee anymore, we were spending too much money on it :(

**Comment by ronaldafrica** [comment]
Why do others use time limit, but I can’t?
