### ISSUE TITLE
(Suggestion) A Metallic Effect in Layer Style.

### ISSUE THREAD

**Issue by MesaBlack** [photopea/photopea#6073]
works in both beveled and non-beveled.

**Comment by camoody1** [comment]
There are many Layer Styles online that have metallic effects. Just do a Google search for "free photoshop metallic layer style", download one you like, install it in Photopea and have fun.

**Comment by MesaBlack** [comment]
now, how do you install it in and find it?

**Comment by camoody1** [comment]
Have you actually tried figuring this out yourself? Maybe researched a little about Layer Styles? Maybe tried entering the exact phrase I told you to search? Maybe also search for "Photopea Layer Styles"?

I've led you to water. It's up to you to start drinking. :)

**Comment by photopea** [comment]
Please, read the article which I wrote for you: https://www.photopea.com/learn/layer-styles

**Comment by MesaBlack** [comment]
> Have you actually tried figuring this out yourself? 
Yep!

> I've led you to water. It's up to you to start drinking. :)
???
