### ISSUE TITLE
Simplifying ground-level Subtract Path changes combination to Exclude

### ISSUE THREAD

**Issue by xilehence** [photopea/photopea#6074]
If the Path around a filled Shape is selected (with Path Select tool) and combination changed (from default Unite) to Subtract, the fill is applied to the background (outside the Shape) instead of the foreground (inside the Shape). I can _almost_ understand this, even though it violates my understanding of the semantics of the Boolean operations. However, if the Path is then simplified, the mode changes to Exclude, and the fill “polarity” goes back to “normal.” I think that must be a bug, especially since extending a Shape with a new Path that is merged with original into a single Path doesn’t show the same behavior.

**Comment by photopea** [comment]
Could you check how it works in Adobe Photoshop? I think we made this mechanism correspond to Photoshop.

**Comment by xilehence** [comment]
Hi, Ivan.

Sorry: i don’t have Photoshop. (One reason [but not the only one!] that we use Photopea!)

I admit that this is an obscure issue that probably no one will care about
(but it’s still kind of interesting).

But i still can’t test on Adobe Ps “gold standard” or “ground truth” or however you think of it.

**Comment by photopea** [comment]
I think this is how Adobe Photoshop renders vector paths in PSD files, and I think we should render PSD files the same way.
