### ISSUE TITLE
Refine Edge Tool not generating an edge on entire lab of computers

### ISSUE THREAD

**Issue by mrbaj100** [photopea/photopea#6075]
Windows 10 and 11 / Chrome OS / iOS 17 running Chrome
Chrome and Edge
The problem happens in the Incognito Mode, too:  Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Select an image with a solid background and foreground subject
3. Use the magic wand to select the background and select the inverse to select the subject
4. Select the refine edge tool
5. At this point I am getting no gray edge between the selection. The border tool makes no changes. there is effectively no border and no edge is being refined. Please see the attached image. This is happening on all of the computers in my lab. Also happening on an iPhone 13 running Google Chrome.

![Refine Edge issue](https://github.com/photopea/photopea/assets/146744054/833449bb-21f5-4648-aa7e-e7f6f6011219)

**Comment by photopea** [comment]
Seems like it has been broken for several months, but nobody reported it :(

I just fixed it, thanks for your report!
