### ISSUE TITLE
Error October 6, 2023

### ISSUE THREAD

**Issue by Kourt32** [photopea/photopea#6081]
Whenever I open the Photopea app or use the site online, I get an error code "Needs More Ram 434." I am enough storage on my device (it has been wiped clean). What do I need to do?

**Comment by photopea** [comment]
I think you have browser extensions which break Photopea. Did Photopea ever opened old files, which you have closed? See this: https://www.photopea.com/tuts/photopea-opens-up-old-files/

**Comment by Kourt32** [comment]
Yes it would open the old files, then as soon as I click anything, like the T to add text or try to move something around on the design, it instantly freezes up and say need more ram with a different number each time. Whenever I try to create a new document, once i chose a size, it freezes for a second, opens the blank document, and once again when I try to add anything to it, it says needs more ram again. It worked fine Thursday, it just crashed alot, and all day yesterday, I dealt with this issue and I need this software BAD.

**Comment by Kourt32** [comment]
Yes it would open old files, with no issues all up until yesterday. As soon as I open the blank document, and click to add text or move anything around on the design, the error needs more ram pops up with different numbers. It worked fine all day Thursday, but as of yesterday, I have not been able to do anything. I have tried it all of my devices in my household, it does the same thing on all of them, and I really need this software BAD.

**Comment by photopea** [comment]
So it opens your old files on all devices in your household? That is really strange.

**Comment by Kourt32** [comment]
It would open the old files, but as soon as I try to make a change like move an object around, or even add something to it like text or anything else, it freezes up, and then says needs more ram. The only way I have it somewhat working now is by have the resolution low on 72-100. I thought it was maybe my chromebook so I used my desktop to create my new design, it did the same thing, I used 2 more laptops I have have in the house, same error (needs more ram), even my cell phone got the same error. I don't know what to do. I've been using Photopea for the last 3 years, and I have never had this problem.

**Comment by photopea** [comment]
Did you read the whole article? It will take you 3 minutes to read + 1 minute to fix the issue. It probably took you longer to write all the stuff here.

**Comment by Kourt32** [comment]
yes i read the 3 minute article, no it did not help to fix the issue. I followed the steps. thank you anyway

**Comment by photopea** [comment]
But Photopea is not opening old files anymore, right?

**Comment by Kourt32** [comment]
Correct. Only if I open the 1 file that I have on my computer that I
created this morning.

**Comment by photopea** [comment]
So you have a file, which you open in Photopea and it crashes? Could you send us that file to support@photopea.com ?

**Comment by Kourt32** [comment]
Yes, I can. I just emailed it over to the link you posted.

**Comment by photopea** [comment]
I can not open your PSD file in Adobe Photoshop. It is probably damaged. Photopea can not open files, which do not work in any program at all.

You should have stopped using Photopea and looked for problematic browser extensions the moment it did not allow you to close documents (and reopened them after a while). From that point, your browser extensions were breaking Photopea and we can not guarantee the correct functionality at that point.

**Comment by Kourt32** [comment]
Okay, I'm not sure what's going on. These are the extensions I have, as
you can see below they are all turned off, and I have the file open on my
computer on Photopea, and it's saved as a PSD file. I'll have to look into
other designer softwares, thank you.

**Comment by photopea** [comment]
I can not see any attched files. Please, open Github.com in your web browser to respond, or communicate with us at support@photopea.com .

**Comment by photopea** [comment]
When using Photopea, click the "puzzle piece icon" at the top right corner of your browser, to see which extensions have your permission to see and change information on Photopea (this includes the source code and the input / output mechanism).

It looks like this: https://www.ghacks.net/wp-content/uploads/2020/11/chrome-extensions.png

**Comment by Kourt32** [comment]
Yes, I did that step. It has full access. I can manage with the files
crashing, is there anything I can do to make it stop saying "need more
ram?" That's the biggest issue I am trying to solve.

**Comment by photopea** [comment]
Are you talking about opening the PSD file that you sent me? I can open it in Photopea and it does not say "need more ram".

Could you maybe record a short video of what exactly are you doing?
![image](https://github.com/photopea/photopea/assets/15955558/33183bb6-bd8f-4154-b356-d8a10025dc89)

**Comment by photopea** [comment]
I have to close it because of lack of details :(
