### ISSUE TITLE
Feature request: Mirror Preview

### ISSUE THREAD

**Issue by DigitalNaut** [photopea/photopea#6082]
It'd be great if there was an option to get a live, mirror preview of a layer or canvas. An important use case is for drawing characters and structures. For example, it'd help me tremendously to churn out characters in T-poses for 3D modeling. Mirroring is already a big part of character creation in Blender and it'd be a time-saver to have that also in Photopea to streamline the workflow. It's not enough to be mirroring the layer manually or running as script as that takes away from the flow just to check progress. Not to mention that it's hard for creatives who'd be the main users of such a feature to modify JS to suit their needs.

I'll be looking into the suggestion in [this old thread](https://github.com/photopea/photopea/issues/1132) as I am familiar with programming, but I really think that it's an incredibly useful QoL feature.

That said, I love the Pattern Preview, which I never expected to find on Photopea but it's been there for years and it's amazing! Great work. I really enjoy the program and thank so much for the forethought and effort you've put into making it both familiar and feature-rich for us former PS users.

**Comment by DigitalNaut** [comment]
A bit of an update. I've looked through the documentation and I think the best I could come up with was this script for anyone looking for an approximate solution. I'll see if I can turn this into a plugin but for now just go to `File > Script`, paste this in there and save it.

<script src="https://gist.github.com/DigitalNaut/200f9e8ced470449ff55070876128a38.js"></script>

What it does is very simple: it makes a mirrored copy of the selected layer to the left and name it "temp_flipped" which you can change in the script. It'll try to keep only one of those layers around.

If you'd rather have it copy it on the right, change line 18 from `AnchorPosition.MIDDLELEFT` to `AnchorPosition.MIDDLERIGHT`. Just run the script whenever you want to see your changes. 

Unfortunately I can't figure out how to automate this by registering events with notifiers whenever the user draws which have their own caveats, and I'd rather not touch unmanaged JS intervals that copy over the image after a set number of time, which I'm not sure are supported anyway.

Cheers!

**Comment by photopea** [comment]
Do you know how people do this in Adobe Photoshop? Since our interface corresponds to Photoshop, we could let our users do this in a similar way.

**Comment by DigitalNaut** [comment]
Hey, thanks for the quick reply!

I found [this tutorial](https://helpx.adobe.com/photoshop/using/paint-symmetry.html) on the main Adobe website. Apparently their feature is called "symmetry mode" and it's an option under the paint brush. I also found [this video tutorial](https://www.youtube.com/watch?v=Ot84dn0ZU6Y) that's closer to the typical use case for artists. But [this other article](https://www.photoshopessentials.com/basics/how-to-use-paint-symmetry-in-photoshop-cc-2019/) gives many more implementation details: 

>Photoshop first places a Transform box around the path so you can scale and resize it if needed. But note that the path is for visual reference only. Symmetry paths always affect the entire canvas regardless of the path's actual size.

>Like regular paths in Photoshop, symmetry paths appear in the Paths panel. The path is named based on its symmetry mode (in this case, "Dual Axis Symmetry 1"). And the butterfly icon in the lower right of the thumbnail tells us not only that it's a symmetry path, but that it's currently active. You can have multiple symmetry paths in the same document, but only one can be active at a time.

>To switch to one of the other paths in the list, right-click (Win) / Control-click (Mac) on the path you need [...] And then choose Make Symmetry Path from the menu.

Please let me know if there's anything else I can help with!

**Comment by photopea** [comment]
It was already reported here: https://github.com/photopea/photopea/issues/5224 , so I will close it.

Otherwise, you can always duplicate a layer, flip it horizontally or vertically, and put it next to the old layer, to make a symmetric copy.
