### ISSUE TITLE
Actions - percentage image resize recording does not respect "keep aspect ratio" selection

### ISSUE THREAD

**Issue by ratheralarming** [photopea/photopea#6083]
Your Operating System: win10
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. open 200 x 100 image
3. create action
4. record resizing image to 25% with "keep aspect ratio" selected
5. observe retained aspect ratio
6. open 100 x 200 image
7. play aforementioned action
8. observe how it distorts

i might just be missing how to do this in a more efficient way (batch resizing images in a folder), and if so, my apologies. thank you for looking either way!

**Comment by photopea** [comment]
Sorry for the delay! There was a bug - Photopea was always recording the new size into the action. So your action was "resize the image to 50 x 25 pixels", and after applying it to 100x200 image, it made a 50x25 image.

I have fixed it - if you use percents, Photopea will record the "relative action", e.g. 33% of the original width and height.
