### ISSUE TITLE
Feature Request: Please add a timeout to content aware features

### ISSUE THREAD

**Issue by e-ave** [photopea/photopea#6084]
Content aware features such as content aware fill can sometimes take 10+ minutes to execute. You are forced to either wait or lose your work, so a simple warning before large operations, or popup that asks if you want to continue or undo the operation that has been running for more than 1 minute would be superb.  Also Please allow me to wait If I want to instead of displaying area too large

**Comment by photopea** [comment]
The speed of the content-aware fill depends on the number of pixels in your selection. I just tried to inpaint about 3 million pixels and it took 10 seconds (3 seconds for million pixels). 

What exactly are you trying to inpaint? Could you show us a specific example (a photo + a selection) where it takes more than 10 seconds:

**Comment by photopea** [comment]
I have to close it, because the person did not respond :(
