### ISSUE TITLE
ARABIC TEXT

### ISSUE THREAD

**Issue by a99119408** [photopea/photopea#6086]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....TRY TO TYPE ANY THING IN ARABIC 
3. ....IT WILL NEVER SHOW
4. ....

**Comment by photopea** [comment]
Could you try it in the incognito mode? Or try these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
We need a full report with your operating system and your web browser :(
