### ISSUE TITLE
Image Auto level Issue

### ISSUE THREAD

**Issue by Ashheer** [photopea/photopea#6089]
Hi, I am currently working on a project and would like to implement the "**image-adjust-levels-auto**" algorithm same with Photopea,  After some initial attempts, I have an issue with the "**enhance per channel contrast**" algorithm in Photopea.

My approach involves calculating the histograms for the three RGB channels, determining the minimum and maximum values based on the "lowcut" and "highcut" parameters(0.10%), and then mapping the pixel values to the range 0-255. However, it appears that my result may have some errors.

I was wondering if you would be kind enough to share your insights on how you have implemented this feature in your repository. Any guidance or advice you could provide would be greatly appreciated.

Below is a snippet of pseudocode to give you a sense of my approach:

`          

            vector<int> histogramred(256, 0);
            vector<int> histogramgreen(256, 0);
            vector<int> histogramblue(256, 0);
            for (int i = 0; i < w * h; i++) {
                histogramred[imagecolor[i][0]]++;
                histogramgreen[imagecolor[i][1]]++;
                histogramblue[imagecolor[i][2]]++;
            }

            int total = wide * height;
            int sum = 0;
            //Red channel
            for (int i = 0; i < 256; i++) {
                sum += histogramred[i];
                if (sum  >= total * 0.001f) {
                    MinRed = i;
                    break;
                }
            }
            sum = 0;
            for (int i = 255; i >= 0; i--) {
                sum += histogramred[i];
                if (sum  >= total * 0.001f) {
                    MaxRed = i;
                    break;
                }
            }
            ........Calc G B channel like R channel

                for (int i = 0; i < total; i++) {
                    vec3f &v = imagecolor[i];
                    v[0] = (v[0] < MinRed) ? MinRed : v[0];
                    v[1] = (v[1] < MinGreen) ? 0.f : v[1];
                    v[2] = (v[2] < MinBlue) ? 0.f : v[2];
                    v[0] = (v[0] - MinRed) / (MaxRed - MinRed);
                    v[1] = (v[1] - MinGreen) / (MaxGreen - MinGreen);
                    v[2] = (v[2] - MinBlue) / (MaxBlue - MinBlue);
                }`
#3572 relative issue about image level
I would greatly appreciate it if you could kindly take a look at my code or approach and let me know if my understanding of the problem appears to be on the right track.
Thank you very much for your time and consideration!

**Comment by photopea** [comment]
I think that our method does not correspond to Adobe Photoshop or other programs. I would like to find out the method behind Adobe Photoshop, to be able to provide an alternative. Do you compare your results with Photopea or Photoshop?

**Comment by Ashheer** [comment]
Yes, my result on the "Enhance Per Channel Contrast" method looks different with Photopea and Photoshop.
In the 'Auto' option for adjusting image levels, Various programs like Photoshop, GIMP, Substance Designer..etc seem different, but currently, I have only implemented the 'Enhance Per Channel Contrast' method within the 'Auto' option. This method in Photopea looks same with Photoshop, but some very minor differences in my implementation:(, I'm thinking about how to adjust my method to make the results correspond to Photopea.
I would also try to implement the other three methods later.
Thanks for considering it.

**Comment by photopea** [comment]
Just because your method is different, it does not mean it is wrong! :)

I am afraid I can not share any code with you, because our code is what makes Photopea unique.
