### ISSUE TITLE
Not showing transparent and guide layers

### ISSUE THREAD

**Issue by bkelm82** [photopea/photopea#6091]
Your Operating System: Windows 10
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: I don't know

**This must be done to see the problem**
1. Go to www.photopea.com
![Screenshot (4)](https://github.com/photopea/photopea/assets/147533466/9da2b812-f500-4faa-88d4-5fab221cd7b8)

2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Hi, could you try this and tell us if it helps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by bkelm82** [comment]
Yes, opening it in incognito solved the problem.Thank you very much  Sent from Mail for Windows From: PhotopeaSent: Tuesday, October 10, 2023 11:50 AMTo: photopea/photopeaCc: bkelm82; AuthorSubject: Re: [photopea/photopea] Not showing transparent and guide layers (Issue #6091) Hi, could you try this and tell us if it helps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
