### ISSUE TITLE
300 DPI Files open in 144 DPI

### ISSUE THREAD

**Issue by billynfl** [photopea/photopea#6092]
Your Operating System: MAC OS Sonoma 14.0 (23A344)
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: ?

**This must be done to see the problem**
1. Go to www.photopea.com
2. Try to open .pdf or .psd in 300 dpi
3. go to image > image size 
4. The image size shows in 144 dpi instead of 300 dpi which the file was saved in
<img width="574" alt="Screenshot 2023-10-11 at 6 26 28 AM" src="https://github.com/photopea/photopea/assets/147608350/245e2bc0-2e2e-407a-8818-e61d13d360ad">

**Comment by photopea** [comment]
PDF files are vector files and they do not contain any DPI info. 

No information about the DPI can be stored into a PDF file.

Photopea is a raster editor and opens all PDF files at 144 DPI by default. You can change it in Image - Image Size (in your screenshot).

If you make a document 10x10 inches and draw a red circle in the middle of a 5 inch diameter, it will be saved as a PDF with sizes in inches. There is no DPI. You can print it at any DPI you want.

**Comment by photopea** [comment]
I have explained how PDF works (above). You can also use a full vector editor www.vectorpea.com
