### ISSUE TITLE
Stroke features for text

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6093]
The features for text layer's stroke are minimal:
![image](https://github.com/photopea/photopea/assets/11801254/8d5f9abe-cfd7-4ba7-a456-427d95bead4a)

It will be possible to have all the same features of the stroke in a path layer?🫣
![image](https://github.com/photopea/photopea/assets/11801254/e9a55196-e3ab-46da-9682-839a3e1d36bc)

For example, i cannot create a font with a outside stroke, so i have to put another one below with a huge stroke:
![image](https://github.com/photopea/photopea/assets/11801254/30fba1b2-c8ca-407e-b78d-9bcb0b8429be)
![image](https://github.com/photopea/photopea/assets/11801254/0093b5de-7349-4d6f-b86a-2bd55dd66f45)

**Comment by TheRadicalDreamer** [comment]
I can copy the effect of the layer style - stroke, which it is basically the same

**Comment by photopea** [comment]
Hi, I have added more features of the text stroke, which are supported by the PSD format. Sadly, there is no "Poisition" of the stroke (inside, center, outside). However, there is an option "Fill before stroke", to tell if you want the shape to be filled first, or stroked first. Try this: www.photopea.com/#i-6pcF6-5

**Comment by TheRadicalDreamer** [comment]
Works like a charm!

Thanksssss
