### ISSUE TITLE
Can't open certain Dropbox folder

### ISSUE THREAD

**Issue by N190392** [photopea/photopea#6095]
When I click Dropbox icon on left side I see my root Dropbox folder.
![image](https://github.com/photopea/photopea/assets/57212053/5da3e76a-3939-428f-b4c2-b2607b540d33)

Whenever I want to open Pictures folder, it just shows:
![image](https://github.com/photopea/photopea/assets/57212053/8900e997-5935-4526-a449-9447f0b27d81)

When I click on it, popup appears/disappears, but the screen remains unchanged. Load Dropbox.

Which is weird, because i can browse other two folders. I must add that Pictures is the heaviest folder.

Edge / Firefox have same behavior.

**Comment by photopea** [comment]
I just tried to use my Dropbox in Photopea. I can open all folders, everything works fine.

Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by N190392** [comment]
Still same issue.
All I can see that in Firefox console when I try to open it show this:
![image](https://github.com/photopea/photopea/assets/57212053/995dc55c-6e37-434c-b8fa-4ff4dc00d882)
When it is successful, I see this:
![image](https://github.com/photopea/photopea/assets/57212053/786fcc93-8d3d-4686-9ad8-a7525fd4a20f)

**Comment by photopea** [comment]
It seems like some of your files in the folder has a weird thumbnail. Because of that thumbnail, it crashes. Could you maybe delete that file, if you know which one it is?

**Comment by photopea** [comment]
Oh, okay, I am very sorry. It should be fixed now. You should be able to have a folder named "GIF" now.
