### ISSUE TITLE
Issue with changing consent

### ISSUE THREAD

**Issue by I-nnerPeace** [photopea/photopea#6098]
Your Operating System: Windows 11
Your Web Browser: 
The problem happens in the Incognito Mode, too: No

**This must be done to see the problem**
1. Go to www.photopea.com
2. When Opening, mistakenly click  "reject all"
3. There is seemingly no "Change Consent"
![image](https://github.com/photopea/photopea/assets/147872066/42d19e39-5f73-4f09-9ef3-46b4aeb73ae2)

**Comment by photopea** [comment]
The "Change Consent" button should be on the right side. Could you share a screenshot of the full screen?

You might be using browser, extensions, which modify the look of Photopea. In that case, report the bug to a person who created your extension.
