### ISSUE TITLE
Eraser not working on gifs

### ISSUE THREAD

**Issue by dxrkoholic** [photopea/photopea#6099]
Your Operating System: ASUS Chromebook C202S Model
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Load up a gif
3. Equip the eraser tool
4. Try to rub out anything on your gif after selecting to put on a vector mask

I don't know if this is just an issue on my device but it has been happening for a while and it is quite annoying.

**Comment by photopea** [comment]
I do not understand the Step 4 :( I can not see any vector mask when opening a GIF.

**Comment by dxrkoholic** [comment]
> I do not understand the Step 4 :( I can not see any vector mask when opening a GIF.

Sorry, I meant raster mask :D

**Comment by photopea** [comment]
The eraser on a raster mask paints with a background color. So if your mask is white and the background color is white, you will not see anything.
