### ISSUE TITLE
Highlight the object under mouse

### ISSUE THREAD

**Issue by tomasnosek** [photopea/photopea#61]
It's advanced feature based on #44. When you have mouse over some object, you should highlight it to tell user on what he is aiming. Maybe looks like not neccessary feature, but i am always very upset when i have to select some thin object like lines or text and have to hit 1-2px wide something. I never know if i hit the correct layer (dont want to find it in layers) and that highlight would help me.

Grandmother's hint : it's pretty precise effort to hit something tiny, so maybe you could add some invisible 5px wide active area around it to allow click easily on it. You know what i mean?

**Comment by tomasnosek** [comment]
![active-area](https://cloud.githubusercontent.com/assets/20184728/16449643/ef2fe60e-3df8-11e6-8e68-9d8ba5d9928a.png)

**Comment by tomasnosek** [comment]
That light blue around the line is only for illustration pourpose. Just recolor slightly hovered object.

**Comment by photopea** [comment]
I am afraid it can not be reasonably implemented.

What do you mean by highlighting? Do you want an object to change the color? When an object is small, you will not notice, that it changed the color.

Active area: there can be a problem, when you have ten 1px lines, one by another. If the top-most layer is the line in the middle, "active area" would make it impossible to choose the lines close to it.

Why don't you just zoom in to choose that layer?

**Comment by tomasnosek** [comment]
You will notice on line, sure not on 2px dot, you are right, but it's not a problem. You simply go over that layer, drag and go. This highlight will be helpful on every layer, not only on the tiny one. Same mechanic is on web - links, buttons. Every element like those should have active state. In photopea is this needed even more because of much more elements on the same place. It will be more communicative to user, more easy to use.

Active area: If you have a layer mess in tiny space, it will be a problem in every situation and you will have to zoom for sure, but this is not our use-case. Imagine situation you are on 100% viewport, have few tiny layers, lines and want to easily drag them very fast. Why you should zoom to 1000% to catch a single pixel, then zoom-out and drag? Its 5-10s of useless effort.

**Comment by photopea** [comment]
Zooming takes 1 second, if you know the shortcuts Ctrl+Space+click,  Ctrl+Space+Alt+click .  You can also always choose the layer in Layers panel.

I am sorry, but to me, it seems like too much effort, which will be useful just in few special cases.

**Comment by tomasnosek** [comment]
It's very often situation actually. Even dragging text in your default design start to be little bit difficult. But sure, if it's too much work to do, let it be. This kind of micro-features are very important for user experience and will say to user if it's well usable app or not.

Btw, lines are one of the most use element in designs and to honestly, ctrl+space+alt+ click is really madness to use and remember. Usable zoom : CTRL+"+/-" or mostly hit "Z" as "zoom" and click. Very good zoom is implemented in PS : Press "Z", click-hold and drag left or right.

**Comment by photopea** [comment]
Regarding active area, what you suggest, if there are two objects A and B "touching" each other, A is above B in layers panel, when I click on B near A, the A would be selected. I find it very confusing and it will make things worse. Do you have another solution?

Highlighting: it would require redrawing the whole project, while you move a cursor. It can eat too much performance for large projects (e.g 2000 x 2000 pixels). What about drawing a bounding box of the current layer under the cursor? would it help?  But I still think, that too many "additional elements" would make it confusing.

**Comment by tomasnosek** [comment]
Active area: If 2 object are the same, and above each other, you have to move the top one and then work with the second. I dont try to find a solution for this specific situation. In case they are above each other and only touching themselves (crossed lines f.e.), you can click on both of them, so i don't see any problem here.

Highlight: You know, i personally don't know how complicated it is. Sure it's nonsense to redraw project., as you said too. I've tried to suggest a solution for this. Main goal is to highlight object under cursor, but there is more methods. Try that bounding box.

I know you are not convinced about this. But try it by yourself. Write some thin text, draw a 1px line, check the "choose the object under the cursor" and try to move that elements little bit quickly. I personally mostly hit the backround or simply missed it (without background). This is not a problem for graphic designers (they dont use lines or thin objects too much), but it's a horrible experience for those who make a webdesign, mobile design, drawing wireframes too etc.

**Comment by photopea** [comment]
Active area larger than actual object: I think it would do more harm than good.

Highlighting: as I said, highlighting an object could require redrawing the whole image. If you want to see the real image, you would have to move the cursor away, so no object is highlighted.

I am deciding not to implement it, for now.

**Comment by tomasnosek** [comment]
Ok, your choice. Today was released Affinity designer (PS competition, very good) and the use active area larger than object :) I can say, there is much better user experience than in other softwares they don't use it.
