### ISSUE TITLE
Suddenly lost all Raster Masks.

### ISSUE THREAD

**Issue by NeistH2o** [photopea/photopea#6100]
Your Operating System: Windows 10
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too: Unknown

I can't really tell how to replicate it but I have been working for a few days on a file, and today I realize every single pixel mask went black.

Thankfully I always keep 2000 files as backup so I can see from where it started happening; Yesterday I started adding relatively large embedded images in the file and it grew from ~10Mb to 59Mb, after that it reached 110Mb and that's when the masks mysteriously vanished in my saves.

**Comment by photopea** [comment]
Could you tell me what should I do to see it happen myself?

**Comment by NeistH2o** [comment]
Thanks for your reply, if it happens again I ll try to figure out exactly what caused it. I tried to re-do some operations I did yesterday but so far it didn't happen again.

**Comment by NeistH2o** [comment]
What causes it is the crop tool, sometimes I want to delete parts of pixel layers that fall out of the canvas area, for that I use the crop tool with "delete cropped pixels" enabled with it covering the entire canvas (not changing its size), and when I apply it also destroys all the masks.

If you want I could try to send you my file so you can try it on your side, but the file is 38Mb in size.

**Comment by photopea** [comment]
You are right, there really was a bug. I think I have fixed it. Could you try it again?

**Comment by NeistH2o** [comment]
Glad I could help :) it seems to be working fine now, thank you very much! By the way, Photopea says that I am using an ad blocker but it is disabled on that website, I see the ads even it thinks I don't, but be sure I ll subscribe again as soon as financially possible ;)

**Comment by photopea** [comment]
Maybe try this: https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

You probably see links of my games which I made in the past. I do not make any money if you click the link and play my games.

**Comment by NeistH2o** [comment]
I don't understand what is causing it, I disabled all extensions at the browser level, tried in a private window where no extension is allowed to run, I tried closing firefox entirely and opening it again, I looked for a feature that could block ads within firefox itself.. I don't see real ads :/

**Comment by photopea** [comment]
Do you see ads in other browsers? We need to figure out, if it is blocked by a browser or by your network.

**Comment by NeistH2o** [comment]
I just tried on Chrome Canary, I think it s up to date, if I disable Ad Block Plus completely I do see ads. I think it's the first time I actually see them...

**Comment by photopea** [comment]
But I can see ads in Firefox, too. Do you use any extensions in Firefox? Or did you enable ad-blocking or "tracking prevention" in Firefox?

**Comment by NeistH2o** [comment]
Ah! that's it, when I set tracking prevention to Standard instead of Strict then the ads appear! even with ad block plus running but disabled for Photopea. Anyway I assume that subscribing is much more profitable for you than ads, I might just do that and sacrifice something else. Does the column where the ads are goes away as well with a subscription, does it makes the tool occupy the entire window I don't remember? Sorry to take so much of your time, keep up the amazing work :)

**Comment by photopea** [comment]
yes, ads will go away: https://www.photopea.com/promo/no_ads.png
