### ISSUE TITLE
File not popping us to save my work

### ISSUE THREAD

**Issue by Trxpgeemoney** [photopea/photopea#6101]
Your Operating System: windows 10
Your Web Browser: google chrome
The problem happens in the Incognito Mode, too: unknown

I went to file, export as, and everytime I click save my file wouldn't open up and i did it to another tab and still doesn't work.

**Comment by Trxpgeemoney** [comment]
Update: It just started working randomly, and my computer is weird for some reason.

**Comment by photopea** [comment]
Could you try it in the Incognito mode?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
