### ISSUE TITLE
i open somes PSDs and Photopea Crahes

### ISSUE THREAD

**Issue by ch3rino** [photopea/photopea#6102]
Your Operating System: Windows 11
Your Web Browser: OperaGX
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Try this, let me know if it helped
https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details :(
