### ISSUE TITLE
Open a PSB that is 4.1 gb.

### ISSUE THREAD

**Issue by 0neChillTree** [photopea/photopea#6104]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: idk

I'm trying to open a PSB-file that is 4.1 gb.
It's just loading, and not opening.
I have 16 gb ram in my computer.

Is there any solution to it?

**Comment by photopea** [comment]
I think 16 GB of RAM might be not enough for such a large file (PSD and PSB files are compressed). Also, Google Chrome has a bug, which does not allow us to create a layer with more than 500 million pixels.

Could you try it in Firefox? If it still does not work, could you disable WebGL before opening your file? (More - Use WebGL)

**Comment by photopea** [comment]
I have to close it because of lack of details :(
