### ISSUE TITLE
Nothing happens when clicking "Watch Ad" after using Magic replace. Please, help.

### ISSUE THREAD

**Issue by Naranca1** [photopea/photopea#6105]
Your Operating System: Windows 10
Your Web Browser: Google Chrome 118.0.5993.70 
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open any image and try to use "Magic Replace" on it.
3. Click "OK" when it asks if you want to watch a short to use the tool without making a premium account.
4. Nothing shows up. Nothing changes visually.

I have seen this issue discussed in this forum already, but there was no solution. The magic replace doesn't work - when I click "watch ad" - nothing appears. There is no paid or free alternative photoshop with generative fill on the internet I could find. Please, I am so desperate.

1. I don't have an adblock
2. Yes, ads show up on the right
3. Yes, I am from Russia
4. Other browsers\vpn\interner providers\DNS don't work
5. This site (https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js) downloads a .txt file and closes istelf

I think that's everything. Please, is there any way you could help? I desperately need photoshop with ai generative fill, and I am at a total loss.

**Comment by photopea** [comment]
Our ad provider does not provide ads in Russia because of sanctions. So I am afraid I can not help you :( Sanctions must be stopped so that we can offer services to Russians.

**Comment by bluep55** [comment]
Hi.
Sorry about your dilemma. 
You say that "There is no paid or free alternative photoshop with generative fill on the internet".
The paid version of Photopea does not have any ads, all ads are removed, so this should eliminate the problem you have.
You don't have to purchase Photopea for the whole year which is $50
If you just want a quick fix, 30 days is only $8 while 90 days is only $15.
Hope this helps.
![Account type](https://github.com/photopea/photopea/assets/118609932/2d11e9a4-9782-44fb-a7fd-c91deaed5290)

**Comment by photopea** [comment]
@bluep55 Actually, card services - Visa, MasterCard, PayPal - also stopped to work in Russia. So there is no way for them to pay us.

We have more users from Russia than from Canada or Mexico, but there is no monetization at all (no ads, no Premium accounts). Honestly, I dont know what to do about it. Their country started an aggressive war, which is supported by most of Russians, so the sanctions are right. But they restrict Russians who dont support the war, too.

**Comment by camoody1** [comment]
Do VPNs not work in Russia, now, either?

**Comment by Naranca1** [comment]
Yes, and I presume that most Russians support it all because of these sanctions. No sanction has ever harmed or stopped the Russian gouverment or military in any way, they all just mildly inconvenience the population.

Yes, VPNs work, and I tried it, but it still shows ads for Russians, and nothing happens when clicking the "Show add" button.

**Comment by photopea** [comment]
Can you choose a country in your VPN? Could you show me what Photopea looks like when you open it (with ads)?

**Comment by Naranca1** [comment]
![image](https://github.com/photopea/photopea/assets/147993181/d0233034-ec22-43bc-9e23-7751ee65f994)

**Comment by photopea** [comment]
Can you see a video ad for the Magic Replace now?

**Comment by Naranca1** [comment]
No, nothing changed. Is there really no way?

**Comment by photopea** [comment]
rewarded ads could you blocked by your extensions. Could you open "about://extensions" and disable all your extensions temporarily? Is the VPN also an extension?

**Comment by Naranca1** [comment]
Yes, the VPN is an extension. I turned off all extensions and now I can't even see the ads O_O

**Comment by photopea** [comment]
I really dont know, maybe try a different VPN, which is not an extension? :/

**Comment by photopea** [comment]
Can you open https://cmp.uniconsent.com/v2/85d3b9563e/cmp.js ?

**Comment by Naranca1** [comment]
Yes, it is full of code

**Comment by photopea** [comment]
I am afraid I can not help you :( I really don't know why our ad provider is not providing an ad to you :(
