### ISSUE TITLE
On the front page of the site I click "About" and nothing happens

### ISSUE THREAD

**Issue by mkrier** [photopea/photopea#6106]
Your Operating System: Windows 11
Your Web Browser: Firefox 118.0.2 (64-bit)
The problem happens in the Incognito Mode, too: What's that?

**This must be done to see the problem**
1. Go to www.photopea.com
2. On the front page of the site I click "About" and nothing happens
3. Profit

**Comment by photopea** [comment]
This is the "About" screen (red rectangle). It can be hidden with the "X" button, and displayed again with the "About" button.

If the "About" screen is visible and you press the "About" button, nothing will happen.
![image (5)](https://github.com/photopea/photopea/assets/15955558/7036863d-1c5c-4caa-8f6c-66377bd46bfb)
