### ISSUE TITLE
screen

### ISSUE THREAD

**Issue by xalex378x** [photopea/photopea#6107]
Your Operating System:macbook pro
Your Web Browser:safari
The problem happens in the Incognito Mode, too:don't know

**This must be done to see the problem**
1. Go to www.photopea.com

My problem is the screen is cut off and doesn't fit so I cant use photopea to its full ability like seen here on the right

<img width="1440" alt="Screenshot 2023-10-17 at 12 25 31 AM" src="https://github.com/photopea/photopea/assets/148180074/eb4fb374-3bd6-4761-9ba8-36b374d2c18f">

**Comment by photopea** [comment]
You are using many browser extensions. Some of them could be modifying the look of Photopea. Please, try to turn off these extensions.

If you don't believe me, try to turn off all your extensions and see that it instantly starts to work correctly.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
