### ISSUE TITLE
Brushes larger than 15px are not smooth until you pick a brush

### ISSUE THREAD

**Issue by jespertheend** [photopea/photopea#6109]
Your Operating System: macOS 14.0 (23A344)
Your Web Browser: Chrome 118.0.5993.70
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Select the brush tool
3. Right click the screen
4. Make the brush larger
5. Paint a brushstroke

Selecting a brush from the same menu fixes the issue.
The issue occurs with all tools, so even if you select a brush for the brush tool, once you switch to the eraser tool you'll have to pick a brush again in order to fix it.

https://github.com/photopea/photopea/assets/2737650/7f8f11fa-5866-41db-b350-eba422ba133b

**Comment by photopea** [comment]
This is a correct behaviour. It all depends on the Spacing parameter: https://www.youtube.com/watch?v=HWeOuwuGrqs

Read this: https://www.photopea.com/learn/brush-tools

The default brush has a spacing of 25%, the new brush which you picked has a spacing of 5%.

**Comment by jespertheend** [comment]
Ah I see, that makes sense 😅 
In that case I think it would be nice to be able to configure a default brush, or maybe just to store the most recent brush locally.
Because every time I load the page, this is one of the first things I do.
But it seems like #5300 already covers this.
