### ISSUE TITLE
Multiple Stroke layer effects broken

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#611]
I added multiple strokes in Layer Style for layer and it shows random lines where shouldn't be.
To reproduce:
1. open pea.psd
2. go to Layer Style of "pea" layer
3. change stroke position to "inside"
4. add another stroke with "+" and go to this second stroke settings (click on it)
5. change second stroke position "outside"
-> shows random black lines over image
(note if you set first stroke "outside" and second "inside" it has no error for some reason)

**Comment by photopea** [comment]
It was fixed. Thank you!
