### ISSUE TITLE
Partially hidden font category panel.

### ISSUE THREAD

**Issue by bluep55** [photopea/photopea#6110]
On Android in portrait mode on the Chrome installed version of Photopea.
The font category panel is partially hidden and I can't find any way to reveal it fully.
The panel pops out to the right and is hidden.
Could it be made to pop out to the left instead?
I've highlighted the panel in red.
![Screenshot 3](https://github.com/photopea/photopea/assets/118609932/5643e0f1-7e76-465e-a706-9c15a981ea75)

**Comment by photopea** [comment]
It is very strange that nobody has reported it so far :(

I have fixed it, thanks a lot!

**Comment by bluep55** [comment]
👍🙂
