### ISSUE TITLE
I want to know how to implement it

### ISSUE THREAD

**Issue by hmwl** [photopea/photopea#6111]
From a technical perspective, I would like to understand how Photosea implements **free transform** of images, especially the **warp** function. I hope to receive help. Thank you @photopea

**Comment by photopea** [comment]
hi, sorry, we can not share any details about our source code :(

**Comment by hmwl** [comment]
Oh no, I don't want to get the code. I just want to get the implementation principles or corresponding papers. I searched the entire network but couldn't find them. I was surprised to find that it was implemented on the webpage in Photosea. I hope to get some help, and I would be very grateful. Thank you.

**Comment by photopea** [comment]
You should look for linear transformations of raster images. Linear transformations are described by matrices.

**Comment by zzq0324** [comment]
> Oh no, I don't want to get the code. I just want to get the implementation principles or corresponding papers. I searched the entire network but couldn't find them. I was surprised to find that it was implemented on the webpage in Photosea. I hope to get some help, and I would be very grateful. Thank you.

Hi @photopea , we need to deform the image based on the meshPoints of PSD in our background system, but I don't know what method can be used to implement this logic. Is this algorithm can implement it like this? Clould you please tell me the algorithm,  I hope to get some help, and I would be very grateful. Thank you.
<img width="1163" alt="image" src="https://github.com/user-attachments/assets/50ecec68-26f1-47f9-9c2d-2bf022c4a145">

**Comment by photopea** [comment]
Sorry, I can not share any of internal "know-how" like this :(
