### ISSUE TITLE
Export TGA generates zero-bit size files (intermittent)

### ISSUE THREAD

**Issue by jerz0** [photopea/photopea#6112]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Upload multi-layer .PSD file (2048x2048px)
3. Make some obvious edits.
4. Export the file as a .TGA
5. Make some more obvious edits.
6. Export the file as .TGA

Expected behaviour: Photopea exports a valid TGA file with the most recent changes.

What happens instead: Sometimes, the dialog for export TGA includes a checkbox to convert to sRGB. Sometimes, this checkbox does not appear. When the checkbox does appear, the preview window does not contain the most recent edits. You need to toggle the Convert sRGB checkbox to refresh the Preview window to include the recent edits. 

When I started using Photopea tonight, I was able to export valid TGA file. After a few hours, the checkbox stopped appearing, and the TGA files were 0 bytes. 

I first thought that this was a limitation of the free version. I've been exporting a lot as I'm designing new car paints for iRacing, so i donated for one month to see if the limitations were removed. They were not. So I am assuming this is a bug with your TGA export workflow.

Don't get me wrong .. i don't regret at all that I subscribed to Photopea. I have been using Photoshop for over 15 years, and I greatly appreciate the fact you have built something with very similar features that is available for free. It is totally worth your monthly price.

I just really need this TGA export to work  :)

I have attached the .PSD and resulting TGA files for reference.

(never mind .. i just tried dragging them, and github doesn't accept either .TGA or .PSD as attachments .. lol)

....  oh .. wait!  i was able to zip them and include them as an archive. I hope this helps you get to the root of the issue. 

[problemFiles.zip](https://github.com/photopea/photopea/files/12984647/problemFiles.zip)

Thanks!

-Jeremy

**Comment by photopea** [comment]
You did not answer the last question - does it happen in the Incognito mode?

I am 99% sure that you are using browser extensions, which break the behaviour of Photopea. E.g. they "protect" you by not allowing websites to store files with weird extensions (TGA), as they could be viruses, etc.

**Comment by jerz0** [comment]
Thanks for the response.

I just tried to export TGA in Incognito, and it did work. Thanks.

Sorry for my misunderstanding .. I thought the suggestion about Incognito is that is something that could cause issues, not avoid them.

The only extension I was using was an ad-blocker, and I white-list Photopea, so I'm not sure what is causing that issue since I'm using chrome without any other add-ons .. but i'm glad this works while in Incognito .

Cheers!

**Comment by photopea** [comment]
Look into the settings of your ad block. Maybe there is an option to allow websites save TGA files.

In general, I am 100% sure that if you disable your extension, Photopea will work perfectly. That is why we ask our users to report only bugs which happen in Photopea, which was not modified by any browser extensions.
