### ISSUE TITLE
Magic Wand selection not Anti-aliased

### ISSUE THREAD

**Issue by N190392** [photopea/photopea#6113]
Can't get smooth edges when either filling or painting selection.
Selecting using Magic Wand and painting with Brush.
![image](https://github.com/photopea/photopea/assets/57212053/39cf8981-9dff-41c0-bcaf-248597bd2b30)
Result:
![image](https://github.com/photopea/photopea/assets/57212053/236458a3-6d69-4f92-8369-ba1da2e05d54)

**Comment by photopea** [comment]
What should I do to see it happen myself?

In your example, if you are selecting the black "curve", you can not expect it to partially select white pixels.

**Comment by N190392** [comment]
The paint curve is already the painted part, but here is how I do it:

1. Draw a Shape
![image](https://github.com/photopea/photopea/assets/57212053/9419c618-c946-4547-90ce-be04cc7a8aa5)
2. Use Magic Wand to select it.
![image](https://github.com/photopea/photopea/assets/57212053/4003d99e-7f77-4d92-b6a7-9cfc6267a523)
3. Hide Shape 1 &  Create a new layer
![image](https://github.com/photopea/photopea/assets/57212053/bcd377ed-4d1b-474c-9e18-1d4bb0b68cdd)
4. Layer - New Fill Layer
![image](https://github.com/photopea/photopea/assets/57212053/afd0a862-1c3a-478a-aaf8-9eba02d735cb)

**Comment by photopea** [comment]
I just tried it in Adobe Photoshop and it works absolutely the same.

Note, that you are selecting a black pixel, but there are only black pixels, no other colors are present in your layer (some black pixels are transparent).

If you want to convert the transparency of a layer into a selection, you should Ctrl+click the thumbnail of that layer. Or use Select - Load Selection - Transparency of a layer.
