### ISSUE TITLE
Bevel and Emboss + Stroke (gradient) is rough render

### ISSUE THREAD

**Issue by N190392** [photopea/photopea#6114]
Photopea:
![image](https://github.com/photopea/photopea/assets/57212053/81ff31d7-6113-452c-98ad-7ad37069dc31)
Photoshop:
![image](https://github.com/photopea/photopea/assets/57212053/5a8e8799-b530-4eee-8a46-6a1d50380f8a)

As you can see, the Photopea has like 'cuts' in stroke. When there are sharp/lots of curves it is just noise, if Stroke gradient is colofrul.
Another example where problem is more visible. Photoshop left, Photopea right.
Note: This PC has some green artifacts, other PC did not.
![image](https://github.com/photopea/photopea/assets/57212053/8fa07048-2d78-4c21-aeba-2319a4d7826a)

Attached template.
[template.zip](https://github.com/photopea/photopea/files/13045181/template.zip)
If needed I can provide second template.

**Comment by photopea** [comment]
I think I have fixed it, it should work a bit better now.

**Comment by N190392** [comment]
Thank you!
Not as smooth as Photoshop, but definitely better now, though there are still 'micro cuts'.
![image](https://github.com/photopea/photopea/assets/57212053/b7c5ef57-fdc9-45bf-b266-27424169ad19)

**Comment by photopea** [comment]
Could you try to switch to a different "Technique" in the Bevel options?

**Comment by N190392** [comment]
With Chisel Soft the lines gets even more noticeable:
Here it is with simplified settings. Looks that it affects all Bevel "Styles". Chisel Hard is more blurried compared to Chisel Soft.
![image](https://github.com/photopea/photopea/assets/57212053/dd61e380-c407-4c5a-8759-18d3ba85b0f7)
![image](https://github.com/photopea/photopea/assets/57212053/94fd8e57-7da8-4bee-a9ac-b4b144e6af2e)

**Comment by photopea** [comment]
I think it works the same in Adobe Photoshop.
