### ISSUE TITLE
Strange issue(s) with pasting on FireFox

### ISSUE THREAD

**Issue by Slooshie1** [photopea/photopea#6115]
Your Operating System: Windows 11 Home
Your Web Browser: Mozilla FireFox
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new project
3. Use the rectangular select tool on any layer
4. Press Ctrl+C
5. Press Ctrl+V
6. Press and hold Ctrl

The issue is quite weird. I've only seen this happen with Photopea but it might be a FireFox issue. When I select an area I want to copy, then press Ctrl+C and Ctrl+V, a weird "Paste" prompt comes up, and clicking it does paste the selection, but if I click off the prompt, the prompt shows again whenever I press Ctrl. If I click paste after this point, holding Ctrl will rapidly paste the selection indefinitely. Attached below is a video of the issue:

https://github.com/photopea/photopea/assets/90230538/545f30ae-4677-4cc9-ad03-87db8fde23a5

**Comment by bluep55** [comment]
I've just tried this on Firefox and on Chrome and pressing Ctrl+C and Ctrl+V work exactly as they should for me, pasting the new selected area on top of the background layer as a separate layer. Looking to the right hand side of your screen, there are no ads showing at all in the right hand panel. This could possibly be your problem. Ad Blockers and any Browser Extensions can cause Photopea to behave in strange ways.

**Comment by photopea** [comment]
I did all six steps which you wrote. Nothing happens when I hold Ctrl :( Also, your video is different to your six steps :( It is so confusing.

**Comment by bluep55** [comment]
I've just tried this on Firefox and on Chrome, and pressing Ctrl+C and Ctrl+V work exactly as they should for me, pasting the new selected area on top of the background layer as a separate layer. Looking to the right hand side of your screen, there are no ads showing at all in the right hand panel. Could this be your problem? Ad Blockers and any Browser Extensions can cause Photopea to behave in strange ways.

**Comment by Slooshie1** [comment]
I have tried this in a private window with no extensions, and the issue persists there. I have changed a couple things here and there in the about:config for FireFox but nothing that should cause this I don’t think. I haven’t been able to find anyone else with this issue anywhere on the internet :(

**Comment by bluep55** [comment]
Try Ctrl + Shift + C to copy, then Ctrl + Shift + V to paste.
This works on Firefox for me as well as Ctrl + C and Ctrl + V

**Comment by Slooshie1** [comment]
Same issue. I decided to try the same thing on Pixlr E and it does not do this. Photopea is the only website so far that has this issue, and I've had it for a while now. Maybe a bout a week or two

**Comment by Slooshie1** [comment]
Okay, update. I created a fresh new profile on FireFox with default everything. The issue does not happen there, so it is indeed something wrong with my main profile, which is unfortunate because I would have to start from scratch and re-customize everything, but I'm not willing to do all that just for Photopea. Oh well, at least the issue was vaguely identified.

**Comment by Slooshie1** [comment]
Here is what shows in the browser console when this issue happens btw 
![image](https://github.com/photopea/photopea/assets/90230538/b4b83bda-5e99-45e6-b8b3-5d49025e4c34)

**Comment by photopea** [comment]
Firefox is the only web browser, which does not support the Clipboard API: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API#browser_compatibility

Clipboard API allows you to copy images in Photopea and paste them anywhere else (e.g. in MS Draw). It allows a webpage to place an image into the main clipboard of your system. As Firefox is really slow with implementing new standards (or maybe they even consider this standard dangerous), I think Firefox will totally disappear in a few years.

**Comment by bluep55** [comment]
If you prefer Firefox for general use, could you use the the Chrome or Edge Browser just for Photopea? You shouldn't have the same problem with those.
Both those allow you to use the install function as well, giving you a Photopea shortcut so you don't even have to open the Browser first.
