### ISSUE TITLE
Illustrator .ai and PDF lacking page division when opened on photopea

### ISSUE THREAD

**Issue by tuconeves** [photopea/photopea#6116]
Hello! May be related to issue #4666

PDF files generated on Illustrator (or its .ai files) opens up on Photopea without its pages division/artboards,
Even though the pages are groupped as normal folders or square shapes on layers panel

Also, photopea draw some shapes in diffent ways than PDF viewers. (Take a look at the green shapes on the bottle)
Same file opens as should, with its propper pages, on any pdf viewer

Example file [PDF file generated with Illustrator]
https://drive.google.com/file/d/1Plz8pSpK270tQQUSv9UMXW8MO2BRamfT/view?usp=sharing

![image](https://github.com/photopea/photopea/assets/88161035/336c3eb8-1342-450d-a95b-7050e919fccb)

![image](https://github.com/photopea/photopea/assets/88161035/17c64b06-c330-47a8-b16e-9753564630d8)

**Comment by tuconeves** [comment]
Expected result:
User are able to open a multi-page pdf file on photopea, and it's pages gets a artboard each;

**Comment by tuconeves** [comment]
> This PDF file seems to contain the "AI part". Photopea detects this part and processes it as the AI file, but Adobe Illustrator can not detect it and handles it as a PDF file (no layer names etc).
> 
> Do you have the AI version of your file, which can be opened in the Illustrator as the AI file? I would like to open it in Illustrator to see what it should look like.

I got it! Here is the original .ai file
https://drive.google.com/file/d/1eT0385148pJqaChrIZ9WHZQGJzkgpNFZ/view?usp=sharing

With this issue I discovered that PDF files can atatch others elements outside the view. Great! Let me know if I could help with something else!

**Comment by photopea** [comment]
I have opened your AI file in Photopea and it looks the same as in Adobe Illustrator.

BTW. artboards in Illustrator are different than artboards in Photoshop (in Photoshop, a layer can not be inside two artboards, but it can in Illustrator).
Photopea converts every AI file into a PSD file, so we can not convert AI artboards into PSD artboards. Maybe use www.vectorpea.com for this.
