### ISSUE TITLE
3-month Premium version - [UI/UX Issue] Side bar and Tool bar is not shown when the screen is in 100% view

### ISSUE THREAD

**Issue by redtaurus9265** [photopea/photopea#6117]
Your Operating System: Mac OS 13.4.1
Your Web Browser: Google chrome
Device : Macbook Air

I paid for the 3 month paid version and now the interface is missing the enter sidebar section. It shows only when I log out. 
<img width="1440" alt="Screenshot 2023-10-21 at 18 41 51" src="https://github.com/photopea/photopea/assets/148633605/efece6ce-c00d-47bc-82ff-f0cd3bbb5126">

And when I select the layer, the sidebar appears but the half of the left side of the screen (toolbar and the top navigation bar) is gone. 
<img width="1440" alt="Screenshot 2023-10-21 at 18 47 14" src="https://github.com/photopea/photopea/assets/148633605/63419913-7b00-4349-9be7-2270bdc41c3f">

Got the paid version to get the work done faster and easier but it turned out to be an utter inconvenience and a waste of money, because the free version shows all these bars although there are time limitations to use certain features. Please attend this ASAP. I use a macbook air, I tried installing the app in that and as well as in the web browser (chrome) version for the Premium account I paid for, both have the same issue. Please attend this ASAP!!!

**Comment by redtaurus9265** [comment]
When I zoomed out the screen to 80% only the entire UI shows up with all the menu bars and tool bars, which is still difficult to work on such a small zoomed out view. Please make it a responsive UI for the Paid versions because the Free version does not have this issue. People pay money to have something more and better than the Free version. Having such careless issues on a PAID version is not acceptable. 
 
<img width="1440" alt="Screenshot 2023-10-21 at 19 02 09" src="https://github.com/photopea/photopea/assets/148633605/535596ab-3ddf-413d-97fc-14845e635faa">

**Comment by photopea** [comment]
I think you are using a browser extension "ublock origin", which is modifying the look of Photopea. Please, ask the creator of that extension to not modify the look of Photopea. Or turn off that extension. Did it help?

**Comment by redtaurus9265** [comment]
**It Worked!!! Thank you so much!!! 😃🎉**

**Comment by camoody1** [comment]
@redtaurus9265 You should consider apologizing to the developer for being so angry with him when it was clearly not his application causing the problems for you. It costs nothing to be kind and considerate.

**Comment by redtaurus9265** [comment]
> @redtaurus9265 You should consider apologizing to the developer for being so angry with him when it was clearly not his application causing the problems for you. It costs nothing to be kind and considerate.

If you were a QAE, your workday will run out just for writing apology notes to developers rather than reporting bugs, especially edge cases on end-user experience. Even JIRA has an “INVALID” ticket status for a reason. Plus, if the Product owners are aware of such conditions, they should mention them in the Premium account Features and Limitations in the first place. App development companies in general should know that people use ad-blockers nowadays. 

And what are you? The GitHub Pastor? Mother/Father to all Developers species? Was this specifically addressed or assigned to you? NO, so mind your own business. If you’re desperate for apologies, speak to the actual person who hurt you, rather than preaching to a random stranger on GitHub.

**Comment by camoody1** [comment]
@redtaurus9265 I feel sorry for you, man. You felt the need to write two paragraphs showing your shitty attitude towards others, instead of just saying you're sorry. I'll pray for you to develop a little more understanding and a respectful heart. ✌🏼
