### ISSUE TITLE
Starting from an existing image fails for HTML sources

### ISSUE THREAD

**Issue by byronwall** [photopea/photopea#6118]
I wanted to start a session by dragging an image from Google.  It worked if I went to image search results and dragged from there.  It failed when I tried to drag the image from the main results knowledge panel (is that the name?) on the home page.  The drag shows the correct image but it does not load on drop in Photopea.

The drag there is a `<meta>` tag with an image somewhere inside it.  Here's a StackBlitz that shows this being handled correctly: https://stackblitz.com/edit/web-platform-l7znv8?file=index.html

Example of the image I wanted to drag (the dog on the left):

<img width="616" alt="image" src="https://github.com/photopea/photopea/assets/495404/ac7793c4-9ae0-46d3-8dd5-6e116400da42">

**Comment by photopea** [comment]
Okay, it should work now! However, I still recommend right-clicking the image on the internet, choosing "Copy Image", and in Photopea, press Ctrl+V (or Edit - Paste).
