### ISSUE TITLE
GIF

### ISSUE THREAD

**Issue by uuanpi** [photopea/photopea#6119]
Your Operating System: WINDOWS 11
Your Web Browser: MICROSOFT EDGE
The problem happens in the Incognito Mode, too: YES

**This must be done to see the problem**

"I'm trying to export this project to a GIF, but when exporting it, there's an issue with the images, and the filters and adjustments applied to them appear mixed up. Can you help me?"

**Comment by photopea** [comment]
Hi, what should I do to see the problem happen? Could you send me your document as a PSD file, and I will export it as a GIF myself?
