### ISSUE TITLE
Drag and drop is not working.

### ISSUE THREAD

**Issue by stutiDX** [photopea/photopea#612]
Drag and drop functionality is not working on Crome as well as on mozilla firefox.
I have tried doing it with several PSDs.
Please get back to me asap.

**Comment by photopea** [comment]
Hi, it was reported before: https://github.com/photopea/photopea/issues/598 but the person stopped responding.

Do you mean duplicating layers between documents by dragging them to another "tab" at the top? What exactly happens instead? Can you maybe take a short video?

**Comment by sadcircus** [comment]
Sorry I stopped responding, I've been busy.

**Comment by photopea** [comment]
Can anybody please take a short video with what you do and what happens when you do it?

**Comment by stutiDX** [comment]
I am trying to add image to the project which is not happening.
I have attach a screenshot of my screen. 
I am trying to put 5557f4fb9a781fe.psd on new project which is opened in another tab. But drag and drop functionality is not working properly and I am unable to add image on Project. 
![capture](https://user-images.githubusercontent.com/34124868/38305258-e08698f0-3829-11e8-81e9-51e1bde5ea0b.JPG)

**Comment by photopea** [comment]
You should not drag the document label (XYZ.psd), but the actual layer from the document area into another tab.

It is described at the end of this article: https://www.photopea.com/learn/layers

**Comment by stutiDX** [comment]
I am not trying to drag and drop the document label but the image into another tab, but it won't allowing me to do so.
Attaching the screenshot for more clarification.
![capture](https://user-images.githubusercontent.com/34124868/38352502-0c404d90-38d1-11e8-9ea2-a3e04b2c9908.JPG)

**Comment by photopea** [comment]
Ok I see what is the problem. This drag-and-drop duplication works only with the Move tool (the first tool in the toolbar). In your case, you have a Free Transform tool. Also, the Move tool is not highlighted in the toolbar.

Escape the Free Transform (press Escape on the keyboard, or just clikc on the Move tool in the toolbar) and do it with the Move tool.

The Move tool switches to Free Transform when you start moving one of 8 control points. If you wanted to resize / rotate the layer, do so with Free Transform, confirm it (checkmark in the top bar), then you can drag-and-drop it with the Move tool.

**Comment by stutiDX** [comment]
I am using the tool only and also tried by clicking escape key as well still it's not working.

**Comment by photopea** [comment]
Are you sure, that when you drag-and-drop, the Move tool is highlighted in the toolbar? It is not in your screenshot.

**Comment by sadcircus** [comment]
I've tried it, my move tool is highlighted and it still doesn't work.

**Comment by photopea** [comment]
Ok, can you send a video to support@photopea.com ?

**Comment by stutiDX** [comment]
I have mailed the video to support@photopea.com. Please have a look and let me know anything else is needed.

**Comment by photopea** [comment]
stutiDX: Ok I see now. The free transform is enabled when you drag the middle area of the layer (it should not be enabled when you do that). This is a bug and I will fix it.

**Comment by stutiDX** [comment]
Yes please try to fix it ASAP. Thank for the support.

**Comment by photopea** [comment]
It was fixed. Thank you for your help!

**Comment by stutiDX** [comment]
Yup It is working now. Thank you so much. Appreciate your quick support.
