### ISSUE TITLE
Site saying that im using ad blocker even though i don't (i can see the ad)

### ISSUE THREAD

**Issue by MarkAlexey** [photopea/photopea#6122]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open a file
3. Wait a minute till ad comes up
4. You can't do anything now

**Comment by DuckyMacfly** [comment]
same problem with me as well

**Comment by camoody1** [comment]
If you're using Microsoft Edge, trying setting your Tracking Prevention to "Balanced" under the browser's Settings->Privacy, Search and Services options.

If you have AdBlock installed but "disabled" for Photopea, try following this writeup I made on Reddit.
https://www.reddit.com/r/photopea/comments/17ecsxk/adblock_fix_for_photopea_issues/

**Comment by photopea** [comment]
We allowed ad blockers back. If we decide to forbid ad blockers in the future, we will also write some tips about how to disable your ad blockers.
