### ISSUE TITLE
Protest recent Ad-enforcement

### ISSUE THREAD

**Issue by DRSDavidSoft** [photopea/photopea#6123]
Hi there Ivan, I hope you're doing well!

Thank you for the continuous development and support for Photopea, I have been a user from the day 1 back in 2017 when you first introduced it across Reddit and Hacker News.

Recently I have noticed that you're trying so hard to display ads on Photopea, and I temporarily disabled my trusty uBlock Origin to see what all the commotion was, and see that you are also developing a new game. I'm impressed, but sadly I really don't have any interest in the games you have developed. No hard feelings, the graphics look amazing but I simply don't have the interest.

Furthermore, If I click on one of the games that I found interesting, your subdomain over at `ivank.net` gives me this message:

<img width="579" alt="image" src="https://github.com/photopea/photopea/assets/4673812/6c75236b-0d6c-4c47-8dbe-95d7ba7419c5">

You seem to be a reasonable guy, so I was wondering if I could please make a reasonable proposal. I'd like to post a screenshot here everytime I encounter an advertisement that is of no to use to me. Also, from the experience, I have never seen an advertisement that is of use to me (like Photopea), and that is why I use uBlock Origin.

There is, however, an actual problem that I wanted to report with Photopea. Even though I'm now seeing the ads for your games, Photopea is still telling me that "Ad blocking detected" message.

Ivan, it's very well thought out that you have put this page:
https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

For testing purposes, I always open the webpage in a **Guest** profile in Chrome rather than Incognito mode. Because, do you know that the extensions can be configured to also work under Incognito mode? And I believe extensions such as uBlock Origin **absolutely** must be enabled in Incognito mode too, because why would someone want to see ads in Incognito and not the regular profile? Here's a screen shot of that:

<img width="529" alt="image" src="https://github.com/photopea/photopea/assets/4673812/b0ef9212-16c5-43f7-88e1-9ab1ec40a50c">

Now, it's very good advice on your part to open the `chrome://extensions/` page and see what extensions are enabled and installed. Do you know what it looks like under the Guest profile? It looks like this:

<img width="599" alt="image" src="https://github.com/photopea/photopea/assets/4673812/f14fd56a-fcf6-40d3-9840-79eec1a7f5fd">

So, as you can see, we're abso-positively sure that no extensions are whatsoever running here.

### However, this is what Photopea displays:

<img width="1037" alt="image" src="https://github.com/photopea/photopea/assets/4673812/45ddc607-e73f-4925-9354-c0eb4390f51f">

Can you tell what's wrong with the UI/UX of the Photopea in the picture above? It is in fact displaying the **Ads**, the toast message says:

> Sorry, but we do not provide any service to people with ad blockers.

This is an issue. I should either:
- Not see ads and not get served by Photopea
- See ads but get served by Photopea

I hope you'll agree that the current option is unacceptable.

In the meantime, I think I will adjust some values in your code, such as the string below:

> `B[[X\\k\\Q<S5=J646>,+%)xpn&dnvyjYcdTKJaSKXF8?=6,C8'/ 4rr+jqqbg^hf}`

and modify the obfuscated javascript file to patch the "bug" and remove this unnecessary feature.

Furthermore, I have another question. Would it satisfy you if I print out the screenshot for your games and stick it to the side of my monitor? Trust me, it ultimately results in the the same thing!

- I would see your "ads" to the right side of my Photopea window
- I would not ever click on any ads
- I can get my job done

It also has the benefit of not reducing my **actual work area** inside Photopea! Wouldn't it be nice?

Thank you for your time reading my request. I hope if anything, you get at least a good laugh out of it.

🇺🇦🇺🇦🇺🇦🇺🇦🇺🇦

### Browser information
**Operating System:** Windows 11
**Web Browser:** Chrome 116

**Comment by photopea** [comment]
Do you know why you can not open https://dinohunt2.ivank.net ? It is a regular website, which should open for everyone with the internet connection.

In what country are you located? Is it Ukraine (you mentioned it)? Could your internet provider or your government be blocking certain domains, or do any censorship?

**Comment by photopea** [comment]
Also, could you tell me your IP address, so that I can investigate it furhter?

**Comment by hergaiety** [comment]
I would absolutely subscribe to a patreon or ko-fi etc if it meant no ads while supporting development of this software.

**Comment by camoody1** [comment]
> I would absolutely subscribe to a patreon or ko-fi etc if it meant no ads while supporting development of this software.

There's no need for a Patreon or Ko-Fi subscription. Just sign up for a premium account through Photopea. If you pay for three months at a time, it's only $5 per month. Just click on the Account button at the top of Photopea and you'll find the information.
![image](https://github.com/photopea/photopea/assets/73725653/ed1e7de5-f809-441d-8ddf-215f395727e7)
![image](https://github.com/photopea/photopea/assets/73725653/c88d5413-e067-4eea-bb85-1a04fbde147a)

**Comment by DRSDavidSoft** [comment]
Thank you @Photopea and the team for your understanding, it's true that the internet connection conditions here are less than acceptable, and using tools like VPNs are the only way to have a (close to) reliable connection like the rest of the world. Sadly, it's also hard to come by good VPN providers here, since selling and using VPN services is illegal in the country for the citizens, and due to the sanctions it's also hard to purchase them from foreign providers.

All in all, thank you for choosing to allow serving Photopea to people with ad blocking, I appreciate your efforts!

**Comment by hergaiety** [comment]
> > I would absolutely subscribe to a patreon or ko-fi etc if it meant no ads while supporting development of this software.
> 
> There's no need for a Patreon or Ko-Fi subscription. Just sign up for a premium account through Photopea. If you pay for three months at a time, it's only $5 per month. Just click on the Account button at the top of Photopea and you'll find the information. ![image](https://user-images.githubusercontent.com/73725653/277586269-ed1e7de5-f809-441d-8ddf-215f395727e7.png) ![image](https://user-images.githubusercontent.com/73725653/277586354-c88d5413-e067-4eea-bb85-1a04fbde147a.png)

Ohh wow I hadn't seen this thank you @camoody1
