### ISSUE TITLE
Merge Down Rasterizes Layer Style

### ISSUE THREAD

**Issue by Numerosityy** [photopea/photopea#6124]
Title explains the issue, when I merge an image onto a layer with a layer style, I'd expect it to be added to the layer, yet the layer style is kept the same. This is how it functions in Photoshop. Please let me know if you need more explanation.

**Comment by photopea** [comment]
What if one layer has a drop shadow and one does not? Should the result have a drop shadow or not?

What if one layer has a red stroke and the other has a blue stroke? What stroke should the result have?

I don't think it functions like this in Photoshop :/

**Comment by Numerosityy** [comment]
Example: if there is a stroke on the bottom layer, and the top doesn't, merging the top to the bottom adds the stroke.

if they both have a stroke, the top layer receives the bottom layers stroke when merged down.

**Comment by Numerosityy** [comment]
before merging:
![image](https://github.com/photopea/photopea/assets/114539001/8b4278cb-d114-4bba-af21-1cd97e377556)

after merging:
![image](https://github.com/photopea/photopea/assets/114539001/1a7f15cd-b6e6-4f6d-b90b-b2af1c1db462)

**Comment by photopea** [comment]
I did not know that Photoshop works this way! But this behaviour seems very strange to me. The stroke of a top folder is rasterized, merged with the bottom layer (without a stroke), and the result gets a stroke of a bottom layer? Is this really what Photoshop users expect to happen? The result looks differently after merging.

Do you know you can right-click a layer - Copy layer style, disable layer styles, merge layers, and later, do Paste layer style?

**Comment by photopea** [comment]
So, in short, I think layer styles should be rasterized when merging, to keep the image looking the same.

If you want to do anything else, you can right-click a layer, and copy or paste layer style (before and after merging).
