### ISSUE TITLE
Pasted images should appear at the part of the canvas the user is viewing

### ISSUE THREAD

**Issue by Numerosityy** [photopea/photopea#6125]
No matter where I'm scrolled, Photopea currently always pastes images at the very top. With a large canvas, this is very annoying. It takes minutes to drag a single image all the way to where I want it to go. If the issue is unclear, I'm glad to explain more.

**Comment by photopea** [comment]
I think it is better to paste them into the center. So I did it - they are pasted into the center now.

**Comment by camoody1** [comment]
@photopea This is a nice change. Thank you.

**Comment by Numerosityy** [comment]
this is much better, thank you!
