### ISSUE TITLE
Create a standalone Desktop app

### ISSUE THREAD

**Issue by Numerosityy** [photopea/photopea#6126]
I only say this for one reason: Web browsers have trouble rendering large files. Even just scrolling through a large image can cause lagspikes. With a standalone desktop app, users could allocate more RAM to minimize these issues, and allow Photopea to perform better using your device's full potential.

**Comment by photopea** [comment]
If there are problems in the current Photopea, the "desktop app" would have the same problems. Problems should be fixed. Certain operations or filters take a long time because they are hard to compute, and not because it is done in a browser. Just tell us what exactly would you like to improve :)

**Comment by TCB13** [comment]
>  Just tell us what exactly would you like to improve :)

A fully offline version (even if its just the web app packaged as a desktop App) would be great. There are lots of situations where an internet access isn't great or accessible.

For instance Figma has a desktop app. Thank you.

**Comment by photopea** [comment]
In Photopea, you can press More - Install Photopea. Did you try it?

Also, you should be able to open www.photopea.com in your web browser when you are offline. Did you try it?

**Comment by TCB13** [comment]
> In Photopea, you can press More - Install Photopea. Did you try it?
> 
> Also, you should be able to open [www.photopea.com](http://www.photopea.com) in your web browser when you are offline. Did you try it?

There's about of small details on those "apps" that make them not useful. They don't even provide true offline mode (they expire), require a certain browser with support installed, can't install without an active internet connection etc.

Thank you.

**Comment by photopea** [comment]
Right now, we have around 5 million users, and we make arnoud 4 cents per user per month (from ads).

If we sold Photopea for e.g. $70, we would probably have 100x less users. But we would make $3.5 million.

What exactly is a "clunky experience"?

**Comment by TCB13** [comment]
> What exactly is a "clunky experience"?

Not having a desktop version is a clunky experience. Browsers are clunky.

**Comment by photopea** [comment]
Did you try to press More - Install Photopea?

**Comment by TCB13** [comment]
> They don't even provide true offline mode (they expire), require a certain browser with support installed, can't install without an active internet connection etc.

We're going in circles, that's not a real app.

Those Chrome backed things don't even provide true offline mode (they expire and stop working), require a certain browser with support installed, can't install without an active internet connection etc.

**Comment by photopea** [comment]
I dont know many people using computers without internet. And their number will keep going down in the future.

Anyway, other than the offline mode, the experience of using Photopea is even better than using any native program made for your os.

**Comment by TCB13** [comment]
> I dont know many people using computers without internet. And their number will keep going down in the future.
> 
> Anyway, other than the offline mode, the experience of using Photopea is even better than using any native program made for your os.

Cmo'n Photopea is good but you don't need to oversell :)

**Comment by photopea** [comment]
I am not overselling, it can literally change lives and turn water into wine

**Comment by TCB13** [comment]
> I am not overselling, it can literally change lives and turn water into wine

It isn't that hard to pack we website into a Windows desktop app using the native WebView2, [check this example](https://github.com/TCB13/TBCalc-Desktop/blob/main/main.cc) where I packaged [TBCalc](https://github.com/TCB13/TBCalc) into a desktop app.

**Comment by photopea** [comment]
But have you tried More - Install Photopea? Your experience would be 100% the same, maybe even better, as browsers are more up-to-date than any "website packers"

**Comment by TCB13** [comment]
> But have you tried More - Install Photopea? Your experience would be 100% the same, maybe even better, as browsers are more up-to-date than any "website packers"

Yes , I did, and it isn't. It won't work offline for extended periods and nobody can install it offline.

In case you aren't aware WebView2 is provided by Microsoft and is essentially an always up to date Edge view that you can have inside any app, not really a website packer.

**Comment by photopea** [comment]
Most of our users do not pay for Photopea Premium, and our ads would not work in "offline Photopea".

**Comment by TCB13** [comment]
I see that, but you can always sell the offline version and keep the online one. Two sources of income, everyone will be happy.

**Comment by photopea** [comment]
I think there are like 7 people who really need an offline version and want to pay for it, it is not worth developing it.

**Comment by TheRealFame** [comment]
> I think there are like 7 people who really need an offline version and want to pay for it, it is not worth developing it.

Is it ever coming?? I still really need offline mode for my long trips. Even if it's basic!

@photopea

**Comment by photopea** [comment]
I still think it is too much work and the number of people without the internet is constantly decreasing. Also, we would not be able to monetize our software with ads, if it is used offline :(

**Comment by TheRealFame** [comment]
> I still think it is too much work and the number of people without the internet is constantly decreasing. Also, we would not be able to monetize our software with ads, if it is used offline :(

Can't you just temporarily store offline ads and get more once they connect?

Also a desktop app would still get you much more users (A guess.) Because then people can point to that installer then say an app like gimp

**Comment by photopea** [comment]
If you open www.photopea.com while being online, you can still use it when you are offline.

Many people keep the same Photopea tab opened in their browser for weeks, as they almost never turn off their computer (they always put it into a sleep mode).

**Comment by participle38** [comment]
I don't need offline access, I just want a proper offline Photopea desktop app _because_. I would be willing to pay like $50 just to have it _because_.
One practical reason I do have: ads slow the browser down and make Photopea's performance a little choppy. I could block them, but then I wouldn't be supporting this excellent app.
Also, I don't want to become reliant on a webapp that could eventually be shut down, ensh*ttified, acquired by a bad company, etc.. I want an executable file on my hard drive that can't be changed or taken away unless I allow updates.

**Comment by photopea** [comment]
Sorry, we do not offer this.

I think the payment should correspond to how much you use the software. If you use it once in a month, for 5 minutes, $50 is too much. But if you use it six hours a day, every day, for 10 years, $50 is too little.

For $50, you can remove ads from Photopea for a whole year. Would you be interested in it?

**Comment by participle38** [comment]
> For $50, you can remove ads from Photopea for a whole year. Would you be interested in it?

That sounds like a fair deal, yes.

**Comment by photopea** [comment]
You can have it right now. Just click "Account" at the top of www.photopea.com

**Comment by photopea** [comment]
Maybe we should promote it more somehow, because less than 0.1% of our users are paying for the Premium account, while it is 100% for software like Affinity Photo or Adobe Photoshop.

**Comment by participle38** [comment]
Definitely. When I Googled "photopea premium" the other day, the top result was [this page](https://blog.photopea.com/photopea-premium.html), which states that Premium has no benefits other than supporting the software. No mention of ad removal.

**Comment by photopea** [comment]
That is from 2016, when we had no ads in Photopea at all.

**Comment by participle38** [comment]
Might need to do some SEO on that.

**Comment by H-KBrothers** [comment]
Wow, what a great support team! Anyway, I could help you develop the offline app. The only thing I'd want in return is free access to that version. That way, you can skip the development phase and just market it on your website. Win-win.
