### ISSUE TITLE
Try to uninstall by removing it from Windows Remove Programs on Control Panel but still there even I restarted the pc.

### ISSUE THREAD

**Issue by ashpc14** [photopea/photopea#6127]
Help me

**Comment by camoody1** [comment]
You're trying to uninstall Photopea? Where did you install it from? It should only be a webapp that is super easy to uninstall. I hope you didn't install it from some malware provider. 😔

**Comment by Pt-home** [comment]
> Вы пытаетесь удалить Photopea? Откуда вы его установили? Это должно быть только веб-приложение, которое очень легко удалить. Надеюсь, вы не установили его от какого-то поставщика вредоносного ПО. 😔

Hi! I think a lot of people might think that this is installing a local application, like Paint.net or others. Everyone has a different level of understanding of processes in any field, this is normal
