### ISSUE TITLE
Rotate around AnchorPosition via script

### ISSUE THREAD

**Issue by jeroenkroese** [photopea/photopea#6128]
Your Operating System: MacOS
Your Web Browser: Brave (chromium)
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Add a layer 
3. Execute following script 
```
var l = app.activeDocument.activeLayer;
l.rotate(90, AnchorPosition.TOPLEFT);
```

**Result**
The layer rotates around the center instead of the provided AnchorPosition.

**Comment by Pt-home** [comment]
Hi! You can checked your task with next executeAction-based script: 
`var idTrnf = charIDToTypeID( "rotateEventEnum" );
    var desc15 = new ActionDescriptor();
    var idnull = charIDToTypeID( "null" );
        var ref2 = new ActionReference();
        var idLyr = charIDToTypeID( "Lyr " );
        var idOrdn = charIDToTypeID( "Ordn" );
        var idTrgt = charIDToTypeID( "Trgt" );
        ref2.putEnumerated( idLyr, idOrdn, idTrgt );
    desc15.putReference( idnull, ref2 );
    var idFTcs = charIDToTypeID( "FTcs" );
    var idQCSt = charIDToTypeID( "QCSt" );
    var idQcszero = charIDToTypeID( "Qcs0" );
    desc15.putEnumerated( idFTcs, idQCSt, idQcszero );
    var idOfst = charIDToTypeID( "Ofst" );
        var desc16 = new ActionDescriptor();
        var idHrzn = charIDToTypeID( "Hrzn" );
        var idPxl = charIDToTypeID( "#Pxl" );
        desc16.putUnitDouble( idHrzn, idPxl, 0.000000 );
        var idVrtc = charIDToTypeID( "Vrtc" );
        var idPxl = charIDToTypeID( "#Pxl" );
        desc16.putUnitDouble( idVrtc, idPxl, 0.000000 );
    var idOfst = charIDToTypeID( "Ofst" );
    desc15.putObject( idOfst, idOfst, desc16 );
    var idAngl = charIDToTypeID( "Angl" );
    var idAng = charIDToTypeID( "#Ang" );
    desc15.putUnitDouble( idAngl, idAng, 45.757066 );
    var idLnkd = charIDToTypeID( "Lnkd" );
    desc15.putBoolean( idLnkd, true );
    var idIntr = charIDToTypeID( "Intr" );
    var idIntp = charIDToTypeID( "Intp" );
    var idBcbc = charIDToTypeID( "Bcbc" );
    desc15.putEnumerated( idIntr, idIntp, idBcbc );
executeAction( idTrnf, desc15, DialogModes.NO );`

Result:
![image](https://github.com/photopea/photopea/assets/29394245/1098f0df-955c-47ce-94e1-9997f254ece5)

**Comment by Pt-home** [comment]
But and your script in playground correctly worked now:
![image](https://github.com/photopea/photopea/assets/29394245/91b9432d-5d23-494c-a3a6-1a23dcc5e24f)

**Comment by photopea** [comment]
@jeroenkroese I just tried your script in Adobe Photoshop and in Photopea, and it works the same in both cases (the layer rotates around its top left corner). What should I do to see a problem? What would you like to happen instead?

**Comment by jeroenkroese** [comment]
Thanks for taking a look. I can't seem to be able to reproduce the issue myself. Closed.
