### ISSUE TITLE
❗BUG urgent in ESTILO DE CAMADA❗

### ISSUE THREAD

**Issue by DavidSilvadeSa** [photopea/photopea#6129]
SYSTEM OS: ANDROID STOCK
DEVICE: POCO X3 PRO

❗BUG QUE COMEÇOU A POUCO TEMPO "ATE O MOMENTO 2 DIAS"❗

🆘BUG🆘

FAZ 2 ANOS QUE ESTOU USANDO O PHOTOPEA EM MEU PROJETO DE REMASTERIZAÇAO DE JOGOS DE PSP

E A 2 DIAS ATRÁS DO NADA ME DEPAREI COM UM BUG ACREDITO RELACIONADO AO "ESTILO DE CAMADA"

✨ANTES ESTAVA 100% PERFEITO✨
![Photoshop](https://github.com/photopea/photopea/assets/82737672/70e96140-959f-46db-9116-8921622c2097)

🥺DERRETE TODO EFEITO GRÁFICO SE PERDEU E FICOU DESSA FORMA🥺
![photopea](https://github.com/photopea/photopea/assets/82737672/83da39ea-594e-4551-b969-5201e81db1ff)

também é notável que a tonalidade de cor também ficou diferente e bugada

eu ficaria extremamente agradecido se esse problema fosse resolvido.
😢pois estou no meio do meu projeto é seria uma tristeza e perca de tempo recomeçar tudo do zero usando o Adobe Photoshop😢

------------------------------------------------------------------------------------------------------------

❗BUG THAT STARTED A LITTLE TIME AGO "SO FAR 2 DAYS"❗

🆘BUG🆘 I'VE BEEN USING PHOTOPEA IN MY PSP GAME 

REMASTERIZATION PROJECT FOR 2 YEARS AND 2 DAYS AGO OUT OF NOWHERE I FOUND A BUG I BELIEVE RELATED TO THE "LAYER STYLE"

✨BEFORE IT WAS 100% PERFECT✨ 

MELT ALL GRAPHIC EFFECT IF LOST AND STAYED LIKE THIS

 It is also notable that the color tone was also different and buggy

 I would be extremely grateful if this problem was resolved. 😢because I'm in the middle of my project and it would be sad and a waste of time to start over from scratch using Adobe Photoshop😢

**Comment by photopea** [comment]
are you talking about the style of text - bevel and emboss?

Could you share your PSD with us, so that we can see it?

**Comment by DavidSilvadeSa** [comment]
❣️YES❣️

**Comment by DavidSilvadeSa** [comment]
[1 CARD S-SR-UR total325 364-160 328-192 136-208 PROJECT by David S AKA Ze Pomba Louca do Nordeste NEW.zip](https://github.com/photopea/photopea/files/13147634/1.CARD.S-SR-UR.total325.364-160.328-192.136-208.PROJECT.by.David.S.AKA.Ze.Pomba.Louca.do.Nordeste.NEW.zip)

**Comment by photopea** [comment]
It should work better now.

**Comment by DavidSilvadeSa** [comment]
I did some tests here

I made some images from scratch that I had already made before

I did a graphic comparison

and nowadays it's not as good as it used to be

Before, when applying layer effects, the effects were clean, sharp and very beautiful

now the effect has a washed out appearance and the graphic quality has worsened

😢😢😢😢😢

**Comment by camoody1** [comment]
@DavidSilvadeSa It would definitely help if you provided before and after images to show exactly what you're talking about.

**Comment by DavidSilvadeSa** [comment]
![1 PERFECT](https://github.com/photopea/photopea/assets/82737672/96eb3886-e3b7-400e-917a-179feb3e31e4)
![2 BUG](https://github.com/photopea/photopea/assets/82737672/72113799-1954-470f-b1d7-14c61c08ae7a)
![3 PERFEITO](https://github.com/photopea/photopea/assets/82737672/267b9461-88bd-4bc9-b57d-291e479af4ca)
![4 BUG](https://github.com/photopea/photopea/assets/82737672/ad6a3e23-c6a9-4a0d-aec5-a7728e342e87)

the graphic difference changed on 10/23/2023

before applying the layer effect to the TEXT |monster/card name| To stop using SILVER or GOLD before, the effect really gave that metallic appearance.

It had very good clarity and depth and now that metallic aspect is no longer the same.

I've been REMASTERING games for the PSP for 2 years and in this project of mine I need to recreate 7,159 cards

1,300 cards were already ready with standard graphic quality

but after 10/23 everything changed and I can't follow the project because it would affect the quality of the project

1,300 perfect
5,859 with quality different from the already established standard

Oh I can't continue

[1.zip](https://github.com/photopea/photopea/files/13199973/1.zip)


#GOOGLE TRANSLATE#

**Comment by camoody1** [comment]
Maybe Ivan can see a bigger difference, but for me, these images are just too small to really notice any sort of depth or metallic look. I can appreciate that you want your project to be perfect in your eyes, but from someone who is new to what you're showing me, I just don't see a difference. 🤷🏼‍♂️

Do you have higher resolution versions of these images you can share?

**Comment by photopea** [comment]
I was fixing this bug: https://github.com/photopea/photopea/issues/6114  and it made your case look worse.

Right now, it makes both your and the other case look "good enough", it is a compromise. I can switch it back to original, but the @N190392 case would look bad.

@N190392 what do you think we should do?

**Comment by N190392** [comment]
I think you should switch back to original. 
My case was improved, but still not as smooth as I would have expected.

**Comment by photopea** [comment]
okay, I have switched back to the original version. So now, Chisel Hard and Chisel Soft work the same.
