### ISSUE TITLE
Update Gradients with angle adjustments

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#613]
The scale and offset already update with dragging, but angle haven't

**Comment by photopea** [comment]
Hi, what do you mean? Dragging of what updates what?

**Comment by hgs54371** [comment]
The slider and circle in gradient dialog from tool bar drop down and property panel

**Comment by photopea** [comment]
"tool bar drop down" - Do you mean the Top Bar, which shows with Vector-editing tools? This, and Gradient properties, work only when the Gradient Fill layer is selected.

**Comment by hgs54371** [comment]
Yes, but by update with dragging I mean the gradient angle update in real time with angle adj circle dragging, not a jump after release

**Comment by photopea** [comment]
Ok, so you mean the **Angle input**, where you drag a tiny red cross in a circle to define an Angle?

I think, if we updated it while dragging, it would be too slow (the red cross would not move smoothly - bad experience). I think updating after the mouse release is better.

**Comment by hgs54371** [comment]
Yes, that, I just showed in video
[gradient.mp4.zip](https://github.com/photopea/photopea/files/1871501/gradient.mp4.zip)
Does this Really that resource intensive ? Or just that you're using a too outdated computer,

Do you also have trouble dragging/panning the photo spheres in google street view ?

When using low power computer, it can also be done by click in numeric input anyways

**Comment by photopea** [comment]
Ok, I made these updates "live" in Angle Input. It will probably be smooth for Gradient angle, but it may be slow for Layer styles (Drop Shadow, Bevel and Emboss).
