### ISSUE TITLE
Opening a PDF, auto detects the layers and it messes up the text.

### ISSUE THREAD

**Issue by iamimsh** [photopea/photopea#6130]
Your Operating System: Mac OS - Sonoma
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open a file from computer, choose any PDF file
3. It opens the PDF but layers are auto detected, and due to missing fonts all the text layers are messed up. 

**Proposed solution:**
There should be an option while importing. 
1. To import and auto detect and convert layers
2. To import as it is in a single layer without any conversion.

**Comment by photopea** [comment]
PDF files contain "reduced" fonts - a font inside a PDF contains only letters used in that PDF. So if we load a font from a PDF file, and let you use it in Photopea to type new letters, you will not be able to the letters which do not occur in the original text.

You are supposed to load a TTF / OTF file from your computer, and then, the text in your PDF will be re-rendered.

**Comment by iamimsh** [comment]
Thanks for your explanation. I think there's a mis-understanding. 

What I meant was: I don't want the text to be re-rendered when importing PDF. Because, most probably I won't have the fonts that are in the PDF. 

So, all I need is, if we import a PDF, import it as an image layer like actual photoshop does. If possible.

Thanks again.

**Comment by photopea** [comment]
Then, you can open your PDF in any PDF viewer, take a screenshot, and paste it into Photopea.

Sorry, Photopea does not have a built-in PDF viewer. It would make Photopea much bigger.
