### ISSUE TITLE
Short keys changed? Some of these are not working.

### ISSUE THREAD

**Issue by andrewatya** [photopea/photopea#6131]
Your Operating System: Win11 Pro 22H2 22621.2428 Windows Feature Experience Pack 1000.22674.1000.0
Your Web Browser: Chrome 118.0.5993.118
The problem happens in the Incognito Mode, too: yes
- short keys could be changed, I started to use this soft to replace PS, and it was really nice to use the same short keys like in PS
- e.g.: Ctrl-T (free transform) was in PS, now in Photopea is to write texts
- e.g.: when use select tool and press Ctrl-I = should make inverse selecting, but it jumps to color sample tool
- e.g: Ctrl-O should open files but does nothing (bug?)
How can I customize short keys? I don't think its a real bug, however I remember I could use these well before...
Thank you in advance.
Andras

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
- sadly, web browsers do not allow us to use the Ctrl+T shortcut :( see https://twitter.com/photopeacom/status/1657899502630588418
- What is the Select tool? I believe all our tools work the same as in Adobe Photoshop
- I can use Ctrl+O in www.Photopea.com to open a new file. Maybe try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of the lack of details :(

**Comment by camoody1** [comment]
@andrewatya If you install Photopea as a webapp in Chrome, some of your normal Photoshop shortcuts will work. CTRL-T will Transform, CTRL-I will invert, CTRL-O will bring up the open file dialog. These don't work inside a standard web browser tab, but they do work as an installed webapp.

**Comment by photopea** [comment]
When I use Google Chrome, Ctrl+I and Ctrl+O work in the "standard web browser tab".

Also, @andrewatya clearly does not know Adobe Photoshop very well. They say "Ctrl-I = should make inverse selecting" - I guess they mean inverting the selection, but Photosohp never inverts the selection when pressing Ctrl+I.
