### ISSUE TITLE
Error when saving within the API

### ISSUE THREAD

**Issue by richardgoslingAOS** [photopea/photopea#6132]
We are seeing the following error within https://www.photopea.com/code/pp/pp.js

`Uncaught TypeError: Cannot read properties of undefined (reading 'push')
    at fx.fL (pp.js:15176:182)
    at fx.azm (pp.js:15179:38)
fx.fL @ pp.js:15176
fx.azm @ pp.js:15179
setTimeout (async)
fz.ane @ pp.js:15134
dQ.X$ @ pp.js:15451
fk.I @ pp.js:10797
hZ.I @ pp.js:10802
dQ.hi @ pp.js:15630
dQ.lE @ pp.js:15610`

This is preventing us from saving the imagery once altered. Please can you assist?

**Comment by richardgoslingAOS** [comment]
We are also seeing this in development tools in Chrome


<img width="839" alt="photopea1" src="https://github.com/photopea/photopea/assets/58290878/da060fa7-a023-4181-9baf-96909a600dec">

**Comment by richardgoslingAOS** [comment]
We are seeing it is failing the determine if it is a .jpg or .webp by the looks of the java script

<img width="1764" alt="photopea2" src="https://github.com/photopea/photopea/assets/58290878/b9afa1cf-e3fe-4f36-952e-401d95226303">

**Comment by photopea** [comment]
I am very sorry :( it should be fixed now.
