### ISSUE TITLE
I can't zoom in/out or scroll around, what's going on??

### ISSUE THREAD

**Issue by ur-locallovely** [photopea/photopea#6133]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by camoody1** [comment]
Everything is working fine on my PC. 🤷🏼‍♂️

**Comment by ur-locallovely** [comment]
it was js a dead tab i fixed it, tho idk why it happened bc this never happens to any other tab/web
