### ISSUE TITLE
`app.open` callback possible?

### ISSUE THREAD

**Issue by ctrlaltdylan** [photopea/photopea#6137]
I've noticed that `app.open(url, null, true)` does a great job opening a remote URL. However, when trying to perform subsequent actions in the same script like `app.activeLayer.resize()` that the new layer isn't always loaded in time. It seems like a race condition.

Would it be possible to support a callback argument to `app.open()` to fire after the image is loaded? Bonus points for DX - pass the layer as an argument to this callback.

**Comment by Pt-home** [comment]
addEventListener and onload work great for helping me always control how the image buffer is loaded

**Comment by photopea** [comment]
Do you use the https://www.photopea.com/api/live ? Photopea should send you a "done" message, when a new document is loaded.

**Comment by yikuansun** [comment]
@ctrlaltdylan is right, the `done` message is often called too early. Nowadays, whenever I want to use `app.open`, I use a promise which checks for when the document's layer count has increased by one: [https://gist.github.com/yikuansun/c0f1a602b4e9d4e344a41c4f49ded3bf#file-addimageandwait-js](https://gist.github.com/yikuansun/c0f1a602b4e9d4e344a41c4f49ded3bf#file-addimageandwait-js). (This code uses my [async function-based Photopea API wrapper](https://github.com/yikuansun/PhotopeaAPI).)

**Comment by photopea** [comment]
I think you are right, the "done" message is called when opening a new document, not when adding a layer to a current document.

But I think you can load the image in your environment, outside Photopea, and send it to Photopea as a binary file, which will be added instantly (re-copy pixels from one document to another, and close the new document, all using one script).

**Comment by jmverges** [comment]
Hi @photopea could you point me to an example about how to do what you mention in your last comment here? Many thanks!

**Comment by yikuansun** [comment]
> Hi @photopea could you point me to an example about how to do what you mention in your last comment here? Many thanks!

@jmverges Try something like this? https://gist.github.com/yikuansun/b3dc1345eac5c717d5b07f55dadddb76

**Comment by jmverges** [comment]
@yikuansun thanks! I will try that one. I'm using now a not array buffer way and seems to work okey with your other gist for addImageAndWait.
