### ISSUE TITLE
erasing doesn't work

### ISSUE THREAD

**Issue by briesrodrigo** [photopea/photopea#6138]
erasing gifs as a whole doesn't work. erasing color fill doesn't work. all that shows up is "layer is not editable". i've rasterized, (the little square thing at the bottom with a circle in the middle), but nothing works

**Comment by photopea** [comment]
There is 1 million of people using Photopea every day, and nobody reported such a problem.

What is "erasing gifs as a whole"? What should I do to see a problem?

**Comment by briesrodrigo** [comment]
If you were to input a GIF into Photopea and tried erasing a part of the gif, it wouldn't work. At least, not for me. When I first opened this issue, erasing pictures and color fill wouldn't work. Now it does, but for gifs, it still doesn't. It works sometimes but other times, it doesn't.

**Comment by photopea** [comment]
Could you maybe record a short video of what you are doing? Or share a screenshot of what you are doing?

**Comment by camoody1** [comment]
> If you were to input a GIF into Photopea and tried erasing a part of the gif, it wouldn't work. At least, not for me. When I first opened this issue, erasing pictures and color fill wouldn't work. Now it does, but for gifs, it still doesn't. It works sometimes but other times, it doesn't.

Make sure you're not just seeing the layer below the one you're erasing starting to show through. Hide all of the other layers and THEN try erasing the layer you're working on.

**Comment by briesrodrigo** [comment]
https://github.com/photopea/photopea/assets/149204681/27199dcb-e745-41ca-b95e-9c8d2e472fc0

**Comment by camoody1** [comment]
@briesrodrigo You don't use the Eraser Tool on layer mask. If you want to "erase" an area using a layer mask, change your paint color to black and use the Brush Tool. 👍🏼

**Comment by briesrodrigo** [comment]
@camoody1 how does one change the color with the Brush Tool?

**Comment by briesrodrigo** [comment]
@camoody1 thank you so much! this works! <3

**Comment by camoody1** [comment]
@briesrodrigo I'm glad that I could help. :)

**Comment by photopea** [comment]
I am glad you have solved it! I still recommend everyone to learn Photopea properly at www.photopea.com/learn, rather than following some random tutorials.
