### ISSUE TITLE
Generate Mockups with API Scripting

### ISSUE THREAD

**Issue by abetancurlobelo2405** [photopea/photopea#6139]
Hello,

Photopea offers a quick way to create mockups by navigating to File > Automate > Generate Mockups... > Selecting your image > and clicking on "Generate."

Is it possible to achieve the same results through scripting? If so, could you assist me in accomplishing this task?. I'm uncertain if scripting using a JSON configuration object is a viable approach.

Thank you.

**Comment by photopea** [comment]
I think you should be able to rebuild this feature yourself, see https://www.photopea.com/api/
