### ISSUE TITLE
PSDs do not open

### ISSUE THREAD

**Issue by dobsss** [photopea/photopea#614]

**Comment by photopea** [comment]
Hi, can you send us your PSD file to support@photopea.com ?

**Comment by dobsss** [comment]
I tried different psd files and nothing works

**Comment by photopea** [comment]
We test Photopea with 154 PSD files each time, and all of our PSDs work. Maybe all your PSDs have something specific, which our PSDs don't have. We need to have at least one corrupted PSD to be able to fix it.

**Comment by photopea** [comment]
When you open Photopea.com, there are two demos in the middle. Click "pea.psd" - it is a PSD file, that is opened without any problems. It is very hard for us to find PSDs that don't work.

Can you please send us your PSD file to support@photopea.com ?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
