### ISSUE TITLE
Add features as in Photoshop: moving the entire working area 

### ISSUE THREAD

**Issue by carboncrystal** [photopea/photopea#6140]
Your Operating System: Ubuntu 22.04.3
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**

1. Go to www.photopea.com
2. Add a horizontal and vertical scroll bar when zoom outside visible space, so you to can move the entire workspace.
3. Implement moving the working area (all layers) from the mouse if you click on the blank area (outside the work area) - to drag entire working area.
4. Move entire working area (all layers) from keyboard arrows.

![photopea-moving-working-area](https://github.com/photopea/photopea/assets/106466414/6747fcf3-68ed-409a-a51b-bf7ceb0242c0)

**Comment by camoody1** [comment]
Do you know that you can move the entire work area by holding down your space bar and left-click dragging your mouse?

**Comment by lovelyanswertell** [comment]
I supose is a suggestion. I need these features please. Happens too in Windows 10 / 11 (Home)

**Comment by camoody1** [comment]
Why do you need all of these options when you can just hold the Space Button and left-click to drag around the entire canvas?

**Comment by lovelyanswertell** [comment]
> Why do you need all of these options when you can just hold the Space Button and left-click to drag around the entire canvas?

Sorry, i not known these. I guess I was comfortable with the scroll bars in every program, for example paint.net.

**Comment by photopea** [comment]
Photopea is used by millions, scroll bars would only take a screen space, and it is really better to use it without scrollbars! You can get used to it, too!

You can scroll with your mouse wheel (add Ctrl for horizontal scrolling), or with two fingers on your touchpad. You can also use the Window - Navigator. You can learn more here: https://www.photopea.com/learn/navigation
