### ISSUE TITLE
color changing when opening psd in photopea

### ISSUE THREAD

**Issue by brablo** [photopea/photopea#6141]
Hi all,

When opening this psd file in photopea, the colors change extremely as you can see:
![image](https://github.com/photopea/photopea/assets/102042025/a9a38f31-bef7-4c58-922b-af670d867d26)

check file:
https://we.tl/t-L9GLwcEpOe

Any idea why?

Your Operating System: windows
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes 

**This must be done to see the problem**
1. Go to www.photopea.com
2. open the file

**Comment by photopea** [comment]
I have opened your file in Adobe Photoshop and it looks similar to Photopea.

I think it can be a bug in the program, which produced your second preview. What do you think? Did the author of your PSD tell you how should it look like? E.g. a PNG or a PDF version of the file?

**Comment by brablo** [comment]
hi,
the second preview is just the google photos preview.
I already did print the file on stickers with the jpg, and they ok with the darker blue background.
but now after I opened the psd file in photopea and changed some text and saved it again. I also printed these stickers and they were so much lighter. Which you can see clearly in the attached jpg's. So A is the original and B is after text changed and saved in photopea. In f.i. google photo viewer there is a clear difference in color between A and B.

Thanks for the help.

![B50x30](https://github.com/photopea/photopea/assets/102042025/252b02c7-1133-4714-a05f-6572c739664d)
![A50x30](https://github.com/photopea/photopea/assets/102042025/ce55f418-a437-4ec3-b483-05c46ee2188c)

**Comment by photopea** [comment]
okay, it is fixed now.

**Comment by brablo** [comment]
what you mean? still the same here.

**Comment by photopea** [comment]
If you open your PSD in Photopea now, it should look the same as in Photoshop. It does in my case. Could oyu show me what you see in Photopea vs. Photoshop?
