### ISSUE TITLE
Many SVGs are not displayed correctly

### ISSUE THREAD

**Issue by rgex** [photopea/photopea#6145]
Your Operating System: Mac OS
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open file 
![piiiine](https://github.com/photopea/photopea/assets/3996942/0da8cc97-338f-474a-8d4a-7205cb036df8)

3. 
<img width="303" alt="Screenshot 2023-11-02 at 10 39 54" src="https://github.com/photopea/photopea/assets/3996942/0d1edbf9-5697-4b28-9fae-28c2e809c4ee">
Letters such as P and e are not displayed correctly. This is happening with many SVGs right now.

**Comment by photopea** [comment]
Photopea has always worked like this. We convert SVG files to a PSD format, and a single path is always rendered with the "even-odd" fill rule in the PSD format. In other words, you can not create a letter P like yours in Adobe Photoshop.

Maybe try www.vectorpea.com for these things?
