### ISSUE TITLE
Embedded Displacement Map produces broken images

### ISSUE THREAD

**Issue by lucadalli** [photopea/photopea#6146]
Your Operating System: Windows
Your Web Browser: Chrome
The problem happens in the Incognito Mode too: Yes

This PSD was last saved in Photoshop with an embedded displacement map. It produces the intended result in Photoshop and a broken one in Photopea.

1. Visit www.photopea.com/#iwkeEhtZC
2. Download PSD and open in Photoshop
3. Place an image in Fabric SmartObject
4. Save SmartObject
5. Return to main document
6. Repeat steps 3- 5 in Photopea

**Photopea:**
![blanket mockup broken](https://github.com/photopea/photopea/assets/39853447/8217d43f-8302-409a-9123-04f343f2d79d)
**Photoshop:**
![blanket mockup](https://github.com/photopea/photopea/assets/39853447/976e0de3-a775-4162-91ea-c7364332af0f)

**Comment by photopea** [comment]
thanks, it is fixed now! :)

**Comment by lucadalli** [comment]
Fix confirmed! Thanks for your hard work @photopea!
