### ISSUE TITLE
There's a problem with the dropdown menus.

### ISSUE THREAD

**Issue by churrito5767** [photopea/photopea#6148]
Your Operating System: iMac (Apple M2)
Your Web Browser: Photopea's App
The problem happens in the Incognito Mode, too: ------

**This must be done to see the problem**
1. Go to Photopea's app
2. Enter Full Screen
3. Find a dropdown menu
4. Click on it
5. It doesn't appear
6. Now, exit Full Screen
7. Try again by clicking the dropdown menu
8. It does show

**Comment by photopea** [comment]
Hi, what is a "dropdown menu", which I should click?

What is "Photopea's app" and where can I find it?

**Comment by churrito5767** [comment]
A dropdown menu is like a button that if you click it, a list appears that lets you choose different options. You should click the button with the text "Normal" and an arrow pointing down at the right of the screen below the text "Layers", "Channels", and "Paths".
I found the Photopea App by just going to www.photopea.com and there was a button that said something like "Download the Photopea app now!".

**Comment by photopea** [comment]
Does it happen when you open www.Photopea.com in your web browser and use it there?

**Comment by churrito5767** [comment]
No, only when I open the Photopea app in Full Screen mode.

**Comment by photopea** [comment]
I tried it on my Macbook Air, but I can not see any such a problem :(

Could you uninstall it, and then, install it again the way you did before?

If it still does not work, could you record a short video of the problem?

**Comment by churrito5767** [comment]
Alright, I'll try it.

**Comment by churrito5767** [comment]
For some reason I can't find the way I installed the app last time...
I'll keep searching for it :[

**Comment by photopea** [comment]
In Photopea, you can press More - Install Photopea

**Comment by churrito5767** [comment]
I just tried that but the text "Install Photopea" is grey and not letting me click it, weird.

**Comment by TurnaboutTom2005** [comment]
I've actually been having the same issue. I'm also on a MacBook Air and every time the app is in fullscreen I can't see the menu next to "Blend Mode". It only seems to work when it's not in full screen. This issue is really recent though, so I think it might have to do with the recent MacOS update.

I'll try to see if uninstalling and reinstalling would work but I'm not sure if that's the solution.

**Comment by TurnaboutTom2005** [comment]
Okay I just tried uninstalling and re-installing and it didn't make a difference.

**Comment by photopea** [comment]
I have to close it, as I can not reproduce it myself, and nobody can tell me what to do to see it happen :(
