### ISSUE TITLE
Raster mask on top-most folder missing when opened in Photoshop

### ISSUE THREAD

**Issue by lucadalli** [photopea/photopea#6149]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode too: Yes

**This must be done to see the problem**
1. Visit www.photopea.com/#ikBg-lAsw
2. Observe top-most folder "Folder 1" has a raster mask
3. Save PSD and open in Photoshop
4. "Folder 1" raster mask is missing

**Photopea:**
![image](https://github.com/photopea/photopea/assets/39853447/b6753a65-248e-4293-96c6-fc1c75704026)

**Photoshop:**
![image](https://github.com/photopea/photopea/assets/39853447/abcff68c-6dfe-496b-9e3e-988e51322db8)

**Comment by photopea** [comment]
This happened only to raster masks, whcih were created by rasterizing a vector mask (Photoshop could not detect them in a PSD file created by Photopea). It was not related to folders.

I have fixed it. If you rasterize a vector mask and save it as a PSD, Photoshop will detect the raster mask in it. Please, delete the raster mask in your PSD and re-create it (as a raster mask, or by rasterizing a vector mask).

**Comment by lucadalli** [comment]
Thanks Ivan @photopea for always solving issues so quickly, even during weekends. Your hard work does not go unnoticed.
