### ISSUE TITLE
Gradient settings in properties panel messed up in firefox

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#615]
The one in Tool bar drop down was fixed, but the one in panel haven't
![screen shot 2018-04-03 at 8 09 30 pm](https://user-images.githubusercontent.com/36803688/38249264-adb3b8ec-377d-11e8-92f1-8eb92baffc03.jpg)
Changed to 21em
![screen shot 2018-04-03 at 8 12 43 pm](https://user-images.githubusercontent.com/36803688/38249268-afa352ca-377d-11e8-93ec-9d1969189030.jpg)

**Comment by photopea** [comment]
It was fixed. Thanks!
