### ISSUE TITLE
Displacement maps are broken

### ISSUE THREAD

**Issue by yikuansun** [photopea/photopea#6150]
Your Operating System: Ubuntu 22.04.3 LTS
Your Web Browser: Chromium
The problem happens in the Incognito Mode, too: yeah

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a document with two Smart Objects
3. Apply **Filter -> Distort -> Displace** to one of the Smart Objects, using the other Smart Object as the source layer

Hi Ivan, did you change the Displace filter in the past week? It was working fine several days ago, but now it just makes a zigzag; its behavior is almost like **Filter -> Stylize -> Wind**. Here are some images to demonstrate:

**Current Behavior**
![displace2](https://github.com/photopea/photopea/assets/38194363/ddeb555a-0151-417b-b8a4-7429c77750c0)

**Expected Behavior** (this was the result of the same document a week ago)
![displace1](https://github.com/photopea/photopea/assets/38194363/6acfd06e-4fa6-452c-9adc-cc2e7a48d7c8)

Edit: [this PSD file](https://www.photopea.com/#iSqf-t_v8) is a clear example.

**Comment by photopea** [comment]
sorry, it should be fixed now.

**Comment by yikuansun** [comment]
Thanks!
