### ISSUE TITLE
Adjusting the line in text

### ISSUE THREAD

**Issue by FarisShamsudeen** [photopea/photopea#6152]
Your Operating System: Windows 11
Your Web Browser: Google
The problem happens in the Incognito Mode, too: Not sure

**This must be done to see the problem**
1. Go to www.photopea.com
2. Opened a New File
3. Grabbed the text tool and I Typed three lines
4. Selected the text and adjust the third line text using this tool
![image](https://github.com/photopea/photopea/assets/132601449/f9adac8f-ee55-4f96-9389-c610be455f90)
5. After that, I selected the First line and tried to re-adjust the position but now the third line was moving instead of First line which I Selected.

**Comment by photopea** [comment]
I just tried it, but I can not see it happen :( Could you maybe record a short video of what you are doing?

**Comment by photopea** [comment]
BTW. you can learn how text works here: https://www.photopea.com/learn/text

Also, our text tool works exactly as in Adobe Photoshop, so you can try any Photoshop tutorial to learn these things.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
