### ISSUE TITLE
In Stable Diffusion Photopea opens in a small section of the screen only. Windows 11. Browser: Edge

### ISSUE THREAD

**Issue by bartgoldman** [photopea/photopea#6154]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....
![image](https://github.com/photopea/photopea/assets/150101198/12a9ba37-5337-409b-9f04-36d7d3b5d62b)

**Comment by camoody1** [comment]
This Stable Diffusion extension was not written by @photopea and is not supported by them. You will need to open a ticket with the person who actually wrote that extension.

Also, from your screen shot, it looks quite likely that you have an ad blocking extension installed on your browser. If you disable the ad blocker (even if just for a short test), you might get a better result.

**Comment by camoody1** [comment]
Here is an already existing issue for the extension with your exact problem.
https://github.com/yankooliveira/sd-webui-photopea-embed/issues/24

The user uninstalled their ad blocking extension and it is working for them, now.

**Comment by photopea** [comment]
I looked at https://github.com/yankooliveira/sd-webui-photopea-embed/issues/24 and it is just what I thought.

@bartgoldman and hundreds of other people use browser extensions, which are supposed to remove ads from Photopea (even though Photopea never contains ads in this case). And these extensions shrink Photopea for some reason.
