### ISSUE TITLE
Photopea crashes when trying to import this one specific PNG (attached inside zip folder)

### ISSUE THREAD

**Issue by arik-so** [photopea/photopea#6155]
Your Operating System: macOS Ventura 13.6.1
Your Web Browser: Chrome 119.0.6045.105 (Official Build) (x86_64)
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Drag the attached PNG into the drop area
3. Or alternatively, go to File -> Open, and open the attached PNG
4. It will hang

[remove.png.zip](https://github.com/photopea/photopea/files/13284713/remove.png.zip)

**Comment by photopea** [comment]
thanks, it should be fixed now.
