### ISSUE TITLE
bug with ads, im out of ram if i allow them to play

### ISSUE THREAD

**Issue by matheowis** [photopea/photopea#6157]
I guess there is some kind of loop in ads logic 10 sec and im out of ram, i have to inspect -> delete block of ads to stop this

**Comment by photopea** [comment]
Hi, that is really strange. There are millions of people who use Photopea with ads for hours.

Does it happen when you disable all your browser extensions? Your extensions could be manipulating with our ads.

**Comment by matheowis** [comment]
I use it almost every day and have never encountered this problem before. Today, I checked it on my Chrome browser as usual, and after shutting it down, I tried using Firefox, which I don't normally use and where I don't have any extensions installed. Within 10 seconds, it also crashed.

**Comment by matheowis** [comment]
It doesnt crash any more, but when ads are reloading i get spikes in CPU usage in OPERA and Firefox from 2% to 40%, in Chrome up to 80%

**Comment by photopea** [comment]
Yes, reloading the ads can use 80% of the CPU, but it lasts only for half a second at most. Or does it last longer in your case?

**Comment by photopea** [comment]
I will close it for now.
