### ISSUE TITLE
Font cannot be selected.

### ISSUE THREAD

**Issue by misammm** [photopea/photopea#6158]
I use photopea in Japan.
When I enter text and try to change the font, I cannot select it.
Previously, the font names were the same as when they were loaded, but now they are all translated into Japanese.
The translated fonts are not loaded, only the English fonts could be selected.
How can I select all fonts?

**Comment by photopea** [comment]
I don't know what it means. Could you tell your browser not to translate Photopea? Also, try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/  Let me know if it helped.

**Comment by photopea** [comment]
I have to close it because of lack of details.
