### ISSUE TITLE
Скасування виділення вмикається без мого втручання

### ISSUE THREAD

**Issue by KsenaPoz** [photopea/photopea#6160]
Коли працюєш з інструментом Виділення прямокутником, відбувається Скасування виділення без моєї на те згоди( 
Неможливо працювати

**Comment by camoody1** [comment]
Can you record a short video of your screen so we can see exactly what is happening?

**Comment by photopea** [comment]
What should I do to see it happen? Did you try it in the Incognito mode?

**Comment by photopea** [comment]
I have to close it because of lack of details.
