### ISSUE TITLE
Url erro .

### ISSUE THREAD

**Issue by allansique** [photopea/photopea#6161]
Mesmo com link correto e de acordo com o exemplo ao lado, surge erro informando que está incorreto

**Comment by photopea** [comment]
Hi, what exactly is happening? I do not understand.

**Comment by allansique** [comment]
Hi, I would like to install a plugin. I uploaded the file in Json, but when
it asks to put a tumbneail link, even following the example on the side,
the error appears stating that the url is wrong. And there is no other way
to do this. Below is a screenshot of the message.[image:
photo_5078151327296629539_y.jpg]

Em sex., 10 de nov. de 2023 às 08:24, Photopea ***@***.***>
escreveu:

**Comment by photopea** [comment]
Could you reply in a web browser at github.com ? Because you send emails to random github addresses and we do not receive your attachments.

**Comment by allansique** [comment]
Hi, I would like to install a plugin. I uploaded the file in Json, but when it asks to put a tumbneail link, even following the example on the side, the error appears stating that the url is wrong. And there is no other way to do this. Below is a screenshot of the message.
![photo_5078151327296629539_y](https://github.com/photopea/photopea/assets/72067977/5d386bb3-585a-49d9-bdda-0626e29e87d1)

**Comment by photopea** [comment]
can you right-click the image at Imgur and choose "Copy image URL"?

The Image URL must end with .jpg, or .png, or .gif, etc.

**Comment by allansique** [comment]
> você pode clicar com o botão direito na imagem no Imgur e escolher "Copiar URL da imagem"?
> 
> O URL da imagem deve terminar com .jpg, ou .png, ou .gif, etc.

It worked out . I managed to continue with the thumbneial upload. Thanks . But unfortunately my aruivo didn't work, the program accepted it because it was json, but it didn't run. The error message appears. In any case, thank you for your prompt assistance. And I leave a suggestion; If possible, please copy adolbe's Avatrar plugin to vectorize.
Oh, one more thing, can I save procedures I do on an image and apply it to others as if it were a plugin? thanks .

**Comment by photopea** [comment]
What vectorize plugin are you talking about?

**Comment by allansique** [comment]
[Avatar V2.0 Photoshop Plugin By Information Ocean.zip](https://github.com/photopea/photopea/files/13328442/Avatar.V2.0.Photoshop.Plugin.By.Information.Ocean.zip)

https://graphicux.com/vector-converter-avatar-photoshop-plugin-v2/

**Comment by photopea** [comment]
Have you tried this? https://www.photopea.com/tuts/vectorize-raster-images/

**Comment by allansique** [comment]
> Você já tentou isso? https://www.photopea.com/tuts/vectorize-raster-images/

this function in phopea just vectorizes . The plugin I told you about has several treatments. It is a preset to give an illustration effect. And it's very good.  I'm from Brazil, São Paulo, where are you talking about?

**Comment by photopea** [comment]
Maybe you could ask the creator of that plugin to make a version for Photopea? Because I dont know how to make a similar plugin :(
