### ISSUE TITLE
Image metadata is deleted when exporting images

### ISSUE THREAD

**Issue by osamaaminaziz** [photopea/photopea#6162]
Your Operating System: Windows
Your Web Browser: Chrome & Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. upload an image that includes meta data
3. export as .webp
4. check the image meta on this website https://jimpl.com/
5. meta data not found.

**Comment by photopea** [comment]
I just tried it, but the step 5 does not work - your website shows a lot of metadata in my WebP file.

At step 3, you can see a checkbox "attach metadata". Did you enable it?

**Comment by osamaaminaziz** [comment]
Yes I have enabled the "attach metadata" option, also I have tried another two websites to check the image meta, and I have got the same result, here they are:
https://www.metadata2go.com/
https://brandfolder.com/

**Comment by photopea** [comment]
Could you be more specific about the step 2? Could you share a specific image with metadata, which I should use for this?

**Comment by osamaaminaziz** [comment]
Here is an image you can test with
https://drive.google.com/file/d/1wS9zUA_p6kDVdB9wLTMOAcoVaG57BVNa/view?usp=sharing
and here is a video that explains what I do exactly.
https://share.zight.com/jku66xGm
Thank you.

**Comment by photopea** [comment]
There is absolutely no problem with saving metadata to WEBP files!

But you have discovered another huge problem - Photopea can not read metadata out of PNG files, or save metadata into them! That is what is going on :) I will look into it.

**Comment by osamaaminaziz** [comment]
Happy to help :)) 
Thanks for your collaboration and your great software.

**Comment by photopea** [comment]
Photopea has its own tool to view, edit or create metadata. You can find it in File - File Info.

Photopea should detect metadata of your PNG file now. However, when I export a WEBP, your website still does not detect the "keywords" metadata. 

If you need a different WEBP file than what Photopea gives you, could you show us such a WEBP file with metadata?

**Comment by photopea** [comment]
Because I think that these websites can not detect metadata in WEBP files at all.

**Comment by osamaaminaziz** [comment]
I have converted the image to webp using the latest version of Photoshop (File > Save As > webp) and it worked good
https://drive.google.com/file/d/1UhQ2CMxQjgCq0UftB0AoBIZYcLJ7TktG/view?usp=sharing

**Comment by photopea** [comment]
ok, it should all be fixed now :)

**Comment by osamaaminaziz** [comment]
Worked well now! appreciate your help.
