### ISSUE TITLE
Menu items suddenly not working on www.photopea.com 

### ISSUE THREAD

**Issue by douggiereid** [photopea/photopea#6163]
This has been working perfectly until today. I last used thid about a week ago.
Now when I try to resize an image the resize dialog does not appear. Also when trying to save as PSD the Save As dialog does not apear.
I am using the latest Chromw browser on a fully updated Windows 10.
Extremely frustrating not to be able save the work I did.

**Comment by photopea** [comment]
One million people used Photopea in the last 24 hours. Nobody reported any problem. 

Did you try to use it in the Incognito mode, i.e. without your browser extensions?

**Comment by psociety** [comment]
He's not alone, this has been happening since few days ago.
It asks you to "constent" for ads, but you can't click constent because any click is prevented.

https://github.com/photopea/photopea/assets/29523682/5f0f1ce1-dcbd-4f37-868b-57549ad10f4b

Incognito/No icognito, deleting cookies/localStorage/sessionStorage anything fixes it but using a different laptop.
Chrome - LInux in my case.

**Comment by douggiereid** [comment]
Okay, I tried Incognito mode and it worked for me.  So I removed two old browser extensions I was no longer using and it works now. The extensions I removed where VideoStream and Volume Booster. Makes no sense to me why these have suddenly interfered with Photopea, but thanks so much for the help.

**Comment by photopea** [comment]
@psociety if you open Photopea for the first timein your life, or in Incognito mode, you should be asked to give Photopea a consent for ads. Have you been asked?

@douggiereid could you ask the creators of these extensions to fix it, so that you can use them again?

**Comment by psociety** [comment]
What you see on the video is my experiences right after deleting all cookies & cache data, so nope. Still as of today doesn't work.

**Comment by photopea** [comment]
@psociety But did you try it in the Incognito mode?

**Comment by psociety** [comment]
@photopea i've tried both cases: Incognito/No icognito, deleting cookies/localStorage/sessionStorage.

After randomly disabling extensions i've found which one seems to trigger the problem: `i don't care about cookies`. If i disable it and enable it back after accepting, it works :p

**Comment by photopea** [comment]
ok great! About 90% of problems with Photopea are caused by browser extensions, which modify the way photopea works.
