### ISSUE TITLE
Layer > Raster Mask > From Transparency leaves transparent border on texture

### ISSUE THREAD

**Issue by hybridherbst** [photopea/photopea#6165]
Your Operating System: MacOS
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Import this file: [TransparentCat.png.zip](https://github.com/photopea/photopea/files/13325142/TransparentCat.png.zip)
3. Select **Layer > Raster Mask > From Transparency**
4. Note that while color and transparency are separated, not all color pixels from the original image are restored – there's a transparent border around the entire image, with the RGB data from there missing:

<img width="832" alt="image" src="https://github.com/photopea/photopea/assets/2693840/493e304b-6843-4f2b-bb6a-a04f4ed74f34">

The actual PNG still contains that data:
| In Photopea | actual data in the file |
| - | - |
| <img width="570" alt="image" src="https://github.com/photopea/photopea/assets/2693840/4c187fe1-41df-451d-969d-5ec3c1f66914"> | <img width="487" alt="image" src="https://github.com/photopea/photopea/assets/2693840/18bd1c55-ec89-482b-ae59-d9e9c817e9e9"> |

A separate problem is that when exporting PNG again and repeating the steps above, all pixels where alpha=0 are written as black and lose their RGB data. Do you want me to open a separate issue for that?

**Comment by photopea** [comment]
This is the expected behaviour. When a pixel is fully transparent, it usually means that it contains no color information, or that its color information can be forgotten. Your image has many rows and columns of transparent pixels around the edges and we throw them away.

If you open a fully transparent PNG 1000x1000 px in Photopea, and there is a 100x100 px red non-transparent square in the middle, a photo editor should create a document with a single layer, which is 100x100 pixels. This is what our users expect to happen.

**Comment by hybridherbst** [comment]
> When a pixel is fully transparent, it usually means that it contains no color information, or that its color information can be forgotten.
This is an assumption that deletes data. Not sure when that is ever a good idea. I understand that "auto-cropping" the data makes sense when everything is black, but not when there's actual color data.

Photoshop seems to agree with that – here's the same operation in Photoshop, which doesn't produce a transparent border – it correctly restores the full color channel:
<img width="831" alt="image" src="https://github.com/photopea/photopea/assets/2693840/5ddb3160-809b-4037-8dff-847b1ef86d48">

**Comment by photopea** [comment]
Is it some "untold rule" that a pixel with no information should have all channels set to black, and setting the opacity to zero is not enough? Maybe we could implement it into Photopea (and delete only pixels which are zero in all four channels). 

I think sometimes in PNG, a line of transparent pixels has a color of the nearest non-transparent pixel, in order to improve the compression (to have many same values in a row).

**Comment by hybridherbst** [comment]
I looked at the spec just now.

I think it's pretty clear about RGB and Alpha channels being independent, e.g. [here](https://www.w3.org/TR/2003/REC-PNG-20031110/#figure42).

I think this section is also relevant (especially the part _In consequence an image editor can take a PNG image and easily change its transparency_ which currently wouldn't be true for the cat in Photopea, I can't easily just change it's transparency)
https://www.w3.org/TR/2003/REC-PNG-20031110/#6AlphaRepresentation
> The colour values in a pixel are not premultiplied by the alpha value assigned to the pixel. This rule is sometimes called "unassociated" or "non-premultiplied" alpha. (Another common technique is to store sample values premultiplied by the alpha value; in effect, such an image is already composited against a black background. PNG does not use premultiplied alpha. In consequence an image editor can take a PNG image and easily change its transparency.) See 12.4: [Alpha channel creation](https://www.w3.org/TR/2003/REC-PNG-20031110/#12Alpha-channel-creation) and 13.16: [Alpha channel processing](https://www.w3.org/TR/2003/REC-PNG-20031110/#13Alpha-channel-processing).

What's interesting is that the spec leaves some of the things we discussed as open to "use case interpretation", which is pretty annoying for a spec if you ask me, as it either requires options for users or a choice by an implementor that's then wrong for some use cases:

**Section 12.4 Alpha Channel Creation** https://www.w3.org/TR/2003/REC-PNG-20031110/#12Alpha-channel-creation

> The alpha channel can be regarded either as a mask that temporarily hides transparent parts of the image, or as a means for constructing a non-rectangular image. In the first case, the colour values of fully transparent pixels should be preserved for future use. In the second case, the transparent pixels carry no useful data and are simply there to fill out the rectangular image area required by PNG. In this case, fully transparent pixels should all be assigned the same colour value for best compression.

**Comment by photopea** [comment]
I made it work as Adobe Photoshop does: Photopea will throw away RGB values of transparent pixels only if the RGB value is black (zeros). So you should be able to recover the color of all pixels e.g. using "Mask from Transparency".

I still think it is a bad practice to use the fourth channel of PNG images to store any data other than the transparency ("shape"). 90% of photo editors will set transparent pixels to a black color, to improve the compression during the PNG export.
