### ISSUE TITLE
Your browser (or an extension) is modifying our code.

### ISSUE THREAD

**Issue by MobileCowCamp** [photopea/photopea#6169]
Photopea will not load a .png file. Photopea gives me the following error, "Your browser (or an extension) is modifying our code." What do I have to do to use the program?

**Comment by photopea** [comment]
It probably means, that you installed a browser extension, which modifies the code of Photopea. To use Photopea, you need a web browser (which runs websites as they are, without modifying them).

Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
