### ISSUE TITLE
Error en la Galeria

### ISSUE THREAD

**Issue by cholombati** [photopea/photopea#6170]
Cuando se incia la galeria de imagenes hay un error, no estaba pasando anteriormente
![error en galeria](https://github.com/photopea/photopea/assets/130771596/ab12a325-d541-470c-b4dd-4be2065c7f5b)

**Comment by photopea** [comment]
I just tried it and it works fine for me.

In what country are you located? Does your internet work well?

**Comment by cholombati** [comment]
Hola, soy de Argentina. Hasta agosto funcionó perfectamente. Este mes noté
el problema

**Comment by photopea** [comment]
Can you access https://pixabay.com/ ?

**Comment by cholombati** [comment]
No, desde la red en la que me conecto cuando trabajo (Escuelas estatales de
la Ciudad de Buenos Aires) no me lo permite

**Comment by photopea** [comment]
Ask your internet provider to let you access https://pixabay.com/ . The photos in our gallery are from this website.

**Comment by cholombati** [comment]
Thanks, I'll check them out.

**Comment by cholombati** [comment]
Confirmado, el problema era el firewall, Muchas gracias!
