### ISSUE TITLE
Dropdown menus not functioning on app

### ISSUE THREAD

**Issue by saahilveneno** [photopea/photopea#6172]
The dropdown menus (e.g. for changing layer style) don't work on the app, but work fine on browser (using a mac if that matters)

**Comment by photopea** [comment]
It was reported before, but I could not reproduce it.

I have a Macbook Air. Could you tell me, what should I do (what OS do I need, what browser etc) to see it myself?

**Comment by saahilveneno** [comment]
Currently on a 2021 MacBook Pro, OS in sonoma 14.0 (technically not the newest one but this has been an issue when I was on previous mac versions as well). Downloaded it off of chrome. Uploading a short clip of the issue below, as you can see I can click on the opacity slider perfectly fine but when I click on the "normal" button, nothing happens

https://github.com/photopea/photopea/assets/88685873/1623b22f-0583-4d36-987f-c5b82002617a

**Comment by saahilveneno** [comment]
Lol so just realized that this issue actually only occurs in full screen on the app, when not in full screen the button works fine. Where do I have to right click on photopea to get that option? I don't see it

**Comment by saahilveneno** [comment]
Lol so just realized that this issue actually only occurs in full screen on the app, when not in full screen the button works fine. Where do I have to right click on photopea to get that option? I don't see it

**Comment by saahilveneno** [comment]
Lol so just realized that this issue actually only occurs in full screen on the app, when not in full screen the button works fine. Where do I have to right click on photopea to get that option? I don't see it

**Comment by photopea** [comment]
you can right-click any place of the editor, e.g. the File button at the top left.

**Comment by photopea** [comment]
What if you try it at www.photopea.com in fullscreen (not in the installed app), do dropdown menus work?

**Comment by saahilveneno** [comment]
Yep photopea.com in fullscreen works perfectly fine

**Comment by photopea** [comment]
I think it is a bug in Mac OS or in Chrome. Could you report it to Google / Apple? I can not reproduce it on my devices (so it would be weird to report a problem I have never seen myself).
