### ISSUE TITLE
Trying to edit PSD action set in photopea

### ISSUE THREAD

**Issue by neekera** [photopea/photopea#6173]
Your Operating System: Windows
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. upload the action and brushes
3. select shape you want to use for the action
4. this is where i run into problems.
5. im trying to turn shapes or vectors into knit style 

i am trying to design a Ugly Christmas knit style sweater using shapes i want to turn into knit. 
 i cant figure out how to edit the posturize and threshold into the action 
Please help i am completely lost, its been 3 days and i still cant figure it out 

I have attached the introduction provided with the download but they are for PS not photopea
this is the action i download if this helps. https://www.creativefabrica.com/product/knitted-effect-ugly-christmas-sweater/
https://youtu.be/lmGjJtBhOjE?si=hLs9Iich6ViJAU_5

![act7](https://github.com/photopea/photopea/assets/148263398/75d1936b-e617-4069-82de-669d087d35d8)
![act6](https://github.com/photopea/photopea/assets/148263398/f260ad4b-cc73-4cd7-8952-ac5123f9fb62)
![act5](https://github.com/photopea/photopea/assets/148263398/2ea6a2d9-40da-4d85-96c8-c95bfab6246a)
![action 4](https://github.com/photopea/photopea/assets/148263398/0ea0bc52-271d-483b-97f5-4f10d4bfb0fe)
![act 3](https://github.com/photopea/photopea/assets/148263398/cbb41490-1b7b-4f9f-9766-5cb2002994e8)
![action2](https://github.com/photopea/photopea/assets/148263398/b469a7bb-9c89-476a-bf99-00e7b37fee20)
![actiot1](https://github.com/photopea/photopea/assets/148263398/e1d1fdd7-f9c1-4e80-a22b-1ed38fcfe2fc)

**Comment by camoody1** [comment]
These screenshots are actually too low of a resolution to be able to read. In general, though, it's important to keep in mind that Photopea is not an exact copy of Photoshop. There isn't always an exact tool for tool replacement in Photopea. So, actions made in Photoshop are not guaranteed to work in Photopea. If the pattern on Creative Fabrica was free, I'd take a look at it to see what I could find, but sadly, it is not.

**Comment by photopea** [comment]
@neekera Are you asking us to buy Photoshop Acitons for $150 to be able to see the issue?

Could you maybe attach them here? I will try to look into it. But in general, we can not guarantee a 100% support of Photoshop actions. You should not buy such expensive actions if you dont have Photoshop, unless the author says they work in Photopea.

**Comment by neekera** [comment]
> @camoody1
 No not asking anyone to buy anything. Yes I can send you the file no problem I need all the help I can get lol but how do I send it to you  privately I don't wanna post it publicly. Can I send you a private message or Google drive link

**Comment by camoody1** [comment]
> > @camoody1
> > No not asking anyone to buy anything. Yes I can send you the file no problem I need all the help I can get lol but how do I send it to you  privately I don't wanna post it publicly. Can I send you a private message or Google drive link

Not me, @photopea 🙂

**Comment by photopea** [comment]
You can send me the actions to support@photopea.com

**Comment by photopea** [comment]
I just tried to run your action in Photoshop and in Photopea, and it works exactly the same in both.

The only difference is that Photoshop allows you to change the Posterize parameter while running it. But Photopea can not do this at the moment (pause the action execution to let you specify extra parameters). So with default parameters, Photoshop and Photopea give identical results.

**Comment by neekera** [comment]
Yes this exactly what I looking for. I want to turn any image or shape into a knitted style effect. When I tried it before I wasn't getting the results I wanted.  Can you break down how u got this to work correctly. Also how do I pause the action and adjust  the posterize parameters. You been a great help

**Comment by photopea** [comment]
Just open the ATN, ABR and PAT files in Photopea / Photoshop, and open your image in Photopea / Photoshop, and then, play a specific action (in Photopea or Photoshop). At the end, Photopea and Photoshop gave me the same results.

You can learn more here: https://www.photopea.com/learn/actions  or just buy a book about Adobe Photoshop to learn how to use Photoshop / Photopea or create your own actions.
