### ISSUE TITLE
Cannot open this PDF properly

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6174]
Your Operating System: ChromeOS
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**

1. Go to www.photopea.com
2. Open this file [1.pdf](https://github.com/photopea/photopea/files/13358381/1.pdf)
3. Should look like this 
![image](https://github.com/photopea/photopea/assets/11801254/3f71d405-9d61-4ef6-a50f-0a00a2d32d14)

4. But it looks like 8 white canvas

**Comment by photopea** [comment]
Your PDF file actually contains Adobe Illustrator data, so Photopea handles it as the Adobe Illustrator file (all PDF content is ignored).

As the AI file, it contains eight placed bitmaps - /Volumes/Macintosh SSD/Rodrigo/sopa/puzzlle Bode/1.psd  ... up to 8.psd. Photopea can not work with placed bitmaps in AI files yet, it can work only with embedded bitmaps.

I have changed the way Photopea works: if you open an Adobe Illustrator file, but the file name ends with ".pdf", Photopea will process it as a PDF file (ingoring the Adobe Illustrator content).

**Comment by TheRadicalDreamer** [comment]
Thanks!!

Now i can open it and see the image! :D
