### ISSUE TITLE
error analize charIDToTypeID

### ISSUE THREAD

**Issue by pluto-ZZZZ** [photopea/photopea#6176]
u can see pic below.
CharIDToTypeID doesn't work, and it returns what i input.
eg:  console.log(charIDToTypeID("ASet") ) --> ASet
link:https://www.photopea.com/api/playground
![1111](https://github.com/photopea/photopea/assets/54714869/cfe90147-d63f-43a8-b054-7cd5510ed4a4)
![2222](https://github.com/photopea/photopea/assets/54714869/a5dd99e7-69d6-4a4c-8c16-8b0d1602656e)

**Comment by pluto-ZZZZ** [comment]
The correct return value should look like the following pic.
https://zhuanlan.zhihu.com/p/600014746
![3333](https://github.com/photopea/photopea/assets/54714869/444f9b67-04fc-4010-93da-9f8593dd6e58)

**Comment by pluto-ZZZZ** [comment]
It appears that photopea does not implement action-related scripts
![5555](https://github.com/photopea/photopea/assets/54714869/1aa1c15c-78f4-457f-bba7-29b0d3f168a4)

**Comment by photopea** [comment]
Hi, could you send me a script, which works in Adobe Photoshop, but does not work (or works differently) in Photopea?

**Comment by pluto-ZZZZ** [comment]
var desc = new ActionDescriptor();
var ref1 = new ActionReference();
ref1.putName( charIDToTypeID("ASet"), "autorun" );
desc.putReference( charIDToTypeID('null'), ref1 );
app.executeAction( charIDToTypeID('Dlt '), desc, DialogModes.NO);

**Comment by photopea** [comment]
It is fixed now! Do you have any other scripts?

**Comment by photopea** [comment]
I have to close it now, but you can still send me more scripts.
