### ISSUE TITLE
Trouble removing AdBlock Plus while using Edge Browser

### ISSUE THREAD

**Issue by ftyari33** [photopea/photopea#6177]
Your Operating System: Windows 10
Your Web Browser: Microsoft Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Either use incognito or not
3. Turn off the Adblocker (I'm using Adblock Plus)
4. Refresh the page (so that the changes take place)
5. And then try doing actions such as clicking the menu options above (File, Edit, Image etc...)

I know that ads help you maintain photopea, but if I turn off my adblocker the app is simply unusable!
Also! the button "Change Consent" on the top right does not do anything at all. I haven't tried it in other browsers, this is an issue I'm facing while using Microsoft Edge.
Here are some screenshots:
![AdBlock_Issue (1)](https://github.com/photopea/photopea/assets/115432847/ad316170-82d1-42d2-bd10-e2f7f85cf181)
![AdBlock_Issue (2)](https://github.com/photopea/photopea/assets/115432847/43c57762-0bfe-490e-a5a0-53dd1acd7802)
![AdBlock_Issue (3)](https://github.com/photopea/photopea/assets/115432847/f7b49da8-2adf-44d6-bec3-45c50d51db18)
![AdBlock_Issue (4)](https://github.com/photopea/photopea/assets/115432847/db263aab-568e-486c-bce0-2a1b87460d73)
![AdBlock_Issue (5)](https://github.com/photopea/photopea/assets/115432847/b6e4eb40-51fd-4615-9cd8-252928a86a33)

**Comment by photopea** [comment]
I have installed AdBlock Plus into MS Edge, and turned it off for Photopea. I can see ads in Photopea.

Do you have any other extensions? Are you from Canada?

![image](https://github.com/photopea/photopea/assets/15955558/c1869ff0-18f2-4b31-a9c2-f89bfb49af6e)

**Comment by ftyari33** [comment]
I have these other 2 extensions and I'm from Greece.
I also tried restarting the browser, but nothing!
![Screenshot (13)](https://github.com/photopea/photopea/assets/115432847/6c0b6bc9-006d-4130-a21e-b9d501a9a725)

**Comment by photopea** [comment]
Could you disable all your extensions and try Photopea again?

**Comment by ftyari33** [comment]
> Could you disable all your extensions and try Photopea again?

Thanks! I disabled the cookie extension and now everything works fine!

**Comment by photopea** [comment]
ok, great!
