### ISSUE TITLE
Polish special letters 'ą,ś,ć,ę etc' are not visible after exporting to pdf

### ISSUE THREAD

**Issue by LachaCDV** [photopea/photopea#6178]
Your Operating System: Win 10 64bit
Your Web Browser: Opera GX
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Type something with text tool with polish special letters
3. export file to pdf
4. Letters dissapears

**Comment by photopea** [comment]
We can not embed fonts into PDF files yet. Please, enable "Vectorize text" when exporting a PDF.
