### ISSUE TITLE
Editing window of layer name not as long as the whole layer row

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#618]
Any layer name longer than 12 character long will be cut off While editing

**Comment by photopea** [comment]
What do you mean? as you type, you should still see the cursor.

**Comment by hgs54371** [comment]
Full layer name
![screen shot 2018-04-04 at 4 04 52 am](https://user-images.githubusercontent.com/36803688/38272998-7551b4a0-37bd-11e8-987e-741ef237f2de.jpg)
Can only see 12 character at a time when editing
![screen shot 2018-04-04 at 4 05 19 am](https://user-images.githubusercontent.com/36803688/38272999-765596aa-37bd-11e8-9bef-a9bd49016003.jpg)

**Comment by photopea** [comment]
But you can move the cursor with arrows to any part of the name, right?

**Comment by photopea** [comment]
There can be effects and some other icons on the right, we can not make the input field wider.
