### ISSUE TITLE
a bug about doAction.

### ISSUE THREAD

**Issue by pluto-ZZZZ** [photopea/photopea#6180]
I used the script to import three jpg files and one atn file at the same time, and directly used doAction, but the system showed that the atn file was not loaded when I doAction, but in fact, when the atn file was imported, the system has returned done, how can I judge whether the atn file was imported successfully?
![7777](https://github.com/photopea/photopea/assets/54714869/7a72b2d5-7390-42e0-b352-eb5ec87eb1ba)
![888](https://github.com/photopea/photopea/assets/54714869/971fd127-b73e-4d22-bfcd-e732fd4f3624)

**Comment by photopea** [comment]
Hi, could you report the issue with the template, together with steps to reproduce the issue?
