### ISSUE TITLE
Cannot load local fonts on my Mac

### ISSUE THREAD

**Issue by MrLeolong** [photopea/photopea#6181]
Your Operating System: MacOS 10.15.7
Your Web Browser: Chrome 116.0.5845.140
The problem happens in the Incognito Mode, too:  Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Install the Chrome App version
3. Start a new project
4. Add new text
5. Change the fonts of the text
6. Check the "load local fonts" Option
7. It always shows the "Loading local fonts...", then nothing happens

**Comment by photopea** [comment]
I think there is one font in your local fonts, which Photopea can not process.

Can you open www.Photopea.com and drag-and-drop your fonts into Photopea, until finding a font which Photopea can not handle? Then, could you send us that font?

Do you have any fonts, which are not TTF or OTF?

**Comment by photopea** [comment]
I have to close it because of lack of details.
