### ISSUE TITLE
suggestion: Please make it possible to save or export AI files in Photopea.

### ISSUE THREAD

**Issue by hank3149** [photopea/photopea#6182]
Your Operating System: ms
Your Web Browser: Brave
The problem happens in the Incognito Mode, too:
**no problem but suggestion : Please add the ability to save or export AI files in Photopea.**

**Comment by camoody1** [comment]
@hank3149 Try this developer's other application, [Vectorpea](https://vectorpea.com). It's more focused on vector-based images like Adobe Illustrator. I know you can export as .ai from that app.

**Comment by photopea** [comment]
You need to use Vectorpea to export AI files.
