### ISSUE TITLE
Minor issue with keyboard shortcut that leads to incognito mode

### ISSUE THREAD

**Issue by ftyari33** [photopea/photopea#6183]
Your Operating System: Windows 10
Your Web Browser: Microsoft Edge
The problem happens in the Incognito Mode, too: Yes 

**This must be done to see the problem**
1. Go to www.photopea.com
2. Start any new project
3. Use the provided shortcut to create a new layer (ctrl + shift + N)

I've noticed that I can use (ctrl + shift + alt + N) instead. Is there a way to update the displayed shortcut for specific browsers like Edge? Or is there a way to ignore Edge's incognito shortcut while using your app?
Thanks!
![Screenshot (16)](https://github.com/photopea/photopea/assets/115432847/50cbc985-a5fa-46ae-ad1e-0a3a427d5c71)

**Comment by photopea** [comment]
I just noticed, that it works the same in Chrome :(

I also noticed, that if you go fullscreen, you can use any shortcut, e.g. Ctrl+T for Free Transform, ect.

**Comment by ftyari33** [comment]
> I just noticed, that it works the same in Chrome :(
> 
> I also noticed, that if you go fullscreen, you can use any shortcut, e.g. Ctrl+T for Free Transform, ect.

Fullscreen worked on Edge too! Thanks!

**Comment by photopea** [comment]
Okay, I will close it for now, as there is nothing I can do about it.

But I still think it is a bug in web browsers, and that they should fix it (and let us use any shortcut we want).
