### ISSUE TITLE
NOT OPENING THE IMAGES 

### ISSUE THREAD

**Issue by Whispeywolf126** [photopea/photopea#6184]
Your Operating System: Mac os catalina
Your Web Browser: google chrome

**This must be done to see the problem**
1. Go to www.photopea.com
2. open any file
3. try to open an image
4. it hangs on the screen
5. `
<img width="1440" alt="Screenshot 2023-11-18 at 8 58 37 PM" src="https://github.com/photopea/photopea/assets/105842483/90e28dc2-2e1e-489d-b970-50ae34d5764b">
<img width="1440" alt="Screenshot 2023-11-18 at 8 58 35 PM" src="https://github.com/photopea/photopea/assets/105842483/8298cc02-41d3-4faf-8808-e8e3402dac2b">
<img width="1440" alt="Screenshot 2023-11-18 at 8 58 30 PM" src="https://github.com/photopea/photopea/assets/105842483/c463cec8-9e80-4da5-91f2-3c87d35e89eb">
<img width="1440" alt="Screenshot 2023-11-18 at 8 58 24 PM" src="https://github.com/photopea/photopea/assets/105842483/e50cbe85-621e-45e7-822c-fc3c732e8b2c">

`

**Comment by photopea** [comment]
did you solve it?
