### ISSUE TITLE
Text boxes in PDF are not correctly sized

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6188]
Your Operating System: ChromeOS
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open this file ([pdf_1700536960359.pdf](https://github.com/photopea/photopea/files/13421426/pdf_1700536960359.pdf))
3. Check the text boxes. Many of them are less wide than it should.
4. Examples:
![image](https://github.com/photopea/photopea/assets/11801254/0ad6e194-9b8b-45ef-b759-429ba2698d29)
----
![image](https://github.com/photopea/photopea/assets/11801254/b661a416-4b50-4ab4-bf45-198660aa4403)
----
![image](https://github.com/photopea/photopea/assets/11801254/fd58a550-867e-4610-8372-83c5ca762c9c)

**Comment by photopea** [comment]
I have improved it a bit :)

In this case, the PDF contains the X and Y coordinate of the beginning of each line of text. The PDF processor should have fonts (Helvetica - the font is not inside PDF), and should calculate the width of a line according to this font. As we dont have the Helvetica font, we are approximating it.

**Comment by TheRadicalDreamer** [comment]
way better!!

Still some texts are not aligned:
![image](https://github.com/photopea/photopea/assets/11801254/a3e56c4c-a8ed-4112-97c0-cdc4d5f3dbfd)


It is not too important, but i am just noticing
