### ISSUE TITLE
Asking for help on mobile devices in Photopea.

### ISSUE THREAD

**Issue by Blad-Runnner** [photopea/photopea#6189]
Hi! I´m new on this.
I wished write to the developers of Photopea, cause I¨ve been tried to use it on my mobile (Android or IOS) but there are troubles:
- the image after upload, appears upside down
- when I try to use the bottons like: "bright, contrast", "intensity of color", etc, the image is damaged on the background, and loose some of the original background.
- the use on mobiles is a little hard,even on coumputer site.

I just wished, if you want to review it, or check it, and try also to make a solution to be more exteneded the use of the platform. Not only on computers, but also on mobiles devices.
I¨ll thank you if you read this note, and you try to verify it, and check if there´s a way to help on this.

Thanks for all.

**Comment by photopea** [comment]
There are about 300,000 people who use Photopea on phones every day. Nobody reported any problems.

Could you try this and let me know if it helped? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of lack of details.
