### ISSUE TITLE
PeaMark GPU Result is Innacurate

### ISSUE THREAD

**Issue by v1phor** [photopea/photopea#6191]
Your Operating System: Windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes.

**This must be done to see the problem**
1. Go to www.photopea.com
2. Use the PeaMark tester.
3. CPU result is realistically accurate. GPU result starts saying Infinity then changes to 2186933 when I use integrated graphics.
4. Tried again and similar absurd results.

**Comment by photopea** [comment]
No matter what I do, I can not see Infinity shown in PeaMark :(

Are you sure it happens in the Incognito, too? Is your Chrome updated? What device do you have / how old is it?

**Comment by photopea** [comment]
Also, could you open "about://gpu" in your web browser and show us what you see there?

**Comment by v1phor** [comment]
> Also, could you open "about://gpu" in your web browser and show us what you see there?

[about-gpu-2023-11-27T14-03-44-002Z.txt](https://github.com/photopea/photopea/files/13476062/about-gpu-2023-11-27T14-03-44-002Z.txt)

**Comment by v1phor** [comment]
> No matter what I do, I can not see Infinity shown in PeaMark :(
> 
> Are you sure it happens in the Incognito, too? Is your Chrome updated? What device do you have / how old is it?

Yes it happens in Incognito too. Yes it is up to date (Version 119.0.6045.160 (Official Build) (64-bit)). The device is an Acer Veriton Desktop but I do not know about the age due to it being a school computer.

**Comment by v1phor** [comment]
> When the test shows Infinity, could you look into a web console (right-clic, "Inspect", "Console") and show us a screenshot of what you see there?

[www.photopea.com-1701183162358.log](https://github.com/photopea/photopea/files/13489565/www.photopea.com-1701183162358.log)

**Comment by photopea** [comment]
Could you maybe record a short video of running the PeaMark for the GPU in the Incognito mode, and showing the web console once it finishes?

**Comment by photopea** [comment]
I see that your CPU is i3-3220, released in 2012. Maybe it can not handle a single run of our GPU test (Chrome kills every GPU process, which takes more than 3 seconds). 

When you press More - Use WebGL, is it enabled? Is it available?

**Comment by photopea** [comment]
I see that your CPU is i3-3220, released in 2012. Maybe it can not handle a single run of our GPU test (Chrome kills every GPU process, which takes more than 3 seconds).

When you press More - Use WebGL, is it enabled? Is it available?

Also, what CPU score do you get?

**Comment by v1phor** [comment]
> When you press More - Use WebGL, is it enabled? Is it available?
I can see WebGL and it is automatically enabled.

> Also, what CPU score do you get?
I get a score around 367.

**Comment by v1phor** [comment]
> Could you maybe record a short video of running the PeaMark for the GPU in the Incognito mode, and showing the web console once it finishes?

[https://streamable.com/us4gag](url)

**Comment by v1phor** [comment]
> I have made the GPU test about 2x faster, could you try to run it again?
> 
> In your console, there is an error at the end: "WebGL: CONTEXT_LOST_WEBGL...". After this error, the test result are not real.

Yeah I think it works now since the GPU score is now 28 which would be realistic for the integrated graphics of a 10 year old computer.

**Comment by photopea** [comment]
Otherwise, I honestly think you could buy a used computer from 2016 for $150, e.g. Lenovo ThinkCentre M900 Tiny (I bought it for my dad)

And your CPU score would be 2x bigger, your GPU score would be 15x bigger, and you will "feel the difference" while using Photopea and other programs :) I think it is really worth it, if you have $150 - $200.
