### ISSUE TITLE
a bug about doAction

### ISSUE THREAD

**Issue by pluto-ZZZZ** [photopea/photopea#6192]
saveToOE will not return all layers after this code is run, only 2 layers, but saveToOE will return all layers manually. Can you help me find out why? Or can you tell me how I can export all the layers directly after doAction?

[Photopea-api-demo-2.zip](https://github.com/photopea/photopea/files/13451191/Photopea-api-demo-2.zip)

**Comment by pluto-ZZZZ** [comment]
You can see the bug by double-clicking test.html. The unzip password is "photopea".
[test.zip](https://github.com/photopea/photopea/files/13454369/test.zip)

**Comment by pluto-ZZZZ** [comment]
No need ""

**Comment by pluto-ZZZZ** [comment]
I know that you can use the sleep function to let the system wait for the picture to be completely imported before execution, but the waiting time cannot be fixed, which will cause sometimes effective and sometimes not effective. So I wanted to ask you if there's any way to make sure it's done 100% correctly.

**Comment by pluto-ZZZZ** [comment]
You can see the bug by double-clicking test.html. The unzip password is "photopea".

I know that you can use the sleep function to let the system wait for the picture to be completely imported before execution, but the waiting time cannot be fixed, which will cause sometimes effective and sometimes not effective. So I wanted to ask you if there's any way to make sure it's done 100% correctly.

On my computer, sleep200ms will get the correct result, 50ms will not.
[test.zip](https://github.com/photopea/photopea/files/13454454/test.zip)

**Comment by pluto-ZZZZ** [comment]
If you can provide an "app.open" synchronization function, that would be a great help to me. If I understand correctly, there are only asynchronous functions at the moment, and your web page will return "done" before performing the import process.
Wait for your good news.

**Comment by pluto-ZZZZ** [comment]
If you still can't replicate the bug, try downloading pycharm and using pycharm to import chrome.

![image](https://github.com/photopea/photopea/assets/54714869/68cac44f-05bf-4c72-bc87-2368b67fb850)
![image](https://github.com/photopea/photopea/assets/54714869/4150bd7b-ca6b-43b4-8ef2-f04d1090337d)

**Comment by photopea** [comment]
When you send Photopea a script: "app.open(...url...)", you should expect two "done" messages! The first is sent when the script finishes. The second is sent when the file was loaded and processed. So just replace if(n==2) with if(n==3), and so on

To avoid this, simply send Photopea an ArrayBuffer inside postMessage() - you will get just one "done".

**Comment by pluto-ZZZZ** [comment]
In fact, the code I sent you above does just that, starting with 1 when importing the atn file. Import "app.open(... url...) "When it was 2. When the atn file is executed, it goes directly to 4 instead of 3. But it still runs with the bugs I mentioned. This bug causes saveToOE to save only the first two imported layers instead of all the layers.
![image](https://github.com/photopea/photopea/assets/54714869/b362b3cc-cac9-4dbc-be6b-b7df74b7cf24)

**Comment by pluto-ZZZZ** [comment]
In fact, the code I sent you above does just that, starting with 1 when importing the atn file. Import "app.open(... url...) "When it was 2. When the atn file is executed, it goes directly to 4 instead of 3. But it still runs with the bugs I mentioned. This bug causes saveToOE to save only the first two imported layers instead of all the layers.

PS: If you change 2 to 3, as you say, then 3 will not be executed, because the atn file will only return a done. If it is convenient for you, you can try to modify the code to see the effect.

![image](https://github.com/photopea/photopea/assets/54714869/edf68309-b555-4220-bee7-e5ad06c8ab30)

**Comment by pluto-ZZZZ** [comment]
I tried some according to you, use "app. Open https://www.photopea.com/api/playground (... url...) "Only one done is returned. Is there a problem? Is there a problem with base64 image loading?
![image](https://github.com/photopea/photopea/assets/54714869/d0675124-614a-455a-ae16-6414125d33e6)

**Comment by pluto-ZZZZ** [comment]
I according to you to try some, at https://www.photopea.com/api/playground. Use "app.open(... url...) "Only one done is returned. Is there a problem? Is there a problem with base64 image loading?
![image](https://github.com/photopea/photopea/assets/54714869/1f371e49-e114-4a4e-ae84-98c0f68d268d)

**Comment by photopea** [comment]
Ok, so I was wrong. "app.open(...url...)" sends a second "done" only when loading an image. It is hard to tell when the action will be added into Photopea (and ready to use) - it could be tens of MB in size, loaded from a different server (we dont check if the URI contains the file itself to do it instantly).

So just send the action as an ArrayBuffer and it should be fine.

**Comment by pluto-ZZZZ** [comment]
If you want to import images, can't you use base64 encoding? It can only be imported as an ArrayBuffer, otherwise the image will not load in real time.

**Comment by pluto-ZZZZ** [comment]
Do you have a reliable base64 encoded image to ArrayBuffer js tool? I have a lot of base64 encoded images, and it would be difficult to use without a tool to convert ArrayBuffer.

**Comment by photopea** [comment]
You can convert base64 to ArrayBuffer with four lines of code. Just make the opposite of your function arrayBufferToBase64()

**Comment by pluto-ZZZZ** [comment]
I followed your tutorial to try to import images. When the data type is arraybuffer, I can return done after the complete import, but now I find a new problem, when I want to import multiple image files in a psd file using your method, He opens each image file as a new psd file with a default name of "file.psd". There is no such option in the api you provide." wnd.postMessage(msg, "*");" . Is there any other way to batch import files via arraybuffer?
![image](https://github.com/photopea/photopea/assets/54714869/d2c4e077-3239-4fa8-9126-a611bad5db29)
![image](https://github.com/photopea/photopea/assets/54714869/457ce4d5-bec7-4c16-8bd0-aca98f1e796a)

**Comment by photopea** [comment]
I will close it now, but we can keep discussing it.

**Comment by pluto-ZZZZ** [comment]
Can you give a demo? I don't know of any api for copying layers between psd's.

**Comment by pluto-ZZZZ** [comment]
Your page doesn't seem to be giving the correct demo
![image](https://github.com/photopea/photopea/assets/54714869/04ca1920-5216-4e94-939d-2f107bc72a15)

**Comment by photopea** [comment]
You must have an active (selected) layer for that demo to work.
