### ISSUE TITLE
weird pattern on images

### ISSUE THREAD

**Issue by anniebooboos** [photopea/photopea#6193]
this weird pattern happens on my images and psds when i try to edit? i'm not sure if it's a bug or if my nephew did something when he was on my laptop
![oie_MOw93wTjFyfQ](https://github.com/photopea/photopea/assets/140460488/d6ab6aea-c46e-4be6-9c57-32ad77f63892)

Your Operating System:
Your Web Browser: google chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by anniebooboos** [comment]
ah thank you so much ! that helped/worked <3

**Comment by photopea** [comment]
great! :)
