### ISSUE TITLE
HTTP error: 401 : User's secret was already generated.

### ISSUE THREAD

**Issue by RobertWo495** [photopea/photopea#6194]
Your Operating System: Windows 10
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Go to the red button called **Account** at the topbar.
3. Then go to the **Log in** button and then **Login with Google**.
4. Then open **PeaDrive** and it shows this message: **HTTP error: 401 : User's secret was already generated.**

I see that message and I can't access to my files, also I have very important files there. Does anyone know how to fix this? Thanks.
![image](https://github.com/photopea/photopea/assets/151863227/bb658b3c-8ef6-4581-ac0a-d369d8a9b6e3)

**Comment by RobertWo495** [comment]
Can someone help me please? I still having that issue and I have really important files there.

**Comment by camoody1** [comment]
@photopea I think this person requires some assistance on the server side. Reference ticket #5420

**Comment by photopea** [comment]
Please, tell me your email address which you see after clicking the "Account" button. You can write it here on github or send an email to [support@photopea.com](mailto:support@photopea.com)

**Comment by RobertWo495** [comment]
@photopea anexoexpress@gmail.com

**Comment by photopea** [comment]
It should be fixed now. Could you close Photopea and open it again?

**Comment by RobertWo495** [comment]
Sorry but I had another issue, when I want tonuse the the **ctrl+alt+t** for free transform tool, it doesn't work.

**Comment by photopea** [comment]
Could you share a screenshot of your whole screen when you are pressing Alt+Ctrl+T?

**Comment by RobertWo495** [comment]
Yes, as you can see here I press Alt+Ctrl+T but nothing happens. Im trying to scale the image but I can't with the Alt+Ctrl+T.
![image](https://github.com/photopea/photopea/assets/151863227/2a23947c-09f9-4e50-ac1e-afca84d58e46)

**Comment by photopea** [comment]
Can you press Edit - Free Transform? Does it work?

You did not share the whole screen, and we can not see how many browser extensions you are using :( Your extensions could be breaking the functionality of keyboard shortcuts.

**Comment by RobertWo495** [comment]
When I use Edit - Free Transform it works, but with keyboard doesn't. Also I don't have any extensions, I tried on all my commputers to use photopea on them and on Incognito too and still not working no metter what commputer I use.

**Comment by RobertWo495** [comment]
The only extension I have is called **Google Docs Offline** and it's a default extension as I never installed any extension on this commputer because it's new.

**Comment by RobertWo495** [comment]
Thank you so much for the help! Also I already sloved the free transformation, so it's working now, thanks!

**Comment by photopea** [comment]
What was the problem?

**Comment by Loyalnaorem** [comment]
Please help mine is also not working the same issue
