### ISSUE TITLE
Your site become super super slow

### ISSUE THREAD

**Issue by jlw484** [photopea/photopea#6195]
Your Operating System: Windows
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com

Hi, your website become super super slow when upload, edit, download image. Even for a small image with 200kb of size.

Thank

**Comment by photopea** [comment]
Hi, what is the resolution of your image in pixels?

Also, what is your PeaMark? You can find it in More - PeaMark.

**Comment by grass29** [comment]
Same or similar - can't use magic replace, it's stuck processing.

**Comment by photopea** [comment]
I have to close it because of lack of details. The Magic Replace works now.
