### ISSUE TITLE
When Exporting Images and trying to send it on discord it doesn't load in.

### ISSUE THREAD

**Issue by MotorSportrauma** [photopea/photopea#6196]
Your Operating System: Acer
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Made an image
3. Export it
4. send it on discord or anything and it will not load in

**Comment by camoody1** [comment]
What exactly do you mean "send it on discord or anything"? When you choose to Export an image, you're asked to choose a file type. You're not asked to send it anywhere. Are you able to export your image as PNG or JPG?

**Comment by MotorSportrauma** [comment]
Any format of image and it wont send, it would go to the sad emoji which bascially means it didn't send correctly.
![Screenshot 2023-11-25 114458](https://github.com/photopea/photopea/assets/151983662/a8534a9f-6811-4ce7-ba66-ac60c288b977)

![Screenshot 2023-11-25 114511](https://github.com/photopea/photopea/assets/151983662/3bafca09-7985-4eb5-a7cd-453d7776ff63)

**Comment by photopea** [comment]
When you export a JPG image in Photopea, can you open it in the image viewer, or in any other program?

**Comment by MotorSportrauma** [comment]
Yea I can open it in my "Photos" app for Windows 11

**Comment by MotorSportrauma** [comment]
But when I send it on discord, This also happens to stuff I make for Roblox. It just says "There was an error"

**Comment by photopea** [comment]
Can you send a JPG image, which was not made by Photopea, to Discord?

**Comment by camoody1** [comment]
@MotorSportrauma I really don't think this is a Photopea issue. How large are your images?

**Comment by MotorSportrauma** [comment]
> @MotorSportrauma I really don't think this is a Photopea issue. How large are your images?

2.2MB as a JPG
and
2,036 KB as a PNG

**Comment by MotorSportrauma** [comment]
oh thats the reason huh, Well thanks.

**Comment by MotorSportrauma** [comment]
it works now.

**Comment by photopea** [comment]
What was the problem?

**Comment by MotorSportrauma** [comment]
the file was too big I guess, i put the quality to 50% and it works now

**Comment by camoody1** [comment]
@MotorSportrauma Yeah, Discord has a really small image limit.

**Comment by photopea** [comment]
But Discord should tell you that a file is too large, right?

**Comment by camoody1** [comment]
Interesting. I was just able to upload a 5MB jpg to my personal Discord server. Maybe whichever server he/she is uploading to has a lower limit. I don't know. 🤷‍♂️

**Comment by photopea** [comment]
I will close it now.
