### ISSUE TITLE
Mobile phone Cancel/Leave query.

### ISSUE THREAD

**Issue by bluep55** [photopea/photopea#6198]
I don't know if it's a bug in Photopea mobile version or something that is specific to my phone.
Android on a Samsung phone.
I accidently pressed the back button at the bottom of my screen while using Photopea on my phone.
A pop up appeared asking if I wanted to leave the site or cancel.
I tapped on cancel expecting the warning to disappear but instead Photopea closed.
When I re-opened Photopea, what I had been doing hadn't been saved. Although, luckily there wasn't much to save.
I tried it several more to times to check it wasn't a one off, but it did the same every time.
![Screenshot 2](https://github.com/photopea/photopea/assets/118609932/e21d28b8-65c3-4442-894f-c4d81fcd1db0)

**Comment by photopea** [comment]
Are you using Photopea at www.Photopea.com ? What web brwoser do you use?

**Comment by bluep55** [comment]
Yes. Installed via Chrome. Everything else works perfectly.

**Comment by photopea** [comment]
apparently, this is the way all apps installed by Chrome for Andoroid work at the moment. If you press Back, your app will be closed and neither we, neither you can do anything about it.

I wrote an email to Chrome developers and asked them about fixing it.

If you know that you hit the Back key too often (accidentally), rather use Photopea in the regular browser.

**Comment by bluep55** [comment]
> apparently, this is the way all apps installed by Chrome for Andoroid work at the moment. If you press Back, your app will be closed and neither we, neither you can do anything about it.
> 
> I wrote an email to Chrome developers and asked them about fixing it.
> 
> If you know that you hit the Back key too often (accidentally), rather use Photopea in the regular browser.

Ok, thank you. Tried it in the Chrome browser and it works as it should 👍

**Comment by photopea** [comment]
I will close it now, as we can not do anything about it.
