### ISSUE TITLE
Better zoom

### ISSUE THREAD

**Issue by tomasnosek** [photopea/photopea#62]
Try to implement better zoom tool "Z". I think users will appreciate thos use-cases after "Z" press:

1) draw a rectangular space by mouse on which i want to zoom - draw a viewport.
2) holding left-mouse and moving from left-right. To right for zoom in, to left to zoom out. Try it in PS, its fluent zoom and it's nice. If it's hard, then it's not neccessary.

**Comment by tomasnosek** [comment]
Oh, also button "original size" in toolbar would be nice to be able go easily back to 100% zoom.

**Comment by photopea** [comment]
I have added click-and-drag right to zoom in, left to zoom out.  I also added buttons for a specific zoom.

**Comment by photopea** [comment]
By the way, PP can now zoom only to values like 1,2,3,4... (so 1 image pixels spreads e.g to 3 real pixels).... and 1/2, 1/3, 1/4, 1/5... (so 1 real pixel contains e.g. 3 image pixels).   So you can not have a zoom 1.8 etc.
