### ISSUE TITLE
Better loading screen (suggestion)

### ISSUE THREAD

**Issue by PiranhaGreg** [photopea/photopea#620]
This is really a minor problem, because loading times of Photopea are blazingly fast. But...

**Current state**

_At first, info bar appears even I already visit Photopea page._
![1](https://user-images.githubusercontent.com/3635737/38297083-9f2276c6-37f3-11e8-99ac-2f13dc87f3ac.png)

_Info bar disappeared._
![2](https://user-images.githubusercontent.com/3635737/38297084-9f39e9a0-37f3-11e8-982a-510a14d3eeb5.png)

_For me, this is most distracting part..._
![3](https://user-images.githubusercontent.com/3635737/38297086-9f585ade-37f3-11e8-9b9f-77efaad46e7a.png)

_Flashing from white to dark..._
![4](https://user-images.githubusercontent.com/3635737/38297087-9f76dcca-37f3-11e8-9a24-048495bb0831.png)

_And finally, loading of Photopea is done._
![5](https://user-images.githubusercontent.com/3635737/38297088-9f90a56a-37f3-11e8-9dc4-902f27d884be.png)

**Comment by photopea** [comment]
Hi, I fixed most of these issues. Thanks! :)
