### ISSUE TITLE
unable to resize images

### ISSUE THREAD

**Issue by pinkjimrussiagirl** [photopea/photopea#6200]
Your Operating System: Windows 11
Your Web Browser: Microsoft Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. insert an image layer
3. make sure it's selected on the move tool
4. see the result that the scale handles are not showing
i also have a bug where the shape handles do not disappear even when selecting something else

https://github.com/photopea/photopea/assets/111091825/91f871cd-62aa-48cc-943f-5adffbc39032

**Comment by pinkjimrussiagirl** [comment]
also there is no option to deselect objects as well as i am more familiar with paint.net but i like the features photopea has

**Comment by bluep55** [comment]
For the scale handles to show, you have to place a tick in the 'Transform Controls' box when you're using the move tool.

**Comment by camoody1** [comment]
You can deselect objects by typing CTRL-D. I would greatly suggest removing the checkmark from the "Auto Select" box in the top toolbar. That can cause weirdness when you're dealing with so many layers. Also, as the previous post says, you should checkmark the "Transform Controls" box to see the handles.

Additionally, you've got a lot of tabs open in your browser. Depending on the power of the PC you're using and how much RAM you have, that _could_ be causing you some issues with Photopea.

**Comment by photopea** [comment]
I have to close it, because the person stopped responding :(

**Comment by thollins00** [comment]
> I have to close it, because the person stopped responding :(

Hello photopea, I am still having issues resizing my layers in the photopea editor, please fix this.

**Comment by camoody1** [comment]
> Hello photopea, I am still having issues resizing my layers in the photopea editor, please fix this.

Resizing layers in Photopea is working fine. I've been using it off and on all day. You need to be more specific about what problems you're having. Please include a short video from the start of opening Photopea and show us exactly what is not working for you.

**Comment by RebuildE** [comment]
also should add that the text cursor doesnt move properly either, and the delete shortcut is disabled somehow

**Comment by photopea** [comment]
Do you use the Brave browser? https://x.com/photopeacom/status/1827627762003173885

**Comment by RebuildE** [comment]
brave's the problem?

**Comment by photopea** [comment]
It works in every browser which can display a website the way it was made. You can try Edge, Chrome, Safari, Firefox, Opera etc.

You can make Brave display the websites the way they were made if you disable their "sheilds".

**Comment by WinUser-Generic** [comment]
> It works in every browser which can display a website the way it was made. You can try Edge, Chrome, Safari, Firefox, Opera etc.
> 
> You can make Brave display the websites the way they were made if you disable their "sheilds".

Thanbks but not, add other method to take money, but no with abusive ads.
