### ISSUE TITLE
Photopea not working 

### ISSUE THREAD

**Issue by WealthWithMe** [photopea/photopea#6201]
Your Operating System: google
Your Web Browser: google
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. create a new project
3. when doing that, it usually gives you a background but it is blank. 
![Screen Shot 2023-11-28 at 7 38 22 AM](https://github.com/photopea/photopea/assets/152290347/e72830f2-3fd4-4c64-8f6e-b4d2cad5405e)

**Comment by photopea** [comment]
I tried your three steps, but I can see the document with a background :( Could you try these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by WealthWithMe** [comment]
Ok. I tried it in incognito mode and it worked. But when I get out of incognito mode it goes back to the sam problem. I check for extensions on my Mac and I don't have any. What can I do

**Comment by photopea** [comment]
Are you using Google Chrome? Could you open "about://extensions" and send a screenshot of what you see there?

Also, did it happen more than once?

**Comment by WealthWithMe** [comment]
I don't have google chrome and it happens every time.

**Comment by WealthWithMe** [comment]
![Uploading Screen Shot 2023-11-28 at 8.02.09 AM.png…]()

**Comment by WealthWithMe** [comment]
![Screen Shot 2023-11-28 at 8 02 09 AM](https://github.com/photopea/photopea/assets/152290347/16dcb5fb-9690-4d5d-adcf-9f58a155f762)

**Comment by v1phor** [comment]
This just happened to me.

**Comment by MorgannLtp** [comment]
I'm in the same case

**Comment by photopea** [comment]
@MorgannLtp did you try the incognito mode?

**Comment by photopea** [comment]
Could you hard-reload Photopea with Shift+F5?

**Comment by graphicmaker** [comment]
that worked! Thank you. Though on my system it's ctrl+f5 ( in case anyone else needs to do this)

**Comment by MorgannLtp** [comment]
Thank you, that worked for me to !

**Comment by Darlin001** [comment]
> Então isso aconteceu apenas no Edge? Ou alguém de vocês estava usando algo diferente do Edge?

eu uso o chrome e estou com esse problema, os atalhos e algumas configurações não está funcionando, quando irão resolver o problema?

**Comment by photopea** [comment]
I will close it, as it seems to be fixed now.
