### ISSUE TITLE
Suspending computer causes Photopea to not show images

### ISSUE THREAD

**Issue by grass29** [photopea/photopea#6203]
Your Operating System: Ubuntu 22.04, X11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: haven't tried in the incognito mode

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open any image.
3. Suspend the computer.
4. Wake up, go to Photopea.
5. It shows gray background and no image.

Reloading the page fixes it.

**Comment by photopea** [comment]
I have Windows 10. If I open an image in Photopea and put my laptop into a sleep mode, I wake it up and I can still see my image there.

I do not have Ubuntu to try your steps :( It sounds like your web browser kills WebGL. You should still be able to save your work using File - Save as PSD. 

What if you try some web game? E.g. https://moonsters.ivank.net/ . If you put your computer to sleep in the middle of playing, can you continue playing after waking up your computer?

**Comment by photopea** [comment]
I have to close it, because the person stopped responding :(
