### ISSUE TITLE
(Feature Request) Material You/3? 

### ISSUE THREAD

**Issue by n128-98** [photopea/photopea#6204]
The Material 3 UI Design has recently released and I think its time Photopea gets a visual upgrade, would Material 3/You be possible to convert Photopea into?

**Comment by photopea** [comment]
What exactly would you like to be changed in the UI of www.Photopea.com ? Could you be more specific?

**Comment by photopea** [comment]
Could you maybe show us how you want Photopea to look like? Do you want round buttons instead of square ones, or different colors?

I will close it, but we can keep discussing it.

**Comment by n128-98** [comment]
![Screenshot 2024-01-02 10 04 04 AM](https://github.com/photopea/photopea/assets/74434783/f56ea7bd-a4a2-42cb-a378-1e9793adcb69) something similar to this, except rounder, because i don't understand css too well, material you is open source so you could take the existing values of the colors (primary40, secondary100, etc.) from the system theme, like on the latest Chrome OS updates, or Android 13+, and apply that color palette to the website, and if there is no available palette, you can make preexisting ones from the color system, you may want to look at the material 3 code (best link here is https://m3.material.io/develop) to see how you want to apply the rounding and such because personally I think that you'd make the better decision on how it would best fit the website,

**Comment by n128-98** [comment]
dont really understand css too much so im not much of help when it comes to the code and such

**Comment by photopea** [comment]
I think your screenshot looks exactly like Photopea looks now. In Photopea, press More - Theme - Blue, you can change theme colors this way.

**Comment by n128-98** [comment]
yes, but this is an example, people can have many different themes with material you, i want the code from the material you color to be used because it depends on the system colors rather than the website colors, if im correct, theres a web development page for material 3 and you

**Comment by n128-98** [comment]
![Screenshot 2024-01-02 12 29 38 PM](https://github.com/photopea/photopea/assets/74434783/47a8d3d3-fab9-4f8a-b1cb-3276b1678f18)
(blue looks like this btw, close, but not what im looking for

**Comment by n128-98** [comment]
the point isnt to comply to my theme, but to comply to the material 3 standards, the screenshot is just a demonstration on how you can use the colors _with_ the material you palette

**Comment by photopea** [comment]
I am a bit confused. I am not sure if what you propose will make Photopea look better. I am not familiar with your materials.

If you think the colors in Photopea interface should be different, show us your idea and we can let people in this thread vote for it.

**Comment by camoody1** [comment]
@photopea This is the Material UI they are talking about. It's a nice standard to use if you ever decide to redesign the Photopea UI.

https://mui.com/material-ui/
