### ISSUE TITLE
Eraser not showing up

### ISSUE THREAD

**Issue by jenne123** [photopea/photopea#6207]
I am trying to erase a small spot out of one text letter but the eraser tool is nowhere to be found, I click on the paintbrush in the toolbar and this is what it looks like for me.... where is the eraser?
![1](https://github.com/photopea/photopea/assets/152545210/1e0a5172-6ee2-4d17-945e-d0b33d24e4a1)

**Comment by photopea** [comment]
The eraser tool is in a toolbar, see here: https://www.photopea.com/learn/workspace

"Icons with a little arrow in the corner (e.g. Lasso tool) contain the whole group of related tools. Click and hold a tool button to see the menu with more tools in that group."

**Comment by bluep55** [comment]
Eraser Tool.
![Eraser Tool](https://github.com/photopea/photopea/assets/118609932/3bb0ba45-ac6f-40be-8e55-8c885474bd09)

**Comment by jenne123** [comment]
I dont have all those in my toolbar, no eraser in mine - see attached image
![tools](https://github.com/photopea/photopea/assets/152545210/7c3dcf56-6b55-42fa-b108-bd65109a581b)

**Comment by photopea** [comment]
Click and hold the Brush tool icon, the Eraser tool is inside that group.
