### ISSUE TITLE
Sketch file not loading

### ISSUE THREAD

**Issue by lizelleg** [photopea/photopea#621]
One sketch file in particular is taking an oddly long time to load—it's a smaller size than others I have been exporting, and there isn't a huge difference in design elements or file components. 

![screenshot 2018-04-04 14 43 55](https://user-images.githubusercontent.com/38086943/38336742-b6e8dbc8-3817-11e8-86fa-9f44774d1918.png)

**Comment by photopea** [comment]
Hi, could you please send us your Sketch file to support@photopea.com ?

**Comment by photopea** [comment]
It was fixed. Thanks for pointing out this bug! :)
