### ISSUE TITLE
Can't retrieve the canvas

### ISSUE THREAD

**Issue by AviceProjects** [photopea/photopea#6212]
Your Operating System: Windows 10
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open DevTools
3. Try to save the canvas as a blob
4. It ends up just being a black square

**Comment by AviceProjects** [comment]
> We never claimed we can provide such a functionality (blogs / canvases / whatever it means).
> 
> You can read this to learn how to save your work: https://www.photopea.com/learn/opening-saving
> 
> If you think you found a bug in Photopea, please, specify, which part of the manual does not work as described: https://www.photopea.com/learn/

Sorry, I'm trying to save the canvas as a png every couple of seconds. Do you know how to do this?

**Comment by photopea** [comment]
Why dont you save the actual image as a PNG? You would probably need to hack a web browser somehow.

**Comment by AviceProjects** [comment]
> Why dont you save the actual image as a PNG? You would probably need to hack a web browser somehow.

Photopea allows you to quick save as a PSD using Ctrl + S, why isn't there a quick save for pngs?

**Comment by photopea** [comment]
You can use Alt+Ctrl+Shift+S

**Comment by photopea** [comment]
Press More - Keyboard Shortcuts to learn about other shortcuts.

**Comment by AviceProjects** [comment]
> You can use Alt+Ctrl+Shift+S

But this doesn't automatically update the image. I suggest allowing users to save their projects as PNGs, so they can quickly update them like PSDs.

**Comment by photopea** [comment]
If you open a PNG file in Photopea, Ctrl+S should replace the old file.

**Comment by photopea** [comment]
If you open a PNG file in Photopea, Ctrl+S should replace the old PNG file with a new PNG file.

**Comment by AviceProjects** [comment]
> If you open a PNG file in Photopea, Ctrl+S should replace the old PNG file with a new PNG file.

Interesting. Well, that _is_ a workaround, thank you.

**Comment by photopea** [comment]
As Photopea can open 16 formats, we would need 16 keyboard shortcuts for it. But we can not use e.g. Ctrl+J for saving as JPG, because it is already used for duplicating a layer.

**Comment by AviceProjects** [comment]
I understand. It would take quite a long time to rework the saving system for Photopea. Thank you for your help, and the workaround!

**Comment by photopea** [comment]
you are welcome!
