### ISSUE TITLE
the "Brushstroke Plain" font doesn't work

### ISSUE THREAD

**Issue by Moina-01** [photopea/photopea#6213]
Your Operating System: Windows 10 Home x64
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Select New project or open from computer
3. Select the text and set the font to Brushstroke Plain
4. Write anything at any setting
![2](https://github.com/photopea/photopea/assets/152931342/5f22e086-7f4b-473f-ad3d-47cc9dfbbd4a)
![1](https://github.com/photopea/photopea/assets/152931342/c6db17cd-0149-4406-8d3e-c6a1f603953c)

**Comment by camoody1** [comment]
Can confirm. This font does not work for me, either.

**Comment by photopea** [comment]
It should be fixed now. Note, that your browser could be caching the old code for a few hours. So clear your cache, or just wait a bit.
