### ISSUE TITLE
Ads are making photopea slow

### ISSUE THREAD

**Issue by Soap64** [photopea/photopea#6214]
Your Operating System: MacBook Air
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: sure?

**This must be done to see the problem**
1. Go to www.photopea.com
2. starts off fine, but just use photopea for awhile.
3. now its unbearably slow.

**Comment by cats1984** [comment]
you need to clear your browser history, this can cause the computer to run slow, however there should be a work around for the "photopea running slow" issue. i would also run a internet speed test on your computer. use this link:https://www.speedtest.net/

**Comment by photopea** [comment]
Could you record a short video of how slow Photopea is? It could be slow because your document is too complex.

Have you tried to use Photopea with an ad blocker? Does the same thing work faster?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
