### ISSUE TITLE
for me on photopea install button not working 

### ISSUE THREAD

**Issue by pepa2023-98** [photopea/photopea#6215]
my Operating System: win10
my Web Browser: opera GX
The problem happens in the Incognito Mode, too

**Comment by photopea** [comment]
I think this feature works only in Chrome and Edge. You can ask the creators of Opera to make it work in Opera, too.

**Comment by Antek-dev** [comment]
hey I can't install photopea, click the button and it doesn't work anyone

**Comment by photopea** [comment]
Open "about://apps" in your browser, is Photopea already installed? Your browser will not give us a permission to install Photopea, if it is already installed.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
