### ISSUE TITLE
Can't read JPG

### ISSUE THREAD

**Issue by vladimirkovacevic** [photopea/photopea#6216]
Your Operating System: Any
Your Web Browser: Any
The problem happens in the Incognito Mode, too: Any

This is an improvement probably more than bug.

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open image 
3. JPG can't be selected
I saw an add for great online app. I wanted to edit quickly some JPG and I can't edit it. I understand you support certain formats, but it shouldn't be hard to convert JPG/PNG to one of those and keep editing it. Instead, I would just go to the other app.

**Comment by photopea** [comment]
I am afraid I do not understand, what the problem is. I should open any image, and then, "select a JPG in that image"? What does it mean?

**Comment by vladimirkovacevic** [comment]
Yes, that is true. But then I need to set resolution to match my image. Takes additional steps. In Photoshop or some other tool you can open any image and it will create graphic in its format and add content from JPG as one layer. Consider to improve that user experience.

**Comment by photopea** [comment]
Could you please be more preciese, what should I do in Photopea and Photoshop, to see that it works differently than Photoshop?

**Comment by vladimirkovacevic** [comment]
In Photoshop or some other tool you can open any image (e.g. JPG) and it will create graphic in its format (e.g. PSD) and add content from JPG as one layer. In Photopea when you open the program and go to Open image it is not possible to select JPG. Consider improving that user experience.

**Comment by camoody1** [comment]
> In Photoshop or some other tool you can open any image (e.g. JPG) and it will create graphic in its format (e.g. PSD) and add content from JPG as one layer. In Photopea when you open the program and go to Open image it is not possible to select JPG. Consider improving that user experience.

You can literally drag a JPG from anywhere on your computer, drop it onto the start screen of Photopea, and it will open into a PSD as a new layer. You can also drag and drop into an existing PSD and it will create a new layer for the JPG. Or, you can choose File -> Open and Place and then select a JPG. Have you tried doing any of these actions?

**Comment by photopea** [comment]
@vladimirkovacevic I just opened www.photopea.com, pressed File - Open, and selected a JPG file. It opened a new document with one layer with a content of that JPG file.

What happens when you do this in Photopea? Are you saying you can not open any JPG file in Photopea?

**Comment by vladimirkovacevic** [comment]
This is strange. Now I can open JPG in the way you described. Yesterday, in the selection window JPG image was blurred, I couldn't select it. It is working now, that is important. Thank you for your prompt responses. You are doing a great job! All the best!
