### ISSUE TITLE
Rulers set to "inches" should subdivide to 8ths

### ISSUE THREAD

**Issue by bmn001** [photopea/photopea#6217]
Your Operating System: Ubuntu 23.10
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Make a new image of any dimension
3. View Menu / Rulers to enable rulers.
4. Right-click the ruler and select 'inches'

You'll see that each inch along the ruler is divided into tenths.  Inches are typically broken into 8ths or 16ths, but never 10ths.

**Comment by photopea** [comment]
Fixed - Inches are divided into eight smaller pieces :)

**Comment by camoody1** [comment]
![image](https://github.com/photopea/photopea/assets/73725653/34020a6f-1ae7-4b14-9540-d16b3140bbc4)
