### ISSUE TITLE
Bug? Magic Replace Tool is Affected by the Current Brush Tool Opacity

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#6218]
Your Operating System: Windows 11
Your Web Browser: Microsoft Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open any sample image to test with.
3. Switch to the Brush Tool and set its Opacity to 10%.
4. Switch to the Magic Replace Tool, select any region within your sample image, and choose to replace the area with something (ex. a shoe, a beer bottle, etc)
5. Notice that the resulting replaced section has very low opacity.

Is this intentional? I can't think of a reason someone would want a low opacity effect for this tool. If it **IS** intentional, I would like to see an Opacity slider added to the top toolbar when the Magic Replace Tool is selected for use.

Thank you!

**Comment by photopea** [comment]
it should be fixed now :)

**Comment by camoody1** [comment]
Looks great! Thank you
