### ISSUE TITLE
Logging out after refresh the page

### ISSUE THREAD

**Issue by Exellion** [photopea/photopea#6220]
Your Operating System: Win11
Your Web Browser: Google Chrome 120.0.6099.71
The problem happens in the Incognito Mode, too: yes

I'm not sure this is actually issue on the photopea side, but maybe someone can help me. From today I can't stay logged in photopea. I log in, then refresh the page and see that I am not logged in again. I try with google and github auth. I cleaned up all cache of my browser, I tried incognito mode, I tried another browser, I tried to log out and log in to my google account. The one thing can help me - it's another PC)) My antivirus is Windows Defender. I checked his log and found nothing there. At the moment I have no idea what could be the reason. Maybe someone can help me here. Thanks!

**Comment by photopea** [comment]
How many browser extensions do you use? Could you temporarily turn off all your extensions, and try it again?

**Comment by Exellion** [comment]
It was AdGuard app. Sorry for disturbing.

**Comment by photopea** [comment]
you should report it to the creator of the adguard.
