### ISSUE TITLE
I cant manipulate layers.

### ISSUE THREAD

**Issue by JamieVenue** [photopea/photopea#6221]
When I try to manipulate my layers for example move 1 below or above another layer, it doesn't move.
As if the layer is locked, except it isn't and it's like this with every layer.

I tried reloading, I tried another browser, same thing.

**Comment by photopea** [comment]
Do you mean in the Layers panel? Are you doing it on a phone with your finger?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
