### ISSUE TITLE
I Cannot Draw

### ISSUE THREAD

**Issue by Flexicity** [photopea/photopea#6222]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by camoody1** [comment]
@Flexicity You need to be more specific, please. What exactly are you attempting to do and what exactly is happening?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
