### ISSUE TITLE
image constantly moving to the right

### ISSUE THREAD

**Issue by whokatethegreat** [photopea/photopea#6223]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. open up a file (any png, svg, etc)
3. use the mouse to hover over the image
4. the image will move to the right, it will not stay sedentary.

**Comment by photopea** [comment]
you must tell us your operating system, your web browser and if it happens in the Incognito Mode.

**Comment by camoody1** [comment]
@whokatethegreat Make sure you don't have a stuck space bar on your keyboard. When you hold the space bar and move your mouse in Photopea, or Photoshop, it moves the canvas around the screen.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
