### ISSUE TITLE
problem with crop and a wand

### ISSUE THREAD

**Issue by CornMag** [photopea/photopea#6225]
My wand hasn't been working for a while, and recently there have also been problems with cropping. The program takes a long time to process and then repeatedly overlays parts of the image and blurs the edges.

I have paid for another quarter, but I cannot use it because more and more errors appear and the programme crashes frequently ;(

**Comment by photopea** [comment]
Hi, could you write a report with a report template? I.e. providing additional details, like your operating system and steps to reproduce the issue?

**Comment by CornMag** [comment]
Windows 11
browser:   Chrome or  DuckDuckGo



opening NEF photo
I change the type settings: exposure, brightness, contrast, saturation..
I go to edit the psd file and remove the background with the eraser, then crop the image: the programme crashes

if I wait a while, the crop shows up with the edges of the photo blurred where the eraser has been edited
in addition, there appear on or around the image as if reflections of its fragments

such a photo is not usable

**Comment by photopea** [comment]
Does it happen if you use Photopea in the Incognito mode, i.e. with all your browser extensions disabled?

**Comment by CornMag** [comment]
no, the page in chrome is not incognito, but the page in DuckDuck Go is incognito

**Comment by photopea** [comment]
Could you maybe record a short video of what is happening? I have plenty of NEF files, but I can not make it happen :(

**Comment by CornMag** [comment]
Yes, I will record the screen for you, but just this time the cropping went well :)
Have you fixed something?

if this problem occurs again, I will try to record it and send it right away

**Comment by photopea** [comment]
I did not do anything to Photopea :(

**Comment by CornMag** [comment]
Hi, I attach a recording of the screen during cropping preceded by the use of an eraser around the edge of the image. Note the time it takes to crop and the effect around the edge after removing the pixels according to my selection.

[https://drive.google.com/file/d/1jdtz5AYYurtWYgRxFXdFuYpfayZEVzrS/view?usp=drive_link]

-------
I'm not sure if you will be able to open the link, but I hope so
--------------




PS. The wand hasn't worked at all for some time, so I have no way of using it even when there is a clear contrast between the background and the main subject of the photo.

**Comment by photopea** [comment]
Sorry, I can not open your link :( Could you open your link in the Incognito mode? If a link can be opened in the Incognito mode, it means anyone can open it.

I think you can also drag-and-drop a video right into Github, too.

**Comment by CornMag** [comment]
Unfortunately I cannot upload the .mkv format, so I have provided the file in the link.
I have changed the sharing conditions, please check if it works now?

https://drive.google.com/file/d/1kzQUDXcOrikZBegaZMxWKmGqySPhRado/view?usp=sharing

**Comment by photopea** [comment]
It works now, thanks!
- could you record the whole process, and start with opening www.Photopea.com ?
- could you record the whole editor, without cutting away the top part of the editor?

**Comment by CornMag** [comment]
ok, I will try to

**Comment by camoody1** [comment]
@CornMag When you're using you Magic Wand tool, make sure that your Tolerance value (in your top toolbar) isn't turned all the way up or all the way down. Play with the values a bit (a good number to start with is ~10) and make sure that you're on the correct layer to do your selection.

**Comment by CornMag** [comment]
Hi, today I recorded the workflow from start to framing and you can see that Phopea hangs (the video) and then the framing effect is as shown in the screengrab.

https://drive.google.com/file/d/1XUOZeYz4AraBIxPD0xWfGvAwLL8fh2XE/view?usp=sharing

![screen_ph_crop](https://github.com/photopea/photopea/assets/153543357/98e1f239-b2e2-4e5d-a038-17faeace3033)

**Comment by CornMag** [comment]
> @CornMag When you're using you Magic Wand tool, make sure that your Tolerance value (in your top toolbar) isn't turned all the way up or all the way down. Play with the values a bit (a good number to start with is ~10) and make sure that you're on the correct layer to do your selection.

Hi, thx - your advice has helped me a lot:  I had "anti-alias" and "continuous" turned on and then the magic wand did not work. I switched giving "sample all layers" and now it works with the settings you suggest.

**Comment by CornMag** [comment]
> @CornMag When you're using you Magic Wand tool, make sure that your Tolerance value (in your top toolbar) isn't turned all the way up or all the way down. Play with the values a bit (a good number to start with is ~10) and make sure that you're on the correct layer to do your selection.

**Comment by camoody1** [comment]
I just watched the video that you sent. Is the video correct in showing that you have a Photopea window INSIDE another Photopea window? The video shows you having two top application headers with menus. That is super weird, and something is definitely wrong if that's what you're actually seeing. Hopefully, that's just some weird anomaly from you recording the video.
![image](https://github.com/photopea/photopea/assets/73725653/82678647-ab6b-42ca-a662-8e425923dcae)

**Comment by camoody1** [comment]
> > @CornMag When you're using you Magic Wand tool, make sure that your Tolerance value (in your top toolbar) isn't turned all the way up or all the way down. Play with the values a bit (a good number to start with is ~10) and make sure that you're on the correct layer to do your selection.

> Hi, thx - your advice has helped me a lot: I had "anti-alias" and "continuous" turned on and then the magic wand did not work. I switched giving "sample all layers" and now it works with the settings you suggest.

Great! I'm glad I could help you out a bit. I hadn't thought about the "Continuous" checkbox. That could definitely cause some issues if you weren't expecting it.

**Comment by CornMag** [comment]
No, it's just a recording. The Photopea window is open normally and nothing is duplicated.

**Comment by camoody1** [comment]
> No, it's just a recording. The Photopea window is open normally and nothing is duplicated.

Well, that's good. 😁

**Comment by photopea** [comment]
The "freeze" in your case is caused by enabling "Content-aware" for the Crop tool. Do you know what it means? It will apply a content-aware fill to transparent areas after cropping. It might take 5 - 15 seconds for large areas.
https://github.com/photopea/photopea/assets/15955558/e2954bee-8e7e-4dfe-a00b-37b16900d111

**Comment by camoody1** [comment]
> The "freeze" in your last video is caused by enabling "Content-aware" for the Crop tool. Do you know what it means? It will apply a content-aware fill to transparent areas after cropping. It might take 5 - 15 seconds for large areas.
> 

Great catch

**Comment by CornMag** [comment]
Ah, I see :) Thank you. I didn't expect that this option could work so adversely in this case.
