### ISSUE TITLE
May I ask why photopea page cannot load some image link when I use it in iframe

### ISSUE THREAD

**Issue by nanonohm** [photopea/photopea#6226]
I use the photopea api, when my image link is 1, photopea can load the image, but when it is 2, photopea cannot load the image

 
1.'https://img0.baidu.com/it/u=2321155095,2409326152&fm=253&fmt=auto&app=138&f=JPEG?w=500&h=889g'
2.'https://image1.cdn.seaart.me/static/1361594f06e4a79a39918063a1918e44/20230315/1a0670f7c6275951d294fdaab6aaeacd.jpeg'

 `
  const jsonString = JSON.stringify({
    files: [
      'https://image1.cdn.seaart.me/static/1361594f06e4a79a39918063a1918e44/20230315/1a0670f7c6275951d294fdaab6aaeacd.jpeg',
    ],
  });

  const encodedJson = encodeURIComponent(jsonString);

`

**Comment by nanonohm** [comment]
Sorry my English is not good, can you understand the problem I described

**Comment by photopea** [comment]
I think it is because of CORS: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS . Your files are not at www.photopea.com, and one domain can not see data from other domains, unless these domains allow it.
