### ISSUE TITLE
Text Warp Arc Lower not arching properly

### ISSUE THREAD

**Issue by AstralChampion** [photopea/photopea#6228]
Your Operating System: Windows 10
Your Web Browser: MS Edge and Firefox
The problem happens in the Incognito Mode, too:  Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new blank project
3. Add a Text layer and write a word or two (increase font size to better see the problem)
5. Select the Warp tool and style **Arc Lower**: the arc effect should not curve the upper portion of the text, but only curve the lower portion of the text.
7. To see the expected effect, select the style Arc Upper which works as expected: the upper portion of the text is curved while the lower portion remains flat.

Difference between the current Arcs Upper & Lower styles:

![WarpArcLowerBug](https://github.com/photopea/photopea/assets/153630619/d3396b88-7b3f-4554-b04b-b31a885d481a)

**Comment by photopea** [comment]
I saw you drew two blue lines with your hand. How do you decide where to draw a blue line? If your ward was only dots ".......", you would draw a blue line on top of a dot?

**Comment by AstralChampion** [comment]
Not sure I get your point. The blue lines are for the horizontal reference where the arc should not be applied.

**Comment by AstralChampion** [comment]
Explain the style icon, then: 
![image](https://github.com/photopea/photopea/assets/153630619/54aebad8-0e64-4c37-9799-291303064476)
flat top, curved bottom... this is not what's happening to the text when using Arc Lower.

**Comment by photopea** [comment]
Where do you think is the top of your text?

**Comment by AstralChampion** [comment]
From the example I gave in my submission, both ends of the lower arc text are touching the "top" indeed. But what about the middle part of the text? It's all curved down. A working "arc lower" doesn't warp any portion of the top of the text.

**Comment by photopea** [comment]
Maybe I do not explain myself properly.

If your word is "aaaAaaa", and you do Arc Lower, are you saying, that the top of both "a" and "A" should be at the same height?

**Comment by AstralChampion** [comment]
I see your point. Lowercase and uppercase letters height ratio should remain unchanged. Only their bottom part should warp. Here's an example using letters of the same height. Their top is warped as well: 
![image](https://github.com/photopea/photopea/assets/153630619/02797237-76f4-409c-ae5f-c87ecd58e3ed)

I wish I still had my Adobe license to pull tangible examples for you. That is not a major gap by the way, your tool is an awesome treasure! Now the only thing I can give you as the expected result is reversing the Arc Upper to show the expected result, something like this: 
![image](https://github.com/photopea/photopea/assets/153630619/245842d6-68ed-415a-9b8b-21a469a0156b)

It seems I could fiddle a bit with the manual warp to achieve the desired effect:
![image](https://github.com/photopea/photopea/assets/153630619/cb04707f-0a49-49f1-8218-81c5905bb511)

**Comment by photopea** [comment]
I am quite sure that our effect works and looks the same as in Adobe Photoshop.

**Comment by AstralChampion** [comment]
It might! I still have a very little doubt but so be it, not really missing the Adobe suite with your great tool, thanks for the lightning quick follow-up.

**Comment by camoody1** [comment]
For reference, this is how Upper Arc and Lower Arc work in Photoshop 2024:

![image](https://github.com/photopea/photopea/assets/73725653/72c1b842-468d-44df-8239-c853a776f803)

**Comment by AstralChampion** [comment]
@camoody1 interesting! Somehow Photopea nails the upper arc better, while Photoshop curves the lower arc as I recalled by keeping the top portion relatively in position.

**Comment by camoody1** [comment]
Those first images were with the "arcs" set to 50%. If I increase the arc value to 100%, it looks like this:
![image](https://github.com/photopea/photopea/assets/73725653/b2ca4628-8b85-40f8-a8c4-77a943f14ce5)

**Comment by camoody1** [comment]
This is how the same text in Photopea appears at 50% and 100% arc:
![image](https://github.com/photopea/photopea/assets/73725653/00a2a9a1-6f5f-4709-8d7a-42402e74d0f0)

**Comment by photopea** [comment]
I think that Photoshop sets the "bottom edge" (which remains straight) to the bottm edge of letters like "p,q,j,g", while we set the bottom edge to a baseline. Do you think we should cahge it in Photopea.

**Comment by camoody1** [comment]
It looks like the Arc Upper in Photopea is leaving the bottom of the text straight and then just stretching the middle letter to make them taller to fit the arc curve. But then the Arc Lower is doing a totally different thing. You can really see the differences in how both applications handle the formatting at the 100% value. Photoshop doesn't seem to maintain ANY straight lines to my eye. They just have a much lower arc when closer to the line than when farther away.

To be honest, I really prefer the way Photopea handles the Arc Upper format, but I also think that you should probably make it work the same as Photoshop does for compatibility purposes.

**Comment by photopea** [comment]
@camoody1 You should try applying the Arc Lower / Arc Upper Warp to a regular rectangular image. The effect in Photoshop and Photopea is totally identical.

The only remaining thing is, how you convert a text layer into a rectangle (a bit different in Photoshop and Photopea now, especially for the bottom edge of a rectangle).
