### ISSUE TITLE
Change plugin hosting

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#6229]
Ivan, hi, say please, if I do, for examples on GitHub, new hosting for plugins files, how rewrite this settings in plugin? Load new JSON file?

**Comment by photopea** [comment]
Each unique JSON file is considered to be a different plugin :(

If you can not make the old URLs work, you should probably publish a new plugin and delete the old one. Hope your current users will find it.

Did you get in touch with repl.it and ask them what is going on, and if they can fix it?

**Comment by Pt-home** [comment]
That is, even you do not have the technical ability to manually replace old links with new ones, do I understand correctly?

**Comment by Pt-home** [comment]
Replit, as I understand it, will no longer provide free hosting for Web projects, so we have what we have(

**Comment by photopea** [comment]
Just upload a new plugin. I am sure users who need them will find 5 seconds to install a new version.

**Comment by Pt-home** [comment]
Ok, I'll do that
