### ISSUE TITLE
Crop by selection

### ISSUE THREAD

**Issue by scottjenson** [photopea/photopea#623]
I'm loving Photopea as as my web replacement for Mac Preview (simple stuff) and Photoshop(heavier stuff) This is really a convenience request for those quick and dirty image clean ups I do all of the time. I'd like to drop in an image, cut out the background, crop a subset and export as a transparent PNG.

Photopea can do all of this but what is slowing me down is the cropping. I *have* to specify a ratio or a fixed size. This is a surprisingly tedious thing to do (I don't know the size I want, it's just a selection) What I'd like to do is something that is fairly common in most editors (it exists in Preview, Photoshop, and Acorn at least) and that is a Crop to selection command.

The classic UI is to have a top level menu item "Crop" which just crops to selection. However, I'd settle for a 'crop to selection' checkbox in the Canvas Size dialog. This option would only be available for rectangular selections.

Thanks

**Comment by photopea** [comment]
Hello Scott! Thanks!

When you switch to the Crop tool (e.g. by pressing C), there is a button in the top menu: Selection. Just press it and confirm the selection. Is that what you wanted?

**Comment by photopea** [comment]
I am going to consider it solved.

**Comment by antonbe** [comment]
Stick it in the menu!
