### ISSUE TITLE
Can't upload an EXR file

### ISSUE THREAD

**Issue by ayoslug** [photopea/photopea#6232]
Can Photopea support .exr files? Because when I tried to open one from maya it only opened the file as one layer and not multiple. And when I tried to workaround this by sending my exr file to my friend and him sending it back to me as a Photoshop file (with all of the layers and everything) and I tried to open it in Photopea it just opened to a background layer of static....

**Comment by photopea** [comment]
Could you share your EXR file here with us, e.g. in a ZIP? Also, is there any program which opens your EXR file the way you want, so that we know how you want it to be opened?

**Comment by ayoslug** [comment]
[am_final(6).zip](https://github.com/photopea/photopea/files/13666082/am_final.6.zip)

here's the zip of the EXR, the photoshop file my friend opened it with opened with all the different layers

**Comment by photopea** [comment]
It should work now :)
