### ISSUE TITLE
Can't close the color picker tab or ok

### ISSUE THREAD

**Issue by MesaBlack** [photopea/photopea#6233]
So I'm working on a psd that takes several meg's, and I just had the color picker tab refuse to close when i click on the x or the "OK" button.

**Comment by photopea** [comment]
Could you tell me what should I do on my computer to see it happen?

**Comment by camoody1** [comment]
Ooooo... this is that same issue we saw many months ago. You said you'd give someone $500 if they could consistently replicate the issue. I never could figure it out.

**Comment by photopea** [comment]
I have to close it because of lack of details :(  Yes, I still offer $500 to a person who can describe, how to make the color picker unable to be closed.
