### ISSUE TITLE
image disapearing when text tool selected

### ISSUE THREAD

**Issue by themanofpolybridge2** [photopea/photopea#6234]
my operating system is windows 11
my web browser is opera gx

this must be done to see the problem (if the problem doesent persist, please tell me what is going on)
1. go to www.photopea.com
2. open an image
3. select the text tool

**Comment by themanofpolybridge2** [comment]
![image](https://github.com/photopea/photopea/assets/121596792/6f235256-9ea4-433d-8015-50c1e496197d)

**Comment by camoody1** [comment]
@themanofpolybridge2 Try disabling all of your browser extensions and then reopen Photopea and try again. Or try this in an In Cognito window. There's no guarantee that the extension are causing this particular issue, but it's important to start troubleshooting from a clean slate.

**Comment by photopea** [comment]
That is right, try to do it in the Incognito mode (with no browser extensions) and tell us if it works.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
