### ISSUE TITLE
photopea just deleted my project

### ISSUE THREAD

**Issue by cats1984** [photopea/photopea#6235]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....draw a simple landscape
3. ....force close several times
4. ....project will be gone.

**Comment by camoody1** [comment]
@cats1984 Are you saving this project at any point? Or are you just creating something and then closing it while ignoring the warning message over and over again?

**Comment by cats1984** [comment]
it does not give me a warning message, i saw something like are you sure you want to close this tab but that went away before i could even click it and the it force closed. i am using google chrome and my os is chrome os. i am at school and incognito mode is blocked.

**Comment by camoody1** [comment]
I'm just trying to be clear, not trying to be rude...

So, you create a project, and then you actually click to close it? Or it just closes on its own while you're working? If you click to close it, then you actually DO see a message, but without you clicking anything, that message just goes away and your window closes? Is that what you're saying?

Is there any possible way for you to record a video of this happening and send it here for the developer to see?

**Comment by cats1984** [comment]
i cannot record again im at school and they have this stupid thing called linewize and it blocks almost everything. i understand that you are not trying to be rude, sorry if i seem kinda grumpy i did not sleep well last night. so yes i do click to close it it shows a warning for a sec but then it goes away before i can even click no and it force closes.

**Comment by camoody1** [comment]
@cats1984 Thank you for your clarification. I'm sorry that you lost your project. And I'm sorry that you didn't sleep well. Hopefully, the developer has a Chrome OS device he can test your issues on. I know Photopea doesn't act that way on my Android phone or PC.

One other question, when you're working in Photopea, I assume you're using a free account? If so, do you actually see advertisements on the far right side of your Photopea window? Or does your school have Ad Blocker installed on your device? I ask because browser extensions can really cause havoc on web applications like Photopea.

**Comment by cats1984** [comment]
they do not have a ad blocker installed on any of the devices, i do see ads on the side of my screen when im in photopea but i just ignore them. i have tried to bypass linewize with a vpn but that does not work because when i go to a website with free vpn it blocks it. and the dumb "report to linewize button" does nothing. so this project is a assignment and all i have to do is use www.edulaunch.com and photopea to draw a simple landscape but tommorow is the end of the six weeks and all the grades are going in and its marked as missing at this time. so if i don't get it done i get another 0 in the grade book.

**Comment by cats1984** [comment]
you have been very helpful and i really am greatful. i will submit another ticket if i have anymore problems, also i thought photopea automaticly saves.

**Comment by cats1984** [comment]
what kind of pc do you have?

**Comment by camoody1** [comment]
> what kind of pc do you have?

I'm sorry, I've been busy all day. I just have a normal Windows 11 PC. But I also have a Samsung Galaxy S22 Ultra that seems to work fine for me. I have a weird feeling that your school's network has something to do with your issues. I was hoping the Photopea Dev would see this ticket today and chime in. I don't know if other Chrome OS users have reported this same problem.

**Comment by photopea** [comment]
What is the third step - "force close several times" - how do I do this step?

**Comment by photopea** [comment]
Also, you did not tell us if it happens in the Incognito mode, too.

**Comment by cats1984** [comment]
ok so to force close you have to close out your tab about 5 times or so and it will be gone. 
i am at school and incognito mode is blocked.

**Comment by photopea** [comment]
I am still confused. What exactly should I do to see your problem myself?

**Comment by cats1984** [comment]
look if i am wasting your time i am very sorry.
really what happend is i did not know how to save and i thought that photopea auto saves when i X out.
but if you could add a auto save feature i think a lot more people will use photopea.
but its up to you, i can't tell you what to do, im not in control of you.
