### ISSUE TITLE
Pencil breaks after using size fade till it fades out

### ISSUE THREAD

**Issue by Penut63** [photopea/photopea#6237]
Your Operating System:Windows 10
Your Web Browser: FireFox (checked and also happens in chrome)
The problem happens in the Incognito Mode, too: yep

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create or open an image
3.  Select pencil tool
4. Go into brush
5. Set size jitter to fade
6. use pencil till it fades out 
7. pencil now no longer draws new lines. I cant even find a way to revive it.

**Comment by camoody1** [comment]
Confirmed. This is super weird. I had to completely close out of Photopea in order to make the Pencil start working again.

The Fade functionality works fine for the Brush tool, but not the Pencil tool.

**Comment by photopea** [comment]
Sorry, it is fixed now.
