### ISSUE TITLE
Aspect ratio for rec selection tool

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#624]
Rec select by common aspect ratio is also often used, just like the one in crop tool

**Comment by photopea** [comment]
What would be the use case?

**Comment by hgs54371** [comment]
For rec select with a certain ratio/size of course, and do it without affecting canvas size, photoshop has it, for trying around ideas or this:

![make-your-own-passport-photos](https://user-images.githubusercontent.com/36803688/38385168-c77d6788-3943-11e8-8089-e55febdf8f46.jpeg)

**Comment by photopea** [comment]
If you want to cut out single pictures out of your photo, I think that is what Guides were made for.

How would fixed size select help you in this case, when you don't know the size, not even the aspect ratio?

**Comment by hgs54371** [comment]
The size and aspect ratio is defined by law, photos submitted needs to meet the size and aspect
Why this seems to be such a foreign concept for you

![screen1](https://user-images.githubusercontent.com/36803688/38386385-18531dda-3947-11e8-80bb-605c7cacd646.jpg)

**Comment by hgs54371** [comment]
The canvas remains 4x6 inch typical print photo size, material needs to crop to different ratios, and put on this fixed size canvas for later print out, the method you mentioned needs each project/canvas for each ratio crop, but not keep all within a single project

In photoshop you can specify the selection by size or ratio
https://helpx.adobe.com/photoshop/using/selecting-marquee-tools.html

**Comment by photopea** [comment]
I don't think this is an important feature. It seems like you are just mentioning all differences between Photoshop and Photopea, to make Photopea to be completely the same as Photoshop.

**Comment by hgs54371** [comment]
I actually often use this in photoshop, but found that it is not exist yet in photopea, that's the reason for all these suggestions, not that I'm nick picking, these are all the features I use in photoshop.
