### ISSUE TITLE
Fix the map control shortcuts keys

### ISSUE THREAD

**Issue by kevinW0W** [photopea/photopea#6240]
Your Operating System:
Your Web Browser: Google chrome that open into incognito windows.
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Go to layer
3. Click new
4. Layer (that show the shortcuts key shift+ctrl+n)

**Comment by photopea** [comment]
Are you talking about Shift+Ctrl+N not working in Chrome? I think it is a bug in Chrome, the shortcut works fine in Firefox. Could you ask Google to fix it?

**Comment by photopea** [comment]
I have to close it because I did not fully understand the problem :(
