### ISSUE TITLE
Feature Request: Additional Refine Edge Options to Match Photoshop

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#6241]
As seen on the following video beginning around 2:45:
https://www.youtube.com/watch?v=0uf1qQh9mTk&ab_channel=GaryBradley

It would be most helpful if some of the sliders under "Global Refinement" could be added to Photopea. In particular: Smooth, Feather, Contrast and Shift Edge. These options would really help to blend the edge refinement much better and allow for effects such as those shown in the attached video.

**Comment by photopea** [comment]
I don't know how to make it :( I think this tool would have to be created from scratch, but I don't know how.

**Comment by camoody1** [comment]
It seems like the sliders almost work as adjustment layers on the Raster Mask.
