### ISSUE TITLE
Photopea keeps randomly crashing(?)

### ISSUE THREAD

**Issue by UniversalSpyCrab** [photopea/photopea#6242]
![Screenshot 2023-12-16 012654](https://github.com/photopea/photopea/assets/153979047/15233f74-7d22-45f0-95c2-be6716ba9681)

Randomly keeps crashing this way after about 10 minutes of working on a project.

**Comment by photopea** [comment]
Hi, could you please write the exact steps, how to make Photopea crash? I need to see it happen with my own eyes, to be able to analyze it and fix it. It never happened to me.

**Comment by UniversalSpyCrab** [comment]
- open photopea
- Work on project for a bit
- Suddenly crashes and makes it so I can no longer see the canvas. I have to close photopea and boot it up again for it to work.
- Same problem happens again.


Note: when photopea crashes, it turns my Google docs white for a second and then back to normal.

**Comment by photopea** [comment]
I tried it, but I could not make Photopea crash :(

Could you record a short video (1 - 2 minutes) of you doing these four steps, until a point when it crashes?

**Comment by gardenertx** [comment]
I have been having the same problem on both Firefox and Google Chrome.. It crashes the program and I have to navigate to photopea again, losing the work I have been working on.

**Comment by UniversalSpyCrab** [comment]
https://youtu.be/RkLDuN3cXAM?si=iXQWrWBePhvZMOjR

Here is a link to the video I made showing the error crash.

still have no idea what I’m doing to make it crash,,

**Comment by photopea** [comment]
@UniversalSpyCrab how long did you use it before it crashed? Is it more than 30 minutes?

After opening your file, could you press Window - More - Memory, how many MB of RAM does your document requre? Also, how many MB of RAM do you have in your computer?

This error means, that a website asks for more RAM memory, but the browser is not giving it more memory, so it kills a website instead.

**Comment by UniversalSpyCrab** [comment]
About 10-15 minutes of work, no matter the document I have open.

I’m not sure how to get there, but my settings says I have “Installed RAM: 4.00 GB (3.82 GB usable)”

It’s good to hear the cause for the crash though. Is this ram not enough?

**Comment by photopea** [comment]
I think 4 GB is not enough for advanced work. My laptop has 24 GB. You can buy an 8 GB module for $18, and it will tripple your amount of RAM.

So I think that is the case - since the computer runs out of RAM, and a website keeps asking for more, a browser decides to kill the website.

BTW. if Photopea crashes, and you close it and reopen it, can you see your old work? There is a backup mechanism in Photopea: https://www.photopea.com/tuts/photopea-opens-up-old-files/

**Comment by UniversalSpyCrab** [comment]
Oh awesome! Is it like a usb where I can just plug it in and it increases my ram?

if not then maybe is should save up for a new computer lol

When Photopea crashes, I cannot access my old work, no. I usually save it as a psd and open it back up when i boot up the website again.

Anyways, thank you! I’ll try the 8 GB module option.

**Comment by photopea** [comment]
it should be plugged into your computer inside, you might need to remove several screws. Also, check if you have DDR3 or DDR4, to buy a right one (DDR3 will not fit into a DDR4 slot and vice versa). You can ask the seller about it.
