### ISSUE TITLE
Photopea "Color Range" strange bug

### ISSUE THREAD

**Issue by jason3120** [photopea/photopea#6243]
Your Operating System: Windows 10
Your Web Browser: Chrome or Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open an image
3. Use Rectangle Select to Select text which on the image
4. click Select->Color Range...
5. Sample Colors->ok
6. There is a bug, apart from selecting the text, it also has a rectangle select the text
7. This should not happen, because if use Fill->Content Aware, it will fail to clear the text on the image

This is the bug appear recently.

Originally should be something like that:
![20231216-1924-53-214_00000__00003](https://github.com/photopea/photopea/assets/29269167/771c3056-5484-4d99-8bc3-3a42f93ff8eb)

But now become this:
![20231216-1931-11-042_00000__00004](https://github.com/photopea/photopea/assets/29269167/d4d62f2e-a99c-4821-9293-89b4889d600c)

It is not supposed to have a rectangle select after using the color range.

**Comment by photopea** [comment]
I just tried it in Photopea and Photoshop, and Photopea seems to work identically to Photoshop.

Are you sure you know how to use Color Range? You can read our manual at https://www.photopea.com/learn/advanced-selecting, or you can read any book about Adobe Photoshop.

**Comment by jason3120** [comment]
> I just tried it in Photopea and Photoshop, and Photopea seems to work identically to Photoshop.
> 
> Are you sure you know how to use Color Range? You can read our manual at https://www.photopea.com/learn/advanced-selecting, or you can read any book about Adobe Photoshop.

Oh, yes, I found that I forgot to click the text color before. I miss one step. Sorry about that. It works now. Thank you.
![20231216-2046-23-482_00000_00001](https://github.com/photopea/photopea/assets/29269167/e8938ad6-2ece-4627-b492-50db679e810d)
