### ISSUE TITLE
photopea

### ISSUE THREAD

**Issue by shahzaib2233213** [photopea/photopea#6244]
Hello, me and my peers are having trouble using Photopea. get back to me asap.
thank you, from Shahzaib. be quick...!!!!!!!!!!!!!!!!!!!!!!

**Comment by camoody1** [comment]
Be quick!!!!! 😂

**Comment by photopea** [comment]
Hi, how can I help you?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
