### ISSUE TITLE
Rendering bug with color overlay when rotating

### ISSUE THREAD

**Issue by thomasbrq** [photopea/photopea#6245]
Your Operating System: _**MacOS Ventura 13.6.3**_
Your Web Browser: _**Arc Browser**_
The problem happens in the Incognito Mode, too: _**Yes**_

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open [bug.psd](https://drive.google.com/file/d/1nR_ZJME1UgizRriMd1HnJ2g6pTKr1f6G/view?usp=sharing)
3. Clone the `Calque 1` layer and apply a color overlay on it
4. Click on the cloned layer
5. Go to Edit > Transform > Rotate 90

https://github.com/photopea/photopea/assets/71637888/5617adc8-0bbf-4d94-af03-9b04acac1f42

The bug is still present even after export:

![bug](https://github.com/photopea/photopea/assets/71637888/c059959f-887f-48cf-bd82-eeb64d2fc102)

**Comment by photopea** [comment]
What an interesting bug! It happened only when transforming a perfect pixel-based rectangle (not a vector shape), and only by a multiple of 90 degrees. 

It is fixed now! :)
