### ISSUE TITLE
Any vector with any effects (e.g gradient, many more) won't be exported as SVG

### ISSUE THREAD

**Issue by mubinets** [photopea/photopea#6246]
Your Operating System: Windows
Your Web Browser: Kiwi Browser
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Literally do anything to add effect to the vector like gradient
3. It can be exported but all effects won't be exported. Almost like it doesn't support effects.

Yes I tried on many other broswers, doesn't work. I can export svg but not including effects.

**Comment by photopea** [comment]
What is this? How can I do it in Photopea?

"Literally do anything to add effect to the vector like gradient"

**Comment by mubinets** [comment]
I mean like any effect, it doesn't matter. A gradient will do.
Lemme explain in simple way and with screenshots.

1. Click on layer.
![Screenshot_20231219_142650](https://github.com/photopea/photopea/assets/154252711/3d63f9e4-3df8-494a-81a6-d8783925417a) 
2. Click on the layer style (also known as effects).
- It doesn't matter, just select any style, a simple gradient will do fine. For me I choose gradient.
![Screenshot_20231219_142758](https://github.com/photopea/photopea/assets/154252711/39edf629-6a47-4faf-b7a3-e1214e855cf6)
3. Now you got a vector with nice gradient, click on file.
![Screenshot_20231219_142852](https://github.com/photopea/photopea/assets/154252711/4c663530-84af-45db-b0e7-8ea0f7153ed8)
4. Literally try to export the svg vector.
![Screenshot_20231219_142946](https://github.com/photopea/photopea/assets/154252711/f872ed9a-f937-4db0-b704-576e19c39b9d) 
5. This is where the real issue happens. You don't see any effect in the vector, they're not exported properly. Only simple vector with simple colors and some parts (as long as they don't have styles) will be exported.
Note: This vector is just zoomed in, not really relevant. But you can see that there aren't any effect or style.
![Screenshot_20231219_141614](https://github.com/photopea/photopea/assets/154252711/b170b003-9808-4b10-a3be-a3b4896a59af)

**Comment by photopea** [comment]
Is it possible to have two fills in SVG? I mean, having one rectangle in SVG, which has a black color, and a gradient fill on top of it?

In Photopea, you can e.g. set 50% opacity to this Gradient, so both the solid color and a gradient fill are visible. Is it possible in SVG?

**Comment by mubinets** [comment]
I am not really sure since I don't know much about SVG (in general). But I am sure that could be possible.

If you mean in photopea, mostly not because one still has gradient effect regardless.

**Comment by photopea** [comment]
I think it is impossible to have more than one fill in on a shape in an SVG file. Just like there is no Bevel and Emboss in SVG, or a lot of blend modes of Photopea do not exist in SVG.

Use Layer - Flatten Image before exporting an SVG, to get exactly what you see in Photopea.
