### ISSUE TITLE
The application does not allow you to select an subject

### ISSUE THREAD

**Issue by VovkAnna** [photopea/photopea#6248]
Your Operating System:macOS Ventura 13.0.1
Your Web Browser:Safari 16.1
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Сlick add file.
3. Сlick Selection in main menu
4. Choose Subject
5. see the message 
<img width="1440" alt="Снимок экрана 2023-12-19 в 15 44 44" src="https://github.com/photopea/photopea/assets/69368079/e66518cb-39d6-4351-a073-9568da58d9e4">

**Comment by photopea** [comment]
Is it possible that you have Photopea opened in your web browser for more than two weeks? If yes, could you close Photopea and open it again?
