### ISSUE TITLE
The projects start automatically when you start Photopea

### ISSUE THREAD

**Issue by Qrodry** [photopea/photopea#6249]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. I go to Photopea and the projects launch themselves

**Comment by photopea** [comment]
Hi, try this: https://www.photopea.com/tuts/photopea-opens-up-old-files/

**Comment by Qrodry** [comment]
> Cześć, spróbuj tego: https://www.photopea.com/tuts/photopea-opens-up-old-files/

thank you, you should have deleted your cookies

**Comment by photopea** [comment]
I never delete my cookies, and I never see Photopea open old files :(

**Comment by funing36** [comment]
Photopea sometimes open's up old files for me. Never bothered me though.

**Comment by photopea** [comment]
It happens if Photopea was not closed properly, so the backup file was not deleted, as described here: https://www.photopea.com/tuts/photopea-opens-up-old-files/
