### ISSUE TITLE
Photopea App Crashes when Guassian Blur is used all the way

### ISSUE THREAD

**Issue by rupkatAI** [photopea/photopea#6252]
Your Operating System: Windows 10 Home 10.0.19045
Your Web Browser: Microsft Edge
The problem happens in the Incognito Mode, too: Not Tested

**This must be done to see the problem**
1. Open Photopea App
2. Create 1920x1080 empty page
3. Copy JPG or PNG to your project
4. Try to guassian blur all the way 

After these steps photopea app always crash for me

**Comment by photopea** [comment]
Hi, I did that, and dragged the Blur slider up to 400 px, but it does not crash :( 

Could you try it in the Incognito mode? Also, what is your PeaMark score (More - PeaMark)?

**Comment by rupkatAI** [comment]
CPU - 710
GPU - 2581

I will try to test it out once again, but after i while, when i have couple of layers and effects on them, the crash occurs.

**Comment by photopea** [comment]
But your steps describe applying the effect only to one layer. So what exactly do you do to make Photopea crash?

**Comment by rupkatAI** [comment]
https://streamable.com/3s44xg

Look. When its above 248 px it always crash.

**Comment by photopea** [comment]
I still cannot make it happen :( Could you disable WebGL (More - Use WebGL) and try it again?

**Comment by rupkatAI** [comment]
Disabling WebGL do the trick. No crash

**Comment by photopea** [comment]
What ANGLE settings exactly did you use, and why? Nobody ever reported such a problem, gaussian blur almost always uses WebGL.

**Comment by rupkatAI** [comment]
D3D9, because any other cause flickering on youtube videos using hardware acceleration.

**Comment by photopea** [comment]
I will close it now. I recommend setting your browser to a default configuration when you have problems with crashing.
