### ISSUE TITLE
  Slicing tool adjustment

### ISSUE THREAD

**Issue by VirRonin** [photopea/photopea#6253]
Can the slicing tool only capture images within the slicing box, and clicking on this box with the mouse can directly adjust the position

**Comment by photopea** [comment]
Hi, I do not understand. Is it a question or a statement? What do you mean by capturing images within the slicing box?

**Comment by VirRonin** [comment]
At present, slicing tools and images based on reference line slicing will also save unnecessary images outside the green selection box and gray. And I only want the pictures within the green selection box.

Additionally, after selecting an area in the slicing tool. Can you click directly with the mouse to move this selection box




 
From: Photopea
Date: 2023-12-21 19:13
To: photopea/photopea
CC: VirRonin; Author
Subject: Re: [photopea/photopea] Slicing tool adjustment (Issue #6253)
Hi, I do not understand. Is it a question or a statement? What do you mean by capturing images within the slicing box?

**Comment by photopea** [comment]
Slices are for creating websites, and you need all images to get the same result as what you see in Photopea. So I think not many people need exporting only of some slices.

The Slice Select tool allows you to click and drag any slice to a new location. See https://www.photopea.com/learn/slices

**Comment by VirRonin** [comment]
I slice comics, and the automatic slicing places are images that I don't need (extra parts).
Can we add an automatic slicing and deletion function (gray area)




 
From: Photopea
Date: 2023-12-23 20:51
To: photopea/photopea
CC: VirRonin; Author
Subject: Re: [photopea/photopea] Slicing tool adjustment (Issue #6253)
Slices are for creating websites, and you need all images to get the same result as what you see in Photopea. So I think not many people need exporting only of some slices.
The Slice Select tool allows you to click and drag any slice to a new location. See https://www.photopea.com/learn/slices

**Comment by MichalSZZ** [comment]
In Photoshop, user has an option to choose which if the slices should be exported.

There is an option "all user slices" and that means, all slices that was draw by user manually. All others slices are created automaticaly and those are not neccessery to export when user choose "images only" mode. Not everybody needs to create HTML site using slice tool.
Even in HTML view images aren't neccessery to put them into TD elements.

**Comment by photopea** [comment]
Where is this option in Photoshop?

**Comment by VirRonin** [comment]
Yes, all I need is this feature to only export manually drawn slices




 
From: MichalSZZ
Date: 2023-12-23 23:43
To: photopea/photopea
CC: VirRonin; Author
Subject: Re: [photopea/photopea] Slicing tool adjustment (Issue #6253)
In Photoshop, user has an option to choose which if the slices should be exported.
There is an option "all user slices" and that means, all slices that was draw by user manually. All others slices are created automaticaly and those are not neccessery to export when user choose "images only" mode. Not everybody needs to create HTML site using slice tool.
Even in HTML view images aren't neccessery to put them into TD elements.

**Comment by MichalSZZ** [comment]
I'm on mobile.phone now and write from my head, but I think there is in 'export for the web' old option (ctrl+alt+shift+s). And there look for more options at the bottom. You should  click somewhere to open a new window or change something in the 'select' option.

If you don't find it I will paste the screenshot after christmas.

**Comment by VirRonin** [comment]
And there look for more options at the bottom




 
From: Photopea
Date: 2023-12-23 23:51
To: photopea/photopea
CC: VirRonin; Author
Subject: Re: [photopea/photopea] Slicing tool adjustment (Issue #6253)
Where is this option in Photoshop?

**Comment by MichalSZZ** [comment]
I have used it many times. Look for the colors in Photoshop. User slices are blue, and those that are added automaticaly are grey (but I don't know if it is in the editor itself or in the export for the web window).
When you create slice in Photoshop you van click right mouse button and there are many additional functions such: renaming, giving visual atributes (only image, image as a background), you can even give there www link or (maybe i don't remember) option onClick or something like that. 
But that isn't a mainstream thing of our subject now.

**Comment by VirRonin** [comment]
ok  Merry Christmas!




 
From: MichalSZZ
Date: 2023-12-23 23:58
To: photopea/photopea
CC: VirRonin; Author
Subject: Re: [photopea/photopea] Slicing tool adjustment (Issue #6253)
I'm on mobile.phone now and write from my head, but I think there is in 'export for the web' old option (ctrl+alt+shift+s). And there look for more options at the bottom. You should click somewhere to open a new window or change something in the 'select' option.
If you don't find it I will paste the screenshot after christmas.

**Comment by photopea** [comment]
Please, let me know where it is in Photoshop, I can not see it :(

**Comment by VirRonin** [comment]
From: Photopea
Date: 2023-12-24 00:15
To: photopea/photopea
CC: VirRonin; Author
Subject: Re: [photopea/photopea] Slicing tool adjustment (Issue #6253)
Please, let me know where it is in Photoshop, I can not see it :(
―

**Comment by MichalSZZ** [comment]
The first place to set the slice as non-image (but that isn't the option that I was talking about):
![obraz](https://github.com/photopea/photopea/assets/38118273/9a7612e5-d8b4-4607-b184-267333d9d305)

And here:
"Save for the web (legacy)"
![obraz](https://github.com/photopea/photopea/assets/38118273/acbe1c01-b978-4d47-ab9a-49abcf345442)

Here you can set file format and compression to each image in a slice (orange is the selected one):
![obraz](https://github.com/photopea/photopea/assets/38118273/e6146fe9-48dc-4a88-b711-f63892a0490b)

AND ....
After clicking "Save"
![obraz](https://github.com/photopea/photopea/assets/38118273/3b50aa99-47f6-4d43-9491-496c6a5eb66d)

In "format" there are "Images only" - that option I use all the time; "HTML and Images"; "HTML only"

In "settings" there are many options - you should test each. For example if you click "Other" you can set naming of the files or...
![obraz](https://github.com/photopea/photopea/assets/38118273/67040808-6649-46f0-8b30-6646e3104d8a)

But the most important in this topic is the last option:
"Slices":
![obraz](https://github.com/photopea/photopea/assets/38118273/4d89b758-8ef0-4fa6-9102-5329f5e69760)

**Comment by MichalSZZ** [comment]
Selected are these Orange in one of my screens.

But the author of the Issue want to have "all User Slices" option

**Comment by MichalSZZ** [comment]
OK i turn off my computer and I wish you all Marry Christmas

**Comment by photopea** [comment]
@MichalSZZ thanks for explaining it to me :) I have implemented it! When exporting a document with slices, you can choose "No Slices", "All Slices" or "User Slices".

**Comment by VirRonin** [comment]
Thank you very much to the team for providing the features I need. Currently, the website interface is not full screen, and there are some blank spaces. What is the reason for this



 
From: Photopea
Date: 2024-01-01 17:58
To: photopea/photopea
CC: VirRonin; Author
Subject: Re: [photopea/photopea] Slicing tool adjustment (Issue #6253)
@MichalSZZ thanks for explaining it to me :) I have implemented it! When exporting a document with slices, you can choose "No Slices", "All Slices" or "User Slices".
―

**Comment by photopea** [comment]
What blank spaces? could you share a screenshot of what you see?

Also, do not reply by sending emails to random email addresses. Reply at www.github.com in your web browser.

**Comment by camoody1** [comment]
@VirRonin The blank space on the far right is where advertisements are supposed to be to support the free use of Photopea. If your area is blank, it's because you have an ad blocker disabling those ads.
