### ISSUE TITLE
Text has wrong stroke rendering when it is added to the text with background parameter

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#6254]
Your Operating System: Windows 10
Your Web Browser: Chrome 120.0.6099.111
The problem happens in the Incognito Mode, too: YES

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new document
3. Create a text layer by clicking with a type tool
4. Write something using a 24px font size and a (for example) yellow font color
5. Go to the top menu and use three dots to add the background color to the text (for example blue)
6. You will see the gaps in the background between the letters and it is the main problem
7. Now add the stroke to the text layer or group the text layer and add the stroke to the folder

As you can see - there are gaps between letters. There is a border around the background in the version with a stroke added to the folder. There is bad rendering of a stroke added to the text with these gaps - little points of stroke under the line where the gaps are.

[buttons-hack.zip](https://github.com/photopea/photopea/files/13740532/buttons-hack.zip)
![buttons-hack](https://github.com/photopea/photopea/assets/38118273/b5470732-97d8-4226-a86e-f6f1298e5c8c)

I'm trying to make a hack that makes flexible, editable buttons with background and rounded corners (something that isn't possible in Photoshop but is possible in Illustrator or any UI program like Figma etc. Screen is attached and a ZIP file with PSD

**Comment by MichalSZZ** [comment]
I see that can be a problem with font rendering.
When there is a "none" set - it works well (in the stroke added to the text directly). "Sharp", "crisp", and "smooth" are bad. "Strong" looks better, but there are still dots at the bottom of the stroke.

I think it is a problem with the font rendering, but the user will see that only when he adds the background to the text, and he will see it even more when he adds a stroke to the text with a background.

**Comment by photopea** [comment]
I think it is not related to text rendering at all.

The problem happens, when a layer has semi-transparent pixel, and is inside a folder with a layer style. These pixels remain partially transparent. See here: www.photopea.com/#iMaF2-3Mb - you can see red pixels between the blue ellipse and the blue stroke.

Sadly, I dont know what to do about it :( Try to create what you want in a different way.

**Comment by MichalSZZ** [comment]
OK. I understand. But it can cause many other situations where the design wouldn't look as the author wants or the opened PSD files will look different than in Photoshop. 
Photoshop hasn't any problem with it as you can see below:
![obraz](https://github.com/photopea/photopea/assets/38118273/93f6891f-6887-4b14-82fe-6bf502f8ff9e)

**Comment by photopea** [comment]
I think I would need someone from Adobe to tell me how they did it. I think
it was reported here before, in the past.
