### ISSUE TITLE
please help if I'm in photopea I want to do it I don't have such an option pls

### ISSUE THREAD

**Issue by jentkier** [photopea/photopea#6256]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by camoody1** [comment]
You want to do what?

**Comment by jentkier** [comment]
I want to mess things up and I don't have that option

**Comment by photopea** [comment]
We never had an option to mess things up.

**Comment by SpiritAxolotl** [comment]
who gave the toddler a keyboard

**Comment by photopea** [comment]
I have to close it, because I do not understand what this person needs :(
