### ISSUE TITLE
Ads are aways not showed

### ISSUE THREAD

**Issue by esdraslov** [photopea/photopea#6257]
Your Operating System: Windows 10
Your Web Browser: Microsoft Edge
The problem happens in the Incognito Mode, too: no

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new project
3. Disable ad blocker
4. Reload the page
5. Create a new project (again)

![image](https://github.com/photopea/photopea/assets/103470150/2d924a29-e1f5-426d-9758-b1132624ed62)
![image](https://github.com/photopea/photopea/assets/103470150/53405bcd-de0e-40c8-9d00-e564692a8bda)

**Comment by photopea** [comment]
I am confused about the step 3. My computer does not have any ad blocker. Do I need to install an ad blocker? Which one?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
