### ISSUE TITLE
Idea for quick export

### ISSUE THREAD

**Issue by AviceProjects** [photopea/photopea#6258]
Photopea doesn't use the shortcut shift + y, so you could use it for a quick export shortcut.

When users export their project, use showSaveFilePicker() so that they can quick export it later.

This would allow users to keep their file as a PSD, while still allowing them to export their project with only the press of a shortcut.

**Comment by photopea** [comment]
Does Shift+Y exist in other programs? I am afraid nobody will ever find out about this shortcut.

**Comment by AviceProjects** [comment]
Well, you could put it in the "file" tab if you want. And it doesn't need to be an intuitive shortcut, it's just for the people who want to use this handy feature.

**Comment by photopea** [comment]
I think nobody will ever find this feature, if we make it. Nobody ever asked for it in 10 years of Photopea existence.
