### ISSUE TITLE
Slow/Freezing and crashes very frequently

### ISSUE THREAD

**Issue by xflipperkast** [photopea/photopea#6259]
Your Operating System: Win 11 and iphone 12
Your Web Browser: Any (ios safari,Chrome,edge,opera on pc)
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Do anything
3. Randomly starts freezing and spikes cpu
4. works for a bit and crashes/freezes again

specs:
rtx 3090
32Gb 3600mhz ram
ryzen 7 5800x3d cpu

**Comment by photopea** [comment]
Hi, I have used Photopea many times, and it never happened.

Could you record a video of what it looks like as a proof?

**Comment by funing36** [comment]
Hello, this is Pebble, I found out, at least with Chrome OS, that the ad's on the side does take up a lot of resourses, so for my sake, I load up Photopea, than close it and go offline, than reopen it. (Photopea saves in the background where it can be loaded in the background) This'll stop the ads from coming, and when the page is loaded, you can turn the internet back on.

https://github.com/photopea/photopea/assets/146106615/aa415efc-cdd6-4760-80f4-298c2f81cf2a

Note: I do allow Photopea to farm ad's whenever I'm not using it for my gratitued and this method I do.

**Comment by funing36** [comment]
> Hi, I have used Photopea many times, and it never happened.
> 
> Could you record a video of what it looks like as a proof?

I have a response...

**Comment by photopea** [comment]
I dont know if your video has a low FPS, or this is the actual way Photopea runs on your device.

What is your PeaMark? Press More - PeaMark, and do the CPU / GPU test.

**Comment by funing36** [comment]
Sorry, the chromebook isnt good at recording, but I had trouble oppening any project (Note: I clicked on the "New Proect" and it took forever to open and itll adventually crash {couldn't show that because of the 10MB limit file upload}.

My PeaMark is:
CPU: 215
GPU: 26

**Comment by photopea** [comment]
That performance is really low, especially the GPU :( Could you disable WebGL (More - Use WebGL)? Does it work faster?

**Comment by funing36** [comment]
Ok, yes, there's a notable difference, that helps!

I got a video about the ad's issue:

https://drive.google.com/file/d/1fMqxa8xysm-uHS-yuYL7DE8hbyFBojAj/view?usp=sharing

https://drive.google.com/file/d/1yvcAqqU1xsysSdRqsGm6ti37xjjLA9qE/view?usp=sharing

**Comment by photopea** [comment]
could you open "about://gpu"? Is the WebGL hardware-accelerated?

**Comment by photopea** [comment]
I have to close it. The origianl person did not respond. And the device with CPU: 215  GPU: 26 is really bad for running Photopea. I think a used phone from 2016 which is sold for $60 could run Photopea better.
