### ISSUE TITLE
Magic tool -> Remove puts a random person in place of the removed object

### ISSUE THREAD

**Issue by Morphic1111** [photopea/photopea#6261]
HI, the Magic tool when lassoed, and click to Remove puts a random person or thing in place of the removed object. See attached 2 screenshots wherein a penguin, although cute, replaced a person instead of removing the person.
This is repeatedly happening with different photos.  

<img width="654" alt="Screenshot 2023-12-23 at 9 11 39 PM" src="https://github.com/photopea/photopea/assets/154713037/ad3ee626-dabf-485b-b6fe-f092afa5cefe">

<img width="664" alt="Screenshot 2023-12-23 at 9 11 49 PM" src="https://github.com/photopea/photopea/assets/154713037/1d279446-3a39-4c66-94cf-8f93f563c2aa">

**Comment by Morphic1111** [comment]
Maybe that's not a penguin, a giant bird, nonetheless.

**Comment by photopea** [comment]
We are aware of this, but there is no easy way to fix it :( 

Try to specify a new content, e.g. "empty sandy beach" and use "Replace" instead of "Remove".

The "Remove" button is "fake", it actually performs "Replace" with a phrase "empty background" as a parameter. It works in about 70% of cases.
