### ISSUE TITLE
Feature Request - "Copy To Clipboard" export option for supported filetypes.

### ISSUE THREAD

**Issue by Z2r-YT** [photopea/photopea#6262]
Feature Request -- In the export menu for supported filetypes, a "Copy to Clipboard" option could be present, this would be great as it would mean that edits of screenshots and other quick taskss can be quickly copied to the clipboard, and temporarily saved, for quick use, rather than saved to downloads, dragged, dropped, sent, recycled, and then finally deleted.

heres just a quick mockup of what the feature would look like
![firefox_ciISkAD06a](https://github.com/photopea/photopea/assets/69476320/f6b04a21-e170-4df2-af89-3e120129d9bf)

this could be done via the [clipboard JS API](https://stackoverflow.com/a/57546936/10885581)

**Comment by camoody1** [comment]
You can just CTRL-A to select all and then SHIFT-CTRL-C to copy all visible layers to your clipboard. Under the Edit menu, it's called "Copy Merged".

That's an existing option if it's helpful to you.

MERRY CHRISTMAS!
![image](https://github.com/photopea/photopea/assets/73725653/47c938b4-3222-44a4-9c6a-9d78a68bcc26)

**Comment by Z2r-YT** [comment]
> You can just CTRL-A to select all and then SHIFT-CTRL-C to copy all visible layers to your clipboard. Under the Edit menu, it's called "Copy Merged".
> 
> That's an existing option if it's helpful to you.
> 
> MERRY CHRISTMAS! ![image](https://private-user-images.githubusercontent.com/73725653/292682896-47c938b4-3222-44a4-9c6a-9d78a68bcc26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0Mzg5NzksIm5iZiI6MTcwMzQzODY3OSwicGF0aCI6Ii83MzcyNTY1My8yOTI2ODI4OTYtNDdjOTM4YjQtMzIyMi00NGE0LTljNmEtOWQ3OGE2OGJjYzI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE3MjQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZmU4NTY0YmRiOTkxZjcxNDJhMjgxZTY0ODYxMTY4Y2MyMDE2MGJiNzFhYzE0OTdlM2VhYWVlMmY2NGJlNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._s2frvDQYzvxgUOmYQIbNf_MNWoWKCcqhEU3S37QCrY)

Thanks for the tip, although, using Firefox v120.0.1 + Windows 11 x64, this feature doesnt seem to work, unsure how or why, but, it just doesnt work. I can paste it back into photopea, but, anywhere else i cant, and my windows clipboard history confirms that nothing was copied, so i assume that the image was simply just copied to browser storage and kept there, rather than the clipboard itself.

**Comment by camoody1** [comment]
> Thanks for the tip, although, using Firefox v120.0.1 + Windows 11 x64, this feature doesnt seem to work, unsure how or why, but, it just doesnt work. I can paste it back into photopea, but, anywhere else i cant, and my windows clipboard history confirms that nothing was copied, so i assume that the image was simply just copied to browser storage and kept there, rather than the clipboard itself.

I don't know what to tell you. That keyboard shortcut works fine in both Chrome and Edge. 🤷🏼‍♂️

**Comment by photopea** [comment]
Sadly, Firefox does not support the latest web standards. We can not change it. https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write#browser_compatibility . But it also says that you can allow it by switching some flags.

From my experience, 99.9% of Firefox users consider it to be extremely risky and totally wrong to allow websites to put images into your clipboard, or read images from your clipboard. But you can try to report it to Firefox and try to convince them to change their mind.

Many say that Firefox is not funded properly, but I think it is not the case. They just live in 1990s and are afraid of making websites more capable.
