### ISSUE TITLE
the over lay system isnt workig for me pls fix this bugg

### ISSUE THREAD

**Issue by rizzler855** [photopea/photopea#6263]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by camoody1** [comment]
What do you mean? We'll need some more details. Perhaps a screenshot or short video would help.

**Comment by photopea** [comment]
What is the overlay system? If you can not describe the problem with words, could you at least share a screenshot?

**Comment by photopea** [comment]
I have to close it because of lack of details.
