### ISSUE TITLE
No keymapping/keyboard shortcut customization (New Feature)

### ISSUE THREAD

**Issue by funing36** [photopea/photopea#6264]
Your Operating System: Chrome OS
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: N/A

**This must be done to see the problem**
1. Go to www.photopea.com
2. Try to change the keymapping/keyboard shortcut
3. Thers the problem.
---
I recently got a drawing tablet (The XP-PEN ARTEST 12) and work's with Photopea to an extent, but I can't change tools with any of the buttons on the pen or tablet. I'd like it to be able to have custom keymapping and possibly have different keymapping presets that can be customized and saved by the user.

**Comment by photopea** [comment]
What buttons do you have on your pen or your tablet? Did you set any settings in Photoshop?

**Comment by funing36** [comment]
Sorry, I ment with Photopea App, i fixed it.

**Comment by funing36** [comment]
I'm not sure what the buttons do, I dont have access to Photoshop at the moment.

**Comment by photopea** [comment]
Could you share a photo of your tablet and mark the buttons somehow? What these buttons are supposed to do?

**Comment by funing36** [comment]
![IMG_20231226_114435379](https://github.com/photopea/photopea/assets/146106615/b2627416-5625-4e9c-9b9b-0e1b4d457a31)

Pad= Touchbar
T1-3, B1-3 is the Express keys
P1-2 is the pen Buttons

**Comment by funing36** [comment]
Ok, it might be that Chrome OS probably doesn't have the proper drivers, so I'll hold this till I can test it with a different PC.
