### ISSUE TITLE
Photopea rotate view move bounds issue (bug)

### ISSUE THREAD

**Issue by funing36** [photopea/photopea#6265]
Your Operating System: Chrome OS
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: N/A

**This must be done to see the problem**
1.  Go to www.photopea.com
2.  Open a file that is portate.
3.  Use the rotate tool to rotate horizontally.
4.  Try to use the hand tool to see the right side of the picture
5.  If you zoom in enough, you'll hit an invisible barrier
---
I used the rotate tool so I could use my pen and found that I couldn't move past a certain point while zoomed in.

https://github.com/photopea/photopea/assets/146106615/c71dcbc0-0428-4db4-933e-b8768a21e59e

**Comment by funing36** [comment]
Ran into the problem again and cant draw the feet. : (

**Comment by photopea** [comment]
Hi, it is fixed now :)
