### ISSUE TITLE
Unable to open files in Photopea

### ISSUE THREAD

**Issue by conniearess** [photopea/photopea#6266]
I am trying to work on photos in Photopea with extensions of .jpg and .heic and I am unable. I am trying to upload the photo into Photopea from my google folder which Photopea has permision. I also attempted from Photopea to a folder on my desktop. Neither works and I receive an error. Attached is a screenshot of the error. 
I have a premium account. PS, this is not a new issue, but I don't see one that's 'open' at this time.
Thanks.
<img width="872" alt="Screenshot 2023-12-26 at 18 44 09" src="https://github.com/photopea/photopea/assets/154917266/a3fba7dd-0a1f-468c-93f9-10076b24687a">

**Comment by funing36** [comment]
Hello, I might be able to help. It could be a weard formt, so I'd try to put it through a converter to help fix that, like https://cloudconvert.com/.

Sence it doesnt sapport heic files, rename "Windblown at Sunrise.heic" to "Windblown at Sunrise.png" than run it.

**Comment by conniearess** [comment]
Thanks so much, but the problem still persisted by changing it manually. HOWEVER... I used cloudconvert.com and it absolutely worked. Thank you so much! It must read HEIC weirdly and if you try to change it without conversion tool, it doesn't really recognize it other than HEIC.... Happy Holidays!

**Comment by conniearess** [comment]
Resolved

**Comment by photopea** [comment]
That is correct, Photopea can not open HEIC files. Please, set your camera to take photos as JPG files, if you want to use your photos outside the Apple ecosystem (Photopea is not made by Apple).

**Comment by photopea** [comment]
Photopea can open HEIC and JPEG XL files now using File - Open :)
