### ISSUE TITLE
Snapping for vectors not always accurate

### ISSUE THREAD

**Issue by SpiritAxolotl** [photopea/photopea#6267]
Your Operating System: MacOS, Windows
Your Web Browser: Chromium, Firefox
The problem happens in the Incognito Mode, too: Yes.

**This must be done to see the problem**
1. Go to www.photopea.com
2. Make a new rectangle with the rectangle tool
3. Duplicate the rectangle and move it
4. Select both rectangles, and resize while holding shift
5. Click the checkmark button in the top right
6. The border will now be semi-transparent (or seemingly not transparent at all)

This can also be seen when resizing just one rectangle on its own.

This issue makes it very annoying to work with vectors in photopea. Snapping to pixels instead of decimals would fix the issue (probably).

**Comment by photopea** [comment]
This is simply how pixels work. If your image is 1x1 pixel, but you draw a rectangle of 0.5 x 0.5 pixels in the middle, you will not see the edge of this rectangle. This is how all raster programs work. Maybe use Vectorpea for what you need.
