### ISSUE TITLE
Changes are saved to wrong file when PWA is installed locally

### ISSUE THREAD

**Issue by ezekiel747** [photopea/photopea#6268]
Your Operating System: macOS Sonoma
Your Web Browser: Google Chrome v120 (latest stable version at the moment of writing this)
The problem happens in the Incognito Mode, too: No. This is strange.

**This must be done to see the problem**

1. [important] Get Photopea installed locally as a Progressive Web App. (see image below) <img width="331" alt="image" src="https://github.com/photopea/photopea/assets/38600480/000d9730-2251-449b-9287-0c8a2e15e307">
2. Navigate to /Users/your-user/Applications/Chrome Apps
3. Ensure Photopea is NOT open
4. Select a few images in a folder and drag the selected images to the Photopea app's icon.
5. Select each image (they are open in separate tabs), make some changes to it (does not matter, crop for example) and save it.
6. Now take a look at the resulted images. ONLY the last in the list of opened images is altered.

Notice that this does NOT happen while on the site (normal or incognito window). Here, instead, i get this popup whenever i save each image:
<img width="443" alt="image" src="https://github.com/photopea/photopea/assets/38600480/31f6b3a4-ed3c-466b-9c45-5e792e611f5e">

If you need a video recording of the actual bug, i can provide. 
Thank you.

[later edit: updated steps]

**Comment by photopea** [comment]
Did you try to disable all your browser extensions? Does it help?

**Comment by camoody1** [comment]
> Your Operating System: macOS Sonoma Your Web Browser: Google Chrome v120 (latest stable version at the moment of writing this) The problem happens in the Incognito Mode, too: No. This is strange.
> 
> **This must be done to see the problem**
> 
> 1. [important] Get Photopea installed locally as a Progressive Web App. (see image below)
> 
> <img alt="image" width="331" src="https://private-user-images.githubusercontent.com/38600480/292967071-000d9730-2251-449b-9287-0c8a2e15e307.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MTQyNTEsIm5iZiI6MTcwMzcxMzk1MSwicGF0aCI6Ii8zODYwMDQ4MC8yOTI5NjcwNzEtMDAwZDk3MzAtMjI1MS00NDliLTkyODctMGM4YTJlMTVlMzA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDIxNTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkZmJlMjI3NDk0NTBhNDkzYTM4NDZlYjgyOWNmZDg3MGIyNWEyMWJiMWY4ZDllYTQxMGE2ZTFiYmJiYjM4YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jnRJGrSSc6luF1KO9gIDlU_Hh2gs5oYGdQFNXNWfpgc">
> 2. Open Photopea from local Apps.
> 3. Open several images at once (one way is to select multiple images, then drag and drop to Photopea open app)
> 4. Select each image (they are open in tabs), make some changes to it (does not matter, crop for example) and save it.
> 5. Now take a look at the resulted images. ONLY the last in the list of opened images is altered.
> 
> Notice that this does NOT happen while on the site (normal or incognito window). Here, instead, i get this popup whenever i save each image: <img alt="image" width="443" src="https://private-user-images.githubusercontent.com/38600480/292966996-31f6b3a4-ed3c-466b-9c45-5e792e611f5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MTQyNTEsIm5iZiI6MTcwMzcxMzk1MSwicGF0aCI6Ii8zODYwMDQ4MC8yOTI5NjY5OTYtMzFmNmIzYTQtZWQzYy00NjZiLTljNDUtNWU3OTJlNjExZjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI3VDIxNTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNDgxNWVhNzI3NGU5OTUxYjk0Y2ZhMDQyNjI4NTY4NDA5NzAyZmI0ZTM3ZTk2YjBhMjY4MzhjNzBiNzQ0OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yWnU9CH69eUKU50vqhVJgAFRNTG0uXndAw3nY7QMrn0">
> 
> If you need a video recording of the actual bug, i can provide. Thank you.

I followed your steps 1 through 4... I dragged five images into my PWA Photopea, made changes to each one, and then went back and saved each updated image individually starting with the first one. I then closed Photopea. When I look at the images in their folder, each of them DO have the updates I made.

Did I do something wrong from what you're desribing? Because it seems to work for me.

**Comment by ezekiel747** [comment]
I didn't try to disable the extensions, but I uninstalled Photopea as PWA, then reinstalled it.
Now the behavior is different, when saving each image i get the popup each and every time:

<img width="445" alt="image" src="https://github.com/photopea/photopea/assets/38600480/8c6db3a5-81cb-42ca-993f-c0eab679abdb">

And the images are saved correctly, each image contains the changes.

Thing is, i don't remember how i got rid of the popup in the past - is there some kind of setting for this?

**Comment by ezekiel747** [comment]
I've been able to reproduce the bug, again.
I didn't realise this was making the difference, but:
instead of opening Photopea PWA, then dragging the selected images in it,

have the shortcut put on dock, then, with Photopea NOT running, drag the selected images to the Photopea icon in dock.

(I'm using macOS as previously mentioned. To put Photopea in dock, navigate to /Users/your-user/Applications/Chrome Apps, then drag Photopea to your dock. I have NOT tried on Windows.)

Hope this helps. Thanks!

**Comment by ezekiel747** [comment]
I've updated the steps to simplify the process of reproducing this.
Please let me know if any other info is needed.

**Comment by photopea** [comment]
It should be fixed now! The workflow with drag-and-dropping multiple files to the Photopea icon and then, saving them back, should work correctly now :)
