### ISSUE TITLE
Export to PDF - Gradient radiant fill does not correctly export into PDF

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6269]
Your Operating System: ChromeOS
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com/#iJ3eBx-Ow
2. Export the file to PDF without rasterizing
3. You'll see that the rainbow borders are not exactly the same as the ones in the project
![image](https://github.com/photopea/photopea/assets/11801254/c6b60042-c631-41b9-9809-73ff9f741bf5)

I need to be fixed soon :(  I have to send to a client the final PDF

**Comment by TheRadicalDreamer** [comment]
It is easier to repro:

Create a circule and fill it with a radial gradient, then export to PDF

![image](https://github.com/photopea/photopea/assets/11801254/7c1b9824-6d57-4110-b1c1-c78bc60876ff)

**Comment by photopea** [comment]
It should work as you expect now.

Regarding the Angle gradient, there is no such thing in PDF or SVG :( either rasterize that layer, or use a different kind of gradient.

**Comment by TheRadicalDreamer** [comment]
![image](https://github.com/photopea/photopea/assets/11801254/8a861dff-a915-4fb2-927e-1f774b842dd3)

Mine is diamond, so that one also PDF cannot support it??

**Comment by photopea** [comment]
Nope, PDF has only linear and radial gradients. A radial gradient can be "squeezed" into an elliptical gradient (possible in Vectorpea). Do you think we should rasterize these layers automatically during the PDF export?

**Comment by TheRadicalDreamer** [comment]
Yes.
I believe if pdf supports a feature, it should have properly.

But if pdf does not support it, them yes, rasterize it

**Comment by photopea** [comment]
okay, these layers should be rasterized automatically during the PDF export now.
