### ISSUE TITLE
Drag selected characters in text layer only deleted after 2nd delete hit

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#627]
The characters(more than 2) selected with text cursor drag only deleted after 2nd delete key hit, 

This issue occurs after the "delete drag selected text also delete text layer in firefox mac" issue was solved, so this is also specific to firefox mac

**Comment by photopea** [comment]
I don't think we can fix it. Lets wait few years until browsers "unify" (or people start using better browsers / OSs). If you know JS, please create some small example and report this to Firefox or Apple. It is really hard for me to report these things, when I don't have a Mac.
