### ISSUE TITLE
"Magic Replace" don't works

### ISSUE THREAD

**Issue by emandeb** [photopea/photopea#6271]
Your Operating System: Linux Ubuntu 20
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: **No.**

Since Dec 28, Magic reeplace stop to work but I **still can use it on Incognito Mode**.
It show the first dialog but don't load the add.
I don't use adBlock on Photopea site.
I had try disable all extensions and erase all cookies but didn't work again.

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
I think something is still blocking ads on your device. Are you sure ads dont play when you disable all extensions? Did you reload Photopea after disabling all extensions? Could you share a video, where you show "about://extensions" of your browser, and then open Photopea and try the Magic Replace?

**Comment by mindplay-dk** [comment]
Yeah, this doesn't work for me either - it plays an ad, then it shows "processing" for a little while, and then nothing happens - it doesn't do anything to the selection at all.

I've tried different prompts, I've tried adding negative prompts, I've tried switching between the 3 available models - no result. If this feature does in fact work, perhaps you could post a link to an article or video showing how to use it? We might be doing something wrong or expecting something it can't do.

In my case, I was just trying to remove a simple white text from a photo - it should be the kind of thing this feature would work for, right?

I'm using the spot healing brush for now instead - it doesn't always give the best result, so I am actually interested in trying this feature, and would probably pay to use it, if it works well. 🙂

**Comment by photopea** [comment]
@mindplay-dk Could you try it in the Incognito mode, where  your browser extensions can not interfere with Photopea?

**Comment by photopea** [comment]
As for the bug, I just tried it, and it works fine for me (I do not have any browser extensions). The Magic Replace was used by our users 10,000 times in the last 24 hours.

**Comment by camoody1** [comment]
The Magic Replace tool is definitely working.

Merry Christmas...
![image](https://github.com/photopea/photopea/assets/73725653/c167c7ed-8363-4bfb-bbf7-1567bb0dc993)

... Look out! Behind you!
![image](https://github.com/photopea/photopea/assets/73725653/24769ee4-5343-401d-931c-0fd111e8b8ba)

**Comment by mindplay-dk** [comment]
Tried disabling all browser extensions, incognito mode, etc. - I don't think it's browser related.

I've never used the Photoshop equivalent of this feature - is it possible some of us are just using this feature wrong, or expecting it to do something it can't actually do?

Perhaps this feature needs a tutorial or help page.

**Comment by photopea** [comment]
You can use this video as a tutorial: https://twitter.com/photopeacom/status/1661425407944425494

In what country are you located? Do you see any errors in the web console when the error happens? Did you try to apply it to more than one image?

**Comment by photopea** [comment]
I have to close it because of lack of details.
