### ISSUE TITLE
Photopea keeps saying I'm using AD blocker but I don't

### ISSUE THREAD

**Issue by cpyb** [photopea/photopea#6272]
Your Operating System: Windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
Photopea is greate I have been using for about 1 month.  
But everytime I save to PSD it will say You are using a AD blocker.
I do use chrome-extension uBlock but I have add photopea.com WHOLE SITE to safelist since the first time.  

Thank you.

![block photopea](https://github.com/photopea/photopea/assets/58124389/18f2f7d1-84ed-4e30-b152-e4c3afc60da2)

**Comment by camoody1** [comment]
You've got something else blocking the site, then. I just installed uBlock Origin, marked Photopea safe, and the ads are showing without an issue. You may need to check if Chrome is blocking ads with its own built-in ad blocker.

**Comment by photopea** [comment]
Try this: https://www.photopea.com/tuts/photopea-says-i-am-blocking-ads-but-i-am-not/

**Comment by photopea** [comment]
I have to close it because of lack of details.
