### ISSUE TITLE
Control+Alt+Click while in selection mode doesn't auto-select the top (unlocked) layer

### ISSUE THREAD

**Issue by DirkBoer** [photopea/photopea#6273]
First of all big compliments to your product! I think your app should have a lot of more coverage then you at the moment seem to have.

I usually have Auto-Select off in the move tool and use Control+Alt+Click in selection mode select the top layer.

The big problem with Photoshop is that they also select the locked layers! See: 

https://community.adobe.com/t5/photoshop-ecosystem-discussions/prevent-locked-layer-to-be-selected-with-option-right-click/td-p/10838436

If understanding issue is fixed I instantly become member for a year and for sure spread that my friends should jump ship.

Your Operating System:
Your Web Browser: Chrome / Windows
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Make sure you have two layers on top of each other
3. In Move-tool make sure Auto-Select is turned off
4. In Selection-tool press Control+Right Click - watch the Context Menu with underlying layers (expected behaviour)
5. In Selection-tool press Control+**Alt**+Right Click - same menu appears. Expected behaviour: select automatically the top option from point 4. (see Photoshop behaviour as an example, but NOT their way how they handle locked layers)

**Comment by photopea** [comment]
I was not aware about this option in Photoshop, nobody ever asked for it. Are you sure it is a good thing to make it work differently than Photoshop? We have many Photoshop users and they probably expect it to work the same as PS.

**Comment by photopea** [comment]
I have implemented it the way you wanted (ignoring locked layers)

**Comment by DirkBoer** [comment]
Wow! You are a beast!
Just bought a subscription and will 100% start spamming all my friends.

Crazy how you made also everything slightly better then Photoshop and for sure even more performant.

**Comment by photopea** [comment]
thanks :)
