### ISSUE TITLE
Guides and align problem

### ISSUE THREAD

**Issue by jasonh77tw** [photopea/photopea#6274]
Your Operating System: Windows 11
Your Web Browser: Edge
The problem happens in the Incognito Mode, too: Not sure

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....Create a specified size select from left top corner, for example 100x100
3. ....Draw a vertical guide and let it snap at the right side of selected area 
4. ....Clean up the specified size select area and create a new free size select from left top corner
5. ....Resize the select area to snap the guide line, you will find the width of select area become 101, not 100

I used photoshop to create test patterns or align patterns, it heavily depends on guides.
It would be great if this issue can be fixed.

Thank you

**Comment by photopea** [comment]
Hi, it should be fixed now.

**Comment by jasonh77tw** [comment]
Thank you so much :)
