### ISSUE TITLE
No keyboard shortcut to close a file?

### ISSUE THREAD

**Issue by mindplay-dk** [photopea/photopea#6275]
It appears there is no keyboard shortcut to close a file?

I looked in the "File" menu, but the option to "close" isn't even listed there.

I looked at "More" -> "Keyboard shorcuts", and nothing is listed there either.

I saw the thread #154 which talked about adding Photoshop-like keyboard shortcuts, but no shortcut for "close" was mentioned.

It looks like the only way to close a document is by clicking the tiny close-button on the tab?

That's extremely inefficient when working through a large number of files, having to reach for the mouse and aim for that tiny button.

Since we can't use CTRL+W, how about something near that key, let's say, CTRL+Q maybe?

**Comment by photopea** [comment]
Photopea has the same shortcuts as Adobe Photoshop and other programs. You can use Ctrl+W to close the current document.

Note, that some browsers have bugs, and they close the browser tab when you press Ctrl+W, so don't use these browsers.

When I use Photopea in Google Chrome, Ctrl+W closes the tab. But if I install Photopea using More - Install Photopea, Ctrl+W closes the current document.

I am afraid that we invent our own shortcuts, people will never discover them. It is better to use "well-known" shortcuts.

**Comment by mindplay-dk** [comment]
> Note, that some browsers have bugs, and they close the browser tab when you press Ctrl+W, so don't use these browsers.

sooo... don't use the most common browser on the internet? 🙂

> When I use Photopea in Google Chrome, Ctrl+W closes the tab. But if I install Photopea using More - Install Photopea, Ctrl+W closes the current document.

what is "More"?

> I am afraid that we invent our own shortcuts, people will never discover them. It is better to use "well-known" shortcuts.

I'd agree, in principle, but reality is this won't work for the majority of users. (66% use Chrome.)

as a web developer, I would say it's bad good practice to attempt to override standard OS keyboard shortcuts - regardless of some lesser known browsers permitting you to do so, most browsers will not.

being unable to override OS shortcuts is a security feature - if every website could hijack CTRL+W, pretty soon you'd never be able to close anything on the internet ever again without reaching for your mouse.

(btw, you don't list the CTRL+W shortcut in the keyboard shortcuts panel - not that it would help most users, since it doesn't work on their browsers.)

**Comment by photopea** [comment]
When you open www.Photopea.com, there is a menu at the top (File, Edit, ...). One of these menu items is named "More", and if you click it, you will see a submenu with "Install Photopea".

I don't even know if there exists a browser which allows websites to use Ctrl+W. I use Chrome, but I never wanted to close a document with a keyboard. I do not see a problem with letting websites override Ctrl+W, as browsers usually provide many other ways to close a tab. Browser already allow websites override Ctrl+O and Ctrl+S.

**Comment by mindplay-dk** [comment]
Sorry, I didn't understand you were referring to a menu item! Running it as an app works, thank you! 🙂

**Comment by Victorcorcos** [comment]
@mindplay-dk

What I did in order to make this feature available is:
1. Installing photophea locally (More > Instal Photophea)
2. `Ctrl + W` (`Cmd + W` for mac) to close the current file

It does not work online because this keyboard shortcut closes the tab is common browsers.
