### ISSUE TITLE
I can't seem to move folders or layers here... (webapp)

### ISSUE THREAD

**Issue by MesaBlack** [photopea/photopea#6276]
[Screen recording 2024-01-01 5.20.17 PM.webm](https://github.com/photopea/photopea/assets/132141735/02a89211-b167-479b-b807-1a46e13bf9fe)

**Comment by MesaBlack** [comment]
no audio... lemme try again

**Comment by MesaBlack** [comment]
[Screen recording 2024-01-01 5.22.34 PM.webm](https://github.com/photopea/photopea/assets/132141735/04e770a1-3a1f-4343-899b-a7293bf44753)

**Comment by photopea** [comment]
Could you try it in the Incognito mode, i.e. without any browser extensions?

**Comment by MesaBlack** [comment]
nvm

**Comment by photopea** [comment]
What does it mean?

**Comment by camoody1** [comment]
> What does it mean?

"nvm" means "nevermind". I assume they figured out a fix for whatever their issue was.

**Comment by photopea** [comment]
I will come to your house, knock on your door for 3 hours, and when you come to open, I will say "nvm" and leave :D

**Comment by MesaBlack** [comment]
I hope what you say is satire

**Comment by photopea** [comment]
@MesaBlack So what was the problem? Could you explain what was happening with your computer?

**Comment by MesaBlack** [comment]
It was probably the program lagging or something
