### ISSUE TITLE
Photopea video advertisement display is unsupported in public browser.

### ISSUE THREAD

**Issue by JulienSimons** [photopea/photopea#6278]
Operating System: Windows 11
Web Browser: Microsoft Edge
The problem does NOT happen in the Incognito Mode.

**This must be done to see the problem**
1. Go to www.photopea.com
2. Select Magic Replace Tool
3. Click OK

**Comment by photopea** [comment]
Hi, what is a public browser? Do you use any ad blockers? I think you are blocking ads.

**Comment by photopea** [comment]
By the way, I can use the Magic Replace in Photopea in MS Edge, video ads are played correctly.  I do not have any browser extensions.

**Comment by photopea** [comment]
I have to close it, because of the lack of details :(

**Comment by JulienSimons** [comment]
> Hi, what is a public browser? Do you use any ad blockers? I think you are blocking ads.

I had all ad blockers turned off. In any case, it work functions in a private browser (incognito).

**Comment by photopea** [comment]
Does it work in a regular mode, if you disable all your extensions?
