### ISSUE TITLE
There is a gray space on the page that was not there before.

### ISSUE THREAD

**Issue by GTXDavid45** [photopea/photopea#6279]
Your Operating System: Windows 11 Pro 23H2
Your Web Browser: Microsoft Edge Version 120.0.2210.91
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com

![image](https://github.com/photopea/photopea/assets/125165383/abedace7-1962-48ee-89da-169e9bb663e9)

**Comment by camoody1** [comment]
That's where advertisements are supposed to be that support the free use of Photopea. You have one or more ad blockers operating on your browser that are preventing these ads from being displayed. You should disable those blockers when you use Photopea.

**Comment by photopea** [comment]
There should be advertisement on the right side. Please, do not block our ads! Photopea would not exist if everyone blocked ads. Almost nobody wants to pay for Photopea, so ads are the only reason we still exist.

**Comment by photopea** [comment]
I will close it now. We should add a clear message in the future, to tell people they are blocking ads.
