### ISSUE TITLE
Snap and guides for the Move function within text layer

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#628]
Snap and guides function are not in the move function within text layer

**Comment by photopea** [comment]
Hi, you can enter the Text layer only with the Type tool (not with Move tool). Do you mean there is no snapping with the Type tool?

**Comment by hgs54371** [comment]
The move function in text layer no snapping and snap guide

**Comment by photopea** [comment]
You forget verbs in your sentence. The Constrained text (in a rectangle) has snapping and guides.

**Comment by hgs54371** [comment]
Oh the text box has it, because I rarely type with the text box, didn't notice it, so by move I mean the one that just added recently

**Comment by photopea** [comment]
Hi, I added snapping for the free text layers, too. Such layer is defined by one point of origin, so this origin point is snapped (i.e. not the bounding rectangle of the text).

**Comment by hgs54371** [comment]
I didn't know it is snap-able just at one point, thought the bounding is growing with the text added, this would be better than just one point

**Comment by photopea** [comment]
It was not snappable at all. I made it snappable with one point. What is not usable?

**Comment by hgs54371** [comment]
I found the real problem,

Just like rec shapes, what you snap to is the bounds on four sides, but right now the bounds of text is not exactly the space they take up, for both free text and box text.

The bounds right now is not an accurate representative of the space the text take up
![screen shot 2018-04-09 at 5 30 30 am](https://user-images.githubusercontent.com/36803688/38472742-265c2f44-3bb7-11e8-9945-5ecbec2467b6.jpg)
A more accurate bounds that is useful for snapping in red
![screen shot 2018-04-09 at 5](https://user-images.githubusercontent.com/36803688/38472784-d55051f6-3bb7-11e8-82c8-d083c710671f.jpg)

**Comment by photopea** [comment]
Why do you have such a small rectangle for such a long word? The one word can not be broken into two lines, so it reaches out of the box.

The bounds of text would be a very useles thing to snap. It changes when you change a font (or font size, tracing etc.).

**Comment by hgs54371** [comment]
Other than that, this font is protruding at the left, but the bounds didn't grow with it just like shape would

I expect that bounds for text just behave like bounds for shapes, they change just as the content change, otherwise what exactly are bounds, and how exactly snapping is used

**Comment by photopea** [comment]
There is a constrained text, which is rendered into a rectangle, and the free text, which is defined by one point. See photopea.com/learn/text .

You can snap the text according to pixel bounds with a Move tool.

**Comment by hgs54371** [comment]
Now I know how to call it, the pixel bounds, this is the one that snapping should Always snap to, whether in move tool or the move function in text tool, what's the point to snap to any other things

**Comment by photopea** [comment]
Absolutely not. With a constrained text, you want everything to be in a rectangle. If you rewrite text, pixel bounds may change (e.g. while aligned to the left, words rarely touch the right side of the rectangle precisely). What you want is to align the constraint rectangle, not the pixels.

**Comment by photopea** [comment]
Do you always write just one-line text? and create a new layer for another line of text? You should really try to use constrained text, it saves a lot of headache.

**Comment by photopea** [comment]
If you need your free text be aligned to something on the right side, just set text-align to the right, and the origin point would be on the right side of text.

**Comment by hgs54371** [comment]
The font protruding issue like the one showed above make both the bound of constrained text and the point of free text not usable for snapping on the left side, snapping on the left side for this kind of font Needs pixel bound, not others
