### ISSUE TITLE
Bad saving files

### ISSUE THREAD

**Issue by BVPmarketing** [photopea/photopea#6280]
I have an issue, each time, when I try to re-open my saved .PSD, even the exported .PNG files, I receive the same error message: "Unknown file format/U0000... "

**Comment by photopea** [comment]
I think you use browser extensions, which rewrite all saved files. Did you try to run Photopea without allowing any browser extensions to rewrite saved files?

**Comment by BVPmarketing** [comment]
Hi, Thank you for reply. I think I have not these kind of extensions into my browser. Even I Already uninstalled all extentions and run Photopea without allowing any browser extensions, but this issue yet not solved.

**Comment by photopea** [comment]
Can you make Photopea generate a corrupted (unopenable) file, when it runs with no browser extensions?

**Comment by photopea** [comment]
So in short:
1) The error when opening a PSD means, that the PSD is damaged (corrupted).
2) If you get a corrupted PSD file out of Photopea, it was probably damaged by your browser extensions.
3) If you know how to create a damaged PSD with Photopea (with no extensions), let us know.
