### ISSUE TITLE
Photopea - none of the tools on on the left are working 

### ISSUE THREAD

**Issue by agilityollie** [photopea/photopea#6281]
Your Operating System: Microsoft Windows
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: don't know

None of the tools from "select" to "zoom" are working. I can't select any of them.

![Capture](https://github.com/photopea/photopea/assets/155554720/e4ceb5eb-4c84-4f98-b989-42465f254eec)

**Comment by agilityollie** [comment]
Update: I tried using the Microsoft Edge browser and they are working there. But, they aren't working in Chrome

**Comment by photopea** [comment]
I think you use browser extensions, which change how Photopea works. Did you try to run Photopea without allowing any browser extensions to interfere with Photopea?

If you dont know how to turn off your extensions, you can use a different browser or a different computer, where you did not install any extensions yet.

**Comment by agilityollie** [comment]
Ah, yes. It was my Adblock extension. Weird, because I've had that extension in Chrome for years, now, but today was the first time it caused a problem. Good to know, though. Thanks.

**Comment by photopea** [comment]
Report this problem to the creator of your extensoin and ask them to fix it.
