### ISSUE TITLE
Export to PDF - Stroke on shapes are not correctly displayed

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6282]
Your Operating System: Chromeos
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a shape
3. Give it a outside stroke of 10 
4. Export to PDF

You'll see that the stroke is filled after the shape's fill: So you can see it centered
![image](https://github.com/photopea/photopea/assets/11801254/6d7bbd61-dc59-4c35-a6da-2ce82d0c2773)

**Comment by photopea** [comment]
I have fixed it by stroking the shape with a double thickness before filling it. However, exporting the inner stroke will still not work. PDF files have only "centered" stroke and advanced vector editors export non-standard strokes as filled paths.
