### ISSUE TITLE
Ruler resets after switching to another tool

### ISSUE THREAD

**Issue by SooZoodimp** [photopea/photopea#6283]
Windows 10 Home
Firefox 121.0 (64-bit) (same in Chrome 120.0.6099.200 (64-bit))
The problem happens in the Incognito Mode too.

1. Go to www.photopea.com
2. Select **Ruler** tool
3. Measure something (values appear in top bar - it's ok)
4. Switch to another tool
5. Switch back to **Ruler** tool (graphic visualization of ruler keeps the same, although the top bar values resets to zero)

video: https://app.screencast.com/d18hSPwd6hApK

It's not a big issue. It doesn't bother me that much. But I thought, You should know.

Thanks for your amazing project that is Photopea.

**Comment by photopea** [comment]
It should be fixed now.
