### ISSUE TITLE
any chance to use magic replace tool for free? need that right now..(

### ISSUE THREAD

**Issue by xyzzart** [photopea/photopea#6285]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by xyzzart** [comment]
after clicking OK nothing happens
![image](https://github.com/photopea/photopea/assets/87940617/e875268f-de81-4925-9f7f-e009a11f882b)

**Comment by xyzzart** [comment]
> So you are not seeing the ad? Did you try it in the Incognito mode?

thanx. it works now!

**Comment by photopea** [comment]
You are using an ad blocker! If you dont know which of your extensions is an ad blocker, try to turn off all your browser extensions.
