### ISSUE TITLE
The text tool takes very long to load and sometimes fails completely. if it does load, it takes ages and the same is repeated each time you try to change the font.

### ISSUE THREAD

**Issue by rose-Hyperthread** [photopea/photopea#6286]
Your Operating System: Windows 11 Pro, Intel(R) Core(TM) i5-8350U CPU, 16,0 GB Memory, (this bug has been present across multiple computers I've used over the past 3 months, which has been around 4 to 5 PCs)
Your Web Browser: Chrome (up-to-date) 
Internet Speed Mbps: down - 42.0   up - 3.57
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Select text tool
3. Click anywhere on project

**Comment by camoody1** [comment]
Do you have the checkbox marked for loading Local Fonts? And do you have a LOT of local fonts?

I can tell you from my usage that the text tool runs quite snappy on my machine which isn't much higher specs than yours.

**Comment by photopea** [comment]
Can you see any errors in a web console? Maybe you have a firewall or something, which blocks our fonts.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
