### ISSUE TITLE
Web interface AND App width limited to1520px

### ISSUE THREAD

**Issue by wysocki** [photopea/photopea#6288]
Your Operating System: Win11
Your Web Browser: Chrome

**This must be done to see the problem**
1. Go to www.photopea.com or open app
2. Open any file
3. If screen width > 1520, display cannot be stretched beyond that.
![2024-01-05 16 09 40](https://github.com/photopea/photopea/assets/575556/c56785a5-6ffe-4fb5-b532-bec8a6b9f2d9)

**Comment by camoody1** [comment]
You're using an Ad Blocker extension. That blank area is supposed to be filled with advertisements that make Photopea free to use. If everyone blocks these advertisements, Photopea will no longer be available for everyone.

**Comment by photopea** [comment]
That is correct, there should be advertisement. Please, do not block our ads, our existence depends on them. You can also pay $15 to get Photopea without ads for 3 months: https://www.photopea.com/promo/no_ads.png
