### ISSUE TITLE
Duller color photo when viewing in photopea canvas

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#629]
Screenshot in both web page and on mac locally
![screen shot 2018-04-09 at 5 05 37 am](https://user-images.githubusercontent.com/36803688/38472944-204b9d80-3bba-11e8-904d-bd65af929a42.jpg)
Screenshot in photopea canvas (drag n drop from both web and desktop)
![screen shot 2018-04-09 at 5 05 48 am](https://user-images.githubusercontent.com/36803688/38472945-215320cc-3bba-11e8-8b14-76ca250a6d16.jpg)
The wood table and red shirt is a lot duller in photopea canvas

**Comment by photopea** [comment]
Hi, can you show us the original image? (not a screenshot)

**Comment by hgs54371** [comment]
The link from google image
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=2ahUKEwjJjcP2yKvaAhWM2LwKHWLsBbcQjRx6BAgAEAU&url=https%3A%2F%2Fwww.mercurynews.com%2F2017%2F05%2F18%2Fapple-wants-to-light-up-your-inner-soul%2F&psig=AOvVaw1k82qMkAMASHWOs2GHQFhS&ust=1523307461002625

**Comment by photopea** [comment]
Hi, my guess is, that your photo uses some weird color profile (not sRGB). Not only Photopea, but also other imare viewers may have problems with it (e.g. web browsers - Chrome or Firefox, it also looks "dull" when you open this image in them).

I recommend to convert the image into sRGB profile, to make sure it is supported everywhere.
