### ISSUE TITLE
Bug: Layer Mask Icon Does Not Show Mask

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#6291]
Your Operating System: Windows 11 Pro
Your Web Browser: Microsoft Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Add a layer mask to any layer.
3. Paint in a mask.
4. The layer mask icon should (I believe) show a representation of that mask. Mine does not.

I'm not sure if this affects everyone or if I've somehow disabled this functionality for myself.
![Screenshot 2024-01-06 185303](https://github.com/photopea/photopea/assets/73725653/9574322c-8f00-4b14-9a7d-1b0bfbcecf73)

**Comment by photopea** [comment]
Did you try it in other borwsers? It happens only in Edge or in other browsers, too? What if you save your work as a PSD and load it back into Photopea?

**Comment by MichalSZZ** [comment]
The color of the mask is gray. Are you sure, your mask isn't a vector mask?

**Comment by camoody1** [comment]
> The color of the mask is gray. Are you sure, your mask isn't a vector mask?

I'm sure it's a Raster Mask.

**Comment by camoody1** [comment]
> Did you try it in other borwsers? It happens only in Edge or in other browsers, too? What if you save your work as a PSD and load it back into Photopea?

I've tried it in Microsoft Edge, Google Chrome and Mozilla Firefox. All of the masks are just gray blocks like the above image. I opened an image, added a layer mask and masked out a section. Then, I saved the project as a PSD file. Closed it and reopened it. The layer mask is still just a gray box as shown above.

**Comment by photopea** [comment]
Does it happen only for this file, or for other files too (with a different resolution)? Could you share your PSD with us?

**Comment by camoody1** [comment]
It happens with all files and resolutions. It's been this way for as long as I can remember.

**Comment by photopea** [comment]
Does it happen even when you open this PSD in the Incognito mode? www.photopea.com/#ic34JfmhO  . Also, do you use any webpage zoom for Photopea?

**Comment by camoody1** [comment]
Same gray box. No zoom. 🤷🏼‍♂️

![image](https://github.com/photopea/photopea/assets/73725653/f22838c2-c1fa-44dc-a703-55988fdc731d)

**Comment by photopea** [comment]
Could you try the Burger menu of the Layers panel to increase or decrease the size of thumbnails? Does it change?

**Comment by photopea** [comment]
Also, what number do you see here? https://johankj.github.io/devicePixelRatio/

**Comment by camoody1** [comment]
> Could you try the Burger menu of the Layers panel to increase or decrease the size of thumbnails? Does it change?
I tried this earlier. I made the thumbnails very large and the box was still just gray.

> Also, what number do you see here? https://johankj.github.io/devicePixelRatio/
![image](https://github.com/photopea/photopea/assets/73725653/410acbae-5d92-4366-8ca0-4ec33de9c345)

**Comment by photopea** [comment]
Is it Windows? How did you set the scale of our OS to 110%?

**Comment by camoody1** [comment]
> Is it Windows? How did you set the scale of our OS to 110%?

Yes, of course it's Windows. Windows 11 Pro. I'm not smart enough to run Linux and not wealthy enough to run a Apple OS. 😂
I have my windows text size set to 110% because I'm running a 2560x1600 monitor that's only 15-inches in size. I wouldn't be able to read the words, otherwise.

**Comment by camoody1** [comment]
Oh... My... God.

I changed my Windows Text Scale back down to 100%... and it's working correctly, now. 😂

Is there no way to account for that on your end in the code? That's so crazy that a text scale would affect the display of that layer mask. Great job figuring that out, Ivan.

**Comment by camoody1** [comment]
And as soon as I went back to 110% scaling, the layer mask went back to gray. So sad :(

**Comment by photopea** [comment]
Great, I was able to reproduce it. And if I can reproduce it, I can fix it, so it is fixed now.

**Comment by photopea** [comment]
I think it happened to many people in the past, but nobody reported it, so thanks a lot for your patience while helping me :)

**Comment by camoody1** [comment]
I just got a chance to test it again after your changes. It works perfectly! Thank you so much, sir. You did a great job drilling down to that level to figure it out. Well done.
![image](https://github.com/photopea/photopea/assets/73725653/758b9668-79fa-49f9-9488-347e86ea93b6)
