### ISSUE TITLE
after i use the pen to make a path, i am unable to use move tool correctly

### ISSUE THREAD

**Issue by ondad** [photopea/photopea#6293]
Your Operating System: windows 11
Your Web Browser: google chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. create a path with pen tool. i have it on unite
3. i usually then right click and make it a selection, delete the path and do whatever i need like mask the object by deleting the selected area or creating a new layer via copy (CTRL + J)
4. then once i get rid of the selection and want to resize or rotate the object via move tool, i cannot. it allows me to move the image around but not rotate or change the size. the measurements in width, height and etc. then come up as NaN%. (check image)
5. the only way ive been able to fix this issue is saving my file and then opening it again, but because i am using the pen tool very frequently this keeps happening over and over again. 

![Screenshot (23)](https://github.com/photopea/photopea/assets/155899796/b5f583bb-097a-4924-9c7e-c31adb9a1674)

**Comment by photopea** [comment]
How do you delete the path? I think your path still contains one point. The Free Transform will try to transform this path.

You can delete or at least deselect the work path in Window - Paths.

**Comment by camoody1** [comment]
@ondad Can confirm that your list of steps DOES work for me. So, there must be something you're missing that you don't normally miss.

**Comment by photopea** [comment]
So as I said, you still have a one-point path. Open the Paths panel (Window - Paths) and delete the work path.

**Comment by photopea** [comment]
I have found a serious bug with a Pen tool, and it should be fixed now.
