### ISSUE TITLE
Merge a duplicated layer group by script, merge the wrong layer

### ISSUE THREAD

**Issue by tempart45** [photopea/photopea#6294]
Your Operating System: Windows 10
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com/#iYbAVv5fU
2. Run the following script.
3. The merged layer is the original layer not duplicated one.

`var layer = app.activeDocument.layers[0];
var duplicated = layer.duplicate();
var merged = duplicated.merge();`

![imagen](https://github.com/photopea/photopea/assets/155907415/a30a64a9-723d-4ce3-8e5c-b27134124138)

**Comment by photopea** [comment]
thanks, it should be fixed now.
