### ISSUE TITLE
Photopea .psd save file erased edits from most layers and altered some layers' properties

### ISSUE THREAD

**Issue by PenniBirb** [photopea/photopea#6295]
Your Operating System: Windows 64-bit operating system
Your Web Browser: Microsoft Edge
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. create .psd file
3. save .psd file
4. ???
5. close photopea
6. reopen photopea
7. open save file to find... whatever this is supposed to be
![GrapeDTIYS (3)](https://github.com/photopea/photopea/assets/155908396/75aa8a69-ab0f-4654-a729-c56ee0953b14)
<img width="1032" alt="Screenshot 2024-01-07 110721" src="https://github.com/photopea/photopea/assets/155908396/dd865aa6-2ecb-4a98-82b0-09ca744635b6">
<img width="215" alt="image" src="https://github.com/photopea/photopea/assets/155908396/d9c25b66-942e-45ed-b872-7a9710ab242f">

**Comment by PenniBirb** [comment]
shoot I forgot to add my OS and browser

**Comment by photopea** [comment]
What should I do to see this problem happen? Whenever I save a PSD and re-open it in Photopea, it opens exactly as it looked before saving.

Are you sure you have opened the PSD file which you saved before?

**Comment by photopea** [comment]
Your screenshots are very unclear. Which do you consider to be right and which are supposed to be wrong?

**Comment by PenniBirb** [comment]
the version with the miscoloured face and most of the colour missing is the error I encountered
the screenshot after is a sample of all the layers that had their edits erased after I reopened the .psd file

Is there anything else I could grab a screenshot of that may help?

**Comment by photopea** [comment]
I need to see the error myself somehow.

Do you have a PSD file, which you can open in Photopea, and if you save it, you get a different PSD file (with a different PSD content)? Could you show me this file? Or could you record a video of doing the steps 1 to 7, so that I can see what you do?

**Comment by photopea** [comment]
I have to close it because of lack of details.
