### ISSUE TITLE
Merged layer group by script return unusable reference

### ISSUE THREAD

**Issue by tempart45** [photopea/photopea#6296]
Your Operating System: Windows 10
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com/#iYbAVv5fU
2. Run the following script.
3. View errors in console

`var layer = app.activeDocument.layers[0];
var merged = layer.merge();
merged .visible = false;`

It seems to be related with #6294

**Comment by photopea** [comment]
fixed! :)
