### ISSUE TITLE
No me deja abrir ni proyecto ni importar uno mío

### ISSUE THREAD

**Issue by luucantoss** [photopea/photopea#6298]
Le doy a los botones de "Nuevos proyecto" o "Abrir desde computadora" y no ocurre nada.

Me sale esto en la consola:
![Captura photopea](https://github.com/photopea/photopea/assets/122809463/d462958a-eab2-4144-9ad8-7db1a87cc198)

**Comment by photopea** [comment]
Did you allow your browser extensions to modify Photopea?

Could you click this button and show us what you see there?
![image](https://github.com/photopea/photopea/assets/15955558/ae8b876e-0efb-43ac-903f-fdcbede70f4c)

**Comment by luucantoss** [comment]
sii, de eso no me daba ningun error creo

![image](https://github.com/photopea/photopea/assets/122809463/81748a74-78cf-45e7-b367-3fc618e5910d)

**Comment by photopea** [comment]
Could you disable your extensions, which are allowed to modify Photopea? I dont speak Spanish, but I think you can understand what is in your photo.

**Comment by luucantoss** [comment]
Vale, todo quitado, pero ahora me aparece esto

![image](https://github.com/photopea/photopea/assets/122809463/c9875dd2-d37f-4d41-be74-0433122d5987)

**Comment by camoody1** [comment]
Why does your Address Bar say localhost:8080 instead of photopea.com?

**Comment by photopea** [comment]
Yeah, why are you opening "localhost:8080"?

**Comment by luucantoss** [comment]
Según esto, había que abrirlo ahí para usarlo offline no?

Descargar el repositorio
abrir una terminal
cden la carpeta donde lo descargaste
En la carpeta, escribe esto:python -m http.server --directory www.photopea.com 8080
Abra http://localhost:8080/ . Debería cargarse y podrás usarlo como de costumbre.

No se si me estoy equivocando

**Comment by camoody1** [comment]
Uh oh... I'm not sure where you read that information, but it's not from the official Photopea site.

Just open photopea.com in your browser. Then, if you want to install it as a webapp, just go into your browser menu and find an option for "Install as app".

**Comment by luucantoss** [comment]
Perfecto, muchas gracias

**Comment by camoody1** [comment]
You're welcome 😊
