### ISSUE TITLE
UI isn't fill all the screen

### ISSUE THREAD

**Issue by chivy141206** [photopea/photopea#6299]
Your Operating System: Windows 11
Your Web Browser: Chrome 120.0
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Look at the screen, you can see this bug (or click into the link below to see the image)
![image](https://github.com/photopea/photopea/assets/44723787/8bbc3b9d-b7ca-4d3d-82da-d26fd137f9fe)

**Comment by photopea** [comment]
There should be advertisement on the right side. You are probably blocking our ads. Could you watch our ads, please? Since less than 0.1% of our users pay for Photopea, we depend on ads. We would not exist if everyone blocked ads.

**Comment by photopea** [comment]
So I will close it now.

**Comment by ZribeDev** [comment]
Same issue, not blocking ads.

**Comment by photopea** [comment]
Did you try this? https://www.photopea.com/tuts/photopea-says-i-am-blocking-ads-but-i-am-not/

**Comment by ZribeDev** [comment]
Yea i did try that, but it did not work. at the end i just bought a subscription for 90 days! Worth it. no regrets

**Comment by photopea** [comment]
Thanks a lot! But we can still keep digging to find out what is blocking ads. Ads are blocked in Russia, Iran and other countries automatically because of sanctions.
