### ISSUE TITLE
Have the current window get noticeable with a teal outline.

### ISSUE THREAD

**Issue by MesaBlack** [photopea/photopea#6301]
what it says. A moment there I didn't notice the current window is #6300.

**Comment by photopea** [comment]
What exactly was the "current window" in your video? What did you do to make it happen?

**Comment by MesaBlack** [comment]
the color picker one

**Comment by MesaBlack** [comment]
I thought it wasn't there

**Comment by photopea** [comment]
It should be fixed now. In a case like in your video, it should move the color picker window from the back to the front.
