### ISSUE TITLE
Loads my previous works all together causing a massive load time and lag

### ISSUE THREAD

**Issue by Retronetic** [photopea/photopea#6303]
Your Operating System: Windows
Your Web Browser: Opera GX
The problem happens in the Incognito Mode, too: No

It never used to happen to me before, sometimes it would just load the work i did the previous time, but now it loads like about 5 works I've done previously all together causing my entire browser and pc to lag and stutter and results in a huge load time. It happens no matter how many times i close my work from Photopea.

**This must be done to see the problem**
1. Go to www.photopea.com or Refresh the Page

**Comment by camoody1** [comment]
@Retronetic Take a look at this page and see if it helps you out with your issue.
https://www.photopea.com/tuts/photopea-opens-up-old-files/

**Comment by photopea** [comment]
I have to close it because of lack of details.
