### ISSUE TITLE
Clipboard Pasting Not Functional

### ISSUE THREAD

**Issue by nwasira** [photopea/photopea#6304]
Your Operating System: Chrome OS
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Haven't tested

**This must be done to see the problem**
1. Go to www.photopea.com
2. Use Keyboard Shortcut: Search +V (only Chromebook)
3. Click on a thumbnail of an image
4. Observe that it does not get pasted into the project

This used to work, I'm not sure why clipboard pasting isn't functional currently.

**Comment by photopea** [comment]
Could you test it in the Incognito mode?

**Comment by nwasira** [comment]
I will let you know later. I am not home.

**Comment by nwasira** [comment]
Not working in incognito either :/

**Comment by photopea** [comment]
Does Photopea have permission to access the clipboard? Can you paste the clipboard content with Search+V into other websites, e.g. into www.imgur.com ?

**Comment by nwasira** [comment]
Yeah, I can. Just not Photopea + I allowed clipboard access in settings, it's still not working..

**Comment by photopea** [comment]
Sadly, I dont have a Chromebook to try it out :(

**Comment by photopea** [comment]
Did you solve it somehow?

**Comment by photopea** [comment]
I have to close it because of no response from the user :( You can still respond, if you have time.
