### ISSUE TITLE
[window-controls-overlay] [quick fix] add draggability to top bar

### ISSUE THREAD

**Issue by glitch128** [photopea/photopea#6305]
hey, I forgot to add draggability to the code in #5085. could you please add `app-region: drag;` to the topbar? and add add no-drag to the buttons

[all.css.txt](https://github.com/photopea/photopea/files/13891031/all.css.txt)
```css
.topbar {
app-region:no-drag;
}
```
[pp.js.txt](https://github.com/photopea/photopea/files/13891079/pp.js.txt)
```js
float:right; padding:4px;display:none; position:relative;z-index:1;app-region:no-drag;
```
```js
position:relative; width: "+W+"px; height: "+s+"px; overflow:hidden; white-space: nowrap; app-region:drag;
```

**Comment by photopea** [comment]
I think your code will not work, I did not use your code in https://github.com/photopea/photopea/issues/5085 either. Usually, there is not that much empty space. You must drag it using a tiny space on the right side, in between the browser UI buttons.

**Comment by glitch128** [comment]
run this code in the javascript console
```js
document.querySelector("div[style*='position:relative;']").style.appRegion = "drag"
document.querySelector("div[style*='position: absolute; left: 0px;']").style.appRegion = "no-drag"
document.querySelector("div[style*='float: right; padding: 4px;']").style.appRegion = "no-drag"
```
this will add the CSS properties temporarily to show that it will work.

**Comment by photopea** [comment]
okay, I think I have implemented it. Thanks a lot for recommending it!
