### ISSUE TITLE
The crop tool is not working for me. 

### ISSUE THREAD

**Issue by RandileighV** [photopea/photopea#6306]
I am using Edge.
Windows 10 Home.
I have used the crop tool many times, however today it is not working. I tried logging in and out and restarting the page. It does not crop.

**Comment by photopea** [comment]
It seems to work fine for me. What should I do to see it not working? Did you try it in the incognito mode, where all your browser extensions are disabled?

**Comment by RandileighV** [comment]
I will check that.
With kind regards,
Randileigh Vaugeois

**Comment by photopea** [comment]
I have to close it because of no response from the user :( You can still respond, if you have time.
