### ISSUE TITLE
Clipping masks show the hidden parts when exported as an SVG file. 

### ISSUE THREAD

**Issue by D-Omega** [photopea/photopea#6308]
Your Operating System: Windows 11
Your Web Browser: Opera GX
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. .... make a design with a clipping mask
3. .... have the clipping mask be bigger than what its masking
4. .... export it as a SVG, and you will see that the parts that should be hidden are shown.

**Comment by photopea** [comment]
Only the PSD format can store exactly what you see in Photopea (with vector layers, text layers, clipping masks etc). All other formats have limitations and you might lose some data.

SVG files do not have any clipping masks like Photopea, where one raster image can be clipping another raster image.

Put your layers into a folder and apply a vector mask to that folder: https://www.photopea.com/learn/masks . It will be exported as a clipping path in SVG.
