### ISSUE TITLE
Save error

### ISSUE THREAD

**Issue by Hi2424000** [photopea/photopea#6309]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: yes

Problem: Even if i try to save my work it doesn't save, it doesn' even ask me if im sure about saving the first time i do it anymore and when i want to close my work it tells me that there's things that weren't saved

**This must be done to see the problem**
1. Go to www.photopea.com
2. create a new project
3. do anything you want
4. save and close the file
5. open the file again
6. modify it and save
7. close the file after save
8. open the file again
9. the problem appears (there´s no modifications, the work didn't save)

I hope to find out how to solve this soon, thanks

**Comment by photopea** [comment]
How do you open a file? Do you use File - Open, or drag-and-drop ?

How do you save a file? Do you use File - Save (available only sometimes), or File - Save as PSD?

As I understand, it is not saved when opening a file, but saved when creating a file?

**Comment by Hi2424000** [comment]
I open the file selecting it in the section "Open from computer".

I usually save using "ctrl+s" but i also tried going to file and saving there, but nothing happened, it just load as always but doesn't really save

when i open a file it already saved once, i mean im able to save it the first time but no after that, like im only able to create the file not modify it.

**Comment by Hi2424000** [comment]
actually i tried changing the resolution from 4k to 2k and now im able to save

**Comment by photopea** [comment]
It should not depend on the resolution. When you can not save for the second time, could you take a screenshot of your whole screen and show it to us?

**Comment by photopea** [comment]
I have to close it because of lack of details.
