### ISSUE TITLE
Snap to pixel bounds and have guides showing like move tool for the move function in text tool

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#631]
It would be better to also have guides showing when snapped and snap to the actual pixel bounds which is always available on all four sides and more universal for all types of fonts, just like in move tool

**Comment by photopea** [comment]
I disagree. Let's talk about vertical snapping. The guiding position could be e.g. a baseline (on which all characters are placed). E.g. you may have a guide (a horizontal line) and you want to put the text exactly on that line.

If you type a word "Stick", bottom pixel bounds are exactly on the baseline. But if you type "Sting", the letter "g" puts the bottom pixel bounds much lower, so snapping a baseline to a guide does not work anymore.

Moving the text with a Type tool works wit "logical bounds", while moving with a Move tool works with "pixel bounds". I would like to keep it that way.

**Comment by photopea** [comment]
There is a tiny black rectangle (the origin of free text) and you can usually deduce to what it was snapped.

**Comment by hgs54371** [comment]
It's not What/which it snapped, it's When/if it snapped (already or not)
