### ISSUE TITLE
Error when using getString, getList ActionDescriptor and executeAction

### ISSUE THREAD

**Issue by khanh-mac-i7** [photopea/photopea#6310]
Hi, I have a piece of code. It works fine on Photoshop. However, when running it on Photopea, it reports an error at the following section:
-    textDesc.getString(s2t('textKey'))
-    textDesc.getList(s2t('textStyleRange'))
-    executeAction(c2t("setd"),desc6,DialogModes.NO);

Can you please let me know what the issue is here? Thank you.

Here is the full code:

    var txt = ['Anna', 'Maria'];
    var colors=['#ff1b1b','#c20bf5','#64f50b','#0be7f5'];
    activeDocument.activeLayer=activeDocument.layers[0];
    executeAction(stringIDToTypeID('placedLayerEditContents'));

    for (var i=0;i<txt.length; i++){
        activeDocument.activeLayer=activeDocument.layers[i];
        const actLay = activeDocument.activeLayer;
        var s2t = stringIDToTypeID;
        var c2t = charIDToTypeID;

        if (actLay.kind === LayerKind.TEXT){
            var ref=new ActionReference();
            var idTxtS=s2t('textStyle');
            ref.putEnumerated(c2t("Lyr "),c2t("Ordn"),c2t("Trgt"));
            var textDesc=executeActionGet(ref).getObjectValue(s2t('textKey'));

            // ERROR
            var theText=textDesc.getString(s2t('textKey'));
            // ERROR
            var rangeList=textDesc.getList(s2t('textStyleRange'));

            var anIndex=0;
            var idT=c2t("T   ");
            var idTxLr=c2t("TxLr");
            var desc6=new ActionDescriptor();
            var ref1=new ActionReference();
            ref1.putEnumerated(idTxLr,c2t("Ordn"),c2t("Trgt"));
            desc6.putReference(c2t("null"), ref1);
            var desc7=new ActionDescriptor();
            desc7.putString(c2t("Txt "), theText);
            var list2=new ActionList();

            for (var m=0;m<theText.length;m++) {
                var desc14=new ActionDescriptor();
                desc14.putInteger(c2t("From"),m);
                desc14.putInteger(idT,m+1);
                var theStyle = rangeList.getObjectValue(0).getObjectValue(idTxtS);

                c=new SolidColor();
                c.rgb.hexValue=colors[anIndex].replace('#','');
                var desc21=new ActionDescriptor();
                desc21.putDouble(c2t("Rd  "),c.rgb.red);
                desc21.putDouble(c2t("Grn "),c.rgb.green);
                desc21.putDouble(c2t("Bl  "),c.rgb.blue);
                theStyle.putObject(c2t("Clr "),c2t("RGBC"),desc21);
                desc14.putObject(idTxtS,idTxtS,theStyle);
                list2.putObject(c2t("Txtt"),desc14);
                anIndex++;
                if (anIndex===colors.length){anIndex=0}
            }

            desc7.putList(c2t("Txtt"),list2);
            desc6.putObject(idT,idTxLr,desc7);

            // ERROR
            executeAction(c2t("setd"),desc6,DialogModes.NO);
        }
    }
    activeDocument.save();

**Comment by photopea** [comment]
I opened a JPG file in Adobe Photoshop and tried to run your script, but it throws an error.

What should I do to run your script in Photoshop? What document do I need? How many layers should it have?

**Comment by khanh-mac-i7** [comment]
Sorry for not describing clearly.
 You need to create a .PSD file and inside there is a layer of text.
<img width="1508" alt="Screenshot 2024-01-14 at 14 30 59" src="https://github.com/photopea/photopea/assets/41607851/f7b9034c-54a9-42aa-a10a-47198880b5c1">

And try running the following script (I'll rewrite it a little more simply):

    var colors=['#ff1b1b','#c20bf5','#64f50b','#0be7f5'];
    activeDocument.activeLayer=activeDocument.layers[0];
    var actLay=activeDocument.activeLayer;
    var s2t=stringIDToTypeID;
    var c2t=charIDToTypeID;

    if (actLay.kind===LayerKind.TEXT){
        var ref=new ActionReference();
        var idTxtS=s2t('textStyle');
        ref.putEnumerated(c2t("Lyr "),c2t("Ordn"),c2t("Trgt"));
        var textDesc=executeActionGet(ref).getObjectValue(s2t('textKey'));
        var theText=textDesc.getString(s2t('textKey'));
        var rangeList=textDesc.getList(s2t('textStyleRange'));

        var anIndex=0;
        var idT=c2t("T   ");
        var idTxLr=c2t("TxLr");
        var desc6=new ActionDescriptor();
        var ref1=new ActionReference();
        ref1.putEnumerated(idTxLr,c2t("Ordn"),c2t("Trgt"));
        desc6.putReference(c2t("null"), ref1);
        var desc7=new ActionDescriptor();
        desc7.putString(c2t("Txt "), theText);
        var list2=new ActionList();
    
        for (var m=0;m<theText.length;m++) {
            var desc14=new ActionDescriptor();
            desc14.putInteger(c2t("From"),m);
            desc14.putInteger(idT,m+1);
            var theStyle = rangeList.getObjectValue(0).getObjectValue(idTxtS);
            // Set color;
            c=new SolidColor();
            c.rgb.hexValue=colors[anIndex].replace('#','');
            var desc21=new ActionDescriptor();
            desc21.putDouble(c2t("Rd  "),c.rgb.red);
            desc21.putDouble(c2t("Grn "),c.rgb.green);
            desc21.putDouble(c2t("Bl  "),c.rgb.blue);
            // Put style to array
            theStyle.putObject(c2t("Clr "),c2t("RGBC"),desc21);
            desc14.putObject(idTxtS,idTxtS,theStyle);
            list2.putObject(c2t("Txtt"),desc14);
            anIndex++;
            if (anIndex===colors.length){anIndex=0}
        }
    
        desc7.putList(c2t("Txtt"),list2);
        desc6.putObject(idT,idTxLr,desc7);
        executeAction(c2t("setd"),desc6,DialogModes.NO);
    }


Thank you !!!

**Comment by photopea** [comment]
I have implemented the missing features, it should work well now :)
