### ISSUE TITLE
TIFF with many layers open as flatten image

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#6311]
Your Operating System: Win 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode too

Ivan, hi!
I encountered an unexpected problem when I needed to open multilayer TIFF files (I haven’t worked with this format for a long time). PS opens correctly, but PP opens in one layer.
I am attaching an example file
[example.zip](https://github.com/photopea/photopea/files/13898589/example.zip)

**Comment by photopea** [comment]
Hi, I think this is not a regular multi-layer TIFF file, but it is a PSD-like file embedded inside a single-layer TIFF file. Adobe came up with this format and nobody knows exactly how it works.

Can you open your TIFF file and see layers in some other program than Adobe Photoshop?

**Comment by Pt-home** [comment]
Intresting... And I think, you are right...
Gimp - no see layers, paint.net - no see layers. pixlr - no see layers, photo-paint - no see layers.
The most ironic thing is a quote from Adobe:
> Aldus Corporation (*Tiff author) was later acquired by Adobe, which has since been responsible for the copyright of the file format.

**Comment by photopea** [comment]
Just use PSD format! :) A lot of programs can work with the PSD format, but only one program can open that strange file that you decided to use.

**Comment by Pt-home** [comment]
But still, such an application was found - this is... Krita;)
![image](https://github.com/photopea/photopea/assets/29394245/6f04ae4e-3eb7-487f-ad1a-59a6253ea6d9)
![image](https://github.com/photopea/photopea/assets/29394245/3e97ab2e-2cc6-4f9a-94a2-98a68c73724e)

**Comment by Pt-home** [comment]
https://docs.krita.org/en/general_concepts/file_formats/file_tif.html

**Comment by photopea** [comment]
okay, you got me there! :) I have implemented it.
