### ISSUE TITLE
Erro ao qbrir arquivo PGN

### ISSUE THREAD

**Issue by lucianomerighetti** [photopea/photopea#6312]
Your Operating System: Abrir arquivo com imagem

Your Web Browser: Google Chrome, Mozilla Firefox

The problem happens in the Incognito Mode, too:
Ao tentar abrir um arquivo pela segunda vez está ocorrendo o erro abaixo, o erro ocorre tambem na aplicação desktop
![image](https://github.com/photopea/photopea/assets/99049549/a204caa1-956f-4534-adde-e2e4b2545b09)

**Comment by photopea** [comment]
That is very strange. Could you try to disable all your browser extensions? Or try it in a browser where you did not install any extensions?

**Comment by lucianomerighetti** [comment]
Ações executadas no Google Chrome
Fiz a desativação das extensões do navegador e o erro persistiu.
Quando eu abri em Modo Anonimo funcionou corretamente.

Ações executadas no Mozilla Firefox
Fiz a desativação das extensões do navegador a ferramenta funcionou corretamente, sem apresentar o erro

Aplicação Desktop:
O erro persiste, só é resolvido quando eu apago o arquivo TMP que é gerado quando estou editando o arquivo com a minha imagem

Conclusão
Creio que, por eu utilizar o ADBlock Plus, algum erro ocorrer pois quando eu abro sem o ADBlock Plus o Mozilla Firefox.
Como ADBlock Plus ainda fica on line mesmo quando desativo no Google Chrome o erro persistiu e quando eu executei o Google Chrome no Modo Anonimo a extesão não sobe, ele funcionou como o esperado.
A impressão que tenho é que o arquivo temporário que não é apagado quando fecho a aplicação na aplicação Desktop é o mesmo e está gerando que está gerando o erro na aplicação WEB

**Comment by photopea** [comment]
I dont think it is AdBlock Plus. Did you try to disable all your extensions except of Adblock Plus?

**Comment by lucianomerighetti** [comment]
Acabei de fazer esse teste e só com o Adblock Plus ficou travando. O Adblock Plus fechou cerca de 73mil anuncios, segue abaixo a imagem
![image](https://github.com/photopea/photopea/assets/99049549/4b929e75-7346-4c87-ad98-be6d24114377)

**Comment by lucianomerighetti** [comment]
Tem como vocês reduzirem esse volume de anuncios?

**Comment by photopea** [comment]
I dont think Photopea shows 73 000 ads. It is probably on all your webpages.

It is hard to understand, could you write in English, please?

**Comment by photopea** [comment]
I have to close it because of lack of details.
