### ISSUE TITLE
Text style SmallCaps doesn't use small caps table in font

### ISSUE THREAD

**Issue by tempart45** [photopea/photopea#6314]
Photopea seems to not manage the substitution table for small caps (smcp) and always fake it. 
www.photopea.com/#iHb7hbfde
In this example the text with the font FiraSans has a different render than Photoshop or LibreOffice Writer

![SmallCapsPhotoshop](https://github.com/photopea/photopea/assets/155907415/59ec3196-fca3-4872-ac11-ea97cc33679e)
![SmallCapsWriter](https://github.com/photopea/photopea/assets/155907415/6e947897-470e-4412-9093-073b3122cd1e)

**Comment by camoody1** [comment]
I never knew there were Real vs Fake small caps. So interesting.
https://creativepro.com/understanding-applying-small-caps/

**Comment by photopea** [comment]
Hey, I have fixed it! If the font supports GSUB/smcp, it will be used.
