### ISSUE TITLE
Can't Move the Layer Order and Bug Display

### ISSUE THREAD

**Issue by ElexiaNotMe** [photopea/photopea#6316]
Your Operating System: Android 13 TKQ1.220807.001
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

This must be done to see the problem

1. Go to www.photopea.com
2. Open any project

Can't change the order of layers from layer panel, I came across the same issue in the past and it happened exactly the same
https://github.com/photopea/photopea/issues/6070
I can't change the layer order except from Layer - Arrange - Move Forward/Backward, so I can't move layers into a folder.
In past cases (issues 6070) it seems that the problem was the client's Android version which was still using Android 8, but I am using Android 13 and this issue has never happened before on my device, the last date I remember I could still change the layer order was 2023-08-17 (based on the PSD date I use). After that I rarely used Photopea until recently when I wanted to use Photopea again this problem arose, it seems that between that time there was a problem either with Photopea or Google as an Android developer.

There is a bug issue that makes the project display inverted colors, and this only appears when using desktop mode in vertical rotation.
![Screenshot_2024-01-13-00-42-19-324_com android chrome](https://github.com/photopea/photopea/assets/136241694/68c4429d-0a58-4127-962d-4b5c3f78ffc2)
This problem can be solved when I change the rotation of the device to horizontal, but this is still quite annoying, especially in some projects where I make the screen vertical in the process.
It seems that this problem doesn't have a serious impact because I and maybe other people that using Android OS will use Photopea use photopea in mobile mode rather than desktop mode and using horizontally, but this could be a note for developers.

For both issues, I have used various other official browsers, such as Firefox, Brave, Edge, Mi, Mint, Opera, UC, Yandex, Kiwi and the results are still the same even in Incognito mode.

**Comment by photopea** [comment]
Is it on your phone? Can you read tiny letters? Please, switch to a regular view to see a proper size of the UI. Also, I think the GPU bug (inverted colors) happens because of the desktop view.

With Chrome for a modern Android (e.g. on my phone), you can tap and hold layers in order to drag them. Let me know if it works when you switch to a regular view.

**Comment by ElexiaNotMe** [comment]
Yes, because sometimes I need to mirror my device to monitor when do work, so I using desktop mode for a wider display and a small UI.

Thank you, it seems you have fixed this. I have tried both in regular view and desktop mode and now I can change the order of the layers, but I can't access the menu for each layer although this doesn't seem too important as it can be accessed in the layer menu on top. It just still has an effect on the experience when using photopea.

**Comment by photopea** [comment]
okay, I will close it now. You might consider buying a bluetooth mouse for your phone, to have a proper right-click. But yes, the Layer menu already contains many items.
