### ISSUE TITLE
The saving bar hangs up

### ISSUE THREAD

**Issue by kipitok99** [photopea/photopea#6317]
Your Operating System: Windows 10
Your Web Browser: Chrome

![browser_IU61pzwy8V](https://github.com/photopea/photopea/assets/156551317/0f875c86-d01e-4593-9810-7f7e5ac0ba28)

The saving bar hangs up and blocks access to properties

**Comment by photopea** [comment]
What should I do to see it happen myself? Did you try it in the Incognito mode?

**Comment by kipitok99** [comment]
No, I haven’t tried it incognito, I don’t know what actions cause saving to
freeze, is it possible to somehow transfer logs with actions?

вс, 14 янв. 2024 г., 01:43 Photopea ***@***.***>:

**Comment by camoody1** [comment]
This happens to me sometimes when I try to save large files to the cloud. My workaround is to save it, again, on my local machine, then closing Photopea and restarting it.

**Comment by kipitok99** [comment]
А computer file, it's crazy to refresh the page every time.

**Comment by photopea** [comment]
When Photopea freezes, could you look into a web console, and see if there are any errors?

Also, how much RAM do you have in your computer, and what is the maximum size of PSD files that you work with?

**Comment by kipitok99** [comment]
psd 18mb, 16 Gb RAM

**Comment by photopea** [comment]
I have 24 GB of RAM and I often worked with 200 MB PSD. Could you tell me how can I make Photopea freeze?

**Comment by kipitok99** [comment]
www.photopea.com/:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at id.akA (pp.js:208:115)
    at id.ays (pp.js:206:1)
    at e5.arR (pp.js:15875:4)
    at e5.<anonymous> (pp.js:15869:6)
    at pp.js:196:73

pp.js:15547 Uncaught (in promise) TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
    at dB.aDT (pp.js:15547:10)
    at jQ.kr (pp.js:15780:58)
    at e5.kr (pp.js:15889:37)
    at dK.p (pp.js:11181:49)
    at it.p (pp.js:11186:77)
    at e5.<anonymous> (pp.js:15995:40)
pp.js:15547 Uncaught (in promise) TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
    at dB.aDT (pp.js:15547:10)
    at jQ.kr (pp.js:15780:58)
    at e5.kr (pp.js:15889:37)
    at dK.p (pp.js:11181:49)
    at it.p (pp.js:11186:77)
    at e5.<anonymous> (pp.js:15995:40)

**Comment by photopea** [comment]
I would like to see it happen on my computer. Could you send me your PSD? Is it enough to open it in Photopea and save back as a PSD, or do I need to do something before saving a PSD, to see the error?

**Comment by kipitok99** [comment]
https://drive.google.com/file/d/1v0O7SzWWHyMicIaIaL0pOKHNf10fzK6C/view?usp=drive_link

**Comment by photopea** [comment]
Could you tell me if the error ever happened when you run Photopea with no browser extensions? E.g. disable all your extensions for a while, or use Photopea in the Incognito mode for a while. Your screenshot has no ads, so you use at least ad blockers, which obviously can rewrite the source code of Photopea.

Also, do you use Photopea at www.Photopea.com? You deleted the URL address from your screenshot.

**Comment by kipitok99** [comment]
![browser_ZSdd5cgjbD](https://github.com/photopea/photopea/assets/156551317/e1067dd3-6bf1-4b54-b2d3-74c0fb09e7f3)
Add-ons have nothing to do with it, ran in incognito mode die saving again hangs up
[www.photopea.com-1705252420591.log](https://github.com/photopea/photopea/files/13932447/www.photopea.com-1705252420591.log)
Most likely if you press 2 times in a row bistro save, the die hangs.

**Comment by photopea** [comment]
Yeah, seems like that is the bug - pressing Ctrl+S twiche quickly in a row, when File - Save is available.

**Comment by photopea** [comment]
It has been fixed now, you can press Ctrl+S as many times as you want, it should never lead to an error!

Thank you very much for your patience and willingness to help me. I think it was a serious problem, which bothered many other users.
