### ISSUE TITLE
Can't run this js code.

### ISSUE THREAD

**Issue by pluto-ZZZZ** [photopea/photopea#6318]
Hello. I find a bug.
I can't run this js code, maybe you haven't implemented "Chnl" yet.

![image](https://github.com/photopea/photopea/assets/54714869/88ede0ac-7eb8-4071-ad23-2faf9d13a0c8)

function step13(enabled, withDialog) {
    if (enabled != undefined && !enabled)
      return;
    var dialogMode = (withDialog ? DialogModes.ALL : DialogModes.NO);
    var desc1 = new ActionDescriptor();
    var ref1 = new ActionReference();
    ref1.putProperty(app.charIDToTypeID('Chnl'), app.stringIDToTypeID("selection"));
    desc1.putReference(app.charIDToTypeID('null'), ref1);
    var ref2 = new ActionReference();
    ref2.putEnumerated(app.charIDToTypeID('Chnl'), app.charIDToTypeID('Chnl'), app.charIDToTypeID('Trsp'));
    desc1.putReference(app.charIDToTypeID('T   '), ref2);
    executeAction(app.stringIDToTypeID('set'), desc1, dialogMode);
  };

**Comment by photopea** [comment]
I tried to run your code in Photopea and I can not see any errors in a web console :( Maybe you are running a different code than what you show us?

![image (2)](https://github.com/photopea/photopea/assets/15955558/408e7452-6e82-4b36-b703-cd37b19a4173)

**Comment by Pt-home** [comment]
Hello! It seems to me that the author of the request should give an example of an attempt to use the function in order to understand the essence of the error

**Comment by pluto-ZZZZ** [comment]
My code is just a case, you need to actively call step13 or use the code like I below, directly delete step13.


var dialogMode = (withDialog ? DialogModes.ALL : DialogModes.NO);
var desc1 = new ActionDescriptor();
var ref1 = new ActionReference();
ref1.putProperty(app.charIDToTypeID('Chnl'), app.stringIDToTypeID("selection"));
desc1.putReference(app.charIDToTypeID('null'), ref1);
var ref2 = new ActionReference();
ref2.putEnumerated(app.charIDToTypeID('Chnl'), app.charIDToTypeID('Chnl'), app.charIDToTypeID('Trsp'));
desc1.putReference(app.charIDToTypeID('T '), ref2);
executeAction(app.stringIDToTypeID('set'), desc1, dialogMode);

**Comment by pluto-ZZZZ** [comment]
@photopea

**Comment by photopea** [comment]
I tried to run your script in Adobe Photoshop, it says "withDialog" is undefined.

I need a script, which runs in Adobe Photoshop, to be able to run it in both Photoshop and Photopea and compare the results.

**Comment by photopea** [comment]
I will close it now, as it all looks very confusing.

When you report a bug related to scripts / actions, please, provide two files: JSX or ATN  and a PSD, so that we can test them in both Photoshop and Photopea, and compare the results.
