### ISSUE TITLE
Cannot go to Google Photos in "Launcher" app only the Google Search is viewed but "Photos" is not empty

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6319]
In Google Photos, is empty. But, in Photos, is viewed.
[Screen recording 2024-01-14 4.41.11 PM.webm](https://github.com/photopea/photopea/assets/154830140/4d61e3da-9c0b-4970-a6b1-010df8fbe2fb)
[Screen recording 2024-01-14 4.41.11 PM(1).webm](https://github.com/photopea/photopea/assets/154830140/e12fc1b1-35cb-41fa-9850-e357973110a2)

**Comment by photopea** [comment]
Hi, how is it related to our website www.photopea.com? We are not Google and we can not change the way Google Photos work :(

**Comment by burnsboyamazing** [comment]
It works!

**Comment by photopea** [comment]
ok

**Comment by burnsboyamazing** [comment]
Fixed!
