### ISSUE TITLE
Create rec shape with a certain size or ratio

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#632]
Right now there's no way to quickly create boxes with certain size or ratio, other than drag out guides for each of them, which is very cumbersome

**Comment by photopea** [comment]
Are these features appropriate for the photo editor? Maybe you should use Figma for what you are trying to achieve.

**Comment by hgs54371** [comment]
Photo with some text box and framing elements is a very basic thing

**Comment by photopea** [comment]
It was added to Rectangle, Ellipse and Custom Shape tool - the same options as for Rectangle selection.
