### ISSUE TITLE
Sometimes app.echoToOE doesn't send the message back to OE

### ISSUE THREAD

**Issue by tempart45** [photopea/photopea#6320]
I'm trying to send some script to execute in Photopea and I get the message sending by app.echoToOE, like in the following example:
```
var r=(function(){})(); app.echoToOE('Hello')
```
However, if the anonymous function return something I don't get the message back to the OE, like in this example:
```
var r=(function(){return 22;})(); app.echoToOE('Hello')
```

**Comment by tempart45** [comment]
Maybe it is cased because you are trying to evaluate a `CallExpression` over a `FunctionExpression` (a function declaration) with the same context, you should create another context to evaluate the function call in order to don't affect to outer context (not only in this case with a `ReturnStatement` also many other side effect (variable declarations, variable modification, ...)).

Once I realize what is the problem, this example could be a possible workaround:
```
a = function(){return 22;}
a()
```
Because in this case `CallExpression` is not a `FunctionExpression` is a simple `Identifier` to resolve and in this case you clone the context to evaluate the function.

**Comment by photopea** [comment]
it should be fixed now, thanks for reporting it! :)
