### ISSUE TITLE
 unable to log in to onedrive

### ISSUE THREAD

**Issue by kotte1982** [photopea/photopea#6321]
Your Operating System: Win 10 Pro
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:
Yes
**This must be done to see the problem**
1. Go to www.photopea.com
2. ....login to Onedrive
3. ....unable to log in to onedrive
The authorization in the Microsoft account has been set
4. ....

**Comment by camoody1** [comment]
@kotte1982 Can you log into OneDrive outside of Photopea? I just tried logging into OneDrive from within Photopea and it worked successfully for me. I am on Windows 11 Pro using Microsoft Edge.

**Comment by kotte1982** [comment]
@camoody1 I can log into OneDrive outside of Photopea, but there's a loop when I'm not in Photopea. I tried all browsers (Mozilla, Edge, Chrome) but without success.
![image](https://github.com/photopea/photopea/assets/156641542/d90a8228-ca76-4dc9-9207-50a7351d713b)

**Comment by kotte1982** [comment]
Hello, thank you. It works now, the problem was the Sophos hardware firewall.
