### ISSUE TITLE
Design changing when exporting as SVG

### ISSUE THREAD

**Issue by tarek171** [photopea/photopea#6322]
Your Operating System:Windows 11
Your Web Browser:Chrome
The problem happens in the Incognito Mode, too: Yes

![svg save bug](https://github.com/photopea/photopea/assets/124294403/b1bffad1-a2ca-4749-8554-3e89b98de568)

**This must be done to see the problem**
1. Go to www.photopea.com
2. I created a logo design using multiple shape layers. I also used a vector mask on the folder containing the shapes.
3. As shown in the screenshot attached, when I try to export as SVG, some areas which are covered by the vector mask do show (blue area). If I try to export as PNG, everything is good. There is no raster layers in the file.

**Comment by photopea** [comment]
Could you share a PSD file here, which looks different after exporting to SVG in Photopea?

**Comment by tarek171** [comment]
I am getting blue areas in the SVG file which should not appear. I am not referring to the cut edges, but to the main design.
________________________________

**Comment by tarek171** [comment]
I uploaded a compressed zip file of the psd file because the size was big. Please let me know if you got it.

**Comment by photopea** [comment]
I did not receive any file :( Please, go to the website https://github.com/photopea/photopea/issues/6322 and reply there, or send your file to support@photopea.com

**Comment by photopea** [comment]
I have received your file!

The vector drawing mechanism of PSD files and SVG files is quite different. E.g. in SVG, there is no "Subtract" operation.

Could you try to merge the shape components of your vector mask? See https://youtu.be/seCm_xgKXF8?t=66

Or maybe use www.vectorpea.com for this purpose (it has no Subtract mode).

**Comment by photopea** [comment]
Update: your vector mask has 4434 points. Photopea did automatic "merge shape components" when exporting the SVG, if there were less than 2000 points (otherwise, exporting the SVG could take 10, 20 or more seconds).

I have increased the limit to 5000 points, so it should export a correct graphics now.

**Comment by photopea** [comment]
but in general, I recommend using www.vectorpea.com for this kind of work.
