### ISSUE TITLE
load JPG but open as PSD

### ISSUE THREAD

**Issue by ducarmotor330** [photopea/photopea#6323]
When I load the photo as .JPG format but open in Photopea was .PSD. before not like this. pls solve this problem. thanks.

**Comment by photopea** [comment]
Hi,

what do you mean? What should I do to see the problem?

Ivan

**Comment by ducarmotor330** [comment]
Hi,
Very glad to get your reply . I mean is that when you load one picture as
JPG into photopea . But the loaded as PSD not the JPG in the photopea. Do
you know why

Photopea ***@***.***>于2024年1月15日 周一18:47写道：

**Comment by ducarmotor330** [comment]
Hi
I can show you the picture it's better to know what I mean.
[image: image.png]
[image: image.png]

Mark Zou ***@***.***> 于2024年1月15日周一 18:55写道：

**Comment by photopea** [comment]
I can not see any pictures. Do you reply by sending emails? To what email address do you send emails? Is it [support@photopea.com](mailto:support@photopea.com) ?

Could you open https://github.com/photopea/photopea/issues/6323 in your web browser and reply there?

**Comment by ducarmotor330** [comment]
ok, I send it to your emails. please check again. thanks.

Photopea ***@***.***> 于2024年1月15日周一 19:24写道：

**Comment by ducarmotor330** [comment]
[123.pdf](https://github.com/photopea/photopea/files/13938360/123.pdf)

**Comment by camoody1** [comment]
Anything opened in Photopea will be opened as PSD. This is how you're able to add layers and other such things to a project. You should make whatever changes you want and then you can either save the PSD file so that you can come back to it later and make additional changes, or you can choose  File -> Export As and select what type of file you want it export as... in your case, it sounds like you would want to choose JPG.

**Comment by ducarmotor330** [comment]
> Anything opened in Photopea will be opened as PSD. This is how you're able to add layers and other such things to a project. You should make whatever changes you want and then you can either save the PSD file so that you can come back to it later and make additional changes, or you can choose File -> Export As and select what type of file you want it export as... in your case, it sounds like you would want to choose JPG.

But before if I opened .JPG in Photopea will be opened as .JPG. when you change the way???

**Comment by photopea** [comment]
If you open any file in Photopea, it is always converted to a PSD. It has always worked like this. Otherwise, you would not be able to add layers, etc.
