### ISSUE TITLE
Feature suggestion : Simple Custome Key Binding 

### ISSUE THREAD

**Issue by Lapis101** [photopea/photopea#6324]
Hi, I love using Photopea and I use it a lot. 

Can you add a feature in keyboard shortcut tab that when double click, it can set the hotkey to new key ? , only for simple and common one like 

step forward, step backward, and free transform

**Comment by photopea** [comment]
I think it is better to have the same shortcut for everyone. Then, we can crate tutorials and manuals and mention specific shortcuts.

Which shortcut would you like to change? Are you sure that shortcut is not used for something else?

**Comment by photopea** [comment]
I have to close it because of lack of details.
