### ISSUE TITLE
[BUG] Can't enable webGL on firefox with big files

### ISSUE THREAD

**Issue by lucastucious** [photopea/photopea#6326]
Your Operating System: Windows 10
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Load a big file (like 1Go)
3. Incredibly laggy and webGL deactivated

**Comment by photopea** [comment]
I think your WebGL can handle textures of up to 16384 pixels wide or high. When you want to work with larger layers in Photopea, WebGL is deactivated automatically.

You can look here: https://webglreport.com/ - "Max Texture Size"

**Comment by lucastucious** [comment]
Any way to have good performance on 300dpi files ?

**Comment by photopea** [comment]
If you work with vector graphics, try www.vectorpea.com

**Comment by photopea** [comment]
I will close it now.
