### ISSUE TITLE
Feature request: Disable Shortcut Hijack, Switch Browser Tab via CMD+1,2,3,... 

### ISSUE THREAD

**Issue by michaelwitk** [photopea/photopea#6327]
love your tool, thanks!

```js
 const getAllEventListeners = () => {
        const elements = Array.from(document.querySelectorAll('*')).concat(document, window);
        const eventListeners = [];
        const getListeners = (element) => {
            const listeners = getEventListeners(element);
            if (listeners) {
                Object.keys(listeners).forEach((eventType) => {
                    listeners[eventType].forEach((listener) => {
                        eventListeners.push({
                            element: element,
                            type: eventType,
                            listener: listener.listener,
                            options: listener.options,
                            useCapture: listener.useCapture
                        });
                    });
                });
            }
        };

        elements.forEach((element) => {
            getListeners(element);
        });

        return eventListeners;
    };

    const eventListeners = getAllEventListeners();
    eventListeners.forEach(({ element, type, listener, useCapture }) => {
        element.removeEventListener(type, listener, useCapture);
    });


    console.log("disabled all successfully")
```

cant run this with tampermonkey sadly, but would work by pasting into console directly

**Comment by photopea** [comment]
Hi, are we trying to solve some problem? What problem?

**Comment by michaelwitk** [comment]
It won't let me change tabs. It won't leave me leave your website (and keep it open)

Windows: ctrl+1 goes to tab1 in browser, ctrl+2 goes to tab2

With photopea it will never let me go to tab1 or tab2 if its on tab3. I know, not every uses their computers shortcuts, but would be nice to disable this somehow

**Comment by photopea** [comment]
We need these shortcuts in Photopea, so this is the expected behaviour: https://helpx.adobe.com/photoshop/using/default-keyboard-shortcuts.html#:~:text=Select%20individual%20channels

In 10 years of our existence, nobody reported it. It is the other way around - people want Photopea use more shortcuts and prevent the default browser shortcuts, e.g. https://twitter.com/photopeacom/status/1668729100528230402

**Comment by michaelwitk** [comment]
I understand. Do you have a dirty solution for me? Browser extension did not work due to `getEventListeners` being a console-api that's not available in the context of tampermonkey for example

**Comment by photopea** [comment]
I wanted to recommend you make a browser extension. Your extension can replace the "addEventListener" or other DOM methods, and add the listener only when it is not for this event.

**Comment by michaelwitk** [comment]
for anyone googling this, just do this in tampermonkey`window. addEventListener = () => {}`
good enough, how didn't i think of this myself 😄 
thank you!

**Comment by photopea** [comment]
If you just do window.addEventListener = () => {} , I think you will break many other features.

**Comment by photopea** [comment]
So you are probably going to report many other bugs in the future, for us to find out they are all caused by your browser extensions :D
