### ISSUE TITLE
I have broken canvas (an empty canvas initiated with some noise) on the latest Chrome.

### ISSUE THREAD

**Issue by ProgrammingLife** [photopea/photopea#6328]
Your Operating System: Arch Linux is up-to-date
Your Web Browser: Google Chrome: Version 120.0.6099.129 (Official Build) (64-bit)
The problem happens in the Incognito Mode, too: Yes (no plugins activated)

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create new empty a white colored canvas with a size: 100x100
3. ![photopea_bug0](https://github.com/photopea/photopea/assets/12764670/774ad1f4-a13a-43a5-943d-990e8cdb6bb4)

There's some noise from a nearest areas but the canvas is pure white and clear. If I move my cursor the contents changes to some another noise parts of the screen.

All worked fine with the browser until 2 days ago with this version of a browser. Maybe some driver has updated. 
In my GoogleChrome I have standart privacy protection.

VectorPea doesn't have this bug! All works fine.
Chromium Version 120.0.6099.216 (Official Build) Arch Linux (64-bit) - also doesn't have this bug even with PhotoPea. 

What can I check in my browser settings?

**Comment by photopea** [comment]
Hi, I did your two steps, but I can not see that pixelated arrow in the middle of the image :( Do you really see that arrow?

**Comment by photopea** [comment]
Cool, it was probably a problem with the GPU. You can disable the GPU acceleration using More - Use WebGL.
