### ISSUE TITLE
Cannot export to pdf in smaller size then default (2480 x 3508)

### ISSUE THREAD

**Issue by orange109** [photopea/photopea#633]
Hello

I imported a psd file that was initially created elsewhere (i think photoshop)

I want to export it in A4 page ratio but way smaller then 2480x3508 .. when trying to make it smaller , in fact i get the same document size.

Please fix

**Comment by photopea** [comment]
Hi, you should do it in Image - Image Size, set a different image size. Then save it as PDF.
