### ISSUE TITLE
Ram error, laggy on i9 128gb ram, 3T ssd, 4090, Win 11 system

### ISSUE THREAD

**Issue by Bladed3d** [photopea/photopea#6330]
I am creating 12,000x17000 200 dpi images for poster prints. Most software uses ram disks so that when memory runs out, they use the ram disk to add any needed memory. Editing this size file on Photoshop is easy and fast.

I have tried editing online using Chrome incognito mode. I have installed the Photopea app to run locally as well. But in every case, I get very laggy interaction and out of memory errors. I tried to load a 2.6gb psd made in Photoshop, but it would not load in Photopea.

Does Photopea use ram disks (which are nearly as fast as ram on an ssd)? Is there a way to have files larger than 4gb? Is there a way to use Photopea on large print images or does it simply not work? Any difference between browser app and installed app?

Thanks

**Comment by photopea** [comment]
There is no difference between the browser app and the installed app. Both of them work equally by displaying a website through the web browser engine.
Photopea does not use a hard drive when the RAM runs out. Actually, websites have no way to know how much free RAM is left. I think the operating system should do the memory virtualization and extend the RAM by paging on the hard drive.

Another limitation is, that Photopea tries to render everything on the GPU, so if you have only 2 GB of the GPU RAM, it will crash, no matter how much regular RAM you have. Often, the integrated GPU uses the main RAM as a GPU RAM.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
