### ISSUE TITLE
CJK Font - Source Han Sans SC not rendered in Simplified Chinese

### ISSUE THREAD

**Issue by zypA13510** [photopea/photopea#6331]
Your Operating System: Windows 11 22H2 22621.3007
Your Web Browser: Microsoft Edge 120.0.2210.133 (Official build) (64-bit) 
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new project
3. Use the Type Tool, set font to "Source Han Sans SC"
4. Paste in the text: 复归门关

Expected behaviour:
Unified CJK codepoints should be rendered using Simplified Chinese glyphs (the SC in font name stands for Simplified Chinese).

Actual behaviour:
It is rendered using a mix of JP and SC glyphs, with JP being the default.

Not sure if related, the default language of both Windows and Edge are set to English.

For comparison:
![A comparison of 复归门关 in Source Han Serif SC/K/JP and Source Han Sans SC](https://runianlee.github.io/2019/02/26/Chinese-character-with-CJK-font/4.jpeg)

**Comment by photopea** [comment]
thanks, it is fixed now.
