### ISSUE TITLE
photopea broke the psd file

### ISSUE THREAD

**Issue by kipitok99** [photopea/photopea#6332]
Your Operating System: Windows 10
Your Web Browser: Yandex
Photoshop 25
Photopea is in the alpha stage?

![Photoshop_nH1HmjiZkr](https://github.com/photopea/photopea/assets/156551317/5cdb9366-d69b-4c30-8ec6-5ec411d7b350)
https://drive.google.com/file/d/1PKLTCWCSV7sxeA-4WvAJjJgg8xXdrLkh/view?usp=drive_link

**Comment by kipitok99** [comment]
> Your Operating System: Windows 10 Your Web Browser: Yandex Photoshop 25.0
Is it in the alpha stage?
> 
> ![Photoshop_nH1HmjiZkr](https://private-user-images.githubusercontent.com/156551317/297401952-5cdb9366-d69b-4c30-8ec6-5ec411d7b350.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MDAzMTYsIm5iZiI6MTcwNTUwMDAxNiwicGF0aCI6Ii8xNTY1NTEzMTcvMjk3NDAxOTUyLTVjZGI5MzY2LWQ2OWItNGMzMC04ZWM2LTVlYzQxMWQ3YjM1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QxNDAwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTQxMTI1OWY5MGUyZDQ3NGI2YzAwYjE5YzEyYjBkZDVhYmY3ZjAzNDRlMmJkMmZiNzMyODhlZDJlZTRkOWNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LLM6VubRI6XbTz-4xKpmCtJVpED5s2FRKndNcY6pR0Y) https://drive.google.com/file/d/1PKLTCWCSV7sxeA-4WvAJjJgg8xXdrLkh/view?usp=drive_link

**Comment by photopea** [comment]
Hi, I am very sorry, it should be fixed now. Just open your PSD in Photopea and save it back as a PSD.

**Comment by kipitok99** [comment]
That trick doesn't work.

**Comment by photopea** [comment]
Your browser is probably showing you the old version of Photopea from an hour ago. To see and use the current version, clear the cache, or open Photopea on a different device, or in the incognito mode.
