### ISSUE TITLE
poly lasso tool doesnt work for me anymore the other lassos do work still 

### ISSUE THREAD

**Issue by frostybicep** [photopea/photopea#6333]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Please, write down a report and specify the details that we ask for. There is 1 million people using Photopea wevery day, and nobody reported any such thing.

**Comment by frostybicep** [comment]
I go to use the the poly lasso and it copy pastes the whole image but only
part of the image  and then the second time i try to use it it does select
anything , this glitch only started happening to me since yesterday , maybe
others will report it soon

**Comment by photopea** [comment]
Could you tell us this
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**Comment by frostybicep** [comment]
im using brave as the browser for it

**Comment by photopea** [comment]
maybe try it in a different browser. Maybe Brave thinks that you are drawing the ad with a polygonal lasso, and brave always tries to remove ads using various crazy methods.
