### ISSUE TITLE
I'm having trouble to download app

### ISSUE THREAD

**Issue by mustafaay92** [photopea/photopea#6334]
it says download app but I can not download on this section

**Comment by photopea** [comment]
Where does it say "download app"?

**Comment by camoody1** [comment]
It doesn't say, "Download"... it says "Install". Photopea is a web application and you can install it as a web app using your browser. It does not "install" in the traditional sense.

**Comment by mustafaay92** [comment]
![Ekran Resmi 2024-01-18 12 07 22](https://github.com/photopea/photopea/assets/157006234/17f166d7-4a8e-420f-a486-fbeafd5ddc1a)
Please check screenshot I can not download or install thats the problem

**Comment by photopea** [comment]
Look into "about://apps", maybe it is already installed on your computer.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
