### ISSUE TITLE
when i open the filter galery, photopea instantly freezes then suddenly unfreezes with the filter galery closed resulting in no way to use the filters

### ISSUE THREAD

**Issue by jayminggrandpa** [photopea/photopea#6338]
Your Operating System: windows
Your Web Browser: photopea aplication

**This must be done to see the problem**
1. Go to www.photopea.com
2.  open a project
3.  select anything
4.  open filter galery

**Comment by camoody1** [comment]
I use Photopea on my Windows 11 PC and I'm not having any trouble with the Filter Gallery. Perhaps try the steps listed here and see if they help:
https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

Beyond this, does the problem happen with every project you open? What about a fresh, blank project?

**Comment by photopea** [comment]
I can not make the Filter Gallery freeze either :( Are you sure it happens for multiple different projects, with different sizes?

The initial filter (Glowing Edges) is quite hard to compute, so if your phone is not very powerful, and your photo is large (20 megapixel), it can freeze the website for a while.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
