### ISSUE TITLE
(Suggestion) The ability to copy individual gradients to use on other layer styles

### ISSUE THREAD

**Issue by MesaBlack** [photopea/photopea#6339]
![image](https://github.com/photopea/photopea/assets/132141735/a250fb94-57bd-4409-b6ca-3ed97a6c1de3)
Taken as of right now (There'd be a copy gradient button)

**Comment by photopea** [comment]
Do you know that each Gradient Selector Button has a tiny arrow, which opens the Gradient Gallery?

You can add the current gradient to a gallery by clicking "Define New". It works the same for brushes, patterns, etc.

![image (1)](https://github.com/photopea/photopea/assets/15955558/19f30b8b-1e5a-429f-8a30-d3fe5afbc29b)

**Comment by photopea** [comment]
I have to close it because of lack of details :(
