### ISSUE TITLE
drag in a picture to a existing project, the picture will be deformed.

### ISSUE THREAD

**Issue by kevincao8828** [photopea/photopea#6340]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Drag first image in to the software, the picture will be fine.
3. Drag the second image into the software, it will be deformed. lost it's original width height ratio. the picture will become a lot slimmer.
4. ....
![image](https://github.com/photopea/photopea/assets/15197981/5e34c2dd-dbbf-475d-a9aa-25452abda8eb)

**Comment by kevincao8828** [comment]
I recalled it did not show this problem last week. It showed today. I think it might be a bug

**Comment by photopea** [comment]
I am very sorry, it should be fixed now. Clear your cookies.
