### ISSUE TITLE
[BUG] Placed SmartObject is stretched if SmartObject document background is transparent

### ISSUE THREAD

**Issue by lucadalli** [photopea/photopea#6341]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode: Yes

**This must be done to see the problem**
1. Visit www.photopea.com/#iS9l2mw-w
2. Observe that car graphic from "Design" SmartObject is stretched to fill entire background space
3. Exact same PSD but with a white background added to "Design" SmartObject: www.photopea.com/#iCx6sdX6H
4. Observe that car graphic is not stretched

**Transparent bg:**
![bug-1](https://github.com/photopea/photopea/assets/39853447/e38c1e36-7272-4876-955f-cd39c348735a)

**White bg:**
![bug-2](https://github.com/photopea/photopea/assets/39853447/69b0785c-2ae3-43ff-9e7c-4b8e87bd79b4)

**Comment by photopea** [comment]
I am very sorry, it should be fixed now. Just open and re-save the smart object.

It happened only when the Smart object had a Warp, so I did not notice it before.
