### ISSUE TITLE
Photopea is not working in iframe from local file

### ISSUE THREAD

**Issue by miroljub1995** [photopea/photopea#6345]
Your Operating System: tested on Linux and Window
Your Web Browser: Google Chrome 120.0.6099.224
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Create file `test.html`
2. Save the following content in it: 
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Wrapper page</title>
  </head>
  <body>
    <iframe id="frame" src="https://www.photopea.com" title="Photopea" style="height: 90vh; width: 90vw;"></iframe>
  </body>
</html>

```
3. Open file in browser (like double click, not served from server)
4. Photopea is stuck on Loading

**Comment by photopea** [comment]
We started to require the document.referrer attribute when PP is in an iframe (referrer should not be empty).

I thikn Chrome does not tell us your referrer, because Is your local web server is HTTP, while Photopea is HTTPS.

It works here: https://jsfiddle.net/bhav9op1/

**Comment by miroljub1995** [comment]
We start it from file, not from http, nor from https

**Comment by photopea** [comment]
I dont know if I should offer Photopea this way. You can make money using our API, but I can not monetize it in any way :(

**Comment by PCRacer** [comment]
Hi,

I am getting the same error, with or without the referrer tag attached...

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Wrapper page</title>
  </head>
  <body>
    <iframe id="frame" src="https://www.photopea.com" title="Photopea" style="height: 90vh; width: 90vw;"></iframe>
  </body>
</html>

Does not work even with a clean and open Iframe!

**Comment by photopea** [comment]
@PCRacer do you use Firefox? There is a bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1876093

**Comment by PCRacer** [comment]
I tested the script on FireFox, Edge, and NetSurfer...

They all keep showing the loading dialog and then freezes.

Its not working on any browser I try.

**Comment by PCRacer** [comment]
It seems to be working now... I don't know why...

**Comment by photopea** [comment]
Could you send me a link to your webpage with Photopea, so that I can see it myself?

**Comment by PCRacer** [comment]
Here is the link:

https://desktop.ssuiteoffice.com/

PhotoPea is listed on the dock/taskbar... it's the fourth tool button from the left, it has the PhotoPea icon.

**Comment by photopea** [comment]
Is it your website? I think Photopea can not see the referrer, because you wrote referrerpolicy="no-referrer"

![image (3)](https://github.com/photopea/photopea/assets/15955558/7f4c9792-cc18-4204-8392-e90631dda5f3)

**Comment by PCRacer** [comment]
I tested it with and without the tags and it kept giving me the same error!

It doesn't matter if the tag reads "no-refferrer" or has an empty element, it kept giving the same error.

But as I wrote before, it now runs and loads images as normal, and is working just fine for me now. Maybe it just took some time for the server to catch up with the new changes that you made.

**Comment by photopea** [comment]
Could you remove the referrer tag and let me look at it?

I just decided to allow using Photopea to those who hide the referrer half an hour ago. But I am planning to introduce it again in the future.

**Comment by PCRacer** [comment]
I just updated the app, clear your cache history in your browser and reload the site. It now runs perfectly.
