### ISSUE TITLE
Avif & jpegXL image support.

### ISSUE THREAD

**Issue by sugoidesune** [photopea/photopea#6349]
Would be great to be able to export to Avif & jpegXL image format as theyre better than webp and and have good browser support.

thank you

**Comment by photopea** [comment]
You can save AVIF and JPG-XL using our plugin: Window - Plugins

**Comment by photopea** [comment]
Photopea can already open AVIF and JPEG-XL "natively" using File - Open.

We will add export when these formats become more popular.
