### ISSUE TITLE
Black & white adjustment under image menu mess up image when first added

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#635]
A rainbow image will turn into a grey mush when added instead of staying at it's original tonal value waiting for adjustments

Detail showed in video
[b&w test.mp4.zip](https://github.com/photopea/photopea/files/1891764/b.w.test.mp4.zip)

**Comment by photopea** [comment]
I think it was related to the previous bug and it is fixed now.

**Comment by hgs54371** [comment]
The luminance of each hue is still shifted quite a bit instead of stay at original

**Comment by photopea** [comment]
Do you mean the value 50 of each CMYK channel? This is the default value.

**Comment by hgs54371** [comment]
For example yellow become very dark, it would be better for them to stay at their original when first added

**Comment by photopea** [comment]
It should behave similar to the Photoshop. I think it is the "obvious" behaviour.

**Comment by hgs54371** [comment]
Have a toggle to switch between keep at original or set all to 50 would be better
