### ISSUE TITLE
Work with Canva.com

### ISSUE THREAD

**Issue by namazix** [photopea/photopea#6350]
hello dear PhotoPea developer
Canva.com uses many 3rd-party apps and Online Tools inside it's editing tools you can add your app also there.
in case if you add there it means PhotoPea will be premium negotiate price with Canva developer team, 
DO NOT LOSE THIS OPPORTUNITY.

**Comment by Jabir-A-H** [comment]
Or the ability to convert Canva design to PSD format for further editing. It would be cool. Like an option where we put the Canva desing link and photopea will open it as editable and we can later save it in any format including PSDs.

**Comment by Jabir-A-H** [comment]
The thing is that Canva doesn't have designs in any particular format. All Canva designs are stored on their servers. And if you want to download the design, you get some formats like JPG, PNG, PDF, SVG, MP4, GIF - none of which are editable to my knowledge.
There only canva thing, which is editable, is the 'public share link' of the designs.
So, being able to import the link directly to photopea would be great.

**Comment by photopea** [comment]
I never used Canva. Could you show me what such a link looks like? I want to look at that link first.

**Comment by Jabir-A-H** [comment]
https://www.canva.com/design/DAF62ZxBvtA/UPs2lNTY3HUgEKz3itUvEw/edit?utm_content=DAF62ZxBvtA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

Here's a slightly changed version of a very basic design I made recently. I set it as anyone can edit, but everyone else except devs, be nice with the design.

**Comment by namazix** [comment]
you have to contact with Canva developers<<<Or the ability to convert Canva design to PSD format for further editing. It would be cool. Like an option where we put the Canva desing link and photopea will open it as editable and we can later save it in any format including PSDs. >>>

**Comment by namazix** [comment]
dear PhotoPea developer Canva will use PhotoPea online just with pop-up or editing area, i am looking for a way to edit canva photos with wide tools like photoshop. 
mt idea:
i will upload my photo in canva in a design
then for edit tools i will choose Photopea then the picture will open in photopea then i will edit then i will save and the photo in canva will be updated. 

no need extra action to download then use photopea then save then upload edited photo to canva again. i am a designer i am looking for ways to save times

**Comment by Jabir-A-H** [comment]
> you have to contact with Canva developers for this issue : Or the ability to convert Canva design to PSD format for further editing. It would be cool. Like an option where we put the Canva desing link and photopea will open it as editable and we can later save it in any format including PSDs.

I see... Well okay I guess. But is there nothing that can be done in this side?

**Comment by namazix** [comment]
> > you have to contact with Canva developers for this issue : Or the ability to convert Canva design to PSD format for further editing. It would be cool. Like an option where we put the Canva desing link and photopea will open it as editable and we can later save it in any format including PSDs.
> 
> I see... Well okay I guess. But is there nothing that can be done in this side?

you can download the design in canva as pdf print then it will be fully editable for Adobe illustrator and Photoshop
Also PSD means PhotoShop Document so it has copyright of saving it or modifing it i think

**Comment by photopea** [comment]
I am afraid having a link to Canva design is not enough. That is like asking us to let you insert a link to a Netflix movie, and allow you to edit that movie (video) in Photopea.

**Comment by namazix** [comment]
> I am afraid having a link to a "Canva document" is not enough. That is like asking us to let you insert a link to a Netflix movie, and allow you to edit that movie (video) in PhotoPea.

this Canva link is a full access to edit this design if you have account in Canva.
if its complicated for you to find out maybe i have to ask Canva team to integrate photo edit with PhotoPea.

**Comment by photopea** [comment]
Yes, I would be glad if you ask Canva to integrate Photopea.

**Comment by emmadeeofficial** [comment]
Looking forward to this integration

**Comment by photopea** [comment]
According to our research, Canva does not allow running another editor as a plugin :( 

On the other hand, Figma allows it: https://www.figma.com/community/plugin/1164118094004004837/photopea

Maybe try to ask Canva to allow advanced plugins: https://twitter.com/canva
