### ISSUE TITLE
Screen usage

### ISSUE THREAD

**Issue by klwemu** [photopea/photopea#6351]
Your Operating System: W11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Y

On my screen the witdth is not fully used.  I use a 1920x1200 px resolution.
![image](https://github.com/photopea/photopea/assets/3965097/de202070-c912-4022-b276-be61c9e8ff80)

**Comment by photopea** [comment]
Hi, there should be ads on the right side of the screen. Do you use any ad blockers?

**Comment by funing36** [comment]
I think you have to get the subscription to get the full screen width.

**Comment by klwemu** [comment]
Thx, yes that is probably the reason.

It's a very nice and powerful app - compared to Krita or Gimp, it's easier
for me to use. I'm a very minimal user, just optimizing some of my summer
vacation pictures. But it's probably too expensive for my use case. $60
would be fine, but not annually. Sad to say.

Best regards
klwemu
