### ISSUE TITLE
export 2 layers with data set (variables)

### ISSUE THREAD

**Issue by jimmywarting** [photopea/photopea#6353]
I'm trying to save a front and a back cover.
but i'm also including a csv with bunch of variables.
i'm wishing for a solution to combine "export all layers" with "export all items" from a data set

if it could be done with scripting that would be fine too.

**Comment by photopea** [comment]
Hi, what do you mean by that? Does any software have such a feature?

**Comment by jimmywarting** [comment]
In here you can export each csv row as one image.
![image](https://github.com/photopea/photopea/assets/1148376/ec1c3f1e-a1b3-4ef2-aa4d-053386088575)

but i have one csv row for both a back and a front cover, so i got two layers i want to export.
an other option is to use the export layers (starting with `-e-`

![image](https://github.com/photopea/photopea/assets/1148376/612c7ccf-9c73-423f-937d-1ee53b6240b5)

but there seems to be no solution to do both at the same time. 

this is my layers
![image](https://github.com/photopea/photopea/assets/1148376/f6960edf-b943-4b5e-bfa8-3b5139a8474d)

so when i do export i want to have
- front-1.png
- back-1.png
- front-2.png
- back-2.png
- etc

i have found a smarter / faster way to achieve this. 
do you have any solution?

I have been embedding your website into my own domain with a iframe, and i'm doing some postMessaging stuff with importing a psd and experimenting with the scripting api. so if there is any automated script that i can send to the application to possible to all of this with scripting than that is fine too.

in that case i would have to do some kind of psudo code like:

```js
dataSet.forEach(row => {
  preview(row)

  // export front
  hide_back_layer()
  show_front_layer()
  exportAs('png') // send front cover to parent window

  // export back
  hide_front_layer()
  show_back_layer()
  exportAs('png') // send back cover to parent window
})
```

**Comment by photopea** [comment]
Maybe you can have a folder of layers "Front" and a folder of layers "Back" on top of each other.

Each line of CSV must still refer to one image. In half of your CSV, set the visibility of "Front" to true, "Back" to false, and in the other half, set "Front" to false and "Back" to true.

**Comment by jimmywarting** [comment]
I have tough about that, but that would essentially mean that the csv would have to be 2x as large. and every row would kind of have to be duplicated and make it more complex for the end user.

is it possible to programmatically set a dataset with code/scripting/postMessaging?
if so, then it would be grate.

**Comment by photopea** [comment]
Sorry, I can not add features, that are needed just by one person :(

You should be able to run Photopea in an iframe and send it scripts to get what you want.

**Comment by jimmywarting** [comment]
> You should be able to run Photopea in an iframe and send it scripts to get what you want.

This is what i'm trying. but it's a bit tricky. a bit tuff to debug when everything is just a proxy object. hard to see what properties/methods exist on an object
I'm a newbe to this hole photoshop area
