### ISSUE TITLE
Error loading ABR files.

### ISSUE THREAD

**Issue by funing36** [photopea/photopea#6354]
Your Operating System: Ubuntu 22.04.3 LTS
Your Web Browser: Fierfox
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Go to your brushes.
3. Upload your .abr file
4. Errors out.

Hello, I tried to upload an .abr file to Photopea so I can have more brushes and every time I uploaded them, It'll think, then error out. I tried 2 different files to no avail.

IDK if it works in chrome, I'ma have to test that later.

Memory: 8GB
Processor: Intel® Celeron(R) CPU @1.60GHz x 2
Graphics: Mesa Intel® HD Graphics 400 (BSW)

**Comment by photopea** [comment]
I just tired it and it seems to work fine. What is "errors out"? What error do you see? Could you share your ABR files with us?

**Comment by photopea** [comment]
I have to close it because of lack of details.
