### ISSUE TITLE
API: Saving to server - how can you identify a specific user?

### ISSUE THREAD

**Issue by fx1234** [photopea/photopea#6356]
Hi,

We would like to use the API for our community.
The user is redirected to Photopea, edits his image and after clicking save, the image is further processed on our server (with PHP). How can we now identify the user (userID) so that we can assign the image to him?

can you pass custom variables when calling the api or what is best practice here?

**Comment by photopea** [comment]
Through the configuration JSON, you can set the server URL, see https://www.photopea.com/api/

you can use a different server URL for each of your users, and append the ID of your user to the end of the server URL.

**Comment by fx1234** [comment]
Ah ok, I understand. Thank you

Maybe it would be an idea to pass custom variables that would then be sent back to the server.

I have another question:
After the user clicks save, how can I redirect them back to my site?

Thank you again

**Comment by photopea** [comment]
Whatever server URL you provide, Photopea will call that server URL exactly as you have written it.

If you use Photopea in an iframe, your "parent website" can delete that iframe or navigate anywhere else. But your server must tell your parent website that the file was saved. Or add a button above the iframe with a label "Go Back".

**Comment by fx1234** [comment]
OK, sad to hear that.

we don't want to use photopea as an iframe. It would be great if you could pass a redirect variable in JSON and the user would be redirected there when he clicked on save

**Comment by photopea** [comment]
Saving can take even a minute or more, depending on the size of your file and the upload speed of your user.

If your webpage opened Photopea in a separate window, I think you can close that tab from your webpage, too.

**Comment by fx1234** [comment]
Our workflow with other online photo editing services is:
- the user clicks on an image on our site that he wants to edit
- the user is redirected to the image editing service
- the user edits his image there and then clicks on save
- the user is redirected back to our site (possibly with a waiting time until the image is saved on our servers)
- the user sees the image displayed on our site

This is the easiest process for our users. This is how it works with the other image editing services. It's a shame that it doesn't work with photopea :( we have thousands of users editing images through our site every day and we want to offer them the same process for all services

**Comment by photopea** [comment]
This workflow is totally doable with Photopea! But the "image editing service" must be your website with Photopea in an iframe. Then, your website can detect when the image is saved, and redirect back.

What exactly is your service? If it is very important, I can add a new feature.

**Comment by photopea** [comment]
But I am still confused ... people often hit Save just to save their work, but they dont want to finish editing yet. What about a special "Save and Leave" button?

**Comment by fx1234** [comment]
We don't want to save any intermediate steps of the editing process on our server, just the final result

A “save and return to example.com” button would be really great. that would fit our workflow perfectly

**Comment by photopea** [comment]
I see, you can do it using the iframe.

**Comment by photopea** [comment]
I can add a new feature, but I must know that it will benefit more than one person. You did not tell me what your website is.

**Comment by photopea** [comment]
You can write me an email to support@photopea.com
