### ISSUE TITLE
Keyboard menu navigation

### ISSUE THREAD

**Issue by ZMYaro** [photopea/photopea#6357]
It would make it much easier to port Photoshop workflows to Photopea if the menus could be navigated by keyboard to more easily select menu items without their own dedicated keyboard shortcuts.  Ideally, this would include:
* The shortcuts to open each menu
* The ability to navigate the menus with the arrow keys and select the highlighted item with <kbd>Enter</kbd>
* The ability to select menu items by their quick access keys

I recognize some shortcuts, such as <kbd>Alt</kbd>+<kbd>F</kbd> for the File menu, would conflict with browser shortcuts when running in a tab, but they could still be made available when Photopea is running in a standalone window (not unlike the UX where <kbd>Ctrl</kbd>+<kbd>N</kbd> only works in a standalone window in Chrome).

**Comment by photopea** [comment]
I am afraid that would be too much work, and there are not that many people looking for this feature :(
