### ISSUE TITLE
Is it possible to implement selecting more than one layer?

### ISSUE THREAD

**Issue by MesaBlack** [photopea/photopea#6358]
![selecting more](https://github.com/photopea/photopea/assets/132141735/e1773b9d-64f3-429f-bede-2495e450c52c)
concept image

rn i have to click every individual path just to replace the color, and it takes more time than this idea.

**Comment by camoody1** [comment]
Just click the first layer in the stack that you want to change, then, while holding the Shift key, click the last layer in the stack you want to change. All of the layers in between will be selected and you change all their fill colors with on click.

If you want to select non-consecutive layers, hold the CTRL key, instead, when selecting.

**Comment by MesaBlack** [comment]
ah
