### ISSUE TITLE
Cant share my project to PSD (photopea.com), just stay in the "Publishing" page forever

### ISSUE THREAD

**Issue by FroustBarba** [photopea/photopea#6359]
Your Operating System: Windows x64
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open the file
3. Try to share the psd link

**Comment by photopea** [comment]
Are you from Turkey? Turkish government is censoring our storage provider.

**Comment by FroustBarba** [comment]
No, from Brazil

**Comment by photopea** [comment]
Can you open https://www.backblaze.com/ ?

Can you publish a small document with just one layer? To make sure you are not publishing a 500 MB PSD.

**Comment by FroustBarba** [comment]
Already tried, not working

**Comment by photopea** [comment]
Can you open https://www.backblaze.com/ ?

**Comment by FroustBarba** [comment]
Its not loading.. Idk why

**Comment by photopea** [comment]
https://www.backblaze.com/ is a regular website. Could you connect to a different wifi? Or ask your internet provider about why they are blocking it. Publishing PSD files will not work if backblaze is blocked. Or you would have to use a VPN.

**Comment by FroustBarba** [comment]
We tried with 4 different computers in 4 different internets.. Still doesnt work... We need the link from the "Share" button to share the psd document... Maybe thats a problem with Brazilian servers?

**Comment by photopea** [comment]
You probably can not open any of our templates, right? https://www.photopea.com/templates/

Our published PSD files are located at https://www.backblaze.com/ . Do you know why you can not open it?

**Comment by FroustBarba** [comment]
Yes, i can open the templates, just the backblaze wesite its not openning. I've a Discord account, if you want to add me and ho throught te problem .froust

**Comment by FroustBarba** [comment]
Backblaze website just opened now

**Comment by photopea** [comment]
If backblaze works, you should be able to publish a PSD.

**Comment by FroustBarba** [comment]
Its not the internet the problem man. I tried wih 4 different computers and 4 different internet connections. All the tools work correctly just the share button isnt working. 
![image](https://github.com/photopea/photopea/assets/137708440/064f2d80-2a09-41e7-8b59-ae0d54281c21)

**Comment by photopea** [comment]
Are you using Photopea at www.photopea.com?

**Comment by camoody1** [comment]
> Its not the internet the problem man. I tried wih 4 different computers and 4 different internet connections. All the tools work correctly just the share button isnt working. Just stays in the Publishing forever.

I know it's frustrating when something isn't working for you and someone else comes along and says, "Well, it's working fine for me!" But I just wanted to insure you that this Share as PSD option is definitely working correctly for "everyone" else. I've used it several times the last couple of days and had others use it, as well, when I was helping them on Facebook and Reddit. Hopefully, Ivan will be able to help figure out whatever is causing your particular issue, but it's important to note that the tool is definitely working correctly at the macro level.
