### ISSUE TITLE
Many Issues, Feature Requests

### ISSUE THREAD

**Issue by blofstedt** [photopea/photopea#636]
I'd be happy to pay for Photopea if you added just a few more features (and worked out the kinks):

1) Support for higher resolution images.

2) Please please pleaaaassseeeee add a trim option. Also, please add an option to assign it to a keyboard key or combination of keys. (ex. In Photoshop I use ctrl+. to trim the white from images, leaving only the subject. It saves tons of time).

3) When you have the crop tool and you click your layer, please set it so the crop tool automatically snaps to the edges of that layer.

4) The quick select tool is broken/very laggy. It selects way outside of the cursor.

5) Please add a "refine edge" tool, allowing for feathering, smoothing, and edge shifting.

Those are my biggest requests. I really want to leave Windows and get a Pixelbook but there are two things stopping me: Photoshop and InDesign. Now that I've found out about Gravit (amazing free InDesign clone online) I just need to find a way to leave Photoshop and Photopea is the closest thing at the moment. I'd be more than happy to pay for Photopea with these features.

**Comment by photopea** [comment]
Hi, thanks for getting in touch here! What do you mean by "higher resolution images"? We tested Photopea with 70 MPx photos and it worked well.

**Comment by blofstedt** [comment]
Oh, perhaps the images I chose were low resolution then. I thought they were higher res, but when I used the feature to grab from the web (which is awesome by the way) they seemed to be much lower resolution than on Google. Perhaps I'm mistaken though.

**Comment by photopea** [comment]
Drag-and-drop from Google Image Search is very "fragile" feature. There is no web standard for doing this. Basically, Photopea gets only the URL of the link, that the dropped item leads to. Then, it loads a HTML page from that link and searches for image URLs in that page. Some webpages contain the same image in multiple resolutions.

It is much better to right-click the image, press Copy Image URL, go to Photopea and press Ctrl+V . This way, Photopea gets the direct URL of the image that you need (not a HTML page of the link).

**Comment by blofstedt** [comment]
About the other features specifically, the refind edge and trim tool with a keyboard shortcut, is that something you'd consider working on? They're absolutely vital to my workflow.

**Comment by photopea** [comment]
Hi, I added the Trim option (both at Image - Trim and as a button in the Crop tool). 

Refine edge is being discussed in another thread: https://github.com/photopea/photopea/issues/272
