### ISSUE TITLE
Path tool duplicates previous path

### ISSUE THREAD

**Issue by clubajax** [photopea/photopea#6361]
Your Operating System: Mac Sonoma
Your Web Browser: Chrome / Web App
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. new document
3. create a new layer
4. create a simple shape with the bezier tool
5. click "Shape" and pick a color (so it can be styled)
6. create a new layer
7.  create a simple shape with the bezier tool
8. click "Shape" and pick a different color

Result: The first shape appears to change to the second color
But when you move the second shape you see the first shape was duplicated

This problem is bad. I'm trying to work around it, but I'm getting countless ghost shapes. Deleting them point by point does get rid of the ghost shape, but create another shape, and there's more ghost shapes.

Am I doing something wrong? I don't remember having to click the Shae button until recently.

![bez-1](https://github.com/photopea/photopea/assets/290747/236ecf0e-e666-4cd7-85de-4104b5634437)
![bez-2](https://github.com/photopea/photopea/assets/290747/aec1e88d-db7b-4136-a890-c3d801453225)
![bez-3](https://github.com/photopea/photopea/assets/290747/f701dfac-eceb-4496-8b6a-42ead4778ab5)

**Comment by photopea** [comment]
Bezier tool - you mean the Pen tool? What mode do you use for drawing? Is it the Path mode or the Shape mode?

Where do you click "Shape" to pick a color?

**Comment by clubajax** [comment]
Yes, Pen tool. Sorry to not be specific.

Oh man, it was the Mode! That was the problem. Now it works as expected when I use "Shape" mode.

I guess whether this issue gets closed or not depends on how the Path Mode is supposed to work. It does create ghost objects as I said, but I might not know the intent of the tool. I guess it's good for creating selections, but it sure doesn't work for creating shapes.

**Comment by photopea** [comment]
We used to have the Shape mode as default, but we switched to the Path mode about a month ago, because some user said that is how it works in Photoshop, and that is what people expect.

**Comment by clubajax** [comment]
So those ghost shapes are as intended?

**Comment by photopea** [comment]
They are not ghost shapes, they are Paths, see https://www.photopea.com/learn/vector-graphics . Or get any book about Adobe Photoshop to learn what it is :)

**Comment by clubajax** [comment]
I've been using Adobe Illustrator and Photoshop since the 90s, no need to get snarky. It looks like a bug to point out, but if you don't care, I don't.

**Comment by photopea** [comment]
What is a bug?

**Comment by camoody1** [comment]
@clubajax Hey man... Is there any chance you could record a short video showing your entire Photopea screen so we can see exactly what you're doing with all your settings? I'm on a Windows PC and I can't recreate what you're seeing following your directions in the first comment. I'm just wondering if we're missing something in your description. Make sure you didn't have something weird happening, like a stuck Command or Option key.

**Comment by clubajax** [comment]
https://github.com/photopea/photopea/assets/290747/19318cd6-96f8-40cb-983e-14196b1adc6b

**Comment by photopea** [comment]
Ok, I see, I made it work like in Photoshop. When you draw a path, and no path is selected, the old content of the Work Path is deleted now.
