### ISSUE TITLE
Cant share my project to PSD (photopea.com), just stay in the "Publishing" page forever

### ISSUE THREAD

**Issue by FroustBarba** [photopea/photopea#6363]
Your Operating System: Windows x64
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

 I tried wih 4 different computers and 4 different internet connections, also tried using a VPN. All the tools work correctly just the share button isnt working. Just stays in the Publishing forever

This must be done to see the problem

Go to [www.photopea.com](http://www.photopea.com/)
Open the file
Try to share the psd link

![image](https://github.com/photopea/photopea/assets/137708440/064f2d80-2a09-41e7-8b59-ae0d54281c21)

**Comment by photopea** [comment]
What website is in your screenshot? Could you share the whole screen, including the website address?

**Comment by FroustBarba** [comment]
![image](https://github.com/photopea/photopea/assets/137708440/7e30e4f7-c121-4138-826b-1b2e5527a7db)
Yes.. I'm using Photopea

**Comment by camoody1** [comment]
Try downloading Microsoft Edge and turning on its built-in free VPN. It's under the Browser Essentials section and labeled as "Microsoft Edge Secure Network". Then try Photopea through Edge. I wonder if you're encountering some weird IP issue.

**Comment by photopea** [comment]
Can you open www.backblaze.com ? If not, publishing a PSD (or opening a PSD link from someone else) will not work.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
