### ISSUE TITLE
Super Slow

### ISSUE THREAD

**Issue by Randolph13** [photopea/photopea#6364]
Why is Photopea so slow? Normally I am able to do a pretty simple edit in less than a minute but the website kept freezing and it took over 15 minutes to complete after multiple attempts and closing the browser it finally worked.  Is this due to the ads on the side?  If I paid for the add free version do you think this would resolve the issue?  

Your Operating System: Windows
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: NA

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Nobody else reported such a problem. Photopea should not be slower than in the past. Of course, some operations can take a lot of time, especially if your device is not powerful enough.

What should I do to see Photopea being slow? What is your Peamark? Press More - Peamark.
