### ISSUE TITLE
Copy Paste Selection Bugging for Mac

### ISSUE THREAD

**Issue by CxryzNFTs** [photopea/photopea#6365]
Your Operating System: macOS 
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open two files so they are in two seperate projects
4. Go to one project, and make a selection then copy
5. Click back to the other project and paste
6. Observe that it pastes the FULL image and not the selection itself

**Comment by photopea** [comment]
I just did what you say, but everything works well in my case :(

Could you record a short video of what you are doing? So many things are not clear. What "projects" did you open? Do they have one or more layers? What layers were selected when you "copy"? How do you do the "copy" (with a shortcut or with Edit- copy)? How do you make a selection?

**Comment by CxryzNFTs** [comment]
Apologies for the delay. Let me share more specifics.

The issue occurs when I copy using the keyboard shortcut "cmd + c", I am using box select to make the selection, and to paste, I do "cmd + v". See the video below that I can copy paste when I don't deselect the object, it works fine. However, when I press "cmd + d" to deselect (I have copied it before I deselected), it does not copy the selection to my clipboard, it just copies the full layer. https://streamable.com/hw84nq

**Comment by CxryzNFTs** [comment]
@photopea In short, the copy paste function is fine until I deselect. Keep in mind I already copied the selection before deselecting so it should have saved the copied selection.

**Comment by photopea** [comment]
Your video has no sound and it is not clear when you press what shortcut :(  Could you use Edit - Copy and Edit - Paste in your video?

Copying without a selection will not copy any image, but it will copy the layers from the Layers panel. These layers can be pasted only back into Photopea.
