### ISSUE TITLE
DESIGN NOT UPLOADING FULLY

### ISSUE THREAD

**Issue by samirali111** [photopea/photopea#6367]
Your Operating System: Windows
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes
![2024-01-30_135831](https://github.com/photopea/photopea/assets/158153977/335e32a5-7c2c-486e-a6bc-6efe25d3b45a)

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
I think this is a bug in your GPU. Is the width or the height of your image bigger than 16,384 pixels? 

Could you try to update your GPU dirvers? If nothing helps, try to disable the GPU acceleration in More - Use WebGL.

**Comment by photopea** [comment]
I have to close it because of no response from the user :( You can still respond, if you have time.

You can fix it by updating your GPU drivers, or disabling the WebGL.
