### ISSUE TITLE
CURSORE CHE NON FA SALIRE E SCENDERE NELLA SEZIONE LIVELLI

### ISSUE THREAD

**Issue by Vgiannelli** [photopea/photopea#6368]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Sorry, I do not understand what is the prloblem :( could you describe it in English? Nobody else reports any problems with Levels.

**Comment by lila569** [comment]
There isn't a horizontal and vertical bars to move the picture when you use a zoom.
Thanks

**Comment by camoody1** [comment]
> There isn't a horizontal and vertical bars to move the picture when you use a zoom. Thanks

Hold the space bar on your keyboard and then left-click and drag the image around the canvas. If you want to zoom in and out easily, hold the ALT key on your keyboard and use your mouse scroll wheel to zoom in and out. 👍🏼

**Comment by photopea** [comment]
That is correct, I think scrolling bars are not needed, as there are many other ways to navigate. E.g. Window - Navigator.
