### ISSUE TITLE
Rectangle select keeps disappearing 

### ISSUE THREAD

**Issue by imjustamansoooo** [photopea/photopea#6369]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open background image
3. Use the select tool to select a part of the image
4. After around using the select tool for more than 4 time, you can't get it back

**Comment by photopea** [comment]
I do not understand :(

2. - what is a "background image"?
3. - what is a "select tool"?
4. - what you can't get back?

**Comment by nwasira** [comment]
he's talking about rectangular marquee tool..

**Comment by nwasira** [comment]
also can you bump my friend's issue, he was out of town for a few days
https://github.com/photopea/photopea/issues/6365 

thx

**Comment by camoody1** [comment]
@imjustamansoooo What exact steps are you taking to cause this issue on your end? I can use the rectangular select tool to draw boxes over and over and over. I'm guessing that's no actually what you're doing to create the problem, though. Please list the exact steps you are taking to cause the issue, or, even better, record a short video of your PC desktop as you're reproducing the issue. Thanks!

**Comment by photopea** [comment]
I have to close it because of no response from the user :( You can still respond, if you have time.
