### ISSUE TITLE
Guides Not Showing/Enter Key/etc.

### ISSUE THREAD

**Issue by blofstedt** [photopea/photopea#637]
When I Import a jpg with guidelines on it (it's a psd file) the guidelines do not show in Photopea. 
Also, please let the user hit the enter key to accept a crop. It's really annoying to have to go to the top and click the checkmark. 
Lastly, in the crop tool, please add an option "contrast" or something similar that would cut a solid background out of an image (say a solid white or black background) leaving the "main subject" only. 
Finally, please enable keyboard shortcuts for tools under "preferences". 

Thanks!

**Comment by photopea** [comment]
Hi! Only PSD files can have guides, not JPGs. Are you sure guides are enabled in View - Guides?

The Enter should work for accepting the Crop. What browser do you have? Can  you update it?

We are going to add the special Trim feature, is that what you need?

What do you mean by "tools under preferences"?

**Comment by blofstedt** [comment]
Yes, trim as I mentioned in my other post would be very helpful. I just noticed you almost had something similar in the crop tool and I wondered if you shouldn't just put it under the crop tool as a new option called "trim by contrast" or someting that would trim solid color backgrounds. Just an idea. 

The thing about preferences I mean is so I can hit "ctrl+." or whatever I set on my keyboard and it will perform the task I have set to that shortcut. I was thinking you could put this under "preferences" similar to how photoshop is set up. 

I'm using chrome and enter isn't working to accept the crop for some reason... Maybe I'll have to try on another computer.

**Comment by photopea** [comment]
Please, go here: http://jsfiddle.net/p45f44zb/3/ , click into the bottom right area and Press Enter. What text do you see in the window when you press it?

**Comment by blofstedt** [comment]
I see this: []

**Comment by photopea** [comment]
Do you see anything when you press other keys? What is your OS?

**Comment by blofstedt** [comment]
Yes, if I press other keys, lets say the v key, I see ["v"] and if I press a combination, like v and g I see ["v","g"].
I'm running Windows 10, 64bit.

**Comment by photopea** [comment]
Can you try to confirm the crop again in Photopea with Enter? In Chrome and Edge?

**Comment by blofstedt** [comment]
It's working now. That said, the options at the top "total content, current layer, selection" are not working. When I click them, they resize the crop as they should, but enter doesn't crop.

**Comment by photopea** [comment]
Some people like to switch betwen buttons with Tab, and press the button with Enter. When you press a button now, and then hit Enter, it works like pressing the same button again (that is why nothing happens).

To confirm the cropping, click into a canvas, to "deselect" the button you pressed, and hit Enter.

**Comment by blofstedt** [comment]
Alright. Gotcha. I'm just so used to Photoshop I guess.

**Comment by photopea** [comment]
I will solve the trimming in a previous issue. Is there anything else you would like to solve in this issue?

**Comment by photopea** [comment]
I made Enter work right after you press the button, you don't have to click into the workspace.

**Comment by blofstedt** [comment]
Hey uh... Guides are definitely not working: 

![image](https://user-images.githubusercontent.com/38229215/38577793-289fa4c6-3cbf-11e8-9735-3773ebb6f2c2.png)

That image is a psd file with blue guidelines in Photoshop. Pulling the psd into Photopea, it does not show the guides.

**Comment by blofstedt** [comment]
You guys are fantastic! Thanks so much! Getting very close to a full-on Photoshop replacement! I'm really excited about this. 

Thanks again!

**Comment by blofstedt** [comment]
Hm... I tried with a psd from Photoshop and guides aren't showing. this image (white box) has blue guides in Photoshop. 

![image](https://user-images.githubusercontent.com/38229215/38577955-b39853ac-3cbf-11e8-9167-4bc76ba4b81c.png)

**Comment by photopea** [comment]
Can you send us your PSD with guides to support@photopea.com ?

**Comment by blofstedt** [comment]
I've tried zooming in. I'll email you the psd.

**Comment by blofstedt** [comment]
Is there a way to make guides in Photopea? That would work too.

**Comment by blofstedt** [comment]
No worries, I used the tool in Photopea to make new guides. 
![image](https://user-images.githubusercontent.com/38229215/38586173-0aa9ce04-3cda-11e8-8cb0-28ac6945dcd8.png)

**Comment by photopea** [comment]
But why do you think there were any guides in your previous PSD? I could not see any guides.
