### ISSUE TITLE
The saved font automatically disappears

### ISSUE THREAD

**Issue by chaien1** [photopea/photopea#6370]
![Screenshot 2024-01-30 4 24 46 PM](https://github.com/photopea/photopea/assets/157555222/e784b903-7f03-450c-a8af-01f8ea2061ae)
Where are all my fonts? I've been using them for almost a year and haven't had that problem. This morning I couldn't see it again. Total loss.

**Comment by photopea** [comment]
Hi, what are "saved fonts"? Did you load TTF / OTF files into Photopea, and told Photopea to keep them in a Local Storage?

Did you clear the website data recently? It also deletes all your Photopea settings, and all other website data, that were saved to your computer by your website.

**Comment by photopea** [comment]
I have to close it because of no response from the user :( You can still respond, if you have time.
