### ISSUE TITLE
I find a new bug about Js action.

### ISSUE THREAD

**Issue by pluto-ZZZZ** [photopea/photopea#6373]
I uploaded a zip file, pressurized password is test, which contains an atn file. When I open it in Photoshop, create a new layer, draw some random patterns, select the new layer and execute this script, the system will work. But when I open this script with photopea and execute it, the system will report an error, as follows. This script is used to set the layer style, it seems that photopea did not make the relevant adaptation.
Thank you for your support.  @photopea 

[bug_report.zip](https://github.com/photopea/photopea/files/14110531/bug_report.zip)
![image](https://github.com/photopea/photopea/assets/54714869/4ee6c3c8-a096-47e5-aa20-7b7dcde35f14)
![image](https://github.com/photopea/photopea/assets/54714869/d4b81a63-ad4e-495c-8f4d-9953818df2b3)
![image](https://github.com/photopea/photopea/assets/54714869/fbb6ade4-acf4-44eb-9ad0-d23f9e47695b)

The details of the error are as follows:
{
    "classID": "Lefx",
    "Scl": {
        "t": "UntF",
        "v": {
            "type": "#Prc",
            "val": 100
        }
    },
    "gagl": {
        "t": "UntF",
        "v": {
            "type": "#Ang",
            "val": 122
        }
    },
    "ebblMulti": {
        "t": "VlLs",
        "v": []
    },
    "frameFXMulti": {
        "t": "VlLs",
        "v": []
    },
    "innerShadowMulti": {
        "t": "VlLs",
        "v": []
    },
    "IrGlMulti": {
        "t": "VlLs",
        "v": []
    },
    "ChFXMulti": {
        "t": "VlLs",
        "v": []
    },
    "solidFillMulti": {
        "t": "VlLs",
        "v": []
    },
    "gradientFillMulti": {
        "t": "VlLs",
        "v": []
    },
    "patternFillMulti": {
        "t": "VlLs",
        "v": []
    },
    "OrGlMulti": {
        "t": "VlLs",
        "v": []
    },
    "dropShadowMulti": {
        "t": "VlLs",
        "v": [
            {
                "t": "Objc",
                "v": {
                    "classID": "DrSh",
                    "enab": {
                        "t": "bool",
                        "v": true
                    },
                    "present": {
                        "t": "bool",
                        "v": true
                    },
                    "showInDialog": {
                        "t": "bool",
                        "v": true
                    },
                    "Md": {
                        "t": "enum",
                        "v": {
                            "BlnM": "Mltp"
                        }
                    },
                    "Clr": {
                        "t": "Objc",
                        "v": {
                            "classID": "RGBC",
                            "Rd": {
                                "t": "doub",
                                "v": 0
                            },
                            "Grn": {
                                "t": "doub",
                                "v": 0
                            },
                            "Bl": {
                                "t": "doub",
                                "v": 0
                            }
                        }
                    },
                    "Opct": {
                        "t": "UntF",
                        "v": {
                            "type": "#Prc",
                            "val": 57
                        }
                    },
                    "uglg": {
                        "t": "bool",
                        "v": true
                    },
                    "lagl": {
                        "t": "UntF",
                        "v": {
                            "type": "#Ang",
                            "val": 90
                        }
                    },
                    "Dstn": {
                        "t": "UntF",
                        "v": {
                            "type": "#Pxl",
                            "val": 5
                        }
                    },
                    "Ckmt": {
                        "t": "UntF",
                        "v": {
                            "type": "#Pxl",
                            "val": 1
                        }
                    },
                    "blur": {
                        "t": "UntF",
                        "v": {
                            "type": "#Pxl",
                            "val": 10
                        }
                    },
                    "Nose": {
                        "t": "UntF",
                        "v": {
                            "type": "#Prc",
                            "val": 0
                        }
                    },
                    "AntA": {
                        "t": "bool",
                        "v": false
                    },
                    "TrnS": {
                        "t": "Objc",
                        "v": {
                            "classID": "ShpC",
                            "Nm": {
                                "t": "TEXT",
                                "v": "线性"
                            }
                        }
                    },
                    "layerConceals": {
                        "t": "bool",
                        "v": true
                    }
                }
            }
        ]
    },
    "St3DMulti": {
        "t": "VlLs",
        "v": []
    },
    "masterFXSwitch": {
        "t": "bool",
        "v": true
    }
}

**Comment by photopea** [comment]
thanks a lot, it should be fixed now.
