### ISSUE TITLE
macOS system shortcuts does not work

### ISSUE THREAD

**Issue by pravdomil** [photopea/photopea#6377]
Safari web app@macOS
incognito mode yes

**How to Reproduce?**
1. open Safari
1. www.photopea.com
1. share
1. add to dock
1. non of these keyboards shortcuts (settings, hide, hide others, quit) works:

<img width="232" alt="image" src="https://github.com/photopea/photopea/assets/2387356/15cafb64-1d42-44e9-8e1c-0b196ef5c6de">

**Comment by photopea** [comment]
What is a step 3 - "share"? Where should I click?

**Comment by pravdomil** [comment]
you can always use help menu to find stuff

<img width="372" alt="image" src="https://github.com/photopea/photopea/assets/2387356/ac8896bf-7f4a-4014-b8c1-bb7ebdd4b099">

...

<img width="121" alt="image" src="https://github.com/photopea/photopea/assets/2387356/60370839-300a-4191-9ac4-331255478b11">

**Comment by photopea** [comment]
I clicked the "Share" button at the top right, and it shows me a menu: https://i.imgur.com/KxXkBDd.png

How do I open the Help menu and what is wrong with it?

You are saying "non of these keyboards shortcuts (settings, hide, hide others, quit) works:", I just tried Command + H and it hid Photopea. Which shortcut is not working?

**Comment by photopea** [comment]
I have MacOS Monterey 12.7.1

Could you please report it again with exact steps, what should I do? Steps for someone who does not use Mac on a daily basis.

**Comment by photopea** [comment]
Our Report Template asks you to mention your operating system and a web browser. It would be nice if you mentioned it. I mean including the version, it could save us a lot of time :D

**Comment by pravdomil** [comment]
you need macOS 14

**Comment by pravdomil** [comment]
> I mean including the version

it says only operating system

not a version

change the template then

and do not laught at me

and I send you link to Apple docs where first sentence says starting macOS Sonoma

![IMG_3186](https://github.com/photopea/photopea/assets/2387356/cbc6835a-6dc9-447f-877f-dc7e7b1245c4)

![IMG_3187](https://github.com/photopea/photopea/assets/2387356/218e2505-4417-48b8-ba06-9cfdcc05b38a)

**Comment by pravdomil** [comment]
> Could you please report it again with exact steps, what should I do?

I give you the exact steps
and said that you have a order version of macOS
which I was right

any you close it as completed?
you really don't care
