### ISSUE TITLE
FONT SIZE IN PHOTOPEA.COM

### ISSUE THREAD

**Issue by janAbdullah** [photopea/photopea#6378]
Your Operating System: Window 10
Your Web Browser: Google Chrom
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....start a new file
4. .... add text box in any layer or background
5. ....no any option for font size to decrease or increase

**Comment by janAbdullah** [comment]
issue in text size in photopea.com

**Comment by photopea** [comment]
I am confused, could you share a screenshot of what is wrong? Please, try it in the Incognito mode first, or disable all your browser extensions before using Photopea. Your extensions can modify Photopea.

**Comment by photopea** [comment]
I have to close it because of no response from the user :( You can still respond, if you have time.
