### ISSUE TITLE
Smart object not updating

### ISSUE THREAD

**Issue by Kylielodge** [photopea/photopea#6379]
Your Operating System: Windows 11
Your Web Browser: FireFox (but also tries in Chrome
The problem happens in the Incognito Mode, too: Video in incognito mode

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open PSD file 
3. Open smart object in top layer
4. File->open and place file
5. CLick tick to accept placement
6. File->save Smart file
7. Close
8. Returns to main file and the jpg added to the smart file isn't visible

https://github.com/photopea/photopea/assets/158636863/48f29bbc-7e58-470a-b3da-dd7c8a2e80b8

**Comment by photopea** [comment]
I tried to do a similar thing, but it works well in my case :( Could you share your original PSD here in a ZIP file?

**Comment by Kylielodge** [comment]
[025A3965 smart object small.zip](https://github.com/photopea/photopea/files/14152558/025A3965.smart.object.small.zip)
Hi this is a smaller version as the original was too big even zipped.
It was made on Photoshop and I have had 3 clients saying they don't work in Photopea in the last month. Not had a problem before then. Some seem to work OK and others don't and I can't see any difference between those that work and those that don't.

**Comment by Kylielodge** [comment]
This is a link to the original sized file
https://1drv.ms/u/s!AnTxaVMi-k9UqTVuZbD2ddlgggy2?e=0wGJUe
Others that don't work are
https://1drv.ms/u/s!AnTxaVMi-k9UqUhmR7_vlBsMjGku?e=KicV09
https://1drv.ms/u/s!AnTxaVMi-k9UqVHP3MpYnxBrZA00?e=AoUEq2

**Comment by photopea** [comment]
thanks, it is fixed now :)
