### ISSUE TITLE
Photopea keeps loading and loading

### ISSUE THREAD

**Issue by TomTom5150** [photopea/photopea#638]
Every time I open Photopea it sits on the loading screen. I've been here for a good 10 minutes

**Comment by photopea** [comment]
Hi, this is really weird. Can you disable browser extensions, that could rewrite the content of websites that you visit, and try it again? Or try it in anonymous window?

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by TomTom5150** [comment]
I don't have the problem Btw
