### ISSUE TITLE
pen tool

### ISSUE THREAD

**Issue by bhuvaneshwar09041999** [photopea/photopea#6380]
pen tool not  working

**Comment by bhuvaneshwar09041999** [comment]
fix this issue soon

**Comment by photopea** [comment]
the pen tool works for me. What should I do to see it not working?

**Comment by camoody1** [comment]
> the pen tool works for me. What should I do to see it not working?

@photopea If you want to see the Pen Tool not working, I recommend installing numerous browser extensions that take control of your screen as well as multiple adblockers. Good luck!

**Comment by bluep55** [comment]
Nothing wrong with the Pen Tool today, it works fine.
Extensions and ad blockers can prevent Photopea from working correctly. 
Click on the Extensions icon to see what extensions are active and disable any that are causing Photopea problems.
Also disable any adblockers you have.
If you don't see ads on the right hand side of Photopea, then you're using ad blockers and asking for trouble. 
![Extensions](https://github.com/photopea/photopea/assets/118609932/80076874-fa7f-43fb-9b29-9fb21e287648)

**Comment by photopea** [comment]
I have to close it because of no response from the user :( You can still respond, if you have time.

**Comment by photopea** [comment]
I have found a serious bug with a Pen tool, and it should be fixed now.
