### ISSUE TITLE
macOS system shortcuts does not work

### ISSUE THREAD

**Issue by pravdomil** [photopea/photopea#6382]
Safari web app@macOS14
incognito mode yes

**How to Reproduce?**
1. open Safari
1. www.photopea.com
1. share
1. add to dock
1. non of these keyboards shortcuts (settings, hide, hide others, quit) works:

<img width="232" alt="image" src="https://github.com/photopea/photopea/assets/2387356/15cafb64-1d42-44e9-8e1c-0b196ef5c6de">

**Comment by photopea** [comment]
Hi, what is the third step "share"?

**Comment by pravdomil** [comment]
![](https://media.idownloadblog.com/wp-content/uploads/2023/06/Add-to-Dock-in-Safari-on-Mac.jpg)

**Comment by photopea** [comment]
This is not a button in Photopea :( It is a button in Safari, so maybe it is a bug in Safari? Did you ask someone from Safari about it?

What exactly does it do? Did you try to press More - Install Photopea inside Photopea? Maybe they dont show this feature to sites which can do it themselves.

**Comment by pravdomil** [comment]
it installs photopea as standalone app

**Comment by photopea** [comment]
Is it what you wanted? Was it added to your Dock?

**Comment by pravdomil** [comment]
after it is installed none of the keyboards shortcuts works

**Comment by photopea** [comment]
Sorry, MacOS 14 can not be installed on my Macbook Air, so I can not see what you are seeing :( I will try to buy a new macbook with MacOS 14 next week.

**Comment by pravdomil** [comment]
there is nothing to see
just don't `e.preventDefault()`
cmd+q
cmd+h
cmd+alt+h
cmd+,

thats all

**Comment by photopea** [comment]
I am not familiar with keyboard shortcuts on MacOS. But we might need some of these shortcuts inside Photopea.

Did you try any other photo editor besides Photopea? Do your keyboard shortcuts work as you want there?

**Comment by pravdomil** [comment]
this is the standard in EVERY macOS app

try it yourself on your air

**Comment by pravdomil** [comment]
also there is cmd+m to minimalize

also you can test it in macOS 13 using Chrome
it does not work there either

**Comment by photopea** [comment]
Have you tried pressing Command + M in Adobe Photoshop on a Mac? I think it should open Curves, and not minimize anything: https://helpx.adobe.com/photoshop/using/default-keyboard-shortcuts.html#:~:text=Command%20%2B-,M,-Select%20next%20point

**Comment by pravdomil** [comment]
⌘Q quit
⌘H dialog (see below)
⌘⌥H hide others
⌘, toggle layer
⌘M curves!
⌘K preferences
<img width="372" alt="Screenshot 2024-02-06 at 13 22 35" src="https://github.com/photopea/photopea/assets/2387356/19a9fcd0-6f9b-4bb4-880c-7921f02c2273">

<details>
<summary>more screens</summary>
<img width="319" alt="Screenshot 2024-02-06 at 13 18 23" src="https://github.com/photopea/photopea/assets/2387356/8eb58fa0-fd9e-4c99-a53d-1c73be3fd982">
<img width="271" alt="Screenshot 2024-02-06 at 13 18 26" src="https://github.com/photopea/photopea/assets/2387356/ed9195b4-a38e-4651-b41f-518a8ae8b639">
<img width="304" alt="Screenshot 2024-02-06 at 13 18 29" src="https://github.com/photopea/photopea/assets/2387356/2010c739-b4ed-4e8c-b364-b8504b7c6579">
<img width="275" alt="Screenshot 2024-02-06 at 13 18 32" src="https://github.com/photopea/photopea/assets/2387356/72624b89-1af8-48f8-8638-d77f98d5a262">
<img width="270" alt="Screenshot 2024-02-06 at 13 18 35" src="https://github.com/photopea/photopea/assets/2387356/4ddfbbae-80c7-4b7e-aadd-2164c163483e">
<img width="325" alt="Screenshot 2024-02-06 at 13 18 37" src="https://github.com/photopea/photopea/assets/2387356/8054e0d7-61ae-474e-84cf-f584182e3590">
<img width="370" alt="Screenshot 2024-02-06 at 13 18 41" src="https://github.com/photopea/photopea/assets/2387356/3fc7da54-2464-4472-bbc9-a66ca4457d5d">
<img width="312" alt="Screenshot 2024-02-06 at 13 18 44" src="https://github.com/photopea/photopea/assets/2387356/9e2669b1-53f0-4d0d-a725-9aac212a4226">
<img width="316" alt="Screenshot 2024-02-06 at 13 18 51" src="https://github.com/photopea/photopea/assets/2387356/05a97b38-9905-4c90-8770-9301e8db0835">
<img width="406" alt="Screenshot 2024-02-06 at 13 18 59" src="https://github.com/photopea/photopea/assets/2387356/cb662428-e2b6-41bb-9d94-605854f0f24d">
<img width="272" alt="Screenshot 2024-02-06 at 13 18 12" src="https://github.com/photopea/photopea/assets/2387356/4ba20e79-68ca-4c3b-b74a-1fac57929477">
<img width="252" alt="Screenshot 2024-02-06 at 13 18 17" src="https://github.com/photopea/photopea/assets/2387356/b338d102-9d1d-4fed-b177-1f29f15f9ce5">
<img width="325" alt="Screenshot 2024-02-06 at 13 18 20" src="https://github.com/photopea/photopea/assets/2387356/66a7db9e-6726-4288-9705-430da0b07408">
</details>

**Comment by photopea** [comment]
I am confused, what are you trying to say?

**Comment by pravdomil** [comment]
> ⌘Q quit
> ⌘H dialog (see below)
> ⌥⌘H hide others
> ⌘, toggle layer
> ⌘M curves!
> ⌘K preferences

those are the default key mappings for photoshop

**Comment by photopea** [comment]
that is exactly what I am saying. Command + M should open curves, and do not minimize Photoshop / Photopea.

**Comment by pravdomil** [comment]
yes

do it the same as psd!

⌘Q quit
⌘H dialog (see below)
⌥⌘H hide others
⌘, toggle layer
⌘M curves!
⌘K preferences

**Comment by pravdomil** [comment]
> that is exactly what I am saying. Command + M should open curves, and do not minimize Photoshop / Photopea.

sorry for that

I would not expect that psd would break the conventions

so now it looks that

only shortcuts that needs to be fixed are:

⌘Q quit
⌘H dialog (see below)
⌥⌘H hide others

it that right?

**Comment by photopea** [comment]
In Photoshop and in Photopea, Command+H is used to switch Extras.

**Comment by pravdomil** [comment]
⌘H

yes

well

depending on what user chooses in [that dialog](https://private-user-images.githubusercontent.com/2387356/302624557-19a9fcd0-6f9b-4bb4-880c-7921f02c2273.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMTEwMzUsIm5iZiI6MTcwNzMxMDczNSwicGF0aCI6Ii8yMzg3MzU2LzMwMjYyNDU1Ny0xOWE5ZmNkMC02ZjliLTRiYjQtODgwYy03OTIxZjAyYzIyNzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDdUMTI1ODU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDZiYzRjMWUwZGMxYWQwN2EzMWY5YWVhY2U3NzYxZGM1ZTU1ZjljZWM4NDBlYWQ2N2U0N2I4MzYwNmM0NGNmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3RlctCPZXm1KDi7qOIuFwLp1gepU8ujO2nVkpwAq9pY) there are two mappings:

⌘H hide
⌃⌘H toggle extras


⌃⌘H hide
⌘H toggle extras

**Comment by photopea** [comment]
I really think that now, shortcuts in Photopea work exactly as 99.9% of our Mac users want them to work. We should not change it. Adding an extra dialogue to let users add extra options is not useful in my opinion. So I will leave it as it is.

**Comment by photopea** [comment]
I am afraid a webpage can not tell a browser to close itself :( Only you can close a website manually.

**Comment by pravdomil** [comment]
you can leave it on browser!
do not preventDefault!
guy please!

**Comment by pravdomil** [comment]
and for the ⌘H
(yes the dialog is annoying)
so add a switch in preferences:
Use ⌘H for Hide
(and then you have better ux then psd)
and do not preventDefault ⌥⌘H and it's done

**Comment by photopea** [comment]
I just opened www.Photopea.com in Safari on my Macbook. I press Command+Q and it closes Safari. What exactly do you want to work differently?

**Comment by photopea** [comment]
Could you also maybe write sentences, instead of random words on many lines? :D

**Comment by pravdomil** [comment]
always try it in webapp added via chrome or safari
in both it does not work

that's how I was born
maybe writing in czech would be help

**Comment by photopea** [comment]
Ok, Photopea is not preventing a default behaviour of Command+Q.

I still can not close the installed Photopea with Command+Q. I think it is a property of the browser, which ingores this shortcut. Even if you click outside the Photopea rectangle, on some other part of the window, Command+Q still does nothing.

**Comment by pravdomil** [comment]
it's a property of pp.js:16144 !!!

<img width="321" alt="image" src="https://github.com/photopea/photopea/assets/2387356/29f3a302-a193-4688-9cb0-4746138e4ae2">
<img width="399" alt="image" src="https://github.com/photopea/photopea/assets/2387356/499c9469-6067-45d8-b982-0113d53fa0a1">

**Comment by photopea** [comment]
Did you try to delete that line inside your tool? Does it help?

**Comment by pravdomil** [comment]
you mean developer tools!
of course it worked!

<img width="1021" alt="Screenshot 2024-02-08 at 19 07 26" src="https://github.com/photopea/photopea/assets/2387356/1a350807-e538-4e1e-ba0b-99b852d33124">

**Comment by photopea** [comment]
you are right, there was a problem on my side, it should be fixed now. Make sure you load a current version (clear your cache).

**Comment by pravdomil** [comment]
nice!!!

and can you don't preventDefault keypresses that is not used in photopea? eg. ⌥⌘H

**Comment by photopea** [comment]
okay it should be done, too

**Comment by pravdomil** [comment]
nice!!!

and if you implement "Use ⌘H for Hide" preferences option
then I can finally use it as psd replacement!!!

**Comment by photopea** [comment]
sorry, that is too much, I dont think anyone other than you needs it. It is not about my work, but about the complexity of settings for all users.

**Comment by pravdomil** [comment]
> complexity of settings for all users
well
if I thought adding "Use ⌘H for Hide" option for all users
(including windows users)
that's not a good idea!!!

just create familiarity of psd settings for macOS users!!!

the ⌘H shortcut is here since June 22, 2001
and I can guarantee you that I'm not the only one
that uses that shortcut on daily basis

**Comment by camoody1** [comment]
@pravdomil You really should learn to stop using exclamation marks (!!!) so much. It comes across as you yelling at people who are trying to help you. It's very off-putting.

**Comment by pravdomil** [comment]
I know!!!
