### ISSUE TITLE
Remove + for keyboard shorcuts hints

### ISSUE THREAD

**Issue by pravdomil** [photopea/photopea#6383]
before
<img width="163" alt="image" src="https://github.com/photopea/photopea/assets/2387356/fadbb133-f3ea-40af-a2a9-4b1c59b16344">

after
<img width="233" alt="image" src="https://github.com/photopea/photopea/assets/2387356/7bca8c2f-b43c-4481-afc2-c9fb787028dd">

**Comment by photopea** [comment]
done :)

**Comment by pravdomil** [comment]
great, you can even remove the space inbetween
