### ISSUE TITLE
Md Ali

### ISSUE THREAD

**Issue by ashan123695** [photopea/photopea#6384]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by camoody1** [comment]
You're going to need to explain your issue a whole lot better than this if you really want assistance.

**Comment by photopea** [comment]
I will close it, as there is not enough information about a problem.
