### ISSUE TITLE
[Critical Bug] Surrounding transparent pixels of WARPED SmartObject are trimmed in parent document

### ISSUE THREAD

**Issue by lucadalli** [photopea/photopea#6386]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode: Yes

**This must be done to see the problem**
1. Visit www.photopea.com/#iS9l2mw-w
2. Observe that transparent pixels are trimmed and car graphic from "Design" SmartObject is positioned in top left corner
3. Exact same PSD but with a white background added to "Design" SmartObject: www.photopea.com/#iCx6sdX6H
4. Observe that car graphic is centered as intended

**Transparent bg:**
![broken](https://github.com/photopea/photopea/assets/39853447/466f29b5-df2e-41db-a8b9-94e540f54ced)

**White bg:**
![bug-2](https://github.com/photopea/photopea/assets/39853447/69b0785c-2ae3-43ff-9e7c-4b8e87bd79b4)

**Comment by camoody1** [comment]
@lucadalli Nice catch! I helped another person on Reddit earlier this week with this same sort of issue. She had purchased a pattern off a site and her Smart Object was off center like this. I couldn't understand the issue, because it seemed to work when I recreated the Smart Object myself. But I bet it was because I used a white background and the original used a blank background. 👍🏼

**Comment by lucadalli** [comment]
@camoody1 Yep, that could explain it. Since reporting this bug I have also found that a transform warp must be applied to the SmartObject to reproduce the bug.

**Comment by photopea** [comment]
Sorry, it is fixed now. This bug was introduced because I solved this previous issue incorrectly: https://github.com/photopea/photopea/issues/6379

**Comment by camoody1** [comment]
> @camoody1 Yep, that could explain it. Since reporting this bug, I have also found that a transform warp must be applied to the SmartObject to reproduce the bug.

I'm pretty sure the person I helped actually did have a warp on it. It was a hanging quilt image.
