### ISSUE TITLE
So slow, "not responding"

### ISSUE THREAD

**Issue by shemaps** [photopea/photopea#6387]
Your Operating System: Windows 11
Your Web Browser: Edge and Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open a file
3. Wait 15 seconds for the file to open
4. Edit a filter, click wait when it keeps saying not responding, can't edit filter, too slow, give up after 10 minutes

**Comment by shemaps** [comment]
What I tried so far: disabling all extensions, using incognito, clearing cookies, restarting computer. I tried all of these things multiple times.

**Comment by photopea** [comment]
I never had to wait 15 seconds for a file to be opened. How large is your file?

Also, what is your PeaMark? Press More - PeaMark and run tests.

**Comment by photopea** [comment]
I have to close it because of no response from the user :( You can still respond, if you have time.
