### ISSUE TITLE
No canvas/viewport

### ISSUE THREAD

**Issue by mega-biggs** [photopea/photopea#6388]
Your Operating System: Windows 11 Home
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new project—custom or from a template
3. New project loads, shows that there are layers. Entire viewport is black. Zooming in or out or trying to select does nothing.

**Comment by photopea** [comment]
I just tried it, but Photopea works well for me in Firefox (on Windows 10). Could you share a screenshot? Does it happen every time? Is your firefox updated?

**Comment by photopea** [comment]
I have to close it because of lack of details :( You can still respond, if you have time.
