### ISSUE TITLE
Quick selection when no layer selected corrupts layers

### ISSUE THREAD

**Issue by Mega0407** [photopea/photopea#6390]
Your Operating System: Windows 10
Your Web Browser: Latest Microsoft Edge Version 121.0.2277.98 (Official build) (64-bit)
The problem happens in the Incognito Mode, too: Yes, confirmed

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open at least 2 images on separate layers. They cannot be the same size.
3. Make sure no layers are selected (use select tool to click outside of canvas)
4. Use quick selection tool. Nothing happens until you click on a layer as necessary to fix the tool. This happens:

![Screenshot 2024-02-05 152054](https://github.com/photopea/photopea/assets/99270686/0001983d-12aa-4eb1-90a9-357f7849c032)

Top layer has a glitched selection, and clicking to reveal layers below it shows they corrupted. I believe this can be undone safely.

**Comment by photopea** [comment]
fixed! :)
