### ISSUE TITLE
The website opens projects that have already been closed, and the poster remains loading

### ISSUE THREAD

**Issue by laucasla** [photopea/photopea#6391]
Your Operating System: Windows 7
Your Web Browser: Opera GX

The page is useless and I cannot open my projects either. This failure has been occurring for several days in a row, since Saturday to be specific, the website before that worked perfectly

**Comment by camoody1** [comment]
Try this:
https://www.photopea.com/tuts/photopea-opens-up-old-files/

**Comment by photopea** [comment]
Exactly, some of your browser extensions, or maybe even the Opera itself, are breaking our backup mechanism: https://www.photopea.com/tuts/photopea-opens-up-old-files/

If you dont know how to turn off your extensions, you can always "fix it" by reinstalling your browser, or switching to a different one :)
