### ISSUE TITLE
Freezing/Crashing

### ISSUE THREAD

**Issue by Ash117578** [photopea/photopea#6392]
Your Operating System: Windows 10
Your Web Browser: Microsoft Edge & Chrome (issue happens on both)
The problem happens in the Incognito Mode, too: Yes incognito on Microsoft Edge also freezes

**This must be done to see the problem**
1. Go to www.photopea.com
2. .... Open an image from your folder (I used a PNG file)
3. .... Zoom in using the alt, and scroll functions and pan around using the shift & ctrl + scroll functions
4. .... Select Polygon Laso and start using the function, the program then very quickly freezes, and because unresponsive permanently

**Comment by photopea** [comment]
I tried to do what you describe, but I can not make Photopea freeze :(

Could you record a short video of opening www.Photopea.com and what you do to make it freeze?

**Comment by Ash117578** [comment]
It did it again, and then when I tried to screen recorded it didn't... all good I will email again if I continue to encounter this problem.

Thanks heaps for your prompt response, I really appreciate it!
________________________________
