### ISSUE TITLE
Freezing, unable to use any tools after pen tool

### ISSUE THREAD

**Issue by akokinias** [photopea/photopea#6393]
Your Operating System: macOS 11.7.10
Your Web Browser: Brave, Chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open .psd from computer
3. Rasterize layer
4. Zoom in
5. Select pen tool
6. Make any closed path
7. Right click > make selection
8. Delete 
9. Deselect
10. Cannot zoom out/in, cannot add any more anchor points, can switch tools but not use them. History shows no more additions

**Comment by photopea** [comment]
I tried it, but after Deselect, I can zoom in / out, and I can start drawing a new path with a Pen tool :(

Maybe I need your PSD to see it happen?

**Comment by akokinias** [comment]
For some reason it's not letting me attach my psd files here, am I doing something wrong? Here's the original png I started with and removed the background before doing the above steps. I've been saving everytime it freezes and I have to close my browser tab so that's why I'm opening it as a psd

![TTPD_logo_upscale_1-transformed](https://github.com/photopea/photopea/assets/159199440/ed2d6c02-e610-4ceb-b86e-12438fd8d5f3)

**Comment by photopea** [comment]
Could you put a PSD into a ZIP and attach it here?

**Comment by akokinias** [comment]
[Uploading TTPD_logo_upscale_1-transformed (1).psd.zip…]()

**Comment by photopea** [comment]
I can not download it :( Can you download it by clicking your link?

**Comment by photopea** [comment]
I have to close it because of lack of details :( you can still respond, if you have time.

**Comment by photopea** [comment]
I have found a serious bug with a Pen tool, and it should be fixed now.
