### ISSUE TITLE
export slices from slice tool to pdf

### ISSUE THREAD

**Issue by MaartenBransen** [photopea/photopea#6394]
Firstly, thank you so much for the amazing work developing Photopea, it works great.

I'm designing a book cover, and I would like to export the front and back of the cover separately for the digital version of the book, instead of one large front+spine+back page as required for printing. The slice tool would perfect for this as I can export the different slices separately, but this is not implemented for PDF export.

Is is possible to implement exporting slices to separate PDFs (or one multipage PDF)?

**Comment by photopea** [comment]
Thanks! I think you should use Artboards for this :) https://www.photopea.com/learn/artboards

Just like when you load a PDF into Photopea, each page becomes an artboard.
