### ISSUE TITLE
shortcut to increase and decrease the brush does not work in Windows

### ISSUE THREAD

**Issue by BrasilCodes** [photopea/photopea#6395]
Your Operating System: Windows
Your Web Browser: Opera
The problem happens in the Incognito Mode, too: idk

**This must be done to see the problem**
1. Go to www.photopea.com
2. Make a psd archive
3. press on the brush
4. try using the shortcuts "[" and "]". As far as I remember, the "[" was used to reduce the brush, but it does the opposite, and the "]" has no effect

**Comment by photopea** [comment]
In Photoshop, I need to switch my keyboard to English to use these keys for a brush size. But in Photopea, it works for me for both an English and a Czech keyboard layout, as Photopea listens for specific hardware keys, rather than characters typed by these keys (like Photoshop does).

**Comment by photopea** [comment]
I have to close it because of the lack of details in the last month.
