### ISSUE TITLE
I have frequent freezes.

### ISSUE THREAD

**Issue by Zeetard** [photopea/photopea#6396]
Your Operating System: Windows 10
Your Web Browser: Chrome

I have frequent freezes. The kind that has to be logged out again and again. I've been looping with it for about 1 hour now.

**Comment by photopea** [comment]
Did you try to open Photopea in the Incognito mode?

**Comment by camoody1** [comment]
@Zeetard Try reading over this page:
https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
You should try it, it takes about 3 seconds.

**Comment by Zeetard** [comment]
> You should try it, it takes about 3 seconds.

I have tried about it. All the irritation was gone. Everything is much better. Thank you.

**Comment by photopea** [comment]
Does it freeze right when you opened www.Photopea.com ? In that case, try this: https://www.photopea.com/tuts/photopea-opens-up-old-files/

**Comment by photopea** [comment]
I will close it now.
