### ISSUE TITLE
Slice labels

### ISSUE THREAD

**Issue by ReynoldsCahoon** [photopea/photopea#6397]
Your Operating System: Windows 10
Your Web Browser: Brave/Chrome
The problem happens in the Incognito Mode, too: Yerp

**This must be done to see the problem**
1. Create a slice
2. Use the `Slice Select Tool` and right click on a slice, selecting `Slice Options`
3. Give the slice a Name.
4. Repeat Steps 1-3.
5. All slices share the same name and the slices cannot be named individually.

Ideally I could name each slice, and when I export the slices, they respect the names given in the slices.

**Comment by ReynoldsCahoon** [comment]
This may be more of a feature request, but I do not have that option. 😅

**Comment by photopea** [comment]
So the bug was, that when you tried to edit the options of a slice with no name, it showed a name of a previous slice, that you edited.

It should be fixed now :)
