### ISSUE TITLE
Half tab size bug

### ISSUE THREAD

**Issue by Jasegaming** [photopea/photopea#6399]
whenever i put a tab into half size the layer viewer dissapears.
![image](https://github.com/photopea/photopea/assets/108829865/2159ccb6-5fbf-45d6-9b00-99ec14d68cdc)

**Comment by photopea** [comment]
What is a "half size"? When your screen is tiny, Photopea switches to a "collapsed view" automatically.

You can use these buttons to expand or colapse the panel:
![image (5)](https://github.com/photopea/photopea/assets/15955558/002db978-7f49-44ae-96c0-cdab3c6f666c)

**Comment by Jasegaming** [comment]
By half size i ment when you make the tab half its size, example
![image](https://github.com/photopea/photopea/assets/108829865/aff06ec6-463a-4692-be6d-feeb86f408d2)

**Comment by photopea** [comment]
ok

**Comment by photopea** [comment]
Ok I see. You can expand the panel using the buttons, as I wrote you before.

**Comment by photopea** [comment]
I will cose it now. Photopea adapts automatically to the area which you give it, to offer you the best experience.
