### ISSUE TITLE
Toolbar issue in Safari

### ISSUE THREAD

**Issue by byrning** [photopea/photopea#64]
Hi,

The left toolbar in Safari (9.1.1) opens at a width of about 440px.
OS: Mac: 10.11.5

![screen shot 2016-06-30 at 2 15 41 pm](https://cloud.githubusercontent.com/assets/9835589/16499192/4488349c-3ecd-11e6-821e-f88c9f02e209.png)

Thanks.

**Comment by photopea** [comment]
Hi, do you know why it happens? The tool images have a fixed size 24x24 px. I have no idea where do 440 pixels come from ... can you analyze it somehow, please? I don't have access to Safari.

**Comment by byrning** [comment]
Changing the following appears to resolve the issue in safari:

.toolbar .tools { display:inline-block; } (line 87 in all.css)
.colorsample { display:block; } (line 573 in all.css)

**Comment by photopea** [comment]
I did that, does it work now?

BTW. can you or anybody else report it to apple (or google / mozilla, don't know who is right) as a bug? It can't be true, that the same CSS looks so different in each browser in 2016 :(

**Comment by byrning** [comment]
Perfect thanks.

**Comment by hannajohnson** [comment]
Hi I'm seeing this problem now in Safari...OS Mac
<img width="1435" alt="screen shot 2018-06-26 at 15 37 39" src="https://user-images.githubusercontent.com/38908236/41915809-e63dde84-7956-11e8-8269-fc6c2b8e883f.png">

**Comment by photopea** [comment]
Hi @hannajohnson , can you try to update your Safari (or Mac OS) ?

**Comment by hannajohnson** [comment]
Yes - I'm running an older version of Safari, it's fine on Chrome - thanks! :)

**Comment by photopea** [comment]
Photopea should run well in all browsers. Just update your Safari (it is probably 6 or more years old).
