### ISSUE TITLE
Сохранение при Закрытии Плагина

### ISSUE THREAD

**Issue by Alexanderksua** [photopea/photopea#6404]
Сделайте Автоматическое Сохранение при Закрытии Плагина после завершения редактирования изображения, пожалуста.

**Comment by photopea** [comment]
Hi, what plugin do you mean?

**Comment by Alexanderksua** [comment]
Photopea[image: image.png]

вс, 11 февр. 2024 г. в 10:48, Photopea ***@***.***>:

**Comment by photopea** [comment]
I can not see your image :( please reply at GitHub.com, do not send emails to some random email addresses

**Comment by photopea** [comment]
I have to close it, because the person did not respond :(
