### ISSUE TITLE
Shortcut for "lock transparency"? (consistency with Photoshop)

### ISSUE THREAD

**Issue by DirkBoer** [photopea/photopea#6405]
Slash / shortcut locks in Photoshop by default only the transparency level. In photopea it does a "full lock" 

I very often lock layers for transparency (working on games/vfx).

I can understand that this might differ with other people, but would it be possible to add also a shortcut for "lock transparency"? 

Like i.e. shift/control/alt + slash. As far as I know they are not used yet, and I think it can make sense and feel natural.
/ "full lock", 
shift+/ "transparency lock"

Your Operating System: Windows
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. create a new layer, draw some stuff on it
3. press / -> see that the whole layer is locked instead of transparency only - this is inconsistent with the Photoshop default behaviour
4. Of course not a problem, some things might be added / improved - but it would really help out if there would also be a shortcut for lock transparency.

Thanks in advance for your answer and keep up the great work!

**Comment by photopea** [comment]
Okay, it should be fixed now.

The Photoshop manual says that "/" is used for the transparency lock https://helpx.adobe.com/photoshop/using/default-keyboard-shortcuts.html#:~:text=Toggle%20Preserve%20Transparency

But I tried to switch with other locks in Photoshop, and then, it seems like the "/" changes the last used lock.

**Comment by DirkBoer** [comment]
you are a beast, thank you!!! ❤️

today coincidently also uninstalled creative cloud - you program circles around the the whole adobe team.
