### ISSUE TITLE
The pen option does not work correctly

### ISSUE THREAD

**Issue by Eros-DS** [photopea/photopea#6407]
Your operating system: Windows
Your web browser: Brave\Google
The problem also occurs in incognito mode: ai

**This must be done to see the problem**
1. Go to www.photopea.com
2. Use the pen tool
3. Create a selection
4. Create another one by selecting above the first one with the "Difference" setting
5. Photopea crashes

As you will see from the video, once I make the first selection and proceed with the second selection with the Difference, Photopea freezes and I cannot use any tool. As you will notice, I cannot press anything even if I continue to click on every part but without any feedback

https://github.com/photopea/photopea/assets/159950291/740c4914-1013-4b3e-b964-9838fa39d5e6

**Comment by photopea** [comment]
So in your video, when you convert a path to a selection, you can not draw a new path with a pen tool?

Could you record a video with opening www.photopea.com and what you do next?

No matter what I do, I can not make this problem happen myself :(

**Comment by Eros-DS** [comment]
Yes exactly. When I create the first selection and I need to create a
second selection, photopea crashes

Il mer 14 feb 2024, 08:51 Photopea ***@***.***> ha scritto:

**Comment by Eros-DS** [comment]
*Video 2* - As you will notice, once I make the selection everything
freezes and I can't do any other action.

*Video 3* - As you will notice, there is also another problem. Photopea is
totally locked, but if I view a layer (or hide it) it won't show me that
I've performed this action, but if I go to save the project for example in
png, looking at the preview, I notice that the action has been performed.
In fact, you will notice that from the main screen my actions are not
performed, but when I go and see the final preview, it shows me exactly
what I did in the design screen. This makes it impossible to continue the
work.
 2.mp4
<https://drive.google.com/file/d/1QF-0ddpiFbl5TMBntMBLiOYe82DuAC8D/view?usp=drive_web>
 3.mp4
<https://drive.google.com/file/d/1aiwDLLusHykzrs4yAiE44tjcbcS-AVB2/view?usp=drive_web>


Il giorno mer 14 feb 2024 alle ore 12:23 Eros Di Sabatino <
***@***.***> ha scritto:

**Comment by photopea** [comment]
I dont have access to your videos :( Could you make sure that your links can be opened by a person who is not logged in to google drive under your account?

Also, please, do not send emails to random github addresses, but reply on a website www.github.com

**Comment by photopea** [comment]
I have to close it because the person did not respond in the last two weeks :(

**Comment by photopea** [comment]
I have found a serious bug with a Pen tool, and it should be fixed now.

**Comment by Eros-DS** [comment]
So have you also found problems with the pen tool?

Il gio 18 lug 2024, 11:50 Photopea ***@***.***> ha scritto:

**Comment by photopea** [comment]
There should be no problems with a pen tool anymore. If you do have any, please, report them.
