### ISSUE TITLE
Bag of photopea when I use the pen tool twice blocking any action on photopea

### ISSUE THREAD

**Issue by Eros-DS** [photopea/photopea#6408]
Every time I use the pen tool twice, photopea freezes

Your operating system: Windows
Your web browser: Brave\Google
The problem also occurs in incognito mode: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Use the pen tool
3. Create a selection
4. Create another one by selecting above the first one with the "Difference" setting
5. Photopea crashes

**Comment by photopea** [comment]
I am confused. Step 4 - create another one - do you mean another path or another selection?

**Comment by Eros-DS** [comment]
Yes, another selection. 

Now I've noticed the definitive problem. 
After the second time I use the pen tool, I can't do any other action because everything in photopea freezes and I can't do any other action (just delete all the work and start over again finding a solution without using the pen tool)

**Comment by photopea** [comment]
Could you write down exact steps - what exactly should I do?

**Comment by photopea** [comment]
I have to close it, because I can not see the problem myself :(

**Comment by Eros-DS** [comment]
So have you also found problems with the pen tool?

Il gio 18 lug 2024, 11:50 Photopea ***@***.***> ha scritto:
