### ISSUE TITLE
image/work disappears after using move tool 

### ISSUE THREAD

**Issue by jasonaxya** [photopea/photopea#6409]
Your Operating System: Windows 11 64x
Your Web Browser: Brave & Opera GX 
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open a image or set of images and edit for a while
3. After editing for a while try to move a duplicated layer or a image that you've copied
4. Screen goes black and no work is visible and cannot restore until unless the work is saved previously.

Please look into this, I've been using photo pea from a very long time and this has never occurred.
Thanks,
Jason

**Comment by photopea** [comment]
Please, do not use Photopea in Brave, Brave is not a real web browser.

I am trying to do your four steps in Google Chrome, but I can not see the screen going black :( could you try it in Google Chrome?

**Comment by photopea** [comment]
I have to close it because of the lack of details.
