### ISSUE TITLE
Doesn't open new psd files from windows pc 

### ISSUE THREAD

**Issue by Y-uli-a** [photopea/photopea#641]
It's possible to open previously downloaded files in Photopea, but new psd files continue "loading" without any result (for the second day already). Tried to open on different Windows devices - with no result. On Mac opens, but only shows one layer.

**Comment by photopea** [comment]
Hi, do you mean PSD files, that you exported from Photopea, can not be open again in Photopea?

Did you create these files in Photopea from scratch, or you opened existing PSDs? Can you send us some of these files (the corrupted one and possibly the original one) to support@photopea.com ?

**Comment by photopea** [comment]
Fixed.
