### ISSUE TITLE
Feature Request: Direct path/vector grabbing

### ISSUE THREAD

**Issue by antrobot1234** [photopea/photopea#6410]
Currently, there are two main ways to modify a path using the direct select tool.

1. grab the path nodes and move them around
2. grab the path handles and move those to change the curve.

I want to suggest a feature I've seen implemented in other vector editing software (e.g. Gimp, Inkscape) that allows for a third option:

clicking and draging on the path itself to allow you to dynamically change the curve handles to "bend" the curve as you drag.
![examplebg](https://github.com/photopea/photopea/assets/21179158/a607b082-1141-45a8-9ba0-c317130b2156)
note that the red circle shows where the user clicked and dragged to. there is no actual path node there, it is simply changing the handles.

**Comment by photopea** [comment]
I have implemented a basic version of this feature. It does not move the anchor points right now (the beginning and the end of a segment).
