### ISSUE TITLE
Duplicate to artboard

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6411]
First issue is taken from March 29, 2021 via @TheRadicalDreamer, at https://github.com/photopea/photopea/issues/3070.
[Screen recording 2021-03-29 23.38.16.webm](https://github.com/photopea/photopea/assets/154830140/5e2ae454-3411-4661-85d6-d65e78da3f80)
[Screen recording 2021-03-30 01.17.57.webm](https://github.com/photopea/photopea/assets/154830140/d1a46575-bdc9-4a41-9c9e-88efb8f1c851)
[Screen recording 2021-03-30 15.08.43.webm](https://github.com/photopea/photopea/assets/154830140/acae26c4-fe59-4983-96b4-a239801a3fd0)

**Comment by photopea** [comment]
Please, report a bug using our template, and include steps to reproduce it.
