### ISSUE TITLE
PDF export don't generate pages when artboards are enabled?

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6412]
This issue is taken at March 30, 2021 via @TheRadicalDreamer, at https://github.com/photopea/photopea/issues/3071.
[Screen recording 2021-03-30 17.29.36.webm](https://github.com/photopea/photopea/assets/154830140/b612c79f-35a9-47d5-ab32-ab1055a31d61)

**Comment by photopea** [comment]
Please, report a bug using our template, and include steps to reproduce it.
