### ISSUE TITLE
Aligning layers horizontally cause them to move A LOT

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6413]
This video is taken from May 28, 2021, via @TheRadicalDreamer, at https://github.com/photopea/photopea/issues/3314.
[Screen recording 2021-05-28 00.00.57.webm](https://github.com/photopea/photopea/assets/154830140/38c1d275-0aa1-4ddf-9585-bf5041c3c98b)

**Comment by photopea** [comment]
Please, report a bug using our template, and include steps to reproduce it.
