### ISSUE TITLE
BUG: Artboards - You cannot reorder artboard folders!

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6414]
This video is taken at May 28, 2021 via @TheRadicalDreamer, at https://github.com/photopea/photopea/issues/3316.
[Screen recording 2021-05-28 01.00.13.webm](https://github.com/photopea/photopea/assets/154830140/4aff526d-f5a4-4704-bb67-a40986d61a5d)

**Comment by photopea** [comment]
You should make a proper report, and include steps to reproduce it.
