### ISSUE TITLE
Artboards - Background is not transparent

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6415]
This video is taken from July 23, 2021, via @TheRadicalDreamer, at https://github.com/photopea/photopea/issues/3520.
[Screen recording 2021-07-11 13.47.02.webm](https://github.com/photopea/photopea/assets/154830140/f42c3cc4-b0b0-40ec-89f5-49fd3db1cb0e)
[Screen recording 2021-07-22 12.41.17.webm](https://github.com/photopea/photopea/assets/154830140/b75e29e7-9219-4501-9307-ed2e1c1c1d22)

**Comment by photopea** [comment]
You should make a proper report, and include steps to reproduce it.
