### ISSUE TITLE
Cannot copy image from Google

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6416]
This video is taken from July 23, 2021, via @TheRadicalDreamer, at https://github.com/photopea/photopea/issues/3600.
[Screen recording 2021-07-23 01.33.03.webm](https://github.com/photopea/photopea/assets/154830140/b0b54d0d-7afa-44c1-95d2-35bfe5af0adf)

**Comment by photopea** [comment]
You should make a proper report, and include steps to reproduce it.
