### ISSUE TITLE
Artboards - Resizing and then moving an artboard in undoable

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6417]
This video is taken from July 30, 2021, via @TheRadicalDreamer, at https://github.com/photopea/photopea/issues/3628.
[Screen recording 2021-07-30 22.04.58.webm](https://github.com/photopea/photopea/assets/154830140/b97de5dc-d3eb-4434-9cde-d90ab7f1bcdd)

**Comment by photopea** [comment]
You should make a proper report, and include steps to reproduce it.
