### ISSUE TITLE
Feature - Export as WMF

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6418]
This video is taken from September 12, 2021, via @TheRadicalDreamer, at https://github.com/photopea/photopea/issues/3723.
[Screen recording 2021-09-12 06.21.23.webm](https://github.com/photopea/photopea/assets/154830140/44c26a0d-0eb0-4d2f-8ab0-03edf3c5f159)

**Comment by photopea** [comment]
You should make a proper report, and include steps to reproduce it.
