### ISSUE TITLE
3 Bugs in one (Resample image; artboard background; artboard history)

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6419]
This video, captured from October 14, 2021, taken from February 14, 2024, via @TheRadicalDreamer at https://github.com/photopea/photopea/issues/3838.
[Screen recording 2024-02-14 11.58.47.webm](https://github.com/photopea/photopea/assets/154830140/3e881a62-e4f7-4bbd-9d26-f40a67ca7f5a)

**Comment by photopea** [comment]
You should make a proper report, and include steps to reproduce it.
