### ISSUE TITLE
postMessage and open files

### ISSUE THREAD

**Issue by titlestad** [photopea/photopea#642]
Hey! It's that time of the month again :-) Here is how Friend is loading files into PhotoPea:
```
var p = msg.Path;
var f = new File( p );
f.onLoad = function( data )
{
	pea.postMessage( data, '*' );
}
// Load binary
f.load( 'rb' );
```
pea = iframe.

The code then sets the state in the Friend application to "load" - and waits for the callback message with data = "done". But it seems any postMessage() I send to PhotoPea just answers with "done" - it would be more useful with some extra data, like: imageKey: "file.psd". And even a unique id for each file. So I could track it through postMessage. 

I am now doing the "save" function. At the moment, I can't really control which file is to be saved. If I have opened three images, and I'm saving, it will just save to the last opened filename on the Friend side. This will make me jump through some hoops, like making a file preview before saving, just to show the user that it's this file that is being saved over the filename.

E.g. Friend opens "hey.jpg" "ho.jpg" "hello.png" into three tabs in PhotoPea. Then I select "hey.jpg" inside PhotoPea and save. This will save "hey.jpg" over "hello.png" - as it's the "currentFile" in the Friend app wrapper.

To do this the proper way, I should be able to name the current tab. Or identify it in a way. This way, I could detect, upon saving, which tab was selected. This is a postMessage I would suggest (to be constructive):

`pea.postMessage( 'app.getDocumentList()', '*' );`

This should return something like:
`{ documents: [ { file: "file.psd", active: true }, { file: "file2.psd", active: false } ] }`

This way, I would know which one was active. Also, after each load, I could get:
`{ result: "done", filename: "file.psd", uniqueid: "a787b7c78d78ff" }`
Which would tell me what the file was called, and which id it had (in case multiple files were called "file.psd").

And:

`pea.postMessage( 'app.activeDocument.setName( "hey.jpg" );', '*' );`

This could rename the file in the tab to match the name of the file I loaded on the Friend side.

Anyway, I think you're seeing where I am going. What do you think?

**Comment by titlestad** [comment]
Oh, and another thing.
In my postMessage calls, it would help to be able to set a callback ID. This way, the response from PhotoPea could include this callback ID, which would allow me to differenciate between the different responses and match them with my queries.
E.g.

> responsesAdd( 47283479, function(){} );
> post( { command: 'load', callbackId: 47283479, data: binToStringData };

```
onmessage( m )
{
    if( m.callbackId ){ executeCallback( m.callbackId ); }
}
```

**Comment by titlestad** [comment]
But how do I match that with the external filename?

**Comment by titlestad** [comment]
And how do I return app.documents[0] from PhotoPea through postMessage? All I get back is data: "done".

**Comment by photopea** [comment]
You can call   app.documents[i].saveToOE("jpg");

I see. It would be nice somehow to unify the HTTP API with the Web Messaging. Until then, I guess you can let users open only one file at a time :(

**Comment by titlestad** [comment]
Yes. I wouldn't mind helping :-) I can imagine huge gains by doing this.

**Comment by photopea** [comment]
The postMessage() can send Strings or ArrayBuffers. I would like everything to be sent in one postMessage call. Should we encode binary files into strings? E.g. in JSON as Base64 ? What do you suggest? E.g. we need to let you send the file name.

**Comment by titlestad** [comment]
https://pasteboard.co/HgViCeW.png

**Comment by titlestad** [comment]
Base64 is tricky. Consider this simple format:
```
// encode and send
var dataMode = 'stringEncoded';
var v = new Uint8Array( data );
data = Array.prototype.join.call( v, ',' );
destination.postMessage( { dataMode: dataMode, data: data, filename: 'thefilename.psd' } );
```

```
// decode to binary on receiving
if( msg.dataMode == 'stringEncoded' )
{
  var data = msg.data.split( ',' );
  data = ( new Uint8Array( data ) ).buffer;
}
```

**Comment by photopea** [comment]
As I said before, we need to send only Strings or ArrrayBuffers with postMessage

**Comment by titlestad** [comment]
As you can see, you can send strings this way. It encodes the binary data as a string. Then it can easily convert it back again.

**Comment by photopea** [comment]
But when you work with just one file, does everything work well?

It would be nice to connect File - Save and File - Export - PNG/JPG/...  with the outer environment, too.

**Comment by titlestad** [comment]
Yes all works now. And I can choose with the file dialog to save in PNG, PSD whatever. Works snappy :-) In fact, I love it!!!!

**Comment by titlestad** [comment]
In fact, I will make a demo tomorrow and post it to youtube. I will link it here.

**Comment by photopea** [comment]
I still don't fully understand what this Friend is. File - Save as PSD should offer the file for saving.

**Comment by photopea** [comment]
I think I can close it now.

**Comment by photopea** [comment]
@titlestad Hi! I extended the API. Now, you have absolute control over the File - Open and File - Save buttons. You can fully integrate it with your own storage system.

I wrote a little tutorial at the end of this article: https://www.photopea.com/api/live
