### ISSUE TITLE
Artboard - Tool is deselected and duplicated artboard goes far away

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6420]
This video is taken from October 20, 2021, via @TheRadicalDreamer, from https://github.com/photopea/photopea/issues/3863.
[Screen recording 2021-10-20 17.04.04.webm](https://github.com/photopea/photopea/assets/154830140/cae121bd-7dbf-47bd-b543-3417e5e76e2a)

**Comment by photopea** [comment]
You should make a proper report, and include steps to reproduce it.
