### ISSUE TITLE
Artboard - Moving a group of layers to another artboard

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6421]
This video, taken from November 10, 2021, captured from February 14, 2024, via @TheRadicalDreamer, at https://github.com/photopea/photopea/issues/3961.
[Screen recording 2024-02-14 12.08.13.webm](https://github.com/photopea/photopea/assets/154830140/e690264c-4dfd-49e8-b97d-7bbb223df09a)

**Comment by TheRadicalDreamer** [comment]
What is this comment?

**Comment by burnsboyamazing** [comment]
It works!
![Screenshot 2024-02-14 12 23 32](https://github.com/photopea/photopea/assets/154830140/aab3880b-38c5-401e-b9d3-3bb98238c26f)
[Screen recording 2024-02-14 12.24.13.webm](https://github.com/photopea/photopea/assets/154830140/af79602b-3e69-40bb-933d-c527eb33ee4e)

**Comment by burnsboyamazing** [comment]
What do you mean?

**Comment by camoody1** [comment]
@burnsboyamazing He's asking why you are going through all of his closed tickets about artboards and opening new tickets referencing him. He doesn't work for photopea.

**Comment by burnsboyamazing** [comment]
That's weird.

**Comment by bluep55** [comment]
This issue was fixed and closed in November 2021.
What is the actual point of opening a new ticket referring to this? 🤷‍♀️

**Comment by burnsboyamazing** [comment]
I have no idea.

**Comment by photopea** [comment]
I will close it, as @burnsboyamazing is not answering any of our questions :(
