### ISSUE TITLE
Vector - Extrange rays on vector

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6422]
This video is taken from November 17, 2021, via @TheRadicalDreamer, at https://github.com/photopea/photopea/issues/3999.
[Screen recording 2021-11-17 16.57.38.webm](https://github.com/photopea/photopea/assets/154830140/a5b54f47-9db4-4de5-b7a2-278af3df67a4)

**Comment by photopea** [comment]
You should make a proper report, and include steps to reproduce it.
