### ISSUE TITLE
Vector Stroke - When changing stroke on a shape, the fill color get transparent

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6423]
This video is taken from November 23, 2021, via @TheRadicalDreamer, at https://github.com/photopea/photopea/issues/4035.
[Screen recording 2021-11-23 16.33.18.webm](https://github.com/photopea/photopea/assets/154830140/aaf492df-15f7-4324-8e32-65cb77293a76)

**Comment by photopea** [comment]
You should make a proper report, and include steps to reproduce it.
