### ISSUE TITLE
Text is not editable

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6424]
This last video, taken from March 23, 2022, via @TheRadicalDreamer, at https://github.com/photopea/photopea/issues/4427.
[Screen recording 2022-03-23 22.18.59.webm](https://github.com/photopea/photopea/assets/154830140/2f31a114-c671-46c9-9601-682fe66e1be0)

**Comment by photopea** [comment]
You should make a proper report, and include steps to reproduce it.
