### ISSUE TITLE
Missing option when selecting "Free" option in ratio/size option selection

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6425]
Missing option in "Free" option when selecting this option at ratio/size selection.

See this video with screenshot.
[Screen recording 2024-02-14 12.33.34.webm](https://github.com/photopea/photopea/assets/154830140/c395e1a1-7082-49dd-9b18-26134afaca18)
![Screenshot 2024-02-14 12 33 57](https://github.com/photopea/photopea/assets/154830140/dd14c0d7-03e2-44ca-bb89-d4d08e4bf276)
@TheRadicalDreamer Missing option in ratio/size selection.

**Comment by photopea** [comment]
You should make a proper report, and include steps to reproduce it.
