### ISSUE TITLE
Path Selection overflow when typing 1000 width/1000 height pixels and then clicking on "Select/New" buttons

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6426]
@TheRadicalDreamer Path Selection is overflowing with 1000 width/1000 height pixels when you type 1000 width/1000 height pixels and then clicking on "Select/New" buttons.
[Screen recording 2024-02-14 12.41.19.webm](https://github.com/photopea/photopea/assets/154830140/61758fec-b52f-47f8-9748-61f99fbfc0e2)

**Comment by TheRadicalDreamer** [comment]
Hello @burnsboyamazing 
You are  a new member of Photopea team?  Why have I received so many replies to closed issues?

**Comment by burnsboyamazing** [comment]
It's working!

**Comment by camoody1** [comment]
@burnsboyamazing Please stop spamming us with all of these reopened cases.

**Comment by burnsboyamazing** [comment]
Why?

**Comment by camoody1** [comment]
> Why?

Because it's annoying and most of your tickets have no real information in them about any actual issue might have. If you have a real problem, open a NEW ticket and reference the other ticket that has already been closed.

**Comment by TheRadicalDreamer** [comment]
I am begging to believe @burnsboyamazing is a bot

**Comment by burnsboyamazing** [comment]
Yes, it is.
