### ISSUE TITLE
Cannot change the color of the shape

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6427]
@TheRadicalDreamer If you change the color of the shape, it does not update the color in shape selection.
[Screen recording 2024-02-14 12.45.30.webm](https://github.com/photopea/photopea/assets/154830140/bd36471b-683b-436f-b1c5-bc779918d7af)

**Comment by bluep55** [comment]
You have to click in the large colour window first.
![Colour picker](https://github.com/photopea/photopea/assets/118609932/a5c4ff95-f274-4b14-9161-8a3a67cc6bdc)

**Comment by burnsboyamazing** [comment]
Thanks, I'll check it out.

**Comment by photopea** [comment]
You should make a proper report, and include steps to reproduce it.
