### ISSUE TITLE
If you crop this image, cropped screenshots will become visible

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6428]
If you crop this image, the cropped screenshot will become visible @TheRadicalDreamer.
[Screen recording 2024-02-14 12.48.35.webm](https://github.com/photopea/photopea/assets/154830140/c7a6bc1b-e006-4c09-9325-ca29a87bfd4b)

**Comment by photopea** [comment]
You should make a proper report, and include steps to reproduce it.
