### ISSUE TITLE
Typing the text in the cropped screenshot stops screen recording

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6429]
@TheRadicalDreamer Typing the text in the cropped screenshot stops screen recording, see screenshot.
[Screen recording 2024-02-14 12.51.05 PM.webm](https://github.com/photopea/photopea/assets/154830140/d46e3415-0aec-442d-8228-4245110d09ba)
![Screenshot 2024-02-14 12 51 19 PM](https://github.com/photopea/photopea/assets/154830140/8b20c73d-67ac-4366-8c14-f136c0b319df)

**Comment by photopea** [comment]
You should make a proper report, and include steps to reproduce it.
