### ISSUE TITLE
Fonts & Brushes

### ISSUE THREAD

**Issue by ShoriFlare** [photopea/photopea#643]
As I mentioned on Twitter I need to add them all back in when I open the site. As I know you said about adding something in for the further future to fix said thing I would also like to mention another problem that there is with the brushes. When I add in a new brush it gets rid of all the other brushes that were already there and when I wish to add them I would have to reload the page completely.

**Comment by photopea** [comment]
Are there any free fonts, that you miss in Photopea? We can add them on our side (for everybody).

**Comment by ShoriFlare** [comment]
[death_in_the_shadow.zip](https://github.com/photopea/photopea/files/1920830/death_in_the_shadow.zip)
[libertinas_co.zip](https://github.com/photopea/photopea/files/1920831/libertinas_co.zip)
[antifont.zip](https://github.com/photopea/photopea/files/1920832/antifont.zip)
[dirt2_soulstalker.zip](https://github.com/photopea/photopea/files/1920833/dirt2_soulstalker.zip)
[blacklisted.zip](https://github.com/photopea/photopea/files/1920834/blacklisted.zip)
[beyond_the_mountains.zip](https://github.com/photopea/photopea/files/1920835/beyond_the_mountains.zip)
[anha_queen_vmf.zip](https://github.com/photopea/photopea/files/1920836/anha_queen_vmf.zip)
[angelic_war.zip](https://github.com/photopea/photopea/files/1920837/angelic_war.zip)

**Comment by photopea** [comment]
I think these fonts are free only for non-commercial use. I am a bit afraid to add them, because some users use Photopea for commercial purposes.

Is the web browser always on on your computer? If yes, maybe you could keep Photopea always open in a tab, so you don't have to re-open all your fonts and brushes.

**Comment by ShoriFlare** [comment]
[angelic_war.zip](https://github.com/photopea/photopea/files/1920847/angelic_war.zip)
[anha_queen_vmf.zip](https://github.com/photopea/photopea/files/1920848/anha_queen_vmf.zip)
[beyond_the_mountains.zip](https://github.com/photopea/photopea/files/1920849/beyond_the_mountains.zip)
[blacklisted.zip](https://github.com/photopea/photopea/files/1920850/blacklisted.zip)
[dirt2_soulstalker.zip](https://github.com/photopea/photopea/files/1920851/dirt2_soulstalker.zip)
[antifont.zip](https://github.com/photopea/photopea/files/1920852/antifont.zip)
[libertinas_co.zip](https://github.com/photopea/photopea/files/1920853/libertinas_co.zip)
[death_in_the_shadow.zip](https://github.com/photopea/photopea/files/1920854/death_in_the_shadow.zip)
