### ISSUE TITLE
cannot select pixels for groups

### ISSUE THREAD

**Issue by antrobot1234** [photopea/photopea#6430]
Your Operating System: windows
Your Web Browser: brave
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. create multiple layers with different contents on them
3. convert them into a group
4. attempt to select group for the group

**Comment by photopea** [comment]
What is "convert them into group"? Do you mean merging layers into one layer, or grouping them - moving them all into one group (folder)?

**Comment by burnsboyamazing** [comment]
Still doesn't select pixels in groups.

**Comment by camoody1** [comment]
@photopea Just block this guy. He's playing games.

**Comment by antrobot1234** [comment]
@photopea i mean taking separate layers and grouping them under one group folder. 
![image](https://github.com/photopea/photopea/assets/21179158/0be0f434-1540-44f2-811e-4c9218c3e59e)

**Comment by photopea** [comment]
I think it should be possible to group layers. Are you a bot?

**Comment by antrobot1234** [comment]
@photopea the issue is not making grouped layers. The problem is that the "select pixel" option which makes a selection of all pixels in a layer does not work if you try to do it on a layer group.

**Comment by photopea** [comment]
Okay, I have added this option. It will process only direct children of a group (and not "grandchildren"), and it will ignore their masks.

But otherwise, you can "select pixels" of any regular layer by holding Ctrl and clicking on its thumbnail. If you add Shift, the new selection will be added to the current selection.
