### ISSUE TITLE
Cannot load in photopea.com page

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/photopea#6432]
@TheRadicalDreamer If you click all the options in photopea.com page, except "Home", "PeaDrive", and "PeaGames", photopea.com page says "Load This Device" and other load pages.
[Screen recording 2024-02-14 5.15.53 PM.webm](https://github.com/photopea/photopea/assets/154830140/52543370-9e81-42cf-a91a-adb7293d2529)
![Screenshot 2024-02-14 5 16 44 PM](https://github.com/photopea/photopea/assets/154830140/41bb3715-a27c-4a51-b407-5c373c59e08e)

**Comment by photopea** [comment]
You should make a proper report, and include steps to reproduce it.
