### ISSUE TITLE
Olympus TG 7

### ISSUE THREAD

**Issue by terrifromwa** [photopea/photopea#6433]
Photopea is unable to open RAW (".ORF") photo files taken with Olympus TG 7 camera.

**Comment by photopea** [comment]
Hi, could you share your file here with us?

**Comment by terrifromwa** [comment]
When I try to attach the the RAW image (".ORF") file here - it says "We don't support that file type."   I can open the RAW file in Affinity Photo 2 and Gimp, but not with Photopea.

**Comment by photopea** [comment]
I was not able to open your file as a RAW file in any program (I tried Adobe Photoshop, Gimp, Affinity Photo, Darktable and others). 

Your camera has been released a few months ago. What program did Olympus tell you to use to open your raw photos? Can you set your camera to take photos in some open raw format, such as DNG? Otherwise, you should ask Olympus for help, as nobody else really knows what is inside these mysterious ORF files.

**Comment by terrifromwa** [comment]
Hi Thanks for having a look into this issue. I have had another look at what software will open this file, and I was wrong about Darktable – sorry. But I can definitely confirm that Affinity Photo 2 will open this file for processing.  I tried to attach an affinity photo 2 file with this ORF file enclosed, but my email says the file is too large. I also tried opening the file with Affinity Photo (the version prior to version 2) and note that it will not open in this program.  But it will open in the later version. I don’t have any specific information from Olympus – but one of the very important reasons that I chose to purchase this camera, apart from it being a rugged waterproof camera, was the fact that it is advertised as being able to shoot in “RAW” format.   Not sure what the issue is but it would be nice to be able to use your software on images captured by this camera.  But in the mean time I guess I will be limited to using Affinity Photo 2, or alternatively importing JPG exported versions. Again thank you for your time. Regards Terri  From: PhotopeaSent: Monday, 19 February 2024 5:51 AMTo: photopea/photopeaCc: terrifromwa; AuthorSubject: Re: [photopea/photopea] Olympus TG 7 (Issue #6433) I was not able to open your file as a RAW file in any program (I tried Adobe Photoshop, Gimp, Affinity Photo, Darktable and others).Your camera has been released a few months ago. What program did Olympus tell you to use to open your raw photos? Can you set your camera to take photos in some open raw format, such as DNG? Otherwise, you should ask Olympus for help, as nobody else really knows what is inside these mysterious ORF files.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by terrifromwa** [comment]
P.S.

I have just done a little Googling. 

It would appear that, as at 16 February 2024, Adobe supports - my OM TG 7 camera, and ORF format (Olympus Raw Format)

See following link:

https://helpx.adobe.com/au/camera-raw/kb/camera-raw-plug-supported-cameras.html

Thanks

**Comment by photopea** [comment]
you should be able to open your ORF file in Photopea now.
