### ISSUE TITLE
Ban burnsboyamazing

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6434]
Sorry, but this user has to be a bot.

It is replicating every closed issue, and replying with nonsense when it is commented on.

![image](https://github.com/photopea/photopea/assets/11801254/13135cbe-89f4-482d-a71b-1cb639200fbf)
--------------------------
![image](https://github.com/photopea/photopea/assets/11801254/920ee175-1881-4cc2-9ef4-ddfef7ba3815)
--------------------------
![image](https://github.com/photopea/photopea/assets/11801254/1994a3e0-f9f5-4d72-a958-84d8e2f2c9fc)

**Comment by TheRadicalDreamer** [comment]
And it has spammed my email
![image](https://github.com/photopea/photopea/assets/11801254/d0e50b95-9e96-424e-b947-90ca86f76bd9)

**Comment by photopea** [comment]
I will look into it.

**Comment by photopea** [comment]
He is not commenting anymore.
