### ISSUE TITLE
Why are there no scroll bars?

### ISSUE THREAD

**Issue by wahtah05** [photopea/photopea#6435]
Your Operating System: win 10
Your Web Browser: chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

Why are there no scroll bars?  why can't i move the image around on the screen??  is the only way to move the image is with the center wheel on the mouse?

**Comment by bluep55** [comment]
Press the Spacebar to pan around the image.
Press Alt to zoom in and out with the scroll wheel.
Click Window > Navigator to use the Navigator window.

![Navigator](https://github.com/photopea/photopea/assets/118609932/dc8a46f7-6ab0-47e8-b032-4ee4857ecec8)

**Comment by photopea** [comment]
I agree, I think scrollbars are not useful, as there are many other ways to navigate around.

**Comment by wahtah05** [comment]
Thanks. my scroll wheel on my mouse is broken and new to this.

**Comment by bluep55** [comment]
You can Zoom and Pan with the Navigator if your scroll wheel isn't working.
