### ISSUE TITLE
Photopea keeps crashing whenever I zoom in

### ISSUE THREAD

**Issue by FJK07** [photopea/photopea#6436]
Your Operating System: Windows 10 Laptop
Your Web Browser: Microsoft Edge
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new file
3. Zoom in on an image by using pen tool or lasso select tool
4. Photopea crashes when I zoom in after a certain amount of time. This has only happened for 2 weeks now and it’s a recurring thing

**Comment by photopea** [comment]
Hi, what exactly does this mean? "Zoom in on an image by using pen tool"

**Comment by FJK07** [comment]
It doesn’t matter now anyway. It’s seemed to be fixed now. I meant that whenever you zoom in on an image and use pen tool, the website just crashes. This hasn’t happened at all since though

**Comment by photopea** [comment]
ok
