### ISSUE TITLE
Using different font style Small Caps doesn't work properly

### ISSUE THREAD

**Issue by tempart45** [photopea/photopea#6437]
Your Operating System: Windows 10
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com/#iZEiri7jw

Check the text (only the first word is marked with SmallCaps property, but the first two words are in smallCaps).
This only occur with mixed fonts (or variants of the same font).

**Comment by photopea** [comment]
Thanks, it is fixed now! The marking was working correctly, but they have been rendered incorrectly. Click the text layers to re-render them.
