### ISSUE TITLE
Top Ribbon Partially Obstructed

### ISSUE THREAD

**Issue by cbcerquiaga** [photopea/photopea#6438]
Your Operating System: Mac OS Sonora 14.1
Your Web Browser: Safari
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com

The top ribbon which has options for the currently selected tool is partially obstructed. The buttons are still accessible, just tougher to click on and very difficult to see.

![image](https://github.com/photopea/photopea/assets/21173989/805cee38-5ec4-4877-9485-6ba92e3bee74)

**Comment by photopea** [comment]
Hi, are you sure you are using Photopea at www.Photopea.com ? I tried it on my macbook in Safari (macOS Monterey) and it seems to work fine.

**Comment by cbcerquiaga** [comment]
Yes I am! I'm on Safari version 17.1

**Comment by photopea** [comment]
Could you share a screenshot of your whole screen? Did you change the webpage zoom?

**Comment by photopea** [comment]
This guy also seems to be using Safari and it looks fine: https://twitter.com/iyia92/status/1759704900114498010/photo/1

**Comment by cbcerquiaga** [comment]
I was just zoomed out lol.

I like to use it zoomed out though, so probably still something that needs fixing?

**Comment by photopea** [comment]
I tried to zoom out in Safari, but it still does not look as in your screenshot :( what exactly did you do in Safari to make Photopea look like that?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
