### ISSUE TITLE
Slice filename convention

### ISSUE THREAD

**Issue by ReynoldsCahoon** [photopea/photopea#6439]
Your Operating System: Windows 10
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create and label 2 slices
3. Export as any image format
4. Select `All Slices` from the Slices option
5. Save
6. Open the generated `.zip` and open the images folder.
7. Images follow the `<image name>_<slice number>.<extension>` convention.

I would like to request an optional convention: `<image name>_<slice name>.<extension>`
If no slice name is provided, default to the slice number.

This allows me to label my slices in a template, import/adjust the image, and export with my desired filenames.

**Comment by photopea** [comment]
got it, it is implemented now.

**Comment by ReynoldsCahoon** [comment]
@photopea This unfortunately doesn't solve this issue. It instead saves out the slices as `<slice name>.<extension>` and doesn't respect the file name.

This means that I'll have to relabel all of the slices manually for each exported template, rather than just renaming/resaving the file with a new name and not having to touch the slice names in the template.

**Comment by photopea** [comment]
But it works like this in Adobe Photoshop, so I think this is how our users expect it to work.

**Comment by ReynoldsCahoon** [comment]
> But it works like this in Adobe Photoshop, so I think this is how our users expect it to work.

Fair. I would love an optional toggle in the export menu to provide this alternative functionality.
![image](https://github.com/photopea/photopea/assets/2556251/d6dfd994-af0d-487e-ae0d-3f23101ecaad)

**Comment by photopea** [comment]
If we added features needed by only one user, our interface would be incredibly messy.

Just adapt your work to the features of Photopea. E.g. set the name of a slice exactly to the name of a future file.

**Comment by ReynoldsCahoon** [comment]
I'll probably use some other tool to automate the naming after I export them.

The benefit of having the filename use the image name as a prefix is:
I have a template of a set of textures that stretch across a 3d model, which have to be cropped in very specific dimensions. Slices allow me to import textures, fit them into the premade template slices (maintaining the individual texture portion names), make my edits, and then export them.

If I'm using 8 or more slices, and you're saying the solution is to rename every slice every time I place a new set of textures into the template for editing, you're greatly increasing my workflow.

Allowing the image name to act as a prefix to the slice names allows me to export them without overwriting previously exported textures.

I acknowledge that the interface cannot serve everyone and include all features. I'm simply asking for your consideration of this use case.
