### ISSUE TITLE
PeaDrive Item Bugged.

### ISSUE THREAD

**Issue by Fitztacles** [photopea/photopea#6440]
Your Operating System: Windows 10
Your Web Browser: Opera GX
The problem happens in the Incognito Mode, too: Yes.

**This must be done to see the problem**
1. Go to www.photopea.com
2. Unsure what I did to cause this to occur, but all files in PeaDrive are .psd files, except for the one highlighted below. It's completely unopenable, and the extension is /psd instead of .psd.
<img width="929" alt="image" src="https://github.com/photopea/photopea/assets/160339967/2cbdca22-654b-460d-af85-389b76927d3c">
3. Attempting to delete the bugged file will result in this appearing:
<img width="736" alt="image" src="https://github.com/photopea/photopea/assets/160339967/a5710ea0-677d-43bd-952d-fac9094947f9">

**Comment by photopea** [comment]
It should not be possible to put a slash into a file name in Photopea anymore (in any Storage).
