### ISSUE TITLE
Photopea stürzt nach Duplizieren von Ebenen ab

### ISSUE THREAD

**Issue by Nadja17** [photopea/photopea#6444]
Photopea stürzt nach Duplizieren von Ebenen ab - Fehler tritt seit 16.02.2024 auf.
Zusätzlich total verzögerte Bewegung bei Verschiebung einzelner Elemente.

**Comment by photopea** [comment]
Hi, what should I do to see this problem myself? Nobody else reported it.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
