### ISSUE TITLE
Photopea doesn't allow me to export a different image after I've exported unless I refresh

### ISSUE THREAD

**Issue by Spoderal** [photopea/photopea#6445]
No I don't have a ad blocker, not sure why its making me refresh to save multiple images

**Comment by photopea** [comment]
When it happens again (a second file can not be downloaded), could you take a screenshot of your whole screen and show it to me?

**Comment by Spoderal** [comment]
Nevermind, it was an issue with permissions with downloading multiple files haha

**Comment by photopea** [comment]
That is what I thought :) I wanted to highlight a notification on your screenshot.
