### ISSUE TITLE
レイヤ―名の変更が出来ない

### ISSUE THREAD

**Issue by umeshige** [photopea/photopea#6446]
レイヤー名の変更が出来ません。レイヤーパレットで名前をダブルクリックすると、別窓が立ち上がって作業出来ません。
ごくまれに、変更出来る事も有りますが、殆ど、出来ません。

**Comment by photopea** [comment]
Sorry, I speak only English :( can you communicate in English?

**Comment by MesaBlack** [comment]
Unable to change layer name #6446
I cannot change the layer name. When I double-click a name in the layer palette, a new window opens and I cannot work on it.
In rare cases, it may be possible to change it, but most of the time it is not possible.

**Comment by photopea** [comment]
Oh, I wrote an email to this guy today, so I will close it.
