### ISSUE TITLE
changing brush colors cause gradient maps to set to last made gradient

### ISSUE THREAD

**Issue by antrobot1234** [photopea/photopea#6447]
Your Operating System: windows 11
Your Web Browser: brave
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. create two new gradient maps via layer > new adjustment layer > gradient map
3. set each one to a different color (e.g. black to red and black to blue)
4. select the gradient mask that was created **FIRST**.
5. change brush color (e.g. pressing X to swap active and inactive brush colors)
6. the gradient that the layer is using will be set to the **LATEST** created gradient map. (e.g. if red was made after blue, then trying to change brush colors while blue is selected will cause it to be set to red).

**Comment by photopea** [comment]
wow, what a complicated bug :( it should be fixed now, thanks a lot!
