### ISSUE TITLE
The "Save" message freezes after a problem with saving to Google Drive, and you can't save anything to Google Drive again until you refresh the page

### ISSUE THREAD

**Issue by Stepan0806** [photopea/photopea#6449]
Your Operating System: Windows 11 Pro 23H2
Your Web Browser: Firefox 122.0.1 (64-bit)
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create new file
3. File > Save More > PSD to Storage > Google Drive > save
4. Edit file
5. Wait until photopea disconnects from Google Drive (e.g. loss of Internet connection)
6. Press Ctrl + S
7.  The "Save" message freezes and the area around it becomes unclickable. Changes are not saved
![зображення](https://github.com/photopea/photopea/assets/64284448/875f3bf7-cbea-48a0-bb32-922b40de8f57)
8. An error appears in the console
![зображення](https://github.com/photopea/photopea/assets/64284448/3efb79b0-eec6-44eb-8fa4-84dc93920c39)
9. Connect to the Internet again
10. Press Ctrl + S
11. A message appears: "Already saving another file. Try again later."
But you can still save files locally on your PC

**Comment by photopea** [comment]
It should be fixed now.

If you try to save to a storage while offline, it will abort the saving process. It will work only when you are back online. Only the "this device" storage is an exception.

**Comment by Stepan0806** [comment]
I still have this problem

**Comment by photopea** [comment]
What steps should I do to see the problem? Is it your original steps? But my internet never goes off, at what point should I turn it off?

**Comment by Stepan0806** [comment]
Yes, the steps I have described reproduce the problem. If you turn off the internet before pressing Ctrl + S, this will happen. Turning off the internet is just the easiest way to get this problem. This happens every time you fail to save a file to Google Drive. Sometimes it happens randomly and I get the following message in the browser console
![зображення](https://github.com/photopea/photopea/assets/64284448/bac8c211-af67-4b68-b56b-f122d7f3eb6f)
Also after that message photopea wants me to load google drive again. This may happen because I use a university Google account and it occasionally logs out of all devices. When I log back into my Google account and load google drive to photopea, it still does not save my changes and the "Save" button remains frozen no matter how long I wait. When I press Ctrl + S again, it says "Already saving another file. Try again later". As I understand, the save process after a saving error is still open, but it does nothing. And photopea thinks that the process is still doing something and won't let me try to save the files again.

**Comment by Stepan0806** [comment]
Yes, I cleared the cache earlier. Although I just tried to do it in edge and there is no problem there

**Comment by photopea** [comment]
okay, so if you have a problem, tell me how to reproduce it.

**Comment by Stepan0806** [comment]
It happened again in Edge with this error in console
![зображення](https://github.com/photopea/photopea/assets/64284448/c2569e92-91d8-4a23-992e-99b70fcd0870)
I didn't have a bad internet connection or disconnecting from my account

**Comment by photopea** [comment]
can you reproduce it?

**Comment by Stepan0806** [comment]
No, it happens randomly

**Comment by photopea** [comment]
I am afraid I can not fix it if it can not be reproduced :( Are you sure it is not related to problems with internet? Maybe it turned off while the file was being saved?

**Comment by Stepan0806** [comment]
No, I was connected to stable internet. Perhaps it is possible to make it so that the message "already saving another file" does not appear if there is a saving error in that another file, so that you can try to save it again after the error occurs?

**Comment by photopea** [comment]
there should not be any "saving error in that other file". Right now, you are the only person reporting such a problem, and I need some way to reproduce it, I can not fix it without reproducing it.
