### ISSUE TITLE
Photo filter adj layer vanish when picking in color picker

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#645]
Vanished once When picking filter color, also vanished once after hit ok in the color picker,

The filter result also didn't update with color picker

**Comment by photopea** [comment]
What do you mean by "vanished"? I think I can not reproduce it.

**Comment by hgs54371** [comment]
Got deleted from layers panel

**Comment by photopea** [comment]
It did not happen for me. Can you take a video of what you did?

**Comment by hgs54371** [comment]
Can't reproduce for now, but that's just I encountered
