### ISSUE TITLE
Brush/Lines are not aligned properly (solved)

### ISSUE THREAD

**Issue by rupkatAI** [photopea/photopea#6451]
Your Operating System: Windows 10
Your Web Browser: Edge
The problem happens in the Incognito Mode, too: yes

![image](https://github.com/photopea/photopea/assets/131705872/2bf2c9e0-9fd4-40f3-9196-4fd01a5487fc)

Theres a gap like u see on the screen. It should be where the lines are, but its moved up. 

How to fix it?

edit:
Solution was cursor offset.

**Comment by photopea** [comment]
yes, it was the cursor offset. Do you think we should delete that option?

**Comment by camoody1** [comment]
> yes, it was the cursor offset. Do you think we should delete that option?

No. That option is probably pretty nice for people on mobile devices without a pen.

**Comment by photopea** [comment]
I have "fixed" it: Whenever your cursor offset is not zero, Photopea will tell you "Edit > Preferences > Cursor Offset is not Zero" each time you start Photopea. So everyone can see the "solution" just by reloading Photopea.
