### ISSUE TITLE
Some Adobe Illustrator files cannot open properly

### ISSUE THREAD

**Issue by kaan-aytekin** [photopea/photopea#6452]
Your Operating System: MacOS Ventura 13.4.1
Your Web Browser: Chrome Version 122.0.6261.57
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Download the AI file [here](https://resources.oreilly.com/examples/9780596808020-files/-/blob/master/Lesson%2011/B%26W%20astronaut.ai)
3. Try to open the downloaded AI file on photopea
4. Canvas does not show any image. Some layer groups are loaded but they are empty.

<img width="1413" alt="resim" src="https://github.com/photopea/photopea/assets/34171928/7b073251-c0ad-4de4-b4bf-ca65306b8f08">

**Comment by photopea** [comment]
I have opened your file in Adobe Illustrator and it looks the same as in Photopea. What does your file should look like, and what software should I use to see this file the way you want me to see it?

**Comment by kaan-aytekin** [comment]
It supposed to look like the image below. 
I can also see the preview by using [this website](https://www.fviewer.com/view-ai)
![resim](https://github.com/photopea/photopea/assets/34171928/c7c104b7-f065-451b-be1e-be6a88b0a47c)

**Comment by photopea** [comment]
Your AI file is also a PDF file. If you rename it from AI to PDF, you can open it in any PDF viewer. This is probably what "this website" does.

I just renamed it into PDF, to make Photopea ignore the AI part of the file, and read the PDF part of the file, and I get the same result as "this website" after opening it in Photopea.
