### ISSUE TITLE
des fichiers endomagés une fois téléchargés que faire ? 

### ISSUE THREAD

**Issue by slimbelli** [photopea/photopea#6453]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....mes fichiers une fois télécharge sont endommagé et impossible de les récupérer que ce passe il ? je veux bien récupérer mes fichiers j'en ai trop trimé pour les bien faire !!? 
4. ....

**Comment by slimbelli** [comment]
mes fichiers une fois télécharge sont endommagé et impossible de les récupérer que ce passe il ? je veux bien récupérer mes fichiers j'en ai trop trimé pour les bien faire !!?

**Comment by photopea** [comment]
Are you talking about PSD files or JPG files? It is probably caused by your browser extensions. Did you try to save files while using Photopea in a web browser with no browser extensions?

**Comment by photopea** [comment]
I have to close it, because nobody is responding.
