### ISSUE TITLE
Slice names not applied on last slice exported

### ISSUE THREAD

**Issue by ReynoldsCahoon** [photopea/photopea#6454]
Your Operating System: Windows 10
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Create an image with more than one slice.
2. Export the slices.
3. The last slice doesn't follow the naming convention, even if labeled.

![image](https://github.com/photopea/photopea/assets/2556251/ae59d7aa-c52f-4bbe-9bea-88dbaefdd40a)

This is related to #6439

**Comment by photopea** [comment]
sorry :( it is fixed now.
