### ISSUE TITLE
Deactivating the ad blocker without success

### ISSUE THREAD

**Issue by LoWi777** [photopea/photopea#6456]
I have deactivated the ad blocker, but I still get the message: "Please let us show you ads ("change consent" on the right), ..."
The “Change consent” button does not respond.

Your Operating System: Windows 11
Your Web Browser: Firefox 123.0 (64-Bit)
The problem happens in the Incognito Mode, too: Didnt try

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open a project from your computer
3. ....
4. ....

**Comment by photopea** [comment]
Did you try to turn off all your extensions?

**Comment by LoWi777** [comment]
I added Photopea to the ad blocker's whitelist: no success.
I deactivated the ad blocker completely, deleted all of Photpea's cookies and restarted the Photopea site with Ctrl+F5: no success.

I didn't completely deactivate **all** extensions, just the ad blocker. Why should I?

**Comment by camoody1** [comment]
@LoWi777 Different extensions affect Photopea weirdly. I recommend disabling all of your extensions, and then one by one, re-enable each extension to find out which one is causing the blocking.

**Comment by photopea** [comment]
I think there might be other extensions that you use which also block ads. If you use Chrome, click this button to see which extensions have your permission to modify Photopea.
![VDzo5rg](https://github.com/photopea/photopea/assets/15955558/2455db76-32bc-4524-8deb-2a7a829eedf8)

**Comment by LoWi777** [comment]
All right, it worked.
The extension “I still don’t care about cookies” caused the error. I whitelisted Photopea in this extension, now everything works.

Many thanks for the help!
All the best!

**Comment by photopea** [comment]
Okay perfect.
