### ISSUE TITLE
Exporting a PSD file to a PDF

### ISSUE THREAD

**Issue by RolyRo** [photopea/photopea#6457]
Apple Macbook Air using Chrome

When I try to export my PSD file as a PDF the PDF is empty. 
It exports but the PFD files has zero KB and will not open.
The PSD file exports fine but I cannot export it to a PDF. Any ideas?

**Comment by photopea** [comment]
Hi, could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it, because nobody responded for two weeks.

Somebody sent me a PSD, which could not be converted to a PDF, and it is fixed now.
