### ISSUE TITLE
Distance knots between each color knot in gradient editor vanish when adjusting

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#646]
There are two knots on each side of a color knots, when adjusting one, the other vanishes

**Comment by photopea** [comment]
You should click on the color knot again, to make the two black knots appear again.

**Comment by hgs54371** [comment]
I know this, but it would be better to both stay visible for quickly switching in between

**Comment by photopea** [comment]
When you drag a black knot, which knot should stay visible, the one on the left or the one on the right? Or all black knots?
