### ISSUE TITLE
Problem with save in SVG shapes with pattern fill 

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#6461]
Hi, Ivan!
First example:
![image](https://github.com/photopea/photopea/assets/29394245/a1e0eba1-03eb-43f0-88e0-a7c2e9e10825)
Blank canvas, as your see
With gradients  - all right
![image](https://github.com/photopea/photopea/assets/29394245/68f172f5-a0ca-412f-a0fa-22fb549a4c84)

**Comment by photopea** [comment]
SVG has no analogy for raster pattern fills :(

I have "fixed" it - Photopea will export pattern fill layers as rasterized pixel layers.

**Comment by Pt-home** [comment]
> SVG has no analogy for raster pattern fills :(
> 
> I have "fixed" it - Photopea will export pattern fill layers as rasterized pixel layers.

I think, this single real variant
