### ISSUE TITLE
paste broken on linux

### ISSUE THREAD

**Issue by hitchhooker** [photopea/photopea#6462]
ctrl + V nor paste button from menu doesn't work on Linux + chromium for some while now
```
10191 🕸 chromium --version                                                                                                           [~]
Chromium 122.0.6261.39 Arch Linux
user@pc01  𓅨 ~
10192 🕸 uname -r                                                                                                                     [~]
6.7.4-arch1-1
```

**Comment by photopea** [comment]
Could you tell us if oyu tried to use Photopea with no browser extensions, which are allowed to modify websites?

**Comment by hitchhooker** [comment]
I did test it in incognito mode(no extensions) having the same problem of not being able to paste from clipboard.

![Peek 2024-02-25 10-18](https://github.com/photopea/photopea/assets/15621959/e5220c49-ba78-4e1d-ab1e-31700f780eff)

**Comment by photopea** [comment]
I think it is all because you are refusing to give Photopea permissions to access your clipboard, so it can not access your clipboard. Did you notice this button? Did you try to click it?
![image](https://github.com/photopea/photopea/assets/15955558/49da028f-35c3-4fb0-8170-0690f0846fd9)

**Comment by hitchhooker** [comment]
Thanks a lot for rapid support and adding alert modal!

**Comment by zoobporsor** [comment]
Copy paste doesnt work for me on Wayland Linux
