### ISSUE TITLE
Is it possible to find out if an image has transparency before saving?

### ISSUE THREAD

**Issue by fx1234** [photopea/photopea#6463]
Hi

We use saveToOE(...) to save an image from a Photopea iFrame. If the user has loaded a JPG, we save it as a JPG again. If the user added a transparent background to the image when editing it, jpg will of course not work. Is there a way to find out whether the image now contains transparency and request it from Photopea in the correct format?

**Comment by photopea** [comment]
You could ask Photopea to send you a PNG, and check the transparency of a PNG. Or run some Photoshop script which loops through all pixels, etc.
