### ISSUE TITLE
Works very slow

### ISSUE THREAD

**Issue by wilmanaro** [photopea/photopea#6464]
Your Operating System: macos
Your Web Browser: crhome
The problem happens in the Incognito Mode, too: yes
Stop using adblock to support advertising. But it works very slow with advertising

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Could you do a Peamark test? Press More - PeaMark.

**Comment by kamenkadze** [comment]
+ work very slow (5-7fps maybe), adblock off/on too same.

**Comment by photopea** [comment]
Could you run the PeaMark test, so that we know how powerful your device is?

**Comment by kamenkadze** [comment]
> Could you run the PeaMark test, so that we know how powerful your device is?

Hello. Everything is fine now, I solved the problem with edge by following the instructions on your website in the problem section.
Now everything is flying for me.

**Comment by kamenkadze** [comment]
> Я вынужден его закрыть, потому что за последнюю неделю никто не ответил.

Oh and if I see a representative of the creator or the creator himself. I express my deepest gratitude.

**Comment by photopea** [comment]
thank you :)
