### ISSUE TITLE
Pasting initial image on Firefox causes cascading 'paste' permission problems

### ISSUE THREAD

**Issue by todduk** [photopea/photopea#6465]
Your Operating System: Windows 10
Your Web Browser: Firefox Dev Edition 124.0b2 (64-bit)
The problem happens in the Incognito Mode, too: N/A

**Repro**
1. Copy an image from another site
1. Go to www.photopea.com
1. On the landing page hit CTRL+V to paste the copied image, there's a paste menu, click it - this works (but it wasn't necessary in the past, probably browser security changes)
1. Press c to crop the image - the paste menu pops up again

This continues for most operations and never goes away, site is effectively useless for me.

**Comment by photopea** [comment]
I think we should look at it only when it happens in a stable version of Firefox. a "Dev Edition" might have many bugs, which will not get into a stable release.
