### ISSUE TITLE
Una mierda!

### ISSUE THREAD

**Issue by cirilasanpedro** [photopea/photopea#6467]
Esto es una mierda, me dice que me trague el anuncio de mierda, me lo trago y sigue sin funcionar al parte de ia... una mierda , no valeis para nada, teneis menos talento que una patata!!... me piro con el ps pirata y que os den mucho por culo anormales!!!

**Comment by cirilasanpedro** [comment]
Esto es una mierda, me dice que me trague el anuncio de mierda, me lo trago y sigue sin funcionar al parte de ia... una mierda , no valeis para nada, teneis menos talento que una patata!!... me piro con el ps pirata y que os den mucho por culo anormales!!!

**Comment by cirilasanpedro** [comment]
Esto es una mierda, me dice que me trague el anuncio de mierda, me lo trago y sigue sin funcionar al parte de ia... una mierda , no valeis para nada, teneis menos talento que una patata!!... me piro con el ps pirata y que os den mucho por culo anormales!!!

**Comment by sugoidesune** [comment]
> This is shit, it tells me to swallow the shitty ad, I swallow it and it still doesn't work on the AI ​​side... shit, you're worthless, you have less talent than a potato!!... I'm pissed off with the pirate ps and they give you a lot of ass, you abnormals!!!


> Esto es una mierda, me dice que me trague el anuncio de mierda, me lo trago y sigue sin funcionar al parte de ia... una mierda , no valeis para nada, teneis menos talento que una patata!!... me piro con el ps pirata y que os den mucho por culo anormales!!!


No hay funciones IA gratuitas, ya que se necesitan computadoras costosas para generar el contenido - a diferencia del editor que se ejecuta en tu computadora.

**Comment by photopea** [comment]
I am closing is, because it seems that the person is using offensive words.
