### ISSUE TITLE
Export to Clipboard

### ISSUE THREAD

**Issue by sugoidesune** [photopea/photopea#6468]
As I am using other online tools, I would appreciate a way to export the result to the Clipboard.
Alternatively display the exported result, so I can right click copy it manually.

Thanks!

**Comment by photopea** [comment]
When you press Edit - Copy in Photopea, you can paste it outside Photopea. Did you try it? Unless you use Firefox, which does not allow websites to put images into a clipboard.

**Comment by camoody1** [comment]
If you want to copy all of your layers to the clipboard at once, click CTRL-A to Select All and then SHIFT-CTRL-C to Copy Merged. Then, you can paste it wherever. 👍🏼

**Comment by photopea** [comment]
In Photopea, I press Ctrl+A, Ctrl+C, I go to www.imgur.com (or to Adobe Photoshop) and press Ctrl+V, and the image is pasted. Is it not enough?

Could you show me an example of how you want it to work? When I copy a JPG file from my desktop (Windows 7), I can not paste it into Facebook or Imgur, etc.

**Comment by photopea** [comment]
Could you at least tell us if you are using Firefox? We are not going to make extra features for Firefox users, just because Firefox developers refuse to implement the web standards.

**Comment by sugoidesune** [comment]
No not firefox. This is not a bug issue.

> In Photopea, I press Ctrl+A, Ctrl+C, I go to and press Ctrl+V, and the image is pasted. Is it not enough?

This only allows to copy as .png
This doesn't allow to copy in a specific file format like jpeg/webp and with a quality setting.

I can't upload a 10MB .png everywhere.
Some websites have MB limits.
Sometimes I need .webp for website upload.
Other website doesn't support .webp I need to upload .jpeg
Some website don't support pasting in upload field only drag / from hard drive. Example:
![image](https://github.com/photopea/photopea/assets/20317691/c04a871c-bfe4-40a1-956f-ea4345a8b4a5)



Many website support copy to clipboard. Unfortunately not many draggable/open new tab.
![image](https://github.com/photopea/photopea/assets/20317691/f5b54f9f-1f44-4a2c-90c5-c5372389d764)
![image](https://github.com/photopea/photopea/assets/20317691/2c3afe79-2afd-4e4b-8023-1f1a39ecc415)
![image](https://github.com/photopea/photopea/assets/20317691/9ee2988c-d817-420b-9edc-8df400be658e)

**Comment by photopea** [comment]
I am afraid what you are asking for is not possible to do with the current technology of our computers.

If you right-click a WebP image on some website, and do "Copy Image", it is still placed into a clipboard as a PNG image. I think software can not place a specific binary file into a clipboard.

If you think it is possible, show us some software which allows you to do it.
