### ISSUE TITLE
pattern fill does not work for shapes

### ISSUE THREAD

**Issue by antrobot1234** [photopea/photopea#6469]
Your Operating System: Windows
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. create a new shape using the path tool
3. set the fill style to pattern mode
4. the shape will not be filled correctly.

**Comment by photopea** [comment]
I can not reproduce this. What tool should I use in the step 2? There is no "path tool" in Photopea.

**Comment by antrobot1234** [comment]
here is a demonstration of the issue. This is happening in the brave browser.
https://github.com/photopea/photopea/assets/21179158/b86227b6-09a0-4c53-a496-48e2a5022305

**Comment by photopea** [comment]
I think it is a bug in a Brave browser. Did you try it in any other browser? We discovered may bugs in Brave in the past, but when we reported it to Brave, they have blocked us.

**Comment by photopea** [comment]
I am pretty sure it is a bug in the Brave browser, we can not do anything about it. So I am closing it.
