### ISSUE TITLE
Gradient does not save correctly

### ISSUE THREAD

**Issue by Wowtones** [photopea/photopea#6470]
Your Operating System:ios
Your Web Browser:google
The problem happens in the Incognito Mode, too:idk

**This must be done to see the problem**
1. Go to www.photopea.com
2. .... first go to gradient fill
3. ....then modify a gradient
4. ....attempt to save as .grd
5. ....import it
It will then when imported not be the correct gradient

**Comment by photopea** [comment]
Hi, what is "go to gradient fill"? Also, did you add the new gradient to a gradient gallery?

**Comment by Wowtones** [comment]
Yes I did and gradient fill is that tool on the side for gradients

**Comment by photopea** [comment]
I have to close it bacause of lack of details :(
