### ISSUE TITLE
Trouble Logging in (says "must go online first")

### ISSUE THREAD

**Issue by JonnyVLV** [photopea/photopea#6473]
Im trying to log in! It keeps saying "Go Online First"
Your Operating System: Apple 
Macbook Pro M1 (Mac OS Monterey) 
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Click the Red "Account" button 
3. It will then say "Go Online First" (In other words it won't let me log into my account)

If you don't know where it says Go Online First basically you now how you use a brush too on something thats un-rasterized and it will say "Must Rasterize first" in a white box at the top...so basically I'm seeing that but it's saying it for when i try to click the account button to log in it will say "Go Online First..stopping me from logging into my account.

<img width="1200" alt="Screen Shot 2024-03-01 at 7 17 22 PM" src="https://github.com/photopea/photopea/assets/161900913/26a82413-9458-4101-bc7c-ad4a1c21dec3">

**Comment by photopea** [comment]
This message should be displayed only if you are offline and you are opening the Account window.

Are you sure you are online when you do this? If yes, could you try turning off all your browser extensions and doing it again?

**Comment by JonnyVLV** [comment]
I am online..  It is not the extensions. I am online photopea just says I'm not. Go in and fix it for me. 👍

**Comment by camoody1** [comment]
> I am online.. It is not the extensions. I am online photopea just says I'm not. Go in and fix it for me. 👍

This is an extensions problem. From your screenshot, it's clear that you have some sort of ad blocker running, whether it be on your PC or on the network you're using. No one else seems to be having this issue. Disable all of your browser extensions and try again. If it works with all extensions disabled, add the extensions back one at a time to find out which extension is causing the problem.

**Comment by photopea** [comment]
Could you try turning off all your browser extensions and doing it again? Sorry, we can not help you, if you refuse to cooperate with us. 

It is like going to see a doctor and telling a doctor that you definitely dont have cancer, and refusing to do the cancer examination.

**Comment by JonnyVLV** [comment]
Solution Fixed: relaunch & update chrome. :)
Thanks team

**Comment by photopea** [comment]
ok

**Comment by ABXstack** [comment]
i have the same issue and i don't have any ad blockers, it was working and not working anymore

**Comment by photopea** [comment]
What is not working? Could you try to use Photopea without any browser extensions?
