### ISSUE TITLE
can't upload .mov file

### ISSUE THREAD

**Issue by kkcaix** [photopea/photopea#6474]
Your Operating System: mac
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. click open from computer and select file
3. popup for fps comes up
4. white bar at the top just says "loading" and the file never uploads

tried using the same file that worked just fine yesterday, and it's not uploading anymore either

**Comment by photopea** [comment]
Could you send me that video to support@photopea.com ?

**Comment by kkcaix** [comment]
Sent!

**Comment by photopea** [comment]
Hi, it should work now :)
