### ISSUE TITLE
PSD Save to Google Drive Stuck

### ISSUE THREAD

**Issue by martinambrus** [photopea/photopea#6475]
Your Operating System: Windows 11
Your Web Browser: latest Chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open a PSD from Google Drive, make any change
3. Wait for about 30-50 minutes
4. Try saving the PSD back to Google Drive

It looks like there is a token timeout when doing this and the save never finishes. Luckily we can still save into local PSD and then save that PSD onto Drive upon page reload - but that's far from user-friendly :-P

**Comment by dobrichovsky** [comment]
Hi,
Thanks for your bug report; it should be fixed now. Gdrive tokens are indeed valid for 1 hour and refreshing them was not handled correctly. If they time out now, you should be promted with Google's authorization screen again to reauthorise.

**Comment by photopea** [comment]
ok, it should be fixed now.
