### ISSUE TITLE
Image crop settings

### ISSUE THREAD

**Issue by deshtele** [photopea/photopea#6476]
Your Operating System: Windows 10
Your Web Browser: Google chrome
The problem happens in the Incognito Mode, too: Yep

**This must be done to see the problem**
1. Go to www.photopea.com
2. Go to crop tool and set crop image size, Width & Height option are available but no option for resolution.

Problem: No option to set image resolution ,like photoshop

**Comment by deshtele** [comment]
No option to set image resolution in crop tool ,like photoshop

**Comment by camoody1** [comment]
Width and Height ARE resolution. What exactly are you looking for?

**Comment by photopea** [comment]
I have added an extra field for the new DPI :)
