### ISSUE TITLE
No Navigator Pane

### ISSUE THREAD

**Issue by DarkScener777** [photopea/photopea#6477]
Your Operating System: Windows 11
Your Web Browser: Waterfox, Firefox
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....There is no navigator pane anymore. I open the site up load an image to be edited and the navigator pane is missing. 
3. ....
4. ....

**Comment by DarkScener777** [comment]
Yesterday 1, March 2024 I had a navigator pane, but today there is none.

**Comment by camoody1** [comment]
@DarkScener777 This is something you have accidentally disabled on your machine. On your top toolbar, click Window -> Navigator. That will add the Navigator pane back.

**Comment by photopea** [comment]
Press Window - Navigator, and it should be there, even after closing Photopea.
