### ISSUE TITLE
Scaling Issues

### ISSUE THREAD

**Issue by CalebPlayzRoblox** [photopea/photopea#6478]
Your Operating System: Windows
Your Web Browser: Chrome+Edge
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open a new template
3. Try scaling the shapes
4. It becomes bigger, when try scaling from side to improve width, it doesn't expand, just grows

**Comment by camoody1** [comment]
Could you please provide some screenshots, or even better a short video, showing what you're having issues with? It's not super clear from your initial description.

**Comment by photopea** [comment]
I think you just have enabled the "keep aspect ratio". Please, read this to learn how the Free Transform works: https://www.photopea.com/learn/free-transform

**Comment by CalebPlayzRoblox** [comment]
> Could you please provide some screenshots, or even better a short video, showing what you're having issues with? It's not super clear from your initial description.

I had it on keep aspect ratio, oopsie

**Comment by CalebPlayzRoblox** [comment]
> I think you just have enabled the "keep aspect ratio". Please, read this to learn how the Free Transform works: https://www.photopea.com/learn/free-transform

issue, thanks!
