### ISSUE TITLE
Drag it outside of gradient editor dialog for deleting color knots

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#648]
This is faster for deleting multiple ones, instead of moving back n forth between knots and delete button, also the delete key in gradient editor dialog deletes layer but not the selected color knots

**Comment by photopea** [comment]
It was fixed, including deleting knots with Delete key.

**Comment by hgs54371** [comment]
When in gradient editor and a knot selected, hit delete key still deletes the layer but not the knot
