### ISSUE TITLE
None of my files load 

### ISSUE THREAD

**Issue by EliRackz** [photopea/photopea#6481]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ...windows
3. ....chrome
4. ....yes

**Comment by EliRackz** [comment]
i have a clothing brand when i put down my mockups and my fronts everything is invisable, please help

**Comment by photopea** [comment]
Could you show us a file, which you can not open in Photopea?

**Comment by EliRackz** [comment]
Thanks for the fast Reply, its not letting me send the file
https://hyperpix.net/text-effects/chrome/free-chrome-text-effect-vol-7/

**Comment by photopea** [comment]
I can open the file "Chrome Text Effect Vol 7.psd" in Photopea (63.8 MB). It took around 20 seconds, as there are 20 layers with Bevel and Emboss, and each layer is like 10 million pixels.

Do you open a PSD file or a ZIP file? Did you try to restart your browser?

**Comment by EliRackz** [comment]
Yes it’s probably just my slow computer sorry

**Comment by photopea** [comment]
So do you have a file, which you could open in Photopea in the past, but you can not open now?

**Comment by EliRackz** [comment]
It’s a T-shirt mockup picture file, if the other file worked for yall then
it’s just my computer I’m sorry to waste your time, I’m just trying to work
on my brand

**Comment by photopea** [comment]
ok
