### ISSUE TITLE
[Feature Request] Update neighboring handles upon node deletion

### ISSUE THREAD

**Issue by antrobot1234** [photopea/photopea#6482]
currently, the way node removal works is that it simply erases the node and joins the two neighboring nodes together with 1 segment.
![image](https://github.com/photopea/photopea/assets/21179158/761dd263-0de0-4d48-b09b-eb0d564d3a18)
I suggest that this functionality changed (or new functionality added) that allows this deletion to update the neighboring node handles to match the original curve as closely as possible (demonstrated using inkscape, as it currently functions this way)
![image](https://github.com/photopea/photopea/assets/21179158/b1a1d6aa-3477-4eeb-8c79-ff3f8090e659)
The reason I suggest this functionality is that it would allow the user to create a rough outline of a shape using basic nodes and curves. they could then delete nodes to be left with a smoother path that still follows the original shape.

**Comment by camoody1** [comment]
This would probably be a nice addition to Vectorpea, as well.

**Comment by photopea** [comment]
Do you know if it is possible in Adobe Photoshop or Adobe Illustrator? I would like to create the same mechanism for this. Basically, you want to reconstruct a curve with two points instead of three.

**Comment by Pt-home** [comment]
This moment use PS and AI
![image](https://github.com/photopea/photopea/assets/29394245/0fc7a876-699a-4f2c-9f91-177709a54ffb)
In Direct Selection Tool

**Comment by photopea** [comment]
@Pt-home are you saying it is possible in Adobe Photoshop?

**Comment by Pt-home** [comment]
> @Pt-home are you saying it is possible in Adobe Photoshop?

Sorry, im not see what question about delete node(((
