### ISSUE TITLE
[Feature Request] ctrl+click to reset/delete path node handles

### ISSUE THREAD

**Issue by antrobot1234** [photopea/photopea#6483]
currently, there is no way to reset node handles except by using alt+click using the pen tool (which resets both handles for a node). I suggest new functionality be added to the pen and direct select tool that allows the user to ctrl+click a path handle to reset it.
![image](https://github.com/photopea/photopea/assets/21179158/1a78c4db-107c-4a7a-859c-8445c581ef5d)
currently, ctrl+click with the path tool functions identically to alt+click (when clicking on a handle) and ctrl+click with the direct select tool currently doesn't do anything.

**Comment by photopea** [comment]
I would like this to work as it works in Adobe Photoshop and Illustrator. Do you know how to do this in these programs? Are you sure the same workflow does not work in Photopea?

**Comment by photopea** [comment]
I have to close it, because nobody replied in four days :(  You can double-click the handles with the direct-select tool to remove them.
