### ISSUE TITLE
Gradient map filter has mask selected by default, rather than gradient

### ISSUE THREAD

**Issue by antrobot1234** [photopea/photopea#6484]
Your Operating System: Windows
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: Yes
when you create a new gradient fill, it has the gradient selected by default.
![image](https://github.com/photopea/photopea/assets/21179158/8bca3772-49a4-46f5-92a7-0ce121219832)
however, if you make a gradient fill adjustment layer, it has the mask selected by default
![image](https://github.com/photopea/photopea/assets/21179158/dd1d8e20-d3c5-4251-9fe2-0d2c76501419)
**This must be done to see the problem**
1. Go to www.photopea.com
2. create a new gradient map adjustment layer
![image](https://github.com/photopea/photopea/assets/21179158/0c99ee6a-e26f-4f38-8557-eefa50e25bdc)
3. the mask will be selected by default, rather than the gradient

the reason that this is an issue is that if you have the mask mode selected, any color picking (such as to select colors for the gradient map) will use the mask colors rather than the image colors. This becomes annoying when you need to make multiple gradient maps for multiple parts of an image.

**Comment by photopea** [comment]
This is how it works in Adobe Photosohp, and how all our users expect it to work :(

**Comment by MichalSZZ** [comment]
> the reason that this is an issue is that if you have the mask mode selected, any color picking (such as to select colors for the gradient map) will use the mask colors rather than the image colors. This becomes annoying when you need to make multiple gradient maps for multiple parts of an image.

@antrobot1234 

in Photoshop - when you are on the layer mask and want to use a color picker, there is a possibility to pick a color from layer - not from the mask's color. Use CTRL + Left Mouse Button Click.

@photopea  do you want to add this feature to Photopea?

**Comment by photopea** [comment]
I can not see such a feature in Adobe Photoshop :( When I have the Eyedropper tool, and I am on a mask, and I hold Ctrl, it switches to the Move tool.
