### ISSUE TITLE
[Feature Request] f2 to rename layer/layer group

### ISSUE THREAD

**Issue by antrobot1234** [photopea/photopea#6485]
It is a common convention in several applications (including the windows file explorer) that f2 is a hotkey for rename. I suggest that this feature be implemented so that if you have a layer/layer group selected, f2 will open the rename textbox.

**Comment by photopea** [comment]
Nobody ever asked for this feature, so I think nobody would use it. I think double-clicking the layer name is much more straight-forward.

**Comment by vvvamik** [comment]
@photopea Double clicking can name a layer, but it doesn't work for a folder. I haven't found it anywhere yet.
