### ISSUE TITLE
[Feature Request] disable anti-aliasing for shapes

### ISSUE THREAD

**Issue by antrobot1234** [photopea/photopea#6486]
Currently, there is no way to disable anti-aliasing for shapes. I suggest that the feature be added and put in the shape panel of the pen tool here 
![image](https://github.com/photopea/photopea/assets/21179158/598a8635-05ec-4d6d-a7f9-53bd0b5f009c)

**Comment by photopea** [comment]
Nobody ever asked for this, and the PSD format does not support non-antialiased vector shapes.

**Comment by MichalSZZ** [comment]
Maybe the author wants an option from Photoshop - named "Align Edges"?
before:
![obraz](https://github.com/photopea/photopea/assets/38118273/75e3e7fe-9e1e-4fff-a00c-12aaa772d481)
after:
![obraz](https://github.com/photopea/photopea/assets/38118273/3adda537-3450-4705-b3f1-ab1bd36c039f)

**Comment by MichalSZZ** [comment]
@antrobot1234  is that what you asked for? But as I can see from your avatar - you probably want to have pixels like in Minecraft ;) 
If you don't want shapes for SVG graphics - you can use some filters or adjustments to achieve that effect. Try to use a threshold adjustment.
