### ISSUE TITLE
Не открываются файлы для редактирования

### ISSUE THREAD

**Issue by MaryFary2** [photopea/photopea#6488]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
I am confused. Do you have a file which you can not open? Could you show us that file?

**Comment by antonyxman** [comment]
Same story but with https://online-fotoshop.ru/

Just unable to open any .jpg file or create anything
Since 2-3 days

Incognito mode as well

Location: Spain

**Comment by Pt-home** [comment]
> Same story but with https://online-fotoshop.ru/
> 
> Just unable to open any .jpg file or create anything Since 2-3 days
> 
> Incognito mode as well
> 
> Tested with Chrome, Opera
> 
> Location: Spain

This site is not Photopea:)

**Comment by photopea** [comment]
@antonyxman That is not our website. You should ask the author of that website about your problem.

Our website is www.Photopea.com, why dont you use Photopea there?

**Comment by antonyxman** [comment]
> @antonyxman That is not our website. You should ask the author of that website about your problem.
> 
> Our website is [www.Photopea.com](http://www.Photopea.com), why dont you use Photopea there?

This is where I came from to this github support, mb it's a mirror of your project? 
Why would anyone copy it but leave the same support page? 

Anyways, photopea.com works good, thanks!

**Comment by photopea** [comment]
I dont know, it seems like someone is trying to steel my work. Do you think I can take it down somehow? Do you know the author?

**Comment by photopea** [comment]
I will close it now.
