### ISSUE TITLE
Remove BG gets stuck

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6492]
Your Operating System: ChromeOS
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open this image 
![image](https://github.com/photopea/photopea/assets/11801254/409f5c3d-48ed-41d5-9b27-88d0f5f79c7d)

3. Apply Remove BG
4. It will be processing for ever.

**Comment by photopea** [comment]
Could you share your image with us? When I cut out the image from your screenshot, the RemoveBG works fine on it.

**Comment by TheRadicalDreamer** [comment]
[Improvisado5.zip](https://github.com/photopea/photopea/files/14513470/Improvisado5.zip)
here

**Comment by Pt-home** [comment]
> Here: [Improvisado5.zip](https://github.com/photopea/photopea/files/14513470/Improvisado5.zip)
> 
> For other images, works fine.
> 
> This is a WEBP

1. Open yor file
2. Use Layer - Flatten Image
3. Use Remove BG
![image](https://github.com/photopea/photopea/assets/29394245/1a8238cb-234e-4570-b330-6fb2d8d53e86)
[PSD.zip](https://github.com/photopea/photopea/files/14519754/PSD.zip)

**Comment by photopea** [comment]
@TheRadicalDreamer I opened your image in www.photopea.com and pressed Select - Remove BG. It worked :(

Did you try it more than once?

**Comment by TheRadicalDreamer** [comment]
yes i tried many times, in incognito AND in another PC.

But today it worked almost immediately. So it is fixed 🤔

**Comment by photopea** [comment]
That is very strange :( Maybe your internet was off?
