### ISSUE TITLE
Font error

### ISSUE THREAD

**Issue by Your-Trash-kid** [photopea/photopea#6495]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

If i open a file which has local fonts/downloaded fonts they do not work and then reset to somthing different why and how can i fix and is there anyway to see what the name of the font being used is so i can compare

**Comment by Pt-home** [comment]
https://www.photopea.com/learn/text-style
Photopea has a huge database of royalty-free fonts. If you know any free font, it is probably already available in PP.

For all other fonts, Photopea allows you to open them (TTF or OTF files) the same way you open any other file (File - Open, or drag-and-drop). They will be added to the end of the font list and used, when some type layer needs them.

**Comment by Your-Trash-kid** [comment]
But my font isn't on that list and it is my own font, I'm asking if there is anyway to see a texts font before editing beacuse when I go to edit it, it changes completely

**Comment by Your-Trash-kid** [comment]
Yes so I downloaded all the needed fonts but when I edit the text the font changes and I don't know why.

**Comment by Your-Trash-kid** [comment]
But im also asking how would it know its the right font because i want to be able to check against that so i know its my fonts

**Comment by photopea** [comment]
You can see the name of the font using the Type tool. Did you load your fonts into Photopea?

As it is not a problem with Photopea (Adobe Photoshop works exactly the same), you should just learn how the program works. Or ask for help here: https://www.reddit.com/r/photopea/

**Comment by photopea** [comment]
That is because you did not load the necessary font.

**Comment by Your-Trash-kid** [comment]
But i did I loaded the right font and it doesn't work and turns into aerial?

**Comment by photopea** [comment]
that is probably not the right font. If you shared your PSD and your TTF font, I could tell you if it is the right font or not.
