### ISSUE TITLE
cant permanantly mute audio of ads

### ISSUE THREAD

**Issue by Tygovr** [photopea/photopea#6496]
Your Operating System: windows 10
Your Web Browser: google
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. video ad pops up
3. click on mute button
4. as soon as a new ad refreshes the audio is back

**Comment by photopea** [comment]
Hi, there should not be any pop-up ads, or ads with audio.

I tihnk you are using a browser extension, which inserts these ads into Photopea. Could you tell us, if it happens in a web browser with no browser extensions?

**Comment by photopea** [comment]
I have to close it, because nobody replied in two days :( But let us know if you really saw ads with sound, while not using any browser extensions.
