### ISSUE TITLE
Cache/backup functionality interfering with API script

### ISSUE THREAD

**Issue by lucadalli** [photopea/photopea#6497]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

I think this is related to #5481 
Sometimes, when loading Photopea to interact with it via API, old documents are loaded from cache causing conflicts with the script sent via `postMessage`.
Is it possible to add an `environment` parameter that disables the caching/backup functionality or a parameter that clears the cache on load?

**Comment by photopea** [comment]
How do you close projects when you are done? Do you use Document.close()? Or you close the website? Does Photopea ask you about the unsaved content?

**Comment by GivenGeorge** [comment]
Templates not working, anyone experiencing the same issue

**Comment by photopea** [comment]
I have disabled the backup mechanism for cases, when Photopea runs in an iframe.

**Comment by lucadalli** [comment]
Brilliant, thanks!
