### ISSUE TITLE
Define Pattern not working as expected

### ISSUE THREAD

**Issue by phpguru** [photopea/photopea#6498]
Your Operating System: MacOS
Your Web Browser: Chrome & Standalone App
The problem happens in the Incognito Mode, too: 

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new blank document with a white background
3. Zoom in as far as it will go
4. Choose the pencil tool
5. Adjust the pencil size to be 1 px hardness 100
6. Anywhere on the canvas draw a checkerboard pattern of 2 x 2 pixels (e.g. black white, white black)
7. Now use the rectangular marquee to select the checkerboard (4 pixels will be selected)
8. Choose Edit -> Define -> New Pattern
9. Zoom out (fit to view)
10. Select All
11. Choose Edit -> Fill... and choose the pattern that was created

Issue: The pattern is defined by the entire document, not from my selection in the current document

**Workaround**
1. Make a new document the size you want the pattern
2. Define the pattern in this document
3. Switch back to the other document
4. Make a selection (optional)
5. Fill with pattern

If this is documented/expected behavior, please close this ticket as User Error :D

**Comment by photopea** [comment]
It is fixed now. If there is a selection, the pattern will be made accordning to the bounding box of that selection :)

thanks for reporting it!
