### ISSUE TITLE
photopea templates not opening?

### ISSUE THREAD

**Issue by GivenGeorge** [photopea/photopea#6499]
![Screenshot 2024-03-07 195901](https://github.com/photopea/photopea/assets/144918184/cba85ea2-023b-4b7c-81a7-eeeb86959f94)

**Comment by photopea** [comment]
Did you try it with several different templates? Did it ever work for you before? Did you try it in the Incognito window?

**Comment by GivenGeorge** [comment]
Yes, I used it a few times, and it worked great, but know its just show loading

**Comment by photopea** [comment]
Did you try it in the Incognito window?

**Comment by photopea** [comment]
In what country are you located now?

**Comment by photopea** [comment]
Can you open this website? https://www.backblaze.com/

**Comment by GivenGeorge** [comment]
Yes

**Comment by photopea** [comment]
Could you try to open some template, and if it does not open, tell me, which one exactly did you click.

**Comment by GivenGeorge** [comment]
Yes sure have a look.

![image](https://github.com/photopea/photopea/assets/144918184/6d0d05e3-e564-433c-a535-aca67e57a103)
![image](https://github.com/photopea/photopea/assets/144918184/3ed0e3ed-5bc7-4654-9fee-60b85fc75f10)

**Comment by photopea** [comment]
Could you connect to the internet through some different internet provider? E.g. enable a wifi hotspot on your phone and connect trhough it.

**Comment by photopea** [comment]
Could you try to use photopea on your phone?

**Comment by GivenGeorge** [comment]
Yes I did not working on phone either

**Comment by photopea** [comment]
Can you open this link? It should start downloading a file (635 kB) https://f000.backblazeb2.com/file/psdshared/UNxT8Uw1

**Comment by GivenGeorge** [comment]
Cant access the link

**Comment by photopea** [comment]
Maybe ask your internet provider about why are they blocking that link. If someone can not open that link, our templates will not work for them. Or get a different internet connection, which allows you to access any website.

**Comment by GivenGeorge** [comment]
I believed it was my network provider that managed to open template when I connected to my mobile hotspot. 

Thank you for your support.

**Comment by photopea** [comment]
ok
