### ISSUE TITLE
Preserve custom shape parameters like corner radius

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#650]
When i try to change corner radius after drawing a rectangle, it is no possibility to do that. Only new shapes have round corners (when it was set before drawing).

Another "nice to have" feature in corner radius, would be four parameters of corners to set separately. In Photoshop it works before and after making rectangle and in default you can type number in one input (all other are linked and set like a first one) or you can unlink (all the same value) and type each radius for corner by hand.

I can show in movie how that is work in photoshop CC if you want.

**Comment by photopea** [comment]
Shape layer in a PSD contains the shape data (vector path), as well as "vector origin data" (if it was originally a rectangle, ellipsis, spiral ... and their parameters). These origin data let us change the parameters and update the vector path in the future (e.g. stretch the rectangle, while keeping the rounded circular corners).

Photopea  ignores these data now, we should implement it. These origin data in a PSD could be generated when converting from Sketch, or when converting from/to SVG (export the rectangle shape as <rect>, now everything is exported as <path>).

**Comment by photopea** [comment]
Hi, it was implemented, see here: https://blog.photopea.com/photopea-3-8-live-shapes-and-new-filters.html

**Comment by MichalSZZ** [comment]
Thank you!
Work very good.
