### ISSUE TITLE
Plz fix the load .tpl not working. When i exported it, Its don't export my brushes. Plz i request you to fix this problem.

### ISSUE THREAD

**Issue by Gorjecs** [photopea/photopea#6501]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Loading custom TPL (tool presets) for the Brush tool should work now. If you still have any problem, please, share your TPL file.

**Comment by photopea** [comment]
I have to close it, because the person did not respond.
