### ISSUE TITLE
Transform not maintaining aspect ratio when scaling with Shift

### ISSUE THREAD

**Issue by CxryzNFTs** [photopea/photopea#6504]
Your Operating System: macos
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open a new project
3. Import an image and try scaling holding with shift
Expected Behavior: Image will keep aspect ratio when scaling.
What actually happens: Image does not keep the aspect ratio and stretches.

On default it should maintain aspect ratio when scaling with shift.

**Comment by photopea** [comment]
That is the expected behaviour, if you have changed the aspect ratio switch. See https://www.photopea.com/tuts/new-free-transform/

**Comment by CxryzNFTs** [comment]
Issue is that it doesn't save my settings. I don't want it to lock
everytime I open Photopea. It used to save my last choice, when I turn off
the aspect ratio lock it keeps it until I turn it back on even when leaving
the site. Only this happened just this month.

**Comment by photopea** [comment]
Oh, wow, you are right. It is fixed now. The switch should keep its "state" after restarting Photopea.
