### ISSUE TITLE
Conver format is not working 

### ISSUE THREAD

**Issue by maxto777** [photopea/photopea#6505]
Your Operating System: Win
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: not sure

**This must be done to see the problem**
1. Go to www.photopea.com
2. File => Automate => Convert formats
3. In the source file select few HEIC files on the computer, and choose JPG 
4. Press convert images, nothing happened, even with several tries and wait for long time

**Comment by photopea** [comment]
it should be fixed now! :)
