### ISSUE TITLE
Please, give us permissions to access your clipboard

### ISSUE THREAD

**Issue by tesunt** [photopea/photopea#6507]
Your Operating System: Windows 10
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: yes

I have been using photopea for a long time now. Everything was working perfectly until 2 days ago when every time I want to copy and paste (Ctrl + C -- Ctrl + V) an image, I get a message that says: "Please give us permissions to access your clipboard."

I've spent hours looking for how to grant these permissions, which were already granted, and I can't find information about it anywhere.

Can anyone here give me a solution?

I appreciate in advance if anyone can help me with this problem.

**Comment by photopea** [comment]
Did you update Brave two days ago? I think this could be their new "feature". 

I just tried Photopea.com in Brave, and copy-pasting works fine for me. When I press Ctrl+V, I see the message (below). Did you enable any "high-security" settings in Brave, which include not letting websites use the clipboard? Could you try to reset your Brave to default settings?

![image (1)](https://github.com/photopea/photopea/assets/15955558/d20375a7-b08e-4438-a1be-a679987de006)

**Comment by tesunt** [comment]
> I just tried Photopea.com in Brave, and copy-pasting works fine for me. When I press Ctrl+V, I see the message (below). Did you enable any "high-security" settings in Brave, which include not letting websites use the clipboard? Could you try to reset your Brave to default settings?

Thanks for your reply. Indeed, brave had blocked photopea's access to the clipboard. I solved the problem by entering here brave://settings/content/clipboard

**Comment by photopea** [comment]
ok

**Comment by photopea** [comment]
Maybe you were asked about it in the past, and you pressed "Block", and Brave does not ask you after that.
