### ISSUE TITLE
Loading pp.js takes 1.5 minutes

### ISSUE THREAD

**Issue by rgex** [photopea/photopea#6508]
Your Operating System: Mac Os
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes!

There are times where loading Photopea is extremely slow.
It would be great if you could use Cloudflare or a similar CDN to host the JS files to ensure high availability and faster loading speeds.

**Comment by photopea** [comment]
Nobody ever reported such a problem. In what country are you located? Do you use a VPN? Do other websites load faster?

**Comment by bennyschmidt** [comment]
I had the same issue recently, sometimes it just does not respond. It seems network related as it only happens sometimes and it even persists in a new tab.

**Comment by rgex** [comment]
> Nobody ever reported such a problem. In what country are you located? Do you use a VPN? Do other websites load faster?

I am located in Cambodia and did not use a VPN, this has happened several times to me already.
Looking at the network traffic my understanding is that there is a single server in Czechia hosting the static files.
In the recent days I had problems connecting to some servers in Europe from Asia but nothing as bad as with PP, perhaps this is due to the Houthis cutting cables that connect Asia to Europe.
<img width="1084" alt="Screenshot 2024-03-11 at 11 09 14 at night" src="https://github.com/photopea/photopea/assets/3996942/13b7be8d-8559-4d4f-a91b-d2d290c06621">

**Comment by photopea** [comment]
I use this tool to check if Photopea is available in different parts of the world: https://www.uptrends.com/tools/uptime , it seems to load fast in all locations. Maybe it is a problem at your internet provider?

**Comment by rgex** [comment]
Today it loaded really fast (less than 2 seconds in incognito mode).
Can it be that when you update the pp.js file and every user is fetching it again the server is saturated with requests?

**Comment by photopea** [comment]
Today, I have changed the cache settings, so it should be cached for 1 hour in your computer.

**Comment by rgex** [comment]
> Today, I have changed the cache settings, so it should be cached for 1 hour in your computer.

Oh I see.
Perhaps you can set an unlimited cache, and when there is a new version change the script src to pp.js?version=12 or pp.js?hash=6d393ac94b6e91d72cb8b6ae79147923
So the file is only reloaded when it is changed, this should massively decrease the network load on your server, but might cause a traffic peak when you push an update.

**Comment by photopea** [comment]
Yeah, I just need to make a mechanism to update these URLs :D I change pp.js about 20x a week, but other JS files are changed like once a month.

**Comment by bennyschmidt** [comment]
> perhaps this is due to the Houthis cutting cables that connect Asia to Europe.

😂 Bullshit politics even makes it way to github

**Comment by funing36** [comment]
It's fine for me, though I had it loaded previously.
![image](https://github.com/photopea/photopea/assets/146106615/f32a7682-ff63-48e7-8477-ef0b31312a4b)

**Comment by photopea** [comment]
I think it is all caused by the attacks of Houthis in Yemen, see https://www.kentik.com/blog/what-caused-the-red-sea-submarine-cable-cuts/

Photopea uses a CDN now to load these files.
