### ISSUE TITLE
.MP4 export option is not working properly anymore

### ISSUE THREAD

**Issue by CornCruskits** [photopea/photopea#6509]
Your Operating System: Windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Layer my photos as usual
3. Go to Animations > Make Layers
4. Attempt to export to MP4 and get mixed results - sometimes the video is 30 seconds long (but not animated), sometimes nothing exports.
5. The GIF and WEBP options look like they work, but I want to use the MP4 option as I export this to my phone.

Thanks!

**Comment by photopea** [comment]
I can not make MP4 export not work, no matter what I do :(

Could you save your document as a PSD and send it to us? I will try to export your PSD with all the layers as a MP4.

**Comment by ericd3hart** [comment]
I'm having this same issue as of a few days. Exporting as .mp4 outputs a corrupt file. I've tried chrome and firefox, tried different image sequences, tried closing and restarting the browser, and tried different quality settings as well. 

GIF exports fine, and it also gives you a preview, as it should. Not seeing a preview for .mp4.

**Comment by photopea** [comment]
Could you show me a PSD file, which you can not export as an MP4 file?

**Comment by photopea** [comment]
Ok, there really is a bug in Photopea.

MP4 video files always have the even number of pixels horizontally and vertically. Your PSD is 2391 x 1345 pixels. What resolution of the video would you like to get? Should we throw away one line and one column of pixels, or should we add another line / column of black pixels?

**Comment by photopea** [comment]
I have fixed it - Photopea should handle odd image dimensions now (it will ad an extra row / column of black pixels).

**Comment by ericd3hart** [comment]
Thanks so much! Either option is fine by me, and I'll be sure to just change the canvas size in the future. Really appreciate the quick fix!
