### ISSUE TITLE
[improvement] transforming rounded rectangle

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#651]
https://youtu.be/QEbo9ExYcj4

In older photoshop versions it worked just like in photopea. 
But it was very frustrating when you have made rounded rectangle with nice corner radius and after width (or height) change (by free transform), knots of corners also was change. 
It looked like it was made using scaleX (Y) of object, not by changing the width (or height) parameter while maintaining the previously set value of the corner radius. 

Scaling in this case is like changing the height and width at once (the radius of the corner stays the same). 

Just another approach to the issue (better for designers). 

And yes, I know that I can change width/height of rounded rectagle by selecting only pair of right, left, top, bottom knots... But Adobe changed that not without the reason ;)

**Comment by photopea** [comment]
I think it is related to https://github.com/photopea/photopea/issues/650  so let's discuss it there.

**Comment by photopea** [comment]
Hi, it was implemented, see here: https://blog.photopea.com/photopea-3-8-live-shapes-and-new-filters.html

**Comment by MichalSZZ** [comment]
It does not work when you use free tranform option. 
Only for changing W and H parameters in properties -> live shape.

**Comment by photopea** [comment]
How does it work in Photoshop?

**Comment by MichalSZZ** [comment]
Like in the movie in my first comment https://www.youtube.com/watch?v=QEbo9ExYcj4&feature=youtu.be
It preserve corner radius when transforming "by hand"

**Comment by photopea** [comment]
You are right, I did not know it could work that way. Will fix it.

**Comment by MichalSZZ** [comment]
No problem :) We are only humans (but sometimes I think that you are a robot :P )
Therefore I check older (closed) issues, to test that you understand what I have in minde.

**Comment by photopea** [comment]
Ok I fixed it :) If you make the rectangle 2x larger with Free Transform, the corner radius stays the same. But if you make it 2x larger with Image - Image Size, the corner radius (and stroke thickness) become 2x larger.
