### ISSUE TITLE
Files not saving when exporting on Photopea

### ISSUE THREAD

**Issue by spicyshee** [photopea/photopea#6512]
Your Operating System: windows
Your Web Browser: chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. do all of your editing
3. Click up to save selected layers
4. click save png 
5. it downloads as a zero byte file repeatedly

I saw another bug about this and they couldnt provide help towards them but I am hoping different

https://github.com/photopea/photopea/assets/163081726/24d726ba-0d47-430d-826e-14ec2adff582

**Comment by bluep55** [comment]
From what I can see, your files are not inside the folder. Only the folder is highlighted so you could be saving an empty Folder.

**Comment by photopea** [comment]
@bluep55 Youa re actually right! That is the reason.

@spicyshee You are saving an empty folder of layers. I have fixed it - Photopea will tell you, that selected layers have no content.
