### ISSUE TITLE
Warp Styles unselectable?

### ISSUE THREAD

**Issue by kuvjason** [photopea/photopea#6513]
Your Operating System: Windows 11
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Yes
I have also tried on Microsoft Edge and the problem still persists.
Update 2: I tried on a different computer and same problem.

**This must be done to see the problem**
1. Go to www.photopea.com
2. Upload picture
3. Upload desired tattoo png
4. Ctrl+Alt+T the tattoo to warp the tattoo and then go select from Warp Style.
5. Once you select a warp style, it usually opens up numerous warp styles to chose from but nothing opens up and you're stuck with "None"

**Comment by photopea** [comment]
I am very sorry, it should be fixed now. Just clear your cache.
