### ISSUE TITLE
Broken Fonts

### ISSUE THREAD

**Issue by angxlzz** [photopea/photopea#6514]
Your Operating System:  Windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Add Text
3. Change Font
4. Doesnt Work

**Comment by hansenwebco** [comment]
Same issue on both Chrome and Firefox.

Cleared cache and local storage same issue.

**Comment by photopea** [comment]
I am very sorry, it should be fixed now. Just clear your cache.
