### ISSUE TITLE
All drop-down menus not functioning

### ISSUE THREAD

**Issue by Millennial-Moron** [photopea/photopea#6516]
Your Operating System: Windows 11 22H2 22621.3155
Your Web Browser: Google Chrome & Microsoft Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Try to use any drop-down menu (font selection, brush sizes, etc. etc.)
3. Drop-down menus and pop-up sliders don't appear

**Comment by davidxuz1** [comment]
Same here.

**Comment by bigbill25** [comment]
+1

Win 10
Chrome Version 122.0.6261.111

**Comment by MrP4nCakes** [comment]
Same here nothing works why??

**Comment by jorgutisan** [comment]
In my case is just with the font.

**Comment by SaltySoggy** [comment]
having the same problem 😭

**Comment by photopea** [comment]
I am very sorry, it should be fixed now. Just clear your cache.
