### ISSUE TITLE
Can change the type of phont

### ISSUE THREAD

**Issue by bia123barbosa** [photopea/photopea#6517]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. add text
3. change type of text (font/phont)
4. not possible ERROR

**Comment by jorgutisan** [comment]
Can't change the type of font too!

**Comment by photopea** [comment]
I am very sorry, it should be fixed now. Just clear your cache.
