### ISSUE TITLE
Can't open fonts menu

### ISSUE THREAD

**Issue by CalebPlayzRoblox** [photopea/photopea#6518]
Your Operating System: Windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open New Project Of Any Size
3. Try to change the font or size
5. Doesn't work

**Comment by photopea** [comment]
I am very sorry, it should be fixed now. Just clear your cache.

**Comment by CalebPlayzRoblox** [comment]
> I am very sorry, it should be fixed now. Just clear your cache.

how
