### ISSUE TITLE
Inconsistent zoom behavior using keyboard shortcuts

### ISSUE THREAD

**Issue by minho42** [photopea/photopea#6519]
Your Operating System: macOS Big Sur, Version 11.7.10
Your Web Browser: Google Chrome, Version 122.0.6261.112 (Official Build) (x86_64)
Does the problem occur in Incognito Mode too? Yes

Steps to Reproduce the Issue:

1. Go to www.photopea.com
2. Use the keyboard shortcut to zoom out (⌘ -) and zoom in (⌘ +) in succession without releasing the command key (⌘). The sequence should be pressed as (⌘ -+).

Expected behavior: The application should zoom out and then zoom in.

Actual behavior: The application zooms out twice instead of zooming out and then zooming in.

**Comment by photopea** [comment]
This is a bug in MacOS and it has been reported here many times. In short, when you hold the Command key, Mac does not tell us which keys have been released, it only tells us which new keys have been pressed. Only Apple can fix it. 

See https://stackoverflow.com/questions/25438608/javascript-keyup-isnt-called-when-command-and-another-is-pressed
