### ISSUE TITLE
Unable to upload any images

### ISSUE THREAD

**Issue by besideman** [photopea/photopea#6520]
Your Operating System: Windows
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Try to upload any photo

I am unable to upload any images for editing - an error immediately pops up. This is the first time this has happened to me - I don't know if it's some temporary problem or if it's just permanently cut me off from Photopea. 
![error](https://github.com/photopea/photopea/assets/163296473/8e29dc4c-fadb-4ad2-8e45-43406630cd98)

**Comment by ArtMau97** [comment]
The same thing is happening to me, I have Photopea downloaded on my PC and I am getting this message from all the PSDs that I am trying to open, happends in both in the program and in the Google Chrome browser.

![CapturaPSD](https://github.com/photopea/photopea/assets/136002458/a416f6a6-c891-4717-b446-c621f356a808)
