### ISSUE TITLE
Photopea 

### ISSUE THREAD

**Issue by Kryptonite67** [photopea/photopea#6522]
Nothing is working. It says "error" when i try to open file

**Comment by Kryptonite67** [comment]
![Screenshot 2024-03-13 123900](https://github.com/photopea/photopea/assets/163299319/a82d2602-9b2e-4ed9-bdfb-4110f4c95cb4)

**Comment by photopea** [comment]
Sorry, it should be fixed now. Please, clear your cache, or wait one hour.

**Comment by Kryptonite67** [comment]
Tnx!
