### ISSUE TITLE
AD-Block Issue

### ISSUE THREAD

**Issue by ZaihnDT** [photopea/photopea#6523]
Your Operating System: Windows 11
Your Web Browser: Microsoft Edge
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Have Ad-Block Extension
3. Photopea shows AD banners on the right
4. Photopea shows "Allow ADs prompt" despite disabled AD-Block

**Comment by camoody1** [comment]
One of your extensions is still blocking ads despite you choosing to disable it for Photopea. You'll need to disable all of your browser extensions and then one by one add them back until you find the offending extension.

**Comment by photopea** [comment]
I installed "uBlock origin" and when I disable it, Photopea does NOT show "Allow ADs prompt".

Which ad block should I install to see what you see?

**Comment by ZaihnDT** [comment]
I have "AD-Block - the best ad blocker" extension installed, but it probably may have got confused by configuration where it doesn't block selective popups but acts as working

**Comment by photopea** [comment]
It is Step 1 in our tutorial: https://www.photopea.com/tuts/photopea-says-i-am-blocking-ads-but-i-am-not/
