### ISSUE TITLE
some pixels

### ISSUE THREAD

**Issue by altons392** [photopea/photopea#6524]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2.I edited the photo and saved it
 3.I sent it to friends everything was fine
 4.Green pixels appeared when opening the file again
![im333age](https://github.com/photopea/photopea/assets/163312975/1f421e14-7101-4ad4-8f7c-bd94c734b489)

**Comment by altons392** [comment]
how to remove these pixels?

**Comment by photopea** [comment]
I think it is a bug on your GPU. What operating system and a web browser do you use?

You can probably fix it by updating your GPU drivers. Or turn off the GPU acceleration in More - Use WebGL. But Photopea will be very slow without the WebGL.

**Comment by photopea** [comment]
Or could you at least share your photo with us, so that I try it myself?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
