### ISSUE TITLE
Flashing Layers

### ISSUE THREAD

**Issue by sharpearnings** [photopea/photopea#6525]
Your Operating System: Windows 11
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2.Open an existing psd file
3.Go to any layer eye (view icon) and layer starts flashing on and off

10:40 am checked photopea it is now working correctly Thanks to whomever fixed the issue, appreciate the promptness!

**Comment by gowriekaran** [comment]
Can confirm it is occurring on Firefox as well, on Windows 11. Seems to be hiding/showing the layer **on hover** of the relative layer eye button, instead of **on click**.

**Comment by break-core** [comment]
I (possibly) have found a source for the issue!

It seems like Photopea recently made a change to the topbar that automatically shows the context panel of any topbar button when you hover over it. This change may have accidentally carried over to the eye button in the layers tab.
![image](https://github.com/photopea/photopea/assets/71668864/e5a87dfd-37a4-4db1-ae40-eab14157d834)

**Comment by OdedOrly** [comment]
Also relevant with the desktop app 
Windows 11

**Comment by daprime07** [comment]
yep same issue here Windows 11, chrome and desktop app

**Comment by photopea** [comment]
Sorry guys :( it is fixed now. I was doing some experiments today, and it had unexpected results.

**Comment by sharpearnings** [comment]
Thanks!
