### ISSUE TITLE
hide/unhide layer spam

### ISSUE THREAD

**Issue by XDKaioden** [photopea/photopea#6527]
Your Operating System: Win 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: No

**This must be done to see the problem**
1. Go to www.photopea.com
2. Not sure

I'm not sure if I pressed the wrong key or not, but suddenly, hovering over the hide/unhide icons spam them as if I was using an auto clicker

**Comment by gowriekaran** [comment]
Same issue as #6526 and #6525

**Comment by photopea** [comment]
Sorry guys :( it is fixed now. I was doing some experiments today, and it had unexpected results.
