### ISSUE TITLE
Copy paste not working in photopea

### ISSUE THREAD

**Issue by rudiffuser92** [photopea/photopea#6528]
Your Operating System: Windows 11
Your Web Browser: Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Draw something
3. Hold ctrl+a to copy everything
4. Hold ctrl+v to paste, nothing happens
5. Hold ctrl+x to cut, it works
6. Hold ctrl+v, nothing happens

**Comment by 87453** [comment]
Same here!

**Comment by photopea** [comment]
sorry, it should be fixed now. Clear your cache, please.

**Comment by rudiffuser92** [comment]
> sorry, it should be fixed now. Clear your cache, please.

Now another problem. Copy paste takes whats on your clipboard from previous first copied image all the time. No matter what you copy but paste results are always from first copy.

**Comment by photopea** [comment]
I can not reproduce such a problem :( Whenever I paste, it pastes the last thing that was copied. What should I do to see what you describe?

**Comment by rudiffuser92** [comment]
> I can not reproduce such a problem :( Whenever I paste, it pastes the last thing that was copied. What should I do to see what you describe?

Issue resolved thank you!! Sorry for getting back late. You fixed it quickly.

**Comment by bluep55** [comment]
Ctrl + A  selects all, it doesn't copy.
In between your actions 3 and 4 you should use Ctrl + C to copy, then use Ctrl + V to paste, otherwise you will be pasting the previous thing you copied.
