### ISSUE TITLE
The "WetShaderBrush" has weird Artificing

### ISSUE THREAD

**Issue by funing36** [photopea/photopea#6529]
Your Operating System: Windows 11
Your Web Browser: Chrome 
The problem happens in the Incognito Mode, too: N/A

**This must be done to see the problem**
1. Go to www.photopea.com
2. Make a layer for the background. Color it brown for example...
3. Make another layer above it, select the "WetShaderBrush", or brush 8

![image](https://github.com/photopea/photopea/assets/146106615/851a1cdb-4a94-47a4-b7fe-4213c3293c53)

4. Make the brush black, then look at the sides after you draw the line...

![image](https://github.com/photopea/photopea/assets/146106615/4d81253d-729c-47ae-b3c9-69408c0602e4)

![image](https://github.com/photopea/photopea/assets/146106615/04632bc2-db97-46d8-bde8-549b55a2d681)

**Comment by funing36** [comment]
Well, I'm not 100% sure if the "artifacting" you see on the sides of the main brush is intentional, or an oversight.

**Comment by funing36** [comment]
I just remember using this brush before I used a custom .abr and having to erase one of the layers for 15-30 minutes in both eyes on a drawing I was working on. (eyes has bright colors, so it was very apparent) If it's intentional, then yay, but I'm just reporting a possible issue.

**Comment by photopea** [comment]
I think this brush should look like this. You can change the parameters of the brush in Window - Brush.
