### ISSUE TITLE
Trim then "Current Layer" issue

### ISSUE THREAD

**Issue by blofstedt** [photopea/photopea#653]
If you trim the image and then select "current layer", Photopea does this instead of realizing that the current layer size has changed...
![image](https://user-images.githubusercontent.com/38229215/39013728-8c545e54-43d5-11e8-93c5-b067c16ab7b6.png)

**Comment by photopea** [comment]
This feature si related to the cropping mechanism in general. Now, cropping does not remove any data (all layers keep having the same pixels.
