### ISSUE TITLE
Smart objects for mockup do not work. 

### ISSUE THREAD

**Issue by Tuzik-Keks** [photopea/photopea#6532]
Check video

https://github.com/photopea/photopea/assets/124617109/0987a1e2-61d9-4135-8e0a-a97f9713ffe0

I've also done it through Adobe Photoshop, and it works just fine. Thank you.
![image](https://github.com/photopea/photopea/assets/124617109/e173a0a7-4153-4cee-a8c0-ca8e1ebdbad4)

Can you tell me what the problem is?

**Comment by photopea** [comment]
Could you share your PSD? You are probably using some filters on that smart object, because you can not make a rectangle "bend" like this using the Free Transform.

**Comment by Tuzik-Keks** [comment]
You can give me your email and I will send you the file, you can't attach a format like .psd here

**Comment by Tuzik-Keks** [comment]
But this is a common function of a smart object, you create a rectangle, make it a smart object, then deform it, then go inside and upload the image, Save it, and it takes the shape you need.

**Comment by photopea** [comment]
You can send it to support@photopea.com

**Comment by bluep55** [comment]
Try using the Transform controls.

https://github.com/photopea/photopea/assets/118609932/a7c8b2ac-c6ef-422e-ac74-adaaf3b9ee6c

**Comment by photopea** [comment]
Your Smart Object has a "Perspctive Warp" filter, which Photopea does not have yet. So we can not redraw your smart object correctly after you update it :( 

I will try to implement it in the following weeks: https://github.com/photopea/photopea/issues/5059
