### ISSUE TITLE
Still having issues with MP4 export

### ISSUE THREAD

**Issue by ericd3hart** [photopea/photopea#6533]
Your Operating System: Windows
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

I'm having two different issues:
For one, the compression on MP4 export is horrible. It's far worse than that of a GIF, and much worse than I would expect for an MP4 file.  Potentially an issue with the quality output. 
Secondly, I can export an MP4 successfully now, with very bad compression, but if I export a GIF file first, the MP4 puts out a corrupted file again. 

**This must be done to see the problem**
1. Go to www.photopea.com
2. Export a series of images as MP4. It should be successful (but the compression is bad).
3. Export the same file as a GIF. It will be successful as well.
4. Try to export as an MP4 again. There is no video preview. The MP4 file is corrupted. 

Thanks in advance.

**Comment by photopea** [comment]
Sorry, it should be fixed now. Photopea should always produce an MP4 file.

Regarding the Quality - did you try to move the Quality slider to the right side? Does it get any better?

**Comment by ericd3hart** [comment]
![image](https://github.com/photopea/photopea/assets/163231427/74512bd8-b293-4c21-ba6c-ce92014ab019)

I did try the quality slider, and the quality between 50 and 100 appears to be the same.

**Comment by ericd3hart** [comment]
Relatively the same, I should say. This is the image in Photopea without exporting as an MP4. 
![image](https://github.com/photopea/photopea/assets/163231427/0030c71e-fe72-46b6-a42e-9313b09e8fdc)

**Comment by photopea** [comment]
Is it still the same PSD with five frames? When I set the quality to zero, I get an MP4 file of 130 kB. When I set it to 100%, I get an MP4 file of 471 kB, so the quality changes. And at 100%, it looks very well in my case.

**Comment by ericd3hart** [comment]
I think I got it to work for my purposes! I was also seeing a difference in file size, and a slight difference in quality, but 100% was still very compressed. I was able to set it to 200% quality (which I didn't know I could do), and that essentially fixed my issue. 

I very much appreciate the help.

**Comment by photopea** [comment]
I did not know you could set it to 200% either :D But I am glad it works!
