### ISSUE TITLE
[Feature Request] Stick comfirm&cancel buttons on edge when tool options overflowed

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#6534]
Like this. Shadow in left border of the buttons is needed.
![Screenshot_20240317_005420](https://github.com/photopea/photopea/assets/79258245/3ca8140d-1bf5-4f63-9fea-875fb30c7dc6)

**Comment by camoody1** [comment]
Solid idea.

**Comment by bluep55** [comment]
A very good idea.
A similar request here from Feb 2023 which is still 'Open' https://github.com/photopea/photopea/issues/5345#issue-1570922247
The original and similar request was from yourself.
This would be a big improvement to mobile phone use, and make things easier and less frustrating if it was implemented.

**Comment by TheRadicalDreamer** [comment]
YES! Please

**Comment by camoody1** [comment]
I'll vote YES PLEASE again.

**Comment by MichalSZZ** [comment]
Good Idea. Many times I wasn't able to drag the top bar to the left without accidentally changing the other values (that have swipe to change feature in inputs)

**Comment by photopea** [comment]
It is fixed now!

@nothingshiru I did not know about "position: sticky", it was really easy to do using it, so thank you! :)
