### ISSUE TITLE
[Feature Request] Move the ad area in proportion to the page

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#6535]
Display ads at right side when width of page is higher than the height, and display it at bottom when the height is higher than the width. And move it during width/height changing. (resizing page on pc, rotate screen on phone/tablet)

**Comment by photopea** [comment]
I am afraid that our ad provider will not allow us to replace ads like that while resizing Photopea :( They might think that we are trying to "cheat" by generating more ad views.

**Comment by photopea** [comment]
we show different ads on mobile screens (portrait mode) and desktop screens. So yes, resizing a window would reload ads.

**Comment by photopea** [comment]
Ads on the right side make more money, so if the screen is big enough, we prefer to display bigger ads.

**Comment by photopea** [comment]
We can place an ad on the right side only if it is at least 600 pixels tall.

Yes, the screen is small, but you can use it in a portrait mode, or pay for the Premium account.

**Comment by photopea** [comment]
Now, if you open Photopea on a mobile display in landscape, it should add a wide ad to the right side.

Resizing the window (rotating your phone) while using Photopea will not replace ads.
