### ISSUE TITLE
Mask is not showed in channel panel when it is not selected

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#6536]
Your Operating System: Windows 11
Your Web Browser: Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new project
3. Create mask on background layer (the mask is selected by default)
4. Switch to channel panel and see there is the mask
5. Switch back to layer panel and click thumbnail of background layer so that the mask is not selected
6. Switch to channel panel again and see there is no the mask

**Comment by photopea** [comment]
it should be implemented now.
