### ISSUE TITLE
Project Disappearing 

### ISSUE THREAD

**Issue by ThatonePinkCrab** [photopea/photopea#6538]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....keep the tab open on your project and go to a new tab
3. .... stay for about five minutes
4. .... go back and you cant see your project only the layers

**Comment by photopea** [comment]
I did steps 1 to 3 many times in the past, but it never happened to me :( What kind of a device do you have? How much RAM do you have?

If you still see layers, you should be able to save your work as a PSD and restart Photopea.

**Comment by photopea** [comment]
I have to close it because of lack of details.
