### ISSUE TITLE
Shortcuts works only on english keyboard layout

### ISSUE THREAD

**Issue by Ser-Gen** [photopea/photopea#654]
I use two layouts: russian and english.
On english everything works fine, while russian is not working.

If you use code just like in that fiddle, then you got, for example, key `я` instead of `z`.
https://github.com/photopea/photopea/issues/637#issuecomment-380155580

Please, use `keyCode` or something layout-independent.

**Comment by photopea** [comment]
Yes. Now, Photopea reads actual characters instead of hardware codes (e.g. you can use the + on the main keyboard, or on the numeric keyboard). Do you have Photoshop or Gimp? How do they work on Russian keyboard?

**Comment by Ser-Gen** [comment]
PS behave like PP in older releases, but CS6 works fine.
Gimp have some weird issues with russian layout, but shortcuts works most of the time too.

**Comment by photopea** [comment]
Today, I completely remade the keyboard handling. Now, Photopea analyzes only hardware keys, that are pressed and released. The "language" of the keyboard (that you usually set in your OS) is completely ignored. I believe it may have fixed your issue.

**Comment by k-risc** [comment]
I just tested it. Changing the zoom with Ctrl++ Ctrl+- does not work for me (Windows 10, German keyboard layout, Firefox or Chrome). Changing the keyboard layout to English and pressing Ctrl and the key combinations on the keyboard that then yield "+" or "-" works.

**Comment by photopea** [comment]
Hi. Can you go here: http://jsfiddle.net/p45f44zb/14/ , click into the bottom right part and try your shortcuts?

What key codes do you see, when you press them? They should be the same for both English and German keyboard.

**Comment by photopea** [comment]
Ok, I can make the combination  ["ControlLeft","BracketRight"]  to zoom in. And what combination you want for the zoom out?

**Comment by k-risc** [comment]
You're a star! That would be ["ControlLeft","Slash"]

**Comment by k-risc** [comment]
You're a star! That would be ["ControlLeft","Slash"]

**Comment by photopea** [comment]
I am going to identify "BracketRight" with a Plus key, so every shortcut that requires Plus, can use BracketRight, too. By the way, do you have Adobe Photoshop? Does it accept that shortcut for zooming in?

**Comment by k-risc** [comment]
I have Photoshop CS3, and that version accepts if I press Ctrl++ and Ctrl+- in the German keyboard layout for zooming in and out.

**Comment by photopea** [comment]
Ok I made them work, too. Thanks! :)
