### ISSUE TITLE
Resize don't work

### ISSUE THREAD

**Issue by szkma27** [photopea/photopea#6540]
Your Operating System: Windows 11
Your Web Browser: Google Chrome

1. Go to www.photopea.com : 
https://github.com/photopea/photopea/assets/163778659/5ef6a1e4-d59d-4a5d-af14-aa8b5b4a074d

**Comment by szkma27** [comment]
If you have that click lenghts option

**Comment by photopea** [comment]
Hi, it is not clear what you are doing in your video :( could you record the whole screen?

**Comment by szkma27** [comment]
> Hi, it is not clear what you are doing in your video :( could you record the whole screen?

Hi ! I tried to resize my photo but it doesen't work then i choose lenght option and it works 🤷

**Comment by photopea** [comment]
ok
