### ISSUE TITLE
[Feature Request] Canvas degree snap only after rotation done

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#6541]
I've experienced a better rotation gesture in a painting app. 

Rotating with 2 fingers, canvas is not snapping while rotating. After released fingers, if the degree is 0±5 (or 90±5, 180±5, 270±5), it snap to 0 (or 90, 180, 270). This allows canvas to continue to follow the fingers without pausing.

**Comment by photopea** [comment]
So we should snap at multiples of 90 degrees?

Why is it better to snap only after the rotation ends? I think it should be snapped while rotating, so that the user knows if it will be snapped after releasing, or not.

**Comment by photopea** [comment]
what is a gesture?  When you touch the canvas with two fingers, it will zoom and rotate, so that the two points always stay under your two fingers. There are no any other "gestures".

**Comment by photopea** [comment]
Ok, the rotation with fingers is snapping to multiples of 90 degrees now.

**Comment by photopea** [comment]
I dont have access to Procreate, Artstudio Pro, Infinite Painter, HiPaint. Could you describe how exactly does it work, and how is it different from the current Photopea?

**Comment by photopea** [comment]
I have made the "snapping radius" smaller, so it should look smoother now.

I dont know why would anyone use a rotation of 3 degrees instead of 0 degrees.

**Comment by photopea** [comment]
I think it is best to keep it as it is now.
