### ISSUE TITLE
[Feature request] Change Brush to crosshair with Capslock 

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#6543]
In Adobe Photoshop there is a shortcut that gives a way, to have a precise cursor in Brush Tool. 
Capslock switches the cursor between brush preview (with its shape, size, and hardness) and the precise Crosshair cursor.

Is it possible to have this shortcut in Photopea?

**Comment by bluep55** [comment]
My Photoshop shows a Crosshair in the centre of the Brush Tool, as shown in this image.
If the Capslock option isn't possible in Photopea, then maybe place a Crosshair in the centre of the curser in Photopea, just as it is in Photoshop.

![Crosshair](https://github.com/photopea/photopea/assets/118609932/95c0c1ff-e68e-46b8-9f5b-ff1d3e06a66c)

**Comment by photopea** [comment]
I have implemented it :)
