### ISSUE TITLE
Vertical scrollbar is showing when user have to many Plugins in photopea 

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#6544]
Your Operating System: Windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: NO (user settings are not displayed in incognito)

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new project
3. Go to the menu Window -> Plugin ... and install a lot of Plugins
4. On the side menu. Icons from Plugins are displayed and the vertical scrollbar is showing. The icons such as "Trash" on the bottom right are hidden. When the user scrolls down - the top interface is hidden (menu and top toolbar).

The scrollbar shouldn't be visible. Add the scroll on the sidebar with icons only (when the mouse is over) or add something like an arrow to scroll down or three dots showing more (hidden) icons.

![obraz](https://github.com/photopea/photopea/assets/38118273/fc440465-17c9-4929-b8cd-c4f4d9d47a59)

**Comment by yikuansun** [comment]
@photopea
```
.rightbar:nth-child(1) {
    height: calc(100vh - 63px); /* or use js to adjust height based on top menubar */
    overflow-y: scroll;
}

::-webkit-scrollbar {
    width: 0;
}
```

**Comment by photopea** [comment]
It should be scrollable now, both when expanded and when collapsed.
