### ISSUE TITLE
[Feature request] Vectorpea + Photopea | Vectorised rendering

### ISSUE THREAD

**Issue by LukeSeers** [photopea/photopea#6546]
I'm a avid photoshop user for decades, and more and more Linux in finally becoming a option. Photopea, is by far, the only good alternative out there that really competes with photoshop! You have done a fab job!

You already beat photoshop with it's performance, and opening my huge PSD files works like it would in photoshop, but.. with no performance impact! generally well done man!

Normally I can pick apart everything when it comes to a program that tries to compete with photoshop like gimp, affinity etc... but.... with Photopea... there is only one request I have. Vectorised rendering.

In VectorPea, it renders the text amazingly! having that in PhotoPea... That's it. I'm ditching adobe 🙌

PhotoPea
![image](https://github.com/photopea/photopea/assets/16389426/52bb1026-d44b-40b0-b3db-ae2c415e493a)

VectorPea 
![image](https://github.com/photopea/photopea/assets/16389426/8124756d-161f-4644-932b-c4085fd4e264)

I would also add. I like the affinity payment model too. I'm not really a fan of a subscription service, been trapped in that for decades. I don't mind paying for updates. That's just my 2 cents.

**Comment by LukeSeers** [comment]
I do apologise, since I don't know much in this area other then using these types of software. You made good points. The one problem I have is the render quality of Photopea. Photoshop and Affinity Photo look more cleaner or polished, not sure how to describe it. 

Is there anyway to achieve similar render quality results like Photoshop and Affinity Photo?

**Comment by photopea** [comment]
Could you send me a comparison of what you mean by "polished"? So I can see it side by side with Photopea and see what is wrong.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
