### ISSUE TITLE
Lasso tool not working

### ISSUE THREAD

**Issue by nissacee** [photopea/photopea#6548]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....Click lasso tool
3. ....Use polygonal lasso tool
4. ....Draw a square

 It disappears, nothing is selected

**Comment by SetsukiFR** [comment]
Same here, on Edge, Firefox, and Firefox in safe mode.

**Comment by WoundedArm** [comment]
Same here, lasso won't work in Chrome on regular or incognito, and when I deselect and try to select again it brings back the old selection to make a great big mess.

**Comment by Nyaron** [comment]
Facing the same issue, other selection tools all seem broken except for the basic rectangle one.

**Comment by photopea** [comment]
sorry, it should be fixed now.
