### ISSUE TITLE
Rectangle Selection Selects, Ellipsis Selection Does Not

### ISSUE THREAD

**Issue by zachtango** [photopea/photopea#6549]
Your Operating System: macOS Ventura 13.4
Your Web Browser: Firefox 121.0.1 (64-bit) and Chrome 122.0.6261.129 (Official Build) (arm64)
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new project
3. Use rectangle selection and see it selects
4. Use ellipsis selection and see it doesn't select

![Recording 2024-03-18 at 13 27 07](https://github.com/photopea/photopea/assets/38231181/bb7d40ac-68e2-4368-902b-2216a82dd54d)

**Comment by camoody1** [comment]
It looks like it's all of the Select tools aside from the Rectangle Select.

**Comment by DoomedIdeas** [comment]
I'm having this same issue with every selection other than rectangle select and magic select.

**Comment by photopea** [comment]
sorry, it should be fixed now :( I am restructuring Photopea to make it ready for 16-bit graphics, and I made an error :/
