### ISSUE TITLE
State of properties panel not remembered on a per layer basis

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#655]
For example, the range drop down list in a color balance adj layer, a layer for shadows, a layer for highlights, but when switch in between layers, the range drop down list stay still

**Comment by photopea** [comment]
The color balance is defined by 9 numbers (3 for Highlights, 3 for Shadows, 3 for Midtones). We use a Dropdown + 3 sliders instead of 9 sliders.  Photopea does not remember which of these 3 values you edited before. I think it is not important - you can always switch it.
