### ISSUE TITLE
Dezgo Now Offers Background Removal

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#6550]
Just wanted to make you aware that Dezgo now offers a Background Removal tool. I thought you might want to check to see if there could be any sort of cost savings for you if you switched from your current provider.

**Comment by photopea** [comment]
Select - Remove BG in Photopea has been using Dezgo background removal since the day Dezgo released it. I even think it was you who told me about it.

**Comment by camoody1** [comment]
@photopea Jeez. I apologize. I'm turning 50 years old on Friday. I guess my memory is starting to fail me, already. 🤷🏼
