### ISSUE TITLE
SVG Exports Blank Image

### ISSUE THREAD

**Issue by zachtango** [photopea/photopea#6553]
Your Operating System: macOS Ventura 13.4
Your Web Browser: Chrome 122.0.6261.129 (Official Build) (arm64)
The problem happens in the Incognito Mode, too: yes

This must be done to see the problem

1. Go to [www.photopea.com](http://www.photopea.com/)
2. Create a new project
3. Put something on the project
4. Export to SVG and see that it exports a blank image

I assume this feature is broken now because before the #6549 fix export to SVG worked. Maybe something with that fix broke the export to SVG?

![Recording 2024-03-18 at 16 18 44](https://github.com/photopea/photopea/assets/38231181/60bc5676-443f-4299-93d1-0fce68663ffc)

**Comment by photopea** [comment]
It seems like your document contains only raster graphics (made of pixels instead of curves). You should enable "add raster graphics" during the export.

![image](https://github.com/photopea/photopea/assets/15955558/a20b31a9-fca8-44bb-b3b6-6087c6148604)
