### ISSUE TITLE
PHOTOPEA IS SUPPER SLOW ON MY PC

### ISSUE THREAD

**Issue by ebeleguys** [photopea/photopea#6555]
Your Operating System: **macOS Sonoma 14.3.1**
Your Web Browser: **Google Chrome, Firefox, Photo Desktop App**
The problem happens in the Incognito Mode, too: **Yes**

My PC specs:
**Processor: 2 GHz Quad-Core Intel Core i5
Graphics: Intel Iris Plus Graphics 1536 MB
Memory: 16 GB 3733 MHz LPDDR4X**

**Also, note that I am using a paid version. I do not have ads enabled and all my browser plugins are disabled, except for one (WalkMe plugin) which is auto-enabled by my system administrator.**

**My PeaMark:
CPU: 634
GPU: 586**

**I'm wondering why my PeaMark is this low considering the specifications of my computer. It should be way higher than this.**

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Your computer should be fast for small documents (up to 2000 x 2000 pixels), but it can be slow for large documents (4000x4000 pixels and more). In what year was your computer made?

What exactly do you do when it is slow? What is the document size, and what tool / filter do you use?

**Comment by ebeleguys** [comment]
Manufacture Date: 2020
I work with Instagram templates mostly which is 1080 by 1080.

Photopea hangs randomly sometimes. Sometimes, merely changing the text font, it just stays in "loading".  However, I notice the behavior is worse when I have a couple of layers, nothing too extreme. And, also, when using special text effects, it becomes almost unusable.

**Comment by ebeleguys** [comment]
What system spec do you recommend to optimize all of photopea's features?

**Comment by photopea** [comment]
It is hard to tell why the scolre is so low :( even my iPad has a CPU score of 1380. 

Could you share your PSD file with us (put it inside ZIP) and tell me, what should I do to see it slow?

**Comment by funing36** [comment]
I'll give my input too. I have significantly lower specks and still don't encounter many issues.

**Comment by photopea** [comment]
My CPU is AMD Ryzen 7 5700U and it gets 1000 points in PeaMark. Yours seems to be 35% slower.

Could you tell me the exact name of your CPU? I will do some research to see if it is 35% slower than mine in other benchmarks, too.

**Comment by ebeleguys** [comment]
2 GHz Quad-Core Intel Core i5

**Comment by ebeleguys** [comment]
> My CPU is AMD Ryzen 7 5700U and it gets 1000 points in PeaMark. Yours seems to be 35% slower.
> 
> Could you tell me the exact name of your CPU? I will do some research to see if it is 35% slower than mine in other benchmarks, too.

2 GHz Quad-Core Intel Core i5

**Comment by ebeleguys** [comment]
> It is hard to tell why the scolre is so low :( even my iPad has a CPU score of 1380.
> 
> Could you share your PSD file with us (put it inside ZIP) and tell me, what should I do to see it slow?

 My file size is 147 MB. I'm unable to attach it.

**Comment by photopea** [comment]
Maybe install Adobe Photoshop and try to edit your PSD in Adobe Photoshop. I dont think it will be any faster.

**Comment by ebeleguys** [comment]
Photoshop is too expensive lol....Is there any other help you can offer?

**Comment by photopea** [comment]
When you open your file, is WebGL on? You can see it at More - Use WebGL.

**Comment by seriousfreezing** [comment]
I recommend that you stop using Photopea. They will never solve this lag issue, I've already opened an issue about the slowness and they will never make a desktop version, which would solve 99% of the problems.

**Comment by photopea** [comment]
I am closing it, because the person stopped to respond.

If you think something in Photopea is "too slow", you should provide a proof that your task can be done faster on your device, e.g. using some other software. Otherwise, we can not do miracles and make a $200 devices work as a $2000 device :(

**Comment by camoody1** [comment]
@seriousfreezing I recommend you stop trying to use Photopea on a potato. The site runs smoothly on my Android phone AND my 6-year-old computer.

**Comment by seriousfreezing** [comment]
I don't think an RTX 3050 is a slam dunk compared to smartphones. The main problem is having to limit such a good application to run only in a browser, and that's a fact, even Gdevelop which runs its games in browsers lags easily.

**Comment by camoody1** [comment]
@seriousfreezing It's a free application developed and maintained by a single individual. Be thankful that it exists instead of being petty that he won't port it to be a downloadable executable. If you don't like how it's being freely presented to you, go use Krita, GIMP or Photoshop. 

Btw... It also runs fine on my niece's God awful Chromebook from school. Perhaps you should consider a reinstall of Windows if it won't run on your PC.

**Comment by photopea** [comment]
@seriousfreezing I need some evidence that you actually saw something being done by Gimp faster than by Photopea for the same image.

**Comment by seriousfreezing** [comment]
> @seriousfreezing It's a free application developed and maintained by a single individual. Be thankful that it exists instead of being petty that he won't port it to be a downloadable executable. If you don't like how it's being freely presented to you, go use Krita, GIMP or Photoshop.
> 
> Btw... It also runs fine on my niece's God awful Chromebook from school. Perhaps you should consider a reinstall of Windows if it won't run on your PC.

I'm not being annoying about this, I've been waiting for an update on the slowdown for a long time. I thought there would be an improvement, but I'm already thinking of moving all my projects to Krita, which is the closest.
I don't think it's Windows' fault, since I tested it on Linux and it gave the same result. But I have to imagine that it doesn't work well on notebooks that have 2 video cards. I'm sad that it's just one person for this whole project, it's amazing with all the community and work, but it's useless when I get my projects and use it crashing. Solution: Make the code open-source, which would make everything easier, I know it's not a push-button task.

**Comment by seriousfreezing** [comment]
https://youtu.be/lGl5X4VyIjI
I literally restarted my computer, with just the recorder and photopea. And I can't activate the graphics acceleration function because the notebook company itself recommends that I leave it deactivated; if I activate it, it bugs all the screens.

**Comment by photopea** [comment]
So you can not apply layer styles to a layer? As it never happened to me, could you share it your PSD with us?

**Comment by seriousfreezing** [comment]
Come on, if I want to do this on just one layer, will I have to limit it because of the program itself?
[Serious_chaos(2).zip](https://github.com/photopea/photopea/files/14795421/Serious_chaos.2.zip)

**Comment by seriousfreezing** [comment]
In fact, this is easy to do not only when applying styles to layers. But I can't remember now in which other situations it happened.

**Comment by photopea** [comment]
Your PSD file has a very strange structure. I think it was not made with Photopea or with Adobe Photoshop, but with some other program. Because of this strange structure, Photopea froze when you tried to add a Pattern Overlay layer style.

I modified Photopea a bit and it should handle your PSD now.

**Comment by seriousfreezing** [comment]
So now should I worry or ask the designer to use another program that has a better system for .psd? Or have I got it wrong?

**Comment by photopea** [comment]
ok

**Comment by camoody1** [comment]
@seriousfreezing You're also using ad blockers. So, you're here complaining to the dev about his application being slow and wanting him to fix it while blocking any ad revenue that he might get from you using it. That's pretty crappy. You should probably consider disabling all of your browser extensions to determine which one is affecting Photopea. That could be causing you performance issues, also.

**Comment by seriousfreezing** [comment]
@camoody1 Ok ok, if the ads didn't appear when recording, it doesn't mean I'm using AdBlocker. Whenever I use Photopea, sometimes it won't let me open a project after opening Krita, or sometimes it won't even show ads. When I use Photopea, I use it in a pure sandbox with Chromium and nothing else.
