### ISSUE TITLE
[Feature Request] Click selected tool to open submenu

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#6557]
Currently we have to right click or long press to open the submenu, which is inconvenient for touch and trackpad. 

It is a common design that click selected item to perform action different from clicking un-selected item. I think the toolbar in photopea can do the same. 

With this feature, selecting a tool in submenu will be much quickly.

**Comment by camoody1** [comment]
I don't understand how you actually want it to work, but I personally don't see a problem with how the toolbar works currently. 🤷🏼

**Comment by camoody1** [comment]
@nothingshiru I use my phone with both my finger and my stylus. And on my PC, I never right-click on a tool item to change the tool. I always just long-click it. Maybe if you better explained how you preferred it to work, it might make more sense to me. But as it exists currently, I really don't have any issues. 🤷🏼

**Comment by camoody1** [comment]
> @camoody1 I made a demo in Figma. [Check it](https://www.figma.com/proto/04FudwERWHYjzoYiXOe4c6)

Ah yes. I see, now. I agree. That would be a nice change. 👍🏼

**Comment by photopea** [comment]
I think the current mechanism is better

If you want to switch to a brush tool, you can click it once, or as many times you want.

In your mechanism, you have to click it an even number of times. So if you accidentally click twice, you have to click again to hide a menu.
