### ISSUE TITLE
[Feature Request]  Mirror/Symmetry line tool

### ISSUE THREAD

**Issue by PebbleCat-Studios** [photopea/photopea#6559]
Pop post?
--------

> Apparently, this is a popular request, and I don't see why this isn't implemented already. From what I saw, there 3 posts mentioning this feature, [this post](https://github.com/photopea/photopea/issues/5224#issue-1516720446) along with the 2 linked within it. 

How I got here.
--------

> I was looking for this tool when I wanted to start making a character that I wanted symmetrical, witch to no avail, I browsed the internet for a tutorial to find out that it doesn't exist. 

My proposal.
--------
> Here's what I propose, the mirror tool can be a feature that can be accessed by the "image" tab or the "filters" tab, witch, when active, would show on the effected layer, per usual, and you can apply it when your done to make it one whole peace. It'll reflect over the x-axis, y-axis, or both, depending on what the user wants. It'll reflect whatever you draw automatically without duplicating and reflecting. You can also add a feature within it that you can set the mirrored part's opacity lower to see what's behind it.

What I think Photopea thinks...
----------
> From what I saw, Photopea thinks that it's more of a toy and not a feature that needs to be added, stating that you can just duplicate an object(s) flip it horizontally and move it to the preferred location. With some use cases, I'd agree and understand that, but because Photopea is fairly popular; regarding the already mind-blowing quality of its design and functionality; I think me and a decent amount of people were looking for this tool at one point.

More Notes
--------
> In general, Photopea 's workaround "dupe and swupe"  isn't a practical use, mainly because I'd have to take time to match the detail, then "dupe and swupe" just to see if it looks good on the other side. I'd prefer if I could see what I'm doing live so I can easily edit it and see anything that's messed up. I can find this useful also with simple character illustrations, general digital art, partial creation, like a diamond or a heart (very basic shapes can turn into something beautiful), and much more.

Not trying to be aggressive with Photopea.
---------
> Photopea is already packed with tons of features, and I feel like something like a mirror filter/tool would slot in perfectly with the already existing features.

Lol
---------
> It would also be a little bit fun in the beginning to toy around with. 😏

Quick representation:
----------

> Here's a couple ideas. (Please note that this was done quickly and in no way this is "professional".)

![Screenshot 2024-01-30 175654 (1)](https://github.com/photopea/photopea/assets/146106615/4379fdc7-422d-48f5-97b6-7932ce05d16c)
![Screenshot 2024-01-30 175715 (1)](https://github.com/photopea/photopea/assets/146106615/df0b8e83-8f80-4b4b-bf1b-7596d2d538e9)
![Screenshot 2024-01-30 180924 (1)](https://github.com/photopea/photopea/assets/146106615/2b8baacf-2c19-48ca-954a-ff48f32d7b29)

**Comment by photopea** [comment]
Are you sure this would not be enough for you? https://github.com/photopea/photopea/issues/5224  If yes, discuss it there, we dont need to start a new issue.

**Comment by photopea** [comment]
I have implemented it

https://github.com/photopea/photopea/assets/15955558/77f4d4d5-887c-41fe-9d7b-86d0358d520a
