### ISSUE TITLE
Text no longer wraps back in a text box

### ISSUE THREAD

**Issue by brolifen** [photopea/photopea#6560]
![image](https://github.com/photopea/photopea/assets/20615514/5c6132f2-f9b0-4e3e-902e-1e7c3a7a5e38)

**Comment by photopea** [comment]
Photopea can not break words into several parts. If you type "Hello", but your box is one pixel wide, most of the text will be outside the box.

**Comment by brolifen** [comment]
This basic functionality which is also present in notepad since Windows XP or before is not possible in Photopea? Wow great tool guys.

**Comment by photopea** [comment]
please, do not lie to us. It is not present in Notepad. When you type in Notepad, the text gets outside the screen
![image (2)](https://github.com/photopea/photopea/assets/15955558/01dcf7d4-c90a-44c5-952d-089e7211243f)

**Comment by camoody1** [comment]
@photopea If you click on the View menu, there should be a "Word Wrap" option that enables the functionality.

**Comment by brolifen** [comment]
I was not lieing and I may have been too harsh previously. But please this was so frustrating to deal with, at least make it a toggle or something so everything can stay in the text box or else what is the point of drawing out a box to begin with.

**Comment by brolifen** [comment]
I was not lieing and I may have been too harsh previously. But please this was so frustrating to deal with, at least make it a toggle or something so everything can stay in the text box or else what is the point of drawing out a box to begin with.

**Comment by photopea** [comment]
Why do you say "no longer"? This works the same for the past 10 years.

**Comment by photopea** [comment]
In practice, words are not so long as in your example, so they are broken to other lines.

*** a word is a sequence of characters with no spaces
