### ISSUE TITLE
Photoshop Tool does not work

### ISSUE THREAD

**Issue by carreraycarrera** [photopea/photopea#6563]
Your Operating System: IOS
Your Web Browser: Google Chrome

Hello! Suddenly, a couple of days ago, the Photoshop tool stopped working. When I go to the "File" - "Open" menu and load a photo for processing, nothing happens and the screen remains black, that is, the document does not load. Before this everything worked great. What could be the problem?
<img width="1375" alt="Screenshot 2024-03-20 at 10 06 01" src="https://github.com/photopea/photopea/assets/164156559/c99ccd75-2d43-43f2-b6e1-b15c4cab28d7">

**Comment by photopea** [comment]
You should use Photopea at www.Photopea.com
