### ISSUE TITLE
Text box's size doesn't save

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6565]
Your Operating System: ChromeOS
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open this PSD [Plantilla Carta Blanca.zip](https://github.com/photopea/photopea/files/14716974/Plantilla.Carta.Blanca.zip)
3. If it is not already set, put DPI to 100cm/pixel
4. Set the size of th
e text box to 50 x 65 and click OK.
5. Check again the size of the text box, it should be 49.9 x 65.1 again

[Screen recording 2024-03-22 00.36.28.webm](https://github.com/photopea/photopea/assets/11801254/348916ef-b8eb-41d4-b525-9b35ccfceaae)

**Comment by photopea** [comment]
It should be fixed now, you should be able to resize the box to any size.

Note, that the Text tool is still snapped to whole pixels. On the other hand, the Direct Select tool has a switch at the top to disable snapping to whole pixels.
