### ISSUE TITLE
can't resize image

### ISSUE THREAD

**Issue by Podognon** [photopea/photopea#6568]
Your Operating System: windows 11
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: 

**This must be done to see the problem**
1. Go to www.photopea.com

idk how this happen, but at random moment while working, I can't resize images, right click doesn't work and some keyboard shortcuts doesn't work (like "del" to delete a layer). Sometimes i can use the application for a while before this happen. Fortunately i can save the psd file

**Comment by photopea** [comment]
What should I do to see it happen? Do you have any browser extensions which have permissions to modify Photopea? Did you try to turn them off?

**Comment by Podognon** [comment]
i tried to turn off the browser extensions, and the bug doesn't seems to appear

**Comment by photopea** [comment]
Could you tell me what exentsion was breaking this feature?

**Comment by Podognon** [comment]
it was adblock360

**Comment by photopea** [comment]
ok, thanks!
