### ISSUE TITLE
files cannot be opened

### ISSUE THREAD

**Issue by Katya-pixel** [photopea/photopea#6569]
Your Operating System: Sonoma 14.2.1
Your Web Browser: Safari 17.2.1
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to [www.photopea.com](https://online-fotoshop.ru)
2. Click File -> Open 
3. Select the file (.jpg or .psd)
4. Click Upload
5. Nothing happens

**Comment by photopea** [comment]
I have only Mac OS Monterrey, and when I open JPG and PSD files, everything works fine.

Did you try to restart your browser? Could you record a short video of what exactly you are doing?

**Comment by Katya-pixel** [comment]
I'm sorry. I made a mistake in the bug report 
Step 1 must be 
1. Go to https://online-fotoshop.ru

I've tried restart my browser and i've tried use another browser - Google Chrome.
Problem still exists

Also I have the same problem at iOS Version 17.3

 short videos attached

https://github.com/photopea/photopea/assets/127355800/2b93f9c1-60fd-441b-be91-25fe26029f6d


https://github.com/photopea/photopea/assets/127355800/090e4be0-3180-40af-890e-c8126e3cc5f8

**Comment by photopea** [comment]
I dont know what is https://online-fotoshop.ru/ . You should ask the owner about the problem with that website. 

Our website is www.photopea.com, did you try to use www.photopea.com instead?

**Comment by Katya-pixel** [comment]
this is strange because when I clicked report a problem I was redirected to gethub photopea

Not yet, but I'll try
Thank you!

**Comment by photopea** [comment]
I think everything should work at www.photopea.com
