### ISSUE TITLE
Ad problem

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#657]
Hi Ivan,
I showed Photopea to my friend and he didn't see advertising because exception. See and I recommend implementing error handling [sentry.io](https://sentry.io/welcome/), again: D

![image 8](https://user-images.githubusercontent.com/3184228/39047310-1f0610e0-44a2-11e8-8872-f4a547df72f6.png)

**Comment by photopea** [comment]
Hi, I think it is a problem in Google Ads. It never happened to me :( I think we can not fix it.

**Comment by landsman** [comment]
I think that you can implement try and catch for ads, or?

**Comment by photopea** [comment]
This happened in an iframe, you can not control what happens in iframe.
