### ISSUE TITLE
cunia font fails to load

### ISSUE THREAD

**Issue by blowsy** [photopea/photopea#6570]
Your Operating System: Windows 10
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Install the font "Cunia" from [1001fonts](https://www.1001fonts.com/cunia-font.html) or fontsquirrel
3. Create a text box and Load the font
4. Font does not appear in list, tried on incognito and firefox

I downloaded a random font and loaded it in the same window, worked fine. I used to use Cunia font on photopea in 2022/2023, not sure why the same TTF is not working anymore.

**Comment by photopea** [comment]
When I load this font into Photopea, it is called "Bold" and it is located at the end of the font list.

**Comment by photopea** [comment]
![image](https://github.com/photopea/photopea/assets/15955558/21b46ed2-19f3-435e-bc50-06dc60cb2b83)

**Comment by photopea** [comment]
![image (1)](https://github.com/photopea/photopea/assets/15955558/86341a44-ba3c-4f37-b867-449b0b68cc41)

**Comment by blowsy** [comment]
Thank you, although I recall it being referred to as Cunia in the font selector when I last used it a year ago. Also, there was a pop up "Font Cunia loaded" which was a little misleading in this case. I think a "recently added" section would be beneficial.

**Comment by blowsy** [comment]
The font name appears correctly as "Cunia" in the Windows fonts list and Photopea correctly identifies it as "Cunia" in the popup. I think it is confusing for it to not be indexed as such in the font selector.
![Screenshot (4801)](https://github.com/photopea/photopea/assets/63466845/08d17c92-9230-495d-a53c-63e2191eab40)

**Comment by photopea** [comment]
This font was made by alejobergmann@gmail.com so maybe ask him to fix it. Or maybe he already made a new version of this font.
