### ISSUE TITLE
Stroke hardness is too high in Photopea

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#6571]
I compared the strokes created with 20px, 1% space, default brush in different hardness, from a same path. I find that 100% hardness in photoshop is similar to 75% in photopea. 

100% in Photoshop(above) vs. 100% in Photopea(below)
![屏幕截图 2024-03-23 212556](https://github.com/photopea/photopea/assets/79258245/d4614be8-4192-4194-a513-a87e7fb2444f)

100% in Photoshop(above) vs. 75% in Photopea(below)
![屏幕截图 2024-03-23 212628](https://github.com/photopea/photopea/assets/79258245/1b74968f-32ff-47a8-9652-8a05f14375fe)

Hardness comparison(Photoshop in left, Photopea in right), From top to bottom, 100%, 75%, 50%, 25%, 0%
![stroke comparison](https://github.com/photopea/photopea/assets/79258245/5e7ba4e5-45bb-4e01-b03a-5d2c0fed7eb1)
You can also check it in this [psd](https://www.photopea.com/#iDVERheJa)

I once reported that Photopea's brushes are not as smooth as Photoshop's brushes. This could be the reason. And I'm also wondering if it affect the smoothness of text.

**Comment by photopea** [comment]
I think it is visible already when you draw a single point with a brush (one click), right? There is no need to draw a stroke. If the single point looked the same, the stroke would also look the same.

This is not related to text rendering.

**Comment by photopea** [comment]
I think in Photoshop, there is a always a gaussian blur of 1 pixel added to each brush.

**Comment by photopea** [comment]
I dont know how to fix it :(
