### ISSUE TITLE
[Feature Request] Add Lossless Optimization to PNG Export

### ISSUE THREAD

**Issue by MilesFarber** [photopea/photopea#6572]
Your Operating System: Windows 10
Your Web Browser: Edge
The problem happens in the Incognito Mode, too: Yes

![PSMD Map](https://github.com/photopea/photopea/assets/24918282/459ae406-e390-449e-b1fa-f17dc1925e0e)
This, is a map.
"Dear god..."
There's more.
"No..."

When opened in Photopea, and exported again as PNG, the file size skyrockets from 5'484'740 bytes, to 7'856'128 bytes. Here's the exported file:

![PSMD Map Photopea](https://github.com/photopea/photopea/assets/24918282/851bf925-1b23-41c8-b50b-3ba0d16c58b5)

The solution is to add an option to losslessly optimize the PNG before downloading it. A good example is https://github.com/hadrien-psydk/pngoptimizer . This program is GPL and takes 1 second to losslessly optimize a 2048x1536 file. The output is this 4'741'522 bytes file:

![PSMD Map Optimized](https://github.com/photopea/photopea/assets/24918282/9b3e2bf6-9916-44af-9030-2ff2f9ea6353)

Steps to reproduce:
1. Go to www.photopea.com
2. Open the **first** map in this thread, the 5'484'740 bytes one.
3. Try to export as PNG
4. The file size will always stay above 7.5 MB. The only way to reduce it is to set Quality to 99% or below, which is lossy.

**Comment by photopea** [comment]
Hey, it should work better now, thanks for pointing it out! Now, you get 5,195,678 B. But the compression takes 1.4 sec instead of 0.4 sec (on my computer).

![316253997-459ae406-e390-449e-b1fa-f17dc1925e0e](https://github.com/photopea/photopea/assets/15955558/e36766f9-e051-40a7-9fc9-734dfb87daf7)

**Comment by photopea** [comment]
I can make Photopea produce a 4,996,710 B file of your image (still no data loss), but it takes 6 seconds. I can add a "even smaller file" checkbox to the PNG export options. Would you like to have it? 

It would be 4% smaller, taking 4x more time.

**Comment by MilesFarber** [comment]
![image](https://github.com/photopea/photopea/assets/24918282/c2283708-d89f-4471-818c-130f5ae1983a)
![image](https://github.com/photopea/photopea/assets/24918282/1830a60b-4cf4-4854-a447-baed19e0be28)
Maybe a compression slider that goes from 1 to 9 like Krita and Gimp?

> I can make Photopea produce a 4,996,710 B file of your image (still no data loss), but it takes 6 seconds. I can add a "even smaller file" checkbox to the PNG export options. Would you like to have it?
> 
> It would be 4% smaller, taking 4x more time.

**Comment by photopea** [comment]
Can Krita or Gimp give you a smaller PNG file than Photopea?

**Comment by MilesFarber** [comment]
![image](https://github.com/photopea/photopea/assets/24918282/f611b19a-a250-4cf5-a18e-2ceef64e3be6)
![image](https://github.com/photopea/photopea/assets/24918282/5e11c74d-af71-4e62-8ea6-5897b188e882)
# Nani!?

**Comment by MilesFarber** [comment]
![image](https://github.com/photopea/photopea/assets/24918282/b8351061-9ff3-4d38-98bc-c35276b5e045)
Gimp's slightly better but it's VERY slow, like 30 whole seconds

**Comment by photopea** [comment]
Is it worth it to wait 30 seconds to get a 7% smaller PNG file?

**Comment by MilesFarber** [comment]
Maybe add Faster Render / Smaller File at the ends of the slider?

**Comment by photopea** [comment]
What is a Faster Render?

**Comment by MilesFarber** [comment]
As in tell the user that the slider lets them choose between saving the PNG file faster or making a smoler PNG file

**Comment by photopea** [comment]
The current Quality slider allows making smaller files with lower quality, but it always takes the same time.
