### ISSUE TITLE
I can't duplicate nor export projects

### ISSUE THREAD

**Issue by crdgans** [photopea/photopea#6573]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Start editing 
3. Can't use the function "Duplicate into"
4. Can't use the function "Export as"

**Comment by photopea** [comment]
No matter what I do, these two features always work in my case :(

Why didn't you try it in the Incognito mode, it takes only 7 seconds?

**Comment by crdgans** [comment]
> No matter what I do, these two features always work in my case :(
> 
> Why didn't you try it in the Incognito mode, it takes only 7 seconds?

i have seen people recommending that but idk how to activate incognito mode 😓

**Comment by photopea** [comment]
I have to close it because of lack of details.
