### ISSUE TITLE
Feature Request: Unmake smart object

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6574]
In photoshop there is an option to convert a smart object layer to a folder with its content, it's called "Convert to layers"

Here you can check:
https://youtu.be/dDciEKi0Cps?t=190&si=WNfudeWZg8ShcsJg

It will be good to have this. I have faced this issue multiple times and i have to open the smart object and duplicate its contents to the original canvas. And then adjusting the position and size.

**Comment by TheRadicalDreamer** [comment]
It is possible to have this feature in Photopea?

**Comment by photopea** [comment]
I have added this feature to Layer - Smart Object - Convert to Layers

**Comment by TheRadicalDreamer** [comment]
![a1348c566154d88d3dbbc602a9f8f9a6](https://github.com/photopea/photopea/assets/11801254/84239d21-44f2-46dd-856f-a53560f0e5e4)
