### ISSUE TITLE
frozen screen and many bug since I use the premium version ( no one before ... ) 

### ISSUE THREAD

**Issue by loraine19** [photopea/photopea#6575]
Chromebook Intel Core 5 :
Chrome:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Foozen screen since in work up to 5 minute 
3. ....
4. ....

**Comment by photopea** [comment]
I think this might be your problem: https://www.photopea.com/tuts/photopea-opens-up-old-files/

In short, you use browser extensions, which break Photopea, and you should clear the website data to fix it. Or use it in the Incognito mode, which should always work (as your browser extensions can not interfere with Photopea in Incognito).

**Comment by photopea** [comment]
Could you record a short video of how you open Photopea and make it freeze?

**Comment by photopea** [comment]
I have to close it because the person did not reply.
