### ISSUE TITLE
The font is forced to change.

### ISSUE THREAD

**Issue by Elitebeatagents** [photopea/photopea#6576]
Your Operating System: Windows 11
Your Web Browser: Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. I want to use a specific font that I downloaded from the internet while using Photopia, but I keep getting forced to replace it with the 'NotoSans KR' font, is there any solution?

**Comment by camoody1** [comment]
It would be helpful to share which font it is and where you got it so the dev might have a better opportunity to assist you.

**Comment by Elitebeatagents** [comment]
'Maplestory' fonts. I downloaded it here. 

https://freefonts.kr/fonts/maplestory-otf-light

**Comment by photopea** [comment]
What exactly are you typing? If your font does not contain a necessary character (while typing), you are switched to a substitute font.

You can always select any part of your text and set the font of this selected part.

**Comment by photopea** [comment]
I think it is fixed now. 

You can always select any part of your text and set the font of this selected part.
