### ISSUE TITLE
Photopea detecting an Add-Block even though it dose not exist

### ISSUE THREAD

**Issue by Avishka-Perera** [photopea/photopea#6577]
Your Operating System: Ubuntu 22
Your Web Browser: Brave (Brave Browser 122.1.63.169)
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. That's all

![Photopea Add-Block detected](https://github.com/photopea/photopea/assets/74392492/b7205e99-b05d-413d-a8b7-493dbc0de790)
![Installed Extensions](https://github.com/photopea/photopea/assets/74392492/35213a82-58f8-41d3-ae26-e911e3bb4c0f)

Thanks!

**Comment by photopea** [comment]
Brave always blocks ads, see https://www.photopea.com/tuts/photopea-says-i-am-blocking-ads-but-i-am-not/ . You should report it to the creators of Brave.
