### ISSUE TITLE
Pasting on Raster Mask creates new layer copy 

### ISSUE THREAD

**Issue by ForgottenPixels** [photopea/photopea#6578]
Your Operating System: Windows 10
Your Web Browser: Opera GX
The problem happens in the Incognito Mode, too: Yep

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open an image
3. Add Raster Mask
4. Open black and white texture
5. Copy black and white texture
6. Alt + Click Raster Mask
7. Copy texture to Raster Mask
8. Copy is placed on new layer not raster mask

Note: I was able to get it to work once but not again.

**Comment by photopea** [comment]
When the raster mask is selected in the layers panel, and I paste some content, it is pasted into the mask. But I do it in Chrome, not in Opera.

Can you try it in Chrome to see if it works differently?

**Comment by ForgottenPixels** [comment]
For some reason its started working. Idk what happened to make it work (I haven't done anything different).

**Comment by photopea** [comment]
ok
