### ISSUE TITLE
Double click slider handle for set it to default

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#658]
This is nice to have for all sliders that appear in properties panel

**Comment by photopea** [comment]
It was implemented. Double click on the slider will set it to the "middle" value. Thanks for such a great idea!

**Comment by photopea** [comment]
Which sliders did you click? It works only for sliders, which do not grow exponentially.

**Comment by hgs54371** [comment]
I found it's firefox specific, in safari it works, both on mac
