### ISSUE TITLE
move tool bug

### ISSUE THREAD

**Issue by pydev16** [photopea/photopea#6580]
Your Operating System: bodhi linux
Your Web Browser: brave
The problem happens in the Incognito Mode, too:  no

**This must be done to see the problem**
1. Go to www.photopea.com
2. create an rectangle 
3. set border radius to 50
4. use move tool to move the object
 when ever i try to move the object it just duplicate's it for no reason making it difficult to edit

**Comment by camoody1** [comment]
Duplication with the Moving Tool occurs when you hold the ALT key down while clicking to move. Are you holding your ALT ket when you do this? Could you ALT key be stuck?

**Comment by photopea** [comment]
I will close it because the author did not reply.
