### ISSUE TITLE
Setting a font family by script has inconsistent loading

### ISSUE THREAD

**Issue by shcott** [photopea/photopea#6581]
I'm trying to write a script to automate the process of resizing an image, adding a white background layer, and adding a text layer at the bottom. I've got everything working except when setting the font family to the font I want, "Indie Flower", it doesn't load properly, and defaults to DeJaVu.

I tried a couple other different fonts in the script and most of them don't work, but some random ones seem to work, for example 2Dumb and Airstream. I'm not sure if this logic is sound, but it seems like the earlier fonts that are one-word names are working.

This is the script:
```
function addWhiteBackgroundLayer(document) {
  // Add bgLayer and move to back
  const bgLayer = document.artLayers.add();
  bgLayer.move(document.artLayers[document.artLayers.length - 1], ElementPlacement.PLACEAFTER);
  document.activeLayer = bgLayer;

  // Fill the layer with white color
  const fillColorWhite = new SolidColor();
  fillColorWhite.rgb.red = 255;
  fillColorWhite.rgb.green = 255;
  fillColorWhite.rgb.blue = 255;
  document.selection.fill(fillColorWhite);

  return bgLayer
}

function addText(document, imageLayer) {
  document.activeLayer = imageLayer;

  const textLayer = document.artLayers.add();
  textLayer.kind = LayerKind.TEXT;

  const textItem = textLayer.textItem
  textItem.contents = "Your Text Here";
  textItem.position = [document.width / 2, document.height - 80]; // Bottom center position
  textItem.size = 150; // Font size
  textItem.font = "Indie Flower"; // Font family
  textItem.fontStyle = "Regular"; // Regular font style
  textItem.color.rgb.hexValue = "000000"; // Black color
  textItem.justification = Justification.CENTER; // Center aligned text

  return textLayer
}

const document = app.activeDocument;
const imageLayer = document.artLayers[0]

document.resizeCanvas(1200, 1200, AnchorPosition.TOPCENTER);
const bgLayer = addWhiteBackgroundLayer(document)
const textLayer = addText(document, imageLayer)
```

**Comment by photopea** [comment]
You should find out what is the Postscript Name of your font. If you select a specific font in Photopea, and you "hover" your mouse over the font family button, you will see the Postscript Name. Postscript name never contains any spaces.

![image](https://github.com/photopea/photopea/assets/15955558/69bfd6d8-ba0f-4a50-afc4-d9bf1c8db68f)

**Comment by shcott** [comment]
Perfect, thank you!
