### ISSUE TITLE
Can't size anything

### ISSUE THREAD

**Issue by RobertBloxs** [photopea/photopea#6582]
I can't size anything! I can't size my text, arrow, and everything!

**Comment by photopea** [comment]
I do not understand. Is the "size" a verb? I thought it is a noun.

**Comment by Thomascorriasss** [comment]
Bonjour, moi aussi j'ai ce problème. Le texte ne pas peut être redimensionnez ni pivoter. Pouvez faire quelque chose pour régler cela ?

**Comment by 3laws** [comment]
> I do not understand. Is the "size" a verb? I thought it is a noun.

Resize. I came to report same bug. Edit > Transform > Scale. Not working. Firefox 124.0.1.

**Comment by photopea** [comment]
I just tried to press Edit - Transform - Scale, and I can resize the layer. Could you show us a screenshot of your whole screen? Maybe it could give us some clue.

There were 200 000 people using Photopea in Firefox in the last 24 hours, so it is very strange that only you are reporting it.

**Comment by Sahio56** [comment]
I also have that issue - scale doesn't work, any Transform for that matter

Using Chrome Version 123.0.6312.123 (Official Build) (64-bit) - works with Incognito tab. 

Also, sometimes the keyboards short cuts don't work (delete, for example)

Thank you

**Comment by photopea** [comment]
If it works in Incognito, it means your browser extensions are breaking Photopea.
