### ISSUE TITLE
photopea please add a change background

### ISSUE THREAD

**Issue by lolfals** [photopea/photopea#6584]
i cant see the images that are white please add the background photopea please

**Comment by photopea** [comment]
what does it mean?

**Comment by MichalSZZ** [comment]
I don't think the author wants the feature that I have in my head but...

in Photoshop you can click with the Right Mouse Button outside the project canvas, and set the other project "window" color.
I use it sometimes when I work with artboard with layers, to see how the artboards with banners will be viewed on the white websites. You can set there any color you want or choose from predefined.

And in Photoshop's preferences, you can also hide the border of the artboard/canvas and the canvas shadow. When you do that - you can simulate the white banners on a white website - how they will look like (Google has guidelines for GDN banners - white banners should have 1px border to show where the banner's creation ends and the website starts - it avoids the misclicks)

**Comment by photopea** [comment]
I have to close it because of lack of details :(
