### ISSUE TITLE
Impossible to mask effect section 

### ISSUE THREAD

**Issue by loraine19** [photopea/photopea#6586]
Chrome book 
Chome OS 
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Impossible to mask the effect section of individual layer 
3. du to the size of the handle 
4. the handle is com on  the button  
5
6. ....

**Comment by photopea** [comment]
Layer styles are generated on the unmasked content of the layer.

Maybe put your layer into a folder and add a mask to that folder.

**Comment by photopea** [comment]
I think it is fixed now.
