### ISSUE TITLE
"Disabling WebGL"

### ISSUE THREAD

**Issue by onenok** [photopea/photopea#6587]
Your Operating System: Win 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. maybe open ~100 .bmp
3. turn to other tabs
4. turn back
5. maybe will happen

![image](https://github.com/photopea/photopea/assets/83169133/b88d0b10-bf5c-491b-94a9-c6865a7f3026)
![image](https://github.com/photopea/photopea/assets/83169133/e13659fc-cbe0-464f-8505-20f6ed6e0f27)

**Comment by photopea** [comment]
The WebGL is disabled when your image is larger than the WebGL texture limit of your device. It is enough to open just one image, which is large enough.
