### ISSUE TITLE
Can't resize anything PLEASE FIX !

### ISSUE THREAD

**Issue by szkma27** [photopea/photopea#6588]
(I repoen a ticket) Hi Photopea ! I can't resize anything i recorded a video to show you for informations i have : 
OS : Windows11
Chrome
I installed "Application" version of Photopea
So the link of the video : 

https://github.com/photopea/photopea/assets/163778659/0d68da30-6025-45bc-9465-7960b296451c

If you can fix that would be very good.

**Comment by photopea** [comment]
No matter what I do, resizing always works in my case :(

Could you try it in the Incognito mode of your web browser at www.photopea.com?

**Comment by szkma27** [comment]
> No matter what I do, resizing always works in my case :(
> 
> Could you try it in the Incognito mode of your web browser at [www.photopea.com](http://www.photopea.com)?

So it works but is that mean i have to redownlaod all my fonts? And i have an ad blocker i'll try to desactivte it then to try if that  works

**Comment by szkma27** [comment]
> Could you click this button and show us, what browser extensions you are using?

Sure ! : 
![image](https://github.com/photopea/photopea/assets/163778659/34289d32-ec00-456f-b4fd-510f17410ef5)

**Comment by photopea** [comment]
Could you temporatily disable these five extensions, reload Photopea (without them) and try to resize again?

**Comment by szkma27** [comment]
> Could you temporatily disable these five extensions, reload Photopea (without them) and try to resize again?

Yeah sure ! I disable all extensions it's seem i can resize now thanks ! If i have any other problem i'll tell you !

**Comment by szkma27** [comment]
But ... I can't see the down bar 
![image](https://github.com/photopea/photopea/assets/163778659/163c3262-f225-4c0c-8be1-88f369b1fa84)

**Comment by photopea** [comment]
It was probably caused by just one extension. You can enable them back, one by one, until you find the one which breaks Photopea.
