### ISSUE TITLE
Content Aware Scale on a PNG image.

### ISSUE THREAD

**Issue by bluep55** [photopea/photopea#6589]
When trying to scale a PNG image using Content Aware Scale, the surrounding transparent area loses it's transparency and becomes black.
Adjusting the size, choosing an Alpha channel or clicking on the Chain link causes this.
I tried this in Photoshop and no such problem.
Image just used for demonstration to show an example of what happens.
I tried it in Chrome, Chrome installed, Firefox and Edge, with all browser extensions disabled with same results.

![Content Aware Scale](https://github.com/photopea/photopea/assets/118609932/3c27ae29-77d2-42b7-ae9d-81649936b590)

**Comment by TheRadicalDreamer** [comment]
This still happens.

The alpha channel of the PNG image that has been resized with Content aware scale, goes black. And remains black after the edit.

![image](https://github.com/user-attachments/assets/20572671-e249-48ed-b23d-00236dd2ef7c)

**Comment by photopea** [comment]
it should be fixed now.

**Comment by bluep55** [comment]
👍
