### ISSUE TITLE
Fixed size/ratio rec shape/selection creation not snap-able on all edges

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#659]
Click to create the fixed size rec shape and drag to position it, but at this stage it's not snap-able on the top and left edge 

Also Fixed size rec selection creation not snap-able on the top edge

And Both Fixed ratio rec shape/selection creation only snap-able on the right edge

**Comment by photopea** [comment]
You can create your shape anywhere and then drag it to a new position.

**Comment by hgs54371** [comment]
This is an Improvement request, not a workaround request,
Everything has workaround, now what's the point of Improvement

**Comment by photopea** [comment]
Ok I made snapping work for drawing fixed-size shapes.
