### ISSUE TITLE
copy merged hotkey is order specific

### ISSUE THREAD

**Issue by antrobot1234** [photopea/photopea#6591]
Your Operating System: windows
Your Web Browser: brave
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. load an image with multiple layers
3. use the copy merged hotkey (ctrl + shift + c)
4. if pressed in the order shift -> ctrl -> c it works fine, but pressing them in the order ctrl -> shift -> c causes the copied content to just use the regular copy method instead of the copy merged method.

**Comment by photopea** [comment]
In my case, it works correctly, no matter if I press Ctrl+Shift+C or Shift+Ctrl+C. I tried it in Brave, too. Are you sure about your report?

**Comment by photopea** [comment]
I have to close it because of lack of details.
