### ISSUE TITLE
 If I open certain psds they show up as black

### ISSUE THREAD

**Issue by benitheworld** [photopea/photopea#6595]
I use an ipad safari
The problem happens in the Incognito Mode, too
 If I open certain psds they show up as black. 
I have used some of them before and this never happened?

**Comment by benitheworld** [comment]
[
![IMG_6333](https://github.com/photopea/photopea/assets/165364299/509569da-cf14-43a9-98d3-e08f771c811d)

**Comment by photopea** [comment]
Could you share one of your PSDs here with us? You can put it into a ZIP.

**Comment by LauraMendes99** [comment]
The same is happing to me, where most of my PSDs show up as black.

**Comment by photopea** [comment]
It should be fixed now. Could you try it again?

**Comment by photopea** [comment]
Could you open this website and show me a screenshot of what you see there? https://webglreport.com/?v=2

**Comment by benitheworld** [comment]
hi i fixed it by turning off webgl!

**Comment by photopea** [comment]
Could you try it again? It should work even without changing any settings.

**Comment by benitheworld** [comment]
i did and it worked! thank you!
