### ISSUE TITLE
Photopea not working for me

### ISSUE THREAD

**Issue by izzwsd** [photopea/photopea#6596]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com

Hello, this happened very recently, i was about to open photopea and edit. I clicked on the raw camera filter and did some changes, but i was unable to click the "OK" to apply my work. And i experienced my other issues, i tried everything from incognito to changing web browsers. I really need help on how to solve this problem so i  can comeback to normally editing in photopea.

Thanks

**Comment by photopea** [comment]
I am sorry, it should be fixed now.
