### ISSUE TITLE
The opened files are black

### ISSUE THREAD

**Issue by Macelloni** [photopea/photopea#6598]
I use a windows 10 PC. i have the same problem with Google Chrome and Edge.
If I open a file psds or jpg they show up as black.
I have used some of them before and this never happened.
i'm attacching one of one file.
![img484 prova](https://github.com/photopea/photopea/assets/165380013/34f3ce00-e719-4dc2-93fa-23bc2aafe38d)

**Comment by photopea** [comment]
Could you try it again in the Incognito mode?

**Comment by photopea** [comment]
It should be fixed now, could you try it again? Clear your cache using Shift+F5.
