### ISSUE TITLE
brightness/contrast glitch

### ISSUE THREAD

**Issue by treeman12** [photopea/photopea#6599]
whenever I use camera raw the filter, Afterwards my brightness/contrast will make the picture invisible this also happened with the exposure adjustment too after using camera raw.

**Comment by photopea** [comment]
Does it happen in the Incognito mode, too? Or could you try to clear your cache memory?

**Comment by photopea** [comment]
It should be fixed now. Could you hard-refresh Photopea or try it in the Incognito mode?

**Comment by treeman12** [comment]
> Does it happen in the Incognito mode, too? Or could you try to clear your cache memory?

its fixed now idk if it was a glitch or not but its working now thankfully

**Comment by photopea** [comment]
ok
