### ISSUE TITLE
Display Full Font Name Used in PSD

### ISSUE THREAD

**Issue by evantobin** [photopea/photopea#66]
I use this so developers can view PSD mockups without having photoshop.

With that in mind it would be useful if there was a way to see the current full font name as font names are cut off in the top bar if they are too long.

**Comment by photopea** [comment]
Hi, do you mean the name of an available font, like this? http://i.imgur.com/rkJ8ZV2.png 

If I display the full font name, the button can have varying width ... if it is too wide, it can look bad, I think ... what if I show the full name when you hold a mouse over it for a while, like when you hold a mouse over tools in a toolbar? Would it be enough?

**Comment by evantobin** [comment]
That would be perfect!

**Comment by photopea** [comment]
ok, it's done :)
