### ISSUE TITLE
How to change the color value for a PhotoFilter layer kind

### ISSUE THREAD

**Issue by jmverges** [photopea/photopea#6600]
For my future self:

If you get yourself in this situation use

```
function changeColor(red, green, blue) {
    var idsetd = charIDToTypeID("setd");
    var desc344 = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var ref16 = new ActionReference();
    var idAdjL = charIDToTypeID("AdjL");
    var idOrdn = charIDToTypeID("Ordn");
    var idTrgt = charIDToTypeID("Trgt");
    ref16.putEnumerated(idAdjL, idOrdn, idTrgt);
    desc344.putReference(idnull, ref16);
    var idT = charIDToTypeID("T   ");
    var desc345 = new ActionDescriptor();
    var idClr = charIDToTypeID("Clr ");
    var desc346 = new ActionDescriptor();
    var idRd = charIDToTypeID("Rd  ");
    desc346.putDouble(idRd, red);
    var idGrn = charIDToTypeID("Grn ");
    desc346.putDouble(idGrn, green);
    var idBl = charIDToTypeID("Bl  ");
    desc346.putDouble(idBl, blue);
    var idRGBC = charIDToTypeID("RGBC");
    desc345.putObject(idClr, idRGBC, desc346);
    var idphotoFilter = stringIDToTypeID("photoFilter");
    desc344.putObject(idT, idphotoFilter, desc345);
    executeAction(idsetd, desc344, DialogModes.NO);
}

changeColor(55, 237, 32);
```

If you need to find how to do something similar in Photopea, install Photoshop trial and ScriptListener https://somethingstrange.com/posts/photoshop-scripting/
This also helped: https://github.com/rendertom/Clean-SL

However Alchemist plugin seems to talk a newer Photoshop JS language that differs more from Photopea

**Comment by photopea** [comment]
I am a bit confused. Can I help you somehow? Maybe buy a notbook to write notes just for yourself :D

**Comment by jmverges** [comment]
@photopea lol I'm leaving this here because probably will save someone a bunch of hours. You could include it in your Blog or examples. You will make people happy for sure 😄

**Comment by jmverges** [comment]
@photopea somehow when saving after executing that I get this

pp.js:4447 Uncaught TypeError: Cannot read properties of undefined (reading 'v')

can you help me with that?

**Comment by photopea** [comment]
How can I help you?

**Comment by jmverges** [comment]
after executing that script, I do 
`app.activeDocument.save();`
and I get an error 
`pp.js:4447 Uncaught TypeError: Cannot read properties of undefined (reading 'v')
`

![image](https://github.com/photopea/photopea/assets/2902073/3c165caa-17d3-436d-9bbe-2b4d7ae571db)

**Comment by photopea** [comment]
I am afraid the save() command will not work, because websites can not overwrite files on your hard drive :(

I need a script that runs in Adobe Photoshop as a proof that it is a valid script. I could not run your script in Adobe Photoshop.

**Comment by jmverges** [comment]
@photopea app.activeDocument.save(); has been working for me via 
                "server": {
                    "version": 1,
                    "url": "{{$saveEndpoint}}",
                    "formats": options.formats
                }

all the time.

After executing 

'''
function changeColor(red, green, blue) {
    var idsetd = charIDToTypeID("setd");
    var desc344 = new ActionDescriptor();
    var idnull = charIDToTypeID("null");
    var ref16 = new ActionReference();
    var idAdjL = charIDToTypeID("AdjL");
    var idOrdn = charIDToTypeID("Ordn");
    var idTrgt = charIDToTypeID("Trgt");
    ref16.putEnumerated(idAdjL, idOrdn, idTrgt);
    desc344.putReference(idnull, ref16);
    var idT = charIDToTypeID("T   ");
    var desc345 = new ActionDescriptor();
    var idClr = charIDToTypeID("Clr ");
    var desc346 = new ActionDescriptor();
    var idRd = charIDToTypeID("Rd  ");
    desc346.putDouble(idRd, red);
    var idGrn = charIDToTypeID("Grn ");
    desc346.putDouble(idGrn, green);
    var idBl = charIDToTypeID("Bl  ");
    desc346.putDouble(idBl, blue);
    var idRGBC = charIDToTypeID("RGBC");
    desc345.putObject(idClr, idRGBC, desc346);
    var idphotoFilter = stringIDToTypeID("photoFilter");
    desc344.putObject(idT, idphotoFilter, desc345);
    executeAction(idsetd, desc344, DialogModes.NO);
}
app.activeDocument.activeLayer = app.activeDocument.artLayers.getByName('color');
changeColor(55, 237, 32);
'''

the app.activeDocument.save(); stops working

I can give you a PSD file if you want to test the script in photoshop and photopea

**Comment by jmverges** [comment]
You can see here the error happens in pp.js 
![image](https://github.com/photopea/photopea/assets/2902073/32add6ed-2970-495c-877b-fe0434d2952e)

**Comment by photopea** [comment]
Please, start a new issue and fill out the issue template with the exact steps of what I should do to see the problem myself. Yes, do include a PSD file, if it does not happen for every PSD file. I can not fix a problem if I can not see it :(

**Comment by jmverges** [comment]
@photopea problem is in here
![image](https://github.com/photopea/photopea/assets/2902073/2afc2f8d-31e6-4f49-b43e-c89b9a0e2385)

Photopea is expecting somehow a non RGBC but a LbCl

**Comment by photopea** [comment]
I still need steps to reproduce the problem.

**Comment by jmverges** [comment]
@photopea to resume for you and my other me.
This one is using LAB color scheme format and it works on save. 
```
function changeColor(l, a, b) {
                               var idsetd = charIDToTypeID("setd");
                               var desc344 = new ActionDescriptor();
                               var idnull = charIDToTypeID("null");
                               var ref16 = new ActionReference();
                               var idAdjL = charIDToTypeID("AdjL");
                               var idOrdn = charIDToTypeID("Ordn");
                               var idTrgt = charIDToTypeID("Trgt");
                               ref16.putEnumerated(idAdjL, idOrdn, idTrgt);
                               desc344.putReference(idnull, ref16);
                               var idT = charIDToTypeID("T   ");
                               var desc345 = new ActionDescriptor();
                               var idClr = charIDToTypeID("Clr ");

                               var desc346 = new ActionDescriptor();
                               var idRd = charIDToTypeID("Lmnc");
                               desc346.putDouble(idRd, l);

                               var idGrn = charIDToTypeID("A   ");
                               desc346.putDouble(idGrn, a);

                               var idBl = charIDToTypeID("B   ");
                               desc346.putDouble(idBl, b);

                               var idRGBC = charIDToTypeID("LbCl");
                               desc345.putObject(idClr, idRGBC, desc346);
                               var idphotoFilter = stringIDToTypeID("photoFilter");
                               desc344.putObject(idT, idphotoFilter, desc345);
                               executeAction(idsetd, desc344, DialogModes.NO);
                           }
```
Snippet in previos comment is using RGB.
Both works without saving in Photoshop and Photopea.
RGB version fails in Photopea on saving.
I don't know if Photoshop has remote saving.
Photoshop can save the file properly after executing 2 versions of the script

**Comment by photopea** [comment]
Could you send me a script and a PSD file which work in Adobe Photoshop? I was not able to execute any of your scripts in Adobe Photoshop.
