### ISSUE TITLE
Photopea is buggier than before...

### ISSUE THREAD

**Issue by ImSyed5012** [photopea/photopea#6602]
Your Operating System:
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: N/A

**This must be done to see the problem**
1. Go to www.photopea.com
2. create a bunch of shapes
3. group them up
4. create a new layer to make a new shape
5. suddenly lose control of everything. you can't navigate or move anything.

also what happened to the previous controls/hotkeys photopea used to have. I preferred those much more than now. now I have to relearn where to navigate the place....

**Comment by photopea** [comment]
I tried to do what I think you are saying, but everything works fine.

Could you actually try it in the Incognito mode, i.e. without any of your browser extensions modifying Photopea?

**Comment by ImSyed5012** [comment]
> I tried to do what I think you are saying, but everything works fine.
> 
> Could you actually try it in the Incognito mode, i.e. without any of your browser extensions modifying Photopea?


I have tried the app in incognito mode. But the same problems resulted.

I have a video of how the issue unfolded. but my file's too big to upload...

**Comment by ImSyed5012** [comment]
![Screenshot 2024-05-07 182148](https://github.com/photopea/photopea/assets/165510919/bfc0349a-a1e6-43cf-8bfb-03b691c4ad92)
i would make a shape, duplicate and fit the shape to make it symmetrical. The second I finish that and went to click on the layer's tab, nothing responded. Layers wasn't responding, the tools aren't responding, nor the tools tab or panning tab either.

I don't know what's the source of the issue

**Comment by photopea** [comment]
I tried to do your five steps, and I cannot see the problem you are describing :(

Each of your steps probably takes like five seconds, there are five steps, so your video should be like 25 seconds long. Upload it here or send it to support@photopea.com. Your video MUST START with opening www.photopea.com. Maybe you are doing something what you did not describe in your five steps.

**Comment by ImSyed5012** [comment]
> I tried to do your five steps, and I cannot see the problem you are describing :(
> 
> Each of your steps probably takes like five seconds, there are five steps, so your video should be like 25 seconds long. Upload it here or send it to [support@photopea.com](mailto:support@photopea.com). Your video MUST START with opening [www.photopea.com](http://www.photopea.com). Maybe you are doing something what you did not describe in your five steps.



Alright, I have sent a video of my issue to the email you provided. I unfortunately couldn't replicate the problem within 25 seconds. but it should give an idea where things went wrong.

**Comment by photopea** [comment]
Can you replicate a problem? I think it is realted to a Pen tool.

**Comment by photopea** [comment]
I will close it, because I still can not replicate a problem.
