### ISSUE TITLE
everything is upside down/distorted

### ISSUE THREAD

**Issue by enskstn** [photopea/photopea#6603]
Your Operating System: windows 10
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. open psd/png
3. it's upside down and distorted in several ways

i tried several different files and methods of importing ("open" feature, opening through file explorer, pasting etc) + incognito mode, and the result is all the same

how it's supposed to look:
![image](https://github.com/photopea/photopea/assets/165528215/82ce4833-3f3a-4dd8-a1a3-1eb91bface9f)

how the psd loads into photopea:
![image](https://github.com/photopea/photopea/assets/165528215/166d751b-67b6-455a-bfd6-6fcf5a2932d8)

**Comment by enskstn** [comment]
fixed by disabling webgl

**Comment by enskstn** [comment]
i can fix it by disabling webgl, but with webgl disabled, there are features that don't work such as lens blur... so i've decided to reopen this issue

**Comment by enskstn** [comment]
lol i had hardware acceleration turned off... all good now. sorry for the closing/reopening/closing!

**Comment by photopea** [comment]
Could you show me how did you turn off the hardware acceleration in your browser? A screenshot? What browser it is? I am just curious, as I did not know you can turn off the hardware acceleration.

**Comment by enskstn** [comment]
i use chrome - i had "override software rendering list" in chrome://flags disabled and also in settings > system, there is a toggle for "use graphics acceleration when available" that i also had turned off.
