### ISSUE TITLE
Image disappears

### ISSUE THREAD

**Issue by nekrophiliaki** [photopea/photopea#6604]
Your Operating System: Windows 10
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: unknown

**This must be done to see the problem**
1. open photopea tab in gradio
2. Open an image
3. switch tabs or run a program
4.  come back to photopea in  the image doesn't show, it's just a black space.  The image is still showing in the layers tab.

**Comment by photopea** [comment]
I can not make it happen :( I also use Windows 10 and Chrome. Do you use any browser extensions? Maybe they are doing this.

**Comment by photopea** [comment]
I have to close it because of lack of details.
