### ISSUE TITLE
SAVING TO SVG

### ISSUE THREAD

**Issue by MEneedhelp101** [photopea/photopea#6605]
![Screenshot (7)](https://github.com/photopea/photopea/assets/165345094/d2fe58ad-ae5e-41b4-94f1-3f6e11faf102)

the issue here is i am trying to save an image with a stroke on it to an .svg but it wouldn't show the stroke so then i read online to fix the issue i need to add a vector mask to the layer im saving, but now no matter what i cant save anything and it wont show me what im saving like normal

**Comment by MEneedhelp101** [comment]
> Please, share your document as a PSD file with us. You can put it inside ZIP and attach it here.

Im trying to save it as a .psd but every time i open the file when it saves it says there's no content on the file and it also says the file has 0 KB. do you still want me to send the file like that anyway or should we try and figure something else out?

**Comment by photopea** [comment]
Send me only the file which you can open in some program.

**Comment by MEneedhelp101** [comment]
> Send me only the file which you can open in some program.

![twofacebck (1)](https://github.com/photopea/photopea/assets/165345094/5a6d84c9-7be5-45f7-9198-539fd3a22995)
like this?

**Comment by photopea** [comment]
I am a bit confused. Could you please start a new issue and fill the issue template, including the steps how to reproduce your problem?

**Comment by MEneedhelp101** [comment]
stew

> I am a bit confused. Could you please start a new issue and fill the issue template, including the steps how to reproduce your problem?

the problem magically fixed itself today. thankyou for whatever photopea did
