### ISSUE TITLE
model 2.1) getting error while in mixing mode.again

### ISSUE THREAD

**Issue by xyzzart** [photopea/photopea#6606]
model 2.1) getting error while in mixing mode.again(

**Comment by camoody1** [comment]
![ConfusedNoGIF](https://github.com/photopea/photopea/assets/73725653/a2fa1545-d20a-4ecc-a5fb-06d7b3be579a)

**Comment by xyzzart** [comment]
> ![ConfusedNoGIF](https://private-user-images.githubusercontent.com/73725653/318361365-a2fa1545-d20a-4ecc-a5fb-06d7b3be579a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTUxNzYsIm5iZiI6MTcxMTk1NDg3NiwicGF0aCI6Ii83MzcyNTY1My8zMTgzNjEzNjUtYTJmYTE1NDUtZDIwYS00ZWNjLWE1ZmItMDZkN2IzYmU1NzlhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA3MDExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZWY1ZTk0YmI1ZjYyNGRjNmYwZWY1ZjUxOWRhYTc2ZDE1MDI4Njg0MGRlNmY4ZTM5MWNlYTVkYjZhZjgzYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VJPy0XGZzkAT0OnXQgZ_XoAVzRTskUsyiCjoAcAPJAg) [ ![ConfusedNoGIF](https://private-user-images.githubusercontent.com/73725653/318361365-a2fa1545-d20a-4ecc-a5fb-06d7b3be579a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTUxNzYsIm5iZiI6MTcxMTk1NDg3NiwicGF0aCI6Ii83MzcyNTY1My8zMTgzNjEzNjUtYTJmYTE1NDUtZDIwYS00ZWNjLWE1ZmItMDZkN2IzYmU1NzlhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA3MDExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZWY1ZTk0YmI1ZjYyNGRjNmYwZWY1ZjUxOWRhYTc2ZDE1MDI4Njg0MGRlNmY4ZTM5MWNlYTVkYjZhZjgzYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VJPy0XGZzkAT0OnXQgZ_XoAVzRTskUsyiCjoAcAPJAg) ](https://private-user-images.githubusercontent.com/73725653/318361365-a2fa1545-d20a-4ecc-a5fb-06d7b3be579a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTUxNzYsIm5iZiI6MTcxMTk1NDg3NiwicGF0aCI6Ii83MzcyNTY1My8zMTgzNjEzNjUtYTJmYTE1NDUtZDIwYS00ZWNjLWE1ZmItMDZkN2IzYmU1NzlhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA3MDExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZWY1ZTk0YmI1ZjYyNGRjNmYwZWY1ZjUxOWRhYTc2ZDE1MDI4Njg0MGRlNmY4ZTM5MWNlYTVkYjZhZjgzYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VJPy0XGZzkAT0OnXQgZ_XoAVzRTskUsyiCjoAcAPJAg) [ ](https://private-user-images.githubusercontent.com/73725653/318361365-a2fa1545-d20a-4ecc-a5fb-06d7b3be579a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTUxNzYsIm5iZiI6MTcxMTk1NDg3NiwicGF0aCI6Ii83MzcyNTY1My8zMTgzNjEzNjUtYTJmYTE1NDUtZDIwYS00ZWNjLWE1ZmItMDZkN2IzYmU1NzlhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA3MDExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZWY1ZTk0YmI1ZjYyNGRjNmYwZWY1ZjUxOWRhYTc2ZDE1MDI4Njg0MGRlNmY4ZTM5MWNlYTVkYjZhZjgzYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VJPy0XGZzkAT0OnXQgZ_XoAVzRTskUsyiCjoAcAPJAg)

sorry, but its still the best kandisnky workflow for me. mixing is great :)

**Comment by photopea** [comment]
@xyzzart hi, how can I help you? are you talking about our product www.photopea.com ?
