### ISSUE TITLE
automatically save

### ISSUE THREAD

**Issue by AsurasSoul** [photopea/photopea#6609]
Hello, recently my photopea is really bugging, everytime i start it in browser (opera gx, why im using opera gx because i have no lags in that browser) everytime i start photopea in browser, my psds automatically loads and my pc lags
![image](https://github.com/photopea/photopea/assets/108613226/8e6bec57-0d94-496e-a1e0-074f78155418)

**Comment by photopea** [comment]
Hi, try this: https://www.photopea.com/tuts/photopea-opens-up-old-files/

**Comment by AsurasSoul** [comment]
> Hi, try this: https://www.photopea.com/tuts/photopea-opens-up-old-files/
i want the delete the cookies, but theres is no lock button there
![image](https://github.com/photopea/photopea/assets/108613226/a8c2e6bb-ef96-4766-b1ac-f7283fe17216)

**Comment by photopea** [comment]
Open Photopea at www.photopea.com and delete cookies

**Comment by photopea** [comment]
Or at least show me your whole screen. There must be a button for deleting cookies it somewhere.

**Comment by photopea** [comment]
I have to close it because of lack of details.
