### ISSUE TITLE
a phenomenon that stops during the pen tool

### ISSUE THREAD

**Issue by applr0327** [photopea/photopea#6611]
Your Operating System: 윈도우11
Your Web Browser: Photopea
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. A bug that suddenly stops while using pen tools
3. The bug that stops causes the work to slow down and get angry
4. ....

**Comment by photopea** [comment]
I am a bit confused. What exactly should I do to see the bug? Or could you record a video?

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by photopea** [comment]
I have found a serious bug with a Pen tool, and it should be fixed now.
