### ISSUE TITLE
Stroke effect problem

### ISSUE THREAD

**Issue by pedropablovalenzuela** [photopea/photopea#6612]
_Reposted from r/photopea._

 Hello!

I've been using Photopea for a long time, but one of the biggest issues I have with it is the fact that the stroke effect doesn't work correctly. If I do a thick stroke, the corners are round, even if the original shape is square. For example, the left image is with the stroke effect, and the one on the right is one I handmade using the lasso tool. Is there any way to fix this? 
![stroke-problem-question-v0-owh9hj67a6sc1](https://github.com/photopea/photopea/assets/162663035/81df7b81-0c7b-4ced-8d09-54a0426178d8)

**Comment by photopea** [comment]
You should start working with vector shapes: [www.photopea.com/#ijDUQ286K](http://www.photopea.com/#ijDUQ286K)

Read this: https://www.photopea.com/learn/vector-graphics and the four related articles below it (a list is on the left side).

This works the same in Adobe Photoshop, so you can use any resource which describes how to do it in Photoshop.

**Comment by photopea** [comment]
I will close it, because there is no problem, the person just needs to learn how to use Photopa / Photoshop.
