### ISSUE TITLE
New Document Issue

### ISSUE THREAD

**Issue by BlueRoseArt** [photopea/photopea#6613]
I can't open a new document i click it and it does nothing any help??? Thank you!!

**Comment by photopea** [comment]
I just tried it and it works fine :/ Maybe try this https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by BlueRoseArt** [comment]
> I just tried it and it works fine :/ Maybe try this https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

Yes it worked with incognito mode thank you!!
