### ISSUE TITLE
Ad Blocker detected when ads are allowed

### ISSUE THREAD

**Issue by joelinstrum** [photopea/photopea#6615]
Your Operating System: Mac Catalina OS
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: 

**This must be done to see the problem**
1. Go to www.photopea.com
2. Export an image as PNG
3. Message displayed "Are you using an ad blocker?" and "Ad-blocker detected", but I have allowed all ads on this page
![Uploading Screen Shot 2024-04-03 at 1.22.55 PM.png…]()

**Comment by photopea** [comment]
Could it be a bug in your ad blocker? Did you try to turn it off completely?

**Comment by Cyrano25550** [comment]
same problem with uBlockOrigin installed but deactivated for the Photopea site
![Screenshot 2024-04-09 at 13-56-26 Photopea Online Photo Editor](https://github.com/photopea/photopea/assets/131190789/ff6fb700-0bc1-4505-bde0-810865fa0677)

**Comment by photopea** [comment]
Maybe you are using other ad blockers and you dont know about them. Did you try to use Photopea with uBlockOrigin as the ONLY running extension? This article can tell you more: https://www.photopea.com/tuts/photopea-says-i-am-blocking-ads-but-i-am-not/

**Comment by peiyingyao** [comment]
I'm having the same problem.
I use Adblock Plus, but I've found that Photopea says I'm blocking ads whether or not I use any ad blocking extensions, Screenshots of Incognito Mode and Guest Mode, which also doesn't allow extensions, prove that.
![Snipaste_2024-04-10_04-01-56](https://github.com/photopea/photopea/assets/165006412/53a71004-56b9-4245-a58f-9b8d54c59f00)
![Snipaste_2024-04-10_04-02-09](https://github.com/photopea/photopea/assets/165006412/316d2110-1354-4ab4-83a6-b2b2ee54125a)
If the image doesn't work: https://postimg.cc/gallery/SszzCVg

Your Operating System: Windows 10 Enterprise LTSC; version: 21H2
Your Web Browser: Chrome; version: 123.0.6312.106
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. use Chrome. I don't think it has anything to do with the system model
2. Go to www.photopea.com. 
3. Export an image as PNG or ICO

**Comment by photopea** [comment]
I have to close the issue, because the person did not respond. I do believe that you can find all answers here:  https://www.photopea.com/tuts/photopea-says-i-am-blocking-ads-but-i-am-not/
