### ISSUE TITLE
My old psd files open each time I use them again and the platform bugs when I open several files.

### ISSUE THREAD

**Issue by clairou29** [photopea/photopea#6616]
Your operating system : windows 10
Your web browser : google chrome
The problem also occurs in Incognito mode: idk

**The following must be done to see the problem**.
1. Go to www.photopea.com
2. The software takes a long time to open because it loads old (and since closed) documents. 
3. After that, I can finally open a new file
4. If I want to open a second psd file, the platform bugs and everything goes black. I can't do anything except save my file, close it and go back to step 2 (a big waste of time).
![bug photopea](https://github.com/photopea/photopea/assets/166033061/b78f4396-e306-4c52-b9fa-52b1e4b88402)

**Comment by photopea** [comment]
Try this: https://www.photopea.com/tuts/photopea-opens-up-old-files/

**Comment by clairou29** [comment]
I've managed to stop the old files from opening (by clearing cookies and data). On the other hand, photopea is still buggy and unusable. Very slow to use and as soon as I want to merge the layers, to save my file as a pdf, everything crashes and it merges me into a blank page, after 5 min of loading. 
![photopea2](https://github.com/photopea/photopea/assets/166033061/31950b79-e88c-4ddf-8427-16818405d7ce)
![photopea1](https://github.com/photopea/photopea/assets/166033061/9ae6d760-61f2-4c5c-aa24-545007fdf12e)

**Comment by photopea** [comment]
None of your links shows www.photopea.com . I have no idea what you are using.

**Comment by cmacd3** [comment]
I am experiencing the same issues.
Your operating system : windows 10
Your web browser : google chrome
The problem also occurs in Incognito mode: yes

**Comment by cmacd3** [comment]
Hello,

Thank you for reaching out and trying to help.

I think I have discovered what the issue is. I was working with images that
were 10800 x 7200 300 dpi. Once I reduced the DPI, and reduced the size
which wasn't necessary anyway as they would be posted to the web, the
problem has disappeared.

I hope this is helpful to someone else.

Kind regards,

Cathy

**Comment by photopea** [comment]
Photopea shuld be able to work with  10800 x 7200 300 dpi files without any problems, as long as you have enough RAM memory.

**Comment by cmacd3** [comment]
I was trying to generate mock-ups in some cases, and may have had two or
three or more mock-ups of that size open. If I wasn't generating mock-ups
when it happened, it was usually when I had other images loaded as well.

You are probably right, it is likely the RAM.

Thank you and I hope you have a great day!
