### ISSUE TITLE
Foreground/Background Color Switch on Mobile

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#6617]
Your Operating System: Android Phone
Your Web Browser: Edge for Mobile
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. On your Android Mobile phone...
2. Go to www.photopea.com
3. Open any image
4. Try to swap the foreground and background colors using the color switcher.
5. It does nothing for me. 🤷🏽‍♂️

![New Project (2)](https://github.com/photopea/photopea/assets/73725653/0eff20c2-124a-4231-a37d-3370217aabb0)

**Comment by photopea** [comment]
It works on my Android Phone in Chrome, but it is hard to hit with a finger, you might need some stylus or a bluetooth mouse.

Have you tried it in Chrome?

**Comment by camoody1** [comment]
I'm using a stylus on my Galaxy S22 Ultra. And it doesn't work for me in Chrome, either. 

I can click the black/white corner to reset the foreground and background colors, but when I tap the other corner, the button just "blinks" and then nothing happens. 🤷🏽‍♂️

**Comment by photopea** [comment]
Maybe your device ignores touches which are too close to the edge of your screen?

**Comment by camoody1** [comment]
No, that's not the issue. I can activate every other tool by clicking the very bottom corner of its button. Also, the color switcher doesn't work for me in landscape mode, either. And that button isn't near the edge of the screen in that case.

**Comment by camoody1** [comment]
Nothing at all you can think of that could be causing this, huh? I checked, again, today and it's still an issue for me. So weird.

**Comment by photopea** [comment]
Did you try to connect an external mouse? It works in my case :(

**Comment by camoody1** [comment]
> Did you try to connect an external mouse? It works in my case :(

I finally found a mouse to hook-up to my phone and yes, it does work correctly with the mouse. I have no idea why it won't work with the stylus. The stylus has a tiny indicator dot showing where it's going to touch the screen and I have it right over that corner. But when I tap, the entire tool button just depresses with nothing activating. So, Photopea acknowledges that I'm tapping that tool button, but it's not activating. Any idea what that button depressing look would be indicative off?

**Comment by photopea** [comment]
Have you tried to use a finger instead of a stylus?

**Comment by camoody1** [comment]
Yeah, it works with my finger, but it's just not very easy for my big sausage fingers to hit the exact right spot in that little corner. I tend to keep accidentally hitting the keyboard button below it. I would think that the stylus would be much more accurate. I don't remember having this issue when I used my phone with Photopea more often. Maybe something changed in the Samsung UI. 🤷🏼

**Comment by photopea** [comment]
So your stylus is not just a piece of plastic, but it has a battery and is synchronized with your phone?

**Comment by camoody1** [comment]
I believe that is correct. The stylus is called an "S Pen". It is synchonized with my phone and has a button that I can use to remotely take photos with my camera. So, I assume there must be a small rechargeable battery inside of it.

**Comment by photopea** [comment]
I can not reproduce it, so I think it is a bug of the device, and can be fixed only by the OS
