### ISSUE TITLE
Save on local machine not working

### ISSUE THREAD

**Issue by gfaurobert** [photopea/photopea#6618]
Your Operating System: Manjaro
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: NA

**This must be done to see the problem**
1. Install the app
2. Create a new PSD
3. Save for the first time
![image](https://github.com/photopea/photopea/assets/132338832/0b54192c-2a49-49ba-a63f-834ab9eac8cf)

5. Make a change
![image](https://github.com/photopea/photopea/assets/132338832/7997b31b-c83e-4650-a844-f87ff5810118)

7. Save  (notifies "Saving" but actually not saved)
8. Save as PSD (notifies "Saving" but actually not saved) 
![image](https://github.com/photopea/photopea/assets/132338832/85324683-bb91-4f9b-a004-36a6f7b0ed0d)

9. When closing without saving after "saveing" as PSD file is actually empty
![image](https://github.com/photopea/photopea/assets/132338832/5a9dbce6-90ce-4d21-8e43-f9546eecd327)
![image](https://github.com/photopea/photopea/assets/132338832/2ebebc11-a0e9-4eae-aef3-11beefb11dde)

**Comment by photopea** [comment]
We accept only bug reports, which happen in a standard web browser with no browser extensions. Does this problem ever happen when you are not using any browser extensions?

**Comment by photopea** [comment]
I have to close it because of lack of details.
