### ISSUE TITLE
Cannot resize using transform controls

### ISSUE THREAD

**Issue by blurryfxcedride** [photopea/photopea#6619]
Your Operating System: Windows
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Select a photo, text, drawing
3. Enable transform controls
4. Attempt to use the transform controls

**Comment by photopea** [comment]
No matter what I do, I can not see a problem at step 4 :(

Could you record a short video of opening www.photopea.com and what you do next?

**Comment by blurryfxcedride** [comment]
I won't be home until tomorrow, but when I get there I will send a video.

**Comment by blurryfxcedride** [comment]
I'm not home at the moment, but when I get home I will take a video

**Comment by bluerag56** [comment]
I'm having a similar problem with Safari and Chrome on a Macbook Air running MacOS 14.4.1. It worked yesterday, but not today. Here is a short video of the problem.

https://github.com/photopea/photopea/assets/166259873/231e1d4e-bbfb-498d-ad50-6b756b719c0b

**Comment by photopea** [comment]
I think I have fixed the problem. Could you try it again?

**Comment by bluerag56** [comment]
Yes. It works again. Thanks.

**Comment by blurryfxcedride** [comment]
I just went back on and everything is working again. Thank you!

**Comment by photopea** [comment]
Could you try it wit all of your browser extensions disabled? I think one of your browser extensions could be breaking Photopea. If you dont know which one, try to disable them all.

**Comment by blurryfxcedride** [comment]
I disabled all browser extensions and it is finally working again. Thank you!

**Comment by photopea** [comment]
ok, perfect!
