### ISSUE TITLE
Create new fill layers from bottom right along with new adj layers

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#662]
It's cumbersome to dig in through the top menu for creating fill layers, having shortcuts at bottom right along with adj layers just like in photoshop would be better

**Comment by photopea** [comment]
We already added Layer effects to the bottom right, and there is less and less space. You can draw solid color rectangles with a Rectangle tool.

**Comment by hgs54371** [comment]
Only fill layers can have their properties changed easily, colors of shape layers are fixed once it's drawn.
This flexibility is why fill layers exit, not replaceable with shape tool

**Comment by photopea** [comment]
But Fill layers are on top of Adj layers, just like in Photoshop.  https://imgur.com/fg1UbYc

**Comment by MichalSZZ** [comment]
In Photoshop, fill layer is also in this menu on the top of "adjustment layer" list.  ![](https://i.imgur.com/4ZWrsDw.png) (this is screen from my phone)

**Comment by photopea** [comment]
Ok I added it to the top of this menu, too.
