### ISSUE TITLE
I can't edit the contents of a smart object.

### ISSUE THREAD

**Issue by aleanikina** [photopea/photopea#6620]
Your Operating System: Win 10
Your Web Browser: Chrome

Nothing happens when you double click on a smart object icon.

**Comment by photopea** [comment]
Nobody else is reporting it. What should I do to see it myself?

**Comment by aleanikina** [comment]
> Nobody else is reporting it. What should I do to see it myself?

I don't know. the same thing happens in Mozilla Firefox. I create a smart object, but I can't open it. In general, double-clicking on any layer and its icon does nothing.

**Comment by photopea** [comment]
Did you try it in the Incognito mode?

**Comment by aleanikina** [comment]
yes, it's the same there

**Comment by photopea** [comment]
Could you put your PSD file into a ZIP and attach it here, so that I can try it myself?

**Comment by aleanikina** [comment]
[прототип реле2.zip](https://github.com/photopea/photopea/files/14978583/2.zip)
I can't even rename any layer

**Comment by photopea** [comment]
I can open your file in www.photopea.com and I can open smart objects.

Please, record a short video of you opening www.photopea.com in the Incognito mode, and what happens next.

**Comment by aleanikina** [comment]
I'm sorry. It turned out that the application requires a very fast double click, which is difficult for me to perform. On Windows I set the double click speed to low, but this setting does not apply to the Photopea application

**Comment by photopea** [comment]
To open a Smart Object, you can press Layer - Smart Object - Open (Edit Contents). There is no need to double-click anything.

**Comment by aleanikina** [comment]
Is it possible to rename a layer in an alternative way?
