### ISSUE TITLE
Send to Controlnet not functioning

### ISSUE THREAD

**Issue by shaveltrw** [photopea/photopea#6621]
Your Operating System: W11
Your Web Browser: Chrome

Using the Stable Diffusion API in AUTO1111 the API successfully fetches a controlnet preprocessor preview and editing panel but I am experiencing a recurring issue where the "send to controlnet" function does not send to controlnet. Custom edits within the photopea API are saved and shown in photopea but will not send back to controlnet. I've been having this issue on and off for a couple weeks. It is particularly consistent after using the 'fetch previous prompt parameters' in the AUTO1111 UI (little blue arrow beneath generate button).

I like using photopea for SD's controlnet, and will continue using it. But I hope this may help in improving the experience. Thanks.

**Comment by camoody1** [comment]
The A1111 extension for Photopea is not an official extension. You'll need to contact the developer of that extension for support.

**Comment by photopea** [comment]
I am not familiar with what you are saying. If it is about some plugin, you should report it to the creator of that plugin.

**Comment by photopea** [comment]
I have to close it because of lack of details.
