### ISSUE TITLE
Does Photopea also have an 'enable missing glyph protection' feature? 

### ISSUE THREAD

**Issue by Elitebeatagents** [photopea/photopea#6622]
Your Operating System: Windows 11
Your Web Browser: Edge
The problem happens in the Incognito Mode, too: Nope.

If there is an 'enable missing glyph protection' function, I would like to know how to turn it off.

**Comment by photopea** [comment]
Hi, we dont have any such a feature. What problem with Photopea exactly do you have?

**Comment by Elitebeatagents** [comment]
The font that I download and use separately now is automatically replaced with the local font. In the case of the Photoshop program, it is said that it is a problem that can be solved if the 'enable missing glyph protection' function is turned off, but I asked if there is a similar function in photopea.

**Comment by Elitebeatagents** [comment]
> The font that I download and use separately now is automatically replaced with the local font. In the case of the Photoshop program, it is said that it is a problem that can be solved if the 'enable missing glyph protection' function is turned off, but I asked if there is a similar function in photopea.

**Comment by photopea** [comment]
If you are typing and your font does not support what you type, the font is changed. Otherwise, there would be squares for the misssing characters.

You can always select a part of text and apply a specific font to that text, after typing.

**Comment by photopea** [comment]
I think what you want can be achieved with Photopea as it is.
