### ISSUE TITLE
RGB/4, RGB/1

### ISSUE THREAD

**Issue by Mobrack20** [photopea/photopea#6623]
Whenever I try to edit a small image, around 30 pixels of size in width and height, in the name of the file it says RGB/4 or RGB/1, and everything is invisible, even when I draw its invisible, any images i put in that image is also invisible

**Comment by Mobrack20** [comment]
![image](https://github.com/photopea/photopea/assets/148381945/d42d5ba5-5742-4001-bd82-aa9cb8511356)
![image](https://github.com/photopea/photopea/assets/148381945/c2314c00-d319-424f-a9dc-938deae9c4fd)

**Comment by Mobrack20** [comment]
It just started happening, I didn't even change anything.

**Comment by photopea** [comment]
Could you share your file with me? Put it inside a ZIP.

**Comment by photopea** [comment]
You can attach it here.

**Comment by Mobrack20** [comment]
I noticed its actually due to the size of the image itself, which was never and issue just until suddenly.

**Comment by Mobrack20** [comment]
> You can attach it here.

ok

**Comment by Mobrack20** [comment]
![hair](https://github.com/photopea/photopea/assets/148381945/63113c91-be1b-45e1-86d8-2b58d291b1f9)
![cap](https://github.com/photopea/photopea/assets/148381945/a8e6495c-76e9-4117-be79-b14b7782c476)
![hat](https://github.com/photopea/photopea/assets/148381945/f7048543-20f0-4985-9ad1-ec5cce30fa2f)
things like the hat works just fine, the other 2 dont work bcs of the size

**Comment by Mobrack20** [comment]
you can right click on the images and press save as, it seems small because its a sprite

**Comment by Mobrack20** [comment]
![skin layer](https://github.com/photopea/photopea/assets/148381945/6835940d-83b5-48ca-8d3c-11e163edd1ea)
images that are bigger, that have more content on it like this one works fine

**Comment by photopea** [comment]
I am very sorry, it should be fixed now. Please, hard-reload Photopea or clear your cache, to be sure you are not using a version from an hour ago.

**Comment by Mobrack20** [comment]
Thank you so much! It worked, love the app.
