### ISSUE TITLE
Feature request:  Object selection using Segment Anything

### ISSUE THREAD

**Issue by patrikzudel** [photopea/photopea#6625]
It would be very cool if Photopea would have Object selection that is more comparable in performance to the one in Photoshop. Select subject is a good feature but lacks control, the user doesn't always want to select only the subject.

An approach that came to my mind is using the Segment Anything model locally in browser, there are two versions, mini (50mb) and base (300mb). Embedding of 1080p image on mini (AMD 5600X) takes 11 seconds. After an embedding is done, selection takes 0.1 seconds. On the base model embedding takes 6x longer. 

Examples of local in-browser implementation: 
- https://huggingface.co/spaces/radames/candle-segment-anything-wasm
- https://github.com/sunu/SAM-in-Browser

The implementations above have selection that's **worse quality** than the official [MetaAI showcase available here ](https://segment-anything.com/demo)
**The Meta showcase has amazing selection and is a great showcase of the models power.** 

I am a paying user and I use Photopea professionally and love it. I would gladly even pay credits for good object selection if local execution of the model wouldn't be suitable. Thank you for considering this.

_Segment Anything uses the Apache 2.0 License._

**Comment by photopea** [comment]
I tihnk Segment Anything is very bad for object selection, as it can not detect precise borders of objects. 

Here is what I got with Segment Anything (375 MB downloaded, 60 seconds processing on my CPU)
![cutout](https://github.com/photopea/photopea/assets/15955558/34ee2ddb-3b60-4afa-8d83-e1676dbe7ab3)

And here is what I got with Select - Magic Cut (part of Photopea, which is 1 MB) in about 5 seconds:
![1568888636_vqudbw](https://github.com/photopea/photopea/assets/15955558/8a74ac94-2e82-4f13-8831-5ff80a723412)

If you want a one-click solution, use Select - Remove BG. It uses a 10 GB AI model (on our server) and gives better results than Adobe Photoshop or any other software.

**Comment by patrikzudel** [comment]
I don't think this comparison is fair for usecases that are more complex, where Segment Anything would shine. Of course for main subject background removal the Remove BG would be far superior, but that is not the only usecase where object selection is needed. Let me give some examples where Segmentation is helpful.

**Example image**
![DonkTipsTricks (3)](https://github.com/photopea/photopea/assets/34461296/bf4d6321-6944-4233-aa5f-b9f37fd86520)

**For example I might need to change the subjects hair. 1 Click with segmentation.** 
![image](https://github.com/photopea/photopea/assets/34461296/24182a82-3232-4c93-aac4-e60ed2f9db53)
![hair](https://github.com/photopea/photopea/assets/34461296/e8a4a0ee-43f4-4efc-97b0-0818aded380e)


**I might need to extract only his left hand. 1 Click again.**
![image](https://github.com/photopea/photopea/assets/34461296/b5532bac-5844-4e2a-b1db-9969d9dbae48)
![lefthand](https://github.com/photopea/photopea/assets/34461296/e78bad62-9d9b-48bc-ba67-ce7928e0c16a)


As I've stated in my first post, I agree that the huggingface implementation of selection is bad, but the **Meta demo implementation is good**. 

Here is a better comparison in my opinion. 

Source Image: 
![image](https://github.com/photopea/photopea/assets/34461296/79ad13cd-b32c-489d-b1dc-e13263edf7be)

Magic Cut (1 minute of work)
![magiccut](https://github.com/photopea/photopea/assets/34461296/972f7af7-a73f-4d76-88b8-4b598641885b)

Remove BG (Good quality, but no control over what the "subject" is)
![removeBG](https://github.com/photopea/photopea/assets/34461296/a79a5f79-bd91-43cb-8092-0c97f5a86c8b)

Segment Anything (Meta demo) 
![meta](https://github.com/photopea/photopea/assets/34461296/46af5b86-4de3-4e62-ae6c-8934e8d47e06)

With WebGPU, Segment Anything embedding can take 1-3 seconds.

**Comment by photopea** [comment]
I think the Segment Anything + smoothing is a bad result for most of the people. The seleciton is smooth, but not precise. Also, I am afraid most of the people would not want to wait minutes to download 375 MB, they would rather use the lasso tool for two minutes.

**Comment by patrikzudel** [comment]
Yes, but let's not forget that they'd call the Magic Cut result worse.
Also, calling it bad needs context to say what it is bad for - for Generative Fill it's a good result, for making stylized cutouts it's a good result. If more precision is needed, the selection can still be post processed significantly, still saving time.

Also, I doubt that anyone would say that the Glove example with Segment Anything + Smoothing is bad. 

Regarding the download, the ONNX implementation I linked showcases a quantized model that is only 108MB in size, that isn't going to be minutes to download for most users, and internet is only going to get faster.

**Comment by patrikzudel** [comment]
My main point is that pursuing Object selection would be great, maybe another approach could be using Segment Anything (smoothed) inside Magic Cut - clicking on an object would set it as Foreground and everything else as Background, then the user could fine tune it if needed.

Here I used an approach where I combined Segment Aynthing + Refine Edge (Right side) + Remove BG (for left side) and made this bear in 1 minute, much more comfortably than masking it using the lasso tool. 
![bearbest (1)](https://github.com/photopea/photopea/assets/34461296/c2d71943-006c-4714-b0c2-a5c178adba8c)

**Comment by camoody1** [comment]
I agree that Segment Anything would be a wonderful addition to the Photopea tool set. But I also understand what Ivan is concerned about with the 320MB download. Perhaps making the tool available with a pop-up window making the user aware of a one-time download of 320MB to make it work? **IS** it a one-time download? Or would that download have to happen every time it was used? If you could make something like that a one-time download, I think it would be great to have.

**Comment by patrikzudel** [comment]
If it is cached in the implementation (it would be), it is a one time
download as long as the user doesn't clear the local storage manually.

As I've mentioned, a quantized version of the base model is available,
having just 100mb, that could be the default option if 304mb would be
deemed too big.

**Comment by photopea** [comment]
I dont think anybody would be interested in it, when we already have Select - Remove BG, which works much better.

**Comment by camoody1** [comment]
> I dont think anybody would be interested in it, when we already have Select - Remove BG, which works much better.

Eh. I disagree. Remove BG removes everything from your image except the main subject. Segment Anything could be used to select from specific objects or pieces of objects. It's very useful in AI image work.

**Comment by patrikzudel** [comment]
> I dont think anybody would be interested in it, when we already have Select - Remove BG, which works much better.

I feel like you are not listening to arguments at all, it is not the same thing as **Subject selection (Remove BG)**. @camoody1 is saying the same thing. 
I often come across a scenario where fast object selection would save a lot of time.

**Comment by photopea** [comment]
You can create a plugin for Photopea: https://www.photopea.com/api/plugins . But I dont think a significant amount of our users would like downloading a huge model and spending 60 seconds to process each image.
