### ISSUE TITLE
Feature request: Magic replacement improvements

### ISSUE THREAD

**Issue by patrikzudel** [photopea/photopea#6626]
It would be very much appreciated if magic replace would have the following 2 features.

1. Option to Sample all layers instead of just the one selected. 
2. The replaced image should be put on a new layer, a copy of the sampled image. It should also be masked according to the selection. Image below as an example. Thus magic replacement would be non-destructive.

Thank you for considering this.

<img width="431" alt="1photopea" src="https://github.com/photopea/photopea/assets/34461296/3248c79c-774a-4fe5-bf63-3fc85de7e7ab">
<img width="450" alt="2photopea" src="https://github.com/photopea/photopea/assets/34461296/88b05c37-d9cb-4968-ad29-6360c5988494">

// EDITED the phrasing of _2._ to be more accurate.

**Comment by photopea** [comment]
Do you know how it works in Adobe Photoshop? Would you like it to work in the same way?

**Comment by patrikzudel** [comment]
I think in Photoshop it is similar to what I described here.

**Comment by Baegus** [comment]
> Do you know how it works in Adobe Photoshop? Would you like it to work in the same way?

This is definitely how it works in Photoshop. It gets the context for Generative Fill from the entire visible canvas.

**Comment by sanjanakri0912** [comment]
IT is not showing ads while using magic replacer and photopea is not responding.

**Comment by photopea** [comment]
It seems to work fine for me, ads play well.

**Comment by photopea** [comment]
I have implemented a new interface for Magic Replace:

- new content is placed into a separate "Generative Fill" layer
- if you open Window - Properties of that layer, you can generate new variations of a content, which will also be placed into the same layer.
- you can switch between variations in the Window - Properties of that layer, or delete variations

https://github.com/photopea/photopea/assets/15955558/40ecafcb-fff0-41f4-927c-ed93a11f57d8

**Comment by photopea** [comment]
There is one more new thing in Magic Replace: it uses the content of all layers ("merged image"), so when you use it, it is not important which layer is selected at that moment. So you can create "patches" on top of each other.
