### ISSUE TITLE
Cursor visibility on 4k is poor

### ISSUE THREAD

**Issue by patrikzudel** [photopea/photopea#6627]
Operating System: Windows 11
Web Browser: Chrome

It is very hard to show on picture, so I've tried to exaggate the differences by zooming out and taking a screenshot of the cursor. 

<img width="466" alt="4kvs1080p" src="https://github.com/photopea/photopea/assets/34461296/155d5146-2cc2-4cda-9745-e4032bce98d1">

All cursors on 4k are **very thin**, it would be amazing if we could manually control the cursor thickness or size.

**Comment by photopea** [comment]
The cursor should be bigger now. Could you confirm if it looks better?
