### ISSUE TITLE
Broken transparency when using Magic Cut / Refine Selection

### ISSUE THREAD

**Issue by ronan36880** [photopea/photopea#6628]
Your Operating System: Windows 11 23H2
Your Web Browser: Google Chrome 123.0.6312.106
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Unzip [New Project.zip](https://github.com/photopea/photopea/files/14898707/New.Project.zip) and open file
3. Try to use magic cut/refine selection
4. when border is set to any value other than 0, transparency is broken.

I believe this issue only showed up a few days ago

Video:
https://github.com/photopea/photopea/assets/93485284/8f63f27d-0401-4698-abbd-19271cd4f5b2

**Comment by photopea** [comment]
I am very sorry, it should be fixed now.
