### ISSUE TITLE
Cannot export as SVG due to vector mask (same issue as 6605).

### ISSUE THREAD

**Issue by LaurenceGough** [photopea/photopea#6629]
Hello,

Your Operating System: Windows 11 23H2
Your Web Browser: Latest Chrome 123.0.6312.106 and also latest Edge (all extensions off)
The problem happens in the Incognito Mode, too: Yes (all extensions off)

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create text (vector as default)
3. Apply a vector mask
4. No longer can you export as SVG. If you hide the text layer with the mask applied you can now export again. Trying a second time prevents any export for web from working. Exporting as PNG etc works fine after you reload the webpage.
5. Clearing cache and trying different browsers does not help
6. **Disabling the vector mask allows the SVG export to function as normal.**
7. No combination of export options appears to allow the SVG to export. At best I got a 0KB file to download.
8. Exporting layers as SVG doesn't work either.

It's the exact same issue as https://github.com/photopea/photopea/issues/6605

They said it just fixed itself eventually, but it's not yet for me...

Thanks

**Comment by photopea** [comment]
It should be fixed now. Vector masks should be exported correctly to SVG now.
