### ISSUE TITLE
Photopea Black PSDs files.

### ISSUE THREAD

**Issue by ellia09** [photopea/photopea#6631]
Your Operating System: Lenovo Chromebook up to date.
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Yes

Hello there I hope you're well. I went to uses Photopea as usual and opened a PSD file only to find it black, the same thing has occurred to me with different PSD files and even if I re-download them. I'm unsure of the cause itself and this worries me since this is the only editing site I feel comfortable using. Here is one example of the outcome.
![Screenshot 2024-04-08 13 47 54](https://github.com/photopea/photopea/assets/166437806/19153126-2cc9-411f-8c81-487e1331b45f)

**Comment by photopea** [comment]
Could you attach your PSD file here?

**Comment by ellia09** [comment]
> Could you attach your PSD file here?
i cant seem able to attach file but here is a link of one of them :[ ](https://www.deviantart.com/somresources/art/PSD-013-IN-A-CROWD-OF-THOUSANDS-797649069)

**Comment by photopea** [comment]
How can I download the PSD file from there?

**Comment by photopea** [comment]
I have to close it because the person did not respond.
