### ISSUE TITLE
Auto tone / contrast / color filters doesn't work correctly

### ISSUE THREAD

**Issue by andrii-nastenko** [photopea/photopea#6632]
Your Operating System: Windows 11
Your Web Browser: Chrome 123.0.6312.106
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Upload any image
3. Navigate to 'Image' menu
4. Apply any of these 3 filters: 'Auto Tone' / 'Auto Contrast' / 'Auto Color'

Actual result:  image gets corrupted in certain places
![Screenshot 2024-04-08 214539](https://github.com/photopea/photopea/assets/40956346/3684e2e7-5ead-4e2e-ae74-b07191d7e155)

**Comment by photopea** [comment]
sorry, it should be fixed now.
