### ISSUE TITLE
Adverts taking focus away from Photopea. Again.

### ISSUE THREAD

**Issue by cyclops365** [photopea/photopea#6633]
Your Operating System: W10
Your Web Browser:  MS Edge
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open document
3. Start typing in a text box. 
4. When ad reloads it takes the focus away and have to click inside the text box to continue. Happens evry 15 seconds.

**Comment by photopea** [comment]
Does it happen when you have no browser extensions modifying Photopea? E.g. in the Incognito mode?

**Comment by photopea** [comment]
Could you share your whole screen so that we can see that you are using the Incognito mode?

**Comment by tsvetav** [comment]
> Yes, and it's this advert in the middle (the video one) ![image](https://private-user-images.githubusercontent.com/72573834/320652034-ec181701-f54d-402f-80f2-9e3946550ae3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MjkxNDUsIm5iZiI6MTcxMjcyODg0NSwicGF0aCI6Ii83MjU3MzgzNC8zMjA2NTIwMzQtZWMxODE3MDEtZjU0ZC00MDJmLTgwZjItOWUzOTQ2NTUwYWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA2MDA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjYjAyOWUzYzMxMDgzMTgwMWFhZmNkN2NlNTdiYjkwOGNkMjc0MDIyYjM5YWNmODkyZGM0YWY1Y2Y2MWJiNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8eId_yHUGg-uAOLZBI7ov950ugYvrt1uzthHNQsIUPc)

Hi, I am a rep of the main ad partner of Photopea. 
Video ads do not refresh every 15 seconds, so the issue may be coming from another unit. 
Please share your entire screen, and confirm whether the issue persists after you've cleared all cache.
Also, it'd be really helpful if you could share the country you're browsing from.

Thanks!

**Comment by cyclops365** [comment]
This my screen. As you can see now it says I am using an adblocker, which I'm not. (Please note the extension icon you see isn't for an adblocker, it is for another thing I use).

I am in the UK and have cleared the cache and cookies.
 
Hope you can help.

**Comment by tsvetav** [comment]
Would you mind sharing the screenshot of your entire screen again, as it did not attach in your latest comment? 
And lastly, could you please describe that behavior of the ad taking away the focus - how exactly is it acting?

**Comment by cyclops365** [comment]
It is the Google services ads that take the focus away. I am usually typing words and when the ad changes over, i have to click on the T to start typing again.

**Comment by photopea** [comment]
Could you please reply by going to www.Github.com? when you send emails to random github addresses, Github does not show us your email attachments.

**Comment by cyclops365** [comment]
![image](https://github.com/photopea/photopea/assets/72573834/53271130-48ee-49b9-98db-eb6b20afdf53)

**Comment by photopea** [comment]
So these are the ads which were "stealing" your focus? Could you click this button and show us what browser extensions you have running? Often, extensions replace webpage ads with their own ads.
![image (1)](https://github.com/photopea/photopea/assets/15955558/df92caac-72b5-46d4-8063-41722692595b)

**Comment by cyclops365** [comment]
![image](https://github.com/photopea/photopea/assets/72573834/235f536c-23d3-4502-ba47-661d43251581)

It's mainly the add in the middle (with the woman) which runs a video. When the video runs out and moves to the next one, that's when it takes the focus away. My extensions have nothing to do with it

**Comment by photopea** [comment]
@tsvetav It seems like the video ad for Bloomberg is stealing the focus from the user. I tried it myself, but I only saw non-Bloomberg video ads, and they did not steal the focus.

Could you remove all Bloomberg video ads from Photopea?

**Comment by tsvetav** [comment]
As per my understanding it's the video ads refreshing that the user is flagging as distracting, otherwise we will contact the video provider for assistance with Bloomberg.

**Comment by photopea** [comment]
@tsvetav "stealing focus" means, that the user is typing, but the "focus is stolen". E.g. try to type here: https://jsfiddle.net/bor3dyjv/

**Comment by photopea** [comment]
I will close it now. If it happens again, please let us know. And please, report it only if it happens in a browser with no extensions (because extensions have your permission to insert their own ads into websites, and many of them do so).
