### ISSUE TITLE
Adjustment Layer Issue

### ISSUE THREAD

**Issue by ayvoree** [photopea/photopea#6634]
Your Operating System: MacOS Sonoma 14.3.1
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open a new project and attempt to use adjustment layer: Gradient Map, Hue/Saturation, etc..
3. Instead of the effect opening up as usual, it pulls up a small properties window with Layer, Mask, Live Shapes selections that do nothing when changed.
4. Once that occurs, it seemingly locks up the current file and nothing can be done inside, when trying to drag a JPG/PNG file into that project when its locked, it says "Error. Please, send your file to support@photopea.com and we will solve it"

**Comment by photopea** [comment]
I just tried Photopea in MacOS Sonoma and everything seems to work as it should.

What is "attempt to use adjustment layer"? Do you mean creating an adjustment layer? A new project has no adjustment layers.

**Comment by ayvoree** [comment]
Yeah create a new adjustment layer like adding a Gradient Map onto your project

**Comment by photopea** [comment]
There was a bug with the Gradient Map adjustment layers, it should be fixed now. Clear your cache or wait one hour before using Photopea.
