### ISSUE TITLE
Focus Stack -> Open and Load creating new tabs, not new layer

### ISSUE THREAD

**Issue by Josef-Khalifeh** [photopea/photopea#6635]
Operating System: MacOS 14.4.1  
Web Browser: Safari 17.4.1, Chrome 123.0.6312.107

**This must be done to see the problem**
1. Open www.photopea.com
2.  Press File - Open, and load one of the images.
3. Then, press File - Open and Place, and select the remaining images (all at once). I have repeated this selecting all images, couple of the images, and one image and get the same result.
4. The tutorial (https://www.photopea.com/tuts/focus-stack-images-online/) says the images will be placed as new layers into the current document, but only one image gets loaded in and in a new tab. I have uploaded a screenshot.

I'm not sure what I am doing wrong or if there is a bug. I would appreciate any help or trouble shooting. 

<img width="336" alt="Screenshot 2024-04-08 at 11 35 17 PM" src="https://github.com/photopea/photopea/assets/125771616/e0b887ea-0739-4c10-b2b1-65d7ccc19813">

**Comment by photopea** [comment]
I just tried it on my macbook and it seems to work fine. What is the format of the images that you open? Are all images JPG images?

**Comment by Josef-Khalifeh** [comment]
The are RAW images in ARW format from a Sony camera. Do you know if it only works in JPG? I could give that a shot.

**Comment by photopea** [comment]
It will not work with RAW images.

**Comment by Josef-Khalifeh** [comment]
Yeah I just converted the files to JPG and it worked. Any chance it will work if I convert them to DNG?
