### ISSUE TITLE
Brush is broken

### ISSUE THREAD

**Issue by BestEverOreos** [photopea/photopea#6638]
Your Operating System: Windows
Your Web Browser: Google
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open an image
3. Use the brush/pencil tool for pretty much anything and it'll start doing random stuff like deleting stuff on other layers, moving the screen around, or acting as if you were holding down the shift key. And the undo button only really makes things worse.

Also the focus keeps being taken from photopea for some reason.

https://github.com/photopea/photopea/assets/149848396/a0e2ca2c-b3f8-45df-9af2-62cd3ae5eb8a

**Comment by photopea** [comment]
Are you sure it happens in the Incognito mode? Your video is not from the Incognito mode. Which means you could be using a lot of browser extensions, which break Photopea.

**Comment by moooofddg** [comment]
my brush buggin too, cant use it properly caus it messes itself up

**Comment by photopea** [comment]
If I can see it happen on my computer, I can fix it. Please, tell me what should I do to see it myself.

**Comment by camoody1** [comment]
> my brush buggin too, cant use it properly caus it messes itself up

"my brush bugging too"? Really? This is how you communicate with people? 🤦🏽‍♂️

**Comment by moooofddg** [comment]
> If I can see it happen on my computer, I can fix it. Please, tell me what should I do to see it myself.

Im not quite sure. i just opened a new project like nomral (and i've tried in incognito) and it just bugs out like @BestEverOreos .

**Comment by photopea** [comment]
@BestEverOreos maybe it would happen to me if I used your PSD file? Could you share your PSD file?

You make it sound like it happens for any image, but I can not make it happen on a one-layer image :(

**Comment by photopea** [comment]
I am very sorry, it should be fixed now. Please close Photopea and open it again.
