### ISSUE TITLE
Brush Stroke to Path is not working with Custom Brushes or Default Brushes

### ISSUE THREAD

**Issue by TMack1972** [photopea/photopea#6639]
Your Operating System: Windows 10
Your Web Browser: Chrome and Edge
The problem happens in the Incognito Mode, too: Not sure

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....import an image and adjust threshold to 170 to define hard edges
3. Use Color Range - shadows, fuzziness set to 20% to define path - Create Path from selection
4. Select B to define your brush selection
5. Select P to define your pen.  Right Click and Select Stroke
6. Using the Brush Tool select Ok
8. The stroke is not applied to the work path

I tried this in Chrome unsuccessfully, and then I switched to Microsoft Edge for the first time, and this workflow worked...once.  Subsequent attempts do not work.
This same workflow was working well the week before last.

**Comment by photopea** [comment]
I am confused. What is "....import an image and adjust threshold to 170 to define hard edges" and all other steps? Could you do it with less steps, e.g. using the Pen tool only?

**Comment by TMack1972** [comment]
Sorry for the confusion,

Can you share the workflow you would like me to use?

I am simply trying to define the outline highlights and lowlights of a
close cropped subject.  I am able to define the work path, but after the
path is highlighted and selected I cannot get the pen stroke applied to the
path I've saved using selection to path.

Regards,
Todd

**Comment by photopea** [comment]
I need to know what should I do to see the problem. What is "Select B to define your brush selection"?

**Comment by photopea** [comment]
I am very sorry, it should be fixed now. Please close Photopea and open it again.

**Comment by TMack1972** [comment]
Don't be sorry at all.

My apologies for not being able to better explain.

Greatly appreciated.

Todd
