### ISSUE TITLE
Brush is interfering with image with clicking "Ctrl + Z"

### ISSUE THREAD

**Issue by whiskeredshrimp** [photopea/photopea#6640]
Your Operating System: WINDOWS 10
Your Web Browser: CHROME + APP
The problem happens in the Incognito Mode, too: N/A

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open my file
3. Select my brush (my brush is a default preset one) and adjust the smoothness
4. I drag my brush
5. Ctrl + Z to undo
6. When I let go, and move my cursor, it erases my image from another layer.
7. When Ctrl + Z again, it removes the image and I am unable to see the image or cursor.
8. (Also happens to a new file)

https://github.com/photopea/photopea/assets/143677276/c0accf67-e2bc-43d2-9db4-6830eb08cec3

**Comment by camoody1** [comment]
You might want to start by getting rid of any adblocking extensions you have. It's pretty ballsy to come ask for help from a developer when you're blocking the ads that pay for his work.

**Comment by photopea** [comment]
How can I open your file in step 2?

**Comment by photopea** [comment]
I am very sorry, it should be fixed now. Please close Photopea and open it again.

**Comment by whiskeredshrimp** [comment]
> How can I open your file in step 2?

Im not sure how I am able to add my PSD file onto this comment. It says it does not support the file type.
