### ISSUE TITLE
TGAs wont save

### ISSUE THREAD

**Issue by Jazer82** [photopea/photopea#6642]
Your Operating System: w10
Your Web Browser: edge
The problem happens in the Incognito Mode, too:

Everytime i try to save a .tga file it save as an empty file and will not let me use the tga

**Comment by photopea** [comment]
Maybe some of your browser extensions thinks that TGA files are dangerous, and it deletes them. Did you try to turn off your browser extensions?

**Comment by photopea** [comment]
I have to close it because the person did not respond.
