### ISSUE TITLE
Nothing was loading

### ISSUE THREAD

**Issue by CalebWave** [photopea/photopea#6647]
Your Operating System: Windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open New Project
3. View Blending tools
4. Notice the stuff isn't properly loading
![image](https://github.com/photopea/photopea/assets/166773393/29ff4cdd-2459-4e5d-8ef3-10b86075ff83)

**Comment by photopea** [comment]
sorry, it should be fixed now.
