### ISSUE TITLE
I cant select my color for my stroke  or just any of the ones with colors 

### ISSUE THREAD

**Issue by UnknownG12** [photopea/photopea#6648]
Your Operating System: Windows 10
Your Web Browser: Microsoft Edge 
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. I click on blending Options 
3. I cant edit my color and also if i dont click the check mark and just want to view the settings for that edit it will add it with out the check mark being checked 
4. I dont click on the check mark and the edit stays

**Comment by photopea** [comment]
sorry, it should be fixed now.

**Comment by UnknownG12** [comment]
thanks very much

**Comment by UnknownG12** [comment]
I LOVE PHOTOPEA!!
