### ISSUE TITLE
Update Menu UI

### ISSUE THREAD

**Issue by mdschu** [photopea/photopea#6649]
I would like to suggest an update to Photopea's menus. I feel the current design looks out of place with the rest of the UI, especially when using a dark theme. I’ve designed a quick mockup to show what I had in mind; please let me know what you think!
![Current Design](https://github.com/photopea/photopea/assets/108202149/13d2f733-bf4c-42b4-b82f-103022f1fa84)

![Mockup](https://github.com/photopea/photopea/assets/108202149/47128d59-d2c8-4a77-b16e-cc9d36a826d9)

**Comment by photopea** [comment]
Hi, thanks a lot for your design! Have you tried Edit - Preferences - Glass Menus?

**Comment by mdschu** [comment]
I had no idea this option existed! Just tried it out, and it's exactly what I was looking for. Thanks for your help!

**Comment by bilogic** [comment]
@photopea glass still feels tacky, especially if there is a very colorful background image, why not make the whole UI follow the selected theme?

**Comment by photopea** [comment]
what do you mean by "whole UI follow the selected theme"?

**Comment by bilogic** [comment]
I meant if the `Theme` is `Light gray`, `Dark gray` etc, then the menus should follow too, why let them remain white? Very glaring and inconsistent if a dark theme is used.

**Comment by photopea** [comment]
Could you share an image of what you see now and what would you like to see instead?

**Comment by bilogic** [comment]
![image](https://private-user-images.githubusercontent.com/108202149/322109982-47128d59-d2c8-4a77-b16e-cc9d36a826d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4NTA5NjEsIm5iZiI6MTczNjg1MDY2MSwicGF0aCI6Ii8xMDgyMDIxNDkvMzIyMTA5OTgyLTQ3MTI4ZDU5LWQyYzgtNGE3Ny1iMTZlLWNjOWQzNmE4MjZkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNFQxMDMxMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmJlMDBjYzliMThhODYzYjRiMzE2OTIzZDUxZDhhOTIyODdlMjM4MTQ2YTRjMzFhOGZlZGMyMDgyNTlkODQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yRR5btmMyP6mm29xu3wtSqgoQL_074m65DJCZmQJ_fI)

**Comment by photopea** [comment]
I can not see any images in your comment :( have you tried to look at your comment?

**Comment by bilogic** [comment]
@photopea fixed please check again thanks

**Comment by photopea** [comment]
I think more people prefer the permanently white menus. It is how they look in Adobe Photoshop, too.
