### ISSUE TITLE
Batch routines

### ISSUE THREAD

**Issue by ianplo** [photopea/photopea#665]
The ability to combine multiple actions into a single routine and then run that routine over multiple images in a batch would be very useful (as per BIMP for GIMP) .

**Comment by photopea** [comment]
Hi, we support scripting right now: https://www.photopea.com/learn/scripts . You can run scripts on a batch of files through the API: https://www.photopea.com/api . Is that what you need?

Notice, that you can not make a script, that opens files from your hard drive, because webpages can not just read or write to harddrives.

**Comment by ianplo** [comment]
Hi, Thank you for the reply.  Yes, that sounds like the sort of thing I was describing.  I am not familiar with the scripting language myself.  For my purposes, I would like to be able to take an image, perform the trim operation and then resize the trimmed image onto a 1000 x 1000px canvas, padding with white.  Would this be possible using a script?  As an example, I might have an image of 2345 x 1234px, when trimmed the image size become 1987 x 876px.  I would want to reduce the longest dimension of the trimmed image to 1000px, retaining the aspect ratio, and then 'pad' the shortest dimension to create a canvas 1000 x 1000px.  Thank you.

**Comment by photopea** [comment]
Yes, I think it can be done with scripts. Read more about scripts (the syntax and meaning is the same as in Adobe Photoshop ... so you can use Google for that) and let me know if you need any help.

**Comment by ianplo** [comment]
Hi,

I have been trying, without much success, to run the following script:

`// get a reference to the current (active) document and store it in a variable named "doc"
var doc = app.activeDocument;  

// these are our values for the END RESULT width and height (in pixels) of our image
var fWidth = 1000;
var fHeight = 1000;

// do the resizing.  if height > width (portrait-mode) resize based on height.  otherwise, resize based on width
if (doc.height > doc.width) {
    doc.resizeImage(null,UnitValue(fHeight,"px"),null,ResampleMethod.BICUBIC);
}
else {
    doc.resizeImage(UnitValue(fWidth,"px"),null,null,ResampleMethod.BICUBIC);
}

// Makes the default background white
var white = new SolidColor(); 
white.rgb.hexValue = "FFFFFF";
app.backgroundColor = white;

// Convert the canvas size as informed above for the END RESULT
app.activeDocument.resizeCanvas(UnitValue(fWidth,"px"),UnitValue(fHeight,"px"));
`

Does the script look correct?  It appears to fail at 'doc.resizeImage'.

Thank you for any help.
