### ISSUE TITLE
Dot appearance in amiri font change if there is no letter in text

### ISSUE THREAD

**Issue by Planche95** [photopea/photopea#6654]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
Create a text layer, choose amiri font, and type anything but not letters:
![image](https://github.com/photopea/photopea/assets/18653765/d8011db4-f827-4ea1-bed5-e47471c8cb71)
dot appears as a diamond

include at least one letter:
![image](https://github.com/photopea/photopea/assets/18653765/2e33011b-2a55-4048-b1fd-c4761ee61637)
it changes to regular dot

is there anything I can do to fix it? I need regular dot with numbers only

**Comment by photopea** [comment]
This is how the font was made. The author made the arabic dot to be the default dot. We would have to add more options for choosing the language into Photopea.
