### ISSUE TITLE
Cannot edit a PSD file

### ISSUE THREAD

**Issue by pconroy328** [photopea/photopea#6655]
Your Operating System: Win10
Your Web Browser: Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Load PSD file 
3. Click on the image - 
4. Bring up Layer Style
5. Click Color Overlay
6. Then not working

**Comment by photopea** [comment]
sorry, it should be fixed now. Clear your cache.
