### ISSUE TITLE
I don't know what's happening.

### ISSUE THREAD

**Issue by jdmhomeboi** [photopea/photopea#6656]
Photopea for some reason is acting strange. For instance when I try to open a new project, the screen is blank. Like it doesn't show the  canvas. It's just a blank gray.
![Screenshot (17)](https://github.com/photopea/photopea/assets/119703005/057fd062-51eb-422f-bcc6-a1a36ebcebd5)

It can open existing files just fine, but the moment I try to move it or transform it in any way, it won't budge. And to top it all off, I can't switch between layers, it won't let me add any color overlays or strokes that aren't black, nor does it let me open the effects tab under the layer so I can make changes. What is going on?

**Comment by jdmhomeboi** [comment]
Update: Now it won't even open existing files without the screen turning gray.

**Comment by photopea** [comment]
I can not see it happen :( Did you try Photopea in the Incognito mode?

**Comment by photopea** [comment]
I have to close it, because the person did not respond.
