### ISSUE TITLE
How do I save css code?

### ISSUE THREAD

**Issue by rickdtc** [photopea/photopea#6658]
I wanted to make a blur behind thing like figma in photopea, so I decided to use the css editor.

![image](https://github.com/photopea/photopea/assets/74096544/fbcbb6c6-c665-4c61-968a-a894838cf225)

I tried use a blur backdrop filter `backdrop-filter: blur(10px);` but how do I save the changes in css I made?

I tried to find something in the docs but couldnt

**Comment by photopea** [comment]
The CSS window converts the layer styles into the CSS format, but it does not work the other way. You should add layer styles to your layer: https://www.photopea.com/learn/layer-styles
