### ISSUE TITLE
i was editing and opened it later and it was white with sad emoji on top left

### ISSUE THREAD

**Issue by imwahaj** [photopea/photopea#6659]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Your browser probably killed Photopea to release some RAM or GPU memory. You should still be able to save your work using File - Save as PSD.

I will close it, as you refused to ansewr any of our questions.
