### ISSUE TITLE
Can't Open PSD

### ISSUE THREAD

**Issue by frameofreality** [photopea/photopea#666]
I saved a few PSDs, but when I go back to open them, it says: Unknown file format: "/u0000/u0000/u0000/u0000"

How do I fix this?

**Comment by photopea** [comment]
Hi, so these PSDs were generated by from Photopea? Could you send one of them to support@photopea.com ?

**Comment by frameofreality** [comment]
Yes, they were made in Photopea. I'll send one over.

**Comment by frameofreality** [comment]
It's saying the file is 0 bytes. I tried remaking a bit of it, I noticed it seems to do the same thing if the file itself takes too long to save.

**Comment by photopea** [comment]
It seems like the error happened as you saved the PSD file. Could you try to create it again?

**Comment by frameofreality** [comment]
Yes, I'll see if the problem happens again.

**Comment by photopea** [comment]
Ok, I will close it for now.

**Comment by Bablox360** [comment]
Hello I also had this same problem but the file still has a size and can open in gimp.
