### ISSUE TITLE
[Advertising] Less memory intrusive ads

### ISSUE THREAD

**Issue by glitch128** [photopea/photopea#6660]
Your Operating System: ChromeOS

Make ads less intrusive and ram intensive. After a minute, it jumps up to 3GB of ram usage and after that, the page crashes
@photopea 
also, stop ads from making cookies.

the app is unusable.

**Comment by photopea** [comment]
You did not tell us if this happens when you use Photopea with no browser extensions. These problems could be caused by your browser extensions. Nobody else reported ads using 3 GB of RAM. Could you record a short video as a proof?

**Comment by glitch128** [comment]
![Screenshot 2024-04-18 10 04 56 AM](https://github.com/photopea/photopea/assets/78228404/d480174d-9234-476d-9a86-c268460fcf9d)
this is also absurd as well

**Comment by glitch128** [comment]
It has reached 4.2 GB

**Comment by photopea** [comment]
You can easily make Photopea use 20 GB of RAM by opening an image and cloning a layer 1000 times. Does it happen if you dont open any documents? I thought you would record the whole screen, without cropping anything.

**Comment by photopea** [comment]
Could you record it in the Incognito mode, so that we are sure no browser extensions are running?

**Comment by glitch128** [comment]
my school also blocked incognito mode

**Comment by photopea** [comment]
BTW. would you be willing to pay for using Photopea with no ads? How much would you be willing to pay for a month of Photopea with no ads (and a larger workspace)?

**Comment by glitch128** [comment]
Well, I don't use this too often, and graphic design isn't my job, so... $5 - $10 OTP
I wouldn't pay a subscription for a website.
And either way, if the ads are causing a problem to where the app is unusable, then the amount of ads should be decreased. Or only allow static image ads, and reduce the refresh rate. I'm pretty sure it's the video ads that do this, along with preloading of the ads assets.

**Comment by photopea** [comment]
When you open Photopea and use it with ads for 10 minutes, we make $0.01 during that time. So if anybody would be willing to pay $0.01 for 10 minutes of usage, we could offer them an ad-free experience.

**Comment by photopea** [comment]
@tsvetav Could you look into this? I opened Photopea in the incognito mode, and after a while, it was using 1.1 GB of RAM. Photopea with no ads uses 200 MB of RAM. Could you improve the RAM usage?
![image](https://github.com/photopea/photopea/assets/15955558/96c0b5b0-667f-4d24-bcc2-55aff410c245)

**Comment by glitch128** [comment]
wait for longer, and it'll use more!

**Comment by glitch128** [comment]
also, I would look into the **large** amount of cookies that are stored

**Comment by camoody1** [comment]
When I log out of my premium account and allow ads to run, I see my memory jump up from about 300MB to 600MB after several minutes. But I also noticed that my processor for the Photopea tab starts jumping up to 10% quite often. I can imagine that would have a painful impact on people with lesser equipment if they're also trying to run YouTube, Spotify, etc. 

I wonder if you might get more people willing to purchase a subscription if you offered payment through PayPal, Venmo and/or CashApp. I know a lot of younger people have access to those accounts more than they do a credit card. 🤷🏼

**Comment by tsvetav** [comment]
> [glitch128](/glitch128)

Hi! I am a rep of Photopea's main ad partner. Could you please tell me what's the country you're browsing from? This will immensely help us troubleshoot more efficiently.

**Comment by photopea** [comment]
@camoody1 you can pay for Photopea through PayPal :)

**Comment by glitch128** [comment]
> > [glitch128](/glitch128)
> 
> Hi! I am a rep of Photopea's main ad partner. Could you please tell me what's the country you're browsing from? This will immensely help us troubleshoot more efficiently.

United States
@tsvetav

**Comment by tsvetav** [comment]
@glitch128 thanks! Could you confirm whether you've experienced high RAM usage over the past couple days? Also, please make sure to clear all cache before checking again.

**Comment by photopea** [comment]
I was told that ads should not use that much memory anymore.
