### ISSUE TITLE
I no use addblock ):<

### ISSUE THREAD

**Issue by JulioCesarBR11** [photopea/photopea#6661]
1 : https://github.com/photopea/photopea/assets/166464464/8fe2ed58-66db-437c-97a8-09280c455b2a

2 : https://github.com/photopea/photopea/assets/166464464/fac0b551-3363-42f0-b826-18eb021d25e7

**Comment by photopea** [comment]
Photopea literally tells you to open the list of your extensions, to see which extensions could be blocking ads.

Could you at least show us this list, as a proof, that you are not using an adblock?
![VDzo5rg](https://github.com/photopea/photopea/assets/15955558/be225e3c-27b9-4705-831b-72f2891bebf9)

**Comment by photopea** [comment]
I never used your extensions :( If you dont know which one is blocking ads, could you try to disable them all?

I tried using Photopea in MS Edge and ads run fine.

**Comment by photopea** [comment]
Did it help to disable your extensions? I think just one of them was blocking ads.

**Comment by JulioCesarBR11** [comment]
do you have a app discord? to resolve problem?

**Comment by JulioCesarBR11** [comment]
my Nickname : jcbr2010

**Comment by photopea** [comment]
I discuss Photopea issues here on Github.

I think your problem could be disabled if you disable your adblockers (or disable all of your extensions, if you dont know which of them are blocking ads). Did you try to disable all of your extensions?

**Comment by JulioCesarBR11** [comment]
sorry i use addblock in youtube for no have a youtbe shorts hence interfered with Photopedia 😓

**Comment by photopea** [comment]
You should not have any ad blockers, if you want to see ads in Photopea. You can use Photopea in the incognito mode, if you want your ad blockers to be disabled.
