### ISSUE TITLE
every time i click on my picture it reduces to fucking atoms

### ISSUE THREAD

**Issue by VOIDGTAG** [photopea/photopea#6662]
Your Operating System: Windows 11
Your Web Browser: AVG Secure Browser
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by camoody1** [comment]
Sounds like a "you" problem. Much like your language and how you ask for help.

**Comment by photopea** [comment]
Sorry, we do not reply to requests which contain offensive words.
