### ISSUE TITLE
Cannot warp!

### ISSUE THREAD

**Issue by fiogob** [photopea/photopea#6665]
Your Operating System:
Your Web Browser: Chrome and Firefox
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by fiogob** [comment]
This bug report is a complicated system to operate - please make it easier! I am having a problem. I disabled by adblocker but still had the problem so went premium. But the issue is not solved. It worked once but now it isn't working. I can't warp text. Sometimes the png I upload appears but even when it has the 'handles' (squares) on it, they won't move. What am I doing wrong. It seemed so simple the first time I did it.

**Comment by fiogob** [comment]
I've gone premium and it still says that an adblocker is detected. HELP!!!!!!!!!!!

**Comment by photopea** [comment]
Hi, could you try this?
https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I need some description, what should I do to see it myself. Also, tell us, if it happens when none of your browser extensions is modifying Photopea.

I can refund you, if you tell me your name, or an email, or the payment ID.

**Comment by fiogob** [comment]
Thanks - would appreciate the refund. I've tried it in Incognito and updated my Chrome browser and it's still not working; and still (sometimes) saying I've got an adblocker when I've disabled it. This a typical screen I get, even when I'm Incognito. I get the symbol of the little square face with a downturned mouth. Sometimes (though rarely) the image I want appears - but mostly it doesn't. If the image appears and I manage to get to warp, it's just super unresponsive for some reason. Just way too glitchy or way to something for my needs. Sorry about that.

Name: Fiona Goble, email address: fkgoble@btinternet.com

![image](https://github.com/photopea/photopea/assets/167574865/e3be8c69-84b9-4abd-8ea4-903689c8eeb0)

**Comment by photopea** [comment]
I have sent you a refund.

Could you describe exact steps, what should I do to see the warp not working? Or at least record a video of you opening www.Photopea.com in the Incognito mode, and what you do next, to make the problem happen.

**Comment by camoody1** [comment]
Avast, CCleaner, Malwarebytes AND AVG Anti-virus... There's no wonder your internet is glitchy. Also, when you see advertisements for games like that on your sidebar, it means you're browser is STILL blocking Photopea's real ads. Those are just "fake" ads that appear when the real ads are being blocked. I suspect one or more of your multiple virus apps are causing you issues.

**Comment by fiogob** [comment]
Thanks, everyone, for your help. Really appreciated. I am still getting the message that I have an adblocker even though I removed AdBlock—I can't think where the adblocker is that seems to be 'switched on'. But I am getting ads in Incognito, and the editor seems to be working okay there, so I will carry on using it in Incognito. However, if anyone can think where an adblocker could be hiding on Chrome, please let me know!

**Comment by photopea** [comment]
If a website acts differently in Incognito than in a regular mode, it is because of your browser extensions. How do you decide which of your extensions to call an ad blocker? All extensions have permissions to modify a website.

Did you read this article? https://www.photopea.com/tuts/photopea-says-i-am-blocking-ads-but-i-am-not/

**Comment by fiogob** [comment]
Thanks. I had something called AdBlocker so that was obvious. I installed it to stop endless ads on YouTube. I really don't know about the others - this is so much more complicated than I thought. I don't have a huge amount of extensions, so I'll have a look through them when I get a moment. Thanks for the comment. I'm learning a lot here!

**Comment by bluep55** [comment]
If you clink on the icon arrowed, it should show you what extensions you have and which ones have current access.
![Screenshot Extensions](https://github.com/photopea/photopea/assets/118609932/2ca8dfcf-6845-459d-be77-6ce40913b998)

**Comment by photopea** [comment]
I will close it now. It is up to you what extensions you install. We can not "fight" your extensions - extensions have more power than websites. You can always run Photopea without your extensions in the Incognito mode.
