### ISSUE TITLE
Mudar fonte

### ISSUE THREAD

**Issue by Kakacriativa** [photopea/photopea#6666]
Não estou conseguindo usar algumas fontes.
Digito o texto, mas quando clico em outra fonte não consigo mudar
Geralmente ocorre com novas fontes carregadas
Alguém teve esse problema e conseguiu resolver?

**Comment by photopea** [comment]
If you type a letter, which is not available in your font, Photopea will switch the typing to a different font, which should support your character.

But if you select a part of text, you can apply a new font to that selected part (to every letter).
