### ISSUE TITLE
Clicking and dragging in the text color picker adds every visited color to the recent colors bar

### ISSUE THREAD

**Issue by TheFullestCircle** [photopea/photopea#6667]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open a new project and select the text tool
3. Click on the color field for the tool (NOT the one in the bottom-left)
4. Click and drag

**Comment by photopea** [comment]
I remember this was very hard to fix, because it would broke some other behaviour, which users wanted to have. We can delete the "recent colors bar" completely.
