### ISSUE TITLE
SLOW TO OPEN

### ISSUE THREAD

**Issue by arjayethPSU** [photopea/photopea#6668]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Hi, are you located in Vietnam / Phillippines / Australia? Some users report they can not open Photopea there (it loads slowly).

**Comment by arjayethPSU** [comment]
> Hi, are you located in Vietnam / Phillippines / Australia? Some users report they can not open Photopea there (it loads slowly).

Yes im from Philippines so slow to open need 3mins to open

**Comment by photopea** [comment]
I tried it here: https://geotargetly.com/geo-browse  and it says it works in Philippines. So maybe just one specific internet provider is blocking Photopea. Who is your internet provider? Could you ask them about it?

**Comment by photopea** [comment]
Are you a client of CONVERGE? https://twitter.com/Converge_CSU  

Seems like thousands of clients of CONVERGE can not open Photopea, but none of them asked CONVERGE about it, so I had to ask them: https://twitter.com/photopeacom/status/1782449022394826830 , but I have never been to Philippines.

**Comment by photopea** [comment]
Does it work now? Nobody reported it in a while, so maybe your internet provider is not blocking Photopea anymore.

**Comment by arjayethPSU** [comment]
Goodday sir yes its working fine now and i notice my utp got bite from rats😂

**Comment by photopea** [comment]
ouch, really? Show us a photo!
