### ISSUE TITLE
BUG in setting opacity to the folders

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#6669]
Your Operating System: Windows 10
Your Web Browser: Chrome (PWA) 123.0.6312.123
The problem happens in the Incognito Mode, too: YES

**This must be done to see the problem**
1. Go to www.photopea.com
2. open www.photopea.com/#igIBPKTjn
3. select first folder in the layers palette and the last folder (with shift)
4. hit 5 on the keyboard to set the opacity of folders to 50%

only the first one looks as it should - all others get the 50% opacity not on the folder but on the layers inside the folder

**Comment by photopea** [comment]
You are changing the opacity of **all selected layers**. When you use Shift, you select **all layers between the first and the last one**. If you want only to select folders, use Ctrl.

**Comment by MichalSZZ** [comment]
wow - it is a very strange behavior... What do you think? I tested it now in Photoshop and it works there the same, but I don't understand why...

**Comment by MichalSZZ** [comment]
I asked few of my friends (graphic designers with many years of skills) how should it work "in theory". All of them said, it should change only the opacity of the folder. It is logical for them. When they did the steps - they can't believe how does it work in Photoshop. For the graphic designers it is a nonsense. They said - (in theory) it can eventually works like that, only when all folders would be expanded with layers visible (then the layers would be selected too).
Why the one folder get the 50% opacity for the folder (and layers inside keeps the opacity) and all others work have different behavior? Is it logical for you?

**Comment by photopea** [comment]
Yes, it is logical. The opacity changes for all selected layers (a folder is a layer).  If you select all layers, between a Folder 1 and a Folder 2, it selects all layers inside a Folder 1, but no layers inside a Folder 2. Opening / closing a folder has no effect on this.

Below, I clicked on Folder 1, and then, with Shift, clicked on Folder 2. Five layers are selected, and the opacity of these layers will change.
![image (3)](https://github.com/photopea/photopea/assets/15955558/1a350e40-69ae-47af-b40e-5885c400b132)

**Comment by photopea** [comment]
Yes, it is logical. The opacity changes for all selected layers (a folder is a layer). If you select all layers, between a Folder 1 and a Folder 2, it selects all layers inside a Folder 2, but no layers inside a Folder 1. Opening / closing a folder has no effect on this.

Below, I clicked on Folder 1, and then, with Shift, clicked on Folder 2. Five layers are selected, and the opacity of these layers will be changed. If you dont want to change the opacity of Layer 4/5/6, do not select them! Select only Folder 1 and Folder 2 (e.g. with the Ctrl key).
![image (3)](https://github.com/photopea/photopea/assets/15955558/04179aa0-8d42-42a6-add6-ebc29dd130fa)

**Comment by MichalSZZ** [comment]
OK - thank you for clarifying it to me. As it works the same in Photoshop I think the issue can be closed.
