### ISSUE TITLE
Text is not wraps

### ISSUE THREAD

**Issue by Ser-Gen** [photopea/photopea#667]
When I use long word without spaces, its letters can overflow text layer.

In Gimp and PS this not happens.

For example, I use `asdasdasdasdasdasdasdasdasdasd`.

Photopea
![image](https://user-images.githubusercontent.com/1856145/39173177-9d1d535a-47ac-11e8-9ac6-6729d7039625.png)

Gimp
![image](https://user-images.githubusercontent.com/1856145/39173099-5e9e1434-47ac-11e8-8384-a48bdb03acd4.png)

Photoshop
![image](https://user-images.githubusercontent.com/1856145/39173110-68c76942-47ac-11e8-9da8-93be894c1881.png)

Is there setting to break line, like `word-wrap: break-word;` in css?

**Comment by photopea** [comment]
Hi. The text rendering mechanism is described here: https://www.photopea.com/learn/text . Photopea can not do word breaking yet. I think it would need different rules for each language.  

Do you often have words with 30 characters? Why don't you make the text box larger?

**Comment by Ser-Gen** [comment]
> Constrained text - defined by the rectangle. Words are wrapped automatically into multiple lines to fill the rectangle.

Maybe it more about consistency, but sometimes I just need to copypaste text from somewhere.
If I choose constrained mode then it must wrap all text.

**Comment by photopea** [comment]
Constrained text wraps all the text. Only if the word is larger than the text box, it continues outside. I think it never happens in practice (wide words and narrow text boxes are very rare).

**Comment by photopea** [comment]
I guess you are right. So should we just break the line before the first character, that is outside the box? Or maybe you could use some program to add spaces after each comma in your text.

**Comment by Ser-Gen** [comment]
>should we just break the line before the first character, that is outside the box?

Yes, this seems correct.

>Or maybe you could use some program to add spaces after each comma in your text

Rules for this program could be hard to define.
Users can use `-`, `/`, `\`, `:` and other symbols.

**Comment by photopea** [comment]
It is hard to implement into the current code, so I am giving it up. Also, I think a word (a sequence of characters with no spaces) makes more sense on one line, than on multiple lines.
