### ISSUE TITLE
Without adblocker photopea does not work

### ISSUE THREAD

**Issue by yqxq** [photopea/photopea#6670]
Photopea works with Adblocker (Adblock Ultimate) on my mac with Firefox, but I get the request to disable it. If I do so, the layout gets ruined and becomes unusable.
With Adblock Ultimate:
![Schermafbeelding 2024-04-23 om 11 42 39](https://github.com/photopea/photopea/assets/145245534/2974a4a5-78ae-4f59-80ef-d40ca3235c69)
With adblocker disabled:
![Schermafbeelding 2024-04-23 om 11 42 51](https://github.com/photopea/photopea/assets/145245534/53fe3cf7-ee78-4960-9aa8-17e95d59352c)

**Comment by photopea** [comment]
Do you use any other browser extensions? Did you try to turn them off?

Is your Firefox updated? What vesion of Firefox do you use?

**Comment by yqxq** [comment]
It is a pretty old FIrefox (68.9.0 ESR), but it is fine, Photopea works great on it with Adblock active. As I said, with the extensions disabled the site does not work. So without Adblock it is unusable.

**Comment by photopea** [comment]
We might block the usage of Photopea for people who block ads in the future.

BTW. both of your screenshots look wrong. I really recommend you to look for some more modern browser to run Photopea. Have you tried it in Safari, Chrome or Edge?

**Comment by photopea** [comment]
I will close it now.

**Comment by yqxq** [comment]
I don't want to block ads, but I have to otherwise it does not work. No, I have no newer browsers, as I like Photopea to give me a pretty decent photo editing on my older computers.

**Comment by photopea** [comment]
You could try Opera or some experimental browser like Vivaldi. 

BTW. how powerful is your machine? Press More - PeaMark, and do the CPU / GPU test, it takes 5 seconds.
