### ISSUE TITLE
30 favourite fonts isn't enough

### ISSUE THREAD

**Issue by Sefrautic** [photopea/photopea#6672]
### Discussed in https://github.com/photopea/photopea/discussions/6644

<div type='discussions-op-text'>

<sup>Originally posted by **Sefrautic** April 11, 2024</sup>
Hi, first of all I would like to thank you for all the great work you're doing with photopea, great job!
My issue is that the amount of favourite fonts isn't enough for me. I've read the old 2018 thread and saw that you increased the amount to 30. And there is still no plugin for managing fonts as I know of.

To be honest, why is this amount should be restricted? Is it memory concern? Maybe fav. fonts could be stored locally, like actions?
There is a lot of fonts in photopea and I just wanted to make my personal list of fonts that I would browse through, because it's quite cumbersome if you're going to do it through the full list. </div>

**Comment by photopea** [comment]
You can mark up to 100 favourite fonts now.

But I sitll think it is wrong to mark so many fonts in practice. It is like opening dozens of tabs in your web browser. It becomes messy and not very useful, even though you might feel like it is useful.

Spending some time picking up 30 favourite fonts is better than marking random fonts blindly.
