### ISSUE TITLE
svg and paths broke from 10 days ago

### ISSUE THREAD

**Issue by rfprogram** [photopea/photopea#6673]
Complicated svg, saved ok despite many layers - we were highlighting and combining layers (to reduce the number) via select+right-click on Layers tab with no problem, 10 days ago. Each group is basically a thicker stroke rectangle and bunch of thinner stroke spikes. Combining in this way was no problem - stroke thickness preserved, background color preserved. Note that this is ONE move: highlight, right-click, merge layers. It will take time but we will not break physically.
We open it today, and the first three sets only color in one segment, and turns off all strokes. Result is half invisible. The layer is visible. Nothing else is different. So we go up to the menu, combine shapes > unite, then manually have to put the stroke width and color back in. Fine, it's x5 the work but it works.
Then after the third set, with nothing different, the spikes suddenly won't take any stroke length. It's just a blank box. 
This was an svg generated by procgen, so all these sets are totally identical. 
![Screenshot 2024-04-23 at 13-23-30 Photopea Online Photo Editor](https://github.com/photopea/photopea/assets/167910650/74971d1b-2e75-4fbc-931d-e449de94a51e)
![Screenshot 2024-04-23 at 13-23-45 Photopea Online Photo Editor](https://github.com/photopea/photopea/assets/167910650/edfbab62-c907-4320-9337-7f951b7dbb00)
There is NO difference. I was doing nothing different 30 seconds before. No other processes are different. Even the order we did it is exactly the same. This is a new file with less than 20 items in History. Reloading all of the program and starting over doesn't work either. 
Recently we have noticed other problems with the .ai and .svg files with not preserving different stroke and fill information on merge or unite shapes, but this is the most perplexing with no visible fix.
We have not yet expanded the file (in image size) but we suspect it will be extra broken there, too - rendering all our work nullified. 

edit: we want to stress that this worked well enough 10 days ago that we got through 20 of these blocks. Not the individual rectangles. But a whole block of these rectangles. The program had no problem with it then. And yes, our adblock has never targeted Photopea. 

Your Operating System: windows 10
Your Web Browser: Firefox (updated in interim so it might be this)

**Comment by photopea** [comment]
Please, fill out an issue template, with steps to reproduce the problem.

**Comment by rfprogram** [comment]
I thought that's what I just did? That is step by step what I did to reproduce the problem, with descriptions of the menu and screenshots. I have no idea what else you want. 
Also, I replicated the problem in a brand new file. After 5 turns, the command to change stroke information stops working.

**Comment by photopea** [comment]
Could you write step 1, step 2, step 3 ... ?

I opened up www.photopea.com . What should I do now? I dont heven have your SVG. I do not see what is in your screenshot.
