### ISSUE TITLE
Someone created a new git about Photopea

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6675]
https://github.com/Alexander-Burns/Photopea/issues

I 've just come across this, because i've got called in one of the threads.

This is really weird.

It is totally a bot. But there is a way to delete it?

**Comment by Alexander-Burns** [comment]
@TheRadicalDreamer No. Opening the Photopea is working in the past, I cannot be deleted. It's not a bot, it's a human.

**Comment by photopea** [comment]
I think there is nothing wrong with somebody naming their repository "photopea". It is up to people to be able to find "real photopea".

**Comment by Alexander-Burns** [comment]
You are right.

**Comment by TheRadicalDreamer** [comment]
> I think there is nothing wrong with somebody naming their repository "photopea". It is up to people to be able to find "real photopea".

Totally agree, but this guy is answering non-sense on your git as well.

> @TheRadicalDreamer No. Opening the Photopea is working in the past, I cannot be deleted. It's not a bot, it's a human.

Like this....

Or like this issue:  
https://github.com/photopea/photopea/issues/6684

**Comment by Alexander-Burns** [comment]
I agree with you.

**Comment by photopea** [comment]
ok, I have blocked @Alexander-Burns from writing in my repositories
