### ISSUE TITLE
Claiming I'm blocking ads, even thou it's whitelisted

### ISSUE THREAD

**Issue by James76x** [photopea/photopea#6676]
Great site! - however, it has started to complain that i'm blocking the ads, but I have whitelisted that site (see the green thumb)..

![screenshot-fixthephoto com-2024 04 24-07_33_47](https://github.com/photopea/photopea/assets/163297639/4b9b4764-36ab-4805-a5b5-c6dd374626d7)

**Comment by photopea** [comment]
As @camoody1 says, use it at www.Photopea.com . 

Also, check out this article: https://www.photopea.com/tuts/photopea-says-i-am-blocking-ads-but-i-am-not/

**Comment by James76x** [comment]
Wait a moment, now i'm lost, so https://fixthephoto.com/online-gimp-editor.html is a "fake" fraud site that is taking credits from photopea?

**Comment by photopea** [comment]
Anybody can insert Photopea into their webpage for free.

**Comment by James76x** [comment]
Ah.. didn't know that :) .. thnx for the information
