### ISSUE TITLE
[FEATURE REQUEST]: Save To PSD when typing the text and merging the layers after using the rectangle tool

### ISSUE THREAD

**Issue by Alexander-Burns** [photopea/photopea#6679]
@TheRadicalDreamer: When saving to PSD when typing the text and merging the layer after using the rectangle tool, you cannot merge backgrounds or background layers.
Steps to Reproduce:
1. Type the text in Photopea.
2. Merge layers but not background.
3. Save as PSD.
This feature works in Chile and other Latin American countries. See videos, screenshot, and the .PSD file. If you do not see the .PSD file, zipping the files automatically.
[Screen recording 2024-04-24 10.17.02.webm](https://github.com/photopea/photopea/assets/113866683/7efd1676-b4a6-4dc3-b5c4-bc82242868d0)
![Screenshot 2024-04-24 10 18 54](https://github.com/photopea/photopea/assets/113866683/a49105db-a532-4c90-a327-549ceaa5b4f8)
[Pasalo Chancho.zip](https://github.com/photopea/photopea/files/15095842/Pasalo.Chancho.zip)

**Comment by photopea** [comment]
Photopea works as it should in your video. I think you should learn how to use Photopea at www.photopea.com/learn

**Comment by Alexander-Burns** [comment]
Thanks, I'll check it out.
