### ISSUE TITLE
Brush drawing is edgy

### ISSUE THREAD

**Issue by Ser-Gen** [photopea/photopea#668]
When I draw lines fast enough, they become edgy.

![pp](https://user-images.githubusercontent.com/1856145/39173868-9c1364fc-47ae-11e8-8672-b04d8befaaf0.gif)

Maybe use something from [disjukr/croquis.js](https://github.com/disjukr/croquis.js)
They have neat [demo](http://labs.crosspop.in/Croquispop/croquispop.html).
And lines looks smooth.
![croquis](https://user-images.githubusercontent.com/1856145/39173639-ff9ce42c-47ad-11e8-8809-82c411d04744.gif)

**Comment by photopea** [comment]
This looks very interesting. The mouse is tracked at 60 FPS, so Photopea gets 60 mouse positions per second (and nothing in between). But maybe this artifficial smoothing would be good.

**Comment by photopea** [comment]
It was fixed. When you move the mouse very fast, the "corners" are smoothed out.

There is another new feature - "pulled string" drawing. You can increase smoothing from 0 to X percent. The brush will not follow the cursor, but it will be "pulled on a string" behind the cursor.

**Comment by photopea** [comment]
Pulled string drawing was inspired by this feature in Photoshop: https://helpx.adobe.com/content/dam/help/en/photoshop/using/pulled-string-mode.gif 

The "analog" version of this probably existed for centuries.

**Comment by Ser-Gen** [comment]
It's so great, thank you!
