### ISSUE TITLE
[FEATURE REQUEST]: Opening (CTRL+O) a file with screenshots instead of blank .PSD file

### ISSUE THREAD

**Issue by Alexander-Burns** [photopea/photopea#6682]
@TheRadicalDreamer: Opening (CTRL+O) a file with screenshots instead of the blank .PSD file in Photopea. This screenshot is the same .PSD file and this video is the full feature. This works in Mexico, Guatemala, and other Latin American countries such as Chile. See videos and screenshots.
![Screenshot (1)](https://github.com/photopea/photopea/assets/113866683/bab05faa-6cf2-4b8d-a1d0-3ce856800b20)
![Screenshot (2)](https://github.com/photopea/photopea/assets/113866683/37439e6e-ee2e-48c8-aef9-02e8474385dd)
[Screen recording 2024-04-24 10.42.25.webm](https://github.com/photopea/photopea/assets/113866683/51343848-2dbd-4de1-adfb-b8e1b8d004de)

**Comment by photopea** [comment]
What you are saying makes no sense to me. I think you are a bot.
