### ISSUE TITLE
[BUG]: If you hide the layer in "Shape 1", it shows the text, but if you show the layer in same shape, it hides the text, blacking out of the text

### ISSUE THREAD

**Issue by Alexander-Burns** [photopea/photopea#6683]
@TheRadicalDreamer: If you hide the layer in "Shape 1", it shows the text, but if you show the layer in same shape, it hides the text, blacking out the text in Photopea.
Steps to Reproduce:
1. Select with the rectangle tool, observing black squares.
2. Show or hide the layer that's blacking out of the text or showing the text in white screen, invisible to type text.
See video and screenshots of the bug showing the black square in the text layer, no visible text when you hide the layer, but if you show the layer, the text is visible.
![Screenshot (3)](https://github.com/photopea/photopea/assets/113866683/fe5009b8-787f-434a-8d4f-040a8d6453ab)
![Screenshot (4)](https://github.com/photopea/photopea/assets/113866683/837737c4-7332-4f1b-a28d-02ba03377455)
[Screen recording 2024-04-24 10.52.48.webm](https://github.com/photopea/photopea/assets/113866683/3eac8ee6-176c-4ecc-80f4-f06f0bfae537)

**Comment by photopea** [comment]
Photopea works as it should in your video. Black text on a black background is still black.
