### ISSUE TITLE
In Crop Tool, if you crop the background, the text still visible with black backgrounds, you can also move the background

### ISSUE THREAD

**Issue by Alexander-Burns** [photopea/photopea#6684]
@TheRadicalDreamer In Crop Tool, if you crop the background, the text still visible with black backgrounds, but you can still move on the black backgrounds in Photopea.
Steps to Reproduce:
1. In New Project, click on the Crop Tool.
2. Crop the background but not text.
You can still move on the black background. But not white background on a text, see video and screenshot.
[Screen recording 2024-04-24 11.48.56.webm](https://github.com/photopea/photopea/assets/113866683/2af34ac8-df08-4436-a996-45e7374fde1a)
![Screenshot (5)](https://github.com/photopea/photopea/assets/113866683/ffa84dd4-5edc-4f94-b5f1-d3bde9935141)

**Comment by photopea** [comment]
You did not explain what the problem is.

**Comment by Alexander-Burns** [comment]
Great!
