### ISSUE TITLE
Cannot zoom any further with background and text

### ISSUE THREAD

**Issue by Alexander-Burns** [photopea/photopea#6685]
@TheRadicalDreamer: The text and background cannot zoom any further in Photopea.
Steps to Reproduce:
1. Click on the zoom tool.
2. Zoom in smaller or zoom out further, or zoom in further or zoom out smaller.
This video can't be uploaded with larger than 10 MB in Github, but you can e-mail at alvaroguzmanp@gmail.com in Gmail. See screenshots of the bug but cannot zoom further.
![Screenshot 2024-04-24 12 02 22](https://github.com/photopea/photopea/assets/113866683/445a5426-883c-473a-9d87-f5d5464e5726)

**Comment by photopea** [comment]
What you are saying makes no sense to me.

**Comment by Alexander-Burns** [comment]
I agree with you.

**Comment by TheRadicalDreamer** [comment]
It is a Bot Ivan

**Comment by Alexander-Burns** [comment]
Why? ***@***.*** is not a bot, it's a human.
