### ISSUE TITLE
If you hide the text in layers, it hides the text, but if you show the text, it shows the text in background

### ISSUE THREAD

**Issue by Alexander-Burns** [photopea/photopea#6686]
@TheRadicalDreamer If you hide the text in layers, it hides the text, but if you show the text, it shows the text in background.
Steps to Reproduce:
1. Type the text with text tool.
2. Hide or show the text in layers.
This bug has hiding the text in layers, but showing the text if you click on "Square" layer icon. See videos, screenshots, and .zip file.
[El Texto.zip](https://github.com/photopea/photopea/files/15097438/El.Texto.zip)
![Screenshot (6)](https://github.com/photopea/photopea/assets/113866683/6f7b9171-3548-4bd0-b777-99edf2419dc1)
![Screenshot (7)](https://github.com/photopea/photopea/assets/113866683/aca6e0c0-c1a4-4543-90f7-5026ee981f0c)
[Screen recording 2024-04-24 12.13.51.webm](https://github.com/photopea/photopea/assets/113866683/e2e5f4aa-8c36-4caa-9868-d8d5b74c942f)

**Comment by photopea** [comment]
What you are saying makes no sense to me :(
