### ISSUE TITLE
select / color range have default cursor, it can be hard to pick color from pixel when  cursor is too big

### ISSUE THREAD

**Issue by saffmila** [photopea/photopea#6687]
Your Operating System: PC
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2.  make cursor really big
3.  pres Select / Color range
4. .try to sample pixel color.. its almost imposible to find pixel to sample, because of huge cunsor.. 
Suggestion - change cursor to small only during color range function

**Comment by photopea** [comment]
Hi, what is "make cursor really big" - how do I do it?

**Comment by photopea** [comment]
I have to close it because of no response from the user.
