### ISSUE TITLE
Changing the text size to 80 pixels overlaps words in both layers and when moving the photo, it moves

### ISSUE THREAD

**Issue by Alexander-Burns** [photopea/photopea#6688]
@TheRadicalDreamer Changing the size to 80 pixels overlaps words in both layers and moving the photo moves in Photopea.
Steps to Reproduce:
1. Change the text size to 80 pixels overlaps words in both layers.
2. Move the photo.
Changing the text size to 24 pixels won't overlap in text size. See video and screenshot of the bug.
[Screen recording 2024-04-24 13.02.19.webm](https://github.com/photopea/photopea/assets/113866683/f1c481f7-1f0d-45a2-8f6f-21bc1dbf0e96)
![Screenshot (8)](https://github.com/photopea/photopea/assets/113866683/f3175032-1ea5-4c2a-b98e-ec18daa45ca5)

**Comment by photopea** [comment]
What you are writing makes no sense. You should improve your AI.
