### ISSUE TITLE
Cannot type the text, it's not visible, but visible in the text layer

### ISSUE THREAD

**Issue by Alexander-Burns** [photopea/photopea#6689]
@TheRadicalDreamer Cannot type the text, it's not visible, but visible in the text layer in Photopea.
Steps to Reproduce:
1. Open Photopea.
2. Create the new project.
3. Load the text.
4. Type the text.
Invisible in the white screen but visible in the text layer. See video and .zip of the bug.
[screen-capture (2).webm](https://github.com/photopea/photopea/assets/113866683/95baa265-c62d-415f-bec2-ee8c790d8759)
[Test Text.zip](https://github.com/photopea/photopea/files/15098223/Test.Text.zip)

**Comment by photopea** [comment]
What you are writing makes no sense. You should improve your AI.
