### ISSUE TITLE
Program stop working after operation in layers panel

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#669]
![github-freeze](https://user-images.githubusercontent.com/38118273/39219535-5b56524e-482b-11e8-9ea7-a754cc0aa4f1.png)

I had this bug for the first time, but I saw that many times on other computers (mac, pc, different browsers).
All the program freeze and only few things works.
I think it may be something with layers/folders, becouse it happend after operations in layers panel (grouping, deleting).
https://youtu.be/1wQY2Iz4LMI?t=19

**Comment by photopea** [comment]
Hi, I would like to reproduce it. Could you send me your PSD file to support@photopea.com, so I can repeat the steps that you did? Or could you maybe find a shorter instructions, that leads to the same problem?

**Comment by MichalSZZ** [comment]
Hi, today, all is OK when I try to repeat that, what I made in the night. I was send the PSD file.
I send PSD file.
This is not the first time (first time for me) but I have students on my graphic design lessons and I saw that many time. 
Today I also have lessons and I will try to look at more, what is the reason if such a problem occurs.

**Comment by photopea** [comment]
Hi, I can not reproduce it from your file :(  Maybe you could find some specific steps, that always lead to the problem.

**Comment by photopea** [comment]
Michal, you are awesome!

The bug happened only to those, who select layers with Shift (If you use Ctrl, it never happened). I fixed it and it should work well now. Thanks again for your help!

**Comment by MichalSZZ** [comment]
Thanx again! That was very frustrating bug for my students.
