### ISSUE TITLE
Invisible text when selecting in Color Picker while using rectangle tool

### ISSUE THREAD

**Issue by Alexander-Burns** [photopea/photopea#6690]
@TheRadicalDreamer Invisible text when you select the color in the Color Picker while clicking the rectangle tool in Photopea.
Steps to Reproduce:
1. Open Photopea.
2. Create a new project.
3. Click on "Text Tool".
4. Type the text.
5. Click on "Rectangle Tool".
6. Add the rectangle with color.
7. Select all the colors in the Color Picker.
8. Click OK or Save.
Selecting all the colors, invisible text. See video of the bug.
[screen-capture (3).webm](https://github.com/photopea/photopea/assets/113866683/4cd43641-f345-4d53-871e-d899f66733c0)

**Comment by photopea** [comment]
What you are writing makes no sense. You should improve your AI.
