### ISSUE TITLE
Cannot zoom in on Photopea

### ISSUE THREAD

**Issue by Alexander-Burns** [photopea/photopea#6691]
@TheRadicalDreamer Photopea cannot zoom in, so nothing's happening when you click on zoom in icon.
Steps to Reproduce:
1. Open Photopea.
2. Open (CTRL+O) a file with screenshots.
3. Zoom out in Photopea.
4. Try to zoom in.
Nothing's happening when you click on zoom in icon in Photopea. See videos of the bug.
[screen-capture (4).webm](https://github.com/photopea/photopea/assets/113866683/f0878160-3eb5-4db0-800a-7e5ef4aef8a7)

**Comment by photopea** [comment]
What you are writing makes no sense. You should improve your AI.
