### ISSUE TITLE
RAW Photos open as black image, sliders do nothing

### ISSUE THREAD

**Issue by vawade15** [photopea/photopea#6692]
Your Operating System: Windows 10, Windows 11
Your Web Browser: Chrome, Normal and Incognito
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Attempt to upload a RAW photo
3. When the RAW processing window appears, the image preview will be completely black, the sliders do nothing, and the histogram shows an all black image
4. JPEG and other file types open just fine.

**Comment by photopea** [comment]
sorry, it should be fixed now.
