### ISSUE TITLE
I can't resize an image or text

### ISSUE THREAD

**Issue by SheLuvVegas** [photopea/photopea#6693]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Import an image or text
3. I can't resize an image or text at all 
4. ....

**Comment by camoody1** [comment]
Perhaps record a short video of your entire Photopea screen while you're attempting these actions. I've not seen anyone else reporting this issue.

**Comment by photopea** [comment]
I think this is a bot. "importing text into Photopea" makes no sense, since Photopea can only open images. So I am closing it.
