### ISSUE TITLE
Photopea

### ISSUE THREAD

**Issue by angelaiaru** [photopea/photopea#6695]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....I can't open files in photopea
3. ....
4. ....

**Comment by photopea** [comment]
Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because of no response from the user.
