### ISSUE TITLE
Cannot Open JPEG

### ISSUE THREAD

**Issue by KatieB92** [photopea/photopea#6696]
Your Operating System: Mac and Windows
Your Web Browser:Safari and Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. File > Open
3. JPEG image
4. Image opens multiplied, and in greyscale. 

I have attached an example scan and a screen shot of how it looks in photo pea. 

Thank you 
Tried on two computers, many different images. Please note the images were scans of watercolour paintings which I am trying to edit for invitations. 
![File_000](https://github.com/photopea/photopea/assets/168173910/bbe9cdc6-e46a-4f7b-8d4f-a4719bd23743)

<img width="1440" alt="Screenshot 2024-04-26 at 08 56 04" src="https://github.com/photopea/photopea/assets/168173910/0defbe7b-926e-400e-8dd9-22ebdeae7336">

**Comment by photopea** [comment]
Your JPG image has a bug in it. I have fixed - the fixed version is below.

![325895303-bbe9cdc6-e46a-4f7b-8d4f-a4719bd23743](https://github.com/photopea/photopea/assets/15955558/d1d87364-428d-46da-abc2-3b4895a61fb1)

**Comment by photopea** [comment]
BTW. I have updated our JPG decoder, Photopea should be able to handle your original JPG file now :)
