### ISSUE TITLE
Unblock my premium Account 

### ISSUE THREAD

**Issue by Photopea24** [photopea/photopea#6698]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....I have paid the premium account
3. ....but I get blocked ! 
![Photopea receipt](https://github.com/photopea/photopea/assets/168183540/cec625c4-f80a-47c8-85d1-fd79e2c1967f)
![photo blocks layers](https://github.com/photopea/photopea/assets/168183540/00819ac2-b0fc-40ff-8e41-29d160484235)

4. ....

**Comment by photopea** [comment]
Hi, what do you mean by "getting blocked"? It seems like you have entered the quick mask mode: https://www.photopea.com/learn/selections#:~:text=or%20Ctrl%20%2B%20D).-,Quick%20Mask%20Mode,-There%20is%20a

You should press Q to escape the quick mask mode.
