### ISSUE TITLE
Shapes with pixel perfect snapping/looking

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#670]
Can you add new function? 
Snapping shape to pixel values without any comma?
Width, Height, X, Y position in integers only.
This can only be for preview and export as raster graphics.

Photoshop have "Align Edges" checkbox ON/OFF (OFF by default) in top toolbar for the shapes.
When it is ON, shape have not antialiasing pixels (when edge is for example in the middle of pixel) and all is sharp in preview/export.

**Comment by photopea** [comment]
Hi, I thin I changed the behaviour in a good way.

Most of vector drawing tools are snapped to pixels. Free Transform is also snapped to pixels (when there is no rotation). Tell me if it is better now.

**Comment by MichalSZZ** [comment]
Yes. Now it works great (no transparent pixels on shapes that have values without comma) 

Thank You!
