### ISSUE TITLE
photopea not loading templates

### ISSUE THREAD

**Issue by Commander17X** [photopea/photopea#6700]
Your Operating System: windows 
Your Web Browser: edge
The problem happens in the Incognito Mode, too: idk not tested but the problem is that the site is not able to pull the templates directory
**This must be done to see the problem**
1. Go to www.photopea.com
its  
step 2 see: ![image](https://github.com/photopea/photopea/assets/67329580/741a0f94-fa2a-49d1-8110-d21a5374b49f)

**Comment by photopea** [comment]
Hi, it should be fixed now.
