### ISSUE TITLE
travamentos 

### ISSUE THREAD

**Issue by Nmkzzz** [photopea/photopea#6701]
bom quando eu utilizo a função de "caneta" para transformar minha imagem em PNG chego em uma determinada parte da imagem que começa a travar muito, e as vezes acontece de travar e não voltar mais, fazendo com  que eu perca todo meu projeto que não foi salvo ou algo do gênero. 

video:
https://youtu.be/lQMob4-jbQU?si=93y3hZEJG4UacEcr

Espero que consiga perceber os travamentos, não é sempre que acontece, mas dependendo do arquivo ou do tempo que está fazendo, ele começa a travar com frequência.

**Comment by photopea** [comment]
Did it crash in your video? I am confused.

**Comment by photopea** [comment]
I have to close it, because the person did not respond, and I can not make it happen myself.
