### ISSUE TITLE
Type tool doesn't work

### ISSUE THREAD

**Issue by joydesign777** [photopea/photopea#6702]
Your Operating System: Window10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Cilick Type Tool
3. Try to type anything
4. Nothing happens

**Comment by photopea** [comment]
I think your steps will not work. You must open or create a document first, to type into it. Did you try to create a document?

**Comment by photopea** [comment]
I have to close it, because the person did not respond.
