### ISSUE TITLE
Black background when resizing a image smaller

### ISSUE THREAD

**Issue by greenred1922** [photopea/photopea#6703]
This happens on every platform, Happens on incognito mode aswell.

When i try to resize an image to make it smaller a black box randomly appears and goes away when i make the image bigger again.
![size small](https://github.com/photopea/photopea/assets/168272487/73226520-e3f4-4115-ad26-7ddbad4bd5dd)

![size large](https://github.com/photopea/photopea/assets/168272487/1d3f9058-7b8a-47df-8b03-e1ae5cf956d0)

Edit: I turned off WebGL and still didn't fix the issue.

Edit 2: I tried restarting and using google instead of the downloaded version, Still doesn't fix.

Edit 3: It never did this about 2 months ago.

**Comment by DISAKIS** [comment]
Same Issue here. Happens on safari aswell as chrome. Only happens at specific image dimension in my case

**Comment by photopea** [comment]
Could you save that document as a PSD and share it here in a ZIP? Because I can not make it happen myself, so I can not fix it.

**Comment by CarrotOrangelight** [comment]
[Scale Please.zip](https://github.com/photopea/photopea/files/15138018/Scale.Please.zip)
First Time I join this issue. Here you go.

**Comment by photopea** [comment]
sorry guys, I introduced this bug an hour ago. It should be fixed now. Clear your cache or wait an hour (our cache lasts for an hour in your computer).

**Comment by DISAKIS** [comment]
Heres an alternative version of a file containing the issue:
[Issue.zip](https://github.com/photopea/photopea/files/15138036/Issue.zip)
