### ISSUE TITLE
[Suggest] Putting adjustment layer's reset button on bottom bar

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#6704]
Now that the properties panel has a bottom bar, I would suggest putting the reset button on the bottom bar, like photoshop. The name of adjustment layers in the panel could also be removed to make the panel cleaner.

![New Project](https://github.com/photopea/photopea/assets/79258245/17c02edf-98ed-4f2b-9442-6091ad288578)
In photoshop, the reset button is to the left of the eye button.

**Comment by photopea** [comment]
Ok, I have placed the button to the bottom.
