### ISSUE TITLE
photo pea takes up nearly 3GB ram

### ISSUE THREAD

**Issue by WashiestWig2477** [photopea/photopea#6705]
photopea takes up nearly 3 GB of ram when editing a 16 pixel image and is sometimes unusable

**Comment by photopea** [comment]
Could you show us some proof? E.g. steps to make it happen?

**Comment by WashiestWig2477** [comment]
make a 16 pixel image on google chrome
start drawing random stuff for 20 minutes
the tab will eventually reach over 2.8 GB ram
sometimes it also happens when i have multiple layers of photos
some times it gets laggy alot
![image](https://github.com/photopea/photopea/assets/102556151/2fd73dcc-873d-4082-bb2b-ad211a273ba2)
![image](https://github.com/photopea/photopea/assets/102556151/78e3a4af-1268-43f1-ba08-d76d57e3fb83)
this time i was able to get it only up to 1.2GB of ram usage but i didnt have time to wait

**Comment by camoody1** [comment]
I followed the steps in the first comment using Microsoft Edge for 20 minutes and my RAM usage never exceeded 450MB. Of course, I'm using the Premium version with no advertisements, so that could be the difference.

**Comment by photopea** [comment]
Also, are you able to make it happen while not using any browser extensions?

**Comment by photopea** [comment]
I think the web browser should regulate this. Using a lot of RAM is not a problem, as long as there is enough RAM for each app.
