### ISSUE TITLE
unable to move more than one layer

### ISSUE THREAD

**Issue by pinkjimrussiagirl** [photopea/photopea#6709]
Your Operating System: Windows 11
Your Web Browser: Microsoft Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. select 2 layers
3. attempt to move them

this has just happened right now, earlier on it did let me move 2 layers and it's just now that it is not letting me move more than 1 layer
![image](https://github.com/photopea/photopea/assets/111091825/d11f5228-3179-46c6-8d0b-2d9a68a16e88)

**Comment by bluep55** [comment]
One of your layers has a Selection round it. Go to Select > Deselect to deselect it, then try.

**Comment by photopea** [comment]
You can either move layers (any number of layers), or a selected part of one layer. If you have a selection, it means you want to move a selected part of a layer. I recommend you to learn about selections here: https://www.photopea.com/learn/selections
