### ISSUE TITLE
Suggestion: WOFF file format support

### ISSUE THREAD

**Issue by Baegus** [photopea/photopea#6711]
It would be nice if Photopea could import WOFF (web font) files just like it can open TTF and others. I mainly use the app for web-related stuff and this would be really handy.

**Comment by photopea** [comment]
Do you have many WOFF fonts on your computer? I think there must exist OTF versions of these fonts somewhere.

**Comment by Baegus** [comment]
> Do you have many WOFF fonts on your computer? I think there must exist OTF versions of these fonts somewhere.

Sure, there ususally are standard versions alongside WOFFs, but let's say you wanna work on an existing project and you only have the finished website (which uses smaller WOFF files) available. In that case, it would be faster to use those files instead of looking for the originals.

**Comment by photopea** [comment]
Photopea should handle the WOFF files now. However, it can not handle WOFF2. WOFF2 uses a Brotli compression, so we would need some tiny Brotli decompressor in JS to handle it.
