### ISSUE TITLE
Liquify tool not working on small images (error in JS console)

### ISSUE THREAD

**Issue by danhowardms** [photopea/photopea#6713]
I had initially thought that this error was happening on all images, but it seems to only affect small ones.  I have attached an example that illustrates the problem.

Your Operating System: MacOS Ventura
Your Web Browser: Chrome and/or Safari
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open a small image (for example, the attached tabletop.jpeg)
3. Choose Filter -> Liquify
4. Attempt to use a liquify tool anywhere on the image
5. Expected: the image is morphed by the tool.  Actual: The image does not change, there is a RangeError reported in the javascript console:

pp.js:1410 Uncaught RangeError: offset is out of bounds
    at Uint8Array.set (<anonymous>)
    at S.WB (pp.js:1410:156)
    at dK.uQ (pp.js:12344:14)
    at dK.a3_ (pp.js:12359:93)
    at dK.p (pp.js:12335:41)
    at kd.LqFy.ZG (pp.js:12889:86)
    at kd.LqFy.aes (pp.js:12877:6)
    at kd.LqFy.qM (pp.js:12872:63

Note that the example image, tabletop.jpeg is 600x300px.  If you resize the image up to 1800x900px (within Photopea) then try the liquify tool again, it seems to behave normally.

**Comment by danhowardms** [comment]
![tabletop](https://github.com/photopea/photopea/assets/44200241/918fe389-6c9a-48e9-99b7-c11d1d3a329c)

**Comment by photopea** [comment]
I am very sorry, it should be fixed now. Please, clear your cache or wait an hour before opening Photopea again.

**Comment by danhowardms** [comment]
Thanks for fixing the bug so quickly, and thanks for your efforts making this fantastic tool. 👍
