### ISSUE TITLE
PDF or PSD cannot be opened in Photoshop or Illustrator

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6714]
Your Operating System: Chromeos
Your Web Browser: Yes
The problem happens in the Incognito Mode, too: YEs

**This must be done to see the problem**
1. Download and open this PSD that i've created in Photopea: https://drive.google.com/file/d/1_QwNDQabh_22lX3PmBvbv7y3jAFC8BBa/view?usp=sharing
2. Open and export it as PDF
3. Open the PDF in Adobe Illustrator or Photoshop
4. It should give you an error
![image](https://github.com/photopea/photopea/assets/11801254/c979633c-1395-4ed8-a91c-4b0976c61f20)
![image](https://github.com/photopea/photopea/assets/11801254/d80347ba-2cb9-4084-82f6-784078f46397)

**Comment by photopea** [comment]
It happened only when you used "Vectorize text". It should be fixed now.
