### ISSUE TITLE
peadrive:   HTTP error: 401 : User's secret was already generated

### ISSUE THREAD

**Issue by ihartaras** [photopea/photopea#6716]
Your Operating System: Android, Windows
Your Web Browser: Chrome, Edge
The problem happens in the Incognito Mode, too: No, but white page on peadrive

premium account
datataras@gmail...

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
hey, it should be fixed now :)

**Comment by ihartaras** [comment]
Yes, it's working. Thanks!
