### ISSUE TITLE
Install Button does not work

### ISSUE THREAD

**Issue by JinXAlt** [photopea/photopea#6717]
Your Operating System: Windows
Your Web Browser: Opera, Google, Firefox are the ones I use
The problem happens in the Incognito Mode, too: The install button does not work (both with and without an adblocker)

**This must be done to see the problem**
1. Go to www.photopea.com
2. Press on the install button
3. You will see there is no response

**Comment by photopea** [comment]
So make sure there are no extensions in Chrome which can change information in Photopea, and then, tell us, if it the Install button works or not.

![VDzo5rg](https://github.com/photopea/photopea/assets/15955558/e9884803-771b-4992-9506-03ab76715d8c)

**Comment by JinXAlt** [comment]
Hello,
I mainly use Opera GX but with other browsers, with absolutely no
extensions it still doesn't work. But after using Edge it finally worked.
Don't know what is happening with the other browsers. Must be an internal
issue.

Thankyou

**Comment by photopea** [comment]
For me, in a regular opera, the "Install" button appears, but it does nothing when clicked :(
