### ISSUE TITLE
Give us access to clipboard

### ISSUE THREAD

**Issue by Zorakie** [photopea/photopea#6718]
Your Operating System: Windows 11 23H2 build 22631.3447
Your Web Browser: Firefox (Developer edition) 126.0b5 (64-bit)
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create an empty project
3. Try to paste any screenshot you have in your clipboard (e.g. previously taken with WIN+SHIFT+S

Instead of pasting, nothing happens and Photopea asks for permissions to clipboard. However, there is no link or guidance how to do it, even the browser does not pop up any permission box. I am not aware of having any restrictions in place.

Sometimes, Photopea reload helps, sometimes not, and it even happened to me that it stopped working in the middle of the project, after I have previously successfully pasted something.

**Comment by photopea** [comment]
I can not see this problem in a stable release of any web browser :( The image is inserted perfectly into Photopea running in Firefox (the latest stable release).

I think it is a bug in your "Firefox (Developer edition) 126.0b5 (64-bit)", so you should report it to the authors of your browser. Photopea is made according to the current web standards, and now, it is up to a browser to support the web standards.

See here - "too new browser" - https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/
