### ISSUE TITLE
Photopea extension for Stable Diffusion A111 not working with Firefox (ok on Chrome)

### ISSUE THREAD

**Issue by NatalieWright17** [photopea/photopea#6719]
Your Operating System: Windows 10
Your Web Browser: Firefox 125.0.3 (64-bit) (Up to date)
The problem happens in the Incognito Mode, too: Yes

Everything was working fine up until this afternoon. When I go to the Photopea tab, no background canvas shows, I can't drag and drop files to open, and I can't open files. (They open but I can't see anything in the window, but can see that there's layers. The extension seems to work on Chrome, but it's not my system default so I'm trying to figure out how to get Firefox to work again for it. Going directly to the photopea website works fine also through Firefox. I have cleared my cache, reinstalled Firefox, reinstalled the Photopea extension. It worked briefly I thought after clearing my cache, but quickly broke again, and clearing my cache once more did nothing. I'm not very tech savvy so I have run out of ideas on fixing this problem. 
[](https://i.gyazo.com/41df77e1eb20d17ad7d519d19a18c27b.png) (Shows no canvas background.)

**Comment by photopea** [comment]
I have never used the thing that you are talking about, and I am not the author of it.

You should report this to the author of A111 or whatever app / website you are using.
