### ISSUE TITLE
Vectorizing of small image is not working

### ISSUE THREAD

**Issue by Ser-Gen** [photopea/photopea#672]
I have problem with vectorizing of small image (13×15): ![cart](https://user-images.githubusercontent.com/1856145/39328474-2a68b8c8-49a4-11e8-85f8-5636f3b0c446.png)

What I got

![small](https://user-images.githubusercontent.com/1856145/39329204-457f9274-49a6-11e8-857e-ef4fd16c4395.png)

When I make image two times larger (26×30), it can be vectorized.

![larger](https://user-images.githubusercontent.com/1856145/39329776-1d43b25c-49a8-11e8-861e-966d3e9b1573.png)

**Comment by photopea** [comment]
Our algorithm deletes "garbage" - tiny shapes or holes. The "size" of the hole is deduced from pixels (1 pixel is too small). Increase the resolution before using a vectorizer.
