### ISSUE TITLE
Feature request: Mouse wheel zoom in/out without holding keyboard key

### ISSUE THREAD

**Issue by ihartaras** [photopea/photopea#6720]
Could you please consider adding an option in preferences to switch between mouse wheel zoom and vertical scroll? CAD-like software users have been requesting this feature for Photoshop for many years, and Adobe finally implemented it. Adding this option to Photopea would be highly appreciated. Thank you!

**Comment by ihartaras** [comment]
![Screenshot_20240503_120648_Shadow PC](https://github.com/photopea/photopea/assets/38782554/cd331478-ca07-4465-b22e-e273442fe3ed)

**Comment by photopea** [comment]
I have implemented this feature! You can enable it in Edit - Preferences.

However, Photopea can not distinguish a mouse wheel from a two-finger trackpad scrolling. So the Trackpad will work exactly like a wheel, too.
