### ISSUE TITLE
Adblocker prompts when adblockers are disabled

### ISSUE THREAD

**Issue by rainy421** [photopea/photopea#6721]
Your Operating System: Windows
Your Web Browser: Chrome

I have an adblocker installed but have disabled it for Photopea (so I'm seeing ads on the page). I'm still getting annoying pop-under messages telling me I'm using an adblocker and that I can make a one-off payment to turn off ads (this usually happens when exporting an image). Is there any way for you to make this not happen when someone's already disabled their adblocker?

**Comment by camoody1** [comment]
@rainy421 Post a screenshot of your Photopea screen and the ads that you're seeing. Most likely, you're seeing the "placeholder" ads that the developer puts there when an ad blocker is blocking the real ads that actually make him some money. His placeholder ads are about his own free games that he's made over the years.

**Comment by photopea** [comment]
Your ad blocker is probably still blocking ads. See this article: https://www.photopea.com/tuts/photopea-says-i-am-blocking-ads-but-i-am-not/
