### ISSUE TITLE
HTTP error 401: User's secret was already generated.

### ISSUE THREAD

**Issue by davidxmejia** [photopea/photopea#6722]
Your Operating System: macOS
Your Web Browser: Chrome / Safari
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Log in
3. Go to PeaDrive
4. Error message appears

I am receiving this error message (HTTP error 401: User's secret was already generated) when I try to access my PeaDrive. I would appreciate some help. Thank you!

**Comment by photopea** [comment]
Could you tell me your email address that you use to log in to Photopea.com ?

**Comment by davidxmejia** [comment]
david.mejia365@gmail.com

**Comment by photopea** [comment]
It should be fixed now. Please, close Photopea and open it again.

**Comment by davidxmejia** [comment]
Thank you! Working all good now.
