### ISSUE TITLE
Photopea dosent load sometimes

### ISSUE THREAD

**Issue by Thatsnice1938** [photopea/photopea#6723]
Your Operating System:Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yea

**This must be done to see the problem**
1. Go to www.photopea.com
2. Sometimes you get a white screen

**Comment by photopea** [comment]
I can not see a white screen :( In what country are you located? Maybe this is the reason: https://twitter.com/photopeacom/status/1782677713607639448

**Comment by Thatsnice1938** [comment]
Philippines :(

**Comment by photopea** [comment]
Please, get in touch with your internet provider and ask them about it. You pay them a lot of money, they should let you access the whole internet.
