### ISSUE TITLE
Transform controls not working

### ISSUE THREAD

**Issue by 60enzo60** [photopea/photopea#6724]
Your Operating System:
Your Web Browser: Chrome

**This must be done to see the problem**
1. Go to www.photopea.com
2. Place a Image
3. Click Transform controls
4. Try to Transform it
And it wont work.

**Comment by photopea** [comment]
I have heard of bug with Free Transform in Brave. Are you sure you dont use Brave?

Did you try to use Photopea in a web browser with no browser extensions, that have access to modifying Photopea? E.g. in the incognito mode?

**Comment by 60enzo60** [comment]
What is Brave? I'll try to use incognito mode.

**Comment by photopea** [comment]
Did it help?

**Comment by photopea** [comment]
I have to close it because of lack of details.
