### ISSUE TITLE
Color picker for New Color Fill Layer does not retain last color selected

### ISSUE THREAD

**Issue by lardofdorkness** [photopea/photopea#6725]
Your Operating System: macOS Monterey v12.7.4
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Select Layer > New Fill Layer > Color Fill
3. Select a color in the Color Picker by clicking inside the color field and/or adjusting the slider. Make sure to click somewhere within the color field, not close to the edges (this makes it easier to demonstrate the effect).
4. Note the position of the marker indicating the selected color within the color field, then click OK to create the layer.
5. Again, select Layer > New Fill Layer > Color Fill
6. Notice that the selected color marker in the Color Picker has "dropped" to the bottom (y-axis). The horizontal position of the marker (x-axis) from the previous time is retained.

**Comment by photopea** [comment]
I can not reproduce it :( When I press Layer > New Fill Layer > Color Fill, it always starts with the Foreground color (the color at the bottom of a toolbar).

**Comment by lardofdorkness** [comment]
I see that now. Since my foreground color is almost always black it wasn't obvious. But it looks like what happens is that when the foreground color is black (and the color picker marker is in the far bottom left corner), and I add a color fill layer of a different color, the next time I add a color fill, the marker is still at the very bottom, but has moved horizontally to the position of the color chosen for the previous fill layer. It's still black (000000) but the marker seems to have been influenced by the previous selection, making it seem like it should have preserved the vertical position as well.

Is it intentional/necessary for the color fill to default to the foreground color? The main reason for this post was that it seems buggy (or at least inconvenient) for it not to retain the color of the previous color fill layer. I tend to use the same color for all color fills, something other than black, so it would be handy to have it hold onto the previously selected color.

**Comment by bluep55** [comment]
I just tried this in Photoshop and it works exactly the same. It defaults to the Foreground colour.

**Comment by lardofdorkness** [comment]
Can it be different in Photopea? :-) Aside from it being that way in Photoshop, do folks find it preferable to have it default to Foreground color, or can you see the value in having it retain the last color chosen from a previous color fill?

Again, some of the confusion surrounding this has to do with the fact that the selected color for a color fill changes the horizontal position of the marker for the foreground color, if the foreground color is black (000). Since the selected color for the color fill influences the horizontal position, it seemed like it should retain the vertical position as well.

**Comment by photopea** [comment]
To make two Color Fill layers of the same color, make one and duplicate it.

Or when you enter a color, copy its HEX value and paste it next time you select a color.
