### ISSUE TITLE
Navigation controls in Open from Storage/Save to Storage show as boxes

### ISSUE THREAD

**Issue by lardofdorkness** [photopea/photopea#6726]
Your Operating System: macOS Monterey v12.7.4
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Select File > Open more > Storage...
3. Connect to PeaDrive or Google Drive.
4. The navigation buttons at the top of the window all appear as boxes.
5. It is the same when Saving to Storage.

**Comment by photopea** [comment]
I have replaced the characters with SVG icons of an arrow. Thanks for reporting it!

**Comment by photopea** [comment]
BTW. what do you think about the buttons at the top right corner? Is it clear what they are for?

**Comment by lardofdorkness** [comment]
Do you mean the buttons for changing the sort element (Date/Name/Size) and display type (Tiles/Icons/List)? Yes, once you cycle through the options for each one and see the effects, they make sense. I have made the mistake before of clicking the X within that browse window rather than the one on the window itself, disconnecting from the drive when I meant to just close the view. That was a learning moment, and now I'm always careful to use the right X to close the window. :-) Thanks for fixing the buttons!

**Comment by photopea** [comment]
You are welcome :) You can learn more about the storages here: https://www.photopea.com/learn/storages
