### ISSUE TITLE
Bug when zooming using keyboard commands

### ISSUE THREAD

**Issue by lardofdorkness** [photopea/photopea#6727]
Your Operating System: macOS Monterey v12.7.4
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open any project/image.
3. Press and hold the Command key, and keep it pressed for the next three steps.
4. Press the + key one or more times to zoom in. The image is zoomed in.
5. Without releasing the Command key, press the - key one or more times to zoom out. The image is zoomed out.
6. Again without releasing the Command key, press the + key to zoom in. The image continues to zoom out. This is the bug. :-)
7. After releasing the Command key and pressing it again, the + key zooms in as expected.
8. Note that this only happens when trying to zoom in after zooming out, but not when zooming out after zooming in.

**Comment by photopea** [comment]
Sadly, it is a bug in Mac OS and we can not fix it :( https://github.com/photopea/photopea/issues/4409
