### ISSUE TITLE
Difference in Duplicate Layer results if selected from menu versus Command-J

### ISSUE THREAD

**Issue by lardofdorkness** [photopea/photopea#6728]
Your Operating System: macOS Monterey v12.7.4
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open an image or an existing project with content in a layer.
3. Select a layer that has some content, and create a selection around a portion of the content.
4. From the menu, select Layer > Duplicate Layer (note that the keyboard shortcut is Command-J). The entire layer is duplicated into a new layer.
5. Now press Command-J. Only the selected content is duplicated into a new layer.

Both functions have their uses and merits, so is this a bug or a feature? :-) Other than the results, there doesn't appear to be any indication that the functionality should be different based on the method of triggering it, so presumably they should behave the same. I can also copy and paste a selection to create a new layer with just the selected content, so if anything the Command-J behavior may be extraneous. I noticed this a long time ago and I'm mostly just curious about it. :-D

**Comment by photopea** [comment]
I have fixed it. They are two different features:

Layer - Duplicate Layer
Layer - New - Layer Via Copy (Ctrl+J)
