### ISSUE TITLE
Pixelated vectorizing

### ISSUE THREAD

**Issue by Ser-Gen** [photopea/photopea#673]
It will be nice, if PP could convert small image to pixelated svg, without line smoothing.

Just like left one.

![larger](https://user-images.githubusercontent.com/1856145/39329776-1d43b25c-49a8-11e8-861e-966d3e9b1573.png)

**Comment by Ser-Gen** [comment]
I want to use this svg in icon font to change color of icon with css.
This app can take svg and convert it into font's glyph:
https://icomoon.io/app/

**Comment by photopea** [comment]
Maybe we could add a checkbox "keep pixel structure" ... but I think only 0.00001 % of people need this.

**Comment by Ser-Gen** [comment]
I can use shape tool and save image to svg in my case #677

**Comment by photopea** [comment]
If you increase the image size (Image Size - 1000%, Nearest interpolation), the vectorizer will detect that you want sharp edges.
