### ISSUE TITLE
Smart Object Layer distorted, color changed to blue or purple

### ISSUE THREAD

**Issue by Larisa-ops** [photopea/photopea#6730]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Place your PSD file inside (which is a mockup). This file is very large and has multiple copies of the principal Smart Object Layer.
3. Open the principal Smart Object Layer.
4. Place your design inside.
5. Save and return to the principal tab.
6. Here is where the problem appears. The original design is distorted, changed color to blue or purple. 

This problem only appears in large files and/or files that have multiple copies of the principal smart object layer. For example, in my case, I had a sticker pile mockup. There was the principal design sticker, and in the background were multiple copies of it. 

Bug:
![Screenshot 2024-05-06 114102](https://github.com/photopea/photopea/assets/136504414/1ef5d30f-11a5-421f-82a2-adb660f241e2)

How the design should look:
![Screenshot 2024-05-06 114200](https://github.com/photopea/photopea/assets/136504414/d3c2a244-ace9-4d62-b68f-25bd600ffaed)

**Comment by Larisa-ops** [comment]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**Comment by Larisa-ops** [comment]
How the final result should look: 
![Screenshot 2024-05-06 114938](https://github.com/photopea/photopea/assets/136504414/e8c7a373-2088-44d9-aff2-5066082ec79f)

This file works in photoshop normally.

**Comment by photopea** [comment]
I think I will not be able to fix it without seeing it happen myself. And for that, I think I need your PSD files. Could you share them with us?

**Comment by Larisa-ops** [comment]
Of course, please indicate an email, and I will send it asap! I'm not sure how GitHub works. I tried to enter in your profile, but there is no email or an option to send a message.

Thank you so much for the fast reply.

**Comment by Larisa-ops** [comment]
In case sharing an email is not possible on this platform, I created a Google Drive folder with the file:
https://drive.google.com/drive/folders/1tlPmSb_oelWTA0qn2HUGc-a0ICLrGCB9?usp=sharing

I'm going to give permission to access it when I receive the request. Thank you again!

**Comment by photopea** [comment]
I just sent you a request.

**Comment by Larisa-ops** [comment]
I accepted it, and you should be able to have access now.

**Comment by photopea** [comment]
Thanks a lot, it should be fixed now! :)

**Comment by Larisa-ops** [comment]
Wow, it works! Thank you so much! Amazing work!
