### ISSUE TITLE
Enhancement request for storage file manager

### ISSUE THREAD

**Issue by lardofdorkness** [photopea/photopea#6731]
Would you consider making the following addition to the file manager for storages?

- Include the last modified date/time information as a separate column in the List view. I see that it appears in the title tags of the file elements, but it would be useful to have it displayed for all items in the file list as well.

Thank you!

**Comment by photopea** [comment]
Sure, I have added a column for it! :)

**Comment by lardofdorkness** [comment]
Hi, thank you for adding this! Could I ask another small favor, to have the date shown as mm/dd/yyyy instead of dd.mm.yyyy, or do you think more Photopea users would prefer it as you have it? I know it's more of a US thing to put the month first. :-D Thanks again!

**Comment by photopea** [comment]
Ok, now, it should show the date according to the local settings of your system.
