### ISSUE TITLE
Hachures sur mes photos 

### ISSUE THREAD

**Issue by Vinou82** [photopea/photopea#6734]
Bonjour, je rencontre un problème avec Photopéa. 
En effet, toute mes photos que j'ouvre avec ce logiciel se transforment et des hachures apparaissent sur chacune de mes photos. 
Je suis actuellement élève à l'EDAA et je ne peux pas avancer sur mon devoir à cause de ce problème. Est-ce que quelqu'un pourrait m'aider ? 

Veuillez trouver ci-joint des exemples de ce que je vous raconte. 
Merci beaucoup

![Capture d'écran 2024-05-07 224155](https://github.com/photopea/photopea/assets/169249341/50080c5f-51d1-495c-a390-1be24a212609)
![Capture d'écran 2024-05-08 105215](https://github.com/photopea/photopea/assets/169249341/a02fe411-3fd0-4150-b3b8-0d24a067fbfc)
![Capture d'écran 2024-05-08 112310](https://github.com/photopea/photopea/assets/169249341/0f4db01e-e691-493d-9745-5e0f78a7b7e6)
![Capture d'écran 2024-05-08 112408](https://github.com/photopea/photopea/assets/169249341/d8c4cfd9-5e18-4a77-b5e4-bada5762638a)

**Comment by photopea** [comment]
Hi, could you share one of your photos with us?

**Comment by Vinou82** [comment]
Le problème est réglé pour le moment. J'ai utilisé Photoshop pour faire mon
devoir en attendant mais si le problème persiste en repassant par photopea
alors je vous en informerai. Merci quand même

**Comment by photopea** [comment]
Let me know if there is anything I could help you with.
