### ISSUE TITLE
Selection Expand / Contract with 16-bit images

### ISSUE THREAD

**Issue by vawade15** [photopea/photopea#6735]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Upload and process a RAW photo, open it up in 16bit color space
3. Select something and attempt to invert the selection
4. Attempt to use the magic wand tool or the "select subject" feature

**Comment by photopea** [comment]
Hey, it should be fixed now. But there is sitll a problem with Expand / Contract.

**Comment by photopea** [comment]
All features from Select- Modify should work on all bit depths now.
