### ISSUE TITLE
"disable Adblocker" prompt even though I'm not blocking Ads

### ISSUE THREAD

**Issue by Krazyplays** [photopea/photopea#6737]
Your Operating System: Windows 10
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
Done

"disable Adblocker" prompt even though I'm not blocking Ads
Quick Info: I did read the article about disabling adblock for photopea

I found 2 problems with your ad-display-system. 
1. Firefox comes with an antitrack feature (killing fingerprints and trackers) and the default setting (which is by no means meant to kill ads, only its tracking) kills your ad display. It doesn't show any prompt or custom ads, just nothing (maybe it does after some time, idk, but if, that also shouldn't be ig). I really suggest looking into that, the Anti-tracking feature is on by default and its really not meant to break ads and shouldnt need to be turned off.
2. I'm using the Windscribe (VPN) addon, which builds upon the UBlock addon (meaning its adblock functionality is just Ublocks code imbedded into the addon). In any case: You can whitelist any website each from the VPN connection and adblock functionality. But theres also the setting to block some trackers, that isn't meant to stop ads from working and that can't be turned off for individual websites. 

Idk if someone mentioned the issue I'm trying to point out here and I'm sorry if, but your ad-display-system seems to stop working, when that of other websites doesnt.

I've also done a quick test on [this](https://d3ward.github.io/toolz/adblock) website, each with everything on, the site whitelisted on every addon (but Firefox's & Windscribe's anti tracker on) and everything disabled.
Result was that disabling everything made no difference to just whitelisting the website on addons, resulting at "3%" Blockage (remaining seem Brand specific) and with "blocking on" resulting at 99%. Ofc that test might make no relevant statement in this case but I'm only trying to make a quick issue report here. 

Hope this somehow helped, really like your product and think that improving on this could be crucial to support Photopea through ads.

**Comment by photopea** [comment]
I just opened www.Photopea.com in the latest release of Firefox, installed at default settings, and the ads are displayed correctly.

If Photopea notices at least one domain which it can not access, we consider it to be ad-blocking.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
