### ISSUE TITLE
freezing when i work , impossible to save files 

### ISSUE THREAD

**Issue by loraine19** [photopea/photopea#6738]
Your Operating System: chomebook intercore i5
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes 
same issue after cleanings cookies , privat mode , other devices ... 

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
I have to close it because of lack of details :(
