### ISSUE TITLE
About metadata 

### ISSUE THREAD

**Issue by jmverges** [photopea/photopea#6739]
Hi there,

Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Execute script
```
// load the library
if ( ExternalObject.AdobeXMPScript == undefined ) {
    ExternalObject.AdobeXMPScript = new ExternalObject( "lib:AdobeXMPScript");
}
```
Should that works? if not, what is the way to work with metadata inside photopea via Scripting?

Many thanks

**Comment by photopea** [comment]
This is not supported in Photopea, and I am seeing it for the first time in my life. It is hard to tell if anybody else needs it. We usually implement only features that are needed by many people.

**Comment by photopea** [comment]
I will close it now.
