### ISSUE TITLE
Initial state of image

### ISSUE THREAD

**Issue by Ser-Gen** [photopea/photopea#674]
How can I restore initial state of image?

![image](https://user-images.githubusercontent.com/1856145/39330543-acd7ddba-49aa-11e8-8cbd-36bdda1f6fc0.png)

Maybe this issue is related to #454.

PS also has limited history, but always show initial state to return at start of editing.

My suggestions
1) Initial state of file in history panel.
2) Option to change size of history.

**Comment by photopea** [comment]
We used to have the unlimited history, but then, sometimes, Photopea ran out of RAM memory and crashed.

You should still have the original PSD in your computer, right?

**Comment by Ser-Gen** [comment]
There are might be some cases.
I can rewrite old file or even remove it.

**Comment by photopea** [comment]
Ok, I agree. There shuld be an initial history item, that will let us return to the original file.

**Comment by photopea** [comment]
it is very hard to implement, and nobody else asked for it since 2018, so I think it is not that important.
