### ISSUE TITLE
Wrong layer size in script

### ISSUE THREAD

**Issue by jxw1102** [photopea/photopea#6740]
Your Operating System: macOS 14.4.1 (23E224)
Your Web Browser: Chrome 124.0.6367.79 (Official Build) (arm64)

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open 2 psd files: for example, fileA and fileB
3. Copy pixels of fileA: ⌘+A then ⌘+C
4. Paste in fileB
5. Execute the following script

```
var layer = app.activeDocument.activeLayer;
alert(layer.bounds[2].value + 'x' + layer.bounds[3].value)
```

We can observe in the screenshot that, the size returned by script (757x997) is not the same as the size in Layer Properties (216x233).

<img width="1102" alt="Screenshot 2024-05-11 at 00 59 32" src="https://github.com/photopea/photopea/assets/1309108/6a64b5e8-fdb5-4085-bd3f-65b44b15297a">

Please make a fix. Many Thanks.

**Comment by photopea** [comment]
This it how it should work.  Layer.boudns does not contain the width and the height of a layer. They are the coordinates of the top left and the bottom right corner of a layer. Please see the documentation from the Adobe company to learn what each layer property means.
