### ISSUE TITLE
PDF - Stroke on text from settings and from layer style give different results when exporting

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6741]
Your Operating System: Chromeos
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**

1. Go to www.photopea.com and open this PSD [stroke layer.zip](https://github.com/photopea/photopea/files/15281292/stroke.layer.zip)

2. Export it to PDF
3. The thickness of the stroke is different when exporting
![image](https://github.com/photopea/photopea/assets/11801254/9104ca5d-cbda-4d69-b99f-a9ecf486c6fd)

Additionally: When the letters collide, depending on how you made the stroke on the text, the effect is different. Using stroke from the settings makes the words overlap, but with layer style they fuse. Even though, when exporting the words look the same.

**Comment by photopea** [comment]
I have fixed a problem with the stroke thickness. However, fixing the separate stroke for each letter would be very hard. I recommend putting each letter into a separate layer. Or create another layer on top with no fill, just a stroke.

**Comment by TheRadicalDreamer** [comment]
It is completely understanble the issue with the separate stroke of each letter, but then, can it be fixed the way they look on the editor?
![image](https://github.com/photopea/photopea/assets/11801254/4fa9b05c-c4d0-4220-a92d-619c3eddd6e1)

It should look like it looks when exporting, not different.

**Comment by photopea** [comment]
Just rasterize a layer. There are many other PSD features that are not exported into a PNG.
