### ISSUE TITLE
Photopea is appearing as a blank white screen.

### ISSUE THREAD

**Issue by raelynns** [photopea/photopea#6742]
Your Operating System: Windows 11 Pro Inspiron 5080
Your Web Browser: Opera GX
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. It does not appear.

**Comment by photopea** [comment]
Maybe this is your issue: https://www.reddit.com/r/photopea/comments/1cpi7wg/photopea_isnt_loading/

**Comment by raelynns** [comment]
Hello!

I forgot to close the thread, as now my Photopea works fine.
You can close the thread as completed!
