### ISSUE TITLE
"Select Pixels" is not working in 16 bit color mode

### ISSUE THREAD

**Issue by Noriych** [photopea/photopea#6743]
Your Operating System: Windows 10 Pro
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Change the color mode to 16 bit
3. Import any image or shape
4. Right click on a layer and click Select Pixels

It works fine on 8 bit color mode

**Comment by photopea** [comment]
it should be fixed now.
