### ISSUE TITLE
Failed to save the image using Saving to server from api

### ISSUE THREAD

**Issue by vedantdere** [photopea/photopea#6744]
Your Operating System:Windows
Your Web Browser:Chrome
The problem happens in the Incognito Mode, too:yes

I am returning the saved work to my server 
As given in the document I am able to get the json 
```
{
	"source" : "https://www.mysite.com/images/button.png",
	"versions" : [
		{"format":"psd", "start":      0, "size": 700000 },
		{"format":"jpg", "start": 700000, "size": 100000 },
		...
	]
}
```
and the binary data 
to save the file with the extension I am indexing from the json ending character to the start + size 
Is this correct way?

**Comment by photopea** [comment]
The JSON is always 2000 bytes, as described at https://www.photopea.com/api/ . So you should "slice out" the file from a byte 2000+"start" to a byte 2000+"start"+"size".

**Comment by vedantdere** [comment]
But in the response I received from the api the json is ending at approx. 36,000 after that binary data is there 
below I am attaching the response saved in text file 
also I am using the ending index of the json and slicing the binary array from the start + json_last_index to size + start + json_last_index 
the image is saved but its corrupted 
[output_new_compare.txt](https://github.com/photopea/photopea/files/15295617/output_new_compare.txt)

**Comment by photopea** [comment]
What is the "source" URL, that you give to Photopea? It should not be too long, to fit inside 2000 Bytes of JSON.

**Comment by vedantdere** [comment]
Its base64 of the image as shown in photopea documentation `https://www.photopea.com#STRING_VALUE`
I am facing issue with the saving output. I am able to separate json data and binary data. But while saving image from the binary data the image is not appearing.

**Comment by photopea** [comment]
You need to change that, as your huge "source URL" will not fit into 2000 Bytes of JSON. 

You can change the source attribute of a document by running a script 

    app.activeDocument.source = "new file"

See https://www.photopea.com/learn/scripts

**Comment by vedantdere** [comment]
Can i use GCP or S3 bucket url ?

**Comment by photopea** [comment]
Photopea will load any image from any URL. But it must uspport CORS, see https://www.photopea.com/api/

You can set the "source" parameter of a document to any string, even an empty string. This string parameter will be delivered to your server. The idea is, that you can put some "id" of the file into it.
