### ISSUE TITLE
Cannot save as anything other than PSD

### ISSUE THREAD

**Issue by erstwhileresonance** [photopea/photopea#6745]
Your Operating System: Windows 11
Your Web Browser: OperaGX

The site will not let me save projects as a png. The only format it allows is PSD. It's kind of difficult to see here, but I tried multiple times to save the project as a png, and it did not work.

https://github.com/photopea/photopea/assets/169607104/98543be7-276d-4201-af38-234f7636c0cd

I tried being lenient with site settings by turning off ads, allowing file access, and allowing pop-ups, but the problem persists. It will let me import png files but not save projects as a png file. The site also doesn't allow me to press the create new project button or install Photopea either.

**Comment by photopea** [comment]
Could you try to use Photopea in the Incongito mode, i.e. with none of your browser extensions running? Also, did it happen more than once, for more than one work of yours?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
