### ISSUE TITLE
page not responding

### ISSUE THREAD

**Issue by ndgalusa** [photopea/photopea#6746]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....windows 11
3. ....Edge
Took 3 hours to work on 3 SIMPLE files

**Comment by photopea** [comment]
I am confused, what should I do to see the problem which happened to you?

**Comment by jackblk** [comment]
@photopea I think what he meant is the script download is VERY slow. I'm from Asia, not sure if photopea has CDN or not but it's really really slow to load the js files.

![image](https://github.com/photopea/photopea/assets/12843654/c3beaa1c-fe6b-409d-9107-27bb2e49a4eb)

Can you consider using CDN for those static files to increase the download speed and avoid adding loads into your server?

**Comment by photopea** [comment]
I dont know how CDN works and I am a bit afraid to let millions of people access Photopea through "someone in between". They would be able to shut down Photopea for half of the world whenever they want.

Do you know why loading Photopea is so slow in your case? Did you try to ask your internet provider about it?

**Comment by jackblk** [comment]
@photopea no idea why it was so slow, but even with VPN (still in Asia), it's still very slow so I doubt it's related to my ISP.

> I dont know how CDN works and I am a bit afraid to let millions of people access Photopea through "someone in between".

CDN is safe and we should use it for static content. There are reliable ones (and free), you can try Cloudflare. I'm available for help if you need for setting up the CDN.

**Comment by photopea** [comment]
Ok, I will try to look into the CDN stuff. But only people from Asia report that Photopea is slow to load, it is something about the internet providers there. Maybe internet providers could fix it easily if they knew about it.

**Comment by photopea** [comment]
BTW. I am in Turkey now. If I use a Wifi in my hotel, Photopea opens in four seconds. If I create a wifi hotspot on my phone (turkish sim card), Photopea takes 5 minutes to load. So I think it is not about a country, but about an internet provider.

**Comment by rgex** [comment]
> Ok, I will try to look into the CDN stuff. But only people from Asia report that Photopea is slow to load, it is something about the internet providers there. Maybe internet providers could fix it easily if they knew about it.

I had already opened a ticket that Photopea was extremely slow to load in Cambodia (and it is still slow as fuck).
Now I told a friend in Bangkok about Photopea and his first reaction was: "That thing takes ages to load".
You are definitively losing users because of this.
I did tests and indeed from my servers in Europe the files load quickly.
I am confident this is a problem with your hosting provider, I would highly appreciate if you either use a CDN or try another hosting provider.

**Comment by photopea** [comment]
Photopea should use CDN now. Does it work better now?

**Comment by photopea** [comment]
It should work better in Asia now.

**Comment by photopea** [comment]
Could any of you guys tell me, if Photopea loads faster in your country now? Some parts are still not on the CDN (e.g. font thumbnails).

**Comment by jackblk** [comment]
@photopea it is certainly a lot faster on my side now, thank you!

> Some parts are still not on the CDN (e.g. font thumbnails).

They are a bit slow but it's not too bad like before. Acceptable.

**Comment by rgex** [comment]
I had no issue loading the site recently so it seems that the CDN has indeed solved the problem.
