### ISSUE TITLE
lag issue

### ISSUE THREAD

**Issue by JUULIANTHEHOOLIGON** [photopea/photopea#6748]
App is very laggy when trying to work takes forever to complete the littlest task

**Comment by photopea** [comment]
Could you tell me what to do to see Photopea laggy? Also, what is your PeaMark? See it in More - PeaMark.

**Comment by JUULIANTHEHOOLIGON** [comment]
its pretty easy to see start working on anything and within 10 minutes there's lag and it's 815 and 4632

**Comment by JUULIANTHEHOOLIGON** [comment]
like this is insane i lag every 10 seconds why is your app so laggy

**Comment by photopea** [comment]
Did you try to use Photopea without any browser extensions? I still can not make Photopea laggy, maybe I need browser extensions which will make it laggy (I do not use any at the moment).

**Comment by JUULIANTHEHOOLIGON** [comment]
im using the app as an external app

**Comment by JUULIANTHEHOOLIGON** [comment]
there shouldn't be a cause for lag

**Comment by JUULIANTHEHOOLIGON** [comment]
like how do you manage to screw it up so bad

**Comment by JUULIANTHEHOOLIGON** [comment]
like build a functioning app its not hard

**Comment by JUULIANTHEHOOLIGON** [comment]
cna't paint more than 2 pixels without the app freezing, paint brush dissappears randomly and the lags all on me thats a joke you guys dont know how to build an app plain and simple

**Comment by photopea** [comment]
We never made any app. Photopea is a website which should be used in a web browser at www.photopea.com . You have probably downloaded some virus. 1 million people used Photopea in the last 24 hours and nobody reported any lags.
