### ISSUE TITLE
Resize algorithm

### ISSUE THREAD

**Issue by Ser-Gen** [photopea/photopea#675]
When I make image larger, it looks partly blurry and sharp on sides.

Source

![cart](https://user-images.githubusercontent.com/1856145/39331067-35253ad6-49ac-11e8-981f-b13a030bcc28.png)

Result

![layer 1](https://user-images.githubusercontent.com/1856145/39331081-3dd3bad6-49ac-11e8-810a-c9af53c6df68.png)

Could you implement options for algorithm of resize?
At least, add nearest neighbour, please.

**Comment by photopea** [comment]
I implemented it. Now, you can choose between Nearest-neighbour and Bilinear interpolation. It is available for both Free Transform, and Image - Image Size.

**Comment by inkhsutesou** [comment]
Nearest Neighbour does not seem to work anymore did something change in an update ?

**Comment by photopea** [comment]
@inkhsutesou I just tried it and it seems to work fine. What exactly should I do to see it not working?

**Comment by inkhsutesou** [comment]
False alarm, sorry, very sorry, the image I was resizing had transparent pixels to begin with.  Please disregard.

Photopea is great !  Although I'm having trouble CTRL+C where Edit > Copy works but CTRL+C does not.  I have clipboard turned on.  But I'll add that in another issue.  Thank you

**Comment by photopea** [comment]
Copy-pasting with Ctrl+C works well for me. Can you disable all your browser extensions and try it again?

**Comment by inkhsutesou** [comment]
After resetting my extensions and refreshing photopea it seems to work well.  But I do think it has something to do with when Photopea is on for too long.  The behavior is

I copy from marquee tool, and have say .. Data A
I paste into another program.  aggie.io / paint / photopea and it pastes ..  Data A
I copy from marquee tool, and try to get .. Data B
I paste into another program, aggie.io / paint / photopea and it pastes .. Data A

I will try to capture video of it if it happens again.  Sorry if that is not very useful.

**Comment by photopea** [comment]
I tried to do what you described, but the new content (Data B) was pasted into another program :(
