### ISSUE TITLE
The Ads on the side of the page are making the website VERY Laggy.

### ISSUE THREAD

**Issue by Oliviaa2O24** [photopea/photopea#6752]
Your Operating System: Windows 10
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: (I don't use Incognito at all.)

**This must be done to see the problem**
1. Go to www.photopea.com
2. I open normally the stuff that I'll be working on.
3. While working, **There are "Ads" that pop up on the side of the website, which are making it lagging very much every couple of seconds!**

What's the best solution to avoid that?

**Comment by photopea** [comment]
Hi, what is your PeaMark? You can test it in More - PeaMark. Could you share a screenshot of the "popping up ad"?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
