### ISSUE TITLE
clipping mask is not working

### ISSUE THREAD

**Issue by SjBsunshine** [photopea/photopea#6754]
Your Operating System:  Apple
Your Web Browser:Safari/Google
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....upload simple .png of black fonts
3. checked that layers are merged
4. open and place another .png design
5. right click on the second design
6. hit clipping mask
7. nothing is happening

This past week I have followed these steps without issue. Today when it didn't work I tested with previous working .pngs and it still did not work.
9. ....
10. ....

**Comment by photopea** [comment]
What is "step 3"? If you open a PNG file, there is always only one layer. You can not merge any layers.

Clipping masks are related to transparency. Do your PNG files have transparency? You can get different results depending on your PNG files.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
