### ISSUE TITLE
[Request] Rearrange size/position input boxes in properties panel

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#6755]
In properties panel, focusing on width and pressing tab, the next one focused would be position x, and height, and position y. Could you please make it width, and height, and position x, and position y?
![屏幕截图 2024-05-16 021633](https://github.com/photopea/photopea/assets/79258245/3a223491-7514-4390-93d4-137a709d367d)

**Comment by Giwayume** [comment]
Would be better to simply rearrange the fields so width and height are next to each other instead of on top of one another.

Having a non-standard tab order is bad usability practice. Your expectations for tab order will be different from some other random user who anticipates it works like most websites (left to right, then top to bottom).

**Comment by photopea** [comment]
The TAB key will jump W-H-X-Y now.

What do you mean by a non-standard order? What is a standard order?

**Comment by Giwayume** [comment]
Standard is the default order a user would expect from visiting most websites, which is the default tab order that comes from the order the elements are placed in the DOM.

Most websites when building a vertical form will but related inputs next to each other on one row, then the next row will have another grouping of fields.

**Comment by Giwayume** [comment]
You probably don't have any blind users of a photo editor application, but screen readers are another reason changing the tab order to be different from the DOM order is not recommended. A screen reader in browse mode will traverse the page in DOM order no matter what. But in focus/forms mode tabbing will follow the tabindex order, which will cause major confusion to a blind user if you make them jump around all over the place in a way that does not match the order they experience in browse mode.
