### ISSUE TITLE
My screen is all black

### ISSUE THREAD

**Issue by LeoAndSabrina** [photopea/photopea#6756]
Your Operating System: Windows 11
Your Web Browser: Firefox

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open a new project

It is all black I don't know what to do!### ### ****

**Comment by photopea** [comment]
I just opened www.photopea.com in Firefox and my screen is not black.

Could you show us a screenshot of what it looks like? Are other websites black, too?

**Comment by LeoAndSabrina** [comment]
No, it is only Photopea. I can send you a screenshot soon.

**Comment by photopea** [comment]
Please, show me what it looks like.

**Comment by LeoAndSabrina** [comment]
![Photopea _ Online Photo Editor — Mozilla Firefox 5_16_2024 6_44_38 PM](https://github.com/photopea/photopea/assets/169955622/3d3a77e1-643a-4f92-8da4-cfedbe64042f)

**Comment by LeoAndSabrina** [comment]
Here you go.

**Comment by photopea** [comment]
What version of Firefox is it? Could you tell me the exact number?

**Comment by bluep55** [comment]
Top right of your screen it says "Ad blocking detected" Looks like you have an ad-blocker active. That could be your problem 😕.

**Comment by photopea** [comment]
I think they are using some experimental version of firefox with many bugs. I can not see such a problem in a regular firefox. The preson did not say what Firefox they use.

**Comment by LeoAndSabrina** [comment]
I don’t know how to see my version, and I am not using an experimental Firefox. I am using a ad blocker but I had it on before and it worked fine.Sent from my iPhoneOn May 17, 2024, at 3:23 PM, Photopea ***@***.***> wrote:﻿
I think they are using some experimental version of firefox with many bugs. I can not see such a problem in a regular firefox. The preson did not say what Firefox they use.

**Comment by LeoAndSabrina** [comment]
Found it, my Firefox version is 126.0 (64-bit)

**Comment by LeoAndSabrina** [comment]
![Photopea _ Online Photo Editor — Mozilla Firefox 5_18_2024 8_17_11 AM](https://github.com/photopea/photopea/assets/169955622/6f727ddd-e1cb-454b-91f2-c11e7b5a02e1)

It fixed itself, I don't know what happened for those couple days.

**Comment by LeoAndSabrina** [comment]
![Photopea _ Online Photo Editor — Mozilla Firefox 5_18_2024 8_17_11 AM](https://github.com/photopea/photopea/assets/169955622/fe5ffdbe-2db0-4989-8231-aa8fd03bb5cb)

It fixed itself. I don't know what happened for those couple days.

**Comment by photopea** [comment]
So it works after disabling WebGL? Did you try it in other borwsers? How old is your GPU / your computer?

**Comment by LeoAndSabrina** [comment]
I didn’t do anything.On May 18, 2024, at 3:43 PM, Photopea ***@***.***> wrote:﻿
So it works after disabling WebGL? Did you try it in other borwsers? How old is your GPU / your computer?

**Comment by photopea** [comment]
So it seems to work now. Let me know if it stops working again.

**Comment by LeoAndSabrina** [comment]
OkOn May 18, 2024, at 4:29 PM, Photopea ***@***.***> wrote:﻿
So it seems to work now. Let me know if it stops working again.
