### ISSUE TITLE
font wont load 

### ISSUE THREAD

**Issue by bigboitv** [photopea/photopea#6757]
every time i try to upload my font it wont i changed it before but now it just doesn't work

**Comment by photopea** [comment]
What should I do to see such an error? When loading a font, do you choose the option "Load next time you use the editor"? Do you press "OK" or "Cancel"? 

Maybe there are too many fonts, and your web browser does not allow Photopea to store more fonts. Please, see Edit - Local Storage, and remove some fonts. Or change the settings of your web browser.

**Comment by photopea** [comment]
I have to close it, because the person did not provide any details / proofs.
