### ISSUE TITLE
Can't buy a premium account

### ISSUE THREAD

**Issue by jangeerts** [photopea/photopea#6758]
Your Operating System:
Your Web Browser: FireFox 126
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. log in with a gmail account....
3. choose a premium option....
4. .Nothing happens, screen does't change (nor update) there's no way no way to pay..

**Comment by photopea** [comment]
Hi, are you pressing the button? Photopea should open a new window. Could you press that button and take a screenshot of your whole screen, and share that screenshot?
![image](https://github.com/photopea/photopea/assets/15955558/cb4052ec-bbce-442b-bc59-36364d8597c3)

**Comment by camoody1** [comment]
I'm guessing you have an extension that's causing you issues. Perhaps try disabling all of your extensions and see if it works for you. If it does, re-enable each extension one by one until you figure out which one is the culprit.

**Comment by jangeerts** [comment]
Half an hour later, it suddenly worked. I noticed today that there were disturbances in the internet connexion due to the bad weather.

**Comment by jangeerts** [comment]
Hi, Half an hour later, it suddenly worked. I noticed today that there were disturbances in the internet connexion due to the bad weather.  Thanks anyway.

**Comment by photopea** [comment]
ok, I am glad it works!
