### ISSUE TITLE
Vectorize Bitmap crashes Photopea

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#6759]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create new project with transparent background
3. Click Image/Vectorize Bitmap
4. Error appeared in console (Uncaught DOMException: Failed to construct 'ImageData': The source width is zero or not a number.) and nothing appeared in Vectorize Bitmap window and after I closed it and painted into layer with brush and tried again Image/Vectorize Bitmap function Photopea freezed and stopped working completely.

**Comment by photopea** [comment]
Thanks for reporting it! Vectorize Bitmap should not be available for empty layers now.
