### ISSUE TITLE
PSD: stroke is not rendered

### ISSUE THREAD

**Issue by Ser-Gen** [photopea/photopea#676]
[strange_border.zip](https://github.com/photopea/photopea/files/1955164/strange_border.zip)

In PS, if shape hasn't stroke, but has _stroke effect_, it's stroke is renders.
In PP is not.

PS
![strange_border ps](https://user-images.githubusercontent.com/1856145/39363868-7e75dcda-4a34-11e8-8c6c-163673937e1c.png)

PP
![strange_border pp](https://user-images.githubusercontent.com/1856145/39363873-85ccb508-4a34-11e8-82a0-fa5d7b131e20.png)

**Comment by Ser-Gen** [comment]
My issue is about shape options

I've turn off fill and stroke
![image](https://user-images.githubusercontent.com/1856145/39426311-04afda8a-4c88-11e8-9b86-21750e75cbfa.png)

Add effect
![image](https://user-images.githubusercontent.com/1856145/39426323-15695cc0-4c88-11e8-95cc-eacc287a432e.png)

![image](https://user-images.githubusercontent.com/1856145/39426349-28e9c8ca-4c88-11e8-8b8f-0c62053253db.png)

Turn on fill
![image](https://user-images.githubusercontent.com/1856145/39426361-38ca0584-4c88-11e8-86a9-911aae1376c9.png)

Result
![image](https://user-images.githubusercontent.com/1856145/39426388-4158e0a8-4c88-11e8-9e01-3a924d2d16cb.png)

**Comment by photopea** [comment]
Thanks, I understand what you mean. There are still quite a lot of differences in PSD rendering between Photoshop and Photopea. Blending options and blending ranges are also ignored by Photopea. The rendering mechanism is very complex and it is not described anywhere.

**Comment by photopea** [comment]
I give it up. 

Currently, layer styles are generated by pixel transparency. So they look the same on vector shapes, as if you would rasterize them.

In Photoshop, if you have the vector stroke and Satin style, the Satin would not cover the shape stroke, while in Photopea, it covers the whole layer. This mechanism is too complex and I am not confident enough to add it into Photopea.

If you really need to do what you said, set the vector fill to color fill, and decrease the Fill property in Blending Options.
