### ISSUE TITLE
Photopea only saves as 72dpi.  How to keep 300dpi when saving/exporting?

### ISSUE THREAD

**Issue by that-ben** [photopea/photopea#6760]
Your Operating System: macOS 14 (unrelated)
Your Web Browser: Firefox (unrelated)
The problem happens in the Incognito Mode, too: Sure.

**This must be done to see the problem**
1. Go to www.photopea.com
2. Import a 300dpi PSD
3. Look under the menu: Image > Image Size... DPI, it should say 300dpi or whatever.
4. Save or export to PSD or PDF and you will end up with a 72dpi document, unsuitable for printing.

How can I export to 300dpi using Photopea?

**Comment by photopea** [comment]
Step 4: who tells you that your PSD is 72dpi? Is it some program or what it is? Did you ever see a PSD that is not 72dpi during Step 4?

**Comment by that-ben** [comment]
macOS 14.4.1 says it's 300dpi before editing it with Photopea, then it says it's 72dpi after Photopea exported it ... and as a bonus, VistaPrint does not want to process it.  But if I do the same edit tasks that I did in Photopea using Photoshop CS6 and save it, the resulting PDF is seen as 300dpi by macOS and VistaPrint wants to process it.

**Comment by photopea** [comment]
I am confused, are you talking about exporting a PSD or a PDF? They are different formats. Does it really say that a PSD is 72dpi after editing in Photopea?

**Comment by that-ben** [comment]
I tried both today and both yielded the same result.  When you export to PDF in the real Photoshop, you have the option to downsample or to keep the same DPI.  In Photopea, there seemingly is no such option.  It results in 72dpi all the time regardless of what the actual PSD was before exporting.

**Comment by photopea** [comment]
I have fixed the problem with DPI of PSD files from Photopea. MacOS should detect the correct DPI now.

Regarding the PDF, once you have a PDF filehow do you determine the DPI of that PDF file?

**Comment by that-ben** [comment]
I have tested and YES, it now works! PSD -> PSD in Photopea now saves with the correct DPI.  Congratulations on fixing this.  It's a good step forward.

To answer your question:
1) Save the 300dpi PSD to PDF in Photopea.
2) Open the saved PDF in Photopea.  FIRST ISSUE: Photopea now reports it as 144dpi instead of 300dpi, which is already weird.
3) Save to PSD.
4) Open PSD in macOS or any PSD program and you will see that it reports as 72dpi, which is also wrong.

**Comment by photopea** [comment]
PDF files do not have any DPI. So if any program tells you, that a PDF has a specific DPI, it is an error, since PDF files can not have any DPI.

Since every PSD should have a DPI, Photopea loads PDF (and other vector formats) at 144 pixels per inch.

If you see a specific DPI in Photopea, and save it as a PSD, all programs should report the correct DPI of that PSD file made from Photopea (it was fixed, as announced by my previous comment).

**Comment by that-ben** [comment]
Alright, so thanks again for fixing it 👍  You are very talented.  Your work is impressive and very useful to the world.

**Comment by photopea** [comment]
thank you

**Comment by doctormarty** [comment]
This happens with saving .jpgs . I tried to save file a 300 dpi file original as jpeg, in Preview info in Mac shows as 300, after save 100% quality jpeg, file seems downsampled to 72.

I learn about this issue hard way after I sent picture to print service and the resolution seemed off.

**Comment by photopea** [comment]
I just opened a 300 DPI JPG file in Photopea and re-saved it. The result is still 300 DPI (I see it in File properties in Windows 10).

Please, tell me what should I do to see a problem.
