### ISSUE TITLE
Can't Import WEBM File

### ISSUE THREAD

**Issue by ColorDumper** [photopea/photopea#6762]
Your Operating System: Windows 11
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. 'Open From Computer'
3. Select a WEBM file.

It will briefly show the white loading box in the background, and ask how many frames per second I would like it to be. But then it just does nothing. Doesn't open the file, even after waiting for a long time.

**Comment by photopea** [comment]
I just tried to load a WEBM file into Photopea in Brave, and it works fine. Could you share your WEBM file with us?

**Comment by ColorDumper** [comment]
Hi, thanks for the quick response. Here's the WEBM file I'm trying to upload. It's a Twitch alert.

[Resub.webm](https://github.com/photopea/photopea/assets/156731588/2814ae28-36ad-4dd7-b9f1-efc7594f102e)

**Comment by photopea** [comment]
it should be fixed now.

**Comment by ColorDumper** [comment]
Thank you so much!
