### ISSUE TITLE
When performing W quick selection, the Image Analysis message appears and the screen remains motionless.

### ISSUE THREAD

**Issue by alion588** [photopea/photopea#6763]
Your Operating System: windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Load a picture
3. Click Quick Select (W)
4. At this time, the message "Image Analysis" with black text on a white background appeared above the photo, and there was no response, almost a crash.
![veryslower](https://github.com/photopea/photopea/assets/40297748/86a3cb09-92ba-4ff5-9685-f2635410ecd9)

**Comment by photopea** [comment]
When I open a 18 MPx image in Photopea and activate Quick Select, the Image Analysis takes 5 seconds, and then, the message disappears and I can use the tool.

Are you sure the message never disappears? Did you try other images? If it happens just for one image, could you share your image with us?

**Comment by alion588** [comment]
thanks for your reply
I checked the photo and found that its file size is as high as 16.1MB. I can only share it with a link for your reference.

PS. If I open the photo file and the size is about 4~6MB, it is true that the information you mentioned will only appear for a few seconds and then disappear.

[https://drive.google.com/file/d/1oocJd-a4vjHeZDae8f9lF-SDfg_HLBeW/view?usp=sharing](url)

**Comment by alion588** [comment]
> When I open a 18 MPx image in Photopea and activate Quick Select, the Image Analysis takes 5 seconds, and then, the message disappears and I can use the tool.
> 
> Are you sure the message never disappears? Did you try other images? If it happens just for one image, could you share your image with us?

thanks for your reply
I checked the photo and found that its file size is as high as 16.1MB. I can only share it with a link for your reference.

PS. If I open the photo file and the size is about 4~6MB, it is true that the information you mentioned will only appear for a few seconds and then disappear.

[https://drive.google.com/file/d/1oocJd-a4vjHeZDae8f9lF-SDfg_HLBeW/view?usp=sharing](url)

**Comment by alion588** [comment]
The location where I use Photopea is in Taiwan. When I use it, there are downloads, such as fonts or shapes, etc. The download speed is very slow, and it usually takes 1-3 minutes to complete.

However, there is no lag when I view the web page. My network bandwidth is 300M downlink and 30M uplink. What is the situation? Is there any way to improve it?

**Comment by photopea** [comment]
I think your internet provider is slowing down Photopea. If you try a different provider, it will be faster. So you should ask your internet provider about why do they make Photopea so slow.

**Comment by photopea** [comment]
@alion588 could you shar your image again? Your link does not work.

**Comment by photopea** [comment]
I will close it now, because the person did not respond :(
