### ISSUE TITLE
Actions not working

### ISSUE THREAD

**Issue by PigggyWiggy** [photopea/photopea#6764]
Your Operating System: Windows 11
Your Web Browser: Google
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Install my atn file
3. Apply the atn file to a layer in photopea
4. The action won't work

**Comment by photopea** [comment]
Could you show us your ATN file, please?

**Comment by photopea** [comment]
Sorry, I can not download it from your link

**Comment by PigggyWiggy** [comment]
I have updated the link it should work now, sorry.

**Comment by photopea** [comment]
I am trying to use your ATN file on a JPG image in Adobe Photoshop. It keeps saying that a document has unsaved changes. 

Who gave you this ATN file? What did they tell you to do with it? I need a proof, that it is a valid ATN file (that it works in some existing program).

**Comment by photopea** [comment]
I have to close it because of lack of details :(
