### ISSUE TITLE
it won't stop

### ISSUE THREAD

**Issue by jessienorth** [photopea/photopea#6765]
Your Operating System: Lenovo laptop
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes, the images that I've deleted continues to pop up with an asterisk on the project tab. 

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Try this to fix it: https://www.photopea.com/tuts/photopea-opens-up-old-files/
