### ISSUE TITLE
cant write text

### ISSUE THREAD

**Issue by AriRoblox** [photopea/photopea#6767]
i cant write text

**Comment by camoody1** [comment]
Is your hand broken? Do you not have a pen? I don't understand.

**Comment by photopea** [comment]
Did you try it in the Incognito mode?

**Comment by AriRoblox** [comment]
> Bạn đã thử nó ở chế độ Ẩn danh chưa?

yes but it not work

**Comment by photopea** [comment]
Where are you located? Some internet providers in Asia are blocking Photopea.

**Comment by photopea** [comment]
Try a different internet provider.
