### ISSUE TITLE
Alt + Scroll not working for zooming while having input box focused

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#6768]
Your Operating System: Windows 11
Your Web Browser: Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a project
3. Open properties panel, and focus on any input box
4. Hover on canvas, and try using <kbd>Alt + Scroll</kbd> for zooming. It does not work. Instead, <kbd>Ctrl + Scroll</kbd> works
5. Click anywhere to make the focused input box not focused
6. Try step 4 again. <kbd>Alt+Scroll</kbd> works

Is it intended, or bug?

**Comment by photopea** [comment]
I tried to do this in Adobe Photoshop. When you focus at an input box, a mouse wheel does nothing (no matter if you press Alt / Ctrl / etc). Should we make it work the same?

**Comment by photopea** [comment]
ok, it should work now.
