### ISSUE TITLE
´Processing...´ alert remains on screen when using ´Select subject´ function

### ISSUE THREAD

**Issue by lastofthegoatmen** [photopea/photopea#6769]
Your Operating System: ChromeOS
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open image file
3. Go to Select > Subject
4. Program bring up ´Processing...´ notice
5. ´Processing...´ notice remains on screen unless tab is closed or refreshed
6. Subsequent attempts to use ´Select > Subject´ successfully execute, but ´Processing...´ notice remains
![Screenshot 2024-05-20 12 46 27 PM](https://github.com/photopea/photopea/assets/170365399/9331db0d-ee7f-499c-b933-233a5d8052f2)
![Screenshot 2024-05-20 12 38 20 PM](https://github.com/photopea/photopea/assets/170365399/93e80184-3030-4b25-9153-24d4e1b83ef9)

**Comment by photopea** [comment]
No matter what I do, the "Processing" never stays on the screen forever. Did it happen to you more than once? Can you make it happen again?

**Comment by photopea** [comment]
I have to close it because of lack of details.
