### ISSUE TITLE
How to combine shapes?

### ISSUE THREAD

**Issue by Ser-Gen** [photopea/photopea#677]
I want to add one shape to another, but they always separated.

![image](https://user-images.githubusercontent.com/1856145/39364456-b110ae48-4a36-11e8-97a7-6e3e8b5a8b87.png)

**Comment by photopea** [comment]
Hi, you need to switch the mode from Shape to Path, see here: https://www.photopea.com/learn/vg-creating

**Comment by Ser-Gen** [comment]
By default Shape mode is using and this select is active.
Maybe disable it at start?

![image](https://user-images.githubusercontent.com/1856145/39368266-cfa5cba8-4a41-11e8-8aab-f01a7d165291.png)

**Comment by photopea** [comment]
"Unite" is not the shape mode, it is a set operation (Unite, Subtract, intersect ...). I thin Unite is the expected operation.

**Comment by zhar97** [comment]
Isn't there supposed a feature that allow set operation between shapes layers via Edit menu?

**Comment by photopea** [comment]
@zhar97 You can learn how vector graphics work in Photopea here: https://www.photopea.com/learn/vg-structure
