### ISSUE TITLE
Scaling Issue (Free Transform)

### ISSUE THREAD

**Issue by yandelomg** [photopea/photopea#6770]
![image](https://github.com/photopea/photopea/assets/74117156/823800f8-1190-4750-a9c2-3265d98b4032)
                                                        **PHOTOPEA BUG REPORT**

Your Operating System: Windows 11 PC
Your Web Browser: Opera GX
The problem happens in the Incognito Mode, too:  Browser OperaGX - Issue: Free Transform 

**This must be done to see the problem**
1. Go to www.photopea.com
2. Used a template (Social Media Panel)
3. Pasted image from browser with CTRL+ C & CTRL + V
4. Scaling Issue Appears

**Comment by photopea** [comment]
What exactly should I do at Step 2? When I paste an image into another document, everything seems fine. What is a "scaling issue"?

**Comment by yandelomg** [comment]
It seems to be a bug that happens only on my Computer on my laptop the issue doesnt exist but when i use it on my Computer which is a desktop doesn't work. It could be because the Browser doesnt support it but i dont know.

**Comment by yandelomg** [comment]
> What exactly should I do at Step 2? When I paste an image into another document, everything seems fine. What is a "scaling issue"?

Step 2: just create a random project and paste a picture in like from google by copying it it seems to give me the error that i cannot scale it

**Comment by photopea** [comment]
Did you try it in the Incognito mode? You could have browser extensions, which are breaking Photopea.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
