### ISSUE TITLE
Arrows on line shapes don't keep the right size when increasing image size

### ISSUE THREAD

**Issue by robolinc** [photopea/photopea#6771]
Your Operating System: **MacOS**
Your Web Browser: **Chrome**
The problem happens in the Incognito Mode, too: **Yes**

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a line shape with an arrow on it
3. Increase the image size

https://github.com/photopea/photopea/assets/11701920/cd6ae51f-a414-4bf5-ba29-18c6055447c5

**Comment by photopea** [comment]
it should be fixed now. Thaks for reporting!
