### ISSUE TITLE
[Bug] Smart object not respect previous selected interpolation method on update

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#6772]
Your Operating System: Windows 11
Your Web Browser: Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Open this [PSD](https://www.photopea.com/#i8XADodH_)
2. In free transfrom, transform the smart object to 200% with nearest neighbor. It is transformed correctly
3. Double-click the smart object to open it in second tab, and press ctrl + s to update it
4. Go back to the first tab. You can see that smart object is different from what it was in step 2. Now It is not transformed with nearest neighbor selected in step 2

In Photoshop, smart objects always respect the interpolation selected in preferrences. Photopea does not have such a setting, ~~but that's fine. After fixed the bug described in title, we will be able to set differrent interpolation methods for individual smart objects. It is better.~~ See this [post from Adobe community](https://community.adobe.com/t5/photoshop-ecosystem-ideas/p-ability-to-choose-a-smart-object-s-interpolation-method/idi-p/12249327)

I thought wrongly. Fixing this bug will make Photopea work just like Photoshop. Setting interpolation method for individual smart objects is another feature to implement.

**Comment by photopea** [comment]
In the PSD format, smart objects always have a bilinear interpolation.

I made it work like Adobe Photoshop. If you are transforming smart objects / text layers / vector shapes, the interpolation menu is not available at all.

**Comment by photopea** [comment]
So you think that PSD files should look different on each device?

**Comment by photopea** [comment]
But this is how it works in Photoshop. If you set your Photoshop to Nearest Neighbour, and your send your PSD to someone else, and they modify the smart object in Photoshop, it will be rendered with Bilinear, because that is what they have in their settings.

**Comment by photopea** [comment]
I think we should cooperate on this with Adobe, to add an interpolation mode as a parameter of each smart object.

**Comment by photopea** [comment]
I wrote an email to some people at Adobe.
