### ISSUE TITLE
Unexpected Layer Selection

### ISSUE THREAD

**Issue by MonzterDev** [photopea/photopea#6773]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a lay
3. Use the selection tool and select a square
4. Fill in the selected area
5. Deselect it
6. Use the move tool on the previously selected layer

I'm not too sure if this is a bug or working as intended, but the behavior differs from Photoshop. I made a Reddit post on this and others weren't sure if this was a bug or intended. 

**Photopea** behavior
https://preview.redd.it/8g5k4bxyqe0d1.gif?width=1920&format=mp4&s=330fa2d6f4f18a319d0dece12a9c7973a6c5ad09

**Photoshop** behavior
https://www.reddit.com/media?url=https%3A%2F%2Fi.redd.it%2F280r0pcvmg0d1.gif

**Comment by photopea** [comment]
thanks for reporting it, it should be fixed now.
