### ISSUE TITLE
Square curser on all tools changes shape when it's rotated.

### ISSUE THREAD

**Issue by bluep55** [photopea/photopea#6774]
Is this the normal behaviour of the curser when using a square brush in Photopea. When the curser is rotated it becomes an octagon which makes it less precise. In Photoshop the curser remains square when it's rotated. 

https://github.com/photopea/photopea/assets/118609932/f7021046-818a-42e7-8a00-a5857d60a529

**Comment by photopea** [comment]
it should be fixed now.

**Comment by bluep55** [comment]
Brilliant. Thank you 👍
