### ISSUE TITLE
Noto Nastaliq Urdu font is corrupted/showing wrong letters.

### ISSUE THREAD

**Issue by realpervez** [photopea/photopea#6775]
Your Operating System: macOS
Your Web Browser: Arc
The problem happens in the Incognito Mode, too: Probably

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new file
3. Create a text layer 
4. Select Noto Nastaliq Urdu font and write text in Urdu.

The text is showing up as different letters (not corresponding to what I type) and sometimes the letters are incomplete.

I copy the following text: 
زمین والوں پر رحم کرو"
"آسمان والا تم پر رحم کرے گا۔
and paste it in photopea, as well as other sites. But in photopea, it shows differently.

![image](https://github.com/photopea/photopea/assets/135947004/c8e42bfc-6780-443a-bac3-1f7bcb7bc6b4)
Above is a photo of pasting the text in Google Font, text typer.
And below is a photo of pasting the same text in PhotoPea.
![image](https://github.com/photopea/photopea/assets/135947004/4d1047ee-45ed-44ab-ab4b-57892bf34612)

This is not the case with one single letter, but many others too.
I try to upload the font manually but it doesn't get updated, probably because the same font exists in the site already.

**Comment by realpervez** [comment]
Umm, I am really sorry but I don't have photoshop. I use photopea because I don't have photoshop. 

Anyways, the dot should exist in the 'u' shape like character. And in my laptop, there is a different issue, as I attached the images above. I will try to make another screenshot and show the error to you.

**Comment by realpervez** [comment]
> I have created text layers using your font in Photopea and Photoshop, and the only difference is in the dot inside the U letter. Is it the only problem in this case? I.e. does Photoshop render it correctly?
> 
> ![template](https://github.com/photopea/photopea/assets/15955558/7ae2528a-f9b5-4743-8b22-6d9f4a0aea7a)
> 
> 

Sorry brother, I don't own photoshop and that is the reason I use photopea. Thanks to you.

Anyways, that is not the only issue. Although the thing you pointed out is also a problem, but there are several other issues with that font, if I use it on Photopea.

If you notice the arrow on the two photos I attached in my original post, another 'u' shape character (ں) can be seen below which there are two dots (incorrect) in one screenshot and no dots (correct). Although I'm using the same text.

There are issues like this with 'ت' letter with dots missing inside. 

I myself can't find out why this issue persists, and as far as I can remember, this problem happened with another software which I used too. 

But on Google Fonts and other font websites it is fine. So what could be the problem? I hope you find a fix to this.

Thanks for Photopea!

**Comment by realpervez** [comment]
> I have created text layers using your font in Photopea and Photoshop, and the only difference is in the dot inside the U letter. Is it the only problem in this case? I.e. does Photoshop render it correctly?
> 
> ![template](https://github.com/photopea/photopea/assets/15955558/7ae2528a-f9b5-4743-8b22-6d9f4a0aea7a)
> 
> 

Sorry brother, I don't own photoshop and that is the reason I use photopea. Thanks to you.

Anyways, that is not the only issue. Although the thing you pointed out is also a problem, but there are several other issues with that font, if I use it on Photopea.

If you notice the arrow on the two photos I attached in my original post, another 'u' shape character (ں) can be seen below which there are two dots (incorrect) in one screenshot and no dots (correct). Although I'm using the same text.

There are issues like this with 'ت' letter with dots missing inside. 

I myself can't find out why this issue persists, and as far as I can remember, this problem happened with another software which I used too. 

But on Google Fonts and other font websites it is fine. So what could be the problem? I hope you find a fix to this.

Thanks for Photopea!

**Comment by photopea** [comment]
I think these two dots belong to a character on a second line, they are above it.

If you are saying that even Photoshop can not render the text properly, I think I will give it up :(

**Comment by realpervez** [comment]
> I think these two dots belong to a character on a second line, they are above it.
> 
> 
> 
> If you are saying that even Photoshop can not render the text properly, I think I will give it up :(

Wow. I am dumb. Sorry. You are correct.

But about the other issues with the font? What is the case?
Btw, you can close the bug if you feel like it's of no use.

**Comment by realpervez** [comment]
Okay. So with the ت letter, there is another bug where the dots don't appear.

https://github.com/photopea/photopea/assets/135947004/5c543b24-0d93-492d-934d-dc1370bf5415

**Comment by photopea** [comment]
Do you know anyone with Adobe Photoshop? I need a PSD file with a text layer, which was rendered correctly in Photoshop, but it looks wrong when you try to edit it in Photopea.

If you say that Photoshop renders your font incorrectly, too, I think I am not going to fix it, as it is probably the error in the font.

**Comment by realpervez** [comment]
I don't have Photoshop or know anyone, but I've checked with a few other apps, and they display the font correctly. (Davinci Resolve etc.)
Also, if there is an error with the font itself, It won't display correctly on the type testing page on Google Fonts and elsewhere.

**Comment by TheRadicalDreamer** [comment]
![WhatsApp Image 2024-05-27 at 14 28 16](https://github.com/photopea/photopea/assets/11801254/44d202a1-38dc-4303-93f3-041a9035ff40)

**Comment by TheRadicalDreamer** [comment]
This is how it looks when i open the Photopea exported PSD in Photoshop:
![WhatsApp Image 2024-05-27 at 14 31 47](https://github.com/photopea/photopea/assets/11801254/c4053dad-2ab3-46a8-8077-d793ef66b445)

**Comment by photopea** [comment]
@realpervez does your text look correct in Adobe Photoshop, as provided by @TheRadicalDreamer ?

**Comment by photopea** [comment]
@realpervez I have found a bug in Photopea and I have fixed it. Please, let me know if it works correctly now.

**Comment by TheRadicalDreamer** [comment]
Sorry to meddle, but yes, it did apparently solve it 
![image](https://github.com/photopea/photopea/assets/11801254/242e30a1-a9ba-49d1-9154-94389b8163ee)

**Comment by realpervez** [comment]
![image](https://github.com/photopea/photopea/assets/135947004/0fe270a8-f2b3-4339-8791-04942da40db9)
Looks like it's fixed :D
Glad.
