### ISSUE TITLE
Cannot use DELETE Key

### ISSUE THREAD

**Issue by githubUser01946** [photopea/photopea#6776]
Your Operating System: Windows 10
Your Web Browser: Edge & Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open an image
3. Select an area with magic wand
4. Press Delete key

As above, I am pressing the delete key and nothing happens. I am having to either ctrl+x or Edit > Clear.

**Comment by photopea** [comment]
I can not reproduce it :( Maybe there is something special about your image? Could you share your image with us?

**Comment by photopea** [comment]
I have to close it, because the person did not respond.

**Comment by kabantejay** [comment]
same too, delete not working often! its just stops somehow sometime and that's all... Edit > Clear not working too

**Comment by photopea** [comment]
Please, tell me what should I do to see this problem.
