### ISSUE TITLE
The loading popup keeps showing up.

### ISSUE THREAD

**Issue by llaa33219** [photopea/photopea#6777]
![스크린샷 2024-05-23 002406](https://github.com/photopea/photopea/assets/147328072/89bf92e1-fabe-4067-876a-d53465173231)

The loading pop-up continues to appear after logging in. It will not be displayed unless you log in. (It remains the same even after a lot of time.)

로그인을 한 후로부터 계속 로딩 팝업이 표시됩니다. 로그인을 하지 않으면 표시되지않습니다.(많은 시간이 지나도 똑같습니다.)

**Comment by photopea** [comment]
Try this:
- press Window - Plugins, "Installed" on the left, and remove installed items
- press Edit - Local storage, and delete items in there.

Let me know if it helped!
