### ISSUE TITLE
PNG Image not open

### ISSUE THREAD

**Issue by Nice-L** [photopea/photopea#6778]
Your Operating System: Windows 10 Pro x64 22H2
Your Web Browser: Chrome 125.0.6422.60 
The problem happens in the Incognito Mode, too: YES

**This must be done to see the problem**
1. Go to www.photopea.com
2. File
3. Open
4. Double tap on png image
5. nothing. File must be opened.

**Comment by photopea** [comment]
I tried it, but it works fine for me. Could you share your PNG image with us? Did you try to open JPG or other formats?

**Comment by Nice-L** [comment]
> I tried it, but it works fine for me. Could you share your PNG image with us? Did you try to open JPG or other formats?

I opened your site as a frame through another one (https://online-fotoshop.ru/). This turned out to be exactly the case. I apologize. Thank you for quick answer.

**Comment by photopea** [comment]
That is not our website :(
