### ISSUE TITLE
Right shift key not work

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#6780]
Your Operating System: Windows
Your Web Browser: Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new project
3. Try using <kbd>Shift + U</kbd> to switching between shape tools. 

Right shift is also not working for adding selection, toggling free/fixed aspect in transforming, etc.

**Comment by photopea** [comment]
I just tried it in Edge on Windows, and the right shift works exactly the same as the left shift :(

**Comment by photopea** [comment]
Ok, I will close it now.
