### ISSUE TITLE
[Feature Request] Live preview for selection modification

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#6781]
When modifying selection, we can't be sure if we'll get what we want before we click OK. It always takes a few tries. I wonder if it's possible to implement a live preview?
![image](https://github.com/photopea/photopea/assets/79258245/e254b421-adfc-4121-afdc-26bfba6eb581)
The live preview for selection while dragging horizontally with magic wand helps a lot. It would be nice to have it for selection modification.

**Comment by xan2622** [comment]
I second this suggestion. Having a _Live Preview_ checkbox would be very convenient. 
![mockup](https://github.com/photopea/photopea/assets/1732773/9283d0cb-f310-4637-af6e-813770f06591)

**Comment by photopea** [comment]
I have implemented it. There is no checkbox, it is always "live".
