### ISSUE TITLE
Photopea wont load on any device/browser/network/ip

### ISSUE THREAD

**Issue by aosumi-rena** [photopea/photopea#6782]
Photopea wont load on any device/browser/network/ip

Your Operating System: Windows 10 Pro 22H2 x64
Your Web Browser: Chrome V 125.0.6422.77
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. It will only load favicon, with blank screen, which loads forever (doesnt show up page take too long to respond or similar stuff)
The issues consists even when I switch to other devices with the following systems: Windows 11, Android 9, Android 11, Android 14, and the following browsers: firefox, yandex, ms edge, and the issues continues when I switch to other networks like hotspot or using proxy or vpn methods to change ip address.

**Comment by Endercat-sia** [comment]
To add on, when it is loading, the whole dev panel (of browser / F12 / Ctrl+Shift+i) element page is empty, and the issues persists even after I clear application storage (dev panel-->application-->storage)

**Comment by photopea** [comment]
Are you located in Asia? Philippines / Vietnam / Thailand? Some asian internet providers are blocking Photopea. Who is your internet provider? See https://www.reddit.com/r/photopea/comments/1cxvhm1/a_modifiable_list_of_asian_isps_that_dont_work/

**Comment by OgxyHeim** [comment]
Am thailand last month am use photopea is no problem. and now when i use photopea is blank am try waiting for 5min and is working but when am try to type something and is loads forever and doesnt show up page take too long to respond or similar stuff [how can i fix that problem plz help me i need to use photopea i love you photopea dont let me go]
@photopea

**Comment by zypA13510** [comment]
Not sure if related. Our traffic is routed through Cloudflare, photopea is working but extremely slow. Loading a font of 16MB takes several minutes.

![image](https://github.com/photopea/photopea/assets/8077540/715270a3-75b1-48ee-ab1e-5f8419835172)

![image](https://github.com/photopea/photopea/assets/8077540/b1e157aa-69ea-4f7d-8040-9c9f0d3a3ecd)

**Comment by zypA13510** [comment]
@photopea In plain terms, you can take that as our ISP is Cloudflare / our internet traffic exits from Cloudflare, as you can see in the speed test image.

**Comment by photopea** [comment]
We have started to use a CDN. Does it work better now?

**Comment by photopea** [comment]
It should load faster now.
