### ISSUE TITLE
HTTP error: 401 : User's secret was already generated.

### ISSUE THREAD

**Issue by Loyalnaorem** [photopea/photopea#6783]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Hi, could you tell me your email address inside Photopea? Press "Account" at the top to see it.

**Comment by Loyalnaorem** [comment]
> Hi, could you tell me your email address inside Photopea? Press "Account" at the top to see it.

naoremloya@gmail.com

**Comment by photopea** [comment]
it should be fixed now. Just close and reopen Photopea.
