### ISSUE TITLE
photopea isn't displaying nearest neighbor when resizing an image

### ISSUE THREAD

**Issue by MrPickle3009** [photopea/photopea#6784]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. make a pretty high resolution project
3. open and place a pixelart or whatever that shouldn't be pixelised when you upscale it
4. when using the move tool enable "transformation controls"
5. try to upscale the image you opened and placed with the move tool and it'll automatically be bilinear and the options to change that are removed

**Comment by photopea** [comment]
We have disabled this option for vector shapes, text layers and smart objects, to be consistent with the PSD format.

**Comment by photopea** [comment]
I have added the option into Edit - Preferences, where you can set the interpolation method for Smart Objects.
