### ISSUE TITLE
Suggestion for making money from people that use ad blockers.

### ISSUE THREAD

**Issue by austinhomolka** [photopea/photopea#6785]
I use an ad blocker extension. I was recently on this website: https://www.freeconvert.com/mp4-to-mp3 -- and it had a great flow that made me disable my ad blocker on the site.. I wanted to pass this along incase it's helpful for getting more revenue for photopea for those who continue to use ad blockers. Thanks!

**Comment by photopea** [comment]
How exactly can I help you? Or what are you suggesting us to do?
