### ISSUE TITLE
[Feature Request] Right-click and drag to pan

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#6786]
This feature in Figma make it no longer necessary to press spacebar frequently. Could it be implemented in Photopea?
![屏幕截图 2024-05-25 103215](https://github.com/photopea/photopea/assets/79258245/ee4e297c-d8b4-472b-a08c-85c72a3440ef)

**Comment by photopea** [comment]
right-clicking the canvas (for a context menu) is a very useful feature in Photopea.

You are the only one asking for it. I am afraid there would be thousands of people who enable it unintentionally, and it would ruin their experience with Photopea.
