### ISSUE TITLE
Can't select the nearest neighbour option anymore

### ISSUE THREAD

**Issue by SkellyUT** [photopea/photopea#6787]
Your Operating System: Windows 11
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Yes

It doesn't showup the bilinear, nearest neighbour and bicubic shaper option when I want to resize an image (by dragging the image) anymore.
Until few days ago the option was still available.

**Comment by photopea** [comment]
You are probably transforming a text layer or a smart object. The Nearest Neighbour should not be available for these cases.

**Comment by SkellyUT** [comment]
I checked and nearest neighbour appears (after I rasterize an image) but it disappears when I try to resize the image. It didn't happen few days ago.

Also when I add an image -> rasterize -> select nearest neighbour -> increase size of the image, the quality of the image is chopped down a bit and basically I have to delete the image and add it again and only then I can resize the image without quality loss bc nearest neightbour option is saved.

It's not a big deal but it's an unecessary step that can be annoying from time to time.

**Comment by photopea** [comment]
This is how it works in Adobe Photoshop and I would like to keep ti the same to be compatible with the PSD format.
