### ISSUE TITLE
Incrementing/decrementing numeric values by pressing (Shift+)Up/Down

### ISSUE THREAD

**Issue by biziclop** [photopea/photopea#679]
In Photoshop and in many other programs too, if you are in a number field, you can press Up or Down key to increment or decrement the current value by 1 (or whatever the default step value is, for example at Gaussian Blur it's 0.1). If you press Shift too, you can change the value by 10* the step value. I don't know how many people use it, but I couldn't live without it.

It could be even better than Photoshop if the step value would depend on the current value, like:
`cur.val: 0…10` -> `step value: 0.1`
`cur.val: 10…100` -> `step value: 1`
`cur.val: 100…1000` -> `step value: 10`
or something similar.

It's also possible that the mouse scroll wheel also can be used to change the value, but I don't use this feature. :-)

**Comment by photopea** [comment]
What a great idea! It was implemented (both for keyboard arrows and for the mouse wheel). Thanks!

**Comment by biziclop** [comment]
It works great! You are fast! :)
