### ISSUE TITLE
Hi, I have translated all English in the "Filter Gallery" into Simplified Chinese.

### ISSUE THREAD

**Issue by yswang0927** [photopea/photopea#6791]
Hi, I have translated all English in the "Filter Gallery" into Simplified Chinese.
These translations(zh-CN) are from Adobe Photoshop, so they are 100% correct.
```
Stroke Pressure 描边压力
Paper Brightness 纸张亮度

Number of Levels 色阶
Edge Simplicity 边缘简化度
Edge Fidelity 边缘逼真度

Brush Size 画笔大小
Brush Detail 画笔细节

Grain 颗粒
Highlight Area 高光区域
Intensity 强度

Glow Size 发光大小
Glow Brightness 发光亮度

Sharpness 锐化程度

Brush Type 画笔类型
	Simple 简单
	Light Rough 未处理光照
	Dark Rough 未处理深色
	Wide Sharp 宽锐化
	Wide Blurry 宽模糊
	Sparkle 火花

Stroke Size 描边大小
Stroke Detail 描边细节
Softness 软化度

Detail 细节

Edge Thickness 边缘厚度
Edge Intensity 边缘强度
Posterization 海报化

Stroke Length 描边长度

	Blocks 块状
	Canvas 画布
	Frosted 磨砂
	Tiny Lens 小镜头
	Bricks 砖块
	Burlap 粗麻布
	Sandstone 砂岩

Relief 凸现
Light 光照
	Bottom 下
	Bottom Left 左下
	Left 左
	Top Left 左上
	Top 上
	Top Right 右上
	Right 右
	Bottom Right 右下

Definition 清晰度
Texture Coverage 纹理覆盖
Shadow Intensity 阴影强度

Edge Width	边缘宽度
Edge Brightness	边缘亮度

Direction Balance 方向平衡

Balance 平衡
Black Intensity 黑色强度
White Intensity 白色强度
Dark Intensity 深色强度
Light Intensity 光照强度

Spray Radius 喷色半径
Stroke Width 描边宽度

Graininess 粒度
Glow Amount 发光量
Clear Amount 清除数量

Distortion 扭曲度

Ripple Size 波纹大小
Ripple Magnitude 波纹幅度

Charcoal Area 炭笔区
Chalk Area 粉笔区

Thickness 粗细
Light/Dark Balance 明/暗平衡

Foreground Level 前景色阶
Background Level 背景色阶

	Right Diagonal 右对角线
	Horizontal 水平
	Left Diagonal 左对角线
	Vertical 垂直

Image Balance 图像平衡
Darkness 暗度

Fiber Length 纤维长度
Crack Spacing 裂缝间距
Crack Depth 裂缝深度
Crack Brightness 裂缝亮度
Tile Size 拼贴大小
Grout Width 缝隙宽度
Lighten Grout 加亮缝隙
Square Size 方形大小

Grain Type 颗粒类型
	Regular 常规
	Soft 柔和
	Sprinkles 喷洒
	Clumped 结块
	Contrasty 强反差
	Enlarged 扩大
	Stippled 点刻
	Horizontal 水平
	Vertical 垂直
	Speckle 斑点
```

**Comment by photopea** [comment]
Hey, thanks a lot! Did you also translate it into www.photopea.com/translate? If not, could you do it?

**Comment by yswang0927** [comment]
> Hey, thanks a lot! Did you also translate it into [www.photopea.com/translate](http://www.photopea.com/translate)? If not, could you do it?

Hey, I visited [http://www.photopea.com/translate](http://www.photopea.com/translate), but found that the translation progress of Simplified Chinese was 100%, and no untranslated content related to "Filter Gallery" was found. 

Can you add these new translation items? I'd be happy to translate them above.

**Comment by yswang0927** [comment]
![223333](https://github.com/photopea/photopea/assets/1838103/5771d6da-0e83-4e92-b448-da899e9018a7)
![55556666](https://github.com/photopea/photopea/assets/1838103/fa7b5b60-58f8-4760-a0c2-afb933212b06)

Hey, I visited http://www.photopea.com/translate, and found that the translation progress of Simplified Chinese was 100%, but in fact, **there are still many untranslated items in the "Filter Gallery"**.

I also found that the main menu and some menu function configuration items are also untranslated.

If you add these new translation items,  I'd be happy to translate them above.

**Comment by photopea** [comment]
I have made all Filter Gallery phrases translatable at www.photopea.com/translate

**Comment by photopea** [comment]
Let me know if you can translate it there, and I will update it in Photopea.com

**Comment by yswang0927** [comment]
> Let me know if you can translate it there, and I will update it in Photopea.com

I saw it. I will translate them in the next few days.

**Comment by yswang0927** [comment]
> I have made all Filter Gallery phrases translatable at [www.photopea.com/translate](http://www.photopea.com/translate)

I will translate them today.

**Comment by yswang0927** [comment]
> Let me know if you can translate it there, and I will update it in Photopea.com

Hey, I have translated them all.

**Comment by yswang0927** [comment]
@photopea 

I have translated both Simplified Chinese(zh-CN) and Traditional Chinese(zh-CHT), and fixed the incorrect translations of "Spin Blur", "Path Blur", "Tilt-Shift", "Iris Blur", "Field Blur" and "Filter Gallery".

PS:  All translations from "Adobe Photoshop 2023 24.0.0"，so they are 100% correct.

**Comment by photopea** [comment]
That is amazing, I can see your translations! I have put them all to www.photopea.com . Thank you very much! :)

![image (9)](https://github.com/photopea/photopea/assets/15955558/cd69b87e-0c56-42f8-8b22-017d4071910f)

**Comment by yswang0927** [comment]
@photopea  

There are still some untranslated items in the main menu, e.g. "File -> Export Color Lookup...", "Select -> Remove Bg|Subject|Grow|Similar", "Filter -> Fourier(+subMenu)", ".....".

If you add these untranslated items,  I will translate them again.

**Comment by photopea** [comment]
I am not sure whether these features will stay in Photopea forever, or they would be removed or replaced at some point.
