### ISSUE TITLE
Please add this font to Photopea's font list

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#6792]
[HarmonyOS Sans](https://developer.huawei.com/consumer/en/doc/design-guides-V1/font-0000001157868583-V1), the default font used by Huawei, the brand with the largest share of the Chinese mobile phone market. And it's royalty-free.

It would be very nice to be able to use them directly in Photopea without downloading them to different devices.

![image](https://github.com/photopea/photopea/assets/79258245/176bd457-57ab-4fb4-8446-46b932c60da5)
![image](https://github.com/photopea/photopea/assets/79258245/27472a80-34c9-44a8-be12-0a369e6bbac5)

**Comment by photopea** [comment]
Is it avaliable at Google Fonts, Font Squirrel, or any other place for royalty-free fonts?

**Comment by TheRadicalDreamer** [comment]
I don't know if you are looking for this, but let me try:
https://developer.huawei.com/consumer/en/doc/design-guides-V1/font-0000001157868583-V1
https://font.download/font/harmonyos-sans#google_vignette
https://www.cufonfonts.com/font/harmonyos-sans#google_vignette

**Comment by photopea** [comment]
Could you ask Google Fonts or FontSquirrel to add this font to their databases? Otherwise, I am not sure if it is free to use for commercial purposes.

**Comment by TheRadicalDreamer** [comment]
It seems so. Because the same company said it in its blog:
https://consumer.huawei.com/za/community/details/Huawei-HarmonyOS-Sans-font-is-available-for-free-commercial-use/topicId_145064/
![image](https://github.com/photopea/photopea/assets/11801254/9560fd90-a1ea-4dcc-9753-665610b9edf3)

**Comment by TheRadicalDreamer** [comment]
As you can read in the article 2, number 3:
>  This limitation does not apply to any work created by using HarmonyOS Sans Fonts. You can freely distribute or sell your work, such as materials, logos, application software etc. created by using HarmonyOS Sans Fonts.

The only limitation, like any other author's right is that you cannot resell the font as stand-alone:
> Neither HarmonyOS Sans Fonts nor any of their individual components may be redistributed or sold in a stand-alone base.

So i see that it has free commercial use. Also, the blog of the company says so:
![image](https://github.com/photopea/photopea/assets/11801254/eaf4c485-3ce1-4fe7-96ea-2eda0c8f1be4)
