### ISSUE TITLE
Ads make website unusable

### ISSUE THREAD

**Issue by MoriMoriMorii** [photopea/photopea#6793]
Your Operating System: Windows 10
Your Web Browser: Opera GX
I'm having issues with lag due to video ads, I see that this problem is not new (as I saw in issue #6121, to which no help was given)
I have an intel i5 processor as well as no extensions and have whitelisted the site on all of Opera's built in safety tools (Which is really risky considering how dangerous ads can be if they are scams or phishing ads), and the lag is to a point I am barely able to use the basic brush tool..

**Comment by photopea** [comment]
Each ad should have the "X" at the top right corner. Click it and then, click "Stop seeing this ad". The ad should never be displayed again.
