### ISSUE TITLE
every time I export a file canvas says its corrupted

### ISSUE THREAD

**Issue by mediarm** [photopea/photopea#6794]
Your Operating System: macOS
Your Web Browser:safari
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ... import a png file
3. ....add a png ( background type)
4. ....take the background file and clip mask it
5. ... export it as a png or svg
6. ... go to canva export the file the you just created in canva and get a message from canva saying the file was corrupted

**Comment by photopea** [comment]
I am confused about "go to canva export the file the you just created" - what does it mean? What should I export from canva?

**Comment by mediarm** [comment]
Sorry import the file into Canva ( the one that you exported from photopea) I tried importing into Canva today again and still doesn’t work …
________________________________

**Comment by photopea** [comment]
So are you importing a PNG or an SVG into Canva? Canva must be able to open a PNG from Photopea. Are you sure it can not?

**Comment by mediarm** [comment]
I imported PNG and it told me the file was corrupted I tried every day since I’ve sent you this issue and it’s still not working
________________________________

**Comment by mediarm** [comment]
________________________________

**Comment by photopea** [comment]
I just tried to insert a PNG file from Photopea to Canva and it works fine. Could you send me a PNG file, which you got out of Photopea, so that I can import it into Canva myself? Send it to support@photopea.com

Please, do not send emails to random github addresses. Open www.github.com and reply there.

**Comment by photopea** [comment]
I have to close it becaue of lack of details :(

**Comment by mediarm** [comment]
I disnt understand your last message , could you please elaborat more? and the email is sent

**Comment by mediarm** [comment]
![2](https://github.com/photopea/photopea/assets/170899947/93d94353-01b0-4689-82be-d13f6b5971ba)

**Comment by mediarm** [comment]
sorry missed the part to send the file to the email , I'll send the email with this email address : riyya487@hotmail.com

**Comment by photopea** [comment]
I can load your file into Canva.

I need to see a file created by Photopea, which you can not load into Canva. Or are you claiming something else?

![image](https://github.com/photopea/photopea/assets/15955558/9f44d85a-78ae-43b5-984f-608853bf611a)
