### ISSUE TITLE
photopea loads all my previous work but never delete's them after

### ISSUE THREAD

**Issue by minisnow10** [photopea/photopea#6795]
Your Operating System: chromebook
Your Web Browser: chromeOS
The problem happens in the Incognito Mode, too: no

**This must be done to see the problem**
1. Go to www.photopea.com
2. wait a couple seconds.
3. all my previous work loads in.

**Comment by photopea** [comment]
Try this: https://www.photopea.com/tuts/photopea-opens-up-old-files/

**Comment by photopea** [comment]
I am pretty sure that you can fix it now, so I will close it.
