### ISSUE TITLE
[Bug] Interpolation menu disappeared on editing in canvas

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#6798]
Your Operating System: Windows
Your Web Browser: Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new project
3. Unlock Bakcground layer
4. Enter Free Transform
5. Do any of following:
    - Click anchor point setting at the left of option bar
    - Press arrow key to move layer
    - Drag control points in canvas

The interpolation menu would disappear at the step 5. Changing values only in option bar would not make it disappear.

**Comment by photopea** [comment]
Wow, thanks a lot! I think many others tried to report it, but I thought they are transforming smart objects. Aou are the only one who provided the steps to reproduce it.
