### ISSUE TITLE
Photopea showing blank white screen when opened

### ISSUE THREAD

**Issue by rydebrb** [photopea/photopea#6799]
Your Operating System: iOS
Your Web Browser: ChromeOS
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com

Running from iPhone XR, deleted chrome, tried safari, incognito, cleared site data

**Comment by photopea** [comment]
In what country are you located? Can you open www.seznam.cz ?

**Comment by rydebrb** [comment]
i’m in the usa, the website works

**Comment by photopea** [comment]
so you can not open www.photopea.com on an iPhone? Did you try to open it on any other device?

**Comment by rydebrb** [comment]
it works on all other devices but my most accessible one for the projects i’m working with would be through my phone

**Comment by photopea** [comment]
I have heard of some Apple devices showing Photopea as a white page. It was due to some certificates. Could you update your iOS?

**Comment by scates98** [comment]
Having this same issue. Photopea opens with a blank white page. Tried opening from my Dell Latitude 7420 laptop running Windows 10 (Version 22H2 OS Build 19045.4412) using Google Chrome (Version 122.0.6261.129), Mozilla Firefox (Version 126.0.1), and Microsoft Edge (Version 125.0.2535.67). None of the three browsers will open Photopea and just display the blank white screen, even after reboot and also trying in Incognito/Private browsing mode. 

Interestingly enough. I tried on another laptop (MSI) also running Windows 10, and it would open in Google Chrome, but NOT in Mozilla Firefox (same versions). 

Note: Website does work on my Apple iPhone 15-Pro using Safari and Firefox apps. 
Location: Alberta, Canada

**Comment by photopea** [comment]
@scates98 Do you have access to the whole internet? Is there any firewall that is blocking you from accessing some websites?

**Comment by scates98** [comment]
No problem accessing any other sites on the internet. There is a firewall, but that doesn't explain why I can access Photopea using one web browser (Chrome) and not another (Firefox) on the same (MSI) laptop.

**Comment by exie-czex** [comment]
same problem here, but I discovered that company i work for is blocking sources from https://vecpea.com/...

**Comment by photopea** [comment]
https://vecpea.com is our CDN, which we started to use recently. Why is your company blocking it? Photopea can not work without a proper access to the internet :(

**Comment by scates98** [comment]
Didn't look at console then, but did just now. You are correct, I cannot open anything at: https://vecpea.com 
![image](https://github.com/photopea/photopea/assets/49077836/595bde99-0dad-4519-8cf7-cf0e6a26ac8f)
Though I can resolve and ping the URL:
![image](https://github.com/photopea/photopea/assets/49077836/298a4130-2d13-4d73-b801-c7906af8243b)

I doubt my company is blocking it, but I will see if an exception can be added to the firewall to open things up. This site may be being blocked by a dynamic firewall auto-update.

**Comment by photopea** [comment]
so who is blocking www.vecpea.com for you then?

**Comment by scates98** [comment]
It would be the firewall for sure, but not a manual rule being put in by the company. Maybe included in an auto-update rules list or something like that. I'll check things out and get back to you.
