### ISSUE TITLE
Problem saving as .psd, saved to Imgur, where did it go?

### ISSUE THREAD

**Issue by LaserKate** [photopea/photopea#68]
HI,
I was having trouble saving to a .psd file, so I chose the Imgur option. Where does it save exactly? It just saved it saved but didn't provide a link or open a new window?
cheers,

**Comment by photopea** [comment]
Hi,

when you save to Imgur, it saves only the PNG image (without layers etc.).  Your image should appear in the new window. Maybe your browser is blocking new windows somehow?

What exactly happened, when you pressed Save as PSD? Do you see any errors in web console? (right click - Inspect - Console).

**Comment by LaserKate** [comment]
Hi,
Thanks for the quick response! Nothing happened when I clicked Save as PSD. No text box came up and no file was created. No errors came up in the console. It was like the button was inactive. I tried to re-create what I was doing before that happened, but could not. 
Yes, the browser was probably blocking pop-ups. Does the image get uploaded to Imgur for public use? I was editing my resume, which has my phone, email and home address, so I would really prefer it to not be out there. Any way to find it and remove from Igmur?
cheers,

**Comment by photopea** [comment]
All the images at Imgur are public. Each of them gets the special URL and it is impossible to find some image for people who don't have that URL.  And when your image is not visited by masses, I think Imgur will delete it eventually.

What browser do you use? Does it pass the Photopea test? https://www.photopea.com/willitwork/

**Comment by LaserKate** [comment]
Hi,
I see. Ok, hopefully it will be deleted soon.
I am using Chrome. Only two objects required for future didn't pass the Photopea test. All current requirements passed.

**Comment by photopea** [comment]
So now it is saved without any problems? Did you edit text layers, before it was impossible to save as PSD?

**Comment by LaserKate** [comment]
Yes, once I sent back to the last version that saved correctly, and re-did what did not save, the file saved correctly. 
Yes, I think it had something to do with maybe the text layers, so object layer. I saw that some other people were having the same issue. I tried to re-create the problem but could not.

**Comment by photopea** [comment]
These are the worst bugs, when it sometimes work, but sometimes does not.

Can you describe, more or less, what you did with the text layer? Did you create the new one, or just edited the existing one? Did you change fonts?

**Comment by LaserKate** [comment]
I don't think creating new layers (either completely new or copying), or editing caused the problem. It might have been the font change though. In the the file that wouldn't save, I accidentally changed the font. In the file that did save, the font was never changed. I noticed that the font I was using was not in the font list, so maybe something with importing a non-default font and then reverting that change caused the problem.

**Comment by photopea** [comment]
Can you share your PSD file with me, so I can play with it for a while, to find a bug? I promise I will not share it with anyone. If yes, can you send it to support@photopea.com , please?

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by mbougarne** [comment]
So the image directly send to IMGUR!!! Without any confirmation from the user - POPUP CONFIRMATION MESSAGE -?! What if someone click on it without meaning that? By that you making something very private public to anyone?

THIS IS VERY A ... I DON'T KNOW WHAT TO SAY.

**Comment by mbougarne** [comment]
EVEN SO, at least ask for confirmation, who know! Maybe someone works with naked photos. 

Thank You!
