### ISSUE TITLE
[bug] After applying a filter, layer is shown distorted

### ISSUE THREAD

**Issue by biziclop** [photopea/photopea#680]
1. open https://www.photopea.com
2. choose pea.psd demo
3. choose layer `top bar`
4. apply some filter, like Gaussian Blur, Color Halftone
5. the layer's height appears to be reduced to its third or such

Some filters are ok, some are not.

Environment: Mac Mini late 2012 with Intel HD Graphics 4000, macOS 10.11, both in Firefox and Safari.

**Comment by photopea** [comment]
It was fixed. Thank you!
