### ISSUE TITLE
free Transform series failure ALT+CTRL+T

### ISSUE THREAD

**Issue by Teatway** [photopea/photopea#6800]
free Transform series failure
ALT+CTRL+T
Unlawful free change, impossible large or small

**Comment by photopea** [comment]
What should I do to see the problem? It seems to work fine for me.

**Comment by JustAnAccount5** [comment]
same thing happening to me

**Comment by photopea** [comment]
Does it happen in the Incognito mode, too? It is possible that some of your browser extensions are breaking Photopea.

Also, what web browser do you use?

**Comment by JustAnAccount5** [comment]
> Does it happen in the Incognito mode, too? It is possible that some of your browser extensions are breaking Photopea.
> 
> Also, what web browser do you use?

Chrome
Works on incognito
there are 4 extensions enabled, Ublock Origin, Tampermonkey (No scripts enabled), McAfee WebAdvisor and malwarebytes browser guard

**Comment by photopea** [comment]
I think you should report it to the creators of malwarebytes , ask them to fix it.
