### ISSUE TITLE
Colour Picker not working

### ISSUE THREAD

**Issue by 07bowerhar** [photopea/photopea#6802]
Your Operating System: Windows 11 Pro
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. .... Create a layered item (ie a shape with a stroke or a coloured shape)
3. .... Add layer style, colour overlay (normal blend)
4. .... Select the colour picker. Attempt to select either background or foreground colour as the colour for the colour picker. It doesn't work. When you click 'ok', the base colour remains the same it doesn't select the new colour. It is therefore impossible to add new colours to items and it's a nightmare.

**Comment by photopea** [comment]
I have fixed it.

Basically, when a color picker window is opened, and you click somewhere to open a new color picker (e.g. in a toolbar), the new color is copied, but the color picker is still applied to the "original target".
