### ISSUE TITLE
Feature Request: Copy entire Canvas to Clipboard

### ISSUE THREAD

**Issue by keaidemao** [photopea/photopea#6803]
Often, I only need to quickly tweak an image to use for other purposes. In photopea I can simply paste an image from the clipboard but after editing I have to export/download it to use it for other purposes. It would be great if there was a simple shortcut to just copy the entire visible canvas to the clipboard. An example use case would be I copy a picture from the Internet, paste it in Photopea, quickly add curves, text maybe blur a face and then can simply copy it to the clipboard again and paste it into other software.

**Comment by MichalSZZ** [comment]
CTRL+A (select all visible layers)
CTRL+Shift+C (copyright merged)

Or you can create a new layer from a visible: CTRL+Shift+Alt+E and then use  Ctrl+C

**Comment by photopea** [comment]
Use "Select All" and "Copy Merged", as mentioned above :)
