### ISSUE TITLE
Photopea Image Analysis Glitch Issue *please help ASAP, i have a project due tomorrow*

### ISSUE THREAD

**Issue by Skelch78** [photopea/photopea#6804]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....Add an image into the website
3. ....Click on quick selection tool on the image
4. ....An image analysis box with white background and black text will appear saying "image analysis" and won't go away, causing me to when i open tabs in photopea, i cant close out of them and makes me stuck on that screen
![Screenshot 2024-05-28 172304](https://github.com/photopea/photopea/assets/171092024/37632e57-420d-40e1-90d7-2afdf0741e75)
![Screenshot 2024-05-28 172259](https://github.com/photopea/photopea/assets/171092024/a9667ea3-3ac1-4f56-b68a-846eee9c8d45)

**Comment by photopea** [comment]
I think it happens only for some images. Please, share your image with us! Put it into a ZIP and attach it to your comment.

**Comment by Skelch78** [comment]
![Snapchat-692392178](https://github.com/photopea/photopea/assets/171092024/fe852c29-cf2c-4fbe-b353-af3e24398970)
i have to make a magazine of my friend

**Comment by Skelch78** [comment]
[Snapchat-692392178.zip](https://github.com/photopea/photopea/files/15476800/Snapchat-692392178.zip)

**Comment by Skelch78** [comment]
please help, i need to do this by tomorrow morning, i need to quick select and wtv so i can put my friends face on the body of a celebrity for a magazine project.. and im still trying to figure out how to do that, but when i looked it up and tried what it said, it didnt let me. but i cant reload the page because then i will lose everything i have currently been working on and its due tomorrow so i really really dont want that to happen

**Comment by photopea** [comment]
You can save your work to your computer as a PSD file and close Photopea, and re-open it next time.

**Comment by photopea** [comment]
I opened your file in www.Photopea.com and selected the Quick Selection tool. The "Image Analysis" disappeared after a second, and I could use the tool. Did you send me the correct JPG file? Did you try to restart Photopea?

![image (11)](https://github.com/photopea/photopea/assets/15955558/11bbd69c-c5f6-40b7-a74a-f9e51aad1a88)

**Comment by Skelch78** [comment]
i tried it and it still happens, i think its because of all of the other images and stuff i added onto the same page.. what can i do??

**Comment by photopea** [comment]
Did you try to restart Photopea? Close it and open it again?

**Comment by photopea** [comment]
I have to close it now, because the person did not reply.
