### ISSUE TITLE
False Ad Blocker Message

### ISSUE THREAD

**Issue by jayjea213** [photopea/photopea#6805]
Your Operating System: macOS High Sierra v10.13.6
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: No
![Screen Shot 2024-05-28 at 6 12 10 PM](https://github.com/photopea/photopea/assets/171097875/d3e0c7da-b7db-4607-a4af-5fe01417d759)
![Screen Shot 2024-05-28 at 6 12 26 PM](https://github.com/photopea/photopea/assets/171097875/82efeebd-a7ad-46ed-9b37-bb58fd18a638)

**Comment by photopea** [comment]
My only explanation is that your Awesome Screen Recorder is blocking our ads. Did you try to disable it?

Why did you give it permissions to see and change the information in Photopea?

**Comment by tinchomaldo** [comment]
Hi guys :) Same here. I have AdBlock (https://chrome.google.com/webstore/detail/gighmmpiobklfepjocnamgkkbiglidom) but it's disabled for Photopea, the message shows anyway everytime I use the site, even when the ads are being displayed

**Comment by camoody1** [comment]
@tinchomaldo But which ads are you seeing? When the "real" ads are blocked, the application shows game ads for apps created by the developer. Those game ads don't make the dev any money. The real ads that make money are for external goods and services.

**Comment by photopea** [comment]
This ad blocker lies to you, it blocks ads even when it says it is not. The only solution is to disable it. See our article: https://www.photopea.com/tuts/photopea-says-i-am-blocking-ads-but-i-am-not/

**Comment by photopea** [comment]
I am glad you have fixed it!
