### ISSUE TITLE
[feature request] preload fonts + CDN

### ISSUE THREAD

**Issue by steamboatid** [photopea/photopea#6806]
Hi,

while I used photopea, especially when dealing with fonts.
Photopea only load selected style of a font selected.

For example, if I select font **Roboto** and use **Light style**, the app only load **Roboto - Light**.
When I need to use other style, such as **Bold style**, the app will load the font and need to wait considerably several seconds for the font to be loaded.

Waiting loaded fonts may take longer, depends on the internet and your server.

Why not preload all font style, when the user select a font type ?
You may use async ajax preloading for this.

Using CDN for fonts also will improve the app performance.

**Comment by steamboatid** [comment]
![image](https://github.com/photopea/photopea/assets/15952139/150d3610-ee2e-4477-a231-60d4b9ef3c25)

it just example how we wait a font to be loaded

**Comment by photopea** [comment]
I think if we load too many fonts, it can use too much data, and many users pay for data.

It should take less than 0.2 seconds to load a font. Where exactly are you located? Who is your internet provider?

**Comment by photopea** [comment]
The problem is, that you are loading 50 kB of data for 10 seconds, which is 5 kB/s, or 40 kb/s. Your internet speed is very low, it should be higher.

When I open https://www.firstmedia.com/, it says "403 forbidden". What do you see at that website? Also, could I ask you again to tell me where are you located?

**Comment by photopea** [comment]
Go to https://www.uptrends.com/tools/uptime and test the availability of https://www.firstmedia.com/

I don't think your internet provider is serious about providing you access to the internet, when their website does not work in most of the world.

![image (12)](https://github.com/photopea/photopea/assets/15955558/c94f1105-7efd-4d1b-b450-4cd666f40323)

**Comment by photopea** [comment]
Photopea should load fonts through a CDN now, so they should probably load faster even for your internet provider.
