### ISSUE TITLE
[feature request] multi project actions

### ISSUE THREAD

**Issue by steamboatid** [photopea/photopea#6807]
Hi,

Photopea already allow user to open several project in the app.
But, for the moment, its lacking of actions that apply to all opened project,
such as : Save All, Close All, Export All

It's also good, if Photopea can also **remember** the last several project opened.
Rather than digging several clicks away via file open sub menus, I believe its much faster if there history of opened projects the click them all.

For now I use Google Drive as my storage,
Its also lacking to open several psd at once. I need to open it one by one.
It's time consuming, because each opening actions is also waiting several seconds.

**Comment by photopea** [comment]
I have fixed it! You can select multiple items in a storage and press "Enter", they all will be opened in Photopea.

Photopea is a website and it does not have a direct access to your computer or Google Drive. If you install Photopea to your google drive, you can double-click items in your google drive to open them in Photopea.

https://www.youtube.com/watch?v=p7kjmwhlNrA
