### ISSUE TITLE
[feature request] tab actions

### ISSUE THREAD

**Issue by steamboatid** [photopea/photopea#6808]
Hi,

Photopea lacks of tab actions, for the moment, there is only **Close** action in the alternate/popup menu in the tabs.
So, maybe its good if we can have similar features like tabbed browser, such as: Close Others (tabs), Close Left (tabs), Close Right (tabs), Close All, Save All, etc

**Comment by photopea** [comment]
I have implemented it. When you right-click a "tab", you can choose "Close", "Close All", or "Close Others".

I think "save all" makes no sense, because you often create a document from scratch, and it is unclear whether you want to save a PSD / JPG / PNG, save to a computer, to google drive ...
