### ISSUE TITLE
When I go to transform; warp;and change to wave, it turns my image black. please help!

### ISSUE THREAD

**Issue by jcthreads** [photopea/photopea#6809]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
I can not reproduce it :( Did you try it in the Incognito mode, i.e. without any of your extensions modifying the code of Photopea?

**Comment by photopea** [comment]
I have to close it now, because the person did not reply.
