### ISSUE TITLE
Problem with Rasterize and Raster Mask

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#681]
I created rectangle shape with Rectangle Tool and added Raster Mask with Add Raster Mask button in Layers window. After this I rasterized this layer with right-click and Rasterize option in menu. After this actions it seems to have two Raster Masks and behaves strangely.
For example
1. If I try to merge this layer with other layer or convert to smart object image of layer suddenly changes (jumps around)
2. If I try delete Raster Mask I need to do it twice before it disappears

**Comment by photopea** [comment]
There really was a bug. I fixed it. Thank you!
