### ISSUE TITLE
Photopea's warp function doesn't work

### ISSUE THREAD

**Issue by angelaiaru** [photopea/photopea#6810]
I can't use the deform tool. When I click edit, transform the warp function does not appear clickable

**Comment by frozenpandaman** [comment]
Also encountering this. To clarify, Warp is actually clickable, but nothing happens upon clicking it. The menu does not close and you can press it over and over to no effect. Upon clicking, an action for "Free Transform" appears in the History list but nothing is transformed, no handles or bounding box appear, etc.

**Comment by photopea** [comment]
I think I have fixed it. Could you try it again?

**Comment by frozenpandaman** [comment]
Works great & as expected here! Thanks!

**Comment by photopea** [comment]
ok perfect :)
