### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by 77zitoon** [photopea/photopea#6812]
Your Operating System: Raspberry PI OS
Your Web Browser: Chromium
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Go to PeaDrive
3. A message says: "HTTP error 401: User's secret was already generated"

**Comment by photopea** [comment]
Hi, could you tell me your email address, that you use for your account?

**Comment by 77zitoon** [comment]
Hello, the email address I use for my account is:
***@***.***

**Comment by photopea** [comment]
I can not see it :( Could you open www.github.com and reply there?

**Comment by photopea** [comment]
I have to close it now, because the person did not reply.
