### ISSUE TITLE
Shortcuts Conflict

### ISSUE THREAD

**Issue by KevinZonda** [photopea/photopea#6813]
Your Operating System: macOS 14.3.1
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

I use macOS, so I will use command key like ctrl in Windows to trigger shortcuts(not sure is it reproducable in Windows).

If I use command++ to zoom in for few times, the key sequence may look like: (hold)command, (enter)+, (enter)+. Keep holding the command, and on the same time triger the - key, the picture will still be zoomed in, but it should be zoomed out.

i.e., the final key sequence may look like: (hold)command, (enter)+, (enter)+, (enter)-, (enter)-

**Comment by KevinZonda** [comment]
This also happened if use command+z instead of - one

**Comment by photopea** [comment]
It is a bug on all Macs, and we can not fix it :( See https://stackoverflow.com/questions/27380018/when-cmd-key-is-kept-pressed-keyup-is-not-triggered-for-any-other-key

**Comment by KevinZonda** [comment]
So sorry to hear that :(

**Comment by photopea** [comment]
Yeah. Either none of the Apple users dares to report it to Apple (as they dare to report it to Photopea), or Apple users did report it, but Apple is ignoring it. Either way, it is very sad.
