### ISSUE TITLE
Some cursors (like selection tool cursor) are invisible to greybackgrounds

### ISSUE THREAD

**Issue by rubening87** [photopea/photopea#6817]
if u're on #808080 background color and you choose selection tool u wont be able to see where your cursor is. because they use a similar color. 

interesting... when i check through the OBS recording screen, the cursor looks white and u can see it

**Comment by photopea** [comment]
I also can not see the selection tool cursors on a background 808080. How do you think we should solve it?

**Comment by rubening87** [comment]
i think you could check whats behind the cursora nd invert the color. but not sure if that would be a good approach. maybe dropping a shadow from the cursor (1px) but that could make the cursor less intuitve to know where the center is.  or MAybe making the cursor to have a small cross inside in a different shade of grey ( darker or lighter) that would ensure that at least of them will be shown. if i come with any other idea ill let you know

**Comment by photopea** [comment]
It should be fixed now. A cursor is a white cross with a black stroke around it.

**Comment by rubening87** [comment]
<3 , i've seen it. THANK YOU SO MUCH! it was quick.
