### ISSUE TITLE
A certain font I'm using gets selected in chunks and not individual characters when small.

### ISSUE THREAD

**Issue by MesaBlack** [photopea/photopea#6818]
Your Operating System: Chrome OS Version 124.0.6367.225 (Official Build) (64-bit)
Your Web Browser: Google Chrome Version 124.0.6367.225 (Official Build) (64-bit) / (installed version)
The problem happens in the Incognito Mode, too: n/a

**This must be done to see the problem**
1. Go to www.photopea.com
2. Use Brandon Grotesque
3. shrink sample text to around 25.72 px
4. click, hold, and move cursor to select text, and it's not individual characters, it's chunks

The font itself:
[BrandonGrotesque-Medium.zip](https://github.com/user-attachments/files/15540787/BrandonGrotesque-Medium.zip)

What's happening here:

[Screen recording 2024-06-03 6.25.04 PM.webm](https://github.com/photopea/photopea/assets/132141735/6d578f7a-45cb-4e2d-a955-21874b6f57f2)

**Comment by MesaBlack** [comment]
nvm I think I got it, but... in case others get this happening, it'll still be up.

**Comment by photopea** [comment]
I can not reproduce what you are describing :( I can select any separate character with a mouse, while using your font :( Why didnt you try it in the Incognito mode, i.e. with no browser extensions?

**Comment by MesaBlack** [comment]
nvm i made it trough anyway
