### ISSUE TITLE
"Are you blocking Ads?" still showing even in incognito with 0 extensions enabled

### ISSUE THREAD

**Issue by LexyTanaya** [photopea/photopea#6819]
Your Operating System: Windows 10 64-bit
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too:

![Capture](https://github.com/photopea/photopea/assets/26859772/7a2451e8-357f-48fd-94f5-ddd31521f197)

**This must be done to see the problem**
1. Go to www.photopea.com
2. Tries to edit images
3. Sees the "Are you blocking Ads"
4. Disables any adblock related extensions (I'm using uBlock Origin)
5. Still sees the pop-up message
6. Goes to incognito with 0 extensions enabled 
7. Still sees the pop-up
8. Frustrated, wrote an issue in github.

Is it because I'm in Indonesia that there are no ads to show to us?

**Comment by LexyTanaya** [comment]
Just used a VPN, no pop-ups anymore. Sorry to bother.

**Comment by LexyTanaya** [comment]
Just used a VPN, no pop-ups anymore. Sorry to bother.

**Comment by photopea** [comment]
Could your internet provider be blocking ads? Where are you located? Can you open these two links?

https://cmp.uniconsent.com/v2/85d3b9563e/cmp.js
https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js

**Comment by LexyTanaya** [comment]
No, my internet provider doesn't block ads. And as I write in my first post, I'm in Indonesia but after I use a VPN browser extension I can see ads normally on the right side and the pop-up message doesn't show either.

For me when I open the first link it shows me a plain text about bunch of coding stuff.
And the second link made me download a .txt file called "f.txt".. (I didn't accept the download).

**Comment by photopea** [comment]
Could you save the first link and the second link as two TXT files and show them to us? Attach them in your post here.
