### ISSUE TITLE
The eyedropper in color picker in text tool is still a move cursor

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#682]
The move cursor is so big, hard for precise color picking for the text.

**Comment by photopea** [comment]
Let's call it a default mouse cursor, not "move cursor". We are still waiting until Firefox implements it for hi-dpi screens. Do you think the eyedropper cursor (which is e.g. in Adobe Photoshop) would be better?

**Comment by hgs54371** [comment]
When color picker is open (the one in tool bar in text tool), change it to an eyedropper cursor is better for color picking
