### ISSUE TITLE
HTTP error: 401 : User's secret was already generated.

### ISSUE THREAD

**Issue by KeeSimSon** [photopea/photopea#6820]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Go to PeaDrive
3. A repeated pop up message says: "HTTP error: 401 : User's secret was already generated.".

**Comment by photopea** [comment]
Hi, could you tell us your email address that you see after clicking the "Account" at the top?

**Comment by KeeSimSon** [comment]
may i know how can i tell my email address here without being visible by others?

**Comment by photopea** [comment]
Send me your email address to support@photopea.com
