### ISSUE TITLE
The background of the icon in taskbar isn't transparent

### ISSUE THREAD

**Issue by kassem3** [photopea/photopea#6821]
Your Operating System: Windows 11
Your Web Browser: MS Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Click the three dots at the top right
3. Hover over More Tools
4. Click Pin to taskbar
5. The Icon has a grey background instead of a transparent one
![Screenshot 2024-06-05 212209](https://github.com/photopea/photopea/assets/159781549/716fbf81-d8bc-4c1e-8324-fed9f5c69eb9)

**Comment by photopea** [comment]
When I do it in MS Edge in Windows 10, here is what I see
![image](https://github.com/photopea/photopea/assets/15955558/5d1a9fbc-d6b8-45d1-a06c-d6b85ada7b25)

I think this is all in hands of Microsoft, as they invented and implemented this method of "pinning websites". I can not change the way it happens, you should report it to Microsoft.
