### ISSUE TITLE
"Alert" should not have blocked interactions

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#6822]
"Alert" blocks interactions with tab bar, move tool, etc. 
![屏幕截图 2024-06-06 122108](https://github.com/photopea/photopea/assets/79258245/27fe833f-7346-4d48-8d1d-3464e67a25b5)

`pointer-events: none;` could've fixed the problem, but it is commented out.

![image](https://github.com/photopea/photopea/assets/79258245/7cec5a80-a918-4ad0-b683-e55ad332986d)

**Comment by photopea** [comment]
it should be fixed now.
