### ISSUE TITLE
Smart Objects don't let you choose the interpolation mode when scaling/transforming anymore?

### ISSUE THREAD

**Issue by aZealot** [photopea/photopea#6823]
When scaling/transforming a raster image, you have the option to choose the interpolation mode, with your options being Nearest Neighbor, Bilinear, and Bicubic Sharpener. It used to be that you could do this with Smart Objects too, but now the option is gone. Can we bring it back? It was nice for deciding what look I wanted the transformed image to have before I rasterized it.

Raster image:
<img width="890" alt="Screenshot 2024-06-06 at 12 00 02 AM" src="https://github.com/photopea/photopea/assets/51274537/691bf50d-8898-4679-9cc2-6df4a7fdeacd">
Smart Object:
<img width="787" alt="Screenshot 2024-06-06 at 12 00 40 AM" src="https://github.com/photopea/photopea/assets/51274537/adf6a153-cae9-40da-94d4-4c9639ef083c">

**Comment by photopea** [comment]
This is a correct behaviour.

**Comment by photopea** [comment]
I have added the option into Edit - Preferences, where you can set the interpolation method for Smart Objects.
