### ISSUE TITLE
Video advertisements create significant GPU usage

### ISSUE THREAD

**Issue by JoshuaKimsey** [photopea/photopea#6824]
Your Operating System: Pop!_OS 22.04 (Ubuntu-based)
Your Hardware: Intel i9-9900k, RTX 3090, 64GB DDR4 RAM
Your Web Browser: Brave v1.66.118
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Run PeaMark when there advertisements on the screen
3. Run again with ads disabled (either via paying or ad block)
4. The scores between the one with and without ads will be rather significant.

It seems that in particular, video advertisements are the culprit. When there is just one video advertisement playing, it doesn't seem to be meaningfully impactful to performance. However, as the side bar updates its advertisements from Google, it seems common for multiple video advertisements to be load at once (sometimes even the same video), which seems to put a lot of strain on the GPU. I lose a good 2/3rds of my performance, according to PeaMark, and I'm on an RTX 3090. In fact, when multiple video advertisements load in at once, it creates some stuttering when moving or dragging windows or elements around inside of Photopea.

I don't know if this is something controllable on Photopea's end, since the ads are being served by Google, though ideally perhaps video advertisements could be limited to one at a time? Regardless, I did want to bring it to your attention so you can know about it, even if it can't be mitigated from your end. Still enjoy leaving ads on for you to earn revenue from it though! Attached below are screenshots showing the performance gap without and with ads:

![Screenshot from 2024-06-06 02-48-02](https://github.com/photopea/photopea/assets/22421310/c98d9347-6a1e-4f04-b999-32f061c22d3d)
_Without Ads_

![Screenshot from 2024-06-06 02-54-48](https://github.com/photopea/photopea/assets/22421310/20c95f01-137f-4cd3-8698-ddec8a5f5e0d)
_With Ads_

Keep up the fantastic work on Photopea, truly the best and most accessible photo & image editing software around! ^_^

**Comment by photopea** [comment]
First of all, there should never be more than one video at a time. Are you sure there are two?

Second, the video should never use that much GPU power. Could there be a bug in your GPU drivers? Could you maybe try to update them? Or try Firefox?

**Comment by JoshuaKimsey** [comment]
There's definitely multiple videos playing at once. You can see that in my image above where the guy drinking the soda and the two people in the "Stayer" thing are both videos (with "Skip Ads" showing up on them sometimes, like it's a YouTube video, which is a bit odd), and the Starbucks ad above it was animated (though I don't think it counts as a true video).

But When I was working on something just now I had 3 and 4 videos playing at once, which was causing a lot of lag on my end. It was hard to move things with accuracy, since it was causing jitter. It's kinda odd, cause I can play multiple youtube videos at once without a hitch. Heck, I've played 4 and 5 at once before even, and my GPU didn't break a sweat. But I can hear my fans ramp up when those video ads load. So I'm not sure why this is happening with these. I can try in Librewolf (with extensions disabled) and see if it still happens. Maybe it's just a Chromium thing on Linux? Cause my drivers are fully update to date and functional. I'll get back to you about Firefox/Librewolf performance and let you know!

**Comment by photopea** [comment]
When I open www.photopea.com in Brave on Windows, I can not see any ads. As far as I know, Brave is always blocking ads in Photopea.

I think Brave is going a step further in your case - they insert their own ads into Photopea, to make money (by displaying you ads). Could you try Photopea in a normal browser like MS Edge or Firefox?

**Comment by photopea** [comment]
Brave could be mining bitcoins on your device, too, who knows :( They blocked me when I tried to submit a bug: https://x.com/photopeacom/status/1522687569833738248

Honestly, we do not accept any bug reports in Brave, as we do not consider it to be a web browser (a program which displays websites according to the web and internet standards).

**Comment by JoshuaKimsey** [comment]
Ok, after testing on Librewolf, I can confirm it still happens there, just differently. It seems like it hits the CPU harder (though strangely I get more CPU performance there than in Brave.) However, the CPU issue still presents itself. In particular when the videos are first loading in is when I see the worst performance drop. After they are playing it seems to recover somewhat, as you can see in the screenshots below. But when they first load in, the UI stutters hard. Also below is a screenshot showing that 5 videos loaded in at once

![Screenshot from 2024-06-06 07-03-40](https://github.com/photopea/photopea/assets/22421310/9a89777d-136a-47af-8bf7-a52515d6995a)
_Librewolf with ads blocked via uBlock Origin_

![Screenshot from 2024-06-06 07-06-59](https://github.com/photopea/photopea/assets/22421310/422b6aa6-d97b-45b4-bca7-91b2bdbb41a8)
_Librewolf with Ads enabled_

![Screenshot from 2024-06-06 07-07-48](https://github.com/photopea/photopea/assets/22421310/b1eea93b-0885-44c6-8bbc-8bbff7a6cdcc)
_5 videos loaded at once_

**Comment by JoshuaKimsey** [comment]
> When I open [www.photopea.com](http://www.photopea.com/) in Brave on Windows, I can not see any ads. As far as I know, Brave is always blocking ads in Photopea.

Yeah, you have to turn off Brave Shields to see the ads, which I'm fine with for you to earn revenue off of. But it's definitely not brave inserting them, it's from the same Google sources as seen above in the Librewolf images.

**Comment by JoshuaKimsey** [comment]
Ok, I tested in a clean install of default Firefox with no extensions installed. Multiple video ads played, which definitely was causing GPU performance issues too, though it was wildly inconsistent too. One batch of multiple video ads caused almost no performance hit, but then another batch did which I show below. Both Librewolf and Brave showed I get GPU performance of about >6000 with no ads, so it seems to be cutting about 40% of that. Here's a screenshot below showing the results.

![Screenshot from 2024-06-06 19-10-22](https://github.com/photopea/photopea/assets/22421310/62e3d5aa-f39b-4947-9289-fc355ab70e51)
_Default Firefox, no extensions, all of those ads are video ads_

**Comment by JoshuaKimsey** [comment]
And here is a clean install of Chromium, with no extensions. It's actually pretty bad, worse than Brave, Librewolf, or default Firefox, as the Benchmark shows. The PeaMark benchmark stutters for the GPU part when multiple video ads are playing, and it can be quite difficult to drag elements around on screen when those stutters happen. It really seems to be the video ads playing that's the problem. I don't think 1 playing would be all that bad, but trying to loads 2, 3, 4 or more really starts causing issues.

![Screenshot from 2024-06-06 19-18-35](https://github.com/photopea/photopea/assets/22421310/5aed7b72-a35f-4ec5-b29e-2c7363183fdd)
_Default Chromium, no extensions, all video ads_

**Comment by photopea** [comment]
I will ask my ad provider to either make videos use less power, or show just one video at most.

**Comment by photopea** [comment]
Does it work any better now?

**Comment by tsvetav** [comment]
@JoshuaKimsey looks like Google fancies you! :) 
I am a rep of Photopea's ad partner, and we have contacted Google for further assistance on the matter.

**Comment by JoshuaKimsey** [comment]
Ok, I just checked at @photopea and at first it was only loading one video, with minimal GPU impacts, but then after a couple loading cycles it started loading multiple videos again, with the same GPU impact. Attached below is a screenshot of that with the GPU performance.

And good to know @tsvetav! Let me know if I can be of any help with this, cause it's probably not that fair to the ad buyers either since I saw 3, 4, and even 5 of the same ad at once, as seen above in the screenshots.

![Screenshot from 2024-06-09 02-02-35](https://github.com/photopea/photopea/assets/22421310/5591cebd-a600-47ca-af36-3953814e7bf3)
_Brave with no Shields/ad blocking, 3 video ads shown on right causing a 50% drop in GPU performance_

**Comment by CaramelMacchiato17** [comment]
The visible ads aren't the problem The invisible ones are insane. There is something wrong with how ads are displayed. I have a gtx 1050 ti and 32 gigs of ram and my computer is CHUGGING.
![image](https://github.com/photopea/photopea/assets/120057417/25e1edc4-10fa-45bf-ba65-2ddbb284733b)

**Comment by CaramelMacchiato17** [comment]
Also, inspecting element on the page shows that when the blocker is on this happens 
![image](https://github.com/photopea/photopea/assets/120057417/6f69e630-ba1b-4453-a05a-5bf9236dfcde)
when off 
![image](https://github.com/photopea/photopea/assets/120057417/7ee88aec-3841-4167-837a-e55e922000f5)

**Comment by photopea** [comment]
What storage access and virus? what are you talking about?

**Comment by photopea** [comment]
Could you open "about://gpu" in your browser and check, if everything is GPU-accelerated?

**Comment by CaramelMacchiato17** [comment]
> What storage access and virus? what are you talking about?

In the Image above, it clearly shows attempted storage access from various sites, Rubicon is a tracking program that installs files directly to your phone/computer, Pubgalaxy is an advertisment based malware.

**Comment by CaramelMacchiato17** [comment]
> Could you open "about://gpu" in your browser and check, if everything is GPU-accelerated?

Yes, everything is. I've opened a new issue discussing this and another issue with the site, would it be best to delete my posts in this thread so as not to clutter?

**Comment by photopea** [comment]
Yes, please, delete your posts here.

**Comment by photopea** [comment]
Could you check if everything is GPU-accelerated in "about/gpu"?

**Comment by JoshuaKimsey** [comment]
Yes, I just checked and GPU acceleration/WebGL is enabled in Brave, Chromium, Firefox, and Librewolf.

**Comment by tsvetav** [comment]
@JoshuaKimsey hey again! This is to let you know that we have limited the in-banner videos, so after clearing all your cookies & cache you should not see 5 of them in a row but a single one at most.

**Comment by photopea** [comment]
I am closing it, it should not happen anymore.

**Comment by JoshuaKimsey** [comment]
@tsvetav Sorry for just now getting back to you. Yes I can confirm that it is no longer showing more than 1 video ad at a time and performance is much improved! Thank you @photopea and @tsvetav for fixing this issue! :)

**Comment by photopea** [comment]
you are welcome :) It is hard to find the right balance, to not drain the users computers too much, and to not lose 50% of our ad revenue (pretty much our only revenue, sadly).
