### ISSUE TITLE
Is there any way  to use your Refine Edge tool with API ?

### ISSUE THREAD

**Issue by Anustup900** [photopea/photopea#6827]
Am trying to refine edges, which have a problem of extra white edge. I am matting using VIT matte, the doing some layers of image processing to remove extra skins/artifacts and sharpen the edges. Still am seeing there are some white lines.
So curious if i can use the tool as an API

**Comment by photopea** [comment]
Hi, you can use Photopea in an iframe, as described at www.photopea.com/api

**Comment by photopea** [comment]
I will close it, as [www.photopea.com/api](http://www.photopea.com/api) is all we have.
