### ISSUE TITLE
Website Glitching

### ISSUE THREAD

**Issue by iVK49** [photopea/photopea#6828]
Your Operating System: Windows 10 pro
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com

When I go to (www.photopea.com) it doesn't load and just shows a white screen
And when I finally managed to get it to load somehow, it was full buggy and everything was magnified and out of place.

I also tried resetting site date, cookie and everything

I cant seen to make it load again, now its just stuck on a white screen.
![image](https://github.com/photopea/photopea/assets/172032444/02e8528e-8664-4c74-9116-16a0c1e5403e)

**Comment by photopea** [comment]
Did it ever work before? What version of Chrome do you use?

**Comment by iVK49** [comment]
I use chrome Version 125.0.6422.142 (Official Build) (64-bit)
and i've used photopea 2 days ago, I wasn't facing the same problem then

**Comment by photopea** [comment]
Could you try it again in the Incognito mode?

**Comment by iVK49** [comment]
I just tried that too, and also with other gmail accounts, but it still doesn't seem to be working 
![image](https://github.com/photopea/photopea/assets/172032444/4e81e395-bb5a-42b5-90fb-339fd2a94c0a)

**Comment by photopea** [comment]
do you see any errors in a web console? Nobody else is reporting any problems, whe have had 1 million users in the last 24 hours.

**Comment by iVK49** [comment]
Oh yea, i see some errors here, but i dont really know how to resolve this 
![image](https://github.com/photopea/photopea/assets/172032444/dc6328db-6173-45b4-a0ef-03c58eb4bc70)

**Comment by joshuajohncohen** [comment]
This seems like a DNS issue, what are your DNS servers set to? Try going to vecpea.com as that is where the code is hosted at, the NAME_NOT_RESOLVED means it can't load the actual code. Does it load / redirect to photopea.com or does it show an error?

**Comment by photopea** [comment]
Do you have access to all websites of the internet? Can you open e.g. www.vecpea.com or www.google.com ?

**Comment by iVK49** [comment]
I have access to google, but i can't access https://www.vecpea.com/

**Comment by photopea** [comment]
Do you know why you cant access https://www.vecpea.com/ ? Photopea will not work without this website.

**Comment by iVK49** [comment]
Not really, when i enter the console of vecpea, it still shows these errors
![image](https://github.com/photopea/photopea/assets/172032444/9731383a-b053-4133-b4dc-8fe35da8414e)

**Comment by photopea** [comment]
You should ask your internet provider about why they are bloking www.vecpea.com . Why dont they block www.photopea.com?

**Comment by iVK49** [comment]
well, it worked properly a few days ago

**Comment by photopea** [comment]
You need an internet connection in order to use Photopea. Internet connection means the ability to open any website. We can not help you if you dont have an internet connection :(

**Comment by iVK49** [comment]
Huhh, i have a internet connection lol

**Comment by joshuajohncohen** [comment]
What are your DNS servers set to?
Try setting them to 8.8.8.8 and 8.8.4.4 (Google public DNS), if there are 4 fields just leave the other two blank

**Comment by photopea** [comment]
You need an internet connection which lets you access all websites, including www.vecpea.com

**Comment by chandujr** [comment]
I'm using a JavaScript blocker tool. I had whitelisted photopea.com in it and the website was working properly till 2 weeks back. Now it draws a blank page and I can see this vecpea.com domain in the blocked list. Can you please clarify why this domain is a required now?

**Comment by joshuajohncohen** [comment]
Because photopea.com only hosts the base HTML to link everything together, all the code/assets/CSS is hosted on vecpea.com

**Comment by photopea** [comment]
www.vecpea.com is our CDN domain. Why are you blocking vecpea.com but not blocking Photopea.com? Do you think "photopea.com" has a "less risky javascript", whatever it means?

**Comment by chandujr** [comment]
My question might have come as a bit aggressive, I'm sorry about that. The JS blocker plugin blocks everything by default and I had to unblock photopea.com during the first load. I just wanted to know why the CDN is required now as compared to some weeks ago. I'm not accusing you of anything, if that's the feeling you got. Your website had helped me a lot.

**Comment by photopea** [comment]
Some internet providers in the southeast asia were not able to open www.Photopea.com (it took over 3 minutes). But with a CDN, they can load Photopea in four seconds. We have it mainly because of them.
