### ISSUE TITLE
Photopea randomly gets super slow and sometimes unresponsive

### ISSUE THREAD

**Issue by interstellar-tars** [photopea/photopea#6829]
Your Operating System: Windows 11
Your Web Browser: Microsoft Edge
  The problem happens in the Incognito Mode, too: Yes

When ever I'm editing something in Photopea, there is almost always a moment where the page goes super slow and sometimes unresponsive to my mouse and keyboard. It's very annoying as I'm always messing stuff up because of it.

*Console shows no errors*

**Comment by photopea** [comment]
What should I do to see it happen myself? How much RAM do you have?

**Comment by interstellar-tars** [comment]
I have 16GB of RAM and there is no specific way to see it happen, it just happens randomly just to the photopea page itself, not my browser.

**Comment by goofyaaah123** [comment]
this happens to me too

**Comment by photopea** [comment]
It would really help if I could see it happen myself :( Could you at least record a video of it? When it happens, do you have any free RAM left?

**Comment by interstellar-tars** [comment]
If it happens again I will record it. And Yes I have about 12GB of RAM left when it happens since I don't have too much stuff running.

**Comment by photopea** [comment]
Let me know once you can make Photopea slow on purpose, and tell us how you did it.

**Comment by interstellar-tars** [comment]
Hey there. I'm unable to get a video but after some testing, I can say that its the ads that are causing the slowness and unresponsiveness. Once the divs are removed via inspect element, the slowness and unresponsiveness stops immediately.
If possible, try bringing it down to 2 ad spaces rather than 3, also try slowing down how often these change.

**Comment by photopea** [comment]
What is your Peamark? Test it in More - Peamark. And how many ad units do you have?

Why are you unable to get a video?
