### ISSUE TITLE
[Feature Request] Add support for extracting depth map from HEIC/HEIF iPhone images that were taken in Portrait mode (only works if iPhone set to JPEG right now)

### ISSUE THREAD

**Issue by joshuajohncohen** [photopea/photopea#6830]

**Comment by photopea** [comment]
Could you share a HEIC file with a depth map with us?

**Comment by joshuajohncohen** [comment]
https://depth.horizon.camera/

**Comment by photopea** [comment]
I have looked into it, and it seems to be too hard to extract a depth map out of a HEIC file. Just switch your phone to JPG, JPG files are only 10 - 20% bigger than HEIC, and modern phones have hundreds of GB of storage anyway.
