### ISSUE TITLE
Scaling Options and Layer style is not showing up on the screen and the output

### ISSUE THREAD

**Issue by PizzaGuy1222** [photopea/photopea#6831]
Your Operating System: Windows 8
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Don't know

**This must be done to see the problem**
1. Go to www.photopea.com
2. Start a new project
3. Go to the search bar and search "free transform or, scale, or rotate
4. it wont show the scaling tools that you are doing to your layer and doesnt show the transform action you preform in the output
this also goes the same with layer style please fix this issue it is really annoying

**Comment by photopea** [comment]
clicking on the options in a search bar should work now.
