### ISSUE TITLE
Move tool isn't working, appears to be a glitch

### ISSUE THREAD

**Issue by pdcaster7** [photopea/photopea#6832]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. .... I create a new file, in this case a 3000 x 3000 image with a red solid background color.
3. .... I open another image, use Ellipse Select to highlight and cut part of the image, which I paste into the original file, over the background layer.
4. .... The Move Tool doesn't work. I can't use it to move the second, imported layer around. When I click on the image, it just creates a box, as if to highlight an area of the image. I can't move the background either.

This is all weird, because before pasting the image, I was able to move the background around. And on the second image (the one I cut and paste over the original background layer), I'm able to move that around fine with the Move Tool.

The image I'm cutting and pasting is a high quality image, but this seems so weird.

**Comment by pdcaster7** [comment]
I should mention the project settings, I'm using 300 DPI and 32 bit sRGB.

I tried to tone it down a little, and went with 72 DPI and 8 bit sRGB, that seems to work fine.

So I'm wondering if Photopea can't handle the intense resolution, lol. I dunno, I'm just guessing.

**Comment by pdcaster7** [comment]
I should mention the project settings, I'm using 300 DPI and 32 bit sRGB.

I tried to tone it down a little, and went with 72 DPI and 8 bit sRGB, that seems to work fine.

So I'm wondering if Photopea can't handle the intense resolution, lol. I dunno, I'm just guessing.

**Comment by pdcaster7** [comment]
Update: It definitely appears to be the Profile -> sRGB -> bit settings, as if I switch from 32 to 16 bit, there are no issues. I can move the cut/pasted layer just fine. As soon as I switch to 32 bit, it doesn't work, you just click and it creates a drag box, and it cannot move the layer with the Move Tool.

**Comment by camoody1** [comment]
@pdcaster7 You should probably re-open this if you still want input from the developer.

**Comment by photopea** [comment]
It should be fixed now.
