### ISSUE TITLE
Magic replacement is not working 

### ISSUE THREAD

**Issue by Gemglitch888** [photopea/photopea#6833]
Your Operating System: Windows 11
Your Web Browser: Microsoft Edge
I am currently unable to use the magic replacement tool as I am using the free version of the software. When I try to use it, I am prompted with the message, ‘This is a Premium feature. Go Premium for $5 a month (press “Account” at the top). Or watch two short ads to do it for free?’ However, I only receive one ad, and sometimes no ads are shown at all. Even after watching the ad, nothing gets replaced in my image.

**Comment by photopea** [comment]
I just tried it, and it works fine, after the two ads are played. Did you try it in the Incognito mode?

**Comment by Gemglitch888** [comment]
> “I just tried using Photopea in incognito mode, and it’s working. However, I am still unable to use it without incognito mode

**Comment by photopea** [comment]
I think you have browser extensions, which break Photopea. Could you show us a list of your extensions, which have your permissions to modify Photopea?

**Comment by photopea** [comment]
It seems to me like a bug in your ad blocker. Ask them to fix it, or use a different ad blocker, or use Photopea in the Incognito mode.

**Comment by Gemglitch888** [comment]
Okay thank you for your help
