### ISSUE TITLE
erases progress

### ISSUE THREAD

**Issue by goofyaaah123** [photopea/photopea#6834]
freezes and says low memory refresh or close page and when i refresh it erases the majority of my progress

**Comment by goofyaaah123** [comment]
it has happened about 10 times since i reported the bug

**Comment by photopea** [comment]
What should i do to see the error? If you are editing a 300 MB PSD with 2 GB of RAM, that is simply not enough.

**Comment by goofyaaah123** [comment]
i dont know what that means

**Comment by goofyaaah123** [comment]
it usually happens if i leave the tab up for a while and right before it happens photopea is unrepsonsive i can only move things but i cant edit them or move layers over eachother

**Comment by photopea** [comment]
I need some steps to reproduce this behaviour. 90% of problems with Photopea are caused by browser extensions, so I recommend disabling all browser extensions which have permissions to modify Photopea.

**Comment by photopea** [comment]
I have to close it because of lack of details.
