### ISSUE TITLE
Can't Resize Anything

### ISSUE THREAD

**Issue by dirwael** [photopea/photopea#6835]
Your Operating System: Windows 11
Your Web Browser: Microsoft Edge
The problem happens in the Incognito Mode, too: No

1. Go to www.photopea.com
2. Create new project.
3. Place an image or shape, write some text, etc.
4. Have transform controls on.
5. The controls are unresponsive.

Sometimes the transform controls work at the start, but if you click on another tool, then go back to whatever you want resized, they suddenly don't work.

**Comment by photopea** [comment]
So everything works fine in the incognito mode? In that case, you use browser extensions, which break Photopea.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
