### ISSUE TITLE
Photopea "remember" last file size saved

### ISSUE THREAD

**Issue by ShinSakamoto** [photopea/photopea#6836]
Your Operating System: windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. open an image, for example, 1200x1200 px
3. then export it as png format reducing its size to 600x600 px
4. now open another image different size from 600x600 px
5. then try to export this new image and you will see on the export screen that the size label box has 600x600 px (different from original image size)
6. it means, photopea "remember" the last image saved size.
7. to avoid this to happen I need to click "F5" to reload photopea

**Comment by photopea** [comment]
This happens ONLY IF the image in step 2 has the same size as the image in step 4.

If you are exporting a 1200x1200px image as 600x600px, and a bit later, you try to export a different 1200x1200px image, I think users would probably also want to export it at 600x600px.

**Comment by photopea** [comment]
I am closing it, as this is an expected behaviour.
