### ISSUE TITLE
file error

### ISSUE THREAD

**Issue by susanta8399** [photopea/photopea#6837]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by camoody1** [comment]
You've given the developer absolutely nothing to go with her. You might as well have never even opened this ticket. 🤷🏼

**Comment by photopea** [comment]
I need some proof that there is a problem. E.g. seeing a video of a problem, or seeing the same problem myself.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
