### ISSUE TITLE
edit flipping tool cooldown

### ISSUE THREAD

**Issue by goofyaaah123** [photopea/photopea#6838]
i cant use the flipping tool multiple times in a row, if i use it multiple times too quickly it wont work anymore and i have to wait around a minute to use it again

**Comment by photopea** [comment]
What is a Flipping tool?

**Comment by goofyaaah123** [comment]
Go to edit, transform and there is flipping options for 90 degrees 180 degrees horizontally and vertically

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by photopea** [comment]
I have tried it about 10 times, and it works correctly, instantly, each time I click the item in the menu.

Does it happen to you in the Incognito mode? Your browser extensions could be breaking Photopea.

**Comment by photopea** [comment]
I have to close it, because the user did not respond.
