### ISSUE TITLE
Possible Phishing links when using adblocker, GPU tanks otherwise

### ISSUE THREAD

**Issue by ghost** [photopea/photopea#6839]
Your Operating System: Windows 11
Your Web Browser: Microsoft Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Disable Ad Blocker
2. Go to Photopea.com
3. Open a new project
4. inspect element the page

When the adblocker is OFF, the entire site runs at a quarter speed due to the amount of tracking requests, storage access requests, and advertisements shown on the frontend and in the code.

Repeat steps one and two, and inspect element the page to recreate this.

![Screenshot 2024-06-09 135958](https://github.com/photopea/photopea/assets/120057417/f35298bd-f431-4218-8234-42f9458af84d)
![Screenshot 2024-06-09 140329](https://github.com/photopea/photopea/assets/120057417/28c2c0d1-4541-41cd-8230-8c199c7b2411)
![Screenshot 2024-06-09 140652](https://github.com/photopea/photopea/assets/120057417/bf6dbfb0-a472-4f02-9810-e68129aefe44)

I'm seriously concerned because another issue was brought up regarding this, and the person was told that the browser they were using was probably trying to bitcoin mine or inserting their own ads.

Applications CAN'T do that, from what I'm aware...

Photopea, has your site been hacked? If I, as a hobbyist with minimal development knowledge, can figure all of this out I'm sure you can too. I hope I'm not coming off as rude but this seems extremely suspicious... in any case this information should be helpful in figuring out the GPU usage problem

![image](https://github.com/photopea/photopea/assets/120057417/ccde25d0-de42-482c-8f33-bee28e194170)

**Comment by photopea** [comment]
Hi, these are my games. What do you mean by being malicious? What kind of nonsense is this?

**Comment by CaramelMacchiato17** [comment]
> Hi, these are my games. What do you mean by being malicious? What kind of nonsense is this?

Hey,

The images posted will help better explain what's going on. The site used has been reported as malicious.

**Comment by photopea** [comment]
https://t.ly/ is just a URL shortener, I dont think it is malicious, whatever you mean by that.

**Comment by CaramelMacchiato17** [comment]
> https://t.ly/ is just a URL shortener, I dont think it is malicious, whatever you mean by that.

Alright then. That's fine.

The other issue though is the bigger one, I think the site may be constantly refreshing the ads?

**Comment by photopea** [comment]
Yes, ads should change every 20 - 30 seconds, not "constantly".

**Comment by CaramelMacchiato17** [comment]
> Yes, ads should change every 20 - 30 seconds, not "constantly".

Gotcha. Apologies for the url shortener confusion. It seems like they're refreshing at an increased rate?

**Comment by photopea** [comment]
What do you mean by that? What is the actual probelm that you have while using Photopea?

**Comment by CaramelMacchiato17** [comment]
> What do you mean by that? What is the actual probelm that you have while using Photopea?

The issue occurring now is that the site is TANKING my gpu and slowing down immensely, and upon closer inspection it is attempting to serve thousands of ads at once.

**Comment by photopea** [comment]
Could you record some video of what is "tanking your gpu"? Animated ads do use some computing power, but it should not be very significant.

**Comment by photopea** [comment]
I have to close it, because the user did not provide any proof.
