### ISSUE TITLE
upgrade premium account

### ISSUE THREAD

**Issue by jangeerts** [photopea/photopea#6840]
Hello,
I'd like to upgrade my Premium account before the current one ends, because I'm happy with the results. But when I try to buy a bigger Premium account, it says I  already have one. That"s right, I just want to buy a bigger one before this short one ENDS, is that possible?

Thanks in advance,
Jan

**Comment by photopea** [comment]
When your Premium ends, ads come back, and you are back with a free version. You can pay again then, whenever you want :) Your account will not be deleted or anything :D
