### ISSUE TITLE
A <label> isn't associated with a form field.

### ISSUE THREAD

**Issue by Iliya5digital** [photopea/photopea#6843]
Your Operating System: Windows 11 Pro 23H2
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

1. Go to www.photopea.com
2. Open any image
3. Create Selective color layer
4. Choose Yellow color
5. Hit F12 and opens DevTools
6. After opening DevTools, hover over the “Problems” tab and click on it
7. Find "No label associated with a form field." and click on it.

[Violating nodes.txt](https://github.com/user-attachments/files/15774635/Violating.nodes.txt)

**Comment by photopea** [comment]
I am confused. Photopea is not supposed to be used from DevTools. It is supposed to be used in a web browser. Do you have any probem with Photopea as a user of Photopea?

**Comment by Iliya5digital** [comment]
There are problems. Described above. Even you didn't look at the attached file

**Comment by Iliya5digital** [comment]
No, am not a bot

**Comment by Iliya5digital** [comment]
![Снимок экрана 2024-06-10 224428](https://github.com/photopea/photopea/assets/115736491/b5a80017-cbf0-431d-88ba-f0e4ed02b2c1)
![Снимок экрана 2024-06-10 224437](https://github.com/photopea/photopea/assets/115736491/5f93ea19-d480-43f5-8c4b-85e32ac11260)

**Comment by photopea** [comment]
It is called "Issues" in English, not "Problems". It should be fixed now.
