### ISSUE TITLE
Suggestion: Add Peadrive support to Gradient

### ISSUE THREAD

**Issue by hetzbh** [photopea/photopea#6845]
I'm playing with Photopea and I found that the Gradient Import/Export only works with local drive, and IMHO a support for importing/exporting to Peadrive could help a lot if a user is using Photopea from several machines where their gradient files cannot be accessed.

Just an idea ;)

**Comment by photopea** [comment]
If you have a GRD file in your PeaDrive (or any other Storage - https://www.photopea.com/learn/storages), just double-click it and it will be added to Photopea.

If you are looking at a storage, you can drag-and-drop files from your computer into that storage.

I don't want to ask every user of Photopea to create a PeaDrive, to be able to save their Gradients and stuff :/
