### ISSUE TITLE
getting compressed psd file from the api 

### ISSUE THREAD

**Issue by vedantdere** [photopea/photopea#6847]
Your Operating System: Windows
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1] Send any psd file in a photopea api check the size of the original file (in my case it is around 11MB)
2] api will open the file dont do anything just save the opened file it will send the POST request to the server defined and write the file and check the file size (in my case it is around 6.88 MB)

**Comment by photopea** [comment]
What exactly is the problem? What do you want to work differently and why?

**Comment by vedantdere** [comment]
solved the issue ```"formats" : ["psd"] // Example format settings``` only setting this will not compress the output psd file.

**Comment by photopea** [comment]
It is described here: https://www.photopea.com/learn/scripts#:~:text=%22-,psd,-%3Atrue%22%20%2D%20%22true . Minified PSD files do not contain a thumbnail at the end of a file.
