### ISSUE TITLE
Saved work loads up as Unsaved work whenever I open Photopea on my browser

### ISSUE THREAD

**Issue by Diamondbro10795** [photopea/photopea#6848]
Your Operating System: ChromeOS
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....open some very big PSD files(like at least 30-50 MB)
3. ....ctrl S and see how it doesn't save
4. ....Save it by pressing "File", then "Save as PSD"
5. Refresh
6. See how it reopens as an unsaved work even though it was already saved.

**Comment by photopea** [comment]
The functionality of Photopea is being broken by your browser extensions, see https://www.photopea.com/tuts/photopea-opens-up-old-files/

**Comment by nailadefitri** [comment]
Hello, I',m Naila. Sorry, but the method didn't work, the unsaved projects which were already saved actually added 2. how about this?

**Comment by photopea** [comment]
It is described in this article: https://www.photopea.com/tuts/photopea-opens-up-old-files/

The easiest way is to clear the website data ("cookies"). And later, turn off your browser extensions which cause these files to accumulate.
