### ISSUE TITLE
[Feature Request] PNG to TGA w/ Alpha layer from transparency

### ISSUE THREAD

**Issue by Master-64** [photopea/photopea#6849]
Won't add much more to this post, other than mentioning this feature would be very helpful for some of the work I do. I tend to run into scenarios where I need to batch a ton of PNGs to TGAs. While the current functionality for batch converting the images does in fact work, it does fail to preserve the transparency layer in the PNG over into the TGA's alpha layer. Adding this feature would save me a ton of time, plus other people's time. A software that does what I'm mentioning doesn't appear to exist without a lot of limitations, aside from Photopea, which is very close to having this functionality.

**Comment by photopea** [comment]
Could you ask the creator of your software (which loads TGA files) to make it accept PNG files? TGA format is a very outdated format and should be replaced with PNG nowadays.

**Comment by Master-64** [comment]
In this particular case, I have no choice. The software is very old and closed-source. If I could, I would.

In either case, I feel like this support should be added, since while Targa files are very rare to be utilized nowadays, it's still a helpful format for those developing images for use in much older software.

**Comment by photopea** [comment]
What is actually stored in the fourth channel of your PNGs? In PNGs, usually a transparency of the RGB image is stored in a fourth channel. But in TGA, people attach many random grayscale images into the fourth channel, it is usually not a transparency. That is why it is not done by default.

When you open a TGA file with four channels in Photopea / Photoshop, the fourth channel is added as a separate channel into Window - Channels.

**Comment by Master-64** [comment]
I've compared my PNG files and then making a brand new PNG file using Photopea, and the channels look identical for both. The RGB channel, then the Red, Green and Blue channels, as would be expected. However, I'm unsure what you mean by "a transparency of the RGB image is stored in a fourth channel", because this doesn't seem to be observable while using Photopea when making a brand new PNG. It's not like with a TGA where it shows a layer that is the alphamap (in grayscale).

So from what it sounds like, you could add an option for TGA exporting where it can assume the current transparency on the file is supposed to be converted to an alphamap for the TGA. That way, it doesn't mess up normal exports in any way, but also allows users like myself to easily convert PNGs to TGAs with the transparency layer the PNG had to an alphamap. Would be sweet if that could be done backward as well, however I'm currently considering the PNGs I have to be my source, then I'm having to convert them to TGAs for importing, so that wouldn't be 100% necessary.

**Comment by photopea** [comment]
okay, it should work as you expect now.
