### ISSUE TITLE
Picture looks dull and dark when opening in Photopea

### ISSUE THREAD

**Issue by dkmullins** [photopea/photopea#6851]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
![IMG_0456 (1)](https://github.com/photopea/photopea/assets/172524020/0991b024-67f9-4cc9-9f84-2ea51957c4a9)
![IMG_0456](https://github.com/photopea/photopea/assets/172524020/79f216d6-fe3f-4613-a91e-34318d9c979f)

3. .... The original is one without our logo
4. ....

**Comment by photopea** [comment]
I opened your image and exported it as a JPG, it looks fine to me. What should I do to see it "dull"?

![image (2)](https://github.com/photopea/photopea/assets/15955558/419edea0-ce27-4c8e-8464-e57ecdd9da8e)

**Comment by dkmullins** [comment]
It’s dull when I do it. Can you see the other attachment of how it looks
exported out of Photopea.

Sincerly,

*Dwayne K. Mullins*

**Comment by photopea** [comment]
I need some proof that your "dull" image was made in Photopea. E.g. tell me how can I produce such an image in Photopea myself. Or record a video of how you make this dull image.

**Comment by dkmullins** [comment]
I open up Photopea.  File, Open, select photo from my computer, and when it opens in photopea its dark and dull compared to the original.  This is even before I export it back out of photopea.

**Comment by photopea** [comment]
Could you share a screenshot of Photopea after you open the image in it, so that I can see how it looks in your case?

**Comment by camoody1** [comment]
@dkmullins You realize that you're asking for help from the developer of a free application while sending him screenshots of you actively blocking advertisements on his app? Try using In Cognito mode where no browser extensions are running and see if that makes a difference.

**Comment by dkmullins** [comment]
@camoody1 Ha!  Thank you for your suggestion.  I will try that.  Also, I am not actively blocking his advertisements as they are the left of my screen and the screenshot is not full screen.  It's offered as a free app and he asked for the screenshots.

**Comment by camoody1** [comment]
@dkmullins The advertisements in Photopea are always on the right of the screen. And he's, it is absolutely offered as a free application... with ads.

**Comment by dkmullins** [comment]
What are you talking about??  Here's the other half of my screen.  The ads are showing.  I just clipped them out of the last screenshot.  Does it matter?!  
![Screenshot 2024-06-13 093852](https://github.com/photopea/photopea/assets/172524020/ddd026fc-a1f4-4347-a501-beda7b0ae7cb)

**Comment by photopea** [comment]
I can see the problem myself, and I will fix it soon.

**Comment by photopea** [comment]
It should be fixed now.
