### ISSUE TITLE
Pasting with ctrl+v in Firefox adds black background to transparent copied image

### ISSUE THREAD

**Issue by 2018ik** [photopea/photopea#6852]
Your Operating System: Windows 11
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com with Firefox
2. Open any image
3. Select any area with lasso tool
4. ctrl + c -> ctrl + v will add a black background to pasted image
5. Right click -> copy will work normally

**Comment by photopea** [comment]
I can reproduce it in Firefox 127, which was released yesterday. It did not happen in Firefox 126.

I think it is a bug in Firefox 127. I have reported it to Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1902217

Try to switch to Firefox 126, or some different web browser, until they fix it.
