### ISSUE TITLE
lag and progress gets erased

### ISSUE THREAD

**Issue by goofyaaah123** [photopea/photopea#6854]
photopea just got really slow none of my other tabs were lagging and then it froze and showed me a screen that said there was a problem loading this page and it erased most of the progress that took me over an hour

**Comment by photopea** [comment]
What should I do to make Photopea freeze like this? When Photopea crashes, you should see your work again when opening it next time, as described here: https://www.photopea.com/tuts/photopea-opens-up-old-files/

**Comment by goofyaaah123** [comment]
if i leave it open for a long time it usally crashes. When i get the prompt that says there was a problem loading this page it says refresh or close the page and when i refresh my progress resets. Usually when i open photopea my work saves but if it crashes and i try to open a new page it takes me back like 40 minutes.

**Comment by photopea** [comment]
I need some clear steps, what should I do to see the problem that you see.

**Comment by goofyaaah123** [comment]
i just regularly edit things and it gets really laggy and just crashes

**Comment by goofyaaah123** [comment]
it happened to me again right now but it erased everything i did

**Comment by photopea** [comment]
Could you record a short video of opening www.photopea.com and what you do next, including "everything being erased"? So that I see what you mean.

**Comment by photopea** [comment]
I have to close it because of lack of details.
