### ISSUE TITLE
Copying error in Photopea

### ISSUE THREAD

**Issue by besideman** [photopea/photopea#6855]
Since yesterday, when selecting with the lasso and copying a section of one photo then pasting it into another, the surrounding black background is also transferred along with the desired shape, making the photo montage completely impossible. Until midday yesterday, nothing like this had happened anywhere - what is the cause of this error and can it be fixed somehow quickly? 
![shark](https://github.com/photopea/photopea/assets/163296473/27604ef6-2cde-44fe-bf36-4c41fa9eebb2)
![shark 1](https://github.com/photopea/photopea/assets/163296473/bdcb8efd-a4a5-4d8f-83d2-00f6b8f16f8f)

**Comment by besideman** [comment]
I thought it might be a problem only on my computer, but I restarted it - nothing helped, and today I opened the program on a completely different computer and the same thing appeared - it's a system error then.

**Comment by photopea** [comment]
You have switched from Firefox 126 to Firefox 127 yesterday, is that correct?

**Comment by photopea** [comment]
The latest Firefox 127 has this problem. Try to use Firefox 126, 125, 124 etc. instead.

**Comment by photopea** [comment]
I have reported it to Mozilla, there is nothing more I could do :( If you know someone at Mozilla, ask them to fix it as soon as possible.

https://bugzilla.mozilla.org/show_bug.cgi?id=1902217

**Comment by besideman** [comment]
OK, thanks... On the other browsers it will be fine then?
