### ISSUE TITLE
Does not open PNGs in correct order on Windows 11.

### ISSUE THREAD

**Issue by OK-NUMBER** [photopea/photopea#6856]
When you make a gif, you take about 40+ screencaps of a scene. The order that they are taken is the order that you want when you CTRL-A and order and place them. In Windows 10, this works perfectly fine; all layers are in order. In Windows 11, they don't arrange in the correct order, creating a very choppy gif. If this is a Windows 11 bug, I hope to see it fixed. Reference:

https://www.reddit.com/r/photopea/comments/1dd43o0/opening_files_not_working/
https://www.reddit.com/r/photopea/comments/1dbho2v/opening_my_layers_out_of_order/

Big fan of this app, thanks!

**Comment by photopea** [comment]
If it works differently in Windows 10 than Windows 11, I am afraid we can not do anything about it.

I would like to reproduce it (see it happen on my computer). Could you share your "screencaps of a scene" with us, so that I can try it and see it happen myself?

**Comment by OK-NUMBER** [comment]
![testing mp4_20240608_205448 943](https://github.com/photopea/photopea/assets/172606139/a69e4339-9f63-41fc-a645-490f248600c3)
![testing mp4_20240608_205449 065](https://github.com/photopea/photopea/assets/172606139/2b262060-5f65-4369-86ef-5653b1c40258)
![testing mp4_20240608_205449 178](https://github.com/photopea/photopea/assets/172606139/7e462ac5-ae1a-4215-bc2f-8bb8906824f3)
![testing mp4_20240608_205449 293](https://github.com/photopea/photopea/assets/172606139/70640937-c97a-4bdd-ad65-cf60d1f1eeae)
![testing mp4_20240608_205449 412](https://github.com/photopea/photopea/assets/172606139/08a2700e-576c-4d05-9392-2f8bd66f928a)
![testing mp4_20240608_205447 907](https://github.com/photopea/photopea/assets/172606139/a063c70f-22f7-482f-a073-f53b9179c704)
![testing mp4_20240608_205448 042](https://github.com/photopea/photopea/assets/172606139/829015aa-6179-4984-bfa3-d6541625a087)
![testing mp4_20240608_205448 169](https://github.com/photopea/photopea/assets/172606139/1f319982-96f0-46f5-9272-69588892f1cd)
![testing mp4_20240608_205448 305](https://github.com/photopea/photopea/assets/172606139/bb7724fd-2286-4f51-a961-b0d2c82a3aef)
![testing mp4_20240608_205448 429](https://github.com/photopea/photopea/assets/172606139/5a6f7c77-6149-4efc-bbb5-65b8aedf72f5)
![testing mp4_20240608_205448 557](https://github.com/photopea/photopea/assets/172606139/fd9547bf-30c7-46cd-a1e3-cdcc86d3f504)
![testing mp4_20240608_205448 685](https://github.com/photopea/photopea/assets/172606139/5da4cc38-f12d-4b44-9e5c-a7b9880f0202)
![testing mp4_20240608_205448 813](https://github.com/photopea/photopea/assets/172606139/39b59d3a-b5d7-4b43-a4e9-45aebd989f84)
![testing mp4_20240608_205446 990](https://github.com/photopea/photopea/assets/172606139/afced0bb-b272-4823-8c70-efbc7b3f8ee6)
![testing mp4_20240608_205447 111](https://github.com/photopea/photopea/assets/172606139/c492ac51-f173-491b-9e96-fa8227a8084b)
![testing mp4_20240608_205447 236](https://github.com/photopea/photopea/assets/172606139/f197348e-e7df-4414-b008-1400bf6ee472)
![testing mp4_20240608_205447 371](https://github.com/photopea/photopea/assets/172606139/e81cc4c4-5558-4c07-9f06-fc64b453eca6)
![testing mp4_20240608_205447 502](https://github.com/photopea/photopea/assets/172606139/d8f548c4-c4e9-44a9-a949-2f2f9a3be0c1)
![testing mp4_20240608_205447 649](https://github.com/photopea/photopea/assets/172606139/e743c9ab-bc6a-43f9-a207-0d0bdfd9d4f8)
![testing mp4_20240608_205447 779](https://github.com/photopea/photopea/assets/172606139/d6a27bf4-c23f-42ad-ace4-4732f4f46fd2)
![testing mp4_20240608_205445 998](https://github.com/photopea/photopea/assets/172606139/4e3fe7d2-e420-4371-9748-e67cbaa62304)
![testing mp4_20240608_205446 115](https://github.com/photopea/photopea/assets/172606139/b3c8650c-ab9f-46ee-9e5e-c42e809aaf23)
![testing mp4_20240608_205446 249](https://github.com/photopea/photopea/assets/172606139/bdddfa19-7751-4acb-8c3f-a35e8044f772)
![testing mp4_20240608_205446 431](https://github.com/photopea/photopea/assets/172606139/9ebdbd27-dd91-435a-8c6e-d2cabc66cf29)
![testing mp4_20240608_205446 572](https://github.com/photopea/photopea/assets/172606139/90c70f5c-63bd-4507-a913-889189b1bb41)
![testing mp4_20240608_205446 697](https://github.com/photopea/photopea/assets/172606139/f81757ff-1353-4358-9de1-32d54e41dda1)
![testing mp4_20240608_205446 824](https://github.com/photopea/photopea/assets/172606139/998abe91-541e-4bb1-bd01-1353f2b4bda4)
![testing mp4_20240608_205444 915](https://github.com/photopea/photopea/assets/172606139/4932f43d-82c4-4934-a99c-d6c84ea385ee)
![testing mp4_20240608_205445 031](https://github.com/photopea/photopea/assets/172606139/23e22e02-9f44-46b6-93a3-f25c0b0cff0a)
![testing mp4_20240608_205445 152](https://github.com/photopea/photopea/assets/172606139/6a587a47-c920-4a87-a335-f092a5738daf)
![testing mp4_20240608_205445 274](https://github.com/photopea/photopea/assets/172606139/1c886def-0891-4d7d-9559-a96f89292fd8)
![testing mp4_20240608_205445 394](https://github.com/photopea/photopea/assets/172606139/8617eb44-732f-43e3-a728-bef77ffc20c4)
![testing mp4_20240608_205445 509](https://github.com/photopea/photopea/assets/172606139/2b08ce18-4579-4351-aa53-0062f17a36cf)
![testing mp4_20240608_205445 624](https://github.com/photopea/photopea/assets/172606139/5c988f9a-2d9e-4ace-843f-4df2e566d902)
![testing mp4_20240608_205445 744](https://github.com/photopea/photopea/assets/172606139/9bf91d21-b943-49d8-94da-742a3c595367)
![testing mp4_20240608_205445 870](https://github.com/photopea/photopea/assets/172606139/8e077658-23c2-4fba-92dd-5bc3ddaa5e0b)
![testing mp4_20240608_205444 005](https://github.com/photopea/photopea/assets/172606139/336e017a-cc90-45fe-8689-2926ae06fd2b)
![testing mp4_20240608_205444 124](https://github.com/photopea/photopea/assets/172606139/2f121de7-2e8f-4856-9247-c63447d70a84)
![testing mp4_20240608_205444 243](https://github.com/photopea/photopea/assets/172606139/eb1acfe7-39af-495e-86f9-5e91951e8c31)
![testing mp4_20240608_205444 377](https://github.com/photopea/photopea/assets/172606139/d8a16d05-28de-458f-bb06-9e5189840f79)
![testing mp4_20240608_205444 500](https://github.com/photopea/photopea/assets/172606139/fe56051d-904c-454b-a6b6-e97d58902f91)
![testing mp4_20240608_205444 668](https://github.com/photopea/photopea/assets/172606139/0abd86c6-ec11-4d96-a741-6b3eae196c84)
![testing mp4_20240608_205444 792](https://github.com/photopea/photopea/assets/172606139/5c7b5602-dc7a-4f63-9553-c48824c735b9)
![testing mp4_20240608_205442 909](https://github.com/photopea/photopea/assets/172606139/6e8d0482-199c-4d6a-a798-d57a79b83a79)
![testing mp4_20240608_205443 024](https://github.com/photopea/photopea/assets/172606139/e73811b5-8147-4464-8a40-ed321e5a48c4)
![testing mp4_20240608_205443 134](https://github.com/photopea/photopea/assets/172606139/d57966d8-8ab7-4fa7-8d03-8ed775818c52)
![testing mp4_20240608_205443 247](https://github.com/photopea/photopea/assets/172606139/2df88305-2737-4ad0-a4f8-c43ed0f3b637)
![testing mp4_20240608_205443 370](https://github.com/photopea/photopea/assets/172606139/38ea7c56-8b52-42e7-9c96-fcd93815d441)
![testing mp4_20240608_205443 506](https://github.com/photopea/photopea/assets/172606139/d5134bc9-5b9b-4945-8713-08c99306e13e)
![testing mp4_20240608_205443 633](https://github.com/photopea/photopea/assets/172606139/d94035c1-84a5-4e62-848a-93881aff1cb1)

**Comment by photopea** [comment]
Could you put them into a ZIP, so that I can see your original file names? Github changes the names of your files.

**Comment by OK-NUMBER** [comment]
[Uploading test zip.zip…]()

**Comment by photopea** [comment]
I can not download any ZIP :( Can you download a ZIP from this webpage?

**Comment by OK-NUMBER** [comment]
The ZIP file does not download for me either; I'll try again.
[test zip.zip](https://github.com/user-attachments/files/15844845/test.zip.zip)

**Comment by photopea** [comment]
So created a new, empty document in Photopea. I pressed File - Open and Place, I navigated to a folder with your images, and pressed Ctrl+A. Then, I pressed "Open".

![image (2)](https://github.com/photopea/photopea/assets/15955558/f4de0dce-041d-4712-a8df-972163fbef03)

It seems like the images are placed in a "correct order" - the first frame is a bottom-most layer, the last frame is a top layer. I can export them as MP4 (see below):


https://github.com/photopea/photopea/assets/15955558/fda2609c-8846-442f-9448-21e572dd7b43


Is anything different happening when you do the same steps? Note, that I only have Windows 10.

**Comment by OK-NUMBER** [comment]
If I do the same steps on Windows 11:

All images are in the correct order in files: 

![image](https://github.com/photopea/photopea/assets/172606139/ebee7aad-6c7d-4328-b4dc-15edba068b36)

Resulting GIF (Windows 11 doesn't seem to support Photopea MP4 for whatever reaason, or that might be the media player's fault. Regardless):

![New Project](https://github.com/photopea/photopea/assets/172606139/fa1c69a1-2724-4fd7-9b7a-fdc2f2e88f26)

**Comment by photopea** [comment]
I think the images in your screenshot are not in the correct order. The first file (frame) should be "testing.mp4_20240608_205445.274.png", which is not the first, neither the last file in your screenshot.

Photopea probably loads the files in the order in which they are displayed in your screenshot (the wrong order). Try to order them by name in your file explorer.

**Comment by photopea** [comment]
So I have figured it out. In your screenshot, images are orderd by Date (wrong order - I don't know who set the date of your images, and how they did it):

![by_date](https://github.com/photopea/photopea/assets/15955558/6e5bfe32-b09d-4ef1-b0bd-2298331159ab)

They need to be orderd by name (as their name corresponds to the time of a video, when each frame must be displayed):

![by_name](https://github.com/photopea/photopea/assets/15955558/0bbb53a8-e933-41ed-a263-75a0ef6ef7b4)

To change a file ordering method, you can probably do something similar to what I do in windows 10:

![sort_by](https://github.com/photopea/photopea/assets/15955558/1ac40c07-02cd-49f7-b404-33a7845525a9)

**Comment by OK-NUMBER** [comment]
Right, but even if I order by name in file explorer, the order that comes up when I attempt to open the files on Photopea isn't by name:

In file explorer: 
![image](https://github.com/photopea/photopea/assets/172606139/1097d6cd-298e-4a5d-b903-f4bc744e2efa)

Opening to Photopea:
![image](https://github.com/photopea/photopea/assets/172606139/5bd9e07a-c6ce-4fd4-bb3a-e7f749344189)

And there doesn't seem to be an option to order during upload:
![image](https://github.com/photopea/photopea/assets/172606139/8a08b4e4-b1b0-4238-a768-57263473ef64)

**Comment by photopea** [comment]
Your last two screenshots do not show "testing.mp4_20240608_205445.274.png" as a first file.

You should right-click an empty space and choose "Sort By". Do not right-click files.

**Comment by OK-NUMBER** [comment]
Oh great, it's working now. Thank you very much for the help, it was very appreciated (and apologies for the back and forth) :)

**Comment by photopea** [comment]
ok no problem.
