### ISSUE TITLE
Save the last configurations of tools

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6857]
It would be possible to have Photopea's account save the last state of tools settings?

For example: 

If i have Move tool with unchecked autoselect, it will be like that the next time i open Photopea?

Or having Fill bucket preselected, instead of gradient the next time i open Photopea?

Or having Ruler preselected, instead of eye dropper the next time i open Photopea?

Or have the Wand to have unchecked "contiguos" the next time i open Photopea?

And so on.

**Comment by photopea** [comment]
The tool options ("autoselect" for Move tool, "contiguous" for Magic Wand) should already be saved after closing Photopea. Is it not?

The active tool is not saved at the moment. I think it is better to always start Photopea with the Move tool.

**Comment by TheRadicalDreamer** [comment]
It is ok that always begin in the Move Tool, but yes, the tool options are not saved after closing.

**Comment by photopea** [comment]
In my case, they are saved. Please, try to disable all your browser extensions and try it again.

**Comment by TheRadicalDreamer** [comment]
Yes, it works.
But the selection of tools do not keep after close.
![image](https://github.com/photopea/photopea/assets/11801254/c11aa3fd-87be-4ec3-bb22-b618d08a49c7)

For example, i use a lot the ruler, so it will be great to have it by default selected when opening Photopea

**Comment by TheRadicalDreamer** [comment]
So, the only thing i would like to be in Photopea is that the selected tools in the left menu are the ones i left selected

**Comment by photopea** [comment]
fixed! :)

**Comment by TheRadicalDreamer** [comment]
I LOVE YOU!!!!!

![image](https://github.com/photopea/photopea/assets/11801254/ec335b00-dbee-4794-bf18-ad401796c761)

**Comment by photopea** [comment]
No, I love you! :D
