### ISSUE TITLE
Control key input being registered even when control key not pressed

### ISSUE THREAD

**Issue by lamenthell** [photopea/photopea#6858]
Your Operating System: Windows 10 Home 64bit
Your Web Browser: Firefox 127
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Paste an image using ctrl+V (May have to paste two)
3. Try resizing the image through transform controls, or clicking any other layer. It behaves as if you are holding down the ctrl key even if you aren't.
I tested to make sure it wasn't a keyboard problem, and it definitely isn't. It works fine being tested on a different browser.

**Comment by photopea** [comment]
It is a bug in Firefox 127. I can not fix it, only Mozilla can fix it :( 

I gave up reporting bugs to Firefox, as it takes them years to fix them. Try to report it yourself, or switch to Firefox 126. Or do not paste anything into Photopea in Firefox 127 (use File - Open instead).
