### ISSUE TITLE
Unable to use any keys after attempting to use ctrl+v

### ISSUE THREAD

**Issue by quinbo007** [photopea/photopea#6859]
Your Operating System: Windows 10
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Load in a .psd file
3. Press ctrl+v
![image](https://github.com/photopea/photopea/assets/172706532/24d4cd10-655d-4be8-b4a6-614bdb12a901)
After pressing ctrl+v, this message appears, doing nothing after being clicked on. Photopea then requests that I enable clipboard access. The issue persists upon pressing any key on my keyboard after attempting to copy and paste

**Comment by photopea** [comment]
This is a bug in Firefox 127. Please, switch back to Firefox 126, or use a different web browser, or do not paste anything into Photopea in Firefox 127.
