### ISSUE TITLE
Bold, italic, etc. not working?

### ISSUE THREAD

**Issue by blofstedt** [photopea/photopea#686]
![image](https://user-images.githubusercontent.com/38229215/39538079-d1c8f846-4df8-11e8-8a8a-8f8f15344b45.png)

When I click "bold" or "bold condensed" or anything else for that matter, and I have text highlighted, the font doesn't change to bold. Also, if I start a new line of text, clicking those same options still does nothing.

**Comment by photopea** [comment]
Sorry, it seems like your font (HelveticaNeue) is missing (the "-" in front of the font name). The used font that you see is not Helvetica Neue. You should open the Helvetica Neue first (File - Open - TTF file), and then change it, or choose another font.

I propose a fix: if the font is missing, the SubFamily list will not open.

**Comment by photopea** [comment]
Ok I fixed it - the SubFamily list will not open in such case.
