### ISSUE TITLE
Blur Filters from Filter Blur Gallery does not work after using Crop tool

### ISSUE THREAD

**Issue by Future-Dev-4** [photopea/photopea#6861]
Your Operating System: Windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

See attached Video to understand what are the steps to see the effect.

[Bug in Photopea.webm](https://github.com/photopea/photopea/assets/172914900/e3c06216-7fb0-43bf-8fba-fb96588832fc)

**Comment by photopea** [comment]
Hey, it should be fixed now.
