### ISSUE TITLE
photopea will not open my image

### ISSUE THREAD

**Issue by Rhondaread9969** [photopea/photopea#6862]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. .windows 10...
3. ..edge..
4. .this started last night, was working fine before i installed the photopea app, i have sine uninstalled it and it still isnt working...

**Comment by Rhondaread9969** [comment]
> 2\. windows 10...

**Comment by Rhondaread9969** [comment]
i need this to work again today

**Comment by photopea** [comment]
Hi, could you share your image with us, so that I can see it myself, to find out what is going on?

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by Rhondaread9969** [comment]
I finally got it to open, thankyou!!
________________________________

**Comment by Rhondaread9969** [comment]
I did get this to open eventually, thankyou

________________________________
