### ISSUE TITLE
How the hue saturation adjustment layer colorize feature works

### ISSUE THREAD

**Issue by RuffleSteels** [photopea/photopea#6863]
Hi,
I know this isn't much of an issue, but I am currently trying to make GLSL shaders, and I have been analyzing how Photoshop's hue saturation colorize adjustment layer actually works when tinting grayscale images, but it seems so random, is there any way you can reveal the logic behind this feature?

Thanks for your time
Ruffle.

**Comment by photopea** [comment]
Hi, sorry, I can not share these secrets of Photopea :(

**Comment by RuffleSteels** [comment]
It's fine, I just went through every HSL value and found out how the colorize affects it, and found the equation to this beutiful graph, and I have the secrets :)

![image](https://github.com/photopea/photopea/assets/77123399/6599c282-5a6a-4863-bdea-f05a83c3a03b)

**Comment by photopea** [comment]
You just need to convert a color from RGB to the HSV / HSL color space, modify the H or S or V, and then, convert it back. There are formulas all over the internet.

https://en.wikipedia.org/wiki/HSL_and_HSV

**Comment by RuffleSteels** [comment]
Yeah ik that, but that’s for the adjustment layer as a whole, it was the colorize checkbox that i had to do some weird math for, cuz both the brightness and saturation weirdly changed depending on the start grayscale pixel
