### ISSUE TITLE
Error during payment

### ISSUE THREAD

**Issue by mrsgit09** [photopea/photopea#6867]
Your Operating System: Windows 11
Your Web Browser: Edge

I decided to buy a subscription for Photopea so I went to Account --> selected a subscription and chose to pay by PayPal. My payment went through successfully and I got a PayPal receipt however, it then loaded a page that said "Corrupted cookies" and I haven't received a key or anything from Photopea in my email. How do I get the license I paid for?

**Comment by camoody1** [comment]
You don't actually get a key or anything like that when you subscribe. Photopea just uses your email address to allow you premium access. Since you're getting a "Corrupted Cookies" message, have you tried deleting your cookies for the Photopea website, then reloading the page and logging in, again? If you click on the little "lock" icon in your Edge address bar, then "cookies and site data", and then "Cookies".... you should see which cookies are currently in use. You can click on each cookie to highlight it and then choose to Remove it. After you remove them all, reload the Photopea site and see if it changes anything for you.

**Comment by mrsgit09** [comment]
Hi Camoody1 - thanks for your quick replay. :)  I tried your suggestion. I cleared browser history in Edge settings and I also deleted the cookies one by one following your steps. After closing and reopening Edge, it still does not work in the browser. Nor does it work in the desktop app. I also installed Chrome and tried it there. When I logged in, I tried using the Magic Replace feature and still get the message saying I need to upgrade or watch ads. See screenshot. I'm going to reboot my machine, but any other ideas after that?

![image](https://github.com/photopea/photopea/assets/11842956/3fcdbbff-ffe7-4554-9d08-0509f0c5b3c2)

**Comment by mrsgit09** [comment]
Restarting my machine did not help. When I try to log in it says: "Your browser deleted cookies. Try it again."

![image](https://github.com/photopea/photopea/assets/11842956/97739d4a-f0c1-4305-860c-347549d9e309)

I also tried it on an iPad that I've never opened Photopea on. It allows me to log in but does not recognize that I have a paid subscription so it doesn't seem to be a caching issue.

**Comment by camoody1** [comment]
Ivan is the developer. I'm sure he'll be quick to assist you when he wakes in the morning on Monday (eastern Europe). He'll need your email address, but don't drop it here. He'll ask you to send it to his Photopea address, I'm sure.

**Comment by photopea** [comment]
Your browser deleted cookies, so the payment was not stored into our database :/ I have inserted it manually, and it should work now. 

I recommend you to turn off some of your browser extensions, especiall if you dont know what they do.

**Comment by mrsgit09** [comment]
That fixed it. Thank you very much! :)

**Comment by nickietay86** [comment]
I am having issues with premium as well. I tried three times now to buy premium for my photopea account and each time it says I have to read the terms and conditions. I did that but there is nowhere on the terms to sign or select anything. It just keeps telling me I must agree to the terms and conditions first.

**Comment by photopea** [comment]
There is a checkbox at the bottom 

<img width="1305" height="703" alt="Image" src="https://github.com/user-attachments/assets/484e43b6-af19-4a5c-aab0-5d3f3ee522fd" />
