### ISSUE TITLE
Progen Flares 2 plugin not loading

### ISSUE THREAD

**Issue by yikuansun** [photopea/photopea#6868]
Your Operating System: Ubuntu 22.04.4 LTS
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: Yep

**This must be done to see the problem**
1. Go to www.photopea.com
2. Install the Progen Flares 2 plugin from the Plugins menu.

I am calling this a bug report since the plugin used to install perfectly fine. (My other plugins still seem to work perfectly fine). I have not changed the plugin whatsoever. Seems that the resource has somehow been stored incorrectly (or Photopea cannot fetch it for some other reason).

Here is the error message in the console:

![image](https://github.com/photopea/photopea/assets/38194363/c37c5952-ebd6-4e5d-9b11-b73aa2a75897)

Could you fix this by any chance? I'd rather not have to reupload the plugin files, since that will reset the installs count.

**Comment by yikuansun** [comment]
Seems that all plugins are actually broken. I think the only ones that were working were just cached somehow.

**Comment by photopea** [comment]
It seems to work fine in my case. Maybe your internet provider is blocking it? Can you open www.backblaze.com ?

**Comment by yikuansun** [comment]
Yeah, the file loaded on cellular data. I guess it's just my firewall (for some reason).

Thanks!
