### ISSUE TITLE
I try dragging an image into photpea, it then says loading and then never loads. I have tried everything in and it is still not working.

### ISSUE THREAD

**Issue by BigMike-55** [photopea/photopea#6869]
Your Operating System: windows 11 (Lenovo) 
Your Web Browser: Chrome 
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. open an image 
3. drag the image on the screen 
4. wait for it to never load

**Comment by photopea** [comment]
Are you opening images in a step 2 and a step 3? So you are opening two images?

**Comment by BigMike-55** [comment]
I meant to say open the image on your computer.

**Comment by photopea** [comment]
I have to close it because of lack of details.
