### ISSUE TITLE
Replace instead of remove

### ISSUE THREAD

**Issue by Subuday77** [photopea/photopea#6870]
Your Operating System: Windows 10 Version 10.0.19045.4529
Your Web Browser: Mozilla Fire Fox, Chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Upload picture
3. Select Magic Replace tool
4. Select object you want to remove (E.g., human)
5. Press Remove button

Expected result - object disappears 
Result - object replaced by another similar one.

**Comment by photopea** [comment]
Could you share a screenshot of an example?

**Comment by camoody1** [comment]
@photopea Would you be able to implement any of these 3rd party applications that use big-lama to remove objects from an image? It does a better job for my inpainting in Stable Diffusion than prompting your standard Dezgo model with "empty" or "nothing". Or perhaps you could ask Dezgo if they would be interested in implementing something like this for their API. It's a very fast and light process. 

https://github.com/advimman/lama?tab=readme-ov-file

**Comment by Subuday77** [comment]
> Could you share a screenshot of an example?


https://github.com/photopea/photopea/assets/55333225/4d53d5aa-122a-4c56-840f-fb3c3b697726

Sure.
In the provided example I'm trying to make a stool from the chair, by removing a chair back.
As you can see, it's not removed, but replaced by another one.
Hope this helps.

**Comment by photopea** [comment]
The selected area MUST CONTAIN THE WHOLE OBJECT, that you want to remove / replace. Photopea does not change the image outside your selection.

E.g. when you want to replace a hat, but you do not select the edge of a hat, Photopea will insert a new hat, because otherwise, the edge of a hat flying in the air would make no sense.

I roughly selected the back of a chair and entered "bar table wood" (what I want instead on that spot) and it worked.

![image](https://github.com/photopea/photopea/assets/15955558/ff21e791-9e33-40cd-9ecb-18cdbf8e7689)

**Comment by photopea** [comment]
here is my selection:
![image (1)](https://github.com/photopea/photopea/assets/15955558/618d6806-9bc3-4e32-91c9-7a56c5685a74)

**Comment by Subuday77** [comment]
I see. I need to operate with a Replace button in all cases, giving a valid prompt.
Bur Replace button is still _replacing_ the objects with similar one. So some bug do exists. I'll give an example (I also could provide a screen record, if needed)
So, I want to eliminate the bottle from the table.
I select it and push Remove button. Instead of current bottle appears another one.
I'm making Undo, returning the original bottle. The selection is still there and it's the same.
Now in the prompt field I'm writing **empty background** and I push Replace button. And bottle disappears.

I think, that the core of the bug - that Remove function does not receive an  **empty background** prompt as it should by default. IDK, which programming language do you use, but generally the bug will looks something like

`def remove_button_call(prompt=None):
     your code here`
instead of
`def remove_button_call(prompt='empty background'):
     your code here`

Try to check it out.
And thanks for help.

**Comment by photopea** [comment]
Clicking "Remove" is a shortcut for typing "empty background" and clicking "Replace". That is always the case.

If you enter the same prompt and call the feature several times, it gives different results, because there is always some randomness included. Often, if you dont get what you want, simply calling it again with the same prompt will give you what you want.

**Comment by photopea** [comment]
I can remove the "Remove" button, if you want. I am not sure if it is useful.

**Comment by Subuday77** [comment]
Also option.
Its existence confuses a bit.

ср, 26 июн. 2024 г., 14:51 Photopea ***@***.***>:

**Comment by photopea** [comment]
I have deleted the button.

I have noticed, that if you keep the prompt empty, it also often deletes the content.

![girl](https://github.com/photopea/photopea/assets/15955558/9127d8cb-91fa-4a57-9120-242e2aba0ffa)

**Comment by photopea** [comment]
There are people wanting it back: https://www.reddit.com/r/photopea/comments/1dqocrm/where_did_the_remove_button_go_in_magic_replace/

**Comment by cakemacaronsy** [comment]
I paid for magic fill but I couldn't find the button anymore and I am confused. I even use plug in for diffusion and still dont' know where it is please help

**Comment by photopea** [comment]
What button are you talking about? This is how the Magic Replace feature looks like right now:

![Image](https://github.com/user-attachments/assets/cd65877c-584c-46b0-aac1-6a2c1b612bda)
