### ISSUE TITLE
PDF - Linear gradient not exported correctly

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6871]
Your Operating System: Chromeos
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a shape and fill it with a gradient like the one below
![image](https://github.com/photopea/photopea/assets/11801254/868e86bd-7227-4973-bba4-399c02db347e)

3. Export it
4. Will look like this
![image](https://github.com/photopea/photopea/assets/11801254/de972e98-2e5d-43d0-bf0c-00a2d343618d)

**Comment by photopea** [comment]
Could you share your PSD file with us?

**Comment by TheRadicalDreamer** [comment]
[gradient.zip](https://github.com/user-attachments/files/15877840/gradient.zip)

Yes of course

**Comment by photopea** [comment]
I am very sorry, it should be fixed now.
