### ISSUE TITLE
Program shows Message "You have Pop up Blocker", but I do not have any

### ISSUE THREAD

**Issue by Azybin** [photopea/photopea#6873]
Your Operating System: Windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Download JPG file
3. Program shows Message "You have Pop up Blocker", but I do not have any.. Adds shown correctly
[Screenshot.docx](https://github.com/user-attachments/files/15890577/Screenshot.docx)

4. ....

**Comment by photopea** [comment]
Could you share a screenshot of what you see? I can not see any screenshot.

**Comment by bluep55** [comment]
On the right hand side of your screen, those are not ads, they are games placed there by the creator of Photopea. This means you must have an ad blocker blocking the ads. Click on the arrowed icon to see which extensions may be blocking the ads.
![screenshot-icon](https://github.com/photopea/photopea/assets/118609932/01bdf141-2dc3-4fb8-b91a-cba9113176ac)

**Comment by Azybin** [comment]
Sure!

**Comment by Azybin** [comment]
This is what extensions I only have
[image: image.png]
[image: image.png]

**Comment by photopea** [comment]
I do not see any images in your comments. 

Please, do not send emails to random Github addresses. Open www.github.com in your web browser and reply there.

**Comment by Azybin** [comment]
Second attempt. Please, see Attachment
![image (6)](https://github.com/photopea/photopea/assets/93623178/380624e4-2c2d-4a77-93c6-3582d10c6c01)
![image (5)](https://github.com/photopea/photopea/assets/93623178/ab1bccb6-d5a5-42d2-be55-1ccccb500b93)
.

**Comment by bluep55** [comment]
Could be your Malwarebytes Browser Guard blocking the ads.

**Comment by Azybin** [comment]
Yes, I've checked it out now

**Comment by photopea** [comment]
Could you share a screenshot of the message, that you see in Photopea, about a popup blocker?

**Comment by Azybin** [comment]
[image: image.png]

**Comment by photopea** [comment]
I can not see your image. Can you see your image in our discussion on Github?

**Comment by Azybin** [comment]
[Screenshot3.pdf](https://github.com/user-attachments/files/15906568/Screenshot3.pdf)

**Comment by Azybin** [comment]
I've sent it again to  Github as an attachment in my Bug

**Comment by photopea** [comment]
But your message is about ad blocking, it is not about pop ups? Why did you mention pop ups?

You probably do have an ad blocker. Please, read what Photopea tells you. There is a link to our article, which will tell you more.

**Comment by Azybin** [comment]
I've never mentioned Pop ups except Message about Adblocker, which is Pop
up itself.

**Comment by photopea** [comment]
You named your issue "Program shows Message "You have Pop up Blocker""

**Comment by Azybin** [comment]
It's probably my mistake - "Ad blocker" has been shown.

**Comment by photopea** [comment]
Did you try to follow the instructions? It will tell you how to find and turn off your ad blocker. Your screenshot shows that you have many extensions, which have your permission to rewrite the website content (so they can even block ads).

**Comment by Azybin** [comment]
No, I've already told you that it's Malwarebytes. It's OK now.

**Comment by photopea** [comment]
ok perfect.
