### ISSUE TITLE
PDF export without unicode characters

### ISSUE THREAD

**Issue by martinambrus** [photopea/photopea#6874]
Windows 11
Latest Firefox
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. create any document with a windows-1251 characters in it (such as ň, ť, č, ž...), use the default Deja-Vu Sans font
3. export into PDF
4. these characters don't appear in the PDF

**Comment by photopea** [comment]
I am aware of this. Please, use "Vectorize text", or "rasterize text", or "rasterize all" when exporting a PDF.
