### ISSUE TITLE
Problem exporting image at 300dpi

### ISSUE THREAD

**Issue by aaad-sss** [photopea/photopea#6875]
Hi, I'm having trouble exporting an image at 300dpi

My step is as follows:

1. New project
2. I configure in cm the size I need and the pixel/cm for 300 dpi
3. I place the image in the open project 
4. Saved as png and the result is 762dpi

If I check in > Image > Image Size it is ok at 300dpi and even so, redoing the export process the DPI is not correct

Previously the process was working

**Comment by photopea** [comment]
If you have 300 pixels in a centimeter, then, you will have 762 pixels in an inch. Because there are 2.54 centimeters in an inch.

DPI means dots (pixels) per inch. You are setting DPC (dots per centimeter). Please, use Dots per Inch to set Dots per Inch (DPI), do not use DPC to set DPI.
