### ISSUE TITLE
photopea promlem with mobile ( sorry if i made this many times idk what happened)

### ISSUE THREAD

**Issue by pppppppppppppcomits** [photopea/photopea#6878]
i am on ipad 
i use safari
The problem happens in the Incognito Mode, too the same thing happens 
 i work with photopea a lot and im on mobile but its rlly annoying when randomly, the screen will just freeze and at the top it says “ needs more ram “ i try to refresh and *all* my work is gone. i try to save my work but i need it to be saved in individual layers and when i try to do it on photo pea it doesn’t work its very annoying and i dont know what to do to fix it. i am using a lot of brushes in photopea around 12 could that be the cause?.

please respond

**Comment by photopea** [comment]
You are probably running into this issue: https://x.com/photopeacom/status/1754834651875545293 . Only apple can fix it. If you buy a $100 Android tablet, you will not have this issue.

**Comment by pppppppppppppcomits** [comment]
so can i contact apple abt it?

**Comment by photopea** [comment]
Yes, contact apple about it. I have reported it to them here: https://bugs.webkit.org/show_bug.cgi?id=268816

**Comment by camoody1** [comment]
@photopea It looks like you need to respond to the last comment made in that bug report, Ivan. The person clicked on your template link, but didn't know to click on the link within that template description, so they were never able to see your example.
