### ISSUE TITLE
Couple of bugs on mobile that is making it nearly unusable

### ISSUE THREAD

**Issue by Grabstertv** [photopea/photopea#6879]
Your Operating System: Android
Your Web Browser: Samsung Internet / Firefox
The problem happens in the Incognito Mode, too: Yep

I'm reporting multiple bugs in this issue but if individual issues need to he created, please let me know and I'll make sure to separate them. 

The mobile experience as of right now is nearly unusable no matter what I try.

## Bug 1: Out of bounds UI
**This must be done to see the problem**
1. Go to www.photopea.com on mobile in portrait mode
As seen in the pic below, the right side UI is out of bounds (you can check this if you go to window and enable any pane)
![Screenshot_20240620_105430_Samsung Internet](https://github.com/photopea/photopea/assets/49114212/08db2ec1-1a68-42ee-a267-3787c01c9d1c)
However there is a fix to it. If you enter full screen mode and then back out, it shows up again. Sometimes that does not work, so you have to rotate your device in landscape, enter full screen mode then rotate back to portrait and exit full screen.

## Bug 2: Sticky selection
**This must be done to see the problem**
1. Tap anywhere on the open document
2. Select lasso tool
3. Tap an area to start lasso selection
This will register the last finger tap on the document as the start of the lasso selection rather than the one you tapped last. The last tap will be registered as the 2nd tap. Here is a screen recording of this problem in action:
https://github.com/photopea/photopea/assets/49114212/855b151e-6d32-4c6b-894f-ddf3f04c5745
This issue is not only present for lasso tool but for brush as well where it is the most problematic during drawing.

**Comment by photopea** [comment]
I have opened www.photopea.com in Firefox on Android, and created a new file. This is what I see. What should I do to see the problem which you describe?
![Screenshot_20240620-091224](https://github.com/photopea/photopea/assets/15955558/e82dd2a6-ea5e-49d4-aded-702c82e468d9)

**Comment by Grabstertv** [comment]
The issue is hit or miss on Firefox but is consistent with Samsung internet (attached video below). You do not need to do anything to reproduce, you just load the website.


https://github.com/photopea/photopea/assets/49114212/282b6333-b96f-4fe9-ab5b-a9ad07a8661e

**Comment by photopea** [comment]
Ok, I do see this problem in Samsung Internet Browser. I think it is a bug in that browser. The browser has only 3.8 start on Google Play. So honestly, I dont know how to fix it, as I think Photopea is made according to web standards, and your browser is not following them.

**Comment by Grabstertv** [comment]
Samsung internet is built in on Samsung devices and while it has bad reviews, its a perfectly solid browser. I have not had any issue with any other website with it hence why I've stuck with using it. Fair enough though, if its a browser issue then i guess I'll wait for a fix.

I hope the other bug can be looked into as that is present on all browsers on mobile.

Appreciate your efforts!

**Comment by photopea** [comment]
Issue 2 - I can not reproduce it in any browser on Android :(

**Comment by sasoriza** [comment]
I have been using photopea for quite some time on my phone and never experienced issue 1 until yesterday. I am using Firefox and as stated it is hit or miss. However I am getting the buggy layout more often than the correct one, making it very hard to work with the page.
![Screenshot_20240625_090500_Firefox](https://github.com/photopea/photopea/assets/2168304/9d12d1c3-8652-41d7-805a-3fbb01499664)
![Screenshot_20240625_090520_Firefox](https://github.com/photopea/photopea/assets/2168304/f77a2d08-f670-4f86-99bc-f4094e4828fd)
![Screenshot_20240625_090528_Firefox](https://github.com/photopea/photopea/assets/2168304/1740618d-f4d5-44ea-88ce-1880e4d09613)
![Screenshot_20240625_090600_Firefox](https://github.com/photopea/photopea/assets/2168304/e8489bcc-f61a-4adc-810a-12e3e15841da)

**Comment by sasoriza** [comment]
Firefox has an option to move the address bar.
I switched to Chrome, page is displaying fine there.

**Comment by photopea** [comment]
I think it is a bug in Firefox. I recommend you to report it to Firefox.,
