### ISSUE TITLE
SVG Export

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6880]
Your Operating System: Chromeos
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new canvas and add a shape
3. Add a layer style drop shadow to that shape
4. Disable the layer
5. Export it to SVG

You'll see that the dropshadow it is being exported, even though you have disabled it.
![image](https://github.com/photopea/photopea/assets/11801254/9e0c559c-20a7-4cb8-9345-128caa6f6059)

**Comment by photopea** [comment]
fixed! :)
