### ISSUE TITLE
Guide Guy Bug.

### ISSUE THREAD

**Issue by bluep55** [photopea/photopea#6881]
In all 3 images I have placed a selection around the top layer (Tower Bridge). In number 1 example, I used the bottom 6 icons of Guide Guy to position the guides and they all synchronized with the selection boundary. In number 2 example, I used the Column Count option in both fields, and again the guides synchronised with the selection boundary. In number 3 example I used the Percent option, choosing 50%, but this time Guide Guy is way out and doesn't match the guides with the Selection. Is this a bug in Guide Guy.

EDIT:
Could you also check out the Column Count when used in conjunction with the Column Gap when using the Inches/Centimeters options. No matter what I try I always finish up with a solid block of guide. It works fine using the Pixel option.

![Guides A](https://github.com/photopea/photopea/assets/118609932/e293f752-fafd-400a-8700-1fdd39fe70c4)
![Guide 4](https://github.com/photopea/photopea/assets/118609932/eccde2b1-0d71-4590-991f-60af6eeb82f4)

**Comment by photopea** [comment]
it should be fixed now :)

**Comment by bluep55** [comment]
Perfect. Thank you 👌.
