### ISSUE TITLE
Photopea looks like this??? no clue why it was working fine today and now it's like this

### ISSUE THREAD

**Issue by myassholle** [photopea/photopea#6882]
Your Operating System: Windows
Your Web Browser: Google Chrome 
The problem happens in the Incognito Mode: Nope

I've deleted most of my extensions and tested w the remaining ones on incognito as well but that's not the problem. I've even updated  my browser but I don't know how and why this has happened. 

![Screenshot 2024-06-20 212435](https://github.com/photopea/photopea/assets/173406378/a8707445-b7e3-4df9-9b87-4aafb0317d32)

**Comment by camoody1** [comment]
Photopea is definitely working fine for me. You've almost certainly got an extension causing you problems. This is even MORE likely to be the case since it doesn't affect Incognito Mode.

**Comment by myassholle** [comment]
> Photopea is definitely working fine for me. You've almost certainly got an extension causing you problems. This is even MORE likely to be the case since it doesn't affect Incognito Mode.

Yeah it was, thank you so much for replying tho, but it was actually mcafee so I'm kinda worried about viruses and the sort

**Comment by camoody1** [comment]
McAfee really isn't necessary on today's Windows 10 and Windows 11 PCs. The built in virus protection does well enough. You could also get Malwarebytes if you feel like you want a little more. McAfee is pretty intrusive. Most PC experts would tell you the same thing. (Note: I am NOT an employee of Photopea. I'm just another user like yourself.)

**Comment by photopea** [comment]
If your browser extension is modifying Photopea in a certain, and you think it should not be modifying Photopea that way, you should report it to the creators of your extension, and ask them to fix it.
