### ISSUE TITLE
Please remove Smart Object audit for Magic Replace

### ISSUE THREAD

**Issue by lardofdorkness** [photopea/photopea#6883]
Since Magic Replace generates a new Magic layer now and does not modify the layer that is initially selected, it shouldn't require rasterization of a Smart Object layer if that's what is selected when the Magic Replace action is taken. I know it doesn't matter which layer is selected, but the audit for Smart Object layers still seems unnecessary in this context at this point. Thank you!

**Comment by photopea** [comment]
The Magic Layer allows you to switch between several versions of the content. If you paint into that layer, do you want to paint into one of these versions? Or how exactly do you want it to work?

**Comment by lardofdorkness** [comment]
Hi! No, the problem is that if the selected layer is a Smart Object when I initiate Magic Replace, I get a pop-up that tells me I must rasterize the Smart Object first. My point is that, since Magic Replace is not going to modify the Smart Object layer but instead create a new Magic layer, it shouldn't tell me I need to rasterize the Smart Object. It is an obsolete audit now that Magic Replace generates a new layer.

**Comment by photopea** [comment]
got it, it should be fixed now.

**Comment by lardofdorkness** [comment]
Great, thank you!
