### ISSUE TITLE
Delete / Remove has a glitch

### ISSUE THREAD

**Issue by Niki-Dla-Yaute** [photopea/photopea#6884]
Your Operating System: Windows 10
Your Web Browser: Google Chrome 
The problem happens in the Incognito Mode, too: No it's seems to work

**This must be done to see the problem**
1. Go to www.photopea.com on normal mode
2. Make a selection (I did with circle then reversed)
3. Try to delete with the keyboard and then edition menu 
4. It's not working

**Comment by photopea** [comment]
Could you try it again?

**Comment by NikoVentura** [comment]
Not the original person who created this but I'm having the same issue too.
Operating System: Windows 10
Web Browser: Brave Browser

However, the weird thing is I switched into Microsoft Edge and it worked fine just there. At first I thought maybe this was just an issue with Chromium based browsers but considering Edge is also chromium based, I have no idea what it could be causing this.

**Comment by photopea** [comment]
It should be fixed now.
