### ISSUE TITLE
Please, give us permissions to access your clipboard.

### ISSUE THREAD

**Issue by AkitaHanabi** [photopea/photopea#6885]
Your Operating System: Windows 11
Your Web Browser: Google Chrome Version: 126.0.6478.115 (64bit)
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Copy a picture piece
3. When I want to paste it. -->
4. Please, give us permissions to access your clipboard.

**Comment by photopea** [comment]
Could you try this? https://www.photopea.com/tuts/give-photopea-clipboard-permissions/

**Comment by photopea** [comment]
I have to close it because of lack of details.
