### ISSUE TITLE
Ferramenta Carimbo

### ISSUE THREAD

**Issue by lucyellesoares** [photopea/photopea#6886]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Abrir arquivo
3. Ferramenta Carimbo
4. Alt + Seleciona area
5. Clique e puxe (trava no movimento que deveria fazer)

**Comment by photopea** [comment]
I just tried it and it works fine in my case :( could you try it again? What kind of file do you open?

**Comment by photopea** [comment]
I have to close it because of lack of details.
