### ISSUE TITLE
drag and drop not working

### ISSUE THREAD

**Issue by shewillreign** [photopea/photopea#6887]
Your Operating System: windows
Your Web Browser: google chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. upload gifs / images
3. try to dragon image or gif onto another
4. will not let me drag it

**Comment by photopea** [comment]
I am confused. What is "upload gifs / images", and "dragon image onto another"? What exactly does it mean?

**Comment by photopea** [comment]
I have to close it because of lack of details.
