### ISSUE TITLE
files automatically open upon startup

### ISSUE THREAD

**Issue by halseam** [photopea/photopea#6889]
Your Operating System: ChomeOS
Your Web Browser: Chrome

every time i open photopea and try to open a new file, whether a blank one or something saved to my advice, it also tries to open seven gif files i made weeks ago. i dont have the psd files of the gifs saved to my device, nor the original mp4 files or final gifs anymore. they open every single time, and most times they freeze my device until i restart it manually, or they crash my device all together. i cant include photos or a screen recording as it would absolutely crash my device, sorry.

**Comment by photopea** [comment]
It happens because you use browser extensions, which break the functionality of Photopea. See https://www.photopea.com/tuts/photopea-opens-up-old-files/
