### ISSUE TITLE
Pinching with trackpad wrecks the page in some tools

### ISSUE THREAD

**Issue by Clorr** [photopea/photopea#6890]
Your Operating System: Mac OS 10.15
Your Web Browser: Firefox 127 (latest stable)
The problem happens in the Incognito Mode, too: Yes

1. Go to www.photopea.com
2. Load an image. If it is a raw, a first tool opens, in which if I pinch zoom on my trackpad, no problem appears
3. Do a selection
4. Click "refine selection" ("Ameliorer le contour" in french)
5. Pinch zoom in the popup, the full tool gets wrecked and i can't even unzoom

(I encountered the problem in some other cases, possibily also popups, but I did not wrote in which)

Thanks anyway for this amazing tool, it's mostly awesome !

**Comment by photopea** [comment]
What is "Pinch zoom in the popup"? What popup?

**Comment by Clorr** [comment]
Sorry if the naming is incorrect. Some tools, like raw import or the "refine selection" open in an interface that pops above the main interface and hides it. It usually has a cross in the upper right corner to close it and go back to the main interface.

 In the "refine selection" popup/tool, if I use the "pinch zoom" gesture (two fingers going apart from each other), the picture get zoomed, and the interface disappears. 

It also happened to me in some other place, but I can't remember which. In the "raw import" popup/tool, I don't have the problem, it works fine

**Comment by photopea** [comment]
I know what you are talking about!

I tried it in Firefox 127 on MacOS 14.4.1, I did a two-finger zoom on a trackpad, and it zoomed well.

Can you zoom with a "pinch" on a regular Photopea document, not in a "window tool"?

**Comment by Clorr** [comment]
In the main editor, I have no problem, it zooms/unzooms flawlessly.
However, in the "refine selection" window, zooming messes all the interface and unzooming does not comes back to normal.

Yesterday, I also had the problem while being the main editor, but i was processing a 32Mpx RAW file, and after a while, I got the same problem. But I think that was because the tab was taking almost 5Gb RAM and it started to be overloaded. But now, trying with a small file, I can confirm it works good in the main window, but there is a bug in the "refine selection" window tool

**Comment by Clorr** [comment]
Actually, I tried to unzoom more, but when I come back to what is certainly the minimum zoom value (1,67%), if I continue unzooming, the UI comes back. If I zoom again, when it gets over let's say 300%, the UI gets a mess again. 

It's hard to say exactly at which threshold it gets messed up because the pinch zoom goes very fast to dramatic values, like 3000%, 12000%, etc...

**Comment by photopea** [comment]
Could you share a screenshot of what you mean by "messed up"? Does it happen in other web borwsers, e.g. in Safari?

**Comment by Clorr** [comment]
Chrome 126.0.6478.114 => works fine
Safari 15.6.1 (15613.3.9.1.16, 15613) => no zooming at all

Firefox 127.0.1 (64 bits) => 
<img width="2560" alt="Capture d’écran 2024-06-24 à 17 15 06" src="https://github.com/photopea/photopea/assets/873943/fc2366f7-a1d1-400a-8358-0a758b1889c5">

But I also realise now that they are scroll bars and that when computer stops lagging, I can scroll till the edges, and I still have the UI but also zoomed. So it's maybe only that the zoom feature is applied on the full UI instead of the images. However, this does not looks like the built in browser zooming because, if I hit Cmd + 0, the zoom don't come back to normal like it does on normal pages
<img width="1283" alt="Capture d’écran 2024-06-24 à 17 18 19" src="https://github.com/photopea/photopea/assets/873943/f634c973-b40c-4271-9f2d-f7ebb77f667d">

**Comment by photopea** [comment]
I am confused about what is happening, because you have cropped out parts of your screen. Could you share your whole screen?

BTW. do you use any browser extensions in Firefox? Could you try to turn them off?

**Comment by Clorr** [comment]
The first screenshot is a full screenshot (I cropped only the UI of Firefox), only the second is partial just to show that the UI of photopea is also zoomed.

I can make new later if you want.

I don't have extensions, except Adblock which is deactivated since it is required to use photopea free.

**Comment by photopea** [comment]
Could you update your Mac OS? It could help. It does not happen on my Mac OS.

**Comment by Clorr** [comment]
Actually, I have a headless mac mini with Mac OS with sonoma, and it works there. So, ok, weird, but it looks that this is OS related... Sorry for spending your time.

**Comment by photopea** [comment]
ok
