### ISSUE TITLE
photphea gray screen

### ISSUE THREAD

**Issue by arjayethPSU** [photopea/photopea#6891]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
![photo_2024-06-22_08-50-01](https://github.com/photopea/photopea/assets/105921547/e8227c8d-0b56-4077-b5a8-4a5c0395207a)

**Comment by HuseyinKurklu** [comment]
same problem

**Comment by photopea** [comment]
Did you try it in the Incognito mode?

**Comment by photopea** [comment]
It should be fixed now.
