### ISSUE TITLE
The "Deselect" option isn't working right now.

### ISSUE THREAD

**Issue by NeoTPolaris** [photopea/photopea#6892]
When I hit "backspace", it usually deletes the selected part of the image that I'm trying to erase. But right now? Nothing. (and also, right now, when trying open "Photopea.com", the page often goes blank now)

**Comment by NeoTPolaris** [comment]
If this is helpful:
My computer brand: Mac Studio 2023
and I'm using Google Chrome: Version 126.0.6478.114 (Official Build) (arm64)

**Comment by photopea** [comment]
sorry, it should be fixed now.
