### ISSUE TITLE
Photopea opens to only grey.

### ISSUE THREAD

**Issue by King-Starx** [photopea/photopea#6893]
Your Operating System: Windows 11
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too: No
Using UBlock Origin

**This must be done to see the problem**
1. Go to www.photopea.com
2. Use select subject (magic wand).
3. Try using it again then pressing [ok] for watching an ad. Doesn't work.
4. Disable ad blocker.
5. Try again with the ad. Doesn't work again.
7. Refresh Tab.
8. See gray screen.

I don't if I was banned or something? Hope this is effective in helping you resolve this. Also I had like 7-8 tabs with YT playing the background and steam and file explorer open. No account as well. Thanks for any help.

**Comment by Daffodall** [comment]
Same with me

**Comment by photopea** [comment]
So if you open www.photopea.com, you see a gray screen? Did you try to open it in the Incognito mode?

**Comment by camoody1** [comment]
@photopea I wonder if a Ublock Origin update went out tonight that is messing with everyone? If so, that would be hilarious. Everyone has been saying that Photopea is down, but I've been using it fine all evening. 🤷🏽

**Comment by photopea** [comment]
I know! I have installed uBlock Origin two hours ago, but it still seemed to work fine.

**Comment by King-Starx** [comment]
Listen after restarting my computer it went back to normal. :) Sorry for the late response i don't use this site really. Yeah i tried it in incognito and it opened as it should have. (of that day fyi) Thanks for the help. It's amazing that such a great alt to PS exists! And is free! Other than Gimp. :3

**Comment by photopea** [comment]
Ok :)
