### ISSUE TITLE
Completely gray screen on Chrome.

### ISSUE THREAD

**Issue by jk0424** [photopea/photopea#6895]
It works fine on Microsoft edge, but it the screen for it is completely gray on chrome.

**Comment by photopea** [comment]
Did you try to open it in the Incognito mode?

**Comment by camoody1** [comment]
> It works fine on Microsoft edge, but it the screen for it is completely gray on chrome.

Are you using Ublock Origin, by chance?

**Comment by photopea** [comment]
It should be fixed now.
