### ISSUE TITLE
The Delete/Clear feature & shortcut (Backspace) has stopped working.

### ISSUE THREAD

**Issue by Synth-ix** [photopea/photopea#6898]
Your Operating System: Windows 10
Your Web Browser: Mozilla Firefox
The problem happens in the Incognito Mode, too: ✅

**This must be done to see the problem**
1. Go to www.photopea.com
2. Make any kind of selection of pixels on a layer
3. Press the Backspace key; and hover your mouse over to Edit in the top left corner of the main gui, go down to Clear (Delete), and click (neither options function)

Referring back to Issue #6884, both Niki-Dla-Yaute and NikoVentura had problems with this bug on Google Chrome & Brave Browser respectively, yet I'm having the same problems in & out of incognito on Firefox which ISN'T chromium-based. Any more insight that could be brought towards remedying this problem?

**Comment by photopea** [comment]
sorry, it should be fixed now.
