### ISSUE TITLE
When exporting images or gifs, they turns weird

### ISSUE THREAD

**Issue by anniebooboos** [photopea/photopea#6899]
Your Operating System: chromebook
Your Web Browser: google chrome
The problem happens in the Incognito Mode, too: no

Hey ! When you export images, or gifs, it turns them into this and i'm not sure if i have pressed something on my server of photopea on my google chrome as the problem didn't happen on incognito mode 
![Screenshot 2024-06-22 10](https://github.com/photopea/photopea/assets/140460488/706e4a34-c11e-4729-b2b0-297fee87eaa6)

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
You have set the Quality to zero, but in Incognito mode, you are not
setting it to zero.

**Comment by anniebooboos** [comment]
ahh thank you sm ! i'm so dumb lol

**Comment by photopea** [comment]
no problem :)
