### ISSUE TITLE
Google Drive open PSD not work

### ISSUE THREAD

**Issue by Studioartcz** [photopea/photopea#69]
Here is a bug:

![image](https://cloud.githubusercontent.com/assets/3184228/16799604/fc8a6c08-48f1-11e6-934b-66d1a390bcd9.png)

**Comment by Studioartcz** [comment]
Chrome blocks pop-up window with access rights ... It´s not bug but this can be problem for some users in future too.

**Comment by photopea** [comment]
I think it is a browser-specific issue. Every user must be able to configure his browser to work properly.
