### ISSUE TITLE
New domain legitimacy

### ISSUE THREAD

**Issue by realgooseman** [photopea/photopea#6900]
Is this website related to the main Photopea project or not ?

Link: https://www.photopea.fr

It looks and works the same as the original Photopea at: https://www.photopea.com

**Comment by photopea** [comment]
I am seeing it for the first time. Basically, anyone can insert Photopea into their webpage.

I dont see what is a point of it. They do not make money through ads, they just promote the brand name "Photopea".

**Comment by photopea** [comment]
I will close it now.
