### ISSUE TITLE
Scripting API doesn't support getting a layer's ID

### ISSUE THREAD

**Issue by syrupyy** [photopea/photopea#6901]
This probably also applies to various other scripting object types, but `app.activeDocument.activeLayer.id` is undefined and cannot be read. The ID property appears to be undocumented in Adobe's official API, but this quick sample script:
```app.activeDocument.activeLayer.textItem.contents = app.activeDocument.activeLayer.id;```
works fine in Photoshop...
![image](https://github.com/photopea/photopea/assets/77413084/168c64ef-892f-4179-b7dd-28ff564a71f2)
...but doesn't in Photopea, as the property isn't available there:
![image](https://github.com/photopea/photopea/assets/77413084/e3c1bbcc-cb91-4fd7-8158-8596d7e2f666)

Hopefully a quick change to make if doable. I apologize for making you look into weird undocumented Adobe APIs, but this would help greatly with the application I'm building around Photopea, which reads layer IDs with a PSD library on the backend and then reflects changes to those layers on the frontend. (Side note: said application would be much easier to make if there were an API around Image > Variables, but even Adobe doesn't seem to have one...)

**Comment by Pt-home** [comment]
Yes, the ID property undocumented. Why not app.activeDocument.activeLayer.name as variant?

**Comment by Pt-home** [comment]
May be this?
![image](https://github.com/photopea/photopea/assets/29394245/e6402bb9-3c23-4bda-b06b-857242179142)

**Comment by photopea** [comment]
Hey, it is fixed now. Your script should work now.
