### ISSUE TITLE
Scam Website Makes Me Lose All My work

### ISSUE THREAD

**Issue by spmrr** [photopea/photopea#6902]
Your Operating System: Windows 10
Your Web Browser: Microsoft edge
The problem happens in the Incognito Mode, too:  Instead of the scam website popping up, the canvas just goes white.

**This must be done to see the problem**
1. Go to www.photopea.com
2. Make a new project.
3. Wait a few minutes or so.
4. A prompt will show up asking if you want to lose your progress and leave the site.
5. You respond no, but it pops up again.
6. You respond no and the scam website pops up offering you an iphone for free.
7. You go cry because you just lost all your work, even if you press return your work doesn't show up and it brings you to the photopea homepage.

**Comment by photopea** [comment]
Hi, could you share a screenshot of what the ad looks like, so that we can ban it? Or what website does it lead to?

**Comment by photopea** [comment]
Also, can you make it happen while not using any browser extensions? There exist many browser extensions named "Google Docs" or "Facebook", which insert such ads into websites.

**Comment by spmrr** [comment]
It Worked!!! I removed all the suspicious browser extensions I had and I waited for the problem to show up for 3 hours and it didn't pop-up. 

Thank you so much!

**Comment by spmrr** [comment]
Also, the website name it used to lead to was called "fortunefinders.net".

**Comment by photopea** [comment]
Okay, perfect.
