### ISSUE TITLE
No other color than black

### ISSUE THREAD

**Issue by largowin** [photopea/photopea#6904]
Your Operating System: OS 14.4.1 (macBook Pro)
Your Web Browser: Chrome Version 125.0.6422.142
The problem happens in the Incognito Mode, too: ??
<img width="907" alt="Capture d’écran, le 2024-06-23 à 13 32 52" src="https://github.com/photopea/photopea/assets/36090529/34590901-2ef6-419d-95a7-4d7f4994b197">

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by bluep55** [comment]
Although you have a tick in Color Overlay, you haven't' opened the Color Overlay window. You need to click on the word 'Color Overlay' for that window to open, or in your case click on the word the word 'Incrustation couleur'.

**Comment by largowin** [comment]
Stupide error... Thx for your help!
