### ISSUE TITLE
KEEPS freezing

### ISSUE THREAD

**Issue by THERatEATS** [photopea/photopea#6905]
Your Operating System: MACBook
Your Web Browser: Chrome

i go to photopea and work on my project for a bit and then it 
just freezes and i have to open a new tab and start over

**Comment by photopea** [comment]
Can you make it freeze on purpose? If yes, how? If you can not describe it with words, could you record a short video of how you make it freeze?

**Comment by THERatEATS** [comment]
No I can’t freeze it, it just freezes by itself randomly and then no
matter how long I wait it never unfreezes, also I can’t record it because
it happens so randomly but, I can record the frozen screen. Also weird how
ever since I contacted photopea it hasn’t happened. That makes no sense.

**Comment by photopea** [comment]
If you do not save your work in Photopea properly, your work should reappear next time you open Photopea, as described here: https://www.photopea.com/tuts/photopea-opens-up-old-files/ . Did it reappear?

You could be using browser extensions, which make Photopea freeze, or which break the backup mechanism. That is why we accept only bug reports that happen in a browser with no extensions.

**Comment by photopea** [comment]
Open "about://extensions"  in Google Chrome and delete all your extensions. Let me know if it helped.

**Comment by photopea** [comment]
I have to close it because of lack of details.
