### ISSUE TITLE
no reply

### ISSUE THREAD

**Issue by Rosianef** [photopea/photopea#6907]
The website is unresponsive. I can't conclude anything else.
![image](https://github.com/photopea/photopea/assets/173752071/1490d821-61e8-428f-bcfb-6ddc153aa2e1)

**Comment by photopea** [comment]
What should I do to see this problem? Did you try to use Photopea without any browser extensions?

**Comment by Rosianef** [comment]
Yes, I've already tried without extensions. It happens out of nowhere

**Comment by photopea** [comment]
What should I do to see this problem?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
