### ISSUE TITLE
Photopea won't open any .eps file

### ISSUE THREAD

**Issue by karlajackson** [photopea/photopea#6908]
Hello,

I was trying to open some of my .eps files but the program won't open any of them. I tried on incognito mode, but it didn't work either. At the begining will be a message that says "loading" but then it will change to "Error. Please send your file to support@photopea.com and we will solve it". I thought it could be my file, but I tried with multiple ones and still have the same problem

Your Operating System: Windows 10 Pro
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open... Try to open an .eps file
3. Drag an open .eps file
4. Message previously described will appear

![image](https://github.com/photopea/photopea/assets/173753576/3d63309c-668c-4599-9ec3-a760fe88eb0f)

**Comment by photopea** [comment]
Please, send your file to support@photopea.com and we will solve it.

**Comment by karlajackson** [comment]
> Please, send your file to [support@photopea.com](mailto:support@photopea.com) and we will solve it.

But it's all of them. All of my .eps files won't open...

**Comment by photopea** [comment]
Hi, thanks for sending me your files!

It seems like it happened whenever you opened an EPS file that contained a pattern.

It should be fixed now.
