### ISSUE TITLE
About premium subscription bug

### ISSUE THREAD

**Issue by theclassu** [photopea/photopea#6909]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by theclassu** [comment]
sir i realy need help i recently purchased premim from photopia but i cannot acces it idk why please help me my email / theclassu@gmail.com
and my tag is classu/theclassu

**Comment by photopea** [comment]
Hi, what exactly you can not access? What happens when you open www.photopea.com ?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
