### ISSUE TITLE
Using ellipsis (…) to indicate dialog-opening menu-items

### ISSUE THREAD

**Issue by biziclop** [photopea/photopea#691]
It's would be a nice visual behavioral clue to have `…` appended to the end of menu items which open some dialog.

Photoshop examples:
`Filter/Blur/Average`: does it's thing immediately without asking anything, no ellipses
`Filter/Blur/Gaussian Blur…`: opens dialog

Currently the use of `…` is not systematic, I can see them in `Edit/Define New…/`, `Layer/Duplicate Into…` only.

**Comment by photopea** [comment]
Do you really think the information whether it opens a window or not, is so important? You use it for the first time only once, and then you already know what to expect. It would only make each text longer.

**Comment by biziclop** [comment]
Well, to me, it is. But don't believe me. :)

https://stackoverflow.com/questions/637683/when-to-use-ellipsis-after-menu-items/637708#637708  
https://ux.stackexchange.com/questions/9544/what-is-the-significance-of-the-three-dots-on-menus-and-buttons-and-how-to/9545#9545

**Comment by photopea** [comment]
Ok, I added ellipsis into Filters, Adjustments and some other items.
