### ISSUE TITLE
Photopea API with Python?

### ISSUE THREAD

**Issue by milqnomadu** [photopea/photopea#6910]
Just wondering if anyone could make this happen. I know Ivan doesn't use Python and therefore isn't keen on this, but as Python is one the main programming languages (especially for image manipulation) I think this is crucial.

**Comment by photopea** [comment]
You would have to create some web browser, which will run Photopea and will communicate with your Python program through some API. I dont think anyone here would be ready to help you, as we mostly have end users here.
