### ISSUE TITLE
Allowing Ads with Opera is not working?

### ISSUE THREAD

**Issue by BEX2294** [photopea/photopea#6911]
My Operating System: Windows 10
My Web Browser: Opera

**My Issue:**
I have a problem with the site telling me that I am blocking ads whenever I go to https://www.photopea.com I tried to allow ads but I am not sure if opera is truly blocking ads or not, but it shouldnt because I allowed ads on YouTube so it should would since I made an exception to photopea too. My main guess is that Opera is allowing ads on your website but your website thinks my browser is blocking ads. I am not entirely sure if this is true. I also do know that https://www.photopea.com/tuts/ does not say anything about Opera too.

![image_2024-06-25_105314254](https://github.com/photopea/photopea/assets/98864273/37a77de2-1459-4029-b124-037bbcd5ee9c)

**Comment by photopea** [comment]
I just opened www.photopea.com in Opera, and there is no message about ad blocking.

Did you try to use Photopea with no browser extensions?

**Comment by photopea** [comment]
Could you try to disable them all (in extension settings, not a button inside each extension)?

**Comment by BEX2294** [comment]
> Could you try to disable them all (in extension settings, not a button inside each extension)?

Ok I think I figured it out it is _AVG Online security_ I am not sure what it is in that extention I looked through the extention settings and the closest I can get is that it blocks website trackers and that type of stuff, but I dont see anything about blocking ads at all. I will continue to look, but I did turn off all the extentions then just tested out _AVG Online security_ by itslelf and that is the one blocking the ads.

**Comment by photopea** [comment]
ok perfect! :)
