### ISSUE TITLE
when i use the square select tool and delete 2 things, deleting things with the square tool doesn't work

### ISSUE THREAD

**Issue by MajinBear** [photopea/photopea#6913]
Your Operating System: Windows 11
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: no

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
I tried to do what you are saying, but it works fine in my case.

Could you record a short video as a proof that there is a problem?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
