### ISSUE TITLE
Layer Deleated itself

### ISSUE THREAD

**Issue by ickkckdbb990** [photopea/photopea#6914]
Your Operating System: Win 11
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: no

**The problem**
1. Go to www.photopea.com
2. i imported my psd
3. i create some layers and folders and drew a beautiful work of art
4. in a determinated moment, i was drawing in the top layer and the brush stop working, so i tried again and again and the layer deleated so i tried ctrl + Z and didnt work for these layer, but the other layers redo succefully. So, i lose a lot of my work :c

**Comment by photopea** [comment]
Please, tell us, what exactly should we do to see the same problem. You must be able to make it happen again, on purpose.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
