### ISSUE TITLE
Variables PDF Export

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6915]
Your Operating System: chromeos
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a canvas with a text
3. Upload a CSV with variables to change the content of the textbox
4. Export to PDF through variables.
5. Unzip the file and drag and drop all files to a new Photopea canvas
6. Each smart object will have a different size.

Here is a PSD for you to use:
[square variable.zip](https://github.com/user-attachments/files/15982954/square.variable.zip)

Here is a CSV for the variable content:
[text for variables.csv](https://github.com/user-attachments/files/15982959/text.for.variables.csv)

**Comment by TheRadicalDreamer** [comment]
![image](https://github.com/photopea/photopea/assets/11801254/bc29b7ac-0b6d-43b7-8048-61731d8d7808)
How it should like the bug

**Comment by photopea** [comment]
I have dragged these five PDF files into an empty PSD document in Photopea. They were placed on top of each other, at the same size. Could you do the same? 

[images (1).zip](https://github.com/user-attachments/files/15986630/images.1.zip)


![image (2)](https://github.com/photopea/photopea/assets/15955558/9a9d7cb3-0b40-46a7-b017-e2b34f08a7d8)

**Comment by TheRadicalDreamer** [comment]
Mmm, weird. Now it works correctly.

If i happen to repro again, i'll open this again.

**Comment by TheRadicalDreamer** [comment]
I managed to repro again.

It is when i select Letter size of the project. Check this out:
[Screen recording 2024-07-23 14.53.12.webm](https://github.com/user-attachments/assets/8d0c88f1-6269-4a46-b0a9-8ea2fd8f409b)

**Comment by photopea** [comment]
I really need to reproduce it myself somehow :(

Could you share your PDF files, which you are inserting into Photopea? That would really help me reproduce it.

**Comment by TheRadicalDreamer** [comment]
[images (6).zip](https://github.com/user-attachments/files/16354764/images.6.zip)
Here

**Comment by photopea** [comment]
thanks, it should be fixed now.
