### ISSUE TITLE
Where is "select subject..." and "remove background" feature?

### ISSUE THREAD

**Issue by rupkatAI** [photopea/photopea#6916]
Your Operating System: Windows 10
Your Web Browser: Edge
The problem happens in the Incognito Mode, too: not checked

What happened to features mentioned in title? 
Now i see something new called "make work path" or "save selection" when right click on the selection using rectangle (M)

**Comment by photopea** [comment]
You should press "Select" at the top, and choose "Remove BG" or "Subject". There is no need to right-click anything.

**Comment by rupkatAI** [comment]
Yea i see but why this option dissapears from dropdown menu? That change makes my workflow a little uncomfortable now

**Comment by photopea** [comment]
We decided to have different items in a dropdown menu. Pressing Select at the top is equally fast, and it works no matter what tool you are using.

**Comment by rupkatAI** [comment]
I would not agree with that equally fast comparsion. Maybe if there was a shortuct, yea but if you have bigger monitor, there's a huge gap between workspace and top menu, especially when you zoom out your project. I never used these different options before. You have to move your cursor for longer distance instead of just right click whenever i want on the image and barely move cursor. I can even measure time for you and prove it.
