### ISSUE TITLE
Show guides shortcut CTRL+; not working on Slovak(SLK) keyboard.

### ISSUE THREAD

**Issue by xkovacikm** [photopea/photopea#6917]
Your Operating System: Windows 11
Your Web Browser: Google Chrome

Hi, Show guides shortcut CTRL+; not working on Slovak(SLK) keyboard.

Hint: On SLK keyboard, the ; character is located between Esc and Tab keys.

Thanks and have a nice day! ;)

**Comment by photopea** [comment]
it should be fixed now.
