### ISSUE TITLE
arabic problem

### ISSUE THREAD

**Issue by mhmdmhmwdanwr10** [photopea/photopea#6918]
Peace be upon you. I want to import a PDF file, but the Arabic writing is the opposite. I hope you solve this problem automatically, because writing the content again in a manual format costs a lot of time. 

I would like you to clarify if there is a way to import the PDF file in Layer format from the Photoshop application itself. 

If the problem cannot be solved

no layer at photoshop but arabic is right 
![Screenshot (14)](https://github.com/photopea/photopea/assets/174009262/5f44ae85-6316-4ec9-bd68-68519fa99e64)
![Screenshot (15)](https://github.com/photopea/photopea/assets/174009262/3890b5de-6a58-4529-b61f-ca1c2f7fe9fd)
![Screenshot (16)](https://github.com/photopea/photopea/assets/174009262/8ec2f73b-bb04-4621-bcd6-be3db431012b)
![Screenshot (17)](https://github.com/photopea/photopea/assets/174009262/c2f795c7-9fdd-40c2-a943-d33ec267484c)
![Screenshot (18)](https://github.com/photopea/photopea/assets/174009262/bc12acb4-7740-4f7d-9589-402bd91a0157)
![Screenshot (19)](https://github.com/photopea/photopea/assets/174009262/2a75a497-49db-4c29-bc12-f8223f8348eb)
[Uploading غلاف كيمياء.pdf…]()

**Comment by photopea** [comment]
You have only one layer in Photoshop. Is it ok for you? Would you like Photopea to open your PDF with just a single layer?

**Comment by mhmdmhmwdanwr10** [comment]
No, brother, I want the opposite. I want to open the PDF in Photoshop in
the Arabic language, but the Arabic language is reversed, and if there is
no solution, I want to open the PDF in Photoshop in the form of several
layers.

**Comment by mhmdmhmwdanwr10** [comment]
I mean, open it in Arabic in Photopia or as multiple layers in Photoshop

**Comment by photopea** [comment]
Could you share your PDF with us? Please, do not send emails to random email addresses. Open www.github.com in your web browser and reply there.

**Comment by mhmdmhmwdanwr10** [comment]
[
[Uploading غلاف كيمياء.pdf…]()
](url)

**Comment by mhmdmhmwdanwr10** [comment]
[غلاف كيمياء.pdf](https://github.com/user-attachments/files/16036350/default.pdf)

**Comment by photopea** [comment]
I can not download it from your link. Can you download it?

**Comment by mhmdmhmwdanwr10** [comment]
[غلاف كيمياء.pdf](https://github.com/user-attachments/files/16039676/default.pdf)

**Comment by mhmdmhmwdanwr10** [comment]
i  can download it

**Comment by mhmdmhmwdanwr10** [comment]
the link of pdf is work

**Comment by mhmdmhmwdanwr10** [comment]
> [غلاف كيمياء.pdf](https://github.com/user-attachments/files/16039676/default.pdf)

here

**Comment by photopea** [comment]
Sorry, it would be very hard for us to make it work. PDF files were not meant to be edited any further. We can recover the original text to a certain degree, but only for left-to-right languages.

**Comment by mhmdmhmwdanwr10** [comment]
Ok, thanks anyway.
Alternatively, can you teach me how to import the file into Photoshop in
multiple layer formats?

**Comment by mhmdmhmwdanwr10** [comment]
Like as photopea there are several layers
But i can't do this at Photoshop
If you teach me that i will be grateful

You do it in photopea

**Comment by photopea** [comment]
I think Adobe Photoshop can not load PDF files as separate layers. But you should ask Adobe about it.

**Comment by mhmdmhmwdanwr10** [comment]
Ok thanks 👍 i will Distract myself
