### ISSUE TITLE
Not enough RAM .sketch file (-1153MB)

### ISSUE THREAD

**Issue by aladingaljic** [photopea/photopea#692]
Hey,

When trying to attach a .sketch file to export in .psd, I get the error message that there is not enough ram. What to do?

Thanks!

**Comment by photopea** [comment]
Hi, you should get a device with more RAM, or make a Sketch file smaller (e.g. split the content into several Sketch files in Sketch App).

We plan to make Photopea work even with large Sketch files, but it is quite hard.

**Comment by aladingaljic** [comment]
Wow, thanks for the quick answer.

So basically I tried with a 16GB RAM Macbook Pro instead of mine 8GB and still didn't work. Also, when splitting up content the amount of "-amount of RAM" gets higher. That seems strange?

The original Sketch file is 206MB, while another at 175MB worked without problems..

Any idea?

**Comment by photopea** [comment]
Sketch files are processed in "patches" - 10 MB, 100 MB, 20 MB .... so the size, that you see in the message, is the size needed for the last patch, not the total size.

Photopea is a raster editor, and PSD is a raster format. That is why Sketch files become so large, because they need to be converted to pixels for rendering.

**Comment by aladingaljic** [comment]
I understand. Thanks! I solved it through minimizing the file to 100MB and it worked.

As I have you here atm, is there anything special I should be aware of and check in the PSD file that could be messed up by converting? Or are most issues solved?

**Comment by photopea** [comment]
There are no issues that I am aware of. You just open a Sketch and get a PSD. If you find any bug or anything, let us know.
