### ISSUE TITLE
Empty curves layer adjustment in Photoshop breaks Photopea

### ISSUE THREAD

**Issue by tim35050** [photopea/photopea#6920]
Your Operating System: macOS Sonoma 14.4.1
Your Web Browser: Chrome Version 126.0.6478.126
The problem happens in the Incognito Mode, too: YES

**This must be done to see the problem**
1. Go to www.photopea.com
2. Import the attached file empty_curves_bug.psd. The file was created in Photoshop. It has a smart object layer containing a rectangle shape, and I applied a default curves layer adjustment to the smart object.
[empty_curves_bug.psd.zip](https://github.com/user-attachments/files/16017949/empty_curves_bug.psd.zip)
3. (first bug) Open the curves adjustment layer, you will see that it fails to load the chart. It should show a default curves chart (same as what you see when clicking "reset").
4. (second bug) Try to resize the smart object with transform controls. Once you click the checkmark to finalize the transformation, Photopea will freeze.

**Comment by photopea** [comment]
It is fixed now, thanks a lot! :)
