### ISSUE TITLE
need help with variables and database

### ISSUE THREAD

**Issue by cmsalomon** [photopea/photopea#6921]
hello, i am trying to **automate** my website appearing on each of these squares and an Order # appearing in each square as well.  I tried applying same rules as used in Photoshop but did not work or I am not skilled enough in this area.  The Blanks will be photos that customers will be sending so i will be manually inserting those pictures.

Since i could not figure out how to use the database and variables,  I tried MANUALLY adding my website in the TEXT Layer so it appears on each square, and **no text** was appearing on each square.

Can you help?

Tx
Ceci

[PHOTOSHOPSquareButtonMagnet.zip](https://github.com/user-attachments/files/16019988/PHOTOSHOPSquareButtonMagnet.zip)
[PNGSquareButtonMagnet.zip](https://github.com/user-attachments/files/16019990/PNGSquareButtonMagnet.zip)

**Comment by photopea** [comment]
This is not a place to ask others to teach you how to use Photopea. Please, ask here: https://www.reddit.com/r/photopea/
