### ISSUE TITLE
[Bug] Changing DPI of SmartObject document with `Image Size...` is inconsistent with Photoshop

### ISSUE THREAD

**Issue by lucadalli** [photopea/photopea#6923]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

In Photoshop it's possible to resize a SmartObject document but keep the same SmartObject size in the main document by changing the SmartObject document Resolution.
![image](https://github.com/photopea/photopea/assets/39853447/3e47d789-db39-4cc2-8dcb-ad611e2decbc)

Photopea does not exhibit the same behavior. When SmartObject document DPI is changed, the SmartObject in the main document is resized.

Here are images comparing the two results:
**Original PSD:**
![dpi-original](https://github.com/photopea/photopea/assets/39853447/e59da045-1469-41df-a0ba-5d13ae12a6e0)
**5 DPI SmartObject in Photoshop (correct):**
![dpi-change-photoshop](https://github.com/photopea/photopea/assets/39853447/d6737e8d-b592-48d6-84a8-62714808af32)
**5 DPI SmartObject in Photopea:**
![dpi-change-photopea](https://github.com/photopea/photopea/assets/39853447/6c73c480-abd9-4be1-89e4-6209af684a16)

Attached is a video showing the different behaviors.

https://github.com/photopea/photopea/assets/39853447/9f043966-0d40-46e4-b773-59eb82c5608f

**Comment by photopea** [comment]
it should be fixed now.
