### ISSUE TITLE
http invalid token error

### ISSUE THREAD

**Issue by Amyr-Askari** [photopea/photopea#6924]
i log into my account, and when i want to go to peadrive, i get this message repeatedly saying "http error: 401: invalid token......q:checkauth

**Comment by photopea** [comment]
could you tell me the email address that you use in Photopea? You can see it by clicking "Account" at the top.

**Comment by Amyr-Askari** [comment]
> could you tell me the email address that you use in Photopea? You can see it by clicking "Account" at the top.

sure. amirhaskr@gmail.com

**Comment by photopea** [comment]
it should be fixed, could you close Photopea and open it again?

**Comment by Amyr-Askari** [comment]
> it should be fixed, could you close Photopea and open it again?

thank youuu. its fixed. you're amazing

**Comment by photopea** [comment]
you are welcome.
