### ISSUE TITLE
Message "Change consent" 

### ISSUE THREAD

**Issue by Mahikorana** [photopea/photopea#6927]
Your Operating System: Chromebook
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: non

Au lancement de Photopea, un message apparaît me demandant de modifier mon consentement, mais la pop'up permettant de le faire n'apparaît pas (sauf en navigation privée) : 

![Screenshot 2024-06-30 17 11 36](https://github.com/photopea/photopea/assets/174262404/7d0796d7-b226-4149-ad0d-4b617be13db4)

**Comment by photopea** [comment]
Your browser extensions are breaking Photopea. Try to disable those which break Photopea. If you dont know which of your extensions break Photopea, try to disable all of them.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
