### ISSUE TITLE
Ad blocking detect without with adguard disabled

### ISSUE THREAD

**Issue by andreresende** [photopea/photopea#6928]
<img width="1457" alt="Screenshot 2024-07-01 at 01 14 46" src="https://github.com/photopea/photopea/assets/600943/e8b0ba4b-772f-4cd9-b609-82d1a7a8b558">

**Comment by photopea** [comment]
I am 99% certain you are using a browser extension, which blocks ads.

Did you ever try to use Photopea in the Incognito mode, or with all your extensins disabled?

**Comment by Fally1221** [comment]
I don't have an ad blocker. Just in case, I disabled all the extensions anyway, even if they have nothing to do with it. I have incognito mode on and photopea still tells me that it is blocking ads. I don't know what to do anymore.

**Comment by photopea** [comment]
Can you open this? https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js

**Comment by photopea** [comment]
I have to close it because of lack of details :(
