### ISSUE TITLE
Magnetic Lasso not working

### ISSUE THREAD

**Issue by littleewok51** [photopea/photopea#6929]
Your Operating System: 64 bit Windows 10
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

When I try to use magnetic lasso the very first small box appears with my first mouse click. But the tracing line doesn't appear. If I try clicking again, or using a different tool then going back to the magnetic lasso it won't even show the initial small box. It just won't do anything

**This must be done to see the problem**
1. Go to www.photopea.com
2. .... select magnetic lasso
3. .... try to use it

**Comment by photopea** [comment]
I just tried to use the Magnetic Lasso and everything seems to work fine.

I think your problem happens because you use a specific image. Could you share your image with us? Otherwise, it sounds like you are claiming it happens with any image, which is obviously not true.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
