### ISSUE TITLE
"Unexpected zip file" message when opening sketch file

### ISSUE THREAD

**Issue by 669966** [photopea/photopea#693]
Hi,

I'm trying to open a sketch file with some icons.
But the program gives the message "unexpected ZIP file" and then "loading". Even after a long wait the file is not opened.
I think it could be a bug since the file has a .sketch extension. 

<img width="1185" alt="screen shot 2018-05-03 at 12 06 41" src="https://user-images.githubusercontent.com/38941571/39571072-997dc5c0-4eca-11e8-8ca1-6659d563d55b.png">

**Comment by photopea** [comment]
Hi, could you please send us your file to support@photopea.com ?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
