### ISSUE TITLE
Pencil sizes below 4 aren't drawing.

### ISSUE THREAD

**Issue by aZealot** [photopea/photopea#6930]
Your Operating System: MacOS
Your Web Browser: Firefox (also tested Safari and Chrome and the same thing happens)
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Set pencil size to 3, 2, or 1.
3. Try drawing.
4. Observe that the pencil tool is not leaving a mark, even though it says in History that you used the pencil tool.

Here's a video showing what I'm talking about [https://www.youtube.com/watch?v=z3uPdVScpxk](https://www.youtube.com/watch?v=z3uPdVScpxk)

**Comment by photopea** [comment]
I just tried to do what you say, but it works fine.

In your video, you are not doing your steps 1 - 2 - 3 - 4. Could you record a video with doing your steps, as a proof that your steps really lead to a problem?

**Comment by aZealot** [comment]
Oh. Huh. The error doesn't happen when I do a new file. Maybe there's something weird about the specific file I'm working on, because it happens regardless if I close the tab and reload the project. I'll try to see if I can get it resolved on my end. Thanks for your help.

**Comment by aZealot** [comment]
Idk what the error was but I just dragged all my layers into a new project and it went away so whatever.
