### ISSUE TITLE
Saving Actions not possible when "Remove BG" action is included in Action

### ISSUE THREAD

**Issue by tangiblewaves** [photopea/photopea#6931]
Your Operating System: WIN10
Your Web Browser: Chrome, Opera; also installed version - same behaviour
The problem happens in the Incognito Mode, too: YES

**This must be done to see the problem**
1. Go to www.photopea.com
2. Load a JPG picture
3. Record Actions, including a Background removal ("Select" - "Remove BG")
4. Click Save in Actions 
Now, no file select dialog is shown, Action set is not saved.

Saving without having a "remove background" recorded works fine!

**Comment by Pt-home** [comment]
https://github.com/photopea/photopea/issues/5650

**Comment by photopea** [comment]
It should be fixed now. But because of https://github.com/photopea/photopea/issues/5650, "Remove BG" is recorded just as adding an empty raster mask to a layer.

**Comment by tangiblewaves** [comment]
Great; thanks a lot! Will try it very soon!



------ Originalnachricht ------
Von "Photopea" ***@***.***>
An "photopea/photopea" ***@***.***>
Cc "tangiblewaves" ***@***.***>; "Author" 
***@***.***>
Datum 07.07.2024 11:50:09
Betreff Re: [photopea/photopea] Saving Actions not possible when "Remove 
BG" action is included in Action (Issue #6931)
