### ISSUE TITLE
Feature Suggestion: Multi-Line Plugin Description

### ISSUE THREAD

**Issue by yikuansun** [photopea/photopea#6934]
Hi, I was just wondering if we could get multi-line plugin descriptions.

Currently, I can type a multi-line description, but the line breaks are not rendered. Ex.:

![Screenshot from 2024-07-03 11-27-02](https://github.com/photopea/photopea/assets/38194363/140cbb77-510e-4f5f-a3ea-bccd05e344b5)
![Screenshot from 2024-07-03 11-26-44](https://github.com/photopea/photopea/assets/38194363/17e0acbd-8e32-4453-8bc2-62a030d56006)

`white-space: pre-line;` on the `<p>` fixes this easily.

**Comment by photopea** [comment]
ok, I have added this bit of CSS.

**Comment by yikuansun** [comment]
Awesome, thanks!
