### ISSUE TITLE
Cannot save PSD files to device

### ISSUE THREAD

**Issue by Tikalian-coconut** [photopea/photopea#6937]
Your Operating System: Windows 10
Your Web Browser: Avast Secure Browser
The problem happens in the Incognito Mode, too: never tried, i guess it'll do same too

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open a psd file
3. Edit 
4. Save to PSD
5. The file is wiped out of all data and appears as 0B in file manager 
![image](https://github.com/photopea/photopea/assets/77456442/ab0911b7-975b-467c-be85-388a1ea7895d)
6. stuck on "saving..." forever
![image](https://github.com/photopea/photopea/assets/77456442/944fcccf-9507-4a21-a5b6-cd7b1ba91f7c)

**Comment by Tikalian-coconut** [comment]
It also does it with saving to storage like drive or peadrive, it refuses to save :/

**Comment by photopea** [comment]
A problem like this is often caused by browser extensions.

Please, tell us if it happens when you do not use any borwser extensions.

**Comment by Tikalian-coconut** [comment]
I'll try, however i will loose all my work in process that's the only downside since the file is completely corrupted now

**Comment by Tikalian-coconut** [comment]
Even with all extensions turned off it still causes problems, psd files that save end up completely wiped out of all data, it says 0 bytes
and refuses to save PSD files in anything, be it drive, peadrive or the computer

**Comment by photopea** [comment]
Could you show me some proof? Open www.photopea.com in the Incognito mode, open a PSD, and save it to your computer, and show me that it is 0 Bytes.

**Comment by Tikalian-coconut** [comment]
![image](https://github.com/photopea/photopea/assets/77456442/f55635c0-765e-443f-8d11-5342c198985e)
I have saved this picture as test for PSD, reloaded it, and it said:
![image](https://github.com/photopea/photopea/assets/77456442/49b1c32b-5f63-4bd3-aea1-a81a3ac9687e)
then it just froze with the "Saving..." on top, in fact now there's two and it cannot be removed unless refreshing the page which makes me loose the file and work done.

**Comment by photopea** [comment]
This could be a bug in the Avast Secure Browser. Letting a website create a file in your computer could be considered "insecure" by your browser.

Have you ever been able to save a PSD? (in Photopea running in this browser?). It could be a bug in your browser.

**Comment by Tikalian-coconut** [comment]
Until few months ago i was able to save PSD files
but one day it just stopped working and now photopea is really buggy 
i've not really tried using it with firefox or another browser yet

**Comment by Tikalian-coconut** [comment]
It does work on Firefox
i guess the issue is fixed, i'll use it on firefox from now on
thanks for help!

**Comment by photopea** [comment]
It should work in Chrome, Edge, Opera, Safari, and every other normal browser.

I recommend you to report this problem to the creators of Avast Secure Browser.
