### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by arjayethPSU** [photopea/photopea#6938]
![image](https://github.com/photopea/photopea/assets/105921547/1bd0db79-4b94-41c2-88b0-ba92e83e58e4)

**Comment by photopea** [comment]
Could you try to open www.photopea.com in the incognito mode of a web browser?

**Comment by jaygodwar** [comment]
![IMG_20240704_205750.jpg](https://github.com/photopea/photopea/assets/113362402/8325abc5-6c64-4567-bd5c-b8888063ab6d)

this is mobile same on pc or laptop sir inconigto mode

**Comment by photopea** [comment]
Could you show me a screenshot of what you see on a laptop?

**Comment by arjayethPSU** [comment]
already fix sir i can use it now thankyou for reply
