### ISSUE TITLE
Share PSD

### ISSUE THREAD

**Issue by vilanova000** [photopea/photopea#6939]
Hi. When I try to share a project as a PSD to get a link, it keeps "publishing" but it doesn't publish anything

![Captura de pantalla 2024-07-04 164657](https://github.com/photopea/photopea/assets/174725797/d026a8d6-8102-4057-bdcc-60347ed4468b)

**Comment by photopea** [comment]
That is stragne. Can you open published projects like [photopea.com#t3ZbOmi07](https://www.photopea.com/#t3ZbOmi07) ?

**Comment by vilanova000** [comment]
Yes, I can. Can I send you the .psd and you send me the link? haha
________________________________
De: Photopea ***@***.***>
Enviado: jueves, 4 de julio de 2024 17:01
Para: photopea/photopea ***@***.***>
Cc: Albert Vilanova Farres ***@***.***>; Author ***@***.***>
Asunto: Re: [photopea/photopea] Share PSD (Issue #6939)

No suele recibir correos electrónicos de ***@***.*** Por qué esto es importante<https://aka.ms/LearnAboutSenderIdentification>

AVISO: Este correo electrónico proviene de un remitente externo a Grupo Godó. No haga clic en enlaces ni abra archivos adjuntos a menos que reconozca al remitente y sepa que el contenido es seguro. Si sospecha del mensaje, utilice el botón de notificación de phishing para reportarlo.


That is stragne. Can you open published projects like photopea.com#t3ZbOmi07<https://www.photopea.com/#t3ZbOmi07> ?

**Comment by photopea** [comment]
Did you try it in the incognito mode?

**Comment by vilanova000** [comment]
Yes, same problem.
________________________________
De: Photopea ***@***.***>
Enviado: jueves, 4 de julio de 2024 17:17
Para: photopea/photopea ***@***.***>
Cc: Albert Vilanova Farres ***@***.***>; Author ***@***.***>
Asunto: Re: [photopea/photopea] Share PSD (Issue #6939)

No suele recibir correos electrónicos de ***@***.*** Por qué esto es importante<https://aka.ms/LearnAboutSenderIdentification>

AVISO: Este correo electrónico proviene de un remitente externo a Grupo Godó. No haga clic en enlaces ni abra archivos adjuntos a menos que reconozca al remitente y sepa que el contenido es seguro. Si sospecha del mensaje, utilice el botón de notificación de phishing para reportarlo.


Did you try it in the incognito mode?

**Comment by photopea** [comment]
I need to see the problem myself, somohow.

Could you put your PSD into a ZIP and send it to support@photopea.com ? I will try to share it myself.

**Comment by photopea** [comment]
I opened it in Photopea and I was able to share it: www.photopea.com/#imKhElwUc

Can you share any other document as a PSD? E.g. an empty document with just a single white layer?

**Comment by vilanova000** [comment]
So rare... But can you see that the logo has moved and the red color is different now?
________________________________
De: Photopea ***@***.***>
Enviado: jueves, 4 de julio de 2024 18:00
Para: photopea/photopea ***@***.***>
Cc: Albert Vilanova Farres ***@***.***>; Author ***@***.***>
Asunto: Re: [photopea/photopea] Share PSD (Issue #6939)

No suele recibir correos electrónicos de ***@***.*** Por qué esto es importante<https://aka.ms/LearnAboutSenderIdentification>

AVISO: Este correo electrónico proviene de un remitente externo a Grupo Godó. No haga clic en enlaces ni abra archivos adjuntos a menos que reconozca al remitente y sepa que el contenido es seguro. Si sospecha del mensaje, utilice el botón de notificación de phishing para reportarlo.


I opened it in Photopea and I was able to share it: www.photopea.com/#imKhElwUc<http://www.photopea.com/#imKhElwUc>

Can you share any other document as a PSD? E.g. an empty document with just a single white layer?

**Comment by photopea** [comment]
Did you insert PDF files into a PSD in Adobe Photoshop?

Photopea handles PDF files a bit differently than Photoshop. You can prevent this by rasterizing these smart objects, or inserting PNG smart objects.

**Comment by vilanova000** [comment]
I didn't make the .psd so i can't know that... so there's no solution?
________________________________
De: Photopea ***@***.***>
Enviado: jueves, 4 de julio de 2024 18:08
Para: photopea/photopea ***@***.***>
Cc: Albert Vilanova Farres ***@***.***>; Author ***@***.***>
Asunto: Re: [photopea/photopea] Share PSD (Issue #6939)

No suele recibir correos electrónicos de ***@***.*** Por qué esto es importante<https://aka.ms/LearnAboutSenderIdentification>

AVISO: Este correo electrónico proviene de un remitente externo a Grupo Godó. No haga clic en enlaces ni abra archivos adjuntos a menos que reconozca al remitente y sepa que el contenido es seguro. Si sospecha del mensaje, utilice el botón de notificación de phishing para reportarlo.


Did you insert PDF files into a PSD in Adobe Photoshop?

Photopea handles PDF files a bit differently than Photoshop. You can prevent this by rasterizing these smart objects, or inserting PNG smart objects.

**Comment by photopea** [comment]
You can report it separately, if you want.  So can you share any other document as a PSD? E.g. an empty document with just a single white layer?

**Comment by photopea** [comment]
I have to close it because of lack of details.
