### ISSUE TITLE
Bug in making another selection with Shift button

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#694]
When I make first selection (rectangle or ellipse) with hold on Shift, it is OK (fixed size with ratio 1:1). But when i try to add or subtract another selection to/from previous, then Shift doesn't work.

**Comment by photopea** [comment]
The Shift (for preserving 1:1 ratio) works only when there is no selection. Otherwise, it means, that the selection should be merged with the previous one (Shift + selecting will merge selections, you don't have to choose the combining mode in the top menu).

**Comment by MichalSZZ** [comment]
Yes I know how it works in simple way ;) But when you  try to make something more difficult with selections, Photoshop can do that.

Make circle selection (1:1 ratio with shift)
Then try to subtract rectangle selection from previus circle.
https://youtu.be/RllmOYyUqfM

In photoshop when you hit alt,shift,ctrl in making secound selection, then options have change. It is clear :)

But if you hold alt and after that start making selection, you can hit shift to hold on 1:1 ratio. In Photopea that dont work like in PS.

**Comment by photopea** [comment]
Do you know, if there is any detailed explanation of this behaviour, which makes it sound simple? Right now, it sounds too complex for me. I wonder if anybody is actually using these features.

**Comment by MichalSZZ** [comment]
Can You reopen this issue? I will try to explain how that should works :)

**Comment by photopea** [comment]
I would prefer to see some description from Adobe. I see, that when you hold Alt before drawing, the following pressing of Shift works differently. But maybe there are some other features, that I am not aware of.

**Comment by photopea** [comment]
Ok I think I made it work.

To make the new selection connect with a previous one, hold Shift before Clicking and dragging. To make width = height, press Shift while dragging, or before, if there was no selection. (so e.g. to connect with an old one and make width=height, press Shift, start dragging, release Shift and press it again).
