### ISSUE TITLE
Program interface broken?

### ISSUE THREAD

**Issue by Anubias25** [photopea/photopea#6940]
Your Operating System: Android
Your Web Browser: GoogleChrome
The problem happens in the Incognito Mode, too:

Program interface broken?
For a few days now, the Photopea program interface on Android, current browser GoogleChrome, has been displayed incorrectly both as a website and in the installed version. This does not only affect the German language. I am attaching pictures.
But everything is fine in Edge and also in the version installed via Edge.
Is this due to the program or the Android operating system or the web browser? Reinstallation was unsuccessful.
![Fehler 3](https://github.com/photopea/photopea/assets/114422147/a17ea65e-7dc8-49fb-a61e-00da150423ea)
![Fehler 4](https://github.com/photopea/photopea/assets/114422147/88ade522-62bc-4aee-97fd-57835c20ce26)
![Fehler1](https://github.com/photopea/photopea/assets/114422147/6fb73420-bb56-4c97-863e-b77614ccef30)
![Fehler2](https://github.com/photopea/photopea/assets/114422147/38540ebf-f2ad-4655-8f5f-8f386735e72e)

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Did you tell Google Chrome to auto-translate the Photopea website?

Please, look at Photopea.com the way it was made. Do not allow other tools to modify Photopea right under your hands.

**Comment by photopea** [comment]
So is it better now?

**Comment by photopea** [comment]
I have to close it because of lack of details.
