### ISSUE TITLE
Ads crashing the page

### ISSUE THREAD

**Issue by jack-s-wonderbolt** [photopea/photopea#6942]
Your Operating System: Windows
Your Web Browser: Opera
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Edit a picture

Since yesterday the page keep crashing and it looks like I'm getting more ads, I mean they change more often than they used to, blink right after they load, which I suspect might be the problem because with ad blocker it works more or less like before. I used to get this issues before but refresh seemed to fix it, I remember it was normal when the middle ad is different and crashing when it's like the rest.

**Comment by photopea** [comment]
I have to close it because of lack of details.
