### ISSUE TITLE
6ujmytgyhtrhgrehgtrhtrqergrwgwegre

### ISSUE THREAD

**Issue by drproto-AUTTP** [photopea/photopea#6943]
Your Operating System: windows
Your Web Browser: Microsoft edge
The problem happens in the Incognito Mode, too: no

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....put in this image
![image](https://github.com/photopea/photopea/assets/174508352/0e991d89-a897-4f52-930c-5fc654075f97)

3. ....
4. ....

**Comment by photopea** [comment]
I can open your image in www.photopea.com . Did you try it more than once? Are you using Photopea on a very old phone?

**Comment by photopea** [comment]
I have to close it because of lack of details.
