### ISSUE TITLE
Pencil tool differ from Photoshop

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#6945]
![1](https://github.com/photopea/photopea/assets/79258245/dceaa251-5cc6-41fd-84b0-e2fa1c1ee71d)
The pencil tool in Photopea doesn't work well.

In Photoshop, pencil in 1px draws when **centre** of cursor moves into a pixel. 

And with different size and spacing, pencil works differrently. If I move like this
![图层 1](https://github.com/photopea/photopea/assets/79258245/c6621db7-391f-40aa-b90a-b438c16de0d4)

pencil draws like this
![屏幕截图(15)](https://github.com/photopea/photopea/assets/79258245/0d68f866-1bd3-4f94-87b9-fb9fdfe3171b)

**Comment by photopea** [comment]
I think it works fine, and you can get used to it. It does not have to work exactly as in Adobe Photoshop.
