### ISSUE TITLE
make desktop app

### ISSUE THREAD

**Issue by YeesterPlus** [photopea/photopea#6946]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by yikuansun** [comment]
Made one in Electron a while back, https://github.com/yikuansun/photopealoader
Haven't maintained it in a while but if you have issues with it lemme know

**Comment by photopea** [comment]
You can install Photopea by pressing More - Install Photopea.
