### ISSUE TITLE
Não aparece acentuação.

### ISSUE THREAD

**Issue by pablo-hp** [photopea/photopea#6948]
Palavras que contém acentuação não estão aparecendo corretamente.
Exemplos de palavras que contém acento mas não aparece o acento;
É, à, á, ã, í, ó, ô, são apenas alguns exemplos de acentuação que não aparecem no aplicativo.

**Comment by photopea** [comment]
Sorry, I speak only English :(

**Comment by photopea** [comment]
It should be fixed now.

**Comment by pablo-hp** [comment]
Thanks
