### ISSUE TITLE
Aligning objects on layers to selection

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#695]
This is really helpful for me in Photoshop.
Most of time, I use Ctrl(cmd) + A to select artboard, and then aligning layers. This is very fast method when you use keyboard shortcuts.
But this works in Photoshop to any selection.

In example: 
I make website with grid. I want to align object to specific column in my layout (I have 12 vertical guides in Photoshop). I fast make rectangle selection with 4 columns and align object in center of this selection.
I use this feature very oft (in many situations - not only with grids)

**Comment by photopea** [comment]
What exactly is the featue that you need? I do not understand.

**Comment by MichalSZZ** [comment]
https://youtu.be/YMcMGaDLjgw 
fast aligning without making objects that are not needed in future

**Comment by photopea** [comment]
It was implemented. Thanks! :)

**Comment by MichalSZZ** [comment]
Works perfectly! Thanks!
