### ISSUE TITLE
Clicking quickly on two different items triggers a double click

### ISSUE THREAD

**Issue by dejan1024** [photopea/photopea#6950]
Your Operating System: Windows 10 / Windows 11
Your Web Browser: Google Chrome 126
The problem happens in the Incognito Mode, too: Yes, I only tested in Incognito

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create or open an image
3. Create two layers in the image
4. In the Layers window, quickly click on one layer and then the other

**Expected result**: the second layer is selected and nothing else.
**Actual result**: The "Layer Style" window opens for the second layer, as if it was double-clicked.

**Note**: This happens on other UI elements as well. For example:
1. Go to www.photopea.com
2. Create or open two images
4. Quickly click on one image tab and then the other

**Result**: the Name dialog opens for the second tab, as if it was double-clicked.

**Note**: The two clicks should be fast enough to register as a double-click if they were at the same place. The issue is easier to reproduce if the double-click speed on your system is slower.

**Comment by photopea** [comment]
thanks, it is fixed now!
