### ISSUE TITLE
Photopea not loading videos and converting them to frames

### ISSUE THREAD

**Issue by kritikalkrispies** [photopea/photopea#6951]
Your Operating System: macOS Big Sur
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Click on "File" and then "Open"
3. Select a video file
4. .Set fps
5. It usually takes a shorter time to have frames appear after setting fps but it's taking forever for them to open now.
6. File has been "loading" for ten minutes and still nothing is showing up. I didn't used to have this problem before.

**Comment by photopea** [comment]
I just tried it and it works fine for me.

Maybe the difference coudl be that a "video file" that you select is a different file than the one that I select. Could you attach your video file here in a ZIP?

**Comment by kritikalkrispies** [comment]
Tried it again with a different video ! And it turns out that the video might be too short. Thanks!

**Comment by photopea** [comment]
Could you share that video which you can not open in Photopea with us?
