### ISSUE TITLE
Lossless WebP filesize unexpectedly large

### ISSUE THREAD

**Issue by ThereforeGames** [photopea/photopea#6952]
Your Operating System: Windows 11
Your Web Browser: Brave Version 1.67.123 Chromium: 126.0.6478.126 (Official Build) (64-bit)
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Load a PNG image
3. File » Export As » WebP
4. Set Quality to 100 and observe that the filesize is significantly larger than PNG

---

In testing multiple images, I have found that PhotoPea's implementation of WebP produces files that exceed both 1) the original PNG filesize and 2) the filesize of its own PNG export option.

Also, the WebP format supports both lossless and lossy compression modes, but I don't see a toggle switch in the Export window. Does PhotoPea automatically switch to lossless at 100% quality?

Here is an example:

https://github.com/photopea/photopea/assets/95403634/557d7842-1d78-4d4e-b087-213b0973897c

Importantly, the original PNG is 233 KB and can be compressed down to ~203 KB lossless WebP using online converters such as this one:
https://www.freeconvert.com/webp-converter/download

If you wish to reproduce this test:
- [Original PNG](https://i.ibb.co/6DLbdPw/0a135f2b811b554f7dcfecabca735ba9.png) (233 KB)
- [PhotoPea WebP export](https://i.ibb.co/gMVjmz4/0a135f2b811b554f7dcfecabca735ba9-1.webp) (286 KB)
- [WebP using online converter](https://i.ibb.co/WHPBN1z/0a135f2b811b554f7dcfecabca735ba9-2.webp) (203 KB)

Am I missing something? Thanks.

**Comment by photopea** [comment]
So your question is "why is lossless WEBP compression in Photopea not the best in the world"? :D

We dont have our own WEBP encoder in Photopea. We are using the encoder that is built-in in your browser 

https://caniuse.com/?search=todataurl%20webp

So the WEBP file size depends on your browser (e.g. WEBP encoding in Photopea is impossible when running in Safari). I dont know if it is worth developing our own WEBP encoder, it might take weeks / months.

BTW I think your image should be compressed in a lossy way, the file is much smaller with almost no loss in quality.

**Comment by photopea** [comment]
The WebP image (below) still looks great and is only 60 kB. You will not get this quality at this size with PNG.

[image.zip](https://github.com/user-attachments/files/16162303/image.zip)

**Comment by photopea** [comment]
I will close it now. You should not use 100% quality for natural images (with thousands of colors). It is a waste of space to use a lossless compression.
