### ISSUE TITLE
Feature Request - Resize canvas / image to specific ratio

### ISSUE THREAD

**Issue by ZombieSmurf** [photopea/photopea#6953]
I'm missing a "to ratio" feature when resizing images or a canvas. It's not unusual that I work with screenshots or parts of other images, where I need them to fit a specific ratio. And it would be great to have that as an additional option in the resize dialog.

I have an image -
![image](https://github.com/photopea/photopea/assets/32956417/d0e1d89a-92bd-4ba4-b963-492dc74c003c)

and would like it to be cut down to a 16:9 ratio

**Comment by camoody1** [comment]
@ZombieSmurf Have you tried using the Crop Tool? It has ratio options.

**Comment by photopea** [comment]
I think the Crop tool should be used for this.

Did you ever use this feature in any program? I think it should be possible to do pretty much the same in Photopea.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
