### ISSUE TITLE
"Fill Path" no longer functions

### ISSUE THREAD

**Issue by mendeesuhl** [photopea/photopea#6954]
Your Operating System: Windows 11 Home
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open a *.svg
3. Select a path under "Layers"
4. Click "Paths"
5. Click "Fill Path"

Note:
If Select > All is performed prior to clicking "Fill Path", the selected path appears to be filled with the foreground color. But if the image or canvas is resized, or saving and re-opening the SVG, the selected path's color reverts back to its original color.  This issue is persistent on multiple machines and on Chrome, Edge, and the downloadable version of Photopea.

**Comment by photopea** [comment]
Which SVG should I open?

**Comment by mendeesuhl** [comment]
The issue can be replicated with any SVG file, or any project's with vector layers.

**Comment by photopea** [comment]
I did what I think you want me to did, and it is not supposed to fill any path. The "Fill Path" feature is for filling work paths, when a raster layer is selected. Not when a vector layer is selected as in your case.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
