### ISSUE TITLE
Ads of the Lagpocalypse

### ISSUE THREAD

**Issue by TheBloodSwiper** [photopea/photopea#6956]
Your Operating System: Work PC (Not Laptop but old hardware low end pc)
Your Web Browser: Edge

**This must be done to see the problem**
1. Go to www.photopea.com
2. Use the website with a HD image / 1980x2800 image.

Every time the ads change or animate, the program stutters. This makes the program really annoying to use!
The adds refresh/change too frequently! Please, it drove me insane and the only reason I forced myself to go trough it was due to a deadline and I was not at home! It was that bad that I loged into github here minutes before work just to post this issue!
Thats all. Please use ads but dont make them load soo frequently! I swear...

**Comment by photopea** [comment]
Could you record a short video of your experience with Photopea? How laggy it is?

I never witnessed a significant lag while using Photopea with ads. What  computer do you actually have? What CPU, RAM, etc? Is it more or less than 15 years old?

Maybe we should introduce some minimum hardware requirements, like other software has, to make sure the users experience is perfect.

**Comment by TheBloodSwiper** [comment]
CPU: Intel i3-8100 CPU 3.60 GHz.
GPU: Intel UHD Graphics 630
RAM: 16.0 GB
System: 64-Bit
Its less than 15 years old.

The lag is gone when the ads are still, and the lag starts right before an ad changes and ends when the new ad has loaded in.
Maybe decrease the frequency, or make the ads change on different timers? Maybe the fact that all 4 refresh/switch at the same time causes the lag?

**Comment by photopea** [comment]
Thanks! Could you press More - PeaMark, and tell us the results of your Peamark test?

**Comment by photopea** [comment]
Also, if you open "about://gpu" in Edge, is Video Decode and WebGL 2.0 hardware-accelerated?

**Comment by TheBloodSwiper** [comment]
Yes, hardware accelerated. Also is a work PC, not allowed to install softwares on it. :(

**Comment by photopea** [comment]
It takes literally 10 seconds.

**Comment by blahbluhblih** [comment]
i have the same issue. oh my god the ads cause so much lag. its unbearable

**Comment by photopea** [comment]
I have to close it because of lack of details :(
