### ISSUE TITLE
Photopea is no longer worth the effort.

### ISSUE THREAD

**Issue by BroDudeas** [photopea/photopea#6958]
When I first started using the website back in 2019 I had found it on my High-School's desktop and it worked, there were ads, but it worked. Now now almost 5 years later on my gaming PC that can run RTX Minecraft at 60 fps it does not work, because of the ads. The ads switch every 10 seconds, and occasionally you get a banner add you have to manually click out of like it's a mobile game. 
It's pathetic. And what's even more pathetic is how when you have an AD Blocker installed the website ceases to function properly. It's wild how someone can just steal Photoshops WHOLE layout, give a worse product, and still fill entitled to financial compensation. I will just pirate Photoshop, and so should you.

**Comment by camoody1** [comment]
@BroDudeas You're literally complaining about a free product and bragging about how you're going to just steal another product... and you think that Ivan is acting entitled? LOL. Goodbye, child.

**Comment by BroDudeas** [comment]
> @BroDudeas You're literally complaining about a free product and bragging about how you're going to just steal another product... and you think that Ivan is acting entitled? LOL. Goodbye, child.

I'd rather steal and be entitled than try and guilt trip adblock users into turning it off and begging for a subscription.

**Comment by camoody1** [comment]
> > @BroDudeas You're literally complaining about a free product and bragging about how you're going to just steal another product... and you think that Ivan is acting entitled? LOL. Goodbye, child.
> 
> I'd rather steal and be entitled than try and guilt trip adblock users into turning it off and begging for a subscription.

You'd rather steal from other people who provide an actual service and product rather than asking to be compensated for your work. Let's see how that plays out in your real life. I assume you go to work each day and tell your employer to just not pay you, right? You wouldn't want someone to accuse you of "begging for a paycheck". Moron

**Comment by tsvetav** [comment]
> When I first started using the website back in 2019 I had found it on my High-School's desktop and it worked, there were ads, but it worked. Now now almost 5 years later on my gaming PC that can run RTX Minecraft at 60 fps it does not work, because of the ads. The ads switch every 10 seconds, and occasionally you get a banner add you have to manually click out of like it's a mobile game. It's pathetic. And what's even more pathetic is how when you have an AD Blocker installed the website ceases to function properly. It's wild how someone can just steal Photoshops WHOLE layout, give a worse product, and still fill entitled to financial compensation. I will just pirate Photoshop, and so should you.

hi, I am rep of Photopea's ad partner. Would you please provide more info on the matter with the banner ad that looks like a mobile game and you have to manually close it? Do you have a screenshot? If you have managed to record it, please share, and provide Geo & browser used for reference. Thanks!

**Comment by photopea** [comment]
Ads in Photopea should always be only on the right side. Could you show us a screenshot of a "fullscreen ad" as a proof?

**Comment by blahbluhblih** [comment]
> > > @BroDudeas You're literally complaining about a free product and bragging about how you're going to just steal another product... and you think that Ivan is acting entitled? LOL. Goodbye, child.
> > 
> > 
> > I'd rather steal and be entitled than try and guilt trip adblock users into turning it off and begging for a subscription.
> 
> You'd rather steal from other people who provide an actual service and product rather than asking to be compensated for your work. Let's see how that plays out in your real life. I assume you go to work each day and tell your employer to just not pay you, right? You wouldn't want someone to accuse you of "begging for a paycheck". Moron

im fine with watching ads and popups but when the ads actually ruin the product (they cause horrible stuttering for some reason) i no longer want to use it

**Comment by camoody1** [comment]
@blahbluhblih If you don't like the application, then don't use it. That doesn't give anyone the right to steal from someone else. Holy shit. This isn't rocket science.

Now, obviously, there is something going on with the ads causing stuttering because a LOT of people have made posts about it. I get it. Ask for the problem to be fixed. Totally understandable. But don't use inconvenience as a justification for theft.

**Comment by photopea** [comment]
I have to close it, because the user is not responding.
