### ISSUE TITLE
Rounding corners of shapes does not work

### ISSUE THREAD

**Issue by Poleshchenkov** [photopea/photopea#6959]
Your Operating System: win 11
Your Web Browser: firefox
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new project
3. Add a rectangle shape to it
4. Set the parameter of rounding of corners
5. ?????
6. It doesn't work

**Comment by photopea** [comment]
You should set the corner radius before drawing a rectangle.

**Comment by Poleshchenkov** [comment]
Aw, okey

**Comment by bluep55** [comment]
If you go to the Properties Panel after you have created your shape, you can adjust the corner radii there.

![Properties panel](https://github.com/user-attachments/assets/fca59703-1ad0-4e26-aacd-15b30d0b4f07)

**Comment by Poleshchenkov** [comment]
Thanks, but I've already downloaded a normal photoshop :)

**Comment by camoody1** [comment]
> Thanks, but I've already downloaded a normal photoshop :)

Congratulations on your theft.

**Comment by vylq** [comment]
Thanks:)

**Comment by photopea** [comment]
It works literally 100% the same as in Adobe Photoshop. The same field at
the same location with the same functionality.

**Comment by camoody1** [comment]
> Thanks:)

That wasn't a compliment.

**Comment by vylq** [comment]
> That wasn't a compliment.

I'm sure it was. 
I solved my problem, you congratulated me on it.

**Comment by vylq** [comment]
> It works literally 100% the same as in Adobe Photoshop. The same field at the same location with the same functionality.

I am not a designer or an artist. I use such programs very rarely. Therefore, it is important for me that they are well-developed in terms of UI/UX. And it is not "works literally 100% the same as in Adobe Photoshop."

![image](https://github.com/user-attachments/assets/12123997-2d77-4ccf-b44a-2b1bfe0d8200)
![image](https://github.com/user-attachments/assets/6c115cd8-5053-48c3-8a97-c5c15b727d96)

**Comment by photopea** [comment]
Here is how it works in Adobe Photoshop. 

As you can see, setting the radius after drawing will not change anything. The radius must be changed in the Properties window.

I really recommend buying and reading some books about Adobe Photoshop to learn how these things work.

![image (1)](https://github.com/user-attachments/assets/ee73479c-c164-4d53-883d-324f3a987020)

**Comment by vylq** [comment]
[![Watch the video] Photopea _ Online Photo Editor — Mozilla Firefox 2024-07-14 06-49-51.webm](https://github.com/user-attachments/assets/a8cd644f-ab75-4ab1-838a-6f8d2a96e934)

[![Watch the video] Untitled-1 @ 66.7 (RGB_8) 2024-07-14 06-50-20.webm](https://github.com/user-attachments/assets/06bccc9d-9c1e-4e20-b972-2057e7c10bc8)

Let's end this pointless discussion. I closed the issue 12 hours ago. When I created it, I didn't intend to argue with anyone. I just wanted to edit a meme. It turned out to be easier and faster for me to download Photoshop than to figure out this program. 
Just to reiterate, I’m not a designer or an artist. I only need to use such programs maybe once a month. So, I don’t see the point in delving deeply into learning them.

**Comment by photopea** [comment]
This is probably some new feature of Photoshop, I did not know about it. But I still recommend to learn how to do it in Photoshop the original way, in the Properties window. It can be really useful.

**Comment by vylq** [comment]
It's not an original way. It's a bad way. If I can't round the corners without opening an extra menu, that's bad app design. It doesn't matter if Photoshop did it this way or not. You shouldn't just match the competition. You should aim to surpass them.

**Comment by photopea** [comment]
It seems like our user suggested it a year ago: https://github.com/photopea/photopea/issues/5842

I just implemented it, so it should work now.

![image](https://github.com/user-attachments/assets/ae00a676-4537-4e0a-aabf-bb20725cee66)

**Comment by bluep55** [comment]
I know you can hold the Alt key to adjust corners individually, but for anyone who doesn't know this, how about a button like this to switch between adjusting all corners to adjusting individual corners.


https://github.com/user-attachments/assets/3e9f8015-1a73-46a0-b570-78cece4927a9

**Comment by photopea** [comment]
I am afraid we would have too many buttons.

It works like this with the Alt key in Figma, too, and they have no menu. People will figure it out, or will read it in a manual.
