### ISSUE TITLE
Equal gaps between layers (and folders)

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#696]
Now in Photopea there is only left/right/center aligning (horizontal or vertical).
In Photoshop when I have more than two objects to align, I use very oft "Distribute horizontal centers" and "Distribute vertical centers".

There are two other options for each aligning in PS (vertical and horizontal) but I can live without them :)

**Comment by photopea** [comment]
Hi, I added a feature called "equal gaps" (in the top menu of the Move tool). I think that is what people usually need. What do you think about it?

**Comment by photopea** [comment]
Let's continue here. I will analyze it and implement it later.

**Comment by MichalSZZ** [comment]
I showed today this feature to my colleagues (graphic designers), and they were very impressed how that works. It is just simpler in use than in Photoshop - doing that, what should to do. Thanks again!

**Comment by photopea** [comment]
Cool, thanks!  :) They can save their PSD, open it in Photopea, make eqal gaps, save back as PSD, and continue in Photoshop! :D

**Comment by photopea** [comment]
I made it work for folders, too.

**Comment by MichalSZZ** [comment]
There is a problem with aligning (any type - left, right, equal gaps) folders, that have other folders inside (i think that is the reason). 
[folders-aligning-bug.psd.zip](https://github.com/photopea/photopea/files/2065428/folders-aligning-bug.psd.zip)

**Comment by photopea** [comment]
Oh, sorry for that ... it is fixed now :)

**Comment by MichalSZZ** [comment]
OMG it works!
LOL. Are you a robot? Or any other thing with AI? Humans don't work so fast!

**Comment by photopea** [comment]
No :D this last problem tool like 20 seconds to fix :D
