### ISSUE TITLE
the ads are causing unbearable amounts of lag

### ISSUE THREAD

**Issue by blahbluhblih** [photopea/photopea#6960]
its almost impossible to draw with the amount of stutter. every few seconds the ads change and the entire website stutters and i can't get anything done. please fix this, it's horrible

**Comment by photopea** [comment]
I can not see such a lag on any of my devices, to be able to tell how bad it is and how to solve it :(

Could you press More - PeaMark (in www.Photopea.com) and tell me the results, please?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
