### ISSUE TITLE
All of a sudden can't dither.

### ISSUE THREAD

**Issue by Memeatode2** [photopea/photopea#6967]
Your Operating System: Windows 11
Your Web Browser: Opera GX
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Upload any image either 64x64 or 32x32 pixels.
3. Resize a larger image to match said size.
4. Click reduce colors.
5. Shabang! It freezes up and corrupts the whole websites functionality for no reason!

**Comment by photopea** [comment]
I did what I think you want me to do, but Photopea did not freeze :(

What is "Resize a larger image to match said size." ? Could you write the exact steps how to make Photopea freeze? If some step is not important, do not mention it.

**Comment by Memeatode2** [comment]
https://github.com/user-attachments/assets/3c3095a4-6d0b-4cee-bd04-ad3c3a67b13d

Heres a video that shows not only the original bug but a new one too.

**Comment by photopea** [comment]
Could you record a short video of how you make Photopea freeze, but **start with opening www.photopea.com in the incognito mode** (without any browser extensions) ?

**Comment by Memeatode2** [comment]
https://github.com/user-attachments/assets/198d8ab2-9b22-40b1-9e18-d2806ab712b3

**Comment by photopea** [comment]
I think I have found a bug. It should be fixed now. I am sorry for it. It should never happen again.
