### ISSUE TITLE
Dither Issue

### ISSUE THREAD

**Issue by someayden** [photopea/photopea#6968]
Your Operating System: Windows 11 Pro
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. .... Select 'Image'
3. .... Select 'Reduce Colors'
4. .... Uncheck 'Reduce Noise'
5. Check 'Dither'
It crashes Chrome

**Comment by photopea** [comment]
I just tried it, but I can not make Chrome crash :(

Did you try it with more than one image? If it happens only for one specific image, could you share it with us? I will not be able to see the problem without your image.

**Comment by someayden** [comment]
The problem occurs with all images. The first image it happened with is attached below.

![sddd](https://github.com/user-attachments/assets/cf7f1c50-814f-4100-8021-e5a7f23fd9f6)

**Comment by someayden** [comment]
Here, it has happened again. I tried it a few minutes ago and something happened. However this time it did not freeze, it just showed half and image. 

![image](https://github.com/user-attachments/assets/8f2995f4-1230-4d8f-8438-6645f0c0109b)

**Comment by photopea** [comment]
I just tried it and it seems to work fine.

![image (3)](https://github.com/user-attachments/assets/475e353d-37f9-4bce-91c3-fa46cc7b1466)

**Comment by photopea** [comment]
Could you record a short video of opening www.photopea.com and what you do next, to make Photopea freeze? Please, do not start the video with opened Photopea. Start the video with opening www.photopea.com

**Comment by photopea** [comment]
I really need to see it not working myself, to be able to investigate it :(

It would really help if you told me how you did it.

**Comment by photopea** [comment]
I think I have found a bug. It should be fixed now. I am sorry for it. It should never happen again.

**Comment by someayden** [comment]
Thank you.
