### ISSUE TITLE
Sometimes the Aliasing options don't show up, and not at all on normal to smaller scales.

### ISSUE THREAD

**Issue by SIG7Pro** [photopea/photopea#6969]
Your Operating System: Bodhi Linux (Desktop: KDE Plasma) (Seems to also occur on other OSes)
Your Web Browser: Vivaldi (and etc.)
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Get anything and scale it.
3. There's most likely not the aliasing things there.
4. And now the images are blurry and not pixelly!
![image](https://github.com/user-attachments/assets/5d2dc754-246c-4801-b0ad-b26c0f4c7ebe)

Yet it can be seen on some smaller scales *sometimes*.
![image](https://github.com/user-attachments/assets/3b1b1acf-51c8-4f8d-a9af-22845e0e5002)

Edit: I decided to see what'd happen if I were to resize the thing in the first image since it was an imported smart object and yeah the thing doesn't show on small resolutions now.
![image](https://github.com/user-attachments/assets/9693d1f8-7c91-4dea-b46b-a23faf5b271f)

Edit 2: Corrected my info at the top. It appears if you try to upscale something imported (like a smart object), then it doesn't show the thing, but drawn layers appear to be sometimes.

**Comment by photopea** [comment]
I have added the option into Edit - Preferences, where you can set the interpolation method for Smart Objects.
