### ISSUE TITLE
Feature request - Squared align

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6970]
it would be great to have an additional alignment shortcut button on the move tool for aligning layers into an evenly spaced square:
![image](https://github.com/user-attachments/assets/0e86ba78-2b5d-41de-99a8-8cac529abea7)

It would be cool to get the top left corner and the right bottom corner, and all in the middle aligns in a square pattern
![image](https://github.com/user-attachments/assets/50abdb43-3205-4968-80ab-0b8547d1d822)

**Comment by TheRadicalDreamer** [comment]
Yes, i have always made it with grids and other techniques.
But as someone who works in printing this is a really common task that takes time.

Maybe you should input the table before hitting the square align button:
![image](https://github.com/user-attachments/assets/b53e7471-e656-4081-8640-e1311cd209d9)

(i  imagine something like this)

And about the order of layers, each layer should be sent to the nearest squared place, and if there is a conflict, it should consider the order of the layers in the layers panel.

:)

**Comment by photopea** [comment]
Is this feature available in any other software? I would like to see what
logic do they use. Did you look into Figma maybe?

**Comment by TheRadicalDreamer** [comment]
check this video:
[Screen recording 2024-07-17 19.34.28.webm](https://github.com/user-attachments/assets/56621b01-ed0a-4015-ba3e-bbe54add0bd8)

**Comment by TheRadicalDreamer** [comment]
And this other:
[Screen recording 2024-07-17 19.35.50.webm](https://github.com/user-attachments/assets/770e497c-13f3-4f8c-be82-d8931c034236)

It gives the same spacing to every piece
![image](https://github.com/user-attachments/assets/274c5d7a-4b3b-4a61-8eba-a1548e6869ff)

**Comment by TheRadicalDreamer** [comment]
The exact order of how it does, i cannot understand it.

But go to figma and play around with it

**Comment by photopea** [comment]
Do you want it to work in Photopea the same as it works in Figma?

**Comment by TheRadicalDreamer** [comment]
Not exactly. Because i dont know how it get the number of columns and rows
It can go from this:
![image](https://github.com/user-attachments/assets/ea7758cd-1749-48e0-b511-944ec32b3ec2)

To this:
![image](https://github.com/user-attachments/assets/41f72911-faf3-4cdc-b23b-c232713eae0e)

What is cool though, is that after you tidy it up, you can modify live the distance between the layers
![image](https://github.com/user-attachments/assets/f9820b0e-2bb7-441a-915f-01adc787354d)

**Comment by TheRadicalDreamer** [comment]
Also (which is good to have) the tidy up tool is disabled disabled if layers are exactly overplaced.

I believe it should ask you the columns and rows OR you it sets them accordingly the amount of layers available trying always to create a filled square (but that maybe will also create random behaviours)

**Comment by photopea** [comment]
And did you try a GuideGuy to create guides?

**Comment by TheRadicalDreamer** [comment]
What is GuideGuy?

**Comment by photopea** [comment]
It is a tool for adding guides. Press Window - More - Guide Guy.

**Comment by TheRadicalDreamer** [comment]
Didn't know about it.

I tried, and it helps. 

Although, i have to put every layer in every place myself.

Normally i have to set 100 or 50 layers, so it is time consuming anyways.

**Comment by photopea** [comment]
so you dont want it to work as in Figma. Do you know how it should work? I dont think such a feature could be useful, because it is faster to place layers manually, than to learn how to use some complex tool with many parameters.

**Comment by TheRadicalDreamer** [comment]
I have been thinking about this. And i believe how Figma works is better for my work scenario. 

Here is a video of me trying to make my task in Photopea and Figma:
https://drive.google.com/file/d/1baen1ee1ir50-nIoaZhQuHCwfq4m73kc/view?usp=sharing

Additionally, it would be good to be able to prioritize the width and height of the columns and rows of the Guide Guy over the margins/paddings (o at least indicate which metric prioritize)

**Comment by photopea** [comment]
When your document is 680 mm wide, and you ask for 10 mm gaps and 50 mm cells, it is not possible!

Try to count with me: 10 + 50 + 10 + 50 +  ... + 50 + 10 = 680 ... how many cells should be there?

What exactly are you trying to achieve? Do you want the objects to be placed evenly within some larger rectangle, or you want to have a specific size of a "cell", like 50.09 mm?

**Comment by TheRadicalDreamer** [comment]
I am trying to achieve a 50.09mm gap, so when i move the layer to the place it belongs, it snaps immediately and i don't have to be adjusting precisely with the cursor, which takes a lot of time, when you are placing 100 or more layers.

And i would like at least 10 mm gap in between. That's why i thought about prioritizing, because it not possible to achieve exactly the number, the Guide Guy prioritizes the gap value, over the width value, giving exactly 10mm gaps, but +/-50mm wide

I need the exact opposite: exact 50mm wide and +/-10mm gaps

In the video above I was just showing you how i face my daily tasks, using the tools i have available, it wasn't made to bother you :) 

Guide Guy is a very useful tool, but it does not give me what i need.

Figma Tidy up tool on the other side, gives me what i need, and also, more visually and intuitively. Because i can edit the gaps in between columns live, i can see how many columns and rows i can fit into my canvas, without calculating beforehand.

That's why i thought that the Tidy up tool should be in Photopea.

**Comment by photopea** [comment]
I think that is what the Grid is for. Set the Grid Gap to 60 mm and drag your items to the top left corner of each grid cell. Then, you can move all your items simultaneously.

I can add a "Tidy Up" option, where you specify a number of columns, and the column width (60 mm in your case), and it will arrange your items into a grid (grid size 60 mm), filling it row by row with your items.

**Comment by photopea** [comment]
I have added an experimental Tidy Up button (to the top menu of the Move tool).  It computes the Width (distance from the left-most edge of all items, to the right-most edge of all items), and creates as many columns as possible within this width.

You can try it ou ton this document: www.photopea.com/#iVXHGTXSP

**Comment by TheRadicalDreamer** [comment]
Looks good!

Should it be possible to add 2 inputs like Figma has, where you can modify the gap in between?
🙈

**Comment by photopea** [comment]
I have added the Columns and the Gap parameters.

**Comment by TheRadicalDreamer** [comment]
Wow!
Super!
I love it!

It is possible to have the units of gap, to be the same you use in the ruler? 🥰

**Comment by photopea** [comment]
Ok, they are ruler units now.

**Comment by TheRadicalDreamer** [comment]
![download](https://github.com/user-attachments/assets/6ffb77db-6443-482f-9be1-e12f3b9aea4e)

**Comment by photopea** [comment]
I will close it then.

**Comment by TheRadicalDreamer** [comment]
Because some print papers are rectangles and not squared, sometimes there is the need to have different spacing between vertical and horizontal.
So, i was wondering if, similar to Figma, you could add vertical gap spacing and horizontal gap spacing, like this:
![image](https://github.com/user-attachments/assets/ddf930ab-aa68-4670-b743-6767ddd00fb6)


So could look like this in Photopea:  
![image](https://github.com/user-attachments/assets/7ad440a4-46b4-4438-8bdd-0b9f8473fffc)

**Comment by photopea** [comment]
I have added a field "Vertical Gap". The "Gap" field changes the "Vertical Gap", but "Vertical Gap" can be changed independently.
