### ISSUE TITLE
Feature request - Store assets in PeaDrive

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#6971]
It would be cool to have all my fonts, swatches, patterns, etc saved in the peadrive.

So when i open a file in another device i have all my things.

This has happen to me a couple of times,that i open Photopea in another device and it has a special font that i don''t have it in that device, so i cannot work on the project properly.

**Comment by photopea** [comment]
If your internet is slow, downloading 20 MB of fonts from PeaDrive could take a minute :/

Are these commercial fonts? It makes no sense to have 100 users keep the same font file on their peadrive. It would be better to add this font into our font database (one file on a server).

**Comment by TheRadicalDreamer** [comment]
Yes, these are commercial fonts.

The issue is not the download speed, but to have a device that have to redownload all the assets again from different sources.

**Comment by photopea** [comment]
But still, downloading fonts from the internet each time you open Photopea will be slower than having them in the Local Storage.

Do you know, that in Edit - Local Storage, you can press "Get all as ZIP", and send this ZIP to a different computer, and load it back into Photopea?

**Comment by TheRadicalDreamer** [comment]
What if everytime i load something to the local storage (and i have a premium account) it also logs the date on the local device and on the cloud, so when i log in in another device it it only checks if the local log of the date is the same as the one on the cloud. And if it is different, only then it ask you to update your local storage.

What do you think about it?

**Comment by TheRadicalDreamer** [comment]
What do you think about this solution?
Do you think it can be implemented?

**Comment by photopea** [comment]
Only 1 in 1000 Photopea users uses PeaDrive, and only 1 in 1000 peadrive users would probably use this feature.

What about having your resources on your Google Drive? when you are on a new device, you can drag-and-drop them into Photopea, and they would stay on that device in a Local Storage forever. What do you think?

**Comment by TheRadicalDreamer** [comment]
That's exactly what i have been doing.

Look, this is your product, i only give my suggestions, report bugs and try to help other users because i respect and appreciate your work a lot 🥰.

Do you think that maybe you can implement some kind of poll on social networks, to see and get comments about new features you might implement? That will also engage the community and make them feel part of the process. Maybe you'll be surprised.

I believe that using Peadrive to have cross-platform cross-device assets is neat.

I use Photopea on my office's PC, my own PC and my phone. So having all my fonts, brushes, patterns synched on all my devices sounds great.

**Comment by photopea** [comment]
I will close it now, as I dont think it is needed by a lot of users.
