### ISSUE TITLE
Unable to change text color.

### ISSUE THREAD

**Issue by barkler** [photopea/photopea#6973]
Your Operating System: Win10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes.

**This must be done to see the problem**
1. Go to www.photopea.com
2. Use text tool to create text. 
3. Highlight text. 
4. Change color on color palate located at the bottom of the tool bar. Click palate, choose new color, OK.
5. Text stays black instead of changing to new color.

**Comment by bluep55** [comment]
Use the color palette on the top toolbar.

**Comment by bluep55** [comment]
It works that way in Photoshop, but in Photopea you have to use the palette on the top toolbar.

**Comment by barkler** [comment]
AHA! Thank you!

**Comment by photopea** [comment]
I am glad that you have solved it! :)
