### ISSUE TITLE
Pen tool path glitched

### ISSUE THREAD

**Issue by Requis000** [photopea/photopea#6974]
Your Operating System: Windows 11
Your Web Browser: Edge
The problem happens in the Incognito Mode, too:
Yes
**This must be done to see the problem**
1. Go to www.photopea.com
2. Click the pen tool and select path
3. Click randomly, (Or make something with it idk)
4. Press, "Shape" make it a shape, then try and use the pen tool (path) again. 

it never works and I have to save it, then open a new tab, and make another shape, then restart the process.

**Comment by photopea** [comment]
What is a step 2: Click pen tool and select path? Should I open some file first? Could you please provide exact steps?

**Comment by Requis000** [comment]
> What is a step 2: Click pen tool and select path? Should I open some file first? Could you please provide exact steps?

Sorry, I will try and explain more in depth.

Open photopea, click new project, do any size, when you arive at the blank canvas, use the pen tool, make "path" instead of "shape." Once you do that, use the pen tool, you can do any shape, anything, then make it a shape, (at top.) and once its a shape, you can try to use it again and it doesnt work, Ill try and attach a video showing this as I am bad at explaining stuff.


https://github.com/user-attachments/assets/669abc68-5478-4c54-815e-f148014d94cc

**Comment by Requis000** [comment]
Im not sure if Im doing something wrong but ive looked everywhere and cant find a fix for this.

**Comment by photopea** [comment]
The bug happened when you deselected the work path, and started drawing a new path with a pen tool.

I think I have fixed it. It should never happen again.
