### ISSUE TITLE
font not uploaded

### ISSUE THREAD

**Issue by tunis34** [photopea/photopea#6975]
Operating System: macOS
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

I downloaded the font called 'suite variable', and it has 7 different styles including 'light, bold, semibold,'...
but photopea only recognized light one and doesn't include other 6 styles when I uploaded the font to it. 

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Could you share your fonts here with us, in a ZIP file?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
