### ISSUE TITLE
Loading a Pdf file

### ISSUE THREAD

**Issue by AudioartEstudi** [photopea/photopea#6976]
Your Operating System: Sindow 10

Hi. I have a problem when I load a pdf file in Photopea. This Pdf is based in music notation but, when I load in photopea, all the musical notes change to a normal letters. 
It does not respect the file format. Do you know any solution?

Thanks and regards

**Comment by photopea** [comment]
It is probably there is a special font inside a PDF, used to draw notes. Photopea can not extract fonts from PDF files, sorry :(  Maybe take a screenshot of your PDF and paste it onto Photopea to edit it as a single-layer raster image.
