### ISSUE TITLE
Magic cut UI not launching properly

### ISSUE THREAD

**Issue by chadcrume** [photopea/photopea#6977]
Your Operating System: MacOS
Your Web Browser: Firefox & Chrome
The problem happens in the Incognito Mode, too: Only tested incognito

**This must be done to see the problem**
1. Go to www.photopea.com
2. Load an image
3. Choose Select > Magic Cut
4. PROBLEM: A modal window opens with title Magic Cut but is empty and remains a small modal window.
5. "x" out of the modal window
6. Again, choose Select > Magic Cut
7. PROBLEM VARIATION: A modal window opens with title Magic Cut and fully expands to the viewport. The magic cut toolbar is visible, but the image is not visible. Clicking into the image canvas shows tool-color transparent overlay on top of default empty background grid.

**Comment by photopea** [comment]
I just tried it and it works fine for me.

Did you try it with more than one image? If it happens only with one specific image, could you share that image with us?

**Comment by chadcrume** [comment]
I did try with several. Will try again when I have a chance

**Comment by photopea** [comment]
So does it work?

**Comment by chadcrume** [comment]
It is working for me now, using the same images.

**Comment by chadcrume** [comment]
Hello. I'm seeing this same issue again right now.

**Comment by kuckir** [comment]
What should I do to see it myself? I think I will need the same image that you use.

**Comment by chadcrume** [comment]
Here's a loom video of what I'm doing (dragging and dropping to open the
image):
https://www.loom.com/share/35b2d9295f6d4d968b259a7bd846d251?sid=9bfacb0f-f334-4a0e-a245-66a20ac88714

And here are large and medium versions of the test image:
https://www.dropbox.com/t/0xTVxArYXTY15Ghf

**Comment by photopea** [comment]
Thanks a lot. It is fixed now.

**Comment by chadcrume** [comment]
Confirmed. Thank you!
