### ISSUE TITLE
Blurry prints

### ISSUE THREAD

**Issue by glapere** [photopea/photopea#6978]
Your Operating System: Microsoft
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....Upload item to print
3. ....Print and you will see the blurriness. **Even if you save a clear image in photopea, it will come out blurry. I have tried numerous high quality prints that I always use in this program and it's doing the same thing to all. First pic shows photopea copy, second is just printing from computer.

Pic 1 & 2 will show one that is crisp printed from my computer, and the blurry one printed from photopea. I've used photopea religiously for the last few years and never had it turn every print blurry. 
![Screenshot_20240718-222659](https://github.com/user-attachments/assets/6b181e15-8225-4837-844b-04937abb2da7)
![Screenshot_20240718-222703](https://github.com/user-attachments/assets/466f5ac8-0e32-4530-835f-60773ab4b019)

**Comment by photopea** [comment]
Hi, in "upload item to print", what exactly is that item? Is it a file? What kind of file?

By "print", do you mean pressing File - Print in Photopea?

**Comment by photopea** [comment]
When printing, could you try to disble "rasterize all"?

**Comment by photopea** [comment]
It used to be disabled by default, but yesterday, I made it enabled by default.

**Comment by glapere** [comment]
Thank you! That fixed the issue! You are awesome and it's so nice how fast you reply!
