### ISSUE TITLE
Trim doesn't work with SVG images under the Batch process

### ISSUE THREAD

**Issue by ivancucer** [photopea/photopea#6979]
Your Operating System: macOS 14.5 Apple silicon
Your Web Browser: Chrome 126.0.6478.127
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open a SVG icon (eg. https://www.svgrepo.com/show/513758/bookmark-check.svg)
3. In Actions: create a new action and start recording
4. Image → Trim (Color to Trim: Transparent; Sides: Left and Right checked, Top and Bottom unchecked)
5. Actions: stop recording
6. File → Automate → Batch
7. Source Images → select a few SVG icons
8. Select a newly created action
9. Format: SVG
10. Process images button
11. Unzip archive
12. All SVG files are empty!

Any ideas on how to fix it?

**Comment by photopea** [comment]
Hi, it should be fixed now.
