### ISSUE TITLE
Moving layer from folder to the back of layers stack

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#698]
I think that is a bug. When I have only folders (and layers grouped in it) without any other layers like background layer, I can't remove one layer from folder and "send to back". This layer should be the first layer on layers panel (without a folder - like background layer on program start).

I can't force it with keyboard shortcuts like in photoshop ("cmd + ]" and "cmd + [" what in Adobe product is responsible for layer ordering "bring forward" and "send backward").

**Comment by photopea** [comment]
In other words, if the folder is at the bottom of layer list, and you move anything under that folder, it ends up as the last item inside that folder.

**Comment by photopea** [comment]
I fixed it. Now, if you drop it very very close to the bottom edge of the last layer, it is placed outside the folder.

**Comment by MichalSZZ** [comment]
Thank You. I will check that when I come back to home. https://youtu.be/Ujb_IGi-uwc 2m 30 sec showing my problem but now is it to late :)

**Comment by MichalSZZ** [comment]
Thanks! Now works correct.
