### ISSUE TITLE
Ads taking up half the screen

### ISSUE THREAD

**Issue by AikoTM** [photopea/photopea#6980]
Your Web Browser: Firefox 128.0

I turned off Adblock for you, and this is how you thank me. 

![grafik](https://github.com/user-attachments/assets/83c8fee9-26c6-47bf-aca2-c4a190b1f435)

**Comment by photopea** [comment]
There should never be ads like this in Photopea.

When it happens, could you please open the web console and scroll to tohe top? There should be a line with a number 0, 1 or 2. What number do you see?

**Comment by AikoTM** [comment]
There is a line with a 1

**Comment by tsvetav** [comment]
> There is a line with a 1

hi, could you please provide info on browser used, as well as Geo? This will immensely help resolve this asap. Thanks!

**Comment by AikoTM** [comment]
Browser used is Mozilla Firefox 128.0
Geo Location is Germany (Not sure how detailed this has to be)

**Comment by tsvetav** [comment]
> Browser used is Mozilla Firefox 128.0 64-Bit Geo Location is Germany (Not sure how detailed this has to be)

That's more than enough at this point, thank you! 
Could you also confirm whether the ad still displays with all cache & cookies cleared? And last but not least, a kind request - if by any chance it displays again, please add #audit right after the url and this will give you the chance to directly report it to the ad quality scanning tool. Thanks for the cooperation and apologies for the inconvenience!

**Comment by AikoTM** [comment]
So far, the ad hasn't shown up today. 
Only yesterday, no matter how many times I restarted - maybe it has been reported and removed already. 
I'll update you if it ever happens again.

**Comment by photopea** [comment]
Ok, I will close it for now.
