### ISSUE TITLE
Scam Adverts

### ISSUE THREAD

**Issue by raminazim** [photopea/photopea#6981]
Your Operating System: Windows
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Work as usual
3. Multiple exit webpage no work saved alert
4. goes to a scam website

**Comment by photopea** [comment]
Hi, when it happens, could you open the web console and scroll to the top? There should be a line with a number 0, 1 or 2. What number do you see?

**Comment by tsvetav** [comment]
@raminazim This sounds like something happening in the browser itself. Did you manage to take a screenshot? What's the browser that you're using and which country are you in?
Thanks in advance for clarifying!

**Comment by raminazim** [comment]
@photopea it happens once in a while, when I do get it I'll let you know asap.

**Comment by raminazim** [comment]
@tsvetav I'm using Chrome and I'm in Canada. It only seems to happen when I'm using photopea.

**Comment by tsvetav** [comment]
> @tsvetav I'm using Chrome and I'm in Canada. It only seems to happen when I'm using photopea.

Thanks for the info! I do suspect this is related to your browser extensions though, as there were similar previously reported cases. I would therefore recommend disabling them and confirming whether this occurrence is still present.

**Comment by tsvetav** [comment]
If you're still seeing such an ad, I would recommend making a .har file and sharing it for reference.
[har file extraction_desktop.pdf](https://github.com/user-attachments/files/16338044/har.file.extraction_desktop.pdf)
I am attaching simpke instructions on how to do so. I know it's already a lot to ask, but would be of immense help to easily resolve the issue, provided that it's indeed ads causing it. And thank you for flagging this in the first place!

**Comment by raminazim** [comment]
[har.file.extraction_desktop.pdf](https://github.com/user-attachments/files/16338781/har.file.extraction_desktop.pdf)

lemme know if you need one with more time

**Comment by photopea** [comment]
I think it is done by your Honey browser extension.

Could you try to use Photopea in the Incognito mode (with no extensions running) and tell us if you ever see any scam ads?

**Comment by photopea** [comment]
Are there any news? Do you ever see any scam ads with the Honey extension disabled? I think it happened in the past with one of our users, when the Honey extension was inserting ads into Photopea.

**Comment by photopea** [comment]
Let me know if you have any other problem again :)
