### ISSUE TITLE
Scam Norton Antivirus Ad takeover and force close

### ISSUE THREAD

**Issue by GetOutOfHim** [photopea/photopea#6982]
Your Operating System: Windows 10
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. .... work as usual
3. .... pop up forces me to close my file without being able to save, even when choosing the "block this dialogue" option
4. .... Norton Scam Antivirus everytime, takes over the entire screen no option returns me to my project window
![nortonscamad](https://github.com/user-attachments/assets/f92734d4-dc1c-46e4-9bc6-e39afd8c282f)

**Comment by photopea** [comment]
Hi, when it happens, could you open the web console and scroll to the top? There should be a line with a number 0, 1 or 2. What number do you see?

**Comment by photopea** [comment]
Also, did it ever happen while using Photopea with no browser extensions? We need to rule out the option that it was done by your browser extension.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
