### ISSUE TITLE
If I press "Esc" instead of cancel or save in the window.  Next time I open other or same image with photopea the save option dissapears

### ISSUE THREAD

**Issue by Usser2023** [photopea/photopea#6983]
![Screenshot 2024-07-21 010410](https://github.com/user-attachments/assets/f7436af0-37df-4c86-bef8-f257400f85b8)

**Comment by photopea** [comment]
I am confused. What are you talking about? Is it about www.photopea.com ?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
