### ISSUE TITLE
exclusion blending mode does not inverse text over color

### ISSUE THREAD

**Issue by IslamZaoui** [photopea/photopea#6984]
OS: windows 10 64-bit
Browser: chrome

Tried to use exclusion blending mode to inverse color of a text over like this:

![image](https://github.com/user-attachments/assets/88b9d3da-0c4b-44a5-81f0-a888627c1583)

but I got this

![image](https://github.com/user-attachments/assets/3541fab2-d7ac-48e8-b207-647ddc82523e)

text over is invisible

**Comment by photopea** [comment]
I am confused. Could you please provide some steps, what should I do to see an error?

If you think the blend mode in Photopea is wrong, could you provide any proof that the exact same thing works differently in any other software?

**Comment by IslamZaoui** [comment]
nvm, it's was a coloring issue just change it from black to white
sorry for that
