### ISSUE TITLE
Navigator panel outline box glitches on canvas rotation

### ISSUE THREAD

**Issue by treefrogman** [photopea/photopea#6987]
Your Operating System: Android
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Switch to Hand Tool > Rotate View
3. Open the Navigator panel
4. Rotate the canvas with the hand or the angle slider in the toolbar
5. Take note of the red rectangle in the Navigator panel at various canvas rotations

**Comment by photopea** [comment]
It should be fixed now.
