### ISSUE TITLE
Feature: Navigator panel rotation slider

### ISSUE THREAD

**Issue by treefrogman** [photopea/photopea#6988]
1. Go to www.photopea.com
2. Switch to Hand Tool > Rotate View
3. Open the Navigator panel
4. Rotate the canvas with the hand or the angle slider in the toolbar
5. Feature request: angle slider copied from that toolbar to the Navigator panel

Why? So I can set/clear canvas rotation without switching tools.

Thank you for considering this idea, and thank you so much for this amazing app!

**Comment by photopea** [comment]
I have added the Rotation slider into the Navigation panel.
