### ISSUE TITLE
Fuji GFX-100 RAW pictures have wrong colors

### ISSUE THREAD

**Issue by eugenialoli** [photopea/photopea#6989]
Your Operating System: Debian
Your Web Browser: Chrome stable, latest
The problem happens in the Incognito Mode, too: dunno

**This must be done to see the problem**
1. Go to www.photopea.com
2. .... Load a RAW file from the Fuji GFX100 camera (100MP).
3. .... The colors are all wrong, it's as if its hue has all shifted to the right.
4. Fixing the color balance via the RAW panel/settings doesn't fix the issue.

Sample RAW files here: https://www.samuelzeller.ch/journal/fujifilm-gfx100-sample-images-jpeg-raw-files

**Comment by photopea** [comment]
Thanks for reporting it, it should be fixed now.
