### ISSUE TITLE
Moving a layer with a transparent background leaves artifacting

### ISSUE THREAD

**Issue by Stebulous** [photopea/photopea#699]
Doing above will leave the layer behind with random blotches of transparency

**Comment by photopea** [comment]
It never happened for us. Can you update your browser? Or tell us, if it happens in pea.psd demo (available in the main menu) ?

**Comment by MichalSZZ** [comment]
@Stebulous 
Are you sure, that you don't have selection on that layer when trying to move?
That was a very common error (for my students) on my graphic design lessons (made with photopea help).

Try to deselect (ctrl + D) befor move any layer.

**Comment by photopea** [comment]
I am going to close it because of lack of details :(
