### ISSUE TITLE
Multitouch canvas rotation produces angles outside -180,180 range in Navigator panel angle field

### ISSUE THREAD

**Issue by treefrogman** [photopea/photopea#6990]
Your Operating System: Android Samsung Tab S6
Your Web Browser: Chrome

**This must be done to see the problem**
1. Go to www.photopea.com on a multitouch device, and create a new blank project
2. Open the Navigator panel
3. Rotate the canvas using multitouch gestures
4. Observe angle values ranging from 0 to 360

Note: the Rotate View hand's toolbar angle field shows correct values on multitouch rotation

**Comment by photopea** [comment]
it should be fixed now.

**Comment by treefrogman** [comment]
https://github.com/user-attachments/assets/8ae3447f-c566-4eb4-930b-0d0004f95b54

no luck on my devices (sm-t860 tablet and pixel 5 phone).
tried incognito, reloading, clearing site data.

**Comment by photopea** [comment]
sorry, it should be fixed now.

**Comment by treefrogman** [comment]
beautiful! thank you!
