### ISSUE TITLE
Keeps Crashing everytime I put a new layer or use the type tool

### ISSUE THREAD

**Issue by Screenthing23** [photopea/photopea#6991]
Your Operating System:MAC
Your Web Browser: Opera GX
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. .... Open Pre saved file
3. .... apply new layer or use the type tool
5. .... the site crashes and is unable to load any of the formentioned images

**Comment by photopea** [comment]
have you tried to use a different web browser? Maybe it is a bug in Opera GX.

**Comment by photopea** [comment]
I have to close it because the pesron did not respond :(
