### ISSUE TITLE
Super laggy and buggy, tried on two computers. Won't even show files that open anymore

### ISSUE THREAD

**Issue by mausmedia** [photopea/photopea#6992]
Your Operating System: windows 11
Your Web Browser: google chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. try to open something
3. wait forever and then watch nothing happen
4. if you start with a new project just try to do anything and it lags like crazy

**Comment by mausmedia** [comment]
I've been using Photopea for years and I haven't had any issues before. It's just been really annoying for a few weeks now.

**Comment by photopea** [comment]
Could you record a short video of how laggy it is, as a proof?

**Comment by photopea** [comment]
Also, could you press More - PeaMark, and tell us the results of your PeaMark test?

**Comment by photopea** [comment]
I have to close it because the pesron did not respond :(
