### ISSUE TITLE
Photopea App Lags Bigtime

### ISSUE THREAD

**Issue by Rakesh19-Ruhin** [photopea/photopea#6993]
Using any Selection tool or Switching between tools after opening and placing image, the app just dosent move at all!!!
I just discovered the app and super excited to see a Photoshop Alternative but we need to work hard to improve basic operations quickly!!

Secondly the Side bar needs attention as pop ups blanket the entire are and is difficult to manouvre in the space!!!

Regards

Rakesh Raina

**Comment by photopea** [comment]
Could you record a short video of the lag? 

Or the "pop ups blanket the" - what it means and what it looks like?

**Comment by cyberphantinja** [comment]
so every time i load up photopea its about 37 or 40 second before it completely freezes

**Comment by photopea** [comment]
Please, write a new issue and fill out the issue template. It is unclear whether your file is 2 MB or 2 GB. Whether you do it on a 20 USD phone on a 20K USD desktop.

**Comment by Rakesh19-Ruhin** [comment]
https://github.com/user-attachments/assets/66c84f98-e18b-414f-9127-d1153b19c5ab

**Comment by photopea** [comment]
What is the resolution of your image in pixels? Is it more or less than 100 million pixels?

The quick selection tool is quite complex. It can process about 4 million pixels per second. So with 100 million pixels, the image analysis might take up to 25 seconds :(

Do you really need so many pixels? Have you thought about resizing it e.g. to 8 million pixels?

**Comment by photopea** [comment]
I have to close it, because nobody is responding :(
