### ISSUE TITLE
Behavior not expected while sliding

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#6994]
![1](https://github.com/user-attachments/assets/c790cfa0-14d0-450a-9ed7-56422154c1a4)

Sliding on some items triggers windows or menus. This is not expected. Even worse, it might block scrolling.

Could these windows and menus only be triggered by a real tap, as we do when we want to trigger them?

**Comment by photopea** [comment]
I think most of users like when the menu opens on pressing a mouse down, not after releasing it. It works in other programs this way.

You should move the menu by tapping it on some "unopenable" places.

**Comment by photopea** [comment]
I think we should keep it as it is. Try to drag it without hitting buttons.
