### ISSUE TITLE
Actions have issues like not storing move selection.

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#6996]
Hello Dear,

Open any image, we are using only one layer that is default (Background)

I use Windows --> Actions, in that created new action.. start record..

Now just Select any part of image using Rectangle Selection.
Click Arrow, and Move selected part..

try 2nd selection and move it to other place (Keep in mide, we are workin in same layer)

Stop Recording of Actions..

then undo till all steps, then try to run Actions...

its not working as expected...

Thanks.

I am using Linux and Opera Browser.

**Comment by Mayur-hot** [comment]
![Screenshot_2024-07-25_15-23-06](https://github.com/user-attachments/assets/ec9656cd-121e-473e-88b3-04e356f8a679)

**Comment by photopea** [comment]
Hi, you should be able to record this action now.
