### ISSUE TITLE
Wrong menu 

### ISSUE THREAD

**Issue by KariiiHome** [photopea/photopea#6997]
![Anmerkung 2024-07-25 141728](https://github.com/user-attachments/assets/201bebc5-50af-4d78-9446-e7fdeac08fe5)
Your Operating System: Windows 10 
Your Web Browser: Chrome Google 
The problem happens in the Incognito Mode, too: no

**This must be done to see the problem**
1. Go to www.photopea.com
2. click on file, then you see the wrong categories (germn only)
![Anmerkung 2024-07-25 141728](https://github.com/user-attachments/assets/8c325ce1-7398-4b14-87b2-e0462a9d6a42)

**Comment by photopea** [comment]
To use Photopea in a German language, you should click More - Language - Deutsch.

I think you are using Photopea in English, but you told your web browser to translate it for you, instead of using our official German version.

**Comment by photopea** [comment]
I have to close it because the pesron did not respond :(
