### ISSUE TITLE
Files reopen after closing app

### ISSUE THREAD

**Issue by liquidbinary** [photopea/photopea#6998]
Your Operating System: Win11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: No

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
![New Project](https://github.com/user-attachments/assets/00e3a363-767b-4c99-be62-f2add8a62611)

3. .... After closing all of the files, closing the photopea window and reopening it, it reloads every single file from all previous projects. Clearing browser data is not helping.
4. ....

**Comment by photopea** [comment]
Try this: https://www.photopea.com/tuts/photopea-opens-up-old-files/

**Comment by liquidbinary** [comment]
Tried multiple times. Not working :(( Trying again.

**Comment by liquidbinary** [comment]
Uninstalling it and reinstalling worked. Also deleting all of the data when
prompted during uninstalling.

**Comment by photopea** [comment]
Turning off all plugins will not help. You need to turn off plugins AND THEN close all documents in Photopea with your mouse. Just like the article says.

**Comment by liquidbinary** [comment]
No shit.

**Comment by liquidbinary** [comment]
And I just told you that process didn't work. I tried it more than 5 times
so I finally just uninstalled it and reinstalled it and it fixed it.

**Comment by photopea** [comment]
What did you uninstall?

**Comment by photopea** [comment]
Sorry, I will not respond to people who curse in their communication.
