### ISSUE TITLE
Fonts missing

### ISSUE THREAD

**Issue by Studioartcz** [photopea/photopea#70]
Hi,

can you add font family "Museo"? Thanks

**Comment by photopea** [comment]
Hi,

Museo font does not seem to be "free"

https://www.fontspring.com/fonts/exljbris/museo?utm_source=fontsquirrel.com&utm_medium=download_link&utm_campaign=Museo#firstfreeproduct

And I couldn't find a place, where it was free to download, without having to sign in.

**Comment by Studioartcz** [comment]
no, is free - https://www.fontsquirrel.com/fonts/Museo

**Comment by photopea** [comment]
Did you manage to download it without making an account? FontSquirrel just redirects to the official site.

**Comment by Hextvideo** [comment]
Hi,
Can you add Cyrillic font "Algerian Regular"? It's free:
https://ofont.ru/view/4302
Thanks

**Comment by photopea** [comment]
Do you really need it? I think it is an old font and it is not used in PSDs anymore.

**Comment by Hextvideo** [comment]
Hi,I need it to update header on customer's site which has Algerian font on header and logo.Thanks
    On Saturday, March 10, 2018, 8:47:06 PM GMT+3, Photopea <notifications@github.com> wrote:  
 
 
Do you really need it? I think it is an old font and it is not used in PSDs anymore.

**Comment by Hextvideo** [comment]
Hi,Could you kindly update me on the issue.Thanks
    On Sunday, March 11, 2018, 3:53:42 PM GMT+3, Evgeni Tchirskov <hextvideo@yahoo.com> wrote:  
 
  Hi,I need it to update header on customer's site which has Algerian font on header and logo.Thanks
    On Saturday, March 10, 2018, 8:47:06 PM GMT+3, Photopea <notifications@github.com> wrote:  
 
 
Do you really need it? I think it is an old font and it is not used in PSDs anymore.

**Comment by photopea** [comment]
@Hextvideo Hi, you can load your font manually into Photopea using File - Open. I think there is no need to blindly add all free fonts into Photopea. What do you think?
