### ISSUE TITLE
Locking layers

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#700]
In others graphic programs (photoshop, gimp, illustrator) there are ability to lock the layers with padlock icon.
In Photoshop and Gimp, there are more options of locking (position lock, pixel lock etc). If I good remember this options was even in old version of photoshop.
https://helpx.adobe.com/photoshop/using/moving-stacking-locking-layers.html#lock_layers

But in Photopea will be good if you add simple layer locking with padlock icon to lock all. 
If there will be "lock all" function, you can add this icon next to eye icon on layers (like in Illustrator).

**Comment by photopea** [comment]
I don't think so much people use this feature. Also, locking transparency would require a change in each drawing tool. It would also make the top part of Layers panel bigger, so there would be less space for layers.

**Comment by MichalSZZ** [comment]
Ok, I will prepare for you projects, with situations, where there are big problems with editing without the lock function. Then you will decide, if it is necessary or not. I talk only about lock all layer funkction. In 99,9% of my work I don't need transparency lock or position lock separatly. I need only padlock icon, to block the layer from accidental selection with auto select function. That all :)

**Comment by MichalSZZ** [comment]
I made a file, that work like a crap in Photoshop (selecting layers with autoselect tool on artboard is horrible), but... in Photopea it works much better (not perfect but smarter). I don't have arguments for my request at that moment :)
[locking-layers.psd.zip](https://github.com/photopea/photopea/files/2065482/locking-layers.psd.zip)

**Comment by MichalSZZ** [comment]
Approach number 2 :)
1. Download this file:
[lock-layer-v2.psd.zip](https://github.com/photopea/photopea/files/2070149/lock-layer-v2.psd.zip)
2. Try to make any paragraph text layer on that background (made from letters).

Yes, I know - it could be a smart object as a background or flat (rasterized) layer and there wont be a problem...

**Comment by photopea** [comment]
Yes, it sucks, when you want to add a text layer on top of another, because the one in the back gets selected.

If you want to "lock" the text layer in the back, so it is not selected ... you could also temporarily hide it, right? Clicking the Eye is as hard as clicking some lock.

**Comment by MichalSZZ** [comment]
Yes, you are 100% right in that case.

**Comment by rocifier** [comment]
I never really need to lock layers myself, but I constantly use transparency lock when painting in photoshop. It's the thing I miss the most trying to use photopea for photo bashing.
