### ISSUE TITLE
Vanishing Point Filter doesn't work

### ISSUE THREAD

**Issue by PepeRod** [photopea/photopea#7000]
Your Operating System: Windows 11
Your Web Browser: Microsoft Edge / Google Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Clic on a normal picture
3. Go to Filters> Vanishing Point
4. Add one layer, add the second one (a box)
5. Now you cant edit the corners of any layer. You can't add a picture neither.
[Grabación de pantalla 2024-07-25 111906.zip](https://github.com/user-attachments/files/16381601/Grabacion.de.pantalla.2024-07-25.111906.zip)

**Comment by PepeRod** [comment]
[Grabación de pantalla 2024-07-25 111906.zip](https://github.com/user-attachments/files/16381597/Grabacion.de.pantalla.2024-07-25.111906.zip)

**Comment by photopea** [comment]
I did your five steps, but everything works fine.

In your video, you have a document with two layers. Which does not correspond to "clic on normal picture".

**Comment by PepeRod** [comment]
I made another try with a new image without any layers and it still doesn't work. Neither the capability to move the corners nor the capability to paste the image above the object. When I clic CTRL + V to paste, it appears a message saying that I need to close that window first.

Thank you for your fast reply.

[Grabación de pantalla 2024-07-25 114953.zip](https://github.com/user-attachments/files/16381882/Grabacion.de.pantalla.2024-07-25.114953.zip)

**Comment by photopea** [comment]
This is how it should work. This is how it works in Adobe Photoshop. 

After you draw a plane perpendicular to another plane (two related planes), you can not drag corners anymore. You can only drag sides.

Please read our article about it: https://www.photopea.com/learn/vanishing-point or get any book about Adobe Photoshop.

**Comment by PepeRod** [comment]
In Adobe Photoshop, you can adjust the corners of the second and third
layers to align with the image (in this case, the box) if the default
direction is incorrect. Simply expanding the layer without modifying the
direction isn't possible. Additionally, you can paste an image while the
window is open to place it in the layer, but that function is not working
in Photopea.

I have already read the article, which states, "You can drag corners of a
main plane (as long as it has no adjacent planes)," but this doesn’t work
for me. That is what I am trying to explain. I hope I’m explaining this
clearly.

Thank you very much for your response.

**Comment by photopea** [comment]
I think Photoshop did not have this feature in the past. When they move a corner of one plane in your video, a corner of the first plane si moving slightly, too. We dont have this feature in Photopea at the moment :(

**Comment by PepeRod** [comment]
I understand, thank you. However, the function of pasting the image inside the layer isn't working. Is that normal? How do uou paste the image inside the box so that it fill the layer?

Thank you again for your answer.

**Comment by photopea** [comment]
You should select a plane and press Ctrl+V.

**Comment by PepeRod** [comment]
Yes, exactly that function is not working. When you click CTRL + V, there
appears a message saying that you must close the window before.

**Comment by photopea** [comment]
Could you try it in the Incognito window? I just tried it in Chrome and it works fine.

**Comment by photopea** [comment]
Could you try it in the Incognito window? I just tried it in Chrome with no browser extensions and it works fine.

**Comment by PepeRod** [comment]
I tried again in the normal browser and now I could paste the image. But I still find weird that you can't edit the perspective of the layers to fit the real surface of the box.

![image](https://github.com/user-attachments/assets/05997813-ec62-4758-89fb-35df588f41ac)


Thank you.

**Comment by photopea** [comment]
This means that your photo was probably cropped. If a center of a photo is not a point to which the camera was pointing, it is not possible to deduce 3D parameters.

**Comment by PepeRod** [comment]
I understand but that´s not the case, the image wasn't cropped. I have tried with different pictures and the 3D parameters are always unaccurate. I  stilll believe that is an error.
![611tLb84mWL](https://github.com/user-attachments/assets/27593bf3-fee9-4409-98c2-8bf88653b2d8)

**Comment by photopea** [comment]
Can you do what you want in Adobe Photoshop? The bottom left edge of your box is not a straight line, so I am not sure if it is possible to get a meaningful result with the Vanishing Point Filter in your case.

**Comment by yikuansun** [comment]
I think there is something wrong with your image. The lines don't intersect at the same place.
![New Project (1)](https://github.com/user-attachments/assets/ad2d5705-543b-40a8-b06b-bc742b069f86)
My guess is that it was shot on a distorted lens or distorted in the edit.

**Comment by photopea** [comment]
I will close it now. If you can not draw a proper model, it means that a photo was cropped, or corners are not 90 degrees.
