### ISSUE TITLE
Uninstall Plugin Remains there, need to Reload page..

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7001]
Hello Dear, thanks for solving Action issue.

Install Plugin... for e.g. Dezgo Text-to-Image

Now we see icon in right panel.. but after uninstall it, icon remains there..

so we have to refresh/reload page to remove it. otherwise uninstall just removes, but still interface shows that.

I can install plugins, and interface shows that, but uninstalling has no effect on inerface..

**Comment by photopea** [comment]
If you have a Photopea account, you need to uninstall it and wait five seconds, until it is saved to our server.

If you dont have a Photopea account, it is uninstalled immediately.

**Comment by Mayur-hot** [comment]
I tested it without account.. and it remains there forever.

**Comment by photopea** [comment]
could you show me a video of how you uninstall it?

**Comment by Mayur-hot** [comment]
No Login Mode:

Steps:
Open any file...

Windows --> Plugins --> Install Dezgo Text-to-image

Install success, and left side we see
INSTALLED (1)

Now close plugins window..

and goto main interface, we see new icon of plugin right side.

now Again goto Windows -> Plugins
Click on Installed (1), and it lists all installed plugins.
and from that list, uninstall it.

Now Installed (0) will be there, and now exit from plugin window.

and we have main interface.. but waiting for 1 min.. till that plugin icon remains there... + works toos.

**Comment by Mayur-hot** [comment]
![1](https://github.com/user-attachments/assets/cda3dc5a-e082-477e-8153-3ce7f5ce7d74)
![2](https://github.com/user-attachments/assets/0235e982-54e3-460f-8d6b-79395550cc3e)
![3](https://github.com/user-attachments/assets/5527609f-ae9c-4d9e-841e-1850d5795f4b)

after clinking uninstall outer interface reamins same as first image.. plugin in icon not removed..

My Video goes beyong 10MB, so I am trying to explain using 1,2,3 screenshots. 4th = 1

**Comment by photopea** [comment]
"Installed" means, that these plugins will be loaded when Photopea starts.

Just close Photopea and it will not be loaded next time Photopea starts.
