### ISSUE TITLE
A lot of bugs

### ISSUE THREAD

**Issue by Itsaproblem** [photopea/photopea#7002]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by Itsaproblem** [comment]
There's always some new bug every time, but this one is insanely annoying: Can't rotate - anything! It first won't allow it, and then, if it does, it literally cuts off a piece of the image and rotates only that. Also, trying to rasterize something is almost always a ridiculous pain in ass

**Comment by photopea** [comment]
We have had 1 million users in the last 24 hours and nobody reported any problem. I think a problem is on your side. Please, try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it because the person did not respond :(
