### ISSUE TITLE
Team Setting is Blank or no message

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7004]
![Screenshot_2024-07-27_15-24-11](https://github.com/user-attachments/assets/37ead12a-4de3-46af-8b35-f47057c30394)
Hello Dear,

I sent a screenshot, and see nothing inside team settings.

Is it Under Development? or Work is in Progress?

**Comment by bluep55** [comment]
You need to log in with an account first. That info will then show up.

**Comment by Mayur-hot** [comment]
Then some kind of message must be there, like please login to show/create/manage team,

right now no message, so its looks like Under Developemnt, so need to Show Message for Free Users

**Comment by photopea** [comment]
I have fixed it, there is a message explaining it now.
