### ISSUE TITLE
photopea creation not saved

### ISSUE THREAD

**Issue by preetkahlonx** [photopea/photopea#7005]

**Comment by photopea** [comment]
Hi, how can I help you?

**Comment by camoody1** [comment]
@preetkahlonx Did you mean to delete your original message?

> Hi, im writing because i have had a lot of issues with photoshop as i saved something and it wont let me open and is coming up wiyh file has 0 bytes and is making me go through pixillion to purchase it. Because of this my homework is late and my time has been wasted as i will have to start again. Please fix this issue and get me my creation back.

What is "pixillion"? Make sure you aren't going through some weird site to use Photopea. You should only use Photopea through the site www.photopea.com .

**Comment by photopea** [comment]
I have to close it, because nobody is responding :(
