### ISSUE TITLE
You can't edit now on photopea, files & editing isn't working

### ISSUE THREAD

**Issue by anniebooboos** [photopea/photopea#7006]
Your Operating System: Chromebook
Your Web Browser: google chrome
The problem happens in the Incognito Mode, too: yes

you can't use the sections file, edit, image, layer, select, filter, view, window, more at all, doesn't let you click on it. you can click on the other side tabs though (the one with about, report a bug, learn, blog, api) 
![oie_9qgAbhjRmXr7](https://github.com/user-attachments/assets/e90d5a1e-4fea-460a-bd6c-9df5f3a878ff)

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by iritu** [comment]
same problem

**Comment by photopea** [comment]
osrry guys, it should be fixed now.

**Comment by anniebooboos** [comment]
Thank you lots! <3
