### ISSUE TITLE
Scripting: how to open Free Transform dialogue?

### ISSUE THREAD

**Issue by yikuansun** [photopea/photopea#7008]
Hi Ivan, hope you are having a good day. I was just wondering if there is a way to open Free Transform through a script (same as pressing Alt+Ctrl+T)? I understand that you can use `translate` and `rotate` to make specific transformations, but I just want to open the dialogue for the user.

Basically, I like how `app.open` automatically opens the Free Transform dialogue when `asSmart=true`. I am using `app.open` but immediately changing the blend mode of the image after it is opened, so the Free Transform dialogue disappears.

**Comment by photopea** [comment]
What is a Free Transform Dialogue? Do you mean switching to the Free Transform tool? It is a tool, just like the Crop tool. What dialogue do you mean?

**Comment by Mayur-hot** [comment]
Open Image,

select a part of image to transform, then
Press V or Move Tool,

Then select "Transform Controls" checkbox,

you can use Shift key and for free transform use Ctrl keys + mouse.

**Comment by yikuansun** [comment]
> What is a Free Transform Dialogue? Do you mean switching to the Free Transform tool? It is a tool, just like the Crop tool. What dialogue do you mean?

@photopea I guess, yeah, just switching to the Free Transform tool. I essentially just want to open the options the user would see when pressing Alt+Ctrl+T.

**Comment by Mayur-hot** [comment]
Just use Menus to get Transform dialog/tools,,

Select --> Transform Select

**Comment by photopea** [comment]
Could you find a script for this, that works in Adobe Photoshop? If it does not work in Photopea, I will take a look at it.

**Comment by yikuansun** [comment]
I don't own Photoshop :( so probably not.

I will close this for now, but I'd appreciate it if anyone else knows a script for it.

**Comment by photopea** [comment]
I have found this solution, it works well in Photoshop and in Photopea: https://community.adobe.com/t5/photoshop-ecosystem-discussions/starting-free-transform-from-a-photoshop-jsx-script/m-p/10437814

```
var cTID = charIDToTypeID;

var desc1 = new ActionDescriptor();
var ref1 = new ActionReference();
ref1.putEnumerated(cTID('Mn  '), cTID('MnIt'), cTID('FrTr'));
desc1.putReference(cTID('null'), ref1);
executeAction(cTID('slct'), desc1, DialogModes.NO);
```

Note that if you run it from a Script window in Photopea, it will not work, because the Free Transform tool can not be enabled when some window is opened.

**Comment by yikuansun** [comment]
@photopea Awesome!!! Thank you so much!
