### ISSUE TITLE
Hold ALT + Last Filter does not show the options (like Photoshop)

### ISSUE THREAD

**Issue by DirkBoer** [photopea/photopea#7009]
Your Operating System: Windows
Your Web Browser: Chrome  (but probably all)
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open random file, apply a filter, like Radial Blur
3. Holding ALT while clicking Last Filter just applies the filter. In Photoshop this would open the settings window of that last filter (including the settings used), so you can easily make small tweaks.
4. Not critical, but this would be nice addition to Photopea for convenience and easier adapting.

**Comment by photopea** [comment]
I have implemnted it.

**Comment by artemetra** [comment]
is there a way to disable this behaviour? for my projects I used to be able to do Alt+Ctrl+F to just reapply the same filter repeatedly without changing the options, but now i have to press Alt+Ctrl+F and click "Ok" on the options, which really slows the process down.

**Comment by photopea** [comment]
I am afraid that there are more people who want ot see the filter window than people who want to re-apply the last filter without changing the options.

But you should be able to click Enter on your keyboard instead of clicking the OK button with the mouse.
