### ISSUE TITLE
Switch to smaller icons on toolbar

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#701]
You can add an option to switch to smaller icons on toolbar to fit on lower screen resolutions without second vertical line.
In my situation on laptop (macbook pro with retina display - 1280x800) I have foreground and background color picker in new column on toolbar.
It can be made with auto-switching (basing on user resolution) or that can be an option to choose, like as theme switching at the start.

**Comment by photopea** [comment]
Hi, Photopea is prepared to work well with a browser zoom (that you set in a browser menu), it will adapt accordingly.  Many people (on hi-dpi screens) mind the large UI, so this is the way to go.

But I don't know how to let people know, that they can "zoom out" in their browser???

**Comment by MichalSZZ** [comment]
Zooming in and out in browser makes many problems for users (trust me :) ).

In new Gimp you can switch to various size of UI. https://www.gimp.org/release-notes/gimp-2.10.html
My Photoshop have smaller icons and fit perfectly to my resolution (with more icons in toolbar).

**Comment by photopea** [comment]
Did you try to zoom in in a browser? It does not cause any problems in Photopea (trust me! ) :)

**Comment by photopea** [comment]
I recommend to reload Photopea after you zoom in (browsers usually remember Zoom settings for each domain, you change it only once). I wish there was some way I could manipulate browser zoom from the app.

**Comment by MichalSZZ** [comment]
...or you can auto change icon size to a little bit smaller, like in RWD layouts. 
In CSS you can use mediaqueries to change like something looks like on diferent resolutions/devices.
https://www.w3schools.com/css/css_rwd_mediaqueries.asp 

Now I think about that what you wrote. Maybe change of viewport in JS? It is possible? (i'm not a webdeveloper but I think it is)
<meta name="viewport" content="initial-scale=0.9">
https://www.w3schools.com/css/css_rwd_viewport.asp

**Comment by photopea** [comment]
Ok I made the toolbar scale, when the window is smaller.

**Comment by MichalSZZ** [comment]
You rock!
Thank you very much! That's what I wanted.
