### ISSUE TITLE
Fonts not loading

### ISSUE THREAD

**Issue by N00BISINURGAME** [photopea/photopea#7011]
Your Operating System: PC
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Agree

My fonts that I uploaded are not loading

**Comment by photopea** [comment]
When you load it, do you tell Photopea to save it in the Local Storage, or you refuse it?

Maybe there are too many files in your Local Storage, and your web browser does not want to allow Photopea to save one more file. Look into Edit - Local Storage, and delete some items. Or simply tell Photopea not to save it to a Local Storage.

**Comment by N00BISINURGAME** [comment]
https://github.com/user-attachments/assets/97d910be-c859-4f42-ad7c-d56f13fc7786

I deleted some stuff in my storage

**Comment by photopea** [comment]
The font Syncopate is already in Photopea, so if you load a TTF file of an existing font, it will be completely ignored.

Why dont you simply choose Syncopate from the font list? Fonts are ordered in the alphabetical order. Or type "synco.." into the font search.

**Comment by photopea** [comment]
I have to close it, because nobody is responding :(

**Comment by phpguru** [comment]
Happens in Electron App also, Mac OS. I will see if there is a newer version.

**Comment by photopea** [comment]
What happens? What is an Electron App?
