### ISSUE TITLE
Adapting windows to the phone screen

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#7012]
When using Photopea on a phone, many windows exceed the width of the screen, making it difficult to close the window, click the “OK” button, etc.

I tried limiting the maximum window width to 100vw and then moving the right button to the bottom. All windows fit nicely on the screen, except for the “Layer Style” window, which needed some extra tweaking.
![compare](https://github.com/user-attachments/assets/1a1e9a6d-b65b-418b-9250-365261e7a6a2)

**Comment by photopea** [comment]
I have implemented it! :)
