### ISSUE TITLE
Cannot open AI files

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#7013]
Your Operating System: chromeos
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open these files
[Archive.zip](https://github.com/user-attachments/files/16431223/Archive.zip)

I cannot open them.
![image](https://github.com/user-attachments/assets/9d93be19-9c6d-40c3-9668-e4750966425d)

**Comment by photopea** [comment]
thanks it is fixed now.
