### ISSUE TITLE
Smart objects do not respect the fusion mode of shadows

### ISSUE THREAD

**Issue by PepeRod** [photopea/photopea#7014]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Visit www.photopea.com.  
2. Open a file with the desired background.  
3. Insert a Smart Object that includes a shadow layer set to Multiply Fusion Mode, or convert an image with the shadow to a Smart Object.  
4. The Multiply fusion mode for the shadow will be ignored, displaying transparencies as white.

[Grabación de pantalla 2024-07-30 113718.zip](https://github.com/user-attachments/files/16431572/Grabacion.de.pantalla.2024-07-30.113718.zip)

**Comment by photopea** [comment]
This is how it should work.

In all graphics editors, ONE LAYER can have ONE BLEND MODE, which means, that all pixels have the same blend mode.

A smart object is ONE LAYER.

If you want parts of your image to have different blend modes, you should have them in different layers, not in one layer.
