### ISSUE TITLE
Text don't show

### ISSUE THREAD

**Issue by DevilDG09** [photopea/photopea#7015]
![Captura de tela 2024-07-31 200736](https://github.com/user-attachments/assets/3a21ee95-713d-4033-8fef-9c65f589ef77)
Look, I'm using a black text, but if I change the color nothing happend, and I don't know what to do.

**Comment by DevilDG09** [comment]
I changed the font, but it didn't help. Sorry if I write wrong, it's because I'm Brazilian.

**Comment by Mayur-hot** [comment]
Press Ctrl+A, or select Text First, to change font color.
Font Color is available for Selected Text Only. so before changing color, you must select part of text ore Press Ctrl+A to select all text.

May be this wll help

**Comment by Mayur-hot** [comment]
![Screenshot_2024-08-01_08-40-45](https://github.com/user-attachments/assets/1e1466c6-f026-4886-ab02-99df1d619c5d)
see in this I select text... then choose color.

So, for any text effect like Bold, Italic you have to select text

**Comment by photopea** [comment]
Could you try it in the Incognito mode? You might be using browser extensions which break Photopea. Browser extensions are disabled in the Incognito mode.

**Comment by DevilDG09** [comment]
When This happen more later Its resolve, but I use app And no the Google, but this erro Go And Back sometimes

**Comment by photopea** [comment]
I do not understand what you are saying. Does Photopea work for you with no browser extensions?

**Comment by photopea** [comment]
I have to close it, because nobody is responding :(
