### ISSUE TITLE
I cant see the brush, though i need it for my thumbnail.

### ISSUE THREAD

**Issue by D1Z2YonVR** [photopea/photopea#7016]
Your Operating System: MacBook
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: I havent tried yet.

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by D1Z2YonVR** [comment]
I cant see the brush, though i need it for my thumbnail.

**Comment by D1Z2YonVR** [comment]
![Uploading Screen Shot 2024-08-01 at 4.38.13 PM.png…]()

**Comment by D1Z2YonVR** [comment]
if you look at the toolbar you cant see the brush

**Comment by D1Z2YonVR** [comment]
![Screen Shot 2024-08-01 at 4 38 13 PM](https://github.com/user-attachments/assets/bef597f9-be93-47be-b13e-3195b7dfee4e)

**Comment by D1Z2YonVR** [comment]
> I just opened Photopea and I can see the brush tool. Do you know how the toolbar works? Please, read our manual: https://www.photopea.com/learn/workspace 

![Screen Shot 2024-08-01 at 4 38 13 PM](https://github.com/user-attachments/assets/6a970883-e243-456a-a5f5-cdd648593567)

**Comment by D1Z2YonVR** [comment]
@photopea

**Comment by photopea** [comment]
Please, read our manual at https://www.photopea.com/learn/workspace .

The brush tool is in the same group with the clone stamp.

![image (1)](https://github.com/user-attachments/assets/64613881-7e6d-47d5-aa0f-44920ca6bd84)
