### ISSUE TITLE
there is no brush for me

### ISSUE THREAD

**Issue by D1Z2YonVR** [photopea/photopea#7017]
Your Operating System: MacBook Pro
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Haven't tried yet

**This must be done to see the problem**
1. Go to www.photopea.com
2. click new project
3. and i dont see the brush

**Comment by D1Z2YonVR** [comment]
i really need it for my thumbnail

**Comment by photopea** [comment]
Why do you report it twice?
