### ISSUE TITLE
how to i click the text

### ISSUE THREAD

**Issue by D1Z2YonVR** [photopea/photopea#7018]
Your Operating System: Macbook pro
Your Web Browser: chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. i cant move or size up the text but a video said to press alt t and i didnt work
3. ....
4. ....

**Comment by photopea** [comment]
Sorry, I do not understand what you are saying :(

**Comment by D1Z2YonVR** [comment]
i fixed it

**Comment by D1Z2YonVR** [comment]
but thanks anyway

**Comment by photopea** [comment]
I am glad you have fixed it.
