### ISSUE TITLE
corrective brushes

### ISSUE THREAD

**Issue by nekoanime** [photopea/photopea#7019]
when I use a concealer brush it corrects but it remains with a white spot, not the same as the color I want to correct.

**Comment by photopea** [comment]
What is a concealer brush? What should I do to see a problem which you describe?

**Comment by nekoanime** [comment]
![Captura de pantalla 2024-08-02 090218](https://github.com/user-attachments/assets/569ad127-5b14-456b-b607-b1abde7f30eb)
![Captura de pantalla 2024-08-02 090408](https://github.com/user-attachments/assets/3e934d29-dffd-43a7-ae3e-30063e045283)

**Comment by nekoanime** [comment]
> ¿Qué es una brocha para corrector? ¿Qué debo hacer para detectar un problema como el que describes?

![Captura de pantalla 2024-08-02 090218](https://github.com/user-attachments/assets/80e2a355-2373-44d9-89b0-4e10296b6085)
![Captura de pantalla 2024-08-02 090408](https://github.com/user-attachments/assets/18bd2032-e597-4044-a89a-7ba9d5a44772)

**Comment by nekoanime** [comment]
> ¿Qué es una brocha para corrector? ¿Qué debería hacer para detectar un problema como el que describe?

![Captura de pantalla 2024-08-02 090535](https://github.com/user-attachments/assets/9008f3b9-2cf7-41ec-b64d-ba2a562db967)
![Captura de pantalla 2024-08-02 090544](https://github.com/user-attachments/assets/122c62e3-1c36-44fe-a4ea-d65ed351cc4a)

**Comment by photopea** [comment]
The Spot Healing Brush tool does not always work as you wish. You can try to use the Clone Stamp tool.
