### ISSUE TITLE
Link two or more layers

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#702]
It is very helpful in big projects to link some of layers with each other.
After that, when you move or resize one layer that should be a group of elements (no need to group in folder), other layers move (resize, rotate etc) too.
It is a chain icon in graphic programs (but I think that you know it :) )
https://helpx.adobe.com/photoshop/using/selecting-grouping-linking-layers.html#link_and_unlink_layers

**Comment by photopea** [comment]
I guess you are going to add 1000 more issues, to make Photopea more similar to Photoshop. I appreciate it, but I am aware of all these things. I would rather add features, that are missing in other programs.

**Comment by MichalSZZ** [comment]
Ok, I understand that and very respect time, that you spent on developing this program.

> "I would rather add features, that are missing in other programs." 

Can you try to explain that on some example? 
I will try to not add issues, that are not match what you wrote.

**Comment by photopea** [comment]
Hi, it was implemented. It should work the same way as in Photoshop (and probably other programs). The info about linked layers is loaded from PSD and stored back into PSD.

**Comment by MichalSZZ** [comment]
Basically it works fine.
You have wrote "It should work the same way as in Photoshop"... :)
Do you want to know, how does it works in Photoshop, when you try to do something with one layer that is linked with others? 
For example, when you want to make smart object of one layer (that is linked), only this layer should be a smart object, not one big smart object with all linked layers inside. Same is for rasterising or creating shape from text layer, grouping, merging down etc.

**Comment by photopea** [comment]
Are you sure? I think "joining" the linked layers together is the expected result.

**Comment by MichalSZZ** [comment]
Yes I'm sure how that is work in Photoshop (tested that). But it is only your decision, how it should to work in Photopea :)
