### ISSUE TITLE
Not Working photoshop

### ISSUE THREAD

**Issue by white-tomato** [photopea/photopea#7020]
Your Operating System: Mac OS
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: not loaded a image to photoshop and dont created canvas for editing image
(((

**Comment by photopea** [comment]
Hi, I am very confused. Did you try to use Photopea in the Incognito mode? Are you talking about www.photopea.com ? We did not make any photoshop, that is the Adobe company.

**Comment by photopea** [comment]
I have to close it, because nobody is responding :(
