### ISSUE TITLE
Bug: pull-to-refresh works

### ISSUE THREAD

**Issue by treefrogman** [photopea/photopea#7021]
Your Operating System: Android
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com on a mobile browser.
2. Choose a part of the interface that does not already have interactivity that prevents using it as a drag handle: the Info panel is one of many examples.
3. Touch-drag the page down until the refresh amulet appears and charges. At which point, release it.
4. You will be prompted to confirm reloading the site.

I just created a test page with the `overscroll-behavior: contain;` property applied to the `body` element, and this successfully prevented pull-to-refresh.

**Comment by photopea** [comment]
I think many of our mobile users might be already using pull-to-refresh, so they expect it to work this way. Nobody ever asked for it to be removed.

**Comment by camoody1** [comment]
I would LOVE to disable the pull-down-to-refresh option if it could be applied exclusively to the photopea.com site. It would be wonderful if you could give us an optional to disable it if you think some people might want to keep it. I hate accidentally doing that.

**Comment by tuconeves** [comment]
The browser also bypass any refresh confirmation when pushing! I have to be really careful when editing on Android because of this.

**Comment by photopea** [comment]
okay, it should be disabled now.
