### ISSUE TITLE
Error opening exported PDF. Adobe cannot read the file

### ISSUE THREAD

**Issue by BemCasadosDanyDesign** [photopea/photopea#7022]
Win 11 Licence or Win 10 all original
Chrome , FireFox ... all of them Adobe cannot read the file
The problem happens in the Incognito Mode, too:

![Captura de tela 2024-08-03 084239](https://github.com/user-attachments/assets/68fc06d0-22e3-4b49-9c17-0fcd07e8b7f7)

**Comment by photopea** [comment]
Could you share your PSD file with us? You can attach it here as a ZIP. 
I would like to convert it to a PDF in Photopea myself, to see what is wrong with the PSD to PDF conversion.

**Comment by BemCasadosDanyDesign** [comment]
Yep, Tks for speed...

**Comment by BemCasadosDanyDesign** [comment]
Yep. and Tks for speed.....
[Nova Logo.zip](https://github.com/user-attachments/files/16480780/Nova.Logo.zip)

**Comment by BemCasadosDanyDesign** [comment]
At the Photshop, no Problem with this file .PSD when I export.. just and only in  PhotoPea

**Comment by photopea** [comment]
It should be fixed now. You should be able to export your document as a PDF file now.
