### ISSUE TITLE
Brush size when using raster masks acting weird

### ISSUE THREAD

**Issue by tuconeves** [photopea/photopea#7023]
Your Operating System: ZorinOS/Ubuntu
Your Web Browser: Chrome 
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open any image
3. Start editting raster mask changing brush size with     ´  /  [       keys
4. Photopea start acting weird in many ways: brush size continue to decrease on any key press; layers change positions down by its own when using " X " to change foreground/background colors

[Gravação de tela de 2024-08-03 12-02-52.webm](https://github.com/user-attachments/assets/da5d52d3-fa7a-4c41-9d27-f69abd26f22b)
On the end of the video its possible to see that the brush size keeps decreasing when pressing X to change colors.  It also move layers down, create copies, deselect raster mask and so on...

When it happens, all projects opened are affected, just reloading photopea solves the issue, and eventually it will happen again.
It happens so often that i could notice some patterns: it usually happens when **high res images** are being edited but not only; It seems to make ghost keypresses; Happens more often when editting raster masks, but not only.

This happens ever since I started use photopea (4y), seems so random that I couldn't find a way to reproduce it until now. I'm using a 16gb RAM machine.

**Comment by photopea** [comment]
I tried your steps, but I can not see any problem :(

Everything seems to work fine in your video. If the brush size is changing, but you are not pressing any keys, it is wrong. But I cannot see what keys you press in your video, to use it as a proof of a bug.

Does it happen for the main content of a layer, too? Or only for a mask?

**Comment by tuconeves** [comment]
It changes the whole photopea behavior. But what triggers the "keypress bug" most often are editing raster masks.

On my video, its possible to see the background and foreground colors changing when I press " X ". It's possible to see that this same key press also trigger the brush size down. What shouldn't happen.
After that, any key pressed change the brush size down. Until photopea reloads.

I'm going to record a video of my keyboard too. Coming back soon.

**Comment by photopea** [comment]
Can you see that problem happen when using a different operating system?

Maybe it is a bug of Ubuntu keyboard drivers.

**Comment by tuconeves** [comment]
Yes. It happened to me using windows, debian and android. But thought it was the browser limiting Photopea due to few resources on the other machines.

**Comment by tuconeves** [comment]
Keyboard recording: https://drive.google.com/file/d/1VNmZrSJpqut_O4q0-eJLDQJj-AT0CqPL/view?usp=sharing

The bar on the screen shows that the hardware was pressed just once, and photopea reacted like more than one key was pressed.
Just tested on MS Edge. Same happens.

**Comment by photopea** [comment]
I see that at 0:39 you are pressing X and a brush circle is getting smaller, which is wrong.

Could you tell me some steps, that I can do to see the problem myself, please?

I can not do what you are doing. You are opening a PSD which I do not have. Either give me your PSD, or create a PSD from scratch.

**Comment by tuconeves** [comment]
Sure! This is just an high res image that was inside another project as an smart object, and I saved as a PSD for this tests
But in my experience, it would happen with any large image

here it is www.photopea.com/#iVLD4YCvl

**Comment by photopea** [comment]
I tried to draw into a mask in your document, and tried pressing shortcuts, but I can not see any stragne behaviour :(

I am doing it on Windows. Are you sure it happens to you on Windows?

**Comment by tuconeves** [comment]
Unfortunately, yes :(
I don't have a windows machine to try it now, but i used to have to reload photopea hundred times a day because of this when editing logos and multi-artboards projects on internship. It was a Dell OptiPlex 7090. Changing layers positions and so on. (are there even a keyboard shortcut for this?)


I have some more work to do on this project i was on earlier. I'll try to create a windows VM and work on it from there.
Are there some stuff to look on console? Or something else i could catch?

**Comment by photopea** [comment]
Are you sure it happens when you have no browser extensions?

**Comment by tuconeves** [comment]
> Are you sure it happens when you have no browser extensions?

Yes. Freshly installed chrome (deb. and flatpak) and edge to test. 

I'll keep looking for it. This problem is really serious and happens on every machine i try.

**Comment by photopea** [comment]
Could you try to install an ad blocker? In case there is an ad which "steals" the focus.

**Comment by tuconeves** [comment]
> Could you try to install an ad blocker? In case there is an ad which "steals" the focus.

Haven't catch this notification. Sorry about that.

Tried an ad blocker, but nothing changes. Anyway, im able to reproduce the problem with some seconds of editing, pressing keys to change brush size repeatedly.

After the problem is triggered, just press ALT (to zoom) changes the layer selected, and CRTL (to move view) makes the layer change its position down.

[Gravação de tela de 2024-08-06 09-13-22.webm](https://github.com/user-attachments/assets/a3c02fd8-efd7-48c4-9984-480eee1c0026)

**Comment by photopea** [comment]
There are shortcuts in Photopea: see Layer - Arrange. Ctrl + ] and Ctrl + [  should move the layer up and down.

So Photopea thinks your Ctrl key is pressed. Do you know why?

**Comment by tuconeves** [comment]
Since i'm using the raster mask a lot for this projects, this worth to research a solution. And I got it!

Fortunately, this is **not a problem with photopea**.

I grab a keyboard tester online and could figure out that **only under chromium based browser** using latin keyboard (pt-br,es, etc) layouts the browser holds for 1 press the keys used to change brush size on Photopea. (waiting for the letter to punctuate)

![image](https://github.com/user-attachments/assets/27cc8d52-0053-4c7c-a4e3-2e2d0fcb63fd)

Thus, it's not a Photopea problem, i think you could help me find the solution. Which library [or whatever] do Photopea use to grab key events on chromium? Google Docs use the exact same shortcut to increase or decrease spacing, and everything act as its supposed.

If you help understand it, With some more details on this key events i'm going to find more help to get a fix for chromium itself.

Closing it, since it's not related to Photopea. Thanks!

**Comment by photopea** [comment]
Could you just switch to an English keyboard while doing it? 

Also, there is about 50 ways to change the brush, e.g. Alt+right click.

**Comment by tuconeves** [comment]
Yes! Changing to en does the job!

**Comment by tuconeves** [comment]
I created a ticket on chromium issue tracker, if you want to follow the thread, or provide details on how photopea works

https://issues.chromium.org/issues/357905826
