### ISSUE TITLE
[Feature request] Export layers with individual settings

### ISSUE THREAD

**Issue by Baegus** [photopea/photopea#7025]
I think the "Export Layers" feature is great, but it could use some more love to make it more usable.

Would it be possible to implement previews and individual settings (for example: different quality for each layer with output preview, just like in the regular Export dialog)?

This is something that Photoshop does quite well, but its format support and compression is nowhere near as good as Photopea's (PP has amazing SVG and WebP support etc.).

Thank you for considering it!

**Comment by photopea** [comment]
I think we could add previews.

But what do you mean by different individual settings? What if there are 200 exported images? Do you want to have to set it to each image separately, no "global setting"?

**Comment by Baegus** [comment]
Well, ideally you would have both options. You could set global settings for all images (for example, WEBP with 100% quality), but then you could click on a preview of a single layer and adjust its settings separately (set a different quality level, for example).

**Comment by photopea** [comment]
It seems to be too complicated and I think it might scare away some users. Could you just put one layers into one PSD and other layers into other PSD, and export them separately with separate settings?

**Comment by photopea** [comment]
I have to close it, because nobody is responding.
