### ISSUE TITLE
Transparent layers exported with background when using artboards

### ISSUE THREAD

**Issue by tuconeves** [photopea/photopea#7028]
Your Operating System: Ubuntu
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com, create a new project, and add an artboard to it
2. Draw any shape or raster with alpha
3. Download the selected layer using the export layers tool or File > Export Layers
![image](https://github.com/user-attachments/assets/41b9805e-c068-420d-a487-e6ba1803af17)
4. File gets background anyway

Works as expected on projects without artboards. (or converting layers to smartobjects and exporting from there)

![image](https://github.com/user-attachments/assets/e278bca6-dbd2-47f0-a8aa-5c787c6438c6)

**Comment by photopea** [comment]
I think there are some people who might want to have an artboard background in this case. So I would end up switching it back and forth when someone reports it.

You can set the artboard background to transparent, would it be useful to you?

**Comment by tuconeves** [comment]
> You can set the artboard background to transparent, would it be useful to you?

Just tested to create a project with transparent background artboards, and the exported layer get the same white background. Even changing the background to Black or custom. Same results

**Comment by photopea** [comment]
You must set the artboard background in Window - Properties.

The Artboard tool lets you set the background for the next artboard, which you are going to draw.

![image](https://github.com/user-attachments/assets/e17db02f-fc3f-4d3a-90b2-0ade35e40892)
