### ISSUE TITLE
Unknow JSON file opened after login

### ISSUE THREAD

**Issue by tuconeves** [photopea/photopea#7029]
Your Operating System: Ubuntu
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com, login with my account, reload the page
2. A message bar shown at the top saying that an unknown JSON file was opened.
3. Logout doesn't fix it. **Clean app data fixes** until new login.

![After login or reload](https://github.com/user-attachments/assets/2c713aee-6cca-48a2-8106-ffb850d04594)

![image](https://github.com/user-attachments/assets/d5b49817-2a93-4fd2-af68-4c1785a21d6c)
![image](https://github.com/user-attachments/assets/dcdfd0e5-c626-445e-a132-c59d0e1fce49)

No more errors happens after that. Photopea works expectedly and it's just appears at start

**Comment by photopea** [comment]
Could you press Window - Plugins, and uninstall some weird plugins?

**Comment by tuconeves** [comment]
After removing a plugin named "????", the issue was fixed.
Thanks!
