### ISSUE TITLE
Converted Sketch to PSD, but won't open in PS.

### ISSUE THREAD

**Issue by aladingaljic** [photopea/photopea#703]
Hey, in 2 out of 6 converted Sketch files I get this error:
<img width="427" alt="skarmavbild 2018-05-04 kl 15 22 10" src="https://user-images.githubusercontent.com/12831611/39630280-2ee3097e-4faf-11e8-856a-a3e9eb6209ae.png">

What is the problem? :-)

**Comment by photopea** [comment]
Hi, can you please send us the Sketch file, that was wrongly converted, to support@photopea.com ?

**Comment by aladingaljic** [comment]
Sure!

**Comment by photopea** [comment]
Can you please tell me, which of the files are problematic? My internet speed does not allow me to download all four.

**Comment by aladingaljic** [comment]
Both of the Sketch files are problematic. The PSD files are just the converted ones from Photopea.

**Comment by photopea** [comment]
Could you try to separate the Sketch file into multiple smaller Sketch files and see, if these smaller files work? I don't have enough memory to open any of your Sketch files in Photopea.

**Comment by aladingaljic** [comment]
I can try. But these are already divided into smaller ones.

**Comment by aladingaljic** [comment]
I found the defective Sketch file, sent to your support email. Please have a look and tell me if you can see anything. Would appreciate it hugely.

**Comment by photopea** [comment]
The Sketch file is still too big for me. I have only 8 GB of RAM.  Could you please split your file into two smaller ones and see, if any of them is still broken?

**Comment by photopea** [comment]
I fixed the mechanism of loading large files. If the graphics take too much area, it is scaled down. You should be able to open your Sketch files now.
