### ISSUE TITLE
Using Artboard with Custom Color

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7030]
Hello Ivan,

Don't able to set Custom Color for artboard. no color dialog box..

Choose Background - Custom:  clicking on whitebox did nothing...

Thanks 
screenshot attached
![Screenshot_2024-08-07_09-52-25](https://github.com/user-attachments/assets/1ad75445-cdd5-4b9e-9017-105168120c19)

**Comment by photopea** [comment]
In the Artboard tool, you can set the background of future artboards, which you will draw.

To change the background of an existing artboard, press Window - Properties.

**Comment by Mayur-hot** [comment]
right, using Window - Properties, we can set the background of future artboards..

Thanks, now one suggestion related to top toolbar... art toolbar:
background: <Custom> <Color>

Can we have colorbox dialog by clicking <Color> same as we do in Window - Properties?

**Comment by Mayur-hot** [comment]
![Screenshot_2024-08-07_16-19-38](https://github.com/user-attachments/assets/1a68ab24-a896-4c50-bb5b-bde42b8e9bba)

**Comment by photopea** [comment]
wow, it is really strange that nobody reported it in the past. It is fixed now.

**Comment by Mayur-hot** [comment]
Ok, its working now..., No body reported and I just use for testing purpose and found this bug and you solve that too.. so Closing this issue.

Thank You Ivan
