### ISSUE TITLE
New Project with Artboard tick

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7033]
Hello Ivan,

Now we have issue of Artboard tool available on all other New Documents without ticking artboard.

So, onces, you create a document with artboard, close that and create 2nd new document without artboard tick, still, it has a artboard toolbar..

I have two suggestions, but need only one solution.

1) Either make artboard toolbar available for all normal documents, so user can draw at any time.
or else
2) Just remove art toolbar from New document without art (may be Multiple document, one normal, one with artboard...

I think 1st suggestion is better, and will show artoard toolbar for all

Thanks

**Comment by photopea** [comment]
What is an "artboard toolbar"?

The artboard tool can be used at any time, to create artboards in any document.

**Comment by Mayur-hot** [comment]
![1](https://github.com/user-attachments/assets/5ce9fda9-0666-4974-a956-596037a7f353)

**Comment by photopea** [comment]
There is no "artboard doc" and "no artboard doc".

Artboards can be added into ANY DOCUMENT at ANY TIME :)

**Comment by Mayur-hot** [comment]
Right, there is no "artboard doc", I mean here app.document or New Project with artboard selected while creating from main Home Page..., after click close button/Close Project, we again have home screen, and clicking New Project...

Ok, now I am saying that.. 

we have two tools: Artboard tool, Arraw tool (left side bar)

Suppose, we choose Artboard tool, then close project and create new project without ticking artboard, then we need arrow selected by default, right not it remains last selected tool..

and suppose we choose new project with artboard, then artboard (left sidebar) tool need to be selected automatically.

TODO:
means Arrow/Art tool selected by default accordingly based on New Project.

CURRENT:
for new project it shows last selected arrow/art for every new project.

**Comment by photopea** [comment]
I think creating a new document should not change your tool in a toolbar. If you select a tool in a toolbar, it stays selected, until you select some other tool.

**Comment by Mayur-hot** [comment]
Ok, that is fine.. So, I am closing this issue...
Thanks Ivan
