### ISSUE TITLE
Photopea on mobile browser zoom issues

### ISSUE THREAD

**Issue by podunktimes** [photopea/photopea#7034]
Your Operating System: Android
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Make a new project
3. The page is immediately enlarged causing Photopea to be barely usable

**Comment by photopea** [comment]
What do you mean by "enlarged"? Could you show me a screenshot?

**Comment by podunktimes** [comment]
> What do you mean by "enlarged"? Could you show me a screenshot?

![Screenshot_20240807_115105_Chrome](https://github.com/user-attachments/assets/6fabb097-4a18-40bb-ab87-6f4716624eeb)

**Comment by podunktimes** [comment]
If you can fix it ASAP I appreciate it. Sorry if bothering.

**Comment by podunktimes** [comment]
This happens especially when i make a larger canvas. 2500x2500. I have to zoom out just to see everything.

**Comment by donnietsunami** [comment]
experiencing some zoom in issues as well...cant scroll fully to the right once you start a project, and when you use search it renders the left side unsuable 
![Screen Shot 2024-08-07 at 1 36 45 PM](https://github.com/user-attachments/assets/77d92e7e-9e06-482d-afac-189382d46f98)
![Screen Shot 2024-08-07 at 1 37 11 PM](https://github.com/user-attachments/assets/bf1c8295-efee-44a9-9f43-9d7a97f55645)

**Comment by photopea** [comment]
Are you using Photopea at www.photopea.com ? What web browsers do you use?

I can not see these issues when I open www.Photopea.com

**Comment by podunktimes** [comment]
> Are you using Photopea at [www.photopea.com](http://www.photopea.com) ? What web browsers do you use?
> 
> I can not see these issues when I open [www.Photopea.com](http://www.Photopea.com)

1. Yes
2. Chrome

**Comment by photopea** [comment]
Did you change any settings in Chrome? Because Photopea looks a lot different on my Android phone in Chrome.

What version of Chrome is it?

**Comment by podunktimes** [comment]
> What version of Chrome is it?
Most recent. No settings changed.

**Comment by photopea** [comment]
Does it look wrong right after you load www.photopea.com? Or do you do something to make it look like this?

**Comment by podunktimes** [comment]
> Does it look wrong right after you load [www.photopea.com](http://www.photopea.com)? Or do you do something to make it look like this?

I make a new project and it does this. I have no idea why.

**Comment by podunktimes** [comment]
Uploading Screen_Recording_20240807_204227_Chrome.mp4…

**Comment by podunktimes** [comment]
Tried to send video. Did not work.

**Comment by podunktimes** [comment]
https://github.com/user-attachments/assets/f0a61574-fe7c-47ad-a41c-7dce16576e32

**Comment by donnietsunami** [comment]
FWIW my zooming issues, completly removing the left side tool bar, seems to be happening in only mozilla

**Comment by podunktimes** [comment]
b0ss plz

**Comment by photopea** [comment]
Did you install any browser extensions? Could you try it on a different phone?

No matter what I do, I can never see what happens in your case :( So I dont know how to fix it and if it can be fixed.

**Comment by podunktimes** [comment]
> Did you install any browser extensions? Could you try it on a different phone?
> 
> No matter what I do, I can never see what happens in your case :( So I dont know how to fix it and if it can be fixed.

No browser extensions.

Maybe it's a problem with the ads? It also seems to affect others on desktop as seen above me

**Comment by photopea** [comment]
Hundreds of thousands of people use Photopea on their phones every day. But nobody is reporting this problem. I can not see this problem on my device either. So I think it must be caused by "something" in your phone.

**Comment by podunktimes** [comment]
It works normally when i go fullscreen & then breaks when I exit. "**donnietsunami**" is having the same problem as me if you look above.

**Comment by photopea** [comment]
I think it for @donnietsunami it is caused by browser extensions. Just like here: https://github.com/photopea/photopea/issues/7035

**Comment by podunktimes** [comment]
I do not use extensions as they don't work on chrome mobile.

Have you tested while making sure "Desktop mode" is off?

**Comment by podunktimes** [comment]
Fixed it

**Comment by photopea** [comment]
How did you fix it?
