### ISSUE TITLE
Display is cut with a 1024x768 monitor

### ISSUE THREAD

**Issue by lemmings189** [photopea/photopea#7035]
Your Operating System: Windows 8.1
Your Web Browser: Mozilla Firefox 115.14.0esr

1. Take a 1024 x 768 screen.
2. Go to www.photopea.com.

Hello,
I know my setup is a bit old-fashioned, but could someone help me fix the display ?
That would be lovely !

Thanks a lot,
![image](https://github.com/user-attachments/assets/42bf9ff8-003e-49dc-9969-65868d9afddd)
![image](https://github.com/user-attachments/assets/5620e1c2-6aed-4c3a-b7b7-322065bfb59a)

**Comment by lemmings189** [comment]
Disable adblock fixes everything !!!

**Comment by photopea** [comment]
great!

**Comment by photopea** [comment]
you should tell the creators of your adblock about this problem.
