### ISSUE TITLE
Droid sangs falls が使えない

### ISSUE THREAD

**Issue by hh2233-pp** [photopea/photopea#7039]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....Droid sangs falls do not use
3. ....
4. ....

**Comment by photopea** [comment]
I can use the font "Droid Sans" in Photopea. But it does not contain any chinese letters. You should use the font "Droid Sans Fallback" for chinese letters.

**Comment by photopea** [comment]
I have to close it, because nobody is responding :(
