### ISSUE TITLE
pdf export changes image

### ISSUE THREAD

**Issue by pranaman** [photopea/photopea#704]
I have a psd, originally made in PS. Edited a text layer, saved as psd. 
Then, exported as pdf. The pdf looks very different than the psd.

![pp-flier](https://user-images.githubusercontent.com/1611829/39718995-25289366-51f5-11e8-9239-360086ab42c1.png)
[2018EHS-Cambridge.pdf](https://github.com/photopea/photopea/files/1981081/2018EHS-Cambridge.pdf)

Here is the psd I used: https://drive.google.com/open?id=1SIH3Op2_qOiSURjEIa9I6G3qloJdsl9u

**Comment by photopea** [comment]
Hi, storing text to PDF is quite hard. Photopea can not export fonts, text alignment and layer styles into PDF now.

I add an option "rasterize all" into PDF export. It will simply make a bitmap of the document and store it inside PDF. It will look 100% the same, as in Photopea, but text will not be selectable in PDF.

**Comment by photopea** [comment]
Look :) [2018EHS-Cambridge (1).pdf](https://github.com/photopea/photopea/files/2058026/2018EHS-Cambridge.1.pdf)

**Comment by pranaman** [comment]
Hey, looks great, sorry for the delay, thank you!
