### ISSUE TITLE
Crash when editing image

### ISSUE THREAD

**Issue by Plunnnnn** [photopea/photopea#7041]
Hello, I was playing around with a psd and the api you provide, and noticed that, if i ever open a new image and try to save the smart object, the layer crash and it tells me to contacts the support.

here's the code :
```
var l = app.activeDocument.layers.getByName('ImageSmartObject');
app.activeDocument.activeLayer = l;
executeAction(stringIDToTypeID('placedLayerEditContents'));
app.open("ArbitraryImageData", true, true); // I tried loading through Base64 and hosted file.
app.activeDocument.save();
app.activeDocument.close();
```
The error I have in the console : 
![image](https://github.com/user-attachments/assets/cb8fe859-600e-4ce4-8638-77bd83540c4f)

If there is any workaround that i could use/a fix, I would love to know !

edit: The issue even happen if you create a blank canvas with 1 smart object and try to edit it with the script.
edit2: The crash does not happen if we save manually.

**Comment by photopea** [comment]
I need to see the problem myself.

Could you give me your PSD that I can run your script on? I guess it must contain a layer "ImageSmartObject".

**Comment by photopea** [comment]
I have to close it, because nobody is responding :(
