### ISSUE TITLE
Can I revert to 8 bit mode?

### ISSUE THREAD

**Issue by Franklynne3** [photopea/photopea#7042]
Your Operating System: macOS Catalina
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too:

I have some psd mockup files that were working perfectly for me until (I believe) the upgrade to 16 bit mode. I think that this mode is too much for my computer.  The mockup files still work, but the software is lagging and I have to keep starting and stopping the application in between each mockup because the software freezes, whereas before I could change the files and create several mockups very quickly without having to start and stop the application in between each one. Is there a way to revert to 8 bit mode?
Thanks for the software. I am a subscriber,and Photopea has been a huge blessing to me in my work.

**Comment by photopea** [comment]
With a 16-bit mode, you need 2x more memory (both RAM and the GPU memory) to represent each pixel.

To change the mode, press Image - Mode - 8bit. At this point, both the 16-bit version and the 8-bit version are stored in history. Save it as a PSD and restart Photopea to free-up the memory and work only with the 8-bit version at this point.

**Comment by photopea** [comment]
I have to close it, because nobody is responding :(
