### ISSUE TITLE
photopea problem aug 11 24

### ISSUE THREAD

**Issue by arnold3214** [photopea/photopea#7044]
Your Operating System: windows 10 home
Your Web Browser: google chrome
The problem happens in the Incognito Mode, too: I don't know what that is

**This must be done to see the problem**
1. Go to www.photopea.com did that same problem
2. ....when I go to gallery nd click on a photo it says loading layer comes up but nothing to work on in main area
3. ....
4. ....

**Comment by photopea** [comment]
Here is how to use the incognito mode: https://support.google.com/chrome/answer/95464

We just need you to try using photopea without any browser extensions, which could be modifying Photopea.

**Comment by photopea** [comment]
I have to close it, because nobody is responding :(
