### ISSUE TITLE
the layer glitches when the effects is disabled

### ISSUE THREAD

**Issue by DryOfficial** [photopea/photopea#7046]
its so hard to describe it but here. [here is the psd (cant send it as a file so i putted it into google drive)](https://drive.google.com/file/d/1nFBcuOgAKdSWfI7CMYPkBMinwZ7-p_NA/view?usp=sharing)

https://github.com/user-attachments/assets/f76d62da-88ce-4488-84a5-a2a4adde6591

**Comment by photopea** [comment]
That is really strange. How did you create this layer?

**Comment by DryOfficial** [comment]
i added drop shadow and the layer is 40% opacity and 0% fill. i just woke up and the bug is still there but its bit different so i guess i did a bit of change.

![image](https://github.com/user-attachments/assets/2b771cb3-652c-4266-a5f2-e18b8f1c4e56)
![image](https://github.com/user-attachments/assets/09157a2f-2635-48e0-9449-c0bcf8ac4a1b)


https://github.com/user-attachments/assets/9bc7ab63-cc13-4ea3-bb29-dc797a210ec4

**Comment by photopea** [comment]
This happens becaue your layer has some crazy blend mode (it shows Normal, because it can not show the mode that you are using). Set the layers mode to Normal and it should work fine.
