### ISSUE TITLE
when i chose a template to work on it keeps on loading forever i decided to subscribe and its still giving the same issues since today i have not done any work

### ISSUE THREAD

**Issue by papaTkay** [photopea/photopea#7047]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Can you load e.g. this link? https://f000.backblazeb2.com/file/psdshared/70imObZ3

**Comment by photopea** [comment]
Also, in what country are you located? Maybe your government is censoring the internet.

**Comment by papaTkay** [comment]
I live in south africa

**Comment by photopea** [comment]
Can you download this file to your computer? https://f000.backblazeb2.com/file/psdshared/70imObZ3

**Comment by photopea** [comment]
I have to close it, because nobody is responding :(
