### ISSUE TITLE
Dezgo disconnected from Photopea account

### ISSUE THREAD

**Issue by silmoe** [photopea/photopea#7048]
Hi. 

Yesterday I added a Dezgo API key to my photopea user, but today it doesn't work anymore and it wont let me connect again with a new API key.

**Comment by photopea** [comment]
What exactly happens when you enter a key? BTW. it works only for Premium users, do you have a Premium?

**Comment by photopea** [comment]
Did you do it according to this article? https://www.photopea.com/tuts/get-unlimited-ai-inside-photopea/

Could you check if the API key is still there?

**Comment by photopea** [comment]
That is really strange. Could you show me a screenshot of the preferences window with the API key in it?

**Comment by photopea** [comment]
No. I mean the window in Photopea where you entered your API key.

**Comment by photopea** [comment]
Please, do not send emails to random github email addresses. Open Github.com and reply to us there.

**Comment by photopea** [comment]
Please, read this to learn how to insert the API key: https://www.photopea.com/tuts/get-unlimited-ai-inside-photopea/

**Comment by photopea** [comment]
Could you show me a website www.photopea.com with the Dezgo API key entered into it?

I think you are confusing "I have a key" button (in your screenshot) with a Dezgo API key, they are totally unrelated.

**Comment by photopea** [comment]
I believe if you read this article right now https://www.photopea.com/tuts/get-unlimited-ai-inside-photopea/ (I mean reading each word in it), you will understand the problem and you will be able to fix it right away.
