### ISSUE TITLE
Photopea resizing bug? 

### ISSUE THREAD

**Issue by SirMely** [photopea/photopea#7049]
Your Operating System: Windows 11
Your Web Browser: OperaGX never had this problem before.
The problem happens in the Incognito Mode, too: No, It worked fine in incognito mode.

**This must be done to see the problem**
What I did is fully in the video. 
When I close and reopen photopea it works fine for a little while and then the problem starts up again 

(Sorry file was 40mb but max is 10mb so view here for issue)
Video: https://drive.google.com/file/d/1jcSk3Tys1OAZL3Ro6IBDwkJ2Q4sBqLj0/view?usp=sharing

**Comment by photopea** [comment]
I think it is caused by your browser extensions.

Please, report only problems which happen in Photopea. After you allow your browser extensions to modify Photopea in any way they want, I think you can not call it Photopea anymore.

**Comment by SirMely** [comment]
Ah yes thank you I deleted some extenstions that I forgot were active and now Photopea works perfectly normal. Thanks photopea.

**Comment by photopea** [comment]
I think you should report this problem to the creators of your extensions. Users of these extensions should be aware of what these extensions do to Photopea and other websites.
