### ISSUE TITLE
Feature Request: Support for Exporting Images to .jxl Format

### ISSUE THREAD

**Issue by mateowoetam** [photopea/photopea#7050]
**Feature Request: Support for Exporting Images to .jxl Format**

I'd like to request the addition of .jxl (JPEG XL) as an export option. Since Photopea already supports opening and editing .jxl files, it seems inconsistent that exporting or converting other image formats to .jxl isn't possible. Adding this feature would enhance the workflow for users who rely on the advanced capabilities of the JPEG XL format.

**Operating System:**
NixOS

**Web Browser:**
LibreWolf

**Issue Present in Incognito Mode:**
Yes

**Steps to Reproduce:**

1. Visit [Photopea](https://www.photopea.com).
2. Open or create an image file in any format.
3. Click "Export As."
4. Notice the absence of an option to export as .jxl.

**Comment by photopea** [comment]
Our users open about 10 JXL files a day, and about a million JPG files a day. So I think nobody needs JXL export at the moment. You cant even use it in a browser, or upload it to any service.
