### ISSUE TITLE
Scripting: How to access background fill via script

### ISSUE THREAD

**Issue by architagrawal-fg** [photopea/photopea#7051]
Hi, Thanks a lot for this amazing tool... Quick noob question...

How can I access the background color of artboard in script?

Example:
I can see this color in UI
![image](https://github.com/user-attachments/assets/7a377717-f3d0-46f2-b8bf-0b367ce24d7c)

Here is a example PSD:
https://fuegocreativestorage.blob.core.windows.net/tmp/photopea-fig.psd

**Comment by photopea** [comment]
Could you figure out if it is possible in a script in Adobe Photoshop? We want to have the same scripting interface as Photoshop has.

**Comment by architagrawal-fg** [comment]
Wow.. thanks for quick respone...

The best I could find is: https://community.adobe.com/t5/photoshop-ecosystem-discussions/setting-artboard-background-to-transparent/m-p/12438432#M588224
To set up background color


Didn't found any direct way to access/change the color in artboard background color.

Sorry don't have Adobe Photoshop installed to test out the script... I completely use photopea :)

**Comment by architagrawal-fg** [comment]
![image](https://github.com/user-attachments/assets/0d7dacf9-3adb-4635-b1f5-48174b51bad2)

Also when experimenting.... I found there is a isBackground flag for artlayer... when I tried on photopea... it returned "bgrd" string for all the layers (including artboard or any others)... Is this expected behaviour ?

**Comment by architagrawal-fg** [comment]
Any updates on this on @photopea

**Comment by photopea** [comment]
Hi, it should be fixed now. "isBackgroundLayer" should return a boolean value now.
