### ISSUE TITLE
How do I install Beeref on Windows Laptop???

### ISSUE THREAD

**Issue by Rakesh19-Ruhin** [photopea/photopea#7052]
I have downloaded Zip file from Beeref.org and since then it has been a struggle!!!
I have tried all methods of Installation but it wont help!
Can anyone just advise???
Rakesh Raina

**Comment by photopea** [comment]
Hi, how is it related to Photopea?

**Comment by Rakesh19-Ruhin** [comment]
its not related to photopea!!
i just raised a  query???

**Comment by camoody1** [comment]
> its not related to photopea!! i just raised a query???

Hahahahaha 😂

**Comment by Rakesh19-Ruhin** [comment]
whats there to laugh??

**Comment by Rakesh19-Ruhin** [comment]
You I think should not be on this forum< rather than showing way forward u laugh????

**Comment by photopea** [comment]
Sorry, we can help you only with www.Photopea.com here.
