### ISSUE TITLE
Exported PDF will not attach the font

### ISSUE THREAD

**Issue by honzaprevratil** [photopea/photopea#7053]
Your Operating System:  MacOS
Your Web Browser:  Arc
The problem happens in the Incognito Mode, too: Did not tried

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create field with Text, I set that to Space Grotesk
3. Export file as PDF
4. Font is not embedded in PDF

[test-data.zip](https://github.com/user-attachments/files/16614167/test-data.zip)
- PSD file
- exported PDF vectorized - looks OK, but the text cannot be copied
- exported PDF as text - text can be copied, but looks like different font

**Comment by photopea** [comment]
Photopea can not export fonts into PDF files :( you can only vectorize or rasterize the text.

**Comment by honzaprevratil** [comment]
OK, thanks for the info. Will you consider this feature?

**Comment by photopea** [comment]
yes, it is in our todo list.

You can also create two copies of text layers, vectorize one and set another to transparent, to make it still selectable. Maybe we could do this automatically during our PDF export.
