### ISSUE TITLE
Photopea or Google erases images in PC, and freezes in laptop

### ISSUE THREAD

**Issue by anibalkohan** [photopea/photopea#7054]
Your Operating System: Windows
Your Web Browser: Google in the PC, Duck - Google in the laptop
The problem happens in the Incognito Mode, too: I don´t know...I signed first at this moment. Was I in Incognito Mode before?
OBSERVATION: I changed the name of the directory-source of images ("models" to "models zombification") while its images were in use in the PC. Silly, I admit, but because there was not a warning against it.

Then on, Google asked me whose account was (one of two possibles), Photopea malcfuntioned and there was a cascade of erasing those images, even if they were renewed. And now the laptop seems to be very slow or freezed.
Kind of "vendetta"? Just joking.

What must I do?

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Hi, I am very confused. What is "I signed first"? 

Is it related to Photopea? You are mentioning Google and some directory-source.

Can you do this again? We can not fix anything if you can not show us what you do to make this problem happen.

**Comment by photopea** [comment]
I have to close it, because nobody is responding :(
