### ISSUE TITLE
File Raw della Lumix S5 II non riconosciuti

### ISSUE THREAD

**Issue by Genialsky** [photopea/photopea#7055]
Salve, è possibile aggiornare il sistema per far si che Photopea riconosca i file Raw (RW2) della mia Lumix S5 II? Grazie

**Comment by photopea** [comment]
Hi, could you share your RW2 file with us?

**Comment by Genialsky** [comment]
Certamente.
 PANA0112.RW2
<https://drive.google.com/file/d/1J69Pi9I4goqQiFWAkf7dHCDbLaG6XgNp/view?usp=drive_web>

Il giorno mer 14 ago 2024 alle ore 18:18 Photopea ***@***.***>
ha scritto:

**Comment by photopea** [comment]
Could you send it to support@photopea.com ?

**Comment by Genialsky** [comment]
Fatto.

Il giorno mer 14 ago 2024 alle ore 19:06 Photopea ***@***.***>
ha scritto:

**Comment by photopea** [comment]
the structure of this RW2 file is not known to me, and i can not make Photopea open it :(

I recommend everyone to buy cameras which can store photos in open formats, such as JPG or DNG. Otherwise, you must rely on your manufacturer to provide you a software for opening their RAW photos.
