### ISSUE TITLE
Hi i have a problem when i open PeaDrive it said HTTP error 401

### ISSUE THREAD

**Issue by Wannabe0012** [photopea/photopea#7056]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Hi, does it say that the user secret is alredy generated? Could you tell me your email address in Photopea? You can see it after pressing "Account" at the top.

**Comment by photopea** [comment]
I have to close it, because nobody is responding :(
