### ISSUE TITLE
HTTP ERROR 401

### ISSUE THREAD

**Issue by Wannabe0012** [photopea/photopea#7057]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by Wannabe0012** [comment]
Why it doesn't load my work

**Comment by photopea** [comment]
Hi, how can I help you?

**Comment by photopea** [comment]
I have to close it because nobody is replying :(
