### ISSUE TITLE
Bug: Pasting an image on a plane in vanishing point

### ISSUE THREAD

**Issue by LasseKB** [photopea/photopea#7058]
Your Operating System: Pop!_OS
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Copy an image from somewhere
2. Go to www.photopea.com
3. Click New Project
4. Click Create
5. Go to Filter > Vanishing point
6. Create a plane
7. Deselect the plane
8. Press CTRL+V

Sometimes nothing happens, sometimes the message "Close the current window first." appears.
Notably, this issue isn't present when using the web browser "Ungoogled Chromium".

**Comment by photopea** [comment]
It should work in Firefox now.
