### ISSUE TITLE
Can not open a GIMP 2.10 file it hang or endless

### ISSUE THREAD

**Issue by Nuvendi** [photopea/photopea#706]
Here is the file I tried to open (tested both with Photopea in Firefox and Chrome):

1) Is the GIMP 2.10 file that only hang

2) Is the same floorplan but made in Photopea just to give an idea about the type of content

It would been great if GIMP files could be opened and as well saved ?
[Larsen original GIMP 2D.zip](https://github.com/photopea/photopea/files/1990365/Larsen.original.GIMP.2D.zip)
[Larsen FP 2D Photopea 2018-05-09.zip](https://github.com/photopea/photopea/files/1990366/Larsen.FP.2D.Photopea.2018-05-09.zip)

**Comment by photopea** [comment]
Hi, it was fixed and you can open your files in Photopea now. It even supports text layers, so you can edit the text inside XCF, or export it as PSD with text layers.

Maybe there are some other problematic XCF files. I started a discussion on Reddit: https://www.reddit.com/r/GIMP/comments/8mppjn/open_gimp_files_anywhere/ .
