### ISSUE TITLE
Lasso direct select would really help for selecting around shapes with a bend or curve.

### ISSUE THREAD

**Issue by MesaBlack** [photopea/photopea#7060]
I try to select the non-flat parts of a horn shape, and the select method is kinda rigid to be honest.

**Comment by photopea** [comment]
do you know that you can draw a rectangle around the points that you want to select? and then, hold Shift and draw another rectangle, just like you do with selections?

**Comment by bluep55** [comment]
To get accurate curves, try using the Path Tool.
