### ISSUE TITLE
Getting Freezed

### ISSUE THREAD

**Issue by wowsathish67** [photopea/photopea#7061]
Your Operating System: windows11
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: not tested

I have ben using for past one month without any issue but today it started freezing, Thanks.

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
What you do you after opening www.photopea.com to make it freeze? Maybe you started opening larger files?

**Comment by wowsathish67** [comment]
What is the maximum file size to use? 
After opening the photopea I put ice cubes to freeze :)

**Comment by photopea** [comment]
The limit is a size of your RAM. Could you press More - Peamark - test RAM size?

**Comment by photopea** [comment]
I have to close it because nobody is responding :(
