### ISSUE TITLE
Fonte não carregar 

### ISSUE THREAD

**Issue by SuzaneSG** [photopea/photopea#7062]
Boa noite!
Estou tentando carregar um arquivo que contém uma fonte, porém quando eu tento aparece a informação de "formato de arquivo desconhecido: "/* w", já tentei tanto pelo celular como também pelo notebook, contudo mesmo assim não carrega. 
![fonte não carregou](https://github.com/user-attachments/assets/901d9d20-c2b2-4800-8f64-d643487cf490)

**Comment by photopea** [comment]
Sorry, I speak only English :(

**Comment by SuzaneSG** [comment]
Good afternoon! I'm trying to load a file that contains a font, but when I try to load the information "unknown file format: "/*w" appears, I've tried both on my cell phone and on my notebook, but it still won't load.
![Screenshot_20240817-231926_Chrome](https://github.com/user-attachments/assets/409e11f7-5f85-4554-8b48-73f455abe592)

**Comment by SuzaneSG** [comment]
Good afternoon! I'm trying to load a file that contains a font, but when I try to load the information "unknown file format: "/*w" appears, I've tried both on my cell phone and on my notebook, but it still won't load.
![Screenshot_20240817-231926_Chrome](https://github.com/user-attachments/assets/61bef5e3-8f69-4b35-869c-db943d2a7da3)

**Comment by photopea** [comment]
I need to see it myself on my computer. Could you share your file and tell me what should I do to see your problem?

**Comment by SuzaneSG** [comment]
I need the entire alphabet in Portuguese, but with this letter from the file. Alphabet in Portuguese (A, B, C, D, E, F, G, H, I, J, k, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z)
this is the file👇
[Dirtyline36Daysoftype2022.zip](https://github.com/user-attachments/files/16665276/Dirtyline36Daysoftype2022.zip)

**Comment by SuzaneSG** [comment]
When I select all the letters or just one letter and then click on the "DejavuSans and load font" icon, this information appears that the file is unknown, and the letter is not converted to that letter in my file.

**Comment by photopea** [comment]
If you want to load a font into Photopea, load a TTF or an OTF file. Do not load ZIP files into Photopea.

**Comment by SuzaneSG** [comment]
I've already tried this format in OTF, but it still doesn't work, send it in zip as it is the only format that can be inserted in this comment.
![Screenshot_20240819-181800_My Files](https://github.com/user-attachments/assets/b4960e81-3a2f-46da-9a6c-aac31435f4cc)
![Screenshot_20240819-182137_Chrome](https://github.com/user-attachments/assets/51206b5b-c820-4f13-a684-627c28ffbd60)

**Comment by photopea** [comment]
Could you send me a font file which you are opening in Photopea? Your ZIP contains like 10 different files. E.g. there is a HTML file in your ZIP, Photopea can not open HTML.

**Comment by SuzaneSG** [comment]
Goodnight! Inside this file is the document in OTF, I saved this document on the drive to insert it into photopea, but it does not convert the letter in the font that is inside this document.
[Dirtyline-36Daysoftype-2022-00845049100.zip](https://github.com/user-attachments/files/16667097/Dirtyline-36Daysoftype-2022-00845049100.zip)

**Comment by photopea** [comment]
Your ZIP contains another ZIP, which contains many files (HTML, TXT, etc).

I will close this issue. Please, file a new issue and describe your problem properly in English. Also, ask someone to translate it for you, because your automatic translation is very confusing.
