### ISSUE TITLE
I got stuck and all my work couldn't be saved!

### ISSUE THREAD

**Issue by Zeetard** [photopea/photopea#7063]
Your Operating System: Chrome
Your Web Browser: Normal
The problem happens in the Incognito Mode, too: Normal

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
What does it mean? What should I do to see such a problem myself? 

If Photopea crashes because your battery dies, there still is a backup mechanism: https://www.photopea.com/tuts/photopea-opens-up-old-files/

**Comment by photopea** [comment]
I have to close it because nobody is responding :(
