### ISSUE TITLE
[Feature request] - save colors more permanently

### ISSUE THREAD

**Issue by mchristie** [photopea/photopea#7064]
I need to copy the right hex colours the my projects almost every time. Could these be saved indefinitely so this isn't needed?

I also seem to be approving cookies almost every time, maybe these are related.

It's allowed to store cookie consent for up to 12 months before asking again, so if the duration of cookies/consent to be extended that would be great.

**Comment by photopea** [comment]
Hi, I have implemented it properly in Window - Swatches.

If you define a new swatch, it should stay in Photopea even after closing and reopening Photopea.

Use a little triangle to define the current foreground color as a new swatch.
