### ISSUE TITLE
PNG RGB/16 bugs, corrupt images

### ISSUE THREAD

**Issue by voidastro4** [photopea/photopea#7065]
Your Operating System: Linux
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: Yes

When opening a PNG RGB/16 (rgba64) file, autotone does not function correctly, result is corrupt blown out image.

When applying an adjustment layer to such an image and then Automating it to other images, they all become corrupt in a different way.

Exporting the image directly works and photopea informs you it converted it to RGB/8.

**Comment by photopea** [comment]
I opened a 16-bit PNG image in Photopea and I pressed Edit - Auto Tone, and it modified the image, it does not look "corrupt" to me.

Please, write exact steps for me to follow, to see a problem. Maybe even share your PNG file.

**Comment by voidastro4** [comment]
I tried it on a different browser and the problem didn't occur. The browser with the problem is brave. I decided to just dedicate an instance of google chrome to photopea.

**Comment by photopea** [comment]
Please, report it to Brave as a bug. Otherwise, millions of people will struggle just as you did.
