### ISSUE TITLE
Magic Replace option Freezing in photopea

### ISSUE THREAD

**Issue by maver1c7** [photopea/photopea#7066]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Could oyu tell me what should I do after opening www.photopea.com to make it freeze? No matter how I use Magic Replace, Photopea never freezes :(

**Comment by photopea** [comment]
I have to close it because nobody is responding :(

**Comment by maver1c7** [comment]
I didn't catch the reply

**Comment by photopea** [comment]
@maver1c7 hi, how can I help you?

**Comment by photopea** [comment]
Does it work now? Did it ever work for you in the past?

**Comment by maver1c7** [comment]
Yes, it did worked but the problem is sometimes even after watching ads
magic replace doesn't properly work if it has been using frequently

**Comment by photopea** [comment]
Nobody else is reporting it. You did not even tell us what web browser and operating system you use, or in what country you are located.
