### ISSUE TITLE
Workspace starts moving on it's own whilst using the brush.

### ISSUE THREAD

**Issue by SvntySvn** [photopea/photopea#7067]
Your Operating System: Windows
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: No

Whenever I work on a project and start using a brush. The workspace starts moving all over the place. I don't know what triggers it, but it has become quite hard to work around it.

**Comment by photopea** [comment]
Does it work well in the Incognito mode? In that case, it is caused by your browser extensions.

**Comment by SvntySvn** [comment]
I've deleted some of the extensions I didn't use anymore and it seems to work. Thank you. I believe it was a Netflix watchparty extension that had recently updated(?) Once again thank you.

**Comment by photopea** [comment]
You can report it to the creators of those extensions.
