### ISSUE TITLE
no se puede utilizar tipos de letras

### ISSUE THREAD

**Issue by aitorchavesserra** [photopea/photopea#7068]
Your Operating System: windows 10
Your Web Browser:
The problem happens in the Incognito Mode, too: no

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....
ingreso una tipografia pero no me deja utilizarlas solo algunas de vez en cuando

**Comment by photopea** [comment]
Sorry, I speak only English :(

**Comment by photopea** [comment]
I have to close it because nobody is responding :(
