### ISSUE TITLE
cannot crop by selection inversion

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#707]
Steps to reproduce:

1. create new PSD
2. draw a rectangle
3. use magic wand to select the area around the rectangle
4. in menu click Select > Inverse
5. Crop > Selection > Ok

Expected result: to crop by rectangle
Actual result: nothing happens

If you use magic wand to select rectangle directly, then crop by selection works.

Not sure if Select > Inverse includes the virtual area outside of the canvas or something.

this approach (select outside > inverse), is very useful when you have a complex image (which you cannot easily select with magic wand) with blank space around and you want to trim the blank space

**Comment by photopea** [comment]
Hi, it should be fixed now. Thanks!
