### ISSUE TITLE
Can't resize anything :(

### ISSUE THREAD

**Issue by ShinySid** [photopea/photopea#7070]
Your Operating System: Windows 11
Your Web Browser: Opera One
The problem happens in the Incognito Mode, too: opera doesn't have incognito

**This must be done to see the problem**
1. Go to www.photopea.com
2. Select a file and drag it in it is moveable 50% of the time
3. It should be resizeable, so click off it and paste a new image in
4. everything is now unresizeable
atleast thats how it is for me i dont know if thats for everyone

**Comment by photopea** [comment]
How many of your browser extensions have your permissions to modify Photopea? Did you try to use Photopea without any of these browser extensions?

**Comment by photopea** [comment]
I have to close it because nobody is responding :(
