### ISSUE TITLE
scripting help

### ISSUE THREAD

**Issue by AizenMD** [photopea/photopea#7072]
Hello, I've tried to get help in the reddit but no one replied. If this is not the place for questions then please inform me before deleting the issue.
I might have also misunderstood the point of the API and if so I'd like a conformation that it is possible to send files addresses + script to run on these files through something like postman and get the result back to the request (or a specified URL). I'm asking because all I see in the docs are examples of URLS that gives the editors with a certain state. If this is not possible, I'd like to be informed.

I want to use the photopea API to insert 2 images into ArtLayers (every image would go to a different one). I can't seem to find a way to do this.  So far the script I've got is this:
var deskLayer = app.activeDocument.layers.getByName("PC");
var deskObjLayer = deskLayer.layers.getByName("PASTE YOUR DESIGN HERE (double click to edit) ");
app.activeDocument.activeLayer = deskObjLayer;
app.open("https://i.imgur.com/52lKErq.jpeg", as, "asSmart:false");

it opens the image but not as part of the specified artLayer but as a new layer within the same LayerSet (that is called "PC").

I would also like to know how to specify dimensions for the image and location.

**Comment by photopea** [comment]
I think the last parameter of app.open() should be boolean: true - false, just as described at https://github.com/Adobe-CEP/CEP-Resources/blob/master/Documentation/Product%20specific%20Documentation/Photoshop%20Scripting/photoshop-javascript-ref-2020.pdf

I just tried this:

    app.open("https://i.imgur.com/k8NkU27.jpeg",0,true);

and it inserts the image into a current document. You can move it using a different script, but call that script a bit later, when the image is inserted.

**Comment by AizenMD** [comment]
I see, and how would I move it to be inside the artLayer? 
also what would the API call would look like then? 
I want to use it to automate a template I use when uploading a new post to my website. So the site's server would send the request to photopea and then after a few seconds would send another? How would it be able to know that it's from the same server?

**Comment by photopea** [comment]
I dont know what you mean by "site server would send request to Photopea". Photopea must be running on your computer and you must send it scripts from your website.

**Comment by AizenMD** [comment]
I mean like POST request from the site's server and get back a file. Does it have to run as an iframe?

**Comment by photopea** [comment]
We do not have any server that can communicate with your app. We only have a Javascript app that you should run yourself.

**Comment by photopea** [comment]
I have to close it because nobody is responding :(
