### ISSUE TITLE
Window->Actions + TODO

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7073]
Action is not working globally......

for e.g.

in File menu, No sub menu to Close Current File,

+ Clicking X from tab, we can close file, but Action is not able to record such actions.. I think same for SAVE...

Suppose, we open 20 images, we apply some action + but also wants to record save & close

but not possible... right now, but that is possible in PHOTOSHOP Software...

File -- > Close File option is not availabe...

I think that is possible, because using script.. we can able to save file + close file too..
but action is unable to record save & close

**Comment by photopea** [comment]
So far, nobody asked for File - Close in the 11 years of our existence. I think people like to use the "X" on the "tab".

Web browsers do not allow websites to write to a hard drive automatically. We must use the "Download file" dialog, which should be confirmed manually by a user.

**Comment by photopea** [comment]
Have you thought about using File - Automate - Batch? You select a set of files and apply a specific action to all these files.

**Comment by Mayur-hot** [comment]
> Have you thought about using File - Automate - Batch? You select a set of files and apply a specific action to all these files.
Yes this is very good option. Thank you Very much..

Closing this todo issue, because recording save & close in action as like photoshop is bit challenge when we use Browser, and if we can achieve using betch so no need to rework on dublicat...
