### ISSUE TITLE
Squared align improvement

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#7074]
This issue is related to #6970

I love this new tool, but because papers are not squared, sometimes there is the need to have different spacing between vertical and horizontal.

So, i was wondering if you could add vertical gap spacing and horizontal gap spacing, like Figma does:
![image](https://github.com/user-attachments/assets/ddf930ab-aa68-4670-b743-6767ddd00fb6)

So could look like this in Photopea:  
![image](https://github.com/user-attachments/assets/b31e8042-3bb9-479e-8bb5-f468d496d9ac)

_Originally posted by @TheRadicalDreamer in https://github.com/photopea/photopea/issues/6970#issuecomment-2272204335_

**Comment by photopea** [comment]
It is added now.
