### ISSUE TITLE
Window not closing // "Close the current window first"

### ISSUE THREAD

**Issue by evanstrikes** [photopea/photopea#7075]
Your Operating System: Windows 11
Your Web Browser: Bing (downloaded Photopea from bing)
The problem happens in the Incognito Mode, too: N/A

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open any window (this specific time it happened I tried using Adjustments > Brightness & Contrast that bugged) and make it glitched
3. Try closing the window 

For some explanation, I was working on a project and had not yet saved any of my progress. I opened another project to create a small asset for the main project I was working on, I went to Adjustments > Brightness & Contrast and the sliders were not working, and when I try to close out of the window it would not close. If I try doing anything else, including switching to a different project to save the progress I have already made, it won't let me and says "Close the current window first.", when I CANT close the current window. Sometimes when you open Photopea, it saves everything you did before you closed it so I did that and hoped that my projects would be back, and there weren't.

This has happened to me many times, but this time is was very infuriating because I had spent a lot of time on the project and it's going to take me a fair bit of time to re-create what I was making. I tried for like 10 minutes to see if there was any way I could close the window, and nothing was working.

**Comment by Mayur-hot** [comment]
Hello evanstrikes
The problem happens in the Incognito Mode, too: N/A

in Icongnito Mode, you are not facing any problem, then you should remove a plugin that cause this issue..

Many time plugin restrict functinality of a website, so try to find which plugin is causing above Close Issue, and disable that plugin while using [Photopea.com](https://www.photopea.com/index.html)


or whitelist photopea.com from ads blocks...if possible..

Thanks

**Comment by photopea** [comment]
I did step 1) - I opened www.photopea.com. But now, I can not press Adjustments :( are you sure your steps are correct?

**Comment by photopea** [comment]
I have to close it because nobody is responding :(
