### ISSUE TITLE
The background gradient applied from a rectangle in photopea doesn't match the CSS-generated one.

### ISSUE THREAD

**Issue by quangxuagoluan** [photopea/photopea#7076]
Your Operating System: Windows
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a 400x400 rect with liner gradient backgournd color 
3. Applying CSS styles copied from a rectangle to an HTML element 
HTML:
![image](https://github.com/user-attachments/assets/3d89339b-0f01-450b-a00b-5379218d75ee)
photopea:
![image](https://github.com/user-attachments/assets/5278401d-4d07-4461-831f-e5985e04c2e6)
The resulting background gradient appears different from what is seen in photopea. Is this a bug, or is it due to differences in how photopea and CSS internally implement gradients?

**Comment by photopea** [comment]
It is all about the Smoothness parameter: 
![image (4)](https://github.com/user-attachments/assets/7311d919-8d74-40bb-b9ae-316e3c3a233b)

If you set it to Zero, it works like a gradient in HTML. But if you set it to 100%, the gradient is "smoother", and there is no way to replicate it in HTML :( 

Look at this example: www.photopea.com/#iOC5KwAJh
