### ISSUE TITLE
Erasing gif 

### ISSUE THREAD

**Issue by gojowckd** [photopea/photopea#7077]
Your Operating System: DEL 
Your Web Browser: Chrome 
The problem happens in the Incognito Mode, too: Yeah 

Basically when I use the erase tool it always leaves a layer behind it for some reason and I don't know why or how to fix it. An example of what's happening is provided below. 
<img width="380" alt="Screenshot 2024-08-21 204101" src="https://github.com/user-attachments/assets/f4014f3e-0043-466a-9ecd-293309b4876e">

**Comment by photopea** [comment]
I have to close it because of lack of details :(
