### ISSUE TITLE
Error Decrypting

### ISSUE THREAD

**Issue by SyphonSK** [photopea/photopea#7078]
Your Operating System: Windows 11
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open Peadrive
3. Upload File
4. Click on file then it says Error Decrypting.

![image](https://github.com/user-attachments/assets/06a6fdff-bbc0-45e1-8ad1-714a5291c1f8)

**Comment by photopea** [comment]
I just tried it and it works fine in my case :( Did you try to upload other files than this PNG? Maybe it happens only with one specific file.

Also, could you try it with all your browser extensions disabled?

**Comment by SyphonSK** [comment]
The issue still happens with other files even with all my extensions disabled

**Comment by photopea** [comment]
Where are you located? Did it ever work in the past? Do you see any errors in a web console?

**Comment by photopea** [comment]
It happens when you try to upload a file, or you can not access your Peadrive at all?

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by SyphonSK** [comment]
when i try to upload a file and sorry i was busy and i forgot about this

**Comment by photopea** [comment]
Is it working now? Can you open the files that you have on your Peadrive, edit them, and save them back?
