### ISSUE TITLE
The Color Picker window won't close, im on a chromebook

### ISSUE THREAD

**Issue by Liam238FM** [photopea/photopea#7079]
This keeps happening, im making jerseys and specifically when im nearing the end of the project

**Comment by photopea** [comment]
Could you tell me what exactly should I do to see it happen? Can you make it happen on purpose?

**Comment by Liam238FM** [comment]
no, it just happens, and its whenever im almost done a project and i have
to restart

**Comment by photopea** [comment]
how exactly do you open the color picker when it happens? Do you click the foreground color at the bottom of a toolbar? Or you edit a color of a drop  shadow layer style maybe?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
