### ISSUE TITLE
If Photopea is turned into a Chrome extension app with applicationize.me login does not work

### ISSUE THREAD

**Issue by GospelNerd** [photopea/photopea#708]
The login window attempts to pass a message using window.opener.postMessage, which is not a valid reference to the original Chrome App window. 

If the same message is posted using window.postMessage in the original Chrome App window console, the login completes and the UI refreshes (removing the ad).

**Comment by photopea** [comment]
Hi. I am not familiar with Chrome App or applicationize.me . I can not guarantee the correct functionality of Photopea besides the standard web browser.

It sounds to me like it is a bug in Chrome App / applicationize.me , not in Photopea. What do you think?

**Comment by GospelNerd** [comment]
Photopea has their own Chrome extension, but that extension does not run as a standalone app (window would have it's own titlebar & dock icon on MacOS).

applicationize.me is a tool which packages any website as a CRX that can be made standalone. A stand alone Chrome App UX is preferable over having to use the browser for Photopea. But, the login is one feature which is not supported in the Chrome App package configuration because of the postMessage call I mentioned above not finding the "opener" window.

So, I guess this issue could be resolved in 1 of two ways:

1. Make the official Photopea Chrome extension open as a stand alone app
-or-
2. Make the login functionality not rely on a new window and window.opener.postMessage (perhaps an iframe with a parent.postMessage instead?)

**Comment by photopea** [comment]
Can you try "Add to Homescreen" option in your browser? It usually adds an icon to your homescreen, which starts Photopea without browser controls. Login should work there.

I do it this way on my phone, but it should work on desktop browsers, too.

**Comment by GospelNerd** [comment]
Never heard of that functionality being on desktop browsers.

The iframe solution should be pretty trivial to implement. I could do it myself if I could access your code. When you open "https://www.photopea.com/papi/login.php" , instead of window.open targeting '_blank', you would just put the login url into the src of a waiting iframe and make it visible as a popup. Then in login.php, the script after the login would just need to call parent.postMessage instead of window.opener.postMessage.

I've got a workaround for logging into the stand alone applicationize app at this point, but it's a console hack. This solution would be an improvement over the current implementation IMO, as well as resolve this issue.

**Comment by GospelNerd** [comment]
Sorry, I think I'm not being clear. Opening the login sequence in an iframe instead of a new window would be helpful across all browsers, and would make that UX more robust by not relying on window.opener which does not always work. An iframe calling parent would be more reliable (and I think it would look better too).

It would also resolve this specific issue with packaging Photopea as an extension.

**Comment by photopea** [comment]
But I think some services that we use for login (Google or Facebook) would not allow anybody to log in, when they are in an iframe. So we would have to make a popup window or something like that. Do you think popup windows would work in your packaging tool?

**Comment by photopea** [comment]
I really think you should try "add to desktop" in your browser. Here is how it looks like on my desktop (icon + program). It was added from Chrome, but it looks pretty much the same when added from Firefox. 

https://imgur.com/4SkdX8Q

**Comment by GospelNerd** [comment]
I have it working just fine for me (see here: https://imgur.com/AHbFMXE). 

"Add to desktop" from Chromium didn't work, and I don't see a comparable function in Firefox. 

I'm still saying avoiding the second window for login would be helpful.

**Comment by photopea** [comment]
Photopea uses Google, Facebook and GitHub as "identity providers" to log the user in. All three of them refuse to open their sign-in pages in the frame.

The solution could be to create our own registering interface, store passwords, etc. But I think it would ruin the user experience (because of filling the form, verifying emails etc ....).

Another solution is to open the identity provider in the main window. But it would remove the current state of Photopea and all the unsaved work. So I also thing, that it would ruin the experience.

I am closing this issue without any fix. I think, that in the future, the applicationize.me and all other similar tools will be replaced by a standard browser behavior, so there is no need to worry.
