### ISSUE TITLE
Getting RAM error

### ISSUE THREAD

**Issue by anushnag** [photopea/photopea#7080]
I am trying to upscale a picture and get enough RAM but I have a 18Gig. I am trying to increase the resolution, smooth the edges etc.
![Screenshot 2024-08-21 at 9 59 13 PM](https://github.com/user-attachments/assets/f847d371-248a-4e1e-b3aa-387826b9165c)

![Screenshot 2024-08-21 at 9 56 46 PM](https://github.com/user-attachments/assets/405f3917-9d12-48fd-95ed-2698ad078b64)
![Screenshot 2024-08-21 at 9 57 40 PM](https://github.com/user-attachments/assets/d2c6433d-a873-4da4-a5a9-914e0a44b17a)
Please let me know how I can add more RAM to Photopea to fix this issue.

**Comment by photopea** [comment]
Could you tell me what should I do to see this problem? Maybe share your image and tell me what to do next.

**Comment by anushnag** [comment]
I am trying to make this image/logo high resolution with smooth surfaces. I am new to Photopea and find it confusing and help not as friendly. 

I found this video https://www.youtube.com/watch?v=2pNG__KKf88 that shows how to increase/smooth the image

this is the image (trademarked) for our business. 
![Haute Sail Black logo with a higher resolution](https://github.com/user-attachments/assets/ee61a7ad-90d4-48e4-b32a-c4cb147875db)

**Comment by anushnag** [comment]
I want the image to be printed on t-shirt w. high resolution.

**Comment by photopea** [comment]
ok

**Comment by photopea** [comment]
Ask these questions here: https://www.reddit.com/r/photopea/

To answer your questions, you might have to close some apps on your computer to have enough free RAM for 380 millions pixels. But I think you do not need that many pixels.
