### ISSUE TITLE
Paid account getting ads

### ISSUE THREAD

**Issue by schellywags** [photopea/photopea#7082]
Please help me understand - I haven't used PP in a while, but I have an invoice that says I'm paid up for 365 days from October 2023.  Now, when I'm trying to access my PP files and account, my browser is inundated with the ads I paid to avoid and I cannot work like this.  Please help.

**Comment by schellywags** [comment]
Yes, I did - and refreshed the screen several times.  Here's what I see:

![image](https://github.com/user-attachments/assets/d66d43a9-4667-454a-a0b8-0801c6c164ef)

**Comment by schellywags** [comment]
![image](https://github.com/user-attachments/assets/229962fe-a195-45fe-8e4e-0333d8defeff)

**Comment by photopea** [comment]
We write dates as Day, Month, Year. 

You paid on 10th of August 2023, so it has expired :(

**Comment by schellywags** [comment]
😕

**Comment by camoody1** [comment]
@schellywags That European date structure gets me every time, too.

**Comment by photopea** [comment]
I have fixed it - it should print the name of a month now.
