### ISSUE TITLE
Falsely blocked ads when using it in incognito mode on Microsoft Edge.

### ISSUE THREAD

**Issue by yohanessalomo5** [photopea/photopea#7083]
Hello, usually i used Photopea on Google Chrome for so long now, however a couple of months ago, i started using Photopea on Microsoft Edge, and on incognito mode. But today, That popped something like this "Ad blocking detected".

Proof:
![Screenshot 2024-08-22 222842](https://github.com/user-attachments/assets/4b31e84d-920b-4a1f-87b4-5353301b42a5)

Like what? I didn't even turned on ad-blocker or something. I think there's a problem when using it in Incognito mode on Microsoft Edge. What's wrong? If possible, please fix this as soon as possible. Thanks! 👏👏👏😇😇😇

**Comment by photopea** [comment]
I just opened Photopea in Edge InPrivate mode, but it does not say "ad blocking detected".

What settings of Edge do you use? Could you reset it to default settings?

**Comment by yohanessalomo5** [comment]
> I just opened Photopea in Edge InPrivate mode, but it does not say "ad blocking detected".
> 
> What settings of Edge do you use? Could you reset it to default settings?

Nothing, everything on settings seemed normal. What could it be?

**Comment by yohanessalomo5** [comment]
That could be a bug or something.

**Comment by yohanessalomo5** [comment]
Alright, another proof here:
![Screenshot 2024-08-23 011013](https://github.com/user-attachments/assets/25eb6751-1818-433a-a7e5-2026551e9557)

**Comment by camoody1** [comment]
@yohanessalomo5 Include a full screen shot, please, so the developer can see that you're definitely using Edge Incognito. The screen shots you've shared so far don't actually show the Edge browser bar to show that you're in Incognito.

**Comment by yohanessalomo5** [comment]
@camoody1 Alright, here's the full screenshot as requested:

Proof:
![Screenshot 2024-08-23 103736](https://github.com/user-attachments/assets/ac5ae10e-969d-4176-b5b7-ec2e69a7ffee)

**Comment by yohanessalomo5** [comment]
No way! I just found something. It's the tracking prevention that is blocking the ads in Incognito mode on Microsoft Edge. I hope this bug will be fixed soon. I guess case closed.

**Comment by photopea** [comment]
So "tracking prevention" means blocking ads in Microsoft Edge?

Are you able to see ads on other websites with your "tracking prevention" enabled?

**Comment by yohanessalomo5** [comment]
> So "tracking prevention" means blocking ads in Microsoft Edge?
> 
> Are you able to see ads on other websites with your "tracking prevention" enabled?

When it's on, then it showed up that the ad blocking was falsely detected, so i tried to turn off the "tracking prevention" and when it's off, ads now did showed up. Like, i don't know what's going on in here. I was panicking for a moment. I hope it's fixed, but if not possible, then i might as well as turning off "tracking prevention" for now, i guess.

**Comment by photopea** [comment]
Photopea shows "ad blocking detected" when it can not load ads properly. We can not see the settings of your browser, or what ad blockers you are using, if any. We only detect that a connection to the ad server could not be established.

**Comment by yohanessalomo5** [comment]
Alright. Here's the setting that might've blocked ads:

Before:
![Screenshot (2701)](https://github.com/user-attachments/assets/c72a2856-6f53-40c6-af33-cb7c3af94cca)

After:
![Screenshot (2702)](https://github.com/user-attachments/assets/82d32805-5c90-4015-b0d7-ce925b84399e)

**Comment by yohanessalomo5** [comment]
Ohhhhhhh! I get it! I accidentally turned on the "Always use “Strict” tracking prevention when browsing InPrivate" option this whole time! I didn't know. But, not a bug. Just a accident by me. Please forgive me! D;

Anyway, i guess case closed.
