### ISSUE TITLE
HAVE PAID PHOTOPEA ACCT, BUT PHOTOPEA WON'T SAVE TO DOWNLOADS

### ISSUE THREAD

**Issue by kmeano** [photopea/photopea#7084]
My paid photopea account won't download my images.  I've tried many different images and it seems to only save the very first one when I begin using Photopea, after I haven't used it for a while.  Then after that first one, during the session, it won't save to my downloads.  It goes through all the steps like it's supposed to, but after I finish exporting and saving, nothing else happens.

**Comment by photopea** [comment]
Hi, when you do the second download and it does not happen, can you take a
screenshot of your whole screen and share it with us?

**Comment by kmeano** [comment]
I accidentally came across why it was happening.  There was some little
icon on the top right of my screen that said something about blocking or
not blocking downloads.  I just saw a flickering of it when I saved the
first image after turning the program back on
And I opened it and it was on block downloads, so I switched it to do jot
block!!! Thank God I saw it.
Thanks for your quick response
.

**Comment by photopea** [comment]
That's what I thought. Some users reported this problem in the past.

However, it never happened to me. I don't know how the browser decides when to allow a website to save just one file, and not more. Maybe you set some strict security settings, so a browser is worried when a website wants to save something to your computer more than once.
