### ISSUE TITLE
If I get One image then the second image is not editable, I cant able to change the size of the later image. It's happening currently previously it was working perfectly, please fix the issue ASAP...

### ISSUE THREAD

**Issue by Aryan1800** [photopea/photopea#7085]
Your Operating System: Windows
Your Web Browser: Chrome & Brave both
The problem happens in the Incognito Mode, too: YES

**This must be done to see the problem**
1. Go to www.photopea.com
2. Thumbnail Editor
3. Selecting 2 images

**Comment by photopea** [comment]
What should I do to see this problem? I can not fix a problem without seeing the problem. What is "Thumbnail Editor"?

**Comment by photopea** [comment]
I think this is the problem: https://github.com/photopea/photopea/issues/7090#issuecomment-2308581942

**Comment by ShivanKaul** [comment]
The report here says Chrome and Brave are both affected.

**Comment by photopea** [comment]
Maybe, but the person did not respond for five days :/
