### ISSUE TITLE
The typed in text does not show

### ISSUE THREAD

**Issue by NestorSampedro** [photopea/photopea#7086]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Did you try it in the Incognito mode? This problem is usually caused by your browser extensions.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
