### ISSUE TITLE
it won't let me scale the image of look at another image

### ISSUE THREAD

**Issue by TheDeatCrusher** [photopea/photopea#7087]
Your Operating System:Windows 10
Your Web Browser:Brave
The problem happens in the Incognito Mode, too:Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
It happens in Brave sometimes, that the transformation stops working. I dont know why :( Did you try to use other browsers?

**Comment by photopea** [comment]
Please, read this: https://github.com/photopea/photopea/issues/7090#issuecomment-2308581942

**Comment by ShivanKaul** [comment]
Brave has fixed the website functionality breakage (see https://github.com/brave/brave-browser/issues/40619#issuecomment-2315684876), let us know if you run into it again.
cc @ryanbr
