### ISSUE TITLE
Not letting me export pages in PDF format. 

### ISSUE THREAD

**Issue by oooodit** [photopea/photopea#7088]
![Screenshot 2024-08-24 105323](https://github.com/user-attachments/assets/adcb2250-7b1d-41e5-974e-d2147ba25913)
![Screenshot 2024-08-24 105426](https://github.com/user-attachments/assets/cbadb3cd-2b5d-4fed-b074-2c2dd966a63e)
![Screenshot 2024-08-24 105503](https://github.com/user-attachments/assets/ce08c847-73ca-4d6d-b52c-7b2f70115771)
Your Web Browser: Google.com

**This must be done to see the problem**
1. Go to www.photopea.com
2. Export any PDF you have.
3. Zoom in / Zoom out / Edit
4. Export as PDF.

It will combine every page of the PDF in a single page. Then your exported PDF will have only one page - combining every page into a single one. HATE IT.

**Comment by photopea** [comment]
This usually happens if you create a layer which is not inside any artboard. 

The artboard to page conversion happens only if all layers are in artboards!

You did not show us your document, so I can not tell what layers you have.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
