### ISSUE TITLE
Cant resize anything

### ISSUE THREAD

**Issue by Kaka123SRV** [photopea/photopea#7089]
Your Operating System: Windows
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: from what i guess, it happens to everyone

**This must be done to see the problem**
1. Go to www.photopea.com
2. Get any object, for now you can resize it
3. Paste any object from clipboard
4. You cant resize anything now!

Bonus Info:
I have no extensions for photopea. All i did was pasted into clipboard. Happens every time i do that.

**Comment by photopea** [comment]
I think I have figured it out.

As you see, Brave is deleting ads from Photopea. But they do it "too thoroughly" and break the resize functionality.

You can ask Brave to fix it (it is them who decided to do something what other browsers don't do), or you can switch to a different browser. Or you can "disable shields" in Brave, which should make it display websites the way they were made.

**Comment by Kaka123SRV** [comment]
Hey! Thanks for the response. I think that was the problem. Ill try it out
later. Have a nice day!

niedz., 25 sie 2024, 02:05 użytkownik Photopea ***@***.***>
napisał:

**Comment by photopea** [comment]
It is probably related to this: https://github.com/brave/brave-browser/issues/40619

Brave tried to "fix adblock message in Photopea" but they actually broke it.
