### ISSUE TITLE
SVG preserveAspectRatio="none"

### ISSUE THREAD

**Issue by lukasz-gorski** [photopea/photopea#709]
SVG saved from Photopea could have preserveAspectRatio="none", for use them as background.

**Comment by photopea** [comment]
I think that people usually want the SVG to preserve the aspect ratio (e.g. if you open a 50x50 px SVG in a browser, you don't want it to be stretched). I suggest that you should add your attribute outsied Photopea.

**Comment by lukasz-gorski** [comment]
It's not stretched with preserveAspectRatio="none" till you change size settings by css. Test it.

**Comment by photopea** [comment]
it is stretched if I remove the "width" and "height" attributes and keep only viewBox. Are you sure the preserveAspectRatio="none" is enough for you?

**Comment by photopea** [comment]
Also, we would be making each SVG several bytes bigger, which many people may not want :(

**Comment by lukasz-gorski** [comment]
I asked about option for that, just small checkboxa adding it. It’s usefull using SVG as backgrounds, realy.. 😉

___Łukasz Górski.

Od: Photopea
Wysłano: niedziela, 27 maja 2018 21:18
Do: photopea/photopea
DW: lukasz-gorski; Author
Temat: Re: [photopea/photopea] SVG preserveAspectRatio="none" (#709)

Also, we would be making each SVG several bytes bigger, which many people may not want :(
