### ISSUE TITLE
Unable to resize or use del

### ISSUE THREAD

**Issue by smokeracc** [photopea/photopea#7090]
Your Operating System: Windows
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Paste an image 
3. Enable transform controls
4. For a short time all functions will work normally
5. Will soon be unable to resize image
6. Selected pixels will not delete using del as normal

**Comment by photopea** [comment]
I tried to do your steps in Brave, but everything seems to work fine. Could you record a short video where you follow these steps, as a proof?

**Comment by maxwellreyes** [comment]
https://github.com/user-attachments/assets/52c091d2-872f-4c93-ac56-505500ab7f2d

I'm not the one who reported the problem but the same thing happens to me. I use the Brave browser

**Comment by photopea** [comment]
you did not start with Step 1 - open www.photopea.com . It is not clear what you did before you started to record your video.

Maybe if I did exactly what you did, I would see the problem, too. But I dont know what you did :(

**Comment by maxwellreyes** [comment]
You should note that when I want to scale the image it is impossible for me, I cannot adjust the size of the layer. In addition, I can only attach a file smaller than 10MB and to display it, since I create the file, its weight increases, which prevents me from attaching it.

**Comment by smokeracc** [comment]
https://github.com/user-attachments/assets/5f6a8675-dd9f-4607-95d7-dc7b86fbcad0

**Comment by photopea** [comment]
I am doing what you are doing, but I can resize the pasted image :(

I noticed that you have different icons at the top right corner than I do, do you know what it means?

![image (1)](https://github.com/user-attachments/assets/cedd611f-20e3-4c10-a7e5-e5f44b1b3c12)

**Comment by photopea** [comment]
I think I have figured it out.

As you see, Brave is deleting ads from Photopea. But they do it "too thoroughly" and break the resize functionality.

You can ask Brave to fix it (it is them who decided to do something what other browsers don't do), or you can switch to a different browser. Or you can "disable shields" in Brave, which should make it display websites the way they were made.

**Comment by maxwellreyes** [comment]
Excellent, thank you very much for the help

https://github.com/user-attachments/assets/742e82ad-de7c-4e2f-9fb6-296b9c640c7b

**Comment by photopea** [comment]
I think you should report it to Brave, only they can fix it. Brave has blocked us on their Github site many years ago for reporting bugs :(

**Comment by photopea** [comment]
It is probably related to this: https://github.com/brave/brave-browser/issues/40619

Brave tried to "fix adblock message in Photopea" but they actually broke it.

**Comment by ShivanKaul** [comment]
Brave has fixed the website functionality breakage (see https://github.com/brave/brave-browser/issues/40619#issuecomment-2315684876), let us know if you run into it again.
cc @ryanbr

**Comment by photopea** [comment]
What does it mean "they fixed it"? Will it be a part of the next release a few months from now?

My brave says "Brave is up to date
[Version 1.69.153 Chromium: 128.0.6613.85 (Official Build) (64-bit)](https://brave.com/latest/)"

and the issue is still there.

**Comment by ShivanKaul** [comment]
No, the fix was an adblock filter rule fix, which means it was rolled out automatically via adblock lists which should have reached you by now. You can double-check by going to brave://settings/shields/filters and pressing `Update lists`. 

It would be helpful if you could take a video of the breakage.

**Comment by photopea** [comment]
I Updated the list, the issue is still there.

You can see it yourself: Open any image in www.photopea.com , wait 1 minute, and then, try to transform it (Edit - Free Transform), fails every time.

**Comment by TemeASD** [comment]
I have the same issue with Edge, Chrome and Firefox. Tested all browsers without adblockers. This is spammed when trying to move the area selected for free transform. 

Uncaught e 2 pp1724937598.js:1366:114
    TN https://vecpea.com/code/pp/pp1724937598.js:1366
    WW https://vecpea.com/code/pp/pp1724937598.js:8407
    aN https://vecpea.com/code/pp/pp1724937598.js:8277
    aCE https://vecpea.com/code/pp/pp1724937598.js:16524
    a https://vecpea.com/code/pp/pp1724937598.js:11517
    a https://vecpea.com/code/pp/pp1724937598.js:11522
    a https://vecpea.com/code/pp/pp1724937598.js:11522
    a https://vecpea.com/code/pp/pp1724937598.js:11522
    a https://vecpea.com/code/pp/pp1724937598.js:11522
    vb https://vecpea.com/code/pp/pp1724937598.js:11541
    (Async: EventListener.handleEvent)
    wm https://vecpea.com/code/pp/pp1724937598.js:11481
    WZ https://vecpea.com/code/pp/pp1724937598.js:11538

**Comment by photopea** [comment]
Could you confirm that you are not using any browser extensions? Could you record a short video of what you so, and start by loading Photopea.com ?

**Comment by TemeASD** [comment]
Sure! Here goes: https://www.youtube.com/watch?v=DsDi14bKlOI

No extensions, cleared site data. Attached the files. Trimmed down the original PSD, but confirmed that the same thing happens with this one as well. 

[example.zip](https://github.com/user-attachments/files/16805909/blackmetalmotorsports.zip)

**Comment by photopea** [comment]
You are right, it happens when transforming a selected part of a layer in a 16-bit document. I will try to fix it tomorrow.

**Comment by photopea** [comment]
It should be fixed now. I am very sorry. We have added the 16-bit support only in April: https://blog.photopea.com/photopea-5-6-advanced-color-depth.html
