### ISSUE TITLE
Plugin FlashFx JSON Error, Same with other plugin by develeoper

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7091]
![Screenshot_2024-08-24_23-42-59](https://github.com/user-attachments/assets/542dedbc-898f-4dfc-a0d3-dda23a9ac658)

Just check first plugin "flashfx" by Kamil Chbeir
not working

also check his Paranormal Glitch Slate plugin....

Not working..

Ok, and one suggestion for qrcode generator plugin...

+ I used QR Code Plugin, Can we Add Themes: [ black/white ]
                                                                           [white/black]
                                                                           [custom] --> This will prompt user input and user can add foreground/background color of a qr code. (Just idea, not nessessory)

**Comment by photopea** [comment]
Plugins are added by our users, anyone can add anything.

I have deleted the damaged plugins. Please, remove them from your "installed" category.

Only the creator of the QR code plugin can change it. I believe it was made by @hxim - https://github.com/hxim

**Comment by Mayur-hot** [comment]
Ok, about qr code theme,

I think user can use invert tool aur set any color latter on.

And most of camera detects white background and black bars, ao theme is
useless for qr code..and if user want then he van modify using photopea any
time.


One thing I found strange in photopea today I found..

If we open plugins or templates in guest (no login mode)

From list click any one..

Now we have plugin/template info with comments..

Accidently I double click above name of temples or plugin.. that will
shows...
Install plugin in/add templates without login...

And also get message like please login..



Finally thanks 🙏.

**Comment by photopea** [comment]
You can use our plugins or templates without having a Photopea account.

**Comment by Mayur-hot** [comment]
Ok, I am sending you screenshot of..
What I am saying..

I see form to add plugin without login.
Ofcourse every user can install it..

But every user can able to make plugin?

Just scrolling down, I see add plugin form

**Comment by Mayur-hot** [comment]
Just do this test

**Comment by photopea** [comment]
I do not see any screenshot. Please, open Github.com in a browser and respond to us there. Do not send emails to random Github addresses.
