### ISSUE TITLE
Pen pressure is not detected on Windows 11.

### ISSUE THREAD

**Issue by roykz792** [photopea/photopea#7092]
Operating System: Windows 11
Web Browser: Edge
The problem happens in Incognito Mode, too:

Description of the problem:

I am using an XP-Pen Star02, and while it worked fine with pen pressure sensitivity on Windows 10, it no longer detects pen pressure on Windows 11. This occurs even when the icon on the device is pressed.

**Comment by photopea** [comment]
Hi, I do not have Windows 11 or your pen :( 

Do you use the same web browesr as before? Did you install the correct drivers? Can you use your pen properly in other apps in Windows 11?

**Comment by roykz792** [comment]
I’m using the same browser. The drivers are installed, and pen pressure is detected in other software. Currently, Photopea is the only application where pen pressure isn’t being recognized.

**Comment by photopea** [comment]
I wish I could help you, but Photopea still works the same, it is your environment which as changed. We can not "detect pressure harder" than what we do now.

Could you look into Windows settings and change something? Or try a different browser? Or ask people with the same tablet on Reddit?

**Comment by photopea** [comment]
Maybe this can help you? https://www.youtube.com/watch?v=Kr8ostpGOxY

**Comment by photopea** [comment]
I have to close it because of lack of details :(
