### ISSUE TITLE
ui does not fit screen

### ISSUE THREAD

**Issue by BlueBinx** [photopea/photopea#7093]
Might not be a bug, but it feels like it is. Not really sure how it happens or what to do to fix it. My Windows Hp laptop's screen resolution is 1366 x 768, but the right side edge of the website version of the program's UI is a few inches away from the edge of the screen that it should be at (see images below). I don't know if this also occurs on the installed app.

1. Go to www.photopea.com 

![image](https://github.com/user-attachments/assets/71580900-3502-411f-814c-5d30a502467e)
![image](https://github.com/user-attachments/assets/91fdd251-76f9-4cb6-8d37-fd6eed1b3ec4)

**Comment by photopea** [comment]
There should be advertisement on the right side of Photopea. It is the main source of our income, we would not exist without it.

Could you please allow our ads to be displayed? Or you can remove the ads (or the empty space) for 90 days for 15 USD (a one time payment, then, ads come back).

**Comment by photopea** [comment]
I have to close it because of lack of details :(
