### ISSUE TITLE
transform/free transform in photopea straight up broken

### ISSUE THREAD

**Issue by Iegacyy** [photopea/photopea#7094]
when i go into edit, transform, and scale, the contols just dont show up. i try free transform, same thing. when i turn on transform controls in the move tool, the controls show up but when i try to scale the layer it doesnt change.

**Comment by Iegacyy** [comment]
https://youtu.be/P-9YEynMFwI
video of the problem

**Comment by photopea** [comment]
About 15 people reported that it happens in the Brave browser. So it will work if you switch to another browser.

We are trying to figure out why it does not work in Brave: https://github.com/photopea/photopea/issues/7090

**Comment by photopea** [comment]
I think I have figured it out.

As you see, Brave is deleting ads from Photopea. But they do it "too thoroughly" and break the resize functionality.

You can ask Brave to fix it (it is them who decided to do something what other browsers don't do), or you can switch to a different browser. Or you can "disable shields" in Brave, which should make it display websites the way they were made.

**Comment by Iegacyy** [comment]
ah okay, i'll just use  a different browser then for photopea

**Comment by photopea** [comment]
I think it is related to this: https://github.com/brave/brave-browser/issues/40619

Brave tried to "fix adblock message in Photopea" but they actually broke it.
