### ISSUE TITLE
unknown file format

### ISSUE THREAD

**Issue by Cvbella22** [photopea/photopea#7095]
Your Operating System: windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: N/A

**This must be done to see the problem**
1. Go to www.photopea.com
2. Click "Open from computer"
3. Choose the file/files
4. Waiting for upload
5. Error message appears
6. Unknown file format "yyyy" (all of the y's have two dots above them)

**Comment by photopea** [comment]
Could you show us your file that you are opening? Can you open that file with any other tool?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
