### ISSUE TITLE
First Check this issue Without Login to photopea

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7096]
![Screenshot_2024-08-25_10-40-22](https://github.com/user-attachments/assets/ea846251-da8f-4eb5-add5-8120a40a8893)

How to recreate this issue..

![good](https://github.com/user-attachments/assets/64d59819-9959-40da-ba1d-d7c6dd12c701)

same with templates, double click on blank area creates Templates/Plugin Form Below...

THis is a BUG, because without login, clicking on "Add Plugins" Gives message like "You need to login first!"

but still end user get FORM, double check 2nd screenshot.

Thanks

**Comment by photopea** [comment]
it should be fixed now.
