### ISSUE TITLE
lag

### ISSUE THREAD

**Issue by janle00** [photopea/photopea#7097]
it is lagging when i am editing😢

**Comment by photopea** [comment]
what is lagging?

**Comment by Sil3a2** [comment]
for me its lagging to when i edit a picture it have like a delay (5 second delay)

**Comment by photopea** [comment]
Could you record a short video of opening Photopea.com and what you do next, to see what you did?

**Comment by Sil3a2** [comment]
i use it on the browser

**Comment by Sil3a2** [comment]
cant send viedo even 5 second is too big

**Comment by photopea** [comment]
you can put it on Youtube for free.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
