### ISSUE TITLE
CSS export, inspecting layers

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#71]
Hi,

what about some CSS3 export like CSS Hat or Avocade?
https://avocode.com/features-developer.html#up

I need some inspecting layers - width, height, sizes between layers etc. It would be great! 
Quick export to JPG / PNG / SVG - maybe by context menu will makes me happy too :)

**Comment by seevikargwal** [comment]
Yes, after this I can move totally to photopea. I just found this tool somewhere on the internet. You guys doing really good job. And I'm going to publish an article on photopsia soon on medium.

**Comment by photopea** [comment]
Hi, we already have layer inspecting  (with a Move tool, check Distances at the top, and see the distances).

CSS export: do you mean for text layers, or other layers too? Can you show me an example of a layer, and a CSS, that you would like to get?

**Comment by seevikargwal** [comment]
Here I have shown avocode tool for SVG export and also CSS for any Box, Button with gradient.
http://d.pr/i/eVhN3o Please see this gif video.

**Comment by photopea** [comment]
Cool, thanks! Can you also send us the PSD file, that you use in the video? E.g. to support@photopea.com , or attach it here in the conversation.

**Comment by seevikargwal** [comment]
Here you can find that PSD file http://d.pr/f/f6QCBJ

**Comment by seevikargwal** [comment]
Here you can find that PSD file. http://d.pr/f/E9muDN

**Comment by seevikargwal** [comment]
any new updates?

**Comment by photopea** [comment]
Hi, I will try to work on it the next week.

**Comment by meeeu** [comment]
how do we edit the css?

**Comment by photopea** [comment]
@meeeu CSS is changed as as you edit the layer. E.g. change the text of the color, and CSS color will also be changed. Or you can copy CSS into another place and then edit it there.

**Comment by landsman** [comment]
@meeeu you want change design (layers) by CSS?

**Comment by meeeu** [comment]
@landsman, yes, I had thought editing the CSS would affect the current layer.  Guess it's just for 'exporting' to use as CSS.

**Comment by photopea** [comment]
So I am closing this issue now. Let me know if you have other ideas about web-related tools.
