### ISSUE TITLE
H and W in info panel show all the time 0

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#710]
When I draw something (shape or selection), width and height on info window doesn't show anything in real time (X and Y works good).

When I click on drawed object (with move tool), this parameters show 0. CSS panel show real witdh and height of this object.
I think, on info window, when I select object with move tool, X and Y should show actual position on canvas and width and height.
 
What do you think about it? Or tell me please how does it work in Photopea.

**Comment by photopea** [comment]
The Width and Height of the Info panel should work the same way as in Photoshop (that was the original request for this panel).

Currently, it shows the size of a selection and a Cropping Rectangle. It also shows the real-time dimensions while you create them. I made it to show the size of the currently drawn shape.

You can enable "Distances" in the top menu of the Move tool. They correspond to what you see in CSS.

**Comment by photopea** [comment]
There is always a dilemma, if we should have the feature with the same name and look as some other program, or once it is too different, if we should rename it. Do you have any other specific proposal regarding the Info panel?
