### ISSUE TITLE
free transform does not work

### ISSUE THREAD

**Issue by person-vr** [photopea/photopea#7100]
Your Operating System: windows 11
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. create text or image on a new layer
3. create a new layer and have it selected
4. the first layer's free transform completely breaks

i have no idea what is happening here, but i have a bad feeling it has something to do with my computer/photopea settings

**Comment by photopea** [comment]
As you see, Brave is deleting ads from Photopea. In the latest Brave update, they did it "too thoroughly" and break the resize functionality. See here: https://github.com/brave/brave-browser/issues/40619

You can ask Brave to fix it (it is them who decided to do something what other browsers don't do), or you can switch to a different browser. Or you can "disable shields" in Brave, which should make it display websites the way they were made.
