### ISSUE TITLE
App crashes whenever I try to duplicate a layer into a new document or open a second project

### ISSUE THREAD

**Issue by sarahmixes** [photopea/photopea#7101]
Your Operating System: Windows 11
Your Web Browser: Brave + the app
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open or create a project with layers
3. Duplicate a layer into another project 
OR 
4. Open multiple projects and try and copy between them

**Comment by photopea** [comment]
Brave started to treat Photopea differently three days ago: https://github.com/brave/brave-browser/issues/40619 Many things do not work.

You should report it to Brave, not to us. If you find a bug while using Photopea in a real browser (the one which runs websites according to web standards), let us know.
