### ISSUE TITLE
Backspace don't want to remove a layer

### ISSUE THREAD

**Issue by Arthurprnt** [photopea/photopea#7108]
Your Operating System: Windows 11 23H2
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a 96x96 transparent canvas
3. Add a 96x96 circle on the default layer
4. Create a triangle on another layer
5. Select this triangle
6. Go back on the circle layer and press backspace
7. The selected area is not deleted

Exemple:
https://github.com/user-attachments/assets/c8fedd58-dd79-44a8-9cea-41bf4a42c68b

**Comment by osameissa** [comment]
Same problem with Photopea desktop

**Comment by photopea** [comment]
It is a bug in your browser Brave. They wanted to delete our ads, but they ended up deleting certain features of Photopea. 

Please, write it here: https://github.com/brave/brave-browser/issues/40619 . Brave has blocked us from writing to them, so if you have permissions to write them, please, let them know about your problems, and ask them not to break Photopea for you.
