### ISSUE TITLE
Brave browser

### ISSUE THREAD

**Issue by sportential** [photopea/photopea#7109]
Your Operating System: Windows
Your Web Browser: Brave
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....EDIT/ FREE TRANSFORM
3. ....The layer does not get a mask to transform the image
4. ....

**Comment by photopea** [comment]
I tis a bug in Brave, you should report it to the creators of Brave, not to us.

I have noticed that Photopea works fine if you disable "shields" in Brave. So "shields" means "break website" in their terminology, you should disable it :D
