### ISSUE TITLE
More mobile friendly.

### ISSUE THREAD

**Issue by LupaWolf300** [photopea/photopea#711]
Hello, I'm an android user using Chrome. Today was my first time testing out this site, one of the things I noticed, that I do not think others have mentioned, though I could easily be wrong, is that on mobile it tends to zoom in if I am using the "Desktop Site" mode. When I'm not, it hosts more options than the desktop version but I can see much, much less of the screen like expected but I cannot scroll over to see it.

**Comment by photopea** [comment]
Hi, "desktop site" should have absolutely the same options as a regular site. Just panels on the right are "collapsed".  So you would like to have something in between?

**Comment by LupaWolf300** [comment]
Ah! I'm so sorry for not clarifying, I meant that when I double-tapped for such things like renaming layers and choosing the style of the layer (it doesn't fit the screen at all for me but that's just my phone, I can luckily move the box itself!) If possible, maybe placing a button on the bottom near where the "Delete," "New Layer," "New Folder," and such are where there can be some other layer specific actions that can counteract with some mobile actions? I understand if this isn't possible or just clutters the space. And yes, the panels are collapsed on the sides and do have the same options, it's just a few intersecting problems. I apologize for the confusion.

**Comment by photopea** [comment]
What do you mean by "counteract with some mobile actions"? What new buttons do you need?

**Comment by LupaWolf300** [comment]
By counteracting actions with how mobile works, I meant the double tapping. I apologize for that and not replying to this sooner. Maybe a button located at the bottom of the layers panel next to the "New Layer" for users who can't double click? Also, maybe the layer style can go under the filters option (or at least that is what I think the half filled in circle located on the bottom of the layers panel, but it's that button I'm talking about)? Though, if not, maybe it can have a separate button for now that goes next to it? Thank you for being patient with me.

**Comment by photopea** [comment]
Do you mean double-clicking the layer thumbnail to open Layer Styles or a Smart Object? This should work well on a touchscreen, too, I think.

The next thing is the right-clicking the layer in Layers panel, which does not work on a touchsceen now. Also, reordering layers by dragging and dropping does not work. Is this what you meant?

**Comment by photopea** [comment]
I have to close it because of lack of details.
