### ISSUE TITLE
Unable to use fill tool

### ISSUE THREAD

**Issue by ghost** [photopea/photopea#7110]
Your Operating System: 64-bit operating system, ARM-based processor
Your Web Browser: Opera

The content-aware fill tool worked fine for me before, but now it just stopped working. I've reset my computer, but so far, nothing has worked, and when I use it, history just lists the brush tool
![Screenshot 2024-08-27 204844](https://github.com/user-attachments/assets/ca7c961b-ea27-4e74-8251-7cde2107aab8)
![Screenshot 2024-08-27 204830](https://github.com/user-attachments/assets/a95fb46f-a9af-4bb8-8993-c3e6a124f558)

**Comment by photopea** [comment]
I just tried it and it works fine.

Could you show a proof that it is not working? In your screenshot, you might have an empty layer with no content, and you are applying it to this empty layer, which does nothing. Why do you cut away the Layers panel from your screenshots?

**Comment by LucasH006** [comment]
![image_2024-08-28_152537857](https://github.com/user-attachments/assets/4e9449fd-a442-4156-90d4-2235d296d63d)
Here is my layers panel. Not sure why I cut them out in my initial screenshots

**Comment by photopea** [comment]
could you share your image with me, so that I try it myself? Maybe your selection is not big enough, and it fills the area with black.

**Comment by LucasH006** [comment]
![Emitt Rhodes (Front)](https://github.com/user-attachments/assets/0695db16-3cbc-44a6-b102-213055108be8)

**Comment by kuckir** [comment]
You sent me a PNG, not a PSD. and you stretched your PNG in your PSD to a much larger resolution.

Anyway, I selected your text with a rectangular selection, and used a content-aware fill, and it disappeared.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
