### ISSUE TITLE
Weichzeichner funktioniert nicht.

### ISSUE THREAD

**Issue by 123547689** [photopea/photopea#7114]
Your Operating System: Windows
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Weichzeichner 
3. Stärke einstellen
4. über Objekt fahren
5. Geht nicht

**Comment by KwiatekMiki** [comment]
can you speak english or at least use google translate

**Comment by photopea** [comment]
Sorry I speak only English :(

**Comment by 123547689** [comment]
Your Operating System: Windows
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, also: Yes

This must be done to see the problem

Go to www.photopea.com
Soft focus
Adjust strength
drive over object
It does not work

**Comment by photopea** [comment]
I dot understand, what is "Soft focus"?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
