### ISSUE TITLE
Chinese input together with English / numbers

### ISSUE THREAD

**Issue by 1234567Yang** [photopea/photopea#7117]
Your Operating System:Chrome OS/Windows
Your Web Browser:Chrome/Edge
The problem happens in the Incognito Mode, too:
Yes
**This must be done to see the problem**
1. Go to www.photopea.com
2. Make a textbox
3. Type(paste) "鸡"
4. Type "zhi yin"
5. See tofu blocks

![image](https://github.com/user-attachments/assets/88d743ea-66aa-4c82-ad94-ef1c8571dfb3)

**Comment by photopea** [comment]
I think your font does not support these characters. Use a different font. You can also use a different font for each character.

**Comment by 1234567Yang** [comment]
> I think your font does not support these characters. Use a different font. You can also use a different font for each character.

Long time ago, I can type both English and Chinese together with the same font in photopea, but I can no longer do that.

**Comment by 1234567Yang** [comment]
I think this happened after some auto change font update(when you type in Chinese character, it will auto change font)

**Comment by Mayur-hot** [comment]
> > I think your font does not support these characters. Use a different font. You can also use a different font for each character.
> 
> Long time ago, I can type both English and Chinese together with the same font in photopea, but I can no longer do that.

![Opera Snapshot_2024-08-29_092911_www photopea com](https://github.com/user-attachments/assets/81de982f-98d8-4942-b45b-e20d616f23cd)

I don't know Chines, but I use google translator and Copy & Paste to Photopea, and Font Goes to Fall Back Font, Because default font is not support Chinese.. So Font Auto Changed From "Droid Sans"  to "Droid Sans Fallback"

**Comment by 1234567Yang** [comment]
![image](https://github.com/user-attachments/assets/541c295b-6b4a-4a12-a46d-89b478c1bbe8)
Yes I just tested many different fonts and I found one.
I think photopea should auto load more capable fonts when typing Chinese/Korean, so maybe a small issue

**Comment by 1234567Yang** [comment]
> > > I think your font does not support these characters. Use a different font. You can also use a different font for each character.
> > 
> > 
> > Long time ago, I can type both English and Chinese together with the same font in photopea, but I can no longer do that.
> 
> ![Opera Snapshot_2024-08-29_092911_www photopea com](https://private-user-images.githubusercontent.com/176575844/362527020-81de982f-98d8-4942-b45b-e20d616f23cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDYxMjIsIm5iZiI6MTcyNDkwNTgyMiwicGF0aCI6Ii8xNzY1NzU4NDQvMzYyNTI3MDIwLTgxZGU5ODJmLTk4ZDgtNDk0Mi1iNDViLWUyMGQ2MTZmMjNjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNDMwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODY1MTJjOGQzNWE1NDFkOTVhNTQwYWFmYzMzODdiZWFmMjZhOWMxMzNlZWI4NDA3NGNlMzNiMGE0NDM1NmNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iKmLoLYSHmHZQGz9kjOSgOa3aUdDFIVOb6Kft1lfKUg)
> 
> I don't know Chines, but I use google translator and Copy & Paste to Photopea, and Font Goes to Fall Back Font, Because default font is not support Chinese.. So Font Auto Changed From "Droid Sans" to "Droid Sans Fallback"

Yes I understanded why photopea add "auto change font" feature now, however, if you continue typing English in this situation after pasting Chinese, you will have some issue, and this can happen really common, for example, if we type "Tom: I have practiced basketball for 2.5 years"(Tom: 我练习时长2.5年)，then we will have something like this:
![image](https://github.com/user-attachments/assets/ec6a7046-e76f-4ada-bf5d-5d2fb2b7ba36)

**Comment by photopea** [comment]
It should be fixed now. If you type with a font that has no latin characters, and you type a latin character, Photopea will apply a more appropriate font to this character automatically. You can still change the font later.

**Comment by photopea** [comment]
I can not fix it. Please, just apply a new font manually.

**Comment by 1234567Yang** [comment]
ok

Photopea ***@***.***> 于2024年8月31日周六 08:01写道：
