### ISSUE TITLE
fail to save the image from api

### ISSUE THREAD

**Issue by vedantdere** [photopea/photopea#7119]
Your Operating System: Linux
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

I am using photopea api. 
```
{
	"files" : [
		"https://www.mysite.com/images/design.psd",
		"https://www.mysite.com/images/button.png",
		"data:image/png;base64,iVBORw0KGgoAAAAN..."
	],
	"resources" : [
		"https://www.xyz.com/brushes/Nature.ABR",
		"https://www.xyz.com/grads/Gradients.GRD",
		"https://www.xyz.com/fonts/NewFont.otf"
	],
	"server" : {
		"version" : 1,
		"url"     : "https://www.myserver.com/saveImage.php",
		"formats" : [ "psd:true", "png", "jpg:0.5" ]
	},
	"environment" : {...},
	"apis"   : { "dezgo": "d4e5f6"  },
	"script" : "app.activeDocument.rotateCanvas(90);"
}
```

In the above code for server to save files if I use my localhost and the server is running on the localhost inside the docker container then the image is saving. But when I deployed container and hosted to my domain the image is not saving. Request is received but the post request from my endpoint is I think not accepting at the photopea end. Thats why I am getting saving all the time as show in the below screenshot. 
![image](https://github.com/user-attachments/assets/dd96534e-3725-44e3-a031-40dcde073f24)

**Comment by photopea** [comment]
Do you see any errors in a web console? It could be a CORS error.

**Comment by vedantdere** [comment]
There were no errors in the console, and I have enabled all domains in the CORS settings.

**Comment by vedantdere** [comment]
I am getting CORS related issue now 
```
A cross-origin resource sharing (CORS) request was blocked because of invalid or missing response headers of the request or the associated preflight request.
To fix this issue, ensure the response to the CORS request and/or the associated preflight request are not missing headers and use valid header values.
Note that if an opaque response is sufficient, the request's mode can be set to no-cors to fetch the resource with CORS disabled; that way CORS headers are not required but the response content is inaccessible (opaque).
1 request
Request	Status	Preflight Request (if problematic)	Header	Problem	Invalid Value (if available)

 save_images	blocked		Access-Control-Allow-Origin	Missing Header
```

**Comment by vedantdere** [comment]
> Did your server receive an image?

No

**Comment by vedantdere** [comment]
From my end I have enables the CORS but the request coming from the photopea on my endpoint does not have `Access-Control-Allow-Origin`.
