### ISSUE TITLE
Filters like GMIC

### ISSUE THREAD

**Issue by imms93** [photopea/photopea#712]
Since the features I asked for have all been added (thank you again!), I think that a bigger update should be done on filters. I have been experimenting with GIMP and I found GMIC's filters absolutely amazing, and it would be nice if everyone could use them in Photopea. There is an online version of GMIC here https://gmicol.greyc.fr, is it possible to integrate it in the editor?

**Comment by photopea** [comment]
PSD files contain Smart Objects, which can have Smart Filters applied to them (the filter, which can be recalculated, after the source image is changed) ... like a "non-destructive filter".

To guarantee the full PSD support, Photopea must be able to perform all Photoshop filters. Some filters are present both in Photoshop and GMIC.

I had an idea, that I can add a plugin interface to Photopea, and you (or somebody else) can make all these GMIC filters. We would publish these JS filters as open-source. Would you be interested in making them?

**Comment by photopea** [comment]
We should not add non-PSD filters, until we have all PSD filters first. If you want any specific filter, please, try to find its version in Photoshop, and tell us which one it is.
