### ISSUE TITLE
No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by vedantdere** [photopea/photopea#7120]
Your Operating System: Linux
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

I am using the photopea api. photopea is send response to my server without header for Access-Control-Allow-Origin. 
Below is the log of the error 

```
www.photopea.com/#%7B%22files%.......%  
Access to XMLHttpRequest at 'https://domain.me/save_images' 
from origin 'https://www.photopea.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Please add 'Access-Control-Allow-Origin' in the response.

**Comment by photopea** [comment]
Hi, only the servers can have the CORS headers, not clients. Only you can fix it on your server.

**Comment by vedantdere** [comment]
The request is coming from photopea end without headers thats why my endpoint is not accepting.

**Comment by photopea** [comment]
that is not how CORS works.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
