### ISSUE TITLE
whenever i put a new line for text the font changes

### ISSUE THREAD

**Issue by podunktimes** [photopea/photopea#7121]
Your Operating System: Android
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Text
3. New line
4. Font changes

**Comment by podunktimes** [comment]
It fixed almost immediately after  i posted this

**Comment by podunktimes** [comment]
IT UNFIXED 

FONT ISSUE?

**Comment by photopea** [comment]
I need you to describe me some steps, what should I do to see it myself. I could fix it in 30 - 50 seconds, if you could tell me how to make it happen on my computer.

**Comment by podunktimes** [comment]
https://github.com/user-attachments/assets/d37c0cee-eaf0-4a97-8813-d16952b16920

**Comment by podunktimes** [comment]
ivan my man u a real 1 i just wanna let you know i have NO extensions and no altered settings (i made sure)

if i could i would give you all da money in the world... but sadly i cannot

regards,

**Comment by podunktimes** [comment]
https://www.reddit.com/r/photopea/comments/1f4dn1y/font_keeps_changing_whenever_i_hit_enter_to_start/

**Comment by photopea** [comment]
Thank you, it is fixed now.
