### ISSUE TITLE
An image bug corrupting the project

### ISSUE THREAD

**Issue by XxEduGoDxX** [photopea/photopea#7122]
Your Operating System: Windows 10 Pro
Your Web Browser: Opera GX

Sometimes by doing anything, literaly ANYTHING at ANY time there's a small chance that on that same input of yours, every other image to the layer you're currently selecting from the last one will just be deleted, and after that you can say Bye bye to your project cuz by trying to save from this point beyond will result in an endless saving print message. If you also try to Ctrl+Shift+S (Which normaly works) it will save a 0 bytes file.

So, it means that if you dont manualy save a backup time to time you're taking the risk of losing ALL YOU PROJECT.

**Comment by photopea** [comment]
I need some proof, to make sure you are not making it up.

Did it ever happen in any browser other than Opera GX? It could be a bug in Opera GX.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
