### ISSUE TITLE
The display of the layer disappears

### ISSUE THREAD

**Issue by Enchante503** [photopea/photopea#7123]
The display of the layer disappears
You can see it when you press the F key, but the display disappears when you try to paint.
I can't see the brush and I don't know the position.

**Comment by photopea** [comment]
What web browser do you use? Did you try to disable all your browser extensions?

Please, file a proper issue - use the issue template. So that we dont have to ask you 10 more questions during the next 48 hours.

**Comment by photopea** [comment]
I dont have Ubuntu to try it out :(

Could you record a short video of how you open www.photopea.com and what happens next?
