### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Drevnii7** [photopea/photopea#7124]
Operating System: Windows 10 22H2 x64
Web Browser: OperaGX

I can move image, but im can't rotate and scale.
![изображение_2024-08-30_120616710](https://github.com/user-attachments/assets/aa9361ca-f225-42d4-b3a9-cfd8eb8be2ae)

**Comment by photopea** [comment]
I dont think it is Photopea. There is the "Account" button missing at the top of your screen. Is it www.photopea.com ?

**Comment by Tonnian** [comment]
Im on Photopea and I have the same problem : I can move image, but im can't rotate and scale.
(w11 + on the downloaded app) (I have also this issue on web (Brave))

**Comment by photopea** [comment]
There is a bug in Brave. Please, report it here: https://github.com/brave/brave-browser/issues/40619

**Comment by photopea** [comment]
I have to close it because the person did not respond :(
