### ISSUE TITLE
Uncaught ReferenceError: UPNG is not defined

### ISSUE THREAD

**Issue by lucadalli** [photopea/photopea#7125]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: 

Happened whilst using the API, not sure how to reproduce. Stack trace:
```
pp1725005979.js:3985 Uncaught ReferenceError: UPNG is not defined
    at pp1725005979.js:3985:45
    at pp1725005979.js:4002:163
    at pp1725005979.js:16804:163
```
![image](https://github.com/user-attachments/assets/8e63de6d-2dff-4bd8-84f3-b97e09e30350)

**Comment by photopea** [comment]
Do you see any other errors in a web console?

**Comment by photopea** [comment]
So it is not happening anymore? I dont know what could be the reason of this error.

**Comment by photopea** [comment]
can you reproduce it by opening www.photopea.com ?

**Comment by photopea** [comment]
I think it should not happen anymore.
