### ISSUE TITLE
Refine edge window goes in Blank mode

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7127]
Hello Evan..

Refine Edges.. multiple time open.. use and close it..
about 2nd or 3rd time it display blank like below image.. trying to zoom, change something but blank remains blank..
Then opening refine edges gives blank..
![Screenshot_2024-09-02_16-23-54](https://github.com/user-attachments/assets/8b8adebf-f243-4382-875d-0ef497708936)

**Comment by Mayur-hot** [comment]
[screen-recorder-mon-sep-02-2024-16-33-43.webm](https://github.com/user-attachments/assets/80d5a778-c7af-4fda-8b32-75233dbfd3d7)

just check this video to confirm...

**Comment by photopea** [comment]
What should I do to see it myself? Could you share your file and tell me what should I do with it?

**Comment by Mayur-hot** [comment]
some time this kind of blank occurs, I picked up a car file from gallery.... then tried for remove background...
created two selection layers..

[selection Layer 2]
[selection Layer 1]
[Background Image]

From background now we have two selection layers..
Then make selection Layer 1 as active.. (select this)

and if I click Refine Edge, see blank..

but If I make 2nd Layer as Active then it works.. so need to remove 2nd layer, either refine edge pick up last layer..

**Comment by photopea** [comment]
Please, make a proper report. Fill out the report template. It must include your web browser and other details.
