### ISSUE TITLE
NOT ABLE TO SELECT THE EDGES OF A SHAPE WHEN IT IT ROTATED AT AN ANGLE

### ISSUE THREAD

**Issue by ebeleguys** [photopea/photopea#7128]
Your Operating System: **MACBOOK PRO SONOMA**
Your Web Browser: **GOOGLE CHROME**
The problem happens in the Incognito Mode, too: **YES**

**This must be done to see the problem**
_**1. Create a shape
2. Rotate the shape at an angle
3. Try transform > distortion**_

![Screenshot 2024-09-02 at 4 58 30 PM](https://github.com/user-attachments/assets/589a4205-d4ff-4885-9450-550b26b9280a)
![Screenshot 2024-09-02 at 4 38 04 PM](https://github.com/user-attachments/assets/b349a1a9-2b5c-4024-8c97-100d51819d86)

**Comment by photopea** [comment]
This is how it should work in programs such as Adobe Photoshop or Photopea.

If you want to see the transformation rectangle of the original shape, use the Rectangle tool, not the Move tool.

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by ebeleguys** [comment]
I checked this in Photoshop and on the contrary, PS works differently. It snaps to the edges of the object.

**Comment by ebeleguys** [comment]
Also, I'm not sure what rectangle tool you are referring to, but I tried the rectangle select tool and it did not seem to do anything.

**Comment by photopea** [comment]
What exactly did you do in Photoshop? I am using the latest Photoshop and it works exactly like Photopea.
