### ISSUE TITLE
it happened again

### ISSUE THREAD

**Issue by podunktimes** [photopea/photopea#7129]
https://github.com/user-attachments/assets/bbb40323-42d4-4641-9e16-e223c07448de

**Comment by Mayur-hot** [comment]
I think pressing Back in Phone = Pressing escape key..

Escape = that removes textbox..

**Comment by Mayur-hot** [comment]
So, you have to type and then press enter or switch to new layer to save your action...

**Comment by photopea** [comment]
@podunktimes I have no idea what you are talking about. Your video has no sound. Please, file an issue and fill out the issue template, including your web browser, OS, and some steps how to make the problem happen. Do not send us random videos.

**Comment by podunktimes** [comment]
the size of the website shrinks when i try to type

**Comment by photopea** [comment]
Photopea shrinks because a keyboard appears on your screen. That is a correct behaviour.

**Comment by podunktimes** [comment]
the sidebar gets messed up

the only way to fix this so far has been to zoom out to the point i can barely see the buttons
