### ISSUE TITLE
Your Program is Garbage

### ISSUE THREAD

**Issue by omgitscool** [photopea/photopea#7130]
Your Operating System: Intel core I7 windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes, and on desktop

Program lags, freezes and crashes. This happens with any kind of professional use. It's Garbage

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by Mayur-hot** [comment]
I have different Opinion...... This Photoshop is really nice.

I am using linux Os.. I always keep old browser.. and then check any required web is working good or not in new updated browser.. many time, new updated browser even crashes google and youtube websites..
I always skip bad updates of browser.. and only accept good updates.. I don't like Auto Update of Browsers..

You may try other browser.. I don't suggest or advertise any browser.. but you can try and may be help..

My name is Mayur (just a guest user of photopea website..), I am not a developer..

**Comment by camoody1** [comment]
@omgitscool Does Ramteq know you're such an ass, Brian?
![image](https://github.com/user-attachments/assets/e43f63da-60f2-4c8c-a575-656b59d991ab)

**Comment by photopea** [comment]
I have to close it, as there are no steps how to reproduce the problem, or any other proof of a problem (e.g.a  video), so the user is probably making it up.

**Comment by photopea** [comment]
If you really had a problem, you would describe it. So please, stop spamming here.

**Comment by omgitscool** [comment]
I did describe it, your program lags, freezes and crashes. I have to save
every few minutes, close and reopen it about every thirty minutes. The link
you sent in the first response, I couldn’t open because my antivirus
software said it was Un advisable. That’s just a reinforcement of the
quality of your program. Take your attitude and shove it up your
egotistical ass.

**Comment by camoody1** [comment]
@omgitscool This you? 
![R (5)](https://github.com/user-attachments/assets/76420987-744f-4e62-8a82-3d1559542e91)

**Comment by omgitscool** [comment]
You’re right, I was upset. I didn’t know it was “a guy” that’s actually a
lot different. My apologies

**Comment by omgitscool** [comment]
Impressive actually, I thought it was an up and coming Adobe.

**Comment by camoody1** [comment]
@omgitscool This is Ivan. He is the creator and supporter for Photopea. Any other person you interact with is simply a fellow user who is willing to try to help you.
![image](https://github.com/user-attachments/assets/de6a04ee-d9a5-4f46-8bf1-14cad07b66ce)

**Comment by omgitscool** [comment]
Impressive work Ivan, you had me fooled to think a team of developers made
photopea. My apologies to you. If I can offer a suggestion, why not have
your bio and a picture on the opening screen of the program. I think it
would impress the hell out of everyone. I’m pretty sure I’m not the only
one who thought a company made it.
