### ISSUE TITLE
The projects I didn't save reappear every time I refresh the app. How do I fix this?

### ISSUE THREAD

**Issue by Diamondbro10795** [photopea/photopea#7131]
Your Operating System: ChromeOS
Your Web Browser: Chrome

**This must be done to see the problem**
1. Go to www.photopea.com
2. .... make a project
3. .... exit without saving
4. .... Refresh and look at the page

**Comment by photopea** [comment]
You did not mention the list of your extensions, which have your permission to rewrite the functionality of Photopea.

Try this: https://www.photopea.com/tuts/photopea-opens-up-old-files/

**Comment by photopea** [comment]
I think the article helped you solve the issue.
