### ISSUE TITLE
Drag-and-drop in Layers panel stopped to work in Chrome for Android 128

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#7134]
Your Operating System: Android
Your Web Browser: Chrome 128
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create several layers
3. Try to drag-and-drop layers

**Comment by camoody1** [comment]
Just as an FYI, dragging layers still works fine in Microsoft Edge for Android, even though it's based on Chromium, also.

**Comment by Mayur-hot** [comment]
Disable All Plugins of Chrome... and if problem not solved.. then install browser plugin/extension to record video of problem...., Video = Describe Better...

and if possible skip Chrome Version 128, and try in 129.. or stick to Chrome 127..

here new Browser version also haves few Bugs many time, and if developer solve that, and that will became bug again in next update. So better to Choose Proper Working Browser and Stick Till next better update and skip bad one..

Thank You.

**Comment by photopea** [comment]
@Mayur-hot hey, are you a bot?

**Comment by Mayur-hot** [comment]
> @Mayur-hot hey, are you a bot?

No, I am Human, Sorry for answer..., Do you remember, we solve issues like Plugin close(Uninstall using right click)...

I think you are one person, I just tried to give answer if possible, like send video....

I just answer for those, if you not answer them...

I am from India

**Comment by Mayur-hot** [comment]
If you don't like, then I will not answer any more.. :) no problem..
I am just giving spare time when I have to read issues... that's it..

**Comment by photopea** [comment]
There was no question for you to answer.

**Comment by photopea** [comment]
It seems like Google is ignoring it, so please, write here about it: https://issues.chromium.org/issues/363930156  or send emails to Google and aks them to fix it. I give it up.
