### ISSUE TITLE
Do not open JPG with Photopea in Google Drive as Default

### ISSUE THREAD

**Issue by tolotrasamuel** [photopea/photopea#7136]
I like the ability to open  JPG with Photopea directly from Google Drive using the Google Apps. But please, not as default. I just want to view the picture sometimes. 

For PSD files, for sure. I love it. 
But not as default for JPG and other Image files. Please.

I had to uninstall your Google Apps https://workspace.google.com/marketplace/app/photopea/463342976776?pann=ogb  due to that. 

Maybe for JPG, keep it openable manually through right click and Open With. Not on default double click. 

Or add a control panel letting the user to Otp-out for some specific file extensions. JPG, PNG,...

Your Operating System:
N/A
Your Web Browser:
N/A
The problem happens in the Incognito Mode, too:
N/A

**This must be done to see the problem**
1. Install Google Apps https://workspace.google.com/marketplace/app/photopea/463342976776?pann=ogb
2. Go to your Google Drive
3. Double click a JPG file (Not PSD)
4. Photopea is opening in a new tab

**Comment by photopea** [comment]
Ok, I have updated it to this list, I removed the JPG from primary formats.

It is hard to tell how long will it take to see the change. If it still opens JPG files two days from now, please, let me know.

![image (5)](https://github.com/user-attachments/assets/2dc8f260-9e3a-4e3c-a6d9-2a13b20d5e1c)
