### ISSUE TITLE
DDS Images color issue

### ISSUE THREAD

**Issue by Misanthropik** [photopea/photopea#7137]
Operating System: Windows 11 23H2 x64
Web Browser: Firefox 130.0

The colors in DDS image files are not displaying accurately, despite being converted to PNG format. A source DDS file, the converted PNG file, and an image showing the correct colors in the PHOTOS app are attached below.

![untitled](https://github.com/user-attachments/assets/5345d1b5-5ece-44cf-8dd5-1c4caad7fc72)
DDS Source Image > [untitled.zip](https://github.com/user-attachments/files/16901865/untitled.zip)
This is how it looks like in Photoshop and Photos app.
![Screenshot 001](https://github.com/user-attachments/assets/42ca6827-11d5-4051-be37-74fb74e0a138)
This is how it looks in Photopea
![Screenshot 002](https://github.com/user-attachments/assets/ee77a667-75fc-4dbc-8edf-0741da5cd12f)

**Comment by Mayur-hot** [comment]
![answer](https://github.com/user-attachments/assets/8bd980b8-de76-4338-bca9-1f0e1b0da1de)

**Comment by Misanthropik** [comment]
> ![answer](https://private-user-images.githubusercontent.com/176575844/365038119-8bd980b8-de76-4338-bca9-1f0e1b0da1de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDE1NzYsIm5iZiI6MTcyNTYwMTI3NiwicGF0aCI6Ii8xNzY1NzU4NDQvMzY1MDM4MTE5LThiZDk4MGI4LWRlNzYtNDMzOC1iY2E5LTFmMGUxYjBkYTFkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQwNTQxMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNmYwZjI3MmQzYTFkZDE0ZTY2ZDdmYTgwNjEyNzg2MTQ1ZmU3OTQxNGI5MGI5MTkwZTllNTk2YzEzNjBjZTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RZhNdOzX7jtNQJQ9qOPxXfKbByoaIpdAPBInot1QQEQ)

Can someone explain this in words please, I'm not familiar with the icons enough to tell what it's referring to, is it one of the Adjustment layers options?

**Comment by photopea** [comment]
You are saying that Photopea displays your DDS file in a wrong way. But what makes you think so?

You are saying that your DDS file looks differently in Photoshop and Photos app. But I can not even open it in Photoshop or the Photos app ... so what do you mean?

**Comment by photopea** [comment]
Just to be clear, your DDS file contains four color channels, and Photopea displays the fourth color channel as the transparency. If some software is throwing away the information from the fourth color channel, it is probably wrong.

I converted your DDS to PNG using this tool: https://convertio.co/dds-png/  and the PNG looks exactly as it looks in Photopea.

**Comment by Mayur-hot** [comment]
Even I tested in HoneyView + XNView in Windows OS + Linux, and it DDS file looks same as photopea with transparency, and Unable to open in Adobe Photoshop...
I think he is using other appx based photoshop in windows 11 that not support transparency.

**Comment by photopea** [comment]
I have to close it because nobody is replying :(
