### ISSUE TITLE
Bug: Text doesn't retain its color if you picked another color and reselect the text afterwards

### ISSUE THREAD

**Issue by xan2622** [photopea/photopea#7138]
Your Operating System: Windows 11
Your Web Browser: Firefox 130.0
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Choose a dark color (for example # 212c36) and use the Paint Bucket Tool to fill the background layer
3. Use the Type Tool and type a sentence, press CTRL+A to select the sentence and colorize it with a lighter text color (# 3d9aee)
4. Create a New Layer
5. Pick another color in the Color Picker (# ef316b)
6. Select a rectangle and use Paint Bucket Tool to fill the rectangle with that color
7. Deselect the rectangle
8. Click on the Type Tool icon (on toolbar on the left)
9. Click one time on your sentence to edit it, at this point you should notice that the whole sentence is colorized with the last color that you picked (# ef316b). 
IMO, this should not happen, the sentence should keep the color the user has chosen before (# 3d9aee) and should change : 
-- only if the user selects all the text (CTRL+A) then pick another color in the top bar.
-- only if after typing a text and confirming it with the ✅ and picking a color in the top bar while not in "text editon mode".

![Photopea_Color_Text_bug](https://github.com/user-attachments/assets/becdb308-939b-4071-bb33-685f83a428be)

**Comment by Mayur-hot** [comment]
Right, something is wrong between **paint Bucket + text tool.**. otherwise text color remains same, but Using Paint Bucket fill, text layer adopts last color... Its a BUG.

**Comment by Mayur-hot** [comment]
[screen-recorder-fri-sep-06-2024-16-55-00.webm](https://github.com/user-attachments/assets/5e76cf99-2121-4c5f-9185-d2cd16bc9772)

Wait for answer from Ivan

**Comment by photopea** [comment]
It should be fixed now.
