### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by imms93** [photopea/photopea#714]
This is a minor feature to ask for but someone could find it useful: Photoshop, when you create a new document, gives you the possibility to choose a template (I'm not sure that's how it's called, sorry but my English is limited), here's how it works

![gif](https://user-images.githubusercontent.com/30982542/39966383-1122a9e6-56ab-11e8-9ad9-7038c9477443.gif)

It may spare people like me googling document sizes all the time

**Comment by photopea** [comment]
BTW. I just added a possibility to enter the size in Inches or CM, and the DPI.

Do you know any database (a list) of these dimensions and how should we structure them?

**Comment by MichalSZZ** [comment]
I can help you in that case. Just give me some time. You can start with International paper dimensions. That is a ISO 216 standard (for all coutries without USA, Canada, Japan, Mexico).

**Comment by MichalSZZ** [comment]
Sizes for print:

1.  International Paper https://en.wikipedia.org/wiki/ISO_216 most common are  A (A4, A3, A5, A6, A2, A1, A0) and B (B5, B4, B3). There is a C size too, and it is often use in envelopes. Size DL (1/3 A4) is for the flyers fe. and can be put in DL envelope. 
![obraz](https://user-images.githubusercontent.com/38118273/40591079-b78ac22c-620a-11e8-9c07-f89ee65c0764.png)
![obraz](https://user-images.githubusercontent.com/38118273/40591080-bf9b747a-620a-11e8-83ed-ba69eaada935.png)

![obraz](https://user-images.githubusercontent.com/38118273/40591051-4ffae0c4-620a-11e8-9644-b4c9c5b8e5f5.png)

2. U.S. Paper https://en.wikipedia.org/wiki/Letter_(paper_size) letter, legal, tabloid fe.
![obraz](https://user-images.githubusercontent.com/38118273/40591094-0a50fb0c-620b-11e8-9639-4091df26da48.png)

3. Bussines cards (90x50mm, 85x55mm most of european countries, some use 90x55mm), 3,5x2in (USA and Canada) https://en.wikipedia.org/wiki/Business_card

4. Photo sizes (can be print and web sizes) https://en.wikipedia.org/wiki/Photo_print_sizes
![obraz](https://user-images.githubusercontent.com/38118273/40591374-30114ba8-6210-11e8-938a-43a415973028.png)


Sizes for web:

1. Google AdWords (and any other similar system)
https://support.google.com/adsense/answer/6002621?hl=en
![obraz](https://user-images.githubusercontent.com/38118273/40591294-e3f82bb6-620e-11e8-87c9-341ca65c7fac.png)
For static JPG, PNG and GIF there is a 150 KB limit 
https://www.adjelly.com/adwords

2. Facebook group ads (facebook, instagram) 
https://www.facebook.com/business/ads-guide/image
https://blog.bufferapp.com/facebook-ad-specs

3. Social media images sizes (cover photos, posts, profile photo e.t.c.)
https://www.adjelly.com/facebook for example - use menu icons on the left (really great site, but there can be an old specifications - facebook change it very often)

4. Popular frameworks (Bootstrap, Foundation e.t.c.). Layouts in PSD with visually shown columns variations and guide lines). It will be great for webdesigners. 
Or you can try to make a layout grid generator, as an option in photopea (width, number of columns, space between columns). That can be a modal window or new panel.

![obraz](https://user-images.githubusercontent.com/38118273/40591648-201b3132-6215-11e8-82b3-47db9b24099f.png)
https://hackerthemes.com/bootstrap-4-grid-psd/ 

to be continued  (laptop battery have down :) )

**Comment by MichalSZZ** [comment]
Google ads are only in these formats and cant be switched (728x90 is OK, but there isn't 90x728). Same thing is for all others web banner. For print, switching can be made with little paper sheet icon, like in any other programs (portrait by default, landscape as a option).

**Comment by MichalSZZ** [comment]
Good UI is very important in this case. First of all, i sugest to use Select element on the top. First option for the się can be "custome" (like now and two inputs for width and height). Next one (when user want to use size from template) should be (web).When user click and use this option, should show an another "Select" element with options.Now is hard to me to explain, how it should to work in 100%. But this templates will help users. And Yes, you are right. Anybody can type dimensions like now. But those templates will be the fastest way to make work without any mistake. I make banners from 10 years but when I fast typed parameters (from memory) in Photoshop, several time I made mistakes in dimensions.

**Comment by MichalSZZ** [comment]
<img width="1280" alt="obraz" src="https://user-images.githubusercontent.com/38118273/40780902-4c8beb90-64da-11e8-8da9-b6878039c469.png">

In Photoshop CC 15.5 it looks like above

<img width="1279" alt="obraz" src="https://user-images.githubusercontent.com/38118273/40780994-93198018-64da-11e8-8aa4-964bfc349b05.png">

And after choose option, parameters in main window are changing, like you can see on screens
<img width="596" alt="obraz" src="https://user-images.githubusercontent.com/38118273/40781325-b7e9edfa-64db-11e8-93b8-80218d824d9e.png">
<img width="580" alt="obraz" src="https://user-images.githubusercontent.com/38118273/40781344-ca231154-64db-11e8-95d7-41095da82975.png">
<img width="574" alt="obraz" src="https://user-images.githubusercontent.com/38118273/40781360-d8eb02c8-64db-11e8-98ac-249f4eb75abf.png">

This is one of the option how to show it. The new Photoshop UI, is showing that in one big window with tabs, and that is very good too. 
In older version in "Select" element, web and print and other groups are seperated with line <hr>. I think this is good for one "Select" item, for all document sizes types. I think, that is easier to develope now in Photopea. What do you think?

**Comment by photopea** [comment]
Hi, I added some size presets into a New Project window. What do you think?

**Comment by MichalSZZ** [comment]
What do I think? :) I think, that you are amazing!

This is a good start point for something big!
Now we have presets. But maybe in the future Photopea can be like Canva with her templates. 

What I see now and you can add/fix in the future:
1. When click on something for print, units should be switched from pixel to mm or inch
2. Bigger/diferent icon with arrows to switching from portrait to landscape
3. For print there isn't American formats (people from US are big % of your user) - but I know that, you will add this and that is only a preview of concept how to show that. Same thing for photos in cm for Europe users.
4. A little hints after hover on some formats (more informations for user where he can use it)
5. And last suggestion for now - after I create new print document, I want to have mm/in on ruler. In photoshop I can switch units by right mouse button click on ruler. That is very useful, when I must to mark (with guide lines) zone outside the trim area. Printing house give that sizes (for bleeds e.g.) in mm or cm/inch. 
But I think that should be a diferent issue/request for you.

![obraz](https://user-images.githubusercontent.com/38118273/40840777-6014c0e6-65a8-11e8-9c14-e8305004c915.png)

**Comment by photopea** [comment]
Thanks! :)

When the preset has inches and you hover it, you will see "mm" and vice versa :)

**Comment by MichalSZZ** [comment]
I think when you hover on the photo presets, it should be show in cm (not mm) and rounded without comma. Now when I hover on it, there is a inch to mm conversion 1:1
In Europe we use 9x13, 10x15, 13x17 naming (but the real size are diferent). First 2 (very common sizes) arn't in yours presets list.

Look at this site 
https://www.fotoskoda.cz/fotobox/#!/albums/new and there are sizes like 10x15

**Comment by photopea** [comment]
Many of sizes in your list correspond to current ones. E.g. now, we have 89x127 mm, and there is 9x13 cm in your list.

So what exactly should we have in our list? So we don't have the same size twice.

**Comment by MichalSZZ** [comment]
Hmm. Now we have 89x127 on the list? I don't see it :/
![obraz](https://user-images.githubusercontent.com/38118273/40960869-4394a1a6-68a1-11e8-8169-db707dc9738c.png)

9x13, 10x15 cm is official name of photo print. People know that names and from UX point of view, they don't want to see something in mm, that not correspond with size in cm (1:1). 9x13 is a format name, like as A4 in print (for 210x297mm)

**Comment by photopea** [comment]
What do you mean by "official name"? I found the current "official dimensions" on "official Wikipedia" :D

**Comment by MichalSZZ** [comment]
If you buy photo paper for ink printer, there is a big size 10x15 (as a name of format), but the real size of sheet is 102x152mm (small letters under) 
![obraz](https://user-images.githubusercontent.com/38118273/40962908-37322a40-68a7-11e8-8b20-9972cf58ef0f.png)
If you print photos in fotolab, there are names (in editor, in pricing tabel) like 9x13, 10x15, 13x18, but the real paper size of what you get is different.
