### ISSUE TITLE
FONT PROBLEM

### ISSUE THREAD

**Issue by antonioperales23** [photopea/photopea#7140]
HELLO, EVERY TIME I TRY TO ADD A FONT IT IS ADDED BUT IT WON'T LET ME PUT IT IN TO USE IT. DOES ANYONE KNOW ANY WAY TO DO IT?

**Comment by Mayur-hot** [comment]
Choose different Font, may be your font file is either corrupted.. (then try to Load Font --> Remember Name of Font may be different so when font loaded just look top message that have actual name of your font.. choose that font name, If you still face problem then try to open https://www.photopea.com in other web browser, may be some plugin is blocking... for here loaded fonts works fine.

**Comment by Mayur-hot** [comment]
https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I tried to open fonts in Photopea and it works fine. When you load it, do you tell Photopea to save it in the Local Storage, or you refuse it?

Maybe there are too many files in your Local Storage, and your web browser does not want to allow Photopea to save one more file. Look into Edit - Local Storage, and delete some items. Or simply tell Photopea not to save it to a Local Storage.

**Comment by photopea** [comment]
I have to close it because nobody is replying :(
