### ISSUE TITLE
New plugin - Side Calculator

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7141]
Plugin:

Link:
https://www.calculator.net/sitemap.html
Icon:
https://www.calculator.net/icon-16x16.png

This website have nice calculators, including all kind of calcs..
just need to make plugin and add it, I am not owner of this site,
but Owener have no issue to add his site..

Description:
Scientific Calculator
This is an online javascript scientific calculator. You can click the buttons or type to perform calculations as you would on a physical calculator.

**Comment by photopea** [comment]
You can publish your plugin to Photopea, as described here: https://www.photopea.com/api/plugins
