### ISSUE TITLE
PSD, EPS, AI file not opening

### ISSUE THREAD

**Issue by Dodo-code12** [photopea/photopea#7142]
Your Operating System: MacOs
Your Web Browser: Safari, Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....FIle
3. ....Open
4. ....Select a new PSD, AI, EPS file

**Comment by xan2622** [comment]
Hi. 

I have just opened a AI file, a EPS file and a PSD file (taken from [this website](https://all-free-download.com/free-vector/download/kia_carnival_2022_car_model_advertising_template_modern_flat_side_view_sketch_6925258.html)) without noticing any issue.

Could you please record your web browser (a GIF or better a MP4 video file would be fine) and show us all the steps that you did?

**Comment by photopea** [comment]
Yes, please, show us some proof that you can not open files in Photopea. I hope you did not make these PSD files by renaming MP3 sound files to PSD :D

**Comment by freecana** [comment]
hello, I can't open the file

**Comment by freecana** [comment]
![image](https://github.com/user-attachments/assets/f798f05d-76fb-41b8-bee4-b0ce8edacefc)

**Comment by photopea** [comment]
Can you open JPG files in Photopea? Did you try it in the Incognito mode?

**Comment by freecana** [comment]
Да, jpg открывается. Открывается файл fig, которому 5 дней. 
В режиме инкогнито файл, который я отправила не открывается


Отправлено из мобильной Почты Mail


суббота, 7 сентября 2024 г. в 22:52 +03:00 от ***@***.***  ***@***.***>:

**Comment by photopea** [comment]
Could you send me your file to support@photopea.com ? 

BTW. Photopea can not open Figma files that were generated by Figma in the last 5 days: https://github.com/photopea/photopea/issues/7143

**Comment by photopea** [comment]
I have to close it because nobody is replying :(
