### ISSUE TITLE
does not open a file in the fig format

### ISSUE THREAD

**Issue by freecana** [photopea/photopea#7143]
Your Operating System: windows 11
Your Web Browser: Ghrome yandex 
The problem happens in the Incognito Mode, too: yes

![image](https://github.com/user-attachments/assets/0aee68cb-5d68-4ace-bc1f-b3689ad8ce57)

**Comment by photopea** [comment]
It seems like Figma started to use a new format for their files. It is still named .FIG, but is much different than the old Figma files. We will need to analyze the new format.

**Comment by photopea** [comment]
It should be fixed now. Photopea can open any existing Figma file now.
