### ISSUE TITLE
Feature request: Keep aspect ratio disabled by default

### ISSUE THREAD

**Issue by xan2622** [photopea/photopea#7144]
Your Operating System: Windows 11
Your Web Browser: Firefox 130.0

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open any image of a "website button" that you'd like to modify to make it larger, for example [this one](https://www.deviantart.com/solidsilver/art/Free-button-collection-166423627)
3. Select the left edge of the button and move it to the left (CTRL + Left arrow)
4. Select a part of the central area of the button and copy it in a new layer (CTRL + J)
5. Right click on this new layer and select its pixels 
6. Click on the Move Tool and tick the Transform Control checkbox at the top
7. Start moving your cursor to the left to stretch the rectangle selection to the left
-- At this point, you should notice that the selection is resized on all directions 

![Photopea_Keep_Aspect_Ratio_enabled](https://github.com/user-attachments/assets/a86dfe6d-088a-451f-b7b4-2fc12115af5f)

Could you please consider to make the "Keep aspect ratio" checkbox **disabled** by default ?
![Photopea_Keep_Aspect_Ratio_disabled_by_default](https://github.com/user-attachments/assets/c80c3901-b5f0-42fa-8c93-cf45fe3ba3f6)

**Comment by photopea** [comment]
I think people want it to be enabled in 90% of cases.

the standard way of transforming stuff is pressing Edit - Free Transform. Then, you can disable "Keep aspect ratio" before you start transforming.

Also, you can hold the Shift key to switch between the two methods.

**Comment by xan2622** [comment]
> the standard way of transforming stuff is pressing Edit - Free Transform. Then, you can disable "Keep aspect ratio" before you start transforming.

I agree with this but my post (this Github issue) is not about this way of doing things (through the "Edit > Free Transform" menu). It's only about the other way: the user clicks on the Move Tool and ticks the Transform Tools checkbox in the options bar at the top. At this moment, the user doesn't have the possibility to disable the Keep Aspect Ratio checkbox.

The issue is that this bar : 
![Photopea_Keep_Aspect_Ratio_disabled_by_default](https://github.com/user-attachments/assets/c80c3901-b5f0-42fa-8c93-cf45fe3ba3f6)
.. appears only **after** you have started to resize the layer (while using the Move Tool). 

If the user didn't want to resize the layer in all directions, he/she has to cancel the last action, disable the "Keep Aspect Ratio" checkbox and start again. That's what is annoying. 


> Also, you can hold the Shift key to switch between the two methods.

Thanks, I didn't know about this hotkey.

**Comment by photopea** [comment]
If the user wanted to keep the aspect ratio, and it was disabled by default, it would be equally annoying.
