### ISSUE TITLE
Transform tool is not working

### ISSUE THREAD

**Issue by somirons** [photopea/photopea#7145]
Your Operating System: Arch Linux
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too: Not tested

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Could you show us a screenshot of your screen when the problem happens?

**Comment by photopea** [comment]
I have to close it because nobody is replying :(
