### ISSUE TITLE
Rezizing doesnt work

### ISSUE THREAD

**Issue by Endlses** [photopea/photopea#7146]
Your Operating System: Windows
Your Web Browser: OperaGX
The problem happens in the Incognito Mode, Not Tested

This must be done to see the problem
1. Go to www.photopea.com
2. Try Rezizing a image
3. Might not work for me
4. Fix Fast

**Comment by photopea** [comment]
Could you share a screenshot of Photopea when it happens?

**Comment by photopea** [comment]
I have to close it because nobody is replying :(
