### ISSUE TITLE
No me deje usar los tipos de letras que tiene el fhotopea 

### ISSUE THREAD

**Issue by limberg11** [photopea/photopea#7147]
"Dear Fhototypea Team,

I am writing to express my frustration with the current state of your font offerings. Despite having a vast library of over 100 fonts, I am only able to access and use a limited selection of 5 fonts. This is unacceptable and severely hinders my ability to edit and create content to my liking.

It appears that there is a technical issue or glitch that is preventing me from accessing the full range of fonts. I urge you to investigate and resolve this matter as soon as possible.

As a user, I expect to have full access to the features and resources that your platform offers. I hope that you will take immediate action to address this issue and restore the full functionality of your font library.

**Comment by photopea** [comment]
Please, tell me what should I do to see a problem which you describe. What is "having a library of fonts"? Where do you have it? Why do you think Photopea should see your "library of fonts"? Is it on a DVD?

**Comment by limberg11** [comment]
Dear Support Team,

I'm experiencing a frustrating issue with Photoshopea. When I try to edit text, I'm only able to use 5 specific fonts, and the rest of the fonts are greyed out and cannot be selected. It's as if they are blocked or locked.

I've tried to access the font menu, but I'm unable to select or change to any other font besides the 5 that are available. This is limiting my ability to edit and create content effectively.

I would appreciate it if you could look into this matter and resolve the issue as soon as possible. I need to be able to access and use all the fonts available in Photoshopea.

Thank you for your attention to this matter.

**Comment by photopea** [comment]
I need to see some proof, to know that you are not making it up. When I use Photopea, I see thousands of fonts. Could you record a short video of a problem, or at least a screenshot, as a proof?

**Comment by limberg11** [comment]
[Uploading 0.2122.zip…]()

**Comment by limberg11** [comment]
Uploading 0.mp4…

**Comment by Mayur-hot** [comment]
> Uploading 0.2122.zip…

Your video is not uploaded ... here can't get video, clicking your link is not downloading anything, so please try again...
Thank You

**Comment by photopea** [comment]
@limberg11 are you replying at a website www.github.com ? Did you even see your comment after writing it, or did you try to play your video?

**Comment by limberg11** [comment]
Uploading 0.mp4…


https://github.com/user-attachments/assets/8642c217-426b-4d71-af3e-8f58d6dc80ce

**Comment by limberg11** [comment]
1. "Hey, I'm having an issue with Photoshopea. As you can see in the video, I'm trying to select different font types, but it won't let me. I've tried clicking a thousand times, but nothing changes. Does anyone know what I can do to fix this problem?"

**Comment by Mayur-hot** [comment]
> 1. "Hey, I'm having an issue with Photoshopea. As you can see in the video, I'm trying to select different font types, but it won't let me. I've tried clicking a thousand times, but nothing changes. Does anyone know what I can do to fix this problem?"

clean your browser file cache and try again, May be you have some corrupted files..

**Comment by Mayur-hot** [comment]
Mouse Hover  --> Click
Because simple mouse over will not change font.., try in other browser

**Comment by limberg11** [comment]
"I'm clicking on each font with my mouse, but it's not changing. I've even cleared my browser's cache data, but the issue persists."

**Comment by limberg11** [comment]
"Even when I open a new image with a standard size, without any corrupted files, the issue persists and I'm unable to find a solution. This is frustrating because I'm unable to fully express my creativity while editing, as I'm limited by this font selection problem."

**Comment by Mayur-hot** [comment]
Only Ivan is Developed whole photopea, I am not developer.

https://www.photopea.com/tuts/ads-in-photopea-do-not-work-what-to-do/

**Comment by photopea** [comment]
I see your screenshot says "Autómovil club británico".

![image (9)](https://github.com/user-attachments/assets/ae2f0fae-d1d5-45b8-a3ce-a896efb3abef)

www.Photopea.com never says "Autómovil club británico", no matter what settings you apply, there is simply no such phrase in our code. Please, try these three things:

- make sure you are opening www.photopea.com . Do not open www.photoooopea.com or any other website, as it is not Photopea.
- make sure you are not telling your browser to translate, or modify Photopea in any other way. 
- make sure you do not have any browser extesnions that are allowed to modify Photopea. If you do not know what your extensions do, simply turn off all your extensions.

**Comment by photopea** [comment]
I have to close it because nobody is replying :(
