### ISSUE TITLE
Error 401: user's secret was already generated

### ISSUE THREAD

**Issue by Mbangula275** [photopea/photopea#7148]
Your Operating System: 
Your Web Browser: chrome, edge, safari
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Log in, account button turn orange
3. Try to enter in my peadrive

**Comment by photopea** [comment]
Could you tell me the email address that you use when you log in to Photopea? Press "Account" at the top to see that email address.

**Comment by Mbangula275** [comment]
cl55bn91@gmail.com

**Comment by photopea** [comment]
okay, it should be fixed now.
