### ISSUE TITLE
does not open a file in the .fig format

### ISSUE THREAD

**Issue by Kangstop00** [photopea/photopea#7149]
Your Operating System: macOS
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: yes

![스크린샷 2024-09-09 오후 12 16 05](https://github.com/user-attachments/assets/1f735e68-57ee-4cd1-bcbd-b6178969a2e6)

**Comment by photopea** [comment]
Could you please send your file to ***@***.***, so that we can
solve it, as the message says?

**Comment by photopea** [comment]
Could you please send your file to support@photopea.com, so that we can solve it?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
