### ISSUE TITLE
Ability to search menus

### ISSUE THREAD

**Issue by BranchS** [photopea/photopea#715]
Under more, it would be great to be able to search the other menus... so like I would type in "Inverse" and it would pull up the inverse function without me having to dig through the menus because I don't remember where it is. Photoshop has this feature.

**Comment by photopea** [comment]
The current structure does not allow adding such feature easily. I recomment to use a regular web search engine. After you search for "Inverse Photopea", you should get a right result.

**Comment by BranchS** [comment]
Hi! While searching the web does help locate the menu, something like this would be much easier. Hopefully it can be added in the future.
<img width="354" alt="screen shot 2018-05-31 at 8 28 05 pm" src="https://user-images.githubusercontent.com/38893932/40814926-27a8585e-6511-11e8-8b5d-3540e8ee8701.png">

**Comment by photopea** [comment]
Hi, it has been implemented, see here: https://github.com/photopea/photopea/issues/1727
