### ISSUE TITLE
Non-optimal plugin window size

### ISSUE THREAD

**Issue by yikuansun** [photopea/photopea#7150]
Continuation of #3686 . Making a new Issue because that one is closed.

**Comment by yikuansun** [comment]
The idea here is to use 300x485 for the default plugin size, but let the developer change it using the old plugin `width` and `height` properties. That way, plugins can default to their ideal dimensions, just like every other side panel.

**Comment by Mayur-hot** [comment]
Hello yikuansun

+ Plugin developer will not test their plugin's look for all kind of screens either desktop, mobile, iphone...
Plugin is just a small window, not a browser..
for large space, developer can use popup window to preview big image.

so, 1) fixed size 2)resize from corner 3) popup window

above three is working nice, 4 (customized by developer) is NOT a good idea.

**Comment by photopea** [comment]
I have implemented the "w" and "h" parameters of the plugin, as the initial size, see https://www.photopea.com/api/plugins

Do you think these should be the "minimum initial size"? I.e. if there is a lot of space on the screen, should Photopea make your plugin bigger than the "w" and "h" which you entered?

**Comment by yikuansun** [comment]
@photopea I like the new `w` and `h` parameters. Thanks so much for implementing them!
I don't think there needs to be a "minimum initial size."
I only have one issue left, which is that when you close a plugin and reopen it, the size will reset to the same as Gallery. Ideally, it would preserve the height from the last time you opened the plugin (just like if you were to open and close Info or Properties).

On a separate note, is there a way for me to edit my plugin files without resetting install count? Last time I tried to update a plugin icon, it set install count to 0 (since I was technically uploading a new JSON file). I'd like to add the new `w` and `h` parameters into my plugins.

**Comment by photopea** [comment]
Would it be ok if I make plugins non-resizable, if they specify "w" and "h"?

**Comment by yikuansun** [comment]
@photopea Not sure, that would definitely be less user-friendly... Would preserving plugin dimensions be difficult to implement?

What if, say, when the user opens the plugin and Photopea loads the plugin `url` into the iframe, you just set the iframe's width to `w` and the height to `h`? This way, the plugin would be automatically opened to its optimal size, but the user would still be able to resize it afterwards.

**Comment by photopea** [comment]
okay, it should be fixed now.

**Comment by yikuansun** [comment]
@photopea Awesome; thanks so much!

On a separate note, can I update my plugin files without resetting download count? Right now, if I modify my plugin JSON and reupload it, it will set the install count to 0, since Photopea considers the new file to be a different resource.

**Comment by photopea** [comment]
I think each uploaded file has a different ID, so you will have to start from zero. Also, people who installed the old version of your plugin will keep using the same JSON file.

**Comment by yikuansun** [comment]
@photopea Do you think you could make a way to update resources (so download count would not reset and the file would automatically be replaced for users)? I would like to fix my plugin window sizes, but I am not willing to reset my download counts because I'm quite proud of them.

**Comment by photopea** [comment]
It would be too much work, sorry :(

I am still not convinced that it is correct to let plugins decide how large they are. Your plugin could ask the user to enlarge the plugin window, and the user decided yes or no.
