### ISSUE TITLE
text wont load and page still loading, have cleared history cache

### ISSUE THREAD

**Issue by belarenapparel** [photopea/photopea#7151]
Your Operating System: windows 10
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....start new project
3. ....click text button
4. ....drag open text window 
5. make sure text colour is contrast to the background colour
6. make sure text size is big enough to be visible
7. try clicking the tick button
8. try double clicked the text layer
9.

**Comment by photopea** [comment]
Hi, what is "drag open text window"? Could you record a short video of what is happening?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
