### ISSUE TITLE
Crop greyed out

### ISSUE THREAD

**Issue by suburbansteve** [photopea/photopea#7154]
Your Operating System:windows 11
Your Web Browser:Crome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....
Just noticed that the crop funtion has greyed out, was ok previously, all exstentions turned off and restarted but to no avail.
Not sure when the last time I used this function.

Thanx.

**Comment by photopea** [comment]
Are you talking about opening www.photopa.com and pressing "Image" at the top, and then, pressing "Crop" in a drop-down menu? It would really help if you told us what you are talking about. I expect you are talking about Image - Crop.

What exactly do you want to happen after pressing Image Crop? What shold be cropped?

In programs like Adobe Photoshop or Photopea, Image - Crop crops the photo according to a current selection. It can not be used if there is no selection.

**Comment by suburbansteve** [comment]
I was using the crop tool to adjust the canvas size but its been a while since I last used it and was remembering the procedure wrong, after playing around in Photopea I found out where I was going wrong and corrected it.
Sorry for the trouble, you can close this now, thanx
________________________________

**Comment by photopea** [comment]
Whenver you need to find a tool or a feature in Photopea, click the magnifying glass button at the top. It also says that you can switch to the Crop tool by pressing "C" on your keyboard.
![image (12)](https://github.com/user-attachments/assets/3a3e2c1f-6061-409e-90aa-1fe3efe8b0d8)
