### ISSUE TITLE
O Cursor do Mouse  

### ISSUE THREAD

**Issue by Athusxxx** [photopea/photopea#7155]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....O Cursor do Mouse nao selecionar da maneira correta, a área selecionada ficar sempre longe do local da seleção.
3. .... exemplo vou selecionar uma área no centro, e a marcação sair em cima de onde eu quero, por que isso ocorre e qual a solução.
4. ....

**Comment by photopea** [comment]
Sorry, I speak only English :( could you ask a friend to explain what you need in English?

**Comment by bluep55** [comment]
Go to Edit > Preferences and set Curser Offset to 0.

![screenshot-1](https://github.com/user-attachments/assets/ff488c0f-ade0-4529-a418-455f2fffd81b)

**Comment by Athusxxx** [comment]
deu certo, obrigado... muito mesmo, fiquei dois dias tentando mudar isso.
