### ISSUE TITLE
Exportar formato AVIF

### ISSUE THREAD

**Issue by WintorABC28** [photopea/photopea#7156]
Buenos días Photopea, quería informar ¿Por qué no se puede exportar en formato AVIF? ya este es un formato Popular, donde GOOGLE en su reciente actualización ya es compatible: https://developers.google.com/search/blog/2024/08/happy-avifriday?hl=es-419 puedes agregar esa función, encantado. mil gracias.

**Comment by photopea** [comment]
You are the first person asking for AVIF export. Some people think AVIF will not get pupular, since JPG XL should replace it.

**Comment by WintorABC28** [comment]
Sería, bueno que lo implementara dentro de Photopea, además que si no fuera importante GOOGLE y otras grandes empresas como Wordpress no acturalizarían a este formato AVIF. Sería genial si se implementa en Photopea. Muchas gracias

**Comment by photopea** [comment]
Sorry, I speak only English, I do not understand what you are saying :(

**Comment by Mayur-hot** [comment]
> Sería, bueno que lo implementara dentro de Photopea, además que si no fuera importante GOOGLE y otras grandes empresas como Wordpress no actuaralizarían la compatibilidad con este formato AVIF. Sería genial si se implementa en Photopea. Muchas gracias

Spenish To English Translation Only..

It would be good to implement it within Photopea, and if it were not important, GOOGLE and other large companies such as Wordpress would not update compatibility with this AVIF format. It would be great if it is implemented in Photopea. Thank you so much

**Comment by Mayur-hot** [comment]
English link for avif related..

https://developers.google.com/search/blog/2024/08/happy-avifriday

**Comment by Mayur-hot** [comment]
![Screenshot_2024-09-16_10-47-33](https://github.com/user-attachments/assets/72c7835b-8232-4fad-ba63-ad9d5d81dba0)
A plugin that have Export AVIF functions..

**Comment by Mayur-hot** [comment]
> Buenos días Photopea, quería informar ¿Por qué no se puede exportar en formato AVIF? ya este es un formato Popular, donde GOOGLE en su reciente actualización ya es compatible: https://developers.google.com/search/blog/2024/08/happy-avifriday?hl=es-419 puedes agregar esa función, encantado. mil gracias.

You got answer ? Just install Plugin to export AVIF

**Comment by Mayur-hot** [comment]
Hello Evan, You can close this issue, because export to AVIF is available via plugin "JPEG XL, AVIF, HEIC Plugin" and its working fine..
thanks..

**Comment by photopea** [comment]
You can export to AVIF in Photopea now.

But it is quite slow: about 1.2 seconds per megapixel. You can enable "Smaller files", which will take 5x more time (6 seconds per megapixel), but can produce 10 % to 15 % smaller files.
