### ISSUE TITLE
HTTP Error: 401: User's secrete was already generated

### ISSUE THREAD

**Issue by grenesto** [photopea/photopea#7157]
Your Operating System: Windows 10 Pro
Your Web Browser: tried both on Chrome and Firefox
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. log into account
3. try to access PeaDrive
4. Get error message
![error message](https://github.com/user-attachments/assets/205ee8b6-a9bd-4a5f-964d-66a11c28e4a0)

**Comment by photopea** [comment]
Could you tell me the email address of your Photopea account?

**Comment by grenesto** [comment]
It's ***@***.***

Thank you

Em sex., 13 de set. de 2024 às 18:11, Photopea ***@***.***>
escreveu:

**Comment by photopea** [comment]
Please, open www.github.com in your browser and repsond there. Do not send emails to random email addresses.

**Comment by grenesto** [comment]
If I reply here will my email be visible to all?

btw, on the footnote of the message said I could reply to the email directly as per the screen capture.
![Captura 2](https://github.com/user-attachments/assets/25573796-aae1-4ce8-89c6-61a540b0151f)

**Comment by photopea** [comment]
It seems like when you send email addresses to Github, they do not show it to us, as you can see in this discussion.

You can send me your email address to support@photopea.com . I am sharing my email address with everyone, I dont think there is any "danger" to it, it is not like people can steal your money by knowing your email address.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
