### ISSUE TITLE
Unable to close DialogBox

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7158]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....
[screen-recorder-sat-sep-14-2024-07-07-09.webm](https://github.com/user-attachments/assets/dce16c05-939e-41fc-bbbf-53b8fe1b2e7c)

see above video, clicking OK button, exit button still child dialog not responding on exit/ok/close
Steps:
New -> Blank Screen 1366x768.. Then add Image from Gallery.

Remove white background layer then click Image->Reveal All to show full gallary image.

Press Ctrl+U, Now Range: Choose Red.. Now Click Sample Hue + icon....
Close Color DialgBox (This time its working) Just close color dialog box only.. and then

Now Tick Colorize Again..

then choose red again and then click Sample Hue + icon...

that will not show color dialog box, clicking multiple time, we get color dialog box.. but that 

Thanks You Ivan

**Comment by photopea** [comment]
I don't know how to do your steps :( Could you explain, please?

"click Sample Hue + icon..." - should I click the text "Sample Hue"? And what icon should I click? No color dialog box is opening.

"Tick Colorize Again.." - should I tick it again? but you never said to tick it before that, right?

**Comment by Mayur-hot** [comment]
"click sample hue + icon..." = 
![Opera Snapshot_2024-09-14_143500_localhost](https://github.com/user-attachments/assets/83416c6f-1251-4ca8-b63c-8653d2fc1274)

1= clicking Range and choose red option will enable sample hue... 
2= Sample Hue: just double click on icon.. to show color picker..

--> Now close color picker.. then
3 = tick colorize..

then repeate step 2.. and then try to close color picker.. (Now Impossible to close color picker..)

**Comment by Mayur-hot** [comment]
![Opera Snapshot_2024-09-14_203937](https://github.com/user-attachments/assets/3f977eed-3525-46fb-ae96-4b6fa84ef83d)

**Comment by Mayur-hot** [comment]
[Uploading screen-recorder-sat-sep-14-2024-20-44-26.webm…]()
see this video...

**Comment by Mayur-hot** [comment]
[screen-recorder-sat-sep-14-2024-20-44-26.webm](https://github.com/user-attachments/assets/13816021-f233-482b-a74e-bd6d080cd0d5)
check  this video...

**Comment by Mayur-hot** [comment]
Hello Ivan..
You checked Above Video? https://github.com/user-attachments/assets/13816021-f233-482b-a74e-bd6d080cd0d5

Issue of Sticky Color Dialog.. not able to close either pressing X or OK button

**Comment by photopea** [comment]
I think I have fixed it. You should not be able to double-click these buttons and open a color picker.
