### ISSUE TITLE
Writing problem

### ISSUE THREAD

**Issue by LovaaOk** [photopea/photopea#7159]
Good morning, 
I have a problem, when I go to the text tool and I select a writing it doesn't work there are some writings that work and others not

**Comment by photopea** [comment]
What is "select a writing"?

**Comment by LovaaOk** [comment]
select a font

**Comment by Mayur-hot** [comment]
Hello LovaaOk,
just use browser extension to record your browser activity.... so Developer can able to understand problem.... 

just record video and drag and drop and wait till Uploading done.... and then write your issues.
Thanks (I am not a developer or part of photopea, Ivan is the only one developer)

**Comment by LovaaOk** [comment]
ok i will do it

**Comment by photopea** [comment]
Your PSD could use fonts like Helvetica, which is quite expensive, and we do not have a licence to provide these commercial fonts to our users for free. If you own that font, load it into Photopea using File - Open, and load a TTF / OTF file.

Please, discuss it at https://www.reddit.com/r/photopea/ , as it is not a problem in Photopea.
