### ISSUE TITLE
stucking in loading  templates

### ISSUE THREAD

**Issue by E-1234-man** [photopea/photopea#7160]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:
![image](https://github.com/user-attachments/assets/84ddde09-f09e-466b-baac-650c866d3f41)

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. .
![Screenshot 2024-09-16 184203](https://github.com/user-attachments/assets/e6424983-a581-4706-827a-b7974454dfdf)

**Comment by E-1234-man** [comment]
stucking in loading

**Comment by photopea** [comment]
Where are you located? Are you in Turkey?

**Comment by E-1234-man** [comment]
iam located in pakistan iam too need for this software plzz help me

**Comment by E-1234-man** [comment]
thanks hogya

**Comment by photopea** [comment]
Do you still have any problems?

**Comment by Mayur-hot** [comment]
> Do you still have any problems?

hogaya (in hindi language) = Its Ok Now

You can close this issue...
