### ISSUE TITLE
magic replace not working, premium user

### ISSUE THREAD

**Issue by random302** [photopea/photopea#7161]
Your Operating System: Windows 
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by camoody1** [comment]
@random302 I am a premium user, too, and the Magic Replace tool is working successfully for me as of 12:52AM EST.

**Comment by random302** [comment]
It was working half an hour ago after watching free ads then it prompted me to pay since it's a premium feature so I did but it's still not working. What could be the problem?

**Comment by camoody1** [comment]
@random302 Silly question, but I assume you were able to login successfully with your new Premium Account? The "Account" icon at the top of your screen is green, now?

It would probably be helpful to the dev if you described exactly what you're doing and exactly "how" it is failing. Error message? Timing out? Is there a screenshot you could share?

**Comment by Mayur-hot** [comment]
> It was working half an hour ago after watching free ads then it prompted me to pay since it's a premium feature so I did but it's still not working. What could be the problem?

Thanks for reply...

Please use browser extension to record your bowers activity.. That will help developer Ivan a Lot to understand problem..

Please send video of your actions to understand issue in better way...

(I am not a developer, Ivan is the only one developer)

Thank you.

**Comment by random302** [comment]
https://github.com/user-attachments/assets/a699f5a5-d190-4b6d-8b31-95d24cd7227c

**Comment by camoody1** [comment]
I'm guessing you've got a browser extension causing you problems. After clicking the "Replace" button, SOMETHING should happen - whether that be an error message or a "Processing..." message. Try disabling all of your browser extensions and see if it starts to work for you. If it DOES work, re-enable each extension one at a time and keep trying the Magic Tool to figure out which extension is causing you the issue.

**Comment by random302** [comment]
Thank you @camoody1 I'll try that and update you guys. Thank you for taking the time to help me.

**Comment by Mayur-hot** [comment]
use this link http://www.photopea.com/

in your normal browser.. also allow ads.... for www.photopea.com...

I see X button right side, your photopea interface looks different.. so may be you are using altered version or  Web APP is not capable..

Try in normal browser...

**Comment by camoody1** [comment]
@Mayur-hot I use the App version of Photopea and have no problems with the Magic Tool. That is not his/her issue. Also, since they are logged in as a Premium user, they will not have an ads section on their screen.

**Comment by Mayur-hot** [comment]
https://www.photopea.com/tuts/premium-account-does-not-work/

**Comment by camoody1** [comment]
> https://www.photopea.com/tuts/premium-account-does-not-work/

This blog post has nothing to do with the problem the OP is having. He is not seeing ads on his screen and he is not supposed to. His issue is only that the Magic Replace Tool is not working.

**Comment by random302** [comment]
Sorry guys it's still not working. I've disabled my extensions and tried clicking the replace button again but nothing's happening. I restarted my computer did the same. Also tried using different images and prompts and on other browsers.

**Comment by random302** [comment]
Maybe it will work if I try again in a few hours as I did with some other problems I've encountered with this app/browser. I'll check in again later. Thanks for commenting @camoody1 @Mayur-hot

**Comment by camoody1** [comment]
@random302 Can you get to this website? https://dezgo.com/txt2img
This is where Photopea processes its AI images.

**Comment by photopea** [comment]
Are you connected to the internet? All features of Photopea can run without the internet, except of the Magic Replace.

Also, have you tried the Magic Replace on other images? Maybe your image is "cursed" somehow.

**Comment by random302** [comment]
It turns out that the magic replace tool can’t handle larger file sizes. The images I was using were over 20MB. I had to compress them before uploading to Photopea again, which solved the issue.

Thank you all so much for taking the time and effort to assist with this issue. We can close this now.

Apologies for bringing up this minor issue.

**Comment by photopea** [comment]
Magic Replace should handle any size. Please, share your image with us, so that I can see that there really is a problem.

**Comment by random302** [comment]
@photopea If it helps, here are the images I'm trying to use. https://drive.google.com/drive/folders/1keUjdB8kaTkdNE6pRs6pDoJtLfO-asq9?usp=sharing

**Comment by photopea** [comment]
you are working with 16-bit images, and the Magic Replace could not process it. I have fixed it and it should work now.

![image](https://github.com/user-attachments/assets/de300379-2b64-4122-98fd-ac51946540b9)
