### ISSUE TITLE
sticky dialog (Not able to close)

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7163]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....
steps in video how to product.. at last unable to close dialogs.
[screen-recorder-sat-sep-14-2024-20-44-26.webm](https://github.com/user-attachments/assets/2d9cda07-9961-4637-b18c-932928979006)

**Comment by Mayur-hot** [comment]
[screen-recorder-wed-sep-18-2024-10-43-54.webm](https://github.com/user-attachments/assets/ddac0cc1-5e09-4c03-8d39-aac745f24f9a)

second video after refreshing.....

**Comment by bluep55** [comment]
I've just tried to reproduce this, and if you double click the 'Sample Hue' icon instead of using a single click, it brings up the Color Picker window. If you click on the X (top right corner) the window closes as it should, but if you click on OK, it causes Photopea to completely lock up.

**Comment by photopea** [comment]
I think I have fixed it. You should not be able to double-click these buttons and open a color picker.
