### ISSUE TITLE
[Feature request] All-in-one selection modifier

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#7166]
Currently, the selection modifications are organized in separate windows. It takes 3 clicks in menu to open one window. Using more than one requires even more clicks. Combining them all into one window makes it more handy, with only 2 clicks to use all selection modifications.

## All-in-one selection modifier
- **Border**: Check to switch to border mode. Replace Shift with Width. 
- **Shift and Width**
  - **Shift**: Positive value for expanding. Negative value for shrinking.
  - **Width**: Border width
  - Values could be preserved when switch between modes, and restored when switch back.
- **Smooth**
- **Feather**
- **Apply at canvas bounds**
![Frame 14](https://github.com/user-attachments/assets/7c2854ed-ad57-48ef-81e1-8f06d6b8b51a)

There is already a shortcut for Feather (<kbd>Shift + F6</kbd>). It could be used for this all-in-one selection modifier since Feather is included.

**Comment by photopea** [comment]
Should there be a switch between "feather before Expand" and "feather after expand"? Or "smooth before feather" and "smooth after feather"?

**Comment by photopea** [comment]
Honestly, nobody asked for it in the 11 years of our existence, and I think nobody will use it, as everyone is used to do it the current way. When you need to just apply feather, looking at a window with one value is not as bad as looking at a window with five values, when you have to read each parameter to find what you want. So I think nobody needs it and nobody will use it.
