### ISSUE TITLE
TAG Ads keep auto-opening on new Mac Update

### ISSUE THREAD

**Issue by jcfoto** [photopea/photopea#7167]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
What are TAG ads? Could you share a screenshot of it? Make sure you are using Photopea without browser extensions, since certain browser extesnions insert their own ads into websites.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
