### ISSUE TITLE
Increase history size

### ISSUE THREAD

**Issue by cow1337killer3** [photopea/photopea#7168]
There should be a setting to let us set a specific number of undo/redo history steps that will be saved. I don't really see any reason to not provide this for paid/premium users, since it's just using our own browser's memory/storage.

**Comment by photopea** [comment]
Are you a paid user? You should have 2x more steps in History than non-premium users.

The real problem with this is, that if you work with large documents, keeping too much "old data" in History could make your computer run out of RAM. In such a case, your web browesr might even kill Photopea (turn it off without giving you any chance to save your work).

**Comment by photopea** [comment]
I have to close it because of lack of details :(
