### ISSUE TITLE
active / inactive tab colors

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#717]
Tabs control is supposed to have currently active tab looking as if "in front":
https://en.wikipedia.org/wiki/Tab_(GUI)
So it's logical to have the active tab's label to be the same color to show it's the same surface, while color other tabs' labels differently, to make them look overlapped by the active page.
Your design got it backwards: the label of an inactive tab has a color, although not exactly the same, comparatively close to the color of the tab itself. Whereas active tab's label has a color that separates it from its tab (whereas they should be one).
I caught myself on that I always have problems figuring which one is active.

**Comment by photopea** [comment]
The label color is deduced from the panel background. It is used in many other places, see here:
![fdzg2f3](https://user-images.githubusercontent.com/15955558/40547583-a0b8251e-6032-11e8-9250-bcf5258b084a.png)

The brithter label is the active label. Just in the workspace area, the canvas is black, so it is confusing. Maybe we should make the canvas background the same bright grey as the active label?

**Comment by photopea** [comment]
So I think it is better to keep the color.

**Comment by ewnjtgouierg** [comment]
I don't really think making active tab color different in different types of windows (panels vs. main edit area) would be confusing. I bet you could even have some panels styled with the inverse colors, as long as tab colors correctly follow the UI pattern, there'd be no problem. We don't remember the colors when we use this UI metaphor, we rely on where the same color with bg is. Same in real life, we look on the label of the page that is on top, we don't care about the color. Here its just the equality of label color with bg color imitates the absence of the overlapping. But WHAT is the color is irrelevant, as long as its not different from the bg. As now it is more confusing b/c the pattern is followed in some, and not in other. And where it is not, it works strongly against the very UI pattern that is used - very un-usability thing.

**Comment by photopea** [comment]
I think it is just a matter of time, until you get used to it. You can use a Silver theme (More - Theme - Silver), which may be clearer to you (the canvas surrounding has the same color as e.g. the toolbar) .

**Comment by jaredlt** [comment]
@photopea I wonder if you would be open to re-opening this issue? I admit that even after months of use I still struggle to identify which tab is the active one :/

I took a look at the Photoshop interface to see what UX differences they may have. When I look at the below I find it clearer which tab is active (the tab on the right):

![photoshop-tabs](https://user-images.githubusercontent.com/8590311/90134471-2036fa80-dd69-11ea-92fd-9519805fa906.jpg)

Compared to the current existing Photopea design (active is also on the right but less clear):

![photopea-current](https://user-images.githubusercontent.com/8590311/90134326-e82fb780-dd68-11ea-8ed8-613065dad7e8.jpg)

I see two main reasons why Photoshop's is clearer:

- There is a more obvious separation of colour between the canvas and the tabs (as you have already mentioned)
- The inactive font colour is slightly darker

I have gone ahead and mocked up a version with slightly modified tab styles which I'm hoping improves the UX:

![mockup](https://user-images.githubusercontent.com/8590311/90142180-fb945000-dd73-11ea-82c5-35fbb59b0d4d.jpg)

The following styles were changed for the INACTIVE tab:

- `background-color: #3e3e3e;` (made slightly lighter so there is better contrast between the inactive tab and the canvas)
- `color: #999999;` (made font-color darker so the active tab stands out more)
- `border-top: 1px solid #484848;` (gave the inactive taps a slightly darker border-top, again so the active tab stands out. Ideally I would change the ACTIVE tab background color to `#555` but this would mean changing the default .app background color to match which I'm guessing you want to avoid. Making the border-top less prominent for the INACTIVE tabs seems to be a good compromise)

Screenshot of updated styles:

![css](https://user-images.githubusercontent.com/8590311/90142211-0222c780-dd74-11ea-9ec2-a2637c800f9b.jpg)

I've gone ahead and applied these updated styles through the app (extra image tabs, plus History and Info panels) to see how it looks in more complex scenarios:

![whole-app](https://user-images.githubusercontent.com/8590311/90142226-064ee500-dd74-11ea-8dc7-0e05f6033eef.jpg)

Let me know what you think :)

PS. When hovering an invactive tab, I would probably change the font colour to match the active tab's font color, so it's even clearer they are interactable, but that's slightly outside the scope of this issue so I'll just leave it down here as a note.

PPS. Absolutely LOVE Photopea. I tell so many people about it and it's one of the few websites where I turn off my adblocker. Genuinely love it, so thank you!
