### ISSUE TITLE
UNABLE TO TRANSFORM/RESIZE [PLEASE FIX PHOTOPEA DEVS]

### ISSUE THREAD

**Issue by Incelations** [photopea/photopea#7172]
Your Operating System: Laptop
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Everywhere.

**This must be done to see the problem**
1. Go to www.photopea.com/Photopea application ON laptop/PC/EVERYWHERE
2. When first start up, I can transform! but When I add or edit something to my photopea project, I can't transform the object that I was trying ot transform nor the new objects I add. It just completely bugs out.
3. This happens when I go on the website and Application, none of it works.
4. Please look into further detail in this issue because if resizing actually worked this would be the NUMBER 1 best FREE website/Application in the world.

**Comment by photopea** [comment]
Your link shows nothing to me: [www.photopea.com/Photopea](http://www.photopea.com/Photopea)  are you sure about it?

**Comment by forresto** [comment]
<img width="615" alt="image" src="https://github.com/user-attachments/assets/0f8605be-d59c-49ac-8432-db99a5a7938e">

Same result in Firefox and Safari... I can't resize or rotate with the transform controls.

**Comment by photopea** [comment]
@forresto please fill out the issue template, we can not help you without having more information.
