### ISSUE TITLE
Plain Text PPM File Opens With Bottom Right Pixel As Transparent

### ISSUE THREAD

**Issue by behreajj** [photopea/photopea#7173]
Your Operating System: Windows 10 Home 22H2 19045.4894
Your Web Browser: Microsoft Edge 129.0.2792.52

**This must be done to see the problem**
1. Go to www.photopea.com
2. Click "Start using Photopea"
3. Click "Open From Computer"
4. Browse to a plain text ppm file.
5. Observe bottom right most pixel.
6. Compare image in Photopea to another image viewing program.

In Photopea:
![ppmScreencap](https://github.com/user-attachments/assets/7d6c3bbe-ad38-49da-b5bf-deaf60dc0f47)

In GIMP:

![ppmScreencap3](https://github.com/user-attachments/assets/81103d5a-3ebf-4763-b3e9-9b48cfb5c34b)

The plain text file contents:

```
P3
4 2
31
30 15 05 21 26 05 00 15 19 19 03 11
27 07 07 29 27 03 00 18 17 12 06 15
```

This does not occur in Photopea with a binary ppm:

![ppmScreencap2](https://github.com/user-attachments/assets/d7387077-3251-4b09-83bb-3bdda4807101)

A hex dump of the binary ppm:

Row | 00 | 01 | 02 | 03 | 04 | 05 | 06 | 07 | 08 | 09 | 0A | 0B | 0C | 0D | 0E | 0F
---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---:
00000000|50|36|0A|34|20|32|0A|33|31|0A|1E|0F|05|15|1A|05
00000010|00|0F|13|13|03|0B|1B|07|07|1D|1B|03|00|12|11|0C
00000020|06|0F|  |  |  |  |  |  |  |  |  |  |  |  |  |  

The same issue occurs with plain text and binary versions of pgm and pbm files.

**Comment by behreajj** [comment]
Looks like the ppm file was missing a white space or new line after the last row. Adding white space fixed the issue.

**Comment by photopea** [comment]
okay, I am glad that you have managed to fix it.

It is always questionable how damaged files should be displayed.
