### ISSUE TITLE
Upload unavailable 

### ISSUE THREAD

**Issue by BARIGA57** [photopea/photopea#7174]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by BARIGA57** [comment]
I cant download the images from photopea on the macbook
, it says "Safari can´t open the side" what could be the problem

**Comment by photopea** [comment]
What versoin of Safari do you use? What exactly do you do in Photopea to "download the images"? Where do you click?

**Comment by BARIGA57** [comment]
It is Safari Version 17.5
 I want to download it as an JPG Image. 

 But also the other posibilitys don't work. 

 With greetings

 Dominik 
Am 22.09.24, 02:07 schrieb Photopea ***@***.***>:

  
  What versoin of Safari do you use? What exactly do you do in Photopea to "download the images"? Where do you click?

**Comment by photopea** [comment]
Did it start to happen after updating to macOS 15 Sequoia, which has been released this week?

**Comment by BARIGA57** [comment]
No the Problem was also before that Am 23.09.24, 01:06 schrieb Photopea ***@***.***>:

  
  Did it start to happen after updating to macOS 15 Sequoia, which has been released this week?

**Comment by photopea** [comment]
I just updated my MacOS to 15 Sequoia, and it has Safari 18, and I can save files without any problems, both PSD and PNG.

Why did you name this post "Upload unavailable", but later, you say "I cant download the images". Do you know the difference between upload and download?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
