### ISSUE TITLE
Fourier Transform numerical instability?

### ISSUE THREAD

**Issue by voidastro4** [photopea/photopea#7175]
Browser: Google Chrome Linux x86-64

When applying the FFT followed by the iFFT the result is a slightly corrupted image (with banding artifacts).

I think that when the FFT filter is used the image should be converted to something with higher bitrate.

When I tried to change the Mode to 32 bits per channel it didn't solve the problem however. That should have been sufficient.

**Comment by photopea** [comment]
Our Fourier transform has no loss only when applied to square images. I dont know how to "arrange" coefficients into pixel color values when the aspect ratio is not square :(

**Comment by voidastro4** [comment]
I see, the Fourier transform did look to be an unusual variant.

Here is how it usually appears and also helps the intuition along: https://www.youtube.com/watch?v=0mHRJ_42800
This also happens to be how MRI machines used to work, now it's compressed sensing 'magic'.

I looked around for a javascript 2d image Fourier transform and wasn't able to find much.
But maybe this can help:
https://github.com/monman53/2dfft
from:
https://monman53.github.io/2dfft/

**Comment by photopea** [comment]
Could you describe, what should I do to see the "numerical instability" in Fourier Transform in Photopea?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
