### ISSUE TITLE
Text tool leads to soft freeze

### ISSUE THREAD

**Issue by Tegurd** [photopea/photopea#7176]
Your Operating System: Windows 11 23H2
Your Web Browser: Edge Version 129.0.2792.52
The problem happens in the Incognito Mode, too: No

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open a project
3. Add a new text with text tool
4. The white "loading" (or "läser in" in my language) shows up at the top but never goes away. Everything else seems to work but I can't write any text.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
