### ISSUE TITLE
Wrong results reading actionSet

### ISSUE THREAD

**Issue by mszuchman** [photopea/photopea#7177]
Your Operating System: OS X
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Run a script

```
var r = new ActionReference()
r.putIndex(stringIDToTypeID('actionSet'), 1)
try { 
        d = executeActionGet(r)
} catch (e) { 
    alert(a)

} 

var numberOfChildren = 0

if (d.hasKey(stringIDToTypeID('numberOfChildren'))) {
    numberOfChildren = d.getInteger(stringIDToTypeID('numberOfChildren'))
} 

alert(numberOfChildren)

```

I have one action set and one action created in Photopea, the expected result should be 1 instead of 0. The same script works well in Photoshop

**Comment by mszuchman** [comment]
Just found another issue with actions.  The action "play" was not implemented.

Steps to reproduce it:
1/ Record actions in Photopea
2/Name the actionSet as "Default Actions"
3/Name the action as "Test"
4/Run the script below:

```
var r = new ActionReference ();

r.putName(stringIDToTypeID('action'), 'Test');
r.putName(stringIDToTypeID('actionSet'), 'Default Actions');

var d = new ActionDescriptor()

d.putReference(stringIDToTypeID('target'), r);


try { executeAction(stringIDToTypeID('play'), d) } catch (e) { alert(e)}


```


Expected result: The script should run

Tried it in Photoshop and it works

**Comment by photopea** [comment]
thanks for reporting it. Both scripts should run well now! :)
