### ISSUE TITLE
Bug issues

### ISSUE THREAD

**Issue by rengokuz** [photopea/photopea#7178]
Your Operating System: Laptop
Your Web Browser: Chrome & Firefox
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. So first issue I have had for months on Chrome, I wasn't able to change any of my image tabs, I could have 8 images and if I stay on one image too long it is stuck on there until I reset the page but then it continues that issue.
2. Firefox and Chrome have been having an issue with pngs, I can see the first image but if I put another png over it I can't see if even when it isn't invisible. I haven't been able to properly use this site for a few months now and I would appreciate if this could be fixed I have no clue if it's an issue with me but it's very frustrating to deal with.

**Comment by photopea** [comment]
"Laptop" is not an operating system. What operating system do you use?

Could you write the steps, which should be done to see a problem?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
