### ISSUE TITLE
drag'n'drop to another tab doesn't work right now?

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#718]
I open 2 png files in photopea.
Then I try to drag one image to the tab with the second image. (Just trying to combine two separately screenshoted pages of the same document).
I tried to do this by dragging image itself, the layer, and the tab - nothing works.
I remember I did this some few weeks ago or so.

btw, finished my task by using "merge into..." function (thanks for this one!)

**Comment by photopea** [comment]
Do you mean dragging a layer over another tab label? It works for me, we did not change it.

Can you restart your browser or something?

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by ewnjtgouierg** [comment]
sorry for the late reply
I just checked again - still doesn't work for me. Chrome on Ubuntu 16.4
+ checked in Chrome on Windows 10 - doesn't work either

I'm sure it worked before

Steps to reproduce:

1. Open png/jpg with File/Open
2. Open another png/jpg with File/Open
3. Drag the only layer of the current tab and drop it on the label of the other tab

DOESN't WORK

if I try to drag the current tab label, or the image itself - doesn't work either

I remember it worked for me in the past, but may be I'm doing something wrong?

**Comment by MichalSZZ** [comment]
The same happens to me (windows-chrome / mac-ff).
 
Now I resolve that problem with right mouse button on layer and using "duplicate into" (great feature by the way). But dragging layer on tab to copy is more user friendly in my opinion.

**Comment by photopea** [comment]
I tried it in Chrome on Windows 7 and it works.

Step 3: as you drag the layer over the label, you should wait 0.5 seconds, until tabs are switched, and only then release the mouse. Can you try it again this way (waiting 0.5 seconds)?

**Comment by photopea** [comment]
Also, could you tell me, if you see any errors in the console?

**Comment by photopea** [comment]
Ok I made it clearer in the docs.

**Comment by ewnjtgouierg** [comment]
thank you very much

**Comment by MichalSZZ** [comment]
Now I understand how it works in Photopea :)

In Photoshop I grab layer (**from layer panel**) and drop on the another tab. This method is better because you can easy copy (with drag and drop) to another document, not only one layer (selected with move tool) but all layers grouped in folders.

I was thinking (making "my way"), that there is a bug, because tab switched to blue color, after I dragged layer on other document tab.

**Comment by photopea** [comment]
Ok, you can drag-and-drop layers from the Layers panel into another tab now.
