### ISSUE TITLE
APP

### ISSUE THREAD

**Issue by Fantasma41010** [photopea/photopea#7180]
opera gx
photopea why you guys dont have any application pls make it I dont wanna use in browser

**Comment by photopea** [comment]
Did you try to press More - Install Photopea?

**Comment by photopea** [comment]
try this https://www.photopea.com/tuts/install-photopea-to-your-device/

**Comment by Fantasma41010** [comment]
no no no I downloaded it and I mistakenly close iy and I cant find it now

**Comment by photopea** [comment]
what did you download?

**Comment by Fantasma41010** [comment]
photopea  I downloaded

**Comment by photopea** [comment]
how did you download photopea?

**Comment by Fantasma41010** [comment]
press more and download photopea thats all

**Comment by photopea** [comment]
There is no "download photopea", there is only "isntall Photopea".

**Comment by Fantasma41010** [comment]
whats the difference

**Comment by photopea** [comment]
How exactly can I help you?
