### ISSUE TITLE
Nu se salvează transformarea modului de culoare din RGB în CMYK

### ISSUE THREAD

**Issue by Vladimir309** [photopea/photopea#7182]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....Nu se salvează transformarea modului de culoare din RGB în CMYK. Fotografia pe care am presupus că este salvată în Modul CMYK rămâne de fapt tot în modul de culoare CMYK.
3. ....
4. ....

**Comment by photopea** [comment]
I have to close it because of lack of details :(
