### ISSUE TITLE
unable to edit text

### ISSUE THREAD

**Issue by pinkjimrussiagirl** [photopea/photopea#7184]
Your Operating System: windows 11
Your Web Browser: microsoft edge
The problem happens in the Incognito Mode, too: idk

just now when i was making a banner for one of my profiles the ability to edit text stopped working just after i closed out of a very large project

**This must be done to see the problem**
1. Go to www.photopea.com
2. add a text with anything in
3. deselect the text
4. double click the text in the layer menu

**Comment by photopea** [comment]
I tried your four steps, but everything seems to work fine. Did you try to run Photopea without any browser extensions? I think your browser extensions are causing this.

**Comment by photopea** [comment]
I have to close it because nobody is replying :(
