### ISSUE TITLE
Not Able To Transform

### ISSUE THREAD

**Issue by Incelations** [photopea/photopea#7185]
Your Operating System:Windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Probably

**This must be done to see the problem**
1. Go to https://www.photopea.com/ and https://www.photopea.com/
2. Unable to transform at the start or middle of doing something

---
![vegeta 2](https://github.com/user-attachments/assets/116abfa2-4a68-48c0-bc8c-ea67a0998748)
![vegeta](https://github.com/user-attachments/assets/f2da7a19-0457-4777-8ab4-cceb269d429b)
----
4. Sometimes it does work, most of time it doesn't transform and that is getting really annoying.
5. It might be because I'm copying the image from google and not downloading the image from google and putting it down on the project but downloading just takes too long.

**Comment by Incelations** [comment]
And I'm snipping the picture and that doesn't work either. It could be just me but I see other people having the same problem.

**Comment by photopea** [comment]
I can see that the ads are missing on the right side of your screen. Do you use any browser extensions, that have your permission to modify Photopea? Could you disable these extensions? 

Press this button to see which extensions can "change information on this site" = change the way Photopea works: https://i.imgur.com/VDzo5rg.png

**Comment by Incelations** [comment]
I indeed do have an adblocker. If I disable it do you think it will work?

**Comment by photopea** [comment]
You can try it and see. All your browser extensions are running in the installed version, too.

**Comment by photopea** [comment]
I have to close it because nobody is replying :(
