### ISSUE TITLE
[URGENT] Unable to open TIF files

### ISSUE THREAD

**Issue by GOrollout-photopea** [photopea/photopea#7186]
Your Operating System: Windows/IOS
Your Web Browser: Opera
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open the TIF file you want to edit
3. Wait for it to open
4. Error message appears; error. please send your file to support@photopea.com and we will solve it.

**Comment by photopea** [comment]
I just opened 60 different files in Photopea and they all work fine.

Could you do what Photopea tells you to do - send your file to support@photopea.com ?

**Comment by llanes25** [comment]
I have the same problem

**Comment by photopea** [comment]
Could you share your file with us?

**Comment by llanes25** [comment]
________________________________

jesus llanes landeros
Puesto
Compañía

________________________________
De: Photopea ***@***.***>
Enviado: martes, 24 de septiembre de 2024 13:18
Para: photopea/photopea ***@***.***>
Cc: llanes25 ***@***.***>; Comment ***@***.***>
Asunto: Re: [photopea/photopea] [URGENT] Unable to open TIF files (Issue #7186)


Could you share your file with us?

**Comment by photopea** [comment]
Please, send your file to support@photopea.com

**Comment by photopea** [comment]
I have to close it because nobody is replying.
