### ISSUE TITLE
Are you blocking ads

### ISSUE THREAD

**Issue by Harun673** [photopea/photopea#7187]
![Screenshot_2024-09-22-21-28-53-596_com android chrome](https://github.com/user-attachments/assets/016b2302-01b7-4e0b-842a-c195b3502761)
Photopea app blocking ads issue please sir solve this problem

**Comment by photopea** [comment]
How exactly can I help you? You need to turn off your ad blockers in order to see ads in Photopea.

**Comment by photopea** [comment]
It should be fixed now - this window should be fuly visible even on small screens, so that you can close it.
