### ISSUE TITLE
UnitValue in scripts?

### ISSUE THREAD

**Issue by carstenjaksch** [photopea/photopea#7189]
I try to use `UnitValue` as documented [here](https://github.com/Adobe-CEP/CEP-Resources/tree/master/Documentation/Product%20specific%20Documentation/Photoshop%20Scripting) and [here](https://extendscript.docsforadobe.dev/extendscript-tools-features/specifying-measurement-values.html).

Also I found this Reddit thread: https://www.reddit.com/r/photopea/comments/tdjehp/need_help_with_a_simple_script/

Does Photopea support this?

For example:

```
app.activeDocument.resizeImage(new UnitValue(200, 'cm'), new UnitValue(200, 'cm'), 300)
```

Tried `new UnitValue()` / `UnitValue()` and as parameters `(200, 'cm')` / `('200 cm')`.

I need to change the image size in cm values, not pixels.

**Comment by photopea** [comment]
I think I have implemented it, both UnitValue(200,"cm") and UnitValue("200 cm") should work :)

Note, that 200x200cm at 300 pixels per inch leads to 560 million pixels. Photopea might crash if you dont have nough RAM (you need 4 Bytes of RAM per pixel).

I hope you know that what you do will not "improve the quality" in any way. E.g. turning 2x2 pixel image into 200x200 cm at 300 DPI will not "improve the quality" in any way.

**Comment by carstenjaksch** [comment]
@photopea Thank you for your fast response.

Context: We have some online shops with print products and want to use Photopea as a web-to-print solution. The customer can choose a width and height (in cm) on the product page and the final print file should have min. 300 dpi.

I now see that it works indeed but I get a RAM error pretty early (not even reaching 1000 cm width/height with 72 dpi).

We would like to purchase the whitelabel version of Photopea, but we need a performant way to design and export files that have 300+ dpi and 1000+ cm width/height.

Is there any way to get this working?

**Comment by photopea** [comment]
Are you aware of what you are asking for? You want to turn this 2x2 pixel image of a car:
![New Project](https://github.com/user-attachments/assets/9e6a290f-38f5-404c-b5b2-1365ae891496)
into a 20x20 cm, 300 DPI image of a car: 
![New Project (1)](https://github.com/user-attachments/assets/3bce9367-fab9-47a2-9284-514f2c105bd8)

Is this really what you want? Do you think it is useful? Have you ever used Adobe Photoshop?

**Comment by carstenjaksch** [comment]
Have you ever created print-ready files? Do you know that these machines need high-resolution images for crisp print quality?

This is because we need to **create**, not upscale, **create** the design file in the correct dpi-resolution and sometimes a banner can be very large.

Online designers like Zakeke and NBDesigner can do that, but have other flaws. So we looked into Photopea. Every software has it's flaws, I guess.
