### ISSUE TITLE
[CRITICAL] Photopea API broken

### ISSUE THREAD

**Issue by lucadalli** [photopea/photopea#7190]
A Photopea API script which has been working perfectly for over a year has suddenly stopped working and throws the error below.
I have emailed the script to Photopea support as it cannot be shared publicly.
```
pp1727338582.js:11212 Uncaught TypeError: Cannot read properties of null (reading 'at')
    at hs.eval (pp1727338582.js:11212:89)
```

**Comment by miroljub1995** [comment]
We have error with arrays too:
```js
console.log([].length);
```

This prints `undefined`, which is critical.

**Comment by photopea** [comment]
@miroljub1995 I tried to run your script in Adobe Photoshop and it says "console is undefined".

Photopea can not run scripts which Adobe Photoshop can not run. You should not invent your own scripting, you should use what already exists.

**Comment by photopea** [comment]
It should be fixed now.

**Comment by miroljub1995** [comment]
@photopea I just put console for log, [].length was `undefined`, not the console itself. Not it is working. Thanks
