### ISSUE TITLE
Magic Replace - Generated content too small when selection goes beyond image

### ISSUE THREAD

**Issue by getitgud** [photopea/photopea#7191]
Your Operating System: Win-7
Your Web Browser: Mozilla Firefox, Opera
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Upload photo
3. Select Magic Replace
4. Outline portion of photo, BUT extend selection off the LEFT and/or RIGHT of the image
5. Select "replace"

Note: Problem was not seen when entire selection stayed within the image. Problem was not seen if selection was extended below the image.  Issue only seen with the selected area goes beyond the left, or right, side of the image.  Issue occurs on both Free and Subscription generations.
Note: Issue was not seen when testing with fruit or pets, only pets

**Comment by photopea** [comment]
I just tried it, but everything works fine :( Could you share more info, e.g. show us your image and how do you select the area to be replaced?

**Comment by getitgud** [comment]
I went to a search engine and found a random picture, just to ensure it
wasn't the images I was working with.

The content phrase was "girl wearing a red shirt", but I get similar
results with other phrases.  It doesn't matter if I use a simple, or
complex phrase, customize the settings or make simple/complex selections.
The trigger for the issue appears to be when you include space to the Left
or Right of the image.

I've included multiple screenshots to let you see the original image, the
selection, and results, Transform settings and how it's correct when you
select below the image.

I have tried simply resizing the new AI content, but it doesn't align
properly.  It's not simply too small, the overall ratio is incorrect too.

I have tried deselecting the "keep aspect ratio" option and generating
again, but that doesn't help.

**Comment by getitgud** [comment]
Instead of just selecting something random, I actually selected her shirt
so you can better see what the AI content looks like.  Same pic, same
prompts as before, I just did a better selection.

**Comment by photopea** [comment]
Please, go to www.github.com and reply there. Do not send emails to random github addresses. If you can write only emails, write us an email to support@photopea.com

Can you recreate the bug right now? If yes, could you share your image and a screenshot of what you are selecting?

**Comment by getitgud** [comment]
Yes,  I can still re-create the problem.

The screenshots included were taken this morning. 

This shows a random pic from the internet.

![1 Orig](https://github.com/user-attachments/assets/ef8cf581-ea30-489a-b795-a933bdaedc56)
![2 red-shirt-before](https://github.com/user-attachments/assets/97352fbc-9cda-4d16-acaf-2f2e3951ed75)
![3 red-shirt-afer](https://github.com/user-attachments/assets/b8c690e2-8708-465a-912d-6fc72830c6d0)

The generated content does not properly fill the space if the selection extends beyond the LEFT or RIGHT side of the image.  If I only extend below the image, the generated content is correct.

**Comment by ronaldafrica** [comment]
Similar problem

**Comment by photopea** [comment]
There really was a problem. It happened when the selection was wider than the document (your case), or higher than the document. I have fixed it, it should always work correctly now.
