### ISSUE TITLE
changing fonts shortcut

### ISSUE THREAD

**Issue by Eran4383** [photopea/photopea#7192]
Your Operating System:win10
Your Web Browser:chrome
The problem happens in the Incognito Mode, too:
not sure if this is a bug or not but on photoshop there are shortcuts for changing fonts (or even brushes) and in here it doesn't work. not sure if it's not a feature or just not working so thought it worth asking.

Also, is there a place where I could suggest something please?
I would like to be able to see the font on my text live so I wont need to chang, check, then changing again and so on....
Or maybe just an option to be able to change the default Preview text to the word we would like it to be. currently its insane to try and find a specific font (like one which presents numbers the way we like).

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
What shortcut exactly are you talking about? Is it in Adobe Photoshop? What exactly should I do in Photoshop to see what you mean?

**Comment by Eran4383** [comment]
hi, i mean that when you press < or > it changes the type of brush you are using.
![image](https://github.com/user-attachments/assets/e8a71f66-9fe8-420e-85e0-48be63e0fd5a)


also this is what I mean when I say that maybe you can let us chose what the text will be instead of preview - this way it will be easy and dynamic for use to chose fonts easily
![image](https://github.com/user-attachments/assets/6b3aaa3e-773a-4663-9e43-da716d636a72)

**Comment by bluep55** [comment]
> hi, i mean that when you press < or > it changes the type of brush you are using. ![image](https://private-user-images.githubusercontent.com/129061889/373290501-e8a71f66-9fe8-420e-85e0-48be63e0fd5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NzM2NjAsIm5iZiI6MTcyNzk3MzM2MCwicGF0aCI6Ii8xMjkwNjE4ODkvMzczMjkwNTAxLWU4YTcxZjY2LTlmZTgtNDIwZS04NWUwLTQ4YmU2M2UwZmQ1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxNjM2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTQ5NzRjNmU0ZTljNzJiNDI2ZGE3YTIyYTBmZDY5MWIwYmNjZTJmYzJiYzlmNjhmYWJkZmJjNmQ0OGJlNjM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8pfb2O5FPD7yMq0vZxm8_LQA7AutRDrkgOU2Wh2ZrG8)
> 
> also this is what I mean when I say that maybe you can let us chose what the text will be instead of preview - this way it will be easy and dynamic for use to chose fonts easily ![image](https://private-user-images.githubusercontent.com/129061889/373292068-6b3aaa3e-773a-4663-9e43-da716d636a72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NzM2NjAsIm5iZiI6MTcyNzk3MzM2MCwicGF0aCI6Ii8xMjkwNjE4ODkvMzczMjkyMDY4LTZiM2FhYTNlLTc3M2EtNDY2My05ZTQzLWRhNzE2ZDYzNmE3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxNjM2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGQzNGUxOTM2MDVkYzRmZjQ0NjUxYjNhNjkxMTEzMjBiNjY2ZmViNjVkOTFmOTk1MWEzMjFjZDA2ZWIxZmZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1RIC1YjDQdgYKrSoSR68vvzGwOJtG7qq9iX_wpY40lQ)

Something like this? Similar to Affinity Photo.

https://github.com/user-attachments/assets/6a6460ea-90b4-496e-aee8-18dba2b87d35

**Comment by photopea** [comment]
I have implemented it into Photopea. Move over the font with a mouse to see it applied to your text.

**Comment by photopea** [comment]
![image](https://github.com/user-attachments/assets/3db5716e-4e04-4d59-9e22-33a31f834498)

**Comment by Eran4383** [comment]
This is awesome! Thank you.
By the way, why on my try it shows those notifications of loading the fonts, and on yours not?
(And can I be moved to the side or something, since its over the text)
![image](https://github.com/user-attachments/assets/ff901740-3458-4513-a95f-5b1335549c29)
