### ISSUE TITLE
Wand tool don't select after something has been already selected

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#7193]
Your Operating System: Chromeos
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Select Wand tool
3. Select something on your canvas
4. Now select a different element

As you can expect, it should select the second element, but it doesn't. You have to deselect first, in order to select again.

This is a regression of the tool.

**Comment by photopea** [comment]
I can not see any problems with the Magic Wand tool :(

What do you mean by "select a different element"? You shuld click with the magic wand tool, and it selects pixels of a similar color.

Are you talking about the Magic Wand? I am not aware of any other Wand.

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by TheRadicalDreamer** [comment]
It don't happens anymore, so it is fine to close it.
