### ISSUE TITLE
Bug: Not able to hide layer.

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7194]
![ok](https://github.com/user-attachments/assets/29f3e130-bf2a-4d7e-9e16-8440b7f2e9e2)

How to produce:

New Project --> Choose From templates (With Online Images Pixbay.com)..

--> Now wait till project loads completely...

--> Now Focus on Layer Panel in that Background Layer.

--> CLick Eye Icon to hide/unhide, its not working...

Thank You.

**Comment by Mayur-hot** [comment]
[screen-recorder-mon-sep-30-2024-09-58-10.webm](https://github.com/user-attachments/assets/15a98fb0-7e9a-4968-9456-1649135ce22a)

See above video --> unable to hide background layer after choosing templates (with photos)

**Comment by photopea** [comment]
Thanks, it is fixed now! :)
