### ISSUE TITLE
unaqble to export jpg image

### ISSUE THREAD

**Issue by Mike1HB** [photopea/photopea#7195]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com....
1. Windows 10

**Comment by Mike1HB** [comment]
unable to export an image jpg
![Screenshot (29)](https://github.com/user-attachments/assets/8aef9f8e-c6c1-4385-a8b9-baa0a24aa4d7)

**Comment by photopea** [comment]
Did you try to disable all your browser extensions?
