### ISSUE TITLE
Lag everything have a delay when I open Photoshop files or I make many layers

### ISSUE THREAD

**Issue by Zedd418** [photopea/photopea#7196]
Your Operating System: Tablet 
Your Web Browser: 
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Did you try it in the Incognito mode, i.e. without any of your browser extensions running at the same time?

Also, what is your PeaMark? You can see it under More - PeaMark.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
