### ISSUE TITLE
Not loading my image

### ISSUE THREAD

**Issue by NotShloakRBLX** [photopea/photopea#7197]
Your Operating System: Microsoft Windows 11 Home
Your Web Browser: Opera GX
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Try making an image
3. Go to another tab
4. Go back to Photopea

Progress gets restarted (all the contents of the image goes gone and doesn't come back)

Fuck you Photopea :)
![image_2024-09-29_142148239](https://github.com/user-attachments/assets/851b9095-eadf-42d3-b131-720646f90f1d)

**Comment by photopea** [comment]
I just tried your steps in Chrome, but I still can see my original work :( Could you record a short video of you doing these steps, as a proof?

What exactly is Opera GX? Is it like Opera?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
