### ISSUE TITLE
Lost Peasmaker Game Progress 

### ISSUE THREAD

**Issue by Ali-Haider8** [photopea/photopea#7199]
I opend the game and couldn't find my progress, then when I look from my account I found it loged out, I login return to game and still no progress.

**Comment by photopea** [comment]
Sorry to hear that :( The progress is saved in cookies. Did you clear your cookies? Do you use browser extensions which clear cookies / website data?

**Comment by Ali-Haider8** [comment]
Yes, maybe ccleaner delete them,but  It could not happen if you declared that function in game.On 30 Sept 2024 11:18 am, Photopea ***@***.***> wrote:
Sorry to hear that :( The progress is saved in cookies. Did you clear your cookies? Do you use browser extensions which clear cookies / website data?

**Comment by photopea** [comment]
Would you like to save your progress to the cloud, so that you can play on different devices?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
