### ISSUE TITLE
Unexpected end of file

### ISSUE THREAD

**Issue by dunkelcode** [photopea/photopea#72]
I have a PSD created with Photoshop. Editing it with Photopea and re-saving it as PSD gives me an "Unexpected end of file" error when I try to open it again with Photoshop, while opening it with Photopea doesn't even bother giving any error message: it simply doesn't do anything.

The message is like that one:
![photoshop-could-not-load-actions 1](https://cloud.githubusercontent.com/assets/12634286/16836898/50b8f668-49c0-11e6-92b4-9e5fcbbf1ede.jpg)

Thank you for the attention.

**Comment by photopea** [comment]
Hi, there is probably a bug in Photopea. Can you share your original PSD file and describe, what exactly did you do,  to produce the "corrupted" PSD in Photopea?

**Comment by dunkelcode** [comment]
Sure. This is the PSD file I was working on:
https://mega.nz/#!2UpwRZ4Y!Q2_HcSA0-QaIRur1-gNEGfbIY75w9oxWIWy1PGInkN4

It seems that other PSD files work fine, it's just this particular one.  (By the way, I have also discovered that Photopea is able to open again that PSD after refresh)

**Comment by photopea** [comment]
I downloaded your PSD, edited it in PP and saved as a new PSD. The new PSD seems to work fine in Photoshop. I tried editing text layer, smart object etc ... everything went well.

What exactly did you do with your PSD, before it became corrupted?

**Comment by photopea** [comment]
I have to close it for now because of the lack of details.
