### ISSUE TITLE
Downloading and Adding Fonts in Photopea

### ISSUE THREAD

**Issue by sydney225** [photopea/photopea#720]
Hello!

I am working in photopea and I need to use a specific font not included in the available fonts. I can easily download this font myself, I'm just not sure how to go about adding it to the program. I'm not even sure if I have the capability to do that; if not, could we add Futura BQ to the font collection? Thank you

**Comment by photopea** [comment]
Hi Sydney, you can load your fonts into Photopea using File - Open. It is described here: https://www.photopea.com/learn/text-style

I think Futura BQ is not free for commercial purposes, so we can not add it to our list.
