### ISSUE TITLE
issue with exporting as pdf. the amsking clip isn't sticking :(

### ISSUE THREAD

**Issue by emmadoll101** [photopea/photopea#7201]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
You should describe what must be done to see the problem. We can not fix a problem which we cannot see :(

**Comment by photopea** [comment]
I have to close it because of lack of details :(
