### ISSUE TITLE
Can't instal photopea on my computer

### ISSUE THREAD

**Issue by ArtMau97** [photopea/photopea#7203]
Operating System: WIndows 11
Web Browser: Opera GX

I try to instal Photopea on my new pc but when i enter the page the "Instal Photopea" is not working, i presed before and i think the app is instaled but dosn't apear on my pc desktop, also can't instal from google chrome too

![imagen_2024-10-02_104536433](https://github.com/user-attachments/assets/f75d0a5f-fd57-4a62-8a2e-208e8aef96e6)

**Comment by photopea** [comment]
Try these steps: https://www.photopea.com/tuts/install-photopea-to-your-device/#:~:text=The%20Install%20option%20is%20not%20available

**Comment by ArtMau97** [comment]
Now it worked, i isntaled from edge and all ok, many thx

**Comment by photopea** [comment]
It should work in these browsers: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeinstallprompt_event#browser_compatibility
