### ISSUE TITLE
Suggestion: blank or empty templates

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7206]
https://www.photopea.com/templates/t-zDsztd7e

need to remove blank or empty or dummy templates that are may be useless or not contain any valid resources.

Just Goto Templates --> Click New

Thank You.

**Comment by photopea** [comment]
But this texture has been used (opened and exported as a JPG / PNG) 127 times! What if somebody needs it?

**Comment by Mayur-hot** [comment]
may be add daily usages trackers for templates....
and try to get average usages of templates per month...
if average of  blank templates usages became 0 for two or six months, then need to remove..

This is what I think, average is better than counter...
You can close this issue.

Thank You.

**Comment by photopea** [comment]
That template was added 1.5 months ago and got 127 uses since then.
