### ISSUE TITLE
[CRITICAL] `layer.resize` with `AnchorPosition.TOPLEFT` is broken

### ISSUE THREAD

**Issue by lucadalli** [photopea/photopea#7207]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Run script `activeDocument.activeLayer.resize(200, 200, AnchorPosition.TOPLEFT);`
3. Notice that layer is resized from center, not top-left

**Comment by photopea** [comment]
Sorry, it should be fixed now.
