### ISSUE TITLE
Main Screen Inner Logo for photopea

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7208]
![photopea_logo](https://github.com/user-attachments/assets/3b381576-4894-4e72-b05f-c52836dd94dc)

I tried to build new inner Logo for photopea screen..

Inner logo above New Project...

Thanks

**Comment by Mayur-hot** [comment]
![image-svg-svg](https://github.com/user-attachments/assets/b879054f-65b9-42c0-895a-cc8131b73ac0)

**Comment by photopea** [comment]
That is nice! I think you can show it on Reddit :) https://www.reddit.com/r/photopea/
