### ISSUE TITLE
Image Gallery is not loading + pixbay templates also...

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7209]
Image Gallery is not loading...
Templates (pixbay...) also not loading....
![Opera Snapshot_2024-10-05_143353_www photopea com](https://github.com/user-attachments/assets/e954352f-bde5-4d67-a5f9-8214140e924c)

Thank You.

**Comment by bluep55** [comment]
Same here. Chrome and Firefox.

**Comment by Mayur-hot** [comment]
Now its working....
