### ISSUE TITLE
Strange line-height in last line of paragraph after font decrease

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#721]
1. Use type tool to create paragraph text box.
2. Paste some long text.
3. Select all and change font size to smaller.
4. After that in the last line, there is a bigger line-height then in other lines above.

**Comment by photopea** [comment]
Hi, I fixed it, thanks! I saw this bug many times before, but I was too lazy to investigate it, sorry :(

**Comment by MichalSZZ** [comment]
Haha. You? Too lazy? Good joke :)
Thanks for that fix!
