### ISSUE TITLE
Is a color preview for certain objects like shapes possible?

### ISSUE THREAD

**Issue by MesaBlack** [photopea/photopea#7212]
Here's a mock-up:

![image](https://github.com/user-attachments/assets/40b825b4-2a00-494e-a563-e25210b3bb4e)

**Comment by bluep55** [comment]
Click the Fill or Stroke colour box first, then click on the box circled red to bring up the colour picker window.

![Preview](https://github.com/user-attachments/assets/dc5ac4e5-6d7b-4c3c-a788-27b650768c47)

**Comment by MesaBlack** [comment]
no as it displays on the shape itself. if color = red, shape shown as red.

**Comment by bluep55** [comment]
Right, I see what you mean. As you change the colour on the colour picker, you get a live view of the colours changing on the shape.

**Comment by photopea** [comment]
I am confused. What feature exactly are you suggesting? What is a mockup? Is it a PNG image?

**Comment by MesaBlack** [comment]
what @bluep55 said. And I sent you the definition of a mock-up.

**Comment by Mayur-hot** [comment]
> I am confused. What feature exactly are you suggesting? What is a mockup? Is it a PNG image?

Do you see Preview CheckBox in his mockup image? he wants Live Preview of shape color...

**Comment by bluep55** [comment]
I think he means something like this:


https://github.com/user-attachments/assets/929dc613-b48b-46a3-817c-2f0e7ecfff90

**Comment by MesaBlack** [comment]
I don't think the preview means adding a buncha unneeded colors.

[Screen recording 2024-10-09 8.04.49 PM.webm](https://github.com/user-attachments/assets/eb4eaadf-ec57-4fc0-acf7-79435792b6e4)

**Comment by photopea** [comment]
Should I remove these colors at the bottom?

**Comment by bluep55** [comment]
You could remove them, but the colours in the Shape swatches panel behave in just the same way. Could you have a "Add to Swatches" button which gives the option of adding recently used colours to a "Recently Used" swatch panel which isn't affected in this way. Just a thought 🤔

![Add to swatches](https://github.com/user-attachments/assets/2b4eb323-d2ea-42fa-8c91-4175da3cbd76)

**Comment by bluep55** [comment]
Or something similar this.


https://github.com/user-attachments/assets/bc3a0190-25e3-4c94-a4dc-7c2b835f1373

**Comment by photopea** [comment]
I have added a button "To Swatch", which will add your color to the Swatches.

**Comment by MesaBlack** [comment]
we also have to put the checkbox thing in mind

**Comment by kuckir** [comment]
What is a checkbox thing?

**Comment by MesaBlack** [comment]
![image](https://github.com/user-attachments/assets/d8bf7c8c-5d91-4ad9-a4db-556ed4849fa1)

**Comment by kuckir** [comment]
I think the live preview is always useful, so it should be enabled whenever possible. why would anyone want to turn it off?
