### ISSUE TITLE
Too many random and hidden bugs...

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7213]
For e.g. open image, edit it, remove white background by selecting blue/red Channel, then adjust Levels... and then selection by ctrl+click, then select RGB channel and then invert selection and then mask...

close image, open image again do same, some time delete not working.. some time blur fails...
some time erase not working....

some time toolbar failed..., some time delete keyboard key is not working when trying to delete layer.
Please check sequences or code again..

Thank you.

**Comment by photopea** [comment]
Did you try it without any browser extensions?

**Comment by Mayur-hot** [comment]
not tried any extension...
But some bugs are like not detected first time... (means its working as like normal)
after closing document, opening other document, and then doing same.. it creates problem...
open third document... and modify, change background....

So, First Time we don't get any error, but 2nd, 3rd time... its not working as expected....
So, its very difficult to generate steps for bugs like Blur not working with normal layer, normal style, normal opacity.. sometime adding mask created BLACK layers.. + Undo/history also not working....

Note: Its like photopea is not stable for editing/testing more than 2 or 3 documents one by one..

So, what I do is just refresh website after closing one document right now.

And its also difficult for you to detect such kind of bugs...

Thank You Evan

**Comment by photopea** [comment]
Should I try to do it on Mac or on Windows? Or on a phone? Please, make a proper report and fill out the issue template?
