### ISSUE TITLE
Flexible square curving.

### ISSUE THREAD

**Issue by MesaBlack** [photopea/photopea#7214]
Here's the mock-up.

![image](https://github.com/user-attachments/assets/78f339f1-7492-4ce0-968a-0d298ae72d48)

You could double click any of the curving dots to achieve that which is seen in the mock-up.

**Comment by bluep55** [comment]
Just hold 'ALT' while you drag a dot.

![Curve](https://github.com/user-attachments/assets/172c4c68-3310-45c1-92a8-65af7bb0178c)

**Comment by photopea** [comment]
It is not clear to me what you want to achieve :( What is a mock up?

**Comment by MesaBlack** [comment]
1. selecting more than one point by double clicking it.

2. In manufacturing and design, a* mockup*, or mock-up, is a scale or
full-size model of a design or device, used for teaching, demonstration,
design evaluation, promotion, and other purposes.

**Comment by photopea** [comment]
People usually want all corners to have the same radius. If you want to change just one corner, hold Alt.

You never even mentioned the Rectangle tool, or even the word "rectangle" or the word "corner", or the word "radius" or "round".

**Comment by MesaBlack** [comment]
hm
