### ISSUE TITLE
i literally cant resize, move anything, or use rectangle select when i use rectangle select it js says deselect

### ISSUE THREAD

**Issue by ohxndsome** [photopea/photopea#7215]
Your Operating System: Windows
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too: Tested

**Comment by photopea** [comment]
I just tried Photopea in Firefox 131.0 on Windows 10 and everything works fine.

What version of Windows and Firefox do you use? 

Do you see ads on the right side? Some browser extensions, which try to remove ads from Photopea, also break the resizing feature.

**Comment by ohxndsome** [comment]
it works now dw

**Comment by photopea** [comment]
ok.
