### ISSUE TITLE
Impossible to choose a recent font from the 'Recent' window. Also, recent fonts being replaced by fonts that have just been hovered over.

### ISSUE THREAD

**Issue by bluep55** [photopea/photopea#7217]
As you can see in the video, when you try to choose a font in the 'Recent' window, the fonts go crazy 😵🙃.
Also, fonts seem to be saved in the 'Recent' window when they have just been hovered over rather when they have actually been used. Consequently, any font recently used is replaced by those that have just been hovered over.
Windows 10. Firefox and Chrome.

https://github.com/user-attachments/assets/b7b6a826-38b4-4bee-b23c-e102977312ef

**Comment by photopea** [comment]
it should be fixed now.

**Comment by bluep55** [comment]
👍
