### ISSUE TITLE
Feature Request: Let user configure grid width and grid height seperately

### ISSUE THREAD

**Issue by RednibCoding** [photopea/photopea#7218]
Currently the user can only define a square grid (128px is applied to width and height in this case):
![image](https://github.com/user-attachments/assets/247ad3ec-fc31-4281-a9a5-2ea40c547787)

It would be nice if one could define the width and the height seperately.
Similar to this:
![image](https://github.com/user-attachments/assets/cdbfce32-8400-4386-9a98-a876a57e863b)

This would make it possible to define grids like this:

![image](https://github.com/user-attachments/assets/d47f01bc-8a27-476d-91f0-e26c7d9fa53c)

**Comment by bluep55** [comment]
You could try this:
https://www.facebook.com/photopea/videos/846874283629621

**Comment by RednibCoding** [comment]
Unfortunately this does not quite work since i want to edit tilemaps and there it is essential that the grid is not part of the image. This means the thickness of the lines of the grid must technically be 0px.

**Comment by bluep55** [comment]
> Unfortunately this does not quite work since i want to edit tilemaps and there it is essential that the grid is not part of the image. This means the thickness of the lines of the grid must technically be 0px to be pixel perfect.

The grid will be on it's own layer and can be hidden when not needed:


https://github.com/user-attachments/assets/dbb1be92-23e6-49e9-a13a-683ad7f2a249

**Comment by MichalSZZ** [comment]
Maybe try to use a grid made from the guides? You can use the "Guide Gay" from menu Window -> More. 
![Screenshot_20241008_123026_Chrome](https://github.com/user-attachments/assets/16094b4c-615f-4d64-b568-ddbc00cac7db)

**Comment by RednibCoding** [comment]
I just do it like this for now. Hope this will be added soon :)

![image](https://github.com/user-attachments/assets/72d483be-6ba8-4a0b-9cbc-58e45255157b)

**Comment by photopea** [comment]
You can add any kind of grid with the Guide Guy! Press Window - More - Guide Guy, and add guides with a single click.

Also, did you try the "Grid Type" - "Isometric"?

**Comment by photopea** [comment]
I am closing it, as I think it should be done with Guides. Guides can ble placed as a "grid" using the Guide Guy tool.

**Comment by RednibCoding** [comment]
Guide Guy is something different. Most photo/image editors have both: customizable grids and guide lines. Imagine having to define guide lines for this – it's ridiculous!
Guides Lines and grids serve two different purposes:

Grids are used for aligning elements in a structured, consistent manner. They create a uniform layout with fixed spacing and proportions, making it easier to place objects or design elements symmetrically or proportionally across a canvas.

Guidelines are flexible reference lines that can be placed manually to aid with the alignment of individual elements. Unlike grids, which are a pattern of lines covering the entire workspace, guidelines are typically added one by one.

![image](https://github.com/user-attachments/assets/564041a5-43ce-4eda-841e-10d63706b2a2)

**Comment by RednibCoding** [comment]
I apologize if I came across the wrong way.
By "most editors," I’m referring to software like Photoshop, Krita, and PhotoImpact, to name a few. All of these have both guides and grids, as they serve different purposes, as mentioned earlier. I feel this distinction isn't very clear here.

The point I’m trying to make is that this isn’t some obscure or random feature that I personally want. It’s something you’d expect from a somewhat complete photo/image editor. PhotoPea has a lot of unique features that I haven’t seen in other editors, which is really impressive. However, having a grid where users can independently define the x and y gaps is neither uncommon nor particularly special, in my opinion.

But that's totally fine. I’ll just stick with one of the other editors I mentioned. PhotoPea is actually quite good and probably sufficient for most use cases. I would have loved to make the switch, but I need a fast and easy way to define grids with different x and y gaps.

**Comment by photopea** [comment]
But does any existing editor have an option to set the different width and the height of the grid?
