### ISSUE TITLE
Resize image problem

### ISSUE THREAD

**Issue by Pantyusha2002** [photopea/photopea#7219]

**Comment by Pantyusha2002** [comment]
There is a typo in the letter. the problem is also present in the Incognito Mode

**Comment by photopea** [comment]
What the problem is? You have deleted your description.

**Comment by Pantyusha2002** [comment]
I found a solution to the problem.It turns out that I accidentally disabled the number keypad on the right side of the keyboard and the numbers were not being entered. I noticed it by accident. I'm sorry

**Comment by photopea** [comment]
ok
