### ISSUE TITLE
Feature Request : Autosave

### ISSUE THREAD

**Issue by lucastucious** [photopea/photopea#7220]
Can we have an auto-save like every 5,10 or 15 min ?

**Comment by photopea** [comment]
We have this backup mechanism: when Photopea crashes, you should see your work after reopening Photopea: https://www.photopea.com/tuts/photopea-opens-up-old-files/

What "auto-save" do you have in mind?

**Comment by lucastucious** [comment]
Yes and it's super cool. But sometimes, I wanted to have an incremental save history as an option.

Maybe every 15min, a file is created like <filename>_<datetime>.psd. maybe just keeping 3 of theses files so I can go back in previous 15, 30 or 45 min. 

It's just I'm paranoid about losing some work and sometimes I forgot to Ctrl+S

**Comment by photopea** [comment]
You should not lose your work, why would you? There is the backup mechanism, which opens your old file if Photopea crashes.

Sadly, websites can not simply create new files in your computer. We would need your explicit permission each time (the "Save as" dialog).
