### ISSUE TITLE
Photopea thinks im using an Adblocker

### ISSUE THREAD

**Issue by Dpog-cmd** [photopea/photopea#7221]
I am experiencing an issue where Photopea detects an Adblocker, even though I do not have any browser extensions installed. When the Adblocker pop-up appears, the website begins to glitch, affecting my ability to scale text and switch between projects and more, this is getting annoying

**Comment by camoody1** [comment]
@Dpog-cmd You should fill out the proper issue submission form so the developer knows more about your installation environment.

Also, you should change your GitHub name so it isn't so damn rude. Do your parents know how rude you are?

**Comment by photopea** [comment]
What web browser and what operating system do you use? Could you share a screenshot of what you see after opening www.photopea.com ?

**Comment by photopea** [comment]
I have to close it because nobody is responding :(
