### ISSUE TITLE
Erro ao mudar fonte

### ISSUE THREAD

**Issue by guilhermetso** [photopea/photopea#7222]
A fonte não muda em meus projetos

**Comment by photopea** [comment]
Sorry, I speak only English :( Could you describe your problem properly in English?

**Comment by Mayur-hot** [comment]
> Sorry, I speak only English :( Could you describe your problem properly in English?

I translated using google...

He wants to say "The font doesn't change in my projects"

![Opera Snapshot_2024-10-10_111009_www google com](https://github.com/user-attachments/assets/2d561370-599e-4880-932f-160fc344d934)

**Comment by photopea** [comment]
Ok, but we need the original author to communciate with us. Since nobody is communicating, I have to close the issue :(
