### ISSUE TITLE
Nothing is working, doesn't show mask channel, and very delayed

### ISSUE THREAD

**Issue by TheBigJack168** [photopea/photopea#7223]
Your Operating System:Windows 10
Your Web Browser:google chrome
The problem happens in the Incognito Mode, too:yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Submit any textures, and the website stops working
3. ....
4. ....

**Comment by photopea** [comment]
What is "submit any texture"? Do you mean opening a file in Photopea using File - Open?

**Comment by photopea** [comment]
I think I have fixed it.
