### ISSUE TITLE
Nothing gets selected when select pixels is done from channel

### ISSUE THREAD

**Issue by sunilcreativesighter** [photopea/photopea#7224]
Windows 11:
Your Web Browser: Google Chrome/ Microsoft edge both
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Load an image
3. Goto Channel and select the pixels (Ctrl click on the thumbnail to select pixels)
4. No selection will happen., when the layers tab is selected, then the selection shows
5. After this, navigation in the viewport/canvas is completely freezed. 
6. Even upon Ctrl+J, new layer wont be created

**Comment by photopea** [comment]
I think I have fixed it.
