### ISSUE TITLE
Photopea rendered size is larger than my browser size when I log in

### ISSUE THREAD

**Issue by stoarca** [photopea/photopea#7226]
Your Operating System: Ubuntu 22
Your Web Browser: Brave
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. If I log in, I cannot see the right side of the photopea screen. I just see the About button, and nothing to the right of that, including any of the panes.
2. If I log out, the screen size resets to normal.

Other info:

I use photopea on multiple devices, including my desktop with a large monitor. This problem happens when I go to my laptop. It seems like somehow the screen size settings are saved on the account and being used regardless of my current device's monitor size. Resizing the window or zooming in/out doesn't solve the problem.

![image](https://github.com/user-attachments/assets/31f586de-8aaa-433d-8542-05096e54d9bf)

**Comment by photopea** [comment]
Do you have any browser extensions, that are allowed to modify Photopea?

I think you have these extensions on your laptop, but not on your desktop. That is why Photopea looks different.

**Comment by photopea** [comment]
Brave stretches Photopea in order to remove ads on the right side. Sadly, Brave is not aware that you have logged in, and does it even if there are no ads. You should ask Brave to fix it.

Do you use Brave on your desktop, too?

**Comment by rupkatAI** [comment]
I have the same problem

**Comment by stoarca** [comment]
Thanks for letting me know. Turning off brave shield solves it. I understand the frustration directed at brave as a developer, but using the broader internet without shields up is torture. Your nag worked by the way.

**Comment by kuckir** [comment]
@rupkatAI some browser extensions might do this too. We can guarantee the correct functionality of Photopea only if it is not being modified by your browser extensions / "shields" (in Brave).

**Comment by rupkatAI** [comment]
> @rupkatAI some browser extensions might do this too. We can guarantee the correct functionality of Photopea only if it is not being modified by your browser extensions / "shields" (in Brave).

cool, but i have this problem on Edge not on Brave. I have only uBlock Origin that is disabled and have premium Photopea.

**Comment by photopea** [comment]
Do you have this problem in Edge if you disable all extensions? If Photopea runs fine with no extensions, it means that your extensions were not disabled, as you are saying.

**Comment by rupkatAI** [comment]
Sometimes it feels like I'm speaking a different language. I use Microsoft Edge, not Brave Browser. I've disabled all extensions, yet the ad-free Premium Photopea still has a size issue. If I launch the Photopea app first, everything works fine. However, if I start with Edge and then open Photopea, the problem continues.

**Comment by photopea** [comment]
I am talking about Edge, I am not talking about Brave! Photopea works perfectly in my Edge.

Could you record a short video, where you show how Photopea looks like in Edge, while also showing that there are no extensions installed?

**Comment by rupkatAI** [comment]
> I am talking about Edge, I am not talking about Brave! Photopea works perfectly fine in my Edge.
> 
> Could you record a short video, where you show how Photopea looks like in Edge, while also showing that there are no extensions installed?

I tested it once more, disabling each extension individually. The issue was due to uBlock Origin. Once it was disabled, Photopea functioned as expected.

**Comment by photopea** [comment]
okay.
