### ISSUE TITLE
Swatches not saving or changing spots

### ISSUE THREAD

**Issue by SilverMetalSparrow** [photopea/photopea#7227]
When I usually go into photopea, it saves my most recent color at the front of the swatches and depending on which one you click on it changes order. But now when I go in it stays stuck like this:

<img width="166" alt="swatchesssss" src="https://github.com/user-attachments/assets/f06647d8-f515-4e74-b893-2370b94e9b2e">

Is there a way you can fix this?

Also, I would like to request adding more available swatch spots for future convenience.

**Comment by kuckir** [comment]
These 10 colors are "fixed" forever.

you can add the current foreground color as a swatch by clicking the tiny arrow and choosing "Define new". Or in the Color Picker window, click "Add Swatch". These swatches stay even after closing Photopea.

**Comment by photopea** [comment]
A user asked us to delete this feature, because the history of colors might become too "messy" sometimes: https://github.com/photopea/photopea/issues/7212#issuecomment-2403695942
