### ISSUE TITLE
Feature Request: "Edit" -> "Paste to new image" or "File" -> "New from clipboard"

### ISSUE THREAD

**Issue by Kukulkano** [photopea/photopea#7228]
It took me and my wife half an hour to find out how to paste a previously marked and copied part of an image into a new image. It was by far not intuitive to use the "File" -> "New..." button, preventing to select any format and clicking the "Create" button, followed by "Paste". 

In other software (like PaintShop Pro etc) there is not only a "Paste" option but also some "Paste to new image" option. I would really love such function. An alternative and intuitive option would be "File" -> "New from clipboard". 

I also can imagine some "Use image from clipboard" button in the "New Project" dialog.

**Comment by photopea** [comment]
Nobody ever asked for this feature, and Photopea exists for 12 years.

If you want a new file with the content of your clipboard, i think it is clear that you need to make a new file and paste the content of your clipboard into it. So I prefer not to add it, as nobody else needs it, and it would only make the user interface more messy.

**Comment by Kukulkano** [comment]
Now I'm disappointed. Do you think that many of the users have a GitHub accounts and post their issues here? I doubt!

It was one of the first things we found after trying Photopea for the first time. And we were close to drop further tests because we were not able to find such function and considered it as not applicable for our needs (we very often cut stuff from bigger document scans and paste it as new images). Maybe you simply do not get such basic functionaliy replies because people simply gave up very early?

And closing the issue just two hours later does not give any other participant in this repository the chance to write his opinion as it normally disappears after closing.

**Comment by photopea** [comment]
But if you have content in your clipboard, and start a new document, the size will be set to the size of your clipboard content. And then, you just paste it. I think four clicks are not that bad. Everything does not have to be just two clicks.

It is natural, that we can not have every feature of every editor.

**Comment by Kukulkano** [comment]
Anyway. I just wanted to point to some functionality that I was missing and almost stopped me from using Photopea until I found the Reddit post linked above that helped me. To be honest, I do not think the current way is intuitive at all. But finally it is your decision.

Apart from that, Photopea is a nice piece of software and especially for me on Linux it is an important alternative. Thank you for that!

**Comment by positron96** [comment]
> Nobody ever asked for this feature, and Photopea exists for 12 years.

Hi, I don't think this is entirely correct. Here is an issue from 2018 that says that it had been requested multiple times by that time already: https://github.com/photopea/photopea/issues/989. The title is about setting size of the new document to clipboard contents (which is implemented by now as I got from the reddit link above), but the discussion goes into exactly this "Create new from clipboard" functionality.

**Comment by photopea** [comment]
What exactly are you asking for? When you press File - New, the Width and the Height of the new document is already set to the size of the content in your clipboard.
