### ISSUE TITLE
Eye dropper tool not working

### ISSUE THREAD

**Issue by arjayethPSU** [photopea/photopea#7229]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
I just tried it and it works fine for me. What should I do to see it not working?

**Comment by Iliya5digital** [comment]
Eye dropper tool works fine and need to close this issue
