### ISSUE TITLE
Color history in the color picker is missing

### ISSUE THREAD

**Issue by TamarWeiss** [photopea/photopea#7230]
I don't know if this simply a change in UI, but as of late I noticed that the color history that was always present in the bottom of the color picker modal is suddenly gone! 

Is there any explanation to this? I relied on it heavily for my colors. and I would like it to come back. It was very useful.

![11-10-2024 13-50-22](https://github.com/user-attachments/assets/35432c4a-0690-4756-8cdf-db1bec9dcc2a)

**Comment by photopea** [comment]
A user asked us to delete them, because they might become too "messy" sometimes: https://github.com/photopea/photopea/issues/7212#issuecomment-2403695942

Why dont you use Window - Swatches, and the "Add Swatch" button?

**Comment by maestro1617** [comment]
I have just spent an hour trying to figure out what is wrong and why I can't see my previous color samples. Can we please have that feature back asap? Or at least give us the option to have the previous colors show or no. Thank you very much.

**Comment by photopea** [comment]
okay, it is back now. I will not listen to my users that much now. But it is hard to decide who should I listen to, when users are saying the oppisite of one another.

**Comment by TamarWeiss** [comment]
oh my god thank you! maybe maximum have the ability to toggle the option if some people have issue with it, rather then outright deleting it. Thanks for listening nontheless :)

**Comment by TamarWeiss** [comment]
or, maybe, have the option to clear the history every now and then, without needing to exit and reenter the app.

**Comment by MichalSZZ** [comment]
I really like the list of the last used colors.
But when it works well, not like in the screen recording from Issue of that user. There should be only colors that was really used by the user, not the live view (changing all the the when a user move his mouse) of colors that was selected on the color picker.

**Comment by bluep55** [comment]
> I really like the list of the last used colors. But when it works well, not like in the screen recording from Issue of that user. There should be only colors that was really used by the user, not the live view (changing all the the when a user move his mouse) of colors that was selected on the color picker.

It doesn't work well at all now with the live Shape color picker. As you say, it should only show colors that are really used. As it is now it's not really any use by just filling all the squares with virtually the same colors. Strangely, the live color picker for the text color doesn't behave like this. This works just how you would expect it to, by only adding  the color that's actually used.

**Comment by photopea** [comment]
You can ignore this "history of colors" then.
