### ISSUE TITLE
NO Paint Bucket

### ISSUE THREAD

**Issue by TheBigJack168** [photopea/photopea#7232]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. No paint Bucket
3. ....
4. ....

**Comment by photopea** [comment]
There are several tools behind each button in a toolbar. Click and hold the tool button to see more tools under that button.

You can also click the "magnifying glass button" at the top and search for the paint bucket tool. It is definitely there.
