### ISSUE TITLE
Lag when ads switch

### ISSUE THREAD

**Issue by TryHardGamerYT** [photopea/photopea#7233]
Your Operating System: Windows 11
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open any project
3. Wait for ads to switch
4. Lag affecting the entire computer

**Comment by photopea** [comment]
Could you record a short video of the lag?

Also, could you press More - Peamark, and tell us what score do you get?

**Comment by TryHardGamerYT** [comment]
Here you go:

https://github.com/user-attachments/assets/b311fa1e-bd18-44c8-b86f-d70deb431806

I get 427, 260, 15.63GB for my score
While trying to find a solution, I found this: [https://www.reddit.com/r/photopea/comments/dve5dz/ads_reloading_causes_lag_is_it_just_my_computer/](url)
Their video shows the same issue, or something similar

**Comment by photopea** [comment]
But the lag happens only for a fraction of a second. I think it is not that bad. I am afraid we can not fix it, because ads require doing some processing while looking for a new ad to be shown :( Have you thought about getting a Premium account?

Your Peamark scores are a bit low, lower than an average smartphone. With a better device, your experience would improve a lot (not just ads, but filters and everything).

**Comment by photopea** [comment]
I dont know how to fix it. If we remove ads, or show less ads, we will lose a large part of our income. How do you suggest we should fix it?

If you can afford to pay for Photoshop, why don't you pay for Photopea Premium? It is much cheaper than Photoshop and you don't have to pay if you dont use it for a few months, as there is no subscription that needs to be cancelled.

**Comment by photopea** [comment]
Do you think we should do what Photoshop does? Never show any ads ever, and provide the product only to those who pay for it?

**Comment by TryHardGamerYT** [comment]
I've already stated what I think should be done.

I cannot afford to pay due to currently lacking a source of income. Until I obtain a _better device_, I will continue using Photopea due to convenience. The issue is caused by ads, and there are many other ways which would allow me to continue using the program, just as there are ways to use Photoshop
