### ISSUE TITLE
Aspect ratio wrong, cant't see right part of the screen and tools

### ISSUE THREAD

**Issue by lzluca99** [photopea/photopea#7234]
Your Operating System: Windows 11
Your Web Browser: Brave Browser
The problem happens in the Incognito Mode, too: No, until i do the access

**This must be done to see the problem**
1. Go to www.photopea.com
2. Access to my account
3. The problem happens only after the login, which i need because of my subscription
![Screenshot 2024-10-12 105545](https://github.com/user-attachments/assets/b21333a6-f825-465b-bdb3-1df29d9f30e0)
![Screenshot 2024-10-12 105559](https://github.com/user-attachments/assets/14b938a4-9687-48dc-9e2b-43c5fa068b11)
![Screenshot 2024-10-12 105633](https://github.com/user-attachments/assets/efd838d6-75ee-4f32-9858-a4ffea2645d0)

**Comment by photopea** [comment]
This is a bug in the Brave browser: https://github.com/brave/brave-browser/issues/41552

You can try to disable shields. Or switch to a different browser. Or ask Brave to fix it (nobody responded to my bug report yet).

**Comment by lzluca99** [comment]
Thanks for now, the problem appeared only yesterday after weeks of normal
use

Il giorno sab 12 ott 2024 alle ore 13:38 Photopea ***@***.***>
ha scritto:

**Comment by photopea** [comment]
You should ask Brave about it :/ You probably updated your Brave browser.
