### ISSUE TITLE
Window distorts on login

### ISSUE THREAD

**Issue by alexkajosz** [photopea/photopea#7235]
Whenever I login, either on the webapp or desktop app, the right side of my screen gets cut off and I cannot view any of my layers or any other tools on the right side. When I log out it all comes back into the window. I canceled my account and purchased premium on a new account thinking maybe it was something to do with my settings, and when I logged in with the new account the problem persisted.

**Comment by alexkajosz** [comment]
Problem was due to downloading the app and accessing the webapp via Brave browser, switched to Chrome and problem resolved.

**Comment by photopea** [comment]
I have reported it to Brave several days ago, but they are ignoring it. Please, if you have time, write some comment there and tell them that it is bothering you too: https://github.com/brave/brave-browser/issues/41552
