### ISSUE TITLE
New Logo Photopea

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7236]
![Gemini_Generated_Image_myhnfsmyhnfsmyhn](https://github.com/user-attachments/assets/5b6f04ad-8ce7-43f1-954d-622e9df43504)

**Comment by Mayur-hot** [comment]
![Gemini_Generated_Image_myhnfsmyhnfsmyhn (1)](https://github.com/user-attachments/assets/ba65850a-3893-4067-8c96-dbd21f069014)

This is color based.

**Comment by Mayur-hot** [comment]
Last one 
![Gemini_Generated_Image_myhnfsmyhnfsmyhn (2)](https://github.com/user-attachments/assets/cad031b6-e816-4537-9314-28fc5e466e90)

**Comment by photopea** [comment]
You can post it on Reddit, where more people can see it.
