### ISSUE TITLE
photopea resizing and rotating problem

### ISSUE THREAD

**Issue by ossu4reeal** [photopea/photopea#7237]
Your Operating System: Windows 10
Your Web Browser: Google
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. .... i try to resize a shape
3. ....it doesn't respond

Uploading 2024-10-13 14-57-02.mp4…

4. ....

**Comment by photopea** [comment]
Are you uploading a video? i can not see any video.

Did you try it in the Incognito mode?

**Comment by ossu4reeal** [comment]
https://github.com/user-attachments/assets/68182b58-642a-45f4-a1b9-4e6fc0dcb226

**Comment by photopea** [comment]
I think you are using browser extensions which break Photopea. Did you try to run Photopea without any browser extensions?

**Comment by ossu4reeal** [comment]
yeah you were right thanks

**Comment by photopea** [comment]
ok.
