### ISSUE TITLE
resize image not working

### ISSUE THREAD

**Issue by BIELKEITHVALMROIA** [photopea/photopea#7238]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
I have heard that it could be caused by uBlock Origin. What browser extensions do you use?

**Comment by BIELKEITHVALMROIA** [comment]
idk im new at photopea

**Comment by photopea** [comment]
do you know what web browser you are using?

**Comment by photopea** [comment]
From our experiecne, uBlock Origin or Brave Browser often cause this problem.
