### ISSUE TITLE
Trying to create automation batch won't proceed

### ISSUE THREAD

**Issue by repo211** [photopea/photopea#7240]
Your Operating System: Mac
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. File
3. Automation 
4. Batch 
5. Source images
6. Set action
7. Set quilty 
8. Process images 

After I pressed process images I kept waiting for the output for a very long time but nothing happened It froze I tried to do it in a bulk image or single image but still had the same issue 

![Screenshot at Oct 15 5-50-31 pm](https://github.com/user-attachments/assets/15693887-2a52-47c1-983a-cc29bb8da363)
![Screenshot at Oct 15 5-43-36 pm](https://github.com/user-attachments/assets/086bf6b7-4ac0-4e62-9ceb-30056c057878)

**Comment by Mayur-hot** [comment]
You are **RIGHT**, I also checked in linux Browser, Opera Browser, No plugins,

I added 2 images to process, but Not Downloading any Zip File, this was working fine, but right now not working..

![2](https://github.com/user-attachments/assets/839a9ae8-a645-4e63-91f6-35cc17e09533)

No download after waiting 10 min..

**Comment by Mayur-hot** [comment]
**File->Automate->Batch (Not working, No output) its a BUG**

**File->Automate-> Convert Format (Chhose AVIF) gives zip but file inside zip is 0 bytes (empty)**

File->Automate-> Resize images works.. (output images.zip as download)
File->Automate-> PDF works fine.

:)

**Comment by Mayur-hot** [comment]
File->Automate-> Convert Format (_Choose MP4_) **NOT** working

**Comment by photopea** [comment]
@repo211 I can not do your steps because you did not share your actions :( Did you try to run your actions in Photopea, without Batch?

**Comment by Mayur-hot** [comment]
> @repo211 I can not do your steps because you did not share your actions :( Did you try to run your actions in Photopea, without Batch?

I tried without any action script, and still its **NOT** working..
File->Automate-> Convert Format (Choose MP4) **NOT** working
File->Automate-> Convert Format (Chhose AVIF) Gives 0 bytes files inside ZIP
File->Automate->Batch Without any script, just set image quality, and its not generate any output. (See console log for errors..)

**Comment by Mayur-hot** [comment]
![Screenshot_2024-10-16_11-43-31](https://github.com/user-attachments/assets/b3044ea5-7e5d-412e-a102-ba501edae87a)

For a single image tiny images, without any script.. 
Batch is not working

**Comment by photopea** [comment]
@Mayur-hot Are you trying to use Automate - Batch? You do not have any actions, and it will not work without actions. Please search the internet to learn how to use Automate - Batch.

@Mayur-hot Please, delete all your comments from this issue, as they are not related to the initial issue. If you have problems with Photopea, please, make a separate issue. But first, make sure you understand how the tools should be used.

**Comment by Mayur-hot** [comment]
File -> Automate->Batch...
Processing is working fine if have working Action Script..

Just test your action script in File->Script.. dialog box (Remove default alert test code and place your action script and run it.)

(HERE I TRIED TO OPEN RECORDED ACTION SCRIPT After Downloading to disk, and its in BINARY FORMAT).

So, user's AS is buggy.

Thanks You.

**Comment by repo211** [comment]
> @repo211 I can not do your steps because you did not share your actions :( Did you try to run your actions in Photopea, without Batch?

I guess I figured out that the issue was with the image extension. the feature glitches while I'm trying to work on the HEIC extension once I converted the HEIC to JPG it works fine, please recheck from your side the issue with the HEIC extension :(

**Comment by photopea** [comment]
I can run File - Automate - Batch on HEIC images :(

can you simply open your HEIC images in Photopea? If not, could you share one of your HEIC images here with us?

**Comment by repo211** [comment]
> I can run File - Automate - Batch on HEIC images :(
> 
> can you simply open your HEIC images in Photopea? If not, could you share one of your HEIC images here with us?

kindly check the google drive  contain a simple of the images we use https://drive.google.com/drive/folders/1ErOPmdjRJNx-1Pc3BCq8VHuNT7Dd4ND8
