### ISSUE TITLE
Exporting edited PDF causing all pages to merge into giant canvas

### ISSUE THREAD

**Issue by Jmatt06** [photopea/photopea#7241]
Your Operating System: 
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Import PDF into photopea
3. Add any form of text onto any page, not in a pre-made folder
4. Attempt to export PDF

I used to use photopea all the time to import and edit PDFS and export. Typically adding little markups on each page or additional text.
Now if I so much as add one line of text and export it, it combines all my pages into one long canvas page. I've tried adjusted settings everywhere but it seems to lose the page functionality. The only workaround seems to be to make sure the text you add is in the same folder as the page you are putting it on, and it can't be floating in the document outside of a folder

**Comment by photopea** [comment]
The "folders" are actually Artboards. Please read how our artboards work: https://www.photopea.com/learn/artboards

The Artboard - to - page mapping happens only if **all layers are inside artboards**. You can create a PDF document with pages from scratch by creating artboards, without opening a PDF first. It has always worked like this.

**Comment by Jmatt06** [comment]
Thank you,

I wonder if in the past I was always inside one of the artboads and didnt realize it. I was able to get it to work last night fluidly.
