### ISSUE TITLE
undeletable line 

### ISSUE THREAD

**Issue by turtleramirez** [photopea/photopea#7242]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:
![Screenshot 2024-10-15 190317](https://github.com/user-attachments/assets/f1bccd4f-9a5a-493c-ac61-ccda62bd424a)
1. Go to www.photopea.com
2. Add any shape and the weird blue line appears 

Normally I would ignore it but when I try to free-transform literally anything it does it for the blue line and I can't do anything to what I actually want to edit and I've tried deleting it but it nothing works.

**Comment by photopea** [comment]
I think you have created a path. You can delete it in the Paths panel, see https://www.photopea.com/learn/vector-graphics

**Comment by turtleramirez** [comment]
it worked, thank you so much

**Comment by photopea** [comment]
ok :)
