### ISSUE TITLE
File -> Automate -> Convert Formats

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7244]
Your Operating System: Linux
Your Web Browser: Opera
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. File -> Automate -> Convert Formats
3. Choose Source Image
4. Format = Choose AVIF

5. Press Convert Images Button.

Choosing **AVIF**, it produce images.zip Open It, and check file size, its 0 always.

DO same steps, but Change Format to **MP4**, and Press Convert Images Button.. For here its show Page Crashing.. but now same as 0 file size inside zip.

Thanks.

**Comment by photopea** [comment]
It is fixed for AVIF files :) We do not support MP4 files.
