### ISSUE TITLE
Feature Request. Change Blending Mode as mouse passes over the options.

### ISSUE THREAD

**Issue by bluep55** [photopea/photopea#7245]
Could you make viewing the Blending modes the same as how it works with fonts now, by changing the mode as the cursor passes over them?

https://github.com/user-attachments/assets/0fef3fa7-97e9-4de7-9655-e77507cc6103

**Comment by photopea** [comment]
It would be quite hard to make :( but you can click into blending modes and use the Up and the Down key to switch the options.

**Comment by bluep55** [comment]
> It would be quite hard to make :( but you can click into blending modes and use the Up and the Down key to switch the options.

Although you can scroll through them using the up/down keys you don't see a preview of the modes as you do this 😢.

**Comment by photopea** [comment]
I do see a preview of blend modes when I scroll them with arrow keys. What web browser do you use?

**Comment by bluep55** [comment]
> I do see a preview of blend modes when I scroll them with arrow keys. What web browser do you use?

Seems to be ok today, no problem.
