### ISSUE TITLE
Request to navigate layers by chain 

### ISSUE THREAD

**Issue by shababd** [photopea/photopea#7246]
When I want to move the layer and move it, there is a single point to which I must apply. This is tiring and uncomfortable to Why can't just move out of the layers and move the layer down or vice versa? Simply leaving the mouse and the layer moving to the bottom will move smoothly, which will be better and easier 

Uploading Record_2024-10-16-16-12-12.mp4…

**Comment by photopea** [comment]
Are you reporting it for a second time?

**Comment by Mayur-hot** [comment]
> When I want to move the layer and move it, there is a single point to which I must apply. This is tiring and uncomfortable to Why can't just move out of the layers and move the layer down or vice versa? Simply leaving the mouse and the layer moving to the bottom will move smoothly, which will be better and easier
> 
> Uploading Record_2024-10-16-16-12-12.mp4…

You are confusing...., but layer scrolling + making it down/first is possible in two ways.
--> Layer Scrolling is already working vice-versa just got little top/bottom not too much out..
--> Drag Layer + Use Mouse Wheel to Scroll to Down.

Try Above two steps, I hope that will help you to make any layer to first position.

**Comment by Mayur-hot** [comment]
Hello shababd..

Your issue solved? Don't drag layers too much outside.... or try to upload recorded video using Browser extensions.. and wait till video uploaded fully.... and then comment it.

**Comment by photopea** [comment]
I have to close it because nobody is replying :(
