### ISSUE TITLE
Request improved transfer classes 

### ISSUE THREAD

**Issue by shababd** [photopea/photopea#7247]
When I want to move and move the layer, there is one point to which I have to apply. This is cumbersome and inconvenient. Why can't you move out of the layers and move the layer down or vice versa? Simply letting go of the mouse and moving the layer down will move smoothly, which will be better and easier 

Uploading VID-20241016-WA0001.mp4…

![Screenshot_٢٠٢٤-١٠-١٦-١٦-٣١-٤٨-٥٥_754cf9a4094c34a8eeb04648e2e3eb8d](https://github.com/user-attachments/assets/64c7ca09-3b0f-4b92-911b-5b524d77b8ac)

**Comment by photopea** [comment]
I am confused, what are you asking? You uploaded only an image, not a video.

**Comment by Mayur-hot** [comment]
I think he want to say that, He wants a Change in Dragging Layer..

Currently dragging layer is not go beyond Layers Panel:

User wants that Dragging any layer to Bellow but Outside the Layer Panel Window will Put Layer at First Position, That will be convenient to make any Layer First by just dragging it outside of panel window.

**Comment by Mayur-hot** [comment]
e.g. Dragging any layer Outside may start Scrolling layer panel till first layer.. but right now its not scrolling..

**Comment by photopea** [comment]
I have to close it because nobody is replying :(
