### ISSUE TITLE
Issue with layermasks when saving as psd

### ISSUE THREAD

**Issue by LINUS135** [photopea/photopea#7248]
Your Operating System: Windows 11 version 23H2
Your Web Browser: Google Chrome version Version 129.0.6668.90 (Official Build) (64-bit)
The problem happens in the Incognito Mode, too: Not to my knowledge

**This must be done to see the problem**
1. Open the Photopea, app or browser. Occurs with both
2.  Make some changes to a not empty layermask
3. Save the file as psd
4. Open the same file again.

Description:
There might be a new black box added to the layer mask, see images for demonstration. It does not always appear but happened multiple times on different layers. I would estimate it to happen ~1/2. Not always permanent sometimes it disappears after reopening the file. And sometimes it's permanent and it does not matter how many times the file is opened and changes made.

Example of Layermask just before the save
![BeforeSave](https://github.com/user-attachments/assets/1ded5358-1b6a-4a67-8265-1a2b72894745)

Example of the same file as in the image above after re-opening it.
![AfterOpeningSameSave](https://github.com/user-attachments/assets/ad89e394-ae09-4dbf-93fb-9c3ae747d8d8)

**Comment by LINUS135** [comment]
After some additional testing it seems to only be adjustments layers and the problem does not seem to occur when creating from a selection since it doesn't start with an empty layermask then.

**Comment by photopea** [comment]
It happened only for documents in 16-bit mode. It is fixed now :) thank you for reporting it.
