### ISSUE TITLE
Raw (CR2) images not displaying properly- colorless, horizontal lines

### ISSUE THREAD

**Issue by g0nkers** [photopea/photopea#7249]
![Opera Snapshot_2024-10-16_114044_www photopea com](https://github.com/user-attachments/assets/140e0601-2940-4422-b7f3-e8e003f50e3d)
My raw images appear very strangely when I try to edit them. I use a Canon EOS 7D, and I shoot in large format raw with .CR2 as the file type. I use Opera as my browser currently, but the issue persists in Chrome and Edge. I cannot attach the base file, but I can email it as needed. Thanks!

**Comment by photopea** [comment]
Could you share your CR2 file here with us?

**Comment by photopea** [comment]
I have to close it because nobody is replying :(
