### ISSUE TITLE
Error with "Open from URL" option

### ISSUE THREAD

**Issue by Primokorn** [photopea/photopea#725]
Hi,

*Context:*
I usually don't have problems with this option and I didn't use Photopea for a few weeks.

I can't open several pictures ([example](https://image.freepik.com/vecteurs-libre/logo-de-roue-de-moto-vecteur_23-2147491893.jpg)).
I get the following error: **Unknown file format: "Nope"**

Thank you.

**Comment by photopea** [comment]
Hi, it should be fixed now. Thanks for reporting it! :)

**Comment by Primokorn** [comment]
It was worth a shot :smile: 
Thanks for the quick fix!

**Comment by Primokorn** [comment]
@photopea Hi, same error today with [this url](https://lh3.ggpht.com/cUZmmI7V28lrOTrLKK91irtxozjYTbbcARjB_qptpYmfOtcVs9li5GHAYOY_UiOtbbE) - Google Play app icon.
Thanks.

**Comment by photopea** [comment]
Now, Photopea requires the URL to contain the extension ".png", ".jpg" (some other image format). Your URL does not contain such extension :(

**Comment by Primokorn** [comment]
Now, indeed because it works well before.
Thanks anyway.

**Comment by photopea** [comment]
Ok I solved it, all URLs should work now :)

**Comment by Primokorn** [comment]
Indeed, thanks a bunch!
