### ISSUE TITLE
right side tool panel disapears when logged in with paid account and using an add blocker.

### ISSUE THREAD

**Issue by baron-de-ropp** [photopea/photopea#7250]
Your Operating System: Linux Zorin OS ubuntu
Your Web Browser: brave
The problem happens in the Incognito Mode, too: Yes, but only after logging in. It appears to be an issue with turning on ad block while logged in.

**This must be done to see the problem**
1. Go to www.photopea.com
2. log in
3. use the ad block feature in brave
4. there is no tool panel on the right hand side (layers, action history, etc.)

**Comment by DirkBoer** [comment]
Ahh man thanks a lot for figuring out it was the ad blocker. For me it was only happening in "WPA mode". 
Disabling the ad blocker (ublock origin) seems to work for me.

I also have a paid account.

**Comment by photopea** [comment]
It is a bug in Brave, I have reported it here: https://github.com/brave/brave-browser/issues/41552

Anyway, it seems like if you disable "Brave Shields", Brave should display a website the way it was made. So disable the shields or switch to a different browser, which can show websites the way they were made.
