### ISSUE TITLE
Free Transform does NOT rotate

### ISSUE THREAD

**Issue by Oxtie** [photopea/photopea#7251]
Win10 with latest Vivaldi browser (chrome 128 based)

**This must be done to see the problem**
1. Go to www.photopea.com
2. upload an image from computer
3. use rectangle select tool to select specific part of image
4. press alt+ctrl+T or edit menu Free Transform, try rotating selected part (it doesn't)

**Comment by Mayur-hot** [comment]
Plz send a screen recorded video (use browser plugin if you don't have any recording software)

record from start.. _(I am not a developer, only Ivan is main developer)_

Thank You.

**Comment by photopea** [comment]
I just tried it and it works fine in my case.

Our users reported this problem before, and it was always caused by a browser (Brave) or by browser extensions (uBlock origin).

Did you try these steps in other browsers, or without browser extensions?

**Comment by Oxtie** [comment]
Yes,.. after disabling uBlock Origin, it all worked normal.

**Comment by photopea** [comment]
ok, perfect.
