### ISSUE TITLE
Can't close the project window

### ISSUE THREAD

**Issue by marcodiversi** [photopea/photopea#7252]
Your Operating System:  15.0.1  Mac OS
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: yes

Hi, it's impossible to close the project window since today, there must be a bug! Please fix it ! 

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....
![Monosnap Photopea | Online Photo Editor 2024-10-17 09-48-46](https://github.com/user-attachments/assets/69507b8d-204c-4e90-ad6d-4d9809af45c0)

**Comment by Mayur-hot** [comment]
Brave Browser is really Brave, so that browser not allows you to close Window :)

plz try to record a video from starting point... (Use browser extension to record video with full screen)
_(I am not a developer, only Ivan is the Main Developer)_
Thank You.

**Comment by photopea** [comment]
I am glad you have fixed it :) but you should also report it to Brave. Other browsers do not do such crazy things to Photopea as Brave does.

**Comment by photopea** [comment]
Ctrl + H is used by Photopea to show / hide Extras (see View - Extras). https://helpx.adobe.com/photoshop/using/default-keyboard-shortcuts.html#:~:text=selection%20and%20planes-,Control%20%2B%20H,-Command%20%2B%20H

On the other hand, we would like to use Ctrl + T for the Free Transform, but browsers think it should be used for opening a new browser tab, and they don't allow us ot change it :(

**Comment by marcodiversi** [comment]
> Ctrl + H is used by Photopea to show / hide Extras (see View - Extras). https://helpx.adobe.com/photoshop/using/default-keyboard-shortcuts.html#:~:text=selection%20and%20planes-,Control%20%2B%20H,-Command%20%2B%20H
> 
> On the other hand, we would like to use Ctrl + T for the Free Transform, but browsers think it should be used for opening a new browser tab, and they don't allow us ot change it :(

thanks a lot, so there is no way I will be able to use CMD + H on mac to hide the app? (see screenshot) 
![Screenshot 2024-10-17 at 4 49 48 PM](https://github.com/user-attachments/assets/04c2b729-6652-4d17-9b4e-fe9445895c07)

**Comment by photopea** [comment]
I think not, since Photopea is handling the shortcut. Maybe you could override it somehow in the browser, I don't know.
