### ISSUE TITLE
Page not correctly sized

### ISSUE THREAD

**Issue by miateo** [photopea/photopea#7253]
Your Operating System: MacOs
Your Web Browser: Arc
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new project
3. Look on the right side and you can notice that content overflows outside the page, this can't be fixed by zooming out

![Photopea _ Online Photo Editor](https://github.com/user-attachments/assets/cbfa581d-8958-4725-ae3b-97fc949bc846)

4. All the content on the right of the image with the black background isn't visible on the browser

**Comment by photopea** [comment]
I have never heard of the Arc browser :( But since other browsers display Photopea correctly, I think it is a bug in Arc.

Do you use any browser extensions? I think browser extensions could be doing this to Photopea, too.

**Comment by XOCODE-OP** [comment]
Brave here, same problem, paid account
![image](https://github.com/user-attachments/assets/d2fe6526-e2b4-49f3-bbba-f73f76a4df2d)
I cant even see the rest

if I use a different browser it works, If I use incognito it works

but: I tried removing all extensions, still no dice.
tried removing all storage, still no dice.
so I did what I could debugging it I guess

page source when I load it: https://gist.github.com/XOCODE-OP/6de2765afbf31051fe0030e6c38e22c3
network tab doesnt load anything that I can see thats not from either photopea or vecpea

**Comment by photopea** [comment]
You can learn more about this problem here: https://github.com/brave/brave-browser/issues/41552 

Only Brave can fix it. They decide to ignore it. It seems like it works fine if you disable the Brave Shield.

**Comment by XOCODE-OP** [comment]
Goddamn, Im sorry I forgot to try to disable shields. I assumed they were already off since it's so obvious to try for Brave issues.
Thanks !

**Comment by photopea** [comment]
Please, write a comment in this issue: https://github.com/brave/brave-browser/issues/41552 to make Brave aware of it :)
