### ISSUE TITLE
Smart objects appear pixelated when image is added to a smart object document, enlarged using the transform anchors, and the smart object document is saved before "confirming" the transformation adjustments

### ISSUE THREAD

**Issue by briefmockups** [photopea/photopea#7254]
Your Operating System: macOS Sonoma 14.4
Your Web Browser: Chrome 129.0.6668.100
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**

1. Go to www.photopea.com
2. Open a PSD mockup the contains a smart object (reference – https://www.dropbox.com/scl/fi/sw9z2jl8tkrjx4g6vgxzq/Photopea-Mockup-Test.psd?rlkey=qye28wmfgiev4c7edzzvm1cc9&dl=1 )
3. Double-click the "Your image" smart object layer's thumbnail to open up its smart object document
4. Insert an image (reference – https://www.dropbox.com/scl/fi/ve2t03mrfgpxt0kc6tmlg/Photopea-Image-Test.png?rlkey=w9sd2vehd6zh5en42xgzt9lso&dl=1 ) within the document by either dragging from the desktop, or using File > Open & Place. Immediately (without hitting Enter or clicking the "confirm" checkmark on the toolbar) drag the transform anchors at the corner of the image to enlarge it to fill the dimensions of the document – and then immediately (again, without hitting Enter or clicking the "confirm" checkmark on the toolbar) go to File > Save Smart Object. 
5. When returning to the main document, the smart object will appear pixelated.
6. (After re-entering the smart object document and re-saving it, the image will become un-pixelated when returning to the main document). 

Linked below is a video demonstration of the steps noted above –
https://www.dropbox.com/scl/fi/gm8tor7nbtxpiv47hd8zr/Photopea-Bug-Video.mov?rlkey=myaqu2dl9muasvaym9n8k72m4&e=1&dl=0

**Comment by photopea** [comment]
This is an amazing description of a problem! I could see the issue myself even without watching your video.

I have fixed it - it is impossible to use File - Save, if the Free Transform is active.

**Comment by briefmockups** [comment]
> This is an amazing description of a problem! I could see the issue myself even without watching your video.
> 
> I have fixed it - it is impossible to use File - Save, if the Free Transform is active.

Thanks so much for taking care of this!

One minor concern – I create mockups, and came across this issue through a lot of experimenting after multiple customers reached out about their designs appearing blurry. It seems that for less experienced users, they don't intuitively understand that the transform operation requires confirmation before proceeding to another action, and I could see the new "Finish the current operation first" message potentially causing some confusion.

I'm curious if a slightly more streamlined approach would be replicating Photoshop's UX in this case, where users are given an option to either confirm or cancel the transform after using File > Save (see screenshot attached). Not sure how complicated this would be to implement, but wanted to get your thoughts.

![Photopea-bug-example](https://github.com/user-attachments/assets/497f4311-b9b6-4810-8015-7913e02b2114)

**Comment by photopea** [comment]
Okay, Photopea will just confirm the transformation now.

**Comment by briefmockups** [comment]
Perfect – thanks again!
