### ISSUE TITLE
Not enough RAM! (Need 3043MB )

### ISSUE THREAD

**Issue by area189** [photopea/photopea#7255]
![Captura de tela 2024-10-18 125038](https://github.com/user-attachments/assets/820b960f-ced3-408d-9a38-a753ac9f191f)
Your Operating System: Windows 11
Your Web Browser: Brave

When opening a file I am receiving the following message (image attached), I have already texted in browsers such as Opera, Brave, Vivaldi, I am using Windows 11.

**Comment by Mayur-hot** [comment]
Try other compatible and secure browsers like FireFox, Chromium, Chrome, Opera, Vivaldi..

Question Time:
Are you trying to open HUGE file? like 11GB of a .psd file and you may have 8GB of Ram configured?

Than You And Your Browser Both are Brave. :)

**Comment by photopea** [comment]
We recommend that you have at least 10x to 20x more RAM than the size of your PSD file. E.g. if your PSD is 100 MB, you need 2 GB of RAM.

How large is your PSD file and how much RAM do you have?

**Comment by photopea** [comment]
I have to close it because nobody is responding :(

**Comment by area189** [comment]
16GB

**Comment by photopea** [comment]
Do you have 16 GB of RAM or is your PSD file 16 GB in size?

**Comment by area189** [comment]
16GB
 RAM

**Comment by photopea** [comment]
And how large is your file?

**Comment by area189** [comment]
One of them 454,0 MB has and the other 831,2 MB

**Comment by photopea** [comment]
And do you know what is the width x height in pixels? Some browsers limit the RAM usage to 8 GB per website, which might be not enough for such large PSD files.

**Comment by area189** [comment]
200cm x 150cm
300dpi

**Comment by photopea** [comment]
That is 432 million pixels, which is quite a lot, but unless you don't have too many layers, it should be fine. Have you tried to use a different web browser?

**Comment by area189** [comment]
Yes, I tried with several browsers, including using Windows and now using Fedora.

The same file that I can't open in Photopea, I can open and edit normally in Adobe Photoshop, for example.
