### ISSUE TITLE
Some div elements don't fit my screen (too wide), so the right sidebar disappear.

### ISSUE THREAD

**Issue by Afrodark** [photopea/photopea#7256]
Your Operating System: Windows 10
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: No.

Issue: The width set in flexrow.app and other div elements are far too wide for my browser.
I don't know, why this isn't happening on incognito, but the thing is, I installed Stylus to "patch" this problem, so I can work normally on my PC. 

This happened right after paying $15. It's like the space for Ads got bugged or something.

**This must be done to see the problem**
1. Go to www.photopea.com (here the main stuff isn't centered)
2. Go to New project (the last settings column is half outside of screen)
3. Click Create (now you see the canvas, but +- 400px are missed on the right side, so the right sidebar cannot be clicked)

I solved this by using Stylus and applying this CSS:

`.flexrow .panelblock.mainblock {
    width: 1190px; /* lower px to see the right sidebar */
}

.panelblock {
    background-color: #444; /* background too see better the sidebar */
}

.flexrow .form {
    width: 370px !important; /* Document settings third column */
}

.flexrow.app > div:first-child > div:nth-child(3) > div:first-child {
  right: 320px !important; /* About Learn API etc buttons */
}
`
Without custom CSS -> ![image](https://github.com/user-attachments/assets/febb58d7-41e6-4f1a-9daa-0839f2a81962)
![image](https://github.com/user-attachments/assets/3ff17fbd-ddd1-4d28-b703-4f410ec884e6)
![image](https://github.com/user-attachments/assets/544583b2-248d-454d-b5ef-5582372abf66)

With custom CSS -> ![image](https://github.com/user-attachments/assets/c017b3d0-f424-4ad9-bad0-50919a114bcf)

**Comment by photopea** [comment]
This is a bug in Brave, they do this to Photopea on purpose. Please, write a comment in this issue: https://github.com/brave/brave-browser/issues/41552
