### ISSUE TITLE
Can't add file

### ISSUE THREAD

**Issue by LonDuma** [photopea/photopea#7259]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Hi, how can I help you? you need to answer the questions above.

**Comment by Mayur-hot** [comment]
You want to add file, but you Can't ...

please send a recorded video (Use Browser extension to record screen)

So, we get more information about your problems, and try to help you in a better way.

Thanks LonDuma

**Comment by photopea** [comment]
I have to close it, because nobody is responding to me.
