### ISSUE TITLE
.xcf file cannot open

### ISSUE THREAD

**Issue by pinkesh14patel** [photopea/photopea#726]
whenever I want to open .xcf file, photopea cannot open it.

**Comment by photopea** [comment]
Hi, we updated our XCF import recently. Maybe we made some mistake. Can you please send one of your files to support@photopea.com (or attach it here) ?

**Comment by giantspeck** [comment]
I am also having issues getting XCF files to load.  I have attached a sample XCF (compressed to ZIP) that I was trying to open this morning.  

[sidebar.zip](https://github.com/photopea/photopea/files/2053173/sidebar.zip)

**Comment by photopea** [comment]
There was a problem with reading data from text layers (Photopea can now detect Text layers inside XCF). It was fixed. Let us know if you have any other problem! :)

**Comment by pinkesh14patel** [comment]
Thank You...
