### ISSUE TITLE
One-click alignment options

### ISSUE THREAD

**Issue by DavyRetroGamer** [photopea/photopea#7260]
Your Operating System: Windows 11
Your Web Browser: Opera GX, Egde, Brave, Firefox, and Vivaldi

In Photoshop, in the alignment options, there are 3 dots “…”, when you click on it, at the bottom there will be an option written “align to:”, and there will be two options “selection” and “canvas”. When I select “canvas”, I don't have to select two layers, but just one, because the alignment options are enabled. As for the “selection” option, I need to select two or more layers for the alignment options to be enabled.

So I've come to request that this option be integrated into Photopea, as it will help a lot!

Thank you very much for your attention! 👍😁👍

**Comment by photopea** [comment]
I have added this option :)
