### ISSUE TITLE
Automate Resize problem

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7264]
Your Operating System: linux
Your Web Browser: opera
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Choose File->Automate->Resize Images...
3. Choose list of Files
4. Set New Width and Height + format
5. Press Resize images button
6. Wait for the result as zip file
7. Open downloaded zip file.
8. Extract images and then check size, but its same as original without any resize operation.
9. Do same for File -> Automate -> Convert Images.. Conversion is OK, but Resize operation is not performed.

To Test it use png file having 447x22 in size Width=447, Height=22,

and Resize that image to 865x23, but resize is not working, in output zip we have 447x22

Thank You.

**Comment by Mayur-hot** [comment]
![test](https://github.com/user-attachments/assets/3e9b4b4c-e782-460a-a1c4-75a97040c803)

png for test, we have to resize it, so png will remain png

**Comment by photopea** [comment]
The "Resize" feature allows you to set the "maximum width" and "maximum height".

It can not resize images to any width and any height. It can only make images smaller, and always keeps the aspect ratio.

**Comment by Mayur-hot** [comment]
for 450 images (same w x h) .. photopea converts from webm to png within in few seconds..
+ shrinking size is possible, but larger not possible.. How Complex to make image larger?

I am using desktop software right now to resize (inlarge) files.

**Comment by photopea** [comment]
What is the point of making PNG files larger? It does not imporove the quality when you resize 100x100 pixels into 1000x1000 pixels. Instead, you should just zoom in when you view these small files.

**Comment by Mayur-hot** [comment]
Right, in large PNG image does not improve the quality + for single image to view we can ZOOM...

I have a project in that wasm takes specific enlarged image files.. but it shows good image after in front..
