### ISSUE TITLE
Text doesn't appear in exported SVG

### ISSUE THREAD

**Issue by npastoCSTB** [photopea/photopea#7265]
Your Operating System: Widows
Your Web Browser: brave

1st THANKS for this great tool !!

issue : On most of exported SVG, texts don't appear.
For instance, on SVG exported from https://excalidraw.com/

view
<img width="463" alt="image" src="https://github.com/user-attachments/assets/bef7a0ba-d706-4be0-b4ed-3028e9fe6235">

instead of
<img width="383" alt="image" src="https://github.com/user-attachments/assets/4da34653-4bf1-4f73-80b6-348f2e5e2bff">

or https://www.plantuml.com/
<img width="241" alt="image" src="https://github.com/user-attachments/assets/d625bb0c-c81b-4066-9484-954c98b25751">

vs expected image view on site :
<img width="320" alt="image" src="https://github.com/user-attachments/assets/dd38b06d-432b-498e-8243-7aa6c61b9a42">

Is there a parameter to fix to make SVG displayed properly ?

thanks.

**Comment by Mayur-hot** [comment]
Do you have any test svg file as .psd? then share it to know actual problem..

I think you have to disable Shield or other extension that breaks photopea.com

try to use photopea.com into edge, chrome, vivaldi, opera, chromium

**Comment by photopea** [comment]
Are you saying that you have an SVG file, which after opening in Photopea and saving back as an SVG, looks differently (missing text in your case)? If yes, please, share that SVG files with us as a proof.
