### ISSUE TITLE
Missed or replaced fonts

### ISSUE THREAD

**Issue by wallyvianna** [photopea/photopea#7266]
I opened a PDF file at Photopea and it replaced all documents fonts. There is how define the fonts to be replaced manually?

**Comment by photopea** [comment]
Photopea can not extract fonts out of PDF files. If your PDF uses commercial fonts, like Helvetica, and you own that fonts, just load these fonts into Photopea (File - Open - TTF/OTF file), and Photopea will re-render all text with the new font.

**Comment by photopea** [comment]
I have to close it, because nobody is responding to me.
