### ISSUE TITLE
HEllo my Friend! 

### ISSUE THREAD

**Issue by Sanyek11** [photopea/photopea#7268]
I want to complain about the "Photopea" site, a couple of us in college were given an assignment on this site. The site does not work well and throws and throws various errors.
Site https://www.photopea.com/

**Comment by Mayur-hot** [comment]
Hello Sanyek11, well, you have to give proper details about "What does not work?"
You have to send recording as a prof (Use browser extension like screen recorder)..

Thank You, I hope you will get better grade for your assignment.

**Comment by photopea** [comment]
I have to close it, because nobody is responding to me.
