### ISSUE TITLE
Cmd (Ctrl) + spacebar + click don't work on mac

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#727]
Same thing for zoom out with Cmd + Alt + spacebar + left mouse button click.
In Firefox I see magnify icon when I use Ctrl (not Cmd) but It doesn't work when I'm clicking. Only cursor blinking (on Safari even that don't work).

**Comment by photopea** [comment]
Hi, I just tried it in MacOS High Sierra and Ctrl + Spacebar + Click works well both in Safari and Chrome.

Do you have any software or extensions, that may be "stealing" your clicks? E.g. some software converts Alt + Click into a right-click.

**Comment by MichalSZZ** [comment]
It should work with Cmd not Ctrl (Cmd = Ctrl on Mac, for example Cmd + Z make undo - also in Photoshop).
On 2 Macs (one with High Sierra 10.13.4, 2nd with El Capitan), it doesn't work. In Windows all is OK.
I think that isn't browser extensions, because in Safari (where I don't have any extensions) don't work too.

**Comment by photopea** [comment]
So does it work with Ctrl on Mac?

**Comment by photopea** [comment]
I just made it work with Command the same as with Ctrl. Can you check it again, please?

**Comment by MichalSZZ** [comment]
Hmm, not really.
When I use Ctrl + spacebar, cursor icon switch to magnifier (with +), but after click, doing nothing (cursor switch only in FF, in Safari not)

**Comment by photopea** [comment]
Once you see the magnifier, the Zoom tool is on, and clicking should work the same as with the Zoom tool. I really think your clicking is a right-click (try to click this way somewhere else in your OS).

**Comment by MichalSZZ** [comment]
Now after you have wrote second comment - it works well!
Thank you again!

**Comment by MichalSZZ** [comment]
:) I think that, on Mac nobody use Ctrl. Everywhere in programs where on windows shortcut is Ctrl + something, on MAc there is Cmd + something.
I'm not Apple big fan. I'm using Mac in my work but know (and use) Windows too.

**Comment by photopea** [comment]
Ok so it works on Mac with a Command in all browsers? If yes, you can close the issue :)

**Comment by MichalSZZ** [comment]
Yes. Now works OK for:
FF
Chrome
Opera
Safari 11 (High Sierra) - OK

Safari 10 (El Capitan) - NOT OK - but don't worry with that :)

You can close this issue, and thank you so much again!
