### ISSUE TITLE
HTTP error 401 peadrive

### ISSUE THREAD

**Issue by cyliamart2** [photopea/photopea#7270]
Your Operating System: MacBook 2020 M1 Chip
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Not unless I'm logged into my account

**This must be done to see the problem**
1. Go to www.photopea.com
2. Logged into my account
<img width="793" alt="Screenshot 2024-10-25 at 4 43 19 pm" src="https://github.com/user-attachments/assets/a97db509-11ae-4643-bae0-5fcf798c7d72">

3. Tried to open Peadrive
4. Error msg

**Comment by photopea** [comment]
Could you tell me the email address of your Photopea account? Click "Account" at the top to see it.

**Comment by cyliamart2** [comment]
> Could you tell me the email address of your Photopea account? Click "Account" at the top to see it.
cyliamart25@gmail.com

**Comment by photopea** [comment]
Okay, could you try it again?

**Comment by cyliamart2** [comment]
It works now but nothing in my peadrive has loaded

**Comment by cyliamart2** [comment]
It's just a white screen

**Comment by photopea** [comment]
Did you log in to Photopea with the same email that you used in the past?

**Comment by cyliamart2** [comment]
Yes however it's all good now, I got it to work - just had to refresh chrome and log out a couple times

**Comment by photopea** [comment]
Ok, I will close it now.
