### ISSUE TITLE
Image position resetting after using other options (buttons only)

### ISSUE THREAD

**Issue by MegaMinerDL** [photopea/photopea#7272]
Your Operating System: Windows 10 Home latest
Your Web Browser: Microsoft Edge
The problem happens in the Incognito Mode, too: True, no extensions

**This must be done to see the problem**
1. Go to www.photopea.com
2. Import an image
3. At any point, select the image and use the top bar buttons (NOT the mouse) to change image position
4. Right after (Without deselecting), change either the image scale, rotation, H, or Y (Issue does not occur with Warp)
5. The image has moved back to its original position after the scale/rotation is applied
6. This only happens if the image position is changed first, it does not occur with the other options in another order

**Comment by photopea** [comment]
I am confused, what should you do between step 2 and step 3? 

By "Import", you mean opening (File - Open)?

After opening an image, I can not see any buttons in the top bar to change the image position.

**Comment by MegaMinerDL** [comment]
> I am confused, what should you do between step 2 and step 3?
> 
> By "Import", you mean opening (File - Open)?
> 
> After opening an image, I can not see any buttons in the top bar to change the image position.

Sorry, what I mean:

Import as in "have an image you will be moving around on the canvas". Such as by dragging an image onto the canvas.

After opening the image:

Select it (the layer) with the move tool, then (I forgot to add:) you have to click the border to reveal the options at the top

![Zrzut ekranu 2024-10-27 004723](https://github.com/user-attachments/assets/2fc4cfda-e2f3-442b-bb21-800fa91b538f)

Now you can move it to a custom location with the numbers (1), then use anything else (2) right after, and the image will strangely move back to its original position.

Sorry if this is specific, I like to use the numbers to move an image, while simultaneously adding a rotate or whatever.

**Comment by photopea** [comment]
It should be fixed now, thanks for reporting it! :)
