### ISSUE TITLE
Opacity and Fill do the same thing

### ISSUE THREAD

**Issue by stefa-shary** [photopea/photopea#7273]
Your Operating System: Windows 10 
Your Web Browser: Google Chrome 
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Put a shape 
3. Color it to anything
4. Go to "Blending Options"
5. Then find "Opacity" and "Fill"
6. After that put random numbers and it will do the same thing

https://github.com/user-attachments/assets/3a1e04ca-44ab-471f-9675-ab7800ed9a61

**Comment by bluep55** [comment]
Give your image a Stroke or Bevel etc. then try again.


https://github.com/user-attachments/assets/be909908-dc9d-4161-ba78-1778da1cc985

**Comment by bluep55** [comment]
Give your image a Stroke or Bevel etc. then try again.
https://www.youtube.com/watch?v=Bv-XaNLR218


https://github.com/user-attachments/assets/5b605e87-a42c-47dc-aee9-896879cf7617

**Comment by stefa-shary** [comment]
Hi!

So, my problem is that I am a logo maker. I need different colors for that.
Opacity helped me to achieve that by making the color darker or lighter.
That's my problem.

Thank you,
Stefan

În sâm., 26 oct. 2024 la 20:06, bluep55 ***@***.***> a scris:

**Comment by stefa-shary** [comment]
Hi!

I am a logo maker. I need to make some colors lighter or darker and Opacity
helped me to do that. So, that is my problem.

Thank you,
Stefan

În sâm., 26 oct. 2024 la 20:06, bluep55 ***@***.***> a scris:

**Comment by stefa-shary** [comment]
For this logo I had to use the Opacity thing to make the green darker
because the color of the green isn't in the color section.[image: New
Project (32).png]

În sâm., 26 oct. 2024 la 20:35, Samurai ***@***.***> a
scris:

**Comment by photopea** [comment]
How do you think it should work instead, and why?

**Comment by photopea** [comment]
Please, open www.github.com in your web browser and reply there. Do not send emails to random github addresses like tpwertlkengslfgjktjwreptiwrelkasdjf@github.com

**Comment by stefa-shary** [comment]
> How do you think it should work instead, and why?

When you turn the Opacity down it should make the color darker and when you turn it up it should make it lighter. That what it would do before the Opacity and the Full became the same thing.

**Comment by photopea** [comment]
> > How do you think it should work instead, and why?
> 
> When you turn the Opacity down it should make the color darker and when you turn it up it should make it lighter. That what it would do before the Opacity and the Full became the same thing.

Does it work like this in any program?

**Comment by stefa-shary** [comment]
I don't use any other program.

**Comment by bluep55** [comment]
Opacity and fill have always worked like this. If you lower the opacity, objects become transparent, Are you confusing Opacity and fill with other actions such as levels, Curves, exposure or Brightness/Contrast which can all be found under Layer > New Adjustment Layer? These can all make your image darker or lighter.

**Comment by stefa-shary** [comment]
I will check it out and get back to you as soon as possible!

**Comment by photopea** [comment]
I have to close it, because I think everything works "as described". It is a problem only if something works differently than described.

You can search the internet to learn the difference between these two options, e.g. here: https://www.youtube.com/watch?v=ok9cVCETDeE
