### ISSUE TITLE
Can't close Photocrea window after working some time (after 10m-15m ).

### ISSUE THREAD

**Issue by somirons** [photopea/photopea#7274]
Your Operating System: fedora KDE Plasma
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too: No

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Hi, are you talking about www.photopea.com ?

Does it work correctly in the Incognito mode?

**Comment by somirons** [comment]
Yes it is working in incognito mode. But I can't close it from the
installed app on Fedora KDE plasma 6.2.2.

**Comment by somirons** [comment]
Yes it is working in incognito mode too. But I can't close it from the installed app on Fedora KDE plasma 6.2.2.

**Comment by photopea** [comment]
I don't know what you mean by "installing app on Fedora KDE plasma", I never worked with Fedora :(

Maybe report it to those who enabled you to install Photopea as an app. Because Photopea is just a website and is used in a browser.

**Comment by photopea** [comment]
I will close it now.
