### ISSUE TITLE
Gradient

### ISSUE THREAD

**Issue by MoKoCho-PS** [photopea/photopea#7276]
Hello,

I try to load a ggr file but since that, gradient menu is blocked. 
when I try to unroll the menu of available gradients there is no reaction.
Before that it was a grd that I had tried to load and if it appeared in the menu, it created a PS gradient menu in addition to Default gradient but empty.

Can you help me please?
Thanks

**Comment by Mayur-hot** [comment]
Hello MoKoCho-PS,

Pleasse record a video using screen record or other extensions and upload here, that will help Ivan (Main developer of this photopea/photohammer project.)

Thank you very much.

**Comment by photopea** [comment]
I need to see this problem myself. Could you share your GRD file with us, so that I can see what is happening?

**Comment by photopea** [comment]
@tlongle it is fixed now.
