### ISSUE TITLE
SHARE BUTTON

### ISSUE THREAD

**Issue by FrancescoThomasFalanga** [photopea/photopea#7277]
Your Operating System: Windows 11
Your Web Browser: Chrome - Opera GX
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Upload a File
3. Share it to PNG or JPG to Imgur 
4. It says that is Saving the file to Imgur, but i will get no Link or no Authentication for the Imgur Account

**Comment by FrancescoThomasFalanga** [comment]
Updates: Although the JPG split works, but the PNG continues to give problems, not showing any links. I therefore ask if the images are uploaded to Imgur anyway, because I am modifying a personal image and by mistake instead of uploading them to my PC I shared your IMGUR but as a PNG... So I would like to request a deletion if it were to be online...

**Comment by photopea** [comment]
It seems to work for me now :( Do you still have problems with it?

Note, that Imgur allows you (your IP address) to upload at most 500 images in a day.
