### ISSUE TITLE
page to big when logged in

### ISSUE THREAD

**Issue by luxxelement** [photopea/photopea#7278]
Your Operating System: windows
Your Web Browser: brave

**This must be done to see the problem**
1. Go to www.photopea.com
2. login
3. the page to work is to big to see the right hand side panel (has been happening for some time.
![not logged in](https://github.com/user-attachments/assets/83ef9f62-5412-4ca0-9f64-df427bed35d0)
![logged in](https://github.com/user-attachments/assets/c50c261c-2d83-45eb-9d5e-1ec61ba766df)

4. ....

**Comment by photopea** [comment]
Hi, this is a bug in your web browser - Brave. I have heard that it works fine if you disable Brave shields. Or switch to a better browser - other browsers don't have this problem.

**Comment by ryanbr** [comment]
Looks fine here.

![photopp](https://github.com/user-attachments/assets/6de7efe2-4f18-469a-8dfd-7513ad04c6c6)

**Comment by kuckir** [comment]
@ryanbr This issue happens in Brave only to those who pay for Photopea Premium (your Account button at the top must be green).
