### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by fmchris10** [photopea/photopea#7279]
I have found Photopea to be a breath of fresh air. I have used it to update various graphics whilst away and since I didn't take my laptop. I found using my phone and tablet to be a very practical solution for needing a Photoshop alternative.

However, the loading... gives no indication as to how much is loaded.

I found myself at times wondering if my connection would ever see my design load, so that I could edit the template and then download the finished graphic. It would be nice if Photopea could show a percentage of how much has been loaded, along with prompts if things are taking a little longer due to a weaker signal.

Also, I found it incredibly difficult to position things at times.

I know, you can move things based on number based variables, but it would be super handing if you could activate a control panel, with up, down, right and left actions. Pressing would allow you to position things much easier, without having to worry that you can place it properly with your finger or using the numbers.

**Comment by photopea** [comment]
Hi, what do you mean by loading? Are you talking about opening a file from your device by pressing File - Open? It is usually opened in under 1 second.

What do you mean by a control panel with up/down/left/right ?

**Comment by photopea** [comment]
I have to close it now, because nobody is responding.
