### ISSUE TITLE
Is it a possibility to open .CDR file?

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#728]
I know that corel draw vector files are very rare, but in my country this software was very popular and many clients have for exaple old logos only in that format.

I bought scanner with OEM version of Corel only for opening CDR and exporting to any other vector format like EPS for example :)
It is funny but many people looking online converter for those files.

**Comment by photopea** [comment]
Sadly, I can not find the .CDR specification anywhere :(

**Comment by MichalSZZ** [comment]
Inkscape uses this build-in converter tool to open CDR files.
https://sk1project.net/modules.php?name=Products&product=uniconvertor

Maybe that will be helpful for you in any way?

**Comment by photopea** [comment]
I ask them today about it: https://www.facebook.com/permalink.php?story_fbid=1918222448197182&id=308311182521658&comment_id=1918269301525830&reply_comment_id=1918280664858027&notif_id=1528105018567442&notif_t=feed_comment

They are preparing some new library.

**Comment by photopea** [comment]
BTW. do you know what version are your CDR files? It seems like there are many CDR formats, and new Corel Draw can not read files generated by the old Corel Draw.

https://community.coreldraw.com/cfs-file/__key/telligent-evolution-components-attachments/00-27-01-00-00-13-17-41/coreldraw_5F00_rw_5F00_support.gif

**Comment by photopea** [comment]
I added the basic support for CDR files :)
