### ISSUE TITLE
Grid is not pixel accurate in WebGL mode

### ISSUE THREAD

**Issue by n128-98** [photopea/photopea#7281]
Your Operating System: ChromeOS
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:
Yes
**This must be done to see the problem**
1. Go to www.photopea.com
2. Go to More --> Use WebGL
3. Turn On Grid Through Edit --> Preferences --> Grid
4. See Results
Grid Seems to move jaggedly when scrolling, zooming, ect, almost never is accurate to grid without turning off WebGL

**Comment by photopea** [comment]
I looked at the grid with and without WebGL, and it looks the same in both cases. But I do it in Windows, I don't have a Chrome OS.

Could you share a screenshot of what you see in your case? Also, what Chrome OS version do you use, or what device?

**Comment by photopea** [comment]
I have to close it now, because nobody is responding.
