### ISSUE TITLE
Bad lag

### ISSUE THREAD

**Issue by ditolus** [photopea/photopea#7284]
Over the last 2 days I've been experiencing bad lag using photopea.  On the website as well as the downloadable version.  I think it might be the ads.

Your Operating System: windows
Your Web Browser: Google chrome
The problem happens in the Incognito Mode, too: dont know

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Please, answer the questions about your browser and OS, and the incognito mode.

**Comment by photopea** [comment]
I have to close it now, because nobody is responding.
