### ISSUE TITLE
Action cannot be recorded. Add text

### ISSUE THREAD

**Issue by LvLaoTou** [photopea/photopea#7285]
Your Operating System: win11
Your Web Browser: Google Chrome 130.0.6723.70
The problem happens in the Incognito Mode, too: Yes
﻿
**This must be done to see the problem**
1. Go to www.photopea.com
2. Open recording action
3. Add text
4. There is "Type tool" in the history, but not in the actions
![PixPin_2024-10-31_18-43-21](https://github.com/user-attachments/assets/1d6c0aea-bb22-4fca-ae04-efb80289ed8c)

**Comment by photopea** [comment]
I have implemented it. You can record creating new text layers as an action now.
