### ISSUE TITLE
Feature Request: Reset Transform and Convert to Layers

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#7287]
Photoshop has these 2 features for smart object.

1. Reset Transform: Reset scale, rotate, distort, etc.
2. Convert to Layers: Turn smart object into a folder with layer structure preserved.

![0](https://github.com/user-attachments/assets/621ab3d9-200d-40bb-839a-fc838cb207e8)

**Comment by photopea** [comment]
I have added these options. When you right-click a layer, there is an item "Smart Object" in the menu, which contains more options.
