### ISSUE TITLE
Import layers by dragging them to the Layers panel, the order is reversed

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#7288]
Dragging and dropping layers into layer panel, layers are imported top-to-bottom. It is differrent from dropping on canvas or use File -> Open..., which is bottom-to-top

1. drop on canvas
![image](https://github.com/user-attachments/assets/634e2a80-69e7-4ded-9473-982d288dada1)

3. drop on layer panel
![image](https://github.com/user-attachments/assets/9d461f2c-f7dd-41ba-81ed-7fbd794917d7)

**Comment by photopea** [comment]
it should be fixed now. Files should load in the same order now.
