### ISSUE TITLE
Filter Halftone Pattern not working

### ISSUE THREAD

**Issue by shaz2000** [photopea/photopea#7290]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....import a photo 
3. ....select halftone filter 
4. ....(blanc page appears)

**Comment by photopea** [comment]
You must tell us your operating system and other details that you see in
our issue template.

**Comment by photopea** [comment]
I have to close it because of lack of details. Nobody else is reporting such a problem.
