### ISSUE TITLE
gif not exporting

### ISSUE THREAD

**Issue by koalakoala592** [photopea/photopea#7291]
whenever i try to export my manip gifs (two gifs blended together on a template background from new project), this always shows up instead of my gif. it has been going on for a while. i tried doing making my gif on different accounts and even incognito mode but i get the same results
[![Screenshot 2024-11-03 013857](https://github.com/user-attachments/assets/be8ec084-3a2e-42be-8656-8b0c5365efb7)
](url)

**Comment by photopea** [comment]
What should I do to see this problem? Do you know how animations work in Photopea? Did you read this article? https://www.photopea.com/learn/animations

I have no idea what you mean by "two gifs blended together". There are animations and frames, and layers.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
