### ISSUE TITLE
RESIZING ISSUE SOVLED (MAYBE)

### ISSUE THREAD

**Issue by Incelations** [photopea/photopea#7293]
Ever since I stopped using an ad blocker on photopea, transforming and resizing is working perfectly fine. May be a fix to others too.

**Comment by photopea** [comment]
uBlock Origin is breaking the free transform in Photopea (other ad blockers do not), I think it is well known, we told it to everyone who reported this problem.

**Comment by photopea** [comment]
I will close it now.
