### ISSUE TITLE
(suggestion) Marker tool

### ISSUE THREAD

**Issue by MesaBlack** [photopea/photopea#7295]
So, I've been using a lighter-colored brush with the opacity lowered and there's no pure black, it's just mixing the color of the brush with the image under it.
![image](https://github.com/user-attachments/assets/a8882a51-9f04-43e0-854f-ee82b76ef752)

### The marker tool.

It's just like an how an actual marker would work: it's not opaque or translucent, so if, say, an orange marker was drawn on a black-and-white doodle, the dark areas would barely change their color.

**Comment by photopea** [comment]
I am confused. How exactly should your marker tool work? Could you show us an image before painting and after painting with a marker?

**Comment by MesaBlack** [comment]
![image](https://github.com/user-attachments/assets/fbe1436b-f4a1-4922-a114-0102fdd66af9)

![image](https://github.com/user-attachments/assets/5a2877e1-a115-4f05-b534-7eefebda9a3b)

**Comment by photopea** [comment]
So the orange color is the marker? Just use the Brush tool and set the blend mode to Multiply.

**Comment by MesaBlack** [comment]
oh

**Comment by MesaBlack** [comment]
but if I draw a multiply brush line on another multiply brushline, the color gets darker. how do I avoid that?

**Comment by MesaBlack** [comment]
nvm I'll figure that out myself

**Comment by photopea** [comment]
You can use the "Darken" or "Darker Color" blend mode instead of "Multiply".

Or just draw into a separate layer (brush uses "Normal" blend mode), and set the blend mode of that layer to "Multiply".
