### ISSUE TITLE
Gradient overlay causes clipping mask not to work.

### ISSUE THREAD

**Issue by ValiantUIX** [photopea/photopea#7296]
Your Operating System: Windows 11
Your Web Browser: OperaGX but it happens on google, and microsoft edge aswell.
The problem happens in the Incognito Mode, too: Yes.

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new project of any size
3. Using the shape tool create any shape of any size.
4. Open blending options on said shape and turn on a gradient overlay.
5. Then import any Image/shape.
6. Using the image/shape pull it to the top layer and make it a clipping mask on the gradient shape while on top of the shape.

this is what I do and the clipping mask is not visible, please help asap.

**Comment by photopea** [comment]
This is how it should work. Layer styles (Gradient Overlay, etc.) are rendered on top of layers above, which have clipping masks.

You can set the fill of your shape to Gradient, without using the Layer Styles, see https://www.photopea.com/learn/vg-structure#:~:text=is%20a%20polygon).-,The%20Look,-While%20vector%20masks

**Comment by ValiantUIX** [comment]
> This is how it should work. Layer styles (Gradient Overlay, etc.) are rendered on top of layers above, which have clipping masks.
> 
> You can set the fill of your shape to Gradient, without using the Layer Styles, see https://www.photopea.com/learn/vg-structure#:~:text=is%20a%20polygon).-,The%20Look,-While%20vector%20masks

Thank you so much!
