### ISSUE TITLE
[Vectorpea Feature Request] Subtract or combine shapes

### ISSUE THREAD

**Issue by kevin-kessler** [photopea/photopea#7297]
Thanks a lot for providing Photopea and Vectorpea - you are doing great work!

In Vectorpea, it would be really useful to have a feature that allows to subtract or combine shapes, similar to what you can do in Illustrator.

For example
- https://logosbynick.com/subtract-shapes-in-adobe-illustrator/
- https://www.youtube.com/watch?v=7VX7QStImYk&ab_channel=DesignMadeSimple

![image](https://github.com/user-attachments/assets/3a8939af-bad2-44e6-838f-01840db6080b)

Thanks for considering the request, in case it isn't on your list yet!

**Comment by photopea** [comment]
I have implemented it, and it works just like in Photoshop or in Illustrator, could you test it out? :)

In Vectorpea or in Illustrator, use Window - Pathfinder.

In Photopea or in Photoshop, use Layer - Combine Shapes - Unite / Subtract / ...

**Comment by kevin-kessler** [comment]
Fantastic! Just tried it, works like a charm. Bravo and thank you! Keep up the great work :)
