### ISSUE TITLE
Template Thumb + Image is different

### ISSUE THREAD

**Issue by Mayur-hot** [photopea/photopea#7300]
Your Operating System: Linux
Your Web Browser: Opera
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Choose Templates
3. in search box type bott
4. from bottle select "Cosmetic Pump Bottle Mockup"

See thumbnail and open it..
below is the link
https://www.photopea.com/#tEc2G21Mm

![bug0](https://github.com/user-attachments/assets/f821c069-a3a6-4a20-9191-39498c4e54e7)

after opening this looks like below
![bug1](https://github.com/user-attachments/assets/4b32406c-9b9d-4ca9-b907-f6a2bde05c98)

What's the reason?

Thank You

**Comment by photopea** [comment]
The creator of that template can upload any preview image they want. It does not have to correspond to what you see when you open a template.
