### ISSUE TITLE
Incorrect display of website

### ISSUE THREAD

**Issue by Smailenty** [photopea/photopea#7302]
Your Operating System: Windows 10
Your Web Browser: Google Chrome latest version
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Thats it!
Screenshots
![1](https://github.com/user-attachments/assets/eaaec2ea-09ef-4ffe-9a8c-f4e12bd7d2e1)
![2](https://github.com/user-attachments/assets/a95e120f-456a-4199-8ac9-dd3679992f45)

Problem description: as usual I opened website and immediately saw incorrect graphic display of elements (I tried to reduce the visible window in the Google Chrome settings but it doesnt work). 
After that i tried to add a project and I also encountered incorrect graphic display of elements and the inability to use the service in any way

I hope my bag report will help you to fix the problem

**Comment by oduvnix** [comment]
I have the same problem! I thought it was my laptop, but that's how the site looks everywhere. Thank you for writing, at least I know that this is a common problem.

**Comment by photopea** [comment]
Are you both from Russia? Do you use a VPN, which could be modifying our source code?

**Comment by photopea** [comment]
I just uploaded a new version to our CDN. Maybe the problem could be in the CDN.

Do you see any errors in the web console?

**Comment by oduvnix** [comment]
It is working perfectly!! Thank you very much

**Comment by photopea** [comment]
Okay, it is really strange. Maybe we should stop using our CDN.
