### ISSUE TITLE
ICO Export cuts canvas to upper left quater

### ISSUE THREAD

**Issue by samtun** [photopea/photopea#7303]
Your Operating System:
* Windows

Your Web Browser:
* Chrome

The problem happens in the Incognito Mode, too: 
* yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create anything
3. Try exporting it as ICO

![Screenshot 2024-11-08 113227](https://github.com/user-attachments/assets/5268324e-fbc8-496f-baa9-5e8ebddd6cf1)

**Comment by samtun** [comment]
TIL: ICO has a maximum size.

It's fine, did not know that and was confused. Thanks for the quick reply.

**Comment by photopea** [comment]
When you export a large image as ICO, Photopea tells you "The maximum ICO size is 256x256" :)
