### ISSUE TITLE
Having Ghostery's Ad-Blocker block photopea.com's ad blocker pop up prevents some features from working when it tries to show up.

### ISSUE THREAD

**Issue by mrrfyW** [photopea/photopea#7304]
Your Operating System: Windows 10 Pro
Your Web Browser: Opera GX (114.0.5282.148)
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Have Ghostery enabled (I know this harms your revenue but trust me on this), with www.photopea.com under "unidentified" blocked.
2. Go to www.photopea.com
3. Try to use the transform tool or delete key on a new layer (or just use the site normally).
4. Wait a minute or two.
5. The transform/delete things (and some other features that I'm unsure of) no longer work until you refresh the page or continuously press escape while trying to perform an action, since the pop up isn't able to appear.

Proof:

https://github.com/user-attachments/assets/75ef602d-40bb-4889-849b-990432ee5b9c

**Comment by photopea** [comment]
So Photopea works fine without your ad blocker, but it is broken with your ad blocker? How exactly is this a bug in Photopea and not in your ad blocker? I do not understand your logic.

Or did you report it to the creator of your ad blocker?

**Comment by mrrfyW** [comment]
I don't know if it's something wrong with my browser or the extensions I have installed, but I don't think I found any extensions I have on that are possibly causing this issue.

**Comment by mrrfyW** [comment]
Okay, so I just figured out that it's not because of the adblocker, it's just the fact that the "Are you blocking our ads" pop up being blocked by Ghostery (ad-blocking extension) causes the site to break, because it isn't re-enabling the ability to do things on the page (Hence the title change, again).

**Comment by mrrfyW** [comment]
...Should I close this?

**Comment by photopea** [comment]
How exactly can I help you? You did not ask us any question.

If you allow your browser extension to do anything it wants to Photopea, and it breaks Photopea, we can not fight it. A website can not turn off your browser extension :( what do you think we should do?

**Comment by photopea** [comment]
I have to close it, because nobody is replying :(
