### ISSUE TITLE
Rounding is broken after export

### ISSUE THREAD

**Issue by natsie** [photopea/photopea#7306]
Your Operating System: Windows 10
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: not tested

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a rectangle spanning the entire canvas.
3. Set a gradient stroke on the rectangle
4. Export (so far the bug has shown on SVG and WebP exports.

Screenshot from Photopea
![image](https://github.com/user-attachments/assets/1a069a2c-705b-468d-9a3b-f61954ef5c4d)

Exported SVG
![jscompile](https://github.com/user-attachments/assets/b74dac04-b34f-4642-891d-6e8b6b9784b4)

**Comment by photopea** [comment]
I did what I think you are doing, but I can not see such a result :(

Could you share your PSD file with us?

**Comment by natsie** [comment]
Here is the PSD file (I had to zip it because of GitHub):
[jscompile.zip](https://github.com/user-attachments/files/17689018/jscompile.zip)

**Comment by photopea** [comment]
Ok, I see. This is because stroke rendering in Photopea works differently than in SVG. In SVG, stroke is placed on top of an object, while in Photopea, it replaces the edge of an object. If the stroke is opaque, the result is identical. But your stroke contains transparency.

Try to place your stroke "outside" the object. Or expor it as a PNG or WEBP (it will export pixels instead of vector graphics).

**Comment by natsie** [comment]
Here is a preview of a png export:
![image](https://github.com/user-attachments/assets/1e7ba980-6843-4db8-b3df-47c3fe65fb91)

but this is the edge on Photopea:
![image](https://github.com/user-attachments/assets/dd09b385-70be-4271-88b9-0feaf9f6e5d8)

here, i've tried to highlight the issue with the edge (i think it's more clear)
![image](https://github.com/user-attachments/assets/8c1f9922-bc95-4547-bba2-a1741a0bf176)

also just before sending this reply, i tried a jpg export and the issue doesn't show there
![jscompile](https://github.com/user-attachments/assets/3214adca-c4fc-4bb5-be93-0db974ad91f6)

**Comment by photopea** [comment]
You should get the same PNG file no matter what web browser you use.

**Comment by natsie** [comment]
I think you misunderstood my previous reply. I am still using Google Chrome. Likewise, I just said that I highlighted (or rather circled) out the issue with the edge in my last reply. I didn't change browsers, though.

**Comment by photopea** [comment]
The corner of your image looks the same to me in all images that you have shared. What is the problem?

**Comment by natsie** [comment]
The corners are not all the same (especially in the formats that support transparency). However, I have resorted to just reducing the size of the rectangle to make sure that it doesn't touch the edge with fixed the issue.

**Comment by photopea** [comment]
Corners do look the same in your screenshots. The stroke is partially transparent, so its color depend on the background color.
