### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by hope-creator** [photopea/photopea#7307]
I open the app and see this, nothing else happens. What should I do about it?

**Comment by photopea** [comment]
what app are you talking about? Can you open a website www.photopea.com ?

**Comment by hope-creator** [comment]
It’s the same on the website, just this blank screen.

**Comment by photopea** [comment]
Could you tell us your operating system and your web browser, and if you tried it in the Incogntio window?

**Comment by hope-creator** [comment]
Already solved the problem, the application simply does not work in Russia, everything is fine with VPN

**Comment by photopea** [comment]
Are you sure? I just used a VPN to connect to Photopea from St. Petersburg, and it seems to work fine :(

When Photopea does not work, can you see any problems in the web console?
