### ISSUE TITLE
Mistakes in the Arabic translation 

### ISSUE THREAD

**Issue by rori5000** [photopea/photopea#7308]
Translation mistakes in the following 
Cut is translated to قطع  the correct is قص
polygonal lasso tool is translated to اختيار بالوهق الكثير الضلع  the correct is التحديد بالوهق المتعدد الأضلاع 
All selection tools are translated to اختيار the correct is تحديد
bucket tool is translated to اداة دلو الدهن  the correct is اداة دلو اللون

Thank you

**Comment by photopea** [comment]
Thanks a lot! Could you insert these phrases into our translation tool? https://www.photopea.com/translate/

**Comment by photopea** [comment]
I have to close it, because nobody is replying :(
