### ISSUE TITLE
Using CMD + S stucks app on Mac OS X

### ISSUE THREAD

**Issue by jvaclavik** [photopea/photopea#7309]
Your Operating System: **Mac OS X 14.3 (23D56)**
Your Web Browser: **Version 1.63.1 (54714), Chromium Engine Version 129.0.6668.101**
The problem happens in the Incognito Mode, too: **Yes**

**This must be done to see the problem**
1. Go to www.photopea.com
2. use CMD + S for saving image
3. App stucks and I can't see confirmation dialog or do anything else (In expose I can see that there is another window but I can't click on it)

Video here:
https://github.com/user-attachments/assets/b535feca-1214-4e0a-9101-4d1728afbd72

**Comment by jvaclavik** [comment]
> What web browser do you use? Are you talking about one browser or two browsers? I am not familiar with these web browsers:
> 
> "Version 1.63.1 (54714)"
> 
> "Chromium Engine Version 129.0.6668.101"

Oh, sorry I forgot! I use [Arc](https://arc.net/)

**Comment by photopea** [comment]
Did you try it in other borwsers like Safari or Microsoft Edge? I think it could be a bug in the Arc browser.

**Comment by jvaclavik** [comment]
> Did you try it in other borwsers like Safari or Microsoft Edge? I think it could be a bug in the Arc browser.

You are right, it works in Safari 💪 thanks

**Comment by photopea** [comment]
I really think it is a bug in Arc. Could you report it to them?

**Comment by jvaclavik** [comment]
> I really think it is a bug in Arc. Could you report it to them?

Done. Thanks for help 👍
