### ISSUE TITLE
Unreadable text in input::selection on dark Photopea theme

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#731]
In the default dark theme, it is hard to see what is in Input elements, when you select some text by the mouse. I think, for this color theme it should be different CSS

.darktheme input::selection {
  background-color: differentcolor;
  color: differentcolor;
}
<img width="262" alt="obraz" src="https://user-images.githubusercontent.com/38118273/41003905-4ed5585e-6918-11e8-93d0-f772ddf9053a.png">

I think that is a default browser setting, because in chrome it looks much better.

**Comment by MichalSZZ** [comment]
same thing for layer or mask selected
<img width="264" alt="obraz" src="https://user-images.githubusercontent.com/38118273/41006486-06b03fc6-6922-11e8-9ede-92b570fd621c.png">

.head .active canvas {
    border: 2px dashed black;
    margin: 2px;
}

will be better with white color

<img width="257" alt="obraz" src="https://user-images.githubusercontent.com/38118273/41006447-dfb88324-6921-11e8-84e1-83e2067d1e45.png">

**Comment by MichalSZZ** [comment]
Firefox on mac OS

**Comment by photopea** [comment]
The default style of selection should be always readable. So I think it is a bug in Firefox. I reported it to developers: https://bugzilla.mozilla.org/show_bug.cgi?id=1467715

**Comment by MichalSZZ** [comment]
Thanks! 
Should I make new Issue with my second suggestion (dashed border on layer thumbnails and masks in dark themes)?

**Comment by photopea** [comment]
I think the white border around the thumbnail looks ugly. We do not need a very strong border, the black border is ok I think.

**Comment by photopea** [comment]
I changed the border to white.
