### ISSUE TITLE
Transforming stroked layer crashes the webapplication

### ISSUE THREAD

**Issue by NilsKrause** [photopea/photopea#7310]
Your Operating System: Windows, none other tested
Your Web Browser: Firefox, Chrome seems to work
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a new project
3. Create and select a new layer
4. Create any form on that layer with the select tool and fill it with any color
5. Give the layerstyle a stroke, settings do not seem to matter, but those are the ones that crashed it for me the first time.
![grafik](https://github.com/user-attachments/assets/73bdc0ac-0e6b-4f9d-af79-de82d72a71fe)
6. Enter transform mode on that layer (Ctrl+Alt+T)
7. Drag one edge with the cursor -> The application crashes -> you cannot save (you get a corrupted file), tools are selectable but useable, etc

Exception in the console is: `Uncaught RangeError: source array is too long`

![grafik](https://github.com/user-attachments/assets/7bd50836-1c88-4ebd-9e5c-913b0e9a23e6)

---

Btw: Love Photopea! Have a paid account but using it on a different laptop right now - so sorry for the adblocker.

**Comment by photopea** [comment]
When the bug happens, do you see ads in Photopea?

If some software is modifying Photopea to remove ads, it could aslo break our code.

**Comment by NilsKrause** [comment]
Okay so... at home I tested with my own laptop (MacOS) also with Firefox 132.0.1 and it worked fine.

Yes I did see Ads, yesterday and now that I tested logged out in incognito mode.
Super weird.

**Comment by photopea** [comment]
I think the thing which has a full control over what you see (can read and rewrite the content of every website that you visit) is removing ads from Photopea and also, it is breaking Photopea. It could be a browser extension or something else. Could you figure it out?

As I understand, the problem happens only when there are no ads displayed in Photopea in your case.

**Comment by NilsKrause** [comment]
No, I tested yesterday with all extensions disabled (today as well). If Firefox is to be trusted, then nothing is modified - ads are displayed:
![grafik](https://github.com/user-attachments/assets/226d9dbc-e304-428b-a07d-e05ea1f5f7d4)

Is there any way I can dig deeper on this from my side?

**Comment by photopea** [comment]
Before you apply the free transform, can you save your work as a PSD and reopen it, and use the free transform, does it still happen? If yes, could you share your PSD with us?

**Comment by NilsKrause** [comment]
Yes it I can reproduce it after I opened it from a psd. Uploaded as zip, as github does not allow psd files.
[crash.zip](https://github.com/user-attachments/files/17716021/crash.zip)

Maybe also interesting. The GUI of Photopea is useable, but I cannot interact with the canvas. When I create a new project, it does not display a new canvas after the error happend.

![grafik](https://github.com/user-attachments/assets/2395a85a-4ea4-4d75-88a5-73fcec2e90ca)

**Comment by photopea** [comment]
I opened www.photopea.com in the latest Firefox 132.0.1. I opened your PSD file in it and applied the free trasnform. When I drag the bottom right corner, everything works fine.

What should I do to see an error? What do you do differently?

**Comment by NilsKrause** [comment]
Ohhh, so very interesting! The fact that you said bottom right corner made me try it again with the bottom right corner - and it seemed to work all of the sudden now. 

Except when I moved dragged towards the center of the object (make it smaller) it then crashed. I always started dragging from the top right to the bottom right corner so I got the error immediately. 

So it seems to only happen when dragging towards the center of the object. Confirmed it with all four corners.

**Comment by photopea** [comment]
I am trying to drag all corners to and from the center, but there are no errors :( 

Could you please tell me what version of Firefox do you use?

**Comment by NilsKrause** [comment]
I am running version 132.0.1 - I did a complete refresh of my Firefox installation because I was paranoid that something in my settings could cause it. But the error remains.

I will try to reproduce it with my private laptop, this one is in an organization. If I fail to reproduce it with another laptop, I will blame the organization settings.

**Comment by photopea** [comment]
I have to close it, because nobody is replying :(

**Comment by NilsKrause** [comment]
Yeah sorry, I overestimated the time I had to follow up on it. Haven't gotten around to it, I'll reply once I have some more data.
