### ISSUE TITLE
не открывается фотопея

### ISSUE THREAD

**Issue by lzvprva** [photopea/photopea#7311]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
What web browser do you use? What is your operating system?

**Comment by lzvprva** [comment]
> Какой веб-браузер вы используете? Какая у вас операционная система?

windows 10.  yandex 
![Снимок экрана 2024-11-14 142152](https://github.com/user-attachments/assets/8525daf9-373b-462f-bdba-efbe1e615cc7)

**Comment by photopea** [comment]
Is it inside Figma?

**Comment by lzvprva** [comment]
> Это внутри Figma?

да, плагин фотопея

**Comment by photopea** [comment]
I think some internet providers in Russia are blocking Photopea. Ask your internet provider about it, or try the VPN.
