### ISSUE TITLE
Dezgo Processing Appears to be Down

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#7312]
Your Operating System: Windows 11
Your Web Browser: Microsoft Edge
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

Trying to perform a Remove Background process results in "An error occurred. We are trying to fix it" message. Trying to use the Magic Replace process just results in a static "Processing" message.

I have sent Discord messages to both Clem and Will at Dezgo asking them to look into the issue on their end - assuming you still work with Dezgo to provide this service. Of course, it's just after 9:30PM here in Ohio, so I suspect they won't actually see my messages for several more hours.

**Comment by photopea** [comment]
hey, thanks for reporting it to Dezgo! Yes, we still work with Dezgo. Do you know about any affordable alternative to Dezgo?

**Comment by camoody1** [comment]
New update. Will just responded to my message and he's looking into the issue now.

**Comment by photopea** [comment]
Oh, you are right, sorry for that :( Everything should work now.
