### ISSUE TITLE
It's keep "Processing"

### ISSUE THREAD

**Issue by ninhkiddindie** [photopea/photopea#7313]
Your Operating System: Windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Using Magic to Replace or Remove whatever
3. The "Processing" notify pop up and nothing happen
4. If I start over from step 2, there will be more "Processing" appear
5. Of course I have credit left
![bug1](https://github.com/user-attachments/assets/1881195e-a7b8-46cd-96b4-54eb25418649)
![bug2](https://github.com/user-attachments/assets/84e657ad-dc73-4bc3-9350-ca35aec4c1cd)

**Comment by photopea** [comment]
Sorry guys, it should be fixed now.

**Comment by ninhkiddindie** [comment]
It fixed. Thanks for your effort. 
But pls aware that it takes longer to finish the process.
