### ISSUE TITLE
не работает фотопея , не открывается

### ISSUE THREAD

**Issue by lzvprva** [photopea/photopea#7315]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Please, answer the questions above in your report.

**Comment by catsmeatman** [comment]
@photopea
in browser console

GET https://vecpea.com/style/all09.css net::ERR_TIMED_OUT
GET https://vecpea.com/code/ext/ext1731426166.js net::ERR_TIMED_OUT
GET https://vecpea.com/code/dbs/DBS1730388484.js net::ERR_TIMED_OUT
GET https://vecpea.com/code/pp/pp1731491123.js net::ERR_TIMED_OUT

**Comment by photopea** [comment]
vecpea.com is our CDN, which works on CloudFlare. Can you open www.cloudflare.com or www.vecpea.com ?

**Comment by catsmeatman** [comment]
http://www.cloudflare.com open normally
http://www.vecpea.com redirected to https://www.photopea.com

**Comment by catsmeatman** [comment]
I have 2 computes.
From first https://vecpea.com/code/ext/ext1731426166.js load is ok
From second https://vecpea.com/code/ext/ext1731426166.js file not loaded

**Comment by photopea** [comment]
What is a difference between your two computers? Do they have the same internet provider? Do you have any antivirus which can see everything that you open on the web?

**Comment by photopea** [comment]
Many people are reporting a problem here, dont know why: https://www.figma.com/community/plugin/1164118094004004837/photopea

**Comment by photopea** [comment]
So is Photopea blocked in Russia?

I am afraid I can not do anythng about it :(
