### ISSUE TITLE
Photopea Free Transform Bug

### ISSUE THREAD

**Issue by Amsogoofy** [photopea/photopea#7317]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open something
3. Use free transform and after click away
4. try to do it again and you cant see the transforms anymore

**Comment by Amsogoofy** [comment]
Your Operating System: Windows 11
Your Web Browser: Microsoft Edge
The problem happens in the Incognito Mode, too: i dont understand

**Comment by photopea** [comment]
are you using "uBlock Origin" or other browser extensions? Some browser extensions are known to break Photopea like this.

**Comment by mrrfyW** [comment]
I mentioned this in a separate issue (that I created) with video evidence: https://github.com/photopea/photopea/issues/7304

**Comment by photopea** [comment]
@Amsogoofy you did not mention what browser extensions you use. In 99% of cases, problems with Photopea happen because you allow your browser extension to do anything it wants to Photopea.

**Comment by photopea** [comment]
I have to close it, because nobody is replying :(
