### ISSUE TITLE
File not being saved properly

### ISSUE THREAD

**Issue by joydesign777** [photopea/photopea#7319]
Your Operating System: Win 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Make some heavy editing file sized more than 240MB with many layers
3. Do some changes, and save the file
4. Close the file
5. Open the file and do more changes, and save the file
6. Close the file
7. Open the file and the version is the one in point 3, not point 5.

This happens alot and randomly with my works for several weeks now. I got confused everytime.

Please kindly check thank you.

**Comment by photopea** [comment]
What is "save the file" in steps 3 and 5? Do you use File - Save as PSD, or File - Save?

Maybe you are closing Photopea while there is still a message "Saving ..." at the top. If you do it, your file will not be properly saved.

If the speed of your hard drive is 24 MB/s, and you are saving 240 MB, it will take 10 seconds. You should not close Photopea until the message "Saving ..." disappears.

**Comment by joydesign777** [comment]
> What is "save the file" in steps 3 and 5? Do you use File - Save as PSD, or File - Save?
> 
> Maybe you are closing Photopea while there is still a message "Saving ..." at the top. If you do it, your file will not be properly saved.
> 
> If the speed of your hard drive is 24 MB/s, and you are saving 240 MB, it will take 10 seconds. You should not close Photopea until the message "Saving ..." disappears.

I save as pdf

And I have confirmed that after I click "save" there was message saying "Saving...". 

And after the message disappears, the file still not properly safed. The asterisk mark is still there, and the file was actually not being saved at all

At some instance, the asterisk mark dissapear but the file was note saved. I know this because when I closed and open the file, the version was not the newest

And I also tried to save as my psd file for backups, and the backups file size was 0 byte

**Comment by photopea** [comment]
I still can not see the problem which you describe myself, no matter what I do.

Maybe I need your PSD, to be able to see what you see. Could you put it on Google Drive and show us a link?

**Comment by photopea** [comment]
I have to close it, because nobody is replying :(
