### ISSUE TITLE
Operations on mask, affect to layer, not to mask itself

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#732]
In Photoshop I can for example make noise effect on raster mask (or make any other filter on the mask, when the mask is selected). In Photopea it affect to the layer with mask not at the mask itself.

**Comment by MichalSZZ** [comment]
Another thing (its corresponding with this issue) - when user try to fill mask with paint bucket tool (by black color for example), mask isn't filling in proper way - pixels from the layer are analyzed (blocks of colors), not pixels in the mask.

**Comment by photopea** [comment]
I made Adjustments, Filters and Paint Bucket work correctly on masks (raster mask and smart filter mask).

**Comment by MichalSZZ** [comment]
Great news! Thank You. :beers:
