### ISSUE TITLE
Question: Library used for editing matadata

### ISSUE THREAD

**Issue by boustanihani** [photopea/photopea#7320]
First thank you for the great product :)

I would just like to know, if you are using any opensource library for editing the metadata of JPG files?

I use the following library to extract the metadata, but I couldn't find any good library that also supports editing the metadata directly inside the browser: https://github.com/mattiasw/ExifReader

For the server side I use this library: https://exiftool.org/

If you wrote custom code for editing metadata, would you consider publishing this part as an opensource project?

**Comment by photopea** [comment]
I made a library "UTIF.js", which can read TIFF / EXIF files: https://github.com/photopea/UTIF.js

For XMP, it is just an XML text, and you can parse it in a browser using the DOMParser class.

I would like people to use File - File Info in Photopea as a metatada editor :) Are there any features that you miss in File Info in Photopea?

**Comment by boustanihani** [comment]
Photopea File Info is great, but I'm also interested in scripting and automation :)

One small thing concerning "File Info", if I edit the metadata and click "Save", the metadata will be ignored. Only if I use "Export...", the metadata will be also exported. In Photoshop, clicking "Save" (Overwrite), will always attach any metadata changes..

**Comment by photopea** [comment]
I have fixed it for JPG and WEBP. Using File - Save (without setting any parameters) should always save with metadata now.

**Comment by boustanihani** [comment]
Thanks a lot.

**Comment by boustanihani** [comment]
Does Photopea also support exporting embeded XMP data?

**Comment by photopea** [comment]
Yes, if you export a file, all the metadata should be there in the XMP format.

**Comment by boustanihani** [comment]
> Yes, if you export a file, all the metadata should be there in the XMP format.

I just tested this, but the data was embeded as IPTC, not as XMP, here is a sample:

![Image](https://github.com/user-attachments/assets/4755a01c-8772-4437-bcd2-75e3f461cd1a)

**Comment by photopea** [comment]
When you export a JPG file in Photopea, and attach metadata, Photopea attaches metadata in IPTC, XMP and EXIF formats.

Please, describe the problem to me. What do you do in Photopea, what happens, what do you want to happen instead. Describe the specific steps, so that I can see exactly what happens in your case.

**Comment by boustanihani** [comment]
Sorry my mistake, the tool I was using was not able to read the XMP data, that's why I thought it was missing..

**Comment by photopea** [comment]
Can your tool read XMP from other files?

**Comment by boustanihani** [comment]
Yes, I don't know why it was not able to detect XMP data inside the JPEG file exported from Photopea.

I opened an issue about this yesterday: https://github.com/mattiasw/ExifReader/issues/485

**Comment by boustanihani** [comment]
> Can your tool read XMP from other files?
> […](#)

Please take a look at this comment: https://github.com/mattiasw/ExifReader/issues/485#issuecomment-2734697306

**Comment by photopea** [comment]
I have added a mention of the "photoshop" namespace. Could you export your JPG file from Photopea again and try to process it in your tool?

**Comment by boustanihani** [comment]
Yessssssss, it is working now, thanks :)

**Comment by photopea** [comment]
okay, perfect, thanks for your help! :)

**Comment by boustanihani** [comment]
Welcome :)
