### ISSUE TITLE
Please help :(

### ISSUE THREAD

**Issue by JotaTheArcadeDoc87** [photopea/photopea#7321]
Your Operating System: MacOS
Your Web Browser: FIREFOX
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open PXZ File with formatted and rotated text.
3. See that it didn't keep the rotation/placement of the text.
<img width="573" alt="Screenshot 2024-11-13 at 4 46 59 AM" src="https://github.com/user-attachments/assets/8d826868-c6a2-4da1-96fa-69ec0a50f385">

<img width="823" alt="Screenshot 2024-11-13 at 4 45 55 AM" src="https://github.com/user-attachments/assets/674b2acc-e5d8-4828-a6fc-cdf626444bde">

**Comment by photopea** [comment]
Could you share your PXZ file with us?

**Comment by JotaTheArcadeDoc87** [comment]
https://drive.google.com/file/d/1JQUmC2kkTofi5ws9W90fdLCwJpu2QHIx/view?usp=sharing
here it is

**Comment by photopea** [comment]
I have fixed it. Photopea detects the rotation of text layers. It also detects the Arial font inside your PXZ file.

However, it seems like the font inside your PXZ does not contain certain characters, such as a pentagram, etc.

**Comment by JotaTheArcadeDoc87** [comment]
oh ok, ty!! :D

**Comment by JotaTheArcadeDoc87** [comment]
Question, can you make special characters show up as well or is that out of your jurisdiction?

**Comment by photopea** [comment]
It seems like the Arial font does not contain these characters, so I am confused about how Pixlr does it, it probably uses some different font for them. Can you type these characters with Arial elsewhere, e.g. in MS Word?

**Comment by JotaTheArcadeDoc87** [comment]
Yeah, i can do it in google docs. whats goin on? :(

**Comment by photopea** [comment]
Please, show me what you do in google docs.

**Comment by JotaTheArcadeDoc87** [comment]
I just paste the special characters in the doc, but it doesn't work on photopea

**Comment by photopea** [comment]
Did you try to load the same font into Photopea as you use in Google Docs?
