### ISSUE TITLE
Photopea account username

### ISSUE THREAD

**Issue by ReimaginedHorizons** [photopea/photopea#7322]
This is not much of a bug, I just couldn't find a source of support here, I made a mistake of creating a Photopea account with my own full name and then also uploading a public template. Now when I google my full name, the template pops up, I'd wish to either remove the template completely or at least be able to change my Photopea username.

**Comment by photopea** [comment]
You can do both.

In Templates, click "Add Template" at the top. You can change the "Creator / Brand name" at the top, and press "Save".

Or, on your template, click "Edit" and then, turn off the "Make Public" switch.

**Comment by BoomLingReady** [comment]
> You can do both.
> 
> In Templates, click "Add Template" at the top. You can change the "Creator / Brand name" at the top, and press "Save".
> 
> Or, on your template, click "Edit" and then, turn off the "Make Public" switch.

i love how photopea responds to every single issue, thats awesome. even if photopea is a photoshop copy i dont give a crap this guy is awesome.

**Comment by photopea** [comment]
I will close it now.
