### ISSUE TITLE
Photos are halved editing and after saving

### ISSUE THREAD

**Issue by zanexus** [photopea/photopea#7323]
Your Operating System: Win 10
Your Web Browser: Edge
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open and Place
3. Scale
4. The right part of the canvas is halved and beyond to the right anything will load as nothing.

**Comment by photopea** [comment]
Did you try it in the Incognito mode?

**Comment by photopea** [comment]
I have to close it, because nobody is replying :(
