### ISSUE TITLE
importing templates freezes photopea

### ISSUE THREAD

**Issue by 0rb5** [photopea/photopea#7324]
Your Operating System: Asus Windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes
**This must be done to see the problem**
1. Go to www.photopea.com
2. Use the desktop version
3. Download template from motion array
4. Load file get's stuck in loading and freeze and eventually crashes. Some files work from that site some don't, sometimes the templates loads but it's super slow and freezes

**Comment by photopea** [comment]
what is a motion array? Could yu send us that "template file" to support@photopea.com, or show us a link to download it?

**Comment by photopea** [comment]
I have to close it, because nobody is replying :(

**Comment by 0rb5** [comment]
sorry I totally forgot about this
