### ISSUE TITLE
help (again)

### ISSUE THREAD

**Issue by JotaTheArcadeDoc87** [photopea/photopea#7326]
Your Operating System: MacOS
Your Web Browser: FIREFOX
The problem happens in the Incognito Mode, too:

This must be done to see the problem

    Go to [www.photopea.com](http://www.photopea.com/)
    Open THIS file in particular (https://drive.google.com/file/d/1nWBvnOB_pEhZB69L8anvpUTON4FttOpS/view?usp=sharing)
    See that it causes an error

**Comment by JotaTheArcadeDoc87** [comment]
what font could i use to replace it?

**Comment by photopea** [comment]
Maybe try DejaVu Sans.
