### ISSUE TITLE
фотопея не работает что с ней ?

### ISSUE THREAD

**Issue by lzvprva** [photopea/photopea#7327]
Your Operating System: windows 10
Your Web Browser: Yandex
The problem happens in the Incognito Mode, too: noy

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....
![Снимок экрана 2024-11-14 142152](https://github.com/user-attachments/assets/529edf93-7834-4da0-a7fd-b42d23f78395)

**Comment by photopea** [comment]
Is it www.photopea.com?

**Comment by photopea** [comment]
We did not do anything :( It is probably caused by your browser or your internet provider.
