### ISSUE TITLE
After opening a PSD file I cannot close this file. 

### ISSUE THREAD

**Issue by area189** [photopea/photopea#7328]
https://github.com/user-attachments/assets/54a63e73-8e2c-4a20-b6b6-53cbdfbd42e2
I've already tested it on several browsers, for example Brave, FireFox and Opera, (and also on two different machines), currently using Fedora 41.

**Comment by photopea** [comment]
Could you share your whole screen? Did you try it in the Incognito mode?

Could you start a video by opening www.photopea.com in the incognito mode, so that it is more clear what you did before the problem?

**Comment by area189** [comment]
It seems to be back to normal, I ran new tests. No, browser being used normally (it was not an anonymous tab).

**Comment by photopea** [comment]
ok
