### ISSUE TITLE
File saving doesn't works 

### ISSUE THREAD

**Issue by Snufkinn** [photopea/photopea#7329]
After saving (ctrl+s) I see the message about Premium version and toast "File saved". Usually after this plugin gonna be closed but it not and changes doesn't saved

**Comment by photopea** [comment]
What plugin are you talking about? What should I do to see an error which you describe?

**Comment by Snufkinn** [comment]
**"PSD-like layer style"** for Figma. But now I check and it works correctly. I don't know what the reason was

**Comment by photopea** [comment]
ok.
