### ISSUE TITLE
Exported SVG Opens blank in Illustrator

### ISSUE THREAD

**Issue by iamjessica330** [photopea/photopea#7331]
Your Operating System: windows 11
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. imported a psd file
3. exported as svg file
4. opens fine in browser but opens blank in illustrator(can't use it for my printing purpose)

**Comment by photopea** [comment]
Could you show me your PSD file?

**Comment by photopea** [comment]
Could you show me your PSD file?

I think it might be a bug in Adobe Illustrator. Did you try to convert your PSD to SVG using different tools, and open that SVG in Illustrator?

**Comment by iamjessica330** [comment]
I can't attach psd but here is the svg. I tried opening the file with AI and Inkscape and both showed blank.

**Comment by photopea** [comment]
Where is the svg?

Can you create the SVG with a similar content without Photopea? Would it work in Illustrator or Inkscape?

**Comment by iamjessica330** [comment]
Take this attached as example. It also opens blank in illustrator.
![Drivien Tech Final-svg](https://github.com/user-attachments/assets/8ff39b33-6bba-47d7-b689-25f3889c9925)

and if I convert this with AI it'll open just fine but for some reason the Photopea quality is way better but it's sad I can't use it.

**Comment by photopea** [comment]
I think it is a problem in Adobe Illustrator - it can not open all SVG files. You can report it to Adobe.

Did you try to export it as a PDF from Photopea? PDF support in Illustrator should be better than the SVG support in Illustrator.

**Comment by photopea** [comment]
I am closing it, since it is a bug in Adobe Illustrator.

If any other tool can convert your PSD to an SVG which works in Illustrator, let us know.
