### ISSUE TITLE
certian glyphs not showing up.

### ISSUE THREAD

**Issue by JotaTheArcadeDoc87** [photopea/photopea#7332]
Your Operating System: MacOS
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too: Ywa

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open any file with special characters (including combining characters)
3. They're all blank squares
4. I don't know what to do to fix them

**Comment by photopea** [comment]
What is a file with special characters? is it a JPG file?

**Comment by photopea** [comment]
I have to close it, because nobody is replying :(

**Comment by JotaTheArcadeDoc87** [comment]
> What is a file with special characters? is it a JPG file?


SORRY I DIDNT GET TO THIS UHH

IT's a PXZ file

**Comment by photopea** [comment]
You must load a font which supports these glyphs into Photopea.
