### ISSUE TITLE
RESIZING ON TRANSFORM DOES NOT WORK

### ISSUE THREAD

**Issue by jambaaaa** [photopea/photopea#7333]
Your Operating System: WINDOWS
Your Web Browser: CHROME
The problem happens in the Incognito Mode, too: YES

**This must be done to see the problem**
1. Go to www.photopea.com
2. create new file
3. import picture
4. resize using transform, if works, wait for a while and it will not work again

**Comment by photopea** [comment]
Did you try these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment]
I have to close it, because nobody is replying :(
