### ISSUE TITLE
okay button on blending option drop shadow not working

### ISSUE THREAD

**Issue by saroiufhqeipurfgh** [photopea/photopea#7334]
Your Operating System: windows
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: have not tested, im on the app not the browser

**This must be done to see the problem**
1. Go to www.photopea.com
2. type a text
3. go into blending options
4. open drop shadow and then change the color

**Comment by photopea** [comment]
Please, test it in a web browser with no browser extensions running. It can be caused by your browser extensions. Your browser extensions are running in the "app", too.

**Comment by photopea** [comment]
I have to close it, because nobody is replying :(
