### ISSUE TITLE
Broken interface

### ISSUE THREAD

**Issue by dimaplay800** [photopea/photopea#7336]
Your Operating System: windows 10
Your Web Browser: Google chrome
The problem happens in the Incognito Mode, too: no

1. Go to www.photopea.com

![image](https://github.com/user-attachments/assets/6f1ef4ad-83f4-42f6-b849-c7ba68037529)

**Comment by photopea** [comment]
Are you in Russia? I have heard that some internet providers in Russia block access to our website.

**Comment by photopea** [comment]
Could you try opening https://www.photopea.com/index_nocdn.html ?

**Comment by ManHunttt** [comment]
Yes, your website is blocked in Russia because of a Cloudflare issue with TLS1.3 ECH and rkn.
If you just disable ECH or turn TLS 1.3 off, it's gonna be working again.
More info: https://community.cloudflare.com/t/cannot-access-sites-from-russia/733159

**Comment by photopea** [comment]
I have disalbed TLS 1.3 in my Cloudflare, could you check if it works now?

**Comment by ManHunttt** [comment]
It works perfectly fine now.
Thank you!

**Comment by photopea** [comment]
Okay, thanks! BTW. do you know why is "ECH in TLS 1.3" working in the whole world except of Russia?

**Comment by ManHunttt** [comment]
Sure, that's because Russian censorship machine (rkn) blocked the domain name cloudflare-ech.com (it's crucial for the ECH performance).
