### ISSUE TITLE
Can't access raster, vector and filter masks properties 

### ISSUE THREAD

**Issue by Smirow** [photopea/photopea#7341]
Hi!

It seems that layer masks are not accessible via script (layerMaskDensity/layerMaskFeather and same thing for vector and filter masks).

And also this script doesn't work: 
```js

function hasLayerMask () {
  var ref = new ActionReference();
  ref.putEnumerated(charIDToTypeID("Lyr "), charIDToTypeID("Ordn"), charIDToTypeID("Trgt"));
  var desc = executeActionGet(ref);
  return desc.hasKey(charIDToTypeID("UsrM"));
}
```
Neither this script to enable mask
```js
var idset = stringIDToTypeID( "set" );
var desc245 = new ActionDescriptor();
var idnull = stringIDToTypeID( "null" );
var ref4 = new ActionReference();
var idlayer = stringIDToTypeID( "layer" );
var idordinal = stringIDToTypeID( "ordinal" );
var idtargetEnum = stringIDToTypeID( "targetEnum" );
ref4.putEnumerated( idlayer, idordinal, idtargetEnum );
desc245.putReference( idnull, ref4 );
var idto = stringIDToTypeID( "to" );
var desc246 = new ActionDescriptor();
var iduserMaskEnabled = stringIDToTypeID( "userMaskEnabled" );
desc246.putBoolean( iduserMaskEnabled, true );
var idlayer = stringIDToTypeID( "layer" );
desc245.putObject( idto, idlayer, desc246 );
executeAction( idset, desc245, DialogModes.NO );
```

Your Operating System: Mac OS
Your Web Browser: Chrome 130
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Try to access activeDocument.activeLayer.layerMaskDensity via script
3. Try to enable/disable mask via script

**Comment by photopea** [comment]
It should be fixed now. Your scripts should work now. layerMaskDensity  and similar properties should work, too.

**Comment by photopea** [comment]
you can set it now, too :)
