### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by DaimySpapen** [photopea/photopea#7343]
Your Operating System: Windows 10
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Only on my main account

My problem is that if i try to login in any way, it says that my browser deleted cookies. This only happens when i do this on my main account and i have disabled all of my ad blocking extensions and i have tried to delete cookies but it still won't work. I also noticed that i don't get ads even without adblockers and i don't get the message saying that im blocking ads.
![Schermopname (99)](https://github.com/user-attachments/assets/ef869403-b32e-421d-89b8-2a0428321cdc)

**Comment by DaimySpapen** [comment]
I already disabled all my extensions but it doesn't change anything. I also tested it on my phone and it works on there with the same google account, i also have the latest version of chrome and have reinstalled it but it still doesn't work.

**Comment by photopea** [comment]
When Photopea says "Your browser deleted cookies. Try it again", could you click the "puzzle piece button" and take a screenshot to show us, if you really disabled all your extensions?

![VDzo5rg](https://github.com/user-attachments/assets/a49720a9-f219-4d1a-a7c0-ab2a440bb672)

**Comment by photopea** [comment]
But still, when Photopea says "Your browser deleted cookies. Try it again", could you click the "puzzle piece button" and take a screenshot to show us?  The button is right there.

![image (1)](https://github.com/user-attachments/assets/a70e16d5-9605-4efa-85ef-a3b460eb2a4d)

**Comment by DaimySpapen** [comment]
That screenshot was from earlier today before i disabled all of my extensions. I have completely disabled them all now and the puzzle piece is not there as you can see in this screenshot.
![Schermopname (101)](https://github.com/user-attachments/assets/840a1d59-6d1f-4903-bc94-3c8bdd1c9689)

**Comment by photopea** [comment]
Okay, I see.

You have an icon of a "crossed cylinder" near your blue arrow, do you know what it means?

Did you configure your chrome settings somehow to clear cookies?

**Comment by photopea** [comment]
Yes, if you want to log in at Photopea, but it needs to redirect to Google in between, and when you come back, it should still somehow remember that "it is you". We need to store it in your cookies.
