### ISSUE TITLE
The interface is weird

### ISSUE THREAD

**Issue by khxiri** [photopea/photopea#7344]
Your Operating System: Windows 11
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com

Normal Mode
![image](https://github.com/user-attachments/assets/7ab603fe-1207-47ce-9daa-61e32f6bac94)

Incognito Mode
![image](https://github.com/user-attachments/assets/f75d9127-222d-4c41-9098-501171463012)

**Comment by photopea** [comment]
it seems like you are deleting our advertisement, which should be on the right side. Please, use Photopea with advertisement. We would not exist if everyone deleted our ads. We would never make any money.
