### ISSUE TITLE
Fallo Al Editar Fotos

### ISSUE THREAD

**Issue by Vertico14** [photopea/photopea#7346]
Your Operating System: WINDOWS 11
Your Web Browser: GOOGLE CRHOME
The problem happens in the Incognito Mode, too: NO

**This must be done to see the problem**
1. Go to www.photopea.com
Al editar las fotos, me desajusta las demas capas y les deja un efecto no deseado
![Proyecto nuevo - 2024-11-19T105549 494 (1)](https://github.com/user-attachments/assets/27cb9d9b-c275-44da-9bf5-1b6f25584b6b)

**Comment by photopea** [comment]
I must see it happen myself. I think I will need your file and you should tell me what you do with it.

**Comment by Vertico14** [comment]
PHOTOPEA ERROR.mp4
<https://drive.google.com/file/d/1r_BrBYd8dJwOLQHIaWqBRZgFDLZ3A0of/view?usp=drive_web>

**Comment by photopea** [comment]
I dont have access to your video. Could you send it over the email to support@photopea.com

**Comment by photopea** [comment]
I also need your PSD file to see the problem myself on my own computer.

**Comment by photopea** [comment]
Thanks for your report, it should be fixed now.
