### ISSUE TITLE
Save error

### ISSUE THREAD

**Issue by swk9eny2** [photopea/photopea#7348]
After editing the image and pressing "Save", the image will lose all information and only the background color will remain.

Your Operating System: windows 11
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
Go to www.photopea.com
1. open "test_1"
2. Draw a red tick
3. ctrl + S save
4. The file becomes only the background color(like "test_error_2")

image for testing :
https://drive.google.com/drive/folders/1nw38AwSjt6TN9O3BLD-vseQ7hP_16sCk?usp=sharing

**Comment by photopea** [comment]
I am sorry guys, it should be fixed now.
