### ISSUE TITLE
Everything's disppearing

### ISSUE THREAD

**Issue by botherer** [photopea/photopea#7349]
Your Operating System: Windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Select New Project
3. None of the preview images are there
4. After I started a second image tab, the first one vanished, and all the menu buttons stopped working

As above, a lot seems to be breaking right now. I just lost an image I'd created, and many of the app's buttons and menus seem to be broken. I've tried stopping my VPN, running in incognito, etc, and the problems remain the same.

Thanks.
![00pea](https://github.com/user-attachments/assets/da0c3799-5a36-4332-ab0d-6ceeb43d5cfd)

**Comment by photopea** [comment]
I think I have fixed it. Could you try it again?
