### ISSUE TITLE
Little + and - next to crosshair cursor in selection tools

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#735]
That could help to identificate active selection mode (unite, subtract etc.), when user use shortcuts (ctrl, shift, ctrl + shift).

Photoshop show those function (when user use alt, ctrl or ctrl + shift) switching additionaly, by the active icon for unite, subtract or intersect. 

Don't look at the giant circle - it show only when I use left mouse button :)
![plus-i-minus](https://user-images.githubusercontent.com/38118273/41008787-47cfd358-692d-11e8-8eed-6cf772486d84.gif)

**Comment by photopea** [comment]
We need Firefox to implement image-set , before we add custom cursors. 

Please write them here: https://bugzilla.mozilla.org/show_bug.cgi?id=1107646

**Comment by MichalSZZ** [comment]
@photopea what do you think about showing active option by the icon change (see gif above). Afer use ctrl, shift, ctrl+shift, icon  for unite, subtract and intersect is highlighted.

**Comment by photopea** [comment]
It used to work like that in the past (buttons switched after pressing Shift / Alt), but I think it is clear even without it.

**Comment by photopea** [comment]
I don't think moving a DOM element as a cursor is a good solution, since it has a several frame delay in most of the browsers, and it does not move at all, when a website is stuck on computing.

**Comment by MichalSZZ** [comment]
Ok, I understand your way of thinking. I wrote that because I really miss for that functionality in Photopea. Me - user who have many years of experience ;) But I look on it teacher eyes too. It is simplier, when begginers can see what some keyboard combination can do (cursor or **icon change** - or both) before making an operation.

Yesterday I tried to post a message on Bugzilla with request, but I failed on create an acount (password with 12 chars and very strange restrictions). And I give up - sorry.

What is the problem with SVGs as a cursor in FF? They are blurred too? Or the size of cursor is twice as big as it shloud to be? Do you have any working example? Any link? I have retina display and want to see what is wrong.

Maybe there is an option, to use image-set on every browsers that support it, and alternative CSS declaration only for FF? I remember the times when there was very popular hacks in CSS on old IE (5.5 and 6). That is not so pretty solution, but sometime you must to choose between clean code and good user feelings.

**Comment by photopea** [comment]
Hi, yes, SVGs are blurred too. Firefox just rasterizes SVGs to PNGs and then works with them in the same way.

Here is a demo. The problem happens in Firefox only for devices with devicePixelRatio>1 : https://github.com/w3c/csswg-drafts/issues/2480
