### ISSUE TITLE
NEW PROJECT

### ISSUE THREAD

**Issue by Tanzbananz** [photopea/photopea#7350]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: blocked by admin.

**This must be done to see the problem**
1. Go to www.photopea.com
2. .... CLICK NEW PROJECT
3. .... Everything on the screen is blank.
4. .... Cannot see options.
![Screenshot (38)](https://github.com/user-attachments/assets/95540983-0ae6-43d0-8494-75f1b1b878ca)

**Comment by photopea** [comment]
I think I have fixed it. Could you try it again?
