### ISSUE TITLE
I cannot save the image in stories format. What is happening? I need this to my job urgently!

### ISSUE THREAD

**Issue by IbraDiniz** [photopea/photopea#7351]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
I think I have fixed it. Could you try it again?

**Comment by ssmathivanan402** [comment]
Yes try any other browser
