### ISSUE TITLE
[Bug] Deleting a custom shape left the shape indicators visible and makes them always get selected with any "free transform" option.

### ISSUE THREAD

**Issue by corruptedhelios** [photopea/photopea#7354]
Your Operating System: Windows 11
Your Web Browser: Firefox 132.0.2 (64-bit)

Steps to reproduce:
Haven't reproduced my steps again, but these were my actions:
1. Create a custom shape (was with the shield icon)
2. Duplicated that shape a few times
3. Deleted one of the duplicated versions

Description:
Deleting a custom shape left the shape indicators visible. These occupy no layer (cant be turned off) and get ALWAYS selected when performing a free transform action, no matter which layer or what kind of selection I'm using. This gets really annoying because for other shapes, they get transformed alongside this "broken" shape. But on rasterized layers, the broken shape gets selected instead of my drawn elements (see attached gif). I can circumvent this by shift selecting an existing shape layer and my rasterized layer. 
In that case both these layers and the broken shape get transformed.

Workaround:
Saving as a .psd and exporting->reimporting only partially fixes the issue. The broken shape isn't active anymore, but the moment I use any shape layer it is there again.
I solved the issue by copying ALL layers into a new file. This gets rid of the broken shape as its apparently not tied to a layer.

Files:
![PhotopeaShapesBug](https://github.com/user-attachments/assets/fad2c3e3-9444-494e-8284-12e7ea6d84a4)

[BrokenShapePSD.zip](https://github.com/user-attachments/files/17829179/BrokenShapePSD.zip)

**Comment by photopea** [comment]
I think you have created a Path (not a layer). Just delete this path in Window - Paths.

You can learn more here: https://www.photopea.com/learn/vector-graphics
