### ISSUE TITLE
[BUG] A FERRAMENTA DE MODELOS ESTÁ INATIVA 

### ISSUE THREAD

**Issue by JorgeLuizEdward** [photopea/photopea#7355]
Your Operating System: MacOS Sonoma
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Sim

![Captura de Tela 2024-11-20 às 15 23 22](https://github.com/user-attachments/assets/f87700f6-0cc3-4331-96fb-afe593d230f1)

 Fiz alteração de navegador e até mesmo de conta, mas o bug persiste

**Comment by photopea** [comment]
Sorry, it should be fixed now.
