### ISSUE TITLE
Text drift on some files

### ISSUE THREAD

**Issue by Smirow** [photopea/photopea#7356]
Sometimes on specific files the text is drifted for some reasons. Forcing a redraw by resizing fixes it but can't manage to fix the issue using scripts.

https://github.com/user-attachments/assets/026be7a7-2ebd-4eb3-a697-e93d548db4bf

The file for testing: https://drive.google.com/file/d/1y3Rr4zooe3KqvEOJaAbU5igdbNo3Vbm1/view

Your Operating System: Mac
Your Web Browser: Chrome 130
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. .... Open the file
3. .... Try to modify TEXT 1

**Comment by Smirow** [comment]
So `boxBounds` of text can be corrupted sometimes it seems. Can we have a way to force update this using script like when rotation or changing dimension in the UI like the video?

**Comment by photopea** [comment]
I am confused. When I open your PSD in Photopea and enter the layer "TEST 1", everything seems to work fine.

Could you tell me some steps, what should I do to see the problem?

**Comment by Smirow** [comment]
I am confused myself. As soon as I save the file the problem is either resolved or gets worse.

Here worst after saving: https://drive.google.com/file/d/1CwvOtTGc3ioT4Ea1Y2gm7mh61uulgbfA/view?usp=sharing

**Comment by photopea** [comment]
Did you try to edit your PSD and save it back to your computer while using a web browser with no browser extensions?

I am trying to edit your PSD. The initial render seems wrong, but after re-rendering it, everything seems to work fine.

**Comment by Smirow** [comment]
Whenever I edit the text drifts. Sure I can move back the text wherever I want after that but how can I manage a similar issue by just using script?
What do you mean by re-rendering? Is there a way to force re-render using script?

**Comment by photopea** [comment]
I think that a PSD file that you sent me is damaged. It was amaged by browser extensions, which you are using.

If you see a bug in Photopea, could you please tell me, what should I do to see it myself? E.g. how to create such a PSD file, where the text layer "jumps away"?

**Comment by Smirow** [comment]
Sure, I will close the issue for now and open a new one if I can easily replicate the issue.

**Comment by photopea** [comment]
I still encourage you to try using Photopea without giving any of your browser extensions a full control over Photopea. E.g. in Chrome, you can see these extensions by clicking this button: https://i.imgur.com/VDzo5rg.png
