### ISSUE TITLE
Website is telling me I'm still blocking ads despite me turning off uBlock Origin

### ISSUE THREAD

**Issue by AJHavok20** [photopea/photopea#7357]
Your Operating System: Win10 Pro
Your Web Browser: Opera GX
The problem happens in the Incognito Mode, too:

I don't want to get banned, so I disabled uBlock Origin for Photopea (Also I want to support this amazing tool), but despite having done this, and since I installed uBlock Origin I have had Opera GX's native ad blocker disabled permanently. Yet the site is still saying detected ad blocker and still tells me to disable it or pay for 3 months ad free. I don't have an ad blocker active on photopea.

**Comment by photopea** [comment]
I think the uBlock Origin extension is lying to you. It says it is not blocking ads, but it is blocking ads. Did you try to turn it off completely (tell a browser to turn it off, instead of asking the extension to turn itself off?)

**Comment by AJHavok20** [comment]
> I think the uBlock Origin extension is lying to you. It says it is not blocking ads, but it is blocking ads. Did you try to turn it off completely (tell a browser to turn it off, instead of asking the extension to turn itself off?)

Just tried it again after disabling uBlock Origin in the browser itself and still the same issue. Not sure what the deal is. Unless Photopea has redirect and pop-ups (for my own protection I have all site settings to not allow redirects or pop-ups)

**Comment by photopea** [comment]
Did you try to turn off all your browser extensions?

**Comment by ncabelin** [comment]
I have not added any ad blockers ever in my Chrome, Macbook and just suddenly got this message also. I've been clicking ads in support before.

**Comment by photopea** [comment]
Did you try to turn off all your browser extensions? Not just those which you think could be blocking ads, but all extensions which have your permission to modify Photopea.

**Comment by PauGuillamon** [comment]
I am currently having the same issue with Firefox and Adblock Plus. I have ads disabled but photopea still says it's blocked :(. Even after fully disabling Adblock Plus in Firefox I get that message, and I do not have other extensions that might block ads.
<img width="1552" alt="Screenshot 2024-12-04 at 12 28 51" src="https://github.com/user-attachments/assets/58841881-a30f-42ce-a882-70634760ad20">

Please fix this so you can get your well deserved revenue through ads for this awesome app 😃

**Comment by photopea** [comment]
Did you look into the article under "Read this article"? There is a part about Firefox: https://www.photopea.com/tuts/photopea-says-i-am-blocking-ads-but-i-am-not/

Ads work fine in Firefox in my case :(

**Comment by CIDXZ** [comment]
Same here, I'm a new user and the sad face instantly wanted to me stop blocking ads but somehow ad blocking still gets detected even after turning off all my extensions

**Comment by photopea** [comment]
Please, make a proper report, while mentioning your web browser, operatng system, etc.
