### ISSUE TITLE
Site continuously crashes without saving progress

### ISSUE THREAD

**Issue by B-Hanna2212** [photopea/photopea#7362]
Your Operating System: photopea
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes.

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....Create new
3. ....Start editing or adding
4. ....will crash and reboot without saving progress

**Comment by photopea** [comment]
Whatever I do, I cannot make Photopea crash :(  Photopea might crash when you don't have enough RAM for the kind of work that you do. But I have 24 GB of RAM.

Could you describe steps, which always make Photopea crash? Or, as a proof, could you record a short video of opening www.photopea.com and what you do next to make Photopea crash?

**Comment by elinaru** [comment]
I'm having the same experience. It's pretty much unusable. And very frustrating. I was hoping to find something better than GIMP…

**Comment by photopea** [comment]
I have to close it, because the original person did not respond :(
