### ISSUE TITLE
WebGL no longer enabled in Chrome 131 (Linux)

### ISSUE THREAD

**Issue by jessepav** [photopea/photopea#7363]
Your Operating System: Linux
Your Web Browser: Chrome 131
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open *More* menu
3. *Enable WebGL* is grayed out

This happens on all my Linux machines (both with integrated Intel GPU drivers and Nvidia drivers) after the Chrome 131 update.

**Comment by photopea** [comment]
It is your task to provide a WebGL for Photopea, just as it is your task to provide the electricity for Photopea. We, as a website, can not "give you WebGL", just like we can not "give you the electricity" :(

Maybe look into "about://gpu", or try a different browser. Photopea can still run fine without WebGL, but it will be much slower.

**Comment by jessepav** [comment]
Hello,

WebGL (1 and 2) are working fine in the browser. Here is the output of `chrome://gpu`:

![chrome-gpu](https://github.com/user-attachments/assets/d269c178-dcb8-45a2-bb3f-e8639b107039)

The console doesn't seem to report anything awry:

```
(index):187             adding
pp1732313904.js:10807   Extra parameter Spcn
```

Photopea worked properly with WebGL until the Chrome 131 update. If there's anything I can do to help debug further, let me know.

**Comment by jessepav** [comment]
It turns out to be a bug in Chrome (with a workaround). In case someone reports an issue like this again, the solution (adapted from [this post](https://www.reddit.com/r/FoundryVTT/comments/o5wou1/comment/h2pg1n1/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)) is to

1. In Chrome, open up your settings
2. Scroll to the very bottom and click on the System group
3. Toggle the "Use graphics acceleration when available" to off
4. Relaunch Chrome
5. Repeat the previous steps to re-enable the graphics acceleration
