### ISSUE TITLE
Layer effects: Wrong signature

### ISSUE THREAD

**Issue by Smirow** [photopea/photopea#7365]
Hi,
When using layer effects I sometimes get a "Wrong signature" error and as a result the effects don't always display.
The file opens correctly in Photoshop, with all effects working.

File: https://drive.google.com/file/d/1P5gCBZ_T1_ds2Ul71romtB3lta3JdlSB/view?usp=sharing

Your Operating System: Mac OS
Your Web Browser: Chrome 131
The problem happens in the Incognito Mode, too: tried without extention 

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open the file
3. Get a wrong signature error and some effects are not showing

**Comment by photopea** [comment]
Hey! Was this file created in Photopea or in Photoshop? If it was created in Photopea, we should fix Photopea, so that it does not create such files.

**Comment by Smirow** [comment]
Hi, created using Photoshop.

**Comment by photopea** [comment]
ok thanks, it is fixed now.
