### ISSUE TITLE
Me being dumb

### ISSUE THREAD

**Issue by Bambi-Alt** [photopea/photopea#7366]
Hey, I was using the spot healing brush tool and was erasing some things but also added some black to the drawing, I'm not sure if this is a bug or something, or if its normal, I am new here! 😅

[Screen recording 2024-11-25 9.20.46 AM.webm](https://github.com/user-attachments/assets/0c2f0dac-393f-4d53-90a0-60c8135a5fc0)

**Comment by photopea** [comment]
This is how it should work. What do you mean by "erasing" and "adding"? You should use the Eraser tool to erase. To make the area black or white, you should use the Brush tool, not the Spot Healing Brush tool.

**Comment by Bambi-Alt** [comment]
Sorry i'm not very bright😅
