### ISSUE TITLE
Bug PNG Export via script

### ISSUE THREAD

**Issue by Smirow** [photopea/photopea#7373]
Hi,

When exporting to PNG using `activeDocument.saveAs(new File("test.png"), new PNGSaveOptions(), true)` or `activeDocument.exportDocument` the PNG file is only a gray bg.

Try using this link: https://www.photopea.com/#%7B%22files%22%3A%5B%22https%3A%2F%2Fwww.photopea.com%2Fapi%2Fimg2%2Fpug.png%22%5D%2C%22script%22%3A%22app.activeDocument.saveAs(new%20File('test.png')%2C%20new%20PNGSaveOptions()%2C%20true)%3B%22%7D

Using `activeDocument.saveToOE('png')` seems to work.

Your Operating System: Mac OSX
Your Web Browser: Chrome 131
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a file
3. Export via script: app.activeDocument.saveAs(new File('test.png'), new PNGSaveOptions(), true);
4. The file is grayed out

**Comment by photopea** [comment]
thanks, it is fixed now.

**Comment by Smirow** [comment]
Still happening. Tried after cleaning cache. Is it live?

**Comment by photopea** [comment]
sorry, now it should be fixed.
