### ISSUE TITLE
Channel Mixer

### ISSUE THREAD

**Issue by imms93** [photopea/photopea#738]
It would be nice to have also Channel Mixer to make almost all the psd colorings compatible with Photopea (there's also Color Lookup but I don't think it's an important feature to add). Here's a gif of the feature in GIMP:
![gif](https://user-images.githubusercontent.com/30982542/41056692-4d66ecb4-69c5-11e8-9c73-2a1800b65a19.gif)

**Comment by photopea** [comment]
It was added. Thanks for suggesting it! :)
