### ISSUE TITLE
Loading Local Fonts popup stays displayed

### ISSUE THREAD

**Issue by CateHazleden** [photopea/photopea#7384]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: no

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create text layer
3. Load local fonts -> popup displays
4. Local Fonts loaded and related banner popup displays and then hides
5. "Loading local fonts" popup remains

screenshot of the popup
screenshot of console error JS child/node issue

<img width="756" alt="image" src="https://github.com/user-attachments/assets/b24312ab-6bca-4ecc-9e6f-0da79f949fe1">

<img width="959" alt="image" src="https://github.com/user-attachments/assets/c207cda0-3b4b-40bc-b17e-5e5dedf650d9">

**Comment by photopea** [comment]
Did you try it in the incognito mode of your web browser? Your browser extensions could be causing it.

**Comment by CateHazleden** [comment]
Windows updates applied overnight seem to have resolved the problem.
Thanks
