### ISSUE TITLE
Got frozen when saving to PSD

### ISSUE THREAD

**Issue by feraio** [photopea/photopea#7385]
Your Operating System: MacBook M3 Pro
Your Web Browser: Arc (1.70.0)
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Spend some time in a not very large file
3. Try to save it

![image](https://github.com/user-attachments/assets/045df972-31f5-487c-9c7e-0d094eac23cc)

**Comment by photopea** [comment]
I can not reproduce it. Can you reproduce it?
