### ISSUE TITLE
When Using The Magnetic Lasso It Auto Anchors...

### ISSUE THREAD

**Issue by Incelations** [photopea/photopea#7386]
Your Operating System: Windows 10
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: YES (Edit)

**This must be done to see the problem**
1. https://www.photopea.com/

ISSUE: When I first started using the magnetic lasso, it worked perfectly fine when I was using it, I had full control over it which made things hella easier. But after a few days I try to trim out the edges of my character using the magnetic lasso and when I was just hovering over with the magnetic lasso it auto anchors (picture below) this causes it to be in that place where I didn't want it, ruins the full control over it instead of me just clicking where I want the anchor to be.

Edit: Please fix, I WANT TO TRIM MY CHARACTERS.

![anchor complaint](https://github.com/user-attachments/assets/0632a4e4-97d6-47c9-8bdc-a63fda2708c8)

**Comment by photopea** [comment]
The magnetic lasso is "magnetized" by the edges of your image. But there are no edges on the plain white image. What exactly do you expect when using the magnetic lasso on a plain white image?

You can delete the anchors by pressing the Delete key. You can learn how to use the magnetic lasso here: https://www.photopea.com/learn/creating-selections#:~:text=finish%20the%20selection.-,Magnetic%20Lasso,-Magnetic%20lasso%20is

**Comment by Incelations** [comment]
No it auto anchors on the edges of the image too, its the whole thing. And I don't know why it does that. And Manually deleting the anchor keys is just time-consuming, this didnt happen before so.

**Comment by Incelations** [comment]
![Capture](https://github.com/user-attachments/assets/5a2afcd0-a751-469b-b126-df65b7d922cf)

**Comment by photopea** [comment]
I need some proof. Could you record a video of where you move your mouse and where the anchors are placed?

Having your finger on the Delete key is a normal thing when using the Magnetic Lasso, I think everyone does that.

**Comment by Incelations** [comment]
Nevermind I'm slow. 😔 you can close it now

**Comment by photopea** [comment]
I am quite sure that our Magnetic lasso works very similar to a magnetic lasso in other programs.
