### ISSUE TITLE
Photopea app frozen when launched.

### ISSUE THREAD

**Issue by Brauhhhh** [photopea/photopea#7387]
Your Operating System: S23 Ultra
Your Web Browser: Arc Search ( using app )
The problem happens in the Incognito Mode, too: No but i use the app more.

**This must be done to see the problem**
1. Go to photopea app
2. Now frozen.

I use the app version of the website more because it's more convenient and faster. 
![Screenshot_20241204_184536_Chrome](https://github.com/user-attachments/assets/d12ad826-2440-442a-9f11-0c5910eb5d32)

**Comment by Brauhhhh** [comment]
Nvm photopea fixed itself but idk if it's gonna happen again

**Comment by photopea** [comment]
okay.
