### ISSUE TITLE
[Feature Request] Open TIF files with pages as Artboards

### ISSUE THREAD

**Issue by Nu11u5** [photopea/photopea#7388]
### Current behavior ###

Photopea supports opening PDF documents with pages as Artboards for each page.  This feature is not supported for TIF files with pages.

### Desired behavior ###

Support opening TIF files with pages as Artboards for each page.

**Comment by photopea** [comment]
Do you have a TIFF file for which it would be appropriate?

**Comment by Nu11u5** [comment]
> Do you have a TIFF file for which it would be appropriate?

Do you mean a sample file?  I can find or create one if so.

Multi-page TIFF files are a common format for certain document scanners.  It would be helpful to be able to view or edit them in a webapp since ChromeOS does not natively support TIFFs, and a webapp would need a library like your UTIF.

**Comment by photopea** [comment]
Have you tried to open your multi-page TIFF files in Adobe Photoshop or some other program? Do the pages look "like artboards"? If yes, could you send me your TIFF file as a proof, so that I can see it myself, what is happening?

I am a bit afraid to make Photopea work totally different than other software, and to make our users angry.

**Comment by Nu11u5** [comment]
If I open a multi-page tiff in Photopea or Gimp the pages load as layers.  I do not have Photoshop to test with.

Windows image previewer opens the file with an additional "page" toolbar for navigating pages.

The TIFF format has a specification for "pages", but I'm not sure if there is an additional specification for "layers".

Here is an example multi-page tiff file created by my cruddy printer-scanner:

[multi-page.tiff.zip](https://github.com/user-attachments/files/18246902/multi-page.tiff.zip)

**Comment by photopea** [comment]
Photopea opens your file the same way as Gimp (different images as layers on top of each other).

Adobe Photoshop sees just one image inside your file.

So I think Photopea should open multi-image TIFs as it opens them now, because that is what most of people expect.

**Comment by photopea** [comment]
I will keep the TIF processing as it works now, as this is how other programs do it and what our users expect.

We could add a button "layers to artboards", which would place every layer of a document into an artboard and arrange the artboards "nicely".
