### ISSUE TITLE
Gybe Asmz - Moving multiple selected layers

### ISSUE THREAD

**Issue by gybeasmz** [photopea/photopea#739]
I use photoshop a lot, so this is not my subjective feeling, but an objective clarification of a correct and desired behaviour of Photopea. Currently it´s very frustrating.

When I select more than one layer using shift. I can see them selected in the layer list, but they are not visualy selected on the canvas + when I start draging them, only the layer I hold with mouse is moving. I shouldn´t have to select them using ctrl shift T to move them - that should be needed only when I want to resize them, but not move them.

**Comment by photopea** [comment]
You are right! It was fixed. Thank you :)
