### ISSUE TITLE
How to get the file object in the displace operation

### ISSUE THREAD

**Issue by maoduomianzida** [photopea/photopea#7390]
```  javascript
// 应用置换滤镜到当前活动图层
function applyDisplace(horizontalScale, verticalScale, displacementMapPath) {
  var idDisplace = stringIDToTypeID("displace");
  var desc = new ActionDescriptor();
  
  // 设置水平和垂直缩放比例
  desc.putInteger(charIDToTypeID("Hrzn"), horizontalScale); // 水平缩放
  desc.putInteger(charIDToTypeID("Vrtc"), verticalScale);   // 垂直缩放
  
  // 设置置换图的文件路径
  
  desc.putPath(charIDToTypeID("Dslc"), new File(displacementMapPath));
  
  // 设置选项：拉伸适配和重复边缘像素
  desc.putEnumerated(charIDToTypeID("Dmnc"), charIDToTypeID("Dmnc"), charIDToTypeID("Stre")); // 拉伸适配
  desc.putEnumerated(charIDToTypeID("Dstl"), charIDToTypeID("Dstl"), charIDToTypeID("Rpeat")); // 重复边缘像素
  
  // 执行置换滤镜
  executeAction(idDisplace, desc, DialogModes.NO);
}

// 示例：应用置换滤镜
applyDisplace(10, 10, "/path/to/displacement_map.psd"); 
``` 
The above code is for displace operation, but it requires a file object. The corresponding psd file can be selected on the UI interface, but how do I get and call it using code?
![image](https://github.com/user-attachments/assets/a61c5269-bd65-4706-ae05-7f51eda83525)
You can see that there is a PSD file corresponding to the smark object on the UI interface that can be selected, but how can I write it through code?

**Comment by photopea** [comment]
I am afraid I can not make this code work in Photopea, because it loads a PSD file from a hard drive, and Photopea as a website can not access your hard drive.
