### ISSUE TITLE
Paid for the yearly subscription but ads won't go away

### ISSUE THREAD

**Issue by ClarinaB** [photopea/photopea#7391]
Your Operating System: Mac Sonoma 14.6.1
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. .... I signed in and the ads are still visible
3. ....
4. ....

**Comment by photopea** [comment]
Hi, did you log in? You must log in to be able to use your Premium account.

Also, you need to log in with the same account (same email address) as the one you used when you paid for Premium.

**Comment by ClarinaB** [comment]
Of course I logged in. It even says my name when I click on account. see screen shot.


<img width="1700" alt="Screenshot 2024-12-07 at 2 06 30 PM" src="https://github.com/user-attachments/assets/40576592-f539-45ac-8ddf-4ee2d94b7619">

**Comment by ClarinaB** [comment]
Ive been using photopea for a few months now and have been EXTREMELY hapy with it. Then I needed to turn off my computer and so I got logged out. I did the steps with the e-mail log in and I am logged in but the adds don't go away.

**Comment by photopea** [comment]
Your screenshot says that your email address is clarina@clarinabezzola.com

I can see a Premium user with an email address clarinabezzola@gmail.com, who paid for a 365 days Premium account about 90 days ago. If it is you, log out and log in under that email address.

Photopea sees each email address as a different person, with a separate account, separate settings, separate Peadrives, etc.

**Comment by ClarinaB** [comment]
Wow!! You are right!! Thank you so much!!!!

**Comment by ClarinaB** [comment]
That was great help! Thank you!!!

**Comment by photopea** [comment]
No problem! If you want, I can move your Premium to a different email address, just let me know :)

It is all described here: https://www.photopea.com/tuts/premium-account-does-not-work/
