### ISSUE TITLE
Brushes are frozen after import  

### ISSUE THREAD

**Issue by elinaru** [photopea/photopea#7392]
Your Operating System: macOS Ventura v.13.7.1 
Your Web Browser: Chrome Version 131.0.6778.109 (Official Build) (x86_64)
The problem happens in the Incognito Mode, too: unknown 

**This must be done to see the problem**
1. Go to www.photopea.com
2. File > Open > Select all 6 brush .ABR files (about 85MB in total) 
3. Select "Open"
4. Open brushes palette in app 
5. Palette is frozen; no brushes can be selected

**Comment by elinaru** [comment]
Hi there, Thanks for replying. Unfortunately, I did not keep the ABR files. However, I know I downloaded them from this site: https://www.brusheezy.com/free/christmas , if that helps at all.

**Comment by photopea** [comment]
Can you make the problem happen again? If yes, what brushes do you use?

**Comment by photopea** [comment]
I have to close it because nobody is responding :(
