### ISSUE TITLE
Snap to grid not working

### ISSUE THREAD

**Issue by kevin-jones** [photopea/photopea#7393]
Your Operating System: Mac
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Show grid
3. Set snap settings to only grid
4. Use the Pen tool or any other tool...the points do not snap to the grid

Am I doing something wrong here? I expect when placing a point with the Pen tool that with the above settings it will be impossible to place a point anywhere other than directly on the grid, but Photopea is letting me place points anywhere and even when moving them manually they don't snap.

**Comment by kevin-jones** [comment]
If I set the Prefernces > Grid Gap X / Y to 1px then it works as expected, just not at any larger grid sizes

**Comment by photopea** [comment]
Snapping to grid means, that if your cursor is 5 px or less from the grid line, it will "snap" (the vertical, horizontal or both coordinates) to the line location. I just tried it with the pen tool and it does work like this.
