### ISSUE TITLE
LOADING IS IN THE SCREEN ALL THE TIME

### ISSUE THREAD

**Issue by Gyanabh** [photopea/photopea#7394]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
Did you try it in the Incognito mode? You should have written it down in your issue report.

**Comment by photopea** [comment]
I have to close it because nobody is responding :(
