### ISSUE TITLE
Provide a way to preview files (via code)?

### ISSUE THREAD

**Issue by KamilDev** [photopea/photopea#7396]
Users have requested `.indd` file preview support in QuickLook (https://github.com/QL-Win/QuickLook/issues/346). During my research, I noticed that Photopea can preview `.indd` files.  

Would it be possible to provide a way to preview a file via code? For example, we could use a WebView (browser) and pass file data to Photopea using one of the following approaches:  

1. **URL Parameters**: `/preview?file=...`  
2. **JavaScript Messaging**:  
```javascript
// Photopea:
window.addEventListener("message", function (event) {
  if (event.type === "preview") {
    // Handle file data and show preview
  }
});

// QuickLook:
window.parent.postMessage(
  {
    type: "preview",
    fileName: "...",
    fileData: ...,
  },
  "*"
);
``` 

3. **We can directly run a JavaScript function that Photopea defines on the webpage.**

Additionally, is there any way to run Photopea locally (saving/caching files) to allow the user to preview files while offline?

**Comment by photopea** [comment]
Hi, you can already send Photopea your binary file using our API: https://www.photopea.com/api/live

**Comment by KamilDev** [comment]
Is it possible to set Photopea to read-only mode, so that the document can't be edited, only able to zoom/pan?

**Comment by photopea** [comment]
You can disable mouse mouse events of the <iframe> using CSS.

Or activate the move tool in a toolbar by running some script.
