### ISSUE TITLE
Imported Photoshop file is missing layers 

### ISSUE THREAD

**Issue by endresol** [photopea/photopea#7397]
Your Operating System: MacOS
Your Web Browser: Chrome or "installed chrome"

I have a psd file made in photoshop and when I import it, some layers are missing.
I discovered this when I exported all the layers as individual files. 
Not sure how to reproduce this error as I do not have access to photoshop personally. Sorry.

**Comment by endresol** [comment]
Sorry, It turned out not to be an error, but layer names with a /
I closed this issue, but a feature request would be that the export layers could keep the folder structure of the file.

**Comment by photopea** [comment]
A PSD file (layers etc) should look the same in all PSD editors. If they look differently in Photopea, it is definitely a bug. Please, tell us more about this bug.

**Comment by endresol** [comment]
The layers where there, but when I ran the Export Layers... function, layers with a / in the filenames where placed in folders. The part before the / as the folder name and the rest as the file name.
Black/White layer name became a folder named Back and inside there a file called White.png

**Comment by photopea** [comment]
I have fixed it - Photopea will replace slashes in file names with dashes.

**Comment by endresol** [comment]
Wow, nice. Thanks
