### ISSUE TITLE
Inverse Select is working as Deselect

### ISSUE THREAD

**Issue by Ak10990** [photopea/photopea#7399]
*** **Functionality not working as expected** ***

Your Operating System: Mac [Version 14.6.1]
Your Web Browser: Chrome [Version 131.0.6778.86 (Official Build) (arm64)]
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Select pixels of any layer
3. Go to Select Menu
4. Click on Inverse [All other inverse as well]

**Comment by photopea** [comment]
I tried to do your steps, but I can not see any strange behaviour. What do you mean by step 2 - Select Pixels of any layer?

**Comment by Ak10990** [comment]
The issue seems to be fixed now. I am no longer able to reproduce it. Thanks for the quick help.
