### ISSUE TITLE
Ads Still Showing in Premium

### ISSUE THREAD

**Issue by fsalvat0** [photopea/photopea#7400]
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Ads are still showing in premium subscription mode. This has never happened before.
2. ![image](https://github.com/user-attachments/assets/5d8b66e4-2bd4-4e84-b26a-6441e33bd8e9)

**Comment by photopea** [comment]
I have to close it, because the person is not responding :(
