### ISSUE TITLE
rename layers

### ISSUE THREAD

**Issue by harry-prog** [photopea/photopea#7403]
Your Operating System: windows 10 y windows 11
Your Web Browser: crhome 
The problem happens in the Incognito Mode, too: no 

cuando intento renombrar una capa con el photopea de premium no me permite hacerlo, mientras que en la versión gratutita si

**Comment by photopea** [comment]
Did you try to disable all your browser extensions?

**Comment by harry-prog** [comment]
desactive todas las extensiones y no funcionó, pero tu pregunta me hizo pensar que quiza desactivando la traducción funcionaria, así fue. Mil gracias, dejo aquí un video por si puede ser de ultilidad para alguien más. 

https://github.com/user-attachments/assets/12bf4561-3e0d-4

**Comment by photopea** [comment]
To change the language of Photopea, press More - Language - choose the language.

**Comment by harry-prog** [comment]
Okey, thanks for everything. ❤️

**Comment by harry-prog** [comment]
Problem solved
