### ISSUE TITLE
the Layer option in the photopea has dissapeared and the arrow key is behaving indirectly 

### ISSUE THREAD

**Issue by MaazTX** [photopea/photopea#7405]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
You should answer the questions in our questionary.

**Comment by Aisha969** [comment]
layer option not showing while creating mockup
