### ISSUE TITLE
Images becoming blurry when adjusting size

### ISSUE THREAD

**Issue by mduensing2000** [photopea/photopea#7406]
Your Operating System: Mac
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open from Computer --> select "photopea example 1" png file
3. Select File --> Open & Place --> select "photopea example 2" png file
4. When I try to adjust the size of "photopea example 2" image, the image becomes blurry. This is a new issue and has not happened before. I tried uploading jpg versions as well and had the same issue. Screenshot of the blurry result in "photopea example 3"
![photopea example 1](https://github.com/user-attachments/assets/cbff9ccf-f035-4777-93e1-c0eccbf2e299)
![photopea example 2](https://github.com/user-attachments/assets/94dcf7e0-9170-4fec-ac09-1cd3c1c27fc3)
<img width="2560" alt="photopea example 3" src="https://github.com/user-attachments/assets/8ebbdcaa-dd89-4447-b56a-d65226c8ce7d" />

**Comment by photopea** [comment]
When using the Free Transform tool, what you see is just a "fast preview" of the result. You should press "Confirm" at the top to confirm and to finish the transformation properly

![image](https://github.com/user-attachments/assets/47d3b3c6-a964-42b3-b7d1-38e7ee119fbe)

**Comment by mduensing2000** [comment]
Thank you!

**Comment by photopea** [comment]
no problem :)
