### ISSUE TITLE
FONT issue：Local fonts don't work

### ISSUE THREAD

**Issue by Jager-hs** [photopea/photopea#7407]
Your Operating System:  Windows 10
Your Web Browser: edge
The problem happens in the Incognito Mode, too: don't know

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open the local file
3. Double-click to select characters：“AKN”
4. try to change font from "S-Jxingkai" to "perfect pixel" (完美像素)
5. when click "perfect pixel", it doesn't work
6. here are the Snipaste
![Snipaste_2024-12-15_11-58-24](https://github.com/user-attachments/assets/7c4c34e2-75d9-4dbc-a271-7db21bddc2f2)

PS: i tried use "perfect pixel" in powerpoint, it works, so it is not font's issue

**Comment by photopea** [comment]
Hi, what exactly is step 2 and step 3? What file should I open and where should I double-click?

**Comment by photopea** [comment]
I have to close it, because nobody is responding.
