### ISSUE TITLE
NOT MOVING 

### ISSUE THREAD

**Issue by MENNISHERE** [photopea/photopea#7408]
THE LAYER ISNT MOVING 

![Screenshot_15-12-2024_13533_www photopea com](https://github.com/user-attachments/assets/8aedbe7c-fa9a-41e4-8981-62c06d5f443d)
 

AND NOT SHOWING EVEN THE OBJECT IS NOT HIDDEN

**Comment by lazitos** [comment]
I have the same problem, the images are locked and I can't move them!

**Comment by photopea** [comment]
Did you try it in the incognito mode? Or in a web browser with no browser extensions?

**Comment by MENNISHERE** [comment]
> Did you try it in the incognito mode? Or in a web browser with no browser extensions?

no but when i make psd and refresh the tab and insert the psd the same problem is on the way

**Comment by photopea** [comment]
I think you have browser extensions, which are doing this to Photopea.

**Comment by MENNISHERE** [comment]
I THINK SO

**Comment by photopea** [comment]
so just disable all your extensions and let me know if you still have any problems.

**Comment by photopea** [comment]
I have to close it, because nobody is responding.
