### ISSUE TITLE
Gybe Asmz - unability to rename project.

### ISSUE THREAD

**Issue by gybeasmz** [photopea/photopea#741]
Unable to rename project once it´s created. It should be possible to double click the name of the project on it´s tab and rename it.

**Comment by photopea** [comment]
The document name is something, what is not stored in a PSD file. It is just the name of the file in the computer.

If we allow users to save files directly to the computer in the future, renaming file would be very confusing (should the old file be updated / renamed / deleted?). It is better to save your file and rename it in your computer / Google Drive.
