### ISSUE TITLE
Форми

### ISSUE THREAD

**Issue by Ksena30** [photopea/photopea#7410]
![Screenshot 2024-12-15 222724](https://github.com/user-attachments/assets/36f2d5cc-12c3-479c-ab13-677c7d1af6ca)
Вітаю! 
Я хочу використати у своїй роботі форму серця. Я вибираю інструмент довільна форма, але не можу вибрати форму серця із запропонованих шаблонів. Додаток photopea зависає і мене викидає з сторінки браузера. В чому причина? Як можна уникнути цього?

**Comment by photopea** [comment]
Did you try it in the Incognito mode?

Maybe you are running out of RAM memory, as you have layer styles, etc. What do you see in Edit - Local Storage?

**Comment by Ksena30** [comment]
Я пробувала працювати на цьому ж ПК, але з іншого аккаунта. Там також
додано стилі. Але все працює і форма відкривається, я можу їх вибирати і
працювати з ними.
Що може бути в моєму обліковому записі, що я не можу працювати з Формами?

нд, 15 груд. 2024 р. о 23:17 Photopea ***@***.***> пише:

**Comment by Ksena30** [comment]
![Screenshot 2024-12-16 005315](https://github.com/user-attachments/assets/b99c7d6f-38d0-4c1e-985a-7c601bb9ca30)

**Comment by photopea** [comment]
I don't know. Can you make this bug happen when you open Photopea in the Incognito mode?

**Comment by photopea** [comment]
I have to close it, because nobody is responding.
