### ISSUE TITLE
Define new tool preset only work with brush

### ISSUE THREAD

**Issue by fer0li** [photopea/photopea#7411]
Your Operating System: Windows 10
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Select type tool or any other tool other than a brush
3. Try define a new preset

**Comment by photopea** [comment]
I never used type tool presets in Adobe Photoshop. What exactly can it achieve?

**Comment by fer0li** [comment]
It is used to save specific tool configurations and make it easier to use later. Using the type tool, for example, if people need to typeset several texts with different configurations, such as font, size, line height, etc. This helps to avoid wasting time having to configure everything several times.

**Comment by photopea** [comment]
I have implemented the Tool Presets for the Type Tool. Not all properties are saved, but let me know if you are missing some property.
