### ISSUE TITLE
Maximum shape=circle breaks at radius > 20px

### ISSUE THREAD

**Issue by yikuansun** [photopea/photopea#7412]
Your Operating System: Ubuntu
Your Web Browser: Chromium
The problem happens in the Incognito Mode, too: Yeah

**This must be done to see the problem**
1. Go to www.photopea.com
2. Import an image
3. apply Maximum with shape=circle, radius=21

It reverts to the Square behavior.

**Comment by photopea** [comment]
Are you talking about Filter - Other - Maximum?

What is a "circle radius"? I can see only the "Radius" parameter in that filter.

What is the "Square behavior"? I think this filter works as it should work. Does it work different in any other software?

**Comment by yikuansun** [comment]
![Screenshot from 2024-12-16 20-29-34](https://github.com/user-attachments/assets/9787d295-bbe1-468b-abb0-ec363367720e)

The spots should be circular, not rectangular.

Edited my previous message to make it more clear.

**Comment by yikuansun** [comment]
I did notice that WebGL sometimes crashes on Maximum. This is why I suggest using a downscale-filter-upscale method, as details matter less when radius is higher. For example, if I apply Maximum with radius=22, it would essentially be the same result as if I downscaled the image to 1/4 size, applied Maximum with radius=11, and scaled it back up to original size. This is how I implemented high blur values in Zeus.

**Comment by photopea** [comment]
But Maximum filter is not the Blur filter. If I do what you say, the result will be very blurry. Just try to do it yourself manually in Photopea.

I have increased the limit for acceptable blur radius in a case of the round shape. For 1 MPx, you should be able to use a radius of up to 75 Pixels.
