### ISSUE TITLE
Element that invokes "Save" or (ctrl+s)

### ISSUE THREAD

**Issue by sidsharths1245** [photopea/photopea#7413]
I am trying to write a script to auto save the project every 30 seconds. I usually edit the files directly from google drive so the "Save" option works for me. But I want a way to automate it. I can't find the element that triggers the "Save" button. Can you please help me? I want the script to trigger "Save" directly.

**Comment by photopea** [comment]
If you run Photopea in an iframe, you can send it a script: app.activeDocument.save();

See https://www.photopea.com/api/live

But pressng Ctrl+S once in a while should not be that hard, I think.

**Comment by photopea** [comment]
I have to close it, because nobody is responding.
