### ISSUE TITLE
Not a bug but still god dang

### ISSUE THREAD

**Issue by PotatoLad7** [photopea/photopea#7415]
Dont make removing ads 15$ a month, theres no way in hell people are actually gonna pay for that when they have ad blocker, youre comparing yourselves to big companies. Make it like 3 dollars or make the whole program 15$ because i would gladly pay 15$ for photopea.

**Comment by PotatoLad7** [comment]
no need to comment on this btw just a thought

**Comment by DatGamerYoloYT** [comment]
honestly photopea should be either fully paid or fully free i am NOT paying money just to get a wider editor for like 3 months

**Comment by photopea** [comment]
okay, I will close it now.
