### ISSUE TITLE
Photoshop Smart Objects not working properly and freezing when saving smart object

### ISSUE THREAD

**Issue by lucianarps** [photopea/photopea#7416]
Your Operating System:
Your Web Browser: All
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open a Photoshop Smart Object
3. Double click the smart object layer
4. Open and place the image
5. .Save Smart Object
6. Bam! Freeze

**Comment by photopea** [comment]
What is the step 2? Do you mean opening a PSD file with smart objects?

I think I did what you say, but I do not see any freeze. Could you share the exact files that you are doing this with?

**Comment by photopea** [comment]
I have to close it, because nobody is responding.

**Comment by lucianarps** [comment]
Hi! I never saw your email before.
I still can't use the psd mockup

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by photopea** [comment]
If you have problems with Photopea, please, make a proper report and describe the precise steps, what should be done to see the error.

**Comment by lucianarps** [comment]
I've done it before, but I don't understand why the support case was closed if I didn't heard from you back.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by photopea** [comment]
Please go to www.github.com and see the full discussion. Do not send emails to random github addresses.
