### ISSUE TITLE
Auto-select is not persistent after close Photopea

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#7418]
Your Operating System: chromeos
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Login to your account
3. Select Move Tool
4. Disable Auto-select
5. Close Photopea
6. Open Photopea
7. Select Move Tool

It will have Auto-select enable again.

But as far as i know, this setting should be saved in my account, right? Like the tool positions

**Comment by photopea** [comment]
You must wait at least 5 seconds between steps 4 and 5, to make sure your settings are saved on our server.

To avoid too many requests from the logged in users, we send the settings to the server only once in five seconds.
