### ISSUE TITLE
NEW?

### ISSUE THREAD

**Issue by MENNISHERE** [photopea/photopea#7419]
THIS IS NOT A ISSUE BUT A QUESTION 

WHEN NEW UPDATE COME ?

PHOTOPEA WORKING ON IT?

**Comment by MENNISHERE** [comment]
my question is when photopea gonna update?

**Comment by photopea** [comment]
We update Photopea almost every day.

**Comment by MENNISHERE** [comment]
> We update Photopea almost every day.

i dont understand like which feature you add recently?????

**Comment by photopea** [comment]
Today, we added a feature of opening DNG photos taken by Goolge Pixel 8 in Photopea :)
