### ISSUE TITLE
Prototype

### ISSUE THREAD

**Issue by webdesignerbg** [photopea/photopea#7421]
Hi! Will we be able to create prototypes in the future?

**Comment by photopea** [comment]
What do you mean?

**Comment by webdesignerbg** [comment]
I mean creating links for clients to preview as prototypes. 

Example: https://invis.io/HV12CDD6A9E4

**Comment by photopea** [comment]
You can share your work with a friend by pressing File - Share - PSD, and sending a link to your friend.

**Comment by webdesignerbg** [comment]
No, I mean prototyping.
