### ISSUE TITLE
Cannot see item boundary when item is selected that allows item resizing

### ISSUE THREAD

**Issue by dexterbrian** [photopea/photopea#7423]
Your Operating System: Ubuntu
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Select an item/layer

**Comment by photopea** [comment]
You probably need to enable "Transform controls" at the top.

**Comment by dexterbrian** [comment]
Let me try that. Thank you.

**Comment by photopea** [comment]
I guess it worked, right?
