### ISSUE TITLE
The account popup freezes and refuses to close yet I can still draw and click on different tools, etc.

### ISSUE THREAD

**Issue by Latatude** [photopea/photopea#7424]
Your Operating System: Windows 10
Your Web Browser: Google Chrome "Application"
The problem happens in the Incognito Mode, too: N/A

**This must be done to see the problem**
1. Go to www.photopea.com
2. Install and open the desktop application
3. manage to go to the studio
4. Click on account
5. Click to sign in
6. Sign in
7. Don't return to the application immediately after signing in
8. Try to close the popup

**Comment by photopea** [comment]
What is step 3 " manage to go to the studio"?

What is step 7? After you log in (e.g. at Google), you are directly redirected back into Photopea, what do you mean by "dont return to the application immediately"?

**Comment by photopea** [comment]
I have to close it, because the person is not responding :(
