### ISSUE TITLE
Transform controls are broken

### ISSUE THREAD

**Issue by Latatude** [photopea/photopea#7425]
No matter what I try, I still can't transform a single thing. Normally, all I'd have to do is make a selection, free transform, grab, and drag one of the corners to resize the content within the selection. But now, when I try to do the same thing (drag one of the transform control corner squares), absolutely nothing happens, as though I never even clicked it in the first place! The same issue occurs when trying to rotate the object. I can still move objects, though. I've tried clearing the cache, reinstalling the Photopea "application," using the website itself (signed in and not), creating a new project, restarting Photopea, refreshing it—every troubleshooting technique possible other than restarting my entire device. What else could I possibly try so I can finally get back to working on my project?

**Comment by photopea** [comment]
Try this maybe: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by SergioGlorias** [comment]
same problem for meIn this case, it's been a few days
It seems that if I add an image without doing anything, it shows as "free transform", but then when I do another action (like adding a new image again, it shows as "move" and the transform controls don't work

**Comment by SergioGlorias** [comment]
[Screen recording 2024-12-21 10.37.22.webm](https://github.com/user-attachments/assets/e0ff12ef-c7e2-4829-b911-f301c66d90e3)

**Comment by photopea** [comment]
I am sure that it will work perfectly if you turn off all your browser extensions. One of your extensions is doing this to Photopea. You installed that extension, so you must be aware of it.

**Comment by SergioGlorias** [comment]
ok... it seems to have worked again by clearing the site's cookies

**Comment by photopea** [comment]
ok, I will close it now.
