### ISSUE TITLE
"Fonts not londed yet?" !?!?!?! What happens? Please help me

### ISSUE THREAD

**Issue by IbraDiniz** [photopea/photopea#7426]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
You must answer the questions above.

**Comment by vetpennews** [comment]
fonts not loaded yet

**Comment by vetpennews** [comment]
نريد حل لهذا المشكلة

**Comment by photopea** [comment]
I have to close it, because the person is not responding.
