### ISSUE TITLE
Local fonts won't load

### ISSUE THREAD

**Issue by cheesemachine19** [photopea/photopea#7427]
Your Operating System: Windows
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create text box
3. Write some text
4. Highlight text and change to a font from my computer, in this case a Microsoft Office font.
5. Displays "fonts not loaded yet", and it never loads. Additionally, the text cannot be edited while it is loading although I assume that is normal.

**Comment by photopea** [comment]
I opened www.photopea.com for the first time in my life, and there is no "Microsoft Office font" ... so what are you talking about? Where should I get this font?

**Comment by cheesemachine19** [comment]
I selected "load local fonts" in the text tool, and wanted to use one but the fonts aren't loading. They've worked in the past, but for some reason it just endlessly displays "fonts not loaded yet".

**Comment by photopea** [comment]
Could you open Photopea.com in the Incognito mode and try to load your fonts (TTF / OTF files) into it manually? Will it crash on a certain font?

**Comment by photopea** [comment]
I have to close it, because the person is not responding :(
