### ISSUE TITLE
Impossible d'avoir la sélection rectangulaire

### ISSUE THREAD

**Issue by Calamelle** [photopea/photopea#7428]
C'est uniquement une sélection en ellipse qui fonctionne.

**Comment by photopea** [comment]
Hi, how can I help you?

**Comment by Calamelle** [comment]
La sélection en rectangle a des bords arrondis, c'est normal? Comment avoir un vrai rectangle?

**Comment by photopea** [comment]
You have probably set "Feather" at the top, which blurs the edge.

**Comment by photopea** [comment]
I guess it was fixed.
