### ISSUE TITLE
Gybe Asmz - incorrect behaviour of gradient tool when masking layers

### ISSUE THREAD

**Issue by gybeasmz** [photopea/photopea#743]
Let´s say, I have a rectangle on a white background and I apply a mask to it, I grab a gradient tool and I want to make that rectangle to fade out to one of it´s sides into the white color. Right now it´s impossible because of 2 reasons:

1) The gradient drawing tools is poorly optimized meaning, that when I draw from the edge of the rectangle to the middle of it. I expect that part of the rectangle to become faded out. Instead what I get is almost unnoticable change to a lighter color on a very small part of that range. It seems the reason for this issue is, that the beginning of the applied gradient actually starts way before the point where I started to draw it. In other words: the range I draw with the gradient tool represents in the final results maybe the last 10% of the actual gradient applied. So the 90% of the gradient is applied outside that rectangle. So what needs to be done is, that the 90% are also being applied within the range that I draw.

1) When I apply multiple gradients to one place, all it does is, that the previous applied gradient is nullified and replaced entirely with the new one. Applied gradients should be adding to one another not rewriting each other.

**Comment by photopea** [comment]
Are you drawing all your gradients to a mask (not the layer)?

**Comment by photopea** [comment]
I have to close it because of lack of details.
