### ISSUE TITLE
When i type it becomes ____________

### ISSUE THREAD

**Issue by ilovemycat2** [photopea/photopea#7430]
Your Operating System: windows 11
![Skärmbild 2024-12-23 144235](https://github.com/user-attachments/assets/90f2a6f7-da33-4f31-b9e3-fcc21bf2c42a)

Your Web Browser: microsoft edge
The problem happens in the Incognito Mode, too: no

**This must be done to see the problem**
1. Go to www.photopea.com
2. FB event image
3. Type tool
4. Type
5.Even when i try changing font it doesnt work

**Comment by photopea** [comment]
I think it is because you are typing a white text onto a white background. Change the color of a text, or a color of a background, to be able to see your text.

**Comment by milqnomadu** [comment]
@photopea Ivan be real, the motivation that drives you to consistently respond to all of these issues is that they give you a good laugh, is it? Hopefully it is because if not I have no idea how you are doing this, some (99%) are incredibly hilarious ahhaha

**Comment by photopea** [comment]
This problem (typing white text on a white background) is actually reported to us about five times a year.
