### ISSUE TITLE
My screen is black

### ISSUE THREAD

**Issue by LeoAndSabrina** [photopea/photopea#7433]
Your Operating System: Windows 11
Your Web Browser: Firefox
I made a issue in May and it fixed itself but it happened again, I kind of also need it now
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. For me I open a new canvas thing and it's just black.

https://github.com/user-attachments/assets/7bba66f6-61b0-450f-bf0f-d7a72f826cc8

**Comment by photopea** [comment]
Do you know why ads are not showing on the right side? Which version of Firefox do you use?

**Comment by LeoAndSabrina** [comment]
I do not know why there are no ads and my Firefox version is the latest one 133.0.3 (64-bit)

**Comment by photopea** [comment]
Do you use any add-ons which are allowed to modify Photopea? Could you make sure that no add-ons are modifying Photopea while you are using it?

**Comment by LeoAndSabrina** [comment]
No I do not use any Add-ons. sorry for responding late It's been a rough Christmas Eve for me, I had to take my cat to the pet hospital.

**Comment by LeoAndSabrina** [comment]
I just realize now that it shows when I hover over the tab?

https://github.com/user-attachments/assets/43241f8e-9bb0-4e5a-998e-088466d68c91

**Comment by photopea** [comment]
It could be some bug in the way Firefox handles your GPU through your GPU drivers.

Try to disable WebGL (More - Use WebGL), or try to use Photopea in a different web browser. Also, try to restart your computer, to make Firefox restart, too.

**Comment by LeoAndSabrina** [comment]
It's weird because when I go to Google Docs too it's black... :|

**Comment by photopea** [comment]
We are not responsible for how Google Docs work.

**Comment by LeoAndSabrina** [comment]
Yes I know.

**Comment by LeoAndSabrina** [comment]
It's fixed.

**Comment by LeoAndSabrina** [comment]
It is fixed.
