### ISSUE TITLE
Attempting to load a file locally gets http://localhost/test.png net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by velara3** [photopea/photopea#7434]
Your Operating System: Win
Your Web Browser: Brave

I am attempting to load Photopea.com in an iframe on my server 

```html
<iframe id="photopea" src="https://www.photopea.com" style="width:800px; height:500px; border:none;"></iframe>
```	

and load in a local file from localhost and it is getting an error:

`net:  http://localhost:3001/file net::ERR_BLOCKED_BY_CLIENT` 

I've started with [demo 3](https://www.vectorpea.com/pp_api_demo/demo3.html) and then changed the URL to localhost. 

```js
function buttonClick() {
	if (inter!=0) return;
	//wnd.postMessage('app.open("https://www.photopea.com/api/img2/pug.png", null, true);',"*");
	wnd.postMessage('app.open("https://localhost:3001/file.png", null, true);', "*");
}
```
**This must be done to see the problem**
1. start a nodejs project and run a local server
2. open demo 3 and download it to the server
3. open the demo 3 page in an an editor and edit the URL to point to a file on localhost (see function above)
4. load the page in browser
5. click the button (an error occurs)

How do I load in a file when running Photopea in an iframe on localhost? Do I have to upload it somewhere? 
Is it possible to load in an array buffer?

**Comment by photopea** [comment]
Can you see any errors in a web console? Did you try it in a normal web browser instead of Brave?

**Comment by velara3** [comment]
The error in the console is the one mentioned:  
```js
net:  http://localhost:3001/file net::ERR_BLOCKED_BY_CLIENT
```
I ended up loading the image and passing in the array buffer.

**Comment by velara3** [comment]
Is it ok to ask questions here instead of reddit? I don't want to create a reddit account

**Comment by velara3** [comment]
I created a tag for Photopea on Stackoverflow. 
https://stackoverflow.com/questions/79310673/save-layer-to-file-or-array-buffer-and-trim

**Comment by photopea** [comment]
I am glad it works! Is there anything else I could help you with?

**Comment by velara3** [comment]
Yes, How would I export a layer to a PNG? Something like the following:  

```js

window.addEventListener("message", this.onMessage);

// after content is loaded 
function buttonClick() {
    this.iframeWindow.postMessage("var layerIndex = 2; app.activeDocument.exportLayer(layerIndex)");
}

function onMessage(event) {
        var data = event.data;
        var arrayBuffer = data;
        console.log("data:", data);
    }
```

**Comment by velara3** [comment]
Is there an event for when Photopea is completely loaded? DOMContentLoaded? Or do I just check for the "done" message twice? 

Also, is there a way to havea Photopea dispatch different event names? 
For example, when I send a message to Photopea with an action can I pass in an event name that Photopea can dispatch with that event name?

**Comment by photopea** [comment]
To tell Photopea to send you the current image, use Document.saveToOE("png"), see https://www.photopea.com/learn/scripts

I believe all what you need is described at www.photopea.com/api and related sites, just read it all properly.

**Comment by velara3** [comment]
> To tell Photopea to send you the current image, use Document.saveToOE("png"), 
Thank you! Will that return the entire document image or the layer? 

I've been reading the API but I couldn't find anything on extracting just the image of the layer.

**Comment by photopea** [comment]
You should hide all other layers, maybe crop a photo, to "extract just one layer".

**Comment by photopea** [comment]
In other words, saveToOE() saves what is on the screen. So it is your task to make what you want me displayed on the screen.
