### ISSUE TITLE
vetpennews@gmail.com

### ISSUE THREAD

**Issue by vetpennews** [photopea/photopea#7435]
![WhatsApp Image 2024-12-24 at 5 52 58 PM](https://github.com/user-attachments/assets/8f4ad825-0cd2-4027-973b-a5ca11bb8422)
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment]
It should be fixed now. If it is not fixed, please, make a proper report in English.
