### ISSUE TITLE
Attempting to type in a text box when creating new project on tablet

### ISSUE THREAD

**Issue by cfogs2091** [photopea/photopea#7436]
Your Operating System: Samsung Android tablet
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: have not attempted

**This must be done to see the problem**
1. Go to www.photopea.com
2. .Create new project
3. Attempt to change project title or
4. Attempt to adjust canvas size
5. Window zooms out and on-screen keyboard doesn't appear

**Comment by photopea** [comment]
Could you try it again? I have fixed some issues with fonts.

**Comment by cfogs2091** [comment]
It still happens.

**Comment by photopea** [comment]
What is step 3 and step 4? What is a project title? how do you adjust canvas size?

**Comment by photopea** [comment]
I have to close it, because the person is not responding :(
