### ISSUE TITLE
Loaded fonts not working

### ISSUE THREAD

**Issue by IngoBrain** [photopea/photopea#7437]
Your Operating System: Windows 11
Your Web Browser: google chrome 
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Try to import font (for example mr_ReaverockG)
3. You can see msg that font loaded. Also you can find it in font list but you can't select it (it's not clickable). 
4. Some other fonts loaded correctly and can be selected from the list? but not that one (before today everything worked)

[mr_ReaverockG.zip](https://github.com/user-attachments/files/18241656/mr_ReaverockG.zip)

**Comment by photopea** [comment]
The new release of Photopea does not support fonts which have underscore in their name.

Who named your font like this? Could they give it a normal name instead?

**Comment by photopea** [comment]
It is fixed now, you can use fonts with any names now.
