### ISSUE TITLE
Sentence With Multiple Font Sub Types Can't Be Changed

### ISSUE THREAD

**Issue by lalalawoowoo** [photopea/photopea#7438]
Your Operating System: Windows 10
Your Web Browser: Mozilla FireFox
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Create a text and use multiple font subtypes (example: a sentence with 5 words in regular and the last word is semi bold of the same font)
3. If you select all the words (both regular and semibold) then try to change it to another font subtype (change all the words to bold) or change the font to anything else (doesn't matter if it's a photopea font or a loaded font) it wont work.
4. If you erase the last word so that all the words are the same subtype, you are able to change the subtype or the font.

**Comment by photopea** [comment]
Hi, I am very sorry, it should work now.
