### ISSUE TITLE
Have the color picker display show info at the bottom of the wheel when top is obscured.

### ISSUE THREAD

**Issue by MesaBlack** [photopea/photopea#7439]
as of right now:

![image](https://github.com/user-attachments/assets/8004579d-f893-4723-b082-1d2c86e2996e)

I want the info to be shown at the bottom sometimes. Is it possible? Or is this suggestion kinda ridiculous?

**Comment by photopea** [comment]
This is called the Eyedropper tool.

You can simply scroll down with a mouse wheel in this case.

You can actually open a Color Picker window (at the bottom of a toolbar) and then, wherever you click, it will show you the color value  in the Color Picker window.

**Comment by MesaBlack** [comment]
I got the magic wand by my side too. Yeah this suggestion was ridiculous.
