### ISSUE TITLE
Removal of one extra step in shape color selection

### ISSUE THREAD

**Issue by gybeasmz** [photopea/photopea#744]
When I draw a shape, the default color is bright red (not the best default setting - no fill + some 2px border would work better, so the user can at least start wireframing immediately, but this is just a detail), when I want to change the color, I click on the color rectangle in the upper button stripe and I expect to see the collor palette immediately. Instead of this, every single time that I want to change color, I have to make one extra click on the red rectangle to get inside the color pallete.

**Comment by gybeasmz** [comment]
it doesn´t have to show the full pallete with the XY circle color generator. But at least 5 basic shades from every color.

**Comment by photopea** [comment]
The Style of vector shapes, that you draw, depends on the previous shape, that you drew.

Also, when you select some shape (in Layers panel), its style is set as a default style, and will be used for new shapes.

Can you be more precise, what button do you mean?

**Comment by gybeasmz** [comment]
![image](https://user-images.githubusercontent.com/40023509/41105410-f8be6b84-6a6d-11e8-8e73-584f01696108.png)
When I click on either of these two buttons. I should get a collor pallete immediately. Right now I have to make one more click to get to the pallete.

**Comment by MichalSZZ** [comment]
Hmm something like that? That shows after first click on fill color
![obraz](https://user-images.githubusercontent.com/38118273/41105405-f5267ac0-6a6d-11e8-8593-fbd459dcb8ab.png)

**Comment by gybeasmz** [comment]
EXACTLY!

**Comment by gybeasmz** [comment]
I´m at work, don´t have PS to make screenshots from.

**Comment by photopea** [comment]
But isn't it easier to select your own color in Color Picker, than to see a table of 1000 colors and look for the one you like?

**Comment by MichalSZZ** [comment]
It could be only one line for me (last used or colors in project).

But I know about one place, where the second click in the color isn't necessary. When I  clicking fast 2x on shape thumbnail on a layer palette, most of time (99, 9%) I want to change only color of the shape (not variant of the fill like gradient, pattern etc.)

**Comment by photopea** [comment]
Ok, I added the list of last used colors.

You can click 2x a thumbnail in Photopea, it will open the Properties panel, where you can choose the color.

**Comment by MichalSZZ** [comment]
But there is still, a one more unnecessary click in this moment
![color-select](https://user-images.githubusercontent.com/38118273/41145922-e90053ee-6b01-11e8-91d0-0f5beffc1491.jpg)
Pink color - what it should work for me (like in Photoshop) - or can you tell me a reason why properties panel should be opened first as a middle step?
