### ISSUE TITLE
Tools not working!!!

### ISSUE THREAD

**Issue by Bedrockwiz** [photopea/photopea#7441]
My Operating System: MacOs
My Web Browser: Google Chrome

None of the tools will make any changes to my image, and they worked perfectly before. I can change all the values and I have verified that the opacity is at 100%, and yet it won't let me draw a pixel. Below is a recording of my issue:

https://github.com/user-attachments/assets/f74d6058-deb5-41c0-8f50-403465bb592d

**Comment by photopea** [comment]
There could be a tiny selection somewhere in your image. Try to press Select - Deselect.

A proper bug report must include steps how to reproduce the bug. And you should be able to close and reopen Photopea several times, and reproduce the bug yourself each time.

**Comment by Bedrockwiz** [comment]
I am not sure how to reproduce the bug, nor am I sure of how to deselect this tiny selection as I have attempted to search for it but was unsuccessful.

**Comment by photopea** [comment]
Did you try to restart Photopea? Did it help?

**Comment by Bedrockwiz** [comment]
Wouldn't restarting Photopea delete the project I've been working on?

**Comment by photopea** [comment]
could you save it first?

**Comment by Bedrockwiz** [comment]
Nevermind. I wasn't logged in when I saved it so it's highly likely that it was not saved when I closed it.
