### ISSUE TITLE
Cannot rename paths on Firefox, therefore cannot save work path as normal path

### ISSUE THREAD

**Issue by Patrickode** [photopea/photopea#7443]
Your Operating System: Windows 11, version 23H2
Your Web Browser: Firefox 133.0.3
The problem happens in Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com in a Firefox Browser
2. Select the Paths tab
3. Create a new path
4. Double click the path name (Nothing will happen)

I learned that this a browser specific issue from this reddit thread: [https://www.reddit.com/r/photopea/comments/1cxfrub/how_to_rename_a_path/](https://www.reddit.com/r/photopea/comments/1cxfrub/how_to_rename_a_path/). I've searched the issues tab, but it doesn't seem like either of the people in that thread have created an entry for this.

I encountered this issue by wanting to save the Work Path as a proper path that won't get automatically overwritten; I found another issue here, #2495 , saying I can do so by renaming the Work Path, which made me realize I cannot do so. Renaming does indeed work on the installation of Chrome I have in my back pocket.

I also cannot click and drag paths on Firefox like I can in Chrome. Click and dragging seems to do nothing in Chrome (I would have thought it would let me reorder the paths), but I CAN do it, so maybe this is a symptom of the same problem.

**Comment by photopea** [comment]
Thanks for reporting it, it is fixed now!
