### ISSUE TITLE
Layer disappears when merged down

### ISSUE THREAD

**Issue by KVKMYH72VT** [photopea/photopea#7447]
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Make shape with pen tool
3. Repeat step 2
4. Merge down both shapes

**Comment by KVKMYH72VT** [comment]
https://imgur.com/a/TfJwEl2 here's a video.

**Comment by photopea** [comment]
You must try it in the Incognito mode (i.e. see if it happens Photopea while Photopea is not being modified by any of your browser extensions).

**Comment by photopea** [comment]
I will close it, because the person is not responding.

**Comment by KVKMYH72VT** [comment]
oh my god i forgot sorry...

**Comment by KVKMYH72VT** [comment]
i wasn't available.

**Comment by KVKMYH72VT** [comment]
I have tried in incognito now and it still disappears

**Comment by photopea** [comment]
Could you send me your document as a PSD file to support@photopea.com ?

**Comment by KVKMYH72VT** [comment]
Okay

**Comment by photopea** [comment]
I did not receive anything yet.

**Comment by KVKMYH72VT** [comment]
Sorry, it's sent now.

**Comment by photopea** [comment]
I still did not receive anything :(
