### ISSUE TITLE
Thumbnail URL is incorrect.

### ISSUE THREAD

**Issue by Pantyusha2002** [photopea/photopea#7448]
Good evening! I have a problem. Problem publishing my file as a public template. 
error: Thumbnail URL is incorrect.

i.imgur.com/xR2boah.jpeg
www.photopea.com/#iqhEPMs95

Screenshot :
![Uploading Снимок экрана (439).png…]()

**Comment by photopea** [comment]
Does it say why the URL is incorrect? Did you try to add https:// ?

**Comment by Pantyusha2002** [comment]
Thanks for your quick reply. After I inserted a link to the preview https:// in front of my existing link, I was able to publish the file, but now the image is not showing on my page, I provide a screenshot of the screen.
![Снимок экрана 2024-12-29 120104](https://github.com/user-attachments/assets/7415db3e-531b-42c3-9d06-a6993d532c4a)

**Comment by photopea** [comment]
You have a space between "https://" and "i.imgur.com..." in the thumbnail URL.

**Comment by Pantyusha2002** [comment]
I thought i checked this, you are right. Sorry for the inconvenience. Everything is fine. I hope to add to the general library of templates and develop our community to the best of my ability) Thank you! You are one of the best!)

**Comment by photopea** [comment]
thank you for sharing your work with our community :)
