### ISSUE TITLE
Can not type the text.

### ISSUE THREAD

**Issue by tham1997-28** [photopea/photopea#7449]
I can not type the text .
[
![Screenshot (1)](https://github.com/user-attachments/assets/59745e05-6ef3-4f33-a801-1283533d325e)

**Comment by photopea** [comment]
What happens when you try to type? Did you try to make a larger text box?

**Comment by Rwolf1232** [comment]
I cannot type the text 

![image](https://github.com/user-attachments/assets/5f1e9b06-adca-4089-886a-8104ad976acc)

**Comment by tham1997-28** [comment]
I think i have found out the way. Thanks😊

**Comment by photopea** [comment]
Whenever you have problems with Photopea, the first thing you try should be to disable all your browser extensions. We can not make Photopea work if you allow your extensions do whatever they want to Photopea.
