### ISSUE TITLE
Shift toogle for locking of horizontal/vertical movement

### ISSUE THREAD

**Issue by gybeasmz** [photopea/photopea#745]
Very important feature - when I move something or draw something, very often I need the mouse cursor to only move within a horizontal or vertical direction. I should be able to hold shift and that would lock the mouse cursor only to vertical/horizontal movement. This is cruciall for wireframing work or precise selection of layers parts.

**Comment by MichalSZZ** [comment]
Drawing with brush tool works for me.
Moving not - it is a good idea to implement that in Photopea.

**Comment by photopea** [comment]
I made it work for the Move tool, too.

I always used the Arrows to move objects horizontally / vertically (or Shift + Arrows to make larger steps). But now, you can do it with Shift + Mouse.
