### ISSUE TITLE
Is there a way to have Photopea dispatch different event names?

### ISSUE THREAD

**Issue by velara3** [photopea/photopea#7454]
Is there a way to have Photopea dispatch different event names instead of done or send back more data for the call I sent to it? 

For example, when I send a message to Photopea with an action can I pass in an event name that Photopea can dispatch with that event name?

For example, every time I send a message to Photopea I get back `done`. So I ask what is done? Is photopea loaded, is my script done, which script is done? 

From the [docs](https://www.photopea.com/api/live): 

> When Photopea is initialized and ready to accept commands, it sends the message "done". After your message is processed, Photopea also sends back the message "done"

So if I have a function to handle messages from PP and I have more than one, let's say I have 10 commands then my function starts to get large and unwelding and starts to look like this:  

```js
onMessage(event) { 
    var data = event.data;
    
    if (eventCalled=="enlargeImage") { }
    if (eventCalled=="shrinkImage") {}
    if (eventCalled=="addBorder") {}
    if (eventCalled=="removeBorder") {}
    if (eventCalled=="somethingelse") {}
    if (eventCalled=="somethingelse") {}
    if (eventCalled=="somethingelse") {}
    if (eventCalled=="somethingelse") {}
    if (eventCalled=="somethingelse") {}
    if (eventCalled=="somethingelse") {}
    if (eventCalled=="somethingelse") {}
}
```

**Comment by photopea** [comment]
The script that you send to Photopea can contain a command app.echoToOE(); which will send you back any string that you want.

Really, just read our docs and think how to use it for your purpose.

**Comment by velara3** [comment]
Hi I have read through the docs many times. Thank you for the reminder to read it again. 

What I'm asking about is if I can have a custom event dispatched when I do something like this:  

```js
app.activeDocument.saveToOE("JPG", "MyCustomEvent");
```

**Comment by photopea** [comment]
You can use app.echoToOE("Hello"); right befor or after using saveToOE();
