### ISSUE TITLE
Can't open HEIC

### ISSUE THREAD

**Issue by lugospod** [photopea/photopea#7455]
Your Operating System: Windows 11 Pro, 10.0.22631 Build 22631
Your Web Browser: Version 131.0.6778.140 (Official Build) (64-bit)
The problem happens in the Incognito Mode, too: ys

**This must be done to see the problem**
1. Go to www.photopea.com
2. File -> Open -> Select HEIC file
3. Nothing happens, no error message, the window for selecting the file closes and nothing happens.

Same problem if I drag and drop the photo from WIndows explorer (which use to work befoe).

**Comment by photopea** [comment]
I just tried to open a HEIC file in Photopea and it works fine. Could you please share your HEIC file with us? So that I can do the Step 2 the same way you do it.

**Comment by photopea** [comment]
I can not open your HEIC file in Affinity Photo. But it opens all HEIC files that I have on my hard drive (except of yours).

I also found this discussion: https://community.synology.com/enu/forum/1/post/189985

I will try to look into it, but I would still recommend you to start taking photos in JPEG as soon as possible, which are just slightly larger, if you want to avoid problems like this and have a comfortable life :D

**Comment by lugospod** [comment]
Unfortunately, the size difference isn't small - it adds up quickly -  HEIC is at least 50% smaller. This has a huge impact on the iCloud storage. :(

Thank you for helping out!

**Comment by photopea** [comment]
JPG photos are usually 10 - 20 percent larger. Did you make any test yourself? If a HEIC file is 2x smaller than a JPG version, it very probably has a worse quality.

**Comment by photopea** [comment]
The problem is inside the library "heic2any": https://github.com/alexcorvi/heic2any/issues/63  We will try to switch to a better library.

**Comment by photopea** [comment]
I would like to let you know that it is fixed now, and you can open any HEIC file in Photopea, even those from iPhone 16 Pro Max.

BTW. I tried to convert your 1.65 MB HEIC file into a 1.1 MB JPG and I can not see any huge difference in quality. Maybe Apple is not doing an efficient JPG compression on their devices to persuade you that their HEIC is significantly better.

![image](https://github.com/user-attachments/assets/d50f1311-ed34-4cb3-8f44-118c3ff81d39)

**Comment by photopea** [comment]
The files that you have sent me are 2.6 and 0.7 MB in size :/

**Comment by lugospod** [comment]
[iCloud Photos (64).zip](https://github.com/user-attachments/files/18333910/iCloud.Photos.64.zip)

I downloaded from ICloud this time, should be better now. Last attempt was via iPhone using some ZIP app.

**Comment by CyberMew** [comment]
> The problem is inside the library "heic2any": [alexcorvi/heic2any#63](https://github.com/alexcorvi/heic2any/issues/63) We will try to switch to a better library.

@photopea may I know which library you end up using?

**Comment by photopea** [comment]
I think we are using this: https://github.com/catdad-experiments/libheif-js
