### ISSUE TITLE
LAYER NOT EDITABLE error message

### ISSUE THREAD

**Issue by gybeasmz** [photopea/photopea#746]
Quite frequent issue, usually when I´m trying to delete a layer ... happened just now when I was trying to remove a rectangle. All I had were 3 layers, 3 identical rectangles. I´m unable to delete it at all.

**Comment by photopea** [comment]
It sounds like you have a selection, and pressing Delete tries to clear that selection (which is not possible on a vector shape).

Can you be more precise? What did you do? I can not reproduce it.

**Comment by photopea** [comment]
I think it was related to a bug with keyboard shortcuts on MacOS, which is fixed now.
