### ISSUE TITLE
Inability to lock layers

### ISSUE THREAD

**Issue by gybeasmz** [photopea/photopea#747]
When working with a bigger number of layers or when some layers are overlaping, the ability to lock some layers is absolutely necessary. Now it´s not even possible to lock the background white layer, so you endup moving it around and it causes chaos. There should be a little lock icon in the layers list. Selected layers would get locked after clicking the lock icon and a lock icon should appear next to them with maybe some visible change of color.

**Comment by MichalSZZ** [comment]
@gybeasmz 
In this #700 Issue I have asked for that functionality too

**Comment by photopea** [comment]
Locks have been implemented. Currently, there is only Pixels lock and a Total lock.
