### ISSUE TITLE
Invert selection bug 

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#749]
When I use keyboard shortcuts for invert selection (Shift + cmd + I), then after i make that, selection is inverted but the image pixels has inversion of colors too.

Same strange bug is when I am on mask edition. I have selection, I want only invert selection, but with that operation, black and white on mask is inverting too.

**Comment by photopea** [comment]
It should be fixed now. Thank you!

**Comment by MichalSZZ** [comment]
Works good. Thanks!
