### ISSUE TITLE
Highlight selected layer

### ISSUE THREAD

**Issue by Ser-Gen** [photopea/photopea#75]
Right now I need to toggle visibility of layer to find desired layer. It may be easier with a dashed border around an image of layer or something like that.

**Comment by photopea** [comment]
I think it needs some more precise description of how the new improved system should look like.

Simply drawing a border around each layer would make it look confusing. In practice, when the layers are logically structured into folders, it is quite easy to find the layer you need.

**Comment by photopea** [comment]
I am closing it for now. Feel free to reopen it, if you wish to leaborate that idea.
