### ISSUE TITLE
Some PSD file are not editable anymore.

### ISSUE THREAD

**Issue by Nakeuh** [photopea/photopea#750]
I have a psd file that is no more editable with photopea.
I was able to edit this file until 24 May at least, but now and since few days, when I try to load the file in Photopea, the Loading popup stay indefinitly and the file never load.

The console browser show the following error : 
Uncaught TypeError: Cannot set property 'cL' of undefined
    at Function.$I.wi (pp.js:1788)
    at Object.$$.PSD.NG (pp.js:178)
    at Function.KF.xm (pp.js:6638)
    at KF.xM (pp.js:6627)

See Attached file for the psd example 
[Free minimalistic and clean resume.zip](https://github.com/photopea/photopea/files/2083791/Free.minimalistic.and.clean.resume.zip)

**Comment by photopea** [comment]
Hi, another user reported the same problem an hour ago on Facebook, and we fixed it 30 minutes ago, so it should work now :)
