### ISSUE TITLE
Quick Selection

### ISSUE THREAD

**Issue by imms93** [photopea/photopea#753]
As you can see from the gif, the selection made with Quick Selection tool is irregular, I mean the selection brush selects well some parts of the image but in other ones selects more than it should, and giant squares and rectangles come out...is there a way to make the selection "smoother"? It looks a bit clunky, I don't know how to explain it well, and so in the end I'm forced to select with the Magnetic Lasso tool and then use Refine Edge. The gif is a bit long but illustrates the entire attempt to select the girl in the photo with QS,
![gif](https://user-images.githubusercontent.com/30982542/41202252-8015fd2c-6cc6-11e8-862a-34f973912611.gif)

**Comment by photopea** [comment]
The Quick Selection tool is all about COMBINING Unite and Subtract modes. When the giant square appears, switch to Subtract (or press Alt) and draw over the Background. If you always use Unite, the selection will only become bigger, but never smaller.

The principle is very similar to Refine Edge https://www.photopea.com/learn/refine-edge
You are making a trimap here, too.

**Comment by MichalSZZ** [comment]
When I wrote longer and more precise, I had in my mind, working with adding and subtracting with small brush at the finish of selecting. I think that we both (author of this issue and I) know how that is work in Photoshop. Big rectangles doesn't appear there. That is the biggest difference in Photopea and Photoshop but I don't expect so much from free browser application :)

**Comment by photopea** [comment]
In Photoshop, the selected area also gets bigger than you want, sometimes. So you have to use Subtract, too.

But in Photoshop, the whole image is selected in that case (a big rectangle of the image). Photopea just creates a small rectangle around the brush in that case.

**Comment by photopea** [comment]
But when I combine Unite / Subtract, sometimes, the area gets selected, where I draw with Subtract before (this should not happen). So there is a bug, but it is different than what you say it is.
