### ISSUE TITLE
SVG looks awful

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#754]
This is not a precise bug report, but this file i am uploading looks very bad on photopea:

https://drive.google.com/open?id=0BxACIQ9JCuosbWEweXdEZFVFVnc

**Comment by avagp** [comment]
Every path is in there, but is like all transparent.

**Comment by photopea** [comment]
Hi, there were some problems with reading coordinates of clip-paths and text layers. It works much better now. Thanks!

**Comment by avagp** [comment]
Thanks, works better, but let me make it harder:
![caja](https://user-images.githubusercontent.com/11801254/41324015-29f0f12a-6e80-11e8-8437-ed8655039fdd.png)
https://drive.google.com/file/d/1DIp9tpMIj6NMn7CKL8K0LRhAuxiAxt30/view?usp=sharing

Also, if i preload the fonts, they wont display properly when opening the svg

**Comment by photopea** [comment]
Cool! I like challenges! :)

**Comment by photopea** [comment]
I improved it :) It looks the same as in a browser. But somehow, in a browser, it looks a bit different than your preview :(

**Comment by avagp** [comment]
Hi!  It's me again.

I have a PDF from a AI, and i get toooooo many paths for just one white plain square.

What do you think might be the problem?

[back cover layout.pdf](https://github.com/photopea/photopea/files/2373280/back.cover.layout.pdf)

**Comment by avagp** [comment]
Dont worry, i know what it looks like that. There is a lot of other shapes outside the canvas.

I did not know that the PDFs retain that data.
