### ISSUE TITLE
Unable to select multiple layers in firefox

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#757]
I am unable to select multiple layers in Mozilla Firefox browser by clicking on layer in layers window while holding Ctrl or Shift. It works in Google Chrome browser but not in Firefox.

**Comment by photopea** [comment]
Hi, I can do so in the latest Firefox on Windows 7. Can you update your Firefox? Do you see any errors in a browser console?

BTW. you should not click on thumbnails with Ctrl, because it creates a selection from the layers transparency.

**Comment by hxim** [comment]
Hello, no error in console and I have latest beta version of Firefox.
I investigated it and found out it is caused by setting "privacy.resistFingerprinting = true" I use and which causes multiple layers not selectable for some reason in photopea...

**Comment by photopea** [comment]
I think you should discuss it with the developers of Firefox.
