### ISSUE TITLE
What this font? i forget to noted !

### ISSUE THREAD

**Issue by abdiprawira** [photopea/photopea#758]
![image](https://user-images.githubusercontent.com/31374361/41362242-b7d60dbc-6ee5-11e8-88c9-d8e14d1f99a8.png)

![image](https://user-images.githubusercontent.com/31374361/41362230-adfebc1c-6ee5-11e8-98f6-998bb9b07b4e.png)

**Comment by photopea** [comment]
Hi, you can load your custom fonts into Photopea using File - Open.

**Comment by abdiprawira** [comment]
no. i get thats font at photopea, but i forgot the name of font
