### ISSUE TITLE
User friendly colorpicker

### ISSUE THREAD

**Issue by Ser-Gen** [photopea/photopea#76]
It's hard to understand, which color will be selected by colorpicker.
I need to zoom image to get color of thin border, for example.
You can make colorpicker more user friendly.

Cursor can zoom image by itself and show which color will be selected, like here:
https://github.com/pixhub-int/colorimeter
Colorpicker is activated by `Ctrl + click`.

**Comment by photopea** [comment]
If you click the image and drag over the picture, the current foreground color is updated as you move your mouse. You can zoom in in advance to be more precise.

I think that color picker with a pointer lock would be an "overkill".
