### ISSUE TITLE
Feature request: autosave

### ISSUE THREAD

**Issue by rocifier** [photopea/photopea#760]
It's annoying to permanently lose an entire document and all changes if I log out of windows, update my web browser, etc.

One solution would be to autosave to browser's IndexedDB, with a quota increase request if the autosave will be above 50MB.

Upon loading the app, the past autosave would be accessible from the file menu if present in the browser database.

**Comment by rocifier** [comment]
Yeah I work on things for multiple days, and I leave the window open. I don't get a message when I log out of windows, just that Chrome is waiting to be closed. If I forget I have something unsaved open in photopea, then it gets lost when I click "restart anyway". The same thing happens actually in photoshop, but it has an autosave feature, or other programs have a recovery feature instead.

**Comment by landsman** [comment]
This gonna be great feature!

**Comment by sonamdawa101** [comment]
Instead of logout we can prefer computer in **HYPERNATE** state so that all our work stays. It is faster to open your computer and also continue with your previous work.  TTTTTT

**Comment by rocifier** [comment]
Actually I use hybernate and it already works for me. If you are being logged out and this is the problem, I suggest opening a new issue.

**Comment by photopea** [comment]
There is no mandatory log in / log out in Photopea. You can log in / out any time, without having to reopen your work.

If your websites are closed or reloaded after the Hybernation of your computer, you can probably change it in computer / browser settings, somewhere.

**Comment by landsman** [comment]
autosave to dropbox / icloud / google disk would be great imho

**Comment by alekexe** [comment]
I just wanted to make an issue regarding this, maybe saving the smaller projects into localStorage would be an option? I think that limit is something like 5 to 10mbm, but for basic users, it would be great

**Comment by photopea** [comment]
If files are small, the browser will probably not crash. It crashes when the work does no longer fit into the RAM memory. But maybe we could show a message "save your work" once an hour?

**Comment by alekexe** [comment]
Perhaps? It would be a good feature.

**Comment by photopea** [comment]
We are waiting for a new web standard, which will allow websites to rewrite files on the hard drive without a Download dialog in between.

**Comment by Erelynn** [comment]
This would be a helpful feature. I have lost my work a couple of times because the browser froze and I had no choice but to quit it. I don't want the browser to permanently save my work but only temporarily until I can get back on the browser after quitting it or after shutting down my computer. If a feature like this is implemented, I'd also like the option to clear up any work that Photopea has automatically saved from the previous session. I wouldn't want everybody who opens Photopea to see what I've been working on because I prefer to keep my files private. I just would like a temporary backup in case something goes wrong, like the browser freezing up or crashing.

**Comment by JerryGreen** [comment]
Honestly if I would be able to CTRL+S **_to rewrite existing file_**, that would be already good.
Isn't it possible to rewrite those files that are created by PWA app itself?

**Comment by MichalSZZ** [comment]
It is possible but you have to make "save as" first and close the file. Next you have to open the file and after making some steps, use Ctrl+S and give permission to browser.

**Comment by JerryGreen** [comment]
> It is possible but you have to make "save as" first and close the file. Next you have to open the file and after making some steps, use Ctrl+S and give permission to browser.

Are you on windows? In my case I only get copies of the file, i.e.:


My File.psd
My File (1).psd
My File (2).psd
etc

**Comment by MichalSZZ** [comment]
@JerryGreen Yes I am.

Windows 10 and PWA version of Photopea.
After my steps and giving a permission I have that icon
![obraz](https://user-images.githubusercontent.com/38118273/123378755-71209d80-d58d-11eb-9ead-d5f169b49564.png)

**Comment by photopea** [comment]
I fixed it. Now, if you create a new document from scratch and save it as a PSD once, you can use Ctlr+S to rewrite the same document, without a window in between.

@JerryGreen I recommend you enabling "Ask where to save each file before downloading." - see here: https://support.google.com/chrome/answer/95759?co=GENIE.Platform%3DDesktop&hl=en

**Comment by xan2622** [comment]
> but I think Firefox will disappear soon anyway.

😯 What makes you think that?
Firefox is probably the number 1 software of the Mozilla Foundation, I doubt they cease its development anytime soon.

**Comment by Nu11u5** [comment]
Has the autosave FR been implemented?

An alternative proposal would be to use browser storage for file recovery in the case that Photopea is closed without saving or the browser crashes.  Photopea could save the workspace to browser storage periodically this way without affecting the user's file.  When the webapp is reopened it will restore the workspace from browser storage (and perhaps prompt a warning to save work to file).  The workspace recovery data would be freed when the file is closed in Photopea.

**Comment by photopea** [comment]
@Nu11u5 Photopea should remind you to save your work every 30 minutes. I think a browser storage is not reliable, as many people use browser extensions, which clear website data (and people dont even know that their extensions do that).

**Comment by photopea** [comment]
So we have added the autosave reminder for now (switch in Edit - Preferences).

If you opened a file from a Storage or from your computer, it should be enough just to press Ctrl+S to save it.

**Comment by xan2622** [comment]
Ivan, could you please consider adding an _input box_ to let the user set the frequency (in minutes) for the "autosave reminder"?

<img src="https://user-images.githubusercontent.com/1732773/180603832-209c9a72-5472-4989-aac5-74fa658e815c.png" width="50%" height="50%">

**Comment by arinuxz** [comment]
I lost a lot of unsaved files, I forgot to save all the files as PSD and I've been editing the image for 6+ hours and I lost all of my edited images, how do I get them back?

**Comment by jerrygreen** [comment]
Honestly Photopea doesn't quite look like a tool for many-many hours work. It looks cool at the beginning, but when your work starts having a hundred layers among your work and various smart objects, when you also put references & screenshots right inside the psd, - it begins «aw snapping» quite a lot.

Some desktop tools might also not work as fast when you compare a full-scale many hours work to a new document, but at least it doesn't «aw snaps». And yes, inability to restore unsaved work in Photopea doesn't add to solving this problem. But honestly the last is not on developers shoulders: Chrome can't save temp files. So basically yes, you lost your work, Gotta save. Like in 2007. Can't blame the app.

P.S. Though MAYBE developers could develop a feature to temporarily save everyone's work to their own servers, but this is a whole lotta another level of responsibility, and would require a lot of storage space, which could an overkill for a free app.

**Comment by photopea** [comment]
Saving work temporarily on a server is hard because of the internet speed. Let's say you can upload 0.5 MB/s. While it works perfectly for text (10 kB saved in under a second), saving a 200 MB PSD would take 7 minutes.

If you save your document to your computer just once, then, you can save with Ctrl+S without any window in between (works in Chrome and Edge).
