### ISSUE TITLE
Move cursor is not working. It´s copying everything I grab.

### ISSUE THREAD

**Issue by gybeasmz** [photopea/photopea#761]
Everything I grab and drag with move cursor is copyied with each click.

**Comment by photopea** [comment]
Maybe you pressed the Alt key. You have to specify what you did, so we can reproduce it.

**Comment by MichalSZZ** [comment]
Hi. It is a problem with alt - but not user problem.
Yesterday I had lessons with my students and it is a big bug. 5 of my students has problems with many different operations (making shapes from center etc.). 
It's look like they have all the time ALT pressed - but it isn't.

**Comment by photopea** [comment]
Do you know how to reproduce it? It never happened to me.

**Comment by photopea** [comment]
Maybe it depends on the OS and the browser.

**Comment by MichalSZZ** [comment]
Yesterday was the Armageddon :)
That was our 8th lesson and i'm sure - that bug wasn't before in photopea.

And again we had a freeze bug like in this #669  issue but in different situation (when i will have some more time, I will try to reproduce all the bugs)

**Comment by photopea** [comment]
What do you mean by Armageddon?  Copying by moving is because of this feature: https://github.com/photopea/photopea/issues/756

**Comment by MichalSZZ** [comment]
Armageddon because i didn't see so many bugs at one time in Photopea before :)

My students has told me on lesson that is something wrong with the program, and when I tried to do something, I saw that is bug with somthing with ALT (not pressed but everything I did without ALT - gave results like ALT was pressed).

**Comment by photopea** [comment]
Today, I completely remade the keyboard handling. Now, Photopea analyzes only hardware keys, that are pressed and released. The "language" of the keyboard (that you usually set in your OS) is completely ignored. I believe it may have fixed your issue.
