### ISSUE TITLE
Question: how to paste selection copied to clipboard into a raster mask

### ISSUE THREAD

**Issue by k-risc** [photopea/photopea#765]
Hi,

in an older version of Photoshop I went the follwoingway:
* add a raster layer to an existing layer (reveal all)
* select some part of some image and copy it to the clipboard
* Alt+Click (on Windows) on the mask
* Paste the contents of the clipboard into the mask

That way the image that was copied to the clipboard now changes the alpha transparency of that layer.

In Photopea I didn't find a way to select the mask itself so I could paste into it. Clicking on the mask gives it a dashed border, but the pasting pasts the contents of the clipboard as an entirely new layer nevertheless.

Maybe it is something that is not (yet) available in Photopea.

Any clue would be very appreciated.

Best

Christian

**Comment by photopea** [comment]
Hi, the "mask view" (what you see in Photoshop by Alt-clicking the mask thumbnail) is not available in Photopea yet.

I implemented the following behaviour: if you paste pixel data when the layer is selected, it is still inserted as a new layer. But if the mask is selected, it it inserted into the mask.

**Comment by k-risc** [comment]
Thanks so much, that helps a lot. Great work!

**Comment by RosyArts** [comment]
This appears to be broken

**Comment by photopea** [comment]
It works fine for me. Did you try to run Photopea without any browser extensions?

**Comment by RosyArts** [comment]
Yes, I have now tried it on Microsoft Edge (which I never use, so no extensions) and I am able to alt-click into the mask but when I try to paste into the mask it instead creates a new layer and pastes normally.

**Comment by photopea** [comment]
Could you maybe share a short video of your whole screen, so that we see what you are doing?

**Comment by RosyArts** [comment]
Sure!
![Video](https://github.com/photopea/photopea/assets/111189040/784452b0-91db-4007-ad42-7dcc783b5535)

**Comment by photopea** [comment]
That is really strange. Could you click the raster mask thumbnail before pressing Ctrl+V? Also, what if you try it in the incognito mode?

**Comment by RosyArts** [comment]
I'm quite confused now as it suddenly works as usual now. It must have been something on my end - strange that it persisted even through a power cycle though. Perhaps my alt key was playing up? Sorry to have wasted some of your time 😅

**Comment by RosyArts** [comment]
Oh - I have found what I did wrong! I was copying the layer itself, but it seems that Photopea wants me to copy the pixels of the layer.

**Comment by photopea** [comment]
Yes, exactly! You can e.g. select all (Ctrl+A or Select - All) and copy pixels (Ctrl+C or Edit - Copy).

**Comment by RosyArts** [comment]
Thanks for the help, and sorry for the hassle! Have a good day
