### ISSUE TITLE
Icons from layer palette disappeared on Chrome (Mac)

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#767]
https://youtu.be/P8Sj2UxY634 
Mac OS 
Chrome 67.0.3396.87

When I launch Photopea, everything is OK (icons are visible)
When I make new project or open something from computer, icons disappear... 
They are visibble again when I close all tabs with projects.
In FF i don't have this bug.

**Comment by MichalSZZ** [comment]
Strange. When I turn on the developer pannel in google chrome they are visible, when I close it, icons disappear. They are disappear too when I resize developer tool to smaller size. Maybe it is something with retina display?
No errors, 0 warnings.

**Comment by MichalSZZ** [comment]
Linking (in IMG) to base64 icons is OK when they are invisible. When I click on icons, they do what it should to do.

**Comment by photopea** [comment]
I think it has to do something with GPU drivers on Mac.

BTW. what if you disable WebGL (More - Use WebGL) ?

**Comment by MichalSZZ** [comment]
Yes. Disabling WebGL helps!
In past it worked good.
Is it a problem with my computer?

**Comment by photopea** [comment]
Another user reported a similar problem in the morning. I think there is a bug in a new Chrome for Mac. I just reported it. https://bugs.chromium.org/p/chromium/issues/detail?id=854340

**Comment by photopea** [comment]
Hi Michal, could you please write a comment here? https://bugs.chromium.org/p/chromium/issues/detail?id=854340

Write precisely, what is your environment (the model of chromebook etc.) and maybe take a short video with how it works.

**Comment by MichalSZZ** [comment]
Sure, but not now. I have a lot of work today.

**Comment by photopea** [comment]
Ok, so there was probably a bug in Intel GPU drivers in your previous Mac OS.
