### ISSUE TITLE
Photopea crashing 

### ISSUE THREAD

**Issue by hbrooks108** [photopea/photopea#768]
Over the last day or so the program has crashed while I am in the middle of projects, then when it loads again my layers are still there but I cannot actually view them or edit them. It is continually crashing.

**Comment by photopea** [comment]
Hi, what do you mean by "when it loads again"? Photopea usually loads empty, so there are no layers. How can your layers still be there?

Are you using Chrome on Mac?

**Comment by hbrooks108** [comment]
Well when I reload the page, what I previously worked on appears as if it can be worked on again and then there is nothing there, but the previous layers are in the layer sidebar. I don't know how they can still be there. 

I am using Chrome.

**Comment by photopea** [comment]
Are you using Mac?

**Comment by hbrooks108** [comment]
No I am on a PC. 

I also cannot seem to use the magnetic lasso at all. That is another point in which it crashes. I am working on large scale images though so I don't know if that is part of the issue.

**Comment by photopea** [comment]
Did you work with large scale images before, too? Did it work well?

I think Chrome introduced some RAM memory restrictions during the last update. How much RAM do you have?

**Comment by hbrooks108** [comment]
Yes, the last time I worked on a large scale image using the program it was fantastic! 

I have no idea how much RAM I have. I am at a computer at work not my personal computer. But you might be right about Chrome because when I tried using it on my computer it crashed as well. 

It just crashed again.

**Comment by photopea** [comment]
That is so weird. Can you try to use it in Firefox, if it works better?

**Comment by photopea** [comment]
BTW. how large are your images (in megapixels)? Are you doing anything specific before it crashes? Can you try to disable WebGL? (More - Use WebGL) ?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
