### ISSUE TITLE
Free transform with perspective 

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#769]
https://youtu.be/3-_7WTE_zYM
Dragging corner with ctrl/cmd works good in Photopea.

Dragging with ctrl + shift should snap to horizontal and vertical movment.

Dragging with ctrl + alt should make free skew (in X and Y) - it's not showed in movie

Dragging with ctrl + alt + shift should make transformation in to perspective (I use this feature a lot)

**Comment by photopea** [comment]
Hi, I think I made it work the same way :) Thanks!

**Comment by MichalSZZ** [comment]
Thanks! Works good for me :)
