### ISSUE TITLE
Drag & drop image bug

### ISSUE THREAD

**Issue by Studioartcz** [photopea/photopea#77]
If i drop img (jpg) on place where tabs names, image will added to current project. Right should be as a new project.

**Comment by photopea** [comment]
Drag and Drop always places the image into a current project. You must use File - Open to open your file as a new project.

**Comment by Studioartcz** [comment]
Auto-creating new project by drag & drop is hard stuff? :(

**Comment by photopea** [comment]
OK, I will try to implement such behavor, so it is more convenient for PS users.

**Comment by Studioartcz** [comment]
Thank you!

**Comment by photopea** [comment]
Now, you can drop files into the current project, or into the header of a specific project in a project bar. If you drop it into the empty place of a project bar, it is opened as a separate project.

**Comment by Studioartcz** [comment]
Nice! Thanks
