### ISSUE TITLE
Make it PWA?

### ISSUE THREAD

**Issue by dzek69** [photopea/photopea#770]
Hello,

I just discovered Photopea and I think this is just awesome thing!

Recently there is (finally) a heat about Progressive Web Apps. I think you can make your application more discoverable and profitable by converting it to PWA (should not be that hard). I've read #85 and about the fonts - I think just loading them when needed (or just slowly caching them on the client side in background while app is working) would be just enough, but I know it would probably take big effort to update your app like that.

Microsoft is gonna enable PWA apps to be installable from their store, so I guess you can get a lot of installs from there soon (which should improve your ad revenue rate, as basic ad blocker blocked ads on your current site in the browser, on PWAs all extensions should be inaccessible). PWA will probably become hot topic in coming months, even Google said they gonna make their apps PWA (and put them on MS Store IIRC) and Google hates creating apps for Windows users.

**Comment by photopea** [comment]
Photopea is a PWA, isn't it?

**Comment by dzek69** [comment]
Hm. looks like it does have manifest.json file, but my desktop Chrome won't install it as PWA, while it works with Google Photos for example.
Weird. Could be Chrome issue,

I did not try Photopea on mobile, not sure if I can do anything on mobile as this seems rather like desktop app.

How is your steps to run this as PWA on desktop?

**Comment by photopea** [comment]
What do you mean by "install as PWA" / run as PWA?

15 % of Photopea users use it on phones.

**Comment by dzek69** [comment]
I mean that what is PWA all about. Making an web app look like native application :) Desktop icon, no browser-like panels, no back/forward/refresh buttons, no url, no tabs.

See this for example how to add website as PWA with Chrome: https://www.xda-developers.com/progressive-web-apps-chrome-how-to/

It should be soon possible to do this with Edge browser - expected to be available this fall. This is when PWA applications are expected to be visible in Microsoft Store.

Every "proper" PWA app can be "installed" from Chrome menu. When installed - app switches to UI without browser elements, has just the app icon and title. The app is installed into OS apps menu. No other tabs. Probably clearing browsing data won't clear the app data from installed as PWA version.

In your app I can only make a shortcut on desktop to it. It has no icon in apps menu. When run - I see just Chrome UI, with address bar, other tabs, etc.

So I guess something is missing from Photopea that prevents Chrome from recognizing it as PWA. Other PWA websites seems to work just fine.

Short screen recording showing what I am talking about: https://dl.dropboxusercontent.com/s/oy5ax9w0s1areat/2018-06-24_19-53-40.mp4

**Comment by dzek69** [comment]
Did you enable full PWA support in Chrome, which is still experimental on desktop version?

See this guide: https://www.xda-developers.com/progressive-web-apps-chrome-how-to/

**Comment by photopea** [comment]
I think we should make Photopea work with regular browsers of today. So I guess we wait a couple of months and re-discuss it again, once PWAs are implemented better in browsers?

**Comment by dzek69** [comment]
Would be nice to have it ready now, PWA related technologies are pretty stable IIRC and should not change and this shouldn't be a big change to make photopea work, but it's your decision.

I'm gonna get deeper into PWA soon so I may look what's missing in Photopea somewhere in the future.

**Comment by photopea** [comment]
So what exactly is Photopea missing, so that you can call it a PWA?

BTW. I want to add the Install button into Photopea, which would work the same as "add to homescreen". But it seems it is not possible to do in browsers now. If you find any website, that has this feature working, let me know and I will add it to Photopea the same way as they did it.

**Comment by photopea** [comment]
We added More - Install Photopea button. It works well in Chrome for desktop, I hope it will work in all browsers soon (depends on when they impement it).

**Comment by blackinitial** [comment]
but still need internet connection, can't offline

**Comment by photopea** [comment]
We do not plan to offer Photopea offline :(

**Comment by blackinitial** [comment]
it would be nice if it could be offline 😀
