### ISSUE TITLE
sketch to pdf

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#773]
Hi Ivan,

I want to open sketch file, make some edits and save it to PDF, is this possible?
thanks

**Comment by photopea** [comment]
It should work, what exactly is a problem?

**Comment by photopea** [comment]
Hi, we improved the PDF export. There is a better export of layer fills. Also, there is an option to vectorize text during the PDF export. E.g. here is a demo "milk.sketch"

[milk-sketch.pdf](https://github.com/photopea/photopea/files/2805263/milk-sketch.pdf)

**Comment by hxim** [comment]
Hello when I opened attached milk-sketch.pdf in Adobe Acrobat Reader DC it says to me
"An error exists on this page. Acrobat may not display the page correctly. Please contact the person who created the PDF document to correct the problem." and is not displayed correctly
Also when I opended milk.sketch in photopea and exported my own pdf it said
"The font 'Riffic-Bold' contains a bad /BBox." and then "An error exists on this page. Acrobat may not display the page correctly. Please contact the person who created the PDF document to correct the problem."

**Comment by photopea** [comment]
Hi, I fixed both problems, PDFs form Photopea should work well in Acrobat Reader now.
