### ISSUE TITLE
Please add rtl (Right to left) paragraph direction to text tool

### ISSUE THREAD

**Issue by eladcandroid** [photopea/photopea#774]
That's how it looks like now:

![screen shot 2018-07-03 at 9 53 36](https://user-images.githubusercontent.com/13297000/42203293-fc526654-7ea6-11e8-9e3e-46e9e393571c.png)

**Comment by photopea** [comment]
Hi, the direction can be switched in Paragraph window. It is mentioned here: https://www.photopea.com/learn/text-style

**Comment by eladcandroid** [comment]
Works great! Thanks!!
