### ISSUE TITLE
I cannot open *.sketch file

### ISSUE THREAD

**Issue by nebojsha-m** [photopea/photopea#775]
Hi,
I can not open *.sketch file, LOADING is all time, I have try chrome, firefox, edge, same results

**Comment by photopea** [comment]
Hi, there is probably a bug in Photopea. Can you please send me your file to support@photopea.com ?

**Comment by photopea** [comment]
Ok, your file is iOS8 UI Kit +.sketch , thanks!

**Comment by photopea** [comment]
Hi, the bug was fixed and your Sketch file should work well now! thanks!
