### ISSUE TITLE
Allow importing of Layer Styles

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#776]

**Comment by photopea** [comment]
yes, you can right-click a layer and copy the Layer Style, then, right-click another layer and Paste the Layer Style. It is also available in the top menu: Layer - Layer Style - Copy / Paste.

Do you use any other workflow in Photoshop?

**Comment by MichalSZZ** [comment]
I'm using faster way (in Photoshop).
Dragging layer style icon from one layer to another with alt key.

**Comment by MichalSZZ** [comment]
In photoshop you can drag (with alt) and copy not only the whole fx, but one style too (f.g. color overlay) . You can make that by dragging with alt, only one layer style name.

**Comment by photopea** [comment]
Dragging layer styles between layers works in Photopea now, too (even with Alt).

**Comment by MichalSZZ** [comment]
Great news. Thx!

**Comment by photopea** [comment]
Layer styles (.ASL) can be loaded and saved now. https://blog.photopea.com/photopea-3-6-edit-presets.html
