### ISSUE TITLE
firefox cursor

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#777]
zoom cursor don't change cursor as in chrome

**Comment by photopea** [comment]
Hi, what do you mean? It works the same for me in Frefox and Chrome.

**Comment by photopea** [comment]
I have to close it because of lack of details.

**Comment by landsman** [comment]
It's installed on lastest Ubuntu 18.10.

![screenshot from 2018-07-21 12-09-28](https://user-images.githubusercontent.com/3184228/43034560-eea32ffc-8cde-11e8-8929-fa0db372c763.png)

![screenshot from 2018-07-21 12-09-49](https://user-images.githubusercontent.com/3184228/43034565-fb2ec286-8cde-11e8-9780-bffc83450528.png)

**Comment by photopea** [comment]
What is the problem? Can you make a video?
