### ISSUE TITLE
Free transform

### ISSUE THREAD

**Issue by Studioartcz** [photopea/photopea#78]
Hi, i am created 300 x 300 px canvas and insert 3000px img. 
How can i turn on free transform for layer? 

Is not intuitive - what about context menu or some icon in tools menu?
CTRL + T not working is associated for browser's new tab (can be fixed in desktop app too :+1:)

**Comment by photopea** [comment]
Ctrl + T works in every browser except Chrome ( Chrome has a bug, so you must use Edit - Free Transform ).

Do you want to enable Transform tool every time after Drag-n-dropping an image + scaling to fit the project size, like Photoshop does?

**Comment by Studioartcz** [comment]
Sure, it can be good if quality of picture stay same. 
I mean that free transform is little hidden for users :)

**Comment by photopea** [comment]
Now, when you drop an image into the project, the Free Transform is chosen automatically.

**Comment by Studioartcz** [comment]
Good! :)
