### ISSUE TITLE
Ability to type value in px in W and H when (free) transforming layer

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#782]
Now I don't know how to easy change width or height of the layer... When I type something in pixels in that place, after that it's change to percentage scale.

In Photoshop, between W and H input there is a chain icon. When you turn on that functionality, it scale width and height proportionaly. Even if you are typing in pixels in one of them, second showing value of scale in %. That is good to know that in many situation (when you must to scale another thing in that same scale)

**Comment by photopea** [comment]
I implemented it. You can click the button to keep the aspect ratio W vs. H.

You can also type a unit manually ("%" or "px") and the transform will adapt accordingly.

**Comment by MichalSZZ** [comment]
Works good! Thank you so much.

Only one more suggestion.
On retina (I can't check that on other display now), can't see units next to value (look at the screenshot). Half of % sign and no px visibility next to 180.0. Maybe a little bit wider input field for entering values, will be a good solution? 
Checked that on FF, Chrome, Opera and Safari on mac with retina. All fields with 4 digits and comma has the same problem.
![obraz](https://user-images.githubusercontent.com/38118273/43739635-06ab9976-99c9-11e8-8d65-35b0515f5d55.png)

**Comment by VityaSchel** [comment]
Hello! How to change units from % to px in width & height?
<img width="383" alt="image" src="https://github.com/photopea/photopea/assets/59040542/e6b7e83e-4228-4efe-acab-33cee78f62c3">

**Comment by VityaSchel** [comment]
I rasterized layer and now it shows 100% 🤣 
<img width="218" alt="image" src="https://github.com/photopea/photopea/assets/59040542/81658746-b182-4cc5-9808-9c93f41ba039">

**Comment by photopea** [comment]
You can simply type "120 %" or "800 px" into the box and press Enter.

**Comment by MichalSZZ** [comment]
> I rasterized layer and now it shows 100% 🤣 <img alt="image" width="218" src="https://user-images.githubusercontent.com/59040542/243813736-81658746-b182-4cc5-9808-9c93f41ba039.png">

when you rasterize the layer, the width, and height will be set to 100% because the program doesn't remember what it was before.
Only Smart Objects remember their initial sizes and show them as a % of the original.
