### ISSUE TITLE
Cursors in clone tool

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#784]
Crosshair cursor when choosing cloning from place with alt.

Brush outline (like it is now) but with cloning source in the middle (visual showing hardness too) to easy presenting from which place will be copy (when aligned option is turn on).

**Comment by photopea** [comment]
Hi, I added the crosshair cursor to a Clone tool and Healing Brush.

The "preview cursor" is quite hard to build into a current structure. We avoid using custom cursors at the moment, mainly because this feature is buggy in Firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1107646
