### ISSUE TITLE
Using an Acer Chromebook Photopea always hangs

### ISSUE THREAD

**Issue by thommesborg** [photopea/photopea#785]
I'm using an Acer Chromebook 15 with an i3 processor and working with Photopea is nearly impossible. For example a simple Blur, I try to move the slider and it is not moving by mouse, 10 sec. later the slider jumps to the place I released it as I tried before. OK, I'll try it again. The result was Photopea completely hangs up. I had to reload the complete page.

Next try was a surface blur. I select it via the menu and was waiting, waiting, waiting until an error said "site not responding". After 5 sec. more the surface blur sliders appear. Tried to move the threshold slider by mouse, but nothing happens.

Had a look on my devices task manager telling me that one of my four cores is at 100%. That lasts for about 3 min. and than both sliders "radius and threshold" had moved forward their position.
![screenshot 2018-07-07 at 15 02 54](https://user-images.githubusercontent.com/40795115/42411135-00a8349c-81f7-11e8-84c0-6c081139c65b.png)
![screenshot 2018-07-07 at 15 02 58](https://user-images.githubusercontent.com/40795115/42411138-0558b78c-81f7-11e8-9a74-a9827e601980.png)

**Comment by photopea** [comment]
Hi, Gaussian Blur takes about 1 second for 2 megapixels. So it takes 10 seconds for 20 megapixels, etc.

Surface blur is 4x slower, than Gaussian blur.

How large was your image? Does it correspond to these times?

**Comment by thommesborg** [comment]
Thanks for the feedback, much appreciated!

Sadly 👍 it does. I don't remember the exact size of the image, but it was a large one. If you try to move the sliders I thing the blurring starts immediately and not after releasing the slider, so the slider don't follow the cursors move, instead it jumps way forward or backward after the effect got applied. So, why not removing the slider and only go with the input-box and add an "go" or "execute"-button to the right (for those not remembering the enter-key)?

Regards, thommes

**Comment by photopea** [comment]
Hi, I just made the blur filter (Gaussian Blur and Box Blur) 2x faster!

There is a slider, because for images under 1 MPx, the slider moves quite smoothly. Also, you can usually just click on the new position of the slider, instead of dragging it.

**Comment by thommesborg** [comment]
Thanks for the feedback and your investigation, much appreciated.
