### ISSUE TITLE
Can't save/export images in 300dpi

### ISSUE THREAD

**Issue by dhartz84** [photopea/photopea#786]
I've tried creating a new project in 300dpi, changed the canvas size to 300dpi and changed the image size to 300dpi and every time I export as PNG, it gets exported in 72dpi.

**Comment by photopea** [comment]
Hi, sorry, the DPI information is not attached when exporting PNG files. Do you really need DPI for PNG? What is your use case?

**Comment by dhartz84** [comment]
The reason why I need this, is because I'm uploading my images to a third-party site, where it's a requirement, that the PNG images are 300dpi. Is there a way to save/export the PNG images in 300dpi?

**Comment by photopea** [comment]
Does it show any error when you upload the 72dpi PNG image?
