### ISSUE TITLE
Spot healing brush tool ! 

### ISSUE THREAD

**Issue by muzahid300** [photopea/photopea#787]
how it working ! i have no idea!!! i have used adobe photoshop , but this tool behavior is different ? !!!
and working like normal brush tool....

**Comment by photopea** [comment]
Hi, there is a bug, that it leaves a colored spots sometimes. Is that what you mean? Or what is the difference between Photoshop version?

**Comment by muzahid300** [comment]
if i click single it doesn't work, but when i drag a little bit it works
and i just want to be responsive with single click.
thank u ! :)

**Comment by photopea** [comment]
Ok there was a bug. I just fixed it. You can just click and it will heal the "circle", too, as in Photoshop.

Thanks for finding this bug!
