### ISSUE TITLE
Pen Tool Issue..

### ISSUE THREAD

**Issue by muzahid300** [photopea/photopea#788]
Please add in pen tool ''add anchor''  option  by showing " +" sign in tool cursor 

it will help what is going on next with this tool

**Comment by photopea** [comment]
Hi, it was added, thanks!

**Comment by QuantumInformation** [comment]
how do you use it?

**Comment by photopea** [comment]
You can click on existing path with a Pen tool, to add a new control point there.

**Comment by QuantumInformation** [comment]
When I click on an existing path,
![image](https://user-images.githubusercontent.com/216566/51433299-d5fe9d80-1c47-11e9-891c-c7f7df926911.png)


 it adds a new path
![image](https://user-images.githubusercontent.com/216566/51433295-c2ebcd80-1c47-11e9-8dc6-4b2c40d4b2f7.png)

**Comment by photopea** [comment]
You should click exactly on a contour, you probably clicked too far away from it.
