### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by muzahid300** [photopea/photopea#789]
when i delete layers by selecting & dragging "DELETE" icon bottom of the layer window doesn't show up or cannot be seen.
 try to improve please !
![crxl9--3](https://user-images.githubusercontent.com/41089986/42543400-83f5640e-84cd-11e8-8c35-b00d5705d6bf.jpg)

**Comment by photopea** [comment]
What do you mean? Do you mean to highlight the icon?

**Comment by photopea** [comment]
The icon is highlighted.

There was a bug, when you dragged multiple layers, only one was deleted. I fixed it.
