### ISSUE TITLE
Saving bugs

### ISSUE THREAD

**Issue by Studioartcz** [photopea/photopea#79]
1) Take picture i can't close if i have opened save for web too:

![image](https://cloud.githubusercontent.com/assets/3184228/17278297/23a4df64-575a-11e6-8e22-2fe70dbcf7fd.png)

2) Save for web - default quality is 50%, its bad - what about 90 - 95% ?
3) Button for saving isn't in "call-to-action" color and bad visible without hover. What about green? :)
4) Why i can't select my folder to saving path?

**Comment by photopea** [comment]
1) fixed
2) I think that 50% is not bad at all. People usually want small size when saving for web. You can set the bigger quality manually.
3) I think it should be a part of a ground-up design update.
4) It depends completely on browser settings. Your browser should offer you to choose the path.
