### ISSUE TITLE
Issues exporting Sketch files to PSD's using PP

### ISSUE THREAD

**Issue by jorgecorrales1** [photopea/photopea#791]
Hi all,

PP works really well when trying to convert sketch files to psd, however, sometimes (and completely arbitrarily) the text files within the psd's created by PP gets damaged/corrupted...

This issue makes PP somewhat unreliable for what I am trying to achieve.

I am using a MacBook pro with OS 10.13.5 with 
Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)

Any help with this will be much appreciated

J

**Comment by photopea** [comment]
Hi, could you please send us a Sketch file, that becomes corrupted after saving to PSD?

**Comment by photopea** [comment]
When you open a Sketch file in Photopea and save it as PSD, the PSD is always the same (if the Sketch file was the same). So I think, there are Sketch files, which are always converted into corrupted PSD files. It would be very helpful to have such Sketch file, so we can analyze it.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
