### ISSUE TITLE
 Chinese character not supported

### ISSUE THREAD

**Issue by doodlewind** [photopea/photopea#797]
Hi, photopea is a great work!

I've contributed to some Chinese i18n translation of the site, while in the text tool for now, I'm still unable to input Chinese characters like below:

``` text
你好
```

Pasting existing words into editor leads to mojibake. My charset should be UTF-8 by default. Am I missing something?

Thanks again for maintaining such an ambitious project!

**Comment by photopea** [comment]
Hi, thanks for your translation!

I tried to copy-paste your two characters into Photopea with Droid Sans Fall font, and they were rendered correctly. Do you have problems with copy-pasting text into Photopea? Are you sure it is not just a wrong font?

**Comment by doodlewind** [comment]
@photopea I tried Droid Sans Fall and DejaVu Sans and get following output:

![image](https://user-images.githubusercontent.com/7312949/43070232-e3cadc32-8ea1-11e8-87f3-b09ed73e5fbf.png)

The characters above are pasted into the editor. For IME text input I record following:

![photopea-0](https://user-images.githubusercontent.com/7312949/43070385-46646c00-8ea2-11e8-9c46-54809e608778.gif)

`你好` is expected while I can only get part of its Chinese pinyin, i.e., `ni`. I'm using latest Chrome on macOS, still confusing on how to get non-ASCII characters rendered 😅

**Comment by photopea** [comment]
Can you try to copy the text outside Photopea (Command+C) and paste it into Photopea with Command+V?

**Comment by doodlewind** [comment]
This is exactly what I did on copying and pasting…Droid Sans works for English and French for me, while besides Chinese, neither Japanese nor Korean can be displayed. Wondering if photopea tailors the font set for now? Willing to provide more help if needed.

**Comment by photopea** [comment]
Hi, I think we are discussing several unrelated problems. I suggest to fix them one by one.

I tried to Copy-Paste the text 你好  from here into Photopea in Chrome on Mac. I saw two squares. When I set the font to "Droid Sans Fallback" (not Droid Sans), it was rendered correctly.

Can you make sure it works for you too, and if it does, can you describe the next problem?

**Comment by doodlewind** [comment]
Thanks for your help, for now I can let Chinese display correctly. With `Droid Sans Fallback`, unicode content from clipboard seems to be usable!

Next problem is IME events, I record GIF to demonstrate it using Droid Sans Fallback:

![sep-08-2018 21-18-33](https://user-images.githubusercontent.com/7312949/45254560-f91d6480-b3ac-11e8-970f-9b4254e8e719.gif)

Hope it helps.

By the way, make I consult you for advice on customizable font rendering in web? Personally, I'm also working on a similar (but certainly not that powerful as Photopea for now) editing app. I found Photopea uses a single canvas handling both text and image layers. So for text editing, does this means to mock native behaviors more than basic typography, like cursor / selection / IME events? Since I found mocking native UX can be formidable, I come up with following idea:

1. Keep all render logic intact, simply add a global singleton `contentEditable` DOM for text editing, which is hidden by default.
2. When user begins text editing, show this DOM element exactly the place above the rasterized text (or maybe hide this text layer) with same text content.
3. When input ends, extract the input text, draw it into off-screen canvas and take the canvas image as a WebGL texture. Then we can apply effects like stroke, filling or shadow to this texture in FBO with minimal performance overhead. Finally re-render the text layer and hide the `contentEditable` DOM.

This can make sense on fixing IME issues. How do you think of this idea in case of Photopea or similar editing app?  Hope for your reply sincerely, thanks.

**Comment by photopea** [comment]
Hi, the typing in pinyin should work well now. Can you please try it?

I am not sure what you mean by "mocking native UX". Photopea uses only two methods of Canvas: getImageData() and putImageData(). All graphic computation is made on images as arrays of Bytes.

To convert text into pixels, you can use canvas.fillText(), or use our library Typr.js , which is open source :)

**Comment by doodlewind** [comment]
Thanks for your bug fix and reply!

I know both the `fillText` API and your awesome Typr.js works for converting text into pixels. For now I'm just wondering if we need to add some blending options to text that requires pixel-by-pixel operations, like stroke, glow, satin, shadow or overlay, does it make sense to render the text with these effects in WebGL shaders, or just use the HTML5 canvas? Looking forward to your suggestions, thanks.

**Comment by photopea** [comment]
As I said before, we do all graphic operations (including blending) on arrays of Bytes. We do not use Canvas or WebGL for this.
