### ISSUE TITLE
Text editing

### ISSUE THREAD

**Issue by byrning** [photopea/photopea#8]
When adding text to an image, one can't select any part of the text to edit it.

Trying to select the text produces "mouseup" and "mousemove" errors in pp.js, lines 509 and 504.

**Comment by photopea** [comment]
Can you tell us some details, or describe steps to reproduce it? For me, everything works well. You must use Type Tool for editing texts.

**Comment by byrning** [comment]
Hmm typical, I can't seem to reproduce the issue right now. Will report back if the issue happens again.

**Comment by photopea** [comment]
There may be bugs, which happen in special cases only, so they are hard to track down. Please let me know, if you notice a problem.

**Comment by byrning** [comment]
Will do. ;)

**Comment by photopea** [comment]
I am closing the issue, feel free to reopen it when you have more details.
