### ISSUE TITLE
Tools + 'ALT' function

### ISSUE THREAD

**Issue by kevintey** [photopea/photopea#802]
Hello Photopea,

Is it possible to have an alternate (opposite) function of some tools when 'alt' key is held down?
1. Blur tool + ALT = sharpen tool
2. Sharpen tool + ALT = blur tool
3. Dodge tool + ALT = burn tool
4. Burn tool + ALT = dodge tool
5. Sponge tool (saturate) + ALT = desaturate
6. Sponge tool (desaturate) + ALT = saturate

It will greatly improve the speed of drawing/retouching.

Also, for Brush Tool, is it possible to change the mouse cursor to color picker or crosshair when ALT is held down?

Thanks

**Comment by photopea** [comment]
Hi, I implemented everything that you mentioned in your post. Thanks for suggesting it! :)

**Comment by kevintey** [comment]
Thanks for taking the suggestion and implementing it ;) 
More to come!
