### ISSUE TITLE
Magnetic Lasso Select error

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#806]
When used on new/empty image/project Magnetic Lasso shows these errors:

pp.js:3243 Uncaught e
t.PB.Pv @ pp.js:3243
t.PB.$V @ pp.js:3235
t.$F.os @ pp.js:2832
fg.xj @ pp.js:7182
pr.q @ pp.js:9
SP.q @ pp.js:5001
SP.q @ pp.js:5001
SP.q @ pp.js:5001
Jh.$V @ pp.js:6627

**Comment by photopea** [comment]
Hi, there was a bug in division by zero. It was fixed. Thanks! :)
