### ISSUE TITLE
Auto switch to "custom" color type upon changing the color of fg/bg typed knots in gradient editor

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#807]
When the color type of a knot is set to foreground/background color (like the default two), it is only editable with the fg/bg color picker, any changes made by the color picker in the gradient editor have no effect, 

It's better for it to take over and switch to custom accordingly when try to make changes with the color picker in the grandient editor

**Comment by photopea** [comment]
Fixed. Thanks!
