### ISSUE TITLE
keyboard shortcuts don't work

### ISSUE THREAD

**Issue by natrader** [photopea/photopea#808]
The keyboard shortcuts don't work on my computer. I'm not sure if it's the type of computer or the browser that I'm using. I have an Asus computer and I'm using Microsoft Edge. I've tried all of them so I know it's not just a few that don't work. Thank you, it seems like a great program, if I could get the shortcuts to work.

**Comment by photopea** [comment]
Hi, there is a missing feature in Edge, and shortcuts don't work because of it. We have been discussing it here: https://github.com/photopea/photopea/issues/799
