### ISSUE TITLE
Script layer.kind always 0

### ISSUE THREAD

**Issue by creatissimo** [photopea/photopea#809]
If I create a new document or open an existing PSD and then run the following script then I go get "0" in my console output instead of e.g. "LayerKind.SMARTOBJECT"
`console.log(app.activeDocument.activeLayer.kind);`
This appears for all different kind of layers.
If I run the same script in Photoshop, then the result is as expected and described in Photoshop Javascript scripting reference

**Comment by photopea** [comment]
Hi, I implemented the support for following "kinds" (read-only):

"NORMAL"      :0,
"SMARTOBJECT" :1,
"TEXT"        :2,
			
"SOLIDFILL"   :3,
"GRADIENTFILL":4,
"PATTERNFILL" :5

**Comment by creatissimo** [comment]
Thanks a lot!
