### ISSUE TITLE
Script ActionReference and ActionDescriptor not working

### ISSUE THREAD

**Issue by creatissimo** [photopea/photopea#810]
If I open a new document and run one of the following scripts, then I do get the following error message in my console: "uncaught exception: e"

Affected scripts:
`var d = new ActionDescriptor();`
and
`var ref = new ActionReference();`

**Comment by braunly** [comment]
*bump*

**Comment by photopea** [comment]
Hi, it was implemented. E.g. you can run scripts from here: https://www.kirupa.com/motiongraphics/scripting5.htm
