### ISSUE TITLE
Error moving layers through mobile

### ISSUE THREAD

**Issue by Cthurax** [photopea/photopea#812]
I can not move layers through my J2 Prime! It's simply impossible and I also can not use the brush

**Comment by photopea** [comment]
Hi,  I just tried to use Photopea in a latest Chrome on Android, everything worked well.

Can you try to update your mobile browser? Or the OS?

**Comment by Cthurax** [comment]
Both are up to date, but the error continues, I do not know what to do.

A Qua, 1/08/2018, 12:28, Photopea <notifications@github.com> escreveu:

**Comment by photopea** [comment]
What is your browser and the OS of your Phone?

**Comment by Cthurax** [comment]
My browser is Chrome and my operating system is Android

A Qua, 1/08/2018, 13:08, Photopea <notifications@github.com> escreveu:

**Comment by photopea** [comment]
Do you know the version of Chrome and Android?

**Comment by photopea** [comment]
I just tried Photopea in a latest Chrome in Android 6.0.1 and it worked well. 

Can you reboot your Phone? Can you use your mouse e.g. in https://sketch.io/sketchpad/ ?

**Comment by photopea** [comment]
I have to close it because of lack of details. It seems like a problem in a device, which we can not solve through our program.
