### ISSUE TITLE
Bloat tool & Full screen options

### ISSUE THREAD

**Issue by frixenj** [photopea/photopea#814]
Recently there was an update done.  Since this was done, the bloat tool has vanished as well as the full screen option under the view tab. Why were these removed and if they are still there, where did you put them or what were they re-named to?

**Comment by photopea** [comment]
Hi, there never were such features in Photopea. Aren't you confusing it with https://pixlr.com/editor/ ?

We can add these features, if you can describe how they should work.

**Comment by photopea** [comment]
I have to close it because of lack of details.
