### ISSUE TITLE
Clone tool works only on current layer - "current and bellow" as an option

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#815]
I think that is not a bug in Photopea, but I must to ask - is there a possibility to make an option with sampling all layers (current and below) as an option to choose? In Photoshop it is set by default and use all pixels bellow as a source to clone (rasters, texts, shapes etc.).

**Comment by photopea** [comment]
This is related to https://github.com/photopea/photopea/issues/835 , so let's discuss it there.
