### ISSUE TITLE
Alpha Quirkiness

### ISSUE THREAD

**Issue by enzyme69** [photopea/photopea#816]
I am using Photopea to make this PNG QR texture, and I encounter a situation where the Alpha PNG seems to be using the Black and White that I drop.

I could see the Layers in Photopea, but unlike Photoshop, I cannot see the Alpha. I wonder how Alpha and Transparency is handled?

I only realized there is funky alpha transparency when I convert the PNG into JPG and it works correctly.

![qr_cube_yellow](https://user-images.githubusercontent.com/3952687/43646472-5ecb5702-9778-11e8-8c85-22f57b842982.jpg)
![qr_cube_yellow](https://user-images.githubusercontent.com/3952687/43646473-5f053594-9778-11e8-86f4-721de707d822.png)
![qr_cube](https://user-images.githubusercontent.com/3952687/43646475-5f3bc974-9778-11e8-9165-acc5b091bc4a.png)

**Comment by photopea** [comment]
Hi, I think I do not understand your problem. What is Alpha PNG ? What do you mean by seeing Alpha?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
