### ISSUE TITLE
Define Brush / Save Brush Settings

### ISSUE THREAD

**Issue by kevintey** [photopea/photopea#817]
Hello Photopea,

Possible to have define brush function? 
Users to draw any shape, with that layer selected, they can define the dimension of the brush by selecting a boundary, and then perhaps via the Menu > Edit > Define Brush; In which the brush shape will be available to select via brush's tool option/sidebar.

As for saving brush settings, understandably it will only work 1 time until the session closes, so I'm not sure if it will be practical or feasible. That way, users wont need to redefine a new brush when they are drawing.

Any thoughts? Thank you!

**Comment by photopea** [comment]
Hi, there are Circular and Pattern brushes in Photopea, see here: https://www.photopea.com/learn/brush-tools

So are you talking about defining a new Pattern brush? There is no place to store such brush between sessions, as cookies are quite small (that is why we don't store user-uploaded Patterns, Fonts, etc.)

**Comment by kevintey** [comment]
Is there a way to limit the sample dimension? e.g. max 50 x 50px?
Can we also made the presets a file to download, so that users can load them when they re-open the editor?

Just a thought...

**Comment by photopea** [comment]
Hi, I added this feature: use Edit - Define New - Brush to create a new "sampled brush". You can also save brushes as .ABR file (a tiny arrow next to a brush gallery).
![brush](https://user-images.githubusercontent.com/15955558/44542098-28c14100-a70c-11e8-9f57-644b3c759dfb.png)

**Comment by kevintey** [comment]
This is a great addition. 

- [Edit > Define New > Brush] This method works wonderfully.
- [Brush tool > Drop down box > Define New] This method **does not** seem to capture the brush.
- All export and import works fine. 

Thanks!

**Comment by photopea** [comment]
[Brush tool > Drop down box > Define New]  - this function saves the current brush into a gallery (i.e. the one that you are using right now, with all its parameters in a Brush panel).

E.g. you can select one of brushes from gallery, change its parameters, and store it as a new brush.

**Comment by kevintey** [comment]
Okay. Understood.
