### ISSUE TITLE
Crosshair cursor in color picker tool instead default arrow

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#819]
I think that will be better solution for showing the place, that colour is sampling from. In Photoshop there is an option to choose between pipette cursor and precise cursor (I'm using second one).

In all tools that have a color picker option in new window, there will be better to visual show an option to use color picker from artboard. Now it's work good, but UX is bad. Cursor don't change when user leave small window with color picker and want to sample color from artboard (to gradient, stroke etc.).

<img width="617" alt="obraz" src="https://user-images.githubusercontent.com/38118273/43740778-8b873a58-99cc-11e8-8f1e-052b3078ea63.png">

And don't think that I want a cursor from the screenshot atachment :) I know problem with cursors - default browser crosshair will be good.

**Comment by photopea** [comment]
Ok, I changed the whole structure. Previously, only Tools could control the cursors. Now, Windows can control cursors, too. I let a Color Picker have a crosshair cursor.

**Comment by MichalSZZ** [comment]
THX. Eyedropper tool should have arrow or crosshair? I ask because now I see arrow like before. All other things works great.

**Comment by photopea** [comment]
I think that you reported in the past, that the crosshair cursor does not let you see the color under it.

**Comment by MichalSZZ** [comment]
Hmm. I don't remember that. Are you sure that was me?
