### ISSUE TITLE
Snaping guides to pixel grid by default

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#820]
In web designing, there is frustrating when you want to make a new guide line, and must to check all the time, if position in pixels are without commas.

I asked my friends for opinion and all of them want that functionality in Photoshop (now there it is like in Photopea).

Of course (if you think that is good idea) in Photopea, you can make an option in menu view (to chose between), for all those who want to have precise guides with commas on X and Y, but I think the pixel snapping will be better by default.

**Comment by MichalSZZ** [comment]
In Photoshop you can make it using shift key when you dragging the new guide, but it is hard to explain now how that it work :)
It correspond with the zoom - by default on 100% it jumps by the 10px. When zoom is bigger then jump is more precise (5px, 2px and 1px). When there is zoom out - snapping the jump is bigger (20px, 50px 100px - i dont remember).
But that is not a solution for me. It will be good to have by default pixel grid snapping and if you can do that - ability to have jumps using shift button.

**Comment by photopea** [comment]
I made it work in a following way. It still moves "smoothly" with no snapping, if you don't hold any key.

If you hold shift and the zoom is 100% or more, it snaps to 1px, when it is less than 100% (zoomed out), it snaps to 10px.

**Comment by MichalSZZ** [comment]
Thank you. Great feature :)
But in free moving (without any key) info palette shows integers (X and Y) even when guide line is between pixels. Is that correct?
