### ISSUE TITLE
photopea - Indian Language Telugu & Hindhi is not supporting 

### ISSUE THREAD

**Issue by snehaProgrammer** [photopea/photopea#822]
i have seen a post regarding online photoshop tool, & found a post on [qa online training](https://www.qatraininghub.com/qa-testing-tools-online-training.php) fb add!

photopea is good & fast, required language support!

mostly major users will be from india if you upgrade this version with language support 

Thank you!

![photopea language support](https://user-images.githubusercontent.com/42198298/43819204-999c216a-9aff-11e8-9981-c85705c243f1.jpg)

**Comment by photopea** [comment]
Hi, I made some research and it seems like Devanagari is quite complex to render: https://docs.microsoft.com/en-us/typography/script-development/devanagari  , reordering characters and re-positioning them to one another is complex.

**Comment by photopea** [comment]
I implemented it in a following way. When you create a new text field, choose a fonts, which supports Devanagari characters. In the font menu, you can enable a filter, to show only Devanagari fonts. Then, you can type in Hindi.
