### ISSUE TITLE
Layer Style buggy

### ISSUE THREAD

**Issue by Primokorn** [photopea/photopea#823]
Hi,
Since yesterday I can no longer edit the layer styles. I get this popup instead.
Tested with various web browsers.

Steps to reproduce:
1. Open a .png file
2. Double click on the layer on the right.

Thanks.

![capture](https://user-images.githubusercontent.com/5938828/44090795-af9d805a-9fcb-11e8-8a38-6b8f19e26ebd.PNG)

**Comment by photopea** [comment]
Hi, I am very sorry for that. I just fixed it. Thanks!
