### ISSUE TITLE
moving objects with arrows doesn't work (changes opacity instead)

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#824]
steps to reproduce:

1. create new project
2. draw a rectangle
3. try moving it around with arrow keys: left, right, up, down

Expected:
moving rectangle around the canvas

Actual result:
opacity changes to some predefined values

I ensured that the Move tool is active

I am not sure when it started, but probably very recently)))

**Comment by photopea** [comment]
Hi, I did what you said, and the rectangle moves very well.

Currently, the arrow keys move object, while entering digits changes the opacity. Note, that Photopea can not detect, if the NumLock is on (if you use arrows on a numpad, they work as digits).

**Comment by photopea** [comment]
Photopea uses KeyboardEvent.code to detect keys: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code , which is always the same for a physical key.

**Comment by photopea** [comment]
I decided to close it.
