### ISSUE TITLE
After clicking on front color box, tools don't work

### ISSUE THREAD

**Issue by jedikalimero** [photopea/photopea#829]
I click on the front color box at the left side and a colourpicker window appears. I choose a colour, close the window and try to paint with the brush tool. But instead of painting, pointer keeps picking colours as if colour picker tool was selected instead of brush tool.

**Comment by photopea** [comment]
Are you able to reproduce it? I.e. turn off Photopea, turn it on again and to the same? I tried it, but it painted just well. I think Photopea Thinks your Alt button is down, for some reason.
