### ISSUE TITLE
Frequency filter

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#83]
It would be nice to have a frequency filter for removing patterns and noise from the image.  https://www.youtube.com/watch?v=yyox358zIRw

**Comment by manticorp** [comment]
How is the high pass filter implemented?

If you have a high pass filter already, a lot of the logic should be very similar to implement an FFT filter.

**Comment by photopea** [comment]
I implemented it under Filter - Fourier - Fourier Transform.
