### ISSUE TITLE
Moving with layer during opened Adjustments window

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#830]
I can moving with picture bottom if I have active Move Tool. 

![screenshot from 2018-08-19 19-31-09](https://user-images.githubusercontent.com/3184228/44311376-812fd000-a3e6-11e8-87b4-e87564f8c2d4.png)

![screenshot from 2018-08-19 19-31-16](https://user-images.githubusercontent.com/3184228/44311375-812fd000-a3e6-11e8-8702-42a8b521f687.png)

**Comment by photopea** [comment]
What exactly is the problem? I can not reproduce it.

**Comment by landsman** [comment]
that you can moving with layer during opened another window

**Comment by photopea** [comment]
but it is ok right?

**Comment by photopea** [comment]
Not every window blocks mouse tools.

**Comment by landsman** [comment]
I do not think so. I want using just window in front not behind. It was miss click which move layer.

**Comment by photopea** [comment]
Some windows "lock" mouse events (e.g. Color Picker lets you click into a document to pick a color). But other windows (e.g. Adjustments) don't need such behaviour.  Some users may want to move layers with an opened window. You can always step back in history.
