### ISSUE TITLE
Smart Object issue

### ISSUE THREAD

**Issue by 4banitoZz** [photopea/photopea#831]
Hello. 
I'm using a paper mockup PSD file: 
https://dealjumbo.com/downloads/free-logo-mock-up-presentation/

The problem starts when I try to edit and save the smart object. 
1. Double click on smart object layer.
2. Edit smart object in opend tab. 
3. File>Save (Smart Object) - Crtl + S and nothing happens. The file name (both smart object tab and the mockup psd tab) in the tab label will have an asterisk like it wasn't saved.
4. On a mockup PSD 'history' shows up a 'Updating Smart Object" notification. Still no changes are saved.

**Comment by photopea** [comment]
Hi, there was a bug in Photopea and I fixed it. It should work well now.

Note, that saving your smart object will take 5 - 15 seconds. It is "warped" in the main document (warps are hard to compute), and it occurs twice.
