### ISSUE TITLE
Motion blur filter

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#832]
When I open PSD (made in Photoshop) who has a smart object with smart filter on it (motion blur), I see the effect in Photopea but can't edit filter parameters.
There is also no motion blur in filters menu.

Is there a possibility to add that filter to Photopea?

**Comment by photopea** [comment]
Motion Blur and Radial Blur have been implemented! :)
![blurs](https://user-images.githubusercontent.com/15955558/44817289-49ded180-abe5-11e8-9008-ff549c41362b.jpg)
