### ISSUE TITLE
Text on a path

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#833]
It is great feature when you try to make for example round logo with text around it.

Here is good explained how that it works in Photoshop http://www.photoshop-bootcamp.com/how-to-draw-text-on-a-path-in-photoshop/ (random link from google first page)

**Comment by photopea** [comment]
Hi, I finally implemented it :) https://blog.photopea.com/photopea-4-4-text-on-a-curve-and-more.html
