### ISSUE TITLE
Histogram of / Clone from multiple layers

### ISSUE THREAD

**Issue by HelenaLindblom** [photopea/photopea#835]
When I make an adjustment layer for levels there is no histogram in the properties window? 
But when I make the levels adjustment throu the Image menu/ adjustment/ levels it shows.
I would like to see the histogram when I adjust the levels in the adjustment layer as well, please.

![skarmklipp](https://user-images.githubusercontent.com/42572629/44396377-fdd4c280-a53c-11e8-8cae-b552683fb04e.JPG)

**Comment by MichalSZZ** [comment]
I have that problem too. But before that worked well as I remember.

**Comment by photopea** [comment]
Photopea works with several images. There are images of each layer, and a "total image" of all layers combined. When you apply an adjustments to a single layer, the image of that layer is used. Clone tool lets you clone from a single layer, or a total image.

However, none of these images is suitable to compute a histogram for Adjustment Layer (there can be multiple layers under it, so the image of a single layer is not enough, and some layers above it, so the total image is not suitable either). Cloning from "current and bellow" is also not possible for the same reasons.

**Comment by HelenaLindblom** [comment]
Tank you for the answer. 
It works in photoshop when the histogram in the adjustmentlayer is a combination from all layers under it (except text layers). Maybe something to develop in Photopea? Otherwise it seems to be an excelent alternative if you don´t have Photoshop on the computer. I will use it with my students. 

![skarmklipp2](https://user-images.githubusercontent.com/42572629/44626056-62fe2e80-a916-11e8-914f-86048e9b8ab4.JPG)

**Comment by photopea** [comment]
Hi, I managed to implement it, so Adjustment layers have a Histogram, too. Cloning "Current And Below" is also possible.

**Comment by HelenaLindblom** [comment]
Wow, great! Thank you!

**Comment by photopea** [comment]
Thank you for suggesting it :) I was aware of this problem for a long time, but I was lazy, so I need somebody to kick me a bit from time to time :D

**Comment by MichalSZZ** [comment]
All fixes (cloning and histogram) works great! Thank you!

In next month I will start second semester "graphic design lessons - level begginer" with my students. It would be not possible without your hard work!

Once again big thanks!
