### ISSUE TITLE
Is 'Saving to server' feature still available?

### ISSUE THREAD

**Issue by sowd** [photopea/photopea#836]
Hi, I enjoy Photopea very much. Nice work!

I am trying to use 'Saving to server' feature described in the API document:
https://www.photopea.com/api/

However, "File - Save (To Server) option" does not seem to show up, even when I specify the "server" option.
Is the feature still available?

My test page (I did not prepare the receiver yet)
https://sowd.github.io/photopeatest/

**Comment by photopea** [comment]
Hey, the "Save (To Server)" is now renamed just to "Save". I changed the description in the API spec :) Thanks!

**Comment by sowd** [comment]
Thank you for the quick support!
I'll check.
