### ISSUE TITLE
you could allow to move selection with arrows w/o even clicking "Select + Transform Selection"?

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#839]
I think PS allowed that.
To resize - yes, you need to turn on the "Transform Selection" mode, but moving it around with arrows they allow w/o need of extra clicks, very convenient.

p.s. I understand that you probably have LOTS of more important stuff to work on, just guessing that you'd like to get this kind of feedback too anyway, so posting it when I notice something that hinders to work. Just thinking that it helps both sides, so hope it doesn't look too brazen :D

**Comment by photopea** [comment]
Hi, I implemented that. Also, if you move the selection multiple times, it stays as just one item in History (so History is not so messy).
