### ISSUE TITLE
Unable to save a smart object in Chrome or Firefox (OSX 10.11 Beta 15A278b)

### ISSUE THREAD

**Issue by verbiate** [photopea/photopea#84]
Steps to reproduce:

1. Open a file containing a smart object
2. Double-click on the layer containing the smart object. The smart object will open in a new tab.
3. Make a change to the smart object. The file name in the tab label will have an asterisk appended to it, indicating unsaved changes exist.
4. Choose File, Save (Smart Object). The menu item is not selectable. Alternatively, using the Ctrl+S shortcut does not work.

Closing the tab brings up a prompt confirming you want to close the file despite the unsaved changes. Even here, there is no option to save the changes when closing.

**Comment by photopea** [comment]
Hi, are you sure you are using the latest Photopea? Try reloading the website several times.

I could not reproduce that bug. Can you share your PSD with us? The bug should not be related to Browser or OS.

**Comment by verbiate** [comment]
Yes, I launched Photopea only minutes ago in Chrome, and opened Firefox specifically to test it. 

I tried with several freely available iPhone frame PSDs. Here's a link to one I tried: http://wikisend.com/download/665872/iPhone-5C-threequarters-view-Mock-up.psd

**Comment by photopea** [comment]
Perfect, I reproduced the bug! There is a problem with one of text layers. I will try to fix it tomorrow.

**Comment by photopea** [comment]
Ok, so I have fixed the problem with saving smart objects.

Thanks to your PSD, I have discovered several other bugs in Photopea. E.g. there was an incorrect formula for Color Burn blend mode, when performed on the GPU. Also the Stroke Layer Style with Fill Type: Gradient was still rendered as Color. I have fixed these too.

You may have one more problem. Your smart objects have a perspective transform applied to them, which Photopea can not handle yet. I have started a new issue for it: https://github.com/photopea/photopea/issues/86
