### ISSUE TITLE
It keeps on crashing? jgkdfkhkf?

### ISSUE THREAD

**Issue by chaotic-mangoes** [photopea/photopea#844]
Every five minutes it entirely crashes, deleting all my progress. I was really happy with how it functioned, but then after a day or so of using it it started doing this. I checked out how other programs like it worked under the same situations and none crashed. I also tried on a different internet connection, at a library and it still didn't work. :,(

**Comment by photopea** [comment]
Hi, could you please send us your file to support@photopea.com and tell us, what you did to make it crash?

Are you really sure it did not crash before, while doing the same thing?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
