### ISSUE TITLE
Integrate google fonts for font selection

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#846]
Some fonts found on google fonts aren't available in photopea right now, direct integration is better than adding manually

**Comment by photopea** [comment]
Google does not offer fonts in a way, which we could use. Please, tell us, which fonts are missing, and we can add them manually.

**Comment by hgs54371** [comment]
Open sans condensed light and light italic is not placed in condensed, 
Sue Ellen Francisco, just another hand, farsan, amatic sc bold, 
Sawarabi gothic, gaegu reg/light/bold, poor story, stylish, nanum pen script, gamja flower

These for now, Probably more later

**Comment by photopea** [comment]
Hi, I added all Google Fonts to Photopea.
