### ISSUE TITLE
Icon/image support on text-based buttons

### ISSUE THREAD

**Issue by jihchuan** [photopea/photopea#849]
It'll be great if there's icon/image support on the text-based buttons on the right sidebar (info, properties, etc.. as well as embeded plugins)

thanks

**Comment by photopea** [comment]
Hi, I updated the plugin specification. You can pass the Icon URL, which will be used as an icon in the right panel.  https://www.photopea.com/api/plugins

Example: https://www.photopea.com/#%7B%22environment%22:%7B%22plugins%22:%5B%7B%22name%22:%22Wikipedia%22,%22url%22:%22https://en.wikipedia.org%22,%22width%22:400,%22height%22:300,%22icon%22:%22https://en.wikipedia.org/static/favicon/wikipedia.ico%22%7D%5D%7D%7D
