### ISSUE TITLE
Desktop app

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#85]
Hi, this is my idea for future:
- app created by Electron (windows, linux, mac)
- context menu integration for OS (open in Photopea, allowed in setup & extensions)
- icon to desktop, os menu integration
- offline ready after install (weekly / manual check updates by some http read json object with version).
- local storage support (after unexpected close data can be loaded from app storage)

little example: https://github.com/Studioartcz/photopea-desktop

**Comment by photopea** [comment]
That is a great idea! But we must solve several obstacles first.

Right now, Photopea is linked to a huge set of 2000 fonts, which has about 300 MB. If we distribute them with a desktop app, the Photopea app would be too large. If fonts are stored on the server, Photopea can not work offline. What option is better?

**Comment by Studioartcz** [comment]
It's ok. I can image that app can be without non-system fonts and user can download fonts manually by some menu item.

**Comment by photopea** [comment]
Photopea needs to access fonts at a vector level. It means, that it needs the access to binary TTF / OTF files. Does electron allow to access system fonts as binary files?

I am afraid I will have to spend several days just by studying Electron docs. I have no experience with Node.js. @Studioartcz would you like to create the native version of Photopea? I can help you, if you need any help.

**Comment by Studioartcz** [comment]
Yeah, i will gladly help you with app. I think that electron have api access to system files, folders more than browser. I'll check.

**Comment by photopea** [comment]
Currently, Photopea has around 1 MB. But it also has a database of 200 MB of fonts. If we want it to work offline, all fonts must be distributed to each computer.

If you want, you can create a native app, which will have an iframe with Photopea (so it will not work offline). But right now, I don't have time or resources to develop and promote such thing.
