### ISSUE TITLE
Issue when resizing things

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#851]
It already happened to me two times. When I was resizing text and when I was resizing with Free Transform - in case it happens by accident that I release my mouse button when cursor is above History window it does the resizing action (correct) but then it moves back in history as if I clicked on history window item (problem).

**Comment by photopea** [comment]
Hi. The history item was selected after releasing the mouse over it (I don't know why). I changed it to "click" instead (the mouse has to be both pressed and released over the same item). Hope it does not break any functionality.
