### ISSUE TITLE
Ability to use system color picker

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#854]
This can enable the use of some default swatches available in system color picker

**Comment by photopea** [comment]
Hi. I don't know too much about how system color pickers work and what they offer. But why not! Where would you want this color picker to be placed?

**Comment by hgs54371** [comment]
"Use system color picker" As a toggle in current color pickers or in the More top drop down menu

**Comment by photopea** [comment]
Hi, I added a system color picker into a current Color Picker, next to the Hex textfield.

**Comment by hgs54371** [comment]
But the color on canvas isn't update with the system color picker yet

**Comment by photopea** [comment]
what color on canvas do you mean?

**Comment by hgs54371** [comment]
The color of items on canvas that's being adjusted, like text

**Comment by photopea** [comment]
Photopea can get a color from a system color picker only after you confirm it in a system color picker.

**Comment by hgs54371** [comment]
The button for open system color picker is updating, so why can't others

**Comment by photopea** [comment]
I think it depends on the OS. In my case of Windows 7, the button does not change until I press "OK" in a system color picker.

The native color picker sends the "change" event, which is detected by Photopea. Ask the authors of your OS to send the "change" event more often.
