### ISSUE TITLE
no logro ver el tamaño de mi pincel o borrador

### ISSUE THREAD

**Issue by ByAnonimaSexy** [photopea/photopea#855]
al seleccionar la herramienta pincel o borrador no logro ver la dimensión que tendrá 
me podrían ayudar

**Comment by photopea** [comment]
Hi. Are you not seeing a brush cursor (black circle) instead of mouse? Can you update your browser or try a different one?

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by ByAnonimaSexy** [comment]
Ya lo solucione!! 😄 solo borre todo el historial de mi navegador
