### ISSUE TITLE
Import images into project

### ISSUE THREAD

**Issue by kevintey** [photopea/photopea#858]
Hi,

Was wondering if we can have this simple yet convenient feature of importing images into project as layers? So we can save a few steps. Currently, if we open an image from File > Open, it opens as a new tab. We need to either drag it or 'Duplicate Into'.

Suggestion:
File > Import > (opens file explorer window) > Loads an image with transformation activated. User presses 'Enter' or '✔' to place the image. 'Esc' or '✘' to cancel placement.

Thanks!

**Comment by photopea** [comment]
Hi, there is a new feature "File - Open & Place" at www.Photopea.com .
