### ISSUE TITLE
Selecting multiple text and changing it

### ISSUE THREAD

**Issue by kevintey** [photopea/photopea#859]
Hi,

I tried to change multiple text layer's font (or other settings) but it doesn't work. Can this be enabled? Currently we need to select and change it one by one. (Even if multiple layers selected, it only updates one layer)

Suggestion:
Either Ctrl / Shift to select multiple layers > change settings > updates applied to selected layers.

Thanks!

**Comment by photopea** [comment]
Hi, I implemented it. It took me the whole day, as I had to remake many parts of the current Type Tool.

Thanks for suggesting it!

**Comment by kevintey** [comment]
Tested it. All good! :)
