### ISSUE TITLE
problem with zooming when layer style window is visible

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#863]
When I try to edit style in layer style dialog box, it is something wrong with artboard zooming. Shortcuts cmd + space, alt + cmd + space works randomly. Sometimes it works only zoom in, sometimes only zoom out.

Mac OS X (10.13.6)
Firefox 61.0.2

**Comment by photopea** [comment]
We made a decission some time ago, that if any window is opened, all keyboard events are given to that window. Now, I decided to change the behaviour, such that if there is a Super Tool (enabled by a key, and disabled after releasing a key), it gets keyboard events, too.
