### ISSUE TITLE
Effect order change in layer style window by drag and drop

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#866]
It is only a suggestion. 
Sometimes when I have many effects of that same category on a layer (gradients [+], strokes [+], shadows [+] etc.), I would like to change they order.
For example:

1. I made stroke 10px with fill type gradient black to white.
2. After that I added second stroke with 20px width and reverse gradient type.
3. I don't see first gradient (and I know why) but don't want to change all parameters in 2 strokes.

In simplest way it can be done with drag and drop like layer order change in layer pallete. But with limitation of order changing in one type of effect.

Bevel and Embos
Stroke[1]
Stroke[2]
Stroke[3]
Inner Shadow

Bevel and Embos
Stroke[3]
Stroke[1]
Stroke[2]
Inner Shadow

Doing it in that way, result it should to be compatibile with PSD format

**Comment by photopea** [comment]
Hi, I added a little arrow next to the Plus button. Press the upper part of the arrow to move the style up, or the down part to move the style down.
