### ISSUE TITLE
Tibetan Font is not rendered properly.

### ISSUE THREAD

**Issue by sonamdawa101** [photopea/photopea#869]
Before putting this issue. I would like to greeting you guy(s) for making this wonderful webapp. Fantastic. Love your work.

I used Tibetan Language. After loading [Tibetan font](https://disq.us/url?url=https%3A%2F%2Farchive.org%2Fdownload%2Fbodyig%2Ffonts%2FHimalayaFonts%2Fhimalaya.ttf%3AgnzmNTOz0dF1tEpb0nv27hLjhdM&cuid=2549616) and typing the following text 
ཀུན་གྱིས་བོད་ཡིག་བསྒྲིགས་རྒྱུར་
The text is displaying but not rendered properly. 

I have a screenshot below where I have made comparison with same text typed in photopea and in a notepad. The text in the notepad is correct.

Kindly check if that could be solved. 

![compare](https://user-images.githubusercontent.com/36448436/45256630-db54fd00-b3b6-11e8-9f66-51a21b09c6a4.png)

**Comment by photopea** [comment]
Hi. It was solved and it should work well now. Thanks very much for such a great description of the problem! :)
