### ISSUE TITLE
Export as PDF not working

### ISSUE THREAD

**Issue by sonamdawa101** [photopea/photopea#871]
I have added some text with red solid color clipped on it. After File>Export as> PDF , it just showing the solid red color and not the final look.

I have tried with vector shape and solid color cliped on it. To export as pdf the same issue. 
I have screenshot attached below.
![export as pdf](https://user-images.githubusercontent.com/36448436/45256789-2d971d80-b3b9-11e8-8f16-ce74cd5c7dc8.png)

**Comment by photopea** [comment]
Hi, Photopea can not export Clipping Masks into PDF at the moment :(  The whole PDF export is more like an experimental feature, it rarely gives a result identical to the PSD.

Please, apply the red color to the actual text layer, or choose "rasterize all" in the PDF export window.
