### ISSUE TITLE
Incomplete unicode font charset

### ISSUE THREAD

**Issue by doodlewind** [photopea/photopea#873]
Hi, in #797 we solved inputing issue with Chinese, for now I can see another point that can be optimized:

With "Droid Sans Fallback", I can only render unicode chars like `你好` in Chinese or `にほん` in Japanese (so even the "Preview" image in the font picker for this font does not display correctly). While with all other fonts, only ASCII chars are supported. wondering is this expected? If I have local TTF font, can I pick it into and use it in browser environment?

**Comment by photopea** [comment]
Hi, the Droid Sans Fallback seems to not support Latin characters, but some other fonts may support both. Choose Chi-Jap-Kor in the font filter menu and try some other fonts with CJK support.

Yes, you can load your own fonts (OTF/TTF) from your computer. Just use File - Open, or drag and drop the font into Photopea.
