### ISSUE TITLE
Step backward/undo in liquify filter

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#875]
Rather than reconstruct or smoothen that apply undo as burshes, normal Step backward/undo that apply undos as whole steps is more helpful for liquify trying

**Comment by photopea** [comment]
Hi, I implemented the history of up to 50 steps. It can be used with Ctrl + (Shift / Alt) + Z.

I also moved the OK button from the bottom to the right part, so there is more space for the image.

**Comment by hgs54371** [comment]
Can also add dedicated icons for mobile device browser that lack physical keys

**Comment by photopea** [comment]
Actually, the list of features, which depend on a keyboard (so can not be used on devices without one) is much much longer ...
