### ISSUE TITLE
Freeze/thaw area function in liquify filter

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#876]
This function is often used, but hasn't available yet

**Comment by photopea** [comment]
I don't think this is such important feature. If you deform some part by mistake, you can always use Reconstruct tool on it.

**Comment by hgs54371** [comment]
It is used for example to deform the whole face at once but leave the eye, nose, mouth intact/in place, in order to estimate the overall result better/faster While deforming, it’s better to freeze them in place first than to reconstruct them back afterwards Everytime
