### ISSUE TITLE
Brush cursor in liquify filter shown as fixed sized square after around size 200

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#877]
Brush cursor size in liquify filter larger than around 200 all shown as fixed sized square

**Comment by photopea** [comment]
Hi, it is a limitation of your browser.

https://bugs.chromium.org/p/chromium/issues/detail?id=591980
https://bugzilla.mozilla.org/show_bug.cgi?id=1253573

There is nothing we can do about it :( Please, if you know anybody who can change it, let them know!
