### ISSUE TITLE
Push left/right tool in liquify filter for apply push uniformly along a line/edge

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#878]
This one is useful, but hasn't available yet, also hold option/alt for reverse direction

**Comment by photopea** [comment]
I wanted to create it, but I was too lazy to draw a new icon.

I made this tool. But the icon is not that good I think :(

**Comment by hgs54371** [comment]
Can also add a checkbox for mobile device browser that lack modifier key

The icon is easier to understand than the one in photoshop
