### ISSUE TITLE
Tibetan Translation up 72% done. Kindly add Tibetan Language option from photopea interface

### ISSUE THREAD

**Issue by sonamdawa101** [photopea/photopea#879]
I have done the Tibetan translation for the photopea upto 72% today. Kindly can you add option to add Tibetan Language selection for the photopea interface. 

I think I will finish up to 100% by tomorrow. 

Thank you
![translation](https://user-images.githubusercontent.com/36448436/45318162-b3ea6580-b559-11e8-8639-7f9110b0fd24.png)

**Comment by photopea** [comment]
Hi. If you are going to finish it to 100%, I will add it once it is at 100%. Thank you very much! :)

**Comment by sonamdawa101** [comment]
### hi photopea, 
Tibetan Translation upto 100% done !

hurray

**Comment by photopea** [comment]
Ok, perfect, thank you very much! I just added your translation into Photopea.com !

Note, that if you want to change any translations, you can do it at the same page, and I will update it :)

**Comment by sonamdawa101** [comment]
Thank you so so much !

**Comment by sonamdawa101** [comment]
### I found some mistake and already made correction and changes in Tibetan Translation. Hope you can update.

**Comment by photopea** [comment]
Ok, I updated it. Thanks! :)
