### ISSUE TITLE
Take picture close

### ISSUE THREAD

**Issue by Studioartcz** [photopea/photopea#88]
Hi, 
how can i close this window?
Close button not working.

**Comment by photopea** [comment]
Hi, when I open Take picture, I can close it right away. What exactly did you do?

**Comment by Studioartcz** [comment]
Here is a situation when close icon not working:

![image](https://cloud.githubusercontent.com/assets/3184228/17741541/e2913928-649c-11e6-8e63-2b18efe23486.png)

**Comment by photopea** [comment]
Do you have any errors in a web console?

**Comment by Studioartcz** [comment]
Yes, here are:

![image](https://cloud.githubusercontent.com/assets/3184228/17745339/bca27920-64ab-11e6-8cff-0cecda0b3125.png)

**Comment by photopea** [comment]
It should be fixed now.

I also made the video area  smaller, so it fits better onto small screens.

**Comment by Studioartcz** [comment]
It works.
