### ISSUE TITLE
Kindly add these Tibetan Fonts

### ISSUE THREAD

**Issue by sonamdawa101** [photopea/photopea#881]
We have been testing and found that it really work very smoothly with Tibetan script. Now we feel that it would easier for us to have Tibetan fonts within the font selection rather embedding each time.

**Therefore kindly can you add the following 14 Tibetan Fonts.** 
One font is from Google Noto Sans Tibetan and the other 13 is free to use fonts created and freely distibuted by Ven. Lobsang Monlam. These 13 fonts has already been upload in Linux Debians under CC license.

### I have the fonts download link: here: https://goo.gl/p8Dnyz

Thank you :-)

**Comment by sonamdawa101** [comment]
I am also planning to prepare a tutorial about Photopea.com and Tibetan Script on facebook and youtube channel. Would be wonderful if all the fonts being add in the font list. 👍

**Comment by photopea** [comment]
Hi, I added your fonts. You can filter out only Tibetan fonts, if you check Tibetan in the filter on the right.

**Comment by sonamdawa101** [comment]
That's really fast ! Thank you :-)
