### ISSUE TITLE
Requesting Color Mode for future update.

### ISSUE THREAD

**Issue by sonamdawa101** [photopea/photopea#882]
Any thoughts about including Color Mode, such as CMYK, Grayscale, Labcolor option in future. This would be very useful and can turn photopea not only for quick web edit but also for printing and publication.

Wonderful to have this feature in future.

**Comment by photopea** [comment]
Hi Sonam, Photopea is supposed to work only in sRGB mode, and all other modes can be converted to or from sRGB. Do you have any specific problem, which you are dealing with?

**Comment by sonamdawa101** [comment]
I am working in a publishing house and most of time we need to send PSD and images in CMYK format to the printer. I am just wondering if CMYK convertion is there in photopea. Or in future are you going to 
plan or think about it.

**Comment by photopea** [comment]
Are you sure the printer accepts PSD images? I think PDF or EPS are more common for printing.

**Comment by sonamdawa101** [comment]
Yes, PDF is to be send but images (including PSD and any other format) embeded in the PDF should be CMYK.

**Comment by photopea** [comment]
CMYK color mode does not mean anything. You would need the Color Profile (ICC file) from your printer to be able to convert the image into their profile. Each printer may use different ICC profile, so you would need many ICC profiles, to convert graphics separately for each kind of a printer.

In terms of the information, any image can be converted between sRGB and any CMYK profile at any time, without losing any information.

Your printer should be able to convert the PDF / PSD files from sRGB into their own CMYK by themselves. It seems stupid to me to request users to use any specific color profile.

**Comment by sonamdawa101** [comment]
Thank for supporting Tibetan on Photopea.
I have made a tutorial about photopea on youtube, facebook and my website.

Links: https://youtu.be/hGPI8wDx1R8
site; http://www.sonamdawa.com/2018/09/photopea.html
fb: https://www.facebook.com/hisonamdawa
