### ISSUE TITLE
PDF upload error

### ISSUE THREAD

**Issue by Mhzta** [photopea/photopea#883]
Hi, 

When opening a pdf document it opens with inverted colors, effect which cannot be fixed. Tried with multiple pdf, which actually used to work 2 weeks ago.

Thank you

**Comment by photopea** [comment]
Hi, can you please attach your PDF here, or send it to support@photopea.com ?

**Comment by Mhzta** [comment]
Sure, please find two of the files I tried. As mentioned, used these exact two about 2 weeks ago and it worked fine.

[E_A5_Dinitial_White_No_Price_260917_PRINT.pdf](https://github.com/photopea/photopea/files/2371298/E_A5_Dinitial_White_No_Price_260917_PRINT.pdf)
[E_A5_Atelier_210317-V1_01.pdf](https://github.com/photopea/photopea/files/2371299/E_A5_Atelier_210317-V1_01.pdf)

**Comment by photopea** [comment]
It should be fixed now. Thanks for letting us know!

**Comment by Mhzta** [comment]
It works indeed. Thank you so much for fixing this so fast!
