### ISSUE TITLE
Download As WMF and EMF 

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#885]
I use a lot Photopea for making SVG that then goes to presentations on PPT or Google Slides.  And both platforms use WMF or the updated EMF.

Normally i download the SVG from photopea and then convert it on CloudConvert.com

But I will be pleased if that can be achieved from within Photopea.

Of course is not a deal breaker, but i lose nothing by asking  :)

**Comment by sonamdawa101** [comment]
I also doing the same step SVG to cloudConvert then to EMF while working with PPT and vice versa. It would be fantastic to have these two format included within Phtopea.

**Comment by photopea** [comment]
Hi, the support for WMF and EMF was added: https://blog.photopea.com/photopea-3-7-wmf-and-emf-support.html

Could you try open your WMF / EMF files report possible problems?

**Comment by avagp** [comment]
I could not find WMF download.
And i got a error when trying to download a svg as a EMF.

![image](https://user-images.githubusercontent.com/11801254/46092779-0b104d00-c18c-11e8-8e4c-fbacfdf72db7.png)

**Comment by photopea** [comment]
It is not possible to export WMF, only EMF. The Save for Web window can not show a preview of EMF (since Photopea is not guaranteed to display it correctly, and a browser can not display it like SVG or PDF), but it  still should save a good EMF file.

**Comment by avagp** [comment]
Maybe you could change the warning sign. And explain that.

Is super stupid, but that warning prevent me to click the save button.  :P

**Comment by photopea** [comment]
There is no preview when you save PSD either. EMF is more like PSD than JPG.

**Comment by avagp** [comment]
I would prefer to not have a preview, rather than a error message on the
preview.

When you export as PSD, it automatically downloads the file, but the EMF
tries to render a preview which it cannot, and there is where the confusion
begins for the user.

In my humble opinion :)

**Comment by avagp** [comment]
I cannot open any :/

Here you have some:
https://drive.google.com/drive/folders/12EpSJa1IVIYLolMYNqNLjT9O_ehbV0s4?usp=sharing

**Comment by sonamdawa101** [comment]
> I cannot open any :/
> 
> Here you have some:
> https://drive.google.com/drive/folders/12EpSJa1IVIYLolMYNqNLjT9O_ehbV0s4?usp=sharing

I can open your WMF files with all the layer and shape intact in photopea. If , If you download your WMF (from google drive ) as pdf and then open it in Photopea.

If your WMF directly opened in Photopea then it become flattened.

**Comment by avagp** [comment]
Yes, i did the same and works.
Also you can open EMF files from the PC, but i cannot open WMF files from the PC though.

Even though, as is, is super useful for my work.

**Comment by sonamdawa101** [comment]
> Also you can open EMF files from the PC, but i cannot open WMF files from the PC though.

Any image format which doesn't show up preview I used to open it in msPaint. There are small programs that can be install just to preview WMF, webP, eps and many other. You can check this link also: https://blog.kareldonk.com/wmfpreview/

**Comment by photopea** [comment]
@avagp How can I download WMF files from your Google Drive? When I press Download, they are downloaded as xxxxx.wmf.jpg ( JPG files). Could you maybe attach them here in a ZIP, or send them to support@photopea.com ?

**Comment by sonamdawa101** [comment]
> How can I download WMF files from your Google Drive?

![new project 2](https://user-images.githubusercontent.com/36448436/46198493-392b9380-c32a-11e8-8b1a-079da21c9463.jpg)

**Comment by photopea** [comment]
@sonamdawa101 It still downloads a ZIP archive with JPGs :(

**Comment by sonamdawa101** [comment]
@photopea That's really strange. This morning I could download in its WMF format but now it is adding extra .jpg. Images are not longer WMF even if remove .jpg.  
I did try to download with other browser, it gives the same result (XXX.WMF.JPG). STRANGE.
@avagp could probably provide us another download link with all the file in one zip.

**Comment by avagp** [comment]
Try now, i uploaded a zip file

**Comment by photopea** [comment]
@avagp  Thanks Alvaro! All your WMF files should work well now.

**Comment by avagp** [comment]
Yes it does!

Yey!

Thanks to all your work :D

**Comment by avagp** [comment]
Hi, i was vectorizing a png (and it got really strange sometimes, i will leave the picture for you to try), but the important part is that the EMF file, was not recognized by google Drive, so it could not be open.

I used CloudConvert to convert the EMF into a EMF, and then uploaded to Google drive again, but now it recognized it! And could be opened.
![image](https://user-images.githubusercontent.com/11801254/46992059-cfa7d500-d0de-11e8-91b5-0ce70e433942.png)

So, i may think that there are something added to the file, because the size went from 10k to 22k.

Can you check this out?

PD: This is the PNG, try to vectorize it with 2 colors
![monitos de palo](https://user-images.githubusercontent.com/11801254/46992093-e3533b80-d0de-11e8-975a-ab2f4fd13401.png)

**Comment by photopea** [comment]
Hi Alvaro, I fixed the problem with vectorizing your PNG.

What do you mean by "opening EMF in Google Drive"? I uploaded several EMFs to GD (which were not made in Photopea), and there was no default app, that would allow me to view them.

Can you share your EMFs with me and tell me, what you did?

**Comment by avagp** [comment]
Ok.
Upload a EMF or a SVG to drive. Then right-click to open with, and select
cloudconvert.

If you don't have that app (that I believe is a default suggestion) you
will need to connect it to your drive by going to add-ons.

Anyway, after opened it with CloudConvert, select EMF as the output format.

After the convertion you will find a new EMF with the same name but could
be opened with Google draw.

If a vector file can be opened with Google draw you can use it there and on
PPT (Google slides).

Ask me anything if you need more explanation.

Cheers!

**Comment by photopea** [comment]
So you always use CloudConvert to convert EMF to EMF? Google Docs accept only EMFs from CloudConvert, but not other EMFs?

**Comment by avagp** [comment]
I always converted SVG from photopea to EMF to use them on PPT.

But when trying to use the EMF directly from photopea doesn't work :/

That is why I tried to convert from EMF to EMF in the first place.

My best scenario is to do a SVG on Photopea, expoeyit and being able to
open as gdraw immediately.

I don't know if it is Google drive the Looney one, or EMF files from
Photopea are missing something from the ones from CloudConvert.

**Comment by photopea** [comment]
So I converted the EMF to EMF in GDrive with CloudConvert, and the new EMF was openable in Google Draw.  I downloaded that new EMF (made by CloudConvert) to my computer, and uploaded it to GDrive again. And the same EMF was not openable by Google Draw  :/ 

So the problem is not in the EMF file, but in the way it is inserted to Google Drive.
