### ISSUE TITLE
These Special Keys unable to type in the Text Box

### ISSUE THREAD

**Issue by sonamdawa101** [photopea/photopea#886]
These special keys are not able to to type in the text tool
![special keys](https://user-images.githubusercontent.com/36448436/45403811-dbd0ea80-b679-11e8-9b8b-04e6674d5b97.JPG)

/
?
]
}
-
_
=
+

Thanks

**Comment by photopea** [comment]
Hi, these are the keys, that contain "+" and "-" on some keyboards. It is related to the fixing of yesterdays bug. So I removed "Ctrl" + "+" / "-" zooming when in a textbox. But you can still use Alt + Wheel.

**Comment by sonamdawa101** [comment]
Fantastic !
