### ISSUE TITLE
Image Size unit should B, KB, MB

### ISSUE THREAD

**Issue by sonamdawa101** [photopea/photopea#889]
While exporting, the image size is showing in Byte (B) only. Would be nicer if shown in B, KB and MB accordingly.
:-)
![b-kb-mb](https://user-images.githubusercontent.com/36448436/45506427-c8726c00-b7ac-11e8-84ee-8ccca9075c8a.png)

**Comment by photopea** [comment]
Hi, I made it show a shorter number (KB, MB ... depending on the size). There is also the exact number in Bytes (a little darker).

**Comment by sonamdawa101** [comment]
**wow ! Thank you so much.**
