### ISSUE TITLE
Copy to clippboard

### ISSUE THREAD

**Issue by landsman** [photopea/photopea#89]
Hi,

1) I have some project where i have layer and was select some area.
2) CTRL+C
3) Clipboard not change :(

**Comment by photopea** [comment]
Hi, what do you mean by "Clipboard not change" ?  Press Ctrl+V and you must be able to paste it as a new layer.

**Comment by Studioartcz** [comment]
No i didn't mean "paste", i want copy from layer to clipboard.

**Comment by photopea** [comment]
You mean copying image to a "system" clipboard? I think there is no web standard for that. You can either copy from PP into PP, or from outside into PP, not from PP to outside.

**Comment by Studioartcz** [comment]
Sure. Its pitty! 
I think that I was seen some services where offers copy to clipboard without flash.

**Comment by photopea** [comment]
From what I know, you can copy only the text into the system keyboard :(

**Comment by Studioartcz** [comment]
Yea i know about text too. 
I will try send question to stackoverflow.

**Comment by photopea** [comment]
2017 is here and it seems like we still can not copy images to a system clipboard :(

**Comment by photopea** [comment]
I will close it and wait, until there are new web standards.

**Comment by iivmok** [comment]
@photopea could you have a button to open the current image in a canvas, or a data-url, so at least right-click-copy manually would be possible?

**Comment by photopea** [comment]
Hi, it seems like standards are ready, so we will "unify" Photopeas clipboard with a systems clipboard.

**Comment by SebiTimeWaster** [comment]
awesome! that will make so man peoples life easier!

**Comment by the21st** [comment]
this is not working on MacOS + Firefox

**Comment by photopea** [comment]
@the21st I just tried Photopea in Firefox on MacOS.

 I was able to copy an image on another website and paste it into Photopea with Cmd+V.
I was able to copy parts of a layer in Photopea and paste them in Photopea.

What exactly is not working for you?

**Comment by the21st** [comment]
@photopea Creating a selection Photopea (e.g. cmd+A) and clicking Edit > Copy is not copying the image to my clipboard.

**Comment by photopea** [comment]
Firefox does not allow websites to put images into a clipboard. It is available only in Chromium - based browsers right now (Chrome, Edge, Opera). You can report it to Firefox, if you want, or switch to another browser.

**Comment by the21st** [comment]
@photopea thanks! I had no idea. Will use Chrome for Photopea from now on 🙂
