### ISSUE TITLE
Tibetan Text/Paragraph goes beyong text box

### ISSUE THREAD

**Issue by sonamdawa101** [photopea/photopea#892]
Just want to let you know that your website is now spreading inside Tibet. ( you can check www.tibetitw.com)  I have friends inside Tibet and they said they can open your webapp and finds fantastic. With the same they found one minor issue and asking for fix and one small suggestion.

**The issue is:** 
when we typed a paragraph. The text goes beyond the text area. I have the screenshot below.

**Below I have sample Tibetan text for test**
ཆོས་ལུགས་ཀྱིས་ཡོད་ཚད་ཐག་གཅོད་ནུས་པར་འདོད་པ་དང་། མིའི་འདོད་བློ་མཐའ་དག་ཆོས་ལུགས་ཀྱིས་བསྐང་ནུས་སྙམ་པའི་ཀུན་སློང་ཞིག་རང་རེ་བོད་མི་རྣམས་ལ་ཡོད་པ་རེད། དུང་ཞེན་དེ་འདྲ་ཞིག་ཡོད་པའི་སྟབས་ཀྱིས་མི་ལོ་སྟོང་ཕྲག་གཅིག་ལྷག་རིང་ང་ཚོས་ཡོད་ཚད་ནས་ཡོད་ཚད་ཆོས་ལུགས་ཀྱི་ཕྱོགས་སུ་ཕུལ་བཞག་པ་རེད། ཐ་ན་དེ་རིང་ངས་འདི་ནས་ཆོས་ལུགས་ཀྱིས་ཡོད་ཚད་ཐག་གཅོད་མི་ཐུབ་པ་དང་། མིའི་འདོད་བློ་མཐའ་དག་བསྐང་ནུས་ཀྱིན་མ་རེད་ཟེར་ནས་བཤད་པ་དེ་ཡང་བློ་ཡུལ་ལ་མི་ཤོང་མཁན་ཡོད་སྲིད་པ་རེད། 

**The Suggestion is:**
In the Tibetan font list the name is not shown complete. The initial words is same and they can't differentiate the fonts unless the font preview sometime works.

Thank you :-)

**The Screenshot**
![new project](https://user-images.githubusercontent.com/36448436/45582466-129f3e80-b8ce-11e8-9b60-0dd9dbdbf26a.png)

**Comment by photopea** [comment]
Hi, so what are the rules for breaking lines in Tibetan? In Latin, the line can be broken after a space " ". Is there any character in Tibetan, after which it is safe to break the line? Or can the line be broken after any character?

**Comment by photopea** [comment]
Ok it seems like we can break lines after Tsheg: http://w3c.github.io/i18n-drafts/articles/typography/linebreak.en#sec_tibetan  right?

**Comment by photopea** [comment]
I think I fixed the line breaking. Also, when you hold the mouse over the font name, you can see the full name.

**Comment by sonamdawa101** [comment]
Perfect, PERFECT, **PERFECT** 
screenshot below
THANK YOU SO MUCH !
![ps tibetan](https://user-images.githubusercontent.com/36448436/46454200-ab84f380-c7c2-11e8-91dc-55584c38f390.PNG)
