### ISSUE TITLE
Layer name not centered vertically in layers panel in safari on iPad

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#893]
![af224a1e-f09a-40d0-815c-2d096dfc8788](https://user-images.githubusercontent.com/36803688/45626475-42af3300-bac2-11e8-9e0b-827d82366fe6.jpeg)

The text is aligned to bottom and cropped as showned in the screenshot

**Comment by photopea** [comment]
Hi, are you using the latest iOS with the latest Safari? This used to be a bug in the old Safari.

**Comment by hgs54371** [comment]
Yes, latest ios, and safari isn’t updated separately

**Comment by photopea** [comment]
It looks well both in Chrome and Firefox, so I think it is a bug in Safari. Please, report it to Safari developers.
