### ISSUE TITLE
Content of character panel not update with text layer selection switch

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#894]
Currently on safari iPad, not sure if also exist on others

**Comment by hgs54371** [comment]
I found this seems to be that it was not in text tool

**Comment by photopea** [comment]
This behaviour is the same for all devices and browsers.

There is something called a Global Text Style. That is what you see in Character / Paragraph panel. Currently, only Type Tool can notice, that you selected a different text layer, and update the GTS according to its style. Also, only the Type Tool can notice, that GTS was updated, and update the selected text layer accordingly.

The solution would be to make this work always, no matter what tool is selected.

We have a related problem with adding guides, which works only with a Move tool.

**Comment by hgs54371** [comment]
" Font style change have no canvas update after adjusting tracking
And after a font size adjustment, it returned normal, on safari iPad "

This one is related but not the same, in this one it happened without leaving the text tool

**Comment by photopea** [comment]
I think it is fixed now.
