### ISSUE TITLE
Two hex field in color picker on safari iPad

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#896]
![52f80be8-a27d-41ac-86a2-eb3dfdf959aa](https://user-images.githubusercontent.com/36803688/45637205-772fe880-badc-11e8-8437-4b0b0b3c13b1.jpeg)

As shown in the screenshot

**Comment by photopea** [comment]
Hi, the second item is a native color input dialog: 

    <input type="color" />

So users, who are used to use a native color picker of their OS, could use it even from Photopea. iOS seems to have just a textfield, which we can not do anything about :/
