### ISSUE TITLE
Text field for angle and scale in properties panel too short on safari iPad

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#897]
![5cdbfd0b-1543-48c8-8f1c-77aff5dca063](https://user-images.githubusercontent.com/36803688/45637837-07226200-bade-11e8-9c3b-df443e3fad37.jpeg)
Angle and scale for gradient and pattern fill layers

**Comment by photopea** [comment]
Hi, is it better now?

**Comment by hgs54371** [comment]
Yes, it's better now

**Comment by photopea** [comment]
ok thanks!
