### ISSUE TITLE
Text field for position and size in free transform tool bar too short on safari iPad

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#898]
![a985a389-efe2-47fb-b029-8f3bde4e0449](https://user-images.githubusercontent.com/36803688/45639023-73eb2b80-bae1-11e8-9856-e3764d75ced4.jpeg)
As shown in screenshot

**Comment by photopea** [comment]
Hi, these text fields look absolutely the same in every browser and device. We made them narrow, so that they fit even when the screen is small. They are still usable.
