### ISSUE TITLE
Hold n drag for re-arrange layer order in layers panel not working on safari iPhone

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#899]
Select and hold a layer, it will not float and move with drag like safari iPad can

**Comment by hgs54371** [comment]
Layer effects also can't be deleted with drag n drop like safari iPad can

**Comment by kappische** [comment]
Maybe it would make more sense to add something like the three dots/lines that is common on android/ios to indicate that something is draggable? 

https://ux.stackexchange.com/questions/26121/what-is-a-good-visual-cue-for-drag-and-drop-for-reordering-a-list-of-items

**Comment by photopea** [comment]
Drag-and-drop is finally supported in mobile Chrome since two days ago (which is our most frequent mobile browser), so it is doable now.
