### ISSUE TITLE
Crop to size or by ratio

### ISSUE THREAD

**Issue by woodytopsail** [photopea/photopea#90]
It would be useful to be able to set a width and depth in pixels for the crop tool like you can in Photoshop. Whatever you select is cropped to that size. Or, at least set a ratio like 4x3 or 16x9 so you can then change the canvas size and end up with what you want.

**Comment by photopea** [comment]
Hi. To crop by size, there is an option Image - Canvas Size. Also, you can hold the Shift while dragging corners to preserve aspect ratio. Isn't it enough?

**Comment by woodytopsail** [comment]
Image-Canvas Size trims off the edges of the picture like trimming the crust off a sandwich. What I would like to do is set a desired pixel size, like 600 x 300, and then when I select an area, say 1200 x 600, that area is cropped and resized to 600 x 300.

**Comment by photopea** [comment]
Image-Canvas Size does not trim any data in Photopea.  BTW. I have added the new option Image - Image Size, which "scales" the image.  Both Canvas Size and Image Size have an option "Preserve aspect ratio".

I think it is not right to add scaling into Crop tool. Cropping must only "crop" the image, without changing the size of the content.  If you need to crop lots of images quickly, it is better to add some batch processing, what do you think?

**Comment by woodytopsail** [comment]
Sometimes I need a picture that is 800x600 pixels to go into a Wordpress photo gallery. I would like to be able to set that in my cropping tool, or at least that ratio, so that I can crop the best part of the picture and leave out the other parts. If I simply crop freehand, and then re-size, each picture will be a slightly different shape only because it's hard to be so exact.

**Comment by photopea** [comment]
What about setting 800x600 with Image - Canvas Size and then moving the picture (a single layer) with Move tool (which is already enabled at the beginning) ?  Canvas Size does not trim pixels.

**Comment by photopea** [comment]
Info panel was added. It shows the dimensions of the cropping rectangle as you edit it.
