### ISSUE TITLE
Gradient map adj shown as gradient fill in properties panel after adding a following gradient fill layer

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#900]
Gradient map adj shown as gradient fill in properties panel and not working, with and without the presence of a following gradient fill layer (both cases encountered)

related:
Gradient map adj layer turned into gradient fill layer after 2times+ gradient adjustments with presence of a following gradient fill layer

**Comment by photopea** [comment]
Hi, I tried to do some experiments and the Gradient Map Adj. layer never "turned into" a Gradient Fill layer.

I really think, that you just got confused. When you have a Grad. Fill layer, and put Grad. Map Adj. layer over it, you just see the gradient beneath recolored.

If you are sure about a bug, please, tell us more about how to reproduce it, or send some screenshots.

**Comment by photopea** [comment]
I tried it several times and it never happened :( Is there anything special what you do?

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by hgs54371** [comment]
Not anything special, just happened as described
