### ISSUE TITLE
Repeat edge pixels for blur filters

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#904]
A checkbox to toggle repeat edge pixels for blur filters like gaussian blur, to keep edges look consistent

**Comment by photopea** [comment]
Hi, what exactly do you mean? What should the option do? Have you seen it in any other software?

**Comment by hgs54371** [comment]
Just google "repeat edge pixel", there will be infos for this, 
For example : https://bit.ly/2xxWeou
This will fill up the transparent edges that's caused by the blur, it exist in blur effects in adobe ae and pr

**Comment by photopea** [comment]
I think that now, Photopea does exactly what you expect, wen bluring images (no transparency blurs on the edge of canvas, transparency blur inside the canvas).  If you open a JPG photo with no transparency, nobody wants to have semi-transparent or black edges after the blur. Just like when you open a PNG with a circle in the middle, you don't want the blur to be cropped into a square around the circle.

**Comment by hgs54371** [comment]
For blur glass effect the blur needs to stay in the original bounds, but right now there's no flexibility to toggle this

**Comment by photopea** [comment]
These filters are defined in a PSD format (e.g. for Smart Filters). If we add new parameters to them, PSDs from Photopea would not work correctly in other PSD editors.

I think you can use masks in your case.
