### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by kkbhe** [photopea/photopea#907]
Your program caused my computer to crash. I was working on a project and didn't save. i need to know how to get this back please. I was so close to being done. This is for a project in my drawing class.

**Comment by photopea** [comment]
Hi, did the computer crash, or just the website crashed? Unsaved files can not be recovered in any way :(

**Comment by kkbhe** [comment]
The compupter crashed. 
I would suggest a notification that pops up saying to save their work. Just saying. Thanks anyways. I'll just try and get an extension.
