### ISSUE TITLE
Adjustments layer effect turn off when selecting layers with shift

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#909]
Like in the title.
Make few random adjustments layers over base layer with photo (with big visual changes).
Try to select first one from the layers panel and then last one with shift button to select all (f.e. to group all).
Visual effects turn off on artboard, but layers have still "eye" and should to be visible.

Mac OSX and FF/Chrome

**Comment by photopea** [comment]
Hi, every time you select an Adjustment Layer, the whole document is re-rendered only with layers below that adj. layer (layers on top of it are hidden). This image is needed to make a Histogram, which is shown in the Properties panel.

There was a problem, such that the layer was not re-rendered again with all layers. I think I fixed it.
