### ISSUE TITLE
Open Imagem

### ISSUE THREAD

**Issue by thiagosmari** [photopea/photopea#91]
Don't open the image

**Comment by photopea** [comment]
Hi, what exactly happened? Do you have problems with all files, or some specific file? Can you share your file with us?

**Comment by thiagosmari** [comment]
Hi, i trie to open one simple image and nothing happen, i will send the imagem to you
![img_1722](https://cloud.githubusercontent.com/assets/6173728/17961102/b2174cb4-6aa1-11e6-92a9-4cfc61281915.JPG)

**Comment by photopea** [comment]
There was an error in JPG decoder, that we use.  The bug is related to this issue: https://github.com/notmasteryet/jpgjs/issues/34

I used the recommended fix and it works now. Thank you for reporting it :)
