### ISSUE TITLE
Color fill layer turned to empty layer after convert to smart object or add a mask

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#912]
This happened on safari iPhone with many background tasks open, it returned to normal after a page refresh

**Comment by photopea** [comment]
Hi, I could convert a Color Fill layer into a smart object without any problems. Are you sure about it?

Color Fill layer is already created with a raster mask. You probably added a vectror mask (hide all) to it. You need to draw vectors into this mask to make some parts visible.

**Comment by hgs54371** [comment]
I just tried it with safari iPad now, on first load it turn every color fill into empty layer with convert to smart object, also after page refresh it returned normal

Also on mac :
When a layer with raster mask selected the add mask icon still shown as add Raster mask, 
After click on it, the vector mask doesn't add correctly, I also tried it on gradient fill, got empty either, also render the layers panel somewhat frozen(can't select another layer, layer highlight is dead)

Also shown in vid
[empty.mp4.zip](https://github.com/photopea/photopea/files/2402415/empty.mp4.zip)

**Comment by photopea** [comment]
Hi, what do you mean "after page refresh it returned normal" ? No document should be opened after refreshing a page.

**Comment by hgs54371** [comment]
By normal I mean it turn to smart object correctly with that command, without turn to empty

**Comment by photopea** [comment]
BTW when you add a vector mask to any layer, it becomes completely hidden, until you draw something into a vector mask. A fill layer with a vector mask is a "vector shape" (has a little square in the thumbnail), so your video is correct.

**Comment by hgs54371** [comment]
Why not leave it visible until the first path is drawn, like it does in photoshop, also show the vector mask after raster mask icon like it does with other layers, for a more consistent look, to avoid confusion

**Comment by photopea** [comment]
When you have a fill layer and a vector mask, I think it makes sense to call it "a shape" and use just one thumbnail image.

**Comment by hgs54371** [comment]
But draw path in it doesn't reveal the fill

**Comment by photopea** [comment]
Yes, it does (make a new fill layer, add vector mask (it becomes empty), draw into it (Pen tool, Rectangle, Ellipse ...)  - it draws shapes into that shape layer)

**Comment by hgs54371** [comment]
I draw path with fill off in tool bar, they show empty, only when fill turned on, the fill layer reveals

**Comment by photopea** [comment]
Hi, what do you mean? Do you mean the tool bar or the top bar?

**Comment by hgs54371** [comment]
![screen shot 2018-09-22 at 3 09 33 am](https://user-images.githubusercontent.com/36803688/45901286-fee76100-be14-11e8-8430-799483d4afda.jpg)
![screen shot 2018-09-22 at 3 09 44 am](https://user-images.githubusercontent.com/36803688/45901300-0575d880-be15-11e8-9093-92c69bc0c5b5.jpg)

**Comment by photopea** [comment]
That is true, the shape does not have any fill, when you set the fill to No fill.
