### ISSUE TITLE
Open sans condensed light/italic isn't put together with bold

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#915]
They are misplaced

**Comment by photopea** [comment]
It is quite hard to understand your reports, it is always such a puzzle for me :D  Please, spend more time on describing your problems. I don't mean longer descriptions, but more precise.

Do you mean, that Open Sans and Open Sans Condensed are two different items in a Font Family List? Actually, font families were defined by a font author. Please, report this to authors of OpenSans, to make Condensed the same font family as the rest of the fonts.

**Comment by hgs54371** [comment]
In font list there are 
1. open sans
2. open sans condensed

Open sans condensed bold is put in 2, this is right
But Open sans condensed light and italic is put in 1, other than with the condensed bold version in 2

It's not mixed like this in google font
