### ISSUE TITLE
Opacity not on same line with blend modes

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#917]
![screen shot 2018-09-21 at 3 23 39 am](https://user-images.githubusercontent.com/36803688/45841912-c9c40b80-bd4d-11e8-8e5a-9b6b03550c8f.jpg)
It's on the 2nd line

**Comment by photopea** [comment]
Hi, it seems your browser makes the Drop Down menu wider, than other browsers. There is nothing I can do about it :(

**Comment by hgs54371** [comment]
They were in line with the blend mode Before the Separators were added, on firefox, safari and mobiles

**Comment by photopea** [comment]
What about now? Is it better?

**Comment by hgs54371** [comment]
Still on 2nd line

**Comment by photopea** [comment]
I think it does not mind. You can resize the right sidebar, too.

**Comment by photopea** [comment]
I think I fixed it now.

**Comment by hgs54371** [comment]
Yes, they're inline now
