### ISSUE TITLE
unable to open new psd

### ISSUE THREAD

**Issue by SnehaSahu05** [photopea/photopea#92]
1st 2 times I was able to import psd and also edit the same. However subsequent to that, now I am unable to open any psd file, no error msg, no crash notification. Simply nothing happens after selecting file, rather my browser hangs for some time, and then every thing gets normal within 2-3 minutes. But psd file does open still.

**Comment by photopea** [comment]
Hi, how large is your PSD file? Can you send it to me to support@photopea.com ?

**Comment by SnehaSahu05** [comment]
Its 411 mb. However I cannot share the file

**Comment by SnehaSahu05** [comment]
The one I was able to upload was 168mb.
But 411mb I could not.

**Comment by photopea** [comment]
Try to disable "WebGL" at the top. Then open your file. Does it work now?

**Comment by SnehaSahu05** [comment]
No, still the same.
168mb file works fine, but not 411mb file (with "WebGL" disabled)

**Comment by photopea** [comment]
It is probably because of limited memory. Photopea loads and parses the whole file in RAM memory, it may need up to 10x more free RAM, than the size of your file. Do you have many layer styles in the file?

**Comment by SnehaSahu05** [comment]
yes, there are many layers.

**Comment by photopea** [comment]
Ok, so it seems like PP supports only files up to about 200 MB now. The size limit is a large issue and it has no quick fix. Native apps can store some data on a hard drive, when there is no free RAM, but webapps can not do that (yet). I will close it for now, but will think about it in the future.
