### ISSUE TITLE
Wrong button name on https://www.photopea.com/translate/

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#921]
Next to English there is Japanese button with polish translation. On polish button there is some... scandinavian?

**Comment by photopea** [comment]
Yeah, this happens from time to time (like twice a week). I didn't figure out why it happens. So I just manually return to the latest version, that was still ok.

**Comment by MichalSZZ** [comment]
Ok. Thank you. 
I was looking for one very very wrong translated word, and without any search it is hard to find in fast way (was on ~400 position) :)
Second thing. Some words are hard to translate without any context.

But anyway - that is great functionality! I have change few translation to better one.

**Comment by MichalSZZ** [comment]
Yes, but some phrases are very general and/or are used in more that one place.
I think i'm quite good of photoshop user and try to be same good in Photopea ;)
