### ISSUE TITLE
New project shown only interface background(no canvas) with three projects opened

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#922]
Add new layer and others also not responsive, only shown glitched when switch back from another opened project

In addition to the three projects opened in photopea, there are also many other tabs open, likely ram used up, better ram management needed ?

![screen shot 2018-09-21 at 7 10 38 am](https://user-images.githubusercontent.com/36803688/45851435-7eb9f080-bd6d-11e8-8064-53089a507c27.jpg)

**Comment by photopea** [comment]
Hi, do your documents work, if you open them separately?  How much RAM does your device have?

**Comment by hgs54371** [comment]
I can open another photopea tab and open/work with additional projects in it, also open other web tabs without problems. (16g)
It seems like the capacity of a Single photopea tab is quite limited

**Comment by photopea** [comment]
Photopea uses as much RAM as the browser lets it to use. What browser do you have? Did you see any errors in a web console?

**Comment by photopea** [comment]
I don't know how to deal with it. I could not reproduce it on any of my devices.
