### ISSUE TITLE
New smart object via copy

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#923]
Sometimes it is necessary, when you have few duplicate of one smart object (who have many layers and modifications inside of it) and want to change something inside only one of it.

In simple words. Another clone but without reference to anothers.

**Comment by MichalSZZ** [comment]
https://www.youtube.com/watch?v=ash1ohZFZwk he's talking in this video about principles of this feature

**Comment by photopea** [comment]
Ok, it was implemented.
