### ISSUE TITLE
Update text layer name after edit text content

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#925]
As in the title. 
Now it is hard to find text layers after content change. Layer name should correspond to start of content of text layer

**Comment by photopea** [comment]
Are you sure about this? I think, if the person decides to give a text layer some nice name, we should not rewrite it.

**Comment by MichalSZZ** [comment]
Yes, I'm sure. But I will try to be more precise in description, because in my last comment, there wasn't one, very important information. Sorry for that. 

When you don't change layer name manually, it works like I wrote in description.

But when you change name in layers palette, it wont change automaticaly after edit content of text. It will be still yor text layer name.

**Comment by photopea** [comment]
Ok, it was implemented! :)
