### ISSUE TITLE
Eyedroppers in curves adj for quick white balance

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#929]
Just found that this function hasn't available yet

**Comment by photopea** [comment]
I noticed, that in Photoshop, the eyedropper for Curves can do many different things (depending on what you select in Curves). Do you think we need all of them?

**Comment by hgs54371** [comment]
Do you mean double click on those eyedroppers can open color picker to choose the target colors other than pure white black and grey

**Comment by photopea** [comment]
I think we can discuss this in https://github.com/photopea/photopea/issues/951
