### ISSUE TITLE
Can't open psd

### ISSUE THREAD

**Issue by anboo** [photopea/photopea#93]
pp.js:643 Extra parameter Spcn
pp.js:322 unknown layer tag: lrFX, size: 396
pp.js:322 unknown layer tag: sn2P, size: 4
2pp.js:322 unknown layer tag: lrFX, size: 396
pp.js:911 Parsing time: 39
pp.js:87 Alert: Font Liberation Sans Bold loaded.
pp.js:322 unknown layer tag: vogk, size: 304
pp.js:322 unknown layer tag: vogk, size: 132
pp.js:318 Object {type: 3, length: 14, pd: 1, iD: 2} 7
pp.js:318 Uncaught errorRa.pC @ pp.js:318ma.aL @ pp.js:337ma.zc @ pp.js:336ba.ZK @ pp.js:354ba.XK @ pp.js:353ba.zc @ pp.js:347ja.Jx @ pp.js:911ja.Dy @ pp.js:909

**Comment by photopea** [comment]
Can you please share your PSD file? You can send it to support@photopea.com

**Comment by photopea** [comment]
Fixed.
