### ISSUE TITLE
Add a 'smile' tool

### ISSUE THREAD

**Issue by HanSchmitz** [photopea/photopea#933]
Sometimes people are on photo's without a smile (=looking tired or sad).
Could you add/create a tool to lift the corners of the mouth to give those people a kind of smile and thus a friendlier face?

**Comment by photopea** [comment]
Hi, I think it is possible to do with a Liquify filter. Have you tried it?

**Comment by photopea** [comment]
I am closing it, as I think the Liquify filter is sufficient to make people smile.
