### ISSUE TITLE
Unresponsive after using patch tool

### ISSUE THREAD

**Issue by MicTarHal** [photopea/photopea#936]
Hi,

after using patch tool to replace around 3% of the picture at once, Photopea freezes.

The preview, while moving cursor works. However after releasing the mouse button, the page becomes unresponsive. And it does not appear to come back even after several chrome Wait attempts.

The area is replaced entirely, with no overlap of previous pixels.

**Comment by photopea** [comment]
Hi, I made the Patch tool about 15% faster. But then I kept trying and accidentally made it 30 times faster.

E.g. previously, patching the area 300 x 300 px took 45 seconds. Now, it takes just 1.5 seconds.
