### ISSUE TITLE
Make W & H in the Info panel show canvas size when nothing is selected?

### ISSUE THREAD

**Issue by ewnjtgouierg** [photopea/photopea#937]
I read you said that you made the Info panel in PP as a replication of the PS after someone's request.
I am not 100% sure, but I have a vogue memory of W & H showing the full canvas dimensions when nothing is selected in PS.
If I'm wrong (PS doesn't do this) - then it's just a suggestion.
b/c right now, if I don't mistake, canvas dimensions are not displayed anywhere.
You can find them opening menu ("Image/Canvas size..."), or better workaround is to select all with Ctrl+A, which still interferes with the work though

(Imagine that you have several big images of different dimensions open in PP, you want to normalize them for a slideshow etc., you switch between tabs looking at them and thinking about optimal size and various constraints, and it's a pain if you cannot just see the dimension right away)

**Comment by photopea** [comment]
I think it would be quite confusing to show the document size, when there is no selection. 

You can find the document size in Image - Canvas Size. You can also estimate it when Rulers are displayed. You can see the document size in the Info panel, if you press Ctrl+A (Select the whole document area).

**Comment by ewnjtgouierg** [comment]
Both workarounds you suggest I mentioned explicitly in my own OP - please don't be like a customer service of a big company :D (you know, when it feels that your message was not read))) I wrote it exactly because having to get by with these workarounds is a pain. 

Showing it when there's no selection MIGHT be confusing. Or not. I think user would very quickly realize what's going on, but I guess you have a point. I will try to check how it is in PS when I get a chance and post here just for the info.

**Comment by ewnjtgouierg** [comment]
Just checked, PS doesn't show canvas dimensions either. Oh well, I guess I'm a minority here
