### ISSUE TITLE
Opening Vector Smart Object no longer works

### ISSUE THREAD

**Issue by jonbp** [photopea/photopea#938]
When I go to double click the thumbnail of a Vector Smart Object in a PSD file, nothing happens.

![Screenshot](https://i.imgur.com/IapkRND.png)

Before, a new window would open that would allow me to download an SVG.

**Comment by jonbp** [comment]
Also, the download SVG button doesn't appear to work either

**Comment by photopea** [comment]
Hi, I think it is fixed now. Otherwise, please, always attach a problematic file (or send it to support@photopea.com ).

**Comment by jonbp** [comment]
Works for me, many thanks for all your hard work, such a great service!
