### ISSUE TITLE
Stroke and fill Path/Shape with a brush

### ISSUE THREAD

**Issue by imms93** [photopea/photopea#939]
I'm here again to ask for features but I can't help it, I love your work too much! I want to reproduce these two tutorials in Photopea: https://textuts.com/simple-bokeh-text-effect/ and https://icon-tutorial.livejournal.com/9445095.html. In both tutorials, there's a step when it says you have to choose a brush (or tweak an existing brush) and, after converting the text to a shape, stroke the shape with the brush selected. Unfortunately, in Photopea you can only stroke and fill a path with a solid colour, a gradient or a pattern. Stroke and fill gradient with a brush can lead to very nice effects like the ones in the tutorials I have linked above. Any chance you might add this feature in the future? Thank you and keep up the good work :)

**Comment by photopea** [comment]
Hi, I have added the options to fill and stroke a vector path. The buttons are at the bottom of the Paths panel.

I am sorry that you had to wait for three years.

**Comment by photopea** [comment]
![image (1)](https://user-images.githubusercontent.com/15955558/120893553-29ed5f80-c614-11eb-921c-1c0cd18e60db.png)

**Comment by MichalSZZ** [comment]
Wow! You are the best! Thanķs for that feature. Many people will be happy.

**Comment by imms93** [comment]
This is amazing, thank you so much!

Il giorno sab 5 giu 2021 alle 07:04:24 -0700, MichalSZZ 
***@***.***> ha scritto:

**Comment by PAEz** [comment]
How do I do this, I cant get it to work.
I click Pen, draw to points to create a straight line. Go to Paths. Click Stroke Path with Brush and it says Layer is not Editable.

**Comment by photopea** [comment]
Find a tutorial on how to do it in Photoshop, everything instruction for Photoshop works in Photopea.

Did you draw a Path or a Shape? see here: https://www.photopea.com/learn/vector-graphics

**Comment by PAEz** [comment]
Ah, sweet, got it now.
My problem was I didnt know the difference between a shape and a path.  When you select the pen tool its set to shape and I didnt notice the option at the top left until I read a photoshop tutorial (thanks for the suggestion).  There is nothing on the page you link to that mentions this.
As all ways, thanks for your quick response and help.
