### ISSUE TITLE
Problem on opening a recent image file again in chrome

### ISSUE THREAD

**Issue by HiradNikoo** [photopea/photopea#94]
In chrome when you want to reopen the recent image it is not going to be opened. So when you open an image and then close it and try to reopen it again it is not possible. This is fixable if you recreate the fileupload again after each file opening.

**Comment by photopea** [comment]
It is fixed now. Thank you for reporting it! :)

BTW. Photopea does not perform any uploading. Everything happens inside a browser. After  photopea.com is loaded, you can disconnect from the internet and continue working.
