### ISSUE TITLE
I have to refresh every text layer so that it takes the right font size and family

### ISSUE THREAD

**Issue by anoltez** [photopea/photopea#947]
I have to refresh every text layer so that it takes the right font size and family.

**Comment by photopea** [comment]
Hi, so you are opening some existing file from your computer? Is it a PSD, a Sketch, an SVG, a PDF, or maybe some other file?

If it is a PSD, Photopea probably does not have a required font, so is uses another font to render the text. That is why your text looks differently after you try to change it.

**Comment by anoltez** [comment]
I'm uploading a PSD file. Indeed, that problem happens because Photopea did not have the sources that we are using. To resolve it, you must preload the font files in Photopea.

Problem solved! Thanks!

**Comment by photopea** [comment]
Ok, just drag-and-drop the necessary fonts (TTF, OTF) before opening your file. Photopea has a database of free fonts only, and it can not access fonts in your computer :(
