### ISSUE TITLE
Pen/stylus pressure

### ISSUE THREAD

**Issue by kevintey** [photopea/photopea#949]
Hey there,

Whilst drawing about with the brush tool using wacom tablet, it does support pen pressure which is great... but after drawing a couple of strokes, it hanged. Several tries with different browsers (Firefox & Chrome) and different operating system (Win & Mac) produced the same outcome.

On one occasion, it prompted the message that it doesn't have enough memory to process.

_p.s. Pen pressure only works with newer tablet models. I can't get mine (Intuos4 PTK840 circa2009) to work regardless of the driver, tablet setting, and browser setting._

Possible to look into this issue? 
Thanks!

**Comment by photopea** [comment]
Hi, what do you mean by "it hanged"? It became unresponsible?

Do you get to the same problem, when you draw the strokes with a mouse?

Photopea just reads the "pressure" property of the PointerEvent. It is up to browser to deliver the right value from the table to a web app. You should report it to the developers of your browser.

**Comment by kevintey** [comment]
Yeah the editor became unresponsive. Browser still functioning. And this usually happens after a couple of strokes.

Drawing with mouse don't have a problem at all, just that it wont have that natural stroke like how we draw using a real paint brush.

**Comment by photopea** [comment]
Hey, can you try it again now?

**Comment by kevintey** [comment]
Seems okay so far for both Mac and PC. Will buzz this thread if any other issue pops up. Thanks!

**Comment by photopea** [comment]
Hi, so wehn you draw, it always crashes the same way, showing you "Not enough RAM"? 

Could you run into this issue, if you drew everything the same way, but with a mouse?

**Comment by kevintey** [comment]
"Not enough RAM!" Doesn't always prompt on MAC (I managed to screen shot that message). In windows there isn't a prompt at all other than asking if want to 'Kill' or 'Wait' for the page to load. Most of the time I just close the whole tab or browser to restart.

Drawing with mouse don't have any issue. Only pen pressure enabled tablets will have issue. If I switch off the pressure mode on tablet, it won't have problem at all. But the strokes would not be as natural, which is a major setback among sketch artists, painters, etc.

![penpressure](https://user-images.githubusercontent.com/41601071/46337938-6d23f300-c661-11e8-934e-9ae0fb8935c6.jpg)
pen (with pressure) vs mouse

Hence I am guessing that the pen pressure setting is consuming a lot of browser memory.

**Comment by photopea** [comment]
Hi Kevin, Pressure settings should not consume any more memory, than with no pressure settings.

I updated Photopea a little. Now, if pressure is greater than 5, it will set it to 5 (in case the device gives us huge values, which could make Photopea crash).  Can you try it again?

**Comment by kevintey** [comment]
With your latest update, I could indeed draw a lot more strokes before it crashes. But it still does crash. 
The usual canvas size that I draw at is 1920 x 1080, and all the brush settings is default (0% smoothness 25% spacing). Also to stress test it I draw my strokes very fast some short some long (like how a sketch artist would).

Could it be that the pen pressure also affects the spacing? because with normal mouse, drawing with say... 10% spacing or less, usually will result in extreme lag and crash in the end.
e.g. try with large brush with 1% spacing.

**Comment by kevintey** [comment]
Again i tested with an A3 canvas, large brush with 1% spacing at 100% smoothness, although it lags, it is still able to draw and doesn't crash. :/

**Comment by photopea** [comment]
Yes, small spacing is very laggy, but it should not crash or use too much memory.

I updated it again. If the pressure is not a number, it should show you a message. Can you ever see such message?

**Comment by kevintey** [comment]
It's now a vast improvement over last version. It takes **a lot** of effort to make it crash (drawing on a3, high smoothness). But i don't see a message about the pressure number. 

All in all this version seems much more usable and less risk of crashing. I also noticed that the brush stroke are slightly less smooth (abit jagged) than previous version, but acceptable.

**Comment by photopea** [comment]
Hi, I think I found the problem and I fixed it. It should never crash again.

**Comment by kevintey** [comment]
Tested. Works great now. Thanks!
