### ISSUE TITLE
Ctrl + (+) & Ctrl + (-) don't work on Chromebook

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#95]
I now there was a related issue with this, but the difference here is that i do not have a numeric keyboard.

All chromebooks have this keyboard layout: http://cdn6.bigcommerce.com/s-blhknq8/product_images/images/chromebook_XE303C12_keyboard_key_replacement.jpg

Albeit some little additions for other languages.

So, i cannot use the combination. Maybe also accept: Ctrl + (=) for zoom in  and  Ctrl + (_) for zoom out?

If there is no other function that uses those combinations, of course.   :/

navigations gets a lot harder without this.

**Comment by photopea** [comment]
I am also having a very bad experience while using Photopea on Chrome OS. It has many default behaviors for some key combinations, which a webapp cannot prevent.

You can type + using Shift + (=). But when you press Ctrl + Shift + (=), it zooms the whole operating system!

Also, you can fast-switch to Zoom tool using Ctrl + Spacebar (+ Alt to switch zoom direction). But when you click with Alt button pressed, it is the right-click in Chrome OS.   https://bugs.chromium.org/p/chromium/issues/detail?id=168285

It seems like Chrome OS is the worst environment for webapps.

**Comment by photopea** [comment]
There are much more important problems in Chrome OS, than a shortcut for zooming.  We must make Google improve these things, or try to avoid Chrome OS completely.

Please let them know, how disappointed you are, in this forum: https://bugs.chromium.org/p/chromium/issues/detail?id=168285

**Comment by wernight** [comment]
You do know that Chrome OS users can almost only use Photopea for image editing?

**Comment by photopea** [comment]
@wernight  I hope there will be more webapps soon. But Chrome OS should really fix these bugs with keys etc.

BTW. does Ctrl and Plus / Minus work on chromebooks now? I sold my Chromebook :(

**Comment by avagp** [comment]
Let me tell you a tip for Chromebooks.

If you want to treat a web app like a web page, you have to open on a tab.
But if you want to treat it like a web app, you should open as a window.

That way you can use Ctrl key combos.

Alt key combos won't be used because is bounded to the mouse, because it
acts as a right click button. Not everyone uses the two finger tap.

To open an app as a window, go to settings, tools, add to shelf, open as
window.

:)

**Comment by wernight** [comment]
- Ctrl + (Shift) + +/- doesn't work as it resizes everything (as noted)
 - Ctrl + Alt + Click has bug (as noted and I'm looking at pushing the bug)
 - Ctrl + Space + Wheel normally allows to zoom but doesn't work on Chromebook
 - Two fingers pitch motion doesn't work (would only work on touch screens and touch not yet supported by Photopea)

So zooming is really a pain right now on Chromebooks.

**Comment by avagp** [comment]
I use pressing Z and then drag to the left and right. You told me that and
is super useful. For me I have no need of Ctrl+ I got used to my way.

But maybe this should be displayed somewhere when selecting the zoom tool.
It would be imposing to discover it by myself.

**Comment by photopea** [comment]
When you put your mouse cursor over some tool and keep it there for 1 second, the "bubble" should appear with the tool name and the key :)

**Comment by avagp** [comment]
But it doesn't say (as far as I know) that you can drag to.the left and
right to zoom in and out.

I meant to display that feature :)

**Comment by photopea** [comment]
You are right :) Such things will be covered at [photopea.com/learn](https://www.photopea.com/learn/).

**Comment by avagp** [comment]
You should add a button on the top displaying something like: "advanced
technics" which incite the user to click.

And that goes to /learn.

**Comment by wernight** [comment]
That Alt issue is being tackled by https://bugs.chromium.org/p/chromium/issues/detail?id=248762 which is likely going to be get fixed "sonnish".

**Comment by photopea** [comment]
It hasn't been fixed in 4 years, so I am pretty skeptical about it :(  

I would still discourage people from buying chromebooks, because Google forces you to use Chrome OS, without offering any simple way to choose between OSs.

**Comment by wernight** [comment]
@photopea You can quite easily install Crouton and put any OS on it (likely Linux). That being said, I think the power resides in using Chrome OS. You get the backup (just log in in any Chromebook), security (even airport security, cough China, could not install a bootloader or rootkit without factory reset and installing something like Crouton first), and I think it's a great OS.

Let's hope it gets fixed. :+1:

**Comment by wernight** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=248762#c133 is finally being done. Basically Alt+Click is mapped to Search+Click and then Alt+Click can be consumed by Photopea. 💛

**Comment by photopea** [comment]
@wernight Unbelievable, after six years :D

**Comment by avagp** [comment]
Yuju!

**Comment by wernight** [comment]
Noticing that this is behind the flag `chrome://flags/#use-search-click-for-right-click`

**Comment by avagp** [comment]
yes it is.

I have been using the last year

**Comment by photopea** [comment]
BTW. I have heard that Alt+Click should no longer work as a right-click in the latest update on Chromebooks. Am I correct?

**Comment by avagp** [comment]
Where did you read that???

**Comment by avagp** [comment]
It does! on m89
[image: image.png]

**Comment by wernight** [comment]
I think that the flag `chrome://flags/#use-search-click-for-right-click` is not yet enabled by default. Enabling this however disables Alt+Click as RightClick (you use Search+Click for that). So it actually frees the Alt+Click to be consumed by websites such as PP.

See also: https://www.androidpolice.com/2021/06/09/google-continues-its-assault-on-the-chromebook-alt-key/

**Comment by avagp** [comment]
Yes. It is not by default.

But if more people uses them, the more possibility they put the option on
the real settings
