### ISSUE TITLE
Copy to buffer

### ISSUE THREAD

**Issue by plohoj** [photopea/photopea#950]
I want to be able to save image to the buffer.

**Comment by photopea** [comment]
Hi, what do you mean by the buffer?

**Comment by plohoj** [comment]
Copy paste buffer (Ctrl+C, Ctrl+V)

**Comment by photopea** [comment]
You can copy from other applications into Photopea. But it is not possible to copy from Photopea elsewhere, because of missing web technologies :(  See https://www.photopea.com/browsershame/
