### ISSUE TITLE
Configure Curves, Hue/sat,  B&W by clicking into image

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#951]
The On-image adjustment tool found in these three adjustment layers is nice to have for quick targeting the range/area to be adjusted

**Comment by photopea** [comment]
Hi, what do you mean?

**Comment by hgs54371** [comment]
![](https://tinytutorials.files.wordpress.com/2011/04/screen-shot-2011-04-04-at-10-16-10-am.png)
The scrubber hand thing for click directly on image and drag to do range select and parameter change

**Comment by photopea** [comment]
Hi, it was implemented.
For Levels and Curves, you can choose the White, Grey and Black point by clicking into the image.

For Hue/Sat, you click-and-dragging into the image will change the saturation of the specific channel.
