### ISSUE TITLE
Gamma correction in exposure adj isn't at slider center by default

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#953]
Double click knob will set it to center, but that's not its default value

**Comment by photopea** [comment]
Ok it was fixed.

**Comment by hgs54371** [comment]
It's still on around 20% location

**Comment by photopea** [comment]
yes it is

**Comment by hgs54371** [comment]
![screen shot 2018-10-03 at 2 57 10 am](https://user-images.githubusercontent.com/36803688/46370389-0f6ec580-c6b8-11e8-98b8-6f1c1cdb4911.jpg)
Not at center as shown in pic

**Comment by photopea** [comment]
yes, I know about it, that is correct.
