### ISSUE TITLE
Resize selection

### ISSUE THREAD

**Issue by borekb** [photopea/photopea#956]
When I create a selection, I can move it but can't find a way to resize it. Is there a way to do it by dragging and dropping boundaries? Adding to selection feels cumbersome as my selection should have certain aspect ratio.

Thanks for an awesome tool!

**Comment by photopea** [comment]
Hi, sure, you can do Select - Transform selection. But note, that it transforms the selection "in a raster way". If you have an elliptical selection and spread it ten times, the contour will be blurry.

**Comment by KaKi87** [comment]
Hi,

What tool must be selected for this to work ?

For me it's not resizing the selected pixels, only the selection area

**Comment by photopea** [comment]
To transform the selected area of a layer, use Edit - Free Transform.

**Comment by KaKi87** [comment]
That works, thanks. Though, coming from Paint.NET, I find it a little cumbersome to have to open that menu and then hold `Shift` to not enforce aspect ratio, so I created a new thread about this : #8570

Thank you
