### ISSUE TITLE
Layer arrange

### ISSUE THREAD

**Issue by kevintey** [photopea/photopea#957]
Hi,
Can we introduce these function and shortcut keys?
Under Menu> Layer > Arrange >

Bring to Front: Ctrl + Shift + ]
Bring Forward: Ctrl + ]
Send Backward: Ctrl + [
Send to Back: Ctrl + Shift + [

It proves to be faster and more accurate than dragging when we are moving the layers arrangement. Should work with layer groups as well.

Thanks!

**Comment by photopea** [comment]
It was implemented. Thanks for suggesting it!
