### ISSUE TITLE
Layer opacity and brush opacity shortcut clash

### ISSUE THREAD

**Issue by kevintey** [photopea/photopea#958]
Hey there,

Currently, it's abit confusing when using the number keys on keyboard to set opacity of Layer and Brush. Both Layer opacity and brush opacity is reacting to the input. 
_i.e. If I press '2' on keyboard, Layer opacity and Brush opacity will be changed to 20% and 2% respectively at the same time._

Suggest to allow brush opacity to react to number input **only when** brush tool is selected; and similarly, to allow layer opacity to react to number input only when 'hand tool' or 'move tool' is selected.

Thanks!

**Comment by photopea** [comment]
It was fixed, thanks!
