### ISSUE TITLE
Bug: Blend mode drop down box

### ISSUE THREAD

**Issue by kevintey** [photopea/photopea#959]
Hello,
Discovered a bug on **Chrome browser** where by blend mode drop down box automatically closes after a few seconds (without making any selection).

It happens on Layer Style > Blending Options and also on Layers panel itself. 

Thanks for looking into it.

**Comment by photopea** [comment]
Hi, it never happened to me. My guess is, that this is a default behaviour of your OS, or some extension is causing it (e.g. the extension clicks somewhere for you).
