### ISSUE TITLE
Selections: Fast-switch between Add / Subtract with Shift / Alt

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#96]
We need to implement fast-switch between Add / Subtract with Shift / Alt

**Comment by photopea** [comment]
Done.

**Comment by avagp** [comment]
I know there are issues with chrome, but holding Alt and then clicking is not possible on chromebooks.

I don't know if you could detect the device so on chromebooks the Alt works more like a toggle than a press a hold option.

:/

**Comment by photopea** [comment]
Yes, Alt and click are not available to webapps : https://bugs.chromium.org/p/chromium/issues/detail?id=248762  I hope it will be resolved oneday.

You will have to switch it manually in the menu ... or do you propose any alternative solution?

**Comment by avagp** [comment]
At least for chromebooks... when i press Alt the option for the selected tool indeed changes. But if i click it gives me the right-click issue.

Maybe the Alt click should not be a key combo, but instead Alt button should be a function toggle.

For example on Zoom tool, if i press Alt, the zoom tool switches to zoom-out and stays that way. If i press Alt again it should change to zoom-in. That way i can have the Alt comfort :)

**Comment by photopea** [comment]
I see what you mean :)  One "click" of Alt would set the Alt ON, and another "click" would set the Alt OFF. But most of users are already familiar with a current way of how it works. It seems crazy to me to make different behavior for each browser.

I hope at some point, when we will have enough fans and supporters, we would be able to address media messages to browser developers, which would be cited my other media and increase the probability, that browser developers would take them seriously. Right now it seems, that Chrome developers ignore it.

**Comment by avagp** [comment]
Let's cross our fingers
