### ISSUE TITLE
Suggestion: Liquify filter background layer reveal

### ISSUE THREAD

**Issue by kevintey** [photopea/photopea#960]
Heya,
Is it possible to reveal and control the background layer's opacity when we are in the Liquify Filter window? 
It helps when we have to trace certain objects to match our 'liquification' to background image.

Thanks!

**Comment by photopea** [comment]
Hi, would you like that background to include the current layer (original state), like it does in Photoshop? Or only the layers behind it?

**Comment by kevintey** [comment]
Apologies. It should be:
Whatever is under our liquifying layer, with 1 click we can hide or reveal them, and that we can change the opacity of the layer we are liquifiying.

**Comment by photopea** [comment]
Hi, I think I implemented it. Check it out!
