### ISSUE TITLE
Can't transform layer that have Smart Object and mask on it

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#961]
When I try to transform smart object who have mask on it, Photopea show warning message "unlink mask before transforming Smart Object". Any type of transformation don't work. When I group that layer in a folder, I can transform folder who have Smart Object with a mask inside. For me, that is a bug. It should to be easy acces to transform all layer  (smart object and a mask).

**Comment by photopea** [comment]
Hi, I fixed it.

Note, that if there is a Warp transform on a Smart Object, you can not transform it together with a mask.
