### ISSUE TITLE
A way to show when there is more text in the paragraph text box

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#962]
For example:
I make a paragraph text rectangle (who have place for 5 lines of text). I copy and  paste some text, that have 7 lines. I don't see 2 lines more and havn't any informations about it. In Photoshop there is a little "+" in the right bottom corner of paragraph text rectangle.
I think that Photopea should have some  visual information about text that does not fit in paragraph dimensions.
- Plus sign like in PS (or) 
- Dashed bottom line instead full line (or)
- Three dots "..." under bottom line of paragraph bounds (or) 
- at the bottom (instead full line), triangle pattern vvvvvvvvv (like a scrap of paper)
- or even counting how many lines is't visible and showing under bounding box little +4 (+4 more/ +4 lines more) or something like that
- or any other idea :)

**Comment by photopea** [comment]
Ok, I added a little plus sign below the bottom right corner. Thanks!

**Comment by MichalSZZ** [comment]
For me, on retina display it is quite invisible... Plus sign is too litle (I will check that tommorow on monitor)
