### ISSUE TITLE
Lorem Ipsum generator

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#963]
It is "nice to have" feature. 
In web designing many times you have to fill text placeholders with some nice looking words.
Photoshop have build in that option.
In photopea at the start it can be a simple dummy lorem Ipsum text. But you can check sites (f.e. https://digital.com/blog/best-lorem-ipsum-generators/ ) that have many options to chose how to generate:
- how many words (f.e. min 15 max 40)
- how many paragraphs
- or even text variants (not only lorem ipsum). For example dummy business words ( http://officeipsum.com that is funny corpo generator ;) but there are normal variant too) etc.

In my work I use polish site http://lipsum.pl/co_to_jest_lorem_ipsum.html because it have many options and very important thing - polish words with accents (try to change select to "nowomowa" f.e.)

**Comment by photopea** [comment]
I think this could be a nice plugin for Photopea, but I would not put it into the main version, because only a small fraction of people would need it.

**Comment by MichalSZZ** [comment]
Ok I understand. Maybe you should remember about it in the future as a feature for the premium accounts? I pay for premium account but only as a thanks to you for such a great program :)
