### ISSUE TITLE
Create new artboards

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#964]
I see that now Photopea can open PSD with artboards (I don't see how to create new one).
Is in the future plan of developing Photopea, to add functionality to create new artboard and options to manage it? Like change dimensions etc.?

That is not "must to have". It is great now, when we have posibility to open PSD with artboards. But in the future... :)

I use artboards because f.e. it's easy to create (and show or edit) many formats of banners in one creative line at one PSD file.

**Comment by ezidio** [comment]
+1

**Comment by avagp** [comment]
+1000

**Comment by avagp** [comment]
Just to know if i wait or i send my file to the printer.

This will be develop soon?  :)

**Comment by avagp** [comment]
Any updates on this feature?

I kinda need it for my work  :0

**Comment by photopea** [comment]
Hi, I just implemented the Artboard Tool. it is "under" the Move tool. 

Artboard is a specific kind of a folder of layers, which has a rectangular "clipping mask" - only content within the rectangle is visible. Our PDF export represents PDF pages as artboards.

Use the Artboard tool to resize artboards or add new artboards. You can set the exact Artboard size in Window - Properties.

**Comment by MichalSZZ** [comment]
Thank you very much for that! I will test now and I will add new issues when something will be wrong.

**Comment by ORN-Fox** [comment]
A great addition for working with PDFs! Thanks for the work done!

**Comment by avagp** [comment]
Great i am so happy!

My works will be more organized!

What i am missing from this feature:
-Multiple pictures files download when exporting to PNG or JPG (on PDF it creates pages, which is fine)
-Alt+click with the artboard tool to duplicate artboard with its elements
-Drag an element too far away from the artboard that gets out of it (and it moves on top of the "folder" on the layers)
-A way to duplicate guides from one artboard to another (this is a huge improvement as itself, i don't know if Photoshop itself has kicked this issue, but i have found a lot of people begging for a feature like that. Illustrator has global guides and artboard guides)

**Comment by avagp** [comment]
Maybe a way to easily copy guides could be setting a relative guides (relative position within the artboard)
like this
![image](https://user-images.githubusercontent.com/11801254/108294238-3f796f00-7174-11eb-8496-aee482bc09bb.png)

but here
![image](https://user-images.githubusercontent.com/11801254/108294206-338dad00-7174-11eb-8bea-354dd82b8546.png)

**Comment by avagp** [comment]
Btw, the X an Y coordinates of the artboard here
![image](https://user-images.githubusercontent.com/11801254/108294643-01307f80-7175-11eb-9dc8-0970816735e9.png)

Does not change it measurement unit to the one on set on ruler units, i believe it should

**Comment by MichalSZZ** [comment]
Hi @avagp look on the issue list here on github. Yesterday I added 10 issueas with features and bugs. Some of yours are there. 
I forgot write about guides like in Photoshop and about export as (that is so so important). But here isn't a good place for that.
Please make new Issue and describe. It will be better organized in that way.

**Comment by MichalSZZ** [comment]
@avagp X and Y change the position of artboard and it works good yesterday when I tested that.
