### ISSUE TITLE
Exports to PDF moves texts

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#965]
I was working on a package today, and i noticed that when exporting the final document the exportation process moves some paths on the pdf.

![image](https://user-images.githubusercontent.com/11801254/46489883-ebf16b00-c7dc-11e8-9f0d-4e92384af1d6.png)

It may help to know that i am updating a .AI file.
For example, when open a .AI file the texts are paths, so i am rewriting them as text, that kind of stuff i mean when "updating" the file.

Here is the file:
[Caja-pdf.zip](https://github.com/photopea/photopea/files/2447339/Caja-pdf.zip)

**Comment by photopea** [comment]
Hi, Photopea is really bad at writing text into PDF at the moment. I recommend right-click the text layer and use "Convert to Shape", to convert characters into bézier curves. We should make it an option in Save for Web window, to do it automatically.
