### ISSUE TITLE
How to make a PSD link that directly open in Photopea? 

### ISSUE THREAD

**Issue by sonamdawa101** [photopea/photopea#966]
Photopea welcome screen with pea.psd and milk.sketch is very interesting. It is easy for anyone to open that exact psd file in Photopea.
    I am wondering if I want to this file http://www.sonamdawa.com/test/student.psd directly open in Photopea. How can I achive it. What additonal code i need to add in my link?
   Method for doing it manually for the time being is ok for us.

**Comment by photopea** [comment]
Hi, you can open an image from URL using File - Open from URL. Currently, we don't provide any storage for your files. But you can link Photopea with your Google Drive: https://www.youtube.com/watch?v=p7kjmwhlNrA

**Comment by sonamdawa101** [comment]
I have seen that option but that it not I want. I am looking something like this : URL with source file and photopea. I saw something like this in the image highlight.

I am note a coder but for example a URL that we can make up like;
www.photopea.com/?source=' http://www.sonamdawa.com/test/student.psd' action='open' *******

![capture](https://user-images.githubusercontent.com/36448436/46652030-75c77c80-cbbf-11e8-817e-ba6bc60a4476.PNG)

**Comment by photopea** [comment]
That is just a basic use of our API :)  You have to make a configuration JSON, and then, convert it to the URL. You can do it here:  https://www.photopea.com/api/playground

    {  "files": [  "https://www.photopea.com/api/img/pug.png" ]  }

    is converted to URL

    https://www.photopea.com#%7B%22files%22:%5B%22https://www.photopea.com/api/img/pug.png%22%5D%7D

Note, that your files have to be on HTTPS (not HTTP) and the CORS should be allowed.

**Comment by photopea** [comment]
We also have www.PSDfiddle.com , where you can store and share PSD files by the unique URL (like Imgur)
