### ISSUE TITLE
I LOVE PHOTOPEA and my suggestions

### ISSUE THREAD

**Issue by sonamdawa101** [photopea/photopea#967]
I really love photopea and the work and improvement you are doing. Most important, you give us prompt reply to our thousands of issues, which we feel we are connected with you !
      As we love photopea we want to photopea look more slick, compact and beautiful. Therefore I am making few suggestion hope I am not crossing your line. :-)

Suggestion 1: **Link at Top Right**
These are very important but "Info, Learn, Report a Bug, Blog, API, Twitter, Facebook" TOO MANY. TOO COLORFUL. Can we have better setting? I would suggestion if we can list them in and above Ads section?
**OR list as drop-down list under My Account as illustrated in the screenshot**? 
![account](https://user-images.githubusercontent.com/36448436/47150581-9943a300-d2f4-11e8-81c2-25def48412b8.png)

Suggestion 2: **Collapsible Ads**
We know Ads is very important for you. But very annoying for majority. Photopea working on tablet and phone is very very difficult. I am not asking to remove the Ads section. But given us option to collapse it to the right side could be better option.
      Recently I found few websites which very much identifcal to our photopea coming in the market with Zero Ads. I don't know how they will do but we can take a look and grasp some good ideas from them. But being your loyal fan, we love to stick to photopea with constant improvement.

![suggestion](https://user-images.githubusercontent.com/36448436/46650797-7f4ee580-cbbb-11e8-9695-344145c8b89f.png)

**Comment by sonamdawa101** [comment]
Photo libray: Good one

![capture](https://user-images.githubusercontent.com/36448436/46652812-d061d800-cbc1-11e8-8834-0450f7b313d5.PNG)

**Comment by photopea** [comment]
The Ads: There is usually third-party ad banner at this spot (the ad for Premium is displayed only to users with AdBlock). We get most of our money from ads, and I am afraid, that if we made them collapsible, our income would drop significantly :(

The colorful buttons: This space is empty anyway, so I think one-click bug report is better, than two-click bug report.

Templates: This is a great idea! But sadly, I don't know about any well-structured PSD templates, and I don't have enough time to make them myself :(

**Comment by sonamdawa101** [comment]
I truely understand regarding Ads. No problem. You can ignore this :-)

For the template you can ask users to submit their original template. Their name will be credited. You can make your community more interactive among themself to promote PHOTOPEA.

**Comment by photopea** [comment]
I really like the idea of Templates. Sites like Canva.com are very popular today. Basically, you start with a template and edit text, background, colors, add new objects etc.

We need good-quality templates, and in a good structure (separated by topics, resolutions, etc.). I have an idea to make an automatic generator of templates.

**Comment by flaneurette** [comment]
sonamdawa101 you can also buy photopea to remove ads. Only $9-$20.

**Comment by Shinhan** [comment]
> We can have user to submit PSD templates.

This would be a bad idea because you would quickly have lots of copyright infringement or photopea would have to spend lots of time of curating the templates in order to stop copyright infringing submissions.

**Comment by photopea** [comment]
Hi, I added auto-generated templates: https://blog.photopea.com/photopea-3-9-templates.html
