### ISSUE TITLE
Line Caps options not working

### ISSUE THREAD

**Issue by randalfien** [photopea/photopea#968]
When I draw lines as pixels, the caps options don't work, it always ends up being square.

**Comment by photopea** [comment]
The caps is related to line ends. I think you need to change the Corners value instead.

**Comment by randalfien** [comment]
![new project 3](https://user-images.githubusercontent.com/5365861/46668153-f0969480-cbcb-11e8-8c04-ea5c6aa36712.png)

I think it's really not working, checkout the screenshot. This is the result of caps round corners round

**Comment by photopea** [comment]
You have the stroke disabled on your shape (a white square with a red cross). Please, see "The Look" at https://www.photopea.com/learn/vg-structure

**Comment by randalfien** [comment]
So there's no way to have round endings using the pixels options?
this is the result with stroke set to 10
![new project 4](https://user-images.githubusercontent.com/5365861/46668495-e032e980-cbcc-11e8-9acc-03b216804012.png)

**Comment by randalfien** [comment]
Also the dots and dash don't work either

**Comment by photopea** [comment]
You are right, there is a bug, there is no Stroke when you draw "Pixels" .

**Comment by photopea** [comment]
So I just noticed, that the behaviour is the same in Adobe Photoshop. The "Pixels" mode draws a shape without any stroke, and filled with a foreground color.

To do what you wanted to do, draw a "Shape" instead of "Pixels", and then, right-click the layer and choose "Rasterize".
