### ISSUE TITLE
How to integrate Photopea API?

### ISSUE THREAD

**Issue by SatishDash20** [photopea/photopea#971]
I am trying to pass this image to photopea api for editing "http://www.converthink.com/public/images/analytics.png". How can i pass this image or how can i integrate photopea api into a project , will you please help me out, i am not getting proper idea from photopea/api please help me out.

**Comment by photopea** [comment]
Hi, you can try it on the Playground: https://www.photopea.com/api/playground , just rewrite the URL of the image with your own URL, and generate the URL of Photopea. 

Note, that your image has to be on HTTPS and the CORS has to be allowed. Learn how to use the web console, where errors are shown.

Please, read some articles about the Web and HTTP / HTML formats, to be able to understand the API. Or you can hire a programmer.
