### ISSUE TITLE
Renaming a file by d-clicking on the TAB

### ISSUE THREAD

**Issue by sonamdawa101** [photopea/photopea#973]
Option to rename the project file from the TAB is very convenient and desired addition. This would allow us to give a desired filename JUST BEFORE SAVING A PROJECT FILE or during the process stage.

This would act similar as renaming a layer in layer panel. :-)

![new project 2](https://user-images.githubusercontent.com/36448436/46727179-9a922180-cc9d-11e8-9dab-aa7f62e4e1bc.png)

**Comment by photopea** [comment]
It was implemented! :)

**Comment by sonamdawa101** [comment]
Wow ! WOW  ....... THANK YOU !
