### ISSUE TITLE
How to create SHAPE: rectangle with 5.5 by 8.5 inches 

### ISSUE THREAD

**Issue by sonamdawa101** [photopea/photopea#974]
I have backgroud sheet of 12 inches by 8.75 inches. Above this layer I want to create a rectangle shape of 5.5inch by 8.5inch. HOW TO DO THIS. 

![new project 1](https://user-images.githubusercontent.com/36448436/46729184-3faef900-cca2-11e8-99c6-a0bc1406a633.png)

**Comment by photopea** [comment]
Hi, the W and H values are in pixels. So multiply it by your DPI (8.5 inches x 300 dpi = 2550 pixels).

You can set the DPI to 100, so 1 inch = 100 pixels, it will be easier to compute. You can change the DPI later.

**Comment by sonamdawa101** [comment]
### Inches to Pixel Convertion Directly related to the chosen DPI
But is it possible to create an option to type **"5.5 in"** or **"5.5 inch"** in the width and height field do the convertion into pixel for us based on the chosen DPI? 

**I understood:** 
I have canvas size of 12 inches by 8.75 inches with **DPI 100**. 
In Pixel it will become: **Canvas = 1200px by 875 px**
![size](https://user-images.githubusercontent.com/36448436/46729941-65d59880-cca4-11e8-8f8c-b19f2af8e600.PNG)

So to create a Rectangle Shape of 5.5 inch by 8.5 inch
in Pixel it should be : **Shape = 550px by 850px**
![perfect](https://user-images.githubusercontent.com/36448436/46729965-771ea500-cca4-11e8-8539-d531a182ec43.PNG)
