### ISSUE TITLE
Alt+t instead of Ctrl+Alt+t for Tranform Shape

### ISSUE THREAD

**Issue by sonamdawa101** [photopea/photopea#975]
Alt+t is not assigned and can we have Alt+t  for Transform a shape instead for Ctrl+Alt+t . Or may be both :-)

**Comment by sonamdawa101** [comment]
Just for the transform shape keyboard shortcut can we have alt+t. 
**pressing 2 keys better than pressing 3 keys if when there is alternative.** 
If it is this way. NO PROBLEM :-)
I try to key in mind the Ctrl+Alt+t for shape transform but every then and now, mistakenly pressing 
Ctrl+t
Ctrl+Shift+t

**Comment by photopea** [comment]
We really need to use Ctrl+T (people are familiar with it from Adobe Photoshop and probably other programs). We will switch to it, as soon as browsers will let us to.

I think, that Ctrl+Alt+T  is "closer" to Ctrl+T in some sense, than Alt+T.
