### ISSUE TITLE
Desktop editor based on nwjs or electron

### ISSUE THREAD

**Issue by Greenplugin** [photopea/photopea#976]
Is it possible?
I can help porting this app to desktop and adding some functions possible only on the desktop.

**Comment by photopea** [comment]
Hi, browsers allow us to add an icon of Photopea to Homescreen, and it will start without the browser UI. Isn't it the same thing? What features do you have in mind?

**Comment by nkkollaw** [comment]
Please do this. Linux has been plagued with GIMP for way too long.

Electron can help dealing with the filesystem, cache, but honestly even an official wrapper that got updates would be awesome.

**Comment by photopea** [comment]
If you want the Offline functionality, we can not do that, since most of our income comes from advertisement, which does not work offline.

If you want to have an icon of Photopea on a desktop, and use it without the browser UI, it is possible through "Add to Homescreen" feature of your browser.

Please, be more precise about what you want.

**Comment by rolandixor** [comment]
> Please do this. Linux has been plagued with GIMP for way too long.
> 
> Electron can help dealing with the filesystem, cache, but honestly even an official wrapper that got updates would be awesome.

1. This app is not open source.
2. Linux has never been "plagued" with GIMP. That's rather uncalled for.

**Comment by JesusGod-Pope666-Info** [comment]
How is this app even on github if it is not open source.... false adviticing or something? Like I don't get it.
I had a nice portable version working years ago from someone, but someone apparently killed the guys project and also put a time bomb in the Photopea app in itself. Very nice..... Just wonderful. I tried to find an app for portable collection and though this was the thing, but clearly the programmer and his team do not want things like that. I hate GIMP, but at least it is free and can be found as portable option.

And the word free is misused so many times, if you have ads in your app, it is not free.

One thinking it was free and opensource, I don't know where that came from, but being on github kinda gives you that sense. So not sure what is going on with that.
