### ISSUE TITLE
Key shortcuts don't work the way they're supposed to, brush tool moves image instead of painting

### ISSUE THREAD

**Issue by remiiidesigns** [photopea/photopea#978]
Ctrl, x keys don't work like they're supposed to. They move the image and change opacity instead which really annoys me. Also, the brush tool acts like the pointer tool and moves the image instead of painting. I've restarted the program numerous times and the same issues keep popping up.

**Comment by photopea** [comment]
Hi, I just tried some shortcuts and the Brush tool, and everything works fine for me.

What exactly did you do?

**Comment by remiiidesigns** [comment]
I used the tools how I usually use them. I just changed brush size and
hardness and it didn’t have that circle. I dragged and it moved the image.
With the shortcuts, I use ctrl + x for lasso and when I hold ctrl, it
deselects. It also randomly changed opacity of the bit I select. This has
been going on for the past few days for me.

**Comment by photopea** [comment]
I just tried to change the brush size and the hardness, the cursor becomes square, but I can still draw. It does not move the image. Maybe you pressed the Ctrl or V accidentally, which switched you to the Move tool?

Ctrl + X usually cuts the selected area, so you could paste it elsewhere. It does not start the Lasso tool.

What OS and a browser do you have?

**Comment by remiiidesigns** [comment]
I have chrome os

**Comment by photopea** [comment]
Please, describe, what should I do, to make the Brush tool move the image.

**Comment by photopea** [comment]
I have to close it because of lack of details :(
