### ISSUE TITLE
Filter -> Distort -> Pinch work strange without make a selection

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#979]
When I try to make distortion for on image (without any selection), it make distortion only on a circa half of artboard.
Its happen on simple image layer and smart object too.

![istock-908468844 1](https://user-images.githubusercontent.com/38118273/46852350-fa520f00-cdfa-11e8-8d21-2b50068fd1e9.jpg)

**Comment by photopea** [comment]
Hey, I fixed it. Sorry for that :) Thanks!

**Comment by MichalSZZ** [comment]
No problem mf :)
I just trying all new features with distortion :)
