### ISSUE TITLE
Layer Mask: Toggle View and Apply 

### ISSUE THREAD

**Issue by kevintey** [photopea/photopea#980]
Hello,

Suggestions to enable a layer mask view, as that feature is very useful when doing some detailed masking  using the layer underneath as a trace.
In photoshop, pressing the ( \ )  backslash key will toggle an overlay fill (default: #ff0000 , opacity:50%) to see those areas that have been masked. 

Refer:
![mask02](https://user-images.githubusercontent.com/41601071/46858620-43778280-ce3e-11e8-8790-7ce617a2e36c.jpg)

When in the mask overlay mode, further pressing of the grave accent ( ` ) button will switch to a greyscale view (or a black and white map view). 

Refer:
![mask03](https://user-images.githubusercontent.com/41601071/46859218-c77e3a00-ce3f-11e8-8f37-6fba1d698688.jpg)

Again, it is useful when we want to see in detail the edges of our mask, or if we missed an area that we didn't mask, to name a few. Perhaps it can be included under Layer > Raster Mask > Toggle Overlay / Greyscale.

Secondly, since we have enable/disable raster mask and delete raster mask (when right click on layer mask thumbnail), it would be great to have 'Apply Raster Mask'. Layer > Raster Mask > Apply. 

What do you think?

Thanks.

**Comment by photopea** [comment]
Hi, it was implemented. Check if it works well.

**Comment by kevintey** [comment]
Hey there,

Thanks for this. I've tested and the mask works well. For next version, is it possible to select the **mask color**? Currently it's fixed as red.

> When in the mask overlay mode, further pressing of the grave accent ( ` ) button will switch to a greyscale view (or a black and white map view).

> Secondly, since we have enable/disable raster mask and delete raster mask (when right click on layer mask thumbnail), it would be great to have 'Apply Raster Mask'. Layer > Raster Mask > Apply.

 Also asking if the above 2 ideas are possible?

**Comment by photopea** [comment]
Hi, I implemented the "red mask view" using a little trick, which currently lets us only use colors, for which the Green component is equal to Blue. 

I implemented the Apply Mask and Grave shortcut.

**Comment by MichalSZZ** [comment]
![obraz](https://user-images.githubusercontent.com/38118273/47705463-ef82e100-dc26-11e8-8dc7-5abc09bcc3c7.png)

One info:
On European macbook keyboard, in this place, where should to be ( ` ) button, is ( § ) but works good with this key. ( ` ) on european macbook keyboard (it is between left Shift and Z) turn red mask on/off.
On external (logitech) keyboard i have ( ` ) but when i press it, it's typing § :) (both buttons switch black and white mask good - I just want to put information about differences on Mac)

**Comment by photopea** [comment]
Hi, Photopea detect keys by their "key codes". Go here, click into the bottom right area and press any keys, to see their key code: http://jsfiddle.net/p45f44zb/14/

Let me know, what key codes should make the mask view red, and what codes should make it black :)

**Comment by kevintey** [comment]
That grave accent shortcut is sort of a image retouching industry trick. When doing complex and super detailed masking, one would need quickly change view modes and having that shortcut does give an extra edge in terms of speed.

In terms of the buttons I m not too familiar with European kb layout... Just assumed that all kb should have that grave accent besides number 1, mac and win alike. haha..
