### ISSUE TITLE
After working on an image for sometime, top menu is not at all working. Not able to save the work I did. Ctrl+S doesn't work anyways. So entire work is getting wasted. Happened to me many times.

### ISSUE THREAD

**Issue by Raghuveer999** [photopea/photopea#981]
Steps: File -> New Image -> Select Size -> Shape Tool -> Ellipse Shape and then try to save.. and then BOOM.. nothing works.. Not able to save the work..

**Comment by photopea** [comment]
Can you find some steps, that would always reproduce it? Without being able to reproduce it, we can not find the cause to fix it :(

**Comment by Raghuveer999** [comment]
> Can you find some steps, that would always reproduce it? Without being able to reproduce it, we can not find the cause to fix it :(

Added Steps now.. Please check..

**Comment by photopea** [comment]
Hi, I created a new document (default size), then used the Ellipse tool to draw an ellipse (red vector shape). Then, I pressed File - Save as PSD. The PSD was sucessfully saved. 

Did I miss anything?

**Comment by mlunadia** [comment]
Same thing happening over here, quite frustrating as you lose everything... :(

After using cropping tool, top menu stops working and cant save anything.

**Comment by photopea** [comment]
Have you been logged-in into Photopea, when it happened (through the Account button) ?

**Comment by photopea** [comment]
I think it was a case of a bug, such that the top menu did not work, when no layer was selected. We fixed this bug.

**Comment by saqikawaay** [comment]
Hey I'm also having problems with the top menu bar. I noticed that if I went to full-screen on Chrome it seems to start working again.

**Comment by saqikawaay** [comment]
Suddenly I can't reproduce this now. I'll be using it again tomorrow long
term, if I run into it I'll inspect and see what I can find. Thanks

**Comment by photopea** [comment]
Amazing, thank you in advance!
