### ISSUE TITLE
CMYK?

### ISSUE THREAD

**Issue by ByAnonimaSexy** [photopea/photopea#982]
soy amateur en el tema del diseño gráfico, hice unas tarjetas de presentación y me pidieron que guardara en CMYK y no veo esa opción en PHOTOPEA.
Realmente necesito ayuda en este tema ya que la mayoría de mis diseños son para imprimir en formato offset

**Comment by photopea** [comment]
Hi, Photopea uses sRGB color space. The printer company should be able to convert your image from sRGB into the color space of their printer.
