### ISSUE TITLE
PINCELES?

### ISSUE THREAD

**Issue by ByAnonimaSexy** [photopea/photopea#983]
Sugerencia... necesitamos una mayor variedad de pinceles para utilizar en nuestros diseños por favor 
y la opción CMYK
![captura 1](https://user-images.githubusercontent.com/42881223/46899873-cad4ee00-ce5e-11e8-8313-24290c73dbf7.png)

**Comment by photopea** [comment]
Hi, you can find the brushes on the internet (.ABR files), and load them into Photopea.
