### ISSUE TITLE
Top menu bar stops working, cannot save, export...all work lost

### ISSUE THREAD

**Issue by mlunadia** [photopea/photopea#984]
Top bar menu stops working and all work is lost.

Not sure which operation is triggering it but the only top bar tool I'm using has been image cropping.

I can see I'm not the only one with this problem now but for different reasons

**Comment by photopea** [comment]
Hi @mlunadia , I heard about it several times and it really makes me sad, since it never happened to me, so I don't know what could be the problem :(

Could you please try to do what you did again, and find some precise steps, that always lead to this problem? I have to able to reproduce the problem, in order to fix it.

**Comment by mlunadia** [comment]
Hey, @photopea thanks for coming back so quick!

It's difficult to confirm exactly what seems to be the cause. I'm working on chrome.

Initially I thought it was the use of the crop tool so decided to opt for cropping once exported but the menu froze since. 

You still can hover over it and it animates but doesnt drop down and nothing happens if you click on it. 

not sure if you can check the log your end of what I've been working on if I send you my account details on a dm.

**Comment by mlunadia** [comment]
I've got it to work. For some reason when layers become de-selected the menu stops working. 

You have to re-select a layer and this gets it back to working.

**Comment by photopea** [comment]
Yes, you are right! The top menus really did not work, when no layer was selected.

I fixed it. Everything should work even when no layer is selected. Thank you very much!
