### ISSUE TITLE
BUG in filter -> render -> "clouds" and "difference clouds"

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#985]
It worked in the past as I remember. Now, I think after add new one (difference clouds) results of both filters looks like in the screenshot.

![new project](https://user-images.githubusercontent.com/38118273/46909908-bcf49b00-cf3a-11e8-896b-3bccbe69a455.jpg)

FF and Chrome on Mac OS

**Comment by photopea** [comment]
Hi, there was a very stupid bug. I am very sorry. It is fixed now. Thanks!
