### ISSUE TITLE
Rotate cursor is missing when transforming the object

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#986]
I saw it several times on my students laptops (Windows OS and FF as I remember). 
For me it is not a problem because I know how that sholud to work, but begginers realy need to see this cursor, to be sure what they do.
When I show them, how to rotate objects without seeing cursor (place a little bit outside of transform rectangle) it works well.

Do you have heard about this problem from somebody else?

**Comment by photopea** [comment]
Hi, we use the same cursor for this, as for the brush tool. Does the brush tool work well in such case?

**Comment by photopea** [comment]
Try to update a browser first.

**Comment by MichalSZZ** [comment]
Ok, but can you wait for the answer (and don't close issue) until wednesday? I must consult that with my students.
 Thx.

**Comment by MichalSZZ** [comment]
OK, you can close this issue.
I have asked about system and browser, (it was windows 10 and newest Chrome), but girl who had that problem said, that situation wasn't repeated to her after our last lesson.

**Comment by photopea** [comment]
ok
