### ISSUE TITLE
Text Jumps Downward When Clicking Inside a Text Box  (with fonts loaded)

### ISSUE THREAD

**Issue by AmayaAnzai** [photopea/photopea#988]
Hello,    After loading a PSD file & all the fonts necessary into Photopea, when I click inside a text-box with the type tool, the text & text box jumps downward about 10 pixels.  I have loaded all the necessary fonts. Strangely enough,  I tried this same file on Photopea about 2 weeks ago & everything was working fine then.

I also did another test with a PSD using text lines instead of text boxes, and although the vertical placement remained the same, the tracking of the font changed when clicking on the text with the Type Tool. I really hope there is a way to fix this!     Thank You

**Comment by photopea** [comment]
Hi Amaya, we did not change the Text tool in months, so it probably always worked the same way, as it does now. 

Could oyu send me your PSD and necessary fonts to support@photopea.com ?

**Comment by AmayaAnzai** [comment]
Wow, such a quick response time. Yes this file & these fonts work fine now
via Photopea. Thank you. Unfortunately, many other fonts I try with other
files still have the same text-jumping issue, so I won't be able to rely on
Photopea yet as a place to send my customers to open PSDs by themselves &
edit their own invitations. Anyway, what I'm saying is your company could
make millions if it setup Photopea to work the way Templett.com or a
similar site that allows for DIY invitations & graphic design files. If
Your program would allow customers to customize their files to a degree far
greater than any other online platform is offering, and be able to do some
really cool gold-foil overlay techniques. Anyway, just saying!   Thanks a
bunch!

**Comment by photopea** [comment]
Please, send us the other files and fonts, which do not work! We tested it with several PSDs, and the text never jumps anywhere.

We rely heavily on users reporting problems to us.
