### ISSUE TITLE
Create new document with dimensions of copied image to clipboard

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#989]
1. Copy image to clipboard (from other tab in Photopea or program or browser etc.)
2. Create new document (Ctrl + N) in Photopea
3. By default in this situation, width and height sholud be set to W and H of image from clipboard

That behavior is very helpfull in PS for me.

**Comment by photopea** [comment]
This request has been reported multiple times (I think that maybe even by you, too). Sadly, web apps can not read the clipboard before it is pasted into them. 

But if you make a selection in Photopea, the New Project window has the dimension of that selection.

**Comment by MichalSZZ** [comment]
Sorry, my fault. I should look for it, before I asked the question :(

**Comment by smoli** [comment]
Maybe when in the "Create New" Dialog provide the option to paste an image there to create a new image with the right dimensions and the image already pasted to the background layer.

Right now, when in the Create New Dialog a paste works on the document that is already open.

**Comment by photopea** [comment]
@smoli That sounds like a great featue! I am just not sure if people would figure out, that they can paste the document into a New Project window.

**Comment by smoli** [comment]
You could provide an area in the Dialog "paste your image here to create a new document from clipboard".

I'd say 70% of the time I create something new in PS I do it based on the contents of the clipboard. It's super usefull, especially when doing some quick and dirty stuff just to try something out.

I made a quick suggestion (using photopea, and it would've been awesome if I didn't need to save the screenshot first):
![grafik](https://user-images.githubusercontent.com/1009634/48136786-d02c2980-e2a0-11e8-8122-14056ad5d938.png)

**Comment by photopea** [comment]
To make it clear: You can paste an image from a clipboard into Photopea any time! If no documents are opened, it will create a new document. Otherwise, it will paste into a current document.

Maybe we could just show the pop-up menu after each Paste, asking, where you want to place the new image?

**Comment by smoli** [comment]
Oh, I didn't know that. That is definetely useful. But unfortunately it only works when no document is open. So to me availability of the functionality seems very limited. I can see having photopea open in a browser tab the whole day.

The popup after each paste could be pestering users that want to paste alot into the current document. 

Tying it semantically to "I want to create a new document" seems to be the cleanest way for me.

**Comment by photopea** [comment]
It is like a difference between File - Open and File - Open and Place

**Comment by positron96** [comment]
Hi. I would like to have this feature too. I also frequently have an open document in photopea, so I cannot use the existing feature of creating new document from clipboard when there is no open document.
Right now when you have "New project" dialog open, pressing Ctrl+V pastes an image into existing document (behind the dialog). How about when user pastes image with "New project" dialog opened, create a new one instead? This way a limitation of web apps mentioned above will not be triggered.
