### ISSUE TITLE
Proper units after switching units to diferent than pixels

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#990]
Now, when we change units (on ruler or create new document for print), only rulers show dimensions (in cm for example).
Info palette should show X and Y or W and H in choosen units when we: 

- drag new guide
- make new shape or selection
- make cropping area
- transform objects

Another thing corresponding with this functionality is ability to set X, Y, W, H (everywhere, where that parameters have input to set it manually) in units like 10 cm, 100 mm, 10 in etc.

In photoshop it works even with font size, corner radius, stroke width etc.
When I set for example font size to 2cm, Photoshop change size and recalculate units and show proper for font (in points) 56,69 pt.

Why I asking for that? I see on Photopea github, that users use it for projects for print.
For example. When printing house give to graphic designer guidelines how to proper make projects (bleeds, safe area or minimum elements size that look good and is visible on printing materials) - they use mm, cm or inches.

You can cut this issue to few smaller one if you dont want to make everything as I described :) First part of my issue is most important for me.

**Comment by photopea** [comment]
Hi, I adapted the Info panel - it shows numbers in the Ruler units. The width / height also shows the correct data during the Free Transform.

I see, that you can enter the text size (and some other values) with the "cm" (etc) at the end, and it will be converted to Pixels. But I am a bit lazy to do it, so let's wait until someone else suggests it :)

**Comment by MichalSZZ** [comment]
Thank you for that update!

> so let's wait until someone else suggests it :)

can we check in the past (6 days ago) this? :)
#974 

@sonamdawa101 have asked how to "create a rectangle shape of 5.5inch by 8.5inch." 
With entering values in W and H + "in" or "cm"/"mm" + "fixed size" option, we can solve that problem. 

BTW. text size, corner radius and stroke size was only a curiosity, I have never use that option before in Photoshop ;). But entering values in inches/cm to create or transform object is important.
