### ISSUE TITLE
Layer Blend Mode (Live Preview)

### ISSUE THREAD

**Issue by kevintey** [photopea/photopea#991]
Heya,

I'm wondering if we can have a real time preview of what the layer blend modes will look like, by simply mouse over it (without selecting it and collapsing the blend mode drop down box) ?

It's easier for users to cycle through the blend modes, without taking space at the history tab.

Thanks!

**Comment by photopea** [comment]
Hi Kevin,

I also watched a video about a new Photoshop CC with this feature :D  We use the "native" dropdown menu of a browser, which does not let us detect the mouse over the menu items. Creating a custom menu would probably be too complicated. 

But once you give a focus to that button, most of browsers let you switch items with arrow keys.
