### ISSUE TITLE
Not able to edit text in layer

### ISSUE THREAD

**Issue by steve178** [photopea/photopea#995]
Hi, looking for help as to why I am unable to edit the text in the layer of my PSD file in Photopea.

Any help is greatly appreciated. 

![d1 4 1](https://user-images.githubusercontent.com/44235819/47093435-2ef90880-d1f7-11e8-899b-a13ab59a9042.png)

**Comment by photopea** [comment]
Hi Steve, could you please send your PSD to support@photopea.com ?

**Comment by photopea** [comment]
I have to close it because of lack of details :(
