### ISSUE TITLE
Crop tool - showing layers, bigger than canvas size, when cropping outside of canvas

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#996]
Many times I use crop tool (in PS) to easy change canvas size of my project.
Now (in Photopea), I don't know how far I should to resize, bacause don't see layers (who are bigger that canvas size).

**Comment by photopea** [comment]
I am afraid that would be pretty hard to implement in a current Photopea :(  I recommend to use the Total Content button at the top.
