### ISSUE TITLE
Rotate layer with ruler tool

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#999]
For example:
I have photo with not ideal horizon line. I want to rotate it, but dont know whitch angle is good. 
Now in Photopea I must do that more or less precise with rotate in free transform.

I'm looking for a method, how can I easily do that in Photopea.
In Photoshop it can be done with 2 ways:

1. Creating line using ruler tool on horizon and clicking option in tool menu "straighten layer"
2. Creating line using ruler tool on horizon and using edit -> transform -> rotate (it that not exist in Photopea now). It make oposite direction of rotate (in PS), but can be fast fix by changing - to + in angle field.
3. Cropping tool have straighten option too, but it is not the point of this issue.

**Comment by photopea** [comment]
Hi, I added the first option: Straighten Layer button for the Ruler.

Previously, you could measure the angle with the Ruler (shown at the top), and enter that angle during the Free Transform. Or you could add a horizontal guide, and rotate the layer until the horizon is parallel to that guide.

**Comment by MichalSZZ** [comment]
Thx. :+1:
